### ISSUE TITLE
If you're trying to register but can't contact the default HS, the UX doesn't make it very clear how to proceed.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10003]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/1922197/59196000-669d3200-8b85-11e9-92cf-b48842f9ce1c.png">
The spinner just spins; if you want to register _somewhere_ your best bet is to click 'advanced', but that isn't obvious.

**Comment by turt2live** [comment]
copy:
**Cannot reach identity server**
You can log in, but some features will be unavailable until the identity server is back online. If you keep seeing this warning, check your configuration or contact a server admin.

Orange: #ff8d13

Treat as warning, do not prevent login for this error.

**Comment by turt2live** [comment]
ftr, this spinner is better than the UX it is hiding from you. If we can't reach the homeserver, we can't render an accurate registration page because we don't know what the server supports.

**Comment by turt2live** [comment]
We fixed this:
![image](https://user-images.githubusercontent.com/1190097/60372042-7ce62300-99b8-11e9-86c5-dc505856c2fe.png)
