### ISSUE TITLE
Can‘t reset password

### ISSUE THREAD

**Issue by KoB-Kirito** [vector-im/riot-web#10009]
### Description

I got logged out of riot and can‘t login anymore.
I tried to reset the password, but it says the e-mail is unknown. I got mails from riot on that e-mail, so I‘m sure it is right.
Where can I get help for my account?

### Steps to reproduce

- Click Reset password
- Enter mail and new password

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox (The newest stable), Safari on iOS
- **OS**: Windows, iOS
- **URL**: riot.im/app

**Comment by jryans** [comment]
Thank you for filing this issue. Unfortunately, we can't help with account issues like this here. You should contact the admin for your homeserver. If that is matrix.org, you can email support@matrix.org about this.
