### ISSUE TITLE
**Cannot reach homeserver** message appears when it's the identity server you can't reach

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10002]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/1922197/59193403-7e70b800-8b7d-11e9-98ec-d54bf2c6f1a6.png">

We get this message even if it's the IS not the HS that cannot be reached.

- The error message should be accurate (not least because the purpose of fail fast is to help people who've misconfigured their riot instance)
- I don't think we should stop users from logging in when the IS is down. The reasons I think this are:
    - the IS is not required for login
    - the IS is not required for a lot of daily use of the HS
    - we _should_ expose IS as a user-configurable option, but login time is not a sensible place for this (what's so special about login?)
    - we _should_ handle IS failures within the app, warning users and/or blocking features if they can't work when the IS is unavailable
    - the IS should be a user config option like any other (with the default coming from the riot instance used for registration, if the user doesn't override this default at registration time)

However, at this stage my desire not to block login on the IS availability check is predicated on our exposing IS as a user config option and defending against misconfiguration within the app. Since this hasn't been done (and is non-trivial), and until it is done we have no other way to validate the choice of IS, nor do we have much confidence that the app would robustly handle an absent or misconfigured IS at "runtime", I don't suggest that we block the release on this.

Registration is another matter entirely - I do think we should stop users from registering when the IS is down, and we should report this error and what users should do to fix it.

**Comment by lampholder** [comment]
Thinking about this more - we never used to validate the IS at any point, so blocking login on the client's ability to access the IS directly does seem overkill.

As I waffled above, I do think we should tell users when the IS their account is configured to use is not responding correctly, but I don't think it's appropriate to block login - I think for any given login attempt it is _much_ more likely that `vector.im` is having difficulties than the Riot instance admin has put the wrong value in `config.json`.

**Comment by turt2live** [comment]
copy:
**Cannot reach identity server**
You can log in, but some features will be unavailable until the identity server is back online. If you keep seeing this warning, check your configuration or contact a server admin.

Orange: #ff8d13

Treat as warning, do not prevent login for this error.
