### ISSUE TITLE
reply/reactions buttons missing for one message

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#10000]
I have no real idea why this one event is missing the knobs

**Comment by richvdh** [comment]
![image](https://user-images.githubusercontent.com/1389908/59190588-00101800-8b75-11e9-9e59-42a992e140fa.png)

**Comment by richvdh** [comment]
(the message in question is a reply to me, obvs)

**Comment by jryans** [comment]
Sounds similar to #9991 with messages that we weren't initially able to decrypt, but unsure if it's the same root cause.

**Comment by richvdh** [comment]
sounds plausible

**Comment by jryans** [comment]
I found a reproduction path for this and based on that it seems like a duplicate of #9991.
