### ISSUE TITLE
Entering a full MXID on login makes the spinner spin indefinitely

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10014]
From @lampholder:

Entering a full mxid (such as @test.user.0392809438934:matrix.org) makes the spinner spin indefinitely with no obvious noise in the console/networking tab

**Comment by jryans** [comment]
This issue only occurs if you use a full MXID that resolves to the same HS as Riot's default HS.

**Comment by turt2live** [comment]
> This issue only occurs if you use a full MXID that resolves to the same HS as Riot's default HS.

![giphy (1)](https://user-images.githubusercontent.com/1190097/59279598-71a5a000-8c21-11e9-8cb8-d006600edc2a.gif)
