### ISSUE TITLE
Tooltip that shows real HS for domain flickers on screen momentarily

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10015]
Steps to reproduce:

1. Go to https://riot.im/develop/#/login
2. Enter @test.user:lant.uk
3. Observe the tooltip with HS details that will be shown when hovering the "on lant.uk" header text briefly appears on screen, then hides until you hover

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/14597
