### ISSUE TITLE
If the IS isn't available, the message says you can register but you can't (the `register` button is disabled)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10018]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/1922197/59285596-219cfc80-8c66-11e9-864a-d636b44b1b72.png">

**Comment by lampholder** [comment]
Also if the IS comes back online whilst you're on this page of registration, nothing detects that it's come back so you're stuck at this stage.

**Comment by turt2live** [comment]
> Also if the IS comes back online whilst you're on this page of registration, nothing detects that it's come back so you're stuck at this stage.

Expectation is that you can click the register button, and it re-checks the IS being alive. That's conditional on the bug where you can't click the button.

**Comment by lampholder** [comment]
This replaces the existing behaviour, which when you try and register without the client's being able to access the identity server, you get this:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1922197/59286407-94f33e00-8c67-11e9-9018-b7952407d190.png">

**Comment by lampholder** [comment]
Presumably, if your client can't reach the identity server at registration time:
- you could register with just a mxid
- you can't register with an email address (because this relies on the IS being contactable by the client)

The simplest change might be to disable registration when vector.im identity server is down, but I _really don't like this_ since it would break registration even for users who weren't registering with an email address, on matrix.org and on other homeservers which also use the vector.im identity server (which is lots of them).

**Comment by turt2live** [comment]
@lampholder to reiterate: the expected behaviour is that you can click the button. If you enter an email address despite the warning, the code should give you a friendly error saying "lolnope". Basically: it should work, and we should have the same error handling on clicking the button regardless of liveliness checks because it's possible the IS died or hates your email in the middle of your attempt.

**Comment by lampholder** [comment]
Oh, okay - cool, thanks.
