### ISSUE TITLE
If the IS is down, you can't change your HS from the default

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10016]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/1922197/59281093-9bc98300-8c5e-11e9-8722-77783c4716e6.png">

Relatively niche. To repro:
- block your client's access to https://vector.im
- go to riot.im/develop
- try and change the homeserver to something not matrix.org

**Comment by turt2live** [comment]
I love it when we have conflicting errors and warnings
