### ISSUE TITLE
Captcha did not load in Firefox when registering

### ISSUE THREAD

**Issue by snapdeus** [vector-im/riot-web#10027]
### Description

No captcha loaded with firefox, when trying to register

### Steps to reproduce

- Tried to register with firefox.
- captcha wouldn't load in the page, so I couldn't proceed
- got about a billion email verification tokens
- disabled adblockers and trackerblockers, still no
- tried chrome
- captcha loaded

__________________________________

captcha didn't load in firefox:
![H8qasvN](https://user-images.githubusercontent.com/44621390/59363355-06cc9580-8d03-11e9-92c0-8b311d7d87e3.png)

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: FIREFOX
- **OS**: WINDOWS 10 PRO
- **URL**: riot.im

**Comment by jryans** [comment]
The matrix.org homeserver currently uses Google's ReCaptcha system. Is it being blocked an add-on? If you don't want to allow this, you can also look for other homeservers at https://matrixservers.net/servers/ or run your own.

**Comment by jryans** [comment]
Ah hmm, I see you disabled blocking add-ons... 😅

**Comment by jryans** [comment]
Any errors in the page console?

**Comment by snapdeus** [comment]
Hey,

Sorry - I edited the initial post to include that I tried again in Firefox with my adblocker/trackerblockers disabled as well - 

no, nothing came up in the console: 
![image](https://user-images.githubusercontent.com/44621390/59364435-d685f680-8d04-11e9-83b7-17eedb3a3cd5.png)

**Comment by snapdeus** [comment]
oooh, wait, I clicked on Reset filters, as shown in the picture in the upper right of the console. 

I found this:

"The resource at “https://www.recaptcha.net/recaptcha/api.js?onload=mx_on_recaptcha_loaded&render=explicit” was blocked because content blocking is enabled."

This is a content blocking setting native to firefox - 
most likely one of these settings:
![image](https://user-images.githubusercontent.com/44621390/59364662-34b2d980-8d05-11e9-88b5-6bc91db77454.png)


thanks for your help, closing now...

**Comment by jryans** [comment]
Aha, great, I'm glad we figured out the cause. I think most agree that Google's ReCaptcha is not ideal here. See https://github.com/vector-im/riot-web/issues/3606 for discussion of alternatives.
