### ISSUE TITLE
If the default HS is down, you can't register on a different HS because the `Register` button is never re-enabled.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10029]
😭
<img width="719" alt="image" src="https://user-images.githubusercontent.com/1922197/59365962-5e81f580-8d31-11e9-8128-a6eeb02253e1.png">

As an aside, our disabled register button still turns the mouse pointer to cursor (or do I mean cursor to pointer) - either way, it turns it into a link-clicky hand when you hover over the button, which I think isn't right :\

**Comment by dbkr** [comment]
Also if your default HS is not matrix.org, you can't change it anyway because all the UI disappears:

<img width="720" alt="Screenshot 2019-06-17 at 15 52 04" src="https://user-images.githubusercontent.com/986903/59614074-f019aa80-9117-11e9-86a7-2209031f4224.png">
