### ISSUE TITLE
CTRL+backtick doesn't work for top left menu

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10031]
At least on Windows

**Comment by t3chguy** [comment]
That is very strange, Web or Desktop?
I wrote and tested the change on Windows (Web)

**Comment by turt2live** [comment]
web, I'm mashing CTRL+` and getting nothing

**Comment by t3chguy** [comment]
Tried even with both CTRL's and both are happy on riot.im/develop
Though /app is still on CTRL+I

**Comment by t3chguy** [comment]
Turns out it is a disagreement on the keyCode for backtick, 192 vs 223 (chrome only it seems)
It might be a UK-keyboard specific thing, either way switching to `.key` is suggested anyways due to keyCode deprecation
