### ISSUE TITLE
Canonical issue for message stuck as latest message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10032]
There's been more instances of this recently. See linked rageshakes.

See also:
* https://github.com/vector-im/riot-web/issues/9894
* https://github.com/matrix-org/riot-web-rageshakes/issues/1564

**Comment by turt2live** [comment]
My current theory (with no evidence) is that our timeline splicing magic is splicing things in the wrong order, causing a non-live timeline in the front which happens to have a single message.

**Comment by Biep** [comment]
A double example:
https://matrix.to/#/!jIkxpZVHbomQzbUTua:matrix.org/$s_kH7e4MX8_mG4oTf1pHmladWI5BbKAeavO64iHYzdQ?via=matrix.org&via=privacytools.io&via=1312.media
and
https://matrix.to/#/!jIkxpZVHbomQzbUTua:matrix.org/$adot7JtGQkQk14XsghRUZK-jUvyD2ZKkTdXpUy_EogM?via=matrix.org&via=privacytools.io&via=1312.media

**Comment by ara4n** [comment]
I've had this ~4 times today.

**Comment by taw00** [comment]
That "Testing 1.5.15" should be right after the "Build 1.5.15 RPMs" message. Alas. :)

![Screenshot from 2020-04-01 15-32-29](https://user-images.githubusercontent.com/6908872/78180004-1e127600-7430-11ea-8d66-b33ffd61c1ef.png)

**Comment by Biep** [comment]
I also have a stuck "X is writing", which stays at the bottom.  Very confusing.  It has been there basically as long as the two messages above, so the same logs would apply.

**Comment by turt2live** [comment]
@Biep that is an entirely different problem.

**Comment by Biep** [comment]
Oh, I see.  For the layman it looks the same: a message stuck at the bottom of the timeline.
Anyway - those logs would still apply.
Emptying the cache solved both problems.

**Comment by turt2live** [comment]
We're suspecting the latest resurgence of this is happening in Synapse and not in Riot. Once fixed, please leave this issue open as there's still some legitimate cases of Riot screwing it up.

**Comment by turt2live** [comment]
The Synapse team is identifying the recent cause for this (looks to be something with sync streams). Taking off our board as there's nothing for us to do as a client team yet.

**Comment by turt2live** [comment]
Latest bunch of this moved to https://github.com/matrix-org/synapse/issues/7206

**Comment by Biep** [comment]
Yet - reloading the cache solves the problem.

**Comment by turt2live** [comment]
Yup, that's the recommended temporary fix.

**Comment by t3chguy** [comment]
> Yet - reloading the cache solves the problem.

Yes, because synapse sends the right thing on initial syncs but misses events on regular syncs.

**Comment by ara4n** [comment]
the most recent instances of this seem to be https://github.com/vector-im/riot-web/issues/1541

**Comment by turt2live** [comment]
We appear to have this tracked on other issues, and at this point we don't need a firepit of issues anymore. We did at the time due to the huge volume of reports, but since May 4th this appears fixed enough for it to not be a concern.
