### ISSUE TITLE
Recent rooms-view doesn't work correctly when moving to an upgraded room

### ISSUE THREAD

**Issue by eras** [vector-im/riot-web#10035]
### Description

When a channel (Synapse Admins) was updated from v1->v5, a button at the bottom appeared allowing me to view the updated room. I clicked the button and joined the channel. This part works ok. But returning to the channel via the recent rooms -list doesn't.

### Steps to reproduce

- Upgrade a room from v1 to v5 (I guess someone else may need to do this)
- Click the button in the bottom allowing to view the updated room
- Join the room
- Switch to another channel
- Switch back to the upgraded channel by using the new recent rooms -list
- Notice that you ended up to the room prior to upgrading, not the upgraded room

I would expect the symbol in the recent rooms list to take me to the updated room; this works if I first visit the upgraded room by using the normal room list.

### Version information

- **Platform**: web
- **Browser**: Firefox 66.0.3 (64-bit)
- **OS**: Ubuntu
- **URL**: riot.im/staging
- **Version**: 1.2.2-rc.1

**Comment by turt2live** [comment]
This should now be fixed in the new room list. If it isn't, please open a new issue.
