### ISSUE TITLE
When joining an upgrade room, its notification level should be the same as the original

### ISSUE THREAD

**Issue by eras** [vector-im/riot-web#10037]
### Description

When a channel (Synapse Admins) was updated from v1->v5, the newly joined room does not preserve the previous channel's notification settings.

### Steps to reproduce

- Set the room's notification setting to "Mentions only"
- Upgrade the room from v1 to v5 (I guess someone else may need to do this)
- Click the button in the bottom allowing to view the updated room
- Join the room
- Check the room notification settings from the room list
- Notice that the notification setting is "All messages"

I would expect the notification level to be the same as of the original room, "Mentions only".

### Version information

- **Platform**: web
- **Browser**: Firefox 66.0.3 (64-bit)
- **OS**: Ubuntu
- **URL**: riot.im/staging
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.2.2-rc.1

**Comment by turt2live** [comment]
This is a synapse issue: https://github.com/matrix-org/synapse/issues/5295
