### ISSUE TITLE
Bullet wysiwyg icon doesn't work

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10040]
I had a long list of items on different lines I selected them all (except the first line) and applied the bullet wysiwyg icon: it added a  bullet on the first line and I couldn't break the text into different bullets

**Comment by aaronraimist** [comment]
This button doesn't exist on the new composer right?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/75043922-ae1be200-54b8-11ea-905a-312a1e4fe9e0.png)
