### ISSUE TITLE
Editing as message breaks the bullets hierarchy

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10041]
I was applying manual bullets to a long list of existing text, including 2 and 3 level deep ones. Fat fingers meant I sent the message before it was finished, so edited it and then the hierarchy was gone

**Comment by bwindels** [comment]
Oh, yeah, the html > md converter for the editing editor doesn't prepend whitespace yet to list items depending on the nesting level.

**Comment by jryans** [comment]
@bwindels Is this a duplicate of https://github.com/vector-im/riot-web/issues/9859?
