### ISSUE TITLE
if you try to create an alias which is already in use, the error is silently discarded

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10048]

**Comment by bmarty** [comment]
The error is now handled has a generic error. The message should be more explicit in case of 409

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/3940906/65240086-bf635b80-dae0-11e9-9f23-522eafcf3e15.png">

**Comment by turt2live** [comment]
yea, this is fixed. The new bug is https://github.com/vector-im/riot-web/issues/9367
