### ISSUE TITLE
Breadcrumbs should display unread status of rooms

### ISSUE THREAD

**Issue by eras** [vector-im/riot-web#10055]
Description

When a room receives more messages that don't have a mention, its status is not reflected in any way in the breadcrumbs view.

It would be nice if they were highlighted in some way (overlaid circle perhaps?), similarly to the rooms in the actual room list.

Version information

    Platform: web
    Browser: Firefox 66.0.3 (64-bit)
    OS: Ubuntu
    URL: riot.im/staging
    Version: 1.2.2-rc.1

**Comment by MurzNN** [comment]
At first easy step will be good to bold text in unread rooms tooltip. And solution may be rounded border like in "Custom user status messages" labs module.

**Comment by turt2live** [comment]
We did this in the new room list
