### ISSUE TITLE
Just white screen when loading on Windows 10, never works, even after reinstall

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#10067]
Buddy gets a white screen when he launches riot, and it never loads. He tried reinstalling it multiple times and removing it from the roaming profile, or other local profile parts.

* Windows 10 Home
* Version 1809
* Build 17763.557
* Screenshot : https://steamuserimages-a.akamaihd.net/ugc/780726761715987921/A4688A8F56071F43D194FE79630E5D9F5D463C36/

Really not sure what more to do! Please send medical assistance!

**Comment by turt2live** [comment]
Press <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd> to bring up the inspector, then on the console tab type `mxSendRageshake("https://github.com/vector-im/riot-web/issues/10067")` to submit debug logs to us for investigation.

**Comment by BloodyIron** [comment]
Hmmm, user re-tested and right now is not getting the same issue, so maybe it was a regression that's solved.

**Comment by turt2live** [comment]
I guess if it happens again, please open a new issue with an attached rageshake (white screen issues are impossible for us to debug without logs).
