### ISSUE TITLE
Riot web v1.2.1: German translation of "Email, name or matrix ID" is not shown

### ISSUE THREAD

**Issue by menturion** [vector-im/riot-web#10066]
Riot web v1.2.1: 

German phrase "E-Mail, Name oder Matrix-ID" of English phrase "Email, name or matrix ID" is not shown. All other phrases are shown correctly in the "Start a chat" popup window, see image below:

![2019-06-15_191238](https://user-images.githubusercontent.com/41576848/59554363-0d2c6d00-8fa2-11e9-857f-95a79a699790.jpg)

**Comment by turt2live** [comment]
This is because the German string is not translated. The string currently translated has a lowercase M for Matrix, which means Riot is not picking it up.

I've copied the translation here: https://translate.riot.im/translate/riot-web/matrix-react-sdk/de/?type=all&offset=111

**Comment by menturion** [comment]
Is it fixed for the next version?

**Comment by menturion** [comment]
@turt2live 

I've checked some localization files (US, ES, EU) and noticed that - with the exception of the "en_EN" file - all files contain the wrong ""Email, name or matrix ID" phrase. So this issue is active for all language translations.

**Comment by turt2live** [comment]
I'm not sure if it will make it into the next version, but will be in one of the next few releases. 

Translators will have to re-submit the translations. Information on how to do this is here: https://github.com/vector-im/riot-web/blob/develop/docs/translating.md

**Comment by menturion** [comment]
Would like to help translating EN -> DE. However, it seems to be quite complicated at a first glance. Don't want to make ianything wrong.

Do you have any how-to on YouTube?

**Comment by jryans** [comment]
No videos that I know of, but I am sure others in #riotweb-translations:matrix.org can help.
