### ISSUE TITLE
The textboxes have changed shape on registration (they're not full width any more)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10073]
Before (on /app):
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1922197/59592906-d4e37680-90e8-11e9-879f-1349a672d7c4.png">

After (on /develop right now): 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1922197/59592852-c006e300-90e8-11e9-9fd5-7c701463b05c.png">

**Comment by bwindels** [comment]
regression from https://github.com/matrix-org/matrix-react-sdk/pull/3104 ?

**Comment by jryans** [comment]
There are several spots where https://github.com/matrix-org/matrix-react-sdk/pull/3104 removed `flex: 1` from styles targetting `.mx_Field`, but that doesn't seem correct... Only `.mx_Field input` styles were safe to prune.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3111
