### ISSUE TITLE
Auto Verification between iOS Librem Client and Riot MacOS Does Not Work

### ISSUE THREAD

**Issue by CaptainKhan** [vector-im/riot-web#10072]
Requires manual legacy verification between the two devices, apps and services. Please allow auto verification for non Riot matrix based clients.

**Comment by aaronraimist** [comment]
There is nothing preventing them from using emoji verification, all they need to do is update their fork.

I would say open an issue on https://source.puri.sm/liberty/chat/ios/issues except you (or someone) already has https://source.puri.sm/liberty/chat/ios/issues/8

**Comment by CaptainKhan** [comment]
great thank you!
