### ISSUE TITLE
Copy/pasting emoji messes up the input field

### ISSUE THREAD

**Issue by BearerOfHonesty** [vector-im/riot-web#10077]
Riot web 1.2.1 behave weirdly when copying and pasting emojis (on their own or as part of more text).

If I add an emoji, select it and copy, then paste one or more times the cursor gets stuck in the position after the first one and non-pasted additional input doesn't show up or shows up wrong.

To get the input field to be have normally again reload or switch to anoter room and back again. In either case the field will probably still contain the original text but not the pasted parts when you get back to the room.

**Comment by BearerOfHonesty** [comment]
I'm not sure if I just hadn't noticed it in 1.2.1 but it also affects just plain text in 1.2.2.

Pasting from other programs works just fine.

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by t3chguy** [comment]
Assuming the answer is no
