### ISSUE TITLE
[Question] electron app ico customization

### ISSUE THREAD

**Issue by w123475** [vector-im/riot-web#10078]
Hello. At the same time I use two accounts: personal and work. In order not to confuse them, I would like to change the favicon of the application (I make it from the source code).

Do not tell me how to do this? What file need to be edited so that the icon in Riot changes in Xubuntu? I am using linux unpack version.

**Comment by jryans** [comment]
There are lots of different icons around... You may be interested in:

https://github.com/vector-im/riot-web/tree/develop/res/vector-icons
https://github.com/vector-im/riot-web/tree/develop/electron_app/img

In the future, I'd suggest asking questions like this in #riot-web:matrix.org where more people can help out.
