### ISSUE TITLE
Prompt to accept integration manager policies on registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10087]

**Comment by lampholder** [comment]
If we have https://github.com/vector-im/riot-web/issues/10088 we might not actually want this

**Comment by lampholder** [comment]
This will require a change to scalar (to expose a policy document) - will this also require a spec change?

**Comment by turt2live** [comment]
> will this also require a spec change?

Technically no, because integration managers are not in the spec yet. I certainly wouldn't mind it being done as a collaborative MSC towards https://github.com/matrix-org/matrix-doc/pull/1956 (which also has a comment on it saying something about legal documents)

**Comment by lampholder** [comment]
I'm thinking maybe we shouldn't do this (at least not now) and instead rely on #10167 + https://github.com/vector-im/riot-web/issues/10088 to cover most cases.

**Comment by nadonomy** [comment]
If we do end up actioning this, the comps in Zeplin should be representative of how we want to expose this: https://zpl.io/brMdWo3

**Comment by jryans** [comment]
Since we've agreed that we actually prefer the terms prompts appearing on use, I'll go ahead and close this issue as something we don't intend to implement.
