### ISSUE TITLE
Prompt to accept integration manager polices on use

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10088]
Before you:

- [x] add a widget to a room
- [x] allow a widget to load for you in a room
  * This does sort of work already with https://github.com/matrix-org/matrix-react-sdk/pull/3199, but the UX is such that your are prompted when entering a room with a widget, not when allowing it to display
  * Time of prompting for existing widgets fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3240
- [x] use the sticker picker

You must read and agree to the policy documents provided by the integration manager

**Comment by lampholder** [comment]
This will require a change to scalar (to expose a policy document) - will this also require a spec change?

**Comment by turt2live** [comment]
> will this also require a spec change?

see https://github.com/vector-im/riot-web/issues/10087#issuecomment-503155269

**Comment by lampholder** [comment]
We considered whether it would be possible for Scalar to handle this "internally" (i.e. scalar presents HTML that gets rendered in iframes in Riot, so why not just let it do this same trick to handle t's and c's acceptance) - _however_, by the time it rendered such an acceptance UX you would already have shared the mxid with the integration manager via OpenID, so this is not feasible.

**Comment by nadonomy** [comment]
After validating today, latest comps are in Zeplin: https://zpl.io/brMdWo3

**Comment by jryans** [comment]
One portion fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3240

**Comment by jryans** [comment]
The rest of this issue will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3199

**Comment by jryans** [comment]
For historical tracking, I did not notice the in-context agreement tooltips from the Zeplin designs while working on this, so this only makes the general terms modal appear at the right moments.

**Comment by jryans** [comment]
(If we still want the in-context agreement tooltips from the design, we should file a new issue to track that.)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2600)

**Comment by jryans** [comment]
Filed https://github.com/vector-im/riot-web/issues/10422 for the more contextual version intended by the designs.
