### ISSUE TITLE
Ability to disable IS via blank URL regressed

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10086]
It has historically been possible to set the `default_is_url` to a blank URL and disable associated functionality. Doing so may have thrown various errors.

For this issue, we want to limit scope to repairing this regression only. The larger work of smoothly disabling all IS functionality is left to https://github.com/vector-im/riot-web/issues/5921.

**Comment by jryans** [comment]
Hmm, as best as I can tell, we default to https://vector.im when `default_is_url` is blank going back to at least Riot 1.0.0, but possibly further back as well. @turt2live, do have more details about this regression?

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/5921 was meant to track the regression - closing in favour of that.

**Comment by jryans** [comment]
@turt2live I guess I am puzzled that we're saying #5921 tracks a regression if it was filed in Jan 2018... I assumed it was describing a future feature request that we've never implemented so far.

**Comment by turt2live** [comment]
The longer story is that 5921 was created as a result of a conversation in #riot where several people were having trouble disabling the identity server. In their particular use case, they wanted to be absolutely sure that the identity server would never be contacted for corporate policy reasons, however it was found at that time that the `default_is_url: ""` trick didn't work anymore. The idea behind opening the issue (which was through the github bot, hence the terseness) was that by now Riot would have added a way to disable the identity server, therefore fixing the regression and introducing a new feature.

**Comment by jryans** [comment]
Okay, thanks for the additional detail! I think I got confused by the word "regression" and assumed it was a recent change, but in reality it hasn't worked for a long time.
