### ISSUE TITLE
Slowness of text messages, whilst audio is perfect?!

### ISSUE THREAD

**Issue by johnstonesnow** [vector-im/riot-web#10096]
I am wondering why text messages are so slow to arrive and deliver to other device. Conversations can get confused due to this delay as some messages insert themselves further up the chain. 

Is this due to server load on matrix.org (in which case I could try another homeserver) or is it due to encryption or..... ? I am having one to one encrypted chat. What I don't understand is how the audio calls are so SUPERB with zero lag, yet a simple text message can get held up for so long before arriving (greyed out for 5-8 seconds) until delivered. 

I am using mac desktop Riot app on iMac, my friend is using Riot on Windows 10 and Windows 7, same across all three devices. Grateful for any suggestions if it's not a bug. 
thanks

**Comment by turt2live** [comment]
> Is this due to server load on matrix.org

Almost certainly. There's an ongoing incident with the matrix.org homeserver which is causing messages to be more delayed than usual.

Switching to a different homeserver (or running your own) is the easiest way to avoid the problem.

In general, support queries are best asked in [#riot-web:matrix.org](https://matrix.to/#/#riot-web:matrix.org) as we normally respond faster in the room.

**Comment by johnstonesnow** [comment]
Thanks. I didn't understand the link, it didn't seem to take me "in" anywhere. Will leave it with you if it's a known problem. thanks again for such a quick reply

**Comment by johnstonesnow** [comment]
Sorry, neither me nor my friend can see that setting anywhere. Under "Advanced" it only shows:

- Room Information - Internal Room ID: xxxxxxxxxxxxxxxx:matrix.org

- Room Version: 4

- Developer options - Open Devtools (looked in there)

**Comment by turt2live** [comment]
Switching homeservers is a manual process which involves creating a new account elsewhere and manually inviting that account to all your rooms. More information about the process can be handled in #riot-web:matrix.org (type `/join #riot-web:matrix.org` - it might be a bit slow)

**Comment by johnstonesnow** [comment]
I don't have any rooms. I dont want any rooms, and even though Riot says it can do 1-1 chat, it still seems to create a room for 1-1 chat, so I am just trying to learn how to use it really. i want to change homeserver so I think what you said means i ought to kill of my current user, and quit the app then restart and get a new ID at the new server i want to join. Will suss it out eventually, and i have joined that room too thanks
