### ISSUE TITLE
Store identity server in Account Data and support choosing identity server integration in User Settings

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10094]
![2019-08-02 at 15 28](https://user-images.githubusercontent.com/279572/62377224-49a82e00-b53a-11e9-9577-24c508752ed6.png)

![2019-08-02 at 15 29](https://user-images.githubusercontent.com/279572/62377280-617fb200-b53a-11e9-9be5-8795ea1b53a9.png)

Additional requirements:
- when we change IS, we'll need to fetch its policy docs and capture that the user has agreed to them
- we should probably also validate that it's really an IS
- we should _also_ somehow validate that the HS permits access to this IS if it maintains a whitelist...

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/5921

**Comment by lampholder** [comment]
Hey @turt2live - I think #5921 is not a dup of this, since the intention of this is to expose this as an option within UserSettings so that a user can change their IS mid flight.

It could be that that's an assumption baked into #5921, but it wasn't obvious to me.

**Comment by lampholder** [comment]
This is related to https://github.com/matrix-org/synapse/issues/5539 and https://github.com/matrix-org/synapse/issues/5540. Until such time as synapse can provide a set of associated ISes per threepid, the best we can do in Riotland is to take the IS associated with the current session and query as to whether there is a bind for that threepid.

Publishing your threepid to an IS initiates the threepid validation flow, so I think it is too simple to render as a simple checkbox.

Crappy placeholder UX for Nad to use as input to requirements:

![Frame 7 2](https://user-images.githubusercontent.com/1922197/60030116-54011d80-969a-11e9-8bdd-1fcbef2a3a6d.png)
![Frame 7 3](https://user-images.githubusercontent.com/1922197/60030117-5499b400-969a-11e9-96e0-33d630751093.png)
![Frame 7 4](https://user-images.githubusercontent.com/1922197/60030120-5499b400-969a-11e9-9895-3a8e801b95c4.png)

The 'share' wording is inspired by the copy from the registration page; I actually don't think it scans very well as an action (if you were to lose track of the column header, the verb 'share' is too vague to be clear). If we come up with a better column heading and button verb, we might want to loop that back onto the registration page, too.

**Comment by lampholder** [comment]
I'm actually going to split this into two issues - one for associating/disassociating an email with an IS, and the other for changing your IS. I'll close this issue when I'm done.

**Comment by nadonomy** [comment]
After validating today, latest comps are in Zeplin: https://zpl.io/brMdWo3

**Comment by dbkr** [comment]
One thing that's not clear on this is how this should work with all the other places that specify ISes, ie. if the one you had at login time (be that from your client's default, .well-known or entered), is that then discarded in favour of using the one in your account settings? I'm going to assume so for now.

**Comment by jryans** [comment]
Another complexity is that (similar to the Disconnect button in https://github.com/vector-im/riot-web/issues/10425), we need to ensure all your 3PIDs are unbound (both on the IS itself and also the HS record of where your 3PIDs are bound) before actually changing the IS.

**Comment by lampholder** [comment]
> One thing that's not clear on this is how this should work with all the other places that specify ISes, ie. if the one you had at login time (be that from your client's default, .well-known or entered), is that then discarded in favour of using the one in your account settings? I'm going to assume so for now.

We should no longer have an IS 'supplied at login time' - rather there is a 'default' that is 'the Identity Server the client would prompt to use if asked to do something identity servery and the user has not made an active choice to use either a different identity server or no identity servrer at all'.

This 'default' could be specified in the config.json or in .well-known (I can't think of anywhere else sensible to provide this at the moment), or it could not be specified at all. 

There is an unanswered question about what we do if an admin wants to provide a matrix stack with a locked-down IS choice. I think answering this question is hard, so despite the risk of our painting ourselves into a corner with the proposed, I'd like to keep a lid on this for now and tackle it if/when we have a concrete usecase to consider.

**Comment by dbkr** [comment]
The nice inline terms dialog has been spun out to https://github.com/vector-im/riot-web/issues/10539 as it's not as critial-path as the rest of this.

**Comment by dbkr** [comment]
Second part of this is done. I think @turt2live is working on the first part.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2651)

**Comment by turt2live** [comment]
I've reclaimed this for the storing in account data part. https://github.com/matrix-org/matrix-react-sdk/pull/3300 has been added to "in test" for Dave's portion of the work.

MSC I need to care about: https://github.com/matrix-org/matrix-doc/pull/2230
