### ISSUE TITLE
Failed to upgrade room

### ISSUE THREAD

**Issue by dchatterjee172** [vector-im/riot-web#10099]
### Description
Room upgrading fails

### Steps to reproduce

* Shows I have to upgrade room
* follow the options
* fails

Describe how what happens differs from what you expected.
* umm, not fail..

Log: sent/not sent?   Not sent

- **Platform**: web
For the web app:

- **Browser**: Chrome
- **OS**: Fedora
- **URL**:  riot.im/app /

```
CORS request rejected: https://matrix.org/_matrix/client/r0/rooms/____/upgrade
```
I have removed some stuff from the above URL, not sure if it is safe to put it here

**Comment by turt2live** [comment]
Can we get debug logs for this please? Open your account settings then on the Help & Support tab click "Submit debug logs". Where it asks for the github issue, use this issue's URL.

**Comment by dchatterjee172** [comment]
@turt2live Done

**Comment by turt2live** [comment]
It looks like this is related to the performance issues of the matrix.org homeserver - see https://twitter.com/matrixdotorg/status/1141055881221758977 for details.
