### ISSUE TITLE
Prompt to accept Identity Server policies on registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10092]
When do we want to do this?

Is it for anyone publishing a threepid to the IS? Or also for anyone who might want to use the IS in future to look up other users by their threepid?

**Comment by lampholder** [comment]
This will require a change to sydent and presumably the spec to expose policy documents

**Comment by turt2live** [comment]
we should try and reuse https://github.com/matrix-org/matrix-doc/pull/1692 if possible

**Comment by nadonomy** [comment]
After validating today, latest comps are in Zeplin: https://zpl.io/brMdWo3

**Comment by jryans** [comment]
We have realised that this is a subset of what will be achieved by https://github.com/vector-im/riot-web/issues/10167, so we don't need both issues.
