### ISSUE TITLE
Make sure there are no ugly edge cases running Riot without an integrations manager

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10090]
There's a good chance there aren't; this is just a reminder to make sure.

**Comment by turt2live** [comment]
There aren't. See https://github.com/matrix-org/matrix-react-sdk/pull/3115

**Comment by lampholder** [comment]
Re-adding the labels just so that it appears as a 'Done' item in the project plan

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2518)
