### ISSUE TITLE
Decouple setting an email for password reset from publishing your threepid to the identity server and support choice of identity server (on registration)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10091]
![image](https://user-images.githubusercontent.com/1922197/60085009-7776a780-9730-11e9-84d9-bd8fb77825e1.png)

**Comment by t3chguy** [comment]
Setting an e-mail for password reset also allows the enablement of e-mail notifications being sent to it

**Comment by lampholder** [comment]
> Setting an e-mail for password reset also allows the enablement of e-mail notifications being sent to it

I don't think this needs calling out in the UX specifically, since you're not opted into email notifications by default (I just verified this).

**Comment by aaronraimist** [comment]
Did you test with a new account or adding an email to your existing account? I’m pretty sure new accounts do have email notifications enabled by default.

**Comment by lampholder** [comment]
I did test with a new account - I just tested adding an email addres sto an old account and email notifs weren't enabled by default (in this instance at least).

Do you have a counter example?

**Comment by aaronraimist** [comment]
I guess not. I just tried it with a new account and it worked as you said. Maybe that behavior changed since I created my account because I'm pretty sure it was enabled by default in the past.

**Comment by nadonomy** [comment]
After validating today, latest comps are in Zeplin: https://zpl.io/brMdWo3

**Comment by lampholder** [comment]
The material parts of this have moved to other issues, namely:
- https://github.com/vector-im/riot-web/issues/10408
- https://github.com/vector-im/riot-web/issues/10167
