### ISSUE TITLE
No system tray in Gnome, but was showing earlier this week

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#10109]
On latest Riot Web (Desktop) as of this writing.

I know there's another thread about no system tray in Gnome, however I think my situation is different because I've had it working for months, and now it's not showing up in my sys tray. As in, this suddenly changed within the last few days.

Unsure if this is a riot update that broke it, or what. Rebooted, can't get icon to show up in system tray at all.

**Comment by jryans** [comment]
I am fairly sure this is the same as https://github.com/vector-im/riot-web/issues/9897. The system tray will appear once you get a notification. The next Riot release will have the fix.
