### ISSUE TITLE
Can't login after failed room upgrade attempt

### ISSUE THREAD

**Issue by Tahomaru** [vector-im/riot-web#10101]
### Description

Can't log in with my account after a failed room upgrade attempt.
Same goes for the other person that was in said room.

### Steps to reproduce

- Click on room upgrade.
- Said upgrade fails.
- Cannot connect to the homeserver anymore no matter the platform. 

Expected the room upgrade to work.

Log: Not sent.

### Version information

- **Platform**: web (in-browser) or desktop?
For the web app:
- Tried with Firefox and Brave to no avail.

For the desktop app:

- **OS**: Windows 10 1903, Ubuntu MATE 19.04 and Android 7.1.2.

**Comment by turt2live** [comment]
This is almost certainly because of the matrix.org outage - see https://twitter.com/matrixdotorg/status/1141055881221758977 for details.

**Comment by Tahomaru** [comment]
Indeed. Looks like it's resolved.
Thanks for answering.
