### ISSUE TITLE
Jitsi plugin does not allow for screen sharing using the app, but does work fine when in the web browser.

### ISSUE THREAD

**Issue by andrewschott** [vector-im/riot-web#10104]
As stated in the title, sharing of the desktop does not work (the options box has an infinite load time, so no options are presented).  But opening the call in a browser works perfectly.

I presume this has something to do with the app itself, but curious if I may be missing something that would fix this.  I am on Linux, both RHEL7 and OpenSUSE Tumbleweed.  Unsure if its a distro thing.

Thanks!

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4880 (it's a known problem, sorry)

**Comment by andrewschott** [comment]
You guys are gods!  That was fast!
