### ISSUE TITLE
Consistent coloring for contacts

### ISSUE THREAD

**Issue by notramo** [vector-im/riot-web#10107]
**Is your suggestion related to a problem? Please describe.**
The avatar colors are not the same in all rooms for the same user (even isn't always the same for the nickname and the letter avatar if avatar image is not set). It would be easier to distinguish between users if the interface used consistent coloring.

**Describe the solution you'd like**
- Assign the same color to the same user in all rooms.
- It should be possible to specify the custom color for every user.

**EDIT:**
**Screenshots**
Profile picture color is different than nickname color.
![image](https://user-images.githubusercontent.com/26059643/59779461-97354800-92b8-11e9-902f-97448f7dbb75.png)
Room picture in the **same room** uses a different color.
![image](https://user-images.githubusercontent.com/26059643/59782402-2abd4780-92be-11e9-858d-396de892ff94.png)

It should be the same color (e.g. green) in both places.

**Comment by turt2live** [comment]
Which colour is this referring to? Can we get screenshots of the problem areas please?

**Comment by notramo** [comment]
Every nickname and capital letter profile picture color.
(I added screenshots to the original comment.)

**Comment by turt2live** [comment]
were the screenshots for the same user/direct chat with that user? The C is a very curious thing as it should be a green U given the name and prior screenshot.

**Comment by notramo** [comment]
Yes these are from the same, I modified the nick name from devtools, but only text.

**Comment by turt2live** [comment]
I think this is largely https://github.com/vector-im/riot-web/issues/2449 (which has been a bug since the colour scheme used 3 schemes ago, sadly) - closing in favour of that, which should address the concern here.
