### ISSUE TITLE
Move accounts between hosts

### ISSUE THREAD

**Issue by leenpaws** [vector-im/riot-web#10100]
I created my account on a generic matrix homeserver and later on created my own, I would like to move my account to my newly created homeserver.

**Is your suggestion related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by t3chguy** [comment]
You can use https://modular.im/tools/matrix-migration

**Comment by turt2live** [comment]
Closing in favour of spec discussion: https://github.com/matrix-org/matrix-doc/issues/915
