### ISSUE TITLE
Guest experience on /app is broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10114]
There's a sign up box when previewing rooms, which does nothing, and some time later the room suddenly can be previewed

**Comment by lampholder** [comment]
So a room that you should be able to preview looks like this:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1922197/59842031-871b7800-934d-11e9-87f0-e3557f06323b.png">

But the 'sign in' link doesn't work correctly, and you should be able to see the timeline but you don't unless you wait ages, then eventually you'll see a view that looks like (without the blurring, I added that):
![Frame 7](https://user-images.githubusercontent.com/1922197/59842329-41ab7a80-934e-11e9-8328-e32ad83fa90e.png)

**Comment by turt2live** [comment]
@lampholder for the intermediary state, how does this look? (pretending the buttons work)

![image](https://user-images.githubusercontent.com/1190097/60147178-b127cc80-9789-11e9-8256-687cde3e20ad.png)

**Comment by lampholder** [comment]
👍
