### ISSUE TITLE
[object Object] for hidden MELS when 'show hidden events' enabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10115]
see https://github.com/matrix-org/riot-web-rageshakes/issues/1614

This is a collapsed MELS:
![image](https://user-images.githubusercontent.com/1190097/59784695-4efa3380-9280-11e9-9cdc-f618219d46b0.png)

for these events:
![image](https://user-images.githubusercontent.com/1190097/59784727-646f5d80-9280-11e9-8e39-5f67c1cfa880.png)

Which are no-op events (join -> join, no profile change)

**Comment by jryans** [comment]
For debugging, an example of this occurs just after [this message](https://matrix.to/#/!DYgXKezaHgMbiPMzjX:matrix.org/$1560960653289174vDzXr:matrix.org?via=matrix.org&via=matrix.allmende.io&via=tchncs.de).
