### ISSUE TITLE
Redacting an edited message should redact all edits, not just the original event

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10111]
1. send a message
2. Edit it
3. Redact it

Riot only redacts the event from step 1, not step 2.

**Comment by bwindels** [comment]
just like https://github.com/vector-im/riot-web/issues/10136, feels like something that should be enforced server-side...

if so, does it make sense to spend time on doing this initially client-side in riot until synapse supports it?

**Comment by lampholder** [comment]
This will be completely resolved by the server side work: https://github.com/matrix-org/synapse/issues/5594

**Comment by richvdh** [comment]
looks like this got reopened as #11978
