### ISSUE TITLE
Web interface missing icons

### ISSUE THREAD

**Issue by imacdonald** [vector-im/riot-web#10126]
### Description

Icons for actions, e.g. Settings, are missing from the web interface at riot.im

### Steps to reproduce

- Login in to the web interface
- Any web pages providing actions are missing the icons
- Mauve squares are shown insted of icons
- Tried with Firefox, PaleMoon & Chromium, all exhibited the same problem
- Clearing the cache made no difference

### Version information

- **Platform**: web (in-browser) or desktop?
 - web app

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
 - Chromium 61.0.3163.100
 - Firefox 52.9
 - PaleMoon 28.0
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
 - Debian 9.1
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
 - riot.im/app

Sigh! Github isn't accepting my screenshot. Will try in follow-up comment.

**Comment by imacdonald** [comment]
Screenshot:

![matrix-via-riot-screenshot](https://user-images.githubusercontent.com/1724575/59846263-43c60700-9357-11e9-9553-43b9d2514da7.png)

**Comment by jryans** [comment]
The icons use `mask-image`, which was added to Firefox 53. Your versions of Chrome is also quite old, so I would guess it's a similar issue there as well. I would recommend installing recent browser versions if possible, or else use Riot desktop.
