### ISSUE TITLE
An empty space above room filter in v1.2.2

### ISSUE THREAD

**Issue by user318** [vector-im/riot-web#10123]
### Description

In version 1.2.2 there is an empty space appeard in the left panel above room filter field. This eats a lot of space from chat list for no reason.

In web inspector I see it is defined by this code:

```html
<div class="mx_AutoHideScrollbar mx_RoomBreadcrumbs mx_AutoHideScrollbar_underflow"><div class="mx_AutoHideScrollbar_offset"><div class="mx_IndicatorScrollbar_leftOverflowIndicator" style="left: 0px;"></div><div class="mx_IndicatorScrollbar_rightOverflowIndicator" style="right: 0px;"></div></div></div>
```

### Steps to reproduce

Updated from v1.2.1 to v1.2.2.

Version 1.2.1:
![riot-v1 2 1](https://user-images.githubusercontent.com/671062/59839522-06f71180-9351-11e9-873a-5922e1c85d86.png)

Version 1.2.2:
![riot-v1 2 2](https://user-images.githubusercontent.com/671062/59839534-0b232f00-9351-11e9-8d31-51cef98a4105.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 66.0.3
- **OS**: Ubuntu

**Comment by t3chguy** [comment]
Not a bug. A feature, if you navigate between rooms it shows you your recent rooms so you can get back to them quickly.

You can also disable it in settings:
![image](https://user-images.githubusercontent.com/2403652/59840311-0018d080-934a-11e9-8a1d-b5747ff0fb53.png)

**Comment by user318** [comment]
Clear cache helped with the issue and there appeared icons of recent rooms probably. Looks like some changed resource file have not changed its name in new version.

**Comment by user318** [comment]
Or may be you are right, I just needed to navigate some rooms first.
