### ISSUE TITLE
Search does not search in urls

### ISSUE THREAD

**Issue by skerit** [vector-im/riot-web#10135]
### Description

Someone had sent a specific url to me, but I forgot what it was or when it was sent. I knew a part of the url (the domain name), so I searched for it. But it did not show up in the search results.

I was not even using a secure chat.

### Steps to reproduce

- Talk to someone, share some urls
- Search for the domain in one of those urls
- The urls will not show up in the search result

I would expect riot to just search through all the text.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Manjaro linux
- **Version**: 1.2.1

**Comment by t3chguy** [comment]
Search is server-side so perhaps you'd be better suited by opening a Synapse issue

**Comment by skerit** [comment]
Oh ok, will do

**Comment by skerit** [comment]
There already is an issue open on the synapse github repository:
https://github.com/matrix-org/synapse/issues/3024

**Comment by ara4n** [comment]
dup #4486
