### ISSUE TITLE
Solid color squares shown instead of emoji in 1.2.2

### ISSUE THREAD

**Issue by BearerOfHonesty** [vector-im/riot-web#10143]
Solid color squares shown instead of emoji in 1.2.2, worked in 1.2.1.

The emoji is actually there but isn't displayed correctly; copying it to another program makes it show up correctly over there.

**Comment by turt2live** [comment]
@BearerOfHonesty can you submit debug logs for this issue please? It should contain debugging information which might help identify the problem.

Account Settings -> Help & About -> Submit debug logs. When asked, use this issue as the URL.

**Comment by BearerOfHonesty** [comment]
Nevermind. I think it's an extension that's causing it.

I was messing around with exceptions for riot.im/app/ in https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/ to make thumbnails on uploads work as someone was complaining about them just being white squares and mentioned that it was probably because of a canvas blocker and somewhere along the way I noticed that emoji had started working again so I'm not sure exactly which blocks caused it.

**Comment by BearerOfHonesty** [comment]
Turns out it's my extension for changing the User-Agent. Apparently there's a test for if it's Firefox or not and lying to it makes it not work.

**Comment by jryans** [comment]
Yes, canvas and user agents are used to detect support for the emoji font so we can try to load the correct format for your browser. I think the best bet to locally modify whatever extensions may be blocking this features so that they allow Riot to use them.

**Comment by lascapi** [comment]
Hi there ! I have the same issue too with the desktop application for MacOs ! 
Since the version 1.2.2 and also with the new version 1.2.3
Can you reopen it ?

**Comment by turt2live** [comment]
@lascapi your logs show that your browser doesn't support COLR fonts and/or canvas. Do you have a privacy blocking plugin like above? If so - try disabling that first. If you continue having the issue, please open new issue.

**Comment by lascapi** [comment]
I don't know, it's the official desktop application. I just install it. So I open a new issue, thank's :-)
