### ISSUE TITLE
Verifying a device from the unknown devices dialog does not update the device list

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10142]
I clicked "Verify" on the dialog below, did some emoji comparison, and was returned to this dialog which did not change the device to verified.

![image](https://user-images.githubusercontent.com/1190097/59954437-e955a500-9441-11e9-8176-2913c83784a0.png)

**Comment by lampholder** [comment]
Dup of https://github.com/vector-im/riot-web/issues/7976 ?
