### ISSUE TITLE
Consider using a <meter> instead of <progress> for key backup passphrase strength indicator

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10141]
Meter (windows 10):
![image](https://user-images.githubusercontent.com/1190097/59954197-b8c13b80-9440-11e9-954d-11ea3879a5ab.png)

Progress (windows 10):
![image](https://user-images.githubusercontent.com/1190097/59954218-dbebeb00-9440-11e9-92ad-99de4228c894.png)

From the docs, a `meter` is more in line with what we're doing anyways.

Edit: the above is in Firefox. Chrome seems to style the progress bar such that the default Windows style doesn't apply.

**Comment by t3chguy** [comment]
I don't think this matters anymore given we roll our own appearance on top of a `<progress />` now

**Comment by t3chguy** [comment]
Looks prettier as of https://github.com/matrix-org/matrix-react-sdk/pull/4599
