### ISSUE TITLE
Right panel unexpectedly switches to member list when changing rooms

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10149]
The top right icons are a bit of a mess of per-room & global actions atm, but they should only change their selection when users trigger them. Currently, switching rooms also changes (e.g. the files panel) to display the member list, which is unexpected.

The right panel selection should only change when a user triggers it. The icons to the left of the vertical rule are interacted with modally, so behave predictably, however:

- [ ] The notification panel should persist when switching rooms, continuing to display notifications from all rooms
- [ ] The files panel should should persist when switching rooms, displaying files belonging to the room being viewed

Relatedly, we do plan to improve the layout of the icons, creating a better separation between per-room & global actions, but those changes are attached to Communities, with an unknown timeline.

**Comment by t3chguy** [comment]
This happens because `<RoomView />` is keyed by roomId, so whenever Room ID changes, the state is wiped out
