### ISSUE TITLE
Messages which can't be edited or reacted to cause frustration in trying to get at the context menu

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10157]
The menu is slightly too high, which means that the path the mouse cursor takes causes the previous message (or non at all) to be highlighted, de-selecting the message the user is trying to access

**Comment by jryans** [comment]
See also https://github.com/vector-im/riot-web/issues/9650

**Comment by uhoreg** [comment]
Coincidentally, I just came across this article, which is somewhat related: https://www.nngroup.com/articles/steering-law/

**Comment by turt2live** [comment]
also https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown

**Comment by jryans** [comment]
Ah yes, I've seen these posts over the years. 😁 It does seem like a good improvement to aim for. Tracking as part of aggregations since that's who changed the UX here.

**Comment by bwindels** [comment]
Is this being addressed as part of #9650 ? I guess it will be. Can we assign/mark it as in-progress if so?

**Comment by jryans** [comment]
Yes, I believe we can consider this fixed by the changes for #9650.
