### ISSUE TITLE
Reduce number of tooltip components

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10155]
We'll soon have 3 different tooltip-like components:

* `InteractiveTooltip`
* `ContextualMenu`
* `Tooltip`

which all have different behaviour in how they open, stay on screen, etc. We should investigate if we truly do need so many tooltip styles.

**Comment by nadonomy** [comment]
After some internal discussion, we decided to attack this visually first and then go from there. More notes for myself:

- `Tooltip` is used for key share icon, registration validation, etc
- `ContextualMenu` is used in the room list, etc
- `InteractiveTooltip` is only used for quick reactions

**Comment by t3chguy** [comment]
`Tooltip` is also now used for the `AccessibleTooltipButton` which is used on the `+` buttons on the Left Sidebar
