### ISSUE TITLE
Store Integration Manager preferences in account data and allow user to change them somewhere sensible

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10161]
The User Settings UX for https://github.com/vector-im/riot-web/issues/4913, basically.

**Comment by lampholder** [comment]
I don't think there's any benefit to my mocking up a UX for this - there are quite a few places one could put this UX :\

It could be implemented in User Settings (along the lines of https://github.com/vector-im/riot-web/issues/10094) or it could be in the IM UX somewhere).

What we need (as a minimum) is for a user to be able to:
- choose not to use an IM at all
   - and Riot should handle this gracefully
   - they should be made aware that this isn't going to do anything to existing widgets
- choose a different IM
   - we should verify that it _is_ an IM
   - we should prompt the user to ready and accept the IM's policy docs
       - (does this need to be done at config change, or at first use?)
   - existing widgets should 'just work'

**Comment by turt2live** [comment]
proposal for this: https://github.com/matrix-org/matrix-doc/pull/1957 (cc from https://github.com/vector-im/riot-web/issues/4913)

**Comment by nadonomy** [comment]
After validating today, latest comps are in Zeplin, as a part of registration & settings: https://zpl.io/brMdWo3

**Comment by turt2live** [comment]
Terms acceptance is https://github.com/vector-im/riot-web/issues/10539

**Comment by turt2live** [comment]
PRs in this issue:
* Part 1: https://github.com/matrix-org/matrix-react-sdk/pull/3301
* Part 2: https://github.com/matrix-org/matrix-react-sdk/pull/3302
* Part 3: https://github.com/matrix-org/matrix-react-sdk/pull/3308

Future work:
* https://github.com/vector-im/riot-web/issues/4913
* https://github.com/vector-im/riot-web/issues/10539
