### ISSUE TITLE
Forward message is hard to understand

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10166]
As a newer Riot user, I was unsure for quite a while what "Forward Message" would do. It appears to take any message you choose (from any original sender) and re-send to a new room as yourself.

This seems okay if you are both the original sender and the forwarder. If that's not true though, it would be much better to have some link back to the original sender (or original event) in the forwarded event.

**Comment by t3chguy** [comment]
Related/Duplicating https://github.com/vector-im/riot-web/issues/4747

**Comment by jryans** [comment]
Ah thanks! Probably similar enough to close this one, as I think having that fixed would be good enough for me at least.
