### ISSUE TITLE
Chrome seems not to like running Riot from file://

### ISSUE THREAD

**Issue by MTRNord** [vector-im/riot-web#10177]
### Description

Please see: https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$15615670652548sbqNr:converser.eu?via=matrix.org&via=linuxgaming.life&via=privacytools.io

(I am only relaying that discussion to the bug report)

### Steps to reproduce

- Download the release
- make a config.json
- open in chrome via a file:// url

Log: not sent    

### Version information

- **Platform**: web (in-browser) or desktop? Web Chrome but local

For the web app:

- **Browser**: Chrome
- **OS**: unknown looked like linux
- **URL**: Local Tar

**Comment by jryans** [comment]
Browsers do tend to lock down `file://` quite aggressively these days. (I haven't attempted it yet locally.)

**Comment by ara4n** [comment]
From my pov it's a feature that Riot doesn't work from file:/// URLs - we simply don't try to make it work. As Ryan says, the permissions tend to be very locked down.
