### ISSUE TITLE
Encrypted rooms cannot be distinguished from unencrypted rooms in the side bar

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#10180]
### Description
The top room in the sidebar is encrypted. The bottom one is unencrypted.

![identical](https://user-images.githubusercontent.com/1917473/60202085-c2ccab00-9841-11e9-9282-f3ddee196095.png)

I can't tell the difference, which causes me to click the wrong room and start typing. As the encrypted lock is in the opposite corner of the screen to the enter text and send button, my eye has never been drawn to the part of the screen that shows a room is unencrypted, which means that i have accidentally sent important information in an unencrypted room.

### Steps to reproduce

Have two direct chats with the same persoson. Mark one as encrypted, the other as not.

I want to tell them apart in the side bar - perhaps an overlaid lock icon.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by michaelkaye** [comment]
Given we've got it, can we merge the PR from t3chguy? It's been a few months so I'd forgotten I'd filed this, and got caught out by it again, sending secrets in a non-private window.

**Comment by t3chguy** [comment]
Nad said to me yesterday that designs are coming so it should be a short road from here

**Comment by uhoreg** [comment]
We have shields now on /develop :shield:
