### ISSUE TITLE
Edited events that get redacted show their content

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#10191]
How to repro:
 - turn on editing in labs if you haven't done so already.
 - send a message (room can be in either encryption state)
 - edit the message
 - redact the message (the original message gets redacted, as it should. The edit doesn't get redacted yet by the server, see https://github.com/matrix-org/synapse/issues/5594)
 - turn off editing in labs and refresh
 - behold:

![image](https://user-images.githubusercontent.com/274386/60276636-85245c80-98eb-11e9-8227-39092b399ca0.png)

On other clients present in the room with editing turned off, the original message appears correctly redacted without the content shown:

![image](https://user-images.githubusercontent.com/274386/60277562-5c9d6200-98ed-11e9-9f72-62cbac933a7e.png)

So seems like the client preserved state somehow.

Potentially related: https://github.com/vector-im/riot-web/issues/10006

**Comment by jryans** [comment]
Hmm, I can't seem to reproduce this (attempted in both room encryption states). I tried a fast local HS and also slow matrix.org HS. @bwindels, could you retest? Maybe it's been fixed by other changes?

**Comment by bwindels** [comment]
Will do!

**Comment by bwindels** [comment]
Indeed, can't repro anymore with the above steps.

**Comment by bwindels** [comment]
Found a way to repro this, you need two riot sessions:
 1. open riot with session 1
 1. send a message
 1. edit it
 1. redact it
 1. send +10 messages to trigger a limited sync in session 2 later on
 1. open riot with session 2, let it sync
 1. the edited and then redacted message should now have it's content visible through the redaction lozenge.
