### ISSUE TITLE
'and 5 others' part of the invited section is wrong

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10199]
#riot-web has 3 email invites and 7 user invites. It shows 'and 5 others', but only reveals 3 more users

**Comment by t3chguy** [comment]
Caused by https://github.com/matrix-org/matrix-react-sdk/blob/3cd9c152c24f7ee1e68721261ddb48ef21c88228/src/components/views/rooms/MemberList.js#L408

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3172

**Comment by t3chguy** [comment]
Whooops, forgot the magic word :')
