### ISSUE TITLE
Consider adding an /avatar command

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10192]
We currently have the following commands available from Riot's input bar:

* `/nick` - change your nick in all rooms
* `/myroomnick` - change your nick in the current room
* `/myroomavatar` - change your avatar in the current room

But we don't have one to change your avatar globally, which I feel we should add for the sake of consistency.

**Comment by turt2live** [comment]
/me bets @t3chguy is going to get to this before it even makes it on my top 30 list

**Comment by t3chguy** [comment]
/me will do this when I get home

**Comment by anoadragon453** [comment]
Yay, thank you!
