### ISSUE TITLE
Own Categories

### ISSUE THREAD

**Issue by marvinjuette** [vector-im/riot-web#10190]
**Is your suggestion related to a problem? Please describe.**
I am a bit upset that I can't create my own room and person categories to organice them better.

**Describe the solution you'd like**
I think it would be cool, if you have the opportunity to create own categories e.g. friends, work, etc. to add the existing groups e.g. rooms, favourites

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/8723
