### ISSUE TITLE
Message Editing: The original message is not shown in the history

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10200]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/60339211-0d643980-99a0-11e9-89c2-c3c551125d95.png)

![image](https://user-images.githubusercontent.com/1342360/60339229-18b76500-99a0-11e9-9d18-31f8f334e09b.png)

![image](https://user-images.githubusercontent.com/1342360/60339239-210fa000-99a0-11e9-9763-5074b1d73bf5.png)

Edit history:

![image](https://user-images.githubusercontent.com/1342360/60339247-28cf4480-99a0-11e9-8c83-7eee5dee5ede.png)

Log: not sent?    

### Version information

- **Platform**: web
- **Browser**: Firefox 69.0a1
- **OS**: Debian Stretch
- **URL**: riot.im/develop

Related: https://github.com/vector-im/riot-web/issues/9490

**Comment by jryans** [comment]
Yes, it is a known issue. Currently Riot team is assuming Synapse changes will be made to fix this.

**Comment by lampholder** [comment]
This should be fixed by https://github.com/matrix-org/synapse/issues/5595

**Comment by lampholder** [comment]
We might need to do a tiny bit of work to make this happen, but probably not.

**Comment by bwindels** [comment]
This is [implemented with an extra `original_event` field](https://github.com/matrix-org/synapse/pull/5626/files#diff-1a9fb836e1af4380ea0cc4dc1495f985R181), which we'll need to implement.
