### ISSUE TITLE
Cookie policy link is broken

### ISSUE THREAD

**Issue by tjhietala** [vector-im/riot-web#10202]
### Description

Riot's cookie policy link points to https://matrix.org/docs/guides/riot_im_cookie_policy which gives a 404.

### Steps to reproduce

Go to a room, click on the link about cookie policy in the banner at the top of the screen.

### Version information

- **Platform**: riot.im/app & riot.im/develop

**Comment by jryans** [comment]
Thanks for bringing this to our attention! We'll get this fixed up.

**Comment by jryans** [comment]
The policy link is now working again.
