### ISSUE TITLE
Reactions can trigger stuck notifications if read receipt above own messages

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10208]
1. Create a room with two people
2. Ensure room is set to noisy notifications
3. Alice sends several messages
4. For every reaction Bob sends, Alice gets a progressively incrementing notification count
    * Viewing the room temporarily clears the notification badge, but the count will keep accumulating for the next reaction
5. Bob has to speak and be read by Alice (advancing Alice's read receipt) to clear Alice's notification count

---

We've decided to address this by default disabling notifications for reactions:

- [x] [Propose MSC defining a push rule to ignore reaction events](https://github.com/matrix-org/matrix-doc/pull/2153)
- [x] [Add push rule to Riot to make it available for early testing](https://github.com/matrix-org/matrix-js-sdk/pull/976)
- [x] [Add push rule to Synapse](https://github.com/matrix-org/synapse/pull/5623)

**Comment by turt2live** [comment]
almost certainly because Alice's read receipt isn't advanced, and Riot optimistically clears the count. The return of the badge is because the room is synced and the server still hasn't received a RR, therefore Riot trusts the counts.

**Comment by jryans** [comment]
It's true that Alice's read receipt isn't advanced, and yes, advancing it would clear the count on the server.

However, all of the regular messages (non-reaction events) in the room are from Alice. So why is the notification count growing...?

The growing notification count seems to be tied to step 2 ("room is set to noisy notifications"). Setting a room to noisy means we set a room-specific push rule that notifies for _all_ events (and room-specific rules do not support conditions), so this means Bob's reaction events are incrementing Alice's notification count.

It's not clear how to best resolve this... It could make sense to do one of:

* Alter room-specific push rules to only affect `m.room.message` events
* Support conditions on room-specific push rules

**Comment by turt2live** [comment]
The messages causing notifications are from Bob in the original post, not Alice. If Alice is sending messages and the notification count isn't going down, it sounds like a Synapse bug. If Bob is sending messages (or reactions, for that matter) and Alice has noisy notifications, then push rules are somewhat working as intended.

We probably just need a push rule for "notify on reactions" which overrides the noisy setting.

**Comment by jryans** [comment]
> The messages causing notifications are from Bob in the original post, not Alice.

Alice is sending only regular messages (see step 3). (I edited the original post to add "to Bob".)
Bob is sending only reactions (see step 4).

> If Alice is sending messages and the notification count isn't going down, it sounds like a Synapse bug. 

Alice sending more message doesn't not clear their own notification count, as currently only advancing Alice's read receipt will do that, and sending messages doesn't advance your read receipt. (Should it...?)

> If Bob is sending messages (or reactions, for that matter) and Alice has noisy notifications, then push rules are somewhat working as intended.

Bob is sending only reactions. 

If Alice uses only "Messages in one-to-one chats" set to "Noisy" (which is the default for a new account), there is no issue because that the `.m.rule.room_one_to_one` underride rule includes a condition to check that the event type is `m.room.message`. (However, this differs from the spec's definition of the push rule... Filed [spec issue](https://github.com/matrix-org/matrix-doc/issues/2150).)

If however Alice sets the room-specific notification settings to "All message (noisy)", then this sets the room-specific push rule which does not support conditions (such as on the event type).

From a product perspective, we believe the default behaviour should be that reactions do _not_ trigger notifications. What's the best route to achieve that?

> We probably just need a push rule for "notify on reactions" which overrides the noisy setting.

To achieve the product goal then, would you recommend adding a "don't notify on reactions" rule by default, or instead tweaking room-specific rules somehow to only match `m.room.message`?

**Comment by turt2live** [comment]
> Alice sending more messages will not clear their own notification count, as currently only advancing Alice's read receipt will do that, and sending messages doesn't advance your read receipt. (Should it...?)

The server should be synthesizing a receipt for the user on their own messages. 

----

On the product goal: This stinks of needing to recosnider what "All Messages (noisy)" means entirely. Currently it'll fire notifications for any event, regardless of type, which is the root cause of the issue here (I think). My understanding is that the product wants to maintain the "all events cause notifications" requirement for the notification level, however reactions have somehow ended up being a special case (whereas any hidden event is not, despite creating the same problem).

**Comment by jryans** [comment]
After chatting with @dbkr and @lampholder today, we're thinking a good approach would be to add a new default override push rule that disables notifications for reactions.

I'll create an MSC similar to https://github.com/matrix-org/matrix-doc/pull/1930 for `m.room.tombstone` events.

**Comment by jryans** [comment]
Considering this done from a Riot Web perspective. The Synapse PR and MSC are still outstanding, but the original issue is effectively fixed in Riot.
