### ISSUE TITLE
Implement final RoomDirectory search UI/UX

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1020]

**Comment by grahamperrin** [comment]
Is this issue 1020 within the scope of the following? 

- [Fullblown search UI · Issue #1854 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/1854)

**Comment by aaronraimist** [comment]
I'm assuming whatever "final" room directory search UI/UX this issue is referencing has long since been replaced
