### ISSUE TITLE
Do not display phone and video icon if TURN server is not enabled in Synapse config

### ISSUE THREAD

**Issue by menturion** [vector-im/riot-web#10201]
Do not display ...

-- phone (class `mx_MessageComposer_voicecall`) and 
-- video (class `mx_MessageComposer_videocall`)

... icon if TURN server is not enabled in Synapse config.

![2019-06-28_133216](https://user-images.githubusercontent.com/41576848/60339933-7486eb80-99aa-11e9-831e-eb53390e4ae4.jpg)

**Comment by t3chguy** [comment]
But you *CAN* make calls without TURN, TURN is only needed to navigate certain network configurations and/or firewalls

**Comment by t3chguy** [comment]
FTR, my personal homeserver does not have TURN and I make calls just fine on all my networks :D

**Comment by menturion** [comment]
@t3chguy 

Thanks for the info! I didn't know that.
Any Synapse settings needed for this to work w/o TURN?

**Comment by t3chguy** [comment]
Nope, Synapse is not involved at all if you don't have TURN, it'll be a p2p call

**Comment by menturion** [comment]
So it works out of the box?
Last time I tried to start a call an error  msg popped up.

**Comment by t3chguy** [comment]
It depends on the network around the parties involved in the call

**Comment by t3chguy** [comment]
Please ask in #webrtc:matrix.org or #riot:matrix.org if you have further questions

**Comment by menturion** [comment]
Ok, many thanks! 
Will check this again.
