### ISSUE TITLE
/usr/bin/riot-desktop: line 3:     8 Trace/breakpoint trap   (core dumped) electron /usr/lib/riot/ "$@"

### ISSUE THREAD

**Issue by qazip** [vector-im/riot-web#10217]
### Description

Updated riot-desktop from the arch repository (it also updated electron and riot-web). It no longer starts.

### Steps to reproduce

- Try to open riot;
- Notice it doesn't open;

Here is the output:
`/usr/bin/riot-desktop: line 3:     8 Trace/breakpoint trap   (core dumped) electron /usr/lib/riot/ "$@"`

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Arch linux
- **Version**: Doesn't open, can't check. But it's the latest version at the time of this issue.

**Comment by jryans** [comment]
Are you able to other Electron-based apps?

Can you attach a debugger to find out more about where Electron crashed here?

**Comment by qazip** [comment]
I think I can. Spotify opens just fine.

How would I debugg?

**Comment by jryans** [comment]
The ["Examining a core dump" section from the Arch wiki](https://wiki.archlinux.org/index.php/Core_dump#Examining_a_core_dump) seems helpful here. If we can get the backtrace from the failure point, it may help identify what's going wrong.

**Comment by t3chguy** [comment]
> I think I can. Spotify opens just fine.

I don't think Spotify is Electron, but it is still Chromium based

**Comment by qazip** [comment]
I found the issue. It has to do with firejail. Running without firejail doesn't make riot crash. I'll raise an issue on their repos.
