### ISSUE TITLE
issue of account creation

### ISSUE THREAD

**Issue by leela52452** [vector-im/riot-web#10213]
please let know this is the right place

i have created an account on https://riot.im/app/#/register

when i try to login with same username at https://riot.im/app/#/login, it shows incorrect password

i did not use optional email address.

fennec 67.0.3
android 5.1

**Comment by leela52452** [comment]
the issue is resolved

my observations:
disabled all webextensions except "htts everywherr" on fennec 67.0.3 ( it seems to me website uses javascript heavily )
requires extremely stable internet connection

**Comment by t3chguy** [comment]
Yes, this app is wholly Javascript. Riot connects directly to a matrix server so has to do everything locally
