### ISSUE TITLE
Reaction tooltip not popping up when reaction button clicked on touchscreen

### ISSUE THREAD

**Issue by Cnly** [vector-im/riot-web#10225]
### Description

The reaction tooltip is not popping up when the reaction button is clicked on a touchscreen. It has no problem when I'm using a mouse.

This can also be reproduced with the mobile simulator in Chrome DevTools.

### Steps to reproduce

- Click the reaction button on a touchscreen.

### Version information

- **Platform**: Web
- **Browser**: Chrome 76.0.3809.38
- **OS**: Chrome OS
- **URL**: riot.im/develop

**Comment by jryans** [comment]
It turns out this is also fixed by some tweaks I am making to the tooltip.
