### ISSUE TITLE
Soft logout: Rehydrate session from soft logout page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10236]
Depends on https://github.com/vector-im/riot-web/issues/10235

**Comment by turt2live** [comment]
Re-hydrating the session is a bit non-trivial for https://github.com/vector-im/riot-web/issues/10235, so using this issue to track it.

**Comment by turt2live** [comment]
Hijacking this for our new design which is essentially an embedded login page rather than navigating elsewhere.

**Comment by turt2live** [comment]
SSO deferred to https://github.com/vector-im/riot-web/issues/10238

**Comment by nadonomy** [comment]
Latest Zeplin: https://zpl.io/a89QL5x
