### ISSUE TITLE
MemberInfo with wide userid doesn't get truncated, so pushes out width of RightPanel to occlude MiddlePanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1023]
So you end up with read receipts or whatever on the RHS of MiddlePanel getting hidden.

**Comment by ara4n** [comment]
https://matrix.org/_matrix/media/v1/download/matrix.org/efoVHPqYzdjpfDjzbsXHQSQJ

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/52818313-a2a30900-3063-11e9-94e4-79723ce90484.png)

Fixed
