### ISSUE TITLE
Soft logout: Actually show the page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10235]
Using designs from https://github.com/vector-im/riot-web/issues/10224#issuecomment-507777092

Conditions: when the user receives a 401 with `soft_logout: true`, redirect to page.

Page requirements:
* [x] Sign in button goes to login (prefill left as https://github.com/vector-im/riot-web/issues/10236)
* [x] Clear data clears data
* ~~Logout section conditional on key backup status~~
* ~~Key export if needed (https://github.com/vector-im/riot-web/issues/9444 / https://github.com/vector-im/riot-web/issues/10249)~~

**Comment by nadonomy** [comment]
As per https://github.com/vector-im/riot-web/issues/10224#issuecomment-508065453, we should also action:

> The client knows whether or not (a) the user had server side key backup enabled (b) if they did, whether any local keys aren't backed up. Therefore, we should only show the "I don't want to sign in again" section to users that don't have keys backed up, and not trouble users who do.

**Comment by turt2live** [comment]
Mostly as a note to myself:

@lampholder had a conversation with M&A about the key backup/export button. tldr is it won't be there now. Updated comps coming later.

**Comment by nadonomy** [comment]
@turt2live Zeplin is now updated based on the latest requirements: https://zpl.io/a89QL5x
