### ISSUE TITLE
There is a bug when entering a Chinese character

### ISSUE THREAD

**Issue by crazecoder** [vector-im/riot-web#10253]
### Description

When entering a Chinese character, receiving a message from someone else will lead to incomplete Chinese character input. The guess is the reason why the focus of the input box changes during the input process

### Version information

For the desktop app:

- **OS**:macOS
- **Version**: 1.2.2

**Comment by windsOne** [comment]
I hope to support more, there are many Chinese users and need support.

**Comment by jryans** [comment]
The sounds like another version of https://github.com/vector-im/riot-web/issues/7665. We hope to replace the composer with a different approach soon that should fix issues like this. I know it's quite frustrating! 😭 Thank you for your patience.
