### ISSUE TITLE
Riot doesn't tell me anymore if I have new unread messages under the ones I'm seeing on screen

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10257]

**Comment by jryans** [comment]
Does anyone know when this was last believed to work? (Trying to spot whether it's a regression, and if so, when it may have appeared.)

**Comment by turt2live** [comment]
Worked in 1.2.2

**Comment by bwindels** [comment]
Neither me or Travis can reproduce this in the room (#ping:maunium.net) where he used to be able to repro this. I tried on /app, riot 1.2.3.

**Comment by turt2live** [comment]
Closing due to no further information - probably fixed at some point.
