### ISSUE TITLE
Please reinstate the ability to react with non-unicode keys

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#10256]
A recent change seem to have been to not display any reaction events which don't have a single (unicode?) character as a reaction key.

Please consider reversing this. I am working on bridging reactions to slack (matrix-org/matrix-appservice-slack#131) and I had implemented bridging custom emoji from slack to matrix using just the short code, so the reaction would come across into matrix as `:partyparrot:` or whatever. This, while being much more ugly in comparison to the actual custom emoji, at least allows the information that people have reacted with that custom emoji to come over into matrix, until we get our own custom emoji implementation.

I understand the desire to restrict the reaction field (as fun as it is to react with 64K of text), but can we loosen it a little to maybe 20 characters or something?

**Comment by Half-Shot** [comment]
Agreed. There is merit to being able to react with shortcodes from a bridging PoV.

**Comment by f0x52** [comment]
I think you could also (ab)use text reactions to have an in-line way to communicate with a bot, which will listen for reactions to do certain actions

**Comment by tulir** [comment]
Buttons (matrix-org/matrix-doc#1485 / matrix-org/matrix-react-sdk#2109 or something) would provide a better solution for @f0x52's use case (which is also my use case), but from a reaction bridging PoV I definitely support text reactions being allowed too.

**Comment by ara4n** [comment]
this is getting fixed. but we're drawing the line at anything longer than `:partyparrot:`

**Comment by Cadair** [comment]
Oh! Now I wish I had considered my example more carefully :stuck_out_tongue: 

(`:partyparrot:` is 13 characters, 20 seems reasonable?)

**Comment by Half-Shot** [comment]
@Cadair surely we just need to whitelist every shortcode used by Slack :) /s
