### ISSUE TITLE
Go to first unread button only half responsive

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10254]
On Riot-web 1.2.2 (and a few versions before), on Windows 7, black theme:
The (^) button at the top right of the message area that appears when the first unread message has scrolled off the screen is only responsive to clicking on its lower half.  In other words: the picture of the button does not correspond to the click-sensitive area.

**Comment by lampholder** [comment]
Hey @Biep can you say what os/browser/version you're running? Thanks

**Comment by Biep** [comment]
Oops - sorry!  Updated the description.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/79056954-a9231580-7c53-11ea-9800-8b8196bc6343.png)

looks fine nowadays
