### ISSUE TITLE
Debug logs dialog pops up a JS error

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10261]
![image](https://user-images.githubusercontent.com/1342360/60673921-d646ca00-9e70-11e9-9d3b-cdf9af402b63.png)

### Description

The JS console displays an error that doesn't affect functionality, but it should probably be fixed:

```
Warning: Failed prop type: The prop `id` is marked as required in `Field`, but its value is `undefined`.
    in Field (created by BugReportDialog)
    in BugReportDialog (created by AsyncWrapper)
    in AsyncWrapper
    in div
    in div
```

### Steps to reproduce

- Upon up the submit debug logs dialog
- backtrace appears

Log: sent

### Version information

- **Platform**: web

- **Browser**: Firefox v69.0a1
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by jryans** [comment]
So when I added the `Field` component, I made it require an `id` prop so the `label` and `input` can be joined together as intended by the HTML spec. However, I don't think it actually enables any functionality, which means people frequently don't add them.

I would suggest removing the `id` prop from the `Field` component and all usages. Alternatively, let's at least mark it as an optional prop.

**Comment by gate3** [comment]
Hi, 

Just made a PR for this: [https://github.com/matrix-org/matrix-react-sdk/pull/3945](https://github.com/matrix-org/matrix-react-sdk/pull/3945)

**Comment by t3chguy** [comment]
> However, I don't think it actually enables any functionality, which means people frequently don't add them.

It is important for accessibility technologies
