### ISSUE TITLE
update error Debian stretch, "NO_PUBKEY C2850B265AC085BD"

### ISSUE THREAD

**Issue by johays** [vector-im/riot-web#10278]
### Description

When updating Debian Stretch system with `sudo apt-get update && sudo apt-get dist-upgrade` I get the an GPG-error NO_PUBKEY C2850B265AC085BD

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.riot.im/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD
W: Failed to fetch https://riot.im/packages/debian/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD
`

Trying to fix the gpg-error, I follow the install-guide for Stretch on https://riot.im/download/desktop/ with a negative result. I have updated my system many times without experiencing this error.

System has been upgraded from Jessie some months ago with no other noticeable issues. 

### Steps to reproduce

- Install Riot-web on a Debian Jessie system 
- Upgrade system to Debian Stretch
- Run `sudo apt-get update && sudo apt-get dist-upgrade` and see the following GPG-error.

FULL TERMINAL OUTPUT WHEN FOLLOWING INSTALL-GUIDE ON https://riot.im/download/desktop/:

```
[username]@[systemname]:~$ sudo apt install -y lsb-release wget apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.4.9).
lsb-release is already the newest version (9.20161125).
lsb-release set to manually installed.
wget is already the newest version (1.18-5+deb9u3).
The following packages were automatically installed and are no longer required:
  icedtea-netx icedtea-netx-common
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

[username]@[systemname]:~$ sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg
--2019-07-07 11:59:21--  https://packages.riot.im/debian/riot-im-archive-keyring.gpg
Resolving packages.riot.im (packages.riot.im)... 104.25.36.105, 104.25.35.105, 2606:4700:20::6819:2469, ...
Connecting to packages.riot.im (packages.riot.im)|104.25.36.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2887 (2.8K) [application/octet-stream]
Saving to: /usr/share/keyrings/riot-im-archive-keyring.gpg

/usr/share/keyrings/riot-im-archive-k 100%[=======================================================================>]   2.82K  --.-KB/s    in 0s      

2019-07-07 11:59:21 (11.6 MB/s) - ‘/usr/share/keyrings/riot-im-archive-keyring.gpg’ saved [2887/2887]

[username]@[systemname]:~$ sudo apt-get update
Hit:1 http://ftp.debian.org/debian stretch-backports InRelease
Hit:2 http://security.debian.org stretch/updates InRelease                                                                                     
Hit:3 http://deb.qubes-os.org/r3.2/vm stretch InRelease                                                                                        
Hit:5 http://prerelease.keybase.io/deb stable InRelease                                                                  
Hit:6 https://packages.riot.im/debian stretch InRelease
Ign:4 http://cdn-fastly.deb.debian.org/debian stretch InRelease                         
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch Release                           
Get:9 https://packages.riot.im/debian stretch InRelease [2,894 B]
Err:9 https://packages.riot.im/debian stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD
Fetched 2,894 B in 1s (2,081 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.riot.im/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD
W: Failed to fetch https://riot.im/packages/debian/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Version information

- **Platform**: desktop
- **OS**: Debian Stretch  (as standalone VM in Qubes-OS )
- **Version**: 1.0.7

**Comment by jryans** [comment]
What does `/etc/apt/sources.list.d/riot-im.list` contain?

**Comment by bwildenhain** [comment]
I have the same problem having followed https://riot.im/download/desktop/ to update Riot on Debian buster (stable).

**Comment by uhoreg** [comment]
> W: Failed to fetch https://riot.im/packages/debian/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD

You have `riot.im/packages` in your apt sources list somewhere, which is the old repository location.  You need to remove that.

**Comment by johays** [comment]
In /etc/apt/sources.list.d/ there is both an entry called matrix.riot.list and riot.im.list

matrix.riot.list contains the lines:

```
# Riot (Matrix client)
deb https://riot.im/packages/debian/ stretch main
deb-src https://riot.im/packages/debian/ stretch main
```

After commenting out the lines above, `apt-get dist-upgrade` runs smooth and riot-im gets upgraded.

I'm uncertain whether the old entry failed to be deleted due to my own misconfiguration back in time, or whether its caused by a bug earlier during the sys-upgrade.

**Comment by dkasak** [comment]
This isn't related to `riot.im/packages` vs `packages.riot.im`. I just followed the instructions on the website which specifies `packages.riot.im` and I've checked that this is the only line in `/etc/apt/sources.list.d/riot-im.list`, but I'm getting the same error.
