### ISSUE TITLE
hitting escape to close preferences dialog doesn't work if a toggle button has focus

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#10286]

**Comment by uhoreg** [comment]
Also does not work if one of the left-side section selectors has focus

**Comment by t3chguy** [comment]
Cannot reproduce this
![kbd1](https://user-images.githubusercontent.com/2403652/77858892-3733e080-71fe-11ea-8309-1288182f06cd.gif)

**Comment by t3chguy** [comment]
Team tried to repro live and could not :'(

**Comment by uhoreg** [comment]
Indeed.  This seems to be working now.  I'm closing this as the original reporter.
