### ISSUE TITLE
Broken code blocks - dropping first line

### ISSUE THREAD

**Issue by jombug** [vector-im/riot-web#10284]
# Description

When using markdown ``` code ```, riot-web (version 1.2.2) drops the first line but creates pretty code block.
If not using markdown but selecting "inline-code", it does not make a code block, but every line is on individual blocks. 

Please see how it is done for example in slack.

**Comment by turt2live** [comment]
I can't reproduce this, what's the message you're sending?
![image](https://user-images.githubusercontent.com/1190097/60833308-32646380-a17b-11e9-8f43-95cd471bf141.png)

**Comment by jombug** [comment]
it seems that if there is no line break after heading ```, it will drop the first line. also if last line ends with ```, it will printed in to the block.

**Comment by turt2live** [comment]
Unfortunately that's a Commonmark feature:
https://commonmark.org/help/tutorial/09-code.html
![image](https://user-images.githubusercontent.com/1190097/60834680-71e07f00-a17e-11e9-818d-fa7544110e4e.png)

**Comment by jombug** [comment]
Thanks for clarification. As an old slack user I already forgot this actually is markdown. don't know about the background for markdown support on chat but would be nice to have slack-like triple tick support on that non-markdown mode. The feature is used by tons of developers, who copy paste code to chat minute basis.

Thanks!
