### ISSUE TITLE
Deploy reactions and edits as enabled by default

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#10281]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2558  

They should be enabled by default.

**Comment by jryans** [comment]
For Riot Web at least, I don't think we'll remove the setting themselves just yet. We do need to remember to deploy reactions and edits as enabled by default though, so I have morphed the issue into that. As a follow up several weeks later (when we're sure we don't want the flag any more), we can remove the settings checks.

**Comment by jryans** [comment]
We've changed the implementation plan slightly: we'll change the default value of the settings to true, so no config file change are needed to enable the features when deployed.

**Comment by jryans** [comment]
This has also merged to the Riot 1.3.0 release branch.
