### ISSUE TITLE
Solid color squares shown instead of emoji in 1.2.2 and 1.2.3 (Mac Desktop version)

### ISSUE THREAD

**Issue by lascapi** [vector-im/riot-web#10296]
Hi, I found an issue, similar to https://github.com/vector-im/riot-web/issues/10143 : 

Solid color squares shown instead of emoji in 1.2.2, worked in 1.2.1.

The emoji is actually there but isn't displayed correctly; copying it to another program makes it show up correctly over there.

- Intall the Desktop Application for Mac
- open a discution with emoji on 
- there is square and not emoji 

On the app
![riot-desktop](https://user-images.githubusercontent.com/6562527/60919266-98dda480-a295-11e9-8edf-91b1ade66a01.png)
On Firefox
![riot-web](https://user-images.githubusercontent.com/6562527/60919268-98dda480-a295-11e9-8216-c16dcc85ffe1.png)

Other Unicode like chinese characters seems to be good. 

### Version information
For the desktop app:

- **OS**: macOS 10.11
- **Version**: 1.2.2 and 1.2.3

**Comment by jryans** [comment]
This is a complex tale of various libraries and versions:

* Riot 1.2.3 desktop uses Electron 4.2.6
* Electron 4.2.6 is [built on](https://github.com/electron/electron/blob/v4.2.6/DEPS#L13) Chromium 69
* Full COLR support regardless of OS support [was (probably) enabled](https://www.chromestatus.com/feature/5897235770376192) with Chromium 71
* When Riot loads, it detects COLR support as not available, so it loads the SBIX fallback fonts
* For some reason, the SBIX version is apparently being chosen by font selection even though it doesn't draw correct glyphs for you

Can you open the DevTools in Riot (Cmd-Opt-I), go to the Network tab, select the Font filter, reload the app with Cmd-R, and take a screenshot / copy a list of the font files loaded?

**Comment by jryans** [comment]
(Electron 5.0.6 is [built on](https://github.com/electron/electron/blob/v5.0.6/DEPS#L13) Chromium 73, so this could become a strong reason to upgrade.)

**Comment by lascapi** [comment]
Hi, there is fonts : 

Nunito-Regular.ffae5d0.ttf | 200 | font | Tinter.js:248 | (from memory cache) | 0 ms
-- | -- | -- | -- | -- | --
Nunito-SemiBold.da07a44.ttf | 200 | font | Tinter.js:248 | (from memory cache) | 0 ms
Nunito-Bold.f7e8fbd.ttf | 200 | font | Tinter.js:248 | (from memory cache) | 0 ms
QldKNThLqRwH-OJ1UHjlKGlZ5qhExfHw.5476fd3.woff2 | 200 | font | Tinter.js:248 | (from memory cache) | 0 ms
TwemojiMozilla-sbix.661486d.woff2 | 200 | font | ScrollPanel.js:731 | 0 B | 1.34 s

![riot-font](https://user-images.githubusercontent.com/6562527/60991875-abb2b080-a34b-11e9-9b50-375495fcb8f8.png)

**Comment by noplanman** [comment]
I've got the same issue, slightly different fonts though:
![riot-web-fonts](https://user-images.githubusercontent.com/9423417/61190429-b2af2b00-a68b-11e9-904b-4026b737d587.png)

**Comment by jryans** [comment]
@lascapi @noplanman Thanks for attaching the network details.

Let's try one more test. I'd like to see the result of the test site https://pixelambacht.nl/chromacheck/ inside the Riot app for you.

Here's a way to achieve that:

1. Open DevTools in Riot (Cmd-Opt-I)
2. Go to Console tab
3. Enter `location.href = "https://pixelambacht.nl/chromacheck/"`
4. Capture a screenshot of the result
5. Enter `history.back()` to go back to Riot

**Comment by noplanman** [comment]
![riot-supported-fonts](https://user-images.githubusercontent.com/9423417/61537272-41be9900-aa26-11e9-8d5d-b48484383cd1.png)

**Comment by jryans** [comment]
Hmm, but it very plainly is _not_ supported in reality... 😭 I'll try to think about what could be done here.

**Comment by jryans** [comment]
I have upgraded Riot to Electron 5, which I am hoping will fix this issue. 

If you are feeling adventurous, you could try to [building the develop branch](https://github.com/vector-im/riot-web#running-as-a-desktop-app) of Riot to see whether it fixes this for you. Our next stable release of Riot will use Electron 5, so you can also wait for that (should be in the next few weeks).

**Comment by noplanman** [comment]
@jryans Hope it's ok to pop the question here, but is there an easy way to build the electron app using the docker image from the develop branch? Because it's the electron app that needs the testing, the web version works fine.

**Comment by turt2live** [comment]
@noplanman you don't need Docker to build the electron image. There's some instructions in the readme, however the steps are roughly: `yarn install electron@5 && yarn build && yarn electron` and it should give you an electron to test with (not installed over top, just long enough to verify the problem is fixed).

**Comment by noplanman** [comment]
Thanks @turt2live, thought it was more involved, but turned out to be super simple :tada: 

Latest dev brings back the Emojis, awesome @jryans :muscle:
