### ISSUE TITLE
one notification alwayson taskbar/titlebar on windows desktop and web riot client (just installed)

### ISSUE THREAD

**Issue by dreamerchris** [vector-im/riot-web#10293]
checked all my rooms and dms and I have no notifications but in taskbar and titlebar it shows always one notification

edit: I just want to clarify that notification count works ok, the problem is that notification count is always plus one and when I have read all chats there still remains one notification at the taskbar/tittlebar

edit2: also I created the issue in the web/desktop riot matrix chat in riot desktop program but as I see this was loaded as riot-web repo!

edit3: get it on web client to, and one more guy has the same issue

**Comment by aaronraimist** [comment]
There are already several
Issues about this. There are various causes but it may make more sense to just comment on an existing issue such as https://github.com/vector-im/riot-web/issues/3059. Also make sure you are submitting debug logs, that is the only way for them to figure out what is happening.

**Comment by RonnyPfannschmidt** [comment]
im also observing the issue

**Comment by jryans** [comment]
As far as I can tell, this is the same as #3059, so let's close this one. Please let me know if this is distinct somehow.
