### ISSUE TITLE
Partial user profile without close button from matrix.to user links

### ISSUE THREAD

**Issue by Lrizika** [vector-im/riot-web#10306]
### Description

Clicking a matrix.to user link (e.g. https://matrix.to/#/@nobody:example.com) within Riot opens a partial user info pane, including only info about devices - and lacking a way to close the info panel. Notably, this occurs even for users that actually exist and are in that room (the expected behaviour would be to open the profile page as if you had clicked their avatar.)

These links are automatically created when a user ID is sent in a message.

![Screenshot from 2019-07-10 14-05-44](https://user-images.githubusercontent.com/8592308/61005083-50b59500-a31c-11e9-914e-9775822202ab.png)

### Steps to reproduce

- Send a message including a user ID
![Screenshot from 2019-07-10 14-11-58](https://user-images.githubusercontent.com/8592308/61005347-e5b88e00-a31c-11e9-8deb-741c65e1dd2c.png)
![Screenshot from 2019-07-10 14-12-21](https://user-images.githubusercontent.com/8592308/61005379-f10bb980-a31c-11e9-80f4-c52ef908469b.png)
- Click the automatically-created link
- There's no way to close the user panel that is opened

There should be a close button, like on user panels that are opened when you click a user avatar. Also, if the user exists within the room, it should provide the full user information panel, rather than the partial one.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 60.7.2esr (64-bit)
- **OS**: CentOS 7.6
- **URL**: private instance (riot-web version: 1.2.2)

**Comment by turt2live** [comment]
for the reproduction scenario: pasting the link doesn't work, the user ID has to be typed out.

**Comment by Lrizika** [comment]
Oh, interesting - if you paste the link it gets changed to a relative #/user/[the user id] link, which leads to either an error and a completely blank page for nonextant users, or a blank page with the same partial info pane for users that do exist. Not sure if that's expected behaviour - right now it's rather useless, but it may be helpful when extensible user profiles come along.

**Comment by aaronraimist** [comment]
This fails much worse using the new memberinfo
<img width="754" alt="Screen Shot 2020-01-26 at 7 42 00 PM" src="https://user-images.githubusercontent.com/5855073/73145593-0a374600-4074-11ea-938b-fdd65cb21810.png">

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/73475743-d8322680-4388-11ea-9f11-283d8a60e3c7.png)

works fine for me in the new UserInfo

original bug is about MemberInfo not having a close button if looking at a member which does not exist in a room, this is fixed by UserInfo, if you can repro the above @aaronraimist then please rageshake, link here and re-open but I believe it got fixed in the last couple of days with the bunch of null guards which got thrown at UserInfo

**Comment by aaronraimist** [comment]
Yeah seems to have been fixed in the last few days
