### ISSUE TITLE
Icon on Windows destkop again

### ISSUE THREAD

**Issue by Metzlmane** [vector-im/riot-web#10313]
On every Update after "there is a new version of Riot", I get the shortcut Icon on the Desktop again.
Could there be an option to avoid this?

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4601

**Comment by zingmars** [comment]
No it's not. The linked issue is about tray icons, this is about desktop shortcuts being created after update. The issue is also still present, so please re-open.

**Comment by t3chguy** [comment]
Duplicate of #9210 then
