### ISSUE TITLE
riot-web implements m.login.password UI auth incorrectly

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#10312]
The [spec](https://matrix.org/docs/spec/client_server/r0.5.0#password-based) says that the client should submit a dict including an `identifier` object. In practice riot-web just sends a `user` field.

Fixing this is blocked by fixing the synapse end (https://github.com/matrix-org/synapse/issues/5665)

**Comment by turt2live** [comment]
Is this on login or sometime else?

**Comment by richvdh** [comment]
I noticed it on device deletion. `m.login.password` isn't used for register, because you don't have a password to authenticate with at that point.

**Comment by turt2live** [comment]
Good point. This is probably broken for several places because we don't use a common library for it

**Comment by anoadragon453** [comment]
The correct behaviour seems to be implemented on normal login.

**Comment by turt2live** [comment]
Login doesn't use UIA.
