### ISSUE TITLE
Cannot leave a replaced room (#matrix-dev:matrix.org)

### ISSUE THREAD

**Issue by Alexendoo** [vector-im/riot-web#10323]
### Description

I used matrix a while ago and join the matrix-dev channel at that time, which seems to be no longer in use. I can try leaving it but I receive an error

```
Failed to leave room

@Alexendoo:matrix.org not in room !DYgXKezaHgMbiPMzjX:matrix.org.
```

![riot](https://user-images.githubusercontent.com/1830331/61087664-2eac3780-a42e-11e9-8efd-0d111fff63fe.png)

Oddly, the URL for the page is `https://riot.im/app/#/room/#matrix-dev:sputnik-messenger.com`

### Version information

- **Platform**: web (in-browser)
- **Browser**: Google Chrome | 76.0.3809.62 (Official Build) beta (64-bit)
- **OS**: Windows 10 OS Version 1809 (Build 17763.615)
- **URL**: riot.im/app

**Comment by Alexendoo** [comment]
+ submitted debug logs

**Comment by turt2live** [comment]
Looks like the server and Riot disagree on whether or not you're in the room - try going to Settings then under Help & Support press "Clear Cache and Reload". It should resolve the issue.

**Comment by Alexendoo** [comment]
That seems to have worked, thanks. I was kicked for inactivity

![image](https://user-images.githubusercontent.com/1830331/61088682-cc086b00-a430-11e9-984d-1a7f778cb777.png)

I was able to forget the channel afterwards. Not sure if there's a bug for that somewhere but I'll close this one in any case, since I'm confident I could reproduce it again without a time machine

**Comment by aflatter** [comment]
@turt2live @Alexendoo Hello! I experienced the same thing. The channel was stuck and I wasn't able to leave it. Found this issue via Google, cleared my cached and then got a message telling me that I got kicked because of inactivity. After that, I was able to join again. From a user experience point of view, this seems to be a bug.
