### ISSUE TITLE
Youtube widget stuck loading (Update Regression)

### ISSUE THREAD

**Issue by jph168** [vector-im/riot-web#10324]
### Description
since update 1.2.3-1 youtube widgets are stuck loading. Tested riot 1.2.2-2 this issue does not occur, I'd definitely assume a regression in 1.2.3-1 and also in 1.2.4-1 desktop app not web versions. I wouldn't be able to say this issue is also on windows or Macos Desktop Clients. Clearing cache and reloading does not resolve this.
### Steps to reproduce
1. Create Youtube widget in channel
2. Try playing it
3. You'll get a message from youtube saying "If playback doesn't begin shortly, try restarting your device." from constantly trying to load.

Log: sent/not sent? Tried, sadly Client was stuck preparing to send them. Idt it went through..
![Screenshot_2019-07-11_21-00-19](https://user-images.githubusercontent.com/31376624/61101624-534ce300-a41f-11e9-9140-4a35bc9d5a27.png)

### Version information

- **Platform**:Linux Desktop Client.
For the web app: unaffected completely

- **Browser**: Tested with Chromium
- **OS**: Linux
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? None of the Web versions are affected.

For the desktop app: Youtube widget does not load.

- **OS**: Linux
- **Version**: 1.2.3-1 & 1.2.4-1

**Comment by turt2live** [comment]
hmmm... I'm not able to reproduce this. Is it possible to get debug logs for this? (go to your settings, then on the Help & About tab click "Submit Debug Logs" and reference this issue).

**Comment by jph168** [comment]
I'm so sorry, it just took a reboot to fix this..must've had to in order to finish the upgrade..Keep up the great work guys :)

**Comment by turt2live** [comment]
Looks like the update went bad and it self-corrected or something when you restarted. Glad it worked out in the end though!
