### ISSUE TITLE
Alt+Up should go back further in history regardless of text in the composer

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10325]
### Description

Pressing <kbd>Alt</kbd>+<kbd>Up</kbd> only goes up to the last message in history when the composer is empty, whereas <kbd>Alt</kbd>+<kbd>Down</kbd> will go forward in history whether the composer is empty or full.

### Steps to reproduce

- Enable editing
- Write and send a few messages
- Try to page up and down through them
- Note that to go up, you need to clear the composer content each time
- However, going down works as expected.

Log: not sent?    

### Version information

- **Platform**: web
- **Browser**: Firefox v69.0a1
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I think it's only when your caret is at the start rather than empty or not

**Comment by anoadragon453** [comment]
Ah, true. But since Riot helpfully puts your cursor at the end it's quite hard to use.

Is there any reason for this restriction?

**Comment by t3chguy** [comment]
No idea, I don't think it was there when I wrote it originally

**Comment by turt2live** [comment]
This is a compromise for keeping the ability to go up in history while also not editing. Considered a feature at the moment.

**Comment by jryans** [comment]
I think we need input from @lampholder on whether to proceed with a change here. In the https://github.com/matrix-org/matrix-react-sdk/pull/3254, @turt2live remembers us not doing this for some reason, but we can't remember why or where it was discussed.

**Comment by jryans** [comment]
@lampholder reviewed during the standup, and suggests we proceed making a change here and watch out for feedback in case any one is negatively affected by the behaviour change.
