### ISSUE TITLE
Control-Shift-U is no longer recognised for Unicode character composition

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#10338]
[Allow default for ctrl+shift+b, ctrl+shift+u in RTE by lukebarnard1 · Pull Request #1274 · matrix-org/matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk/pull/1274) was merged – #4750 was fixed – in 2017. 

<kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd> no longer has the required effect – keystrokes after the chord are misinterpreted as literal characters so, for example I get: 

- `2026 ` instead of `…`
- `2013 ` instead of `–`

– and so on. 

A regression? 

I noticed the bug a few months ago. First with Waterfox Classic on KDE Plasma on FreeBSD-CURRENT. 

Reproducible with Waterfox Classic 56.2.12 and Firefox 68.0.

**Comment by t3chguy** [comment]
The PR you referenced no longer applies as it was for the old RTE, which was based on Facebook's DraftJS, Riot moved to SlateJS, can you reproduce this issue on the examples over at https://www.slatejs.org/#/rich-text ?

Thanks

**Comment by grahamperrin** [comment]
Apologies for the late response. 

The bug disappeared from https://riot.im/app/ some time ago (I can't recall when, wasn't paying much attention to the app) and is not reproducible at https://www.slatejs.org/#/rich-text
