### ISSUE TITLE
Message forwarding needs fixing for redesign

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10335]
Context menu on an event -> forward.

**Comment by richvdh** [comment]
s/room/event/ ?

**Comment by turt2live** [comment]
technically message, but yes - thanks

**Comment by aaronraimist** [comment]
Related/dup: https://github.com/vector-im/riot-web/issues/10165

**Comment by jryans** [comment]
Yes, I think we can treat this as a duplicate of https://github.com/vector-im/riot-web/issues/10165.
