### ISSUE TITLE
Display unread message counter in room list for muted rooms

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#10342]
At now, when user mutes the room, room only becomes bold on new unread messages. Most of other messengers (Telegram, VK, Viber) mutes only notifications from room, but still display unread counters in room list for muted rooms.

Can Riot implement same behavior and mute only notifications for muted rooms, with continue displaying unread message counter in room list?

Current "bold only" mode is useful too, but more for "Low priority" rooms section, so will be good to have both mute ways together.

**Comment by turt2live** [comment]
We have made a decision that if a room is muted then the user doesn't care about the count at all. Currently the best possible approach is to set the room to 'Mentions & Keywords', and in future the notifications work should address this further.

**Comment by abitrolly** [comment]
Is it possible to show the unread message counter in channel view behind unread jump button (or directly on it)?
