### ISSUE TITLE
Editing a message which pings someone after they've replied causes a stuck notification

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10345]
1. Get pinged
2. Send a message
3. Have the other person edit their message in step 1

Room is now stuck as a notification. Switching rooms and back clears it temporarily, until someone's read receipt comes down which resets the counts (Synapse sends new counts)

**Comment by bwindels** [comment]
Sounds similar to https://github.com/vector-im/riot-web/issues/10314, is this still reproducable in 1.3.0? I would expect this to be fixed with that bug.

**Comment by turt2live** [comment]
Looks like this is indeed fixed. Thanks!
