### ISSUE TITLE
Toggling markup while citing prevent sending the message

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10352]
I chose 'quote message' and then switched markup on.  The result was that the > signs appeared, but the quotation bars didn't disappear - and hitting enter only added returns to the message.  I could no longer send or discard the message, and was effectively prevented from writing in that room.

**Comment by jryans** [comment]
Is there any way to work around it, such as switching rooms and coming back, for example?

**Comment by Biep** [comment]
I managed to get out of it, but am unsure how.  Switching rooms, or restarting Riot, didn't work.
If I have time and feel courageous I'll create a test room and try to recreate the effect.

**Comment by t3chguy** [comment]
No longer an issue
