### ISSUE TITLE
User's avatar is hidden when hidden events are rendered

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10350]
![image](https://user-images.githubusercontent.com/1342360/61294149-19882d80-a7cd-11e9-9d38-f8bfe2853823.png)

### Description

Those last two messages are from Brendan, however it looks as though I'm saying them.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefoxv69.0a1
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Why are there `m.room.message` events being rendered as collapsed "unknown" event tiles...?

Could you share the source of those collapsed `m.room.message` events from Brendan?

**Comment by anoadragon453** [comment]
So the reason for this is if you have the "show hidden events" option enabled in the timeline, and a message from that same person arrives afterwards, Riot will not render a new avatar since it thinks that's already happened with a previous `m.room.message` event (the edit).

**Comment by turt2live** [comment]
Tbh I already told someone that a bug in a developer feature is the lowest priority possible unless it prevents development. To the point of it not really needing a bug report, but I guess it's good to have?

**Comment by anoadragon453** [comment]
I think it's worthwhile to have it reported.

**Comment by jryans** [comment]
Ah, I think I forgot those were just edits while reading this... 😅

It would be nice to fix at is quite confusing in the image above, but yes, as Travis says, it's a developer feature, so this will be quite low priority.
