### ISSUE TITLE
Message Editing: Remove button is available in edit history even if I don't have permissions to remove the edit

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10366]
### Description

The "Remove" button appears on message edits even if I don't have the PL to remove that message.

### Steps to reproduce
- Be in a room with someone
- Have them send a message and edit it
- See that you have a "Remove" button when viewing the edit history for that message

Riot should check if I'm able to redact the edit first before showing that button.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/10292
