### ISSUE TITLE
/rainbowme 💩 causes server error

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#10368]
because 💩 spans two utf-16 units, and they end up getting split up by the font tags from /rainbowme, resulting in invalid unicode.  Because utf-16 is a pain.  (ref https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1563499702139761sobfL:matrix.org?via=matrix.org&via=privacytools.io&via=linuxgaming.life )

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/9794#issuecomment-494607106

**Comment by t3chguy** [comment]
Rainbow emoji sure does look cool though 
![image](https://user-images.githubusercontent.com/2403652/61569242-63e40580-aa7e-11e9-8526-e93bccbc96a6.png)
