### ISSUE TITLE
Room disappears from list after a kick

### ISSUE THREAD

**Issue by z3ntu** [vector-im/riot-web#10374]
### Description

I've been kicked from a couple of freenode rooms because of an issue with the nickname and nickserv, but the rooms I have been in quietly disappeared from my room list.
I just have a big list of rooms in the "IRC Admin Room" that I can manually rejoin:
![image](https://user-images.githubusercontent.com/3768500/61580121-8160b000-ab0e-11e9-8398-e87e3d70e710.png)

but these rooms don't show up in my room list.

### Steps to reproduce

- Get kicked from a room?
- Room disappears

The rooms should still be visible and have some kind of icon to show that I have to rejoin.

### Version information

- **Platform**: Desktop
- **OS**: Arch Linux
- **Version**: 1.2.4

**Comment by turt2live** [comment]
They will have moved to historical, which is expected. Note that in the new room list this is an explicit requirement.
