### ISSUE TITLE
Writing accents on Mac

### ISSUE THREAD

**Issue by woachk** [vector-im/riot-web#10375]
### Description

When trying to write an word using accents on a Mac, the letter selected ends up being typed twice, once with the accent, once without it

### Steps to reproduce

- Press the E button and hold it.
- Press the 1 button when the prompt appears

Describe how what happens differs from what you expected.

- eè is seen instead of è when using the Riot app on macOS (Catalina).

### Version information

- **Platform**: Desktop 
- **OS**: macOS Catalina 
- **Version**: 1.3.0

**Comment by t3chguy** [comment]
This is #7665
