### ISSUE TITLE
😊 shows up under :anxious:

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#10372]
I may not be great at reading emojis, but that [sure doesn't look anxious to me](https://emojipedia.org/smiling-face-with-smiling-eyes/).

**Comment by aaronraimist** [comment]
Presumably something that should/could be opened upstream https://github.com/milesj/emojibase/issues

https://github.com/milesj/emojibase/blob/master/packages/generator/src/resources/shortcodes.ts#L71

**Comment by Half-Shot** [comment]
Raised as https://github.com/milesj/emojibase/issues/26

**Comment by Half-Shot** [comment]
This was fixed in https://github.com/milesj/emojibase/pull/27

**Comment by t3chguy** [comment]
Indeed, so once package.json/lock get bumped this can be closed
