### ISSUE TITLE
Theming documentation is obsolete

### ISSUE THREAD

**Issue by SimonMulquin** [vector-im/riot-web#10397]
**Is your suggestion related to a problem? Please describe.**

The theming documentation in docs/theming.md is obsolete and not relevant since the themes were moved to matrix-react-sdk and are currently not in src/skins/vector/css/themes as describe in theming.md

**Describe the solution you'd like**

Can someone update it ?

**Additional context**

We would like to use Riot with our matrix servers in a mutli-institutions context where it will be important for institutions to implement they own theme so the user can distinguish them when using they implementation of Riot. (also it would be appreciated to have the possibility to fetch themes on a files server rather than in node_modules)

**Comment by ptman** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3503

**Comment by aaronraimist** [comment]
This got fixed by ^
