### ISSUE TITLE
Hitting the Ctrl key bring the cursor back to the editor

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#10390]
![Peek 2019-07-22 15-12](https://user-images.githubusercontent.com/5547783/61635162-3de37e80-ac93-11e9-944d-f73ab89ce767.gif)

The text I've highlighted un-highlights itself and the cursor is brought back to the editor when I hit Ctrl, which prevents me from e.g. copying text using Ctrl+C.

Observed on latest develop, with Firefox on GNU/Linux.

**Comment by jryans** [comment]
Hmm, I would have expected https://github.com/matrix-org/matrix-react-sdk/pull/3237 to fix this ~5 days ago. What precise version of develop do you have?

**Comment by babolivier** [comment]
I'm always using `riot.im/develop`
For some reason it stopped doing that the day after I opened the issue. However, it still does it if I select the two words around a space by double-clicking on the space:

![Peek 2019-07-24 11-26](https://user-images.githubusercontent.com/5547783/61782261-0ba65e00-ae06-11e9-99bf-cfab312fd6d6.gif)

**Comment by bwindels** [comment]
I think Ryan was referring the version in "Help & About" in the settings you were seeing. /develop puts the git hashes of our 3 libraries there, e.g. for me atm:

riot-web version: 55e2f18d1e46-react-e73690439f2f-js-6cca73b9998c

This helps to exclude your cache isn't stale for some reason :)

I tried to reproduce both reported behaviours (normal selection, and selecting by double clicking space between words), but couldn't trigger the composer to focus for either on Firefox 68 on Fedora 30.

**Comment by babolivier** [comment]
Right, my current version is `55e2f18d1e46-react-ac31b4b8f411-js-6cca73b9998c` and I'm reproducing the space one (can't reproduce the normal selection one anymore, and I've no idea what my version of Riot was then) on Firefox 68 on Archlinux.

**Comment by anoadragon453** [comment]
Cannot reproduce on Debian Buster, Firefox v70.0a1. Maybe a GNOME thing?

**Comment by bwindels** [comment]
I'm on GNOME fwiw

**Comment by babolivier** [comment]
For some reason the bug shown in the issue's initial comment just reappeared.

Riot version is `55e2f18d1e46-react-cef67d5784fa-js-6cca73b9998c`

**Comment by bwindels** [comment]
> For some reason the bug as shown in the issue's initial comment just reappeared.
> 
> Riot version is `55e2f18d1e46-react-cef67d5784fa-js-6cca73b9998c`

Thanks for reporting. I am still unable to reproduce anything alike unfortunately :(

Nothing interesting in the console I suppose?
Could you send a profiling session while reproducing? (in browser devtools, go to "Performance" tab, hit start recording, reproduce, hit stop, and save.)
Does it also happen in Chromium? If so, please do the profiling there as it's a bit more informative.

**Comment by jryans** [comment]
> Could you send a profiling session while reproducing? (in browser devtools, go to "Performance" tab, hit start recording, reproduce, hit stop, and save.)

As an aside, if you want good profiling in Firefox, I recommend trying one of the following:

1. Use Firefox Nightly
2. In DevTools, go to 3 dots -> Settings -> Enable new performance recorder
3. Re-open DevTools
4. Capture in Performance tab

**or**

1. Go to https://profiler.firefox.com
2. Install add-on as it suggests
3. Use add-on to capture and share a profile

**Comment by lnicola** [comment]
I started seeing this after upgrading from 1.3.0 to 1.3.2. Firefox on Gnome, Wayland.

**Comment by bwindels** [comment]
Hmm, I indeed [see](https://danburzo.github.io/input-methods/index.html) (Linux, Gnome & Wayland) a keyboard event for just pressing `Control` on Chromium but not Firefox. If they `ctrlKey` flag isn't set on this event, it would explain things, but for me this flag is set. I'm adding some extra checks to not refocus when just pressing a modifier key, regardless of the state of the modifier flags. Let's see if that helps.

**Comment by jryans** [comment]
@bwindels has a possible fix for this that has now landed on develop. Please refresh and see if it helps.

**Comment by lnicola** [comment]
Did this get in `riot-web 1.3.4`? It still seems to happen (and it's pretty annoying TBH).

**Comment by bwindels** [comment]
No, should land in Riot 1.4.0

**Comment by lnicola** [comment]
Seems fixed for me in 1.4.0. @babolivier, can you test?

**Comment by babolivier** [comment]
Yep, can't reproduce anymore :+1:
