### ISSUE TITLE
'Check for updates' seems unresponsive: green update bar is behind dialog

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10393]
When clicking 'Check for updates' in the settings, there is no visible response.  The button does not show being clicked, and there is no visible answer either - only after dismissing the settings pop-up one can clearly see the green bar at the top.  This leads to repeated clicking and frustration.

**Comment by turt2live** [comment]
is this web or desktop? can we get logs with this please?

**Comment by Biep** [comment]
Riot Web/Desktop 1.3.0
![image](https://user-images.githubusercontent.com/12461597/61649437-c8d37180-acb1-11e9-9abc-f77bdc7404cd.png)
The green bar is theoretically visible, but is part of the blacked-out background.
Not sure how to do logs - nor what they would add.

**Comment by turt2live** [comment]
the bug sounded like the green bar wasn't being shown, but this seems to be more that the green bar is not obvious. Logs aren't required, I guess.

**Comment by Biep** [comment]
Yes, sorry - I miswrote that.  The "clearly" would be the only place where I gave the correct information.

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4609 and related PRs
