### ISSUE TITLE
room alias bug 

### ISSUE THREAD

**Issue by amiraelsayed** [vector-im/riot-web#10409]
hello I have a problem in room creation with alias

I have the following scenario 

check if alias found using

`https://domain.com/_matrix/client/r0/directory/room/#james&__&350&__&sameh&__&27&__&:domian.com`

this will return error

`{"errcode":"M_NOT_FOUND","error":"Room alias #james&__&350&__&sameh&__&27&__&:domain.com not found"}`

try to create the room using alias

```
https://domin.com/_matrix/client/r0/createRoom
{"invite":["@sameh:domain.com"],"room_alias_name":"#james&__&350&__&sameh&__&27&__&:domain.com","visibility":"private_chat"}
```

it return error room alias already taken while it was not found in the first request

try to delete this alias using

`https://domain.com/_matrix/client/r0/directory/room/#james&__&350&__&sameh&__&27&__&:domain.com`

it will give error

`{"errcode":"M_NOT_FOUND","error":"Room alias #james&__&350&__&sameh&__&27&__&:domain.com not found"}`

everything was working before 3 weeks as I remember and suddenly the room creation start to make this problem

**Comment by turt2live** [comment]
`room_alias_name` on the createRoom call is the localpart (the bit between the `#` and `:`), not the full alias. See https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-createroom for more details.
