### ISSUE TITLE
Messing in unencrypted room gets stuck at the bottom

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10407]
### Description

![image](https://user-images.githubusercontent.com/1342360/61797749-ed4d5c00-ae1f-11e9-9b04-91bd426904dc.png)

The message "Synapse v1.2.0-rc2 has been release..." has gotten stuck to the bottom. When I send a new message, it goes below this message, but once a /sync request completes, it goes back to the bottom of the message list again.

I then edited the message, but this didn't fix anything.

The event's contents are:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "Synapse v1.2.0-rc2 has been release. Release notes here: https://github.com/matrix-org/synapse/releases/tag/v1.2.0rc2"
  },
  "event_id": "$156397396416sIHvL:amorgan.xyz",
  "user_id": "@andrewm:amorgan.xyz",
  "room_id": "!yZHTGeDKZUeKaqeTeU:matrix.org",
  "origin_server_ts": 1563973964247
}
```

Room ID: !yZHTGeDKZUeKaqeTeU:matrix.org

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v70.0a1
- **OS**: Debian buster
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/10032
