### ISSUE TITLE
user search does not retrieve all users in system  

### ISSUE THREAD

**Issue by amiraelsayed** [vector-im/riot-web#10419]
if I am logged in using
username : james
password : 123456
users that comes from martix server are

Sameh/@sameh:domain.com
Walid/@Walid:domain.com
madonna/@Madonna:domain.com

if I am logged in using
username : john
password : 123456
users that comes from martix server are

Sameh/@sameh:domain.com
Walid/@Walid:domain.com
madonna/@Madonna:domain.com
Habib/@habib:domain.com
elias/@elias:domain.com
nour/@Nour:domain.com
wiliam/@wiliam:domain.com

if I am logged in using
username : nour
password : 123456
users that comes from martix server are

john/@john:domain.com
Sameh/@sameh:domain.com
Walid/@Walid:domain.com
madonna/@Madonna:domain.com
elias/@elias:domain.com
wiliam/@wiliam:domain.com

why that could happen?

**Comment by jryans** [comment]
I would suspect this is a Synapse bug with listing users somehow, but I am also perplexed how this could happen.

**Comment by jryans** [comment]
Is this happening on matrix.org HS, your own homeserver, somewhere else...?

**Comment by t3chguy** [comment]
Synapse only shows you users you share rooms with (or users in world-readable public rooms) by default, its a Synapse configuration option whether this behaviour is enabled or not.

**Comment by amiraelsayed** [comment]
@jryans no it is in my homeserver

**Comment by amiraelsayed** [comment]
@t3chguy  I am using 
getSession(context).eventsApiClient.searchUsers("domain", 100, null, userFoundCallback)
in android matrix sdk

**Comment by t3chguy** [comment]
Then this is the wrong repository for such queries, try https://github.com/matrix-org/matrix-android-sdk

Also read https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md

**Comment by jryans** [comment]
I am going to assume this is the Synapse feature that @t3chguy mentioned. I would suggest asking for support in a room such as #matrix-dev:matrix.org or similar. If you find a bug, it's likely something to report to Synapse or Android SDK repos.

**Comment by amiraelsayed** [comment]
@jryans I tried to use swagger api method also 

https://ensofia.com:8448/_matrix/client/r0/user_directory/search

and it is behave the same as android sdk, so I think the problem is not related to android sdk as it is only call the API methis

**Comment by jryans** [comment]
It sounds like this is either Synapse behaving correctly as @t3chguy mentioned, or perhaps there is a bug in Synapse which you could report to https://github.com/matrix-org/synapse. Either way, it seems unlikely to be a Riot Web issue.
