### ISSUE TITLE
Message edit history not loading

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10412]
In an encrypted room, trying to view edit history on a recently edited message, on lant.uk (which has no aggregations support enabled and is on Synapse 1.0.0, oops), you get this:

<img width="785" alt="Screenshot 2019-07-25 at 10 48 26" src="https://user-images.githubusercontent.com/1922197/61864952-4a9de780-aeca-11e9-9910-c37f7f6ea38b.png">

<img width="1330" alt="Screenshot 2019-07-25 at 10 48 19" src="https://user-images.githubusercontent.com/1922197/61864951-4a9de780-aeca-11e9-80e9-fe618004c3a3.png">

**Comment by bwindels** [comment]
Just checked locally with synapse 1.0.0 with msc1849 turned off and in an encrypted room, couldn't reproduce. The warning is unrelated as well. Could you rageshake please @lampholder ?

**Comment by lampholder** [comment]
Yeah, I can't reproduce this now (though as mentioned IRL my server is now 1.2.1 so I'm not testing under exactly the same conditions).

Happy to close this and we can reopen if anyone sees it again.
