### ISSUE TITLE
Widget permission prompt is too angry, not informative

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10413]
We have a widget permission prompt that looks roughly like:

<img width="977" alt="2019-07-23 at 18 17" src="https://user-images.githubusercontent.com/279572/61732709-1fa27f00-ad76-11e9-9e68-4b0230e5ef84.png">

This is shown for anyone other than the person who added the widget the first time they encounter it for a given room. Once they allow, that is saved for that particular widget.

Some problems (taken from discussion in https://github.com/matrix-org/matrix-react-sdk/pull/3243):

* It's unclear how this should fit in with in-progress IM terms flows (users might be prompted for both widget permission for a specific widget and terms for the IM server generally)
* The current design is somewhat angry with lots of "warning" and "be afraid"
* Other metadata could be useful here, such who added the widget, what type of widget is it, etc.
* It's unclear how to best present the URL without overwhelming users (only the origin part, only what fits on the first line, etc.)

**Comment by turt2live** [comment]
We iterated on this. Now it's too vague: https://github.com/vector-im/riot-web/issues/11471
