### ISSUE TITLE
Crash on Riot when switching rooms

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#10410]
# Description

When I switch rooms on riot-web desktop, the frame displays a white screen.

Bits of log I managed to salvage:
```
rageshake.js:107 Switching to room id !pQhDfsljSUQxaPNpur:matrix.org at event undefined
rageshake.js:107 Looking at $Vnjh4XW83ourSn6gBxR3JnDZXbX3-oDUq2J2oeGbgZs
```

### Steps to reproduce

- Open Riot as usual
- Wait for it to sync
- Switch to a room
- Crash!

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian 10
- **Version**: 1.3.0

**Comment by turt2live** [comment]
It looks like it just died... what did the crash page look like?

**Comment by Half-Shot** [comment]
> It looks like it just died... what did the crash page look like?

On electron it froze for about 15 seconds, and then just white paged.

On Firefox, unresponsive script errors.

**Comment by Half-Shot** [comment]
![riotbad](https://user-images.githubusercontent.com/2072976/62055250-28ca9a80-b213-11e9-8d7a-35b4ca0e5fd6.png)

So I clicked on it again, after trying to leave it without success. Looks like Riot ran out of memory on the step above.

**Comment by turt2live** [comment]
Chrome's OOM detection is pretty terrible tbh. It just tells you when it failed, not that you had a billion gb of stuff in memory before then.

Can you get a memory snapshot when it looks like it's at high memory usage? I imagine this would be some hours after you've started it.

**Comment by Half-Shot** [comment]
This is caused by https://github.com/matrix-org/matrix-js-sdk/pull/1001
