### ISSUE TITLE
Clarify in vector doc that homeservers that require captchas will let untrusted vectors register(?)

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-web#1042]
I'm trying to register an account on matrix.org with a self-hosted vector instance.
However, after having clicked on the confirmation link I received by mail, I have the following error : 
![captcha](https://cloud.githubusercontent.com/assets/8963482/13373588/dbadbc0c-dd6b-11e5-8586-ded13ae2eb1e.png)

I'm also hosting a Synapse instance on the same server, however I didn't enable the captcha.

**Comment by ara4n** [comment]
This is behaving as intended (i think) - the captcha will fail when signing up to matrix.org with a foreign Vector currently as we don't know whether we can trust the foreign Vector's CAPTCHA.  The workaround is either to create the account on matrix.org using the vector.im-hosted vector, or to create it against your own synapse.

**Comment by Annwenn** [comment]
That's what I finally did.
Thanks for explaining this (undocumented?) behaviour. :)

**Comment by ara4n** [comment]
i've turned this into a bug to fix the doc - thanks for bringing it up.

**Comment by aaronraimist** [comment]
Does this still exist?

**Comment by aaronraimist** [comment]
I don't think so.
