### ISSUE TITLE
Logout timeout or Cookies deletion after a period of time

### ISSUE THREAD

**Issue by enannos** [vector-im/riot-web#10421]
Hello all,

is there a way to force the web riot to ask for the credentials after closing the browser window? 
We have seen that when a user closes the browser without logging out, restarts the PC and starts the browser again after days, he can login to riot(running the matrix-synapse server).
Is there a cookie or another way to force the user to give his credentials on browser start?

**Comment by turt2live** [comment]
You can use the new token expiration stuff on the server-side: 
https://github.com/matrix-org/synapse/blob/97bf3077550915161765fdd1cf9290d8039a55f9/docs/sample_config.yaml#L789-L798

Questions like this are best asked in #riot-web:matrix.org rather than through our issue tracker.

**Comment by enannos** [comment]
Hi turt2live,
thanks for your answer. 

I actually do not want to use the expiration setting on the server. Our users are logged in with the mobile app, the electron app and sometimes, using the web client. But I need only to force the users in the web(browser) client to log-in again after a period of time.
There is not a cookie or anything that we could change so that the session expires after a specific period of time?

**Comment by enannos** [comment]
Just for your info in case someone else is interested.
A quick workaround is to change the mx_access_token cookie location storage.
It is by default set to localStorage. If you change it to sessionStorage, when you close the browser, you have to login back again.

Search into bundle.js for mx_access_token
Find localStorage.getItem("mx_access_token") and replace with sessionStorage.getItem("mx_access_token")

**Comment by t3chguy** [comment]
@AnassDriate the code is still there.

![image](https://user-images.githubusercontent.com/2403652/227157326-b3af3311-70b6-4c54-b6e4-561dc8a987ee.png)

**Comment by AnassDriate** [comment]
Big Thanks @t3chguy  
Regards,

**Comment by t3chguy** [comment]
@AnassDriate you are making unsupported modifications, I'm not about to help you with them.

**Comment by AnassDriate** [comment]
@t3chguy 
Thank you for your feedback
