### ISSUE TITLE
Docker image does not contain /app/version file

### ISSUE THREAD

**Issue by NullIsNot0** [vector-im/riot-web#10426]
### Description

Riot Web version 1.3.0
Docker image from https://hub.docker.com/r/vectorim/riot-web does not contain /app/version file which contains Riot Web version which is displayed in UI under `Settings -> Help & About`.

### Steps to reproduce
run these:
`docker run -dit --rm --name riot-web -p 8080:80
![Riot](https://user-images.githubusercontent.com/12268397/61966083-727c7080-afda-11e9-9db6-b3bb76505bfd.png)
 vectorim/riot-web:v1.3.0`
`docker exec -it riot-web sh`
`ls -la /app`

```
/ # ls -la /app
total 644
drwxr-xr-x   11 root     root          4096 Jul 18 15:18 .
drwxr-xr-x    1 root     root          4096 Jul 26 16:14 ..
drwxr-xr-x    3 root     root          4096 Jul 18 15:18 bundles
-rw-r--r--    1 root     root          1358 Jul 18 15:18 config.json
drwxr-xr-x    5 root     root          4096 Jul 18 15:18 fonts
drwxr-xr-x    2 root     root          4096 Jul 18 15:18 i18n
drwxr-xr-x    6 root     root         12288 Jul 18 15:18 img
-rw-r--r--    1 root     root          3788 Jul 18 15:18 index.html
-rw-r--r--    1 root     root          1616 Jul 18 15:10 manifest.json
drwxr-xr-x    2 root     root          4096 Jul 18 15:10 media
drwxr-xr-x    2 root     root          4096 Jul 18 15:18 mobile_guide
-rw-r--r--    1 root     root        170676 Jul 18 15:18 olm.219048b.wasm
-rw-r--r--    1 root     root        411549 Jul 18 15:10 olm_legacy.js
drwxr-xr-x    3 root     root          4096 Jul 18 15:10 themes
drwxr-xr-x    2 root     root          4096 Jul 18 15:18 vector-icons
drwxr-xr-x    3 root     root          4096 Jul 18 15:10 welcome
-rw-r--r--    1 root     root          5505 Jul 18 15:10 welcome.html
```

There's no file named `version`, but it should be there and contain `1.3.0`

### Version information
1.3.0

![Riot](https://user-images.githubusercontent.com/12268397/61966143-9b9d0100-afda-11e9-891e-46601b61e298.png)

However `/app/version` file is present in downloadable zip version under releases. For example `https://github.com/vector-im/riot-web/releases/download/v1.3.0/riot-v1.3.0.tar.gz`

**Comment by aaronraimist** [comment]
@turt2live You said to yell if the image was broken :)

![Screen Shot 2019-11-30 at 11 26 04 AM](https://user-images.githubusercontent.com/5855073/69903808-32e8db00-1364-11ea-85ed-8e50550a4a9c.png)
![Screen Shot 2019-11-30 at 11 26 27 AM](https://user-images.githubusercontent.com/5855073/69903812-4300ba80-1364-11ea-9dec-c3c43b4f4fcc.png)

Keywords: riot web version shows as unknown. Check for update button shows a 404 error.
