### ISSUE TITLE
Use more contextual prompt for integration manager polices on use

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10422]
As of https://github.com/vector-im/riot-web/issues/10088, we will show a generic terms modal flow on use of the IM, but it's a bit removed for whatever action you were trying to perform.

An improved approach would be this more contextual version from the [designs](https://zpl.io/brMdWo3):

![2019-07-26 at 10 42](https://user-images.githubusercontent.com/279572/61942832-14c43600-af92-11e9-83f3-d7a91ec9c748.png)

**Comment by turt2live** [comment]
I think this is superseded by https://github.com/vector-im/riot-web/issues/11262 - please correct me if I'm wrong.
