### ISSUE TITLE
"Failure to create chat room" when it doesn't fail?

### ISSUE THREAD

**Issue by kendosoul** [vector-im/riot-web#10420]
### Description

I had both auto_join_rooms and autocreate_auto_join_rooms on. Everytime a new user (guest user) signs up, a strange  "Failure to create room message pops up"
<img width="876" alt="Screen Shot 2019-07-26 at 12 12 49 AM" src="https://user-images.githubusercontent.com/4179681/61933411-aa33db80-af3a-11e9-9501-8d3523635692.png">
<img width="1019" alt="Screen Shot 2019-07-26 at 12 14 33 AM" src="https://user-images.githubusercontent.com/4179681/61933412-aacc7200-af3a-11e9-80cf-dac584fc32ca.png">

### Steps to reproduce

- https://hub.docker.com/r/matrixdotorg/synapse/
-docker pull the app
- other than renaming the server to neo.zeon (it's not on DNS), I followed it 100% as is
- generate the files
- start the server (so that the docker container gets initiated)
- manually edit the homeserver.yaml to allow autocreate_auto_join_rooms and auto_join_rooms
- docker cp into the proper directory 
- docker restart the container
- sign up from Riot on Mac

Describe how what happens differs from what you expected.
Rooms were created upon the first signup ....

### Version information

- **Platform**: Mac RIot Client 

For the web app:

For the desktop app:

Mac OSX 10.14.4 (18E226)
Riot: Version 1.3.0 (1.3.0)

**Comment by turt2live** [comment]
This is likely your welcome_user_id in your Riot config causing problems. I would recommend asking for help in #riot-web:matrix.org rather than here.
