### ISSUE TITLE
Organising Feature Requests

### ISSUE THREAD

**Issue by Malmik** [vector-im/riot-web#10437]
There are about 3,500 opened issues, most are feature requests. This can be really overwhelming and probably nobody ever read them all and '+1' every one that he liked. Nor the devs can probably remember all the ideas.

Solution I would propose is voting page hosted probably on vector.im website. Let me name it "Impulse" (because in my opinion it fits nicely with Dendrite and Synapse and it's catchy). To use it you must login with your Riot account and fill captcha. After that you will see random feature request with:

- Name of it at the top
- "Report" button somewhere
- Description in the middle
- And vote buttons at the bottom - "+1" and "-1"

After voting, you have aditional option to write why you like/dislike the idea and what could be better. This comment would not go to devs, but to the person who made feature request instead. Next time creator will login to the "Impulse", he will see it with an option to mark it helpfull/unhelpfull/spam and to start chat with the person who made comment. Feature requests will be editable so creator can modify it and take suggestions into account.

Some thoughts:
- Feature requests from Github could be imported to the website with their current count of "+1".
- If a person would like to create a new feature request, he would have to meet certain conditions, for example giving 10 suggestions marked as helpful.

**Comment by turt2live** [comment]
Just as a data point: I regularly read all new issues and often re-read old issues to maintain context on them. I can't say that I know about all issues, but the vast majority I do have memorized for keywords.

It ends up helping a lot to have the feature requests in the same place as everything else to identify gaps in our implementation. We also consistently receive bugs which are actually feature requests, and feature requests which are bugs. Being able to convert those quickly and easily is more desirable than forking features off to a new service, I think.

**Comment by Malmik** [comment]
Oh, I see! Thanks


pon., 29 lip 2019 o 13:30 Travis Ralston <notifications@github.com>
napisał(a):

**Comment by turt2live** [comment]
Making it harder for developers and project management to implement features is less desirable I'd say.

We do already have labels and github's sorting effectively highlights the requested features because it's rare for people to upvote bugs.

There's also the concern of upvoting not being the single driving factor for what we work on next. It is considered, however there's many other factors that go into what we work on (including driving the mission of Matrix and being sponsored to work on something).

**Comment by jryans** [comment]
I agree with @turt2live that I think we actually have something fairly manageable (among the core contributors at least) with GitHub issues, as the line between feature and bug can be quite fuzzy.

I agree it may look unwieldy at first to users that want to comment or upvote, but issue search works fairly well to find previous reports. It's easy to [sort by most upvotes](https://github.com/vector-im/riot-web/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) as well. As @turt2live said, that's only one of many signals we consider when prioritising.
