### ISSUE TITLE
Command-A quickly followed by Backspace doesn't delete text

### ISSUE THREAD

**Issue by dstaley** [vector-im/riot-web#10441]
### Description

After selecting all the text in the input box, If I quickly press Backspace, the text is not removed. If I pause for a brief moment before pressing Backspace, the text is correctly removed.

### Steps to reproduce

- Type text in input box
- Select all with Command-A/Control-A
- Quickly press Backspace

Describe how what happens differs from what you expected.

Text should be removed from the input box.

Logs being sent: Yes

![riot bug](https://user-images.githubusercontent.com/88163/62083407-b1ddd380-b20b-11e9-9858-2dfc2ba06699.gif)

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Chrome 75, Firefox 69, Safari 12
- **OS**: macOS 10.14
- **URL**: riot.im/app (also occurs on riot.im/develop)

**Comment by aaronraimist** [comment]
Does this still happen? The composer has been replaced.

**Comment by t3chguy** [comment]
Nope
