### ISSUE TITLE
Provide sensible defaults for integrations_widgets_urls

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#10454]
In the case that someone running a self-hosted Riot doesn't define `integrations_widgets_urls` at all, Riot [defaults to](https://github.com/matrix-org/matrix-react-sdk/blob/ddcb7a68bdc4dce562c356b97de4ceeaee7c91fe/src/utils/WidgetUtils.js#L103) `integrations_rest_url`.

Since the `integrations_widgets_urls` "normally" (ie in app/develop, desktop) has [defaults as follows](https://github.com/vector-im/riot-web/blob/develop/riot.im/app/config.json), it would make sense to default to those in the case that the widget urls are not set:

```
    "integrations_widgets_urls": [
        "https://scalar-staging.vector.im/api",
        "https://scalar.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
```

This would ensure that widgets created with either live or staging Scalar would work even if the Riot configuration doesn't define them. It should be possible to disable all of them still by setting `integrations_widgets_urls` to an empty list.

This issue comes from a real world case where custom hosted Riot didn't define these urls and failed to thus render a widget created via `scalar-staging.vector.im`.

**Comment by turt2live** [comment]
fwiw if I get my way with the integrations API proposals then this field becomes obsolete.

**Comment by turt2live** [comment]
(also insert a comment here with my community hat about dissatisfaction for continuing to default to scalar when there are other integration managers in the world)
