### ISSUE TITLE
Possible EventEmitter memory leak detected. 11 RoomMember.membership listeners added.

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10456]
This is due to recent changes from https://github.com/matrix-org/matrix-react-sdk/pull/3255.

It's not a leak in this case, but we are adding lots of listeners since every message now listens to the room for permissions changes, even though the user's permission state should be the same throughout the room.

I would suggest computing this permission info higher up so it happens once per room and passed down as props. This should help us leverage React's update cycle more naturally as well (it should update all components in one go, rather than each message updating separately due to having its own listeners).

**Comment by jryans** [comment]
```
MaxListenersExceededWarning: "Possible EventEmitter memory leak detected. 11 RoomMember.membership listeners added. Use emitter.setMaxListeners() to increase limit"
    _addListener events.js:208
    addListener bundle.js:349203
    componentDidMount MessageActionBar.js:56
    React 14
    enqueueUpdate bundle.js:378946
    enqueueSetState bundle.js:379140
    setState React
    onMessageListFillRequest TimelinePanel.js:388
    _execute bluebird.js:987
    _resolveFromExecutor bluebird.js:3275
    Promise bluebird.js:2866
    onMessageListFillRequest TimelinePanel.js:389
    tryCatcher bluebird.js:5290
    _settlePromiseFromHandler bluebird.js:3302
    _settlePromise bluebird.js:3359
    _settlePromise0 bluebird.js:3404
    _settlePromises bluebird.js:3484
    _drainQueueStep bluebird.js:190
    _drainQueue bluebird.js:183
    _drainQueues bluebird.js:199
    drainQueues bluebird.js:69
```

**Comment by jryans** [comment]
@t3chguy Are you interested in working on this?

**Comment by t3chguy** [comment]
Yup, will sort this tonight

wt., 30 lip 2019, 17:51 użytkownik J. Ryan Stinnett <
notifications@github.com> napisał:

**Comment by t3chguy** [comment]
This is super annoying to wire up, needs to be passed: `RoomView > TimelinePanel > MessagePanel > EventTile > MessageActionBar`

**Comment by t3chguy** [comment]
I'm thinking a RoomContext which has all the useful calculated bits from RoomView would be super-useful

**Comment by turt2live** [comment]
A RoomContext sounds like the perfect answer for this, I think

**Comment by t3chguy** [comment]
How stable are Contexts in React 15.6 though? I've only been using 16.8 recently

**Comment by turt2live** [comment]
We've had a matrix client context for the history of the project powering a good third of the app, so I'd hope stable enough. We also want to upgrade to React 16 any day now.

**Comment by t3chguy** [comment]
> We also want to upgrade to React 16 any day now.

<3

is that 16 or 16.8 (hooks)?

**Comment by turt2live** [comment]
it'll probably be "whatever is latest" at the time of upgrade, depending on who does it. Ideally we'd keep up with react releases...

**Comment by t3chguy** [comment]
very exciting
