### ISSUE TITLE
Reactions tooltip can behave strangely after adding the first reaction on a message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10466]
Possibly platform specific. Reported to be on Riot Desktop.

![image](https://user-images.githubusercontent.com/1190097/62185911-76cdc400-b321-11e9-83db-7d705dd14049.png)

In the above, the tooltip appears to move upwards but the focusable area (red box) sticks to the button. This makes it difficult to reach the other reactions.

**Comment by turt2live** [comment]
From the user, a video of the problem: https://t2bot.io/_matrix/media/r0/download/matrix.org/VwjNKZLpIzEveJgxLAzKUrNF

The tooltip randomly disappearing before a reaction can be sent feels a bit like matrix.org being slow at sending the reaction, so when it does send the timeline remounts and causes problems for the tooltip. The rest looks like jump scrolling to me.

**Comment by t3chguy** [comment]
No longer a thing
