### ISSUE TITLE
preload the /!\ warning icon

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10467]
once upon a time i preloaded the warning icon on the main index.html for Riot so that if the statusbar error shows due to losing network, the icon renders correctly rather than falling back to the ascii /!\ alt attribute. it looks like that fix got removed/broken at some point :(

**Comment by jryans** [comment]
https://github.com/vector-im/riot-web/pull/10197 was meant to fix exactly this... I wonder what's changed since then.

**Comment by t3chguy** [comment]
It seems to get pre-loaded:

![image](https://user-images.githubusercontent.com/2403652/62828974-0198a380-bbeb-11e9-98e6-e704c7a2b4ae.png)

**Comment by jryans** [comment]
Maybe @ara4n should try disabling network to re-check the current behaviour...?

**Comment by turt2live** [comment]
I'm also unable to reproduce this - if it's still an issue, please open a new one.
