### ISSUE TITLE
I constantly run off the edge of the reactions tooltip on the dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10469]
My mouse takes a weird S-turn and usually runs off the left or top edges, even after the improved hit area

**Comment by jryans** [comment]
Hmm, curious... Can you included a video? I recently added a 50px buffer around the top and sides of tooltip, so curious if you are going even beyond that.

**Comment by turt2live** [comment]
I can't include a video that's of reasonable size at the moment. The problem is more that I can't see the edges of the tooltip, so I seem to spend some time flying around looking for the buttons I want.

I'm also willing to accept that this might be a Me problem and not a Riot problem.

**Comment by jryans** [comment]
> can't see the edges of the tooltip

Ah, I guess you're on dark mode then?

**Comment by turt2live** [comment]
Yes, see title :p

**Comment by jryans** [comment]
Marking needs design... We may want the something with more contrast on dark theme.

**Comment by t3chguy** [comment]
outdated
