### ISSUE TITLE
Remove gemini scrollbars

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10474]
and replace with native, like the room list I believe.

Potentially related issues:
* https://github.com/vector-im/riot-web/issues/8492
* https://github.com/vector-im/riot-web/issues/6926
* https://github.com/vector-im/riot-web/issues/6694
* https://github.com/vector-im/riot-web/issues/5854
* https://github.com/vector-im/riot-web/issues/2875

Probably needs a designer checkmark before implementation. p2 because it's not identified on any of our immediate roadmaps.

**Comment by turt2live** [comment]
I'm bumping this to p1 otherwise it'll never happen, and it's just constantly in the way.

**Comment by aaronraimist** [comment]
Most of those potentially related issues are still open. Presumably they have now been fixed.
