### ISSUE TITLE
Make it possible to add any arbitrary IRC network

### ISSUE THREAD

**Issue by MaliusArth** [vector-im/riot-web#10484]
There are 4 hardcoded irc networks available and I would like to be able to add a currently unsupported network. IRC chat clients usually let users choose any network they like, is it a technical limitation that they have to be hardcoded the way they are now?

**Comment by t3chguy** [comment]
Riot is not an irc client. There are more than four irc networks accessible it's just that riot only knows about those irc bridges. An irc bridge cannot connect to arbitrary networks partially because it requires special provisions to allow many connections from a single place.

**Comment by t3chguy** [comment]
Refer to https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks for some other public irc bridges.

**Comment by jryans** [comment]
> IRC chat clients usually let users choose any network they like, is it a technical limitation that they have to be hardcoded the way they are now?

Coming back to this question, in the Matrix ecosystem, bridges like IRC are run on the homeserver (such as the one run by matrix.org or anyone else who wants to run their own), so clients likely Riot are not able to freely choose any IRC network: they are limited to whatever bridges are supported on homeservers.
