### ISSUE TITLE
Implement Outbound SAS verification in right panel, styled with new design (excluded QR code business for now)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10492]
We only have designs which include **QR codes** and **security notification events in the timeline** for now - **neither of these should be implemented as part of this task*.

QR codes should come in `phase:2`, security notif events are probably going to end up in DMs (depending on the outcome of https://github.com/vector-im/riot-web/issues/10493)

Zeplin: https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5d27a2b8caa4a66b12c6ef97

Screenshots (pulled from Zeplin):
![image](https://user-images.githubusercontent.com/1922197/62365676-8e24d100-b51c-11e9-8ec8-bce0cb6cf86f.png)
![image](https://user-images.githubusercontent.com/1922197/62365684-967d0c00-b51c-11e9-966e-5ea617c0df7a.png)

**Comment by jryans** [comment]
This work has happened in other cross-signing issues.
