### ISSUE TITLE
Implement new user profile design

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10490]
Zeplin: https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5d27a2b8caa4a66b12c6ef97

Screenshots (pulled from Zeplin):
![image](https://user-images.githubusercontent.com/1922197/62365132-346fd700-b51b-11e9-923d-821b4923bb6c.png)

![image](https://user-images.githubusercontent.com/1922197/62365175-4b162e00-b51b-11e9-809b-c0f1211333e1.png)

**Comment by schiessle** [comment]
looks really nice... Not sure if this is the right place, but I think it would be really useful if people could have a more extended profile. Writing a few sentences about themselves, show a URL to their webpage, maybe decide to publish some of their email addresses, phone numbers, etc. This would make it easier to identify the right people would make the profile more useful

**Comment by t3chguy** [comment]
@schiessle see https://github.com/vector-im/riot-web/issues/7704 and https://github.com/vector-im/riot-web/issues/1401

**Comment by jryans** [comment]
This work has happened in other cross-signing issues.
