### ISSUE TITLE
Terms test scalar requires the legacy ?v query param on the new account route

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10498]
`/_matrix/integrations/v1/account` with no auth/additional args says "Invalid or missing version 'v' query parameter". This argument is specifically not included in this `/_matrix/*` IM endpoints spec.

**Comment by jryans** [comment]
@turt2live Is there anything Riot needs to change here after the Scalar fix?

**Comment by turt2live** [comment]
We should probably clean up the code a bit.
