### ISSUE TITLE
Image upload is broken in Google Chrome 76

### ISSUE THREAD

**Issue by bartmoc** [vector-im/riot-web#10494]
### Image upload is broken in Google Chrome 76

After upgrading to Google Chrome 76 (from 75) I'm unable to upload images.

### Steps to reproduce

- Download sample image https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg
- Select a person on a room in riot, drag & drog image to upload 
 

Describe how what happens differs from what you expected.
Getting error message 
![image](https://user-images.githubusercontent.com/16946872/62369912-655b0680-b531-11e9-9138-6e8f1c373ee6.png)
![image](https://user-images.githubusercontent.com/16946872/62369939-7b68c700-b531-11e9-91a7-c460e4ad2b09.png)
![image](https://user-images.githubusercontent.com/16946872/62369969-95a2a500-b531-11e9-8fc7-e6ff9de0c6f1.png)

### Version information
matrix-react-sdk version: 0.12.3
riot-web version: unknown
olm version: 2.2.1

- **Platform**: Linux 4.18.16-041816-generic #201810200431 SMP Sat Oct 20 08:33:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

For the web app:
Google Chrome  76.0.3809.87 (Official Build) (64-bit)

**Comment by turt2live** [comment]
This looks like a problem with your homeserver, not Riot. What do the server's logs say?

**Comment by bartmoc** [comment]
We are running `v0.28.1`.

**Comment by turt2live** [comment]
You should upgrade your homeserver immediately to pull in several security fixes. Synapse is now at v1.2.1

**Comment by bartmoc** [comment]
Thx, upgrade solved this issue, thank you for support, it's was blazing fast!
