### ISSUE TITLE
Memberinfo panel reveal resize on hover

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10491]
Zeplin: https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5d27a2b8caa4a66b12c6ef97

Screenshots (pulled from Zeplin):
![image](https://user-images.githubusercontent.com/1922197/62365506-2b333a00-b51c-11e9-8596-3aa64e23ffd5.png)

**Comment by jryans** [comment]
This work has happened in other cross-signing issues.
