### ISSUE TITLE
Evaluate secure enclave approaches for private key storage

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#10495]

**Comment by jryans** [comment]
I believe @uhoreg is focusing this issue on evaluating secure enclave libraries and storage approaches.

**Comment by uhoreg** [comment]
I was, but am not working on it any more.  The tl;dr at the moment is https://www.npmjs.com/package/keytar is a nice library that provides support for integrating with the OS's password storage on macOS, Linux, and Windows.  The macOS support seems to be the reasonably secure.  IIRC the Windows support doesn't always prompt the user when an application asks for the password, so a rogue application could steal private data.  The Linux support uses the Freedesktop.org Secret Service, which is supported in GNOME by GNOME keyring, but doesn't seem to have support in KDE that's actively developed.  I didn't determine whether the GNOME keyring always prompts the user for permission to access the data.

keytar requires native modules, so its use would be blocked on adding native modules to our build.

**Comment by jryans** [comment]
This round of evaluation happened, so no need to keep this open.
