### ISSUE TITLE
Settings option available on invites

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10507]
![image](https://user-images.githubusercontent.com/1190097/62504175-82ebd280-b7b4-11e9-8cee-ed48c3fdc884.png)

**Comment by t3chguy** [comment]
I mean is that technically wrong? What if you wanted to open devtools or see the id of the room you are being invited to? The button *works*

**Comment by t3chguy** [comment]
also it successfully shows you that the room is encrypted before you accept the invite

**Comment by turt2live** [comment]
The settings don't work, so it shouldn't be there. You can get the room ID from the address bar.

The values it does show are based on the unsigned events the server happened to send with the invite.

**Comment by t3chguy** [comment]
fair enough, will PR the hiding of the button and leave it to higher powers to decide if thats the exact desired behaviour, seems sane enough

**Comment by turt2live** [comment]
I think @nadonomy is the highest ranking person for these kinds of decisions at the moment (everyone else is on holiday). Although tbh I'm tempted to make the executive decision to just remove it.

@nadonomy do you have any thoughts on this? (ie: should we show the button or not?)

**Comment by nadonomy** [comment]
If Settings doesn't work, then it seems like a no brainer to hide the Settings button.

Even if Settings was gracefully handling it, it seems like a better use of resources for us to not have to maintain/support users accessing it in this state.
