### ISSUE TITLE
IS interactions proxied through the HS also need terms agreement

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10525]
There are several places where we send data to the IS via the HS, such as:

* Adding 3PIDs at registration
* Adding 3PIDs in settings

These currently don't trigger terms on use in Riot because they don't happen directly with the IS and the HS is not aware of terms yet... In any case, we need to get user agreement for these flows as well.

**Comment by jryans** [comment]
See also https://github.com/matrix-org/synapse/issues/5786

**Comment by turt2live** [comment]
Do they? Wouldn't the homeserver ToS take care of this?

**Comment by jryans** [comment]
Hmm, it seems at the very least unclear and confusing... I don't think we want to force HS admins to participate in a formal data processing arrangement with the ISes, so it would seem we'd need to get user consent for any operation that can flow to the IS.

**Comment by lampholder** [comment]
Very quickly thinking about this:

It's right that (at the present time) we don't want the HS admin to have a formal DPA with the IS provider. The relationship should be:
- between the user and the homeserver
- between the user and the identity server

When the user makes a request to the identity server that is proxied via the homeserver (there are a few of these) then:
- the data being shared with the homeserver should be covered by the homeserver's relationship with the user
- the homeserver should have its own token for interacting with the identity server on the user's behalf
- the homeserver should use this token to check that the user has read and agreed to the terms of service _before it sends any personal data_ (in the same way that the client does)
- if the homeserver discovers that the user has not agreed to the terms of serivce, it should reject the request

**Comment by jryans** [comment]
After [another look at the MSC](https://github.com/matrix-org/matrix-doc/pull/2140/files#diff-c03a26de5ac40fb532de19cb7fc2aaf7R94), the client is meant to send the `is_token` to the HS for requests that the HS proxies to the IS, so this implies the client will contact the IS directly to work out a valid token first, and then pass that to the HS.

I have edited @lampholder's bullets above to match.

**Comment by jryans** [comment]
It seems clear how to proceed, so I have removed the blocked label.

**Comment by jryans** [comment]
Based on discussion in the [Synapse issue](https://github.com/matrix-org/synapse/issues/5786#issuecomment-522932028), it looks like the APIs to consider here are:

* `/account/3pid/email/requestToken`
* `/account/3pid/msisdn/requestToken`
* `/rooms/{roomId}/invite` for 3PID invites
