### ISSUE TITLE
don't try & show threepids in discovery section if we don't have an ID server

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#10528]

**Comment by jryans** [comment]
@nadonomy, when the user has no identity server, should the Discovery section disappear entirely, or should it be present but with some kind of "⚠️ You need to select an Identity Server before you can share your email addresses and phone numbers."?

(This is similar but not the same as https://github.com/vector-im/riot-web/issues/10522.)

**Comment by nadonomy** [comment]
> @nadonomy, when the user has no identity server, should the Discovery section disappear entirely, or should it be present but with some kind of "⚠️ You need to select an Identity Server before you can share your email addresses and phone numbers."?
> 
> (This is similar but not the same as #10522.)

Is there any reason to not expose the same state as comped here? https://github.com/vector-im/riot-web/issues/10522#issuecomment-521030251

I'm working from the assumption that the client should always have a default identity server specified, if it doesn't, then we could tweak the copy accordingly. As per the other comment, feedback is welcome/I'd be very glad to rubber duck through the copy and minutiae on this.

**Comment by jryans** [comment]
Hmm, I guess it's not entirely clear to me how the Discovery section should behave when the user currently has no Identity Server...

Over in a [related privacy issue](https://github.com/vector-im/riot-web/issues/10094#issuecomment-520404102), @lampholder said:

> We should no longer have an IS 'supplied at login time' - rather there is a 'default' that is 'the Identity Server the client would prompt to use if asked to do something identity servery and the user has not made an active choice to use either a different identity server or no identity servrer at all'.

...but it's not immediately clear to me how to interpret that for the Discovery section. @lampholder, does it mean the Discovery section is always has _some_ IS set: either the one you are actively using, or else the default IS?

**Comment by lampholder** [comment]
With IS disabled, my Discovery section looks like:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/1922197/63021916-932d3d00-be99-11e9-947f-99962762857b.png">

Would it not just be appropriate to hide the *Email addresses* and *Phone numbers* sections if no IS is connected?

I think the text under *Identity Server* is good, but it is a little confusing that the Identity Server text box appears to have defaulted to something - might it be clearer if this was either proper placeholder text (such as `e.g. vector.im`) or nothing at all?

**Comment by jryans** [comment]
> Would it not just be appropriate to hide the _Email addresses_ and _Phone numbers_ sections if no IS is connected?

Yes, I think that could work.

> I think the text under _Identity Server_ is good, but it is a little confusing that the Identity Server text box appears to have defaulted to something - might it be clearer if this was either proper placeholder text (such as `e.g. vector.im`) or nothing at all?

Yes, I agree the current state of that text box is confusing, and maybe proper placeholder text is a good route to go so people have some clue of what would work there.
