### ISSUE TITLE
"Cannot Connect To Server" every day

### ISSUE THREAD

**Issue by rphmeier** [vector-im/riot-web#10521]
### Description

A few days ago, my Riot started to say it was unable to connect to server. Importantly, it also has failed to work on my phone at all since that entire time. At first I tried changing wi-fi networks, VPN, etc.

Weirdly enough, I could actually send messages and images. I didn't see that they were going through on my side, but on others' clients they actually went through.

The only thing that worked is to completely delete the Riot data-dir (`rm -rf /Users/robert/Library/Application\ Support/Riot/`). Simply clearing the cache did not work.

This has the downside that I lose all encryption keys and history. (side note: the import E2E keys does not work for me at all.)

For the past few days, the same thing has happened again. I'm just flushing my keys each time. It's making Riot relatively useless as an asynchronous chat application, as I can only really communicate with those who are online at the same time as me. Messages sent while I'm offline will just be lost in the Ether.

### Steps to reproduce

I don't know how to reproduce the initial conditions or necessarily how I got into this situation. I've used Riot almost every day for work-related chat for the past 2 years without ever running into this. 

To reproduce now that I'm stuck in this loop, it seems all I have to do is wait for a few hours and I will be in the same position.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop app: Version 1.3.2 (1.3.2)
- **OS**: macOS
- **Version**: High Sierra 10.13.5

**Comment by rphmeier** [comment]
(i've since uninstalled riot on my phone, but it hasn't helped)

Any suggestion on what to do?

**Comment by turt2live** [comment]
Unfortunately it looks like your logs that you've submitted don't reveal the problem. The symptoms you're describing sound like an overwhelmed homeserver though - try and contact the admins of the server and they might be able to look into it.

[#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) is a good place to troublshoot synapse issues.

**Comment by rphmeier** [comment]
Frankly a disappointing response - there are ~100 users on the same server and no others are experiencing the same.

**Comment by jryans** [comment]
The main reason for issue closure is that we have found that GitHub issues are not a good medium for support questions that affect specific installations. The appropriate Matrix room for Riot or Synapse questions depending on the problem is a better place for support as it is interactive and more people are present to help.
