### ISSUE TITLE
Handle terms agreement in the Discovery section of settings

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10522]
It's possible that the Discovery section of settings is the first place the user interacts with their identity server, and therefore we need to show some kind of state when terms haven't been agreed yet, allow for agreeing the terms, etc.

Maybe something like "⚠️ You need to agree to Identity Server terms before you can share your email addresses and phone numbers. <Review terms>" inline in the Discovery section?

**Comment by nadonomy** [comment]
@jryans yep this sounds totally reasonable!

Looking at the design, I think the best thing to do would be to hide all of the Discovery section content and display this warning in place, as I think it'll just provide more noise than value if we expose it in a disabled/low alpha state.

Does that sound good to you? If so let me know and I can update Sketch/Zeplin with the warning.

**Comment by jryans** [comment]
Yes, I think that sounds reasonable for the issue described here. I recently also raised https://github.com/vector-im/riot-web/issues/10525, which makes me concerned that other steps (like adding a 3PID to your account in General settings) may also face this issue.

In any case @nadonomy, we can probably apply the same UX to any other areas facing this as well, so updating designs as you described sounds good to me.

**Comment by nadonomy** [comment]
Ok, in that case I'll add a comp for how we can visualise this generically in any section in Settings.

**Comment by jryans** [comment]
Marking blocked for now until we have designs.

**Comment by nadonomy** [comment]
@jryans I've updated Zeplin here: https://zpl.io/brMdWo3

<img width="969" alt="Screenshot 2019-08-13 at 15 15 28" src="https://user-images.githubusercontent.com/4626865/62981110-44ba6880-bddd-11e9-95cf-fb4b79927946.png">

I'm a little removed from the privacy project while I'm working on other things, so would appreciate any input/to rubber duck any logical dependencies or if you think we should/shouldn't expose changing an identity server in this state, etc.

But, hopefully this is enough to unblock the visual design at least, even if we need to chew the fat on some of the minutiae of what we do/don't expose.

**Comment by jryans** [comment]
Thanks, I think that's seems like it should work to me. 😁
