### ISSUE TITLE
Font issue for some emojis on Mac OS

### ISSUE THREAD

**Issue by ledangtrung** [vector-im/riot-web#10536]
### Description

![Screen Shot 2019-08-12 at 1 28 48 PM](https://user-images.githubusercontent.com/24932062/62848335-5fb9a980-bd05-11e9-8038-2c70413a63bf.png)

### Steps to reproduce

- type : to bring up emoji. This also happens to reply
### Version information

- **Platform**: web (in-browser) or desktop?
Web, verion: riot-web version: 906045b2159e-react-75bcd61934f1-js-17724fc8d35f
olm version: 3.1.0

For the web app:

- **Browser**: Safari Version 12.1.2 (14607.3.9)
- **OS**: Mac OS, 10.14.6 (18G84)
- **URL**: https://riot.im/develop/

**Comment by jryans** [comment]
Thanks for the feedback. I believe this is the same issue as https://github.com/vector-im/riot-web/issues/9895.
