### ISSUE TITLE
unable paste(ctrl+v in message box) image in chrome browser but working in firefox.

### ISSUE THREAD

**Issue by akhilin** [vector-im/riot-web#10537]
# chrome response:
{"errcode":"M_UNKNOWN","error":"Internal server error"}

# screenshot:
![image](https://user-images.githubusercontent.com/21128035/62854045-ce9a0100-bd0b-11e9-9bba-a838e3b33a48.png)

**Comment by jryans** [comment]
What version of Chrome are you using? What desktop OS? What version of Riot? (These questions should have all appeared in the issue template...)

**Comment by akhilin** [comment]
OS: Linux mint and Windows 10
Riot web version: 1.2.1

Google Chrome | 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux
JavaScript | V8 7.6.303.29
Flash | 32.0.0.223 /home/akhil/.config/google-chrome/PepperFlash/32.0.0.223/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by sundh4** [comment]
Hello,
This also affecting me. Its not only uploading image but including upload any file. Appreciate if you guys can solved this.

Thanks

**Comment by jryans** [comment]
Hmm, file upload appears to work here in Chrome 78.0.3896.0 on macOS 10.14.6.

What homeserver are you using? What version of Synapse? What Riot are you using?

**Comment by akhilin** [comment]
riot-web 1.2.1
matrix synapse 1.0.0

**Comment by jryans** [comment]
A [fix](https://github.com/matrix-org/matrix-js-sdk/pull/952) for a [similar sounding issue](https://github.com/vector-im/riot-web/issues/9913) was first released in Riot 1.2.2 on 2019-06-19.

Please update your Riot and re-test. I am fairly confident that will resolve the issue, so closing for now. Please report back either way and reopen if not fixed.

**Comment by akhilin** [comment]
> A [fix](https://github.com/matrix-org/matrix-js-sdk/pull/952) for a [similar sounding issue](https://github.com/vector-im/riot-web/issues/9913) was first released in Riot 1.2.2 on 2019-06-19.
> 
> Please update your Riot and re-test. I am fairly confident that will resolve the issue, so closing for now. Please report back either way and reopen if not fixed.

Yes. It worked after upgrade.

Thank you.
