### ISSUE TITLE
Text field description remains visible behind typed text (login screen, Edge browser)

### ISSUE THREAD

**Issue by anton-molyboha** [vector-im/riot-web#10531]
### Description

When using login screen in Edge browser (Windows 10), typing the username does not make the work "Username" disappear in the textbox. Instead, your username is overlayed on top of the "Username" hint in the textbox.

![login_screen](https://user-images.githubusercontent.com/7339795/62824943-dbc2be80-bb58-11e9-9ef2-a2082075f73a.png)

### Steps to reproduce

- Log out
- Visit https://riot.im/app/
- Type some text into "Username" field

Describe how what happens differs from what you expected.

The hint "Username" should be invisible as long as something is typed into the text field.

Log: sent/not sent?  Not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Microsoft Edge 44.17763.1.0 ; Microsoft EdgeHTML 18.17763
- **OS**: Windows 10
- **URL**: riot.im/app

For the desktop app: N/A

**Comment by turt2live** [comment]
Edge is not a supported browser - does the same happen in the latest version of Chrome or Firefox?

**Comment by anton-molyboha** [comment]
Ah, that explains it. Sorry for the confusion.

I have tried with Firefox, and everything works correctly.
