### ISSUE TITLE
Share Screen not work

### ISSUE THREAD

**Issue by liberodark** [vector-im/riot-web#10538]
Hi,

On riot-desktop the feature share screen not work.

Test 1
Riot : 1.3.0
Desktop : XFCE
OS : Manjaro x64

Test 2
Riot : 1.3.2
Desktop : KDE
OS : Arch Linux x64

Test 3
Riot : 1.3.0
Desktop : Gnome
OS : CentOS 7 x64

![pas d'bol](https://user-images.githubusercontent.com/4238928/62866031-36eae180-bd10-11e9-9eac-22bcb0618c43.png)

Best Regards

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4880
