### ISSUE TITLE
Riot Desktop : downloading pictures open tab in browser

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riot-web#10542]
### Description

In Riot desktop (ubuntu), before when I was clicking on "download 11111.jpg", it was downloading the image directly to my "download" folder.
Unfortunately, now, it opens a tab in firefox instead... So I have then to save it...
Is it possible to get the previous behaviour?

### Steps to reproduce

-In Riot desktop 1.3.2 in ubuntu 18.04
- Click "download xxxxxx.jpg" below an image inside a room.
- It opens a tab in the browser

It should save it in a download folder chosen in the settings.

Logs being sent: yes

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**:  Ubuntu 18.04
- **Version**: 1.3.2

**Comment by jryans** [comment]
Hmm, as far as I can tell, this area of code hasn't changed very much lately... Can you perhaps remember when it used to download directly in the desktop app?

**Comment by turt2live** [comment]
(it changed sometime around 1.0 when we not only changed the CSP, but also the behaviour of the download button. I believe this is a regression)

**Comment by Thatoo** [comment]
No, sorry, I really can't recall as I don't download pictures very often.
It could be around 1.0 but not much earlier I believe.

**Comment by Thatoo** [comment]
I have found a surprising element.
It actually behave "wrongly" in non encrypted room.
However, in encrypted room, I click first on "unencrypt the image" then on "download image", in that case, it does download the image directly to the folder (it actually asks me where I want to download, which is fine ).
In non encrypted room (chat), when I click on download the image, it opens an https link into my browser...
That explain why I didn't noticed this bug before because I mostly use encrypted room.

**Comment by horstvogel** [comment]
The same Problem with Windows Desktop App Electron 1.32. Windows 10 and Windows RDS Server 2016
In encrypted room the download is working, in non encrypted room the Picture is open in the browser

**Comment by t3chguy** [comment]
Closing in favour of more generic https://github.com/vector-im/riot-web/issues/12405
