### ISSUE TITLE
Working weirdly when typing zh-CN language.

### ISSUE THREAD

**Issue by momoblydblk** [vector-im/riot-web#10547]
### Description

When typing Chinese in the chat box, with the original Windows 10 Chinese input, sometimes a letter or two will disappear, and all the newly typed letters are appearing to the right of the cursor, which should be at left.

### Steps to reproduce

- Switch to the original Chinese input method. (For clarity, zh-CN specifically with Pinyin input)
- Start typing rapidly.
- It will start to act weirdly.

Expected:
- Typing rapidly without problem ( even in Chinese)

Appeared:
- Letters gone missing after pressed the 2nd key OR it appeared without a chosen box which let you choose which Chinese character you want to use.
- Letters appear to the right of the cursor.

Log: sent    

### Version information

- **Platform**: Desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows
- **Version**: Windows 10 Home Chinese, Ver. 1803, OS Ver. 17134

**Comment by turt2live** [comment]
This is a known problem: https://github.com/vector-im/riot-web/issues/7665
