### ISSUE TITLE
Prompt for fallback VOIP should only happen when the user tries to make a call

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10546]
As currently proposed/defined, the prompt for using a fallback server is done at startup. This is subpar imo for a number of reasons:

1. There's a number of homeservers out there (including mine) which have not bothered to set up VoIP because there's no need for it. For instance, I don't make calls through Matrix and therefore haven't bothered to set it up. Getting a prompt is just going to be annoying for me.
2. Some homeservers (including some I run) intentionally have not set up a TURN server largely because of point 1. The users on the homeserver are largely not technologically inclined and do not make calls in the first place - this prompt will be confusing and annoying to them, regardless of the copy used.
3. It is yet another thing added the onboarding experience. The mobile apps are the worst offenders for this (https://github.com/vector-im/riot-meta/issues/214) and would now have 3 prompts at startup. New users trying to register for the app already feel drained by the time they actually get to send a message - another prompt that won't affect them is likely to be the nail in the coffin.

**Comment by jryans** [comment]
We'll be changing this to happen in context, so I'll assign this and revise the PRs.
