### ISSUE TITLE
Remove the ability to set an IS at login/registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10553]

**Comment by jryans** [comment]
There is a backwards compatibility issue here, as older HSes will still need an IS supplied for registration with email and password reset, but new HSes will not.

See also migration work generally in https://github.com/vector-im/riot-web/issues/10593.

**Comment by jryans** [comment]
`/versions` from the HS describes whether an IS is already known to the HS. If an IS is known to the HS, the IS field can be hidden / removed (UX to be determined).

**Comment by jryans** [comment]
@lampholder, do we need more product thinking around how we want the IS field to removed, or is the goal clear and we need designs?

**Comment by lampholder** [comment]
I'm thinking:

- user chooses to register or reset password
- user chooses to enter custom server details
- user is prompted to enter custom homeserver url
- we check with that homeserver's `/versions` to see if an IS is needed for registration/password reset
- if an identity server _is_ needed, the form expands to solicit an identity server from the user, too
    - this transition should be animated

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1922197/63521707-dec19580-c4ee-11e9-8292-2602c4eddda9.png">

**Comment by jryans** [comment]
Thanks @lampholder! It seems clear how to proceed now.

I also verified that we don't need the IS at login time, so we can always hide it during that flow.
