### ISSUE TITLE
Allow email registration, password reset & adding 3pids when no IS

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#10552]
When the HS doesn't require an IS to send any of these validation tokens, riot should allow you to do all of these things when you have no IS configured.

This requires some spec to allow the client to know that it doesn't need to supply the id_server param to the various `requestToken` endpoints.

**Comment by anoadragon453** [comment]
> This requires some spec to allow the client to know that it doesn't need to supply the id_server param to the various requestToken endpoints.

Capabilities or somewhere else?

**Comment by dbkr** [comment]
Yes. Capabilities currently requires auth though, so that's out for registration.

**Comment by anoadragon453** [comment]
Maybe a `GET /_matrix/client/r0/3pid/identity_server` with a 

```
{
    "identity_server": "example.com"
}
```

or

```
{
    "identity_server": null
}
```

response?

**Comment by dbkr** [comment]
Travis was suggesting a param in the UI auth flow, so that's an option.

**Comment by anoadragon453** [comment]
Ah, yeah that would be cleaner.

**Comment by dbkr** [comment]
Closing in favour of split out bugs above
