### ISSUE TITLE
Add better domain for turn.matrix.org use as STUN server

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10563]
As of https://github.com/vector-im/riot-web/issues/10173, we will be offering a public STUN server hosted at `turn.matrix.org`. For those who know how STUN and TURN work, it feels a bit deceptive to say "STUN server at domain name including the word `turn`", as it is surprising and confusing to read.

We should consider: 

* Adding an additional, more generic domain name to the STUN / TURN server, such as `voip.matrix.org` or `call-assist.matrix.org` etc.
* Updating the clients to use this domain for connections and in text to explain the situation

**Comment by ara4n** [comment]
TURN is a superset of STUN though; it's perfectly reasonable to say "use the stun server at turn.foo.com".  I don't think we should obfuscate things here tbh.
