### ISSUE TITLE
Scalar should serve a .well-known file

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10561]
This is for integration manager discovery. See https://github.com/matrix-org/matrix-doc/pull/1957/files#diff-276ec43dc975b6b6ac1d919fab8b9fc8R109-R131 for details (as of writing).

Domains which should support this:
* scalar.vector.im
* scalar-staging.vector.im

**Comment by turt2live** [comment]
p1 for rollout of integration manager changes. I assume users are most likely to punch in "scalar.vector.im" as their integration manager, which should just return the config for itself.

**Comment by jaywink** [comment]
This is now done.
