### ISSUE TITLE
Flux RSS not work great with -

### ISSUE THREAD

**Issue by liberodark** [vector-im/riot-web#10576]
Hi,

Use RSS on my room but is not work great with - : 
The bug is on web and desktop version.

RSS Link on Riot : 
https://www.domain.ch/link/jeu&#45;vidéo/linux/489499&#45;test+1+4+nano

The correct link
https://www.domain.ch/link/jeu-vidéo/linux/489499-test+1+4+nano

**Comment by liberodark** [comment]
https://github.com/matrix-org/go-neb/issues/299

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/go-neb/issues/299
