### ISSUE TITLE
Cannot verify mobile device

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10583]
In an encrypted 4-persoon room, I want to verify the two devices (desktop and mobile) of one person, the old way.  I succesfully verify the desktop device, but that sets the button for the mobile device on unverify.  Clicking that button changes the status for the desktop device.  Gong to another room and coming back restored normal behaviour.

**Comment by turt2live** [comment]
We're changing this whole UI with cross signing, so I'm closing this as fixed under that umbrella. It's probably still a bug with the old UX (which people are subjected to), but I'm inclined to believe it's fixed under the new stuff.
