### ISSUE TITLE
Cannot restore session in Firefox after closing tab

### ISSUE THREAD

**Issue by tx1683** [vector-im/riot-web#10581]
### Description

After closing tab, even in new and empty Firefox profile with default settings, and not in private mode, sessions are not preserved.
Especially annoying combined with bug: https://github.com/vector-im/riot-web/issues/10577

### Steps to reproduce

- Normal Riot Web usage
- Close tab
- Reopen Riot

Session should be preserved as in other websites which are working correctly (you are kept logged in).

### Version information

- **Platform**: web
- **Browser**: Firefox 60.8.0esr
- **OS**: Debian 9
- **URL**: riot.junta.pl 1.3.2

**Comment by jryans** [comment]
Are you low on disk space? It's possible the browser can't completely store you session data.

Please submit debug logs (top left menu -> Settings -> Help & About -> Submit debug logs) and reference this issue so we can investigate further.

**Comment by jryans** [comment]
More details needed, please reopen if you can send them.
