### ISSUE TITLE
Need to remove alias but is not work

### ISSUE THREAD

**Issue by liberodark** [vector-im/riot-web#10589]
Hi,

We suffered an attack for which I need to change the rights of a user who admin but impossible.
In addition I also need to delete an alias.
how could a user put such an alias on our server ?

cordially

Bad alias : 
https://riot.im/app/#/room/#sperme:matrix.org

Official Adresse is : https://riot.im/app/#/room/#linuxosfr:matrix.org

**Comment by turt2live** [comment]
Please contact support@matrix.org and patiently wait for a response.

**Comment by liberodark** [comment]
Thank
