### ISSUE TITLE
Securiy issue with Alias

### ISSUE THREAD

**Issue by liberodark** [vector-im/riot-web#10595]
Hi,

For what a simple user have permission to add alias ?

![image](https://user-images.githubusercontent.com/4238928/63283644-14c60600-c2b2-11e9-8a54-1188c2cd72f5.png)

And have this rules : 
![image](https://user-images.githubusercontent.com/4238928/63283673-2effe400-c2b2-11e9-9d42-ec5a0c5c5db7.png)

For me is important to lock that on admin or moderator.

Best Regards

**Comment by turt2live** [comment]
Anyone in the room. Please use #riot:matrix.org on Matrix to ask questions - our issue tracker is a poor place to get reliable answers.

**Comment by liberodark** [comment]
ok thanks
