### ISSUE TITLE
Ensure IS in account data is read / written as specced

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10597]
We should ensure that both reading and written the IS in account data follows the model specced by [MSC2230](https://github.com/matrix-org/matrix-doc/pull/2230).

**Comment by turt2live** [comment]
@jryans 2140 or 2230? If 2230, I think this is solved by https://github.com/matrix-org/matrix-react-sdk/pull/3320

**Comment by jryans** [comment]
Ah right, 2230, thanks. I updated the top comment to clarify.

I opened this after @dbkr mentioned something about clients needing to write the IS value to account data after login, as I couldn't recall that happening in Riot changes so far.

It's quite possible there was a miscommunication and/or I misinterpreted. Looking at MSC2230, it seems like clients are meant to:

* Write to account data when the user changes the IS in Settings
* Read from account data and apply a new IS value if it appears in the account data
  * If `m.identity_server` is missing entirely, use a default IS value from config, .well-known, etc.
  * If `m.identity_server` is present and null, disable all IS features

If that's a correct reading, then I think Riot is following the spec indeed.

@dbkr, maybe you can clarify / repeat your mental thread from this morning?

**Comment by jryans** [comment]
In the privacy sync, we agreed that clients **should not** write any IS in account data in login / startup and clients **should** apply any changes via account data as they come down.

@dbkr suggests we may need to update the MSC to match this.

**Comment by dbkr** [comment]
So there are difference between the impl and the spec, but our conclusion is that we want to do what the impl currently does (ie. update account data only if explicitly set by the user in settings, always use a value if it comes down in account data)

**Comment by jryans** [comment]
I have added comments to the MSC on the bits that seem like they need to be updated to match Riot. Since there's nothing for Riot to change, I think we can close this issue.
