### ISSUE TITLE
Feature request: Set custom home server address if MXID is provided instead of Username?

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/riot-web#10590]
### Description

The login process is a little bit confusing for users not used to federated instant messenger if they have to provide a custom home server address in a sub menu. Would it be possible to set a custom home server if a Matrix ID is provided in the field "Username" so that the client recognizes the custom home server address from the given MXID automatically?

### Steps to reproduce

1. Open https://riot.im/app/#/login to login with an account on a custom home server.
2. If you provide `@myuser:example.com` as Username you get the error "Invalid homeserver discovery response".
3. You have to click "Change" to set `https://example.com/` a custom "Homeserver URL" to log in to your account on your custom home server.

#### Describe how what happens differs from what you expected

I would like to see that Riot sets the custom home server address in step 3 automatically if I provide `@myuser:example.com` in step 2 so that I just need to tell my users: "Provide `@myuser:example.com` for "Username" and your password and choose "Sign in" to log in (so no need to set a custom home server address).

Thx for Matrix and Riot!

**Comment by turt2live** [comment]
It's complaining that the response it got from https://matrix.org/docs/spec/client_server/r0.5.0#well-known-uri is invalid - setting that up should magically make it work.

**Comment by r4dh4l** [comment]
Thx @turt2live but I think my well-known setup is right:

For client:

```
{
	"m.homeserver": {
		"base_url": "https://my.ddns.net:443"
	},
	"m.identity_server": {
		"base_url": "https://my.ddns.net:443"
	}
}
```

For server:

```
{
	"m.server": "my.ddns.net:443"
}
```

...isn't it?

**Comment by turt2live** [comment]
if you're running a homeserver and identity server at those locations, yes.

**Comment by jryans** [comment]
As Travis mentions, this should be working if you have a valid .well-known config. I have confirmed that Riot correctly supports entering `@bob:matrix.org` when the default is some other homeserver, for example.

We have found that GitHub issues are not a good medium for support questions that affect specific installations. The appropriate Matrix room for Riot or Synapse questions depending on the problem is a better place for support as it is interactive and more people are present to help.

If you need more help on this issue, I'd suggest asking in #synapse:matrix.org to troubleshoot your config.

**Comment by r4dh4l** [comment]
Thx for confirming. So I try to find the problem in my config.

However:

> We have found that GitHub issues are not a good medium for support questions that affect specific installations. The appropriate Matrix room for Riot or Synapse questions depending on the problem is a better place for support as it is interactive and more people are present to help.

With all due respect, it is nice that _you_ "have found hat GitHub usses are not a good medium for support questions". Although this issue was initially totally not a support request GitHub issues are currently the only real sustainable possibility to ask for help as long the there is no official forum as requested (and well motivated) in https://github.com/matrix-org/matrix.org/issues/43.

However: Thx for your reply.
