### ISSUE TITLE
Accounts which are created after invitation are periodically kicking out of the room

### ISSUE THREAD

**Issue by nesnera** [vector-im/riot-web#10592]
### Description

Accounts which are created after invitation are periodically kicking out of the room

### Steps to reproduce

1) Have a room and invite user which have not yet matrix account (by email)
2) When new account is created you can see that he accepted invitation before he do it manually
3) The user accepts the invitation and enters the room. He can read and wirte posts but he is kicked out within tens of minutes (I don't know it exactly, but it happens certainly within an hour)
4) Step three happens repeatedly (It's very bad for getting new users)
It's realy bad for getting new users, I'm afraid. :-/

It's realy bad for getting new users, I'm afraid. :-/

I have already tried to find a solution, but unsuccessfully. I tried:
- reject invitation, create new one and accept it
- kick off user (when looks be a member) and rejoin

Logs being sent: no

### Version information

- **Linux 4.13.12/Fedora 28**: Mozilla Firefox 66.0.4
- room and accounts are at riot.im server

**Comment by nesnera** [comment]
Workaround:
- accept invitation
- leave room
- logout (I'm not sure if it's necessary)
- add room (find as `#<room_name>:matrix.org` and join again)

**Comment by nesnera** [comment]
[Workaround](https://github.com/vector-im/riot-web/issues/10592#issuecomment-524526902) is good for many hours put it doesn't work permanently

**Comment by turt2live** [comment]
Closing in favour of synapse issue: https://github.com/matrix-org/synapse/issues/5908
