### ISSUE TITLE
Change AddressPickerDialog to use MultiInviter

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10600]
We should change `AddressPickerDialog` to use `MultiInviter` like all other invite flows. This would allow Riot to have only one code path for initiating invites. In addition, it would change the address picker dialog from "client looks up 3PID" to "client sends 3PID invite to HS for lookup", which is how the other invite flows are functioning today.

**Comment by t3chguy** [comment]
Address picker is used for non-invite things too though, like adding rooms to communities

**Comment by turt2live** [comment]
fwiw the reason why we do a lookup is for UX purposes, not for invite purposes. https://github.com/vector-im/riot-web/issues/10556#issuecomment-523539667 has a bit more detail.

Is there anything actionable here? It seems like we want to do the lookup intentionally, so MultiInviter means nothing here.

**Comment by jryans** [comment]
No, it seems like now that we've talked through the UX, we actively want to keep things as they are here.
