### ISSUE TITLE
message composer puts the first character at the end and the cursor at the start and wtf

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#10613]
![Peek 2019-08-22 12-38](https://user-images.githubusercontent.com/1389908/63511762-f6daea00-c4d9-11e9-9c48-d1eef54e7194.gif)

**Comment by richvdh** [comment]
this fixed itself when I switched rooms. I don't know how to repeat it :/

**Comment by jryans** [comment]
Sorry to hear about this. We are in the process of replacing the composer (you can test it on develop via Settings -> Labs). Since we're not sure how to reproduce this, I think I'll close for now, but let us know if more information is available.
