### ISSUE TITLE
Adding e-mail through web does not work, Android way it does

### ISSUE THREAD

**Issue by smarek** [vector-im/riot-web#10623]
### Description

I've received invite to room on my e-mail address, then find out that the email is not paired with the account (which was using only username, no phone number).
I've tried multiple times to add e-mail through web-interface, click on username on the left top, filled the email address, got verification email, clicked the link which shown "Verification successful! Please return to your Matrix client to continue.", however the email was not added.

After I've tried with my Android device (F-Droid retrieved version 0.8.28a F-3bc5baad3),
in settings filled the email, opened the link in the same computer, where web-way did not work, clicked continue in mobile app, and the email was added on 1st try

### Steps, to reproduce

- Using matrix.org username-only account
- Login, open profile settings, fill in the e-mail
- Receive the "Your Riot Validation Token" email
- Open the link in the web browser
- Link https://vector.im/_matrix/identity/api/v1/validate/email/submitToken?token=redacted&client_secret=redacted&sid=redacted
- See the confirmation message "Verification successful! Please return to your Matrix client to continue." along with riot.im logo on the confirmation page
- Open the profile settings in the web-client https://riot.im/app and see that no e-mail has been added

### Version information

- **Platform**: web in-browser
No visible errors in browser console, no resource errors (such as HTTP 404/400/500/etc.), no JS errors (first few tries were with JS disabled, then few with JS enabled, which made no difference)

For the web app:

- **Browser**: google-chrome-unstable 78.0.3887.7 amd64
- **OS**: Linux
- **URL**: riot.im/app and vector.im/_matrix/identity/api/v1

**Comment by turt2live** [comment]
It should have given you a button to press to finish the verification - was this button not present?

![image](https://user-images.githubusercontent.com/1190097/63549293-5989b100-c4ed-11e9-8edd-934e7c913b16.png)

**Comment by smarek** [comment]
I'd swear it did not appear, but re-trying with different e-mail address and same account, showed the button as you suggested, so this is probably just PEBKAC

I'm voting for this report to be changed from bug to UX-issue, because I simply ignored whatever the button text was, because niether it's position or visual changed, all I could see was "we sent you e-mail", and I did not read the rest, because the same process in similar web-usecases is always the same, "go click the link in the email, then refresh this page"

I suggest using the same UX which is used in Android, modal dialog, same description text, button might read something different than "continue" (maybe something along the "click after opening the link from e-mail", web browsers have the space for large buttons.

**Comment by turt2live** [comment]
I'm going to close this in favour of https://github.com/vector-im/riot-web/issues/715 because it calls for a better UX (just work rather than require the user to do anything).
