### ISSUE TITLE
I don't know what it means when the people icons have other little people in the bottom right corner?

### ISSUE THREAD

**Issue by xpseudonym** [vector-im/riot-web#10624]
### Description

some people icons have little people in the bottom right and others don't, see screen shot?  What's the difference?
![Screenshot from 2019-08-23 08-24-54](https://user-images.githubusercontent.com/5032475/63575067-1547f080-c581-11e9-9ecc-2dc67c5c0ab4.png)

### Steps to reproduce

- Use Riot desktop client

Describe how what happens differs from what you expected.

- Desktop client elements should be intuitive or explained

Log: not sent    

### Version information

- **Platform**: desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Fedora GNU/ Linux
- **Version**:
matrix-react-sdk version: <local>
riot-web version: 1.3.0
olm version: 3.1.0

**Comment by t3chguy** [comment]
They denote whether a room is marked as "People" or "Rooms", if you were to un-favourite all of them then 3 would go into People and 1 into Rooms.

You can remedy this by right-clicking the room and selecting `Direct Chat`, it is merely a grouping label

Support/Query requests like this (not bugs and feature suggestions)  are better suited for `#riot:matrix.org`

**Comment by xpseudonym** [comment]
Many thanks for that - will try and find a better home for my queries next time
