### ISSUE TITLE
Unable to add email address to HS account without IS set

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10637]
At the moment, it is standard for a homeserver to require an identity server to be passed as part of adding an email to your HS account.

This will be changing for future Synapse versions as they learn to manage email themselves, but for the moment it is still the current state.

Riot Web on develop at the moment assumes we've already made it to ideal world, creating the following problem:

1. Disconnect from your IS in Settings
2. Try to add an email to your HS account
3. HS returns 400 error demanding an IS be passed

This can be reproduced on the termstest environment.

**Comment by jryans** [comment]
I suppose this is blocked on deciding how the product should function in this case... For old Synapse which requires an IS to be passed for adding an email to your account and you do not have one as you have disconnected from your IS, should we:

a. Show an error and force choosing an IS first (a bit confusing as the Discovery bits are further down in the Settings and not visually related to your HS account info)
b. Use Riot's default IS when talking to an HS that requires one
c. ...something else?

**Comment by jryans** [comment]
Paging @lampholder for product thoughts.

**Comment by lampholder** [comment]
Already fixed - we only show the 'add email address to account' UX if the hs is properly configured to send emails
