### ISSUE TITLE
Scalar's widget embed check doesn't handle redirects

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10639]
If https://example.org passes the embed check, Scalar will let the custom widget go through even though it redirects to https://www.example.org which doesn't support iframes.

**Comment by makyo** [comment]
Not sure if this is still applicable. Still, to make sure I'm understanding this correctly, https://example.org allows embedding, but https://www.example.org does not?

Currently, using `http.Head()`, redirects are followed blindly, and the final redirect's response headers are used. For example: https://gist.github.com/makyo/1e07a1065b2366e695df8ca5bc0b54d8

This works as expected in scalar:
![2019-10-23-082018_1916x1037_scrot](https://user-images.githubusercontent.com/303761/67408592-18099680-f56e-11e9-919f-ed0dfea33481.png)

**Comment by turt2live** [comment]
There was a specific example of this not working, though I'm failing to find the example :(

it was a cross-domain 302, not just a path, which may affect the result a bit. The deny might have also been on the wrapper's iframe specifically, which empirically scalar doesn't check for.

**Comment by turt2live** [comment]
Closing as this is technically "cannot reproduce"
