### ISSUE TITLE
New composer is incompatible with japanese IME

### ISSUE THREAD

**Issue by Ai-rin** [vector-im/riot-web#10646]
I use fcitx as input method framework. With the new composer, choosing suggestion from the popup list is problematic, and it tends to corrupt the input, instead of replacing it.
![Screenshot_20190823_141323](https://user-images.githubusercontent.com/29887769/63625610-c3e34400-c608-11e9-8f72-3e315f3cda4a.png)
![Screenshot_20190823_141441](https://user-images.githubusercontent.com/29887769/63625616-c8a7f800-c608-11e9-808b-bb79ec3181af.png)

**Comment by turt2live** [comment]
@Ai-rin which operating system and browser is this on?

**Comment by Ai-rin** [comment]
@turt2live It's openSUSE Tumbleweed x86_64 and Chromium 76.0.3809.100

**Comment by bwindels** [comment]
Got closed automatically by linked PR by accident, reopening

**Comment by bwindels** [comment]
@Ai-rin could you please test whether this is still an issue on latest /develop now the linked PR is merged?

**Comment by Ai-rin** [comment]
@bwindels I just tested. Now, the IME part works nicely, but at the end it produces empty messages in the timeline itself.
![Screenshot_20190829_201939](https://user-images.githubusercontent.com/29887769/63962022-bf041180-ca9a-11e9-8c1c-0e6981f559f6.png)

**Comment by bwindels** [comment]
Great that the IME part works well, the empty message should be an easy fix.

**Comment by bwindels** [comment]
Could you please try again on latest /develop @Ai-rin? Thanks!

**Comment by Ai-rin** [comment]
@bwindels I just reloaded and tried, but nothing changed. I still get empty messages.
Versions
matrix-react-sdk version: <local>
riot-web version: 435c14d8222b-react-de0719151f7a-js-42b359eb5c95

**Comment by Ai-rin** [comment]
After another update it's finally fixed! Thanks a lot, I'm closing the issue.
