### ISSUE TITLE
Video call: video preview not horizontally flipped

### ISSUE THREAD

**Issue by robertfromont** [vector-im/riot-web#10650]
## Description

When making a video call, the video preview (i.e. my view of myself) is not horizontally flipped.
The UX is uncomfortable, because the preview doesn't act like a mirror.

### Steps to reproduce

- Start a video call (in my case, to the Android Riot app)
- Look at the video preview of yourself

I expect the video to be horizontally flipped, as though looking in a mirror, but the image is 'right way round'.

Logs being sent: no

e.g. in the following screenshot, the text in the preview should be in mirror-imaged 'looking glass' text, but it's not.

![Screen Shot 2019-08-24 at 3 35 28 PM](https://user-images.githubusercontent.com/1911137/63641487-aacca880-c685-11e9-8d59-967890bf9760.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox version 68.0.2 (64-bit)
- **OS**: macOS
- **URL**: Private server hosted by modular.im, version info:
matrix-react-sdk version: <local>
riot-web version: 1.3.2
olm version: 3.1.0

**Comment by t3chguy** [comment]
This is configurable:
![image](https://user-images.githubusercontent.com/2403652/63641646-baf67f00-c6a9-11e9-912e-04b4c8021bac.png)
