### ISSUE TITLE
Checking email invite account is unclear when no IS set

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10669]
Since it's now possible to be disconnected from an identity server entirely (your session has no active identity server), it's unclear how some IS dependent features should function, such as:

Checking an email invite in the invite preview bar to ensure the invited email is for the active account (in case you have multiple Matrix accounts in different tabs, etc.)

![2019-08-23 at 15 53](https://user-images.githubusercontent.com/279572/63602578-ad64ca80-c5bf-11e9-89e1-a54aa922ed96.png)

I think we are at a stage where @lampholder needs to work out how the product should function for this case.

---

After some discussion, we'd like to use the following text for the different combinations:

1. Case: Email not added to account
Title: This invite to %(roomName)s was sent to somebody@example.com which is not associated with your account. 
Subtitle: Link this email with your account in Settings to receive invites directly in Riot.

2. Case: Email added to account, no ID server
Title: This invite to %(roomName)s was sent to somebody@example.com. 
Subtitle: Use an identity server in Settings to receive invites directly in Riot.

3. Case: Email added to account, have ID server but email not bound
Title: This invite to %(roomName)s was sent to somebody@example.com. 
Subtitle: Share this email in Settings to receive invites directly in Riot.

4. Case: Email added to account, email bound on ID server (success case, unchanged from current)
Do you want to join %(roomName)s?
userName invited you

In all cases, the button will just say "Join the discussion".

**Comment by lampholder** [comment]
The current text is actually:

```
This invite to Testo wasn't sent to your account
Sign in with a different account, ask for another invite, or add the e-mail address somebody@example.com to this account.

[ Try to join anyway ]
```

This is not correct or helpful. You don't need to take any of the steps suggested, and there is no 'try' - joining will just work. 

We could make this more simple and more correct by:
- not talking to an IS at all and just comparing the email address in the invite to the email addresses associated with your account on the homeserver
- changing the message text to something like:

```
This invite was sent to **somebody@example.com**, but this email address is not associated with your account.

[ Join anyway ]
```

**Comment by turt2live** [comment]
We don't know that the invite will succeed though - if the room is private then the join will fail still unless you also happen to be invited by mxid.

**Comment by turt2live** [comment]
@lampholder it's also unclear what all the copy for the states is, if anything. Putting this back as blocked until we have copy for all the states we care about (ie: https://github.com/vector-im/riot-web/issues/10669#issuecomment-525861980 )

**Comment by lampholder** [comment]
> We don't know that the invite will succeed though - if the room is private then the join will fail still unless you also happen to be invited by mxid.

Is this true?

I:
- created a new room (incidentally on lant.uk)
- configured it like this:
    <img width="604" alt="Screenshot 2019-09-02 at 10 30 46" src="https://user-images.githubusercontent.com/1922197/64105107-759f1500-cd6d-11e9-84ef-ddb82b8ac40e.png">
- invited a random email address (not associated with any mxid in any way)
- logged into a super old (pre redesign) riot with a test acccount
- grabbed the link from the email and navigated to it
- got some UX that looked like this:
    <img width="891" alt="Screenshot 2019-09-02 at 10 30 30" src="https://user-images.githubusercontent.com/1922197/64105460-33c29e80-cd6e-11e9-9cfc-913742c12dcd.png">
- clicked accept
- joined the room

**Comment by jryans** [comment]
As far as text for the different combinations, how about:

1. Email not added to account
This invite was sent to somebody@example.com, but this email address is not associated with your account.

2. Email added to account, no ID server
This invite was sent to somebody@example.com. Use an identity server in Settings to receive invites directly in Riot.

3. Email added to account, have ID server but email not bound
This invite was sent to somebody@example.com. Share this email in Settings to receive invites directly in Riot.

4. Email added to account, email bound on ID server (success case, unchanged from current)
Do you want to join %(roomName)s?
<userName/> invited you

In all cases, the button will just say "Join". @lampholder, how does this sound?

**Comment by lampholder** [comment]
1. still sounds a bit errory to me (I anticipate users feeling a little confused by the 'but' there if it doesn't actually stop them joining the room).

How about:
This invite was sent to somebody@example.com which is not associated with your account. Link this email address with your account to receive invites directly in Riot.

Otherwise looks good.

**Comment by jryans** [comment]
Okay, great. I posted the revised version in the top comment of this issue.

**Comment by turt2live** [comment]
> Is this true?

Technically, yes. The 'accept' button does a different thing than what you're imagining. It's claiming the invite because it has all the information to do so, even without your email being added.
