### ISSUE TITLE
Sizing issue of rooms area in left panel

### ISSUE THREAD

**Issue by remram44** [vector-im/riot-web#10665]
### Description

The multiple separate scroll areas have always been hostile to users in more than a handful of rooms, but this is a new low:

![Screenshot_20190827_115606](https://user-images.githubusercontent.com/426784/63787659-329ef680-c8c2-11e9-8f23-09b04174187e.png)

I am in 19 rooms, but can only see one at a time after I log in and collapse "low priority". There is blank space at the bottom. Eventually after collapsing/expanding both "rooms" and "low priority" I can get to the normal situation (normal situation being getting 4 lines to scroll through my 19 rooms, if I don't collapse "favorite" or "people", which is still a major inconvenience).

### Steps to reproduce

- Be in many rooms

### Version information

- **Platform**: web (in-browser) or desktop? Firefox Desktop on Ubuntu, `riot.im/app`

```
matrix-react-sdk version: <local>
riot-web version: 1.3.2
olm version: 3.1.0
```

**Comment by remram44** [comment]
This is still a problem, no change. Bump.

**Comment by turt2live** [comment]
Fixed in the new room list
