### ISSUE TITLE
SVG file preview not working. after a click on the image only it's showing.

### ISSUE THREAD

**Issue by akhilin** [vector-im/riot-web#10689]
SVG file preview not working. after a click on the image only it's showing.

matrix 1.0.0
riot-web 1.2.1

Google Chrome | 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux
JavaScript | V8 7.6.303.29
Flash | 32.0.0.238 /home/akhil/.config/google-chrome/PepperFlash/32.0.0.238/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**GIFshot**

![Peek 2019-08-29 15-12](https://user-images.githubusercontent.com/21128035/63929905-e5608780-ca6f-11e9-86a5-b7364fac0b91.gif)

**Comment by turt2live** [comment]
Synapse does not support thumbnails for SVG images, unfortunately. Closing in favour of https://github.com/matrix-org/synapse/issues/1309
