### ISSUE TITLE
CIDER puts mxid in text fallback for pills rather than displayname, breaking notifs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10682]

**Comment by ara4n** [comment]
may be the same as #10681

**Comment by turt2live** [comment]
Possibly not, because the mscbot doesn't ping either. Unless it does the same thing?

**Comment by bwindels** [comment]
Hmm, not sure what you mean, CIDER puts `<a href=\"https://matrix.to/#/@bruno4:matrix.org\">Bruno the bloodhound</a>` and Slate puts `<a href=\"https://matrix.to/#/@bruno4:matrix.org\">Bruno the bloodhound</a>:`. Maybe the missing colon :thinking: ?

**Comment by turt2live** [comment]
The `body` (not `formatted_body`) has the mxid instead of the display name. See https://matrix.org/docs/spec/client_server/r0.5.0#user-room-and-group-mentions for info
