### ISSUE TITLE
CIDER: tab-completing a nick when it's at the beginning of a line should append <colon><space>

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10680]
for compat with previous composers and other clients

**Comment by bwindels** [comment]
Will have a look, might need some further refactoring in CIDER but nothing too major.

**Comment by Ai-rin** [comment]
It still doesn't, when nick inserted by mouse click (on nick in timeline or on "Mention" in user info)

**Comment by bwindels** [comment]
> It still doesn't, when nick inserted by mouse click (on nick in timeline or on "Mention" in user info)

Indeed, I'll create a separate issue for this.

**Comment by bwindels** [comment]
Tracking doing the same when inserting mentions as https://github.com/vector-im/riot-web/issues/10719, closing this one.
