### ISSUE TITLE
hitting enter in CIDER while autocompleting should send the message rather than commit the autocomplete

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10693]
i think this is how slate & draft worked

**Comment by bwindels** [comment]
I [recently changed](https://github.com/matrix-org/matrix-react-sdk/pull/3287/commits/e2dfe888ccae21e8eeec83686fa374cc24704967) it to be in line with what slate does:
 - if an option is selected, require enter to confirm the autocomplete
 - if no option is selected, enter is not captured by the autocomplete and sends the message straight away.

Just tried again and that seems how slate works for me. Maybe I'm missing something?

**Comment by ara4n** [comment]
hm, what does it mean to have an autocomplete open but no option selected?
it just seems a bit weird to type "hello bru<tab><return>" and have to then hit <return> again to get it to send. the act of hitting tab should be acceptance enough.

**Comment by ara4n** [comment]
(from memory, slate also had this bug at first until i fixed it)

**Comment by bwindels** [comment]
> hm, what does it mean to have an autocomplete open but no option selected?

Indeed, opening autocomplete either with tab and then hitting arrow up to go back to the text you entered, or typing @bru... e.g. nothing highlighted in the autocomplete box and no pill in the composer.

We can definitely change it, just want to make sure that we're not misaligned on what slate currently does.

**Comment by ara4n** [comment]
hm, you're right. it still feels clunky to me and a thinko. perhaps draft got it right, and we never fixed it for slate?

**Comment by bwindels** [comment]
cool, will change. Didn't think too much about it when adopting the behaviour but does make sense to never require enter.
