### ISSUE TITLE
What colour are our links supposed to be?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10703]
In the timeline they are blue with underline, in settings they're green with underline sometimes, and elsewhere they're green with no underline

**Comment by jryans** [comment]
In authentication flows, they are green with no underline... I suppose I caused this to multiply while working on https://github.com/matrix-org/matrix-react-sdk/pull/3359 which was trying to implementing this screen:

<img width="1792" alt="Screenshot 2019-08-23 at 15 03 48" src="https://user-images.githubusercontent.com/4626865/63626283-55c26100-c5b7-11e9-84ed-5e5d48fab701.png">

**Comment by nadonomy** [comment]
As a general rule, text links should be blue, and we should be using green for primary actions & accents.

In practise, it's used wildly inconsistently. I can add to my list to comp & write up a clear proposal for us to clean this up everywhere (and probably get to it in 1-2 weeks) if that's useful.

Are there any specific pieces though we could action to unblock p1/release blocking things now?

**Comment by jryans** [comment]
@nadonomy So is "Use the default" from the above screen a "text link" or a "primary action"...? It is linked text that completes an action we're suggesting...

The same applies to things like "Change" links in authentication flows:

<img width="448" alt="2019-08-30 at 17 24" src="https://user-images.githubusercontent.com/279572/64036440-1cf03200-cb4b-11e9-8772-abe7284e8b32.png">

There are many "text links" above that also trigger actions in the app, so should those be green or blue?

**Comment by nadonomy** [comment]
Sorry I could've explained that better! As a general rule:

If it's a call to action (like everything in the auth screenshot) then it should be green.

If it's informational (a link in a message, the bullets in the upgrade dialog) then it shoudl be blue.

**Comment by jryans** [comment]
Okay, I think it was broadly correct then until my recent PR https://github.com/matrix-org/matrix-react-sdk/pull/3359 which made all dialog links green.

I'll restrict that to just the address picker dialog then, and I think that covers the main confusion here.
