### ISSUE TITLE
New composer triggers browser spell check for pills

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10701]
In Firefox 70, the new composer triggers spell check on pill content like display names (which are highly unlikely to be words):

<img width="404" alt="2019-08-30 at 16 11" src="https://user-images.githubusercontent.com/279572/64031692-d990c600-cb40-11e9-8fe1-b6302d59969c.png">

**Comment by jryans** [comment]
To be explicit, this is different from the old composer, which did not cause browser spell check for pill content.

**Comment by bwindels** [comment]
@jryans could you please try again in FF70 once the above PR gets merged? I couldn't repro on FF70 on Linux fwiw...

**Comment by jryans** [comment]
Yes, this fixed it for me on macOS, thanks! 😁
