### ISSUE TITLE
We treat an empty string identity server as not having one

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10704]
It should default to the client as far as https://github.com/matrix-org/matrix-doc/pull/2230 is concerned

**Comment by turt2live** [comment]
actually, @lampholder, what do you think about treating invalid data as `null`? The spec doesn't really say what we're supposed to do, but I would generally consider invalid as "Disconnected".

**Comment by jryans** [comment]
I think it seems reasonable to consider anything falsy or otherwise invalid as the same as `null` and disconnected.

@turt2live, I believe that's what Riot already does, so is the only task to clarify the spec on this point?

**Comment by turt2live** [comment]
yea, I'm tempted to throw this into spec territory and not riot territory. It's completely reasonable that invalid values be treated as none imo.

**Comment by jryans** [comment]
Great, I filed a [spec issue](https://github.com/matrix-org/matrix-doc/issues/2332) we can use to track over there.
