### ISSUE TITLE
Clicking on the Members button with a reaction tooltip open persists a tooltip you can't dismiss

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10705]

**Comment by turt2live** [comment]
how did you manage to get the mouse that far without the tooltip disappearing on you?

**Comment by nadonomy** [comment]
![Sticky Tooltip](https://user-images.githubusercontent.com/4626865/64046927-19948080-cb22-11e9-8578-ba9201f7499b.gif)

**Comment by turt2live** [comment]
... that's incredible, it should have disappeared well before you got to the icon

**Comment by nadonomy** [comment]
> ... that's incredible

I feel honoured! 😀

Admittedly upon reproducing the issue it doesn't happen every time, but often enough that I'm able to run into the issue while absentmindedly using the app.

**Comment by t3chguy** [comment]
UX here is different and this no longer applies
