### ISSUE TITLE
Mobile ICE (MICE) support

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#10712]
Coturn has Mobile ICE (MICE) support (http://tools.ietf.org/html/draft-wing-tram-turn-mobility-02).
1. Should it be supported in riot?
2. Should I open separate issues for riot-android, riotX-android and riot-ios?

**Comment by jryans** [comment]
It looks like this idea did not make it beyond the draft RFC stage? https://datatracker.ietf.org/doc/draft-wing-tram-turn-mobility/

At least in Riot Web, the ICE negotiation is handled by the browser internals, so there's not much Riot itself can do here. It might be different for the mobile apps, but I would guess we'd want an active spec to exist first.
