### ISSUE TITLE
Allow bridging to private Slack channels

### ISSUE THREAD

**Issue by ADmad** [vector-im/riot-web#10713]
Currently if I use "Manage integrations", select "Slack" followed by "Event Bridging" it provides a list of channels which doesn't include private channels.

**Comment by jryans** [comment]
Thanks for the feedback! 

Looking at the related issue on the Slack bridge (https://github.com/matrix-org/matrix-appservice-slack/issues/159), it sounds like we just need to change some bridge config for matrix.org version to support this. @Half-Shot, is that correct?

**Comment by Half-Shot** [comment]
Hiya, this is actually something we are working on right now. It's going to be part of the next slack bridge so I can give an eta of a few weeks at worst.

**Comment by Half-Shot** [comment]
Closing as this is being tracked in the slack repo.
