### ISSUE TITLE
Prevent 'exo' and 'exp' from proposing emojis

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10717]
When the strings 'exo' or 'exp' are typed into the message entry box, a collection of emojis is shown.  Maybe there are other strings for which this is the case.  This ought not to happen.

**Comment by aaronraimist** [comment]
just `XP` does it as well https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$MT9wqUhEcmJtx44YmDay1LEMwip9CrTs2aCHWNfNXUg?via=matrix.org&via=privacytools.io&via=chat.weho.st

**Comment by t3chguy** [comment]
`*xo` and `*xp` seem to always reproduce it where * is any set of characters

**Comment by Biep** [comment]
Including the empty set.

**Comment by turt2live** [comment]
The empty set is expected because it's a plaintext emoji.

**Comment by Biep** [comment]
But why have the * at all then?  Typing 'xo' or 'xp' causes the problem, it seems.

**Comment by turt2live** [comment]
I'm not defending the * being a problem, just that XP and XO are emoji which people use. exp is obviously not an emoji, and clearly a bug

**Comment by Biep** [comment]
I'd much prefer having a single, settable, delimiter for emojis.  If I don't type that (currently ":", but I'd prefer "#"), no emojis should be shown.

**Comment by t3chguy** [comment]
# is for rooms though

**Comment by Biep** [comment]
True.  Then maybe $, or another character that rarely shows up in "normal" text.

**Comment by t3chguy** [comment]
This got fixed at some point, probably upstream
