### ISSUE TITLE
Irritating reaction emoticon panel

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10720]
When the mouse pointer only hovers over the reaction button, the panel with emoticons pops up - for no reason, because in order to select an emoticon one still needs first to click the button.  And sometimes that panel is 'left behind' - it stays visible after the mouse has moved on.
Please let the panel only pop up after *clicking* the button, and disappear again after clicking it again.

**Comment by thosgood** [comment]
I'm guessing this was probably implicit in your suggestion, but the panel should also close if the user clicks anywhere outside of it too :-)

**Comment by turt2live** [comment]
It would be good to have gifs of what sorts of conditions don't cause it to go away. There's an area around the tooltip to prevent it accidentally dismissing (because that's much more annoying), but there are potentially some bugs with how that works. Please include browser and operating system information alongside the gifs.

**Comment by Biep** [comment]
@thosgood: yes, I guess so.  But (personal preference) clicking on one of the emoticons should *not* close it, as I might want to add another emoticon.
@turt2live: I'll try to get some.  And I hope calling up the screen shot program won't make it close, otherwise I'll have to edit a full screen print.

**Comment by Biep** [comment]
@turt2live: not what you asked, but this leads to the emoticon panel hopping up and down between having the heart and the thumbsdown selected.  I can only get the effect with those two emoticons - the other three pairs seem stable.  It is consistently reproducible.
![afbeelding](https://user-images.githubusercontent.com/12461597/64130348-056eae80-cdc2-11e9-8fe6-17c2b8e85103.png)
Ubuntu 19.04

**Comment by Biep** [comment]
@turt2live: This should be what you asked.
![afbeelding](https://user-images.githubusercontent.com/12461597/64277770-768d9d80-cf4b-11e9-8aa9-45eb4297857f.png)

**Comment by turt2live** [comment]
@Biep that's the kind of thing that would be good to report in a new, dedicated, issue.

**Comment by Biep** [comment]
You mean the first screenshot - the vibrating panel?

**Comment by turt2live** [comment]
No, I meant the stuck tooltip bug.

**Comment by Biep** [comment]
That second one I posted in reaction to your first comment here.

**Comment by turt2live** [comment]
right... which had the underlying implication of opening new issues for unique things. I'm not trying to discredit the panel as annoying, but triaging each annoyance on its own is a better option for us to try and fix the problems.

I've opened https://github.com/vector-im/riot-web/issues/10752 to track the issue. I see that you've opened https://github.com/vector-im/riot-web/issues/10751 already for the vibrating problem.

If you run into other cases where the tooltip gets tuck, please open a new issue. For now though, I'm closing this in favour of the two issues mentioned above.

**Comment by Biep** [comment]
But shouldn't this one stay open for the original issue: the panel popping up on hovering?  Or is there an issue for that one already too?

**Comment by turt2live** [comment]
At this point I'd recommend a whole new issue so the slate can be cleaned.

**Comment by Biep** [comment]
OK.
