### ISSUE TITLE
Hovering over the tray icon should show the rooms with unread messages.

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10737]
Most people will have some 'important' rooms, to messages of which quick attention is necessary, and others that can wait.  It also helps pintpoint the source of spurious counters.

**Comment by t3chguy** [comment]
https://www.electronjs.org/docs/api/tray#traysettooltiptooltip

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/7190
