### ISSUE TITLE
Bound 3PIDs warning should better explain what's being left behind

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10750]
The bound 3PID warning is too easy to dismiss and should be strengthened to clarify what's being left behind, that the user must take manual action, possible listing the 3PIDs that will be left bound, etc.

**Comment by jryans** [comment]
@lampholder, are there specific things you think the dialog should have to correctly inform?

**Comment by lampholder** [comment]
Current text:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/1922197/64429147-45c57980-d0ad-11e9-81a6-6629f74b5333.png">

Maybe something like:

## Disconnect Identity Server
You are still **sharing your personal data** on the identity server **identityserver.domain.tld**. 

We recommend that you remove your email addresses and phone numbers from the identity server before disconnecting.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/1922197/64429678-6cd07b00-d0ae-11e9-9448-b13b1661f0ef.png">
