### ISSUE TITLE
Revoke may be too vague for unbinding a 3PID

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10758]
We've had some feedback that a button with the word "Revoke" to unbind a 3PID is too vague / unnatural.

<img width="579" alt="2019-09-05 at 15 59" src="https://user-images.githubusercontent.com/279572/64353747-2a4b6780-cff6-11e9-9fd9-f375b5343e4b.png">

There was also some suggestion that the Share / Revoke flow would be simpler if it were a toggle switch (eliminating the need for labels), but there's an intermediate state where you validate an email and click a continue button, so it may not be a good match for a toggle.

**Comment by jryans** [comment]
@nadonomy, any thoughts on this? Maybe Revoke is okay for now, or perhaps there's a better word?

**Comment by nadonomy** [comment]
@jryans Maybe just [Stop Sharing]?

Once the user clicks on it, does the email address persist in the list (with a [Share] action?) or is it removed entirely?

**Comment by jryans** [comment]
> Once the user clicks on it, does the email address persist in the list (with a [Share] action?) or is it removed entirely?

Currently it remains in the list with a [Share] action.

**Comment by nadonomy** [comment]
Thanks!

In this case— is the email address removed from the IS? Or is it persisted with a 'don't share' state?

I think the best course would be to make this better represent what's going on under the hood.

**Comment by nadonomy** [comment]
> > Once the user clicks on it, does the email address persist in the list (with a [Share] action?) or is it removed entirely?
> 
> Currently it remains in the list with a [Share] action.

Having thought about it more, perhaps [Share] & [Stop sharing] is clearer? And then separately [Add] & [Revoke] for managing which email addresses are being managed by IS's.

**Comment by jryans** [comment]
> Having thought about it more, perhaps [Share] & [Stop sharing] is clearer? And then separately [Add] & [Remove] for which email addresses the IS knows of.

I think that makes sense to me.

Mobile is also wondering about this problem space as well. I think they really wish it could be a toggle switch on their side... 😅

**Comment by nadonomy** [comment]
Thinking more about it.. I can't think of a super strong rationale for it not to be. I could look at this in more detail visually later today if that's useful?

**Comment by lampholder** [comment]
The reason for a toggle being tricky is that horrible interstitial where you have to check your email then come back and click a button to complete the toggle state change.

I'm sure there exists a way to represent this nicely, it's just not absolutely as straightforward as switching the button dance for a toggle.

I would love to see a toggle though if we can find a way to handle the state transition.

**Comment by nadonomy** [comment]
What about if we had a toggle with 3 states:

- Off & Disabled, with micro copy/link to verify email
- Off
- On

?

**Comment by jryans** [comment]
For various reasons, we currently verify your email both when enabling and disabling sharing.

It could work for it to be disabled (either off or on) until you validate, though I am not sure if it would be overwhelming for every address to show the same copy by default about needing to verify first to "enable" the toggle, which you then need to click...?

**Comment by nadonomy** [comment]
Ah gotcha, I was hoping that the email addresses would be in an unverified state, and then when verified once we could simply show an off/on toggle.

I'll spend some time on this later today and see if I can find a toggle interaction that works, will report back with any useful findings.

**Comment by jryans** [comment]
For discussion purposes, here's the current UX today:

1. Go to Discovery section that looks as follows:

<img width="586" alt="2019-09-10 at 17 53" src="https://user-images.githubusercontent.com/279572/64633902-f6a47f00-d3f3-11e9-8ed6-67460175b795.png">

2. Click Share or Revoke button for an email address as appropriate

3. An email is sent to you, and the UI changes to: 

<img width="575" alt="2019-09-10 at 17 55" src="https://user-images.githubusercontent.com/279572/64634046-4aaf6380-d3f4-11e9-91b0-f1d9b005fdcd.png">

4. Click the link in the email

5. Click Continue in Riot

**Comment by jryans** [comment]
After chatting with @nadonomy, we're broadly okay with this interaction for Riot Web, except we'd like to change the UI after sending the email to:

Verify the link in your inbox [Complete]

As for mobile, it sounds like toggles are something we're more eager to explore there, so @nadonomy and @BillCarsonFr should sync on this.
