### ISSUE TITLE
FTUE: Small improvements for left panel

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#10759]
### Explore & Filter buttons
https://zpl.io/VD1q8yw
- [x] put "Explore" button up top
- [x] restyle filter field, with new interaction

### (+) buttons
https://zpl.io/brPYv47
- [x] make (+) go to create room dialog
- [x] update tooltips on (+) buttons

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/11486
