### ISSUE TITLE
Editing messages reacted to is dangerous

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10762]
There should be a way to make reactions conditional on the message not being subsequently edited.  If someone writes a message 'I X Trump', with X &elt; {love, hate}, and after reactions switches to the other word. the reactions may not correspond to the intentions of the reactor.

**Comment by tulir** [comment]
Duplicate of  #10136?

**Comment by Biep** [comment]
Partly.  Greying out the reactions given before the last edit might be another (and better) solution.

**Comment by turt2live** [comment]
Counting this as a duplicate of https://github.com/vector-im/riot-web/issues/10136
