### ISSUE TITLE
FTUE: Improve user lists in Create DM & Invite

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10764]
<img width="522" alt="Screenshot 2019-09-05 at 15 41 11" src="https://user-images.githubusercontent.com/4626865/64388338-9ed0d700-cff3-11e9-990d-78f95c824ece.png">

https://zpl.io/ad141pp

Notes
- [ ] List the 6 most recent DM’s, sorted by activity, then suggestions
- [ ] Ensure that search input yields results from all parts of the mxid (e.g searching for ‘matrix’ should also yield results from the domainpart, so users don’t need to to know mxid syntax, or have to prefix search queries with @)
- [ ] Ensure users can enter 3PID’s
- [ ] Display flair next to usernames, visualised the same as elsewhere in the app, capped at a max amount?
- [ ] Search results should have a selected result, which is navigable by keyboard (arrows) and completable (enter/tab)
- [ ] Highlight (with font weight) matching strings in search results when searching
- [ ] When ticking/completing search results, add pill & clear outstanding input
- [ ] If trivial, include profile pics in pills like in message composer
- [ ] After dogfooding, consider adding an x inside each pill to the right so users can delete pills with mouse input

TBD
- [ ] Profile link links to matrix.to link of own profile with target=”_blank” (Could explore adding this to a tooltip with copy to clipboard button also)— concerns that matrix.to links could be confusing, re-sync on this before implementation

**Comment by turt2live** [comment]
Closing in favour of smaller issues:
* https://github.com/vector-im/riot-web/issues/11197
* https://github.com/vector-im/riot-web/issues/11198
* https://github.com/vector-im/riot-web/issues/11199
* https://github.com/vector-im/riot-web/issues/11200
* https://github.com/vector-im/riot-web/issues/11201
