### ISSUE TITLE
FTUE: Improve wording when receiving an invite

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10766]
- [x] `User (@user:matrix.org) invited you` should be `User (@user:matrix.org) wants to chat`
- [x] `[Accept]` button should be labelled `[Start chatting]`

**Comment by turt2live** [comment]
@nadonomy is this for all invites or just DMs?

**Comment by nadonomy** [comment]
@turt2live sorry missed this— this should be DM only!
