### ISSUE TITLE
FTUE: Ensure the right panel is disabled until explicitly triggered for new users

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10769]
- [x] The right panel is distracting for new users, so should be disabled until triggered by the user
- [x] As a general rule, the right panel should only display when a button in the top right is explicitly clicked (maybe [related](https://github.com/vector-im/riot-web/issues/8772))

**Comment by Cadair** [comment]
Also maybe related #10149 ?

**Comment by turt2live** [comment]
While I'm here, here's a list of issues to fix:
* https://github.com/vector-im/riot-web/issues/9822
* https://github.com/vector-im/riot-web/issues/8772
* https://github.com/vector-im/riot-web/issues/10149
* this one
