### ISSUE TITLE
FTUE: Improve Create Room Dialog

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#10761]
https://zpl.io/brPYv47
 - [x] change fields, update design
 - [x] add topic field
 - [x] add public toggle
 - [x] add list to add aliases
 - [x] add validation of name and alias
 - [x] wire up new fields

Misc notes:
- Room name is mandatory
- When public, adding an alias is mandatory
- Use same components from login for validation & tooltips
- Validate in tooltip if a room address (alias) is available

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3464
