### ISSUE TITLE
FTUE: Ensure room sections are expanded for new users

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10770]
During testing & dogfooding I noticed room sections could be collapsed for new users, meaning they need to click on them to reveal rooms.

We should ensure the room list sections are always expanded for new users.

If useful: Latest Chrome on macOS, using /develop, connecting to matrix.org

**Comment by turt2live** [comment]
@nadonomy do you have more information on this? It seems fine for me:
![image](https://user-images.githubusercontent.com/1190097/69511973-74f6c480-0eff-11ea-9c08-def6160354a8.png)

**Comment by turt2live** [comment]
They are expanded by default. Assuming this is a non-bug.
