### ISSUE TITLE
Key backup prompt appeared even though key backup is already set up

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10776]
### Description

I switched to a room and saw the key backup prompt, which made me think my backup might've been deleted somehow. I went into settings to see that it instead is still there and fine, and when closing settings I saw that the prompt was now gone.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v71a
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by wrapper** [comment]
+1 I'm getting the key backup prompt on various rooms despite having enabled it multiple times on the same room / device.

**Comment by uhoreg** [comment]
Anoa's problem sounds like https://github.com/vector-im/riot-web/issues/9990.  wrapper's problem sounds different as it's persistent.

**Comment by jryans** [comment]
Yes, this sounds like a duplicate of https://github.com/vector-im/riot-web/issues/9990.
