### ISSUE TITLE
No check before inviting user(s) to a community they are already member to

### ISSUE THREAD

**Issue by Zeklandia** [vector-im/riot-web#10773]
### Description

Unlike when inviting users to a room, there is no check to make sure the user(s) being invited are not already members of the community they are being invited to. This results in users being both a member and invited at the same time. If they decline this second invitation, it will remove them from the community.

### Steps to reproduce

- Invite user to a community
- Have user join the community
- Invite the same user to the same community

Describe how what happens differs from what you expected.

I expected to receive a warning that the user(s) I tried to invite were already members of the community so their invitations couldn't be sent, like what happens with the same situation in rooms.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.3.2

**Comment by Zeklandia** [comment]
The underlying issue of double invitations and being kicked out upon declining a duplicate invitation are platform issues, but I do not know where in the pipeline that problem arises, so I am not sure where to report that.

**Comment by turt2live** [comment]
Closing in favour of the server-side bug: https://github.com/matrix-org/synapse/issues/2633
