### ISSUE TITLE
Declining a duplicate community invitation revokes membership

### ISSUE THREAD

**Issue by Zeklandia** [vector-im/riot-web#10774]
### Description

This problem follows from #10773. When a user is invited again to a community they are already a member of and they decline the invitation, they are removed from the community as if the invitation they declined was their original invitation.

### Steps to reproduce

- Invite user to a community
- Have user join the community
- Invite the same user to the same community
- Have user decline this second invitation

Describe how what happens differs from what you expected.

I expected the second invitation to be cancelled, removing the user from the "Invited" list.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.3.2

**Comment by turt2live** [comment]
I'm going to close this because fixing https://github.com/matrix-org/synapse/issues/2633 would fix this.
