### ISSUE TITLE
New composer: pasting images is a bit buggy

### ISSUE THREAD

**Issue by AlexDaniel** [vector-im/riot-web#10795]
The issue didn't exist in the previous composer. When pasting images (that are stored in the clipboard in a specific way), the data is pasted both as a file and as binary garbage in the composer.

This is how it looks:
![image](https://user-images.githubusercontent.com/5507503/64493611-eae97900-d28a-11e9-96f2-4ed4dc0f1041.png)

Notice the weird characters on the bottom in the composer.

To reproduce:
* Linux
* Riot on Firefox, with new composer enabled in the labs
* Take a screenshot using this command:
```
import png:- | xclip -selection c -t image/png
```
* Select part of the screen, now the screenshot is in your clipboard. Go to Riot, click on the composer and paste the image. You'll see “Upload files” dialog (which is correct) and also some unicodey characters in the composer (which should be fixed).

**Comment by bwindels** [comment]
Ahh, this must be a regression from https://github.com/matrix-org/matrix-react-sdk/pull/3392 . Will have a look. Thanks for testing!
