### ISSUE TITLE
riot-web allows unverifying itself (and doesn't allow re-verifying).

### ISSUE THREAD

**Issue by cloudyfuel** [vector-im/riot-web#10791]
riot-web 1.3.3 desktop.

In any room I'm able to unverify the currently used device. I think this shouldn't be possible nor is it possible on riot android. When I try to verify this device through the emoji method, I see a loading icon forever, only the legacy method allows me to re-verify.

**Comment by jryans** [comment]
It's no longer possible to unverify your own devices with cross-signing work in place.
