### ISSUE TITLE
Community invite should not talk about ISes at all.

### ISSUE THREAD

**Issue by AyoubGhaddab** [vector-im/riot-web#10800]
### Description

Hello,
i am trying to invite a person into a community page using an email address, after clicking the "invite to community" button, the popup window closes and there is no indication if the invite was sent or not, can someone explain to me if this feature is currently under development or am i doing something wrong. 

![image](https://user-images.githubusercontent.com/6554523/64528766-33437e00-d301-11e9-878f-75482650d49d.png)

### Steps to reproduce

- on a community page, click the 'invite to community' button.
- click the ' Use the default (vector.im)' link to open a new popup.
- put an address mail in the text field and click invite to community.

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
As the middle of your screenshot shows you can only invite by "Name or Matrix ID", not by email such as here: 
![image](https://user-images.githubusercontent.com/2403652/64529338-908bff00-d302-11e9-97b1-d1b158533b87.png)

**Comment by AyoubGhaddab** [comment]
@t3chguy  thankyou for your reply, but on the first popup windows; its state that the user can in fact  invite someone via mail using the identity server.
![image](https://user-images.githubusercontent.com/6554523/64529505-f5dff000-d302-11e9-8115-72ecf2c46880.png)

**Comment by t3chguy** [comment]
Interesting, that was recently added and it must have been incorrectly added to this modal.

**Comment by AyoubGhaddab** [comment]
Ah gotcha, oh well,  i was hoping that the feature existed, it would have helped us a lot in our daily workflow. any way thank you so much for your help.
