### ISSUE TITLE
user profiles no longer appear reliably when entering mxids into the invite dialog

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10801]
If you have an existing room and hit the Invite user button, and enter something like `@erikj:jki.re`, it doesn't successfully discover a profile (to reassure you that you have the right mxid) at any stage. Even though your local Riot knows about the profile, and presumably your HS does too.

<img width="766" alt="Screenshot 2019-09-09 at 13 25 06" src="https://user-images.githubusercontent.com/1294269/64530594-6e47b080-d305-11e9-899d-5c6d6eeb5dde.png">

**Comment by jryans** [comment]
I gave this a try with latest develop, and it appears to work as expected for me. We did make quite a few changes in here as part of privacy, so I think I'll assume this is fixed now.
