### ISSUE TITLE
Reacting to existing reactions should instantly update tooltip

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10804]
Adding a +1 to a reaction or redacting a reaction should instantly update the tooltip, the same way the react count provides instant feedback. Presently, you need to mouse away and re-trigger the tooltip. The lack of feedback makes it feel like the app or connection is broken.

**Comment by bwindels** [comment]
I think it does do that for me:

![reaction-feedback](https://user-images.githubusercontent.com/274386/64541995-4e6ab980-d312-11e9-9d11-6356974ea2ad.gif)

**Comment by nadonomy** [comment]
Ah, for _existing_ reactions:

![ExistingReactions](https://user-images.githubusercontent.com/4626865/64549809-56acff80-d2e6-11e9-843e-b44303a049a4.gif)

Will update the title to be more obvious.

**Comment by t3chguy** [comment]
outdated
