### ISSUE TITLE
Webcam not being recognized

### ISSUE THREAD

**Issue by derritter88** [vector-im/riot-web#10812]
### Description

I am using a Dell XPS 13" 9370 with Ubuntu 18.04. 
Unfortunately the build-in webcam is not being recognized by Riot.im app.
In general I can use the webcam (e.g. with Cheese). 

### Steps to reproduce

1. Open Riot.im
2. Go to config menu
3. No webcam is being listed

Describe how what happens differs from what you expected.
actual: Webcam not working.
expected: Webcam working.

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop

For the desktop app:

- **OS**: Ubuntu 
- **Version**: 18.04

**Comment by t3chguy** [comment]
Can you use the Web cam in chrome/chromium?

**Comment by derritter88** [comment]
To be honest: I haven't tried that yet as I do not use any Google spy apps.
Is there an alternative to test it?

**Comment by t3chguy** [comment]
The desktop app is built on chromium (electron)

**Comment by derritter88** [comment]
I have tried to use webcam with Chromium - this works without any issues.
Chromium asks for permission, I grant it and can use the webcam.

**Comment by SwoosOfficial** [comment]
This is still an issue.
On Kubuntu 19.10 riot-web 1.5.13.
"No webcam detected".
But works in Firefox and Chromium.

**Comment by cbrokaw** [comment]
I am experiencing the same issue in Linux Mint 19.3 and Riot 1.5.15. The camera works in Chromium, Firefox, Wire, and Cheese.

**Comment by derritter88** [comment]
I have found out what was "wrong" with my webcam - I did not read the manual until the end:
[https://snapcraft.io/riot-web](Snapcraft)

_Riot supports video calling, but the camera interface is disabled by default. If you wish to enable the camera in the Riot snap, after installation issue the following command in a terminal:

`snap connect riot-web:camera`_

**Comment by jryans** [comment]
Is everyone else here using the snap package?

**Comment by SwoosOfficial** [comment]
I used aptitude.

**Comment by morningstar1** [comment]
I'am using snap. For me `snap connect riot-web:camera` solved the issue.

**Comment by andriusign** [comment]
> I'am using snap. For me `snap connect riot-web:camera` solved the issue.

Confirmed on Linux Mint 19.3 Cinnamon.

**Comment by derritter88** [comment]
Okay so far seems that a few other had the same "issue" as I had.

**Comment by rebastion** [comment]
how can this be closed? still happens in latest Riot Desktop (Ubuntu), installed via ppa

**Comment by derritter88** [comment]
Closed it because my "bug" referrs to the snap installation and this was a simple user error.

**Comment by rebastion** [comment]
sorry my bad, took me a while as well to realize that snaps by default dont have camera permission and it can be solved by changing the permission in the software store :)
