### ISSUE TITLE
Favourite section keeps rearranging

### ISSUE THREAD

**Issue by Torxed** [vector-im/riot-web#10816]
`riot-web version: 1.3.3`

In this version (and maybe others), the favorite section keeps bouncing around. The entries change position when I click on them, messages being recieved etc.

I've turned off all automatic features I could find:

![2019-09-10-154104_1169x213_scrot](https://user-images.githubusercontent.com/861439/64618885-678e6b80-d3e1-11e9-9b93-1b684ea55094.png)

Related older issue: #8857

**Comment by Torxed** [comment]
Might not be related, but I can't manually re-arrange entries either. I used to be able to drag and drop entries in a order which suited me more.

**Comment by turt2live** [comment]
if possible, please go to your account settings and on the Help tab submit debug logs for this issue. A gif of the problem also wouldn't hurt.

Drag&drop is tracked as https://github.com/vector-im/riot-web/issues/8614

**Comment by Torxed** [comment]
I should mention, that during the above video. I never wrote anything in any of the channels. Neither did any of the participants/partner in those rooms/conversations. So the issue appears (I'm guessing) based on events such as activity, presence changes, etc.

**Comment by Torxed** [comment]
Logged out, cleared all the cache, logged back in. Still the same issue.
Thought it might have been because I kept cache between UI updates.

**Comment by Mikaela** [comment]
I think Element may have fixed this?

**Comment by Torxed** [comment]
> I think Element may have fixed this?

I mean yea, by always re-arranging the favorites by latest respondee heh.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/88266432-1e789a80-ccc7-11ea-9039-f4763f4ea589.png)

You can choose alphabetical if you prefer.

**Comment by Torxed** [comment]
> ![image](https://user-images.githubusercontent.com/2403652/88266432-1e789a80-ccc7-11ea-9039-f4763f4ea589.png)
> 
> You can choose alphabetical if you prefer.

That would work, if I can find the setting..
![Screenshot_20200723-103131_Element (Riotim)](https://user-images.githubusercontent.com/861439/88266593-c1cdad80-cccf-11ea-91f9-21b2e2834373.jpg)

**Comment by t3chguy** [comment]
Wrong repository for the mobile queries. Web and Desktop have the behaviour I screenshotted.
