### ISSUE TITLE
Possibilty to share window of desktop during video call

### ISSUE THREAD

**Issue by J0ker30** [vector-im/riot-web#10824]
### Description

Possibilty to share desktop-window during video call

### Steps to reproduce

- videocall

Describe how what happens differs from what you expected.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: all
- **Version**: 1.3.2

**Comment by t3chguy** [comment]
Closing as duplicate of https://github.com/vector-im/riot-web/issues/4880 or https://github.com/vector-im/riot-web/issues/245
