### ISSUE TITLE
infinite spinner on create account if registration is disabled

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10835]
it's cosmetic but ugly

**Comment by aaronraimist** [comment]
How do you get to that? Doesn't it fail with this error before you can get there?

![Screen Shot 2019-09-16 at 10 13 06 PM](https://user-images.githubusercontent.com/5855073/65008495-2a3d4880-d8cf-11e9-8748-b4e3be71db7b.png)

**Comment by turt2live** [comment]
It's when the default homeserver has it disabled:
![image](https://user-images.githubusercontent.com/1190097/65008787-be0b1680-d8c7-11e9-849b-33590719ed0e.png)
