### ISSUE TITLE
X in the room search field should appear on hover

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10843]
Having the room search field not be clear-able until I click inside the field to make the X show up is annoying.

**Comment by eras** [comment]
While I agree with this, this is so very related that I didn't file a new bug: clicking the X (after revealing it by clicking the field) also doesn't seem to work (it does nothing but hide the X again).

**Comment by dbkr** [comment]
Pulled out to https://github.com/vector-im/riot-web/issues/10857 as the 'x' button not working at all is a fairly large and very clean bug and is otherwise going to get lost in this bug about tweaking the UI.

**Comment by dbkr** [comment]
Actually this was fixed with https://github.com/matrix-org/matrix-react-sdk/pull/3432 too in that the 'x' now stays visible all the time if there's text in the box
