### ISSUE TITLE
Can't close your account if you've logged in with SSO

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10847]
This is probably true for all password-authed actions (change password, delete devices, delete key backup?, close account).

**Comment by softvision-sergiulogigan** [comment]
I think my situation fits this already opened issue:

I used to work with Mozilla, and during that time, I was logged into Riot using my SSO credentials.
Now, my SSO is disabled, and I cannot deactivate my account (it asks me to use SSO to prove my identity).

**Comment by t3chguy** [comment]
> Now, my SSO is disabled, and I cannot deactivate my account (it asks me to use SSO to prove my identity).

There is nothing that can be done about this on Riot's end, it just passes on the server's request for verifying your identity.
You should contact your server admins to resolve this issue.

This issue is actually solved as per https://github.com/matrix-org/synapse/issues/5667 being closed
