### ISSUE TITLE
apt package gconf2 and python2 dependency

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#10855]
GConf2 is deprecated, why riot depends on it?

```
% apt policy riot-web 
riot-web:
  Installed: 1.3.4
  Candidate: 1.3.4
  Version table:
 *** 1.3.4 500
        500 https://packages.riot.im/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
% apt depends riot-web 
riot-web
  Depends: gconf2
  Depends: gconf-service
  Depends: libnotify4
  Depends: libappindicator1
  Depends: libxtst6
  Depends: libnss3
  Depends: libxss1
```

```
# apt purge python2
...
The following packages will be REMOVED:
  gconf2* python* python2* riot-web*
...
```

**Comment by jryans** [comment]
I believe we are using the default deps from [Electron Builder](https://www.electron.build/configuration/linux#debian-package-options), so this upstream tool would need to be changed and upgrade in Riot to resolve this.

**Comment by xelaseer** [comment]
It looks like this has now been resolved upstream.

https://github.com/electron/electron/pull/19498

Can this dependency now be removed from Riot?

At this time, given that Python 2 (and gconf) are now EOL, users are forced to install unsupported (and potentially insecure) software to run Riot.

**Comment by 532910** [comment]
riot-desktop doesn't depend on python2 or gconf2 more
