### ISSUE TITLE
 "Missing translation" everywhere until reload

### ISSUE THREAD

**Issue by jnalanko** [vector-im/riot-web#10859]
### Description

Today the text "Missing translation" was popping up everywhere in the Riot web client. Refreshing the page fixed the issue.

### Steps to reproduce

Could not reproduce yet.

Logs being sent: no

Below is a screenshot (parts that would identify the room are grayed out).

![riot_translation](https://user-images.githubusercontent.com/912507/64859732-b92e3480-d633-11e9-9eba-3c573bcdd465.png)

### Version information

- **Browser**: Firefox 69.0
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by turt2live** [comment]
This is usually a caching problem out of our control. Logs would be appreciated to help confirm the problem

**Comment by aaronraimist** [comment]
Related: #9422

**Comment by turt2live** [comment]
I'm presuming this fixed by the caching problem. @jnalanko if you continue to experience the issue, please visit #riot:matrix.org on Matrix and the issue can be troubleshooted there.
