### ISSUE TITLE
Remove recent messages from user not visible unless you have other admin tools

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10852]
Should show up if you have permission to redact their messages, even if you can't ban them.

**Comment by bwindels** [comment]
You currently indeed can't redact messages of users that have a higher power level than yourself. Do we not want this?

**Comment by turt2live** [comment]
mass redaction in a DM or for yourself seems useful. There was also an instance where I was the same PL as a spammer and would have liked to remove their messages.
