### ISSUE TITLE
spellcheck no longer works in Firefox

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#10867]
Tested on Firefox 69.  It reportedly works in Chrome, so it may be something broken in Firefox.

**Comment by bwindels** [comment]
Is this specific to the (new) composer?

**Comment by uhoreg** [comment]
It's actually specific to the old (slate) composer, and seems to be working properly in CIDER.  Interestingly, if the composer loses focus and then regains focus, then misspelled words are highlighted as normal.

**Comment by jryans** [comment]
Ah yes, I have noticed this for quite a while with the old composer. I suppose we can close it once the new composer is on by default...?

**Comment by aaronraimist** [comment]
The new composer is on by default and Slate is gone so I'm closing this.
