### ISSUE TITLE
Mobile guide isn't picking up iPad as a mobile device

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10863]
![image](https://user-images.githubusercontent.com/1294269/64878246-fce06880-d64a-11e9-95e2-98d47cae937e.png)
iPad Pro 11-inch, iOS 13.1 (beta).

**Comment by bwinton** [comment]
To make your life harder, Apple has decided to make the user agent for the new Safari:
![IMG_0067](https://user-images.githubusercontent.com/159571/64878792-57b19a00-d622-11e9-856d-a12744e7333a.jpg)
(And in mobile mode:
![IMG_0068](https://user-images.githubusercontent.com/159571/64878814-639d5c00-d622-11e9-84cf-7cc1a0cbb7e7.jpg)
) 😉

**Comment by aaronraimist** [comment]
Actually with the new desktop class browsing in iPadOS 13 RIot web actually works pretty well. The only thing you I’ve found that you can’t do is drag to resize things.

**Comment by aaronraimist** [comment]
Can this be closed? Riot works fine on iPads.

**Comment by jryans** [comment]
Yes, with the desktop-class browsing, it seems like this is a decent experience, and so there's no need to make a change here. It seems clear Apple is trying to let iPad users visit sites as if they were desktop, so I think we should go with the flow here.

We may also be landing some mobile styling as well for smaller screens in the near future, so the mobile web story is improving in several ways at the moment.

**Comment by bwinton** [comment]
As an iPad user, I would expect to see a link to the app somewhere on that first screen, if only as an option… 🙂

**Comment by jryans** [comment]
Ah right, I've moved that part to a [new issue](https://github.com/vector-im/riot-web/issues/12209). 😄
