### ISSUE TITLE
Ability to have unread message counts separately from missed notif counts

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10868]
`@eric.shepherd:mozilla-test.modular.im` would like to have badges on the roomlist which show the number of missed messages, rather than the number of missed notifications.  This doesn't seem unreasonable (although it's interesting that this is the first time this has come up, to my knowledge).

**Comment by eternaleye** [comment]
I'll also note that there are a few different presentations that might be useful:

1. Separate badges for number of missed messages and number of missed notifications
2. Number of missed messages; boolean marker showing that there are also missed notifications
3. Number of missed messages if no missed notifications; if any missed notifications, that is shown instead (different color?)

I'd personally prefer the first, though I can definitely see people favoring other styles.

**Comment by aaronraimist** [comment]
Dup: #3374
Related: #5953
