### ISSUE TITLE
CIDER: when using autocomplete with a command, it is sent as text

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#10877]
![commandsentastext](https://user-images.githubusercontent.com/274386/64969503-900bdf00-d893-11e9-87e4-e4400c1a4b64.gif)

**Comment by bwindels** [comment]
when typing it out yourself, it works

**Comment by ara4n** [comment]
I just got bitten badly by this in HQ on current /develop (so it should have matrix-org/matrix-react-sdk#3468 in it).  Typing `/kick foo<tab> reason` enthusiastically sent the command as text.

**Comment by bwindels** [comment]
Can repro

**Comment by bwindels** [comment]
Made a PR to make the check a bit more resilient in any case. Please report if it would happen again after that.
