### ISSUE TITLE
TypeError: this._filter is undefined / save button on edits doesn't work

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10876]
see https://github.com/matrix-org/riot-web-rageshakes/issues/1733

**Comment by ara4n** [comment]
is this reproable? (i can't repro it)

**Comment by turt2live** [comment]
Bruno is having the same problem, and has been troubleshooting it in #riot-dev 

It seems to be a dependency problem (so far)

**Comment by bwindels** [comment]
I can't repro the editing failing as reported, but it would only happen if you have a filter set on your timeline.

**Comment by bwindels** [comment]
develop doesn't have the issue, app does ftr

**Comment by bwindels** [comment]
Ok, so this is already fixed in https://github.com/matrix-org/matrix-js-sdk/commit/3071587f11827aa672d5b3fc5bb3db574ff17c24 but hasn't been released yet.

**Comment by turt2live** [comment]
fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1034
