### ISSUE TITLE
Desktop: Clear filter room does not work

### ISSUE THREAD

**Issue by adriaaah** [vector-im/riot-web#10870]
### Description

In Riot-Web 1.3.4 a new filter room has been introduced. When you press the the X button next to it to clear the text, simply nothing happens and the introduced text is still there, instead of the expected behaviour that should be clear the text field and consequently display all the rooms.
Only by manually deleting the input text, the filter is emptied and hence all joined room are visible again.

### Steps to reproduce

- Join any room and it will appear in the left pane
- Click on "Filter" (left pane) and type some text
- Click on the X in the filter to clear the text you previously typed

I expect the text is automatically cleared when the X button is pressed, but the text remains.

Logs being sent:no

<img width="298" alt="Bildschirmfoto 2019-09-14 um 14 18 27" src="https://user-images.githubusercontent.com/11198894/64908135-4a68de00-d6fc-11e9-84ea-ffbc8cd3cc3f.png">

### Version information

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: macOS
- **Version**: 1.3.4

**Comment by t3chguy** [comment]
Fixes by https://github.com/vector-im/riot-web/issues/10842
