### ISSUE TITLE
UX regression when trying to invite by email if no IS is configured

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#10878]
On matrix.org HS with no IS, I get this screen on https://riot.im/develop:

![image](https://user-images.githubusercontent.com/8418515/64970060-5d6ae200-d8a5-11e9-9d26-e39146cecfcb.png)

The console says:
```
Error: "No Identity Server base URL set
```

#10619 suggested a better UX.

**Comment by jryans** [comment]
This is a regression introduce by https://github.com/matrix-org/matrix-react-sdk/pull/3408.
