### ISSUE TITLE
Package not available for debian/testing (bullseye)

### ISSUE THREAD

**Issue by sblondon** [vector-im/riot-web#10886]
Desktop app packages are available for several releases of Debian (and Ubuntu) at `https://packages.riot.im/debian/dists/`.
For Debian releases:
 - buster
 - jessie
 - sid
 - stretch

In july 2019, 'buster' has been published. So, currently, the 'testing' version has 'bullseye' codename. 

It would be nice to provide a 'bullseye' directory to easily install the package on 'testing' and the next 'stable' release.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```

**Comment by calbasi** [comment]
Hi, I think this iisue could be similar to this one:

https://github.com/vector-im/riot-web/issues/4661 (about adding Debian Buster).

In fact, if riot is on Debian unestable (Sid) and Debian Stable (Buster) I wonder why it is not for debian testing...

**Comment by calbasi** [comment]
By the way, Testing and Sid are very close each other... I've installed riot-web package just changing the /etc/apt/sources.list.d/riot-im.list with a "sid" reference:

`deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ sid main`

An alternative, and more user friendly way, will be that Riot maintainers create a Testing repository what just be a symbolic link to Sid repository (or just a clone if symbolic lyncs have any problem on deb / apt system).

**Comment by sblondon** [comment]
I use the same workaround (use the 'sid' package on 'testing' system).

With the idea of symbolic link, perhaps only the codename packages (Stretch, Buster, Bullseye) could be generated. Symlinks would link to them so when a new version of Debian is released, only the symlinks have to be updated.

```
sid -> bullseye
stable -> buster
testing -> bullseye
```

**Comment by jryans** [comment]
We have now added a `default` distribution that anyone can use in https://github.com/vector-im/riot-web/issues/13367. It will contain `riot-desktop` when the upcoming 1.6 release goes out.
