### ISSUE TITLE
Windows 10 - Notification on taskbar doesn't clear if "read" on other device

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#10884]
I get a notification. Windows 10, the taskbar icon for Riot blinks and such, but I go to my phone and read the message, it gets marked read. The taskbar icon for Riot continues to be lit up, even though all notifications are cleared.

This should clear the blinking of the taskbar if all alerts are cleared by any other Riot session for the same account.

It only clears when I open un-minimize the app.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/9652

**Comment by BloodyIron** [comment]
@t3chguy lol sorry for duping my own post D:
