### ISSUE TITLE
we have a memory leak somewhere

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10890]
My riot tab gets to 3.5gb before noticeable slowness. Takes 24h or so to get there. This is recent - am looking into it

**Comment by richvdh** [comment]
+1. I've noticed an uptick in tab crashes in recent weeks.

**Comment by turt2live** [comment]
looks like ~18% of the tab's memory pre-crash is spent storing my own custom status. Comparing to a "normal" usage snapshot, only ~8% is used for custom status. Something seems to duplicate objects in there, somehow.

Also MegolmEncryption is a very heavy class, topping the charts in both the normal and pre-crash snapshots. Both at the same value though.

More investigation needed.

**Comment by turt2live** [comment]
Blocked on more data - custom status seems to be the fault for me, but I have a hard time believing that is the case for everyone affected by this.

**Comment by tuxayo** [comment]
Instructions for getting a memory profile, source + some changes : https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15698610401101qMXQV:t2l.io?via=matrix.org&via=taylorbuchanan.com&via=t2l.io

**Firefox:**
1. CTRL+SHIFT+I (I as in eye, again)
2. Click the Memory tab
3. Press the camera icon in the top left of the dev tools window
4. Wait a bit (suggest coffee)
5. When the save button appears in the left sidebar, click it and save it locally.
6. Send the file (optionally gzipped) to someone over a safe medium (it can contain your access token, though it shouldn't)

Note that with Firefox the tab might be inoperable during the process above.

**Chromium/Chrome:**
1. Press CTRL+SHIFT+I (I as in eye)
2. Go to the Memory tab
3. Select "Heap snapshot" and the riot.im VM instance
4. Click "Take Snapshot"
5. Make some coffee and wait.
6. After the profile is taken, there should be a save button on the left sidebar. Click that and save it to your hard drive somewhere.
7. Send the file (optionally gzipped) to someone over a safe medium (it can contain your access token, though it shouldn't)

Note that with Chorimum/Chrome the tab might be inoperable during the process above.

If you start catching the tab spontaneously freezing as you click around and type messages, grab a snapshot - there's a good chance it is about to crash on you.
A "normal" usage snapshot (~30-60min after reloading the page) and just before crash are the most helpful.

**Comment by Half-Shot** [comment]
Checking in to say I will get a white screen of death at least once a day, which I believe is due to memory consumption issues.

**Comment by turt2live** [comment]
@Half-Shot *please* get memory profiles so we can figure out what is going on. One of "normal" (about 30-60 minutes after startup) and one of just before crash (ie: the 23rd hour before crash). See https://github.com/vector-im/riot-web/blob/develop/docs/memory-profiles-and-leaks.md for more info

**Comment by Half-Shot** [comment]
Kk, will do.

**Comment by dbkr** [comment]
I've just noticed my riot-web had accumulated a lot of memory and snapshotted it. There was an awful lot of stuff retained by velocity so I suspect this has regressed again. Rather than taping it back up again I suggest we kill velocity as native CSS animations must be non-terrible by now.

**Comment by turt2live** [comment]
I also have a backlog of community profiles to look at, but am hoping to find a trend somewhere.

It sounds like we should kill velocity independently of bugs it might have.

**Comment by jryans** [comment]
If you do happen to have the custom status lab enabled, a leak in that feature was just fixed on develop.

**Comment by jryans** [comment]
@turt2live Is this general meta-issue useful to keep open? Are you still noticing memory issues?

**Comment by turt2live** [comment]
We still do have a memory leak, though not as severe as when reported. I'm not currently looking at it though

**Comment by turt2live** [comment]
I think we fixed this by accident.
