### ISSUE TITLE
Autocomplete unhelpful for screen readers

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10900]
related: https://github.com/vector-im/riot-web/issues/302

> Autocompletes not usable by non-advanced screen reader users.

**Comment by turt2live** [comment]
also:
> There's no indication that an autocomplete appeared.

**Comment by t3chguy** [comment]
> There's no indication that an autocomplete appeared.

is the only part which is not possible using ARIA attributes, this can be done as per the below example by using/abusing screen readers to read hidden text elements.

https://haltersweb.github.io/Accessibility/autocomplete.html
