### ISSUE TITLE
My 'people' room list has lost all the people

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#10919]
See https://matrix.half-shot.uk/_matrix/media/r0/download/half-shot.uk/c3e2fd8652460de46e4cde2bf11b5eef6b467778. This is on riot 1.3.3

**Comment by Half-Shot** [comment]
It fixed itself on scrolling, straaaaange.

**Comment by bwindels** [comment]
Likely to be a problem with `LazyRenderList`

**Comment by bwindels** [comment]
Sounds like a dupe of https://github.com/vector-im/riot-web/issues/8811
