### ISSUE TITLE
Context menus have big blue halos

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10926]
Latest Chrome on macOS on /develop:

<img width="341" alt="Screenshot 2019-09-20 at 12 04 32" src="https://user-images.githubusercontent.com/4626865/65352214-ed0eda00-db9e-11e9-9ff6-069ae5765dfb.png">
<img width="291" alt="Screenshot 2019-09-20 at 12 04 09" src="https://user-images.githubusercontent.com/4626865/65352216-ed0eda00-db9e-11e9-86f6-5f553fafde81.png">

@BillCarsonFr is reporting blue dotted dashes on Firefox too.

@turt2live related to your accessibility work?

**Comment by turt2live** [comment]
> @turt2live related to your accessibility work?

yes
