### ISSUE TITLE
Doing @room[tab]hello results in @roomhello which doesn't bing the room

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10925]
Using CIDER but unsure if this is also present in the old composer.

**Comment by bwindels** [comment]
Can reproduce indeed:
![roomhello](https://user-images.githubusercontent.com/274386/65411840-6eec4680-dddd-11e9-84ef-ec9a62d45545.gif)

**Comment by bwindels** [comment]
It doesn't happen with Slate (likely because it inserts a space):

![roomhello-slate](https://user-images.githubusercontent.com/274386/65411995-cf7b8380-dddd-11e9-8a33-1e16b5a4e35d.gif)

So a fix would probably to also append a space with CIDER
