### ISSUE TITLE
Empty context menu for downloads

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10922]
When right-clicking on the line that describes an image (e.g. 'Download Eaxmple.jpg'), a, context menu opens with '(empty)' in it.  That looks like a bug.  There could be useful entries in the context menu, such as 'Open', 'Open in ..', and 'Save'.

**Comment by t3chguy** [comment]
This is fixed
![image](https://user-images.githubusercontent.com/2403652/87634820-e78a0e00-c735-11ea-9631-be49e2273066.png)
