### ISSUE TITLE
Mentions don't appear as numbers anymore :(

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10934]
The room list only shows a red "!"
<img width="245" alt="image" src="https://user-images.githubusercontent.com/8582858/65426035-5abd3f00-de07-11e9-83e9-f616323b2d1c.png">

**Comment by bwindels** [comment]
Only in e2e rooms I presume?

**Comment by turt2live** [comment]
This is known for e2e rooms, but I am failing to find the issue that reports it. It usually has something to do with how the counts are done locally, which is not very well executed right now.

**Comment by turt2live** [comment]
I think this is fixed? If not, a new issue or the notifications project will be helpful.
