### ISSUE TITLE
Strange red highlight on - (dash) in a codeblock

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10930]
### Description

When you send a message with \`-\`, the `-` gets highlighted red.

![image](https://user-images.githubusercontent.com/1342360/65379413-6b629d80-dcbf-11e9-9d50-a5d74d14b592.png)

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v71a
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This is automatic language detection doing its thing.
