### ISSUE TITLE
Edited messages appear to not display (on firefox)

### ISSUE THREAD

**Issue by Ekleog** [vector-im/riot-web#10932]
(note: the description is likely wrong, see message below for another reason that looks more reasonable and that we actually managed to reproduce)

### Description

Messages starting with an asterisk followed by an emoji appear to not display (on firefox)

### Steps to reproduce

- Send a message with an asterisk followed by an emoji
- Observe on another account, via riot-web, that the message isn't shown
- Notice that riot-android does display it

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox 68.0.2
- **OS**: NixOS (server), NixOS & Windows (clients)
- **URL**: Private server, v1.2.1

**Comment by Ekleog** [comment]
Actually maybe this is a mischaracterization and is due to edited messages not displaying?

**Comment by t3chguy** [comment]
What does `* 🎧` have to do with editing?

**Comment by Ekleog** [comment]
Things originally triggered only on * followed by an emoji emitted by an iOS device, but it then appeared that these messages were all the result of edits, or so it seems -- which also sounds more likely, esp. given we didn't manage to reproduce without edits.

**Comment by turt2live** [comment]
> Notice that riot-android does display it

riot-android doesn't support edits, which is why you're seeing the messages. Edits are sent as regular messages to try and keep context on them, and smart clients are supposed to collapse them down (like riot-web does).
