### ISSUE TITLE
Read marker regression

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10942]
@anoadragon453 says:

> I'm also seeing the bug , where you join a room with a lot of missed messages, use the "jump to last unread message" arrow to get up (which actually went past the last message I sent?), scroll down a bit, the arrow re-appears (why?) and clicking it again jumps back again but not as far as the last time.
>
> So yeah that behaviour is a bit weird and confusing.

This is biting mozilla.

**Comment by jryans** [comment]
This is tracked actively by https://github.com/vector-im/riot-web/issues/12338, so I don't think we need this one as well.
