### ISSUE TITLE
Truncated rageshake logs & possibly related UISIs

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#10951]
Riot seems to have started truncating rageshake logs at some point, in some cases: symptoms being that the last entry in the rageshake log will be from a day or more ago from when the rageshake was sent. Usually the last line is it logging that it's sending a rageshake which is also absent, so I don't think it's just mismatched clocks.

**Comment by dbkr** [comment]
It looks like this is correlated with the device not being able to decrypt messages in encrypted rooms, and appears to be specific to Firefox. Presumably something something indexeddb.

**Comment by dbkr** [comment]
Apparently it is not just firefox

**Comment by turt2live** [comment]
@dbkr apologies for the late post on this, but is this any different from https://github.com/vector-im/riot-web/issues/5822 ?
