### ISSUE TITLE
Creating a public room with no alias is both invalid and valid

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10964]
See below:
![](https://i.imgur.com/uEXtdl5.png)

**Comment by bwindels** [comment]
Yeah, this might require some refactoring of the validation code to be possible, see the comment on https://github.com/matrix-org/matrix-react-sdk/pull/3464:
> One thing left to do, the server check for the room alias should only happen if the empty check and format check did pass, as the server check shows a message both when the alias is available or not available, which doesn't make sense when the other checks haven't passed. Will do this in a follow-up PR.

Now we have a ticket to track this :)
