### ISSUE TITLE
Disabling read receipts doesn't reclaim the lost margin

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10968]
I suspect this is a dup but i can't find the original.

Lots of complaints from Mozilla that if you disable RRs you don't reclaim the screen real-estate.

This means clobbering https://github.com/matrix-org/matrix-react-sdk/blob/master/res/css/views/rooms/_EventTile.scss#L106 (the 110px margin-right) and also hunt for other 110px constants (i suspect the editor uses one).

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4248
