### ISSUE TITLE
Settings tab buttons have blue halos

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10969]
Latest Chrome on macOS, likely dotted lines on Firefox

**Comment by nadonomy** [comment]
@turt2live related to your accessibility work?

**Comment by jryans** [comment]
Presumably related to @t3chguy's https://github.com/matrix-org/matrix-react-sdk/pull/3475.

**Comment by t3chguy** [comment]
Yup, got a PR which switches them out to AccessibleButtons which doesn't do that
