### ISSUE TITLE
deactivate button has disappeared?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10973]
i thought we had an account deactivate button available to admins from riot now. but i can't find it in the UI

**Comment by turt2live** [comment]
Thisi s because matrix.org is (still) misconfigured - ***please*** expose the API.

**Comment by t3chguy** [comment]
> Thisi s because matrix.org is (still) misconfigured - please expose the API.

Tbh if it was rightly configured it is my understanding everyone will see a Deactivate button that won't work for non-server admins without any visible error. Is there a proper way to detect whether a Synapse user is Server Admin over APIs?

**Comment by turt2live** [comment]
No - https://github.com/matrix-org/synapse/issues/6130

Having the button is much more important imo than running without it.

**Comment by t3chguy** [comment]
> without any visible error

is pretty bad IMO, at least show an error if it fails instead of logging to console would be better
