### ISSUE TITLE
Clicking Jump to first unread message button does nothing

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10975]
### Description

Clicking on the "Jump to first unread message" does nothing, even though there are indeed messages I haven't read.

Video: https://streamable.com/g2soe

Switching away to another room and back doesn't fix it. Refreshing Riot does not fix it.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox nightly v71a
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by jryans** [comment]
@anoadragon453, is this still an issue for you?

**Comment by jaragunde** [comment]
This is still happening to me in a personal server. Sometimes, the "jump to first unread" button does nothing (not always reproducible, though). Versions reported by riot-web:

riot-web version: 1.5.15
olm version: 3.1.3

Browser is Firefox 75.0.

**Comment by jryans** [comment]
I believe I happened to finally realise what's going wrong here: the read marker might be set to an event with no tile (like a reaction), and this breaks some of the assumptions of the "jump to event" code.
