### ISSUE TITLE
keyboard focus ring is visible when keyboard-navigating LeftPanel RoomTiles

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10995]
<img width="332" alt="Screenshot 2019-09-29 at 16 27 07" src="https://user-images.githubusercontent.com/1294269/65834764-3d401780-e2d6-11e9-934b-16b0633de722.png">

**Comment by turt2live** [comment]
this sounds intentional? The focus ring is supposed to be there when using a keyboard.

**Comment by t3chguy** [comment]
Indeed it is

**Comment by t3chguy** [comment]
I guess it conflicts with keyboard navigation on those elements also triggering the hover style

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/14498 for the highlight portion, the ring is definitely intentional
