### ISSUE TITLE
Unreadable misconfiguration error.

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#10996]
![image](https://user-images.githubusercontent.com/14617699/65836645-50fd7500-e2fa-11e9-8a63-1d9795379edc.png)

riot-web version: 1.4.0

**Comment by turt2live** [comment]
What browser and OS information is this?

**Comment by 532910** [comment]
firefox @ debian sid, but it's not due to browser or OS, but due to foreground color (red) is defined without background color (which is gray by default in my case).

**Comment by t3chguy** [comment]
This is now fixed
