### ISSUE TITLE
Allow rooms to have an ephemeral chat history (delete history after X amount of time)

### ISSUE THREAD

**Issue by trosel** [vector-im/riot-web#10991]
### Rationale

Maintaining an eternal log of everything you've ever said has caused many problems for people. Many even [delete their tweets on a rolling basis](https://blog.jumboprivacy.com/five-reasons-to-clean-your-tweets.html).

Room settings should have a `Delete chat history every ___ days` setting. 

Chat rooms _can_ be used as wikis or forums, but _should_ they? In most cases, no.

### Implementation

I know this is difficult because of the federated system of matrix. But what I'm thinking is that when/if a server requests to co-host a room from another server, part of this initial sync will include syncing on the ephemeral history setting and matching up their clocks. Just a thought.

**Comment by trosel** [comment]
Update: The [Room Admin Specified Per Room Retention Proposal](https://github.com/matrix-org/matrix-doc/blob/matthew/msc1763/proposals/1763-configurable-retention-periods.md#room-admin-specified-per-room-retention) is what I'd like to see. **Not** the server admin specified. Or at the least, I'd like to see both.

**Comment by aaronraimist** [comment]
Yep as you saw there is already a proposal for that and a Riot issue here #3800
