### ISSUE TITLE
Collapse user list by default on 1:1 chats

### ISSUE THREAD

**Issue by TheTimeWalker** [vector-im/riot-web#11000]
Right now when you open up a 1:1 (or DM) chat with a person then the user list is always by default open. This doesn't make much sense as it's clear from the context that the only members in this room are the other person and you. So having the member list be open by default makes it look confusing.

I would suggest to have the user list be automatically collapsed so it doesn't feel too much as a room and more like a real 1:1 chat. This could be done in tandem with #8534 to create a better impression and gain some extra chat space.

**Comment by ieure** [comment]
Big +1 for this.

The member list is my biggest annoyance with Riot.  I close it, and sometime later, I'll find that it's been opened up again.  There's no preference to indicate that I prefer to have it closed by default.  And the state is global, not per-room.

**Comment by turt2live** [comment]
We have since made it hidden by default.

**Comment by TheTimeWalker** [comment]
I'm not seeing this change on the latest Nightly
