### ISSUE TITLE
look into automatically applying the dark theme if the user is using a dark system theme

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#11006]
based on https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by aaronraimist** [comment]
I thought there was already an issue for this but I guess it was just this comment https://github.com/vector-im/riot-web/issues/7578#issuecomment-433355898

Basically a dup of https://github.com/vector-im/riot-web/issues/8394 if you just edit it to be more of a generic title

**Comment by aaronraimist** [comment]
Fixed
