### ISSUE TITLE
Allow to login with uppercase or mixed case in username

### ISSUE THREAD

**Issue by enannos** [vector-im/riot-web#11015]
### Description

We are using the matrix-synapse server with the built-in ldap authentication. 
Our problem is that whenever a user tries to login with his username(written in uppercase or mixed), he gets the error "For security, this session has been signed out. Please sign in again." from RIOT.
We used the mxisd during the past and cannot recall facing these kind of problems. But we had to abandon the mxisd for AD-auth because the project is not maintained anymore. 

### Steps to reproduce
User tries to authenticate(AD) using **N**ame.**L**astname (and not name.lastname)

Logs being sent: no

![grafik](https://user-images.githubusercontent.com/8511600/65969702-8a062880-e465-11e9-9bd1-0dac697a9715.png)

### Version information

- **Platform**: web (in-browser) or desktop? Both

For the desktop app:

- **OS**: Windows
- **Version**: 1.4.0

**Comment by turt2live** [comment]
When this error happens, please open the console (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd>) and type `mxSendRageshake("For https://github.com/vector-im/riot-web/issues/11015")` so we can see what is going wrong here.

**Comment by enannos** [comment]
Hello @turt2live, here are the errors from the console.

```
Getting push rules failed 
Object { errcode: "M_UNKNOWN_TOKEN", name: "M_UNKNOWN_TOKEN", message: "Unrecognised access token", data: {…}, httpStatus: 401, stack: "" }
rageshake.js:107
    r rageshake.js:107
    e sync.js:541
    E runtime.js:62
    _invoke runtime.js:296
    t runtime.js:114
    c bluebird.js:5290
    _promiseRejected bluebird.js:2157
    _settlePromise bluebird.js:3366
    _settlePromise0 bluebird.js:3404
    _settlePromises bluebird.js:3480
    p bluebird.js:190
    f bluebird.js:183
    _drainQueues bluebird.js:199
    drainQueues bluebird.js:69
```

**Comment by turt2live** [comment]
That's a server-side error saying the token is invalid. Riot can't do anything but log you out in this case.

Double check your setup and server config, and visit #synapse:matrix.org for additional troubleshooting.
