### ISSUE TITLE
Invalid command prompt is confusing (CIDER)

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11019]
### Description

Putting an invalid command in CIDER (and possibly the old composer?) shows the following dialog:

![image](https://user-images.githubusercontent.com/1342360/65981866-e707db80-e471-11e9-92a0-f9a56c565f43.png)

Which is different from the usual "Invalid command" error I was expecting. It looks like my server is failing instead.

Describe how what happens differs from what you expected.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox nightly v71a
- **OS**: Debian buster
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Is this fixed on /develop for you now?
<img width="781" alt="Screen Shot 2020-01-23 at 3 45 33 PM" src="https://user-images.githubusercontent.com/5855073/73026662-735e5580-3df7-11ea-9ad2-13db43adc57d.png">

**Comment by anoadragon453** [comment]
Indeed, thank you!
