### ISSUE TITLE
Explain what "mxc_url" is in /avatar commands

### ISSUE THREAD

**Issue by trosel** [vector-im/riot-web#11016]
![image](https://user-images.githubusercontent.com/1299322/65974030-40541880-e43a-11e9-9005-ae05180eed22.png)

I'm trying to figure out how to customize my room avatar. But I don't know what an `mxc_url` is. Is it a filepath from my own machine to the image I want to use? Is it a URL of an image that I've somehow uploaded to a matrix server?

**Comment by t3chguy** [comment]
> Is it a URL of an image that I've somehow uploaded to a matrix server?

Exactly that, but if you omit it (it is optional given the `[]`) it'll give you an upload file dialog

**Comment by trosel** [comment]
@t3chguy Can a user even see a list of all the files they've uploaded to their home server?

Ah, I see. And when I send junk text, it just erases my avatar (helpful actually).

**Comment by t3chguy** [comment]
No but they can send a file to a room then view source on that message to see its msc

**Comment by turt2live** [comment]
(or start a conversation with something like `@mediabot:t2bot.io` and it'll spit out the MXC URI for you)

**Comment by trosel** [comment]
I think there is ongoing discussion about adding this to the UI in the room settings. But this is helpful, thank you!

**Comment by shsorbom** [comment]
How does one return it to the default global avatar?

**Comment by Biep** [comment]
> How does one return it to the default global avatar?

I *believe* resetting the global avatar to itself will delete all local avatars.  I am not going to try, because it would take a lot of work to get all the local ones set up again.
