### ISSUE TITLE
powerlevel as int in a string confuses riot

### ISSUE THREAD

**Issue by airblag** [vector-im/riot-web#11012]
### Description

While giving power to other users in a room (direct through the api, or with riot dev tools), you can set the powerlevel to "N" instead of N.

It brings to some strange behaviours, at least in Riot.
In my case, an admin with powerlevel set to "100" instead of 100 is shown as admin, but cannot edit any settings in riot. 

Actually, I'm not sure, it this should be forbidden from the server side (and it's then a synapse bug), or if riot should understand/convert it internally (now it's more a riot bug). 

### Steps to reproduce

- create a room
- make a user join this room
- /devtools
- explore room state -> m.room.power_levels

you get something like 

<code>
"users": {
 "@myuser:myserver.org": 100
}
</code>

- edit it like this and click send
"users": {
 "@myuser:myserver.org": 100,
 "@myuser2:myserver.org": "100"
}

- it's accepted and now you have power levels once with quotes, and once without.
- riot is saying "@myuser:myserver.org" changed the  power level of @myuser2:myserver.org from Default(0) to Admin (100)
- @myuser2:myserver.org is not allowed to do anything in riot through the menus. However, the commands with / are working 

It looks strange to have this mixed json with quoted or not quoted integers, and i first thought it should be forbidden to quote them to avoid this kind of behaviour.

But it looks it's clear in the spec :
https://github.com/matrix-org/matrix-doc/blob/master/specification/rooms/v1.rst

> If type is m.room.power_levels:
> 
>     If users key in content is not a dictionary with keys that are valid user IDs with values that are integers (or a string that is an integer), reject.

So maybe it's only a riot bug. I'll let you decide :)

### Version information

- **Homeserver**:
self hosted.

- **Version**:
matrix-synapse-py3 1.3.1+stretch1
riot 1.4.0 (but the problem exists since a while)

- **Install method**:
apt with matrix.org repositories

**Comment by t3chguy** [comment]
The spec says it must be an integer, so this is an issue with Synapse. https://matrix.org/docs/spec/client_server/r0.5.0#m-room-power-levels

**Comment by airblag** [comment]
I actually started to write this bug report on the synapse repository, but reading again this, I'm still not sure if the spec is not saying 2 different things at 2 different places...

What does mean "a string that is an integer" in the specfs of the room v1 I mentioned before ?
I would interpret it as "42" is a string which can be converted to an integer (42).

And it seems, that riot is also understanding a powerlevel as a string that is an integer like "100", when you do things like /op someone else, it works.
Only the context menus are greyed out for making administrative task, so somehow riot is not interpretting it the same way in different places, so I think it might also be a bug of riot.
