### ISSUE TITLE
Feature Request: UI

### ISSUE THREAD

**Issue by barkingbandicoot** [vector-im/riot-web#11027]
**Is your suggestion related to a problem? Please describe.**

**Describe the solution you'd like**
Mimimalise the UI and demarcate speech

**Describe alternatives you've considered**
1. Add speech balloons or some sort of demarcation for different communicators.
Have image icons for users on opposite sides.
2. Collapse the 'Communities' and 'Bug Report' buttons into the the next column.
3. Add option for background art.

Thanks!!

**Comment by t3chguy** [comment]
1 is https://github.com/vector-im/riot-web/issues/4635
2, you're just not using the Communities Bar so its empty for you: 
![image](https://user-images.githubusercontent.com/2403652/66114980-d2d5f280-e5c7-11e9-8cbc-0827a7c6ac06.png) but you *CAN* disable it: 
![image](https://user-images.githubusercontent.com/2403652/66115006-df5a4b00-e5c7-11e9-99f3-7652431d37e9.png)
3. Please make a new issue for this.

**Comment by barkingbandicoot** [comment]
Oh, fantastic! It is so customisable I missed that setting!
Thanks!
Why closed though? I also did request:
Add speech balloons or some sort of demarcation for different communicators.
Have image icons for users on opposite sides.

Thanks!

**Comment by t3chguy** [comment]
That which you request is a duplicate of #4635 as I stated above

**Comment by barkingbandicoot** [comment]
> That which you request is a duplicate of #4635 as I stated above

Ugh! Yes, you did state. My apologies, It is the end of the day in my part of the world. Tired eyes!
Thanks.
