### ISSUE TITLE
System alerts room can pop out of its tag

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11025]
Clicking around enough in the room list will cause it to jump out into Rooms

**Comment by turt2live** [comment]
dev note: this is almost certainly because the room list algo stuff counts the tag as invalid because tag support isn't enabled. It probably just needs to treat it as okay even without tag support.

**Comment by neilisfragile** [comment]
Note: One implication of this issue is that it breaks the server resource limit reached banner. Once triggered the banner will no longer by synced with reality. 

Though a client refresh reverts channel and effectively fixes the problem.

**Comment by turt2live** [comment]
Not anymore in the new room list. It's been tested for the last month and hasn't popped out once.
