### ISSUE TITLE
Backspace when text field has no focus removes the entire page contents

### ISSUE THREAD

**Issue by surakin** [vector-im/riot-web#11036]
### Description

Backspace when text field has no focus removes the entire page contents

### Steps to reproduce

- Click outside the text entry field
- Press backspace.
- Everything is gone, you have to reload the page or restart the desktop client.

### Version information

- **Platform**: web (in-browser) AND desktop

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.4.0

**Comment by Biep** [comment]
Still the case in 1.4.1.

**Comment by turt2live** [comment]
I swear we had an issue for this already, but this is likely the backspace key triggering browser navigation and Riot having a bad day.

**Comment by aaronraimist** [comment]
In Safari it doesn't remove the page contents but it (permanently?) breaks the composer in the room where you try it. Refreshing the page or clear cache doesn't seem to fix it.

**Comment by t3chguy** [comment]
Travis, it is not, the console says something about unable to remove node talking about composer

**Comment by turt2live** [comment]
@t3chguy We do have a history of bugs relating to browser navigation and causing things to break. Would be good to get some logs from someone though so that error you speak of is recorded somewhere.

**Comment by t3chguy** [comment]
@turt2live here ya go:

![image](https://user-images.githubusercontent.com/2403652/66157065-e3638880-e61a-11e9-82ee-a91d49ac4ee8.png)

**Comment by turt2live** [comment]
yup, something broke it to cause it to explode in anger :|

see https://github.com/vector-im/riot-web/issues/11045

**Comment by t3chguy** [comment]
More deets:
![image](https://user-images.githubusercontent.com/2403652/66159166-566efe00-e61f-11e9-8350-79360afd32aa.png)

**Comment by t3chguy** [comment]
Cannot repro with CIDER
