### ISSUE TITLE
UI for adding an email address is confusing

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11039]
### Description

It is confusing that there are more steps to do after I click the link in the email and see the page saying my email has been validated. At that point I assumed that the process was done, and when it wasn't working, I assumed the process was broken, not that I had missed clicking a button.

### Steps to reproduce

- Add email address to account
- Receive email from homeserver
- Click link in the email to verify email address
- See page saying my email has been validated (process should be done here if possible, otherwise made more clear that there are more steps)
- Go back to Riot, click Continue button (and get issue #11040)

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Safari 13.0.1
- **OS**: macOS
- **URL**: riot.raim.ist running 1.4.2rc1

**Comment by aaronraimist** [comment]
This is probably just a dup of  #1481

**Comment by aaronraimist** [comment]
![Screen Shot 2019-10-03 at 11 46 44 AM](https://user-images.githubusercontent.com/5855073/66146996-7ed10b00-e5d3-11e9-8c59-4aa0f3cd02e3.png)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/13897
