### ISSUE TITLE
Consider removing/replacing the sticker picker when the user changes their integration manager

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11030]
Unless you're a user who is intimately aware of how widgets and integration managers interact, you're going to assume that the sticker picker and integration manager are related. In fact, the integration manager adds the widget to your account but after that it's entirely possible to use a different integration manager from your sticker picker. 

Most people expect that when you change your integration manager it also changes your sticker picker (the few that don't know about devtools and can fix it themselves). We should just reinforce that idea rather than keep punishing the user for not knowing better.

Removing the sticker picker when the integration manager is changed is easiest, and probably fine enough for most people. The user would fall into an awkward flow to re-add their sticker picker, but at least it'd be with the right manager. This also avoids the lack of "make me a widget" API that replacing would need.

Replacing the sticker picker would be the best bet, though Riot has no way of knowing what the integration manager wants its widget to look like. In future there will be a MSC to expose a "make me a widget of X type" API on integration managers for cases exactly like this. Common cases are Jitsi widgets (the URL structure is largely unknown to the client) and sticker pickers (if we go the replace route).

Instead of automatically doing all this, we could also add a toggle for "also replace/remove my sticker picker" below the change manager form. This is only useful if we expect people to want to keep their existing manager (they probably don't).

**Comment by turt2live** [comment]
for now we'll just remove the sticker picker on change.

**Comment by lampholder** [comment]
We're not letting the user change their integration manager now (supporting it served to demonstrate how many assumptions were made about its _not_ changing - this issue is an example).

So I'm going to close this, making the judgement call that the utility of leaving it open is less than the noise generated.
