### ISSUE TITLE
1.4.1 blank screen

### ISSUE THREAD

**Issue by rev138** [vector-im/riot-web#11034]
### Description

I am experiencing the problem described in #10983 using 1.4.1

- **Browser**: Firefox 68
- **OS**: Fedora
- **URL**: https://matrix.gibberfish.org/

![image](https://user-images.githubusercontent.com/1538633/66068857-e2a8f480-e53d-11e9-888c-d2bba164de36.png)

**Comment by turt2live** [comment]
matrix.gibberfish.org reports using 1.3.5, not 1.4.1 - are you sure this is with 1.4.1?

**Comment by rev138** [comment]
Yes. I switched back because it's broken.

**Comment by turt2live** [comment]
Have you self-compiled Riot or are you using a downloaded release? The error you're getting should only be present if the thing was compiled itself without the required attention (this release is a bit weird).

**Comment by rev138** [comment]
Self compiled. Did I miss something?

**Comment by rev138** [comment]
Ok, I did this:
```
rm -rf node_modules/*
yarn install
```
This complained it couldn't find "rimraf", so:

```
npm i rimraf
yarn install
yarn dist
```
This created `dist/riot-v1.4.1-dirty.tar.gz`, which when unpacked still gives a blank screen.

**Comment by turt2live** [comment]
Is the error fixed? The error in your original post is a dependency error and so should be fixed using the instructions. 

Using npm probably didn't help - try `yarn add rimraf` instead.

**Comment by turt2live** [comment]
Also the cache clean is important.

**Comment by rev138** [comment]
Sorry, yes. I did the clean. Using npm got me past the rimraf error. I'm not sure what to do next.

**Comment by turt2live** [comment]
Repeat the steps, but use the yarn command I mentioned instead of the npm command. 

That could be one of the reasons the tarball is dirty.

We also publish signed tarballs at https://github.com/vector-im/riot-web/releases for every release, if you want to avoid compiling yourself.

**Comment by rev138** [comment]
The official tarball worked. I'll just stick to those in the future. Thanks!
