### ISSUE TITLE
Weird errors since React 16 introduction

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11045]
There's a bunch of soft crashes (grey/white/black screens depending on theme) due to seemingly random causes. The errors received after the crash are likely due to lack of error boundaries (prior to when we introduced them earlier today, as of posting).

The current "weird" errors are:
* https://github.com/vector-im/riot-web/issues/11036 - Backspace causes app unmount
* https://github.com/vector-im/riot-web/issues/10997 - Joining a room through a community causes an unmount
* https://github.com/vector-im/riot-web/issues/11032 - NPE when using permalinkPrefix (has same error as 10997 now)

The introduction of an error boundary should help identify what is going wrong in the app, as the cases above are almost certainly red herrings. Somewhere we have an error that can be triggered by something related to the cases above (or possibly an async thing), and that is causing the app to crash in weird ways.

Labelling as critical because it seems to be affecting everyone one way or another - feel free to demote if this isn't a good use of the classification.

**Comment by turt2live** [comment]
Also the rageshakes appear to missing the actual error that happened: https://github.com/matrix-org/riot-web-rageshakes/issues/1799#issuecomment-538101893

**Comment by tuxayo** [comment]
I can't load anymore Riot web since this issue. Will provide privately a memory dump (because I already had to for another issue)

**Comment by jryans** [comment]
@turt2live Is this issue useful now that we an error boundary? I think we should probably track each soft crash separately so it can be fixed as need. (I have added a new issue label `react-soft-crash` that we can use to group them.)

**Comment by jryans** [comment]
Removed this from Workflow board as the individual issues should be tracked.

**Comment by turt2live** [comment]
Yea, let's track the individual errors and monitor that way. This was meant to be converted into a list of soft failures, but a label is better.
