### ISSUE TITLE
Please remove "new version" notification.

### ISSUE THREAD

**Issue by kevincox** [vector-im/riot-web#11042]
### Description

Occasionally I get an undismissable banner at the top of the Riot website telling me to refresh to get the new version.

I don't really need the new version that badly, I restart my browser every week or two and I will happily wait that long. Either refresh the page for me or don't bother me.

### Version information

- **Platform**: web (in-browser)

**Comment by bytesandnibbles** [comment]
I actually like that feature... And it seems pretty common in modern web-apps. Perhaps there could be a setting for this?

**Comment by kevincox** [comment]
A setting us a reasonable compromise. Also have a close option on the bar is good.

**Comment by t3chguy** [comment]
IMO would be nicer as less intrusive, maybe a notification bell on the top left menu or something

**Comment by jryans** [comment]
@lampholder, maybe we should by thinking about what we want from a product perspective here?

**Comment by kevincox** [comment]
Maybe I'm too cynical but the new version is likely to have just as many bugs as the previous version fixed. In fact with this argument it is better to have a slow rollout of the new version so that if serious issues occur you can roll back.

You can also focus this to just reporting errors. When the user opens the error reporting dialog then you can do the check, and suggest that the user tries to reproduce the problem on the newest version if they aren't up-to-date.

I think there are ways to balance the requirement for users updating with the bother of users manually doing so. For example only show the dialog if the version is significantly old or has major known issues.

In my opinion the user shouldn't really compare about the version they are running, they should just keep using it and slowly notice new features appear.

**Comment by kevincox** [comment]
Because it is annoying to do this regularly. Bothering your users into doing something doesn't seem like the best approach. How I see it is that this feature is purposely taking up my screen space to get me to do something.

1. If you want me to do it bad enough, just refresh the page yourself.
2. If it isn't that important (this is my opinion) just remove the popup.

In other words I'm bothered because someone went out of their way to bother me. I understand that wasn't the intention however I hope you can understand that I don't like having to do extra work, especially when it is trivial.

**Comment by turt2live** [comment]
just to be clear: is this on riot.im/app or /develop?

**Comment by kevincox** [comment]
https://riot.im/app/

**Comment by t3chguy** [comment]
I personally like the way Discord does it, a smaller but noticeable highlighted green icon on the top right panel

**Comment by t3chguy** [comment]
This will become a Toast which is deferrable.

**Comment by gdvine** [comment]
Simply adding a close button would solve the issue.

**Comment by t3chguy** [comment]
It has landed as a toast now, but it should be deferrable as toasts are much more interaction blocking
