### ISSUE TITLE
Unable to verify email address error

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11040]
### Description

After getting #11039 and clicking the Continue button I get an error dialog

### Unable to verify email address.
null is not an object (evaluating 's.default.get().idBaseUrl.split')

![Screen Shot 2019-10-02 at 11 43 32 PM](https://user-images.githubusercontent.com/5855073/66099931-7397c400-e56e-11e9-980c-bca42665ca32.png)

This seems to be the same error you get if you don't click the link in the email at all and just immediately click continue. So there is probably a Synapse issue going on where it is not realizing I clicked the link to validate my email address, but still that error message is ugly.

### Steps to reproduce

- Disconnect from your identity server
- Add email address to your account
- Receive email from homeserver
- Click link in the email to verify email address
- See page saying my email has been validated
- Go back to Riot and click the Continue button

Logs being sent: no

```
[Error] Unable to verify email address: TypeError: null is not an object (evaluating 's.default.get().idBaseUrl.split')
	error
	(anonymous function) (bundle.js:40:95961)
	(anonymous function) (bundle.js:118:207639)
	c (bundle.js:1:81425)
	(anonymous function) (bundle.js:1:54591)
	(anonymous function) (bundle.js:1:55412)
	(anonymous function) (bundle.js:1:56100)
	(anonymous function) (bundle.js:1:57342)
	p (bundle.js:1:9543)
	f (bundle.js:1:9468)
	(anonymous function) (bundle.js:1:10988)
	(anonymous function) (bundle.js:1:9221)
	promiseReactionJob
```

### Version information

- **Platform**: web

For the web app:

- **Browser**: Safari 13.0.1
- **OS**: macOS
- **URL**: riot.raim.ist running 1.4.2rc1

**Comment by lampholder** [comment]
I have a note written hastily from the end of Friday's standup saying "test 11040". Well, I've tested on lant.uk and matrix.org, but haven't been able to reproduce the issue now.

**Comment by aaronraimist** [comment]
@lampholder Oh whoops I guess I didn't specify in this issue that you need to not be connected to an identity server.

**Comment by aaronraimist** [comment]
Verified fixed! Thanks. I'm surprised this wasn't caught in testing before release.

**Comment by jryans** [comment]
I am also a bit puzzled, as I swear we tested that case... anyway, it's fixed now. 😄
