### ISSUE TITLE
Improve visualization of deleted messages

### ISSUE THREAD

**Issue by IndeedNotJames** [vector-im/riot-web#11056]
Currently, deleted messages are visualized with a rather meaningless bar:

![riot-web-deleted-msg](https://user-images.githubusercontent.com/55066419/66216939-b10f6500-e6c6-11e9-81a6-50e936f34074.png)

While there is this nice tooltip when hovering above, it isn't really intuitive.
I thought about two ways:
- explanation what this is when a new user sees it the first time
_or_
- replace the bar with an actual text like pattle.im does:

![pattle_deleted_msg](https://user-images.githubusercontent.com/55066419/66219662-dd79b000-e6cb-11e9-83d9-83d7db74fda1.jpg)

**Comment by yannicka** [comment]
Here's what it looks like on Riot Web/Desktop 1.6.2:

![image](https://user-images.githubusercontent.com/22885898/82729741-49139a80-9cfa-11ea-9d18-8092027fe8e8.png)

**Comment by t3chguy** [comment]
Ah yes, this had a duplicate issue which I closed but didn't know about this one

**Comment by IndeedNotJames** [comment]
Awesome :+1: 
Good job :rocket:
