### ISSUE TITLE
Riot-Web is unable to log-in to custom homeserver using federation port

### ISSUE THREAD

**Issue by sammorley** [vector-im/riot-web#11058]
Riot-Web is unable to log-in to a custom homeserver when an alternate port number (such as 8448) is entered into the custom server field of the login screen.  Riot is able to establish an initial connection to the homeserver and then prompts for a username and password but when these credentials are submitted Riot displays an unable to connect error and continues unsuccessfully to connect indefinitely. Riot does connect normally once a rerverse proxy is set up regardless of what port value is entered into the custom homeserver field.

### Steps to reproduce

Disable reverse proxying on a custom homeserver and attempt to log in over the federation port with a vailid user account from Riot-web

Log: 

in the console logs their is a 'Getting push rules failed' message.  The URI in that message shows that the port number is not getting appended to the domain name when a request is being sent to the server and the connection is thus getting refused.  For example:

message: "CORS request rejected: https://synapse.gq/_matrix/client/r0/pushrules/"

![Screenshot-2019-10-4 Riot  Offline](https://user-images.githubusercontent.com/18384191/66229780-7215eb00-e697-11e9-9b3c-a0a2e429fbde.png)

### Version information

- **Platform**: This occurs on Riot-Web v 1.4.2

For the web app:

- **Browser**: Chromium 76.0.3809.100 and Firefox-esr v 60.9.0
- **OS**: Debian 10.1
- **URL**: riot.im/develop, riot.im/app, riot.t2host.io

I did not attempt to log in from desktop app

**Comment by turt2live** [comment]
Just to double check: your `public_baseurl` setting in Synapse's `homeserver.yaml` is pointing to the same thing you entered into the custom server box?

**Comment by turt2live** [comment]
I am assuming this is either fixed or no longer relevant. Please visit #riot-web:matrix.org to troubleshoot or #synapse:matrix.org if it looks to be a server issue.
