### ISSUE TITLE
Use a different loading animation

### ISSUE THREAD

**Issue by pbbob** [vector-im/riot-web#11067]
The loader/spinner that is used in many places on riot is actually just an animated gif. This is not a good solution, because it is low resolution, and it is really noticeable especially on high-dpi monitors.
It would be much better to use an SVG animation, or even a CSS animation.
[this site](https://loading.io/) has a bunch of (CC0 licensed) customizable loader animations. They can be exported as either CSS animations or SVG animations, both of which will render much better on highres displays.

It is also even more noticeable with the dark theme:
![image](https://user-images.githubusercontent.com/34972102/66278055-af36d480-e873-11e9-88db-76a8bf31d9c2.png)

**Comment by pbbob** [comment]
Also, the advantage of using a CSS spinner would be that the dark theme could use different colors for the spinner.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/6740
