### ISSUE TITLE
Screen not loading in Riot Desktop

### ISSUE THREAD

**Issue by ackxolotl** [vector-im/riot-web#11063]
### Description

Riot Desktop stopped loading when starting the application. The progress wheel disappeared but everything stayed grey: No rooms or any other GUI elements appeared.

### Steps to reproduce

- Start Riot Desktop

I expected to see all GUI elements as usual and not an empty, grey screen.

Log: sent

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.4.2

**Comment by bwindels** [comment]
Sounds related to https://github.com/vector-im/riot-web/issues/11045

**Comment by dbkr** [comment]
This one is being triggered by a bug in the slate code, specifically https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/MessageComposerInput.js#L194 (where somehow `children` is null - empty code blocks, presumably).

If we don't kill slate by the next release, we should put a null-guard in here.

**Comment by jryans** [comment]
We're going to fix for release users this by shipping CIDER in stable Riot in the next few days.

Since CIDER is already enabled on develop, it think we can consider this issue fixed (since merged to develop is our usual dividing line).
