### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by taokann** [vector-im/riot-web#11065]
### Description

I can't upload any file, there is a quite mysterious error message showing up.

### Steps to reproduce

- Login into riot web
- enter a chatroom
- try sending a file with the paperclip icon
- confirm that you want to upload the file
- watch the file being uploaded
- see the error message

Logs being sent: yes

![Screenshot_20191006_155858](https://user-images.githubusercontent.com/38343089/66270346-91a54300-e852-11e9-936c-94e8fc74ac94.png)
![Screenshot_20191006_155909](https://user-images.githubusercontent.com/38343089/66270347-923dd980-e852-11e9-92bf-6eb078f13dee.png)

(sorry it's in french)

### Version information

- **Platform**: web

- **Browser**: Firefox 69.0.1 (64 bits)
- **OS**: Ubuntu 19.04
- **URL**: https://mtx.gnous.eu (private server)

Versions
matrix-react-sdk : <local>
riot-web : 1.0.8
olm : 3.0.0

**Comment by t3chguy** [comment]
Check error on your private synapse server's log

**Comment by jryans** [comment]
Riot 1.0.8 is very old... Please update to the latest version, which is known to fix issues like this.

**Comment by jryans** [comment]
Please file a new issue after testing modern versions if you still see this.
