### ISSUE TITLE
HTTP 403 on stickers

### ISSUE THREAD

**Issue by taokann** [vector-im/riot-web#11064]
### Description

I can't use the emoji panel, i get an HTTP 403 error

### Steps to reproduce

- Login in riot web
- go to a chat
- click the emoji icon in the bottom right
- optional : click on the "pen-paper" icon in the panel to experience a second time the same error.

I expected the emoji panel to show the emojis

Logs being sent: yes

![Screenshot_20191006_153938](https://user-images.githubusercontent.com/38343089/66270231-36268580-e851-11e9-8a64-e10c67c82d97.png)

![Screenshot_20191006_154009](https://user-images.githubusercontent.com/38343089/66270233-37f04900-e851-11e9-971e-753758e793bb.png)

### Version information

- **Platform**: web

- **Browser**: Firefox 69.0.1 (64 bits)
- **OS**: Ubuntu 19.04
- **URL**: https://mtx.gnous.eu (private server)

Versions
matrix-react-sdk : <local>
riot-web : 1.0.8
 olm : 3.0.0

**Comment by jryans** [comment]
Have you changed your integration manager in Settings? What is it currently set to?

**Comment by jryans** [comment]
Please file a new issue with more detail if this comes back.
