### ISSUE TITLE
Tag rageshakes via React soft crash / error boundary to indicate the app was broken

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11072]
For rageshakes submitted via the React error boundary, we should tag these somehow in rageshake metadata to indicate the priority.

**Comment by turt2live** [comment]
ftr, the rageshake server does support labels (the mobile apps use this). We could also go with old school prefixes on the message: `[WSOD] User message here`

**Comment by jryans** [comment]
I guess WSOD is a bad name, since the colour depends on theme... Will use "soft crash" term as with https://github.com/vector-im/riot-web/issues/11045.
