### ISSUE TITLE
Emoji picker UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1107]

**Comment by ara4n** [comment]
Once upon a time a suggested design wireframe for this was:

<img width="987" alt="screen shot 2016-03-10 at 16 25 04" src="https://cloud.githubusercontent.com/assets/1294269/13676194/bfc89b2c-e6dc-11e5-998e-5287e0e986ca.png">

**Comment by AndrewJDR** [comment]
Much preferred over the text-based search method for emoji as it stands!

**Comment by superdump** [comment]
:+1: or in general, I feel that GitHub do a pretty good job with emoji UX-wise.

**Comment by joelostblom** [comment]
This would be a very helpful addition!
I was having troubles writing emojis initially, as autocomplete didn't work until I enable the experimental Rich Text Editor. Now I can get emojis for `:smile:` etc, but I still can't autocomplete emojis on `:)` and similar. An emoji selection UI would make this much more straightforward and the design suggestion above looks great!

**Comment by lukebarnard1** [comment]
@lukebarnard1 wonders if we're going to change the current emoji picker to look more like this

**Comment by MurzNN** [comment]
We can add button to select smiley in bold-italic-quote panel.

**Comment by MurzNN** [comment]
Good implementation of Emoji picker we can see in VK.com (Vkontakte):
![](http://i.imgur.com/qWaE9cn.jpg)
and Telegram:
![](http://i.imgur.com/u060I0C.jpg)

**Comment by MurzNN** [comment]
Here is React implementation of Slack Emoji picker: https://slack.engineering/rebuilding-slacks-emoji-picker-in-react-bfbd8ce6fbfe?gi=37f3b106bb90 - maybe we can reuse it in Riot?
![img](https://cdn-images-1.medium.com/max/1600/1*-9whH4kAysq6wVZaUQUc8Q.png)

**Comment by MurzNN** [comment]
And here is another React implementations of Emoji picker:
https://github.com/tommoor/emojione-picker
https://github.com/missive/emoji-mart
https://github.com/ealush/emoji-picker
https://github.com/conorhastings/react-emoji-react

**Comment by floviolleau** [comment]
Hi, I like links from @MurzNN.

Can s.o. have time to implement it?

KR

**Comment by pafcu** [comment]
As a data-point, Mastodon has switched to using emoji-mart

**Comment by Hoeze** [comment]
Are there any updates on this?

**Comment by MightyCreak** [comment]
There is a pretty important bug in the latest 1.0.x releases: we don't see which smiley is currently selected any more. So we just need to hit tab until we get the right one.

**Comment by eMPee584** [comment]
emoji-mart still seems to be well maintained and thus a good candidate for integration:
https://github.com/missive/emoji-mart/graphs/contributors

**Comment by aleex5** [comment]
this feature is necessary, it will give more life to the application

**Comment by MurzNN** [comment]
Riot moved to Emojione, so here [Emoji Picker](https://github.com/tommoor/emojione-picker) is good react emoji picker integrated with Emojione.

**Comment by lalomartins** [comment]
@MurzNN you're a little late 😅 Riot just moved *away from* Emojione

**Comment by eMPee584** [comment]
> emoji-mart still seems to be well maintained and thus a good candidate for integration:

… Is it not?
having the sticker function sit behind that smiley face and no picker still is really somewhat confusing..

**Comment by juliusv** [comment]
I do have to agree, it's hard to sell a chat app (on the web) to people if it doesn't have an emoji picker. The current smiley face not leading to an emoji keyboard (but to some unwanted sticker store) was confusing for me as well.

**Comment by Ezwen** [comment]
Quick question: is it planned to also use the fancy new reaction emoji picker for writing emojis in the message composer? Would be really neat :)

**Comment by turt2live** [comment]
it's been requested a lot, and I don't think anyone is opposed to it. Best to keep the discussion on https://github.com/vector-im/riot-web/issues/9484

**Comment by Ezwen** [comment]
Thanks for the link! sorry I did not find the other issue with my first search

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/9484#issuecomment-489096947 sets out the overarching plan

**Comment by Letterus** [comment]
Just want to push this issue. Current UI/UX is not consistent and confusing. Several of our users reported that.

**Comment by Hoeze** [comment]
Can we just have something working? It does not need to be pretty, things can always be improved.

This (seemingly simple/essential) functionality is discussed for four (!) years now :laughing:

**Comment by fti7** [comment]
With the current speed we can expect something for Christmas :-)

**Comment by t3chguy** [comment]
Designs are almost ready actually.

**Comment by nadonomy** [comment]
@t3chguy just to unblock this specific issue, we can lift the icons from the new Composer work in Figma (which still has some validation left to do):

https://www.figma.com/file/WM63nhWpzWUrVhEYgFRUpt/Composer?node-id=8%3A680
