### ISSUE TITLE
"Voice call" button in group chats doesn't make full use of Integration Manager settings

### ISSUE THREAD

**Issue by mrjohnson22** [vector-im/riot-web#11074]
### Description

After having chosen a custom Integration Manager, Jitsi widgets created by the "Voice call" button in group chats may not use the correct Jitsi URL. This leads the Jitsi widget to not load.

### Steps to reproduce

- Log on to either riot.im/app, or a Riot/Web that uses the default `integrations_` URLs in its config.json
- Set a custom Integration Manager (a Dimension domain is recommended)
- Enter/join a group chat and get permissions to add/edit widgets
- Click the "Voice call" button

Result: A Jitsi widget appears, but it remains blank.

In contrast, Jitsi widgets created through the Integration Manager menu (the four-squares icon) work as expected.

Also, if config.json's `integration_` URLs point to that of a custom Integration Mamager (in the case of Dimension, the URLs listed on its homepage), the problem goes away.

What appears to be the problem is the widget URL used by Riot when clicking on the "Voice call" button. The URL used is the following (non-working case):

`https://<integration_manager_domain>/api/v1/scalar/widgets/jitsi.html`

In contrast, after having edited config.json or using the Integration Manager menu, a Jitsi widget has the following URL (at least in the case of Dimension) (working case):

`https://<integration_manager_domain>/widgets/jitsi`

Also, only the latter case includes query parameters from the v2 Widget API, notably `domain`, in the widget URL. If possible, it should always be used, so that clients which load a Jitsi view directly (instead of a page with a button that redirects to a Jitsi page) can refer to the `domain` parameter to connect to Jitsi calls hosted at a non-default domain.

### Version information

- **Platform**: web
- **Browser**: Firefox 69.0.2
- **OS**: Fedora 30
- **URL**: riot.im/app / private server
- **Riot/Web version** v1.4.2

EDIT: the query parameter I meant was `domain`, not `hostname`.

**Comment by turt2live** [comment]
This is fixed by a "make me a widget" API that we don't currently have. The current solution of a config option is not sustainable.

Note that Dimension also uses jitsi.riot.im by default - if this isn't okay with you, set your own Jitsi server and enable the force flag (which introduces some compatibility problems on mobile) to enforce usage of it on riot-web.

Related:
* https://github.com/vector-im/riot-web/issues/5048
* https://github.com/vector-im/riot-web/issues/6930

**Comment by turt2live** [comment]
We're depriotizing this for now because it's missing a prerequisite. We can't really fix it from a Riot perspective at the moment and would need the "make a widget" API. This API is somewhere in the pipeline of things to happen, and this issue is one of the leading reasons for it existing.

**Comment by perkooo** [comment]
This issue is also really blocking for me as I can't configure our integration manager (Dimension) self-hosted.
Even if I configure the default jitsi.riot.im, the voice/conf call button does not work on Applications (only on riot-web). A blank page in the widget appears.

**Comment by turt2live** [comment]
Change the jitsi conference URL in your config.json - visiting Dimension in a web browser will give you instructions on what to do.

**Comment by perkooo** [comment]
I already did this, it worked perfectly on riot-web (with default jitsi.riot.im or my jitsi server) where I can see the new URL.
But it does not work on client applications (like for Ubuntu, Windows or Android), the button "Call" with multiple users is still giving me a blank page in the widget (calling another external URL).

**Comment by turt2live** [comment]
There's also a desktop config file you can change. Other than that, this is stuck in the state described just a few comments earlier: https://github.com/vector-im/riot-web/issues/11074#issuecomment-539460494
