### ISSUE TITLE
Getting logged out doesn't stop async code from running

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11087]
It's possible to cause so many errors while things are loading that the app just crashes instead of logging out. 

This typically happens when the server returns M_UNRECOGNISED_TOKEN on startup.

Flagging as a react-soft-crash because we've seen an uptick in reports of these on 1.4.2 - possibly caught by the error boundary?

**Comment by jryans** [comment]
I think this should also be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3533. Let's reopen / refile if we continue to see reports like this after the next release.
