### ISSUE TITLE
Leaving a room can leave a stale room UI hanging around

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1109]
from atig on #vector:matrix.org

So vector has some bug in creating rooms
To reproduce
- Click start couple of rooms ( do not enter any details)
- Switch to an existing room that might be in your favourites or 'rooms' list
- Switch to another existing room (whilst you can see that 2 'unamed room' rooms have been added to your room list
- Now jump to the first 'unamed room' that you created and click 'leave room' >> ok
- I presented with teh second 'unamed room' (which may be by design), Leave this room as well
- I am still presented with a UI of 'unamed room' which I am not sure where it came from (Is a bug I suppose)

**Comment by turt2live** [comment]
In practice this got fixed somewhere along the lines.
