### ISSUE TITLE
Unable to join #general:privacytools.io from matrix.org

### ISSUE THREAD

**Issue by JonahAragon** [vector-im/riot-web#11095]
### Description

Matrix.org users do not appear to be able to join #general:privacytools.io, even after upgrading the room to v5 (which we also had to do to solve some state errors we were seeing anyhow). Other homeservers seem to be able to join fine, we have a user from chat.weho.st.

### Steps to reproduce

- Login to an account on matrix.org
- `/join #general:privacytools.io`

<img width="461" alt="image" src="https://user-images.githubusercontent.com/3637842/66441960-7b3bea80-e9fe-11e9-86f6-17926801d433.png">

Logs being sent: yes

### Version information

- **Platform**: In browser, Riot 1.4.2. The privacytools.io HS runs Synapse 1.4.0.

For the web app:

- **Browser**: Firefox
- **OS**: macOS
- **URL**: riot.im/app

**Comment by JonahAragon** [comment]
Well 30 minutes later it seems to work as expected again. So I'll chalk this up to yet another bizarre matrix.org-only intermittent issue :)

I'll leave this open in case the matrix.org HS logs around this time or the Riot logs I submitted are helpful at all.

**Comment by turt2live** [comment]
It looks like matrix.org had a moment of sadness. Sorry about that, it's moderately common these days :(
