### ISSUE TITLE
macos catalina complains about Riot Desktop not being signed

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#11093]
catalina blocks Riot from running unless you create an exception in the privacy manager.  As reported by sixecho in https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$n_nt43FIQbsHEVeGoUJq0hJFbhebFFgkwt3IhcemZ98?via=matrix.org&via=privacytools.io&via=feneas.org

**Comment by aaronraimist** [comment]
Not being notarized*

**Comment by jryans** [comment]
Fixed on develop https://github.com/vector-im/riot-web/pull/11119

**Comment by jryans** [comment]
Ported to release in https://github.com/vector-im/riot-web/pull/11158
