### ISSUE TITLE
Go to bottom button shown on search results

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11109]
When someone sends more messages in a room while you're looking at search results (or searching), the button to go to the bottom shows up. For obvious reasons, it doesn't work

**Comment by t3chguy** [comment]
Looks like I resolved this some time back: https://github.com/matrix-org/matrix-react-sdk/blob/0a6f54da335b80ec4fb18812b5c93b6ac2380485/src/components/structures/RoomView.js#L1976
