### ISSUE TITLE
ldap user can't connect to server company

### ISSUE THREAD

**Issue by HaxepBcex** [vector-im/riot-web#11107]
Hello, have some trouble with ldap user...
When he tries to connect (web, desktop client, mobile) to the riot server of the company, he receives a message:
"For security, your session has been completed. Please log in again."
I get the same message when I delete the current device in the security settings.

Log from server:
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,667 - ldap_auth_provider - 133 - INFO - - User authenticated against LDAP server: ldap://ip:389 - cleartext - user: CN=user_name,OU=domen - not lazy - bound - open - <local: ip:34852 - remote: ip:389> - tls not started - listening - SyncStrategy - internal decoder окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,668 - synapse.storage._base - 496 - WARNING - - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,668 - synapse.storage._base - 535 - WARNING - - Starting db connection from sentinel context: metrics will be lost окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,671 - synapse.storage._base - 496 - WARNING - - Starting db txn 'store_device' from sentinel context окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,671 - synapse.storage._base - 535 - WARNING - - Starting db connection from sentinel context: metrics will be lost окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,701 - synapse.storage._base - 496 - WARNING - - Starting db txn 'is_support_user' from sentinel context окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,702 - synapse.storage._base - 535 - WARNING - - Starting db connection from sentinel context: metrics will be lost окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,709 - synapse.storage._base - 496 - WARNING - - Starting db txn 'add_access_token_to_user' from sentinel context окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,709 - synapse.storage._base - 535 - WARNING - - Starting db connection from sentinel context: metrics will be lost окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,712 - synapse.storage._base - 496 - WARNING - - Starting db txn 'get_device' from sentinel context окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,713 - synapse.storage._base - 535 - WARNING - - Starting db connection from sentinel context: metrics will be lost окт 09 17:36:10 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:10,063 - synapse.logging.context - 495 - WARNING - PUT-603034 - Expected logging context sentinel but found POST-603030 окт 09 17:36:10 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:10,380 - synapse.api.auth - 339 - WARNING - GET-603052 - Unrecognised access token - not in store.

This is bug or what?

**Comment by HaxepBcex** [comment]
any ideas?

**Comment by turt2live** [comment]
It looks like your server is misconfigured - visit #synapse:matrix.org for troubleshooting.

**Comment by HaxepBcex** [comment]
funny, but [https://github.com/matrix-org/synapse/issues/6188](url) matrix-org/synapse said that the problem is not related to them

**Comment by HaxepBcex** [comment]
[https://github.com/matrix-org/synapse/issues/6188#issuecomment-540169501](url)
they said that the problem is not related to them

**Comment by HaxepBcex** [comment]
they said that the problem is not related to them
![synapse](https://user-images.githubusercontent.com/37692925/67082080-17a18200-f1a1-11e9-89c0-3e3e08471338.jpg)

**Comment by enannos** [comment]
I have the same problem, using AD authentication and the ma1sd connector.

**Comment by WebFreak001** [comment]
We had the same issue, however for reference in our case this just meant the username was capitalized wrongly. For example on the first login the user logged in with all lowercase username and in another login they try to capitalize the first character which breaks things with this obscure error message.

**Comment by turt2live** [comment]
please open new issues instead of commenting on old ones.
