### ISSUE TITLE
still cant use my mousepad to scroll in chats....

### ISSUE THREAD

**Issue by MparkG** [vector-im/riot-web#11135]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by t3chguy** [comment]
Please re-open the issue with the issue template filled in. You did not provide enough information.

**Comment by MparkG** [comment]
@t3chguy 
Nah mate, go fix it, you are be already filled in with information as this is not the first message i sent and this problem is known, in riot-web aswell in the riot desktop app running riot web.

I just messaged again to remind you of this problem, as it still persists. For multiple month.
As you apparently dont know of your issues, and do not keep track of them, i suggest you hammer this scrolling problem into the search bar.

In case you are not able to get an overview have a look at #9777
where i firstly got a useless response, similar to yours,
and then no response at all, after filling out these apparently worthless forms.

the second try turned out more successful:
have a close look at #10533.
you will see a the very compromising tags "major" "bug".

Hence i am writing you a message again to encourage you to stay to your very own labels true, and concider fixing this reasonably important normal and strongly expected functionality of scrolling.
