### ISSUE TITLE
Make URL links selectable in chats

### ISSUE THREAD

**Issue by Hi-Angel** [vector-im/riot-web#11134]
**Is your suggestion related to a problem? Please describe.**

Sometimes people want to choose only part of a URL, for one reason or another. However if you try to select a subtext inside a URL, the URL would stick to your mouse instead, and there will not appear any selection. AFAIK this behavior has no other use than to annoy people.

**Describe the solution you'd like**

A text that you try to select inside a URL gets selected.

**Comment by turt2live** [comment]
This is a feature of your browser - we can't change that without an unreasonable amount of effort, sorry.

**Comment by Hi-Angel** [comment]
@turt2live I'm using desktop version of riot.

**Comment by turt2live** [comment]
The desktop version is essentially Chrome with a little less gloss.
