### ISSUE TITLE
"Explore" button blends with non-buttons

### ISSUE THREAD

**Issue by Hi-Angel** [vector-im/riot-web#11133]
### Description

People tend to follow patterns. And when one searches for clickables such as buttons/checkboxes, it is very easy to miss them, when they not only have no distinct shape compared to "labels", but also use the same font and color. See:

![Screenshot_20191012_220243](https://user-images.githubusercontent.com/7935057/66706506-089f7780-ed3c-11e9-9339-5ec68ed771aa.png)

You can't tell by the look of it that you can click `Explore` and `Filter` until you actually read the text and figure out what it is.

### Steps to reproduce

1. Start a logged-in riot-desktop instance.

#### Expected

The `Explore` and `Filter` buttons at top-left part of the window has either a box-like shape around them, or a color distinct from the non-button widget `INVITATIONS` just below them.

#### Actual

`Explore` and `Filter` buttons look totally like non-buttons `INVITATIONS`, `ROOMS`, etc just below them.

### Version information

- **Platform**: desktop
- **OS**: Archlinux
- **Version**: 1.4.2

**Comment by t3chguy** [comment]
Looks very different now.
