### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by RichGriese** [vector-im/riot-web#11145]
While trying to fix a duplicate email notification problem, see https://github.com/vector-im/riot-web/issues/11142

I ended up creating a situation where I cannot login.

I am https://riot.im/app/#/user/@richg:matrix.org

When I try to login with my username / pw I get a hanging screen saying "Unable to connect to Homeserver. Retrying..."

And if I try to login with my email address / pw it says "Incorrect username and/or password."

If I try to set a new pw it tells me; "Failed to send email: This email address was not found"

If I can't login with my existing un/pw, and the system now doesn't know my email address... what's the best way to proceed?

Enjoy life!

**Comment by aaronraimist** [comment]
The matrix.org server you are using was having issues but it should be fixed now.

**Comment by RichGriese** [comment]
Ah! I was just beginning to realize that now. I'm in, but now the encrypted messages I had with one person are unreadable... I'm wondering if a pw change I tried when it was having problems actually too place. But... at least I'm not locked out now. Will try to figure out my status late.

Thanks for taking the time to let me know.

Cheers!

**Comment by jryans** [comment]
As Aaron says, the matrix.org server is having some issues that we are working on with our hosting provider.
