### ISSUE TITLE
Jitsi unable to access Microphone, Strangely Varying Computer Specific

### ISSUE THREAD

**Issue by jph168** [vector-im/riot-web#11153]
### Description

It is impossible for the desktop application to access the microphone, not introduced in any specific version that I know of since I ran into others with this issue versions back that had to use the browser version but thought nothing of it(That they had setup something incorrectly whatnot) till I personally ran into it using a different computer, same settings same os, different hardware though,issue is hard to reproduce only affects some computers, when it does, its permanently this way for that computer. Hopefully the Debug log is helpful. 

### Steps to reproduce
Sadly have no way of reproducing this issue atm, unknown source of the issue.

### Debug Logs sent: yes

![Screenshot_2019-10-17_21-18-47](https://user-images.githubusercontent.com/31376624/67065819-9c9a8600-f124-11e9-9310-da94863fa994.png)
![Screenshot_2019-10-17_21-26-27](https://user-images.githubusercontent.com/31376624/67065917-fef38680-f124-11e9-84d7-bea669ed9f49.png)
![Screenshot_2019-10-20_12-03-54](https://user-images.githubusercontent.com/31376624/67164670-ec01d180-f331-11e9-98d3-0a59174b8bd4.png)
### Version information

- **Platform**: Desktop App

For the web app: May affect browser version depending on the browser used.

For the desktop app:
- **OS**: Linux
- **Version**: 1.4.2-1

**Comment by turt2live** [comment]
What flavour of Linux are you using?

**Comment by jph168** [comment]
Manjaro Linux

**Comment by jph168** [comment]
Completely user side.
