### ISSUE TITLE
Ctrl backspace doesn't remove next word

### ISSUE THREAD

**Issue by Destroyer** [vector-im/riot-web#11164]
### Description
Can't use ctrl backspace to remove next word when typing a message. Doesn't happen with multiline messages

### Version information
Verze matrix-react-sdk: <local>
verze riot-web: 1.5.0
verze olm: 3.1.3

- **Platform**: 
Firefox 69.0.3, Windows 10, riot.im/app

**Comment by bwindels** [comment]
Works for me on Fedora 30/Gnome 3.32.2 fwiw.

**Comment by turt2live** [comment]
Works fine for me on Firefox on Windows.

**Comment by Destroyer** [comment]
Since riot stopped working today and i kept refreshing it, the issue appears to be gone.
