### ISSUE TITLE
CSS on group room tags broken

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11160]
### Description

![image](https://user-images.githubusercontent.com/1342360/67108916-be047c00-f1cf-11e9-90d1-d6726f91a432.png)

The tags for rooms in groups has some strange vertical CSS going on. The `Guests Allowed` and `World Readable` tags can actually get on top of each other.

Example group: https://riot.im/app/#/group/+rustlang:matrix.org

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v71a
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/11174 (also covers the avatar being in the wrong place)
