### ISSUE TITLE
Registration Required dialog should prompt to login

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#11172]
There are a few actions (join group, create room etc) which when performed in Riot when you are not logged in (guests enabled) it asks you to register.

![Screen Shot 2019-10-21 at 10 11 38](https://user-images.githubusercontent.com/1391051/67192458-8b36cf80-f3eb-11e9-823f-c28dbbabd592.png)

I think that it should also give you an option to login, this means that if someone sends you a link for a riot instance you are not signed in to, (i.e. I am logged in on riot.im and I send you a riot.cadair.modular.im link) then I have the option to sign into my matrix account to perform the action rather than having to navigate to my signed in Riot. (or just if I am on a new device etc).

**Comment by turt2live** [comment]
This is an artifact of ILAG :|

**Comment by Cadair** [comment]
What is ILAG? :grinning:

**Comment by turt2live** [comment]
Improved Landing As Guest. It's a legacy thing within Riot that was ripped out for 1.0, but we never really touched parts of communities which are clearly affected.

**Comment by Cadair** [comment]
It's not just the communities stuff, it's also clicking on the room creation button etc.
