### ISSUE TITLE
Cleanup emojipicker code

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11179]
Some points to clean up while going through the emojipicker PR:

- [ ] consider only creating the DATA_BY_EMOJI object when opening the picker, although that might further slow down things. It does seem like a big object to keep permanently in memory.
- [ ] consider only creating `emoji.filterString` when opening the picker and perhaps not putting it on emoji, an object exported by emojibase.
- cleanup code to track most recent emojis
  - [ ] actually track most recent, right now it returns and tracks most used.
  - [ ] cap most recent to amount we use, this will also solve the problem that over time `REACTION_COUNT` could grow quite big.

The old tooltip behaviour is removed, so if we do end up wanting a feature flag, we'll need to bring it back, but I think we said we can do then only when we feel we need to to be able to release.

**Comment by tulir** [comment]
> actually track most recent, right now it returns and tracks most used.

The code is intended to track most used (with recentness as the tie-breaker). That's why the title in the UI is "Frequently Used"

**Comment by jryans** [comment]
@bwindels What's the state of this bug? Is the intention to fix these things before the new reactions ship in a release...?

Also, I don't really follow:

> The old tooltip behaviour is removed, so if we do end up wanting a feature flag, we'll need to bring it back, but I think we said we can do then only when we feel we need to to be able to release.

Are we saying we'd like to be disable the new reactions UI if the above items are not yet completed...?

**Comment by jryans** [comment]
It sounds like these are optimisations we'd like to have, but they aren't release blockers.

**Comment by bwindels** [comment]
> The old tooltip behaviour is removed, so if we do end up wanting a feature flag, we'll need to bring it back, but I think we said we can do then only when we feel we need to to be able to release.

I meant that if we want to have a feature flag, we'd need to bring the old tooltip back for reactions.

**Comment by t3chguy** [comment]
Emoji in general were cleaned up and consolidated with the EmojiProvider Autocomplete code
