### ISSUE TITLE
New reactions picker is slow to open.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#11173]

**Comment by lampholder** [comment]
Firefox osx

**Comment by lampholder** [comment]
slow == ~200ms rather than instantaneous

**Comment by turt2live** [comment]
for me it's ~150ms on first render, then sub-100ms on subsequent renders.

**Comment by bwindels** [comment]
@t3chguy suggests virtualizing the scrolling to have less DOM nodes in the tree

**Comment by turt2live** [comment]
Scrolling isn't the slow part?

**Comment by bwindels** [comment]
No, doing a quick profile, opening the picker in chrome takes 524ms, of which layout takes 117ms, and a lot of time seems spent on mounting `Emoji` components, so only mounting them when they would be shown could speed it up.

**Comment by bwindels** [comment]
Started virtual rendering on `bwindels/speedupemojipicker` but needs more work.
