### ISSUE TITLE
Since 1.5.0 Riot complains "Cannot reach homeserver"

### ISSUE THREAD

**Issue by popey** [vector-im/riot-web#11178]
### Description

The bug described in issue #10373 appears to have returned in the snap of riot-web 1.5.0

In 1.4.x everything worked fine.

I build the snap using a short script such:

```
cp electron_app/riot.im/config.json .
yarn install
yarn dist
yarn run build:electron:linux
```

The cp command was to fix #10373, which it did. However, since 1.5.0, I now get:

![Screenshot from 2019-10-21 16-42-11](https://user-images.githubusercontent.com/1841272/67220694-277bc900-f422-11e9-9eb2-3e8b62c24700.png)

Which smells like the same thing.

### Steps to reproduce

```
snap install riot-web --stable
snap run riot-web
```

Everything works as expected. Close Riot.
Now update to 1.5.0 which is in the edge channel.

```
snap refresh riot-web --edge
snap run riot-web
```

Get the error in the above screenshot.

I'd expect to be able to login.
- **Platform**: Desktop app

For the web app:
For the desktop app:

- **OS**: Ubuntu 19.10
- **Version**: 1.5.0

**Comment by turt2live** [comment]
By default it is trying to reach matrix.org, which is having some performance problems today. Use a different homeserver in the config, or log in so that this doesn't happen.

The fact that you can't change your homeserver is a bug: https://github.com/vector-im/riot-web/issues/11077
