### ISSUE TITLE
Community room list has regressed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11174]
the lozenges that we had before for 'guests can join' etc have broken in a really ugly manner

**Comment by ara4n** [comment]
<img width="1114" alt="Screenshot 2019-10-21 at 11 39 51" src="https://user-images.githubusercontent.com/1294269/67198788-a1e32380-f3f7-11e9-9c73-5999ccbc69f4.png">

**Comment by ara4n** [comment]
icon is misaligned with text; room name has "Guests can join" appended to it.

**Comment by aaronraimist** [comment]
Broke between version 1.3.3 and 1.3.4
