### ISSUE TITLE
Not able to join room

### ISSUE THREAD

**Issue by MichaelKohler** [vector-im/riot-web#11180]
### Description

I tried to join https://riot.im/develop/#/room/#riot-web:matrix.org but when clicking the "Join" button it crashed.

### Steps to reproduce

- Use riot.im develop version
- Try to join #riot-web:matrix.org

### Version information

- **Browser**: Firefox Nightly
- **OS**: macOS 10.14.6
- **URL**: riot.im/develop

**Comment by MichaelKohler** [comment]
I've just now also sent debug logs.

**Comment by MichaelKohler** [comment]
"Clear cache and reload" helped.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/11120 (same stacktrace)
