### ISSUE TITLE
New input field in Invite/Create DM dialog

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11199]
this does not include search, just entering mxid, e-mail, see https://github.com/vector-im/riot-web/issues/11200 for that.

~~implement input field with cider:~~
 
   - allow caret to navigate between pills
   - turn into pill on "," & detect:
     - typed mxid, show spinner while fetching profile
     - typed e-mail, show spinner while talking to IS
     - other: error pill
   - have input grow vertically with lots of pills
   - support pasting identifiers separated by , and turn them into pills
   - add tooltip to pills, make the tooltip content accessible by making the screen reader read it out when landing on the item in the list.
   - if not too much work, select pills as a whole when having the caret on them, rather then inside their text.

----

Update Jan 6, 2020 (TravisR): New requirements without CIDER (for now?). These requirements are much closer to the old dialog and feel good enough for now.

* [x] Pills for users
* [x] X next to pill removes/deselects the user
* [x] Emails use the dedicated pills
* [x] No phone pills for now (was a demo in the design below)
* [x] Pasting figures out the pills to add - with error pills or error messages?
* [x] Checkmarks for selected users

Accessibility is pawned off to https://github.com/vector-im/riot-web/issues/11771

![image](https://user-images.githubusercontent.com/1190097/71867275-c41b4200-30c6-11ea-9ab3-e46fc8fadf67.png)

----

More design at https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5d661ab8684fa927fe955d8e

**Comment by turt2live** [comment]
Done by the referenced PRs above.
