### ISSUE TITLE
Release FTUE: improve user lists

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11196]
Once [all the tasks](https://github.com/vector-im/riot-web/labels/project%3Aftue-user-lists) are done:

 - [ ] remove feature flag
 - [ ] remove old `AddressPickerDialog` code after a few weeks

The plan is to duplicate the `AddressPickerDialog` code so we easily feature-gate the new dialog features.

**Comment by turt2live** [comment]
We can't remove the old address picker dialog until groups are changed. For now, this is done.
