### ISSUE TITLE
Apply new design to user lists in Invite/Create DM dialog

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11201]
- [x] add own profile link
 - [x] change copy
 - [x] design polish
 - [x] remove feature flag - blocked on https://github.com/vector-im/riot-web/issues/11769
 - [x] i18n for humanization of time
 - [x] make dialog work for regular invites too

**Comment by turt2live** [comment]
This is blocked on design review in order to continue.

**Comment by turt2live** [comment]
Design feedback here: https://github.com/vector-im/riot-web/issues/12000

**Comment by turt2live** [comment]
Going to track this as the PR itself so it's a bit more clear on the workflow board: https://github.com/matrix-org/matrix-react-sdk/pull/3906
