### ISSUE TITLE
Use SSSS for new key backups

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11209]
The key backup key info is currently stored in the metadata for the key backup. It needs to be migrated to Secure Secret Storage (https://github.com/matrix-org/matrix-doc/pull/1946) so the user's recovery key / passphrase is for the SSSS master key and the backup key is then obtained via that.

This task covers:
 * When we set up a new key backup, use SSSS instead of key backup metadata
 * Support key backup keys in both key backup metadata and SSSS

Blocked on spec release of https://github.com/matrix-org/matrix-doc/pull/1946 as this would already be two different places the key could be - let's not make it 3 with vendor/stable prefixes of SSSS.

js-sdk SSS impl is in the cross-signing PR: https://github.com/matrix-org/matrix-js-sdk/pull/832

**Comment by jryans** [comment]
To avoid the bootstrapping cycles involved in creating all the various keys without all the infrastructure in place, @dbkr suggests:

<ul><li>Create cross signing keys, but don't store the private parts yet</li><li>Create an SSSS default key (which will be signed with the cross-signing master key you just created)</li><li>Save the cross signing keys to SSSS</li><li>Create key backup</li></ul>

**Comment by jryans** [comment]
As it turns out, the steps above are quite similar to https://github.com/vector-im/riot-web/issues/11212, so I'm effectively working on both issues. (After chatting with @dbkr, originally we weren't signing the SSSS key, so there was less of cycle than there is currently.)

**Comment by jryans** [comment]
For the moment, this is paused while we complete the related items in https://github.com/vector-im/riot-web/issues/11212.

**Comment by jryans** [comment]
@dbkr will be taking over here while I am away.

**Comment by jryans** [comment]
@dbkr is focusing on the new build system, so I'm taking this one back.
