### ISSUE TITLE
Redesigned search results in suggestions/recent conversations in Invite/Create DM dialog

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11200]
* [x] Search acts like a filter on recents/suggestions
* [x] Mix in the sever-side results to suggestions
* [x] Font weight 900 for matched portions
* [x] Match displayname and user ID
* ~~Keyboard navigable~~ https://github.com/vector-im/riot-web/issues/11771
* ~~3pids behaviour stays the same, except https://github.com/vector-im/riot-web/issues/11028~~ https://github.com/vector-im/riot-web/issues/11770
* [x] "No results" for no results

**Zeplin designs are wrong for this screen - we're keeping the sections when searching**

Design at https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5d661ab8684fa927fe955d8e

**Comment by tapper82** [comment]
Add the A11Y lable
