### ISSUE TITLE
Verify by QR code

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11216]
Add verification by QR code to outbound and inbound verification requests. Negotiate and show the appropriate options depending on what's supported by either side.

**Comment by turt2live** [comment]
MSC: https://github.com/matrix-org/matrix-doc/pull/1544
Figma: https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing

![image](https://user-images.githubusercontent.com/1190097/72654478-fe99a000-394c-11ea-8d3a-124a41d0e1ce.png)
