### ISSUE TITLE
Switch to verifying users rather than devices

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11213]
This probably ought to be coupled tightly to https://github.com/vector-im/riot-web/issues/11212 since between doing that and this, we'll be in a weird quasi-state where we've set up cross-signing but new verifications will still be verifying devices.

In the MemberInfoPanel, if the cross-signing labs flag is enabled, ~hide verify buttons on the individual devices~ (moved to https://github.com/vector-im/riot-web/issues/11668) and instead show just one for the user. This button does a cross-signing verification. Use existing verification UI for now, placeholder UI for the verify button at this stage.

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3728 is enough to verify users, but it does not currently hide the devices as well. From chat in the room, we may want a separate issue to track hiding the device list in case it's more complex than just hiding?

**Comment by jryans** [comment]
Or does "hide verify buttons on the individual devices" mean the device list would stay, but just the verify buttons per device removed...? Either way, let's track with a separate issue: https://github.com/vector-im/riot-web/issues/11668
