### ISSUE TITLE
Set up cross signing in key backup flow

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11212]
After https://github.com/vector-im/riot-web/issues/11209

Set up cross signing in the background when setting up a key backup:

 * Add a cross-signing labs flag (@jryans: [done separately](https://github.com/vector-im/riot-web/issues/11407))
 * When we set up a new key backup, if the labs flag is turned on:
   * Make the 3 keypairs and save them to SSSS along with the key backup key
   * Do the initial set of signatures between the above keypairs & upload to server
 * No UI changes apart from the labs flag

Tasks:

* [x] Add a cross-signing labs flag
* [x] Work out React and JS SDK APIs for cross-signing key creation
* [x] Create cross-signing keys
* [x] Create SSSS default key, signed with cross-signing master key
* [x] Store cross-signing keys in SSSS
* [x] Get cross-signing keys from SSSS on a new device
* [x] Prompt for secret storage passphrase
* [x] Sort out device signing upload success even when unauthed
* [x] Re-sign secret storage key when cross-signing key changes
* [x] Check why regular keys upload with 200 then embedded 400 (filed https://github.com/vector-im/riot-web/issues/11574)
* [x] Add tests

**Comment by jryans** [comment]
From chatting with @dbkr today, he'll be taking over remaining work here.
