### ISSUE TITLE
Cross-signing setup: verify by QR code

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11217]
After https://github.com/vector-im/riot-web/issues/11215
After https://github.com/vector-im/riot-web/issues/11216

Once we've done the above (for SSSS key sharing) and also finished QR code verification, add QR code verification to the new sign-in flow.

**Comment by turt2live** [comment]
Work to do on this:
* [ ] Clean up FOSDEM demo code into reviewable PRs
* [ ] Match designs
* [ ] Make it work still
