### ISSUE TITLE
Cross-signing setup: verify by emoji

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11215]
After https://github.com/vector-im/riot-web/issues/11214

Add support for verifying a new signin by emoji.

 * Implement SSSS key sharing
 * Add the 'verify by emoji' option to the verify-new-signin flow, using SSSS key sharing to request the default key from other devices once verification is completed.

**Comment by turt2live** [comment]
Has this actually been done?

**Comment by jryans** [comment]
Hmm, we've kind of "accidentally" done pieces of it. A few things are missing still:

* There is no key sharing between devices, have to enter SSSS instead
* The flow does not match designs

![2020-01-30 at 09 34](https://user-images.githubusercontent.com/279572/73437153-c0847f00-4343-11ea-802e-91cc597516c5.png)

**Comment by turt2live** [comment]
@jryans would it be worth me adding this to the QR code estimate?

**Comment by turt2live** [comment]
answer: no
