### ISSUE TITLE
Sending exactly **BOLD ** doesn't turn bold

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11229]
Sending a message with ** at the start and end, with a space before the ** at the end gets sent as plain text

**Comment by bwindels** [comment]
![image](https://user-images.githubusercontent.com/274386/67566412-3c54a700-f717-11e9-8a2e-b86d49c22aad.png)

**Comment by lampholder** [comment]
Same for GitHub:

**hello **

I understand we can probably "do better" in terms of generously understanding a user's intention (**bold ** was almost certainly meant to be **bold**) but personally I'd rather we hug the standard as closely as we can (I like the simplicity of "riot does X flavour markdown" over "riot does X flavour markdown with tweaks Y, Z and Խ"

**Comment by bwindels** [comment]
huh, indeed. Wasn't aware that this is what markdown mandates. Oh well, closing then.
