### ISSUE TITLE
Rethink release process so we can support native node modules

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11227]
Blocks: https://github.com/vector-im/riot-web/pull/11125
Blocks: https://github.com/vector-im/riot-web/pull/10369

**Comment by turt2live** [comment]
Related: #8299

**Comment by jryans** [comment]
As an interim step to avoid long-lived PRs waiting for this process, we're going to attempt the following:

* Test for the native node module(s) needed with runtime checks
* Do not add the native node module as an app dependency (instead record what should be added in a doc)

**Comment by turt2live** [comment]
The label "new-build-process" fixes this.

**Comment by dbkr** [comment]
Split out into the above.
