### ISSUE TITLE
Move verification to side panel

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11224]
After https://github.com/vector-im/riot-web/issues/11222
After https://github.com/vector-im/riot-web/issues/11223

Move the verification from dialogs into the side panel

Moved remaining work into other tickets:

 - [look at .cancel code to determine whether something was missed, dismissed or errored, ...](/vector-im/riot-web/issues/11971)
 - [UX refinements for verification in right panel](/vector-im/riot-web/issues/11970)
 - [show/hide verification toast when going to/leaving DM?](/vector-im/riot-web/issues/11969)
 - [check in SSSS if user is really verified when showing 'X is verified' tile](/vector-im/riot-web/issues/11968)
 - [handle race when both parties send a .ready event, see verif over dm spec how to handle.](/vector-im/riot-web/issues/11967)
 - [show toast when verification request is accepted/declined on requestor side if not in already](/vector-im/riot-web/issues/11966)
 - [clients that didn't accept verification request should dismiss toast, show accepted in timeline](/vector-im/riot-web/issues/11964)
 - [Verification messages in the timeline don't use the historical display name](/vector-im/riot-web/issues/11727)
 - [Accepting DM verification in an encrypted DM can cause unknown device warnings you can't access](/vector-im/riot-web/issues/11709)
 - [it's possible to end up with multiple verification sessions in flight with the same user](/vector-im/riot-web/issues/11698)
 - [Implement all states for new IconButton as per design](/vector-im/riot-web/issues/11390)

**Comment by bwindels** [comment]
react-sdk branch: `bwindels/verification-right-panel`
js-sdk branch: `bwindels/verification-ready`

**Comment by bwindels** [comment]
some notes of current state:

 - DONEISH: support .ready event
 - replace KeyVerificationStateObserver with VerificationRequest
 	- DONE-ISH: in MKeyVerificationRequest
 	- in MKeyVerificationConclusion
 	- in VerificationToast
 - DONE: introduce new phase and panel to right panel
 - DONE: navigation to open request in side panel
 	- listen for for show_verification_request in MatrixChat
 	- show right panel if `collapsedRhs`
 	- emit view_right_panel_phase with new phase
 - implement component for side panel
 - Room.timeline is *not* fired for every event in the store upon refresh, duh. So what does this mean for restoring toasts when reloading? Note that this is not a requirement though ...
 - wrt to VerificationRequest, sometimes we set an event reference on remote echo, but we already change the phase when sending the event. We should have a consistent approach to this so we don't get it wrong.

 - only validated verification events should be displayed in the timeline ... if we don't check timeout in validateEvent and allow all verif events to create requests independent from their age, we can probably make this work. We can mark the request as timed out and not create a verifier and not send any events, but still allow the state machine to update with incoming events.

 - while testing, I get the following errors:
	- send a request from chrome
	- click accept in ff, sends .ready event
	- the code in the DeviceVerifyDialog gets the verifier through beginKeyVerif and sends .start event (should verify this)
	- the remove echo of the start event tries to create a verifier and fails because it can't find out who it is directed to (can't determine who the verifier should be targeted at. No .request or .start event and no targetDevice)
  	- questions:
  		- why doesn't it use the ready event that was cached?
  		- why isn't the verifier set earlier? verifier should always be defined while in phase start

**Comment by bwindels** [comment]
the notes above are stale and should be ignored ^

**Comment by jryans** [comment]
@bwindels Is this safe to close then, since we've got other tickets for the remaining work?

**Comment by jryans** [comment]
(@bwindels says yes.)
