### ISSUE TITLE
Room decoration: padlocks

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11226]
Decorate private rooms with padlocks as per designs:

 * Padlock: rooms is invite only
 * No padlock: Room is publicly joinable

(nb. This is absolutely nothing to do with cross-signing but has been lumped into the sprint because it's so closely related to the e2e UX improvements)

**Comment by aaronraimist** [comment]
Related: #8742

**Comment by foldleft** [comment]
I'm not sure what assets to use – is res/img/feather-customised/lock.svg right one?
