### ISSUE TITLE
Room decoration: shields

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11225]
Decorate rooms with black/green/red shields as appropriate

(The following describes rooms in terms of users, but updating the shields on users in the UI is left to a separate issue https://github.com/vector-im/riot-web/issues/11811.)

* Users
  * None: e2e off in the room
  * Black: Encryption is enabled (I don’t care about their devices)
  * Red: I’ve verified them and an unverified device exists or they were previously verified and their cross-signing identity has changed
  * Green: I’ve verified them and all of their devices are verified
* Rooms
  * None: e2e off in the room
  * Black: Encryption is enabled
  * Red: A red user exists in the room
  * Green: All users are green
  * (The state of all users, including yourself, is considered when decorating a room)

The areas to update for this issue are:

* Room avatar in the room list
* Room avatar in the room header above the timeline for the current room
* Shield in the message composer at the bottom

**Comment by jryans** [comment]
This decoration should only appear when the cross-signing labs flag is enabled.

**Comment by jryans** [comment]
For some additional detail, the shields are meant to layer onto the room icon in both the room list and room header:

<img width="177" alt="2020-01-14 at 12 01" src="https://user-images.githubusercontent.com/279572/72342953-a0a75700-36c5-11ea-81b2-0826fcfb8946.png">
<img width="457" alt="2020-01-14 at 12 02" src="https://user-images.githubusercontent.com/279572/72342976-b157cd00-36c5-11ea-8bf8-c0547e6fccac.png">

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2906)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/845)

**Comment by foldleft** [comment]
@jryans this decoration is already added in order to represent the room state under the old scheme – but it'll only behave the new way with the labs switch on

**Comment by foldleft** [comment]
I just wanna flag here that it looks like it'll be a pretty big change to start keeping track of all room states simultaneously – it'll require a new top-level-ish (`RoomList.js`, probably) bit of code to watch every room and every user and figure out shields appropriately.

**Comment by foldleft** [comment]
Note that this task isn't quite done – it also represents the need to put things in the room list. That'll take a little more care with respect to getting the rooms x users cross-product and calculating it at the top level, so I'm delaying this one in favour of #11880 which has a lot more user visibility

**Comment by jryans** [comment]
The logic for producing the correct shield for each room has now be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3850.

A few tasks remain, but we've broken them out into separate issues, so we can close this and use those to follow the remaining bits:

* [Shield in the room header should appear in corner for room avatar · Issue #11833 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11833)
* [Room list decoration: shields · Issue #11935 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11935)
