### ISSUE TITLE
quote context menu option shown on search results

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#11231]
but given composer is not shown it does not work

**Comment by grahamperrin** [comment]
Thanks and FWIW my preference might be for the composer to appear in response to opting to quote. 

If what's to be quoted was difficult to find, then the end user might be frustrated by disappearance of the search result. This makes me wish for a quote in this context to take the form: 

> At {place} on {timestamp}, {name} wrote: 
> 
>> {blah blah blah}
>>
>> {blah blah blah}

**Comment by spacebug0** [comment]
Is is supposed to work?

I needed this function today. I was gonna quote something I search and saw that it did not work *sad face*
