### ISSUE TITLE
Let users start a message with ">" again

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/riot-web#11237]
Now that the latest Riot release has removed the markdown toggle, it seems to no longer be possible to start a message with ">" without it formatting the message in a way which may not be desired.

Screenshot of what is currently happening: https://imgur.com/a/XoJaLRY
Screenshot of what I want to be able to do: https://imgur.com/a/p6wKJke

I am requesting a way for a user to be able to start their message with ">" without the formatting. The easiest way around this that I can think of is to let users type a space before the ">". Currently, even if you start the message with a space (or more than 1), they get trimmed and it still formats the message. If there's currently a way to do this that I'm missing, please let me know.

**Comment by t3chguy** [comment]
Use /plain

**Comment by BurnyBoi** [comment]
Thanks. That works for me

**Comment by anoadragon453** [comment]
What if I want to write a formatted message starting with `>`, but containing markdown?

![image](https://user-images.githubusercontent.com/1342360/72807171-b7622680-3c4e-11ea-896a-84e0f989e3c7.png)

**Comment by t3chguy** [comment]
`\> foobar *foobar*` works for that

**Comment by kakolisgay** [comment]
> `\> foobar *foobar*` works for that

Escapes seem to be broken in riot at the moment, that's the issue.

**Comment by t3chguy** [comment]
I tested my above example and it worked just fine
