### ISSUE TITLE
check-i18n.pl is linked out of directory

### ISSUE THREAD

**Issue by yesennes** [vector-im/riot-web#11247]
### Description
The file `scripts/check-i18n.pl` is a symbolic link to `../../matrix-react-sdk/scripts/check-i18n.pl`. If I understand the project set up, we can't rely on that file existing there, it instead should link to `../matrix-react-sdk/scripts/check-i18n.pl`. This doesn't seem to be causing problems with normal use, but can break some tools i.e. trying to use grep inside the project folder will break.

I can fix this really quick if someone can confirm its an issue and not me misunderstanding something.

### Steps to reproduce

- Clone the project in a directory without matrix-react-sdk in a sibling directory
- `ls -l scripts/check-i18n.pl`

Symbolic links should point to files that exist.

Logs being sent: no

### Version information

N/A
Centos 7

**Comment by turt2live** [comment]
The project should not have the react-sdk within the riot-web directory, so the symlink is correct (if one were to follow the development instructions).

Realistically it probably shouldn't be a symlink, but the alternative is code duplication :(

**Comment by t3chguy** [comment]
> Realistically it probably shouldn't be a symlink, but the alternative is code duplication :(

Could it not expose it like https://github.com/matrix-org/matrix-react-sdk/blob/develop/package.json#L32-L36

**Comment by turt2live** [comment]
There was a reason why we didn't do that, but maybe yarn fixes it

**Comment by yesennes** [comment]
@turt2live Oh, I see. The directions from build from source end up with the folders inside riot web, while the development instructions don't. Maybe we should consider changing that to make them consistant? Could be as simple as having `scripts/fetch-develop.deps.sh` pop a directory before it clones the sdks.

**Comment by jryans** [comment]
It does seem like we're creating a trap for people by having `scripts/fetch-develop.deps.sh` arrange a different directory layout than would be used for full development mode...

I guess the tricky part is `scripts/fetch-develop.deps.sh` is used for CI as well, so we'd need to tune those steps if we change the script.

**Comment by turt2live** [comment]
We shouldn't be encouraging people to use the CI scripts. If I have to rename that script to stop people using it, I will :|

The development instructions should be making no reference to that script.

**Comment by jryans** [comment]
Let's just remove references to that script from the docs then.

**Comment by yesennes** [comment]
Renaming seems like a good idea, `fetch-develop.deps.sh` not fetching developer dependencies seems misleading. Even if we remove it from the documentation, some people could stumble on it.
