### ISSUE TITLE
Use r0 APIs for privacy features when HS supports spec version

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11246]
As per [MSC2324](https://github.com/matrix-org/matrix-doc/pull/2324) on how to ship spec-dependent things, we should change to the `r0` API prefix when a server advertises the spec version that includes a feature.

For privacy, this means updating how we handle feature flags and spec versions to change the prefix when the spec version appears.

**Comment by turt2live** [comment]
Please double check with the backend team that this is the plan for legacy stuff. Although there's an MSC for the process, it's not final yet. There's also no wording for how past flags are being dealt with, if at all.

**Comment by jryans** [comment]
At the moment, it's not entirely clear to me what the backend team intends here. I have [asked](https://github.com/matrix-org/synapse/issues/6045#issuecomment-549778300) for clarification on their r0.6.0 issue.

**Comment by turt2live** [comment]
from memory, which may have been a verbal conversation, the plan is to honour the 2 month notice window. I would poke Neil directly to get an answer.

"2 month notice window" being the backend team supports the unstable APIs, spec release, *and* flags for 2 months at which point they start screaming at us if we haven't done our appropriate checks.

**Comment by jryans** [comment]
Looks like @neilisfragile indeed agrees with the 2 month window and then unstable prefix would be removed.

We should go ahead and use the stable prefix in Riot when the new spec version appears.

**Comment by jryans** [comment]
PR is ready to go, so we're just waiting on the r0.6.0 spec text later this week.

**Comment by turt2live** [comment]
For good measure: r0.6.0 is now published, as is r0.3.0 for identity servers. The backend team has some work to do in order to have the version published on their end (moving things to the stable namespaces) still. Under the new spec process, if they haven't done so in 2 months we get to yell at them.

**Comment by jryans** [comment]
Hooray! To be clear though, it's fine to merge this in Riot now though, right?

**Comment by jryans** [comment]
Answer: yes, though it means it's untested.
