### ISSUE TITLE
Odd empty space to the left of collapsed menu

### ISSUE THREAD

**Issue by Fmstrat** [vector-im/riot-web#11241]
![riot](https://user-images.githubusercontent.com/971474/67644175-65329300-f8f5-11e9-800f-27048165cfd9.png)

### Description

I'm new to Riot, so I'm not sure if this is an interface issue, or how it's supposed to be for some reason. Given the "floating circle" design method, I would expect the `Communities` and `Bug report` buttons to hover over the collapsed area of the menu bar. Instead, they seem to be causing a large empty space to exist to the left of the menu bar that cannot be removed.

When docking the window at 1/4 screen, this takes up some valuable real estate and I would expect it could be configured to hover or be removed entirely.

### Steps to reproduce

- Open Riot
- Look to the left ;)

### Version information

- **Platform**: Ubuntu 18.04, latest from the repo.

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 1.5.0

**Comment by turt2live** [comment]
This is the Left Left Panel (or better known as the Communities panel). In theory it's supposed to behave like Discord's servers thing. 

There's some new designs in the pipeline for making this not so empty/useless-looking. In the meantime, there's a setting to turn off the Community Filter Panel found in your user settings.
