### ISSUE TITLE
Doing yarn upgrade on react-sdk causes breakage in Firefox

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11253]
1. Borrow Tom's account to find out what is actually being broken and how
2. Bisect the updates to see which dependency change has broken us

**Comment by t3chguy** [comment]
Upon further thought, I'll push this back until Wednesday when Tom is in the office and this will be much clearer

**Comment by t3chguy** [comment]
This is caused by Bluebird. Here starts the eradication of Bluebird.
