### ISSUE TITLE
VectorAuthFooter.js no longer overriding AuthFooter.js since 1.4.0

### ISSUE THREAD

**Issue by csett86** [vector-im/riot-web#11250]
### Description

The override in riot-web/src/components/views/auth/VectorAuthFooter.js for the component matrix-react-sdk/src/components/views/auth/AuthFooter.js is no longer working since version 1.4.0

Thus the config.json options for "branding.authFooterLinks" also no longer works.

### Steps to reproduce

- Open welcome page on 1.4.0+: https://riots.im/1.4.0/#/welcome No blog/twitter/github links
- Same on riot.im/app and riot.im/develop: No blog/twitter/github links
- Open welcome page on 1.3.6: https://riots.im/1.3.6/#/welcome blog/twitter/github links from riot-web/src/components/views/auth/VectorAuthFooter.js visible

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 70, Safari 13.0.2
- **OS**: macOS
- **URL**: riot.im/app and https://riots.im/1.3.6/

**Comment by jryans** [comment]
Hmm, indeed... 😓 Thanks for letting us know!
