### ISSUE TITLE
disable_3pid_login attribute missing in documentation

### ISSUE THREAD

**Issue by fnoah** [vector-im/riot-web#11255]
The configuration attribute `disable_3pid_login` is not present in the [documentation](https://github.com/vector-im/riot-web/blob/develop/docs/config.md). Is this intentional or does it belong there?

**Comment by turt2live** [comment]
Where are you seeing that attribute coming from?

**Comment by fnoah** [comment]
I don't know where I got this from. But as far as I know, `disable_3pid_login` is a valid attribute in Riot's `config.json`.

**Comment by jryans** [comment]
This was documented in https://github.com/vector-im/riot-web/pull/13260.
