### ISSUE TITLE
Switch to verification in DMs

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11251]
Scope of this issue is to switch verification events from going over to_device events to being sent in DM rooms. Some UI will be needed for this, eg. a prompt to create a new DM if the user doesn't already have one with both people in.

 - [x] Add a labs flag for verification in DMs.
 - [x] Support incoming verifications both in DMs and old to_device messages. If the labs flag is on, initiate verifications using DMs (interface in https://github.com/matrix-org/matrix-js-sdk/pull/1050)
 - [ ] Once other clients support verif over DMs, remove labs flag & always send over DM.
 - [x] Add tiles for verification events in rooms (nb. I think we should only show the events if we'd start a verification from them, eg. if we see verif events in non-DM rooms or for nonmatching users, just don't display anything).
 - [x] Any other UI necessary, eg. prompt to start a DM if there isn't one we can use.

 * Verifications will still pop up in a dialog for now: nag bar / verif in side panel are separate tickets and can be decoupled (unless it makes sense todo them together).

**Comment by bwindels** [comment]
@dbkr What is this ticket about exactly? About sending the actual verification events over the timeline in the DM instead of to_device messages? Or is this a meta ticket?
