### ISSUE TITLE
Javascript error - TypeError "e is null" in PinnedEventTile, crashes room

### ISSUE THREAD

**Issue by freelock** [vector-im/riot-web#11268]
### Description

I tried to view pinned messages in a room in Riot >= 1.5.0, and now the room is unreachable.

### Steps to reproduce

I'm not sure what causes this -- I have other rooms where pinned messages still work as expected. But this one room, I was on /develop and clicked the Pin to see previously pinned messages, and I got this:

![error page](https://matrix.freelock.com/_matrix/media/r0/download/matrix.freelock.com/jlDsVsswvncSHhtUBwXCXBBt)

... Clear Cache and Reload brings me back to the same page -- now that this has happened, I cannot get into this room in Riot Web at all!

I tried switching to /staging, and this room showed the same message.

I tried logging into a self-hosted Riot 1.5.0 in an entirely different browser, and at first it worked, but when I enabled pins and clicked the pin, same thing happened.

Console logs show this:
![image](https://user-images.githubusercontent.com/46937/67906148-f2adf700-fb30-11e9-8427-31cc5f7e4ee5.png)
(messages scroll too fast to cut/paste!)

Android clients have no trouble accessing this room.

Log: not sent (this is a bit more of a sensitive room, would prefer not to send)

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Latest Chrome, Firefox
- **OS**: Ubuntu,
- **URL**: riot.im/develop, riot.im/staging, riot.im/app, chat.freelock.com (1.5.0)

**Comment by t3chguy** [comment]
@freelock without the logs and thus original source lines its a bit hard to investigate the bug but tried my best to fix it, fix should be deployed to /develop shortly. Re-open the issue if it still occurs for you, thanks!

**Comment by freelock** [comment]
oh awesome, looks like the fix worked! I'm able to be in the room again... thanks!

**Comment by t3chguy** [comment]
Awesome!
