### ISSUE TITLE
Setting user profile picture resets per-room nicks

### ISSUE THREAD

**Issue by CraftedCart** [vector-im/riot-web#11293]
### Description

If custom nicknames are set on a per-room basis, then the user profile picture is changed, custom nicknames are reset. (With a message `CustomNick changed their display name to OrigNick.`, but using the new profile picture)

### Steps to reproduce

- Set custom nicknames in various rooms using the `/myroomnick` command
- Go to user settings and upload a new profile picture, and save
- Custom nicknames are all reset to the one specified in user settings when saving

**Describe how what happens differs from what you expected.**

I'd expect only the profile picture to change whilst keeping custom nicknames in rooms

**Logs being sent**: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.4.2

**Comment by turt2live** [comment]
This isn't really a formally supported feature yet: https://github.com/vector-im/riot-web/issues/2458

**Comment by jtrees** [comment]
> This isn't really a formally supported feature yet: #2458

What is the `/myroomnick` command for then? Was it accidentally included in a release? Has it since been removed?

**Comment by t3chguy** [comment]
As in it works on Synapse, but there is nothing in the Matrix Spec to mandate it working the way it does. https://github.com/matrix-org/matrix-doc/issues/545 
It is there for powerusers.
