### ISSUE TITLE
Redo keyboard command doesn't work

### ISSUE THREAD

**Issue by kethinov** [vector-im/riot-web#11298]
### Description

Redo keyboard command causes undo instead.

### Steps to reproduce

1. Open a chat in the Electron app.
2. Type stuff.
3. Undo some stuff with cmd+z.
4. Redo some stuff with cmd+shift+z.
5. Redo keyboard command causes undo instead.

### Version information

- **OS**: macOS Electron app. (Possibly other operating systems too, only tested on macOS.)
- **Version**: 1.5.0

**Comment by t3chguy** [comment]
So it looks like the new composer didn't realise Mac had a different shortcut for Redo typically and instead coded it as Cmd+y
