### ISSUE TITLE
Rooms disappear and don't come back after clearing cache and reload

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11303]
### Description

![image](https://user-images.githubusercontent.com/1342360/68130751-cc62cf80-ff13-11e9-853b-8880588ef126.png)

![image](https://user-images.githubusercontent.com/1342360/68130767-d553a100-ff13-11e9-8c06-d8a52994249c.png)

![image](https://user-images.githubusercontent.com/1342360/68136606-76932500-ff1d-11e9-806d-02553f70799b.png)

Several rooms have disappeared from Riot Web and they aren't coming back even after clearing cache and reloading.

However, this is only for one of my Riot/web clients. On my other computer with the same version of Riot/web, I can see those rooms.

Describe how what happens differs from what you expected.

Logs being sent: yes, from both devices

### Version information

(for both clients)

- **Platform**: web
- **Browser**: Firefox nightly
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Are you sure you're on the latest develop? https://github.com/vector-im/riot-web/issues/11263 claims to be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3584

**Comment by anoadragon453** [comment]
> Are you sure you're on the latest develop? #11263 claims to be fixed by [matrix-org/matrix-react-sdk#3584](https://github.com/matrix-org/matrix-react-sdk/pull/3584)

Yep, Riot tells me I'm running commit https://github.com/vector-im/riot-web/commit/3cabd195d2ed

**Comment by bwindels** [comment]
Does scrolling or resizing the room sub lists affect it in any way?

**Comment by bwindels** [comment]
@anoadragon453 ^

**Comment by anoadragon453** [comment]
> @anoadragon453 ^

I don't *think* so? Unfortunately my test case is now gone and things are working again :/

**Comment by anoadragon453** [comment]
Ohh, I say that but it's happened again with my Brendan PM.

Resizing doesn't seem to fix anything.

**Comment by bwindels** [comment]
@anoadragon453 How about scrolling? And I assume the rooms come back when clearing the filter again? Or are they permanently not shown in Riot?

**Comment by anoadragon453** [comment]
@bwindels They are permanently not shown in Riot.

Brendan is back.

**Comment by anoadragon453** [comment]
Ok, so when I click on him after he's come back, I see him in the sidebar. But then I click to another room and he disappears, lost forever to the sands of time. He's still in breadcrumbs though.

This is an upgraded room btw. Maybe the upgrade room code is hiding this room, thinking it's been upgraded? There's no tombstone in here though.

**Comment by bwindels** [comment]
I see. I'm trying to figure out whether this is a problem with our rendering optimization or something deeper down discarding the rooms. When filtering for Brendan, could you enter this in the console and paste the result here?

```
document.querySelector(".mx_RoomSubList[aria-label='People']").outerHTML
```

**Comment by anoadragon453** [comment]
```
"<div class=\"mx_RoomSubList mx_RoomSubList_nonEmpty\" role=\"group\" aria-label=\"People\" style=\"height: 74px;\"><div class=\"mx_RoomSubList_labelContainer\"><div class=\"mx_RoomSubList_label mx_AccessibleButton\" tabindex=\"0\" aria-expanded=\"true\" role=\"treeitem\" aria-level=\"1\"><div class=\"mx_RoomSubList_chevron mx_RoomSubList_chevronDown\"></div><span>People</span></div><div class=\"mx_RoomSubList_addRoom mx_AccessibleButton\" aria-label=\"Start chat\" role=\"button\" tabindex=\"0\"><div></div></div></div><div class=\"mx_AutoHideScrollbar mx_RoomSubList_scroll mx_AutoHideScrollbar_underflow\"><div class=\"mx_AutoHideScrollbar_offset\"><div style=\"padding-top: 0px; padding-bottom: 0px;\"><div tabindex=\"0\" class=\"mx_RoomTile mx_RoomTile_noBadges mx_AccessibleButton\" aria-label=\"brendan\" aria-selected=\"false\" role=\"treeitem\"><div class=\"mx_RoomTile_avatar\"><div class=\"mx_RoomTile_avatar_container\"><span class=\"mx_BaseAvatar\" disabled=\"\"><span class=\"mx_BaseAvatar_initial\" aria-hidden=\"true\" style=\"font-size: 15.6px; width: 24px; line-height: 24px;\">B</span><img class=\"mx_BaseAvatar_image\" src=\"img/ac3ba8.4aa77aa.png\" alt=\"\" aria-hidden=\"true\" width=\"24\" height=\"24\"></span><img src=\"img/icon_person.6a32066.svg\" class=\"mx_RoomTile_dm\" alt=\"dm\" width=\"11\" height=\"13\"></div></div><div class=\"mx_RoomTile_nameContainer\"><div class=\"mx_RoomTile_labelContainer\"><div title=\"brendan\" class=\"mx_RoomTile_name\" dir=\"auto\">brendan</div></div><div class=\"mx_RoomTile_menuButton mx_AccessibleButton\" role=\"button\" tabindex=\"0\"></div></div></div></div></div></div></div>"
```

**Comment by bwindels** [comment]
Thanks, doesn't look related to `LazyRenderList` fwiw, so https://github.com/matrix-org/matrix-react-sdk/pull/3584 wouldn't have fixed this.

Just to be clear, you expected multiple results under DMs and only see one for the query "Brendan"?

**Comment by anoadragon453** [comment]
Correct.

![image](https://user-images.githubusercontent.com/1342360/68302274-94859480-0099-11ea-9b03-463245644efc.png)

**Comment by turt2live** [comment]
@anoadragon453 it's somewhat hard to see what's going on here without room IDs. The js below is long and awkward, but the idea is that it dumps all the structures involved in the room list and searching algorithm - please run it and let me know what it returns (**it can contain personal information - share via DM or rageshake - do NOT post here with results**).

Change line 88 if "bren" no longer causes the problem.

```js
(function() {
console.log(":: DEBUG BEGIN");

// Dump what the RoomListStore thinks are rooms
let dbg_roomLists = singletonRoomListStore.getRoomLists();
for (let k of Object.keys(dbg_roomLists)) {
    console.log(":: Room list: " + k);
    let rooms = dbg_roomLists[k];
    rooms.map(r => console.log(`::\t${r.roomId} (${r.name})`));
}

// Dump what the MatrixClient thinks are rooms
let dbg_mtxRooms = mxMatrixClientPeg.get().getRooms();
console.log(":: Matrix client rooms:");
for (let r of dbg_mtxRooms) {
    console.log(`::\t${r.roomId} (${r.name})`);
}

// Dump anything that MatrixClient thinks is visible
let dbg_mtxVisibleRooms = mxMatrixClientPeg.get().getVisibleRooms();
console.log(":: Matrix client visible rooms:");
for (let r of dbg_mtxVisibleRooms) {
    console.log(`::\t${r.roomId} (${r.name})`);
}

// Dump anything that doesn't appear in the RoomListStore
console.log(":: Checking that all mtxRooms are in the RoomListStore...");
for (let r of dbg_mtxRooms) {
    let foundInList = null;
    for (let k of Object.keys(dbg_roomLists)) {
        let rooms = dbg_roomLists[k];
        let otherRoom = rooms.find(r2 => r2.roomId === r.roomId);
        if (otherRoom) {
            foundInList = k;
            if (otherRoom !== r) {
                console.warn(`::\tRoom ${r.roomId} in client is a different object from RoomListStore, but the same ID`);
            }
            break;
        }
    }
    if (!foundInList) {
        console.warn(`::\t${r.roomId} was NOT found in RoomListStore's rooms`);
    } else {
        console.log(`::\t${r.roomId} found in ${foundInList}`);
    }
}

// Dump anything visible that doesn't appear in the RoomListStore
console.log(":: Checking that all mtxVisibleRooms are in the RoomListStore...");
for (let r of dbg_mtxVisibleRooms) {
    let foundInList = null;
    for (let k of Object.keys(dbg_roomLists)) {
        let rooms = dbg_roomLists[k];
        let otherRoom = rooms.find(r2 => r2.roomId === r.roomId);
        if (otherRoom) {
            foundInList = k;
            if (otherRoom !== r) {
                console.warn(`::\tRoom ${r.roomId} in client is a different object from RoomListStore, but the same ID`);
            }
            break;
        }
    }
    if (!foundInList) {
        console.warn(`::\t${r.roomId} was NOT found in RoomListStore's rooms`);
    } else {
        console.log(`::\t${r.roomId} found in ${foundInList}`);
    }
}

// Dump anything that is invisible
console.log(":: Checking that all rooms are visible...");
for (let r of dbg_mtxRooms) {
    let found = false;
    for (let r2 of dbg_mtxVisibleRooms) {
        if (r2.roomId === r.roomId) {
            found = true;
            if (r !== r2) {
                console.warn(`::\tRoom ${r.roomId} found in visible list, but different object.`);
            }
        }
    }
    if (!found) {
        console.warn(`::\t${r.roomId} not found in visible rooms list`);
    }
}

// Do the search algorithm ourselves to see what we come up with
let dbg_searchTerm = "bren"; // CHANGE THIS IF YOU'RE LOOKING FOR A DIFFERENT ROOM.
let dbg_matchingRooms = dbg_mtxRooms.filter(r => r.name && r.name.toLowerCase().includes(dbg_searchTerm.toLowerCase()));
console.log(":: Manual search results for: " + dbg_searchTerm);
for (let r of dbg_matchingRooms) {
    console.log(`::\t${r.roomId} (${r.name})`);
}

// Now search visible rooms only (matches essentially what the RoomList does)
let dbg_matchingVisibleRooms = dbg_mtxVisibleRooms.filter(r => r.name && r.name.toLowerCase().includes(dbg_searchTerm.toLowerCase()));
console.log(":: Manual visible search results for: " + dbg_searchTerm);
for (let r of dbg_matchingVisibleRooms) {
    console.log(`::\t${r.roomId} (${r.name})`);
}

console.log(":: DEBUG END");
})();
```

**Comment by turt2live** [comment]
or alternatively if you don't want to leak that massive amount of information: I have two theories about what might be going on. It could be:
1. The room was upgraded or Riot thinks it has been upgraded, and the room list is wrong.
2. The `RoomListStore`'s sorting algorithm is optimizing the room out of a tag.

The idea is that the script will dump all the information that the `RoomListStore` has and what it should have. The key identifiers are actually the two sections towards the end of the dumps:
* If the two searches yield **different** results, it is probably the upgrade bug (the other information can confirm this).
* If the two searches yield the **same** but **incorrect** (missing rooms) results, something is seriously wrong.
* If the two searches yield the **same** and **correct** results, the `RoomListStore` is probably at fault - look for messages like `"$roomId was NOT found in RoomListStore's rooms"` in the logs.

There is some additional information that doesn't cover these 3 cases, such as dumping the same results of the same algorithm in different ways, however that information is there to avoid followup questions depending on the result here.

**Comment by turt2live** [comment]
The DM in question is searchable, considered visible, and known to the client. What's weird is it is not in the RoomListStore, so it is obviously being missed.

**Comment by turt2live** [comment]
Just an update on this: the room is still going missing, but triggering none of the code paths it was previously. Might possibly be a webpack problem.

**Comment by turt2live** [comment]
It's increasingly difficult to narrow this down. It's clearly a bug (we have evidence of this), but we've been unable to replicate it on our side. My current theory is that @anoadragon453's web server is weird, but it being weird shouldn't break specifically the room list because of how webpack chunks work. 

We have a bunch of debugging information though for the next time this happens to someone.

**Comment by turt2live** [comment]
This turned out to be a custom tag mixup: the client that was doing the searching had custom tags enabled, but the tag the DM was in was not enabled, so the room was filtered out. See https://github.com/vector-im/riot-web/issues/11494
