### ISSUE TITLE
Already started direct chats not listed when clicking on a user name in a message

### ISSUE THREAD

**Issue by chimere2** [vector-im/riot-web#11321]
### Description

Clicking on a user address appearing in a message (@user:matrix.org) offers to start a new direct chat but does not list the already started direct chats with that user. The Android application does list already started chats however. 

### Steps to reproduce

- In a room, send a message containing a user address (@user:matrix.org)
- Click on the address
- the right pannel will show info about that user
- the "DIRECT CHATS" section in that right pannel only offers to start a new direct chat and does not list the already started direct chats with that user
- if clicking on the user avatar instead, it works as expected and list already started direct chats

The Android application works as expected and lists the already started direct chats and offers to start a new one.

Log: not sent    

![Screenshot from 2019-11-05 07-13-53](https://user-images.githubusercontent.com/8785152/68207179-69694b00-ff9c-11e9-9b6d-63a107793d74.png)

### Version information

- **Platform**:  desktop

- **OS**: Windows , Linux
- **Version**: 1.5.0

**Comment by Half-Shot** [comment]
I've noticed this one too, it's a major pain. I've noticed that it might be caused in part by when the recipient user migrates their account to a new mxid, and the DM mappings do not update.

**Comment by turt2live** [comment]
We don't have this list anymore.
