### ISSUE TITLE
PPA needs Ubuntu 19.10/Eoan Release file section

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#11327]
Hey Guys,

Just upgraded Ubuntu 19.04 -> 19.10 and the PPA (one linked on the riot.im website) doesn't have a release file for 19.10, naturally I don't get updates now.

Considering 19.10 has been released for weeks now, can we please get the PPA updated with this and future Ubuntu releases too?

Thanks :D

**Comment by fearedbliss** [comment]
Yup I'm in the same situation, using Pop OS 19.10 (Based off Ubuntu 19.10) and there are no official Eoan repos yet.

**Comment by jryans** [comment]
Thanks for letting us know, we'll get it taken care of. If anyone knows a good way to follow when the next Debian / Ubuntu release names are decided, that would be nice to have, so we can catch this in advance.

**Comment by dbkr** [comment]
Done

**Comment by fearedbliss** [comment]
Thank you @dbkr and @jryans !

**Comment by BloodyIron** [comment]
> Thanks for letting us know, we'll get it taken care of. If anyone knows a good way to follow when the next Debian / Ubuntu release names are decided, that would be nice to have, so we can catch this in advance.

You're welcome! I love this response :DDD
