### ISSUE TITLE
new user info panel isn't overflow: auto

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11324]
if you click on someone who has a lot of devices so that the panel is taller than the page, it makes the panel taller than the window and causes the window to scroll, breaking the timeline

**Comment by bwindels** [comment]
Interesting, this is also what broke the FilePanel and NotificationsPanel, even when not having UserInfo enabled.

**Comment by t3chguy** [comment]
It's been in for a month and only just becoming apparent. That's rough :/

**Comment by bwindels** [comment]
I guess nobody has the flag enabled...

**Comment by t3chguy** [comment]
I meant 

> even when not having UserInfo enabled.

**Comment by bwindels** [comment]
Ah, yeah, not sure what made it regress tbh.

**Comment by t3chguy** [comment]
this got fixed
