### ISSUE TITLE
a person can read me, but i cannot read his message

### ISSUE THREAD

**Issue by coding-sys** [vector-im/riot-web#11345]
<i   

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

I write messages to a person.
He can read my messages, but i cannot read his messages
Pleas, can you correct that ?

With other people, that's ok, but not with him

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
@coding-sys please fill in the rest of the template. Also, is the room encrypted?

**Comment by jryans** [comment]
No reply so far... Please reopen if you can supply more detail so we can investigate the issue.

**Comment by coding-sys** [comment]
Hi

I have 2 questions in fact :

i recently started to use riot

I ws integrated in a group

I want to know if i can use my keys to decrypt the previous conversation of
the group, or only the conversation after I intered the chat for the first
time

Thank you

**Comment by jryans** [comment]
It's best to ask general questions like this in Matrix rooms such as #matrix:matrix.org so that others can participate and/or redirect as necessary.
