### ISSUE TITLE
Upgraded rooms appear in Direct Chats under a user's profile

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11342]
### Description

Rooms that have been upgraded still appear in the Direct Chats section under a user's profile.

![image](https://user-images.githubusercontent.com/1342360/68394949-a8e39300-0166-11ea-8cd0-ccac8df26d0b.png)

They should be excluded from the list else the Direct Chats section will just build up with old rooms as PMs get upgraded.

### Steps to reproduce

- Have a PM
- Upgrade it
- Notice that you now have two direct chats with a person appear under their profile, even though the room list only shows one.

Describe how what happens differs from what you expected.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v72.0a1
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
We don't have this list anymore
