### ISSUE TITLE
Update copy in key backup dialog to make it about cross-signing

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11350]
We're going to use the current setup screens for key backup to set up cross-signing (and key backup) but will just need to change the wording as it's currently all key backup specific.

@nadonomy says to poke him and go through and update the copy in the code in real time

**Comment by dbkr** [comment]
I think this is now mostly irrelevant: we have a separate flow for setting up cross signing which should bear at least a passing resemblance to the designs.

**Comment by jryans** [comment]
Agreed, and also we'll be doing an overall copy polish pass today, so let's close this.
