### ISSUE TITLE
Audio and Video call only work in the same LAN, no Debugging Information (e.g. TURN config) given

### ISSUE THREAD

**Issue by benkees** [vector-im/riot-web#11368]
### Description

After having set up an own Matrix- and TURN Server, remote audio and video calls did not work for my users using riot-web.
Analyzing the logs of synapse and TURN didn't gave me a clue what was wrong.
So thoroughly I tested a variety of factors in (almost) any possible permutation:

To get any combination i changed the following For Users Alice and Bob separately:
* Platforms and Client: Debian (riot), Android(app), IPhone(app)
* Network Connection: LAN behind plastic router, wifi behind plastic router, tethering over smartphone
* Server: my Server / Matrix.org

I found out that audio and video calls are only (sometimes) possible if the clients share the very same broadcast domain. In wireshark I could observer UDP Packages being exchanged directly with the local IP. That worked for Alice and Bob both having an account at the same Server or on different servers.
Sometimes it takes more than 20 seconds until audio is audible.

Expecting to have configured my synapse and turn server incorrectly, I finally found out that also Alice and Bob both using Accounts at matrix.org, no Call could be established both not being in the same LAN but behind NAT. Assuming that the matrix.org is configured correctly i guess there must also be a problem with the riot-web - e.g. obeying the TURN setting provided by the server.

There are different levels of fail when the Clients do not share the same broad cast domain:

- at Alices client a Ringing is indicated, it also rings at bobs client, he can klick "answer" but then no audio/video is exchanged
or
- at Alices client ringing is indicated but it doesn't ring at Bobs client
or
- at Alices it doesn't even start to indicate ringing

At any set up interchanging text messages was possible.

I cannot find useful Information in the Clients GUI nor in the Clients log for debugging. 

I'd very much appreciate a hint, where to find useful info if already possible.

### Steps to reproduce

- get two accounts at matrix.org
- set them up on different machines (linux,iphone,android)
- connect devices within same LAN and try to initiate an audio or video call - a call (maybe) works
- connect one of the devices with another connection not using the same Broadcast Domain (LAN) - calls do not work

### Description of what happens differs from expectations

I expect the connection to be established or the clients to give useful info for debugging at the GUI or within the logs. E.g like demanded in ticket #10575 the client should give information about the TURN configuration provided by the Home Server.

### Version information

- **Platform**: web in-browser/desktop (on debian)  iphone (riot 0.10.1 v0.10.1) / android (o.9.4 @ fdroid)

For the web app:

- **Browser**: Chromium73.0.3683.75, Firefox 60.9.0esr (64-Bit)
- **OS**: Debian Jessie, Android 8.0.0, Iphone
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Debian Jessie
- **Version**: Riot-Web 1.5.0

**Comment by jryans** [comment]
Thanks for reporting this issue. I'm adding this to our investigation queue.

**Comment by dbkr** [comment]
I've just tried to reproduce this, unsuccessfully, with Riot desktop on wifi and chrome/firefox tethered through a mobile connection, both users on matrix.org - the call connects fine, with audio.

Calls in riot are all handled by the browser's webrtc stack, so you can look at about:webrtc in firefox or chrome://webrtc-internals for debugging info. Firefox displays the candidates for each side nicely so is a good one to check if you have 'relay' candidates on both sides (if you don't, the client is failing to use the TURN server).

**Comment by benkees** [comment]
@dbkr Could you retest and use one smartphone client, to test the connection? Can you say, where/if the "about:webrtc" line can be put within riot-desktop?

**Comment by dbkr** [comment]
Chrome on wifi to iPhone on cellular data also works fine for me (both accounts on matrix.org)

You'll need to use riot in a browser to use the webrtc debugging tools.

**Comment by benkees** [comment]
@dbkr Thanks a lot. The "about:webrtc" hint helped tremendously to debug WebRTC and TURN setup on my own instance of synapse. Anyway - infos in the Riot GUI are very desirable.

**Comment by jryans** [comment]
@benkees Does that mean you were able to get calls working then?

**Comment by benkees** [comment]
@jryans Yes - On my own server with synapse and coturn I could find a way to configure it, that is working for riot clients behind a nat. I didn't to the verbose check only with matrix.org accounts that i described above. Anyway - From matrix to my instance it was possible to call from and to riot-desktop, iphone client and riot at my server.

**Comment by jryans** [comment]
Okay, that's great to hear! This issue contains both your specific problem as well as general suggesting that there should be more call debugging info. I have extracted the need for debugging info over to [a new issue](https://github.com/vector-im/riot-web/issues/11511), so let's close this one now that your current problem is fixed.

**Comment by matrixtempnew** [comment]
@benkees. Audio and video calls are not working when using different mobile network with riot app. I configure synapse and turnserver in my virtual machine  with NAT. When using same network i can place audio and video call, but it fail to connect on different network.Can you please tell me how to resolve this.let me know if you need any other details.

**Comment by benkees** [comment]
There are many levels on which you can debug the problem. You should check if the server is reachable from outside (ping). If so, can you establish a chat between different accounts on different matrix servers? If so, does it ring on a VoIP call? If so, use e.g. riot.im and analyse the webRTC logs, as described above. Often the problem can be found in the synapse config yaml. You may also want to check federation with this tool: https://federationtester.matrix.org/api/report?server_name=yourserver.com

**Comment by emiliomf** [comment]
I tested with linux mint 19.1 and android. Was able to voice call with wifi (same LAN) but not if android was via mobile data.

**Comment by bilalbilalsheikh** [comment]
> @jryans Yes - On my own server with synapse and coturn I could find a way to configure it, that is working for riot clients behind NAT. I didn't do the verbose check only with matrix.org accounts that i described above. Anyway - From matrix to my instance it was possible to call from and to riot-desktop, iphone client and riot at my server.

kindly explain briefly I can't figure it out please give the solution how to resolve audio, video call problame

**Comment by bilalbilalsheikh** [comment]
> Okay, that's great to hear! This issue contains both your specific problem as well as general suggesting that there should be more call debugging info. I have extracted the need for debugging info over to [a new issue](https://github.com/vector-im/riot-web/issues/11511), so let's close this one now that your current problem is fixed.

I unable to call via a different network on matrix synapse 
kindly give the solution of this problem, it would very help full for me

**Comment by jryans** [comment]
Please open new issues instead of commenting on old ones.
