### ISSUE TITLE
you can't filter the roomlist if the LeftPanel is collapsed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11365]
folks still need ctrl-K to work if the LeftPanel is collapsed. We should pop out the explore/filter buttons or something

**Comment by aaronraimist** [comment]
You can now.

**Comment by turt2live** [comment]
Nope:
![image](https://user-images.githubusercontent.com/1190097/81628447-efd46e80-93bd-11ea-8875-e51970f2eb1c.png)

**Comment by turt2live** [comment]
oh,. CTRL+K does work. neat.
