### ISSUE TITLE
riot clients (android and desktop/windows) do not store server address

### ISSUE THREAD

**Issue by damnms** [vector-im/riot-web#11367]
### Description

I have my own homeserver. Some of my friends, including me, have different accounts on my homeserver. My homeserver is not yet connected to any other server. 
Whenever someone logs in to my homeserver and logs out, the default setting is configured in the client, which means they have to reconfigure the client all the time.

### Steps to reproduce

- log in to any homeserver, lets call this server X
- log out
- log in again to server X -> you have to reconfigure the client

Describe how what happens differs from what you expected.

I would expect that the client stores the last information in the server which was working.

### Version information

- **Platform**: web (in-browser) or desktop? Desktop App (Windows) and Android

For the web app:

- **Browser**: Chromium, Version 80.0.3946.0 (Offizieller Build) (64-Bit)
- **OS**: Windows 10
- **URL**: private homeserver without riot web client

For the desktop app:

- **OS**: Windows 
- **Version**: Version von matrix-react-sdk: <local>
Version von riot-web: 1.5.3
Version von olm: 3.1.3

**Comment by turt2live** [comment]
Currently we have decided that this is the way we want it to work, as logging out should be infrequent.
