### ISSUE TITLE
No sound during calls, unable to connect a call on Firefox

### ISSUE THREAD

**Issue by Csardelacal** [vector-im/riot-web#11366]
### Description

Hello Riot Team,

We are running a server using Modular for small teams, and the service was running perfectly fine until this Monday. We are experiencing the following issues:

- When my colleague is on the browser version (on Firefox) I get an error that reads `(could not connect media)` and then disconnects the call.
- When my colleague is on the desktop client (or a chromium based browser), we get connected, but neither has any sound.

We're running on Debian and Mint and are using Firefox as the web browser. Sound works normally on Telegram and Discord, so it's confirmed that it's not a problem with the machines themselves.

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Chrome,  Firefox Quantum 68
- **OS**: Debian and Mint
- **URL**: modular.im Server

For the desktop app:

- **OS**: Debian and Mint
- **Version**: Debian 10 - Stable repositories

**Comment by Csardelacal** [comment]
Here's the transcript of my conversation with Jason from the Modular team. He seems to believe that the issue is on the Riot side of things.
[No audio during call.txt](https://github.com/vector-im/riot-web/files/3840566/No.audio.during.call.txt)

**Comment by jryans** [comment]
Thanks for the feedback. I'm adding this to our investigation queue.

**Comment by dbkr** [comment]
Looks like this one is actually a bug in the modular setup which I've passed over to the modular team.

**Comment by jaywink** [comment]
Hi @Csardelacal . A fix has been deployed to all Modular hosts. This should hopefully fix the issues you have been experiencing. If not, please re-open this issue, thanks!
