### ISSUE TITLE
Can't cut and paste user pills in the composer

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11378]
Often I'll write a message in one room then realise it's better placed in another. When cutting or copying messages with pills to the clipboard, it seems they're reduced to plaintext. It's a pain to have to go through the message and manually replace the pills after pasting.

**Comment by bwindels** [comment]
Indeed. I suppose we could intercept the `copy` event and add a custom mimetype, e.g. `application/x-cider-composer`, that contains the editor parts as json, and look for that mimetype over text when pasting in cider.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3828

**Comment by turt2live** [comment]
Reports are it doesn't work

**Comment by turt2live** [comment]
Closing because the bug is actually fixed, it just wasn't deployed to /develop. https://github.com/matrix-org/matrix-react-sdk/pull/3848 fixes a regression caused by https://github.com/matrix-org/matrix-react-sdk/pull/3828
