### ISSUE TITLE
Twitch emotes

### ISSUE THREAD

**Issue by Sceluswe** [vector-im/riot-web#11372]
The twitch community is huge and currently (because twitch canceled their own voice application) every streamer and user is building their communities in discord, where they can also use the emotes from twitch in their specific communities. I'd like to see that happen here as well. There's only 2 things keeping me from fully switching to Riot. The first is already a topic and this topic presents the second one.

If possible I'd like the possibility to be able to use twitch emotes in Riot. I don't know if this is possible, but I thought I'd bring it up.

**Comment by turt2live** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/2648

**Comment by Sceluswe** [comment]
It's not, this works against their API, not against ones own local content.

**Comment by turt2live** [comment]
That would still be possible with custom emoji. The source of emoji is largely undefined and could be backed by Twitch if wanted.

**Comment by Sceluswe** [comment]
Alright, as long as that handles channel specific emotes it should do.
