### ISSUE TITLE
Setting `theme` to `custom-<theme name>` doesn't actually default users to the custom theme

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#11370]

**Comment by turt2live** [comment]
@lampholder are the custom themes also set in the config.json?

**Comment by lampholder** [comment]
Yes they are :)

**Comment by turt2live** [comment]
ftr the setting is `default_theme` in the root of the config, not the `theme` under `settingDefaults` (we should deprecate `default_theme`)
