### ISSUE TITLE
Shields artwork is wonky

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11398]
We've lost the border.

It should be:

<img width="879" alt="Screenshot 2019-11-15 at 20 30 37" src="https://user-images.githubusercontent.com/1294269/68973678-cd82df00-07e6-11ea-8957-b90f375f6de3.png">

It is:

<img width="239" alt="Screenshot 2019-11-15 at 20 30 01" src="https://user-images.githubusercontent.com/1294269/68973699-d1aefc80-07e6-11ea-8df8-8ef65cbb1548.png">

**Comment by bwindels** [comment]
Yeah, I took a compromise while trying to keep the icons styleable with css using `mask-image: ...` for theming. I guess I'll need to use two layers to the icon for every color. Just making the red themeable and keep the white hardcoded wouldn't be possible with `mask-image` either ...

**Comment by bwindels** [comment]
After discussing with Nad, we'll make the e2e icons non-themable, so no need for css masks.
