### ISSUE TITLE
Text on the Riot client is way too small. Hurts eyes, cant make it bigger.

### ISSUE THREAD

**Issue by jouks-netlander** [vector-im/riot-web#11402]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by jouks-netlander** [comment]
Linux platform, running Manjaro on KDE.

**Comment by jryans** [comment]
@jouks-netlander Is this in the desktop client or in a web browser?

**Comment by taw00** [comment]
Note: Just tested desktop app on Fedora. No issues here.

**Comment by uhoreg** [comment]
dup of https://github.com/vector-im/riot-web/issues/3160 ?

**Comment by taw00** [comment]
> dup of #3160 ?

Must be. Closed without any comment or context given. Oi. People.
#petpeeve

**Comment by turt2live** [comment]
I was trying to save the extra email notifications to people :(
