### ISSUE TITLE
Key backup claims to be disabled despite being set up 

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#11404]
## Description

I connected my device to an existing key backup, but the room banner keeps saying that it's not set up, and the settings screen says it is not set up.  The console logs say that there is an unhandled rejection.

### Steps to reproduce

- Log in to an account
- go to an encrypted room
- see the backup banner and click on the "Connect this device to Key Backup" button
- enter the passphrase
- go to another encrypted room and see the banner still
- go to user preferences, click on "Security & Privacy", and see that it says that "The device is not connected to backup".

### Version information

- **Platform**: web (/develop)

For the web app:

- **Browser**: Firefox 70.0.0.1
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
```
2019-11-18T03:52:20.166Z I Backup public key REDACTED is trusted locally
2019-11-18T03:52:20.168Z I No usable key backup: not enabling key backup
```

hmm...

**Comment by jryans** [comment]
We seem to have several reports of this, so I suspect this is a regression from merging the JS SDK changes last week. For those affected, it would be helpful to see what's displayed in the key backup area (Settings -> Security & Privacy -> Key backup -> Expand advanced) of Settings.

**Comment by jryans** [comment]
Looking at the path that logs `No usable key backup: not enabling key backup`, it would seem `Crypto.prototype.isKeyBackupTrusted` has changed in some way that it decides your key backup is not trusted any more.

**Comment by jryans** [comment]
It sounds like @dbkr can reproduce on a test account and will be looking into this.

**Comment by dbkr** [comment]
Looks like this when backups should be trusted due to having beeb restored.

**Comment by jryans** [comment]
> Looks like this when backups should be trusted due to having been restored.

As a possibly confounding data point, my main client on matrix.org is trusting the backup via being restored, but key backup appears to working correctly for me on develop.
