### ISSUE TITLE
Tall usernames cause a scrollbar to appear in new user info panel

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11421]
![image](https://user-images.githubusercontent.com/1342360/69101672-29a06a00-0a58-11ea-8a54-b5ec2961445c.png)

### Description

Tall usernames (with strange lettering) can cause a scrollbar to appear.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v72.0a1
- **OS**: Manjaro
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
It looks fixxed
![image](https://user-images.githubusercontent.com/2403652/70227980-761fc100-174b-11ea-863d-1592e1ff0c16.png)
