### ISSUE TITLE
users without avatars have a big empty gap in UserInfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11427]
it should show the circle+plus+letter avatar for consistency, imo

**Comment by ara4n** [comment]
<img width="437" alt="Screenshot 2019-11-19 at 13 57 44" src="https://user-images.githubusercontent.com/1294269/69152612-aa9d4700-0ad4-11ea-8c8b-a8546df10464.png">

^ @kegsay looking a bit blank

**Comment by Kegsay** [comment]
I'm also a bit of an edge case because I have an HTTP URL as my avatar and not an MXC URI, so it's possible the code isn't handling that case (HTTP URLs shouldn't be used).

**Comment by t3chguy** [comment]
Indeed its an edge-case 
![image](https://user-images.githubusercontent.com/2403652/71001808-f9d79700-20d5-11ea-9ad9-ac41e6a50eb0.png)
![image](https://user-images.githubusercontent.com/2403652/71001828-022fd200-20d6-11ea-8726-3e6b77de5917.png)

**Comment by t3chguy** [comment]
@nadonomy how should a User Info right-panel look for users without a set Profile Picture? Omit that section entirely (latest screenshot) or make a circular icon with their initial letter and associated background colour just as their avatar looks in the timeline.

**Comment by t3chguy** [comment]
Nad provided design which may need iterating on of showing the default letter avatar but with a relatively small font so its not to scale.

![image](https://user-images.githubusercontent.com/2403652/71166627-0b8e7b00-224b-11ea-81b5-f2411a248239.png)
