### ISSUE TITLE
riot can somehow get into a state where click-to-ping & quite don't work

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11428]
I just got this on the desktop app: restarting Riot fixed it. It looks like SendMessageComposer somehow maybe had a dispatcher leak: `SendMessageComposer.onAction` was being called with a `this` with a `null` `_editorRef` which caused `insertMention` to throw. Guess this caused the dispatcher to stop processing callbacks, so never getting to the actual SendMessageComposer onAction callback. No idea how it managed to leak though.

**Comment by turt2live** [comment]
in recent problems this usually means the app exploded elsewhere and the click-to-ping feature is collateral damage.

**Comment by t3chguy** [comment]
Assuming fixed
