### ISSUE TITLE
Riot failed to get the public room list. Internal server error

### ISSUE THREAD

**Issue by shreyaspandey** [vector-im/riot-web#11438]
### Description

So I have created a synapse homeserver and started Riot web client.
I can able to create room and add users to it.
But I am not able to find any rooms under matrix.org.

![image](https://user-images.githubusercontent.com/8277155/69190821-39b75880-0aef-11ea-9e63-409ce40af587.png)

I checked on the internet and it was a bug which has been fixed but I am still getting this error.

Also, when I am trying to search for any well known matrix room it shows below error.
![image](https://user-images.githubusercontent.com/8277155/69190736-04ab0600-0aef-11ea-95ae-fd78c0300da3.png)

### Version information

- **Platform**: web (in-browser) 

For the web app:
Synapse version-1.5
- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: https://riot.im/app/#/room/#shreyas-herndon:herndon.nvhosted.net

[New Microsoft Word Document (3).docx](https://github.com/vector-im/riot-web/files/3866268/New.Microsoft.Word.Document.3.docx)

**Comment by turt2live** [comment]
Your server is not configured with valid certificates - create an account on matrix.org and visit #synapse:matrix.org to get help fixing the problem.
