### ISSUE TITLE
Widgets can no longer access people's microphones (Jitsi)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11432]
This feels important.

**Comment by turt2live** [comment]
I can't reproduce this now :|

It seems great - I can hear my own voice and everything. Possibly a browser update unbroke it?

Tested Chrome, Firefox, and Desktop on Windows.

**Comment by jellykells** [comment]
I tested the latest versions of Vivaldi, Firefox, and Icecat on Linux. The issue does not occur in Firefox.
