### ISSUE TITLE
Federation Issue:- Not able to federate between two synapse homeserver.

### ISSUE THREAD

**Issue by shreyaspandey** [vector-im/riot-web#11439]
### Description

I have created two synapse homeserver which are working perfectly as a stand-alone thing.
I can add clients, create rooms and exchange messages.

So I went a step further and try to federate between the two.
I have certificate for both the server which is not from Lets Encrypt.
There is no delegation thing as such but I am reverse-proxying using Nginx as webserver.

I tried to connect to a user from one home server to another homeserver but it throws an error saying there is no such user or fail to create room.
![image](https://user-images.githubusercontent.com/8277155/69191999-b0555580-0af1-11ea-8936-24b1a580b6d6.png)

I tried federation testing for the two homeserver and below are the links for them:-
https://federationtester.matrix.org/api/report?server_name=herndon.nvhosted.net
https://federationtester.matrix.org/api/report?server_name=matrix.nvhosted.net

Noticeably the error is;-
WellKnownResult": {
    "m.server": "",
    "result": "Get https://herndon.nvhosted.net/.well-known/matrix/server: x509: certificate signed by unknown authority"
  }

I have not set Wellknown page as I am not delegating.
Also,I havent set acme ON because I have my own certificates.

I ran into below link where it is advised to setup acme.
But I dont think it is required in my case.I tried acme as well but it didnt work.
https://github.com/matrix-org/synapse/blob/master/docs/MSC1711_certificates_FAQ.md#configuring-certificates-for-compatibility-with-synapse-100

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome
- **OS**: First homeserver is on Ubuntu and other one is on Centos
- **URL**:  / riot.im/app /

**Comment by turt2live** [comment]
as mentioned on your other issue, https://github.com/vector-im/riot-web/issues/11438#issuecomment-555741889 , you should visit #synapse:matrix.org for support with your homeserver.
