### ISSUE TITLE
reaction emoji picker mangles rainbow-flag emoji

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11446]
either twemoji is failing or the picker is picking the wrong combining combo somehow. twemoji gets it right though, as per 🏳️‍🌈, but it's presented as a separate flag & rainbow emoji in @tulir's picker

**Comment by ara4n** [comment]
at least in FF 70 on Catalina.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/1294269/69263138-9fbde180-0bbc-11ea-974f-e71bf81bb2b8.png">

**Comment by tulir** [comment]
Weird, that's expected if the emoji font doesn't support some multi-part emoji, but that shouldn't be the case here. I can reproduce the problem with twemoji, but it works fine with noto color emoji.

**Comment by ara4n** [comment]
twemoji renders it right in the timeline itself though.  in the timeline it comes out as:

`f0 9f 8f b3 ef b8 8f e2 80 8d f0 9f 8c 88` (aka 🏳️‍🌈)

in the emoji picker it comes out as:

`f0 9f 8f b3 e2 80 8d f0 9f 8c 88` (aka 🏳‍🌈)

...so I think you're feeding your emoji picker the wrong kind of combiner (at least 'wrong' in terms of what i implemented in twemoji ;P)
