### ISSUE TITLE
Settings local echo seems to be unreliable

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11443]
inexplicably, when setting one of the normal themes (ie. 'light' or 'dark'), SettingsStore.getValue() appears to return the local echo value correctly. When setting a custom theme (eg. 'custom-Dark Blue') the local echo value is undefined.

I've had to add the `forceTheme` param to the `recheck_theme` dispatch to work around this.

**Comment by turt2live** [comment]
I don't know what to think of this - the exact same local echo wrapper is in place for both paths...

After all the theme changes land I'll try to take a look and see if it's obvious.

**Comment by t3chguy** [comment]
I think I solved this by accidentally finding a false-cache-miss in LocalEchoWrapper
