### ISSUE TITLE
Scalar doesn't work with Chrome 79 (beta at the moment)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11459]
```
618:51:16.945 A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
18:50:42.020 /app/#/room/!redacted:1 A cookie associated with a cross-site resource at https://scalar.vector.im/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

Widgets sometimes say `18:50:42.173 Widget.js:181 Content is not embeddable Forbidden - Invalid Scalar access token` (probably due to lack of cookie) but appear to still be receiving the token via query string.

Tested by a third party: Chrome 79 on riot.im/app 

Chrome 79 is due for January 2020.

**Comment by gordol** [comment]
Even Google's own extensions are broken by this change. For example, the hangouts extension quits working in Chrome 80 due to the SameSite changes.

**Comment by jaywink** [comment]
@turt2live a new Scalar has been deployed which adds `SameSite=None;Secure` to ensure Chrome should not start blocking widgets. Confirmed with Chrome 80 Beta.
