### ISSUE TITLE
Encryption decoration in room titles is too big

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11454]
Should match the designs/composer icon sizes.

**Comment by bwindels** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3641 made them smaller in the composer, but the design also shows them smaller (and ideally overlaid on the room avatar) in the design as well.

**Comment by nadonomy** [comment]
At the risk of opening pandoras box on release blockers, if we place it over the avatar then we'd also need to do that consistently in the room list.

@bwindels just to unblock release I think for now we could just reduce the size of the icon in its current place (to 16px or 24px)— does that sound good to you?
