### ISSUE TITLE
Volume is not respected when taking photo

### ISSUE THREAD

**Issue by pfournier-ETL** [vector-im/riot-web#11455]
### Description

My phone was in vibration mode (no sound).  When I took a photo to send, a loud camera shutter sound was heard.

### Steps to reproduce

1. Make sure phone speaker is muted
2. Click text field to send a message
3. Click the paper clip
4. Select "Take photo"
5. Take the photo

### Version information

0.9.8 (Android)

**Comment by t3chguy** [comment]
This is the riot-*web* repo, perhaps you want github.com/vector-im/riot-ios or github.com/vector-im/riot-android or github.com/vector-im/riotx-android
