### ISSUE TITLE
Upgrading invite only room did not invite users

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#11464]
Upgraded an invite only room from v1 to v5 (Synapse v1.5.1). Room upgrade went fine. Went to my other account also in the same room (on another server). Saw the notice about upgrade. Clicked it and got "you have not been invited to this room".

Retried a few times in hope of invite appearing. Ended up inviting all the users to the new room manually.

ping @turt2live

**Comment by turt2live** [comment]
This is unfortunately a known limitation, and fixing it can introduce a few scary vulnerabilities to the room. The upgrade warning does say that people will not be invited.
