### ISSUE TITLE
Gnome Files shows nothing when attempting to attach files on Electron.

### ISSUE THREAD

**Issue by hendersonreed** [vector-im/riot-web#11482]
### Description

When attaching a file through the paperclip icon, the file manager (Nautilus, in Gnome) when opened shows no files or directories in the home directory or under the Recent tab. In the root directory and lower, all that shows up is empty directories.

I verified this wasn't a permissions issue by chmoding files in the home-directory, and still nothing was showing up.

**When running the web version (through Firefox), the file selection panel opens and shows files as normal**, and navigation works as expected, making me think this isn't necessarily a Gnome issue. I also searched through their repositories for issues related to this, and wasn't able to find one.

### Steps to reproduce

Describe how what happens differs from what you expected.

- From any room or chat, click the paperclip icon.

Logs being sent: yes

It's not a super valuable screenshot, but here:

![Screenshot](https://user-images.githubusercontent.com/18652932/69470111-4afba180-0d49-11ea-87cd-585c5c55ea57.png)

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop aka Electron

For the desktop app:

- **OS**: Fedora 30
- **Version**: 
```
matrix-react-sdk version: <local>
riot-web version: 1.5.3
olm version: 3.1.3
```

**Comment by t3chguy** [comment]
I wonder if whatever fedora build of riot you're running is configured to run in a chroot or sandbox

**Comment by hendersonreed** [comment]
Ah, that's a good idea. The fedora version is distributed via flatpak, which isn't distributed by Vector.

Here's the relevant flathub page. https://flathub.org/apps/details/im.riot.Riot

**Comment by hendersonreed** [comment]
@t3chguy was right, it was all down to flatpak permissions. 

I was able to fix it by giving the application permission to my entire homedir, using `flatpak --user override --filesystem=home im.riot.Riot`. This is probably isn't best practice, but it fixed the problem.

Since the bug sn't the fault of Riot, I'll go ahead and close this issue.
