### ISSUE TITLE
Consider putting shield icons on bottom right of room avatar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11491]
### Description

I think the shield in the room name currently looks a bit odd size-wise. Also it takes up some horizontal space that could be useful in compressed windows.

I propose moving the shield from beside the room avatar to just on top of it. This also helps signify that the shield is referring to the room itself, and that it contains unverified users. I think this feeling particularly works well on 1-1 chats.

Before:

![image](https://user-images.githubusercontent.com/1342360/69537843-d7d87200-0f78-11ea-9987-151acca142fc.png)

After:

![image](https://user-images.githubusercontent.com/1342360/69537691-8d56f580-0f78-11ea-8649-bbdfe9f3d33e.png)

This would also allow us to move the room name over a bit as well.

**Comment by ara4n** [comment]
the current implementation is a WIP of the final design, which is at https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing, and behaves as you've suggested.

**Comment by anoadragon453** [comment]
Cool, looking forward to it :)

(That link doesn't seem to be public btw).
