### ISSUE TITLE
C+P in text composer loses pills from the copied source

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#11498]
### Steps to reproduce
- Type a message with a pill in the composer
- Cut the message before sending
- Paste it back to the composer

-> The pill is gone.

I think it used to work.

### Version information

- **Platform**: web
- **Browser**: Chrome Version 78.0.3904.108
- **OS**: MacOS
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3828/ supposedly fixed this but it doesn't seem to work for me.

**Comment by turt2live** [comment]
hmm... let's move this over to https://github.com/vector-im/riot-web/issues/11378 and reopen it for now.
