### ISSUE TITLE
Unable to load edit history for a message: refNode is undefined

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11497]
### Description

I'm unable to load the edit history of [a message](https://matrix.to/#/!xYvNcQPhnkrdUmYczI:matrix.org/$DMS0EwTPpxVLx8rzFyzhMNlhXU1ATrHwfii9wLvopwk?via=matrix.org&via=maunium.net&via=feneas.org) in an unencrypted room (TWIM). Refreshing does not fix the issue.

### Steps to reproduce

- Try to open the edit history for a message
- Server returns a 200 on the network request
- Message history dialog appears with a loader and then just suddenly closes

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v72.0a1
- **OS**: Debian
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This happens when a list has its items changed (added, removed, indentation).
