### ISSUE TITLE
Duplicate users in search

### ISSUE THREAD

**Issue by dmi-michael** [vector-im/riot-web#11501]
![Riot_Duplicate](https://user-images.githubusercontent.com/49456698/69567711-e1f57300-0f6e-11ea-8e6d-65e8bcdcfd23.JPG)

We are currently seeing Users being duplicate din the User Directory when searching for a user to start a chat with or inviting to a room. This occurs in all versions of Riot tested, including Browser, Desktop and Android. We started noticing this issue in 1.4+ versions; if we revert to 1.3.6 or below the issue goes away

**Comment by turt2live** [comment]
Are you using ma1sd or mxisd as your identity server?

**Comment by dmi-michael** [comment]
> Are you using ma1sd or mxisd as your identity server?

. . . actually, yes. I didn't even think to check that repo for the issue. Has this been documented?

**Comment by turt2live** [comment]
Yup :)

https://github.com/vector-im/riot-web/issues/11028

The short version is that your identity server is publishing multiple results (which is really shouldn't be) and riot doesn't combine them anymore (but it should).
