### ISSUE TITLE
Match system dark mode setting should be called Match system theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11505]
Also if an existing theme is explicitly selected, that should be used instead

**Comment by strixaluco** [comment]
And the issue is that this setting doesn't really match system dark mode. Tested on Debian Buster with GNOME 3.30.2 and Debian Sid with GNOME 3.34

**Comment by turt2live** [comment]
@strixaluco that sounds like a different issue if it's not matching the system theme.

**Comment by strixaluco** [comment]
@turt2live that's true. Opened a separate ticket #11509

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3673
