### ISSUE TITLE
Non-translatable `callType` name in src/TextForEvent.js

### ISSUE THREAD

**Issue by fenuks** [vector-im/riot-web#11507]
### Description

Hello,
matrix-react-sdk contains hardcoded `callType` name in [src/TextForEvent.js](https://github.com/matrix-org/matrix-react-sdk/blob/21a15fdcb4ec1098df2a62ea3fabea5812c7dbd5/src/TextForEvent.js#L361).

It could be easily fixed like so (I would submit patch as merge request, but I wish not to sign DCO with my real name as it is required per CONTRIBUTING.md, especially for such trivial change…):

```diff
diff --git a/src/TextForEvent.js b/src/TextForEvent.js
index e3c249df3..6607383ab 100644
--- a/src/TextForEvent.js
+++ b/src/TextForEvent.js
@@ -358,13 +358,13 @@ function textForCallHangupEvent(event) {
 function textForCallInviteEvent(event) {
     const senderName = event.sender ? event.sender.name : _t('Someone');
     // FIXME: Find a better way to determine this from the event?
-    let callType = "voice";
+    let callType = _t('voice call');
     if (event.getContent().offer && event.getContent().offer.sdp &&
             event.getContent().offer.sdp.indexOf('m=video') !== -1) {
-        callType = "video";
+        callType = _t('video call');
     }
     const supported = MatrixClientPeg.get().supportsVoip() ? "" : _t('(not supported by this browser)');
-    return _t('%(senderName)s placed a %(callType)s call.', {senderName, callType}) + ' ' + supported;
+    return _t('%(senderName)s placed a %(callType)s.', {senderName, callType}) + ' ' + supported;
 }
 
 function textForThreePidInviteEvent(event) {
```

**Comment by turt2live** [comment]
we should probably just make the whole string translatable rather than using the callType variable

**Comment by fenuks** [comment]
It might be a good idea, due to inflection in some languages.

If I may touch another question, assuming that prune-i18n.js script is correct, it seems that many translation strings in JSON files are no longer required, for some languages more than 400 of these are removed.

**Comment by turt2live** [comment]
We rarely run the script for some reason, so removing 400+ strings sounds accurate.

**Comment by fenuks** [comment]
You are member, could you please run the script and update translations? It's waste of translators' time to work on strings that are in fact not used by SDK.

**Comment by turt2live** [comment]
I've reported it as a different issue to avoid making this issue harder to follow: https://github.com/vector-im/riot-web/issues/11539
