### ISSUE TITLE
"Autoplay GIFs and videos" option does not work when homeserver's media repo serves animated thumbnails

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11519]
### Description

From what it looks like, if the option "Autoplay GIFs and videos" is off, Riot will serve the thumbnail of a gif instead of the gif itself:

https://github.com/matrix-org/matrix-react-sdk/blob/d4d51dc61f75bcaab50184e066da23fc5cabfbdc/src/components/views/messages/MImageBody.js#L469-L477

While this is successful if your homeserver has a media repo which does not animated thumbnails, if you *do* have one that does (such as @turt2live's popular [matrix-media-repo](https://github.com/turt2live/matrix-media-repo/)) then you will be shown a thumbnail that's still animated. 

![Peek 2019-11-26 18-36](https://user-images.githubusercontent.com/1342360/69662099-a4324080-107b-11ea-8172-342d189fd5e8.gif)

### Steps to reproduce

- Use a homeserver with animated media thumbnails
- Send a gif in the room
- Roll over the gif with your mouse and see that it animates no matter what

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v72.0a1
- **OS**: Debian
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Animated thumbnails are a non-standard feature. Proper spec is needed in this area.
