### ISSUE TITLE
Ugly [object Object] leak in error on inviting lots of people

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11515]
<img width="756" alt="Screenshot 2019-11-26 at 15 06 36" src="https://user-images.githubusercontent.com/1294269/69645723-8a363500-105e-11ea-84f2-91c27d62bfa0.png">

...after trying to invite 20 people into an upgraded room.

**Comment by turt2live** [comment]
@ara4n can you rageshake if you still have the logs please?

**Comment by turt2live** [comment]
This is coming from the MultiInviter, and clearly the `<br/>` joining doesn't work anymore.

**Comment by turt2live** [comment]
actually this is the BR
