### ISSUE TITLE
Not updating to 1.5.4 - Windows

### ISSUE THREAD

**Issue by IamUSER** [vector-im/riot-web#11523]
### Description

1.5.4 available. App keeps pulling 1.5.3. 1.5.4 not available for download on Riot.im or Github.

### Steps to reproduce

Riot app in perpetual update loop. Open Riot and hit update. Riot reopens and says update is available again.

This is just to inform you.

Logs being sent: yes/no

### Version information

1.5.3 to 1.5.4 update.

- **Platform**: web (in-browser) or desktop?

Windows 64 and 32 bit.

**Comment by turt2live** [comment]
This should be fixed in our next release. I'm going to leave this open so we stop getting duplicates reported (hopefully).

**Comment by IamUSER** [comment]
Thank you! I did look at open issues before posting. Sorry for the repeats!

**Comment by jryans** [comment]
1.5.5 has now been released, which should resolve this update loop.
