### ISSUE TITLE
Seshat doesn't log anything when it loads?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11528]
The only evidence i have that seshat might be working is `EventIndex: Adding initial crawler checkpoints` in the console logs. It would be super useful to have a bit more logging...

**Comment by poljar** [comment]
This has been addressed [here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/indexing/EventIndex.js#L40) and [here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/indexing/EventIndexPeg.js#L44) for the error cases.

Feel free to re-open if more is wanted.
