### ISSUE TITLE
Riot stuck in update loop

### ISSUE THREAD

**Issue by martinvonwittich** [vector-im/riot-web#11522]
### Description

I've gotten two reports from users in our company today that Riot keeps reporting "A new version of Riot is available", even after it has been updated. I'm using Linux in the office and that doesn't seem to be affected, but now that I'm at home on Windows, I'm seeing this too.

### Steps to reproduce

- Open Riot
- Note the "A new version of Riot is available" message and click on Update
- Riot will restart
- The "A new version of Riot is available" will reappear soon

You can manually trigger the issue by checking for updates in Help & About.

### Version information

- **Platform**: desktop
- **OS**: Window
- **Version**: 1.5.4

matrix-react-sdk version: <local>
riot-web version: 1.5.4
olm version: 3.1.3

**Comment by turt2live** [comment]
This should be fixed for our next release.
