### ISSUE TITLE
Opening and closing widgets can cause them to show a blank screen

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11536]
This is a recurring regression. See https://github.com/vector-im/riot-web/issues/6707 for the last time.

Likely to be highly related to https://github.com/vector-im/riot-web/issues/10499

**Comment by rxl881** [comment]
Seeing the same with Modular widgets, for example Etherpad too

**Comment by rxl881** [comment]
I actually think that this might be related to a failure to get the widget capabilities. Seeing the following for an Etherpad widget, for example: 
![Screenshot 2019-11-27 at 16 09 55](https://user-images.githubusercontent.com/6763606/69740177-e36e9900-1130-11ea-9b56-5c7d2cb11aa0.png)

**Comment by turt2live** [comment]
It's because our persistent app stuff is failing to re-mount the correct widget I believe. A side effect of that is the capabilities exploding.

**Comment by rxl881** [comment]
I'm also seeing invalid scalar token errors (which I would not expect), as I haven't changed anything, and nothing has changed in scalar (to my knowledge). 

Could the persistant app stuff also be affecting cookie loading (or could that be linked to something else, e.g. CSP changes)?

**Comment by turt2live** [comment]
> Could the persistant app stuff also be affecting cookie loading (or could that be linked to something else, e.g. CSP changes)?

Yes, it affects the whole bootstrap process.

**Comment by turt2live** [comment]
@rxl881 your etherpad problem might be something slightly more subtle, actually. If you've changed integration managers or your Scalar token is no longer valid then there's a good chance it won't work. If that's the case, that would be a different (new) issue.

**Comment by rxl881** [comment]
@turt2live -- Yeah, but I really haven't changed integration managers or done anything else that would have (should have) invalidated the scalar token recently. Definitely still possible to be something unrelated in scalar though.

@makyo -- can you please check that (existing) scalar Etherpad and Grafana widgets are working for you, just to confirm the general breakage case, and to determine if there is any evidence that there is something additional, Scalar-specific going on (and if so log it as a new issue)?
