### ISSUE TITLE
Self messaging

### ISSUE THREAD

**Issue by theoden8** [vector-im/riot-web#11541]
**Is your suggestion related to a problem? Please describe.**
Sometimes, it's convenient to share a link across your devices.

**Describe the solution you'd like**
Similar to how there's a special "saved messages" on Telegram or Signal, it would seem intuitive if there was a similar default option to create or use an encrypted conversation with oneself.

**Describe alternatives you've considered**
You already can do that by creating a conversation with one person.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4933
