### ISSUE TITLE
Mobile setup page still references identity servers

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11543]

**Comment by olmari** [comment]
For example our HS has been setup _not_ to refer any IS on everywhere possible, from .well-knowns to Synapse to Riote-web... relevant exerpt from our "local" riot-web config.json:
```
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.hacklab.fi",
            "server_name": "hacklab.fi"
        }
...
    "disable_3pid_login": true,
}
```

yet on mobile browsers on our riot-web url gives:

![Screenshot_20191128-011333_Vivaldi](https://user-images.githubusercontent.com/5422161/69765822-2c990a00-117e-11ea-993b-8126a949536b.jpg)

While page is more-or-less informational, it's still false information :)

Riot-web version: 1.5.5
