### ISSUE TITLE
Riot-web does not start

### ISSUE THREAD

**Issue by monochromec** [vector-im/riot-web#11568]
The error message is similar to  #8451 but is displayed *right* after launching the client.

Platform is Windows 10 Pro, version 1909. This error message only occurs in the 64 bit version, 32 bit version works as expected.

Steps to reproduce:
1) Install 64 bit client
2) Launch client

More than happy to provide more information, just let me know.

**Comment by turt2live** [comment]
@monochromec which version precisely are you trying to use? What's the exact error you're seeing?

**Comment by monochromec** [comment]
Reinstalling the client solved the problem. Closing the ticket.
