### ISSUE TITLE
Riot doesn't send the authorization token to the /_matrix/identity/v2/account endpoint

### ISSUE THREAD

**Issue by ma1uta** [vector-im/riot-web#11560]
### Description

I setup the IS. After that try to invite other users but Riot write "something went wrong".

### Steps to reproduce

- setup an identity service with support of the MSC2140 (v2)
- invite users by email

First Riot sends the request to the `/_matrix/identity/v2/account/register` endpoint with correct data.
The identity service response with the authorization token.
After that Riot sends the request to the `/_matrix/identity/v2/account` endpoint without any tokens.
But this endpoint (https://matrix.org/docs/spec/identity_service/r0.3.0#get-matrix-identity-v2-account) requires the authorization.

This issue present in the Riot 1.5.5 and all previous versions.

- **Platform**: web and desktop.

**Comment by turt2live** [comment]
@ma1uta I can't reproduce this with ma1sd 2.2.0-rc3 or on vector.im. There was a bug in a previous version of Riot - are you sure this was tested against 1.5.5?

**Comment by jryans** [comment]
Also what homeserver version is being used? There are various homeserver feature flags that affect which code path is taken...

**Comment by ma1uta** [comment]
@turt2live Ok, I will check it.

**Comment by ma1uta** [comment]
Yes, it is fixed in the Riot 1.5.5. Thanks.
