### ISSUE TITLE
CIDER: Colon after pill is missing

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11563]
Old composer automatically inserted a : after the pill when you click to ping someone. I keep manually inserting it but it would be really nice to get back.

**Comment by t3chguy** [comment]
Looks like a regression: https://github.com/vector-im/riot-web/issues/10680

**Comment by aaronraimist** [comment]
and actually I just realized this is Safari specific. It appears to work in Firefox.

**Comment by aaronraimist** [comment]
Hmm toggling the new composer off and on gives me colons back? Maybe just some borked something?

**Comment by aaronraimist** [comment]
Closing for now

**Comment by aaronraimist** [comment]
Nope this is still an issue.

It works correctly when there is nothing in the composer but often I write out a message and then realize I need to mention the person so I put the cursor at the beginning of the composer and click to ping. The composer I guess is trying to be smart and not put a colon since I've written stuff but since my cursor is at the start, I actually do want a colon.
