### ISSUE TITLE
Joining a room permalink doesn't direct ?via correctly

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11578]
`/join https://matrix.to/#/!whatever:example.org?via=example.org` should append a `server_name` of `example.org`, but instead it tries to join the room ID with query string

**Comment by t3chguy** [comment]
It *should* https://github.com/matrix-org/matrix-react-sdk/blob/d4d51dc61f75bcaab50184e066da23fc5cabfbdc/src/SlashCommands.js#L469

**Comment by t3chguy** [comment]
nvm thats a different codepath

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/d4d51dc61f75bcaab50184e066da23fc5cabfbdc/src/SlashCommands.js#L498

**Comment by turt2live** [comment]
it's probably something with the parsePermalink function, given the via stuff shows up in the room ID as encoded.

**Comment by turt2live** [comment]
or maybe we obliterated support for query strings in the js-sdk, though I do hope that isn't the case.

**Comment by t3chguy** [comment]
imma have a small dig at this

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/70004434-29c35e00-155e-11ea-8b7f-ca8007e036d3.png)

**Comment by t3chguy** [comment]
So turns out the codepath only worked for event permalinks and even then only worked for one via=, multiple via's would not strip the `&`
