### ISSUE TITLE
Create riot.im/user/dm links to start DMs straight away

### ISSUE THREAD

**Issue by frandavid100** [vector-im/riot-web#11572]
When I give someone the link to my user in Riot (https://riot.im/develop/#/user/@frandavid100:matrix.org) so that they can start a conversation with me, they still have to find and click the "direct message" button. Which might be confusing for new users, since the button doesn't really stand out:

![image](https://user-images.githubusercontent.com/694794/69903678-01403600-139d-11ea-8a6e-3749392c0bc8.png)

I'd like to be able to give them a link similar to this, that would start a new DM with me (or ideally open the most recent DM, if it exists) straight away:

https://riot.im/develop/#/user/@frandavid100:matrix.org/dm

Would that be possible?

**Comment by t3chguy** [comment]
https://riot.im/develop/#/user/@frandavid100:matrix.org?action=chat is what you want :)

**Comment by martindale** [comment]
I'm getting a re-invite to the same room, which cannot be joined, when using `?action=chat` — is there a way to force the creation of a new room?
