### ISSUE TITLE
macOS text replacements are handled incorrectly

### ISSUE THREAD

**Issue by kiliankoe** [vector-im/riot-web#11575]
### Description

macOS supports system-wide text replacements, which are finally supported in the current versions of Riot Desktop 🎉 
Unfortunately they're being handled a bit differently than elsewhere in that they're *always* expanded, not just on word boundaries. This is very annoying when having set up replacements for short words, which are also parts of other words.

For example I have `eig` set to complete to `eigentlich`. In other text fields I can still type words such as `eigener`. In Riot this is not possible currently without explicitly hitting <kbd>esc</kbd> after `eig`.

### Steps to reproduce

- Set up a text replacement in system settings
- Type replacement string in Riot composer without a trailing word boundary (punctuation or spaces).

### Version information

- **Platform**: desktop
- **OS**: macOS 10.15.1
- **Version**: 1.5.5

**Comment by aaronraimist** [comment]
Can someone add a composer label to this?

It seems to be an issue with the new composer (the old composer is even more broken). Other text fields in the app work fine (like the message search field and room filter field).

**Comment by zerowidthzen** [comment]
Riot in chrome-based browsers is unusable for me due to this issue

**Comment by kiliankoe** [comment]
I just realized this appears to be fixed, I'm no longer encountering the issue and everything works as expected 🎉
