### ISSUE TITLE
If you start typing a message with a / you then can't make it not a command

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11580]
I started typing `/var/log` realizing that riot would consider it a command, so added back ticks and some words in front. Upon sending, my message is swallowed. Alt+Up to get the message back does the same thing. I had to re-type the whole message

**Comment by aaronraimist** [comment]
Duplicate of #4630

**Comment by turt2live** [comment]
Nope, this is different. When fixing the leading slash problem, the message is swallowed.
