### ISSUE TITLE
Electron nightlies

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11586]
* [ ] Set up a buildkite job to run at 9am UK time Mon-Fri (or every day if that's difficult). Time subject to opinions.
* [ ] Job generates *unsigned* tarballs and electron builds, similar to https://github.com/vector-im/riot-web/issues/11585
* [ ] Job automatically publishes to packages.riot.im (or whatever host we end up deciding upon).
* [ ] Use a different icon in the builds
* [ ] Use a different data directory for these builds.

We are using a separate binary for ease of deployment and for some semblance of safety. 

Depends upon https://github.com/vector-im/riot-web/issues/11582 and https://github.com/vector-im/riot-web/issues/11585

**Comment by turt2live** [comment]
Fixes https://github.com/vector-im/riot-web/issues/8299

**Comment by aaronraimist** [comment]
Different icon is https://github.com/vector-im/riot-web/issues/12709

**Comment by jryans** [comment]
@turt2live Unsure if this meta issue still has value, what do you think? We've done some of the things, but in different ways, and other parts are tracked separately in different issues.

**Comment by turt2live** [comment]
Yea, let's use labels.
