### ISSUE TITLE
inconsistent/confusing terminology: "recovery passphrase" (German: Wiederherstellungs-Passphrase)

### ISSUE THREAD

**Issue by jans23** [vector-im/riot-web#11593]
I'm using latest Riot (it's the same for Android, Web and desktop) in German. I don't know if this issue exists for English as well. Riot uses a confusing terminology: For protecting backups the user should enter a passphrase (German: **Passphrase**). Then users should make a copy of the recovery key (German: **Wiederherstellungsschlüssel**). But when logging in from a new device the user should enter a recovery passphrase (German: **Wiederherstellungs-Passphrase**). So it's unclear if this refers to **Wiederherstellungsschlüssel** or (backup) **Passphrase**. Instead the dialogue at the new device should be changed from "Wiederherstellungs-Passphrase" to "Wiederherstellungsschlüssel". This simple change would improve the usability for new users significantly.

![1  Passphrase](https://user-images.githubusercontent.com/1450547/70030628-e7277300-15a9-11ea-9584-d5bf0ae64221.png)
![2  Wiederherstellungsschlüssel](https://user-images.githubusercontent.com/1450547/70030629-e7277300-15a9-11ea-9a29-da2d4823c085.png)
![3  Wiederherstellungs-Passphrase](https://user-images.githubusercontent.com/1450547/70030630-e7277300-15a9-11ea-8be7-785f20fddd85.png)

**Comment by dbkr** [comment]
https://translate.riot.im/ is the place to fix this: our translations are contributed by the community

**Comment by jans23** [comment]
I just checked the English dialogue which states "Recovery Passphrase". Therefore it's not a translation issue but an issue of the original (English) terminology.

**Comment by aaronraimist** [comment]
Related/dup: #9437

**Comment by jryans** [comment]
We've recently standardised the English text to say "recovery passphrase" where intended. Translations may take a bit to update.
