### ISSUE TITLE
Firefox spams CSP warnings

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11610]
Content Security Policy: Directive 'child-src' has been deprecated. Please use directive 'worker-src' to control workers, or directive 'frame-src' to control frames respectively.

**Comment by aaronraimist** [comment]
@jryans fixed in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1486331

child-src is no longer deprecated https://github.com/w3c/webappsec-csp/pull/313
