### ISSUE TITLE
Feature request: More details of Users like deaprtment, location, function, for internal use

### ISSUE THREAD

**Issue by ppabst** [vector-im/riot-web#11612]
Hello,
we use riot.im for the internal communilation of our employees. 
Many employees do not know each other personally or even work in a different location. 
In the riot.im currently only the name, mail and phone can be read out via LDAP. 
It would be helpful if additional information about the employee from the LDAP can be displayed in the rioit.im, such as: Department, location, function

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/1401
