### ISSUE TITLE
Old Matrix HQ Room still shows up in room list

### ISSUE THREAD

**Issue by BrenBarn** [vector-im/riot-web#11622]
On Riot Web, in Vivaldi on Linux, two Matrix HQ rooms appear in the room list.  One appears to be the old room.

![double_matrix_hq](https://user-images.githubusercontent.com/1439047/70357023-b43fe200-182a-11ea-8dbb-03ca7cd9b3b3.png)

**Comment by aaronraimist** [comment]
@turt2live Can this get a roomupgrades label?

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/11724
