### ISSUE TITLE
ephemeral messages - Self destructing events feature?

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riot-web#11621]
**Is your suggestion related to a problem? Please describe.**
Ephemeral messages or self destructing chat/salon is a requested feature by people for whom privacy is a matter of life

**Describe the solution you'd like**
As this synapse feature is coming, https://github.com/matrix-org/synapse/pull/6409, would it be possible to have such feature available on Riot-web?

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/2497

**Comment by Thatoo** [comment]
sorry
