### ISSUE TITLE
Buildkite agents don't clean up after themselves

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11623]
```

+ git clone git://github.com/matrix-org/matrix-js-sdk.git matrix-js-sdk --branch develop
--
  | fatal: destination path 'matrix-js-sdk' already exists and is not an empty directory.


```

**Comment by turt2live** [comment]
We fixed this

**Comment by madan712** [comment]
> We fixed this

Could you please share how you fixed it. I am also facing same issue.

**Comment by t3chguy** [comment]
In part we started using ephemeral agents in places, we've pretty much stopped using buildkite so you're unlikely to get the desired response here.
