### ISSUE TITLE
Riot connects to cloudflare servers, even if an isolated private homeserver is used

### ISSUE THREAD

**Issue by bpcurse** [vector-im/riot-web#11648]
**Is your suggestion related to a problem? Please describe.**
Riot Desktop 1.5.5 on Manjaro Linux is establishing connections to cloudflare servers on startup, even in a private/unfederated setup not using any id or integrations servers and having set "trusted_key_servers" to the private homeserver only.
From a privacy point of view this shouldn't happen. The person running the server can - under circumstances - even face legal trouble (EU-GDPR).

![Riot connections on startup](https://user-images.githubusercontent.com/29312856/70664316-1735dc80-1c62-11ea-8726-cbb7ac7cd298.png)

What causes these connections? Is it the preset integrations server (scalar.vector.im) that seemingly cannot be set to "none" in the config, neither by the server admin, nor the client user?

![ID and integrations servers](https://user-images.githubusercontent.com/29312856/70664320-19983680-1c62-11ea-84fa-6038a74834b8.png)

**Describe the solution you'd like**
Riot must not connect to 3rd party servers in a private setup, as long as no id/integrations servers are explicitly set. The client shouldn't set a default integrations server in this case as is the default for id servers already.

**Describe alternatives you've considered**
On first use (if a custom homeserver has been defined) there could be a splash screen informing the user about default servers with the option to disable them before connecting.

**Additional context**
Slightly related issue: https://github.com/vector-im/riot-web/issues/8691

**Comment by turt2live** [comment]
It appears as though you're using an outdated Riot as the option to disable the integration manager was added in the last release. 

Though, it would be good to get more information about your environment: are you using riot.im/app or the desktop app? have you deployed Riot to your own webserver and are using that?

Some deployment decisions (or lack thereof) can result in Riot making sure that matrix.org is still alive, which is where the cloudflare hits are coming from.

**Comment by bpcurse** [comment]
I am using Riot Desktop (v1.5.5) as mentioned in the OP. So this feature has been added in v1.5.6?
Will update as soon as the Manjaro repository has 1.5.6 available.
Our homeserver is synapse v1.5.0.

We have deployed a server hosted web version of riot as well. It too initially connected to a cloudflare server, but only one connection. In the web version I could stop all cloudflare connections by deleting every entry mentioning external servers.

Using this riot-web config there are no more cloudflare connections established:
```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.xxxxxxxx.de",
            "server_name": "xxxxxxxx"
        },
        "m.identity_server": {
        }
    },
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "xxxxxxx",
    "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
    "defaultCountryCode": "DE",
    "showLabsSettings": false,
    "features": {
        "feature_pinning": "labs",
        "feature_custom_status": "labs",
        "feature_custom_tags": "labs",
        "feature_state_counters": "labs"
    },
    "default_federate": false,
    "default_theme": "dark",
    "roomDirectory": {
        "servers": [
            "matrix.xxxxxxx.de"
        ]
    },
    "welcomeUserId": "@riot-bot:matrix.org",
    "piwik": false,
    "enable_presence_by_hs_url": {
        "https://matrix.xxxxxxxx.de": false
    },
    "settingDefaults": {
        "breadcrumbs": true
    }
}
```

**Comment by turt2live** [comment]
It's not new for 1.5.6, and without more detailed logs I can only make assumptions about what it could be connecting to. Riot performs a self-test of its config on startup, which is typically pointing to matrix.org. The desktop app has the same thing.

The config you've posted changes the default homeserver, so the config self-test will be hitting that server instead. The desktop app can be configured to do the same thing: https://github.com/vector-im/riot-web/blob/develop/docs/config.md#desktop-app-configuration

The symptoms you're describing sound like https://github.com/vector-im/riot-web/issues/11655 which puts the issue much more succinctly.
