### ISSUE TITLE
hide join/leave messages are only cosmetically

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#11656]
### Description

When I disable "Show join/leave messages" and open a room with many join/leave messages (e.g. after IRC idle kicks or announcement rooms with low content-to-join/leave-ratio), it seems it still retrieves all joins/leaves and thus there is a spinner for a couple of seconds

### Steps to reproduce

- disable "Show join/leave messages" in settings
- (clear cache)
- open a room with many joins/leaves

I expected disabling that option enables faster load times when switching rooms.

Log: not sent

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.5

**Comment by t3chguy** [comment]
It is not possible to filter them out at the sync level as join/leaves are identical to displayname and avatar changes so the filtering must be done locally and thus the loading spinner

**Comment by lub** [comment]
I see. I'll close the issue :)

**Comment by C0rn3j** [comment]
Took me a while figuring out how to do this and this is the top result for search, so for posterity, this is how to enable the setting in the first place:

<img width="981" height="578" alt="Image" src="https://github.com/user-attachments/assets/5b34e2af-1f4b-42ce-bdf2-09783cbc1d7b" />

I was looking for it really hard in `Notifications` instead.
