### ISSUE TITLE
RightPanel can become stuck and non-resizable

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11666]
### Description

Recently, there are points where the RightPanel sidebar (be it on the users/files/notifications pane) becomes unresizable. I have to refresh to fix it. 

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
@anoadragon453 do you have any steps on how to reproduce this?

**Comment by anoadragon453** [comment]
The following seems to eventually reproduce it after 4-5 tries:

* Switch between rooms
* Click a user avatar in the timeline
* Try to resize the right panel
* If it works, close the right panel and repeat

**Comment by ZerataX** [comment]
I have the same exact issue, but additionally the notification tab covers the whole chat area when it happens:
https://streamable.com/meo5a

**Comment by turt2live** [comment]
Considering this a duplicate of https://github.com/vector-im/riot-web/issues/11674 for now - if it happens still after that issue is closed, please open a new issue.
