### ISSUE TITLE
"Node was not found" when displaying or closing the edits history dialog

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#11661]
With the latest develop, I get this error either when trying to display edits (for some events, in which case the dialog closes and I can't see the edits) or when trying to close the edit dialog (for other events, in which case the dialog spins then closes):

```
NotFoundError: Node was not found MessageDiffUtils.js:110:8
    insertBefore MessageDiffUtils.js:110
    renderDifferenceInDOM MessageDiffUtils.js:191
    editBodyDiffToHtml MessageDiffUtils.js:276
    render EditHistoryMessage.js:140
    React 2
        finishClassComponent
        updateClassComponent
    beginWork$1 bundle.js:393010
    React 4
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        beginWork$$1
    performUnitOfWork bundle.js:397522
    React 2
        workLoopSync
        performSyncWorkOnRoot
    performSyncWorkOnRoot self-hosted:913
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:699
    React 2
        runWithPriority$2
        flushSyncCallbackQueueImpl
    flushSyncCallbackQueue bundle.js:385006
    React 3
        scheduleUpdateOnFiber
        enqueueSetState
        setState
    loadMoreEdits MessageEditHistoryDialog.js:71
    InterpretGeneratorResume self-hosted:1150
    AsyncFunctionNext self-hosted:689
```

It's unclear to me why it doesn't come up at the same time for different events.

I'm using the latest stable version of Firefox (71.0).

I can PM the event IDs and which room to find them in if needed.

**Comment by turt2live** [comment]
Event IDs and room IDs would be appreciated as it's almost certainly something in the event itself.

Note that you'll have to refresh riot after this happens otherwise it might emit symptoms of a larger problem.

**Comment by t3chguy** [comment]
I managed to hit a different stack with the same symptom:

`DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node`

**Comment by twouters** [comment]
I've managed to reproduce at least one case:

Send simple message:  
`x bold`

Edit message to:  
`x **bold**`

The message edit popup closes and the reported exception is thrown

**Comment by MayeulC** [comment]
I hit this [in the riot-web room](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$tgepXRT2L4ms2HTCZ6K4K6QXUW767w-AahKNjzzMoek?via=matrix.org&via=privacytools.io&via=mozilla.org) while wanting to showcase another issue with edits.

It seems to happen when adding a new `code block` to the message. Here are a few tests I made (in every case, the last message starts exhibiting the issue, as well as for every subsequent edit, even after removing the extra code block.

```
hi
hi `hello`
```

```
hi `hello`
hi `hello2`
hi `hello2` `hello3`
```

**Comment by z3ntu** [comment]
I'm also seeing this with this message: https://matrix.to/#/!ZPbDMeSXDwjIJrdCvo:fam-ribbers.com/$Wmzpjbr8NDz3ySII2kugE-uE4ir1Vt61-0wm5ATjgjc?via=matrix.org&via=kde.org&via=postmarketos.org

**Comment by t3chguy** [comment]
digging into this a little:

![image](https://user-images.githubusercontent.com/2403652/81938455-d7966680-95ec-11ea-8544-f4957e5ef637.png)

we are trying to insert X into Y but before Y :D

**Comment by t3chguy** [comment]
This looks to be a regression caused by https://github.com/matrix-org/matrix-react-sdk/pull/3680

**Comment by MayeulC** [comment]
Thanks a lot :tada:
