### ISSUE TITLE
member info panel expands to fit device names on a line

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11674]
![Screenshot 2019-12-16 at 11 26 21](https://user-images.githubusercontent.com/986903/70903519-f4efe600-1ff6-11ea-8727-d99e3b159ab8.png)

It's also not resizable either way despite having the resize cursor.

**Comment by turt2live** [comment]
I suspect this has nothing to do with the device lists and more to do with the resizer. https://github.com/vector-im/riot-web/issues/11666 seems highly related, if not a duplicate.
