### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by hans-mm1** [vector-im/riot-web#11671]
### Description 
I'm having an issue with a room I'd like taken down 

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by t3chguy** [comment]
Riot is just a client. It hosts no rooms. Contact your homeserver administrator, for matrix.org it's abuse@matrix.org
