### ISSUE TITLE
Bots permanently offline

### ISSUE THREAD

**Issue by O5ten** [vector-im/riot-web#11689]
### Description

Bots are offline in all channels and does not respond to interactions like !guggy, !giphy or !wikipedia. When i check the status of an individual bot user then it is offline. I am not inviting them to encrypted channels. 

### Steps to reproduce

- Install a homeserver
- Setup federation and https behind an apache reverse-proxy
- Create a channel
- Add a bot to it
- Try to use it

It does not answer

Logs being sent: yes

[homeserver.log](https://github.com/vector-im/riot-web/files/3980702/homeserver.log)

![image](https://user-images.githubusercontent.com/3242379/71126523-773ffc00-21e9-11ea-9e31-39de2b6a42d4.png)

### Version information

- **Platform**: web (in-browser) or desktop?
Both 

For the web app:

- **OS**:  homeserver in Ubuntu 16 something. 

For the desktop app:

- **OS**: Desktop Client in Windows,
- **Version**:
riot-web version: 1.5.6
olm version: 3.1.3

**Comment by turt2live** [comment]
Presence information ("offline") isn't a good metric for these bots given they're on matrix.org which has presence disabled. 

The bots appear to be working fine - you might just need to disinvite and reinvite them. Alternatively, you might homeserver issues - visit #synapse:matrix.org to troubleshoot if you're having problems with DMs to other users on other servers.
