### ISSUE TITLE
Riot error when no identity server is defined when clicking on synapse' confirmation email

### ISSUE THREAD

**Issue by wuhlheide** [vector-im/riot-web#11688]
### Steps to reproduce
- Use a non federated synapse/riot-web environment
- Use no identity server configured in synapse and riot
- Register a new user with email in riot web
- Click confirmation link in email

### Output in browser console
- TypeError: "undefined is not a valid URL."
- Invalid base_url for m.identity_server
- Error determining preferred identity server URL: 
Object { state: "FAIL_ERROR", error: "Invalid base_url for m.identity_server", base_url: null }

### Result
Loading icon of death.

**Comment by aaronraimist** [comment]
What does your `.well-known/matrix/client` file look like? I'm guessing you have an `m.identity_server` section but it is blank. Instead just remove the identity server section.

**Comment by wuhlheide** [comment]
```
{
  "m.homeserver": {
    "base_url": "https://matrix.foo.net"
  }
}
```
no identity server there

**Comment by aaronraimist** [comment]
Both Synapse and Riot are up to date?

**Comment by wuhlheide** [comment]
Sorry, that was a caching problem.
But now when clicking on the email confirmation link riot opens in a new tab and shows:
```
Eine E-Mail wurde an gesendet
Bitte prüfe deine E-Mails, um mit der Registrierung fortzufahren.
```
That is a little bit buggy....there is the email missing in the text and no email gets sent. The first browser tab shows a registration success message.

**Comment by wuhlheide** [comment]
In the latest riot web version it shows "User ID already taken." and the first browser tab shows a success.
