### ISSUE TITLE
Show IRC nickname alongside Matrix nickname

### ISSUE THREAD

**Issue by dannycolin** [vector-im/riot-web#11680]
**Is your suggestion related to a problem? Please describe.**
When the IRC bridge fail to reconnect me to my account, my username is changed by the IRC server. Also, I don't always receive or see the PM from NickServ or the IRC service.

**Describe the solution you'd like**
Could it be possible to show the IRC nickname just after our matrix nickname in the channel userlist. 

**Describe alternatives you've considered**
AFAIK, there isn't.

**Additional context**

**Comment by t3chguy** [comment]
How would this work if a room is bridged to 5 different networks? A room can be bridged to any number of places

**Comment by dannycolin** [comment]
> How would this work if a room is bridged to 5 different networks? A room can be bridged to any number of places

Not sure I understand your question. I mean if I'm on #freenode_#fedora:example.com or #freenode_#fedora:domain.com I'm still connected to the same IRC server.

**Comment by t3chguy** [comment]
Those are portal rooms, but any room at the technology level can be bridged to any number of rooms. Portal rooms are just automatically generated rooms bridging to a single place but there's no way of detecting that between bridges. This would need matrix API support from the bridges and would need design into how it'd work for rooms where there are more than 1 Bridge present

**Comment by turt2live** [comment]
This sounds like a bug with the bridge rather than the client. If the bridge isn't setting your nick predictably or in a stable way, that's a fail on the bridge's part.

**Comment by dannycolin** [comment]
> This sounds like a bug with the bridge rather than the client. If the bridge isn't setting your nick predictably or in a stable way, that's a fail on the bridge's part.

@turt2live Sure the bridge should re-log me to my account but the issue was more with the fact that there's no visual cue to easily see my IRC username when I'm connected to a network via Riot-web.

**Comment by turt2live** [comment]
That would be https://github.com/vector-im/riot-web/issues/3319
