### ISSUE TITLE
Long room names should be truncated in room list.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#1168]
![vector](https://cloud.githubusercontent.com/assets/238916/13799313/07b5f090-eb44-11e5-866f-246bd3ff96ac.png)

**Comment by ara4n** [comment]
this is subjective - we've deliberately implemented this like this for now, as some room names can legitimately be long.

**Comment by aviraldg** [comment]
Makes sense, but is there some limit at which it does cut off? Personally, I find that the uneven heights of the room list entries make it slightly harder to use.

**Comment by ara4n** [comment]
not currently - agreed that it should be capped before one hits the 65536 byte limit of the maximum event size ;D  Will put a `max-height`, `overflow: hidden` and `text-overflow: ellipsis;` on it

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/52818386-e0079680-3063-11e9-9470-d28426ec0c96.png)

Fixed
