### ISSUE TITLE
Allow usage of ">" as is, instead of changing it into a quote

### ISSUE THREAD

**Issue by picowar** [vector-im/riot-web#11685]
I'm frustrated that I am not able to quote using just ">". When I do so, it changes into a block quote. 

This is what I want: 
<img width="235" alt="Screenshot 2019-12-17 at 22 26 25" src="https://user-images.githubusercontent.com/22015936/71055736-52ca1e00-211c-11ea-80dc-a261af215345.png">

This is what I get: 
<img width="129" alt="Screenshot 2019-12-17 at 22 26 32" src="https://user-images.githubusercontent.com/22015936/71055743-5e1d4980-211c-11ea-9750-f81fda8e64b1.png">

**Describe alternatives you've considered**
I just don't think this is the proper behavior that one expects when using ">".

**Comment by turt2live** [comment]
Use `/plain` before your message
