### ISSUE TITLE
Things that feel weird as I try to use cross signing on 2019-12-19

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#11693]
Many of these are kinks that'll be ironed out by as-yet-not-started work:
- [ ] Verified sessions only appear on memberinfo in encrypted rooms
- [ ] I can _Unverify user_ on myself - what does this mean?
- [ ] The UX listing unverified devices on my account doesn't look like you can interact with it, but you can (clicking it initates a verification request)
- [ ] The modal text for verifying my own devices is the same as for verifying somebody else (the instruction to verify in person is silly for verifying myself)
- [ ] Verifying a user or device by DM is blocked if the DM is encrypted and there are unknown devices in the room
- [ ] Toast didn't appear
- [ ] Initiating a verification, the message appeared in the DM (though no toast) and the verifee clicked 'accept' and then the verifor received a modal titled 'Incoming Verification' which said the other party cancelled the verification.
    <img width="1440" alt="image" src="https://user-images.githubusercontent.com/1922197/71180324-d5142880-2269-11ea-8084-13c06a09ffd6.png">
- [ ] Refreshing both clients and trying again worked 
    - [ ] Whereby 'worked' means the verification flow completed. At the end, the verifor had still only verified the verifee's device on which the verifee accepted the verification request

**Comment by jryans** [comment]
>     * Verified sessions only appear on memberinfo in encrypted rooms

This one agrees with the designs: we're only meant to show verification status and actions on user info in encrypted rooms.

**Comment by jryans** [comment]
As far as I can tell, these items are either fixed already or intended by designs. Either way, much has changed, so it would be better to have a fresh list of issues.
