### ISSUE TITLE
it's possible to end up with multiple verification sessions in flight with the same user

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11698]
with the result that you click 'accept' and it sits there spinning on both sides because they're waiting for the other side to respond to different sessions (one side still has the toast in the top left behind the dialogs).

Unsure exactly how to repro this but it might involve starting verification wile there are unseen devices in the room and then sending the request using 'send anyway'.

**Comment by bwindels** [comment]
indeed, we should show "continue verification" in the encryption panel if a request is ongoing.
