### ISSUE TITLE
leftpanel filter is now weirdly case sensitive

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11701]
when filtering for a room i now seem to often have to use the correct case to match the room name (but not always?)

**Comment by ara4n** [comment]
For instance, a private room in my favourites with no aliases and name "Foo Bar" now has to be searched for by 'Bar' rather than 'bar'.

**Comment by benparsons** [comment]
Possibly same as #11700 ?

**Comment by t3chguy** [comment]
Is indeed, closing it as this one has more info

**Comment by t3chguy** [comment]
oh heh, this is because lowercase `m` gets unhomoglyphed into an `n`, so need to apply toLowerCase before and after unhomoglyph
