### ISSUE TITLE
Room list filter should ignore case

### ISSUE THREAD

**Issue by benparsons** [vector-im/riot-web#11700]
### Description

Searching for rooms should be case insensitive, right now it seems to depend on case. This might be a regression.

### Version information

https://riot.im/develop 443d3812d11f-react-24d0d0d59674-js-fe2bdd027ed6

**Comment by t3chguy** [comment]
This might be a regression with the new fuzziness added but I'm pretty sure it had case insens, will test

**Comment by t3chguy** [comment]
It looks case-insensitive to me on /develop:
![image](https://user-images.githubusercontent.com/2403652/71268688-6a381f80-2345-11ea-8571-73f78685ea9f.png)


Could you share an example?

**Comment by t3chguy** [comment]
Closing as #11701 has more information about the same thing
