### ISSUE TITLE
Accepting DM verification in an encrypted DM can cause unknown device warnings you can't access

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11709]
![](https://i.imgur.com/iSaQwmq.png) 
This is slightly unhelpful if I have to cancel verification to verify the user...

**Comment by foldleft** [comment]
I was unable to repro this; is it still a valid ticket?

**Comment by turt2live** [comment]
depends on whether or not we are keeping the unknown devices concept at all. Currently I can reproduce it, but this was a time before the cross-signing flag.

@jryans is the concept gone forever with cross signing or just part of the transition?

**Comment by jryans** [comment]
The default state in a cross-signing world allows all messages, but there are further plans to allow paranoia options that would block unknown devices in some way:

* [Add setting for confirmation when sending messages to a room with verified users who have unverified devices · Issue #11807 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11807)
* [Adapt existing setting to only send to verified devices for cross-signing · Issue #11808 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/11808)

**Comment by bwindels** [comment]
action for this ticket: don't block sending for unknown devices

**Comment by foldleft** [comment]
if this is an issue it's extra urgent now I've landed auto-E2E for verifications 💃

**Comment by bwindels** [comment]
I can't repro this anymore. I've tried adding a new device, skipping the complete-security to not have it cross-signed, and then verify that user from another account. This is with the *Never send encrypted messages to unverified devices from this device* flag off on the initiating side. Left is what I see from the account itself, and right from the account trying to verify it:

![verifyunknowndevice](https://user-images.githubusercontent.com/274386/75544815-a1e5d680-5a1c-11ea-90e8-1f3f7f777d00.png)

I could successfully verify, without any unknown device warnings, and after verification completed I saw a red device for the account as well, so all seems to be working well.

With the *Never send encrypted messages to unverified devices from this device* flag on, I get this on the receiving side (on a cross signed device):

![utd-unverified](https://user-images.githubusercontent.com/274386/75545279-ca220500-5a1d-11ea-87c2-38eef6d4e4f3.png)

#11808 seems to be about fixing that though, so closing this issue.
