### ISSUE TITLE
Ignore irrelevant characters when sorting users

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11707]
We should ignore characters that aren't alphanumeric when sorting people in the member list, to avoid e.g. square bracket prefixed usernames automatically rising to the top.

**Comment by turt2live** [comment]
how do we handle non-latin characters in this?

**Comment by nadonomy** [comment]
Not sure without doing more R&D, but I'd be happy with us just excluding [these 14 punctuation marks](https://grammar.yourdictionary.com/punctuation/what/fourteen-punctuation-marks.html) from sorting.
