### ISSUE TITLE
Can‘t send encrypted messages

### ISSUE THREAD

**Issue by maralorn** [vector-im/riot-web#11711]
### Description

When I try to send a message in an encrypted room I get the message "Did not send message: Retry / Cancel" (back translated from german).

### Steps to reproduce

- Go to riot.im/app, create a new account on matrix.org.
- Create a room, activate encryption.
- Let any account (can be the same) with any device join that room.
- Enter a message and press send.

Log will be submited.

#### Further details

This bug happens exactly when there is one or more other unblocked device in the room.
After trying to send a message once while this is the case the room seems to "crash". As in: you can‘t send any other message after that. After blocking all devices than your own and reloading the client you can send messages again.

### Version information

firefox 71.0 (64-bit)
nixos 19.09.

I tested different scenarios:

**This bug reproduces** on riot.im/develop, own my own riot instance with riot-web 1.5.6, with matrix.org as matrix-server and with my own matrix-server as server, also on a computer of another nixos user also with firefox and inside my firefox within a new freshly created firefox profile and in different rooms, old ones and new created ons.

**This bug does not reproduce** in chromium and in **firefox private mode.** (What‘s up with that?)

**Comment by maralorn** [comment]
When I try to submit the error log I get `Failed to send logs: Query failed: undefined`.

**Comment by turt2live** [comment]
Are you low on physical disk space?

**Comment by maralorn** [comment]
No, 64G free.

**Comment by turt2live** [comment]
it sounds like your privacy settings might be interfering with how Riot works

**Comment by ashkitten** [comment]
having this problem with firefox 71, works fine with firefox 69

**Comment by turt2live** [comment]
Oh, you're both on Firefox 71. That particular build of Firefox is defective - see https://github.com/vector-im/riot-web/issues/11606#issuecomment-565043225 for the fix.

**Comment by maralorn** [comment]
I am not sure this is the same issue. I got told by the nix maintainers that this issue has been fixed on firefox two weeks ago. Still not working.

@ashkitten on which distri are you?

**Comment by turt2live** [comment]
You may have to manually update your firefox, at least that's what some people in the community have had to do. Something about package managers not being helpful.

**Comment by maralorn** [comment]
Well I also have
```
Error performing indexeddb txn 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, currentTarget: IDBTransaction, eventPhase: 3, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
NotificationUtils.js:23:78
Error sending event DOMException: "The operation failed for reasons unrelated to the database itself and not covered by any other error code." NotificationUtils.js:23:78
    r NotificationUtils.js:23
    ce client.js:65
    c bluebird.js:5290
    _settlePromiseFromHandler bluebird.js:3302
    _settlePromise bluebird.js:3359
    _settlePromise0 bluebird.js:3404
    _settlePromises bluebird.js:3480
    p bluebird.js:190
    f bluebird.js:183
    _drainQueues bluebird.js:199
    drainQueues bluebird.js:69
```
So it sure seems like the same bug.

**Comment by ashkitten** [comment]
i'm on nixos as well. managed to get it working by using firefox-bin instead of firefox
