### ISSUE TITLE
Room alias validation inconsistent

### ISSUE THREAD

**Issue by bit** [vector-im/riot-web#11737]
While creating a room, its possible to set an alias without any restrictions for the local part.
The settings dialog on the other and does not allow slashes in additional aliases.

According to https://github.com/matrix-org/matrix-doc/issues/668 slashes should be allowed.

Both places should use the same alias validation function for a consistent user experience.

matrix-react-sdk/src/components/views/dialogs/CreateRoomDialog.js
matrix-react-sdk/src/components/views/room_settings/AliasSettings.js

the error dialog should state what a valid alias is. right now it just says:

Invalid alias format: 'a/b/c/d/e/f' is not a valid format for an alias.

**Comment by turt2live** [comment]
Room alias grammar hasn't been fully defined yet, but we should still be consistent within the app.
