### ISSUE TITLE
Community Icon (Top left) not clickable. 

### ISSUE THREAD

**Issue by martiniturbide** [vector-im/riot-web#11731]
Hi

Just as a GUI suggestion:

On the top left  community icon, I would expect that it would be clickable and takes me to the community page (with the several channels there) . But if I click there, it does not do anything. I have to click on the "three points" and select "view community". 

Example:
<img width="173" alt="2019-12-27 15_54_51-Riot _ OS2World" src="https://user-images.githubusercontent.com/498092/71532576-fefcc900-28c1-11ea-8337-6ac17c509d14.png">
Clicking directly on the icon does not do anything. 

<img width="188" alt="2019-12-27 15_57_39-Riot _ OS2World" src="https://user-images.githubusercontent.com/498092/71532580-0328e680-28c2-11ea-9c44-6155f4ee3904.png">
I have to click the "three dots" and go to "view community".

Please give it a thought. 

Regards

**Comment by t3chguy** [comment]
Clicking on the community selects it and filters your room list to the rooms of that community

**Comment by bpcurse** [comment]
I had the same first use experience as @martiniturbide
It seems more intuitive to me that the community overview is opened when the avatar is clicked on.
At least something to be discussed further. It probably depends on the use case (maybe provide a new config option?)

**Comment by t3chguy** [comment]
The entire point of the panel is for filtering the room list which is adjoining it

**Comment by martiniturbide** [comment]
Hi
The UX issues is that if you click the center of the icon, it does not do anything. It is a waste of a good clicking space to see the contents of that community. 
Regards

**Comment by t3chguy** [comment]
In next release it'll look more clear that something happens when you click it, note the new indicator to show it is selected, its not a big jump to it being selected to modulate the list of things next to it:
![image](https://user-images.githubusercontent.com/2403652/72153046-b3a7e780-33a4-11ea-9be5-4892b2119b4c.png)

**Comment by aaronraimist** [comment]
I think this can be closed. It is clickable and the design has been improved.
