### ISSUE TITLE
[Feature request] Any chance for an "Archive" folder?

### ISSUE THREAD

**Issue by KopfKrieg** [vector-im/riot-web#11739]
I'd like to have an additional "Archive" folder for rooms/chats that I don't want to have in my list of People/Rooms, but that I'm still part of. Many messengers (e.g. Signal, Wire, or even WhatsApp) already have such a feature. Rooms/Chats that are moved into the "Archive" folder are still active (you don't leave those Rooms/Chats), and if you get a new message in those Rooms/Chats they are automatically moved back to your People or Rooms list. It's for Chats you don't want to delete, don't want to leave, but still want out of sight as much as possible (I'd call it a "Peace of Mind"-feature. For things you still need, but don't want to see if not absolutely necessary).

This also means this "Archive" folder is different to the already existing "Archive" folder for Rooms/Chats you've left.

**Comment by benqrn** [comment]
I was using 'leave room' and 'historical' section, but this does not work like an archive; you can no longer interact with the rooms once you leave and accessing historical rooms does not work reliably on clients.

Simply providing another room category in the left panel would be sufficient, the panel can be kept closed and out of sight if desired, but still accessible and searchable.

**Comment by KopfKrieg** [comment]
> Simply providing another room category in the left panel would be sufficient, the panel can be kept closed and out of sight if desired, but still accessible and searchable.

If it's just another category I'm also fine with it. As long as I don't see some rooms in my default overview.

**Comment by turt2live** [comment]
Closing in favour of the more modern issue for this: https://github.com/vector-im/riot-web/issues/14038
