### ISSUE TITLE
Sign/verify key backup with cross-signing key

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11747]
So trusting the cross-signing key will also allow you to trust (ie. start uploading keys to) the key backup.

**Comment by dbkr** [comment]
Actually most of this is already done, apart from re-signing the backup with the cross-signing key when we convert a key backup to a cross-signing.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/element-android](https://github.com/vector-im/element-android/issues/3368)
