### ISSUE TITLE
The 'Members' button should always toggle the right panel

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11749]
Currently when viewing a user profile, clicking on the members profile reveals the member list, meaning users need to click it twice to dismiss the right panel. Clicking it should simply toggle the right panel off, and clicking it again should then reveal the member list.

**Comment by turt2live** [comment]
the logic which manages the right panel is starting to get a bit complicated with changes like these :(

It's probably not an issue yet, just a head's up that the thing is steering towards spaghetti.
