### ISSUE TITLE
Update or kill EncryptedEventDialog

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11752]
Needs to be updated to reflect cross-signing verification status, but personally I would really like to kill it off. The info it presents is all available elsewhere and it's mostly misleading (sending device is never displayed for UTD messages and everybody assumes that it's UTD because the sender is unknown rather than the other way around).

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/4412 starts us down the path by at least hiding the option to access this when cross-signing is enabled.

**Comment by jryans** [comment]
Product is okay with removing this.

**Comment by dbkr** [comment]
Apparently we already disabled it anyway when cross-signing is active: https://github.com/matrix-org/matrix-react-sdk/pull/4412
