### ISSUE TITLE
 Report Content to Your Homeserver Administrator function not working

### ISSUE THREAD

**Issue by wuhlheide** [vector-im/riot-web#11759]
### Description

The report content function in riot web does nothing on my private environment. Browser console shows no error, synapse logs show no error.

### Steps to reproduce

- Go in riot, choose a message not from you and not from admin
- Click report content and fill in something
- Modal closes and nothing happens

### What should happen

Homeserver Admin should get a notice

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 71.0 64 bit
- **OS**: Windows 10 1903
- **URL**: Riot Web 1.5.6
- **Synapse**: 1.7.3
- Variable in homeserver.yaml is set to: admin_contact: 'mailto:hugo@habicht.com'

**Comment by turt2live** [comment]
The functionality of notifying the server admin is left as a server concern, not for the client. Please open an issue with your homeserver's issue tracker.
