### ISSUE TITLE
Update unknown device warning logic

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11750]
With cross signing flag off, everything should stay as it is currently. With cross-signing on, send keys to all devices (except blacklisted ones maybe?) Note: there will be a ["Confirm before sending messages to untrusted sessions" toggle](https://github.com/vector-im/riot-web/issues/11807) which will cause a dialog like this if turned on, but this can come later (and the dialog will probably be sufficiently different that we won't want to re-use the old one anyway).

Edit: this tracks the target behaviour *before* implementing new settings. For after, see https://github.com/vector-im/riot-web/issues/11808

**Comment by ara4n** [comment]
sgtm. i don't /think/ we're killing off blacklisting ftr

**Comment by dbkr** [comment]
The other complication here is how this interacts with both the setting we currently have ("Never send encrypted messages to unverified devices from this device") and the new one ("Never send messages to untrusted sessions"). The new settings will come later, so for now this describes how sending messages interacts with the *old* flag.

cross signing off:
 * everything stays as it is now
cross signing on:
 * old flag in default state:
  * room has green or black shield: send message to all devices in room
  * room has red shield, at least one untrusted device is unknown: warn
  * room has red shield, all untrusted devices are known: send to all devices in room
 * old flag in paranoia state:
  * room has green shield: send message to all devices in room (which are all verified)
  * room has green or black shield: send only to verified devices

**Comment by dbkr** [comment]
Mostly note to self: the js-sdk doesn't have the tools to do this right now, since an unverified device from a verified user would just go back to 'unverified, unknown' which would be the same as an unverified device from an unverified user.

**Comment by jryans** [comment]
@dbkr, does your PR implement "room has green or black shield: send only to verified devices", or is that future work? It seems like it only disables this existing warning when cross-signing is on...?

**Comment by dbkr** [comment]
yep, with the paranoia flag on it will only encrypt to verified devices as it did before (in this case it just doesn't send keys to them rather than erroring)
