### ISSUE TITLE
message edits dialog is shown when closing image dialog

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#11762]
when clicking an image, and closing the resulting image dialog, you briefly see a dialog saying 'message edits' with a spinner

**Comment by turt2live** [comment]
@bwindels this is indicative of a previous attempt to open the message edits dialog and it crashed, so it is forever in the modal stack. You'll probably get the same thing when you open/close settings, etc. 

Try reloading the page and if that doesn't work, rageshake.

**Comment by turt2live** [comment]
Root cause is https://github.com/vector-im/riot-web/issues/11661
