### ISSUE TITLE
rotated jpeg image wrong aspect ratio in inline preview

### ISSUE THREAD

**Issue by hramrach** [vector-im/riot-web#11776]
Rotated jpeg image has wrong aspect in inline preview. It also does not appear rotated.

Message screenshot

![Screenshot from 2020-01-05 11-30-01](https://user-images.githubusercontent.com/787652/71778486-d013e080-2fae-11ea-849c-9d881b201a9a.png)

Original image

![ftdi-serial_s](https://user-images.githubusercontent.com/787652/71778491-d73aee80-2fae-11ea-9fe3-f031f2b7021c.jpg)

### Version information
- **Platform**: web 
- **Browser**: Chromium  78.0.3904.108
- **OS**: Linux
- **URL**: https://riot.privacytools.io/ v 1.4.2

**Comment by jomat** [comment]
We have the same problem on latest Riot 1.5.12 on Firefox and Chrome.
One user reported that it was displayed correctly after uploading the identical image a second time.

**Comment by turt2live** [comment]
This is a server-side bug: https://github.com/matrix-org/synapse/issues/6046
