### ISSUE TITLE
Bulk Options section located under Security & Privacy in Riot settings

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11773]
![image](https://user-images.githubusercontent.com/1342360/71768798-bb204a00-2ee7-11ea-9105-6079fb4ea99e.png)

The "Bulk Options" section (which only appears if you have pending invites) is located in Security & Privacy for some reason. I assume this is because it only shows occasionally.

As a result, the potentially very useful options here (accept 22 invites to bridged rooms at once) are never exposed or found by users.

**Comment by t3chguy** [comment]
Where should these go

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/6450
