### ISSUE TITLE
Email send notification whitout IS

### ISSUE THREAD

**Issue by Unsourire** [vector-im/riot-web#11779]
### Description

You need to enable an IS if not you can't send invitation.

### Steps to reproduce

As Synapse propose the possibility to send email for registration why it is not possible? Always asking for an IS....

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 7.1.0
- **OS**: Windows,
Version de riot-web : 1.5.6
version de olm : 3.1.3

**Comment by turt2live** [comment]
This is because of how Matrix works. Currently 3PID (email) invites require an identity server to store some information and interact with the homeserver. In future, this role could be placed on the homeserver instead.
