### ISSUE TITLE
Going back to an encrypted message after the sender has disabled sending to unverified devices breaks the message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11787]
Expected:
![image](https://user-images.githubusercontent.com/1190097/71874056-19af1900-30de-11ea-9fa6-3f7cdfc04dd2.png)

Then change rooms to get:
![image](https://user-images.githubusercontent.com/1190097/71874070-23388100-30de-11ea-95eb-99e15fdaecca.png)

> ** Unable to decrypt: TypeError: Cannot read property 'plaintext' of undefined **

The full error seems to be lost. Tested on /develop.

**Comment by uhoreg** [comment]
Was this fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1142 ?

**Comment by turt2live** [comment]
Looks like it
