### ISSUE TITLE
Presence indicator alignment in roomlist is a little odd

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#11799]
Without notif:
![image](https://user-images.githubusercontent.com/1922197/71979808-89c0ba80-3216-11ea-808c-b1b4448b3ac9.png)
Without notif hover:
![image](https://user-images.githubusercontent.com/1922197/71979822-90e7c880-3216-11ea-90d4-4d1fcdde2e4b.png)
With notif:
![image](https://user-images.githubusercontent.com/1922197/71979833-96451300-3216-11ea-98f5-5123dd126be4.png)
With notif hover:
![image](https://user-images.githubusercontent.com/1922197/71979842-9c3af400-3216-11ea-9bd4-43c46bfdf1e4.png)

Concrete issues:
- the dot is too close to the notif count indicator
- I find the dot's bouncing around on hover surprising

**Comment by lampholder** [comment]
Additional personal feedback - it might just be my adjusting to it, but with the dot's occupying the same space as the notif count I keep thinking people with the presence dot have messages for me.

**Comment by jryans** [comment]
For now, we've agreed this isn't quite ready. I'll wrap the presence indicator in a feature flag so it won't impact the current release.

**Comment by jryans** [comment]
I have added a feature flag on develop (and soon release) to disable this for now. I'll reassign this back to @t3chguy and @nadonomy to work out the desired experience.

**Comment by MayeulC** [comment]
FWIW, other chat services (Discord at least, IIRC) put the indicator in a corner of the avatar, which seems to convey the online/busy/etc status quite well, especially if unified across the interface.

**Comment by t3chguy** [comment]
Tom said he was happier with this

**Comment by t3chguy** [comment]
Closed prematurely
