### ISSUE TITLE
"Start chat" doesn't start a new chat any more, but reuses an existing one

### ISSUE THREAD

**Issue by jomat** [vector-im/riot-web#11809]
### Description

We are starting new direct chats with other users for a number of reasons quite often. Since a while, an existing one is used instead of a new one being started.

### Steps to reproduce

- click the + button next to "People"
- enter some user name
- click start chat
- repeat the steps above a second time

Expectation: Have two or more chats with the same user
Result: Have one chat with the user

Workaround: Create a new room, set it to direct chat, invite the person, give the person PL 100, remove the room name (in the hope the user name will be displayed, what doesn't work always) and so on…

### Version information

- **Platform**: web (in-browser)
For the web app:

- **Browser**: Firefox 70.0.1
- **OS**: Linux
- **URL**: riot.asra.gr

**Comment by t3chguy** [comment]
This is intentional in preparation for https://github.com/matrix-org/matrix-doc/pull/2199

**Comment by jomat** [comment]
Would it be possible to have an option to choose between creating a new chat or reuse one of the existing ones?

**Comment by t3chguy** [comment]
That was the previous behaviour, as linked above the future in Matrix brings Canonical DMs where you have only exactly one DM with each person so no it will not be possible in the future, this DM will be used for things like cryptographic verifications and such

**Comment by jomat** [comment]
Ok, thanks for clarification and improving stuff :-)
I'll miss that feature :-(

**Comment by t3chguy** [comment]
> I'll miss that feature :-(

Me too :'(

**Comment by turt2live** [comment]
Do either of you have a rationale for wanting to do that? The spec is obviously not final and if there's compelling reasons to not go forward with it then now is the time to raise those reasons.

**Comment by jomat** [comment]
Right now: Messages couldn't be sent, clicking on "Resend all" didn't work. Closing the broken chat to open a new one would have resulted in losing history.
In general: Sometimes DMs break in different ways, having a second room comes in handy.

Other times:
 - often discussing different topics and projects in different 1:1 chats
 - sometimes starting a 1:1 chat and inviting a third person that is also affected by the same topic - this probably also won't work anymore with the current idea of canonical DMs?
 - having encrypted and unencrypted DMs for different sets of trusted and untrusted devices

The concept of having direct messages as rooms with some special settings brings a lot of flexibility and it's a loss if it is abandoned.

**Comment by jomat** [comment]
Hit the wrong button, didn't want to reopen it :-/
