### ISSUE TITLE
Accepting a room invite places it in the room list into oblivion

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11806]
When accepting a room invite, the room is opened and immedately 'read' and therefore placed after unread rooms in the room list. If you have breadcrumbs enabled, have favourite rooms, have an amount of DM's, or are in an amount of rooms effectively the room alarmingly disappears into oblivion.

Until we can move away from scrollable letterboxes we should consider if there's any special casing we can do to sorting to make accepting a room invite and tracking where it goes better.

**Comment by turt2live** [comment]
We could do this trivially with the by-importance algorithm (what most people have today): we consider the room sticky and put at as the top/first position in the sublist.

**Comment by nadonomy** [comment]
@turt2live This sounds great if it's a low effort tweak!

**Comment by turt2live** [comment]
We now stick it at the top of the list so it doesn't get too lost.
