### ISSUE TITLE
Changing Notification Levels on Desktop Client Doesn't Work

### ISSUE THREAD

**Issue by HCastano** [vector-im/riot-web#11815]
### Description
When trying to change notification levels on rooms (eg. from "All Messages" to "Mentions Only") there is no effect. After clicking the new setting, the UI still shows (and the app still acts) like the previous notification setting. 

### Steps to reproduce
- Open up the Riot Desktop App
- Choose a channel, any channel
- Try to change the notification level
- Fail

![Screen Recording 2020-01-07 at 4 57 02 PM](https://user-images.githubusercontent.com/12344623/72159266-fd370900-3389-11ea-8ff3-4e9f173deb2b.gif)

Logs being sent: no

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: macOS Catalina
- **Version**:  v1.5.6

**Comment by andresilva** [comment]
If any workaround is known would appreciate that it is posted here, this bug is seriously disrupting my workflow.

**Comment by andresilva** [comment]
BTW this bug doesn't seem to be related to the web UI itself as the exact same thing happens on the mobile app RiotX.

**Comment by turt2live** [comment]
Are you able to submit debug logs for this issue? It looks like a server problem and not a client issue.

**Comment by andresilva** [comment]
@turt2live Sure, could you kindly point me to some docs on what I have to do? (or just give a brief explanation if such docs don't exist.)  I'm only able to collect client logs, but if you need server logs I'll get in contact with the server admin that should be able to provide them.

**Comment by andresilva** [comment]
The issue was server-side and has been fixed in the meantime (don't know more details about it since I'm not involved in configuring it). I think this issue can be closed as @HCastano who created the issue was using the same matrix server as I am.

**Comment by HCastano** [comment]
Can confirm, notification settings are working now.
