### ISSUE TITLE
Import E2E keys does not work

### ISSUE THREAD

**Issue by gdvine** [vector-im/riot-web#11819]
### Description

No message of any type given, as per [this UX bug](https://github.com/vector-im/riot-web/issues/9445). No change to encrypted messages or key verification.

### Steps to reproduce

- Export keys from Account A
- Log out and into Account B (mine is on a different homeserver)
- Go to Settings > Security & Privacy
- Click Import E2E room keys
- Upload file, type password, press Import

The modal closes and nothing at all else happens.

Logs being sent: yes

### Version information

MacOS Desktop client v1.5.6

**Comment by aaronraimist** [comment]
At the time you made the export were you able to decrypt those messages that you looking at?

> or key verification.

Key import/export doesn't have anything to do with device verification so that is to be expected.

**Comment by gdvine** [comment]
> At the time you made the export were you able to decrypt those messages that you looking at?

Yes.

> Key import/export doesn't have anything to do with device verification so that is to be expected.

Ah okay, thank you. Is there a way to export/import a device verification profile?

**Comment by aaronraimist** [comment]
> Ah okay, thank you. Is there a way to export/import a device verification profile?

No. In a month or two when cross signing is done you won’t have to worry about verifying individual devices.

**Comment by uhoreg** [comment]
This sounds like the same issue as https://github.com/vector-im/riot-web/issues/9450, so I'm closing this in favour of that one.

**Comment by gdvine** [comment]
> This sounds like the same issue as #9450, so I'm closing this in favour of that one.

Ah thank you. I did a search but somehow missed it.
