### ISSUE TITLE
User decoration with shields

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11811]
Decorate users with black/green/red shields as appropriate

  * None: e2e off in the room
  * Black: Encryption is enabled (I don’t care about their devices)
  * Red: I’ve verified them and an unverified device exists or they were previously verified and their cross-signing identity has changed
  * Green: I’ve verified them and all of their devices are verified

See also the rooms version https://github.com/vector-im/riot-web/issues/11225.

![2020-01-16 at 10 14](https://user-images.githubusercontent.com/279572/72516131-1687fb80-3849-11ea-9c0b-a1e1e41518b9.png)

![2020-01-16 at 10 15](https://user-images.githubusercontent.com/279572/72516161-20a9fa00-3849-11ea-81c2-3b2f4e29f6c5.png)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/844)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2905)

**Comment by jryans** [comment]
This one seems done by other PRs:

* the shield logic has been updated 
* there is a shield on the profile
* the shield only appears in E2E rooms
