### ISSUE TITLE
Autocomplete for upgraded rooms has regressed

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11825]
This shouldn't be visible:
![](https://i.imgur.com/Aa6LK5V.png)

**Comment by t3chguy** [comment]
I can repro in a slightly different case:
![image](https://user-images.githubusercontent.com/2403652/72393955-658c3e80-372c-11ea-9e3b-8bb2ab9f1c9e.png)

but its not consistent and 100% reproducible in my tests

**Comment by turt2live** [comment]
Yea, I'm not sure what causes it. I can reliably reproduce the Modular one, but only on one device.

**Comment by turt2live** [comment]
@t3chguy the #test problem is actually due to a massive state reset that the client has picked up on. #modular shouldn't have reset, and was obviously broken moments after joining the new room.
