### ISSUE TITLE
Terms and Conditions checkbox is invisible

### ISSUE THREAD

**Issue by animages** [vector-im/riot-web#11823]
### Description

While creating a new account, the checkbox next to Terms and Conditions is invisible and I guess clicked where it was. It is not visible even after it is checked.
### Steps to reproduce

- Create account
- Register
- Do the Captcha

Describe how what happens differs from what you expected.
Its color is supposed to be different from the background color so people can see it but it's not.

Screenshots:
https://cdn.discordapp.com/attachments/290129628012609536/665681270889644043/unknown.png

https://cdn.discordapp.com/attachments/290129628012609536/665681375696912386/unknown.png

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Parrot OS 4.7
- **Version**: 1.5.6

**Comment by t3chguy** [comment]
Testing in Windows it looks fine, 
![image](https://user-images.githubusercontent.com/2403652/72394439-32e34580-372e-11ea-9888-a54e70bc9c65.png)

so it could be related to Parrot OS, any chance you could try in different environments?

**Comment by t3chguy** [comment]
Also I just noticed, you're using Revolt which I believe is unsupported as it is based on a pretty old Chromium version

**Comment by t3chguy** [comment]
Revolt hasn't been updated in two years: https://github.com/aperezdc/revolt
It is built against an old Chromium version. That Chromium version is no longer supported by riot-web due to missing features.

**Comment by turt2live** [comment]
Closing as this is a platform/environmental bug and not one that riot-web can reasonably solve.
