### ISSUE TITLE
Locks appearing on rooms that aren't encrypted

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11835]
### Description

![image](https://user-images.githubusercontent.com/1342360/72272020-d4c83c80-361f-11ea-829e-529a62c9d46d.png)

Not sure what metric you're using to determine whether a room is encrypted, but I'm getting locks on rooms without `m.room.encryption` events.

Specifically, all of the rooms generated by [mx-puppet-discord](https://github.com/matrix-discord/mx-puppet-discord) are getting locks, despite them being bridged rooms and thus not encrypted.

For example, one of the room IDs affected is `!PJbIAndwJxScdbUGtt:amorgan.xyz`.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v74.0a1
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
The locks are for *private* rooms, there'll be a shield for Encrypted ones

**Comment by jryans** [comment]
We may need to add a padlock explanation on hover to avoid confusion... Feel free to file it as an issue if you agree.

**Comment by t3chguy** [comment]
or put it behind cross-signing labs so they appear same time as the new shields

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/11841
