### ISSUE TITLE
edits for messages in flight often get lost

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11834]
i'm sure this used to work, but if i rapidly edit a message after it's been sent (even in non-E2E rooms), the edit often seems to get lost.

**Comment by turt2live** [comment]
I've also seen this - the edit does show up once the timeline remounts due to someone else's message though. Switching rooms doesn't always help.

**Comment by ara4n** [comment]
i can reproduce this pretty reliably ftr, as per https://matrix.org/_matrix/media/r0/download/matrix.org/YyWSIAthKIhsRnNwMweJbQvB

**Comment by turt2live** [comment]
I can reliably reproduce this for messages which *have* been sent and I edit them a few seconds later.

**Comment by ara4n** [comment]
(one thought: i think it might have coincided with me turning on show-invisible-events)

**Comment by turt2live** [comment]
I have that option turned off

**Comment by lampholder** [comment]
I think Travis and Matthew might be seeing different things.

@turt2live - I can't reproduce what you're seeing, which I understand to be "sometimes edits don't render at all until the timeline react remounts".

@ara4n - I can reproduce what you're seeing, which I understand to be "if I edit messages quickly, sometimes I don't see the edits locally echoed".

Specifically, it is easy to reproduce Matthew's issue when there is more than one message queued for sending:

- send a bunch of messages - enough for some to be in the grey 'sending' state
- press up and edit the most recent, still sending message
- no local echo for you

If only one message is pending to send and you edit it, the edit is locally echoed.

**Comment by lampholder** [comment]
From a prioritisation perspective I'd like to see us leave this alone until we get a chance to ease off on E2E/Cross signing.

**Comment by turt2live** [comment]
it looks like what I'm seeing is still local echo, just at a different stage. My /sync is slow, and the edit doesn't update until it's received over /sync which could be seconds away - long enough to switch between rooms and such and start to worry about the problem.

**Comment by ara4n** [comment]
<img width="1047" alt="Screenshot 2020-02-03 at 11 34 20" src="https://user-images.githubusercontent.com/1294269/73650062-28570480-4679-11ea-8a0b-062d808a02be.png">

Here's me trying to edit "duno" to be "dunno" while the original was still sending, and everything going wrong.

**Comment by gdvine** [comment]
Here is my simply stated report I was going to submit as new before I found this issue.
====

### Steps to reproduce

1. Write message and send it (throttling upload speed as necessary).
2. While it's sending, edit the message and submit.

Expected result: Message edit gets submitted and updates sent message.
Actual result: Message edit is totally lost.

Suggested solutions:
1. Easy (and probably best): Disable edit feature until sending is completed (ie sidestep this bug).
2. Hard: Enable edits to be submitted properly before message send is complete (ie fix this bug).



### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: macOS
- **Version**: 1.5.12
