### ISSUE TITLE
Power level state events are rendered empty

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#11846]
As the second event in this screenshot:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/3940906/72290481-a06b7500-364d-11ea-9e97-ec895f0a78e8.png">

Event source:

```json
{
  "type": "m.room.power_levels",
  "sender": "@benoit.marty:matrix.org",
  "content": {
    "users": {
      "@benoit.marty:matrix.org": 100
    },
    "users_default": 0,
    "events": {
      "m.room.name": 50,
      "m.room.power_levels": 100,
      "m.room.history_visibility": 100,
      "m.room.canonical_alias": 50,
      "m.room.avatar": 50
    },
    "events_default": 0,
    "state_default": 50,
    "ban": 50,
    "kick": 50,
    "redact": 50,
    "invite": 0
  },
  "state_key": "",
  "origin_server_ts": 1578913991809,
  "unsigned": {
    "age": 776
  },
  "event_id": "$N8wh8ceZHLNQngdDDrHraowLqMOCtCyc9abELqEN8Eo",
  "room_id": "!vMoAaIrEcKXsfwnKeS:matrix.org"
}
```

**Comment by turt2live** [comment]
Only when you have "show hidden events" enabled.

**Comment by bmarty** [comment]
Ok, but even with "show hidden events", could be better to have something like "Power level state event" rather than an empty area...

**Comment by t3chguy** [comment]
thats fundamentally https://github.com/vector-im/riot-web/issues/11510

**Comment by bmarty** [comment]
Yes @t3chguy , I've done a GH search with "power level" but not "PL" :)
Anyway #11510 is not closed, so that's good.
