### ISSUE TITLE
Riot web unable to display admin options

### ISSUE THREAD

**Issue by NHAS** [vector-im/riot-web#11856]
### Description

As an administrator user when clicking on another user the options to "deactivate" the account should be presented like so:

![Screen Shot 2020-01-15 at 5 25 24 PM](https://user-images.githubusercontent.com/6820641/72404950-0d9d1880-37bc-11ea-9c36-c96fa410d082.png)

However this option isnt present as the request to `/_synapse/admin/v1/users/<user>/admin` becomes URL encoded which the matrix server responds with: 
```
{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
```

### Steps to reproduce

From user interface:
1. Sign in as admin user
2. Click on other user and observe lack of admin options

For example this is the request that riot generates:
[redacted]

However, if the values are manually decoded the request succeeds:

[redacted]

### Version information

- **Platform**: web (in-browser) 
- **Browser**: Chrome 79.0.3945.117, Firefox  72.0.1
- **OS**: macOS
- **Riot version**: 1.5.7
- **Web server**: Nginx

- **Matrix version**: 1.8.0+bionic1

**Comment by turt2live** [comment]
@NHAS you should log out of that account immediately - you've disclosed your access token, which gives complete control of your account. I've removed your original screenshots.

**Comment by NHAS** [comment]
While unfortunate, and I should have known better. This was a test server that isnt connected to the internet, nor does it have ability to federate and has nothing on it.

**Comment by turt2live** [comment]
as for the actual issue: it sounds like an nginx or synapse fail because encoded paths are completely reasonable. Every character could be encoded if we wanted to, but that rarely makes sense.

**Comment by NHAS** [comment]
I agree with that! Thanks!
