### ISSUE TITLE
Upgraded rooms cause stuck badges

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11859]
A specific case of https://github.com/vector-im/riot-web/issues/3059

If a room is upgraded and then somehow (normally due to state resets) gets a notification count, it will cause riot's global badge counter to increment but
 1. the room tile won't have a notification
 1. neither will it's section title
 1. viewing the room won't cause the badge to clear, so you have to not only find the right room but go to the start of it and click back to the previous version to send an RR to the right place

**Comment by turt2live** [comment]
Was there a banner at the top saying "There are notifications in a prior version of this room" (or similar)?

**Comment by t3chguy** [comment]
There is but its only for notifications (highlights) not unreads which can also increase the global counts depending on the settings of the room
