### ISSUE TITLE
Cannot build from tarballs anymore

### ISSUE THREAD

**Issue by guoyunhe** [vector-im/riot-web#11851]
### Description

We have a server to automatically download new release tarballs and build RPM packages.

But recently the build fails because here are some build steps that check `.git` data. Git data should be optional for the build because it doesn't provide any functionality to the app but some commit version information.

### Steps to reproduce

- Download the tarball
- Extract tarball
- Run build electron command

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by jryans** [comment]
Ideally the tarball should already have the release version, which I assume is what Git is being invoked for here... @turt2live, I think you're aware of this; can we change to reading the version file when building from tarballs?

**Comment by turt2live** [comment]
Possibly, though I think this is just a temporary problem for this release only.

**Comment by rodolpheh** [comment]
This seems to be solved with 768cabe4bb051b03b0798b8600ee2788c67e3ecd. @guoyunhe can you check it out ?

**Comment by guoyunhe** [comment]
Still not able to build. But error is different now:

```
yarn run v1.21.1
$ yarn clean && yarn build:genfiles && yarn build:compile && yarn build:types && yarn build:bundle
$ rimraf lib webapp electron_app/dist
$ yarn reskindex && yarn build:res
$ reskindex -h src/header
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'optimist'
```

**Comment by jryans** [comment]
@guoyunhe, can you share the full set of commands you are running? Perhaps you need to `yarn install` first, for example, but it's hard to tell if that has already happened.

**Comment by guoyunhe** [comment]
wow, now I got it. I was using `npm install` before. after changing to `yarn install`, it is built successfully!
