### ISSUE TITLE
Old Parser disabled?

### ISSUE THREAD

**Issue by LunarNeedle** [vector-im/riot-web#11853]
Most recent update pushed to Riot.im removed the old parser, forcing me to use the broken markdown converter with all the issues described here https://github.com/vector-im/riot-web/issues/11230

I am using the Desktop client, although friends using the browser client are experiencing the same issues. Was this removed in an update? I upgraded from version 1.5.3 to 1.5.7, although my friend who used web client has the same issue.

**Comment by t3chguy** [comment]
Yes, the old composer was removed as it was outdated and brought a lot of its own issues (more than the new one)

The issue you linked has a work-around using /plain

This issue shouldn't be an issue, it was a feature which was planned to be removed and thus got removed, if you have issues with the new one which need fixing like #11230, please report them with reproduction cases etc.

For future support please use `#riot-web:matrix.org`
