### ISSUE TITLE
Rageshake logs should always be in UTC, not the browser's timezone

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11854]

**Comment by t3chguy** [comment]
According to JavaScript docs we already do this:

The toISOString() method returns a string in simplified extended ISO format (ISO 8601), which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively). The timezone is always zero UTC offset, as denoted by the suffix "Z".

Its possible that Firefox fingerprinting prevention bodges this as it bodges timezones in general.

**Comment by turt2live** [comment]
indeed, I thought I was dealing with a non-UTC log but it turns out I'm wrong.
