### ISSUE TITLE
Some people suddenly not able to decrypt my messages

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#11861]
Some people suddenly not able to decrypt my messages

{
  "type": "m.room.encrypted",
  "sender": "@twilight:twilightsparkle.dev",
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "sender_key": "nUKW+rP1sbZnfIEFDYSvbXZkZFFWVdG4ltpxdaym71E",
    "ciphertext": "AwgLEoABGOSjBPklptqaw6mmrIeE2FjiZXykuiNvFImIS+csd9IOoPYhClhUYTfWam9yuRr9pVSKewssxOg6Arae6LMbZGSZekF3KZHDCkAK5YBT4kMDyDKc+gquS5a14mXlZmb/0Oyzs8Y0M+la1/pWLEJapX9mxEo1+QAT78YWpHtR1QeJgz1Hg/3eBPYINdqTrMUVmhV6RYKnabNsW1Boj8+KKulvlxYZR7THg1W096BsTjGVfX7aJoYwPf4A/PRpsiZMe7lk3n2JKgg",
    "session_id": "GCDubxQtbmTMjHPj5zczZ3BOj5KJJAbjRjjloRFwVGU",
    "device_id": "YHNRJYCFVF"
  },
  "event_id": "$157909678438HwWbs:twilightsparkle.dev",
  "origin_server_ts": 1579096784343,
  "unsigned": {
    "age": 219524,
    "transaction_id": "m1579096778532.45"
  },
  "room_id": "!GDoOXUnRPfQneOhHur:matrix.org"
}

**Comment by uhoreg** [comment]
Thanks for the rageshake.  We don't need a separate issue for each instance of unable-to-decrypt, so closing this.
