### ISSUE TITLE
Fallback for HSes that don't support cross signing

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11863]
We need to do "something sensible" if the HS does not support cross signing

**Comment by dbkr** [comment]
https://github.com/vector-im/user-stories/issues/37

**Comment by jryans** [comment]
At the very least, we should probably be using the new Synapse feature flag to detect support and not attempt to create a cross-signing identity when not supported on your own HS, as I assume many strange errors would result.

@dbkr also raises that other users on a bad HS (broken cross-signing) won't see anyone as verified (themselves or others), but other users _will_ see them as verified, which muddles things quite thoroughly.

**Comment by jryans** [comment]
At the moment, we believe the sensible changes to make are:

* Skipping all bootstrapping / signing key access if HS doesn't support it
* Hiding user verify buttons when your HS doesn't support it

There's a related issue around ensuring that the other user has published their key which will be handled separately https://github.com/vector-im/riot-web/issues/12161.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/3238)
