### ISSUE TITLE
Instant expose autocompete user list after typing @ in composer

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#11878]
Most of custom (not public) chat rooms generally have not too much members, so will be good to expose autocomplete users list immediately after typing @ in composer, with list of room members, so users can select user via mouse, without typing his name via keyboard.

**Comment by MurzNN** [comment]
For example, Telegram and Skype expose list of room members immediately after typing `@` in composer.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/8960
