### ISSUE TITLE
"ReferenceError: dispatcher is not defined" when clicking avatar in timeline

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11887]
### Description

When clicking on an avatar in the timeline, nothing happens, and a JS error appears in the browser console. I can't peek into `bundle.js` here, so all I have is "ReferenceError: dispatcher is not defined".

I expect when clicking on an avatar next to a message that the memberpanel will come up. All labs flags are off.

Logs being sent: **no**

I'm unable to submit debug logs even after refreshing multiple times:

![image](https://user-images.githubusercontent.com/1342360/72535326-4696c500-3870-11ea-8d39-99e5b43b33b4.png)

![image](https://user-images.githubusercontent.com/1342360/72535310-3c74c680-3870-11ea-9abd-dd3210d391a1.png)

(That may be a problem with my deployment though, shrug. It usually works)

### Version information

- **Platform**: web
- **Browser**: Firefox v74.0a1
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
I can reproduce the issue at least. The rageshake problem looks like a problem with your environment. Note that the entire build system has changed in the last day or so.
