### ISSUE TITLE
formatting toolbar button don't understand multi-line

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#11882]
after highlighting a multi-line segment in the composer and selecting the Italics button it puts a start marker on the first line and an end marker on the last line but commonmark needs it to be on every line instead

**Comment by tulir** [comment]
specifically, new markers are required for each paragraph, not just linebreaks

**Comment by t3chguy** [comment]
This was surprisingly difficult to achieve due to how ambiguous paragraph breaks are in the model :(

![11882](https://user-images.githubusercontent.com/2403652/72814037-4cb7e780-3c5c-11ea-9bcf-cd5946175113.gif)
