### ISSUE TITLE
Integrate key backup setup into SSSS bootstrapping

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11889]
At the moment, we have a bootstrap process for SSSS, and separate flow to also set up key backup with SSSS.

We should integrate these together so that you only go through one series of complex dialogs instead of two.

Ideally, key backup would be offered as a default-on optional feature you could disable if you only want cross-signing identity but not key backup.

**Comment by jryans** [comment]
This should be solved by https://github.com/vector-im/riot-web/issues/11902, but let's confirm once that's done.

**Comment by dbkr** [comment]
Assuming that restoring the key backup when we log in with a passphrase is part of this too
