### ISSUE TITLE
Bootstrapping: new users / no key backup, after sign up / in

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11902]
[Figma](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=2323%3A0)

<img width="1875" alt="2020-01-17 at 10 55" src="https://user-images.githubusercontent.com/279572/72607114-e3f90400-3917-11ea-936b-652e2eb68089.png">

* Account password temporarily held in memory to avoid additional key upload auth prompt

**Comment by dbkr** [comment]
Password caching pulled out to https://github.com/vector-im/riot-web/issues/12046
