### ISSUE TITLE
Remove keyshare dialog once cross-signing exits labs

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11908]
Once cross-signing is the default, we should remove the keyshare dialog.

**Comment by turt2live** [comment]
The original change here feels a bit misguided. We still require keyshare requests for RiotX->Web to get information about devices and such. Cross signing does help, though there are legitimate use cases where key sharing is required.

We've backed the original change out for the demo.

**Comment by jryans** [comment]
The key share dialog (disabled with cross-signing in https://github.com/matrix-org/matrix-react-sdk/pull/3860) is only used for unverified devices. For verified devices, [we send immediately](https://github.com/matrix-org/matrix-js-sdk/blob/620118af5fe2a149b2a275ec5f85a26c3b9c2c6a/src/crypto/index.js#L2925-L2931) and that has not changed.

It would be good to have more details on this scenario to track down what failed and what should be happening.

**Comment by turt2live** [comment]
we were pretty tired at the time - would be worth talking it over with @BillCarsonFr to see what was going on.

**Comment by jryans** [comment]
For the record here, there was a bug that prevented auto key sharing with cross-signed device. Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1243.

This dialog is still planned for removal when cross-signing is out of labs.
