### ISSUE TITLE
Desktop notifications nag bar keeps coming back

### ISSUE THREAD

**Issue by virtadpt** [vector-im/riot-web#11919]
**Is your suggestion related to a problem? Please describe.**

When using the web client, I routinely close the tab in question when I have work to get done, or if I'm logging out for some period of time.  Every time I log back in, however, I always get the "You are not receiving desktop notifications Enable them now" bar.  And every time I close it, because I neither need nor want desktop notifications.

**Describe the solution you'd like**
When I close that bar, set a cookie that means "never ask about this again."  If I go into my personal settings and change that, update the cookie to "enable desktop notifications."

**Describe alternatives you've considered**
I've considered adding that CSS selector to my local uBlock Origin collection, but that seems like overkill.  I just X the bar closed.

**Additional context**
Can provide upon request.

**Comment by t3chguy** [comment]
It does get stored in `global.localStorage.notifications_hidden`
When you log out, local storage is wiped for privacy, so this gets forgotten.
