### ISSUE TITLE
New session toast doesn't tell me which of my devices to go looking for

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11916]

**Comment by turt2live** [comment]
This is important from a bootstrapping perspective: it turned out I never verified my own laptop, so when I refreshed I was met with the prompt. The only way I was able to tell which device it was was going through the legacy verification and seeing the device info. 

There's also the security aspect: Seeing a sudden "new session" toast when you didn't log in should tell you which device it is just in case you forgot you had a laptop or to indicate you've been compromised.

**Comment by jryans** [comment]
Yes, we should definitely do something here before releasing cross-signing, but I don't see it as required for FOSDEM.
