### ISSUE TITLE
Mentions look like error messages

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riot-web#11927]
When you’re mentioned, all text gets red (somehow even the own, quoted text). Every time I see this, I first think of an error. Would you like to change that to a say blueish tone, for example? Or maybe even better to not alter the text at all, and instead highlight that textbox with a slightly striking background color or a frame?

![Bildschirmfoto von 2020-01-18 20-52-19](https://user-images.githubusercontent.com/10520767/72669648-e0a76a80-3a34-11ea-8d90-026e4f0df9da.png)

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/441 https://github.com/vector-im/riot-web/issues/6520
