### ISSUE TITLE
Either package Desktop for Linux Mint or add instructions on how to install with other codenames

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11929]
This is commonly asked about.

`$(lsb_release -cs)` doesn't work on Linux Mint since that produces `tina` rather than one of the codenames that is in the repository. People say that Riot works in Linux Mint if you use `bionic`. Can we provide packages for Mint codenames as well? 

Otherwise add instructions specifically for Linux Mint showing how to use the codename Riot needs.

For reference to install on Linux Mint 19.2 you would run:
```
sudo apt install -y lsb-release wget apt-transport-https
sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ bionic main" |
    sudo tee /etc/apt/sources.list.d/riot-im.list
sudo apt update
sudo apt install riot-web
```

**Comment by LinuxOnTheDesktop** [comment]
I really wish someone would fix this important but technically trivial issue. There is more than one bug report about it.

**Comment by jryans** [comment]
We have now created a `default` distribution for everyone to use going forward (https://github.com/vector-im/riot-web/issues/13367). The download page (https://riot.im/download/desktop/) has been updated to match.
