### ISSUE TITLE
UI confusion about which server a room belongs to

### ISSUE THREAD

**Issue by samwilson** [vector-im/riot-web#11931]
### Description

It's possible to join rooms from different servers, but they all get listed together and there's no way to quickly tell which room comes from which server. Worse, different rooms could have the same or very similar names on different servers, and so it'd not be clear which is which (they could even have the same icon); this could lead to phishing problems.

For example, I'm in a Wikimedia room called `#test-public:wikimedia.org` here, but there's no way to know that it's at all related to Wikimedia; all the other rooms are on matrix.org:

![roomlist](https://user-images.githubusercontent.com/213655/72691382-e51c7200-3b5f-11ea-8eae-ca855ba52597.png)

The only way around this now is to rename the room to make it universally clear (e.g. include the organisation name or something).

One possible improvement could be to include the server name in the tooltip (which currently looks like it's only ever the same text as the room name anyway, so isn't currently adding any value).

### Steps to reproduce

- Join multiple rooms on multiple servers;
- look at the room list sidebar; and
- try to know which server each room comes from.

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: 1.5.6

**Comment by t3chguy** [comment]
Just for a little information, rooms don't belong to servers. If a server has users in a room then that server is as much part of that room as the server which was first to be part of that room
So you presumably mean the canonical alias

**Comment by samwilson** [comment]
Ah, okay, that's interesting; I'd not been thinking about it correctly then. I guess I do mean the canonical alias (that includes the server name part doesn't it? Or is it just the bit before the colon?)

Or is the general idea that room names should distinguish themselves enough in a broader context? Or are Communities a different take on this same idea (i.e. they group rooms together, so the name of each room is always read in context of the Community name)?

(Sorry for my lack of solid understanding of lots of this stuff! I'm still getting my head around it all.)

**Comment by turt2live** [comment]
The canonical alias is just one of the aliases on the room. It's used as a fallback when the room doesn't have a name.

It's best to name your rooms according to the organization, or make a public/private community to organize your rooms. 

#riot-web:matrix.org is a better place to ask about this sort of thing.

**Comment by samwilson** [comment]
Okay sure. Thanks for the information!

I do still think there might be something to be said for not having the tooltip be the exact same string as the displayed name, but I have yet to learn enough about communities...
