### ISSUE TITLE
Room list updates are slow (favourites don't change very quickly)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11939]
from @nukeador

**Comment by turt2live** [comment]
It does for me. It is known to be slow - is that what happened here?

**Comment by nukeador** [comment]
Ok, yes that's it, I tried to unfavorite 10 rooms and it was taking forever.

**Comment by turt2live** [comment]
alright, going to hijack this as "room list updates are slow" because I can't find the other issue.

**Comment by jryans** [comment]
(Copied detail from https://github.com/vector-im/riot-web/issues/12305)

When modifying the room list directly through actions like:

* Moving a room between categories (favourites, low priority, etc)
* Removing / leaving a room

...the room list should local echo / show the update immediately so it's clear the app understood. Currently, there's quite a delay, so it feels as if your selection was ignored or something is broken.

**Comment by turt2live** [comment]
Should be fixed in the new room list.
