### ISSUE TITLE
Impossible to invite mxids you know exist but the dialog won't suggest

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11943]
For the new dialog. Needs design review to figure this one out.

**Comment by turt2live** [comment]
@lrq3000 that sounds like a different issue. This is saying that the new dialog has a bug. Failing to receive invites is a whole other problem.

**Comment by lrq3000** [comment]
@turt2live Ok if you think so, I will open a new ticket, it's indeed about failing to receive invites.
