### ISSUE TITLE
Find a better word than "device" for things that are not devices

### ISSUE THREAD

**Issue by BrenBarn** [vector-im/riot-web#11958]
A device is a physical object.  No matter how many times I log in or out of any services on my phone, it is still only one device.  Matrix and Riot continue to use the term "device" in an incorrect way which misleads users, as evidenced by confused users asking on the #matrix channel why they have all these mysterious "devices" listed under their profile.

It's fine if, from the perspective of the protocol, logging out and then creates a new "thing" for purposes of encryption, etc., but that thing is not a device.  The device is the physical object a person uses to connect, and has no relationship to any accounts or login sessions.  Within the UI, Riot should only use "device" to refer to. . . devices.  For what it currently calls a "device", we might consider alternatives such as "login", "session", or "connection".

**Comment by aaronraimist** [comment]
Related: #5159

**Comment by aaronraimist** [comment]
They will be called Sessions in version 1.6.0
