### ISSUE TITLE
Conversion of text smileys to emojis doesn't work anymore

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#11955]
### Description

The conversion of text smileys to emojis doesn't work anymore.

### Steps to reproduce

- In the message field, type `:D`
- Hit <kbd>Space</kbd>
- No thing happens...

Instead of nothing, the characters `:D` should have been replaced with the emoji 😄.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.5.7

**Comment by t3chguy** [comment]
So this is a partial breakage, `:)`[space] still works as expected, maybe the emojisource data changed :(
