### ISSUE TITLE
Emoji verification: German word for corn isn't the same across web and android

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11961]
![image](https://user-images.githubusercontent.com/5855073/72778839-a7f7c480-3bdf-11ea-8306-f113bb321bfd.png)
![image](https://user-images.githubusercontent.com/5855073/72778840-a9c18800-3bdf-11ea-916e-a026730745e9.png)

**Comment by turt2live** [comment]
translate.riot.im is where this needs to be fixed - the translations are 100% contributed, and as far as I can tell the same source word is used.

**Comment by aaronraimist** [comment]
Yes but some quality control needs to be applied to the emoji verification words to ensure they are the same across all platforms

**Comment by aaronraimist** [comment]
One translation for every word should be decided on (preferably published in the spec) and then those translations should be not be able to be edited by the community

**Comment by turt2live** [comment]
That would be https://github.com/matrix-org/matrix-doc/issues/2070

**Comment by turt2live** [comment]
(we already have a giant JSON file for all the emoji anyways: https://github.com/matrix-org/matrix-doc/blob/master/data-definitions/sas-emoji.json )

**Comment by bmarty** [comment]
Hi @turt2live ,
I do not understand why you are closing issue which are not fixed?

**Comment by poljar** [comment]
> One translation for every word should be decided on (preferably published in the spec) and then those translations should be not be able to be edited by the community

The translation is plainly wrong, Weizen is wheat, while we do use the corn emoji, meaning Mais is the correct translation.

https://emojipedia.org/ear-of-corn/

**Comment by aaronraimist** [comment]
@poljar Right. That's why I'm saying the correct translation for every emoji verification word should be picked and then the translation should be locked so it cannot be changed.

**Comment by turt2live** [comment]
@bmarty it's an issue for the spec, not Riot in particular. https://github.com/matrix-org/matrix-doc/issues/2070 already tracks the root problem here.
