### ISSUE TITLE
read receipts for author of message shouldn't be shown

### ISSUE THREAD

**Issue by mozbhearsum** [vector-im/riot-web#11979]
**Is your suggestion related to a problem? Please describe.**
Read receipts are shown for the author of a message. Eg:
![image](https://user-images.githubusercontent.com/49649/72813377-347ea300-3c31-11ea-80cc-6b3d82fe0e47.png)

**Describe the solution you'd like**
Don't show read receipts for the author - they clearly read their own message already :).

**Comment by aaronraimist** [comment]
Where would you put the authors read receipt? If you placed it on the message above then it would look like they hadn’t read their own message which I think would be even weirder.

**Comment by mozbhearsum** [comment]
IMO, it doesn't need to be shown anywhere, ever. Authors wrote their own post, so I think it's safe to assume that they read it.

**Comment by mozbhearsum** [comment]
Maybe I misunderstand what read receipts are doing. I thought they indicated that a particular person has seen a particular message. It seems like they're actually indicating how far in the entire channel a particular person has seen. If that's the case, I agree there's probably nothing to be done here (although I still find it confusing).

**Comment by t3chguy** [comment]
Indeed, Read Receipts mark the latest message a user has read, very few apps track read-state per-message as this would a HUGE amount of data for large rooms, and visually cluttered.

**Comment by mozbhearsum** [comment]
Thanks for the info. I'm going to close this given that I filed it under incorrect assumptions!
