### ISSUE TITLE
there's no way to cancel new MemberInfo when you're in it

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11987]
how do i get back to MemberList?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/72899602-41c58b80-3d1e-11ea-864f-035c7ddd1509.png)
There's a `<` button as per the Figma
![image](https://user-images.githubusercontent.com/2403652/72899699-6e79a300-3d1e-11ea-81c5-7d756a27fb5b.png)

Clicking the MemberInfo button in the top right corner works too
