### ISSUE TITLE
User lists iteration

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12000]
Zeplin for reference: https://zpl.io/bPnYrKp
- [x] Only the user list area should be scrollable, with the scroll bar aligned to it, ref Zeplin
- [x] Extraneous 'or' in copy before 'share your username'
- [x] Use a fixed size for the modal to avoid glitching when interacting with 'Show more'
- [x] Completing a search (by clicking on a user, adding them to the list) should remove the search string from input
- [x] Discuss users missing from list

**Comment by turt2live** [comment]
@nadonomy where is this extra 'or'? It seems fine to me:
![image](https://user-images.githubusercontent.com/1190097/72956016-6c820500-3d5b-11ea-8caa-50d08b3c04a5.png)

**Comment by nadonomy** [comment]
<img width="631" alt="Screenshot 2020-01-23 at 10 20 21" src="https://user-images.githubusercontent.com/4626865/72976201-0b454a80-3dca-11ea-84c6-cc9e8f35283f.png">

@turt2live here's what I see in my client, could it be sourcing from a 'translated' string?

**Comment by nadonomy** [comment]
@turt2live ah apologies, I'd noted the problem incorrectly in this issue, just amended the parent to be accurate now.

**Comment by nadonomy** [comment]
@turt2live I have an open DM with someone where we last conversed on Jan 8th & there was a profile picture update event on Jan 17th.

I would expect them to appear in the recently list but they're absent from it, and therefore missing when filtering/searching. Is this expected? Can chat more when you're online to help clarify.

**Comment by turt2live** [comment]
They should be showing up, I think. It's entirely possible that room is afflicted by one of the many bugs related to DMs - is the room listed under People with the DM indicator on it? How many people are in the room?

**Comment by turt2live** [comment]
The DM issue looks like an anomaly which would be fixed by canonical DMs. I'll add some debugging but fixing it is not a blocker for launch (unless of course a bunch more people notice it).
