### ISSUE TITLE
Thought on cheap multiaccount

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12003]
*This should probably be a comment, but this button was closer, sorry.*

We could do some nasty namespacing on the storage side to do different account support. When the user switches accounts, we take the entire working copy of storage and duplicate it into a namespaced version then pull out the new user's storage and overwrite the working copy.

For localstorage this would be something like (caution: from memory, not tested):
```
const currentKeys = Object.keys(localStorage).filter(k => !k.startsWith("m.alt."));
const obj = currentKeys.reduce((i, k) => {i[k] = localStorage.getItem(k); return i;}, {});
localStorage.setItem("m.alt.@currentuser:example.org", JSON.stringify(obj));

for (const key of currentKeys) localStorage.deleteItem(key);
const newObj = JSON.parse(localStorage.getItem("m.alt.@newuser:example.org"));
for (const key in newObj) localStorage.setItem(key, newObj[key]);
```

Then slash commands to switch between/login to accounts.

**Comment by jryans** [comment]
It's an interesting thought, but I've heard @ara4n / product would like to avoid creating a "switch workspace" style experience, so that might rule out an approach like this.

**Comment by turt2live** [comment]
:(

**Comment by turt2live** [comment]
also I'm moving this to the right issue
