### ISSUE TITLE
Show room encryption status as a bubble tile

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12006]
Show the room encryption event as a bubble tile (same style as the new verification timeline):

[Figma](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=2533%3A193)

<img width="276" alt="2020-01-22 at 18 49" src="https://user-images.githubusercontent.com/279572/72923964-f031f680-3d47-11ea-9d76-0bec8c51d8a5.png">

**Comment by dbkr** [comment]
fwiw I think the above is the tile for mobile. Looks like on web it should look like this:

<img width="480" alt="Screenshot 2020-01-30 at 17 12 07" src="https://user-images.githubusercontent.com/986903/73472883-acf90880-4383-11ea-83d6-e616ea23e796.png">

**Comment by dbkr** [comment]
It turns out this is quite complex because encryption events are included in the room creation events summary. In actuality what we probably want is for all the events included in the summary to be turned into a decent summary tile perhaps?

**Comment by jryans** [comment]
I think for this purpose, it's okay to unbundle the encryption event from the summary if that's possible? 

Or is the issue that it occurs in the middle of the bundled set, so it's unclear where it would go in the timeline order?

**Comment by dbkr** [comment]
I was thinking of just dumping the encryption event at the end of the summary, but after asking it looks like we may want something slightly more complex.

**Comment by dbkr** [comment]
ok, I think we have come up with something!

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/3237)
