### ISSUE TITLE
Copy from compose box does not work on riot.im/staging

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#12018]
### Description

Unable to copy/paste from the message edit bar.

### Steps to reproduce

- Type something into the message bar.
- select the text, ^C to copy, or rightclick -> copy
- attempt to paste

Describe how what happens differs from what you expected.

Nothing is pasted.

In comparison i'm able to copy message bodies from elsewhere in the page via ^C or rightclick -> copy.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 72.0.1
- **OS**: Linux/ubuntu
- **URL**: riot.im/staging

**Comment by turt2live** [comment]
Don't know why github didn't close this - https://github.com/matrix-org/matrix-react-sdk/pull/3922
