### ISSUE TITLE
Bootstrapping breaks if cross-signing keys in SSSS but not uploaded to server

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12019]
Bug 1:
Bootstrapping gets confused in this case because it sees keys in SSSS but then gets confused when the user has no keys registered with the server.

Bug 2:
The 'complete security' flow appears to have succeeded in this case even though it threw an exception

Bug 3:
It's possible to get an account in this state, probably if you cancel when asked for you account password to upload cross-signing keys (although it's not clear what the correct behaviour should be here - perhaps this is correct and we should be prompting for the SSSS passphrase then picking up where the process left off and uploading those keys).

For the cross-signing sprint we should at least make sure cancelling the auth prompt for key upload doesn't leave your account in an unrecoverable state.

**Comment by jryans** [comment]
Seems like something we should investigate after FOSDEM.

**Comment by dbkr** [comment]
Unsure how I got it into this state as it appears to upload SSSS keys after uploading cross-signing keys. May have been something I did locally which got it into that state, so this shouldn't be a problem in practice, so yep, safe to leave until after fosdem.

**Comment by jryans** [comment]
> For the cross-signing sprint we should at least make sure cancelling the auth prompt for key upload doesn't leave your account in an unrecoverable state.

This case appears to work correctly: cancelling the auth prompt stopped the entire bootstrap operation as expected, since the auth step is attempted first. I am still able to restart bootstrap after cancelling.

Overall, this seems to be working now, but let's file new issues if we find something is still not right here.
