### ISSUE TITLE
How to set myself as away

### ISSUE THREAD

**Issue by armenzg** [vector-im/riot-web#12010]
On IRC & Slack, I could set myself as away with a message like "I will be back tomorrow". [1][2]
On Slack I can even set by when should such message be cleared (e.g. 1 week). [3]

Is there a way for me to do the same on Riot Desktop?
Is changing the nickname the way?

[1]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/44410/72936494-4a758c00-3d35-11ea-834e-9911e92ca4dd.png">
[2]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/44410/72936438-329e0800-3d35-11ea-8cb2-cbd5dec7c217.png">

[3]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/44410/72936413-23b75580-3d35-11ea-8696-a2d7ecee5664.png">

In either case, a user trying to contact me would realize that I won't be getting back to them.

**Comment by turt2live** [comment]
Currently this isn't possible, but would be in https://github.com/vector-im/riot-web/issues/478
