### ISSUE TITLE
URL previews in Slack for Riot deeplinks are horribly large

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12014]
We need to tweak the OG to show the right logo (if present) and ensure it's not mahoosive.

<img width="463" alt="Screenshot 2020-01-22 at 18 39 59" src="https://user-images.githubusercontent.com/1294269/72952449-bf04f680-3d46-11ea-8d92-2f169b7bd45c.png">

**Comment by foldleft** [comment]
Found a handy reference: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

**Comment by foldleft** [comment]
It's gonna take a minute for this to go all the way to production, so we may have to leave this ticket open for a while

**Comment by foldleft** [comment]
oops, this shouldn't have closed

**Comment by jryans** [comment]
Here's what I now see in Slack:

<img width="490" alt="2020-05-13 at 13 01" src="https://user-images.githubusercontent.com/279572/81809934-055eab00-951a-11ea-9d99-7bf95265b434.png">

Seems pretty good...?

**Comment by foldleft** [comment]
well at least one thing is fixed

**Comment by foldleft** [comment]
thanks for checking! I guess I'll close this
