### ISSUE TITLE
Error when clicking "add reaction"

### ISSUE THREAD

**Issue by mythmon** [vector-im/riot-web#12027]
### Description

I clicked the "add reaction" button a message, and received an error page.

### Version information

- **Platform**: Web

For the web app:

- **Browser**: [RamboxPro](https://rambox.pro)
- **OS**: Fedora Linux
- **URL**: chat.mozilla.org

**Comment by mythmon** [comment]
I tried to submit a debug log via Riot. I assume it was logged in a non-public place?

**Comment by aaronraimist** [comment]
> I assume it was logged in a non-public place?

That's correct

**Comment by turt2live** [comment]
Unfortunately Rambox is not one of our supported platforms. Specifically, the browser is missing `Object.fromEntries` and that's making things angry.
