### ISSUE TITLE
Can not delete devices

### ISSUE THREAD

**Issue by hwine** [vector-im/riot-web#12028]
### Description

Delete device workflow errors and does not delete device

### Steps to reproduce

- Navigate to "Settings" -> "Security & Privacy"
- select a device to delete
- click the "delete device" button
- observe "No appropriate authentication flow found" message with "dismiss" button
- click "dismiss" button
- observe devices still in list, and selected

My expectation is that the devices would be removed from the list.

Logs being sent: yes

![image](https://user-images.githubusercontent.com/132412/73015253-8447a080-3dd0-11ea-84db-078eb5165f60.png)

### Version information
- **Platform**: web

- **Browser**: Firefox 74.0a1 (2020-01-22) (64-bit)
- **OS**: Windows 10
- **URL**: https://chat.mozilla.org/#/room/#general:mozilla.org

**Comment by jryans** [comment]
Thanks for the report! Yes, this is specific to SSO deployments like the Mozilla instance, and it is waiting on a server-side fix in https://github.com/matrix-org/synapse/issues/5667 (which is actively being worked on).

**Comment by wagnerand** [comment]
Is this live of Mozilla's instance already?

**Comment by jryans** [comment]
> Is this live of Mozilla's instance already?

Not yet, still a few more steps to go. We'll be sure to shout in #synchronicity:mozilla.org when it is available there.

**Comment by jryans** [comment]
@wagnerand and others here: SSO support for deleting devices, adding email addresses, and other such features should now be working on Mozilla's deployment. Please file new issues if problems remain.
