### ISSUE TITLE
Revise DM decoration to match designs

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12035]
@nadonomy's feedback on DM decoration:

* Rename 'People' section of the room list to 'Direct Messages' (which reenforces the model for users that these rooms are implicitly private)
* Don't use user icons on users as they're redundant, instead decorating with shields (which reenforces (a) that verification is user:user & (b) the trust level of that user)
* Don't use padlocks in DM room names, as they're implicitly private
* If a DM room is being displayed in favourites, again don't use padlocks as they're implicitly private already

**Comment by foldleft** [comment]
Oops, DM icons are going away entirely!
