### ISSUE TITLE
"verify own device" ux refinements

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12038]
- [ ] timeout in toast is rendered as 0
 - [ ] wording in device dialog refers to users when verifying own device

#### Timeout in Toast
The flow to trigger this isn't clear, but I've definitely set it off.  I think it's a flow that happens outside of the sign-at-login flow.  Possibly the toast appears after completing the cross-verify flow, which it probably shouldn't be doing, but if it does, it should show the right timer.

Expected: the toast shows a countdown timer, which counts down
Actual: the toast displays `0`

#### Wording in device dialog
* Device **A** is already logged in
* Device **B** logs in
* Device **A** gets a toast and clicks `Review`
* Device **A** clicks `begin verifying`
* Device **B** sees a new screen with text reading "Verify this user to mark them as trusted. Trusting users gives you extra peace of mind when using end-to-end encrypted messages."

Expected: The text explains that the user is verifying a device on their account
Actual: The text explains that the user is verifying another user

See also: https://github.com/vector-im/riot-web/issues/12106 for this flow; that task can probably be resolved at the same time

**Comment by foldleft** [comment]
could you clarify the task? I couldn't see any timeout for the toast:
<img width="320" alt="Screenshot 2020-01-28 at 13 38 31" src="https://user-images.githubusercontent.com/3935731/73269651-21da1000-41d5-11ea-948b-40153ae50e36.png">

**Comment by foldleft** [comment]
update: looks like we have two issues here
1. nothing happens when the countdown reaches zero (though it does count down)
2. the component is mounting with a timeout of zero, as well
