### ISSUE TITLE
Should be able to view E2E info and verify users in MemberInfo, even if the room is unencrypted

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12030]
Even if they're unencrypted

**Comment by t3chguy** [comment]
> I think the devil is in the execution details on this— I'd prefer to detail some copy & comps for these states before you start lifting code, does that work for you?

**Comment by ara4n** [comment]
This is *constantly* tripping me up. I want to see what devices a user has; i go to their MemberInfo, and look blank because i'm in an unencrypted room.  I want to verify them; similarly.

@nadonomy do you agree MemberInfo should show the same whether it's in an encrypted room or not?

**Comment by nadonomy** [comment]
> @nadonomy do you agree MemberInfo should show the same whether it's in an encrypted room or not?

Yup. I'm not sure if it's as binary as displaying the exact same thing though, will review the micro copy and figure out what other changes (if any) are needed.

**Comment by ara4n** [comment]
this continues to massively trip me up - c.f. the related mess in https://github.com/vector-im/riot-web/issues/12850#issuecomment-603469629

**Comment by nadonomy** [comment]
Having looked at the user journey in more detail, when viewing users in unencrypted rooms, we need to vary the copy in 3 places, detailed below.

@jryans @manuroe @BillCarsonFr what's the best way to track this cross-platform? Are you ok to echo the issue across respective repos?

----

### 1. Viewing profiles

_E2E:_ Messages in this room are end-to-end encrypted.
_Non E2E:_ Messages in this room are not end-to-end encrypted.

### 2. Before verifying

After clicking [Verify], before clicking [Start Verification]

_E2E:_

> Messages in this room are end-to-end encrypted.
> 
> Your messages are secured and only you and the recipient have the unique keys to unlock them.

_Non E2E:_

> Messages in this room are not end-to-end encrypted.
> 
> In encrypted rooms, your messages are secured and only you and the recipient have the unique keys to unlock them.

### 3. After verifying

_E2E:_ Verify all users in a room to ensure it’s secure.
_Non E2E:_ In encrypted rooms, verify all users in a room to ensure it’s secure.

**Comment by jryans** [comment]
> @jryans @manuroe @BillCarsonFr what's the best way to track this cross-platform? Are you ok to echo the issue across respective repos?

At the moment, our approach is each team filing issues in their repos as needed and labelling for the story. It does take some vigilance to avoid things falling in the cracks, so something to ponder for the future.
