### ISSUE TITLE
Message panel can be completely collapsed

### ISSUE THREAD

**Issue by Pinksys** [vector-im/riot-web#12044]
### Description

The left panel can be expanded all the way to the right panel (and vice versa for the right to left panel) so that the message panel is completely out of sight.  Attempting to drag the panel back is tricky since the hit boxes of the right and left panel edges seem to overlap.  

### Steps to reproduce

- drag the right edge of the left panel all the way over to the right panel
- the middle panel is now hidden behind the two side panels

Logs being sent: no, not necessary

![bug](https://user-images.githubusercontent.com/17036774/73086291-5df03680-3e9e-11ea-88d9-58823f8e5abf.png)

A simple fix would be to set  max-width attributes (for .mx_RightPanel and .mx_LeftPanel, which are both located in:

matrix-react-sdk/res/css/structures/

### Version information

- **Platform**: web
- **Browser**: Bug appears in Firefox Quantum 68.3.0esr and Chrome 78.0.3904.108
- **OS**: CentOS 7
- **URL**: riot.im/app, riot-web version 1.5.7, olm version 3.1.3

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4692
