### ISSUE TITLE
Twemoji isn't used in SAS verification in 'complete security' dialog

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12056]
We only install Twemoji in LoggedInView and we haven't got there yet

**Comment by turt2live** [comment]
can we just apply it ot `body`?

**Comment by dbkr** [comment]
Unfortunately it is done with the magic colr font detection code, so it is that the code has not run yet.

**Comment by ara4n** [comment]
bruno fixed in https://github.com/vector-im/riot-web/issues/12807
