### ISSUE TITLE
Invite to this room shouldn't suggest users who are already in the room

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12051]
<img width="1200" alt="danny" src="https://user-images.githubusercontent.com/5855073/73115107-99fbb980-3ee7-11ea-96bf-6889a59a46b9.png">

Clicking the Invite to this Room button in `#riot-web:matrix.org` suggests Danny, who is already in the room and was the last person to speak.

**Comment by turt2live** [comment]
:( there's code explicitly to handle this, but clearly it's not working.
