### ISSUE TITLE
Add testing button to remove cross-signing

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12069]
At least for testing (but perhaps after as well), it's helpful to have a clear way to remove your cross-signing identity. We should add a testing button in Settings.

**Comment by dbkr** [comment]
This might need spec support - I don't think there's a way to remove your published cross-signing keys: only change them.

**Comment by jryans** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/12221
