### ISSUE TITLE
1.5.8. webchat needing newer webfeatures? doesnt work with firefox 52.9.1 any more, 1.5.7 did fine?

### ISSUE THREAD

**Issue by subscribernamegoeshere** [vector-im/riot-web#12074]
### Description
Was ha happy riot webchat user as well in adition to android app. Webchat so far was probably 1.5.7, which worked nicely on a dated firefox 52.9.1 esr windows system, which cant use newer firefox releases.

today riot webchat (with matrix.org username account) wanted to update itself. after the update the riot page showed my me session data or browser storatge data was incompatible with this newer riot application and I needed to logout in red button or something like that. after I logged out and tried to re-login from scratch, the submit of username/passwod doesnt log me in at all any more. Doesnt load or bring up my own chatroom etc. what happened?

windows xp, firefox 52.9.1 esr, nothing unusal that didnt work with 1.5.7 previously. Now with 1.5.8 release I am hosed? :(

**Comment by subscribernamegoeshere** [comment]
What are the requirements for webbrowsers, features or releases of the main browser manufacturers that every riot webchat release works with? 

shouldnt during an update such warnings be issued? thanks.

**Comment by turt2live** [comment]
> Riot is officially supported on the web in the last 2 major versions of Chrome, Firefox, and Safari. 

From the README for the project. We've only supported the last 2 versions of major browsers for quite some time now, and 1.5.8's build system helped enforce this. Unfortunately, Firefox 52 is about 20 versions out of date for us to support right now.

In theory there should have been a different warning saying your browser is missing features, not that your session was incompatible. Your username/password not working anymore would be a dfferent issue.

Also, Windows XP has never been a supported version for us.
