### ISSUE TITLE
Add option to hide verification UI

### ISSUE THREAD

**Issue by squidink7** [vector-im/riot-web#12072]
Riot's verification process is good from a security perspective, but every time I convince a friend to switch to Matrix/Riot, I keep hearing over and over "why do I need to verify your devices? I didn't need to do that on [previous_messaging_client], we should move back to that". Now that cross-signing is just around the corner it should improve a lot, however for simple communication between friends/family, it is not really necessary to have a whole system set up to make sure every device is trusted. As long as I still have access to my device list and can remove any untrusted ones that is enough.

So if there was a way to easily turn off/hide the verification UI I would have a much easier time convincing my friends to switch from the previous (much less secure) platform to Riot.

**Comment by turt2live** [comment]
Cross-signing disables a lot of this verification UI you're speaking of, in favour of communicating through shields. For instance, iirc a black shield means the room is encrypted but you haven't verified anyone. Red means there's unverified users in the room, and green means everyone is verified. No more constant prompts about unknown devices, etc littering your view. You still retain the ability to remove bad devices from your account, though the perspective has changed from verifying devices to verifying people.

Does that sounds like the sort of experience you were looking for?

**Comment by squidink7** [comment]
> Cross-signing disables a lot of this verification UI you're speaking of, in favour of communicating through shields. For instance, iirc a black shield means the room is encrypted but you haven't verified anyone. Red means there's unverified users in the room, and green means everyone is verified. No more constant prompts about unknown devices, etc littering your view. You still retain the ability to remove bad devices from your account, though the perspective has changed from verifying devices to verifying people.
> 
> Does that sounds like the sort of experience you were looking for?

It is very close, although every time I open the site it prompts me to verify my own devices, which there is no obvious way to disable.

**Comment by turt2live** [comment]
That's intentional, and should be done for the safety of your encrypted messages (aiui).

**Comment by squidink7** [comment]
But as far as I am aware, verification doesn't affect riot's behaviour. So if everyone has a good password and knows that they are the only ones with access to their account, it is irrelevant, right?

**Comment by t3chguy** [comment]
Verification in cross-signing is whether or not other users should trust your devices to be yours, so it very much is different

**Comment by squidink7** [comment]
Ok, I understand. It just feels clunky and unintuitive for new users when they have to go and verify the devices that they just signed into so others know that their phone and laptop is really theirs.

**Comment by turt2live** [comment]
I guess that could be annoying. I've added it to our internal tracking doc on this for review. For now though I'm closing this as working as intended, and will reopen/open a new issue if it needs to be fixed.

**Comment by t3chguy** [comment]
its to prevent your server being compromised and logging in as you, and also your account password being cracked

**Comment by Octelly** [comment]
So, any plans to add an option to disable the shield UI at least for bridge messages?
Participating on Discord chats where most people are bridged and seeing everything in red is seriously distracting and annoying.
