### ISSUE TITLE
Possibly not warning on unsigned self-devices

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12077]
I logged in a new user (on riot.im/app) and verified but failed to cross sign – their messages are still shown as non-alarming but the user panel says they're not verified.

It's not clear if there's underlying device-to-device trust being shown as untrusted in the right hand panel for our own user, or if there's a lack of device-to-device trust being shown as okay in the messages.  That said – total failure to verify seems to result in alarms.

**Comment by jryans** [comment]
@foldleft, any further details on this one? Are we at the investigation stage, or do we have some hints of what's wrong already?

**Comment by jryans** [comment]
Sounds like core issue here is that resetting cross-signing only makes the user go black instead of red. Filed https://github.com/vector-im/riot-web/issues/12808 for this.
