### ISSUE TITLE
Members button no longer closes the MemberInfo sidebar

### ISSUE THREAD

**Issue by foresto** [vector-im/riot-web#12088]
### Description

In riot-web 1.5.8, the Members button no longer closes the MemberInfo sidebar. It will close the sidebar if the MemberList is shown, but not if a member's details are shown. This is a regression since 1.5.7.

### Steps to reproduce

- Enter a room
- Click the Members button at the top of the screen and then click a member from the list. (Or just click someone's icon in the chat.)
- Click the Members button at the top of the screen again.

This used to close the side panel. Now it does nothing.

### Version information

1.5.8

- **Platform**: web and desktop

For the web app:

- **Browser**: Firefox 72.0.1
- **OS**: Xubuntu 19.04
- **URL**: https://riot.im/app/

For the desktop app:

- **OS**: Xubuntu 19.04
- **Version**: 1.5.8

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/3804
