### ISSUE TITLE
Encryption upgrade popup copy is wrong

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#12089]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/8582858/73213778-6e124b00-4116-11ea-839b-81d533b931b8.png">

 Surely 'Verify your other devices easier' is not proper english???

**Comment by ara4n** [comment]
"Verify your other devices more easily"

**Comment by jryans** [comment]
Tagging @nadonomy in case he has a preference, otherwise I suppose we'll go with @ara4n's suggestion.
