### ISSUE TITLE
Message placeholder stays as 'send a reply' after sending a reply

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12093]
Typing some text and deleting it, or sending another message, clears is back to normal. Likely to do with the cross-signing labs flag

**Comment by t3chguy** [comment]
Bug is actually with BasicMessageEditor not applying the prop:

![image](https://user-images.githubusercontent.com/2403652/73408563-8770ee00-42f4-11ea-947d-d93dd0ece496.png)
