### ISSUE TITLE
Placeholder encryption text doesn't update

### ISSUE THREAD

**Issue by yesennes** [vector-im/riot-web#12090]
### Description

When Encryption is enabled for a room, the placeholder text doesn't update.

### Steps to reproduce

- Create a new room
- Enable E2E encryption

I would expect the text that appears in the empty message box to update to encrypted.
Typing text and deleting it will make it appear correctly, but there's no good reason I can see to require that.

Looking at the code, the problem seems to be that in [BasicMessageComposer](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/BasicMessageComposer.js#L158) `_showPlaceholder()` isn't called until an editor update is triggered. I would suggest (and can implement) in the `render()` method checking if the model is empty and applying the proper styling and classes to the div if so.

Logs being sent: yes

![image](https://user-images.githubusercontent.com/10568297/73213220-d9135000-411d-11ea-8d81-0eb64d1b46c4.png)

### Version information

- **Browser**: Chrome 78.0.3904.97
- **OS**: Centos7
- **URL**: https://riot.im/app

**Comment by t3chguy** [comment]
This is already fixed in Labs with Cross Signing (by way of using props for the update)
