### ISSUE TITLE
can't create a private room with oneself anymore

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#12092]
click create room, invite myself, get an error msg 'Failed to invite the following users to chat: @Amandine:matrix.org'. Click on new DM, invite oneself, there is a loading wheel and then it fails silently

**Comment by aaronraimist** [comment]
Basically a duplicate of https://github.com/vector-im/riot-web/issues/4833, it just fails in a different way now

**Comment by turt2live** [comment]
(the new dialog is supposed to be a little more forgiving in this)

**Comment by aaronraimist** [comment]
This seems to work now

**Comment by turt2live** [comment]
Indeed, seems to work.

**Comment by turt2live** [comment]
This doesn't actually work as expected: it pukes errors when you invite yourself now.
