### ISSUE TITLE
're-request encryption keys' doesn't appear to work with cross-signing

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12104]
Using (only) two riot-web instances, I found that cross-signing a device directly leaves it unable to re-request keys; doing a cross-verify does let this work. I surmise that it only works with direct-device verification, and may be a moot point if the user enters the backup key.

Probably this represents one of two actions:
* Hide the "re-request keys" button if cross-signing is on
or
* We're not connecting to the key backup when we should be

**Comment by jryans** [comment]
This should be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1243.
