### ISSUE TITLE
don't verify individual devices for oneself

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12107]
if you navigate to your own user in the right hand panel, expand your own devices and click 'verify', you'll start a verification which immediately gets stuck. special-case this for when the user is looking at her own devices

**if you click here,**
<img width="346" alt="Screenshot 2020-01-28 at 13 54 22" src="https://user-images.githubusercontent.com/3935731/73270093-f60b5a00-41d5-11ea-85ce-5268b490179f.png">

**this shouldn't appear**
<img width="854" alt="Screenshot 2020-01-28 at 13 54 26" src="https://user-images.githubusercontent.com/3935731/73270133-00c5ef00-41d6-11ea-9f7b-7a66a9efb802.png">

**Comment by jryans** [comment]
@foldleft, can you elaborate on why it should not appear? I think that's how verifying own devices at the moment. You can either reach it via the new toast or going to your own user info (the path described here).

**Comment by foldleft** [comment]
This may be another bug, then. It gets stuck after this screen!

**Comment by bwindels** [comment]
let's retest this once `travis/wip/qr` is merged, as I'm 99% sure this worked for the demo. Was this 100% reproduceable for you @foldleft ?

**Comment by bwindels** [comment]
Now that the above mentioned branch has landed, let's see if this is still a problem. I can't repro this personally. How about you, @foldleft ?

**Comment by foldleft** [comment]
yup, this now goes through a cross-signing flow and the other device gets cross-signed :D
