### ISSUE TITLE
Allow blurbs for users

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#12105]
User names may not be familiar, and are not the place for explanations.  Robots might have a global blurb explaining what they do.  Human users might have a global blurb, and then per-room specific blurbs informing how they are relevant to that room - knowledge, opinions/position, formal status, ..

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/1401

**Comment by Biep** [comment]
It was indeed a duplicate, but rather of #7704
I added the bit about hierarchy there.
