### ISSUE TITLE
rendering issue in the sign-in verification flow

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12106]
I initiated a verification from another riot-web instance. the instance signing in rendered as per the image
<img width="760" alt="Screenshot 2020-01-28 at 13 38 43" src="https://user-images.githubusercontent.com/3935731/73269577-fd7e3380-41d4-11ea-8bc4-a59178bfd230.png">

**Comment by jryans** [comment]
@foldleft, can you describe how you reached a verification flow at sign-in...?

Did you login, stop at complete security, then go to existing device and try to verify the new session?

**Comment by foldleft** [comment]
Sure

**A: Log in with a new device and stop here** (private mode, which may be germane)
<img width="699" alt="Screenshot 2020-01-28 at 16 38 32" src="https://user-images.githubusercontent.com/3935731/73284588-b865fb80-41ec-11ea-99c7-b01eb2ea56c9.png">

**B: click `review` toast here**
<img width="379" alt="Screenshot 2020-01-28 at 16 38 35" src="https://user-images.githubusercontent.com/3935731/73284590-b8fe9200-41ec-11ea-9063-39adf68d1aa8.png">

**B: click `begin verifying` here**
<img width="877" alt="Screenshot 2020-01-28 at 16 38 39" src="https://user-images.githubusercontent.com/3935731/73284591-b8fe9200-41ec-11ea-8c77-b95d245a94cb.png">

**A: proceeds automatically to this screen**
<img width="862" alt="Screenshot 2020-01-28 at 16 38 45" src="https://user-images.githubusercontent.com/3935731/73284592-b8fe9200-41ec-11ea-84d7-43bb1ff4d714.png">
