### ISSUE TITLE
Local Echo for cross-signing verification

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#12116]
provide local echo for button clicks as now the VerificationRequest only relies on events coming from the server and doesn't have local echo anymore.

**Comment by t3chguy** [comment]
Split out from https://github.com/vector-im/riot-web/issues/11970

**Comment by bwindels** [comment]
This has been done as part of `travis/wip/qr` (aka the demo branch) but only locally for a component. E.g. if you click accept on the timeline tile it will disable the button there, but not in the toast, the toast will only disappear once the remote echo is received. We should probably add something to VerificationRequest that at least prevents double submission of the same event.
