### ISSUE TITLE
Can't turn mxid into pill by pressing enter in new invite dialog

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12118]

**Comment by bwindels** [comment]
![newinvitefullmxid](https://user-images.githubusercontent.com/274386/73341140-f35f4200-4273-11ea-9bf8-c28c1b38065d.gif)

typing a full mxid in the field, and then pressing enter removes the mxid from the field without turning into a pill. Pressing backspace strangely enough brings back the mxid text. Clicking on the suggested pill below was the only way I could find to get a pill to appear in the text field.

**Comment by turt2live** [comment]
would be handled in https://github.com/vector-im/riot-web/issues/11771
