### ISSUE TITLE
You can't cancel a verification request in the right panel

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12123]

**Comment by t3chguy** [comment]
how should we be able to?

**Comment by turt2live** [comment]
a random suggestion would be that exiting the panel does a cancel for you, as does leaving the panel through other means (room switches, etc). If for some reason there's a verification not going on in the panel and it hasn't been cancelled, just put a cancel button on the event tile.

**Comment by t3chguy** [comment]
I suggested that in Riot Web Internal and was told that in future if you close the panel a toast will come up prompting you to resume verification

**Comment by turt2live** [comment]
sure, that's fine. Really the longer ask here is that there's some way to say "actually no I don't want to verify this person" and to avoid random in-flight sessions all over the place.

**Comment by t3chguy** [comment]
I guess it could be close sidebar, toast opens, click Dismiss on toast

**Comment by turt2live** [comment]
possibly. This is almost certainly something that needs actual product review and not random developer suggestions (particularly from me)

**Comment by bwindels** [comment]
It should probably be fairly explicit if we want to add this option, like an X button in the verification panel or a cancel button?

**Comment by bwindels** [comment]
This was implemented in https://github.com/matrix-org/matrix-react-sdk/pull/4283
