### ISSUE TITLE
Reports of right panel getting confused with verifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12128]

**Comment by jryans** [comment]
@turt2live, can specify any further detail here? A particular sequence of events? What does confused mean?

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/73655459-0617b380-4686-11ea-86fa-5181a3f5daca.png)

@BillCarsonFr where's those reproduction steps? :p

**Comment by jryans** [comment]
I have a feeling this is already tracked by one of @bwindels's existing issues.
