### ISSUE TITLE
can't send message in encrypted room

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12120]

**Comment by bwindels** [comment]
Trying to send a message in an encrypted DM, the messages appear in the timeline but stay pending (grey) and the text stays in the composer after sending. I looked in the console and saw this error:

```
TypeError: "timeline is null"
    _checkForPreJoinUISI TimelinePanel.js:1177
    _getEvents TimelinePanel.js:1133
    onMessageListFillRequest TimelinePanel.js:389
```

Rageshake (originally for other issue but sent around the same time as this occured): https://github.com/matrix-org/riot-web-rageshakes/issues/2158

**Comment by bwindels** [comment]
After some refreshing (and having sent a message through /app in the same DM), the error doesn't seem to occur anymore.

**Comment by jryans** [comment]
I am quite sad about this, since it's precisely the thing I assured @uhoreg was not possible during review... 😭
