### ISSUE TITLE
Can't verify my session on login

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12122]
I get the 'complete security' dialog, but clicking 'start' doesn't seem to do much. There's a passphrase dialog, but nothing beyond that

**Comment by jryans** [comment]
Any errors or hanging network requests?

**Comment by turt2live** [comment]
literally nothing.

**Comment by dbkr** [comment]
I can't repro this - may be a state your account has got itself into. I've added https://github.com/matrix-org/matrix-react-sdk/pull/4009 to log the exception: please try again!

**Comment by jryans** [comment]
@turt2live, please retry when you have a moment.

**Comment by turt2live** [comment]
I did this a bunch over FOSDEM and it seemed fine. Probably developer error on my part.
