### ISSUE TITLE
Support HTTP Basic Auth on custom homeserver url

### ISSUE THREAD

**Issue by abliss** [vector-im/riot-web#12136]
**Is your suggestion related to a problem? Please describe.**
I'm trying to run my own matrix homeserver, secured by HTTP Basic Authentication. When I enter a custom homeserver url in the riot.im web app, e.g. `https://user:pass@example.com`, it seems to strip out the user and password, so its requests to the homeserver all fail with status 401.

**Describe the solution you'd like**
the webapp should support HTTP basic auth.
 
**Describe alternatives you've considered**
I also tried the riot and riotX android apps, and they also don't seem to work with basic auth.
I'm currently not able to host the matrix server in my environment without basic auth.  

**Additional context**
I would be happy to try to send a PR for this feature, if it would be welcome.

**Comment by t3chguy** [comment]
I think this will conflict with the Auth system in Matrix which also uses the `Authorization` HTTP header so this is simply not possible.

**Comment by abliss** [comment]
FYI, stepping through the JS, it seems that the user:password is being scrubbed from the url in _sanitizeWellKnownUrl here: https://github.com/matrix-org/matrix-js-sdk/blob/0f1f18b23291124489000a61ff1f0e69e379326a/src/autodiscovery.js#L243

**Comment by t3chguy** [comment]
that's for wellknown discovery, if you manually enter a HS url then this isn't the right codepath

**Comment by jryans** [comment]
I assume this would at least require a spec change @turt2live? If so, then the spec process seems like a better place for this.

**Comment by turt2live** [comment]
Yea, it would be a fairly significant spec change. Closing this for now in favour of an MSC (matrix.org/spec/proposals)
