### ISSUE TITLE
Verifying a new session from the existing device causes 2 verification flows

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12138]
An incoming verification request shows up over top of the sign in form, and after that you're left with a confirm emoji screen.

**Comment by jryans** [comment]
This should only be happening when the new session doesn't have the labs flag enabled when the verification request is received. Once we've enabled it by default at the config level, this should go away...

I suppose it would still be an issue for self-hosted installs that don't enable the flag but do have SSSS though.

**Comment by turt2live** [comment]
Yea, this is fixed by turning on the flag in the config. I'd consider this acceptable for not-labs-with-SSSS environments though, so closing. It'd be fixed when we finish shipping the thing, and it's kinda the operator's fault for not turning on the flag for the thing they're trying to install.
