### ISSUE TITLE
User directory doesn't always return useful results for most of an mxid

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12143]
If I search for `@someone:matrix.or` it should figure out that I mean matrix.org

**Comment by turt2live** [comment]
Fixing this in Synapse is hard, so might have to fix it in the client, somehow.

**Comment by neilisfragile** [comment]
It's more that its not a quick hack, it needs some thought on how changing postgres's search will impact all use cases (and not cause the db to melt) - so I think Synapse should be fixing this, but as part of FTUE rather something to land in the next few days.

**Comment by turt2live** [comment]
I think we can improve the client scoring for this without too many changes to Synapse, maybe.

**Comment by turt2live** [comment]
Closing as this is the wrong issue tracker for this.
