### ISSUE TITLE
UI Suggestion: Add globe next to public rooms

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#12148]
Having the lock icon is kinda nice to differentiate public vs private rooms in the member list (though I still find it a bit odd that it doesn't indicate encryption, but that is probably just me).

However, I do now find something a bit jarring when scanning the room list:

![screenshot-2020-01-30_120037_339x101](https://user-images.githubusercontent.com/8428120/73448672-4828b880-4359-11ea-886f-a97ba50f4275.png)

I think its some combination of room name no longer being aligned and the lock icon being quite heavy compared with room names and so draw the either.

An example of where we align them:

![screenshot-2020-01-30_120951_331x96](https://user-images.githubusercontent.com/8428120/73448796-9473f880-4359-11ea-877c-a2a15ca889e8.png)

An example if we add globes for public rooms:

![screenshot-2020-01-30_121307_334x101](https://user-images.githubusercontent.com/8428120/73448924-e87edd00-4359-11ea-8740-f87da9dfbd4f.png)

![screenshot-2020-01-30_121430_336x107](https://user-images.githubusercontent.com/8428120/73449027-267c0100-435a-11ea-88f0-84b8cc70a7af.png)

Equally, we may expect public rooms to be the exception for majority of users, in which case it might make sense to only have an icon for public rooms:

![screenshot-2020-01-30_121649_346x97](https://user-images.githubusercontent.com/8428120/73449157-765ac800-435a-11ea-849f-7747fd221e97.png)

**Comment by ara4n** [comment]
having been deluged with padlocks, i certainly like the “globe = warning, this is public” idea rather than putting padlocks everywhere

**Comment by aaronraimist** [comment]
> Having the lock icon is kinda nice to differentiate public vs private rooms in the member list (though I still find it a bit odd that it doesn't indicate encryption, but that is probably just me).

It's not just you. I find it very confusing.

I think globes are maybe a good idea but I'd like the option to not have either of these icons in the room list. Why do I need to know whether all the rooms in my list are public or not? and why is that status more important than the name of the room (before the name of the room)?

It seems like I would only need to know if a room is public or not when I am actually in the room. Why isn't this icon in the composer or the top of the page rather than the room list?

**Comment by jryans** [comment]
> Why isn't this icon in the composer or the top of the page rather than the room list?

At the moment, it actually also appears in the room header as well as each room list tile.

**Comment by erikjohnston** [comment]
@ara4n 

> having been deluged with padlocks, i certainly like the “globe = warning, this is public” idea rather than putting padlocks everywhere

Yeah, I also think it may be less confusing to new non-techy users. People who have joined public rooms likely understand the difference between public/private rooms, and thus can understand the presence of the globe. Users who have joined and only use private rooms or DMs (e.g. whatsapp style) may get confused why everything is marked as private if they don't know you can do public rooms.

OTOH maybe that is a way to educate such users, though my personal bias would be that it'd be better to keep such a UI as uncluttered and simple as possible.


@aaronraimist 

> I think globes are maybe a good idea but I'd like the option to not have either of these icons in the room list. Why do I need to know whether all the rooms in my list are public or not? and why is that status more important than the name of the room (before the name of the room)?

I think the padlock may be just a bit too heavy atm and draws the eyes. If it was subtler the room name/avatar would remain the more prominent info. Something like:

![screenshot-2020-01-31_102300_178x37](https://user-images.githubusercontent.com/8428120/73532091-d6617500-4413-11ea-853a-8e92254b8206.png)


> It seems like I would only need to know if a room is public or not when I am actually in the room. Why isn't this icon in the composer or the top of the page rather than the room list?

I'm actually finding it quite useful in work contexts to make it easier to find internal rooms vs our public ones. I imagine the say would be true for others using it for work.

**Comment by notramo** [comment]
It would be confusing also to current Riot users as Riot is using padlocks for encryption currently.

**Comment by t3chguy** [comment]
> Padlocks would be confusing also to current Riot users as Riot is using padlocks for encryption currently, so +1 for the globe icon.

Where is riot using padlocks for encryption?

![image](https://user-images.githubusercontent.com/2403652/76401317-962dd480-6379-11ea-9648-4fda57539f34.png)

**Comment by notramo** [comment]
Riot Android

**Comment by notramo** [comment]
Also, don't forget that other encrypted services and tools e.g. ProtonMail, Mailvelope, Claws Mail, etc. are using padlocks as encryption symbol, so using it with a different meaning in Riot would be worse FTUE.

**Comment by t3chguy** [comment]
Riot Android is on its way out of the door, it is only still available because riotX is not yet feature-complete.

**Comment by notramo** [comment]
I wrote "current Riot users". That means the old Riot Android. When they will upgrade to RiotX, they will be confused also.
Keep in mind that RiotX is at least a year away from replacing the old Riot Android. That means that Android users will be confused for a year (and non-techie users will struggle to remember the meaning of the padlock symbol).
**Also, it doesn't change the relevance of my previous comment.**

**Comment by fooness** [comment]
We should prefix public rooms with `#` and non-public rooms with a lock. That’s basically a standard by now.

**Comment by notramo** [comment]
Please don't use _lock symbol_ for indicating invitation-only rooms. **It's the widely accepted symbol for indicating _encryption_.** 
The following is a list of services/software, that uses **lock for indicating encryption**:
- ProtonMail
- Claws Mail
- Tutanota
- Mailvelope
- Delta Chat
- Threema
- Signal

**Comment by steef435** [comment]
Maybe it's a bit too much to make another issue related to this, but I think the padlocks as they are right now are confusing, apart from them breaking the reading flow (I think any of erikjohnston's suggestions would work wonders here).

The padlocks actually have _more_ agency than the encryption shields, which I think should be more important. Also, I think it's not intuitive that private messages are not marked, as they are also invite only. But above all I wonder what the point is of having an indicator of invite-only there in the room list. It's not like I have two rooms with the same name and avatar I'd like to differentiate between by how locked they are. It's also not as if it matters to know whether a room is locked from the room list. If I wanted to remind myself whether a room was invite-only or not, I'd click on the room and check the top bar (I think they're fine there). If it changes, it's there in the timeline.

What is the goal of the padlocks in the roomlist? If the goal is solely to differentiate between more "personal" conversations and impersonal ones like #riot-web:matrix.org or smth, maybe there's another way to make that distinction without causing confusion?

**Comment by yusf** [comment]
> Where is riot using padlocks for encryption?

Riot iOS as well, in addition to Riot Android.

**Comment by yusf** [comment]
<img width="53" alt="bild" src="https://user-images.githubusercontent.com/346211/81151150-fe1b2880-8f80-11ea-9170-2120d59b9a8f.png">

The example screenshots doesn't feature the avatar overlay icons. That system of icons should be taken into consideration before adding another one. Instead of decreasing horizontal space for the room name it would be worth considering merging the two icon systems into one.

**Comment by rrix** [comment]
One situation which I have not seen taken in to account, and the thing which is grating on me most, is that this new badging does not (and probably is not able to) describe the state of rooms which are "invite only" but with a bridge admin which can invite anyone who joins a (public) IRC or Telegram or Slack or whatever...

I don't know how to model that, but these bridged rooms are probably 70% of my Riot rooms at this point with a handful of puppet bridges deployed. I am unsure how to handle that UX reasonably, there's as far as I'm aware no channel for that information to flow from bridge services to the HS to Riot.

**Comment by jryans** [comment]
> One situation which I have not seen taken in to account, and the thing which is grating on me most, is that this new badging does not (and probably is not able to) describe the state of rooms which are "invite only" but with a bridge admin which can invite anyone who joins a (public) IRC or Telegram or Slack or whatever...

I'd suggest filing a separate issue for this part to capture your needs on this, as it's a bit orthogonal from the main focus of this one and likely to get lost otherwise.

**Comment by aaronraimist** [comment]
Apparently there is also this ancient issue for this https://github.com/vector-im/riot-web/issues/3206, can probably be closed in favor of this one

**Comment by turt2live** [comment]
This is done in the new room list.
