### ISSUE TITLE
Skipping verification on new device leaves you with being unable to notice when a verification is coming in

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12141]
1. Be logged in to riot-web
2. Log in with another riot-web
3. Skip the setup on the new session
4. Note the number of toasts you have on the new session, but don't do anything with them
5. On the older session, start to verify your new session
6. Unless you noticed the toast count change, the new session doesn't appear to do anything.

**Comment by bwindels** [comment]
Yeah, this is a general problem with our toasts. We could add a priority and push verification requests to the front of the queue?

**Comment by jryans** [comment]
We'll likely do more to improve toast handling in the future, but for now, I think we should take the minimal steps needed to resolve this like @bwindels suggests above:

* add a priority concept to toasts
* set active verification requests to a high priority
