### ISSUE TITLE
Signing-in from a room URL does not redirect to said URL when signed in

### ISSUE THREAD

**Issue by nchevobbe** [vector-im/riot-web#12155]
### Description

if I click the https://chat.mozilla.org/#/room/#devtools:mozilla.org URL and I don't have an account, after signing-in, I'm redirected to https://chat.mozilla.org. 

---

I'd expect to be redirected to the room URL. It would be important for our contributors who are not used to Riot to directly arrive in the right room.

### Version information

- **Platform**: web (in-browser) 
- **Browser**: Firefox 74
- **OS**: macOS
- **URL**: https://chat.mozilla.org

**Comment by jryans** [comment]
Thanks for the feedback! I agree this would greatly help with onboarding new users.

**Comment by jryans** [comment]
I guess there's a bit of design challenge, as we currently show the "Riot Bot" user first for a new account to intro bits of Riot.

We would need to somehow also remember the room of interest as well.

**Comment by jryans** [comment]
We have since removed Riot Bot, so this may now be easier to achieve.

**Comment by t3chguy** [comment]
So this issue is actually SSO specific, we don't pass the fragment as SSO callback arg.
https://github.com/matrix-org/matrix-react-sdk/blob/7e996cb91c9d6af8bfffd1782b51c6bff75075da/src/BasePlatform.js#L172
