### ISSUE TITLE
Cannot log into chat.mozilla.org with Firefox Account

### ISSUE THREAD

**Issue by caitmuenster** [vector-im/riot-web#12152]
Submitting on behalf of Zitronella, a contributor to the add-ons community. 

### Description

User is unable to log into chat.mozilla.org with Firefox Account

### Steps to reproduce
Using Firefox 72.02, German locale 
Go to chat.mozilla.org 
Click Sign in 
Click Sign in with single sign-on 
Submit credentials for Firefox Account
After submission, taken to page that just says "Forbidden". URL is https://mozilla.modular.im/_matrix/saml2/authn_response 

User is able to log into other Mozilla properties (such as addons.mozilla.org) with this account. 

Logs being sent: No

### Version information

- **Platform**: web (in-browser) or desktop? 

Web (in-browser)
Browser: Firefox 72.02 

Same error occurs in Edge

**Comment by richvdh** [comment]
can you help me identify this in the logs? A timeframe of when this happened?

**Comment by caitmuenster** [comment]
Sure! We started attempts at about 3:00pm CET and stopped our last attempt at about 3:50pm.

**Comment by richvdh** [comment]
thanks, investigating now!

**Comment by richvdh** [comment]
Turns out it's being blocked because users with `...@aol.com` email addresses are blocked on this server... is it possible for the user to use a different account with a different email address?

**Comment by Zitronella** [comment]
i coud add another account ...@mail.de to my primary account and now i can log in the chat.

**Comment by Smile4ever** [comment]
I have a @zoho.com address and I'm also unable to login with either of the single sign on services. Please fix this.

@richvdh

**Comment by richvdh** [comment]
the list of blocked domains is mozilla's choice, not mine, I'm afraid.

**Comment by Smile4ever** [comment]
I will open an issue in Mozillas bug tracker then.

**Comment by Smile4ever** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1618791
