### ISSUE TITLE
Riot requires `unstable_features` key on the /versions flag

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12160]
The spec [implies](https://matrix.org/docs/spec/client_server/unstable#get-matrix-client-versions) this is optional and yet Riot seems to require it.

**Comment by turt2live** [comment]
for what specifically? I added a bunch of null checks to /develop recently...

**Comment by jryans** [comment]
@anoadragon453, would be great to have more details here! 😄

**Comment by jryans** [comment]
@anoadragon453, did you happen to learn any more detail here?

**Comment by anoadragon453** [comment]
Oh! Yes, sorry for this awfully non-informative issue. I think this arose when testing Dendrite a few months ago.

I've tested this and can confirm it is no longer the case!
