### ISSUE TITLE
Verification over federation results in strange state

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#12169]
`@alice:lant.uk` (fresh account, secret storage enabled, 2 devices, both verified) verified `@dogtanian:matrix.org` (fresh account, secret storage enabled, 1 device) by clicking Verify .

The emoji verification completed successfully, but the end result was:
- `@alice:lant.uk` sees dogtanian as having a black shield, with one session that is verified. The _Verify_ link is still available:
    <img width="244" alt="image" src="https://user-images.githubusercontent.com/1922197/73538308-9eadf980-4422-11ea-90cb-853f0bc9564c.png">
- `@dogtanian:matrix.org` sees alice as having a red shield, with one verified session and one untrusted session. The _Verify_ link is gone:
    <img width="260" alt="image" src="https://user-images.githubusercontent.com/1922197/73538497-1a0fab00-4423-11ea-90ca-b8f2b633e1b7.png">

**Comment by lampholder** [comment]
I was able to reproduce this with a second runthrough

**Comment by lampholder** [comment]
Specifically:

- `@alice:lant.uk` has two verified devices; `@somebody:notlant.uk` has one device and SSSS enabled
- `@alice:lant.uk` clicks on `@somebody:notlant.uk`'s profile
- `@alice:lant.uk` initiates verification
- `@somebody:notlant.uk` accepts request
- They both see QR codes
- `@alice:lant.uk` chooses to verify by emoji
- They both confirm the emoji are the same
- Verification success prompt appears in right panel (at this point `@alice:lant.uk` still sees a black shield)
- `@alice:lant.uk` dismisses the success notification and sees `@somebody:notlant.uk` as green-shielded
- `@somebody:notlant.uk` dismisses the success notification and sees `@alice:lant.uk` as red-shielded, with one untrusted session (and no option to verify). As if Alice had not cross-signed her device.

**Comment by jryans** [comment]
I believe this is the same or at least similar to what @turt2live and I just saw over the federation:

* we each had all of our devices verified for our own account
* we verified our user accounts by emoji
* we each see the other person as having only 1 verified session (the current one they were using) but all others are unverified

**Comment by jryans** [comment]
We seem to see same trust status on RiotX as well, so this suggests there is a Synapse issue with federating the keys.

**Comment by uhoreg** [comment]
This is fixed by https://github.com/matrix-org/synapse/pull/6844
