### ISSUE TITLE
Collapsed room list has unaligned room tiles

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12171]
![](https://i.imgur.com/rKBSUZP.png)

The two E's are private rooms. The T is a public room.

**Comment by TestardR** [comment]
Sorry tur2tlive, I have tried to reproduce on Chrome and Firefox. It works just fine, they all are nicely aligned. 
![Screenshot_2020-02-02 Riot T](https://user-images.githubusercontent.com/40339476/73611118-e7aaad00-45de-11ea-8ea7-7b7ed2291afc.png)

**Comment by turt2live** [comment]
@TestardR are you on /develop?

**Comment by TestardR** [comment]
> 
> 
> @TestardR are you on /develop?

Yes !

**Comment by turt2live** [comment]
I can still reproduce this :(

**Comment by jryans** [comment]
I cannot reproduce either... @turt2live, maybe it's specific to accounts using custom tags?

**Comment by turt2live** [comment]
This is definitely still happening. It's possible in my earlier screenshot that the locks failed to load:
![image](https://user-images.githubusercontent.com/1190097/73614305-aeca0280-45f5-11ea-9734-1bd9788ca810.png)

**Comment by jryans** [comment]
Okay, but what about this part:

> @turt2live, maybe it's specific to accounts using custom tags?

**Comment by turt2live** [comment]
It's not custom tags, I don't use custom tags and this is a dev account.

**Comment by jryans** [comment]
Ah right okay, I am seeing this issue as well, yes, probably related to padlocks.

**Comment by TestardR** [comment]
![Screenshot_2020-02-03 Riot vanessa(1)](https://user-images.githubusercontent.com/40339476/73683086-f322d480-46c1-11ea-8df9-ebeae46a7aff.png)

Someone solved this issue I guess !

**Comment by TestardR** [comment]
Dear all, I filed a pull request solving this issue. "Collapsed room list has unaligned room tiles #12171"

![Screenshot_2020-02-03 Riot MyBlockedRoom](https://user-images.githubusercontent.com/40339476/73691381-89f78d00-46d2-11ea-8700-ac04c4c9acdb.png)


Please let me know if I mix up pull requests together. I am a bit new to contributing.
