### ISSUE TITLE
/app/ shows "Unable to restore session" error without any further information.

### ISSUE THREAD

**Issue by Liniert** [vector-im/riot-web#12183]
### Description

When I try to start the riot browser app, it shows an "Unable to restore session" error.

![Screenshot_7](https://user-images.githubusercontent.com/60542762/73592052-4ea06700-44f6-11ea-87fc-c33abf573fdd.png)

### Steps to reproduce

- Visit https://riot.im/app/

Describe how what happens differs from what you expected.

The app doesn't start.

Log: I will after I created this github issue here, as the window told me to do..    

I tried adding a screenshot, not sure if it will show up.

The chrome console shows 3 errors when I try to load the page. I edited the cachebuster numbers.

![Screenshot_10](https://user-images.githubusercontent.com/60542762/73592053-4f38fd80-44f6-11ea-963b-0bb0bc01a470.png)
![Screenshot_11](https://user-images.githubusercontent.com/60542762/73592054-4f38fd80-44f6-11ea-8eb4-6ed7952ce08e.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome/62.0.3202.89
- **OS**: Windows 7 Professional x64
- **URL**: riot.im/app

**Comment by aaronraimist** [comment]
Chrome 62 is quite an old version of Chrome, you should update. https://github.com/vector-im/riot-web/issues/12195 suggests that the error you are seeing is due to Chrome.

Riot only supports the last two major versions of Chrome, Firefox, and Safari.

**Comment by turt2live** [comment]
Yea, sorry we don't support this browser version. If you get the same problem on a newer browser, please open a new issue. Thanks!
