### ISSUE TITLE
the DM created for verifying is not E2E by default!

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12187]

**Comment by jryans** [comment]
We want to reuse the detection of whether user is E2E-capable that already happens in the invite dialog when pressing "verify" in the right panel with someone you haven't created a DM for yet.

**Comment by foldleft** [comment]
It looks like this isn't going to be quite so simple as turning on encryption:
<img width="792" alt="Screenshot 2020-02-13 at 14 09 05" src="https://user-images.githubusercontent.com/3935731/74443073-7c789a80-4e6a-11ea-8f4d-b8ee6ed6bee4.png">

Either this was a race condition, or we can't decrypt until we accept the invite.

Code that got me here:

```
diff --git a/src/createRoom.js b/src/createRoom.js
index c25b618dc..fd44744df 100644
--- a/src/createRoom.js
+++ b/src/createRoom.js
@@ -23,6 +23,7 @@ import dis from "./dispatcher";
 import * as Rooms from "./Rooms";
 import DMRoomMap from "./utils/DMRoomMap";
 import {getAddressType} from "./UserAddress";
+import SettingsStore from "./settings/SettingsStore";
 
 /**
  * Create a new room, and switch to it.
@@ -174,7 +175,16 @@ export async function ensureDMExists(client, userId) {
         const room = suitableDMRooms[0];
         roomId = room.roomId;
     } else {
-        roomId = await createRoom({dmUserId: userId, spinner: false, andView: false});
+        let encryption;
+        if (SettingsStore.isFeatureEnabled("feature_cross_signing")) {
+            /* If the user's devices can all do encryption, start an encrypted DM */
+            const userDeviceMap = await client.downloadKeys([userId]);
+            // => { "@userId:host": { DEVICE: DeviceInfo, ... }}
+            const userDevices = Object.values(userDeviceMap[userId]);
+            // => [DeviceInfo, DeviceInfo...]
+            encryption = userDevices.every((device) => device.keys);
+        }
+        roomId = await createRoom({encryption, dmUserId: userId, spinner: false, andView: false});
     }
     return roomId;
 }
```

**Comment by foldleft** [comment]
Bruno suggests that the encryption may not be properly started until we've received the remote echo (I assume from the other user, acknowledging that crypto is on) so this is probably a race condition where we send the verification request too fast.

I should verify this by seeing if an invite does trigger crypto normally.

**Comment by foldleft** [comment]
A quick experiment shows that it's a race condition. Invitees do indeed participate in the megolm session
<img width="402" alt="Screenshot 2020-02-17 at 10 13 50" src="https://user-images.githubusercontent.com/3935731/74644494-425f0f80-516e-11ea-9d63-0bbda7551de9.png">

**Comment by foldleft** [comment]
perhaps this is a member of a class of bigger problems: should we be able to send a message to a room that the user cannot decrypt in the first place?
