### ISSUE TITLE
Cannot do anything while you're verifying

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12185]
The right panel should stick to your current verification session so you can walk away from it

**Comment by jryans** [comment]
@nadonomy, we made need some design guidance here. Do we need to change the right panel so that it persistently follows you across rooms while verifying? Alternatively, should there be some way to resume the verification by clicking on the tile in a DM (which I hear mobile has done)?

**Comment by bwindels** [comment]
Note that this is less of a problem now, as you can resume by starting a verification again, which will resume the existing request since https://github.com/vector-im/riot-web/issues/11698

**Comment by bwindels** [comment]
the design implies that we'll show a toast when moving away from the right panel, so keeping the panel open when changing room might not make sense. closing for now
