### ISSUE TITLE
DMing a bogus mxid from the new DM UI doesn't warn you

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12186]
i DMd `@foo:matrix.ogr` and it silently worked but didn't invite anyone

**Comment by turt2live** [comment]
This is largely a question about what the dialog should do when you have text that hasn't been pillified yet.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/11771#issuecomment-582459264

**Comment by jryans** [comment]
We may address this specific issue separately from general accessibility, so let's keep this open to track it separately.

**Comment by turt2live** [comment]
I'm assuming this is because of the go button creating an empty room rather than saying you've done it wrong?

The dialog itself feels pretty suggestive that it's not going to work:
![image](https://user-images.githubusercontent.com/1190097/75473911-400d6a00-5953-11ea-8215-9d8bfc9e3800.png)
