### ISSUE TITLE
Caching secret storage passphrase doesn't work on login flows

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12198]

**Comment by jryans** [comment]
Can you provide more detail? It's only cached in memory, so in a fresh tab, you would still need to provide it once at the moment.

**Comment by turt2live** [comment]
right, yes, I was going to do that: after logging in to a new device, you get prompted with the passphrase dialog but it is a different passphrase dialog, so the caching doesn't work. For the demo we tried to set the setting so the passphrase would be cached by that dialog, but ultimately had to enter it later. 

This isn't to make it cached and quiet on the login side, just to make the login side cache the passphrase for later verifications in that tab (post-login).

**Comment by jryans** [comment]
We're changing to a mode where we requests keys at login (https://github.com/vector-im/riot-web/issues/12302), so the passphrase prompt at login would go away.

I'll continue tracking this for now, but I think it can be closed once that work is done.

**Comment by jryans** [comment]
Above mentioned thing has closed, so I think this can also be closed / is now outdated.
