### ISSUE TITLE
Extremely easy to dismiss passphrase dialog

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12199]
We should disable background clicking on this and other important dialogs

**Comment by bwindels** [comment]
It uses a prop to disable the background click handler, for lack of a nicer way to pass the flag.

**Comment by jryans** [comment]
@nadonomy, for at least the SSSS passphrase prompt, we've realised from testing that the modal dialog should not allow clicking the app to exit, as it's too easy accidentally cancel it unintentionally.

Would you prefer we change behaviour just for this one dialog or alternately stop all modals from supporting click to close?

**Comment by nadonomy** [comment]
I think there's some nuance to getting this right. I just benchmarked some existing solutions to confirm some suspicions and:

1. Generically, all modals should allow you to click the background to dismiss them (e.g. room settings, returning back to room).
2. However, modals should be able to also stack an 'Are you sure' modal on top of them. (e.g. When you have unsaved settings, or for sensitive cases like SSSS).

Therefore in the common case users can click the background to dismiss, and in any sensitive cases clicking the background would be simply toggling on/off the 'Are you sure' stacked modal, where they're forced to interact with the stacked modal to cancel.

**Comment by bwindels** [comment]
Thanks for the input, will try to make it work as described above.

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/4038 is also merged, so I believe this is completed done now.
