### ISSUE TITLE
Sign out disincentivize

### ISSUE THREAD

**Issue by cassiersg** [vector-im/riot-web#12213]
**Is your suggestion related to a problem? Please describe.**
Some users have the habit of signing out of websites before closing the browser tab, which they do quite often. They therefore re-login quite often, leading to a huge list of (inactive) devices associated to their account.

That fact, in itself, is a suboptimal experience. Combined with E2EE, it currently breaks verification, even though this should be partially solved by cross-signing (through backup is the user has no other device ?).

**Describe the solution you'd like**

The user shouldn't sign out often. I can think of two solutions (but I'm nowhere near a UX designer):
* Don't delete all the key material on the browser at the sign out action (maybe only revoke server authentication & protect browser key material with user password ?). Provide another "remove account from browser" action.
* Change the sign out dialog to explain users they probably don't want to actually sign out.

**Comment by turt2live** [comment]
Inactive devices on a user's account shouldn't happen if they sign out - it should be removed.

**Comment by cassiersg** [comment]
I got more information from the user: he actually used to have the "Delete cookies and site data when Firefox is closed" option set.
I guess then it's hard to do anything better.

**Comment by uhoreg** [comment]
Yes, if the browser drops the stored data, there isn't much we can do about it, other than somehow encouraging users to clean up their device list (https://github.com/vector-im/riot-web/issues/2154)

**Comment by cassiersg** [comment]
Indeed.
Thanks for the prompt answer.
