### ISSUE TITLE
Rooms should only go green / red when you have verified at least one user in the room

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12214]
There are some cases where this doesn't happen today, e.g. if you have not verified one of your own devices, all rooms would go red (even large public rooms where you have no intention verifying users).

To make the experience more straightforward, we decided after chatting with @dbkr and @nadonomy to add the additional check that green / red states are only shown if you have verified at least one user in the room. If you haven't, the room is black.

[Summary doc on shields](https://docs.google.com/document/d/1RFUN0YRrOs8QZwiblaUbs4wWR0BjA0hBJ27rKJ57Zvk/edit#)

**Comment by foldleft** [comment]
Ohhhh and I've just realised why I excluded the user from the device check

**Comment by jryans** [comment]
@foldleft, well the scope changed along the way, so it was probably correct before, but then we changed the plan again.

I think we **do** want to include the current user in the status though, it's just that the room is left as black if there's no **other** user in the room you have verified.
