### ISSUE TITLE
DM verification should look at the `to` field to see if it is for you

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12211]
In a world with canonical DMs where people might be in the room and not important, it's possible the user could click 'accept' (with confusing state, but otherwise unsuccessfully). Instead, the UI should probably be something like 'Tom has requested to verify Travis' instead of 'Tom is trying to verify you'

**Comment by bwindels** [comment]
interesting, I thought it did this, but just checked the code and it doesn't anymore :-1: Will fix
