### ISSUE TITLE
We need a reset button for cross-signing state while in develop

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12221]
For people who've mullered their cross-signing by configuring it on RiotX rather than Riot/Web or otherwise colliding, we need to provide a reset button

**Comment by foldleft** [comment]
For reference, though I think there's no need to go nearly this low-level: https://github.com/matrix-org/matrix-doc/blob/master/proposals/1756-cross-signing.md

**Comment by jryans** [comment]
It's currently a bit unclear whether to offer "reset == regen and save new cross-signing keys" vs. "clear == remove existing secret storage and cross-signing account data and local cache".

**Comment by jryans** [comment]
There does seem to value in have a "clear away secret storage" button somewhere at least, as otherwise there's no way to proceed if you forgot your SSSS passphrase. (Would need appropriately dangerous dialogs before you delete your cross-signing identity and key backups.)

**Comment by jryans** [comment]
I suppose there is even another variant of resetting just the USK, SSK, so we have at least these options we may want to offer somewhere:

* Reset user and own device signing keys (USK, SSK)
* Reset entire cross-signing identity, forfeiting existing trust chain (MSK, USK, SSK)
* Clear all keys and also empty out secret storage (reset to pre-bootstrap state)

**Comment by foldleft** [comment]
don't use this, I think I don't give back working keys

**Comment by foldleft** [comment]
Also I note there's a flow from `AccessSecretStorageDialog` for recovering secret storage, that we may wish to contemplate adding
