### ISSUE TITLE
Session review toast doesn't do anything if your Synapse is old

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12228]
We should catch the case of old servers somehow and be generally better

**Comment by jryans** [comment]
@turt2live When you say it does "nothing", does that mean you click the button in the toast and nothing happens at all, or you go through a whole setup flow, but the toast still remains?

**Comment by turt2live** [comment]
nothing happens at all, it was like clicking a broken button.

Not sure what is 'old' here though, this is FOSDEM fallout issue.

**Comment by jryans** [comment]
Okay, I see a few places to make this more robust.
