### ISSUE TITLE
Search email: "Something went wrong!"

### ISSUE THREAD

**Issue by WitteShadovv** [vector-im/riot-web#12235]
### Description

In Riot (1.5.8) is a possible bug. As as you type something that looks like an email address (xxx@yyy.zz) with a domain.tld part, a match is found and shown, but after a few milliseconds it shows: Something went wrong!. The dev-tools console shows: Error: "Unsupported identity server: bad response".  The ma1sd log and the tcpdump both look good.

I noticed this on ma1sd 2.2.0 and 2.3.0 with synapse 1.6.1 and 1.9.1. The problem occurs when using Riot web/desktop on Linux and Windows. In the Riot Android app this problem doesn't occur. 

### Steps to reproduce

- Install synapse and ma1sd, 
- Start a chat in Riot web and search for email
- Match found but disappears after a few milliseconds and "Something went wrong!" appears

### Version information

Could successfully reproduce on the following systems:

Web app:

- **Browser**: Chrome, Firefox
- **OS**: Windows, Ubuntu
- **Riot Version**: 1.5.8

Desktop app:

- **OS**: Ubuntu
- **Version**: 1.5.8

Not reproducible on:

Android app:
- **OS**: Android
- **Version**: 0.9.9

**Comment by turt2live** [comment]
@WitteShadovv can you submit a rageshake for this please? Next time you get the screen, click "Submit Debug Logs" and reference this issue. Thanks!

**Comment by WitteShadovv** [comment]
@turt2live I submitted the debug logs of two different servers that both have a nearly identical setup with ma1sd. The error occurs on both of them.

**Comment by turt2live** [comment]
thanks, I unfortunately only see one of them. It looks like you have a server configuration error: the endpoint is returning 405 Method Not Allowed.

**Comment by rda0** [comment]
@turt2live You were right, it was a configuration error on our side in `ma1sd`. I created an issue at ma1sd to describe what happened: https://github.com/ma1uta/ma1sd/issues/26

Please close #12235
