### ISSUE TITLE
Mac shortcuts: Cmd-, should open user settings

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12246]
On macOS, users expect Cmd-, to open the app's settings window. We should add this shortcut to Riot Desktop on macOS. Ideally there would also be a "Preferences..." item in the app menu as well.

**Comment by madduck** [comment]
Please make it configurable

**Comment by aaronraimist** [comment]
@madduck all shortcuts are configurable in macOS, Riot doesn't need to provide any special support for it.

**Comment by nadonomy** [comment]
> On macOS, users expect Cmd-, to open the app's settings window

@jryans can you clarify this? I'd expect _CMD + -_ to zoom out? The macOS keyboard shortcut for settings is normally _CMD + ,_.

**Comment by jryans** [comment]
@nadonomy We are agreeing, I was using `-` as the separator between keys. The sequence is indeed "hold Cmd, press comma".

**Comment by t3chguy** [comment]
In a browser app should this open the settings of the browser or the app therein?
