### ISSUE TITLE
Encrypt to verified devices doesn't respect cross signing

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#12245]
### Description

@mvgorcum and I did the cross signing dance, and then he patched synapse to include the federation fixes so he was showing as all sessions verified (green shield) for me. I then enabled "Never send encrypted messages to unverified sessions in this room from this session" in room settings and he was no longer able to decrypt my messages.

### Steps to reproduce

- Enable cross signing and verify all sessions
- Enable "Never send encrypted messages to unverified sessions in this room from this session"
- Be unable to decrypt messages

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: Sender (develop branch desktop build) receiver desktop and web develop

**Comment by mvgorcum** [comment]
I also noticed that while my DM with @turt2live has a green shield, if I click 'End-to-end encryption information' it still tells me:
> Verification | NOT verified.

**Comment by Cadair** [comment]
It also seems that my device isn't trusting the devices on message receive either (which makes sense):

![Screenshot_20200206_092712](https://user-images.githubusercontent.com/1391051/73923996-a7d81400-48c3-11ea-9160-7a0662298f8d.png)


![image](https://user-images.githubusercontent.com/1391051/73923981-a1e23300-48c3-11ea-921a-e5486d86fd79.png)
