### ISSUE TITLE
RVS is spamming updates

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12256]
Cause unknown

**Comment by jryans** [comment]
It seems like a regression of some kind, and it makes it much harder to follow other things in the console... We should investigate what's happened here, and try to fix the root cause. Failing that, we should at least disable log.

**Comment by turt2live** [comment]
The log line is very important in debugging, so I would rather we root-cause it.

**Comment by jryans** [comment]
Looks like it's because of a recent sync state addition, will fix.
