### ISSUE TITLE
Web's QR codes might be overcomplicating themselves

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12257]
Actions summarised by @jryans:

* [x] Use some library that allows quality level control and set it to the lowest possible value
* [x] Remove the [m] logo from the QR code

**Comment by jryans** [comment]
We are currently use the [`qrcode-react` package](https://github.com/cssivision/qrcode-react), which hasn't been updated in a bit and does not offer directly quality level control.

I believe we should instead switch to [`qrcode.react` package](https://github.com/zpao/qrcode.react), which has level control, is recently updated, and still has logo support.

**Comment by turt2live** [comment]
the `qrcode` package (not react) also had pretty good success, though no logo. I'm not convinced we need the logo tbh.

```
class MatrixQRCode extends React.Component {
    static props = {
        url: PropTypes.string,
    };

    constructor(props) {
        super(props);

        this.state = {url: null};
        const asBytes = props.url.map(c => )
        QRCode2.toDataURL(props.url, {
            //version: 2,
        }).then((url) => this.setState({url}));
    }

    render() {
        if (!this.state.url) return <div className='mx_EmptyQrCode' />;

        return <img src={this.state.url} />
    }
}
```

**Comment by jryans** [comment]
> I'm not convinced we need the logo tbh.

@nadonomy also agrees that the [m] logo is not desirable, let's also remove it as part of this work. Will update top comment to summarise.
