### ISSUE TITLE
Tab doesn't load when Firefox starts up

### ISSUE THREAD

**Issue by digitarald** [vector-im/riot-web#12259]
### Description

When starting up Firefox, Riot gets stuck in endless loading state. 

### Steps to reproduce

- Riot open
- Restart Firefox (need 2xdaily as I am on Nightly)

![image](https://user-images.githubusercontent.com/8599/73864039-d25b9b80-47f5-11ea-8f15-a3c81e28c620.png)

### Version information

- **Browser**: Firefox Nightly, 74
- **OS**: macOS
- **URL**: https://chat.mozilla.org/#/room/#profiler:mozilla.org

**Comment by jryans** [comment]
@digitarald Does this only happen during Firefox startup, or does Riot fail to load all the time for you?

At the moment, the Mozilla Riot instance appears to load in Firefox Nightly for me...

**Comment by jryans** [comment]
In particular, the line about MIME type mismatch and `x-content-type-options: nosniff` seems suspicious... I don't receive this error when I try to load. When I load the page, the `12.js` file is served with `content-type: application/javascript`, and it seems quite strange that you would get something else...

@digitarald, could you test in clean Firefox profile? I wonder if your default profile has a security setting or extension that's causing this.

**Comment by digitarald** [comment]
This hasn't happened recently, maybe this was just a blip on Nightly. Closing for now.
