### ISSUE TITLE
Renaming your device doesn't actually happen until you hit enter in the field

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12264]
### Description
When renaming your devices in the Security & Privacy Settings tab, you can rewrite a device name and click out of the field, but your device name isn't actually updated until you are in the field and hit enter.

This can cause confusion where users leave the field (since there's no confirmation button) and assume the device name change has taken place.
### Version information

- **Platform**: web
- **Browser**: Firefox v74.0a1 (nightly)
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5012
