### ISSUE TITLE
Incoming Verification Request title overlaps modal close icon

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12267]
### Description

![image](https://user-images.githubusercontent.com/1342360/73943173-365e8c80-48e8-11ea-9406-d6a320a468ad.png)

### Steps to reproduce

- Someone sends you a verification request
- Click Accept, then click Start Verification
- Get presented with this UI bug

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox nightly v74/0a1
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/12267
