### ISSUE TITLE
Error: Problem communicating with the given homeserver. (M_UNKNOWN)

### ISSUE THREAD

**Issue by mohoj** [vector-im/riot-web#12274]
Hello,
I have problem by logging into different server. Every time I get this error ''Error: Problem communicating with the given homeserver. (M_UNKNOWN)''. I tried to login with Chrome, FirefoX, Opera, Tor and desktop application and on the mobile app - no results. I have no idea what I can do more. I can login to this server: ''https://matrix-client.matrix.org''. I also tried to change password on this server where I have problem. How and where to find solution for this issue ? 
Thanks.

**Comment by turt2live** [comment]
That sounds like a configuration issue on the server-side. Are you able to share the server you're trying to speak to?

**Comment by mohoj** [comment]
> That sounds like a configuration issue on the server-side. Are you able to share the server you're trying to speak to?

Yes, this server: https://hyperreal.chat

**Comment by turt2live** [comment]
It appears to be working okay for me. Are you using a VPN or still having the problem?

**Comment by mohoj** [comment]
I still have this problem with VPN and without. Several people have the same problem.

**Comment by turt2live** [comment]
I think you're running into a server-side issue. Troubleshooting it in #synapse:matrix.org would be better than in an issue.

**Comment by 0x9060** [comment]
@mohoj how did you solve this? I am having the same issue. Clean deployments of matrixdotorg/synapse and vectorim/riot-web via Docker.

**Comment by 0x9060** [comment]
I was able to login via the RiotX app on my phone without any issues...
