### ISSUE TITLE
tab completion always tries to complete the last word in the entry box, even if the cursor is at a different location

### ISSUE THREAD

**Issue by sbts** [vector-im/riot-web#1227]
I belive I just found a bug with tab completion in vector web develop.
if you type a message then go back to earlier in the message and try to tab complete a name it actually completes against the last word in the message rather than the current cursor position.

**Comment by ara4n** [comment]
i think this is a dup of #863

**Comment by richvdh** [comment]
It might be a dup of #863, but this is a *much* better description of the bug

**Comment by richvdh** [comment]
if your message composer ends with a space you get a random person whose name begins with 'a'.

**Comment by t3chguy** [comment]
Fixed by new autocomplete/composer
