### ISSUE TITLE
[bug] over-zealous spell check

### ISSUE THREAD

**Issue by azah** [vector-im/riot-web#12273]
I'm using the latest riot mac app.

How to reproduce:

* type "for", spellcheck will immediately autocorrect "fo" to "do" so you end up with "dor".
* type "bruh", spellcheck will immediately autocorrect "br" to "be" so you end up with "bruh".

expected behavior:

* spell check should wait until I finish a word before correcting it
* the app should check my system preferences for spell check or disable spellcheck initially on non-mobile devices

**Comment by aaronraimist** [comment]
The desktop app doesn't have any spellcheck. Do you perhaps have text replacements setup for fo and br? Riot currently handles macOS's text replacements incorrectly and immediately applies them without any confirmation https://github.com/vector-im/riot-web/issues/11575

**Comment by azah** [comment]
@aaronraimist that did appear to be the case. Removing those default text replacements fixed the issue.
