### ISSUE TITLE
Riot web end user (critical) issues 20200207

### ISSUE THREAD

**Issue by telmich** [vector-im/riot-web#12279]
Good morning,

after our complaint about UI/UX and the discussion with Mathew, I think it is necessary that we make it more precise, which UI/UX "bugs" are - in our opinion - show stoppers for bringing Matrix to the masses.

The primary purpose of this bug report is to raise awareness of which issues are degrading the matrix user experience.

While this bug report is for riot web (only), I'll refer to matrix in some parts of this bug report due to riot being the primary interface for new users.

I have divided this bug report into sections that refer to the severity of each issue.

I hope this list is helpful for UI/UX input and if not, feel free to close it right away.

## Show stoppers

This category only includes issues that we rate as "clearly stopping new users to make use of matrix" and that will turn users actively away from using matrix.

### E2EE device handling

If matrix is to be promoted with E2EE capability (which we deem is a key feature), then users need to be able to use it without needing to care which device the communication partner(s) use, once they are verified.

This issue is probably mostly solved with the cross-signing release, however the effective flow needs to be retested.

## Severely disturbing

This category of issues lists items that are strictly speaking interfering with the user workflow, but even with their presence, matrix can mostly be used by a user.

## Problematic, but users can workaround

This is the lowest severity and includes bugs that from our testing confuse users and make the users feel that matrix is difficult to use. These issues can be explained to users and there are workarounds for it, but for a seamless/flawless interaction, they will also need to be removed

### User list of room re-appearing

If in non-responsive mode you disable the list of users in a room, you shrink the window width to half, causing responsive mode to be activated. Then switch back to regular width and the user list will re-appear. Clicking on the icon top right to make it vanish does not have an effect on the first click. On second click it disappears.

This is strongly confusing, as a) something that is disabled re-appears and b) it needs 2 instead of one click after responsive mode was activated

### No possibility to check all unread rooms by keyboard shortcut

If using a chat platform on daily basis and having 20+ channels active, it is imperative to have an easy way to find the "next important room" which contains unread messages. Mattermost solves this issue with the Ctrl-k shortcut and is probably one of the best features of Mattermost.

### Hard to detect which room is which in responsive mode

The list of icons on the left representing rooms is hard to use, because the room names only appear on mouse-over. Additionally the number of unread messages completely hides the symbol itself so that the list is only a list of "unread numbers". Combined with the next issue, the responsive mode is very hard to use.

### No keyboard shortcut for changing rooms in responsive mode

The current mapping of Ctrl-k in desktop mode allows to navigate between rooms. As soon as the responsive mode is activated, this shortcut is disabled. 

### Inconsistent scroll bars for the room list

The user list on the right is shortened if it exceeds a certain number of users. The room list on the other hand is using scroll bars. 

### Unintuitive scroll bars for the room list

The scroll bars and the adjustable heights for the different categories (rooms/people/favorites) are somewhat confusing. It might be worth to checkout as an alternative to fully display all rooms and not to introduce any scroll bars.

### Second list of rooms on top left

Above the "explore button" there is a list of icons of rooms.
First it is unclear why it is there (what is the purpose?) and secondly it has a very weird horizontal scroll bar.

### Hiding unread messages count

If only symbols of rooms are show the unread message count currently completely shadows the icon/symbol. I suggest to remove the counter in this mode and only make the symbol visually indicating "any number of unread messages" (f.i. bold, circle, etc.)

### Responsive modes

There could be 3 responsive modes:

* regular desktop (as is)
* half sized mode
  * this mode could try to expose rooms names only by text instead of icon
* slimmest mode
  * don't display any of the left/right bars
  * no room list
  * no user list
  * only the current room
  * this would require an easy way to switch rooms, like ctrl-k to be possiblee

The advantage of this way is to react more fitting to the user expectation.

## Version / infos

Tested with chromium & firefox under Linux.
```
matrix-react-sdk version: <local>
riot-web version: 1.5.6
olm version: 3.1.3
```

**Comment by jryans** [comment]
Thanks for the feedback! 

It's quite hard to triage issues like this that combine many different suggestions and bugs in one list, as some things might be duplicates of other issues, each one may be prioritised separately, or need feedback from different people.

@telmich, could you split up your items into separate issues?

**Comment by jryans** [comment]
It looks like you have split up the issues, thank you very much! 😍 I'll close this mega-issue. If there are still unfiled sections, feel free to continue filing separate issues as needed.
