### ISSUE TITLE
IndexedDB and service worker Modnernizr tests fail in Firefox private window

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12270]
Firefox 74 with develop in private window

```
Browser missing feature: 'serviceworker' rageshake.js:65:27
Browser missing feature: 'indexeddb' rageshake.js:65:27
Vector starting at https://riot.im/develop/ rageshake.js:65:27
Browser is missing required features.
```

I think the right course is to remove those two tests, as we feature detect and have backup path when they are unavailable.

**Comment by t3chguy** [comment]
interestingly the `indexeddb` check is not new

**Comment by jryans** [comment]
Hmm... Did we change how we block at startup then? My evidence is that e.g. https://vector.riot.im works does not block me, while develop does now.

We may actually convince ourselves this is acceptable, but need to discuss as a team.

**Comment by t3chguy** [comment]
nothing should have changed in terms of blocking other than the new rules, the `serviceworker` one being too strict as noticed

**Comment by jryans** [comment]
Our suspicion during the stand up is that the Modernizr upgrade altered the IndexedDB approach to correctly detect the Firefox actually doesn't have this in a private window.

The team agreed at the stand up that (since both of these have fallback), we should remove both of the tests.

@t3chguy, are you available to work on this?
