### ISSUE TITLE
ssss key entry doesn't proceed

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12288]
when trying to verify another user, I couldn't get the ssss key entry to accept my key

**Comment by foldleft** [comment]
this doesn't affect me on staging so I think it's something peculiar to my env

**Comment by foldleft** [comment]
does affect me on riot.im/develop though, looks like a regression then?

**Comment by jryans** [comment]
@foldleft, hmm, well on staging and app, cross-signing is not enabled, so I would have thought you wouldn't even reach the SSSS prompts there?

**Comment by foldleft** [comment]
it's even on key backup prompts

**Comment by foldleft** [comment]
Okay, looks like either one or two bugs!

1) the input dialog wasn't providing feedback properly if the key was invalid
2) (still to investigate) possibly `checkPrivateKey` isn't behaving properly; possibly I've broken my cross-signing state

**Comment by foldleft** [comment]
Also I note there's a flow from `AccessSecretStorageDialog` for recovering secret storage, that we may wish to contemplate adding

**Comment by foldleft** [comment]
yep that was it, i broke my own state
