### ISSUE TITLE
there's huge RHS padding on the new DM invite text field

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12282]
which means that if you're zoomed in or on a narrow screen, the mxid wraps mid-string for no obvious reason

**Comment by turt2live** [comment]
@ara4n screenshot? The text field is a bit of a lie, but should be fixed properly in the future.

**Comment by turt2live** [comment]
Closing - need more information/cannot reproduce.

**Comment by ara4n** [comment]
please chase me if i miss a notification like this, rather than closing the bug... i can't believe this one has been open since FOSDEM :(

reopened at https://github.com/vector-im/riot-web/issues/13066
