### ISSUE TITLE
trying to invite kegan into rooms in the new DM invite thing does not include the right kegan in the search results

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12284]
it gives me kegan:openmarket.com (which hasn't existed for ~4 years), and a few others, but not the actual main account who i'm talking with in a tonne of other places. wtf?

**Comment by turt2live** [comment]
Please rageshake.

**Comment by turt2live** [comment]
This is likely https://github.com/vector-im/riot-web/issues/12143

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/12488 (lacking more information as to what this problem is)
