### ISSUE TITLE
defaultCountryCode does not work in desktop app

### ISSUE THREAD

**Issue by xvalex** [vector-im/riot-web#12294]
### Description

I'm running a private matrix server for our company. Now I'm trying to pre-configure server and other settings. I can successfully configure almost everything except the default language.

### Steps to reproduce

- Clear profile folder, "%appdata%\Riot"
- Create custom config.json with non-english defaultCountryCode, say "defaultCountryCode": "RU"
- Place config at %appdata%\Riot\config.json
- Run Riot

It runs with English interface, when it is expected to run with the language, specified at config.json. Other settings, including the custom homeserver work fine.

The same config, placed at the web server version of Riot works fine and shows UI using the language configured.

Probably, it is a good idea to match Windows interface language on the first run if language is not specified.

### Version information

- Appears at desktop version only, web version works fine
- Windows
- Riot 1.5.8

**Comment by t3chguy** [comment]
`defaultCountryCode` is the default country code for the phone number dropdown. Given languages don't 1:1 map to countries what you want is:

```
"settingDefaults": {
    "language": ...
}
```

**Comment by t3chguy** [comment]
The app does attempt to match system language, which is perhaps why it works in browser for you, its possible electron is simply not passing the correct language across.
