### ISSUE TITLE
The letter in the default avatar in typing section is not well centered

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#12298]
As per this screenshot:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/3940906/74136874-277d2000-4bef-11ea-893a-ecdcbcfebe7a.png">

Firefox for MacOs

**Comment by TestardR** [comment]
@bmarty I have filed a pull request to correct this issue. 
Uncentered letter inside avatar for currently typing users #4051

Cheers,
Romain

**Comment by bmarty** [comment]
Thanks @TestardR!
I let the Riot-Web experts do the review :)
