### ISSUE TITLE
Event reaping

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#123]
(as it slows down react horribly if the app has been running for a while)

**Comment by dbkr** [comment]
This is a js-sdk bug.

**Comment by dbkr** [comment]
Actually, reopening and will track upstream

**Comment by dbkr** [comment]
https://matrix.org/jira/browse/SYJS-23

**Comment by ara4n** [comment]
nowadays tracked on js-sdk at https://github.com/matrix-org/matrix-js-sdk/issues/247

related to https://github.com/vector-im/riot-web/issues/2951

**Comment by richvdh** [comment]
Closing as per https://github.com/matrix-org/matrix-js-sdk/issues/247#issuecomment-340700012
