### ISSUE TITLE
Room list should update immediately for direct changes (moving room etc.)

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12305]
When modifying the room list directly through actions like:

* Moving a room between categories (favourites, low priority, etc)
* Removing / leaving a room

...the room list should local echo / show the update immediately so it's clear the app understood. Currently, there's quite a delay, so it feels as if your selection was ignored or something is broken.

**Comment by Mossop** [comment]
The delay I have seen is in the order of seconds. Certainly long enough to get confused about whether my change took effect and go through the menu to try it again before it finally appears to apply.

**Comment by aaronraimist** [comment]
Basically a duplicate of #11939

**Comment by jryans** [comment]
Ah right, will close and copy my note there.
