### ISSUE TITLE
Implement SSSS sharing requests

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12302]
After a self-verification, check whether we have the USK & SSK cached locally. If we don't, ask the device we just verified for them and store them locally if we manage to get them.

Requires https://github.com/vector-im/riot-web/issues/12299

**Comment by foldleft** [comment]
Using the task for notes as I go along :D

> so I think it all cascades off signObject -> CrossSigningInfo.getCrossSigningKey -> callbacks.getCrossSigningKey -> CrossSigningInfo.getFromSecretStorage which eventually calls the callback that opens the dialog

**Comment by foldleft** [comment]
`index.js` line `1535`: `setDeviceVerification` – we call `_crossSigningInfo.signDevice`.

possibly `verifyKeys` in `verification/Base.js` is a good place to do this – it's called by the various verification strategies
