### ISSUE TITLE
Implement SSSS sharing responses

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12300]
Respond to SSSS key sharing requests (https://github.com/matrix-org/matrix-doc/pull/1946).

Rules we plan to implement:
 * Respond to requests for USK, SSK and backup key from locally verified devices if they were verified in the last [we haven't decided on this value yet] seconds. We respond automatically without prompting the user.
 * Silently reject any requests for keys we don't have cached in indexedb (ie. don't ask the user for their SSSS password to get them out of SSSS)
 * Silently reject all requests from any devices not verified in the last n seconds.
 * Silently reject any request for the master key.

Requires https://github.com/vector-im/riot-web/issues/12299

**Comment by jryans** [comment]
> if they were verified in the last [we haven't decided on this value yet] seconds

This part so far hasn't been implemented on any platform. Filed https://github.com/vector-im/riot-web/issues/12664.

**Comment by foldleft** [comment]
oh, whoops, that'll teach me to read tickets
