### ISSUE TITLE
Content Security Policy: is img-src * required?

### ISSUE THREAD

**Issue by rugk** [vector-im/riot-web#12304]
Follow-up of #3632 and https://github.com/vector-im/riot-web/pull/12258

> Why `img-src *`?
>
>At the time [I've suggested one](https://github.com/vector-im/riot-web/issues/3632#issuecomment-367110054) it did seem to work without that (in my tests). Maybe I did not use/test some third-party image embedding loading?
>
>That said, loading images directly from third-party servers may/should possibly be avoided due to privacy concerns, should not it?

https://github.com/vector-im/riot-web/pull/12258#discussion_r376813261

I.e. can't we remove that `*` from `img-src`?

**Comment by jryans** [comment]
I believe this is because of (at least) user and room avatars, which come from your homeserver.

**Comment by t3chguy** [comment]
and image files in general

**Comment by t3chguy** [comment]
Yeah, this won't be possible with a meta tag in the html where the HS is not known until runtime without sandboxing each and every image into a sandboxed iframe hosted by the HS which seems hugely overkill. It could also be done by downloading the image in javascript and converting it to a blob but this is much less efficient and will ignore the browser's caches

**Comment by jryans** [comment]
It sounds like then the answer is: yes, it is required for various images.
