### ISSUE TITLE
CORS blocks https://mozilla.org/.well-known/matrix/client

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12311]
If you try to discover a custom server in Riot/Desktop (e.g. by entering `@foo:mozilla.org` as your mxid), it fails miserably with:

```
Access to XMLHttpRequest at 'https://mozilla.org/.well-known/matrix/client' from origin 'vector://vector' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by t3chguy** [comment]
That doesn't look like CSP

**Comment by t3chguy** [comment]
especially as riot/desktop official builds don't have the CSP changes yet

**Comment by jryans** [comment]
Instead of CSP, it looks like this is a CORS issue on Mozilla's side: 

* https://mozilla.org/.well-known/matrix/client replies with a 302 to https://www.mozilla.org/.well-known/matrix/client (adding **www** prefix) but is **missing `access-control-allow-origin: *`**.
* https://www.mozilla.org/.well-known/matrix/client itself replies with a 200 and correct CORS header

So, this seems to be something Mozilla would have to correct on their side.

**Comment by Twi1ightSparkle** [comment]
https://mozilla.org/.well-known/matrix/server needs the CORS too while you're at it

**Comment by ara4n** [comment]
> That doesn't look like CSP

oops, sorry for misdiagnosing.

> https://mozilla.org/.well-known/matrix/server needs the CORS too while you're at it

Strictly speaking, the /server URI shouldn't need CORS, as clients don't check the server URI.

**Comment by pmac** [comment]
hmm... so https://www.mozilla.org/.well-known/matrix/client is responding with the proper CORS header, but https://mozilla.org/.well-known/matrix/client isn't when it sends the 302. Is that the problem? I'll see about getting the redirect to send the header. Though it might be easier for the team that owns the redirect to just host the file as well.

**Comment by pmac** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1614615

**Comment by jryans** [comment]
> hmm... so https://www.mozilla.org/.well-known/matrix/client is responding with the proper CORS header, but https://mozilla.org/.well-known/matrix/client isn't when it sends the 302. Is that the problem? I'll see about getting the redirect to send the header. Though it might be easier for the team that owns the redirect to just host the file as well.

Yes, either the redirect needs to also set the `access-control-allow-origin: *` or serve the file directly (also with `access-control-allow-origin: *` set).

**Comment by jryans** [comment]
Since we can't do anything about this on the Riot side and there's an issue tracking it for Mozilla's infrastructure, let's close this one.

**Comment by pmac** [comment]
Got an update in the bug that this should now be fixed. I do see the proper header on the redirect. Can someone confirm that it works now?

**Comment by aaronraimist** [comment]
Works for me

**Comment by ara4n** [comment]
yup, confirmed fixed - thanks!
