### ISSUE TITLE
Hard to detect which room is which in responsive mode

### ISSUE THREAD

**Issue by telmich** [vector-im/riot-web#12326]
Referring to #12279 for base information

The list of icons on the left representing rooms is hard to use, because the room names only appear on mouse-over. Additionally the number of unread messages completely hides the symbol itself so that the list is only a list of "unread numbers". Combined with the next issue, the responsive mode is very hard to use.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8507
