### ISSUE TITLE
Unclear purpose of 2nd room list

### ISSUE THREAD

**Issue by telmich** [vector-im/riot-web#12329]
Referring to #12279 for base information

Above the "explore button" there is a list of icons of rooms.
First it is unclear why it is there (what is the purpose?) and secondly it has a very weird horizontal scroll bar.

As a user it is unclear what I should be doing, how it is different from the other list.

**Comment by t3chguy** [comment]
Those are the breadcrumbs, your recently visited rooms, you can disable them in preferences.

![image](https://user-images.githubusercontent.com/2403652/74287472-f18c8880-4d21-11ea-995b-2ba9cc9a1efe.png)
