### ISSUE TITLE
Inconsistent scroll bars for the room list / unintuitive scroll bars

### ISSUE THREAD

**Issue by telmich** [vector-im/riot-web#12328]
Referring to #12279 for base information

The user list on the right is shortened if it exceeds a certain number of users. The room list on the other hand is using scroll bars.

The scroll bars and the adjustable heights for the different categories (rooms/people/favorites) are somewhat confusing. It might be worth to checkout as an alternative to fully display all rooms and not to introduce any scroll bars.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/983
