### ISSUE TITLE
Emojis in reactions and message composition are not combined

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#12336]
Travis requested I create an issue with these images cos they looked weird when he saw them on my screen.

![redhaired](https://user-images.githubusercontent.com/1917473/74331875-79a77800-4d8c-11ea-9bb0-58758005ec24.png)

![emoji-picker](https://user-images.githubusercontent.com/1917473/74331877-7a400e80-4d8c-11ea-85f4-098a890ecac2.png)

this is on current https://riot.im/app

matrix-react-sdk version: <local>
riot-web version: 1.5.8
Firefox: 72.0.2 (64-bit) ubuntu

**Comment by michaelkaye** [comment]
![when-sent](https://user-images.githubusercontent.com/1917473/74332059-e589e080-4d8c-11ea-84cb-3e32155fab0b.png)

Also worth mentioning they seem to get sent and appear in my riot-web and my riot-android as two separate icons:

```
"content": {
    "body": "🧑‍🦰",
    "msgtype": "m.text"
  },
```

**Comment by t3chguy** [comment]
Try /develop
Got fixed weeks ago

**Comment by tulir** [comment]
That 🧑‍🦰 might still be a problem, but not a riot problem. It's a new combination that was only added to the spec in late 2019 and being released in fonts only now (twemoji got it a few weeks ago)

**Comment by ara4n** [comment]
/me is not looking forward to rebuilding twemoji...

**Comment by t3chguy** [comment]
This is fixed now
