### ISSUE TITLE
Implement MSC2432: Alias semantics

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#12337]
We've got yet another idea for how to implement alias semantics, documented in https://docs.google.com/document/d/1NNDkobiFLeUkJtyj0H6qvKIedgvIkZnFKo78-03cGEk and [MSC2432](https://github.com/matrix-org/matrix-doc/pull/2432).

Here are the things I think need doing in Riot (et al):

- [x] stop formatting m.room.aliases events specially in timelines
- [x] stop considering m.room.aliases events for room names
- [x] Update Room Settings UI to:
  - [x] remove display of m.room.aliases, since they are now meaningless
  - [x] let users see all the aliases for the room on the local server
  - [x] hide local aliases behind an ‘advanced’ disclosure or something, just to help hide obnoxious local ones by default unless you’re *really* hunting for them
  - [x] let users see the current "main" and "alternative" aliases from the m.room.canonical_aliases list
  - [x] let mods twiddle the list of advertised aliases and send updated canonical_aliases events

**Comment by richvdh** [comment]
The synapse side of this is https://github.com/matrix-org/synapse/issues/6898.

**Comment by jryans** [comment]
We'll start with updating the local aliases as a subset of this in https://github.com/vector-im/riot-web/issues/12408.

**Comment by bwindels** [comment]
Already started working on editing alt_aliases on branch `bwindels/altaliases` fwiw. Parked it now as it is not priority.

**Comment by bwindels** [comment]
PRs are out for all of the above checkboxes, but doing a search for `m.room.aliases` in the code shows still quite a few occurrences.

**Comment by bwindels** [comment]
Filed #12680 to track the remaining cleanup, closing this.

**Comment by richvdh** [comment]
\o/ thanks bruno!
