### ISSUE TITLE
Update device settings for cross-signing

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12332]
[Figma](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=6%3A649)

![2020-02-12 at 10 27](https://user-images.githubusercontent.com/279572/74326487-61caf680-4d82-11ea-8f04-8fd9e5c04f60.png)

* Update device info in security section of settings to match design above
* Display device trust status

**Comment by jryans** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/11221

**Comment by MurzNN** [comment]
Will be good also add button "Verify" for unverified devices. Because now when user press "Later" in cross-signing toast at top-left, later he can't understand where to find interface for verify this device.
