### ISSUE TITLE
[Bug] Unresponisve, white window on Riot desktop 1.5.8-1

### ISSUE THREAD

**Issue by Atrate** [vector-im/riot-web#12350]
### Description

When running Riot Desktop. it launches successfully but then after a few seconds the whole app window becomes white and unresponsive.

### Steps to reproduce

- Launch app
- Wait a few seconds

Can reproduce on two machines.
This did not happen before the update to this version.

[847610:0213/081819.765220:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Arch
- **Version**: 1.5.8-1

**Comment by shellowl** [comment]
I have the exact same error with 1.5.8-2 on Arch Linux.

**Comment by shellowl** [comment]
Not sure if it was responsible, but since the update to electron 5.0.0, everything works again.

**Comment by Atrate** [comment]
Oh yes, seems the Electron update solved it.
