### ISSUE TITLE
Cross-signing wedges

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#12357]
1. observe "Unverified session" popup
2. click through "verify your session" dialog
3. observe another popup which confusingly says "this room is encrypted" (it's not) and "Verify this user" (that user is me)
4. Wait
5. Wait
6. cancel

![Peek 2020-02-13](https://user-images.githubusercontent.com/1389908/74456973-85279b80-4e7f-11ea-8918-d8ef5d3f20e2.gif)

**Comment by jryans** [comment]
I believe this has been addressed through other verification stability work.
