### ISSUE TITLE
Pills, autocomplete, etc all don't work without alias events

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12364]
The spec says we shouldn't rely on `m.room.aliases`, but we need them to render pills.

**Comment by turt2live** [comment]
Also the cache becomes outdated when aliases change, so pointing at a new room doesn't work.

**Comment by turt2live** [comment]
also affects autocomplete.

**Comment by richvdh** [comment]
on the subject of pills: related to #430

**Comment by ara4n** [comment]
why do we need `m.room.aliases` to render pills?

**Comment by turt2live** [comment]
So that when someone sends `<a href='https://matrix.to/#/!roomid:exmaple.org'>text</a>` it shows `#matrix:matrix.org`.

**Comment by richvdh** [comment]
also also: you can't set a new room to "anyone can join":

![image](https://user-images.githubusercontent.com/1389908/74819018-99dcb700-52f7-11ea-8d68-56bd40faef3f.png)

**Comment by richvdh** [comment]
aiui: the current plan here is to forge ahead with #12337

**Comment by bwindels** [comment]
So which alias should we use for pills?

**Comment by bwindels** [comment]
for autocomplete: complete for all aliases (alt_aliases, canonical, and local aliases)
for pill: first canonical, then alt_aliases, then probably local aliases

**Comment by turt2live** [comment]
^this should be pretty much what we already do ftr

**Comment by bwindels** [comment]
After some discussion on #msc2432:matrix.org, I didn't add local alias support to pills and autocomplete. The label of a pill will be left alone though for a local alias (albeit without avatar), see linked PRs.
