### ISSUE TITLE
We shouldn't show 'registration disabled' pages at /#register when talking to SSO-only servers

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12362]

**Comment by aaronraimist** [comment]
Presumably it should just show a "Register with single sign-on" button?

**Comment by turt2live** [comment]
Need clarification on what we actually want to happen: hide the button, disable the page, or what @aaronraimist says.

**Comment by ara4n** [comment]
Wearing product hat to unblock this, I suggest we route the 'create account' link on https://chat.mozilla.org/#/login to SSO rather than /#/register.  If people manually register to /#/register it would be nice to give them a "Register with single sign-on" button as @aaronraimist suggests.

**Comment by turt2live** [comment]
For ease of writing code, and making minimally invasive changes to auth, a config option for "onlySSO" or something is probably going to be best.

**Comment by turt2live** [comment]
...except the client might not know about SSO from the server until the user changes the default server to something else. We'll need a more intelligent check here.

**Comment by turt2live** [comment]
Fixed in release, using https://github.com/matrix-org/matrix-react-sdk/pull/4170 to track the bits that need to go to develop.
