### ISSUE TITLE
DNSSEC support

### ISSUE THREAD

**Issue by Avamander** [vector-im/riot-web#12361]
**Is your suggestion related to a problem? Please describe.**
`riot.im` and it's subdomains should support DNSSEC to allow those who wish to not worry about DNS poisoning and similar DNS security flaws

**Describe the solution you'd like**
`riot.im` has DNSSEC configured

**Comment by t3chguy** [comment]
Looks as though the `im.` TLD does not support DNSSEC at present so what you're asking for is impossible: http://stats.research.icann.org/dns/tld_report/

**Comment by Avamander** [comment]
Interesting, I sent them an email asking about their plans about it.

**Comment by Avamander** [comment]
I got a reply from them

```
Hi,

To confirm that DNSSEC is not currently possible, however we plan to implement this in a future update to our platform. We do not have a go-live date for this feature, however.

Please let us know if you have any queries.

Kind Regards
Ryan Crellin
Nic.im Support
```

**Comment by t3chguy** [comment]
Given how open-ended that reply is I am closing this issue until it is a thing which is possible.

**Comment by pali** [comment]
https://mail.jabber.org/pipermail/operators/2016-February/002794.html
> the operator has expressed some interest, and asked other interested domain owners to email them to special mailbox dnssec@nic.im. The more public interest, the more priority this feature
gets on their development timeline. So please drop them a line to express your interest.

**Comment by Avamander** [comment]
@t3chguy How about opening it now? Just to track the status and timeline properly, it is now a real possibility.
