### ISSUE TITLE
An extra DM is sometimes created when trying to verify again

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12370]
Manu: riot-web seems to create a new DM every time you want to make a verification. You can fix it by turning on e2e into one of these DMs

**Comment by bwindels** [comment]
@manuroe Could you provide the rooms for the other user present in the `m.direct` account data on the account where you are initiating the verification request?

**Comment by manuroe** [comment]
```
{
	"@riot-bot:matrix.org": [
		"!hrmHrNGszbhdjdetqQ:matrix.org"
	],
	"@xcbob3:matrix.org": [
		"!ZLIhUrEFJuZDYagwRi:matrix.org"
	],
	"@manolo:matrix.org": [
		"!NdCmGzIahZAeZbrFQy:matrix.org",
		"!eWMUIVHWSRLkOPfgpE:matrix.org"
	]
}
```

`!eWMUIVHWSRLkOPfgpE:matrix.org` is the one where I forced e2e. All my verifications go to that room now.
`!NdCmGzIahZAeZbrFQy:matrix.org` was a room unexpectedly created when doing a verification. I left it to clean my room list.

**Comment by bwindels** [comment]
Thanks @manuroe , so you are not able to repro anymore now? if you leave `!eWMUIVHWSRLkOPfgpE:matrix.org`, can you repro again?

**Comment by manuroe** [comment]
> so you are not able to repro anymore now? 
no, it works now. It started to work as expected (ie no more creating new DM) once I enabled E2E in that DM.

I left `!eWMUIVHWSRLkOPfgpE:matrix.org` so that I have no more DM with the other party. I cannot repro the issue. All verifications go to the same single new DM.

The main change I see is that users know each other (and their devices) a bit more than on my first test.

**Comment by bwindels** [comment]
retest with a local setup where you already have a non-e2e DM with a person and then you try to verify them from an e2e room. If we can't easily repro like this. close

**Comment by bwindels** [comment]
Creating a room, inviting the other party, and marking it as a DM makes the request go to this room. Unmarking the room as DM indeed creates a new DM room. Likely the `m.direct` account data got out of sync, canonical DMs should solve this.
