### ISSUE TITLE
Redacted events aren't removed from search event index (seshat)

### ISSUE THREAD

**Issue by stoically** [vector-im/riot-web#12386]
### Steps to reproduce

- Send message into encrypted room
- Redact the event
- Search for the message text

Expected: No result
Actual: Message found

### Version information

- **Platform**: web
- **Version**: 1.5.9-rc.1

Related seshat issue: https://github.com/matrix-org/seshat/issues/45

**Comment by poljar** [comment]
Addressed by https://github.com/vector-im/riot-web/pull/12703, https://github.com/matrix-org/matrix-react-sdk/pull/4204 and https://github.com/matrix-org/seshat/pull/49.
