### ISSUE TITLE
option to disable registration button 

### ISSUE THREAD

**Issue by damnms** [vector-im/riot-web#12382]
**Is your suggestion related to a problem? Please describe.**
my homeserver does not allow registration, but the button "create account" is visible

**Describe the solution you'd like**
i have a homeserver where registration is denied through the regular UI because of security concerns (especially because of googles recaptcha).
it would be nice to have some way to disable that "create account" button or to somehow configure that to execute a different action. i wrote myself matrix registration portal for my homeserver. i would love when i could configure that button or at least remove it completely by config.json

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9528
