### ISSUE TITLE
Small fix for react warnings in MFileBody and MessageComposer

### ISSUE THREAD

**Issue by jsonjuri** [vector-im/riot-web#12381]
**Fix for:** 
Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:void(0)".

matrix-react-sdk\src\components\views\messages\MFileBody.js
![image](https://user-images.githubusercontent.com/11409905/74591439-f9666880-5052-11ea-8c51-4dd01c02bdc8.png)

**Fix for:**
Warning: Each child in a list should have a unique "key" prop.

The warning shows when having a replaced room:
![image](https://user-images.githubusercontent.com/11409905/74591550-cffa0c80-5053-11ea-9134-272d6b86bcb9.png)

matrix-react-sdk\src\components\views\rooms\MessageComposer.js
![image](https://user-images.githubusercontent.com/11409905/74591456-27e44380-5053-11ea-89eb-72c0c19013a0.png)

**Comment by t3chguy** [comment]
the javascript:void thing is actually already fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4046
