### ISSUE TITLE
Words for emoji verification can be cut off

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12391]
<img width="933" alt="Screen Shot 2020-02-16 at 2 37 04 PM" src="https://user-images.githubusercontent.com/5855073/74612333-18541180-50ca-11ea-8382-aecb5f91e6dc.png">

Doesn't matter how wide I make the right panel, Strawberry is always cut off

I assume this is even worse in other languages

**Comment by t3chguy** [comment]
This was done on purpose as some languages like German have insanely long emoji names so it just looks bad
