### ISSUE TITLE
Window is invisible after update? 

### ISSUE THREAD

**Issue by levjoy** [vector-im/riot-web#12402]
After updating the app (in-app updates), windows on the Mac client are invisible. The menu bar shows the app is open after clicking the dock icon, but no window appears. 

This is only resolved by removing the contents of ~/Library/Application Support/Riot, which forces to the user to re-log in, verify keys, etc., which is extremely laborious. 

The same bug seems to occur when resizing the window after hotplugging new monitors.

**Comment by zottelchin** [comment]
Have the same Problem. Notifications will show up as normal.

**Comment by jryans** [comment]
Hmm, that's quite surprising to hear. Did you try restarting the app? If you open the DevTools (Cmd+Opt+I), does the Console reveal any errors?

**Comment by zottelchin** [comment]
Yes, i restarted the app and updated the client to the newest version. Still not showing a window. 
Opening the DevTools does nothing. I think it opens the dev tools, but there is no window to see it. 
If I right click the riot icon in the dock, it will show the window name, as if it was open.

If I can help with more informations let me know :)

**Comment by jryans** [comment]
@zottelchin Okay, thanks for checking. In the folder `~/Library/Application Support/Riot`, there is a file `window-state.json` which is meant to store window positions, which may have become confused somehow. Stop the app if it's running, then try moving that file to the trash or somewhere outside the directory, then start the app again.

**Comment by zottelchin** [comment]
removing the file solved the issue for me. 

Thanks for Your support! :)

**Comment by jryans** [comment]
Okay, great to hear. For now, I'll close this, but if more people are affected, do let us know.

**Comment by Pol-Lanski** [comment]
I just got this a couple of days ago, removing the file worked too! Thanks!
