### ISSUE TITLE
Autoselect first result on room/user autocompletion

### ISSUE THREAD

**Issue by nukeador** [vector-im/riot-web#12409]
### Description

When I'm typing @someone and there is clearly just one result I instinctively hit enter because I assume the only result is selected (maybe because that's the case in other systems, first result is selected), ending up sending the message with unfinished username like @someo  

### Steps to reproduce

Open a room, start typing a username or room you know and wait for the autocompletion dialog to appear.

Riot web
![imagen](https://user-images.githubusercontent.com/531906/74739813-ebceff80-5259-11ea-8eac-5f82fab80fc9.png)

Others
![imagen](https://user-images.githubusercontent.com/531906/74739973-410b1100-525a-11ea-8677-c35f31b03111.png)

![imagen](https://user-images.githubusercontent.com/531906/74740017-5bdd8580-525a-11ea-88f6-44833fabdf07.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 73
- **OS**: Ubuntu Linux
- **URL**: riot web stable

**Comment by t3chguy** [comment]
Closing in favour of autocomplete-is-a-mess-and-doesn't-play-like-others https://github.com/vector-im/riot-web/issues/11071
