### ISSUE TITLE
Populate the view of local aliases from the new API rather than m.room.aliases

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12408]
As an urgent subset of [MSC2432](https://github.com/matrix-org/matrix-doc/pull/2432), we should change to using the new API `GET /_matrix/client/r0/rooms/{roomId}/aliases` instead of `m.room.aliases` when showing local aliases.

[Additional info on alias changes](https://docs.google.com/document/d/1NNDkobiFLeUkJtyj0H6qvKIedgvIkZnFKo78-03cGEk/edit)

**Comment by bwindels** [comment]
working on editing alt_aliases on branch `bwindels/altaliases`
