### ISSUE TITLE
Changing network in "Discover" closes popup window

### ISSUE THREAD

**Issue by rghvdberg** [vector-im/riot-web#12406]
### Description

Changing network in "Discover" closes popup window

### Steps to reproduce
- Click `Discover`
- Change the network to `#Freenode` 
- Popup window closes
- Here's a short screencast

![Peek 2020-02-18 09-05](https://user-images.githubusercontent.com/10710663/74715975-eeb3fb00-522d-11ea-849b-d42192ae355c.gif)

### Version information

- **Platform**: web (in-browser) and riot-web  

For the web app:
- **Browser**:  Firefox 73.0 (64-bits)
- **OS**:  Ubuntu 19.10
- **URL**: both riot.im/develop / riot.im/app / 

For the desktop app:
- **OS**: Ubuntu 19.10
- **Version**: riot-web-versie: 1.5.9

**Comment by t3chguy** [comment]
Is there any error in your console when this happens? Can you send a bug report from Settings?

**Comment by rghvdberg** [comment]
I tried sending a bug log from settings but nothing seems to happen ?
with "console" you mean terminal client ?
only thing I see is
```
$ riot-web 
Seshat isn't installed, event indexing is disabled.
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
(node:6943) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:6943) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
```

**Comment by t3chguy** [comment]
The logs you sent contain a lot of:
`2020-02-18T08:07:58.952Z E Analytics error:  NetworkError when attempting to fetch resource.`

and 
`2020-02-18T07:59:05.865Z E protocols[proto].instances is undefined`

Could you use Control Shift I to open the devtools and see which network requests are failing when this issue happens?

**Comment by t3chguy** [comment]
myself I get a failure on matrix.org so it seems like an outage with them

![image](https://user-images.githubusercontent.com/2403652/74748629-bb3e9400-5260-11ea-82c2-5cab26caadc5.png)

**Comment by t3chguy** [comment]
This turns out to be a misconfiguration in matrix.org, I have reported this to them.

**Comment by t3chguy** [comment]
matrix.org appears to have resolved this.
