### ISSUE TITLE
Reproducible crash while attempting to edit a message

### ISSUE THREAD

**Issue by Yoric** [vector-im/riot-web#12416]
### Description

I wrote the following message:

```
@farhan787:mozilla.org: I don't know very much about that code, but perhaps you could find more help [#fxa:mozilla.org](https://chat.mozilla.org/#/room/#fxa:mozilla.org)?
```

I wished to edit it to fix the typo. Clicking on the edit button crashes the web ui. Attempted a few times to edit, got the crash each time.

I have attempted to upload the debug logs but I don't see them anywhere.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 75.0a1 (2020-02-17) (64-bit)
- **OS**: macOS 10.14.6 (18G3020)
- **URL**: https://chat.mozilla.org (sorry, I don't know how to check the version)

**Comment by jryans** [comment]
Thanks for the report, we'll investigate!

**Comment by t3chguy** [comment]
happens when we try and pillify a room we know nothing about
https://github.com/matrix-org/matrix-react-sdk/blob/7e45979e00904d039d002a1f598bfa81cc548b30/src/editor/parts.js#L434
