### ISSUE TITLE
Invite dialog will refuse to match an exact user ID if the server returned results

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12419]
This makes it impossible to invite `@telegram:t2bot.io` to a room because matrix.org (for example) will return ~15 Telegram users but not actually the bot you've asked for.

**Comment by ara4n** [comment]
returned *no* results surely?

**Comment by ara4n** [comment]
well, it refuses to match exact user IDs whether there were results or not...

**Comment by turt2live** [comment]
No, the code doesn't try exact matches when the server does return results, as it expects the server to figure this out:
![image](https://user-images.githubusercontent.com/1190097/74870561-2f3b7380-5317-11ea-8983-7f790dcf21ee.png)

However Synapse doesn't always do something as convenient as shown in the above screenshot:
![image](https://user-images.githubusercontent.com/1190097/74870677-5c882180-5317-11ea-81a6-3bd1ed95e9fd.png)

So unless you have interacted with certain users before, it won't suggest anything. However, when the server returns no results (because you don't share a room with the user, or they aren't public, etc) the dialog takes a bit of time to track down a profile and fill in the gap for you:
![image](https://user-images.githubusercontent.com/1190097/74870802-935e3780-5317-11ea-8841-db6495ccf4e8.png)

The fix is that when you enter a mxid-looking thing it should always track down a profile and push the result to the top of the suggestions. If the server happens to return the result it's looking for, it should just move the entry to the top (skipping the profile check because it would already have one).
