### ISSUE TITLE
Define the flavours of linux we support

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12422]
Ubuntu? Mobile? Arch with whatever random things have been installed? etc

**Comment by julianschacher** [comment]
I think the intention of [this PR](https://github.com/vector-im/riot-web/pull/12377) was that Riot Desktop is supported on **Desktop** Linux (and not on **Mobile** Linux).
The PR didn't clarify that tho and therefore the support status of **Mobile** Linux is ambiguous.

I think the best solution would be to explicitly mention the status of support for **Mobile** Linux and I personally think it would fit quite well in the category of experimental support, since the mentioned PR just introduced that kind of support for other mobile platforms.

**Comment by julianschacher** [comment]
Also this PR is quite related to [this one](https://github.com/vector-im/riot-web/issues/12421).

**Comment by steef435** [comment]
It currently says:
> Linux versions that are actively supported by the OS vendor and receive security updates

As a desktop Linux user I'm very happy that it's that vague, haha. Maybe a little bit more precise like "all major desktop linux distributions that are actively maintained [maybe some specific software dependencies]" would be enough?

There is way more to desktop Linux than Ubuntu (and its derivatives).

**Comment by jryans** [comment]
> I think the intention of [this PR](https://github.com/vector-im/riot-web/pull/12377) was that Riot Desktop is supported on **Desktop** Linux (and not on **Mobile** Linux).

Yes, the intention is desktop Linux only. 

Riot Desktop on mobile Linux would be too niche at the moment, unfortunately, given the low market share. I assume mobile Linux would benefit from most work done to support mobile web, and that may also be a better path to using it there (as opposed to installing Riot Desktop which assumes desktop-class hardware).

(Personally, I do want to see mobile Linux succeed, and I'll be buying some devices myself in the near future. I hope it will gain traction and eventually become something Riot targets in the future.)

**Comment by jryans** [comment]
> versions that are actively supported by the OS vendor and receive security updates

As @steef435 mentions, I did try to be intentionally vague and avoid listing specific distro. So far, I don't believe we've seen many issues that only affected one distro vs. another, so I'd prefer to remain flexible for now.

We may of course revisit this, but for now I'd like to attempt to accommodate a variety of desktop Linux configs that actively receive support.

**Comment by jryans** [comment]
I'll clarify mobile Linux as part of https://github.com/vector-im/riot-web/issues/12421. Given that, I don't think there's anything else we need to do here at this time.

If there are specific environments that are not yet supported which you believe should be, feel free to open a separate issue to discuss them.
