### ISSUE TITLE
"Completing security" infinispinnered on a fresh login

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12426]
Just logged into my main account on a local develop. It prompted me quite early on for my SSSS passphrase in order to login.  Initialsync then completed in the bg... but it sat there infinispinnering at me :/

<img width="2032" alt="Screenshot 2020-02-20 at 02 08 41" src="https://user-images.githubusercontent.com/1294269/74894168-1ddd8000-5386-11ea-9ebf-bb0cc035345b.png">

https://github.com/matrix-org/riot-web-rageshakes/issues/2284

**Comment by ara4n** [comment]
also, why are there two indexedb workers?! :/

**Comment by ara4n** [comment]
i eventually got bored and hit refresh and got into the app. however, my megolm keys hadn't loaded from online backup... and despite the thing claiming that it's participating in online backup, I am failing to see a way to kick it to re-download them.

**Comment by ara4n** [comment]
i'm designating this as 'fire' given it's impacting every log in, and richvdh got bitten by it earlier.

**Comment by ara4n** [comment]
context, I've been staring at this for about 15 minutes now:

<img width="1292" alt="Screenshot 2020-03-06 at 23 49 36" src="https://user-images.githubusercontent.com/1294269/76131124-2af4a300-6005-11ea-8e98-8e966a568a1f.png">

why are there 4 indexeddb workers?!

**Comment by jryans** [comment]
> and why are there 4 indexeddb workers?!

We leak a worker whenever the client is stopped, filed https://github.com/vector-im/riot-web/issues/12642.

**Comment by jryans** [comment]
> i'm designating this as 'fire' given it's impacting every log in, and richvdh got bitten by it earlier.

I don't think this technically meets our definition of fire, since it's not a regression or high visibility issue we'd do an off-cycle release for, so I'll clear the label... It only appears to happen for larger accounts with cross-signing, as best as I can tell.

In any case, we're looking at it. 😄

**Comment by jryans** [comment]
For @ara4n's logs, unfortunately they seem to be truncated and the initial phase of login is not captured, so it's hard to say what happened there.

From @richvdh's logs, the main slowdown appears to key signature upload, which suggests this is a version of https://github.com/vector-im/riot-web/issues/12223, so I'll focus on that one first and then asks for retesting here.

**Comment by jryans** [comment]
Develop now has a fix for the related issue https://github.com/vector-im/riot-web/issues/12223. @ara4n and @richvdh, could you please retest?

**Comment by jryans** [comment]
Ah actually, I've spotted another issue that's probably important here: we're currently awaiting a full key backup restore during login... 😬
