### ISSUE TITLE
Support definitions need to clarify mobile vs desktop

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12421]
cc @jryans 
See convo up from https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$3_gPbNoSPMz02MFDQy3AwIBs9PrPdSmBAssJZrA3BlY?via=matrix.org&via=privacytools.io&via=feneas.org

"Last 2 major versions of Chrome, Firefox, and Safari" is presumably not intended to include mobile browsers but some are reading it that way.

**Comment by jryans** [comment]
Correct, that line is meant to be about browsers on desktop OSes only. Will attempt to clarify.

**Comment by jryans** [comment]
I'll also clarify that Riot desktop is supported only on desktop OSes.
