### ISSUE TITLE
Riot Web Develop - no connection to server even though Synapse is up and running

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#12432]
### Description

Riot Web Develop - no connection to server even though Synapse is up and running. Internet connection on my Mac working

### Steps to reproduce

Not sure, it just happened out of nowhere

Log: sent/not sent? yes   

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 73.0 (64-bit
- **OS**: macOS Catalina 10.15.3 (19D76)
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Unfortunately, the logs just say things like "network error", so we may need to discuss interactively if this happens again.
