### ISSUE TITLE
Registration flag inhibit_login changed for inhibitLogin

### ISSUE THREAD

**Issue by clecat** [vector-im/riot-web#12437]
### Description

Hello, I'm currently working on the implementation of a matrix server in OCaml.
But since my riot-client moved to 1.5.10, when I try to register a user on my server using riot,
the request json received on the endpoint `/_matrix/client/r0/register'` does not contain the key `inhibitLogin` instead of the `inhibit_login` key contained in [the specification](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-register):

I believe this typo might have been introduced by [this PR](https://github.com/matrix-org/matrix-react-sdk/pull/3992).
If the field names of the dictionary are used as the json keys, it might be that, the inhibit value being registered as `inhibitLogin` in the dictionary.
However as I have 0 experience with javascript nor the codebase, I'm not sure of it.

### Steps to reproduce

- Launch clean matrix server with full log activated
- Launch riot-web client
- Go to `Create account`
- Fill the form with correct values ![Capture d’écran de 2020-02-20 15-56-57](https://user-images.githubusercontent.com/24659882/74946681-faecb380-53f9-11ea-9fd7-58a1debdeafa.png)
- Then validate

On the server side, the following json was received, with `inhibitLogin` key instead of `inhibit_login`:
```
{
  "username":"gwen",
  "password":"$best_password$",
  "initial_device_display_name":"Version bureau de Riot sur Linux",
  "auth":{},
  "inhibitLogin":false
}
```

### Version information

- **Platform**: Desktop (electron app)
- **OS**: elementary OS 5.1.2 Hera (Unbuntu based)
- **Version**: 1.5.10

**Comment by jryans** [comment]
Thanks for reporting this! It should now be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4337. It looks like the upcoming Riot 1.6.0 will be the first release with this included.
