### ISSUE TITLE
Convert SSSS to symmetric encryption

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12431]
The SSSS MSC [has been updated](https://github.com/uhoreg/matrix-doc/commit/41ea250dacfe1b8e3958eb1f55436dc535e381da?short_path=2a4bb46#diff-2a4bb463c1a2f8464cd2d99e2876c7a4) to use symmetric encryption, and we'll need to update the JS SDK to match.

**Comment by uhoreg** [comment]
We probably also need a task for making sure it works with the react-sdk, and to create something for migrating from the current version of SSSS.

**Comment by dbkr** [comment]
Filed https://github.com/vector-im/riot-web/issues/12508 to cover the migration for users who set up asym SSSS

**Comment by jryans** [comment]
Blocked until we have the migration part ready to land safely.
