### ISSUE TITLE
we have lost any UI to tell us that 3PID invites exist

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12444]
as a result, i have NV customers failing to DM me because they don't know what Matthew to talk to, and don't realise they can enter matthew@matrix.org as an email to contact me :|

**Comment by turt2live** [comment]
@vector-im/design please advise on what this should look like. We currently accept email addresses in the dialog, but never tell people that we support such a thing.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/12775
