### ISSUE TITLE
Fix subpixel rendering in desktop client

### ISSUE THREAD

**Issue by jagerman** [vector-im/riot-web#12443]
### Description

Fonts are not subpixel rendered (at least on the Linux) in the desktop client.  The fix seems to be relatively simple in Electron (see below), though I haven't tested it.

### Steps to reproduce

On Linux, in the standalone debian package, my fonts look like this:

![image](https://user-images.githubusercontent.com/4459524/74977019-4609c500-5400-11ea-89d2-ee1c5e37a45f.png)

whereas in Firefox on riot.im I get:

![image](https://user-images.githubusercontent.com/4459524/74977044-5326b400-5400-11ea-8ef0-70be45c9a39a.png)

which ends up looking much clearer when zoomed out.

The fix seems quite easy:

https://www.electronjs.org/docs/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do

i.e. add an explicit backgroundColor on the electron BrowserWindow constructor.

### Version information

- **Platform**: desktop?
- **OS**: Debian Linux
- **Version**: 1.5.10

**Comment by dbkr** [comment]
Good catch! Baffling that this is required, but it looks like it is.

I've added this to riot-desktop so it'll be released when we switch over to using that repo for the desktop builds (in 1.6.0).
