### ISSUE TITLE
Auto-builder for nightly

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12452]
Some tools (or more likely, a tool) that:

 <del>* [ ] Watch for new tags and build the release tarball from them</del> https://github.com/vector-im/riot-web/issues/12706
 <del>* [ ] Watch for new release tarballs and build the release electron apps</del> https://github.com/vector-im/riot-web/issues/12707
 * [x] Watch for it being Nightly Time and build a nightly electron app

and probably also
 <del>* [ ] Watch the develop branch and build the develop tarball</del>https://github.com/vector-im/riot-web/issues/12708

Build tool platform support:
 * [x] MacOS
 * [x] Linux
 * [x] 64 bit Windows
 <del>* [ ] 32 bit Windows (pending https://github.com/neon-bindings/neon/issues/490)</del> not critical for nightlies

Other remaining bits:
 * [x] Sort out version mess on nightlies (just rename the files?)
 <del>* [ ] Replace logo</del< https://github.com/vector-im/riot-web/issues/12709
 * [x] Gather assets and upload to server
 * [x] Override update URL
 * [x] Make a debian repo with both the deb we just built and the latest deb for the other channel
 * [x] Make a signing script for windows that passes the token password to signtool
 * [x] Figure out if we can access the keychain while screen is locked, move to files if not
 * [x] Give it a bot account & room
 * [x] Different debian package control file for nightly(!)

Split out of https://github.com/vector-im/riot-web/issues/11227

**Comment by jryans** [comment]
(Let's track for now as part of cross-signing since it's active work in support of that.)

**Comment by dbkr** [comment]
Have narrowed the scope of this to just nightlies and split the rest out to other bugs, so this is now done!
