### ISSUE TITLE
Pasting an mxid into the new invite dialog reliably coughs up bogus "failed to find users" error

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12459]
To repro:
 * copy an mxid like `@vincent_houlot:matrix.org`
 * Paste it into the invite box
 * See this error dialog

<img width="804" alt="Screenshot 2020-02-21 at 14 23 06" src="https://user-images.githubusercontent.com/1294269/75042102-cb02e600-54b5-11ea-99d1-7bd4c5be7d65.png">

**Comment by turt2live** [comment]
Judging from the dialog, someone forgot a length check

**Comment by turt2live** [comment]
ugh, this is actually because of a space at the end. Eg `@travis:t2l.io ` will cause this but `@travis:t2l.io` won't.
