### ISSUE TITLE
MELS can collapse days too

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12469]
![image](https://user-images.githubusercontent.com/1190097/75068266-1617fb80-54ac-11ea-89a5-acb8ca204ee5.png)

Here we see part of a MELS that started on Tuesday (as the header implies), but person 187 joined on Thursday which is why the timestamps make no sense.

MELS shouldn't be able to pass the day boundary, or the day boundary should be in the MELS.

**Comment by t3chguy** [comment]
this may be a regression from the recent changes in the area

**Comment by turt2live** [comment]
Which area? There's quite a bit of areas that lead up to this.

**Comment by t3chguy** [comment]
@turt2live https://github.com/matrix-org/matrix-react-sdk/pull/4059

**Comment by turt2live** [comment]
ah, hmm... possibly. I'll tag this as p1 for now but not a fire.
