### ISSUE TITLE
Cannot read property 'onTab' of null

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12461]
Nad had some complaints about a spinner in the timeline taking ages and not being able to send messages:
> is it known that /develop is being funky as hell?
![image](https://user-images.githubusercontent.com/274386/75050283-9ac24400-54c3-11ea-910d-77617d7f8d94.png)
> I have this loading spinner everywhere
![image](https://user-images.githubusercontent.com/274386/75050334-b0d00480-54c3-11ea-8032-6a96f544d3f2.png)
> had to hard refresh to be able to send these messages, so apologies if that blitzed potentially useful debug logs :/

matrix.org was feeling a bit sluggish at the time, but the error in the console looks a bit worrying:
```
2020-02-21T15:47:40.990Z E Cannot read property 'onTab' of null
TypeError: Cannot read property 'onTab' of null
    at BasicMessageEditor._tabCompleteName (webpack-internal:///1776:591:32)
```

Rageshake: https://github.com/matrix-org/riot-web-rageshakes/issues/2295

**Comment by turt2live** [comment]
this onTab error has shown up in previous rageshakes I haven't seen - sending into the pit of fire

**Comment by turt2live** [comment]
ftr the performance issues described in the top post are matrix.org failings and not riot's.

**Comment by turt2live** [comment]
removed this from the fire and release blocker states - the error is just log spam. It's a caught error that happens as the last step in a function, so has no ill effects on the app. 

Only happens when the user hits tab when the autocomplete isn't open.
