### ISSUE TITLE
Room server selector: Cannot delete "matrix.org"

### ISSUE THREAD

**Issue by benbucksch** [vector-im/riot-web#12495]
### Description

In the room explorer, I cannot easily enter an alternative server.

### Steps to reproduce

1. Click on "Explore" to see the list of rooms
2. Click into the server widget.
3. You see "matrix.org" in black.
4. Try to delete the text, before replacing it with "mozilla.org".

### Actual result:

1. You _cannot select_ "matrix.org", and therefore you cannot delete it.
2. If you click into the text field, and press the _Delete_ keyboard key, nothing happens.
3. If you ignore that there is already text in the input field, and you just start typing, it works.

![image](https://user-images.githubusercontent.com/1907525/75205016-e8b0a380-5772-11ea-8554-1cbf8763c1a9.png)

### Expected result:

1. Acts like a normal text field
2. The field is empty when I click into it, so that I don't need to delete anything before typing.
3. If you want to have a sample "empty text" placeholder, it should be clearly visible as such, in grey, in italics, so that it's apparent that it's not the input field value, but just a placeholder and that I can ignore it.

### Cause
The "matrix.org" text that appears to be the textfield value is in fact just the placeholder. The bug is caused by bad styling. It's styled in black, bold, 100%, and normal text, so that it appears to be the text field value, although it's not.

The fix would be to fix the style. I could not find the offending CSS rule, though.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 74
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/3770
