### ISSUE TITLE
Firefox incorrectly strips linefeeds when writing multiline input with trailing whitespace in CIDER

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12493]
If you enter multiline input in CIDER but either put trailing whitespace at the end of any line, or leave a blank linefeed, then all the linefeeds get collapsed.  This is very frustrating for people who like writing paragraphs of markdown in their msgs (cc @arcalinea)

To reproduce, enter something like:

```
asd<space>
 
asd
```

and see the message appear as `asd asd`.

or

```
asd
 
asd

```
(note trailing linefeed).

Chrome gets it right however.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/12510 which has some digging
