### ISSUE TITLE
Room server selector: Servers in dropdown are from IRC, but not marked as such

### ISSUE THREAD

**Issue by benbucksch** [vector-im/riot-web#12496]
### Description

In the room explorer, the server selector widget shows #moznet, Freenode etc..

### Steps to reproduce

1. Click on "Explore" to see the list of rooms
2. Select "#moznet" (or any other community)

### Actual result:

1. ![image](https://user-images.githubusercontent.com/1907525/75205863-36c6a680-5775-11ea-8b24-2a27df6ca51d.png)
2. You do not see the Mozilla Matrix rooms.
3. You see 2 IRC channels (i.e. not even all IRC channels).

It may be obvious to long-time Riot users that these are IRC networks, but I was assuming that "moznet" refers to the Matrix server of Mozilla, not the IRC server. After all, this is a Matrix client.

### Expected results

Given that Mozilla just moved to Matrix, and Mozilla has its own Matrix home server with its own channel list, and this is a Matrix server, I was assuming that "#moznet" refers to the Mozilla Matrix server, not to the IRC server. After all, this is a Matrix server. There is nothing in the UI that shows that these are IRC servers.

If a Matrix client lists IRC servers, I would expect this to be clearly marked in the UI as IRC, in a way that no newbie can miss.

Go with your BMW to an BMW dealer, ask for tires, you expect tires that fit your car, not a VW.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 74
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by benbucksch** [comment]
FWIW, if you say that the "#" is the marker that this an IRC server: Given that Matrix rooms also start with `#`, that's not even close to enough. Given that this is Matrix, I would say that no icon would be sufficient and that there needs to be clear and visible text saying "IRC" right next to the server/network name, and always visible, to avoid  confusion.

**Comment by turt2live** [comment]
I think this is fixed in the new directory
