### ISSUE TITLE
Riot-Web won't share room key with cross trust device?

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-web#12509]
Step to reproduce
1) Use an existing session on riot web with some encrypted message and cross signing 
2) Create a new session on riotX, verify session with passphrase (no key backup)

-> RiotX sends room key requests, but it RiotWeb won't share
https://github.com/matrix-org/matrix-js-sdk/blob/bf92cb15223b8549800f19b10023e6daae9f497d/src/crypto/index.js#L2967

I did put some breakpoint on riot-web
and i can see that `device.isVerified() == false`

Maybe it's only checking for local trust? and not checking cross signing trust?

**Comment by BillCarsonFr** [comment]
On my profile page i can see that all my sessions are trusted

**Comment by BillCarsonFr** [comment]
On my profile page i can see that all my sessions are trusted

**Comment by jryans** [comment]
Possibly related to https://github.com/vector-im/riot-web/issues/12104

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1243
