### ISSUE TITLE
Peeking a room over federation without previews allowed spins forever & cannot join

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12500]
If I try to peek a room over federation without previews allowed, Riot hangs with a spinner:

<img width="509" alt="2020-02-25 at 02 06" src="https://user-images.githubusercontent.com/279572/75239347-6c41b300-57ba-11ea-9ac6-82b7f5fb089c.png">

Looking at network traffic, there is an `initialSync` request that fails with `403 Forbidden`:

`GET /_matrix/client/r0/rooms/<room_id>/initialSync?limit=20`

```
HTTP/2 403 Forbidden

{
    "errcode":"M_FORBIDDEN",
    "error":"User <mxid> not in room <room_id>, and room previews are disabled"
}
```

**Comment by jryans** [comment]
The particular room I tried to join has in room state:

```
"join_rule": "public",
"guest_access": "can_join",
"history_visibility": "world_readable",
```

**Comment by jryans** [comment]
I suppose the fundamental issue is that we don't support peeking over federation today, but hopefully https://github.com/matrix-org/matrix-doc/pull/2444 will help at a protocol level.

We can still do a lot more here in the client to convey the current error state.

**Comment by turt2live** [comment]
This used to work just fine, counting it as a regression.

**Comment by ara4n** [comment]
The problem is worse though - not only does the peek never load, it sounds like there's no option to join?  So this means that clicking on any room link over federation is currently broken, which is a pretty spectacular regression.

**Comment by turt2live** [comment]
Hmm... this seems to be working fine for me:
![image](https://user-images.githubusercontent.com/1190097/75294615-24388580-57e6-11ea-9280-3be031e71794.png)

even with the 403.

**Comment by turt2live** [comment]
Caused by https://github.com/matrix-org/synapse/issues/6992 - will fix anyways.
