### ISSUE TITLE
Invisible Riot Notification Icon after update to v.1.5.10

### ISSUE THREAD

**Issue by Wordpress-User** [vector-im/riot-web#12514]
Riot full reinstallation, clearing the windows icon cache and Riot cache did not help
The program otherwise works as usual.
System: Windows 7 64x. Riot v1.5.10
![1](https://user-images.githubusercontent.com/50451695/75286582-ce85cc80-5829-11ea-8210-bb79e8927a07.jpg)

**Comment by t3chguy** [comment]
Windows 7 is EOL and thus unsupported by Riot: https://github.com/vector-im/riot-web#supported-environments

**Comment by turt2live** [comment]
Unfortunately Windows 7 is not supported by Riot or Microsoft anymore. I don't see this on Windows 10.
