### ISSUE TITLE
Login button can be pressed twice to log you in twice in one session

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12546]
as we saw live on stage tonight

**Comment by dbkr** [comment]
The same bug (or at least a very similar looking bug) exists in both registration and login, where:

 * On login, you click 'sign in', it correctly shows a spinner and disables the button, but then hides the spinner and re-enabled the button and sits there for a bit.
 * On registration, you complete the last UI auth step (clicking accept on the terms on matrix.org) and that turns into a spinner for a bit, then the terms screen comes back for a bit before it moves on.
