### ISSUE TITLE
end-to-end encryption information dialog shows 'NOT verified' when device was cross-signed

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#12556]
It's probably still checking device verification rather than cross-signed verification.  ref: https://matrix.to/#/!gGkYcJLTzcNrfERksd:matrix.org/$Zd2y9UxgQ1mvt6XXOtlSD0EkKa2r-8ncSvENBqGqFWQ?via=matrix.org&via=privacytools.io&via=feneas.org

**Comment by jryans** [comment]
Yes, it has not been updated. There's some desire to just remove it entirely, but decision taken yet.

Let's use https://github.com/vector-im/riot-web/issues/11752 for this.
