### ISSUE TITLE
Automatically categorize the Direct Messages / Direct Chats rooms

### ISSUE THREAD

**Issue by aleb** [vector-im/riot-web#12558]
### Steps to reproduce

1. Join a room where only a single other user joined, now there are two users in the room
2. Notice the room appears in section "Rooms"
3. Click the room ellipsis button -> click "Direct Chat" to move it to "Direct Messages".

This should be automated:
- The room should be automatically placed in Direct Messages if initially it has one or two users.
- Once a room has more than two users, it can be automatically moved from Direct Messages to Rooms. 
- If somebody leaves and it's back to two users, it can be left in Rooms as we assume others might join. The user can then manually move it if they really want, and this functionality can be moved in the room settings as it's not so important anymore—cleaning up the UI.

### Version information

riot-web version: 1.5.10

**Comment by turt2live** [comment]
This should already happen for you, but it might be a bit delayed. Does it happen if you refresh after creating the DM, instead of having to tag it manually?

**Comment by aleb** [comment]
The DM I create are correctly put in the Direct Messages section.

**Comment by aleb** [comment]
I'm not sure how the users who invited me to the 1-1s created them. I guess their Matrix client did not "properly" create the room?

**Comment by turt2live** [comment]
Possibly, but there's also some known performance issues with the room list that sometimes mean it doesn't show changes like this.

**Comment by turt2live** [comment]
This looks like either a performance issue or the sender didn't correctly flag the room.
