### ISSUE TITLE
Confusing (room) sections in the Explore Rooms dialog

### ISSUE THREAD

**Issue by aleb** [vector-im/riot-web#12559]
### Description

Users should not have to bother about the room networks in the "Explore rooms" dialog. The UI should also explain what they are exactly.

### Steps to reproduce

- Click Explore button, notice the dialog

<img width="760" alt="Screenshot 2020-02-28 at 10 50 08" src="https://user-images.githubusercontent.com/505582/75538068-f20a6c00-5a0f-11ea-9c5c-7b076c1c590f.png">

There is a search field saying "Find a room..." and at the right there is a combobox with a list of some kind of room sections. This reminds of the various IRC networks. The search is limited to the rooms in the selected section.

It would be good to allow searching in all the sections at once, and make this the default. When listing the results, each room would list the corresponding section(s) and it would be possible this way to give details about what they represent exactly, for example by linking them to some representative page.

### Version information

riot-web version: 1.5.10

**Comment by turt2live** [comment]
pinging @vector-im/design because they're in the area at the moment

**Comment by jryans** [comment]
This is definitely on our minds at the moment. We're be looking over this whole area as part of https://github.com/vector-im/riot-web/issues/5194.

**Comment by nadonomy** [comment]
Closing as this area of the UI has been iterated on since.
