### ISSUE TITLE
#pathfinder:mozilla.org style links don't work in the standalone riot app on macOS

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/riot-web#12568]
### Description

Clicking on a link like `#pathfinder:mozilla.org` just causes a "Loading..." screen with a spinner. This screen never successfully loads anything.

### Version information

macOS 10.15 with Riot Version 1.5.10 (1.5.10)

**Comment by t3chguy** [comment]
Peeking was broken by Synapse, this is fixed on riot.im/staging
