### ISSUE TITLE
Jump to last read message sometimes doesn't do anything

### ISSUE THREAD

**Issue by jdm** [vector-im/riot-web#12564]
### Description

Sometimes when I press the button to jump to the last read message, the view doesn't change despite there being a clear backlog of messages since the last time I looked at the room.

### Steps to reproduce

- Press the jump to last read message

Usually it behaves as expected (modulo #12338), once in a while it does not.

Log: sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 74 nightly
- **OS**: macOS
- **URL**: chat.mozilla.org

**Comment by jdm** [comment]
Eventually the button disappeared when I focused the room while submitting this issue and the debug logs.

**Comment by turt2live** [comment]
This is a function of https://github.com/vector-im/riot-web/issues/2903
