### ISSUE TITLE
Invites failing to show up in room list

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12579]
I invited my matrix.org account to several rooms originally created on mozilla.org. The notification badge for the invite appeared, but then the invite itself never appeared in the room list.

I was able to navigate to the invite by entering the room ID in the URL bar, but that's obviously not ideal... Even after joining this way, the room did not appear in the room list until after a clear cache and reload.

**Comment by turt2live** [comment]
Should be fixed in the new room list, whatever this was.
