### ISSUE TITLE
Redacted pinning events soft-crashes the conversation when trying to pin

### ISSUE THREAD

**Issue by notramo** [vector-im/riot-web#12574]
### Description
If the last pinning event is redacted, the conversation crashes when clicking on the three dot menu of a message that is possible to pin.

### Steps to reproduce

- pin some messages
- redact last pinning event
- click on the three dot menu of a message

### Version information

Riot Desktop on Linux 1.5.10

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4133 on riot.im/staging
