### ISSUE TITLE
Label of the RHS panel search/invite box should be improved

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1257]
Current:

> Invite/search by name, email, id

Proposal:

> Invite by email / id or search by name

**Comment by ara4n** [comment]
it doesn't fit, alas, unless we make the font size tiny.

I'd prefer we worked out a way of making inviting-by-email a first-class citizen - i.e. have a "Invite / Search" input which people will naturally use for names / mxids - and then a separate first class 3PID invite button.  We could put this in the dead space at the very bottom right of the page below the member list - or we could put it in the "INVITE" section at the bottom of the list, or perhaps alongside/below the invite/search input field...?

**Comment by ara4n** [comment]
this is obsolete now
