### ISSUE TITLE
Riot web seems ignores ordering in tagged rooms (favourites)

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#12571]
A change that happened today on `/develop` apparently resulted in some of my tagged rooms to be displayed out of order (I use the "Group & filter rooms by custom tags" labs feature, though that also happens with favourite rooms).

This means that, for a `newvector` tag, the room with this account data:

```json
{
  "type": "m.tag",
  "content": {
    "tags": {
      "newvector": {
        "order": 0.19444444444444442
      }
    }
  }
}
```

is displayed before the one with this account data:

```json
{
  "type": "m.tag",
  "content": {
    "tags": {
      "newvector": {
        "order": 0.08333333333333333
      }
    }
  }
}
```

which, while it doesn't seem to be explicitly forbidden by the spec, seems to go in the opposite direction and is quite counter intuitive (https://matrix.org/docs/spec/client_server/r0.6.0#id123).

**Comment by turt2live** [comment]
What does tags.t2bot.io show you for the rooms? There's a chance that the tombstoned rooms are being sorted into a different position than what you'd expect.

**Comment by t3chguy** [comment]
Its because of
![image](https://user-images.githubusercontent.com/2403652/75589819-b6a18900-5a73-11ea-9fab-6bb88acdf70c.png)
https://github.com/vector-im/riot-web/issues/12242#issuecomment-584746827

Soo all sections which are not Favourites are now recents/alphabetically sorted.

**Comment by turt2live** [comment]
I'm not sure Nad was necessarily aware that it would affect custom tags too, and the top post says it's happening to favourites.

**Comment by babolivier** [comment]
> Soo all sections which are not Favourites are now recents/alphabetically sorted.

Oh. Can't we just do that for all rooms that aren't tagged? It's pretty annoying as I got all of my company rooms organised for quick access to the ones I use the most frequently :/

Also, this definitely affects favourites, some of my favourite rooms are now out of order.

**Comment by turt2live** [comment]
A rageshake would also be nice as there's logging for this sort of thing.

**Comment by babolivier** [comment]
> A rageshake would also be nice as there's logging for this sort of thing.

Done.

**Comment by t3chguy** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/2403652/75590174-97572b80-5a74-11ea-88ba-34a55f8bd798.png)

**Comment by turt2live** [comment]
thanks, fortunately the rageshake doesn't have the logging in it which means it's not some obscure bug with the list.

If you can, please test with another client that supports manual ordering (that isn't in the Riot family) like Quaternion or https://tags.t2bot.io - at least for favourites the ordering should be stable.

**Comment by babolivier** [comment]
> If you can, please test with another client that supports manual ordering (that isn't in the Riot family) like Quaternion or https://tags.t2bot.io - at least for favourites the ordering should be stable.

Yep, still waiting for it to load my rooms, will bing back here when it does.

**Comment by turt2live** [comment]
I've opened https://github.com/vector-im/riot-web/issues/12572 for the custom tags side of this ftr

**Comment by babolivier** [comment]
tags.t2bot.io shows me the rooms ordered in the right order. Here's the comparison of what's shown for in both tags.t2bot.io and Riot for my tag for the public matrix.org rooms I'm in, but I've also checked that it differs both with this tag, my `newvector` one and my favourites.

![image](https://user-images.githubusercontent.com/5547783/75590426-33813280-5a75-11ea-82f5-079ae7012ee1.png)

![image](https://user-images.githubusercontent.com/5547783/75590455-4b58b680-5a75-11ea-91f9-abb8217d3f96.png)

**Comment by t3chguy** [comment]
Yes, it is known custom tags lost manual ordering, that's #12572
Which was a conscious effort on my part based on Nad's instructions.

This issue is about Favourites tagged stuff which should still be manually ordered as shown above in my screenshot.

**Comment by babolivier** [comment]
Ah right, sorry.

Anyway, I'm not going to post a screenshot here of my favourite rooms because some of them are private but they also differ between tags.t2bot.io and Riot.

**Comment by turt2live** [comment]
Summary of this is that riot-web is indeed doing something weird with the favourites, but not for me or t3chguy. 

Suggestion is to try and use tags.t2bot.io to reset the tag ordering which might make riot-web less confused.

**Comment by bhauer** [comment]
I'm not sure I follow the nuances in this thread, but I want to add that as a user of Riot, I would really appreciate an option to alphabetize the favorites list.

**Comment by t3chguy** [comment]
@bhauer thats https://github.com/vector-im/riot-web/issues/4484

**Comment by turt2live** [comment]
We now intentionally ignore manual ordering by default. It's more stable now, and should be more helpful.
