### ISSUE TITLE
Profile Message link broken

### ISSUE THREAD

**Issue by btsfav** [vector-im/riot-web#12582]
when I want to link to direct message via

![image](https://user-images.githubusercontent.com/15261692/75623777-fb313f80-5bad-11ea-8dcf-b0385dd329db.png)

https://matrix.to/#/@fav:matrix.org > https://riot.im/app/#/user/@fav:matrix.org

an error message pops out, it's not working correctly

**Comment by ara4n** [comment]
yup, it seems that all matrix.to/#/@foo:matrix.org style URLs to Riot are currently broken :((

**Comment by turt2live** [comment]
Do they work on `/develop` or `/staging`? We fixed a bug in this area recently: https://github.com/vector-im/riot-web/issues/12404

**Comment by turt2live** [comment]
This looks like a duplicate of https://github.com/vector-im/riot-web/issues/12404 - if it happens after the next release, please open a new issue.
