### ISSUE TITLE
Room list does not reorder on new messages

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#12588]
When getting a new message the room list doesn't reorder to bubble the room to the top. This happens for both DMs and rooms. The lists don't appear to ever reorder, even if I go to different rooms, send messages, change windows, etc.

**Platform**:
- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
What options do you have for your room list sorting? (top two toggles in Settings > Preferences)

**Comment by erikjohnston** [comment]
Both are off ("Order rooms by name" and "Show rooms with unread notifications first")

**Comment by tulir** [comment]
I guess "Show rooms with unread notifications first" is the old behavior and it just needs to be enabled by default?

**Comment by erikjohnston** [comment]
> I guess "Show rooms with unread notifications first" is the old behavior and it just needs to be enabled by default?

That orders based on if there's an unread message or notification and reorders the list when you've read the room (so it drops down the list). The old behaviour was to order by last message send time only.

**Comment by turt2live** [comment]
There's a couple levels of old behaviour: we turned on the "unread notifications first" ordering by default for people, but I believe @erikjohnston turned it off after we did that to make the thing just ordered by recents.

Because of this, the room list sorting might be confused and think that the settings mean something different depending on where they're read.

**Comment by erikjohnston** [comment]
So I should be enabling `Show rooms with unread notifications first` to get to default behaviour?

(FWIW the room list not updating is surprisingly annoying since I end up not realising there are new events in rooms)

**Comment by jryans** [comment]
I believe the core problem here is that adding alpha sort introduced a regression, which https://github.com/matrix-org/matrix-react-sdk/pull/4164 should soon fix. @erikjohnston, you should not need to change anything to preserve the same behaviour you'd had for a while (once the regression is fixed).

**Comment by turt2live** [comment]
@erikjohnston please make loud noises in riot-web internal if this isn't fixed after refreshing develop.
