### ISSUE TITLE
registration email is not send

### ISSUE THREAD

**Issue by xi8Qn** [vector-im/riot-web#12581]
### Description

After creating a new account via the web client and either choosing to register the email on creation or in the settings after creation no email is received. 

(And no it's not in the spam folder...)

### Steps to reproduce

- go to settings
- add email
- wait
- still waiting

Log: sent

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 72.0.2
- **OS**: NIxOS
- **URL**: riot.im/app

**Comment by jryans** [comment]
Sorry to hear about this! 😓 

I can't see anything in the logs that would explain the issue. I recommend contacting support@matrix.org about this and include the email address you used so that we can investigate.
