### ISSUE TITLE
Session verification confusing and not working with cross-signing

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12586]
With cross-signing at the moment, if you go to an encrypted room and expand someone's session list and click an unverified session, you get a dialog like:

<img width="786" alt="2020-03-02 at 11 08" src="https://user-images.githubusercontent.com/279572/75671225-2d0dd900-5c76-11ea-81c9-2bb9d7517992.png">

Clicking "manually verify" seems to send a verification request for that specific session which the other side never receives, so there's a bug there at least... but also, does that actually match the meaning of "manual"...?

**Comment by bwindels** [comment]
just tested, and the request gets sent correctly, and seems to be received but for some reason no toast is shown.

**Comment by bwindels** [comment]
Created https://github.com/vector-im/riot-web/issues/12621 for UX confusion mentioned here, and lack of comparing public keys. This ticket is just about the device verification not working.

**Comment by bwindels** [comment]
Very weird, I can't repro this anymore. Have tried locally and on /develop and I always get a toast now...

**Comment by bwindels** [comment]
@jryans can you still repro this? I've tried with multiple accounts on /develop and local dev after having pulled, can't repro at all anymore.

**Comment by bwindels** [comment]
test with an account with xsigning turned off

**Comment by jryans** [comment]
Yes, I am still able to reproduce when the target user does not have keys or the flag enabled.

The request appears when the target user enables the flag even without uploading keys. I did notice in `MatrixChat` that we only bind the `crypto.verification.request` listener when cross-signing is enabled, but making that unconditional did not seem to be enough for the toast to appear, so there must be another lurking check as well...

**Comment by bwindels** [comment]
With the xsign flag off, I indeed don't see a toast
