### ISSUE TITLE
If you reply to a redaction, the redacted text still appears

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12597]
![image](https://user-images.githubusercontent.com/1342360/75787493-b8fb3000-5d5e-11ea-997a-060dc236d801.png)

### Steps to reproduce

- Send a message
- Reply to that message
- Redact the original message
- (Switch to another room, then switch back)
- The redacted text is displayed, presumably because it's contained in the reply as fallback text

Ideally Riot-web would not display this text, even though the client has access to it.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/75803695-15008d00-5d3c-11ea-9366-5f1dcec712d6.png)

Cannot reproduce - do you have more specific steps? The fallback isn't used in riot at all.

**Comment by anoadragon453** [comment]
Maybe someone else has to reply to you?

Not really, this just happened out of the blue when I went back to this room.

Uploaded logs, in case they were useful.

**Comment by turt2live** [comment]
I've tried all kinds of combinations of encryption, parties, who redacts what, and timing and it doesn't happen. Are you still able to reproduce it?

**Comment by anoadragon453** [comment]
I am not.

**Comment by turt2live** [comment]
I'm going to write this off as a race condition, possibly with sync. If it happens again, we can always reopen.
