### ISSUE TITLE
Extract all cross-signing keys if we unlock the SSSS for any

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12604]
this is so we can cache them all at once

Grep for links to this issue. There may be changes to `VerificationBase` that are waiting for it.

**Comment by foldleft** [comment]
I can't find the easy win for this one yet and I'm frazzled on this bit of the codebase so I'm picking up something else for a while :)

**Comment by jryans** [comment]
I think we could wait until after release for this one.

**Comment by jryans** [comment]
We need this for reliable key sharing to other devices.
