### ISSUE TITLE
Terrible icon scaling in Riot 1.15.12

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#12609]
Like I said (https://github.com/vector-im/riot-web/issues/12518#issuecomment-594513750) icon become terrible in 1.5.12 (Electron 7):

![Screenshot_20200304_190913](https://user-images.githubusercontent.com/3843657/75904410-d659f800-5e4b-11ea-8b2d-9d5b462acd20.png)

It was ok in 1.5.11 (Electron 8 - Chromium 70 where icon scaling was fixed):

![Screenshot_20200304_191353](https://user-images.githubusercontent.com/3843657/75904679-508a7c80-5e4c-11ea-972b-3d1da890558b.png)

Please revert!!!

**Comment by turt2live** [comment]
also as mentioned on that issue, we're consciously not upgrading to electron 8 at the moment.

**Comment by turt2live** [comment]
We fixed this, probably.
