### ISSUE TITLE
room aliases in topics don't hyperlink correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12605]
#synchronicity:mozilla.org in the topic for #general:mozilla.org links to chat.mozilla.org/#synchronicity:matrix.org which is not a thing

**Comment by bwinton** [comment]
As a side note, it might be nice if https://chat.mozilla.org/#synchronicity:matrix.org _was_ a thing, so that people could more easily guess at urls to channels. 😉
