### ISSUE TITLE
Failed to join mozilla.org rooms

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/riot-web#12608]
### Description

I try to join #webapps and I get the following error:
```#webapps:mozilla.org is not accessible at this time.
Try again later, or ask a room admin to check if you have access.
```

### Steps to reproduce

- Try to join any mozilla.org rooms

Describe how what happens differs from what you expected.

### Version information
Desktop Version 1.5.12 (1.5.12)

**Comment by turt2live** [comment]
It looks like this was a temporary problem on the mozilla.org servers, but it should be resolved now. If you're having troubles while on a mozilla.org account, visit #general:mozilla.org (should be autojoined) or #synchronicity:mozilla.org

If you're trying to join from your own server, chances are it is a problem with your server: visit #synapse:matrix.org to troubleshoot.

**Comment by jrmuizel** [comment]
Yep, this is fixed now.
