### ISSUE TITLE
Downloading Images Hijacks Riot Client

### ISSUE THREAD

**Issue by ZaquMan** [vector-im/riot-web#12602]
### Description

Using Riot-Web Version: 1.5.11
The link for downloading images from riot are no longer opening in a new browser tab.  Instead it opens the image in the active Riot window with no option to close the image.  This forces the user to restart Riot (not just close the active window) in order to regain functionality.

### Steps to reproduce

- Select an image shared in the room
- Click the box labeled "Download this file"
- Enjoy staring at the image that will not go away

Describe how what happens differs from what you expected.

I would expect either the image would be opened in a new browser tab/window, as with previous version of riot, or the image be displayed in a new box that can be closed, similar to the box that opens when you open the settings.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?
Issue occurs in Web and Desktop Client for 1.5.11

For the web app:

- **Browser**: Brave (Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit))
--**Browser**: Chrome (Version 80.0.3987.122 (Official Build) (64-bit))
- **OS**: Windows
- **URL**: https://riot.im/app/#/room/#adminhelpdesk:serverplus.com (Hosted on private server running Synapse 1.10.0 (unverified)

For the desktop app:

- **OS**: Windows
- **Version**: 1.5.11
![riot_client_screenshot](https://user-images.githubusercontent.com/43051103/75812951-5c8f1500-5d4c-11ea-84b3-2e8a8b7cdbb5.png)
![riot_web_screenshot](https://user-images.githubusercontent.com/43051103/75813106-a8da5500-5d4c-11ea-9634-ff6aeb640753.png)

**Comment by t3chguy** [comment]
> Issue occurs in Web and Desktop Client for 1.5.11

You say this occurs in the desktop client, is it the official one from riot.im?

The download link has a `download="..."` attribute which instructs your browser to download the file.

**Comment by turt2live** [comment]
Can confirm this on Windows, official client. Will fix.

**Comment by ZaquMan** [comment]
> > Issue occurs in Web and Desktop Client for 1.5.11
> 
> You say this occurs in the desktop client, is it the official one from riot.im?
> 
> The download link has a `download="..."` attribute which instructs your browser to download the file.

I had most recently upgraded the windows client using the built-in upgrade button.  We use the official downloads from riot.im/download/desktop

**Comment by t3chguy** [comment]
> Brave (Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit))

Brave is not a supported browser and if it ignores `download` attributes then there's not much that can be done about that

**Comment by turt2live** [comment]
This also happens in Chrome, so going to revert the whole PR (https://github.com/matrix-org/matrix-react-sdk/pull/4113)

**Comment by turt2live** [comment]
Closing in favour of the release branches which will fix this: 
* https://github.com/vector-im/riot-web/tree/release-v1.5.12
* https://github.com/matrix-org/matrix-react-sdk/tree/release-v2.2.1

**Comment by turt2live** [comment]
actually going to leave this open to figure out a fix for develop that isn't crudely reverting things...

**Comment by hexmode** [comment]
upgrading fixed for me.

**Comment by turt2live** [comment]
So because the media repo implementations out there return a `Content-Disposition` header with `inline`, the `download` attribute is ignored entirely. Because of this, going to reopen https://github.com/vector-im/riot-web/issues/12405 and stick it back into the backlog as it'll need more thought.
