### ISSUE TITLE
Formalise expectations for submitting & reviewing pull requests better somewhere visible

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12614]
Internally, we concluded it's wholly unproductive for design & product to be signing off PRs having to checkout & make builds locally, so therefore there'd be occasions where developers would need to link to ad hoc builds as a part of the PR review process.

We should formalise these expectations somewhere visible (README? PR template?) both for core team members & community contributors.

**Comment by nadonomy** [comment]
@jryans I assume this is one for you? feel free to unassign/triage more appropriately.

**Comment by jryans** [comment]
Yes, I can work on formalise this workflow. 😄 

As far as the process itself, are you still okay with requesting review from the design / product teams as part of PR review? I think I am understanding that the process as follows:

* When design and / or product review is needed for a PR, anyone should feel free to request it
  * (This reminds me we should also share in a similar location the steps for when exactly product review is required, which I think is trapped in some Google doc somewhere...)
* The developer should be prepared for design / product to request a link to an ad-hoc build for review
  * (We could make this stronger and require an ad-hoc build to exist before request design / product review, but I wonder if it would mean some ad-hoc builds are created to check a box for things that didn't really need them?)

**Comment by nadonomy** [comment]
Yep precisely!

To build on what you're saying— I agree that ad hoc builds as a requirement would be too strong and in a lot of cases unnecessary. But, I'd like there to be clear expectations especially for community contributors that as a part of the review process they may be requested for their PRs to be approved.

**Comment by turt2live** [comment]
We can just build and deploy them automatically at effectively zero cost: https://github.com/vector-im/riot-web/issues/12624

I'm just going to go ahead and do this because it's not really fair to expect developers to find a web server to shove things onto either.

**Comment by nadonomy** [comment]
@turt2live thanks, that sounds great! Part of my motivation for filing this issue was that it felt uncomfortable asking community contributors to have to deploy builds.
