### ISSUE TITLE
Error when trying to "Start Chat" without having any rooms

### ISSUE THREAD

**Issue by lazka** [vector-im/riot-web#12611]
### Description

If you haven't joined any rooms then pressing the "Start Chat" button results in a Javascript exception and nothing happening.

### Steps to reproduce

* Not rooms
* Click "Start chat"

I expected the "Direct Messages" popup to appear.

Instead I got:

```
bundle.js:2 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.getUniqueRoomsWithIndividuals (bundle.js:2)
    ...
```

### Version information

- **Platform**: both web and desktop

**Comment by pbek** [comment]
That was fast! 👍

**Comment by lazka** [comment]
Thanks :)

**Comment by jryans** [comment]
@turt2live When did this regress? Is the issue in the stable channel and we need an off-cycle release?

**Comment by turt2live** [comment]
It regressed when we added the dialog. I don't believe it warrants an off-cycle release yet.
