### ISSUE TITLE
Migrate legacy trust to cross-signing

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12619]
Ensure that If I bootstrap SSSS after legacy verifying, my legacy verifications should be migrated to signing those users.

The JS-SDK [already has some code](https://github.com/matrix-org/matrix-js-sdk/blob/bc53f8fdec7222b6ca44a63cafbc7ae8c4cc396f/src/crypto/index.js#L982-L1006) for this, but the react-sdk isn't providing the `shouldUpgradeDeviceVerifications` callback yet. We're relying there on the device having signed the master key, which we currently only do [during bootstrapping](https://github.com/matrix-org/matrix-js-sdk/blob/bc53f8fdec7222b6ca44a63cafbc7ae8c4cc396f/src/crypto/index.js#L626). We [discussed](https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$efQiUfJlbRaILawnqV_QlhtshTt9ZP5ijMnTNAkdmiY?via=matrix.org&via=vector.modular.im&via=half-shot.uk) all devices signing the master key with their device key once they start participating in cross-signing, but deemed it not worth it. So this means that you will only be able to migrate legacy trust if you had legacy verified the device on which the other user has bootstrapped cross-signing.

**Comment by bwindels** [comment]
There's also a .. chick and egg problem here I think ... if I only attempt migrating once I enable cross-signing, and I am the first one of my contacts to do so, I won't be able to migrate as nobody has uploaded cross-signing keys yet. So apart from attempting it automatically when enabling cross-signing, we might also want the user to explicitly attempt migration by e.g. a button in the security settings.

**Comment by jryans** [comment]
The time window for this has mostly passed now that cross-signing has released.
