### ISSUE TITLE
I should be able to opt out of cross-signing/SSSS altogether

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12616]
via Settings (“Manually verify all remote sessions”). [Figma](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=6%3A649)

**Comment by dbkr** [comment]
Having a go at pinning down exactly what this does. To start with I think I'd suggest making `isVerified()` on a DeviceTrust only return true if the device is locally verified so it effectiely ignores any cross-signing verifications.

In future I think this will want more UI changes so it's obvious why the devices aren't trusted. We should also think about whether to show user verification statuses or whether to allow the user to verify another user at all.
