### ISSUE TITLE
Server also shows after nickname if it is unique

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#12622]
See https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$Wl56ixZkMvq7DNoidHu7pniTPHclNvE0eFXQSa8xHNk?via=matrix.org&via=privacytools.io&via=mozilla.org and following.

**Comment by tulir** [comment]
Duplicate of #8903, although neither issue has much detail

**Comment by Biep** [comment]
Duplicate of #8903.
