### ISSUE TITLE
legacy verified devices are not counted when calculating user e2e shield

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12626]
![legacyshield](https://user-images.githubusercontent.com/274386/76001984-da465280-5efd-11ea-8216-0f1ac5a0e3e0.gif)

**Comment by jryans** [comment]
Hmm, this might be correct though...? I assume you have not verified the user, so we use a black shield for them.

**Comment by jryans** [comment]
Hmm, I guess it means we may need to re-think again the shield rules when legacy verifying.

**Comment by bwindels** [comment]
Indeed. Who should be involved in that conversation?

**Comment by jryans** [comment]
I suppose we should have at least you, me, Dave, Nad, Manu, Valere.

**Comment by jryans** [comment]
Maybe it can be discussed async in the room? We could try starting that way, and see how confusing it gets at least... 😅

**Comment by jryans** [comment]
I believe we've reached some agreement that this is largely fine, but we'd like mark non-cross-singing users "distinctly" somehow, with maybe a gray shield or similar.

The precise design is TBD, but let's use this issue to update it.

**Comment by jryans** [comment]
Filed https://github.com/vector-im/riot-web/issues/12806
