### ISSUE TITLE
Propagate legacy trust to all of my devices using cross-signing

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12620]
Ensure that If I have SSSS set up, and I legacy verify someone else, then I would migrate that legacy verification to signing the user, and therefore I would see that legacy verification on all of my devices. The assumption here is that the other user never enables cross-signing (so #12619 wouldn't help us here), but we still want to have the benefits of propagating trust to all of our own devices as provided by cross-signing and SSSS.

This is something the spec currently does not provide a way of doing ([see discussion](https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$VXy55Wf3nZue9QSqIkMIzdrqz357KG-JraroW0whB3w?via=matrix.org&via=vector.modular.im&via=half-shot.uk)), and we're deferring this until the need arises.

**Comment by jryans** [comment]
The time window for this has mostly passed now that cross-signing has released.
