### ISSUE TITLE
Invite only tooltip scrolls with the list

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12637]
![](https://i.imgur.com/L4nNYXP.png)
Hello tooltip, in the middle of nowhere

**Comment by Infinity-Intellect** [comment]
@turt2live I would like to fix this. Where, on the screen, if I place my mouse, does this 'Invite only' tooltip appear ?

**Comment by turt2live** [comment]
The lock in the room list when cross-signing is enabled.

**Comment by turt2live** [comment]
this is gone
