### ISSUE TITLE
Custom widget inside self-hosted riot web.

### ISSUE THREAD

**Issue by PlutonicCoder** [vector-im/riot-web#12644]
Hello,
         I would like to embed a video into my self-hosted Riot instance using 'Custom Widget', but not sure where to add the code. As per this  article - https://matrix.org/blog/2017/08/23/introducing-matrix-widgets, we can accomplish this by manually injecting a state event l into the room, i did try to add code into few files in riot, but it didn't work, what did i miss? where exactly the code has to be injected? an example code is much appreciated.

Thanks

**Comment by t3chguy** [comment]
Custom Widgets are external websites which get iframed in.

**Comment by PlutonicCoder** [comment]
> Custom Widgets are external websites which get iframed in.

Yes, this is exactly i am looking to accomplish,  but how do i do this inside my self-hosted Riot?

Thanks

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/76141525-35db2200-605d-11ea-9556-c0dc497e2118.png)

`/addwidget https://your.website.here`

**Comment by PlutonicCoder** [comment]
> ![image](https://user-images.githubusercontent.com/2403652/76141525-35db2200-605d-11ea-9556-c0dc497e2118.png)
> 
> `/addwidget https://your.website.here`

Thanks, but i am pretty much new to the riot-web, where can i find this option in my self-hosted riot-web? ie where should i add this code in the riot-web installed in my own vps server.

**Comment by t3chguy** [comment]
Its a command, you write it in the chatbox.

![image](https://user-images.githubusercontent.com/2403652/76141708-d120c700-605e-11ea-9863-5740213cb625.png)

**Comment by PlutonicCoder** [comment]
> Its a command, you write it in the chatbox.
> 
> ![image](https://user-images.githubusercontent.com/2403652/76141708-d120c700-605e-11ea-9863-5740213cb625.png)

Thanks so much, it was so easy, but the height of the iframe is adjustable?

Thanks

**Comment by t3chguy** [comment]
I don't think so.

For future support queries please use https://matrix.to/#/#riot-web:matrix.org
