### ISSUE TITLE
Your Riot is misconfigured Invalid configuration: No default server specified

### ISSUE THREAD

**Issue by Infinity-Intellect** [vector-im/riot-web#12655]
### Description

I follow the steps in the readme of the riot repository to run riot on my local machine. After I execute 'yarn start' and head over to the browser and navigate to localhost:8080, I get the message, "No default server specified".

### Steps to reproduce

Follow all the steps mentioned in "Setting up a dev environment" in the Readme.md at 'https://github.com/vector-im/riot-web'

![Screenshot (68)](https://user-images.githubusercontent.com/49329642/76158641-e6b8ee00-613d-11ea-81cf-c28202de7d73.png)

For the web app:

- **Browser**: Firefox Developer's Edition 74.0b9 (64-bit)
- **OS**: Windows 10

**Comment by t3chguy** [comment]
What does the javascript console say?

**Comment by Infinity-Intellect** [comment]
@t3chguy It gave out a couple of messages. I've attached a screenshot to this comment.

![errors](https://user-images.githubusercontent.com/49329642/76164145-7d9f9d80-6172-11ea-91d5-b79162db00aa.PNG)

**Comment by t3chguy** [comment]
`no default server specified.`

what does your config.json look like?

**Comment by Infinity-Intellect** [comment]
@t3chguy  Below is my config.json, which was in the folder /riot.im/develop/

{
    "default_server_name": "matrix.org",
    "brand": "Riot",
    "integrations_ui_url": "https://scalar-staging.vector.im/",
    "integrations_rest_url": "https://scalar-staging.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "hosting_signup_link": "https://modular.im/?utm_source=riot-web&utm_medium=web",
    "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
    "features": {
        "feature_pinning": "labs",
        "feature_custom_status": "labs",
        "feature_custom_tags": "labs",
        "feature_state_counters": "labs",
        "feature_many_integration_managers": "labs",
        "feature_mjolnir": "labs",
        "feature_dm_verification": "labs",
        "feature_cross_signing": "enable",
        "feature_invite_only_padlocks": "enable",
        "feature_event_indexing": "disable",
        "feature_bridge_state": "labs",
        "feature_presence_in_room_list": "labs"
    },
    "welcomeUserId": "@riot-bot:matrix.org",
    "piwik": {
        "url": "https://piwik.riot.im/",
        "siteId": 1,
        "policyUrl": "https://matrix.org/legal/riot-im-cookie-policy"
    },
    "roomDirectory": {
        "servers": [
            "matrix.org"
        ]
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "terms_and_conditions_links": [
        {
            "url": "https://riot.im/privacy",
            "text": "Privacy Policy"
        },
        {
            "url": "https://matrix.org/legal/riot-im-cookie-policy",
            "text": "Cookie Policy"
        }
    ]
}

**Comment by turt2live** [comment]
it needs to be at the root of the riot-web directory if you're going to use localhost.

**Comment by Infinity-Intellect** [comment]
@turt2live I don't quite understand what to do. Am I supposed to place the config.json in the root directory?

**Comment by Infinity-Intellect** [comment]
Thank you @turt2live, placing a config.json in the root folder got it working.
