### ISSUE TITLE
Spurious notification badges slowly appear on signing into Riot Desktop

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12659]
Signed into the new nightly desktop build on Friday evening and now I have red notification badges in rooms I haven't been mentioned in. Could this be Seshat indexing causing them to appear by back-paginating somehow?

Edit: Some, but not all, are notifications from prior versions of the rooms. In combination with the room ordering being flakey so the red badges are often stuck halfway down the room list, this makes for a very shonky-feeling experience.

**Comment by dbkr** [comment]
Lots of reports of this so marking release-blocker for seshat

**Comment by jryans** [comment]
I think release-blocker might be confusing, as we usually check it for the currently-in-flight Riot release, which not quite the right meaning here for a project that spans multiple Riot releases.

For shipping E2EE by default work, we should have all phase 3 work complete by the time we ship it.

In any case, yes let's fix this before releasing Seshat work generally. 😄
