### ISSUE TITLE
Unable to update a room avatar in a new room.

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#12662]
## Description

Unable to update a room avatar in a new room.

### Steps to reproduce

Create room -> Settings -> click upload in top right, select file, file appears but is seemingly not persisted.

I tried with multiple images and multiple rooms. Even clicking away in the settings to another tab and then returning loses the avatar. 

### Version information

/develop Chrome on Mac

**Comment by jryans** [comment]
@neilisfragile I can't remember for sure, but you may need to also press "Save" at the bottom of "General" after uploading, perhaps this confusing UX is the issue?

**Comment by neilisfragile** [comment]
Right, that's the problem. 

I was looking at the bottom of the settings for a save button. I guess some stronger delineation of sections might help?

**Comment by jryans** [comment]
I expect this will get cleaned up as part of larger Settings UX improvements in the future.
