### ISSUE TITLE
Deleting the alias which is the main address for a room creates a blank message

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12666]
<img width="403" alt="Screen Shot 2020-03-09 at 12 48 01 PM" src="https://user-images.githubusercontent.com/5855073/76242181-3bbf3780-6204-11ea-924c-566f25986ce0.png">

```
{
  "content": {
    "alt_aliases": []
  },
  "origin_server_ts": 1583734561897,
  "sender": "@aaron:mozilla.org",
  "state_key": "",
  "type": "m.room.canonical_alias",
  "unsigned": {
    "replaces_state": "$w9WKS850XN5qdly7K51qoQIIx9hCXJh6s54bNzakB7I",
    "prev_content": {},
    "prev_sender": "@aaron:mozilla.org",
    "age": 210
  },
  "event_id": "$k-xgLg2Wvi3JjSytBt_IFomV8-PbIf30jav1UGgJsYw",
  "room_id": "!YFQavwsdLAMiCdFaDX:mozilla.org"
}
```

**Comment by turt2live** [comment]
This is because of @bwindels's work in replacing aliases.

**Comment by turt2live** [comment]
Oh, might be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4189

**Comment by bwindels** [comment]
@aaronraimist: is the event source you posted the source of the first or second (empty) event in your screenshot? If the first, what is the second? An `m.room.aliases` event? In that case, yes, it should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4189

**Comment by aaronraimist** [comment]
@bwindels the source is of the second empty event

**Comment by aaronraimist** [comment]
The first event is

```
{
  "type": "m.room.canonical_alias",
  "sender": "@aaron:mozilla.org",
  "content": {},
  "state_key": "",
  "origin_server_ts": 1583734561569,
  "unsigned": {
    "replaces_state": "$dsz0shxcxQ4aexcQeNWxCoN_zQpSJlEdH0k7Pf9f8A0",
    "prev_content": {
      "alias": "#weekly-project-call:mozilla.org"
    },
    "prev_sender": "@aaron:mozilla.org",
    "age": 116823926
  },
  "event_id": "$w9WKS850XN5qdly7K51qoQIIx9hCXJh6s54bNzakB7I",
  "room_id": "!YFQavwsdLAMiCdFaDX:mozilla.org"
}
```

**Comment by bwindels** [comment]
Thanks for the extra info @aaronraimist. This won't be fixed yet by the mentioned PR. I'm somewhat puzzled that your riot is sending two `m.room.canonical_alias` events ... did you do this through devtools or the room settings?

**Comment by aaronraimist** [comment]
I clicked the X button next to the alias in room settings

**Comment by bwindels** [comment]
Hmm, I can't reproduce the two events being generated when removing the local alias that is also the canonical alias. I'll build in some potential mitigation though and report back here.

**Comment by aaronraimist** [comment]
I can't reproduce anymore so I'm going to assume it got fixed
