### ISSUE TITLE
Messages disappearing or missing on Riot Desktop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12677]
...on Riot Nightly (Desktop).

Probably a different failure mode of https://github.com/vector-im/riot-web/issues/1541 or https://github.com/vector-im/riot-web/issues/10032

**Comment by ara4n** [comment]
Just had it again.

**Comment by turt2live** [comment]
@ara4n are you getting this on web at all?

**Comment by bwindels** [comment]
Only red flag I've seen so far in the rageshake is:
```
2020-03-11T00:20:33.614Z E Caught /sync error TypeError: Cannot read property 'highlight' of undefined
    at MatrixClient.eval (webpack-internal:///40:412:68)
    at MatrixClient.emit (webpack-internal:///38:157:7)
    at ReEmitter._handleEvent (webpack-internal:///66:33:17)
    at ReEmitter.forSource (webpack-internal:///66:41:24)
    at Room.emit (webpack-internal:///38:152:5)
    at Room.addReceipt (webpack-internal:///57:1708:8)
    at Room.addEphemeralEvents (webpack-internal:///57:1508:12)
    at eval (webpack-internal:///56:1253:10)
    at Module.promiseMapSeries (webpack-internal:///33:894:11)
    at async SyncApi._processSyncResponse (webpack-internal:///56:1165:3)
```
I assume that the line that caused the error is client.js:412, throwing there would prevent `event` being emitted on client for a sync, but perhaps not much more...

**Comment by bwindels** [comment]
Apart from the above PR, not sure what else to do here apart from waiting for more occurences/specifics to narrow it down. Please report here if you see it again @ara4n

**Comment by bwindels** [comment]
Interesting, Dave's rageshake contained the same error:
```
Caught /sync error TypeError: Cannot read property 'highlight' of undefined
```
Which should be fixed with the above PR, so some evidence this is indeed the issue, although still not entirely sure how this is happening.

**Comment by ara4n** [comment]
Just had this again: https://github.com/matrix-org/riot-web-rageshakes/issues/2472

(Also https://github.com/matrix-org/riot-web-rageshakes/issues/1747 is a much older instance of the same symptoms)

**Comment by ara4n** [comment]
This is particularly nasty as it results in splitbrained conversations and general subsequent drama. "Why are you ignoring my messages?!"

**Comment by bwindels** [comment]
Changed to title as this is not just about messages the syncing user has sent, but also about the messages of other users not appearing.

**Comment by jryans** [comment]
So far, I am hearing that this only happens on nightly builds, so it seems like a bad interaction with Seshat's room crawling somehow. @poljar, would you happen to have any theories or ideas?

**Comment by poljar** [comment]
I looked at this already but concluded that it's fairly unlikely that Seshat is eating messages in unencrypted rooms as @bwindels rageshake points out so.

Now if it is indeed Seshat's fault it might have something to do that we have additional event listeners set up [here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/indexing/EventIndex.js#L178).

I saw something similar happen if I would await the decryption promise in the `onRoomTimeline` handler instead of adding it to a set like [here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/indexing/EventIndex.js#L193).

Though that happened only for encrypted rooms.

**Comment by jryans** [comment]
Hmm, I wonder if we may want to try / catch on the event emitter side (and possibly in each handler as well) of timeline events like that to ensure things can't go wrong...

**Comment by ara4n** [comment]
I haven't seen this in over a week. Either it was being triggered by Matrix.org being completely overloaded, or possibly a bad interaction with the /sync corruption we were seeing due to the replication rewrite, or some weirdness that has since gone away.  I would deprioritise it for now.

**Comment by turt2live** [comment]
Sync corruption is https://github.com/matrix-org/synapse/issues/7206 ftr

**Comment by turt2live** [comment]
see https://github.com/vector-im/riot-web/issues/10032#issuecomment-659120385
