### ISSUE TITLE
Riot-web doesn't give (anymore) any indication where it's coming from :(

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#12673]
Usually almost all packages give some indication as to where they are from where they are from within the OS repoistory archive or not. For e.g. :-

```
~$ apt-cache policy firefox-esr
firefox-esr:
  Installed: 68.5.0esr-1+b1
  Candidate: 68.5.0esr-1+b1
  Version table:
 *** 68.5.0esr-1+b1 900
        900 http://deb.debian.org/debian testing/main amd64 Packages
        100 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

Now for reasons unknown, riot decided not to show its sources even though its there in /etc/apt/sources.list.d/riot-im.list 

```
/etc/apt/sources.list.d$ cat riot-im.list 
deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ bullseye main
```

Just to share there is nothing wrong with the integrity of the package here is a report generated via reportbug which gives the stats. - 

```
Subject: abcd
Package: riot-web
Version: 1.5.12
Severity: normal

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (900, 'testing'), (500, 'testing-debug'), (100, 'unstable-debug'), (100, 'experimental'), (100, 'unstable'), (50, 'experimental-debug')
Architecture: amd64 (x86_64)

Kernel: Linux 5.4.0-4-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  libappindicator3-1  0.4.92-7
ii  libatspi2.0-0       2.34.0-4
ii  libgtk-3-0          3.24.13-1
ii  libnotify4          0.7.9-1
ii  libnss3             2:3.49.1-1
ii  libsecret-1-0       0.19.1-1
ii  libuuid1            2.34-0.1
ii  libxss1             1:1.2.3-1
ii  libxtst6            2:1.2.3-1
ii  xdg-utils           1.1.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information
```

The instructions taken are from https://riot.im/download/desktop/ . Looking forward for the fix.

**Comment by t3chguy** [comment]
riot-web was accidentally removed from the index when riot-nightly was added, it is being fixed today.

**Comment by shirishag75** [comment]
@t3chguy  it would have been better if you would have linked the commit that would have fixed it and then closed the bug, still would be nice if we can get some info. about it. Would it be 1.5.13 or how ?

**Comment by t3chguy** [comment]
There is no commit to fix it, it was an infrastructure issue which is fixed by logging into a box and running commands.

**Comment by shirishag75** [comment]
> There is no commit to fix it, it was an infrastructure issue which is fixed by logging into a box and running commands, the actual package isn't faulty, but the repository has accidentally removed the package from its indexes

ah ok, got you, so for us it's just running a normal `sudo apt update` that should fix it, say in 12-24 hours ?

**Comment by jryans** [comment]
> for us it's just running a normal `sudo apt update` that should fix it, say in 12-24 hours ?

Yes, `sudo apt update` is likely needed. It should be fixed now, so feel free to verify.

**Comment by shirishag75** [comment]
> > for us it's just running a normal `sudo apt update` that should fix it, say in 12-24 hours ?
> 
> Yes, `sudo apt update` is likely needed. It should be fixed now, so feel free to verify.

It didn't, shares the same as before. I did update the index just now.  - 

```
shirish@debian:"10 Mar 2020 18:06:13" ~$ apt-cache policy riot-web
riot-web:
  Installed: 1.5.12
  Candidate: 1.5.12
  Version table:
 *** 1.5.12 100
        100 /var/lib/dpkg/status
```

**Comment by jryans** [comment]
Hmm, okay, we'll keep this open as we continue investigating then.

**Comment by jryans** [comment]
@shirishag75 Can you try another `sudo apt update` and re-test?

**Comment by shirishag75** [comment]
> @shirishag75 Can you try another `sudo apt update` and re-test?

yup, now it got fixed, thank you :)
