### ISSUE TITLE
How to join an existing communit with riot-desktop?

### ISSUE THREAD

**Issue by c33s** [vector-im/riot-web#12699]
related to #9971 and #4428 but i haven't found a clear answer. 

riot-web version: 1.5.12
olm version: 3.1.3

there is the big plus sign on the left, where i come to a "communities" page. but there only another plus sign is listed with the following description

> Create a new community
> Create a community to group together users and rooms! Build a custom homepage to mark out your space in the Matrix universe.

but where to join an existing one? in electron there is no way i know to force electron to open a specific url.

as far as i understand only a button with a dialog where i can enter the commuinity name i know is missing. 
i am not sure that the approach to have an epic like #4428 is a good approach (with listing and search and...) if only a mini dialogbox is missing where i can enter the existing communities name. like visible in the screenshot of https://github.com/vector-im/riot-web/issues/4428#issuecomment-499442476
the epic issue is quite old and it looks like the feature is still missing.

1. is it possible to get an eta (only for the quickfix with a dialog box without a full listing)?
2. is there a workaround (with the desktop app)?

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/4428 is currently the ticket for this.

You can create an empty room and put the link in there, then click it to get to the community page as a workaround.

We currently do not have an ETA on any of the communities rework, but it is slated for sometime this year.

**Comment by c33s** [comment]
@turt2live putting the link in an empty room an clicking it helped to see the community on the right side but how to add a community to the community sidebar for quick access?

![2020-03-12 05_09_46- #  Riot _ dummy  #](https://user-images.githubusercontent.com/649209/76486641-3e967400-6420-11ea-85f1-b840ff7ab201.png)

**Comment by turt2live** [comment]
You can't at the moment: https://github.com/vector-im/riot-web/issues/5730

Support questions are best asked in #riot-web:matrix.org
