### ISSUE TITLE
new session toast pops up again after doing self-verification with same device

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12690]

**Comment by bwindels** [comment]
Rageshake https://github.com/matrix-org/riot-web-rageshakes/issues/2382

**Comment by bwindels** [comment]
Rageshake doesn't seem to contain all the information about the self-verification request, just this one cancel event sent by riot-web that moved the request from phase started to cancelled. 

```
2020-03-11T14:30:33.630Z I Verification request 7iNBC2trWduZGulkUOlKKzYrZrsw3TVt: m.key.verification.cancel event with id:undefined, content:{"code":"m.user","reason":"User declined","transaction_id":"7iNBC2trWduZGulkUOlKKzYrZrsw3TVt"} deviceId:UAAPDVEEIE, sender:@matthew:matrix.org, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>5, observeOnly:false=>false
```

`UAAPDVEEIE` is the device named `Mobile`, so presumably the iOS device. If this is indeed the self-verification request referred to in the title, it would mean `cancel()` was called on the request (with the default reason/code), which can happen from multiple locations (e.g. closing the verification dialog) but that also means the request didn't complete successfully. That would explain the new session toast appearing afterwards...

But without more information and also a rageshake from iOS this is only guesswork. Need more info.

**Comment by bwindels** [comment]
So I don't think this is related to https://github.com/vector-im/riot-web/issues/12926, as this is a toast for verifying another device and the other ticket is about self-verification. Not entirely sure whether there is even a problem (at least with toasts) here until we have more info, see comment above.

**Comment by dbkr** [comment]
oh, this has already been looked at - will leave for now

**Comment by jryans** [comment]
Sounds like we don't have enough info here to investigate, so I'll close for now. Please reopen / refile if it happens again.
