### ISSUE TITLE
goneb room is in the room directory even though it doesn't have an alias?

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12698]
The goneb room is in the matrix.org room directory but is unjoinable because there is no alias listed so clicking on it gives a "No known servers" error since it is trying to join by room ID.

<img width="727" src="https://user-images.githubusercontent.com/5855073/76481742-54844480-63e0-11ea-9d98-681e74b7193f.png">

**Comment by bwindels** [comment]
This looks like fallout from the recent alias changes in https://github.com/vector-im/riot-web/issues/12337

**Comment by bwindels** [comment]
#neb:matrix.org might want to consider setting a canonical alias. `m.room.aliases` have been deprecated by MSC2432 and Synapse doesn't seem to return any local aliases any more to prevent alias spam. I've filed https://github.com/matrix-org/synapse/issues/7069 as well to see if we can improve anything on the server side as well.

**Comment by bwindels** [comment]
Once we decide if and how to handle this on the synapse side, there might be some more work left on the riot side, so leaving it open for now, but as the fix is easy (adding a canonical alias) I'll deprioritize this.

**Comment by bwindels** [comment]
Turns out we can also improve the situation on the riot side by passing the currently selected server in the room directory to the join command. PR is out for that.
