### ISSUE TITLE
Setting the history visibility as part of room creation process shouldn't be displayed in the timeline

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1269]
When creating a room, the timeline shows "Amandine made future room history visible to all room members." just after "Amandine joined the room.". Given I didn't explicitly set the history visibility but it set itself by default it probably shouldn't be shown in the timeline.

The only reason to do it would be to make clear what is the current setting.

In that case let's improve the wording and not say a user set it but something like "The future room history visible to all room members" and possible do the same with other important settings like "Only people who have been invited can access this room". And display it _before_ the event saying the room creator joined the room (which also feels a bit clunky as really exposing how the tech works behind, but  I'm not entirely sure it should be removed yet).

Let's discuss about the conclusion: remove the event from the timeline or improve it.

**Comment by ara4n** [comment]
Agreed. I think we should just remove it, given all rooms share their history by default in vector.

**Comment by t3chguy** [comment]
Related to https://github.com/vector-im/riot-web/issues/8830
