### ISSUE TITLE
Request and respond to key sharing for backup key as well

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12704]
Similar to USK and SSK, we should also request and respond to the key backup key in 4S as well.

**Comment by foldleft** [comment]
we can see what's cached with `await mxMatrixClientPeg.get().restoreKeyBackupWithCache(undefined, undefined, await mxMatrixClientPeg.get().getKeyBackupVersion())`

If this throws, it means no cached key was available.

**Comment by foldleft** [comment]
I'm using this diff so I can run tests quickly:

```
diff --git a/src/components/structures/MatrixChat.js b/src/components/structures/MatrixChat.js
index 52002f059..fc6c9b1d6 100644
--- a/src/components/structures/MatrixChat.js
+++ b/src/components/structures/MatrixChat.js
@@ -1504,6 +1504,20 @@ export default createReactClass({
                 { failures, source, continuation });
         });
 
+        // XXX: probably don't commit?
+        // This is just so I can go right to the dialog
+        cli.on("restorekeybackup", () => {
+            const RestoreKeyBackupDialog =
+                sdk.getComponent('dialogs.keybackup.RestoreKeyBackupDialog');
+            Modal.createDialog(
+                RestoreKeyBackupDialog,
+                null, /* Props */
+                null, /* className */
+                false, /* Priority */
+                true, /* static */
+            );
+        })
+
         cli.on("crypto.verification.request", request => {
             const isFlagOn = SettingsStore.isFeatureEnabled("feature_cross_signing");
```

and then in the console:
`mxMatrixClientPeg.get().emit("restorekeybackup")`

**Comment by foldleft** [comment]
alright! Now we have a cache which should mean we only ever have to prompt the user for their backup keys once per session.

Still to do:

- [ ] Add a responder to `onSecretRequested` in `CrossSigningManager` to send the cached key on requests
- [ ] Modify `RestoreKeyBackupDialog` to fire a request to another device in the background, and use the key if it comes back

**Comment by foldleft** [comment]
the key sharing request during verification happens here: https://github.com/matrix-org/matrix-js-sdk/pull/1245/files#diff-0a3445e771f0c35ffee76e9d08b65e12R219

I think what's essentially needed is along the lines of

```
const client = MatrixClientPeg.get();
const key = await client._crypto.getSessionBackupPrivateKey();
if (!key) {
  const { promise } = client._crypto._secretStorage.request('m.megolm_backup.v1', devices);
  const result = await promise;
  if (result) {
    const decoded = decodeBase64(result);
    await client._crypto.storeSessionBackupPrivateKey(Uint8Array.from(decoded));
  }
}
```

problems to solve:
1. where to get the value `devices`
2. where to put this code (startup somewhere?)
3. handling the no-response case (a timeout)
4. handling the no-data case (return of `null`)

**Comment by jryans** [comment]
I think we'd want to at least request during a self verification, like with USK and SSK, so that all keys come across at the same time?

But yes, we may also want to request during restoring as well if we don't already have it.
