### ISSUE TITLE
Videoconference performance

### ISSUE THREAD

**Issue by erotavlas-turbo** [vector-im/riot-web#12702]
Hi,
I’m currently testing different platform for videoconferencing. In particular, I’m comparing riot.im, hangouts, teams, mega.nz and jitsi. I cannot figure out what is the maximum number of users in a conference call (audio/video). Moreover, does riot support desktop sharing?
Thank you

**Comment by dbkr** [comment]
This is a bug tracker rather than a forum for questions like this, however Riot uses Jitsi for conferencing, so you should look on the Jitsi forums: https://community.jitsi.org/search?q=maximum%20participants

**Comment by erotavlas-turbo** [comment]
> This is a bug tracker rather than a forum for questions like this, however Riot uses Jitsi for conferencing, so you should look on the Jitsi forums: https://community.jitsi.org/search?q=maximum%20participants

You are right, I already ask into [community help room](https://riot.im/app/#/room/#riot:matrix.org) without any response.
