### ISSUE TITLE
Enforce email on register

### ISSUE THREAD

**Issue by JOJ0** [vector-im/riot-web#12700]
**Is your suggestion related to a problem? Please describe.**
users registering without email don't have the ability to reset their passwords without an admin changing it for them in the db

**Describe the solution you'd like**
an option in config.yaml to enforce registration with email address.

**Describe alternatives you've considered**

**Additional context**
I hope I didn't miss that this feature is existing already. Tried a lot of googling and searching in issues already. Please point me in the right direction if this is possible already!

Thanks a lot for Matrix and Riot in any case!!!! Love it!

**Comment by t3chguy** [comment]
Riot (the client) can't enforce a demand for an e-mail, but the homeserver (Synapse) can.

https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml#L963-L967
