### ISSUE TITLE
Disable Free and Premium options on "Register - Create your account" page

### ISSUE THREAD

**Issue by JOJ0** [vector-im/riot-web#12701]
**Is your suggestion related to a problem? Please describe.**
Often new users click on the "Free" link "instead" of "Advanced" when first registering on my Matrix server via Riot-Web. Even though "Advanced" is pre-selected, the average user tends to choose a "Free" option over a "Premium" one and most probably not something "Advanced". IMHO this is misleading.

**Describe the solution you'd like**
An option in config.yaml to disable the registration on matrix.org and modular.

**Describe alternatives you've considered**
- Patching it out of the html page myselft via Ansible - please point me in the right direction which file holds this information before I start grepping through them. Thanks :-)
- A nice alternative would be to rename the "Advanced" Option to something like "Personal Homeserver", "This Self-hosted Matrix-Server", "This Private Homeserver, "This server" or the like AND most importantly make it the left-most option. Also the green-colored frame is very light and could be stronger to really let the user recognize that this is the option preselected already for him. 

If I missed that this is already possible, I am sorry to have bother you uselessly, please point me in the right direction. Thanks a lot!

**Comment by jryans** [comment]
`disable_custom_urls` in Riot's `config.json` should be helpful here.

**Comment by JOJ0** [comment]
Oh! That was too easy! Thanks a lot that helped perfectly.
