### ISSUE TITLE
Different logo for Riot Nightly

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12709]
So we can tell them apart

Split from https://github.com/vector-im/riot-web/issues/12452

**Comment by dreadnaut** [comment]
Out of nowhere, a "nightly" variation of the current logo:
![logo-nightly](https://user-images.githubusercontent.com/584584/76576590-6f2aec00-64ba-11ea-9177-b7d8d70b5daa.png)

[SVG version](https://github.com/vector-im/riot-web/files/4327090/logo-nightly.zip) (zipped, as GitHub does not accept SVG attachments.

**Comment by jryans** [comment]
We've decided this is not a blocker for cross-signing release.

**Comment by t3chguy** [comment]
Right now it looks like nightly has no icon at all however:
![image](https://user-images.githubusercontent.com/2403652/79215803-0b426d00-7e44-11ea-941c-3f7975fac469.png)

**Comment by turt2live** [comment]
@t3chguy sounds like a bug with our electron upgrade: https://github.com/vector-im/riot-web/issues/12518

**Comment by t3chguy** [comment]
I doubt it, all those reports are Linux caused by https://github.com/vector-im/riot-web/issues/12518#issuecomment-595780659
I use Windows

**Comment by turt2live** [comment]
It's also fine for me:
![image](https://user-images.githubusercontent.com/1190097/79263483-261ade80-7e50-11ea-8b86-d9c850723d3c.png)

**Comment by t3chguy** [comment]
Is it fine for you the moment the app starts?

**Comment by turt2live** [comment]
Oh, nope. Let's track that separately: https://github.com/vector-im/riot-web/issues/13170

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/14592
