### ISSUE TITLE
Close button overlaps dialog text on incoming verification

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12717]
(I'm slightly surprised to see this coming in as a dialog rather than a toast or in the timeline?)

<img width="356" alt="Screenshot 2020-03-12 at 21 15 26" src="https://user-images.githubusercontent.com/1294269/76567463-b9a26d80-64a6-11ea-8fab-c55e5ebeeace.png">

**Comment by bwindels** [comment]
I assume this is self-verification? Or with somebody who doesn't have cross-signing enabled?

**Comment by jryans** [comment]
It would be good to work out how we're even reaching this old modal. I haven't seen it myself recently, but there are several link issues above from seemingly both self-verif and other user verif.

**Comment by t3chguy** [comment]
This modal is used for to_device SAS verification, such as that incoming from a non-cross-signing device.
