### ISSUE TITLE
Not clear how to uninvite users who haven't joined rooms yet

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12711]
Users reporting they can't uninvite someone from a room after erroneously inviting them. We should ensure there's an uninvite button on invited users profiles.

**Comment by nadonomy** [comment]
I can see this button locally when testing:

<img width="343" alt="Screenshot 2020-03-12 at 13 15 38" src="https://user-images.githubusercontent.com/4626865/76525498-d4072780-6463-11ea-9865-a8e77702b8aa.png">

So I'll close out this issue for now until I get more debug info from the user hitting this.

**Comment by piegamesde** [comment]
@nadonomy this is likely because of a permissions issue: https://github.com/element-hq/element-web/issues/5273#issuecomment-2141413599
