### ISSUE TITLE
Seshat can be broken by disabling it?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12721]
My index looked weird on Nightly, so I restored from key backup. Seshat didn't appear to be doing anything so I clicked disable and pressed various toggles in the labs settings. Now I'm trying to press Enable again and it's just a spinner

**Comment by turt2live** [comment]
```
TypeError: Cannot read property 'addInitialCheckpoints' of null
```

RIP function.

**Comment by turt2live** [comment]
Workaround was to call `mxEventIndexPeg.deleteEventIndex()` then click the start button.

**Comment by poljar** [comment]
This has been hopefully addressed by https://github.com/matrix-org/seshat/pull/51, https://github.com/vector-im/riot-desktop/pull/48, and https://github.com/matrix-org/matrix-react-sdk/pull/4212.

At least I wasn't able to reproduce it anymore. We now wait for Tantivy to shut down before we delete the index, so no files should be left that would hinder the creation of a new one.
