### ISSUE TITLE
No Webcams detected

### ISSUE THREAD

**Issue by fedsax** [vector-im/riot-web#12723]
### Description
The Desktop version on Ubuntu doesn't recognise the Webcam.
Webcam works on the browser version ( firefoz)

Log: sent/not sent?    

### Version information

- **Platform**:
desktop - Ubuntu bionic

For the desktop app:

- **OS**:Ubuntu - No Webcams detected

**Comment by bwindels** [comment]
Thank you for reporting @fedsax. What version of riot are you using? If v1.5.11, please try updating to the latest v1.5.12 where we reverted some changes (updating electron to version 8) that could have caused this.

**Comment by fedsax** [comment]
![Screenshot_2020-03-13_11-06-02](https://user-images.githubusercontent.com/62133946/76611375-ae892500-651a-11ea-8202-5724886ba039.png)
I solved it. Going in the software app you can give permission to use the webcam
Thanks for replying
