### ISSUE TITLE
Riot-web client localhost server fails to start

### ISSUE THREAD

**Issue by ThobyV** [vector-im/riot-web#12738]
### Description

I am trying to start the riot-web client web application from a forked clone which I have installed all necessary dependencies for, and also  linked to `matrix-react-sdk` and `matrix-js-sdk` as per instructions on readMe file for riot-web.

However after running `yarn start` the server does not start and instead exits with an error:

`
[webpack.Progress] 94% after seal
Command failed with exit code 1
`
I have tried everything I could including upgrading/updating yarn etc. Although I suspect that either I am missing a step or that this is a webpack version build issue.

### Steps to reproduce
- run `yarn start` after fresh clone of all three riot-web client repos

Log: not sent    

### Version information

- **Platform**: web (in-browser) or desktop?

- **OS**: Linux x64 Fedora 28

**Comment by turt2live** [comment]
Usually this is memory related - webpack requires a fair number of resources to get going. It's best to ask your question in #riot-dev:matrix.org though instead of on the issue tracker.
