### ISSUE TITLE
User pills can wrap around lines

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12748]
(Screenshot inc) Visually, breaking the continuity of a pill over multiple lines is jarring. Is there a strong rationale for why we allow user pills to span line breaks?

**Comment by turt2live** [comment]
I think the answer is mostly just "CSS is hard"

**Comment by bwindels** [comment]
Related: https://github.com/vector-im/riot-web/issues/5739

**Comment by bwindels** [comment]
Perhaps we can use css ellipsis to trim a pill if it would span multiple lines (with the full name, mxid as a tooltip?)

**Comment by t3chguy** [comment]
See
![image](https://user-images.githubusercontent.com/2403652/76841951-68d99e80-6831-11ea-9479-7da91eadfb71.png)

**Comment by bwindels** [comment]
@benparsons reports:
![image](https://user-images.githubusercontent.com/274386/77167151-5cfa1080-6aad-11ea-83e5-0696d3af17ff.png)

**Comment by ara4n** [comment]
this used to be fine, i'm sure... when did it regress?

**Comment by benparsons** [comment]
I think something changed last week - never noticed it before then. Bruno's comment above is right after I pinged about it

**Comment by bwindels** [comment]
Might have regressed in https://github.com/matrix-org/matrix-react-sdk/commit/4996139b1a933cb4baf180ce05de106e907eef0a

**Comment by bwindels** [comment]
So I think it's either:
 - this
 - the previous behaviour where if a pill can't fit on one line, only the first line has a background color, 
![image](https://user-images.githubusercontent.com/274386/77552376-5acbf380-6eab-11ea-834d-1a5f4a747dc7.png)

 - we show an ellipsis if the pill can't fit on one line, we can do that with these changes:
```
a.mx_Pill {
- display: inline;
+ text-overflow: ellipsis;
+ white-space: nowrap;
+ overflow: hidden;
}
```

Although there seems to be an cropping issue with that:
![ellipsis](https://user-images.githubusercontent.com/274386/77552153-13ddfe00-6eab-11ea-915b-27bca089f4f3.gif)

**Comment by t3chguy** [comment]
As shown in screenshot between Nad and I above, privacy-cautious folk might care to see the entire thing.

**Comment by bwindels** [comment]
> As shown in screenshot between Nad and I above, privacy-cautious folk might care to see the entire thing which would rule out 3.

True, although that would only be the case if your timeline is not wide enough to show the entire display name ... which is rather exceptional.

**Comment by t3chguy** [comment]
Pills can show in other more narrow panels too:
![image](https://user-images.githubusercontent.com/2403652/77646505-9246a880-6f5c-11ea-8fdf-818d5b28af2e.png)

**Comment by ara4n** [comment]
The new behaviour is really really annoying:

<img width="928" alt="Screenshot 2020-04-17 at 10 12 43" src="https://user-images.githubusercontent.com/1294269/79553318-36bb9680-8094-11ea-8314-b8de8cd24927.png">

I suggest we fix it by putting an ellipsis on it and hoverover text to disambiguate it for privacy purposes.

**Comment by t3chguy** [comment]
> Regressed in matrix-org/matrix-react-sdk@4996139

I wouldn't say that, it used to look way worse.
![image](https://user-images.githubusercontent.com/2403652/79557561-af255600-809a-11ea-982d-5b4929058994.png)

Using 3. above failed for me:
![image](https://user-images.githubusercontent.com/2403652/79557744-fa3f6900-809a-11ea-9084-dfeca17ce8f5.png)

but adding a `max-width: 100%;` fixed that

![image](https://user-images.githubusercontent.com/2403652/79557793-17743780-809b-11ea-9bb9-e2da2ba246e9.png)

**Comment by ara4n** [comment]
thanks
