### ISSUE TITLE
Blank page accessing chat.mozilla.org - SyntaxError: missing ( before catch

### ISSUE THREAD

**Issue by IanN-GH** [vector-im/riot-web#12746]
If you try to access chat.mozilla.org with some browsers all you get is a blank page with the following message in the Error Console:

Timestamp: 3/10/20, 9:24:49 AM GMT
Error: SyntaxError: missing ( before catch
Source File: https://chat.mozilla.org/bundles/2f0ae51a45924d8f7f72/bundle.js
Line: 2, Column: 4390563
Source Code:
c e=>{const t=O.a.get();let n;try{n=await t.getStats()}catch{return}this.setState({eventIndexSize:n.size,roomCount:n.roo

I presume there should be something other than a blank page.

### Version information

riot-web version: v1.5.12
olm version: 3.1.3

For the web app:

- **Browser**: SeaMonkey 2.53.1
- **OS**: Fedora 30
- **URL**: chat.mozilla.org

**Comment by t3chguy** [comment]
SeaMonkey is not a supported browser. See https://github.com/vector-im/riot-web#supported-environments

**Comment by t3chguy** [comment]
```javascript
c e=>{const t=O.a.get();let n;try{n=await t.getStats()}catch{return}this.setState({eventIndexSize:n.size,roomCount:n.roo
```
as a snippet looks like a valid bit of Javascript, a try-catch.
