### ISSUE TITLE
unverified session toast is not dismissed after verifying session

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12754]

**Comment by jryans** [comment]
(I guess it's story 1, since it's self verif, but please flip back if I misunderstood.)

**Comment by bwindels** [comment]
right, makes me realize I should probably look once in a while in the `story:1` bucket, as the verification code is roughly the same for self and user verification.

**Comment by bwindels** [comment]
Closing, can't repro anymore, so must have been fixed by something in the meantime.
