### ISSUE TITLE
Jitsi widget screensharing on scalar.vector.im does not work in Firefox

### ISSUE THREAD

**Issue by pv** [vector-im/riot-web#12755]
### Description

Screensharing does not work in the Jitsi videoconferencing widget, when opened in a Firefox window (https://scalar.vector.im/api/widgets/jitsi.html?...).

This is on Linux (on both X11 and Wayland), Firefox 74.0. The screen sharing does work fine in Firefox on https://meet.jit.si, and only https://scalar.vector.im is having problems. The screen sharing in https://scalar.vector.im/ does work in Chrome (chromium 79.0.3945.130).

**EDIT:** also tested on Windows, with the same result.

### Steps to reproduce

- Create new profile in Firefox (or reset all settings to defaults).
- Open Riot and log into a Matrix channel with a Jitsi widget.
- On Jitsi videoconferencing widget, click on "Open app in new windows".
- That opens a page https://scalar.vector.im/api/widgets/jitsi.html?... in Firefox.
- Videoconferencing itself appears to work fine on that page.
- In Firefox, on that page, click on the screensharing button on lower left. Nothing happens when the button is clicked (and no error etc messages appear on the screen).

What I expected to happen, is that clicking this button asks for permissions for screen sharing, and if they are given, starts sharing the picture from the desktop to other participants.

In Firefox devtools console, the following messages appear every time the button is clicked: 

<details>

```
[modules/RTC/RTCUtils.js] <value>:  Using the new gUM flow Logger.js:125:17
[modules/RTC/ScreenObtainer.js] <obtainScreenFromGetDisplayMedia>:  Using getDisplayMedia for screen sharing Logger.js:125:17
[react/features/base/tracks/functions.js] <a/<>:  Failed to create local tracks 
Array [ "desktop" ]
 
{…}

message: "User canceled Chrome's screen sharing prompt"

name: "gum.chrome_extension_user_canceled"

stack: "a@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:117805\nobtainScreenFromGetDisplayMedia/<@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:180571\n"

<prototype>: {…}

constructor: function a(e, t, n)

stack: ""

<prototype>: Object { … }
app.bundle.min.js:35:62066
[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  
{…}

message: "User canceled Chrome's screen sharing prompt"

name: "gum.chrome_extension_user_canceled"

stack: "a@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:117805\nobtainScreenFromGetDisplayMedia/<@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:180571\n"

<prototype>: Object { constructor: a(e, t, n), stack: "" }
Logger.js:125:17
uncaught exception: Object
XHRPOSThttps://jitsi.riot.im//http-bind?room=<censored>
[HTTP/1.1 200 OK 10059ms]

[modules/RTC/RTCUtils.js] <value>:  Using the new gUM flow Logger.js:125:17
[modules/RTC/ScreenObtainer.js] <obtainScreenFromGetDisplayMedia>:  Using getDisplayMedia for screen sharing Logger.js:125:17
[react/features/base/tracks/functions.js] <a/<>:  Failed to create local tracks 
Array [ "desktop" ]
 
Object { name: "gum.chrome_extension_user_canceled", message: "User canceled Chrome's screen sharing prompt", stack: "a@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:117805\nobtainScreenFromGetDisplayMedia/<@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:180571\n" }
app.bundle.min.js:35:62066
[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  
Object { name: "gum.chrome_extension_user_canceled", message: "User canceled Chrome's screen sharing prompt", stack: "a@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:117805\nobtainScreenFromGetDisplayMedia/<@https://jitsi.riot.im/libs/lib-jitsi-meet.min.js?v=139:6:180571\n" }
Logger.js:125:17
uncaught exception: Object
XHRPOSThttps://jitsi.riot.im//http-bind?room=<redacted>
[HTTP/1.1 200 OK 10037ms]

XHRPOSThttps://jitsi.riot.im//http-bind?room=<redacted>
```
</details>

### Version information

- **Platform**: desktop
- **Browser**: Firefox 74.0
- **OS**: Linux (Fedora 31 x86_64) (tested to occur both on X11 and Wayland); also reproducible on Windows.
- **Desktop app version**: 1.5.12

**Comment by tamas-z** [comment]
Can confirm the same behavior on Arch, using Firefox 74.0 on X11.

**Comment by jryans** [comment]
This seems related to https://github.com/jitsi/jitsi-meet/pull/5180, so we likely need to wait for a Jitsi release that includes that and upgrade.

**Comment by turt2live** [comment]
People won't be able to see this, but I have submitted the task of an upgrade to ops: https://github.com/orgs/matrix-org/projects/20#card-35712383

**Comment by jryans** [comment]
We have upgraded Jitsi and I have verified that screensharing works in Firefox via widgets, so I believe this is resolved.
