### ISSUE TITLE
Hide video and phone call buttons in composer when config option set

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12758]
No changes by default. We would support a new config.json option that would hide the video and phone call buttons for situations where it is more confusing than helpful.

**Comment by jryans** [comment]
You can add the following to config.json to hide the call buttons:

```
    "settingDefaults": {
        "showCallButtonsInComposer": false
    }
```

**Comment by schneif2** [comment]
Will it be possible to disable only video call button?

**Comment by jryans** [comment]
> Will it be possible to disable only video call button?

Please open a new issue with more about your use case so we can evaluate the best path.
