### ISSUE TITLE
No indication of sending problems

### ISSUE THREAD

**Issue by ErrorProne** [vector-im/riot-web#12768]
### Description

I'm not quite sure if this is a real bug or a problem with synapse, but I just want to rise awareness for this, maybe something can be done.
We stumbled upon a bug yesterday where 1:1 messages after synapse upgrade could be sent to one server but not the other way around (see https://github.com/matrix-org/synapse/issues/7099)

The "problem" with riot is that the users did not get any indication that the messages could not be delivered. I'm not sure if riot actually receives any information about this from the homeserver, in this particular case.

Versions involved:

Hard to figure out afterwards, there have been multiple versions of riot web (and some riotX) involved, but at least one instance of riot web 1.5.12. Also multiple OS from Windows to Linux and Browser from Firefox to Chrome in different versions have been used.

**Comment by t3chguy** [comment]
>  I'm not sure if riot actually receives any information about this from the homeserver, in this particular case.

Riot only gets to know if the message was successfully persisted into the room, as Matrix is eventually consistent it is actually considered acceptable that messages may not arrive for a while.

**Comment by ErrorProne** [comment]
Thanks, I expected something like this. Than this should be fine from a riot perspective =)
