### ISSUE TITLE
Cannot send message in encrypted room

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12761]
Multiple reports by @anoadragon453 that he is unable to send messages in e2ee rooms.
The logs contain a lot of `Error downloading keys for <userid1>, <userid2>, ...: No signature`

**Comment by bwindels** [comment]
Rageshakes:
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2406
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2409
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2411

**Comment by bwindels** [comment]
Dave says:

wrt to the many key requests: last time I looked at this it was synapse sending device list change events all the time, https://github.com/matrix-org/synapse/issues/6162

wrt to signature error: could be something like that sig not making it over federation, perhaps

**Comment by bwindels** [comment]
Possibly related: https://github.com/matrix-org/riot-web-rageshakes/issues/2413

**Comment by anoadragon453** [comment]
Happy to help with whatever you need here, as it impacts me quite a bit :D 

Note that things work on mobile, but not on riot web, no matter which domain I use.

**Comment by bwindels** [comment]
Discussion (also) on https://github.com/matrix-org/riot-web-rageshakes/issues/2406

**Comment by anoadragon453** [comment]
Right, I'm also unable to send encrypted messages from RiotX (latest debug), which is also X-signing enabled.

**Comment by uhoreg** [comment]
> Possibly related: [matrix-org/riot-web-rageshakes#2413](https://github.com/matrix-org/riot-web-rageshakes/issues/2413)

If I've properly diagnosed anoa's issue, then this one seems to be something different.
