### ISSUE TITLE
Upgraded room showing twice in Room List

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12776]
This persists over restarts.

<img width="1351" alt="Screenshot 2020-03-18 at 16 36 23" src="https://user-images.githubusercontent.com/1294269/76984440-bf7cd080-6936-11ea-8e1e-9f131dbb7902.png">

**Comment by turt2live** [comment]
Effective duplicate of https://github.com/vector-im/riot-web/issues/11724
