### ISSUE TITLE
Custom Tag Scrolling

### ISSUE THREAD

**Issue by SaturnSoftware** [vector-im/riot-web#12785]
### Description

Custom tags don't scroll like communities do, so when there's too many of them, it adds whitespace to the bottom of riot. 

### Steps to reproduce

add custom tags and enable it in labs
resize the window so that the custom tags go past the bottom of the screen.

![image](https://user-images.githubusercontent.com/20211219/77058780-eae9d480-69a3-11ea-8031-a6007a0598b3.png)

### Version information

- **Platform**

riot-web version: 7296b704a8a4-react-ce90cbe35ef7-js-11e3b1ab5305
( /develop ) 
firefox
windows

**Comment by t3chguy** [comment]
Please fill the issue template. 3 Words are not enough.

**Comment by SaturnSoftware** [comment]
That was an accident, i'm sorry, i pressed enter by mistake. 😓

**Comment by t3chguy** [comment]
So this is a bug caused by removal of gemini

**Comment by t3chguy** [comment]
Actually not a release blocker because its in Labs
