### ISSUE TITLE
"View community" link very difficult to see on macOS

### ISSUE THREAD

**Issue by clokep** [vector-im/riot-web#12797]
![image](https://user-images.githubusercontent.com/517124/77105970-cbc76300-69f4-11ea-9c0c-2c06e29a8d44.png)

### Description

The "..." in the top-right of the community icon has very low contrast and is difficult to see (it seems to be white on gray). I actually didn't realize that was separately clickable for a while (and couldn't figure out how to get back to the community "overview" page).

### Steps to reproduce

- Join a community
- Hover over it so that the "View community" link appears
- Try to notice the "..." in the middle of it

Note that this is probably made worse by using a retina screen.

### Describe how what happens differs from what you expected.

I'd expect more contrast so that the "..." is clearly visible in the bubble.

### Version information

- **Platform**: Riot Desktop
- **OS**: macOS 10.15.3
- **Version**: 2020031901

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/77106241-ae0af580-6a16-11ea-988a-13382ae46cd2.png)

Its not any better on a 4k Windows instance with dark theme

**Comment by ThobyV** [comment]
Can I be assigned to this issue?

**Comment by clokep** [comment]
Thanks for fixing this! 👍
