### ISSUE TITLE
Trying to search with Seshat, i got "db locked" and "corrupt db" errors

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12791]
https://github.com/matrix-org/riot-web-rageshakes/issues/2427

**Comment by poljar** [comment]
PR that should fix this: https://github.com/matrix-org/seshat/pull/55.

**Comment by poljar** [comment]
PR merged, should be fixed in the next Seshat release and nightly build.

**Comment by jryans** [comment]
@poljar Do need to also update the Seshat version in `riot-desktop` to get the fix?

**Comment by poljar** [comment]
Yes, but first I need to do a release, will bump the version requirement after that.
