### ISSUE TITLE
Slow server can cause E2EE to wedge completely.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12792]
https://github.com/matrix-org/riot-web-rageshakes/issues/2429
https://github.com/matrix-org/riot-web-rageshakes/issues/2413
possibly https://github.com/matrix-org/riot-web-rageshakes/issues/2419
https://github.com/matrix-org/riot-web-rageshakes/issues/2431

I had a few toDevice sends which were taking 23s or more, and i think there may be some failure mode where the crypto subsystem wedges solid and can't recover.

This is particularly frustrating on Nightly, as you can't hit refresh - and also, the app is so stuck that it refuses to quit. So you have to force quit (kill -9) it and reload.

**Comment by bwindels** [comment]
Do you get "Your message was not sent" when it fails in the room status bar?

**Comment by turt2live** [comment]
(as someone who is also on a super slow server (>60s request times on average), I'm not seeing this level of failure. Could be matrix.org specific, or platform specific, or both)

**Comment by ara4n** [comment]
> Do you get "Your message was not sent" when it fails in the room status bar?

no, it's stuck in greyish-green forever.

**Comment by ara4n** [comment]
A consistent pattern I'm seeing here is that to_device messages are taking *ages* to send (like, minutes) - and the client can get stuck somewhere and never recover.  I also saw this on FF, at https://github.com/matrix-org/riot-web-rageshakes/issues/2431

**Comment by bwindels** [comment]
Hmmm, to try and repro, I've hardcoded a 2min delay on sending any `m.room.encrypted` to_device messages on a local riot and synapse. Messages all got sent and riot stayed responsive.

**Comment by ara4n** [comment]
@lampholder is seeing this too on nightly.

I wonder if we have two problems: Nightly gets stuck entirely (and then won't quit), but FF completes eventually somehow?

I'm also seeing *huge* delays on calls to /claim (20-60s on matrix.org atm), and more /claim calls in general than i'd expect.

**Comment by jryans** [comment]
> I'm also seeing _huge_ delays on calls to /claim (20-60s on matrix.org atm), and more /claim calls in general than i'd expect.

The PRs for https://github.com/vector-im/riot-web/issues/11836 merged ~4 days ago, so that could be related to more `/claim` traffic, although it looks like it merged ~1 hour _after_ this issue was first opened, so you were already experiencing some other problem it would seem.

@uhoreg, do you have cycles to investigate this issue?

**Comment by uhoreg** [comment]
Seems to be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1280
