### ISSUE TITLE
Key signature upload fails after verification 

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12790]
This is a verification between riot-web and riotx

 `/keys/signatures/upload` request:
```
{
  "@valou35:matrix.org": {
    "NGGABWQQKB": {
      "algorithms": [
        "m.megolm.v1.aes-sha2",
        "m.olm.v1.curve25519-aes-sha2"
      ],
      "keys": {
        "curve25519:NGGABWQQKB": "TqdCPTEbKoh5yi9uvS8eCdnnqdE572XJne20CADU7G0",
        "ed25519:NGGABWQQKB": "ukdvwtkgmxxDTcKRBWEgKCbX7i1741HsAukdc6IroOA"
      },
      "device_id": "NGGABWQQKB",
      "user_id": "@valou35:matrix.org",
      "signatures": {
        "@valou35:matrix.org": {
          "ed25519:MKLPfimUGo0n7NK5pPzaHbPYTI+UQcaVp2X9SCOS3HE": "7NIAOLQC9mhHRiHE969LBdM+pjsuzMKvax8hPL0GgvjCNNIk7jhp/d9dCkL3LnwPBn8+kOmTQQ1woJ/1PuyhBw"
        }
      }
    }
  }
}
```
and response:
```
{
  "failures": {
    "@valou35:matrix.org": {
      "NGGABWQQKB": {
        "status": 400,
        "errcode": "M_INVALID_SIGNATURE",
        "message": "400: Invalid signature"
      }
    }
  }
}
```

**Comment by bwindels** [comment]
Discussion: https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$NJNZvWZq_xMedoSgz3Ywz4bLwF0tRkpQvuDOUsNMdI4?via=matrix.org&via=vector.modular.im&via=half-shot.uk

**Comment by non-Jedi** [comment]
I'm seeing what I assume is this same failure between two riot-web develop instances. I've submitted debug logs, but please let me know if there's any other info I can give (I can consistently replicate the error).

**Comment by bwindels** [comment]
@non-Jedi Thanks for reporting, it looks more like your server is not happy, with a lot of:
```
2020-03-26T19:24:28.065Z I failed to claim one-time keys Internal server error ...
2020-03-26T19:24:31.983Z I Key backup request failed Internal server error ...
```
To be sure, could you also submit logs from the linux side (also referring to this ticket)?

With regard to the server errors, it looks like you might be running your own homeserver. If so, could you look into your synapse logs and post a bug with the internal server errors in https://github.com/matrix-org/synapse/issues/ ?

Thanks!

**Comment by bwindels** [comment]
Actually @non-Jedi this seems to be a problem with riot-web, see https://github.com/vector-im/riot-web/issues/12901 so no need to submit a synapse issue.

**Comment by non-Jedi** [comment]
Great. Thanks for updating me. :)

**Comment by bwindels** [comment]
@non-Jedi Have you reset cross-signing keys on your account by any chance?

**Comment by bwindels** [comment]
This is likely to be have been an instance of https://github.com/vector-im/riot-web/issues/13056. Hard to tell now, as we can't check any more if the cross-signing keys mismatched between the clients. It could have gone like this:

 - User starts riot-web session 1
 - User starts riot-web session 2
 - User resets cross-singing key on session 1 (session 2 would not adopt these new keys)
 - User tries to verify riotx session from session 2 and server complains about bad signature.

**Comment by jryans** [comment]
Okay, it sounds like we have a good theory linked to a fixed issue, and there's nothing more we can do for this instance, so let's consider this closed until we hear another case.
