### ISSUE TITLE
I see two different emoji fonts used for SAS on same platform & browser

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12807]

**Comment by bwindels** [comment]
![image](https://user-images.githubusercontent.com/274386/77167362-cf6af080-6aad-11ea-87e4-e71d018ca862.png)

**Comment by bwindels** [comment]
Both are Version `79.0.3945.130 (Developer Build) Fedora Project (64-bit)`, just different profiles.

**Comment by ThobyV** [comment]
Please can I be assigned to this issue?

**Comment by bwindels** [comment]
Sure, that would be great! We welcome lots of communication about the analysis and progress on the issue, rather than just one big PR that changes a whole bunch of stuff :)

Some background info:
We use the twemoji font (in multiple formats for different browsers, see FontManager), but here one of the labels seems to be using the native emoji font, which we don't want.

We might need this done within a week or so, so if I haven't heard back I might need to reassign it to myself by then.

**Comment by bwindels** [comment]
Having a look at this

**Comment by jryans** [comment]
PR was reverted, reopening for now.
