### ISSUE TITLE
SAML SSO for Mozilla via Github failing with bad /authn_response

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12801]
> Hope this is the right place to say this: I tried to signup using github but after the authorization was done, redirected to mozilla.modular.im and the webpage was like:
>> Method Not Allowed Your browser approached me (at /_matrix/saml2/authn_response) with the method "GET". I only allow the method HEAD here.

**Comment by bwindels** [comment]
Convo is here: https://matrix.to/#/!pcfWjiETvnVuspPLPl:mozilla.org/$IO71OeAO1JOD9WeTOiTZ5_uOJahvRyO840AoWfip9Dg?via=mozilla.org&via=matrix.org&via=maunium.net

**Comment by bwindels** [comment]
Is this something to solve in Riot @ara4n? If not, shall we move it to the correct repo?

**Comment by jryans** [comment]
I filed https://github.com/matrix-org/matrix-synapse-saml-mozilla/issues/7 for this.
