### ISSUE TITLE
minimising a jitsi widget seems to keep the jitsi running still

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12810]
which could be very surprising, in terms of keeping broadcasting despite being minimised

**Comment by pv** [comment]
matrix-react-sdk@c000583 with this change seems to abruptly disconnect on widget minimize without cleanly hanging up, leaving a "ghost" user behind in the conference that disappears after the ~30sec disconnect timeout. Happens on Chromium (80.0.x), but usually not on Firefox 75. (Ran into this while looking to address https://github.com/vector-im/riot-web/issues/12986 with https://github.com/matrix-org/matrix-react-sdk/compare/develop...pv:jitsi-close-on-popout)

**Comment by turt2live** [comment]
That's because we don't have an opportunity to disconnect cleanly. If there is a way we didn't notice/consider, please open a PR.
