### ISSUE TITLE
new jitsi labels the conferences with super ugly conference names, derived from the randomly generated ID

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12812]

**Comment by ara4n** [comment]
this happens whether using scalar or the new embedded jitsi IM.  I think the fix is to make the new embedded Jitsi IM generate IDs which aren't so fugly when rendered by Jitsi.  Currently it looks like this:

<img width="570" alt="Screenshot 2020-03-20 at 14 52 15" src="https://user-images.githubusercontent.com/1294269/77175350-6b9af480-6aba-11ea-9169-7a411225a7ff.png">

**Comment by turt2live** [comment]
This is neither a release blocker or priority issue, just a really nice to have from what I understand.

**Comment by jryans** [comment]
I'll take a look at this, as it would be nice to have given how the ID appears in the new Jitsi UI.
