### ISSUE TITLE
Encrypted by a deleted session

### ISSUE THREAD

**Issue by squidink7** [vector-im/riot-web#12828]
On every removed message there is a yellow bar and red sheild saying "Encrypted by a deleted session" when the mouse is hovered over it.

Steps to reproduce: 
Remove a message, and hover your mouse over the grey redaction bar.

Version:
riot web ffd155a6aa7d-react-2df06800cc0a-js-6a7a25508189
Chrome 80
Arch Linux ARM
riot.im/develop

**Comment by bwindels** [comment]
Thanks for reporting @squidink7. I cannot reproduce this locally. Can you provide some more information? Do you see this happening in any room? Did the sender perhaps log out after sending the messages? If not, could you please provide:
 - a screenshot of what you are describing
 - submit debug logs (from help & about in the settings), linking back to this issue

Thank you

**Comment by squidink7** [comment]
Strange, I went back to the same messages the next day and they didn't say it anymore. It must have been a once off or fixed with an update.
