### ISSUE TITLE
Search field of current rooms should also search the canonical room alias and maybe the topic

### ISSUE THREAD

**Issue by tuxayo** [vector-im/riot-web#12822]
**Is your suggestion related to a problem? Please describe.**
#linuxgaming:maunium.net is named "general"
#opensuse:matrix.org is named "general"

So they aren't found we searching for "linux", "gaming" or "suse"

**Describe the solution you'd like**
The search should also include the room id, or the description.

**Describe alternatives you've considered**
Maybe the rooms should always be prefixed by their general topic. (not sure requesting will work enough to make the issue non-relevant) I don't know what's better.

**Additional context**
The search for adding a new room on the other hand searches in the room ID and the description.

Note that it searches in the full room id so it's possible to search for "matrix" to find room related to the project. Should I open an issue about this?

**Comment by t3chguy** [comment]
This actually used to work, code for it is here https://github.com/matrix-org/matrix-react-sdk/blob/4da7ce10de46eff134d93d3f2fda7dd1ce639e23/src/components/views/rooms/RoomList.js#L650

but regressed with recent alias management changes.
