### ISSUE TITLE
UI doesn't support markdown tables

### ISSUE THREAD

**Issue by deterok** [vector-im/riot-web#12820]
I used this text to test tables
```
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
```
and got this:
![image](https://user-images.githubusercontent.com/1702003/77225307-f47b6400-6b7e-11ea-8527-653e11ad8364.png)

What I do wrong?

**Comment by t3chguy** [comment]
Riot uses commonmark which doesn't support entering tables. Riot supports rendering them if sent via an alternate means.
