### ISSUE TITLE
"Failed to access your microphone" / "Cannot use microphone for an unknown reason."

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/riot-web#12826]
### Description

I've set my Logitech camera with integrated microphone under Riot -> Settings -> Voice & Video ->  Microphone but accessing the Jitsi widget I get an orange warning box:

> Failed to access your microphone
> Cannot use microphone for an unknown reason.
> OK

The camera and microphone works fine in direct (1to1) audio/video calls.

### Steps to reproduce

1. I've attached my camera.
2. I've started Riot and set the camera and microphone in settings.
3. I add the Jitsi widget.
4. I press "Join Conference".
5. I get the warning joining the conference:

![riot-web_jitsi-micro-fail](https://user-images.githubusercontent.com/44623983/77250451-6370bf80-6c48-11ea-858b-4ee259a055c1.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian 10
- **Version**: 1.5.13

```
# apt policy riot-web
riot-web:
  Installed: 1.5.13
  Candidate: 1.5.13
  Version table:
 *** 1.5.13 500
        500 https://packages.riot.im/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
#
```

**Comment by bwindels** [comment]
@r4dh4l could you please submit your debug logs? You can do this from "Help & About" in the settings.

**Comment by jryans** [comment]
(Removed from inferno queue until we get more info.)

**Comment by r4dh4l** [comment]
Sorry for my late reply. I think the problem is more related to JitsiMeet. I had similar problem with JitsiMeet outside Matrix/Riot and have currently no time to reproduce the error providing error logs. I will re-open the issue when I have time for further investigations.
