### ISSUE TITLE
Feature request: /passwd riot command to change password of home server accounts as admin?

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/riot-web#12824]
Hi,

it would be nice to have the possibility to change account password from within Riot (currently I do this accessing the database which is a little bit exhausting and nothing I can do when I'm on the way). I would imagine something like this:

1. I open a room used just by me created on my home server.
2. I type `/passwd alice NewPassword` (or `/passwd @alice:myhomeserver.com NewPassword`) and the new password of `@alice:myhomeserver.com` is set to `NewPassword`.

Would this be a useful feature or did I forget something why this is not good idea?

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/4125
