### ISSUE TITLE
SSO sign-in uses unknown vector:// URL type

### ISSUE THREAD

**Issue by paulmelis** [vector-im/riot-web#12830]
### Description

Signing in to an internal chat server that uses SSO does not work as some of the browser-based flow is broken.

### Steps to reproduce

- Start riot desktop application
- Click `Sign in`
- Click `Change` to use our internal server, click `Next`
- Click `Sign in with single sign-on`
- Browser (firefox) window opens with our internal SSO page, where I log in
- Get a new browser page with `The application at vector is requesting full access to your <censored> Matrix account. If you don't recognise this address, you should close this browser window.`, plus a button with `I trust this address`
- Pressing the address button redirects the page to a URL reading `vector://vector/webapp/?homeserver=...`
- Browser gives error `The address wasn’t understood`

Describe how what happens differs from what you expected.

The browser should probably open the riot application with the verification info in the URL, but that doesn't work, as the `vector://` type isn't understood.. [This issue](https://github.com/flathub/im.riot.Riot/pull/93) seems similar, but it mentions a "riot://" URL, plus I'm not using the flathub version of the application.

Is there a way to manually give back the login URL to the `riot-desktop` application? I check the command-line params but don't see a relevant option.

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.13 (note: the latest available version in the Arch repos is currently 1.5.12, I updated the PKGBUILD locally and built it to check if the SSO updates in 1.5.13 helped with the issue, but they don't)

**Comment by t3chguy** [comment]
Seems like its running with the wrong electron version. In riot-web 1.6 the flow does break out to browser but currently it should open in-app.
in 1.6 a `riot://` protocol handler gets registered so the browser knows where to send it.

**Comment by paulmelis** [comment]
Electron version I've have installed is 8.0.2, which is slightly older than the current 8.1.1 in the Arch repos. There's also packages for version 7 and before. Which version should riot-desktop use?

**Comment by t3chguy** [comment]
Are you building from this repo or from actual riot-desktop: https://github.com/vector-im/riot-desktop

For this repo, 7: https://github.com/vector-im/riot-web/blob/develop/package.json#L155 . For riot-desktop I believe 8

**Comment by paulmelis** [comment]
The sources come from https://github.com/vector-im/riot-web, i.e. this repo

**Comment by t3chguy** [comment]
Therefore, as per the package.json, the electron 7 specified there.

**Comment by paulmelis** [comment]
Ok, I'll try building against v7. But shouldn't the build process check if electron7 is actually available? Or does it get downloaded during the build? Sorry, I'm not really familiar with the whole JS/Rust build pipeline, I'm more of a C++ type.

**Comment by t3chguy** [comment]
The build process (electron-builder) reads from the package.json and downloads that electron version for building with
In the case of linked packages in Linux it may be using system level packages instead however

**Comment by paulmelis** [comment]
Strange, I removed the electron 8 package from my system, installed the electron7 package and updated the PKGBUILD. Rebuilt the package, reinstalled, but it still uses the external browser to process the SSO info (which still fails).

```
melis@juggle 14:33:~$ pacman -Q |grep electron
electron4 4.2.12-3
electron7 7.1.14-1

melis@juggle 14:34:~$ cat /usr/bin/riot-desktop
#!/bin/bash

electron7 /usr/lib/riot/app.asar "$@"
```

**Comment by t3chguy** [comment]
can you check the electron console to see if it says `Using Web platform` or `Using Electron platform` ?

When you start SSO flows does the electron window get a modal saying `Go to your browser to complete Sign In?`

**Comment by paulmelis** [comment]
> can you check the electron console to see if it says Using Web platform or Using Electron platform ?

It reads `Using Electron platform`.

> When you start SSO flows does the electron window get a modal saying Go to your browser to complete Sign In?

No, it merely opens a browser window, but the app keeps the Sign in screen with the button `Sign in with single sign-on`. No other windows/boxes appear

**Comment by t3chguy** [comment]
Seems like the riot build is somehow broken then. Did you use a tarball build or did you build riot-web 1.5.13 yourself?

**Comment by paulmelis** [comment]
This is with the official Arch build recipe, which I merely updated to the 1.5.13 sources. Specifically the PKGBUILD file here: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/riot

**Comment by paulmelis** [comment]
Perhaps only the SSO stuff is broken in the Arch build? I would expect users to complain if the app is completely unusable with respect to logging in

**Comment by t3chguy** [comment]
Indeed looks that way, it looks to be pulling a tarball which should be fine. It looks to be missing the necessary matrix-react-sdk changes somehow :/

**Comment by paulmelis** [comment]
> It looks to be missing the necessary matrix-react-sdk changes somehow :/

Where would those changes get applied? During the build? Or should they be part of the source tarball? Any pointers to what I can check?

**Comment by t3chguy** [comment]
Is this still an issue with 1.5.15?

**Comment by paulmelis** [comment]
> Is this still an issue with 1.5.15?

Yes, I just tried the official Arch package for 1.5.15, which still opens the browser for the SSO. I also hacked the package build script again to make it depend on electron7 (and uninstalled electron 8 from my system). Unfortunately, that also shows the SSO issue.

**Comment by t3chguy** [comment]
> which still opens the browser for the SSO

That is intentional. Does it still try and callback to `vector://` though or `riot://`

**Comment by paulmelis** [comment]
Btw, in the dev console I see a message 

```
bundle.js:2 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('vector://vector') is not supported.
    at Module.<anonymous> (bundle.js:2)
    at r (bundle.js:2)
    at bundle.js:2
    at bundle.js:2
```

and it still says "Using Electron platform"

**Comment by t3chguy** [comment]
The service worker failing is fine for electron, it should just be skipped there tbh

**Comment by paulmelis** [comment]
> > which still opens the browser for the SSO
> That is intentional. Does it still try and callback to `vector://` though or `riot://`

It calls `vector://`

**Comment by t3chguy** [comment]
Weird. means that somehow https://github.com/vector-im/riot-web/blob/c1da3bf5378692154e77bdd104034d31572bd72e/src/vector/platform/ElectronPlatform.js#L426 is not being executed

**Comment by paulmelis** [comment]
Ok, if I manually copy the URL behind the "Sign in with single sign-on" button (i.e. right click, copy link address) and change the 2 occurrences of `vector` to `riot` it still fails, as the `riot://` URL type is not registered

**Comment by t3chguy** [comment]
Something is certainly strange with your build:
https://github.com/vector-im/riot-web/blob/bb6afd7c3040b7d6ac7e82ce14f2d6d064abfd18/electron_app/src/protocol.js#L30-L35

**Comment by t3chguy** [comment]
also I don't know why there'd be two instances of `vector`, there should just be one in the protocol of the callback url

**Comment by paulmelis** [comment]
Sorry, I misread the hostname 'vector' as the 2nd instance.

**Comment by paulmelis** [comment]
> Something is certainly strange with your build:
> 
> https://github.com/vector-im/riot-web/blob/bb6afd7c3040b7d6ac7e82ce14f2d6d064abfd18/electron_app/src/protocol.js#L30-L35

There's no `else` branch, could that be taken for some reason, leaving the protocol info in an incorrect state?

**Comment by paulmelis** [comment]
I can try a fully manual build and see what that produces

**Comment by t3chguy** [comment]
> There's no else branch, could that be taken for some reason, leaving the protocol info in an incorrect state?

`isPackaged` is only false if running electron directly, which would be entirely incompatible with protocol handlers except on Windows

**Comment by paulmelis** [comment]
Right, so building manually based on the readme produces a version that indeed calls back to a `riot://` URL from the SSO pages. I guess the [Arch official build script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/riot) is doing some non-standard things. 

What would be the final step to get the `riot://` URL working?

**Comment by t3chguy** [comment]
> electron7 /usr/lib/riot/app.asar "$@"

Ah so indeed this build does call electron directly which is totally incompatible with protocol handling :/

**Comment by t3chguy** [comment]
You could try https://superuser.com/a/309343

**Comment by paulmelis** [comment]
But how to pass the URL back to the `riot-desktop` application from the `.desktop` file? It doesn't seem to accept a relevant command-line option. Or at least, it doesn't report one.

**Comment by t3chguy** [comment]
`MimeType=x-scheme-handler/riot;` claims it'll pass `riot://` urls to this `.desktop` file which will launch electron with the right args, no?

**Comment by paulmelis** [comment]
Yes, but the arguments are to be specified in the `.desktop` file and that's the point. Can I just pass the URL as a single argument to `riot-desktop`? I'm certain I tried that at some point during this issue and found that it didn't work. To be concrete, your linked example contains

```
Exec=emacsclient %u
```
where `%u` is the URL. 

Oh, and I can't figure out how to run the built binary with arguments as the relevant readme section (https://github.com/vector-im/riot-web/tree/release-v1.5.15#running-as-a-desktop-app) shows `yarn electron` as a build command, but it actually runs the application as well and I don't immediately see the command it's executing (so I know what to put in the `.desktop` file). The instructions on `electron-builder` also don't help, as there's no `node_modules/.bin/build` command in source dir I can use to build a package (nor does `electron-builder` seem to be a command).

**Comment by paulmelis** [comment]
Okay, I guess I need a `yarn add electron-builder --dev` to add the relevant `electron-builder` stuff, will see how much further I get

**Comment by paulmelis** [comment]
Alrighty! So managed to build a packaged version (executable is apparently `node_modules/.bin/electron-builder` and not `node_modules/.bin/build` as mentioned in the readme). Passing the SSO URL through the command-line gives me a logged in chat room!

**Comment by t3chguy** [comment]
So yes the riot:// url should be passed as an argument

**Comment by t3chguy** [comment]
Indeed `node_modules/.bin/build -l --x64` is wrong in the README, I won't bother updating it as the switch to riot-desktop repo with its different build instructions is due on Thursday.

**Comment by qubidt** [comment]
Note for others facing this issue on Arch: it's due to the `.desktop` file included in the `riot-desktop` Arch package. The issue is being tracked in [this Arch bug report](https://bugs.archlinux.org/task/66324?project=5&string=riot-desktop). The fixed `.desktop` file in the bug patch (with the things @t3chguy suggested) solves the issue, just waiting on the package to be updated, now.

**Comment by t3chguy** [comment]
Good to hear there is a resolution in the works

**Comment by t3chguy** [comment]
Linked issue https://bugs.archlinux.org/task/66324?project=5&string=riot-desktop was closed on the 6th of May.
