### ISSUE TITLE
Wait until current session is verified before sending room key requests

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12843]
At the moment, we seem to send megolm / room key requests to other sessions immediately after login / initial sync, but because the new session is not yet verified, they are all ignored by existing devices.

We should wait until the current device is verified before blasting room key requests.

**Comment by foldleft** [comment]
how does this interact with https://github.com/vector-im/riot-web/issues/11908 / don't we get keys from SSSS now?

**Comment by foldleft** [comment]
Aight, I've clarified with Ryan. There's a flow where users can't get keys from SSSS or key backup, such as if they don't trust the server. This is to support those cases.

**Comment by jryans** [comment]
An alternate approach to this situation and possibly others might be to block initial sync until after the new device is verified (as suggested in https://github.com/vector-im/riot-web/issues/12953), but that might cause other regressions, and I am a bit hesitant to make that change this close to release.

**Comment by foldleft** [comment]
yeah, that seems imprudent. as far as i can tell the system for requesting keys from another device does this in a timed loop so i'm not sure why things don't magically sync on their own, to be honest. more reading to do

**Comment by jryans** [comment]
It could be the case that they _do_ indeed fix themselves the next we go around that timed loop... 

So far, we're reacting to the fact that existing devices are hit with a bunch of key requests that will definitely fail (because the new device is unverified), so it at least results in lots of logging noise and things looking broken even though it might fix itself eventually.

I wonder how long does it take before we try again (assuming we do indeed try again after some time)?

An ideal fix might be to give the app layer more control over when the key requests begin (so we can try it into verification status). If that's too complex, perhaps we can adjust the existing timing rules to make it less of an issue.
