### ISSUE TITLE
Scrolling message panel requires focus

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12841]
In MacOS. I can scroll most apps / web pages by hovering over the window and using the mouse wheel / trackpad scroll without having to click the window to focus it. This doesn't work in Riot: I would expect it to scroll the message view in this case. Applies to both the web and electron version.

**Comment by bwindels** [comment]
Fairly sure this is the `AutoHideScrollbar`, which has `overflow: hidden` unless you hover over it. I'm afraid it will either be auto-hiding scrollbars or this.

**Comment by bwindels** [comment]
Or... could we style the scrollbars to be transparent perhaps when not hovering? :smiling_imp:

**Comment by t3chguy** [comment]
Hover events work for me in Windows at least even when the window doesn't have focus

**Comment by bwindels** [comment]
omg! `scrollbar-color: transparent transparent;` works, and also allows us to get rid of the margin-right hack I think!
