### ISSUE TITLE
If you switch away from the room where you're verifying someone in the RightPanel you may never be able to finish the verification.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12859]
* I tried to verify Amandine
 * She clicked on the toast and went to a [random DM](https://github.com/vector-im/riot-web/issues/12850) where she started the interactive verification dance in the RightPanel.
 * She then switched room, and lost the RightPanel
 * She then went to my MemberInfo, hoping to get back into the verification.
 * Instead, because her device thinks she's already verified me, she had no way to resume it.

Additionally, if she hadn't verified me, she would have had to have (unintuitively) hit the 'verify' button again to resume the verification - shouldn't it take you straight back in when you open MemberInfo?

**Comment by bwindels** [comment]
The issue seems to be that her device thought she had already verified you. I'm not sure how that would happen. @AmandineLP When you went again to your member info, all Matthew's session were green and there was no verify button?  I asked Amandine to rageshake.

> Additionally, if she hadn't verified me, she would have had to have (unintuitively) hit the 'verify' button again to resume the verification - shouldn't it take you straight back in when you open MemberInfo?

Hmm, could do, that would prevent you though from looking at the member info while a verification request is ongoing. If we add this, we should definitely pair it with fixing #12860

**Comment by ara4n** [comment]
> The issue seems to be that her device thought she had already verified you. I'm not sure how that would happen. @AmandineLP When you went again to your member info, all Matthew's session were green and there was no verify button? I asked Amandine to rageshake.

Yes. Because she'd already cross-signed me, i assume?  But i'd presumably lost my cross-signing state at some point.

**Comment by bwindels** [comment]
But if she had already cross-signed you, why (and how) did you send here a request in the first place? Did you send a request to a device she hadn't cross-signed herself yet? Or did she cross-sign you but you hadn't cross-signed her yet?

**Comment by ara4n** [comment]
> But if she had already cross-signed you, why (and how) did you send her a request in the first place? 

Because my client was not showing her as cross-signed.

> Did you send a request to a device she hadn't cross-signed herself yet? Or did she cross-sign you but you hadn't cross-signed her yet?

The latter, i think.

**Comment by bwindels** [comment]
I see. So this can be summarized as "If you send a verification request to somebody who has already verified you, they accept, but then navigate elsewhere, then they have no way to get back to the request as the member info won't show the verify button anymore"

So yeah, in this case, we should either we still show the verify button, or show the encryption panel straight away when clicking the member in the member list. I'd personally prefer the former, as it will still allow you to see the member info while a request is ongoing. Wdyt?

**Comment by bwindels** [comment]
Had a call with Nad and he agreed to go straight to the verification request if you click a member in the memberlist with whom you have an ongoing verification request.
