### ISSUE TITLE
DMs used for key verification are picked very unintuitively.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12850]
I'd expect it to a) pick the most recent DM i've used with someone (typically the one I'm currently in when I'm initiating the verification), b) prefer encrypted ones to unencrypted ones.  Instead, it seems the pseudo-canonical DM it picks is random at best.

**Comment by ara4n** [comment]
This is is particularly bad when it picks an unencrypted one so you then can't re-initiate verification, given MemberInfos in non-e2e rooms inexplicably stop you from verifying people.

**Comment by turt2live** [comment]
it's "the first one" where the source is the ordering of keys of the `m.direct` json object in account data. True canonical DMs also fixes this.

**Comment by ara4n** [comment]
right, agreed that canonical DMs fix this, but can we pick the most recent one instead rather than the oldest one, which is most likely to be abandoned?

**Comment by ara4n** [comment]
THANK YOU!! :D
