### ISSUE TITLE
Tried to self-cross-sign using legacy verif; failed with sig error

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12858]
Having failed to cross-sign my new RiotX from Riot/Web develop due to https://github.com/vector-im/riot-web/issues/12681, I tried to do it via legacy verification.  This also failed, with a surprisingly overdetailed error message:

<img width="386" alt="Screenshot 2020-03-24 at 23 29 49" src="https://user-images.githubusercontent.com/1294269/77486466-bce31500-6e27-11ea-8fb2-a35e73cce779.png">

https://github.com/matrix-org/riot-web-rageshakes/issues/2448

**Comment by ara4n** [comment]
(I did, in theory, upgrade to symmetric SSSS earlier today, in case it's relevant)

**Comment by bwindels** [comment]
This appears to be because RiotX rotated its device key.

**Comment by jryans** [comment]
I'll track this for now, but it seems likely it will be resolved by Android side.

**Comment by jryans** [comment]
I'm assuming this key rotation issue is fixed by https://github.com/vector-im/riotX-android/pull/1172

**Comment by jryans** [comment]
I'm assuming this key rotation issue is fixed by https://github.com/vector-im/riotX-android/pull/1172. As for too much detail in the error dialog, I filed https://github.com/vector-im/riot-web/issues/12942.
