### ISSUE TITLE
"Unverified session" toast is still confusingly named.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12856]
It's very unclear what "unverified session" means.  Specifically, it's unclear whether it's talking about your session or someone else's.

RiotX is much better, calling it "New sign in", which is much less ambiguous.

**Comment by bwindels** [comment]
This is inconsistent in Figma between desktop and mobile designs, but I'm tempted to just change it to what mobile has.

**Comment by ara4n** [comment]
"Unverified login" might be enough or 'Unverified account login", given it's clear contextually that the login will be yours.

**Comment by nadonomy** [comment]
I've updated the copy in [Figma](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=6%3A1695) to "Unknown login. Was this you?". In context it's the least ambiguous and seems to correct the right sense of urgency.
