### ISSUE TITLE
prompt for secret storage key immediately after creation

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12867]
i created a new account and set up secret storage with a key. i was immediately prompted to enter it again to unlock secret storage.  nb this will likely go away on the completion of https://github.com/vector-im/riot-web/issues/12704 since that does caching, so this ticket is mostly likely to entail double-checking that actually happened

**Comment by foldleft** [comment]
possibly related to https://github.com/vector-im/riot-web/issues/12892

**Comment by bwindels** [comment]
@BillCarsonFr hit this, additionally also saw a "Verify this session" toast after login.
