### ISSUE TITLE
Keyshare request modal is stuck on top of the verif modal it triggers.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12872]
I got a keyshare request on Riot/Web, which tried to prompt me to self-verify the device (RiotX).  I hit the verify button, and it brought up an inaccessible verification dialog hidden underneath (presumably having failed to close the keyshare req dialog):

<img width="795" alt="Screenshot 2020-03-24 at 21 54 06" src="https://user-images.githubusercontent.com/1294269/77542534-3c133000-6e9e-11ea-8c69-4405de76a6de.png">

**Hm, i just noticed this was on Riot 1.5.8 - so this may be irrelevant**

**Comment by jryans** [comment]
This should be gone now, and it's reported as older version, so let's assume this is fixed.
