### ISSUE TITLE
Icons in the upper-right corner become unresponsive

### ISSUE THREAD

**Issue by kuba-orlik** [vector-im/riot-web#12870]
### Description

More than once have I and other users from my team experienced an issue where icons in the top right corner become unresponsive:

![image](https://user-images.githubusercontent.com/2697916/77538988-8691ae00-6e98-11ea-8332-1813cfd62d98.png)
 
When the issue occurs clicking the icons has no effect, and so far rebooting my pc seems to be the only solution.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Manjaro Linux, Ubuntu
- **Version**: 1.5.12

**Comment by t3chguy** [comment]
This is already fixed https://github.com/matrix-org/matrix-react-sdk/pull/4238
