### ISSUE TITLE
Option to enlarge the widget area

### ISSUE THREAD

**Issue by kuba-orlik** [vector-im/riot-web#12874]
**Is your suggestion related to a problem? Please describe.**

When using a Jitsi widget, it's too small to handle certain parts of it's UI and it's hard to see others. I can open it in a new tab, but that would mean having to disconnect form the conference for a while.

**Describe the solution you'd like**
A button that would toggle between standard and larger area for the widget in chat view.

**Describe alternatives you've considered**
A draggable frame that would let users adjust the widget to any height

**Comment by benparsons** [comment]
![Screenshot 2020-03-25 at 12 16 32](https://user-images.githubusercontent.com/1197991/77558300-af26a180-6eb2-11ea-93ff-ad5e5a144c53.png)

This has been reported to me by others - the "Full Screen" menu option is actually at the top here, highlighted above "Share a YouTube video". The settings screen is also too compact to be usable.

**Comment by rkfg** [comment]
As a temporary workaround you can switch to fullscreen by pressing S on the keyboard. Caveats: if you have multiple keyboard layouts you have to switch to English first; the input focus should be on the Jitsi frame so you need to click the widget. Indeed, those frames should be adjustable and draggable, they're put side by side as of now and it's not convenient if you have more than one widget in a room. Jitsi window is certainly designed for larger spaces than that.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/6785
