### ISSUE TITLE
URL is missing parts

### ISSUE THREAD

**Issue by almereyda** [vector-im/riot-web#12880]
### Description

When entering a link in Markdown format to a relative URL in Riot, like

    [/#/home](/#/home)

Riot Web throws

    Error: "URL is missing parts"

in the console and stops rendering the whole channel. Below it says

```
The above error occured while React was rendering the following components: 
    in TextualBody
    in MessageEvent
    in div
    in div
    in EventTile
    in li
    in ol
    in div
    in div
    in div
    in s
    in ScrollPanel
    in Xt
    in TimelinePanel
    in div
    in div
    in div
    in s
    in Cc
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in Cc
    in MatrixChat bundle.js:2:752069
```
Then it displays a message asking me to post this issue here and delete the application cache.

Deleting the offensive message, i.e. with Fractal, allowed to view that channel again.

### Steps to reproduce

Create a Markdown Link as of above.

### Version information

web ffd155a6aa7d-react-519c7f9ef039-js-6a7a25508189

This does not happen in Riot Desktop

For the web app:

- **Browser**: Firefox 73.0.1
- **OS**: Fedora 30
- **URL**: https://riot.allmende.io

**Comment by t3chguy** [comment]
Hmm, I cannot reproduce:


![image](https://user-images.githubusercontent.com/2403652/77594145-a8695000-6eed-11ea-84fe-d3cf58c5e516.png)

**Comment by almereyda** [comment]
Thanks for the quick fix.
