### ISSUE TITLE
Can't connect to integration manager

### ISSUE THREAD

**Issue by TuringMachinegun** [vector-im/riot-web#12886]
### Description

When trying to access the integration manager, I get the following message:
"cannot connect to integration manager. The integration manager is offline or it cannot reach your homeserver."

I tried turning federation on (it was turned off initially), but it didn't change the outcome.
I'm using modular.im for hosting.

### Steps to reproduce

- click on integrations manager icon

Log: sent    

![image](https://user-images.githubusercontent.com/8633845/77641315-26fcd680-6f5c-11ea-9de9-df4fc5572ff8.png)

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**:  Firefox 74.0
- **OS**: Ubuntu
- **Version**: c4f3d39d4229-react-c4f3d39d4229-js-c4f3d39d4229

For the desktop app:

- **OS**:  Ubuntu
- **Version**: 1.5.13

**Comment by turt2live** [comment]
Please contact Modular support for problems with your host.

**Comment by Per0x** [comment]
I have the same problem on my dedicated server (not Modular) with last update.

**Comment by turt2live** [comment]
@Per0x visit #riot-web:matrix.org for support.

**Comment by SebastGG** [comment]
Me too, can some give me hint how to solve this?

**Comment by plamenh** [comment]
Us too for some time now.

**Comment by JuanSeBestia** [comment]
+1

**Comment by plamenh** [comment]
I solved this bu making sure the correct ports are working on our matrix server. You can google ‘test mattix federation’ to use an online tool that tella you if there are any problems.
