### ISSUE TITLE
Allow 'no bots' setting

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#12888]
The entrance rules for rooms should have a 'no bots' option.  This could be linked to a captcha challenge, or whatever test the room admins deem appropriate.  It should still be possible for the admins to invite bots.
A warning should be given that determined users can circumvent this and have a bot enter, and that no security for public rooms is possible - but it would remove the large majority of unwanted leakage.

**Comment by jryans** [comment]
This seems very much like a spec feature request, as I don't see how Riot could implement this unilaterally. 

Please file this idea in https://github.com/matrix-org/matrix-doc.
