### ISSUE TITLE
Version bar soft crash

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12889]
Looks like the NewVersionBar has caused a soft crash somehow (on develop, so probably something to do with the github changelog magic).

**Comment by dbkr** [comment]
https://github.com/matrix-org/riot-web-rageshakes/issues/2454

**Comment by babolivier** [comment]
I've been hit by this three times in the past 36h, and apart for the third one it's really annoying as getting back into Riot takes ages on a somewhat big account (for some reason the third one was a bit swifter to reload).

**Comment by bwindels** [comment]
Might have had something to do with https://github.com/vector-im/riot-web/issues/13557, also we moved the NewVersionBar to a toast and haven't had any reports since, so closing this.
