### ISSUE TITLE
Can we avoid the SSO login flow making you click a 'log in with SSO' button?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12883]
We have a complaint from a new SSO user that it's clunky to force the user to click login from the home page... and then click 'log in with SSO' when it's the only option available. Why not jump straight to logging in with SSO?

**Comment by t3chguy** [comment]
Certain browser configs don't allow for js to launch a new tab if not at the direct result of a user action, if its asyncy based on loading API from Synapse it may get rejected

**Comment by babolivier** [comment]
Technically the user has already made an action since the button only shows up if they click on "Login" (or "Register" which redirects to the login view) fwiw (though I don't know enough about Riot and React to know if this is relevant).

**Comment by t3chguy** [comment]
Sure, but then that action is interrupted with a call to Synapse to ask for login flows, then a few ticks later we have a response from Synapse and handle it

**Comment by t3chguy** [comment]
but if this still automatically works for 99% of users thats probably acceptable

**Comment by t3chguy** [comment]
So I tried this and without some polish it looks a little strange as the browser keeps riot rendered until it has IAM: https://github.com/matrix-org/matrix-react-sdk/pull/4279

**Comment by t3chguy** [comment]
> when it's the only option available.

Also worth keeping in mind, riot-web only supports showing you one flow.

https://github.com/matrix-org/matrix-react-sdk/blob/c41b39488b46ac772d3b0c0ba5c9c3b060e495e6/src/components/structures/auth/Login.js#L443-L445

**Comment by babolivier** [comment]
> We could show a spinner but then if the user's browser blocked the new-tab we won't know and the user won't be able to trigger it manually.

Maybe show a spinner with a link below that says "Click here if you're not redirected automatically"?

**Comment by babolivier** [comment]
(What the hell happened?)

**Comment by t3chguy** [comment]
> Why not jump straight to logging in with SSO?

Additionally, how would such a user switch HSes in this scenario if the default HS is SSO but they want to log in elsewhere?

**Comment by artonge** [comment]
Hi,

I am interested in his feature. Here are my thoughts.

- In some cases going straight to SSO flow would be wanted for Riot instances dedicated to a home server that only allows SSO connection. So @t3chguy case should not happen. It would be the admin decision to force the users using his instance of Riot to only log in using SSO. But it is possible to not go straight to SSO flow on a predefined URL like riot.im/app/login?direct=true. Nextcloud is using this logic.

- I don't think SSO flow requires opening a new tab. At least for SAML. Again with the Nextcloud example, they achieve automatic SSO flow for SAML. But maybe the redirection is initiated by the server using the Location header.

**Comment by t3chguy** [comment]
So for a changeset without refactoring the entire Login path, I added support for welcome.html to access $riot:ssoUrl and $riot:casUrl so that the Login buttons there can link straight to the SSO flow rather than going through `/#/login/`
