### ISSUE TITLE
Right sidebar freezes up after accessing community room

### ISSUE THREAD

**Issue by lempamo** [vector-im/riot-web#12882]
Soon after I enter a community room in both the desktop and web versions of Riot (the latter accessed in Firefox), the buttons to change what the right sidebar is viewing as well as the right sidebar itself completely stop working. I saw no errors raised within the web console that related to this, but I did see a notice about an attribute being deprecated. That notice didn't pop up every time I tried to interact with the right sidebar, though.

I'm using the latest versions of Riot Desktop, Windows 10, and Firefox.

**Comment by t3chguy** [comment]
This is already fixed for next release.
