### ISSUE TITLE
Sometimes see 2 passphrase dialogs when singing in to an existing account with cross-signing enabled (and without having upgraded to symmetric 4S?)

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12892]

**Comment by foldleft** [comment]
possibly related to https://github.com/vector-im/riot-web/issues/12867

**Comment by dbkr** [comment]
Tried signing into an account with crypto just set up and it's OK - haven't yet tried pre symmetric upgrade but I'm not sure how much we care about that given I think everyone that had asymmetric SSSS has probably upgraded by now.

**Comment by jryans** [comment]
Agreed, let's consider this probably fixed until we get a new report.
