### ISSUE TITLE
Key backup upload can still fail because is_verified is missing on some sessions

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12901]
I'm seeing constant `500` responses on `PUT https://matrix.org/_matrix/client/unstable/room_keys/keys?version=1`. Other users are reporting the same on their homeservers (https://github.com/matrix-org/riot-web-rageshakes/issues/2457, also @babolivier )

One possible cause is that riot is not sending `is_verified` on every session. I'm seeing it on most sessions in the request body, but it is missing on a few.

We fixed a very similar issue a while back, see https://github.com/matrix-org/matrix-js-sdk/pull/1246/

Also see discussion at https://matrix.to/#/!WCHwNGGsrVwPeRtAnq:matrix.org/$1585308918512037WKxZx:matrix.org?via=matrix.org&via=vector.modular.im&via=jayfoobar-staging.modular.im

**Comment by babolivier** [comment]
Synapse stacktraces definitely say that it's because of a lack of `is_verified`:
```
Mar 27 11:20:10 errol synapse[5205]: Traceback (most recent call last):
Mar 27 11:20:10 errol synapse[5205]:   File "/home/synapse/synapse/synapse/http/server.py", line 78, in wrapped_request_handler
Mar 27 11:20:10 errol synapse[5205]:     await h(self, request)
Mar 27 11:20:10 errol synapse[5205]:   File "/home/synapse/synapse/synapse/http/server.py", line 331, in _async_render
Mar 27 11:20:10 errol synapse[5205]:     callback_return = await callback_return
Mar 27 11:20:10 errol synapse[5205]:   File "/home/synapse/synapse/synapse/rest/client/v2_alpha/room_keys.py", line 134, in on_PUT
Mar 27 11:20:10 errol synapse[5205]:     ret = await self.e2e_room_keys_handler.upload_room_keys(user_id, version, body)
Mar 27 11:20:10 errol synapse[5205]:   File "/home/synapse/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Mar 27 11:20:10 errol synapse[5205]:     result = g.send(result)
Mar 27 11:20:10 errol synapse[5205]:   File "/home/synapse/synapse/synapse/handlers/e2e_room_keys.py", line 210, in upload_room_keys
Mar 27 11:20:10 errol synapse[5205]:     if not isinstance(room_key["is_verified"], bool):
Mar 27 11:20:10 errol synapse[5205]: KeyError: 'is_verified'
```

**Comment by babolivier** [comment]
Also, as @bwindels pointed out on Matrix, [the WIP spec](https://11379-24998719-gh.circle-artifacts.com/0/root/project/scripts/gen/client_server/unstable.html#put-matrix-client-r0-room-keys-keys-roomid-sessionid) says this parameter is required.

**Comment by jryans** [comment]
A bit puzzled that this is still happening, but anyway, I'll sort it out. 😅

**Comment by non-Jedi** [comment]
This is expected to be fixed on riot.im/develop, right? I'm still seeing "signature upload failed" with `M_INVALID_SIGNATURE` when trying to verify between devices. I sent a couple of rageshakes to #12790 thinking that was the issue but @bwindels thought it was this one instead. Do I need to open a new issue for what I'm seeing? If so, is it against riot-web or synapse?

```
{
  "@adam:thebeckmeyers.xyz": {
    "UCEFGLRWSN": {
      "status": 400,
      "errcode": "M_INVALID_SIGNATURE",
      "message": "400: Invalid signature"
    }
  }
}
```

**Comment by jryans** [comment]
This issue is about errors of the form:

```
Key backup request failed Internal server error
```

which @bwindels [did appear to see](https://github.com/vector-im/riot-web/issues/12790#issuecomment-604932451) in your logs. This kind of error should be fixed.

The one you are mentioning here about "signature upload failed" is something different and is not related to key backup.

It might be similar to some other open issues, but just to be sure we fully capture your situation, I recommend a new issue (with rageshakes if possible) for now and we can de-duplicate later as needed.

**Comment by non-Jedi** [comment]
Will do. Thanks. :)
