### ISSUE TITLE
riot-web 1.5.14-rc.1 sends e2e keys without the is_verified attribute

### ISSUE THREAD

**Issue by darix** [vector-im/riot-web#12918]
### Description

riot-web 1.5.14-rc.1 sends e2e keys without the is_verified attribute
1.5.13 seems to work properly

### Steps to reproduce

- install rc1
- reload tab

browser google chrome (latest) on linux

https://github.com/matrix-org/synapse/issues/7165

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/1289#pullrequestreview-382904582
