### ISSUE TITLE
if /goto is a thing, put it in the slash command autocompleter

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12919]

**Comment by tulir** [comment]
`/goto` is just an alias for `/join` and aliases aren't autocompleted. There's another issue for making `/goto` work differently: #10128

**Comment by jryans** [comment]
Couldn't we add aliases to the autocomplete and help though...?

**Comment by tulir** [comment]
The autocomplete thing might get a lot of unnecessary entries if aliases were separate, but maybe they can autocomplete the same entry instead of being separate? (i.e. typing `/goto` will suggest `/join`)

**Comment by t3chguy** [comment]
Hopefully not like 
![image](https://user-images.githubusercontent.com/2403652/77909487-5aee3980-7285-11ea-9c8a-4f03b00e3bd7.png)
