### ISSUE TITLE
hide jitsi conference title

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#12917]
### Description

jitsi conferences display the (seemingly randomly generated) title, which looks ugly and confusing:
![image](https://user-images.githubusercontent.com/1029578/77833709-a8608e80-713f-11ea-887f-f70d1955eb66.png)

### Steps to reproduce

- start a jitsi conference
- look at the top of the widget when you hover over it

I'd expect it to not display some random strings :)

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.12

**Comment by turt2live** [comment]
This is fixed in the next version (the title isn't hidden, but they are made of words).

**Comment by lub** [comment]
I don't think using words instead of the room id really helps with looking random and confusing, but that's only my opinion
