### ISSUE TITLE
Giving he roomadmins the power to delete rooms, not just to the server admins

### ISSUE THREAD

**Issue by sk-alexis** [vector-im/riot-web#12928]
Problem: When a room is no longer needed or wanted there is no simple way to remove the room.  Need an easy way to delete the room. So people dont need to kick every room member one by one and change status to invite only just before leaving the room yourself.(leaving the room member-less, without the ability for nobody to join, basically a room lost in time in limbo) 

Solution: Provide in Admin Settings the option to delete a room.
Also for new users this is more intuitive dynamic.

**Comment by sk-alexis** [comment]
This a feauture requested by another comunitie member, im just doing a favor and reposting the problem. Cheers.

**Comment by t3chguy** [comment]
Closing in favour of spec bug https://github.com/matrix-org/matrix-doc/issues/1882
