### ISSUE TITLE
should cmd-left/right square bracket mimic browser back/fwd buttons in desktop?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12920]

**Comment by t3chguy** [comment]
Isn't this already taken by text navigation?

![image](https://user-images.githubusercontent.com/2403652/77850902-7bf35380-71cd-11ea-890b-b3b129648828.png)

**Comment by aaronraimist** [comment]
Browsers use ⌘[ and ⌘] for back/fwd. Seems like it would make sense to use those.

**Comment by t3chguy** [comment]
@aaronraimist I think something went wrong with your input:
![image](https://user-images.githubusercontent.com/2403652/79044940-2fae0780-7c00-11ea-9460-7cfa90098821.png)

**Comment by aaronraimist** [comment]
No that's what I wrote

Command + either square bracket

**Comment by t3chguy** [comment]
oh 🤦

**Comment by t3chguy** [comment]
Okay so yeah, matching Slack here.

Back:
+ Mac: Cmd + `[`
+ Windows/Linux: Alt + LEFT_ARROW
Forward:
+ Mac: Cmd + `]`
+ Windows/Linux: Alt + RIGHT_ARROW
