### ISSUE TITLE
Your Riot is misconfigured

### ISSUE THREAD

**Issue by lijianl** [vector-im/riot-web#12927]
I am using to visit [developer room on Riot](https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org) but has an error to open.

then I clicked browser and download desktop from [Riot](https://about.riot.im/) to test, they all show "Your Riot is misconfigured, Invalid homeserver discovery response", could you help me with this? I am visiting the page from china via VPN, Does this has any effect?

For the web app:

For the desktop app:

**Comment by lijianl** [comment]
The desktop version is 1.5.13

**Comment by dbkr** [comment]
Yes, it sounds like Riot can't contact the default homeserver: matrix.org. Closing this as this isn't specifically a bug (although the fact that it fails in this way is).

**Comment by dbkr** [comment]
https://github.com/vector-im/riot-web/issues/11154 is the bug for this behaviour
