### ISSUE TITLE
Starting a Jitsi conference shows 404 Not Found

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#12929]
### Description

After clicking on "Join conference" it just shows "404 Not Found you can create a new conversation here"

![image](https://user-images.githubusercontent.com/1029578/77931966-29896400-72ad-11ea-8e8d-7185d246146f.png)

It tries to reach an URL like https://jitsi.riot.im/JitsiConference_SatisfyingNeedyParty, but it seems the Jitsi instance doesn't support underscores.

I've tested it with a config.json from https://riot.im/develop/config.json (because I normally use that one) and without, but no difference.

### Steps to reproduce

- Click on the phone/camera to add the Jitsi widget
- Click on the green button
- get an error message

I'd expect it to join a conference instead of displaying an error

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.5.14

**Comment by turt2live** [comment]
We've fixed this for our side, but we'll have to remove the underscore eventually as it seems like a common thing to forget to configure on custom jitsi installs (there's also zero reason why there's an underscore anyways).

De-firing as we don't need a special release.

**Comment by eNirantar** [comment]
The same error i am getting 
https://vebinarr.website/
Please check how can i solve

**Comment by t3chguy** [comment]
This looks like your Jitsi Meet Instance is misconfigured. as even clicking Go on https://vebinarr.website/ doesn't work. You'd have to reach out to Jitsi support.

**Comment by eNirantar** [comment]
> This looks like your Jitsi Meet Instance is misconfigured. as even clicking Go on https://vebinarr.website/ doesn't work. You'd have to reach out to Jitsi support.

can you please suggest what issue can be.. i have messaged to support to but did not get any reply yet.

**Comment by eNirantar** [comment]
> This looks like your Jitsi Meet Instance is misconfigured. as even clicking Go on https://vebinarr.website/ doesn't work. You'd have to reach out to Jitsi support.

I have tried to solve issues and reconfigured it but having same issue

**Comment by eNirantar** [comment]
When i use this url it shows something 
https://vebinarr.website/index.html?room=UrbanFlowsSighNext

**Comment by t3chguy** [comment]
That isn't the format Riot requires. It requires links like http://meet.jit.si/RoomName to function.

**Comment by eNirantar** [comment]
> That isn't the format Riot requires. It requires links like http://meet.jit.si/RoomName to function.

yes i understand.. could you suggest what issue can be or there is something that is done via htaccess or what issue can be at my end

**Comment by eNirantar** [comment]
> That isn't the format Riot requires. It requires links like http://meet.jit.si/RoomName to function.

yes i understand.. could you suggest what issue can be or there is something that is done via htaccess or what issue can be at my end

**Comment by t3chguy** [comment]
This is the wrong repo for such queries.
