### ISSUE TITLE
Widgets shouldn't be expanded by default

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12921]
Signing into an existing account on a new browser, and all of my widgets are expanded, when they should be minimised by default:

<img width="1436" alt="Screenshot 2020-03-29 at 16 15 17" src="https://user-images.githubusercontent.com/4626865/77852921-19a05000-71d9-11ea-9a24-ba8b834640c4.png">

**Comment by jryans** [comment]
I haven't really formed an opinion yet, but my first thought is: if they are minimised by default, will people even realise they are there at all...?

**Comment by nadonomy** [comment]
> I haven't really formed an opinion yet, but my first thought is: if they are minimised by default, will people even realise they are there at all...?

If it's important to them they'll expand them. If not, then even more rationale for them to not be as present. Right now they're just a big annoying huge distraction from users achieving their primary goals in the first time user experience.

We should also anticipate widget discoverability to improve when we implement room profiles in the right panel.

**Comment by DJCrashdummy** [comment]
i see both arguments and they have both their pros & cons, but **as soon as i minimized a widget it should stay minimized for me** no matter which client i use.

newly integrated widgets or existing widgets for new users can or ideally even should be expanded to get some attention, but IMHO that's the only case for now to automatically expand a widget. - *i have a bunch of rooms with widgets and login with riot-web very often... and then it gets quickly tedious having to minimize the widget at every room before i can go on as i'm used to.*
