### ISSUE TITLE
New SSO flow doesn't work with non-default profile

### ISSUE THREAD

**Issue by SISheogorath** [vector-im/riot-web#12932]
### Description

When using a custom profile (`/path/to/riot --profile test`) the SSO redirect with the `riot://` isn't aware of the profile and therefore Riot ends up messing with the default profile instead of the one you use for starting the SSO process.

### Steps to reproduce

- Run Riot with a non-default profile (`/path/to/riot --profile test`)
- Try to log in via SSO
- Follow the `riot://`-URL in order to complete the SSO login

Describe how what happens differs from what you expected.

Riot opens with the default profile and even causes a "successful" login in the wrong profile which leads to re-syncs, changed E2E keys and everything you expect from a new login for the default profile instead of the non-default one.

### Version information

- **Platform**: desktop
- **OS**: Fedora Linux with Riot in Flatpak from Flathub
- **Version**: v1.5.14

**Comment by t3chguy** [comment]
Protocol handlers (except in Windows) cannot provide command line arguments, so there isn't really anything which can be done here

**Comment by SISheogorath** [comment]
I think the redirect URL itself could contain this information as a parameter. When riot opens/handles the URL it could use the same logic as for the CLI argument. This could solve this issue. This is already done with the homeserver and should also be doable with the profile.

**Comment by t3chguy** [comment]
Potentially. Will see how electron likes it.
