### ISSUE TITLE
Unverified encrypted calls should not open warning dialogs

### ISSUE THREAD

**Issue by notramo** [vector-im/riot-web#12935]
### Description
If Alice knows Bob's voice very vell, they could verify in-band. It shouldn't place any dialogs about unverified session, but should allow to place the call and show a warning when the call is active. This would the best approach to new users because it wouldn't pop up any dialogs. They don't want dialogs asking them what to do with verification when they don't even know what this encryption thing is. They are scared out by these dialogs. New users is mostly invited by someone who is more familiar with Matrix. If the call is established, they could ask the experienced user what that warning means.
It should default to emoji verification because if they are calling, that mostly means that they are away from each other, so they can't start QR code verification.

![image](https://user-images.githubusercontent.com/26059643/77956937-007bca00-72d3-11ea-8891-35eed5e2f0a6.png)
(Sorry for the green shield, I was too lazy to change it to red, but it should be.)

**Comment by dbkr** [comment]
I think this is talking about the pre-cross-signing UI so I think this is effectively fixed with cross-signing enabled, if I've understood correctly.
