### ISSUE TITLE
Missing Spell Check 

### ISSUE THREAD

**Issue by NHAS** [vector-im/riot-web#12938]
### Description

Spell check is non-functional on the desktop version of riot.im

### Steps to reproduce

- Type misspelled word in input bar
- Notice it isnt highlighted as misspelled 

Logs being sent: no

![image](https://user-images.githubusercontent.com/6820641/77968579-2f7e5400-7344-11ea-9ab9-9e396e20b548.png)

### Extra information

From searching I've found that this feature was added and is present in `https://github.com/vector-im/riot-desktop/blob/2571c26372d0ff7f5bae88c03cdfea3ca0227209/src/electron-main.js#L298`

This seems to be caused by the fact that the UI is trying to send the call to set language and thus start off all the spell check stuff. But the code isnt present. 

![image](https://user-images.githubusercontent.com/6820641/77968750-91d75480-7344-11ea-873c-8c0802155113.png)

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**:  macOS
- **Version**: 1.5.13

**Comment by t3chguy** [comment]
Spell check will be available in version 1.6 which will be the first release from riot-desktop repo. This release is weeks away.
