### ISSUE TITLE
turning on SSSS on a virgin existing account didn't also set up cross-signing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12949]
I took an existing account on 1.5.14 which has never done SSSS nor cross-signing (afaik).  I hit the bootstrap button in settings to enable SSSS, which worked... but didn't set up cross-signing keys.  I then reopened settings, and it let me hit it again, this time to set up cross-signing keys

**Comment by jryans** [comment]
Unsure how easy it will be to repro, but we should at least try and see.

**Comment by jryans** [comment]
* Created account on /app (no cross-signing)
* Switched to /develop while logged in for cross-signing flows
* Skipped the encryption toast and went to Settings instead to bootstrap
* Both 4S and cross-signing keys created ✅

I am not sure how to investigate further without a log or more details, so I'll close this for now. If it happens again, please file again with a rageshake log.
