### ISSUE TITLE
Upgrade toast for pre-cross-signing account did not appear

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12948]
on riot 1.5.14 (sorry, not develop) with cross-signing enabled in labs, i was already logged into a basic account with no e2e backup or cross-signing setup. I then connected to an existed e2e backup, but it didn't prompt me to set up cross-signing.  I then refreshed and i didn't see an 'upgrade encryption' bootstrap toast.

**Comment by jryans** [comment]
Not sure why the upgrade toast did not appear, should at least investigate to find the cause.

**Comment by jryans** [comment]
As an attempt to reproduce, I did the following:

* Created a new test account on /app (where cross-signing is disabled)
* Enabled key backup alone on /app
  * Noticed that the new account has 2 sessions even though I did not add an email
* Signed out and signed in on /app to be disconnected from the key backup
* Changed to /develop to receive cross-signing enabled flows while already logged in
* Encryption upgrade available toast appeared on first load ✅
* Ignoring the toast and instead connecting only to the existing key backup works, but no further toasts are sent
* On reload, I get another encryption upgrade toast ✅

We did tweak the toasts a bit last week, so perhaps that has resolved this issue. Marking fixed for now, but please reopen or file a new issue if it comes back.

**Comment by jryans** [comment]
>     * Noticed that the new account has 2 sessions even though I did not add an email

This bit is tracked as https://github.com/vector-im/riot-web/issues/13040
