### ISSUE TITLE
expand collapse are not clickable anymore when read receipts are disabled

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#12944]
### Description

Some events can be collapsed (e.g. join/part/kick). The little button with 'expand' or 'collapse' cannot be clicked anymore. It seems mx_EventTile_info is layered over mx_eventListSummary_toggle (the actual button). When I manually hide mx_eventTile_info I can click the button.

![image](https://user-images.githubusercontent.com/1029578/78018666-97d23300-734e-11ea-9032-0bea4fef3362.png)

### Steps to reproduce

- Find some collapsed events (e.g. https://matrix.to/#/!jxlRxnrZCsjpjDubDX:matrix.org/$_pefrLQS9eEvkEVkQxwbSW_ibZUHomGPqGjDbBAdUsQ?via=matrix.org&via=privacytools.io&via=feneas.org)
- Try to expand or collapse

The cursor just stays default and when you click on it nothing happens. I'd expect the cursor to become this hand thingy and on click actually collapse or expand the events.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.5.14

**Comment by t3chguy** [comment]
Are you sure this is on 1.5.14? I cannot reproduce on riot.im/app but can on /develop as I believe this regressed by https://github.com/matrix-org/matrix-react-sdk/pull/4295 which is unreleased.

**Comment by t3chguy** [comment]
Actually, this is caused by hidden read receipts

**Comment by lub** [comment]
You are right, it only happens with hidden read receipts. And yes I'm sure it's 1.5.14, although I use the config.json form /develop for labs

![image](https://user-images.githubusercontent.com/1029578/78025606-9d357a80-735a-11ea-924d-be9f89f25647.png)
