### ISSUE TITLE
After entering megolm passphrase to sidestep self-verif at login, self-verification still popped up.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12954]
I just tried to self-verify on login (on develop).  The self-verification didn't complete however, so I entered my passphrase instead.  After having entered it, it dumped me back into a self-verification flow modal saying "Session verified"... but still prompting me to verify my session via emoji(?).

<img width="710" alt="Screenshot 2020-03-31 at 14 42 21" src="https://user-images.githubusercontent.com/1294269/78033135-e1764a00-735d-11ea-93c5-32fd1d09ab88.png">

**Comment by foldleft** [comment]
I'm having some trouble reproing this one

**Comment by jryans** [comment]
@foldleft Maybe it's some kind of race...? I've never seen this come up so far in local testing, so it might be something specific to @ara4n's large account?

I'd suggest time boxing your investigation to try any remaining repro attempts, and if that fails, let's close this for now until there's more detail / more reports.

**Comment by foldleft** [comment]
I've tried aborting the flow from the already-logged-in side at every stage and cannot repro.

I've updated my homeserver and everything, still no repro.

Possibly this is an interaction when one side doesn't have the flag on?  Otherwise yep I'll close as unreproduceable.
