### ISSUE TITLE
Setting up E2EE on a new login doesn't block initial sync

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12953]
Resulting in the initial sync exploding in attempts to decrypt undecryptable messages, rather than just waiting until E2EE has been set up.

**Comment by ara4n** [comment]
I think this basically breaks self-verification, because the self-verif to-device msgs get blocked behind the explosion of initialsync traffic

**Comment by jryans** [comment]
Hmm, I have definitely seen self-verif work fine, so perhaps it only "breaks" for large accounts then...?

I am a bit worried we might rely on some client APIs that expect an operational sync to be running, so I am wary of changing this just before release...

**Comment by jryans** [comment]
In https://github.com/vector-im/riot-web/issues/13098, we took a decision that we should gate on initial sync before complete security, so this may be resolved soonish.

**Comment by ara4n** [comment]
this is now resolved, i think?
