### ISSUE TITLE
When self-verifying a new login, it says "Waiting for Matthew to accept..." rather than "...you to accept..."

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12952]
~It's also strange that the "Unverified login, was it you?" prompts with "Review?" rather than "Authorise" or "Verify" or something.  We're not really 'reviewing' the login, are we?~

**Comment by jryans** [comment]
> It's also strange that the "Unverified login, was it you?" prompts with "Review?" rather than "Authorise" or "Verify" or something. We're not really 'reviewing' the login, are we?

@nadonomy is reviewing copy such as this, so I'll ignore this part for this issue.

**Comment by jryans** [comment]
This is effectively a duplicate of https://github.com/vector-im/riot-web/issues/12725.
