### ISSUE TITLE
The verification process is cumbersome and redundant

### ISSUE THREAD

**Issue by 35609902357** [vector-im/riot-web#12964]
When a new device is added, and it's verified by another device, all the devices already verified should automatically flag the new device as verified and viceversa. This should work also for a new device added by a contact, if it's verified by him then it should be verified for me too.

This would act like a "verified zone" or "trust zone" if you will, instead of manually verify all devices of all contacts every single time. If a contact verifies a new device it enters the "trust zone" and it's verified for all his and my devices.

I failed to get people on board many times because of this. The cumbersome verification process scared many users away from the application because they can't be bothered to verify every single device or session. Some people was scared about logging out and back in again.

This should be the default method and a setting should be added to restore the current one if a more strict security is needed

**Comment by turt2live** [comment]
This is https://github.com/vector-im/riot-web/issues/2714, which is an active stream of work.
