### ISSUE TITLE
After logging in on a new device, my passphrase is rejected when trying to connect to online backup.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12966]
After managing to log in on a new device this flow (https://github.com/vector-im/riot-web/issues/12954), i noticed that online backup didn't seem to be working (UISIs everywhere for past devices).  I tried to 'connect to backup' in settings, but it rejects my passphrase - despite it being the same one i used to verify myself at login.

**Comment by ara4n** [comment]
apparently #12970

**Comment by turt2live** [comment]
I've also been inflicted with this.

**Comment by jryans** [comment]
@ara4n @turt2live Can you please retest here now that the backup key format work has landed?

**Comment by turt2live** [comment]
Do we have to relog or just try restoring from backup?

**Comment by jryans** [comment]
> Do we have to relog or just try restoring from backup?

Just trying to restore in the same session _should_ work, but if not, trying a fresh login would also be good information to have.

**Comment by jryans** [comment]
The advanced view in Security settings for cross-signing has also been updated to report on the key format, so that may be useful to copy before and / or after.

**Comment by turt2live** [comment]
Before:
![image](https://user-images.githubusercontent.com/1190097/79242497-a716ad80-7e31-11ea-8813-1636457b67d1.png)

Stared at this for minutes:
![image](https://user-images.githubusercontent.com/1190097/79242600-c4e41280-7e31-11ea-9121-41e40f2c68dd.png)

Gave up and submitted this comment.

Is the loading screen expected and should it be taking a while? Wallclock time says 5 minutes, no obvious errors in logs. Will rageshake.

**Comment by turt2live** [comment]
Of course just as I submit the comment, it magically restored keys. It didn't ask me for a passphrase though, which is worrying.

**Comment by turt2live** [comment]
After:
![image](https://user-images.githubusercontent.com/1190097/79243163-7d11bb00-7e32-11ea-82b8-bdcbee096651.png)

**Comment by jryans** [comment]
> It didn't ask me for a passphrase though, which is worrying.

According to the before info, you have the backup private key cached locally so this is expected.

**Comment by jryans** [comment]
> Is the loading screen expected and should it be taking a while? Wallclock time says 5 minutes, no obvious errors in logs. Will rageshake.

Hmm, I would have expected to see more progress detail than just a spinner. I have extracted this part out to https://github.com/vector-im/riot-web/issues/13167.

Great to hear that the core issue of restoring appears fixed, so let's close this issue. 🎉
