### ISSUE TITLE
Modals for cross-signing your own device don't match designs

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12961]
@nadonomy to fill in the details here

**Comment by jryans** [comment]
I am assuming this is at least partly about https://github.com/vector-im/riot-web/issues/12725, but perhaps there are additional things to do as well.

**Comment by bwindels** [comment]
The only designs I am aware of fwiw are here, https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=0%3A1

**Comment by nadonomy** [comment]
@bwindels & I had a call on this today to clarify the updates needed, for brevity we just recorded notes in this google doc:

https://docs.google.com/document/d/1JxxjthxipQ0XUn8mIHY-UMKniwVaayyqX8ZoT5flSdQ/edit
