### ISSUE TITLE
Message stays at bottom of timeline

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#12969]
See https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$SNQOYYpr5KTvIi5nweoQPYz_-Wq_iJKyBR7OZBMjMSw?via=matrix.org&via=privacytools.io&via=mozilla.org and https://matrix.to/#/!jIkxpZVHbomQzbUTua:matrix.org/$s_kH7e4MX8_mG4oTf1pHmladWI5BbKAeavO64iHYzdQ?via=matrix.org&via=privacytools.io&via=1312.media

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/10032

**Comment by Biep** [comment]
This one has the same problem:
https://matrix.to/#/!jIkxpZVHbomQzbUTua:matrix.org/$adot7JtGQkQk14XsghRUZK-jUvyD2ZKkTdXpUy_EogM?via=matrix.org&via=privacytools.io&via=1312.media
