### ISSUE TITLE
Need to find a way to expose non-federatable room configuration knob

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1296]
Which either means bringing back 'create room' (ugh), or making unfederatable more flexible (yay)!

**Comment by richvdh** [comment]
related: https://matrix.org/jira/browse/SPEC-454

**Comment by uhoreg** [comment]
@ara4n the "Create Room" now has a checkbox for making a room non-federatable, so I guess this one can be closed now?

**Comment by richvdh** [comment]
yup let's close this. thanks!
