### ISSUE TITLE
Riot generates Jitsi conference name with a wrong format

### ISSUE THREAD

**Issue by ptrkbmn** [vector-im/riot-web#12978]
### Description

It is not possible to create and join a Jitsi conference within the Jitsi widget.

The problem is that the conference name which is generated by Riot. It contains an underscore which is not supported by Jitsi.

### Steps to reproduce

- Open a room and invite at least 3 people
- Click on the phone button in the bottom right
- Click on Join Conference in the Jitsi widget

The Jitsi server responds with an 404 error. With the default Jitsi settings in the config.json-file you see a link that redirects you to the front page of the Jitsi server, which is where you can enter a custom name for the conference. Every other member in that room has to type in the exact same conference name to join the conference.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.5.14

**Comment by t3chguy** [comment]
This is already fixed for the next release which is due shortly.
