### ISSUE TITLE
Let images be pasted from the clipboard

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1297]

**Comment by SijmenSchoon** [comment]
Found a [StackOverflow question and answer](http://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c) on this, I'll be experimenting with this

**Comment by ara4n** [comment]
fixed by #605 - thanks @SijmenSchoon!

**Comment by gavofyork** [comment]
#605 appears to have nothing to do with this and this feature doesn't seem to have made it into the currently available web version on riot.im

what's going on?

**Comment by ara4n** [comment]
hey @gavofyork; matrix-org/matrix-react-sdk#605 is the PR which fixes it. it's available on the develop branch (riot.im/develop) if you enable the experimental rich text editor. develop will be released to stable next week. unfortunately the rich text editor still needs some fixes before it's enabled by default however.
