### ISSUE TITLE
roomlist filter isn't recalculated when you unselect a community

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12977]

**Comment by t3chguy** [comment]
I cannot reproduce this, any chance of a gif?

![rlf](https://user-images.githubusercontent.com/2403652/78133247-00d0ae00-7416-11ea-8514-e3c3351291fd.gif)

**Comment by t3chguy** [comment]
Presumably will be fixed by the new room list which rewrites this entire part of the app

**Comment by t3chguy** [comment]
(Assuming solved, re-open if not)

**Comment by turt2live** [comment]
(had better be solved, the filtering logic is 5x more intelligent now)
