### ISSUE TITLE
Clarification about jitsi.html in 1.5.15

### ISSUE THREAD

**Issue by darix** [vector-im/riot-web#12989]
the release notes for 1.5.15 say that jitsi.html should not longer be used. but the tarball with the 
precompiled version still ships with a jitsi.html and the file seems unmodified according to

https://github.com/vector-im/riot-web/compare/v1.5.14...v1.5.15

the diff also shows no deletion of the file.

should a packager include the jitsi.html still? or should it be dropped from the package?

**Comment by t3chguy** [comment]
The new one is fine and required for Jitsi confs, the old one is not.

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/compare/v1.5.14...v1.5.15#diff-74410ccaa6a36e48b022603397fed2a6
https://github.com/vector-im/riot-web/compare/v1.5.14...v1.5.15#diff-1536b2b9d1674954ff8d3ae5d7edd952

are the applicable modifications

**Comment by turt2live** [comment]
The changelog is trying to get you to remove vulnerable versions, not to delete the thing. 

For support questions, please use #riot-web:matrix.org

**Comment by darix** [comment]
so it was just the code in jitsi.ts that needed fixing + the new include? but not the jitsi.html?

then the wording in the release notes is a bit confusing.

**Comment by t3chguy** [comment]
Those two are used to build the output jitsi.html in webpack.

**Comment by t3chguy** [comment]
if you compare the two jitsi.html's in the release tarballs you will see it has changed.
