### ISSUE TITLE
Template variables for display name and such don't apply on widgets anymore?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12985]

**Comment by turt2live** [comment]
specifically custom widgets, eg: `/addwidget https://example.org?name=$matrix_display_name`

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/5c2841323e58d5b22f488a3fc47607b9387a8463/src/components/views/elements/AppTile.js#L141 malforms `$matrix_display_name` into `%24matrix_display_name`
