### ISSUE TITLE
"Server error" when trying to invite a user to a room via /invite

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12983]
### Description

![image](https://user-images.githubusercontent.com/1342360/78152059-39ca4c00-7431-11ea-8245-539d618b73ba.png)

I'm getting the following popup when I type `/invite @bla:example.com`. It seems that trying to invite any invalid MXID immediately pops up this error, real user or not.

Looking at network traffic there aren't any invite requests going to the homeserver, which makes me believe this isn't actually a server-related issue.

### Steps to reproduce

- Invite someone into a room with `/invite`
- Receive this error message

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
hmm, this is confirmed and probably affects /app too.

Likely regressed in @t3chguy's SlashCommands rework.

**Comment by t3chguy** [comment]
indeed, turns out the ` = []` wasn't useless
