### ISSUE TITLE
Self-verify is incredibly slow.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12981]
Just spent 2 minutes or so staring at this.  Eventually it arrived (and then the actual emoji comparison was fairly instant).

<img width="626" alt="Screenshot 2020-04-01 at 14 18 26" src="https://user-images.githubusercontent.com/1294269/78142031-4300ec00-7424-11ea-9ae8-adcae3a31e5e.png">
<img width="778" alt="Screenshot 2020-04-01 at 14 18 37" src="https://user-images.githubusercontent.com/1294269/78142037-45634600-7424-11ea-8dda-1584c4e0d2ae.png">

**Comment by ara4n** [comment]
might be related to https://github.com/vector-im/riot-web/issues/12953

**Comment by jryans** [comment]
Hmm, unsure what the easy fix would here, as presumably we need an active, syncing client to get the verif messages...?

**Comment by ara4n** [comment]
my client was active and syncing.

**Comment by jryans** [comment]
To address this, we've agreed in the cross-signing meeting that we should move the initial sync spinner *before* the complete security flow.

We'll need to work with @nadonomy on design details such as should the spinner be on a while background (which is how initial sync spinners currently work) or on the glossy auth flow background now that it will appear between two stages of UX on outside the app.

**Comment by dbkr** [comment]
Linked above is a first cut putting the spinner in the same container ad the Complete Security stuff.

**Comment by jryans** [comment]
@t3chguy is going to take over the initial sync spinner work here. Latest designs take a different approach than @dbkr's PR above, so unclear whether it's better to build on that or start over.

The latest designs are version A in https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=4277%3A25011, which replaces buttons with spinner & 'Signing In...', then once we log in & start syncing, replace 'Signing In...' with 'Syncing...' and add the text below. 

See also [discussion on Matrix](https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$1EXgGvAOAZ7T4fzAEraQGQmClFlAZKINxY4dlXqmhw4?via=matrix.org&via=vector.modular.im&via=dbkr.me).
