### ISSUE TITLE
I'm not allowed to edit my last message

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-web#12999]
## Description

The web client prompts me to file an issue when I try to edit my last sent message

### Steps to reproduce

- send a message in an encrypted room
- select the message
- try to edit it

### Version information

- web (Chrome, MacOS, riot.im/develop)

**Comment by t3chguy** [comment]
Should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4331/commits/8e405dda2e5ec77f9063ced1abd0154eab96bad4
