### ISSUE TITLE
Pressing the “up” key in the composer sometimes crashes the room

### ISSUE THREAD

**Issue by RAOF** [vector-im/riot-web#12997]
### Description

I pressed the “up” key in the composer hoping to select the previous message for editing. Instead, the room history blanked out and the “it's crashed, please submit logs” message came up.

### Steps to reproduce

- Select the #freenode_#ubuntu-desktop:matrix.org room
- Press the up key with the composer selected.

This reliably occurs, but is bizarrely room-specific. It happens in some, but not all bridged Freenode rooms, and in some, but not all, of my bridged Signal rooms, and some, but not all, of my Matrix DMs. If a room does it once then it seems it will reliably do it; likewise, if a room doesn't do it then it will reliably not do it.

Log: pending

### Version information

- **Platform**: Web
- **Browser**: Firefox, nightly: 76.0a1 (2020-04-01) 
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4331/commits/8e405dda2e5ec77f9063ced1abd0154eab96bad4
