### ISSUE TITLE
generated turn server credentials contain full mxid

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-web#13003]
### Description

When placing a 1:1 voip call the generated turn server credentials contain full mxid. This is an issue because plain turn sends everything in cleartext, and thus all hops in between can sniff out the mxid.

### Steps to reproduce

-Place a VOIP call in a 1:1 room

### Suggested solution

I'd suggest creating a random username, or possibly a hash of the mxid.

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/riot-web/issues/11489
