### ISSUE TITLE
Up arrow in composer crashes

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13001]
Similar to https://github.com/vector-im/riot-web/issues/12997

Looks like this one is due to Travis' componentWillMount/componentDidMount replacement, in that componentDidMount is too late to set the model in EditMessageComposer.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/4331/commits/8e405dda2e5ec77f9063ced1abd0154eab96bad4 claims to fix it

**Comment by dbkr** [comment]
Empirically it does not

**Comment by turt2live** [comment]
looks like there were two failure modes, https://github.com/matrix-org/matrix-react-sdk/commit/8e405dda2e5ec77f9063ced1abd0154eab96bad4 fixed one of them and https://github.com/matrix-org/matrix-react-sdk/pull/4333 fixed the other. Unclear what causes either, but at least they're fixed
