### ISSUE TITLE
Open user settings keyboard shortcut don't work on Mac

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#13017]
### Description

In macOS, the default keyboard shortcut to open settings for an application is CMD+ ,
So this overrides Riot Web. I'm guessing this applies to the Mac Desktop app as well?

### Steps to reproduce

- Buy a Mac
- Open any browser
- Log in to Riot Web
- Press CMD + ,
- Enjoy the preferences window of your web browser

Logs being sent: no

### Version information

For the web app:

- **Browser**: Firefox 74.0 (64-bit), Chromium 82.0.4083.0 (Developer Build) (64-bit), Safari 13.0.5 (15608.5.11)
- **OS**: macOS 10.15.3 (19D76)
- **URL**: riot.im/develop / riot.im/app / somewhere else. Probably all Riot Webs

**Comment by Twi1ightSparkle** [comment]
CMD + ` too (Toggle the top left menu). This switch between windows of the same app in macOS

**Comment by t3chguy** [comment]
> Enjoy the preferences window of your web browser

Overwriting this in-browser was chosen against. Do other webapps (github, Gmail, etc) overwrite it? It works fine in the electron client.

**Comment by t3chguy** [comment]
If you look at the Keyboard Shortcuts page, it only lists Cmd + , on the desktop app. Not in browser.

**Comment by Twi1ightSparkle** [comment]
> Overwriting this in-browser was chosen against. Do other webapps (github, Gmail, etc) overwrite it? It works fine in the electron client.

I'm glad it doesn't overwrite, but it should be another key imo

> If you look at the Keyboard Shortcuts page, it only lists Cmd + , on the desktop app. Not in browser.

I guess my browser is special then. /app has the same ftr
![Screen_Shot_2020-04-03_at_12_51_28_PM](https://user-images.githubusercontent.com/19155609/78358000-5dfd6880-75aa-11ea-9a3d-c6e20ce5e1c1.png)

**Comment by t3chguy** [comment]
Ah, that is a bug. https://github.com/vector-im/riot-web/blob/3d266cb23746d852445e06d3b4c923bed0ee83f5/src/vector/platform/ElectronPlatform.js#L40 should not be getting executed. Will resolve this today.

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/12645 covers the ability to change shortcuts

**Comment by t3chguy** [comment]
Going to close in favour of the more generic #12645 which would be able to do this
