### ISSUE TITLE
Tried to edit message, Riot Desktop crashed

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#13015]
### Description

Was in a room and after typing some messages, wanted to fix one, so pressed "up" arrow key. "Something went wrong!" screen popped up.

### Steps to reproduce

(not sure if reproducable)

- Type messages in a room (encrypted, if that matters)
- Try to edit by pressing "up" arrow key
 * update: seems to happen in every room for me at the moment, including when using the "edit" function

Will upload debug logs.

### Version information

- **Platform**: desktop, nightly

For the desktop app:

- **OS**: Ubuntu 19.10
- **Version**: nightly 2020040201

**Comment by jryans** [comment]
A fix landed yesterday, so this should be fixed in today's nightly build.

**Comment by jryans** [comment]
@jaywink Today's nightly should now be published, does that fix it for you?

**Comment by jaywink** [comment]
> @jaywink Today's nightly should now be published, does that fix it for you?

It does indeed, thanks! <3
