### ISSUE TITLE
Right panel for your own profile lets you verify the device you're currently on

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13011]
this feels counterproductive. The good news is it just spins 'waiting for partner'.

**Comment by bwindels** [comment]
I assume this is when you haven't gone through complete security yet

**Comment by turt2live** [comment]
yes, sorry. I dismissed the toast after some failures verifying.

**Comment by bwindels** [comment]
I actually get the "4S-enter-passphrase" dialog :thinking:

**Comment by jryans** [comment]
Hmm, curious... Like @bwindels, I also get the 4S bootstrap flow and no verification when trying to replicate.

@turt2live, are you still able to hit this with a new account? Please describe details if so.

**Comment by turt2live** [comment]
Looks like I can't reproduce this now, but I swear I wasn't lying ._.
