### ISSUE TITLE
Consider not using a spinner on the 'complete security' prompt

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13010]
I was staring at this for about 5 minutes before I realized I had to do something:
![image](https://user-images.githubusercontent.com/1190097/78283884-bca7e100-74db-11ea-9a5d-5bd8a85cb9d2.png)

The spinner made it feel like it was getting set up in the background and was just taking longer than usual. Maybe replace it with a button to start verification?

**Comment by turt2live** [comment]
cc @nadonomy

**Comment by uhoreg** [comment]
I had a similar experience.  The spinner drew my attention, making me skip the sentence above.  Also, the "use your recovery key or passphrase" doesn't jump out as something actionable.  Maybe it would be better as a button?

**Comment by ara4n** [comment]
this bit me too.

**Comment by jryans** [comment]
For now, I'll track this for after release.

**Comment by turt2live** [comment]
@jryans is it possible to get this to be a pre-release fix? I'm counting 4 people in the company who all got bitten by it, which is certainly a red flag for when we release this.

**Comment by jryans** [comment]
I defer to @nadonomy, as I don't have a strong opinion. We'll want to have designs if we make a change here.

**Comment by nadonomy** [comment]
Happy to iterate on the designs Monday, hopefully we have time to action changes before launch.

**Comment by ara4n** [comment]
i really really think this has to be before release - it's literally the first thing a user sees when logging in for the first time with cross-signing enabled, and the UX is baffling.  All it needs is wording tweaks.  

I think replacing "Waiting..." with "Please verify this login from an existing session?" might be enough?  

Then we don't even need the "Open an existing session..." text - it can just be a spinner, and a CTA.

**Comment by nadonomy** [comment]
@jryans Having looked at this in detail, I've added an update to Figma in a separate page here:

https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=4269%3A25112

Basically we should:

- [ ] Remove the spinner (as we train users to think that's waiting for the server, normally)
- [ ] Update the body copy
- [ ] Use micro copy in place of where the primary action normally lives in a modal

And we should reduce confusion easily for now. I'll also round back to this in more detail across all platforms post launch.
