### ISSUE TITLE
While trying to verify my own device from the right panel I'm told verification is not possible

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13012]
![image](https://user-images.githubusercontent.com/1190097/78290307-caac3080-74e0-11ea-98cb-6a29bec32079.png)

When in fact I'm staring at this on the device I'm verifying:
![image](https://user-images.githubusercontent.com/1190097/78290332-d7308900-74e0-11ea-99ca-35e155d27573.png)

Hitting 'continue' makes the right panel jump to life

**Comment by foldleft** [comment]
What's the action on this –– fixing this for old-style verification? Getting the device cross-signed?  Not allowing the user to use this flow for their own devices?

**Comment by turt2live** [comment]
I think it just needs to be more aware of states and needs a loading icon.

**Comment by bwindels** [comment]
This seems to work for me... is there anything different about your case than in the GIF below?

![legacy-sas](https://user-images.githubusercontent.com/274386/78888942-3a2a9e80-7a52-11ea-9cb7-a6c0df138c9f.gif)

**Comment by turt2live** [comment]
Probably got fixed between discovering, reporting, and investigating. I can't reproduce it now :(
