### ISSUE TITLE
SSO for cross-signing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13042]

**Comment by turt2live** [comment]
@vector-im/design this will need designs for what it should look like during the bootstrap, key backup, and other related flows where a password would normally be asked.

**Comment by jryans** [comment]
@turt2live I guess I had assumed SSO UI auth would just "work" wherever UI auth is used, but maybe that's not what happens? Does it needed to be customised for each use site?

**Comment by turt2live** [comment]
It does work, but the default UI is a bit minimalistic (title and a button). Some copy at least would be good.

**Comment by nadonomy** [comment]
@turt2live I don't have the full context on when this would be prompted precisely in the user journey, but in general can we follow the standard we set [here](https://github.com/vector-im/riot-web/issues/12692#issuecomment-602748255) for contextual SSO prompts?

In this instance I'm not sure we'd need the 'after auth', so instead just:

### Use Single Sign On to continue
To continue, use Single Sign On to prove your identity.
[Cancel] **[Single Sign On]**

The body copy could do with being more specific which I can add if you let me know exactly which screens this is prompted for between.

**Comment by jryans** [comment]
Since it at least works even if a bit confusing, tracking for after release.

**Comment by turt2live** [comment]
thanks @nadonomy - will try and get this in for release, but things aren't looking good on my side for that.

**Comment by turt2live** [comment]
@nadonomy we'd need the after-auth because of how the auth steps work. Following the other dialogs, presumably something like this is good enough?

## Confirm encryption set up

Click the button below to confirm setting up encryption.

----

The screen shows up after this one:
![image](https://user-images.githubusercontent.com/1190097/81223518-57944f00-8fa3-11ea-9639-75ca63b6efb8.png)
