### ISSUE TITLE
Ability to configure private rooms as E2EE at creation time.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13065]
DMs are E2EE by default \o/

However, when creating a private room, it would be really nice to have a toggle (defaulting to 'on') for E2EE.  There should probably be some microcopy to remind users that most bots/bridges won't work in E2EE private rooms however.

**Comment by t3chguy** [comment]
https://www.figma.com/file/j2H4Py956itzt8wEZ73ACG/Create-room-modal?node-id=0%3A1
