### ISSUE TITLE
Option to change the registration link on the welcome page.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [vector-im/riot-web#13069]
**Is your suggestion related to a problem? Please describe.**

I am using a different registration page [matrix-registration](https://github.com/ZerataX/matrix-registration) and have riot-web registration disabled. Therefore, the create account button on the welcome page links to an incorrect page(the riot-web registration, not my different one). 

**Describe the solution you'd like**

The ability to change where the create account button on the welcome page links to via a configuration file.

**Describe alternatives you've considered**

An alternative would be to implement something that is registration upon invitation. This could be accomplished via a token like the  [matrix-registration](https://github.com/ZerataX/matrix-registration), or some other system.

**Additional context**

The reason that I am using a different registration method is that the current built-in registration options are not ideal for my use case.
1. With no registration, then account credentials would have to be manually generated and communicated securely.
2. With public registration, then anyone can join.

**Comment by t3chguy** [comment]
Surely this should be something controlled by the homeserver, otherwise someone using riot-desktop or something wouldn't be led to the same registration link? It can probably be done already using the fallback registration mechanisms.

**Comment by turt2live** [comment]
Isn't this page replaceable with some config options?

**Comment by t3chguy** [comment]
The welcome page is, but the login page would still have a `Create an account` button which wouldn't work for them

**Comment by TheCakeIsNaOH** [comment]
> It can probably be done already using the fallback registration mechanisms.

If someone could point me to documentation on how to do this, that would be great.
