### ISSUE TITLE
Changing integration server does not change m.widgets

### ISSUE THREAD

**Issue by PolynomialDivision** [vector-im/riot-web#13071]
### Description
Changing integration server needs manually deleting `m.widgets` json with `/devtools`.

### Steps to reproduce
1. Setup own integration server
2. Change the integration server in Riot
3. Try Sticker App: You will get a `403 - Permission denied`

To solve the issue:
1. Type in `/devtools`
2. Explore Account Data
3. `m.widgets`
4. Empty to empty-json `{ }`

## What I would expect

Changing the integration server should remove all `vector.scalar` and `vector.im` related stuff.
No userinteraktion with `/devtools` should be required.

For the desktop app:
- **OS**: Manjaro
- **Version**: 1.5.12

**Comment by turt2live** [comment]
We don't support changing the integration manager anymore - closing.
