### ISSUE TITLE
subsequent image previews/thumbnails have different size

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13072]
### Description

Thumbnails have a different size depending on whether they are the first message or a a subsequent message (the black bars are all the same image, but the previews are displayed differently):

![image](https://user-images.githubusercontent.com/1029578/78772745-857d7800-7992-11ea-8d74-3f98c6224e8f.png)
![image](https://user-images.githubusercontent.com/1029578/78772777-8f9f7680-7992-11ea-822e-d17a4c820593.png)

### Steps to reproduce

- choose an image, which is wider than the timeline in riot (so it has to get downsized)
- choose a room where you have not written anything for a while, so your nick/avatar gets displayed
- send the image
- directly afterwards send the image another time

The two images will have a different size. I'd expect them to be the same size.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.5.15

**Comment by t3chguy** [comment]
This is related to hidden read receipts
