### ISSUE TITLE
Disable (“grey out”) jitsi/integrations/widgets buttons for unprivileged users …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13087]
I think it would be an improvement to disable (“grey out”) jitsi/integrations/widgets buttons for unprivileged users (per room) …

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/78876774-c08db300-7a47-11ea-8e0e-928a6a739663.png)

They are greyed out. If you mean greying out the button:
![image](https://user-images.githubusercontent.com/2403652/78876799-c8e5ee00-7a47-11ea-83dd-97e01bffc88a.png)

then that doesn't make sense as you can have personal things like stickerpicker widgets in there too.

**Comment by fooness** [comment]
What about the jitsi buttons/icons? They don’t make sense if you don’t have permissions to start a call in the room you’re currently in?

<img width="139" alt="Screenshot 2020-04-09 at 10 53 30" src="https://user-images.githubusercontent.com/11408027/78876967-70ffb500-7a50-11ea-8d81-b26cb6aa3248.png">

**Comment by t3chguy** [comment]
Thats https://github.com/vector-im/riot-web/issues/13118

**Comment by turt2live** [comment]
It sounds like this is asking for https://github.com/vector-im/riot-web/issues/13118 not the integration manager. The integration manager evidently already does the right thing.
