### ISSUE TITLE
infinite spinner during login

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#13094]
after login, I got a dialog saying "open another session and verify this one"

I had riotx open, and waited for ages. Nothing happened. I had to give up.

nothing in the dialog suggested I needed the other session to be any particular client software or client.

**Comment by ara4n** [comment]
i had this too at https://github.com/vector-im/riot-web/issues/12981

**Comment by jryans** [comment]
This does seem the same as #12981, so let's track it there.
