### ISSUE TITLE
"Invalid homeserver response" during login

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#13097]
got the above error during login. From the console, it looks like it's complaining about an "invalid /versions response". I have no idea why, the versions response looks perfectly good to me.

**Comment by richvdh** [comment]
![13097](https://user-images.githubusercontent.com/1389908/78887246-6e548e00-7a57-11ea-8485-2d85263a4ad4.gif)

**Comment by ara4n** [comment]
sounds like https://github.com/vector-im/riot-web/issues/12694

**Comment by jryans** [comment]
Does not look particularly cross-signing specific, so seems separate from https://github.com/vector-im/riot-web/issues/12694.

**Comment by turt2live** [comment]
Entering your mxid does another round of discovery, and http://sw1v.org/.well-known/matrix/client 404's

This is working as intended.

**Comment by richvdh** [comment]
to be clear, the error came up after I clicked on "sign in". I'm surprised that does well-known discovery, not least because I've just gone to the effort of typing in my HS URL?

**Comment by turt2live** [comment]
It does a quick validation of the .well-known after clicking too, particularly when entering a mxid as the username.
