### ISSUE TITLE
Self hosted jitsi in riot-desktop

### ISSUE THREAD

**Issue by rajil** [vector-im/riot-web#13091]
Hello,

I am using riot-desktop-1.5.15-1 from ArchLinux package and have a self hosted jitsi and synapse installed. The riot-desktop package has a config file in /etc/riot/config.json. I appended the jitsi stanza at the bootom of the file. However, riot-desktop is still using jitsi.riot.im instead of my own jitsi server.

What file needs to be modified for riot-desktop to use self hosted jitsi?

```
$cat /etc/riot/config.json
{
    "update_base_url": "https://packages.riot.im/desktop/update/",
    "default_server_name": "matrix.org",
    "brand": "Riot",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "hosting_signup_link": "https://modular.im/?utm_source=riot-web&utm_medium=web",
    "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
    "welcomeUserId": "@riot-bot:matrix.org",
    "roomDirectory": {
        "servers": [
            "matrix.org"
        ]
    },
    "piwik": {
        "url": "https://piwik.riot.im/",
        "siteId": 1,
        "policyUrl": "https://matrix.org/legal/riot-im-cookie-policy"
    },
    "phasedRollOut": {
        "feature_lazyloading": {
            "offset": 1539684000000,
            "period": 604800000
        }
    },
    "features": {
        "feature_lazyloading": "enable"
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    }
    "jitsi": { 
        "preferredDomain": "meet.mydomain.im" 
    } 
}
```

**Comment by t3chguy** [comment]
Instead of modifying config files which may get overwritten, follow the docs. https://github.com/vector-im/riot-web/blob/develop/docs/config.md#desktop-app-configuration
The app would need restarting (fully quitting not just closing to tray) and it only applies to you clicking the Video call button in group chats.

**Comment by t3chguy** [comment]
For further support queries use https://matrix.to/#/#riot-web:matrix.org

**Comment by rajil** [comment]
For anybody else reading this. The config.json does not exist out of the box in ~/.config/Riot. It needs to be created in the Riot folder.
