### ISSUE TITLE
"complete security" spinning for *ages* after login

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#13098]
after the whole "wait for another session" experience (#13094), there was a "complete security" dialog, with no other text but a spinner. I had to wait for about 30s for it to come up with "enter secret storage recovery key".

**Comment by richvdh** [comment]
![13098](https://user-images.githubusercontent.com/1389908/78887379-a956c180-7a57-11ea-92ea-76a081d1151b.gif)

**Comment by ara4n** [comment]
I had this too, and thought I filed it, but I can't find it.  Agreed that it's an awful awful experience.

**Comment by ara4n** [comment]
found it: https://github.com/vector-im/riot-web/issues/12981

**Comment by jryans** [comment]
There was a previous edition of this in https://github.com/vector-im/riot-web/issues/12426 where I assumed the problem was restoring all your keys. Let's keep this one separate, as it may be something different.

**Comment by richvdh** [comment]
I think the problem might be that the browser has queued up hundreds of keyshare requests, so other requests take ages?

**Comment by jryans** [comment]
To address this, we've agreed in the cross-signing meeting that we should move the initial sync spinner *before* the complete security flow.

We'll need to work with @nadonomy on design details such as should the spinner be on a while background (which is how initial sync spinners currently work) or on the glossy auth flow background now that it will appear between two stages of UX on outside the app.

**Comment by jryans** [comment]
This is closely related to https://github.com/vector-im/riot-web/issues/12981, where we'll be changing to move the initial sync before complete security, so let's see how it feels after that.

**Comment by richvdh** [comment]
this doesn't happen every time, btw. It felt like there was a race as to whether the necessary requests got out before all the keyshare requests or not.

**Comment by jryans** [comment]
We made some change to this process in https://github.com/vector-im/riot-web/issues/12981, so it would be good for @richvdh to re-test and update on how it feels for him now.

I hoping the fixes from https://github.com/vector-im/riot-web/issues/12981 are enough improvement that this no longer blocks release at least, so updating the phase.

**Comment by ara4n** [comment]
i retested and it's fixed.
