### ISSUE TITLE
Modify username color via e.g. `/color @user #rrggbb` …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13103]
It would be interesting to be able to modify the color of my own or someones else’s username via e.g. `/color #000000` or `/color @user #0000ff` …

**Comment by t3chguy** [comment]
Matrix has no concept of username colours. The colours riot shows are based on a hash of the user's MXID.

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/riot-web/issues/11816
