### ISSUE TITLE
e2e search failed: Sqlite database error: database is locked

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13108]
Searching an e2e room failed on nightly with error `Sqlite database error: database is locked`

**Comment by jryans** [comment]
@dbkr Any chance of a rageshake? Does it happen every time or intermittently?

**Comment by dbkr** [comment]
Intermittently. Unfortunately there was nothing useful in the logs because of https://github.com/matrix-org/matrix-react-sdk/pull/4372 - I will try again with tomorrow's nightly.

**Comment by poljar** [comment]
There was a Seshat release which tries to address this, relevant PR https://github.com/matrix-org/seshat/pull/58.

If someone experiences this again, especially in the form of database corrupted please reopen and we'll further tweak it.
