### ISSUE TITLE
Share Room COPY button’s icon is glitched …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13104]
Seems the icon is mis-aligned somewhat, see the right and bottom of the circle …

<img width="106" alt="Screenshot 2020-04-09 at 14 16 27" src="https://user-images.githubusercontent.com/11408027/78894136-d6fa3580-7a6c-11ea-9b96-183e7b04ec24.png">

Also, it would be a **massive improvement if the icon just had no background color at all**, i.e. the same background color as the complete box …

**Comment by dbkr** [comment]
I can't reproduce this on current /develop in chrome. Please don't delete and ignore the bug template: these can often be platform specific and we need to know what platform you're using.

**Comment by fooness** [comment]
Firefox `75.0` and Chromium `83.0.4099.0` on macOS `10.14.6` …

Same issue in `/develop` …

**Comment by turt2live** [comment]
It's ovwer-clipped. Using the dark theme makes it more obvious, and it's been like that for ages (pre-1.0).
