### ISSUE TITLE
Desktop app broken if account has cross-signing enabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13117]
```
Loaded cross-signing public keys from crypto store
bundle.js:2 Unable to initialise e2e Error: Tried to set cross-signing keys without a master key
    at c.setKeys (bundle.js:2)
    at bundle.js:2
    at IDBRequest.n.onsuccess (bundle.js:2)
```

This prevents most of the app from functioning, but it doesn't tell you that. Errors like #13116 happen.

**Comment by bwindels** [comment]
Can repro when:
 - session 1 reset cross-signing keys
 - refresh session 2 for same user
 - crash happens now

**Comment by turt2live** [comment]
@bwindels is it possible to squeeze the fix for this into 1.15.16 (due Tuesday)?

**Comment by jryans** [comment]
> @bwindels is it possible to squeeze the fix for this into 1.15.16 (due Tuesday)?

Is 1.5.15 currently affected by this?

**Comment by bwindels** [comment]
> > @bwindels is it possible to squeeze the fix for this into 1.15.16 (due Tuesday)?
> 
> Is 1.5.15 currently affected by this?

It should not as this regressed only in https://github.com/matrix-org/matrix-js-sdk/pull/1312, which is only on develop AFAIK.

**Comment by turt2live** [comment]
I had this on 1.5.15

**Comment by bwindels** [comment]
> I had this on 1.5.15

That's ... surprising. You were not using /develop then when reporting this?

**Comment by turt2live** [comment]
No, this was me using my matrix.org account on the current desktop release. It's all a bit moot as of tomorrow though.

**Comment by bwindels** [comment]
Ok, just wondering if the fix really fixes it then. I guess we would have noticed by now though.
