### ISSUE TITLE
Fix/Improve/Unify element alignment in room list …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13113]
Just a quick sketch …

The `Explore` button could also be aligned left, directly next to it (with some spacing) a `Filter` input field stretching out till the right border …

![riot](https://user-images.githubusercontent.com/11408027/78952979-a13e6680-7ad7-11ea-9dc8-37159aaa0fb4.gif)

<img width="358" alt="04" src="https://user-images.githubusercontent.com/11408027/78953360-e31bdc80-7ad8-11ea-86c8-55c64f436849.png">

PS: Borders around `Explore` and `Filter` are just to visualise the approximate size of the button area, they are not meant to be seen.

**Comment by turt2live** [comment]
should be better in the new room list
