### ISSUE TITLE
Cannot scroll room list with touch if mouse pointer is not hovering the room list

### ISSUE THREAD

**Issue by jens1o** [vector-im/riot-web#13112]
### Description

I cannot scroll the room list unless the mouse is hovering above the room list
![gif](https://user-images.githubusercontent.com/11234139/78941378-ddfa6580-7ab7-11ea-86ad-22ce08b70d2a.gif)

### Steps to reproduce

- Have a large enough selection of rooms so there is a scrollbar.
- Scroll the room list with your touchscreen (I'm using a Lenovo Thinkpad L390 Yoga), when the mouse pointer is not on the room list
=> you cannot scroll the room list

### Version information
- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox Nightly (77)
- **OS**: Windows
- **URL**: https://chat.mozilla.org

**Comment by t3chguy** [comment]
This is fixed in the next release which is due on Tuesday. Available at riot.im/staging
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4276/commits/0436507574704d700a73eccd0b82b9f7d0a6c02e

**Comment by jens1o** [comment]
Ah, that was a fast fix. ;) Thank you very much! :)
