### ISSUE TITLE
Do not require password to add email addresses/delete devices

### ISSUE THREAD

**Issue by squidink7** [vector-im/riot-web#13119]
Description 
If someone forgets their password and would like to reset it, but does not have and email tied to their account, they should be able to add one using an already existing session, however this is not possible due to the password requirement to add an email address. 
Also a user should be able to delete old sessions tied to their account without entering their password, as the worst case scenario is they have to sign in again on accident. 

It would be ideal if a user could change these settings for ease of use, and so it makes account recovery possible. I do realise this would lessen the security of the application, but if somebody has already gotten access to your account with malicious intent, you have already been pwned and there isn't much you can do anyway.

Alternatives: 
You could also implement a password reset option within the application accessible from existing sessions, but it would not make it any more secure, and would only make more work on your end.

Not being able to reset ones password without a preexisting email tied to their account seriously harms the usability of Riot as a chat service, because as much as it pains me, not everyone uses a password manager and people forget their sign in details frequently.

**Comment by t3chguy** [comment]
This is something the matrix server mandates and not riot.

**Comment by squidink7** [comment]
Thank you, where might I find the correct place to submit this request to the matrix team?

**Comment by t3chguy** [comment]
support@matrix.org

**Comment by turt2live** [comment]
This would require spec changes and a strong argument to remove the security features from the protocol: please open an issue on matrix-doc.
