### ISSUE TITLE
Upgrade encryption at login prompts twice for passphrase

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#13110]
* @BillCarsonFr created a new account on app (no cross-signing) and set up key backup, sent 1 encrypted message
* Logged in to develop, prompted to upgrade encryption during auth flow
* It does work, but you are asked for your passphrase twice.

**Comment by jryans** [comment]
I'll retest this next week once https://github.com/matrix-org/matrix-js-sdk/pull/1311 is merged.

**Comment by bwindels** [comment]
I can't repro this anymore.

**Comment by jryans** [comment]
Okay, thanks for trying!

**Comment by LinuxOnTheDesktop** [comment]
I am getting asked twice for a password when logging in - logging into a homeserver. Combined with [other problems in broadly the same area](url=https://github.com/vector-im/riot-web/issues/13270) - and to which this problem might causally relate - it means I must give up on Riot.

**Comment by jryans** [comment]
> I am getting asked twice for a password when logging in - logging into a homeserver.

Password is not the same as passphrase. Sorry to hear you've had trouble, but we can only improve if you report the situation you're experiencing. Please file a new issue if you're interested in helping.
