### ISSUE TITLE
Failed to send logs: End-to-end encryption disabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13116]
What?

![image](https://user-images.githubusercontent.com/1190097/78961524-fd40c500-7aae-11ea-9758-8b12acf5c2a2.png)

**Comment by turt2live** [comment]
Logs and e2e should be decoupled.

**Comment by bwindels** [comment]
> Logs and e2e should be decoupled.

I imagine this is to get the cross-signing keys, etc to include in the rageshake.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4381/commits/f91565c231278bbf510bcd33ac9ffded38983987
