### ISSUE TITLE
Link to yarn install guide in README is now a 404

### ISSUE THREAD

**Issue by cheryllium** [vector-im/riot-web#13124]
### Description

Under "Building from Source" section of README.md, the link to the yarn install guide leads to a 404 because of changes on yarn website. The current (broken) link is https://yarnpkg.com/docs/install/ 

The correct link should be https://classic.yarnpkg.com/en/docs/install

**Comment by cheryllium** [comment]
@turt2live I can do this, it's a simple change. I'd appreciate instruction on correct way to make pull request. I forked riot-web, should I create a new branch for this change and if so what should be the naming convention for this branch? I'm hoping to contribute more substantially in the future so good to learn the process with something low stakes :)

**Comment by turt2live** [comment]
The branch name doesn't matter because it's your own fork. For substantial contributions, we require sign off: see the CONTRIBUTING.md doc for more information.
