### ISSUE TITLE
Disasociating from identity server, user still discoverable

### ISSUE THREAD

**Issue by geckolinux** [vector-im/riot-web#13129]
Hi there, I would prefer for my account to not be discoverable. So in Riot I hit the big red *Do not use an identity server* button, and it now says: 

> You are not currently using an identity server. To discover and be discoverable by existing contacts you know, add one below.

However, when using another Riot account, I can still find that account by searching for it when adding a new direct chat. Is this just a matter of a cache needing to be cleared? Or am I not understanding something? Thanks a lot.

**Comment by geckolinux** [comment]
Related? #10967

**Comment by t3chguy** [comment]
> I can still find that account by searching for it when adding a new direct chat.

Are you searching by e-mail address?
Thats all the identity server does, e-mail and msisdn (phone number) lookups.

Your homeserver makes you visible to other user if you are in any public rooms, additionally you can be found in the user directory if you have any rooms in common with the user which is searching.

**Comment by geckolinux** [comment]
The user part of the email address `user@domain.com` is shared with the Matrix ID `@user:matrix.org`. When I search for `user`, it finds `@user:matrix.org`, despite that account supposedly disassociating from the default vector.im identity server.

So maybe it's still visible because at some point I probably used one of the public test rooms with that account? As for rooms in common with the user that's searching, no, I don't believe there are any.

**Comment by t3chguy** [comment]
Identity server can only perform *exact matches* so if you're searching for `user` and it finds the user `@user:matrix.org` then that doesn't even touch the Identity server

**Comment by geckolinux** [comment]
Hmmm OK... So where's it finding it from?

**Comment by t3chguy** [comment]
Your server's user directory which indexes all users in public rooms

**Comment by geckolinux** [comment]
Hmm OK, so we're still going on the probable assumption that I used one of those Matrix test rooms at some point with my user, and that got me publicly indexed?

So not a bug. Thanks for helping to explain that.
