### ISSUE TITLE
while yarn install 'building fresh package' is loading non stop

### ISSUE THREAD

**Issue by maruthimaru** [vector-im/riot-web#13121]
### Description

I had download your project and yarn install all packages are download successfully but "building fresh package loading non stop

### Steps to reproduce
1) I had clone your project in vs code
2) using yarn installed the packages command - yarn install 
3) after loadind the packages "buildind fresh packages..." started.
non stop loading even network is good

[4/4] Building fresh packages...
[-/5] ⠁ waiting...
[2/5] ⠂ canvas
[3/5] ⠂ ejs
[-/5] ⠂ waiting...
[-/5] ⠂ waiting...

![riot web issue](https://user-images.githubusercontent.com/27765062/79004315-20807880-7b72-11ea-9d3b-194fb560e2ad.png)

In some case:
If terminate the loading and again yarn install i brings some other error.

In this case
[4/4] Building fresh packages...
[-/5] ⢀ waiting...
[2/5] ⢀ canvas
[-/5] ⢀ waiting...
[4/5] ⢀ core-js-pure
This is issue:

![Screenshot from 2020-04-10 21-39-11](https://user-images.githubusercontent.com/27765062/79005385-60485f80-7b74-11ea-93de-d27a11e6567e.png)
![Screenshot from 2020-04-10 21-47-06](https://user-images.githubusercontent.com/27765062/79005617-e664a600-7b74-11ea-9e8f-028c57cf651c.png)

### Version information

npm - 6.14.4
node - v13.12.0
react native - 4.6.0 
- **Platform**: web (in-browse)

For the web app:

- **Browser**: Chrome ? Version 80.0.3987.163
- **OS**: Ubuntu 18.04
- **URL**: riot.im/develop

So I need Support to fix this issue.

**Comment by turt2live** [comment]
This is yarn being slow and not something we're able to look at. For support, use #riot-web:matrix.org
