### ISSUE TITLE
New messages counter on down arrow shouldn't standard be red

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#13135]
When back messages are shown, at the bottom right there is an arrow button to jump to the most recent message.  If new messages arrive while that arrow is there, their number is shown on a red disk.  This is misleading, as it seems to suggest a 'red' message has arrived - one that is specifically addressed to one.  That shield should only be red if such messages are indeed among the new ones.

**Comment by turt2live** [comment]
A very long time ago it used to be red for notifications, and green for other messages. Definitely a regression in the last 3 years.
