### ISSUE TITLE
Janky text wrapping in filenames in quoted messages

### ISSUE THREAD

**Issue by geckolinux** [vector-im/riot-web#13147]
Hi, I'm using the Riot 1.5.15 Electron app on openSUSE Tumbleweed.

I usually keep my chat window pretty small. This is what happened when I quoted this message:

![Screenshot_20200412_195531](https://user-images.githubusercontent.com/2692138/79084240-446dc680-7cf8-11ea-8ccd-2b519679923a.png)

---------------

![Screenshot_20200412_195426](https://user-images.githubusercontent.com/2692138/79084243-49cb1100-7cf8-11ea-83ef-65c80d9089e7.png)

**Comment by geckolinux** [comment]
Same thing with quoted
![Screenshot_20200412_222451](https://user-images.githubusercontent.com/2692138/79089684-9ddff080-7d0c-11ea-9fe7-b653a841d8bf.png)
 links:

**Comment by turt2live** [comment]
Largely https://github.com/vector-im/riot-web/issues/6488
