### ISSUE TITLE
Communities can be dragged around by their context dialog

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13145]
### Description

![Peek 2020-04-12 20-16](https://user-images.githubusercontent.com/1342360/79077574-9dd6f500-7cfa-11ea-9cf9-e0eef6bcaf0a.gif)

Kinda fun, but the behaviour I expected.

### Steps to reproduce

- Open a community's context menu
- Drag the menu
- See the community start to re-order itself in the list

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Manjaro Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
That works hilariously well :D
