### ISSUE TITLE
The URL /.well-known/matrix/client is not requested on the right server port

### ISSUE THREAD

**Issue by andyg1001** [vector-im/riot-web#13142]
### Description

The desktop and iOS riot clients do not pick up the .well-known file from homeservers that do not use the standard HTTPS port.  My guess is that the request for this file does happen and the correct server name is used in the URL, but the port is 443 rather than the correct port.  However, I am not able to test this assumption because my internet firewall does not allow port 443 to be opened to the internet (don't ask!).  My guess is based on this: https://github.com/vector-im/riot-web/blob/86b612330598f455fbb75d74d1b1ae00f098399f/src/vector/mobile_guide/index.js#L67

Note: In comparison, the android client does request the .well-known file correctly.

### Steps to reproduce

1. Install your own synapse homeserver running on a non-default public port (i.e. not 443).
2. Create a .well-known file according to https://matrix.org/docs/spec/client_server/latest#get-well-known-matrix-client
3. Connect to homeserver from the desktop, iOS and android client apps
4. Check web server logs for access requests

### Version information

- **Platform**: desktop (definitely), web (probably, but untested)

For the desktop app:

- **OS**: Windows and Debian Linux tested
- **Version**: 1.5.15

**Comment by t3chguy** [comment]
how from an MXID like @user:server_name would it know to go to `https://$server_name:$your_port/.well-known/matrix/client`? This is what well-known look ups are for.

As per the spec,

> Note that this endpoint is not necessarily handled by the homeserver, but by another webserver, to be used for discovering the homeserver URL.

It isn't meant to be on your custom port.

**Comment by andyg1001** [comment]
I can't say since this is not my area of expertise, but the android client does handle it nicely, seemingly, in the sense that it really does request this file on the right port.

Up until now this hasn't been something on my radar because there is no real use for this file, like you say, if all you're doing is using it to access a server "globally" since no other part of the infrastructure expects a non-443 port.  However, if this is a totally private installation, it starts to become useful when you consider the up-and-coming support for self-hosted jitsi through this file (see https://github.com/vector-im/riot-web/blob/develop/docs/jitsi.md).  With this, people can log in through their iOS/android client using the custom homeserver with port included, and the client will pick up the jitsi config directly.

According to the above document support in iOS and android is not yet there ... but hopefully one day it will be ... and my expectation is that the android client will use the well-known file to pick up the correct jitsi server but, currently, the web/desktop client and iOS client won't.

**Comment by t3chguy** [comment]
where should it be discovering your port from though? Where do you have a file/thing saying what port is it on?

**Comment by andyg1001** [comment]
When you log in using a custom homeserver, you can set the port there.  The fix, potentially, is relatively straight-forward: copy the whole base url, including port, from the custom homeserver, rather than just the domain name.

**Comment by t3chguy** [comment]
Riot Web only cares about well-known lookup for mxid entry, not for custom homeserver entry where is let's you control exactly what you connect to.

**Comment by andyg1001** [comment]
Isn't that about to change, or have I misunderstood the jitsi doc I linked above?  That document suggests that the well-known config file will be used by the client to connect to the correct jitsi server when using a custom homeserver.  I was really looking forward to this improvement.

**Comment by t3chguy** [comment]
I was confusing your use-case with login. Will defer to someone who knows better for jitsi

**Comment by andyg1001** [comment]
No probs, sorry I was not very clear!  But thanks, anyway, for spending the time :o)

**Comment by turt2live** [comment]
The .well-known configuration for Jitsi is not yet available. It's meant to be included in 1.15.16 (next release, due Tuesday). 

It'll use it regardless of how the user logged in, and will make the call according to the spec. What is the request here?

**Comment by t3chguy** [comment]
What host:port will it fetch it on? Server_name:443?

**Comment by turt2live** [comment]
Correct, that's the spec.

**Comment by t3chguy** [comment]
Sorry, where in https://matrix.org/docs/spec/client_server/latest#get-well-known-matrix-client does it say the fixed port? or the fact that its requested on $server_name as opposed to $hs_url?

**Comment by turt2live** [comment]
Steps 1 through 3 of https://matrix.org/docs/spec/client_server/latest#well-known-uri

**Comment by t3chguy** [comment]
So @andyg1001 as shown in the documentation mentioned right above, the port for `.well-known` files is *not* configurable.

**Comment by andyg1001** [comment]
I understand that this is the spec, but therefore I ask if it would be possible to add another mechanism by which it is possible to configure riot to use a self-hosted jitsi server.  Otherwise I see no way to get clients connecting to my homeserver to use my self-hosted jitsi server -- even once it is rolled out to the iOS / android clients (I appreciate we're not there yet, but I am hoping to be able to do this as soon as it is!).

According to the jitsi document (https://github.com/vector-im/riot-web/blob/develop/docs/jitsi.md) there are only two methods currently:

1. You can "hack" the client to tell it the preferred domain (as far as I can see, really this only works if you host riot-web in your own web server and is not practical if you use one of the other clients - e.g. desktop, iOS, android - since their installation is outside your control)

2. You can use the "well-known" file -- but this only works if you can serve an https server on port 443 (not possible for me), and the spec doesn't support reading this file from the same port as the homeserver connection as a backup option.

The method that seems absent, therefore, is that the synapse configuration is able to "push" this information to the client once it is connected.

I appeciate this is not the topic of this ticket, which is now closed, but if there is the possibility of adding such a feature to the spec, I will move this to a new ticket.

@turt2live - please could you comment?  Thanks.

**Comment by turt2live** [comment]
The `.well-known` is the way to push client configuration from the server, though other methods are being investigated in the spec (take a browse through https://matrix.org/docs/spec/proposals ). We don't currently have another way to do client configuration from the server.

The first approach is not a hack - it's an option if you self-host Riot, which is a common and encouraged use case. Installations outside of that are indeed not going to be affected, but for many communities this is fine.

The second approach feels like a self-imposed limitation. The reason `.well-known` was chosen in the spec was partly because by having the domain in your Matrix ID you're proving ownership of that domain (as you'd have to set up DNS). By proxy, if you can set up DNS you can set up a web server, which is also needed to operate a homeserver. That homeserver also needs valid SSL certificates to federate, which are free and easily acquired through DNS verification. There's also options in all popular website builder/hosting sites to put in custom routes and redirects - if `https://example.org/.well-known/matrix/client` can't be used, set up a redirect to `https://matrix.or.whatever.example.org/.well-known/matrix/client`.

**Comment by andyg1001** [comment]
Thanks for the feedback.  Its not a self-imposed limitation, but it is a limitation of the network I am working on over which I have no control.  Still, I guess I have to continue to work with what I have.  Generally it has been quite a fun challenge to get it all working on a different port; I guess I'll find some solution in the end.  Maybe I'll even have success getting the Dimension integration server working instead and use that to get the jitsi widget working...
