### ISSUE TITLE
Documentation mentions "Labs", but no such entry exists

### ISSUE THREAD

**Issue by xobs** [vector-im/riot-web#13148]
### Description

Documentation mentions there is a `Labs` feature in Rit-Web and the Desktop client, accessible under "Settings".  However, in version 1.5.15, no such section exists.

The "Labs" feature is mentioned in https://www.electronjs.org/apps/riot and in https://github.com/vector-im/riot-web/blob/develop/docs/labs.md

![image](https://user-images.githubusercontent.com/238325/79090204-75430f80-7d7b-11ea-94d9-d70df5a76b4e.png)

### Steps to reproduce

- Install the latest Riot Web version (1.5.15)
- Open the Settings menu, as per Labs documentation
- Attempt to find the "Labs" section

Logs being sent: yes/no

### Version information

- **Platform**: Desktop
- **OS**: Windows 10
- **Version**: 1.5.15

**Comment by aaronraimist** [comment]
Labs features have to be enabled in `config.json`. See https://github.com/vector-im/riot-web/blob/develop/docs/config.md.

**Comment by xobs** [comment]
I can confirm that adding `"showLabsSettings": true,` to `config.json` makes the `Labs` setting show up according to the documentation.

The docs should be updated to point out that "Labs" will only show up when configured to do so, and default to not being visible.

**Comment by aaronraimist** [comment]
Feel free to submit a PR

**Comment by xobs** [comment]
https://github.com/vector-im/riot-web/pull/13149
