### ISSUE TITLE
There is still no way to view the public keys of your own devices

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13150]
If I view my own MemberInfo and expand the device list, the cursor makes it look like i can click on them. But nothing happens if I do, and I have no way of viewing the device's public keys for legacy verif purposes (e.g. people who want to publish their pubkeys out of band as an additional safety measure)

**Comment by ara4n** [comment]
I also can't view the pubkeys of verified devices for other people.

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/2735
