### ISSUE TITLE
Network dropdown is not scrollable

### ISSUE THREAD

**Issue by dapor2000** [vector-im/riot-web#13158]
### Description

If you are looking after a room and have a lot of servers in your list, you aren't able to scroll to the top of the list and the list is wasting space with this "matrix" under each server.

### Steps to reproduce

- use riot-web: 1.5.15 
- connect to a riot with a lot of servers as https://riot.dapor.org
- go to the explorer room view
- try to change the server on which you will try to find a room

Describe how what happens differs from what you expected.

I would like to search on matrix.org, but arent able to select the server

![Bildschirmfoto von 2020-04-14 13-22-39](https://user-images.githubusercontent.com/4719017/79223380-82363080-7e59-11ea-8fca-16167c802fbb.png)

### Version information

- **Platform**: web (in-browser) on Firefox

For the web app:

- **Browser**: FireFox 75.0 (64-Bit)
- **OS**: ubuntu 18.04
- **URL**: https://riot.dapor.org

**Comment by t3chguy** [comment]
Well in future networks may be discoverable over federation so `Matrix` might be joined with Bridges, so multiple entries are in fact needed

**Comment by joepie91** [comment]
> Well in future networks may be discoverable over federation so `Matrix` might be joined with Bridges, so multiple entries are in fact needed

That seems like it could be made conditional; collapse into single-line entry if there's only a "Matrix" entry, display full-size otherwise.

**Comment by t3chguy** [comment]
It was built on https://www.figma.com/file/zAnOai5bnR94dI4mBhsmok/Explore-servers

**Comment by joepie91** [comment]
That URL is not publicly accessible, FWIW.

(Aside, note that this issue is two-fold; the bulky single-entry servers are one issue, but the apparent inability to scroll through the list is another that's separate from that.)

**Comment by t3chguy** [comment]
Indeed, it should definitely become scrollable

**Comment by dapor2000** [comment]
I would prioritize scrollable before the  "bulky single-entry servers"

**Comment by t3chguy** [comment]
In this repo we favour one problem issues, so if you care about the design then feel free to open another issue for the design, but this issue will just be used for the scrolling
