### ISSUE TITLE
Unable to create key backup

### ISSUE THREAD

**Issue by fladd** [vector-im/riot-web#13153]
### Description

I had to delete the key backup, because Riot would fail to recover from it. But now when trying to set it up again, I get this:
﻿﻿
![image](https://user-images.githubusercontent.com/2971539/79172373-d4913600-7df4-11ea-8b75-b91d308f7530.png)

I am on Riot develop and I have cross-signing enabled (which by the way also does not work at all, as I cannot verify any devices, please also see: https://github.com/vector-im/riot-web/issues/12959#issuecomment-612433987

### Steps to reproduce

- Settings --> Security & Privacy --> key backup --> Start using key backup

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop?
web (develop)
For the web app:

- **Browser**:=Firefox 75
- **OS**: macOS
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Hmm, interesting, I am seeing a lot of errors of the form:

> Error creating key backup Key type master from getCrossSigningKey callback did not match
> Error creating key backup Key type self_signing from getCrossSigningKey callback did not match

@uhoreg, do you have any forensic requests on things to examine here?

If not, I am tempted to guess that something's gotten out of sync in your account data with all the various cross-signing changes, and at this point it may be best to reset your cross-signing / secret storage. As a safety measure, you may want to export E2E room keys first just in case something goes very wrong. Resetting cross-signing / secret storage will recreate key backup and your cross-signing identity, so it should get key backup going again and you would also need to reverify any users with cross-signing that you may have verified before.

**Comment by uhoreg** [comment]
It looks odd to me that it looks like it's calling the bootstrap function to re-create the backup.  But it looks like something is out of sync with the cross-signing keys.  Maybe try logging in and logging back out again.

**Comment by fladd** [comment]
After resetting cross-validation, it now seems to work again. Except that I have now one password more than before (before I thought that the "encryption passphrase" was identical to the "secret storage passphrase", but now apparently these are different things (I have 4 things in total now: account password, secret storage passphrase, encryption passphrase and encryption recovery key; I hope this is correct?).

Here is how things look now after resetting and verifying 5 devices in total (Riot-dev/Win10, Riot-dev-MacOS, Riot-X, Riot-Android, Riot-iOS):

![image](https://user-images.githubusercontent.com/2971539/79467286-e98ce580-7ffd-11ea-80bb-7b4772fd23c9.png)

**Comment by fladd** [comment]
From a recent discussion in #riot-web it is not clear whether this is actually solved for me now. It might be that the "encryption passphrase" and the "secret storage passphrase" are two different things for my account now.

To be more precise, during resetting cross-validation, I was first asked to enter a new "encryption passphrase", which I did ( I let my password manager generate a random one for me). Then I was shown my new "encryption recovery key", which I also wrote down. Then I was asked to enter my "secret storage passphrase", so I entered the one that has always been in my password manager (i.e. long before resetting), which apparently worked. It was only afterwards, that I was told that "encryption passphrase" and "secret storage passphrase" are apparently the same thing. It was only because I was not aware of that renaming that I attempted to enter my "old" "secret storage passphrase", when asked for it. It is not clear to me why I had to enter the old one again, when I literally just the second before created a new one (as apparently those two passphrases are the same), and it is also not clear to me, whether after having entered the old one (for whatever reason), it has been deleted (overwritten with the new one). It would be great to get some clarification on this, before I consider this issue to be solved for me.

It also appears that all of my other devices now automagically do key backup without asking for a password anymore. I don't understand why. Before the reset, they constantly asked for that, but I couldn't provide them with one, since things were broken for me. Now they just stopped asking, and seem to backup fine. How did those devices get the access to my secret storage? Especially since the password apparently changed, and they have never ever received the new one from me (whether in a successful or unsuccessful attempt)? Again, some clarification would be highly appreciated.

**Comment by jryans** [comment]
> To be more precise, during resetting cross-validation, I was first asked to enter a new "encryption passphrase", which I did ( I let my password manager generate a random one for me). Then I was shown my new "encryption recovery key", which I also wrote down. Then I was asked to enter my "secret storage passphrase", so I entered the one that has always been in my password manager (i.e. long before resetting), which apparently worked. It was only afterwards, that I was told that "encryption passphrase" and "secret storage passphrase" are apparently the same thing. It was only because I was not aware of that renaming that I attempted to enter my "old" "secret storage passphrase", when asked for it. It is not clear to me why I had to enter the old one again, when I literally just the second before created a new one (as apparently those two passphrases are the same), and it is also not clear to me, whether after having entered the old one (for whatever reason), it has been deleted (overwritten with the new one). It would be great to get some clarification on this, before I consider this issue to be solved for me.

I agree that's very confusing, and @dbkr filed https://github.com/vector-im/riot-web/issues/13212 which we'll track to fix before release.

> It also appears that all of my other devices now automagically do key backup without asking for a password anymore. I don't understand why. Before the reset, they constantly asked for that, but I couldn't provide them with one, since things were broken for me. Now they just stopped asking, and seem to backup fine. How did those devices get the access to my secret storage? Especially since the password apparently changed, and they have never ever received the new one from me (whether in a successful or unsuccessful attempt)? Again, some clarification would be highly appreciated.

As part of recent changes in the last few weeks, your device now uses "key sharing" or "gossiping" to send certain private keys using device-to-device messages after you verify them, including the message backup key, the user signing key, and the self signing key. (The master key for your cross-signing identity is not cached on device or gossiped, so accessing it would require the recovery passphrase.)

With that in mind, it sounds like things happened as expected, but we certainly need better user-facing docs and info about how it all fits together. 😅 You reset on web, which also cached some private keys (including backup key) locally for gossiping to your verified devices, and they received that key during verification. Since they received it, they are able to access your backup without any other steps from you.

Given all of that, would you consider this issue resolved?

**Comment by fladd** [comment]
No, as of your advice I just logged in to Riot with a different browser and verified via "recovery passphrase". This only worked with the **old** passphrase!

**Comment by fladd** [comment]
> 
> 
> > To be more precise, during resetting cross-validation, I was first asked to enter a new "encryption passphrase", which I did ( I let my password manager generate a random one for me). Then I was shown my new "encryption recovery key", which I also wrote down. Then I was asked to enter my "secret storage passphrase", so I entered the one that has always been in my password manager (i.e. long before resetting), which apparently worked. It was only afterwards, that I was told that "encryption passphrase" and "secret storage passphrase" are apparently the same thing. It was only because I was not aware of that renaming that I attempted to enter my "old" "secret storage passphrase", when asked for it. It is not clear to me why I had to enter the old one again, when I literally just the second before created a new one (as apparently those two passphrases are the same), and it is also not clear to me, whether after having entered the old one (for whatever reason), it has been deleted (overwritten with the new one). It would be great to get some clarification on this, before I consider this issue to be solved for me.
> 
> I agree that's very confusing, and @dbkr filed #13212 which we'll track to fix before release.
> 
> > It also appears that all of my other devices now automagically do key backup without asking for a password anymore. I don't understand why. Before the reset, they constantly asked for that, but I couldn't provide them with one, since things were broken for me. Now they just stopped asking, and seem to backup fine. How did those devices get the access to my secret storage? Especially since the password apparently changed, and they have never ever received the new one from me (whether in a successful or unsuccessful attempt)? Again, some clarification would be highly appreciated.
> 
> As part of recent changes in the last few weeks, your device now uses "key sharing" or "gossiping" to send certain private keys using encrypted device-to-device messages after you verify them, including the message backup key, the user signing key, and the self signing key. (The master key for your cross-signing identity is not cached on device or gossiped, so accessing it would require the recovery passphrase.)

Thanks for the detailed explanation!

**Comment by jryans** [comment]
> No, as adviced in #riot-web I just logged in to Riot with a different browser and verified via "recovery passphrase". This only worked with the **old** passphrase!

Now that reset should be working on develop, I believe this is fixed. If there is still a problem. Let's reopen / create a fresh issue.

**Comment by lrvick** [comment]
@jryans This issue is biting me as well so I suspect we should reopen this.

Out of a desire to rotate my recovery password I deleted my recovery and tried to recreate it.

Now all my clients nag me to setup recovery, however when I try to I get the same "Unable to create key backup" error.

**Comment by lrvick** [comment]
On further investigation web console says:

"Error creating key backup Error: Could not decrypt m.megolm_backup.v1 because none of the keys it is encrypted with are for a supported algorithm" 

Perhaps I have an old key backup from an old client that modern clients no longer support and this has my account in a broken state?

**Comment by lrvick** [comment]
So it seems I can't fetch keys for people, and I can't create new rooms. 

Looking at the console logs it looks like a lot of operations just hit the "checking backup key status" then choke, and try again over and over until I get 429s and it errors and tells me it can't create a room.

Seems related.

**Comment by t3chguy** [comment]
@lrvick are you using matrix.org? They are overloaded. 429 errors are server-side and unrelated to Riot.

**Comment by lrvick** [comment]
Same problems in both https://app.element.io and https://riot.im/app
