### ISSUE TITLE
#general:mozilla.org doesn't show up in my autocomplete

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13152]
But Riot knows the alias exists

**Comment by MichaelKohler** [comment]
Works for me

**Comment by t3chguy** [comment]
Same here

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/79704853-a1c1c480-8270-11ea-9279-7b0946e2b44e.png)

It definitely knows the alias exists:
![image](https://user-images.githubusercontent.com/1190097/79704890-c28a1a00-8270-11ea-901e-92ab604f93c2.png)

I have tried clear cache and reload, much to my server's despair.

**Comment by t3chguy** [comment]
Room autocomplete only shows the top *4* results, hence it not showing up for you.
https://github.com/matrix-org/matrix-react-sdk/blob/2b1964878681fae72a0382f11000a807da76ed2c/src/autocomplete/RoomProvider.js#L109

**Comment by turt2live** [comment]
Didn't we used to have a heuristic for most recently used shows up first?

**Comment by t3chguy** [comment]
I don't recall that, but would be a sane thing to add
