### ISSUE TITLE
Encryption setup gets stuck on spinner if key upload fails

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13162]
Just made a new test. account and the request to upload the secret storage default key (`PUT https://matrix.org/_matrix/client/r0/user/[user]/account_data/m.secret_storage.default_key`) took more than 30s so the client gave up, but I am now stuck staring at a spinner on the 'Setting up keys' page and I don't think it's actually doing anything at all.

**Comment by artooro** [comment]
Having the same issue with riot-web 1.6.0-rc.2 with synapse 1.12.3 .
Clicking Upgrade on the new "Upgrade your encryption" toaster ends up in a "Setting up keys" dialog that never goes anywhere, click the X close button results in a "Unable to set up secret storage" message.
