### ISSUE TITLE
twemoji font is missing from emoji in self-verif flow at login

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13184]

**Comment by ara4n** [comment]
<img width="1075" alt="Screenshot 2020-04-15 at 20 13 02" src="https://user-images.githubusercontent.com/1294269/79378700-ac6d1880-7f55-11ea-93d5-aa68b5e2070f.png">

these are Apple emoji, not twemoji

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/12807
