### ISSUE TITLE
if you enter the wrong SSSS passphrase after cross-signing another user it silently fails and cancels the verification

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13185]

**Comment by bwindels** [comment]
To be clear @ara4n, you're not being told your passphrase is wrong like here?:

![image](https://user-images.githubusercontent.com/274386/79452893-64430a00-7fd8-11ea-967c-384c986b0800.png)

**Comment by ara4n** [comment]
correct.

**Comment by ara4n** [comment]
i'll try to repro - i thought i rageshaked but i can't find it :(  i was surprised it was prompting me for an SSSS passphrase at all after cross-signing another user, though...

**Comment by bwindels** [comment]
Does your `m.cross_signing.user_signing` have a `mac` and `iv` property @ara4n ?

**Comment by ara4n** [comment]
yup.

**Comment by bwindels** [comment]
Relevant account data at https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$Yvyd1uUQKcDRd6C0L8dj0VdRB7Frvk7LVq1Spt3mg_s?via=matrix.org&via=vector.modular.im&via=uhoreg.ca

**Comment by uhoreg** [comment]
Looks like it should be working.  I just tried, and when I enter an incorrect passphrase, it displays a warning.  @ara4n are you on the latest develop?

**Comment by bwindels** [comment]
Same for me btw, I could not repro.

**Comment by bwindels** [comment]
@ara4n Both me and @uhoreg can't phantom how this could happen given your account data AND you're definitely running the latest develop. I wonder how if you're certain you entered the wrong passphrase. Could it be possible your passphrase was correct and something else failed afterwards.

Can you still repro? If so, could you rageshake?

**Comment by jryans** [comment]
Seems like more info is needed, and these areas changed rapidly up to release, so I think it's best to close until there's another report of this.
