### ISSUE TITLE
'complete security' naming is strange

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13182]
shouldn't it be 'verify this login'?

**Comment by jryans** [comment]
The text [comes from Figma](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=6%3A7651), so I defer to @nadonomy on this. It seems okay as-is to me, but I am likely biased from seeing it so many times...

**Comment by ara4n** [comment]
it is now fixed as "Verify your session", given that's what's happening.
