### ISSUE TITLE
riot-desktop (1.6rc): tray icon blank / res packaged wrongly

### ISSUE THREAD

**Issue by steef435** [vector-im/riot-web#13190]
This is an issue for code in https://github.com/vector-im/riot-desktop specifically.

### Description

yarn run build places the img folder in the same path as the asar (asarPath) in the package, but the code expects icons to be in asarPath/res/img. See https://github.com/vector-im/riot-desktop/blob/master/src/electron-main.js#L130. This results in a blank tray icon until it gets updated* (e.g. something is unread). Quick fix is `sed -i "s@resPath = path.join(path.dirname(asarPath), 'res');@resPath = path.dirname(asarPath);@g" src/electron-main.js`, but this will probably break the path resolution for local development.

### Steps to reproduce

- start riot-desktop (with zero unread messages)
- the tray icon is blank until the unread counter changes from 0 to something else

Note: this is hard to reproduce on real accounts since then there are usually some unread messages on startup, so the icon will instantly be visible. For new users or for those in little rooms, it may remain blank for a long time though.

### Version information

riot-desktop packaged (master as of now, but specifically 1.6 rc 1).

- **OS**: Linux (built on Linux)
- **Version**: 1.6.0-rc.1

To be extra clear: this is _not_ the same as #12518. The tray icon is there, it's just blank because of the seemingly faulty packaging / search path.

*: honestly I don't know why this _does_ show up. But I can confirm that on start, it only sends a zero-byte icon to the tray, and then after there are notifications it starts sending icons properly.

**Comment by t3chguy** [comment]
This will affect stable 1.6 builds too as they come from the new repo riot-desktop
