### ISSUE TITLE
New login failed to participate in online backup.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13201]
* Signed in on new account and self-verified using emoji comparison (from memory)
 * Backup wasn't restored (**but last time I did this, i hit the backup key corruption bug which should now be fixed**)

At this point, my backup settings were:

![image](https://user-images.githubusercontent.com/1294269/79451532-99eaf180-7fde-11ea-8f66-091a47a536a1.png)

 * Hit the "restore backup" button, entered passphrase, was told passphrase was wrong.
 * Hit the "restore backup" button again, this time it worked and downloaded all my keys (without prompting for passphrase?!)
 * After churning for a few minutes, it prompted for SSSS passphrase
 * Then it reported failure that restoring key backup had failed:

```
rageshake.js?432e:65 Secure Secret Storage ready
12:14:27.824 rageshake.js?432e:65 Error restoring backup TypeError: this.getSecretStorageKey is not a function
    at MatrixClient.restoreKeyBackupWithSecretStorage (client.js?2444:1825)
    at async accessSecretStorage (CrossSigningManager.js?8a57:259)
    at async RestoreKeyBackupDialog._restoreWithSecretStorage (RestoreKeyBackupDialog.js?a15b:185)
```

 * I then refreshed and empirically my keys had restored.  backup & xsigning settings then looked like:

![image](https://user-images.githubusercontent.com/1294269/79451577-ab33fe00-7fde-11ea-9f58-e05a657483d7.png)

**Comment by jryans** [comment]
The "backup key stored: not stored" bit is somewhat surprising since it's checking whether "m.megolm_backup.v1" exists in 4S, and @ara4n has confirmed it is present in account data. 🤔

**Comment by jryans** [comment]
@t3chguy suggests this might related to / the same root cause as https://github.com/vector-im/riot-web/issues/13229

**Comment by bwindels** [comment]
@ara4n Looks like there was an issue with the migration path which would prevent restoring your key backup. I imagine your key still hasn't been migrated fwiw. The PR above should hopefully fix it.

Might help to explain some other key backup issues.
