### ISSUE TITLE
Resetting cross-signing/SSSS doesn't reset SSSS password

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13212]
It asks for the SSSS password after prompting you for a new one, but then appears to store the new cross-signing secrets with the old SSSS key, so your password stays the same.

**Comment by jryans** [comment]
Flagging as blocker, we definitely want a reset button that works.

**Comment by fladd** [comment]
More importantly, the old key is still valid after the resetting procedure!

**Comment by dbkr** [comment]
Updated the title & description to reflect this

**Comment by dbkr** [comment]
Looks like this regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1311

**Comment by non-Jedi** [comment]
Is key reset expected to work on Riot Android and RiotX? After resetting it's showing a different set of devices as verified on Riot Android and RiotX than riot-web. Can file bug/send rageshake if necessary.
