### ISSUE TITLE
If "Order by name" is enabled some rooms don't show in the list

### ISSUE THREAD

**Issue by dannycolin** [vector-im/riot-web#13211]
### Description

When the preference to order the rooms by name is activated, some of the room I'm in don't show in
the list. The `Show rooms with unread notifications first` preferences mixed with `Order by name` seems to mitigate the issue for certain rooms only when there's unread message of course.

Note: I have 40+ rooms in my list and I haven't tried with a smaller room list.

### Steps to reproduce

- Disable `Show rooms with unread notifications first` and `Show shortcuts to recently viewed rooms above the room list`
- Enable `Order by name`

Describe how what happens differs from what you expected.

Logs being sent: yes

### Version information

- **Platform**: Web (1.5.15)

For the web app:

- **Browser**: Firefox Nightly
- **OS**: Fedora 31
- **URL**: chat.mozilla.org

**Comment by turt2live** [comment]
Should be fixed in the new room list. There's an edge case in the old algorithms which would cause this, and hopefully the bug hasn't made it into the new list.
