### ISSUE TITLE
Cleaning of Deleted Messages from Riot-Web

### ISSUE THREAD

**Issue by samyak-jn** [vector-im/riot-web#13228]
**Is your suggestion related to a problem? Please describe.**
Yes, my suggestion is that whenever we remove a thread from the channel, it gets removed, leaving behind some blurred lines icon (pasted below). 

![image](https://user-images.githubusercontent.com/44315191/79494480-b7e93e00-8040-11ea-946f-d383acc40849.png)

I'm currently using riot-web on the web and in my main OS. This seems to be buggy on both the platform. But, The Riot.im app in Android doesn't have the same bug. The message gets completely removed, leaving no traces behind. 

Is there anything we can do in this matter?

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/79495291-9c027f80-7fe1-11ea-8143-94cdc8f13cc6.png)

Turn this off in Settings -> Preferences.
