### ISSUE TITLE
Cross signing verification doesn't make it clear that you need to open a device that supports cross-signing

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13237]
Some confusion is ensuring due to the fact that riot starts waiting for another device to verify with after login, but people are going and opening a pre-cross-signing riot on a mobile device and of course nothing happens.

This is particularly acute right now when no released mobile apps support cross-signing, but will still be an issue with riot android. We probably just need a copy tweak to help the user understand that a) it has to be an up-to-date riot b) it has to not be riot android and c) if nothing happens, it's not one of those

**Comment by ara4n** [comment]
This is very similar to https://github.com/vector-im/riot-web/issues/13186#issuecomment-614274824

**Comment by jryans** [comment]
@nadonomy Do you see a copy tweak to make here to improve this? Happy to roll that in if so.

**Comment by jryans** [comment]
Instead of tweaking copy alone, we could try https://github.com/vector-im/riot-web/issues/13281 and look for whether devices to use exist, though it might lead to more waiting.

**Comment by nadonomy** [comment]
This is now unblocked, with copy & designs here:

https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=4453%3A27409
