### ISSUE TITLE
Cross-signing recovery passphrase security-level bar remains red

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13236]
### Description

![image](https://user-images.githubusercontent.com/1342360/79567440-244d5700-80ac-11ea-8b96-78d05c4ca46f.png)

![image](https://user-images.githubusercontent.com/1342360/79567365-008a1100-80ac-11ea-95a1-76192b10d4a9.png)

The bar is still red :( I assume it should go red->yellow->green as your entered password gets better and better?

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
It should be blue...

**Comment by t3chguy** [comment]
It is completely styled by the browser, and it is awfully varied between browsers: https://css-tricks.com/html5-progress-element/

**Comment by t3chguy** [comment]
Design:
![image](https://user-images.githubusercontent.com/2403652/81958428-e76e7480-9605-11ea-97f1-12bbeeb07bae.png)

`#f56679` `#ffc666` `#f8e71c` `#7ac9a1`
