### ISSUE TITLE
Building from source says it cannot find module `matrix-react-sdk`

### ISSUE THREAD

**Issue by TheStranjer** [vector-im/riot-web#13251]
## Description

When I follow the directions in `README.md` to build from source, it throws the error:

```
$ tsc --emitDeclarationOnly --jsx react
src/vector/init.tsx:123:13 - error TS2307: Cannot find module 'matrix-react-sdk'.

123             "matrix-react-sdk"),
                ~~~~~~~~~~~~~~~~~~


Found 1 error.
```

This is _after_ I `yarn install`, which should ostensibly install `matrix-react-sdk`.

### Steps to reproduce

1. Install or update `node.js` so that your `node` is at least v10.x.
1. Install `yarn` if not present already.
1. Clone the repo: `git clone https://github.com/vector-im/riot-web.git`.
1. Switch to the riot-web directory: `cd riot-web`.
1. Install the prerequisites: `yarn install`.
1. Configure `config.json`
1. `yarn dist`

See error above. I think that `matrix-react-sdk` is meant to be installed by `yarn install`, but it is not for whatever reason.

## Workaround

I have found a workaround for this: `npm install`. It takes a while. `@dawidpotocki:privacytools.io` had the same issue and the workaround required that he `rm -rf node_modules/` before using this workaround.

### Version information

Commit: `19130dc70550895518df7e60ce87f40e205061fd` (current `develop` head)

**Comment by k-meeks** [comment]
What worked for me was to git clone matrix-js-sdk, yarn link, yarn install, git clone matrix-react-sdk, yarn link matrix-js-sdk, yarn link, yarn install, THEN do the riot-web install, doing a yarn link matrix-react-sdk before the yarn install in riot-web

**Comment by turt2live** [comment]
Building from source requires using a development environment: https://github.com/vector-im/riot-web#setting-up-a-dev-environment

**Comment by ViniciusAlberto** [comment]
i am have same problem when build my project in server. Local host is working. Know how to solve this problem on the server?
