### ISSUE TITLE
always display description of log submission input fields

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13258]
### Description

The input boxes have a beatiful description, but it's only displayed when focused.

If you start typing directly after clicking on the input box/textarea you never see the description, as they are only displayed after a short animation.

![image](https://user-images.githubusercontent.com/1029578/79640452-fe9a7d80-8191-11ea-8d14-ad7accdce924.png)

### Steps to reproduce

- click on submit debug logs
- click on one of the two fields

It only displays the description when you already clicked on the field and want to start typing. In my opinion it should be displayed before.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.15 (develop @ 19130dc70550895518df7e60ce87f40e205061fd)

**Comment by t3chguy** [comment]
As per @nadonomy, the way it is currently is intentional https://github.com/matrix-org/matrix-react-sdk/pull/4440#issuecomment-620935472

> This is actually deliberate. The copy there is extremely verbose and noisy, so is deferred to a contextual interaction.
