### ISSUE TITLE
Enable key backup and cross-signing by default

### ISSUE THREAD

**Issue by 35609902357** [vector-im/riot-web#13252]
With E2EE enabled by default for private chats, key backup should be enabled by default as well. The Key backup dialogue should be presented when a new user is signing up. Cross-signing devices (#2714) should also be enabled for maximum ease of use by non-technical users.

**Comment by aaronraimist** [comment]
Key backup and cross signing are enabled by default when you signup. The first step in after you signup for an account is this screen
<img width="625" alt="Screen Shot 2020-04-18 at 2 30 23 PM" src="https://user-images.githubusercontent.com/5855073/79669447-246b5680-8181-11ea-94a5-dd0bc6874068.png">
