### ISSUE TITLE
Make Matrix appealing to non-technical people

### ISSUE THREAD

**Issue by 35609902357** [vector-im/riot-web#13268]
With the boom Zoom had in its userbase overnight, a window for Matrix to become the universal messenger has opened. If Riot and RiotX could be brought to a point where they are easy to use enough for the people who are used to sign up with their phone number and keep using the same app because they are used to it, Matrix has the chance to climb to the top in a very short time. If the UI and overall user experience become pleasant enough (#8751 for example) before people get used to Zoom, Matrix has the potential to get Zoom's new users, and from there it is not unreasonable it will appeal also Whatsapp and Telegram users (because it can do everything they can do, but better), and then Signal and Wire users (because with E2EE enabled by default the privacy conscious people will happily jump on board), and then Jami and Tox users (because it would, at least in part, satisfy their will for decentralization), and then XMPP and IRC users (because Matrix integrates everything and better). If enough people get on board, many will probably be interested in packaging and shipping Riot as the default messenger in Linux distros instead of Pidgin and HexChat, and thanks to its permissive license it might even be shipped as a default app in Android ROMs (Purism already made of Matrix their default communication method for their Librem5). It could even appeal many as a replacement for emails. Thinking big here, but why not? I see in this time frame a golden opportunity for Matrix to truly shine.

**Comment by turt2live** [comment]
Thanks fore the suggestion! We are already going down lines of work we call FTUE (First Time User Experience) which is intended to help new users with our app.
