### ISSUE TITLE
Unable to upgrade encryption - stuck at Setting up keys

### ISSUE THREAD

**Issue by artooro** [vector-im/riot-web#13269]
### Description

When attempting to upgrade encryption using riot-web RC.3 it gets stuck at setting up keys and the Synapse server (on v1.12.3) responds with a 401 status code.

### Steps to reproduce

Click Upgrade here
<img width="313" alt="Screen Shot 2020-04-18 at 17 37 56" src="https://user-images.githubusercontent.com/393395/79671873-a6687900-819b-11ea-90c7-535a6962a7b9.png">

Riot-web sends the following API calls logged in homeserver.log

```http
200 GET /_matrix/client/unstable/room_keys/version
401 POST /_matrix/client/unstable/keys/device_signing/upload
```

I see this dialog in riot-web and click Next
<img width="625" alt="Screen Shot 2020-04-18 at 17 42 22" src="https://user-images.githubusercontent.com/393395/79671967-fcd5b780-819b-11ea-8a90-dd591a2ac2d4.png">

Another request is sent to the server which responds with a 401 error.
```http
401 POST /_matrix/client/unstable/keys/device_signing/upload
```

The riot-web client is stuck on this window
<img width="715" alt="Screen Shot 2020-04-18 at 17 44 34" src="https://user-images.githubusercontent.com/393395/79672023-46260700-819c-11ea-829f-b278c0d4ec5a.png">

**Describe how what happens differs from what you expected.**
I'm not sure what to expect exactly but certainly something to the effect of keys getting upgraded.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop? Using riot-web in browser

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Brave | 1.7.92 Chromium: 80.0.3987.163
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? macOS 10.15.4
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? private server running 1.6.0-rc.3

**Comment by artooro** [comment]
I'm not sure if the fact that we use SAML for authentication has any affect on this, as there are other bugs such as we can't currently delete old sessions due to an SAML bug that I believe is fixed in synapse dev currently.  
Whether this is a bug in Synapse or Riot I don't know.

**Comment by aaronraimist** [comment]
I setup a test account earlier today and also got stuck at this spinner for a long time. Not using SAML or anything.

**Comment by t3chguy** [comment]
Possibly fixed by @MichaelKohler in https://github.com/matrix-org/matrix-js-sdk/pull/1329
