### ISSUE TITLE
Homeserver version: all invitations methods confuse and fail

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [vector-im/riot-web#13270]
### Description

There seems to be no way to invite someone from a private server or at least no way that I have in confidence in. A less technical user woulfd give up.

### Steps to reproduce

- Get a private homesever from - as it turns out - 'Modular'. (And it turned out to be rather expensive.)
- Configure the server. In my case - and I don't know whether reproducing the bug requires this - I limited registration to various (full) email addresses, though I think I allowed some guest access at all.
- Try to invite people to the room, in various ways,

**What happened**

I tried three methods of invitation. (I did see a fourth, which involves the invitee already having some sort of Matrix account. I leave that aside.)

1) When I used the 'invite' button from within my server's 'room' (and finding that button was hard)  I encountered a chain of arcane webpages - screenshots below - none of which enabled me to log in using one of the aforementioned whitelisted e-mail addresses. (I say 'none' but I did not try _all_ of the options here. Or I suppose I should say 'sub-options', given that I am discussing method / problem '1'.) 

2) When I used the 'share' button that I found somewhere else in my room, similar things (similar to 1) occured. Also: it needs to be clearer what the 'share' button means to do. Does it mean to give access? Or to send a screenshot? I think it is the former (though it does not work) but the user concerned about privacy might suppose the latter and will wonder about the point of encryption if any user can send a screenshot.

3) I could give people - or test myself - the (short, direct) URL of my server. Here is how that fails (when I test it myself). I am prompted to log in or create an account. When I try to do the latter, I am eventually told that there is something wrong with my credentials and I am asked whether I mean to log into a _non-_private server. Does that message appear only when there is a credential overlap detected? Or does it always appear? So: even that message confuses. And must one try to logon via an e-mail address when one has whitelisted e-mails? Well, I tried that and it did not work. UPDATE: When I use my _existing_ Riot administrator account to login - via this third method of using my custom URL - it does work but only . . if I supply my credentials _twice_ (as I have noted [in another bug report](url=https://github.com/vector-im/riot-web/issues/13110#issuecomment-616229172)).

**Screenshots**

I saw the following when attempting methods 1 and 2 (but not, I think, method 3).

![image](https://user-images.githubusercontent.com/47056543/79681109-1401bd00-820f-11ea-8810-96b01b668168.png)

![image](https://user-images.githubusercontent.com/47056543/79681110-18c67100-820f-11ea-9bc9-762c080fea84.png)

Whilst pursuing method 3 above, I saw this too - note its error message.

![image](https://user-images.githubusercontent.com/47056543/79681368-bf137600-8211-11ea-8f6e-8e6920ff28b8.png)

### Version information

- **Platform**: web (in-browser) or desktop?

Web.

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
Firefox 75.0

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Linux Mint

- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

The private server I'm trying to log into: philbrek.riot.im. Version of riot-web: I cannot seem to tell.

PS: Before submitting this report, github asks me to review the contributing guidelines. Yet, none of those seem relevant to a bug report.

**Comment by Twi1ightSparkle** [comment]
Related 152486

**Comment by turt2live** [comment]
@Twi1ightSparkle that's not an issue number. Are you able to edit/supply a link instead please?

**Comment by Twi1ightSparkle** [comment]
It's a customer support ticket number. Did not link as it's not a public system

**Comment by jryans** [comment]
With a bare number, I think the default is to expect an issue here, so let's at least prefix with "support ticket" or similar. You could even add a link if it's possible to link to, it just won't work for most people.

**Comment by Twi1ightSparkle** [comment]
Customer abandoned Matrix
