### ISSUE TITLE
Video Call doesnt use audio output from setting

### ISSUE THREAD

**Issue by arozhankov** [vector-im/riot-web#13274]
**Description**

When video calling the windows default audio device is used instead of the audio device selected in the Riot settings menu.

**Steps to reproduce**
- Change the windows default audio device to something besides your headphones.
- Set the Riot voice & video audio output to your headphones
- Start a video call
- Notice the output it the windows default instead of the riot default
- I checked this with the desktop client on 2 mac (MacBook and iMac).
- Moreover when doing a voice call, the device specified in the settings menu is used. So this seems like a discrepancy between the video and voice call.

**Version information**
OS: MacOS 10.15.4
Version: 1.5.15

**Comment by turt2live** [comment]
This looks largely copy/pasted from https://github.com/vector-im/riot-web/issues/10567
