### ISSUE TITLE
DeviceListener triggers account data queries when rechecking during initial sync

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#13279]
DeviceListener runs `_recheck` when the `accountData` event is triggered on the client. In `_recheck`, it calls `client.isCrossSigningReady()`, which will go into `SecretStorage`, which tries to get the `m.cross_signing.master` account data through `client.getAccountDataFromServer()` which checks the sync status to decide whether an account data request is needed or not. `accountData` is fired during the processing of the initial sync, and the sync status is only changed after having processed the entire sync response, so this situation occurs *during* the processing of the sync response.

As `_recheck` is rerun on quite some events, it can spin up to 8 requests before the sync status is changed, making the whole bootstrap security flow a lot slower than it needs to be, especially on matrix.org where each request can take up to 50s during peak times.

**Comment by jryans** [comment]
Would it make sense to change `DeviceListener` to hold of on taking an actions until initial sync processing is complete?

**Comment by dbkr** [comment]
Yeah - I was thinking similar. I can take a look at doing this?
