### ISSUE TITLE
Two cross-signing keys uploads (of which the first is empty) during registration

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#13286]
`/_matrix/client/unstable/keys/device_signing/upload` with request body `{}` which returns a `401`. Then later, it does the same request with the cross-signing keys it generated.

**Comment by bwindels** [comment]
This is apparently intentional ... https://github.com/matrix-org/matrix-react-sdk/blob/25fa675f88c783a995992fe6ff6b6638f2822ffe/src/async-components/views/dialogs/secretstorage/CreateSecretStorageDialog.js#L121

**Comment by bwindels** [comment]
Are we ok with it coming with a cost of a longer (15s under current circumstances) login / registration flow?

**Comment by jryans** [comment]
Currently we do this to skip a second account password prompt if that's all we would need to upload keys, so I suppose the choices look like:

* Check auth flows (potentially adding 15s of network delay) to possibly avoid a prompt
* Show a second password prompt
* Use some other mechanism (perhaps previous knowledge of auth flows) to avoid the request and preserve behaviour

**Comment by dbkr** [comment]
Another option would be for the synapse side to move this request to a work that passes the request to the master if it actually gets past auth, so at least the first request that intentionally fails auth is fast?

**Comment by bwindels** [comment]
> Another option would be for the synapse side to move this request to a work that passes the request to the master if it actually gets past auth, so at least the first request that intentionally fails auth is fast?

Apparently this would not be straightforward to do on synapse, so maybe not for now.

**Comment by bwindels** [comment]
> Use some other mechanism (perhaps previous knowledge of auth flows) to avoid the request and preserve behaviour

I think this won't bring any benefit for existing sessions, as we wouldn't have persisted their information from their login. Could help for new signups though.

**Comment by bwindels** [comment]
One thing I don't understand here is why we can't assume that the server will always require interactive auth? The MSC seems to [imply so at least](https://github.com/uhoreg/matrix-doc/blob/cross-signing2/proposals/1756-cross-signing.md#uploading-signing-keys). Are there any conditions that the homeserver would not enforce this? E.g. if you have interactively authenticated recently already?

**Comment by jryans** [comment]
During the standup, we were it may be possible to skip the first request that tests auth and instead pass along as password if we have one. In the current world, it's highly likely for a server to require the same auth for login and key upload, so it's reasonable to pass along if we have it. No information is leaked, since we sending the password to the homeserver which already has it.
