### ISSUE TITLE
Couldn't verify self on a new account with no rooms. 

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#13285]
See rageshake from nad: https://github.com/matrix-org/riot-web-rageshakes/issues/2631

**Comment by jryans** [comment]
Likely to be the following regression in Synapse: https://github.com/matrix-org/synapse/issues/7301

**Comment by jryans** [comment]
I'll continue tracking here for now to keep visibility on the issue.

**Comment by jryans** [comment]
Should be fixed now.
