### ISSUE TITLE
Search in direct messages encrypted room doesn't find any results

### ISSUE THREAD

**Issue by tredondo** [vector-im/riot-web#13298]
### Description

Search is very slow (~10 seconds for a DM room started a few days ago), and searching for anything only produces results from before the encryption was turned on. This seems worse than #12385

If this is expected, the search should give a prominent error about the room being encrypted. 

### Steps to reproduce

- Create a room with another user
- Send a few "test" messages
- Encrypt the room
- Send a few more "test" messages
- Search for "test"

The results should show all test messages, but only those after encryption was enabled will show up. Please note that in my case, I searched a few days after setting up encryption. I did not see any results from after the encryption, but I did see results from before.

Logs being sent: available upon request if necessary

![image](https://user-images.githubusercontent.com/10043369/79804813-ebb5c200-83b8-11ea-9966-bd8ec12683bf.png)

### Version information

- **Platform**: desktop?

- **OS**: Ubuntu 18
- **Version**: 1.5.15

**Comment by turt2live** [comment]
Version 1.5.15 does not have this feature. The 1.6 release will be the first with it, which is in the immediate future.

**Comment by tredondo** [comment]
Just found https://github.com/vector-im/riot-web/issues/2548#issuecomment-563112536. Thanks.

**Comment by ldexterldesign** [comment]
👋 https://github.com/vector-im/element-web/issues/26620
