### ISSUE TITLE
Cannot remove old device sessions when the auth backend is SAML

### ISSUE THREAD

**Issue by eddie1030** [vector-im/riot-web#13293]
### Description

My Matrix homeserver makes use of SSO (SAML), so authentication is handled by the IAM software. This works fine for the most part, *but when I try to remove an old device sessions* Riots asks for a confirmation by password, where the SSO password doesn't work.

### Steps to reproduce

- Setup matrix hs with SAML backend + setup Riot client
- login a couple of times with a (test) account in different browser sessions
- nagivate to the user settings -> security & privacy
- delete one of the device sessions (tick the box, click delete)
- add your accounts password , it should fail

### Version information

- **Platform**: web + desktop

For the web app:

- **Browser**: Firefox 
- **OS**: Debian
- **URL**: ...

For the desktop app:

- **OS**: Debian
- **Version**: 1.5.15
![bug-matrix](https://user-images.githubusercontent.com/40951658/79785611-6bee1000-8344-11ea-92e5-eb8ddb57d367.png)

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/issues/5667#issuecomment-610332077
