### ISSUE TITLE
What's the point of verification for non-encrypted rooms?

### ISSUE THREAD

**Issue by tredondo** [vector-im/riot-web#13299]
Not sure if this is a security issue that should go to security@.

### Description

A, B and C are new Riot users. In a room created by A, B joined soon, and C joined later. B and C later wanted to chat securely so they ran the verification process, which went fine. B and C went through the trouble of communicating the emojis OOB and all that.

Later, B and C discovered the room was not encrypted to begin with (!). Apparently A neglected to do so. What's the point of verification then? If there is some obscure point, neither A, nor B, nor C thought it was an intuitive one.

In our opinion, verification should either not work on unencrypted rooms, or it should warn the users that the room is not encrypted.

![image](https://user-images.githubusercontent.com/10043369/79805922-5536d000-83bb-11ea-8556-eb8d04976d22.png)

![image](https://user-images.githubusercontent.com/10043369/79805937-5ec03800-83bb-11ea-83e8-777bdc6c6f48.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.5.15

**Comment by turt2live** [comment]
> Not sure if this is a security issue that should go to security@.

When in doubt, please file it with security@ and wait for confirmation. In this case, it's not a security issue though. If there is a security issue angle, please file it with security@ and not here.

**Comment by tredondo** [comment]
@turt2live: how do I send logs to security@ without exposing them publicly? The recommended method says this:

> Before submitting logs, you must create a GitHub issue to describe your problem.

**Comment by turt2live** [comment]
You don't need to fill that in, it's just a suggestion. Logs are submitted privately, always. In general, it's fine to submit a ticket to security@ and if we need logs, we'll provide instructions.

**Comment by jryans** [comment]
When verifying users, you are verifying them wherever they may appear, not just for a single room. With the new cross-signing UI (default enabled in 1.6 to be released soon), there are shields to clearly indicate the room's encryption status and re-work much of this experience.

Are you testing cross-signing in 1.5.15 by enabling it manually somehow? If this is about the default experience in 1.5.15, then I'd suggest we close this and wait a week or so until you've tried the cross-signing experience which changes much of the UX you are evaluating here.

**Comment by jryans** [comment]
Looks to me from https://github.com/vector-im/riot-web/issues/13300 that you are indeed testing pre-cross-signing, so I think I'll close this for now, but please do test https://riot.im/staging if you want to evaluate the experience, as that's the soon-to-be-released version.
