### ISSUE TITLE
Verification dialog doesn't always auto-hide after the verification completes

### ISSUE THREAD

**Issue by tredondo** [vector-im/riot-web#13300]
### Description

After both parties complete the verification, for one of them the spinner dialog didn't hide, even though the browser console showed that verification completed. The other party still had the red shield in the message compose field.

### Steps to reproduce

- A's Desktop client (1.5.15, Linux) initiates verification
- B's web client completes verification after B verifies with A via their desktop clients the emojis

![image](https://user-images.githubusercontent.com/10043369/79810940-7e119200-83c8-11ea-98e7-f410c978c567.png)

Might this be a desktop <-> web verification incompatibility, or unidirectional verification issue? To B's web client, A's desktop does appear verified. But to A's desktop, B's web appears unverifed. To B's desktop, both B's web and A's desktop appear verified.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromium 80
- **OS**: Ubuntu 18
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
This dialog is no longer in the primary flows from 1.6 cross signing release. Try riot.im/staging

**Comment by jryans** [comment]
Thanks for providing feedback on this! As @t3chguy says above, much of the encryption experience has been reworked for the upcoming release and this flow is gone now, so I'll close this.
