### ISSUE TITLE
Build error after update - modernizr.js

### ISSUE THREAD

**Issue by magicznyadrian** [vector-im/riot-web#13308]
### Description

after today's git pull and try yarn build I have errors:  Property 'Modernizr' does not exists..
When I open src/web/vector/index.ts in line with "import './modernizr"  I have error: Could not find a declaration file for module modernizr

### Steps to reproduce

- yarn build

### Version information

- **Platform**: web (in-browser)

For the web app:
- **OS**: Ubuntu 19.10
- **URL**: riot.im/develop/src/vector/modernizr

**Comment by t3chguy** [comment]
Did you pull the latest react-sdk changes?
