### ISSUE TITLE
Cannot unignore users

### ISSUE THREAD

**Issue by gcp** [vector-im/riot-web#13309]
### Description

I accidentally ignored a co-worker. I can see him listed in Settings->Security & Privacy, and there is an unignore button. Clicking the button has no effect. (force) Refreshing the page does not change anything either. It is not possible to unignore the users from the web client.

I worked around this with the mobile app, though the web client needed a "clear cache" before it picked up the change.

### Steps to reproduce

- Ignore a user
- Try to unignore via the settings on the web client

Describe how what happens differs from what you expected.

button go vroom

### Version information

- **Platform**: web (in-browser)
For the web app:

- **Browser**: Firefox Nightly
- **OS**: Ubuntu 18.04
- **URL**: chat.mozilla.org

**Comment by ihatetothink** [comment]
I'm giving it a go.
