### ISSUE TITLE
Riot Desktop client not working with ReCaptcha

### ISSUE THREAD

**Issue by andreasnuesslein** [vector-im/riot-web#13307]
### Description

When using recaptcha with matrix-synapse and the riot-desktop client you get a 
```
ERROR for site owner:
Invalid domain for site key
```

This seems due to the fact that the riot-desktop clients recaptcha request is not proxied via the actual matrix instance and therefore it is not in the list of recaptcha-allowed sites/domains.

This can be circumvented by unchecking "Verify the origin of reCAPTCHA solutions" in the ReCaptcha settings but I think the nicer solution would be to do the same thing the riot-android does and have the matrix instance proxy the captcha (I think?)

### Steps to reproduce

- install custom matrix-synapse
- get recaptcha keys from https://www.google.com/recaptcha/admin/
- leave "Verify the origin of reCAPTCHA solutions" checked.
- enable recaptcha in the homeserver.yaml
- try to register on the custom server using the riot-desktop built

### Version information

- **Platform**: desktop
- **OS**: Ubuntu, using the `https://packages.riot.im/debian/ bionic main` repo
- **Version**: 1.5.15 amd64

PS: I did query the existing issues for at least 10 minutes and could not find this - I hope I didnt overlook it after all.

**Comment by t3chguy** [comment]
> riot-desktop clients recaptcha request is not proxied via the actual matrix instance and therefore it is not in the list of recaptcha-allowed sites/domains.

No riot proxies recaptcha via the matrix server. They always load it directly, loading it in an iframe makes it fail more due to less data it can collect and this is the only way to proxy it as you describe. Either add `vector` as a whitelisted origin or disable verifying of origin.

**Comment by andreasnuesslein** [comment]
Oh, hm - why did it work just fine with the android app then? I did specifically try it before reporting this issue. 
Would I add `vector.im`? or which domain exactly?

**Comment by t3chguy** [comment]
The desktop app runs on an origin called `vector` it is virtual and only exists to the app for security.

Presumably using Google's mobile SDK makes it ignore the origin-check but I do not see an equivalent electron sdk.

**Comment by andreasnuesslein** [comment]
Sorry yes that worked perfectly with just putting `vector`.

Thank you for your help!
