### ISSUE TITLE
Account deactivation is not working if logged in using SSO

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#13310]
Step to reproduce:
- Connect to mozilla.modular.im, using SSO (for instance)
- Try to deactivate your account with any password (because you do not have password for your matrix account since its SSO) (settings/general/deactivate account)

This request is done:
/_matrix/client/r0/account/deactivate
with body
```json
{"auth":{"type":"m.login.password","user":"@alice:mozilla.org","identifier":{"type":"m.id.user","user":"@alice:mozilla.org"},"password":"leakPassword"},"erase":false}
```
and get a 400 with body:
```json
{"errcode":"M_UNKNOWN","error":"Password login has been disabled."}
```

UI Side, we got this:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/3940906/79876112-e8d3c500-83ea-11ea-9c65-e0bc5b5f965d.png">

I think the deactivation of the account should be disabled following the change password capability of the home server seems it's a bit related.

But we maybe should propose a way to deactivate the account anyway and to wipe out data if the user wants it to conform to GDPR directives.

**Comment by t3chguy** [comment]
Mozilla's Synapse doesn't yet support SSO for UIA.
https://github.com/matrix-org/synapse/issues/5667#issuecomment-610332077

**Comment by bmarty** [comment]
Also #12692 is a thing
