### ISSUE TITLE
Smiling Face With Tear emoji has turned into a box

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13316]
![](https://i.imgur.com/F5dg0s0.png)
Windows 10, Chrome 80, develop

**Comment by t3chguy** [comment]
This is a new emoji (v13) . We need to update our fonts.

**Comment by turt2live** [comment]
There's several emoji which are boxes, and some aren't joining together correctly: 
![image](https://user-images.githubusercontent.com/1190097/79918871-81b61080-83ea-11ea-96c8-102c57cac4bb.png)

This also affects staging

**Comment by jryans** [comment]
After a brief look, there actually are quite a few missing boxes like this, which is not ideal. It also sounds like it might be a while before we can reconstruct @ara4n's font build environment...

Could we somehow filter out the emoji we know we don't have font support for...? I know it's distasteful, but even just a static list in React SDK of known missing characters to filter out from the UI would be one approach.
