### ISSUE TITLE
"Remove recent messages" feature seems to count already removed messages for yourself

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/riot-web#13318]
### Description

"Remove recent messages" feature seems to accurately track how many messages have been loaded for **other users**. However, it seems to double-count already removed messages for yourself.

For example, if you use "Remove recent messages" for another user, and all the messages get removed, and then you try using "Remove recent messages" again, you will get a pop-up message saying "No recent messages by ____ found. Try scrolling up in the timeline to see if there are any earlier ones." This is the expected behavior, since there are no more messages that have not already been removed.

However, when trying to remove your own recent messages via the same process, your messages which have already been removed seem to be counted again by "Remove recent messages."

### Steps to reproduce

- Go to channel
- Open members pane
- Click on own icon
- Click on "Remove recent messages." Note the number of messages to be removed.
- Wait for all messages to be removed (watch the striped barrier turn solid)
- Click on "Remove recent messages" again. Notice the number of messages to be removed is the same.

The expected behavior is that the messages that have already been removed would not be counted again.

It's unclear whether the messages which have already been removed are merely counted, or if they are actually added to the queue for removal again, and wasting server resources or something like that.

Logs being sent: yes/no

### Version information

- **Platform**:  desktop?

For the desktop app:

- **OS**: Linux Mint 19.3
- **Version**: 1.5.15

**Comment by catscratchedme** [comment]
An educated guess based on the # of redaction messages sent out:

It seems like using "Remove recent messages" on yourself also attempts to remove any redaction messages that you sent out.

This leads to a never-ending loop of removing redaction messages and sending new ones.

**Comment by t3chguy** [comment]
Yup, you got the nail on the head: https://github.com/matrix-org/matrix-react-sdk/blob/719faed2ff50e3bb0dca2a827fa6c73e174b2d84/src/components/views/rooms/MemberInfo.js#L367
