### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by ravindrsharma99** [vector-im/riot-web#13326]
Can i use my website username and password for logging into RIOT ?

**Comment by t3chguy** [comment]
Riot as per https://matrix.org/docs/spec/client_server/r0.6.0#module-sso-login supports SSO and CAS login. Its up to the Matrix server (Synapse) to expose this. Additionally Synapse supports LDAP and other password providers.

For future support queries please use https://matrix.to/#/#riot-web:matrix.org

**Comment by ravindrsharma99** [comment]
@t3chguy  can you tell me where can i find server side code for sso.

**Comment by ravindrsharma99** [comment]
i have integrated SSO . But i autheticate user from my server to this server.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/
