### ISSUE TITLE
User count in audio/video group chats

### ISSUE THREAD

**Issue by koyuawsmbrtn** [vector-im/riot-web#13331]
### Description

If there is a way to do group voice chats without Jitsi (and directly in Riot) there should also a way to see how many users are in there with configurable limits (setting it to zero disables group voice chats). I recommend doing it like Discord does UI-wise with a quite nice way to highlight the current user count.

![grafik](https://user-images.githubusercontent.com/40538332/80028942-4567da80-84e6-11ea-96a0-4802d9a82ce2.png)

### Steps to reproduce

Nothing to reproduce. This feature is far from being implemented.

### Version information

This applies to all versions of Riot Web up until v.1.6.0

**Comment by t3chguy** [comment]
There is no such way other than Jitsi. See https://github.com/vector-im/riot-web/issues/3546 / https://github.com/vector-im/riot-web/issues/7487
