### ISSUE TITLE
Chat tabs move up when selected via keyboard navigation with Alt + Up/Down

### ISSUE THREAD

**Issue by tdemin** [vector-im/riot-web#13343]
### Description

If multiple chat tabs of a single category (i.e. rooms, direct messages, favorites) are open and are visible in the chat list on the left, moving between them with keyboard shortcuts (<kbd>Alt</kbd>+<kbd>Up</kbd>, <kbd>Alt</kbd> + <kbd>Down</kbd>) will pull chats you've moved through to the top of the category.

As chats promotion is not instantaneous (there's, like, a 100 ms delay before the chat is pulled to the top after it being selected), you can still navigate to the bottom of the chat list, but this will still mess up the ordering of the chat list.

### Steps to reproduce

+ Have a few chats of a single category, be it groups or direct messages, open (4 or 5 is enough).
+ Open the top chat of the category.
+ Try navigating to the bottom using only <kbd>Alt</kbd> + <kbd>Down</kbd>.

Works the same way in the reverse direction (from the bottom to the top).

Log: not sent due to being not needed

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.15

### Screenshots

Chat list before trying to scroll through with <kbd>Alt</kbd> + <kbd>Down</kbd>:

![image](https://user-images.githubusercontent.com/26599554/80110994-bf589c00-8598-11ea-8c9f-d0c9fe96b1f4.png)

Chat list after trying to scroll through:

![image](https://user-images.githubusercontent.com/26599554/80111094-df885b00-8598-11ea-86a8-9f999c76991b.png)

**Comment by t3chguy** [comment]
The rooms re-arrange regardless of whether you use keyboard shortcuts or your mouse. 

Closing in favour of https://github.com/vector-im/riot-web/issues/11743
