### ISSUE TITLE
Cross-Signing device wizard only accessible at application start?

### ISSUE THREAD

**Issue by TheJJ** [vector-im/riot-web#13355]
If existing logins are dismissed with the "later" button, I could not find a way to reach this menu again.
In the "Security & Privacy" setting section, there's no button or obvious way to set the trust of own sessions.

The list of sessions contains information like ID, name and last seen, but no button to perform the trusting procedure or a status of the trust state. There should be both for each device.

Is there even a way to run this trust wizard again? I could not find it. (Ah ok, you have to relaunch Riot...)

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/12857
