### ISSUE TITLE
I need help sorry if im doing it wrong im desperate 

### ISSUE THREAD

**Issue by b7553** [vector-im/riot-web#13356]
### Description

My  new passwords NEVER work and the username way of logging in is totally broken 
and I cant get into my new email because that password isnt working.

### Steps to reproduce
- set new password with typing or copypaste if youre paranoid like me
- log out with new password
- try to set new password using SAME copypaste or by typing it

I expect my new passwords to work without me having to send a verification email 
EVERYTIME TO CHANGE IT AGAIN back to the one it was before. 

Logs being sent: yes/no
no I cant I dont have access to my account

### Version information

- **Platform**: web (in-browser)

- **Browser**:  BRAVE Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
- **OS**: Windows 7 
- **URL**:  this is all I can give https://riot.im/app/#/room/!ZEDINXycSizYuCszsU:matrix.org
I saved the link if that helps at all.

For the desktop app:
same still doesnt work

**Comment by turt2live** [comment]
Setting new passwords appears to work for me (I've had to do this recently for one of my own accounts), so something else might be going wrong. Creating a temporary account and joining #riot-web:matrix.org for troubleshooting would be best.
