### ISSUE TITLE
Add default Debian distribution for desktop

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#13367]
Instead of endlessly creating new Debian distros for Riot Desktop each time one appears from Debian and Ubuntu, let's create a single `default` distro and suggest everyone should use that going forward. This has the nice side effect of also helping smaller distros where we've never managed to add their distro names. We'll need to keep all the existing ones around for a while / indefinitely so existing users continue receiving updates.

* [x] Add a `default` distro for Riot Desktop
* [ ] Update desktop download page to suggest it (happening in https://github.com/matrix-org/riot-im/pull/107)

**Comment by aaronraimist** [comment]
Would this fix https://github.com/vector-im/riot-web/issues/11929 and https://github.com/vector-im/riot-web/issues/13194?

**Comment by t3chguy** [comment]
Yup!

**Comment by t3chguy** [comment]
And https://github.com/vector-im/riot-web/issues/8095

**Comment by securerootd** [comment]
True - riot still does not have a release for Ubuntu 20.04 LTS (focal fossa) and it makes sense to use a default distribution since packages are basically same - there is no difference in packages

**Comment by jryans** [comment]
The `default` distro has been added. It should appear tomorrow with next nightly build. https://github.com/matrix-org/riot-im/pull/107 tracks updating the desktop page, including mentioning this new distro.

**Comment by jryans** [comment]
The `default` distro is now live, though for the moment it contains only `riot-nightly`. Riot 1.6 will also appear when released.

**Comment by shirishag75** [comment]
If I understand it, then the name has been changed to element. So what are the new instructions.
