### ISSUE TITLE
maintenance: update emojis to 13.0

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#13365]
emojibase-data@v5 brings emoji 13 definitions but we will also need to update our font to support them too

**Comment by ara4n** [comment]
Worth noting that Mozilla haven't brought twemoji-colr (https://github.com/mozilla/twemoji-colr/releases) in line with 13 yet, so we'd need to do this in our own fork over at https://github.com/matrix-org/twemoji-colr/tree/matthew/sbix (which is probably okay, given we did it for 12, but it means manually checking the new glyphs to check they got converted okay).

**Comment by ara4n** [comment]
also, twemoji 13 only was released 22 days ago: https://github.com/twitter/twemoji/releases
