### ISSUE TITLE
jitsi widget no longer goes into sidebar

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13369]
reproduced by pressing video call button in room with 3 people then switching a different room. marked as a release blocker but staging is unaffected so the 1.6. release is fine.

**Comment by turt2live** [comment]
I can't reproduce this. It should only pop into the sidebar when the conference has been joined, but not before. Is this consistent with what you're seeing @dbkr?

**Comment by dbkr** [comment]
Yep, I did join the conference but it's still not going into the sidebar. Can repro reliably here - I'll take a look.

**Comment by dbkr** [comment]
Ah, this happens if the URL you're hosting riot on doesn't qualify for using the built-in jitsi widget (in this case because my dev copy is on http rather than https).
