### ISSUE TITLE
Network infor for p2p audio/video calls

### ISSUE THREAD

**Issue by grinapo** [vector-im/riot-web#13363]
**Is your suggestion related to a problem? Please describe.**
For video/audio problems it would be good to see whether it's a bandwidth, a packet loss or something else (browser, local camera, audio driver, …) problem.

**Describe the solution you'd like**
Possibility to enable 

- bandwidth (send/receive)
- rtt
- packet loss

display on p2p audio/video calls.

A network problem indicator for the _masses_ (a red worrying admin face :worried: ) may be also useful.

**Describe alternatives you've considered**
No easy to use alternative. I could analyse the traffic with wireshark, which is a teribbly suboptimal solution.

**Comment by jryans** [comment]
I think this is broadly the same as https://github.com/vector-im/riot-web/issues/11511, would you agree?

**Comment by grinapo** [comment]
They both have a common motive of seeing what's wrong, but 11511 is about call establishing (if I understand correctly) and this one is for a working connection.

**Comment by grinapo** [comment]
lets continue over there. too much tickerts already.
