### ISSUE TITLE
Sophisticate toast interactions for new vs old sessions

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13361]
_For all Riot platforms. This may be captured but want to be doubly sure. _

The toasts for reviewing previous sessions should be distinct from reviewing new sessions as it's confusing for users.

Ideally, we should be comparing timestamps (even though they can be faked by malicious server admins, in the common case they're not, and we shouldn't hamper the UX for everyone) to display distinct copy, and perhaps display one generic 'Review all your sessions' toast which goes to Settings shown immediately after bootstrapping.

Some notes from @BillCarsonFr [via](https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$qp_anjV4vNTG5eNVbNxHg9g4oGqS1HbeFUesdWot2nw?via=matrix.org&via=vector.modular.im&via=uhoreg.ca):

> I've talked with a user that got confused with the security notices. Here is the scenario:
> He first sees the 'complete security' on his riotX (and it looks like that it's translated as 'full security', adding to confusion
> We have improved this already, but it was not clear for the user that he had to open another existing session (and why for?), I had to explain him that there will be a prompt on the other session also
> And just after completing verification, he sees another security notice just after, but this time saying that there is an untrusted session (pobably an old session)
> Looks like the user was confused by this second popup, because he thought he just did that (it's true that on mobile, these toaster are a bit similar)
> Maybe we should prompt only for 'new' untrusted session?
> For old ones, you should go to settings?

**Comment by jryans** [comment]
This is done now: we should different toasts for old and new devices.
