### ISSUE TITLE
clicking on jitsi widget in sidebar causes widget to disappear

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13370]
Whilst testing to see if https://github.com/vector-im/riot-web/issues/13369 was present on staging, it wasn't (the jitsi widget went to the sidebar correctly) but clicking on the bar above the widget (where it says 'Jitsi') caused the widget to disappear completely, like so:

<img width="395" alt="Screenshot 2020-04-24 at 15 06 29" src="https://user-images.githubusercontent.com/986903/80221847-c685b580-863d-11ea-9939-8be6ff236c3a.png">

I was clicking on the bar to try & get back to the room with the call in (I think there was some way like this to get back to the right room...)

**Comment by turt2live** [comment]
This is a regression on staging/develop.

**Comment by turt2live** [comment]
presumed fixed - if it happens again, please open a new issue.
