### ISSUE TITLE
Key Backup init screen copy is confusing for new homeserver users

### ISSUE THREAD

**Issue by benparsons** [vector-im/riot-web#13376]
<img width="701" alt="Screenshot 2020-04-24 at 17 28 42" src="https://user-images.githubusercontent.com/1197991/80235679-ef17aa80-8651-11ea-9e84-5bd8a38cb4c5.png">

"our server" here is confusing for people who just installed their own server and are now using it as the only user. Have just had a fresh-install user ask if "our server" meant *his* new server or matrix.org (or riot.im!)

**Comment by t3chguy** [comment]
This is a duplicate and fixed by cross-signing
