### ISSUE TITLE
Search in rooms doest work at all

### ISSUE THREAD

**Issue by Bib10311** [vector-im/riot-web#13385]
#13103# Description

Search feature doesnt work in any room on any device.

### Steps to reproduce

- Open any room
- press on search icon
- try to find something in history
- it always says: No results
https://gyazo.com/0f895d145e5a271cffb488bf2bbbdd18
### Version information

- **Platform**: desktop and mobile

For the desktop app:

- **OS**: Windows
- **Version**: 1.5.15

For the mobile app:
- **OS**: iOS
- **Version**: 0.10.5

**Comment by t3chguy** [comment]
Is the room you are searching encrypted?

**Comment by Bib10311** [comment]
yes, it is

**Comment by t3chguy** [comment]
That feature is coming in riot-desktop 1.6
Web will be unable to do it as a browser doesn't give you a secure enough environment to index encrypted events
