### ISSUE TITLE
FTUE: Invite dialog still doesn't give you any idea that you can invite people by email to an existing room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13382]
<img width="770" alt="Screenshot 2020-04-26 at 00 29 16" src="https://user-images.githubusercontent.com/1294269/80293187-0ab7a980-8755-11ea-818b-d9f62b1caf1e.png">

**Comment by t3chguy** [comment]
It does if you have an IS hooked up:

![image](https://user-images.githubusercontent.com/2403652/80306750-0a52f900-87bd-11ea-9a23-a7554b358ad5.png)

**Comment by nadonomy** [comment]
@t3chguy we can just vary the imperative so:

> Invite someone using their name, username (like <userID/>) or email address.

**Comment by t3chguy** [comment]
so drop the "or <share this room btn>" bit?

**Comment by nadonomy** [comment]
@t3chguy ah great point, so let's do:

`Invite someone using their name, username (like <userID/>), email address or <share this room/>.`
