### ISSUE TITLE
encryption is cumbersome for average users

### ISSUE THREAD

**Issue by ousia** [vector-im/riot-web#13387]
### Description

This comes from #13386. Sorry for wording the issue this way, but encryption is presented as problematic (at least) for average users in Riot.

The average user (non-tech oriented) doesn’t understand this:

> #### Never lose encrypted messages
> 
> Messages in this room are secured with end-to-end encryption. Only you and the recipient(s) have the keys to read these messages.
> 
> Securely back up your keys to avoid losing them.
> 
> Connect this session to Key Backup
> Not now
> Don't ask me again

And _Don’t ask me again_ might be clicked to avoid hassle. In most cases, none wants to loose messages. 

A similar issue arises in backing up sent messages:

> You'll lose access to your encrypted messages
> 
> Encrypted messages are secured with end-to-end encryption. Only you and the recipient(s) have the keys to read these messages.
> 
> Back up your keys before signing out to avoid losing them.

Again, the user may select the wrong option to simply log out.

### Steps to reproduce

1. Log in and go to a room using encryption.
1. Log out after sending a message in an encrypted room (without having sent the passphrase before).

How about directly prompting for the passphrase as the user starts a chat or goes to a room with encryption? (I guess that, once #13386 is fixed, passphrase wouldn’t be required again to backup sent messages from encrypted rooms in the same session, would it?) This is way better than explaining why they need to connect to key backup.

BTW, why there is no on/off button to enable encryption in every room by default? If encryption cannot be disabled, maybe asking for encryption for the newly created room would be an option.

### Version information

- **Platform**: web (in-browser).
- **Browser**: Firefox 66.
- **OS**: Fedora.
- **URL**: https://riot.im/app.

**Comment by t3chguy** [comment]
> BTW, why there is no on/off button to enable encryption in every room by default? If encryption cannot be disabled, maybe asking for encryption for the newly created room would be an option.

Its there on riot.im/staging and will be in the upcoming release. Most of the e2ee flows will be different than you saw.

![image](https://user-images.githubusercontent.com/2403652/80306438-3f5e4c00-87bb-11ea-8987-a23e89fc1a82.png)

**Comment by ousia** [comment]
@t3chguy, many thanks for your reply.

I’m afraid that I’m experiencing inaccessible encrypted messages from previous sessions (which had the passphrase provided to access the backup keys).

**Comment by ousia** [comment]
I’m reporting an issue with this problem.

**Comment by jryans** [comment]
Thanks for the feedback. We're well aware these flow are not ideal in release, which is why we've been working on it with upcoming cross-signing work. Much of this UX is changing drastically with cross-signing to be released with Riot 1.6 in a few days. I would recommend retesting once that's happened. Please file new issues for feedback with cross-signing.
