### ISSUE TITLE
Set Up Encryption toast wording error

### ISSUE THREAD

**Issue by notramo** [vector-im/riot-web#13397]
![image](https://user-images.githubusercontent.com/26059643/80357060-ad1d7d00-887a-11ea-84f4-4b5e63d41dc1.png)

**It doesn't upgrade anything. It isn't set up yet.**
It would be better:
![image](https://user-images.githubusercontent.com/26059643/80357162-d63e0d80-887a-11ea-98ec-80b9dfff5986.png)

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/13231
