### ISSUE TITLE
Rename 4S to Server Side Encrypted Secret Storage

### ISSUE THREAD

**Issue by notramo** [vector-im/riot-web#13393]
New users not familiar with cryptography doesn't know what a "secret" is. **Also the name doesn't indicates that it is an encrypted thing (_and they have to use a STRONG password_).** It have to be explained (among other things that are **not** trivial for them) that it is an encrypted storage. This makes FTUE worse.
Maybe __Server Side Encrypted Storage__ would be sufficient?

**Comment by t3chguy** [comment]
Where do you see it coming up in the ui? Is it still there on riot.im/staging?

**Comment by notramo** [comment]
I don't see exactly this in the UI. I opened another issue for the UI.
