### ISSUE TITLE
Integration shown despite integration manager disabled in settings.

### ISSUE THREAD

**Issue by cloudyfuel** [vector-im/riot-web#13403]
### Description

The integration in question is etherpad on scalar. I accepted integrations with a plan to disable them soon after, there's no other switch that I can find other the one in general settings and that one is set to disable. Cache cleaned, re-logged, Etherpad still shown.

### Steps to reproduce

Accept integration manager's licence and then disable it in settings? I stopped this bug only accidentally.

### Version information

- **Platform**: desktop

- **OS**: Debian
- **Version**: current

**Comment by turt2live** [comment]
This is working as intended - the integrations settings disable *adding* integrations, but do not prevent them from being shown.

**Comment by cloudyfuel** [comment]
@turt2live How do I opt-out of using integration manager then? Couldn't find anything and so such option is certainly a dark pattern. Sounds like there should be another option in general settings.

**Comment by turt2live** [comment]
There is an option:
![image](https://user-images.githubusercontent.com/1190097/80508516-63de3380-8935-11ea-8442-a52662590910.png)

The switch on the right side turns it off.
