### ISSUE TITLE
Replace multiple unverified session toasts with a single toast to check all 

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#13400]
We've decided it's a better experience to show a single toast for all unverified sessions (no matter the number of them), rather than the current toast per session system.

On web, the new single toast should take you to your user info panel to take action (since the Settings version doesn't exist yet). If that's somehow not possible for users not in any rooms yet, show an error modal for this case.

Design coming today from @nadonomy.

**Comment by t3chguy** [comment]
> If that's somehow not possible for users not in any rooms yet, show an error modal for this case.

We can show a userinfo panel without an associated room, e.g http://riot.im/app/#/user/@x:riot.ovh

**Comment by nadonomy** [comment]
Copy is here: https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=4592%3A104
