### ISSUE TITLE
Refreshing riot while offline can cause keybackup warnings?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13404]
see rageshake

> Lost internet, after it returned and I refreshed Riot it had disconnected from keybackup

**Comment by jryans** [comment]
@Twi1ightSparkle Where did you see evidence of key backup being disconnected? At the top of the room timeline, or in settings...?

**Comment by Twi1ightSparkle** [comment]
> @Twi1ightSparkle Where did you see evidence of key backup being disconnected? At the top of the room timeline, or in settings...?

The "Connect this session to key backup" appeared. Was not a new session. I entered my key backup password and confirmed with my account password I think. It finished up with a modal "3456 (something like that) keys restored"

**Comment by jryans** [comment]
> The "Connect this session to key backup" appeared.

@Twi1ightSparkle Okay, but where did it appear? At the top of the room timeline, or in settings...? (They each use different approaches to check status, so would help to know which.)

**Comment by Twi1ightSparkle** [comment]
> @Twi1ightSparkle Okay, but where did it appear? At the top of the room timeline, or in settings...? (They each use different approaches to check status, so would help to know which.)

It was the large one that appear on top of the room timeline. I believe the one that appears on new accounts asking if they wanna set up key backup

**Comment by jryans** [comment]
Great, thanks for the detail. I believe we need to handle network errors in the `RoomView` code that shows this backup warning.
