### ISSUE TITLE
Add link from Settings to user info panel to verify devices

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#13401]
As a temporary measure, let's add a link from Settings to your own member info for device verification, so that users looking for this in Settings left confused. (We do plan to update Settings with verif buttons, but that's post-release.)

**Comment by nadonomy** [comment]
Quick design comp here: https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=4592%3A134
