### ISSUE TITLE
Vector attempts to load thumbnail for SVGs, but Synapse does not support SVG "thumbnailing".

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#1341]
As described, plus it does not make sense to generate thumbnails for SVG.

**Comment by ara4n** [comment]
This is more a Synapse bug - https://matrix.org/jira/browse/SYN-344, and I'm afraid I coincidentally fixed it last night in Synapse in: https://github.com/matrix-org/synapse/commit/2c838f6459db35ad9812a83184d85a06ca5d940a - sorry!

**Comment by ara4n** [comment]
Had to back this out in https://github.com/matrix-org/synapse/commit/bd77216d06518ace2ec6213aa0ac0c834e923456

**Comment by ara4n** [comment]
this has been fixed by using the clientside-generated thumbnail (if one exists)
