### ISSUE TITLE
Main timeline area is blank when viewing own profile from e2e toast

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13421]
Thinking out loud: wondering if we should show home.html instead?

**Comment by jryans** [comment]
It's possible to do, but for the moment, I'm consider this low priority, esp. since we're switch back to specific toasts for new devices.

**Comment by nadonomy** [comment]
Yup, definitely low priority. Also marking as `needs-design` as this may become redundant as we implement more ideal user journeys.
