### ISSUE TITLE
Automatic leaving of upgraded rooms is more obtrusive than helpful

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13429]
It seems like more and more people are running into issues where they want to leave the old version of the room (which may very well be a hopeless effort depending on room version), but Riot tries to help and ends up making them leave *all* versions of that room. We should consider disabling the behaviour when not looking at the most-current version of the room, or possibly expose a checkbox for it.

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/10380 (has 6 thumbs)
