### ISSUE TITLE
Settings link to user profile uses incorrect link styling

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13420]
<img width="496" alt="Screenshot 2020-04-28 at 13 27 21" src="https://user-images.githubusercontent.com/4626865/80487420-acf1b000-8954-11ea-986d-6566bc09f136.png">

Should be green & not underlined.

**Comment by jryans** [comment]
@nadonomy Just to be clear, most links throughout settings are currently blue and underlined, only the only in Analytics section is green and non-underlined. Should they all be changed?

**Comment by nadonomy** [comment]
@jryans if it does something in the app it should be green & if it's an external link it should be blue.
