### ISSUE TITLE
Failure to restore key backup on login

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13428]
Despite entering 4S passphrase during login, keybackup wasn't restored. I had to manually enter the 4S passphrase again in settings to make it work.

**Comment by jryans** [comment]
@ara4n I suspect this is related to double key backup creation, which we have since fixed on develop, and should be present in the latest build you're testing. Can you re-test again?

**Comment by jryans** [comment]
No new info, and I don't believe we've seen more reports of this, so closing for now.
