### ISSUE TITLE
[Jitsi Call] ICE failed add TURN server

### ISSUE THREAD

**Issue by magic-debian** [vector-im/riot-web#13426]
### Description

On my homeserver riot client when I try to make a call with also my homeserver jitsi I get the following errors on the developer console :

`ICE failed, add a STUN server and see about:webrtc for more details`

`Failed to get URL preview: Error: CORS request rejected:`

Now from what I remember there is no need to install a STUN server in such setup (A VPS with a synapse server, a riot client and a jitsi server). So how come I get this error ?

### Steps to reproduce

Log in/create two accounts at riot.manusept.fr
Make a call between those two users without using jitsi.matrix.im server (jitsi.manusept.fr instead)
The call will be made but there wont be no audio nor video. But you can accept the phone call

Logs being sent: yes/no

### Version information

The same issue (no video or audio) will happen on the riot app too (but I don't see anything in the logs)

Web browsers are 
Chromium Version 80.0.3987  -> Debian Buster
Chrome Version 81.0.4044 -> Windows 10
Riot Web version 1.5.15 (on the server) -> Debian Buster

Urls are
riot.manusept.fr
jitsji.manusept.fr

Installation mode
https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi

(logs on the way)

**Comment by turt2live** [comment]
This sounds like a configuration error - visit #synapse:matrix.org for troubleshooting.

**Comment by magic-debian** [comment]
Oh okay, sorry for the bothering then
