### ISSUE TITLE
Reset option on bootstrap cross-signing dialog results in error

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13436]
`Resetting secret storage unimplemented` and the dialog closes, leaving behind a single error of 'Error: Secret storage access cancelled'

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/80551457-c1e43880-8980-11ea-8808-be0cbb42a083.png)

**Comment by turt2live** [comment]
@jryans not sure if this is a release blocker per-say, but it feels important enough to at least land on some radar somewhere for triage.

**Comment by jryans** [comment]
Hmm, agreed that's an unfortunate trap we've left lying around. I'll try to sort something out here.
