### ISSUE TITLE
Re-using tab for email verification link results in 'we have sent an email to <blank space>'

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13434]
Presumably at this step it should be something like 'please wait while we verify your request'

**Comment by foldleft** [comment]
I'm not sure where to start on this; is the string actually `This invite to %(roomName)s was sent to %(email)s`?

**Comment by foldleft** [comment]
Looks like this message is displayed by `RoomPreviewBar` when

```
                if (this.state.threePidFetchError) {
                    return MessageCase.OtherThreePIDError;
                } else if (
                    this.state.accountEmails &&
                    !this.state.accountEmails.includes(this.props.invitedEmail)
                ) {
                    return MessageCase.InvitedEmailNotFoundInAccount;
                } else if (!MatrixClientPeg.get().getIdentityServerUrl()) {
                    return MessageCase.InvitedEmailNoIdentityServer;
                } else if (this.state.invitedEmailMxid != MatrixClientPeg.get().getUserId()) {
                    return MessageCase.InvitedEmailMismatch;
                }
            }
```

Specifically I think `MessageCase.InvitedEmailMismatch` so next place to look is `invitedEmailMxid`

**Comment by turt2live** [comment]
Ah, this is on the login page sorry. I've been meaning to get screenshots but have failed.

**Comment by foldleft** [comment]
ah, I was down the wrong rabbit hole entirely

**Comment by dbkr** [comment]
Fwiw I'm not sure this has anything to do with using the same tab, I think it's just a thing that happens when matrix.org is slow enough that you see the email UIA component before it's verified that you've clicked the link.

**Comment by turt2live** [comment]
I wasn't able to reproduce this on matrix.org when using multiple tabs :(
