### ISSUE TITLE
Toggle switch for setting round or square avatars/buttons/pills/et cetera …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13446]
In regards of design and theming, it would be amazing to give the user (or, at least, custom theme author) to define if they want to have rounded or rectangular elements in riot-web.

It could be implemented rather “quick and dirty” by adding simply ` * { border-radius: unset; }` or `* { border-radius: unset !important; }` … but I guess there’s also a much nicer solution to this.

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/riot-web/issues/9058
