### ISSUE TITLE
split config.json from bundle.js to make Vector easier to package

### ISSUE THREAD

**Issue by hurzelmann** [vector-im/riot-web#1344]
load the config at runtime:

this would make it possible to make a distribution package without a config.json.
Making a dsitribution package that a webmaster can put on a webserver would increase the user acceptance.

**Comment by ara4n** [comment]
I guess the way to do this would be to separate config.json from bundle.js to make it easier for packages to customise.  Agreed it'd be nice to have.

**Comment by DanielDent** [comment]
Unless I'm mistaken, this issue was resolved in #1516 and can now be closed.

**Comment by t3chguy** [comment]
@DanielDent yep thanks
