### ISSUE TITLE
Images don't seem to be bound when viewing them anymore

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13448]
### Description

Someone sent the following image:

![image](https://user-images.githubusercontent.com/1342360/80627581-19011080-8a48-11ea-8e1c-de148dc64006.png)

Clicking on it shows me:

![image](https://user-images.githubusercontent.com/1342360/80627629-228a7880-8a48-11ea-8b8a-b38485e015d5.png)

I can scroll down to reveal more of the image, but some is clipped at the top (notice the scrollbar), which I can't scroll up to see.

[Image for your testing](https://user-images.githubusercontent.com/1342360/80627694-359d4880-8a48-11ea-940b-f54df3cebf15.png)

Logs being sent: yes

I've noticed this happening with other images for a few days now and thought it was a new feature, but this is the first time I've been unable to view some of the image, so maybe it's a bug.

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This feels like it might be a result of the scaling work, but not sure if the regression is that recent or not.

**Comment by anoadragon453** [comment]
I think it is recent. Notice it somewhat often now and only in the past few days.

**Comment by jryans** [comment]
@turt2live I guess this is a regression then?

**Comment by turt2live** [comment]
I believe so, but haven't had a chance to confirm (and probably won't for a while)

**Comment by anoadragon453** [comment]
Aw yiss, this was bugging me hard. Thank you!
