### ISSUE TITLE
Don't show reaction count when there's only one reaction

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13440]
**Is your suggestion related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/1342360/80593299-dd028700-8a18-11ea-8fd4-f01f383c4427.png)

There's not really a need to show `1` if this is the first instance of the reaction. The fact it's there implies that at least one reaction of this type was sent.

**Describe the solution you'd like**

The vote count should only show once at least 2 reactions of a given type have been sent.

**Describe alternatives you've considered**

This probably only applies to text-based reactions, but I'd like to keep those.

**Additional context**

The screenshot comes from a bot that will give you status updates in the form of reactions to your command messages. It's pretty cool.

**Comment by turt2live** [comment]
fwiw: the bot chose those words so it would be mildly less confusing when there was a number. About an hour of work was put into picking words which made some amount of sense when a number was suffixed.

Just mentioning as a datapoint for why it could be good to remove the number.

**Comment by t3chguy** [comment]
Seems like this is not a thing Product/Design wants :(

**Comment by anoadragon453** [comment]
Aw, sad times.
