### ISSUE TITLE
Please add config option for disabling invite only padlocks

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#13455]
For many of the reasons pointed out by Erik in #12148 I would really like to be able to turn off the invite-only padlocks.

**Comment by pwr22** [comment]
I'd rather the symbol get changed to be a bit clearer myself.

**Comment by Cadair** [comment]
@pwr22 that's more the discussion in #12148 this issue is just for the addition of a flag in the settings and not thoughts on about the feature.

**Comment by turt2live** [comment]
We've changed the icon, so this no longer should be needed.
