### ISSUE TITLE
Stylise macOS consistently

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13459]
We currently stylise macOS as Mac OS in device names, which we should update. It'd be worth searching our repo/translation strings/etc to ensure we use macOS everywhere.

**Comment by jryans** [comment]
I recall looking at this briefly... It's actually more interesting that it sounds, as we don't have either string in our code directly. Instead, we take the browser's user agent (e.g. `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:77.0) Gecko/20100101 Firefox/77.0`) and parse bits out of it, which is where the "Mac OS" is coming from.

I agree it should be updated though, it has bothered me in the past as well. I suppose we could replace "Mac OS" -> "macOS" when we find it in the parsed UA value.
