### ISSUE TITLE
Audio and Video not working with point to point call from different network

### ISSUE THREAD

**Issue by jerryn-acceleron** [vector-im/riot-web#13468]
I have setup a riot server in my lab. Here chatting, conference call are working properly. Also point to point call is working if both the parties are in same network or in LTE network. If parties are in different network, video and audio are not coming in point to point call... 
Please give me some suggestions. 
I followed these links for installation (https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi) and (https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md)

**Comment by turt2live** [comment]
You will need to set up a TURN server for your homeserver. If you're using Synapse, please visit #synapse:matrix.org

**Comment by jerryn-acceleron** [comment]
TURNserver is already installed in my setup. 
My server is connected via vpn. Is there any issue for TURN with VPN. Or any extra configuration that I have to take care.

**Comment by AlexDaniel** [comment]
Interesting. I'm seeing exactly this except that my setup was working for months. Pretty sure something was changed and I need to tweak something yet again, but I wonder what exactly…
