### ISSUE TITLE
Bots Are Showing Offline In Chat Room.

### ISSUE THREAD

**Issue by samsantiago89** [vector-im/riot-web#13476]
### Description

Giphy and Guggy Bots Are Showing Offline In Chat Room and not working. Would like to be able to send GIF's in chat room.

### Steps to reproduce

1. Install a home server using the following steps outlined in this article.

https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi

2. Configure a TURN server using the following guide.

https://meetrix.io/blog/webrtc/jitsi/setting-up-a-turn-server-for-jitsi-meet.html

3. Start a new direct message chat with another user.

4. Go into integrations and add Giphy or Guggy to the room (Non Encrypted).

5. Use "!giphy Hello or !guggy Hello" 

6. Check status of bot and its shows Offline.

7. Open a direct chat with the bot try the same steps. Use "!giphy Hello or !guggy Hello" and you will get the following error. 

@_neb_guggy:matrix.org
Failed to query Guggy: Failed to decode response (HTTP 522)

Describe how what happens differs from what you expected.

I am expecting a GIF image to appear on the screen instead I do not get a response or get the error listed above.

- **Platform**: web (in-browser) or desktop?

For the web app:

**OS**: Windows 10 
Riot Desktop App:
Versions
riot-web version: 1.5.15
olm version: 3.1.3

V40 ThinQ CellPhone Using Riot app from App store.

Iphone and Ipad tested as well same behavior using the Riot App.

The Matrix server is running on Ubuntu 19.10

**Comment by samsantiago89** [comment]
Screenshots:

![Screenshot_1](https://user-images.githubusercontent.com/64609368/80833580-b4f35f00-8ba3-11ea-8077-9b7305ccf745.png)
![Screenshot_2](https://user-images.githubusercontent.com/64609368/80833583-b6bd2280-8ba3-11ea-8054-d82345f1e8b1.png)
![Screenshot_3](https://user-images.githubusercontent.com/64609368/80833594-bc1a6d00-8ba3-11ea-8382-4f7f34a3a61a.png)

**Comment by turt2live** [comment]
matrix.org has presence turned off, and the bots you're using are from matrix.org

**Comment by samsantiago89** [comment]
Travis,

So eventually this is gping to start working or is there anything I can do
on my end?
