### ISSUE TITLE
"Could not load user profile" when leaving user profile

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/riot-web#13479]
### Description

Using the latest nightly, I get the following dialog:

![Screenshot from 2020-05-02 09-39-51](https://user-images.githubusercontent.com/77743/80858341-16293a00-8c59-11ea-9914-3407a4f98f9e.png)

when leaving my own user profile.

### Steps to reproduce

1. Go to "Settings -> Security & Privacy"
2. Click "verify them in your User Profile"
3. In the panel that pops up: Press the back button (`<`)

The above dialog shows up.

### Version information

- **Platform**: desktop?

- **OS**: Fedora
- **Version**: 2020050101

This is a custom flatpak build based on https://github.com/flathub/im.riot.Riot/pull/96, but with the newer `deb`-link and corresponding sha256 sum.

**Comment by turt2live** [comment]
Looks like your reverse proxy is altering the request before it hits Synapse. Visit #synapse:matrix.org for support.

**Comment by turt2live** [comment]
Turns out if I read the reproduction steps a bit closer it would have been trivial to reproduce.

**Comment by turt2live** [comment]
This doesn't affect the release, so removing urgency labels from it.
