### ISSUE TITLE
The "View Source" tool doesn't reflect further editing.

### ISSUE THREAD

**Issue by nesnera** [vector-im/riot-web#13471]
### Description

The "View Source" tool doesn't reflect further editing. It contains first submit only.

### Steps to reproduce

- send a post
- change it by edditing
- display its code by "View Source" tool

Describe how what happens differs from what you expected.

To see the code of the current content
![riot_view_source-2020-05-01](https://user-images.githubusercontent.com/1737463/80798877-b4f45e80-8ba5-11ea-95b1-69253e8b8de1.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop
  - riot-web version: 0e75b1b0db1a-react-c19338b1d3ea-js-e5b6a9f8cba5
  - olm version: 3.1.3

**Comment by jryans** [comment]
Hmm, yes, it would likely be more natural to default the primary "view source" to show the source of the last edit to match what's displayed.

For now, you can workaround by clicking on the "(edited)" to see the edit history, and each edit there has it's own "view source" button.

**Comment by nesnera** [comment]
Guys, "In testing" means it should work in [dev client](https://riot.im/develop) or not?

**Comment by t3chguy** [comment]
Yes.

![image](https://user-images.githubusercontent.com/2403652/84877509-83b1ee00-b080-11ea-92ae-286d4e2bcd27.png)
![image](https://user-images.githubusercontent.com/2403652/84877524-8876a200-b080-11ea-918a-cf7bd7bda8e8.png)
