### ISSUE TITLE
stickers are sent two times

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13470]
### Description

It seems stickers are sent two times on my system.

![image](https://user-images.githubusercontent.com/1029578/80798111-d81e0e80-8ba3-11ea-9b71-96397015e81f.png)

### Steps to reproduce

- send a sticker

Two stickers are sent instead of one.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**:  2020043001

**Comment by turt2live** [comment]
I can't reproduce this - does it happen for all stickers in all rooms or did it happen just this once?

**Comment by lub** [comment]
Hm, tried the same sticker in the same room and it seems to not happen anymore. strange
