### ISSUE TITLE
 Riot displays unread message counts at startup that it knows are incorrect.

### ISSUE THREAD

**Issue by bjherbison** [vector-im/riot-web#13477]
### Description

Riot displays unread message counts at startup that it knows are incorrect.

### Steps to reproduce

- Visit https://chat.mozilla.org/#/home or https://riot.im/app/ , read all the messages.
- Wait some time, take a walk, relax.
- Visit https://chat.mozilla.org/#/home or https://riot.im/app/ again and watch the left column.

The list of room shouldn't have any unread counts until correct counts are displayed. What actually happens is that counts from the previous session are displayed, then removed and replaced with the current counts.

And the bad information isn't from the end of the previous session (which would show just one count from the last room I was reading). The counts are often from the beginning or middle of the last session and show counts from many rooms I finished before I last closed the tab.

I just visited https://riot.im/app/ , cleared the counts for all the rooms, closed the tab, and revisited the site. Four rooms had unread message counts on first load, and then the counts went away.

Incorrect unread message counts should never be displayed.

Logs being sent: yes

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox Nightly 77
- **OS**:  Ubuntu with XFCE
- **URL**: https://riot.im/app/ and https://chat.mozilla.org/#/home .

**Comment by turt2live** [comment]
This is expected due to how Riot works. It only stores information every 5 minutes or so, which means it doesn't actually know the counts are incorrect until it asks the server for updated information.

**Comment by bjherbison** [comment]
I just discussed this on https://chat.mozilla.org/#/room/#synchronicity:mozilla.org .

Why is it expected that Riot will always give bad information to users at the start of a session and this behavior will never be possible to fix?

**Comment by t3chguy** [comment]
Because the only two ways to show the correct information would be to:

+ Disable offline mode and instead show a spinner until a connection is established and the server sync response is parsed.
+ Immediately update IDB with every single action that you do, synthesizing sync responses from the server, this is harder to do and additionally would slow down the app as IDB accesses are not cheap.
