### ISSUE TITLE
backgrounds of fallback avatars in pills in the composer have gone black

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13478]

**Comment by ara4n** [comment]
<img width="199" alt="Screenshot 2020-05-02 at 01 58 36" src="https://user-images.githubusercontent.com/1294269/80851252-78157f80-8c18-11ea-8bd1-38cf302aa568.png">

**Comment by jryans** [comment]
@ara4n This is for the case of user with avatar but can't be loaded due to network / server issues?

The case of user who has no avatar set at all seems to be working at least.

**Comment by nadonomy** [comment]
+1, am seeing this too.

**Comment by turt2live** [comment]
this sounds a bit like matrix.org being slow and causing requests to stack up, so the request for the image which runs the background there is blocked.

**Comment by turt2live** [comment]
oh, this is *only* in the composer.

**Comment by bwindels** [comment]
I assume this regressed in https://github.com/matrix-org/matrix-react-sdk/pull/4503, will have a look.

**Comment by bwindels** [comment]
Can repro in Firefox, the data url for the background gets a `../../` prepended and doesn't render.
