### ISSUE TITLE
Missing Ubuntu 20.04 release file for ppa

### ISSUE THREAD

**Issue by kristbaum** [vector-im/riot-web#13483]
### Description

Ubuntu 20.04 has been released, but there is no release file in the official Riot repo. It's missing [here](https://packages.riot.im/debian/dists/). Until it is added, I think no one can upgrade or install on the newest Ubuntu LTS (focal).

**Comment by kristbaum** [comment]
This was related I think: #11327

**Comment by t3chguy** [comment]
From v1.6 it'll use the 'default' distro and the package name will be riot-desktop
