### ISSUE TITLE
Здравствуйте я купил ключ, с того момента как купил я ждал исправление краша, но теперь у меня срок закончился и я даже не играл, написал модератору он сказал продлят но мне не продлили

### ISSUE THREAD

**Issue by said952727** [vector-im/riot-web#13494]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by said952727** [comment]
Здравствуйте я купил ключ, с того момента как купил я ждал исправление краша, но теперь у меня срок закончился и я даже не играл, написал модератору он сказал продлят но мне не продлили мой емаил почта arsamurzaev.1998@gmail.com

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/13497

**Comment by said952727** [comment]
WG3J3J3K2BMP8HLW29WG:NqTWrR59

**Comment by said952727** [comment]
Hello, I bought a key, from the moment I bought it, I was waiting for a crash fix, but now my deadline is over and I didn’t even play, I wrote to the moderator, he said it was extended, but my email didn’t extend me
