### ISSUE TITLE
Toggle switches jump instead of slide

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#13491]
This appears to be a regression on develop only so far (staging is okay).

**Comment by turt2live** [comment]
@jryans this isn't a regression in the shipped app - can we de-fire and remove release blocker from it?

**Comment by jryans** [comment]
After chatting a bit more with @turt2live, it's clear I've mixed up a few labelling concepts. 

It's not a blocker for the 1.6 release; with release-blocker I had only wanted to ensure it doesn't leave develop, but we don't have a great way to track the distinction. For now, we'll remove release-blocker since we only use it for the upcoming release.

As for fire, while it's not a great thing to ship, it's also not the end of the world either, so priority seems more appropriate.

Also, it would generally be better to allow the maintainer to triage and process these decisions, rather than surprising them with extra things out of the blue, so in the future I'll contact the maintainer instead of just adding labels like I did here.
