### ISSUE TITLE
Здравствуйте я купил ключ, с того момента как купил я ждал исправление краша, но теперь у меня срок закончился и я даже не играл, написал модератору он сказал продлят но мне не продлили

### ISSUE THREAD

**Issue by said952727** [vector-im/riot-web#13497]
Здравствуйте я купил ключ, с того момента как купил я ждал исправление краша, но теперь у меня срок закончился и я даже не играл, написал модератору он сказал продлят но мне не продлили

**Comment by said952727** [comment]
Здравствуйте я купил ключ, с того момента как купил я ждал исправление краша, но теперь у меня срок закончился и я даже не играл, написал модератору он сказал продлят но мне не продлили

**Comment by turt2live** [comment]
From the translation, it looks like your issue is elsewhere. Riot is not a paid service.
