### ISSUE TITLE
Replace session/account modal dialog notifications with a log view - or otherwise get rid of modals.

### ISSUE THREAD

**Issue by sirocyl** [vector-im/riot-web#13493]
**Problem:** Many account and session notifications, events and active cross-device actions (e.g., verification) require a modal dialog.

Modals are only ever able to be handled by the user in a "last-in first-out" nature, owing to the fact that they cover, and seize, all other UI but itself - *including prior modals.* Frustrating.

**Requirements to solve:** 
- The user should be able to handle such actions non-exclusively, in the order that they make sense to - not a strict "last-in-first-out".
- These actions and events should carry priority with them.
- Modal UX should be limited to immediate interruption of, and in response to, user actions - for example, "`You have an unsent message [Return] [Quit and discard]`" upon closing the window. They shouldn't be instantiated by passive actions from other devices, even those from the same user.

**Solutions considered:**
1. Combine what would've been these modals, and other "account activity" into a log/stream type list view. This is similar to a chatlog view but with a very distinct layout - I'd envision like a list of dialogs, with a title, message/description, and one or two quick actions. Clicking the dialog, outside of those action buttons, enlarges it/activates it to be a full-size modal.
2. Make modals (or, at least, almost all of them) movable, and non-exclusive.
3. When a modal is dismissed (closed, backed out of, clicked outside of) it goes somewhere that it can be returned - no action is taken, not even a "cancel" or "default" action.

**Example:**
Here's a screenshot of a stack of about 3 or 4 modals from requests for signing keys from when I signed in on the Riot X mobile app:
![Riot_Ys72P8KybS](https://user-images.githubusercontent.com/944067/80986685-e9168c00-8dfe-11ea-8410-32b99a4d5124.png)

**Comment by sirocyl** [comment]
I'm told that at least some of these modals have been replaced with toasts in development versions [here](https://github.com/vector-im/riot-web/issues/12230#issuecomment-623533003) - While they're an improvement, toasts are still one-dimensional. There is only one toast visible at a time, and there is no method to recall toasts from history, prior to the current one, from what I can tell. I could be wrong on that one, though.

**Comment by turt2live** [comment]
This is indeed fixed in the cross-signing work, so closing for that.

Toasts not being recoverable is largely https://github.com/vector-im/riot-web/issues/12857
