### ISSUE TITLE
Moderator can still post to upgraded (tombstoned) room

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#13502]
### Description

When upgrading a room, it gets deactivated and links to the new room via tombstone. A room Mod or Admin can still post to the old room.

### Steps to reproduce

- Be room Mod or Admin
- Upgrade room
- Go to old room
- Post

If a room is declared dead, it should stay dead.

Logs being sent: no

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.5.15

**Comment by turt2live** [comment]
This is entirely expected.
