### ISSUE TITLE
New riot version usability

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#13511]
Installed v1.6.0 today with some cross-signing. What is it BTW, how to use?! It asked me to enter new passphrase and returned new key to copy and save. So for now I have to store 4 passwords and keys:
- for account
- for local backup
- for the server backup (is it removed now or replaced with cross-signing?!)
- cross-signing

FOUR!!! This is madness from usability point of view!!! As a Viber or Telegram user I do not have any. Could we have only 1 password? Riot is unusable for common and even for advanced users if encryption enabled with such complex and uncertain mechanism. How private rooms will work now, is they are usable at all now?!

**Comment by ara4n** [comment]
you have two passwords; your login and server-backup/cross-signing (which is the same).

we'll publish guides shortly.

**Comment by turt2live** [comment]
For support it's best to ask in #riot-web:matrix.org as we don't always see new issues. Please watch for the guides Matthew mentions coming shortly.

**Comment by akontsevich** [comment]
> you have two passwords; your login and server-backup/cross-signing (which is the same).

But why riot gave me new keys for cross-signing then if it is the same?! Why do I need these keys then - old and new?! Which to delete?! That's crazy!

**Comment by akontsevich** [comment]
I have 2 passwords and 2 long keys which Riot asked me to save. Why do I need them at all?! That is a delirium!

**Comment by akontsevich** [comment]
I do not know what passwords to use and when. And I'm an advanced user!!! And what about regular users?! There is **ZERO** chance anybody switches from Viber or Telegram!!!!

**Comment by akontsevich** [comment]
> For support it's best to ask in #riot-web:matrix.org as we don't always see new issues. 

I can't enter the room - just see infinite spinner. This f..g Riot is completely unusable!!! Wish you luck with this complete failed project.
