### ISSUE TITLE
Repeated requests to verify riot web session

### ISSUE THREAD

**Issue by PatrickRose** [vector-im/riot-web#13520]
### Description

Updated Riot Web to the latest version (at riot.im/app), and clicked "Verify". After verifying with my recovery password, I was asked to verify the session again.

I'm also unable to verify my RiotX session (though I did use my recovery key)

Log: sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 81.0.4044.138
- **OS**: Windows
- **URL**:riot.im/app

**Comment by NHAS** [comment]
Not entirely certain this is the same issue. But people on our self hosted synapse instance that have updated to 1.6.0 have lost their verification with all 30 so people in the room.

**Comment by turt2live** [comment]
@NHAS that would be a different issue, though it sounds expected. The new encryption stuff requires everyone to re-verify (sorry, but it's for the better).

**Comment by NHAS** [comment]
@turt2live Well, thats rather unfortunate. Is there a PSA about that somewhere, so I can give it a read? (And send it around as a reason to why we have to reverify)

Thanks

**Comment by turt2live** [comment]
We should have a blog post out soon that explains all of this in detail.

**Comment by PatrickRose** [comment]
Just had another go today - it might be in the debug logs I've already sent but my logs say:

```
Error: "Key type master from getCrossSigningKey callback did not match"
    getCrossSigningKey https://riot.im/app/bundles/9f769ac7a648e2ec9507/vendors~init.js:2
```

Would it be worth submitting another log or have you got enough?

**Comment by turt2live** [comment]
Yea, from what I can see this looks like https://github.com/vector-im/riot-web/issues/13542 - closing in favour of that, though someone more experienced might want to take a look.
