### ISSUE TITLE
Add option to disable room list categories in favour of one continuous list (self sorted?)

### ISSUE THREAD

**Issue by aral-matrix** [vector-im/riot-web#13521]
**Is your suggestion related to a problem? Please describe.**
The categorization of the room list(s) forces individual scroll areas with a lot of display space wasted to category names: Favorites, Direct Messages, Rooms, Low Priority, Historical

Each of those categories has it's own scroll area, limited to a subsection of the (vertical) application window size. This requires frequent re-sizing of the category areas, is counter-intuitive and unpractical.

Related issues:
https://github.com/vector-im/riot-web/issues/6982
https://github.com/matrix-org/matrix-react-sdk/pull/4531

**Describe the solution you'd like**
It would be highly beneficial if the categorization could be toggled (turned off) and all rooms (because, in effect, everything is rooms in the end) could be displayed in one single, continuous list.

This list should have sorting options:
- Manual sort (persistent, the user can move rooms up/down)
- "category" sort: User can choose the sequence in which rooms are displayed in the list based on their category (e.g. Favorites, then Direct Messages, then Rooms). Within categories, the manual sorting order applies

An SQL example of how the sorting could look like:
- manual sort --> ORDER BY roomSortId
- category sort --> ORDER BY categorySortId, roomSortId

**Describe alternatives you've considered**
Categories could be expanded to the needed size (to display all elements), so that the later categories are off-screen, and a central scrolling function could allow to scroll the room list down to see the entries in the desired category (ICQ/Pidgin contact grouping style)

**Additional context**
n/a

**Comment by toger5** [comment]
I think this is one of the biggest ux flaws. It also looks bad when there is a lot of cut of text so its also a UI issue.
In #8042 this is mentioned as well. I really would love to see this fixed.
Fractal does it really well. I think in the way you described it.

**Comment by turt2live** [comment]
oh hey, we do have an issue for this. It's currently being looked at, though is a bit far away.

**Comment by turt2live** [comment]
We've effectively done this with the new room list. Closing as the design is largely implemented, and in the feature queue for landing on mainline.
