### ISSUE TITLE
the lock sign on unencrypted rooms

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13529]
1.6.0 starts show the lock sing on room that are not encrypted
![image](https://user-images.githubusercontent.com/14617699/81137716-68739f00-8f68-11ea-9b79-b3ebc22e7939.png)
![image](https://user-images.githubusercontent.com/14617699/81137739-76292480-8f68-11ea-8cf9-cf221e12ab08.png)

**Comment by dawidpotocki** [comment]
This lock means "invite only" and not "encryption", it doesn't make any sense, but that's how it is.
I don't know why anyone would even need that information here.

**Comment by 532910** [comment]
so "invite only" must use other sign, as lock is for "encryption" or not be shown at all

**Comment by 532910** [comment]
> I don't know why anyone would even need that information here.

I totally agree!

**Comment by turt2live** [comment]
Effectively #12148

**Comment by 532910** [comment]
It's a big omission and fail that 1.6 was released before this fix.
