### ISSUE TITLE
Community filter panel doesn't work on develop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13530]
Appears fine on /app

**Comment by turt2live** [comment]
selections work, but the actual filtering yields no rooms being shown - it should show something.

**Comment by t3chguy** [comment]
![filt](https://user-images.githubusercontent.com/2403652/81281302-91239380-9051-11ea-9f9b-418c337db88e.gif)

**Comment by t3chguy** [comment]
possibly related to https://github.com/vector-im/riot-web/issues/12977

**Comment by turt2live** [comment]
on the other hand, there's 10 missing rooms here:
![image](https://user-images.githubusercontent.com/1190097/81316731-2ec69500-9049-11ea-865e-f0ce2b7eff51.png)

**Comment by t3chguy** [comment]
I tried to figure out what may have been happening but without being able to reproduce it that is proving difficult.

**Comment by turt2live** [comment]
hmm, looks like the community in my screenshot and the one I used to test the original complaint are both corrupt beyond recognition. Looks to be a Synapse problem, but not really worth reporting as the implementation is being replaced.
