### ISSUE TITLE
Messages from unverified devices no longer marked as untrusted

### ISSUE THREAD

**Issue by rudis** [vector-im/riot-web#13532]
### Description

This worked in 1.5 (alert icon) but not in 1.6. This is a security issue because one can no longer differentiate trusted from untrusted messages, circumventing one of the goals of device verification.

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian
- **URL**: self-hosted, 1.6.0

**Comment by turt2live** [comment]
Yes they are? What indicates that they aren't?

https://blog.riot.im/e2e-encryption-by-default-cross-signing-is-here/ has details on the new UX.

**Comment by rudis** [comment]
Well, I didn't see them. I was chatting with another user with multiple devices. We verified only two of them (due to another bug which didn't let us verify the user itself) and messages from a third device was not flagged as untrusted.

**Comment by turt2live** [comment]
This is expected - you've verified the whole user, not their devices. See the blog post for more information.

**Comment by rudis** [comment]
No, I didn't. The user still had a black shield and not all devices of the user were marked as trusted. In addition the user could not read any messages sent to devices which were not listed as verified because I set the "Never send encrypted messages to unverified sessions from this session" option.

**Comment by t3chguy** [comment]
Black shield means you have not verified the user
Green shield means you have verified the user & they have verified all their devices
Red shield means you have verified the user & one of their devices is unverified by them

**Comment by rudis** [comment]
Yes, I did not verify the user (because of a separate bug I still have to replicate). However, I verified a single device. Now I'd expect messages from all other devices to be marked as untrusted. And at least for the "Never send encrypted messages to unverified sessions from this session" feature this is also working. The other device cannot read my messages. But messages from that device are not marked. That's what this bug is about.

**Comment by rudis** [comment]
Oh, and it's quite easy to replicate even without any verification. Just join a direct chat of an unverified user. All messages from this user are not marked as untrusted when in fact they are because I didn't verify the user or any device.

**Comment by turt2live** [comment]
Yes, the blog post explains all of this.

**Comment by rudis** [comment]
The only thing I could find in the blog post is "the user’s shield going red is your cue to warn you that badness may be happening." Did I miss anything else?

However, this is not happening if you didn't verify the user (at least in my case). This is problematic when talking to somebody who does not yet support cross-signing (because you can only sign single devices then). And it's also problematic if the user verification failed (which is a separate bug) but I was able to verify a single device.

**Comment by turt2live** [comment]
It's probably best to troubleshoot this in #riot-web:matrix.org as it doesn't seem like anything is going wrong per-say, just unexpected.

**Comment by rudis** [comment]
That might be. I'm already joined and explained my situation.

But my main issues is that this issue doesn't permit safe messages with non cross-signing users anymore. Because I can never know if messages are really from those devices I trusted.
