### ISSUE TITLE
How to disable encryption for direct messages permanently

### ISSUE THREAD

**Issue by anilk9096** [vector-im/riot-web#13538]
Hi,

Riot web was very nice. Thank you for riot . I want to disable encryption permanently while creating direct messages and groups . please suggest 

Note : My usage was internal and not federation .

**Comment by jryans** [comment]
This sounds the same as https://github.com/vector-im/riot-web/issues/13539, so let's track it there.

**Comment by logmeonce11** [comment]
To permanently disable encryption for direct messages, you’ll need to navigate through your messaging app’s settings and adjust the encryption preferences. For a detailed guide on [how to disable end-to-end encryption in messages](https://logmeonce.com/resources/turn-off-end-to-end-encryption-android/).Remember, disabling encryption can impact the security of your conversations.
