### ISSUE TITLE
Desktop notifications aren't working

### ISSUE THREAD

**Issue by GenaIT** [vector-im/riot-web#13541]
Hi guys.
After today's update of the Application Riot
push notifications stopped coming (from group or private messages)
OS: Win Server 2012R2

**Comment by t3chguy** [comment]
riot-web doesn't have push notification support.
push notifications are only in the mobile apps.

Perhaps you are simply using the wrong terminology, try to rephrase your issue.

**Comment by GenaIT** [comment]
I do not use riot web.
riot is installed on the desktop
and before today's update of the application, notifications came.

**Comment by t3chguy** [comment]
riot-desktop is riot-web in electron (embedded chromium)
the code is identical, and it still doesn't support *push notifications*

Desktop Notifications however should be supported in Settings.,
![image](https://user-images.githubusercontent.com/2403652/81167373-04170680-8f8d-11ea-94c0-55ac1d15e4d5.png)

**Comment by GenaIT** [comment]
I repeat!
Until today's Riot Application Update, everything worked, everything is turned on in the settings.
No notifications!

**Comment by t3chguy** [comment]
Ok. Next time use the issue template.

**Comment by turt2live** [comment]
@GenaIT please submit logs from Settings -> Help for this issue.

**Comment by GenaIT** [comment]
> @GenaIT please submit logs from Settings -> Help for this issue.

I sent logs

**Comment by GenaIT** [comment]
Will updates be released to fix the problem?

**Comment by t3chguy** [comment]
You are the only user reporting this issue so far, so unlikely unless it is clear that it is a Riot issue.

**Comment by GenaIT** [comment]
I don’t think that anyone has problems with this, we have already done tests on other OSs, and we don’t get push notifications anywhere
there are two options
or nobody uses the desktop version of Windows
or just don't report on the problem.

**Comment by t3chguy** [comment]
I personally use Windows and use Riot Desktop without any issues with Notifications.

**Comment by t3chguy** [comment]
Both reports of this issue come from the same homeserver, maybe something changed on that end?

**Comment by GenaIT** [comment]
Well, so what could be the problem then
Notifications are all included!
![Screenshot_8](https://user-images.githubusercontent.com/64897721/81573495-3f5e6e80-93ad-11ea-905e-bd729ffc8466.png)
On Windows itself, notifications are also allowed
but after we updated RIOT to version 1.6.0 they stopped coming.
Coincidence? I don’t think so.

**Comment by GenaIT** [comment]
> Both reports of this issue come from the same homeserver, maybe something changed on that end?

No, there were no changes on the server.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/81574126-4e3d2500-939d-11ea-8d78-416063073eb2.png)

They happily work here

**Comment by GenaIT** [comment]
Then I still do not understand what the problem is.

**Comment by GenaIT** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/64897721/81581835-f3fd8d80-93b7-11ea-8d44-20b26dc25345.png)
maybe off topic.
but for some reason he does not recognize the signs "+", "-", "*"
tell me where to dig?

**Comment by t3chguy** [comment]
Riot uses https://spec.commonmark.org/dingus/ for markup (markdown)

For future support queries like such use the Matrix Room https://matrix.to/#/#riot-web:matrix.org

**Comment by nraiha** [comment]
I have the same problem. I do not receive any notifications, not depending on if the riot app is hidden in tray or not.

I am using debian buster with 4.19 kernel and I have installed riot desktop with aptitude from riot deb. I am using dunst as my notification-daemon.

**Comment by GenaIT** [comment]
@t3chguy 
All the same, the problem exists.
After updating Riot to version 1.6.0
notifications on Windows family OS which are lower than the version stopped coming
Windows 10
and Windows Server 2016

**Comment by jryans** [comment]
@GenaIT So it does work in Windows 10 / Windows Server 2016 then?

Our current [support policy](https://github.com/vector-im/riot-web#supported-environments) for Riot only cover OS versions with active support from the vendor, and Microsoft's mainstream support for Windows Server 2012 has already ended.

I would recommend upgrading to Windows 10 / Windows Server 2016 and later then, since you seem to be saying the issue is resolved there.

**Comment by GenaIT** [comment]
@jryans 
Then we will probably have to find another web application

Which will support what we need, and not change the whole structure of work.

**Comment by GenaIT** [comment]
all the more so since everything worked fine on early versions of Riot.

**Comment by t3chguy** [comment]
Riot just uses electron's Notifications APIs. You could ask them to try and support your edge case but it is not something Riot would be using old electron versions for.

**Comment by GenaIT** [comment]
Clear
then I’ll probably close the ticket.
and start looking for another product.
