### ISSUE TITLE
"Your messages are not secure" error despite successful device verification

### ISSUE THREAD

**Issue by jonathancross** [vector-im/riot-web#13547]
### Description

After "upgrading" encryption, I saw that my own mobile device was marked as unverified.
I tried to verify via emoji, but got this error message:
![messages-are-not-secure](https://user-images.githubusercontent.com/5115470/81176319-4ba98c80-8fa5-11ea-8c40-5a161a0890aa.png)

### Steps to reproduce

- Click "Upgrade encryption" when prompted in v1.6.0 
- Complete the process
- Select conversation with my own mobile phone (Android Riot.im)
- Note that session is unverified.
- Start verification process with emoji.
- Confirm.

**Describe how what happens differs from what you expected.**

I saw the modal warning above stating:

> **Your messages are not secure**
> One of the following may be compromised:
> • Your homeserver
> • The homeserver the user you’re verifying is connected to
> • Yours, or the other users’ internet connection
> • Yours, or the other users’ session

Clicking "OK" took me back to the app.
Mobile client indicated that verification was "Canceled" (which it was not by my actions)
On desktop, I then saw that the mobile device was **verified and shown in green** now.

I expect to not see this error if verification was successful.

### Version information

- **Platform**: desktop
- **OS**: macOS
- **Version**: 1.6.0

Homeserver: https://matrix.org
Identity Server: https://vector.im

Sorry, not submitting logs (too much personal data)

**Comment by turt2live** [comment]
Without logs we will not be able to debug this, sorry. Please reopen this if you're willing to send logs over for us to take a look.
