### ISSUE TITLE
Difficult to mouse over the room lock icon when room list is collapsed

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13554]
### Description

![image](https://user-images.githubusercontent.com/1342360/81200159-7acaf880-8fbb-11ea-86e0-5ad44707368e.png)

Trying to mouse over the lock in the collapsed room list results in the room name often showing up on top as well. This is at default browser zoom level on a 1080p 16:9 monitor.

I think the hitboxes might need some adjusting.

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
goodbye lock icon
