### ISSUE TITLE
Secure jitsi conferences automatically with a password

### ISSUE THREAD

**Issue by awesome-michael** [vector-im/riot-web#13550]
Is it possible to create the jitsi conference with a generated password that is distributed in the matrix room? I think the jitsi API allows to set a password for the conference (https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) but I'm not sure if the password can be passed automatically to jitsi-meet.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/13074
