### ISSUE TITLE
Support password login/registration alongside SSO buttons

### ISSUE THREAD

**Issue by artonge** [vector-im/riot-web#13558]
**Is your suggestion related to a problem? Please describe.**
When the server support multiple login methods, in my case sso, and password, Riot only shows SSO login with no possibility to login using a password.

**Describe the solution you'd like**
On the login page (/#/login), it would be nice to have a button to switch to another login method.

**Describe alternatives you've considered**
The only option I see is to disable SSO login altogether.

**Additional context**
My use case would be to allow local users listed in LDAP to log in with SSO and to enable registrations for external users that would log in with a password.

**Comment by turt2live** [comment]
There is a general assumption that your SSO system is capable of creating those external accounts as needed fwiw.

**Comment by artonge** [comment]
After some thoughts, I think you are right, the SSO system should handle registrations.
Also, allowing registrations with an SSO system could probably lead to username conflict.

Should we close this issue ? I don't think the use case was valid any more.

**Comment by turt2live** [comment]
Username conflicts are also the responsibility of the SSO system.
