### ISSUE TITLE
Pings don't update the display straight away

### ISSUE THREAD

**Issue by Standard8** [vector-im/riot-web#13551]
### Description

I received a ping notification sound, looked at the desktop client, and didn't see any signs of a notification until I moved my mouse over it (which may have been a co-incidence).

### Steps to reproduce

- Have multiple channels open on the desktop client on a separate display.
- Be doing something else.
- Have someone else ping you in a channel or as a direct message.

Expected Results

- Sound displayed at the same time as the UI updates to indicate a message has been received.

Actual Results

- Sound and desktop notification are displayed first
- The indicator of which room/direct message is not displayed.

You have to focus the app or move the mouse over the list to see the room/direct message list update.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop
- **OS**: macOS 10.14.1
- **Version**: 1.6.0

**Comment by turt2live** [comment]
This sounds like the room list is being rate limited - one for #11743

**Comment by turt2live** [comment]
I think we fixed this now
