### ISSUE TITLE
Notification and lock icons get cut off in collapsed room list

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13555]
### Description

![image](https://user-images.githubusercontent.com/1342360/81200700-43a91700-8fbc-11ea-93bf-a0b8aca68bf6.png)

Both long notifications and room lock icons get cut off at the sides when the room list is collapsed for me. This is on a 1080p 16:9 monitor.

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Not anymore!
