### ISSUE TITLE
IRC style layout for message list

### ISSUE THREAD

**Issue by JorikSchellekens** [vector-im/riot-web#13552]
Add a simple IRC style `timestamp | name | message` style layout for messages.

Current work looks like this:

![image](https://user-images.githubusercontent.com/23084468/81191243-b7452700-8fb0-11ea-9724-d38de0793f12.png)

**Comment by JorikSchellekens** [comment]
Suggestions from @nadonomy:

[] 24 hour timestamps
[] Don't show avatars next to usernames (or, default off and provide a toggle to enable)
[] More compact layout

Currently the 24hour layout is already an option in preferences.
Optional avatars is being worked on

**Comment by JorikSchellekens** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/4531

**Comment by jniniinoinoino** [comment]
I'm just gonna shine in here and say; 

> [] Don't show avatars next to usernames (or, default off and provide a toggle to enable)

Is a bad idea, people distinguish faster by color than text. Removing avatars next to usernames can become hard to read when the in-flowing information gets too much. Our brain might work faster and harder and will eventually, by nature, create headaches.

Or have I gotten this thing completely wrong, is this the default view when starting Riot-Web in the future?
