### ISSUE TITLE
Resetting cross-signing keys ignores key backup preference

### ISSUE THREAD

**Issue by ndorf** [vector-im/riot-web#13562]
### Description

Enabling cross-signing forces key backup to be enabled

### Steps to reproduce

From an initial state where neither key backup nor cross-signing are enabled, enabling cross-signing forces key backup to be enabled also.

There doesn't seem to be any good reason to require key backup to use cross-signing only?

In fact, after this process, the key backup can be deleted and cross-signing appears to remain enabled. However, if one does not want their E2E keys to be transmitted to the server, then the damage has already been done.

Logs being sent: no

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Firefox 68.7.0esr
- **OS**: Debian Stretch
- **URL**: riot.im/app

**Comment by turt2live** [comment]
It can be disabled during setup:
![image](https://user-images.githubusercontent.com/1190097/81222237-33d00980-8fa1-11ea-913d-49ccf45d57d7.png)

Key backup helps make sure that your message keys aren't lost forever if you lose your device.

**Comment by ndorf** [comment]
@turt2live Even after deselecting that option, Key Backup ends up enabled, at least if one uses the 'recovery key' option hidden under 'Advanced.'

**Comment by ndorf** [comment]
It ends up enabled if one enters a passphrase, also. Again, with the 'Backup encrypted message keys' option explicitly deselected.

**Comment by turt2live** [comment]
The recovery key is explicitly for key backup. I can't reproduce the scenario where entering a passphrase, disabling key backup, and clicking continue enables key backup.

**Comment by ndorf** [comment]
I just hard-refreshed riot.im/app and reproduced it, here are the screenshots:

1.
![Screenshot at 2020-05-06 14-06-18](https://user-images.githubusercontent.com/5393543/81224257-aa223b00-8fa4-11ea-994a-b1906756923f.png)

2.
![Screenshot at 2020-05-06 14-16-23](https://user-images.githubusercontent.com/5393543/81224289-b8705700-8fa4-11ea-9194-5988eb104b8d.png)


3.
![Screenshot at 2020-05-06 14-17-43](https://user-images.githubusercontent.com/5393543/81224279-b4dcd000-8fa4-11ea-821c-9f32c6478ec9.png)

**Comment by ndorf** [comment]
To be 100% clear, I used the 'Reset cross-signing and secret storage' button in the first screenshot.

**Comment by turt2live** [comment]
Ah, the reset button does indeed do the wrong thing. The initial setup is fine though.

**Comment by ndorf** [comment]
I couldn't figure out a way to go back to the initial state where cross-signing is not enabled. Using 'Reset' and then 'Skip' leaves it enabled as it was before (but, that doesn't unexpectedly enable Key Backup) at least.

On another note,

> The recovery key is explicitly for key backup. 

Why is this the case? Shouldn't I be able to use cross-signing without relying on a human-generated passphrase (just as one can for key backup)?

And the UI doesn't really make this clear, since that option is on the same screen as the explicitly disabled 'Back up keys...' option.

**Comment by turt2live** [comment]
The recovery key button is honestly a bit surprising to me as it has no text to even remotely explain what it is - a new issue would be best.

**Comment by ndorf** [comment]
OK, thanks.
