### ISSUE TITLE
Allow disabling markdown quotes

### ISSUE THREAD

**Issue by seitokaichou** [vector-im/riot-web#13561]
Platform: web
Version: most recent

I am opening this as a bug, because in my eyes, it is. Please add a setting to disable the rendering of
`>quotes` as rich text, similar to the emoji setting.
I don't think I am exaggerating when I say that a lot of users find those are awful, and just want plaintext arrows instead.

**Comment by turt2live** [comment]
Sorry, we currently support markdown for messages and don't have an interest in using our own markdown specification. As a workaround, there is the `/plain` command which doesn't use any markdown processing.

**Comment by seitokaichou** [comment]
>using our own markdown specification.

What? 

You thought it was reasonable for emojis, why not for quotes?

**Comment by turt2live** [comment]
Emoji has nothing to do with markdown? And I don't think we have an option to turn off emojis...

**Comment by seitokaichou** [comment]
It has to do with the way text is rendered. I was talking about
```
Composer
-> Automatically replace plain text Emoji
```
And was asking for something similar ("automatically replace plain text quotes with markdown ones")
At any rate, please reconsider. I understand your point of view, but this would be a relatively easy way to improve riot-web for a lot of users. Thank you.

**Comment by t3chguy** [comment]
> Automatically replace plain text Emoji

is something which happens on your interaction (when you press the space bar)

When you send the message, it gets parsed as markdown using the commonmark library, making changes to whether or not `>` is parsed by that library is not possible without literally creating our own markdown dialect and library to parse it for all 3 platforms.

**Comment by seitokaichou** [comment]
Yeah, I understand - the html is baked into the protocol:
```
 "msgtype": "m.text",
    "body": ">this",
    "format": "org.matrix.custom.html",
    "formatted_body": "<blockquote>\nthis\n</blockquote>\n"
```
It is reasonable to dismiss this request then. 

Is there a way to enforce the sending of plain text messages on a server level?

**Comment by t3chguy** [comment]
It is not as the server doesn't get to see the content of encrypted rooms. It could be made such that a server converts all messages to plaintext

**Comment by seitokaichou** [comment]
Yes, that's not going to cut it. So one needs to disable it clientside.
In light of issues such as #4674 - could you please consider such an option?
Seemingly the markdown is not only annoying, it's also brittle and causes troubles elsewhere.

**Comment by t3chguy** [comment]
that is what `/plain` is for

**Comment by seitokaichou** [comment]
You really suggest I should type that every time?
In our community of 50 users, nobody wants the shitty markdown.
This is beyond retarded.

**Comment by mureni** [comment]
For the record, when Discord went through this same discussion, they reached a compromise that most people found acceptable:

`>text` (with no space between the > and the following text) would render as plain, so as to not mess up certain text emojis or chan-style "greentext"
`> text` (with a space) would render as markup

I don't think this abuses the intention or implementation of markup while still allowing expected plaintext results. Recommend re-opening this.

**Comment by t3chguy** [comment]
The markdown is parsed by commonmark. If you want them to change the behaviour raise it with them.
https://github.com/vector-im/element-web/issues/5940 is the issue about changing markdown parsers.
