### ISSUE TITLE
Room list is jumping back down again

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13565]
Yesterday it wasn't being weird but today when I click on a room and it jumps down, the scrollbar follows it. This means I have about 30 unread rooms I didn't know about :(

**Comment by jryans** [comment]
@turt2live Should this be in the inferno list or some other part of the board so we act on it?

**Comment by turt2live** [comment]
Possibly? It might also get fixed in the room list rework.

**Comment by jryans** [comment]
@turt2live says this is not bad enough to be release-blocker.

**Comment by turt2live** [comment]
(it never was, I was probably eager with labels)

**Comment by uhoreg** [comment]
I'm seeing the issue too (FF on Linux) on /app after updating

**Comment by stoically** [comment]
Not sure if that's the same issue, but what I'm seeing since 1.6.1 is that the room list jumps back to the selected room when scrolling with mouse wheel. If it isn't the same issue (and no other issue regarding that exists) then please let me know and I'll open a new one

**Comment by turt2live** [comment]
Should be fixed in the new room list.
