### ISSUE TITLE
default_theme is ignored

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13567]
I have

```
% curl -s https://myriot.tld/config.json | jq '.default_theme'
"dark"
```

but it's light, when I make a new login in a private tab:

![image](https://user-images.githubusercontent.com/14617699/81240919-7fba9700-9011-11ea-8b8a-3e2c6c77cd05.png)

riot-web 1.6

**Comment by turt2live** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/12955

**Comment by 532910** [comment]
Nope!

**Comment by 532910** [comment]
I did more tests and actually this is #13573.

`"default_theme" : "dark"` works fine itself.
