### ISSUE TITLE
riot-web 1.6.0: cannot set own integrations server

### ISSUE THREAD

**Issue by cy8aer** [vector-im/riot-web#13560]
### Description

In former versions it was simple to set an own (Dimension) integrations server in
`resources/webapp/config.js`. With Version 1.6.0 we have have `resources/webapp.asar` which IMHO is not editable anymore. You cannot change the configuration in the web interface either (only switch on/off of scalar.vector.im is possible.

- **Platform**: web (in-browser) or desktop? Official debian riot-desktop

For the desktop app:

- **OS**: Linux Debian Testing
- **Version**: 1.6.0

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-doc/pull/1957 describes the various ways that integration managers can be defined. You shouldn't have ever needed to modify the build output to change integration managers.

The config.md docs in this repo have more information as well.

**Comment by cy8aer** [comment]
1. .well-known: riot-desktop does not access .well-known/matrix/client or server.
2. config.json is simply not used anymore

**Comment by turt2live** [comment]
The `.well-known` is called every 8 hours after startup, including at startup, for the sole reason of making sure to capture integration manager changes.

How is the config wrong?

**Comment by cy8aer** [comment]
Ok, then I need to wait > 8 hours  with running Client. 

config wrong: When I installed riot-desktop 1.6.0 over riot-web 1.5.2 config.js was deleted. After restoring config.js it is not used anymore (otherwise I the integrations server setup would be used). So `config.md` describes a file which is not used anymore.

**Comment by turt2live** [comment]
The docs do not mention a `config.js` - they mention a `config.json`. 

> Ok, then I need to wait > 8 hours with running Client.

It should work on startup. If it doesn't, check the console logs for indications of failure.

**Comment by cy8aer** [comment]
I meant config.json of course, sorry.

**Comment by turt2live** [comment]
for the config issue, it'd be good to troubleshoot in #riot-web:matrix.org instead as the config features should still work.

**Comment by cy8aer** [comment]
Yep, swapping to the room. Thank you for now...

**Comment by aliyousefiaan** [comment]
Hello.
Before version 1.6.0 I change config.json on riot desktop to use my self-host matrix-dimension.
But in 1.6.0 version there no config.json file to edit integration server and add matrix-dimension server as an integration server.
Now, what gonna I do?
I have my homeserver and matrix-dimension.

**Comment by t3chguy** [comment]
You were editing an internal config file. See docs https://github.com/vector-im/riot-desktop/blob/develop/README.md#user-specified-configjson

**Comment by aliyousefiaan** [comment]
Yep, but I don't want to build or compile it.
Is there any other way?

**Comment by t3chguy** [comment]
Read the link I sent you. It tells you where to create a config.json file.

**Comment by aliyousefiaan** [comment]
Yep, I got it.
Thanks a lot.
