### ISSUE TITLE
Match system theme by default

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13568]
As I see riot can take browser's theme, when the `Match system theme` is on. (Via `prefers-color-scheme` css media query I suppose.) But this toggle should be on by default. At least it should be possible to set via `config.json`.

**Comment by turt2live** [comment]
It is on by default unless you've previously selected an explicit theme choice.

**Comment by 532910** [comment]
Indeed, but once selected it's impossible to revert it back to default. This is another issue #13573
