### ISSUE TITLE
riot-desktop doesn't respect system theme

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13569]
riot-desktop 1.6 from https://packages.riot.im/debian doesn't respect system theme
I have `$GTK_THEME=Adwaita:dark` and `$QT_QPA_PLATFORMTHEME=qt5ct` and all gtk2, gtk3, qt4 and qt5 apps that I have are dark, but riot with `Match system theme` switched on is white.

Chromium (from debian repo) is also white, even if I press `Use GTK+` button in it's setting and it becomes dark, sites doesn't become dark there. Yes, riot-desktop doesn't use chromium from debian, but I suspect these effects are common. Possible I don't set the system theme properly.

**Comment by turt2live** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/12955

**Comment by 532910** [comment]
Nope!

**Comment by turt2live** [comment]
are you going to explain why or just disagree? On the information provided, it's the same issue.

**Comment by 532910** [comment]
1. This issue is only about riot-desktop that's electron based.
2. When I choose `Match system theme` in the riot-desktop on electron I always see the white theme. The dark one is never applied. I'm sure this issue is electron related.

**Comment by 532910** [comment]
BTW, `Developer Tools` is white, I bet electron doesn't guess system theme settings.

**Comment by 532910** [comment]
Indeed:
![image](https://user-images.githubusercontent.com/14617699/81254407-a8ec1f00-9033-11ea-9d6a-eda77e909665.png)

**Comment by turt2live** [comment]
It sounds like the theme is getting stuck, not that it's failing to recognize it - this would be https://github.com/vector-im/riot-web/issues/12955

**Comment by 532910** [comment]
No, it doesn't getting stuck. What evidence should I provide for you to believe me?

**Comment by turt2live** [comment]
The only way I can reproduce this is by selecting a theme myself, which turns off the system theme matching, which is expected. The other issue that we know of is that the light theme is forced on and often stays forced on, regardless of setting choices.

We'd need some reproduction steps that don't lead into these cases.

**Comment by turt2live** [comment]
It's also worth noting that the forced theme causes the system theme matching to be disabled - it's part of that bug.

**Comment by 532910** [comment]
![Peek 2020-05-07 09-23](https://user-images.githubusercontent.com/14617699/81261330-8e6e7180-9044-11ea-9dc2-e03b05dc354d.gif)

**Comment by 532910** [comment]
@turt2live is this screen record not enough evidence for you to reopen this issue?
I suppose this is an electron issue rather riot-desktop, but it's not #12955.

**Comment by turt2live** [comment]
Apologies, I didn't see your response :(

Yes, the gif tells much more of a story than the issue did on first read.

**Comment by t3chguy** [comment]
This sounds like an upstream (electron) issue with it not passing your system dark theme preference into the BrowserWindow

This issue will likely get nowhere and will require a fix from Electron.

**Comment by 532910** [comment]
Looks like it's fixed as I can't reproduce it more.
