### ISSUE TITLE
Inline reactions that add on to messages.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#1357]
Without taking up additional (vertical) space.

Needs to be specced.

**Comment by ara4n** [comment]
blocked on https://matrix.org/jira/browse/SPEC-135

**Comment by markwooff** [comment]
Any updates on this issue? https://github.com/vector-im/riot-web/issues/1357 doesn't seem to have much info either.

**Comment by ara4n** [comment]
An old PR that has been pending review forever is at https://github.com/matrix-org/synapse/pull/1633.

Meanwhile, I've had some interestingish discussions recently on how to efficiently model reactions in Matrix, which i'll put on on the spec bug.

**Comment by markwooff** [comment]
Thanks for the update @ara4n - you guys are doing great work! Looking forward to seeing the progress on this feature.

**Comment by GhitaB** [comment]
+1 for this feature to be included.

**Comment by dessalines** [comment]
Would love to see this too! [This is currently the 10th most requested feature](https://github.com/vector-im/riot-web/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)

**Comment by devcline** [comment]
voting up!

**Comment by vranki** [comment]
I hope this can be disabled per-channel when it's introduced. This will be hated by people who want to use Matrix as better IRC, not as a social media.

**Comment by martindale** [comment]
Excited to see this land, personally — especially if it comes with a wave of bridge updates to sync across all the platforms that have this. :)

**Comment by dkout** [comment]
Very excited for this! I think it's the only thing missing! Is there any news on the state or an estimated time for release?

**Comment by MightyCreak** [comment]
I must say I would be pleased to see if there's progress on this feature, and if there if, where you devs are at? (maybe in the next TWIM? @benparsons)

**Comment by benparsons** [comment]
The blocker for this is aggregations - which requires a spec feature. Think about the way redactions work today - this idea of referencing a previous event can be generalised to reactions, edits etc.

It's on the spec/backend roadmap, take a look at https://github.com/orgs/matrix-org/projects/9

**Comment by jryans** [comment]
This feature is being broken down into [smaller tasks](https://github.com/vector-im/riot-web/labels/feature%3Areactions) and we hope to start those pieces soon.

**Comment by jryans** [comment]
An initial version of this now exists (as a disabled by default labs feature) on https://riot.im/develop. We'll continue to iterate on it there until it's ready for general release.
