### ISSUE TITLE
Cannot encryption encryption keys when recovery passphare and recovery key are lost

### ISSUE THREAD

**Issue by robinmoussu** [vector-im/riot-web#13578]
# Description

I set-up encryption probably more than 1 year ago, for testing, and stopped using riot for some time. I recently restarted to use it.

- I know my password so I can connect to my account and chat with people
- I forgot my recovery passphrase
- I forgot where I put my recovery key
- **I don't care at all about any past encrypted message**

There is a pop-up that ask for upgrading the encryption (I read the blog post on reddit, and the implementation you choose seems a really good idea). However I cannot do it, because I forgot both my passphrase and my recovery key.

# What I was expecting

I was expecting to be able to **reset my current encryption key** (and thus both revoke all past authentications, and loose the ability to open any previous encrypted message. This is exactly what protonmail does with your mailbox if you loose your access.

Of course this is something that is definitive, so I was expecting to have to type a long phrase like "I understand that I will loose all encrypted message, and the ability to decrypt then in the future" by hand before being allowed to click a confirmation button.

### Version information

Android app (Riot and Riot-X) + web version (firefox, fedora 30)

**Comment by dbkr** [comment]
Does this link not do what you want?

<img width="808" alt="Screenshot 2020-05-07 at 16 32 53" src="https://user-images.githubusercontent.com/986903/81314160-b1b71200-9080-11ea-8481-575e0ad97824.png">

**Comment by robinmoussu** [comment]
It's a bit hard to take screenshots because if I wait because if I wait like 5-10s it goes back to the first screen where you have to enter your session password. Anyway, if I click on "set up new recovery options", I quickly end-up here:

![image](https://user-images.githubusercontent.com/6200547/81338331-c01b2300-90ac-11ea-8bfc-a5c8a3aa4a60.png)

I didn't click on "skip" because it definitively doesn't look like what I want, and potentially something that you can't easily undo.

---

I think that a link to menu/settings/security and privacy key back-up delete back-up should be accessible from the same page. I am pretty sure that if I click there my issue will be solve (I didn't clicked it yet in order to be able to do more user testing if need be).

![image](https://user-images.githubusercontent.com/6200547/81339464-89460c80-90ae-11ea-9dc8-4a2330e25ab9.png)

What is even worse is that this page can't be accessible because of the pop-up until you click on "later" (the menu is behind).

![image](https://user-images.githubusercontent.com/6200547/81338490-01133780-90ad-11ea-9956-838183529faa.png)

---

If there is more testing to do in order to improve the UI, feel free to ask me, otherwise I will click on the "delete backup" button and if need be "boostrap cross signing and secret storage" from the security and privacy" page.

**Comment by robinmoussu** [comment]
I re-tested to click on "set-up new recovery options" and it immediately went back to the authentication page (this is a loop between the "Enter recovery passphrase page and the authentication one).

![image](https://user-images.githubusercontent.com/6200547/81340039-754eda80-90af-11ea-969f-d43c9187ace3.png)

riot-web version: 1.6.0
olm version: 3.1.3
firefox 75.0
fedora 30

**Comment by dkozel** [comment]
I'm encountering exactly the same loop as robinmoussu.

I don't know what the recovery passphrase is, I don't remember having set one. I don't think I have a recovery key, also don't remember that. And setting new recovery options seems to be reliant on having done the upgrade.

We just moved a community to Matrix+Riot this week and this is causing wide-spread confusion as the UI already required a lot of re-learning.

riot-web version: 1.6.0
olm version: 3.1.3
Firefox 76
Ubuntu 19.10

**Comment by dbkr** [comment]
OK, looks like the problem here is that the 'Set up new recovery options' link isn't doing the right thing - it looks like it's triggering the 'skip' behaviour instead, similar to https://github.com/vector-im/riot-web/issues/13346
