### ISSUE TITLE
Member button doesn't work when user details are opened

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13571]
It's impossible to hide right panel with the `members` button when user details are opened:
![image](https://user-images.githubusercontent.com/14617699/81247019-9ec12500-9021-11ea-8659-39e7560327b8.png)

**Comment by foresto** [comment]
I can confirm this problem in Riot Desktop 1.6.0 on linux.

**Comment by 532910** [comment]
I confirm it's fixed now.
