### ISSUE TITLE
Allow users to select avatar border shape and font size.

### ISSUE THREAD

**Issue by StormyMint** [vector-im/riot-web#13570]
The 1.6.0 update has changed the UI in a way that I really do not like in the slightest, the font in the user information panel has been shrunk to half it's previous size and the avatars are now a circular image.

I'd like a setting that allows users to select between at least three different font sizes and the ability to choose between your avatar being shown as circular or the old blocky shape.

I started trying search through the files of the desktop client to see what I needed to change to make a custom theme but I can barely code as is and trying to search through the files was becoming a hassle when I realized how many different things there were to go through just to even try and find what I wanted. I realized that changing elements through the browser dev console could temporarily solve my issue but it's not a permanent solution.

**Additional context**
Adding a screenshot comparison of what the UI looks like as of the recent update and rough idea of how I'd prefer being able to resize and reshape it. The image looks a bit odd due to long group chat name removed.
![compared](https://user-images.githubusercontent.com/64933228/81244982-6dbd0200-8fd9-11ea-9e66-21cb865df167.png)

**Comment by t3chguy** [comment]
Shape is #9058
Font size is wip in labs right now.

**Comment by StormyMint** [comment]
What about avatar shape?

**Comment by t3chguy** [comment]
See the issue i linked. Bottom comment specifically.

**Comment by StormyMint** [comment]
I should've slowed down and read the entire comment, only saw the last part and got confused, thank you for responding.
