### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13577]
Both https://riot.im/app and my instance shows
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```
in the web developer console at reload.

**Comment by 532910** [comment]
I tried to set `script-src` to `unsafe-inline` in nginx headers, but it changes nothing.

**Comment by t3chguy** [comment]
the CSP is set in index.html and is set as strictly as is possible.
There are no inline scripts in modern riots.

I cannot reproduce your issue:
![image](https://user-images.githubusercontent.com/2403652/81297573-56c6f000-906b-11ea-9775-7f62b20ced1a.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/81297623-6cd4b080-906b-11ea-854a-f65780bcd027.png)

also cannot reproduce in Firefox

**Comment by t3chguy** [comment]
It is likely you have some browser extensions which apply further CSP

**Comment by 532910** [comment]
I did not think it could be, an extension, indeed, it's inserted by tampermonkey. Thank you!
