### ISSUE TITLE
Previous/next room or DM leads to endless cycle between 2 rooms

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/riot-web#13593]
### Description

The hotkey list shows that Alt + UpArrow and Alt + DownArrow navigate up and down on the room list.

They work as expected, however, when you navigate to a different room, it gets moved to the top of that room list section. So if you keep pressing Alt + DownArrow in a room list section with more than 2 rooms (when you are currently in the top room), you will keep cycling between those two rooms forever.

There is also some similarly unexpected behavior in room list sections with only 2 rooms.

### Steps to reproduce

- Navigate to the top room in a room list section with more than 2 rooms
- Press Alt + DownArrow to navigate up a room
- Wait for the rooms to re-order themselves
- Observe that if you press Alt + DownArrow again, you will cycle back to your initial room.

I would expect that the rooms stay in their original order, so that I can navigate through the whole list with the hotkeys

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Linux Mint
- **Version**: 19.3

**Comment by t3chguy** [comment]
This is caused by a bug in the "breadcrumb" algorithm which https://github.com/vector-im/riot-web/issues/11743 aims to fix.
