### ISSUE TITLE
Rageshake support rather than ending up crappily taking screenshots of the console

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#136]

**Comment by ara4n** [comment]
this is really important now given it's getting in the way of debugging e2e work. i think @kegsay volunteered? O:-)

**Comment by Kegsay** [comment]
I wouldn't go that far :wink: 

So the plan on this is to:
 - monkey-patch `console` to write logs to a big string.
 - Periodically flush the string to local storage. (so as not to take a perf hit by doing it on every `console.log` call).
 - The key for the string needs to be unique *across browser tabs*, so generating a random ID for that particular tab then keying off that needs to be done to ensure we don't pollute logs. Probably structure the keys as `log_$ID`, without indexes for now and we can see how big single key/values can get.
 - Storage format: we want timestamps, the log line and the level (`console.log` vs `console.error`). It looks like there is an [LZ implementation](https://github.com/pieroxy/lz-string) for precisely this kind of thing (storage in local storage) which might be interesting to look at.

**Comment by Kegsay** [comment]
Having spoke about this a bit more, it's going to be a PITA if it turns out the local storage impl isn't up to the job. We might just want to jump straight to IndexedDB. We will be using it for #121 anyway sooo... might as well.

**Comment by Kegsay** [comment]
Sending wise:
 - Upload logs to the content repo on the HS.
 - Add a mailto link with the URL in the body.

**Comment by Kegsay** [comment]
Spoke about this on #riot-dev and:
 - Only using IndexedDB is :sadpanda: because it won't work on incognito tabs, so localstorage fallback would be good. (thanks @richvdh ) - Use `localForage` and rely on it falling back?
 - Uploading the logs to the content repo is :sadpanda: because they will be unencrypted at rest and may be sensitive (thanks @ara4n )
    * We could gen a pub/priv key pair and put the pub key in `config.json` and encrypt the logs before uploading to the content repo. However, @dbkr points out this is painful both on the client (webcrypto) and the server (decrypting the logs). Having a POST API or something makes this moot, so is preferable.
    * If the POST API is separate from Matrix entirely this also helps with a point which @ara4n made: relying on Matrix to send logs about Matrix isn't a great idea...

So sending wise, the plan:
 - Write a server API endpoint which will take the logs.
 - Clients POST to this endpoint. Done.

**Comment by ara4n** [comment]
This will also make @ylecollen :happypanda: for https://github.com/vector-im/riot-android/issues/842

**Comment by Kegsay** [comment]
Riot-Web work is now complete. It will attempt to POST logs to an endpoint specified in `config.json`, and there's UI in UserSettings if there is an endpoint available.

Server work is blocked pending clarification on where the logs should end up. I was under the impression that dumping them on disk would suffice, but as per https://github.com/vector-im/riot-web/pull/3072#issuecomment-275372471 it appears that they should end up in a bug tracker. See that PR for further discussion on the practicalities.

**Comment by ara4n** [comment]
kegan did this.
