### ISSUE TITLE
Cross-Signing not working properly

### ISSUE THREAD

**Issue by Beiri22** [vector-im/riot-web#13614]
### Description
At first I got a lot of trouble with initiating the cross signing. After all of that I resetted cross signing a few times and logged out all my devices; and started "fresh". Only thing that was not fresh is my key backup.

Cross-Signing is working only with some users. Consider the following setting:
ME) 3xLinux with Riot-Desktop 1.6.0-2 (Manjaro) + 1 Phone with RiotX 0.19
A) 1xLinux with Riot-Desktop 1.6.0-2 (Manjaro) + 1 Phone with RiotX 0.19
B) 1xLinux with Riot-Desktop 1.6.0-2 (Manjaro) + 1xWindows with Riot-Desktop 1.6+1xiOS Phone with Riot 0.11.2 (the latest of yesterday)

After all the trouble: Cross-Signing is working well between A and ME.
B sees all my devices as verified, so this part is working
ME does only see a few devices of B verified, ME can see that B has not verified all his devices, although B has verified all his devices.

So I have started a verification with B. I did not have to choose a specific device. After successfully verifying, only one verification was perfomed. Futhermore, I can now choose individual devices of B again for verification.

**Comment by jryans** [comment]
When did ME and B setup their cross-signing identities? What is only with the release versions of Riot clients, or were you also testing it earlier while in development?

What version of Synapse is your homeserver running? Are all of these users on the same homeserver?

**Comment by Beiri22** [comment]
We did only use the releases. (If you call RiotX a release, because it's beta).My homeserver (ME, A) is synapse at 0.12.4. and B is on matrix.org.

What we further tried afterwards:
1.) I unlogged all devices and tried to remove all their entries from the my homeserver-db (devices, e2e_*) and logged all in again, verified my devices. Same problem when verifying B.
2.) I finally convinced B to reset his cross-signing via the official option. That made it! It is now working between B and ME. But I do not know the reason of the problem.

Maybe there are some problems when people migrate to the new verification algorithm, when they use old (riot android) and new(riotx/riotDesktop) algo simultaniously? Maybe synapse can do some check&fix on the database, i don't know.

**Comment by jryans** [comment]
Ah okay, it's quite helpful to know that ME and B are on separate homeservers, and I am glad to here that you could workaround by resetting at least, though of course that's not ideal.

I believe this is another example of https://github.com/matrix-org/synapse/issues/7418, which has a fix in progress on the Synapse side.

For now, I'll close this as I don't think Riot can make a client side change. Once the Synapse fix is available and deployed, if you continue to see issues like this, please open a fresh issue.
