### ISSUE TITLE
Git over Riot/Matrix feature [Keybase is dead, long live to Riot!]

### ISSUE THREAD

**Issue by fakeNews-jpg** [vector-im/riot-web#13615]
Hello,

Following the acquisition of Keybase by Zoom, it could be really really interesting to offer a git via matrix within this Riot
They are expermimental projects and I do believe the concept can work well ! (i'm not the only one: http://git.jcg.re/jcgruenhage/git-on-matrix)
I think this way we can have a really secure git :)

Thanks a lot in advance for your answer,
Sincerely,
G.M

**Comment by lucaszanella** [comment]
I don't know what riot or matrix are but I'd start to use if you guys provide a end-to-end encrypted git just like Keybase

**Comment by dbkr** [comment]
There are some PoCs of git over Matrix, but Riot is a Matrix chat client. If the PoCs progress then Riot could look at integrating in some fashion, but we're not quite there yet!

**Comment by ptman** [comment]
@dbkr is there any public info about the PoCs? any link?
