### ISSUE TITLE
join forgotten room

### ISSUE THREAD

**Issue by oeai** [vector-im/riot-web#13613]
i've made a room public, then i decided to clean it with new text and deleted the room,
it was riot.im and it was moved to history, then i press forget and it was removed.
But it was written in my community andthe community room list is now stuck and not resolving.
Now i try to join the room - no luck

> request failed: CORS request rejected: 

i wanted to create the room once again to solve it - the room name is not free
i did relog, tried with html client - no way.

i want to restore the room and join it / change name or make the room name free somehow
i need my community room list working (is it resolving by name or UID?)
> room previews are disabled (M_FORBIDDEN)

**Comment by dbkr** [comment]
I think this is essentially https://github.com/vector-im/riot-web/issues/3194 (ie. if you own a room alias you need a way to remove it from a room, even if that room is empty).
