### ISSUE TITLE
"Missing session data"

### ISSUE THREAD

**Issue by leer10** [vector-im/riot-web#13624]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- I opened Riot and it said my message keys were missing. It said to help fix the problem by sending logs so this is what I'm doing.

Log: Sent

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Chrome
- **OS**: ChromeOS 81.0.4044.103
- **URL**: riot.staplemac.xyz (also present on riot.im/app) 1.6.0

**Comment by leer10** [comment]
Actually I tried to do the log upload (on both flagship Riot website and my own instance) and it said "Failed to send logs: Cannot read property 'getDeviceEd25519Key' of null"

**Comment by dbkr** [comment]
The above should fix the failure to send a bug report, but the error itself is due to chrome deleting your indexeddb data, which is a thing that can happen if you haven't used riot in a while and/or are low on disk space.
