### ISSUE TITLE
Sticker box is just plain white

### ISSUE THREAD

**Issue by etc0de** [vector-im/riot-web#13632]
### Description

When I click "Add some now" to add a sticker pack, this is what I'm seeing:

![stickerwindow](https://user-images.githubusercontent.com/1573352/81586269-8d777000-93b5-11ea-888f-c8fd00976902.png)
(some background parts pixelated)

### Steps to reproduce

- 1. Click emoji icon in riot's text input bar
- 2. In  the small popup saying "You don't currently have any stickerpacks enabled" click "Add some now"
- 3. Click that you want to enable the integration thing
- 4. Observe blank white box as shown above

### Version information

- **Platform**: h riot-web version: 1.6.0
- **Browser**: Firefox Nightly
- **OS**: Linux
- **URL**: https://riot.im/app

**Comment by turt2live** [comment]
@etc0de please submit logs for this from Settings -> Help

**Comment by dbkr** [comment]
Not much we can do with this without further info: let's re-open if we get more data.

**Comment by christiansacks** [comment]
Happens the same to mine too. What info would you need to troubleshoot further?
