### ISSUE TITLE
Can't add an email addres: No appropriate authentication flow found

### ISSUE THREAD

**Issue by JulienPalard** [vector-im/riot-web#13639]
# Description

Can't add an email addres to my account.

### Steps to reproduce

- I enter my email
- I click the "Add" button
- I receive the email
- I click the « Complete email verification » button
- It shows me « Verification successful! Please return to your Matrix client to continue. »
- I click the « Continue » button
- I'm getting an error « No appropriate authentication flow found ».

### Version information

Web app:

- **Browser**:  Firefox 76.0 (from Debian sid), desktop.
- **OS**: Debian bullseye, Linux 5.4.0, x86_64
- **URL**: https://chat.mozilla.org
-  Riot-web : v1.6.0
- Olm : 3.1.3

**Comment by t3chguy** [comment]
Same root cause as https://github.com/vector-im/riot-web/issues/12028 which is solved in riot-web, missing functionality in Synapse which is due in next release.

**Comment by JulienPalard** [comment]
Thanks for the fast reply!
