### ISSUE TITLE
closing app on smart phone signs out user

### ISSUE THREAD

**Issue by Motocycle347** [vector-im/riot-web#13636]
**Is your suggestion related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by turt2live** [comment]
Please fill out the issue template.

**Comment by Motocycle347** [comment]
where are the issue templates?

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/new
