### ISSUE TITLE
No easy way to close/hide profiles.

### ISSUE THREAD

**Issue by ludwigbald** [vector-im/riot-web#13653]
![image](https://user-images.githubusercontent.com/34342715/81803733-65ece880-9518-11ea-9273-633484455942.png)

### Description
When clicking on a username, I am presented with the profile as seem on the screenshot. Unlike I expected, there is no button that closes this panel.

### Steps to reproduce
- Click on a username
- Try to close the panel

### Version information

- **Platform**: Web v1.6.0, Chrome

**Comment by t3chguy** [comment]
What about the close chevron?

![image](https://user-images.githubusercontent.com/2403652/81804301-cbd57200-9510-11ea-8dc2-580c6418588f.png)

**Comment by t3chguy** [comment]
Closing as there is a labelled close button.

**Comment by ludwigbald** [comment]
That close button does not close the panel. It's a back button, not a close button.
The "members" button usually closes the members panel. But if you are on an individual profile, it does nothing.

**Comment by t3chguy** [comment]
> But if you are on an individual profile, it does nothing.

This isn't right unless you're on an old version in which it was broken. On 1.6.2 it is fine.
