### ISSUE TITLE
permalinkprefix via .well-known/matrix/client ?

### ISSUE THREAD

**Issue by Lighti123** [vector-im/riot-web#13676]
**Is your suggestion related to a problem? Please describe.**

Hello!

we have a non-federated closed down homeserver for our university.
We use riot web and also the riot desktop and mobile clients.

On our university hosted riot web instance i can set "permalinkPrefix" in the config.json to direct to our riot web instance, thanks to #7659.
When my users "share a room" in our riot web instance, they get a permalink they can post to their students which can then join the room through our riot web instance.

On mobile and desktop clients i can not change the default config.json
When my users there try to share a room, they get a permalink directing to matrix.to instead to our own riot web instance.

This may work, but it is quite a security concern for us.

**Describe the solution you'd like**
Can you maybe also provide the permalinkPrefix through the ".well-known/matrix/client" file?

With this our riot.im desktop and mobile apps connecting to our university matrix server would have the right permalinkPrefix value and "share a room" would generate permalinks as intended by us. 

Thanks!

**Comment by turt2live** [comment]
It's not currently possible, though it does tie directly into something I've been thinking about for a couple weeks now: whether we want to support a .well-known config in general for several settings (not just permalink prefixes). I've finally opened https://github.com/vector-im/riot-web/issues/13678 to track this, so closing this issue just so we can avoid having several issues which track the same thing in different ways.

**Comment by Lighti123** [comment]
thank you very much!
