### ISSUE TITLE
Unable to set up new recovery options during bootstrap cross-signing flow

### ISSUE THREAD

**Issue by neutralinsomniac** [vector-im/riot-web#13686]
### Description

I have a coworker that is trying to set up cross-signing and can't set up a new recovery passphrase (he forgot his old one). Check steps to reproduce below for details.

### Steps to reproduce

- Coworker clicks "Bootstrap cross-signing and secret storage" button in user settings.
- He enters his account password at the "confirm the upgrade" prompt (we're using the ldap3 auth provider if that factors in at all), which succeeds.
- Next comes "Enter recovery passphrase". He's forgotten his passphrase, so he clicks "set up new recovery options".
- Coworker is again presented with the "confirm the upgrade" prompt. Typing his password again brings him again to the "Enter recovery passphrase" dialog.
- Repeat this process forever with no change in outcome.

I would expect that, after clicking "set up new recovery options", my coworker would've been presented with a dialog allowing him to specify a new recovery passphrase.

Logs being sent: no (running on a sensitive network :/ )

### Version information

Riot-web 1.6.0 running on Windows 10, tried Firefox 72.0.2 and Chrome 80.

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/riot-web/issues/13578 (best to file bugs against the develop branch if possible).
