### ISSUE TITLE
In rooms with E2E encryption, older unencrypted messages can't be searched

### ISSUE THREAD

**Issue by justin-sleep** [vector-im/riot-web#13682]
### Description

I have a few rooms where encryption was recently enabled. When I attempt to search them for old messages, only the newer, encrypted messages are present in the results.

### Steps to reproduce
- Create a room with E2E encryption turned off
- Send a message
- Turn encryption on
- Attempt to search for the prior message

Unencrypted messages will not show up in the results. My guess is that this is because the search bar uses seshat when the room is encrypted, but the older, unencrypted messages rely on server-side search.

### Version information
- **Platform**: Desktop
- **OS**: Arch Linux
- **Version**: 1.6.0

**Comment by t3chguy** [comment]
I wonder why Seshat wouldn't just index all the way to the beginning of time in this case?

**Comment by poljar** [comment]
I think the described behavior means it indexes new events only and a checkpoint just needs to be added when a room becomes encrypted. Just a forgotten case.

**Comment by 532910** [comment]
While I experience the same issue, the workaround that works for me is: search in `All Rooms`.

**Comment by poljar** [comment]
Rebuilding the index by disabling/enabling the feature works as well as a workaround.

**Comment by 532910** [comment]
By disabling/enabling what feature exactly?

**Comment by poljar** [comment]
Message search in the `Settings` -> `Security & Privacy`

**Comment by 532910** [comment]
There are no any `search` controls in the riot-electron 1.6.4 from the official debian repository:

![image](https://user-images.githubusercontent.com/14617699/84602782-70413000-ae92-11ea-883a-485b826adfe9.png)
![image](https://user-images.githubusercontent.com/14617699/84602819-ad0d2700-ae92-11ea-8c5b-4a4e1edcc019.png)

**Comment by poljar** [comment]
There is a `Message Search` section in your second picture. Clicking on the manage button will reveal a button to disable the feature.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/84602906-6a435300-ae82-11ea-8ea0-0ebf68bc8450.png)

Yes there is, as per your screenshot..

![image](https://user-images.githubusercontent.com/2403652/84602910-6fa09d80-ae82-11ea-8e76-203e215d6976.png)


You can disable & re-enable there.

**Comment by 532910** [comment]
Disabling it, indeed, make it work correctly. But enabling it back breaks again.

**Comment by poljar** [comment]
You'll have to wait for the index to be completely rebuilt. You can track the progress in the same UI where you disabled message search.

**Comment by 532910** [comment]
I waited. And it has finished.
