### ISSUE TITLE
Messages with gossiped keys show as "Encrypted by a deleted session"

### ISSUE THREAD

**Issue by igbjnI05bF** [vector-im/riot-web#13689]
Dave says: Because of the TODO at https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/crypto/index.js#L2197 we don't return the event sender for any messages where we got the key from one of our other devices, which mean show up as 'Unknown', ie. the message in the title.

Original description follows:

### Description

Riot electron 1.6.0 on Kubuntu 20.04 (installed via apt) is showing red shields with "encrypted by a deleted session" next to sessions that I have verified and that are not deleted. I'm seeing it right now on a message that I sent an hour ago from Riot-electron (on gentoo installed via flatpak) on my desktop. I have successfully set up cross signing and all of my devices are verified. I can read the messages, they aren't gibberish, they just have the red shield with that message when I hover over the shield.

I noticed this yesterday in a few rooms. I signed out of Riot, deleted the session, signed back in, and verified the device. This actually did fix the red shields in one room, but not in others. 
![image](https://user-images.githubusercontent.com/24235468/82087121-79858400-96bd-11ea-9e03-65b736c60a8a.png)

![image](https://user-images.githubusercontent.com/24235468/82087150-873b0980-96bd-11ea-9f30-5ea6547116ae.png)

I will submit logs in Riot after this

**Comment by IF-Adin** [comment]
To me, this happened when restoring a backup via Timeshift.

**Comment by dbkr** [comment]
I can't see any logs for this issue - if you get it again can you try again?

**Comment by igbjnI05bF** [comment]
Just installed Riot on a brand new laptop, did cross signing, everything seemed to work. I'm in a room right now and see the "encrypted by a deleted session" for messages sent by a friend today on an active non-deleted session.

I submitted logs again

**Comment by IF-Adin** [comment]
When i updated Riot today, the message went away. Is it perhaps a cache issue?

**Comment by dbkr** [comment]
Updated the description with the cause of this. We should either finish writing key forwarding (ie. check the trust of forwarded keys) if we're going to continue supporting them.

**Comment by jryans** [comment]
@dbkr Do you think https://github.com/vector-im/riot-web/issues/13531 is the same issue as well?

**Comment by d2dyno** [comment]
Me and everyone on my homeserver have this issue too.

**Comment by dbkr** [comment]
> @dbkr Do you think #13531 is the same issue as well?

The OP there says, "Wait for encrypted message keys to be shared" which implies they're relying on keys being shared from other devices rather than using key backup, in which case, yep, it will be the same bug.

**Comment by uhoreg** [comment]
The message now says that the authenticity of the message cannot be verified, which is a more accurate description of what is going on.
