### ISSUE TITLE
Desktop app: Unable to upgrade to encryption for Mozilla instance's account

### ISSUE THREAD

**Issue by arunsathiya** [vector-im/riot-web#13696]
### Description

On the Riot desktop app, setting up encryption fails for a Mozilla homeserver-based account. To be more specific, encryption is already setup for my account, but trying to verify other devices **from Riot desktop app** fails with this error: `No appropriate authentication flow found`

This error does not occur on Riot website client - that is, https://chat.mozilla.org

### Steps to reproduce

- Setup a Mozilla homeserver-based account
- Login into it on Riot desktop
- Login into Riot website client as well and setup encryption
- When prompted to setup encryption on desktop app, choose to proceed. In other words, when prompted to upgrade that desktop session to encryption, choose to proceed.

### Describe how what happens differs from what you expected.

- **What is expected:** Able to complete encryption setup for that desktop session
- **What happens instead:** Encryption setup fails. There is a brief time when the `Setting up keys` popup appears, but immediately disappears and shows `No appropriate authentication flow found` error instead.

### Screenshots

I can try to add them later.

### Version information

- **Platform**: Desktop

For the web app:

- **Browser**: All browsers are fine
- **OS**: Windows and macOS
- **URL**: https://chat.mozilla.org

For the desktop app:

- **OS**: Windows and macOS
- **Version**: Unsure where to find this

**Comment by arunsathiya** [comment]
Notes: 

I see an issue here with the same error message https://github.com/vector-im/riot-web/issues/13639

It eventually leads to https://github.com/matrix-org/synapse/issues/5667 and the PR related to it is merged.

**Comment by t3chguy** [comment]
Yup. This is simply lack of support in release Synapse. Its in their latest release candidate so should be coming soon.
