### ISSUE TITLE
Trying to Upload Files and Can't Access Personal Folders on Desktop

### ISSUE THREAD

**Issue by cbrokaw** [vector-im/riot-web#13699]
### Description

I cannot access other folders to add files/pictures to upload except my "Downloads" folder.

### Steps to reproduce

- Open Riot Desktop (Linux Mint, Flatpak)
- Click on the paperclip icon to upload a file
- After clicking the paperclip, my "Downloads" folder opens by default, but I can't access my other personal folders/files under "Home"

Logs being sent: yes

### Version information

- **OS**: Linux Mint 19.3
- **Version**: 1.6.0 Flatpak

**Comment by t3chguy** [comment]
This is by design of the flatpak. https://github.com/flathub/im.riot.Riot/issues/33
