### ISSUE TITLE
/op <user-id> is broken

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#13697]
No matter what you put as the user-id you always get an error saying "Could not find user in room". The user shouldn't have to be in the room so I'm not sure why it would check that but regardless it doesn't matter if they are or are not in the room, you always get that error.

Regression since 1.5.15

**Comment by t3chguy** [comment]
Cannot reproduce, works fine for me with a valid MXID which is inside the room.
https://github.com/vector-im/riot-web/issues/2168

**Comment by t3chguy** [comment]
Argh, actually I see the issue, it only works for users with an existing PL modification.

**Comment by alignwaivers** [comment]
Just wanted to +1 this and say I appreciate that ya'll are totally on this!

Just started my own room for the first time and despite not understanding ins and outs Riot it is F***ing AWESOME. Thank you for the great work and fantastic piece of F.L.O.S.S.!
