### ISSUE TITLE
Unable to join room or DM user

### ISSUE THREAD

**Issue by redbassett** [vector-im/riot-web#13700]
### Description

Unable to join a room or DM a user upon creating a new account.

### Steps to reproduce

Room:
- Create a new account
- Go to a room which is publicly visible. Read some messages
- Decide to join room, click the "Join The Discussion" button

DM:
- Open the new DM dialog
- Enter a user's handle
- Click on the user in the suggestions list and click "Go"

Describe how what happens differs from what you expected.

Room:
An error dialog appears:
> Failed to join room
> You are not invited to this room.

DM:
An error appears below the username input:
> We couldn't create your DM. Please check the users you want to invite and try again.

### Version information

- **Platform**: web (in-browser)

- **Browser**: Brave 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)
- **OS**: Mac OS X
- **URL**: https://riot.im/app/#/home

**Comment by t3chguy** [comment]
Can you send logs from Settings > About please.

**Comment by redbassett** [comment]
Done

**Comment by redbassett** [comment]
The app said it was successful when I sent logs, but I don't see anything in this issue about it? Any ideas?

**Comment by t3chguy** [comment]
The logs are uploaded privately, they are linked, don't worry.

![image](https://user-images.githubusercontent.com/2403652/83085714-9d18d900-a084-11ea-8f65-4554a352e4cd.png)

**Comment by t3chguy** [comment]
```
2020-05-18T02:53:39.142Z E Internal server error
M_UNKNOWN: Internal server error
```

it isn't looking like a Riot issue however

**Comment by redbassett** [comment]
Ok, I thought this server was hosted by Riot, but Riot is just the front-end client?

**Comment by t3chguy** [comment]
Yup, Riot is just a client which runs entirely in your browser and connects to the Matrix server on which your account is
