### ISSUE TITLE
What happened to the v.1.0 UI?

### ISSUE THREAD

**Issue by ingingin** [vector-im/riot-web#13709]
I wanna know what happened to the excellent designs in [v.1.0](https://medium.com/@RiotChat/the-big-1-0-68fa7c6050be).

![Screenshot from 2020-05-19 09-57-47](https://user-images.githubusercontent.com/65529926/82300510-7bde2b80-99a6-11ea-9a41-271436026ed4.png)
^ I loved the admin/mod *star* next to the picture. Why was this removed?

![1*1-qVfzJWhO24OFIaQArzKQ](https://user-images.githubusercontent.com/65529926/82300387-4b968d00-99a6-11ea-8e7c-bd1a8246c07e.png)
^ This looks so good. Is this on the TODO list? It looks so clean. I swear I have seen an issue about doing the same floating username box that discord has. This should be it. And add an extra button on this box to expand to the side would be AWESOME.

Is this still on the menu? I am just asking.

**Comment by t3chguy** [comment]
For questions use https://matrix.to/#/#riot-web:matrix.org

The Admin *Shield* with a star was removed as it was conflicting with the Encryption Shield design language.

What you're showing there is the old MemberInfo panel, replaced now with the new UserInfo panel with the latest designs. It was always in the right panel, not floating.
