### ISSUE TITLE
Riot-desktop AppImage build: "Couldn't find webapp files in any of..."

### ISSUE THREAD

**Issue by hsanjuan** [vector-im/riot-web#13710]
### Description

When building riot-desktop as an AppImage target, the application cannot start:

```
[10:42:46] ~/g/riot-desktop (develop|✚2) $ ./dist/Riot-1.6.0.AppImage
Seshat isn't installed, event indexing is disabled.
Couldn't find webapp files in any of: 
        /tmp/.mount_Riot-1w3RFZ5/resources/app.asar/webapp.asar
        /tmp/.mount_Riot-1w3RFZ5/resources/webapp.asar
        /tmp/.mount_Riot-1w3RFZ5/resources/app.asar/webapp
        /tmp/.mount_Riot-1w3RFZ5/resources/webapp
App setup failed: exiting Error: Failed to find webapp files
    at tryPaths (/tmp/.mount_Riot-1w3RFZ5/resources/app.asar/src/electron-main.js:114:11)
```

### Steps to reproduce

I built riot-web from source (1f1c1279ea654b509ca9ef2d7b7536e8107ab218).

Then I followed Riot-desktop README and symlinked the generated webapp folder per the instructions:

> \# Assuming you've checked out and built a copy of riot-web in ../riot-web
> ln -s ../riot-web/webapp ./

Then I built riot-desktop (829451c4c48bf21dfdad267bc714eed4487d9b10) but changed the target to app image:

```diff
     "linux": {
-      "target": "deb",
+      "target": "AppImage",
       "category": "Network;InstantMessaging;Chat",
       "maintainer": "support@riot.im",
       "desktop": {
```

Back when the electron wrapper was in this repository I could build the AppImage just fine and it worked.

`yarn run start` actually works. So I must be missing some packaging step?. How can I build the AppImage?

### Version information

- **Platform**: desktop
- **OS**: OpenSUSE Tumbleweed
- **Version**: `develop` (see above).

**Comment by t3chguy** [comment]
As the docs say, the symlinking method does *not* work for packaging.

> If you only want to run the app locally and don't need to build packages, you can provide the webapp directory directly:

**Comment by t3chguy** [comment]
I personally use something like https://github.com/vector-im/riot-desktop/pull/59/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17 to workaround and package a symlinked path into a `webapp.asar`

**Comment by hsanjuan** [comment]
Thank you, works now.
