### ISSUE TITLE
SSO Fallback does not work on Riot-desktop

### ISSUE THREAD

**Issue by artooro** [vector-im/riot-web#13719]
### Description

The new cross-signing SSO/SAML flow is working from riot-web but on riot-desktop when the user gets to the authorized web page, the desktop app never seems to recognize it.

### Steps to reproduce

- Upgrade encryption on riot-desktop
- Authenticate SAML login

Describe how what happens differs from what you expected.

I'd expect that the authentication and encryption upgrade completes.

### Version information

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? macOS
- **Version**: 1.6.1

**Comment by artooro** [comment]
This is related to https://github.com/matrix-org/synapse/issues/7484

**Comment by turt2live** [comment]
This is *not* related to https://github.com/matrix-org/synapse/issues/7484

The error is:
```
vendors~init.js:2 Uncaught Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.sendSync (ipc-renderer-internal.ts:13)
    at Object.invokeSync (ipc-renderer-internal-utils.ts:17)
    at Object.<anonymous> (init.js:40)
    at Object../lib/sandboxed_renderer/init.js (init.js:201)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

Which comes from the depths of electron.
