### ISSUE TITLE
What the green dot is for?

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13714]
![image](https://user-images.githubusercontent.com/14617699/82337722-c1c1e080-99f4-11ea-9f6c-0093bac46985.png)

**Comment by turt2live** [comment]
Presence.

Please ask questions in #riot-web:matrix.org

**Comment by 532910** [comment]
It looked like a bug for unread messages, and I've not found anything in the changelog.

**Comment by t3chguy** [comment]
Its in https://github.com/matrix-org/matrix-react-sdk/releases/tag/v1.7.6-rc.1
