### ISSUE TITLE
Missing CORS headers on matrix-client

### ISSUE THREAD

**Issue by smarek** [vector-im/riot-web#13712]
Having identity from matrix.org, being connected at URL [https://riot.im/app/#/room/!roomid:matrix.org]

From Google Chrome console

1. `Access to XMLHttpRequest at 'https://matrix-client.matrix.org/_matrix/client/r0/keys/upload' from origin 'https://riot.im' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
2. `POST https://matrix-client.matrix.org/_matrix/client/r0/keys/upload net::ERR_FAILED`
3. `Access to XMLHttpRequest at 'https://matrix-client.matrix.org/_matrix/client/r0/user/%40my.username%3Amatrix.org/filter/1' from origin 'https://riot.im' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

And many more, is this something that is expected, or is the API broken for CORS strict validating web clients?

**Comment by t3chguy** [comment]
`1.` sounds like a timeout causing the ACAO header to never arrive and thus CORS to trip.

This hypothesis is reinforced by `net::ERR_FAILED`

Do you have any extensions blocking things like Privacy Badger?

For future support queries use https://matrix.to/#/#riot-web:matrix.org

**Comment by smarek** [comment]
`net::ERR_FAILED` is because preflight check did not succeed, and I have uBlock disabled for riot.im website, no other blocking extension used

**Comment by t3chguy** [comment]
Its likely to be matrix.org being slow but it isn't a riot-web issue. As per the Matrix spec, things must serve an ACAO to be web-compatible.
