### ISSUE TITLE
Riotbot: "Download Hi there and welcome to Riot!" Broken link

### ISSUE THREAD

**Issue by alignwaivers** [vector-im/riot-web#13727]
I started to chat with riotbot and got this message
```
Riot-bot sent an image
Download Hi there and welcome to Riot! (8.34 KB)
Hi there and welcome to Riot! My name is Riot-bot and I am here to help you get started using Riot. Would you like me to show you around the features of Riot?
### Steps to reproduce
```
But the download link produces a json file containing:
```
errcode	"M_NOT_FOUND"
error	"Not found [b'matrix.org', b'ljxwjBuEVUZlUoXrTvweVwjR']"

```
- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?   Couldn't find the report bug option in settings, so no 

![image](https://user-images.githubusercontent.com/26056586/82403264-44f22f00-9a13-11ea-8224-ac2f48f62dd5.png)

- **Platform**: web (in-browser) or desktop?

For the web app:

Firefox v 75.0
Ubuntu 18.04 (KDE neon User Edition 5.18)
riot.im/app

Love riot.im, thank you for the great work! I'm just trying to sort out some finer usage details cause there isn't so much documentation, and was assuming riotbot would help me out with that hah!

**Comment by turt2live** [comment]
riotbot is a bit dead at the moment - we aren't encouraging its use in the app. Instead, #riot-web:matrix.org is a better place to ask questions and get help.

We do need to update our FAQ and general documentation though :(
