### ISSUE TITLE
Key backup: Backup has a signature from unknown session

### ISSUE THREAD

**Issue by rda0** [vector-im/riot-web#13730]
### Description

The key backup shows: `Backup has a signature from unknown session with ID XRSPGSUYLK`.
The session ID is not listed above. I don't see anything else misbehaving related to e2ee
and cross-signing.

![signature_from_unknown_session](https://user-images.githubusercontent.com/6731714/82445537-479d6480-9aa5-11ea-82af-21b3440c9dbd.png)

I am not sure how I would resolve this without loosing my encrypted message history.

### Version information

Riot 1.6.1. I fist noticed this with the official release of Riot 1.6.0, but it could have been introduced with one of the 1.6.0 RCs. I also use RiotX.

- **Platform**: web + desktop app
- **Browser**: Firefox 76.0.1 (64-bit)
- **OS**: Windows 10

**Comment by rda0** [comment]
When I try to submit debug logs I get:

`Failed to send logs: m.secretStorageKeyNeedsUpgrade is not a function`

**Comment by dbkr** [comment]
This isn't a bug - it just means the a device that has signed the backup has been logged out. We should probably move these advanced details somewhere people won't unwittingly stumble over them.

The rageshake error should be fixed if you refresh /develop, which I assume is where you experienced it, but you didn't say.

**Comment by rda0** [comment]
Thanks for explaining that. Since "unknown" is colored red, I assumed something "bad" has happened.

The rageshake error was in the Windows desktop app and in a self-hosted riot-web https://riot.phys.ethz.ch (both on the official 1.6.1 release).

**Comment by promi** [comment]
Yes, please don't color it red as that means "something is wrong" to me as well.
