### ISSUE TITLE
Disable JS source mappings

### ISSUE THREAD

**Issue by bobvandevijver** [vector-im/riot-web#13731]
Apparently, the production builds still contain source source mappings for the javascript files.

For example, now on https://riot.im/app, you can see the following files:
- [JS: riot-web-app.js](https://riot.im/app/bundles/50caaaf01ea4c840e4b6/riot-web-app.js)
- [JS: riot-web-app.js.map](https://riot.im/app/bundles/50caaaf01ea4c840e4b6/riot-web-app.js.map)

There are multiple reasons on why you shouldn't deploy these files, but probably the most common one is "it just isn't necessary", and in this case it doesn't even add anything.

The build can probably also be sped up when you exclude the generation of the files.

**Comment by t3chguy** [comment]
It was recently turned back on, on purpose. It was part of the decoder-ring project to help us regain the ability to make sense of the logs users submit from riot.im/app which requires the sourcemaps.

https://riot.im/app/decoder-ring/ fwiw

**Comment by jryans** [comment]
> There are multiple reasons on why you shouldn't deploy these files

Could you elaborate? They seem quite useful for debugging production issues and decoding log files.

**Comment by dbkr** [comment]
Yep, these are very useful for us to decode stack traces from the wild: we could keep them to ourselves but Riot is an open source app so there's no reason not to share them with the world so other people might be able to debug too. They're in a separate file so the browser won't even look for them unless you open developer tools.

**Comment by bobvandevijver** [comment]
> They seem quite useful for debugging production issues and decoding log files.

This is absolutely true!

Usually, you don't deploy them because:
* It takes up unnecessary space and time (it currently takes up about 15-20% of the uncompressed build artifact of Riot). This does not look like much, but smaller is always better, most certainly when you keep building and deploying in a steady rate. There are also other deployments of your tool out there that get these maps pushed probably without doing anything with it.

* You do not want users to see the original code but that obviously doesn't make any sense for an open source project.

* It currently doesn't have directly added value in the debugger as it does not know where the actual sources are.

> They're in a separate file so the browser won't even look for them unless you open developer tools.

Guess what I was doing when I got presented with an error 😄 
```
Could not load content for webpack:///./node_modules/@babel/runtime/helpers/arrayWithHoles.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```

I might have been to blunt in my initial post, but it was mostly meant as an possible optimization: it appears there is a good reason for deploying them, and not just a simple oversight. 

There are still optimizations possible, such as putting it in a separate package, serving them from a dedicated location, putting them only in your debug tooling etc, but I can understand if that is something you do not need at this time. That's why I will close this now, thank you for the swift responses!
