### ISSUE TITLE
"Chat with Riot Bot" button text-wrapping

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13746]
### Description

![image](https://user-images.githubusercontent.com/1342360/82548743-b9cc8280-9b53-11ea-95ca-7479d58a286f.png)

This is on latest develop right now. Application is maximized on a 1080p monitor.

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
We should get rid of that, Riot Bot is depr

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/13784
Text wrapping was caused by change of default font-size to 16px which was reverted anyhow
