### ISSUE TITLE
(propsal) Remove IndicatorScrollbar

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#13749]
I'm fairly sure the `IndicatorScrollbar` logic doesn't make a huge difference to rendering.

Here's a before and after for being scrolled to the top, with the gradient logic being unconditional in the second screenshot:
<img width="269" alt="Screenshot 2020-05-21 at 13 42 02" src="https://user-images.githubusercontent.com/3935731/82560473-6f560080-9b69-11ea-883f-d181f7a149c7.png">
<img width="284" alt="Screenshot 2020-05-21 at 13 44 27" src="https://user-images.githubusercontent.com/3935731/82560477-70872d80-9b69-11ea-86b4-1b0c24d5ab23.png">

However, I suspect the `checkOverflow()` logic is quite expensive, as it does a lot of out-of-band DOM measurement and changes during scroll events.

Is there some other reason this logic exists?  I think we can probably remove it.

```
diff --git a/res/css/structures/_RoomSubList.scss b/res/css/structures/_RoomSubList.scss
index 2c53258b0..e31956028 100644
--- a/res/css/structures/_RoomSubList.scss
+++ b/res/css/structures/_RoomSubList.scss
@@ -166,7 +166,7 @@ limitations under the License.
 
 // overflow indicators
 .mx_RoomSubList:not(.resized-all) > .mx_RoomSubList_scroll {
-    &.mx_IndicatorScrollbar_topOverflow::before {
+    &::before {
         position: sticky;
         content: "";
         top: 0;
@@ -180,8 +180,5 @@ limitations under the License.
         background: linear-gradient(to top, $panel-gradient);
     }
 
-
-    &.mx_IndicatorScrollbar_topOverflow {
-        margin-top: -8px;
-    }
+    margin-top: -8px;
 }
```

**Comment by foldleft** [comment]
@bwindels I think you wrote the original logic – does the reason for it being there still exist?

**Comment by bwindels** [comment]
The reason it exists is to remove the gradient if we're hitting an edge of the viewport. In your example the gradient is not noticeable in both screenshots, perhaps because there the white space on top is big enough to make it not noticeable. This is not the case on the bottom of the letter box though. Also unsure if this is as designed. The room breadcrumbs on top of the left panel also use this though, and there the gradient is noticeable.

**Comment by foldleft** [comment]
Alright. I think it's not affecting roomlist, but I didn't realise it was also in breadcrumbs
