### ISSUE TITLE
DM icon failing to load looks like a UI artifact

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#13755]
![image](https://user-images.githubusercontent.com/2072976/82582183-91f81180-9b89-11ea-97c5-1d514493c123.png)

On reload, the text and icon were nowhere to be seen :/

**Comment by turt2live** [comment]
What DM icon? We shouldn't have this thing anymore.

**Comment by t3chguy** [comment]
Indeed, what version is this

**Comment by Half-Shot** [comment]
`v1.6.1`

**Comment by t3chguy** [comment]
I cannot see it existing in the codebase anymore. `dm` as a string only exist in tests/enums not in alt texts of images

**Comment by Half-Shot** [comment]
Willing to close this and say my browser was caching or something, this was on a modular host.

**Comment by Half-Shot** [comment]
(I can no longer repro it)
