### ISSUE TITLE
Emoji picker layout breaks when names have multiple lines

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13754]
<img width="382" alt="Screenshot 2020-05-21 at 17 20 09" src="https://user-images.githubusercontent.com/4626865/82580692-6a07ae80-9b87-11ea-8476-40d67aa61ad0.png">

Latest /develop. Chrome.

**Comment by t3chguy** [comment]
This is caused by the default font size change.
What should the layout look like when the copy exceeds one line, should it grow that bottom container?
