### ISSUE TITLE
Feature "Always show message timestamps" not working

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#13759]
I want to see timestamps of each post in room timeline always, but now it show only on mouse hover. I see option "Always show message timestamps" in Riot settings, but enabling it (and refreshing browser) don't show timestamps, all works like before. Seems it becomes broken after some other changes?

_P. S. Also will be very good to see exact date of messages, especially when I scroll up too far, but this is other issue https://github.com/vector-im/riot-web/issues/7575_

**Comment by dbkr** [comment]
I'm assuming this is on /develop? (The templates are there to help!)

**Comment by t3chguy** [comment]
This will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4615

**Comment by MurzNN** [comment]
> I'm assuming this is on /develop? (The templates are there to help!)

On stable, staging and develop too.

**Comment by dbkr** [comment]
Fwiw I tested and this bug did not make it to the released builds, only /develop.

**Comment by turt2live** [comment]
there is a separate issue where a whole bunch of settings don't affect the timeline right away - switch rooms to see their effects.
