### ISSUE TITLE
Keyboard shortcuts aren't working in the latest Riot Desktop Nightly.

### ISSUE THREAD

**Issue by bwinton** [vector-im/riot-web#13763]
### Description

Well, option-shift-up/down and option-up/down anyways… Command-k seems to work.

### Steps to reproduce

- Press option-shift-down on a Mac.

Describe how what happens differs from what you expected.

Nothing happens. I would expect it to go to the next unread room. 😉

### Version information

- **Platform**: desktop

For the desktop app:
- **OS**: macOS
- **Version**: 2020052201

Also, it worked yesterday, so it's likely something from yesterday/this morning.
(Unfortunately, it looks like there were a bunch of dependency updates since then, so, uh, good luck? 🙂)

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/4253

![image](https://user-images.githubusercontent.com/2403652/82669132-c5db4180-9c32-11ea-907c-7bfe3670e991.png)
