### ISSUE TITLE
Can't download files shared on Riot 

### ISSUE THREAD

**Issue by nedsomerville** [vector-im/riot-web#13761]
### Description

I can't download the files (word docs) shared in the room i'm in on Riot. 

### Steps to reproduce

- I click the file hyperlink in order to download it. 
- I'm in chrome browser, on a chromebook.
- The file doesn't download. Instead, it opens a tap with a grey screen (see screenshot) and nothing happens. 

Log: sent/not sent?  
![Screenshot 2020-05-22 at 12 45 46 PM](https://user-images.githubusercontent.com/65764722/82660218-40539380-9c2a-11ea-92bd-4da1b7907279.png)
  

### Version information

- In browser. 

For the web app:

-  Chrome, Version 81.0.4044.141 (Official Build) (32-bit)

- https://riot.im/app/#/room/!mzAtZJgFdFltMeFJJN:matrix.org

**Comment by dbkr** [comment]
dup of https://github.com/vector-im/riot-web/issues/11972
