### ISSUE TITLE
Allow picking a recovery key file upon login / other places where you need the SSSS key

### ISSUE THREAD

**Issue by Sorunome** [vector-im/riot-web#13766]
![Screenshot_2020-05-22_15-35-46](https://user-images.githubusercontent.com/2433620/82674179-35f1c380-9c43-11ea-8333-76bb375c5321.png)

When logging in and verifying yourself via SSSS or other places when you need the SSSS key you have to manually enter your passphrase or your key. It might be nice to be to have some kind of "Chose keyfile" dialog to be able to upload/use a keyfile you previously downloaded/created when setting up cross-signing etc. Else you would have to manually open said keyfile and paste its contents....that seems sub-ideal

**Comment by dbkr** [comment]
Using design from https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=5050%3A30269 but could do with some design assistance on this one: I'm currently displaying feedback on validity of the recovery key by using the Field control which has a tooltip indicating validity. Unfortunately with the upload button, this tooltip goes straight over the button:

![Jun-04-2020 15-16-33](https://user-images.githubusercontent.com/986903/83768377-9b4ba880-a676-11ea-8991-110740331579.gif)

 * How should we display feedback without getting in the way of the other from control?
 * I've put the contents of the file into the box once uploaded and was planning to use the same tooltip feedback to indicate whether it's valid or not - does this seem reasonable?
 * How should we display feedback if the file the user picked isn't something that will fit in the box? (They picked an image or something)

**Comment by dbkr** [comment]
https://github.com/matrix-org/matrix-react-sdk/tree/dbkr/recovery_key_upload has my progress on this so far

**Comment by nadonomy** [comment]
@dbkr for this, I think we want to display the feedback below the input box, rather than in a tooltip. I'll message you to figure out what UI comps we need.
