### ISSUE TITLE
FilePanel CSS has regressed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13779]
![Screenshot 2020-05-23 at 11 37 23](https://user-images.githubusercontent.com/1294269/82728666-d00c4700-9ce9-11ea-9f9f-8a659f66471a.png)

**Comment by t3chguy** [comment]
Notif Panel too 
![image](https://user-images.githubusercontent.com/2403652/82728686-03e76c80-9cea-11ea-9199-53fe662b56ed.png)
