### ISSUE TITLE
Riot shouldn't be prompting you to talk to Riot Bot on the login page if RiotBot has been turned off.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13784]
<img width="449" alt="Screenshot 2020-05-23 at 19 56 58" src="https://user-images.githubusercontent.com/1294269/82738464-a7a73b80-9d2f-11ea-90d3-145c6963a61b.png">

**Comment by t3chguy** [comment]
What do we want the welcome page to look like without that button?

**Comment by t3chguy** [comment]
Design from Nad:

![image](https://user-images.githubusercontent.com/2403652/83174549-74d7bb80-a112-11ea-96f1-aea07c825402.png)
