### ISSUE TITLE
Switching the default font size to 16px from 15px makes everything look a bit Fisher Price (and breaks layout)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13785]
Here's an example of the 'talk to riotbot' button layout being broken in English by develop having pumped up the font size from 15px to 16px.

<img width="449" alt="Screenshot 2020-05-23 at 19 56 58" src="https://user-images.githubusercontent.com/1294269/82738935-6f096100-9d33-11ea-9dcb-6a8a7d4defc5.png">

Personally I'd much rather keep it at the original size, and let people who dislike that go and bump it up in settings rather than vice versa.

It's also causing the LeftPanel to look really crowded by default.

**Comment by bwindels** [comment]
We should probably make a call either way before the next release.

**Comment by bwindels** [comment]
@nadonomy wdyt?

**Comment by nadonomy** [comment]
@bwindels in lieu of being able to spend real time on this in this release cycle the suggestion to revert to 15px seems sane to me. But we absolutely should return to this as a part of FTUE to ensure the out of the box legibility and info density is as optimal as it can be for new users.
