### ISSUE TITLE
Easy access to bulk invitations

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#13789]
In Settings - Security there is an option to either accept or reject all open invitations.  This option should be available when clicking on the number of outstanding invitations above the room list.  Clicking that number should bring up a check list, where the user can 'check all', 'clear all', or set/clear individual check marks, before clicking a 'Go!' button.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/11773
