### ISSUE TITLE
"Something went wrong" during search

### ISSUE THREAD

**Issue by martinvonwittich** [vector-im/riot-web#13798]
### Description

When I'm using the search, I'll get an error "something went wrong" when I click on "All rooms".

I'll submit debug logs linked to this issue.

### Steps to reproduce

- Open a direct message room
- Search for "a b c"
- Click on "All rooms"

The message "Something went wrong appears".

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 1.6.2

**Comment by t3chguy** [comment]
This is a missing null-guard on search results from rooms which you have left:
https://github.com/matrix-org/matrix-react-sdk/blob/798e7a1f86605b4c45fe9694174f3d9edc8eb457/src/components/structures/RoomView.js#L1314

**Comment by bwindels** [comment]
We might want to match synapse behaviour and not search in left rooms here. Should seshat remove those from it's index @poljar, wdyt?

**Comment by poljar** [comment]
From the Seshat side of things, removing a room would need a new API and would be O(n) to remove all events from the index.

From a user perspective, I'm not sure that I would want those search results to be gone. Maybe I remember a conversation happened but I forgot that I left the room. Though if I delete/recreate my index the results will be gone as well. Not sure if we want that inconsistency.

**Comment by poljar** [comment]
Another point, I don't think we should depend on that Synapse specific behavior. The spec states this quite clearly [here](https://matrix.org/docs/spec/client_server/latest#id104).

> The search API allows clients to perform full text search across events in all rooms that the user has been in, including those that they have left. Only events that the user is allowed to see will be searched, e.g. it won't include events in rooms that happened after you left.

**Comment by t3chguy** [comment]
This certainly raises good reason to fix https://github.com/matrix-org/matrix-react-sdk/blob/798e7a1f86605b4c45fe9694174f3d9edc8eb457/src/components/structures/RoomView.js#L1310-L1313 as other homeservers may break Riot too. Good catch @poljar
