### ISSUE TITLE
riot-desktop crashes when enabling experimental feature

### ISSUE THREAD

**Issue by commando-crypto** [vector-im/riot-web#13791]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

The app just crashed

### Steps to reproduce

- Enable 

Describe how what happens differs from what you expected.

Log: sent

### Version information

- **Platform**: riot-desktop

- **OS**: GNU/Linux (NixOS)
- **Version**: 1.5.15

**Comment by commando-crypto** [comment]
"Failed to send logs: End-to-end encryption disabled" - doesn't make sense, i use e2ee regularly.

**Comment by t3chguy** [comment]
> 1.5.15

This is an old version with bugs.
