### ISSUE TITLE
Make auth argument in the register request compliant with r0.6.0

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#13799]
Work on this has been proposed with https://github.com/matrix-org/matrix-react-sdk/pull/4347 and https://github.com/matrix-org/matrix-js-sdk/pull/1304, with the latter being blocked on unravelling the registration code apparently. So finding a way to unblock the js-sdk PR is the main action point here.

This is needed to make riot work with Conduit, as Riot apparently isn't fully spec compliant. So they are using a patched Riot currently it seems.

**Comment by turt2live** [comment]
Optimistically labelling this as a release blocker so it can make it into the RC next week :D

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4347 and https://github.com/matrix-org/matrix-js-sdk/pull/1304.
