### ISSUE TITLE
change port in dev environment 

### ISSUE THREAD

**Issue by mohsenrezaeis** [vector-im/riot-web#13804]
### Description

can we change the port instead of 8080? i follow https://github.com/vector-im/riot-web/tree/03414d92d00feafc8035c86710fd94c3a7e1f480#setting-up-a-dev-environment to setup the dev environment. based on this after running "yarn start" i should see the page in http://127.0.0.1:8080/ . but in my computer this port is already assigned to another app.

- **OS**: Windows
- **Platform**: web (in-browser)

**Comment by t3chguy** [comment]
https://webpack.js.org/configuration/dev-server/#devserverport
