### ISSUE TITLE
Cannot connect to integration manager

### ISSUE THREAD

**Issue by jerryn-acceleron** [vector-im/riot-web#13802]
I have setup a new matrix server in my office. Here I am getting "Cannot connect to integration manager" error in riot.
What is the issue or where i have to troubleshot. 

I already have another matrix server in my office (it is powered off now) and that doesn't have this error message.
I have followed the same procedure for both the installation.

Can anyone please help me on this issue.

**Comment by turt2live** [comment]
It's best to troubleshoot this in #riot-web:matrix.org first and open an issue if there's a cause we are able to fix.
