### ISSUE TITLE
Blank page on KaiOS

### ISSUE THREAD

**Issue by piegamesde** [vector-im/riot-web#13800]
### Description

I tried opening <https://riot.im/app> in the KaiOS browser and I only get a black page without content.

### Steps to reproduce

1. Get a running phone KaiOS (that might be the hardest part ^^)
2. Open the browser
3. Visit <https://riot.im/app>

### Version information

- **Platform**: web
- **Browser**: Probably some Firefox
- **OS**: KaiOS 17.00
- **URL**: <https://riot.im/app>

**Comment by turt2live** [comment]
We don't really support mobile browsers, sorry. If you're using the latest version of firefox, it should probably be fine though the mobile apps themselves are a much better experience.

**Comment by piegamesde** [comment]
I know. Is it possible to at least put a "this is not supported, please use XYZ" notice instead of a blank page?

> If you're using the latest version of firefox

I can't find any version information, but based on my experience I assume it won't be the newest one. The sad thing is that since KaiOS is a web operating system, where there is no concept of a "native app". All applications will have to run in their web engine, be it in the browser or not.

**Comment by turt2live** [comment]
If the browser is so outdated we probably won't be able to show anything more than a blank page, unfortunately. We support extremely modern and maintained browser versions, and our old browser checks go back only a few years. Anything beyond that is just so old we can't feasibly even support it enough to say it is unsupported.
