### ISSUE TITLE
riot-desktop electron wrapper does not minimize into the taskbar

### ISSUE THREAD

**Issue by ilu33** [vector-im/riot-web#13801]
This actually belongs to the electron wrapper of riot-desktop but since for some reason there is no issue tracker for that project I'm reporting here. 

Closing the window does not minimize to taskbar or system tray but into nirwana. Program still runs but no way to reopen the window. "Close to taskbar" is checked in the settings. Other programs manage just fine, so taskbar and system tray are functional.

System: Debian 10 with XFCE, riot-desktop 1.6.2 from your repo

Logs being sent: no (I'm not sending logs I haven't seen and sanitized myself)

**Comment by t3chguy** [comment]
Do you have a visible tray icon? If not then your issue is https://github.com/vector-im/riot-web/issues/12518

**Comment by t3chguy** [comment]
Assuming it is that issue as stock XFCE doesn't support SNI/libappindicator without `sni-qt` or `snixembed`.

**Comment by ilu33** [comment]
Its most probably that issue. Sorry for not searching enough. And installing sni-qt or xfce4-statusnotifier-plugin did not help, but you probably knew that. Now default app settings - which rely on tray icon being present - really mess things up for new users.

**Comment by ilu33** [comment]
Just fyi (and for anybody else having this problem) I got it working. xfce4-statusnotifier-plugin in fact did help - it needs to be installed and the respective widget needs to be placed to the panel. Whether installing sni-qt did anything I don't know.
