### ISSUE TITLE
Either Synapse or Riot doesn't backfill gappy syncs anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13815]
I had a client closed for a while, and reopening it shows only the 5 most recent messages in the room. There's certainly more than 5 today. 

This is on matrix.org

**Comment by bwindels** [comment]
Could this be the sync cache that got truncated for that room, and the backfill being slow?

**Comment by turt2live** [comment]
yes, and yes.

**Comment by turt2live** [comment]
Err, it could be that but not sure. Either way this seems to have gone away so was probably a synapse issue if some sort.
