### ISSUE TITLE
e2e mechanism problem key restored operation no stable work

### ISSUE THREAD

**Issue by CyberMan571** [vector-im/riot-web#13812]
> Unable to load event that was replied to, it either does not exist or you do not have permission to view it.

my friend reply to my message then gives this warning
so this is e2e encryption problem

In permission settings, there is no problem! If you insist, show me before you say topic closed! I didn't play(change) with any settings! Do not topic closed

_Originally posted by @CyberMan571 in https://github.com/vector-im/riot-web/issues/13810#issuecomment-634033858_

**Comment by turt2live** [comment]
That message is accurate then - you may not have permission to view it.

Please visit #riot-web:matrix.org for support/troubleshooting before opening issues.

**Comment by CyberMan571** [comment]
please, send full link

**Comment by t3chguy** [comment]
https://matrix.to/#/#riot-web:matrix.org
