### ISSUE TITLE
no can show my all messages, the encryption problem

### ISSUE THREAD

**Issue by CyberMan571** [vector-im/riot-web#13810]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    
I send it now

### Version information
riot-web version: 1.6.2
olm version: 3.1.3

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
riot.im/develop / riot.im/app / I tested in both
For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y 
I use riot.im all os an web version android and tested but I can't see my all message on all room in all platform
 I had no problem and  I could see my messages   last night however I can't see  my all messages  today 

I had decided pass to end to end encryption and the problem arose

**Comment by CyberMan571** [comment]
> Unable to load event that was replied to, it either does not exist or you do not have permission to view it.

my friend reply to my message then gives this warning
so this is e2e encryption problem

**Comment by CyberMan571** [comment]
My Friends and room members see my sending message but  I, I can't  see
the messages, text are visible  in source

**Comment by turt2live** [comment]
You may not have permission to see the event. Please troubleshoot in #riot-web:matrix.org before opening an issue.

**Comment by CyberMan571** [comment]
In permission settings, there is no problem! If you insist, show me before you say topic closed! I didn't play(change) with any settings! Do not topic closed

**Comment by CyberMan571** [comment]
![Screenshot 2020-05-26 18:26:42](https://user-images.githubusercontent.com/30759335/82919295-5e403180-9f65-11ea-93ed-9ab9f118232c.png)
my messages are not visible in the messaging board table go, you look sumbitted(shipped)  bug report, please
