### ISSUE TITLE
riot.im/app -> riot.im | app.riot.im

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13826]
I'd prefer to see the riot application (https://riot.im/app) directly on https://riot.im with `about` link to https://about.riot.im on the main page (and do not redirected from riot.im to about.riot.im). Or, less preferred, on https://app.riot.im

Of course, there is no significant reason for this.

One insignificant is to make it scannable by https://observatory.mozilla.org/
(https://github.com/mozilla/http-observatory-website/issues/119, https://github.com/mozilla/http-observatory-website/issues/219)

One more that riot.im is easier to remember and type than riot.im/app

**Comment by t3chguy** [comment]
> app.riot.im

this would force everyone to have to log back in.

**Comment by 532910** [comment]
Nope, app.riot.im can be added in addition to riot.im/app.

**Comment by t3chguy** [comment]
That would cause session proliferation as users mistakenly switch between the two.

**Comment by 532910** [comment]
Yep ):
But I'm for the first way: riot.im/app -> riot.im

**Comment by 532910** [comment]
https://app.element.io
Fixed now
