### ISSUE TITLE
Certain room's notifications are becoming (noisy) without me touching them

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13820]
### Description

I'm randomly getting bings now in rooms that have always been set to (All Messages). Now, clicking on their settings, they have been set to (Noisy notifications).

It's only a couple rooms.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Debian
- **URL**: This is using a fork of Riot at https://app.chat.horse, for which is source code is located at https://github.com/chat-horse/riot-web, so take it with a grain of salt. But perhaps you may come across something.

**Comment by anoadragon453** [comment]
Actually, going back a week in my homeserver's logs, I can't see anything related to those push rules being set. So this may just be something that my local Riot randomly decided.

**Comment by turt2live** [comment]
is this possibly your server being slow and not handling the call fast enough? Riot tries to eagerly show the change here, but if the server isn't responding fast enough and you refresh riot then the request is lost.

**Comment by anoadragon453** [comment]
The rooms were never set to Noisy.

**Comment by turt2live** [comment]
Considering the age of the fork, I'm inclined to close this until it can be proven to happen on mainline.
