### ISSUE TITLE
Upgrading encryption gets stuck on "Setting up keys"

### ISSUE THREAD

**Issue by spinda** [vector-im/riot-web#13827]
### Description

I'm getting stuck on the "Setting up keys" spinner on https://chat.mozilla.org at the end of the "Upgrade your encryption" flow. It sounds similar to #13269, but that's marked as fixed.

### Steps to reproduce

- Follow the "Upgrade your encryption flow"
- End up stuck on the "Setting up keys" spinner

### Version information

- **Platform**: web, in-browser

For the web app:

- **Browser**: Firefox 76.0.1
- **OS**: Windows 10
- **URL**: https://chat.mozilla.org (riot-web version: v1.6.1, olm version: 3.1.3)

**Comment by spinda** [comment]
I'm actually unable to send debug logs because of the following error:

```
Failed to send logs: m.secretStorageKeyNeedsUpgrade is not a function
```

![image](https://user-images.githubusercontent.com/7958605/83082207-96b04000-a037-11ea-888e-41de3c79a52b.png)

**Comment by spinda** [comment]
Immediately after submitting this ticket, I was able to get through after doing "Clear cache and reload" from Settings -> Help & About. I'll leave this open, though, since the underlying issue remains.

**Comment by bwindels** [comment]
The error when submitting debug logs should be fixed in 1.6.2. Could you try submit your logs again?

**Comment by jryans** [comment]
I assume by now the relevant logs would have fallen away from the log store, and upgrade keys is a one-time step, so I don't know if we have something we can investigate clearly. If someone else hits this and can submit logs, please let us know.

**Comment by jryans** [comment]
@wagnerand is able to reproduce a similar issue, and has submitted debug logs. @bwindels, I wonder if any of your recent work might help here?

**Comment by bwindels** [comment]
@jryans left a comment on the rageshake, short answer: some bootstrap operations don't seem to finish indeed, but not sure why when looking at the logs. Given that, hard to tell if the bootstrap work will help here, but with what is planned currently, it might very well not help.

**Comment by wagnerand** [comment]
I just tried this again and it worked for me now.

**Comment by jryans** [comment]
Aha okay, great. Hopefully this is indeed fixed now.
