### ISSUE TITLE
Riot gets really slow if the reactions/messages ratio of what's currently displayed is high

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#13836]
### Description

Riot gets really slow for me (and some times unresponsive for a few seconds) if there's a lot of reactions but only a few messages sent, like in the Synapse or Riot announcement rooms.
I wouldn't be surprised if this had already been reported, but I couldn't find any issue for it.

### Steps to reproduce

- Go to e.g. `#homeowners:matrix.org` in Riot
- Witness the slowness, and hear your computer's fans go crazy

Log: sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 76.0.1, have also seen that happen in older versions
- **OS**: Arch Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/riot-web/issues/3261 (riot is hiding the events, but rendering them still)
