### ISSUE TITLE
video file upload previews show up excessively large when sent from nheko

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/riot-web#13839]
### Description

If I am running Riot in my web browser and Nheko as well, posting a video from Nheko shows up gigantic on the Riot screen. It's the size of the actual full video instead of being shrunken to something manageable. It adds a horizontal scrollbar and everything.

### Steps to reproduce

- post a video from Nheko in a chat to someone 
- view that same chat from Riot-web (I had both open at once, if it matters)

### Describe how what happens differs from what you expected.
Normally uploaded videos have a very small preview, with the option to get bigger when you actually watch them.

Logs being sent: yes

![2020-05-28-105546_grim](https://user-images.githubusercontent.com/3146494/83164442-76c95c80-a0c9-11ea-89bb-17bc1c4845c1.png)
(the whole video preview is cut off on the right because of how wide it is)
### Version information

- **Platform**: web (in-browser) or desktop?

web

- **Browser**: Chrome, Safari, Firefox? which version?
Icecat (Firefox) 68.8.0
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Guix System GNU/Linux
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
https://webchat.weho.st/
riot-web version: 1.5.6

**Comment by aaronraimist** [comment]
Update to the latest version of Riot or use riot.im/app.

I can reproduce on 1.5.6 but it is fixed on the current version which is 1.6.2.

**Comment by Soundtoxin** [comment]
This seems to happen still on p2p.riot.im. Not sure what version it uses, settings list "unknown version".
