### ISSUE TITLE
Riot doesn't send `identifier` when changing password

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13837]
### Description

According to the spec [for `/account/password`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-account-password), clients should [be sending an `identifier` dict](https://matrix.org/docs/spec/client_server/r0.6.1#password-based) for `m.login.password` User-Interactive Auth challenge responses.

Here, Riot is using the deprecated `user` parameter, which still works, but it should be updated to send an `identifier` dict as well, as was done for a few endpoints in https://github.com/matrix-org/matrix-react-sdk/pull/3211.

Noticed by @jcgruenhage in https://github.com/matrix-org/synapse/issues/5665#issuecomment-623417707

**Comment by turt2live** [comment]
We also send the wrong field altogether: 
```
            await this.client.setPassword({
                type: "m.login.email.identity",
                threepid_creds: creds,
            }, this.password);
```

That should be `threepidCreds` in the `identifier` object.
