### ISSUE TITLE
Add option to re-ask info from server

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#13832]
Sometimes message info gets lost, for instance because of local lack of storage.  In such cases, after repairing the local problem, the server may not know it has to resend the information.  A button or link to tell it so near the error message would be helpful.

**Comment by Biep** [comment]
@tulir told me:
You should probably specify in the issue that you're talking about decryption keys not being stored because the disk is full, currently it's way too vague.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/83135942-8c954c80-a0de-11ea-81e7-bc9e8b434527.png)

The button is right there, `Clear cache and reload`

**Comment by t3chguy** [comment]
> You should probably specify in the issue that you're talking about decryption keys not being stored because the disk is full, currently it's way too vague.

There isn't a way to get those decryption keys again, the server doesn't store them.
You would have to re-ask the other party to send them. Which is https://github.com/vector-im/riot-web/issues/12275

**Comment by Biep** [comment]
(A) That didn't help for messages originating at other servers.  (Though a few hours later one of them did come through spontaneously.)
(B) For the average user, there is no link between the problem and that button.  I was asking for something *in the error message*.  "Request keys from your other devices" could have been a button hidden in the setting too, but it isn't (and rightly so).

**Comment by t3chguy** [comment]
The originating server won't have a copy of the decryption keys either, it is end-to-end encryption.

**Comment by Biep** [comment]
Well - it ought to have an encrypted version of them, oughtn't it?  After all, how could I ever get it otherwise?

**Comment by t3chguy** [comment]
> "Request keys from your other devices" 

this is scoped to a single encryption session so it couldn't be in Settings

**Comment by t3chguy** [comment]
> Well - it ought to have an encrypted version of them, oughtn't it? After all, how could I ever get it otherwise?

to_device messages which carry decryption sessions are not kept around, especially on the outbound server.

**Comment by Biep** [comment]
All right - but a link that effectually repopulates the cache (and if possible does more) *at the place of the problem* would be very user-friendly.

> to_device messages which carry decryption sessions are not kept around, especially on the outbound server.

All right - so that server should ask the sender's client, as soon as it is in the air again?

**Comment by t3chguy** [comment]
> so that server should ask the sender's client, as soon as it is in the air again?

This is not something possible in Matrix currently, track https://github.com/vector-im/riot-web/issues/12275

**Comment by t3chguy** [comment]
>  but a link that effectually repopulates the cache (and if possible does more) at the place of the problem would be very user-friendly.

Clearing cache won't help you with decryption errors typically so it'd cause additional server load for users clicking it whenever they see it and no benefit most of the time.

**Comment by Biep** [comment]
Yes, I was thinking of something like a very localised version of #12275 - just getting the keys for *this* message.  Given that they had already been sent to exactly that session, probably no explicit permission would be needed either.

**Comment by Biep** [comment]
Clearing the whole cache would indeed be overkill - it should be only the bit related to the offending message.

**Comment by t3chguy** [comment]
The Matrix protocol's sync API doesn't allow such scope. Especially as the protocol won't know which encrypted to_device messages pertain to which encrypted messages.

**Comment by Biep** [comment]
OK.  So it blocks on that.  Pity.
