### ISSUE TITLE
Account creation always fails

### ISSUE THREAD

**Issue by Wangmmx** [vector-im/riot-web#13833]
I just want some WND to continue my test, but I can't register in Riot.
![image](https://user-images.githubusercontent.com/22836587/83133614-b7e75e00-a115-11ea-80ab-4eda59988e3d.png)
email-address:
wangmmx0725@163.com
I'm sure this is a working and normal mailbox, What kind of email format is available?

**Comment by Wangmmx** [comment]
I put the problem in the wrong category, sorry

**Comment by t3chguy** [comment]
This is not a Riot issue, that is a response from the Matrix server on which you are trying to register. Contact the admin of that server about their email domain whitelist/blacklist choices.
