### ISSUE TITLE
Icon notification badge on PWA

### ISSUE THREAD

**Issue by artooro** [vector-im/riot-web#13840]
### Description

Currently in the Riot PWA the icon does not change if you have any notifications.  
Google just launched their PWA for Google Chat, which does add a badge when you have notifications.  I'm comparing them only for example purposes.

<img width="40" alt="Screen Shot 2020-05-28 at 11 56 41" src="https://user-images.githubusercontent.com/393395/83164678-81d8b880-a0da-11ea-844c-899af1df7231.png">

<img width="37" alt="Screen Shot 2020-05-28 at 11 56 50" src="https://user-images.githubusercontent.com/393395/83164674-81402200-a0da-11ea-9008-ff3228e83b30.png">

As we can see that it is possible, it would be nice to add this UX functionality to Riot as well.

- **Browser**: Brave 1.9.72
- **OS**: macOS
- **URL**: self-hosted 1.6.2

**Comment by bwindels** [comment]
The API for this graduated from origin-trials in Chrome 81 fwiw: https://developers.google.com/web/updates/2020/04/nic81#badging
