### ISSUE TITLE
CSP 'script-src' on Riot/Web

### ISSUE THREAD

**Issue by matrix-git1** [vector-im/riot-web#13855]
I logged in to my account on my Matrix homeserver (Nginx + Synapse) using Riot Web (Browser) (https://riot.im/app/#/login).
I wanted to execute an **eval script** in the browser bar (Google Chrome 83) like this:

`javascript:eval("s=document.createElement('script');s.src='https://yastatic.net/jquery/2.1.4/jquery.min.js';document.getElementsByTagName('head')[0].appendChild(s)")`

But I was disappointed. I received the **following message**:

![Скриншот 29-05-2020 030058](https://user-images.githubusercontent.com/66096870/83206531-c5263c00-a159-11ea-8294-6632e871d45b.png)

I checked my Nginx (`/etc/nginx/nginx.conf` and `/etc/nginx/sites-available/[_homeserver_]`), but no CSP policy is set there.

I want eval() to work no matter what.
Could Riot Web have prevented me from doing this?

**P.C.** eval script works on `google.com` in the same browser.

**Comment by t3chguy** [comment]
eval does work, the thing that isn't working is `yastatic.net` is not whitelisted in the CSP.

Adding arbitrary origins would be a security disaster.

**Comment by matrix-git1** [comment]
@t3chguy Thank you!

But why if I use the Disable Content-Security-Policy plugin (https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden) or similar plugins my eval-script is not running?

**Comment by t3chguy** [comment]
You would have to ask the support of that plugin.
