### ISSUE TITLE
Add option to use hCaptcha to config.json/homeserver

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/riot-web#13876]
**Is your suggestion related to a problem? Please describe.**
Riot and Synapse are only compatible with reCaptcha by default. You can alter the Synapse config to use the hCaptcha API (https://hcaptcha.com/siteverify) which is extremely similar to reCaptcha, but you cannot easily alter all your clients to point to it.

**Describe the solution you'd like**
It would be nice if hCaptcha was optional, and you could run it alongside or in place of reCaptcha. Clients would ideally inherit these values from config.json or the homeserver, or both. It could be an easy way to finally have an alternative captcha system people can use.

**Describe alternatives you've considered**
I can edit it into the web client on my site with a bit of effort, but every other client will break like so:

![Error](https://user-images.githubusercontent.com/29645145/83390706-f4240280-a424-11ea-9a56-640f8e43eb87.png)

**Additional context**
https://docs.hcaptcha.com/

**Comment by PC-Admin** [comment]
Here are the files on Riot-Web you would need to alter:

```
$ grep -rl "recaptcha"
riot-v1.6.2/index.html
riot-v1.6.2/bundles/ad206c913dd23f98f2b9/vendors~init.js
riot-v1.6.2/bundles/ad206c913dd23f98f2b9/vendors~init.js.map
```

**Comment by t3chguy** [comment]
The Matrix server would have to ask for that captcha and also verify against it. It isn't a client issue.

**Comment by PC-Admin** [comment]
Yes it is, i tried that substituting 'recaptcha_siteverify_api:' with the equivalent hcaptcha url, and riot-web still brings up reCaptcha instead.

So this client isn't trying to ask the server what captcha to use, it just assumes it will use reCaptcha or nothing.

**Comment by t3chguy** [comment]
Because the server is saying `m.login.recaptcha`: https://matrix.org/docs/spec/client_server/r0.6.1#google-recaptcha

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/3606
