### ISSUE TITLE
Unicode 13.0 emoji support

### ISSUE THREAD

**Issue by dngray** [vector-im/riot-web#13871]
Support for Unicode 13.0 emoji which was announced some time ago.

- http://blog.unicode.org/2020/01/unicode-emoji-130-now-final-for-2020.html
- https://unicode.org/emoji/charts-13.0/emoji-released.html

Looking forward to seeing the [most important one](https://www.unicode.org/L2/L2019/19296-polar-bear.pdf) 😉

**Comment by t3chguy** [comment]
Riot sends unicode messages with no restriction on versions. If you are referring to the emoji picker/autocomplete definitions then yes, we need to update our data source for those: https://github.com/vector-im/riot-web/issues/13365

**Comment by t3chguy** [comment]
The polar bear specifically just requires a font update
