### ISSUE TITLE
riot don't user jitsi preferredDoamin

### ISSUE THREAD

**Issue by piotr-sikora-v** [vector-im/riot-web#13875]
Hi,

I have running public jitsi and matrix with riot.
In config.json I set jitis preferreDomain (and  https://czat.lhub.pl/.well-known/matrix/client) to my server but when I add widget it always have url from https://jitsi.riot.im/
also in chrome debug log I see correct address "Jitsi conference domain: lho.lhub.pl"

my riot/matrix server: https://czat.lhub.pl/  my jitsi server: https://lho.lhub.pl/

**Comment by rettichschnidi** [comment]
(Hint: you spelled preferredDomain wrong in the title. Will be hard for other people to find this bug)

**Comment by turt2live** [comment]
Adding widgets through the integration manager are not affected by this setting. The call buttons on the lower right should use it though.
