### ISSUE TITLE
Presence indicator (green dot) remains after synapse config modification until user logs out

### ISSUE THREAD

**Issue by bpcurse** [vector-im/riot-web#13880]
### Description

Minor UX issue with persistent presence states until user logs out.

### Steps to reproduce

- Have a riot-desktop client (v1.6.2 Manjaro Linux) logged in to a synapse server
- Disable presence tracking on the server (synapse 1.11.0) and restart the process
-> Presence is still showing the last states

- Restart the client
-> It keeps showing the last presence state until you log out and log in again.

**Comment by t3chguy** [comment]
This sounds like a Synapse issue of never updating that presence to say offline?

**Comment by t3chguy** [comment]
Yes, riot has no way of knowing the server disabled presence
