### ISSUE TITLE
We don't show toasts for hs_disabled server notices

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13908]

**Comment by t3chguy** [comment]
How were they previously shown?

**Comment by turt2live** [comment]
As a banner.

**Comment by t3chguy** [comment]
Shows up a toast fine for me, just not when https://github.com/vector-im/riot-web/issues/11025 hits

**Comment by turt2live** [comment]
Yea, this is a duplicate of https://github.com/vector-im/riot-web/issues/13907
