### ISSUE TITLE
MAU limit toast disappears on its own

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13907]
It should probably stick around until the user deals with it

**Comment by t3chguy** [comment]
it disappears when the issue goes away, this was something Nad wanted when I raised it to him in a call

**Comment by turt2live** [comment]
The issue hasn't gone away and yet the toast went away. While the event is pinned in the server notice room, it is an issue.

**Comment by t3chguy** [comment]
> While the event is pinned in the server notice room, it is an issue.

ah, if a successful sync comes in that may clear it
