### ISSUE TITLE
Nightly always says no update available when there is

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13928]
Checking for an update manually always says there's no update, despite the update toast being shown simultaneously

**Comment by t3chguy** [comment]
Just tested all the various flows around deferring and it all seemed to work fine :(

The check for updates button ignores `Later` and actually dismisses your deferral.

**Comment by t3chguy** [comment]
So this seems to be due to electron `checkForUpdates` only working once, so will need to write some more code to keep the latest result from it around in the main process
