### ISSUE TITLE
Compact layout is less compact on 1.6.3 than on 1.6.2

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#13934]
### Description

Since the update from 1.6.2 to 1.6.3, the compact layout is less compact. I sadly don't have screenshots of 1.6.2 to make a side-by-side comparison, but it's most definitely noticeable on multiple devices.

![Screenshot_20200605_085237](https://user-images.githubusercontent.com/1565836/83845871-f4185100-a709-11ea-856e-295472c92061.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox v76 and v77
- **OS**: Alpine Linux
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/83858884-0e0b6100-a715-11ea-9389-3750f7027675.png)

**Comment by PureTryOut** [comment]
That was quick, thanks!

**Comment by PureTryOut** [comment]
Just updated to 1.6.8 and the issue is back.

**Comment by t3chguy** [comment]
The setting level changed, you will need to re-enable compact mode.

**Comment by PureTryOut** [comment]
You are right, thanks! I didn't expect things like this to happen in a point-release.
