### ISSUE TITLE
Do not recreate desktop icon after update

### ISSUE THREAD

**Issue by phoerious** [vector-im/riot-web#13932]
### Description

Please stop putting your icon on my desktop. I don't want it there and I have to delete it again after every update of Riot. Its pretty annoying. 

### Steps to reproduce

Delete Desktop icon, then do Riot update. Icon is back. 

Logs being sent: no

### Version information

- **Platform**: desktop?

For the desktop app:

- **OS**: Windows
- **Version**: 1.6. 3

**Comment by t3chguy** [comment]
I am not sure we can provide the custom Squirrel.Windows hooks via electron-builder: https://github.com/Squirrel/Squirrel.Windows/issues/762

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/9210
