### ISSUE TITLE
Compact timeline doesn't change straight away, setting can get stuck

### ISSUE THREAD

**Issue by Standard8** [vector-im/riot-web#13951]
### Description

I was taking a look at using the compact timeline layout on the desktop client. When I initially toggled it, it did not have any effect. When I subsequently cleared cache and reloaded, it applied, however now I can't turn it off.

In the #synchronicity:mozilla.org channel, multiple people have been complaining that toggling it has no effect.

### Steps to reproduce

- Go into settings, toggle the "compact timeline" setting under "Appearance"
- Look back at the display, try changing rooms, try restarting the client

=> Doesn't take effect, on restart the setting is lost.

- Set the setting again, then try clear cache and reload.

=> Yay, setting applied.

- Now try turning off, then clearing cache and reload, or restarting client or anything.

=> Setting never gets turned off.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop
- **OS**: macOS 10.14.6
- **Version**: 1.6.4

**Comment by Standard8** [comment]
I just sent logs for toggling the setting, clearing cache and the setting failing to be applied.

**Comment by jryans** [comment]
Hmm, thanks for the feedback. Definitely not meant to be like that... The expected behaviour is that the setting applies quite quickly after you change it. I can usually see it apply in the room behind the Settings screen just after toggling the UI control.

When trying on my matrix.org vs. mozilla.org accounts, I can reproduce the behaviour you're seeing only on mozilla.org... It seems to be something like the server failing to echo back the changed value of the setting. I'll raise this issue for further investigation.

**Comment by jryans** [comment]
A few more details to aid Modular team's investigation: for some reason, when sending account data settings changes (`PUT https://mozilla.modular.im/_matrix/client/r0/user/<MXID>/account_data/im.vector.web.settings`) to (at least some) mozilla.org accounts, the changed settings never seem to come back down through sync.

**Comment by jryans** [comment]
We believe this is a symptom of https://github.com/matrix-org/synapse/issues/7617, which has been fixed as part of Synapse 1.15.0.

**Comment by jryans** [comment]
@Standard8 The fixed server version has now been deployed for mozilla.org, and I confirmed this fixes the issue on my account. Please try toggling the setting again and let us know how it goes.

I'll close for now given I've verified, but please reopen if it's not fixed for you.

**Comment by Standard8** [comment]
@jryans that seems to have fixed it. Thanks!
