### ISSUE TITLE
Redesign room list tile notification dropdown

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#13961]
https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=381%3A4544

**Comment by turt2live** [comment]
ftr the room list tile is undergoing heavy changes in the new room list. Would recommend waiting for its context menu to land before the notifications bell does.

**Comment by fedon** [comment]
Will it be sliding panel? Left panel takes too much space on mobile. Please do it sliding. Or at least remove that fat "+" from left panel.

**Comment by turt2live** [comment]
Unblocked for now: Wedge it in next to the context menu, include all 4 current states (against proposed notification changes).

**Comment by nadonomy** [comment]
Straw man proposal for improving todays interactions here:

https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=1814%3A181

Designs will be dressed up properly soon.
