### ISSUE TITLE
Unread counts are wrong for rooms when new messages arrive

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#13974]
### Description

The unread count in a room seems to be stuck, and will show a larger number than expected. Typically, it will show the number of messages sent this session, rather than the number of messages that are unread. For instance, if someone DMs me with 5 messages, and I read them, and then I get a sixth message, the badge will show 6.

### Steps to reproduce

- Have a message sent to one of your rooms
- The room name should be bolded with an unread count of one/
- Open the room, scroll to the end. Read the room. Even respond if you like.
- Someone responds in the room, **except the unread count is now 2.**

I'd expect the unread count to be 1.

Describe how what happens differs from what you expected.

[Video](https://chaotic.half-shot.uk/_matrix/media/r0/download/half-shot.uk/6bfcafdd447137d08fc5db1fa93e020f2d52abee)

### Version information

For the desktop app:

- **OS**:  Ubuntu 20.04
- **Version**: 1.6.4

**Comment by turt2live** [comment]
issue looks to be on the server - rageshake submitted has a bunch of server-side errors.
