### ISSUE TITLE
`@room` does not respect `Show avatars in user and room mentions` setting …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13991]
In the chat/room timeline, posting a message with `@room` does not respect the `Show avatars in user and room mentions` setting … the room avatar is always displayed.

Riot-Web `1.6.4` on latest stable Firefox, Chromium, Chrome

**Comment by t3chguy** [comment]
That sounds like by design, `@room` isn't a room mention

![image](https://user-images.githubusercontent.com/2403652/84380493-53c99d00-abdf-11ea-9dba-20992d800f07.png)

The above shows a user mention followed by a room mention. `@room` is a different type altogether.

**Comment by fooness** [comment]
Interesting, thank you for clarifying.

IMHO that should be in the very same category, though. 🤔
