### ISSUE TITLE
Half setup 4S/Cross signing ? 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-web#13993]
https://github.com/matrix-org/riot-web-rageshakes/issues/2991

According to settings cross signing and keybackup are not setup 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/9841565/84383662-fdfbf180-abec-11ea-9f7b-aa1f9200b5eb.png">

But when tapping on setup keybackup, a recovery key is asked

<img width="466" alt="image" src="https://user-images.githubusercontent.com/9841565/84383692-0eac6780-abed-11ea-9754-980600acd419.png">

**Comment by jryans** [comment]
I think we should try to address this by exposing the reset button if any part of cross-signing or 4S seems to exist.

**Comment by jryans** [comment]
@BillCarsonFr Develop now has a fix to show the reset button in Settings for this case, perhaps you can message them to suggest trying it. Or if they don't want to use develop, it will be part of the next release.
