### ISSUE TITLE
WebP images don't render (enlarged previews work)

### ISSUE THREAD

**Issue by jakem72360** [vector-im/riot-web#14014]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.
WebP images sent in Riot, aren't visible unless clicked on, where they become visible once the full version is previewed.

### Steps to reproduce

- Send a WebP image. You won't see it until you click on it.
![f155fa21](https://user-images.githubusercontent.com/7912205/84574011-467eff00-ade7-11ea-8d3d-af3eda2016c5.png)

### Version information

- **OS**: Arch Linux
- **Version**: 1.6.4-1

**Comment by t3chguy** [comment]
Sounds like a Synapse bug with thumbnailing WebP

**Comment by t3chguy** [comment]
Looks like it'll be fixed in latest Synapse by https://github.com/matrix-org/synapse/issues/4382
