### ISSUE TITLE
make date time-stamp stick on top

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14023]
With `Always show message timestamps` set to `on` only time is shown, without date it was. It's really annoying thing:
![image](https://user-images.githubusercontent.com/14617699/84582697-1ab84500-adf8-11ea-9acd-997e77af5a40.png)

The solution is easy: to make date timestamp stick on the top.
![image](https://user-images.githubusercontent.com/14617699/84582724-65d25800-adf8-11ea-8909-d861d30bc8b4.png)

**Comment by t3chguy** [comment]
That leads to confusion as it makes it look like that is the first message of that date

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/7575
