### ISSUE TITLE
New room list: Make resizing be less awful (don't desync so often)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14022]
Could track the Y position and figure out size from that instead of decrementing available space, which implies using our own resizing lib instead of whatever awful thing is currently in use.

**Note**: This could affect UI refresh work, sync with them to ensure it's sensible to start reworking the component to avoid conflicts.

**Comment by nadonomy** [comment]
Outstanding things to solve:

- [ ] Final designs for resize handle
- [ ] Final designs for show more/show less interaction
- [ ] Final designs for background fills/how we clip/occlude content

**Comment by turt2live** [comment]
Further iterations are being done outside of this issue's scope.
