### ISSUE TITLE
Privacy: update my read marker or don't, choice per room

### ISSUE THREAD

**Issue by mcg-matrix** [vector-im/riot-web#14030]
**Is your suggestion related to a problem? Please describe.**
For some rooms, I want the other room members to know which messages I have seen; for other rooms, I do not want the members to know when I have (or not yet have) seen a message. It looks like I currently don't have that choice.

**Describe the solution you'd like**
I would like to be able to choose per room whether the other room members can see up to which message I have read the conversation.
A bonus feature would be a choice of default behaviour for newly joined rooms.

**Comment by t3chguy** [comment]
The read marker is the green horizontal line which is private to you. Perhaps you mean the read receipt?

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/2527

**Comment by mcg-matrix** [comment]
> The read marker is the green horizontal line which is private to you. Perhaps you mean the read receipt?

Oops, yes, thanks for the reply! I'll edit this issue's title.

**Comment by t3chguy** [comment]
#2527 already has

> For bonus points, configurable per room. cf: #2526

**Comment by mcg-matrix** [comment]
> Closing in favour of #2527

My bad, I had searched for "read marker" and not "read receipts". Sorry for the noise.

**Comment by mcg-matrix** [comment]
> #2527 already has
> 
> > For bonus points, configurable per room. cf: #2526

For future readers of this issue: Don't get confused, #2526 did not deal with the sending of read receipts (nor with a per-room setting), see https://github.com/vector-im/riot-web/issues/2527#issuecomment-643762462.

**Comment by mcg-matrix** [comment]
This issue is about a choice per room (for sending read receipts or not).

> Closing in favour of #2527

#2527 just got "closed as completed in matrix-org/matrix-react-sdk#8629", but as far as I understand there won't be a choice per room.

**Comment by SimonBrandner** [comment]
> This issue is about a choice per room (for sending read receipts or not).
> 
> > Closing in favour of #2527
> 
> #2527 just got "closed as completed in [matrix-org/matrix-react-sdk#8629](https://github.com/matrix-org/matrix-react-sdk/pull/8629)", but as far as I understand there won't be a choice per room.

I've opened https://github.com/vector-im/element-web/issues/23021 :)
