### ISSUE TITLE
Horizontal scroll bar no longer shows in block text

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14044]
See https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$7gKTzKcb4GLWLPaQAyv6o3X5d4kcJeh_2OelzhWu6xU?via=matrix.org&via=privacytools.io&via=mozilla.org and the next message.
Text blocks between triple backticks have no horizontal scroll bar if the contents is wider than the timeline pane.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/9052
