### ISSUE TITLE
Some stickers are not displayed

### ISSUE THREAD

**Issue by gnomelibre** [vector-im/riot-web#14048]
### Description

In the stickers pack « loading artist », when I choose the sticker « Money », it displays this icon instead of the sticker

[https://riot.im/app/img/icons-show-stickers.4e420bf.svg](url)

I've tried to use it several times without success in the last few weeks.

Before making this bug report, I tested the other stickers (of the same pack) in the Public Test Room (!PQgcrPZqvvbaAGKezi:matrix.org) and many of them are not displayed: Blush, Distraught, Get outta here, Lewd, Smug, Spider, Wtf...

Several months ago, everything was okay. But if I go back in the history of my room, at the time when it was ok, the images were replaced by the icon indicated previously.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox 77.0.1
- **OS**: Fedora 32
- **URL**: riot.im/app/

**Comment by t3chguy** [comment]
This is an issue in that matrix.org deleted the underlying resources.

**Comment by t3chguy** [comment]
The team said stickers should now be unbroken, they are working on a way to prevent this happening again.
