### ISSUE TITLE
Store theme in localstorage for fastest possible rendering of dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14045]
It can take a little while for the dark theme to actually come into effect, so we should just cache the last theme the user used in localstorage to make the transition as soon as possible. Facebook appears to do this for instance.

**Comment by t3chguy** [comment]
Now that the theme is device-specific on purpose we can rely on that setting instead.

**Comment by turt2live** [comment]
yea, I'm going to close this because of that change.
