### ISSUE TITLE
New room list: Breadcrumbs re-implementation

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14040]
see comment: https://github.com/vector-im/riot-web/issues/14040#issuecomment-647694845

**Comment by niquewoodhouse** [comment]
### List of requirements (WIP)
Please add any if you think any are missing, but I think this is what we need @turt2live 

**Breadcrumbs as a whole**
- [ ] Allow Scroll, as prev room list, with scrollbar only appearing on hover
- [ ] Include a header "Recent" that users would be able to close, same as all other headers.


**Each breadcrumb**
- [ ] Presence (if available)
- [ ] Notifications (if available)
- [ ] Public room (if available)

<img width="536" alt="Screenshot 2020-06-22 at 19 18 25" src="https://user-images.githubusercontent.com/1587166/85321888-553b7500-b4bd-11ea-9335-fe237db12e17.png">

**Comment by turt2live** [comment]
> This might not be agreed by everyone, so potentially worth leaving and raising as another iteration later.

Will ignore the header - I've tracked it as https://github.com/vector-im/riot-web/issues/14145 under "nice to haves" for now.
