### ISSUE TITLE
#general:privacytools.io is not accessible at this time.

### ISSUE THREAD

**Issue by romulasry** [vector-im/riot-web#14059]
### Description

Try again later, or ask a room admin to check if you have access.

M_UNKNOWN was returned while trying to access the room. If you think you're seeing this message in error, please submit a bug report.

### Steps to reproduce

Try to go to the room #general:privacytools.io
it fails with the above error

The room should work

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? Browser.

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? FIrefox 77.0.1
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? openSUSE tumbleweed
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? https://riot.privacytools.io/#/room/#general:privacytools.io

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by t3chguy** [comment]
That sounds like a server issue, contact your server operator.
