### ISSUE TITLE
Don't leave upgraded rooms when leaving old versions of themselves

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#14058]
Because of room upgrades, I've got a lot of duplicates in my rooms list (which Riot hides but not all clients) and would like to leave them to reduce the size of my initial sync responses. However, if I show an old version of a room and leave it from the room settings, Riot also leaves the upgraded version, which means that for every room I want to clear up duplicates of I need to leave then rejoin it.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/13429 which is https://github.com/vector-im/riot-web/issues/10380
