### ISSUE TITLE
Allow automatic invite

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14062]
In some situations may want someone else present in all rooms where one is invited.  Some use cases:
- Parental control.
- Account switch, where instead of abandoning the old account one wants to have the new account invited in all rooms that invite the old account.
- Auto-invite of one or more bots - say a translate bot, or some bookkeeping bot that serves as a witness.
- Counsellor support - to prevent a vulnerable client from having DMs with their oppressors, e.g. when the oopressor verifies himself to the client.
- Back-up account - in countries such as China, servers get blocked routinely, so having a back-up account in all rooms is no luxury.
So it would be great if there would be a setting 'Autoinvites' where one could give a list of accounts that would be invited automatically in every room for which the current account gets an invite.

**Comment by t3chguy** [comment]
If anything this should probably be a spec/server thing so you don't need to implement it in every client, no?

**Comment by turt2live** [comment]
Yea, this is a spec/server request, not one that riot can action itself.

**Comment by Biep** [comment]
Why not?  If *I* can send an invite through Riot, Riot can do it for me too, can't it?
Anyway - how do I move this to where it belongs?
