### ISSUE TITLE
Desktop now prompts to enable desktop notifications

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#14066]
<img width="272" alt="Screenshot 2020-06-17 at 15 42 22" src="https://user-images.githubusercontent.com/986903/84912255-27b38d80-b0b1-11ea-9e29-1ff27e43ccc8.png">

This toast appeared when I updated nightly this morning, so we're:
 1. Prompting new users on desktop to enable desktop notifications, which I didn't think we intended to or ever did (ie. we intended to just start sending notifs) although @t3chguy thinks we did prompt at some point.
 2. Showing this toast for current users of desktop as soon as they update, even though they've been getting notifications fine up until now.

**Comment by t3chguy** [comment]
They were previously getting desktop notifs due to a bug, but yes.
