### ISSUE TITLE
riot transmits video and audio in one direction from a text chat

### ISSUE THREAD

**Issue by aktivkohle** [vector-im/riot-web#14063]
### Description

I was speaking to someone running riot on Mac. Part way through the conversation we paused while they accepted an upgrade that riot was offering

I had a few issues with the network connection yesterday. I rebooted the PC and attempted a video call which appeared to not connect then hung up. Next I started typing in the chat. The riot user interface displayed neither audio or nor video call, just a text chat. I could not hear or see the other party, but they could hear and see me!!! They typed into the chat what I was saying.

An update was pushed yesterday (riot-web: 1.6.5) and it might have something to do with this bug.

It is unnerving as it means that riot at the moment may transmit audio and video to the other side without giving any signs that it is doing so. This is not as bad as leaking it out to third party but is none the less a serious malfunction.

Am not sure if this is a bug which has been dormant a long time which has suddenly been activated by some network problems at my end but it is more likely that the recent release did it.

Another possibility is that, just before it occurred I had switched from an ethernet to a wifi connection, maybe that confused riot an triggered this behaviour.

Would not know if this can be reproduced, is the first time it has occurred and have been using riot for a while now.

If you need my logs - please tell me how to view the log files, I want to view them before supplying them. 

### Version Information

my system: riot-web: 1.6.4 and olm: 3.1.3 on Debian 10
other party: riot-web: 1.6.5 . He is on olm: 3.1.3 on mac for the other user

**Comment by Twi1ightSparkle** [comment]
Might be related to https://github.com/vector-im/riot-web/issues/12569 ?

https://newvector.zammad.com/#ticket/zoom/4397 for additional context

**Comment by t3chguy** [comment]
Indeed, that is the issue I was looking for yesterday to close as dup of
