### ISSUE TITLE
New room list: Drop account-level ordering options

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14069]
We don't need them anymore.

**Comment by inputvalidation** [comment]
Also applies to Direct Messages and the order also appears to change when you click a certain room, even if you've only selected "Order by name".

**Comment by turt2live** [comment]
@inputvalidation that's an entirely different bug unrelated to anything tagged `New room list`.

**Comment by turt2live** [comment]
actually we're going to drop them

**Comment by auscompgeek** [comment]
Will existing account settings for the old room list get migrated for new new room list users?

**Comment by turt2live** [comment]
@auscompgeek nope, we already decided that the user having to change their options for their sublists is acceptable for now. If this changes, we'll open a new issue for it.
