### ISSUE TITLE
[Firefox] Unable to close Matrix App screen

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#14078]
Firefox 77.0

In a room, open the integration manager

Try to close it using the close button (top end in the screenshot below): it has no effect, the page has to be refresh (F5) to close the dialog

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/3940906/84990669-c8538d00-b145-11ea-91da-369e0db9d5b5.png">

It works fine with Chrome

**Comment by auscompgeek** [comment]
I think this is just a long-standing bug of the multiple integrations manager lab.

**Comment by jryans** [comment]
Yes, agreed, the bug only occurs when using the multiple integration managers lab.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/10678

**Comment by bmarty** [comment]
Ok, thanks I confirm that without multiple IMs it works well.
