### ISSUE TITLE
New room list: Sticky headers unreliable (sticking behind other headers)

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#14070]
- I have a persistent 'rooms' header behind my favourites
- It sometimes draws above everything else when I scroll down
- I think sticky headers at the bottom worked once, but now I can't get them to work at all :(

**Comment by turt2live** [comment]
> I have a persistent 'rooms' header behind my favourites

This happens when you scroll down so it sticks to the bottom, then top, then bottom again. It's just a silly bug.

> I think sticky headers at the bottom worked once, but now I can't get them to work at all :(

This feels like an artifact of the above.

> It sometimes draws above everything else when I scroll down

Not sure what this means: have opened https://github.com/vector-im/riot-web/issues/14077 to track is separately.

**Comment by nadonomy** [comment]
@turt2live not sure tracking separately makes sense— the draw order when scrolling specifically pertains to the buggy sticky header

**Comment by turt2live** [comment]
I'm still not sure what that means, or what is expected :(

When it's working correctly the header taking the spot of the old header will go on top. 

Wanted to track it separately for a) figuring this out and b) it's easier for dev.
