### ISSUE TITLE
Riot don't close correctly the session in Google Tokens. 

### ISSUE THREAD

**Issue by Belladona-c0re** [vector-im/riot-web#14073]
Riot don't close correctly the session in Google Tokens. 
When you authenticate with SSO/Google OpenID and later use the Close Session, if you open a new open session again (same user)  you don't pass from Google site. and you get a message 

```
The application at https://riot.im/app/#/ is requesting full access to your my.server Matrix account.

If you don't recognise this address, you should ignore this and close this tab.

I trust this address

```
without new Google verification process. I think that the token is not correctly expired/closed and is re-used. 

if you close a session you should kill the used token

Tested in riot.im

**Comment by t3chguy** [comment]
Riot doesn't have a concept of Google Tokens, only Matrix m.login.token which it gets from the Homeserver so if anything the act of closing the token would be as part of the homeserver's redirect, not here. This should either be a spec (matrix-doc) or server (Synapse) issue.
