### ISSUE TITLE
New room list: Usability issues with unread rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14084]
* The difference between read and unread (bold/non-bold) is less pronounced, and hard to se at all with preview enabled
* The small unread (no number) counter on the rooms with unread messages is a lot less obvious than the previous bold behaviour.

**Comment by turt2live** [comment]
Design that came through on a call was:
* In future, the user gets to pick between dots and counts
* Show dots whenever we would bold, with possible counts if enabled and possible
* Increase bold to 700 from 600.

**Comment by t3chguy** [comment]
> possible counts if enabled 

When wouldn't it be possible?

**Comment by turt2live** [comment]
with the current notification structure, bold rooms (mentions only). These are apparently disappearing in the notifications work though, so we'll always have access to a count.

That awkward condition is mostly a stopgap and not actually final functionality.

**Comment by turt2live** [comment]
ugh, my notes differ from the call minutes:

> On badges/counts, intention is to:
> * Always show a dot whenever there’s an unread/the room is bold
> * Show counts on mentions
> * Let users opt in to showing counts on all rooms in Account Settings
> * Nad validating the above with Notifications work, will shout on conclusions

I'll make it behave as per the minutes.
