### ISSUE TITLE
New room list: Divider is a window to the universe below it

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#14094]
<img width="382" alt="Screenshot 2020-06-18 at 16 46 08" src="https://user-images.githubusercontent.com/4626865/85042643-5863f780-b183-11ea-99f7-bc30a742d52c.png">

macOS/Chrome.

**Comment by turt2live** [comment]
This seems to be happening to a lot of people :(

**Comment by turt2live** [comment]
ftr it's an indicator that the resizer is desyncing from the view, meaning when you refresh it might show you more than you intended.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/14051
