### ISSUE TITLE
New room list: make unread rooms stand out more

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#14097]
I'm having a hard time telling which rooms are read or not.  In the old room list, unread rooms were slightly bolder, and a different colour (whiter in the dark theme).  In the new room list, unread rooms are now the same colour, and I find the "slightly bolder" doesn't stand out as well.
![image](https://user-images.githubusercontent.com/1012976/85056775-d0272780-b16d-11ea-9fe4-1867c26a5ccd.png)
(FluffyChat has unread messages, F-Droid does not)
Changing the font-weight of unread rooms to 700 instead of 600 makes it easier to tell which rooms are unread:
![image](https://user-images.githubusercontent.com/1012976/85056825-e1703400-b16d-11ea-898e-db3316deb6be.png)

**Comment by uhoreg** [comment]
This seems to be done in the latest /develop, both by making the font bolder and adding a grey dot

**Comment by turt2live** [comment]
oops, yes it was. Was being tracked as https://github.com/vector-im/riot-web/issues/14084 for the more general complaints (sorry, completely forgot about this issue)
