### ISSUE TITLE
New room list: custom tags support

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14091]

**Comment by MTRNord** [comment]
This causes me to have to use a version that is older than a version where this is the default :( As otherwise my list is empty

**Comment by daduke** [comment]
same here. back to old version until I can has tags :gift:

**Comment by eternaleye** [comment]
I use room tags heavily to support my workflow; I use Element for three primary purposes:

- My work uses Matrix as its textual chat solution
- I use Matrix as my IRC bouncer for hobbyist programming
- I use Matrix to communicate with my roommate in real-time, to coordinate shopping etc.

By using room tags, I'm able to effectively separate these, so I can see if I have any work-related notifications by glancing at the communities panel, or hide work while I'm off-hours, or hide hobbyist chat while I'm working. Without tags, none of these things are viable, and I'm significantly less able to use Element in an effective manner :frowning_face:
