### ISSUE TITLE
Failed to Join room: You are not invited to this room

### ISSUE THREAD

**Issue by IgnisFlamme** [vector-im/riot-web#14109]
### Description
I am on the mozilla.modular.im homeserver and cannot join any rooms from the matrix.org server due to a error that gives me:

Failed to join room
You are not invited to this room.

I cannot join ANY of the rooms, all rooms return the same error.

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Manjaro
- **Version**: 1.6.4

**Comment by t3chguy** [comment]
Contact the support for your instance.
This isn't a Riot issue.
Incidentally, I successfully managed to join #riot-web:matrix.org from my Mozilla test account so cannot reproduce your issue.

Try the support room: https://chat.mozilla.org/#/room/#synchronicity:mozilla.org
