### ISSUE TITLE
Some emoji sent from riot-web don't transmit correct emoji to mobile platforms.

### ISSUE THREAD

**Issue by flackr** [vector-im/riot-web#14116]
### Description

When sending certain emoji from riot-web, they are received on RiotX and Riot mobile clients as a small black version of the emoji, even though they look identical to the full color versions of the emoji transfered from iOS / Android.

### Steps to reproduce

- Send a :sun: or :heart: emoji in a message or reaction.

Expect it to show up as the normal sun or heart emoji on mobile platforms. Instead, it shows a tiny black and white version of the emoji. While this may be a Android/iOS bug I suspect that the message riot-web is sending may be malformed in some way.

There's likely other emoji that do this, but these are the two that I've noticed.

Logs being sent: no

Image of sun and heart sent first on riot-web and then on Android RiotX:

What it looks like on riot-web:
![riot-web](https://user-images.githubusercontent.com/366761/85174947-6d548f80-b244-11ea-88dc-53de234cc15b.png)
What it looks like on RiotX:
![riotx](https://user-images.githubusercontent.com/366761/85175001-8d844e80-b244-11ea-958e-0149893dd31c.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 83.0.4103.97 (Official Build) (64-bit)
- **OS**: ChromeOS
- **URL**: private server running riot-v1.6.5 from https://github.com/vector-im/riot-web/releases

**Comment by jryans** [comment]
I believe this is the same as https://github.com/vector-im/riot-web/issues/13926, and if so there's a fix on develop that will be included in the next release. @flackr, any chance you can re-test with https://riot.im/develop to see if it's doing what you expect>

**Comment by flackr** [comment]
Yup, it all looks good in the develop branch! Thanks!

**Comment by jryans** [comment]
Great, thanks for testing! I'll close this then, since it's already fixed on develop.

**Comment by jryans** [comment]
Riot 1.6.6 will contain the same fix, and should be released today / tomorrow.
