### ISSUE TITLE
Ability to remove avatars from quoted messages.

### ISSUE THREAD

**Issue by penloy** [vector-im/riot-web#14122]
**Is your suggestion related to a problem? Please describe.**
I'm always frustrated when quotes in the Riot.im client take up so much screen real estate. Trying to read chat when it's filled with excessive quoting is annoying.

**Describe the solution you'd like**
I'd like the ability to remove user avatars from quoted messages in order to make quotes much more compact. Any other way of reducing screen space bloat would be appreciated.

**Describe alternatives you've considered**
I've tried rummaging through the Riot.im settings to find some setting that'd make things more compact. I've enabled compact mode but I'd still like to make the quotes smaller and more compact by removing the user avatar.

**Additional context**
N/A

**Comment by t3chguy** [comment]
Quotes do not have replies, do you mean Replies?

![image](https://user-images.githubusercontent.com/2403652/85199301-5fefe180-b2e6-11ea-98e6-a332601bcbac.png)

You should add it to the existing meta-issue.

**Comment by penloy** [comment]
> Quotes do not have avatars, do you mean Replies?
> 
> ![image](https://user-images.githubusercontent.com/2403652/85199301-5fefe180-b2e6-11ea-98e6-a332601bcbac.png)
> 
> You should add it to the existing meta-issue #6445

Yes, sorry I meant replies. I will add it to that existing issue. Thank you.
