### ISSUE TITLE
Riot Web unusable on Firefox 

### ISSUE THREAD

**Issue by GirardR1006** [vector-im/riot-web#14128]
### Description

Hello, since last week the Riot web client is unusable on my Firefox (see a screenshot attached below). The bug was reproduced on my two computers (both with the same version of Firefox).

Here is a sample screenshot:
![2020-06-21_14-56](https://user-images.githubusercontent.com/19275558/85225331-b8031280-b3d0-11ea-8d93-6c377e1b3882.png)

### Version information

- **Platform**: Web browser, Firefox 77.01; I have uBlock Origin and Cookiele Autodelete as well as other plugins, but I don't recall having such kind of trouble before

For the web app:

- **Browser**: Firefox 77.01, uBlock Origin and cookie-auto-delete installed on both, though they were not causing any issue before that
- **OS**: Solus OS, linux kernel 5.6 and Archlinux, linux kernel 5.7
- **URL**: riot.im/develop and riot.im/app both exhibit this behavior

**Comment by t3chguy** [comment]
Someone reported a dark theme/mode extension causing this issue where that extension prevents the css from loading.

**Comment by GirardR1006** [comment]
Yup:
* Cookie AutoDelete https://github.com/Cookie-AutoDelete/Cookie-AutoDelete
* Dark Mode https://mybrowseraddon.com/dark-mode.html
* Invidition https://gitlab.com/Booteille/invidition
* KeePassXC-Browser
* NoScript https://noscript.net/
* Plasma Integration
* uBlock Origin
* Zotero Connector
* Twitter to nitter redirect https://gitlab.com/nitrohorse/twitter-to-nitter-redirect

**Comment by GirardR1006** [comment]
And indeed, when disabling the "Dark Mode" extension, the UI is going back to normal. 
I am using Dark Mode regularly however, so it's just a temporary fix for me. Maybe we should mark this issue as duplicate from the one you mentioned?

**Comment by t3chguy** [comment]
The issue I mentioned was reported directly to the developers of dark-mode via e-mail by the user experiencing the issue, it is something they have to fix as I understand it.

**Comment by jryans** [comment]
Thanks for reporting this. Since it sounds like this is not an issue in Riot itself and disabling the extension responsible fixes it, I'll close this issue.
