### ISSUE TITLE
+N on read receipt group hidden under read receipts

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14127]

**Comment by jryans** [comment]
Hmm, possibly related to layout changes for IRC mode...?

**Comment by turt2live** [comment]
@jryans if possible, can we consider this a release blocker?

![image](https://user-images.githubusercontent.com/1190097/85300555-ef6ecf00-b463-11ea-91f9-614392273d27.png)

No idea how many people actually read this message.

**Comment by t3chguy** [comment]
It is an issue in current RC.

**Comment by jryans** [comment]
Ah okay, thanks. I'll try to investigate a fix here for the RC then.

**Comment by jryans** [comment]
This was regressed by https://github.com/matrix-org/matrix-react-sdk/pull/4725.
