### ISSUE TITLE
[Needs revist] Having 4 tiles shown on the new room list feels a bit much

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14137]
I'd like to hide just 2 more of my DMs as I don't DM people that often

**Comment by niquewoodhouse** [comment]
@turt2live That's really interesting.  Do you think we should not have an arbitrary minimum and let each person set it themselves, via resize for example?

**Comment by turt2live** [comment]
We could probably show 4 by default and let the user collapse down to 1 if they want (making 'show less' go to 4 as well).

**Comment by niquewoodhouse** [comment]
That sounds like a good way to let people customize the room list to fit their super-specific needs, without adding complication.

My only concern is consistency of the 'show less'. I think 'show less' should go to whatever the default number of items shown is, whether it's 7 or 5 or 4 or whatever.    I currently have no insights into what specific number users would generally prefer.

**Comment by turt2live** [comment]
The proposal is to have it do that (4 is the default), so should be fine. I'll add a thing that lets us tweak the default for dogfooding.

**Comment by turt2live** [comment]
Initial PR for dogfooding at https://github.com/matrix-org/matrix-react-sdk/pull/4825

**Comment by turt2live** [comment]
See https://github.com/vector-im/riot-web/issues/14266 - we'll change as needed.
