### ISSUE TITLE
New room list: after joining via directory, room did not appear in the list

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#14132]
A user reports:

> Joined a room by entering the alias into the room directory dialog. The join gave an infinite spinner despite having successfully joined (and showing up in other clients). Navigating manually to the room worked, but still does not show up in the new room list.

**Comment by auscompgeek** [comment]
Original reporter here. Just to clarify, the joined room not showing up in the new room list is reproducible when joining from a different client as well, but the breadcrumbs work.

I wonder if there's a separate bug with the forever loading screen when joining on develop as well.

**Comment by turt2live** [comment]
Forever loading is a different issue.
