### ISSUE TITLE
[Idea] User permissions on a server

### ISSUE THREAD

**Issue by tutosfaciles48** [vector-im/riot-web#14130]
I wonder how I can manage new users permissions: for example, what can do a new registered user (create a room ? ...)

A solution could be a user gestion panel, or something similar to this, which allow to create or delete user roles, set defult roles for peaple which login (whith ldap module for ex)

I'm not 100% sure that it could be fully implemented only on riot web (or even desktop version) but for organizations, this could seriously compete with teams

**Comment by t3chguy** [comment]
Bundling this in as part of https://github.com/vector-im/riot-web/issues/4125

Matrix and Synapse do not currently expose APIs to manage user permissions like you want, so you might want to open issues there.

**Comment by tutosfaciles48** [comment]
Thanks for the reply.
