### ISSUE TITLE
New room list: headers jump horizonally on hover-over

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-web#14135]
When hoovering over the roomlist the header of the tag that's hovered over shows a down-arrow, causing it to jump to the right a bit. When moving the mouse this can be quite distracting.

**Comment by auscompgeek** [comment]
FWIW I'd be happy if the header simply always leaves space for the twistie caret, like so:

![image](https://user-images.githubusercontent.com/128854/85304319-f4c52b80-b4ee-11ea-945e-2c0733100049.png)

(… now the unaligned + on the sticky header is bugging me too :disappointed_relieved:)

**Comment by turt2live** [comment]
Design is to simply not do this, combined with other things. I'll make sense on the PR in a minute.
