### ISSUE TITLE
New room list: Simple resizing improvements (TBD)

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/riot-web#14141]
### WIP Proposal 

**New resize bar**
This suggestion looks less like a scrollbar and more like a traditional resize bar.

<img width="336" alt="Screenshot 2020-06-22 at 23 22 12" src="https://user-images.githubusercontent.com/1587166/85341158-7319d180-b4df-11ea-8658-85aeb6853d14.png">

We need to look at the "show XX more" to come up with a more rounded proposal because I think the resize and the "show more" are strongly related, especially when next to each other in the UI and impact each other.

**Comment by turt2live** [comment]
The majority of this is implemented, with https://github.com/vector-im/riot-web/issues/14022 tracking further iteration.
