### ISSUE TITLE
Feature request: port riot to KaiOS

### ISSUE THREAD

**Issue by mefuller** [vector-im/riot-web#14146]
**Is your suggestion related to a problem? Please describe.**
Feature phone OS KaiOS does not currently have a matrix chat client available.
Currently WhatsApp is available on the OS, but there is an opportunity to make mobile access to a matrix client widespread as the OS is targeted at low-cost handsets in the developing world

**Describe the solution you'd like**
Request that Riot-Web be ported for KaiOS (feature phone OS, https://developer.kaiostech.com/)

**Comment by t3chguy** [comment]
riot-web does not intend to support Phone OSes other than experimentally in-browser as per https://github.com/vector-im/riot-web#supported-environments

There are probably other Matrix clients which would work on your phone.

**Comment by HenkKalkwater** [comment]
Maybe https://github.com/vector-im/hydrogen-web would work on KaiOS (or could be packaged to work on KaiOS)
