### ISSUE TITLE
New room list notifications: Forced red badge on DMs can result in a 0 count

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14160]
![image](https://user-images.githubusercontent.com/1190097/85432339-113d8400-b540-11ea-952a-1c7c7cb75a6d.png)

If the message was muted (previously bold-only), the badge becomes a zero because of the forced count.

It's unclear how this is meant to be resolved, but apparently the count is changing in the notifications project? Will monitor that project for progress and closer to release re-evaluate what we could do here.

**Comment by t3chguy** [comment]
This will be inherently fixed by the FTUE Notifications project but that is slated to land later so might need some local fix

**Comment by turt2live** [comment]
Solution for now: Red dot if zero
