### ISSUE TITLE
Not getting audio and video call

### ISSUE THREAD

**Issue by SHUFIL** [vector-im/riot-web#14170]
Not getting audio and video call
### Description
I have installed Riot with own local matrix server, and created user with terminal, riot is up and can login with local metrics server 
But not at all getting audio and vdeo call 
Describe here the problem that you are experiencing, or the feature you are requesting.
For audio and vedio cal i need to install and configure any other software , currently running Riot and metrics only
### Steps to reproduce
started services using below commands
docker run -p 80:80 -v config.json:/etc/riot-web/config.json vectorim/riot-web
source ~/synapse/env/bin/activate
synctl start
Created used below commands
register_new_matrix_user -c homeserver.yaml http://localhost:8008
- For bugs, list the steps
installed riot-desktop version , not at all connecting audio and vedio calls , but ring getting 
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.
need vedio and audio calls 

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? Desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?  Chrome
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?  Windows
- **Version**: 1.x.y

**Comment by jryans** [comment]
Have you setup a [TURN server](https://github.com/matrix-org/synapse/blob/develop/docs/turn-howto.md)? This is may be needed for success VoIP calls depending on the network environment.

This sounds like a server admin issue, rather than a Riot bug, so I'd recommend asking about this in rooms like #synapse:matrix.org.
