### ISSUE TITLE
New room list: VoIP + Jitsi

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14177]
Has design:
* [x] Incoming call box (1:1 calls only)
* [x] Jitsi floating conference box (bottom right)

This issue does not scope in decorations for in-progress calls, doesn't change the ringing noise, and doesn't deal with anything that isn't feature parity.

**Comment by niquewoodhouse** [comment]
Attaching incoming call box for reference.

<img width="542" alt="Screenshot 2020-06-25 at 19 10 19" src="https://user-images.githubusercontent.com/1587166/85775462-b5c5ee80-b717-11ea-9a8a-3785676cf246.png">


[Figma link](https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=1755%3A67987)

**Comment by JorikSchellekens** [comment]
We need some design for the active calls as well:
![image](https://user-images.githubusercontent.com/23084468/86264511-86e9c580-bbba-11ea-9831-77ffaf72e7e5.png)
One to one voice call currently active ^

![image](https://user-images.githubusercontent.com/23084468/86264518-89e4b600-bbba-11ea-92b7-1fb0b9aa649f.png)
The black box above is a placeholder for video

We're proposing to have jitsi calls floating to the bottom right of the room view. This raises the question of where the new call box should be: Should it be where the call view will be (bottom right) or should it be closer to the room list which groups it cognitively with the list of people.

**Comment by turt2live** [comment]
We're going for parity. Do 1:1 calls currently show up in the room list?

**Comment by JorikSchellekens** [comment]
Yes they do

**Comment by turt2live** [comment]
godwhy.jpg

I suppose we stick them in the lower right with the jitsi then.
