### ISSUE TITLE
Add a shortcut in the desktop app to open the file I just downloaded

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#14171]
It would be great to have a shortcut in the app to open the file I just downloaded on desktop. Firefox or chrome give us one on web, but when I download a file on desktop, I have to open my file explorer and navigate to wherever I saved it to open it, which is an amazing pain

**Comment by jryans** [comment]
Related to https://github.com/vector-im/riot-web/issues/14149
