### ISSUE TITLE
RSS Bot can no longer subscribe or unsubscribe RSS feeds

### ISSUE THREAD

**Issue by taw00** [vector-im/riot-web#14194]
In my scenario, in a private channel on matrix.org, I have an RSS Bot running. It has been configured with several feeds for ... a long long time. It continues to chug along posting links to feed entries as they are published. But, I can't add or subtract feeds:

Today I went to unsubscribe one feed and to subscribe another. Both actions failed and the error was the same: "Unexpected token < in JSON at position 0"

I don't know where RSS Bot bugs should be reported and someone suggested here (riot-web). I don't know if this is a riot-as-interface issue, or if it is a matrix.org issue, or if this is a bot issue ... I don't even know where the bot code lives. Regardless, the bot doesn't currently work.

Thanks.

**Comment by jryans** [comment]
@taw00 Are the feed URLs you tried to remove / add working properly, or could they possibly be returning error pages instead of proper feeds?

**Comment by taw00** [comment]
The one I am attempting to subscribe to is just fine (a legit rss feed that I subscribe to in feedly as well):
```
<?xml version="1.0" encoding="UTF-8"?><rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0" xmlns:media="http://search.yahoo.com/mrss/"><channel><title><![CDATA[ ...yadda yadda yadda...
```

The one I am attempting to unsubscribe from is no longer functional (it is showing a red triangle exclamation point in the feed listings), but once was (it's SSL cert is expired or something). I am no longer interested in it anyway, but ... if you go to the feed in a browser, it returns a page complaining about it being insecure. When I use wget to save the results to a file it looks something like this:
```
--2020-06-25 13:44:54--  https://www.example.org/feed/
Resolving www.example.org (www.example.org)... 93.184.216.34
Connecting to www.example.org (www.example.org)|93.184.216.34|:443... connected.
The certificate's owner does not match hostname ‘www.example.org’
```

I'm guessing what the bot is trying to parse is that last line (I think that is the actual message). It's not XML because the XML doesn't exist. Of course, I am not certain why upon an unsubscribe the bot would need to download the XML anyway. You are shooting the thing in the head.

I also tried to unsubscribe from a feed that ISN'T broken and it failed to unsubscribe. This time it gives an HTTP 500 error and lists the broken feed. So it sounds like the error message is associated to broken feeds in the list and maybe not the feed I am working on. Regardless, I can't add a feed and I can't subtract a feed.
---
So maybe this issue tracker should read: **RSS Bot can no longer subscribe/unsubscribe from RSS feeds if you have a broken feed already configured.** Maybe?

**Comment by jryans** [comment]
Okay, indeed that seems to match what's reported over in the bot's repo: https://github.com/matrix-org/go-neb/issues/315. Let's track it over there, as there's nothing Riot can do about this issue.
