### ISSUE TITLE
New room list: Invites seem to have tag settings now

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#14198]
![image](https://user-images.githubusercontent.com/279572/85707827-78437000-b6db-11ea-9cb6-70a413e3d9f4.png)

Is that expected...? It's different from before at least.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/85763959-13a10900-b70d-11ea-8ba8-f4b448ac60b9.png)

**Comment by turt2live** [comment]
I imagine we'll want to add an accept and reject button to this instead.

**Comment by turt2live** [comment]
Temporary design: No context menu.

**Comment by t3chguy** [comment]
Depending on which of this and https://github.com/matrix-org/matrix-react-sdk/pull/4858 land first the other has more work to do

**Comment by t3chguy** [comment]
okay, added the same logic to notifications context menu in above PR
