### ISSUE TITLE
New Room List: Don't "show less" if you're already showing 2/2 items in a section.

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#14219]
![new_room_list-dontshowless](https://user-images.githubusercontent.com/1917473/85881186-1ff09900-b7d5-11ea-9b2e-d1b37e24ea7d.png)

The "show less button" here isn't being useful, - clicking it does nothing, and i'd more likely close the list section than show less than 2 items.

Perhaps always show all items if 1-2 items in list, then add in the show more/ show less option if > 3 items.

**Comment by turt2live** [comment]
whoops, that shouldn't be there.
