### ISSUE TITLE
New room list: Move room tile context menu to be right of tile

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14226]
Currently it is fit within the room list. It should be statically sized and to the right of the menu, as shown in the Notifications project designs.

**Comment by t3chguy** [comment]
> statically sized

Can you elaborate? Should it be truncating i18n'd text or what?

**Comment by turt2live** [comment]
should just wrap. Right now it matches the room list width, it should just be the width of the designs with whatever natural consequences.
