### ISSUE TITLE
New Room List: Dark mode rooms feel harder to see than light-mode

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#14220]
Just a subjective comment, but i think that after moving to the new room list it's harder to see bolded (new activity) rooms than it was before. I know there's a gray dot on a black background too but that is also quite hard to see. I wouldn't even mind a white dot on a dark background.

I might get used to it over time, but right now it doesn't feel very visible.

**Comment by turt2live** [comment]
Going to merge this with https://github.com/vector-im/riot-web/issues/14043 for now

**Comment by benedikrok** [comment]
I doubt that we are already using the latest colors specified for the re-brand. Please let me know what it the current status of the color implementation!
