### ISSUE TITLE
New room list: notification badge overflows

### ISSUE THREAD

**Issue by Georift** [vector-im/riot-web#14225]
Old room list:
![before](https://user-images.githubusercontent.com/859430/85931478-3e4eb580-b8f7-11ea-90a7-67d8e9532679.png)
New room list:
![after](https://user-images.githubusercontent.com/859430/85931481-43ac0000-b8f7-11ea-8177-05f3ebae7d12.png)

Are we OK with making the badge expand like the previous version? If so I'd be happy to put together a PR.

Tested on riot.im/develop running riot-web version: 69f72e330aae-react-5172c7b205a2-js-68c7273f56d5

**Comment by turt2live** [comment]
Normally we'd be happy to accept PRs, however this particular feature is still in ongoing and active development. Some of the rebranding work going into the app is likely to fix this, so I've blocked it behind that for now.

**Comment by turt2live** [comment]
Turns out this is a regular bug which only applies to the sublist headers.
