### ISSUE TITLE
Handle show_room_tile on view_room in new room list

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14233]

**Comment by turt2live** [comment]
This doesn't exist

**Comment by turt2live** [comment]
This actually does exist when a room tile is clicked from an a11y point of view, to ensure the list scrolls to have the tile in view. We should replicate that.

**Comment by t3chguy** [comment]
Also extends to the alt-arrows and alt-shift-arrows behaviour

**Comment by turt2live** [comment]
decision: expand as needed, taking heavy inspiration from other apps.
