### ISSUE TITLE
Improve reliability of new sticky sublist headers

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14232]
There's a few states that are known to not be handled well:
* [x] Height of left panel changing
* [x] Init (bottom missing)
* [x] Collapsing lists
* [x] Whatever fixes https://github.com/vector-im/riot-web/issues/14253
* [x] Fix https://github.com/vector-im/riot-web/issues/14318
* [x] Fix https://github.com/vector-im/riot-web/issues/14371

**Comment by turt2live** [comment]
Sticky headers are changing, this is blocked.

**Comment by turt2live** [comment]
relevant patches have landed for this, so things might be fixed (or new issues discovered)

**Comment by t3chguy** [comment]
Sticky headers are changing, this is blocked.

**Comment by turt2live** [comment]
This appears done
