### ISSUE TITLE
Support stacked headers in the room list

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-web#14243]
due to the lack of stacked sticky headers the easiest way to scroll up is click the sticky header currently visible and subsequently scroll up further. However, this requires the user to wait for the scrolling due to clicking to finish, because manually scrolling after clicking stops the automated scrolling

**Comment by turt2live** [comment]
This is a browser limitation. We simply tell the browser to scroll and it does the needful.

**Comment by turt2live** [comment]
I've converted this to an ask for stacked headers at it has a better chance of being looked at that way.

**Comment by mvgorcum** [comment]
Doesn't that make this a dupe of #14085?

**Comment by turt2live** [comment]
Oh, so it does. Let's track this there for design.
