### ISSUE TITLE
Email option not coming while register on Riot Web

### ISSUE THREAD

**Issue by yugdeep17** [vector-im/riot-web#14246]
Hi All,

I am new to riot. I have setup my own riot server.
I am facing an issue that a user can register only with user name and password.
While i want to register the user with their email id also, so that if they forget their password they can reset themselves.
But i am not seeing any option in my riot web.

Please assist. I have attached the screenshot.

Thanks.
![qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq](https://user-images.githubusercontent.com/61185415/86018274-bd9cd000-ba42-11ea-9ad2-b639e8688722.jpg)

**Comment by t3chguy** [comment]
The server (Synapse) has to include email in the registration flows, this is part of Synapse configuration homeserver.yaml.

This is a bug tracker, for support seek https://matrix.to/#/#synapse:matrix.org

**Comment by yugdeep17** [comment]
Thanks @t3chguy 
I tried to add the email in homeserver.yaml but its now working.
Can i have a working example for email setting.
 It would be great help. 

Thanks

**Comment by t3chguy** [comment]
As said above,

> This is a bug tracker, for support seek https://matrix.to/#/#synapse:matrix.org
