### ISSUE TITLE
New room list: Collapsing a room list section while partially scrolled down it causes the first click to jump slightly, where the second click then collapses as expected

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#14253]

**Comment by turt2live** [comment]
ah ha, this might be the reason for the jumpiness of the sticky headers (https://github.com/vector-im/riot-web/issues/14138): scrolling slowly shows the header scroll nearly past the viewport before jumping down. We might need some padding (calculated by JS) to reliably take over.

**Comment by turt2live** [comment]
This doesn't appear to be an issue for anyone anymore.
