### ISSUE TITLE
New room list: Tile context menu for tagging

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14269]
Outstanding concerns:
* Considering https://github.com/vector-im/riot-web/issues/14038, what are the options themselves?
  * Currently we have Favourite and Low Priority, but if Low Priority goes away then the favourite interaction might feel bare.
* Designs needed for toggled-on state (bold?).

Development:
* [ ] Make it work
* [ ] Designs as appropriate

**Comment by t3chguy** [comment]
> Designs needed for toggled-on state (bold?).

Presumably this should match the Notifications menu which gets accented and a checkmark:

![image](https://user-images.githubusercontent.com/2403652/86134606-c1336400-bae1-11ea-8455-84eec13cd546.png)

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/4858 gets rid of the `Low Priority` option as per the design

**Comment by turt2live** [comment]
Actually going to merge this in with https://github.com/vector-im/riot-web/issues/14038 for ease of representation
