### ISSUE TITLE
Help recovering an account

### ISSUE THREAD

**Issue by CameronNemo** [vector-im/riot-web#14285]
### Description

I have no way to reclaim an account that I still have access to. I am logged in on exactly one device, but I cannot recover the password. I have not backup options to change the password. The device I am logged into will not allow me to change the password without entering the current password.

Is there anyway I can recover this account?

### Steps to reproduce

- idiotically refrain from attaching any backup email or other recovery options
- change password to something and forget to write it down
- cry

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
Riot is just a Matrix client which runs entirely in your browser.

Most Matrix servers demand your password to add a recovery method and obviously to change your password. Your best bet is to contact the server admin of the Matrix server which you are using.
