### ISSUE TITLE
keytar storage isn't aware of profiles

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#14287]
The keytar name the pickle key is stored under is the same regardless of profile.

**Comment by dbkr** [comment]
Actually it stored under matrix ID and device ID so this shouldn't be a problem, but empirically it seems to be causing the same symptoms as an indexeddb deletion.

**Comment by jryans** [comment]
To be clear, this is about different sessions from the same app (not different applications)? macOS keychain does support locking items to a specific app by default, so wasn't sure if keytar is using that feature.

**Comment by dbkr** [comment]
Keychain grants access by application but the items are stored by 'name' and 'account', so riot running as any profile will use the name 'riot.im' but the 'account' field will be different (since the device ID would be different). The 'name' is just by concention so other apps could use/request 'riot.im' but the user would have to grant permission.

**Comment by dbkr** [comment]
Actually I think the symptoms I'm seeing are probably due to an indexeddb format upgrade between electron 8 and 9, and I was inadvertently switching between them. Closing for now.
