### ISSUE TITLE
New room list: Favourites selection and low priority

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14283]
* [x] Selected states: https://github.com/vector-im/riot-web/issues/14283#issuecomment-653189860
* [x] Low priority toggle in advanced room settings: https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=1955%3A0
  * MVP: Toggle in room settings, section in room list (hidden if empty)
  * Could be improved with a contextual interaction - nice to have.

**Comment by nadonomy** [comment]
Outstanding things to solve:

- [ ] Be resolute on whether we want to have the context interaction on the room list to also let you mark low priority rooms
- [ ] Designs for context menu states when rooms are/aren't favourited (do we use the same green checkmark pattern from notifications radio interactions? Or, do we use hollow/filled star iconography? etc)

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/86403000-11d5c900-bc6a-11ea-827e-3f893bc93132.png)
