### ISSUE TITLE
New room list: Hovering over room should moves notification button

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#14297]
(Sorry there are no screenshots, but I've broken them on my laptop... :cry:)

Many rooms (?) have the little bell icon on them, which when you click give you notification options, but when you hove over the room the "..." appears for more options which then moves the bell icon to the left. This leads to a bit of a feeling of "argh, why are buttons moving?!?!?" for me. Maybe we should swap the "..." and bell icon so that the bell icon doesn't move?

**Comment by niquewoodhouse** [comment]
I think that's a great suggestion, and would match the "..." "+" currently used in the headers for People and Rooms.

**Comment by nadonomy** [comment]
Adding to the design queue to validate further. :)

**Comment by turt2live** [comment]
(taking off the room list board as it's being tracked elsewhere)

**Comment by benedikrok** [comment]
We already swapped the positions in the designs:
https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=480%3A570

**Comment by bwindels** [comment]
https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/%5B%2334%5D-Room-List?node-id=480%3A570
