### ISSUE TITLE
New room list feedback: Reduce default rooms to 5

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14296]
10 DMs is a lot

**Comment by bmarty** [comment]
Should be responsive: if user have only 10 DMs (and no other rooms), he should see them without having to expand anything.

**Comment by nadonomy** [comment]
@turt2live in the interest of keeping the scope trim, if 10 is feeling too big in practise I think we should reduce to 5 or so for now as a quick win, but then explore suggestions like @bmarty's in detail as medium-low priority nice to have.

**Comment by turt2live** [comment]
Tracking the further improvements at https://github.com/vector-im/riot-web/issues/14320
