### ISSUE TITLE
New room list: slightly too much padding about the search box

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#14301]
### Description

![image](https://user-images.githubusercontent.com/1342360/86416044-cb5f8900-bcc0-11ea-9686-a86b57bbc177.png)

Looks like we could save a little bit of vertical space by eliminating some of the padding between the search box and the breadcrumbs bar.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by bwindels** [comment]
figma should have the right padding, make the implementation in line with that.

**Comment by JorikSchellekens** [comment]
Unfortunately the figma uses even more space, however it does look much more balanced.

![image](https://user-images.githubusercontent.com/23084468/87107707-6378e780-c258-11ea-9c1d-8c5d80658a81.png)

Clearly Irene is Irene's favourite conversational partner.
