### ISSUE TITLE
New room list: Collapsing the people section shows a rooms section with the section header at the bottom

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#14300]
### Description

![image](https://user-images.githubusercontent.com/1342360/86415621-8850e600-bcbf-11ea-88f0-4668c2553469.png)

After closing the People section, as there were a lot of people, the list of group rooms I'm in showed up. However, the section header was at the bottom.

Changing to another room fixed the layout.

I did this right after refreshing Riot.

This does not seem easily reproducible.

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
it was probably off the bottom before the collapse, and the collapse didn't trigger a recalculation of headers.
