### ISSUE TITLE
New room list: favourites sublist shinking as I read rooms

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#14305]
My favourites section of the new room list kept shrinking by one tile each time I switched to an unread room. The tiles go missing completely (there's no way to reveal them by showing more or dragging).

Filtering and unfiltering did not bring back the missing rooms. Switching to a room outside of favourites **did** bring back all the favourites rooms, and now they have stopped disappearing. 😵

**Comment by turt2live** [comment]
Closing as a likely side effect of https://github.com/vector-im/riot-web/issues/14314
