### ISSUE TITLE
invites in new room list are alphabetic rather than chronological and i can't get them chronological

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14309]

**Comment by nadonomy** [comment]
@turt2live is there any reason why not to expose the same sublist context menu and interactions? Which of the contextual checkboxes or radios would be problematic technically? As we could just remove those, and leave sorting options only, for example.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/86482787-854f0780-bd4a-11ea-9abd-5c35178334f8.png)


Well surely `Activity` is non-sensical and would need to be `Age` or something.

Unread and Message previews also make no sense here

**Comment by turt2live** [comment]
Considering invites are on the cutting floor for notifications, I think we can get away with calling it "Activity" for now. Removing the nonsensical options (previews, unread first) makes sense.
