### ISSUE TITLE
New room list: Auto-expand groups when showing filtered list of rooms by search string

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#14308]
Will be good to auto-expand groups when showing filtered list of rooms by search string, like in old room list.

**Comment by nadonomy** [comment]
@turt2live @t3chguy would this suggestion mirror with what we plan to do for a11y anyway?

**Comment by turt2live** [comment]
a11y is a massive bucket, but should be careful about continually putting things into it. I'd consider this feature parity, not a11y.
