### ISSUE TITLE
Settings - Appearance: "Use a more compact ‘Modern’ layout" is displayed twice

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-web#14304]
I got this option twice in Appearance tab by checking advanced options in riot.im/develop:
<img width="375" alt="Screenshot 2020-07-03 at 09 45 40" src="https://user-images.githubusercontent.com/8969772/86445491-c75c5700-bd12-11ea-8c5b-7c2eb498da32.png">

**Comment by jryans** [comment]
Just noticed this would go out with the release, so I'll try to fix it up, since @JorikSchellekens is away today.
