### ISSUE TITLE
New room list: Overscroll when resizing can create gaps

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14303]
Possibly mac-specific

**Comment by turt2live** [comment]
not actually fixed - the resizer can apparently create a many-hundred pixel gap on macs.

**Comment by JorikSchellekens** [comment]
I haven't noticed this since turt2live replaced the resizer. I'm hesitant to call it call it resolved because it was hard to reproduce reliably. If I don't see it by tomorrow evening I'll close this.

**Comment by JorikSchellekens** [comment]
Haven't seen this at all. @turt2live it's up to you whether to close this

**Comment by turt2live** [comment]
I haven't heard any complaints, so will close.
