### ISSUE TITLE
new room list: unable to uncollapse low priority

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-web#14311]
I clicked the low priority header which collapsed the rooms, but clicking again doesn't show the rooms again. Restarting riot-desktop-nightly didn't help

**Comment by mvgorcum** [comment]
I managed to uncollapse it by clicking the header when searching for a room.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/14273
