### ISSUE TITLE
Filtering the room list leaves sticky headers in the wrong place

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14318]
See video from https://github.com/vector-im/riot-web/issues/14317

**Comment by turt2live** [comment]
Likely same cause as https://github.com/vector-im/riot-web/issues/14300

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/14232

**Comment by t3chguy** [comment]
So I reproduced this as a case of display:none being left around in case a header goes from off-the-top (and not the shown sticky top header) to some other state.
