### ISSUE TITLE
Filtering the new roomlist is very sluggish

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14317]
Video is linked from this message; watch with audio to see the problem.  About 500ms lag on typing.

https://matrix.to/#/!NTUKVQdPRwdQhaunBn:matrix.org/$JtLX5zC6NsQa7Erv8xSWJ8B9RiEtfH6DgausmX-7MGs?via=matrix.org&via=t2l.io&via=riot.ovh

**Comment by turt2live** [comment]
for my reference: `sluggish filter.mov`

**Comment by ara4n** [comment]
(this was on nightly, ftr)

**Comment by turt2live** [comment]
The educated guess on this is that with every key press it's re-running the filter on *all* rooms to see if any new ones match. In practice, we could probably be a bit smarter and track relatively lightweight collections for filtered rooms at particular points. 

The common cases for filtering would be:
1. Adding more characters to the query -> Fix by only checking if the already-filtered rooms match still (smaller search size)
2. Fixing typos (backspace) -> Re-use calculated filters as a starting point
3. Clearing the search -> Pretty obvious: throw away the results (we already do this)

This could still mean that lag happens while we're searching over 3000 rooms at the first character. We could probably throw a bit of a throttle down or ensure that we stop calculations when the filter changes (as I'm sure we're overlapping a bit too).

**Comment by turt2live** [comment]
Aside from the above, it could also simply be the 200kb of logs it generates with every key press.

**Comment by turt2live** [comment]
This looks fixed now. If it continues to be a problem, please re-report.
