### ISSUE TITLE
hoverover on the new roomlist is very sluggish and lags the cursor by about 50-100ms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14327]
there's also a 1px gap between the roomtiles which might accentuate this effect, given the list cycles through three different states (top highlight, no highlight, bottom highlight) as you move from top to bottom rather than going straight from top highlight to bottom highlight for adjacent roomtiles.

I'm assuming we're rerendering the whole control to show the highlight rather than just the roomtile in question?

https://matrix.to/#/!NTUKVQdPRwdQhaunBn:matrix.org/$osH6nyWINQfcwA80kColxW_EN1zQJP38_WacMsNVXxo?via=matrix.org&via=t2l.io&via=riot.ovh "sluggish hoverover.mov" shows this in action on my roomlist.

**Comment by turt2live** [comment]
The gap feels a bit required as without it (either through elimination or smarter padding) the list feels a bit broken. The effect you're seeing is likely performance related where the browser is dropping fps (and therefore layout updates) due to the thing screaming in the background.

**Comment by turt2live** [comment]
It looks like this is basically https://github.com/vector-im/riot-web/issues/14035 causing fps drops rather than anything spectacular. Will leave this open to double check though.

**Comment by turt2live** [comment]
This looks fixed now. If it continues to be a problem, please re-report.
