### ISSUE TITLE
Jump to media

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14331]
The same as https://github.com/vector-im/riotX-android/issues/1540 it'd be nice to have this in riot-web.

Please make Riot jump to according position in the timeline selecting a media in `Files` panel.

**Comment by t3chguy** [comment]
It already does this when you click the timestamp of the item in the Files panel.

![image](https://user-images.githubusercontent.com/2403652/86515527-65cee200-be11-11ea-999b-e849eab6253a.png)

**Comment by 532910** [comment]
Indeed. So it must be more clear.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4479
