### ISSUE TITLE
Recent UI update changes defautls for room sorting

### ISSUE THREAD

**Issue by noc0lour** [vector-im/riot-web#14334]
### Description

A recent update to https://riot.im/develop changes default room/user sorting

Previously the sorting defaulted to activity based and rooms with unread messages have been at the top. 
A recent update to the UI on riot.im/develop changes this to sorting A-z and not displaying unread messages at the top. 

It would break a lot of user expectations if this is published as is in a release and it would be really good to retain the old 
behaviour as default and just add the new options for users to change their sorting.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 72
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
We have intentionally made this decision - there's options on the individual lists to change the ordering.

**Comment by noc0lour** [comment]
Have these options is great and all, i just want to raise a point that this breaks with a lot of user experience. I guess I need to look into patching this for a hosted version.

**Comment by marcusmueller** [comment]
@turt2live I can see why one would want to change defaults for new users.

But why for existing ones? This means a bit of  personal support effort for people running instances with many existing users that got used to the way it was specifically set up now.

We're running such an instance, and truth be told, the update that breaks ui in such a surprising (if easy to fix for each individual user) way won't be perceived by the majority of our users as upgrade.
