### ISSUE TITLE
Something goes wrong with filtering and resizing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14354]
<img width="379" src="https://user-images.githubusercontent.com/1190097/86606350-1d283d80-bf65-11ea-858a-537a4795089f.png"/>

**Comment by t3chguy** [comment]
not sure what I am looking at here @turt2live

**Comment by turt2live** [comment]
@t3chguy Matthew's room list got royally screwed up.
![image](https://user-images.githubusercontent.com/1190097/86926235-0e6d9200-c0ef-11ea-901c-c0fba3971730.png)

That's supposed to be the start of at least a few more tiles.

**Comment by turt2live** [comment]
I think this is the gap issue.
