### ISSUE TITLE
New Room List: Control items in room list sidebar the same as in main room timeline: eg "you changed your name" should be hidden

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#14366]
When you change your name on your account, the sidebar updates to say "You changed your name" as the current state in the room.

That's not intrinsically very helpful (i know the last thing I did was to change my name) and is especially confusing given the room timeline itself is (with my config preferences) hiding that information.

Maybe this issue would be better expressed as: If it doesn't show up in the main room timeline, it shouldn't show up in the room list preview.

**Comment by turt2live** [comment]
we'll tackle this as a nice to have - it needs some thinking alongside how to handle reactions in the previews.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/14662
