### ISSUE TITLE
multple images in welcomeBackgroundUrl cycles through them on each keypress in username field

### ISSUE THREAD

**Issue by Bubu** [vector-im/riot-web#14364]
### Description

Setting multple images in welcomeBackgroundUrl cycles through them on each character entered in username field. It also cycles through the images a few more times during the actual initial sync then. Also when putting the cursor into and then outside the username field again.

### Steps to reproduce

- Set `welcomeBackgroundUrl` to something like
```        "welcomeBackgroundUrl": [
	    "themes/riot/img/backgrounds/dunvegan.jpg",
	    "themes/riot/img/backgrounds/rum.jpg",
	    "themes/riot/img/backgrounds/dutch_lake_clearwater.jpg"
	],
```
- go to login and start typing

Can be seen in action here: https://riot.bubu1.eu/#/login

The option is documented as "choses a random image for each visit". So I expected the image to stick around until the next visit to that page/pressing f5/logging out again and not changing 15 times during one login.

Logs being sent: no

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Firefox 78.0.1
- **OS**: Arch Linux
- **URL**: riot.bubu1.eu; version 1.6.4 currently

**Comment by t3chguy** [comment]
"Its a feature"

Just kidding, but it is pretty funny :')

**Comment by Bubu** [comment]
Uhm, also it seems when I start on the welcome screen and click sign-in it reloads different pictures a bunch of times. :see_no_evil:
