### ISSUE TITLE
3pid invite and revokation lead to incorrect summary

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#14363]
- An existing room menber event is in the timeline
- Invite a user by email.
- Revoke the invitation.

Expanded:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/3940906/86802704-92833380-c075-11ea-8ea5-eafb11b22ce2.png">

This is correct.

But when collapsed the summary is not correct: 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/3940906/86802759-9dd65f00-c075-11ea-9002-3f0ddee83961.png">

-> `was invited 2 times` is not correct.

Note that if there is no previous Room member change, the two third party invite events are not collapsed.

**Comment by t3chguy** [comment]
> Note that if there is no previous Room member change, the two third party invite events are not collapsed.

Yes, the summary threshold is at 3 events currently
