### ISSUE TITLE
Message power levels

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14365]
Ideally messages would have a power level too, showing who can read it. Setting the power level above zero means communicating with the admins only - and admins themselves (including abuse bots) can set power levels higher to remove material from public view.
Some possible use cases:
- Inter-admin discussions (including or excluding mods and whatever other levels there might be);
- Removing abusive messages without destroying the trail - so auditing remains possible.
- Sending "private" messages to all admins at once - better than having to choose one single admin to DM;
- Having "advanced" material only readable for members who have reached that state (reflected in a slightly raised power level).

**Comment by t3chguy** [comment]
Please open an issue in https://github.com/matrix-org/matrix-doc/

**Comment by Biep** [comment]
Done.

**Comment by Biep** [comment]
This is actually part of my earlier proposal #11600.
