### ISSUE TITLE
New room list: People header overlaps filter input on first load

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#14390]
![room-list-header-overlap](https://user-images.githubusercontent.com/279572/87055992-eb310880-c1fc-11ea-92a0-19fdff814443.gif)

As of today on develop, when I refresh the page, the people sublist header seems to start at the top for some reason, and eventually overlaps the filter input once the breadcrumbs appear.

Once I scroll down far enough through my favourites so that the top of the people sublist moves into visual range, the people sublist header jumps to the correct place.

**Comment by turt2live** [comment]
this was supposed to be fixed in the PR that landed >:(

For some reason a header ends up on top but the padding doesn't get applied so there's no gutter for it to fall into.

**Comment by turt2live** [comment]
looks like the initial layout is completely screwed. My invites and favourites are in the wrong places:
![image](https://user-images.githubusercontent.com/1190097/87063821-118a8000-c1cc-11ea-8f6e-e8ba035f954b.png)

**Comment by t3chguy** [comment]
I cannot reproduce it, its wrong for me for a split second and it fixes itself

**Comment by neilisfragile** [comment]
I can regularly reproduce fwiw, at least a few times per day. I mention in case it would be helpful to have a case in the wild.
