### ISSUE TITLE
Add focal to Ubuntu repository

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14396]
It is missing.

**Comment by tulir** [comment]
It's not missing, the per-distro repos were replaced with `default`

**Comment by jryans** [comment]
Yes, we've stopped adding per-distro repos.

**Comment by Biep** [comment]
So what does that mean for me?  What must I change to get rid of the error message and be able to download Riot again?
See [this message](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$I0UuLuhdrpwxnGqHRLai8t6IGD-M-Lfoj3LwQhKiTa4?via=matrix.org&via=privacytools.io&via=mozilla.org).
Should I replace "focal" by "default"?

**Comment by jryans** [comment]
You would need to update your `apt` config, but basically yes, replace with default. See also https://riot.im/download/desktop/.

**Comment by Biep** [comment]
OK, so I now have
`deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main`
in my config.  Will try downloading again when I am on a good connection.
