### ISSUE TITLE
on hitting 'show more' on the new room list, a11y can incorrectly mark the newly displayed room as having keyboard focus

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14395]

**Comment by turt2live** [comment]
specifically if there's not enough rooms to warrant a 'show less' button (ie: 5 rooms)

**Comment by t3chguy** [comment]
> a11y can incorrectly mark the newly displayed room as having keyboard focus

The a11y code *should* be putting the focus on the top-most new tile, the one which would be in a similar location to the `Show more` button, I am not following what is `incorrect` about this?

**Comment by t3chguy** [comment]
I believe this is caused by https://github.com/vector-im/riot-web/issues/14426

Where it causes it to put the focus one too far

**Comment by turt2live** [comment]
Blocked by https://github.com/vector-im/riot-web/issues/14426 as it could very well fix it

**Comment by turt2live** [comment]
Current theory is that https://github.com/matrix-org/matrix-react-sdk/pull/4964 will fix this, though testing is required.

**Comment by t3chguy** [comment]
Regression caused by https://github.com/matrix-org/matrix-react-sdk/commit/96f296885403f73a6db5360fd1ea105a430463ba#diff-f90ab14c3901148afd3231b9329c95ccL221
