### ISSUE TITLE
Unit testing.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#144]

**Comment by pafcu** [comment]
Some unit tests exist. Does this issue refer to some specific unit tests, or could this issue be closed?

**Comment by turt2live** [comment]
I believe it's more targeted as an ever-increasing goal to have more unit tests. The few that do exist have some coverage, but as always there can be more ;)

**Comment by pafcu** [comment]
Right, but does an issue that just say "Unit testing" contribute to that effort? I don't think anyone will forget that unit tests are needed. Perhaps this could then be a place to collect what unittests are missing currently?

**Comment by turt2live** [comment]
To be honest, I misread the age of this particular issue. If it were updated with a list of test cases to add, then it might be useful as a tracker issue.

**Comment by ara4n** [comment]
it was more "we need UT framework" ,which didn't exist at the time. nowadays it does!
