### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by Gozala** [vector-im/riot-web#14406]
Hi,

I have old riot app installed on my mac which is has active login to my account @gozala:matrix.org. I want to use riot on my iphone and can't recall the password, but I'm unable to recover it because I don't have email set in to my account.

Is there a way to recover it somehow from the roit-desktop on mac ? I looked bit into source code to try to figure it out. But all I could find is this
https://github.com/vector-im/riot-desktop/blob/a11feaca324a004c2f93ee18b8b348cc4e56e894/src/electron-main.js#L378-L386

It seems to store some key in the keychain, but there seems nothing in my keychain with `riot.im`. Nor `keytar.findPassword('riot.im')` seems to find anything.

Is there someway I could recover password from the riot-desktop that seems to login ? And if not would deactivating my account release the id so I can create it over again ?

Thanks

**Comment by turt2live** [comment]
Passwords cannot be recovered in this way. Please use #riot-web:matrix.org for support.

**Comment by t3chguy** [comment]
(Riot doesn't store passwords, during login it exchanges your password for an Access Token; to change your password you need both the Access Token and the Existing Password, vast majority of Matrix servers have that same requirement for adding a recovery e-mail address too)
