### ISSUE TITLE
[Build][develop] Dependency to canvas failing for ARM

### ISSUE THREAD

**Issue by floviolleau** [vector-im/riot-web#14400]
### Description

Question about why the dependency (on develop branch) "canvas" is needed?

I don't see any usage in the code of it.

I'm asking because the yarn installation on arm is failing at step 4 saying that this is unable to download node canvas prebuild for arm:
`404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v79`

### Steps to reproduce

- yarn install

Describe how what happens differs from what you expected.

No arm prebuilt for node-canvas

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: N/A
- **OS**: Raspbian 10 buster | node v13.14.0
- **URL**: N/A

**Comment by t3chguy** [comment]
> I don't see any usage in the code of it.

It is not needed for production builds hence it being a devDependency, it is needed for the automated tests suite (Jest).
