### ISSUE TITLE
New room list: small lists can cause weird cutoff artifacts when selecting rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14413]
![image](https://user-images.githubusercontent.com/1190097/87216407-b0ae9500-c2fc-11ea-9059-c128a8cf6287.png)

I've selected my VM DM here, which caused Ryan's hair to go missing. Probably related to the scroll margins?

**Comment by t3chguy** [comment]
Empirically it is not related to the scroll-margins but instead, the a11y feature of making sure the room tile you select is visible
