### ISSUE TITLE
Avatars are not displayed correctly when resistFingerprinting option is enabled in Firefox

### ISSUE THREAD

**Issue by maskedriotuser** [vector-im/riot-web#14419]
Hello,

When the [privacy.resistFingerprinting](https://wiki.mozilla.org/Privacy/Privacy_Task_Force/firefox_about_config_privacy_tweeks) option is enabled in Firefox, user and room avatars are not displayed correctly.
For example, here is what it looks like on Firefox 78.0.1 on Linux:

![avatar](https://user-images.githubusercontent.com/68146982/87223864-fce6ed00-c36f-11ea-81e5-960d741719f1.png)

Among other things, ``privacy.resistFingerprinting`` makes Firefox send a Windows User-Agent.
But I also have the problem on a Windows device with this same option enabled.
On some previous versions of Firefox (77 for example) the avatars appeared as just blank circle.

I guess it's safe to say that a lot of Riot users are concerned by privacy, so this option might be used frequently.

**Comment by t3chguy** [comment]
The default avatars are generated using canvases as it is the sane way to generate imagery client-side without huge JS dependencies and/or relying on a server to do it.

Firefox's resistFingerprinting mangles canvases which causes many strange effects, errors which cause a blank circle or it to just address random data/memory which looks like the stripes you show above.

There isn't much Riot can do as adding huge dependencies to replace canvases would add a lot of weight and slowdowns for something which Firefox lets you whitelist per-site nowadays as I understand it.

If you don't trust the Riot instance which you are using I suggest you host your own and then whitelist it from resistFingerprinting

**Comment by maskedriotuser** [comment]
Thank you for your reply.

If anyone else has the same problem, I've found a workaround:

1. In `about:config`, temporarily set `privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts` to `false`.
2. Reload the Riot / Element page. Firefox should ask if you want to allow the website to access canvas data.
3. Reload again the Riot / Element page, avatars should now be displayed correctly.
4. Finally you can set the option back to `true`.
