### ISSUE TITLE
Guest account gets lost when clicking on login

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1443]
Using Vector as a guest and wanting to register I made a mistake and clicked on login rather than register. On the login page I clicked on "Create a new account" but my username wasn't pre-populated anymore (and given it's a random number I forgot it): my account is lost.

Can we keep the account along that flow so that I don't lose it?

**Comment by ara4n** [comment]
@AmandineLP "Return to app" should do this?

**Comment by AmandineLP** [comment]
Apparently it does. Can we make it more explicit? It didn't occur to me. "Continue as guest" or similar?

**Comment by uhoreg** [comment]
fixed by ILAG?
