### ISSUE TITLE
[Accessibility?/UX] Default-generated user icons smehow feel unpleasant to look at

### ISSUE THREAD

**Issue by ell1e** [vector-im/riot-web#14433]
*(This issue is forwarded from here: https://github.com/matrix-org/synapse/issues/7826 )*

### Description

I don't know if it's just me, but I find the default-generated user icons are straining/painful to look at. I'm not a scientist so I am not sure why exactly this is, but I have identified a way to improve it:

*Current generated icon:*

![](https://user-images.githubusercontent.com/64124388/87298662-12881e00-c4fa-11ea-84f7-5047ac6146e0.png)

*Manual edit of mine that somehow feels way better for me (I just made the stripes 6px wide, from previously 1px):*

![](https://user-images.githubusercontent.com/64124388/87299339-57f91b00-c4fb-11ea-8bbc-5ecd38a349b9.png)

I have no idea if it's just me, or why exactly these larger stripes are better. But at the chance that I'm not alone with this, I am hereby suggesting to collect more feedback from others and consider changing it because I find the current icons really strangely unpleasant to look at. So if I'm not alone, it definitely sounds like worth changing.

### Steps to reproduce

- 1. Open up riot and join any channel
- 2. Observe the unchanged default icons of other users or channels where a custom one wasn't set

(screenshots see above)

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
Do you have resistFingerprinting enabled in your Firefox? Enabling that causes data read from canvases to look like random stripes like you have found.

**Comment by ell1e** [comment]
Interesting, that appears to be indeed the issue. But since allowing canvas access just turns the avatars into solid colors, why isn't riot just using plain background color divs? Seems like it's quite unnecessary to even require canvas access for this

**Comment by t3chguy** [comment]
> just using plain background color divs?

Because things like the Notifications API do not support that https://developer.mozilla.org/en-US/docs/Web/API/notification/Notification

> icon: A USVString containing the URL of an icon to be displayed in the notification.

So to be able to show that same icon in the notification it must be done in canvas

**Comment by ell1e** [comment]
Couldn't the parts in the riot UI still use the div approach, or is that too much effort to implement? Because then it would at least look right everywhere but the notifications (which I have disabled anyway, not sure how common that is and whether that justifies a separate code path)

**Comment by t3chguy** [comment]
Having to make sure that two different codepaths for one underlying feature work just sounds brittle. It isn't the only place where canvases are needed so working around a browser with broken canvases sounds like a waste of time

**Comment by ell1e** [comment]
Ok, then I'll close this. (even though from a user side I am kind of hoping you rethink this some day, but up to you)

**Comment by t3chguy** [comment]
Canvases are required for local thumbnailing such as required in e2ee rooms and for videos, its especially bad when the browser returns false data rather than erroring like it used to. Firefox lets you whitelist sites nowadays though

**Comment by maskedriotuser** [comment]
See https://github.com/vector-im/element-web/issues/14419#issuecomment-667531145 to allow only Riot / Element to access canvas data.
