### ISSUE TITLE
Clicking 'invite' in the member list when you don't have permission does nothing

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#14435]
So you sit there clicking on it a bit wondering what's going on.

It should give feedback telling you you don't have permissions. It should also probably appear greyed out. With a hover text that says you don't have permissions to invite people.

Sorry if this is already filed - I couldn't find it if it is.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/87368705-5456aa00-c576-11ea-8826-4717748518c2.png)

It does get greyed out and gets a `not-allowed` cursor

**Comment by lampholder** [comment]
Peculiar - that's not the experience I had, but I can't reproduce it now either. I'll unfile this bug and shout if I encounter it again.
