### ISSUE TITLE
Room list sorting by name is unusable...

### ISSUE THREAD

**Issue by JigmeDatse** [vector-im/riot-web#14449]
![Screenshot_20200702_203814](https://user-images.githubusercontent.com/66363/87341664-de632c00-c4fe-11ea-9baa-5551fa663a78.png)

This is what the room list looks like when not using the "new and improved" UI which has a lot of rooms which float to the top.

![Screenshot_20200713_114629](https://user-images.githubusercontent.com/66363/87341759-fcc92780-c4fe-11ea-8bcf-29f4c7949188.png)

This is what the "new and improved" UI gives me which for me is an absolutely *horrible* UX for me.  See there are 85 rooms to go through in order to find the 21 which (if I'm reading this right) which have active messages in it.  

But, I guess I'm just an idiot, because I heard about the new thing, and I was told "trust us, we know what we're doing, it will be lovely."  It doesn't just *look ugly* it's non-functional.  

Prior to today, I was able to get something to work more or less like the screenshot from July 2nd.  As of today, I can't see that option at all.  

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
There's a 3 dot menu to the right of the section names which should make this easier.

In general we appreciate feedback, but unfortunately all this says is that it's bad but doesn't explain how we could improve it. Please give the options a chance, and if you find it's still unusable then open an issue explaining how we can improve instead of how it sucks.
