### ISSUE TITLE
New room list show more incorrectly when more=1

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#14461]
Initial:
![image](https://user-images.githubusercontent.com/2403652/87403976-73c0f780-c5b5-11ea-90a6-ad78b6ef7f6e.png)

After a manual resize it shows `Show 1 more` when there isn't 1 more to show
![image](https://user-images.githubusercontent.com/2403652/87403977-74598e00-c5b5-11ea-8f42-36147861baf6.png)

Clicking it actually shrinks the sublist and then subsequent clicks no-op
![image](https://user-images.githubusercontent.com/2403652/87403979-74f22480-c5b5-11ea-8049-255cb991abf2.png)

**Comment by turt2live** [comment]
from my understanding it is showing the 'show more' appropriately, it's just doing the wrong thing when clicked.

**Comment by t3chguy** [comment]
That may be the case, I am basing my wording on old behaviour behind which the intent may have changed

**Comment by turt2live** [comment]
yea, the intent did change: the button now needs to show up for things relating to cutting tiles with transparency, so it also has a slightly awkward count to it.

**Comment by turt2live** [comment]
This looks fixed on the Secret Branch
