### ISSUE TITLE
Failed to start - your element is misconfigured

### ISSUE THREAD

**Issue by janvlug** [vector-im/riot-web#14479]
### Description

I was going to try the new element.io web app. Something went wrong when I tried to verify my session.
![image](https://user-images.githubusercontent.com/5903208/87545256-f4602080-c6a7-11ea-98e7-6a1a97871eaa.png)

I'm using Firefox on Fedora 32. I removed element.io cookies, and tried again, but I still have this problem.

**Comment by t3chguy** [comment]
This is likely one of your browser extensions blocking requests to matrix.org.

**Comment by janvlug** [comment]
I confirm that disabling Privacy Badger made element.io working.

**Comment by lulucasono** [comment]
What is going on ?
What changed in riot, now element, that my pricacy badger breaks it ?

**Comment by t3chguy** [comment]
Privacy Badger has a heuristic which says if a domain is accessed from multiple sites, such as matrix.org would be (from riot.im and from element.io) then it assumes it is a bad domain and blocks it.

**Comment by perremba** [comment]
I just installed the stand alone version and got exactly the same error...

**Comment by CsatiZoltan** [comment]
@perremba Today I discovered that the standalone versions are somehow connected to the web versions. There was an option in the web version to install the standalone application. When I did so from a web version that did not work, the standalone version had the same issue.
In my case, installing from the Brave browser resulted in a problem, however, installing from Chrome went fine. Here is a screenshot showing that the standalone application somehow knows where it was installed from.
![standalone](https://user-images.githubusercontent.com/12742890/94903058-7e46ab00-0499-11eb-9cb4-67004337d811.png)

**Comment by t3chguy** [comment]
I don't think you're installing the standalone version but in fact the browser PWA version, which is no different than using your browser.

**Comment by t3chguy** [comment]
The standalone application should be installed from Element.io Get Started

**Comment by CsatiZoltan** [comment]
@t3chguy What is PWA?

**Comment by t3chguy** [comment]
Progressive Web App: https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DDesktop&hl=en&oco=0

**Comment by CsatiZoltan** [comment]
You are right, that's what I installed.

**Comment by frankgerhardt** [comment]
> I confirm that disabling Privacy Badger made element.io working.

I have this issue as well and disabling Privacy Badger is not an option. This ticket should not have been closed. 

I uninstalled element-desktop again because it is unusable for me, all the hard work on it you did is wasted. As if it wouldn't exist.

**Comment by krisfris** [comment]
Just had the same problem after updating my system (`apt upgrade`). Removing the config directory (~/.config/Element) solved the problem for me.

**Comment by ekron** [comment]
Confirming **Firefox, Privacy Badger and app.element.io** fail in some cases.

Try this in Firefox with the Privacy badger add-on:

- Click Privacy Badger in the toolbar.
- Click the Settings icon (cog) in the top right.
- Click the "Disabled Tabs" tab
- Make sure app.element.io and matrix.org are in the list of domains.

**Note**: this will remove any protection offered by Privacy Badger on these domains. But it is a work-around for those who are willing to disable Privacy Badger.

**Comment by absort0** [comment]
In KDE, changing the default browser from Konqueror to Firefox will make it work.
