### ISSUE TITLE
New room list: A-Z ordering with "Always show unread first" doesn't put unread room back after reading it

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#14475]
### Description

If I select a room list to order from A to Z, but with the "Always show unread room first" option enabled, the unread rooms jump to the top but never go back down to it's A-Z location after reading them. Over time this causes the rooms to be scrambled again and hard to find.

### Steps to reproduce

- Set a room tag to order from A to Z, with the "Always show unread room first" option enabled
- Wait for a room to receive a new message so it jumps to the top of the list, then read it
- Notice the room not jumping back down to it's A-Z position

### Version information

Riot 1.6.8.2

- **Platform**: web (in-browser)
- **Browser**: Firefox 78.0.2
- **OS**: Alpine Linux
- **URL**: https://app.element.io

**Comment by auscompgeek** [comment]
I'm seeing this too now. I think this is a regression from Riot 1.6.8.

**Comment by t3chguy** [comment]
> I think this is a regression from Riot 1.6.8.

In Riot 1.6.8 rooms re-ordered randomly so its not a regression :D

**Comment by MacLemon** [comment]
I consider sort oder alphabetically or sort order via last-activity to be mutually exclusive from a UI point of view.

There is no first and second order criteria obvious to the user that would make sense to use last-activity as a first order sort criteria and alphabetical room name as the second order criteria. This would give us two blocks of room names, the first one all being sorted by last activity, and the rest being sorted alphabetically.
Meaning active rooms would jump around all the time and over time it would end up in last-activity as the only sort criteria anyway.

It makes a lot more sense to have either last-activity as the sort criteria to always have the most recently updated room on top (exclusive) or an alphabetical list, to always have the same room in the same spacial location so users can benefit from muscle memory and knowing the alphabet for their navigation.

**Comment by PureTryOut** [comment]
How are they mutually exclusive? First order by unread status, then if read order them by A-Z. It's how I expected it to work and how it sometimes does work but most of the time not. I don't see how one excludes the other.

**Comment by auscompgeek** [comment]
> > I think this is a regression from Riot 1.6.8.
> 
> In Riot 1.6.8 rooms re-ordered randomly so its not a regression :D

I meant with the new room list lab enabled.
