### ISSUE TITLE
Notiication settings: Settings stuck on "use default"

### ISSUE THREAD

**Issue by johnsu01** [vector-im/riot-web#14484]
### Description

I can't change the notification settings for any rooms I'm in away from "Use default".

### Steps to reproduce

- Click the bell next to the room name in the sidebar

- See that notifications are set to "Use default" (there is a check mark next to it)

- Try to click another setting, such as "Mentions and keywords". Nothing happens. Would expect the notification setting to change.

### Version information

- **Platform**: in browser

- **Browser**: Firefox 78.0.2 
- **OS**: Manjaro GNU/Linux
- **URL**: app.element.io v1.7.0

I had the same issue with previous versions of Riot -- when the notification selector was a toggle, it would briefly toggle on and then switch back to off by itself.

I do have uBlock Origin and NoScript installed. But I've tested with uBlock Origin disabled for the site (and reloaded), and NoScript is allowing all the scripts.

**Comment by t3chguy** [comment]
You might want to check your Matrix server logs if you are the server admin otherwise contact them, it is erroring.

```
2020-07-15T13:28:54.943Z E Internal server error
m@https://app.element.io/bundles/0064a9a4cd78f3935e9d/vendors~init.js:2:487134
p/</i<@https://app.element.io/bundles/0064a9a4cd78f3935e9d/vendors~init.js:2:486750
p/<@https://app.element.io/bundles/0064a9a4cd78f3935e9d/vendors~init.js:2:486907
_request/_<@https://app.element.io/bundles/0064a9a4cd78f3935e9d/vendors~init.js:2:486061
t/</r.onreadystatechange/<@https://app.element.io/bundles/0064a9a4cd78f3935e9d/vendors~init.js:2:20760
t/</r.onreadystatechange@https://app.element.io/bundles/0064a9a4cd78f3935e9d/vendors~init.js:2:20784
```

**Comment by t3chguy** [comment]
Closing as a server issue
