### ISSUE TITLE
new room list community filtering sometimes gets stuck

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#14487]
filtering with both text + community and then removing the community filter does not show the right rooms, its still applying the filter even though the community is no longer selected

**Comment by lampholder** [comment]
I encounter this multiple times a day - more now that the selected community highlights is more subtle (and easier to miss)

**Comment by t3chguy** [comment]
Good thing there's already a PR to fix it then :P

**Comment by lampholder** [comment]
Woop woop woop thank you thank you thank you 🥇 👍
