### ISSUE TITLE
new room list text filtering sometimes nopes out

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#14491]
![image](https://user-images.githubusercontent.com/2403652/87570492-a9063c00-c6c0-11ea-967b-c9dce7f062bd.png)

**Comment by turt2live** [comment]
possible causes: changing which communities are toggled

**Comment by t3chguy** [comment]
Yeah am pretty sure that isn't the case due to the other bug I opened which would have resulted in !all my rooms being shown

**Comment by t3chguy** [comment]
Ah, this happens on ENTER

It clears the actual filter but leaves the field
