### ISSUE TITLE
Message reaction is shown as message preview for room

### ISSUE THREAD

**Issue by mawalu** [vector-im/riot-web#14490]
![Screenshot_2020-07-15 Element Element Web Desktop(1)](https://user-images.githubusercontent.com/2027387/87564429-ad325980-c6c0-11ea-82cf-8c363496d3d1.png)

### Description

If a user reacts to a message this reaction will be shown below the room name as preview. This is confusing since it is impossible to see if the user send a message containing just an emoji or if they reacted to some old message.

### Steps to reproduce

- Enable message previews
- React to a message

I would expect the last real message (text, image etc.) to be shown as preview, not a reaction to some previous message. This is also how other messengers handle this.

Logs being sent: no

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Firefox 78.0.1
- **OS**: Arch Linux, 
- **URL**: https://app.element.io/

**Comment by t3chguy** [comment]
Merging into https://github.com/vector-im/riot-web/issues/14298#issuecomment-656768842
