### ISSUE TITLE
Impossible to mark rooms as low priority

### ISSUE THREAD

**Issue by burdges** [vector-im/riot-web#14492]
An upgrade to Element makes it impossible to mark rooms as low priory.  Element also makes it impossible to scroll rooms conveniently, which makes marking rooms as low priority more important.

It's currently essential to downgrade back to Riot to fix these two bugs.

**Comment by t3chguy** [comment]
> An upgrade to Element makes it impossible to mark rooms as low priory. 

Nope, it got moved to Room Settings - https://github.com/vector-im/riot-web/issues/14440
If you have suggestions on how you want the scrolling to function please open another issue

Closing as duplicate

**Comment by burdges** [comment]
Where?  It's really not obvious..

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/87572809-ffc14500-c6c3-11ea-9c38-0feb2c2166e4.png)

**Comment by burdges** [comment]
ugh way down in advanced, that's the last place anyone would look
