### ISSUE TITLE
sort out matrix-react-sdk structure such that jsx compiled source can be used, and apps don't have to jsx transform the sdk itself

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#145]

**Comment by t3chguy** [comment]
@turt2live is this something included in your current ongoing Webpack stuffs?

**Comment by turt2live** [comment]
Not entirely sure what the issue is trying to accomplish, but we use the src tree instead of lib in the new webpack stuff.

**Comment by ara4n** [comment]
i was thinking here about publishing a matrix-react-sdk bundle as pure JS, so apps using it didn't need to know about React or transpiling JSX to JS.

This is the opposite of the recent webpack work which puts the transpilation firmly in the hands of the app, aiui.

That said, this is pretty useless given many other issues stop matrix-react-sdk being usable as a plain JS library currently (and React is now so prevalent, that it's not unreasonable to assume that matrix-react-sdk would always be used by a React app).
