### ISSUE TITLE
Room list preview doesn't always match the timeline on profile update

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#14504]
Just saw the preview tell me a user changed their avatar while the timeline view says they've changed their display name:

![Screenshot from 2020-07-15 20-48-27](https://user-images.githubusercontent.com/5547783/87589363-06a88180-c6dd-11ea-86f3-775ed08200a8.png)

The event is:

```json
{
  "content": {
    "displayname": "Antoine Blondeau",
    "membership": "join"
  },
  "event_id": "$159484155123199ltwfy:matrix.org",
  "origin_server_ts": 1594841551504,
  "sender": "[...]",
  "state_key": "[...]",
  "type": "m.room.member",
  "unsigned": {
    "replaces_state": "$1548161809135331bCTIP:matrix.org",
    "prev_content": {
      "displayname": "nd4pa",
      "membership": "join",
      "avatar_url": null
    },
    "prev_sender": "[...]",
    "age": 1014
  },
  "room_id": "[...]"
}
```

I assume the room list understood the transition `avatar_url == null` -> `avatar_url` not in the content as an avatar change whereas the timeline view ignored it.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/14662
