### ISSUE TITLE
Show presence dot for favorite DM's

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#14503]
**Is your suggestion related to a problem? Please describe.**
It's annoying to not see when favorite DM's are online

**Describe the solution you'd like**
A presence dot on favorite DM's 

The two favorited DM's here are both currently online, but I can't tell 
<img width="277" alt="Screen_Shot_2020-07-15_at_8_04_34_PM" src="https://user-images.githubusercontent.com/19155609/87586364-559fe800-c6d8-11ea-8cfb-c6c84321c508.png">

**Comment by Twi1ightSparkle** [comment]
The presence dot currently also don't show for the favorite DM's in the breadcrumbs, ftr

**Comment by t3chguy** [comment]
For context; it was a product decision that they only appear in the People/DMs list, it is not a regression either.

**Comment by progserega** [comment]
Also it is not show for encripted DM's and for DM with bots (as described in #14524 )

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/87637279-e0fd9580-c739-11ea-80aa-96ff4af811f1.png)

That is incorrect. Encrypted DMs^

**Comment by nadonomy** [comment]
> For context; it was a product decision that they only appear in the People/DMs list, it is not a regression either.

Missing the context— but it sounds fine to me to expose presence dots for users/DMs in favourites, echoing how they're displayed in 'People'.

**Comment by t3chguy** [comment]
@progserega you only get a presence dot on rooms with exactly 2 joined users
