### ISSUE TITLE
Auto-delete non-admin communities

### ISSUE THREAD

**Issue by TheEvilSkeleton** [vector-im/riot-web#14518]
**Is your suggestion related to a problem? Please describe.**

Yes. We have created a community, and the admin left the community, thus making it unusable. We were forced to create another community because of that.

**Describe the solution you'd like**

I would suggest making the community automatically delete once a community does not have an admin anymore.

**Describe alternatives you've considered**

If the above suggestion does get rejected, I would suggest having an issue template for those that want to delete non-admin communities

**Additional context**

The creator (admin) of the community and I got into a little conflict, in which made him leave the community, thus making it a non-admin community. We sorted everything out, but then realized that there were unfortunately no admins. We were then forced to create another community since the one we wanted was taken (and useless).

The adminless community is called `+reverseeagle:privacytools.io` and the new community is called `+reverse_eagle:privacytools.io`. If it is possible, we would appreciate if you can delete the old community (and also implement a way to delete communities), so we can use the old name.

**Comment by t3chguy** [comment]
This shouldn't be a riot-web exclusive feature, I would suggest opening a Synapse issue as that is the server-side implementation of the Communities and thus would apply to any and all clients.

**Comment by resynth1943** [comment]
Thanks!

**Comment by resynth1943** [comment]
@t3chguy would this apply to the spec too?

**Comment by t3chguy** [comment]
Communities aren't in the spec yet, maybe for the pending proposal to rewrite them: https://github.com/matrix-org/matrix-doc/pull/1772
