### ISSUE TITLE
Desktop app icon on macOS

### ISSUE THREAD

**Issue by pixlwave** [vector-im/riot-web#14512]
### Description

With the new Element desktop app, it's icon for macOS is larger than all the other icons in my dock.

### Steps to reproduce

- Update to the latest version of Element
- Open the app and compare with other icons

Logs being sent: no

<img width="377" alt="Screenshot 2020-07-15 at 22 04 31" src="https://user-images.githubusercontent.com/6060466/87596265-bda9fa80-c6e7-11ea-9a00-c39b9d3cbaab.png">

The upcoming macOS 11 icon template is included in both of these design resources if it helps 🙂
https://developer.apple.com/design/downloads/macOS-11-Sketch.dmg
https://developer.apple.com/design/downloads/macOS-11-Photoshop.dmg

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS 10.15.5
- **Version**: 1.7.0

**Comment by jryans** [comment]
We have a revised icon (which I believe also fixes this) at https://github.com/vector-im/riot-desktop/pull/117, so should be fixed soon.

**Comment by pixlwave** [comment]
Nice! Downloaded and applied 👍
