### ISSUE TITLE
Integration manager issue.

### ISSUE THREAD

**Issue by philibertc** [vector-im/riot-web#14527]
### Description

When you click on the integration manager icon, the popup remains white indefinitely.

### Steps to reproduce

- Click on the integration manager icon in the Element or Riot app.
- A popup will appear but nothing is displayed inside.

### Version information

- **Platform**: Web.

For the web app:

- **Browser**: Brave Browser (v. 1.11.74)
- **OS**: Arch Linux (Manjaro)
- **URL**: riot.im/app or app.element.io

![Issue_Screenshot](https://user-images.githubusercontent.com/57588282/87645567-f8467e00-c74d-11ea-82be-363546b63f41.png)

**Comment by t3chguy** [comment]
Do you have any browser extensions like PrivacyBadger or uMatrix? Can you send logs from Settings > Help & About?

**Comment by philibertc** [comment]
> Do you have any browser extensions like PrivacyBadger or uMatrix? Can you send logs from Settings > Help & About?

Hello, no, I haven't any extensions like PrivacyBadger or uMatrix.
The logs have been sent.

**Comment by philibertc** [comment]
> Do you have any browser extensions like PrivacyBadger or uMatrix? Can you send logs from Settings > Help & About?

I made a mistake in my browser version. It's now fixed, maybe this will help you.

**Comment by turt2live** [comment]
Brave is not a supported browser of ours, sorry. It's best to troubleshoot these issues in #element-web:matrix.org
