### ISSUE TITLE
Your browser can't run Element! - in Private Mode of Browser

### ISSUE THREAD

**Issue by flyinghuman** [vector-im/riot-web#14535]
### Description

With latest Element 1.7.0 Release a Error is displayed accessing RIOT-WEB / Element-Web with LATEST Google Chrome Browser Version / LATEST Firefox Browser Version in PRIVATE Mode / INCOGNITO Mode

### Steps to reproduce

Update to latest Element-Web version and access the Element-Web Website with Browser in Private Mode.

### How it should be

Allow also users in Private-Mode to Access RIOT/Element without Error-Message.

(This Error was not seen on app.element.io; only on self hosted instances.)

```
index.ts:73 Browser missing feature: 'crypto'
(anonymous) @ bundle.js:2
rageshake.js:65 Initialised rageshake.
rageshake.js:65 To fix line numbers in Chrome: Meatball menu → Settings → Blackboxing → Add /rageshake\.js$
rageshake.js:65 Using Web platform
rageshake.js:65 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
e.<computed> @ vendors~init.js:2
rageshake.js:65 falling back to ArrayBuffer instantiation
e.<computed> @ vendors~init.js:2
rageshake.js:65 Using WebAssembly Olm
rageshake.js:65 returning explicit theme: dark
rageshake.js:65 returning explicit theme: dark
rageshake.js:65 Loading skin...
rageshake.js:65 Starting watcher for TagPanel.disableTagPanel@<null room> as ID 1594897732184_1_TagPanel.disableTagPanel_null
rageshake.js:65 👋 legacy room list store has been disabled
e.<computed> @ vendors~init.js:2
rageshake.js:65 ⚡ new room list store engaged
rageshake.js:65 Starting watcher for feature_custom_tags@<null room> as ID 1594897732211_2_feature_custom_tags_null
rageshake.js:65 Starting watcher for breadcrumb_rooms@<null room> as ID 1594897732266_3_breadcrumb_rooms_null
rageshake.js:65 Starting watcher for breadcrumbs@<null room> as ID 1594897732266_4_breadcrumbs_null
rageshake.js:65 Skin loaded!
rageshake.js:65 set language to de
rageshake.js:65 Browser is missing required features.
e.<computed> @ vendors~init.js:2
```

**Comment by t3chguy** [comment]
> index.ts:73 Browser missing feature: 'crypto'


Your browsers private mode disabled SubtleCrypto - without this most of the app would not work.

**Comment by flyinghuman** [comment]
> > index.ts:73 Browser missing feature: 'crypto'
> 
> Your browsers private mode disabled SubtleCrypto - without this most of the app would not work.

maybe, but was this introduced since 1.6.5? With 1.6.5 all was fine.

I only use the private mode if i want to check the login-dialog because of custom Design-changes. But maybe other users will use this as usual to access matrix-universe e.g. from workplace.

**Comment by t3chguy** [comment]
Yes, SubtleCrypto is often disabled on http if its not localhost.

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

**Comment by t3chguy** [comment]
Yes the check for it was added since 1.6.5, without SubtleCrypto the app can explode violently.

**Comment by flyinghuman** [comment]
ok, so i will close this issue as it is the intended behaviour
