### ISSUE TITLE
SSO redirect broken

### ISSUE THREAD

**Issue by lchanouha** [vector-im/riot-web#14530]
Hello,
It appears that since upgrade to Element, SSO redirection is broken.

We use SAML2 on our server, and generated server web link riot://vector/webapp/?riot-desktop-ssoid=XXX&loginToken=YYY#/ doesn't trigger Element desktop app which stays stuck to "Utilisez votre navigateur pour terminer la connexion" (use your brower to login).

If i manually  replace riot:// with element:// it works.

Can't find where the reference in the code is :)

**Comment by t3chguy** [comment]
This will be fixed in today's point release. https://github.com/vector-im/riot-web/pull/14513
