### ISSUE TITLE
Sending a tombstone event in favor of an existing room lead to two annoying side effects

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#14532]
I observe this by sending a tombstone event to RiotX android room and link the tombstone event to Element-Android room.

It's maybe some sort of a hack usage of tombstone event though.

## Steps:

- Send a tombstone event to RoomA including the id of an existing room RoomB

## First small bug:

RoomA claims that the room has been upgraded. This is not the case.

## First side effect:

Clicking on the link of tombstone event rendering in RoomA send the user to the beginning of RoomB (the create event). In this case, as this is not a room upgrade, user should should land to the latest message of RoomB

## Second side effect:

Leaving RoomA makes the app also leaves RoomB which is quite annoying.
RoomB's create event does not refer to RoomA as a predecessor, so in this case RoomB should not be left automatically.

**Comment by t3chguy** [comment]
2nd side effect is https://github.com/vector-im/riot-web/issues/10380

**Comment by t3chguy** [comment]
> RoomA claims that the room has been upgraded. This is not the case.

Isn't it?

https://matrix.org/docs/spec/client_server/r0.6.1#id160 `m.room.tombstone` is listed in the `Room Upgrades` section.

**Comment by turt2live** [comment]
Yea, unfortunately we're not able to tell the difference between a redirect and an upgrade. Abusing tombstones for this purpose is generally not recommended, and the people who did recommend this approach will have known that it'll be counted as an upgrade.

**Comment by bmarty** [comment]
> RoomA claims that the room has been upgraded. This is not the case.

True, sorry, I've seen that on RiotX

**Comment by bmarty** [comment]
> Yea, unfortunately we're not able to tell the difference between a redirect and an upgrade

The m.room.create does not contains a predecessor in case of a redirect.

**Comment by turt2live** [comment]
> The m.room.create does not contains a predecessor in case of a redirect.

From a spec perspective, this is an invalid event not a redirect. Redirects are not a thing.
