### ISSUE TITLE
Sidebars: wrong colors in regard to website screenshots

### ISSUE THREAD

**Issue by stephanedupont** [vector-im/riot-web#14548]
So I just updated to the new version of Riot now named Element.

On the website element.io, there are some screenshots like this one:
https://element.io/images/homepage-all-platforms-1.png

On this screenshot, we see the community and rooms side bar with these colors:

- a gradient around #ebeff4 for the room side bar
- a gradient around #dee3e9 for the community bar

And that works fine.

But on the actual Riot/Element web client, the colors are:

- a gradient around #dddddd for the room side bar
- #b2b2b2 for the community bar

And I know colors are subjective, but god that's hideous. It's way prettier on the screenshots on the website.

Why this difference? Is it intended? If yes, can we skin it easily?

**Comment by t3chguy** [comment]
The gradient across those bars is based on your User Avatar

**Comment by stephanedupont** [comment]
Well, it seems to me that it shouldn't be then... Is there at least a way to disable this?

**Comment by t3chguy** [comment]
Not yet 

Closing for https://github.com/vector-im/riot-web/issues/14493

**Comment by stephanedupont** [comment]
I mean, for a black and white avatar, it makes the bars look darker, and that's really bad, here's a screenshot:

![image](https://user-images.githubusercontent.com/5102441/87700718-14bad880-c797-11ea-852c-421409731d23.png)

**Comment by stephanedupont** [comment]
Not yet, but you are closing it, does that mean that disabling it is planned already?

**Comment by t3chguy** [comment]
All "blur is unexpected/undesirable" issues are being tracked in #14493

**Comment by stephanedupont** [comment]
Thank you. But it seems like a different problem (it's not a blur issue, text is perfectly readable, the issue is the background color). Should I mention it in #14493?

**Comment by t3chguy** [comment]
Sure, but the background colour is due to the blur of the background image imposed underneath it.

**Comment by stephanedupont** [comment]
Thank you!
