### ISSUE TITLE
"Upgrade to your own domain" broken link

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#14547]
### Description

When using a matrix.org account, the "Upgrade to your own domain" link is broken.

Currently it links to https://modular.im/services/matrix-hosting-riot?utm_source=riot-web&utm_medium=web&utm_campaign=user-context-menu which redirects to https://element.io/matrix-services-riot?utm_source=riot-web&utm_medium=web&utm_campaign=user-context-menu. That last page 404's

![Screen_Shot_2020-07-16_at_5_22_29_PM](https://user-images.githubusercontent.com/19155609/87696811-3f9e3000-c789-11ea-904a-9515a9f30132.png)

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 78.0.2 (64-bit), but I this likely is the same on all browsers and desktop apps?
- **OS**: macOS
- **URL**: app.element.io

**Comment by turt2live** [comment]
Fixed in the release 2 minutes ago.
