### ISSUE TITLE
my favicon is missed

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14562]
after the update to 1.7.1:

element-desktop 1.7.1 debian sid:
![image](https://user-images.githubusercontent.com/14617699/87731174-8401ee00-c7d2-11ea-8c40-c69368850c81.png)

element-web 1.7.1 hosted on my server:
![image](https://user-images.githubusercontent.com/14617699/87731246-b01d6f00-c7d2-11ea-82d4-9ac65487cfe5.png)

https://app.element.io shows my userpic correctly

**Comment by turt2live** [comment]
Cannot reproduce - it's likely a local issue or temporary network failure.

**Comment by 532910** [comment]
It's shown in the settings:
![image](https://user-images.githubusercontent.com/14617699/87736534-085b6d80-c7e1-11ea-86f9-726ffc5acf23.png)

and in my contact view:
![image](https://user-images.githubusercontent.com/14617699/87736570-25903c00-c7e1-11ea-8dba-31d6058c368d.png)

I believe there no network failures.

**Comment by 532910** [comment]
I got:
```
psycopg2.IntegrityError: duplicate key value violates unique constraint "local_media_repository_thumbn_media_id_thumbnail_width_thum_key"
DETAIL:  Key (media_id, thumbnail_width, thumbnail_height, thumbnail_type)=(pwJGenkxEQAsZUFtmdCjriRH, 32, 32, image/png) already exists.
```
in homeserver.log

#2182 says it does not appear to affect local media.

Is this an another issue?

**Comment by turt2live** [comment]
That's a synapse problem, nothing to do with Element.

**Comment by 532910** [comment]
Sorry, I meant https://github.com/matrix-org/synapse/issues/2182.
The question is this is the same synapse issue, or another one?
