### ISSUE TITLE
~/.config/Element (Riot) is created

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14561]
```
% ls -1d ~/.config/Elem*
/home/sergio/.config/Element/
/home/sergio/.config/Element (Riot)/
```

**Comment by t3chguy** [comment]
Did you run both 1.7.0 and 1.7.1?

**Comment by 532910** [comment]
The same time? No.

**Comment by 532910** [comment]
Steps to reproduce:
1. kill all riots and elements
2. `rm -rf ~/.config/Element*`
3. run element
4. two directories will be created

**Comment by t3chguy** [comment]
Will be fixed in next version

**Comment by 532910** [comment]
ack
