### ISSUE TITLE
room tile presence icon should respect disabled presence

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#14568]

**Comment by turt2live** [comment]
It does? Where are you seeing that it doesn't?

**Comment by t3chguy** [comment]
Oh. You are right. Someone complained that it didn't and I thought it was a thing we probably missed.

**Comment by hpdeifel** [comment]
I think I'm that "someone" and unless I'm misunderstanding something, it's broken for me:

- I have `use_presence: false` in my synapse config
- Riot shows little grey dots next to DMs with local users with a tooltip saying "Offline"

**Comment by t3chguy** [comment]
Do you have `enable_presence_by_hs_url` configured as per https://github.com/vector-im/riot-web/blob/develop/docs/config.md to hide presence for your HS in the Element instances pointed at it?

https://github.com/vector-im/riot-web/issues/4398

Element has no way of knowing your server has presence disabled, it just tells us Offline.

**Comment by hpdeifel** [comment]
Ah, thanks! Well that answers my original question whether it has to be configured client-side or server-side (e.g. well-known). Unfortunately, I have no way of controlling the Element configuration of my users.
