### ISSUE TITLE
M_UNKNOWN Returned

### ISSUE THREAD

**Issue by silentshotghost** [vector-im/riot-web#14571]
M_UNKNOWN was returned while trying to access the room

happened when trying to join a matrix.org room from a privacytools.io account 

riot-web version: 1.6.5
olm version: 3.1.3

Homeserver is https://chat.privacytools.io
Identity Server is https://chat.privacytools.io

**Comment by t3chguy** [comment]
That is a Server error and thus you should be asking the admins of the server it came from
