### ISSUE TITLE
"Riot is now Element" toast should have a dismiss button

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14575]
Surely all tooltips should have dismiss buttons of some kind...

**Comment by t3chguy** [comment]
presumably you mean toast?
Should it dismiss forever or dismiss until you refresh?
I think it was intentionally not dismissable at first, should only be shown to you once per-session if you interact with it

**Comment by LookitheFirst** [comment]
Can we get the option to disable it on new instances? Since it will probably confuse new users who never used Riot

**Comment by turt2live** [comment]
after a few releases I imagine we'll take it out instead of leaving it there forever. Could also use a custom welcome page which does `localStorage.setItem("mx_rename_dialog_dismissed", "true");`

**Comment by LookitheFirst** [comment]
> after a few releases I imagine we'll take it out instead of leaving it there forever. Could also use a custom welcome page which does `localStorage.setItem("mx_rename_dialog_dismissed", "true");`

Thanks, that works for me

**Comment by tredondo** [comment]
I think it should have a [more convincing explanation first](https://github.com/vector-im/riot-web/issues/14685).

**Comment by lmojzis** [comment]
In my opinion this message should be optional and you should be able to opt-out without setting localStorage without user's consent OR hack the js bundle and risk breaking the app altogether. I installed it on a new instance - there are no users yet, yet all the users who will register will be informed about Riot now being Element which they don't care about in the first place. PLUS they can't dismiss it because such change is SO important you have to acknowledge it in a modal. Fun.

**Comment by lmojzis** [comment]
For future reference, If you want to hide the "Riot is now Element" toast, I replaced `localStorage.getItem("mx_rename_dialog_dismissed")` with `false` in `bundles/2bf2e97955bd40c82b34/vendors~init.js` and it worked

**Comment by dbkr** [comment]
We talked about a couple of solutions to this. One was adding the dismiss button to the one-time toast (not the one that nags you to move to a new domain). We also talked about saving the fact you've dismissed it into account data so each user sees it only once. Conclusion is that we're going to add the dismiss button for now, as we don't want to litter people's account data with the boolean flag or have to clean it up.

NB. We've already renamed the desktop app from 'Element (Riot)' to just 'Element', so this will go out in the next release, so the next release of the desktop app will just be called 'Element' but *will* still have the one-time toast (with a dismiss button).

**Comment by nadonomy** [comment]
> We talked about a couple of solutions to this. One was adding the dismiss button to the one-time toast (not the one that nags you to move to a new domain). We also talked about saving the fact you've dismissed it into account data so each user sees it only once. Conclusion is that we're going to add the dismiss button for now, as we don't want to litter people's account data with the boolean flag or have to clean it up.

Just for clarity for future selves, the dismiss button should be in the updated native apps and element web instances on element.io only, as we're still monitoring traffic on old riot.im/app & *.riot.im instances and will make a call on what to do there in the coming weeks.
