### ISSUE TITLE
Getting some graphic artifacts under ubuntu

### ISSUE THREAD

**Issue by mogoh** [vector-im/riot-web#14577]
### Description

The picture says it all:

![Screenshot_20200717_123817](https://user-images.githubusercontent.com/580975/87779206-ba6c5700-c82c-11ea-820c-f82f9781b7b8.png)

### Steps to reproduce

- Start the App ...

Some clues:

The same bug affects multiple Apps, based on electron, installed via Flatpak.
I have opened a second issue over at: https://github.com/flatpak/flatpak/issues/3749

### Version information

- **Platform**: desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Ubuntu 20.04
- **Version**: 1.7.1
- **Installed via Flatpak**

~~~
$ flatpak info im.riot.Riot 

Element - Create, share, communicate, chat and call securely, and bridge to
other apps

         Kennung: im.riot.Riot
             Ref: app/im.riot.Riot/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         Version: 1.7.1
         License: Apache-2.0
        Ursprung: flathub
      Collection: org.flathub.Stable
    Installation: system
       Installed: 226,5 MB
Laufzeitumgebung: org.freedesktop.Platform/x86_64/19.08
             Sdk: org.freedesktop.Sdk/x86_64/19.08

          Commit: 8228d8bab5916ab273e99ec317175acf17550059cd3e72def08c68b78fc1cfcb
          Parent: 9ef7506d320f018c258b3cebc57169421a6be8175d875c10ed248355b6e52e63
         Subject: Update element-desktop_1.7.1_amd64.deb (3f514872)
            Date: 2020-07-17 03:27:58 +0000
~~~

**Comment by t3chguy** [comment]
Does the bug exist with the official distribution? https://riot.im/download/desktop/ (`element-desktop` is available at the same repository)

**Comment by mogoh** [comment]
> Does the bug exist with the official distribution? https://riot.im/download/desktop/ (element-desktop is available at the same repository)

No, it does not.
The Flatpak is not offical?

**Comment by t3chguy** [comment]
The Flatpak is community maintained.
https://element.io/get-started has the official Debian/Ubuntu repo instructions

**Comment by t3chguy** [comment]
Going to close this in favour of the upstream bug as it does not seem Element specific. Thanks for reporting though
