### ISSUE TITLE
Error in members list when disabling encryption

### ISSUE THREAD

**Issue by dedlfix** [vector-im/riot-web#14573]
### Description

I'm trying to disable encryption because it's very complicated and confusing for the average user. As a first step I went to matrix-js-sdk/src/crypto/index.js and changed the function isCryptoAvailable() to return false. Seemed successful so far. But when I go to a room, open the Members list, and click one of the users I get the "Something went wrong!" screen and some error messages appear in the browser's console pointing to BasicUserInfo in matrix-react-sdk. (Perhaps there is a better way to disable encryption at all but I couldn't find out.)

### Steps to reproduce

- in matrix-js-sdk/src/crypto/index.js change the function isCryptoAvailable() to return false
- enter a room
- on the top right click the Members symbol
- click a user

### Version information

- **Platform**: web

- **Browser**: Chrome, Firefox - current versions
- **OS**: Windows
- **riot-web**: release-v1.7.1
- **matrix-react-sdk**: release-v2.10.1
- **matrix-js-sdk**: release-v7.1.0

**Comment by t3chguy** [comment]
Could you send logs to save us having to reproduce it? The error stack trace would be enough.

**Comment by dedlfix** [comment]
That was a quick fix. But I guess also [canVerify](https://github.com/matrix-org/matrix-react-sdk/blob/5c8d12ab25e878d0960ea73ee178f5fe6f569b0c/src/components/views/right_panel/UserInfo.js#L1311) needs to be checked for cryptoEnabled, otherwise you'll see an endless spinner for users that are !isMe.

**Comment by t3chguy** [comment]
Good spot. Done
