### ISSUE TITLE
Emoji don't show in firefox

### ISSUE THREAD

**Issue by Sorunome** [vector-im/riot-web#14583]
### Description
Emoji in firefox are just white squares

![Screenshot_2020-07-17_14-41-37](https://user-images.githubusercontent.com/2433620/87787343-c3b0f000-c83b-11ea-8b88-9b6c2354f986.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 78.0.2-1
- **OS**: Arch Linux
- **URL**: app.element.io

**Comment by t3chguy** [comment]
Are you using a custom font?

**Comment by Sorunome** [comment]
@t3chguy no, no custom font

**Comment by t3chguy** [comment]
Strange, they look fine here on Firefox. Can you send logs?

![image](https://user-images.githubusercontent.com/2403652/87787727-040c7000-c834-11ea-9b35-4bafccf0f061.png)

**Comment by auscompgeek** [comment]
FWIW, it's also fine for me in Firefox 78.0.2 on Arch Linux.

**Comment by Sorunome** [comment]
What kind of logs, where / how?

**Comment by t3chguy** [comment]
Settings > Help & About > Submit debug logs

**Comment by t3chguy** [comment]
`2020-07-17T12:50:08.499Z I Canvas check revealed COLR is supported? false`

**Comment by t3chguy** [comment]
Do you have something which removes `Firefox` from your user agent & also resistFingerprinting enabled?

Firefox doesn't let us know if it support COLR so we special-case if the user-agent has `Firefox` in it to assume Yes.



Your UA looks like a Spoofed Chrome one.

**Comment by Sorunome** [comment]
Yeah, seems to be related to that. When disabling https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/ in firefox the emoji suddenly show. Somehow it wasn't enough to just set it in that addon to use the default user agent.
