### ISSUE TITLE
Remove config variable welcomeUserId

### ISSUE THREAD

**Issue by jaller94** [vector-im/riot-web#14580]
**Is your suggestion related to a problem? Please describe.**
As someone new to the project I get confused when seeing a config variable that's seemingly not used anywhere.
`welcomeUserId` does not seem to be used anymore and RiotBot has been shut down.

**Describe the solution you'd like**
Remove all mentions of `welcomeUserId`

**Describe alternatives you've considered**
Leaving it in as an unused config variable.

**Additional context**
https://github.com/vector-im/riot-web/search?q=welcomeUserId&unscoped_q=welcomeUserId

**Comment by t3chguy** [comment]
Just because the official deployments don't use it doesn't mean other deployments don't

I still see it wired up in the code:
![image](https://user-images.githubusercontent.com/2403652/87781338-6c555480-c828-11ea-83f1-bb41d27d571a.png)

**Comment by jaller94** [comment]
Oh, I didn't see those in the search from GitHub.
Ok, if this is still a feature, lets keep it.

**Comment by t3chguy** [comment]
You were likely searching the wrong repo, https://github.com/matrix-org/matrix-react-sdk/ has the majority of Riot code
