### ISSUE TITLE
New room list: Section headers not scrolling properly, overlapping room names, jumpy

### ISSUE THREAD

**Issue by MacLemon** [vector-im/riot-web#14582]
### Description

It's relatively unclear when the “Historical” section appears or disappears from the new room list. (I cannot consistently affect it, seems random to me.)
When it appears, its behaviour is erratic, it doesn't scroll properly with the rest, it stays at the bottom, overlaying other entries (which is inconsistent with the way the new room list is supposed to work, or said to be working.)
I fail at describing how it behaves, see the animated `.gif` to see for yourselves.

### Steps to reproduce

- ? Do unknown things to get a “Historical” section header at he bottom of the new room list
- See that it overlaps other entries when it should not.
- try scrolling it out of view

![Element, Historical Section behaves incoherent](https://user-images.githubusercontent.com/90635/87783151-31f1b480-c834-11ea-9ebe-a9ce472dba9a.gif)

Describe how what happens differs from what you expected.
The section header should behave consistently with the other ones, not overlapping parts of the list all the time. It should not jump around upon scrolling the room list.
It's undiscoverable for me when it appears and when it goes away.

Logs being sent: yes

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: macOS 10.13.6
- **Version**: Element 1.7.1

**Comment by t3chguy** [comment]
The headers stick on both the top and bottom edge, this is intentional and not limited to the Historical header. Its so you can always see both the previous and next header.

> It's relatively unclear when the “Historical” section appears or disappears from the new room list.

It'll be disappearing entirely soon for a dedicated Archive section.
Current behaviour is if you left a room in this session is then it'll be in Historical.

**Comment by turt2live** [comment]
Closing as expected behaviour.
