### ISSUE TITLE
Crash after sending /part

### ISSUE THREAD

**Issue by ndarilek** [vector-im/riot-web#14595]
### Description

I experienced a crash when sending "/part" to leave a room. Submitting logs requires an issue, so here it is. :)

### Steps to reproduce

1. Enter a room.
2. Type "/part" to attempt to leave.

Log: sent    

### Version information

- **Platform**: desktop
- **OS**: Linux (Fedora 32, Flatpak)
- **Version**: 1.7.1

**Comment by t3chguy** [comment]
```
TypeError: Cannot destructure property 'cmd' of 'Tr(...)' as it is null.
    at ym._updateEditorState (vector://vector/webapp/bundles/2bf2e97955bd40c82b34/vendors~init.js:2:4628159)
```

**Comment by t3chguy** [comment]
Hmm, I cannot reproduce it. I can add a null-guard but it doesn't explain what went on for you
