### ISSUE TITLE
Missing Option to remove Rooms from Communities

### ISSUE THREAD

**Issue by Y0ngg4n** [vector-im/riot-web#14590]
### Description

There is no Option to remove Rooms from Communities.

### Steps to reproduce

- View Community and edit it
- Add Room to community
- Search for button to remove it again

Describe how what happens differs from what you expected.

I expect a button to remove a room from a community.

![image](https://user-images.githubusercontent.com/30302975/87797151-99b2fa00-c84a-11ea-8ee8-3cbda41655d2.png)

### Version information

Version von OblivionCoding Riot: 15203bb32b33-react-15203bb32b33-js-15203bb32b33
Version von olm: 3.1.3

For the web app:

- **Browser**: Chrome, Opera, Firefox
- **OS**: Windows, Manjaro Linux
- **URL**: Self hosted

**Comment by t3chguy** [comment]
It is there; see https://github.com/vector-im/riot-web/issues/5743

**Comment by Y0ngg4n** [comment]
@t3chguy thx
