### ISSUE TITLE
Registration: Insecure password prompt is broken looking

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#14604]
### Description

![image](https://user-images.githubusercontent.com/1342360/87837465-7fe5d700-c88b-11ea-8d1e-24a751e90119.png)

This doesn't look great. Also I haven't enabled dark theme so not sure why this is the case.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox nightly
- **OS**: Linux
- **URL**: develop.element.io

**Comment by t3chguy** [comment]
Tooltips in the light app are now styled like that

![image](https://user-images.githubusercontent.com/2403652/87850634-b8b49900-c8e9-11ea-9011-55260862917c.png)

**Comment by t3chguy** [comment]
I will revert it for this one place as it does look strange
