### ISSUE TITLE
Community icons are blurry

### ISSUE THREAD

**Issue by dkasak** [vector-im/riot-web#14607]
Community icons are blurry/washed out in the Element Desktop 1.7.1 release while previously they were fine. This seems to be due to improper scaling. This is on Arch Linux (if it matters). 

![image](https://user-images.githubusercontent.com/463342/87850500-3f647880-c8e0-11ea-8dac-b36fef23824f.png)

When viewing a community's rooms, the room icons are also blurry while they are fine outside the community view.

Blurry:

![image](https://user-images.githubusercontent.com/463342/87850545-98341100-c8e0-11ea-8de0-139b0c937958.png)

Normal (the way it looks outside a community):

![image](https://user-images.githubusercontent.com/463342/87850555-a7b35a00-c8e0-11ea-8f99-3f735fea219f.png)

- **OS**: Arch Linux
- **Version**: 1.7.1

**Comment by t3chguy** [comment]
This is a Synapse thumbnail rounding issue

**Comment by turt2live** [comment]
This is also a spec issue - not something we are going to be able to fix here.

**Comment by dkasak** [comment]
Could you give some more information on why this is a spec issue? It's not obvious to me at first glance.

**Comment by t3chguy** [comment]
We ask for a thumbnail of size X, Synapse gives us one of size 1.5X - this doesn't round cleanly hence blurring. The spec doesn't specify to make the thumbnail round

**Comment by turt2live** [comment]
The spec allows media repositories to return larger-than-requested images.
