### ISSUE TITLE
Double app icon : Element and Element (Riot) on Debian Buster - Dash to Dock

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riot-web#14619]
### Description

On Debian Buster with the Dash to Dock Gnome extension, we get two app icons, one is called "Element" can stay in the dock but doesn't get active and neither get notifications counter, the other one is called "Element (Riot)" , appear in the dock once Element is launched, is active in the dock (but can't stay in the dock, can't be favorite) and gets notifications counters.

### Steps to reproduce
- Add Element to the Dock
- launch Element by clicking on the Element app icon
- A second icon appears : Element (Riot)

Describe how what happens differs from what you expected.

-The second app icon should not appear and the main app icon of Element should become active and gets the notifications counter

Logs being sent: no

![image](https://user-images.githubusercontent.com/464782/87859445-5bded000-c935-11ea-9036-fadc63fb1263.png)

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Debian Buster with Gnome
- **Version**: 1.7.1

**Comment by jryans** [comment]
Hmm, what is this "Dash to Dock Gnome extension"...? How does it decide to read the app name? Does the issue occur without this extension?

**Comment by PopeRigby** [comment]
Also having this issue with KDE Plasma on Arch Linux.

**Comment by Thatoo** [comment]
> Hmm, what is this "Dash to Dock Gnome extension"...? How does it decide to read the app name? Does the issue occur without this extension?

Yes, I've tried. Without the popular Gnome extension "Dash to Dock" then, the native dash/dock (whatever name it has) of Gnome has also two icons.
