### ISSUE TITLE
Missing tooltip on mouse hover over room icons (collapsed room list)

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14610]
### Description

There is no tooltip saying the room name (thus you rely on the first letter or the icon to know which room it is) when you hover over the icon of a room when that left bar (list of rooms) is collapsed. `riot-desktop` did have it.

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by t3chguy** [comment]
I did this last night - it'll be in the next release
