### ISSUE TITLE
Set urgency hint (X11) upon receiving a notification (which are customizable already)

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14614]
https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45805407959456 (`_NET_WM_STATE_DEMANDS_ATTENTION`) and https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#URGENCY may be of help. If you have more questions let me know.

The reason for why I want Element to set the urgency hint is because my statusbar has a visual indicator for urgent windows on a particular workspace.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/3435
