### ISSUE TITLE
Unread first option isn't toggling again

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14624]
A video demonstrating the bug (2, albeit related bugs) can be seen [here](https://streamable.com/7eyos9).

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by t3chguy** [comment]
I cannot reproduce this on neither app.element.io nor develop

**Comment by turt2live** [comment]
Yea, this looks fixed. It was time-based before but after waiting some time it seems fine. If you continue to see problems, please open a new issue.
