### ISSUE TITLE
--profile launch flag broken on Element

### ISSUE THREAD

**Issue by aa1874** [vector-im/riot-web#14623]
After updating to Element Desktop from Riot Desktop, `--profile` launch flag on Element desktop broke. I can't get into other profiles anymore.

**Steps to reproduce:** Open Element Desktop on terminal with `--profile <launch-profile>` launch flag

I expected the launch profile set on launch to load, not the main profile. But the opposite happens. The main profile loads regardless of the `--profile` launch flag.

On Windows, Element Desktop 1.7.1

**Comment by odiferousmint** [comment]
It works for me on Arch Linux. I use multiple profiles.

This is the output I get when I run `element-desktop --profile foobar`:

```
[...]
/home/odiferousmint/.config/Element-foobar exists: yes
/home/odiferousmint/.config/Riot exists: no
[...]
```

It is still odd that it looks for `/home/odiferousmint/.config/Riot` instead of `/home/odiferousmint/.config/Riot-foobar`.

**Comment by aa1874** [comment]
Weird. It works on Linux but not on Windows.

**Comment by t3chguy** [comment]
Which executable are you passing the argument to?

**Comment by aa1874** [comment]
`riot --profile <profile-name>`

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/87872386-f5e35e80-c9af-11ea-8978-3dab7b5002d2.png)
![image](https://user-images.githubusercontent.com/2403652/87872391-f976e580-c9af-11ea-8904-60aec8ef641c.png)

The args need passing to the actual executable which is inside the app-X.Y.Z directory
If you are passing it to any of the executables in the latter directory I do not expect it to work. This is just how Squirrel.Windows works

**Comment by harmathy** [comment]
> It works for me on Arch Linux. I use multiple profiles.

I have this exact problem on Arch Linux. I use multiple profiles since 1.5.x

> This is the output I get when I run `element-desktop --profile foobar`:
> 
> ```
> [...]
> /home/odiferousmint/.config/Element-foobar exists: yes
> /home/odiferousmint/.config/Riot exists: no
> [...]
> ```

Starting a profile after the update gives me:

```
$ /usr/bin/element-desktop --profile work
/home/max/.config/Element-work exists: no
/home/max/.config/Riot exists: yes
Using legacy user data path: /home/max/.config/Riot
```

Did you add the foobar profile after the update to 1.7.x?

**Comment by harmathy** [comment]
However, moving the profile path from `Riot-work` to `Element-work` fixed it for me

**Comment by t3chguy** [comment]
@harmathy this issue is different, it is about

> I expected the launch profile set on launch to load, not the main profile. But the opposite happens. The main profile loads regardless of the --profile launch flag.

**Comment by harmathy** [comment]
@t3chguy that is exactly what I was writing about.

> @harmathy this issue is different, it is about
> 
> > I expected the launch profile set on launch to load, not the main profile. But the opposite happens. The main profile loads regardless of the --profile launch flag.

As opposed to @odiferousmint I have the same issue on Arch Linux. 

> However, moving the profile path from `Riot-work` to `Element-work` fixed it for me

This is a workaround which solved this issue for me.

**Comment by veritanuda** [comment]
> However, moving the profile path from `Riot-work` to `Element-work` fixed it for me

Ditto can confirm it works for the flatpak version as well. Rename your profile directories , for flatpaks that is in `~/.var/app/im.riot.Riot/config` and rename `Riot-<profile>` to `Element-<profile>`. It will  then be picked up with the --profile switch.

This strikes me as something the program could check for, legacy profile names and automatically update them to the new name on first start. It is something I would expect from a project that changes name to be aware it would break old profile configs.

**Comment by odiferousmint** [comment]
> However, moving the profile path from `Riot-work` to `Element-work` fixed it for me

I moved `Riot-foobar` to `Element-foobar` manually which did the trick. :)

**Comment by snegodick** [comment]
Works fine in MacOS:
`open -na "Element" --args --profile=k`
