### ISSUE TITLE
Add option to not apply formatting on sent messages

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14626]
### Steps to reproduce

- Type and send `-`

### Result

![rect18-3](https://user-images.githubusercontent.com/43568459/87863559-6a8cad80-c95c-11ea-8ad5-9cf180999c0e.png)

### Expected

I expected it to show `-`. This happens with `#` and so forth.

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

---

Perhaps you could label this as a feature request instead of a bug as it seems like the formatting UI above the input field does the same thing; just simply adds `**`, `>`, and so forth.

**Comment by odiferousmint** [comment]
> /plain [message] does it

Is there a way (an option perhaps) to "use" `/plain` by default? In any case, I will use `/plain` as a workaround, thank you!

**Comment by compu42** [comment]
> > /plain [message] does it
> 
> Is there a way (an option perhaps) to "use" `/plain` by default? In any case, I will use `/plain` as a workaround, thank you!

I don't think there's an option. That ought to be a thing though. You're welcome!

**Comment by aaronraimist** [comment]
There isn't :(

https://github.com/vector-im/riot-web/issues/483 is the existing issue for this so please add a thumbs up there
