### ISSUE TITLE
"Forget Room" button does not seem to work

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14622]
### Description

Nothing happens upon clicking the "Forget Room" button.

### Steps to reproduce

1. Create a room
2. Leave the room (it now appears under category "Historical")
3. Right click on the room, and then left click on "Forget Room"

It does not do anything. I expected it to actually get rid of the room, but it does not.

### Screenshot

![2020-07-19-004154_276x128_scrot](https://user-images.githubusercontent.com/43568459/87863171-a7ef3c00-c958-11ea-86e4-c9fdd3ae030c.png)

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by turt2live** [comment]
This menu isn't going to survive much longer.

**Comment by rgpublic** [comment]
Well, the menu is still there. The button doesn't work. And there's currently no way to get rid of a "historical" room except from signing off and signing on again. Should I file a new bug?

**Comment by jryans** [comment]
> And there's currently no way to get rid of a "historical" room except from signing off and signing on again. Should I file a new bug?

In my experience, it does work, but just takes much longer to apply than an reasonable person would expect. In any case, yes, please open a new issue to describe what you are seeing.

**Comment by turt2live** [comment]
https://github.com/vector-im/element-web/issues/15559 is the symptomatic issue.
