### ISSUE TITLE
Performance regression on CIDER with new room list

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14639]
There's something about the new Element CSS which means that every key press is doing 30ms of layout in Nightly (even if there are no pills or anything else happening).  Hovering over the layout item in the profiler indicates it's doing a full-screen layout.

<img width="1840" alt="Screenshot 2020-07-19 at 19 22 15" src="https://user-images.githubusercontent.com/1294269/87882073-855f3080-c9f5-11ea-8a7c-d493119a1aa0.png">

**Comment by ara4n** [comment]
[trace](https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$1595183142341960zvZdx:matrix.org?via=matrix.org&via=t2l.io&via=riot.ovh) (internal only)

**Comment by ara4n** [comment]
quite aside from the fact that CIDER shouldn't be redrawing the world, i suspect there are some basic thinkos in our CSS (particularly too much dynamically-sized nested flexbox on the new RoomList) which means that the layout is horribly slow. 30ms is forever on a top-end box. And this is with a roomlist with only ~100 rooms visible.

**Comment by ara4n** [comment]
I just noticed that if you collapse the LeftPanel the layout time for the whole page drops from 30ms to 2ms.  (I'm still surprised it's doing a full CSS layout of the whole page every time i press a button in CIDER though)

**Comment by ara4n** [comment]
(This is with ~10 pages of RoomList shown)

**Comment by ara4n** [comment]
removing `with: calc(100% - 16px)` from `mx_RoomList2` speeds up the full layout from 30ms to 3ms, which makes sense, given `calc` in CSS effectively shells out to JS, iirc.

**Comment by ara4n** [comment]
> (I'm still surprised it's doing a full CSS layout of the whole page every time i press a button in CIDER though)

It turns out that any kind of text input (e.g. into an `<input>` form field, or a contentEditable) triggers a full page CSS layout in Chrome, empirically.  However, generally it takes <1ms (e.g. google is 0.31ms to layout), rather than the 30ms we're seeing here.

**Comment by ara4n** [comment]
another datapoint: naively switching `width: calc(100% - 16px)` for a horizontal flexbox layout (i.e. `flex 1` on lhs and `flex 0 0 16px` on rhs, for a 16px padding box on the RHS) went back to the 30ms layout time.

**Comment by ara4n** [comment]
however, setting `width: 100%` on `.mx_RoomList` but adding `padding-right: 16px` to `.mx_LeftPanel_roomListContainer` seems to do the trick... but has then weirdly slowed back down again :/

I think our level of flexbox nesting here is way too deep and complicated here: wherever we can set static heights/widths we should be, and only use flexbox where strictly necessary.  Likewise `calc()`.

**Comment by ara4n** [comment]
(this is reducing my laptop battery life by 2-3x fwiw)

**Comment by turt2live** [comment]
I can't find this in profiles tbh, but might not be looking close enough (or have fixed it by accident on my dev branch)

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/5034 is the thing which might be masking the problem for me.

**Comment by ara4n** [comment]
given there's no CSS in 5034, it seems a bit unlikely...

**Comment by ara4n** [comment]
also, are you looking in FF or Chrome? i can believe this could be a browser-specific pathological-CSS bug. (also n.b. i have room previews turned on, in case that's impactful)

**Comment by ara4n** [comment]
> removing `width: calc(100% - 16px)` from mx_RoomList2 speeds up the full layout from 30ms to 3ms, which makes sense, given calc in CSS forces a dynamic layout.

I recorded an (internal only, given it shows my account with room previews turned on) [video](https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$1595414969645985mUYhY:matrix.org?via=matrix.org&via=vector.modular.im&via=t2l.io) of this happening (using today's Nightly), to try to make the problem crystal clear:

**Comment by turt2live** [comment]
Was profiling my main account in chrome with previews and an obscene number of rooms present.

**Comment by ara4n** [comment]
confirmed fixed on Electron by matrix-org/matrix-react-sdk#5038

**Comment by fblaese** [comment]
The performance improved quite a bit with 1.7.2.
However scrolling through the room list ist still somewhat laggy with all my ~200 rooms unfolded (On a desktop system with dedicated graphics..)
