### ISSUE TITLE
Notification settings in room settings should allow changing notification level

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#14630]
### Description

When navigation to "Notifications" in the room settings, I expect to be able to change the notification level from there. However, it only allows changing the notification sound, and for the level I have to do it via the context menu in the room list.

![Screenshot_20200719_132831](https://user-images.githubusercontent.com/1565836/87873677-ca6a6f00-c9c3-11ea-840f-ce280ff92380.png)

### Version information

- **Version**: 1.7.1
- **Platform**: web but desktop has the same obviously since it's a UI/UX issue :unamused: 
- **Browser**: Firefox but obviously this is the same over all the browsers
- **OS**: Alpine Linux but obviously this doesn't matter
- **URL**: https://app.element.io

**Comment by t3chguy** [comment]
Yup, this is planned already.

https://github.com/vector-im/riot-web/issues/13960
