### ISSUE TITLE
Wiki rooms

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14645]
Certain rooms could be presented as wikis - the first message being the 'home page'.  Messages can link to one another, and if anyone with sufficient power level can edit the message the quick editability of wiki pages would also be implemented.  Messages/pages would begin with an unique string (the title) between `__double underscores__`, and mentions of those would be turned into links to the corresponding messages.  Attempts to give a message a title that already exists would be caught.  All this could be pure client-side.  I am not sure how to label a room as 'wiki', but a special (emoji?) character as the first character of the room name would already work.  This would add truly new functionality to Matrix - and could also be used for the help function of Matrix and Element themselves.

**Comment by dbkr** [comment]
Interesting idea - I think this would be something to build out in a separate piece of software, then we could consider using it in Element if there were a feature that it could be used to implement.

**Comment by rauldipeas** [comment]
Could you guys use GitBook, mdBook or something like, as integration maybe?

**Comment by t3chguy** [comment]
Sure but for that to be a `Room` then it'd have to be a Matrix Bridge, this isn't the repo for such requests.
