### ISSUE TITLE
The :heart emoji is rendered as a black heart on riot-web

### ISSUE THREAD

**Issue by flackr** [vector-im/riot-web#14657]
### Description

When reacting or sending the :heart: emoji it shows up as a black heart on riot-web even though it shows the correct red heart on mobile devices.

### Steps to reproduce

- React with a :heart: or send one in a message.
- Or, send a heart from mobile

The heart should be red but is black.

Logs being sent: no

![Screenshot 2020-07-20 at 10 58 55 AM](https://user-images.githubusercontent.com/366761/87952652-124ace00-ca78-11ea-97b5-8e1866ad3111.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 83.0.4103.119 (Official Build) (64-bit)
- **OS**: ChromeOS
- **URL**: Private server running riot-v1.7.1.tar.gz

This seems to be a regression.

**Comment by t3chguy** [comment]
This is already fixed on develop.
