### ISSUE TITLE
Messages not sending, but receiving messages fine.

### ISSUE THREAD

**Issue by SkyeWint** [vector-im/riot-web#14682]
### Description

Messages seeming to lag being sent, all messages received from other accounts. No messages actually transmitting to other person. This has happened in the same way with both the web client and desktop application. Windows 10. All other internet functions working at 100% outside of Element. This was the case both before and after the update.

### Steps to reproduce

- Send message.

Message not sent. Screenshots:

![My Perspective](https://user-images.githubusercontent.com/6006884/88094625-bbf99000-cb48-11ea-8edf-2d961c7ef0e6.png)
![Azelast Perspective](https://user-images.githubusercontent.com/6006884/88094910-27436200-cb49-11ea-9413-72d8a7ceed46.png)

Log: Sent via desktop app. Hopefully it transmitted unlike the messages. My account is @skyewint:matrix.org if that is necessary. 

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 78.0.2
- **OS**: Windows 10
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows 10
- **Version**: Element version: 1.7.1    olm version: 3.1.3

**Comment by t3chguy** [comment]
`ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/sync?filter=0&timeout=30000&since=s1465647517_757284957_2014210_552384293_378267938_1447579_72463412_184369934_118721` looks like matrix.org issues - not anything Element can do anything about
