### ISSUE TITLE
Input Editor causes to duplicate typed multiple times (and send it)

### ISSUE THREAD

**Issue by MTRNord** [vector-im/riot-web#14684]
### Description

More often on develop.element.io I get now that when I start to type the type result is not normally just being shown once but at the end of the string it duplicates. And at the end of that duplicate it does the same and so on. It eventually limits itself but on sending it also sends everything I see.

### Steps to reproduce

This is currently unsure. I did not yet find any pattern.

Logs being sent: yes

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 78.0.2 (64-Bit)
- **OS**: Windows 10
- **URL**: https://develop.element.io  ( Version: 6c50aa14ad9e-react-37aed54d125e-js-c7aee7cebdc6 )

**Comment by eternaleye** [comment]
I can consistently reproduce this bug:

1. Type some text
2. Use Control-A to select what I typed
3. _Without_ hitting delete or backspace, begin typing a replacement

**Comment by t3chguy** [comment]
I cannot reproduce this in Chrome but can in Firefox

**Comment by t3chguy** [comment]
Looks to be a regression between master and develop
