### ISSUE TITLE
Red heart emoji is white (or black)

### ISSUE THREAD

**Issue by foresto** [vector-im/riot-web#14693]
![whiteredheart](https://user-images.githubusercontent.com/322134/88125666-9e4a1c00-cb84-11ea-97fb-3c82695f4d27.png)

### Description

Since upgrading from Riot desktop to Element desktop, the Red Heart emoji is now rendered as a colorless heart: white when the dark theme is in use, and black for the light theme. It no longer matches its description or the style of the other emoji.

### Steps to reproduce

- Open the emoji picker or an existing message with a red heart reaction.
- Observe the incorrectly colored heart.

### Version information

- **Platform**: desktop
- **OS**: ubuntu linux
- **Version**: 1.7.1

**Comment by turt2live** [comment]
This is fixed on develop and will be in the next release.
