### ISSUE TITLE
You can't click the context hover popup thing on communities any more - they get stuck and don't work

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#14697]
Like so:
<img width="58" alt="image" src="https://user-images.githubusercontent.com/1922197/88161479-efe7ba80-cc07-11ea-84c0-ccf63c436e91.png">

Instead of popping up the option to view or edit the community, you just pin the (...) in place.

**Comment by t3chguy** [comment]
This was fixed yesterday.

**Comment by lampholder** [comment]
Excellent - I searched for open/closed issues with 'community' in the title but didn't spot anything...

**Comment by t3chguy** [comment]
TagPanel :P
