### ISSUE TITLE
We're leaking mx_Tooltip_wrappers?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14700]
I just noticed I have ~300 mx_Tooltip_wrapper divs as children of my body tag.  Surely this isn't right?

![Screenshot 2020-07-22 at 11 44 15](https://user-images.githubusercontent.com/1294269/88167520-de56e080-cc10-11ea-8932-d4e459240091.png)

**Comment by t3chguy** [comment]
We have one in the DOM for each possible tooltip. Because of CSS animations to simplify having to inject into the DOM and then later update the CSS to show them

**Comment by t3chguy** [comment]
This is a relatively hard thing to resolve as it is possible to have multiple tooltips at the same time due to Fields showing tooltips too
