### ISSUE TITLE
Tooltips account for about 1/5th of the first app render

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14707]
It requires use of `getBoundingClientRect` which triggers a forced style recalc and a forced layout change, multiplied by the potentially hundreds of tooltips in the room list alone.

We should find a better way of positioning them that doesn't cause so many forced renders during the initial app mount.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/88221195-55947080-cc21-11ea-8ec0-02ce1ddaa163.png)

so many tooltips

**Comment by t3chguy** [comment]
With the above PR the app render cost will go away but the forced style recalc will still happen on hover of a tooltip-enabled component.
