### ISSUE TITLE
Integration manager issue

### ISSUE THREAD

**Issue by philibertc** [vector-im/riot-web#14717]
### Description

When you click on the integration manager icon, the popup remains white indefinitely.

### Steps to reproduce

- Click on the integration manager icon in the Element or Riot app.
- A popup will appear but nothing is displayed inside.

### Version information

- **Platform**: web (in-browser).

For the web app:

- **Browser**: Same issue on any browser.
- **OS**: Manjaro Linux
- **URL**: https://app.element.io/

The logs have been sent.

![issue](https://user-images.githubusercontent.com/57588282/88266768-0b1dfd00-ccd0-11ea-8044-a32c80ddbd53.png)

**Comment by dbkr** [comment]
This means the browser can't load the integrations manager - is it being blocked by an extension?

**Comment by philibertc** [comment]
> This means the browser can't load the integrations manager - is it being blocked by an extension?

I'm gonna test.

**Comment by dbkr** [comment]
I've also filed https://github.com/vector-im/riot-web/issues/14718 as I couldn't see an issue for the fact that there's no error (I don't *think* adblock should be an issue: let us know in #element-web:matrix.org if you need further support).

**Comment by philibertc** [comment]
> This means the browser can't load the integrations manager - is it being blocked by an extension?

It was the third-party cookie blocker built into my browser. All works now.
