### ISSUE TITLE
A hotkey to focus search field

### ISSUE THREAD

**Issue by unclechu** [vector-im/riot-web#14710]
As far as I know it’s impossible to start searching rooms by just using a keyboard. It would be nice if there was a hotkey you press to focus search field. Also the Tab key is bound to something else in the message input field so you can’t move your focus outside at all by just using a keyboard.

**Comment by t3chguy** [comment]
Yes there is such a shortcut; 
![image](https://user-images.githubusercontent.com/2403652/88237671-a33bc800-cc77-11ea-82d8-7236b8c02580.png)


Tab trapping is https://github.com/vector-im/riot-web/issues/11071

**Comment by unclechu** [comment]
@t3chguy Didn’t know about `ctrl+/`, thanks.

**Comment by t3chguy** [comment]
It's also in settings > help & about
