### ISSUE TITLE
QR Code Scanner does not work

### ISSUE THREAD

**Issue by ManDay** [vector-im/riot-web#14719]
Doesn't work on current develop branch, never did work on any branch or release for me. It shows the camera with the scanning frame, but nothing will trigger it.

**Comment by t3chguy** [comment]
Web and desktop don't have a QR scanner. Only the mobile apps do.

> It shows the camera with the scanning frame

Can you share a screenshot?

**Comment by ManDay** [comment]
Urgh, sorry, wrong repo.
