### ISSUE TITLE
enable_presence_by_hs_url doesn't allow wildcards

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-web#14716]
### Description

As most of homeservers disable presence, I wish to disable it for all servers by default as currently it causes more harm than good by showing everyone offline or gray against black. Disabling presence for `*` is also easier than keeping a list of every homeserver in the single file.

### Steps to reproduce

- Add `"*": false` to end of `  "enable_presence_by_hs_url": {}`
- Clear cache and reload

Everyone still appears as offline or gray against black, while I expect everyone to be shown as if "online" or white against black in the user list.

Logs being sent: no

![Element-offline-userlist](https://user-images.githubusercontent.com/831184/88260115-6c43d180-cccc-11ea-8812-79c024ba402f.png)

### Version information

- **Platform**: web/Radical web extension

For the web app:

- **Browser**: Firefox 79.0 (64-bit)
- **OS**: Microsoft Windows10.0.19041.388
- **URL**: Radical webextension, Element 1.7.1 / https://addons.mozilla.org/firefox/addon/radical-web

**Comment by Mikaela** [comment]
I was told that `enable_presence_by_hs_url ` makes everyone appear as offline instead of online and after testing with additional config including users visible above I have confirmed this.

**Comment by t3chguy** [comment]
Also `enable_presence_by_hs_url` is only about the hs_url of the logged in user, you have no way of knowing the hs_url of other users, only their server_name

**Comment by Mikaela** [comment]
https://github.com/vector-im/riot-web/issues/12164 seems to be my actual problem assuming that the option accepts wildcards.
