### ISSUE TITLE
Search results in (partially) encrypted rooms misleading (Element Web only)

### ISSUE THREAD

**Issue by rda0** [vector-im/riot-web#14715]
Element Web does not include encrypted messages in search results and therefore shows "No results" for encrypted rooms. It may also show some incomplete results if the room was not encrypted from the beginning. This misleads users thinking the search function is broken.

There should be a hint in the UI (triggered by search button, input field or search result) that they are better off with Element Desktop, when actually trying to search.

**Comment by philibertc** [comment]
Hello, you need to install the desktop app to search among the encrypted messages. This function is not implemented in Element Web.

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/riot-web/issues/12896 basically

**Comment by rda0** [comment]
sorry, didn't find that issue
