### ISSUE TITLE
Adaptive UI

### ISSUE THREAD

**Issue by darkdragon-001** [vector-im/riot-web#14723]
### Description

Element website (PWA) should adapt for small-width screens:
- The leftmost bar with only the "+" icon should be moved somewhere else (it is always a waste of space IMHO)
- The profile/search/people/rooms column should be hidden behind a "…"-button
- Text should be located _below_ the user avatars instead of being right of them

### Steps to reproduce

- Try to shrink browser window to effective 360px width (Librem 5).

Describe how what happens differs from what you expected.

_See [Description](#Description)._

Currently, the app has a minimum width of 500px and is unusable:
![Element-Adaptive-UI](https://user-images.githubusercontent.com/177976/88279699-cc467200-cce4-11ea-9ba9-152045d75896.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu 20.04
- **URL**: app.element.io

### Background

Linux phones are on the rise. Most of the potential users are using Matrix chat protocol (that's why Purism mentions the Matrix protocol for their desktop SMS/chat app [Chatty](https://source.puri.sm/Librem5/chatty/)). The Linux landscape is diverse by nature ([PureOS](https://www.pureos.net/), [UBPorts](https://ubports.com/), [PostmarketOS](https://postmarketos.org/), [Mobian](https://mobian-project.org/), ...) so [PWAs](https://en.wikipedia.org/wiki/Progressive_web_application) are a very promising solution to publish a single app for all platforms (including desktop and mobile). Element/Riot is providing an outstanding PWA so far, but needs some UI adaptions to work in small-width screen scenarios.

[Librem 5 screen info](https://puri.sm/posts/easy-librem-5-app-development-scale-the-screen/), [Demonstration of adaptive behavior](https://puri.sm/wp-content/uploads/2019/05/adaptive-settings.gif)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8733 and https://github.com/vector-im/riot-web/issues/1633
