### ISSUE TITLE
"No known servers" when you try to answer an invite whose invitee has given up and left

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#14722]
Instead we could say something much better like "Sorry, the inviter has already left".

**Comment by t3chguy** [comment]
Except I don't think we can know that for sure? Could just be their server is offline?

**Comment by bwindels** [comment]
I'll go with "Sorry, the inviter has already left" if the inviting user is on the same HS, otherwise ... either query /versions on their server (we'd need to do well-known discovery though) or just say "... or their server might be offline, in this case try again".

**Comment by t3chguy** [comment]
> (we'd need to do well-known discovery though)

And also ask the user if they are happy for their IP to be leaked to that service (privacy)

**Comment by bwindels** [comment]
Hmm, true. Shame the HS doesn't let us distinguish between inviter has left and server could not be reached.

**Comment by t3chguy** [comment]
Sounds like a spec issue :P
