### ISSUE TITLE
Broken Keycap sequence emojis - web & desktop

### ISSUE THREAD

**Issue by DanieLoche** [vector-im/riot-web#14745]
### Description

On Desktop application (tested W10 & Ubuntu 20.04) and Web, sequences emojis like :one: are not rendered properly.

### Steps to reproduce

- Open Element (any version).
- Write a message using one of the following emojis : :one: :two: :three: :four: :five: :six: :seven: :eight: :nine: :hash: :asterisk: 
- Open Element Desktop or Web version
- Should see something like this : 
![Result - emoji picker + message result](https://i.imgur.com/yIFBiXj.png)

Describe how what happens differs from what you expected.
=> We should get the correct emojis displays as in Element Android version.

### Version information

- **Web version**
Version de riot-web : 1.6.8
version de olm : 3.1.3
Browser : Firefox 78 (no issue on Chrome..!), on Windows & Ubuntu, private server (not tester on official server)
- **Desktop version**
Version de Element : 1.7.1
version de olm : 3.1.3
**OS**: Windows & Ubuntu

#### Notes
Not sure if its an upstream issue, so just reporting here for now...

**Comment by t3chguy** [comment]
Fixed on develop.

![image](https://user-images.githubusercontent.com/2403652/88388784-1a26ad00-cdad-11ea-8672-7dcfd1659dd5.png)
