### ISSUE TITLE
All new messages are decryptable by untrusted sessions

### ISSUE THREAD

**Issue by dnut** [vector-im/riot-web#14766]
### Reproduce

1. Login to new device.
2. Click either "later" or "this wasn't me" on the verification request in a pre-existing verified session.
3. Note that the new session is listed as "untrusted."
4. Have encrypted conversations with other people.

### Expected

No messages can be decrypted by the untrusted session.

### Actual

All new messages can be read by the untrusted session. It doesn't matter who sends them, whether its me from any device, or anyone messaging me. This is insane and totally defeats the purpose of end-to-end encryption!

Logs being sent: yes

### Discussion

I can stop the hemorrhage if I go into my list of sessions and delete any untrusted ones. But it is absolutely unacceptable to trust by default despite saying it is untrusted. The public key of the new session should never be used to encrypt messages until it is verified.

### Version information

Arch linux
Element desktop: 1.7.1
olm: 3.1.3

**Comment by dbkr** [comment]
This is the intended behaviour, but you can make it behave as you describe by toggling the, "Never send encrypted messages to unverified sessions from this session" switch in settings / security & privacy on each of your logins.

**Comment by dnut** [comment]
> This is the intended behaviour,

That's a big problem. It is very deceptive to your users. You should strongly consider changing the default.
