### ISSUE TITLE
Unnecessary spacing in the "Files" bar

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14762]
### Description

There's some unnecessary spacing in "Files" as is seen in the screenshot. Not in all cases/rooms though.

![image12](https://user-images.githubusercontent.com/43568459/88455427-80770280-ce75-11ea-8516-e763bb538d3d.png)

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by t3chguy** [comment]
That spacing is the space where it is trying to preview the mkv file but Electron (chromium browser) is presumably failing to support that

**Comment by odiferousmint** [comment]
Oh I see, thank you. I suppose I'll close it then. :)
