### ISSUE TITLE
cannot install element (riot) for windows, getting "Your Element is misconfigured"

### ISSUE THREAD

**Issue by f1-outsourcing** [vector-im/riot-web#14773]
I did not even configure anything.

![element-error](https://user-images.githubusercontent.com/13450219/88530953-6ae31380-d002-11ea-8443-52af653d43ea.png)

**Comment by t3chguy** [comment]
Do you have a firewall/internet connection which is blocking matrix.org?

**Comment by f1-outsourcing** [comment]
> 
> 
> Do you have a firewall/internet connection which is blocking matrix.org?

No, and even so, then I would not be able to select an own server not? I have a vm for testing software which runs windows7 still. I hope you are not testing on that?

**Comment by t3chguy** [comment]
Part of startup is verifying the config is valid, which means verifying the matrix server specified in the config.json is reachable; https://github.com/vector-im/riot-web/issues/11655#issuecomment-646065432

We don't prevent function based on the environment.

**Comment by f1-outsourcing** [comment]
If I try these urls from firefox, from the same environment

https://matrix.org/.well-known/matrix/client
this has json (as expected, I assume)

https://vector.im/_matrix/identity/api/v1
this has an empty request

**Comment by t3chguy** [comment]
You can open the devtools using Ctrl+Shift+I and see what the exact error/failing request is.

**Comment by f1-outsourcing** [comment]
some stuff

​ Uncaught (in promise) TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('vector://vector') is not supported.
    at Module.<anonymous> (​)
    at a (​)
    at ​
    at ​
​ Initialised rageshake.

vendors~init.js:2 CORS request rejected: https://matrix.org/.well-known/matrix/client
e.<computed> @ vendors~init.js:2

matrix.org/.well-known/matrix/client:1 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID

I see you are using this cloudflare, that is always fucking things up.

**Comment by t3chguy** [comment]
> matrix.org/.well-known/matrix/client:1 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID

Do you have a proxy or something with TLS termination?

**Comment by t3chguy** [comment]
When you open matrix.org in your browser inside that VM can you share what certificate it thinks it is?

**Comment by f1-outsourcing** [comment]
> 
> 
> > matrix.org/.well-known/matrix/client:1 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
> 
> Do you have a proxy or something with TLS termination?

No

**Comment by t3chguy** [comment]
> When you open matrix.org in your browser inside that VM can you share what certificate it thinks it is?

**Comment by f1-outsourcing** [comment]
I will check, but now I have noticed this is not really a native application, and is based on chrome, which I do not use, it is probably related to that.
