### ISSUE TITLE
Win10: Element does not start anymore after being asked to update

### ISSUE THREAD

**Issue by fladd** [vector-im/riot-web#14789]
### Description

I was asked to update Element, did so, and now Element Desktop does not start anymore.

### Steps to reproduce

- Attempt to start Elment

Describe how what happens differs from what you expected.

I expect Element to start.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Windows 10
- **Version**: 1.x.y 
Cannot check, because it does not start. It should be the current one, as of creating this issue.

**Comment by q5sys** [comment]
I can confirm this issue, Element worked great yesterday with no problems.  Powered on my machine today (no updates or any other software changes) and Element now wont start.

**Comment by dbkr** [comment]
Ah, there are some workarounds we applied for the 'Riot' -> 'Element (Riot)' rename but didn't apply for the 'Element (Riot)' -> Element rename. What I observe is that 1. the app doesn't auto-restart after updating and 2. you end up with 2 shortcuts, one called 'Element' which works and one called 'Element (Riot)' which doesn't. We can add a workaround to prune the 'Element (Riot)' shortcut in the next version.

**Comment by jlgarnier** [comment]
Hi all,

Reopening this issue as the latest release doesn't want to launch. All updates have run smoothly so far but the application requested the new update to be installed this afternoon (v1.11.94?) and now the app silently crashes when opened. I don't have any other change applied today.
Environment: Win 11 22H2 build 22621.4317

Thanks in advance for any help!

**Comment by t3chguy** [comment]
@jlgarnier what makes you think its related to a 4.5 year old issue?

https://github.com/element-hq/element-desktop/issues/2161 is the live issue.
