### ISSUE TITLE
room list: "unread" dot desync'ed with bold text

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#14780]
Some times, a room in the room list has a dot indicating it's unread, but the room name is not bold (see "Element Android" in the screenshot).  And sometimes, a room is bold, but has no dot (see "#synapse-dev" in the screenshot).  I've only observed the second case with whatever room is currently being viewed.
![image](https://user-images.githubusercontent.com/1012976/88595098-5fa6dc80-d030-11ea-9399-17c61c86a35f.png)

(element nightly, 2020-07-27)

**Comment by turt2live** [comment]
Fixed on develop.
