### ISSUE TITLE
Completely black program window  on Windows 7 SP1 64bit; solution is updating "d3dcompiler_47.dll" and possibly .NET

### ISSUE THREAD

**Issue by NintendoManiac64** [vector-im/riot-web#14783]
Simply put, the desktop client displays an entirely black program window on Windows 7 SP1 64bit; Riot v1.3.x seemed to have been the last version without this problem.

I have replicated this problem on 4 different Windows 7 SP1 64bit PCs, and have successfully tested the solution mentioned in the title on two of the PCs as of this time.

The solution seems to simply be to update the "d3dcompiler_47.dll" file to a newer version (such as the one found in Chrome v84), and possibly also to update the .NET framework (possibly to at least 4.7.1, but I updated straight from 4.6.x to 4.8 so I'm uncertain on this).

On one PC I tried only updating .NET by itself from v4.7.2 to v4.8 but that alone did not fix the issue - it was only until I additionally updated the DLL that the problem went away.

On the other PC I tested the solution on, I initially only updated the DLL but that by itself also did not work - it wasn't until I also updated .NET from v4.6.x to v4.8 that the problem went away.

This issue has been reported with other electron v6 apps as well:
https://github.com/electron/electron/issues/24434
https://github.com/electron/electron/issues/19569
https://stackoverflow.com/questions/53400985/black-window-when-running-postman-on-windows-7

I've been aware of this issue for around a year now (back when v1.4 initially released), but I just assumed it was a case of Riot no longer supporting Windows 7 since that OS was approaching EOL so I just stuck with v1.3.6 and disabled the auto-updater by renaming "Update.exe" to "Update.exe_BAK".

But a couple months ago I discovered another completely unrelated electron app with the exact same "black program window" issue.  And now that today I just discovered the Electron.io rebranding and that "riot.im/app" will be going away soon, I got paranoid that my trusty old v1.3.6 of desktop client Riot would no longer work at some point, so I searched for a proper solution now that I know it's an issue with electron itself...which lead me to the updated DLL + .NET fix.

**Comment by t3chguy** [comment]
> This issue has been reported with other electron v6 apps as well:

We're an electron v9 app in modern versions.

> Electron.io rebranding and that "riot.im/app" will be going away soon, I got paranoid that my trusty old v1.3.6 of desktop client Riot would no longer work at some point

Your trusty 1.3.6 will work indefinitely (until the matrix server becomes incompatible) because it has a local copy of the app.

riot.im/app might be going away but it is replaced by app.element.io.

**Comment by turt2live** [comment]
Sorry, Windows 7 SP1 is not one of our supported platforms currently.

**Comment by NintendoManiac64** [comment]
> 
> 
> Sorry, Windows 7 SP1 is not one of our supported platforms currently.

Was it a supported platform back when the problem first cropped up around 10 months ago when Riot v1.4 released?

**Comment by t3chguy** [comment]
Yes given that Windows 7 EOL was January 14th 2020

**Comment by NintendoManiac64** [comment]
> 
> 
> Yes given that Windows 7 EOL was January 14th 2020

So if I had actually reported the issue back then, it could have actually gotten fixed. But because I'm only just reporting it now, it's a "doesn't matter, won't fix" despite it being a problem that did in fact exist back when the OS was supported and a solution already being known?

The worst part is that the DLL fix may not have even worked back then - it may only be working now because the version that Chrome 84 uses is considerably newer (for all we know the problem could have persisted with the DLL used by whatever version of Chrome was current in September 2019)

**Comment by t3chguy** [comment]
> So if I had actually reported the issue back then, it could have actually gotten fixed.

Unlikely as it sounds like an upstream (electron) issue.

> solution already being known?

We don't provide those DLLs, either electron-builder or electron provide them.
