### ISSUE TITLE
rejected invites leave an annoying red badge

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#14798]
* receive invite
* reject
* "Historical" section of room list now has a red badge against it
* Also, the room doesn't disappear from the "Invites" section of the room list immediately, despite also appearing in the "Historical" section.

**Comment by richvdh** [comment]
there's also a red badge in the breadcrumbs. there are two rejected invites here:

![image](https://user-images.githubusercontent.com/1389908/88689767-cd1b4180-d0f2-11ea-8b55-cb6dce6b1a7e.png)

**Comment by turt2live** [comment]
> "Historical" section of room list now has a red badge against it

This is where things are going wrong - the rest is entirely side effects. Likely fallout from the performance work.

**Comment by turt2live** [comment]
> Also, the room doesn't disappear from the "Invites" section of the room list immediately, despite also appearing in the "Historical" section.

Turns out this is also a bug, isolated from the first :(
