### ISSUE TITLE
Noisy notifications for every message.

### ISSUE THREAD

**Issue by kruug** [vector-im/riot-web#14795]
### Description

I have noisy notifications turned on for mentions and room alerts.  (See image)  I am still getting notifications for every single message that is sent to a room.  From what I'm reading in the settings, I should only be getting notifications for mentions.

![](https://i.imgur.com/vz1qB3C.png)

### Steps to reproduce

Messages that don't include my nick or @room generates a notification even though nothing in Notification Settings is set for that.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? Desktop
- **OS**: Windows 10
- **Version**: 1.7.2

**Comment by t3chguy** [comment]
`On` means notify

You have Messages in group chats set to On

Noisy means notify with sound

Notifications are getting cleaned up as part of https://github.com/vector-im/riot-web/issues/13959

**Comment by kruug** [comment]
Oh, rooms are considered group chats?  I'm new to Matrix, but coming from Slack and Discord, those wouldn't be the same thing.

**Comment by kruug** [comment]
For instance, if I have a private chat between me and 2 or more other people, I would want notifications.  If I'm in a public room, however, I might not care about every single message.

**Comment by t3chguy** [comment]
Well everything is a Room. DMs are rooms too.

The distinction here is DM vs non-DM.

For what you want you should use per-room settings; 

![image](https://user-images.githubusercontent.com/2403652/88682832-0cde2b00-d0eb-11ea-804c-8c2fd9909d57.png)

**Comment by t3chguy** [comment]
And the DM distinction is baked into the Matrix spec; https://matrix.org/docs/spec/client_server/r0.6.1#m-rule-room-one-to-one

**Comment by kruug** [comment]
Thank you for the image and the docs link.

I found a bug with that notification bell setting.  Clicking on a different option in the Windows desktop app doesn't change it until you click another option/click away.  Put in a new issue for that one?

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/14790

**Comment by lachesis** [comment]
For anyone confused like me, this option doesn't show up if your window is too narrow:

![2020-11-26-095250_172x759_scrot](https://user-images.githubusercontent.com/347481/100381156-317cdd80-2fcd-11eb-947e-538d6d9b47f0.png)

If you allow your Element desktop window to full screen, then the bell icon becomes visible.

**Comment by t3chguy** [comment]
You don't have to resize your window, there is a resize handle on that panel you can grab to resize it.
