### ISSUE TITLE
notifications drop-down in room list behaves erratically

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#14790]
it seems like clicking entries in the dropdown might do anything except what you expect.

![Peek 2020-07-28 13-46](https://user-images.githubusercontent.com/1389908/88667220-fa5af600-d0d8-11ea-93da-39f439bea058.gif)

**Comment by t3chguy** [comment]
Its not clear when you are clicking, are you complaining about having to wait for Synapse to echo the change down Sync?

**Comment by t3chguy** [comment]
oh nvm wtf

**Comment by t3chguy** [comment]
I think this is the perf stuff gone wrong

**Comment by turt2live** [comment]
Can you be more specific about "gone wrong"? It still looks like local echo to me.

**Comment by t3chguy** [comment]
It is related to local echo, the Room Tile doesn't update once that echo comes down, it doesn't react to push rule updates

**Comment by t3chguy** [comment]
(so effectively it lags a click behind)

**Comment by t3chguy** [comment]
Best solution to this (without causing a performance regression) is https://github.com/vector-im/riot-web/issues/14280

**Comment by turt2live** [comment]
Considering this a duplicate of https://github.com/vector-im/riot-web/issues/14280 for tracking purposes.
