### ISSUE TITLE
Channel tooltip name no longer appears, compact channel list, desktop

### ISSUE THREAD

**Issue by mcint** [vector-im/riot-web#14806]
### Description

The compact channel list no longer displays the channel name in a tooltip on mouseover. The community list and profile photo in room provide a community- and user-name respectively.

### Steps to reproduce

- Open Riot Desktop, join a server, open channel(s)
- Mouseover channel profile photo, no name appears

Community, with name tooltip:
<img width="139" alt="Screen Shot 2020-07-28 at 7 31 46 PM" src="https://user-images.githubusercontent.com/601708/88750091-a3b9e000-d109-11ea-8cc7-352e4f87caca.png">
Channel (tooltip not present, though expected):
<img width="182" alt="Screen Shot 2020-07-28 at 7 31 28 PM" src="https://user-images.githubusercontent.com/601708/88750093-a4527680-d109-11ea-9704-e70699333483.png">
Profile pic, in-chat, with tooltip:
<img width="280" alt="Screen Shot 2020-07-28 at 7 26 01 PM" src="https://user-images.githubusercontent.com/601708/88750094-a4527680-d109-11ea-9e0d-09b0960ffa71.png">

(arrows added to stand in for mouse pointer, since screenshot excluded it)

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: desktop, macOS

For the web app:

- **OS**: macOS

For the desktop app:

- **OS**: macOS
- **Version**: 1.7.1

Channel tooltip was present in 1.6.8.

**Comment by turt2live** [comment]
Try 1.7.2 - it was fixed shortly after 1.7.1 was released.
