### ISSUE TITLE
Add Syphon to matrix.org/clients

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/riot-web#14800]
I've sent a [message](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$fROtPfoZulg0rz9MYyRUsL816be9xJ3JicUoM-LNOsM) to Element Web/Desktop but got no reply so I thought I'd open an issue:

I found a cool new Matrix client which is looking very promising and glossy, although is still in early Alpha. It's called [Syphon](https://syphon.org). I was thinking it could be added to matrix.org/clients.

**Comment by t3chguy** [comment]
That is entirely unrelated to this project? Try https://github.com/matrix-org/matrix.org/

**Comment by TR-SLimey** [comment]
@t3chguy I saw people reporting website-related issues to the Riot Web repo hence why I posted this here, but thanks for the tip, will post there.

**Comment by t3chguy** [comment]
Issues with the element.io website maybe, otherwise they'd get closed just like this one :)

**Comment by TR-SLimey** [comment]
That makes sense. Thanks!
