### ISSUE TITLE
Call Invitation showing up in 'advanced notifications' not in the menu

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#14817]
### Description

Call Invitation notifications are mixed up in notifications menu.

### Steps to reproduce

Do something (?) to break it. I logged in on this account on launch day and have updated to the newest release when it came out.  I also use element android.

This shows up correctly on element android.

If i look in the notifications configuration menu on eleweb, I see the following screenshot:

![notification-targets](https://user-images.githubusercontent.com/1917473/88824435-3fa52380-d1be-11ea-9c7b-7a22ff9897ec.png)

Describe how what happens differs from what you expected.

The Call invitation should be in the main set of radio buttons, not separated.

I have this in my account data for push rules, if that is where this data is stored:
```
{
  "type": "m.push_rules",
  "content": {
    "global": {
      "underride": [
        {
          "conditions": [
            {
              "kind": "event_match",
              "key": "type",
              "pattern": "m.call.invite"
            }
          ],
          "actions": [
            "dont_notify",
            {
              "set_tweak": "highlight",
              "value": false
            }
          ],
          "rule_id": ".m.rule.call",
          "default": true,
          "enabled": true
        },
```

### Version information

- **Platform**: web (in-browser) 
For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: app.element.io

**Comment by michaelkaye** [comment]
Should say that I don't believe i've ever customized these rules beyond the basic buttons in element web and element android

**Comment by t3chguy** [comment]
So Element android seems to insert `dont_notify` which probably confuses web, clicking on one of the radio options 

![image](https://user-images.githubusercontent.com/2403652/88826614-da066680-d1c0-11ea-99ad-9e100b690b71.png)

should resolve your issue.

https://github.com/vector-im/riot-web/issues/13959 will make the UI more resilient to `dont_notify` which itself is getting ripped out of the spec in due time.
