### ISSUE TITLE
[Feature Request] Jump to Mention

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#14812]
Often when I get mentioned in a busy channel I get the notification number beside it, but I can't for the life of me find where I was mentioned. Can we please have a feature where we can jump to where we were mentioned, or see a list of those somewhere?

**Comment by t3chguy** [comment]
Notifications panel top right.

**Comment by BloodyIron** [comment]
Egads somehow I missed that feature being added! Sorry @t3chguy :(

**Comment by t3chguy** [comment]
That feature predates me, so its been there for 2/3 years at least if I had to guess

**Comment by BloodyIron** [comment]
OOF well go me then D:
