### ISSUE TITLE
unfindable notifications

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-web#14827]
![image](https://user-images.githubusercontent.com/24435423/88932695-b73a8780-d27e-11ea-90e0-0508ee19c7f7.png)

### Description

As in screenshot above: I have a notification (mention) in a room, but other than the [1] in the tile and the red logo in the systray this notification is completely invisible and I have to randomly scroll around until I find it. Which obviously means I first scroll all the way in the wrong direction.

### Steps to reproduce
Get a notification in any room that's not currently visible, and you won't be able to see it.

Describe how what happens differs from what you expected.

I expect mentions to be easily accessible at all times.

### Version information

I currently use element-desktop-nightly, but I assume this goes for all element-web versions.

- **OS**: Kubuntu 20.04
- **Version**: Element Nightly version: 2020073001

The obvious solution to this problem is fixing #14085 though I suppose another solution would be possible as well.

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/riot-web/issues/14057
