### ISSUE TITLE
SoftLogout schedules all message keys for backup

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#14829]
The SoftLogout screen calls `flagAllGroupSessionsForBackup` which re-schedules all keys to be backed up. It uses the result to decide whether or not to show the user a warning, but it's just scheduled all keys to be backed up so looks like the warning will always show?

**Comment by turt2live** [comment]
I think this was it trying to determine whether or not the key backup was enabled, which would be identified by the key backup having pending work to do. Nowadays I'm pretty sure we have more sane methods to do this.
