### ISSUE TITLE
Images sometimes get sent as files

### ISSUE THREAD

**Issue by f0x52** [vector-im/riot-web#14831]
Somewhere around the rename to Element, I started having random issues with image uploads, where they get sent as `m.file` (and no thumbnail) instead.
Reuploading the exact same image again usually sends a proper `m.image`, so this is probably some kind of race condition

**Comment by t3chguy** [comment]
Please fill in the issue template. Versions are important with such issues.

**Comment by turt2live** [comment]
Likely duplicate of https://github.com/vector-im/riot-web/issues/7069
