### ISSUE TITLE
Media capture fails if specific device selected isn't available

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#14837]
I think our audio/video device selection fails entirely if you select a specific media device and then that device isn't availaible ('Couldn't start capturing media' error).

**Comment by absorber** [comment]
Yep, that was me.

What I think happened was that I had my Chromium session open during the time that I changed my audio interface (using `qjackctl`) - In fact I remember the audio interface unexpectedly disappearing (there was a minor oopsie with my DAC losing power suddenly)

In any case, I vaguely remember having to `kill -9` either my `autojack` or `jackdbus`, and then restart JACK for my builtin audio interface.
This could have triggered the events which made Riot.im / Element.io unable to recognize the current working interface.

In any case, completely shutting down my Chromium instance and restarting it again fixed my issue.

**Comment by dbkr** [comment]
Looks like this isn't actually the problem - for me it falls back to a different device if the specified one isn't available. I'm guessing chromium got confused and decided there were no audio devices available.
