### ISSUE TITLE
Enable desktop notifications prompt should be greyed out or hidden on browsers that don't support it

### ISSUE THREAD

**Issue by oddvar** [vector-im/riot-web#1501]
The enable notifs link doesn't do anything. I can close the whole bar though. This is on Chrome on iOS.

**Comment by t3chguy** [comment]
Should be fixed by 6aba9f8edaa749247917002fc7a7b83b6e859731

**Comment by t3chguy** [comment]
Tested on Chrome on iOS, no bar appeared so I believe this was fixed by the above mentioned commit
