### ISSUE TITLE
URL preview fail for sky.com

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1511]
A only-visible-to-matthew example:

https://vector.im/develop/#/room/!lFdHwFlnCHQWDBxEjs:matrix.org/$1463153911370065oGstk:matrix.org

**Comment by Kegsay** [comment]
Test closing/opening

**Comment by t3chguy** [comment]
Seems like this is no longer the case?
![capture1](https://cloud.githubusercontent.com/assets/2403652/26103206/49f79652-3a30-11e7-8912-1308c0188e3f.PNG)

**Comment by t3chguy** [comment]
closing unless someone can reproduce

**Comment by ara4n** [comment]
this was a sensitive url failing in the depths of sky.com, which has probably moved on now anyway
