### ISSUE TITLE
Release notes don't allow to identify their differences

### ISSUE THREAD

**Issue by almereyda** [vector-im/riot-web#1559]
When looking at the https://github.com/vector-im/vector-web/releases it is indistinguishable how the releases differ from each other. I am currently hunting down

```
vector-web@0.6.1
npm info ok 
 ---> 82464a46714a
```

for https://lab.allmende.io/allmende/docker-vector/blob/master/Dockerfile#L73 / https://hub.docker.com/r/allmende/vector/ which still reports **Version 0.5.2** on https://vector.allmende.io/#/settings, likewise the https://vector.im/beta/#/settings client, but without the **v0.6.1** line below.

But maybe this is another issue and I can trust the client to be up to date now due to the build log.

**Comment by ara4n** [comment]
Weird. unsure why the contents of https://github.com/vector-im/vector-web/blob/master/CHANGELOG.md isn't showing up on the GH releases page.  @richvdh, any idea how that works?

**Comment by richvdh** [comment]
Yeah, you have to explicitly create a github release via the github UI (or API). Currently we just let github build the releases list from the tags.

We could make creating the github release a part of our release script, but obviously it needs a different set of credentials to the git part, so it wouldn't be trivial.

**Comment by dbkr** [comment]
We do now put a changelog on our github releases (and explicitly do github releases) so I'm closing this. I've created https://github.com/vector-im/riot-web/issues/6613 to track the shortcomings of these changelogs.
