### ISSUE TITLE
Validation token email notif for vector.im are broken on ios

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1578]
![broken email notif](https://cloud.githubusercontent.com/assets/8582858/15738910/de91764c-28ad-11e6-899c-c0da830faa62.png)

**Comment by ara4n** [comment]
I think I fixed this by removing the 'or copy this link' stuff. need to check.

**Comment by yannicka** [comment]
I'm not on iOS, but the full link has been removed, so the problem must have disappeared.

![image](https://user-images.githubusercontent.com/22885898/87853101-a184a400-c907-11ea-86e5-41959a17b6c3.png)

Can someone confirm?

**Comment by t3chguy** [comment]
Assuming fixed, either way its a HS/IS issue not a Riot/Element one.
