### ISSUE TITLE
Badge overlaps the room name in FF

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1581]
version 46.0.1

![capture](https://cloud.githubusercontent.com/assets/8582858/15740719/6ce1851a-28b6-11e6-98b7-f0fde6d2185d.PNG)

**Comment by t3chguy** [comment]
We're up to Firefox 60 now and it seems to no longer be an issue, I think it was actually fixed in the app though with a `text-overflow: ellipsis` 
![image](https://user-images.githubusercontent.com/2403652/41820704-caede26c-77cd-11e8-9ab0-e1fb6ac4ad92.png)
