### ISSUE TITLE
"I already have an account" should not be shown on the 'check your email page'

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1599]
![image](https://cloud.githubusercontent.com/assets/1294269/15802486/f38b6864-2aab-11e6-8d66-55c9c0caac06.png)

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it.

![image](https://user-images.githubusercontent.com/22885898/87852931-70f03a80-c906-11ea-923e-55dee93b2fed.png)

Or it's on another screen?
