### ISSUE TITLE
Chrome Incognito: enable desktop notifications seems to be broken?

### ISSUE THREAD

**Issue by rryan** [vector-im/riot-web#1634]
Was trying to repro #1632 with a test account. (@rryan-test:matrix.org).

Chrome Version 51.0.2704.84 (64-bit) Incognito Window

Clicking "Enable them now" on the header or going into settings and trying to check "Enable desktop notifications" does nothing.

No errors show up on the Developer Tools console.

**Comment by DerUser** [comment]
Seems to be brocken with "normal" Chrome mode too, not only Incognito Windows

Chrome Version 51.0.2704.106 (64-bit) MAC OS X 10.11

**Comment by t3chguy** [comment]
matrix-org/matrix-react-sdk/pull/827 means that it'll pop up with a somewhat descriptive error
could you both test again @DerUser and @rryan

**Comment by turt2live** [comment]
Just tested this. It's been fixed by the PR mentioned above.
