### ISSUE TITLE
[Legal] T&C modal click-thru dialog box

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1644]
There should be some notification for example through a pop-up on the website & app notifying the guest user that they are agreeing to the Terms of Use

**Comment by ara4n** [comment]
This should be a modal when you first go to https://vector.im/app imo.

**Comment by ara4n** [comment]
The 'cancel' button should probably take them back to the https://vector.im website.

**Comment by AmandineLP** [comment]
We need:
- A direct access to all 3 docs from the app, I would assume the settings
- A warning displayed when using the app as a guest, similar to the cookies one on websites ("By using the Services as a guest, you confirm that you have read and accept the terms of use  <link> and Privacy policy <link> and you agree to comply with them"). Possibly another banner at the top to make it visible enough for people to click through it without disrupting the onboarding experience
- A mandatory check-box ("By registering to the Services, you confirm that you have read and accept the terms of use  <link> and Privacy policy <link> and you agree to comply with them") at registration

**Comment by ara4n** [comment]
@AmandineLP DONE!
