### ISSUE TITLE
Document integrations_*_url config options when they land

### ISSUE THREAD

**Issue by RickCogley** [vector-im/riot-web#1698]
Hello - a couple questions about the config file: 

```
{
    "default_hs_url": "https://matrix.org",
    "default_is_url": "https://vector.im",
    "brand": "Vector",
    "integrations_ui_url": "http://localhost:8081/",
    "integrations_rest_url": "http://localhost:5050"
}
```
- If I set up my own vector, does it act as an identity server, to link an email address to a matrix id? 
- Presumably, if I have my home server on https://matrix.mydomain.com and vector on https://chat.mydomain.com these go in the default_hs_url and default_is_url, correct? 
- What does the brand setting control? 
- Do the integrations settings need to be localhost, and, what does that imply - that all the bots and whatnot need to be served from this server? 
- Can these integrations settings be some other ports? I ask because, since this is pretty static, I want to run it from a web container on my usual static hosting service, and, you have to get them to supply custom ports.

Thanks for your help. 
Kind regards,
Rick

**Comment by vith** [comment]
I found a description of the `integrations_*_url` fields in a since-removed piece of code: https://github.com/matrix-org/matrix-react-sdk/blob/b54376aa2acda9451d684a1565772503beaff631/src/SdkConfig.js#L17-L22

```js
var DEFAULTS = {
    // URL to a page we show in an iframe to configure integrations
    integrations_ui_url: "https://scalar.vector.im/",
    // Base URL to the REST interface of the integrations server
    integrations_rest_url: "https://scalar.vector.im/api",
};
```

Further clarification would be helpful for server operators who come across these in [config.json](https://github.com/vector-im/vector-web/blob/master/config.json).

**Comment by ara4n** [comment]
Integration management stuff hasn't landed at all yet - it's mostly on branches. We'll be sure to document it when it does (in the next few weeks :)

**Comment by mheppner** [comment]
Are there any updates on this? It's been a bit longer than a few weeks 😛

Great project, I'm excited to see where it progresses!

**Comment by seisatsu** [comment]
I'm also interested in what's going on with this, I get the integrations server error but can't easily find related documentation.

**Comment by almereyda** [comment]
If you provided a PR which resolves this issue, I guess it would be highly appreciated by the maintainers.

**Comment by turt2live** [comment]
Some additional documentation was merged to the README. Is it now documented adequately?

**Comment by seisatsu** [comment]
Still not even remotely clear on what the integrations server actually is, or what it does, or if it even exists yet.
