### ISSUE TITLE
"Mark all read" doesn't work when you upload a picture taller than the window

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#1704]
1. Upload a picture tall enough to overflow the window
2. "Unread messages" banner appears
3. click "mark all read"
4. Nothing

**Comment by turt2live** [comment]
With the new bar, I can't reproduce this. However, it does seem awkward that the bar even shows up for this.

**Comment by aaronraimist** [comment]
This button doesn't exist anymore (#8666)
