### ISSUE TITLE
Text field sometimes collapses when writing a long message

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#1724]
Might be due to an extension called grammerly (the green dot on the screenshot).
Seen with chrome on macbook air. 
(reported by TheguyfromTV)

![image](https://cloud.githubusercontent.com/assets/8582858/16650554/1755889a-443f-11e6-98ce-04d77c9ace41.png)

**Comment by yannicka** [comment]
Do you still have the problem now?
