### ISSUE TITLE
Horizontal scrollbar if room topic is too long

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#1725]
Vector develop as of July 7, 1:36 US Eastern Time. Doesn't seem to have a vector-web version in settings?

matrix-react-sdk version: e6ff1f883676b0fce8c2a91fce17e993ecdaa841
vector-web version: 

![screen shot 2016-07-07 at 1 35 53 pm](https://cloud.githubusercontent.com/assets/1923178/16662891/c229ff14-4447-11e6-9c31-bb445b586af9.png)

**Comment by richvdh** [comment]
This only affects unwrapppable topics. Otherwise you get #1836 instead.

**Comment by turt2live** [comment]
I can't reproduce this, and assume it is fixed
