### ISSUE TITLE
Back/Forward when offline shows incorrect room state.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#1726]
Compare: 

![screenshot from 2016-07-07 23-55-12](https://cloud.githubusercontent.com/assets/238916/16664608/6b0c1ae4-449e-11e6-8b45-de4f730c18ec.png)

(offline, when navigating with history forward/back)

![screenshot from 2016-07-07 23-55-24](https://cloud.githubusercontent.com/assets/238916/16664614/70769ae0-449e-11e6-9a61-4f00c36c12d7.png)

(offline, but clicking through room list)

**Comment by ara4n** [comment]
@aviraldg: i don't understand this. How were you 'navigating with history forward/back' in the first example?  How did you join the room if not via the room list?

**Comment by yannicka** [comment]
Is this problem still relevant?

**Comment by t3chguy** [comment]
This should now be fixed with the local room alias cache we hold
