### ISSUE TITLE
Message Context Menu to be restyled

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1744]
To restyle the RHS message context menu (grey)
- Design: small tweaks and assets need to be marked ready

**Comment by AmandineLP** [comment]
Note that the "Permalink" text should be displayed as a link not a text like on the design

**Comment by bradlegge** [comment]
Screen design:

https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=5746423e3135b1130ff70e56

**Comment by ara4n** [comment]
design is signed off and good to go, with the proviso that we should move the URL Preview hide/unhide functionality to the context menu (c.f. #1751).  Happy to skip an icon for that for now.

**Comment by t3chguy** [comment]
/me would love to see said design :(

**Comment by ara4n** [comment]
<img width="205" alt="screen shot 2017-10-24 at 22 56 16" src="https://user-images.githubusercontent.com/1294269/31970035-a53bbdce-b90e-11e7-9219-7d272a371121.png">

i.e. to match the LeftPanel context menus.

**Comment by t3chguy** [comment]
thanks!

**Comment by lampholder** [comment]
Whatever of this wasn't implemented is superceded by the new redesign
