### ISSUE TITLE
Notification alert: implement the notification style

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1749]
Notification alert: implement the notification style as per design 

**Dependency**: Vector team to provide feedback and possibly new functionality in matrix.js?
- Design: small tweaks and assets marked ready

**Comment by AmandineLP** [comment]
@ara4n => Vector team to provide feedback and possibly new functionality in matrix.js?

**Comment by ara4n** [comment]
We just need the visual badge here.  Wiring it up can be on our side.

**Comment by bradlegge** [comment]
Screen URL:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=57464236aa4f5c031fffa260

**Comment by ara4n** [comment]
design signed off. implementation is intimately entangled with #1750.

**Comment by lampholder** [comment]
I think this is done.
