### ISSUE TITLE
Create room 1 and 2: Room creation flow to be improved

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1756]
Create room 1 and 2: Room creation flow to be improved

~~Dependency/question: functionality does not exist - Vector or ribot team to create?~~

**original requirements from Amandine**

We've been getting feedback from the users which confirmed our experience that the room creation flow is not great.

Today we get into an empty room and the focus in on the invite field. Which makes people invite others in a name-less room. And there is no mean to cancel the creation except by leaving the room. 

We’re thinking that a 2 stage creation flow would be (was) better there are steps through which people should be going before inviting: set a room name and potentially a topic. 
An idea was to open a an empty room _but_ with a modal popup (or possibly the room settings pane open? But they’re scary today) for the user to fill in the room name and possibly a topic, and visibility/privacy settings. Then once pressing OK the room is created and focus is on invite field. 

What do you think? Any other thoughts to improve the experience?

**Comment by AmandineLP** [comment]
Please define "functionality".
This is updating the "Create room" flow, redirecting to a reduced version of the current room settings when clicking on "Create a new room" button in the bottom left corner.
It's the same screen as the room settings, albeit with a better design and only part of the settings.

**Comment by ara4n** [comment]
To clarify: we do have a create room component already, but it looks nothing like Trevor's new design.  A new one will need to be created, sharing much of the functionality with the current Room Settings page.  It would be great if this could be done on the Ribot side (although this one is pretty much all coding rather than design).

I'd prioritise the more fiddly cosmetics over this one and do it if we have time, as this can always be done on the Vector side, whereas the HTML+CSS wrangling is at more of a premium.

**Comment by bradlegge** [comment]
Screen URL:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=576975c5b5f095ce2c9019eb

**Comment by ara4n** [comment]
Signed off as a style sheet - not to be taken as literal form contents though

...with the exception that we need to work out where to put the save button in the event of the form being taller than one page.

**Comment by ara4n** [comment]
...now solved in https://zpl.io/1hf7ar. signed off!

**Comment by ara4n** [comment]
We're going for a short-term fix in #2178 for now...

**Comment by t3chguy** [comment]
Room Creation flow is vastly improved and further improvements scoped to Nad's design
