### ISSUE TITLE
Chat inline error: Implement styling for private/system error messages

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1759]
Chat inline error: Implement styling for private/system error messages
- Design: exists - going back to how it was before with better styling. Tweaks and assets marked as ready for dev

**Comment by bradlegge** [comment]
Screen URL:

https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=577a42028bb68509172ccb97

**Comment by antikewl** [comment]
Do we have a Big List of Errors somewhere? By "we" I probably mean Matthew. :)

https://zpl.io/Z1XGRuz
https://zpl.io/Z1XGRuz

**Comment by wmwragg** [comment]
@ara4n Would you be able to flesh out the scope of this ticket a little more, as I'm not 100% on what this ticket is wanting to be implemented esp. with respect to which errors you want propagated to the new error popup

**Comment by ara4n** [comment]
for now, the only errors i'd expect to be propagated would be connectivity & resending errors. in future we'd also put scalar (integration) errors in there, but this doesn't exist yet (although it's close).  @kegsay: can you think of any i'm missing?

It's worth noting that i'd expect the implementation to change radically here when we implement https://github.com/vector-im/vector-web/issues/1761 and it'd probably make sense to implement both at the same time. Currently @aviraldg is poised to implement the autocomplete and new statusbar stuff once we have designs for it.

**Comment by wmwragg** [comment]
Right you are. I'll hold off on this then and wait until #1761 has been implemented

**Comment by Kegsay** [comment]
> can you think of any i'm missing?
- Remote network (e.g. IRC) connection errors
- Remote network (e.g. IRC) protocol level errors (e.g. `err_nicktoofast`)
- Command failures which aren't from `!pling` (e.g. setting up webhooks)

**Comment by antikewl** [comment]
Are there any errors that wouldn't be covered by the designs above?

**Comment by ara4n** [comment]
n.b. major overlap with #1991

**Comment by lampholder** [comment]
@ara4n can we kill this? It doesn't seem aligned with our design direction any more
