### ISSUE TITLE
Current room can magically switch from under you when racing with leaving a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1769]
@AmandineLP encountered:
- I created a room
- I searched for a user
- I left the temporary room
- I switched to a different room
- I started to type into it
- Only the first letter was typed there - the rest got entered into HQ (presumably because the room had switched from under me, and I didn't notice as I was looking at the keyboard)

so I suspect that I switched very quickly back to here and the room I had just left wasn't removed from the room list yet, and when it eventually got removed HQ was selected by default.

This sounds like the leave action racing with the explicit room switching, so that when the leave action completed it overrode the room switch to the most recently active room, ignoring the explicit room switch that had already happened.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9270 as it has less questions
