### ISSUE TITLE
End-to-end encryption: show whether encrypted room and room members are trusted or not

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1783]
Need a way to flag users in the room which have unverified devices (and so are causing the overall room to be labelled s containing unverified devices).  Red warning icon of some kind in the members list?

**Comment by itsrachelfish** [comment]
Really looking forward to seeing users show up red or have some unlocked icon next to their name in the user list!! :slightly_smiling_face:

**Comment by uhoreg** [comment]
fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4006 and https://github.com/matrix-org/matrix-react-sdk/pull/3908
