### ISSUE TITLE
End-to-end encryption: device name management

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1787]
In User Settings, need to be able to view and edit the names of your devices that you have associated with your account.

**Comment by richvdh** [comment]
What's remaining to be done here?

**Comment by ara4n** [comment]
from memory, we have official UI cosmetics from Ribot that just hasn't been implemented.

**Comment by Orbixx** [comment]
This appears to be available now. Can this issue be closed?

**Comment by richvdh** [comment]
Sadly, a year on, the situation remains unchanged: the UI still needs work.

**Comment by Orbixx** [comment]
It seems to be working perfectly fine for me. What do you feel is missing?

**Comment by Orbixx** [comment]
Ignore, I forgot about the previous post from Matthew

**Comment by turt2live** [comment]
Closing this in favour of https://github.com/vector-im/riot-web/issues/5012 and other related issues - the UI is there, but is terrible for discoverability.
