### ISSUE TITLE
Allow users to rearrange app layout (tileable UI)

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1790]
We'd like to be able to let users rearrange the layout of the app beyond the current hiding/showing LeftPanel and RightPanel behaviour.  Specifically, the ability to view multiple 'plugins' at the same time in different tiles on the page.  For instance, you could end up with a Video Call view, a Room history view, a shared Whiteboard view, and another Room history view, all in different segments of the page.  This suggests having some kind of tile management UI that appears on hoverover to let you move tiles around, hide them, grow them, split them etc.  Suggestions for the UI & UX would be very welcome.

**Comment by ara4n** [comment]
closing as dup of #1554
