### ISSUE TITLE
Threading UX

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1792]
Placeholder for future threading UX discussions

**Comment by ara4n** [comment]
![image](https://cloud.githubusercontent.com/assets/1294269/16842293/db06073e-49d4-11e6-8fc0-d83bbb854b21.png)

**Comment by ara4n** [comment]
The design happened; we need to implement it.

**Comment by tessgadwa** [comment]
@ara4n would it be possible to upload the design specs?

**Comment by richvdh** [comment]
#2349 is about the implementation, so this is done.

**Comment by t-m-w** [comment]
This issue says the design is complete, but it looks like folks are continuing to brainstorm designs over in the implementation thread (#2349) three years later. Is the design meant to be kept private?

**Comment by jryans** [comment]
I am not sure where these designs from 3 years ago (before I joined the core team) are kept, but I would guess any design from so long ago that hasn't been implemented yet likely needs a lot of rework anyway, so I am not sure how much value they would have now.
