### ISSUE TITLE
Github / gitlab / openid login?

### ISSUE THREAD

**Issue by fommil** [vector-im/riot-web#1840]
This project looks great! I'd love to use it instead of gitter.im for all our ensime.org communications. But when i tried out the app it wanted me to create an account and provide a password, that's going to be too high a barrier of entry. Could you support openid logins with convenient buttons for github / gitlab?

**Comment by ara4n** [comment]
Mm, yup, good point.  We've got a few alternative login mechanisms hooked up (LDAP, SAML etc) but fullblown OpenID would be awesome.

**Comment by fommil** [comment]
w00000t!

Please let me know when it's up and running. I'd love to move away from gitter and go libre.

**Comment by ToferC** [comment]
Any movement or interest on this issue? We're doing a lot of work on OpenID. It would be great to provide a way to link to other apps.
