### ISSUE TITLE
Per-group room directory listing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1847]
It'd be really useful for a group of users to have visibility to a particular set of published rooms.

**Comment by vith** [comment]
My first thought was a (homeserver?) setting that causes local rooms to be grouped before remote rooms in the directory list, but a user group/team concept would probably be even better.

**Comment by martinklepsch** [comment]
Just for others wondering "groups" are a concept in the process of being implemented in Matrix with [more information available in this Google Doc](https://docs.google.com/document/d/1cTK2pKolWNXspL69knpDJkcQWZsHpsMDTc2X_dEB5XQ/edit#heading=h.ohd7iv995bgp).
