### ISSUE TITLE
Editable messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1862]
https://github.com/matrix-org/matrix-doc/issues/682

**Comment by richvdh** [comment]
From https://matrix.org/jira/browse/SPEC-410:

> Pretty, pretty please with sugar on top add this soon.

**Comment by AndrewJDR** [comment]
Coffee on chat the brought up the point that this could be tricky to deal with for bridges (e.g. irc bridges) since they don't support the concept of message edits or message redaction. I propose that for bridges, a new message be sent and prefixed with something like "Message Edit: <newly modified message content>".

**Comment by ara4n** [comment]
The gitter bridge already handles this quite well actually, for gitter->matrix, using something like this

**Comment by AndrewJDR** [comment]
@ara4n @richvdh  Lack of this feature has long been a thorn in my side, so I'm considering tackling implementation of this issue with a friend.
Which files/functions within synapse, vector-web, matrix-react-sdk would need to be modified to get this working for synapse and vector-web for starters?
Even if this is just a few very general pointers, this would be helpful.

**Comment by k3vmcd** [comment]
Editing a message and deleting the entire line should then cause the redaction (deletion) of that message.

**Comment by k3vmcd** [comment]
Using the up arrow should edit the last message that user sent.

**Comment by tjgillies** [comment]
has anyone made a PR or branch for this anywhere?

**Comment by ara4n** [comment]
yes: https://github.com/matrix-org/matrix-react-sdk/pull/588. It needs review. This is working its way up our todo list...

**Comment by MightyCreak** [comment]
I sure hope this will be implemented shortly. I remember it was the first thing I requested for the open source social network service Diaspora, it's been 7 years now, but the feature is still not here.

As a result, after a long wait, I eventually left this social network. Of course, post editing was not the only reason, but it was definitely part of the reason.

Anyway, I truly hope the same scenario won't happen again with Matrix/Riot.

**Comment by L3rchal** [comment]
Kinda hope as well this feature will be added soon 🙏

**Comment by LexiconCode** [comment]
It sort of a basic feature of any chat client.

**Comment by adocampo** [comment]
Agree. Pretty rare nowadays a chat client's user cannot edit its own sentences.
From a developer's point of view surely is not interesting as this has been asked since 2016, but for a users point of view is ridiculous. I just like use a word processor without fonts format or a media player without volume control... I think if people wanted that, they would stick with IRC.

**Comment by MightyCreak** [comment]
Recently, the devs told about their roadmap for Riot Web: https://medium.com/@RiotChat/whats-next-for-riot-web-be48f948c801

So, the good news is that it's in the "Next" column, right after "Now" and "Later". So less good (yet understandable) news is that there is no ETA for this "Next" column. It simply says what the devs will work on after the "Now" features are done.

Hopefully, we'll see message editing before the end of the year.

**Comment by jryans** [comment]
This feature is being broken down into [smaller tasks](https://github.com/vector-im/riot-web/labels/feature%3Amessage-editing) and we hope to start those pieces soon.

**Comment by jryans** [comment]
An initial version of this now exists (as a disabled by default labs feature) on https://riot.im/develop. We'll continue to iterate on it there until it's ready for general release.

**Comment by lnicola** [comment]
@jryans I tried the labs feature and it seems to send a copy of the older message, without redacting it. Is that intended?

**Comment by t3chguy** [comment]
Yes, its so that you can see an edit history

**Comment by t3chguy** [comment]
Editable messages are already a thing with web and desktop riot builds.

**Comment by sschuberth** [comment]
Ah, right, I was assuming the option to be in a message's dot menu, but there's a dedicated icon, silly me. Thanks!

**Comment by MightyCreak** [comment]
I.. don't see the button in the Riot/Desktop on Linux.. should I see it?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/65878680-83ed4a80-e386-11e9-8452-ab89c651ff10.png)

**Comment by MightyCreak** [comment]
I got that buttons too, but that's smiley/reply/others, and in the others menu, there is no edit menu.

**Comment by t3chguy** [comment]
Whooops, posted the wrong one:

![image](https://user-images.githubusercontent.com/2403652/65880449-bcdaee80-e389-11e9-9d50-8474b2e4048d.png)

**Comment by MightyCreak** [comment]
We agree this is only in develop, right? Or at least that it's not on desktop Linux?

**Comment by aaronraimist** [comment]
> We agree this is only in develop, right? 

No. It was released in July with Riot 1.3. You also need to be logged in to a up to date homeserver.

**Comment by MightyCreak** [comment]
I'm on Riot/Desktop on Linux with the latest flatpak version (1.4 I think) and I don't have this option on my messages. I have the same as your first screenshot (without the pencil).

**Comment by jryans** [comment]
@MightyCreak The editing feature should be enabled for everyone for a while now. Please open a new issue if you aren't seeing it, so we can work out what's wrong.

**Comment by MightyCreak** [comment]
Yep sorry, I added a previous comment and deleted it right after because I needed to try something first.

So, TLDR: good news, it works on Riot/desktop on Linux.

The thing is, I was looking at the buttons on a message where I uploaded an image which, apparently, is not editable. Testing on a text message, it was working as expected.

Sorry for the confusion.
