### ISSUE TITLE
Self-presence is often several minutes old in Vector on launch

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#187]
I'd expect launching Vector to trigger a presence update that sets my lastActiveAgo to zero.  In practice the app often sees me as active several minutes ago on starting up the app.  Why?  Is it because of how presence is merged on synapse?

**Comment by ara4n** [comment]
In practice my self-presence often seems to be stale in general atm, which is very disconcerting.

**Comment by ara4n** [comment]
> CCLXI:
Also, is anyone fixing the user list?
In this room I am "online 10m ago"

**Comment by richvdh** [comment]
I reckon this got fixed
