### ISSUE TITLE
Show a preview image in the "are you sure you want to upload this file" modal dialog

### ISSUE THREAD

**Issue by oddvar** [vector-im/riot-web#1881]
Feedback from the KDE guys: The only issue I see is that when posting an image, it does not show a preview before it is sent to the chat :)

**Comment by nunoperalta** [comment]
Definitely, this should be a basic feature. :)

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2858 
![Screen Shot 2019-04-19 at 9 31 38 AM](https://user-images.githubusercontent.com/5855073/56428747-1a6cfa00-6286-11e9-8e44-11438070687e.png)
