### ISSUE TITLE
Emoji completion needs support for aliases.

### ISSUE THREAD

**Issue by jansol** [vector-im/riot-web#1949]
Many emoji have needlessly long names, which (to me) are largely unintuitive as well. A simple solution would be supporting aliases for emoji that have multiple commonly used names. (even if it completes to the canonical name of the emoji, search should support the aliases)

Example: :japanese_ogre: is `:japanese_ogre:` instead of, as I expected, `:oni:` or `:oni_mask:`
Similarly :video_game: being `:video_game:` is not very intuitive for someone who sees the symbol as a controller and thinks of `:game_controller:`

Granted, `:game_controller:` could also refer to `:joystick:`, so maybe aliases could allow one-to-many mappings. Since there is a window for picking the wanted one from the results, this should not be a problem.

**Comment by ara4n** [comment]
If someone can find a list of emoji aliases, then i'm sure we can add this in...

**Comment by turt2live** [comment]
@lukebarnard1 I believe this is completed?

**Comment by lukebarnard1** [comment]
I don't think it is completed, but there is certainly meta data that we can search as part of the emoji completion.

**Comment by lukebarnard1** [comment]
This _is_ now implemented but [17 days ago](https://github.com/vector-im/riot-web/issues/1949#issuecomment-314371921) there was a bug in the search logic, which has now been fixed - matrix-org/matrix-react-sdk#1236.
