### ISSUE TITLE
[enhancement] Add a "copy to clipboard" button to code blocks

### ISSUE THREAD

**Issue by jansol** [vector-im/riot-web#1974]
Just a small button in the top-right corner that only shows when hovering over the block should be fine. This would be a valuable addition to people transitioning from slack.

**Comment by edgardmota** [comment]
Hi... may I have a try on solve this issue? Thanks!

**Comment by jansol** [comment]
of course, go ahead

**Comment by niklaskallander** [comment]
@edgardmota What's the status on this?

**Comment by SpEcHiDe** [comment]
Hi! Is this issue up_for_grabs , if it's not solved yet?

**Comment by ara4n** [comment]
absolutely - yes please!!

**Comment by edgardmota** [comment]
Do it, @SpEcHiDe, I've struggled on it for awhile but I'm not currently working on it anymore.

**Comment by t3chguy** [comment]
How about adding it to the `…` menu on a message?

**Comment by t3chguy** [comment]
closed by #4204
