### ISSUE TITLE
Format users and rooms as dedicated objects in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1988]
We have designs for showing users & rooms as HTML elements in the timeline at https://zpl.io/21BYjq

The idea is to do this to joins/leaves etc. as well as actions, as well as messages with `<a href="mx://"/>` style 'metadata' hyperlinks in them.

@aviraldg: filing this as a dedicated bug for your radar as I don't think we previously had one.

**Comment by ara4n** [comment]
@wmwragg heads up that I've split this one out here.

**Comment by t3chguy** [comment]
@ara4n I don't have access to the zpl link, is this essentially done by Pills?

**Comment by t3chguy** [comment]
Assuming this is solved by Pills
