### ISSUE TITLE
New Status Bar behaviour (hide status bar by default)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1991]
Split out from #1761:
- Status bar is hidden by default.  It appears only for:
  - Error messages (e.g. the "connectivity failure" warning)
  - "You have N unread messages" (when scrolled up the page)
  - "Matthew and 5 others are typing" (but _only_ when scrolled up the page)
- Typing notifications are shown like the iMessage ellipsis chat bubble, as a phantom inline message in the timeline.  To stop the timeline bouncing up and down as people start and stop typing, we debounce the timeline animation - after making room for the typing notification by scrolling up, the timeline waits N seconds (if at all?) to scroll back down again.

**Comment by ara4n** [comment]
@antikewl - this needs a design for the iMessage-style chat bubble.

@wmwragg - i think the implementation of this can be attacked independently of that design (and independently of the rest of the autocomplete stuff in #1761)

**Comment by antikewl** [comment]
![02_x chat inline error command](https://cloud.githubusercontent.com/assets/3658981/18351598/c5836f44-75d2-11e6-938d-782dad035e47.png)
https://zpl.io/Z1XGRuz

![02_x chat inline error connection](https://cloud.githubusercontent.com/assets/3658981/18351600/c8cfea10-75d2-11e6-93dc-dbd248a3f14f.png)
https://zpl.io/Z10xKb4

**Comment by ara4n** [comment]
with ben's typing notification design, this is done & design signed-off

**Comment by wmwragg** [comment]
@ara4n This appears to be two completely different tasks:

1. Status bar is hidden by default.
2. Typing notifications are shown like the iMessage ellipsis chat bubble, as a phantom inline message in the timeline.

Shouldn't these be two separate tickets

**Comment by ara4n** [comment]
sorry, i conflated them together as the act of hiding the status bar means that we need somewhere else for the typing notifs to go. you can't really have one without the other. happy to split though if it helps!

**Comment by ara4n** [comment]
I'm a bit worried that the process of showing & hiding the statusbar could be a bit of a nightmare in terms of causing the main TimelinePanel to change shape and lose offset etc.  It might be worth a quick initial investigation, but if it's looking too invasive (given we're meant to be frozen) i'd deprioritise it.

**Comment by ara4n** [comment]
see #2237 for the typing notif look & feel ticket, but that has a dependency on this one.

**Comment by wmwragg** [comment]
@ara4n It's proving ridiculously difficult to show/hide the `mx_RoomView_statusArea` in the `RoomView`, it's used by so many different components, some determine their own show behaviour, but expecting to always be viewable. I think I'm getting a feeling for how the spaghetti hangs together, but this is going to be a fairly long ticket. Just warning you, so if you want to deprioritise this   let me know.

**Comment by lukebarnard1** [comment]
Should this be closed now? Or should we close it once we've actually gone and put the typing avatars in the TimelinePanel itself and done the animation via actually scrolling the scroll panel?

**Comment by ara4n** [comment]
We've had a week or so to play with the current implementation, and I'm a bit worried that it may not be far enough along to actually be considered an improvement. 

Specifically, the intended design here is to mimic iMessage: that typing notifs are shown as if they are a new message... and critically **when the user stops typing by sending their message, the typing placeholder morphs into the real message**.

This means that the statusbar transparently collapses again, rather than the current situation where 10s after anyone sends a message, you get the separate & very distracting collapse animation happening.  This means that the only time you see distracting and annoying collapse animations is in the unlikely scenario of someone who starts typing, and then thinks better and stops.  Which we could even consider sufficiently unlikely to kill the collapse animation entirely.

My current feeling is that we should disable this (or make it an optional setting) until we've gone the whole hog to implement this behaviour, otherwise it keeps bouncing up & down way too much, even with the debounce logic.  @superdump and @aliencq and others have already WTFed fairly loudly at us on this.

@lukebarnard1 wdyt?

**Comment by uhoreg** [comment]
> This means that the only time you see distracting and annoying collapse animations is in the unlikely scenario of someone who starts typing, and then thinks better and stops. Which we could even consider sufficiently unlikely to kill the collapse animation entirely.

That scenario isn't that unlikely.  I do it all the time. ;)

FTR, I also don't like how when I scroll up in the timeline and then back down the statusbar hangs open for a long time.  I think the statusbar should close immediately after scrolling down to the bottom, if there are no other notifications.

IMHO, the current behaviour would be fine with the following tweaks:

1. when a new message appears, then hide the statusbar if there are no current notifications
2. when the user scrolls to the bottom of the timeline, hide the statusbar if there are no current notifications.

Another thing that may help is to fade out the typing notifications gradually in the case where someone starts typing and then stops, so that the statusbar isn't completely empty for so long.

**Comment by lukebarnard1** [comment]
Forgot to respond to this before. I agree (albeit a bit late anyway) and have started implementing the Real Deal :tm: here: https://github.com/matrix-org/matrix-react-sdk/pull/728

**Comment by turt2live** [comment]
I think we ended up doing this... Please reopen and clarify if I'm wrong
