### ISSUE TITLE
We should not push users who are known active.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1993]
If my presence shows that I am active on some device, we should not send push notifications to other devices in general.

If the user goes idle shortly after receiving a pushable message, then we should send the push through anyway after a short delay.  We might also want to do this if the user is active but isn't sending read receipts for the messages we would have pushed them.

**Comment by tokred** [comment]
Would greatly appreciate such a feature - e.g. in the office, I am logged in via desktop client and therefore constant notifications on my phone are annoying! I think this is now tracked in https://github.com/vector-im/riot-web/issues/3432.

Regards

**Comment by t3chguy** [comment]
Duplicate of #469
