### ISSUE TITLE
Mouse over state in MemberList can get stuck on if you quickly mouseover

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#1997]

**Comment by albuic** [comment]
I can confirm this bug on Windows.
If you select a room and move quickly out of the room list, the mouseOver state doesn't seem to change. (see pictures)

![bug](https://cloud.githubusercontent.com/assets/8595270/25040086/a276bda4-2107-11e7-86fe-44239a461809.png)
![bug2](https://cloud.githubusercontent.com/assets/8595270/25040087/a2771fa6-2107-11e7-89d7-4d0d2ac6c3a9.png)

**Comment by ara4n** [comment]
the screenshots here very nicely show https://github.com/vector-im/riot-web/issues/2420.

however, the chevrons on the memberlist problem is even worse :)

<img width="254" alt="screenshot 2018-09-12 at 12 36 41" src="https://user-images.githubusercontent.com/1294269/45422578-84864680-b688-11e8-8b06-624f952919f9.png">
