### ISSUE TITLE
Consider ditching RRs on tiny screens to save space

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2002]

**Comment by t3chguy** [comment]
RRs are now user-disablable, and there is a new issue of the space still being taken up - I think that splits off from this

**Comment by aaronraimist** [comment]
Closing as duplicate of https://github.com/vector-im/riot-web/issues/4248 and https://github.com/vector-im/riot-web/issues/1633 which have thumbs and conversation
