### ISSUE TITLE
DnD effect on room list is broken

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2004]
there is no feedback when you try to DnD a room

**Comment by richvdh** [comment]
apparently only affects chrome 52?

**Comment by ara4n** [comment]
what precisely are you seeing? seems okay for me...

**Comment by richvdh** [comment]
See vid at https://matrix.sw1v.org/_matrix/media/v1/download/sw1v.org/uAMWxrwhJNmAADfrcAdlGcuU; I can't tell that dragging a room is having any effect until I get out of the main "rooms" list

**Comment by ara4n** [comment]
this is working fine for me on Chrome 61 on OSX, but then again I think it always did.  @richvdh is it still borked for you? if so, please reopen (and let's tag it as platform specific).  @t3chguy, as our token windows user, does it work there? ;)

**Comment by t3chguy** [comment]
Works great here on Windows with Chrome 61
