### ISSUE TITLE
Option for selecting maximum size of image thumbnails

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2026]
Some people don't want massive image thumbnails

**Comment by scar45** [comment]
I am encountering an issue within Firefox, where a high resolution image displayed in the chat log causes the browser to be non-responsive for a handful of seconds. Even on a machine with plenty of horsepower. This behavior doesn't seem to happen in Chrome though. Not sure it's related, but

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/1520
