### ISSUE TITLE
Vector is all sorts of broken on mobile web

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#205]
In no particular order:
- [x] _Incredibly_ slow and unreliable at changing rooms
- [ ] Lets you scroll off the bottom of the screen
- [ ] Doesn't resize when keyboard is visible
- [ ] Need to change the zoom to be more legible in general
- [ ] Autofocuses the input box too often, rezooming everything
- [x] Hoverovers get stuck on
- [ ] Doesn't default to hiding membership list (on 6+ at least)
- [x] Flexbox bug on iOS 9.2 means invite box overlaps the membership list
- [x] Scrolling to bottom of the timeline doesn't make it all the way
- [x] Avatars overlap (general Safari layout bug potentially)
- [ ] doesn't progressively load (#126 aka #2498)

I fixed most of these for angular already; it's just a matter of porting over similar fixes.

New screenshot:
![ima_52e1219](https://cloud.githubusercontent.com/assets/1294269/12526923/23a14eec-c16b-11e5-935e-7afc067b2148.png)

**Comment by lampholder** [comment]
Do we still want this?

**Comment by turt2live** [comment]
@lampholder I'm pretty sure we can close this because of the mobile landing page...

**Comment by lampholder** [comment]
Works for me. There's an app for this, I've heard :P

**Comment by ara4n** [comment]
i’m not entirely sure we should close this one tbh; we need to make Riot more of a PWA, and a good indicator if whether we have is if it runs on mobile. At least, this was my motivation...

**Comment by jryans** [comment]
I think we would need to very consciously choose to support mobile web and invest in making it work for there to be any chance of it working well as each new feature lands over time. (To be clear, I think it would be great to support this! I just want to call out the level of investment required.)

If we're not in a position to support mobile web now, maybe the issue can wait until we are.
