### ISSUE TITLE
We no longer have the date on old message timestamps

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2051]
Whereas we had it when it was on the RHS (as there as more space). It would be great to work out how to have it back

**Comment by lukebarnard1** [comment]
Tooltip on the timestamp FTR!

**Comment by zzottel** [comment]
When scrolling back to the last unread message, I often miss the day divider, and then I'm unsure which date I'm at. A tooltip when hovering over the message timestamp would help a lot.

**Comment by ara4n** [comment]
good idea - fixed in 67efb8bde264e3ea0823e40558d29dd89120c0c9
