### ISSUE TITLE
Upgrading from Guest to registered resurrects third party invites

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2062]
Invite a user by email. 
He joins as a guest by clicking on the link in the email, then joins another room from the directory: both rooms are joined and listed properly. 
Upgrade guest to register user: rooms where he was invited are back into the unjoined invite section and he needs to reaccept the invite. 
Tested on /beta
matrix-react-sdk version: 0.6.5-r1
vector-web version: v0.7.5-r2

**Comment by AmandineLP** [comment]
It works fine for non-email invite FTR

**Comment by lukebarnard1** [comment]
I'm guessing this flow has totally changed via ILAG
