### ISSUE TITLE
Timezone doesn't update without refreshing on Chrome/OSX

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#207]
This is a bug in Chrome :(
https://code.google.com/p/v8/issues/detail?id=2861

**Comment by turt2live** [comment]
Related/dupe? https://github.com/vector-im/riot-web/issues/44

**Comment by lampholder** [comment]
It looks like the Chrome bug was fixed (in 2014?) and I ran their test case in modern chrome and the date objects did update themselves by magic once the OS tz was updated.
