### ISSUE TITLE
'Deactivate account' masquerades as a save button

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2074]
The location of 'Deactivate account' makes people think it's a save button and click it by mistake: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1472921580557drvEN:matrix.freelock.com

**Comment by t3chguy** [comment]
Suggestions for improvement?

**Comment by t3chguy** [comment]
Is
> But perhaps that could be moved to the account section of the page? Next to Log Out/Change PW I think would be an appropriate place

wanted?

**Comment by richvdh** [comment]
it's certainly better than it was. tbh the whole settings page could do with some tidying so I'm happy to close this.
