### ISSUE TITLE
Have opt-in analytics for performance and usage of the app

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2075]

**Comment by tuxayo** [comment]
Good idea, I'm not sure many users know that Google is informed of every time they use riot-web. (+ all the info that Google Analytics sends home)

**Comment by 4nd3r** [comment]
related https://github.com/vector-im/riot-web/issues/2787#issuecomment-269201678

**Comment by kyrias** [comment]
First of all I'll make it clear that I do consider both forced and opt-out analytics to be immoral, and that if analytics should be implemented it should *always* be opt-in, potentially just having a popup with an accept/decline link on first use.

Secondly, if opt-in analytics would make such a huge difference in your funding then that would certainly suck for you, but I honestly don't care that much about that when it concerns issues like these.

I'm unclear on how exactly it affects your funding though, and would appreciate some clarification on that point (@ara4n?).  If it's just "how many users actively use it" it would be simple to just collect anonymized webserver logs, using a hashed version of important details like the IP to do aggregated stats over.

--- 

But anyway, even before this happens the riot.im website should either way be changed to make it abundantly clear that language like

> No one should control your communication and data but you.

does in fact *not* apply if you use the hosted version.  And yes, users should be reading the privacy policy and related documents, but that kind of language would still mislead a large part of the majority that doesn't.

**Comment by ara4n** [comment]
The only reason we haven't switched away from GA is because of the amount of effort it takes given the size of metrics pipeline we've got built on top of it (especially for more exotic things like cohort retention analysis, which stuff like piwik doesn't do).  In turn, the metrics do directly impact funding for the core team, which frankly is critical for the project; without a core team of funded developers I'm pretty confident that Riot and Matrix dev would grind to a halt - after all, the ambition and scope here across the whole Matrix ecosystem is way more than most do-it-in-your-spare-time FOSS projects.

The intention is to switch, as you suggest, to generating stats on Riot uptake from serverside logs on the Matrix.org HS instead.  This is significant work, and  medium priority though relative to burning issues we have elsewhere (federation stability, E2E stability, etc).  I'm expecting us to get to it in the next month or so.

In terms of language on the riot.im website, I don't see using GA as being incompatible with "No one should control your communication and data but you." - by using GA we're not somehow letting Google control your communication or communication data.

In the interim, a PR to make GA opt-in (perhaps by using the StatusBar at the top of the riot-web page to say "oh hai, click yes/no to share usage info with us to improve the app") would be super-appreciated.

**Comment by kyrias** [comment]
Not communication data maybe, but it does give Google access to more metadata than they otherwise would, and that does matter.  Currently they get access to every IP using the hosted version, and every room that the user opens.  And at large scale, that data is relatively simple to correlate to specific users across multiple devices, and that potentially lets you track location as well.

**Comment by tuxayo** [comment]
> and every room that the user opens

You means by knowing the url which contains the room name?

**Comment by kyrias** [comment]
Yes.

**Comment by ArchangeGabriel** [comment]
Well I’m quite new here, but I definitively agree with @kyrias and will hold on starting to use riot until this get fixed.

**Comment by ara4n** [comment]
GA has been removed entirely from riot-web for now, until someone can get around to making it opt-in only: https://github.com/vector-im/riot-web/commit/6a7daaf6c4a9526068bf6a4595e063e87e0b6a36

**Comment by orbifx** [comment]
When accessing Matrix via Riot.im, my browser still tries contact GA. Is it just a Riot.im thing?

Is the desktop client affected?

Also, which release version did this change make it to the master? ArchLinux's AUR still uses 0.9.7 and it patches-out GA.

**Comment by ArchangeGabriel** [comment]
@orbifx Dunno about riot.im, but for master this landed in 0.9.8rc1. ArchLinux update to 0.9.9 is ready and dropped the patch (because nothing to patch anymore), but is waiting on https://github.com/vector-im/riot-web/issues/3024 to be fixed.

**Comment by ArchangeGabriel** [comment]
(If you go on the commit page, just below the commit message there is a list of tags containing this given commit)

**Comment by orbifx** [comment]
Thanks @ArchangeGabriel. I've upvoted #3024. Looking forward to that newer version.

**Comment by ara4n** [comment]
We have no plans to ever turn on GA again on riot.im/app.  Instead we're going to look more seriously at piwik or similar to try to get UX feedback.

**Comment by ara4n** [comment]
(which is bug #2077)

**Comment by pmgouveia** [comment]
piwik is very heavy mysql analytics... I use instead https://github.com/allinurl/goaccess analyzing the requests... everytime a user uses a feature it makes a request no?
