### ISSUE TITLE
Look at piwik for analytics

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2077]

**Comment by jfrederickson** [comment]
It's worth noting that my browsers block GA as I have uBlock Origin installed and running. As Riot's audience right now is likely fairly technical, I suspect I'm not the only one - you may see a boost in the user count if you switch to something self-hosted due to this. How much of a boost, I don't know, but it's maybe something to keep in mind.

**Comment by richvdh** [comment]
See also #2075

**Comment by richvdh** [comment]
To clarify (my understanding of) the Riot team's position on GA:
* User analytics are useful tools and are important to secure our funding (#2075 is the place for debate on whether we should be collecting analytics at all on riot-web)
* GA has been useful in helping us get started collecting metrics quickly, allowing us to concentrate on adding functionality instead.
* The use of a commercial, closed-source, third-party service to collect those analytics does not sit well with a security-conscious open-source project, and many people find the use of a service provided by Google particularly troublesome.
* Users would also like more clarity on what sort of metrics we collect via our analytics.

Switching from GA to a system we can manage ourselves, such as piwik, could help address these concerns. Accordingly it is very much on the feature list.

Finally, to reiterate for clarity: analytics are only collected on the hosted versions of riot-web at https://riot.im (and vector.im). You are of course free to run your own copy of riot-web, which will not collect any analytics at all.

**Comment by uhoreg** [comment]
For those following this issue and not #2075, https://github.com/vector-im/riot-web/issues/2075#issuecomment-279032514 indicates that Google Analytics has been removed from riot-web for now.

**Comment by t3chguy** [comment]
Piwik stuff added in #2075, this probably needs breaking off into an issue of what we track, closing this
