### ISSUE TITLE
Disable url previews in E2E rooms by default

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2084]

**Comment by uhoreg** [comment]
In addition to disabling URL previews by default, the room setting to enable/disable URL previews should come with a warning in e2e rooms that enabling them may leak information.

**Comment by PureTryOut** [comment]
This happens in WhatsApp as well and is gaining a fair bit of attention on [/r/Android](https://www.reddit.com/r/Android/comments/6n0kyr/interesting_video_about_whatsapp_leaking_your/?utm_content=comments&utm_medium=hot&utm_source=reddit&utm_name=Android). Please disable it by default, it shouldn't be that hard to do.

**Comment by t3chguy** [comment]
@ara4n given the prio bump could you clarify the desired behaviour

+ Do we split the UserSettings toggle into non-e2ee and e2ee
+ Do we ignore account&default values for e2ee rooms and require it to be explicitly set per-room
or something else

**Comment by turt2live** [comment]
It makes sense to me to say that the `room` setting means nothing in e2e rooms, likewise for `account`. `room-account` or `room-device` (technically not settable) would have to be explicitly required.

**Comment by t3chguy** [comment]
so the latter option but also ignoring `room`

**Comment by Half-Shot** [comment]
Explicitly set per room seems obvious to me PLUS making sure the user knows the implications (I realise they should know the implications as it's E2E, but I'd spell out the consequences anyway)

**Comment by t3chguy** [comment]
> (I realise they should know the implications as it's E2E, but I'd spell out the consequences anyway)

This either way :)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/41691062-81f60cb8-74f0-11e8-9492-9df64345215c.png)

opinion on wording? (ignore i18n warning)

**Comment by turt2live** [comment]
I'd recommend starting with explaining what they are (which should really be included in every room to be honest). How does something like this sound?

When someone puts a URL in their message, a URL preview can be shown to give more information about that link such as the title, description, and an image from the website. In encrypted rooms, like this one, URL previews are disabled by default to ensure that your homeserver (where the previews are generated) cannot gather information about links you see in this room.

**Comment by t3chguy** [comment]
🎉
