### ISSUE TITLE
Only half of the chat is displayed when switching tabs

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#2089]
As a picture tells more than a 1000 words in this case:

![screenshot_2016-09-02_09-53-00](https://cloud.githubusercontent.com/assets/1565836/18244158/d676ac4c-735e-11e6-9179-6ea3b4963167.png)

Happens when switching tabs. Is fixed by either sending a message or switching rooms. Sometimes also fixed by rapid tab switching. This has been happening to me for a few days on 2 different PC's running /beta, both running Firefox, and still happens as of this writing on /develop.

**Comment by ara4n** [comment]
@PureTryOut is it still doing this? precisely what OS and Firefox versions?

**Comment by PureTryOut** [comment]
Sometimes yes, not as much as before though. Happens on both Arch Linux and Ubuntu 16.04 for me, using Firefox 48 on I believe both of them.

**Comment by PureTryOut** [comment]
I can't reproduce this issue anymore, so closing.
