### ISSUE TITLE
registration_shared_secret support

### ISSUE THREAD

**Issue by WGH-** [vector-im/riot-web#2090]
As far as I know, the only way to register on private homeserver with closed registration is through Synapse script `register_new_matrix_user`, which allows user to supply shared secret through commandline option.

Although the script is standalone, and doesn't require extra dependencies (beside stdlib), it's still quite an inconvenient way to register account.

I think Vector support will be quite handy.

**Comment by ara4n** [comment]
@WGH- how would you know whether vector users should be trusted to sign up for an account then?  This is what guest access is intended for...

**Comment by WGH-** [comment]
Uhm, my expected use case is that I run a private homeserver, and distribute access token via e.g. mailiing list.

I don't want to say "download python script and run it so and so", I want to say "open this url, enter this token and go".

**Comment by WGH-** [comment]
As it turns out, "shared secret" is something more powerful than "registration token", as it allows one to register an admin account freely. 
Exposing it in Vector registration form will likely give false impression that it's just a "registration token", so it's probably a bad idea.

**Comment by t3chguy** [comment]
following the comments, probably better using #2353 for this scenario (once that is implemented properly)
