### ISSUE TITLE
No way to remove stale third party invites from the MemberList at all.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2098]
Closely related to #1282 and #1134, we don't seem to have a bug to track the fact that you can't remove 3rd party invites from MemberList, or at least i can't find it.  Also, if the user accepts the invite but subsequently leaves, the 3rd party invite continues to hang around the MemberList.

**Comment by ZerataX** [comment]
I'm not really sure if it's the same problem, but I invited a user by userid, but mistyped it. I'm fairly sure I misspelled him as `user@matrix.org `instead of `@user:matrix.org`
For me or any other member it isn't possible to now revoke this invite in any way on any platform.

**Comment by t3chguy** [comment]
@ZerataX late but the issue you want is https://github.com/vector-im/riot-web/issues/625

**Comment by ara4n** [comment]
dup #625 surely?
