### ISSUE TITLE
Custom notification sounds, globally and per room.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#2105]
Kinda surprised this hasn't been suggested yet, given how useful it could be for users who are not a fan of the notification sound, or who have a bazillion rooms and would like to be able to distinguish them audibly.

The implementation could work like:
- User uploads a sound clip to HS (which would probably be limited by whitelist to ogg or mp3)
- Store the mxcurl inside `/_matrix/client/r0/user/@Half-Shot:half-shot.uk/rooms/!somethinghere:matrix.org/account_data/org.matrix.notifysound`
  (or omit the room for global)
- Load the sound either on initial load or when the first notification is received.

Pitfalls:
- Browser support for sound formats is still patchy and although I don't think we should avoid implementing this altogether, it would be wise to fall back to the default sound for browsers that suck. Might even be worth warning users somewhere if possible.

**Comment by gdvine** [comment]
Agree this is a very important feature

**Comment by dud1337** [comment]
Did this solve it globally or just per room?

**Comment by Half-Shot** [comment]
>Did this solve it globally or just per room?

Technically yes. Riot supports setting a global custom sound as well as a room one, however only the room UI is exposed. You'll need to use the developer tools to set global sounds for now.

**Comment by dud1337** [comment]
Thanks, man.

**Comment by rosalogia** [comment]
For clarification, what file formats are readable when it comes to custom notification sounds right now?

**Comment by Half-Shot** [comment]
>For clarification, what file formats are readable when it comes to custom notification sounds right now?

IIRC, we don't validate beyond what your browser supports. E.g. I'd expect ogg/mp3/wav to be supported.

**Comment by rosalogia** [comment]
For some reason facing an issue where once I upload an ogg for a specific chat and save it, the fact that the new notification sound was ever uploaded and set completely disappears from the settings page. At first it will look like this:
![image](https://user-images.githubusercontent.com/66163965/83690301-7c89db00-a5be-11ea-8373-4e6bd56cfd3f.png)

But once I go back in it looks like this again:
![image](https://user-images.githubusercontent.com/66163965/83690370-9e835d80-a5be-11ea-9ece-7bb6f0d95cbf.png)

**Comment by matrixes** [comment]
> 
> 
> > Did this solve it globally or just per room?
> 
> Technically yes. Riot supports setting a global custom sound as well as a room one, however only the room UI is exposed. You'll need to use the developer tools to set global sounds for now.

"You'll need to use the developer tools"

Can I ask for something a bit more specific? I'd like to replace the global sound and am very comfortable with messing around in hidder settings/making temporary changes, but I'm drawing a blank in terms of _where_ in the developer tools I need to poke around. Thanks.

**Comment by Half-Shot** [comment]
Fair warning that the following steps may void your warranty or brick your client.

To change the sound globally:
- Set a notification sound in a single room, either in a test room or one you have already.
- Say `/devtools` in that room.
- Click `Explore Account Data`.
- Click the red `Account Data` button.
- Click `im.vector.web.settings`.
- Copy the `notificationSound` block

e.g. 
```json
	"notificationSound": {
		"name": "your-sound-name.ogg",
		"type": "audio/yourmimetype",
		"size": 0000,
		"url": "mxc://half-shot.uk/59770ed76c3527ba43b54b1791589ca5a95a5b43"
	},
```
- Click `Back`
- Click the green `Room Data` button
- Click `im.vector.web.settings`
- Click `Edit` (you may have to scroll down)
- Insert the following json into the object somewhere, being careful to replace the text below.
```
	"notificationSound": {
		"name": "your-sound-name.ogg",
		"type": "audio/yourmimetype",
		"size": 0000,
		"url": "mxc://half-shot.uk/59770ed76c3527ba43b54b1791589ca5a95a5b43"
	},
```
- Click `Send`.
- Sounds should now change globally.

**Comment by Half-Shot** [comment]
Suggest further commentary on global sounds takes place on https://github.com/vector-im/element-web/issues/20286

**Comment by dud1337** [comment]
@Half-Shot, I think you need to flip the order of `Room Data` and `Account Data` in that **awesome** guide of yours.
