### ISSUE TITLE
Implement correct error feedback UI for registration

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#211]
It's mean to look like this.
<img width="248" alt="screen shot 2015-10-11 at 18 47 29" src="https://cloud.githubusercontent.com/assets/1294269/10418072/a22c0302-7048-11e5-9ff7-ce8c550d5417.png">
<img width="256" alt="screen shot 2015-10-11 at 18 47 21" src="https://cloud.githubusercontent.com/assets/1294269/10418069/a22476f0-7048-11e5-90f5-b43e53fe08fd.png">
<img width="253" alt="screen shot 2015-10-11 at 18 47 17" src="https://cloud.githubusercontent.com/assets/1294269/10418070/a22660f0-7048-11e5-9183-d1259922e633.png">
<img width="375" alt="screen shot 2015-10-11 at 18 47 04" src="https://cloud.githubusercontent.com/assets/1294269/10418071/a2277c06-7048-11e5-885c-14e35dc8eb6e.png">

**Comment by ara4n** [comment]
We should hold off on on this until the new look & feel is tied down for registration.

**Comment by lampholder** [comment]
This is going to get a whole rework with the new skin inbound; I think we can close this.
