### ISSUE TITLE
Permalinks from clicking timestamps have wrong URL

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2119]

**Comment by ylecollen** [comment]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$147488640013427XpTqQ:matrix.org
is properly displayed.

**Comment by ylecollen** [comment]
Android does not support $ in URLs.

The android client URL encodes the permalinks.

**Comment by richvdh** [comment]
Have wrong URL?

Is this just a dup of https://github.com/vector-im/riot-web/issues/2509?

**Comment by ara4n** [comment]
it's a riot.im URL. it should be a matrix.to URL.
