### ISSUE TITLE
Multiline pastes are broken in RTE

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#2120]

**Comment by SijmenSchoon** [comment]
I'm having trouble reproducing this, could you provide some more details?

**Comment by ara4n** [comment]
My vague memory of the story here is that it was impossible to paste a codeblock into the RTE.

You go to a code editor, copy-paste a bunch of code as if you were doing a triple-backtick block in MD.   In RTE however it either ignores the fact you're already in code-editing mode and pastes it as normal proportional text... and if you then select the proportional text and hit the format-as-code button, it inserts newlines everything and ends up looking like this:

<img width="1035" alt="screen shot 2017-01-10 at 23 52 10" src="https://cloud.githubusercontent.com/assets/1294269/21829731/d148229c-d78f-11e6-9534-8e2bb9b44b2c.png">

I can't see anything wrong with non-code multiline pastes however.

**Comment by lukebarnard1** [comment]
Steps to repro:
 - Copy multi-line text from somewhere
 - Paste into RTE /w MD disabled
 - Select all
 - Click format-as-code button
 - Send
 - Observe the above
