### ISSUE TITLE
Scroll offset is jumping around even worse than before when back-paginating

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2138]

**Comment by wmwragg** [comment]
@ara4n Than before what?

**Comment by ara4n** [comment]
@wmwragg than since #1689. I have no idea when the regressions have happened, but something is definitely wrong.  I doubt it's anything you did in the CSS of RoomTimeline though.

**Comment by ara4n** [comment]
going to close this in favour of the more recent #2646
