### ISSUE TITLE
Warn user if an unverified device turns up

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2143]
When a new unverified device turns up in a room, and the user sends a message, we should warn them and let them check the device list.

This is going to be tricky to get right, without races: it would be easy for a malicious homeserver to engineer a race so that a new device turns up milliseconds before you press enter, so we must make sure we deal with that race robustly.

**Comment by richvdh** [comment]
Related to #2313

**Comment by remram44** [comment]
Does everyone have to approve the new device? Only one? Only the owner (from other device)?

**Comment by maralorn** [comment]
I’d actually suggest making this an opt-in option, because this is protection against active attackers. The majority of the population will get drowned in false positives they don’t understand.

**Comment by remram44** [comment]
This is the only way to protect against any homeserver of any participating user snooping in on the conversation. In my opinion it is not worth implementing end-to-end encryption at all without this, if you trust the homeservers just rely on TLS.

**Comment by maralorn** [comment]
I see the difference between a passive and an active attacker. If you don’t use E2E anyone who can one day get access to the homeserver logs (or break tls) can read the message. The active attacker scenario would actually require malicious code in the homeserver (today, without anyone noticing, which will be hard, if users who now, what they are doing are actually verifying their keys). I totally understand that the security is lower, but E2E crypto is much more important than verified E2E crypto. Confusing users with misplaced warnings lowers security and does not raise it.

(I will not push this point any further, this has to be decided by the developers. We can discuss it on matrix, if you want.)

**Comment by pierce403** [comment]
I think these warnings should pop up per room.  Something like:

`<nick> (<id>) has added a new device "<device name>" [verify] [blacklist]`

Presumably, whoever added the key would also message the room with an older verified key/device saying something to the effect of "Hey, just got a new phone" or something.  This will also encourage users to have descriptive device names.

**Comment by ara4n** [comment]
this has just merged to /develop. @pierce403 - the implementation is very similar to what you suggest (although the verify/blacklist buttons are going to land shortly in a later PR)
