### ISSUE TITLE
UI for selecting which DM to reuse (if any) when finding a conversation with a person

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2148]
In #1882 we decided in in the short term to reuse existing DMs when trying to 'start a chat' with a user.

However, this is pretty confusing and magical if you have multiple DMs or rooms in common with a user.

Much as https://github.com/vector-im/vector-web/issues/1477 shows all the rooms you have in common in a MemberInfo to let you pick how to contact someone, we need a design so that having tried to start a chat with someone from the BottomLeftMenu, we can be told "actually, you already have 3 DMs with them - do you want to use one of them rather than starting another?"

I suggest we could just update the 'start chat' dialog box with possible rooms to use for the user who has been specified in the input field, so the user can just click through to those rooms rather than actually hitting the 'start chat' button.

**Comment by turt2live** [comment]
@ara4n this seems implemented?
![image](https://user-images.githubusercontent.com/1190097/27342447-726ad440-559d-11e7-811c-0bf7a251bf45.png)

**Comment by t3chguy** [comment]
seems half-done, doesn't seem to get triggered from Start Chat

**Comment by t3chguy** [comment]
or maybe has regressed, I've seen it in the past

**Comment by t3chguy** [comment]
I just had it pop up on me so it definitely works at least sometimes

**Comment by aaronraimist** [comment]
I think this is done. I haven't had it not work from start chat.

**Comment by turt2live** [comment]
I think this is asking for the "Start chat" button on the MemberInfo to also give the same dialog. I think...

**Comment by aaronraimist** [comment]
It does, I just tried it

**Comment by turt2live** [comment]
I also just tried it and it definitely did not prompt.

**Comment by aaronraimist** [comment]
Well no the button on MemberInfo doesn't but the rooms are displayed right above the button

![screen shot 2018-11-28 at 3 44 06 pm](https://user-images.githubusercontent.com/5855073/49184225-73161780-f324-11e8-856c-b02b6aab1cfd.png)

**Comment by turt2live** [comment]
This happens automatically now.
