### ISSUE TITLE
Markdown syntax-highlighting breaks with commas in content

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#2169]
_abc, def_ for example

**Comment by ara4n** [comment]
The more I think about it the more I feel we should just disable 'syntax highlighting' - implementing a realtime MD parser is no fun and always going to get it a bit wrong.  I've also seen underscores being incorrectly parsed.  If the user wants to preview what it will look like they should roundtrip via the MD button.

**Comment by aviraldg** [comment]
@ara4n We could get rid of it entirely, or switch to a Markdown parser that returns a parse tree we can reuse for this purpose (so we don't have to implement this ourselves.) What do you think we should do?

**Comment by aviraldg** [comment]
@ara4n We could get rid of it entirely, or switch to a Markdown parser that returns a parse tree we can reuse for this purpose (so we don't have to implement this ourselves.) What do you think we should do?

**Comment by lukebarnard1** [comment]
I don't think any syntax highlighting happens until he message gets to the timeline now.
