### ISSUE TITLE
stop MD from creating HRs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2170]

**Comment by remram44** [comment]
Changing [this line in matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk/blob/ec9243d4b0cd15e900b2bb167ad05daec7f0e104/src/components/views/rooms/MessageComposerInput.js#L23) would disable this.

Rationale is that users inserting breaks in rooms is awkward, and people are triggering it by mistake when using the `-_-` smiley by itself.

**Comment by ara4n** [comment]
thanks @remram44!

**Comment by ara4n** [comment]
the patch doesn't seem to be working...

**Comment by t3chguy** [comment]
so should <hr>'s not be part of the whitelisted subset of HTML?

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/1319
