### ISSUE TITLE
I was invited into a federated room. The push notif gave me the details of the room.   The invite in Vector had none.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2206]

**Comment by ara4n** [comment]
@erikjohnston is this a synapse regression?

**Comment by erikjohnston** [comment]
I've added a sytest and it seems to pass? https://github.com/matrix-org/sytest/pull/311

**Comment by erikjohnston** [comment]
And it works for me for matrix.org -> jki.re invites. If you see it again can you give details please?

**Comment by lukebarnard1** [comment]
@ara4n and I tested, seems fine
