### ISSUE TITLE
Clients should pick up when notification settings change

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#221]

**Comment by ara4n** [comment]
This is only really noticeable atm because vector doesn't let you edit your own push settings within the app.  Unblocking.

**Comment by ara4n** [comment]
new notif settings should come down sync in account_data these days, so this shoudl be fairly easy to sort now.

**Comment by turt2live** [comment]
@ara4n I'm pretty sure this is fixed.

**Comment by aaronraimist** [comment]
@turt2live Yeah
