### ISSUE TITLE
Drag and drop file upload is broken on FF

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2234]
FF 38.6.1

**Comment by ara4n** [comment]
@AmandineLP 38 is ancient - we're on 48 now; i'm amazed 38 works at all. What symptoms are you seeing?

**Comment by AmandineLP** [comment]
![image](https://cloud.githubusercontent.com/assets/8582858/18588477/e50467c4-7c26-11e6-8930-d04836f95ee1.png)

and ok will tell to upgrade

**Comment by ara4n** [comment]
oh, *that* kind of drag and drop - i thought you meant reordering the room list...

**Comment by ara4n** [comment]
also present on 48

**Comment by t3chguy** [comment]
Seems to work in 53

**Comment by pafcu** [comment]
@AmandineLP Could be closed, as all supported versions of Firefox seem to work?
