### ISSUE TITLE
New typing notification look & feel

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2237]
Complementary to #1991, implement Ben's new typing notification UI from https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=57d18332dc01260412dfe934

**Comment by lukebarnard1** [comment]
https://matrix.org/_matrix/media/v1/download/matrix.org/YaQnyQSzYmtOyLgDGHBfQnkV

**Comment by lukebarnard1** [comment]
I now need to update the text "Matthew, Amandine and...." such that it matches the avatars. WhoIsTyping in react-sdk will need adjusting.

**Comment by ara4n** [comment]
@lukebarnard1 can this be closed up yet?

**Comment by lukebarnard1** [comment]
Yes, it can indeed.
