### ISSUE TITLE
3PID invite not being resolved correctly to a normal invite

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2276]
Yaniel says:

> I created a room and invited someone by email address
> now I do see their join event and avatar change
> but it shows as a rejoin
> and the invite is still there
> and they don't show in the room list
> my friend on matrix.org does see everything fine though
> how should I unwedge this?
> hm after reloading they show up in the list, but the invite is still there
> so uh, essentially "how do I remove invites?"

**Comment by dbkr** [comment]
Whilst trying to repro this, I have found https://github.com/vector-im/riot-web/issues/3505

**Comment by dbkr** [comment]
I can't repro this

**Comment by lampholder** [comment]
We can't reproduce this, so closing. We can always reopen if more evidence comes to light.
