### ISSUE TITLE
Too many ellipsises icons in room list

### ISSUE THREAD

**Issue by WGH-** [vector-im/riot-web#2288]
There're two "three dots" buttons in room list per room.

First one manages "direct chat" status, favourite, etc, and the second one manages notification settings.

I think this is a bit too much, and just clutters the UI. One would be sufficient.

![test](https://cloud.githubusercontent.com/assets/1099351/18637012/07a0fa0a-7e9c-11e6-9691-9dab4ef196c6.png)

**Comment by ara4n** [comment]
agreed that we've end up with too many ellipses. @antikewl: what do you think about merging the context menus?

**Comment by lukebarnard1** [comment]
Closing since https://github.com/vector-im/riot-web/pull/3395 & https://github.com/matrix-org/matrix-react-sdk/pull/746 merge the context menus
