### ISSUE TITLE
Emote + leaving combo breaks RRs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2298]

**Comment by ara4n** [comment]
<img width="992" alt="screen shot 2016-09-19 at 17 40 18" src="https://cloud.githubusercontent.com/assets/1294269/18649925/36e86bb0-7e90-11e6-96f7-2556e23d93ad.png">

**Comment by ara4n** [comment]
can probably be fixed with proper emote artwork

**Comment by turt2live** [comment]
Seems to be related, if not the same as, #3128

This one was reported first however...

**Comment by turt2live** [comment]
This seems fixed by https://github.com/vector-im/riot-web/issues/3742
