### ISSUE TITLE
tadzik says demoting rooms to low prio doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2310]

**Comment by ara4n** [comment]
can't reproduce this - @tadzik, any idea what you were seeing?

**Comment by tadzik** [comment]
Here's the video :) https://tadzik.net/pub/riot.mp4

**Comment by turt2live** [comment]
Video 404's and no one else has mentioned this since 2016 - closing. If it continues, please open a new issue.
