### ISSUE TITLE
Option to only send encrypted messages to verified devices

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2313]
Probably at the per-room level. Shared across all users, or per-user?

**Comment by vext01** [comment]
We've just discussed this very issue.

It worries me that an unverified party can silently intercept encrypted messages undetected.

**Comment by vext01** [comment]
And this is not a bug unique to vector-web

**Comment by ArdaXi** [comment]
I would suggest having this per-user. Primarily because it empowers the user to increase security for their own messages without having to have the necessary room privileges.

Would be nice if this were supported for the entire room as well, but that's a Matrix spec issue too.

**Comment by ara4n** [comment]
Just to confirm: this is very much on our radar, but we're also having to juggle all other issues coughed up by the beta - i.e. the Unknown Inbound Session ID bugs, verifying devices, and giving folks the ability to backup & restore E2E state.  It will be coming RSN, and yes, it does pose a serious issue (as do the others).

**Comment by ara4n** [comment]
i did this.
