### ISSUE TITLE
Network tag is always Riot in the user search

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2319]
When I want to invite a user to chat, I see users from other networks in the search result but they have the Riot logo instead of their network one. you can search for 'aman' and in the middle of all my test accounts there is my slack user and a rocketchat user

![image](https://cloud.githubusercontent.com/assets/8582858/18686924/ca53cf96-7f4b-11e6-9737-27582cd29553.png)

**Comment by ara4n** [comment]
See also https://github.com/vector-im/vector-web/issues/1508

**Comment by ara4n** [comment]
we have killed the R logo for now.
