### ISSUE TITLE
#/login link doesn't work on riot.im page

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2337]

**Comment by Matrixcoffee** [comment]
Clarification: Typing `https://riot.im/develop/#/login` into the URL bar directly, or following the "door" link on the front page (`https://riot.im/app/#/login`) takes you to the Directory rather than the Login page.

**Comment by BenfLewis0** [comment]
....likewise having #/register work would be very useful too...

**Comment by lukebarnard1** [comment]
It seems that guest login skips to the directory. Directory should be the default, but if a path is specified it should go to that path as a guest.
