### ISSUE TITLE
Should adding an a room alias into the directory change the m.room.aliases event?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2369]
I am very unclear as to why we ever echo the aliases put in the directory into the `m.room.aliases` event.  What does the `m.room.aliases` event even do?

**Comment by ara4n** [comment]
@erikjohnston - can you please remind me how this is meant to work?  Is `m.room.aliases` purely to advise humans of other aliases where they can find this room?  Can't we handle that OOB instead to avoid abuse?

**Comment by ara4n** [comment]
This is fairly urgent now we let anyone set aliases on a room.

**Comment by erikjohnston** [comment]
> Is m.room.aliases purely to advise humans of other aliases where they can find this room?

This, which was more important before we had the concept of a canonical alias

**Comment by ara4n** [comment]
@erikjohnston (or @richvdh), what do you think about killing it entirely? it seems to bring more risk of abuse than value...  Or possibly decoupling it entirely from the room directory, and requiring a power level to set it, so that admins can decide the official list of aliases they wish to endorse for a room?  (Or we could put that list in canonical aliases...)

**Comment by richvdh** [comment]
> @erikjohnston (or @richvdh), what do you think about killing it entirely? it seems to bring more risk of abuse than value... Or possibly decoupling it entirely from the room directory, and requiring a power level to set it, so that admins can decide the official list of aliases they wish to endorse for a room? (Or we could put that list in canonical aliases...)

lol, good ideas! If only someone would hurry up and [spec](https://github.com/matrix-org/matrix-doc/pull/2432) this

**Comment by richvdh** [comment]
this is now superceded by #12337 etc.
