### ISSUE TITLE
Riot makes it look like images are encrypted, even if they are not

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2371]
This would be less of a problem if we fixed #2262, but even then, it would be possible for a client to upload an image in the clear, and we shouldn't show the padlock for them.

**Comment by ara4n** [comment]
prioritising at p1 as i've had a bunch of people panic at me about this and it's an easy fix

**Comment by richvdh** [comment]
is the idea just to detect unencrypted attachments and show an open padlock?

**Comment by ara4n** [comment]
yes.

**Comment by aaronraimist** [comment]
Fixed
