### ISSUE TITLE
Make a 'talk on matrix' badge

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2373]

**Comment by masvil** [comment]
I'm pretty sure it will be one of the best way to spread the world Matrix.

**Comment by t3chguy** [comment]
and get the `[matrix]` stickers in a webstore somewhere (ME NEED MORE)

**Comment by ara4n** [comment]
See also https://github.com/matrix-org/matrix.to/issues/3 which also has some solutions

**Comment by rxl881** [comment]
FTR, I've asked @benparsons to have a look at collating some graphics that we can use for a basic [matrix] stickerpack, and we'll get them added to scalar asap.

**Comment by turt2live** [comment]
I think this is asking for https://shields.io/category/chat style badges? (which now exist, btw)
