### ISSUE TITLE
User pages let you close MemberInfo, leaving you in limbo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2386]
e.g.  https://vector.im/develop/#/user/@matthew:matrix.org is a blank MiddlePanel and a MemberInfo in the RHS. If you hit the close button on the MemberInfo you get stranded in a weirdly blank UI

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/3586 (you can't actually close them right now due to https://github.com/vector-im/riot-web/issues/10306)
