### ISSUE TITLE
self-demotion is broken

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2392]

**Comment by ara4n** [comment]
If I'm an Admin in a room, i don't see any options in MemberInfo to demote myself.

**Comment by richvdh** [comment]
It works through the API (or Matrix Console) - it's just a UI bug.

**Comment by t3chguy** [comment]
The dropdown is now available, but should warn you that the action is one-way

**Comment by dkasak** [comment]
I cannot find this dropdown. Which version of Riot did this get in?

**Comment by lpalgarvio** [comment]
never seen this on almost a full year of using riot.

**Comment by ara4n** [comment]
It was talking about:

<img width="232" alt="screen shot 2018-03-12 at 01 20 22" src="https://user-images.githubusercontent.com/1294269/37261344-983adea6-2593-11e8-8b5a-99c1f5c6be9f.png">

**Comment by turt2live** [comment]
This is fixed as of apparently forever ago, but definitely now too:
![image](https://user-images.githubusercontent.com/1190097/55435857-ff954880-5557-11e9-970c-6e17c240ad85.png)

(from a 1:1 created moments ago, where the user shown is logged in and definitely admin)

**Comment by hex-m** [comment]
I would assume to find this under "Room settings" in "Roles & Permissions". It's extra confusing as you see that you are admin/privileged there but the drop-down is deactivated - visually indicating that you don't have permissions to change this setting.

Also, the implemented solution only works for users with the power level `100` (admin) which feels inconsistent. related: https://github.com/matrix-org/matrix-doc/issues/940
