### ISSUE TITLE
Login as email is case sensistive

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2396]
trying to login by typing my valid email address but with a capital letter returns invalid username/pwd error. Email consideration shouldn't be case sensitive

**Comment by slang800** [comment]
But local part of email addresses _are_ case-sensitive, right?

From RFC 5321, section-2.3.11:

> The standard mailbox naming convention is defined to be "local-part@domain"; contemporary usage permits a much broader set of applications than simple "user names". Consequently, and due to a long history of problems when intermediate hosts have attempted to optimize transport by modifying them, the local-part MUST be interpreted and assigned semantics only by the host specified in the domain part of the address.

I could see a case for correcting the email address if we know of exactly 1 existing user with a case-insensitive matching email, but we shouldn't just force emails to be lowercase or something like that.
