### ISSUE TITLE
LeftPanel behaviour improvements

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2403]
Based on brainstorming with @wmwragg we have a few possible directions to iterate on LeftPanel:
- We could split it into a bunch of separate sublists, each individually scrollable, dragging the separators to adjust the balance of sublists... but the UX of dragging the separators could be quite icky.
- Kill the sublists entirely but bubble mentions to the top, prioritising 1:1s.  (Could even kill Favs & Low Prio for simplicity)
- Hide non-active rooms entirely (relying more on filtering to find them)

**Comment by ara4n** [comment]
Autofavouriting could help too.

**Comment by wmwragg** [comment]
Perhaps pinning rather than favouriting, so pinned rooms always at the top

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-meta/issues/96

**Comment by turt2live** [comment]
> We could split it into a bunch of separate sublists, each individually scrollable, dragging the separators to adjust the balance of sublists... but the UX of dragging the separators could be quite icky.

Sounds like we finally picked this option. Further improvements to come with #8531 and co.
