### ISSUE TITLE
would be nice to be able to click on a quote and jump to the quoted message

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2409]

**Comment by ara4n** [comment]
The "quote" button in the context menu should track metadata somehow to say who what you're replying to - a basic form of threading.

**Comment by AmandineLP** [comment]
"yes, like in telegram :/ It shows the original author + allows you to click to jump to the message for further context  - also it would be nice if it alerted like telegram
https://public.etherpad-mozilla.org/p/riot_complaints

**Comment by t3chguy** [comment]
closing in favour of #3571
