### ISSUE TITLE
Changing the default HS/IS in settings.json doesn't take effect unless you clear local storage

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2412]
We should only persist /custom/ HS/IS in local storage, so that if folks change the default it takes effect. I thought this already works, but https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$147559705037BLKbj:matrix.wirebug.ch suggests otherwise

**Comment by turt2live** [comment]
We changed this such that we don't store this outside of a session anymore, so it should work now.
