### ISSUE TITLE
Read receipt badges : "show more" feature isn't consistent to the number of badges

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#2414]
When it's possible to expand the read receipt badges (more than 5) :
- For example when there is "2+" next to the badges, I'm expecting 2 more badges beind added to the list.
  There is 1 less added to the list each time. A blank one seems to replace the place occupied by the expand icon (2+).

Before expanding:
![see viewvers_before](https://cloud.githubusercontent.com/assets/22364949/19113528/6045e04c-8b0a-11e6-857d-a7b701ff5dfe.png)
After :
![see viewvers_after](https://cloud.githubusercontent.com/assets/22364949/19113531/6268b5a2-8b0a-11e6-9407-b33c07c2ff60.png)

**Comment by pafcu** [comment]
@jeangb This seems to have been fixed

**Comment by pafcu** [comment]
@lampholder This seems to be fixed. Could be closed?

**Comment by uhoreg** [comment]
Seems to be fixed.
