### ISSUE TITLE
Per-room notification control button gets stuck visible

### ISSUE THREAD

**Issue by leonerd** [vector-im/riot-web#2420]
If I click the mouse too quickly on the room list to switch between lots of rooms, sometimes the little grey "notification control menu" button gets stuck and doesn't hide. See screenshot. The mouse (not captured) is currently over the "Matrix Internal" name having recently been clicked in other places like #matrix-dev and [Gitter AS Admin].

Simply hovering the mouse over the names is enough to dismiss them. Also if I click room names slowly enough, it doesn't happen. It seems related to whether I move the mouse out of the room's name area before it's finished loading the timeline view, or something around that nature.

![riotweb](https://cloud.githubusercontent.com/assets/350941/19119469/c2d04e84-8b17-11e6-85dd-fcd5546cc580.png)

(Browser: Firefox 45.3.0)

**Comment by leonerd** [comment]
Furthrmore this appears to be a Firefox-specific bug as it doesn't happen for me on Chrome.

**Comment by leonerd** [comment]
Still happening having upgraded to Firefox 49.0

**Comment by ara4n** [comment]
this is a fun fun race between JS & CSS i think.

**Comment by jcgruenhage** [comment]
This is easy to reliable reproduce in i3, not only on Firefox, but the desktop app too:
 - click on a room, then don't move the mouse
 - switch to a different workspace
 - move the mouse away
 - return to the workspace containing riot
Et voilà, you have a stuck menu button.

**Comment by uhoreg** [comment]
Copied the labels from #3672.  Also removed the platform specific label, since it doesn't seem to be platform specific (I can reproduce it in the desktop app).

**Comment by MTRNord** [comment]
Can reproduce in Firefox Quantum Windows 10 but at random times. With Touch and touchpad and mouse as input

**Comment by lukebarnard1** [comment]
I can't seem to reproduce this. Is anyone still experiencing this issue?

**Comment by jcgruenhage** [comment]
The i3 reproduction I've posted above does not work anymore, but I've found another way to reproduce it:

 - Have the mouse hover over a room
 - have the room change position because someone sent a message

The button is stuck again.

**Comment by jfrederickson** [comment]
I can still reproduce. Easiest way for me is to click a room, then move the mouse away before it finishes loading.

**Comment by t3chguy** [comment]
I still get it fairly frequently on desktop build on Windows

**Comment by turt2live** [comment]
are people still seeing this case today? I can reproduce https://github.com/vector-im/riot-web/issues/1997 easily but this one is a lot harder.

**Comment by jfrederickson** [comment]
Just checked and I'm no longer able to reproduce this one.

**Comment by jcgruenhage** [comment]
I haven't seen it in a while either

**Comment by turt2live** [comment]
Considering this fixed then. If the issue persists, please open a new issue.
