### ISSUE TITLE
/commands should work with additional information inserted by autocomplete so they work with display names (with linked mxids as well)

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#2426]

**Comment by lukebarnard1** [comment]
This is actually done by auto-completing the command and _then_ auto-completing the user. Not sure what "so they work..." means.

**Comment by t3chguy** [comment]
@lukebarnard1 I think its because commands just want an MXID, but autocomplete completes to Display Name (MXID?)

**Comment by lukebarnard1** [comment]
Oh right, of course. Maybe the `CommandProvider` could give different completions for the parameters that follow the commands themselves.

**Comment by lukebarnard1** [comment]
This does not look like it's fixed by #1890 because:
https://github.com/matrix-org/matrix-react-sdk/pull/1890/files#diff-fa2e6c7a24d3ee8c284aa720b8f399edR989

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
