### ISSUE TITLE
Implement custom welcome pages (was: improve room discovery process for new users)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2430]
Especially on mobile, folks need a better on-ramp to use the app.  Being presented with the full roomdirectory is overwhelming for non-geeks.  And discovering other people to talk to is a mess too

**Comment by ara4n** [comment]
Unsure how this should work.  Options include:
 * Tutorial (#1631)
 * Curated RoomDirectory subsets for particular groups or servers
 * The vector-bot idea (#1864)

**Comment by ara4n** [comment]
actually,  a really simple solution might be just a MOTD for the server: a chunk of HTML to handle both 'welcome to the server' as well as legal crap, links to popular rooms, etc.

**Comment by Zenexer** [comment]
How about tags or categories?

**Comment by ara4n** [comment]
The plan at the moment is to have the "welcome page" idea, which I started on  https://github.com/vector-im/riot-web/pull/2575 but needs to be finished.

**Comment by ara4n** [comment]
I think we can enhance this by also having a dropdown when you log in to pick from a set of 'teams' (as configured by config.json), which can have different welcome pages.  We could also define regexps to lock teams to requiring certain valid email addresses to participate (e.g. you need a valid @cam.ac.uk address to participate in a Cambridge team).  In the absence of groups in matrix in general this would hopefully be adequate, and is needed for the "Riot for Students" idea.
