### ISSUE TITLE
Option to autoplay animated GIFs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2433]
We might even want to turn it on by default :S

**Comment by chron0** [comment]
Oh, yeah, we're currently trying to move from slack to matrix/riot, but our users seem to deem this a very important feature and don't want to hover/click to see animations from giphy/etc. so they stick with slack because of something like this...

**Comment by Half-Shot** [comment]
*is working on this*

**Comment by Half-Shot** [comment]
@ara4n This can be closed now :)

**Comment by ara4n** [comment]
thanks! :D

**Comment by chron0** [comment]
Yeah, thanks a lot, looking forward to testing it

**Comment by sparky-raccoon** [comment]
Hi guys, I was wondering, is it finally a way to enable autoplay video and GIFs as default for a very first time login ? Seems it's not like that.

**Comment by t3chguy** [comment]
It's a per-user option that cannot be forced upon people

**Comment by sparky-raccoon** [comment]
What if we wanted to force autoplay ? Where is the default value (enabled/disabled) set? Just asking for hints ;)

**Comment by MTRNord** [comment]
@sparky-raccoon atleast in develop (I don't use /app) there is a option in the settings menu

**Comment by t3chguy** [comment]
@sparky-raccoon 
https://github.com/matrix-org/matrix-react-sdk/blob/9e0aca534c0be130dbf442c36227872770c29916/src/components/views/messages/MImageBody.js#L84
and
https://github.com/matrix-org/matrix-react-sdk/blob/aef0a8025ca2c94c2a52c823d9bc7d4825b52e15/src/components/views/messages/MVideoBody.js#L155

(for Gifs and Videos respectively)

**Comment by sparky-raccoon** [comment]
K, thanks !!!

**Comment by BloodyIron** [comment]
This doesn't seem to work for gifs that are hyperlinked (URLs) as opposed to uploaded. :( Seems like a silly limitation. Any chance we could get this adjusted please?

**Comment by t3chguy** [comment]
Hyperlinked gifs are url previewed by synapse, so it's not merely an adjustment but requires both server and client changes

**Comment by alexiirj** [comment]
when using photoshop to export, choose loop forever

**Comment by naimesedzou** [comment]
I'll add this elsewhere, but, in addition to an auto-play option for videos and GIFs, I think the option to turn on auto-loop would be useful (Telegram does this).  If nothing else, it permits the use of far-more efficient video formats as substitutes for GIF, saving server space and providing a better user-experience.

**Comment by aaronraimist** [comment]
@naimesedzou https://github.com/vector-im/element-web/issues/4546
