### ISSUE TITLE
Support for notifying everyone in a room

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2440]
We need to define the semantics for this (https://matrix.org/jira/browse/SPEC-352)

**Comment by ara4n** [comment]
Suggest that we support defining a list of custom notifications per-room that folks can opt-in/out of.  Unsure how that opt-in/out would actually work though.

**Comment by t3chguy** [comment]
@room is now a thing

**Comment by vsund** [comment]
Who's allowed to use this in a room? Admins, moderators?
Also I couldn't find a setting to manage who's able to use this. Would be cool to have a setting for this :)

**Comment by ara4n** [comment]
@vsund power level 50 or higher (i.e. admins or moderators).  Agreed that this should be configurable - have filed https://github.com/vector-im/riot-web/issues/5835
