### ISSUE TITLE
Background Colours for Messages

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2460]
Originally https://github.com/matrix-org/matrix-react-sdk/issues/380; @lukebarnard1 says:

Background colours for messages would be a useful addition to the matrix web interface because some bridged systems support this functionality, namely IRC. This can be problematic when an IRC message is sent across which has white text and a black background. The text could become difficult to read when against the potentially light background of a matrix client. 

A suggestion is to modify the HTML sanitation of `<font>` tags so that

``` html
    <font color="white" data-matrix-bg-color="black">Hopefully visible text</font>
```

is transformed into

``` html
    <font color="white" style="background-color:black;">Hopefully visible text</font>
```

whilst checking for CSS injection of the provided bg-color.

Given that CSS injection needs to be checked for anyway, perhaps a better solution would be to accept the `style` attribute and only allow `color` and `background-color` attributes to be allowed. `http-sanitize` sadly doesn't support this functionality, but it could be written separately.

Sanitization within matrix-react-sdk:
https://github.com/matrix-org/matrix-react-sdk/blob/24223ae2b69debb33fa22fcda5aeba6fa93c93eb/src/HtmlUtils.js

(See https://github.com/matrix-org/matrix-appservice-irc/issues/62)

**Comment by taw00** [comment]
Related to <https://github.com/vector-im/riot-web/issues/2300> and <https://github.com/vector-im/riot-web/issues/2865>

**Comment by lukebarnard1** [comment]
This issue is mostly for tracking per-message background colours for messages.
