### ISSUE TITLE
UX for removing multiple devices is awful

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2464]
You have to type in your password for every single one

**Comment by richvdh** [comment]
One solution to this might be a "delete multiple devices at once" API (with tickyboxes to select the ones to delete in Riot): proposed at https://docs.google.com/document/d/1LaA9Q96ytumLmE-eAscONMMX5rE26ri4G7uj-rmltbs/edit#

However there is also a suggestion of a "sudo mode", which lasts for a few minutes. That would obviously be more involved.

**Comment by Mikaela** [comment]
I would like removing multiple devices (or even all of them at the same time) as the devices (especially browsers) get logged out randomly and when desktop client comes it will be fun having to click all dozens of devices separately to only have the desktop client devices listed.

**Comment by ara4n** [comment]
i fixed this.
