### ISSUE TITLE
Can't delete devices on systems with  CAS/SAML login or custom login types

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2465]
User-interactive auth doesn't support CAS, which is the main stumbling-block here.

**Comment by richvdh** [comment]
The current behaviour is that you get a modal error saying:

> Error
> No appropriate authentication flow found

**Comment by aaronraimist** [comment]
Going to close in favor of the modern Mozilla issue #12028.

(Wow I did not realize this bug was so old :/)
