### ISSUE TITLE
Unread message bar should include the contents of the most recent message of the room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#247]
Rather than just saying "2 unread messages" or whatever it should say "2 msgs: <Matthew> and another thing..." - i.e. including the most recent message in the alert, so that if you're scrolled up the page you still have a way of tracking how the conversation is proceeding.

**Comment by dbkr** [comment]
This is counter to the current wireframes so it might be worth making a note on the wireframe that it's inaccurate. Also presumably this will include the sender's display name?

**Comment by ara4n** [comment]
Yes, this is counter to the current wireframes/assets and a feature 
request from yours truly.  I'll see if we can get assets for it.

**Comment by AmandineLP** [comment]
it would really make me sad to have yet another type of notifs and it would make the bar terribly busy.

Another option would be to enable desktop notifs when scrolled up. but I would wait for the full read marker spec to be implemented, see if it really feels missing and/or poll users.

**Comment by turt2live** [comment]
We ended up replacing the whole thing with a circle, so closing this.
