### ISSUE TITLE
Mentioned message isn't highlighted anymore

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#2470]
I noticed that a message mentioning my username isn't highlighted anymore. (Jean: blabla). This message is highlighted in the mobile application.
Plus, the same kind of message is still highlighted upper.
Adress for the room is : #RennesConnection:matrix.org
Room's internal id is !GzvmKcFNOiOmXzAQgi:matrix.org.

This the no more highlighted message:
![webclient_non highlited message](https://cloud.githubusercontent.com/assets/22364949/19392548/7a65c586-9231-11e6-92b6-b48eb2927515.jpg)
If i reach back a bit in the top in the same room, the same kinds of mention are highlited:
![webclient_highlited message](https://cloud.githubusercontent.com/assets/22364949/19392615/d045af3e-9231-11e6-8328-c6ea29f08591.jpg)

**Comment by ara4n** [comment]
might be related to #2493

**Comment by clopez** [comment]
I can confirm this bug.
I not longer see in different color the messages where my nickname is wrote.
Very annoying

**Comment by clopez** [comment]
I don't this bug is minor, it breaks an essential functionality.  I have to scroll up and read everything to find where my name is instead of just going directly to the message with different color

**Comment by aaronraimist** [comment]
Probably fixed?

**Comment by turt2live** [comment]
There's still cases where it happens, although those instances are poorly documented and largely ignored by users :(

**Comment by aaronraimist** [comment]
either https://github.com/vector-im/riot-web/issues/3818 or this can probably be closed then, both are basically the same

**Comment by turt2live** [comment]
ah, yes, indeed. Closing in favour of https://github.com/vector-im/riot-web/issues/3818
