### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by agilob** [vector-im/riot-web#2484]
Would like to get support for GitLab.com integration which would be the same as GitHub integration

**Comment by svoop** [comment]
Please add the integration for any GitLab server (gitlab.com or self-hosted on a different domain). After all, the ability to self-host GitLab is one of the biggest pros compared to GitHub etc.

**Comment by svoop** [comment]
I guess, this integration is primarily a go-NEB task, see https://github.com/matrix-org/go-neb/issues/127

**Comment by t3chguy** [comment]
closing in favour of https://github.com/matrix-org/go-neb/issues/127 as it is a go-NEB task

**Comment by beedell-roke** [comment]
@t3chguy, that repository has since been archived.
