### ISSUE TITLE
Riot doesn't take into account my french accents shortcuts done on a qwerty keyboard

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2492]

**Comment by dbkr** [comment]
How are you entering these accents? Where are they not taken into account? In the message composer? In the timeline? When do accents work for you?

**Comment by ara4n** [comment]
@AmandineLP need more info... i use accents on qwerty all over the shop in Riot successfully (on OSX)

**Comment by AmandineLP** [comment]
I have an american keyboard
it fails when I use shortcuts like Ctrl+' then e 
That said it fails here too....

**Comment by richvdh** [comment]
This feels more like an OS/browser issue than anything we want to try to fix in the webapp? Trying to pick up ctrl-' as an accent key sounds like it will cause more problems than it will solve.

alt-gr-' e gives me an ê here...

**Comment by richvdh** [comment]
I'm going to close this, as I don't think it's something we want to do.
