### ISSUE TITLE
monitoring on coturn

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2501]
to trap the failure mode of livelocking

**Comment by leonerd** [comment]
If it writes a PID file somewhere we can easily throw the prometheus `process_exporter` onto it. I've been gathering more process stats there lately; should be easy enough to have a generic "This process has been spinning 100% CPU for a while" alert that way.

**Comment by ara4n** [comment]
i'd assign it to @leonerd if he joined the team :) leo - can you self-assign when you get here please?

**Comment by leonerd** [comment]
It turns out `turnserver` does write a PID file, and I've had `process_exporter` watching it most of the week now.

https://grafana.openmarket.com/dashboard/db/matrix-all-processes?var-job=turnserver

The generic `ProcessSpinning` alert will also warn of high CPU usage.

**Comment by ara4n** [comment]
okay, hopefully this will be good enough. @leonerd, please do make sure the alert goes somewhere that someone will see it...

**Comment by Varindakhanna** [comment]
is there any grafana dashboard for coturn?
