### ISSUE TITLE
show room avatar full-size

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2502]
there doesn't appear to be a way to see the room avatar in big

**Comment by ara4n** [comment]
click-on-avatar to zoom in lightbox seems desirable, much like for user avatars

**Comment by t3chguy** [comment]
is this wanted when clicking on the RoomHeader RoomAvatar, instead of it sending you into RoomSettings?

**Comment by ara4n** [comment]
thanks @aidalgol!
