### ISSUE TITLE
RoomList filter should search aliases as well as room names

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2557]

**Comment by grahamperrin** [comment]
[Room filtering in dir should search names, topics as well as aliases · Issue #974 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/974) (2016-02-21)

**Comment by t3chguy** [comment]
It does this now
![image](https://user-images.githubusercontent.com/2403652/79108293-f2678800-7d6d-11ea-85b2-f7b1c78fba63.png)
