### ISSUE TITLE
Back-pagination spinner gets stuck after using Purge History API in synapse

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/riot-web#2566]
not sure if synapse or vector-web bug.

![scrot-1478804473](https://cloud.githubusercontent.com/assets/7166727/20190130/dbacbd92-a788-11e6-9730-530c183c8639.png)

**Comment by richvdh** [comment]
It's trying to back-paginate. Is this in a federated room, or one that only exists on your server?

**Comment by 4nd3r** [comment]
only in my server

**Comment by richvdh** [comment]
sounds like a synapse bug then. Do you get the same behaviour after reloading riot?

**Comment by 4nd3r** [comment]
has been spinning for days now, so yes.

**Comment by richvdh** [comment]
Yup, repeated here; synapse is returning 500 errors. Raised https://github.com/matrix-org/synapse/issues/1623.

**Comment by 4nd3r** [comment]
thanks

**Comment by richvdh** [comment]
Let's keep this open to track it from the application side.

**Comment by babolivier** [comment]
We realised today that https://github.com/matrix-org/synapse/issues/1623 had been fixed (just hadn't been closed at the time), should we also close this issue?

**Comment by turt2live** [comment]
I think this is now waiting on https://github.com/matrix-org/matrix-doc/issues/2251 to be fixed so we can fix the infinite spinner problem.

**Comment by babolivier** [comment]
@turt2live Right, but is that infinite spinner problem really still a thing though? I've just tried to reproduce it by creating a room on my local HS (unfederated), sending multiple messages in it, purging the history from one of these messages, and hitting "Clear cache and reload" in Riot. Once the room was loaded by Riot, it apparently tried to back-paginate events before the oldest event not purged, and when `/messages` returned with an empty chunk (`[]`) it stopped hitting that endpoint and showing a spinner.

**Comment by turt2live** [comment]
Hmm, indeed. Closing this as fixed.
