### ISSUE TITLE
support optionally automatically converting :P into 😛 etc

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/riot-web#2567]
translate :P :D :) :| etc to emojis

**Comment by aperezdc** [comment]
One of the things I like about Riot is that

> `scp foo.png host:public_html/`

does _not_ get translted into

> `scp foo.png host` :stuck_out_tongue: `ublic_html/`

Automatically translating the first into the second is something I am definitely _not_ looking forward to. If anything, automatic translation should be either 1.) an opt-in setting, or 2.) undoable.

**Comment by ara4n** [comment]
this can be handled nicely in RTE by offering the emoji as an autocomplete option - which is hiding in https://github.com/vector-im/vector-web/issues/1761#issuecomment-252036883

**Comment by ara4n** [comment]
(closing as dup)

**Comment by 4nd3r** [comment]
> scp foo.png host :stuck_out_tongue: ublic_html/

this is a classic case of shitty regex. we have `\s` and `\b` for this kind of cases.

**Comment by ara4n** [comment]
this comes up fairly regularly as people ask if we can automatically do the substitution... as an option.  so reopening this to be the canonical bug for that.

**Comment by jasuarez** [comment]
> One of the things I like about Riot is that
> 
> scp foo.png host:public_html/
> does not get translated into
> 
> scp foo.png host :stuck_out_tongue: ublic_html/
> 

One way to avoid this could be if the conversion is done only if there's a white before the emoticon. I think that would solve 95% of cases.

We could also request another white after the emoticon, or an EOL.

**Comment by simm3** [comment]
I'd also like to suggest a "mapping" feature. Most of the emojis are very ugly (at least in Chrome under Linux). Also most (if not all) emoticons are not animated.

So it would be nice if there could be an (optional?) mapping between emoticon code and emoticon URL. Example emoticons: http://www.smiley-paradies.de/animierte-smileys/liebe.html

So one could write :dance: (or whatever the code is) and will see this emoticon: http://www.smiley-paradies.de/smileys/tanzend/tanzend_0014.gif

**Comment by lukebarnard1** [comment]
So this is done but is slightly buggy but stuff like `:) *tab*` results in :smiley: and `<3 *tab*`, :heart: etc.

**Comment by kethinov** [comment]
Would be nice to:

- Map the defaults better (e.g. how hangouts does it)
- Have a setting to do it automatically (without having to force it using tab)

Should we file a separate issue for that?

**Comment by lukebarnard1** [comment]
@kethinov two separate issues for those would be much appreciated, and a quick description of how hangouts does it would be great

**Comment by kethinov** [comment]
- https://github.com/vector-im/riot-web/issues/4553
- https://github.com/vector-im/riot-web/issues/4554
