### ISSUE TITLE
unverify and block buttons are not properly aligned

### ISSUE THREAD

**Issue by elopio** [vector-im/riot-web#2580]
When I click my user name in the right bar of a room, two buttons appear: unverify and block. These two buttons are not horizontally aligned:
![ekrankopio de 2016-11-14 22-33-07](https://cloud.githubusercontent.com/assets/617831/20293293/b5a96a66-aaba-11e6-8753-b55e3e71dd53.png)

I'm using ubuntu zesty, firefox 49 and https://riot.im/app/

**Comment by richvdh** [comment]
@elopio: that's not our standard stylesheet. Are you using a custom userstyle?

**Comment by elopio** [comment]
@richvdh I don't think so. As far as I remember, this was the first time I opened riot.im in this machine, in this browser. How can I check the stylesheet I'm using?

**Comment by richvdh** [comment]
If you haven't deliberately installed a custom stylesheet, I'd guess it's a browser extension doing something weird. Do you see the same from an incognito window?

**Comment by elopio** [comment]
This is from firefox in private mode, in the same machine
![ekrankopio de 2016-11-17 20-56-55](https://cloud.githubusercontent.com/assets/617831/20417125/e3576dd2-ad08-11e6-9687-e7fe25af42dc.png)

**Comment by elopio** [comment]
This is from my chromebook machine, also ubuntu zesty but using chrome. The difference is not so obvious, probably because the screen is a lot smaller.

![ekrankopio de 2016-11-17 20-59-29](https://cloud.githubusercontent.com/assets/617831/20417154/1d5e2962-ad09-11e6-9f97-91c78addf8f8.png)

**Comment by richvdh** [comment]
Ah right. Actually I see the misalignment too, and the non-standard colours are probably coming from your room. Will add it to the list to investigate.

**Comment by elopio** [comment]
ah, yes, I made the room black.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/52824545-41d0fc00-3076-11e9-8976-e90ad242e4f7.png)

Fixed
