### ISSUE TITLE
long device names make the memberinfo too wide

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2582]

**Comment by richvdh** [comment]
![screenshot_2016-11-15_11-33-09](https://cloud.githubusercontent.com/assets/1389908/20304311/5b734cc0-ab27-11e6-894e-4cc616a5f5d4.png)

**Comment by turt2live** [comment]
Display names are https://github.com/vector-im/riot-web/issues/1023 (fixed)

However, long device names are differently broken now:
![image](https://user-images.githubusercontent.com/1190097/52824681-c58ae880-3076-11e9-9e86-e5800f187cef.png)
