### ISSUE TITLE
Inviting users is case sensitive

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#2586]
https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1479306533641067ARppi:matrix.org

**Comment by dbkr** [comment]
Turns out the problem is that user search is case sensitive

**Comment by ara4n** [comment]
i'm having problems reproing this... @dbkr, any idea?

**Comment by dbkr** [comment]
I think the problem here is that inviting a user (or starting a chat with them, if you don't already have an open chat room) is case sensitive, ie. create new room, hit 'invite to this room', entering "@test:localhost" is different to entering "@Test:localhost".

**Comment by dbkr** [comment]
ie. This is a dup of https://github.com/vector-im/riot-web/issues/617
