### ISSUE TITLE
Kicks and bans are taken to be leaves in MemberEventListSummary

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#2594]
Check that sender === target for summarised events

**Comment by jeangb** [comment]
@lukebarnard1 can you confirm that is the same issue: 
I withdrew invitations with riotuser9 (invited by user2) in a DM room.
I had this:

> riotuser9 left the room.
> riotuser9 withdrew riotuser1's invitation.
> riotuser9 withdrew riotuser6's invitation.
> riotuser9 withdrew riotuser2's invitation.
> riotuser9 withdrew riotuser3's invitation.

**Comment by lukebarnard1** [comment]
@jeangb: was this in the expanded form?

**Comment by jeangb** [comment]
@lukebarnard1 I think so:
![collapse events and bug of false left](https://cloud.githubusercontent.com/assets/22364949/20558803/233accba-b172-11e6-81bc-95495a130040.jpg)

**Comment by lukebarnard1** [comment]
Yep, OK thanks for the info! This helps a lot :+1:

**Comment by ara4n** [comment]
i'm not sure i understand this bug - do the screenshots so kicks, bans, withdraws or leaves?

**Comment by lukebarnard1** [comment]
The bug is caused by the fact that MemberEventListSummary assumes that a change in membership = a leave or a join and nothing else. Other events, however, including kicks, bans and withdrawals also have a change in membership.
