### ISSUE TITLE
Padlock icon in text entry area is in an inconsistent location.

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#2610]
In Revolt (WebKit-based Riot desktop app), the padlock icon is at the top of the text entry area
![selection_001](https://cloud.githubusercontent.com/assets/1012976/20463058/0771de68-aef9-11e6-90c5-23686ca614b2.png)
whereas in Firefox, the padlock icon is at the bottom of the text entry area
![selection_002](https://cloud.githubusercontent.com/assets/1012976/20463059/0777fa64-aef9-11e6-9ba1-0c9f6fe111aa.png)

**Comment by t3chguy** [comment]
I previously saw this issue myself, just tested it again and could not reproduce, will test on the machine that I first saw it on before marking it as such. @uhoreg could you test again pl0x

**Comment by uhoreg** [comment]
Nope, I still see the same difference between Firefox/Desktop and Revolt.

**Comment by lukebarnard1** [comment]
I can't see find a reason why different browsers would position it differently unless they don't all treat `top: auto` (which is implied by it not being here in this case). We could try adding `top:24px`, which doesn't make a difference in position for Chrome.

@uhoreg as you can repro, is there any chance you could see if adding `top: 24px` to the CSS for the padlock to see if it solves your problem?

**Comment by turt2live** [comment]
@uhoreg are you still seeing this in 1.0.0?

**Comment by uhoreg** [comment]
Nope.  Seems to be magically fixed by the redesign.
