### ISSUE TITLE
Support for large encrypted attachments

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2615]
The current implementation for encrypted attachments relies on data urls, which are only good up to 2MB. We need to add support for larger attachments

**Comment by NegativeMjark** [comment]
Chrome dies in odd ways when the URL is bigger than 2MB. https://bugs.chromium.org/p/chromium/issues/detail?id=69227

In particular it's fine to use the URL as the `src` of an `<img>` tag. But trying to use "Save As" or "Open in new tab" dies with a "Network Error".

**Comment by NegativeMjark** [comment]
This will probably be fixed by matrix-org/matrix-react-sdk#562

**Comment by ara4n** [comment]
this merged.
