### ISSUE TITLE
encrypted images mess up scroll position

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2624]
when the image loads, it changes the scroll offset in the window

**Comment by ara4n** [comment]
is this still the case with mark's new iframe-based image loading?

**Comment by richvdh** [comment]
Seems to be. 

On 25 November 2016 22:45:31 GMT+00:00, Matthew Hodgson <notifications@github.com> wrote:
>is this still the case with mark's new iframe-based image loading?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/vector-web/issues/2624#issuecomment-263029775

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lukebarnard1** [comment]
FTR, this is part of #2624
