### ISSUE TITLE
switch from open lock to struck-through-lock to show unencrypted

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2626]

**Comment by ara4n** [comment]
the problem being that 'open lock' can mean 'decrypted' rather than 'unencrypted'

**Comment by JasonLocklin** [comment]
Not sure if this should be a separate issue, but the lock should also be darkened, perhaps to black, to make it more obvious to the user that he is in an un-encrypted room, and make it far more readable on a small screen. 

It should also be clickable -and go straight to the encryption settings for the room.

**Comment by tuxayo** [comment]
>  but the lock should also be darkened, perhaps to black, to make it more obvious to the user that he is in an un-encrypted room, and make it far more readable on a small screen.

If it can help, here is a picture of how it show on my screen. It's taken with a potato but still shows the little contrasts with the background and small size of the lock.
![img_20161229_200124](https://cloud.githubusercontent.com/assets/2678215/21552450/eba7d26e-ce01-11e6-90a4-8518f43d61cf.jpg)

**Comment by uhoreg** [comment]
Is this issue regarding the lock icon next to the input box, or regarding the unlocked icon next to unencrypted messages in the timeline?

If it's the former, then #3317 also has some suggestions.

**Comment by uhoreg** [comment]
The room decoration has changed, so this issue is no longer relevant
