### ISSUE TITLE
Clicking on incoming call collapse sublist

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#2627]
To reproduce:
- Receive incoming call on a DM room (I don't think the category matters)
- Click on the incoming layout (don't click on accep or decline buttons)

This action collapse or de collapse the sublist.
vector-web version: v0.9.0
![incoming call layout collapse sublist](https://cloud.githubusercontent.com/assets/22364949/20521388/5575df70-b0ab-11e6-9932-73b4deedae38.jpg)

**Comment by ara4n** [comment]
fixed by be52787
