### ISSUE TITLE
vector releases page on github should surely show changelog, like synapse's does?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2632]

**Comment by dbkr** [comment]
There are 2 problems with this:
 1. The changelog generator appends to the changelog file, so we'd have to extract the latest entry (not hard)
 2. Most of the changes are actually in react-sdk

We could either somehow fix these problems, or make a more end-user digestible release notes which could be used both here and in text for the 'new version' bar.

**Comment by ara4n** [comment]
i'd assume we'd just grab the summary of js, react & vector changelogs for use in the vector release.

**Comment by kyrias** [comment]
Dupe of #1559?

**Comment by ara4n** [comment]
given the changelog is typically going to be blank for riot-web, i think we should reopen this until we aggregate in the matrix-react-sdk changes too.

**Comment by ara4n** [comment]
oh, you made https://github.com/vector-im/riot-web/issues/6613
