### ISSUE TITLE
Notification icon for channels

### ISSUE THREAD

**Issue by JasonLocklin** [vector-im/riot-web#2633]
When a channel receives a notification, the browser [tab] icon gains a little red (1). This is really nice. However, it's not always clear to which channel that notification belongs. 

The appropriate channel icon should also gain the same little red number, indicating the notification count for that particular channel.

**Comment by dbkr** [comment]
It should behave exactly as you describe: this is how it works for me. Presumably this is not working for you? Are you seeing any badges on the channels at all? What version of Riot?

**Comment by JasonLocklin** [comment]
On further review, I figured out that the problem is that there are, in fact, *no* current notifications, but the browser (firefox) has not changed the tab icon back. It's also not something I can consistently replicate. I'm going to close this issue, but if someone else can replicate it, feel free to re-open.
