### ISSUE TITLE
JS heap usage is leaking alarmingly and causing long-lived tabs to crawl

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2647]
I think this may be an artefact of the increasing number of E2E rooms, but on Chrome I got 6 minute's worth of "application unresponsive" warnings on unsleeping this morning interspersed with snatches of responsivity.  It finally recovered; here's the JS console:

[wedged-during-catchup.txt](https://github.com/vector-im/vector-web/files/612905/wedged-during-catchup.txt)

It's possible that the JS heap had grown so huge that Chrome was swapping, given that it's been trying to generate a JS heap snapshot for the last 4 minutes now and has only got 32% of the way there.....

**Comment by ara4n** [comment]
(except the chrome process in question is 'only' 2.4GB RSZ, and the box isn't swapping :/)

**Comment by ara4n** [comment]
rather splendidly, the Inspector crashes about 5 minutes into trying to generate a heapdump, so i have no clue what state Chrome's in here :(  Restarting...

**Comment by ara4n** [comment]
i think this is basically a memory leak - tabs which are older than a few days seem to be using *loads* of heap.

**Comment by ara4n** [comment]
i imagine this will be very problematic for electron too. may be related to #2109.

**Comment by richvdh** [comment]
let's not assume this is e2e until proven otherwise

**Comment by ara4n** [comment]
this is indeed just running out of heap, which is capped at 1.5GB on Chrome.  It's been improved by various bugfixes by kegan but it's still a problem because we simply never reap old events from memory.

**Comment by ara4n** [comment]
closing as a dup of #2951
