### ISSUE TITLE
Own history is not decryptable after moving from web to mobile

### ISSUE THREAD

**Issue by floviolleau** [vector-im/riot-web#2650]
Hello !

This just a general feeling. I prefer having a better UI or other features on the chat, like the possibility to edit my message, rather having a kind of E2E encryption which is for the moment unusable.

I ticked by mistake the checkbox of E2E encryption of a room and it messed up completely the room. What happens was like this:
- I talked on that room with my PC
- I finally go on my mobile and all the previous talk was said 'Encrypted message'... and I couldn't saw the messages I sent from my computer
- I send some message from my mobile and on my computer my mobile messages are 'Encrypted message'.

Finally I re-created from scratch a new room without this checkbox ticked.

Kind regards

**Comment by ara4n** [comment]
We'd rather get both UX & E2E working well ;)

To debug the E2E error, please can you confirm which version of the app you were using on mobile, and also what your device id is on the PC (you can see in Settings).  Thanks!

**Comment by croulibri** [comment]
Same problem !
It is not only our own history, but even messages from other users that are not readable. Using Riot F-Droid version 0.62 then 0.63
(same comment posted in Issue of "vector-Android")

**Comment by ara4n** [comment]
Closing this as there's a whole mix of different issues here and not enough version info to go on.  Please track the other label:type:e2e bugs.
