### ISSUE TITLE
changing password to one with non-ascii chars gives a 500

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2658]
apparently. Compare: https://github.com/vector-im/vector-web/issues/2538

**Comment by ara4n** [comment]
yup. this barfs for me on matrix.org with a 500 at login after changing my password to non-ascii.

**Comment by ara4n** [comment]
should be fixed by https://github.com/matrix-org/synapse/pull/1711

**Comment by lukebarnard1** [comment]
Tested, seems fixed
