### ISSUE TITLE
Can't accept, decline, or otherwise dismiss invites originating from a homeserver which no longer exists.

### ISSUE THREAD

**Issue by unknownloner** [vector-im/riot-web#2663]
My user on matrix.org is @dash:matrix.org

I received an invite from my friend while he was testing things, using the ID @Luna:aooki.link

Now the issue is, there isn't a homeserver running on aooki.link anymore. However, **there is currently a homeserver running on the IP address to which aooki.link points**. It's just configured to use a different domain (ukl.me). The matrix SRV records for aooki.link are still in place at this time.

Now, "accept" and "decline" both do two different things depending on if the server is running or not, neither of which is ideal:

### If the new server is **offline**

When I click on "accept" for the invite, I get the error message:

```
Failed to join room
Internal server error
```

When I click on "decline" for the invite, I get the error message:

```
Failed to reject invite
Internal server error
```

### If the new server is **online**

When I click on "accept" for the invite, I get the error message:

```
Failed to join room
Unauthorized
```

When I click on "decline" for the invite, I get no error message.
Instead, my client changes focus to a channel on the ukl.me homeserver (which as I mentioned earlier is currently running on the server which USED to be configured to host for the previous domain, aooki.link).

It's not clear to me if this is an issue with the web client, or the backend server, but I figure this is probably the most relevant place to put it since it's where the problem shows up.

**Comment by unknownloner** [comment]
UPDATE: The invite doesn't show up anymore now. I'm not really sure why; refreshing the page didnt fix it before.

**Comment by ara4n** [comment]
this is https://github.com/matrix-org/synapse/issues/1564 - going to close as a dup.  Thanks for all the additional detail though, which should help fix it there...
