### ISSUE TITLE
config.sample.json: no such file

### ISSUE THREAD

**Issue by xuhdev** [vector-im/riot-web#2665]
There is no such file `config.sample.json` as mentioned in the doc:

> If desired, copy config.sample.json to config.json and edit it as desired. See below for details.

**Comment by 4nd3r** [comment]
reported in #2607, fixed in 9ce2adceef2851ed2b262c4ed54bfae3e58c1e2f

for now copy it from repo.

**Comment by xuhdev** [comment]
Thanks.
