### ISSUE TITLE
Delete device button hides off to the right of the window

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2668]
... so people don't realise it's there.

![screenshot_2016-11-30_17-28-20](https://cloud.githubusercontent.com/assets/1389908/20763581/890db7d6-b722-11e6-8511-b273c9cff2dd.png)

**Comment by jeangb** [comment]
I agree I couldn't see it with the small resolution of my computer. The rest of the controls are responsive.

**Comment by aaronraimist** [comment]
Does't look like this anymore since 1.0
