### ISSUE TITLE
e2e voip calls don't work web<->ios & android

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2669]

**Comment by ara4n** [comment]
Anecdotal evidence suggests it's also broken on Android :(

**Comment by richvdh** [comment]
desktop as in electron or as in web?

**Comment by intelfx** [comment]
@ara4n I've probably just hit this. In my testing, calls are broken (established but silent) between web<->iOS if **BOTH** e2e is enabled **AND** TURN is used (i. e. no direct connection).

If I either use a room without e2e **OR** place the devices in the same (Wi-Fi) network, everything works.

**Comment by ara4n** [comment]
desktop as in web. sounds like it's a problem on the iOS side, at least.

**Comment by manuroe** [comment]
Fixed on iOS side with https://github.com/matrix-org/matrix-ios-sdk/pull/387
