### ISSUE TITLE
vector-web Image attachment previews are now stretched to fit the box

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#2673]
See https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$14805930092taBTn:kyriasis.com

**Comment by dbkr** [comment]
hmm, now I can't repro this

**Comment by ara4n** [comment]
other people can - e.g.: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1480934305118BRyjT:kyriasis.com

**Comment by dbkr** [comment]
Looks like this was caused by https://github.com/matrix-org/synapse/issues/1677
