### ISSUE TITLE
Disasterous performance on FF on rooms with large encrypted images

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2678]
In a room with several encrypted 3MB images, silwol reports that FF completely grinds to a halt until you move to a different room, pausing for ~30s on end.  Attached is a JS profile, and a screenshot of what it's doing.  It seems to be spending multiple blocks of 10s in PresShell::DeReflow(), and then over 3s actually painting.

<img width="2025" alt="screen shot 2016-12-01 at 23 39 52" src="https://cloud.githubusercontent.com/assets/1294269/20817564/7827faa4-b820-11e6-8260-74d6d9a9181e.png">

**Comment by ara4n** [comment]
this happens both on /app and /develop.

**Comment by ara4n** [comment]
i can reproduce this spectacularly with 3x 3MB images.

**Comment by ara4n** [comment]
see also #2866

**Comment by florianjacob** [comment]
Can reproduce with 2x 4MB images.

**Comment by ara4n** [comment]
should now be fixed at last by matrix-org/matrix-react-sdk#1864. feedback welcome!

**Comment by nailyk-fr** [comment]
Thanks! Sorry for stupid question but looks like those patches are only in `develop` branch. While clicking at the version number and read the commit history, looks like my client is not using it. 
How can I test the web-ui on develop branch please ?

**Comment by t3chguy** [comment]
@nailyk-fr try riot.im/develop

**Comment by nailyk-fr** [comment]
Many thanks. 
No way to compare with earliest performance. Scrolling and writing are now working damn fast. 

I sent a report through the webui some days ago about gif/videos playing making webUI unusable but looks like it fixed it too. 

Will test more but it is now really good! Many thanks for the fix!

**Comment by ara4n** [comment]
riot.im/develop :)

**Comment by nailyk-fr** [comment]
After more testing performance are just awesome. (not tried yet on my 10 years old laptop)
However am not able to tell if this patch or something else fixed it as I switched to `/develop` only yesterday. 

Thanks for reactivity... And many thanks for the apps !
