### ISSUE TITLE
Using SRV records instead of requiring custom server specification

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#2682]
I should be able to log in to Riot.im with username `madduck@madduck.net` or `@madduck:madduck.net` and expect the app to to a SRV lookup on the domain to figure out the homeserver to use. Expecting users to specify a string like `https://matrix.madduck.net:8448/` as "custom server" (which also requires several clicks and Javascript-roundtrips) is not particularly user-friendly.

**Comment by richvdh** [comment]
browsers don't support SRV lookups, so this is not possible. One option would be to support a .well-known file, which is tracked at https://github.com/matrix-org/matrix-doc/issues/433.

**Comment by jonas-hagen** [comment]
Would it be possible to use DNS-over-HTTPS? This specification attempts to solve exactly this problem. Possible providers would be [Google](https://developers.google.com/speed/public-dns/docs/dns-over-https) and [Cloudflare](https://developers.cloudflare.com/1.1.1.1/dns-over-https/).

Example:
`curl 'https://cloudflare-dns.com/dns-query?ct=application/dns-json&name=_matrix._tcp.matrix.org&type=SRV'`

Also see: [Mozilla Is Testing "DNS over HTTPS" Support in Firefox](https://www.bleepingcomputer.com/news/software/mozilla-is-testing-dns-over-https-support-in-firefox/) (it uses the 1.1.1.1 Cloudflare DNS server for DNS-over-HTTPS)

**Comment by t3chguy** [comment]
@jonas-hagen that means exposing your privacy to that provider. Plus the SRV is used only to specify the location of fed api and not client api, they don't have to be the same
