### ISSUE TITLE
autocomplete ordering seems to have regressed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2685]
the issue described in #1741 seems to have broken again - tab seems to return in a fairly random order rather than the last person who spoke in the room.

**Comment by dbkr** [comment]
I can't reproduce this: for me, pressing tab on the empty composer box brings up the last person who has an entry in the timeline and is not me.

**Comment by ara4n** [comment]
what happens if the person hasn't spoken recently enough to be in the timeline?  It then seems to go into random order rather than using presence data?  the regression is perhaps that our timelines are now weirdly tiny (#2752)

**Comment by turt2live** [comment]
I can't reproduce this
