### ISSUE TITLE
Remember last open room when closing Riot

### ISSUE THREAD

**Issue by jaragunde** [vector-im/riot-web#2688]
When I open the Riot web client, it always shows the room with the most recent messages, even if that room is a low priority one.

I think it would be better if it could remember and show the last open room when the client was closed, like it was "recovering the state" of the previous session.

**Comment by ara4n** [comment]
This has now changed on develop such that it always seems to load the directory when you relaunch the app.  It should still remember & re-show the last room you were on instead.

**Comment by jaragunde** [comment]
I see this has been part of the released versions for a while. Thank you very much! I'll close the ticket.
