### ISSUE TITLE
Email notifs are off by default?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2690]
The intention is that they are on by default (but easily disabled)

**Comment by ara4n** [comment]
someone claimed this to be the case; need to check

**Comment by mihaibujanca** [comment]
@ara4n I don't think this looks like a major bug, plus it's debatable whether having email notifications on by default is desirable or not

**Comment by ara4n** [comment]
looks like they're working again now, but were briefly broken. @mihaibujanca agreed that it's debatable, however it's also invaluable in case people sign up, forget about the app, and then someone tries to contact them. email notifs are the only way they'll get the msg.
