### ISSUE TITLE
Giphy Integration

### ISSUE THREAD

**Issue by Nolski** [vector-im/riot-web#2693]
Hi! I'm a long time IRCer and new user to riot/matrix and absolutely love it. 

I'd love to see a client integration that has a `/giphy` command option similar to the popular slack option. The way I was thinking it'd work is the user can input `/giphy {search query}` and riot will ping the [giphy api](https://github.com/Giphy/GiphyAPI#search-endpoint) and post the link to the gif. If the web.

The output would look similar to what is below
```
<nolski> | /giphy funny cat
<nolski> | http://media2.giphy.com/media/FiGiRei2ICzzG/giphy.gif
```

Maybe we can even parse for giphy commands and display them inline in the client? I'd be happy to work on this feature but I wanted to see what everyone thought of it before starting.

**Comment by ara4n** [comment]
It already exists :)  It's !giphy rather than /giphy though, and you 
have to add it via 'Manage Integrations' in riot-web in room settings. 
It's powered by 
https://github.com/matrix-org/go-neb/blob/master/src/github.com/matrix-org/go-neb/services/giphy/giphy.go

**Comment by Nolski** [comment]
Amazing! Thank you :)

**Comment by krrisis** [comment]
Cool, thx! Saw the bot but had to google to find (here) how it works, time for a good FAQ! :) 
Two things: 1) only works on mouse-over (why not always?) 2) Would be could ofc if it could now evolve, so that just like in slack you can choose between gifs and it doesn't choose for you.
It's the little things like these that stimulate user adoption.
Thx!

**Comment by krrisis** [comment]
Extra question: as the bot is a user, if you had it to a private conversation, this means the owner of the bot could actually read all these pvt conversations, right?

**Comment by skylord123** [comment]
@krrisis you can enable auto playing of gifs under your settings. It's called "Autoplay GIFs and videos". I actually prefer them playing on mouse hover so it starts from the beginning.

**Comment by kamisori** [comment]
Wouldn't a widget be a better giphy integration?

Type in your giphy query into the widget, the widget looks up gifs, then sends the chosen gif.

Is there a reason not to do that?

**Comment by t3chguy** [comment]
Absolutely none, an Integrations Manager could do it today and even make use of the new but unused Left Panel Widgets support.

![image](https://user-images.githubusercontent.com/2403652/105019885-8887b780-5a3e-11eb-9921-5c3c581caaf3.png)

**Comment by sascha-wi** [comment]
> It already exists :) It's !giphy rather than /giphy though, and you have to add it via 'Manage Integrations' in riot-web in room settings. It's powered by https://github.com/matrix-org/go-neb/blob/master/src/github.com/matrix-org/go-neb/services/giphy/giphy.go

Link leads nowhere.

**Comment by digitalextremist** [comment]
Stalled and recently ~closed~ locked: https://github.com/element-hq/element-meta/issues/321

**Comment by t3chguy** [comment]
@digitalextremist `Open` is a funny way of spelling `recently closed`

<img width="383" height="310" alt="Image" src="https://github.com/user-attachments/assets/9fae2fb5-2886-4c97-953d-7b306f9aecc4" />

**Comment by digitalextremist** [comment]
Correct, it is open. But closed to comments and locked:

<img width="562" height="43" alt="Image" src="https://github.com/user-attachments/assets/28a8e254-b1da-4390-a417-00305feb746e" />
