### ISSUE TITLE
scroll doesn't work in some tag names in room list

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#2696]
Scrolling the room list using the scroll wheel doesn't work when the mouse is over some tag names in the room list.  For example, in the screenshot below, the scroll wheel doesn't work when the mouse is in the outlined areas, but it does work when the mouse is over the "ROOMS" tag.  I'm guessing this is because the affected tags names are position: "fixed"
![selection_001](https://cloud.githubusercontent.com/assets/1012976/20896636/b05db89a-baec-11e6-966a-46135acd8262.png)

**Comment by turt2live** [comment]
(also happens on custom tags, ftr)

**Comment by turt2live** [comment]
the whole behaviour is different now
