### ISSUE TITLE
We should sign our releases.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2710]

**Comment by kyrias** [comment]
Random note off the top of my head: remember to post the public keys that are valid for signing each specific project in some official location that would not be vulnerable if the repo was hacked in some way.

A disturbing amount of projects forget to do this, making the signature literally worthless.

**Comment by ara4n** [comment]
yay, this is done now!

@dbkr: where is the public key published? is it https://riot.im/packages/debian/repo-key.asc?

**Comment by ara4n** [comment]
answer: https://riot.im/packages/keys

**Comment by kyrias** [comment]
Are they linked to from somewhere on the website? Hmm

**Comment by ara4n** [comment]
they will be

**Comment by richvdh** [comment]
we do sign our releases. See #3031 for linking the keys.
