### ISSUE TITLE
to_device message went missing from vdh->matthew with megolm session data

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2711]
```
2016-12-06 15:04:34.568 sharing keys with device @matthew:matrix.org:VACHRWKSRK
2016-12-06 15:04:34.568 Using sessionid 9Qn7CnpPkl4+GKsM1Wxry9SPNL8nF/FgbA2r8TOp8Nw for device @matthew:matrix.org:VACHRWKSRK
```

never made it through from vdh's riot-web to mine.

**Comment by richvdh** [comment]
annoyingly I've now left it long enough that all the logs have been rotated :/

**Comment by lampholder** [comment]
Do we have some logs available for this? Is it possible to make material progress with this issue, or is it waiting for a recurrence?

**Comment by ara4n** [comment]
waiting for a recurrence, unless richvdh thinks he's fixed a possible cause of to_device events going missing over federation somewhere along the line.

**Comment by richvdh** [comment]
I don't think I did anything that would fix it, but given this hasn't been seen for months, I vote for closing it.

**Comment by lampholder** [comment]
Agreed - we can always reopen if we see more instances.
