### ISSUE TITLE
Desktop App: Copy Link Location

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#2712]
We should implement a 'copy link location' option on the context menu for links. Seems like the most sensible (albeit still way more faff than it ought to be) way is to use: https://developers.google.com/web/updates/2015/04/cut-and-copy-commands

**Comment by uhoreg** [comment]
Electron also has its own clipboard API http://electron.atom.io/docs/api/clipboard/

**Comment by t3chguy** [comment]
What about for e2e files? Or would you only want this for decrypted files?

**Comment by fuzzy76** [comment]
Was this supposed to make it into a release? Still not seeing this in 0.12.2.

**Comment by t3chguy** [comment]
@fuzzy76 well I'm not sure where you're looking...
![image](https://user-images.githubusercontent.com/2403652/29924749-e3ff18be-8e55-11e7-94e3-14528207ff67.png)

**Comment by fuzzy76** [comment]
Sorry about that. I posted a comment about not finding it, and then deleted it when I _did_ find it. However, I had trouble finding it at first, but when I switched back it was there. I might have encountered an electron glitch or something.
