### ISSUE TITLE
Name list sometimes appears badly in desktop app

### ISSUE THREAD

**Issue by cjdelisle** [vector-im/riot-web#2717]
OSX 10.10.5 (macbook pro w/ Intel Iris Pro 1536 MB) running electron native app.
Unlike in chrome, the name list in a channel can render incorrectly when it has shifted up or down.
Image here: https://up1.xwikisas.com/#ahQkUWB2Pr3wu_I7zP2qsA

**Comment by dbkr** [comment]
0.9.1 has a newer version of electron: let's see if this helps

**Comment by ara4n** [comment]
@cjdelisle if you can test latest from https://riot.im/download/desktop that'd be fab

**Comment by cjdelisle** [comment]
Currently running: Version 0.9.1-rc.2 (0.9.1-rc.2)
Which is where I noticed the issue.

**Comment by ara4n** [comment]
0.9.1 was released on sat which may fix it?

**Comment by cjdelisle** [comment]
Oh I'm sorry, I just looked at https://riot.im/download/desktop/ and it was still pointing to rc-1, can you perhaps link me to the new dmg ?

**Comment by dbkr** [comment]
@cjdelisle Oops, sorry - they're now updated, or https://riot.im/download/desktop/install/macos/Riot-0.9.1.dmg for the new dmg directly

**Comment by cjdelisle** [comment]
Ok upgraded and the problem persists :(

**Comment by t3chguy** [comment]
can anyone reproduce?

**Comment by cjdelisle** [comment]
Seems fixed for me
