### ISSUE TITLE
Desktop App: add ability to Inspect Element

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#2718]
It would be nice to be able to do Inspect Element in the desktop app just like you can in a normal web browser.  If you don't want to confuse normal users with the feature, maybe it can only be available when developer tools is open.

**Comment by uhoreg** [comment]
Hmm... developer tools does have a button to click on an element to inspect, so maybe this isn't necessary.

**Comment by ara4n** [comment]
yup, @dbkr added dev tools, so you can now query from there.
