### ISSUE TITLE
GitHub bot isn't doing anything

### ISSUE THREAD

**Issue by kasbah** [vector-im/riot-web#2721]
Hey, thanks for working on riot.im! 

Not sure if this is the right place to report this but I added a GitHub bot to [my public channel](https://riot.im/app/#/room/#kitnic:matrix.org) and added a few repos to its settings but it doesn't seem to be doing anything at all. 

EDIT: When I first added it there were suddenly two GitHub bots and I booted one of them. I think the one I booted had the channel name in brackets in its own name.

**Comment by Kegsay** [comment]
As per the messages I left on that channel:
 - 2 integrations were added (Github commands and Github webhooks), which are governed by 2 different users.
 - 1 of those users was kicked (the webhook one), so it has been unable to send webhooks into the room.

If you toggle a webhook off/on again it will attempt to rejoin the room. I'll file an issue on the respective projects to make it clearer to users that there are 2 bots involved.

**Comment by kasbah** [comment]
Ok, thank you very much for explaining.
