### ISSUE TITLE
I cant find the way to sign out  

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-web#2724]
the sign out button is not on main page clearly but in the setting page, this is very confusing for new user.

**Comment by richvdh** [comment]
we can't put *everything* on the main page...

**Comment by wjhtinger** [comment]
Maybe you are right, but the  sign out is in the setting menu, which is some odd

**Comment by ara4n** [comment]
I can't think of anywhere better to put it than Settings tbh.

**Comment by ssbarnea** [comment]
I totally agree that current placement makes it hard to find. I had to google after spending a lot of time trying to find the option, even if I did look multiple times in Settings. Maybe because is not Log-out but Sign-out?

Clearly such an option should be present in the application menu-bar.
