### ISSUE TITLE
quoting in MD mode when using RTE toolbar doesn't insert trailing \n

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2746]
So you select text, hit quote on it, but the quote bleeds to the next lines

**Comment by pavi** [comment]
I reported this issue. But for now the workaround for the users is to simply press the quote button thrice so as to force the `\n` on to the editor. Maybe another option would be to allow the user to press `enter` and not send the text. Some platforms give a choice of `enter` or `ctrl-enter` to send formatted text. 
![screenshot_2016-12-12_19-19-25](https://cloud.githubusercontent.com/assets/971668/21206946/6cf34702-c265-11e6-8029-db16e0d08f44.png)

**Comment by pavi** [comment]
Its easy now to do a `shift+enter` and go to the next line. Also its easy to click on the next line. But a `\n` is not yet inserted. Its not so inconvenient as before but a minor annoyance for newbies.

Checked on:
*  matrix-react-sdk version: 1189368aab8cfb22c1895f8ce6c0d8a8fbe7ca0b
* riot-web version: v0.9.8-4
