### ISSUE TITLE
Midori browser rendering weirdly

### ISSUE THREAD

**Issue by hackervera** [vector-im/riot-web#2748]
![selection_008](https://cloud.githubusercontent.com/assets/143954/21192398/486dc548-c1dd-11e6-93b5-f96ce43b2185.png)

**Comment by ara4n** [comment]
looks like it's choking badly on the flexbox layout. we don't support midori - sorry!

**Comment by lampholder** [comment]
Closing this (since we don't support Midori browser, keeping an issue open for this specific failure is not super useful). Also, hopefully midori has implemented flexbox support since dec 2016 :D
