### ISSUE TITLE
Linkifier not working with more than one dot in domain name

### ISSUE THREAD

**Issue by VShell** [vector-im/riot-web#2756]
When linking to rooms like #erlang:57north.org.uk, only #erlang:57north.org gets turned into a link. Same with #letstesthis:halfshot.co.uk ending at the .co. However, #thisisatest:foo.example.com works. I assume that the issue is that .org and .co are valid TLDs, so the linkifier is not greedy enough?

**Comment by Half-Shot** [comment]
I'm wondering why the linkifier is even verifying TLDs at all. I'd either go all the way and verify the HS/room/user_id or don't verify and let the user click through.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/41812343-1a24dd64-7719-11e8-90a0-97f0e24481bc.png)
its not related to the number of dots in the domain

**Comment by t3chguy** [comment]
it gets weirder
![image](https://user-images.githubusercontent.com/2403652/41812354-3bb542c0-7719-11e8-9b86-b8af0bfc580d.png)
