### ISSUE TITLE
start chat button in bottom-left should prompt between reusing and creating new chat

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2760]

**Comment by ara4n** [comment]
in fact, it should list all the direct chats you have with that person to pick which to use, and have "create new chat" as the final option.

**Comment by croulibri** [comment]
I would say the same should apply when I select a member of a room (right panel) and I want initiate a direct chat with her/him : the "Start new chat" button should also invite me first to select one of the existing direct chat with her/him
