### ISSUE TITLE
[e2e] Riot on safari fails to upload and decrypt image

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#2762]
1. First issue
On an encrypted room, it's impossible to upload an image with Safari.
```
Upload Failed
The file 'Koala_climbing_tree.jpg' failed to upload.
```
2. Second issue
On an encrypted room, it's impossible to decrypt an image sent by an other client/browser/user with Safari.
![safari fails to decrypt image](https://cloud.githubusercontent.com/assets/22364949/21307891/c3169fa6-c5d7-11e6-82e2-a13732cae291.png)

**Comment by aaronraimist** [comment]
This has been fixed for a while
