### ISSUE TITLE
UI is broken on direct chat list on Windows

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2763]
It initially appears properly but then turns into this:

![capture](https://cloud.githubusercontent.com/assets/8582858/21316799/adb0e7d6-c602-11e6-92c0-13869f763fa7.PNG)

**Comment by ara4n** [comment]
i think i've also seen this on not-electron

**Comment by ara4n** [comment]
i'm 75% sure i did something to fix this, but i have no idea what.
