### ISSUE TITLE
Linux desktop app: broken /usr/local/bin/riot-web symlink

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#2767]
The Debian package for the Linux desktop app creates a symlink at /usr/local/bin/riot-web to /opt/riot-web/riot-web, but /opt/riot-web does not exist.  The symlink should point to /opt/Riot/riot-web instead.

**Comment by uhoreg** [comment]
Also, deb packages shouldn't be putting things in /usr/local/bin.  The symlink should be in /usr/bin instead.

**Comment by 4nd3r** [comment]
also, maybe it's my ocd, but ``/opt/riot/riot-web`` with all lowercase would be nicer and correctish.

**Comment by uhoreg** [comment]
deb packages really shouldn't be putting things in /opt anyways, but that's a separate issue (not filed yet, AFAIK).  It would probably take a bit of work to put things in their "proper" locations.

**Comment by maikell** [comment]
ack, please close 'my' issue, plz :)

**Comment by uhoreg** [comment]
Closing this issue because the /usr/local/bin/riot-web is no longer included

**Comment by uhoreg** [comment]
Actually, the symlink is created in the postinst script, so it is still there.  However, it is now pointing to the right thing, so this issue is fixed anyways.
