### ISSUE TITLE
'Download file' button on lightbox doesn't work for e2e attachments on Chrome >= 2MB

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2770]

**Comment by lukebarnard1** [comment]
As far as I can tell, it does?

**Comment by lukebarnard1** [comment]
oh I didn't test for non-image files

**Comment by dbkr** [comment]
Not if the image is too big for a data: URL

**Comment by dbkr** [comment]
Same applies for audio files. It plays the first however much of the file and then stops, and the download link (built into chrome's audio element) doesn't work.
