### ISSUE TITLE
expose notification setting to let people disable notifs for their MXID

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2773]
as we constantly get confusion due to folks forgetting their MXID userid and then being surprised when they get binged

**Comment by ara4n** [comment]
e.g

> * Half-Shot is getting a little fed up with being pinged due to his domain being used by bridge users and being unable to switch that off.
Would like to be able to suggest to the pinger that he doesn't wish to be pinged on his userid

**Comment by turt2live** [comment]
@ara4n this has been fixed (see referenced PR: https://github.com/vector-im/riot-web/issues/3334 )

**Comment by turt2live** [comment]
@t3chguy or @ara4n this is resolved (see above)
