### ISSUE TITLE
Need a better way to save files from the desktop app

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#2778]
I realise that given it's not a native app this might not be doable however having to click on the image, click on download, right click on the one opened in the browser and do a 'save as' is a pain...

**Comment by scar45** [comment]
I must add that clicking on "Download this file" (when viewing an image modal) from within the Electron app doesn't actually do anything for me. Right-clicking the same button shows the MIME type and base64 encoded data (truncated) in a single-entry native menu object.

Tested on 3 Windows 10 systems with the 0.9.5 release.

**Comment by ara4n** [comment]
@scar45's bug is #2970.

**Comment by ara4n** [comment]
apparently fixed by #3640 - thanks @t3chguy!
