### ISSUE TITLE
captcha not showing up on electron client when registering

### ISSUE THREAD

**Issue by DiskVera** [vector-im/riot-web#2785]
http://imgur.com/niMrrqP

**Comment by ara4n** [comment]
ugh, thanks for this.

**Comment by dbkr** [comment]
Having had a quick look, we try to get the URI scheme from window.location, but even then, the captcha fails to load with 'invalid domain'.

**Comment by ara4n** [comment]
crappy fix in https://github.com/matrix-org/matrix-react-sdk/pull/601 landed just now in 0.9.5

@DiskVera thanks for the report!
