### ISSUE TITLE
room created via start chat + 3PID (email) is not tagged as DM

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2794]

**Comment by t3chguy** [comment]
Annoyingly, the room is shown as a 1:1 after the 3pid invite is accepted

**Comment by turt2live** [comment]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=40333174)](https://www.bountysource.com/issues/40333174-room-created-via-start-chat-3pid-email-is-not-tagged-as-dm)

**Comment by turt2live** [comment]
additionally, the user that accepts the invite does not get admin in the room.

**Comment by t3chguy** [comment]
> additionally, the user that accepts the invite does not get admin in the room.

is a different issue, and down to how synapse createRoom 3pidInvites works
