### ISSUE TITLE
Emojis: Convert text to emojis when sending a message

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#2802]
Would be nice to convert text smileys to their emojis equivalent.

:) => 😄 
;) => 😉 
:P => 😛 
etc...

**Edit:**

This option should be optional, as some people don't like the non-determinism of this feature.

Also, if the option is enabled, it would be nice if emojis written in plain ASCII text would be parsed as well and interpreted into emojis (e.g. `:dromedary_camel:` would become 🐪).

This can be done by the client either before sending the message or after receiving it. I don't know what's the best implementation.

**Comment by MightyCreak** [comment]
Also, it would be nice if the textual emojis where parsed as well.

Right now, if we type `:dromedary_camel:`, don't select explicitly an emoji and press Enter, the text isn't convert into its emoji.

Note: GitHub do convert the text emojis, unless it's inside code block.

**Comment by MightyCreak** [comment]
As proposed in the Riot room, this option should be optional.

**Comment by MightyCreak** [comment]
Part of #2984

**Comment by dbkr** [comment]
I'd probably vote against this: I had enough of MSN messenger randomly turning things into emoji back in 1999.

**Comment by MightyCreak** [comment]
The problem with MSN-like client is that they were stupidly parsing the text and every time they found a pattern they would interpret it as a smiley. This is especially painful when sharing code, like if for Instance I was pasting this: "MyClass::Disable()", it was converting the ":D" into 😆 making your code both stupid and unreadable.

To prevent this, you can simply only detect smiley that are "alone" (i.e. that has spaces before and after). The RE pattern would be this: `(^|[[:space:]]):D([[:space:]]|$)` so that it also tolerates text smileys at beginning and end of line.

I think this simplifies the writing of casual and pro messages in an elegant way.

**Comment by MightyCreak** [comment]
@dbkr I changed the description of the issue, especially this:

> This option should be optional, as some people don't like the non-determinism of this feature.

And:

> This can be done by the client either before sending the message or after receiving it. I don't know what's the best implementation.

Would you still be against such feature? Since, depending on the chosen implementation, emoji characters would still be sent through the network (and not ASCII text).

**Comment by kythyria** [comment]
Never, _ever_ do things like this on receive. Ever.

**Comment by ara4n** [comment]
The way this is meant to work in the RTE is that if you hit : it pops up a list of possible emoji, including :) and :( etc as options.   It could also autosuggest similar ones.  I think this will be sufficient.

This is tracked by a tickbox at https://github.com/vector-im/riot-web/issues/1761

**Comment by MightyCreak** [comment]
But not all the smiley starts with `:`, for instance `;)`

**Comment by ara4n** [comment]
we hope that folks will learn that hitting : brings up an emoji menu, whether they were thinking ;) or not ;)

**Comment by MightyCreak** [comment]
I really think this point would be criticized where comparing against Slack (where the feature is opt-in by default). Of course some will love the fact that it's not too simple to make smileys, but I'm not sure it's going to be the majority of users.

I understand that all the emojis will be proposed through `:` and I really like and use it everyday, but I don't understand why Riot could not have a feature to convert well known smileys to emojis (and I'm talking about UI here, not Matrix, just to be clear). Since I don't see the difficulty or the security issue here, I don't see why not doing it. It's not invasive either. I understand that it's not high priority, but closed? I'm not sure, I think there is value in this feature that the mere `:` won't suffice.

Also, it would be an interesting feature if the `text => emoji` map was exposed to the users, especially with custom emojis, that would allow a user to map common abbreviations (e.g. brb, lol, omw, ...) to emojis of their choice.

Just wanted to expose my point of view as a pretty intensive user of both Riot and Slack.

**Comment by ara4n** [comment]
ok, we'll make auto text->emoji conversion an optional feature.

one possible compromise: how about if it recognises *any* valid emoji sequence, including ;) and lets you either click on the preview or hit tab to turn it into a real emoji?
>

**Comment by intelfx** [comment]
I just hope that this will be optional and will remain optional forever.

**Comment by MightyCreak** [comment]
@ara4n It's a bit less conventional but I guess that would do. Isn't it going to be harder to implement though? Anyway, I think that, like every UI/UX dev, the best strategy is to try different ways and get users feedbacks.

Again, I understand you have other fish to fry. I guess it enters in the "nice to have" section, and I guess it's a pretty feasible task for a new comer dev 😉 

OT: that makes me think that maybe Riot (and Matrix) could have a wishlist where users could add and vote for their most wanted features (à la https://www.gog.com/wishlist). I know I'm biased as much as the other guy, that's why I think that this kind of wishlist is a very simple way to get users feedbacks and I'm sure that would help you to prioritize tasks.

@intelfx I've repeated that several times, don't you worry, this is optional, can even be opt-out if you like, and you'll be able to keep your IRC-like look&feel.

**Comment by aliencq** [comment]
Hope it won't consume additional RAM or slow down the composer. I'd vote against it as well.

**Comment by MightyCreak** [comment]
@intelfx I've repeated that several times in the and the comments, don't you worry, this is optional, can even be opt-out if you like, and you'll be able to keep your IRC-like look&feel.

@aliencq no it won't, this is will happen while writing, it won't use more than the current emoji system. And honestly, I guess emojis aren't really a problem for RAM... Their are a lot more code to optimize before worrying about emojis.

Come on guys, don't you think you're a bit dishonest here? This feature won't honestly impact you in any way. Aren't you saying this just because you don't like emojis and prefer pure text based communication systems?

**Comment by ara4n** [comment]
folks, no reason to panic; we're not going to implement anything which slows anything down. having it as opt-in is fine. we'll experiment with the best UI for proposing the emoji replacements. @MightyCreak: thanks for championing this one.

I don't think there's anything more to say here until someone implements this.

**Comment by ara4n** [comment]
(and this is still closed as it's tracked on the other issue).

**Comment by MightyCreak** [comment]
@ara4n Thank you!
