### ISSUE TITLE
White space appears next to room list when mouse is plugged in (Riot Desktop - macOS)

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#2805]
Ran into this when plugging in a mouse - there's a blank white space next to the room list. It looks like there's supposed to be a scrollbar there, but the scrollbar ended up to the right of that. This behavior occurs only when a mouse is plugged in and goes away when unplugged. Similar to #1276.

![screen shot 2016-12-23 at 9 31 44 pm](https://cloud.githubusercontent.com/assets/1923178/21464826/5ad9dd26-c957-11e6-849e-97d7e55f4b3b.png)
![screen shot 2016-12-23 at 9 32 03 pm](https://cloud.githubusercontent.com/assets/1923178/21464827/5bd62ed2-c957-11e6-83e2-9a80d6c658c4.png)

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/1276
