### ISSUE TITLE
Add jump to unread banner message

### ISSUE THREAD

**Issue by k3vmcd** [vector-im/riot-web#2813]
### Description
When there are unread messages in a conversation, viewing the room opens to the most recent message and there is not an easy way to start from the last unread position instead.

### Steps to reproduce
- Participate in a room
- Deselect room and wait until there are enough unread messages to cause the last unread position to be off-screen)
- Select room to read messages

**Actual result:** Room is loaded to most recent message and unread badge clears. There is no way to jump to the last read message and begin reading in chronological order.
**Expected result:** There is a persistent, manually dismissible banner that says "X Unread Messages" and when the user clicks on the banner it jumps to the last read message. (Alternate behavior: The room always loads to the last read message and the user scrolls chronologically to the most recent message).

**Comment by ara4n** [comment]
i think this is probably a dup of https://github.com/vector-im/riot-web/issues/1146?

**Comment by k3vmcd** [comment]
Hmm, I didn't realize it would show up eventually if the user scrolls up. If there is already a banner that behaves as outlined above, then yes this is a dup of #1146 as it's just a display bug.

**Comment by MightyCreak** [comment]
> i think this is probably a dup of #1146?
I'm not sure I understand what #1146 tries to fix... but I sure agreed with this one here.

Also I think the unread banner should stay way longer than the few seconds we have currently. I often don't even have the time to see it, it's already gone.

**Comment by richvdh** [comment]
dup #1146
