### ISSUE TITLE
Rename "Device key"

### ISSUE THREAD

**Issue by gsantner** [vector-im/riot-web#2821]
Please rename "Device key" to "Device public key" in the Settings section of the web application. So people know this is shareable. Maybe a button "Copy public identiy" or like that would be great, which copies ID and public key to clipboard. So it can be shared via e.g. E-Mail.
**I thought this is a private key.**

**Comment by lampholder** [comment]
I expect this will get covered in the coming rounds of E2E imrovements

**Comment by gsantner** [comment]
Closing some old stuff nobody seems to care about
