### ISSUE TITLE
Add emojis to messages

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#2824]
Possibility to add emojis on messages (might be something more Matrix/SDK related, idk)
Here is an example from Slack:

<img width="1413" alt="emojis_on_message" src="https://cloud.githubusercontent.com/assets/6382548/21471960/607b7338-ca93-11e6-9bf9-21f2ae583fb7.png">

It seems superfluous, but it actually clears the room a lot since less people are typing stuff like "lol", "+1", etc. They prefer to add their emoji to the message or click on an existing one to increment its number.

It is also a great feature-that-attract-new-users ;)

**Comment by Anathea** [comment]
Oh, it's more a reaction than an emoji in the message. But yes, it would be a great feature !

**Comment by MightyCreak** [comment]
It's reacting through an emoji ;)

**Comment by currymj** [comment]
i think a lot of people would be interested in this. it may be the most-loved slack feature. how difficult of a contribution would this be?

**Comment by dbkr** [comment]
This is https://github.com/vector-im/riot-web/issues/1357
