### ISSUE TITLE
'Internal server error' when try to remove old device from devices list after enter password

### ISSUE THREAD

**Issue by unclechu** [vector-im/riot-web#2830]
It happened just for first time, second try is successful.

**Comment by unclechu** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/799353/21484547/84f09514-cbbe-11e6-947d-7e8137065d89.png)
*P.S. I just removed password before took screenshot for security reasons.*

**Comment by ara4n** [comment]
i'm hoping you just got unlucky with the server being overloaded. i've not seen this since, at least.
