### ISSUE TITLE
UI fix for underline position of members list button when number is very big

### ISSUE THREAD

**Issue by unclechu** [vector-im/riot-web#2832]
Could be reproduced here: [#freenode_#Haskell:matrix.org](https://riot.im/app/#/room/#freenode_#Haskell:matrix.org)
![selection_002](https://cloud.githubusercontent.com/assets/799353/21484760/3fe54a2e-cbc2-11e6-8cda-c62f6d8fc8e4.png)

**Comment by turt2live** [comment]
This is not a thing anymore
