### ISSUE TITLE
Shortcut Menu

### ISSUE THREAD

**Issue by k3vmcd** [vector-im/riot-web#2837]
Provide users with a keyboard shortcut key combo that allows them to jump to conversations. Default open to unread conversations as in #301.

Suggestion: Duplicate Slack "Control/Command + K" menu.

**Comment by richvdh** [comment]
I'm confused about what is being asked for here.

**Comment by k3vmcd** [comment]
I'm looking for a keyboard shortcut that allows me to jump between conversations.

Example (from Slack):
![image](https://cloud.githubusercontent.com/assets/5653317/22994425/1f5101c4-f384-11e6-99b0-6b5064007407.png)

**Comment by richvdh** [comment]
dup #3216 then
