### ISSUE TITLE
Emoji should render when keyword is marked with colons

### ISSUE THREAD

**Issue by k3vmcd** [vector-im/riot-web#2838]
When a user enters an emoji keyword surrounded by colons, it should render as an emoji.

Examples:

`:smiley:` should render as the smiley face
`:astonished:` should render as the astonished face

**Comment by gonight** [comment]
Would a collapsed emoji keyboard (like on iOS/android) make sense? Should this be a separate issue?

**Comment by Dasoren** [comment]
I personally would like to have better emoji support and even custom emoji.
I hate bring up slack here, but that is one of the main things I miss about slack after I moved to matrix/riot.

**Comment by ara4n** [comment]
the beta rich-text-editor is already doing this. it just needs to be finished. see https://github.com/matrix-org/matrix-react-sdk/pull/518.

**Comment by k3vmcd** [comment]
The rich text editor brings up the selector window, but it does not expand
fully typed keywords even when surrounded by colons. This issue is specific
to converting these to emoji, not simply filtering the selector (as it
currently operates).

**Comment by aviraldg** [comment]
That is by design, so it is up to you to choose whether or not you want them replaced.

**Comment by ara4n** [comment]
this is basically a dup of #2802.
