### ISSUE TITLE
Collapse invites into joins and parts more efficiently

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2842]
See https://github.com/vector-im/riot-web/issues/74.  @lukebarnard1  implemented collapsing joins/parts, but it could take up less room:
 * The collapsed view should be entirely replaced when expanded, rather than the expansion being added to the collapsed summary
 * Invites should be included as well as joins/parts in the collapsing, otherwise every time an IRC user joins, they are first invited by the bridge and so break the collapsing.

**Comment by lukebarnard1** [comment]
> The collapsed view should be entirely replaced when expanded, rather than the expansion being added to the collapsed summary

@ara4n: does this mean it should not be toggle-able? 

> Invites should be included as well as joins/parts in the collapsing, otherwise every time an IRC user joins, they are first invited by the bridge and so break the collapsing.

Should the invites be included in the summary? E.g. "12256 people were invited"

**Comment by ara4n** [comment]
We should still be able to expand/collapse; let's just put the toggle at the end of the topmost message (whether it is expanded or collapsed).

Yes, let's include invites too.  So the categories end up being joined/left/kicked/banned/invited, ordered chronologically as per #2856
