### ISSUE TITLE
Option to disable automatically trusting new devices.

### ISSUE THREAD

**Issue by JoranHonig** [vector-im/riot-web#2843]
At this moment, if a homeserver has a user in an encrypted room the homeserver is able to create a new device connected to that user.  This device will have a specific keypair that is known to the compromised server. All messages sent to e2ee rooms the user is in, will then be available to the compromised server since all the messages are encrypted for all the devices which are not blocked. This would make the e2ee useless, since everything can be seen by the homeserver.

Hence, it would be useful to have an option to have new devices start in the blocked status and then manually can be changed to verified.

**Comment by richvdh** [comment]
dup #2313
