### ISSUE TITLE
add information to website: Linux repository adding commands

### ISSUE THREAD

**Issue by edmundlaugasson** [vector-im/riot-web#2845]
Please add to the site https://riot.im/download/desktop/ and https://riot.im/desktop.html appropriate Linux repository adding commands. As I see from https://riot.im/packages/debian/dists/ then there are Debian and Ubuntu supported.
E.g.:
## Adding Linux repository
Check your Linux distribution.
* using lsb-release command
  * if you do not have then install _lsb-release_ package
 `sudo apt update && sudo apt-get -y install lsb-release && sudo ldconfig && sudo dpkg --configure -a && sudo apt-get clean`
  * then enter the command
`lsb_release -da | grep -i codename`
  * the output could be e.g.:
`Codename:	wheezy`
or
`Codename:	xenial`
... then you know, which folder name to choose as codename from the address https://riot.im/packages/debian/dists/
  * to cut the codename only (output will be the codename itself only):
`lsb_release -da 2>/dev/null | grep -i codename | cut -f2`
  * In case of Linux Mint, which is based on Ubuntu LTS version you can use Ubuntu repositories - https://en.wikipedia.org/wiki/Linux_Mint_version_history#Release_history - e.g. Linux Mint 18 corresponds to Ubuntu 16.04 LTS, it means _xenial_ can be used as codename in repository list file.
* In case of any other Debian/Ubuntu based distro please check appropriate Debian or Ubuntu version and use this as codename in _/etc/apt/sources.list.d/matrix-riot-im.list_ file.
* Add repository (choose one of these):
  * manually entering the appropriate distro codename: replace "codename" with appropriate distro codename:
`echo "deb https://riot.im/packages/debian/ codename main"  > /etc/apt/sources.list.d/matrix-riot-im.list`
  * using automatic way
_echo "deb https://riot.im/packages/debian/ \`lsb_release -da 2>/dev/null | grep -i codename | cut -f2\` main"  > /etc/apt/sources.list.d/matrix-riot-im.list_
* if you have any other distro than Debian or Ubuntu then check corresponding codename and replace with correct one in _/etc/apt/sources.list.d/matrix-riot-im.list_ file
* Import GPG-key (digital signature) to ensure in software authenticity:
`wget https://riot.im/packages/debian/repo-key.asc && sudo apt-key add repo-key.asc && rm repo-key.asc` 
* Update your Linux repositories database, install the software and clean up the system:
`sudo apt update && sudo apt-get -y install riot-web && sudo ldconfig && sudo dpkg --configure -a && sudo apt-get clean`
* program is now installed and ready to use, it can be run from _/opt/Riot/riot-web_
* for easier access you may want to create a symlink:
`ln -s /opt/Riot/riot-web /usr/bin/`
  * then you can just run the command _riot-web_

**Comment by 4nd3r** [comment]
why `sudo ldconfig && sudo dpkg --configure -a` ? normally you wouldn't need to do it. ymmv.

you can get debian release name from `/etc/os-release` without installing `lsb-release`.

wheezy (oldstable LTS) doesn't have `apt`. using `apt-get` is more universal if you care about anything older than jessie or what ever ubuntu version still supported, but doesn't have `apt` also.

also, too much wall of text imho. it would be easier if people can just download deb file and do `sudo dpkg -i` and with first installation postinst script adds repo to sources and riot archive singining key to keyring.

**Comment by Mikaela** [comment]
Why `lsb_release -da | grep -i codename` instead of `lsb_release -sc`?

Why three commands for importing GPG key instead of just `curl -L https://riot.im/packages/debian/repo-key.asc | sudo apt-key add -`?

**Comment by Mikaela** [comment]
If --recv-keys is going to be recommended, the full fingerprint should possibly be used. 

Alternatively --fetch-keys now that you mentioned adv

**Comment by edmundlaugasson** [comment]
I'm glad that anyone responded. Certainly those results can be achieved in many ways and great if you found shorter ones. Those software trimming and clean up commands are to ensure all works properly. If there is everything fine then those commands do nothing harmful. Former experience have shown that sometimes there occur some errors whether former software update have somehow not finished or any other unsolved issue in package management.  Here is shorter version:

## Adding Linux repository
Check your Linux distribution.
  * open the terminal (e.g. CTRL+ALT+T) and enter the command
`cat /etc/os-release`
  * the relevant part from output could be (look the <b>bold</b> codename) e.g. in case of Ubuntu 16.04.x LTS:
_UBUNTU_CODENAME=<b>xenial</b>_
or in case of Debian 8.x:
_VERSION="8 (<b>jessie</b>)"_
or in case of Linux Mint 18.x:
_UBUNTU_CODENAME=<b>xenial</b>_
... then you know, which folder name to choose (here in bold) as codename from the address https://riot.im/packages/debian/dists/
* Add repository:
  * replace "codename" with appropriate distro codename:
`echo "deb https://riot.im/packages/debian/ codename main"  > /etc/apt/sources.list.d/matrix-riot-im.list`
* if you have any other distro than Debian or Ubuntu then check corresponding codename and replace with correct one
* Import GPG-key (digital signature) to ensure in software authenticity:
`curl -L https://riot.im/packages/debian/repo-key.asc | sudo apt-key add -` 
* Update your Linux repositories database, install the software and clean up the system:
`sudo apt-get update && sudo apt-get -y install riot-web && sudo ldconfig && sudo dpkg --configure -a && sudo apt-get clean`
* program is now installed and ready to use, it can be run from _/opt/Riot/riot-web_
* for easier access you may want to create a symlink:
`ln -s /opt/Riot/riot-web /usr/bin/`
  * then you can just run the command _riot-web_

**Comment by ara4n** [comment]
@edmundlaugasson thanks for this. we're about to relaunch the website, and will incorporate this.

**Comment by ara4n** [comment]
the website relaunch is delayed, so i've just linked to the instructions in this comment thread for now. thanks!

**Comment by MurzNN** [comment]
Here is one-liner for quick install Riot on Debian/Ubuntu systems:
```
echo "deb https://riot.im/packages/debian/ $(lsb_release -s -c) main" > /etc/apt/sources.list.d/matrix-riot-im.list; curl -L https://riot.im/packages/debian/repo-key.asc | sudo apt-key add -; sudo apt-get update; sudo apt-get -y install riot-web
```

**Comment by wikey** [comment]
There is also an open "Request for Package" bug in the Debian system to include riot-web in the main distribution repositories: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866502
