### ISSUE TITLE
Electron can get stuck insisting that you update

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2847]
If you're on 0.9.2, see an update prompt for 0.9.5, hit update, it seems to install the 0.9.5 HTML and restart the app... but the user-agent is still 0.9.2.

**Comment by ara4n** [comment]
affects both macOS & windows seemingly

**Comment by dbkr** [comment]
https://github.com/Squirrel/Squirrel.Windows/issues/774 is a bug in Squirrel.Windows where if the local version is higher than any version available on the update servers, it gets stuck in a loop. This may be what you were seeing?

**Comment by dbkr** [comment]
Closing this as it should be fixed by the explicit version check. Have split out the windows behaviour I described into https://github.com/vector-im/riot-web/issues/2968
