### ISSUE TITLE
Show more clearly when sending non E2E encrypted message

### ISSUE THREAD

**Issue by tuxayo** [vector-im/riot-web#2850]
Here is a solution suggested by Jon 😺:
> could also be done the way Conversations does it (the text in the input box says "send unencrypted message" when encryption is disabled)
https://riot.im/app/#/room/#riot:matrix.org/$148303643413sNpVB:terracrypt.net

This was during a discussion about the risk of users believing that they are covered by E2EE when they are not. (as it's advertised on the website)

If the full discussion is needed, here is the start:
https://riot.im/app/#/room/#riot:matrix.org/$148303529135272nuTCB:matrix.org
~ 110 messages read to get the proposals and feedback.

Related to #2626

**Comment by ara4n** [comment]
i missed this at the time (thanks to operational hell over xmas) - agreed this is a great idea.

**Comment by ara4n** [comment]
@lukebarnard1 the PR seems to be broken :(

![screen shot 2017-02-22 at 17 44 02](https://cloud.githubusercontent.com/assets/1294269/23224522/a651f578-f926-11e6-8a79-58cfd6489daa.png)

**Comment by lukebarnard1** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/723
