### ISSUE TITLE
Google Catpcha to verify user

### ISSUE THREAD

**Issue by Malvarose** [vector-im/riot-web#2851]
Why are you using this?  I think the reason most people are interested in Riot, or Matrix in general, is because of privacy.  You could use an alternative one that is open source.  visualCaptcha seems like a decent one from a quick search.  (they have a repo on here)  I just don't think using anything Google is beneficial.

**Comment by neomodern** [comment]
+1 on this. Google does produce some cool things but it's not essential to allow them to track users via their captcha service when there an open-source alternatives available.

**Comment by gonight** [comment]
I strongly support having alternatives to ReCaptcha, but I'd argue against removing it entirely.

**Comment by Kiyuubi** [comment]
Yeah, definitely.  I don't think a captcha should be removed, but simple do not use Google.

**Comment by richvdh** [comment]
dup #2759
