### ISSUE TITLE
Encrypt/decrypt images fails with Safari

### ISSUE THREAD

**Issue by simsasaile** [vector-im/riot-web#2852]
Instead of showing the encrypted images Safari shows: "Error decrypting image" and trying to upload an image results in "Upload failed: The file "IMG_xyz.jpg" failed to upload.

Vector-web version: v0.9.5
Safari version 9.1.3

Not a big deal, with firefox it's working just fine :)

**Comment by simsasaile** [comment]
![bildschirmfoto 2016-12-30 um 13 48 06](https://cloud.githubusercontent.com/assets/7559897/21565407/b2cdfb80-ce97-11e6-9fb6-9b3cb3bbabca.png)
![bildschirmfoto 2016-12-30 um 13 47 45](https://cloud.githubusercontent.com/assets/7559897/21565415/dc311af2-ce97-11e6-9df4-9ae8eef89ebe.png)

**Comment by jeangb** [comment]
Related to https://github.com/vector-im/riot-web/issues/2762

**Comment by simsasaile** [comment]
Thanks @jeangb haven't seen that, so I'm closing this duplicate.
