### ISSUE TITLE
collapsed join/part messages don't respect causality

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2856]

**Comment by ara4n** [comment]
16:44 Cyberops-NSA joined the room. 1 user joined and left [expand]

expands to:

16:44 Cyberops-NSA joined the room.
16:44 Michael Englehorn left the room.
16:45 Michael Englehorn joined the room

... so shouldn't the first line say "1 user left and joined"?

**Comment by richvdh** [comment]
well, we don't count the number of times people join and leave - they just get lumped into "joined and left" if their end state is the same; otherwise we'll end up with "1 user left and joined. 1 user joined and left. 1 user joined, left, joined, left and joined again. 1 user shook it all about."

**Comment by ara4n** [comment]
the point here was just that the wording is confusing. "1 user joined and left" implies that the same user joined, and then they left.  The solution is surely to just collapse using the most recent state changes, in order to reflect causality.

So: if there are X people who joined, Y who left, Z who were kicked, we'd take the most recent person from each of the 3 groups, and then order the descriptions chronologically.

So in this instance, it'd be:
 * Michael Englehorn left and Michael Englehorn and one other joined.

If we were collapsing:
 * A joined
 * A left
 * B joined
 * C joined
 * D was kicked

then it'd be:
 * A left, C and 2 others joined, D was kicked.

wdyt?

**Comment by lukebarnard1** [comment]
Yep, this makes sense and expand nicely to include kicks, bans and invites.

**Comment by ara4n** [comment]
One refinement that came to mind is that we might want a dedicated grouping for transient join-then-part and part-then-joins (rejoins) sequences.  So for the two examples above, this would end up being:

 * Cyberops-NSA joined and Michael Englehorn left and re-joined.

 * A left and re-joined, B and one other joined, D was kicked

For another example:
 * P joined
 * Q joined
 * S joined
 * S left
 * R joined
 * Q left

would be...

 * R and one other joined, Q and one other joined and left.

**Comment by richvdh** [comment]
AIUI, you now have:
* invited
* rejected invite
* withdrew invite
* joined
* left
* kicked
* banned
* unbanned
* left
* joined and left
* left and re-joined.

How will the following be shown?
* a user who joins, leaves, and joins
* a user who joins, is kicked, and re-joins

I ask mainly to ensure that Luke isn't going off implementing something that isn't what we expect :)

**Comment by ara4n** [comment]
the suggestion above was:

> So: if there are X people who joined, Y who left, Z who were kicked, we'd take the most recent person from each of the 3 groups, and then order the descriptions chronologically.

so, for this, you'd see:
 * W joined and left, and W joined
 * W was kicked and W and one other joined  (which I agree is a bit crap).

Perhaps a better algorithm would be to group transitions per user, and then deduplicate users who have the same lifecycle.  Which would result in:
 * W joined and left and joined
 * W joined and was kicked and joined

The examples above would end up as:
 * Cyberops-NSA joined and Michael Englehorn left and joined
 * A joined and left, B and one other joined, D was kicked
 * P and one other joined, Q and one other joined and left

...which actually feels much nicer, i think?

**Comment by richvdh** [comment]
that was my original suggestion at https://github.com/vector-im/riot-web/issues/2856#issuecomment-270093542 I think. The question remains of how you deal with people who join and leave half a dozen times because they are on flaky connections.

**Comment by ara4n** [comment]
OH! i had totally failed to realise that comment was a suggestion for a solution.

Just IRLed with Luke and the new algorithm sounds plausible.  We don't have a solution for "A joined and left and joined and left" scenarios, other than either doing a special heuristic to collapse those down into a single "join and left"... at which point you might as well go the whole enchilada and collapse it down to "joined and left 42 times" :)

thanks for spotting the hole in the other proposal.

**Comment by richvdh** [comment]
tbf it wasn't meant as a very serious suggestion.

so you are going with "A joined and left 42 times"? Won't you end up with "A joined and left 42 times. B joined and left 41 times. C left and re-joined 42 times"?

What about people who do a leave/join dance and are also affected by one of the other transitions? (Banning seems likely after leaving and rejoining 42 times...)

**Comment by ara4n** [comment]
yeah, i think we should?  Yes, it'll end up worst case with the kind of example you listed, but that's better than 42*2 + 41*2 + 1 + 42*2 = 251 timeline entries ;D

If they do leave/join and are affected by other transitions, it'd end up as "A joined and left 42 times and was banned", which feels fine to me!

(internationalising this will be hilarious)

**Comment by richvdh** [comment]
well, ok. I worry it will become unreadable in large IRC channels with lots of people coming and going, but we can see.

**Comment by ara4n** [comment]
I'd expect the worst case we'll see will be "Foo and 56 others joined, Bar and 34 others joined and left, Quux and 623 others left and joined, Baz and 20 others left"... which doesn't feel unreadable to me.

**Comment by richvdh** [comment]
because you don't expect to see lots of people doing multiple joins/leaves?

"A joined and left 42 times. B joined and left 41 times. C joined and left 40 times. D joined and left 39 times. ... Z joined and left 20 times ... etc" would be pretty unreadable.

**Comment by ara4n** [comment]
i guess. worst case we can collapse them down without the "42 times" bits if it's a problem.

**Comment by richvdh** [comment]
ok then :)

**Comment by richvdh** [comment]
Is there any expectation of the ordering of the summary? 

Should
   16:44 Cyberops-NSA joined the room.
   16:44 Michael Englehorn left the room.
   16:45 Michael Englehorn joined the room

be 

"Cyberops-NSA joined, Michael Englehorn left and joined", "Michael Englehorn left and joined, Cyberops-NSA joined", or does it not matter? (ftr: current implementation is for arbitrary ordering)

**Comment by lukebarnard1** [comment]
I don't think it matters too much. I'm hoping the commas suggest "and also this other thing happened" instead of "and then". If we wanted to aggregate by time as well, it might be quite complicated.

**Comment by richvdh** [comment]
Another question (paging @ara4n):

"invite, join, leave, join, leave": the current implementation will not collapse the join/leave pairs and will be expanded into "Bob was invited, joined, left, joined and left". Likewise if there are any non-join/leave events anywhere in the event list. (kicks, bans, more invites, etc).

Is this a problem? Should the above be "Bob was invited, and joined and left 2 times", or?

**Comment by ara4n** [comment]
regarding ordering: how about we order the groups chronologically (i.e. based on timestamp of the last event in that group).

regarding "Bob was invited, and joined and left 2 times", i thought the decision was to try to special-case consecutive join/left or left/join combinations into "joined and left N times" or "left and joined N times".

**Comment by lukebarnard1** [comment]
ok, I think I've made the current impl. (https://github.com/matrix-org/matrix-react-sdk/pull/613/commits/d2d78919cefda89c37c3abb8d20700793bde3cd3) slightly too generic - I'll special-case the join/leave and leave/join into single transitions, and then look for consecutive transitions

**Comment by richvdh** [comment]
> regarding ordering: how about we order the groups chronologically (i.e. based on timestamp of the last event in that group).

To be clear, as I understand it, this would mean that 

```
16:44 Cyberops-NSA joined the room.
16:44 Michael Englehorn left the room.
16:45 Michael Englehorn joined the room
```

becomes "Michael Englehorn left and joined, Cyberops-NSA joined".

@ara4n: please confirm.

**Comment by richvdh** [comment]
Oh wait, you probably meant something else:

* A joins, A leaves, B joins -> "A joined and left. B joined."
* A joins, B joins, A leaves -> "B joined. A joined and left."

**Comment by richvdh** [comment]
How about:

* A joins, A leaves, B joins, C joins, C leaves?

**Comment by ara4n** [comment]
Yes, i meant https://github.com/vector-im/riot-web/issues/2856#issuecomment-273216576, not https://github.com/vector-im/riot-web/issues/2856#issuecomment-273216052.

 * A joins, A leaves, B joins, C joins, C leaves? -> "B joined, A and C joined and left."

(as the timestamps of the last events in the A&C group come after the B group).  Although in that specific example it hardly matters that much.

**Comment by lukebarnard1** [comment]
On the current PR https://github.com/matrix-org/matrix-react-sdk/pull/613, I commented :
>I'm not sure why we should order by the last event vs. the first event, or rather I'm not sure which is better. There are also cases where neither ordering by the first nor the last actually produces something accurate:
>
>A joins, B joins, B leaves, B joins, A leaves.
>ordered by first event: A joined and left, B joined and left and joined
>ordered by last event: B joined and left, A joined and left

**Comment by ara4n** [comment]
@lukebarnard1 why would it ever be "B joined and left"? B always "joined and left and joined" surely?  Is this a bug, or am I missing something else here?

**Comment by lukebarnard1** [comment]
Sorry, my mistake. Comments updated.

**Comment by ara4n** [comment]
i agree that it's pretty debatable whether you should order by first or last. thinking more, perhaps first works better.
