### ISSUE TITLE
Can't follow web links with the Linux desktop client

### ISSUE THREAD

**Issue by joelostblom** [vector-im/riot-web#2858]
Links are highlighted in blue, but when I click them nothing happens. There is no output in the terminal window and the link does not open in a web browser. This is the case for both group and single chats, encrypted and not encrypted.

I also sometimes don't get a "Download" link when people attach a file, and if they attach multiple files, only some of them are downloadable. On my phone (android), there are always download links to all attached files.

I tested this with the latest version of the desktop client, 0.9.5.

**Comment by joelostblom** [comment]
I should mention that I am on Arch Linux, so I am not using the prepackaged `.deb` installer. I followed the instructions in README.md to pull from github and build locally.

**Comment by taw00** [comment]
0.9.5 that I built for the Red Hat family of linux'es... works fine.
https://github.com/taw00/riot-rpms

**Comment by richvdh** [comment]
I can't repro this either.

Let's start with the simple case, of unencrypted chats. The 'Download' links have `target="_blank"` which should make electron open the link using the default browser. AIUI, under linux, that means it uses `xdg-open`. Can you confirm that `xdg-open https://www.google.com` works on your machine?

**Comment by joelostblom** [comment]
Thanks for the replies! Yes, `xdg-open` works fine on my machine.

If I view the source on a link I sent to myself in an empty, unencrypted room, it looks like this

```
{
  "origin_server_ts": 1483318741799,
  "sender": "@joelostblom:matrix.org",
  "event_id": "$1483318741191555nixGA:matrix.org",
  "unsigned": {
    "age": 154108464,
    "transaction_id": "m1483318741688.0"
  },
  "content": {
    "body": "www.duckduckgo.com",
    "msgtype": "m.text"
  },
  "type": "m.room.message",
  "room_id": "!WiyfEnIzotxCBXslNn:matrix.org"
}
```

**Comment by joelostblom** [comment]
Here is the source when I upload an image called `C9.jpg` to that room. The thumbnail displays as expected and I see the download link for this image, but when I click it, seemingly nothing happens.

```
{
  "origin_server_ts": 1483473939237,
  "sender": "@joelostblom:matrix.org",
  "event_id": "$14834739391042222UKZCE:matrix.org",
  "unsigned": {
    "age": 505,
    "transaction_id": "m1483473938314.9"
  },
  "content": {
    "body": "C9.jpg",
    "info": {
      "mimetype": "image/jpeg",
      "thumbnail_info": {
        "mimetype": "image/jpeg",
        "h": 600,
        "w": 600,
        "size": 25607
      },
      "h": 2560,
      "thumbnail_url": "mxc://matrix.org/WuDNJZoNXhLAOGjnFdvJBeTJ",
      "w": 2560,
      "size": 176097
    },
    "msgtype": "m.image",
    "url": "mxc://matrix.org/AaHHLCkKGnqnYaJmYuyxSfeB"
  },
  "type": "m.room.message",
  "room_id": "!WiyfEnIzotxCBXslNn:matrix.org"
}
```

**Comment by richvdh** [comment]
Bizarre. If you left-click on the download link, it should show you the link in question. In this case it should be `https://matrix.org/_matrix/media/v1/download/matrix.org/WuDNJZoNXhLAOGjnFdvJBeTJ`. Can you confirm?

**Comment by joelostblom** [comment]
Nothing happens on left click, but when I right click the link or anywhere on the thumbnail, a little window pops up with the address `https://matrix.org/_matrix/media/v1/download/matrix.org/AaHHLCkKGnqnYaJmYuyxSfeB`. This corresponds to the `url` field in the source message posted above, rather than the `thumbnail_url` as you indicated, could that be the problem? When I hover over this url popup, it is highlighted in blue, but when I click it, it seems like nothing happens.

I can also left click the thumbnail to view a bigger thumbnail, with a download link to the right. Again, nothing happens when I left click the download link and the same url address shows up on when right clicking.

**Comment by richvdh** [comment]
That sounds right, I just c&p'ed the wrong URL. 

I'm somewhat out of ideas at this point. It looks like the app is doing all the right things, so the issue is either in the electron wrapper, or on your system. 

If you're familiar with strace, you could try stracing the riot-web process to see what commands it tries to run, which might give some clues.

**Comment by richvdh** [comment]
Also apparently I can't tell left from right. Sorry for the misdirection on that, too.

**Comment by joelostblom** [comment]
I haven't used `strace` before, but it sure looks helpful. I tried it out, let me know if you get any ideas from this, otherwise I will just try to reinstall.

I start riot by running this command from the `riot-web` directory:
```
./node_modules/.bin/electron .
```

Then I find out the PID and attach strace to it like so:
```
sudo strace -tp 10343 -o strace-riot.log
```

I keep strace running for a few seconds and I click the download link of the image 3 times. The log is cluttered, so I filter out some of the lines that are produced in multiples every second, even when I am not doing anything.

```
grep -v 'gettid\|futex\|write' strace-riot.log > strace-riot-filtered.log
```

The out put of the filtered file looks like this
```
13:06:06 madvise(0x28416b7e0000, 32768, MADV_DONTNEED) = 0
13:06:06 madvise(0x3a9d4991c000, 106496, MADV_DONTNEED) = 0
13:06:06 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
13:06:06 madvise(0x3a9d49913000, 143360, MADV_DONTNEED) = 0
13:06:06 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:06:06 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:06:06 mmap(0x1f4372500000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1f4372500000
13:06:07 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 71, 0) = 0x7f54ce1ee000
13:06:07 munmap(0x7f54ce1ee000, 524288) = 0
13:06:07 close(71)                      = 0
13:06:07 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:06:07 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:06:07 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 71, 0) = 0x7f54ce1ee000
13:06:07 munmap(0x7f54ce1ee000, 524288) = 0
13:06:07 close(71)                      = 0
13:06:07 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
13:06:07 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:06:07 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:06:07 madvise(0x3a9d49913000, 143360, MADV_DONTNEED) = 0
13:06:07 madvise(0x3a9d4991c000, 106496, MADV_DONTNEED) = 0
13:06:07 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
13:06:07 madvise(0x3a9d49913000, 143360, MADV_DONTNEED) = 0
13:06:10 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:06:10 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:06:10 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 71, 0) = 0x7f54ce1ee000
13:06:10 munmap(0x7f54ce1ee000, 524288) = 0
13:06:10 close(71)                      = 0
13:06:10 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:06:10 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
```


For comparison, here is the filtered output from when I kept riot open for about as long time, but did not click on the download link:
```
13:09:22 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:09:22 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:09:22 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 48, 0) = 0x7f54ce810000
13:09:22 munmap(0x7f54ce810000, 524288) = 0
13:09:22 close(48)                      = 0
13:09:22 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:09:22 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:09:27 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d49508000, 1048576, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d499bf000, 536576, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d49754000, 270336, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d4980a000, 147456, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d49913000, 69632, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
13:09:27 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:09:27 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
13:09:27 madvise(0x3a9d49508000, 1048576, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d49217000, 2646016, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d49508000, 1863680, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d499bf000, 1085440, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d4979f000, 167936, MADV_DONTNEED) = 0
13:09:27 madvise(0x3a9d49754000, 475136, MADV_DONTNEED) = 0
13:09:27 mmap(0x1c9e23600000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1c9e23600000
13:09:27 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 48, 0) = 0x7f54ce810000
13:09:27 munmap(0x7f54ce810000, 524288) = 0
13:09:27 close(48)                      = 0
13:09:27 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
13:09:27 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
```

Let me know if this is useful and if I should include some of those lines I filtered out.

**Comment by richvdh** [comment]
The trouble is that the interesting things happen in a subprocess. Try passing -f to strace, and grepping for exec. 

On 4 January 2017 18:14:19 GMT+00:00, joelostblom <notifications@github.com> wrote:
>I haven't used `strace` before, but it sure looks helpful. I tried it
>out, let me know if you get any ideas from this, otherwise I will just
>try to reinstall.
>
>I start riot by running this command from the `riot-web` directory:
>```
>./node_modules/.bin/electron .
>```
>
>Then I find out the PID and attach strace to it like so:
>```
>sudo strace -tp 10343 -o strace-riot.log
>```
>
>I keep strace running for a few seconds and I click the download link
>of the image 3 times. The log is cluttered, so I filter out some of the
>lines that are produced in multiples every second, even when I am not
>doing anything.
>
>```
>grep -v 'gettid\|futex\|write' strace-riot.log >
>strace-riot-filtered.log
>```
>
>The out put of the filtered file looks like this
>```
>13:06:06 madvise(0x28416b7e0000, 32768, MADV_DONTNEED) = 0
>13:06:06 madvise(0x3a9d4991c000, 106496, MADV_DONTNEED) = 0
>13:06:06 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
>13:06:06 madvise(0x3a9d49913000, 143360, MADV_DONTNEED) = 0
>13:06:06 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:06:06 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:06:06 mmap(0x1f4372500000, 1048576, PROT_READ|PROT_WRITE,
>MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1f4372500000
>13:06:07 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 71, 0) =
>0x7f54ce1ee000
>13:06:07 munmap(0x7f54ce1ee000, 524288) = 0
>13:06:07 close(71)                      = 0
>13:06:07 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:06:07 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:06:07 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 71, 0) =
>0x7f54ce1ee000
>13:06:07 munmap(0x7f54ce1ee000, 524288) = 0
>13:06:07 close(71)                      = 0
>13:06:07 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
>13:06:07 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:06:07 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:06:07 madvise(0x3a9d49913000, 143360, MADV_DONTNEED) = 0
>13:06:07 madvise(0x3a9d4991c000, 106496, MADV_DONTNEED) = 0
>13:06:07 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
>13:06:07 madvise(0x3a9d49913000, 143360, MADV_DONTNEED) = 0
>13:06:10 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:06:10 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:06:10 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 71, 0) =
>0x7f54ce1ee000
>13:06:10 munmap(0x7f54ce1ee000, 524288) = 0
>13:06:10 close(71)                      = 0
>13:06:10 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:06:10 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>```
>
>
>For comparison, here is the filtered output from when I kept riot open
>for about as long time, but did not click on the download link:
>```
>13:09:22 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:09:22 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:09:22 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 48, 0) =
>0x7f54ce810000
>13:09:22 munmap(0x7f54ce810000, 524288) = 0
>13:09:22 close(48)                      = 0
>13:09:22 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:09:22 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:09:27 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d49508000, 1048576, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d499bf000, 536576, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d49754000, 270336, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d4980a000, 147456, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d49913000, 69632, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d497e3000, 36864, MADV_DONTNEED) = 0
>13:09:27 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:09:27 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>13:09:27 madvise(0x3a9d49508000, 1048576, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d49217000, 2646016, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d49508000, 1863680, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d499bf000, 1085440, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d4979f000, 167936, MADV_DONTNEED) = 0
>13:09:27 madvise(0x3a9d49754000, 475136, MADV_DONTNEED) = 0
>13:09:27 mmap(0x1c9e23600000, 1048576, PROT_READ|PROT_WRITE,
>MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1c9e23600000
>13:09:27 mmap(NULL, 524288, PROT_READ, MAP_SHARED, 48, 0) =
>0x7f54ce810000
>13:09:27 munmap(0x7f54ce810000, 524288) = 0
>13:09:27 close(48)                      = 0
>13:09:27 epoll_wait(21, [{EPOLLIN, {u32=24, u64=24}}], 1024, 0) = 1
>13:09:27 read(24, "\1\0\0\0\0\0\0\0", 1024) = 8
>```
>
>Let me know if this is useful and if I should include some of those
>lines I filtered out.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/2858#issuecomment-270443500

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joelostblom** [comment]
I tried with the `-f` flag but when I grep for "exec" there are no matching lines.

I also tried cloning the repository and building riot again, but same problem. I follow the setup in the readme:

```
npm install
npm install electron
npm run build
node_modules/.bin/electron .
```

Not sure what I am missing here...

**Comment by dbkr** [comment]
Could this be related to https://github.com/electron/electron/issues/1348 ?

**Comment by joelostblom** [comment]
Following links now works as expected both for urls and downloads!

I have not updated Riot since I last posted here, but I have updated other components of my OS, so the bug must have been in some system library originally.
