### ISSUE TITLE
Suddenly not able to decrypt messages from one contact on my phone

### ISSUE THREAD

**Issue by joelostblom** [vector-im/riot-web#2859]
I have been trying out the the encrypted chat features in Riot with a few friends and they have been working really well so far!

They only issues we have run into is that sometimes when a new room is started, people joining that room are having troubles seeing new messages and instead they get `** Unable to decrypt: The sender's device has not sent us the keys for this message. **`. This is usually resolved within a few hours of joining the room.

However, lately my phone (Android) has been having troubles decrypting messages from one of my contact's phone (also android), both in group chats and private rooms. I can still see his desktop messages on my phone, and on my desktop I can see both his desktop and phone messages. He can see all my messages both on phone and desktop. I can still see his old messages and his phone's verification number has not changed, and neither has mine, we have not logged out during the time this happen.

Any ideas of how I could go about troubleshooting this?

**Comment by joelostblom** [comment]
I should mention that I am on Arch Linux, so I am not using the prepackaged `.deb` installer. I followed the instructions in README.md to pull from github and build locally.

**Comment by richvdh** [comment]
Your contact may have been affected by from https://github.com/vector-im/riot-android/issues/799.

**Comment by joelostblom** [comment]
Thanks, that sounds similar to my situation. I tried opening a new chatroom with the same person, but the problem persists. Do you think it would help for me to log out and then in again? I'm a bit reluctant to do this, since I would lose my chat history, but it is more important to be able to chat with this person encrypted for now, so if that would fix it, I will try.

**Comment by richvdh** [comment]
Yes, if either you or they log out and in again, that will fix it. Sorry for the inconvenience.
