### ISSUE TITLE
Require confirmation when clicking logout in login screen

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-web#2862]
I have logged out of Riot destroyting my keys by accident twice.

First time I was moving from another window to Riot when it was in the loading screen and caused logout by accidentallty pressing the log out button.

Just now I logged out when Riot was in loading screen by hitting the other side of screen in Riot window as apparently the logout link width is the whole screen and not only the part of screen that reads "log out".

**Comment by Mikaela** [comment]
Additional issue: logging out that way by accident doesn't remove the device from my devices list.

**Comment by richvdh** [comment]
dup #2068?

**Comment by Mikaela** [comment]
I guess it depends on where the warning will be shown. Above log out button in settings it's not a duplicate in my opinion, pop up screen before actually logging out it's a duplicate.

**Comment by richvdh** [comment]
Yes, we want to make this a popup.
