### ISSUE TITLE
Option to have the user nick and the text left and right, instead of one on top of the other

### ISSUE THREAD

**Issue by subiol** [vector-im/riot-web#2863]
For modern 16:9 and similar desktop computers, by having the messages:

```
(Img) Usernick
      Message of the user
```

takes a lot of the screen quick plus makes the conversation harder to follow.

It would help to have the option of having the format like this:

```
(Img) Usernick         Message of the user
(Img) Otherusernick    Message of the other user
```

Not necessarely by default, just have the option to change it. Also being able to change the font and style would be another good addition.

**Comment by richvdh** [comment]
something to consider for #109

**Comment by ara4n** [comment]
this is the intended solution in #109, so closing as a dup
