### ISSUE TITLE
RFE: desktop versions: A means to alter the font themes

### ISSUE THREAD

**Issue by taw00** [vector-im/riot-web#2865]
I'm old. I need more contrast and larger font sizes.

With the desktop version, I can boost the fontsize temporarily by using the very-browser-like CTRL-+. As soon as I switch to a new room, it resets the fonts to their usual size.

There really should be a setting for size and color sets for the fonts for each pane. I mention color as well because these are related challenges. One of Riot's weaknesses compared to her competitors is the muted color palette with no way to change that contrast.

Thanks for considering. -t

**Comment by taw00** [comment]
Related to <https://github.com/vector-im/riot-web/issues/2460> and <https://github.com/vector-im/riot-web/issues/2300>

**Comment by richvdh** [comment]
What makes this particular to the desktop version?

**Comment by richvdh** [comment]
basically a dup of #377 I think

**Comment by ara4n** [comment]
i've merged this into https://github.com/vector-im/riot-web/issues/660
