### ISSUE TITLE
Firefox wedges whilst trying to display the data URI in the status bar when hovering over E2E images

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2866]
Report from @lowee:matrix.org on firefox-esr 45.3.0 on freebsd that hovering over an E2E image causes FF to grind to a halt briefly whilst trying to display the data URI in the preview section of the browser window on the bottom left

**Comment by ara4n** [comment]
should now be fixed at last by matrix-org/matrix-react-sdk#1864. feedback welcome!

**Comment by jtl999** [comment]
Unable to reproduce with a 10000x10000 10MB PNG file in an E2E room with a friend.

Firefox 59 on Linux.
