### ISSUE TITLE
Riot: Technology used

### ISSUE THREAD

**Issue by djokeefe** [vector-im/riot-web#2867]
If there is a support group somewhere I should be using instead of here, please let me know as I'm a newbie.

Trying to wrap my head around riot and have a few questions. I have installed and used riot on windows, mac, and iOS as well as used it in the browser. I have read everything I can find on it and what I am trying to understand is when I install riot myself on a server, what are the technologies used? But here is what I know so far:

•	Javascript ES6
•	Node.js (for NPM only I think?)
•	React
•	Matrix JS SDK AND React SDK
•	Electron wrapper (for desktop apps), same as Slack

Next step is to actually install riot and set it up which might clear it up for me. But being a web developer, it always comes down to, what is the database, application server and front end. I know the front end is React and is built upon their react SDK, but what is used for the web server and where is the data stored? I am guessing the web server is irrelevant, any can be used but the data storage confuses me.

Anyone who can steer me in the right direction would be appreciated.

Thanks much

**Comment by ara4n** [comment]
Yup, the technology stack you've listed is right.  Node is only used for NPM for package management.
Riot is just a client app (like Chrome or Thunderbird or similar) - it comes with no serverside component.  You use it to talk to Matrix servers, of which there is only one usable one currently - https://github.com/matrix-org/synapse, which is written in Python/Twisted and uses sqlite or postgres as a DB.  You shouldn't need to touch it though when developing on Riot.

Best place for questions like this is #riot:matrix.org, and to get up and running the README for riot-web hopefully is helpful!  I'll close the issue for now as hopefully this answers your q's :)

**Comment by djokeefe** [comment]
Thanks much for the help. A followup question here if I could since we have the context.

So is everyone that is using riot right now using matrix servers and the data is stored there? Reason I ask is I am considering a healthcare application which falls under HIPAA requirements, so I would need to control the data.

I looked at synapse a little, and I understand is written in Python/Twisted which is basically the web server & python controller so to speak. Once I install that on my server I am able to point it to my database?
