### ISSUE TITLE
inconsistent behaviour with redacted join events

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#2869]
When Riot is running and a join event is redacted, the user's displayname is preserved.  When Riot is reloaded, the displayname does not show up and only the MXID is shown.  This happens both in the timeline and in the room members list.

see conversation starting at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14834702191017404Wppar:matrix.org

**Comment by uhoreg** [comment]
This is what is shown when the join event is redacted:
![image](https://cloud.githubusercontent.com/assets/1012976/21620671/7ca87a06-d1c3-11e6-81e4-456cc71bf152.png)
This is what is shown after Riot is reloaded:
![image](https://cloud.githubusercontent.com/assets/1012976/21620765/dd2347f8-d1c3-11e6-97f7-12f9bdb3e79c.png)

**Comment by ara4n** [comment]
dup #3214
