### ISSUE TITLE
Riot fails to remove backslashes if the resulting message is entirely plain text

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-web#2870]
Test vectors:
\\\*correct\\\* because of \*other markdown\* -> \*correct\* because of *other markdown*
\\\*incorrect\\\* -> \\\*incorrect\\\*

https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$14834739331042207DLNXN:matrix.org

**Comment by kyrias** [comment]
I have a fix for this ready already, but it's blocked on matrix-org/matrix-react-sdk#575.

**Comment by ara4n** [comment]
this is super-annoying. I just tried to past `egrep "{PUT-O-(`seq -s \| 497 578`|578)}" homeserver.log.5` into a mainly-IRC channel from Matrix, and the MD totally mangled it on the IRC side, and i couldn't escape it :(

**Comment by kyrias** [comment]
(Anyone feeling like Java or Obj-C development? ;p)

**Comment by ara4n** [comment]
kegan has the con on switching riot-web to commonmark.  we're not going to try to do it in sync with mobile.  this can then land!

**Comment by Kegsay** [comment]
@kyrias : You said you had a fix for this already somewhere? Can has please? 🐱

**Comment by Kegsay** [comment]
Annnd it's merged.
