### ISSUE TITLE
Inbound call notification dialog is partly hidden

### ISSUE THREAD

**Issue by youcha33** [vector-im/riot-web#2884]
<img width="113" alt="screen shot 2017-01-04 at 11 33 17 pm" src="https://cloud.githubusercontent.com/assets/24924955/21663475/5f9f50cc-d2d8-11e6-9fa5-35ed309506a1.png">
This happens often in the MacOS client.

**Comment by ara4n** [comment]
What precise macOS version is this?  And which version of Riot/Desktop?

**Comment by youcha33** [comment]
It is macOS Sierra 10.12.2 and Riot 0.9.5

**Comment by CR0CKER** [comment]
Yep, can confirm this problem on El Capitan.

**Comment by ara4n** [comment]
i would love to know why i've never seen this on El Capitan or anywhere else... :/ Is the room sublist (e.g. favourites) somehow collapsed?

**Comment by CR0CKER** [comment]
The room lists are not collapsed and I don’t see anything else unusual about my setup. Maybe because I only have one contact in the “People” section of the navigation? Two in “favorites” and three in “Rooms”.

**Comment by CR0CKER** [comment]
This doesn't always happen, but every few calls. It's happened to a contact who is on windows as well.

**Comment by youcha33** [comment]
As a workaround for this problem, the dialog appears normally when I reduce the size of the window to around 1/4 of the screen. My screen resolution is (1280x800) Retina.

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/2683
