### ISSUE TITLE
Add option to prevent computer from going idle on a video call

### ISSUE THREAD

**Issue by youcha33** [vector-im/riot-web#2886]

**Comment by ara4n** [comment]
This already exists on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=517870#c41

I'm surprised that Chrome doesn't have something similar. What OS and Browser were you seeing this on?

**Comment by ara4n** [comment]
ah, from the other bugs i'm concluding this is Electron.  You'd hope that it would do the right thing too....

**Comment by t3chguy** [comment]
note to self: https://github.com/electron/electron/blob/master/docs/api/power-save-blocker.md

**Comment by t3chguy** [comment]
I don't think this should be optional, in call it should `prevent-display-sleep`

opinion @ara4n?

**Comment by t3chguy** [comment]
done by #3992
