### ISSUE TITLE
Clicking on a # link in topics of directory search results does nothing

### ISSUE THREAD

**Issue by youcha33** [vector-im/riot-web#2887]
This happens on macOS

**Comment by ara4n** [comment]
I think the request here is for 3PLs to be hyperlinked correctly in topics in the RoomDirectory.

**Comment by pafcu** [comment]
E.g. searching for Riot, in the room directory, and clicking on the links in the #riot:matrix.org topic (e.g. #riot-android:matrix.org) only updates the browser address bar without actually loading the page / closing the room directory. Alternatively, these links miss the `target='_blank'` attribute that the "normal" links have.

**Comment by aaronraimist** [comment]
Is this fixed? I can click on links in topics.

**Comment by turt2live** [comment]
Yea, this was fixed.
