### ISSUE TITLE
Support for nesting channels aka subchannels

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2895]
Slack users like how different slacks group together sets of channels, and miss this grouping in Riot. As well as 'team directories' we should have a way to auto tag or group rooms together. Custom tags may actually be sufficient for this, although the most common request is for nesting.

**Comment by knewter** [comment]
My $0.02 - it's best if they're namespaced (even if this is just at the UI level) so if I join the `#elm` riot channel, I could have channels like `#general`, `#random`, within it, rather than having a million channels at the top like `#elm-general`, `#elm-random`, etc.

**Comment by ara4n** [comment]
This is almost the same as #2454

**Comment by richvdh** [comment]
> This is almost the same as #2454

Yes. What's the difference?

**Comment by ara4n** [comment]
I thought #2454 was asking for the thing where if you join one room it autojoins you to various 'subrooms'.  I was wrong; will add a different bug for that.
