### ISSUE TITLE
Allow data & mxc URLs in img tags in HTML

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2900]
PR matrix-org/matrix-react-sdk#333 whitelisted data URIs for img tags in the HTML sanitizer.  Unfortunately this introduced a vuln where you could do `<img src=//evil.com/tracker.gif/>` given null URL schemes are apparently implicitly in the allowedSchemes list, and got backed out in matrix-org/matrix-react-sdk@8ae210c.  Would be good to get it back again, especially so we can embed mxc URLs nicely in messages for stickers, custom emoji, captioned images, etc.

**Comment by lukebarnard1** [comment]
I've pushed https://github.com/punkave/sanitize-html/pull/137 but I'm not sure the project is active enough for that to go through.

**Comment by lukebarnard1** [comment]
I've pushed https://github.com/punkave/sanitize-html/pull/137 but not sure if it'll get through - activity on that project seems minimal.

We _could_ roll our own version of `naughtyHref` which would not be that painful. That would mean removing all the `href`s that don't validate.

**Comment by lukebarnard1** [comment]
FTR https://github.com/punkave/sanitize-html/pull/137 got merged, so we should be able to whitelist `data:` and `mxc:` if we want 😁

**Comment by ara4n** [comment]
done in https://github.com/matrix-org/matrix-react-sdk/pull/712
