### ISSUE TITLE
Validating email tokens breaks horribly on iOS during signup

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2905]
If the user clicks on a validation email link on iOS during signup, they'll get taken to MobileSafari which will give them an app warning.  If they are in private mode it's even worse - see #2904

**Comment by ara4n** [comment]
assigning to Luke as the whole 'following invites to mobile' is being looked at again for referral stuff.

**Comment by lukebarnard1** [comment]
Hm, this problem _would_ be solved by swapping `/app` for `/referral`, but `/referral` only makes sense from the perspective of the referral campaign and not registrations in general. If this is a more general problem, maybe it should be `/post-register` instead.

**Comment by lukebarnard1** [comment]
I've tested this now. The app suggestion does come down from the top, but in terms of the actual mechanism, registration works fine; it just looks a bit small. It would be _really_ nice if riot.im could redirect the user to the app, with all the tokens for the final steps of the registration (/w captcha).

**Comment by ara4n** [comment]
Okay, if this is actually working then \o/. I've filed an iOS bug for smoothing the registration process.
