### ISSUE TITLE
Users directory / Being able to list local users

### ISSUE THREAD

**Issue by aperezdc** [vector-im/riot-web#2906]
In particular for organizations, it would be interesting to be able to list and search “local” users (i.e. in the same domain / homeserver). This would improve discoverability for new users.

As a workaround, in our self-hosted installation we are considering having a room where everybody is invited, with the sole purpose of letting users discover each other. Having an actual “users directory” would be much better.

Note that this probably needs some thinking to see how it plays with groups. My first (naïve) approach would be that the room directory would allow to see all “local” users, and have also a drop-down to filter by group.

**Comment by ara4n** [comment]
going to close this as a dup of #2930. agreed we need this for groups too (when they land!)
