### ISSUE TITLE
Being banned from a brand new room (that you were never part of) makes it stuck on your client

### ISSUE THREAD

**Issue by kfatehi** [vector-im/riot-web#2907]
I use https://riot.im/app

A few days ago, I was banned from a room shortly after joining it.

Room ID:  !WBDaeTcNCVVjaqxzLn:matrix.org

That room went into "Historical" as one would expect.

Yesterday I login and i see a new room in which the ban list seems to have been manually transferred over.

This seems to have caused riot to think i am actually a participant of this room, when im not and never have been. I also cannot join it in order to leave it, so it is stuck in the "Rooms" section.

This new phantom room has ID: !gnPQuYZyKKZQwGrmjp:matrix.org

**Comment by richvdh** [comment]
dup #1819.
