### ISSUE TITLE
iceweasel and tor browser and others fail modernizr

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2908]
https://twitter.com/motters/status/818559720575422469 - this surprises me

**Comment by bashrc** [comment]
If you need help reproducing this, or logs, let me know.

**Comment by dbkr** [comment]
Working fine for me on TorBrowser 6.0.8 (even through Tor).

**Comment by bashrc** [comment]
One thing I should point out is that I was using the web client option of synapse and not riot-web. It may be that riot-web is perfectly ok.

**Comment by ara4n** [comment]
aaaaah - well, the ancient webclient that synapse ships with is obsolete. we really should be shipping a link to matrix.to or something instead :(
