### ISSUE TITLE
underline doesn't work on RTE

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2912]
you can select text and hit cmd-U or the underline button, but it's not relayed when you send it

**Comment by t3chguy** [comment]
http://spec.commonmark.org/0.26/ doesn't seem to list underline

**Comment by lukebarnard1** [comment]
This seems to have been fixed. 

@t3chguy yeah, that's for markdown though and this is why the "U" button becomes disabled when you turn markdown on;.
