### ISSUE TITLE
We could speed up initial sync by lazyloading and paginating state within a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2914]
E.g., the server could work out the memberlist data required to be shown (i.e. the first N members of the membership list) and avoid having to sync all the state of the room when loading it for the first time.

This feels like it would push a lot of IM-client specific logic into the server however, and reduce the flexibility of the client considerably in how it presents the data. It's possible that #1846 (paginated sync) would be a sufficient win.

**Comment by pik** [comment]
Room leave and join events currently make up the majority of the bandwidth usage on `/sync` - 
https://github.com/vector-im/riot-web/issues/2825#issuecomment-270692398. I guess some of the discussion in https://github.com/vector-im/riot-web/issues/2737#issuecomment-270714234 maybe relevant.

**Comment by ara4n** [comment]
i did this.
