### ISSUE TITLE
Unable to decrypt: Encryption not enabled

### ISSUE THREAD

**Issue by CIAvash** [vector-im/riot-web#2927]
Encryption stopped working for me on Riot web after one of your updates; can't enable It and encrypted messages from Android show up as `** Unable to decrypt: Encryption not enabled **`.

I'm using Firefox 50.1.0.

**Comment by ara4n** [comment]
@CIAvash did this ever fix itself? to debug we'll need javascript logs - can you try hitting 'submit bug report' in User Settings?

**Comment by CIAvash** [comment]
@ara4n After an update the error message became `Unable to decrypt: The sender's device has not sent us the keys for this message.` and then after another update it was fixed and everything started working again. So this issue can be closed.

But now I'm seeing `Unable to decrypt: The sender's device has not sent us the keys for this message.` for some devices on my Android phone. When I tap to see e2e information, Decryption error is `Unknown inbound session id`. I saw #2996 so I didn't report another issue.
