### ISSUE TITLE
Invite button is too hidden at bottom-right

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2932]
Let's move it up to be immediately below the filter field on the MemberList, leaving the  bottom right area blank for now.

**Comment by lukebarnard1** [comment]
This looks roughly like 
![2017-05-19-112429_1128x366_scrot](https://cloud.githubusercontent.com/assets/6750344/26243973/c8ac38d4-3c85-11e7-8cb3-ef66844936a1.png)
in practice, which isn't ideal, especially when filtering as it feels like it's just getting in the way.

How about doing something to the invite dialog and have a suggestion for inviting users conflated with the filtered member list?

![2017-05-19-113029_248x186_scrot](https://cloud.githubusercontent.com/assets/6750344/26244163/934236fc-3c86-11e7-9d1a-8066d2afdf95.png)

**Comment by almereyda** [comment]
Even having the filter box display suggestions for users who are not yet in the room, as in merging it with the box that's presented in the invite pop up, seems a workable path to me.

**Comment by lukebarnard1** [comment]
>How about doing something to the invite dialog and have a suggestion for inviting users conflated with the filtered member list?

>Even having the filter box display suggestions for users who are not yet in the room, as in merging it with the box that's presented in the invite pop up, seems a workable path to me.

Seems we're on the same page, @almereyda :+1:

**Comment by turt2live** [comment]
It's at the top now
