### ISSUE TITLE
"R" logo when searching for users is ugly

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2934]
I think we should remove it for now, until we support searching user directories exposed by bridges, which we don't yet.

**Comment by lukebarnard1** [comment]
@dbkr is this really closed? The "R" is still visible... Surely we could use the "initial" avatars instead?

**Comment by ara4n** [comment]
yeah, i'm not sure why this has been closed.

**Comment by ara4n** [comment]
oh, i guess it's because the double icon got fixed. but rather than ugly R's we should be showing appropriate avatars instead.
