### ISSUE TITLE
Performance on querying Room Directory is still terrible

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2935]
It takes multiple seconds to load the Room Directory, and switch between filters.

**Comment by ara4n** [comment]
this seems to have sped up a bit atm; it's more like 500ms now.

**Comment by richvdh** [comment]
90 seconds here. It's only quick on a local homeserver. See #3327

**Comment by grahamperrin** [comment]
Please, is this still an issue? 

At least with <https://riot.im/develop/#/directory>, performance seems good to me. 

A little delay when (for example) selecting _Freenode_ for the first time, but I guess that's to be expected. The asynchronous progress indicator was not on screen for too long. (Less than ten seconds? I didn't count.)

**Comment by ara4n** [comment]
this got fixed.
