### ISSUE TITLE
Freenode channels should be re-introduced to the main Matrix.org room dir

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2936]
I think we removed Freenode-bridged rooms from the default room directory because they were drowning out other Matrix-only rooms.  I suggest that as soon as we are syncing membership from freenode to matrix https://github.com/matrix-org/matrix-appservice-irc/issues/344 we then add FN back into the main directory list.

**Comment by ara4n** [comment]
this is currently blocked on matrix-org/synapse#1760

**Comment by lampholder** [comment]
This is no longer the desired behaviour.
