### ISSUE TITLE
Need a way to view remote display names of bridged users

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2939]
It's very confusing that I have no idea what nicknames other Matrix users are using on IRC when talking on Matrix - including our own(!).  Profile info for the user should probably track their nickname/displaynames on remote systems so we are not completely blind.

**Comment by ara4n** [comment]
1. As a first cut let's add a ! command.
2. Later on we could provide an API that Riot's MemberInfo could call through to...
3 ...or we could let ASes write arbitrary data into a namespaced part of the extensible profile stuff, which might be useful anyway for ASes to tag arbitrary users with info (except this doesn't work if the user is remote).  Or something.  needs more thought.

**Comment by afranke** [comment]
Is this considered a definitive fix or just a workaround for the time being?

**Comment by Kegsay** [comment]
This fix is:

> As a first cut let's add a ! command.

which is more of a workaround than a definitive fix. A definitive fix would be 2 or 3 on that list, but is far more involved although something which we're going to want to have at some point down the line.

**Comment by afranke** [comment]
Right, then maybe you could keep this report open, or create a new one to track the the long term work?

**Comment by Kegsay** [comment]
The long term solution doesn't really involve Riot: this is a general Matrix problem of how to view remote (bridge) information for users. I'm happy to have an issue for this, but not in this project. Probably `matrix-doc`.
