### ISSUE TITLE
Referral invites

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2941]
As part of supporting use of Riot for teams (#2940), we need to give users the ability to issue invites to their friends which can then get some kind of credit for.  This is different to 3PID invites as this isn't necessarily specific to a given target user, but a generic "please sign up via this link!"

I suggest slapping `?referrer=SECRETCODE` onto the riot.im/app URL that gets handed out to people, and adding a section in User Settings that lets users generate these referrer links.  We should then store the code somewhere serverside in order to be able to refer to it in future (perhaps on the user's extensible profile, once we finally have that?).

We also need to be able to somehow track referrers all the way through to iOS or Android app installs.  Unsure how to best to do that.

Alternatively, GA may provide a way of doing this...

**Comment by lukebarnard1** [comment]
For Riot web, it'd just be a case of siphoning of a query parameter. Is there a way for the mobile apps to use those special links that pull users into them (like `riotim://registration_screen`)? 

Once you have the code, you could PUT some room state to associate a registered user with a referral code. Anyone who was referred could be automatically joined to a "Welcome" room, and the state could be stored there. Could split the welcome rooms by referral code, with one per referrer.

**Comment by ara4n** [comment]
someone needs to research how to get mobile apps installs to track referral data. i think it's possible with some awkward hoop-jumping.

i'm not sure that room state would be a good place to track referral info - we can't guarantee which room they'd first join etc.  I suspect a better bet would be to submit it during registration/login and extend synapse to track it somewhere - or alternatively use extensible profiles to track it in private profile info.

**Comment by ara4n** [comment]
or alternatively we make the user manually enter the referral code in the registration page, a bit like a discount code, if we can't figure out a way to make referral links work to mobile.

**Comment by lukebarnard1** [comment]
Using GA:
- `https://www.riot.im/?utm_campaign=student&utm_medium=referral&utm_source=student_001` is an example URL that GA could use to track a referral from `student_001`. The `utm_source` must be known in advance, there would be one per student ambassador and it could be some randomly-generated base64 string.
- https://support.google.com/analytics/answer/1033863 has details on how to build URLs for iOS and Android.
- To track the referral registration within the iOS app: https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns#overview
- To track the referral registration within the Android: https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#general-campaigns

**Comment by lukebarnard1** [comment]
As per discussion with @AmandineLP and @Ben0001:matrix.org, `utm_source=userId` should be fine for tracking referrers.

**Comment by lukebarnard1** [comment]
FTR the campaign never launched and Riot Team Server has been made half-redundant by Groups, but still could provide referral-campaign tech if we ever wanted to launch one.
