### ISSUE TITLE
Team room directories

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2942]
For team-based registration (#2940) and welcome pages (#2430) it would be great if the RoomDirectory could show subsets of rooms for particular teams.  Ideally this would be done using groups, but before we have that, config.json defined sets of rooms might be good enough.

A way to do this might be to just put a regexp which matches rooms of a given alias or whatever to show them as a group from the main dropdown selector on RoomDirectory.

This is slightly related to #2454 and quite similar to #2906.

**Comment by ara4n** [comment]
we've prioritised #1636 above this one for now.

**Comment by turt2live** [comment]
The team server is not a thing anymore, and there are issues (which I can't find atm) for the equiv groups behaviour
