### ISSUE TITLE
Generate QR codes in RoomSettings to help sharing login details for a chat

### ISSUE THREAD

**Issue by manuschiller** [vector-im/riot-web#2943]
Hi!
Is there the possibility to start a chat / join a group by scanning a QR Code?

**Comment by ara4n** [comment]
Sure. Riot URLs can be taken and QR'd.  I guess the request here is for Riot to generate such a QR code for you in RoomSettings to make it easier to share around.  This overlaps heavily with https://github.com/vector-im/riot-web/issues/3076

**Comment by lukebarnard1** [comment]
We _could_ use https://github.com/kciter/qart.js and put the room avatar as the image :grin: ...
![hq-qr](https://cloud.githubusercontent.com/assets/6750344/23135860/1c65e440-f792-11e6-918b-ad3da121d50d.png)

Although it doesn't look great with some room avatars...

![riot-qr](https://cloud.githubusercontent.com/assets/6750344/23135905/5228d07e-f792-11e6-865c-92ee038e4e05.png)

**Comment by madduck** [comment]
In addition to the pure URL data, I'd find it great to be able to encode

- encryption information, if applicable
- stuff like a custom homeserver URL to be used for login/register

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/877

**Comment by t3chguy** [comment]
:D
