### ISSUE TITLE
Room directory icon is not discoverable enough

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2955]

**Comment by holtopia** [comment]
Most users (including myself, but also others) I've introduced the Riot interface to have been surprised to discover the file folder icon is not related to files or attachments, but instead of directory of places to go.

**Comment by frabcus** [comment]
I had this problem too. When I first used Riot, I went straight into a room.

Then I couldn't work out how to get back out!

It took ages of exploring every button to find the tiny folder icon. The four icons down there are very small and cryptic for primary interface.

Some suggestions:

- put the "Room directory" command at the top of the list of rooms in the very visible sidebar above.
-  guess then the "Create new room" could go in the same place. And "Start chat" in the section for "People".
-  all those icons a bit larger and clearer, preferably with text not just icons.

**Comment by ara4n** [comment]
I've fixed the directory icon, and split out the general button discovery problem to https://github.com/vector-im/riot-web/issues/3704
