### ISSUE TITLE
Hide menu for the desktop version

### ISSUE THREAD

**Issue by schnuffle** [vector-im/riot-web#2962]
I played a bit with the riot desktop version, so I examined the menu on the top. 
After some reasoning I come to the conclusion that the menu is only usefull for people developinng riot, normal user might more be confused by it.

I took a look at what can be easily changed and found a config parameter for the electron-BrowserWindow. I like it, pressing the "Alt" key toggles the menu, so it is still available.

Riot reads in a Preferences file so maybe it could be made a setting but I haven't had a look yet how that gets read in.

Here's the small patch in case somebody else  has the same impression. 

```
diff --git a/electron/src/electron-main.js b/electron/src/electron-main.js
index 675640a..1d15aab 100644
--- a/electron/src/electron-main.js
+++ b/electron/src/electron-main.js
@@ -164,6 +164,7 @@ electron.app.on('ready', () => {
 
     mainWindow = new electron.BrowserWindow({
         icon: icon_path,
+        autoHideMenuBar: true,
         width: 1024, height: 768,
         show: false,
     });
```

**Comment by dbkr** [comment]
Seems like a good compromiseL: PRed as https://github.com/vector-im/riot-web/pull/2975

**Comment by Pulfer** [comment]
Unfortunately, using just Alt for menu is quite bad idea because it's common to switch input layouts using Alt+Shift. So every time people switch input layout the focus jumps from chat window to menu.
