### ISSUE TITLE
there is no way to download an image in an E2E room from the lightbox page on electron

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2970]
download button does nothing; right-click button does nothing

**Comment by dbkr** [comment]
For me, the download link below the message works but the one in the lightbox view does nothing

**Comment by ara4n** [comment]
ah, right. the two in the lightbox fail, but the one below the message works.

**Comment by ara4n** [comment]
apparently #3640 fixes this - thanks @t3chguy!
