### ISSUE TITLE
Need some CSS magic to make team registration look nicer

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#2976]
Following https://github.com/matrix-org/matrix-react-sdk/pull/620, when teams are added to config.json, the reg page looks like this:

<img width="400" alt="screen shot 2017-01-18 at 17 57 22" src="https://cloud.githubusercontent.com/assets/6750344/22074117/96972990-dda7-11e6-9335-10f15b4dee40.png">
<img width="386" alt="screen shot 2017-01-18 at 17 57 11" src="https://cloud.githubusercontent.com/assets/6750344/22074116/969618a2-dda7-11e6-8f85-0c0f86830ad4.png">

We need some CSS to make it look more like
```
.--------------+----------.
|         ldb26|@cam.ac.uk|
'--------------+----------'
                     '---> greyed-out
```

## Updated screenshots for clarity

**Comment by ara4n** [comment]
what about using a custom input textbox control which forces the correct 
suffix to be appended to the field, rather than messing around with two 
input boxes?

**Comment by lukebarnard1** [comment]
That would be fine but the user might find it a bit strange when they can't edit the text box in a normal manner... Although I suppose we could reselect a team based on the given domain part of the email.

**Comment by lukebarnard1** [comment]
A different UI is being used which selects a team based on the field - no drop down needed
