### ISSUE TITLE
Find sustainable funding for the core team

### ISSUE THREAD

**Issue by tuxayo** [vector-im/riot-web#2977]
A follow up of https://github.com/vector-im/riot-web/issues/2075#issuecomment-273462642

@ara4n

> the metrics do directly impact funding for the core team, which frankly is critical for the project; without a core team of funded developers I'm pretty confident that Riot and Matrix dev would grind to a halt - after all, the ambition and scope here across the whole Matrix ecosystem is way more than most do-it-in-your-spare-time FOSS projects.

It's normal to not expect Amdocs to be able to fund Matrix/Riot forever if there is not a significant ROI from it. So it's an important sustainability issue. Are there any ideas that have already been considered?

One possible approach is recurring funding with platforms such as:
- https://salt.bountysource.com/
- https://liberapay.com/
- https://gratipay.com/
- https://opencollective.com/opensource
- https://www.patreon.com

**Comment by ara4n** [comment]
This is something that myself & @AmandineLP spend quite a lot of time thinking about ;)

Amdocs' reason for funding Matrix in the first place is a long-term investment in building out a new communications ecosystem.  If/when Matrix is successful, they can then make money going and selling carrier-grade Matrix deployments to telcos, alongside the PSTN stuff they sell today. This is similar to someone like Cisco donating employee time to work on RFCs etc, on the basis that investing in the internet will let them sell more network hardware to ISPs.

Matrix.org itself is non-profit, and independent of Amdocs, and is being set up as a neutral foundation to nurture and safeguard the standard on behalf of the overall community - a bit like W3C does for the web or XSF does for XMPP.  The process of setting up that entity (i.e. all the governance documents etc) is taking ages, and frankly is slightly lower priority than ensuring the Matrix standard itself is working well, stable and emerging from beta.  However, it is progressing.  Once it's set up, we'll likely look to ways to fund it from the community - e.g. the crowdfunding style approaches mentioned in the earlier comment.

Riot on the other hand is a for-profit startup, currently incubated within Amdocs, which aims to be financially self-sustainable by selling hosted Matrix services in future (specifically, hosted bots/bridges/integrations for use in private rooms; additional storage for private rooms; vhosted and branded synapses/riots etc).  The hope is that this (or other biz models) will be enough to support Riot development (and thus inevitably help Matrix too).

For now, however, both Matrix & Riot are well funded by Amdocs, and by far the best way to contribute is not with $ but by spreading the word, testing the apps, filing bugs, contributing PRs, and generally helping make the project as great as it can be.  Obviously, the second this changes we'll be the first to shout out for donations! :D

**Comment by tuxayo** [comment]
Thanks for all these clarifications, this transparency has a lot of value.

Does Riot has to be a for profit to be financially self-sustainable? (It's about trying to create as much as possible profit for the shareholders isn't it?) Except if it's planned that Amdocs has share in Riot then it's normal that it will be for-profit.

Anyway, this issue can be closed, thanks for your time.

**Comment by ara4n** [comment]
transparency ftw :)

Riot could probably be self-sustainable at its current size as a non-profit, rustling up philanthropic donations from wherever.  But frankly at the current size we don't have enough manpower to do proper justice to the full scope of Riot, let alone support and evolve the wider Matrix ecosystem.  Some of the stuff on the horizon (antispam; decentralised reputation; decentralised accounts; threading; bridges to *everything*) is simply enormous amounts of work - especially to get it to the level of UX polish that things like Slack manage.  Plus it'd be awesome to build more professional stuff on top of Matrix than just Riot!  So we feel the best way to get that kind of resource is to run for-profit, which makes it much easier to become selfsufficient, as well as raise more conventional support.  Obviously it is critical that our funding supports Riot sustainably, and to the direct benefit of Matrix, and we are *very* mindful to avoid any conflict of interest there and play the long term sustainable game rather than "let's maximise profit in the shortest timescale whatever the longer term impact". You just have to trust us not to screw that up though :)

**Comment by tuxayo** [comment]
I get it, we weren't using the same definition of non-profit. I was using the one found here: https://john.onolan.org/what-it-means-to-be-non-profit/

So I didn't mean a charity. But something like Ghost which doesn't prevent it from selling services.

It seems that a non profit dedicated only to the software project is an healthy and sustainable structure.

**Comment by tuxayo** [comment]
OMG you did it! https://matrix.org/blog/2017/07/07/a-call-to-arms-supporting-matrix/

Insta-donation through Liberapay ❤️

**Comment by irelativism** [comment]
I think donations should go through a DAO like system in order to make this project a token sustainable effort,without the need for fiat external investment
similar to what was suggested by a community member on precursor project /betrusted-io/betrusted-wiki/issues/12

**Comment by irelativism** [comment]
I believe this is a actual competitor to the data mining model while respecting FOSS ideals, and in addition the democratizing the last standing hierarchical organization that is business, something very much in need to prevent abuse even if unintended, and reduce incentive to do so by element team members. Setting up the matrix.org project in a stable solid foundation.

**Comment by jryans** [comment]
@irelativism Let's discuss that in Matrix rooms, rather than on this old issue.
