### ISSUE TITLE
commonmark parser not allowing del tags though

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#2982]
so we can't use del tags as strikethrough in commonmark

**Comment by ara4n** [comment]
the code says:

```
var sanitizeHtmlParams = {
    allowedTags: [
        'font', // custom to matrix for IRC-style font coloring
        'del', // for markdown
```

**Comment by dbkr** [comment]
Mm, it's not this actually as the formatted body for the message ends up as:
`<!-- raw HTML omitted -->as shown here<!-- raw HTML omitted -->` so probably the commonmark parser not allowing HTML

**Comment by uhoreg** [comment]
Possibly caused by the "safe: true" at https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Markdown.js#L62, since the "safe" option strips HTML

**Comment by dbkr** [comment]
Fixed now
