### ISSUE TITLE
Integration/Bot suggestions

### ISSUE THREAD

**Issue by gsantner** [vector-im/riot-web#2983]
Hi there, thanks for developing Riot (and also Matrix).
Here are some suggestions (or things that would be great) for integrations/bots:

* <--> XMPP MUC
* <--> Telegram Group

**Comment by Croydon** [comment]
I would also like to see a Telegram bridge :)

**Comment by ara4n** [comment]
Sorry for the delay on this - we've fallen behind on bug triage.

There are already bridges for XMPP MUCs (e.g. https://github.com/pztrn/matrix-xmpp-bridge) and Telegram (e.g. https://github.com/SijmenSchoon/telematrix).  Neither are mature enough to be official integrations, but we'll add them as soon as we can.

For now I'm going to close this, given the bridges do already exist.  You can rest assured that adding them into the integration management UI is on our radar :)
