### ISSUE TITLE
can't disinvite users from 1:1s

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2989]

**Comment by ara4n** [comment]
if you accidentally invite a user, there's no way to withdraw the invite as the other user will have been given equal power in the room.

**Comment by ara4n** [comment]
solution is prolly to only give them equal power after they accept?

**Comment by turt2live** [comment]
I've accidentally duplicated chats twice today - would be nice to be able to do something other than admit to the person that I did something dumb like click through a dialog warning me about duplicate rooms :p

**Comment by aaronraimist** [comment]
Dup #2212

@lampholder

**Comment by lampholder** [comment]
Copy useful bits from this over to #2212 and closing this one; thanks @aaronraimist
