### ISSUE TITLE
We load pointless theme-<name>.js files

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2992]
1.5K each, of nothing but JS comments, for each theme. We don't need extra pageloads on riot startup.

**Comment by richvdh** [comment]
I think this is caused by https://github.com/webpack/webpack/issues/1967.

Until a fix lands for that, we should probably exclude the \<script> tags from index.html via the templating, and remove them before building the tarball.

**Comment by MTRNord** [comment]
From the comments on the upstream issue: maybe worth looking into https://github.com/jamesjieye/html-webpack-exclude-assets-plugin

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/79110428-496f5c00-7d72-11ea-80eb-fb2193296d11.png)
This looks to be resolved
