### ISSUE TITLE
In one direction FF to FF: Unable to decrypt: The sender's device has not sent us the keys for this message.

### ISSUE THREAD

**Issue by DreamFlasher** [vector-im/riot-web#2993]
Setup: I have a chat with another person and I am using multiple devices, amongst those two Firefox on different computers.

I am getting **Unable to decrypt: The sender's device has not sent us the keys for this message.** on one of the FF instances when sent from the other. I have verified all fingerprints everywhere. All other participants can decrypt that message, and in the other direction messages can be decrypted, too.

**Comment by richvdh** [comment]
See #2996 .
