### ISSUE TITLE
Debian Stretch - riot-web incompatible with firejail

### ISSUE THREAD

**Issue by roadkillazpartybird** [vector-im/riot-web#3004]
riot-web does not work with firejail, there is also no firejail profile for it.

```
$ firejail riot-web
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 10699, child pid 10700
Child process initialized
Gtk-Message: Failed to load module "canberra-gtk-module"
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform
[2:0120/155622:FATAL:udev_linux.cc(20)] Check failed: monitor_. 
#0 0x000001e5839e <unknown>
#1 0x000001e6e09b <unknown>
#2 0x000000cbe566 <unknown>
#3 0x000001248442 <unknown>
#4 0x000001e59066 <unknown>
#5 0x000001e74595 <unknown>
#6 0x000001e74888 <unknown>
#7 0x000001e74cdb <unknown>
#8 0x000001e4e4a9 <unknown>
#9 0x000001e8d25e <unknown>
#10 0x000001eac24a <unknown>
#11 0x000002707c76 <unknown>
#12 0x000002707e7e <unknown>
#13 0x000001eac30e <unknown>
#14 0x000001ea8893 <unknown>
#15 0x7f1ec95d5464 start_thread
#16 0x7f1ec303e9df clone


Parent is shutting down, bye...
```

If someone who's smarter and cooler then me could fix that i'd be grateful.

**Comment by carlos22** [comment]
I think you need to look to get electron running. Because riot-web is using electron (which is a kind of a headless chromium the browser chrome is based on). There is no electron profile either, but there is one for google-chrome. You can try it, but i doubt it helps much...

**Comment by richvdh** [comment]
This doesn't sound like a riot-web bug to me.

@carlos22 sounds like he is talking sense.

**Comment by ara4n** [comment]
yup. the bug here sounds a lot like electron itself not being supported on firejail, not riot-dev. i'm afraid the best i can suggest is to work with the firejail community to work out how to use it with electron.  none of the Riot dev team can help here :/

**Comment by aidalgol** [comment]
I have created a profile for riot-web in https://github.com/aidalgol/firejail/tree/riot-profile and have submitted a pull request to the upstream firejail project.  In the meantime, you can take it straight from my repo.

**Comment by Fred-Barclay** [comment]
We've merged the profile into firejail - thanks @aidalgol!
