### ISSUE TITLE
clicking with mouse button 3 on a username causes Firefox to leave the page

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3007]
as reported by @ lowee:matrix.org at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$148492897077502SwEaQ:matrix.org

Clicking on a username above their message in the chat log, e.g.
![image](https://cloud.githubusercontent.com/assets/1012976/22157447/c7721354-df05-11e6-8e20-1cf49e7677b5.png)
causes Firefox to paste the username in the URL bar and try to load it as a web page.  It happens intermittently, and happens when the clipboard is empty.

**Comment by ara4n** [comment]
someone who knows something about linux WMs and FF behaviour will have to advise on this...

**Comment by yannicka** [comment]
Do you still have the problem?

**Comment by t3chguy** [comment]
Cannot reproduce, but I think the anchor got turned into an AccessibleButton which should resolve any Mouse 3 behaviour.
