### ISSUE TITLE
consider @ here support

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3010]
lots of people expect @-mentioning here will bing folks whose presence is currently active in a room. This might be more palatable than an @-all

**Comment by uhoreg** [comment]
It may also make sense to make this a per-room setting, in order to reduce spam potential.

**Comment by MightyCreak** [comment]
It's a very used feature with Slack at my job. It allows to notify a channel about something that would interest all of them. It's clear that there is a spam potential, so I think the option should be disable by default, and it's up to the admins or the moderators to enable it.

I'd like to highlight a subtlety: in Slack, `@here` will notify every active people in the channel while `@channel` will notify everyone in the channel, active or not. So for instance, you'll use `@here` if you want an answer to a question while you'll use `@channel` when you want to broadcast a message.

If possible, it would be nice if Riot could have the same keywords (maybe something like `@here` and `@room`).

**Comment by t3chguy** [comment]
closing in favour of #2440
