### ISSUE TITLE
the debian riot-web electron package should probably be called riot-desktop

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3012]

**Comment by uhoreg** [comment]
or just "riot"

**Comment by ArchangeGabriel** [comment]
ArchLinux user here, we’re also waiting on input here regarding packaging names. ;)

We’re going to have both the electron package and the web one, so maybe `riot-desktop` is more appropriate.

**Comment by ara4n** [comment]
yeah, i agree that riot-desktop is a better name, especially given riot-web may be packaged as a proper webapp separately (although this would then clash with the old riot-web package name; perhaps riot-webapp might be better for that package and kill off riot-web).

**Comment by ArchangeGabriel** [comment]
On ArchLinux, we went for riot-web and riot-desktop, the latter being only the electron files and thus depending on riot-web for the actual app content. ;)

**Comment by t3chguy** [comment]
Done!
