### ISSUE TITLE
Big modal dialogs randomly scroll to the bottom when loaded

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3018]
i think this is because the dialog starts off with tiny vertical height, and then expands after the component is loaded, leaving the scroll offset very confused

**Comment by richvdh** [comment]
If this is referring to the `EncryptedEventDialog`, it's nothing to do with the asyncness of it - it's because the OK button is `autoFocus: true`, which makes it scroll into view.

**Comment by richvdh** [comment]
presumably the right fix to that is to collect "enter" keypresses in the dialog rather than autofocussing the button. In general we probably want to factor the escape/enter handling out of all the dialog impls.

Matthew: can you confirm if this was the bug you meant, or if I have misunderstood?

**Comment by ara4n** [comment]
yup, this would be the bug - i hadn't spotted the `autoFocus: true`.  However, i think a better solution would be not to scroll the buttons off the bottom of the dialog, which is horrific UX, but instead chuck a gemini scrollbar on the body of the dialog if it insists on being too large.

**Comment by richvdh** [comment]
Not obvious to me that losing the top of the dialog is much better than losing the bottom, but ok

**Comment by ara4n** [comment]
I'm not suggesting losing the bottom of the dialog, only its body.  I'm 
suggesting you show the body, scrolled to top as per any sane windowing 
system, given humans read information top-to-bottom.  But the buttons 
are always visible on the bottom.

**Comment by richvdh** [comment]
ah, sorry, missed that.

**Comment by richvdh** [comment]
The mechanics of adding a geminiscrollbar to the dialog are trivial.

The CSS-fu to make the dialog fill just the right amount of the screen, however, appears to be beyond me. I spent a while messing about with flex layouts and nothing seemed to work. Hope @ara4n can help!

**Comment by ara4n** [comment]
I've fixed this for the case of UnknownDeviceDialog in matrix-org/matrix-react-sdk@5e5b7f8. I'm not sure it's worth applying it to EncryptedEventDialog too, which generally will fit on the page.

**Comment by richvdh** [comment]
I wouldn't bother. Think it's fine to fix the dialogs case-by-case.
