### ISSUE TITLE
Async dialog loader breaks ability to verify devices

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3020]
The previous e2e info dialog relied on being able to switch to the verification dialog when you hit a verify button.  This now breaks in exotic ways.  I suggest we either make it sync again (why do we care about loading the component async here? it's tiny!) or we implement stacked dialog boxes like any other windowing environment.  This also breaks my new UnknownDeviceDialog.

**Comment by richvdh** [comment]
Yeah there's no need for this, of all things, to be async. I picked it as a demo of asynciness which was so simple it couldn't possibly break. Haha. 

Will take a look tomorrow.
