### ISSUE TITLE
Room directory icon changes

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3023]
The room directory icon starts out with an "empty" middle, like this:
![image](https://cloud.githubusercontent.com/assets/1012976/22183707/d5deb838-e091-11e6-9a77-3dfa6344db12.png)
If I mouse over it (or mouse over certain other things), the middle gets filled in, like this:
![image](https://cloud.githubusercontent.com/assets/1012976/22183758/275e60e0-e093-11e6-83e7-a88b45745ab7.png)

**Comment by uhoreg** [comment]
Seems to be fixed now.

**Comment by uhoreg** [comment]
Actually, seems to still be happening. :(

**Comment by uhoreg** [comment]
The same issue might also be causing this in the dark theme:
![image](https://cloud.githubusercontent.com/assets/1012976/22344232/5dc5e1b0-e3c9-11e6-822f-76c86cf13675.png)

**Comment by uhoreg** [comment]
I suspect it only happens when you switch back and forth between themes.  After a reload, things seem to work properly.

**Comment by uhoreg** [comment]
BTW, this was all in Revolt

**Comment by ara4n** [comment]
this has to be a bug in Revolt.  I have zero idea what would be causing it though; we don't change the images on mouseover :/  The 'filled in' images are older versions of the artwork.  It almost looks like it's switching between SVG and PNG somehow on mouseover?

I have absolutely no idea what's going on here, nor can I reproduce it.  Might be worth filing it against Revolt...

**Comment by uhoreg** [comment]
Agreed.  I've been using the desktop app for a while and not seeing any the same behaviour.  Opened [aperezdc/revolt#45](https://github.com/aperezdc/revolt/issues/45).
