### ISSUE TITLE
Provide the .svg icon somewhere?

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#3029]
I’m wondering why the riot.svg file isn’t provided in this repo? Currently packagers have to manually add it to their sources, like we do in Arch Linux: https://aur.archlinux.org/cgit/aur.git/plain/riot.svg?h=riot.

I think it would be better to provide it here. ;)

BTW, I don’t know why the name as changed since I’m quite new here, but for me vector was a better name and had a better icon. But I suppose this is because I’m a scientific geek. :p

**Comment by ara4n** [comment]
Just an oversight - now added at https://github.com/vector-im/riot-web/commit/706ffbec3c2eb41d67587ace8e01dd3c7df0e03b

N.B. that Riot deliberately has a whole set of alternative logos.

And yes, I miss the Vector name & icon too.  But I too am a scientific geek...
