### ISSUE TITLE
Self-typing notifications should never show up.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3034]
![image](https://cloud.githubusercontent.com/assets/1294269/22217869/f1160016-e1a4-11e6-9b91-37a3f6194e2d.png)

@lukebarnard1 looks like a bug in the new stacked up typing notifs.  My avatar should not be there.

**Comment by lukebarnard1** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/637
