### ISSUE TITLE
Riot displays blank white screen after waking computer from sleep

### ISSUE THREAD

**Issue by jimmycuadra** [vector-im/riot-web#3038]
Latest macOS, latest Electron version of Riot (although this isn't a new problem in Riot, it's happened as long as I've used it.)

After waking the computer from sleep, Riot's window is just blank white. It never loads, even if I leave it open for a long time. I have to quit the application and relaunch it for it to connect and display normally.

**Comment by ara4n** [comment]
i suspect this is a variation on a theme of #2951.
