### ISSUE TITLE
Issue with self signed certificates and windows app

### ISSUE THREAD

**Issue by daveb778** [vector-im/riot-web#3039]
I have noticed the apps dont like the certs that the server makes, ive been able to get around this by adding a conception in the browser but how would i go about that in the windows app? I also attached a screenshot of the message i am receiving.

![image](https://cloud.githubusercontent.com/assets/18433196/22238401/1bc79038-e1df-11e6-89ec-2c214d93d487.png)

**Comment by daveb778** [comment]
Also another odd bug i noticed is that when i enable url previews in the config the server will refuse to launch. 
![image](https://cloud.githubusercontent.com/assets/18433196/22238378/0cf6dc80-e1df-11e6-8e3d-70d61c9f63da.png)

**Comment by dbkr** [comment]
See https://github.com/vector-im/riot-web/issues/3003
