### ISSUE TITLE
Long device lists cause rendering issues with direct chats section of sidebar

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3050]
Test case:

1. Have a direct chat with someone that has lots of devices (causing a scrollbar)
2. Click on that user to bring up more information in the right sidebar

The sidebar is correctly rendered up until the device list loads.

Examples of rendering misbehaviour (enough devices to cause a scrollbar):
![image](https://cloud.githubusercontent.com/assets/1190097/22264932/24befe94-e237-11e6-8ffa-48f2fbb7b201.png)
![image](https://cloud.githubusercontent.com/assets/1190097/22264938/2d5362c0-e237-11e6-9b6e-cce4e9b9a5f3.png)

Examples of rendering correctly (few devices):
![image](https://cloud.githubusercontent.com/assets/1190097/22264992/63393356-e237-11e6-9e73-6e82711b8d84.png)
![image](https://cloud.githubusercontent.com/assets/1190097/22265001/6c5f7daa-e237-11e6-94b9-26d4943846eb.png)

**Comment by ara4n** [comment]
hopefully fixed by matrix-org/matrix-react-sdk@df625b0
