### ISSUE TITLE
Riot has stopped syncing messages

### ISSUE THREAD

**Issue by C0rn3j** [vector-im/riot-web#3054]
http://i.imgur.com/ti4BgXt.png

Can't accept invites, chat, or do anything since about midnight(UTC+1).

Doesn't work on the web, linux client or my android phone.

account - @C0rn3j:matrix.org

I can provide more info if needed.

**Comment by tessgadwa** [comment]
I am experiencing this as well.  @rosecheval:matrix.org

**Comment by migscabral** [comment]
I am experiencing this as well both mobile and web @migscabral:matrix.org

**Comment by C0rn3j** [comment]
Seems like it just started syncing again

**Comment by richvdh** [comment]
`matrix.org` was down overnight
