### ISSUE TITLE
Riot web client, unable to join room

### ISSUE THREAD

**Issue by roadkillazpartybird** [vector-im/riot-web#3055]
Hi!

Using the riot web client with Firefox 45.6/Linux.

After trying to join i room (Matrix HQ) i received the error message:

CORS request rejected: https://matrix.org/_matrix/client/r0/join/%23matrix%3Amatrix.org?access_token=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI0Y2lkIHVzZXJfaWQgPSBAZW1vb246bWF0cml4Lm9yZwowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IGUtQnhhMm9SVGZPd29HUWcKMDAyZnNpZ25hdHVyZSC7kSMqaQuIWBKZm64TshZu1WXqUcjJRY1qWLaRcyJnFgo

retrying gives me the same kind of error message.

**Comment by richvdh** [comment]
`matrix.org` was down overnight.

**Comment by roadkillazpartybird** [comment]
Yes, it worked just now, thank you.
