### ISSUE TITLE
Feature request: public vs private PC option on login to save e2e key in local storage

### ISSUE THREAD

**Issue by mogorman** [vector-im/riot-web#3058]
It would be nice if there was a public vs private pc checkbox on login. If this was an option we could save the e2e key into local storage for private pcs, while still maintaining security when roaming.

**Comment by richvdh** [comment]
Suggest you use incognito mode in your browser.

**Comment by mogorman** [comment]
no. im sorry if i wasnt clear.  currently if you sign out on the web mode, your e2e key is chucked. so when you log back in you cant see previous messages.  I am suggesting having a checkbox so that the key can be saved to local storage. that way i can log back in and not miss messages.

**Comment by richvdh** [comment]
oh. don't sign out then?
