### ISSUE TITLE
Add indicator to Riot client on macOS reflecting the last seen msg in a chat

### ISSUE THREAD

**Issue by foss-** [vector-im/riot-web#3068]
Problem: Currently there is no UI indicator of the last seen position in a chat.

Expected: When leaving riot desktop client in the background or working on other stuff or even closing and reopening after 2 days, it would be fantastic if there was an indicator in the scrollbar on the right-side, clearly showing where the last read message is, so it can be scrolled to easily and unread msgs can be catched up with.

Many IRC clients do this (when remaining open, they don't cover the closed app case).

**Comment by richvdh** [comment]
think this is a dup of #1146
