### ISSUE TITLE
#mozilla_#rust has disappeared from the room list

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3070]
I didn't leave the room, and I can see it in the room list from another Riot instance (a locally-built one...).

When I tried to join the room, I got a brief "You are trying to access a room, do you want to join it", then that quickly disappeared as Riot realised that I was in fact already joined.

Update: The room is gone from the room list when I refresh Riot

**Comment by richvdh** [comment]
This will probably have been due to https://github.com/matrix-org/synapse/issues/1935. @lukebarnard1: what is the state of play for you with this now?

**Comment by lukebarnard1** [comment]
That looks likely (I was indeed mostly lurking). I decided to leave the room a while back because it was causing other problems at the time.

**Comment by richvdh** [comment]
it should be better in synapse 0.20, fwiw.

let's consider it fixed for now.
