### ISSUE TITLE
What difference between PEOPLE and ROOMS?

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-web#3075]
Looks like there is no difference between them, right? So why make this distinguish?

**Comment by uhoreg** [comment]
The "People" section is for rooms marked as Direct Chat, whereas the "Rooms" section is for rooms that are not Direct Chat.

**Comment by dbkr** [comment]
Closing as this appears to be a question rather than a bug (and has been answered with no response for over a week).
