### ISSUE TITLE
Overlapping typing notifications don't correctly show avatars for people without avatars set (see image)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3084]
![image](https://cloud.githubusercontent.com/assets/1190097/22378468/f1c6b264-e472-11e6-8fb6-ed1c35093307.png)

Above, hov and holly are typing. Both don't have avatars, and therefore both should be `H` in a circle. Individually they work, but together one gets the `H` removed.

Theme change does not appear to affect result (light or dark). Witnessed on Chrome 55.

**Comment by ara4n** [comment]
i saw this too today.

**Comment by lukebarnard1** [comment]
This is an intentional design due to the intricacies of CSS z-indices... I couldn't manage to wrangle the CSS to have incremental z-indices based on the order of the avatars, so I just ended up preventing all but the last avatar from having an initial.

**Comment by ara4n** [comment]
ew. the fix here is probably just to make each avatar position relative, which then kicks off its own subset of z-index space, iirc.

**Comment by lukebarnard1** [comment]
So the z-index of the initial itself is set to 1, which puts it above the solid colour image... Maybe we could use a background colour here? If you get rid of the z-index on the initial, the avatars display correctly z-indexed.

**Comment by ara4n** [comment]
that could work. but unless i'm completely making it up, you can use position: relative to isolate different sections of z-index from each other.

See the first answer to: http://stackoverflow.com/questions/8986071/how-to-use-z-index-with-relative-positioning

So all you should have to do is make each avatar element position relative, or put each one in a separate wrapper that is.

-- 
Matthew Hodgson
Matrix.org
