### ISSUE TITLE
add gitter back to room directory

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3086]

**Comment by dbkr** [comment]
Things needed for this:
 1. Make gitter AS publish a `network_id`. We did this but neglected to do the other bits.
 1. Sort out the `icon` disaster, ie. decide where the icons appear and whether they are mxc urls or http urls - https://docs.google.com/document/d/13NGa46a_WWno-XYfe8mQrglQdtOYMFVZtxkPKXDC3ac/edit#heading=h.m0btedxhv6ao says mxc but reality doesn't reflect this, and riot doesn't support mxc URLs.
 1. Make the gitter AS publish rooms to its own directory list: https://github.com/matrix-org/synapse/pull/1676/files#diff-3f2ae6df6c03245c966e4380f79a904cR192
 1. Move the existing gitter rooms over to that list (`select 'gitter', 'gitter', room_id from matrix.room_aliases where room_alias like '#gitter_%:matrix.org';`)

**Comment by leonerd** [comment]
Initial rollback done: https://github.com/matrix-org/matrix-appservice-gitter/commit/8d79ae866d8023bef7e377d212024ef2ad4bd71f

**Comment by dbkr** [comment]
Above PR allows riot to use mxc URLs for the icon

**Comment by ara4n** [comment]
gitter is still not back in the room directory, 3 weeks later >:(

**Comment by lukebarnard1** [comment]
Change made to the IRC bridge: https://github.com/matrix-org/matrix-appservice-irc/pull/306

**Comment by ara4n** [comment]
@leonerd: 

1. sorting an icon should be trivial. just use an http url.
2. crib the code from https://github.com/matrix-org/matrix-appservice-irc/blob/develop/lib/bridge/PublicitySyncer.js#L205
3. one-liner
4. @dbkr can help you move the old rooms over once it's done.

**Comment by leonerd** [comment]
I have some code that might work but currently finding it hard to test if it actually works, because most of the relevant synapse APIs to do so appear to be entirely undocumented :/

Currently blocking me: I don't know how to drive the `/_matrix/client/r0/publicRooms` API to make queries regarding third-party published aliases.

**Comment by leonerd** [comment]
Ah; apparently the trick is to `POST` to it, not `GET`. So yes this seems to work.

**Comment by leonerd** [comment]
Code is now ready; https://github.com/matrix-org/matrix-appservice-gitter/commit/971c5fe309f6685a3b0887eca0e41d6951597643
Solves 2 and 3 above.
Solving 1 can be done with a config file edit if required.
@dbkr - are you in place to be able to assist with part 4 - updating the existing publications?

**Comment by leonerd** [comment]
2+3 is now installed and running live.

**Comment by leonerd** [comment]
1 done by https://github.com/matrix-org/internal-config/commit/4e2f7fc722ac39e37bb68952e5844e7ae9df4bf4

**Comment by leonerd** [comment]
Hm.. Doesn't appear to be working yet. The unfiltered public rooms list still shows the gitter ones; and the filtered list shows nothing at all.

**Comment by leonerd** [comment]
Turns out that raw database fiddling didn't work. But going in by the front door properly appears to; namely:

    $ for ROOM in `cat gitter-room-ids.txt`; do echo "$ROOM"; matrixtool client -u @gitterbot:matrix.org json "/_matrix/client/r0/directory/list/appservice/gitter/$ROOM" '{"visibility":"public"}'; done

**Comment by leonerd** [comment]
Hmm. Well, almost. The rooms now appear on the gitter filtered list as required. But they also appear on main public rooms list as well.

**Comment by leonerd** [comment]
Ah, it seems that so too do rooms of other bridges - I see mozilla and freenode in there at least also. So I think this is done.
