### ISSUE TITLE
Timed messages room setting

### ISSUE THREAD

**Issue by zpskj** [vector-im/riot-web#3088]
It would be nice to be able to set a room to automatically redact messages older than X days/hours. Although this can't be relied on as a security feature, as you can't stop someone recording messages, it is a major convenience rather than everyone in the room having to manually delete old messages. 

Is this planned?

**Comment by ara4n** [comment]
redacting wouldn't be the way to do this, but setting up retention periods for different rooms. this is basically https://github.com/vector-im/riot-web/issues/3177
