### ISSUE TITLE
Turning e2e on by default

### ISSUE THREAD

**Issue by zpskj** [vector-im/riot-web#3089]
An option to set all new rooms as end-to-end encrypted by default would be very handy, for users that want their communications to be encrypted. It currently is very easy to accidentally start sending someone messages before realizing they're unencrypted, particularly when direct messaging someone from an encrypted room.

**Comment by uhoreg** [comment]
I believe that the plan is to enable it by default in private rooms once e2e is out of beta, but there are still issues that would make it very frustrating for people to use.

**Comment by AlexDaniel** [comment]
“but there are still issues that would make it very frustrating for people to use”

Is there a list of these issues somewhere?

**Comment by uhoreg** [comment]
@AlexDaniel #2996, as well as #2142 and #2714, and maybe #4522

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/projects/5
https://github.com/vector-im/riot-meta/issues/63
fwiw

**Comment by ara4n** [comment]
oops, i just accidentally dupped this by https://github.com/vector-im/riot-web/issues/6779
