### ISSUE TITLE
Security Headers

### ISSUE THREAD

**Issue by indolering** [vector-im/riot-web#3090]
I have experience with Content Security Policy headers and sandboxing single-page-apps.  Let's start out with what you have considered doing in the past?

**Comment by ara4n** [comment]
erm, what is the bug here? if you've found a problem with our CSP or an XSS please disclose to security@riot.im.

**Comment by indolering** [comment]
Ahh, I've worked this out in another repo!

**Comment by indolering** [comment]
Oh, nm, looks like I mixed up a similar request.

I haven't found a specific XSS and as far as I can tell you don't seem to be passing any CSP headers to the client, using iFrames to sandbox message content ... are you even running messages through a sanitizer?

**Comment by ara4n** [comment]
> I haven't found a specific XSS and as far as I can tell you don't seem to be passing any CSP headers to the client,

The only place where we should send user generated content to Riot is: https://github.com/matrix-org/synapse/blob/master/synapse/rest/media/v1/download_resource.py#L50
> using iFrames to sandbox message content ...
> 
iframes are only used to sandbox the special case of displaying end-to-end-encrypted user generated content which has been locally decrypted by javascript.
> are you even running messages through a sanitizer?
> 
https://github.com/matrix-org/matrix-react-sdk/blob/master/src/HtmlUtils.js#L83

Is there actually a bug being reported here?
