### ISSUE TITLE
make sure that error messages don't display the access_token

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3098]
so that people don't post screenshots with their access token, e.g. in https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$14858131272616rvGgR:disroot.org or https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1485793133542mKYgZ:im.nostrodomo.tk

("CORS request rejected: ..." isn't a particularly user-friendly error message anyways)

**Comment by uhoreg** [comment]
It looks like there are a couple issues already about the "CORS request rejected" error message.  In addition to fixing the specific place(s) where that error gets shown, it would probably be good if the error dialog did something like a "s/access_token=[^& ]/access_token=[redacted]" just in case other things try to display the access token.

**Comment by richvdh** [comment]
Another solution to this would be to move the access token into the request headers, per https://github.com/matrix-org/synapse/pull/1098.

**Comment by Kegsay** [comment]
This is surely a trivial one liner in the JS SDK?

**Comment by Kegsay** [comment]
... or it would be if the "MatrixClient crypto" tests didn't then fail.

The diff was:
```
$ git diff
diff --git a/src/http-api.js b/src/http-api.js
index 761a552..00908b5 100644
--- a/src/http-api.js
+++ b/src/http-api.js
@@ -385,8 +385,14 @@ module.exports.MatrixHttpApi.prototype = {
         if (!queryParams) {
             queryParams = {};
         }
-        if (!queryParams.access_token) {
-            queryParams.access_token = this.opts.accessToken;
+        if (!opts) {
+            opts = {};
+        }
+        if (!opts.headers) {
+            opts.headers = {};
+        }
+        if (this.opts.accessToken) {
+            opts.headers["Authorization"] = "Bearer " + this.opts.accessToken;
         }
 
         const request_promise = this.request(
```

**Comment by uhoreg** [comment]
kythyria mentions in https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1488941883207PLlSe:berigora.net that moving the access token to the headers would double the number of HTTP requests, since each request would have to be preceded by an OPTIONS HTTP request due to CORS.

**Comment by richvdh** [comment]
Most requests already have a CORS preflight. I don't think that concern outweighs the problems of having the access token in the query string. 

On 8 March 2017 05:08:05 GMT+00:00, Hubert Chathi <notifications@github.com> wrote:
>kythyria mentions in
>https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1488941883207PLlSe:berigora.net
>that moving the access token to the headers would double the number of
>HTTP requests, since each request would have to be preceded by an
>OPTIONS HTTP request due to CORS.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/3098#issuecomment-284948292

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ara4n** [comment]
i've gone through cleaning up all the error msgs to never blindly past JS errors into the dialog box.
