### ISSUE TITLE
Can't use /topic to see full topic 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#3100]
Part of the issue is outlined in https://github.com/vector-im/riot-web/issues/1729

But part of the issue I'm documenting. I like to run /topic to know the topic. As can be seen, sometimes the whole topic (even in IRC clients) isn't displayed properly so having them in the message window displayed lets me know what is going on. 

![quassel-long-topic-spilling](https://cloud.githubusercontent.com/assets/727626/22461892/2c591db6-e7d1-11e6-93d4-5292d1ca31ce.png)

The below one is when I do /topic in speech. 

![quassel-topic-in-message-window](https://cloud.githubusercontent.com/assets/727626/22461916/4093a6ac-e7d1-11e6-868c-756db22a96ea.png)

I hope the pictures speaks for themselves.

**Comment by richvdh** [comment]
I'm slightly unclear - you're expecting `/topic` alone to show you the existing topic?

**Comment by shirishag75** [comment]
@richvdh - yes exactly - in the message window like when we chat. You could try it in quassel or any IRC client. In RIOT `/topic` apparently is for changing the topic and not getting the topic.

**Comment by richvdh** [comment]
Makes sense.

**Comment by richvdh** [comment]
Related to #1836

**Comment by aaronraimist** [comment]
Seems to be fixed
