### ISSUE TITLE
Add option to prune history after a certain time

### ISSUE THREAD

**Issue by rubo77** [vector-im/riot-web#3104]
Usually the history for a room is kept forever, but we should add an option in the room settings to use the prune api to clean up the room older than a certain timeframe.

This will not delete the messages from all federated servers, so you can still scroll back and recover pruned messages eventually (which also _can_ be desired).

Additionally we should add a button to automatically "redact" all old messages before prunigng them, so they are _not so easily_ recoverable by standard clients (this would be needed first: https://github.com/matrix-org/synapse/issues/1730 )

Be aware, that this is just a little **enhancement of the current state** where no old messages are deleted. Messages are not securely deleted this way! Only old messages that were not federated to any other synapse servers (i.e. private rooms) are deleted completely this way.

This enhancement will be a very useful frontend-cleanup of old messages.

**Comment by Tarnatos** [comment]
+1

**Comment by rubo77** [comment]
Maybe this issue is just about the buttons in the admin panel and the rest has to be done in the synapse issue.

**Comment by ara4n** [comment]
this is entangled with https://github.com/matrix-org/matrix-doc/issues/440

**Comment by roadkillazpartybird** [comment]
Agreed, it should be set per-room i think. The default mode should be for no auto-deletion but there should be an option too.

**Comment by ara4n** [comment]
see also matrix-org/matrix-doc#447

**Comment by ara4n** [comment]
closing as dup of #3800
