### ISSUE TITLE
Possible to get a sent message stuck to the bottom of the timeline

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3109]
I typed a message into Riot, waited for it to go black and then immediately closed and unplugged my laptop. This message is now stuck at the bottom of the timeline.

Inspecting the state, this message is in the list of pending events for the room with state 'sent' but just doesn't seem to be going away. The same message also appears in the timeline at the appropriate place.

Sounds like the event stays in pending until the echo comes down, but the echo failed to come down before I closed my laptop, and by the time I opened it again, enough had happened in the room that the event didn't arrive in a gapped initial sync, and the js-sdk isn't smart enough to deal with this situation.

**Comment by Ralith** [comment]
I've observed this behavior as well, when synapse was under very heavy load.

**Comment by richvdh** [comment]
dup #1541

**Comment by Kegsay** [comment]
I'm guessing the correct way to fix this is to remove pending messages when the room gets a gapped sync, if the message is marked as SENT.
