### ISSUE TITLE
Disable E2e import/export buttons on Safari

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3112]
Apparently webkit doesn't support the necessary webcrypto primitives. We should disable the relevant buttons.

**Comment by aaronraimist** [comment]
The import button at least seems to work on Safari Technology Preview Release 68 (Safari 12.1, WebKit 13607.1.11)

Haven't tested export button or tested either button on the stable Safari 12

**Comment by aaronraimist** [comment]
Both buttons work as of Safari 13 so this can be closed.
