### ISSUE TITLE
keyboard nav of roomtiles needs up/down as well as tab/shift-tab

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3114]

**Comment by ara4n** [comment]
@JaniM before i collide with you: were you looking at this already?  (related to https://github.com/vector-im/riot-web/issues/1754)

**Comment by JaniM** [comment]
@ara4n It was on my roadmap, but I haven't had any time to look into it. All yours. :)

**Comment by pvagner** [comment]
Would it be possible to generalize this a bit more? e.g. it would be usefull to use this keyboard nav paradigm in the room list, and also in the member list.
Pressing up and down arrow keys should navigate to the prev / next item and pressing tab / shift + tab should allow navigating to other activatable elements within a respective list item e.g. when navigating to a room in filtered view pressing enter key should open that room as proposed in #1754 however navigating to a room using up / down arrow keys, pressing tab or shift+tab should focus respective room avatar and pressing enter key while such an avatar is focused should inwoke its popup menu.
Once appropriate aria related markup becomes implemented this is also relevant to #302.

**Comment by ara4n** [comment]
this is done in https://github.com/vector-im/riot-web/pull/3654
