### ISSUE TITLE
"session.import_session is not a function" when trying to import session keys

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3116]
I tried to import a room keys file that was exported from another Riot client, only to see this error displayed in the import dialog (in red text):
`session.import_session is not a function`

**Comment by richvdh** [comment]
where? /app? /develop? If it's local it's because your olm is out of date

**Comment by lukebarnard1** [comment]
I was trying to import it on a local instance, so that would explain it.

**Comment by richvdh** [comment]
PEBKAC ;-p
