### ISSUE TITLE
Opening register link in same browser causes logout

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3119]
1. Register with an email
1. Click the email link such that it opens another tab in the same browser
1. Go back to the first tab
1. Do the captcha
1. Original tab gets logged in, then immediately is 'logged out for security reasons'
1. Other tab gets logged in

The tabs share local storage, so somehow the access token issued to the original one is being deleted (although @richvdh didn't think we did this) and they end up sharing a device ID.

**Comment by ara4n** [comment]
this flow is surely very common indeed.
