### ISSUE TITLE
add little 'what is this' (?) icon next to presence indicators

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#3121]
Lots of people ask about the little icons that wander down the message list, indicating the place up to which other users have read/followed the stream.

How about adding a little (?) icon to their right to explain this, until the person clicks "no longer display those" inside the popup that would open?

**Comment by ara4n** [comment]
dave just added proper rollover text for these a few hours ago, which may be sufficient?

**Comment by dbkr** [comment]
I just did https://github.com/matrix-org/matrix-react-sdk/pull/669 which should help this, so I vote let's see how this works out.

**Comment by madduck** [comment]
Should probably suffice. Thanks!
