### ISSUE TITLE
sending an attachment in an e2e room with unknown devices fails

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3124]
you get an error, but not the 'unknown devices' dbox, so can't do anything about the unknown devices

**Comment by ara4n** [comment]
i wonder whether this is what was happening on #3148 with @rxl881 and @manuroe?

**Comment by lukebarnard1** [comment]
FTR, this looks like:

![2017-03-09-101518_806x307_scrot](https://cloud.githubusercontent.com/assets/6750344/23745757/566a0078-04b1-11e7-9337-fbf1688fe9d0.png)

And the file gets uploaded regardless.
