### ISSUE TITLE
Complex/slow/big device-change query on startup

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3127]
Consider the following:
* I am in an e2e room with a few users
* I am in a bunch of other, very busy, rooms
* I get the device list for the users in the e2e room, and store the relevant sync token as my up-to-dateness token
* Lots of people come and go in the non-e2e rooms, but since I don't share e2e rooms with them, I don't care.
* I restart the app
* I have to go allll the way back to the last device update, which is slow, and can produce a huge result

**Comment by richvdh** [comment]
We could update the 'up-to-dateness' token more often, but it probably requires us to fix https://github.com/vector-im/riot-web/issues/3126 first.

**Comment by ara4n** [comment]
i don't get why we're even receiving device list info for users in non-e2e rooms...

**Comment by richvdh** [comment]
> i don't get why we're even receiving device list info for users in non-e2e rooms...

We're not.

At startup, we ask the server for a list of users who might have changed their device list since we last started. It returns a list of userids - *not* the device lists themselves. The server doesn't distinguish between e2e rooms and and non-e2e rooms for this - it is up to the client to do that.

The basis of this bug is that we ask the server to look further back in history than we need to. That requires more db work on the server than necessary, so it takes longer for the client to get its device list into sync than necessary.
