### ISSUE TITLE
Status bar doesn't hide after scrolling up and back down

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#3137]
In Riot 0.9.7, the status bar hides when nobody is typing and you're at the bottom of the timeline view. However, if you scroll up and back down again, the status bar remains there (but empty) as it did in previous versions of Riot. The same happens if you scroll back down with the down arrow in the status bar.

EDIT: Looks like it also doesn't hide after the person who was typing sends a message, which means it's only hidden until someone starts typing for the first time since you opened the room.

**Comment by ara4n** [comment]
this is currently a feature.  the longer term behaviour is as per #1991
