### ISSUE TITLE
Weird half-a-typing notification

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3141]
Avatar but no text?

![screenshot_2017-02-05_11-23-50](https://cloud.githubusercontent.com/assets/1389908/22625747/ab0b7434-eb95-11e6-9573-5e777a6ef993.png)

**Comment by ara4n** [comment]
just got this too:

<img width="1119" alt="screen shot 2017-02-06 at 01 37 19" src="https://cloud.githubusercontent.com/assets/1294269/22631399/e1404fe4-ec0c-11e6-9c72-4fd58254efec.png">

**Comment by uhoreg** [comment]
And, just for fun, it seems like text-but-no-avatar seems to happen too:
![image](https://cloud.githubusercontent.com/assets/1012976/22763384/5953acca-ee32-11e6-8aba-fce5ae3555f1.png)
