### ISSUE TITLE
Ability to order room tag groups

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#3144]
After adding a number of tags to rooms via the API, I can now see the groupings in riot-web. However, their order seems random and there's no way to reorder them. It'd be nice if I could specify their vertical ordering and put those on top that are more important to me.

**Comment by richvdh** [comment]
Did you try setting the `order` property (per http://matrix.org/docs/spec/client_server/r0.2.0.html#id77) ?

**Comment by madduck** [comment]
I did not, but considering how one sets it for each tag-per-room, I was under the impression that this controls ordering *within* a tag. A quick test seems to confirm this:

1. adding an existing tag to a room with prios 0.5 (1.5) place it at the top (bottom) within the tag;
1. adding a new tag to a room with either of those prios has no effect on the placement of the tag wrt the other tags.

**Comment by richvdh** [comment]
ah yes, sorry.

**Comment by ara4n** [comment]
now this one /is/ #1373 as near as damnit. the intention of the UI there is to let you order & hide/create tags to your heart's desire.  closing as a dup.
