### ISSUE TITLE
Hide favourites/low prio if empty and there are other tags

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#3145]
Once a user defines other tags, s/he might no longer want to use Favourites/Low Priority. Could those be hidden (or moved to the bottom) if they're empty and there are other tags?

**Comment by ara4n** [comment]
i think this is basically a request for customising tags in general, which is #1373

**Comment by ara4n** [comment]
we can't hide them entirely by default because we need them as drop targets. it'd be better to provide a way to edit tags in general, i think, so closing in favour of the other bug.
