### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by storrgie** [vector-im/riot-web#315]
I've recently started using rocket, but became aware of matrix/vector today. One of the main reasons I jumped into rocket was that they have an official docker image that makes it relatively easy for me to deploy. Is there plans to begin maintaining a docker image for this project?

**Comment by ara4n** [comment]
There's an unofficial dockerfile at https://hub.docker.com/r/silviof/docker-matrix/ that provides a synapse matrix server alongside a vector matrix client. I'll leave this open though for supporting an official one.

**Comment by pafcu** [comment]
There is an official Synapse image now (https://hub.docker.com/r/matrixdotorg/synapse/), but it does not include Riot.

**Comment by itay-grudev** [comment]
Ping! It would be great if you create an official docker image and update it regularly.

**Comment by turt2live** [comment]
ftr, there is a dockerfile proposed at https://github.com/vector-im/riot-web/pull/7771 which we are chasing now.
