### ISSUE TITLE
file uploads with spaces in the filename get turned into %20's on download

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3155]

**Comment by lieuwex** [comment]
Shouldn't this issue be closed?

**Comment by ara4n** [comment]
only when the PR is merged.

**Comment by lieuwex** [comment]
Oh sorry I thought it was already merged, my bad

**Comment by richvdh** [comment]
fixed (at last) by https://github.com/matrix-org/synapse/pull/2090
