### ISSUE TITLE
Riot can't be loaded if cookies are blocked in chrome

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#3164]
To reproduce:
1. Configure Chrome to block cookies for https://riot.im
2. Reload Riot

Riot can't be load, the page is all blank

**Comment by NegativeMjark** [comment]
It seems to die at: https://github.com/matrix-org/matrix-react-sdk/blob/master/src/MatrixClientPeg.js#L24

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
