### ISSUE TITLE
Start minimized to tray

### ISSUE THREAD

**Issue by mrbiber** [vector-im/riot-web#3167]
Possibly configurable via options.

[This comment](https://github.com/vector-im/riot-web/issues/2799#issuecomment-272913340) is relevant.

**Comment by richvdh** [comment]
Presumably this is about the electron wrapper

**Comment by ArsenArsen** [comment]
+1

**Comment by tristan-k** [comment]
+1

**Comment by richvdh** [comment]
If you'd like to express your support for an issue, please give it a 'thumbs up'.

**Comment by ara4n** [comment]
looks like #3641 gives a solution to this, via a `--hidden` option.

**Comment by fuzzy76** [comment]
Only for Windows, changing the command line options for electron apps on Mac is not easy.

**Comment by t3chguy** [comment]
If you use the built in option `Start automatically after system login` it'll open minimized.

**Comment by fuzzy76** [comment]
Nice to know, it didn't occur to me that desktop settings could be found inside Riot's web views... I assumed there were no UI settings since I couldn't find a preferences menu. This fixes it for me, for now atleast. :)

**Comment by BadPackets** [comment]
The client behavior is not consistant between Windows 7 and Windows 10.
![image](https://user-images.githubusercontent.com/32589462/40573458-c99eee2e-6076-11e8-985a-57908cb98a73.png)
Client does not start minimized with Windows 7
Client starts minimized with Windows 10
