### ISSUE TITLE
UI buttons on right-hand panel are mis-aligned

### ISSUE THREAD

**Issue by Kegsay** [vector-im/riot-web#3171]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

UI buttons on right-hand panel are mis-aligned

### Steps to reproduce

![screencapture-riot-im-develop-1486561032025](https://cloud.githubusercontent.com/assets/7190048/22739526/e5958110-ee03-11e6-9c98-bbfbc92631d1.png)

### Version information

- **Platform**: web

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
@kegsay would have been great to know the chrome version here, given it works fine for most people...

**Comment by ara4n** [comment]
i can't repro, but hopefully 5f745ff will fix it.
