### ISSUE TITLE
Very confused typing notifications

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3172]
![screen shot 2017-02-08 at 13 56 08](https://cloud.githubusercontent.com/assets/986903/22740135/7edb7d50-ee06-11e6-9c82-31f80528d7dc.png)

Previously just had Matthew's avatar with "ishitatsuyuki is typing"

**Comment by dbkr** [comment]
Strongly suspect this is related to https://github.com/vector-im/riot-web/issues/3141

**Comment by uhoreg** [comment]
Similarly, I just got:
![image](https://cloud.githubusercontent.com/assets/1012976/22757351/670715a6-ee18-11e6-9221-a67c70c17748.png)
(where the avatar displayed is neither Erik's nor vurpo's)

**Comment by ara4n** [comment]
@lukebarnard1 these bugs are pretty high profile flakiness if you can take a look at some point soonish...

**Comment by lukebarnard1** [comment]
Sure, I can take a look today. I think I know what this is.
