### ISSUE TITLE
Sync (verified) key-state between two logged-in trusted devices

### ISSUE THREAD

**Issue by Torxed** [vector-im/riot-web#3173]
No clue where to post this, and I apologize in fore-sight for my laziness to investigate.

**Feature request:** Sync verified keys between two/more logged in self-owned devices (ex: Phone to Web).

I know this goes against a lot of common sense, but so does user liabilities and actions.
There's no sane every day Joe Bloke who is willing to go through a room of even 5 people with two devices each and verify them manually one by one. He won't go through the hassle of doing it with his two devices in hand, let alone during IRL meetings with everyone.

If Joe Bloke could go through the pain of verifying keys once IRL, or even with alternative communication methods verified twice - he could then sync the trusted keys and blocked keys between two of his devices by logging on both of them and press a magical button called "Sync key state between device: [dropdown]".

I have no clue if this has been suggested before, but I sure as anything would think this is a security enhancing feature if you know anything about user behavior and how the world actually works. I know it's a rule breaker in a Utopian dystonia at the same time. But give us the option to pick and choose?

**Comment by richvdh** [comment]
I think this is a dup of #2537
