### ISSUE TITLE
Welcome page button doesn't work (/develop)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3174]
### Description

*Note*: I'm somewhat sure this is part of RTS, which I also feel shouldn't affect my account (my own HS, using riot as a client).

The welcome page button is shown, but when clicking on it I get a generic "Unrecognized token" error. It seems like the button shouldn't be shown for the particular case.

### Steps to reproduce

- Log in without a Teams account (in my case, `@travis:t2l.io`)
- Note that the Welcome Page button is shown
- Click the button
- Note the error

I would have expected a welcome page, considering the button is present. However, due to the error, I feel the button shouldn't have been shown for me in the first place.

Log: sent

![image](https://cloud.githubusercontent.com/assets/1190097/22746217/4e2f25b0-ede0-11e6-9b7c-db660fd6d605.png)
![image](https://cloud.githubusercontent.com/assets/1190097/22746241/5ce92a56-ede0-11e6-820f-e89f64e2a4c3.png)

(also, as an aside, the button & error don't play well with the dark theme)

***Edit***: The colors schemes for rooms also don't apply to the button
![image](https://cloud.githubusercontent.com/assets/1190097/22762219/7ca01f04-ee1b-11e6-9b17-3be68eca5a34.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
@lukebarnard1 surely this shouldn't be leaking out into normal /develop?

**Comment by lukebarnard1** [comment]
@ara4n a fix has been merged for this. People's team tokens have been set to `undefined`, so it should go away after log-out/log-in but it's hardly ideal.

**Comment by ara4n** [comment]
@lukebarnard1 hmm. we don't want to force people to logout/login obviously, especially as it risks killing their e2e state if they don't back it up properly... if they've been set to `undefined` can we not specialcase to ignore it?

**Comment by lukebarnard1** [comment]
@ara4n good point... I wonder why the home icon even displays if it's set to `undefined`.. unless it's the string `"undefined"` ?

**Comment by turt2live** [comment]
![image](https://cloud.githubusercontent.com/assets/1190097/22790602/f61c85ba-eea3-11e6-81e3-9e6e75fdb9c6.png)

@lukebarnard1 Yup, it's a string.

**Comment by lukebarnard1** [comment]
That's quite unfortunate...

**Comment by lukebarnard1** [comment]
Seems fixed?
