### ISSUE TITLE
Cannot scroll up through large message

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3175]
### Description

It is difficult to scroll up, past this event:
~https://riot.im/develop/#/room/#offtopic:matrix.org/$14865703912801734wvDMl:matrix.org~

### Steps to reproduce

- Go to a very big event ~https://riot.im/develop/#/room/#offtopic:matrix.org/$14865703912801734wvDMl:matrix.org~
- Scroll up to try and view messages prior to that one

Expectation: scroll past message and see messages before it.
Reality: unpagination (or something) causes the view to jump back down, before the event.

__Update:__ The event in question appears to have been redacted

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Chromium 53
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
I'm not having much success reproducing a similar case to the event observed.

Here's a possible event: https://matrix.to/#/!mqKhqSwKDanxfItygf:t2l.io/$1486572121281DTgnT:t2l.io

In my case, the scrollbar jumps about while I'm trying to go up, but I can fight it (and win) to get above the message. The message in the OP was impossible to scroll up in.

Myabe it has something to do with line breaks in the message? (I just used a lorem ispum generator)

**Comment by lukebarnard1** [comment]
(another example: https://riot.im/develop/#/room/#freenode_#matrix-test:matrix.org/$149089217320UHAdG:ldbco.de)

**Comment by lukebarnard1** [comment]
Disabling unpagination allows for expected behaviour, as expected. Reducing the number of events unpaginated by one in the "backwards" case fixes, I shall PR.

**Comment by lukebarnard1** [comment]
This appears to still be a problem, which can be repro'd by making the window very thin. I haven't investigated yet, but this issue was undoubtedly caused by https://github.com/matrix-org/matrix-react-sdk/pull/795

**Comment by lukebarnard1** [comment]
Seems fixed
