### ISSUE TITLE
Status bar no longer shows when you trigger a VoIP call

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3181]

**Comment by lukebarnard1** [comment]
I would say it's slower than I remember, but it does show eventually.

**Comment by lampholder** [comment]
It doesn't show until you move the mouse.

**Comment by lukebarnard1** [comment]
>It doesn't show until you move the mouse.

I _think_ this was a coincidence as I cannot repro this happening. I can reliably repro without ever moving the mouse.

**Comment by ara4n** [comment]
ok, so it's reproduceable?

**Comment by lukebarnard1** [comment]
>ok, so it's reproduceable?

Yep, seems like a race due to the `StatusBar` needing to inform it's parent (the thing that keeps it hidden) when its size changes. I'm investigating atm.

**Comment by lukebarnard1** [comment]
The quick fix here is to do `isStatusAreaExpanded = this.state.statusBarVisible || inCall`.

The better fix would be to not rely on `this.state.statusBarVisible` and instead somehow let the status bar fill up as much height as it needed and also let it change its own height. OR calculate whether the status bar is visible in `RoomView`. So basically move `_getSize` of `RoomStatusBar` to `RoomView`.
