### ISSUE TITLE
Clicking on IRC channel name unlinks bridge

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3183]
### Description

When configuring the IRC channel in a room the text next to `Unlink` (see image) doesn't appear clickable, however clicking it performs the same action as the `Unlink` button.

![image](https://cloud.githubusercontent.com/assets/1190097/22769280/db7ac9c4-ee44-11e6-8a89-69489b0da0f4.png)

### Steps to reproduce

- Have a room linked to an IRC channel
- Click the text next to `Unlink`

Describe how what happens differs from what you expected.

I was hoping for some configuration options for the bot (ie: bridged user display name format, etc) or nothing to happen. Was not expecting to have to reconfigure the bridge.

Log: not sent?    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 55
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
fixed
