### ISSUE TITLE
if you try to /join a room which is invite only, you get stranded on an infinite spinner after the warning dialog's shown

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3186]

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/79155885-c37eff80-7dc9-11ea-9c0e-b3a34e01acb5.png)

![image](https://user-images.githubusercontent.com/2403652/79155895-c548c300-7dc9-11ea-82ca-5c661aa4abbe.png)

Seems fine now
