### ISSUE TITLE
My Riot MacOS Desktop client freezes regularly

### ISSUE THREAD

**Issue by enyo** [vector-im/riot-web#3199]
### Description

Since I updated to the latest version, my Desktop client freezes about 3 times a day.

### Steps to reproduce

Normal use... 

Log: not sent

### Version information

- **Platform**: desktop
- **OS**: macOS Sierra `10.12.3 (16D32)`
- **Version**: `0.9.7`

**Comment by ara4n** [comment]
how many rooms are you in? any idea how much RAM the process is using?  This is probably either #3198 or #2951

**Comment by enyo** [comment]
I'm in 4 rooms, so that isn't really an issue.

That's the usage when it's running fine. I'll check when it freezes again.

![image](https://cloud.githubusercontent.com/assets/133277/22855071/03036abe-f07a-11e6-93ad-dde577a87c22.png)

**Comment by enyo** [comment]
So it just froze again. IMO it's not #3198 or #2951 because my CPU is doing nothing:

![image](https://cloud.githubusercontent.com/assets/133277/22972179/e31b06d8-f378-11e6-9743-9935e908ad3a.png)

And this is the memory footprint:

![image](https://cloud.githubusercontent.com/assets/133277/22972188/ed3637be-f378-11e6-9e33-78df7ff6404d.png)

It's also not as if it was slow or unresponsive. It is *completely* frozen.

**Comment by ara4n** [comment]
does this happen when you try to view a particular room? are there any reproduction steps or does it happen entirely at random? if you can share the javascript console logs up to the point it goes bang that'd be very useful (you may need to hit the 'pause' button on the debugger in order to make chrome responsive).

**Comment by enyo** [comment]
I am only using the Riot Mac OS app not the browser. Not sure if it also happens in the browser. Is there a way to provide the JS debug info from the MacOS app as well? (Never developed with electron before).

From what I can tell, it seems pretty random and doesn't have anything to do with a particular room. For example: I could be in a conversation with my brother, continue working, and see that I have new notifications on my phone. Confused I switch to the Riot MacOS app and still see the conversation with my brother but no UI updates, and the app is completely unresponsive (although as state before, *not* using inadequate amounts CPU or RAM).

**Comment by enyo** [comment]
Any more info on that? Still get this on a regular basis (on two separate machines) multiple times aday.

**Comment by fuzzy76** [comment]
I am seeing this too. It usually happens when I switch between rooms, often when I switch to a room I haven't looked at before in the current session - could there be some syncing happening? But the symptoms are frozen Riot, no CPU use, quit works fine.

I will report back with console output the next it happens.

@enyo View -> Toggle developer tools

**Comment by fuzzy76** [comment]
Actually, scratch that. I managed to do it again (by just opening the desktop client and clicking through rooms).

- There are several "Riot Helper" processes, and one of them shows 110% CPU.
- Developer tools console shows no output (blank).
- There seems to be a frozen scrollbar in the current room - perhaps the cause?
- Bringing the client out of fullscreen worked, but the UI did not resize to the new window size (looks like the HTML renderer did not respond to or get the resize events)
- Tried running the javascript CPU profiler, but that froze the entire developer tools.

So am I seeing a different issue?

**Comment by enyo** [comment]
Thanks for the tip about the dev tools. Didn't realise that they were available.

> But the symptoms are frozen Riot, no CPU use, quit works fine.

Exactly my problem. But it doesn't have anything to do with switching rooms. It happens for me sometimes when I have one chat open, do something else, come back to riot, and it's frozen.

**Comment by ara4n** [comment]
@enyo just wondering if 0.9.10 helps with this?  We've done quite a lot of perf work recently.

**Comment by enyo** [comment]
I haven't experienced it recently, so I guess you fixed it :)
Going to close the issue, and if it occurs again, I'll reopen. Thanks
