### ISSUE TITLE
Banned user can't leave room, and sees it in RoomList on web but not android

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3200]
<img width="852" alt="screen shot 2017-02-10 at 15 48 58" src="https://cloud.githubusercontent.com/assets/1294269/22833074/77be388e-efa8-11e6-921c-9e06ff1d268e.png">

**Comment by dbkr** [comment]
This should now be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/709 and https://github.com/matrix-org/synapse/pull/1922
