### ISSUE TITLE
can't reject invite from user with broken federation

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3201]

**Comment by ara4n** [comment]
got an invite from `@max:kamax.io`. looks like his federation is broken; if i try to join it (on iOS) i get a permenand redirect error(!).  If i try to reject it on desktop, i see a spinner, which then dumps me to a different room, but the invite remains

**Comment by ara4n** [comment]
max has now fixed his federation (which was indeed doing 308 permenant redirect voodoo), but I still can't reject the invite - it now says "no known room".

**Comment by Matrixcoffee** [comment]
I'm currently stuck with 2 invites, for which I get "Internal Server Error" on both accept and reject. It seems the remote homeserver had problems, and at the moment is down and may never come back.

**Comment by richvdh** [comment]
This issue appears to have gone away for matthew. Things changed a bit in synapse 0.20 anyway. @Matrixcoffee if you still have issues please let me know/open a new issue so we can investigate.

**Comment by richvdh** [comment]
This is https://github.com/matrix-org/synapse/issues/761, which appears not (yet) to have been fixed after all.

@Matrixcoffee has been confirmed to be suffering from it. @Matrixcoffee: I've removed the offending invites from the matrix.org database so they should go away if you clear your client caches.

**Comment by Matrixcoffee** [comment]
Awesome, thanks!

**Comment by richvdh** [comment]
This was properly fixed in https://github.com/matrix-org/synapse/pull/2145.
