### ISSUE TITLE
Ugly white halos on black avatars

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3203]
Why are there visible halos around the avatars in typing notifications?
(at least on the dark theme)

https://matrix.org/_matrix/media/v1/download/berigora.net/jzmtjCXsjeHHLGeemcKeEzVY

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it (on Element Web 1.7.1).

![image](https://user-images.githubusercontent.com/22885898/87853714-ba438880-c90c-11ea-9bb4-a9fc18136a1f.png)
