### ISSUE TITLE
invite UI has become incredibly slow

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3204]
the text-search is pausing for ~5s for me as i try to invite people; seems like we're missing some ratelimiting

**Comment by ara4n** [comment]
this is in ChatInviteDialog

**Comment by lukebarnard1** [comment]
@ara4n it would be good to know if fuse has made this worse/better (I'm guessing worse)

**Comment by lukebarnard1** [comment]
Closing this because things seem fast (at least on my account). We can reopen if performance with using Flux to search appears slow.
