### ISSUE TITLE
invite UI doesn't search displayname

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3205]
If i search for kyrias i find @kyrias:kyriasis.com. If i search for remmy (his display name) nothing comes up. :|

**Comment by ara4n** [comment]
this comedy mess means that searching for 'luke' doesn't show up @lukebarnard1...

**Comment by lukebarnard1** [comment]
So https://github.com/matrix-org/matrix-react-sdk/pull/732 is running at the moment and has solved this as far as I can tell. Whether we'll stick with fuse is another question - it's performance seems OK to me.
