### ISSUE TITLE
Display name save mechanism trips new users

### ISSUE THREAD

**Issue by maxidor** [vector-im/riot-web#3212]
### Description

Currently, if one wants to change its account Display name, it has to change the value then press Enter, which is counter-intuitive compared to all other items (like the profile picture) which are automatically saved.
New users tend to trip very easily on this and are confused why their change is not saved.

There should either:
- Be a button "Save" just like in the room settings, thus keep it consistent across the app
- Auto save on closing the settings page or directly after changing the value

### Steps to reproduce
- Go into Settings
- Click on the Display Name text field value
- Enter the new Display name
- Press Enter (confirmation step)
- Wait for the info to be saved on the server

### Version information
- **Platform**: all
- **Version**: all

**Comment by richvdh** [comment]
dup #1602
