### ISSUE TITLE
Invite suggestions can be unreadable in Dark theme

### ISSUE THREAD

**Issue by maxidor** [vector-im/riot-web#3213]
### Description
In Dark theme, highlighted "Searching for known users" suggestion in the "Invite new room members" dialog is barely readable due to wrong color/contrast.

The color scheme should be changed to the highlighted suggestion is actually readable.

![dark-theme_invite-search](https://cloud.githubusercontent.com/assets/10545559/22863315/1358b602-f13e-11e6-8058-708d38aef7fe.png)

### Steps to reproduce
- Switch to dark theme
- Invite a new user
- Start entering text to trigger search for known users IDs
- Enjoy the blindness

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Firefox 51.0.1 (64-bit)
- **OS**: Linux Mint 18 Cinnammon
- **URL**: riot.im/app

For the desktop app:

- **OS**: Linux Mint 18 Cinnammon
- **Version**: 0.9.7

**Comment by ara4n** [comment]
this is already fixed on develop (riot.im/develop)
