### ISSUE TITLE
E2E-enabled user was sending unencrypted messages into an E2E room (but decrypting ok)

### ISSUE THREAD

**Issue by arraiano** [vector-im/riot-web#3215]
I don't know if that's an issue or an ussage error: testing Riot for a work meeting between 4 persons, on a room with e2e encryption enabled, all the messages from one of them was uncrypted. We know his messages was uncrypted bacause the padlock symbol on each of them was open, and when we leave the room, and then login again, only their messages was readable. He was using riot on web version, from Tor Browser. If I click on the (open) padlock symbol by their messages, the encryption information was:

End-to-end encryption information
Event information
User ID	@userID:matrix.org
Curve25519 identity key	none
Claimed Ed25519 fingerprint key	none
Algorithm	unencrypted
Session ID	none
Sender device information
unknown device

As I said, the room has the endo-to-end encryption enabled, and the messages of the other participants was correctly encrypted. The most amazing thing was that this person (wich messages were send to the room on plain text) could read the encrypted messages from the other participants (something like if we had his public key and could encrypt messages for him, but he had not our public keys and can't encrypt messages for us, so send ir uncrypted??).

I thought that in an encrypted room, all of the messages was encrypted or, if not, it can't be send. Could someone explain why this strange behavior could have happened?

Thankyou very much!

**Comment by richvdh** [comment]
Please ask the user to send a bug report from the settings screen.

**Comment by ara4n** [comment]
@arraiano any chance of reproducing this or getting a bug report from the settings screen? this sounds like a nasty but genuine bug...

**Comment by arraiano** [comment]
I am afraid that I have no possibility of providing further information. The room in which the chat was developed no longer exists ... maybe I could ask the person whose messages were not encrypted to send me any log ... but where should he look for it?

**Comment by richvdh** [comment]
Ask them to send a bug report from the settings screen

On 18 February 2017 12:56:21 GMT+00:00, arraiano <notifications@github.com> wrote:
>I am afraid that I have no possibility of providing further
>information. The room in which the chat was developed no longer exists
>... maybe I could ask the person whose messages were not encrypted to
>send me any log ... but where should he look for it?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/3215#issuecomment-280843951

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by richvdh** [comment]
not enough info to reproduce
