### ISSUE TITLE
Fuzzy search for room names

### ISSUE THREAD

**Issue by WhyNotHugo** [vector-im/riot-web#3216]
### Description

Fuzzy-searching of open rooms would be really useful to quickly switch across rooms. I'm thinking about hitting a certain set of keys, and typing a room name that fuzzy-matches open ones.

Having to use slack for work, memory-muscule keeps tricking me to hit <kbd>ctrl</kbd>+<kbd>k</kbd> to try and fuzzy-search open rooms.

**Comment by JaniM** [comment]
This is pretty much done with https://github.com/vector-im/riot-web/pull/2946 and https://github.com/vector-im/riot-web/issues/3114 (as soon as the latter is implemented).

**Comment by ara4n** [comment]
i'm going to merge this into #3114.

**Comment by ara4n** [comment]
actually, i'm not, i'm going to turn this into a 'fuzzy search' request

**Comment by ara4n** [comment]
the hotkey request is #3114, but agreed it'd be cute to have fuzzier search when filtering on rooms by name.

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/1853

**Comment by ara4n** [comment]
also very related to https://github.com/vector-im/riot-web/issues/1754

**Comment by hobarrera** [comment]
Glad to see there's more interest in this, thanks!

**Comment by aviraldg** [comment]
@lukebarnard1 Didn't you implement this?

**Comment by lukebarnard1** [comment]
@aviraldg nope, I only did searching through display names when inviting someone. (https://github.com/matrix-org/matrix-react-sdk/pull/725)

**Comment by lukebarnard1** [comment]
@ara4n Shall I hook fuse up to the RoomList and see what happens? And do the <kbd>ctrl</kbd> +  <kbd>k</kbd> thing?

**Comment by hobarrera** [comment]
@lukebarnard1 Sounds fine by me! 😄

**Comment by ara4n** [comment]
i've done the ctrl-k thing in the matthew/quick-search branch which just landed. i think we should see how it feels so far before adding fuse - i'm not sure how fuzzy it should be.
