### ISSUE TITLE
rich text editor can get confused and just keep inserting formatting chars

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3225]
https://matrix.org/_matrix/media/v1/download/matrix.org/UsKbPuEwGsmoBmIOzBWRBrBl

**Comment by aviraldg** [comment]
@ara4n Like we discussed before, it's the intended behaviour. Toggling formatting characters is much harder in Markdown mode, so what it's doing is adding them around an empty string (which is what looks confusing)

How do we proceed here?

**Comment by lukebarnard1** [comment]
Surely the caret position should be at the end of the thing that was formatted:

Before: `Some text |` 
*press italic*
After: `Some text *|*`

where "|" is the caret.
