### ISSUE TITLE
Search in "Room directory" confusing when you press return

### ISSUE THREAD

**Issue by frabcus** [vector-im/riot-web#3229]
### Description

The Room directory search appeared to not work too me, because I was pressing Return and it tried to go into the room rather than completing a sarch.

### Steps to reproduce

I was trying to search the Room directory (in the Linux desktop app).

I type fast and instinctively press Return. This meant it tried to go to a room with the name of what I'm typing, and gave the message "You are trying to access a room.
Click here to join the discussion!".

I assumed this wasn't a search field after all, but a "go to specific named room" field

Instead, it turns out (and I only found out by asking someone else) I have to type and *wait* and that does a search.

Log: not sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 0.9.7

**Comment by frabcus** [comment]
Some ideas:

- Make it clearer it is search, perhaps with a magnifying glass button?
- If e.g. I type "django" and press return, as well as showing a link at the top to join or make a room, it could conduct the search as well below.

**Comment by ara4n** [comment]
this is a major screwup - thanks for the report :)

**Comment by lukebarnard1** [comment]
I guess this could be split up into:

1. The first item in the list should be auto-selected, and hitting <kbd>Enter</kbd> should do the same thing as clicking.
2. The room directory should only do joining upon hitting <kbd>Enter</kbd> if the query begins with "#". This should be indicated by having the first item being a special "Join #whatever:matrix.org".

**Comment by lukebarnard1** [comment]
- [ ] Hitting enter should not do anything!

**Comment by ara4n** [comment]
(and if you want to join, then hit the nice 'join' button)
