### ISSUE TITLE
Add ability to choose audio/video input device

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/riot-web#3234]
### Description

I was trying to have a video chat with a friend who was using Riot on her macOS desktop. She could see and hear me, but I couldn't see or hear her. I assume the issue lies with Riot defaulting to an incorrect input device because she does need to choose other settings than the default settings when using [Jitsi Meet](https://meet.jit.si/). However, Riot does not seem to provide any ability to choose the input device.

### Steps to reproduce

- Ensure preferred audio and/or video input device are not the default devices
- Start an audio/video call
- Observe it does not work and you cannot choose input devices

### Version information

- **Platform**: Desktop (not browser)
- **OS**: macOS Sierra (10.12.2)
- **Version**:
matrix-react-sdk version: 0.8.6
vector-web version: 0.9.7
olm version: 2.2.1

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/2822
