### ISSUE TITLE
Referral link shown in user settings (with obviously broken link)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3241]
### Description

This is highly likely to be related to #3174 in the sense that my `team_token` somehow got set to the string `undefined`. A fix might be to special case this in a commit like so:

```
if (team_token === "undefined") {
  team_token = undefined;
  // actually save the variable to storage
}
```

Link is obviously broken because it has `team_token=undefined` in the URL (see screenshot below).

### Steps to reproduce

- May need to have a team token of `"undefined"`
- Open user settings
- See referral link in view

Describe how what happens differs from what you expected.

I would expect to not see this given I'm not part of a Team/on RTS.

Log: not sent

![image](https://cloud.githubusercontent.com/assets/1190097/23033433/42954f30-f435-11e6-94bc-cd8d772b5297.png)

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows 
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Interesting note:

Following the link (in an incognito tab to simulate sending it to someone) doesn't leave me at the registration page - it leaves me at the directory as a guest. Forcing my way to the registration page with the link after being a guest just forces Riot to remove the parameters, losing them forever once I actually register.

**Comment by lukebarnard1** [comment]
> it leaves me at the directory as a guest

It treats the string "undefined" as `undefined` now, which was a quick fix for #3174. So the behaviour you've described is expected.

> remove the parameters, losing them forever once I actually register.

Under the hood, the parameters are still there, so that's not a problem. 

Conclusion: the bug really is that you can see the referral link, probably because the link is rendered without a null guard on the team token.

**Comment by turt2live** [comment]
The account I registered to see what happens does not see the referral link. Something is certainly not working for my primary account.

Is it possible that the team token the referral link uses for visibility isn't the same one that was patched? (ie: it reads directly from storage instead).

**Comment by lukebarnard1** [comment]
> Is it possible that the team token the referral link uses for visibility isn't the same one that was patched? (ie: it reads directly from storage instead).

Well predicted! I've just found that it is exactly as you describe. Fixing now.

**Comment by turt2live** [comment]
Fixed, thanks!
