### ISSUE TITLE
/develop is forgetting that I want the dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3247]
### Description

When refreshing the page, riot-web seems to forget that I want the dark theme. The option is selected in the settings, but not visibly enabled. Switching back and forth fixes the issue.

### Steps to reproduce

- Have dark theme set
- Refresh page

Describe how what happens differs from what you expected.

I would expect the dark theme to persist :p

Log: ~~sent~~ not sent - can't submit :(

![image](https://cloud.githubusercontent.com/assets/1190097/23073018/40355e80-f4f1-11e6-94a5-27f49b769f40.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

```
Logged in as @travis:t2l.io
Homeserver is https://t2l.io
Identity Server is https://vector.im
matrix-react-sdk version: 775834b7073c7a9f098c5fa85121fdca9b36b622
riot-web version: 0d1c53285b48-react-775834b7073c-js-37e507707d1b
olm version: 2.2.1
```

**Comment by dbkr** [comment]
This is the indexeddb sync stuff not remembering the setting

**Comment by Kegsay** [comment]
It's being stored in indexeddb, so I'm guessing that riot-web is checking way too early for the theme (so it hasn't loaded and defaults to light).
