### ISSUE TITLE
need some way to easily jump to a matrix.to link

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3248]
For example, some GitHub issues include matrix.to links to a specific comment.  It would be nice to be able to stick that link somehow in Riot and have it jump to that link, rather than having to open a new tab with Riot.  This would be especially helpful with the Electron app, since the user may not be signed into Riot in their browser.

I have no idea how the UX for this would look without being completely ugly.

**Comment by lukebarnard1** [comment]
Maybe this could be an added feature to message searching? If the query looks like a matrix.to link, turn it into a riot URL (using `linkify-matrix.js` of react-sdk) and then just redirect the user?

**Comment by uhoreg** [comment]
Another possibility might be to add a new /command, say `/goto https://matrix.to/#/...`

**Comment by z3ntu** [comment]
The "/goto" variant would probably be the quickest to implement and easiest to use. After it's implemented it also should be put on the matrix.to website.

A workaround is copy-pasting the matrix.to url into an empty room and clicking it then.

**Comment by MurzNN** [comment]
Good place may be input field in `Room Directory` page, if user type url in it - show button "Jump" that do the thing.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2272

**Comment by maxidor** [comment]
Is there an issue for the GUI version of the command? The GUI gives a way to get the matrix.to directly in the GUI, even with a nice QR pic and all, but no GUI way to use it.

`/goto` is not documented on the share window either, is not documented on the matrix.to pages, is not directly mentionned in the react-sdk [corresponding release](https://github.com/matrix-org/matrix-react-sdk/releases/tag/v0.14.5-rc.1) (only join is mentionned), is not mentioned in the [Riot release](https://github.com/vector-im/riot-web/releases/tag/v0.17.6-rc.2) either - all in all, it feels like it's easy to miss.
