### ISSUE TITLE
Notifications shown for already-read messages on page refresh (/develop)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3251]
### Description

Refreshed the page due to Riot wanting to update and noticed a popup from Chrome about a new message. The message in question was already read (and addressed). Refreshing the page again yielded the same message being shown.

### Steps to reproduce

- be on /develop and have desktop notifications enabled
- refresh the page
- lose focus on the tab (so the notification is triggered)
- wait a short while for a notification

Describe how what happens differs from what you expected.

I would expect that I wouldn't be receiving desktop notifications for messages I've already looked at.

Log: not sent (can't)

![image](https://cloud.githubusercontent.com/assets/1190097/23077194/c13113a8-f500-11e6-8180-21195ed69783.png)
(name redacted for privacy)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

```
Logged in as @travis:t2l.io
Homeserver is https://t2l.io
Identity Server is https://vector.im
matrix-react-sdk version: 3fcea0f586dba6381ae8f021a1aec1bf8a1a9d29
riot-web version: f51669664ce8-react-3fcea0f586db-js-a5c726eef971
olm version: 2.2.1
```

**Comment by turt2live** [comment]
More information:

Seems to only happen when the message that caused the notification happened recently (quite recently). Not sure how the timing works out.

**Comment by ara4n** [comment]
This is probably related to https://github.com/vector-im/riot-web/issues/2608 and https://github.com/vector-im/riot-web/issues/809

**Comment by ara4n** [comment]
...except it's presumably related to @kegsay's new IndexedDB stuff

**Comment by Kegsay** [comment]
Probably: we only sync every 5 mins, so any new notifs in that time will be re-triggered on refresh.

**Comment by Kegsay** [comment]
To fix this, we'd need to aggressively persist unread notification counts as they change, which would mean factoring them out from the /sync response JSON and into a separate table.
