### ISSUE TITLE
call invites may be covered by notification bar

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3258]
if the room the call is coming from is at the bottom of the visible screen.  As reported by nepugia in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1487424736527224Qaalw:matrix.org

**Comment by ara4n** [comment]
I'm not sure I understand this one - afaik inbound VoIP call notifications always happen in popups for the room in question from RoomList?  How could they be overshadowed by the room's StatusBar?

**Comment by uhoreg** [comment]
Yeah, you'll have to ask @ lowee:matrix.org (who refuses to use GitHub) about this.  I just relayed his bug report.

**Comment by CR0CKER** [comment]
I can confirm this. Has happened several times on web client -- the popup window to accept the call is hidden behind the main chat area.

**Comment by lukebarnard1** [comment]
I can't reproduce this. Screenshot, @CR0CKER?

**Comment by CR0CKER** [comment]
Actually, I think this report refers to something else. What I've ben observing is a different problem where the inbound call notification is hidden behind the main chat area, not the notification bar. I don't have a screenshot.

**Comment by ara4n** [comment]
@CR0CKER you're seeing #2683. if you can give reproduction steps there we'll fix it - currently we can't reproduce.

**Comment by ara4n** [comment]
i'm going to assume this is a dup of #2781 as i don't understand it otherwise.
