### ISSUE TITLE
Highlight notifications stuck

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#3263]
Seemingly randomly, notifications sometimes get 'stuck'. Opening the room and marking all messages as read doesn't clear them out

**Comment by ara4n** [comment]
To investigate this i suspect we need a rageshake - please ping here once you've submitted one from User Settings on riot web

**Comment by ara4n** [comment]
I have one of these at the moment.  It looks like the server just gave me an unread count for that room in /sync, which then got stored in indexeddb, and has never been overridden (until presumably the next message is read in the room).  This looks distinctly like a serverside issue.

**Comment by PureTryOut** [comment]
Good that you can reproduce it, as I didn't get a proper rageshake yet... The option for that should really be added to the desktop client. Anyways as long as Synapse is updated when the fix for this lands, it should be gone?

**Comment by ara4n** [comment]
should be fixed by #1147
