### ISSUE TITLE
The fact 3PID invites create guests rather than registered users is very confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3265]
@BenfLewis0 points out that inviting someone by email can backfire as they will be a guest when following the invite, which makes their account worryingly ephemeral.

Options to fix are:
 * Put them into a registration page anyway to give them the option of creating a real account (or signing in with an existing account if they choose)
 * Improve the process of upgrading guests to registered users (i.e. probably ditching the numeric user ID, which is basically the same as #2947)

**Comment by t3chguy** [comment]
This is no longer the case because now you're forced to register
