### ISSUE TITLE
StatusBar now has 2px of StatusAreaLine above it, misbalancing the in-call status bar

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3269]
@lukebarnard1 i think this was added as part of the new StatusBar stuff - is there a way we can get rid of the 2px that has snuck in on the top?  The height of StatusBar is meant to be 50px, not 52px.

**Comment by lukebarnard1** [comment]
If the StatusBarArea should be 50px, the StatusBox will have to be 48px, ( with line-height 48px).

**Comment by ara4n** [comment]
As per the title of the bug, the reason i was asking to get rid of the 2px line is because it breaks the vertical symmetry by having 2px of additional content at the top which isn't at the bottom, which in turn contributes to #3182:

<img width="302" alt="screen shot 2017-02-21 at 15 35 46" src="https://cloud.githubusercontent.com/assets/1294269/23171837/a4c25850-f84b-11e6-9fbf-b6a28b17b138.png">

So ironically shrinking the area to 48px actually makes the misbalancing more pronounced and ugly! :)

**Comment by lukebarnard1** [comment]
How does this look?
![2017-02-21-160141_210x63_scrot](https://cloud.githubusercontent.com/assets/6750344/23172844/1cc48c76-f84f-11e6-98d9-430f6ed3d33f.png)
I took 3px off the top off line height for "Active call".

**Comment by lukebarnard1** [comment]
line-height 46px
