### ISSUE TITLE
Markdown mangles list numbering

### ISSUE THREAD

**Issue by abrahimladha** [vector-im/riot-web#3273]
### Description

If you try to enumerate a list, but do not start it at 1, it will falsely correct you to starting it at 1

### Steps to reproduce

-Have the RTE disabled in settings (edit: tested with RTE enabled and same results)
-Type "3. a" including the space and hit enter
-observe as it changes it to "1. a"

Describe how what happens differs from what you expected.
-It should be "3. a"

### Version information

- **Platform**: web

For the web app:

- **Browser**: FireFox 50.1.0, bug present in Chromium as well.
- **OS**: Arch Linux
- **URL**: our private server

**Comment by ara4n** [comment]
Yeah, this is very annoying. It's basically markdown behaving as expected.  We need to investigate whether CommonMark has support for not overriding the numbering but instead preserving what the user has used (via `<li value="3.a">` style HTML).

**Comment by taw00** [comment]
@ara4n The way it is suppose to work is that a list starts with the number you begin it with...

1. This should be 1.
1. This should be 2.

Bunch of stuff.

1. This should be 1. again.

Bunch of stuff

8. This should be 8.
1. This should be 9.

**Comment by ara4n** [comment]
this is very confusing, given riot is using commonmark these days :/

**Comment by taw00** [comment]
ara4n: Just do the 8 then 1 example in Riot. It will not do what it should.

**Comment by JaniM** [comment]
Note that the generated HTML _is_ correct.

```
{
  "origin_server_ts": 1491126342587,
  "sender": "@vegai:matrix.org",
  "event_id": "$14911263421361596sVOpI:matrix.org",
  "unsigned": {
    "age": 5384
  },
  "content": {
    "body": "200. the index here is actually 200",
    "msgtype": "m.text",
    "formatted_body": "<ol start=\"200\">\n<li>the index here is actually 200</li>\n</ol>\n",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!XqBunHwQIXUiqCaoxq:matrix.org"
}
```

Riot just seems to ignore the `start` parameter.

**Comment by abrahimladha** [comment]
I think this issue is fixed now with the https://github.com/matrix-org/matrix-react-sdk/pull/787 so I am going to close this issue.
