### ISSUE TITLE
Launch a call in a e2e and 1:1 room with unknown devices doesn't work

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#3277]
### Description

When I start a call in a 1:1 room with encryption enabled, and unknown devices present, the callee never received the call.

### Steps to reproduce

- Open a 1:1 room with encryption enabled with unknown keys
- Start a audio or video call

The call doesn't succeed.
I'm expecting the same pop up which is displayed when I send a message in e2e room with unknown devices. "Room contains unknown devices".
Rio-ios displays this pop-up in the same case.
On riot-android, the call fails: https://github.com/vector-im/riot-android/issues/952

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
oops, i just filed a dup of this as #3285. thanks!
