### ISSUE TITLE
Grey local echos are visible in addition to remote echos, causing duplicate messages in timeline

### ISSUE THREAD

**Issue by vatterspun** [vector-im/riot-web#3281]
### Description

Having issues with previous messages showing up below the current one.

### Steps to reproduce

1. Get a login from either email or web invite (https://riot.im/app/#/room/#tpf:matrix.org)
2. Login and exchange a few messages

**Defect**: messages start appearing below current (see screenshot).  Light colored skin shows them in a light gray, darker skin shows them as the same color and font.

### Screenshots

![2017-02-20 19_04_29-riot](https://cloud.githubusercontent.com/assets/1289134/23147047/a619263e-f7a1-11e6-8e91-63603a8d89df.png)
![2017-02-20 18_16_45-riot](https://cloud.githubusercontent.com/assets/1289134/23147048/a739956c-f7a1-11e6-8be4-f76450070a5e.png)

---

**Log**: not sent ... sorry I accidentally closed the browser before I could grab that.

### Version information

Setup: Win7x86, Web application, Firefox (51.0.1)

**Comment by vatterspun** [comment]
Quick update here: I got it to happen again.  I couldn't get log to send in the bug report view (error message "Failed: No connected database") but do have another (bigger) screenshot:

![2017-02-20 19_22_46-riot](https://cloud.githubusercontent.com/assets/1289134/23147170/6880f616-f7a2-11e6-9e22-1248c7ac0a15.png)

Here's some details from the settings tab:

Logged in as @157689:matrix.org
Homeserver is https://matrix.org
Identity Server is https://vector.im
matrix-react-sdk version: 0.8.6
vector-web version: v0.9.7
olm version: 2.2.1

**Comment by ara4n** [comment]
Hm, we could really do with the logs for this.  Are you running firefox 
in incognito mode (as per 
https://github.com/vector-im/riot-web/issues/3230)?

Either, can you please copy & paste the logs out of the Javascript 
Console and email them to rageshake at riot.im, or see if you can 
reproduce in non-incognito mode...

**Comment by vatterspun** [comment]
> Hm, we could really do with the logs for this. Are you running firefox in incognito mode (as per #3230)?

No, although I am running the multifox add-on that lets you run browser sessions in different tabs (e.g. log into Google with two separate accounts).  That shouldn't filter results or ignore cookies the way private/incognito mode does.

> Either, can you please copy & paste the logs out of the Javascript Console and email them to rageshake at riot.im, or see if you can reproduce in non-incognito mode...

I'll try to reproduce that and get it posted.  I'll also see if I can make that happen in a fresh copy of Firefox to make sure it's not my setup.

**Comment by vatterspun** [comment]
Update here: just because of overload, I am no longer able to test this program and I'm not going to be able to provide logs.  Please feel free to close this case.

**Comment by richvdh** [comment]
sounds a bit like https://github.com/vector-im/riot-web/issues/1541, though also different

**Comment by richvdh** [comment]
given that nobody has seen this since 2017 I suggest we forget about it.
