### ISSUE TITLE
UnknownDeviceDialog box breaks VoIP in E2E rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3285]
The VoIP call silently fails rather than coughing up the dialog box.

**Comment by ara4n** [comment]
See also #2669

**Comment by ara4n** [comment]
see also #3124

**Comment by ara4n** [comment]
it's also a problem for the person receiving the call (where the call then rings forever etc)

**Comment by ara4n** [comment]
Are we sure this is fixed?  It feels to me that the UDD is showing up a long time you try to hit 'Answer', and then appears multiple times, even if you say "Send anyway"?

**Comment by lukebarnard1** [comment]
@ara4n I wonder if more than one event is being sent at once, triggering 3 UDEs and 3 consecutive UDDs... Yep I've confirmed this. I'm too sure how the signalling works so I'm not sure why this would happen, but I've confirmed that 3 UDEs occur when starting a call.
