### ISSUE TITLE
1:1 e2e room: call doesn't work when callee have unknown devices

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#3286]
### Description
In a 1:1 room with encryption enabled,
- When caller knows all the keys, but callee don't, the callee receives the call but this one does't succeed.
Indeed, callee accepts the call but the connexion isn't made. Ringtone is still hearable for caller and the call is eventually ended.

What to do in this case ?
Maybe we should warn the call that he can take the call when this one arrives, as long as he have unknown keys.

This problem exists on android and ios as the call fails when accepted.

**Comment by ara4n** [comment]
i'm going to merge this into #3285.

**Comment by jeangb** [comment]
@ara4n ok ! just to be sure, what is expected ? the unknown devices alert have to be displayed on the callee client ?

**Comment by jeangb** [comment]
FYI for the mobiles, as we don't open the room when accepting a call, it's not possible to display the Unknown devices alert.
