### ISSUE TITLE
Voip event tiles in e2e rooms have shifted text on :hover

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3289]
![2017-02-21-164025_271x45_scrot](https://cloud.githubusercontent.com/assets/6750344/23174502/7ca851fe-f854-11e6-8f09-498625cfc45e.png)

![2017-02-21-170750_221x61_scrot](https://cloud.githubusercontent.com/assets/6750344/23175779/51f7038e-f858-11e6-8df3-bb49ed2fc4a0.png)

### Description

e2e event tile text shifts a few pixels to the left on hover

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: locally built, but basically /develop

**Comment by ara4n** [comment]
oops, i fixed this in ae145ff but forgot to push it

**Comment by ara4n** [comment]
(dup #3270)
