### ISSUE TITLE
Slash-command auto-completion doesn't work when the status bar is hidden

### ISSUE THREAD

**Issue by Kegsay** [vector-im/riot-web#3291]
If the typing status bar is hidden and you start typing in a slash command e.g `/ni` it does not show a list of auto-completion suggestions (e.g `/nick <display name>`)

**Comment by lukebarnard1** [comment]
I can't repro this. Screenshot, @Kegsay?

**Comment by Kegsay** [comment]
![riot-web-develop-no-auto-completion](https://cloud.githubusercontent.com/assets/7190048/23208329/7f36ce12-f8ec-11e6-8303-6499f9401935.jpg)
