### ISSUE TITLE
"Start a New Chat" uses different "close" button to other dialogs

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3297]
![2017-02-22-103321_805x130_scrot](https://cloud.githubusercontent.com/assets/6750344/23207790/720112b8-f8ea-11e6-8299-567274adab63.png)

**Comment by ara4n** [comment]
this is the correct design. if anything the design of @dbkr's new close button should be brought inline to match - this is https://github.com/vector-im/riot-web/issues/3253
