### ISSUE TITLE
RTS welcome page CSS is farked on Safari

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3298]

**Comment by lukebarnard1** [comment]
I've figured out the changes needed:
```css
.mx_HomePage {
    height: 100%; 
    overflow-y: hidden;
}

.mx_MatrixChat_middlePanel {
    height: 100%;
}

**Comment by ara4n** [comment]
This sounds like a worryingly invasive change, in terms of changing the 
whole height management CSS of the app, which I had absolute hell 
sorting out in the initial incarnations of vector.  Particularly I think 
it might break when the status bar is visible at the top.  I'll have a play.
