### ISSUE TITLE
mx_AddressSelector needs much better CSS

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3301]
It should be as wide as the input box above it, and the position:absolute is probably unnecessary

**Comment by ara4n** [comment]
the design is deliberately that the dropdown is not the full width of the text input, but the width of the results.  is that the only concern here?

**Comment by lukebarnard1** [comment]
That seems fair. In hind-sight, "much better CSS" is _slightly_ ambiguou :)
