### ISSUE TITLE
Invites subsection on left sidebar isn't very noticeable: roll-up badges to the sublist heading

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3305]
### Description

I didn't realize I had an invite until I checked my phone and saw the push notification. Having a more flashy way to see that there's a pending invite would be appreciated (or some kind of way to make it noisier).

### Steps to reproduce

- Get an invite
- Note how on riot-web it is somewhat hidden (see screenshot)

*Describe how what happens differs from what you expected.*
I'd expect an icon of some kind to show that there's a pending invite. Something like the red pinged badge?

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/23236780/cdbbf79e-f917-11e6-87cd-7a534a26bbc7.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
we should be rolling up the badge count to the unread list when it's collapsed to make them more obvious

**Comment by ara4n** [comment]
we do this on the other sublists; this is just a plain old bug.

**Comment by ara4n** [comment]
fixed in https://github.com/vector-im/riot-web/pull/3654/commits/e5e259e1f8e403383f5051e148c76229b59e0440
