### ISSUE TITLE
Opening MemberInfo starts a download of many users' keys

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3310]
... which is slooow. Why are we downloading keys other than those for the user in question?

**Comment by richvdh** [comment]
https://riot.im/bugreports/listing/2017-02-23/141949/

**Comment by ara4n** [comment]
related to https://github.com/vector-im/riot-web/issues/3588

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/425
