### ISSUE TITLE
Slow performance with Chromium on Linux

### ISSUE THREAD

**Issue by cglosser** [vector-im/riot-web#3312]
### Description

I'm experiencing some pretty significant performance issues under Chromium on Linux. It took upwards of 60 seconds to display my channel list after entering my login credentials, updates propagate sporadically out of the settings panels, and refreshing the page takes a similar amount of time, etc.

### Steps to reproduce

I don't know that there are any specific steps; this seems to occur on a fresh install of Debian + Chromium.

Log: sent

### Version information

- **Platform**: web
- **Browser**: Chromium 56.0.2924.76 Built on 8.7, running on Debian 8.7 (64-bit)
- **OS**: Debian 8.7
- **URL**: riot.im/app

**Comment by uhoreg** [comment]
I suspect that the slowness is more due to server issues rather than client issues.  The matrix.org server has been encountering performance issues recently (being a victim of its own success).  In particular, the delay after a fresh login or page reload are known to be slow.

**Comment by cglosser** [comment]
I wondered if it was more of a Matrix issue, but I don't seem to be having much difficulty on my Android phone. That certainly doesn't rule it out, though.

**Comment by uhoreg** [comment]
The Android app at least does some caching so that it doesn't always have to start from scratch when it is reopened, unlike the webapp, so that would eliminate at least one cause of slowness.  The next version of the webapp will have the same caching feature, which will speed up page reloads.

**Comment by cglosser** [comment]
Interesting! Good to know; thanks! We've really been enjoying Riot for a couple months now and I'm glad to hear these issues are more due to its popularity than something more technical.
