### ISSUE TITLE
register doesn't send the initial device display name?

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3316]

**Comment by richvdh** [comment]
yeah, this is a thing which was made surprisingly complicated by the Interactive-Auth. I thought we had bugs to track it already, but have been unable to find them.

**Comment by ara4n** [comment]
@dbkr is this actually a bug? in practice the device name is getting set somehow?

**Comment by richvdh** [comment]
I don't think it is being set on register.

**Comment by lampholder** [comment]
I'm killing this issue 'cause I don't think this little snatch of thinking from early 2017 is of much value hanging around.
