### ISSUE TITLE
UX: Improve Visibility of Encryption "Lock" Icons

### ISSUE THREAD

**Issue by tessgadwa** [vector-im/riot-web#3317]
Chat "lock" icon indicating whether a conversation is encrypted or unencrypted is light gray and very easy to overlook. This leads to confusion about whether a convo is encrypted or not. Several people have mentioned this issue. Suggest a simple fix -- adding color to lock icons. I am enclosing two variants--gold and cobalt--as well as the original gray
![e2e-unencrypted-cobalt-darktheme](https://cloud.githubusercontent.com/assets/6475035/23326565/bc33f092-facc-11e6-91f0-5354092526eb.png)
![e2e-unencrypted-cobalt-lighttheme](https://cloud.githubusercontent.com/assets/6475035/23326567/bc351828-facc-11e6-861f-471ce506752b.png)
![e2e-unencrypted-gold-darktheme](https://cloud.githubusercontent.com/assets/6475035/23326568/bc3695a4-facc-11e6-93e6-dbfce28d5480.png)
![e2e-unencrypted-gold-lighttheme](https://cloud.githubusercontent.com/assets/6475035/23326566/bc347db4-facc-11e6-9e87-41fc38d5dac7.png)
![e2e-unencrypted-grey-darktheme](https://cloud.githubusercontent.com/assets/6475035/23326569/bc371c9a-facc-11e6-962e-637401b07603.png)
![e2e-unencrypted-grey-lighttheme](https://cloud.githubusercontent.com/assets/6475035/23326570/bc38ec1e-facc-11e6-86ec-c1ae34e921f4.png)

 for comparison, in both light and dark themes. 

I would recommend same color be used for locked and unlocked states. 

Let me know if folks have other thoughts re: color and visibility. If not I will submit new SVGs as a PR.

**Comment by tessgadwa** [comment]
Third option (referenced from last night's discussion online): black lock for light theme,  white lock for dark theme.

**Comment by tessgadwa** [comment]
See thread https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/%241487971316629269UYhJd:matrix.org

**Comment by richvdh** [comment]
Dup of https://github.com/vector-im/riot-web/issues/2850, which has been addressed on develop

**Comment by uhoreg** [comment]
@richvdh there were some comments in one of the rooms that some people didn't like the "Send a message (unencrypted)" message that was implemented.  This was meant as an alternative to that, which would still make it clearer that the room is unencrypted, but which would be less confusing to people.

**Comment by richvdh** [comment]
If the issue is "we don't like 'Send a message (unencrypted)'", probably best to open an issue explaining why. This issue didn't seem to even mention that message.

**Comment by tessgadwa** [comment]
Comment purely for clarification -- issue was opened bc gray color of both locked and unlocked encryption icons makes them exceedingly easy to overlook.
