### ISSUE TITLE
show spinner whilst doing initial incr sync

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3318]
very confusing that we don't distinguish between initial app launch running from indexeddb data versus once it has actually done a catchup sync

**Comment by lampholder** [comment]
@ara4n Do we know what success looks like for this?

**Comment by ara4n** [comment]
yup. the app knows when it's actively syncing successfully from the server and when it isn't - but we're warn the user for the scenario that the app has yet to start syncing after launch.  This didn't use to be a problem, but since we added indexeddb it means the user can see a stale version of the data on launch but be unaware that it's stale.

Success would be to just show a "Not yet connected to server" warning in the status bar (similar to the "Can't connect to server" warnings we already show) - or just superimpose a spinner on the history whilst we wait to connect.
