### ISSUE TITLE
 Hard to find the "Room directory" button

### ISSUE THREAD

**Issue by frabcus** [vector-im/riot-web#3321]
### Description

When first using Riot, I went into a room, but couldn't work out how to get out again.

### Steps to reproduce

- Go into a room as a new user
- The only way out is to click the tiny folder icon. It took me ages to find this. The four icons down there are very small and cryptic for primary interface.

Suggestions for ways to improve it:

- Put the "Room directory" command at the top of the list of rooms in the very visible sidebar above.
- Then the "Create new room" could go in the same place. And "Start chat" in the section for "People".
- Make all those icons a bit larger and clearer, preferably with text not just icons.

### Version information

- **Platform**: desktop

For the web app:

- **OS**: Ubuntu
- **Version**: 0.9.7

**Comment by ara4n** [comment]
i think this is a dup of #2955?

**Comment by frabcus** [comment]
So it is, sorry!
