### ISSUE TITLE
URL displayer shows carriage returns

### ISSUE THREAD

**Issue by frabcus** [vector-im/riot-web#3324]
### Description

When expanding URLs, if the page being viewed has carriage returns in its title

### Steps to reproduce

- Paste in a URL of a site with carriage returns in the HTML <title> 
- The display of the title has multiple lines in it, and looks messy, like this.

![radar-bug](https://cloud.githubusercontent.com/assets/10153/23342248/cb4b2ca2-fc4e-11e6-87b6-488a9690a777.png)

Expected behaviour is to squash up all white space in the title into ordinary spaces, and it look good. Browsers all do this - I guess because HTML is neutral about kind of whitespace.

This is the source code to the page:

![source-space-title](https://cloud.githubusercontent.com/assets/10153/23342266/30f67fde-fc4f-11e6-91cb-535dd990b5f2.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by ara4n** [comment]
fixed in 8a7ec27 - thanks!
