### ISSUE TITLE
room directory is very very slow over federation as that API doesn't let you paginate

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3327]
It takes at least 90 seconds to get a room list

**Comment by ara4n** [comment]
@erikjohnston are you seeing this?

**Comment by richvdh** [comment]
(ftr, it has never been quick. I assume it pulls the entire room list from matrix.org before responding to the client)

**Comment by erikjohnston** [comment]
yes, it is quite slow

**Comment by ara4n** [comment]
...and it gets stuck issuing 50x's half the time :(

**Comment by ara4n** [comment]
I've split this into two synapse bugs: matrix-org/synapse#1980 (general perf problems) and matrix-org/synapse#1981 (client-reader gets entirely wedged).

**Comment by ara4n** [comment]
so @erikjohnston seems to have fixed the 'general perf problems' part of this, but the problem over federation still exists.  Apparently this is because the publicRooms API simply doesn't paginate at all over federation.

**Comment by ara4n** [comment]
apparently it should be usable but slow over federation (i.e. it's as slow as if you weren't paginating).

**Comment by ara4n** [comment]
reprioritising appropriately

**Comment by martindale** [comment]
Current status?

**Comment by ara4n** [comment]
still waiting for someone to make the directory api paginate over federation, sadly :(

**Comment by ara4n** [comment]
This is going to get really bad with the advent of hosted homeservers.

**Comment by ara4n** [comment]
I'm also not sure whether the problem is really a question of pagination or caching problems.  This might also improve if we ever land the matthew/stats branch, so that the public room directory can just be pulled straight out of a room_stats table rather than having to do more sophisticated shenanigans?

**Comment by martindale** [comment]
Any interest in a merkle tree implementation for federation of large list?
🤷‍♂️

**Comment by turt2live** [comment]
Searching matrix.org now that the directory is paginated is pretty quick.
