### ISSUE TITLE
Dark theme on dark tint makes buttons look greyed out

### ISSUE THREAD

**Issue by Kegsay** [vector-im/riot-web#3328]
![dark-tint](https://cloud.githubusercontent.com/assets/7190048/23363057/968fd038-fcf0-11e6-989a-dd28521f0feb.png)
![dark-tint2](https://cloud.githubusercontent.com/assets/7190048/23363058/969060a2-fcf0-11e6-84a3-678066186411.png)

**Comment by ara4n** [comment]
the bug here is that if you set the colourscheme to make the buttons grey... the buttons are grey? ;D  I guess the only mitigation here would be to colour the button text white if you choose the grey colourscheme.

**Comment by tessgadwa** [comment]
I think it is a very limiting in general to be using the same set of buttons across light and dark themes; particularly challenging for individuals who are colorblind. I would recommend making two complete sets of SVG icons, one each for light and dark themes. Happy to assist in graphics production, if others feel there is a need.  :)

**Comment by Kegsay** [comment]
> if you set the colourscheme to make the buttons grey... the buttons are grey?

$insert_50_shades_of_grey_joke

> colour the button text white if you choose the grey colourscheme.

Yup, this is what I was gunning for.

**Comment by pafcu** [comment]
@Kegsay Gray is no longer suggested for tinting. Does this solve the issue?
