### ISSUE TITLE
consider adding guest access for bridged rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3335]
eg experience at http://indieweb.org/discuss is horrid as guest access isn't enabled

**Comment by lampholder** [comment]
@ara4n this sounds like a fairly chunky feature rather than a bug, or do you disagree? Trying to access that room as a guest fails in a fairly clear way I think.

**Comment by ara4n** [comment]
hopefully this will be solved by the new guest landing stuff. agree that it's a feature; unsure what i was smoking.

**Comment by t3chguy** [comment]
ILAG has since landed
