### ISSUE TITLE
when /versions succeeds but /sync fails, there is no disconnected indicator

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3336]

**Comment by ara4n** [comment]
Quite possibly related to https://github.com/vector-im/riot-web/issues/2523 and also tangentially similar to https://github.com/vector-im/riot-web/issues/3318

The end result is that you can be disconnected from the server but seemingly everything is fine...

**Comment by ara4n** [comment]
prioritising as p1 'cos with synapse still being overloaded we expect to see more synchrotron meltdowns, and it's awful that it can result in everyone's riot's talking the void with no evidence of problems.  It also gets in the way of diagnosing when the synchrotrons are screwed, because we could legitimately just notice ourselves for minutes on end.

**Comment by lukebarnard1** [comment]
So my hunch is that successfully calling `/versions` but encountering an error on `/sync` leads to the sync state being left in `RECONNECTING`. I'll make a PR that includes this sync state as another possible indication of connection loss.
