### ISSUE TITLE
Please add support for linking to a room (for new people to join it)

### ISSUE THREAD

**Issue by kaniini** [vector-im/riot-web#3341]
### Description

It would be nice to have the ability to generate a link to a room, probably with a nice looking badge icon like the rest of the ones you see on Github.  This would be a powerful tool for people wanting to easily onboard additional users to their rooms.

### Version information

- **Platform**: web
- **Browser**: Chrome 56.0.2924.87 (64-bit)
- **OS**: Mac
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? riot.im/app

**Comment by uhoreg** [comment]
looks like a dup of #2373 and/or #877

**Comment by kaniini** [comment]
likely so, apologies if that's the case :)

**Comment by lukebarnard1** [comment]
dup
