### ISSUE TITLE
rich-text-editor consumes Ctrl-Tab

### ISSUE THREAD

**Issue by HendrikF** [vector-im/riot-web#3344]
### Description

The rich-text-editor consumes Ctrl-Tab when focused, so tabbing away from Riot is only possible after removing focus from the editor.

### Steps to reproduce

- turn on rte in settings
- open another tab and switch back to riot
- focus editor
- ctrl-tab should now switch to the second tab, but does not

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 54.0
- **OS**: Ubuntu 16.04 + Windows 7
- **URL**: private server

matrix-react-sdk version: 0.9.1
vector-web version: v0.10.1

(@hendrik:h3ndr1k.de)

**Comment by aviraldg** [comment]
@HendrikF I attempted to reproduce this issue on both Firefox and Chrome but could not -- not sure what could be causing the issue for you.

**Comment by HendrikF** [comment]
I updated the steps to reproduce. It is perfectly reproducible for me, even with all firefox addons disabled.

I just noticed, that the editor does nothing when pressing tab and the focus stays there.
This is ok, but do you do the same when modifying keys are pressed? This might prevent tab switching.

**Comment by lukebarnard1** [comment]
I can't repro this either.

**Comment by HendrikF** [comment]
Can still reproduce. Even on Windows 7 and with updated Riot (0.10.1).

Note that I don't mean Alt-Tab.

But yeah, feel free to close as I seem to be the only one having this issue... 😕
