### ISSUE TITLE
Show room notification volume level on RoomTile

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3346]
We used to have this, but it got removed, perhaps because it's a bit too busy or Will couldn't get it to work right.  The idea is:

 * [x] Show mute icon where the badge overlay would be if a room is muted (and grey out the room text a bit?)
 * [ ] Show 'mentions only icon' if it's mentions only
 * [ ] Show 'loud' icon if it's noisy.
...otherwise we don't show anything special.

**Comment by yannicka** [comment]
Are you referring to this?
![image](https://user-images.githubusercontent.com/22885898/87853810-b19f8200-c90d-11ea-9767-f0d3f026894a.png)

It has been added recently.
