### ISSUE TITLE
filtering roomlist and then clicking on a room resets the filter

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3348]
wtf?

**Comment by ara4n** [comment]
@dbkr @lukebarnard1 @richvdh anyone want to 'fess up to causing this? O:-)  I assume that it's some weird lifecycle problem for RoomView itself?

**Comment by lukebarnard1** [comment]
@ara4n I did some RoomTile-related stuff recently, it might have been that. I'm kind of failing to imagine how though.

**Comment by lampholder** [comment]
The current behaviour (clear filter on room selection) is at least as confusing as its opposite (stick filter on room selection). I think something more user friendly (supporting either behaviour) requires some thought, and the current behaviour is not too bad, so I'd propose leaving it as it is until that thinking has been done.

**Comment by ara4n** [comment]
From my POV this is very much a regression in behaviour, even though the original behaviour was actually a bug.  We can have a separate issue if we want to change or extend the behaviour - for now i've fixed the regression in 8bc434a.
