### ISSUE TITLE
Sending a message into an encrypted room fails silently

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3353]
### Description

When sending a message into an encrypted room, the resend bar appears and an error is logged : `Error sending event Error: Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.`.

### Steps to reproduce

- Send a message into an encrypted room
- Not sure of particular repo steps

Log: not sent - built locally

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: (basically riot.im/develop) vector-im/riot-web@a79e05d matrix-org/matrix-react-sdk@e75c21e matrix-org/matrix-js-sdk@ff36064

**Comment by lampholder** [comment]
Hey @lukebarnard1 - when does this happen? It doesn't happen on every sending of a message into an encrypted room... :P

**Comment by lampholder** [comment]
Could be the same as #3498 ?

**Comment by lukebarnard1** [comment]
I can't repro. Redacting the encryption event does not have an effect...
