### ISSUE TITLE
Joining a new channel on Freenode does not list all members

### ISSUE THREAD

**Issue by aruiz** [vector-im/riot-web#3357]
I just joined #blogalia through the freenode bridge and only newly joined users would be listed

**Comment by uhoreg** [comment]
This is due to matrix-org/matrix-appservice-irc#344.  In short, membership on Freenode currently isn't fully synced for performance reasons, but will be done eventually.

**Comment by aruiz** [comment]
I understand, thanks for the feedback.

**Comment by ara4n** [comment]
dup
