### ISSUE TITLE
Mentions don't highlight after a reload

### ISSUE THREAD

**Issue by sbts** [vector-im/riot-web#3368]
Hitting F5 to update RIOT web causes all previous highlights to become normal text. Especially when running develop this is horrid as finding those mentions in a busy channel when you can be updating a number of times an hour.

**Comment by dbkr** [comment]
I can't repro this. Can you be more specific?

**Comment by ara4n** [comment]
i can't repro this either. @sbts please give full repro steps (and ideally use the template when filing bugs in future in case that helped clarify how to repro...)

**Comment by sbts** [comment]
@dbkr @ara4n 
Ok, so this is interesting, I've had this issue for a long time, including up to the version of develop that was running when I raised the issue.

This version (or perhaps the one before it) exhibited the issue 
> matrix-react-sdk version: b7f1b1a424c17b8c8c829da840501a15e1a12fde
riot-web version: 08852c61742c-react-b7f1b1a424c1-js-b52a674c1a8f
olm version: 2.2.1

However this version seems to have fixed it
> matrix-react-sdk version: 2786fb0f467153c62463b906cc500e5fb169b1d7
riot-web version: e5b3ec83b338-react-2786fb0f4671-js-2cd5fe2fec71
olm version: 2.2.1

**Comment by sbts** [comment]
The repo steps __*were *__ as simple as....
- see that an update was needed (green bar at top of window)
- view any highlight and it is shown in highlight colour
- hit F5 to reload the new version
- view the same highlight and it's now normal text colour instead of highlight color

**Comment by ara4n** [comment]
pretty sure this is now resolved.
