### ISSUE TITLE
drop & drag RoomTiles results in them flipping to their previous position...

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3370]
before the change takes effect, and then they jump back to where you asked them to go

**Comment by ara4n** [comment]
before the change takes effect, and then they jump back to where you asked them to go

**Comment by lampholder** [comment]
I wasn't able to verify this on chrome (56) or firefox (52) - @ara4n presumably you were using /develop and Chrome?

Similar to but distinct from https://github.com/vector-im/riot-web/issues/2004

**Comment by ara4n** [comment]
all bugs from the core team should be assumed to be on develop unless stated otherwise :)

Here's a video that clearly demonstrates #3280 (first half) and this bug (second half):

https://github.com/vector-im/riot-web/issues/3280 (https://matrix.org/_matrix/media/v1/download/matrix.org/QGjQcfAikCABgzKOXEOOrgOB

It's very possible the two are related.

**Comment by ara4n** [comment]
(worth noting that my video shows that on MacOS Chrome at least i'm immune to #2004)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8614
