### ISSUE TITLE
Hitting refresh on /develop shows you the login prompt for about 2s before it suddenly disappears

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3371]
This is very very disconcerting and makes you think you may have lost your e2e keys. @dbkr is this a regression in your stuff?

**Comment by ara4n** [comment]
@lukebarnard1 or is this an RTS thing?

**Comment by lukebarnard1** [comment]
I recently refactored the bit that decides which screen gets shown after login (which happens at refresh). The previous impl was a bit race-y iirc.

This could be solved by moving `<Login>` from being in the `else` in `MatrixChat.render` to being in an `else if(screen === login)` and putting the spinner in the `else`.

**Comment by lampholder** [comment]
The scope of this is to figure out the smallest and least-invasive solution to users' seeing the flash of the login ui.

**Comment by lukebarnard1** [comment]
The route cause is (in `MatrixChat`):
 - `this.state.logged_in` being `false`
 - `this.state.loading` being `false`
 - `MatrixChat` defaults to `<Login>`

This is can be exacerbated (for reproduction) by inserting a delay before `logged_in` is set to true.
