### ISSUE TITLE
Replace the icons with Google Material Design Icons

### ISSUE THREAD

**Issue by ishitatsuyuki** [vector-im/riot-web#3372]
tldr; Yes, your thin design is wrong.

The current icon has 1px width which hurts your eyes, and some of them looks odd (e.g. notifications bell).

Reference: Material Design Guidelines recommends 2dp stroke + round corner.

**Why just not replace them with the industry standard MD icons?**

* The Google MD icons library probably has all the icon we use, in a more beautiful version.
* It's available as Apache-2.0.
* It's easy to add, just a npm package. Its size is probably more optimized than ours.

**Comment by ara4n** [comment]
your opinion of the icons is subjective; please feel free to contribute a theme with whatever icons you happen to personally like the most.

**Comment by tessgadwa** [comment]
@ara4n  I have some issues with Google Material Design; it is a complete set of specifications but I don't feel it is the be-all-and-end-all.  I have been thinking about contributing a Riot theme myself, to address some of the issues I have observed regarding the visibility of key features, for instance encryption labels.

I do have concerns about the proliferation of themes -- 1) Many naive users are overwhelmed and confused by choices, not empowered by them.  2) It diverts effort from making the core/default UX experience more seamless and awesome.  3) As new features and icons are added it will be more difficult for ad hoc authors authors to keep up with them and many themes will break.

I think the way that Trello handles theme choice, and also its UX for multi-platform integrations, is a great model. Note that they have a theme option specifically designed for low-vision, color-blind individuals.

**Comment by tessgadwa** [comment]
Community UX feedback from GNOME devel land (metabug) #3373
