### ISSUE TITLE
Unable to join new freenode channels and neither can get room list 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#3378]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Go to Room Directory 

- Select #Freenode from the list of servers there 

- Try to get the list 

Describe how what happens differs from what you expected.

It should have given the list. 

Log: sent/not sent?    

I don't see it in the settings page , I did see this however, might be useful 

```
Logged in as @shirish:matrix.org
Homeserver is https://matrix.org
Identity Server is https://vector.im
matrix-react-sdk version: 0.8.6
vector-web version: 0.9.7
olm version: 2.2.1
```

### Version information

- **Platform**: web (in-browser) or desktop?  

Desktop 

For the desktop app:

- **OS**: Debian GNU/Linux 
- **Version**: 0.9.7

I am unable to get a freenode room list I get the following error - 

```
Failed to get public room list

Unexpected end of JSON input
```

Getting to a room gets me an empty room when I know it should be filled with people.

**Comment by CR0CKER** [comment]
Same problem here, except that I cannot get ANY room list anymore. Not just Freenode channels.

**Comment by pmgouveia** [comment]
I get to errors on my Inspect > Network tab:

`https://matrix.org/_matrix/client/unstable/thirdparty/protocols?access_token=MDA 403 Forbidden`
`https://matrix.org/_matrix/client/r0/publicRooms?access_token=MDAxO 502 bad gateway`

**Comment by pmgouveia** [comment]
both in chromium Version 56.0.2924.87 (64-bit)
 and firefox 51.0.1

`XMLHttpRequest cannot load https://matrix.org/_matrix/client/r0/publicRooms?access_token=MDAxOGxvY2F0a…QgPSB0cnVlCjAwMmZzaWduYXR1cmUgvcafUwBNPt5mnthhJFiJ3-fLcQWtKNrqTs2ffA94muUK. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://riot.im' is therefore not allowed access. The response had HTTP status code 502.`

`Failed to get publicRooms: {"cors":"rejected"}`

**Comment by ara4n** [comment]
dup #3327. thanks for the comprehensive bug reports though :) fixing this is a top priority atm...
