### ISSUE TITLE
clicking on notifs in notifications panel goes to matrix.to

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3380]
Shouldn't they open in-app?

**Comment by richvdh** [comment]
(in /app, the links go to riot.im. In /develop, they have been replaced with matrix.to, which is fine, but they probably need an onclick handler)

**Comment by lukebarnard1** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/735 changed all event permalinks to matrix.to. It might be possible to use `onClick` to prevent the `<a>` from jumping to it's `href` and instead go to /#/room/bla/bla
