### ISSUE TITLE
Add badge counts & highlights to NotifPanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3383]
Oddvar, Tom, and many others simply don't know it exists.

**Comment by ara4n** [comment]
Apparently ribot have already fixed this :S 

<img width="174" alt="screen shot 2017-03-08 at 14 24 26" src="https://cloud.githubusercontent.com/assets/1294269/23707630/faedaa34-040a-11e7-8b58-287d94146db0.png">

**Comment by ara4n** [comment]
this depends on having NotifPanel able to distinguish highlights from non-highlight notifs - and actually display a count!

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2336
