### ISSUE TITLE
read receipts overlap with long messages

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3384]
https://matrix.sw1v.org/_matrix/media/v1/download/jki.re/EoyDXTiJpWlHSMlfmQwJjkrz

**Comment by lampholder** [comment]
Assuming: Chrome /develop ?

I suspect the problem is due to the double-digit user read count - long messages seem to be fine otherwise.

**Comment by lukebarnard1** [comment]
This seems fixed to me, although finding evidence that some CSS has changed that would fix this is proving difficult.
