### ISSUE TITLE
CSS for new "Create a new chat or reuse an existing one" dialog

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3387]
We have a new "Create a new chat or reuse an existing one" dialog!  Yay!

But whoever implemented it made up their own CSS & design, and we don't seem to (cue passive aggressive bug filing) have a bug to track that as an issue.

**Comment by tessgadwa** [comment]
Do we have an existing design standards guide w/CSS attached?  Hint: this is something I'd love to take on.

**Comment by ara4n** [comment]
@tessgadwa no, we don't have a pure design guide, although in practice pretty much every asset is drawn out on zeplin.  It would be great to have got a formal design language book from the design agency, but too much $.

I've fixed the CSS here.
