### ISSUE TITLE
Jumping to a membership event causes infinite back pagination 

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3388]
- Goto https://riot.im/develop/#/room/#riot-dev:matrix.org/$14889852423133093YTgbI:matrix.org for example
 - Watch the timeline scroll up infinitely 
 - Do some scrolling over the timeline to stop it

This was discovered in the process of creating https://github.com/matrix-org/matrix-react-sdk/pull/744 and is not caused by it.

**Comment by lampholder** [comment]
I can confirm that clicking that link does cause a heck of a lot of pagination.

Could you help me out by letting me know what the expected behavior is?

**Comment by ara4n** [comment]
it should jump to the right event, and stick there rather than going berserk.  i.e. same as any other event.

**Comment by lukebarnard1** [comment]
I don't think this happens anymore. Closing!
