### ISSUE TITLE
CSS for redacted events

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3390]
https://github.com/matrix-org/matrix-react-sdk/pull/739 needs better CSS

https://github.com/vector-im/riot-web/pull/3379 is the working CSS

**Comment by ara4n** [comment]
before I try to fix up the CSS for this, please can the visible redaction be tweaked to display the sender's name, message timestamp, etc?  I assumed that folks knew what a redaction looked like, but the idea is something like this:

![image](https://cloud.githubusercontent.com/assets/1294269/23837522/f0d4b496-0781-11e7-807e-988329dfba1b.png)

Obviously we don't know the right size of black-out to use, so i'd suggest just making it 30 characters wide or something.

To be explicit, I think a sensible appearance would be:

<img width="977" alt="screen shot 2017-03-13 at 00 16 11" src="https://cloud.githubusercontent.com/assets/1294269/23837560/48d58b5c-0782-11e7-9de9-4d076991ad3c.png">

**Comment by lukebarnard1** [comment]
@ara4n we can't show sender or TS until JS-SDK doesn't redact `origin_server_ts` or `sender`. See https://github.com/matrix-org/matrix-js-sdk/issues/387

Also, thanks for the explicit design.
