### ISSUE TITLE
Clicking invitation RoomTile leads to rejection

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3394]
### Description

When clicking an invitation RoomTile ("invitation from ...") in the LeftPanel, the room becomes historical and the invite is rejected.

The invite was sent from a ldbco.de user to a matrix.org user.

The logs show
```
[!FQzHaMbMZokvBFbPRK:ldbco.de] Peek poll failed: MatrixError
```

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
@erikjohnston said this was something to do with federation and peaking on matrix.org

**Comment by erikjohnston** [comment]
(I said it *could* be)

**Comment by lampholder** [comment]
Find out the cause and scale of impact of this is important before the next release - if it's affecting a lot of people badly we should include it in the next release; if not, we can deprioritise it.

**Comment by lampholder** [comment]
@lukebarnard1 to reproduce this and add the logs.

**Comment by lukebarnard1** [comment]
Could not reproduce this, peaking seems to not give any errors this time around.
