### ISSUE TITLE
Margin to the right of read receipts is misaligned, as is the MELS collapse button (regression)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3396]
This is a regression.  On /app:

<img width="160" alt="screen shot 2017-03-09 at 17 10 45" src="https://cloud.githubusercontent.com/assets/1294269/23761654/6d846fca-04eb-11e7-9ec4-b577a8643f86.png">

On /develop:

<img width="159" alt="screen shot 2017-03-09 at 17 10 35" src="https://cloud.githubusercontent.com/assets/1294269/23761668/71ef88ec-04eb-11e7-8a41-1a748d9c4d07.png">

The margin between RRs and the RHS of the timeline has got way too big - probably also causing https://github.com/vector-im/riot-web/issues/3384.  Please can we be super-careful about introducing cosmetic regressions like this.

Meanwhile, the MELS 'collapse' button has the correct margin (but is then unaligned with the RRs).  I assume the reason to put the MELS collapse button on the RHS is to let you quickly toggle them on & off, as they'd be replaced by a Collapse button which is in the same place... except in practice when you click it, the button typically jumps upwards on the page due to the scroll lock.  So I'd be quite inclined to put it back where it was in the first place - i.e. inline in the MELS.  Which presumably might also fix the CSS which is causing the original issue here.

**Comment by lukebarnard1** [comment]
It looks like the RRs are off to the left by the width of one RR.
