### ISSUE TITLE
Camera not selectable

### ISSUE THREAD

**Issue by petmos** [vector-im/riot-web#3397]
### Description

Feature request: Possibility to select front camera on notebooks.

### Steps to reproduce

- Start riot on a system with 2 camera systems
- Start a video call and try to use front camera instead of rear camera

When starting a video call the user should be asked which camera system should be used (like in browsers when using cameras over webRTC).

Log: not sent?    

### Version information

- **Platform**: desktop
- **OS**: Windows10
- **Version**: 0.9.7

**Comment by ara4n** [comment]
dup of #2822 - thanks though :)
