### ISSUE TITLE
preview when pasting an image from the clipboard

### ISSUE THREAD

**Issue by bbigras** [vector-im/riot-web#3399]
I'm really glad that we can now paste images from the clipboard (see #1297).

I think it would be nice to be able to see a preview before uploading just like discord does. It's a really nice way to prevent uploading the wrong stuff.

With discord we can also add a comment at this moment.

**Comment by lampholder** [comment]
This would be a nice enhancement.

Related to feature: #1297

**Comment by t3chguy** [comment]
closing in favour of more generic #1881
