### ISSUE TITLE
After pasting an image to Riot, focus is lost on the message entry field

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3400]
### Description

Being able to paste files is a great addition, and very useful (I was getting annoyed at having to save and upload images constantly). One minor annoyance is that focus is lost from the text entry field after the upload dialog is closed (approved or denied). It would be nice if I could approve the dialog and send a message right after without having to figure out where my cursor went.

### Steps to reproduce

- Copy an image/file to your clipboard
- Paste it in Riot
- Approve the dialog (or decline - I don't judge)
- Note that your cursor isn't in the text entry field

I would expect that, at least, if I started the paste operation with my cursor in the field then my cursor would still be there after the paste operation.

Log: not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Should be an easy fix to remove a niggling issue.

Related to: #1297

**Comment by t3chguy** [comment]
likely fixed by https://github.com/matrix-org/matrix-react-sdk/pull/822

**Comment by turt2live** [comment]
Fixed by @t3chguy in https://github.com/matrix-org/matrix-react-sdk/pull/822 by accident.

Thanks @t3chguy :)
