### ISSUE TITLE
'Resend All / Cancel All' option still shown after Unknown Device Dialog 'Send Anyway' clicked

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3401]
### Description

*Feel free to rename this issue if the title is inaccurate - I found it difficult to come up with a descriptive subject in 10 seconds or less.*

It is somewhat confusing to see the 'Resend All' option after clicking 'Send Anyway' to the Unknown Devices dialog. This only applies to e2e rooms.

I feel that having the option to resend/cancel messages should be hidden based on the user's selection to the dialog. For instance, 'Send Anyway' should act as 'Resend All' and hide the option completely while the message visually indicates it is sending.

### Steps to reproduce

- Be in an encrypted room with unknown/new devices
- Send a message
- Note that the dialog says 'Send Anyway' - click that
- Note that the 'Resend All' option is still shown. Depending on latency and all that, this can be present for a couple seconds or so.

I would have expected to not be able to thing about resending after already asking the messages to be sent. The prompt was present long enough to be confusing as to whether or not the 'Send Anyway' button actually worked.

Log: not sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I was able to reproduce this - I only saw the 'Resend All/Cancel All' prompt for maybe half a second, but as @turt2live says this probably varies based on latency.

**Comment by lukebarnard1** [comment]
I have seen this today myself. It seems a bit pointless to show the status bar ("resend/cancel all") when the user has already decided to effectively resend all.

**Comment by turt2live** [comment]
This has slightly regressed to expected behaviour, but is still "broken". The status bar is still shown immediately after showing the dialog, however previously it would also be shown when switching rooms. This is no longer the case (it doesn't re-appear).

This is also effectively fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1600 when it lands

**Comment by turt2live** [comment]
This got resolved
