### ISSUE TITLE
accepting an invite from a different client doesn't add the room to the room list until cache is cleared

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3403]

**Comment by lampholder** [comment]
Hey @dbkr - can you advise how frequently the cache is cleared without its being forced?

**Comment by ara4n** [comment]
it's never cleared, only when forced.  i'm not sure that the bug here is accurate though; my hunch is that something else went wrong and caused the invite to be ignored on the other client.

**Comment by ara4n** [comment]
i've had loads of invites and not seen them going awol. in fact, i wonder if this dates back to the initial teething bugs after indexeddb landed?  prioritising assuming it does still exist as a bug.

**Comment by lampholder** [comment]
I wasn't able to reproduce this on /app or /develop - accepting an invite on iPhone was immediately reflected in the roomlist on Riot Web.

Closing this - we can always reopen if @dbkr does start seeing this again.
