### ISSUE TITLE
actually route rageshakes into github issues keeping the files on the protected share

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3405]

**Comment by lampholder** [comment]
Where do rageshake reports go right now and how many do we get?

**Comment by ara4n** [comment]
we get a few a day; they go into a go server that kegan wrote that dumps them on a filesystem somewhere which is accessed via HTTP. the descriptions are currently dumped onto the FS; they should be routed into GH instead.  Originally we wanted to route them into a RT deployment, but it never got set up, and in practice having everything in GH is probably good enough.

**Comment by richvdh** [comment]
done, via https://github.com/matrix-org/rageshake/pull/4 etc
