### ISSUE TITLE
Support clientside search for e2e rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3413]
We should support searching the clientside history cache for e2e rooms.  This means that history would need to be stored (or indexed) unencrypted.  And ideally we should save as much history as possible.

**Comment by ylecollen** [comment]
We need to know the algorithm used by the server : it seems that some words are replaced.

**Comment by ara4n** [comment]
the algorithm isn't defined and depends on the server.  for instance, both sqlite & postgres provide different full-text-search implementations, so depending on which one your synapse is using, you'll get different results.

in other words: we should use the best full-text search engine available for a given platform (without spending too much time on it). On Android I suspect the simplest solution is sqlite as per https://developer.android.com/training/search/search.html, which will end up behaving the same as on Synapse-with-Sqlite.   The code for that is around https://github.com/matrix-org/synapse/blob/develop/synapse/storage/search.py#L298

Failing that, https://www.google.co.uk/search?q=android+full-text+search+library+stemming gives a bunch of alternative ideas.

**Comment by uhoreg** [comment]
looks like a dup of #2548

**Comment by ara4n** [comment]
so it is - thanks.
