### ISSUE TITLE
Upload images by pasting

### ISSUE THREAD

**Issue by Polsaker** [vector-im/riot-web#3415]
### Description

It would be nice if I could upload images by pasting them (Ctrl-V). It's very useful when I take screenshots or to just copy an image from a random site and paste it on Riot (without having to save it on the computer).

### Steps to reproduce
- Copy random [image on the internet](https://i.imgur.com/ui9dasO.jpg), go to the Riot tab and hit Ctrl-V. It should ask and upload the image.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Latest Chromium
- **OS**:  Arch Linux, etc

**Comment by ara4n** [comment]
this has already landed on riot.im/develop if you use the rich text editor labs setting.

**Comment by xuhdev** [comment]
This still does not work on 0.9.8, which should have already included the commit. I'm on Firefox and Chromium on Debian.

**Comment by uhoreg** [comment]
@xuhdev do you have the experimental "New Composer" enabled in your user settings?
