### ISSUE TITLE
Web/Desktop: No last seen attribute

### ISSUE THREAD

**Issue by Croydon** [vector-im/riot-web#3417]
### Description

While Riot Android shows when an user was online the last time, the web/desktop versions are not showing such an information. It simply states "offline" instead.

Android:
![lastseen](https://cloud.githubusercontent.com/assets/1593194/23862688/fa2dd0ea-080d-11e7-90b2-decbaec05110.png)

Expected: The last seen information is getting exposed to web and desktop as well.

### Version information
- **Platform**: web and desktop
- **OS**: Windows
- **URL**:  riot.im/app
- **Version**: v0.9.7´

Additional: The language of the Android version seems a bit odd. I'm sure everyone gets the point, but "Offline 2h ago" sounds... like I was offline 2h ago, so I'm online now? Oh and, yes, that's me, so why does it think I'm offline in the first place? At the very same time the Desktop versions says I do idle for 14mins. Since this is the same account, same room and same sever I don't get the different information.

**Comment by lampholder** [comment]
On some occasions Riot web does show you the same information (using the same language as the android app); on other occasions it just says 'offline'. I'm not (yet) familiar enough with the impl to know when it does what, and whether this is a bug or an integral feature of the platform.

I'll try and find out the right person to ask to find out :)

**Comment by lampholder** [comment]
UPDATE: The 'presence' feature currently has some known issues on matrix.org - some aspects of it are not enabled whilst associated performance constraints are worked out.

So, you might see presence for some users and not on others, but for any given user at a given time you should see the same information on Riot Web and Riot Android. Can you confirm whether this is the case?

**Comment by mvintila** [comment]
Could the 'presence' feature issues also cause #3432 ?

**Comment by Croydon** [comment]
> So, you might see presence for some users and not on others, but for any given user at a given time you should see the same information on Riot Web and Riot Android. Can you confirm whether this is the case?

As I said initially this is not the case. I see different information at the very same time in Riot Android and Riot Web/Desktop.

E.g. one user is displayed as online on Web but offline on Android, another idle on Web but offline in Android.

However, right now even in Android I'm only getting plain "offline" instead of a last seen time.

**Comment by lampholder** [comment]
Thanks for clarifying - I didn't get from the original report that the devices were showing different statuses _simultaneously_.

Leaving this at P2 for now; I suspect it will be significantly easier to solve once the presence performance challenges have been tackled.

**Comment by turt2live** [comment]
I haven't seen this since matrix.org has turned presence back on. A quick check of a few rooms showed that Android and riot-web appear to agree on the timestamp (with slight variance resulting from me being slow at checking).

**Comment by richvdh** [comment]
dup #2667 I think
