### ISSUE TITLE
Typing indicator avatar still appears even when the room status bar is showing (confusing).

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3418]
### Description

While waiting for a message to send in a room, someone started typing and that caused some state to leak through.

This was done in an e2e room, however I have a feeling (with zero evidence) that this could occur in a 'regular' room.

### Steps to reproduce

- Cause messages to not be sent (unknown device dialog, for instance)
- Have someone type in the room
- Note state (see screenshot)

I would have expected that the typing notification be suppressed so the avatar doesn't shine through the warning.

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/23867583/f799c98c-07e1-11e7-83f2-6670d7ddabdc.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Renamed to (hopefully) represent the issue more precisely :)

**Comment by turt2live** [comment]
Typing notifications are now a different element, so this shouldn't happen.
