### ISSUE TITLE
Message search UI is confusing

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3421]
### Description

Every time I use message search, I click on the "This Room" button several times, expecting something to happen, and am confused when nothing happens.  That's because "This Room" looks like an action button rather than a radio button (which it actually is) and the magnifying glass button looks like a decoration instead of a button.

### Steps to reproduce

(Disclaimer: the following is a dramatization.  Actual results may vary)

- click on the Search button in a room
- type something in the input box
- click on "This Room" to try to initiate search
- click again when nothing happens (repeat as needed)
- get confused
- frantically look around for something else that can be clicked
- see the magnifying glass icon that vaguely looks clickable
- click on it
- sigh in relief

Describe how what happens differs from what you expected.

AFAICT, the message search UI is the only place that uses a normal-button look for radio buttons, which makes it seem like clicking on them should actually make it *do* something, rather than just changing an option.  The "This Room" vs. "All Rooms" looks like a default action vs. secondary action.

Either the buttons should be changed to look like a normal radio button, or else they should be changed to actually perform the search.

Log: not sent

### Version information

- **Platform**: desktop (though it's also in web)

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.7

**Comment by lampholder** [comment]
100% agreed - radio buttons looking like normal buttons confused me, too.

**Comment by lampholder** [comment]
It's also slow and provides limited feedback, so it can appear broken :(

**Comment by turt2live** [comment]
I believe this is fixed with the redesign.
