### ISSUE TITLE
Add Safari < 9.0 to the 'recommended do not use' list (in modernizr?)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3425]
As per #3406 - Riot Web is all kinds of broken in Safari 8.1, but Safari 8.1 is 2 years old and only used by a handful of people.

Matthew indicated that we use modernizr to warn on browsers which are unlikely to have a good experience. Can we add Safari <9.0 to the list?

**Comment by ara4n** [comment]
solved by 8e2e6ce
