### ISSUE TITLE
Unlocked-padlock icon is too difficult to see in dark theme

### ISSUE THREAD

**Issue by OliverUv** [vector-im/riot-web#3433]
### Description

Unlocked-padlock icon is too difficult to see in dark theme. The one next to the field where the user types their messages.

![scrot](https://cloud.githubusercontent.com/assets/374505/23937722/e971ec5a-0993-11e7-96c1-d50431c36e04.png)

### Version information

- **Platform**: web (in-browser), , 
- **Browser**: Firefox 52 64bit
- **OS**: Kubuntu Yakkety
- **URL**:  riot.im/app /

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/2988

This appears to have been fixed in recent builds (not currently released)

**Comment by lampholder** [comment]
This appears to have been fixed for Chrome but not for Firefox; at least on /develop with my firefox it still looks a very similar colour to the background :P

**Comment by tessgadwa** [comment]
Relieved that this issue is getting attention. IMO the lime green color used for the locked encryption icon could be used for the unlocked icon as well.

**Comment by OliverUv** [comment]
I don't think you want these two opposite indicators to look too similar at
a glance, so I suggest an orange / warning like color instead. It should
probably have a slightly stronger luminosity, so that it is also different
for someone with color blindness that mash these two hues together

**Comment by tessgadwa** [comment]
I see your point Oliver. Truly, anything but grey!

**Comment by ara4n** [comment]
fixed  by @t3chguy in firefox too - thanks!
