### ISSUE TITLE
[RTE] quoting a message that has a quote in it doesn't nest the quote properly

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3444]
### Description

See below.

### Steps to reproduce

- enable RTE
- find a message that has a quote in it
- click the menu button on the right of the message and select "Quote"
![image](https://cloud.githubusercontent.com/assets/1012976/23963365/656751fe-0987-11e7-8fb0-5546ae12f676.png)
- see something like this in the composer area (sent message will appear similarly):
![image](https://cloud.githubusercontent.com/assets/1012976/23963380/7660f636-0987-11e7-9361-d45227dfdc0f.png)

Describe how what happens differs from what you expected.

The quoted portion of the original message should be nested, like:

>> test
>
> test

Log: not sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.7

**Comment by lukebarnard1** [comment]
whilst markdown supports nested quoting, draft-js native richtext quoting does not

**Comment by ara4n** [comment]
we support nesting now in matrix-org/matrix-react-sdk#1890, but quoting is broken for other reasons (https://github.com/vector-im/riot-web/issues/7034)
