### ISSUE TITLE
Don't fetch URL previews for links in quoted text

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3445]
because it usually just results in the preview showing up twice in quick succession (once for the original message, and once for the quoted message), wasting space

**Comment by lampholder** [comment]
This seems like a reasonable idea.

**Comment by uhoreg** [comment]
Alternatively, rate-limit URL previews so that the client won't try to preview the same URL if it already appeared in a recent message (similar to what's suggested in matrix-org/go-neb#151)

**Comment by pafcu** [comment]
@uhoreg This seems to have been fixed. Could be closed?

**Comment by uhoreg** [comment]
Indeed, it seems to be fixed.
