### ISSUE TITLE
Support multiple accounts for desktop version

### ISSUE THREAD

**Issue by exap** [vector-im/riot-web#3447]
At the moment I can't _really_ use multiple accounts, that is signing out from my current account and logging into a another account:

If I sign out from my current account, the keys will be deleted. So verifying a key becomes pointless because you'd have to verify a key everytime you sign into an account again.

Solution: Don't delete the keys when signing out. Only create keys on the first login from that device.

**Comment by exap** [comment]
#2108

**Comment by richvdh** [comment]
dup #2320
