### ISSUE TITLE
Read Marker is hidden by things

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3450]
It seems to be frequently obscured by code blocks and highlighted events. The line probably needs a higher z-index.

**Comment by lampholder** [comment]
@lukebarnard1 Could you provide any more detail? Is it wholly obscured such that it's impacting its function? thx

**Comment by lukebarnard1** [comment]
Yep, completely obstructed. I'll try to grab a screenshot.

**Comment by lampholder** [comment]
@lukebarnard1 lets have a look IRL when you're back :)

**Comment by lukebarnard1** [comment]
![img_8190](https://cloud.githubusercontent.com/assets/6750344/24752387/91910e6a-1ac5-11e7-8aa0-7800a5d7c6a6.JPG)

**Comment by lukebarnard1** [comment]
Perhaps some CSS:
```CSS
hr.mx_RoomView_myReadMarker {
   /*top: 5px*/
   top: -2px;
}
```
