### ISSUE TITLE
"More" ellipsis is broken for Favourites

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3452]
![2017-03-16-151441_246x388_scrot](https://cloud.githubusercontent.com/assets/6750344/24003434/62e2eae0-0a5b-11e7-9772-be5ca078d063.png)
Clicking "more" reveals unread rooms:
![2017-03-16-151451_247x178_scrot](https://cloud.githubusercontent.com/assets/6750344/24003433/62d070b8-0a5b-11e7-91f7-0df6acb77007.png)

**Comment by lampholder** [comment]
Are there only meant to be inactive/quiet/read rooms below the ---MORE ?

**Comment by lukebarnard1** [comment]
"More" shows when there are > 10 rooms listed in each sublist. The hidden rooms are determined purely on how they are ordered, which for favourites is manual. The button to the right of "More" should display the number of unread rooms.

**Comment by lampholder** [comment]
@lukebarnard1 - so is that what's broken? That the button to the right of 'more' doesn't show the number of hidden rooms?

**Comment by lukebarnard1** [comment]
Actually it is working, I got confused with my notification settings 😅 

When I said 
>The button to the right of "More" should display the number of unread rooms.

I was lying, it should display the total number of notifications for the rooms in that section.

**Comment by lampholder** [comment]
Cool, in which case it sounds like this can be closed 😃
