### ISSUE TITLE
If you have multiple email addresses registered, there is only one checkbox for enabling email notifications

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3454]
### Description

I have multiple email addresses associated with my account, but under the Notifications section of the user settings, there is only one checkbox to enable email notifications, which seems to be associated with the last email address added.

### Steps to reproduce

- associate account with one email address
- enable email notifications for that email address
- add another email address
![image](https://cloud.githubusercontent.com/assets/1012976/24010396/1ab8172a-0a4e-11e7-96e5-1555dd3a0367.png)
(in this screenshot, the uhoreg.ca address was added first)
- there is now no way in the user settings to disable email notifications on the first email address added, since there is only one checkbox for enabling email notifications
![image](https://cloud.githubusercontent.com/assets/1012976/24010430/3f70a898-0a4e-11e7-9272-29a97b428308.png)

Describe how what happens differs from what you expected.

There should be two checkboxes -- one for each email address that is registered.

Log: not sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.7

**Comment by uhoreg** [comment]
It *looks* like per-email-address notification preferences already work, since I'm only getting notifications on one of my email addresses, so I *think* it's only a matter of tweaking the UI.

(But I have no problems with this issue being put on the backburner since my notifications just so happen to be set up the way that I want it to be.)

**Comment by lampholder** [comment]
@uhoreg interesting - do you mind my asking which email address is receiving the notifications?

@dbkr - do you know of any reason why we wouldn't send notifications to all of the email addresses (flinging this at you because I don't know exactly which bit of Riot/Matrix is responsible for generating these notifications)

**Comment by uhoreg** [comment]
@lampholder: my uhoreg.ca address is receiving notifications (the first address that I registered)

**Comment by Mikaela** [comment]
Is there any way to currently select which email address gets the notifications inside or outside Riot? 

I am currently receiving email notifications to Gmail while I would wish them to arrive to my Pushover email where I would see them faster in case I miss Riot Android notification.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/5496 (more thumbs)
