### ISSUE TITLE
[Feature Request] Marker for where you left off

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#3456]
With how active channels can be, when you come back to them you can very easily lose your place in the discussion. If we had a way (setting?) for the chat history to start where you left off where you last were in the channel, and a horizontal line, this would be quite helpful for catching back up on conversation.

Small feature, but something that can help if you're in charge of keeping up with a particular channel.

**Comment by israuor** [comment]
that feature would be nice in riot for android as well ;)

**Comment by lukebarnard1** [comment]
FTR this feature exists but is apparently broken.

**Comment by lukebarnard1** [comment]
Oh wait! 
>where you last were in the channel

Means that you left and then joined. I guess this is Non-Trivial due to missing history, which you might nto be able to get depending on the settings of the room I guess.

**Comment by israuor** [comment]
I don't thenk he's meaning leaving an joining.

**Comment by BloodyIron** [comment]
And/or close the page/app, but not leave the room.

**Comment by lukebarnard1** [comment]
Oh ok, then this does exist and it is broken. See https://github.com/vector-im/riot-web/issues/3456#issuecomment-287340232
