### ISSUE TITLE
Room topic sanitization in room directory is broken

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#3461]
### Description

Sanitization in the room directory seems to be incorrectly escaping room topics

### Steps to reproduce

![screenshot from 2017-03-18 12-11-15](https://cloud.githubusercontent.com/assets/238916/24069783/89cc8efa-0bd6-11e7-8b31-80224de7eda1.png)
![screenshot from 2017-03-18 12-10-59](https://cloud.githubusercontent.com/assets/238916/24069784/8a10f194-0bd6-11e7-96bc-b2b00593bb0d.png)

**Comment by lampholder** [comment]
Yuck.

**Comment by t3chguy** [comment]
not easy to fix with the way its currently written, whereas #5568 is nice'n'ez

**Comment by t3chguy** [comment]
Issue is actually worse than it looks, it can eat bits in angle brackets:

![image](https://user-images.githubusercontent.com/2403652/32990471-bf076c86-cd21-11e7-89d8-fe80850abc0b.png)
![image](https://user-images.githubusercontent.com/2403652/32990473-c9c70d52-cd21-11e7-935e-36b07f756f89.png)

**Comment by aaronraimist** [comment]
Seems to be fixed
<img width="722" src="https://user-images.githubusercontent.com/5855073/76478691-7fb66600-63d7-11ea-9dc2-5859c522078a.png">
