### ISSUE TITLE
rejecting invites from appservice rooms isn't reflected in /sync responses

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3462]
i have 30 stuck invites i can't reject from oftc channel invite spam

**Comment by ara4n** [comment]
this is a regression.

**Comment by Kegsay** [comment]
Does it work if you make a new incognito tab and log in with your account?

**Comment by dbkr** [comment]
I can't repro this locally, trying on matrix.org

**Comment by dbkr** [comment]
No luck reproing this. Are you still unable to reject the invites?

**Comment by dbkr** [comment]
Right, I think this is actually the UI just not updating to remove the room from the left hand list. Theory: the list is updated when the leave call returns rather than when our membership of the room changes

**Comment by richvdh** [comment]
The symptoms of this were:
* further attempts to reject would result in 'Room does not exist'
* clearing the client cache would make the invite disappear

https://github.com/matrix-org/synapse/pull/2056 fixes it for synapse 0.20.

**Comment by madduck** [comment]
Clearing the client cache on Android has no effect, i.e. the invite still can't be rejected. I don't know how to clear the client cache for `riot.im` in Chromium, other than force-reload…?

**Comment by Kegsay** [comment]
If you are using `/develop` there is a reset cache button in user settings. If you're using `/app` then force-refresh should be enough.

**Comment by madduck** [comment]
Okay, found it, all the way at the bottom (using `/develop`). Unfortunately, this has no effect and the invites still can't be rejected.

**Comment by richvdh** [comment]
FTR, @madduck 's issue was investigated and resolved at https://github.com/matrix-org/synapse/issues/1987
