### ISSUE TITLE
collapse display name changes

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3463]
when a user changes their display name multiple times in a row, each change is displayed separately.  It would be nice if they were all collapsed into one line.

**Comment by lampholder** [comment]
Agreed; this would be nice.

**Comment by uhoreg** [comment]
Also collapse avatar changes in with display name changes.

**Comment by ara4n** [comment]
https://matrix.org/_matrix/media/v1/download/matrix.org/FYZGIOmtEOXDtJWXqqicoNdE :(

**Comment by ara4n** [comment]
f1x0r3d
