### ISSUE TITLE
Video call fails silently when unverified devices are present in an encrypted chat

### ISSUE THREAD

**Issue by ianmcxa** [vector-im/riot-web#3464]
### Description

Attempting to initiate a video call in a chat with encryption enabled fails silently when the chat contains a user with an unverified but not blacklisted device.

### Steps to reproduce

- Create a chat with another user
- Sign in with an unverified devices
- Verify the other user's devices
- From your verified device, attempt to place a video call with the other user

Describe how what happens differs from what you expected.

The call appears to initiate. The "ringing" sound occurs, but the other person in the chat will not receive the call.

An error message should display similar to when a user attempts to send a message with an unverified device present.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 52.0
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by ara4n** [comment]
this should be fixed in 0.9.8 (released to /app a few days ago).  Thanks for the bug report!
