### ISSUE TITLE
mouse-dragging to select over the RoomList doesn't show the highlight

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3468]
so you can't see what you've selected

**Comment by lampholder** [comment]
Are you trying to highlight room topics on the room directory page?

**Comment by ara4n** [comment]
neither :) RoomList is the name of the component that draws the left-hand panel in riot-web - i.e. the list of rooms you're in.

**Comment by lampholder** [comment]
@ara4n I'll grab you sometime tomorrow IRL to find out what you mean - the RoomList rooms are all obvs mouse-draggable and figuring out how to highlight the text without triggering mouse drag is a tedious game :P

**Comment by turt2live** [comment]
Fixed in the new room list (2020 edition)
