### ISSUE TITLE
Invites to mxid containing a '.' silently go missing ('.' in mxid possibly also breaks other things)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3469]
e.g. can't search for people (which is more likely https://github.com/vector-im/riot-web/issues/2930), and sent invites go silently missing.  see https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$14898846601633597DzwZZ:matrix.org

**Comment by lampholder** [comment]
Renaming to reflect the meat of this issue - as Matthew says the search is likely #2930.

This is likely only affecting a small number of users, but is very confusing for the ones it does affect.

**Comment by lampholder** [comment]
ericwayman
00:51
A friend of mine had to hit "Enter" to change his display name in the interface, when he couldn't find a save button in the account preferences. It might be nice to have a graphical save button.
Also, it seems that if you sign up with a display name that contains a "." character, the interface doesn't prevent you from using that name, but various functions don't work.
(For example, you can't search for people or send invitations)
(To be precise, you can actually "send" invitations, but they never reach the person addressed.)

**Comment by lampholder** [comment]
Tom will do some testing of things with ~mxid~ and displaynames with dots in them to see if this is a real thing.

**Comment by lampholder** [comment]
mxids and displaynames with dots in had no problems at all receiving invites, so I'm calling this closed.
