### ISSUE TITLE
RRs can jump backwards in time

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3472]
Rob has noticed this twice in the past few days - the read receipts suddenly, while not doing anything in riot web, jump backwards from their current position as if someone un-read stuff
it looks like it happens service-wide, not just in specific rooms

**Comment by lampholder** [comment]
This is certainly worrying, though the end user experience is 'not that bad' in the grand scheme of things.

**Comment by grahamperrin** [comment]
> … read receipt…

A green horizontal rule, yes? A rule/line that might disappear by narrowing, from both extents, to its centre?

**Comment by ara4n** [comment]
i've never seen a RR jump backwards.
