### ISSUE TITLE
Emotes are sent with an extraneous leading space

### ISSUE THREAD

**Issue by lieuwex** [vector-im/riot-web#3474]
Emotes are sent with an extra space at the begin of `content.body`, this is trimmed in riot (at least the web) so it isn't visible, in weechat you can clearly see it though.

**Comment by lieuwex** [comment]
I submitted a PR: https://github.com/matrix-org/matrix-react-sdk/pull/764

**Comment by ara4n** [comment]
merged - thanks!

**Comment by lieuwex** [comment]
Yay, thanks!
