### ISSUE TITLE
Support filtering joins/leaves

### ISSUE THREAD

**Issue by Chaos99** [vector-im/riot-web#3476]
With the IRC bridge we get a lot of leave/join meta messages in some channels, especially when mobile clients are constantly joining the IRC channel. It would be nice if there was an option to not display the leave/join messages, e.g. have a filter checkbox in the settings for the channel.

This is a copy of issue vector-im/riot-android#1038 in riot-android

**Comment by lampholder** [comment]
Modified the report to better link to the riot-android issue.

This would certainly be nice to have - setting P3 for now because I don't think we have any immediate plans to implement but would be a great feature.

**Comment by ara4n** [comment]
this is actually higher than p3, imo - even with MELS many powerusers want to just nuke joins/leaves for a room entirely. also, dup of https://github.com/vector-im/riot-web/issues/916 :)
