### ISSUE TITLE
give feedback quicker when assigning a room alias that already exists

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3477]
It's annoying not to be told before 'save settings' that the alias is already taken

**Comment by lampholder** [comment]
Agreed, this is annoying.

Setting p3 because I don't think it's _that_ urgent to address. It shouldn't be particularly difficult either, though.

**Comment by anoadragon453** [comment]
Not sure if this is still relevant anymore as settings aren't saved on exit.
