### ISSUE TITLE
Re-pinged when navigating permalinks

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3480]
### Description

When navigating to a search result, or clicking on some other permalink, if the timeline has to load events and one of those events is a mention, the user is pinged again.

In my scenario, I was searching a room for something and went to a result from 7 days ago (long enough that Riot definitely had to load some events). Once loaded, it pinged me because my name was mentioned a few messages after the search result.

**Note**: When trying to reproduce this with the same event/room I was unable to get the audible notification to occur. I was able to reproduce it in other rooms, however. But not more than once per permalink.

### Steps to reproduce

- Be mentioned in a room a long time ago
- Navigate to a permalink near that ping
- Note the notification (assuming it is enabled)

I would have expected to not hear the audible ping so I don't go chasing rooms for where I was pinged.

Log: not sent (unable)    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Certainly glitchy, so worth looking at when we have some time.

**Comment by richvdh** [comment]
dup #2608 I think
