### ISSUE TITLE
Really long description in url preview.

### ISSUE THREAD

**Issue by NathanBeelen** [vector-im/riot-web#3481]
### Description

When sending a link in the chat, you'll get a preview for that page, this preview contains a description that is probably based on the `<meta property="og:description" content="">` tag or the `<meta property="twitter:description" content="">` tag. When the website misuses this tag and places the entire article in these tags, Riot also displays these whole articles in the chat. In my opinion this seems like bad behavior because it takes up a lot of unnecessary space in the chat.

### Steps to reproduce

You can reproduce this by posting a link to a page that has a long `og:description` or `twitter:description` tag in a chat. 

Expectations: A short description in the url preview.
Reality: A really long description in the url preview.

### Version information

- **Platform**: Desktop
- **OS**: Debian 9 (Stretch)
- **Version**: 0.9.7

**Comment by uhoreg** [comment]
Looks like the same issue as #2894.

**Comment by NathanBeelen** [comment]
Yes it is, I'm sorry I wasn't able to find it.

**Comment by lampholder** [comment]
Thanks for reporting; closing due to duplication.
