### ISSUE TITLE
RTE still uses '~~' for strikeout when Markdown is enabled, which CommonMark doesn't parse as strikeout

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3482]
as reported by ThatGeoGuy at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14900416982748036XTHXR:matrix.org

**Comment by lampholder** [comment]
Sorry to have left this one so long.

Does this mean if I highlight text in RTE, click 'strikeout' and click send, the raw text is sent as '~text~'? What are the consequences of its not being parsed by CommonMark?

Thanks :)

**Comment by uhoreg** [comment]
Yeah, when Markdown mode is enabled in the RTE, if you click on the strikeout button, e.g.
![image](https://cloud.githubusercontent.com/assets/1012976/24417388/3370c73c-13b6-11e7-9600-9210fcf191f4.png)
then it sends the text surrounded by `~~` instead of properly struck out
![image](https://cloud.githubusercontent.com/assets/1012976/24417415/4ac93f04-13b6-11e7-972c-d100aa5d8df7.png)

**Comment by lampholder** [comment]
Hmm, I can't find an issue for this, but it seems to have been fixed on /develop if I'm testing it correctly.

**Comment by uhoreg** [comment]
Seems to still be broken for me on /develop.  Do you have Markdown mode enabled in the RTE?

**Comment by uhoreg** [comment]
Added some labels.  Feel free to re-prioritize if p2 isn't correct.

**Comment by lukebarnard1** [comment]
This still happens when enabling MD

**Comment by turt2live** [comment]
The RTE lost strikethrough
