### ISSUE TITLE
Redacting a state event (name change, etc) should probably also show a 'black bar' redaction

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3483]
### Description

Event reference (and associated conversation that sparked this ticket): https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14900590252292Uhfhr:tang.ents.ca

Currently on riot-web develop, redactions appear as black bars (see below). I feel this should expand to state events, such as people changing their display name, instead of just removing them.

#### Example:
Before
![image](https://cloud.githubusercontent.com/assets/1190097/24128595/844e3816-0da2-11e7-8fca-36a18efeb751.png)

After (pardon the horrible graphics):
![image](https://cloud.githubusercontent.com/assets/1190097/24128606/9fbdba68-0da2-11e7-874f-45836b520470.png)

An alternative would be to just show `@453:tang.ents.ca changed their display name.`.

### Steps to reproduce

- Be a user
- Change your display name
- Redact your change display name event

I would have expected the event to remain in the timeline, but be redacted similar to messages, like the following:
![image](https://cloud.githubusercontent.com/assets/1190097/24128649/d951652c-0da2-11e7-9690-44ae54bc7939.png)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by richvdh** [comment]
dup #3214 I think
