### ISSUE TITLE
modernizr warns ff 52 can't run riot?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3486]
says @davidar

**Comment by lampholder** [comment]
52.0.1 on my xenial ubuntu machine seems to be fine (/app and /develop, private browsing session)
52.0.1 on my osx sierra mac wouldn't actually start 

Windows Firefox ate itself upgrading to 52.0.1, so that'll take longer to verify :\

**Comment by ara4n** [comment]
@davidar can you give us anything else to go on?

**Comment by ara4n** [comment]
no idea what was going on here. @davidar please yell if you can repro it.

**Comment by davidar** [comment]
Sorry, I can't reproduce it now either, not sure what was going on that day. My localStorage was full at the time, perhaps that had something to do with it?

**Comment by ara4n** [comment]
yeah, that'll prolly explain it

-- 
Matthew Hodgson
Matrix.org
