### ISSUE TITLE
spell out that riot-desktop requires Win7 or later; Vista and XP are not supported.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3493]
Don't fail with ugly GetCurrentProcessExplicitAppUserModelID not found in SHELL32.DLL symbol error on launch

**Comment by lampholder** [comment]
This looks unpolished, but could we fix it with documentation - just update https://riot.im/desktop.html to say it only works on Win7 +

**Comment by ara4n** [comment]
updated.
