### ISSUE TITLE
optional paranoia mode to force TURN

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3499]
stops IPs being leaked, and could be useful for testing TURN too

**Comment by lampholder** [comment]
TURN is very hard to test at the moment, so I would appreciate this.

**Comment by ara4n** [comment]
We may actually want to optionally select this on a call by call basis - e.g. if i know my correspondent is on the same LAN, i may be happier talking direct and sharing IPs, whereas if my correspondent is some random on the internet i may be happier to explicitly route via my TURN server.

**Comment by ara4n** [comment]
sorted by @t3chguy - thanks!
