### ISSUE TITLE
Accepting an invite as a guest fails over federation

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3505]
1. Create a room on an account on a non-matrix.org HS
 1. Invite an email address that isn't associated with a matrix account
 1. Click on the link in the email in a different browsing session, it should go to riot.im/app and be using matrix.org
 1. Click the button to accept the invite and the button to set a display name

Error appears saying, "Failed to join the room", "This room is private or inaccessible to guests. You may be able to join if you register."

The 3pid invite appears as accepted on the inviter's client (it gets converted to a real matrix user ID that's been invited) but the user doesn't join.

The invite remains in the sidebar on the inviters client but the same error appears if you try to join it.

**Comment by dbkr** [comment]
Actually, this is much worse and is a general problem with invites over federation.

**Comment by dbkr** [comment]
Deprioritising: guest access + federation is a bit WIP. Created https://github.com/matrix-org/synapse/issues/2065 to track upstream.

**Comment by croulibri** [comment]
I confirm the bug, exactly as indicated in the first post (steps 1. to 4.).

After setting the name, error appears saying `CORS request rejected: https://vector.im/_matrix/identity/api/v1/sign-ed25519?token=YJUWgnXXXXXXXXXXXXXXXXXXXXXXXXXXTdXTRvVQZZCJqxZHhcWbFiqssTVIacanHJHNpqfXXXXXXXXXXXXXXXXXXXXXXXXXXvIMYRbAd&private_key=rqzW138G5LihuyRpv_XXXXXXXXXXXXXXXXXXXXXXJqqA&mxid=%4111111111%3Amatrix.org`
(I have changed token by XXXX and number by 1111)

Crou²

**Comment by ara4n** [comment]
guests are basically dead now.
