### ISSUE TITLE
Message width wrap different when menu button for message is visible.

### ISSUE THREAD

**Issue by Torxed** [vector-im/riot-web#3507]
When hovering over a message, it wraps differently when not hovering over it.
Strange part is that when hovering over a message - more of it become visible on one line.

See video down below for a better description.

- **Browser**: Chrome
- **OS**: Arch Linux
- **Version**: 9.7

https://youtu.be/5oU0vtVbIvo

**Comment by lampholder** [comment]
Thanks for submitting the video :)

This looks glitchy - shouldn't be too difficult a fix.

**Comment by dbkr** [comment]
It looks like this has been fixed now
