### ISSUE TITLE
12 hour format option

### ISSUE THREAD

**Issue by alallier** [vector-im/riot-web#3509]
### Description

It would be nice to have a 12 hour format option across all of riot for us 'Mericans.

**Comment by ara4n** [comment]
agreed :) dup https://github.com/vector-im/riot-web/issues/1728 tho.

**Comment by alallier** [comment]
Sorry about that, didn't see it in the issue cue. I was searching 12 hour, and hour and the whole word hour doesn't exist in #1728.
