### ISSUE TITLE
Person who redacts a message has their read receipt disappear alongside the message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3511]
### Description

When someone redacts their message, their read receipt also disappears with it (if their read receipt was associated with it, such is the case if that was their most recent message).

### Steps to reproduce

- Send a message (note that this now becomes your most recently read message)
- On another account, double check the read receipt is there
- Redact the message
- Note that the read receipt for the sender disappears

I would have expected their read receipt still stays linked to the message, as is the case with everyone else who has read up to that message.

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/24310956/962ddd00-1097-11e7-89bb-a64fa1db3550.png)

Above is a demonstration of the 'unexpected' behaviour: @Mikaela sent a message and Voyager (the blue airplane) saw it. Later on they redacted the message, but didn't send a later one until after my message 'sneaky'. Mikaela's avatar should have been next to the redacted message until they sent another message/read my message (at least).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This actually appears to be the person who performed the redaction has their RR disappear, not the person who sent the message. Was just a coincidence at the time of reporting. 

Long shot guess of mine would be something to do with Riot unable to find the event after redacting and freaks out about sending the RR.

Title updated.

**Comment by turt2live** [comment]
RR disappears even if their most recent read message is not the one redacted:

* <someone> Hello world
* <someone else> Hello indeed
* *<someone> redacts hello world*
* *RR disappears from hello indeed*

**Comment by t3chguy** [comment]
I guess their RR is now pointing at their `m.room.redaction` event because of js-sdk's implicit RR calculations; I'll look into this

**Comment by t3chguy** [comment]
I was right :D
js-sdk needs to ignore `m.room.redaction` when synthesising RRs

**Comment by turt2live** [comment]
This seems to have gotten fixed (tested by sending a message on another account and redacting the message immediately after)
