### ISSUE TITLE
Depend on current Emojione set

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#3513]
If there's no specific reason to stick to 2.2.3, please move on to 2.2.4 (current release according to Emojione home page), or even to 2.2.7 (current Github master).

**Comment by ara4n** [comment]
have bumped it to ^2.2.7 in 546e2ab, although it's worth noting that we depended on ^2.2.3 previously... which in practice means "whatever the newest 2.x.x release, starting from 2.2.3".  This will flush out any older versions though.
