### ISSUE TITLE
room aliases with more than 2 domain parts aren't hyperlinked

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3514]

**Comment by JaniM** [comment]
This isn't quite about the amount of domain parts nor about tlds.

These work:
```
#xyz:abc.dex.com
#xyz:abc.dex.co
#xyz:abc.dex.st
```

These don't:
```
#xyz:abc.dex.dxkc
#xyz:chat.weho.st
#nebot:chat.weho.st
```

**Comment by turt2live** [comment]
Android seems to parse them okay. Not sure about ios. I'm suspecting this a web-only issue.

**Comment by ara4n** [comment]
they are fine on ios

**Comment by uhoreg** [comment]
see also #2756.  Not quite the same, but it may be worth looking at both bugs at the same time.
