### ISSUE TITLE
Make a way to choose the camera to use in the electron app

### ISSUE THREAD

**Issue by inducer** [vector-im/riot-web#3515]
### Description

I have multiple cameras attached to my laptop when I'm at the office (one built into the top of the screen, and one attached via USB). The electron app picks one (more or less) at random, which is often not what I want. It would be great if there was UI to select a different camera, like there is in most browsers.

### Version information

- **Platform**: Desktop
- **OS**: Linux

matrix-react-sdk version: 0.8.6
vector-web version: 0.9.7
olm version: 2.2.1

**Comment by uhoreg** [comment]
looks like a dup of #2822

**Comment by inducer** [comment]
Yep. Thanks for pointing me in the right direction. Sorry for the dup.
