### ISSUE TITLE
SMS for phone number verification is only working reliably in the UK.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3516]
Provisioning request for International routing is in progress.

This issue will be resolved once that provisioning has been completed and tested.

**Comment by ara4n** [comment]
related: #3542

**Comment by lampholder** [comment]
This should now be working globally with the exception of US and Canada (who need to be provisioned differently).

**Comment by lampholder** [comment]
We don't have a good way to test this, though, so it would be good to hear from anybody having problems (or achieving success) from a non-UK/US/Canada territory.

**Comment by lampholder** [comment]
Closing this; tracking at #3542
