### ISSUE TITLE
phone number listed as target for email notifications?

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3518]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14906247991873042FPIXh:matrix.org

**Comment by lampholder** [comment]
I can reproduce this.

I suspect it's possible to reproduce with a subset of these instructions, but I'll include everything I did here:
1. Start with a matrix login with an email address and a msisdn associated
1. Knife all the email addresses until you're just left with the msidsn - this sensibly kills the 'email notification' UI components in user settings
1. Add an email address again
1. Success - your settings tab will now contain the checkbox:
- [ ] Enable email notifications (447890123456)

**Comment by lampholder** [comment]
I have not verified where it is sending any email notifications it's trying to send...
