### ISSUE TITLE
notification options menu per chat doesn't open

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#3519]
if the user clicks the 3 little dots next to a room name, a menu should popup to change the notifications for that room. this does however not happen

**Comment by lampholder** [comment]
It works for me :)

Can you add any additional detail? What OS/browser version, and what time you were trying? And whether this was on /app or /develop?

Thanks for your help!

**Comment by PureTryOut** [comment]
OS is Gentoo Linux, on both desktop and laptop. I'm using the desktop version (Electron wrapper) so whatever Chromium version comes with that.
As for time, yesterday but it's still happening right now. It's on a self-compiled build in the develop branch, so `/develop`.

**Comment by ara4n** [comment]
i'd assume this is because your riot-web and matrix-react-sdk projects have got out of sync; you need to git pull on both.
