### ISSUE TITLE
Numbered list "problem"

### ISSUE THREAD

**Issue by JoeyGH** [vector-im/riot-web#3522]
Every time I start a line with a NUMBER and a DOT (like a numbered list), my line gets automatically transformed into a numbered list, starting with 1.

For example, if I type:

```
6. Riot
9. Vector
30. Matrix
```
_(hit Enter)_

It will get transformed/converted into:

```
1. Riot
2. Vector
3. Matrix
```

Now this might be a useful feature to some people, but I myself find it quite annoying. Is there a way to turn this off? If not, please add a way to turn it off somehow.

Cheers!

**Comment by lukebarnard1** [comment]
This is inherent to markdown engines in general, it's not Riot specific.

**Comment by dbkr** [comment]
Yeah, this is because the regular text editor uses markdown and markdown does this. Once the rich text editor becomes the default, markdown will no longer be the default.

**Comment by ara4n** [comment]
This has been improved by @VShell in https://github.com/matrix-org/matrix-react-sdk/pull/787 - the example problem is now rendered as:

```
6. Riot
7. Vector
8. Matrix
```

However, the proper solution is still to run away from MD for this.
