### ISSUE TITLE
'Type to search' label on country selector in login page is very unintuitive

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3524]
It appears to be an entry in the dropdown, not a UX hint for the search box itself.  Need to come up with better UX.

**Comment by lampholder** [comment]
This is confusing.

Also, if you start typing a multi-word country name that doesn't match what it expects (unlikely example: "Democratic People's Republic of North Korea") it just stops searching after the first space.

I have some ideas on what this might look like which I'll put together if I have time.

**Comment by lampholder** [comment]
This is blocked on design work.

**Comment by lampholder** [comment]
We want to:
- replace the round flags with full flags
- make searching for country simpler (Tom to find a design)
- make choice of login mechanism specific with a dropdown

**Comment by lampholder** [comment]
https://baymard.com/labs/country-selector looks good - exists as a jQuery plugin (not sure how suitable that is to include) https://github.com/JamieAppleseed/selectToAutocomplete

**Comment by lampholder** [comment]
Some mockups of what login might look like (not yet reviewed by anybody).

Points that aren't obvious from the mockup:
- The default should be the most common (probably email)
- The login button doesn't move (no bouncing up and down as we choose different login mechanisms)
- We can default country to one established by IP
- You can't type in your country code, only your country (power users--, consistency++)


- Login with msisdn:
![login_with_msisdn](https://cloud.githubusercontent.com/assets/1922197/24864469/30a921fc-1dfc-11e7-95d1-76f619da1402.png)
- Login with email:
![login_with_email](https://cloud.githubusercontent.com/assets/1922197/24864466/309bc778-1dfc-11e7-8888-dd5c56c60194.png)
- Login with matrix id
![login_with_matrix_id_1](https://cloud.githubusercontent.com/assets/1922197/24864467/309c231c-1dfc-11e7-9f22-6821dc3875f5.png)
- Alternative login with matrix id (depends how much we want to train users to start identifiers with '@'):
![login_with_matrix_id_2](https://cloud.githubusercontent.com/assets/1922197/24864468/309dd702-1dfc-11e7-9494-b42c6a7f7428.png)

**Comment by AmandineLP** [comment]
Looks good overall!
* Can the country field be a drop down which auto-filters when typing so that one doesn't have to type the country name fully?
* For the matrix ID, can we do sthg like the below, where the servername is an editable text field but pre-populated with matrix.org? That would allow people to just enter their username for expedience and make the server bit of the ID more transparent. 

![image](https://cloud.githubusercontent.com/assets/8582858/24865773/30ae6e7e-1e00-11e7-8f57-2e86b173ef7f.png)

**Comment by lampholder** [comment]
I'm picturing the country picker working like this: https://baymard.com/labs/country-selector - what do you think?

And yes, `username : server` is a good idea - I forgot that there was a sensible default that would work for most people :P

**Comment by ara4n** [comment]
The domain of the matrix ID cannot be changed, as it's determined by the URL of the HS that you're logging into (intuiting that URL from the mxid is a whole 'nother problem which I suggest we punt for now).  So i'd suggest just having a textfield with :matrix.org at the end.  Variable length could be cute, and I think we might get that for free if you use my custom input box control which wraps a contenteditable div.

**Comment by lampholder** [comment]
Looks like we're all broadly happy with the design. 

The UX also addresses the "sign in page asks me for email and phone number" issue #3526

**Comment by lukebarnard1** [comment]
Actually, thinking about the username input, it's entirely possible that users will want to login with the localpart of there mxid. So we can't really enforce the '@' prefix without complicating things.
