### ISSUE TITLE
MSISDN login isn't working for me.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3525]
I can't log in with my MSISDN, despite it being associated as a 3PID to my account.  (Is this not just that it's missing from my HS list of 3PIDs, and is only on the IS?)

**Comment by lampholder** [comment]
Assigning this as a P1 critical bug until we know better the impact.

@dbkr - can you take a look at this and add your thoughts?

/me assigns to @dbkr too - let me know if you prefer assignment or mentions for things like this :)

**Comment by lampholder** [comment]
This is potentially a candidate for release-blocker, too, so I'm adding that now just in case :)

**Comment by ara4n** [comment]
i am a total !@*£ing crank - apparently i was systematically entering the wrong password, presumably because the user->password mapping in my brain was keyed off the wrong password :(
