### ISSUE TITLE
People's section constantly reorders

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#3529]
### Description

The rooms in the people's section reshuffles constantly

![peek 2017-03-28 15-01](https://cloud.githubusercontent.com/assets/8428120/24409445/20c7eab8-13c8-11e7-835d-aa0ad1645b75.gif)

### Version information

matrix-react-sdk version: 91d10646b5d8314c5a7c15261f59cc230cafc1d5
riot-web version: 8b50ed800618-react-91d10646b5d8-js-f52e198b17f8
olm version: 2.2.1

- **Browser**: Chrome 57
- **OS**:  Ubuntu
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I've labelled this MAJOR because even though it's still usable, it's incredibly annoying.

**Comment by erikjohnston** [comment]
Looks like this is due to the fact that there were a few old rooms whose last events were redacted. There was a recent change to make them appear in the timeline, which caused the sorting algorithm to attempt to order based on their timestamps.

However, there was a previous bug in the JS SDK that caused timestamps of redacted events to be stripped, and so `getTs()` returned `undefined` for those events since they had been cached in indexdb.

https://github.com/vector-im/riot-web/blob/develop/src/components/structures/RoomSubList.js#L156 should probably check that `getTs()` doesn't return `undefined` before blindly returning it
