### ISSUE TITLE
underscores in URLs are interpreted as markdown

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3534]
Not sure how practical it is to fix this, but `http://example.com/_foo_` is turned into `http://example.com/<em>path</em>`

**Comment by dbkr** [comment]
https://talk.commonmark.org/t/markup-collision-with-underscores-in-link-texts/1016

**Comment by lampholder** [comment]
This would be a great one to fix.

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/4674
