### ISSUE TITLE
MSISDN registration should warn/error for unsupported countries

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3542]
I just had a minor disaster in an important demo where the folks trying Riot all tried to sign-up with phone numbers in Hong Kong.  Unsurprisingly, the 2FA SMS didn't work.  We shouldn't just silently fail :(

**Comment by lampholder** [comment]
:(

Amandine has already raised this. I _think_ making it work is actually an easy fix, esp. outside of the US/Canada (probably easier than modifying the clients with caveat text) - we just need to set the originator.

**Comment by lampholder** [comment]
@dbkr hardcoded the originator, which should make this work properly for global SMS with the exception of the US and Canada. US and Canada are currently expected in ~a week.

**Comment by lampholder** [comment]
If we are releasing /develop before US/Canada goes live we should put a warning on the sign up and settings pages. I don't know what we should do about the mobile apps - a multi-day lead time on releasing to the various app stores makes managing this a challenge.

IIRC the apps downgrade gracefully if the server doesn't support msisdn sign up - @ara4n might we consider disabling it in the matrix.org server until we've verified SMS sending is working globally (hopefully a week away)?

**Comment by ara4n** [comment]
i wouldn't object too much to hiding it until the OM side is sorted properly.

**Comment by lampholder** [comment]
I've changed my mind again :) Because we can't get a warning notice in front of iPhone/Android users until a release is pushed out, I think we should disable this in Synapse to stop new people from seeing the (possibly doomed to failure) option to register with their msisdn.

**Comment by dbkr** [comment]
Blocked on https://github.com/matrix-org/synapse/pull/2147

**Comment by dbkr** [comment]
Synapse PR now merged, we should probably wait for deploy / release

**Comment by ara4n** [comment]
bleurgh:
> Shaltay joined
Hi
How can I add my phome number from Russia? I did it before without any problems, now it says "not supported

**Comment by lampholder** [comment]
We commented our Russia, so it now _will_ try and send SMS there.

**Comment by ara4n** [comment]
this all happened; and russia got special cased.
