### ISSUE TITLE
emoji in room topic not using emojione in room header

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3548]
### Description

When the room topic has emoji characters, they are displayed as plain text rather than converted to emojione images.

### Steps to reproduce

- set the room topic to some text that includes emoji characters
![image](https://cloud.githubusercontent.com/assets/1012976/24552518/c726bbcc-15f4-11e7-82fb-0a415556e9ea.png)
- see that the emoji are displayed as plain text in the room header
![image](https://cloud.githubusercontent.com/assets/1012976/24552702/81a48cb8-15f5-11e7-9eef-ec7498413a46.png)

Describe how what happens differs from what you expected.

The topic displayed in the room header should use the emojione images for the emoji characters.

Log: not sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.7

**Comment by lampholder** [comment]
This works fine on web/android/ios so it looks like a desktop-specific problem.

**Comment by uhoreg** [comment]
It doesn't work for me on web under Chrome (haven't tried FF yet) -- I still get the same plain-text-looking emoji instead of the pretty colourful one.  I tried both /app and /develop.  If you're seeing the colourful emoji, maybe your OS is doing the replacement?

**Comment by turt2live** [comment]
Chrome uses very similar icons to those of emojione. Here's what I see, using the same icons:
![image](https://cloud.githubusercontent.com/assets/1190097/24809354/71bf7196-1b7c-11e7-8829-139cdd38d049.png)
![image](https://cloud.githubusercontent.com/assets/1190097/24809360/795e5d68-1b7c-11e7-830d-91d24c3bdaef.png)

Other icons are a lot more obvious:
![image](https://cloud.githubusercontent.com/assets/1190097/24809385/91fd9ee2-1b7c-11e7-8061-935d85ef5134.png)
![image](https://cloud.githubusercontent.com/assets/1190097/24809391/9702dc22-1b7c-11e7-848d-3bc2e38ae27b.png)

Tested with riot.im/develop on Chrome 56, Windows 10.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/1170
