### ISSUE TITLE
Messages through the OpenMarket SMS gateway don't make it through after the first one

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#3552]
**UPDATE: The missing messages ended up arriving about 30 minutes later.**

I sent a few messages to myself through the OpenMarket SMS gateway. I received the first one just fine (after responding with "ALLOW" to let it through) but the next three never made it to my phone.

Event ID of the message that went through successfully: `$14910761282898hdQuk:terracrypt.net`

Event IDs of the messages that didn't:

```
$14910781272914xfIwP:terracrypt.net
$14910781672915XXNek:terracrypt.net
$14910781992917MqIgZ:terracrypt.net
```

Not really a Riot issue, but Matthew said to put it here. :P

**Comment by lampholder** [comment]
I've labelled this a bug, since it's obviously not desirable, but in all likelihood is simply the result of the vagaries of SMS connectivity :S (there are lots of places en route and outside the span of Riot/OM's control that can hold up delivery of a message).

**Comment by turt2live** [comment]
@lampholder is there actually anything we can do about the gateway anymore?

**Comment by lampholder** [comment]
Nothing that represents a particularly good use of our time I think :\

This bug isn't adding any value being tracked here - time to close.
