### ISSUE TITLE
Panic button to restore UISI rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3553]
As discussed a few weeks ago with @richvdh, I really think that until we resolve all of #2996 we simply have no choice than to provide users with a panic button to reset the olm & megolm state for a room or participant.  Yes, it will make debugging #2996 slightly harder, but in practice anyone smart enough to be reporting coherent bugs on #2996 will also be smart enough not to mash the panic button before having done so.

In practice, this would be a contextual menu option or something on UISI messages saying "try to fix decryption" which would readvertise your device's existence to the users in the room, and perhaps reset your olm sessions with all the devices present in the room.

**Comment by richvdh** [comment]
Resetting the olm state won't help - the other user may continue to use the existing olm sessions. 

We can start a new megolm session, which might help if for some reason the original key-share message got lost. I don't think that happens very often, though. 

Probably the most useful things to do would be to force a refresh of the other user's device list, and to request that they refresh ours. That would at least fix the out-of-sync device lists.

**Comment by richvdh** [comment]
> Probably the most useful things to do would be to force a refresh of the other user's device list, and to request that they refresh ours. That would at least fix the out-of-sync device lists.

This isn't actually the case, because now the main cause of out-of-sync device lists is server-side, rather than client-side (https://github.com/matrix-org/synapse/issues/2165).

So it's still unclear on what a panic button would actually do. I'm reluctant to spend a lot of effort on code specifically for it.

**Comment by gavofyork** [comment]
any news on this?

our organisation (30+ people) is trying to use riot day-to-day and are now consistently having to spend 15 tedious minutes (or more) per day to sort riot out when it suddenly decides that all rooms/messages are in the state of: `Unable to decrypt: The sender's device has not sent us the keys for this message`.

it is extremely trying and the collective anger makes us want to switch to a system that actually work.

**Comment by mosesjohann** [comment]
In my case I can read and write message to my womans cellphone and I can't read them on Riot Desktop. She has the same problem too. 
I've just updated my server to actual matrix-synapse version and now I can read the messages (after waiting a few minutes). Seems that is has to do with that she changed her phone and the new one didn't get listed.

**Comment by ara4n** [comment]
the panic button got implemented.

**Comment by tymat** [comment]
Still getting this `** Unable to decrypt: The sender's device has not sent us the keys for this message. **`   and we're all up to date on the version.  

We've tried all sorts of things:

- Kicking the user and re-inviting him.
- Having him clear his cache and reload.
- Having him re-verify every members' devices.
- Having us re-verify his devices.

**Comment by turt2live** [comment]
@tymat The issue you're running into is almost certainly one of the cases listed on #2996. The best thing to do is to submit a bug report from both the sender and receiver side. 

The panic button described in this issue is due to be released very soon, but is currently undergoing testing.

**Comment by wey1288** [comment]
If happened suddenly anyone have an urgent message, or just want to have a
simple chat, no hesitate to call me directly any time +77071114646.

**Comment by richvdh** [comment]
(yes it got released:

![image](https://user-images.githubusercontent.com/1389908/43462644-8c088764-94ce-11e8-952e-930118a6c525.png)

**Comment by dkasak** [comment]
Oh, *that's* the panic button. That doesn't work due to vector-im/riot-web#6838. I was hoping there was something else that would allow me to fix my rooms.
