### ISSUE TITLE
Auto replace emoticon text with emoji

### ISSUE THREAD

**Issue by kethinov** [vector-im/riot-web#3556]
Desired feature: replace emoticon text with emoji in a manner similar to Hangouts.

Examples:
- `:)` becomes 😀
- `:p` becomes 😛
- `-_-` becomes 😑
- etc

**Comment by 4nd3r** [comment]
#2567 :-(

**Comment by ara4n** [comment]
reopened #2567 as this keeps coming up, but going to close this as a dup. thanks @kethinov.
