### ISSUE TITLE
Inconsistent save mechanism for settings

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3567]
To persist changes on the user settings panel, I click 'X'

If I click 'X' on the room setting panel, I close it without saving my changes.

**Comment by mittalswastik** [comment]
@lampholder Instead could we not have a prompt to save settings incase any changes have been made and yet closing it without saving. It would also be a pretty standard way.

**Comment by ara4n** [comment]
this is basically a dup of https://github.com/vector-im/riot-web/issues/5476, or at least the 'direct manipulation' v. 'deferred manipulation' bit of the discussion.

**Comment by turt2live** [comment]
Fixed
