### ISSUE TITLE
Disable sending typing notifications

### ISSUE THREAD

**Issue by cryptix** [vector-im/riot-web#3568]
### Description

Disable sending typing notifications to a room.

### Steps to reproduce

Lot's of reasons why this might be a problem for users.
Some people don't want to bother others by the start>stop cycles when re-writing messages.

### Version information

all / soon? :)

(i hope this isn't a duplicate but search didn't turn up much for me)

**Comment by uhoreg** [comment]
dup of #3220

**Comment by cryptix** [comment]
sigh.. guessed so. thanks, will track that one.
