### ISSUE TITLE
Ability to quote specific messages

### ISSUE THREAD

**Issue by superdump** [vector-im/riot-web#3571]
Embed links to messages in chat as a better form of quoting, using markdown for quoting messages provides only the quoted text as context. One has to scroll back (and hope the message was in the room) to read discussion leading up to the message. It would be nice to be able to 'respond' to a specific message producing a nicely-formatted quote which doubles up as a link to the quoted message. One could then elaborate on this to hop into a thread/focused conversation view for easy navigation of a drawn out back and forth, even if it were to span multiple rooms! :grin:

**Comment by lampholder** [comment]
I like this idea; it's superficial similarities to threading would mean it would have to play nicely with any full threading implementation we had/planned to have.

Am I understanding the current quoting behaviour right - does it literally just reproduce the text of the original message, without even any association with the user who said it?

**Comment by ara4n** [comment]
I'm making this a generic "quote specific messages" bug.  The RTE has (or had) this - a context menu item on given messages called 'quote' which would copy that message into the editor... Rob's extension here to also hyperlink to the original would be lovely too.

This is easy and desirable imo; prioritising accordingly.

**Comment by ara4n** [comment]
Worth noting that telematrix somehow is doing this already:

<img width="384" alt="screen shot 2017-04-10 at 15 07 29" src="https://cloud.githubusercontent.com/assets/1294269/24865534/77dd27a0-1dff-11e7-86f5-e5f694450252.png">

**Comment by pravi** [comment]
Just to add, it should also mention the original poster in addition to linking to context, so they can come back and join the conversation immediately.

**Comment by Nostradamos** [comment]
Idea on how to do the ui:

https://i.imgur.com/oyklK7F.png

It's basically a @mention with some special rules for mentions stuff inside a blockquote.
What to consider UX wise, is that if we want to have a basic md quote where the first line is a @mention, then this looks a bit ugly in the raw markdown editor.

**Comment by ara4n** [comment]
we have quotes which work quite nicely now with matrix-org/matrix-react-sdk#1890
