### ISSUE TITLE
refreshing /develop shows brief(?) VoIP inbound call notifications which may flicker on & off as it resyncs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3572]

**Comment by lampholder** [comment]
I tried refreshing /develop in a room that had had some VoIP activity and nothing popped up for me - have you got any more context you can add to help reproduce?

**Comment by ara4n** [comment]
Have two clients; keep placing calls from A to B, hanging up, and then refreshing B.  Within about 5-10 attempts you'll find that B starts ringing during sync - and never shuts up even if you reject the call.

**Comment by jryans** [comment]
Keywords: incoming call on start
