### ISSUE TITLE
riot-web repo does not work with apt-cacher-ng

### ISSUE THREAD

**Issue by pravi** [vector-im/riot-web#3573]
### Description
I get this error when using apt-cacher-ng. It works without apt-cacher-ng and all debian repos work with apt-cacher-ng

```
Err:2 https://riot.im/packages/debian sid Release
  Received HTTP code 403 from proxy after CONNECT
```
### Steps to reproduce

- setup apt-cacher-ng
- configure it in /etc/apt/apt.conf.d
- try apt-get update

Describe how what happens differs from what you expected.

I should be able to install riot-web with apt-cacher-ng

**Comment by lampholder** [comment]
I have no idea what would be causing this, but I _can_ reproduce it reliably.

**Comment by pravi** [comment]
Now the error message is clear. After changing url to http from https, it is working with apt-cacher-ng.

```
  Invalid response from proxy: HTTP/1.0 403 CONNECT denied (ask the admin to allow HTTPS tunnels)
Reading package lists... Done
```
 So I think it is a proxy configuration issue and we can close this. @lampholder what do you think?

**Comment by pravi** [comment]
after adding
`
PassThroughPattern: riot\.im:443$`

in /etc/apt-cacher-ng/acng.conf I can connect to https as well. Closing this issue.

**Comment by thijstriemstra** [comment]
> in /etc/apt-cacher-ng/acng.conf I can connect to https as well.

Or you can simply allow CONNECT for every https host:

```
PassThroughPattern: .*
```
