### ISSUE TITLE
Use the right riot logo on the login page

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3577]
please? O:-)

**Comment by lukebarnard1** [comment]
Which one?...

**Comment by lampholder** [comment]
Dup of #3402?

#3402 _also_ doesn't know which the right logo is to use :P

**Comment by lampholder** [comment]
Arbitrarily closing #3402 and leaving this one as the one true issue about using the right logo on the login page.

@ara4n can you point us at the right logo?

**Comment by lukebarnard1** [comment]
Answer from Matthew:
```
vector-web/src/skins/vector/img/logos/riot-logo-$i.svg
```
where 1 <= $i <= 5

**Comment by ara4n** [comment]
luke did this - thanks :)
