### ISSUE TITLE
cannot reject a second invite to a room

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3580]
STR:
* receive invite to room
* reject it
* receive second invite to the *same* room
* when you open it, you get 'You are trying to access Empty room. Click to join the discussion'. There is no option to reject the invite.

**Comment by richvdh** [comment]
The room disappears from your room list so if you don't click "join" immediately, you lose the ability to join as well. Until you reload your client (and force a re-initial-sync).

**Comment by richvdh** [comment]
I have a feeling this may have been a client bug which got fixed. Can't check from here though

**Comment by turt2live** [comment]
@richvdh confirmed fixed

1. Invited myself to a DM
2. Rejected
3. Invited again
4. Rejected

No mention of an empty room or error rejecting said invite.

**Comment by richvdh** [comment]
Thanks!
