### ISSUE TITLE
Allow user to disconnect or close local account without removing keys

### ISSUE THREAD

**Issue by albuic** [vector-im/riot-web#3581]
### Description

UI should allow a user to disconnect or close the apps without removing keys (an option should be there added to allow removing local key)

### Version information

- **Browser**: locally encrypt in local storage.
- **Desktop/Phone apps**: locally encrypt

**Comment by lampholder** [comment]
It would be nice to have a way of achieving this, but how tractable is it?

What would we use to encrypt the keys in the local storage? What guarantees can be made about local storage?

**Comment by albuic** [comment]
Closing in favor of #3777
