### ISSUE TITLE
make redaction black lozenge optionally hidable

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3589]

**Comment by lampholder** [comment]
What would it look like instead? No message?

**Comment by t3chguy** [comment]
@lampholder I've seen people ask for this, its because they want the old behaviour which didn't show redactions. Someone gave an example of using a Matrix room as a todo list.

**Comment by turt2live** [comment]
There's also a couple people who use https://github.com/turt2live/matrix-email-bot for mailing lists, and by nature of email, receive spam in the room or excess parts to messages. They seem to prefer the 'like it never happened' approach before the change when redacting the spam/excess bits of email.

**Comment by lampholder** [comment]
It sounds like this could satisfactorily be implemented with a room-level option to choose how redacted messages are displayed (or otherwise). What options would we want to support? Is it as simple as visible/invisible?

**Comment by t3chguy** [comment]
going to implement this as an account level thing for now (SyncedSetting) and it will be dragged onto Granular Settings once they are implemented. At least this way it can restore the old behaviour if someone so wishes.

**Comment by turt2live** [comment]
This seems to be resolved?

**Comment by t3chguy** [comment]
in a broken manner, but yes
