### ISSUE TITLE
Ability to forward attachments/files between rooms without downloading

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3592]
Related to #2597 - it would be very nice to be able to fwd files to other users/rooms without first downloading them.

**Comment by t3chguy** [comment]
In regards to the UX of this, I propose a search box, similar to that contained in "Start a new chat" but autocompleting to rooms you are in. This I believe is the fastest (and simplest) input method on a device such as a laptop or desktop. Personally I'd prefer that over having to scroll through my Room List to click it, though that might be more attractive. Typing a couple of characters (for autocomplete) then maybe up/down arrow keys and ENTER.

Any and all comments appreciated

**Comment by lampholder** [comment]
Can't you just copy+pasta the link to the file? Or does that fall foul of some permissions/access thing?

@t3chguy are you suggesting a search box to search files, or to search destinations for the file?

**Comment by turt2live** [comment]
@lampholder copy/pasting the url isn't as helpful as uploading the attachment to the room again. For the parties on the receiving end, it's potentially an extra unwanted step. Additionally, not many people are aware of the ability to right click to get a URL.

**Comment by t3chguy** [comment]
@lampholder I'm suggesting a forward button in the `…` menu of a message which brings up a dialog. The dialog allowing you to search for a destination to forward the message to

**Comment by lampholder** [comment]
Thanks all - I agree that copy+paste isn't optimal (though I'd be surprised if not many people really were aware that you can generally right click links to get URLs on the web).

I think a forward button in the `...` menu might be the way to go about this; this would additionally benefit from being trivially compatible with the file list (which could just include the same option and launch the same modal dialogue).

It might be nice to address this via a more general 'share...' option that lets you forward to another riot user/room, send to dropbox, get a sharable link etc.

**Comment by t3chguy** [comment]
Hmm, with @ara4n's quick-search room thing maybe incorporating that would be the way to go. Could make use of that to select where to forward to

**Comment by t3chguy** [comment]
done by #3688
