### ISSUE TITLE
Opening a user's profile leaves Riot unresponsive for a while

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3595]
### Description

When opening the right sidebar for a user, Riot appears to be trying to pull the device list for the user. As it does so, the entire UI becomes increasingly unusable until it loads the devices. Closing the sidebar while the UI is responsive does not prevent the issues to come. The UI ends up being unusable (for me) for up to 2-3 minutes, making it really hard to start a chat with someone easily.

After it downloads the keys for the devices, the UI doesn't lock up for browsing other user profiles. It does eventually come back though, usually around the time I end up wanting to use the sidebar for something.

### Steps to reproduce

- Open right sidebar for a user
- Watch the UI descend into a bad day

Log: sent ('Unable to open right sidebar...')    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Hey @turt2live this sounds very annoying, but I was unable to reproduce it (either using matrix.org or federated) - in fact opening the memberinfo panel is super snappy for me :)

Is this still happening reliably for you? Is it happening for all users, or just some with a particular characteristic?

**Comment by turt2live** [comment]
@lampholder As mentioned in the ticket, it is somewhat intermittent. I was experiencing it a couple minutes ago, but now can't reproduce it. 

I'll try to remember to get a CPU profile before opening the pane - maybe it'll reveal something.

**Comment by lampholder** [comment]
Also could well be related to this: https://github.com/vector-im/riot-web/issues/3310

**Comment by ara4n** [comment]
it's almost certainly a dup of #3310.
