### ISSUE TITLE
Implement a mechanism for Riot to generate and cache a user password

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3600]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta/issues/59

We want to improve the experience for users landing as guest by giving them full access to Riot after they've picked a username and successfully completed a (accessible, privacy-concern-sensitive) CAPTCHA.

As part of this, completing registration with a password would be completed at a later stage, so Matrix/Riot need to support the user's existing/operating without a password.

The scope of this task is to make sure this is possible (it might be that no work is required).

If work is required, the 'right way' to implement this is down to the implementor - it could be to modify Synapse/the DB schema, it could be for Riot to generate a throwaway password that is not exposed to the user (or something else entirely).

**Comment by lukebarnard1** [comment]
>If work is required, the 'right way' to implement this is down to the implementor 

I'm not sure this should hold true... I think we should discuss, design and implement collectively.

**Comment by tessgadwa** [comment]
Agree with Luke.

**Comment by lampholder** [comment]
Okay :)

A summary of discussion so far - we are wedded to the idea of users being able to have full access without having to provide a password, so we would like to implement this by:
- Riot generating a password for the user and caching it locally (thereby not requiring any changes to the server impl to support passwordless users)
- Riot prompting the user to provide a password (using whatever combination of encouraging wording and UI works most effectively)

**Comment by lampholder** [comment]
So that would likely change the scope of this task to - **implement a mechanism for Riot to generate and cache a user password**, and it can come later in the sequence.

**Comment by lukebarnard1** [comment]
Ah, well let's change the title to that then :)

**Comment by lukebarnard1** [comment]
The generation is simple:
```js

generateRandomPassword() {
    // Returns something like "yigddhuo6ucrbeyvh35v78pvi",
    // but not always of the same length
    return Math.random().toString(36).slice(2);
}
```

As to _when_ we do this, and where this fits in with existing code, I'm not sure. It could easily go into the dialog to choose a mxid/do a capcha before it calls through to hit an InteractiveAuth of some flavour. This needs a bit more thought.

**Comment by lukebarnard1** [comment]
Done in the initial implementation of mxid dialog https://github.com/matrix-org/matrix-react-sdk/issues/849
