### ISSUE TITLE
Nag-bar and dialog for Passwordless Users to provide password

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3602]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta#59

Users who have provided a username and completed a CAPTCHA should be prompted to complete their registration to avoid losing access to said username.

This should use the existing 'You are Rioting as a guest' top notification bar, and should include a link to the mechanism to complete registration.

**Comment by lampholder** [comment]
@ara4n @AmandineLP we need some wording for the nag box.

We probably want to go for something like one of these four (steadily increasing in level of alarm):
1. Please [click here to complete registration](url) of your Riot account.
1. To log in on other devices, please complete registration by [setting a password](url) for this account.
1. To claim _@greatname:matrix.org_ [complete registration by setting a password](url).
1. Without completing registration you risk losing _@greatname:matrix.org_ forever! [Set your password now](url)!

**Comment by lampholder** [comment]
The current nag bar features links to log in or to register.

We might want to consider a button here instead since buttons are more actiony:
![nag](https://cloud.githubusercontent.com/assets/1922197/25395147/05042a8c-29d8-11e7-98cf-f11db16b984c.png)

**Comment by AmandineLP** [comment]
M & I suggest:

To be able to return to your account, you need to set a password.  [............]

**Comment by lampholder** [comment]
Is that the password field in the nag bar itself?

**Comment by lukebarnard1** [comment]
>Is that the password field in the nag bar itself?

Conclusion was that, no it's the "Set Password" button.

**Comment by lampholder** [comment]
The current registration password set UX has some issues:
- password criteria (minimum length == 6) is not written and has to be discovered by typing
- if there is _anything_ wrong with you password (too short or mismatched) it just wears a red border and shakes itself side to side
- the field names are only there as placeholder text (so they can be completely hidden by malfunctioning form auto-completes)

To move forward, I suggest we:
1. Implement a naive impl of the password by dropping the password set components from the registration page into here
1. Prioritise reworking our password set UX as a separate task.

Thoughts?

**Comment by lukebarnard1** [comment]
@lampholder this feels like the wrong place for that. This issue is for the nag bar and the new dialog for changing passwords.

**Comment by lukebarnard1** [comment]
^ Initial simple implementation of the dialog has now been merged.
