### ISSUE TITLE
Improve Landing as Guest: Provide mechanism to complete registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3603]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta#59

Once users have selected a username and completed the CAPTCHA they have full access to all of Riot. They should be able to complete registration by supplying a password.

**Comment by lukebarnard1** [comment]
Removing this as it's intrinsically linked to https://github.com/vector-im/riot-web/issues/3602
