### ISSUE TITLE
Make Synapse support username availability check

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3605]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta#59

I believe there are design decision reasons why this hasn't been implemented in the past. I'd like us to consider this because picking an available username is particularly tedious if checking availability isn't as painless as possible.

The scope of this task would be to deliver an API in Synapse that can be called to check username availability.

@ara4n - what are your thoughts on this existing?

**Comment by ara4n** [comment]
sounds great to me. i'd expect the auth stuff would give us an API we could already prod for this...

**Comment by lukebarnard1** [comment]
>i'd expect the auth stuff would give us an API we could already prod for this...

Not quite true. We'll have to write a simple API for Synapse that does a `SELECT` in whichever table stores user IDs.

**Comment by Half-Shot** [comment]
Could username be exchanged for any other field? If I wanted to see if a phone number was taken or something like that. Perhaps even allowing /avaliable to take multiple fields?

**Comment by erikjohnston** [comment]
To what extent do we want to stop people from being able to iterate over lists of mxids? We probably want to have quite aggressive ratelimiting on the endpoint at least.

**Comment by lukebarnard1** [comment]
Yep, it would be heavily rate limited, I forgot to mention that.
