### ISSUE TITLE
For Read-Only Users, redirect any attempt at an interactive action to the prompt to choose a username.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3608]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta#59

The user should be able to read the page unhindered, but any other action should trigger the username dialogue (https://github.com/vector-im/riot-web/issues/3604).

**Comment by lukebarnard1** [comment]
This is done in https://github.com/matrix-org/matrix-react-sdk/pull/849 but needs refinement.

- [ ] style tweaks for the InteractiveAuth in the dialog (capcha) and error message, which is currently black text.
- [ ] checking for mxid availability, which depends on #3605

**Comment by lampholder** [comment]
What does the UX look like for each of these if we replace the custom text with the [`To get started, please pick a username!` dialogue](https://cloud.githubusercontent.com/assets/1922197/26007765/d83e4eaa-3739-11e7-8422-ce306a35dd36.png) and:
 - if the intercepted action is joining a room, make them join (if they permissions allow)
 - if the intercepted action is anything else, dump them back on the read-only room view/room directory (wherever they started) and let them try to perform that action again

>"This room is private or inaccessible to guests. You may be able to join if you register.
If instead I see the generic pick-a-username popup, I will enter a username and click 'Continue', expecting to enter the room. If I can join I do and I'm happy. What happens if I can't?

>"Guest users can't upload files. Please register to upload.
I think I can only trigger this by dropping a file on the room window, which I think is a bug. Non-participating users shouldn't be able to drop files on rooms - this fails even if you're not a guest.

>"Guests can't set avatars. Please register.
Can an unregistered user access the UX to trigger this?

>"Guests can't use labs features. Please register.
Can an unregistered user access the UX to trigger this?

>"Guest users can't invite users. Please register.
Can an unregistered user access the UX to trigger this?

>"Saving room color settings is only available to registered users
Could clicking the room settings cog trigger the `pick a username` dialogue? Then you'd just be dumped back on the read-only room view after picking your username, and you could click it again.

>"This action cannot be performed by a guest user. Please register to be able to do this.
This is a very generic message - what action triggers this?

>"Guest users can't create new rooms. Please register to create room and start a chat.
I enter my username, am dumped back where I started and click again to create a new room. Seems fine to me.

**Comment by lukebarnard1** [comment]
>"This action cannot...

This is actually setting power levels

**Comment by lampholder** [comment]
Discussed IRL - decided we would bounce all actions (including clicking on user settings) to the mxid picker, without including any of the action-specific context for now.
