### ISSUE TITLE
Make the left panel look sensible for Read-Only Users

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3609]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta#59

Currently, the left panel shows text inviting the user to drag rooms around. This isn't very helpful for a user who only has read access to the room they're currently in.

**Comment by lukebarnard1** [comment]
This also applies for registered users FTR. I swear there was an issue for that...

What about this as a stand-in UI that replaces the 4 Drag Here boxes of the apocalypse?:
![2017-04-25-150417_216x187_scrot](https://cloud.githubusercontent.com/assets/6750344/25389491/b49027ea-29c8-11e7-9444-ebaa67dc7dcf.png)

So if there are no joined rooms, just show a message to encourage the user to start some chats/ join some rooms.

**Comment by lampholder** [comment]
This is so much more straightforward than the thing I was imagining. Lets do this.

For the record, I was thinking of some changes that could:
- include room/DM creation in the roomlist UX:
  ![image](https://cloud.githubusercontent.com/assets/1922197/25395635/9ac1fc9c-29d9-11e7-945b-3ecb6ae5861d.png)
- in the void left by our not yet having joined any rooms, put a little thingy to prompt people to use that UI to create a room/DM:
  ![image](https://cloud.githubusercontent.com/assets/1922197/25395661/b42ca272-29d9-11e7-81a8-f40196197fd1.png)
- replace all of the above with placeholder wigglies for read-only users:
  ![image](https://cloud.githubusercontent.com/assets/1922197/25395679/c3470478-29d9-11e7-8cd9-24d74b992bab.png)

**Comment by dbkr** [comment]
Reopening as this gone back into design

**Comment by dbkr** [comment]
New design:

![room-buttons2](https://cloud.githubusercontent.com/assets/986903/25495292/94f0903e-2b74-11e7-8502-f4bbb8e76a38.png)

**Comment by lampholder** [comment]
I have a couple of thoughts on the room wording:
- could we switch the order (so that you read what the leftmost button is about first)
- could we change 'browse the directory' to 'join an existing room' so that it more directly aligns with a new user's intentions

Such that it reads:
> You're not in any rooms yet!
> Click (≡) to join an existing room or (+) to make a new one.

@ara4n @AmandineLP - what are your thoughts?

**Comment by lampholder** [comment]
@dbkr am I right in thinking this is now blocked on:
 - [ ] design + CSS for the room list header buttons
 - [ ] CSS for the hint bubble speech triangles

**Comment by dbkr** [comment]
Yes, except s/CSS/SVG/ for chevrons, because the borders are dashed (or just make the borders solid).
