### ISSUE TITLE
Don't override Chrome's Ctrl+Shift+Pg{Up,Down} tab moving behavior

### ISSUE THREAD

**Issue by juliusv** [vector-im/riot-web#3614]
In Chrome on Linux, Ctrl+Shift+Pg{Up,Down} usually moves a browser tab to the left or right within the list of open tabs. However, Riot grabs this combination and instead scrolls the current chat window up or down - this is the same behavior as just pressing PgUp / PgDown (without Ctrl+Shift). If Ctrl+Shift are pressed, Riot should not act on PgUp / PgDown itself, to not break Chrome tab moving behavior.

**Comment by richvdh** [comment]
guess we're forgetting to check the modifiers.

related to https://github.com/vector-im/riot-web/issues/3232

**Comment by richvdh** [comment]
fixed via https://github.com/matrix-org/matrix-react-sdk/issues/825
