### ISSUE TITLE
login without captcha no longer works

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3621]

**Comment by turt2live** [comment]
Background: We're using a self-hosted Riot and Synapse. Synapse doesn't have captcha support.

What users see:
![image](https://cloud.githubusercontent.com/assets/1190097/24970362/3e54d79e-1f71-11e7-84f6-6e733ecf73f8.png)

Steps to reproduce the above screenshot:
* Try to register an account without an email or phone number

The 'Start authentication' text (which is a link, but doesn't look like a link) brings the user to a URL like so `https://tang.ents.ca/_matrix/client/r0/auth/m.login.dummy/fallback/web?session=SomeIdHere`

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-js-sdk/issues/420 - tested and appears fixed :)
