### ISSUE TITLE
Unsupported Browser Warnings - Remember Acceptance

### ISSUE THREAD

**Issue by p0087** [vector-im/riot-web#3624]
Riot Web under Edge (and presumably other unsupported browsers) prompt that "Sorry, your browser is not able to run Riot." with a red background *every single time* you use riot web. Clicking "I understand the risks and wish to continue" isn't remembered and has to be clicked on every visit to the page.

I'd expect the acceptance to persist.

Microsoft Edge
Windows 10
Riot 0.98 selfhosted

**Comment by lukebarnard1** [comment]
Sounds like we should be putting a flag in `localStorage`.

**Comment by p0087** [comment]
Unsure if you're taking bug reports for Edge as it's an unsupported browser, but I'll add that on receiving a message in edge, it doesn't autoscroll to the bottom of the convo

**Comment by lukebarnard1** [comment]
By definition Riot is unlikely to work well in unsupported browsers.

**Comment by ara4n** [comment]
@turt2live thanks!
