### ISSUE TITLE
in login screen, disable or hide phone number inputs when username input is non-empty

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3625]
When a user enters something in the username box in the login screen, the phone number inputs are unnecessary and get in the way (e.g. they need to be tabbed over).  IMHO it would be nice if the phone number inputs disappeared, or at least were disabled, if the user typed something in the username box.  If the user changes their mind and empties the username box, then the phone number inputs should reappear/be enabled.

**Comment by uhoreg** [comment]
Conversely, when a user enters something into the phone number box, then the username box should disappear/be disabled.

**Comment by lampholder** [comment]
This is approximately a duplicated of https://github.com/vector-im/riot-web/issues/3526 which we're in the process of fixing :P 

Actual UI mockups here: https://github.com/vector-im/riot-web/issues/3524
