### ISSUE TITLE
Presence status is confusing

### ISSUE THREAD

**Issue by allanday** [vector-im/riot-web#3626]
### Description

The labels that describe user presence are confusing. There have been multiple times when I have either misinterpreted them, or haven't been able to understand what they are saying.

Some example presence labels:

"Online now"
"Idle 14m ago"
"Offline 2h ago"

It is very hard to understand what the latter two examples mean. I have read a message like "Offline 2h ago" and interpreted it as meaning that the user is online now (since they were offline in the past, you can read it as implying that the user is now online).

A big part of the issue is that the labels refer to states as having happened at specific points in the past. People don't understand why Riot would know about a user's presence at one point in time and not another. This is compounded by the fact that these states are more like non-events - "idle" is the lack of activity.

If the presence isn't known, it might simply be better to be transparent about it:

"Online"
"Status unknown (active 14m ago)"
"Idle (active 3h ago)"
"Offline (active 2h ago)"

### Version information

Revolt on Fedora 25 (Flatpak build e5277854679b)

**Comment by turt2live** [comment]
Alternative verbage, that may fit in the limited space of the sidebar:
* Online
* Unknown  (*or simply 'Offline'*)
* Idle for 3h
* Offline for 3h

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/3417

Changing all presence messages to read 'for n units' instead of 'n units ago' is in my opinion a super easy way to make this a lot clearer :)

**Comment by ara4n** [comment]
+1 - thanks @turt2live!

**Comment by allanday** [comment]
Yes, thanks @turt2live !
