### ISSUE TITLE
Riot does not validate identity server

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3629]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=44115986)](https://www.bountysource.com/issues/44115986-riot-does-not-validate-identity-server?utm_source=44115986&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### Description

Identity servers aren't validated, and apparently are perfectly okay for Riot/Synapse. In our case, users get confused occasionally and enter our homeserver domain name as the homeserver and identity server, making it impossible to add emails/phone numbers in the future. 

### Steps to reproduce

- Create an account with an identity server that doesn't exist

I would have expected Riot to warn/error about the identity server not existing/being unavailable. 

Log: not sent

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop and tang.ents.ca (v0.9.8-3-g76f140c6-dirty)

**Comment by lampholder** [comment]
This is horrible :(

**Comment by ara4n** [comment]
it's horrible, but i'm not sure it's critical (by the definition that critical == bug which makes the whole app broken for all users).

**Comment by lampholder** [comment]
Agreed.

**Comment by turt2live** [comment]
Updated original post for the bounty :)

**Comment by turt2live** [comment]
Another $15 is being thrown in to get this fixed.

**Comment by turt2live** [comment]
Head's up that this is still an issue in 1.0.0: using the custom server option doesn't stop you from typing a nonsensical URL for the identity server.

The identity server is otherwise validated using .well-known.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3001 - it won't make it into 1.2.0, but should be in the next regularly scheduled release.

Will reallocate the $25 bounty to some other riot-web issue
