### ISSUE TITLE
Clicking buttons has lingering hover/click styles (/develop)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3630]
### Description

It appears as though https://github.com/vector-im/riot-web/commit/15accf33f59131752d49007ba92d18d0b3fa9721 fixed #3053, however added a somewhat undesirable side effect (anecdotal evidence - can't actually confirm this at the moment). More often than not clicking a room section ends up having some interesting styling. Invoking a click or keypress elsewhere causes the effect to dismiss itself.

### Steps to reproduce

- Click a room section to expand/collapse it

I would expect that the section header collapse/expand without having styles be 'stuck'.

Log: not sent    

Dark theme:
![image](https://cloud.githubusercontent.com/assets/1190097/25062739/76c4270e-218f-11e7-817e-0fed9f28f94e.png)

Light theme:
![image](https://cloud.githubusercontent.com/assets/1190097/25062741/86ea6e18-218f-11e7-8c92-e8d467256403.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Updated title - the effect applies to every button.

**Comment by ara4n** [comment]
this is a feature - trying to show focus on buttons less ugly than the big blue outlines. the misbehaviour on the light theme is now fixed.
