### ISSUE TITLE
Mistyped aliases (that are invalid) show up in the 'main address' dropdown, but otherwise disappear

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3631]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=44168310)](https://www.bountysource.com/issues/44168310-mistyped-aliases-that-are-invalid-show-up-in-the-main-address-dropdown-but-otherwise-disappear)

### Description

When mistyping an alias' domain and pressing enter, the alias magically disappears (which seems awkward - I would have expected it to stick around with a warning/error to let me know I'm doing something wrong). The alias ends up staying in the 'main address' options, however. Saving the room settings with the bad alias causes the 'Failed to save settings' dialog with an error about the alias needing to be local.

### Steps to reproduce

- Open the room settings
- Add a room alias with a bad domain (`matrix.orrrrrrrrg` for example)

A couple things would be expected, I believe:
* The 'bad' alias would remain on the page, with a warning/error indicator
* If it is supposed to disappear, then it shouldn't end up in the main address options or try and be saved

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/25062775/c8d6401c-2190-11e7-9478-85f447553757.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This should also probably just auto-append the homeserver if one isn't supplied, to feel more local to the server.

**Comment by turt2live** [comment]
Updated OP to advertise the bounty on this :)

**Comment by t3chguy** [comment]
this could also be fixed if only the localpart is allowed as input and the glyph and server_name bound, as is actually the case

**Comment by t3chguy** [comment]
Related to https://github.com/vector-im/riot-web/issues/664

**Comment by ara4n** [comment]
fixed these days.
