### ISSUE TITLE
permalinks are broken on desktop

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3643]
clicking a link to a message on the electron app now does nothing

**Comment by ara4n** [comment]
@dbkr i can't repro this - e.g. I posted https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$14928980761270360Ossru:matrix.org to myself on riot/desktop 0.9.8 and clicked on it and it did the right thing.

**Comment by dbkr** [comment]
oh, it was a riot.im/develop permalink: https://riot.im/develop/#/!cURbafjkfsMDVwdRDQ:matrix.org/$14928980761270360Ossru:matrix.org (which is somehow ending up as a link to /Applications...

**Comment by dbkr** [comment]
This was fixed by https://github.com/matrix-org/matrix-react-sdk/commit/5de71ef504f01c016be02940030de967af8dd84d which was after we cut the 0.9.8 release.
