### ISSUE TITLE
Getting :focus on some AccessibleButtons looks odd

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3650]
CountyDropdown:
![2017-04-18-170713_349x128_scrot](https://cloud.githubusercontent.com/assets/6750344/25140858/8d16a7b2-2459-11e7-8868-0bb10e589837.png)

RoomList ellipsis
![2017-04-18-170925_226x22_scrot](https://cloud.githubusercontent.com/assets/6750344/25140922/cde3ef66-2459-11e7-8e2a-1535f329521f.png)

Buttons in general
![2017-04-18-170818_39x37_scrot](https://cloud.githubusercontent.com/assets/6750344/25140923/cde4d610-2459-11e7-9895-c0d6fb8f3190.png)

RoomList header
![2017-04-18-170810_225x33_scrot](https://cloud.githubusercontent.com/assets/6750344/25140924/cde5da42-2459-11e7-9a06-9a55b72452ad.png)

(On Chromium 53 on Ubuntu 14)

**Comment by ara4n** [comment]
This shouldn't remotely look like this.  Can you try on current Chrome (57)?

**Comment by lukebarnard1** [comment]
Yep, can do

**Comment by ara4n** [comment]
oh, hang on, i just reproduced it. looks like i might have only tested this on the dark theme (wtf!?)

**Comment by lukebarnard1** [comment]
I've since upgraded to Chrome 57 and, as expected, it's still a problem.

**Comment by turt2live** [comment]
*coughs* #3630 :) 

This seems to apply to both dark and light themes.

**Comment by ara4n** [comment]
i've dialled down the brightness of focus highlights to 125% on the light theme which improves it significantly.
