### ISSUE TITLE
Enable forwarding uploaded files

### ISSUE THREAD

**Issue by aurabindo** [vector-im/riot-web#3663]
### Description

Make it possible to forward a particular file to different user once uploaded. This will reduce the duplication of data when I would want to send to different people who are not available though one group.

There is no forward option in Riot Web. Currently the forward option in Android app uploads a new version of the file. It would be faster experience for the user if forward option always reuse the uploaded file being forwarded.

**Comment by t3chguy** [comment]
Duplicate of #3592

**Comment by aurabindo** [comment]
hmm the title of the referenced issue had `fwd` instead of `forward`, which is why I should have missed the original issue when searching
