### ISSUE TITLE
key-up/down doesn't work under Windows to navigate from SearchBox

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3667]

**Comment by lampholder** [comment]
Which SearchBox? What's the expected behaviour?

@ara4n this bug would be a _lot_ more useful for me with just a little more information 😜

**Comment by turt2live** [comment]
SearchBox appears to be the element above the room sidebar on the left. If it is, I'm on riot.im/develop and can't reproduce this on Windows 10, Chrome 57.

**Comment by lampholder** [comment]
That component does appear to be called SearchBox, even though its function is clearly filtering, not searching :\

**Comment by ara4n** [comment]
seequ reported this and then declared it started working. so i think he was just on an old build. sorry for terseness; this bug was mainly for me (as part of the quick-search implementation i did over easter)
