### ISSUE TITLE
sticky headers don't refresh when the window is resized any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3670]

**Comment by lukebarnard1** [comment]
![gifrecord_2017-04-20_150253](https://cloud.githubusercontent.com/assets/6750344/25234595/7d623a48-25da-11e7-895a-a97e22d42744.gif)

**Comment by lampholder** [comment]
Is there a definition somewhere of how they are supposed to resize? What about that gif isn't what we want?

**Comment by ara4n** [comment]
the sticky headers are meant to stick to the bottom. they don't, due to my recent optimisation work.

**Comment by ara4n** [comment]
fixed in 1faecfd
