### ISSUE TITLE
The memberinfo panel is a mixed bag of UI concepts.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3678]
![memberinfo_pane_issue](https://cloud.githubusercontent.com/assets/1922197/25244950/a08483f8-25fa-11e7-8ad0-f949b85c48a7.png)

Featuring:
 - links that are actually buttons
 - buttons that are buttons
 - different-looking buttons
 - a dropdown to set a value (that can optionally be set to a subset of the values by clicking a link that is actually a button)
 - warning icons that don't have tooltips to say what they're warning about
 - a scary blacklist button that you don't know if it will take effect immediately and/or be reversable

Also the 'dividing line' between devices actually separates the device id from the buttons that do stuff to that device, which gets confusing as you scroll down the (inevitably huge) list of devices.

Not to mention the buttons don't line up with each other :P

**Comment by yannicka** [comment]
The current seems to correct the problems cited:
![image](https://user-images.githubusercontent.com/22885898/87854093-8322a680-c90f-11ea-8a6f-51d6695b91b9.png)
