### ISSUE TITLE
Files sidebar doesn't show encrypted files

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#3679]
### Description

In an unencrypted room, the 'files' sidebar shows all uploaded files in the room. In riot-android, this happens for encrypted files as well, but in riot-web they are not shown in this sidebar.

### Steps to reproduce

- Enable encryption in a room
- Send a file in this room
- Open the 'files' sidebar

I would expect to see the encrypted files that were sent in this room, but only files sent before encryption was enabled show up there.

![screen shot 2017-04-20 at 5 52 45 pm](https://cloud.githubusercontent.com/assets/1923178/25254180/48010aec-25f2-11e7-8f18-3906e9daeb44.png)

### Version information

- **Platform**: Desktop
- **OS**: macOS
- **Version**: 0.9.8

**Comment by ara4n** [comment]
dup #3412 - will reference the excellent report from there though. thanks!
