### ISSUE TITLE
field names (e.g. in registration screen) are light and hard to read

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3685]
there isn't enough contrast between the text and the background colours
![screenshot - 200417 - 11 22 45 pm](https://cloud.githubusercontent.com/assets/1012976/25261544/575ac3b0-2620-11e7-826f-0aa9ffacad77.png)

**Comment by lampholder** [comment]
Placeholder fields have to be faint (maybe not this faint) to distinguish them from actual values - perhaps in the medium term we should consider labelling them with external labels? This would also solve their being wholly obscured by autocompleted values.

- [ ] as a good next step make the placeholders a little bit darker
- [ ] in the long run consider redesigning to place labels externally

**Comment by lampholder** [comment]
That said, they don't actually look too faint to me as they are :)

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/52827052-75b11f00-3080-11e9-9564-15812eb030cb.png)

I think we fixed this
