### ISSUE TITLE
CountryDropdown does strange things when Enter is hit

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3686]
If you hit <kbd>Enter</kbd> whilst typing an unfinished country name, you get:

![2017-04-21-110250_82x60_scrot](https://cloud.githubusercontent.com/assets/6750344/25273054/12aff3b8-2682-11e7-9e3b-56079e352b8e.png)
which looks like the desired image cannot be found. It appears to be looking for `1f1d3-1f1c9`, but we don't ship an emoji under that name.

**Comment by lampholder** [comment]
Bleugh.

Can probably be tackled in tandem with https://github.com/vector-im/riot-web/issues/3524
