### ISSUE TITLE
RoomSubList_chevron is in the wrong place

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3691]
![2017-04-21-164850_255x67_scrot](https://cloud.githubusercontent.com/assets/6750344/25285597/bd0fda0a-26b2-11e7-94cb-c0202413051e.png)

(It should probably be further to the right?)

**Comment by ara4n** [comment]
the design is deliberately there to leave room for the badge.  whether this is correct or not...

**Comment by ara4n** [comment]
Yeah, zeplin designs confirm this is as desired. I don't think it a problem particularly.

<img width="250" alt="screen shot 2017-04-22 at 16 20 22" src="https://cloud.githubusercontent.com/assets/1294269/25305676/bd4850b8-2777-11e7-9e9c-4d094b5b9e9c.png">

**Comment by lukebarnard1** [comment]
ah, fair enough!
