### ISSUE TITLE
grey out labels for disabled controls in settings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3698]

**Comment by grahamperrin** [comment]
From https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1492866675955166eKlUX:matrix.org: 

> Re: the screenshot below, should I treat the Anyone radio button as an issue with Riot? … 

![anyone](https://cloud.githubusercontent.com/assets/192271/25304821/048107ce-2767-11e7-871c-027b9c04a684.png)

> …  on closer inspection, you're correct.
> There's not sufficient distinction between things that can be enabled, and things that can not. …

## Another example

Only one of these two preferences can be enabled: 

![only one of these two can be enabled](https://cloud.githubusercontent.com/assets/192271/25304835/438885dc-2767-11e7-9863-c431d7190131.png)

**Comment by turt2live** [comment]
fixed
