### ISSUE TITLE
immediately after joining a room via /join, tab-complete doesn't work at all

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3700]
can't complete names or commands - everything just blinks red

**Comment by ara4n** [comment]
this is really annoying.

**Comment by ara4n** [comment]
it fixes if you switch away from the room and back again.

**Comment by t3chguy** [comment]
it seems to have the autocomplete data of the last room in some cases, in some simply none 

Only seems to happen when joining new rooms
also found that after a join new Composer doesn't have focus, but old does

**Comment by lukebarnard1** [comment]
This is because `RoomView` calls `setUserListFromRoom` once on component mount. It should be calling it when we receive the `onRoom` down the sync stream after joining.
