### ISSUE TITLE
email template needs current riot logo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3701]

**Comment by lampholder** [comment]
I'm guess this is all three of:
 - registration
 - invite
 - notification

**Comment by lukebarnard1** [comment]
I'm guessing we need to use 
![2017-04-27-143302_212x178_scrot](https://cloud.githubusercontent.com/assets/6750344/25485640/84275df0-2b56-11e7-958f-cda3444f46d3.png)

(vector-im/vector-web/vector/img/logos/riot-logo.svg)
