### ISSUE TITLE
Consider whether the bottom-left and top-right button groups are too hidden

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3704]
We get fairly consistent feedback that the bottom-left (and top right) button groups are too hidden - e.g. @frabcus' excellent comment at https://github.com/vector-im/riot-web/issues/2955#issuecomment-279975697.

This could be mitigated a bit by a joyride style tour, but we need to revisit the UX to see if these should be somehow more prominent and discoverable.

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/3383

**Comment by turt2live** [comment]
In practice I think we fixed this with the new design
