### ISSUE TITLE
support ascii escape codes for special characters in room names

### ISSUE THREAD

**Issue by pravi** [vector-im/riot-web#3708]
### Description
Ascii escape codes like %23 for # is not working. For example https://riot.im/app/%23/room/%23plus:matrix.org 

### Steps to reproduce

visit any room with %23 substituted for # in url.

Describe how what happens differs from what you expected.

### Version information

 **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 52
- **OS**: Debian sid
- **URL**: riot.im/app / 

If you give # in url, it gives error in w3c validator https://validator.w3.org/nu/?doc=http%3A%2F%2Fkl10.fsug.in%2F

```
Error: Bad value https://riot.im/app/#/room/#ssugm:matrix.org for attribute href on element a: Illegal character in fragment: # is not allowed.

From line 80, column 109; to line 80, column 207

">Home</a><a class="w3-bar-item w3-button w3-padding-16" href="https://riot.im/app/#/room/#ssugm:matrix.org">Matrix

```

**Comment by uhoreg** [comment]
I think this is #3550?  The first "#" is supposed to be there, because it indicates that the rest of the URL is supposed to be a fragment identifier, but the rest of the "#"s after that should be escaped.

**Comment by lampholder** [comment]
I agree with @uhoreg - closing. @pravi please reopen if you think there's a subtlety we've missed.
