### ISSUE TITLE
"Unable to decrypt: Error: Duplicate message index, possible replay attack" on previously decrypted messages, after resume/restart

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3712]
### Description

Riot seems to have gotten confused, and now says "Unable to decrypt: Error: Duplicate message index, possible replay attack" on messages that it previously decrypted in #megolm:sw1v.org.  I noticed this after I suspended and resumed my computer -- the "Unable to decrypt" messages seem to be all the messages received before I suspended my computer.  https://matrix.to/#/!UCnwUWwIKhcpaPTHtR:sw1v.org/$14929562381788079GbZDJ:matrix.org is the first message that I can read, which was sent after I suspended my computer.  Scrolling up, it looks like every other message in the room history has that same error.

![image](https://cloud.githubusercontent.com/assets/1012976/25318970/16b0e3ba-2866-11e7-9630-3897eb6b28f4.png)

Messages in another encrypted room seem to be unaffected (although that room did not have any recent messages -- I don't know if that has anything to do with it).

Log: ~~sent (at least, will be sent shortly)~~ `Failed: ETIMEDOUT` ☹️ 

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.8

**Comment by uhoreg** [comment]
Unfortunately, submitting a rageshake times out, and the console logs seem entirely unhelpful:

```
2017-04-23 08:44:35.847 bootstrap_node.js:27 Persisting sync data up to 
2017-04-23 08:49:36.258 indexeddb-local-backend.js?79bc:216 Persisting sync data up to  s137151481_208559999_425526_22691963_228743_74311_748348_599730
2017-04-23 08:49:36.259 bootstrap_node.js:27 Persisting sync data up to 
2017-04-23 20:29:44.804 indexeddb-local-backend.js?79bc:216 Persisting sync data up to  s137467904_209457582_77719_22772440_229970_74628_750819_602959
2017-04-23 20:29:44.911 bootstrap_node.js:27 Persisting sync data up to 
2017-04-23 20:33:30.578 rageshake.js:63 Using sessionid 45qSBF28sreVrbp3oYRU1XuY73PyNmf/fhPn+6ZSiYo for device @michael:productionservers.net:MUTWAFMWFB
2017-04-23 20:33:30.579 rageshake.js:63 sharing keys with device @michael:productionservers.net:QHHRTWVJXZ
2017-04-23 20:33:30.579 rageshake.js:63 Using sessionid bVy2IpoyjPdnPZmgnk2iPTDcHFhhbm9qNTblqNlkvJY for device @michael:productionservers.net:QHHRTWVJXZ
2017-04-23 20:33:30.596 rageshake.js:63 sharing keys with device @michael:productionservers.net:ENSNYUMQER
```

`2017-04-23 08:49:36.259` would have been the last message before I suspended my computer, and `2017-04-23 20:29:44.804` would have been the first message after I resumed, and `2017-04-23 20:33:30.578` is when I send a message to #megolm, after noticing the issue, which means that there's nothing relevant in that section of the logs.

Later on in the logs (probably after scrolling up to check previous messages), I see messages such as

```
2017-04-23 20:36:59.853 rageshake.js:63 Error decrypting event (id=$14927245961215939DlXmd:matrix.org): DecryptionError[msg: Error: Duplicate message index, possible replay attack: mTvcbEvXXJgd3R42QQEkVgpl5k6vdKFoBD9kY3taG0s|QUdCGKebAtP+F8VpnykvKDYFeHoImDHFXCelJWQGwUU|1, session: mTvcbEvXXJgd3R42QQEkVgpl5k6vdKFoBD9kY3taG0s|QUdCGKebAtP+F8VpnykvKDYFeHoImDHFXCelJWQGwUU]
```

But that doesn't seem to provide any more useful information.

**Comment by richvdh** [comment]
> Unfortunately, submitting a rageshake times out, 

0.9.9 compresses the uploaded logs, so should fix this, once it's released.

Basically the crypto code has been asked to decrypt the same events twice, which presumably means that Riot has forgotten it saw the events the first time.

**Comment by uhoreg** [comment]
FYI, doing a "Clear cache and reload" causes those messages to be readable again.  So it's annoying that it happens in the first place, but at least it isn't a permanent condition.

**Comment by richvdh** [comment]
I'd imagine a quit and restart also solves it.

It turns out that when we get a limited timeline back from /sync (in other words, there have been more than 20 events in the room since your last sync, which is entirely plausible if you suspend your riot instance for 12 hours), js-sdk forgets about the old events; then when you reload them the crypto layer thinks that you're being replay-attacked.

In essence, it's because https://github.com/matrix-org/matrix-js-sdk/pull/395 happened without reference to the TODO at https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/OlmDevice.js#L106.

**Comment by uhoreg** [comment]
Yup, I count over 50 messages in that room between my suspend and resume.

**Comment by richvdh** [comment]
Possibly this can also happen on restart?
- we load a handful of messages from indexeddb and decrypt
- we get a limited sync and reset
- we back-paginate, finding the messages we'd previously loaded from indexeddb, and hit the same case as [above](https://github.com/vector-im/riot-web/issues/3712#issuecomment-296682425).

**Comment by zzottel** [comment]
Yes, happens to me every once in a while after a restart. I never put my work laptop to sleep, only close FF and shut down the laptop. When I enter the Riot tab after starting FF again, sometimes there are the replay attack messages.

A reload always fixes the problem.

**Comment by JigmeDatse** [comment]
I don't suspend the computer, at least not consciously (I know that my OS has different ideas about how it wants to be configured than how I want it configured, so it's possible it is doing something that some long time ago I said "stop it" to).  I do shut down at the end of the day.  So suspend/resume are not the only culprits.  But maybe shutdown/restart while Chrome is open lead to it?

**Comment by maxidor** [comment]
This also happens on Riot Desktop on start up from power off.
Closing and re-opening Riot doesn't necessarily solve the issue.
Clearing cache always (so far) solves the issue.

**Comment by uhoreg** [comment]
It sounds like this is exactly the problem mentioned in the "TODO" at https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/OlmDevice.js#L99.

Would it help if OlmDevice stored the event ID corresponding to the group session, and then when decrypting checked if the event ID matches the previous event ID?  So something like (completely untested):

```
diff --git a/src/crypto/OlmDevice.js b/src/crypto/OlmDevice.js
index 3c3336e8..28a1b54c 100644
--- a/src/crypto/OlmDevice.js
+++ b/src/crypto/OlmDevice.js
@@ -802,7 +802,7 @@ OlmDevice.prototype.importInboundGroupSession = async function(data) {
  *    keysClaimed: Object<string, string>}>}
  */
 OlmDevice.prototype.decryptGroupMessage = async function(
-    roomId, senderKey, sessionId, body,
+    roomId, senderKey, sessionId, body, eventid,
 ) {
     const self = this;
 
@@ -816,13 +816,13 @@ OlmDevice.prototype.decryptGroupMessage = async function(
         } else {
             // Check if we have seen this message index before to detect replay attacks.
             const messageIndexKey = senderKey + "|" + sessionId + "|" + res.message_index;
-            if (messageIndexKey in self._inboundGroupSessionMessageIndexes) {
+            if (messageIndexKey in self._inboundGroupSessionMessageIndexes && self_inboundGroupSessionMessageIndexes !== eventid) {
                 throw new Error(
                     "Duplicate message index, possible replay attack: " +
                     messageIndexKey,
                 );
             }
-            self._inboundGroupSessionMessageIndexes[messageIndexKey] = true;
+            self._inboundGroupSessionMessageIndexes[messageIndexKey] = eventid;
         }
 
         sessionData.session = session.pickle(self._pickleKey);
diff --git a/src/crypto/algorithms/megolm.js b/src/crypto/algorithms/megolm.js
index 7d2fd7e1..6c355259 100644
--- a/src/crypto/algorithms/megolm.js
+++ b/src/crypto/algorithms/megolm.js
@@ -627,7 +627,7 @@ MegolmDecryption.prototype.decryptEvent = async function(event) {
     let res;
     try {
         res = await this._olmDevice.decryptGroupMessage(
-            event.getRoomId(), content.sender_key, content.session_id, content.ciphertext,
+            event.getRoomId(), content.sender_key, content.session_id, content.ciphertext, event.getId(),
         );
     } catch (e) {
         if (e.message === 'OLM.UNKNOWN_MESSAGE_INDEX') {
```

The main concern, AFAICT, is whether Riot can trust the server to never send it two different events with the same event ID.

**Comment by uhoreg** [comment]
As a followup to my previous comment, maybe if `_inboundGroupSessionMessageIndexes` stored both the event ID and the `origin_server_ts`, instead of just the event ID.  This would at least prevent the scenario where a past event gets replayed as a later event, since the timestamp would need to match.  And any use case that depends on the actual uniqueness of the event should store the event IDs that it has seen.

I think this might potentially provide better security than the proposed solution in the TODO, since the proposed TODO solution could only result in catching replay attacks within a relatively small window of messages.  And this seems more robust than relying on developers to remember to purge items from `_inboundGroupSessionMessageIndexes`.

There is, however, another issue that `_inboundGroupSessionMessageIndexes` could grow without bounds and eat up a lot of memory if it has received a lot of encrypted messages.  So maybe it should be moved to indexeddb, though this would mean that some functions would need to be changed to be async.

@richvdh if this approach seems sane-ish, I can make a PR (and test it out) (without any indexeddb changes).

**Comment by richvdh** [comment]
You're correct in that it relates to the TODO at OlmDevice.js:99. As I wrote [above](https://github.com/vector-im/riot-web/issues/3712#issuecomment-296682425):

> it's because matrix-org/matrix-js-sdk#395 happened without reference to the TODO at https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/OlmDevice.js#L106.

(the lines in OlmDevice have since moved slightly).

Yup, storing a map from message index to (event_id, ts) seems like a good solution. Indeed you could store a hash of the event or similar.

However, I do think it would be a mistake to do so in localstorage rather than in indexeddb - which as you note, requires more work on making things asynchronous (though I did lay much of the groundwork for that already).

An alternative approach would be just to clear out the map when the code in matrix-org/matrix-js-sdk#395 unloads events.

**Comment by uhoreg** [comment]
I'll work on a patch and test it.  Do I need to worry about maintaining compatibility in `OlmDevice.prototype.decryptGroupMessage`?  i.e. should it do the exact same thing as it currently does if it's only called with the roomId, senderKey, sessionId, and body?  Is OlmDevice meant to be a public API, or is it only meant to be used internally?

**Comment by richvdh** [comment]
sorry, I missed your question, because apparently github has a mind of its own as to whether or not it emails me.

OlmDevice is private so there's no need to preserve compatibility.

**Comment by uhoreg** [comment]
fixed by https://github.com/matrix-org/matrix-js-sdk/pull/555
