### ISSUE TITLE
performance on searching users in invite dialog is still terrible on my account

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3713]

**Comment by lukebarnard1** [comment]
I guess that answers the question, "Is flux fast enough?" following https://github.com/matrix-org/matrix-react-sdk/pull/732

**Comment by dbkr** [comment]
s/flux/fuse/

**Comment by lukebarnard1** [comment]
>s/flux/fuse/

Ah, updated

**Comment by dbkr** [comment]
Had a quick look at this and yep, it's pretty much what Luke said: fuse takes 1.26s to search over 77,000 users. It doesn't index or anything, it just does a linear (I think) scan over all the results when you search.

Do we actually need this to be a fuzzy search? If so, we'll have to look at something smarter like the Levenstien distance algorithm Avril was looking at for autocompletion of names in RTE.

**Comment by ara4n** [comment]
Can we please just turn off the fuse thing?  I'm assuming this is trivial and can be snuck into today's release.
