### ISSUE TITLE
Dialogs don't go away when using Enter instead of clicking the button

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3714]
### Description

After clicking the + in the bottom left, a create room dialog is presented. After filling in the field, if the user presses the Enter key instead of clicking the Create Room button, the dialog is immediately returned to the user.

### Steps to reproduce

- Click + button to create a room
- Give it a name (required to reproduce) and press Enter to create that room
- The dialog should reappear.

I'd expect for the dialog to go away and not come back unless I ask it to.

Log: sent   

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Also appears to apply to the kick and ban dialogs (with or without reasons given). There appears to be some race condition or other qualifier I'm not aware of that *occasionally* allows for the 'Create Room' dialog to re-open when not giving a name to the room.

**Comment by lampholder** [comment]
I think enter-for-submit (and as mentioned elsewhere esc-for-back-out) should be applied universally across the app - if we agree on this we'll probably make a concerted effort to spot and fix cases where this is not the case at some point in the future.

**Comment by turt2live** [comment]
Enter was working prior to this report. It's sad to see it go :(

**Comment by lampholder** [comment]
Oh, so this is a regression?

**Comment by lukebarnard1** [comment]
It's as if there are two dialogs and as one closes, the other one appears.
