### ISSUE TITLE
Room list formatting breaks when connecting mouse on macOS

### ISSUE THREAD

**Issue by superdump** [vector-im/riot-web#3716]
When connecting a mouse to a macOS device that normally has a touch pad, scroll bars are added to scrollable areas which takes space and forces the room titles in the room list onto the line below, placing them under the next room's avatar.

**Comment by superdump** [comment]
I think to trigger it, one would need to load the page using only the touch pad and then connect the mouse. Refreshing the page with the mouse connected works fine.

**Comment by ara4n** [comment]
This is basically an instance of https://github.com/vector-im/riot-web/issues/1276 (aka https://github.com/vector-im/riot-web/issues/476)
