### ISSUE TITLE
no warning on close whilst typing a message

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#3724]
I often somehow manage to accidentally trip tab close and without warning riot will abide, it should fight back and ask me to confirm

**Comment by turt2live** [comment]
I ran into a similar issue while testing something: uploading files also doesn't preventing a close.

**Comment by lampholder** [comment]
Is this not down to personal preference? If we did implement this I think I'd like it to be configurable - I personally hate it when website think they know better than me 🗡 

What do other people think?

**Comment by lampholder** [comment]
Actually, rereading the title - was the intention that this behaviour only occur when you're halfway through a message? That's _much_ less annoying.

**Comment by t3chguy** [comment]
Content is saved so not the end of the world, as to @turt2live's issue that has been fixed in the referenced PR

**Comment by ara4n** [comment]
@t3chguy might be worth checking how often the content is saved - might be worth an explicit save() on onUnload()?

**Comment by t3chguy** [comment]
@ara4n it looks like it was saved explicitly on componentWillUnmount, which I presume fires during unload also?

**Comment by ara4n** [comment]
might be worth checking. i'd be surprised if react hooks into onUnload to call unmount on all the components, given it's fairly unusual to need to do cleanup when the user closes a tab.

**Comment by t3chguy** [comment]
@ara4n weirdly looks like `sentHistory.saveLastTextEntry()` is only being called on `componentWillUnmount` yet seems to dump content just fine when closing Riot

**Comment by t3chguy** [comment]
done by referenced PR
