### ISSUE TITLE
single `=` or `-` is interpreted as title

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3726]
```
test
=
```

becomes `<h1>test<h1>`

Shouldn't there be a minimum number of underline characters to trigger this?

**Comment by richvdh** [comment]
This does seem to be as expected by the commonmark spec:

http://spec.commonmark.org/0.27/#example-52

so we should probably leave this as-is. Still, leaving here in case anyone else has opinions.

**Comment by lampholder** [comment]
My passion for categorisation means I can't leave this chap unlabelled, so I'm going go ahead and stick the somewhat inflammatory 'INVALID' label on there for now :)

@richvdh if people do jump in with opinions we can always rethink.

**Comment by pafcu** [comment]
@richvdh  @lampholder Could perhaps be closed if it actually is working "as intended" (i.e. follows Commonmark). It might make sense to instead create an issue collecting all the surprising/disliked stuff in Commonmark (there seems to be a few complaints)

**Comment by richvdh** [comment]
yeah let's close this one. Volunteers to start a "unexpected commonmark behaviour" doc welcome. Not sure an issue is the best place since it's not something we currently plan to fix.
