### ISSUE TITLE
More than one RoomTile can be highlighted

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3729]
![2017-04-25-140033_232x241_scrot](https://cloud.githubusercontent.com/assets/6750344/25386539/9e8816f0-29bf-11e7-9057-c9318cd84980.png)

Similar to https://github.com/vector-im/riot-web/issues/3672 (but this one can't be solved with CSS)

**Comment by lampholder** [comment]
I can reproduce by clicking one room then dragging another.

**Comment by yannicka** [comment]
Do you still have the problem?

**Comment by turt2live** [comment]
Presumed fixed.
