### ISSUE TITLE
Sending message of just '/me' doesn't behave as expected

### ISSUE THREAD

**Issue by commagray** [vector-im/riot-web#3733]
So, writing `\/me` is expected with output like just `/me`, but I get `* Coma Grayce /me`. Wut.
![screenshot_20170425_224524](https://cloud.githubusercontent.com/assets/27947961/25404502/efc0b1a0-2a08-11e7-9410-fa429c15341d.png)

**Comment by lampholder** [comment]
To clarify, I think we're talking about this behaviour:
![gifrecord_2017-04-27_100620](https://cloud.githubusercontent.com/assets/1922197/25476195/51f8f21e-2b31-11e7-9245-fe7c1e7f26f0.gif)

**Comment by dbkr** [comment]
Looks like this is specific to the richtext editor

**Comment by t3chguy** [comment]
caused by https://github.com/matrix-org/matrix-react-sdk/blob/6cbd04045d67197679a318944bdd40eb9d68c697/src/components/views/rooms/MessageComposerInput.js#L545-L545
