### ISSUE TITLE
Desktop app: add "--help" command-line option that lists command-line arguments

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3734]
So that people can see what arguments can be passed, e.g.

- `--proxy-server`
- `--disable-smooth-scrolling`
- `--enable-logging`

**Comment by t3chguy** [comment]
good call, there is also `--hidden`

**Comment by lampholder** [comment]
Seems like a good idea to me.

**Comment by dbkr** [comment]
Problem is that (apart from --hidden) these options are magically added by electron so we could add docs but if electron decide to change things it would just end up being wrong. It would be nice if electron had a way to list the options it provides, but it doesn't look like it does, so just adding some doc is probably better than nothing.
