### ISSUE TITLE
Browser notifications for things that are not mentions, whilst a room is set to 'Mentions only'

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#3735]
## `/develop/`

Whilst https://riot.im/develop/#/room/#freenode_#trueos:matrix.org is set to _Mentions only_ I received (at least) two notifications for posts that do not mention me. 

The most recent: https://matrix.to/#/!rlkOZoHZqtNXEQHzjY:matrix.org/$1493161419626990ReTNQ:matrix.org

**Comment by grahamperrin** [comment]
More notifications this evening, from a different room – again, a room that is set to _Mentions only_. 

An example: https://matrix.to/#/!uvlLotPlOrcJhyNnOj:matrix.org/$1493232526298144TYRDb:matrix.org

**Comment by lampholder** [comment]
I can't see the history for #trueos and or #pcbsd (not that I expect seeing the events to be particularly useful anyway).

This is very peculiar :\

Are you getting notifications for _all_ posts, or just a random selection? If it's just a subset, is there any pattern to the notifications you do receive?

Could you try refreshing and then checking the notification setting on the room again (to make sure that the correct setting has been persisted)?

**Comment by grahamperrin** [comment]
Thanks. 

> … refreshing and then checking the notification setting on the room …

I did so, for both rooms. For each room I chose to click the volume slider: 

- down from _Mentions only_ to _Mute_
- then (after observing disappearance of the slider) back up to _Mentions only_.

There followed another notification for a message, to one of the rooms, that was not a mention.

**Comment by grahamperrin** [comment]
>  … for all posts, or just a random selection? If it's just a subset, is there any pattern to the notifications you do receive? …

Based on my current view of https://riot.im/develop/#/room/#freenode_#trueos:matrix.org I _might_ say, a subset, because I don't recall any notification for any recent message. 

I can not say with certainty because: 

- I don't know what Firefox does, in my environment, with notifications whilst I am away from the computer with the screen locked by KDE (Plasma 4)
- there may be complications from other issues, one of which seems to be very recent (and not limited to the two rooms above).

**Comment by grahamperrin** [comment]
Sorry! PEBKAM, I forgot that I had set keywords: 

- PC-BSD, TrueOS, graham, grahamperrin

With a reasonable assumption that each notification was for a mention _of a keyword_, I close this issue. If you like, mark it as invalid.
