### ISSUE TITLE
New login page is a bit confusing for users with custom homeservers

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3736]
@erikjohnston brought this up earlier, but unsure if it got bugged anywhere:

* It's a bit weird that the domain part of the mxid disappears when you select a custom homeserver
* It's a bit weird that you can't interact with it when you're on the default homeserver (e.g. to click on it to pick an alternative HS)
* At the least, we should surely show a placeholder of the expected shape of mxid if you choose a custom HS.
* Ideally, we should synthesise the expected mxid domain from the custom HS details (which is blocked on .well-known URI stuff landing)

**Comment by lampholder** [comment]
On the last point, if I understand it correctly the .well-known stuff doesn't work that way round.

If we have the custom homeserver location, it's feasible (though perhaps not yet exposed as an API) to ask that homeserver what its domain part is.

If completing specifiying a custom homeserver could trigger replacing `:matrix.org` with `:appropriatedomain.tld` would enough of the confusion be gone?

**Comment by ara4n** [comment]
can we perhaps just ditch the @:[        ]:[      ] template for now? in the interests of minimising MXID exposure to the user, and in practice the input field accepts both `matthew` and `@matthew:matrix.org`?  I just logged into my arasphere HS and can concur that the UX feels weird...

**Comment by lukebarnard1** [comment]
https://github.com/matrix-org/matrix-react-sdk/issues/906 is now deployed on https://riot.im/experimental
