### ISSUE TITLE
@ section on username box is 1px too short at the bottom

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3738]

**Comment by dbkr** [comment]
![screen shot 2017-04-26 at 13 12 05](https://cloud.githubusercontent.com/assets/986903/25433880/fe74ec06-2a81-11e7-8549-1f4c0359f4ab.png)

**Comment by lampholder** [comment]
Did this already get changed? I've definitely seen the 1 pixel wonkalonk in the past, but it looks good now in Chrome on Ubuntu, Windows at least.

**Comment by lampholder** [comment]
The wonky extra pixel is there on Chrome on Mac. Hoo-ray for browser standards.

**Comment by ara4n** [comment]
fixed by fe61a7e. i really need to give people a crash course in maintainable CSS - the problem here is that we were sizing the box to the font, which inevitably has different sizing on platforms.  If we have boxes that we want to line up we *have* to give them explicit heights.
