### ISSUE TITLE
when Ctrl+K-ing the search field should be highlighted to make it clear tat the focus has moved there

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#3740]

**Comment by lampholder** [comment]
Also, the placeholder text should probably advertise the ctrl+k shortcut.

Do you have any thoughts as to what the highlight should look like?

**Comment by ara4n** [comment]
in keeping with our focus behaviour elsewhere we could just whack up the brightness on the SearchBox overall when focused.

**Comment by lampholder** [comment]
So should we mirror the room tile behaviour?

Room tiles when selected briefly flash bright then settle down to brighter-than-their-peers - I think this could work well for the filter box (esp. if it flashed with every selection/ctrl+k).

**Comment by t3chguy** [comment]
This is resolved now due to the Explore/Filter combo now getting expanded to Filter when Ctrl+K'ing
