### ISSUE TITLE
When using the keyboard alone to page down, 'Jump to first unread message.' jumps up to messages that are read

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#3747]
### Description

The more that I test with – and without – keyboard-only paging up and down, in relatively busy rooms such as https://riot.im/develop/#/room/#riot:matrix.org, the greater my suspicion that when using the keyboard alone, the system _sometimes_ **fails to sense that messages are read**. 

### Steps to reproduce

Dark mode, right handed, with an extended keyboard, with a **trackball** pointing device (no scroller) to the right of the keyboard: 

1. in a room that has many pages of unread messages
2. accept an invitation to jump
3. with your **left** hand, reach to the far right of the keyboard
4. key Page Down
5. refrain from moving your left hand
6. take **relatively little time** to read
7. whilst rushing the reading, use your right hand move the pointer down from the first message, over as many messages as possible, to the last – so that the backgound colour of the line changes, momentarily, for at least some (maybe all) of the visible messages
8. move the pointer down, to the left, then up – ready for the next page of messages
9. repeat steps (4)–(8) …

#### Expected and actual result

- the system behaves as if the read messages are read :ballot_box_with_check: 

#### Variation to the steps

1. in a room that has many pages of unread messages
2. accept an invitation to jump
3. refrain from moving your left hand
4. with your **right** hand, reach to the far right of the keyboard
5. key Page Down
6. maybe move the pointer aside, beyond the left or right extent of the messages column
7. **refrain from moving the pointer**
8. take **much more time** to read all visible messages
9. repeat steps (5), (7) and (8) (and refrain from moving the pointer) …

#### Expected and actual result

- the system should behaves as if the read messages are read

#### Actual result

- after a few repeats of steps (5)–(8), the system misbehaves – as if at least one of the read messages is **unread** :x: 
- there appears a prompt to jump
- if the prompt is accepted, then the jump is _up_ – to a point in time where there was previously, with certainty, enough time to truly read the message.

### In other words

There seems to be a workaround to the bug, but the workaround is not ergonomic. 

It should be possible to have the system recognise that messages are read: 

- _without_ hand movements; or 
- without unnaturally resting the left hand at the far right of the keyboard whilst using the right hand to roll the ball.

### Please note

This issue `#3747` should be not confused with #3746. Maybe the clearest distinction between the two issues: 

- in #3746, the point to which the system returns, after the jump, does not change
- in this issue, the jumps are progressive however – if each of the system's prompts to jump is followed, strictly, then progress is a snail's pace.  

### Version information

- Firefox 53.0 (64-bit)
- TrueOS Desktop

```text
$ about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
       after restart (R) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    number of cores ……………… 4
host ……………………………………………………… momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
memory ………………………………………………… 16384 MB available, 3653 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… a009033ff
OS kernel build time ………………………………………………………… Wed 2017 Mar 29 20:13:33 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… CUSTOM
TrueOS version …………………………… TrueOS-Desktop-201703201429
uptime ………………………………………………… 13:27
user  …………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …… KDE
    sound card driver ………… pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> on hdaa1  (1p:2v/1r:4v) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… intel_drv.so 

$ 
```

**Comment by lukebarnard1** [comment]
I think this would be as simple as firing `user_activity` on page up, down
