### ISSUE TITLE
Don't prompt PWLUs for the password they don't know

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3748]
The details of the new guest experience for Riot are on the project plan: vector-im/riot-meta#59

If we enable users to create new accounts without submitting passwords, we need to make this bit of UI in the user settings pane still make sense:

![image](https://cloud.githubusercontent.com/assets/1922197/25482001/b77b4090-2b47-11e7-9c4c-9bbee8bdc73b.png)

This should either present a mechanism to set the password inline, or launch the same modal you'd get from clicking the 'complete registration' nag button.

If we implement it inline, at the bare minimum it should look like this:

![image](https://cloud.githubusercontent.com/assets/1922197/25482016/c6c0ec12-2b47-11e7-9101-407bdd005aaa.png)

Of course, we could just remove the section completely and rely on the modal.

**Comment by lukebarnard1** [comment]
I've realised this affects more than just the "Account" section in UserSettings:
 - [ ] UserSettings "Account" section;
 - [ ] UserSettings "Devices" section (when deleting them, the user is prompted for a pwd);
 - [ ] UserSettings deactivation section, which requires a password.

These will each require a special case for PWLUs

**Comment by turt2live** [comment]
This isn't a thing that we do anymore, so pushing this under the umbrella of https://github.com/vector-im/riot-web/issues/9264
