### ISSUE TITLE
the camera icon on room settings looks greyed out but it isn't

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3752]

**Comment by lampholder** [comment]
This one?

**Comment by ara4n** [comment]
hm. i don't get this one; it was reported by someone else, and i vaguely remembered the camera being too grey so filed it. but in practice, it isn't.

Instead, i've fixed a different bug (that the same camera icon lacks a cursor-pointer on the user settings page: 582a34c)... which i vaguely remember may actually be what they were complaining about.
