### ISSUE TITLE
/develop freezes for 10s on trying to join Matrix HQ as a guest

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3755]
It fires a onRoomMemberName and onRoomStateMember on every single new room member, of which there are thousands.  Time is burnt in calculateRoomName for each and every one, as well as logging in the constant time dispatcher code (which I just removed for now).

**Comment by lampholder** [comment]
@ara4n is this guest-specific behaviour? Or would it be the same for any new joiner to Matrix HQ?

**Comment by ara4n** [comment]
Probably impacts anyone. Removing the logging will have sped it up a bunch but it's still not ideal.

-- 
Matthew Hodgson
Matrix.org

**Comment by ara4n** [comment]
this got fixed somewhere along the way; /develop froze for a mere 328ms on trying to join.

**Comment by ara4n** [comment]
oh, it probably helps that ILAG has removed the concept of guests effectively...
