### ISSUE TITLE
Verifying signatures for someone's devices is very slow

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3764]
On opening the MemberInfo panel, Riot starts verifying signatures for all that person's devices, which makes the UI lock up for about 300ms at a time as each verification seems to take of the order of hundreds of milliseconds).

**Comment by ara4n** [comment]
See also https://github.com/vector-im/riot-web/issues/3595 and #3310

**Comment by lampholder** [comment]
@dbkr you filed this 3 days after the fix... do you think it's still a problem? Or were you just on /app or remembering a bug from earlier?

**Comment by dbkr** [comment]
Oh, probably using an old version then, so either fixed or dup one of those.
