### ISSUE TITLE
make `/markdown off` setting persist

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3767]
currently it gets forgotten on every restart etc.

**Comment by Matrixcoffee** [comment]
This should be a proper entry in room settings as well.

Having different interfaces to different and mutually inaccessible room settings seems like a bad idea.

**Comment by lampholder** [comment]
Is this the setting controlled within the RTE?

@Matrixcoffee - is this not currently a global setting? Are you saying you'd like it to be a per-room setting?

**Comment by Matrixcoffee** [comment]
The setting is already per-room in Riot-Web.

The issue is that it is invisible in the room's settings screen.

Having a setting which is invisible and can only be changed by typing a command, seems like a bad idea.

**Comment by lampholder** [comment]
I think invisible settings are probably okay if they are only of interest to a small number of people (and that small number of people is perfectly satisfied managing invisible settings).

In this case, the setting seems to be per-room when you're not using RTE, and global when you are using RTE - we should pick one approach and stick with it :)

**Comment by ara4n** [comment]
I've just added a global synced setting. hopefully when GranularSettings land it will magically be customisable per-room too.

**Comment by lampholder** [comment]
Current situation:
- old editor:
    - markdown enabled/disabled through /markdown command
    - setting is global but appears to be per room because when you swap rooms the editor doesn't get remounted
    - changing the setting with /markdown doesn't seem to be synced to the checkbox in global settings
- new editor:
    - markdown enabled/disabled through ctrl-m or the markdown icon
    - setting is global and appears to be global but is not synced to the user settings checkbox

**Comment by lampholder** [comment]
I think we want a stable baseline which we can later customise with per-room granular settings.

So - let's get the new editor to set/honour the global user setting and then I think we're in a good place.

It would mean that the new editor would lose the /markdown command but I don't think that's a huge loss?

**Comment by lukebarnard1** [comment]
So it turns out the RTE _does_ persist a setting for whether markdown/RT mode is enabled, called `MessageComposerInput.isRichTextEnabled`. This is not the same as `disableMarkdown`, the old setting controlled with `/markdown on|off`.
