### ISSUE TITLE
Room Directory - add manually typed server to the list of servers

### ISSUE THREAD

**Issue by pik** [vector-im/riot-web#3770]
Currently typing a server manually in room directory will not remember it, so it must be re-typed every time to view the room list. 

develop @ 67efb8bde264e3ea0823e40558d29dd89120c0c9

![screenshot from 2017-04-29 09-36-48](https://cloud.githubusercontent.com/assets/10236920/25556284/8a2cee1c-2cbf-11e7-8def-458250f4f560.png)

**Comment by lampholder** [comment]
This would be a nice thing to have.

**Comment by bqv** [comment]
:+1: I've been looking for this exact feature, didn't realise it wasn't even implemented
