### ISSUE TITLE
Design Proposal to simplify key verifications

### ISSUE THREAD

**Issue by glaxx** [vector-im/riot-web#3772]
### Description

In "Settings - CRYPTOGRAPHY" where your device key is listed, the font should be a monospaced for easier and less error prone device verification. Furthermore the fingerprint should be (visually) separated by dashes.

#### Current State: (This "fingerprint" is an example)
Device Key: **hWTyfybz46DYdYcsJnQvKZ2SKJYUavRax8B6oLbp4VP**

#### Proposed Change:
Device Key: **```hWT-yfybz46DYd-YcsJnQvKZ2-SKJYUavRax-8B6oLbp4VP```**

```
hWT-yfybz46DYd-YcsJnQvKZ2-SKJYUavRax-8B6oLbp4VP
0                                            42
```

### Steps to reproduce

Does not apply.

### Version information

- **Platform**: web
For the web app:

- **Browser**: chromium 58.0.3029.81 (64-bit)
- **OS**: Arch Linux
- **URL**: riot.im

**Comment by lampholder** [comment]
Thanks for the suggestion - it looks to me like the device key already _is_ monospaced (it looks like it's set in the css, and appears monospaced on Chrome on my mac).

Visually separating the key with cosmetic dashes is an interesting idea - is there a particular rationale for the 3-10-10-10-10 breakdown over another pattern?

**Comment by glaxx** [comment]
Regarding the font: Oh. I probably was just to blind/drunk (or so haha) to recognize it as an monospaced font.

The 3-10-10-10-10 pattern was/is just an try to get 43 (which is a prime number) letters divided into nice, not too long slices which I guess would also improve readability.

**Comment by uhoreg** [comment]
#2142 is the issue for improving key verification

**Comment by uhoreg** [comment]
The key has been separated into groups of 4 (plus one group of 3), so I think this is closable now.

**Comment by glaxx** [comment]
Awesome! :+1:
