### ISSUE TITLE
QtWebKit infinite loading.

### ISSUE THREAD

**Issue by commagray** [vector-im/riot-web#3773]
Subj. I'm using [qutebrowser](https://github.com/qutebrowser/qutebrowser/) with QtWebKit backend and can't get to the site. [Debug log](http://termbin.com/vhdr). I mean that:
![screenshot_20170430_084952](https://cloud.githubusercontent.com/assets/27947961/25562015/3e633d88-2d82-11e7-9570-355dbbade942.png)

**Comment by ara4n** [comment]
The browser crashed with:

```
08:31:53 DEBUG    js         webpage:javaScriptConsoleMessage:457 [:0] IndexedDB worker is ready
08:31:54 DEBUG    js         webpage:javaScriptConsoleMessage:457 [https://riot.im/app/bundles/bab0d1f71b846e270316/indexeddb-worker.js:28] ReferenceError: Can't find variable: console
```

and looking at the minimised code, this is:

```
function(t){console.error("Error running command: "+i.command),console.error(t),r.postMessage.call(null,{command:"cmd_fail",seq:i.seq,error:"Error running command"})})}}]),t}();t.exports=l}});
```
which prettied up is:
```
function(t) {
    console.error("Error running command: " + i.command),
    console.error(t),
    r.postMessage.call(null, {
        command: "cmd_fail",
        seq: i.seq,
        error: "Error running command"
    })
})
```

If the browser doesn't give a `console` global for logging to the console when running a web worker (or perhaps it doesn't support webworkers at all?), then pretty much all bets are off, i'm afraid.  I suggest raising it with the qutebrowser folks.
