### ISSUE TITLE
Stuck typing notifications should be impossible

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3774]
I thought the whole point of our typing notification events are that clients need to keep sending them every N seconds in order to keep everyone (local HS, remote HS, remote clients) believing that the client is still typing.

However, empirically it's possible that if ephemeral typing events get lost over federation, riot shows the notif stuck forever.  It seems that we trust our server to time-out lost typing notifs and relay it to the client.  So, either we need synapse to correctly time-out received typing notifs which are no longer firing, or matrix-react-sdk should be timing them out too (in the case the homeserver is missing the logic).

**Comment by lampholder** [comment]
Is this related to #2456?

**Comment by richvdh** [comment]
> Is this related to #2456?

looks like it to me.
