### ISSUE TITLE
Following a matrix.to link when using federation just tells you "no known servers"

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3779]
Which is particularly annoying when I'm following a link in a bug report to a room I'm not in and Riot fails to find me the room (e.g. https://matrix.to/#/!GiBpZSGcdzTfkNXmer:matrix.org/$1493418047567086nulfy:matrix.org )

I'd like my homeserver to at least have a guess at where it might find the room (matrix.org is a good bet).

Perhaps this is linked to the .wellknown stuff (such that we can at least find the homeserver associated with a given domain), but even naively assuming the domain _is_ the homeserver would save me a lot of bother in the common matrix.org case :P

**Comment by lampholder** [comment]
I solve this by using my @toml:matrix.org account to find the room, then join it under @tom:lant.uk

**Comment by uhoreg** [comment]
I think this is essentially the same as #2925

**Comment by lampholder** [comment]
I agree that it is :)
