### ISSUE TITLE
Create a Fedora compatible package

### ISSUE THREAD

**Issue by Lailah** [vector-im/riot-web#3781]
### Description

A desktop app for RPM based systems, such as Fedora and OpenSuse.

### Steps to reproduce

It's a mess to use it on Fedora while it works nicely on Debian.  A RPM package would be greatly appreciated.  Or at least an executable (like Firefox and Telegram).

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Fedora Workstation 25  (fully updated)

**Comment by ara4n** [comment]
ooi does https://copr.fedorainfracloud.org/coprs/taw/Riot/ work?

**Comment by uhoreg** [comment]
https://copr.fedorainfracloud.org/coprs/taw/Riot/ seems to be quite outdated currently

**Comment by TheLastProject** [comment]
As a Fedora user, just voicing my feedback here, this would help tremendously. And yes, @ara4n, https://copr.fedorainfracloud.org/coprs/taw/Riot/ always worked great (while it was maintained), aside from one build missing some emojis.

**Comment by t3chguy** [comment]
@dbkr surely an automated build&release server for Electron builds would be ideal, that way throwing more release types would be a breeze?

**Comment by dbkr** [comment]
I'd definitely like to make a build server but I don't think that helps with more release types: the current build script can spit out more packages just as much as if it were running on a build server. The overhead would be managing where we put the resulting packages, eg. we could just spit out an rpm but then this wouldn't auto-update so we'd presumably do a copr package or something, which is not too difficult but it all incrementally adds to the complexity of the release process.

**Comment by akontsevich** [comment]
Good this ticket is created: nice to have RPM package on openSUSE as well: ring, skype, qtox are present already - only riot-web missed.

**Comment by dani** [comment]
There's also https://copr.fedorainfracloud.org/coprs/ansiwen/Riot/ which is a bit more recent (not tested)

**Comment by TheLastProject** [comment]
To underline the apparent demand for this, Fedora Magazine, which is on the default Firefox homepage on Fedora, mentioned Riot and linked to ansiwen's COPR (which is unfortunately outdated): https://fedoramagazine.org/4-cool-new-projects-try-copr/

**Comment by taw00** [comment]
UPDATED: https://copr.fedorainfracloud.org/coprs/taw/Riot/
Sorry folks. Took a technical (and corporate) leave of absence. I will try to keep a bit more current. :)

**Comment by akontsevich** [comment]
> UPDATED: https://copr.fedorainfracloud.org/coprs/taw/Riot/
Works fine in openSUSE however need to download and install manually, repo does not work for openSUSE.

**Comment by AquaL1te** [comment]
Since there is still no word on official support for RPM based system such as Fedora, RHEL, CentOS, SLES or OpenSUSE. Can we at least get an indication if this is planned for the future, if at all?

And can we please have a stamp of approval for the [Flatpak version?](https://flathub.org/apps/details/im.riot.Riot) Can we consider it as a trusted source? And if not, please advice.

**Comment by jryans** [comment]
> And can we please have a stamp of approval for the [Flatpak version?](https://flathub.org/apps/details/im.riot.Riot) Can we consider it as a trusted source? And if not, please advice.

The Flatpak version seems reasonable to me, since it appears to build from our deb package and add some icons and desktop files. Of course, I can't make any guarantees since we don't publish it ourselves.

**Comment by taw00** [comment]
I *could* build the RPMs from the binaries (that are built for other linuxes). I have done this in the past in testing. But, IMHO that is ... simply "incorrect" packaging. :) Plus, in the end, even those lean heavily on 3-party bits of code that come from free-for-all places like various javascript registries.

Though I have been building RPMs for over two years now as a member of the Riot community. I suppose I could (a) petition to have them somehow become "blessed" by the team (the vector dudes), and (b) pursue getting them included into the Fedora distribution... which is challenging since everything has to build from source to make it into the distro, and Riot uses 1-billion external packages.

Dunno. I do need a "hit by a bus" plan for these RPMs though. Someday, I am sure, they will just suddenly stop being updated... ;)

**Comment by AquaL1te** [comment]
@taw00 I should have more free time in about 6 months. I could then help to co-maintain it for Fedora. Unless of course Flatpak is the "correct" way to package it. Then it would be very nice to advertise it as such on the Riot web page.

**Comment by taw00** [comment]
The "incorrect" thing I am referencing is repackaging binaries built with foreign libraries, on potentially foreign architectures, waving a wand and calling it "Fedora". Whether that be a Flatpak or an RPM. The ideal scenario is to build the application on the distribution that is the target with libraries for the architecture of that target, and that build system is self-contained with no reliance on external repositories... Flatpak vs. RPM is just a fancy word for "zipfile". :) And the RPMs are already advertised ... somewhere. Or at least they used to be.

**Comment by Lailah** [comment]
@taw00  So there is a RPM package?  Where can I find it?  Does it work in Fedora 29 or 30?

**Comment by taw00** [comment]
@Lailah 
> @taw00 So there is a RPM package? Where can I find it? Does it work in Fedora 29 or 30?

https://github.com/taw00/riot-rpm
Yes. EL7, Fedora 28, 29, and 30, OpenSUSE 15 and Tumbleweed.

**Comment by Lailah** [comment]
Cool, thank you! I'm closing this now.

**Comment by Mikaela** [comment]
Is the taw00 package official(ly supported) or why is this issue closed? It's not mentioned on Element website which only has Debian/Ubuntu instructions and I think most of people wouldn't come looking for a GitHub issue.

**Comment by taw00** [comment]
It's not officially supported. It was "blessed" though in the past with a link to it from their website. In fact they linked to several community supplied packages. They stopped that, and I am not sure why. It may be for liability reasons, I don't know. Either that or they are simply trying to steer everyone to flatpak / snap packaging. I will ask.

**Comment by taw00** [comment]
I asked and ... My COPR repository is already linked from the Element website (via install instructions for Fedora and CentOS.

- Goto: https://element.io/get-started#linux
- Click on Linux button
- Note COPR instructions under Fedora and CentOS

Cheers. -t

**Comment by linuxmail** [comment]
hi,

btw: there is [no newer version](https://copr.fedorainfracloud.org/coprs/taw/element/), than `element-1.9.7-1.fc34.taw.x86_64` 

> PROBLEM: The Element source-code ships with non-free code (really, it is the Electron platform's fault).
> PROBLEM: Until I resolve that in some way, I can no longer build this package.
> PROBLEM: Stay tuned.

that is pretty sad. Question is .. how to build an own RPM version for Fedora35 and above.
