### ISSUE TITLE
switching to a room and then mousing out before it finishes loading leaves the menu button visible

### ISSUE THREAD

**Issue by nightpool** [vector-im/riot-web#3782]
![menus](https://cloud.githubusercontent.com/assets/233815/25592877/6778de7e-2e88-11e7-8e8a-243de8c7b7b9.gif)

The chats I was recording the gif with load pretty fast, but if a room takes a long time to load the bug will be much more noticeable. (initially I thought mouseout was just broken entirely, until I tried a room with less history)

### Version information

- **Platform**: web
- **Browser**: chrome
- **OS**: mac
- **URL**: im.cybre.space riot-web version: v0.9.9-rc.1

**Comment by ara4n** [comment]
thanks for the gif & additional repro steps - this is very useful.  we have a bug tracking it as https://github.com/vector-im/riot-web/issues/3672 so going to close as a dup, but this will one will get referred to during the fix.

**Comment by lampholder** [comment]
This looks very much like a duplicate of #3672

**Comment by nightpool** [comment]
@lampholder it was already closed, but thanks.

**Comment by lampholder** [comment]
:P
