### ISSUE TITLE
'X' button on 'Jump to first unread message' bar is hard to see in dark theme

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3783]
as reported by dcg_mx in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14936911012350850Hjzys:matrix.org.  See screenshot in https://matrix.org/_matrix/media/v1/download/matrix.org/fcKVcDllzaUJQjrPDYfnsKxu

**Comment by lampholder** [comment]
It is indeed hard to see:
![image](https://cloud.githubusercontent.com/assets/1922197/25706178/92eed972-30d7-11e7-8032-2b8883904228.png)
