### ISSUE TITLE
Riot can get stuck infinitely bouncing between the RM and the bottom of the timeline

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3787]
**Symptom:** Riot does some mad un/pagination following a combination of "Jump to first unread message" and clicking the button to jump to the live timeline. 

**Cause:** It seems that the room has lost its live timeline completely and the js-sdk just panics and falls in a heap. When that error happens, presumably the scroll state is restored in `ScrollPanel`, bumping the user back to where they were scrolled to before...

`2017-05-02T14:18:37.743Z E Caught /sync error Error: live timeline 0 is no longer live - it has a neighbouring timeline`

https://github.com/matrix-org/riot-web-rageshakes/issues/51 is the related rageshake.

(reported by @AmandineLP )

**Comment by lampholder** [comment]
@AmandineLP/@lukebarnard1 what is the actual user experience of this?

**Comment by lampholder** [comment]
Flagging it P1 until I know more about this :)

**Comment by AmandineLP** [comment]
The timeline was rapidly scrolling to the last message (like when I click on the last message arrow) then back up to the last unread (?), in loop.

**Comment by lukebarnard1** [comment]
I don't think we've seen this reported again so I'm closing this.
