### ISSUE TITLE
Rejoins collapse to 'null'

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3788]
### Description

When bots rejoin rooms, and there are several in a room, their rejoins collapse to be 'null' (see screenshot).

### Steps to reproduce

- Have 3 people/bots rejoin the room

The text should say 'Someone and N others rejoined'.

![image](https://cloud.githubusercontent.com/assets/1190097/25626568/2d58e12c-2f1d-11e7-825b-8e9811bfd3ef.png)
![image](https://cloud.githubusercontent.com/assets/1190097/25626649/7223f9cc-2f1d-11e7-9ca6-0eb936922230.png)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This looks horrible. Nulls in an end product look super sloppy.

P2 only because I expect this turns up fairly infrequently

**Comment by ara4n** [comment]
should be fixed by 2b71123ddcacb103d2338d8d525fd4922d24ff68
