### ISSUE TITLE
The context menu from the room list is not scrollable when displayed at the bottom of the screen

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#3792]
if you open it for a room at the bottom of the list the menu is partially hidden and you have no way to unhide it, you need to close it, scroll the list up then open it again

It should either display upwards or be scrollable

![image](https://cloud.githubusercontent.com/assets/8582858/25653836/88e10a6e-2fe6-11e7-8555-e3a8eaddb776.png)

**Comment by turt2live** [comment]
#3429

**Comment by lampholder** [comment]
#3429 relates to the message menu popup disappearing off the side of the screen (rather than the room menu popup disappearing off the bottom of the screen).

If we can tackle both together by having our popups have better awareness of visibility/screen dimensions that would be great.

**Comment by t3chguy** [comment]
This is no longer the case, it gets moved away from the edge:

![image](https://user-images.githubusercontent.com/2403652/57554041-44d34400-7368-11e9-9c6c-fec579e8c7ae.png)
