### ISSUE TITLE
read avatars can go over the event body when expanded

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#3794]
on a narrow enough viewport and/or with enough read avatars on the event and it isn't immediately obvious how to get them to retract, maybe make an extra avatar-like icon which is a cross at the left of the list when its expanded to signify close/retract or for a large number of read avatars show them in a modal similar to how riot-android shows it

edit, at the extreme they can go past into the timestamp+main avatar part of the chat getting truncated at the left sidebar

**Comment by lampholder** [comment]
Is there an argument for their only expanding on mouse over?

**Comment by t3chguy** [comment]
Duplicate of #3384
