### ISSUE TITLE
Moving rooms from custom tags to 'Rooms' leaves artificial tags (/develop)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3797]
### Description

I use the tag API to add additional tags so I can better organize my fairly large room list. Using these tags up until now didn't cause any major issues with Riot, however now it is possible to end up with a partially-stuck room in Rooms.

### Steps to reproduce

- Join a room such that it lands under 'Rooms' in the sidebar
- Use the tag API to tag that room (in my case, 'EsperNet')
- Click and drag that room back to 'Rooms'
- Open the settings for the room and note the 'im.vector.fake.recent' tag

I would have expected this tag to not be visible to me. It does prevent me from moving the room elsewhere using the quick actions in the context menu (ie: pushing it to low priority without dragging).

Log: sent  

![image](https://cloud.githubusercontent.com/assets/1190097/25672225/e803d1da-2fef-11e7-9bee-14a9bdf3f701.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yuk.

P2 whilst this is only visible to the (relatively few) users using the tag API.

OOI what happens if you uncheck `im.vector.fake.recent`, save and reopen? Is it still visible?

**Comment by turt2live** [comment]
Unchecking it (and hitting save) results in the tag disappearing from the room (much like custom tags - they don't exist in the list unless checked) and the room leaves the Rooms section. It appears to act as a tag that forces it into the 'Rooms' list.

**Comment by turt2live** [comment]
I haven't seen this in recent builds - is anyone still having this issue?

**Comment by turt2live** [comment]
Closing as not an issue
