### ISSUE TITLE
seequ says adding a room to favs doesn't remove from rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3801]
probably shouldComponentUpdate() fail

**Comment by turt2live** [comment]
related/dupe: #3797

**Comment by lampholder** [comment]
High priority because super-glitchy.

If this turns out only to affect tag API users perhaps consider a lower priority.

**Comment by JaniM** [comment]
This was fixed by removing `im.vector.fake.recent`, as per #3797.

**Comment by lampholder** [comment]
Closing as a dupe of #3797
