### ISSUE TITLE
Improvement Suggestion: RSS Bot

### ISSUE THREAD

**Issue by martiniturbide** [vector-im/riot-web#3802]
Hi

I had been trying the RSS Bot and it works fine.  But I noticed that when the RSS feed gets updated with a bulk of 20 news at once, the RSS Bot does his job and flood the chat channel with all the news.

I was wondering if there can be some feature on the RSS Bot to put a delay between each post, and that it can be turn on and select the delay time  in seconds.. 

Regards

**Comment by lampholder** [comment]
I've moved this over to https://github.com/matrix-org/go-neb/issues/178 - go neb is better place to track feature requests for bots :)
