### ISSUE TITLE
Ability to ignore invites

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3805]
If I have an invite i neither wish to accept nor reject, it'd be nice to just have an 'ignore' option in the context menu, which relegates them to Historical or somewhere, never to be seen again unless i really want to.

**Comment by lampholder** [comment]
dup https://github.com/vector-im/riot-web/issues/2341 ?

**Comment by ara4n** [comment]
yup; <--🚔🏍🚓🚇🚀

**Comment by ara4n** [comment]
(which spells crank on my emoji keyboard apparently)
