### ISSUE TITLE
re-add welcome_page option so that folks running their own riots without RTS can have a welcome page

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3806]

**Comment by lampholder** [comment]
@ara4n This would be neat - is there enough information in here for somebody to do this? Is it exposed in a Riot config file rather than the UI?

**Comment by dbkr** [comment]
The `welcomePageUrl` should do this now

**Comment by turt2live** [comment]
(it can - this is what we do)

**Comment by lampholder** [comment]
Excellent; sounds like we can close this.
