### ISSUE TITLE
Zalgo-like text not trimmed when collapsing events

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3807]
### Description

Zalgo-like effects tend to take up a lot of vertical space. Normally Riot does a great job of trimming this text to ensure it doesn't overflow onto other text, however when the name changes are collapsed, it doesn't trim.

### Steps to reproduce

- Change your name to something zalgo-like a couple times
- Note that the collapsed version overflows

I would expect the overflow to not happen.

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/25712212/4674fa78-30ae-11e7-8862-5629e2aa61a3.png)
![image](https://cloud.githubusercontent.com/assets/1190097/25712220/4bfef958-30ae-11e7-9754-5412b0a03e71.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
@lukebarnard1 your MELS needs a

```
display: block;
overflow-y: hidden;
```

or similar :)

**Comment by lukebarnard1** [comment]
I can't repro (on linux Chrome) and the summary already has `overflow-y: hidden` from `.mx_TextualEvent`
