### ISSUE TITLE
Riot Desktop: Option to start Riot minimized to tray

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#3811]
It would be nice to have the option to start Riot Desktop already minimized to the tray, either as an option in settings or as a command line flag. This is useful for automatically starting Riot on login, in which case I would like to have it open but would prefer not to have the main window pop up on the screen.

**Comment by t3chguy** [comment]
Command line flag exists, `--hidden` not sure whether its in master branch yet

**Comment by t3chguy** [comment]
anyway, dup of #3167

**Comment by lampholder** [comment]
Thanks @t3chguy :)
