### ISSUE TITLE
Pulling There was a problem logging in. (HTTP 400)

### ISSUE THREAD

**Issue by ccsouthard** [vector-im/riot-web#3812]
### Description

 I'm attempting to signin with my credentials. I cannot access and I cannot reset password.

### Steps to reproduce

-added credentials
-denied pulled a 400 error

Describe how what happens differs from what you expected.

 

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome 
- **OS**: macOS 
- **URL**: https://riot.im/app/#/login

**Comment by lampholder** [comment]
Hi @ccsouthard:

- do you have an email address associated with your account?
- are you using matrix.org or have you chosen a different homeserver?

**Comment by mitchhentges** [comment]
I also have an issue with this. I'm using matrix.org. The response from the server is:
```
{"errcode":"M_UNKNOWN","error":"Unable to parse phone number"}
```

**Comment by lampholder** [comment]
Sorry you experienced this - @mitchhentges this is a known problem; we have a redesign of the login in the works (https://github.com/matrix-org/matrix-react-sdk/pull/811)

**Comment by lampholder** [comment]
@ccsouthard it sounds like you might have had the same issue as @mitchhentges - I'm going to close this issue but please reopen if you're having different problems :)
