### ISSUE TITLE
Signature of riot-web source code release fails to verify using GnuPG

### ISSUE THREAD

**Issue by timschubert** [vector-im/riot-web#3813]
### Description

Signature of riot-web source code release fails to verify using GnuPG. 

### Steps to reproduce

- Download from the [release-page](https://github.com/vector-im/riot-web/releases])
- Verify using GnuPG.
- While vector has a good signature, riot-web fails to verify.

- Download the release of riot-web [tarball](https://github.com/vector-im/riot-web/archive/v0.9.9.tar.gz) and the [signature](https://github.com/vector-im/riot-web/releases/download/v0.9.9/v0.9.9-src.tar.gz.asc) and the release of [vector](https://github.com/vector-im/riot-web/releases/download/v0.9.9/vector-v0.9.9.tar.gz) and the accompanying [signature](https://github.com/vector-im/riot-web/releases/download/v0.9.9/vector-v0.9.9.tar.gz.asc)

- The SHA256 sums are
```
b8025e97b0da50d6340ada395f9b2d5643b4690df605bbca4fdd005cd79641e5  v0.9.9-src.tar.gz.asc
872210523062011d9b3c21433e1a0b5cb95cdf72850ba516f59ac281c70e90c4  riot-web-0.9.9.tar.gz
209cd3eee841c208dfb8ec1c4558667471b0c4373d87138210205b83f1a7c97b  vector-v0.9.9.tar.gz
9515b252c7f5acbf0dc3c35994346d8e2c8700c76a0b617578b3bbff20f5f83e  vector-v0.9.9.tar.gz.asc
```
 
- Verify using GnuPG
```
$ gpg -v --verify v0.9.9-src.tar.gz.asc riot-web-0.9.9.tar.gz
gpg: armor header: Version: GnuPG v2
gpg: Signature made Tue 25 Apr 2017 12:11:11 PM CEST
gpg:                using RSA key C0FC33162DD2A11D
gpg: using subkey C0FC33162DD2A11D instead of primary key E019645248E8F4A1
gpg: using pgp trust model
gpg: BAD signature from "riot.im (Package Signing key) <packages@riot.im>" [unknown]
gpg: binary signature, digest algorithm SHA256, key algorithm rsa4096
```
```
$ gpg -v --verify vector-v0.9.9.tar.gz.asc vector-v0.9.9.tar.gz
gpg: armor header: Version: GnuPG v2
gpg: Signature made Tue 25 Apr 2017 12:11:01 PM CEST
gpg:                using RSA key C0FC33162DD2A11D
gpg: using subkey C0FC33162DD2A11D instead of primary key E019645248E8F4A1
gpg: using pgp trust model
gpg: Good signature from "riot.im (Package Signing key) <packages@riot.im>" [unknown]
gpg:                 aka "riot.im (Debian signing key) <packages@riot.im>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6FEB 6F83 D48B 9354 7E7D  FEDE E019 6452 48E8 F4A1
     Subkey fingerprint: FA9E E1AE 9F4F 22CD 7B4F  4499 C0FC 3316 2DD2 A11D
gpg: binary signature, digest algorithm SHA256, key algorithm rsa4096
```
**Notice that while riot-web fails to verify, vector does not.**

**Expected**: Both vector and riot-web produce valid signatures.

Log: not sent    

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 0.9.9 
- **GnuPG Version**: gpg (GnuPG) 2.1.20
- **libgcrypt Version**: libgcrypt 1.7.6

**Comment by dbkr** [comment]
You seem to be trying to verify a `.tar` file but the signature is for a `.tar.gz`? I'm not sure where the tar file is from: we only offer the precompiled version as `.tar.gz` and github offers the source as `.tar.gz` or `.zip`. Has your computer tried to be helpful by un-gzipping the file for you?

The original issue is quite old now but both sigs verify correctly for me now.

**Comment by aaronraimist** [comment]
Oh yep you are correct, my browser was unzipping it to a `.tar`. The signature looks good.

```
⟩ gpg -v --verify riot-v0.17.8.tar.gz.asc riot-v0.17.8.tar.gz
gpg: armor header: Version: GnuPG v2
gpg: Signature made Mon Dec 10 07:50:42 2018 CST
gpg:                using RSA key C0FC33162DD2A11D
gpg: Note: signature key C8800C52878D735B expired Sat Dec 22 11:26:42 2018 CST
gpg: using subkey C0FC33162DD2A11D instead of primary key E019645248E8F4A1
gpg: Note: signature key C8800C52878D735B expired Sat Dec 22 11:26:42 2018 CST
gpg: using pgp trust model
gpg: Good signature from "riot.im (Package Signing key) <packages@riot.im>" [unknown]
gpg:                 aka "riot.im (Debian signing key) <packages@riot.im>" [unknown]
gpg: Note: signature key C8800C52878D735B expired Sat Dec 22 11:26:42 2018 CST
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6FEB 6F83 D48B 9354 7E7D  FEDE E019 6452 48E8 F4A1
     Subkey fingerprint: FA9E E1AE 9F4F 22CD 7B4F  4499 C0FC 3316 2DD2 A11D
gpg: binary signature, digest algorithm SHA256, key algorithm rsa4096
```

**Comment by dbkr** [comment]
OK good - since this appears to be working I'll close this.
