### ISSUE TITLE
Option to suppress notification bodies

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3814]
On all platforms, having option not to show message contents in desktop and mobile push notifs is desirable for privacy (especially on web when screensharing, etc)

**Comment by t3chguy** [comment]
Maybe per-room

**Comment by alallier** [comment]
Would also be nice to have every room suppress the bodies on the lock screen like in Windows. So that way if you lock your computer and walk away from it people can't read your personal messages

**Comment by t3chguy** [comment]
looking at the source code of Mattermost they don't differentiate between lock screen notifications and normal ones, I do not see any such possibility in Electron

**Comment by t3chguy** [comment]
https://github.com/mattermost/desktop/blob/544a2434d73b28d78b90c1430214987337037226/src/browser/js/notification.js fwiw

**Comment by t3chguy** [comment]
actually: https://github.com/felixrieseberg/electron-notification-state

**Comment by alallier** [comment]
I'm not sure how they do it but the functionality exists. Any message on the lock screen is masked and hidden.

**Comment by t3chguy** [comment]
I actually can't figure out how Mattermost does it :L

**Comment by ara4n** [comment]
fixed by https://github.com/vector-im/riot-web/pull/4988 - thanks @t3chguy.  Although it bugs me that MM has a better soln and we don't know how!
