### ISSUE TITLE
Riot shows notification "Listening for events" on Android, which cannot be removed or marked as read

### ISSUE THREAD

**Issue by bamstam** [vector-im/riot-web#3820]
### Description

Riot shows notification "Listening for events" on Android, which cannot be removed or marked as read

### Steps to reproduce

- update to riot version 0.6.9 (FDroid-1866137)
- Riot shows notification "Listening for events" on Android (see screenshot)
- notification cannot be removed or marked as read, stays forever in Android notifications

Log: not sent?    

### Version information

- **Platform**: Android 4.4.2

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y 

![screenshot_2017-05-05-12-09-12](https://cloud.githubusercontent.com/assets/9203888/25754046/26b61f9e-31be-11e7-968c-75d3dc1917c1.png)

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-android/issues/1058 is the issue tracking this

**Comment by lampholder** [comment]
Actually, I'm going to close this here in favour of exclusively tracking this riot-android specific issue on the riot-android specific repo (not to discourage people from filing general Riot things here, just to encourage tracking ongoing progress in the right place)
