### ISSUE TITLE
Option to have fully-scrollable left sidepanel instead of stacking

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3824]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=44886366)](https://www.bountysource.com/issues/44886366-option-to-have-fully-scrollable-left-sidepanel-instead-of-stacking)

### Description

A result of fixing https://github.com/vector-im/riot-web/issues/3670 ended up being a bug which I abuse to use Riot a little better. When you resize Riot to be smaller, and then maximize it again, the LHS allows you to scroll instead of stacking your custom tags at the bottom, eating up a lot of your screen.

As much as I'm not a fan of "add another setting", this is probably best put behind a setting due to different uses of Riot. 

As a little background: I have a lot of custom tags, which riot-web thankfully supports gracefully. Navigating the tags works nicely on my portrait monitor, however the landscape monitor makes it less than ideal to navigate rooms.

Here's what my sidebar looks like (exaggerated):
![image](https://cloud.githubusercontent.com/assets/1190097/25756594/88dcf812-3184-11e7-8ce6-13a0ed1e2742.png)

Here's the 'easier to navigate' version (some sections intentionally collapsed):
![image](https://cloud.githubusercontent.com/assets/1190097/25756643/bf2e94fc-3184-11e7-9cd3-d06381aef3d9.png)

Ideally the behaviour in the second screenshot would be behind a setting, so that people who want the stacking behaviour can keep it.

Having scrolling does mean that badges for rooms disappear, making pings/unread messages harder to find. This could be combated by having sticky headers for rooms that have badges, maintaining the 'click to go to that tag' behaviour. Only rooms with badges would stick to the top/bottom, stacking as needed.

Because it's technically a bug, here's the steps to reproduce the scrolling LHS panel:
* Have riot-web at a size where the LHS is expanded
* Shrink the window's width so the LHS collapses
* Expand the window's width so the LHS expands again
* You now have a scrollable LHS

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Some have asked what I mean by this, so I present a less-than-optimal diagram:
![image 2](https://cloud.githubusercontent.com/assets/1190097/26071113/405c7152-3964-11e7-9b17-5fb2bbd3053b.png)

**Comment by turt2live** [comment]
Updated the OP to advertise the bounty :)

**Comment by remram44** [comment]
Is this still being considered? I had to deploy 0.17.9 for myself when 1.0 came out because the left panel is completely unusable:

![screenshot](https://user-images.githubusercontent.com/426784/61136677-e1a18300-a478-11e9-8c73-a73d8416474b.gif)

**Comment by toger5** [comment]
This would be sooo great if it gets fixed. The current behaviour is very annoying

**Comment by turt2live** [comment]
We made a fully scrollable list now.

**Comment by toger5** [comment]
Guys you are sooo amazing! I love the new element! It is so beautiful!
