### ISSUE TITLE
Use webcam for taking photo's in the desktop client

### ISSUE THREAD

**Issue by rghvdberg** [vector-im/riot-web#3828]
### Description

- Option to use a webcam as photo camera in the desktop client (riot-web)

### Steps to reproduce
- None

Describe how what happens differs from what you expected.
- I would expect a `Take photo or video` option in the `send files` dialog, i.e. the same experience as the Android app.

Log: not sent   

### Version information

- **Platform**:desktop
- **OS**: Ubuntu
- **Version**:  0.9.8

**Comment by t3chguy** [comment]
Duplicate of #3423
