### ISSUE TITLE
Auth users by REMOTE_USER env var somehow

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3830]
A common req is to auth Riot users based on upstream HTTP Auth that sets a REMOTE_USER env var. This is tricky as Riot is entirely clientside and can't see serverside vars, but we could have a snippet of PHP or similar serverside which picked up the variable and somehow mixed it into the auth flow.

**Comment by Josue-T** [comment]
Hello,

I'm going see about making a patch to support the sso auth for the [yunohost package](https://github.com/YunoHost-Apps/riot_ynh). The idea is to make a php script witch get the access_token from the matrix server and send it to the browser.
So the authentication process will look like that : 
- If the browser don't have already a access token he call the php script.
- The php script get an access token from the server and return it to the browser. The php script can get the authentication data (user/password) from the web server header.
- The browser receive the access token save it and show the riot home page.

Do you have any advice to help me to make this patch.

**Comment by Josue-T** [comment]
Hello,

I have found a way to add the sso for yunohost. The yunohost package (with the patch) is available here : https://github.com/YunoHost-Apps/riot_ynh

Just some some explaination how I did this : 

- I made a php script witch provide an access_token. It get this by calling the default homeserver (set in config.json), and it use the webserver header to get the username and password. This script is available here : 
https://github.com/YunoHost-Apps/riot_ynh/blob/master/sources/get_user_token.php
- I made a patch witch force the browser to try to get the access token (call the php script) before to show the login page. This part of code is available here : https://github.com/YunoHost-Apps/riot_ynh/blob/master/sources/bundle_patch.js
This part of code is actually added by a custom script (available here https://github.com/YunoHost-Apps/riot_ynh/blob/master/scripts/_common.sh#L34-L64 ) witch modify the minified code.
In the source it should be added here : 
https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/structures/MatrixChat.js#L412-L414

**Comment by richvdh** [comment]
this sounds like a thing that is handled by the SSO flow nowadays.
