### ISSUE TITLE
Improved communication to recipient that the sender didn't want you to see their message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3831]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=44913209)](https://www.bountysource.com/issues/44913209-improved-communication-to-recipient-that-the-sender-didn-t-want-you-to-see-their-message)

### Description

Ran into an issue in #megolm where a user turned on the "don't send to unverified devices" box. Because their messages were unable to decrypt, I sent a rageshake. Only after the rageshake was sent was it indicated to me that the user chose to not send keys to me.

With the understanding that it's hard to determine a user having checked that box, it would still be very much appreciated if it was visible in Riot that the message was intentionally blocked from view, instead of appearing as a generic issue.

Suggestions in #megolm to help counteract this also include having an option for the room to disable that setting, for public encrypted rooms like #megolm.

### Steps to reproduce

- Be in an encrypted room with someone
- Have them turn on "Don't send to unverified devices"
- Have them double check that your device is not verified
- Have them send a message to you

I would expect some kind of message along the lines of "This message cannot be decrypted because the user does not trust your device" instead of "The user has not sent us keys for this device" (the generic "It's broken" error).

Log: sent    

(although the rageshake sent is probably invalid)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
> Suggestions in #megolm to help counteract this also include having an option for the room to disable that setting, for public encrypted rooms like #megolm.

One issue with having a flag like that is that a server admin could impersonate a room admin and set the flag without users realizing it, which could cause them to encrypt to unknown devices without realizing it.  So if there is a flag like that, it should only be allowed to be set at room creation time.

**Comment by ara4n** [comment]
(these made it to rageshake as https://github.com/matrix-org/riot-ios-rageshakes/issues/17 ftr)

**Comment by turt2live** [comment]
Updated the OP to advertise the bounty :)

**Comment by uhoreg** [comment]
This is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1135  (And since I'm on the team, I'm not eligible to collect the bounty.)
