### ISSUE TITLE
We don't check for indexeddb support in modernizr

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3833]
and Safari 8 has no indexeddb apparently, so the app crashes and spins forever during launch :(

**Comment by lampholder** [comment]
Also we should be screening Safari 8 anyway as per: https://github.com/vector-im/riot-web/issues/3833

We should tackle this and https://github.com/vector-im/riot-web/issues/3833 simultaneously.

**Comment by ara4n** [comment]
fixed in 8e2e6ce, which will then automagically kick out Safari 8 as a result of requiring indexeddb.
