### ISSUE TITLE
Scalar has some interesting lines through it

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3834]
### Description

See screenshot. There are diagonal lines across the view.

### Steps to reproduce

- Open integrations menu

Describe how what happens differs from what you expected.

Log: not sent

![image](https://cloud.githubusercontent.com/assets/1190097/25778520/6f78bc1e-32bd-11e7-89c2-781775e6c6c3.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
how very strange. looks like that might be graphics driver bugs playing badly with Chrome's HW acceleration.  Can you try it with Chrome HW acceleration turned off, and if that fixes it, what graphics driver & version you're using?

. o O ( 3dfx voodoo 1 )

**Comment by turt2live** [comment]
Chrome is a strange thing, apparently.

Restarting chrome resolved the issue, even without hardware acceleration. I'm going to go ahead and place blame on https://github.com/turt2live/matrix-voyager-bot/issues/96 because only after voyager kills Chrome does the effect appear. 

Probably some weird Chrome voodoo indeed.

fwiw: Using nvidia's game ready driver v378.78
