### ISSUE TITLE
[UX] Focus text input on key press

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#3841]
(See Slack for an example, but the idea is implemented in several IM applications)

If the focus is not on an input text field, starting typing on the keyboard should automatically set the focus on the message bar.

### Version information

- **Platform**: both web and desktop

For the web app:

- **Browser**: all
- **OS**: all

For the desktop app:

- **OS**: all
- **Version**: 0.9.9

**Comment by uhoreg** [comment]
dup of #435
