### ISSUE TITLE
We no longer warn users that they must specify an email address if they want password reset to work (was: Password reset via msisdn)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3844]
Do we even want this, given how easy SS7 hijacks are?

**Comment by lampholder** [comment]
I don't think we want this for a few reasons:
1. it's introducing an unnecessary attack vector
1. it's introducing an operational dependency on successful SMS delivery - it's one thing to succeed/fail to link a matrix id with a MSISDN based on the vagaries of international SMS delivery, quite another to have access to somebody's living account be blocked behind intermittent one-way connectivity to India

The only reason we would need to support this would be if we had (and wanted to support) a class of user who was only ever willing to associate a msisdn but not an email address with their mxid. Is there any such person?

**Comment by ara4n** [comment]
It was such a person who raised this with me yesterday :)  "I signed up with my phone number, but i've forgotten my password. Help?"

**Comment by lampholder** [comment]
Crucially, is that a person who didn't set an email, or who _wouldn't_ set an email?

If it's just _didn't_ then we can mitigate this by adding UX to encourage such users to set a password-reset-friendly 3pid.

I was wondering if there was a class of users who for some reason _wouldn't_ set an email address for some reason.

**Comment by ara4n** [comment]
It's a person who didn't set an email.  So yes, we can probably mitigate this a bit via UX.

**Comment by ara4n** [comment]
This turns out to be a regression: we're meant to be warning with a dialog that you can't reset your password if you try to sign up without an email address, but the dialog has either gone missing or is spontaneously clearing itself :(

**Comment by ara4n** [comment]
This has now regressed even further, comically, on ILAG, where we're no longer letting users set an email address at all(!) - thus meaning they have no way to reset their password, receive notifs, etc.

Luke is adding an additional dialog into ILAG after the set password prompt to specify the email address.

**Comment by lukebarnard1** [comment]
Fixed for ILAG flow by https://github.com/vector-im/riot-web/pull/4301 but we still don't warn for the registration page flow.

**Comment by dbkr** [comment]
Removing release-blocker because it's fixed for the ilag flow.

**Comment by ara4n** [comment]
empirically i saw this working on normal registration too last night
