### ISSUE TITLE
Differentiate between 'failed to share keys' and 'recipient is blocked'

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3845]
Add a way for the recipient to distinguish 'the sender failed to send to you' vs 'the sender chose not to send to you' (either they blocked you or your device explicitly, or because they had the 'Never send encrypted messages to unverified devices from this device' setting (matrix-org/matrix-js-sdk#336) checked).

-- basically we should be able to distinguish between "it went a bit wrong" and "expected behaviour".

Of course that would probably mean the sender sending a "you're blocked' notification to the recipient, but that wouldn't be hard.

**Comment by uhoreg** [comment]
dup of #3831

**Comment by richvdh** [comment]
so it is
