### ISSUE TITLE
Implement solid-line chevron for roomlist hints

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#3847]
For rest of https://github.com/vector-im/riot-web/issues/3609

 * Chevrons on dashed-border hint boxes
 * Images for smaller versions of buttons (as the svg versions end up with <1px lines when scaled down to the lower size)

**Comment by lampholder** [comment]
After discussion, we agreed to an easier-to-implement solid line. The scope of this task is now just to do implement the solid line chevron, since we're reverting the small-icon change.

**Comment by lampholder** [comment]
After yet more discussion, we're removing the buttons from the roomlist section headers, so there's nothing for a chevron to point at, so there's no reason to go with a solid line over a dashed one. CASE CLOSED.
