### ISSUE TITLE
Device list sidebar is misleading

### ISSUE THREAD

**Issue by vext01** [vector-im/riot-web#3852]
### Description

The device list sidebar is misleading:
![ya](https://cloud.githubusercontent.com/assets/604955/25808657/b036a6bc-3402-11e7-9afc-8808d90159cf.png)

I thought that the horizontal rules were separating the devices, but really the rule separates the device name from the corresponding buttons. As a result I've verified the wrong devices!

Also, when I verified, the device IDs in brackets disappeared, making further verification hard.

### Steps to reproduce

Click on your avatar in riot web.

### Version information

chromium-58.0.3029.81/OpenBSD

riot.im/app

**Comment by lampholder** [comment]
Also identified in https://github.com/vector-im/riot-web/issues/3678, but I'll leave this here because this is an instance of the dividing lines leading to actual user problems.

**Comment by uhoreg** [comment]
This is fixed in the redesign
