### ISSUE TITLE
People header remains highlighted after closing it

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#3853]

**Comment by erikjohnston** [comment]
![screenshot from 2017-05-08 15-38-02](https://cloud.githubusercontent.com/assets/8428120/25809294/6f383bc4-3404-11e7-8c5f-ec0504fb7361.png)

**Comment by turt2live** [comment]
This is apparently a feature: https://github.com/vector-im/riot-web/issues/3630

**Comment by lampholder** [comment]
Since this is a feature, I'm going to close this :)
