### ISSUE TITLE
jump to first unread message jumps to the same point every time at /develop/#/room/#freenode_#trueos:matrix.org

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#3854]
## Steps

1. click the `#trueos` room at https://riot.im/develop/#/room/#freenode_#trueos:matrix.org

2. observe the green line above https://matrix.to/#/!rlkOZoHZqtNXEQHzjY:matrix.org/$1493236148351786iPjrJ:matrix.org

> danboid (IRC) joined the room.

3. read

4. click the `#pcbsd` room at https://riot.im/develop/#/room/#freenode_#pcbsd:matrix.org

5. again, click the `#trueos` room at https://riot.im/develop/#/room/#freenode_#trueos:matrix.org

## Expected

- the green line should appear below the read messages

## Actual result

- the green line reappears in the same place

## Logs

I'll send them with reference to this issue. 

## Environment

> matrix-react-sdk version: 9cae667c063e67b32e60b89e7256d714a056559b
> riot-web version: 2983b36d4c18-react-9cae667c063e-js-6021c1c6b11d
olm version: 2.2.1

53.0 (64-bit) 

```text
$ about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
       after restart (R) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    number of cores ……………… 4
host ……………………………………………………… momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
memory ………………………………………………… 16384 MB available, 8398 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… a009033ff
OS kernel build time ………………………………………………………… Wed 2017 Mar 29 20:13:33 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… CUSTOM
TrueOS version …………………………… TrueOS-Desktop-201703201429
uptime ………………………………………………… 1:32
user  …………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …… KDE
    sound card driver ………… pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> on hdaa1  (1p:1v/1r:1v) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… intel_drv.so 

$ 
```

**Comment by turt2live** [comment]
IRC rooms don't allow us to see history, unless we're already part of the room. However I'm suspecting you're seeing something similar to the following:
![image](https://cloud.githubusercontent.com/assets/1190097/25815507/f0bbf824-33dd-11e7-9f27-c58f250150be.png)

where there's a green line (read marker) above some number of collapsed events (in my case, 175 joins + other stuff). 

I can't for the life of me find the issue for this, but the MELS prevents read receipts from being sent. Much like part of the issue in #3561. 

A temporary solution is to gather enough events in the MELS (collapsed thing) so that expanding causes the 'Jump to unread message' banner, then dismissing the banner. Sending a message also works.

... unless of course I'm completely wrong and you see some other issue.

**Comment by lukebarnard1** [comment]
I've seemingly reproduced a stuck RM for a reason totally separate to MELs. I've got a fix and will push tomorrow.

**Comment by lukebarnard1** [comment]
@grahamperrin, @turt2live, has this problem gone away?

**Comment by turt2live** [comment]
@lukebarnard1 I keep seeing the RM above the MELS, but I haven't had "always stuck in the past" for a while.

**Comment by grahamperrin** [comment]
At https://riot.im/develop/#/room/#freenode_#ghostbsd:matrix.org the first unread message is repeatedly 2017-05-23. I page down, there reappears the prompt to jump to the first unread message. Looping.

**Comment by grahamperrin** [comment]
… later, in that room I clicked the close icon without realising that it treats all unread messages as read.

**Comment by lukebarnard1** [comment]
@grahamperrin this sounds like https://github.com/vector-im/riot-web/issues/4134

**Comment by grahamperrin** [comment]
> jumps to the same point every time 

In recent weeks, as far as I recall, I have not observed that symptom in any room.
