### ISSUE TITLE
If you specify multiple HSes in roomDirectory in config.json, RoomDirectory always loads the local HS first (but mislabels it)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3855]
We have a regression that you used to be able to configure your Riot's config.json to know about various alternative room directories - e.g. other HSes, other bridges room directories, etc.  We appear to have lost this entirely.

**Comment by lampholder** [comment]
@ara4n - do you remember how far back this feature existed?

**Comment by ara4n** [comment]
It was added in 761600f3253140f77248b184f78aaee38750224d and I thought it regressed in f5bd8abfdac612b4fddad343b92c31db86302b33, although the commit implies that the functionality still exists.  It's just that it's undocumented and nobody's using it.  Also it's confusing that riot's production config.json still uses the old config file syntax (which i /think/ is obsolete).

Having played a bit more, i think this is actually a combination of a #3327 (room dir unusably slow over federation), and a new issue that if you specify a different HS as your primary DS, riot doesn't pick it up when you load the directory and instead shows your local HS's directory, but mislabels it as your primary DS.  I'll change the bug appropriately.

**Comment by aaronraimist** [comment]
It works properly now
