### ISSUE TITLE
Formatting issue on old redacted(?) e2e event

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3858]
### Description

This happened a while ago.
![image](https://cloud.githubusercontent.com/assets/1190097/25816743/53b24aba-33e2-11e7-9faf-4a8498693623.png)
Event: https://matrix.to/#/!UCnwUWwIKhcpaPTHtR:sw1v.org/$14912480902388472OVaKX:matrix.org

Event source (encrypted):
```
{
  "origin_server_ts": 1491248172944,
  "sender": "@Add:matrix.org",
  "event_id": "$14912481722389309Rozsz:matrix.org",
  "age": 3015983451,
  "unsigned": {
    "age": 3015983451,
    "redacted_by": "$14912574832496428jaZMn:matrix.org",
    "redacted_because": {
      "origin_server_ts": 1491257483452,
      "sender": "@Add:matrix.org",
      "event_id": "$14912574832496428jaZMn:matrix.org",
      "age": 3006672943,
      "unsigned": {
        "age": 3006672943
      },
      "content": {},
      "redacts": "$14912481722389309Rozsz:matrix.org",
      "room_id": "!UCnwUWwIKhcpaPTHtR:sw1v.org",
      "user_id": "@Add:matrix.org",
      "type": "m.room.redaction"
    }
  },
  "content": {},
  "room_id": "!UCnwUWwIKhcpaPTHtR:sw1v.org",
  "user_id": "@Add:matrix.org",
  "type": "m.room.encrypted",
  "redacted_because": {
    "origin_server_ts": 1491257483452,
    "sender": "@Add:matrix.org",
    "event_id": "$14912574832496428jaZMn:matrix.org",
    "age": 3006672943,
    "unsigned": {
      "age": 3006672943
    },
    "content": {},
    "redacts": "$14912481722389309Rozsz:matrix.org",
    "room_id": "!UCnwUWwIKhcpaPTHtR:sw1v.org",
    "user_id": "@Add:matrix.org",
    "type": "m.room.redaction"
  }
}
```

Event source (decrypted):
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: Unknown encryption algorithm \"undefined\". **"
  }
}
```

Not sure if there's anything to do, but it does look strange.

Note that this does not happen for redactions now. Unsure of what happened to that event (and the surrounding events - see permalink)

### Steps to reproduce

 Unsure

Log: sent (references this issue)    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
https://github.com/matrix-org/riot-web-rageshakes/issues/82

**Comment by uhoreg** [comment]
dup of #3744

**Comment by turt2live** [comment]
Couldn't find that issue in my searching, apologies. 

Although it doesn't happen currently with newly-redacted messages. Suspecting something else is breaking it.
