### ISSUE TITLE
Decrypting a redacted message leads to error message

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#3861]
See screenshot:

![2017-05-09 10_54_28-riot](https://cloud.githubusercontent.com/assets/1236369/25845928/1fe45db2-34b0-11e7-96c7-68bbd75f999e.png)

Text for searchability: `** Unable to decrypt: Unknown encryption algorithm "undefined". **`

**Comment by uhoreg** [comment]
dup of #3744

**Comment by richvdh** [comment]
thanks uhoreg
