### ISSUE TITLE
Allow disabling "seen by" individually

### ISSUE THREAD

**Issue by csoriano89** [vector-im/riot-web#3867]
### Description

Other people can see if I read the message in the public channels, and unfortunately that's used as in "why you ignore me", unfortunately pretty common in environments like IRC.

I expect to be able to disable this, so the server doesn't communicate when I was "looking" at the room or not.

**Comment by turt2live** [comment]
You're probably waiting for the PR here: https://github.com/matrix-org/matrix-react-sdk/pull/821

Which is blocked by https://github.com/vector-im/riot-meta/issues/66

(I'm not sure if there's already a riot-web issue for this, just thought I'd leave a comment with a little bit of an update)

**Comment by lampholder** [comment]
Thanks @turt2live - I think https://github.com/vector-im/riot-web/issues/2527 is the riot web issue for this. Closing this one as a dup :)
