### ISSUE TITLE
desktop (electron) clients have no autostart feature

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3870]

**Comment by t3chguy** [comment]
does Linux?
I was toying with https://www.npmjs.com/package/auto-launch at one point with riot-web, got it to work but wanted a more generic interface for Electron to expose additional settings for Riot to show

In Windows for instance putting the shortcut in Autostart works, no idea for Mac
How do you propose this is done UX wise?

Could be in the menu bar but we don't show that by default so wouldn't be too user-friendly

**Comment by lampholder** [comment]
I haven't the foggiest :)

I've picked up rageshake triaging, so you can expect to see me filing a selection of issues I don't have a huge amount of context on for the next hour or so :P

**Comment by t3chguy** [comment]
fair enough, I believe it does not (nothing about riot-web autostarts anywhere basically)
we now have the structure to easily add deps for the electron main process so its relatively easy, just needs input on UI

**Comment by t3chguy** [comment]
This is now a thing
