### ISSUE TITLE
Room is spuriously highlighted in room list

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#3872]
![screenshot from 2017-05-10 11-45-35](https://cloud.githubusercontent.com/assets/8428120/25895069/426afe42-3576-11e7-8f3a-b26ef84a7001.png)

Note how I am looking at offtopic, the Peoples section is highlighted (as i just closed it), but Vector iOS is also highlighted

**Comment by ara4n** [comment]
going to be another shouldComponentUpdate race with the optimised RoomList :(

**Comment by turt2live** [comment]
should be fixed in the new new room list
