### ISSUE TITLE
Room settings 'tagged as: favourite / low priority' options are checkboxes (but they're really radio boxes)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3876]
These options are mutually exclusive but represented as checkboxes.

I wouldn't be surprised if this had been captured elsewhere.

**Comment by grahamperrin** [comment]
Today's screenshot at https://github.com/vector-im/riot-web/issues/4975#issuecomment-327388316 exemplifies a case where the third item in the row of tags _probably_ **must not** be a radio button.

**Comment by turt2live** [comment]
They've been removed.
