### ISSUE TITLE
Adding email addresses and msisdns is not super intuitive.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3887]
![image](https://cloud.githubusercontent.com/assets/1922197/25945550/36f5260e-363f-11e7-9d03-1da40bc015f5.png)

Where do you click on the above UI to start adding a new phone number or msisdn?

If you click on the `+` you're rewarded with a crap error:
- `Invalid Email Address` in the case of email, and 
- `Unrecognized request (Status 400)` in the case of the msisdn

There's a few problems:
- The email address field doesn't look like a text field _at all_.
- The msisdn one is a bit better, but it still doesn't look like the other text fields on the same page.

**Comment by turt2live** [comment]
The UX is different but can be improved. Closing as the issue described here is fixed.
