### ISSUE TITLE
File panel spins infinitely when peeking

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3889]
`Failed to get or create file panel filter ... MatrixError ... "M_GUEST_ACCESS_FORBIDDEN"`

Should probably just display some text like "No files"

**Comment by lampholder** [comment]
![image](https://cloud.githubusercontent.com/assets/1922197/26001544/9f22fc8e-3724-11e7-9e3e-e792d9d87d88.png)

**Comment by lampholder** [comment]
It shouldn't spin, but I also don't think it should say "No files" - your not being able to see any files is not the same as there not being any :)

If the truth is that you can't see the files because you're peeking, then it should say something informative and true like 'Join this room to see files'.

**Comment by t3chguy** [comment]
@lampholder what about for guests that are in the room?
```
VM46 bundle.js:59088 Failed to get or create file panel filter 
MatrixError {errcode: "M_GUEST_ACCESS_FORBIDDEN", name: "M_GUEST_ACCESS_FORBIDDEN", message: "Guest access not allowed", data: Object, httpStatus: 403}
```

**Comment by lukebarnard1** [comment]
Maybe we should just hide the  ![2017-05-12-160715_39x54_scrot](https://cloud.githubusercontent.com/assets/6750344/26004253/13c330ec-372d-11e7-8b26-72554649eb8d.png) if the user is a guest? Because it looks like it doesn't matter if the guest is joined or peeking.

**Comment by t3chguy** [comment]
only for Guests?
then a message to join the room if you're not in it first or hide for both?

**Comment by t3chguy** [comment]
looks like same happens for guests and the notifications panel
```
MatrixError {errcode: "M_GUEST_ACCESS_FORBIDDEN", name: "M_GUEST_ACCESS_FORBIDDEN", message: "Guest access not allowed", data: Object, httpStatus: 403}
```

**Comment by ara4n** [comment]
as per commentary on #3907 i don't think we should be hiding the file button for guests. however, showing the error if (for whatever reason) the FilePanel is unavailable effectively fixes this anyway :)

**Comment by t3chguy** [comment]
@ara4n I don't believe so, my fix only caught if there was no room, a guest can't make use of Filters so even when they're in a room it'll error. I'll double check and extend a similar fix. Re-opening until then
