### ISSUE TITLE
Create Room dialog doesn't resize

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3891]
![2017-05-11-162807_546x369_scrot](https://cloud.githubusercontent.com/assets/6750344/25957906/42d86b2a-3667-11e7-81b5-91772309d45d.png)

**Comment by lampholder** [comment]
@lukebarnard1 you mean when the browser resizes, right?

**Comment by lukebarnard1** [comment]
@lampholder not necessarily, the browser window might just be small (e.g. on a small screen)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/41338340-ce843396-6ee9-11e8-9a45-4c3486e871ed.png)
removed fixed sized, realigned and et voila
