### ISSUE TITLE
Compress the country+msisdn picker down to a single line

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3895]
![image](https://cloud.githubusercontent.com/assets/1922197/25962482/df509fe6-3675-11e7-90f8-11adb75aab0e.png)

Points to note:
- flags are actually square
- country names have country codes after them to both:
    - reinforce that we're doing this for the phone number
    - allow the user to search by country code as well as country name
- the country picker and the phone number field should both be similarly styled, so that it's obvious that they are both there to be interacted with/completed
- +447700900000 is a reasonable placeholder because it is a drama range number
    - we might rethink this in future, but it's probably fine for now

**Comment by lampholder** [comment]
- helps with https://github.com/vector-im/riot-web/issues/3893
- avoids the sense that we're collection user country information for no reason

**Comment by lukebarnard1** [comment]
Searching by country code does work but it doesn't strip the initial "+" if you happen to enter one. This breaks the search which assumes you haven't put a "+".

IRL @lampholder and I discussed that the dropdown can be much smaller that 50% but in practice this is a parameter that can be altered with minimal CSS anyway (once the above design is implemented),

**Comment by lukebarnard1** [comment]
Next up:
 - [ ] Actually use square flags (from https://github.com/gosquared/flags)
 - [ ] Put the chevron on the left
 - [ ] Change background colour to white
