### ISSUE TITLE
We should encrypt m.room.name, m.room.topic and m.room.avatar on E2E rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3898]
Even though we don't have a generic way of encrypting state events, we should really make a special case for these guys (perhaps gossiping the AES key for them between participants?), otherwise users would be forgiven for thinking that the name/avatar/etc is encrypted when the big padlock is on.

**Comment by uhoreg** [comment]
OK, so I'm really bad at this "[this is my last comment for the night](https://github.com/vector-im/riot-web/issues/415#issuecomment-301658500)" stuff, but this is a dup of #3410
