### ISSUE TITLE
When user settings can't be loaded, we get an infinite spinner

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3900]
### Description

When user settings can't be loaded due to "Server may be unavailable or overloaded", then we get an infinite spinner.

### Steps to reproduce

- [wait for matrix.org to die](https://matrix.org/blog/2017/05/12/update-on-matrix-org-homeserver-reliability/) 😛  (looking at the debugging tools when I perform the next step, matrix.org is sending a "500 Internal Server Error" in response to the `/profile/%40uhoreg:%3Amatrix.org` and `/account/3pid` requests)
- click on user settings button
- see error dialog 
![image](https://cloud.githubusercontent.com/assets/1012976/25980577/79e29ee8-369d-11e7-82f5-c10474d2c8fb.png)
- click on either the "X" button or the OK button
- see UI greyed out and spinner spinning forever (fortunately, the room tiles are still clickable, so I can get out)

Describe how what happens differs from what you expected.

I would expect that after hitting "X" or OK, it would bring be back to the view that I had before.

Log: not sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.9

**Comment by turt2live** [comment]
I'm cautiously going to say this is fixed because the settings load from cache where possible, with spinner otherwise. Error handling *should* be present but not great.
