### ISSUE TITLE
feature request: Remember scroll position for convos

### ISSUE THREAD

**Issue by muzirian** [vector-im/riot-web#3904]
It would be nice to keep scroll position of a conversation even if we changed the view  to another conversation,for the current session atleast.
Like if we are going to lots of unread texts in one conversation and want to quickly reply to another one and come back and keep reading from where we left.

Thnx

**Comment by lampholder** [comment]
I think we already do, in the same browser session at least (at least, that seems to be what's happening on my Chrome+Ubuntu) - what are you experiencing instead?

**Comment by muzirian** [comment]
Its working fine for me too, sorry for the trouble.Closing the issue and thanks for reply.
