### ISSUE TITLE
Add room alias - the adding '+' is only shown on mouseover

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3905]
So it just looks like a textbox with no obvious way to submit. Also this is similar-but-different from the 'add email' dialogue in user settings.

![image](https://cloud.githubusercontent.com/assets/1922197/26001891/bdafc24e-3725-11e7-9707-2d1d065c6c16.png)

**Comment by t3chguy** [comment]
This UI got completely changed:
![image](https://user-images.githubusercontent.com/2403652/63856379-5ed97680-c999-11e9-9f05-48674380395f.png)
