### ISSUE TITLE
### in new composer /me doesn't work

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#3910]
but does in old composer

**Comment by lampholder** [comment]
Sorry, what's not working?
- `###`
- `/me`
- `### + /me`

And is this is in the new compose on /develop?

I had a play and it seemed to be working in ways that I expect...

**Comment by t3chguy** [comment]
`/me ### foo` would not be h3, whereas doing the same on old composer would

**Comment by lampholder** [comment]
@t3chguy can reproduce this reliably
@lampholder can't

So... something strange is going on :P

**Comment by aaronraimist** [comment]
The new *new* composer seems to fix this.

**Comment by jryans** [comment]
Indeed it does, thanks! 😁
