### ISSUE TITLE
RTE hijacks Ctrl+Shift+I

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#3913]
makes opening devtools in electron that tiny bit more painful, Alt, etc :L

**Comment by lampholder** [comment]
This sounds annoying :P

**Comment by t3chguy** [comment]
it hijacks it for Italics, but shouldn't that be just Ctrl+I? it should ignore when in conjunction with the Shift modifier

**Comment by lukebarnard1** [comment]
@t3chguy yep, that sounds like a fix to me
