### ISSUE TITLE
Riot doesn't like Chrome 58 (/develop)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3914]
### Description

It appears as though https://github.com/vector-im/riot-web/commit/8e2e6cee35845f256cfe2f9981a1efa7978d2f0a has caused riot-web to give the red screen of death while on Chrome 58.

### Steps to reproduce

- Be on chrome 58ish
- Open riot.im/develop

Log: not sent    

![image](https://cloud.githubusercontent.com/assets/1190097/26038975/4d14cdf6-38d1-11e7-8566-944336c0f299.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
oops, fixed by c3477a3
