### ISSUE TITLE
when someone is typing, i sometimes can't see the last message

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3923]
albuic says: when someone is typing, i sometimes can't see the last message (using the webapp in firefox)

when you click another chan, you don't have the bottom space which is reserved for the bar containing the text 'XYZ is typing'

https://riot.im/staging

**Comment by lampholder** [comment]
This doesn't seem to happen in chrome, but can be reliably reproduced in firefox

To reproduce:
- Be logged in as two users in two separate rooms in two separate browser sessions
- User A start typing
- User B switch to the room User A is in
- Look - the typing notification box is on top of the room message text

This doesn't happen if the typing notification occurs when User B is already in the room - then the notification functions as expected and bumps the room text upwards.

**Comment by turt2live** [comment]
Hopefully fixed by new typing notifications (which are part of the timeline and not a status bar)
