### ISSUE TITLE
about.riot.im site: menu can be covered by app links bar

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3926]
On https://about.riot.im/riot-is-free/, when I expand the menu, I get:
![image](https://cloud.githubusercontent.com/assets/1012976/26110073/38ff17be-3a1f-11e7-84c1-58ae978c4f27.png)
(notice how the app links bar covers up the Blog item in the menu)

This can be fixed by changing the style for the `main-header` class from `z-index: 1` to `z-index: 2`, like this:
![image](https://cloud.githubusercontent.com/assets/1012976/26110236/c0432e86-3a1f-11e7-929a-0e6e257eecd1.png)

**Comment by ara4n** [comment]
fixed, thanks :)
