### ISSUE TITLE
Font in field too dim.

### ISSUE THREAD

**Issue by commagray** [vector-im/riot-web#3927]
Subj, pic related. Dark theme on QtWebEngine5.8-based browser.
![screenshot_20170516_192649](https://cloud.githubusercontent.com/assets/27947961/26117152/32ca998c-3a6e-11e7-92f0-863ee8e76a5d.png)

**Comment by lampholder** [comment]
Yep, it looks weird. This should be darker.

**Comment by ara4n** [comment]
woo, thanks @ollieh!
