### ISSUE TITLE
Ability to discover correct HS URL for your 3PID from your IS

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3930]
In an ideal world, we'd be able to configure the identity service to tell clients where to find the HS for them to log in a given user based on their 3PID

**Comment by ara4n** [comment]
related to #507, although we obviously shouldn't be using heuristics to guess the HS but record it properly in the IS DB

**Comment by uhoreg** [comment]
I'm not sure that storing the HS in the IS DB is a good idea, since if the HS URL changes, then the IS will have outdated information.  IMHO, the IS should resolve to the MXID, and then it should figure out the HS from the MXID using `.well-known` or whatever other mechanism.

**Comment by ara4n** [comment]
agreed. not sure what i was thinking here.
