### ISSUE TITLE
Display redacter of event.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#3931]
It's not clear at a glance *who* redacted an event which would be useful to make moderation more transparent to the rest of the room.

**Comment by turt2live** [comment]
Although a bug, the lack of read receipt can be used in smaller rooms: https://github.com/vector-im/riot-web/issues/3511

**Comment by lampholder** [comment]
I'd also like to be able to see the time of the redaction, too (I don't think this is currently available)

**Comment by uhoreg** [comment]
A fix for this should try to take into account #3929/#3657 as well (and vice versa)

**Comment by ara4n** [comment]
@turt2live's fix shows the redacter, but not the time of the redaction (which is tracked separately as #5061). closing this one - thanks!
