### ISSUE TITLE
Local room aliases

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#3937]
Especially in direct chats, it'd be useful to specify a local-only room alias. While the room itself is unnamed, it shows up using the `@user:handle` of the peer, but naming a room affects everyone in this room.

It'd be better if I could give a room a local label that is only visible to me (but consistent across all devices). That way, I can name the rooms in a way that makes sense to me, without affecting everyone else.

Thanks,
-m

**Comment by turt2live** [comment]
This sounds a lot like #3130

**Comment by t3chguy** [comment]
I'd say it is, alias implies the address for the room which I believe this does not mean. Closing as dup of #3130
