### ISSUE TITLE
Cannot download image in Electron App

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3938]
From a rageshake bug report:

- ask somebody to send some you an image
- you see it Riot Electron but can't download it. Trying to download it launches firefox but doesn't succeeed

Firefox is already running. but not responding. To open a new firefox window, you must first close the existing Firefox process, or restart your system

**Comment by t3chguy** [comment]
This should be fixed in next release, where the Download buttons will actually trigger a system save as dialog

**Comment by uhoreg** [comment]
Looks like the user already reported it as #3826, which @ara4n closed, so closing this one too.

**Comment by t3chguy** [comment]
yeah fixed by #3640
