### ISSUE TITLE
Escaping/dismissing paste confirmation dialog does not re-focus on message entry

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3944]
### Description

Related to #3400, except with the other button this time :)

### Steps to reproduce

- Have an image on your clipboard
- Paste image into Riot
- Dismiss the dialog (close button or escape key)

Focus should be returned to the field, much like pressing OK would do.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
hedged on matrix-org/matrix-react-sdk/pull/894

**Comment by t3chguy** [comment]
(did not mean to close)

**Comment by turt2live** [comment]
Closing this in favour of https://github.com/vector-im/riot-web/issues/4664
