### ISSUE TITLE
on develop: when room groups are expanded, the room list shows up at the bottom of the list rather than under the group title

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3948]
as reported by fladd in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14950445401817538KALwY:matrix.org, and as show in https://matrix.org/_matrix/media/v1/download/matrix.org/PkqRqeqonggrnKEjFlLeIJyg

**Comment by Kegsay** [comment]
I get the same thing on Chrome 57 OSX

> matrix-react-sdk version: 90ee0c7ad9150b4ed457d6c8546779d561431cc0
riot-web version: 53f0a6b360fb-react-90ee0c7ad915-js-4ccec1373905
olm version: 2.2.1

**Comment by dbkr** [comment]
OK, looks like this is a gemini issue: it only seems to be a problem on a mac with no mouse plugged in.

**Comment by dbkr** [comment]
Fixed. I missed https://github.com/matrix-org/matrix-react-sdk/commit/1347d9fa65f878cb65aaf0898536645e4a642429
