### ISSUE TITLE
Simple success notification for completed ILAG registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3955]
When you provide a password to complete registration following the new landing-as-guest process, the dialogue accepts your password but doesn't provide a confirmation message.

At a bare minimum we need to tell the user they've succeeded, which we can achieve with a modal saying 'Registration successful'.

One modal immediately followed by another is clunky, so if we can just replace/modify the contents of the password set modal and have it self-dismiss after a few seconds that might work well.

There is a *lot* of scope here for something better - this is a key interaction moment with the new user, in which we should be feeding them the next spoon of Rioty goodness, but deciding on how that should work is beyond the scope of this task.

**Comment by lukebarnard1** [comment]
> just replace/modify the contents of the password set modal and have it self-dismiss after a few seconds that might work well.

Why didn't I think of that? And yes this is quite simple.
