### ISSUE TITLE
The roomlist on /develop doesn't scroll if your mouse is over the ROOMS, LOW PRIORITY or HISTORICAL label headings.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3957]
If your mouse is over a room tile or a different heading it scrolls fine.

Possible related to (and almost certainly shares a genesis with) https://github.com/vector-im/riot-web/issues/3948

**Comment by uhoreg** [comment]
@lampholder is this #2696?  i.e. does this only happen when the ROOMS, LOW PRIORITY, and HISTORICAL labels are at the very bottom of the room list?

**Comment by ara4n** [comment]
it is.
