### ISSUE TITLE
App gets stuck in loading on every launch until browser cache is cleared

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3971]
This is a public bug to track the rageshake at https://github.com/matrix-org/riot-web-rageshakes/issues/112

It seems particularly nasty :(

**Comment by lampholder** [comment]
Do we know if many people are experiencing this?

**Comment by lampholder** [comment]
Filing as critical since it sounds like it effectively takes out the whole app unless you're willing to dig into the settings and clear the cache.

P1 just to mine the logs to see if they help us understand what's going on so we can see how to proceed.

**Comment by ara4n** [comment]
this is long gone
