### ISSUE TITLE
On experimental, sticky headers have too high z-index

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3972]
<img width="985" alt="screen shot 2017-05-19 at 23 43 43" src="https://cloud.githubusercontent.com/assets/1294269/26269542/19d405b8-3ced-11e7-93d2-39ab054d0804.png">

**Comment by uhoreg** [comment]
At that vertical size, aren't all the headers supposed to be non-sticky?  Otherwise, you can't scroll anything.  At least, that's how it is in non-experimental.

**Comment by ara4n** [comment]
this is not a bug on develop, and experimental is pretty dead; i guess it will reappear once my LeftPanel optimisations finally land
