### ISSUE TITLE
Make window.title base component ("Riot ") customizable

### ISSUE THREAD

**Issue by chr-1x** [vector-im/riot-web#3973]
### Description

Currently, if you are participating in two different networks/servers under two different user accounts, it can be confusing to switch back and forth between browser tabs. A custom favicon can help mitigate this, but even better would be the ability for server operators to customize the base text of their Riot webapp to clarify which server the webapp is being hosted on. 

There are two potential options for this that I see after administrating Riot webapps for a few weeks now:
 - Use the "branding" key in the config.json. I'm not sure where this is currently used, but it _appears_ to fit the use case. (e.g. a server called Foonet hosting the Riot webapp as their main interface to their matrix server could change this to "Foonet", and it would also likely be appropriate elsewhere in the app)
 - Use the initial <title> tag contents in the index.html as the base text (save it when the webapp loads and then append all indicators to the saved value). I think this only makes sense if using the "branding" key would be inappropriate, since it would allow you to set the two to different things, e.g. "Foonet" for the branding and "Foonet | Riot" as the title of the webapp (if, e.g. foonet was providing multiple Matrix client options)

Other options are conceivable, and some combination of options (with fallback if e.g. the config.json doesn't set the branding key) may also be desirable.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Any
- **OS**: Any
- **URL**: Any third-party deployment of the riot webapp

**Comment by t3chguy** [comment]
Agreed, I personally would like to be able to choose which of the favicons is used, Riot has like 6
custom text wouldn't be that much further

**Comment by MurzNN** [comment]
At now, as workaround, you can hack `index.html` and replace text in `<title>` tag manually to your string. But this will be overwritten on Riot code update to new version.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/b5d532b8cd64bc017369ef63431d8355d522d76e/src/components/structures/MatrixChat.js#L1825 this is now possible
