### ISSUE TITLE
Flag images are really muddy

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3974]
It looks like the resizing filter is a really fuzzy one, or possibly resized from too small a size?  it's particularly bad on a retina display, where we should be serving these at 2x.

<img width="482" alt="screen shot 2017-05-20 at 02 40 11" src="https://cloud.githubusercontent.com/assets/1294269/26271997/f4e134c4-3d05-11e7-8efd-e96a8c70b20c.png">

Are SVGs definitely too slow to load?

**Comment by lampholder** [comment]
@lukebarnard1 - what are your thoughts on svg?

**Comment by lukebarnard1** [comment]
The previous SVGs were, and we'd still be rendering the same number. But I haven't tried honestly. 

These flags are not designed to be shrunk to such a tiny size, they're just done in a big blob so we're not going to achieve very nice scaling whatever we do. We could of course use a set of flags that have been designed from the outset to be icons.

**Comment by lukebarnard1** [comment]
The previous SVGs were, and we'd still be rendering the same number. But I haven't tried honestly. 

These flags are not designed to be shrunk to such a tiny size, they're just done in a big blob so we're not going to achieve very nice scaling whatever we do. We could of course use a set of flags that have been designed from the outset to be icons.

**Comment by ara4n** [comment]
I've switched the script to use Lanczos filtering (which is sharper than the sigmoidized EWA cubic B-spline filtering that IM does by default).  I've also doubled the res for retina displays.  The end result seems pleasing:

<img width="339" alt="screen shot 2017-05-29 at 00 07 20" src="https://cloud.githubusercontent.com/assets/1294269/26532817/1ae21414-4403-11e7-92fb-a2033010140f.png">
