### ISSUE TITLE
When room panel is collapsed, tooltip for room categories does not match tooltip for rooms

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3979]
The rooms use some custom tooltip that appears right away when you mouse-over the room avatar, whereas the tooltip for room categories uses the browser-native tooltip, which only shows up after a pause.  IMHO, it would be better if both used the same kind of tooltip.

**Comment by lampholder** [comment]
Consistency ftw :)

Although, as I continue to think about it, the twp tooltips do serve different purposes.

1. On the _compact view_, the tooltip is the only way to see the room name, so you need it right away.
1. On the _full view_, the tooltip is only useful for seeing the full name of rooms with names longer than the roomlist is wide. Most often you don't need to see the tooltip, indeed, seeing it immediately could be very visually noisy.

So whilst I think cosmetic consistency would be nice to have, we probably want to think more about whether we want to get rid of the browser-native brief pause behaviour.

**Comment by uhoreg** [comment]
This isn't about consistency between the compact view and the full view.  I'm fine with the browser-native tooltips in the full view.  This is about consistency between two different things (group headings and room names) in the compact view.  Here are some screenshots:
Group heading:
![image](https://cloud.githubusercontent.com/assets/1012976/26360257/a75ff88c-3fa5-11e7-87b3-e3e9cb332743.png)
Room:
![image](https://cloud.githubusercontent.com/assets/1012976/26360278/b1a29084-3fa5-11e7-9e49-d3b2eee0d2e2.png)

**Comment by lampholder** [comment]
Revisiting due to #4399 - obvs I misunderstood when I looked at this the first time.

We should certainly use the same custom popup for titles and room headings in compact view.

Changing the priority to P2 (and resolving #4399).
