### ISSUE TITLE
Handle RTS members nicely /w new-guest-access

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3981]
Currently, if you set a matrix ID as a guest with a team token (i.e. you've been referred by a team member), you won't be tracked as a team member and your Riot won't have a team token when you close your browser and come back to Riot.

So there are a few options and UXs that are possible here (when a user tries to join a room as a ROU):
 1. Send them to /register so that they can provide an email address.
 2. Show a dialog and send them to /register.
 3. Show "Pick a username" but modify the existing dialog to include a link (like the different server link) that will take them to `/register` with a small explanation like "if you want to register as a team member or choose a different server, click here".

**Comment by lampholder** [comment]
I think we added another option in our discussion earlier - show the 'choose a mxid' dialogue as per ILAG, but include a non-optional email field that validates the domain is correctly associated with the team.

**Comment by lampholder** [comment]
@ara4n @AmandineLP - thoughts?

**Comment by lampholder** [comment]
RTS is not really a thing now.
