### ISSUE TITLE
The label 'today' is lost

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#3985]
I sent messages in a room which hadn't had any msg activity for a long time. my msg seem to appear as being sent 12 Arpil (we're 22 May)

https://riot.im/develop/#/room/#testingguestaccess:matrix.org

![image](https://cloud.githubusercontent.com/assets/8582858/26313236/1db2efde-3f02-11e7-831b-9d891dcc5e27.png)

**Comment by lukebarnard1** [comment]
This looks like a MELS bug. It's possible that a `DateSeparator` is _not_ inserted for a non-MELS event that occurs at least a day after the MELS.

**Comment by lampholder** [comment]
P1 major 'cause people _need_ to be able to trust that a message was said when it looks like it was said, otherwise it undermines a lot of faith in the app.

**Comment by lukebarnard1** [comment]
I *think* this got fixed.

**Comment by turt2live** [comment]
looks fixed to me: 
![image](https://user-images.githubusercontent.com/1190097/40129065-881a6952-58f0-11e8-9f81-4bf340a61dfe.png)
