### ISSUE TITLE
If the mxid picker interrupts a room entry attempt, we should reattempt room entry after mxid-picking completes.

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#3986]
currently when doing an action launching the new process of providing a user name (eg join a room, create a direct chat, create a room after either accessing riot.im/app or clicking a link for example) riotbot is launched and I'm dumped in a discussion with him. It's very disruptive. If the user is trying to make a given action he should be able to finish it and only have a pending invite from riotbot

**Comment by lampholder** [comment]
We discussed this this afternoon and identified that, whenever there is an obvious room intention for a user, they should end up in that room after choosing a mxid if possible.

So this would look like:

1. User navigates to a room link
2. User sees the preview
3. User elects to join the room
4. User is prompted to choose a mxid
5. User is thanked for choosing a mxid
6. User lands directly in the room if they can - they don't see the same peeking dialogue, they're straight through to the room

What do we do if they don't have permissions to access the room, i.e. if it's invite only?

**Comment by lampholder** [comment]
For any other action (create room, invite user, change settings, whatever), there is no obvious room intention so we will just drop them into a chat with riot bot. Assuming the user still wants to perform the original action, they'll have to reinitiate it from scratch.

Obviously we can see how this feels and consider other options if it feels bad :)
