### ISSUE TITLE
Welcome page for new users navigating to /app

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3998]
**The scope of this task is to put in place a welcome screen for new users navigating to /app to replace the Room Directory**

### Details
Today we hit new users with the Room Directory, which is far from the warmest of welcomes.

Our new _Improve Land as Guest_ onboarding flow for brand new users is basically:
- show users the full UX
- let them look at any publicly-viewable rooms
- if they try and do _anything else_, intercept and get them to pick a mxid and start their journey towards becoming a full user

So, to work best within this flow, it would be good for the welcome page to suggest some things a new user might be interested in doing, to pique their interest.

**Comment by lampholder** [comment]
Mockup with mocked up language:
https://docs.google.com/document/d/1pmwiWYKlmZoTteU9zN0W4PSkzAk2Qi-Bw3QevbDKN6M

**Comment by BenfLewis0** [comment]
Hey Tom, 

Here you go....

<img width="1144" alt="screen shot 2017-05-23 at 11 25 10" src="https://cloud.githubusercontent.com/assets/24248929/26350288/903d5f96-3faa-11e7-8146-e498a7086bb8.png">

**Comment by lampholder** [comment]
It's easy to lose track, so for the record, the reason we're considering the welcome page is because at this stage users won't have entered a mxid, so they're not yet ready to be dropped into a chat with riot-bot.

We might consider dropping the welcome page entirely in favour of just prompting to enter a mxid, but since we know these users are less... intentional than users who've clicked a room/event link, it might be worth taking the opportunity to suck them in a bit more and hint at all the goodies that lie behind their providing said mxid :)

**Comment by turt2live** [comment]
@lampholder I believe this is done now?

**Comment by tmikaeld** [comment]
I've been moving a few company users over to Riot and a few normal users as well, mostly from Wire and Signal.

They are completely confused and overwhelmed by all the myrriad of buttons, texts, new conventions like private/public rooms, favorites, pages, public, private rooms... while all they want to do is connect with their peers and starta a discussion!

Tell me, as a new user, is it easy to get ANY grasp of where to start on this initial page?

The proposal above is at least simple, the current page is NOT simple and very disencoraging for anyone not already versed in IRC or Slack.

![image 2018-08-10 at 11 48 21 am](https://user-images.githubusercontent.com/907195/43951399-59309c38-9c93-11e8-8041-c63293be2df7.png)

**Comment by tmikaeld** [comment]
I think a better way to address on-boarding is a choice where we apply GOOD defaults and relevant on-boarding to the role they choose.... for example:

What will you use Riot for?

- Chatting with friends (Like Skype or WhatsApp)
- Collaborate with my team (Like Slack)
- Join discussion boards (Like IRC or Discord)

This will make it a ton easier to instantly make the interface familiar to everyone!

**Comment by turt2live** [comment]
Closing: I'm 99.9% sure the homepage is what this is talking about.
