### ISSUE TITLE
New login UI breaks if you fill in multiple fields

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4000]
* Fresh login
* Select phone number from dropdown and enter a phone number
* Don't click login
* Switch to mxid login
* Try to log in
* Login fails, as apparently we submit the (now invisible) phone number :(

**Comment by lampholder** [comment]
Obviously this is a shame, but the thing that really interests me is why none of us thought to test this case before it went live?

Something for a riot-web retrospective I think.
