### ISSUE TITLE
ILAG snagging list

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4004]
### Urgent
- [x] cannot read property teamServerURL of undefined (https://github.com/vector-im/riot-web/pull/4024)
- [x] Kill the `You are Rioting as a guest. Register or sign in to access more rooms and features.` nag bar (https://github.com/matrix-org/matrix-react-sdk/pull/9230)
- [x] In the left panel, hide the [Drag here to favourite] and [Drag here to demote] boxes - just leave the FAVOURITES and LOW PRIORITY sections expanded but empty (exactly as if you'd set `display:none;` on the textbox) (https://github.com/vector-im/riot-web/pull/4023 - hides the labels when there are no rooms at all)
- [x] Drop the 'You have successfully picked a username' confirmation dialogue (https://github.com/matrix-org/matrix-react-sdk/pull/926)
- [x] Remove the word 'new' from the password setting dialogue heading
- [x] Remove the word 'new' from the password setting dialogue explanatory text
- [x] PWLU NAG BAR: Change PWLU nag bar to read 'To return to your account in future you need to set a password'
- [x] PWLU NAG BAR: Underline 'set a password'
- [x] PWLU NAG BAR: Interpret any click on the whole nag bar as a request to set a password
- [x] BUG: As a ROU, the PWLU nag bar is shown - the SessionStore should be wiped on logout! (https://github.com/matrix-org/matrix-react-sdk/pull/930)
### Can wait a tiny bit

- [x] Set the mxid (minus the '@' and the domain part) as the display name (https://github.com/matrix-org/matrix-react-sdk/pull/933)
- [x] Can the username availability checker be snappier? Is there a reason it isn't?
- [x] If the availability check fails (kill networking in browser developer tools to test) we vomit up the error - we should be 1. checking if the javascript error has a .message to render and 2. falling back on 'Something went wrong' if it doesn't (https://github.com/matrix-org/matrix-react-sdk/pull/935)
- [x] Clicking the user settings button doesn't trigger the 'pick a mxid' dialogue (https://github.com/matrix-org/matrix-react-sdk/pull/936)

**Comment by lampholder** [comment]
I'm going to reorder the above into: "needs to go out before ILAG can add value" and "can be deferred to phase 1.1"

**Comment by ara4n** [comment]
I've sped up the username availablility check run after 250ms rather than 2000ms in matrix-org/matrix-react-sdk@1efc5c2b2599120849ef7c01ebdef5d8941d4c15, as randomly being forced to wait 2s every time i try to check for the availability of a username was driving me maaaaaad :)

**Comment by ara4n** [comment]
The remaining stuff from my POV here is:
 * [ ] fix the tests
 * [ ] check RTS works (especially after my switching iframe for request() on tom's branch - we may need to support iframe for RTS as well as request() for simple static content)
 * [ ] broken focus on the setMxIdDialog https://github.com/vector-im/riot-web/issues/4063
 * [ ] broken back button from the login page https://github.com/vector-im/riot-web/issues/4061

I suggest we try to get it into today's RC.

**Comment by lukebarnard1** [comment]
>check RTS works 

@lampholder, you've been doing this right? And it's still fine?

**Comment by ara4n** [comment]
RTS isn't a release blocker, and afaik still works; we have #4061 for the other open bug, so i'm going to close this one.
