### ISSUE TITLE
Insanely long og:description gets shown in entirety and causes message to flicker

### ISSUE THREAD

**Issue by alexgleason** [vector-im/riot-web#4006]
### Description

When sharing a link with a super long og:description, Riot displays it in its entirety. This causes the message to flicker on the screen, and attempting to scroll up forces the scrollbar back to the bottom after a second.

### Steps to reproduce

- Open any room on Riot desktop
- Paste this URL into the message https://www.eff.org/issues/tpp
- See the message flicker incessantly and scrolling up is not possible

### Version information

- **Platform**: desktop, nothing else tested

For the desktop app:

- **OS**: elementary OS (based on Ubuntu 16.04)
- **Version**: 0.9.9

**Comment by t3chguy** [comment]
closed by matrix-org/synapse/pull/2243

**Comment by alexgleason** [comment]
Hmm is this something Riot should deal with too, not just Synapse? Say an alternative server implementation doesn't truncate it, it's wrong to show that to the user either way.

**Comment by t3chguy** [comment]
Sure, then duplicate of #2894

**Comment by alexgleason** [comment]
Thank you!
