### ISSUE TITLE
when starting a new chat, selecting the nick is too slow

### ISSUE THREAD

**Issue by pmgouveia** [vector-im/riot-web#4008]
### Description

When I want to start a new chat It's very hard to write an ID a user sent me, to open a new chat. Firefox complains after I write a character, that the script is going slow...

### Steps to reproduce

Click on start new chat -> type a user id...
For the web app:

- **Browser**: Firefox 53.0.2 64bits
- **OS**: Linux Manjaro / Arch
- **URL**: riot.im/app

http://oi67.tinypic.com/hsrejk.jpg

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/3713
