### ISSUE TITLE
Login textbox asks for "Email or user name" but doesn't allow to enter the '@' character

### ISSUE THREAD

**Issue by racribeiro** [vector-im/riot-web#401]
I'm using the portuguese keyboard layout and I can't enter the '@' character out from the keyboard when focused on the "Login textbox for Email or user name". When I change to the English keyboard layout, it works. It also works on the Portuguese layout if I copy&paste the @ character.

**Comment by ara4n** [comment]
thanks for the report - we'll check it out; we're wading through a lot of bugs atm :)

**Comment by ara4n** [comment]
@racribeiro i appreciate it's been a while, but can you see if this is still happening for you these days on https://riot.im/app? 😇

**Comment by racribeiro** [comment]
Hi Matthew,

It seems ok now.

Thanks,

Rui


2017-05-16 0:39 GMT+01:00 Matthew Hodgson <notifications@github.com>:

**Comment by ara4n** [comment]
great - what a weird bug. thanks!
