### ISSUE TITLE
streamline room creation process

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4017]
I can't recall if this was the legacy way of doing, but might be useful to reconsider whether having few steps to create a room like the below would be useful
1. enter name
2. invite people
3. basic config: public vs private; encrypted or not (maybe)
I find it annoying to have to create then go to the right place into the room to invite folks and update the settings.

**Comment by t3chguy** [comment]
The only bit missing now is to invite people inline, but for that you can use the `Start chat` flow and enter multiple people.

![image](https://user-images.githubusercontent.com/2403652/79047605-9e469180-7c0f-11ea-8e92-b56c2fe46836.png)
![image](https://user-images.githubusercontent.com/2403652/79047609-a272af00-7c0f-11ea-870a-b7519f7c8258.png)

I think this is majorly resolved at this point
