### ISSUE TITLE
when signing up, provide feedback when SMS verification is expected to fail, instead of failing silently

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4018]
If users sign up using an phone number from a country that isn't supported yet, they're left wondering why the SMS verification never arrives.

**Comment by lampholder** [comment]
Dup of https://github.com/vector-im/riot-web/issues/3542 (and https://github.com/vector-im/riot-web/issues/3618) - for unsupported countries you should now get an error message saying 'Phone numbers in this country are not currently supported'.

However, reliable international SMS delivery is a challenge, and it's possible that our list of supported countries is out of sync with the connectivity (either temporarily or permanently) - do you know which country we were trying to send to when we:
- didn't get this error, and
- didn't deliver the SMS?

**Comment by uhoreg** [comment]
Ah, I missed that issue.  Closing.
