### ISSUE TITLE
Riot not clearing out rooms I've left

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4025]
### Description

When I leave a room, normally it disappears from the room list (albeit with a delay). This seems to have stopped working.

### Steps to reproduce

- Join a room
- Leave it

The room seems to stick around in the client. I have to click 'forget' to get rid of the room, but any other Riot instance I have open doesn't see the change, and I have to forget the room there too.

Rooms should be removed if I've voluntarily left them.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/experimental

**Comment by lampholder** [comment]
I thought I had to explicitly choose to 'forget' rooms I'd left to remove them from the list, but that might just be my having been impatient wanting to get left rooms to disappear immediately.

Can anyone comment as to whether this is a true regression? @ara4n?

**Comment by turt2live** [comment]
This appears to no longer be an issue. Tested on /develop and /experimental - the issue no longer repeats itself.

At the time of reporting it might just have been excessively slow.
