### ISSUE TITLE
riot-bot videos have unknown mime types

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4027]
### Description

This seems to be a firefox problem. Unsure if platform specific.

The last 2 videos from riot bot (invite by email and bots) give the following error in Firefox:
![image](https://cloud.githubusercontent.com/assets/1190097/26455186/ac307918-4126-11e7-9c49-0399bbac645c.png)

They work fine in Chrome.

### Steps to reproduce

- Be on firefox
- Get riot-bot to send you "invite by email" or "bots/integrations"
- Attempt to play the video(s)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 52.0.2 64bit
- **OS**: Windows 10
- **URL**: tang.ents.ca (based on riot.im/app - issue also occurs on riot.im/app)

**Comment by lampholder** [comment]
This didn't happen in ff 52 on mac, so perhaps it is specific to windows?

**Comment by turt2live** [comment]
I can no longer reproduce this.
