### ISSUE TITLE
UX to remove n device keys, replace with one

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4031]
Instead of removing old devices, I propose that we allow users to shuffle a chosen device key around to several of their devices by using the existing `to_device` channels. Those selected devices would all then use the same device key, reducing the number of devices by a factor of `n` because we could allow the option to delete any other devices in the process.

We could aggressively prompt the user to do this. Also, when a new device is added, we could prompt the user to verify whether they'd like to add it to their "linked" devices and send the encrypted key to the new device. 

The caveat here being the movement of the private keys off device.

**Comment by richvdh** [comment]
I'm not sure this will help. Even if two devices share the same key, we still have to encrypt things for each of them - so they still need to exist as separate devices in the system.

**Comment by lukebarnard1** [comment]
>Even if two devices share the same key, we still have to encrypt things for each of them

Ohhhh this was the thing that I clearly wasn't getting earlier. I was under the impression that if devices share the same key, you could encrypt once for that key and send the same ciphertext to both devices (but the server would be none the wiser)

**Comment by ara4n** [comment]
olm is a strictly 1:1 channel, sadly.
