### ISSUE TITLE
/user/@bob:bob.net should start a DM with bob

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4034]
Required to do "start DM with RiotBot" button/link nicely

**Comment by ara4n** [comment]
i agree we need a URL for this, but /user is already used to pull up the MemberInfo for bob, i think.  So prolly needs a different prefix.

**Comment by uhoreg** [comment]
Another alternative would be to add a query parameter to the link, e.g. `/user/@uhoreg:matrix.org?action=chat` (see also matrix-org/matrix.to#22 for some thoughts on the matrix.to side)

**Comment by uhoreg** [comment]
Also, it should probably have some sort of confirmation screen before starting a DM, otherwise someone could post a message saying `Click <a href="/user/@uhoreg:matrix.org?action=chat">here for free money</a>!`, and flood me with invite spam.

**Comment by lampholder** [comment]
I believe the plan is now to move forward with this.

The behaviour as I understand it will be:

- click `/user/@uhoreg:matrix.org?action=chat`
    - if the user is not logged in, show `choose a mxid`
    - if the user is logged in and has no DM with uhoreg, prompt them asking if they'd like to start one
    - if the user is logged in and has one-or-more DMs with uhoreg, prompt them asking if they'd like to use one of the existing DMs or start a new one

Are there any complexities introduced by the user navigating straight into `https://riot.im/app/#/user/@uhoreg:matrix.org?action=chat` (i.e. not clicking a link whilst already operating within the app)?
- if they're not logged in, can we just show them the `choose a mxid` dialogue? On top of a blank background, or the welcome page?
