### ISSUE TITLE
riot-bot's jokes need some filtering/vetting

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4036]
### Description

> A woman is at a grocery store. She goes to the clerk to purchase her groceries. The clerk looks at her items and sees a carton of eggs, a gallon of milk, and a head of lettuce. He says to the woman, "You must be single." The woman was surprised & replies, "Yes, how did you know?" The clerk answers, "Because you're ugly."

As reported here: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1495761431759475evsZX:matrix.org

**Comment by ara4n** [comment]
Apparently riotbot had a load of 'jokes' bulk-loaded into it fairly blindly without anyone bothering to check through them >:( We've disabled jokes entirely on it for now.
