### ISSUE TITLE
Translations: Selecting the same language should not cause a page refresh.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4042]
### Description

English is the default, and selecting English again should not cause the page to refresh.

### Steps to reproduce

- Find the language selection
- Pick the same language you already had.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
sorted - thanks :)
