### ISSUE TITLE
12h time shows 'AM' in the PM

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4043]
### Description

![image](https://cloud.githubusercontent.com/assets/1190097/26509401/d43d7754-4215-11e7-91d9-60a5ddc27f38.png)

Unsure if time related (ie: if 1pm is just a bad time).

fwiw, timezone is GMT-6 (MDT)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
also happened for noon:
![image](https://cloud.githubusercontent.com/assets/1190097/26509465/1b3acaf8-4216-11e7-9f98-a7d6e63d5011.png)

**Comment by t3chguy** [comment]
fixed by https://github.com/matrix-org/matrix-react-sdk/issues/939
