### ISSUE TITLE
Tracking Issue for missing translation strings.

### ISSUE THREAD

**Issue by MTRNord** [vector-im/riot-web#4045]
This Issue is for keeping track of "missing translation" bugs. As it otherwise just will fill the issues if we open one for every string, Just add a commit with the string and where you found it.

**Comment by MTRNord** [comment]
`missing translation: en|For security, this session has been signed out. Please sign in again.`   Found at the logout if the device was removed

**Comment by turt2live** [comment]
![image](https://cloud.githubusercontent.com/assets/1190097/26510664/95815dfe-421b-11e7-9756-5577b1e81208.png)

**Comment by JigmeDatse** [comment]
Just got:

```
a changé le niveau de pouvoir de @realitygaps:chat.weho.st from missing translation: fr|Default (0) to Moderator (50)
```

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/945 fixes some of these.

**Comment by ara4n** [comment]
I wrote a script to chase these down at https://github.com/matrix-org/matrix-react-sdk/blob/develop/scripts/check-i18n.pl, and subsequently chased down all the ones I know of (committing onto develop).

The script also lists strings which exist in en_EN, but don't have `_t()` in the app itself - as well as the delta between specific languages and en_EN.
