### ISSUE TITLE
on develop: non-functioning "Always show message timestamps" preference

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4047]
On /develop, there is a preference called "Always show message timestamps" that does not seem to do anything.  It looks like it was accidentally added as part of the 12h hour timestamp patch, when it was uncommented in https://github.com/matrix-org/matrix-react-sdk/commit/008cc95e9ca97199add9e9591a85012b3dbf8759#diff-e7c389fce1332fbeee9ef9ed05d4b1a5L68 instead of just uncommenting the "Show timestamps in 12 hour format (e.g. 2:30pm)" option.

**Comment by uhoreg** [comment]
assigning to @ara4n since he merged the PR 😛

**Comment by t3chguy** [comment]
related pr-wise:
https://github.com/matrix-org/matrix-react-sdk/commit/008cc95e9ca97199add9e9591a85012b3dbf8759#diff-1e29f502e08e29b96cc7bea29b0ee420R489 haunts me

**Comment by ara4n** [comment]
it should function once that PR is merged :)
