### ISSUE TITLE
i18n shouldn't mix up ISO country codes in with rest of the translations

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4055]
otherwise they may collide with other 2-letter translations like 'OK'

**Comment by pafcu** [comment]
These have been removed, so should no longer be an issue?

**Comment by pafcu** [comment]
@ara4n Could be closed?

**Comment by pafcu** [comment]
@lampholder Could be closed?

**Comment by ara4n** [comment]
sounds like it - thanks!
