### ISSUE TITLE
ILAG: browser's back button doesn't work when navigating from /login (or /register) to /home

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4061]

**Comment by lukebarnard1** [comment]
This is actually because going to /login causes the client to update its state to reflect being logged out. So the history is intact.

I find it odd that by default, changing screen will log the user out:

```js

    setStateForNewScreen: function(state) {
        const newState = {
            screen: undefined,
            viewUserId: null,
            loggedIn: false,
            ready: false,
            upgradeUsername: null,
            guestAccessToken: null,
       };
       Object.assign(newState, state);
       this.setState(newState);
    },
```

**Comment by lukebarnard1** [comment]
OK, so I've realised why it's actually not odd - `setStateForNewScreen` only happens for lifecycle operations like registering, logging in, resetting a password. Setting `loggedIn` takes the user out of the `LoggedInView` which makes sense.

So we could set the default `loggedIn` to `true` and have separate state for indicating the intention to be "outside" of the app (not being in `LoggedInView`).

**Comment by ara4n** [comment]
this is nasty, but probably not a release blocker

**Comment by ara4n** [comment]
this drives me nuts :(

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2383 (for experimental)
