### ISSUE TITLE
[slack/riot-web integration] bot or app messages don't get relayed from slack to riot-web

### ISSUE THREAD

**Issue by arthurlutz** [vector-im/riot-web#4065]
### Description

When using the riot-web / slack integration, the user's messages are correctly bridged/mirrored across both channels (even images), but when an "app" talks on slack the messages don't get relayed to riot. (The "app" is getting messages from an incoming webhook). 

### Steps to reproduce

- setup riot/slack integration with both incoming and outgoing webhooks
- write a msg on slack, see it on riot
- write a msg on riot, see it on slack
- configure an integration/app on slack, get a new message on slack, don't see it on riot.

### Version information

- **Platform**: both web and desktop

**Comment by uhoreg** [comment]
This is probably matrix-org/matrix-appservice-slack#42

**Comment by t3chguy** [comment]
@uhoreg good spot, seems like it, closing in favour of linked issue
