### ISSUE TITLE
Spurious "X" in room header when peeking 

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4074]
![2017-05-30-102426_701x76_scrot](https://cloud.githubusercontent.com/assets/6750344/26576835/3f7810f6-4522-11e7-9edd-4c34ad13f6ee.png)

**Comment by t3chguy** [comment]
the cog is there on purpose, since it allows you to see things such as room aliases, permissions levels and other room options. Plus the Room Settings page even has a Forget Room button so I presume this is intentional.

**Comment by t3chguy** [comment]
fixed by referenced PR
