### ISSUE TITLE
Emoji autocomplete is noticeably slow in Firefox

### ISSUE THREAD

**Issue by jplatte** [vector-im/riot-web#4080]
### Description

When the "New Composer & Autocomplete" feature is enabled in the desktop app or in Chromium and you type `:`, you will instantly get emoji suggestions (I personally find this a bit annoying, but that's besides the point of this bug report). On Firefox, the same happens, but with a noticable delay between pressing the key and the character as well as the autocomplete menu being displayed – on my desktop machine with a modern i7 and less than 20 tabs loaded in Firefox, I'd say the delay is around half a second. When I do it over and over again (erase and re-add the `:`, or just add characters after it), the JS interpreter seems to warm up and it gets less noticable, but it's definitely still there.

### Steps to reproduce

- Open Riot in Firefox
- Enable "New Composer & Autocomplete" in the settings
- Go to any room
- Type `:` into the message box

### Version information

- **Platform**: web
- **Browser**: Firefox 53.0.3 (Nightly seems to not be affected equally, but that might just be because I tested this when there was only a single other tab in it)
- **OS**: Arch Linux
- **URL**: both riot.im/develop and riot.im/app

**Comment by lampholder** [comment]
I also find this very annoying - the delay is noticeable for me on ff 52 with a single tab open. The filtering should either happen a heck of a lot faster or asynchronously - anything that hinders my typing a message feels very clunky :\

**Comment by lukebarnard1** [comment]
@lampholder if you would please try and repro the slowness. I've tried on Firefox with /develop and it seems fine.

**Comment by lampholder** [comment]
/develop seems perfectly fast now on Ubuntu Firefox 54 and Nightly.

Autocomplete delay can now be configured, too - certainly with it set to 0ms it seems fast enough to me, so I think we can close this. If people are still finding it to be slow, let's reopen.
