### ISSUE TITLE
Language picker should show flags & names of countries primarily in the *target* language, not the current local one

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4082]

**Comment by MTRNord** [comment]
![image](https://cloud.githubusercontent.com/assets/1374914/26588633/22bf275e-4556-11e7-95fe-f24dd527e678.png)

Something like this was suggested by @Shrike:matrix.org at https://riot.im/app/#/room/#riot:matrix.org/$14961478934051544YNLeR:matrix.org

**Comment by dtygel** [comment]
Holpe this fixes the issue...

**Comment by ara4n** [comment]
it does - thanks :)
