### ISSUE TITLE
Starting a chat with an email address doesn't make the room a 1:1

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4093]
### Description

![image](https://cloud.githubusercontent.com/assets/1190097/26601513/56d6af76-453d-11e7-928d-c32bdbf24069.png)

Room name is "Inviting tra...@nir..." instead of something more helpful, and is in the Rooms section, not People. Accepting the invite can also lead to other confusing flows, but still does not flag the room as 1:1.

In addition to all of that, the new user doesn't get ops in the room.

### Steps to reproduce

- Start a chat with an email address that isn't on Matrix

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
The fact that the room isn't marked as a direct chat is #2794, but there are other things mentioned in here as well.

**Comment by turt2live** [comment]
I'm going to go ahead and close this as a duplicate of https://github.com/vector-im/riot-web/issues/2794 hoping that the fix also fixes the lack of ops.
