### ISSUE TITLE
ILAG: Accepting email invite lands you nowhere

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4098]
### Description

Piggybacking off of #4097 - when you click 'accept' you are prompted to enter a username. Upon successfully picking a username, you're left in nowhere land (no new conversations, at the welcome page, no indication of any invite)

### Steps to reproduce

- Do #4097's steps
- Accept invite

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: self built

https://github.com/vector-im/riot-web/commit/64a67583e033601aedbc37f2c04c4db7dde1555e
https://github.com/matrix-org/matrix-react-sdk/commit/c15568e003a9a32c37bf6600b796698cea66cd41

**Comment by turt2live** [comment]
Update: After opening settings and closing it (didn't change anything) I was brought to the fragment for the room. 
![image](https://cloud.githubusercontent.com/assets/1190097/26604610/16ece2da-4548-11e7-9174-3fca0058e8ae.png)

Seems like it is just too eager to go back to home?

The 'join room' button spun infinitely while matrix.org threw 403 Forbidden at me, by the way

**Comment by lampholder** [comment]
Will be fixed by the fix for https://github.com/vector-im/riot-web/issues/4123, dropping this from the ILAG project for clarity.
