### ISSUE TITLE
ILAG: Entering username clears 3pid invite

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4099]
### Description

Similar to #4097 and #4098.

This is the issue to track my email not being associated with my fresh account.

### Steps to reproduce

- See steps in #4098

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: self built
https://github.com/vector-im/riot-web/commit/64a67583e033601aedbc37f2c04c4db7dde1555e
https://github.com/matrix-org/matrix-react-sdk/commit/c15568e003a9a32c37bf6600b796698cea66cd41

**Comment by lampholder** [comment]
Will be fixed by the fix for https://github.com/vector-im/riot-web/issues/4123, dropping this from the ILAG project for clarity.
