### ISSUE TITLE
Broken image on vector.im after validating email

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4100]
### Description

![image](https://cloud.githubusercontent.com/assets/1190097/26604837/e57d233a-4548-11e7-98d8-c763f837fa44.png)

Image is https://riot.im/app/img/logo.png

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/4109

We really need to be careful of the wider impact when moving image resources :\

**Comment by turt2live** [comment]
#4109 actually looks like a duplicate?

**Comment by turt2live** [comment]
#4109 was closed as fixed. Closing this as presumed fixed as well.
