### ISSUE TITLE
ILAG: [Rare case] Land as guest, set mxid, logout, login as guest without page refresh gives password nag bar which fails

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4101]
### Description

This should hopefully be a rare case, but a bug nonetheless. Steps to reproduce should clear up the confusion left in the title

### Steps to reproduce

- Without being logged in, land on Riot. You should be presented with the welcome page
- Click something to prompt you to enter a username
- Enter a username successfully
- Note the password nag bar, but don't fulfill it
- Go to settings and click 'Logout'
- Without refreshing the page, click 'Login as guest' from the login page
- Note the password nag bar (*this is probably where the bug fix goes: hide the bar so the following doesn't happen*)
- Click 'set password'
- Enter a password and submit
- Note 401 error

I would have expected the password nag bar to not be there after clicking 'Login as guest'. Worth noting that a page refresh between logging out and clicking the login as guest button does *not* reproduce this issue. You *must not* refresh to cause this problem.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: self built
https://github.com/vector-im/riot-web/commit/64a67583e033601aedbc37f2c04c4db7dde1555e
https://github.com/matrix-org/matrix-react-sdk/commit/c15568e003a9a32c37bf6600b796698cea66cd41

**Comment by lukebarnard1** [comment]
It looks like `SessionStore` only `null`ifies its `cachedPassword` when the password is changed. Logging out should set it to `null` instead of setting it to what is in `localStorage`. 

We still don't shout loudly when a user logs out as a PWLU but this is another issue.
