### ISSUE TITLE
ILAG: Welcome page logo has serif font for ".im"

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4108]
![2017-05-31-103344_144x122_scrot](https://cloud.githubusercontent.com/assets/6750344/26625668/b9b40292-45ec-11e7-8c6e-a549cf46275b.png)

**Comment by lampholder** [comment]
This could have been an intentional choice to avoid its scanning as RIOTIM; worth checking though (the serifs do look wrong to me)

**Comment by lampholder** [comment]
Hi @ara4n - assigning this to you in case you have the skills and tools to do it quickly.

**Comment by ara4n** [comment]
will fix in a sec

**Comment by ara4n** [comment]
fixed.
