### ISSUE TITLE
Electron linux VoIP call initiation not working.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4112]
Placing a call, both in a room or direct chat, from the Linux desktop app doesn't ring the other person in the conversation. Receiving a call works, but when you accept the call, it will keep on ringing for the other person, never establishing a connection

**Comment by t3chguy** [comment]
Is this from a rageshake? I have no issue with this :/

**Comment by lampholder** [comment]
Yeah, from a rageshake :(

**Comment by lampholder** [comment]
Cool - let's close; if we find people having this problem, we can dig out the original rageshake as additional data.
