### ISSUE TITLE
Riot Android keys file imported into Riot Web failed with the unenlightening message: "The operation failed for an operation-specific reason"

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4113]
According to Rich vdH importing keys cross platform _is_ supposed to work.

**Comment by richvdh** [comment]
Yes, it should work fine, and indeed does for me. I suspect this was nothing to do with it coming from Android, and just some random failure in the import.

**Comment by lampholder** [comment]
We still have the problem of the unenlightening message - is there anything more useful we could say? Bearing in mind that if this can happen, it's going to be a pretty scary moment for the end user :(

**Comment by richvdh** [comment]
I had a go at trying to improve this, in https://github.com/matrix-org/matrix-react-sdk/pull/1061, which tries to detect various plausible causes, and fall back to saying something like 'Your browser does not support the required cryptography extensions' instead.
