### ISSUE TITLE
on develop: missing translations in login screen

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4115]
![image](https://cloud.githubusercontent.com/assets/1012976/26633679/33fbfb00-45e2-11e7-9ff7-768f3f1c42c0.png)

**Comment by uhoreg** [comment]
(hope you don't mind me marking this as a blocker)

**Comment by lampholder** [comment]
Heh, this is a fairly prominent instance, I think release-blocker is highly appropriate :P

**Comment by uhoreg** [comment]
This is fixed in /staging, so closing

**Comment by ara4n** [comment]
i wonder if this was a stale cache of i18n/*.json....

**Comment by uhoreg** [comment]
Actually, it's still present on /develop, but since it isn't present on /app, then presumably it's an issue with the build process, rather than the code itself -- like a stale cache as @ara4n.  So reopening, but removing the release-blocker tag.

**Comment by ara4n** [comment]
does it go away if you force-clear your browser cache?  if you curl the i18n json in question, what are the expire headers on it?

**Comment by uhoreg** [comment]
Oh, you were talking about browser cache.  Yes, when I shift-reload, then the problem goes away.  The expire header is "Thu, 01 Jun 2017 02:35:14 GMT", which is 1 day.  Should the i18n files be stuck somehow inside the `/bundles/[hash]/` directory along with the js and css files so that it won't load stale files?

**Comment by ara4n** [comment]
closed in favour of #4136
