### ISSUE TITLE
When managing integrations the back button doesn't work

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4116]
To reproduce:
- go to a room you can manage integrations for
- click the settings cog
- click 'manage integrations'
- choose an integration to manage (perhaps guggy)
- click the back arrow but it won't do anything

![image](https://cloud.githubusercontent.com/assets/1922197/26634086/64812d74-460d-11e7-9b44-9e4b0071060b.png)

This only happens in Electron; riot web is fine.

**Comment by lampholder** [comment]
You can always click X and start again, annoying as that is.

**Comment by t3chguy** [comment]
I just had the same issue on web,
```
ComponentHeader.js:23 Uncaught TypeError: Cannot read property 'props' of undefined
```

**Comment by t3chguy** [comment]
bumping priority as it seems to affect integrations on riot-web in general.

**Comment by t3chguy** [comment]
@lampholder just re-read the OP, could you double check this on riot-web, as your last line says that
> web is fine

**Comment by t3chguy** [comment]
even weirder, found it to work on /develop/ but break same as Electron on /app/

**Comment by lukebarnard1** [comment]
So scalar is in a weird state right now as we wrangle with new things :)
