### ISSUE TITLE
ILAG: Becoming PWLU /w Email 3PID Invite

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4123]
In theory this can be achieved by storing the email tokens long enough to use when the `SetMxIdDialog` calls `/register`. If that fails, pre-fill an email input box in `SetMxIdDialog` and send that as part of the registration request. 

v2 = The input box could also appear (but empty) if `teamToken` has been supplied (this wouldn't be a 3pid invite, but rather a referral). Referral links could then point at /home instead of /register.

**Comment by turt2live** [comment]
related(?): #4098 and #4099

**Comment by lukebarnard1** [comment]
@turt2live yes, I totally forgot to reference them, they are the main reason for this issue.
