### ISSUE TITLE
MemberInfo sometimes shows Custom of 0 instead of User

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4124]
### Description

![image](https://cloud.githubusercontent.com/assets/1190097/26645541/951acfc0-45f5-11e7-86db-3c38500b54af.png)

Unknown cause. Transient failure.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I just saw this too when room member state was being updated

**Comment by turt2live** [comment]
I haven't seen this in a while. Is anyone still seeing it?

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it (on Element Web 1.7.1).

**Comment by t3chguy** [comment]
Rewritten
