### ISSUE TITLE
login screen - Tweak css for long strings?

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4127]
can we tweak the login screen CSS to support longer strings than english ones?

![image](https://cloud.githubusercontent.com/assets/8582858/26647094/17ccd932-4636-11e7-9053-2ec1a17423d6.png)

**Comment by jeangb** [comment]
I think this is related ?
![image](https://cloud.githubusercontent.com/assets/22364949/26682976/91878a54-46e2-11e7-966f-98cb7e69b12f.png)

**Comment by MTRNord** [comment]
As said in #4153 "One solution would be to change the width css to use `display: inline-block;` in combination of `min-width: x px;` (width gets changed to min-width)"

**Comment by ara4n** [comment]
i fixed this for 0.10
