### ISSUE TITLE
Feature Request for Riot Electron: Persist (send to tray) instead of closing option

### ISSUE THREAD

**Issue by JonTheNiceGuy** [vector-im/riot-web#4142]
### Description

It would be useful to be able to indicate that when you "close" the app, it should instead send it to the tray. This mirrors the behaviour of Skype for Business and Telegram.

### Steps to reproduce

Set new option "Send to tray instead of close" in the settings panel, then close the application. This should shrink to the "R" icon in the system tray (similar to selecting the "Show/Hide Riot" option in said icon). 

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: riot-web version: 0.9.10 / matrix-react-sdk version: 0.8.9 / olm version: 2.2.1

**Comment by t3chguy** [comment]
This is weird because this is the intended behaviour and has always worked for me :/
any more details about your setup might help

https://github.com/vector-im/riot-web/blob/master/electron_app/src/electron-main.js#L233

**Comment by t3chguy** [comment]
As per PM
> Huh. Turns out I needed to clear the cache and reload and it fixed it. Dunno what went on there. Close out the bug! :D
