### ISSUE TITLE
Set a default colour scheme for a self-hosted Riot instance.

### ISSUE THREAD

**Issue by NIXOYE** [vector-im/riot-web#4146]
Hi, I'd like to change the default color of the theme from the green to a custom purple so visitors to my web client automatically see the custom purple. How could I achieve this?

**Comment by tessgadwa** [comment]
It is really difficult because the .svg icons right now are hard-coded to be green. A better scheme would be to have the icons be semitransparent or have multiple icon image sets for multiple themes.

**Comment by NIXOYE** [comment]
@tessgadwa how can i change the stuff that changes when switching from light to dark theme that would be enough for now

**Comment by tessgadwa** [comment]
If it's an image icon, you can't change it using the current theming setup which is pretty primitive, really more of a workaround. I'm working on adding the ability to swap out icon images using CSS attributes -- hopefully finish this week. Will let you know when I have something you can test!

**Comment by NIXOYE** [comment]
awesome, I'd also like to point out that the arrow in the top right to bring out the user menu is facing the wrong way. It should be pointing right to hide the menu and left to bring out the menu. This is more intuitive and is how the arrows work for the room names.

**Comment by tessgadwa** [comment]
Good to know. That would be a great thing to log as a separate issue, if you feel so inclined.  : )

@ara4n

**Comment by tessgadwa** [comment]
Also check out https://riot.im/app/#/room/#designUX:matrix.org for further theming discussions.

**Comment by NIXOYE** [comment]
Just noticed the "Room Color" option. How does this work? couldn't I change the colors however this works? Also, is it possible to make my web client use dark theme and purple room color by default?

**Comment by NIXOYE** [comment]
Any update on how one would setup the dark theme and room color to be
different by default?

**Comment by lampholder** [comment]
Hi @NIXOYE - to clarify, are you running your own Riot instance and just want to know how visitors to the whole instance can see a different theme/colour option chosen by default (across all rooms)?

**Comment by NIXOYE** [comment]
Exactly

**Comment by turt2live** [comment]
This should be supported by granular settings on develop by adding this to the config.json:
```
"settingDefaults": {
    "roomColor": {
        "primary_color": "#a442f4",
        "secondary_color": "#cc92fc"
    }
}
```

However it doesn't work at the moment due to some bug (I'm going to repurpose this issue for tracking it instead of opening a new one).
