### ISSUE TITLE
expand/collapse buttons for side panels are confused

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4148]
the button for the left side panel points outward to collapse and inward to expand, whereas for the button for the right side panel it is the opposite way

**Comment by turt2live** [comment]
Which way is the preferred way? Personally I like the left side where the arrow points in the direction of the action to come.

**Comment by krombel** [comment]
>Personally I like the left side where the arrow points in the direction of the action to come.

me too

**Comment by lugino-emeritus** [comment]
I also think the top right arrow should point in to the other direction. Moreover the arrow should be left from the symbol which shows the number of room members.

**Comment by uhoreg** [comment]
One option would be to collapse the right-hand bar instead of completely hiding it, and leave icons for the different functions like, so that it behaves a bit more like the left-hand bark, so that it looks like:

> **<**
>  👤
> 📄 
> 🔔 
> [blank space]
> 👤 +

when collapsed, and then the top would look like

> **>** [blank space so that icons are right-aligned]  👤 📄 🔔 

when expanded. (apologies for the emoj-art)

**Comment by lugino-emeritus** [comment]
uhoreg: this would be perfect

**Comment by turt2live** [comment]
They're gone!

**Comment by afranke** [comment]
> They're gone!

Yay. I can see how to get rid of the right side panel (by clicking on the currently selected tab) but I don’t see a way to collapse the left one anymore. Is that gone too?

**Comment by jryans** [comment]
You can drag to minimize the left panel, but not fully hide it currently.
