### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4151]
Login screen:
![image](https://cloud.githubusercontent.com/assets/8582858/26703094/e7691978-471f-11e7-97a1-5ffd8bf4199c.png)

Room settings:
![image](https://cloud.githubusercontent.com/assets/8582858/26704515/8513f45c-4727-11e7-9ddd-4f67d2e0cef4.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26703789/56ce620c-4723-11e7-976b-e4443adb5188.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26703804/691d765a-4723-11e7-9363-8bf63a8b1be3.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26703831/7f45fcae-4723-11e7-9690-01653149431b.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26703842/8e639426-4723-11e7-8a97-771b8ba3ce97.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26703870/b13d67ba-4723-11e7-9d19-0ec44653c8a1.png)

Member details:
![image](https://cloud.githubusercontent.com/assets/8582858/26703897/d1f1e3fa-4723-11e7-9090-812cf31901e2.png)

![image](https://cloud.githubusercontent.com/assets/8582858/26703916/ed43a986-4723-11e7-88cd-edade289295d.png)

User settings:
(adding bad phone number)
![image](https://cloud.githubusercontent.com/assets/8582858/26703977/3a9bad96-4724-11e7-9c58-6047ee42ada3.png)

(trying to delete a device)
![image](https://cloud.githubusercontent.com/assets/8582858/26704020/8adfa334-4724-11e7-92c1-168a09256667.png)

Encryption
![image](https://cloud.githubusercontent.com/assets/8582858/26704204/72dc7b30-4725-11e7-9d9c-f43406eaf7be.png)

Import new keys:
![image](https://cloud.githubusercontent.com/assets/8582858/26704128/183b2bcc-4725-11e7-94c3-935b06783cea.png)
 
![image](https://cloud.githubusercontent.com/assets/8582858/26704111/feef66ba-4724-11e7-9d2a-8f8027c784f0.png)

Logout warning
![image](https://cloud.githubusercontent.com/assets/8582858/26703143/1ab9f914-4720-11e7-8e2f-1bca371c42da.png)

Guests setting display name:
![image](https://cloud.githubusercontent.com/assets/8582858/26703345/1eb67f5a-4721-11e7-9d1b-db532c0b6dae.png)

Start a chat:
![image](https://cloud.githubusercontent.com/assets/8582858/26703423/8700a8ba-4721-11e7-8705-d591f65689bc.png)

Launch conference call:
![image](https://cloud.githubusercontent.com/assets/8582858/26703509/eecdcf18-4721-11e7-9c9c-80219a837958.png)

Guest starting a voice conf:
![image](https://cloud.githubusercontent.com/assets/8582858/26703526/04d57c34-4722-11e7-9531-1c29afcba66d.png)

Register screen:
![image](https://cloud.githubusercontent.com/assets/8582858/26703570/304d25a6-4722-11e7-9878-137736627c8c.png)

Lost pwd screen:
![image](https://cloud.githubusercontent.com/assets/8582858/26703629/7d4d7f04-4722-11e7-9148-215bda35d759.png)

Leaving a room:
![image](https://cloud.githubusercontent.com/assets/8582858/26703684/c3efe136-4722-11e7-9944-bc0c8db57e3f.png)

**Comment by Kegsay** [comment]
I've been approaching this from the other end by looking at the code. When I've finished with that I will xref with this issue to make sure I got these ones. Expect this today.

**Comment by Kegsay** [comment]
- "Unable to parse phone number" is from Synapse.
- "Export E2E room keys" needs a french translation. Set to english currently.
- "Import" needs a french translation. Set to english currently.
- "No file chosen" doesn't appear in riot-web at all, might be a browser thing?
- "Header line not found" is a tech error thrown by `MegolmExportEncryption` and probably shouldn't be shown directly to the user.

The rest have been done on https://github.com/matrix-org/matrix-react-sdk/pull/1005

**Comment by AmandineLP** [comment]
Strings updated
