### ISSUE TITLE
e2e 'Verify' button too small in German

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#4153]
![image](https://cloud.githubusercontent.com/assets/1389908/26720293/8aee518a-477f-11e7-99ae-9a47fd333237.png)

Shouldn't the button scale as the contents get bigger?

**Comment by aaronraimist** [comment]
Fixed 
<img width="446" alt="Screen Shot 2020-01-04 at 7 27 11 PM" src="https://user-images.githubusercontent.com/5855073/71773745-43264400-2f28-11ea-96cd-6be331638512.png">
