### ISSUE TITLE
JS Error with 0.10: `SyntaxError: missing ) after argument list` when launching riot-desktop

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#4161]
### Description

When trying to launch Riot after 0.10 upgrade (desktop), it crashes right away. I always had issue when upgrading versions, and generally was able to solve them, but here I can’t see what I’m missing.

### Steps to reproduce

- Upgraded to 0.10
- Launched Riot (desktop)

```
/usr/lib/riot/electron_app/src/electron-main.js:199
electron.ipcMain.on('settings_get', async function(ev) {
                                                                ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:280:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:322:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.10.0

**Comment by ArchangeGabriel** [comment]
(I’ve edited the log that was missing the first three lines…)

**Comment by t3chguy** [comment]
@ArchangeGabriel you will need to update your Electron version to one which comes with Node 7+
I believe thats Electron 1.6.2+ or Electron 1.6.8 (I can never remember)

**Comment by t3chguy** [comment]
basically your issue is caused by electron having no reason to update as its not a direct dep, #4149

**Comment by ArchangeGabriel** [comment]
Hum, then it’s just a case of Arch not being up-to-date: https://www.archlinux.org/packages/community/x86_64/electron/… Or even way out-of-date in this case. Thanks for this information, will ping the packager responsible for it.

**Comment by t3chguy** [comment]
oh yeah that version of electron is quite far out, the official Riot builds are built against electron 1.6.8 (https://github.com/vector-im/riot-web/blob/master/package.json#L147)

**Comment by t3chguy** [comment]
@ArchangeGabriel I know nothing about Arch but is it not possible for you to install Electron from https://www.npmjs.com/package/electron ?

**Comment by ArchangeGabriel** [comment]
@t3chguy You can always install anything linux-compatible on your system. But our philosophy at Arch is to only install distro packages, and thus to create one if there is none. And honestly this is almost the policy of any Linux distro. :)

Especially, if I installed electron from upstream, that would work for me, but what about all other Arch users? They would have to do the same (without this being handled by the dependencies system), and if they use whatever other program depending on electron, this would break the dependency because they would have to remove the electron package from their system to install upstream one.

The simple solution is just to update electron in the distro. ;)
