### ISSUE TITLE
Add setting to hide your status

### ISSUE THREAD

**Issue by nvbln** [vector-im/riot-web#4181]
Just like the title says, it would be nice if there was a setting to hide your offline/online status. Adding to this, it would also be nice if it is possible to disable the message read functionality (where the icon goes to the last message that you've read).

**Comment by MTRNord** [comment]
Not sure if this is what you want but in the develop version is a "Hide read receipts" option

**Comment by nvbln** [comment]
Yes it is what I meant with disabling the message read functionality.

Thanks for the quick response. :)

**Comment by t3chguy** [comment]
I think the other half of this is #1528
Custom status meaning you could just set your presence to whatever you want essentially hiding it

**Comment by nvbln** [comment]
Yes, it's not exactly what I meant, but as you said, it does what I want it to (I was even thinking of referring to Skype's ability to change your status, which is the same as what is mentioned in #1528).

Thanks for pointing that out. :)
