### ISSUE TITLE
Riot icon breaks Windows volume mixer

### ISSUE THREAD

**Issue by JKingweb** [vector-im/riot-web#4185]
### Description

The Riot icon is displayed at an enormous size in the Windows volume mixer, pushing the actual volume controls for Riot beyond reach.

### Steps to reproduce

- Receive a notification
- Open the volume mixer
- Try to adjust Riot's volume, see this:
![image](https://cloud.githubusercontent.com/assets/89590/26761920/62afec00-4906-11e7-80be-2ea6c7ec263c.png)

### Version information

- **Platform**: Desktop (0.10.1, apparently)

For the desktop app:

- **OS**: Windows
- **Version**: 10.0.15063

**Comment by t3chguy** [comment]
Yeh I'm midway through fixing it, #4183

**Comment by JKingweb** [comment]
Oh, great!  Thanks. :)

**Comment by ara4n** [comment]
fixed by @t3chguy - thanks!

**Comment by t3chguy** [comment]
(broken and fixed by @t3chguy) :')
