### ISSUE TITLE
The ellipsis on "is typing" / typing notification has gone missing

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4194]
The typing notification used to read "Alice, Bob and 5 others are typing..." but now it reads "Alice, Bob and 5 others are typing" (no ellipsis). This happens regardless of _who_ is typing and this is probably a i18n regression.

**Comment by t3chguy** [comment]
Weirdly looking at the diff it does not look like it was removed by i18n
https://github.com/matrix-org/matrix-react-sdk/commit/d419c42a4f32b993dcf3e2d5c674f83c41490a85#diff-71f7d4f3110b4062b13bf9be7fb8c3aeL67

**Comment by t3chguy** [comment]
/me queues up a build of 0.9.0

**Comment by t3chguy** [comment]
is it possible you were thinking of this:
![image](https://cloud.githubusercontent.com/assets/2403652/26789951/dec42442-4a09-11e7-8542-780ce6c7ce2b.png)

**Comment by lukebarnard1** [comment]
Maybe I totally imagined that this was a thing. It's a thing on mobile... oh well
