### ISSUE TITLE
Feature request: person icon in "people" room should change color based on presence

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#4199]
Matrix already exposes (online/unavailable/offline) presence, it would be nice if the icons in the room list changed color based on that presence rather than staying green all the time.

**Comment by turt2live** [comment]
How should chats with multiple users be handled? Any room may arbitrarily be tagged as a 1:1 chat, even if it is not. 

Example cases:
* Me, friend, and giphy
* Me, friend1, and friend2 (because I want to have the conversation under "People")

**Comment by uhoreg** [comment]
Relying just on colour change may not work so well for people who are colour-blind, so we may want to add some additional method of indicating presence.

**Comment by jfrederickson** [comment]
@turt2live Didn't see it before, but looks like this came up in the general UX thread: https://github.com/vector-im/riot-web/issues/2984#issuecomment-305218884

...in which one suggestion was to have a "multiple people" icon for rooms with more than one person.

@uhoreg That's fair. I'd note that there are other features that may not work well for colorblind people as well - red vs. (default) green for the unread notifications counter, for example. It may be worth considering dedicated color schemes for varying types of colorblindness. (Custom theme support would take care of a lot of this.)

Alternatively, many messengers use a person icon with a clock on it to mean "away" and so on - that would also be reasonable, though the icon may be too small for that to make sense. You could maybe use meaningful icons by themselves (without a "person" icon), in which case I think the sensible thing to do for a "people" room with more than two members is to just not show a presence icon at all.

**Comment by turt2live** [comment]
Having bots in rooms causes other issues, such as the room name (https://github.com/vector-im/riot-web/issues/3087). Part of the fix for that would help address the concern of a 1:1 with someone including a bot, I suppose.

**Comment by MurzNN** [comment]
As workaround maybe we can display status of first user in room list for private rooms, or first room admin?

**Comment by MurzNN** [comment]
We can show status of second user if room market as direct and with 2 users. And for direct rooms with more that 2 users - very often private chats contain only bots that have no admin permission, so room have only 2 admins and we can show status of second admin of room (or user with max permissions excluding current user).

**Comment by Biep** [comment]
What about showing a tiny pie chart?  Full disk if all members (not counting oneself) are present, fully absent if none are?  Maybe even part of it in a different colour if that is the room they are perusing right now?

**Comment by heylix** [comment]
If you showed a pie chart and had a lot of users in the chat, but some of them offline for weeks, the pie chart would never be full. Maybe there could be some threshold based on the median offline time?

**Comment by Biep** [comment]
It should show availability rather than presence, and availability is something that should be settable per user, per room.  During work hours, I may only be available to my customer/neighbour in the business rooms, not in the leisure rooms.

**Comment by panki27** [comment]
Any progress on this yet? It's the biggest "feature" I'm missing from the desktop client. I feel like the problem here is trying to find the "one fits all" solution instead of implementing something basic first (show a green dot when *somebody* in the room is online).

The screenshots on https://about.riot.im/ show a green dot (which I assume means the person in question is online). Is this a fake? Is this only implemented in web?

**Comment by t3chguy** [comment]
Part of the issue is the matrix.org server has disabled presence support due to performance issues, so even if that design was implemented it wouldn't work as expected for a huge amount of people

**Comment by iuliuh** [comment]
AFAIK the server has the presence disabled by default but it can be enabled by the server admin. How about build the feature and let the server owner decide on enabling the feature or not. Because for organizations which host their own server for their companies and for small teams this is really a huge thing to have.
All chat clients have this feature with no exception. I can't think of a chat client lacking this feature other than Riot.

**Comment by t3chguy** [comment]
It's enabled by default in synapse

**Comment by iuliuh** [comment]
Then this is another reason, if there weren't enough, that this should be a high priority feature.

**Comment by panki27** [comment]
@t3chguy I don't really think thats part of the issue.
Matrix is supposed to provide decentralised communication - if everyone is using matrix.org, then it's not decentralised. 

And yes, presence is in fact enabled by default on `matrix-synapse`. I agree with @iuliuh here as I have this exact constellation at work... I brought in Matrix and Riot as a way to handle internal communication, and this is an important feature a regular end user wants and expects to be there.

**Comment by t3chguy** [comment]
I'm having a little play with this:

![image](https://user-images.githubusercontent.com/2403652/71180886-ffb2b100-226a-11ea-9a6e-96890d77c291.png)

**Comment by iuliuh** [comment]
This looks awesome! :grinning: 
Any idea when we could see it upstream? :P

**Comment by t3chguy** [comment]
It is blocked on an existing PR, the designer also must sign off on it, with it being the holidays a little while.

**Comment by iuliuh** [comment]
Well, there is hope. As long as it will reach upstream in the next months, it's worth the waiting! :)

**Comment by iuliuh** [comment]
I've subscribed to the pull request. Can't wait.

**Comment by c33s** [comment]
just for googlers: this feature is not enabled on matrix.org for performance reasons
