### ISSUE TITLE
room context menu gets cut off at bottom of screen

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#4205]
so you can't use it on your bottom-most rooms

**Comment by richvdh** [comment]
![image](https://cloud.githubusercontent.com/assets/1389908/26818900/74911da6-4a94-11e7-893b-9119cc6ceeee.png)

**Comment by t3chguy** [comment]
Related or duplicate of #3792

**Comment by richvdh** [comment]
thanks t3chguy
