### ISSUE TITLE
After installing the fresh web app my room/people list didn't sync until I cleared the cache

### ISSUE THREAD

**Issue by croulibri** [vector-im/riot-web#4208]
I installed the new web app in my share hosting server.
I have my HS (synapse latest version) on personnal Yunohost server.

On the first connexion to my Riot Web 0.10.1 I can't see any room / direct chat.

If I clear the cache and refresh, then all rooms appear again, but my direct chat (PEOPLE) preference disappeared (I have to set them up as direct chat again) and the low priority room preference also (have to drag them again.
The mess up is then sync to the server because the organisation of my room as direct chat / low priority rooms disappear when I connect back to the old version of Riot Web.
My browser language preference is French.

Then following connexions to my web app and my server don't face again this problem of room that have disappeared, only the first time/connexion.
Other people who connect to my web app on my server don't face any more this problem.

To be complete, I have to say that when I connect to my matrix.org account, through the web app I have installed on my server, I don't face this problem.

Seems similar to https://github.com/vector-im/riot-android/issues/1281

**Comment by ara4n** [comment]
we're just doing a hotfix for this.

**Comment by ara4n** [comment]
fixed in 0.10.2 (hopefully)
