### ISSUE TITLE
Forgot password page broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4210]
### Description

It loads infinitely and never gives you a forgot password page. Only applies when going to the fragment directly. The 'forgot your password' link from the login pages appears to be okay. 

This direct link is [included in communications from riot](https://email.t2bot.io/m/cfbe24d6-4bea-49c4-aa67-3de9ff10745b) and may be higher priority as such.

### Steps to reproduce

- In an incognito, or otherwise fresh session, navigate to https://riot.im/app/#/forgot_password (or on /develop)

I would have expected that going to the link directly will allow you to reset your password.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop and riot.im/app

**Comment by ara4n** [comment]
thanks - we're releasing a hotfix :(

**Comment by dbkr** [comment]
Now fixed in 0.10.2
