### ISSUE TITLE
member info is still broken

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4223]
![image](https://user-images.githubusercontent.com/8582858/26887783-db6fce02-4ba0-11e7-80fa-603ff3dff7c9.png)

Can we also hide the device list while we're at it?

**Comment by turt2live** [comment]
related: https://github.com/vector-im/riot-web/issues/3050

**Comment by ara4n** [comment]
hopefully fixed by matrix-org/matrix-react-sdk#df625b0d318661ba64d2b1155651204f3219f7bf
