### ISSUE TITLE
Failed to load timeline when viewing a room scrolled back in time and then swapping to another room

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4224]
- Go to a room and jump to a message in the past
 - Swap to any other room
 - Swap back to the original room
 - Swap to any other room
 - See Failed to load timeline position

**Comment by richvdh** [comment]
Another repro case:

* Do a search, 
* follow a result, 
* switch to another room, 
* observe error

**Comment by richvdh** [comment]
From #riot-dev:

>this is happening because MatrixChat's `_onRoomViewStoreUpdated` is firing before onAction, which means it is trying to mount the new RoomView while `state.initialEventId` still points to an event in the old room
>
> I guess the problem here is that `initialEventId` is in the state, so gets stuck, but I don't know how else you are meant to pass one-off parameters into subcomponents
>
> in general, setting `state.currentRoomId` without setting all the other things that get set in _viewRoom feels like it's going to go wrong

**Comment by ara4n** [comment]
tested the repro case above and it seems to be working now - yay! but the performance is at least twice as worse for rooms which are scrolled up; boo :(( have filed https://github.com/vector-im/riot-web/issues/4255 for this one though.
