### ISSUE TITLE
Login button is hidden if LeftPanel is collapsed in ILAG

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4227]

**Comment by ara4n** [comment]
putting as P2 as it's fairly unusual to collapse LeftPanel, and you can always login via the SetMxIdDialog

**Comment by ara4n** [comment]
To fix this, please can we just jump to the solution from the redesign - it doesn't need to cosmetically look right, but the idea is to just chuck the login & register buttons in the messagecomposer space for this scenario (given we can't send messages when we're a guest)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2219
