### ISSUE TITLE
numeric user ids shouldn't be reserved to guest users anymore

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4228]
![image](https://user-images.githubusercontent.com/8582858/26894198-90710816-4bb5-11e7-9c89-e3c1dfe09b50.png)

**Comment by ara4n** [comment]
i'd prefer that we kept this (not least because under the hood, we're still creating guest accounts for read-only access, before we replace them with proper accounts now).  Was there a reason particularly to allow numeric mxids?

**Comment by AmandineLP** [comment]
Just felt useless to set limit for the users for no reason. But if we're still using them then yeah let's keep it
