### ISSUE TITLE
Couple issues with develop homepage

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4230]
### Description

This is just a point of reference for tracking.

* [x] Text hard to read (dark theme)
   ![image](https://user-images.githubusercontent.com/1190097/26894853-db8a18da-4b7c-11e7-8873-b4015bb88c8e.png)

* [x] No icon/letter in circle:
   ![image](https://user-images.githubusercontent.com/1190097/26894863-e40e81c6-4b7c-11e7-9e49-331c5ad65bc8.png)

* [x] iOS room icon outdated
   ![image](https://user-images.githubusercontent.com/1190097/26894934-1e7b332c-4b7d-11e7-856e-0067769ee5c5.png)
   versus
   ![image](https://user-images.githubusercontent.com/1190097/26894945-2922e11c-4b7d-11e7-9d66-87f72bd7665e.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by MTRNord** [comment]
About the Translations Channel. If anyone got a Logo for it I can add it :) I guess thats why it doesn't show a Logo yet

**Comment by uhoreg** [comment]
MTRNord: for a translations logo, maybe something along these lines:
![riot-world](https://user-images.githubusercontent.com/1012976/26994345-4159b1ac-4d35-11e7-95b2-72383416813b.png)
(though I'm sure someone with better graphics skills can do something nicer)

**Comment by MTRNord** [comment]
@uhoreg As I like that I will add it for now in the channel :+1:
