### ISSUE TITLE
clicking on 'chat with riot bot' only works once

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#4233]
click, cancel dialog, click again, nothing

**Comment by ara4n** [comment]
...if you're not yet logged in.  (if you're already logged in, the clicking works as expected).
Still broken atm.

**Comment by lukebarnard1** [comment]
This is because we use /user/.. and cancelling the set mxid won't reset the URL. One possibility is going "back" in history but not all code paths to open setmxid will include a change to the URL hash.
