### ISSUE TITLE
username checker lets you enter invalid names

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#4234]
In 'please pick a username' dialog, if you put a name with invalid characters, it says it is available

**Comment by lukebarnard1** [comment]
Could you give some examples? I cannot reproduce this... 

![2017-06-08-225347_595x201_scrot](https://user-images.githubusercontent.com/6750344/26952452-6db8bd4e-4c9d-11e7-9578-79981eda4e97.png)

**Comment by richvdh** [comment]
Hum. Nor can I. Strange.
