### ISSUE TITLE
Riot doesn't work with Tor Browser 7 anymore

### ISSUE THREAD

**Issue by ollieparanoid** [vector-im/riot-web#4238]
### Description
Tor browser has been upgraded to version 7 today:
https://blog.torproject.org/blog/tor-browser-70-released

* When I open a riot page ( https://riot.im/app/ or https://chat.disroot.org/ ), a warning with a red background appears:
> Sorry, your browser is not able to run Riot.
>
>Riot uses many advanced browser features, some of which are not available or experimental in your current browser.
>
>Please install Chrome or Firefox for the best experience.Safari and Opera work too.
>
>With your current browser, the look and feel of the application may be completely incorrect, and some or all features may not function. If you want to try it anyway you can continue, but you are on your own in terms of any issues you may encounter!
* When I click on "I understand the risks and wish to continue", I get a blank page with a spinner icon and nothing happens
* Security is set to "high" in TOR Browser, which means I need to enable Javascript for the page manually after loading ("Temporarily allow all this page")
* I suspect, that his happens because of Javascript hardening in Tor Browser?

### JS Console output (F12)
* this stands out: `TypeError: asm.js type error: Disabled by 'asmjs' runtime option  olm.js`
```
downloadable font: download failed (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:0): content blocked source: https://riot.im/app/fonts/Open_Sans/OpenSans-Regular.ttf  theme-light.css:1:66588
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  olm.js
Browser missing feature: 'indexeddb'  bundle.js:81:18562
	C</<.value/</e[r] https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:81:18562
	i https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:1:1372
	<anonymous> https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:1:5763
	<anonymous> https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:1:801
	t https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:1:102
	<anonymous> https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:1:777
	<anonymous> https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:1:2
"Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome."  bundle.js:81:18562
All candidate resources failed to load. Media load paused. app
set language to en  bundle.js:81:18562
User has previously accepted risks in using an unsupported browser  bundle.js:81:18562
"Vector starting at https://riot.im/app/"  bundle.js:81:18562
No previous session found.  bundle.js:81:18562
"Doing guest login on https://matrix.org"  bundle.js:81:18562
Unable to load session Error: must pass indexedDB into IndexedDBCryptoStore
Stack trace:
e@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:118:973
@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:32:8248
e.exports.createClient@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:118:9309
a@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:85:28512
i/<@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:85:28002
r@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:27:8950
g.prototype.then/</<@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:27:9223
g/r.promiseDispatch@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:27:2944
g.prototype.then/<@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:27:9174
r@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:27:6501
e@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:27:6439
o@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:81:7943
a@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:81:8121
u/n@https://riot.im/app/bundles/927be34866a1b2ae3fe2/bundle.js:81:8480
  bundle.js:81:18562
Error: must pass indexedDB into IndexedDBCryptoStore  bundle.js:118:973
Initialised anonymous analytics  bundle.js:81:18562
XML Parsing Error: syntax error
Location: https://riot.im/app/version?cachebuster=1496876489400
Line Number 1, Column 1:  version:1:1
XML Parsing Error: syntax error
Location: https://riot.im/app/version?cachebuster=1496876489500
Line Number 1, Column 1:  version:1:1
TypeError: n is null[Learn More]  bundle.js:146:10921
TypeError: n is null[Learn More] bundle.js:146:10921
```

**Comment by ara4n** [comment]
Ugh. I think the smoking gun here is actually:
`Browser missing feature: 'indexeddb'  bundle.js:81:18562`

We rely on indexeddb these days to store local state for encrypted room history as well as e2e encryption keys. I am surprised and sad if the Tor browser disables it, given it's no better/worse than localstorage in terms of privacy, as far as I know.  And it's really not unreasonable these days to expect a webapp to want to store state clientside!

**Comment by ollieparanoid** [comment]
What should we do? Reach out to the tor browser devs and ask if they re-enable it? Or could you code up a workaround (doesn't seem feasible from what you write=?

**Comment by ara4n** [comment]
Looks like you can manually enable indexeddb in the browser advanced config and then everything works fine:

<img width="977" alt="screen shot 2017-06-08 at 00 22 11" src="https://user-images.githubusercontent.com/1294269/26905683-97796bf0-4be0-11e7-98ea-73f153726448.png">

**Comment by ollieparanoid** [comment]
Thanks, that was super fast support! I'll add a comment to the release news with this ticket!
