### ISSUE TITLE
Forgetting room issues for guests

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4246]
New guest user
I join a room (set a name on the way)
I leave the room 

- [ ] **bug 1: if i leave the room from the room settings the settings should hide, today they stay visible. If 
i do it from the room list it works well**

-> the room moves to historical and goes to peeking mode (wrong behaviour, see #4244 )
I forget the room by clicking on the small door icon in the top right 

- [ ] **bug 2: nothing happens in the room view, I'm still seeing the room in preview mode => I should be redirected to home**

-> the room disappears from historical (expected behaviour)
I go to home
I open the settings then close them

- [ ] **bug 3: the room reappears in the historical section and I'm dumped into this room in preview mode => I should just go back to home**

this sounds pretty much like all the same navigation issue where home is not considered as the default landing when there are no other rooms in the room list

**Comment by lukebarnard1** [comment]
I think these are fixed now
