### ISSUE TITLE
read receipts disabled, space in right-hand margin of timeline is wasted

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4248]
when someone switches off the showing off read receipts, we could make the event width wider to occupy the now wasted space

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/1633

**Comment by uhoreg** [comment]
This issue doesn't show up when I search for "receipt".  Hopefully, by writing this comment with "receipt" in it, it will now show up.

**Comment by meain** [comment]
This still seems to be the case in IRC style layout.

**Comment by SimonBrandner** [comment]
@meain, please open a new issue for that
