### ISSUE TITLE
"No known servers" when joining external rooms on Riot

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4251]
### Description

Something in the join process in Riot seems to be corrupting or otherwise failing to allow Synapse to join rooms. This affects invites, `/join`, and the join button a peek/preview.

This seems to only affect external rooms (federation). This appears to be riot-specific as curl (at least) allows me to join rooms.

### Steps to reproduce

- Attempt to join `#_twitter_#dogsatpollingstations:t2bot.io` or some other room
- Receive "no known servers" error

Log: sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 
- **URL**: riot.im/develop

**Comment by non-Jedi** [comment]
If this is the same issue I (@adam:thebeckmeyers.xyz and @abeckmeyer:matrix.org) am experiencing, joining small rooms or rooms with local aliases seems to work fine (in my case #gyr:matrix.org). You can also join a room without problem once you are invited to it.

riot.im/app does not seem to have this same issue.
