### ISSUE TITLE
loading RoomView which is scrolled to a point in the past is ~2x slower, and flashes non-gemini scrollbar and spinner

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4255]
i think it used to load much more quickly?

**Comment by uhoreg** [comment]
FWIW, the non-gemini scrollbar (or, rather, the presence of a scrollbar at all) is reported in #4121

**Comment by ara4n** [comment]
i think that non-gemini scrollbar may have a different root cause, fwiw.

**Comment by ara4n** [comment]
vdh's fix seems to be working well for this - thanks.
