### ISSUE TITLE
Nickname auto-completion should have priority rules

### ISSUE THREAD

**Issue by devnoname120** [vector-im/riot-web#4267]
### Description

Nickname auto-completion indiscriminately puts the nicknames of people who are not active on the channel with people who are active, which makes it less useful in my opinion.

There should be priority rules, for instance:
- Matches the whole nickname
- Matches the start of the nickname
- Matches anywhere in the nickname
- People who last talked
- People who last connected

### Steps to reproduce

- Go into #henkaku
- Type `xyz` and then press `<tab>`.
- It's auto-completed to `xyzz` even though this one never speaks here and I want it to auto-complete to `xyz`.

Log: No.

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 0.9.10

**Comment by dbkr** [comment]
Is this with the rich text editor or the normal one?

**Comment by lampholder** [comment]
@dbkr does the RTE already have some sort of prioritisation feature?

**Comment by devnoname120** [comment]
@dbkr This was with the normal one. I didn't test the new editor to see whether it has the same issue or not.

I can't reproduce my example right now (even with the basic editor). I'm not sure if the issue is fixed or not.

**Comment by lukebarnard1** [comment]
The new editor puts people who have spoken recently first, even if they don't really match the query used to tab-complete. I'll work on this today,

**Comment by lheckemann** [comment]
I can't see this behaviour, for me typing gc when "gchristensen (IRC)" last sent a message still suggests "grahamc" first, with the new editor enabled.

**Comment by t3chguy** [comment]
@lheckemann:
> with the new editor enabled

this implies you are using riot.im/app (or an eq thereof)
the RTE has had ***MANY*** changes in the current release candidate, or on riot.im/staging if you'd like to have a play

**Comment by lheckemann** [comment]
That is indeed much better, thanks for the pointer!

**Comment by t3chguy** [comment]
no problem!

**Comment by lampholder** [comment]
Looks like this can be closed :)
