### ISSUE TITLE
room avatar in eventtile incorrect

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4268]
![image](https://user-images.githubusercontent.com/2403652/27005029-3fb45964-4e0d-11e7-9d0b-ae84ade7ce55.png)
avatar in top right changed properly but the one in the event tile at the bottom did not
confirmed that the image at the mxc: is correct

**Comment by ara4n** [comment]
erm, i'm lost. which top right?

**Comment by t3chguy** [comment]
apparently I don't know left and right, top left

Avatar in top left is the correct one
but the room change event says "changed the room avatar to <>" which does not match

**Comment by t3chguy** [comment]
Better screenshot:
![image](https://user-images.githubusercontent.com/2403652/27078648-612f4e02-502c-11e7-8b5a-069aaf7f085b.png)

**Comment by t3chguy** [comment]
another note, clicking the wrong avatar opens the correct one in the lightbox.

**Comment by t3chguy** [comment]
Ah I think I found the cause:
https://matrix.org/_matrix/media/v1/thumbnail/riot.ovh/YWCmMjEpHpeBoYMbQFWnWUwR?width=17.5&height=17.5&method=crop
```
{"errcode":"M_UNKNOWN","error":"Query parameter 'width' must be an integer"}
```

**Comment by t3chguy** [comment]
fixed by referenced PR
