### ISSUE TITLE
Voip settings collide with scrollbar

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4269]
### Description

![image](https://user-images.githubusercontent.com/1190097/27005325-a8d79598-4dd9-11e7-872f-47fcf93974f7.png)

Blue emphasis is mine.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: tang.ents.ca (running v0.11.0-rc.2)

**Comment by t3chguy** [comment]
Fixed in a pr today by MTRNord

**Comment by t3chguy** [comment]
(yet to be merged)

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/pull/4266 I assume

**Comment by MTRNord** [comment]
@turt2live correct assuming ;)

**Comment by turt2live** [comment]
fixed
