### ISSUE TITLE
chat with riot-bot button on welcome-page should reuse 1:1s

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4273]
i just clicked it and it started a whole new chat rather than re-use my existing one

**Comment by turt2live** [comment]
I couldn't reproduce this:
![image](https://user-images.githubusercontent.com/1190097/27015760-12bcd892-4ed4-11e7-8468-18ce8fefa9e4.png)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8133
