### ISSUE TITLE
layout is broken after zooming on FF ESR 45.9.0 on Win10

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4274]

**Comment by ara4n** [comment]
![broken-layout](https://user-images.githubusercontent.com/1294269/27015038-a7cc4404-4efc-11e7-9798-f9a0c0b9d240.png)

Note broken centering of avatar initials, the (...) ellipsis, and the fact the RoomStatusBar overlaps the bottom of the RoomTimeline (and can't be scrolled down, most of the time)

**Comment by aidalgol** [comment]
The remaining ellipsis seems to be unrelated to the zooming, but I can't reproduce that one consistently.

**Comment by aidalgol** [comment]
This also happens in Firefox ESR 52.2.0 on my Debian 8.8 system.

**Comment by turt2live** [comment]
Is this still happening for your @aidalgol ?

**Comment by aidalgol** [comment]
No, this appears to be resolved as of riot-web 1.0.0, running in Firefox 60.5.0esr on Debian 9.7.
