### ISSUE TITLE
Application does not give option to save self signed certificate

### ISSUE THREAD

**Issue by abugandar** [vector-im/riot-web#4276]
### Description

We have our own server for testing and using within our team. We have self-signed certificate and do not want to purchase certificate for this small server. However both the riot application and the web application shows that "homeserver SSL certificate problem". 

### Steps to reproduce

- Make your own synapse server with a self signed certificate.
- Run riot with your server added in the config.json as the default server OR choose your server as a custom server
- You cannot log in any more because there is no option to accept this certificate.

Instead like any other site I was expecting to get a Invalid certificate dialogue and giving me the option to accept self signed certificates.  

Log: not sent

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Firefox Latest versions as of this date.
- **OS**: Windows 8.1 32 bit
- **URL**: Private server, riot-web version 0.10.2

For the desktop app:

- **OS**: Windows 8.1 32 bit
- **Version**: 0.10.2

**Comment by dbkr** [comment]
dup https://github.com/vector-im/riot-web/issues/3003
