### ISSUE TITLE
Sent messages stuck in pending state in e2e room

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#4278]
I've seen a couple of rageshakes from people who send a message in an e2e room, but the message gets stuck in the 'pending' (green) state forever. I haven't figured out what's causing it yet: opening this to track it.

**Comment by richvdh** [comment]
See: https://github.com/matrix-org/riot-web-rageshakes/issues/133, https://github.com/matrix-org/riot-web-rageshakes/issues/184

**Comment by t3chguy** [comment]
I have seen this once before also but did not think to look into it :/

**Comment by richvdh** [comment]
It turns out that once a device list download attempt fails (normally because of networking issues), subsequent download attempts get queued up rather than send out, and the messages get queued up waiting for them.
