### ISSUE TITLE
Can't start a new 1:1 with someone I'm already having 1:1s with

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4287]
Specifically I tested agains Matthew, but probably reproduceable against other: click on start chat in bottom left menu > find the contact > get the info I already have ongoing 1:1 with them > click 'start new discussion' and nothing happens

**Comment by lukebarnard1** [comment]
This regressed when we introduced `/user/@...?action=chat`

**Comment by ara4n** [comment]
fixed now.
