### ISSUE TITLE
The message that invites you to join a room doesn't specify the room name

### ISSUE THREAD

**Issue by mflorea** [vector-im/riot-web#4297]
### Description

I got a couple of invitations today from different people to join different rooms. The invitation message looked like this:

    You have been invited to join this room by @someUserName:matrix.org
    Would you like to accept or decline this invitation?

It says "this" room, but it doesn't say the room name. So I know who invited me but I don't know what room I have been invited to. Also, it's not clear from the message if I was invited to a direct 1-1 chat or to a group chat.

### Steps to reproduce

- Create a room and invite someone
- Ask that someone to show you the invitation message

### Version information

- OS: Ubuntu
- Homeserver is https://matrix.xwiki.com
- Identity Server is https://vector.im
- matrix-react-sdk version: 0.8.8
- riot-web version: 0.9.9
- olm version: 2.2.1

**Comment by lampholder** [comment]
I thought this was already filed somewhere, but I couldn't find it easily.

It certainly would be a big win if we could show the room name in the invite dialogue.

**Comment by turt2live** [comment]
We fixed this.
