### ISSUE TITLE
Cannot accept invites (race condition?)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4298]
### Description

This is quite the annoying regression. It appears to allow the invite to go through, but not actually work.

The chrome network pane shows that 2 initalSyncs (peeking) are fired off when clicking on the invite in the room list. When clicking accept, a join is not sent, however after the spinner goes away I'm left with one more initalSync.

This appears to be a race condition because the join is never sent to the server, and others aren't reporting similar behaviour. A page refresh did not fix the behaviour.

### Steps to reproduce

- Receive an invite to a room (1:1 or otherwise)
- Click 'Accept'

Here's a gif of what's going on:
https://t2l.io/_matrix/media/v1/download/t2l.io/mxXiGmWNzUahUwfgydiWqCcQ

Log: sent  

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1093
