### ISSUE TITLE
Trying to accept invite from `@babolivier` fails silently

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4307]
Logs reveal that there was a failed peek into the 1:1 (`!frmllkJSfSE...:matrix.org`) and the client tried to join another room, weirdly always internal regardless of previously viewed room.

**Comment by dbkr** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/4298

**Comment by dbkr** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1093

**Comment by lukebarnard1** [comment]
@AmandineLP says it's not fixed
