### ISSUE TITLE
Inaccurate confirmation title after setting up pwd only from guest 

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4311]
After setting a password and skipping the email, the Current popup says 'You've successfully set a pwd and email'. 
We can either have a custom title which says 
* "You've successfully set a pwd" when only a pwd is set 
* "You've successfully set a pwd and email" when both are set

or, the text could be more generic and something like 'you have successfully secured you account' instead

**Comment by lukebarnard1** [comment]
This is because when you cancel `BaseDialog`, it calls `onFinished` with a mouse event instead of `true/false`
