### ISSUE TITLE
/develop stopped requesting url previews

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4327]
### Description

Homeserver is configured to allow it, and other Riot instances are requesting them OK. A quick search in the network pane for things like "reddit" and "github" yield no results.

### Steps to reproduce

- Send URL in message

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: a7a7ffd84b7d-react-1f48b4caa617-js-c8674ff10403
olm version: 2.2.1
```

**Comment by dbkr** [comment]
We only set URL preview visibility in _onRoomLoaded which we now only call on onRoom, after a peek or in the conditional bit of _onHaveRoom where we stop peeking.
