### ISSUE TITLE
h2 behaves weirdly

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4328]
### Description

![image](https://user-images.githubusercontent.com/1190097/27201612-89bdbbfa-51db-11e7-9175-af73495904a6.png)

Message body:
```
# h1
## h2
### h3
```

Tried tricking it with this:
```
# h1


## h2


### h3
```

### Steps to reproduce

- Send one of the messages above

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
oh, crap. i guess the reason we coerced these to be h3's is to avoid colliding with the existing h1 & h2 CSS used in the timeline for things like day separators.

The fix is to make the h2 CSS for day separators only apply to... day separators.

**Comment by turt2live** [comment]
Yea, that's my fault for not adequately testing. Apologies.
