### ISSUE TITLE
settings are dismissed for guests after setting display name

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4329]
launch the app as guest, open settings, prompted to set a display name, set the name, click continue, once the process is complete the user is redirected to the riotbot chat while they should stay in settings

**Comment by lampholder** [comment]
@AmandineLP - I think this is one of the 'weird behaviours for guests' and should be resolved by ILAG.

**Comment by lukebarnard1** [comment]
It wasn't resolved by ILAG but created by it. Closing because it's a dup.
