### ISSUE TITLE
Room cannot be marked as read when latest message in this room is a hidden redacted message

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-web#4336]
When you enable the option to hide redacted messages and someone sends a message and redacts it before it got seen it is not possible to set this room as read. The unread-flag persist (observable by room name beeing bold) until another message gets send (and seen) or i disable the option to hide redacted messages

**Comment by richvdh** [comment]
I suspect this has causes similar to https://github.com/vector-im/riot-web/issues/1192.

**Comment by t3chguy** [comment]
I think this is fixed now

**Comment by t3chguy** [comment]
Tested, cannot reproduce which seems to match my memory of fixing it
