### ISSUE TITLE
Picture preview awkward on desktop

### ISSUE THREAD

**Issue by JKingweb** [vector-im/riot-web#4339]
### Description

The preview when clicking on an offered picture when using desktop Riot doesn't really make sense: for large images it can lead to a *smaller* than what is already visible, and is an extra, unnecessary step to viewing the full image.

### Steps to reproduce

- Have someone send an image, particularly a large one
- Click on the image, expecting to see the image at full size
- See the image at smaller size instead:

![image](https://user-images.githubusercontent.com/89590/27238741-128d03bc-529c-11e7-9c60-8d02e96f9bbf.png)

I would expect clicking on the image to either open the image in my preferred browser, or to download the image to a temporary location and then open it in my preferred image viewer, without an intermediary preview.

### Version information

- **Platform**: desktop 
- **OS**: Windows 10
- **Version**: 0.10.1

**Comment by turt2live** [comment]
This is being tracked here: #3638

**Comment by uhoreg** [comment]
closing as a dup of #3638 and/or #3638
