### ISSUE TITLE
Firefox incognito refuses to let the app load

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4340]
### Description

When using firefox in private mode (incognito), the app stays at a spinner for an eternity.
Logs: https://gist.github.com/turt2live/5e3b942ae15100d47f2c7ab463bb35aa

Probably related to #3230

### Steps to reproduce

- Open firefox in incognito mode
- Open riot

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 54 (Incognito)
- **OS**: Windows 10
- **URL**: riot.im/staging

**Comment by lampholder** [comment]
I tried this - the app loaded, allowing me to get to see the welcome page and navigate to the sign in screen. Then I signed in - so far I'm five minutes into an inifinispin.

**Comment by lampholder** [comment]
[logs.txt](https://github.com/vector-im/riot-web/files/1088206/logs.txt)

**Comment by lampholder** [comment]
Some logs pasted from my browser:

[logs.txt](https://github.com/vector-im/riot-web/files/1088216/logs.txt)

**Comment by richvdh** [comment]
Hrm. it's nothing to do with the CAS login.

It appears to be because firefox incognito doesn't support indexeddb.  (And it doesn't not support it in a useful way like making `window.indexeddb === undefined`; oh no, it just throws a deferred DOMException whenever you try to do an indexeddb operation, including deleting a database.)

I'm going to have to think about how we can detect this, and fall back to an in-memory store.

**Comment by richvdh** [comment]
TIL: whilst Indexeddb doesn't work from an incognito tab in firefox, it *does* work from a web-worker under an incognito tab in firefox.

Given it seems to work more-or-less as you might expect (doesn't share the database with non-incognito tabs, clears it out once you close incognito tabs), I'm a bit confused as to why https://bugzilla.mozilla.org/show_bug.cgi?id=781982 has been waiting for a fix for five years.

**Comment by lukebarnard1** [comment]
@richvdh can we close?

**Comment by richvdh** [comment]
yup think it was fixed by https://github.com/matrix-org/matrix-js-sdk/issues/472

**Comment by richvdh** [comment]
(oh, and https://github.com/matrix-org/matrix-react-sdk/issues/1133)
