### ISSUE TITLE
copy-to-clipboard button on code blocks plays badly with horizontally scrolling code blocks

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4341]

**Comment by lukebarnard1** [comment]
So @ollieh's copy buttons are added post-hoc to `<pre>` tags in `HtlmUtils` and that's actually the only way a copy button per code-block is possible. I'm not sure what CSS is needed here.

**Comment by t3chguy** [comment]
Fix caused worse issue: https://github.com/vector-im/riot-web/issues/6934

**Comment by lukebarnard1** [comment]
I think the solution here is to wrap the `pre` in a `div` with `position: relative` and have the copy button as a child of that div:
![2018-06-27-111113_337x87_scrot](https://user-images.githubusercontent.com/6750344/41967964-e7261fba-79fa-11e8-945c-deb3744eab76.png)
