### ISSUE TITLE
Sort room list options in sidebar

### ISSUE THREAD

**Issue by betz** [vector-im/riot-web#4343]
Have sort options in rooms overview in sidebar.
If you are in a lot of rooms, it becomes difficult to find a specific room back.
One thing which could make it more easy is have sort options.
![rooms](https://user-images.githubusercontent.com/256909/27256948-f603f57c-53c5-11e7-849f-1688556160a4.png)

Nice sort options:
- by name alphabetically
- by latest messages date (as is now)
- by amount of users

**Comment by turt2live** [comment]
#1373 will probably help with this a bit. There's also a search bar at the top of the room list that can help filter things down.

**Comment by Mebus** [comment]
This is really annoying. Can you please sort the rooms aphabeticaly. 

Thanks

**Comment by infinity0** [comment]
Sorting rooms alphabetically is the most time-efficient and pleasant and lack-of-surprises way to find information that I want, that doesn't depend on other people's behaviour that I have no control over. Please consider adding this, this would substantially improve my user experience with riot.

Right now the room list pretty much randomises itself every 2 seconds. From someone that recently joined an organisation that was invited into 20 rooms, randomising a list of 20 rooms every 2 seconds really does not help one to learn which rooms are for what purposes.

**Comment by turt2live** [comment]
the 2020 room list has this per-list sorting.
