### ISSUE TITLE
@user:server URI / contact me URI

### ISSUE THREAD

**Issue by betz** [vector-im/riot-web#4344]
Can we have a uri pointing to a @user:server
From that page you could start a new chat, for example.
This would make it easy to have your riot as a contact me link/form.

This gives the question if we want guests be able to start a new conversation.
Or do do we allow this as a setting?

It would be a nice feature anyway.

**Comment by t3chguy** [comment]
https://matrix.to/

**Comment by betz** [comment]
myeah, this would point then to https://matrix.to/#/@betz:hackerspace.be
which then points to https://riot.im/app/#/user/@betz:hackerspace.be
where you can click on 'start new chat' from the sidebar.

First of all, didn't know about https://riot.im/app/#/user/@betz:hackerspace.be
This is what I meant. But then to have a empty page with info about the user and a big button 'contact me', which would then open a new conversation.
As a person who never used matrix or anything this would be clear.

**Comment by turt2live** [comment]
In the recent builds of Riot you can have a link like https://riot.im/app/#/user/@travis:t2l.io?action=chat

**Comment by uhoreg** [comment]
see also https://github.com/matrix-org/matrix.to/issues/22 regarding the equivalent to https://riot.im/...?action=chat for matrix.to

This is related to #2373, though that issue is probably intended for rooms, rather than people.

**Comment by uhoreg** [comment]
Actually, this looks like mostly a dup of #4296.  I think that everything mentioned in this issue has been captured in other issues, so I'm closing this.
