### ISSUE TITLE
After update, every pressing 'alt' key opens the top menu

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4345]
> this is ANNOYING BUG, for example, alt+shift combination is the most popular for change keyboard layout, alt+tab for task switching.

Says user on rageshake 198 on Riot Desktop 0.10.1 on Linux

**Comment by strixaluco** [comment]
Can't replicate on Riot Desktop 0.11.3 @ Debian Stretch

**Comment by uhoreg** [comment]
can't replicate here either

**Comment by t3chguy** [comment]
nor here

**Comment by MRZA-MRZA** [comment]
I experience this *HIGHLY* annoying bug on Riot 0.11.4 on Ubuntu 17.04.

**Comment by t3chguy** [comment]
Can you provide more than your Base distribution as information. The more the better considering we cannot reproduce it, I tried on kde neon 17.04

**Comment by MRZA-MRZA** [comment]
I'm using XFCE4. What kind of information do you need?

**Comment by strixaluco** [comment]
Still not reproducible on Riot Desktop 0.11.4 on Debian Buster with GNOME Shell 3.22.3.
@MRZA-MRZA, you mean exactly <kbd>Alt</kbd>+<kbd>Shift</kbd> sequence, not the opposite (<kbd>Shift</kbd>+<kbd>Alt</kbd>)? The latter does trigger the top menu indeed.

**Comment by MRZA-MRZA** [comment]
Yes, I use Alt+Shift to switch keyboard layout.

**Comment by uhoreg** [comment]
What method are you using to make Alt+Shift switch the keyboard?

My guess is that something eats the Shift key, so Electron only sees "Alt down, Alt up", instead of "Alt down, Shift down, Alt up", and so the menu gets triggered.

**Comment by MRZA-MRZA** [comment]
> What method are you using to make Alt+Shift switch the keyboard?

What do you mean? It's default for xfce4 I guess.

**Comment by uhoreg** [comment]
OK, setting "Alt-Shift" as the "Change layout option" in `xfce4-keyboard-settings`, I can reproduce it.  If I hold down "Alt", and then hit "Shift", the menu bar immediately appears.  Interestingly, this does not happen in Firefox, which also toggles the menu bar when "Alt" is pressed.

**Comment by MurzNN** [comment]
Same problem on Ubuntu Linux and KDE wint Riot-web Desktop app: Alt+Shift changes keyboard layout, but in Riot it also activate menu, so users must manually set focus on message area for continue typing.

**Comment by MurzNN** [comment]
@ara4n from which version does this issue active? If I downgrade version - Alt will works normally?

**Comment by ara4n** [comment]
@t3chguy do you happen to know how to stop electron from intercepting `alt` like this?

**Comment by t3chguy** [comment]
only thing I can think of is to capture it ourselves, and preventDefault if it is pressed with shift, can't do it without my hands on a system that does this though, I'll try it in a VM again

**Comment by uhoreg** [comment]
FTR, it's not just Alt-Shift.  It also happens if you have XFCE4 set to use other combinations for switching keyboards, such as Alt-Ctrl, Alt-CapsLock, and Alt-Space.

**Comment by MurzNN** [comment]
Confirm that this problem exists with Alt-Ctrl, Alt-CapsLock, and Alt-Space on KDE4 too. But if I change hotkey form Alt+Shift to Alt+Ctrl - Alt+Shift combination goes to work normally (without activating menu). 

But when I press Shift+Alt (shift is first) - all works normally.

So seems the problem is with changing focus to some language switch process with Alt stay pressed in our app.

**Comment by MurzNN** [comment]
I have found same issue here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/50

**Comment by MurzNN** [comment]
And seems here is solution: https://github.com/saenzramiro/rambox/issues/120#issuecomment-244884398

**Comment by MurzNN** [comment]
I have found another file and those changes fix this issue, so I provide pull request: https://github.com/vector-im/riot-web/pull/4623

**Comment by nekomiko** [comment]
Patch fixes issue only partly. Menu no longer opens, but toggles its visibility if I:
1. press alt
2. press shift
3. unpress alt
4. upress shift
but not if I upress keys in different order. I recently updated Xorg up to 1.19.3 on Ubuntu 16.04, IIRC patch worked better before an update.

**Comment by YevgenK** [comment]
Same issue when I press alt+shift. 

Kubuntu 16.04, plasmashell 5.8

**Comment by t3chguy** [comment]
Weird, I could not reproduce on my KDE Neon installation

**Comment by MurzNN** [comment]
@nekomiko - can't reproduce this on KDE, seems this is your local issue. Now menu opens only when I press `Alt` and unpress it without other keys, so no problems. I'll try to finish pull request.
