### ISSUE TITLE
Filtering rooms in the left sidebar does not display rooms from collapsed categories

### ISSUE THREAD

**Issue by aperezdc** [vector-im/riot-web#4364]
### Description

When filtering rooms using the input box in the left sidebar, matches from collapsed room categories are not shown.

### Steps to reproduce

- Collapse a room category in the left sidebar.
- Enter a search string in the room filter input box for which results from the collapsed category would be shown.

Searching for rooms probably should show also the matches from collapsed categories without having to manually un-collapse them.

![riot-room-filter-collapsed](https://user-images.githubusercontent.com/723451/27320232-ef4a7092-559d-11e7-8e17-e2829ba474e6.gif)

### Version information

- **Platform**: Both web and Electron application.

For the web app:

- **Browser**: Any.
- **OS**: All.
- **URL**: riot.im/develop + riot.im/app 

For the desktop app:

- **OS**: All.
- **Version**: 0.9.10

**Comment by lampholder** [comment]
This _does_ seem unintuitive.

The opposite behaviour would be to show all matches in all categories (probably including 'Historical'). It might be best to mock this up and see whether it feels 'right', though my instinct is that it would feel better than the current behaviour.

Even thinking to the future when users might have lots of custom categories, I can't see a particularly compelling case for not always just showing all matching rooms.

**Comment by turt2live** [comment]
fwiw, searching with lots of custom categories is kinda... unhelpful:
![image](https://user-images.githubusercontent.com/1190097/27340960-18df9bb2-5599-11e7-8715-8b6ca34f81b4.png)

**Comment by aperezdc** [comment]
About @turt2live's issue: Probably what I would do is hiding the tiles for titles of the categories which do *not* contain any room matched by the filter string.

**Comment by turt2live** [comment]
This got fixed
