### ISSUE TITLE
If RoomSubList is collapsed or filtered we still don't see the IncomingCallBox for incoming calls(!)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4369]

**Comment by lampholder** [comment]
Does this need a design before a fix can be done?

**Comment by ara4n** [comment]
No. The problem is simply that the IncomingCallBox has ended up in the wrong place in the DOM yet again, which means that if the RoomSubList is collapsed it's invisible.  It also means the CSS is wrong, as it looks like it's embedded within the H2 tag of the list or something.

@dbkr: i assume this is because of a revert fail when demerging my RoomList fixes.

**Comment by ara4n** [comment]
this is at least a major bug, because it means people miss calls entirely.

**Comment by lukebarnard1** [comment]
Ok, this is still true - but the incoming call box is pinned to the RoomSubList header regardless of whether it's collapsed and regardless of whether the LeftPanel itself is collapsed. The position is also slightly off.

**Comment by turt2live** [comment]
It's not pretty, but it seems to be visible?
![image](https://user-images.githubusercontent.com/1190097/47247108-cbb9d280-d3be-11e8-9830-55eb37cba575.png)

**Comment by lampholder** [comment]
If the list is filtered it's definitely not there:

![screen recording 2018-10-23 at 18 02 59 2018-10-23 18_04_23](https://user-images.githubusercontent.com/1922197/47377777-148ac780-d6ee-11e8-914f-3df636c62a4c.gif)

Sorry for the crappy gif - it starts with isobelle mctestphone making a (hidden) call to me, which is only revealed when I unfilter my roomlist

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2333 🎉
