### ISSUE TITLE
Success toaster when bug report submitted

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4372]
### Description

iirc there's a dialog/toaster for when a bug report could not be sent. It would be nice to have a prompt for when one is submitted successfully.

**Comment by NotAFile** [comment]
would this be as simple as adding `err: _("Report sent sucessfully! Thanks")` in [this file](https://github.com/vector-im/riot-web/blob/24a5297fc8b38dce7790f98a3b25a29372e612db/src/components/views/dialogs/BugReportDialog.js#L67)?

**Comment by turt2live** [comment]
I'd hope there'd be something better that `err`, but that seems like the right place.
