### ISSUE TITLE
Cannot reject invite to empty room

### ISSUE THREAD

**Issue by MoritzFago** [vector-im/riot-web#4374]
### Description
Cannot reject invite to empty room.

### Steps to reproduce

- Get invited to a chat or into a room
- Room/chat ceases to exist, because everyone leaves
- You can neither accept nor decline the invitation

Describe how what happens differs from what you expected.
The decline button should remove the invitation regardless of room status. It is unacceptable that there are "ghost" invitations.

Log: sent/not sent?    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS 10.12.5
- **Version**: 0.x.y 
Version of matrix-react-sdk: 0.9.6
Version of riot-web: 0.11.3
Version of olm: 2.2.1

initial report in synapse: matrix-org/synapse/issues/2293

**Comment by lampholder** [comment]
I haven't been able to reproduce this yet.

If I:
- create a room on my federated homeserver
- invite sbdy from matrix.org
- leave and forget the room
then:
- the invitee can just join the room (they're now the only participant)

If I:
- create a room on matrix.org
- invite sbdy from matrix.org
- leave and forget the room
then:
- the invitee can't accept the invite 'Failed: No known servers', but they _can_ reject it

**Comment by turt2live** [comment]
@lampholder did the reject actually go through? https://github.com/vector-im/riot-web/issues/4225 has me a bit worried about it not going through.

**Comment by lampholder** [comment]
If by 'go through' you mean "disappear from the invitee's interface", then yes, it did disappear.

**Comment by Qwertie-** [comment]
I just had the same issue

![screenshot from 2017-08-29 21-33-26](https://user-images.githubusercontent.com/6601505/29819951-4be01dca-8cb2-11e7-82a0-0ce7bc04c67a.png)

![screenshot from 2017-08-29 21-33-40](https://user-images.githubusercontent.com/6601505/29819961-58645912-8cb2-11e7-819f-ecc64df68513.png)

**Comment by rexometer** [comment]
I have the same problem, can't accept nor decline invitation if the room does not exist anymore:

![bildschirmfoto zu 2017-09-08 21-08-57](https://user-images.githubusercontent.com/29459232/30227818-69a4230c-94db-11e7-8913-180b036860a8.png)

**Comment by lampholder** [comment]
Okay, so it looks like it's still happening (event though I can't reproduce it reliably) - P2 minor because it doesn't seem to be happening a lot and can be worked around by refreshing the cache, but it is pretty smelly :(

**Comment by rexometer** [comment]
Hi @lampholder thanks for your answer! What do you mean with "can be worked around by refreshing the cache"? Refreshing the cache in the vector client didn't solve it. Is there another way to delete the invitations? For example in the database? If you need any more information for debugging, I'm happy to provide them.

**Comment by turt2live** [comment]
I also have this in a room where the homeserver lost state, not the client. Harder to reproduce, but just as a point of information.

**Comment by lampholder** [comment]
Ah @rexometer sorry - I was basing that on @Qwertie- 's statement that refreshing the cache fixed their problem - it could well be that there are multiple classes of problem here and that client cache refreshing can't fix all of them :(

**Comment by richvdh** [comment]
If clearing the riot cache fixes it, it's https://github.com/vector-im/riot-web/issues/3743 / https://github.com/matrix-org/synapse/issues/2181

**Comment by justfortherec** [comment]
I have had a similar looking issue with one invite for a long time. I believe the room I am invited too doesn't exist anymore (or is empty).

Flushing cache through the button in settings does not resolve the issue on my side.

#2341 would be a good enough solution for me.

**Comment by lampholder** [comment]
Since it sounds like some of these invites can't be gotten rid of *at all* I think that warrants a higher priority.

**Comment by Half-Shot** [comment]
Can also confirm I am now having this with an invite.
![image](https://user-images.githubusercontent.com/2072976/35510349-a65d894e-04ef-11e8-86af-046a2d84932a.png)

**Comment by t3chguy** [comment]
@Half-Shot clear cache
and it'll magically go away :)

**Comment by Half-Shot** [comment]
It did indeed :3

**Comment by richvdh** [comment]
> If clearing the riot cache fixes it, it's #3743 / matrix-org/synapse#2181

**Comment by richvdh** [comment]
so we think this is a dup of #3743.
