### ISSUE TITLE
SlashCommands could do with a help command to discover commands

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4375]

**Comment by turt2live** [comment]
Possible dupe: #1715

**Comment by lampholder** [comment]
I think https://github.com/matrix-org/matrix-react-sdk/pull/296 on the new composer meets this need?

![image](https://user-images.githubusercontent.com/1922197/27376971-8e9fdfa6-566b-11e7-88f7-aa211274f05b.png)

**Comment by t3chguy** [comment]
@lampholder I disagree, you're missing a few there
`/topic` and `/tint` off the top of my head at least
I believe there are 13 commands so far

**Comment by tanius** [comment]
@t3chguy Both `/topic` and `/tint` and several other additional ones are available in the [riot.im/develop/](https://riot.im/develop/) development version. Just not in [riot.im/app/](https://riot.im/app/) at this time.

**Comment by t3chguy** [comment]
That's because I just added them @tanius :) https://github.com/matrix-org/matrix-react-sdk/pull/1169

**Comment by lampholder** [comment]
@t3chguy - to clarify, if the pop-up listed _all_ of the available commands, do you think this would be sufficient or do you think we need an additional help solution?

**Comment by t3chguy** [comment]
@lampholder since my PR it now does list all commands, whether or not a `/help` command is needed is probably now a no, going to close this unless some other people want the same :)
