### ISSUE TITLE
Bulk removal of devices

### ISSUE THREAD

**Issue by uppps** [vector-im/riot-web#4384]
Each time you login in the web app a new device is added to the list in your profile configuration menu. There is a button that allows to remove a device one by one but after been using riot for some months I have a huge list and removing each device individually its a hard work. I personally can write a bot to automate the task but it is not an option for common users.

**Comment by lukebarnard1** [comment]
Synapse actually already supports a bulk-removal API for devices, Riot just hasn't implemented it yet (https://github.com/matrix-org/synapse/pull/1993)

**Comment by turt2live** [comment]
This happened
