### ISSUE TITLE
fix css for verify and blacklist buttons in memberinfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4387]

**Comment by krombel** [comment]
This is an issue for translated strings where the translation is longer than "verify", "unverify" or "blacklist"

**Comment by grigruss** [comment]
Yes. I think this is easier to solve in translation. Replace the word Verification by a word shorter with the same meaning.

**Comment by grigruss** [comment]
Translation corrected a few days ago.

**Comment by ara4n** [comment]
the CSS is still broken, though - it doesn't line up on Windows, and it certainly shouldn't let the text overflow the buttons.  It's not just a problem in Russian.

**Comment by grigruss** [comment]
Ou.. may be this
overflow-wrap:break-word;

**Comment by lampholder** [comment]
Partially related: https://github.com/vector-im/riot-web/issues/3678

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7712
