### ISSUE TITLE
`Read` report time shows in 24 hour format when 12 hour format is selected

### ISSUE THREAD

**Issue by alallier** [vector-im/riot-web#4393]
### Description

The `read` report time shows in 24 hour format when the 12 hour format is selected in settings.

### Steps to reproduce

Set 12 hour format, exchange message with someone. Hover their profile photo on the read receipt and notice the 24 hour time format.

![riotseenscreenshot](https://user-images.githubusercontent.com/13004518/27433079-07647216-5721-11e7-9679-3c0433a158ab.png)

### Version information

- **Platform**: **Both** in web (in-browser) and desktop?

For the web app:

- **Browser**: Chrome. Version 59.0.3071.109 (Official Build)
- **OS**: Windows 10
- **URL**: https://riot.im/app/*

For the desktop app:

- **OS**: Windows 10
- **Version**: 
```
matrix-react-sdk version: 0.9.6
riot-web version: 0.11.3
olm version: 2.2.1
```

Related to #1728

**Comment by lampholder** [comment]
I seem to be getting 12hr format messages on message read receipts and 24 hour on MELS read receipts?

Also, I don't know if this is captured elsewhere, but the 12 hour format seems to be a bit broken - there's no such thing as 06:00 PM (12 hour format should not have the preceeding 0).

**Comment by turt2live** [comment]
I'll write up a patch for the leading zero, but this particular issue was resolved here: https://github.com/matrix-org/matrix-react-sdk/issues/1140
