### ISSUE TITLE
prevent config.json from being overwritten by apt upgrade

### ISSUE THREAD

**Issue by Metzlmane** [vector-im/riot-web#4394]
I installed the riot-web package via the debian package resource and set all the url's in the config.json under /opt/Riot/resources/webapp/
If i update the package, I have to redo this. The config file gets overwritten. Is it possible to move this one to /etc or something else?

Ubuntu 16.04

**Comment by t3chguy** [comment]
This is more of an internal config file, if you want to change options you should build it yourself, as per instructions in Readme. It is used for per-build data really
Though a saner approach would be an override file, so you have a config file that gets merged with the one that ships and that combination is the actual config.

**Comment by t3chguy** [comment]
for now you could make it immutable https://www.cyberciti.biz/tips/linux-password-trick.html

**Comment by t3chguy** [comment]
This is intentional as it is a build configuration file rather than a user configuration

**Comment by t3chguy** [comment]
Last I pestered someone, namely Dave, he said this was completely intentional and that adding an override file i.e /etc/riot/config.json was not wanted at the time

**Comment by t3chguy** [comment]
Possible via #8983 by specifying the path of your config.json from which override values will be sourced

**Comment by jryans** [comment]
See the [README](https://github.com/vector-im/riot-web#desktop-app-configuration) for more detail on how to use a local config override.
