### ISSUE TITLE
Notification number next to system tray icon isn't cleared after reading all unread messages

### ISSUE THREAD

**Issue by msmeria** [vector-im/riot-web#4396]
### Description

The notification number from the system tray isn't cleared after I've read all messages

### Steps to reproduce

* Wait until you receive messages from 2-3 chats (the notification icon displays 2 or 3 inside a red circle)
* Open Riot and read all unread messages
* Check the system tray icon -> ![screenshot_1](https://user-images.githubusercontent.com/4384658/27438528-3960ec34-576e-11e7-9f3a-3c4852122e39.png)

I was expecting the number of unread messages to be removed from the system tray once I've read them all, but instead I see a 1.
If I restart the application the number disappears.

Log: not sent.    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10
- **Version**: 1703 Build 15063.413

**Comment by t3chguy** [comment]
Which App Version?
#4355 should (have?) fixed it
not sure if it has hit a release yet

**Comment by msmeria** [comment]
matrix-react-sdk version: 0.9.7
riot-web version: 0.11.4
olm version: 2.2.1

**Comment by t3chguy** [comment]
Yeah the PR hasn't hit release yet but will fix this issue, its actually more general than it not being able to reset its simply that there is a N% chance that the update to the icon fails. Closing, if whenever the next update is released this persists please shout at me here

**Comment by msmeria** [comment]
Ok. Thanks for the information.
