### ISSUE TITLE
registration page no longer remembers custom HS options

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4408]
if you set a custom HS on the login page, it then forgets it by the time of the registration page, and keeps forgetting it every time you try to register (if it errors due to things like weak password)

**Comment by lukebarnard1** [comment]
So I think I've traced this back to

https://github.com/matrix-org/matrix-react-sdk/commit/51467506f8320ad415855b7caed714d7a2e120c3#diff-cdf5decb79b402425672c2cb1c8baf37R328
