### ISSUE TITLE
Mobile website text overlap

### ISSUE THREAD

**Issue by seth10** [vector-im/riot-web#4411]
https://about.riot.im/ on mobile appears to have an issue where the language names overlap. Found on iPhone 6 Plus through Safari.

![img_1747](https://user-images.githubusercontent.com/5026621/27513003-d3fe28ea-5923-11e7-94f3-4ac7b44609a5.PNG)

**Comment by lampholder** [comment]
Looks like the media settings in the CSS aren't working/have been done incorrectly.

The flags shouldn't be displaying at all on a small screen - I wonder if the 6 plus isn't registering as a small screen, though...

**Comment by lampholder** [comment]
Today I learned that you can set font size using 'vw' so that it scales with the viewport width and then I fixed this bug :P

**Comment by seth10** [comment]
Looks good! Things seem a bit right-aligned, but the text doesn't overlap so I'd call it a win :)

![img_1802](https://user-images.githubusercontent.com/5026621/27925994-cc29e6a6-6254-11e7-86f8-ed1e957c7a2d.PNG)
