### ISSUE TITLE
Show <pre> border when hovering on the block, not the whole message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4416]
Currently hovering on the message has the border on code blocks visible, even if the code block itself isn't hovered. The border should appear only when the code block itself is hovered, much like the code copy button.

**Comment by turt2live** [comment]
This only applies to the dark theme. Without the border on the light theme, the block blends into the hover state of the tile.

**Comment by ara4n** [comment]
thanks @turt2live!
