### ISSUE TITLE
riot.im/app urls are rewritten to riot.im/develop when on /develop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4417]
If someone sends a message with a link to riot.im/app, the url is rewritten to be riot.im/develop. Eg: riot.im/app/#/user => riot.im/develop/#/user

```
matrix-react-sdk version: <local>
riot-web version: c614bc2356d6-react-f9b37208a3f0-js-cc16cb92813e
olm version: 2.2.1
```

**Comment by lukebarnard1** [comment]
This is intentional I think. Can you give a use case where it wouldn't be desired?

**Comment by turt2live** [comment]
@lukebarnard1 trying to debug an issue someone is having, and silently troubleshooting the wrong version.

At the time of reporting, I was looking at a possible issue involving /app and middle clicked to open the link in a new tab. Didn't realize it was /develop until too late.

**Comment by lampholder** [comment]
I can see how it would be helpful if this _didn't_ happen, though I can also see its being annoyingly tricky to implement :\

**Comment by turt2live** [comment]
I'm not really convinced this is actually needed. Generally people on /develop are going to be power users of sorts and be more aware of what's going on. 

If someone disagrees, please comment and I'll re-open this :)
