### ISSUE TITLE
Clicking riot.im/#/user/whoever?action=chat url leads to bad ux

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4418]
> there's a bug, I give it a username and then check not a robot and then it starts the chat and then pops the window to pick a username again :(    Also the matrix onboarding bot joins and start yammering at me

**Comment by turt2live** [comment]
github bot usage derp

**Comment by lukebarnard1** [comment]
gah this looks like a pretty bad ILAG bug

**Comment by t3chguy** [comment]
Seems to happen even without action=chat
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14992535254824478TNJTN:matrix.org

**Comment by lukebarnard1** [comment]
So I think the intent to start a chat with someone is totally lost in the ILAG flow.

**Comment by lukebarnard1** [comment]
Actually, I can't reproduce this. @turt2live are you still experiencing issues with this?

My experience is `welcomeUserId` user in the background behind a "Start chatting" that shows the requested user.

**Comment by turt2live** [comment]
Yea, at some point this got fixed. It also looks like the concerns in https://github.com/vector-im/riot-web/issues/5598 are fixed @lukebarnard1
