### ISSUE TITLE
Sending plaintext emote quickly leaves RTE emoji autocomplete stuck on

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4419]
### Steps to reproduce

- Send a simple message like `:p` quickly
- Note that the autocomplete pane is stuck

The emoji pane should probably not show up after the message was sent.

Log: not sent    

![image](https://user-images.githubusercontent.com/1190097/27547269-ac1e19cc-5a52-11e7-83e4-016924c30b13.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: c614bc2356d6-react-f9b37208a3f0-js-cc16cb92813e
olm version: 2.2.1
```

**Comment by turt2live** [comment]
Also happens if `:p` is at end of message. Eg: `hello world :p`

**Comment by lukebarnard1** [comment]
ah ok, so there's a race here where the auto completions are fetched after the message has been sent and after the input has been cleared. A clear input should remove all suggestions.

**Comment by turt2live** [comment]
@lukebarnard1 this is still happening

**Comment by lukebarnard1** [comment]
/me cannot repro, you'll have to send a video or something @turt2live

**Comment by lukebarnard1** [comment]
@turt2live have you seen this since https://github.com/matrix-org/matrix-react-sdk/issues/1198 ?

**Comment by turt2live** [comment]
Nope.
