### ISSUE TITLE
e2e icon drifts when permalinked

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4420]
### Description

It also moves on hover.

Before hover (plain permalink):
![image](https://user-images.githubusercontent.com/1190097/27548507-5cca0210-5a56-11e7-986c-fff09dbbcc7b.png)

After hover (still permalinked):
![image](https://user-images.githubusercontent.com/1190097/27548519-67ec5760-5a56-11e7-895b-9bb0933a7337.png)

### Steps to reproduce

- Permalink encrypted message

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: c614bc2356d6-react-f9b37208a3f0-js-cc16cb92813e
olm version: 2.2.1
```

**Comment by lampholder** [comment]
UGLY

**Comment by turt2live** [comment]
![e2e-hover](https://user-images.githubusercontent.com/1190097/52829433-faed0180-3089-11e9-94e8-f788504f4836.gif)

it no longer collides, but it does drift

**Comment by turt2live** [comment]
It doesn't even drift now. Magic!
