### ISSUE TITLE
h2 not greyed out when message in flight

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4421]
### Description

Sample message:
```
# Now
## Does
### It
#### Deal
### With
## Multiline
# Headings?
```

The 2 h2's will not be grey when sending.

### Steps to reproduce

- Send the message above (may require slow connection)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Was able to reproduce using Chrome's degraded connection simulator throttling thing.

**Comment by turt2live** [comment]
This is fixed, likely by https://github.com/vector-im/riot-web/pull/4693
