### ISSUE TITLE
Cannot press up arrow in RTE

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4422]
### Description

It tries to get me to edit my previous message, even if I already wrote something new out. For example ('up' is annotated as markup):

```
Here's the payload I sent:
hello <up arrow>
```

### Steps to reproduce

- Type a message and press the up arrow key

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
So the easiest thing to do here would be to just not jump through history when you have something in the input box.

**Comment by lukebarnard1** [comment]
It would be even better if we can simulate what happens in `bash`:
 - Before history is selected, store the thing currently being composed in separate bit of state
 - Restore this state when returning to history item -1.

**Comment by turt2live** [comment]
This is still annoying for multiline, @lukebarnard1 

Ie:
```
First line
Second line <up arrow>
```

It should go to the first line, then to history.

**Comment by turt2live** [comment]
@lukebarnard1 and now the down arrow is broken again :P

**Comment by lukebarnard1** [comment]
Ah I assume this is because the key presses are `preventDefault()`ed before they get a chance to do the thing.
