### ISSUE TITLE
Riot does not validate m.video event properties

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4423]
### Description

A bad `m.video` payload (sample below) caused Riot to fall over and have a really bad day. All participants of the room could no longer send events to the room or see the room again once clicking away. After clicking away, events could not be sent to other rooms either. The fix was to redact the event using riot-android (unsure of impact on ios). 

The stream of conciousness is available [here in #riot-dev](https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1498509404157rbDuN:t2l.io). 

The payload was this:
```
{
  "body": "HAVE A VIDEO",
  "msgtype": "m.video",
  "format": "org.matrix.custom.html",
  "formatted_body": "test"
}
```

It seems as though the format properties are unrelated, but were included in the test event.

`m.audio`, `m.image`, `m.file`, `m.location`, and of course `m.text`, `m.emote`, and `m.notice` are not affected.

### Steps to reproduce

- Send an `m.room.message` with the above payload
- Watch riot fall over

Log: sent (should be something along the lines of 'bad m.video caused nothing to work')    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: c614bc2356d6-react-447f93ba73a8-js-cc16cb92813e
olm version: 2.2.1
```

**Comment by t3chguy** [comment]
/me had the same on /app/
![image](https://user-images.githubusercontent.com/2403652/27559938-464577b8-5aba-11e7-8b22-473611fe5bb7.png)

**Comment by JigmeDatse** [comment]
I had the same in I think 0.9.8 as well as riot.im/develop  I sent a bug report about `unable to access #test:matrix.org` or something like that from my long outdated version.

**Comment by turt2live** [comment]
@lukebarnard1 this was fixed, correct?

**Comment by lukebarnard1** [comment]
Yep :smile:
