### ISSUE TITLE
Turn 'room directory' button into an 'explore' button

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4429]
[UX Google Doc](https://docs.google.com/document/d/1wv78GqgG59CLjIKPi7GGkdqI6KOeQUBl9Bnf-uA-Kc0)

The 'room directory' button should be replaced with an 'explore' button which will pop up two options - 'group directory' and 'room directory'.

**Comment by lukebarnard1** [comment]
What's with the `type:autocomplete` label?

**Comment by lampholder** [comment]
Fat fingers?

**Comment by turt2live** [comment]
The room directory got a different design in the end
