### ISSUE TITLE
Configure flair on user settings page

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4436]
[UX Google Doc](https://docs.google.com/document/d/1wv78GqgG59CLjIKPi7GGkdqI6KOeQUBl9Bnf-uA-Kc0)

**Comment by lampholder** [comment]
I think there's still some work to be done here deciding the MVP.

We want users to be able to select the groups they want to broadcast membership of through badges/flair.

There are some areas (member info panel) where we can put as much flair as we like without causing UX problems.

There are other areas (timeline, memberlist panel) where we will have to impose limits to avoid awful noise.

The most fully-formed impl of this UX would provide users with a way to:
 - choose the groups they want to advertise membership of through flair
 - allow them to order those groups so that the ones they're most enthusiastic about have the highest priority screen space

However, that feels like overkill for an MVP.

**Comment by pafcu** [comment]
Can be configured now, but not re-ordered yet.

**Comment by turt2live** [comment]
This happened
