### ISSUE TITLE
Display flair in timeline.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4437]
[UX Google Doc](https://docs.google.com/document/d/1wv78GqgG59CLjIKPi7GGkdqI6KOeQUBl9Bnf-uA-Kc0)

**Comment by pafcu** [comment]
@lampholder @dbkr This is done now, right?

**Comment by uhoreg** [comment]
From just the title, this seems to be done (module flair missing in some spots, but those are filed as issues elsewhere), but comparing with the Google Doc, flair is still missing from some spots mentioned (e.g. member list), so I'll leave it for @lampholder / @dbkr to decide if this can be closed, or if it'll be used for tracking flair in the other locations.

**Comment by turt2live** [comment]
The member list and other components have their own tracked issues as well.

**Comment by ara4n** [comment]
the timeline specific one is done for sure
