### ISSUE TITLE
Code blocks without syntax highlighting illegible on dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4444]
### Description

As per https://github.com/matrix-org/matrix-react-sdk/pull/1074#issuecomment-311144976 and https://github.com/matrix-org/matrix-react-sdk/pull/1074#issuecomment-307667422 the block is completely illegible. Toggling the 'guess language' setting does fix this.

![image](https://user-images.githubusercontent.com/1190097/27592907-f458d234-5b12-11e7-98f9-b5de96ba15db.png)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Kegsay** [comment]
This is infuriating for me. When did this break? I'm fairly sure it wasn't always this bad.

**Comment by t3chguy** [comment]
@Kegsay Syntax highlighting used to be set to auto so it made some dash attempt which at least applied some colour, now syntax highlighting is explicit only since matrix-org/matrix-react-sdk#1074

**Comment by turt2live** [comment]
@Kegsay a recent PR (https://github.com/matrix-org/matrix-react-sdk/pull/1074) removed syntax highlighting for code blocks. There's now a setting to turn on the highlight-guessing code

**Comment by t3chguy** [comment]
@turt2live SNIPED

**Comment by Kegsay** [comment]
I'd rather have random words like `this` and `for` in weird colours along with a legible default colour than what we have currently. The old form was annoying but this form is unusable.

**Comment by sbts** [comment]
I have to agree with @Kegsay 
Even worse is the fact that we regularly explicitly declare a type of plain.
That was working until a day or so ago, and now it's broken, even with the config setting flipped.

If plain is broken, we need the riot code to be specifically overriding it to force guessing until plain can be fixed!!!!!!

Probably more important until then, the default setting for the config option should be enabled if dark theme is enabled, and probably even if it's not

**Comment by ara4n** [comment]
i believe e7ba618b fixes this. it was a bug, plain and simple, irrespective of the fact that removing autosyntaxhighlighting exposed it.
