### ISSUE TITLE
UX feedback from kirru

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4448]
Stuff they really missed:

* signin against external service
* message threads (also on mattermost, which we ran away from due to horrific android/ios clients)
* well documented integrations (e.g. https://rocket.chat/docs/administrator-guides/integrations)
* several devops projects are rocketchat aware, i.e. https://wiki.jenkins-ci.org/display/JENKINS/RocketChat+Plugin , or https://docs.ansible.com/ansible/rocketchat_module.html as an example
* well working @mentions for searching for the right person to talk to ...

**Comment by richvdh** [comment]
This isn't really UX feedback...

* signin against external service: https://github.com/vector-im/riot-web/issues/4610
* message threads: https://github.com/vector-im/riot-web/issues/2349
* well documented integrations: seems to mean "incoming webhooks". raised as https://github.com/vector-im/riot-web/issues/4978
* several devops projects are rocketchat aware: seems to mean "add matrix support to other projects", which is a bit nebulous.
* \@mentions now work
