### ISSUE TITLE
Configure default language of Riot web interface in config.json

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4453]
How can I configure default language of Riot web interface, even first auth page, in `config.json` file or other place?
I know that users can change language in settings, but want to force that all users see Riot login page in my pre-defined language.

**Comment by t3chguy** [comment]
I think it loads the language before it loads `config.json` and setting the default language would require a rebuild of riot unfortunately atm

**Comment by t3chguy** [comment]
Adding a Language Selector to the Login/Register page may be an idea though

**Comment by MurzNN** [comment]
Adding Language Selector in https://riot.im Login/Register page is good idea, because on https://riot.im/app/ we also can't change language before login.
After this we can pre-define language via url GET argument, something like `https://riot.im/app/?hl=en_US` or hash `https://riot.im/app/#hl=en_US`.

**Comment by MurzNN** [comment]
Configuration from `config.json` file is reading after app loads for fill default_hs_url and other fields.

Can we add in this place comparison of current language with pre-defined in `config.json`, and if it's defined (not empty) and not equal to current app language - do page reload with new language?

**Comment by t3chguy** [comment]
While the latter could be done it would make the initial load experience twice as long for new users which I am not sure is a good idea

**Comment by MurzNN** [comment]
Yes, this is not so good way, but this will happens only on custom home servers, that force default language.

If they use default config file and don't fill manually "force_default_language" custom config option, all will works like now, with single page load.

**Comment by MurzNN** [comment]
Another way is setup default language in `index.html` file, for example in `<html>` tag, at now here is `en` language:
```
<html lang="en" style="height: 100%;">
```
But this is also not so good way, because `index.html` will be overwritten after updates.

**Comment by turt2live** [comment]
This is now possible with granular settings on develop. Add this to your config:
```
"settingDefaults": {
  "language": "en_US"
}
```

**Comment by t3chguy** [comment]
I deem this solved by Granular Settings 🎉 
(probably should go in an example config somewhere though)

**Comment by MTRNord** [comment]
/me wonders when granular gets loaded. Last time I worked on languages (half year ago or longer) the language did get loaded before anything else at riot to prevent weird loading issues. Does granular get loaded before the language gets loaded? I ask because it might cause Double file downloads if not

**Comment by turt2live** [comment]
The config-level of granular settings are parsed prior to the app bootstrapping. So at worst Riot should download the default language (as defined by the config) then the user's desired language when it recalculates the settings tree.

**Comment by MTRNord** [comment]
Ok:) that's what I hoped for:) not that it downloads one file more than needed:)

**Comment by ThoreKr** [comment]
How does one do this in 2021? 

https://github.com/vector-im/element-web/blob/develop/docs/config.md isn't very extensive on `settingDefaults`.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/settings/Settings.tsx is the authoritative source, if specified you may need to use the `invertedSettingName`

**Comment by ThoreKr** [comment]
Thanks for the direction.

It is still the same parameter, but I screwed up with the "en_EN" (default is apparently "en" now) and consequently it had to be set to "de".
