### ISSUE TITLE
Add current chat title in Riot web page title

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4454]
At now Riot contains only "Riot" text in html `<title>` tag that shows in browser tab name, without any additional info. Will be good to add other useful info in title, for example - current chat title.

For other than chat pages - will be usefult to add page title (for example, Settings, Room directory, etc).

**Comment by MurzNN** [comment]
Also will be useful to see current logged user name (login) in page title, for differ tabs with different logins in browser.

**Comment by t3chguy** [comment]
I think the latter is not the right approach, a customizeable favicon colour would be better, revealing your MXID for people peeking over your shoulder at a backgrounded window/tab seems like a slight privacy issue

**Comment by MurzNN** [comment]
Custom icon colours is not so good solution, because colour can't show names, we must only remember colours.

For not break privacy - we can do this optionally: display username and current chat title only, if user enable this mode in his own settings page. 

At now I setup and try to use about 5 Riot home servers (I can't use one https://riot.im/app/ site because it don't allow multiple login) on different domains and with different logins, and it's too hard to remember which login and organisation in which tab are opened.

Another example is when I open different chatrooms of one server in different browser tabs - I want to see which chatroom is located in each tab.

**Comment by lampholder** [comment]
It's probably best that we restrict this issue to a feature request for 'including the current room name in the page title'.

There are separate design questions raised by how we handle multiple accounts (I can't find an issue for that, though I'm certain it's been discussed).

**Comment by aaronraimist** [comment]
I would like to (optionally) be able to see username in the tab title. Favicon color is a cool idea as well but something needs to happen.
![Screen Shot 2019-06-07 at 1 19 15 PM](https://user-images.githubusercontent.com/5855073/59125106-001ad880-8927-11e9-90ca-bcf01cc9753b.png)
This is not very helpful.

**Comment by wlach** [comment]
I've had good luck using [react helmet](https://github.com/nfl/react-helmet) to solve this problem for other projects I've worked on.
