### ISSUE TITLE
[UX] Ability to set mode to "busy" which suppresses desktop notifications

### ISSUE THREAD

**Issue by cjdelisle** [vector-im/riot-web#4455]
A colleague of mine needs to do meetings with customers and share her screen, the easiest way for her to avoid getting notifications while she is presenting is to close riot entirely. There is an option in the settings to disable desktop notifications but no global "disable notifications" button.

Having additionally a way to signal to others that you're in "do not disturb" or "busy" mode is nice to have but it is seriously important to have a way to disable notifications quickly.

**Comment by turt2live** [comment]
Related/dupe: https://github.com/vector-im/riot-web/issues/3569

**Comment by uhoreg** [comment]
also related to #1672

**Comment by lampholder** [comment]
Yeah; closing this due to being duplicate. @cjdelisle please feel free to +1 #3569
