### ISSUE TITLE
Translate Riot website about.riot.im to most of languages

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4458]
Many users afraid sites with non-native language, so looking at https://riot.im/ in English may be stopper for non-English visitor to continue registration and using our service.

Will be good to translate content (at least - front page), auto-detect browser language and show content for users in his native language (with language switcher combobox).

**Comment by lampholder** [comment]
We should do this, though it might be a little fiddly with the current impl of the marketing site.

**Comment by arthurlutz** [comment]
Seeing the [french government looking into using Riot](https://www.nextinpact.com/news/106467-a-decouverte-riot-outil-libre-derriere-future-messagerie-letat-francais.htm), I thinks translating the about website seems quite important. Are the sources published anywhere ? Any chance of getting the site's content into some crowdsourcing translating platform ?

**Comment by Clonewayx** [comment]
>Are the sources published anywhere?

**Comment by 532910** [comment]
1. it should use Accept-Language HTTP header. (Like debian.org does, for example.)
2. and take translation from translate.riom.im

**Comment by turt2live** [comment]
We've since changed websites entirely - closing as about.riot.im no longer exists.
