### ISSUE TITLE
[UX] [NewComposer] Quoting a message with markdown *disabled* in new composer cursor is in wrong location

### ISSUE THREAD

**Issue by cjdelisle** [vector-im/riot-web#4463]
To reproduce:

1. Enable new/experimental composer
2. Click the little "m" above your message composer to *disable* markdown
3. click the elipses on someone's message in order to quote it
4. Observe the cursor is at the end of the quoted message and not 2 lines below where it should be.  Continuing to type will modify the quote rather than adding text below it.

**Comment by t3chguy** [comment]
This was fixed yesterday by luke (https://github.com/matrix-org/matrix-react-sdk/pull/1161)

**Comment by cjdelisle** [comment]
👍 Thanks
