### ISSUE TITLE
Empty messages shouldn't be sent

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4469]
### Description

Currently possible with /develop RTE. Send a bunch of newlines and/or spaces. 

### Steps to reproduce

- Send a bunch of newlines/spaces
- Message is trimmed to be 0 characters
- Message is still sent (empty)

The empty message should probably just not be sent.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: 515f8de2c559-react-0b46184a21d7-js-cc16cb92813e
olm version: 2.2.1
```

**Comment by lukebarnard1** [comment]
This is the same behaviour as the old composer and I'm not sure what _should_ happen.

**Comment by turt2live** [comment]
As a (biased) user, I'd expect my message to just be consumed. Effectively "send" becomes "clear field" with nothing sent outbound.

**Comment by lampholder** [comment]
fb messenger and slack both refuse to send whitespace (it doesn't clear the input box or anything - just waits until you've typed a single non-whitespace character before allowing you to send anything)

@turt2live I'm less keen on the 'consumption and clear' model - refusing to send trains the user quite nicely; accepting the send request but not rendering it I feel would be more surprising.

I think we should also 'refuse to send' empty messages.

**Comment by lampholder** [comment]
If our UX had speech bubbles, I'd quite like the idea of being able to 'say' an empty speech bubble (to represent speechlessnness), but with the UX as it is an empty message looks weird.

**Comment by lukebarnard1** [comment]
>I'd quite like the idea of being able to 'say' an empty speech bubble

I've never seen that anywhere or from anyone. I've only ever seen "..." or :no_mouth:

**Comment by turt2live** [comment]
Doing nothing is certainly a better option.

**Comment by turt2live** [comment]
Given it's not an accident to go to the devtools, fill out a hand-crafted message, and click the send button I'm going to close this under "working as intended". If someone feels strongly the other way, please open a new issue.
