### ISSUE TITLE
Long messages in RTE do not allow you to use up/down arrows to navigate

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4471]
### Description

![gif](http://g.recordit.co/wmxSYT7xJe.gif)

The message above is a continuous sentence with no line breaks or punctuation. When pressing keys to navigate the text, such as Home or End, the browser picks a reasonable place to put a cursor, however it is then impossible to get to the 'upper line' without mouse intervention.

### Steps to reproduce

- Write a really long message without newlines
- Try to navigate to the 'top line' of your message

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: 515f8de2c559-react-0864ad9c8a80-js-cc16cb92813e
olm version: 2.2.1
```

**Comment by lukebarnard1** [comment]
Oh. Well this could be fixed by allowing the editor to move it's selection position but check if it's actually changed. If it hasn't changed and we're on the top line, then we can select the previous history item. Similarly for going to the previous.
