### ISSUE TITLE
Localpart shown in display name setting field instead of "No display name"

### ISSUE THREAD

**Issue by tanius** [vector-im/riot-web#4477]
### Description

In the user's "Settings" screen, field "Profile → Display name" initially shows the localpart of a user's Matrix ID. However, the actual value is null / unset (see also #798). This can be seen from the fact that the full Matrix ID instead of just the localpart is used in chatlogs (namely in small gray font above a message, to show its author).

### Steps to reproduce

- Create a new user and log in.
- Send a test message and confirm the full Matrix ID is shown above it as author (in small gray font).
- In Riot, go to the new user's "Settings" screen.
- Confirm the localpart is shown as value of "Profile → Display name".
- Try changing the display name to the localpart yourself ("because you want that display name and it's not yet in use in the software").
- Send another test message. Riot still shows the full Matrix ID is shown above it as author (in small gray font).
- Change the display name to anything else than the localpart, confirm with a test message this worked.
- Change the display name to the localpart, confirm with a test message it worked this time.

From this process it's apparent that the Setting screen "thinks" the initial localpart value is indeed the display name, as changing it to the same one will not save anything. That thinking is wrong though, as no display name is set, so the full Matrix ID gets used. Changing the display name, including to something else and then to the localpart, works successfully. Changing it from the initial null / undefined value to the localpart directly does not (but should!).

Log: not sent

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 54.0 (64-bit)
- **OS**: Ubuntu Linux 17.04
- **URL**: https://riot.im/app/

**Comment by turt2live** [comment]
This kinda sounds like a race condition in a way. Between setting your display name to the local part and sending a test message did you see an event about changing your display name in the room?

**Comment by tanius** [comment]
No, between (1) trying to enter and save the localpart display name instead of the shown "phantom" localpart display name, and (2) sending the test message, there is no event about changing the display name in the room. No delay-indicator icon is shown when pressing "Enter" in the display name field either, which is why I think that simply no save action is attempted as it will seem to the form I entered the same value that was already shown in it (even though that is shown in error).

Just found a better way to explain that same issue:

- Start from having a display name that is not empty and not your local part.
- Open the "Settings" screen, delete the "display name" field's content, and save by pressing enter.
- Go back to the room, and you should see an event "@localpart:example.com removed their display name". No problem so far.
- Go back to the setting screen and you'll see that the "display name" field will contain your localpart. Which is wrong, as your display name is empty now.

**Comment by lampholder** [comment]
My experience of this is that it's not possible to remove your display name - if I delete it as described above, any messages I type afterwards are marked with my local part (rather than a full mxid) and as @tanius says opening up settings again I find the display name box pre-populated with my localpart.

I suspect this is all the result of the default-to-local-part changes we made for new users coming on board in the Improved Landing as Guest project.
