### ISSUE TITLE
"someone has changed room avatar" in file panel

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4480]
### Description

Right at the start of the file panel (first known event).
![image](https://user-images.githubusercontent.com/1190097/27776562-ebf87c70-5f68-11e7-8340-ef5db984124f.png)

### Steps to reproduce

- Create new room
- Scroll up in file panel?

May involve uploading enough files to paginate the file panel. Reproduction steps somewhat unclear.

Log: sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Very odd. I'm P2 minoring because it doesn't seem that likely to come up, but that it came up at all is very puzzling.

That said, I wasn't able to reproduce by creating a new room and filling teh room list with enough files to paginate.

**Comment by turt2live** [comment]
I'll try to find a reproducible case for this. The room affected by this is private and can't be shared, but is still very much an issue in that room.

**Comment by uhoreg** [comment]
I see the same issue in one of my (private) rooms as well.

**Comment by turt2live** [comment]
@lampholder I was able to reproduce this very easily without any kind of extra files or people. I guess that stuff was just noise masking the problem.

* Create a room (no need to invite people)
* Set the room avatar
* If you already had the files pane open, click to another pane and then back to refresh

![image](https://user-images.githubusercontent.com/1190097/27887390-c82e874e-619d-11e7-99d2-4dae5174361c.png)

**Comment by uhoreg** [comment]
This is probably because FilePanel only filters for events containing a `url` (https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/structures/FilePanel.js#L69) which room avatar events have.  It probably needs to explicitly filter out `m.room.avatar` events.

**Comment by turt2live** [comment]
@lampholder second plea to remove "cannot reproduce"
