### ISSUE TITLE
"You must join the room to see the files" when looking at account settings page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4481]
### Description

![image](https://user-images.githubusercontent.com/1190097/27776589-33b093a4-5f69-11e7-9ea7-89070091335a.png)

(right side of image - remainder is context)

### Steps to reproduce

- Open file panel
- Open account settings

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Likely introduced when fixing https://github.com/vector-im/riot-web/issues/3889

**Comment by turt2live** [comment]
Fixed
