### ISSUE TITLE
[Feature Request] Custom color schemes!

### ISSUE THREAD

**Issue by berkiyo** [vector-im/riot-web#4482]
**[I also posted this in the android repo]**

Hi vector-im team!

This might be a duplicate request but I am requesting a feature where we can set custom hex values in the UI for background and general accents.

It shouldn't be that hard to implement as there are custom CSS themes for the web version of Riot and all it requires is a change in background colour and the general UI elements (ie: the green accents)

Keep up the great work!

**Comment by t3chguy** [comment]
Try the `/tint #hex [#hex] ` command

**Comment by lampholder** [comment]
I didn't know about /tint - nice :P 

Could we treat this issue as a request to make this feature more discoverable? Presumably we could put a 'custom base colour' option alongside the existing Room Settings Room Colour UI?

**Comment by MTRNord** [comment]
Even thus propablly isn't 100% what is said above I still would like have a theme manager that allows to do full theme changes not just doing color tinting

**Comment by anatomism** [comment]
Ability to change how messages are displayed would be excellent. My users keep 'compliaining' about the list view of messages, and sometimes loose messages because they thought it was one of their own.

They want a more traditional chat app view, i.e. Coloured bubbles with sender and receiver on different sides of the page, like iMessage, Signal, Whatsapp etc.

**Comment by ornithologistnightmare** [comment]
/tint has stopped working since the move to v1, and all colour-related options are gone in the UI as far as I can see. Please add a slider-based thing (per-room as it was originally as well as a global control for a user).

**Comment by ara4n** [comment]
dup of #5844 basically

**Comment by aaronraimist** [comment]
This one had more thumbs

**Comment by ara4n** [comment]
true. if people can apply thumbs to #5844 that'd be appreciated O:-)
