### ISSUE TITLE
ctrl+k for focusing room filter

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4485]
Pressing ctrl+k when using RTE doesn't work

Actually this isn't a regression, the feature got stuck in https://github.com/matrix-org/matrix-react-sdk/pull/895

**Comment by t3chguy** [comment]
half of it seems to be matrix-org/matrix-react-sdk/pull/895 (adding of KEY_K) but the commit which uses KEY_K seems to be missing from that PR

**Comment by lukebarnard1** [comment]
I found the commit: a74bbb424c7c07494d71329e8d4c6ef9fc37a7b9

**Comment by t3chguy** [comment]
@lukebarnard1 cherry-picked it
