### ISSUE TITLE
Topic links not clickable anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4487]
### Description

![image](https://user-images.githubusercontent.com/1190097/27808711-00c3e29a-6007-11e7-9146-f1423f7de6af.png)

Previous to today those links/room aliases would have been clickable.

### Steps to reproduce

- Set topic to have a URL in it

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I bet I broke that by making them Emojione friendly... DAMN

**Comment by lampholder** [comment]
This doesn't seem to be broken any more - can we close?

**Comment by t3chguy** [comment]
Yep, my PR was reverted
