### ISSUE TITLE
RTE no feedback when no tab completions

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4490]

**Comment by lampholder** [comment]
Terminal visual bell style flash?

**Comment by lukebarnard1** [comment]
>Terminal visual bell style flash?

I'd be up for that. I shall experiment. Although, FTR the latest from @ara4n was https://riot.im/develop/#/room/#riot-dev:matrix.org/$14992123954489417sOQHR:matrix.org
