### ISSUE TITLE
/ddg needs layout/CSS adjustment

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4492]
- Even if there is only one result, an ugly scrollbar appears
 - When a result is longer than another result, swapping between the two causes the composer to resize awkwardly

**Comment by AlexDaniel** [comment]
Which means?

**Comment by t3chguy** [comment]
Seems to work for me, sans good layout
![image](https://user-images.githubusercontent.com/2403652/30829223-2be38f0c-a238-11e7-8584-4bc6459cf535.png)

**Comment by lukebarnard1** [comment]
So I think originally it really was broken, but has since started working so I've turned this into a bug to track the layout issues
