### ISSUE TITLE
Decorate links in message composer (first cut just strip them out)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4493]

**Comment by uhoreg** [comment]
related/dup #3990?

**Comment by lukebarnard1** [comment]
Thanks, @uhoreg it's certainly related but not quite a dupe. With any luck we should be to kill both issues with one fix

**Comment by lukebarnard1** [comment]
- [ ] If there are any entities, we want to send HTML so that links etc. are correctly sent as `<a>`s
 - [ ] Pressing space after the link should allow you to input text after it
