### ISSUE TITLE
Order rooms sensibly when auto completing and improve perf

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4496]
- Improve performance by slicing before creating completion pills
 - order by the rooms that the user is most active in or has viewed most recently (use 'view_room').

**Comment by lampholder** [comment]
What makes this slow? Typing `/join #` (followed by typing random possible room name prefixes) seems fairly performant at the moment, but is it scanning through all the rooms on the homeserver, or something else?

**Comment by lukebarnard1** [comment]
It's all done locally and actually I was referring to a glaringly obvious optimisation that could be made (hence "slicing"). This has been done and the ordering seems OK so we should probs just close this.

**Comment by lampholder** [comment]
Sounds good to me :)
