### ISSUE TITLE
if MD is disabled in RTE, it would be nice to show the user 'it looks like you're writing MD - do you want to switch to MD mode?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4499]

**Comment by uhoreg** [comment]
![](https://i.imgflip.com/1s1aos.jpg)

(Sorry, couldn't resist)

**Comment by lampholder** [comment]
I like the idea but we'd need to spend the time to do this well, otherwise it risks being enraging :)

**Comment by uhoreg** [comment]
related to https://github.com/vector-im/riot-web/issues/483.  (Probably similar enough that one of these can be closed.)
