### ISSUE TITLE
Allow trailing slash in custom home server URL

### ISSUE THREAD

**Issue by tanius** [vector-im/riot-web#4505]
### Description

When logging in to riot-web with a custom Matrix home server, one has to fill the "Custom server → Home server URL" field on the login screen. This field if very picky about the correct value, creating UX issues for quite some users, as the URL field does not work like the one in browsers they are used to, which also accepts more "colloquial" forms of URLs.

For example, a trailing slash on the URL (example: `https://matrix.example.com:8448/`) will create an error: "Can't connect to homeserver - please check your connectivity, ensure your homeserver's SSL certificate is trusted, and that a browser extension is not blocking requests."

Even if matrix-synapse needs the URL without the trailing "/" for some technical reason, Riot could improve UX by auto-correcting for this minor variation. Same for other minor variations, like omitting the protocol – it could default  to `https://`, as that avoids introducing a potential security issue.

### Version information

- **Platform**: web
- **Browser**: Firefox 54.0
- **OS**: Ubuntu 17.04
- **URL**: riot.im/app

**Comment by starling-ib** [comment]
Similar to https://github.com/vector-im/riot-android/issues/816 over in riot-android

**Comment by starling-ib** [comment]
I'd suggest this be labelled higher than "minor". This is a showstopper for anyone using home servers and has affected several of my server users.

The application gives no meaningful error message that helps diagnose the issue. I spent hours looking at firewall settings, error logs and trying various nginx and matrix/synapse config changes only to come across https://github.com/vector-im/riot-android/issues/816 by accident, which gave me the clue it was as simple as leaving off the trailing slash from the server address on the login screen.

**Comment by starling-ib** [comment]
A fix is likely to be similar to https://github.com/vector-im/riot-android/commit/96d9d89e48825c8ecb65595f0556d19cde67bc76

**Comment by t3chguy** [comment]
@starling-ib the desktop client is built from this codebase too, and yeah this does seem quite an annoyance

I'll bump to `p2` and look into it

**Comment by t3chguy** [comment]
/me wonders whether this would be better thrown into js-sdk - thoughts?

**Comment by t3chguy** [comment]
Looks like js-sdk
Closing in favour of https://github.com/matrix-org/matrix-js-sdk/issues/334
Track it there, should be fixed next release.
