### ISSUE TITLE
Regression: Hide read receipts option does not clear unread counter for rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4506]
This should be completely unaffected by this option as the option simply hides the RRs. Is something relying on the RR being visible?

**Comment by t3chguy** [comment]
oh I think this should be simple:
`manageReadReceipts={!UserSettingsStore.getSyncedSetting('hideReadReceipts', false)}`

manageReadReceipts is being used instead of something like visibleReadReceipts or whatever

**Comment by turt2live** [comment]
Fixed on /develop, likely due to https://github.com/matrix-org/matrix-react-sdk/pull/1352
