### ISSUE TITLE
RTE should preserve message when switching between rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4507]
This was a feature of the old composer, and the new RTE doesn't do this anymore.

Steps to reproduce:
* Type a message in a room, but don't send it
* Go to another room
* Come back
* Message draft is lost :(

**Comment by lukebarnard1** [comment]
At the moment, the draft is preserved when you move through history. The MessageComposerInput gets unmounted and mounted when we swap rooms so this draft is lost (and wouldn't be set unless the user browsed history and then changed room).

I suspect a good solution to this would involve a store of some flavour. `MessageComposerStore` probably. This will allow us to persist some state outside of the view. Exactly how the store works is as follows:
 - When the MCI updates it's contents whilst not browsing history, save a draft by launching a `composer_content` action, which contains a `room_id` and an `EditorState`.
 - The MCI maintains a mapping of `room_id` to `EditorState` objects for later retrieval.
 - When the MCI is mounted, get state from the MCS to load the last edited content.

For some reason, the old composer did this with `localStorage` but this isn't necessary, we only want to remember the drafts for the current app.
