### ISSUE TITLE
How to configure mail settings in Riot (smtp server for send invitations and url in email)

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4510]
At now when I install Riot-web on my homeserver, seems it send invitations not from server, but via openmarket.com:
```
Received: from arkroyal.mxtelecom.com (arkroyal.mxtelecom.com. [83.166.64.11])
Received: from ldc-prd-matrix-001.openmarket.com ([83.166.68.175]) by arkroyal.mxtelecom.com with esmtp (Exim 4.80.1) (envelope-from <noreply@riot.im>) id 1dSdLK-0003oL-6P for xxxx@gmail.com; Wed, 05 Jul 2017 06:59:18 +0100
```
And instead of my homeserver url, message contains url to https://riot.im/app

How can I configure to send mail via my homeserver smtp server, and change url of Riot app to https://riot.myhomeserver.org/app ?

**Comment by lampholder** [comment]
Hi @MurzNN - invitations are sent from the identity server, not the home server.

It is possible to run your own identity server, but you'll be on a separate identity network to the majority of other Matrix users (so you won't be able to look up other users by email, etc., and they won't be able to find you).
