### ISSUE TITLE
RTE should de-duplicate user completion results

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4511]
![2017-07-05-092233_472x261_scrot](https://user-images.githubusercontent.com/6750344/27855790-b27060d8-6163-11e7-9afc-8767250315da.png)

**Comment by lukebarnard1** [comment]
I'm wondering if I was accidentally on a dodgy local branch for this.

**Comment by lampholder** [comment]
I... definitely saw this at some point along the way in /develop.

**Comment by turt2live** [comment]
Reproducible case, requires 2 users with similar names. In my example, I'm using "TravisR" and "TravisR Guest".

- Have User1 send a message
- Have User2 send a message
- Have User1 send another message
- Tab complete for User

![image](https://user-images.githubusercontent.com/1190097/28035069-78965b5e-6570-11e7-9714-72ee239b6c6a.png)

Looking at another room and coming back will fix the issue. So long as the room stays open you'll see this behaviour.

To get 4, I'd assume the following steps (untested):
- User 1 sends a message
- User 2 sends a message
- User 3 sends a message
- User 4 sends a message
- User 1 sends another message
- User 1 sends another message
- User 1 sends another message
- User 1 sends another message
- Tab complete for User
