### ISSUE TITLE
MELS gets confused with banning

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#4515]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14992656374973093mYUTd:matrix.org

![screen shot 2017-07-05 at 16 42 08](https://user-images.githubusercontent.com/986903/27872534-022af72c-61a1-11e7-9aeb-87c984bacfe9.png)

Vanishare was not banned, some other user was banned

**Comment by lukebarnard1** [comment]
But Vanishare is the user that was banned...

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/27883307-ffcf1d9c-61c7-11e7-90e3-d960ee6f0d89.png)

![image](https://user-images.githubusercontent.com/2403652/27883262-dd3d5e56-61c7-11e7-90b6-3af4ab78f582.png)

/me thinks this was a moment of madness and seems to be a mis-issue. Re-open if I'm wrong

**Comment by lukebarnard1** [comment]
I think it's a slight confusion due to some events not containing the display name of the subject. If a user has left and then gets banned, the ban won't have a display name to work with. So expanded, @dbkr's MELS would have been "Vanishare left.... @shaggoth:matrix.org was banned".
