### ISSUE TITLE
insert current display name by click

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#4519]
When clicking a user's display name ("DN") in chat history, the DN is inserted in the composer to mention them. If the DN changed after the post you want to mention them from, the old DN is inserted regardless. This breaks the mention function, unless a client keeps a list of all former DNs - which riot does not.

### Expected behavior

Instead, I'd expect riot to either
- insert the localpart instead, which can lead to unclarity, because we usually only see the current DN
- get and insert the user's latest DN

### Version information

- **Platform**: web (in-browser) v0.11.4
- **Browser**: Vivaldi 1.11.890.4
- **OS**: Windows 7
- **URL**: https://riot.im/app

**Comment by lampholder** [comment]
This is a tricky one - all potential behaviours could be a little bit jarring, but I think you're right - the intended behaviour is to mention somebody, so perhaps fetching and inserting the user's current DN might be the least obstructive.

**Comment by lukebarnard1** [comment]
The real solution to this is #2980

**Comment by lampholder** [comment]
So clicking the user's name would insert a pill into the composer with their current avatar and display name?

**Comment by lukebarnard1** [comment]
Yep, and there's a plan to insert the user's most recent display name when the pill gets rendered in the timeline

**Comment by HarHarLinks** [comment]
This seems solved in the current version via #2980.
