### ISSUE TITLE
IOS / Android: No notifications on (locked) screen

### ISSUE THREAD

**Issue by linuxmail** [vector-im/riot-web#4520]
Hello,

we want to switch from Skype to Riot/Matrix, but one bigger problems are the notifications. We get no hint, that there are new messages on the (locked) screen. Nor on IOS 10 nor on Android 6. I have to open Riot, to get new messages with notifications.

Version is from IOS: 0.3.13 master #63 (Appstore)
Version is from Android: 0.6.13 (Google Play) 

With the Android version I also don't get any messages on my Pepple Watch.

Any suggestions ?

Thanks :-)

**Comment by richvdh** [comment]
please could you file this at https://github.com/vector-im/riot-android / https://github.com/vector-im/riot-ios

**Comment by richvdh** [comment]
though actually that sounds like a problem with your configuration rather than the app. Suggest discussing it online rather than raising bugs.
