### ISSUE TITLE
Anecdotal evidence of DMs losing their DM status.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4521]
A recurrance of https://github.com/vector-im/riot-web/issues/3331, mentioned in https://github.com/vector-im/riot-web/issues/4385.

I think I've heard a few people still complaining about DMs losing their DM status - this issue exists to track any further evidence (and becuase I couldn't find a currently-open issue to represent it).

**Comment by lukebarnard1** [comment]
#3331 has been closed, can I close this?

**Comment by turt2live** [comment]
Presumed fixed and more stable than before.
