### ISSUE TITLE
indicate when there are unverified devices in the room

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4532]
I think it would be helpful to change the green lock icon next to the message input box if there are unverified devices that the user has opted to send messages to anyways, as a reminder that the room may not be as secure as they may want it to be.  Maybe change the icon to a lock with a question mark, or a lock with a warning sign.  And of course the tooltip should be updated accordingly ("Encrypted room with unverified devices").

**Comment by turt2live** [comment]
Related/dupe: https://github.com/vector-im/riot-web/issues/4522

**Comment by uhoreg** [comment]
I don't see this particular feature mentioned in 4522.  It's definitely related, but probably different enough that it should be tracked separately.

**Comment by turt2live** [comment]
> The second the untrusted devices appear, the warning appears in the StatusBar telling you messages will be queued until you verify them.

It's not exactly the same, but a very similar resolution.

**Comment by uhoreg** [comment]
I think he's actually talking about unknown devices, rather than unverified devices.  They could be designed into the same interface, or they could be implemented separately, but I don't want to pile unrelated stuff into his issue while it sounds like they have some sort of vision already for how 4522 might work.

In any event, I'll let someone else decide if this should be wrapped in with 4522 or if it's separate.

**Comment by turt2live** [comment]
whoops, sorry. I read unverified as uknown - my apologies ._.

**Comment by turt2live** [comment]
There's now an icon at the top of the room
