### ISSUE TITLE
Cannot tab-complete users sometimes

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4533]
Sometimes, typing `ric *tab*` will give you results and sometimes the input box will just flash red. Presumably this affects other completions. This is flaky and difficult to repro.

**Comment by turt2live** [comment]
I don't know how, but I've run into this fairly often. No obvious reproduction steps and no obvious errors in the console. Possibly adding more logging would help find it?

**Comment by lukebarnard1** [comment]
>Possibly adding more logging would help find it?

Maybe, although I think I might have inadvertently fixed it. Have you seen it happen with a recent `/develop` build?

**Comment by turt2live** [comment]
@lukebarnard1 several reports of this in #riot (https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1499707108843DnhBm:t2l.io see messages below permalink)

I don't personally recall if I've seen this in the last 3 or so days, but will be testing.

**Comment by turt2live** [comment]
@lukebarnard1 this happens when users are inactive for extended periods of time, it seems.

The timeout seems to be about 2 minutes (possibly as short as 1 minute). 

* User sends message
* Tab complete for user
* Wait 2 minutes
* Tab complete for user again

**Comment by lukebarnard1** [comment]
This appears fixed to me!
