### ISSUE TITLE
CORS error popup when failing to join room

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4541]
According to erdnaxeli in the discussion starting at https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1499518666138684TsxJg:cervoi.se, failing to join a room caused a popup to display a CORS error.  @ara4n had previously fixed all the error popups to be more friendly, but either he missed one, or a new one crept in.

**Comment by erdnaxeli** [comment]
![2017-07-08-152703_1254x1041_scrot](https://user-images.githubusercontent.com/479441/27985773-4581784a-63f2-11e7-8523-b89dede70a28.png)

**Comment by MTRNord** [comment]
Got the same error right now on /develop

**Comment by MTRNord** [comment]
My error is HTTP error 504

**Comment by lampholder** [comment]
Dunno what the underlying error is, but we should never be vomiting up that kind of error message direct to the user :\

**Comment by uhoreg** [comment]
Apparently, we also get the CORS error popup when it fails to change settings, as per https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1505422396418vKhhA:matrix.freelock.com

![](https://matrix.org/_matrix/media/v1/download/matrix.freelock.com/lshJoGeXimLnbxjDAMotKABp)

**Comment by grahamperrin** [comment]
FWIW I haven't seen any token, within an error dialogue, recently.

**Comment by aaronraimist** [comment]
Fixed by 
https://github.com/matrix-org/matrix-react-sdk/pull/2306

See 
https://github.com/vector-im/riot-web/issues/7526#issuecomment-444643555

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7785
