### ISSUE TITLE
Username/avatar is not shown for messages following a redacted message, even when it's hidden

### ISSUE THREAD

**Issue by Magnap** [vector-im/riot-web#4543]
### Description

When hiding redacted messages, Riot does not subsequently show the username/avatar for the same user until it would've been shown again if their messages hadn't been redacted.

### Steps to reproduce

- Configure Riot Web to "hide removed messages"
- Send a message after another user
- Redact it
- Send another message

It now looks like your second message was sent by the other user.

![2017-07-09-121638_865x426_scrot](https://user-images.githubusercontent.com/1183556/27993053-eca26ef4-64a1-11e7-9654-30beb9b600c4.png)

Log: not sent as this is AFAICT a purely visual bug.

### Version information

- **Platform**: In-browser, but via nativefier.

For the web app:

- **Browser**: Chromium, Version 59.0.3071.115 (Developer Build) (64-bit)
- **OS**: Arch Linux
- **URL**: riot.im/app/

**Comment by lukebarnard1** [comment]
I think this is fixed as part of the fix for #916

**Comment by lampholder** [comment]
Shall we leave this open until we've verified the fix for #916 also fixes this problem?

**Comment by t3chguy** [comment]
It does fix it, just tested
