### ISSUE TITLE
shark emoji don't get autoenlarged

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4548]
If you send a message (at least with new RTE) of just 🦈, it doesn't get the Big Emoji treatment, for reasons unknown

**Comment by ara4n** [comment]
Oh, presumably the problem is that emoji-one doesn't know the emoji so doesn't know to autozoom it or even substitute it for SVG

**Comment by t3chguy** [comment]
We're running emojione 2.2.7 yet 2.2.4 appears to have shark - https://emojipedia.org/emojione/2.2.4/shark/

**Comment by t3chguy** [comment]
fixed by ref'd PR
