### ISSUE TITLE
Some analytics are i18nised

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4549]
So we get reports of the `Warnung!` modal being opened 100s of times, when really these events should not have any i18n information in them at all. Here's a list of things that are keyed off-of the i18n data:
 - [ ] Modals: when calling `createDialog`, pass an English ID that can be used to trace the call to it

**Comment by t3chguy** [comment]
/me could do with piwik creds to spot these fun things.

**Comment by t3chguy** [comment]
well fixing this (without moving the `_t` call to later, for which I think I'd be skinned alive) means passing both the English and the i18n'd string to `createDialog` :L

Any better solns?

**Comment by turt2live** [comment]
Just a theory, and probably not a great idea, but you could do a reverse lookup for the purposes of piwik. It would mean the analytics would need to know about the dialogs and user's language setting so it can find the English version.

**Comment by t3chguy** [comment]
@turt2live very much possible but I doubt that the i18n lib allows for that, /me looks at @MTRNord

**Comment by MTRNord** [comment]
@t3chguy well the _t() is defined in languageHandler.js so I guess you could implement it in someway. But I am not sure if I understood where the problem woud be

**Comment by lukebarnard1** [comment]
I would prefer not to assume that the `title` of the dialog is the output of a call to `_t` (despite it probably being so). I'd vote for some kind of `analyticsId` that we can pass into `createDialog` that ends up being the English title so that we can easily grep for the dialog when we see it doing strange things in the analytics.

**Comment by lampholder** [comment]
@lukebarnard1 can we IRL to talk about the consequences this?

**Comment by lukebarnard1** [comment]
(FTR we did IRL) and the consequences are that the analytics in piwik are separated by language inadvertently.
