### ISSUE TITLE
Less errors when submitting invalid username as guest

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4551]
### Description

![image](https://user-images.githubusercontent.com/1190097/28030882-bad13704-6562-11e7-9352-2973d4653c53.png)

This was on trying to join #test:matrix.org

More annoyingly, the second error doesn't go away after:
![image](https://user-images.githubusercontent.com/1190097/28030951-e9f3a706-6562-11e7-8f30-ef4107ef74be.png)

### Steps to reproduce

- Replicate screenshot

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: c1b8879b6bed-react-4f95d4ccaf40-js-3294f4858a65
olm version: 2.2.1
```

**Comment by lampholder** [comment]
Ah, I see - this happens when you type-in-and-submit a borked mxid. 

Just typing rewards you with the top error - pressing enter/clicking submit gets you the full set.

**Comment by lukebarnard1** [comment]
It would be nice if we only ever showed one error but we _are_ hitting two APIs here. So we do need to show both, but I'm not certain they need to be shown separately.

**Comment by lukebarnard1** [comment]
@turt2live/ @lampholder I can't reproduce this anymore, would be nice to know if it's gone away.

**Comment by t3chguy** [comment]
my PR should catch some of those: https://github.com/matrix-org/matrix-react-sdk/pull/1259

**Comment by turt2live** [comment]
Appears fixed. Closing. Apologies for the delay.
