### ISSUE TITLE
Home screen formatting is off in Firefox

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#4552]
### Description

When viewing the home screen in Riot, I'm unable to scroll the page. Further, the navigation pane on the left side seems to extend off the bottom of the window.

### Steps to reproduce

- Launch Riot in Firefox (and preferably log into an account with lots of rooms)

Log: not sent (received 'Failed to send report: No connected database' when I tried)

![screen shot 2017-07-10 at 4 37 55 pm](https://user-images.githubusercontent.com/1923178/28038892-68b87046-658e-11e7-9652-a8419a2f6a59.png)

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly 56.0a1 (2017-07-07) (64-bit)
- **OS**: macOS
- **URL**: riot.im/app

**Comment by turt2live** [comment]
Do you have any custom tags set up? If so, that would be why the navigation flies off the page. Riot decides that if the area to click a room is too small and stops trying to fit the headers on the page.

**Comment by lampholder** [comment]
I couldn't reproduce this on FF 56.0a1 (2017-07-09) (64-bit) on Linux

**Comment by jfrederickson** [comment]
No custom tags - I have the standard set of Favourites, People, Rooms, Low Priority, and Historical.

**Comment by lampholder** [comment]
/me checks macOS... OH DEAR.

Even if there aren't enough rooms in the roomlist to fill the left hand panel, the bottom left navigation items are still missing D:

**Comment by ara4n** [comment]
fixed years ago
