### ISSUE TITLE
Better defaults for emoji (plaintext) auto completion

### ISSUE THREAD

**Issue by kethinov** [vector-im/riot-web#4554]
Offshoot of this discussion: https://github.com/vector-im/riot-web/issues/2567#issuecomment-312935697

This would be a good guide to follow: https://aprescott.com/posts/hangouts-emoji

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/2648

**Comment by lukebarnard1** [comment]
"Better" is quite subjective and I'm still not clear on what you mean. We currently use the meta data from the emojione data set:
`:') :'-) :D :-D =D ':) ':-) '=) ':D ':-D '=D >:) >;) >:-) >=) O:-) 0:-3 0:3 0:-) 0:) 0;^) O:) O;-) O=) 0;-) O:-3 O:3 ;) ;-) *-) *) ;-] ;] ;D ;^) :) :-) =] =) :] :* :-* =* :^* >:P X-P x-p :P :-P =P :-p :p =p :-Þ :Þ :þ :-þ :-b :b d: B-) B) 8) 8-) B-D 8-D :-X :X :-# :# =X =x :x :-x =# -_- -__- -___- :$ =$ >:[ :-( :( :-[ :[ =( >:( >:-( :@ >:\ >:/ :-/ :-. :/ :\ =/ =\ :L =L >.< :-O :O :-o :o O_O >:O D: :'( :'-( ;( ;-( ':( ':-( '=( #-) #) %-) %) X) X-) *\0/* \0/ *\O/* \O/ <3 </3
`

**Comment by lukebarnard1** [comment]
@kethinov By "better", do you mean "include the Hangouts emoji shortcuts too"?

Emojione doesn't currently have a mechanism for custom shortcuts but we can add them at runtime via user settings.

**Comment by lukebarnard1** [comment]
I think we should also consider whether using the above replacements is going to get confusing WRT the auto-completions, which show a different ordering of emoji.

e.g. ":L" produces
![2017-07-13-175500_662x369_scrot](https://user-images.githubusercontent.com/6750344/28177916-682e39ae-67f4-11e7-888e-e79c2c7d497a.png)

but will auto replace to the `emojione` interpretation of ":L", which is :confused:

**Comment by kethinov** [comment]
I think what Mattermost does would be a good model.

On Mattermost you have both ASCII-style shortcuts, e.g. `:)` or `:p` auto replacing into 😀 and 😛 as well as an auto completion interface like `:stuck_out_tongue:` with a picker similar to Riot's.

**Comment by lukebarnard1** [comment]
>On Mattermost you have both ASCII-style shortcuts, e.g. :) or :p auto replacing into :grinning: and :stuck_out_tongue: as well as an auto completion interface like :stuck_out_tongue: with a picker similar to Riot's.

this is exactly what Riot does (albeit you have to tick a box in user settings to enabled auto replacement). But I thought you were more concerned about the particular plaintexts chosen?

**Comment by kethinov** [comment]
On a second look, yeah, there may be nothing to do here. I'm basing this mostly on your comment about replacement string priorities [here](https://github.com/vector-im/riot-web/issues/2567#issuecomment-312838625). I forgot the checkbox was already implemented because it isn't in 0.11.4, so I haven't yet played with the feature.

**Comment by lukebarnard1** [comment]
@kethinov OK, fair enough and thanks for clarifying. Let's keep this issue open as I'm sure others will have thoughts on this.

**Comment by kethinov** [comment]
Just tested this with the latest update. Checkbox "Automatically replace plain text Emoji" is checked and it doesn't appear to do any auto replacing. (Riot 0.12.1)

**Comment by lukebarnard1** [comment]
@kethinov you'll have to be a bit more specific. What were the steps to reproduce, what did you expect etc.

**Comment by kethinov** [comment]
Riot 0.12.2, ASCII-style shortcuts, e.g. `:)` or `:p` auto replacing into 😀 and 😛 do not work with the "Automatically replace plain text Emoji" checkbox checked.

The auto complete method using `:` to bring up the emoji menu does work.

**Comment by t3chguy** [comment]
@kethinov the catch is you have to hit space after `:P` to complete it

**Comment by t3chguy** [comment]
or even with the option off you can do `:P` `[TAB]`

**Comment by kethinov** [comment]
Ah there we go. Woohoo! 🎉

**Comment by t3chguy** [comment]
@kethinov there is a related issue you may be interested in: https://github.com/vector-im/riot-web/issues/4872

**Comment by xoxys** [comment]
Why this not work on android?

**Comment by jryans** [comment]
> Why this not work on android?

This is the repo for Riot Web. You can file Riot Android issues in [that repo](https://github.com/vector-im/riot-android/).
