### ISSUE TITLE
Piwik cookies seem to disappear on refreshing riot.im/app

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4555]
To reproduce:
1. Load riot.im/app
1. Open a cookie inspector to look at your piwik cookies
1. Refresh
1. See how there doesn't appear to be any cookies any more :S

**Comment by lampholder** [comment]
Hey @t3chguy - any thoughts on what might be causing this/how to fix? I think it might be playing merry hell with some piwik stats :\

**Comment by t3chguy** [comment]
only thing that should kill piwik cookies is an opt-out iirc, I will take a look

**Comment by t3chguy** [comment]
@lampholder and I PM'd about this and could not reproduce, written off to cookie inspector glitch until it recurs
