### ISSUE TITLE
Keep in tray after closing Riot window in Electron Windows app

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4562]
At now when I press "Close" button on window in Riot Electron Windows app - it closes totally. But when I do same action on Linux (Ubuntu with KDE) - Riot hides to tray.
How can I configure Riot Electron Windows app for minimize to tray at close window event, instead of exiting?

**Comment by t3chguy** [comment]
I cannot reproduce this, the behaviour of Minimize-on-close is hardcoded into the app and works on my Windows 10 machine
Build 15063.413

**Comment by MurzNN** [comment]
Strange, I install `Riot%20Setup%200.11.4.exe` on 3 computers with Windows 7 and on all of them - when I press "Close" on Riot window - it closes totally. I will try to check this on Windows 10.

**Comment by MurzNN** [comment]
Ow, sorry, it stays in memory after close, but tray app not shown for me, because custom tray app installed on my computers when I must manually enable each new app. Sorry for noise.
