### ISSUE TITLE
Run multiple instances of Riot-web electron app with different config folder

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4566]
I need to be online in several Matrix accounts simultaneously. Can I run multiple instances of Riot-web electron app with different config folders? At now on Linux Riot-web store config in `~/.config/Riot` folder.

Maybe I can set another path to Riot config via command line argument or shell variable? And will be good to have the way to change app icon too.

**Comment by t3chguy** [comment]
Use the `--profile=x` switch when starting riot, where x is a unique value for each extra store you want

**Comment by MurzNN** [comment]
Thanks, it works! Maybe there also exist way to replace app icon (and tray icon) for profiles too?

**Comment by MurzNN** [comment]
I find in sources of `resources/app/src/tray.js` that config file `resources/webapp/config.json` can have `icon_path` value with custom icon, but setting it to custom image not help - app icon stay original.
Also changing `brand` only change "Show/hide" menuitem in tray icon, but general popup is stay "Riot".

**Comment by lampholder** [comment]
Since the ability to run multiple instances already exists, I'm labelling this a p4 cosmetic feature request (to enable each of those instances to appear visually distinct).

OOI what do people think about this vs the app's having the ability to handle multiple accounts within a single instance? Obviously that's a fair amount more work...

**Comment by t3chguy** [comment]
The Logo and Text are actually based on the Favicon and document.title of the underlying webapp, the config.json values are only for during start-up
You should be able to edit the index.html and replace the favicon

**Comment by ansiwen** [comment]
@lampholder: I think the possibility to have several accounts within the app is still essential. If you run it in the browser or especially as the iOS app, there is no ways to run multiple instances. (Yes, in the browser you can create a wildcard webserver where *.chat.example.com are all served with a riot instance and have different configs that way...) It would also look nicer to have just one icon for the app. Imagin you would need several email client instances for different mail accounts?

**Comment by MurzNN** [comment]
If Riot Electron app is only web page in browser, can Election app have multiple tabs with different webpages, and switcher between them? Example of this implementation we can see in multiple accounts apps like http://rambox.pro/

**Comment by t3chguy** [comment]
@MurzNN not without rewriting too much of the app

**Comment by t3chguy** [comment]
Since config is more of a build config rather than user config, and it **is** now possible to have multiple profiles of riot-web electron open I think that the next step is proper multiple account support, so closing this in favour of that: https://github.com/vector-im/riot-web/issues/2320

**Comment by MurzNN** [comment]
Yes, multiple accounts is tracked at https://github.com/vector-im/riot-web/issues/2320
Also I create separate issue about changing app icon and names https://github.com/vector-im/riot-web/issues/4745
