### ISSUE TITLE
Enabling markdown mode adds backslashes in code spans/blocks

### ISSUE THREAD

**Issue by heftig** [vector-im/riot-web#4574]
Either:
- In Markdown mode, type <code>\`foo_bar_baz\`</code>, creating a code span, or
- In non-Markdown mode, enable code formatting and type `foo_bar_baz`, creating a code block

Then rapidly toggle Markdown mode. Whenever it is switched on, more backslashes are added to the underscores in the code block/span.

Riot Develop, Firefox Nightly, Arch Linux

**Comment by lampholder** [comment]
I seriously wonder whether toggling markdown should be supported when there's text in the textarea. It's a lot of fiddly for limited return - maybe we could disable it (though we'd have to UX design that so it didn't just seem broken) and come back to the problem again in the future?

**Comment by lukebarnard1** [comment]
(This is part of https://github.com/vector-im/riot-web/issues/1944)

**Comment by aaronraimist** [comment]
There is no markdown mode toggle anymore
