### ISSUE TITLE
Unable to send a message sometimes

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4580]
Repro steps:
 - Focus empty composer
 - <kbd>ctrl</kbd> + <kbd>j</kbd>
 - Hit <kbd>Enter</kbd> any number of times
 - Observe the message not being sent.

Related: https://github.com/vector-im/riot-web/issues/4535

**Comment by lampholder** [comment]
It seems to go into the same 'code editing' mode as it does when it's in RTE mode. So I think:
- there's a bug where  <kbd>ctrl</kbd> + <kbd>j</kbd> does _anything_ when you're in markdown mode
- there's a bug where the UX whilst you're in code editing mode should be improved to make it:
    - obvious that carriage returns are not going to send the message (they're part of the code block)
    - obvious how you return to 'normal mode' to actually send the message

**Comment by lukebarnard1** [comment]
I think the second bullet point there is essentially fixing https://github.com/vector-im/riot-web/issues/4535. I've certainly never heard of that particular key combination but apparently some browsers use it for opening dev tools and given we have special treatment for ctrl+i, I'd happily get rid of it.

**Comment by lukebarnard1** [comment]
- [ ] Better visual indication of code blocks in the editor
- [ ] Backspace at the start of a block toggles block formatting
- [ ] Enter in an empty block also toggles block formatting

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
