### ISSUE TITLE
Pressing `ctrl+j` will not insert ``` in  markdown mode

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4582]

**Comment by lampholder** [comment]
So we could solve the first bullet in https://github.com/vector-im/riot-web/issues/4580 by making ctrl+j insert six backticks with the cursor in between backticks 3 and 4 (just as pressing ctrl+b inserts 4 asterisks with the cursor between 2 and 3).

**Comment by lukebarnard1** [comment]
So actually, the behaviour of ctrl+j varies in non-MD mode depending on the current selection. If you haven't selected anything, a new code block is inserted. If you have selected something, only the selection is given code formatting.

Currently we make no distinction when applying markdown formatting, but we could do in this instance.
