### ISSUE TITLE
Unable to decrypt: Encryption not enabled

### ISSUE THREAD

**Issue by commagray** [vector-im/riot-web#4585]
Subj, I guess. I got it in the chats and `olm version: <not-enabled>` in the settings, so E2E completely don't work. Problem on OpenBSD (-current and -stable) with Firefox ESR (52.2.1).

**Comment by lampholder** [comment]
@richvdh what causes `olm version: <not-enabled>`?

**Comment by richvdh** [comment]
A build of riot-web without olm, generally. To the OP: please could you re-file this issue (https://github.com/vector-im/riot-web/issues/new) and fill in the template.
