### ISSUE TITLE
Suggestion: Allow manual reset of unread message display (number on the icon). 

### ISSUE THREAD

**Issue by gibbousmoon100** [vector-im/riot-web#4586]
On Riot for Windows (using win7 pro), I often see a "1" on both my notification icon and the taskbar icon which does not disappear upon viewing the unread message.

The current workaround for me is to exit Riot and start it up again.

Until this bug is fixed, an option to "mark all messages as read" would be a much nicer workaround.

(Posting in riot-web, because I don't see a dedicated forum for riot-windows.)

**Comment by lampholder** [comment]
Thanks @gibbousmoon100 - riot-web is the right place to file things for the desktop builds :)

I've P1 majored this because inaccurate unread message counters can be _extremely_ irritating. Do we know if this problem exists on riot-web too?

**Comment by t3chguy** [comment]
I thought I fixed this but am sure I got it again this morning, I'll build a new dev build and try to debug it next it happens

**Comment by ArchangeGabriel** [comment]
Mark all messages as read would be a workaround for #4588 too.

**Comment by t3chguy** [comment]
@ArchangeGabriel I don't think so actually, one is based on Read Marker the other on Read Receipt :/

**Comment by ArchangeGabriel** [comment]
Well obviously such a feature should reset both.
