### ISSUE TITLE
"Jump to first unread message." jumps far back in history

### ISSUE THREAD

**Issue by felipeborges** [vector-im/riot-web#4588]
### Description

I am using the IRC bridge because I don't want to miss any conversation in the channels I follow. For this reason, I often "Jump to first unread message" to catch up from where I left.

I suspect that Riot is not grabbing the focus properly, failing to mark messages as "read". I didn't investigate/debug it any further.

### Steps to reproduce

- Stay a couple days away from Riot
- Click "**Jump to first unread message**" in a busy IRC channel

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome
- **OS**: Fedora
- **URL**: riot.im/app

**Comment by ArchangeGabriel** [comment]
Same issue using the desktop version. I had to use `Jump to first unread message` and `Scroll to bottom of page` several times in a row to get it to track the current state again.

**Comment by lampholder** [comment]
Hi @felipeborges - just to clarify - are you finding that 'jump to first unread message' is jumping _too far_ back in history?

@ArchangeGabriel - are you having the same problem, would your problem be described as "having clicked 'jump to first unread message', you then find that your timeline no longer tracks the latest new messages"?

**Comment by ArchangeGabriel** [comment]
Trying to describe more accurately:

- at some point, they have been more than 600 messages in half an hour on the chan;
- following this, when opening Riot, it was saying I had several hundreds of unread messages in the room. Clicking on `Jump to first unread message` was bringing me back to when the “storm” started, at which point I just jumped back to the current time and scrolled back manually until retrieving the actual first unread message, the feature being useless at this stage;
- every time I closed Riot or let some messages accumulate, using the button brought me back one screen lower in the “storm” than the previous attempt.

I finally used the button as much times as required for the view to reach the bottom of the chan.

**Comment by felipeborges** [comment]
@lampholder yes, today (monday) I was catching up with the convos from the weekend, but the "Jump to first unread message" link took me to almost a month back in the past (messages that I already read a couple of times).

**Comment by lukebarnard1** [comment]
It's likely that this is related to #4134 and although you've already read the messages the first time, you might have missed one or two that preceded them or you might have scrolled down too quickly for them to have been marked as read.

**Comment by uhoreg** [comment]
I'm running into this issue quite a bit.  I don't think it's related to scrolling too quickly because I've scrolled very slowly, and the "Jump to..." bar doesn't show up while I'm scrolling.  When it happens, the "Jump to..." bar will bring me to the same message every time it shows up.  It's almost like the client knows that I've read those messages, but the server doesn't get updated.

**Comment by lukebarnard1** [comment]
@uhoreg when you jump back to the same message, can you _see_ the read marker (the green line)? I've encountered the similar #4694 and it sounds vaguely like this.

**Comment by t3chguy** [comment]
this original issue is on /app
which predates my hide join/parts

**Comment by uhoreg** [comment]
@lukebarnard1 I'll check next time it happens.  The RM seems to be pretty flaky recently, so there may be a bunch of different issues here, and I don't remember all the different symptoms.  I've also seen a case where the "Jump to..." link doesn't go back far enough, and I have to scroll back a bunch to get to the first unread message.

**Comment by uhoreg** [comment]
Just happened in #riot.  This is where it brought me back to:
![image](https://user-images.githubusercontent.com/1012976/29185676-f2e4cb0a-7dd7-11e7-8c4c-381866160633.png)
No green (or orange, in this case) line.  Will send rage shake.

**Comment by lukebarnard1** [comment]
@uhoreg awesome, thanks very much, at a guess I'd say it's stuck on 0xHyde's join

**Comment by lukebarnard1** [comment]
This looks like it may have been fixed, if anyone has evidence to the contrary, feel free to (suggest) reopen.
