### ISSUE TITLE
Tom's emoji displayname doesn't show up when autocompleting in RTE

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4589]
<img width="707" alt="screen shot 2017-07-17 at 13 24 18" src="https://user-images.githubusercontent.com/1294269/28267736-4f20bf0c-6af3-11e7-9980-797bfa86bc9f.png">

**Comment by ara4n** [comment]
note blankness in composer

**Comment by lampholder** [comment]
Almost as if I were reproducing that very bug :P
