### ISSUE TITLE
Autocomplete in RTE only searches the 4 most recent usernames, rather than searching all usernames (but truncating the list of options shown)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4590]
Rob<tab> ain't showing me `Rob (@robswain:matrix.org)` as an autocomplete target in Matrix HQ, even though he's in the room.  I only see 4 options in fact.

<img width="1018" alt="screen shot 2017-07-17 at 13 37 24" src="https://user-images.githubusercontent.com/1294269/28268181-2de034ec-6af5-11e7-9a66-e531ad7eeb0d.png">

**Comment by superdump** [comment]
😢

**Comment by ara4n** [comment]
just to be clear: hitting Tab iterates over only these 4 options. It's not a cosmetic bug, I simply have no way of autocompleting him (i had to manually check the memberlist to see whether he was even in the room!)
