### ISSUE TITLE
French translation of 'Send a message (encrypted)' is wrong.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4596]
For unencrypted channels, it reads 'Envoyer un message (non-chiffre)' (as it should)
For encrypted channels, it reads 'Envoyer un message non chiffré' (which is wrong)

I'd suggest replacing with 'Envoyer un message chiffré' unless an authentic Frenchperson can suggest something better?

**Comment by lukebarnard1** [comment]
This has been fixed in weblate but that change hasn't been reflected in react-sdk

**Comment by lukebarnard1** [comment]
This has been fixed, and shall be merged when we next merge translations.
