### ISSUE TITLE
Add new email address UX trips people up.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4598]
![image](https://user-images.githubusercontent.com/1922197/28271119-a3eaa000-6aff-11e7-8387-226cca84ab4d.png)

I've seen rageshakes, bugs and I've encountered myself problems with this UI.

People click on the + first (rather than clicking on the words), and are rewarded with the ```This doesn't appear to be a valid email address``` error message.

Could we try making the 'Add email address' look like a textbox?

**Comment by pafcu** [comment]
Also "disable" the plus sign (make semi-transparent, don't change mouse pointer to indicate it is clickable, don't do anything when clicked, add a tooltip "Add another email address").

**Comment by aaronraimist** [comment]
This is fixed
