### ISSUE TITLE
Generic E2E Issue

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4602]
There are several rageshakes which are related to E2E but the description doesn't give much to help in triaging. I'm creating this generic issue to reference from them.

**Comment by richvdh** [comment]
I'm... not sure this is something we can do anything with?

**Comment by lampholder** [comment]
Hmm, and it looks like I didn't even associate that many rageshakes with it. Not sure what I was thinking. Probably just despairing at rageshake after rageshake of "E2E borken".

You're right though, I think we can close this.
