### ISSUE TITLE
The day separator in the timeline also includes a time, which I find confusing

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4605]
This only seems to happen when the day separator is far enough back in time that it also includes a date. Separators for today, yesterday and the few days before that (identified only by their name, not the date) don't include a time.

TBH I'd prefer if it always just had the day and date in there. Today/Yesterday isn't even necessarily true if I haven't refreshed the timeline - a good solid unambiguous day and date would be very reassuring.

**Comment by turt2live** [comment]
"Today" and "yesterday" are helpful to me, as it means I don't have to think about when the messages were sent. The timestamps in later breaks are strange, however.

**Comment by ara4n** [comment]
The 'showTwelveHour' thing sounds like it would have been absentmindedly added by someone when adding 12h support

**Comment by t3chguy** [comment]
fair enough, DateUtils has no methods for creating date strings with no time, so adding one
