### ISSUE TITLE
I would like to delete my current avatar and revert to the default one.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4611]
From a rageshake.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4611

**Comment by lampholder** [comment]
#4611 is a dup of... #4611?

**Comment by t3chguy** [comment]
@turt2live you've outdone yourself this time :P

**Comment by turt2live** [comment]
I'm the best at this. I meant https://github.com/vector-im/riot-web/issues/682

**Comment by t3chguy** [comment]
Duplicate confirmed!
