### ISSUE TITLE
Inviting multiple people only invites the first person

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4614]
### Description

When trying to invite multiple people to a room in one shot only the first person receives an invite. The remaining people do not see an invite, and an event is not pushed to the timeline.

### Steps to reproduce

- Create a room
- Open invite dialog
- Enter 2+ names to invite
- Send invites

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

```
matrix-react-sdk version: <local>
riot-web version: cb4f57eb4a2b-react-ee5117525c3c-js-e2599071c5db
olm version: 2.2.1
```

**Comment by lampholder** [comment]
This does seem to be the case - I'll just check whether it's happening on /app, too...

**Comment by dbkr** [comment]
This is another bluebird regression ftr, due to the multiple invite code usiing deferred.notify which bluebird doesn't have
