### ISSUE TITLE
User invite autocomplete should prioritize frequent invites/matrix users first

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4616]
### Description

I often invite my matrix.org account (`@turt2live:matrix.org`) to rooms, and yet it still suggests an IRC user to invite. matrix-native users should probably be prioritized higher than IRC, imo. More so it should definitely prioritize the account I invite constantly to rooms over the ones I don't.

![image](https://user-images.githubusercontent.com/1190097/28281423-41d09962-6ae4-11e7-8316-f1cb466c3d32.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Interesting - we did some work to address exactly this, and anecdotally it seems to be working pretty well for me... I wonder if we prioritise display name over mxid?

**Comment by aaronraimist** [comment]
Probably fixed by the new invite dialog?

**Comment by turt2live** [comment]
yup, or at least close enough
