### ISSUE TITLE
Autocompleting room suggestions can be duplicated

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4618]
### Description

Seems to only duplicate the room after hitting `:m`, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/1190097/28283226-58606d46-6aea-11e7-9e34-6bd7fc7c321f.png)

### Steps to reproduce

- Start autocomplete for `#irc:matrix.org` by typing `#irc:m`

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I can't reproduce this, and I know @lukebarnard1 is active in the area - Luke have you already fixed this?

**Comment by lukebarnard1** [comment]
This is the one area of the auto completion I _haven't_ touched, but I do plan to because it could do with some changes and this looks like it could be a simple fix.

**Comment by turt2live** [comment]
I've also managed to reproduce the issue by auto completing a room without the colon. It probably doesn't help much.

![image](https://user-images.githubusercontent.com/1190097/28319519-58da722a-6b8b-11e7-967d-91645d986894.png)
