### ISSUE TITLE
autocompleting emoji should search within emoji descriptions rather than just prefix match

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4620]
unlike usernames, emoji searches should search within the descriptions of emoji - e.g. :tongue<tab> should match both :tongue: and :stuck_out_tongue: etc. (Also, we shouldn't truncate :stuck_out_tongue_winking_eye: to :stuck_out_tongue...: as otherwise the lable is basically useless)

**Comment by lampholder** [comment]
I think we can release without this, but it's a great optimisation.

**Comment by lukebarnard1** [comment]
So this is happening because the `:` which is part of the query (and which needs to be there for searching ascii aliases e.g. ":)") is preventing matches against data such as "face with tears of joy". 

It would be nice if we could take off the ":" for matching against certain data vs. others.
