### ISSUE TITLE
Accepting invites is consistently broken for me.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4624]
* I receive invite on develop
* I click accept
* I get infinite spinning
* On refresh, the client no longer shows the room at all - i have to refresh cache to recover it.

This seems similar to:
* https://github.com/vector-im/riot-web/issues/4298
* https://github.com/vector-im/riot-web/issues/4518
* https://github.com/vector-im/riot-web/issues/4307

This is rageshaked at:
* https://github.com/matrix-org/riot-web-rageshakes/issues/257
* https://github.com/matrix-org/riot-web-rageshakes/issues/256 
* https://github.com/matrix-org/riot-web-rageshakes/issues/239
* https://github.com/matrix-org/riot-web-rageshakes/issues/233

**Comment by dbkr** [comment]
Above PR should fix the infinite spinner, but may not fix the fact that it vanished on refresh.

**Comment by lukebarnard1** [comment]
@ara4n is this still a problem?

**Comment by ara4n** [comment]
i haven't seen it since, although haven't tried it either. can someone try to repro, and then declare dave's fix worked if they can't repro?

**Comment by lukebarnard1** [comment]
I've tested and don't get an infinite spinner at least.

**Comment by ara4n** [comment]
nobody's seen this since Aug 15 so........
