### ISSUE TITLE
[Feature request] Lookup DNS SRV record before connecting to Matrix server

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4625]
Very often Matrix server located at another ip address that main domain or non-standard port, so Riot users must type subdomain address and port number manually.

For example, example.com domain with IP 1.2.3.4 and Matrix server on subdomain matrixhomeserver.example.com:8008 (without ssl at now) at IP 5.6.7.8. 

Will be good to lookup DNS SRV record of example.com domain before connecting and connect to other address, if exists, so users of riot.im can type https://example.com as address of server, instead of long https://matrixhomeserver.example.com:8008

**Comment by t3chguy** [comment]
closing as dup #2682 (see that issue for meta issue)
