### ISSUE TITLE
moving the cursor whilst autocompleting in RTE doesn't cancel current autocompletion

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4627]
So if I start typing :smil but then change my mind and use mouse or cursor keys to move elsewhere in the composer text input field, the autocomplete options keep lingering confusingly.  Surely they should disappear the second I move my cursor and thus leave autocompletion mode

**Comment by lukebarnard1** [comment]
It's possible to click on the autocomplete options though?

**Comment by lukebarnard1** [comment]
OH. You don't mean the mouse cursor. Yep the autocompleter should definitely be cancelled if you move.

**Comment by lukebarnard1** [comment]
This conflicts a little bit with "we should navigate through the autocomplete dialog with left and right arrow keys" - https://github.com/vector-im/riot-web/issues/4737

**Comment by lampholder** [comment]
I'd suggest we keep it simple:
- left and right move back and forth through the list
- up and down the same as left and right (for now, until and unless we develop some sort of autocomplete grid)
- clicking anywhere outside of the autocomplete suggestion box closes the autocomplete suggestion box
- pressing <kbd>Esc</kbd> closes the autocomplete suggestion box

**Comment by lukebarnard1** [comment]
>- clicking anywhere outside of the autocomplete suggestion box closes the autocomplete suggestion box

Something tells me this won't be an easy thing to achieve. How about whenever the composer loses focus, we hide the autocompleter?

**Comment by lampholder** [comment]
Works for me :)

**Comment by lukebarnard1** [comment]
fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1287
