### ISSUE TITLE
Closing the electron Riot.im non-obviously minimises it to the system tray rather than properly closing it.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4628]
I would expect it to close the application.

**Comment by lampholder** [comment]
We might want this to be configurable? And/or (on first close/minimise) pop up a message explaining what's happened?

**Comment by ArchangeGabriel** [comment]
This is standard behaviour for a lot of apps, but I agree it could be made configurable.

**Comment by t3chguy** [comment]
I already have an IPC for configuration of the electron main process from the renderer, so just need to add persistence and then this'll be painless

**Comment by fuzzy76** [comment]
For OS X the normal behaviour is closing the window, but keeping the app running. Which is what is does now. :)

**Comment by BPaden** [comment]
A system tray is also not guaranteed to exist on Linux. It doesn't on gnome now. Riot should automatically detect this case and Do The Right Thing™.

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/3133

**Comment by eleius** [comment]
I have this problem in Gnome. No tray icon so I cannot close Riot (I have to kill the process, or start it from the terminal and use ctrl-c to exit).

**Comment by xoxys** [comment]
Also, closing with Menu -> Close does not force close Riot on gnome/fedora. And that's a default behavior in MacOS as I know... There has to be a way to force close a UI application without killing the process on cli. That's a bit messy and should be fixed

**Comment by t3chguy** [comment]
This is configurable:

![image](https://user-images.githubusercontent.com/2403652/62458004-d1c54800-b773-11e9-8913-de34b7e32c43.png)

**Comment by 532910** [comment]
ack. Thank you!
