### ISSUE TITLE
UX: People aren't creating 1:1 chats, but instead are creating rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4631]
Quite a few people on our homeserver (tang.ents.ca) are creating new rooms and inviting one other person to create a direct chat with them, instead of using the 'Start Chat' buttons in the UI. We should be reporting piwik analytics upstream, but I'm not sure if these users have it enabled or if the metrics catch this case.

I've personally seen this on the receiving side of these rooms for tang.ents.ca as well as users on other homeservers (which is why I'm reporting this). The rooms end up as generic rooms (presumably because `is_direct` is false/missing) and I'm without admin rights, implying they didn't "start a chat" but instead created a room and invited me to it.

A possible solution may be to somehow communicate to the user creating the room that they're creating a 1:1 without realizing it, and asking them if that was their intention. I'm also not a UX designer, so this might be a bad idea. 

This doesn't really affect anything in terms of day-to-day usage on Riot, but does confuse some users on the receiving end (chats aren't "People").

**Comment by lampholder** [comment]
A hard one to prioritise this - @t3chguy how feasible do you think it would be for piwik to provide useful stats on this? I have a feeling it might be tricky (since we'd be trying to interpret a sequence of UI events to distill the user's intent to 'create a one-to-one room by creating a new room and inviting one person to it').

**Comment by t3chguy** [comment]
how would you suggest differentiating between a room that they invite one user to and one they invite multiple users to one-at-a-time :/?

**Comment by t3chguy** [comment]
could say if they invite one person and then no more in the next X minutes, then send that as an event, but if they close riot before that X minutes is up that would be lost etc

**Comment by lampholder** [comment]
That feels like it's going to be tricky to implement (and buggy) - I wonder if there's a better way to measure this.

**Comment by turt2live** [comment]
I'm not sure what's changed in the last 5 months, but this isn't happening now (and hasn't happened for a few months now). I'm not sure if it's worth keeping this open for the tracking aspect (assuming it's not already done) - but the core issue appears to be "fixed".

**Comment by turt2live** [comment]
I'm going to go ahead and close this - the primary issue is fixed and no one has spoken up against my last comment.

If there are opinions otherwise, please re-open or open a new issue.
