### ISSUE TITLE
Change log text too dark on dark theme

### ISSUE THREAD

**Issue by Qwertie-** [vector-im/riot-web#4637]
The text on the dark theme is too low contrast to read easily while using the dark theme.

![example image](https://i.imgur.com/4QoWjgT.png)

riot-web version: bd693768ccb3-react-b9dfaf777e5a-js-e2599071c5db
Browser: firefox
OS: ubuntu 17.04

**Comment by turt2live** [comment]
This is probably a side effect of using the dark tint in a room. The default tint seems to look fine.
![image](https://user-images.githubusercontent.com/1190097/28372941-3cb7199e-6c5e-11e7-94b5-eebd243df881.png)

**Comment by pafcu** [comment]
@Qwertie- Was the issue due to grey tinting, and is it sovled now that grey is no longer a suggested color?

**Comment by Qwertie-** [comment]
@pafcu Quite possibly. I haven't had the issue in a while.

**Comment by pafcu** [comment]
Perhaps it could be closed in that case?

**Comment by Qwertie-** [comment]
Yep, looks like it's solved.
