### ISSUE TITLE
VOIP outputs sound to the wrong device, no option to change output device

### ISSUE THREAD

**Issue by foxlet** [vector-im/riot-web#4648]
### Description

When making a call via VOIP on Riot, the wrong output device is used (nothing can be heard), and there is no option under the desktop client to change the output device.

### Steps to reproduce

- Start conference call
- Attempt to talk
- Hear no sound in response

There is no sound, although other users can hear the microphone properly. It would be useful to have a dropdown for selecting the proper audio device for output under the desktop client.

Log: not sent    

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows
- **Version**: 0.11.4

**Comment by t3chguy** [comment]
Dup #4203
