### ISSUE TITLE
RTE: set `contentEditable` to false on `img` tags in the composer

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4651]
Otherwise some browsers let you resize them

**Comment by ara4n** [comment]
i /think/ this is fixed in slate in matrix-org/matrix-react-sdk#1890, but need to check.

**Comment by ara4n** [comment]
according to https://stackoverflow.com/questions/19165944/contenteditable-image-resize-in-chrome-what-is-the-best-solution, firefox does this out of the box. so, to test this, one would plonk an img tag into the RTE somehow and then see if you can resize it via gribbers or not.

However, i don't think we allow you to copy-paste images into the new RTE in RT mode yet - and i don't think it would roundtrip a MD image into a contenteditable image in the RTE currently either.

So, i strongly suspect this is completely irrelevant until we support authoring images in slate in the first place.
