### ISSUE TITLE
Move app caches to from config home folder to cache in Riot-app on Linux

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4653]
At now Riot-web application store cache files near to config files in folders `~/.config/Riot/Cache` and `~/.config/Riot/GPUCache`, so config folder contains many useless files with large size (more than 200 mb).
Will be good to move all cache files to `~/.cache/Riot/` folder, like other apps do.

**Comment by t3chguy** [comment]
@MurzNN not possible with Electron - https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

Open an issue upstream

**Comment by MurzNN** [comment]
Yes, it's Electron issue: https://github.com/electron/electron/issues/1404

**Comment by t3chguy** [comment]
not quite, that issue is about roaming vs non-roaming AppData on Windows

**Comment by MurzNN** [comment]
So I create new issue about Linux cache folder: https://github.com/electron/electron/issues/10082
