### ISSUE TITLE
User pills on RTE bugs

### ISSUE THREAD

**Issue by Kegsay** [vector-im/riot-web#4654]
cc https://github.com/vector-im/riot-web/issues/4640

In all these examples, I'm using `Guggy` as the name of a person in the room.

- Backspacing over a user pill doesn't work at all (it skips to the front of the pill) - E.g `hello Gugg<tab><backspace>`
- Backspacing over a user pill when you already have the name in non-pill form jumps you to the earliest occurrence of the name - E.g `hello Guggy and Gugg<tab><backspace>`.
- If you CTRL+A (select all) and try to remove the input text after backspacing, it doesn't remove all the text. It also seems to cleave the pill in half somewhere exposing the markdown underneath. - E.g `hello Gugg<tab><backspace><ctrl+a><backspace><ctrl+a><backspace><ctrl+a><backspace>` see https://github.com/vector-im/riot-web/issues/4666

**Comment by Kegsay** [comment]
- Quoting text with a pill in it exposes the raw markdown underneath for some reason - E.g `hello Gugg<tab><select all><hit quote button>`

**Comment by lukebarnard1** [comment]
FTR Markdown mode was enabled for these issues

**Comment by lukebarnard1** [comment]
>Backspacing over a user pill doesn't work at all

Actually, it only suffers from weird jumping when backspacing in front of an entity that is _not_ at the start of the message. 

> jumps you to the earliest occurrence of the name

This is the same bug, but it looks like a coincidence that the cursor ended up at the earliest occurance.

**Comment by turt2live** [comment]
I don't know if this is categorized or not already, but here's a strange key sequence (using `seequ` as the user)
`hello see<tab>'s<backspace><backspace><backspace>'s<backspace><backspace><end>'s`

Animated here
![gif](http://g.recordit.co/j0pnO9wj18.gif)

**Comment by lukebarnard1** [comment]
When logging the selection state (the position of the text cursor) it's clear that draft-js has issues knowing where the cursor is when it enters an entity, causing all sorts of craziness. When the cursor enters an entity, its offset becomes relative to the entity itself, which explains all of the bugs!

**Comment by lukebarnard1** [comment]
I've come across something that suggests using `data-offset-key` in the decorators and it seems to fix this issue.
