### ISSUE TITLE
Keywords for mention do not trim whitespace, leading to lack of notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4657]
### Description

I had keyword notifications set to `turt2live, t2bot` and was not being pinged for `t2bot`. Turns out the space in front was the problem.

### Steps to reproduce

- Set multiple keywords, comma separated (as per instructions) with spaces around the comma
- Try to get pinged

I would have expected that the keywords would support some basic presentation formatting (1 space after the comma) so as to not mysteriously not ping me.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
I can't reproduce this. @turt2live could you try reproducing again?

**Comment by turt2live** [comment]
I can't reproduce this 25 days later (sorry for the huge delay). I'm assuming it was either something wrong in my testing, or some strange unrelated bug.
