### ISSUE TITLE
Add Debian buster and Ubuntu disco distros

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#4661]
As debian is starting with the buster cycle it would be an excellent opportunity for riot to work with Debian. I do/did hear that riot would be in Debian soonish (meaning the buster cycle of roughly around 2 years). It would have been nice to have some initial buster support on the lines of -
```
18	######## Third party repos #######
19	deb https://riot.im/packages/debian/ buster main
```
If I add that to my /etc/apt/sources.list I get the following -

```
E: The repository 'https://riot.im/packages/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Please fix the above.

**Comment by uhoreg** [comment]
> I do/did hear that riot would be in Debian soonish

I find it unlikely, given that there are some significant dependencies that are not yet in Debian, including React and Electron.  Unless the Debian JavaScript team pulls off some sort of miracle in the next couple of years.

**Comment by shirishag75** [comment]
FWIW, react is now in debian https://salsa.debian.org/js-team/node-react

**Comment by uhoreg** [comment]
Yup, I already noted that it https://wiki.debian.org/Matrix.  There's still a bunch of other libraries that need to be packaged.

**Comment by shirishag75** [comment]
ah cool, just writing about it. Btw have been looking at https://riot.im/desktop.html and https://riot.im/packages/debian/dists/ . There it says sid instead of unstable. I know some people use 'unstable' some people use 'sid' , there are still no rules if we should call it one or other - 

```
/etc/apt/sources.list.d> cat matrix-riot-im.list 
deb https://riot.im/packages/debian/ sid main 
```

And it has worked for the time-being - 

```
/home/shirish> sudo apt update
[sudo] password for shirish: 
Hit:1 http://debug.mirrors.debian.org/debian-debug testing-debug InRelease                           
Hit:2 http://debug.mirrors.debian.org/debian-debug unstable-debug InRelease                                                    
Get:3 https://riot.im/packages/debian sid InRelease [3,061 B]                                                                  
Hit:4 http://debug.mirrors.debian.org/debian-debug experimental-debug InRelease                 
Get:5 https://riot.im/packages/debian sid/main amd64 Packages [420 B]                   
Hit:6 http://cdn-fastly.deb.debian.org/debian buster InRelease                                                                                                                 
Hit:7 http://cdn-fastly.deb.debian.org/debian unstable InRelease
Hit:8 http://cdn-fastly.deb.debian.org/debian experimental InRelease
Fetched 3,481 B in 27s (129 B/s)                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

```
```
/home/shirish> aptitude search riot-web
p   riot-web                                                                        - A feature-rich client for Matrix.org 
```

It seems it still has no gtk+3 support as of  now.

**Comment by shirishag75** [comment]
FWIW, there is stretch and sid support but no buster lablel yet :( . The sid support seems to have been done about couple of weeks back from the time-stamp. 

https://riot.im/packages/debian/dists/

**Comment by fndax** [comment]
Debian buster is now frozen for release in a few months. Riot will not be in Debian's repositories for buster, and https://riot.im/packages/debian/dists/ hasn't been updated to include buster yet.

Notably, riot.im's repositories are also missing disco, the current non-LTS version of Ubuntu, released last week.

**Comment by jryans** [comment]
Let's morph this issue into the smaller task of validating that Riot works on these new distro releases and adding them to the set we regularly deploy.

**Comment by richvdh** [comment]
I've added the package to buster and disco in the repository. I'm afraid I've not tested it works on either distro.

**Comment by richvdh** [comment]
(I also removed trusty and wheezy while I was there)

**Comment by shirishag75** [comment]
FWIW, I didn't see any change per-se -

```
$ cat /etc/apt/sources.list | grep riot
	  deb https://riot.im/packages/debian/ buster main
```

```
$ sudo apt update
............................
...........................
Get:8 https://packages.riot.im/debian buster InRelease [2,894 B]
Get:9 https://packages.riot.im/debian buster/main amd64 Packages [431 B]
```

I haven't tried this though as yet, should I uncomment it now ?

```
/etc/apt/sources.list.d$ cat matrix-org.list 
# This sourcelist is managed by the matrix-archive-keyring package; changes
# done here will be overridden by the next package configuration or update.
# deb [signed-by=/usr/share/keyrings/matrix-archive-keyring.gpg] http://matrix.org/packages/debian/ buster main
# deb-src [signed-by=/usr/share/keyrings/matrix-archive-keyring.gpg] http://matrix.org/packages/debian/ buster main
```

**Comment by jryans** [comment]
@shirishag75 I think you might be mixing up the Riot and Synapse package repos. We recently updated the instructions at https://riot.im/download/desktop for the new Riot packaging key. I'd suggest trying those steps.

**Comment by jooola** [comment]
@richvdh Just installed the package from the buster repo, everything went well.

**Comment by ra1nb0w** [comment]
> @richvdh Just installed the package from the buster repo, everything went well.

Also for me. thank you!

**Comment by jryans** [comment]
Thanks for the verification! I am going to consider this task done. Thanks for the help @richvdh!

If some are still having trouble, please open a new issue.
