### ISSUE TITLE
Editing an RTE tab-completion at the beginning of a message to remove : is b0rked

### ISSUE THREAD

**Issue by superdump** [vector-im/riot-web#4666]
When tab-completing a name in RTE at the beginning of a message, a `:` is appended. Sometimes I don't want to direct a message at that person but just mention them, at the beginning of a message. Pressing left-arrow to go back past the space and then hitting backspace to erase the `:` results in the tab-completion expanding to its markdown form which feels really odd. IMO the `:` is a convenience and not part of the mention itself so this shouldn't happen. Only editing within the tab-completed name itself should do this.

**Comment by lampholder** [comment]
Is this already fixed? I'm not experiencing this, either with markdown enabled or disabled...

**Comment by lukebarnard1** [comment]
This seems like the same bug causing part of #4654:
>If you CTRL+A (select all) and try to remove the input text after backspacing, it doesn't remove all the text. It also seems to cleave the pill in half somewhere exposing the markdown underneath. - E.g hello Gugg<tab><backspace><ctrl+a><backspace><ctrl+a><backspace><ctrl+a><backspace> see #4666

**Comment by lampholder** [comment]
Ah yes, I meant to come back to this - later in the day I definitely did experience the same behavour @superdump describes :(

**Comment by lukebarnard1** [comment]
As predicted, if we insert underlying content for the entity that has the same length as the entity itself, this issue goes away.
