### ISSUE TITLE
3pid invite memberinfo

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4667]
for a normal invite you can see memberinfo of the invitee, after clicking on them in the room members right panel. For a 3pid invite the on-hover `>` appears but clicking does nothing

**Comment by lampholder** [comment]
This might be a dumb question but are you sure it's a valid 3pid identifier?

Trying to reproduce this, I found I could see the memberinfo of a newly created user when invited by their email address, but an email address that _didn't_ resolve to a real user behaved in the manner you described.

**Comment by t3chguy** [comment]
I'm saying before they act on the invite, so one that sent out an email to a prospective new user 
Basically the on hover `>` should be hidden if clicking on it doesn't bring up a member info
