### ISSUE TITLE
Serious RTE glitch observed when pasting into a code block with markdown enabled

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4675]
c.f. https://matrix.org/_matrix/media/v1/download/matrix.org/dJUSQimGEIITIMxamnzyjQuy

**Comment by lampholder** [comment]
Matthew appears to:
- click on the RTE
- type three backticks
- presumably presses 'shift+enter' in order to move to a new line without sending the message
- pastes some text (presumably from iterm, presumably having highlighted it with the mouse and then pressing ctrl+v in the rte
- perhaps he then presses ctrl+j to close the code block
- the cursor then gets moves to the wrong position (two characters into the original three backticks) and it seems to get worse from there...

**Comment by lukebarnard1** [comment]
>perhaps he then presses ctrl+j to close the code block

I don't think so, otherwise there would be more backticks inserted into the composer

**Comment by lukebarnard1** [comment]
So I've figured out that this is platform dependent and an example is the Chrome/macOs/terminal combination, which I'm assuming was used here. It's possible that the fact that the copying was done from terminal is irrelevant. 

What's clear is that the pasted text must include tab characters.

**Comment by lukebarnard1** [comment]
I know think this is https://github.com/facebook/draft-js/issues/1146 based on the fix, which updates `editOnInput.js`, which is the thing causing the weird deletion of text.

**Comment by lukebarnard1** [comment]
Right. Updating the draft-js version to 0.10.1 does actually work.

**Comment by ara4n** [comment]
are you sure that's fixed?

https://matrix.org/_matrix/media/v1/download/matrix.org/orYDeRCqJHStohNMdZeCUpuu

**Comment by lukebarnard1** [comment]
So I've got a local build where it really really works. I shall investigate the diff between PR https://github.com/matrix-org/matrix-react-sdk/issues/1262

**Comment by lukebarnard1** [comment]
So. Riot also depends on draft-js. And it's a dependency on 0.8.1.

**Comment by lukebarnard1** [comment]
This didn't work :confused:

**Comment by turt2live** [comment]
fwiw, I managed to reproduce this on riot.im/develop on Windows 10 Chrome 59. 

Copy/pasted a multiline search result from Github (there a tab after `30` on the second line):
```

const USERNAME_REGEX = /@\S+:\S+/g;
--
30 | const ROOM_REGEX = /#\S+:\S+/g;
```

^ Raw copy/paste
Search result is from looking for `regex` in `matrix-react-sdk` and finding the result for `RichText.js`, highlighting the code on lines 29 & 30 (backwards)

**Comment by lukebarnard1** [comment]
https://github.com/facebook/draft-js/commit/5863399a3a1bcbbe9b090249504a70496a7af7cc is the commit that we want in our draft-js dep. `0.11.0-alpha` has been published on npm and contains this commit, so let's stick it on `develop` branch and see if this is is fixed.
