### ISSUE TITLE
Cannot /join an auto-completed room alias

### ISSUE THREAD

**Issue by Kegsay** [vector-im/riot-web#4676]
I tried typing:
```
/join #neb
```
and saw `#neb:matrix.org` pop up, so I selected it with my mouse and then hit enter and a dialog appeared which said:
```
Command Error
Usage: /join #alias:domain
```

I'm guessing because the raw text is in markdown form by that point.

**Comment by lukebarnard1** [comment]
This would be fixed if we didn't insert MD on completion of rooms, much like https://github.com/vector-im/riot-web/issues/4674

**Comment by lukebarnard1** [comment]
> because the raw text is in markdown form by that point.

correct

**Comment by lukebarnard1** [comment]
So instead of totally rewriting the RTE to either use entities with type `MENTION` or totally rewriting the RTE to always use the same AST for a given message (see #4679), I'm going to do the quick fix of stripping MD mentions before handling commands.
