### ISSUE TITLE
RTE does WAY too many conversions

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4679]
We have had many discussions that end up with us wishing that the draft-js editor always represented the same message with the same underlying AST (= Abstract Syntax Tree) regardless of whether markdown mode is enabled. Currently we have problems such as:
 - Toggling markdown mode is not a stable conversion: https://github.com/vector-im/riot-web/issues/1944
 - Loading history into the composer but it not appearing exactly as it was at the point of sending (which has the same issues as toggling between MD mode and RT mode, despite them being on totally separate code paths)
 - Any issues resulting from inserting different content depending on whether we're in markdown mode or not (like https://github.com/vector-im/riot-web/issues/4676)
 - In theory any issue that occurs in markdown mode alone.

Options:
 - Always use one format (either markdown or rich)
 - Always use markdown but then use clever decorators to make it _look_ rich when we're in RT mode
 - Always use richtext but use clever decorators to make it _look_ like markdown when we're in MD mode

See this diagram for full awfulness:
![ima_0f6318f](https://user-images.githubusercontent.com/6750344/28617274-a96aefae-71f7-11e7-97c7-e1a2e6a3d782.jpeg)

**Comment by ara4n** [comment]
Slate does fewer conversions, and I think its behaviour is justified.  You can see the equivalent of the above diagram over at https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/slate-formats.md
