### ISSUE TITLE
matrix.to links to events in rooms are shown as the room id / event id

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#4680]
https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$150107937414OJXuY:msgs.tk

**Comment by krombel** [comment]
The link-text does not get shown (only when viewing the source code of the event)

**Comment by lukebarnard1** [comment]
Ah, this is because the link is treated as a room pill for a room, when it should just appear as intended.
