### ISSUE TITLE
Leaving roomDirectory out of the config results in a blank screen on load

### ISSUE THREAD

**Issue by sirideain** [vector-im/riot-web#4681]
### Description

I am setting up Riot with a matrix home server. If I leave the roomDirectory out of the Riot config, I only ever get a blank screen in the browser. There are no controls or anything. Adding the roomDirectory back gets it working again.

### Steps to reproduce

- Use a home server
- Comment out the roomDirectory section
- Hard reload web page

### Version information

- **Browser**: Chrome and Firefox, current releases
- **OS**: Windows
- **URL**: v0.11.4

**Comment by aaronraimist** [comment]
This seems to work now. If you are still having issues feel free to reopen or open a new issue.
