### ISSUE TITLE
HTML entities in message text are auto-converted to symbols in Riot-web & Android app

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4684]
When I send message with HTML entities like `&tcy;&iecy;&scy;&tcy;4` - Riot on web and Android app auto converts it to symbols, so me and other people see this text in sent message like "`тест4`" instead of source with html entities like "`&tcy;&iecy;&scy;&tcy;4`".

**Comment by t3chguy** [comment]
This is down to Commonmark. Open an issue upstream.
Try your above input here: http://spec.commonmark.org/dingus/

**Comment by t3chguy** [comment]
using backticks like you did above in your GH issue works

**Comment by MurzNN** [comment]
Thanks, I create same issue in CommonMark project: https://github.com/jgm/CommonMark/issues/484
