### ISSUE TITLE
lock icon on messages may be misleading

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4689]
users may interpret the lock icon on a message as indicating secrecy (i.e. it was only sent *to* verified devices), whereas it actually indicates authenticity (it was sent *from* a verified device.  See the discussion starting at https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1501179243453616DNeTx:matrix.org

**Comment by lheckemann** [comment]
A tick mark on the avatar might be clearer in meaning. A separate secrecy indicator (I think the lock icon is nice for this) would be nice to have, but I'm not sure secrecy is actually possible to determine? I don't really know much about the model for matrix.

**Comment by lampholder** [comment]
This certainly warrants further thought, but as a first, easy step we could just whack a tooltip on the padlocks to explain what they're trying to represent.

**Comment by uhoreg** [comment]
I think maybe changing the lock icon to a checkmark icon may be sufficient.

**Comment by turt2live** [comment]
We don't have a lock icon anymore
