### ISSUE TITLE
Cannot autocomplete #ents:tang.ents.ca without difficulty

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4691]
### Description

This is more of a specific issue for a set of rooms, but will cause problems when we inevitably update Riot on tang.ents.ca.

tang.ents.ca has several rooms, some are private to specific members. When trying to get auto complete suggestions for `#ents:tang.ents.ca` I see rooms for everything except the "main" room.

![image](https://user-images.githubusercontent.com/1190097/28691232-68d7ba5c-72d9-11e7-9c3a-1ec12d6a5afe.png)

I am able to eventually autocomplete it when I type enough of the domain part.

Here's an example on a less test-filled account:
![image](https://user-images.githubusercontent.com/1190097/28691405-112a1632-72da-11e7-8665-de4c2881348a.png)

### Steps to reproduce

- Join a bunch of tang.ents.ca rooms
- Try to autocomplete `#ents:tang.ents.ca`

I would expect that the near-exact match for a room would be the first suggestion, not other rooms.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
OK, so this comes under "we should be putting exact matches at the top of auto completed rooms/users/emoji"

**Comment by turt2live** [comment]
I also wouldn't be surprised if it's confusing the scoring for rooms because of the homeserver domain/room titles (all of them are prefixed `ENTS`).
