### ISSUE TITLE
Pill mention causes scrollbar in RTE

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4695]
### Description

![image](https://user-images.githubusercontent.com/1190097/28723798-2b383b26-7375-11e7-8e73-e9ac5c730792.png)

See right hand side of image. Having the markdown tray expanded does not appear to affect the result. 

### Steps to reproduce

- Click-to-mention someone

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
This is only when there's an initial avatar in the pill

**Comment by lukebarnard1** [comment]
Fixed by matrix-org/matrix-react-sdk@07ca70f
