### ISSUE TITLE
CTRL+Z should un-pill, not clear the entire message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4698]
### Description

Undo currently wipes the entire field clean of all text, which forever loses that message. Undo should, at least in my opinion, undo the pill after a suggestion to what it was before accepting the suggestion.

### Steps to reproduce

- Type part of an alias
- Tab complete it
- CTRL+Z

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I think this would be nice to have, but for now at least the behaviour is consistent (ctrl+z wipes your current message).

To compare with other platforms:

- fb messenger
    - does enpill identified user names
    - ctrl-z restores to the typed-characters-pre-suggestions
    - ctrl-z otherwise just wipes the message
    - there is no 'redo' (ctrl-r, ctrl-y)
- slack
    - does not enpill identified user names after accepting a suggestion
    - ctrl-z wipes the message
    - there is no 'redo' (ctrl-r, ctrl-y)

**Comment by turt2live** [comment]
This happened at some point
