### ISSUE TITLE
Theme Options in User Settings Are Mildly Broken

### ISSUE THREAD

**Issue by tessgadwa** [vector-im/riot-web#4700]
### Description

After switching between theme options using the radio buttons in User Settings, switching back to the previous selection has no effect.

### Steps to reproduce

- Switch from Light theme to Dark theme
- Without closing the User Settings window, switch back from Dark theme to Light theme

The theme will remain Dark.

If you close the User Settings window and reopen, you are then able to select the radio button for the theme of your choice. 

Log: sent

![screen shot 2017-07-28 at 8 53 50 am](https://user-images.githubusercontent.com/6475035/28725605-d460360c-7372-11e7-842d-6b8a653bc30e.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 59.0.3
- **OS**: macOS
- **URL**: https://riot.im/app

**Comment by turt2live** [comment]
Confirmed also broken on riot.im/develop

**Comment by tessgadwa** [comment]
This is only a minor glitch in everyday use, but becomes more problematic when >2 theme options are included under User Settings.

**Comment by lampholder** [comment]
When trying to reproduce this, I had a slightly different failure mode.

I had Riot logged in on two machines (side by side). Toggling from light to dark on machine A, the change actually occurred on machine B. Machine A did not change it's theme.

Toggling from dark back to light as described in the original report had no effect.

**Comment by t3chguy** [comment]
note to self, onChange is only firing the first time

**Comment by t3chguy** [comment]
was fine in v0.10.2

**Comment by t3chguy** [comment]
It seems like it was broken by an unpinned React dep
(and them fixing an implicit bug)

**Comment by t3chguy** [comment]
React 15.6.0 introduced https://github.com/facebook/react/pull/8575 which broke the theme selector

**Comment by turt2live** [comment]
This has been fixed.
