### ISSUE TITLE
The fact we show 'click here to join the room' room preview whenever we start a chat is very ugly and jarring

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4701]
and a regression

**Comment by lukebarnard1** [comment]
I can't reproduce this by starting a chat with someone.

**Comment by turt2live** [comment]
I can still reproduce this. Logs sent via rageshake.

**Comment by lukebarnard1** [comment]
@turt2live I can't find your rageshake, what did you put in it?

**Comment by turt2live** [comment]
@lukebarnard1 Looks like chrome ate the bug report, but trying to reproduce this now is leading to unsuccessful attempts, although Riot is painfully slow to navigate to the room.

Probably some caching weirdness?

**Comment by ara4n** [comment]
This is trivial to reproduce on my side, and increasingly ugly and frustrating.  Here's a video. https://matrix.org/_matrix/media/v1/download/matrix.org/NxbVwuSelGzXBCWICPmRktVB

**Comment by ara4n** [comment]
And even worse is this: https://matrix.org/_matrix/media/v1/download/matrix.org/hKkIACfLEWtjRPuMVqjSiXfp - especially if you don't have permission to join the room, where it's just annoying to be nagged through a preview window after you told it precisely what you wanted to do.
