### ISSUE TITLE
Tab-completion order for emojis is frustrating

### ISSUE THREAD

**Issue by vberger** [vector-im/riot-web#4704]
If I want to insert ":book:" quickly, I expect to be able to type `:book:`, then press `<tab>` and the correct emoji to be there.

However the order of emojis in the completion window does not seem to be "best match first", and doing so gives me 📔 ( `:notebook_with_decorative_cover:`). The correct emoji for `:book:` is actually third of the list, and so I need to press `<tab>` 3 times.

There are several other emojis causing the same issue. For example, typing `:heart:` brings :heart: only 5th.

In general, one would expect when typing a complete emoji code before pressing `<tab>` to get the coded emoji first.

**Comment by t3chguy** [comment]
Luke knows about this and it is on his to-do
