### ISSUE TITLE
Search within a room: the white magnifying glass icon does not visibly pulse when its button, clicked, changes from green to off-white

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#4707]
From [Message search UI is confusing · Issue #3421 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/3421):

> … magnifying glass icon … clickable …

## Steps

1. prefer the dark theme
2. in the search field, type something
3. click the magnifying glass icon

## Expected

- the icon should pulse until matches begin to appear

## Actual result

- the button becomes almost completely off-white, not pulsing
- if you look very closely, you'll see the fractionally whiter magnifying glass within the off-white of the button

## Workaround

- to the left of the icon, click anywhere in the search field
- observe the white magnifying glass pulsing against a green button

**Comment by turt2live** [comment]
We no longer pulse the icon during searching
