### ISSUE TITLE
electron notification tray icon is still unstable on Windows

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4709]

**Comment by MTRNord** [comment]
Same goes for linux arch. But I am not sure if thats because it is started via the electron command. (It happens using the -git package so the new master)

**Comment by lampholder** [comment]
I feel like this is a known issue I'm missing context on... how is it unstable? What's happening?

**Comment by MTRNord** [comment]
On linux arch it is a to large one (Desktop system used is KDE Plasma 5)

**Comment by t3chguy** [comment]
Uninstall `libappindicator1` equivelant (thats what it is called on ubuntu)
I stubbed it on my system to fix that, thats not something we can fix in the app.

By unstable I mean sometimes the notifications count is sometimes wrong (doesn't match the window titlle)
and today I even had the tray icon go completely blank

**Comment by MTRNord** [comment]
@t3chguy oh ok didn't knew that. hm not sure if I should do it in the AUR package by default :/ is there a upstream electron issue about libappindicator1 ?

**Comment by t3chguy** [comment]
latest issue applies :P https://github.com/electron/electron/issues/10163

**Comment by dos1** [comment]
The issue on Arch is actually with Chromium - it's code for using libappindicator has a bug. I've submited a patchset that fixes this issue: https://chromium-review.googlesource.com/c/chromium/src/+/1173235

**Comment by syhe** [comment]
The current Riot Desktop app does not display a notification badge (with the number of channels that have notifications) on Taskbar buttons under Windows 10.

These buttons appear when you either pin the app to the taskbar or have set "Combine Taskbar buttons" to "Always, hide labels". Showing badges on Taskbar buttons is enabled.

If you configure your Taskbar to show the window labels it works as expected. Furthermore, highlighting/setting urgent marker on the window seems to be unaffected, though I encountered some hiccups when using combined buttons there as well in the past.

Can this be fixed / is this the correct issue for this? Is this the original buggy behavior that you encountered, @t3chguy ?

**Comment by t3chguy** [comment]
Another weirdness:
![image](https://user-images.githubusercontent.com/2403652/50542670-03ad7500-0bbb-11e9-876b-f3567c69ffea.png)

**Comment by turt2live** [comment]
@t3chguy are you still seeing this?

**Comment by t3chguy** [comment]
Sadly I haven't used the desktop app much for most of my Windows use is at work where my HS is blocked :(
