### ISSUE TITLE
Buttons misplaced in spanish UI

### ISSUE THREAD

**Issue by agarciabz** [vector-im/riot-web#4713]
### Description
Buttons for login ("Abrir sesión") and sign in ("Registrarse") appear not aligned. Plus, text for "Registrarse" is not correctly adapted to the button size (see attached image below).

![captura5](https://user-images.githubusercontent.com/27777512/28781404-3c4deef0-760a-11e7-9550-c29d40cdb905.PNG)

### Steps to reproduce

- Download and install Rise.im v0.11.4 for Windows x64.
- Open application.
- This issue appears in the first screen you see (see attached image above).

### Version information

- **Platform**:  Desktop

For the desktop app:

- **OS**: Windows 10 Pro
- **Version**: 10.0.15063

**Comment by Nostradamos** [comment]
Same happens in german.
https://user-images.githubusercontent.com/11379925/29368473-18fa5cd4-82a0-11e7-9004-88a1e50d1893.png

Problem is that the register & login button have a fixed width.
Solution, set width to min-width and add the following css:
```
.mx_LoginBox_registerButton {
    margin-top: 0;
    margin-bottom: -8px;
}
```

**Comment by t3chguy** [comment]
Closing in favour of duplicate #4804
