### ISSUE TITLE
MELS seems to stop working when there are hidden events between joins

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4716]
### Description

![image](https://user-images.githubusercontent.com/1190097/28808760-ce60d3bc-763b-11e7-9443-c8e31865f974.png)

Note the addition of the github bot, which requires configuration through state events.

### Steps to reproduce

- Invite some users
- Configure github

Expected MELS, like in earlier builds (screenshot below).
![image](https://user-images.githubusercontent.com/1190097/28808742-b01a1b52-763b-11e7-86cf-a1ae90a8057f.png)
*Please ignore the state bug surrounding the lack of join of the github announcement bot*

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
:(

**Comment by lampholder** [comment]
I'm not 100% convinced with my P2 minoring of this - it seems to me like something that won't come up very often and won't cause huge problems when it does, but I'm not confident in my assessement - please argue loudly if (and why) you think this should be prioritised differently.

**Comment by t3chguy** [comment]
Its a regression and I'll prioritise it higher to myself as its caused by my adding of hide-join-parts from what I can tell.

**Comment by t3chguy** [comment]
Cannot repro :(
![image](https://user-images.githubusercontent.com/2403652/28862176-fdaad3a4-775b-11e7-9809-3b5d01806d9a.png)

**Comment by t3chguy** [comment]
Cannot repro :(
![image](https://user-images.githubusercontent.com/2403652/28862215-2796bd7c-775c-11e7-84bf-17a29c19787d.png)

![image](https://user-images.githubusercontent.com/2403652/28862221-2be9e840-775c-11e7-88a4-b7b49eb4ddba.png)

**Comment by t3chguy** [comment]
okay, Travis has led me to where this happened and now I can reproduce, just need to isolate it

**Comment by t3chguy** [comment]
looks like an m.room.aliases event is actually causing this... still debugging

**Comment by t3chguy** [comment]
Aah I see what is happening

the MELS generation loop checks whether an event is not a memberEvent and breaks BEFORE it checks if its hidden.

**Comment by t3chguy** [comment]
Javascript debugging is beautiful

**Comment by t3chguy** [comment]
flipped OOO and now:
![image](https://user-images.githubusercontent.com/2403652/29362806-48c368ea-8285-11e7-94ea-61842fa9fd7a.png)
