### ISSUE TITLE
Cannot insert emoji after quote

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4728]
### Description

After quoting a previous message, I can't insert an emoji using autocomplete.

### Steps to reproduce

- click on the "..." menu to the right of a message
- select quote
- start typing an emoji (e.g. ":smi")
- click on an emoji in the autocomplete popup
- alternatively, hit tab and then space
- popup disappears, but text is not replaced by emoji

(It seems to work properly if there is no quoted message.)

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chromium
- **OS**: Debian
- **URL**: riot.im/develop (af85f18eae78-react-ff378cc85af9-js-bdb90b4b334f)

**Comment by lukebarnard1** [comment]
This affects all completions and seems to be a bug with `textOffsetsToSelectionState` where we return a selection state that doesn't have a `focusKey`.
