### ISSUE TITLE
inviting outsider to m.federate=false is a silent no-op

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4733]
server returns 403 but nothing is shown to user

**Comment by lampholder** [comment]
To clarify: do you mean that if you invite a user from a different homeserver to a room on a homeserver that has been configured not to federate, the UX doesn't provide any feedback?

**Comment by t3chguy** [comment]
If I invite a user from a different homeserver to a **room** that has been configured not to federate (via the m.federate creation flag) synapse sends a 403 and the ux provides no feedback

**Comment by t3chguy** [comment]
Oh wait that is what you said
/me just woke up

**Comment by lampholder** [comment]
Ha, actually my original message was unintentionally ambiguous - your comment was enlightening (I didn't actually know room-level non-federation was a thing).

**Comment by t3chguy** [comment]
Seems fixed now - 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/2403652/31202159-73b225a0-a959-11e7-8a57-13bf6131d99e.png)
