### ISSUE TITLE
Emoji picker keyboard navigation is uncomfortable

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-web#4737]
### Description

I'd like it to be fully keyboard-navigable. Instead only `Down` works which selects next emoji.

### Steps to reproduce

- type :a
- select emojis with `Down` which actually moves the selection to the right
- if you got past the desired item you'd like to press `Up` or `Left`
- the picker closes instead

I expect all four arrow keys to work for quicker selection of emojis. Purely accidentally did I discover that Shift+Tab allows to move the selection back. Also, according to #4721, Enter closes the picker and sends the message instead of just confirming the selection.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60.0.3112.78
- **OS**: Debian testing amd64
- **URL**: https://riot.im/develop/ 4b8764c-react-5752345b8082-js-bdb90b4b334f

**Comment by lukebarnard1** [comment]
I think this would require the emojis to appear as a grid, as is standard with most emoji pickers. There was discussion at one point to have them in a grid and have the `:shortname:` of each emoji appear as a tooltip.

**Comment by npny** [comment]
Found this annoying as well, especially coming over from Slack, as I instinctively reach for the left/right arrow keys, so I created a PR for it: https://github.com/matrix-org/matrix-react-sdk/pull/2966

Arguably, as mentioned, a full grid would be better, but looking at the code, that'd be a bit more involved, so in the meantime, simply allowing left/right arrow keys to work linearly should help make the typing of emojis slightly less painful. 🙂

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2966.
