### ISSUE TITLE
visual filter to hide/show the change name events

### ISSUE THREAD

**Issue by psaavedra** [vector-im/riot-web#4744]
### Description

Any time a user changes his name, a event message appears in all the rooms where he is in.
The result is a little bit annoying from my POV.

### Request
- A visual filter to hide/show the change name events
- A personal setting which actives or deactive the filter

### Related
- Discussion about this feature: https://riot.igalia.com/#/room/!DgvjtOljKujDBrxyHk:matrix.org/$15018464445545MtyqM:igalia.com

**Comment by t3chguy** [comment]
Feel free to implement: See https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/shouldHideEvent.js#L49 for an example
plus see UserSettings.js on how to add the checkbox (4 lines of code maybe?)

**Comment by t3chguy** [comment]
Done: https://github.com/matrix-org/matrix-react-sdk/pull/1272
