### ISSUE TITLE
By holding a modifier key pressed while cursor is on 'Send a message ...' field, you keep generating traffic. 

### ISSUE THREAD

**Issue by thanos-massias** [vector-im/riot-web#4755]
### Description

If user keeps holding a modifier key ( Shift, Ctrl, Caps Lock etc ) pressed while cursor is on 'Send a message ...' field, traffic is generated in the form of lots ( 2000+ request/min at 800+ KB/min ) of successive  .../typing/... requests in the form: _https://matrix.org/_matrix/client/r0/rooms/!HSaVVKVEAulrErpEFP%3Amatrix.org/typing/%40ThanosMassias127%3Amatrix.org?access_token=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDJmY2lkIHVzZXJfaWQgPSBAVGhhbm9zTWFzc2lhczEyNzptYXRyaXgub3JnCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gaEVGRnVTTHMqYmo3WFl0UwowMDJmc2lnbmF0dXJlIGbfSFVbrgjr0KWCzUBAR6EuA5M-gLLB6HwgvYvIKqVcCg_ 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/26714951/29066218-36f5a460-7c37-11e7-93d4-b5af111132d2.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 59, 60 ( Win ) and Firefox 54 ( Win ), 52 ( Lin )
- **OS**: Windows, Kali
- **URL**: https://riot.im/app/

**Comment by lukebarnard1** [comment]
That appears to be the old composer, which is being phased out in the next version of Riot. I can't reproduce this on `/develop`

**Comment by thanos-massias** [comment]
Thanks. Closing this then.
