### ISSUE TITLE
Scroll to bottom has regressed

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4758]
When inserting soft newlines, the composer doesn't follow the cursor anymore. Only seems to happen with multiple blocks in the composer.

**Comment by lampholder** [comment]
P2 because: I think this is annoying but probably comes up infrequently enough (and is easy enough to work around) that we can fix it after the new composer is in use in the wild.

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
