### ISSUE TITLE
History navigation via up/down key breaks on lines which end with emoticons e.g. :/

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4760]
In that the history navigation mysteriously gets lost toggling between :/ and 😕

**Comment by lukebarnard1** [comment]
So this happens for any uncompleted completion. If you have the plaintext `#riot` at the end of a message in history, you get exactly the same problem where you get trapped trying to complete `#riot`.

So one solution would be to not do completions when selecting history. However, you might decide to edit a message in history and expect completions to work.
