### ISSUE TITLE
History navigation via up/down breaks on multiline messages.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4761]
If you navigate up and down through a history which contains multiline messages, the cursor sometimes jumps to the bottommost line of the multiline message when navigating downwards, rather than stepping through line by line

**Comment by lampholder** [comment]
Is this only in the case when you're navigating _down_ to a multiline message?

**Comment by lukebarnard1** [comment]
Yep, and this is how the old composer worked

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890

**Comment by turt2live** [comment]
I don't think this is fixed for the moving down case?

**Comment by t3chguy** [comment]
@turt2live could you share a gif of an example of where it fails please?

**Comment by turt2live** [comment]
When I complained it failed, but now it's fixed. Probably part of one of the many slate fix PRs.
