### ISSUE TITLE
Completions when composing commands

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4762]
- [ ] `/invite @user` still doesn't work if tab-completing (likewise for `/ban` etc.) because:
     - [ ] You have to complete a user that is already in the room 
     - [ ] The user pill contains text == the display name of the user, not the user ID, so stripping the MD before executing the command in MD mode won't help.
- [ ] Very similar problem with `/join` for rooms - you get completions for rooms that are in your sync stream but that's it.

For now, we shall disallow tab-completing when entering a command (probably showing the visual bell (red flash) instead). But to do better we should consider providing other suggestions for /join and /invite etc. based on what the command is doing. For /invite, we may want to use the user directory for example. Likewise for rooms and /join.

Related issues:
 - commands should do clever tab-completion vector-im/riot-web#2426
 - when inviting users, you only get completions for users in the room already #vector-im/riot-web#4473

**Comment by lampholder** [comment]
P2ing because commands should support tab complete but we _can_ release without this as long as we don't have commands with pills _looking_ like they would work but actually failing.

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
