### ISSUE TITLE
Tracking issue: Myriad of bugs when pills include avatar initial (user avatar not set)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4772]
Because the initial that is used in the avatars place contributes to the length of the string within the decorated pill

**Comment by lukebarnard1** [comment]
Caused by https://github.com/facebook/draft-js/issues/1327

**Comment by lukebarnard1** [comment]
I've just thought of a workaround: using `::before` and `content` seems to fool draft-js into thinking there isn't any text in the avatar node. Fix incoming.

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
