### ISSUE TITLE
Captcha doesn't work

### ISSUE THREAD

**Issue by stemy2** [vector-im/riot-web#4778]
Hello,

I created an account for the web application, then i received the confirmation email. I clicked on «complete email verification», wich redirects me to page with a captcha. So i completed the captcha and it asked me to «Copy this code and paste it in the empty box below», so i copypasted the text and now, i have no idea of what to do. There is no validation button nor any other way to submit. What am i supposed to do ?

Thanks.

**Comment by lukebarnard1** [comment]
Hi @stemy2,

This looks like https://stackoverflow.com/questions/28505540/elusive-recaptcha-bug-copy-code-always-fails. Have you got some sort of extension that will disable javascript?
