### ISSUE TITLE
RTL text confuses MELS

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4779]
### Description

![image](https://user-images.githubusercontent.com/1190097/29215324-cd509b5e-7e67-11e7-8484-b40de98c8694.png)

Browser locale is en_US. Riot is set to en_US. Expanding the MELS is okay though:
![image](https://user-images.githubusercontent.com/1190097/29215352-f575bfe2-7e67-11e7-8e67-888bb2f2f943.png)

### Steps to reproduce

Uncertain. Page refresh did not resolve issue.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
That's an RTL issue, has been reported more generically 

Closing as superseded

**Comment by t3chguy** [comment]
Also, appears to be fixed : https://github.com/vector-im/riot-web/issues/2922#issuecomment-321244563

**Comment by turt2live** [comment]
@t3chguy Not fixed on /develop (07ca70fd4405-react-02217c8bd21e-js-92a75aaa0861). Please re-open this or direct me to the open ticket that this is a duplicate of.

**Comment by t3chguy** [comment]
@lukebarnard1 apparently not fixed

**Comment by richvdh** [comment]
this is something of a dup of https://github.com/vector-im/riot-web/issues/1712

**Comment by lukebarnard1** [comment]
Yep. Closing in favour of #1712.
