### ISSUE TITLE
Add links to download desktop and mobile Riot app to Riot welcome page

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4781]
At now Riot welcome page provide only links to room directory, Riot bot and popular Matrix rooms, so new Riot users don't see anything about Riot desktop and Android/iOS apps. 
Will be good to add short info about apps and download links.

**Comment by lampholder** [comment]
https://about.riot.im _does_ have these links, but the welcome page now doubles as a landing page for brand new users, so maybe it would be worth having a link to the desktop/mobile apps on the welcome page too.

**Comment by turt2live** [comment]
We fixed this in the rebrand
