### ISSUE TITLE
pager duty only fires after datacenters come back(!)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4785]

**Comment by lampholder** [comment]
SIGH.

**Comment by richvdh** [comment]
It's not entirely obvious how we fix this. The problem is that the prometheus alertmanager couldn't reach pagerduty to send out the alert. Obviously we need to monitor prometheus from outside the DC, but I don't think pagerduty does that natively, so we'll have to use something else.

**Comment by ara4n** [comment]
we subsequently added datacenter monitoring from latency.at (thanks to them!)
