### ISSUE TITLE
Can't close user info

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-web#4788]
### Description

User info can't be closed.

### Steps to reproduce

- click on a user in the userlist
- user info panel opens
- click the X on that panel to go to the full userlist

Nothing happens. I expect it to close and show the userlist. This is a regression.

### Version information

- **Platform**: web

- **Browser**: Chrome 61.0.3163.39
- **OS**: Debian testing amd64
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
`Uncaught TypeError: Cannot read property 'userId' of null`

**Comment by t3chguy** [comment]
This is probably the recent change to remove the duplicated code paths for user/member info

**Comment by t3chguy** [comment]
@ https://github.com/matrix-org/matrix-react-sdk/blob/02217c8bd21eb7c8ca46bd29a0b05a931acdffd9/src/components/structures/MatrixChat.js#L451

**Comment by uhoreg** [comment]
@t3chguy / @lukebarnard1 can this be closed now that #1294 is merged?  It seems to be working for me (on /staging)

**Comment by t3chguy** [comment]
I believe the revert should have fixed it. Closing until proven otherwise
