### ISSUE TITLE
Autocompleting inserts the pill in the wrong location in bulletted lists

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4792]
To reproduce:
1. use the rich text composer
1. turn on 'bullets'
1. enter a few lines of bulleted text
1. move your cursor to any line but the last one
1. autocomplete a username or room

The autocompleted pill will appear at the start of the last bullet. Also once that's happened you're firmly in glitchtown and you might also see duplicate pills :(

**Comment by lukebarnard1** [comment]
This is limited to specifically tab-completing (i.e. not "click to mention")

**Comment by lukebarnard1** [comment]
Turns out there was another bug in the calculation for calculating selection state from text offsets.
