### ISSUE TITLE
RTE doesn't let you autocomplete MXIDs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4794]
If a user in the room has no displayname and you type @foo<tab> or foo<tab> they don't come up at all.  This is a regression relative to pre-RTE

**Comment by lukebarnard1** [comment]
I can't reproduce this (tested by tab-completing `@alan.` in HQ).

**Comment by lukebarnard1** [comment]
(Related to this, autocompletion of userIds where a user has set their displayname has been disabled - https://github.com/vector-im/riot-web/issues/4495)

**Comment by ara4n** [comment]
Turns out this is specific to trying to autocomplete commands - e.g. `/op @Am<tab>` doesn't autocomplete to `/op @Amandine:matrix.org`.  I would expect the pre-RTE behaviour to work in this case (or for slash-commands to accept pills)

**Comment by pafcu** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4762 ?

**Comment by uhoreg** [comment]
closing as a dup of #4762, as it is is (temporary) intentional behaviour as documented in that issue:

> For now, we shall disallow tab-completing when entering a command (probably showing the visual bell (red flash) instead).
