### ISSUE TITLE
Browser back button doesn't work on register page after leaving homepage

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4801]
### Description

Reproduction steps are probably more clear than I can ever try to explain.

### Steps to reproduce

- Be logged out
- Go to #/home
- Click the Register button
- Click your browser's back button

Expectation: Navigate back to home page.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I think this is a dup of https://github.com/vector-im/riot-web/issues/4061 - I've modified the description of #4061 to be more inclusive.
