### ISSUE TITLE
Riot-web ignores image markgown tags ![](/path/to/image.jpeg)

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4806]
When I try to integrate image in message via https://riot.im/develop/# with markdown enabled with code like `![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)` - it shows like empty space instead of image.
In github this tag works well: ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png) - image showed normally.

**Comment by t3chguy** [comment]
Riot-web *does not permit* http:// urls for images, as this would be a privacy leak]

imagine me posting an image from my own webserver, every client that loads it would then leak their IP to me

instead the files must be mxc:// (uploaded to matrix network) and served over federation, so all that can be leaked is your Homeserver's Public IP Address.
