### ISSUE TITLE
Communities

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4807]

**Comment by t3chguy** [comment]
Epic indeed :D

**Comment by lampholder** [comment]
:D

I'm messing around with zenhub, which for some reason only lets you group github issues into an epic if you also create a (totally redundant?) github issue to represent that epic :(

**Comment by pafcu** [comment]
@lampholder Seems to be tracked at https://github.com/vector-im/riot-web/issues/2454. Could be closed to reduce the number of open issues?

**Comment by lukebarnard1** [comment]
I'm assuming @lampholder won't mind if we close this now.
