### ISSUE TITLE
Microphone devices are unreadable

### ISSUE THREAD

**Issue by AndrewJDR** [vector-im/riot-web#4815]
I'm using 3664a86722f6b2c96fe7d4d as an electron app on linux.

Inside the settings area, all the microphone devices look all wacky like this:
![screenshot at 2017-08-18 20 57 45](https://user-images.githubusercontent.com/1588857/29483285-e8376466-8457-11e7-85f6-f7c967440ea0.png)

**Comment by t3chguy** [comment]
I had initially made this dropdown a lot wider, someone must've shrunk it and your device names are too long, 

### Make dropdown happy to wrap child element text to multiple lines

**Comment by lampholder** [comment]
Is this really an electron-only issue?

**Comment by lampholder** [comment]
I'm going to bump this to major 'cause it does look pretty awful (and does make the microphone selection feature basically unusable) :(

**Comment by t3chguy** [comment]
Not electron specific

**Comment by aidalgol** [comment]
Regardless of what the menu width should be, for entries that are too long, do we want to wrap, or truncate and show the full name on (mouse) hover?

**Comment by ara4n** [comment]
fixed by @spantaleev  - thanks!
