### ISSUE TITLE
Add setting to disable emoji autocomplete suggestions

### ISSUE THREAD

**Issue by akien-mga** [vector-im/riot-web#4819]
### Description

I like using plain text emojis (e.g. `:)`) instead of PNG ones. Still, on riot.im/develop, an autocomplete box appears with emoji suggestions whenever one types `:`, which is visually distributing (at least to me) when trying to type ascii emojis.

I would like a setting to disable these emoji autocomplete suggestions. As a workaround, I've increased the autocomplete delay to 4000 ms (it seems it can't be fully disabled either), but I lose the autocomplete feature in cases where I would actually find it useful (usernames, commands).

### Steps to reproduce

- Type `:)`, see the confusing suggestions pop up

![spectacle c29371](https://user-images.githubusercontent.com/4701338/29485783-3002cd00-84d8-11e7-931c-6f7e440b541a.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox Night, build 20170818
- **OS**: Mageia 6 (Linux) x86_64
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
fixed by @turt2live - thanks!
