### ISSUE TITLE
don't count join/part msgs in 'jump to unread' calculation

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4820]

**Comment by lampholder** [comment]
@ara4n Do you mean - "Don't treat a join/part message as the 'first unread message'"? Or something else?

**Comment by ara4n** [comment]
i have no idea what i meant for this. the readmarker should show you where you last read up-to in a room, irrespective of any joins/parts.

**Comment by ara4n** [comment]
ah, it was talking about the total in the "you have 453 unread messages", where the total would confusingly include joins/parts, which aren't "unread messages". Given we no longer give a total there, it's not a problem.
