### ISSUE TITLE
If riot is narrow enough, such that 'Send a message (unecrypted)' wraps to a second line, the timeline doesn't fit the window.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4821]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15031763073271mbXTz:krtdex.com

**Comment by lampholder** [comment]
Could you/seequ_ provide a screenshot? Thanks :)

**Comment by turt2live** [comment]
@lampholder I wasn't able to reproduce this, but in theory @JaniM (seequ) would. Possibly a Firefox Nightly issue (I'm personally on Chrome 60, Windows 10).

**Comment by JaniM** [comment]
![screenshot_20170824_070604](https://user-images.githubusercontent.com/908675/29649123-cc241dd6-889a-11e7-8473-36221209bb56.png)

The scrollbar scrolls the entire right-hand side.

**Comment by lampholder** [comment]
Grim :(

**Comment by Nostradamos** [comment]
For `.mx_MessageComposer_input .public-DraftEditor-content` we have an `overflow: auto`, but not for the  `.DraftEditor-root`. Simply adding it solves the problem. I will look into it, and see if we can solve this by only adding it to `.DraftEditor-root` and removing it from `.mx_MessageComposer_input .public-DraftEditor-content`
