### ISSUE TITLE
rooms poking between sublists

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4822]
reported by Ruff_Wizard 
happens on W10 Firefox
![img](https://riot.ovh/_matrix/media/v1/download/matrix.org/djGxTdLQKiwWfAcZwyAxktwt)

**Comment by t3chguy** [comment]
happens on Desktop app (chromium) when you zoom in or out a tiny bit

**Comment by turt2live** [comment]
The room list is radically different
