### ISSUE TITLE
Does not honor x-www-browser

### ISSUE THREAD

**Issue by nblock** [vector-im/riot-web#4825]
### Description

I have firefox and chromium installed and I want riot-web to open links in firefox as it is my default browser.  x-www-browser reflects that.

### Steps to reproduce

- Click on a link
- Riot-web opens the link using chromium

I expect a link to be opened in the browser that x-www-browser points to:
```
$ update-alternatives --display x-www-browser
x-www-browser - auto mode
  link best version is /usr/bin/firefox
  link currently points to /usr/bin/firefox
  link x-www-browser is /usr/bin/x-www-browser
  slave x-www-browser.1.gz is /usr/share/man/man1/x-www-browser.1.gz
/usr/bin/chromium - priority 40
/usr/bin/firefox - priority 70
  slave x-www-browser.1.gz: /usr/share/man/man1/firefox.1.gz
```

### Version information

- **Platform**: desktop
- **OS**: Debian Stretch
- **Version**: 0.11.4
- via riot.im/packages/debian

**Comment by t3chguy** [comment]
I'm not sure we can do much about that, that's probably electron chromium preferring itself over x-www-browser

**Comment by uhoreg** [comment]
Hmm.  I somehow managed to coerce Riot Desktop to open links in Firefox in Debian (Jessie, at the time).  I thought I did it by changing x-www-browser.  What browser do you have set in your desktop environment?

**Comment by nblock** [comment]
I'm using i3 (which should not matter) and the BROWSER environment variable is set to firefox.

**Comment by dbkr** [comment]
We use electron's openExternal for this (https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options-callback) which in turn uses xdg-open, so check your xdg-open is configured correctly.

**Comment by nblock** [comment]
I just tried the following:
```
$ xdg-open https://google.com
$ xdg-open http://google.com 
```
Both commands spawn firefox.

My xdg user configuration is:
```
$ cat .config/mimeapps.list  
[Default Applications]
x-scheme-handler/magnet=userapp-transmission-gtk-5BGZUY.desktop

[Added Associations]
x-scheme-handler/magnet=userapp-transmission-gtk-5BGZUY.desktop;
application/pdf=kde4-okularApplication_pdf.desktop;
```

**Comment by nblock** [comment]
The latest update to 0.12.2 fixes this issue for me.

**Comment by t3chguy** [comment]
@nblock, weirdly there have been no changes to the electron side of the app in a few releases

**Comment by nblock** [comment]
@t3chguy strange, I guess its some issue on my side then. I made no xdg related changes on my side either.

**Comment by RocksteadyTC** [comment]
Why the fuck in 2021 am I experiencing this issue?
