### ISSUE TITLE
Displayname missing and continuations broken in HQ?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4827]
<img width="1084" alt="screen shot 2017-08-21 at 23 54 20" src="https://user-images.githubusercontent.com/1294269/29541466-1d316d30-86cc-11e7-9c39-8c818158ce0c.png">

**Comment by t3chguy** [comment]
Weirdly this is localized to that user
few lines above same room, on a client that sees the above:
![image](https://user-images.githubusercontent.com/2403652/29542079-8cd5328a-86d0-11e7-90ae-23d636a24aae.png)

**Comment by t3chguy** [comment]
oh it appears my client thinks that user is not the in the room, maybe the continuation stuff relies on the user being in the room

**Comment by t3chguy** [comment]
It seems matrix.org is being hammered, could have led to this

**Comment by t3chguy** [comment]
yeah actually this only happens on matrix.org, connected to my HS its fine :L

**Comment by t3chguy** [comment]
This was matrix.org grinding to a halt and a missing state, after clearing cache and reloading:
![image](https://user-images.githubusercontent.com/2403652/29542938-6d9d7f9e-86d5-11e7-924b-837fbd63fa8e.png)
