### ISSUE TITLE
prompt for inbound voip call was invisible when calling rick earlier

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4828]
it's possible that the z-index of the widget auxpanel sits higher than the prompt dialog and so occludes it?

**Comment by TheLastProject** [comment]
No clue, but I see the same thing consistently. Can no longer answer calls :(

**Comment by t3chguy** [comment]
@TheLastProject give more info
version, os etc

**Comment by TheLastProject** [comment]
Riot 0.12.1, Debian 9.

**Comment by t3chguy** [comment]
update to 0.12.2

**Comment by TheLastProject** [comment]
Okay, 0.12.2 literally just hit the Debian repositories and fixes the calling issue for me, was indeed in an encrypted room. Thanks.

**Comment by ara4n** [comment]
\o/
