### ISSUE TITLE
if you switch rooms and come back to a room, the last line of text is covered by the notification of someone else typing until a line of text is inserted in the log

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4829]

**Comment by lukebarnard1** [comment]
I can repro this in an e2e room but not in other rooms. Was this an e2e room?

> a line of text is inserted in the log

It would be interesting to know what the text was (unless you meant that a message was sent into the room?)

**Comment by lampholder** [comment]
Anecdotally I feel like I notice this all the time, not just in E2E rooms.

**Comment by lukebarnard1** [comment]
I'm noticing something similar now:
 - swap back and forth between two rooms
 - in one of them my scroll panel is no longer stuck to the bottom, but rather creeping slowly upwards

This can be prevented by scrolling to the very bottom in the creeping room.

**Comment by uhoreg** [comment]
maybe related to #3923 (seems to happen consistently in FF)

**Comment by ara4n** [comment]
I'm certainly not seeing this very often, if at all.  Going to un-releaseblock it.

**Comment by turt2live** [comment]
This happens *all the time* in e2e rooms for me, but I've never seen it in other rooms.

**Comment by turt2live** [comment]
Fixed by new typing notification behaviour
