### ISSUE TITLE
"Show Apps" button doesn't show dialog the second time you click on it.

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4834]
### Steps to reproduce

- Click on the "Show Apps" button at the bottom of the room view
- Close the dialog that pops up
- Notice that the "Show Apps" button is now highlighted 
![image](https://user-images.githubusercontent.com/1012976/29580997-e3070866-8745-11e7-9427-ae71e7a73472.png)
- Click on the "Show Apps" button again
- The button is now unhighlighted, but the dialog does not pop up
- Click on the "Show Apps" button again
- The dialog now shows up
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

I would expect the dialog to appear the second time the button is clicked.

Log: not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromium 60.0.3112.78
- **OS**: Debian
- **URL**: riot.im/staging 0.12.1-rc.1

**Comment by rxl881** [comment]
This button has been removed as part of a redesign of the way that apps/widgets are added. I'm assuming that this issue is no longer relevant.
