### ISSUE TITLE
Fullscreen custom widgets don't close on clicking the bottom right arrows.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4840]
Clicking:
![image](https://user-images.githubusercontent.com/1922197/29607397-013f9ea8-87e9-11e7-8e81-6dca8235c7f0.png)
expands the widget, but clicking it again doesn't shrink it (you can shrink it by pressing <kbd>Esc</kbd>).

Chrome, Windows 10

**Comment by turt2live** [comment]
@lampholder this was fixed

**Comment by lampholder** [comment]
Coool
