### ISSUE TITLE
Rich text editor erroneously forces RTL

### ISSUE THREAD

**Issue by florolf** [vector-im/riot-web#4854]
### Description

When certain text is present in a room's history, the riot-web rich text editor exhibits right-to-left editing behavior regardless of browser settings.

Only seems to happen in Chromium, Firefox works fine.

### Steps to reproduce

The room #rtlbreakage:matrix.org has been put into the state which triggers said behavior. The string "schreib mal frag und rein" seems to be sufficient to trigger the behavior. Some variations of it work, others don't.

Log: not sent

![2017-08-23-204030_591x358_scrot](https://user-images.githubusercontent.com/1835/29632449-54dfa49a-8843-11e7-9886-7696b9e0dacd.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chromium Version 60.0.3112.101 (Developer Build) (64-bit)
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
Duplicate of literally the previous issue... #4853

**Comment by t3chguy** [comment]
but since you provided more info, I'll close Dave's ;)

**Comment by florolf** [comment]
Oops, that wasn't there when I started typing this one up. Sorry.

**Comment by lampholder** [comment]
P1 at least until we know what's causing this and how likely people are to hit it :\

**Comment by florolf** [comment]
Seems there was something broken with my browser state. I recreated the browser profile from scratch and now everything seems to be fine. Probably not a Riot bug after all, sorry for the noise.
