### ISSUE TITLE
Can't get rid of mention without it going out of scrollback

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4856]
### Description

I sent a rageshake for this a couple days ago. The summary is that when mentioned in a room, the mention occasionally (fairly often) keeps coming back even after I've read it. The badge should not be returning, and I should not be hearing pings for it a second, third, fourth, etc time.

### Steps to reproduce

- Be mentioned in a room
- Read mention
- Be pinged a short while later, for the same message

Log: sent  

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
I haven't seen this for a week or so. @t3chguy iirc you were also having this issue? is it still happening?

**Comment by t3chguy** [comment]
I had it only that once after making fun of you

**Comment by turt2live** [comment]
I'm going to go ahead and close this as mysteriously fixed.
