### ISSUE TITLE
Domain-based config fails if invalid JSON returned

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4859]
No spinner or anything. In my case, nginx was set up to use a custom 404 page, so config.t2bot.io.json threw a 404 with HTML content, failing to be parsed and leading to a white screen

**Comment by Aksem** [comment]
I have the same problem. I tried package from github(0.12.3) and self-built from sources, but it doesn't work(just white screen and ` JSON.parse: unexpected character at line 1 column 1 of the JSON data` error in index.js:217:29). If I open index.html in browser(as local file) it works.

**Comment by lucas-dclrcq** [comment]
Same problem here, I have a blank screen when I try to open the integration menu and a 404 on config.mydomain.json. Any idea why ?

**Comment by turt2live** [comment]
This seems to have gotten fixed at some point (no longer seeing failures)

**Comment by TamTamDevTeam** [comment]
This bug just appear to me in 2020, any idea of how to fix or a workaround ?
