### ISSUE TITLE
RTE (macOS, Desktop, 0.12.1) breaks macOS keybindings

### ISSUE THREAD

**Issue by tfreedman** [vector-im/riot-web#4860]
### Description

Riot (macOS, Desktop, 0.12.1) breaks macOS keybindings.

Background: 
macOS allows you to change what functionality various keys have, by changing ~/Library/KeyBindings/DefaultKeyBinding.dict. This is different than traditional key remapping in that you aren't changing _every_ instance of the behavior of the physical keycap, but rather a specific function that was coincidentally assigned to that key. For example, you could remap 'Copy' from 
Command-C to Command-F if you wanted to - you haven't changed what the C and F keys do on their own, you've just removed the bonus functionality of Copy from one and moved it to the other. 

In Riot 0.11.4 (and all previous versions of Riot Desktop on macOS that I've used), this functionality works as expected, with all hotkey changes just working like any other program. In 0.12.1, keybindings are no longer loaded. This is typical of programs that use things like Java (or other non-native UI frameworks), but hasn't been a problem for me in any Electron-based apps before.

An example DefaultKeyBinding.dict file is this:

{
  "@\U007F" = deleteWordBackward:;
  "@\UF728" = deleteWordForward:;
}

On Riot 0.11.4, pressing Command-Delete in a text field containing (pipe represents cursor).

The quick brown fox jumps over the lazy dog|
would produce:
The quick brown fox jumps over the lazy |

On 0.12.1, It would delete the whole line.

**Comment by tfreedman** [comment]
Just noticed that this works as expected in /other/ text fields that aren't the main text box (e.g. typing a sentence into the 'filter room names' box). This suggests the problem is with the rich text editor, and not Riot.

**Comment by lukebarnard1** [comment]
This is draft-js assuming that the default OS key bindings haven't been changed.

**Comment by lampholder** [comment]
So draft-js doesn't honour the default OS key bindings? Can you file that upstream with them (if you haven't already)?

**Comment by lukebarnard1** [comment]
No, the exact opposite: draft-js  _expects_ the default OS key bindings to be used elsewhere. If a user changes their key bindings, native text inputs that are handled by the browser will function as expected, with those bindings taking effect. When using draft-js, none of the OS key-bindings are actually used because draft intercepts every key press and applies its own defaults.

draft-js is assuming that everyone on XYZ OS uses the default key bindings for text editing. This isn't platform specific.

**Comment by aaronraimist** [comment]
Fixed in the new composer
