### ISSUE TITLE
Pill mentions can break when editing trailing colon

### ISSUE THREAD

**Issue by akien-mga** [vector-im/riot-web#4864]
### Description

After inputting a pill mention (start typing user name and tab-complete it), resulting in e.g. 
![image](https://user-images.githubusercontent.com/4701338/29653286-7a12740c-88a9-11e7-8f13-ee1d5fd348c6.png)
if you attempt to edit the trailing colon to change it e.g. in a comma using backspace, you may end up breaking the pill and have instead:
![image](https://user-images.githubusercontent.com/4701338/29653197-2a623f0a-88a9-11e7-90d2-2a27a0eb7f5b.png)

I'll describe the exact steps to reproduce below. Note that it's only one breaking case, I've experienced similar (and more blocking, needing a refresh of Riot) issues in slightly different scenarios for which I haven't debugged the exact steps to reproduce yet. I may describe them later on here or in a new issue when I come to that.

### Steps to reproduce

1. Tab complete a username into a pill mention, e.g. type `red<TAB>` and get it completed as:
![image](https://user-images.githubusercontent.com/4701338/29653286-7a12740c-88a9-11e7-8f13-ee1d5fd348c6.png)
Note that the cursor is two columns after the pill, preceded by a colon and a space. 
2. Press backspace twice, to delete the colon and space and be right next to the pill:
![image](https://user-images.githubusercontent.com/4701338/29653348-b83329de-88a9-11e7-85e6-963f926c5cb0.png)
Note that the cursor is not *next* to the pill as expected, but inside it. (*)
3. Input a comma:
![image](https://user-images.githubusercontent.com/4701338/29653386-d8ec7716-88a9-11e7-80ca-73621e95aca8.png)
Note that the comma is placed *after* the cursor and the pill, and the cursor stays inside the pill as if expecting the user to append to the username.
4. Input a space, everything breaks:
![image](https://user-images.githubusercontent.com/4701338/29653423-00b599f8-88aa-11e7-819f-5add5e056141.png)

(*) One could expect that the cursor is inside the pill to allow appending to the username (e.g. to mention `@reduzio` instead of `@reduz`, but in all evidence it does not work, as the first added character is inputted after the pill without moving the cursor, and the second one breaks the pill:
2. (a). Input `i`:
![image](https://user-images.githubusercontent.com/4701338/29653496-56bd5ae8-88aa-11e7-9b23-2f17daf2a859.png)
2. (b). Input `o`:
![image](https://user-images.githubusercontent.com/4701338/29653518-66f9e368-88aa-11e7-9f54-8918a1089325.png)

Also worth mentioning, waiting long enough (5 s) between keystrokes allows to continue inputting stuff according to the 2. (a) logic.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox Nightly 20170823, Chrome 60.0.3112.90
- **OS**: Mageia 6 x86_64 (Linux), Windows 7
- **URL**: riot.im/develop as of 24.08.2017

**Comment by lampholder** [comment]
On Chrome 60.0.3112.78 on Ubuntu:
 - the cursor goes 'into the pill'
 - pressing <kbd>,</kbd> then <kbd>space</kbd> doesn't break the pill

On FF Nightly on Ubuntu:
 - the cursor does not go into the pill
 - pressing <kbd>,</kbd> then <kbd>space</kbd> doesn't break the pill

**Comment by akien-mga** [comment]
Thanks for testing, I'll have to recheck on Nightly - I wrote these steps to reproduce based on Chrome behaviour, and I remember having similar pill issues on Nightly, but maybe the exact behaviour differs.

**Comment by lukebarnard1** [comment]
This is probably because there's an "R" for the avatar of this person. Draft-js has a bug where it expects the text inside the pill to be exactly the text it decorates - https://github.com/vector-im/riot-web/issues/4772

**Comment by akien-mga** [comment]
I checked again on FF Nightly, and the bug described above is worse. With the exact same steps to reproduce, the final output is:
![image](https://user-images.githubusercontent.com/4701338/29677652-0ca50508-88fc-11e7-96e3-eac74245c8c9.png)

And the text editor is then completely broken:
- The weird `Rreduz „ Rreduz „` cannot be deleted
- Text can be inputted to the left of the existing text, but cannot be deleted either:
![spectacle x18988](https://user-images.githubusercontent.com/4701338/29677799-8f346e8c-88fc-11e7-8300-8f32175283bc.png)
- Only a reload of the browser tab can fix it in my tests, leading to a delete-able `Help!! Rreduz ,, ` (notice the absence of the second instance of this pill leftover).

**Comment by lukebarnard1** [comment]
A workaround for this could be to not have any text in the member avatar in pills. I'm not sure what we'd put there instead. Maybe no avatar? Maybe a placeholder image?

**Comment by eternaleye** [comment]
Could the issue be sidestepped by using an SVG "image" containing the text?

**Comment by ara4n** [comment]
This bug is super-annoying (as per #5002 - @turt2live thanks for spotting the dup :)
I suspect eternaleye's solution is a fine workaround: i.e. rather than putting a `<span>R</span>` in the avatar, we can put a `<svg><text>R</text></svg>` instead, and hopefully Draft.js won't overenthusiastically try to parse text out of the SVG.

**Comment by eternaleye** [comment]
@ara4n: Even if it does, there's always `<img src="data:..."></img>` as a fallback option. That'd definitely behave more like an actual avatar.

**Comment by grahamperrin** [comment]
Breakage with different symptoms: 

https://vimeo.com/234174685

> **multiple issues affecting Riot**
> 
> … around 01:18 on the timeline: …

**Comment by lukebarnard1** [comment]
>`<svg><text>R</text></svg>`

SGTM

**Comment by lukebarnard1** [comment]
OK so it turns out that the SVG `<text/>` is still a text node in the DOM, it's not just rasterized once.

**Comment by eternaleye** [comment]
@lukebarnard1: What about an `<img>` with a `data:` URI?

**Comment by lukebarnard1** [comment]
@eternaleye this would strictly be an option. But we do lose the CSS, which means themeing won't work.

**Comment by eternaleye** [comment]
@lukebarnard1: I thought the SVG was just for the letter itself, though, not even the background? At that point, we don't "lose the CSS" any more than we do when a user has an avatar set...

**Comment by lukebarnard1** [comment]
By CSS I meant we lose the ability to apply a different colour to the initial through the existing theme mechanism.

**Comment by alex-mayorga** [comment]
¡Hola @ara4n!

This just bite me yet again on https://riot.im/develop/ and annoyed me enough to comment.

Any hopes for a fix or workaround to this bugger?

¡Gracias!

**Comment by rschulman** [comment]
This bit me just now on Firefox 57.0 (Quantum) as well. So just a +1.

**Comment by stormi** [comment]
+1 too

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
