### ISSUE TITLE
Broken VOIP on 0.12.1

### ISSUE THREAD

**Issue by dva-re** [vector-im/riot-web#4865]
### Description

On new desktop client after update - voip calls not work.
I was tested Mac <-> Android, Windows <-> Android, Mac <-> iOS. Connection to the participant is not established.

On incoming call in desktop client there are not 'incoming call badge' at all.

On old version it work properly. 
Current workaround - downgrade desktop client to 0.11.4 version. 

- **Platform**: desktop
- **OS**: Windows, macOS
- **Version**: 0.12.1
- **Encryption in room**: enabled

**Comment by blobity** [comment]
Having the same issue here. 

When I create an Encrypted-enabled chatroom and attempt to make a VOIP call, the recipient does not have an incoming call badge. At times the recipient wont even hear ringing, but the chatroom displays the senders attempt to make a call.

However, if the room does NOT have encryption enabled, I am able to make VOIP calls and the recipient gets an incoming call badge as per normal.

It seems that the issue only began to occur during once I updated to 0.12.1. 
It has worked flawlessly on the older version (0.11.4).

That is what I have found out so far (for me).

Hope devs can fix it soon.

**Comment by dbkr** [comment]
Yep, this is indeed specific to e2e rooms. There is another symptom in that the text of the message doesn't appear in the timeline for me until I move my cursor over the window (but the notification badge does appear on the room tile).

Same happens on web, so it's not desktop-specific.

**Comment by dbkr** [comment]
Also happens with both Chrome and Firefox (tested in case it was Chrome's new behaviour of limiting js execution when the tab is in the background).

**Comment by strixaluco** [comment]
> There is another symptom in that the text of the message doesn't appear in the timeline for me until I move my cursor over the window (but the notification badge does appear on the room tile).

Confirming the same issue in e2e rooms on Riot Desktop 0.12.1 @ Debian Stretch
