### ISSUE TITLE
expose power level setting for adding widgets to a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4866]

**Comment by lampholder** [comment]
You just mean in the PERMISSIONS section of the room admin settings, right?

**Comment by lampholder** [comment]
@ara4n do you mean expose it as a configurable option, or just render it in the list with a fixed power level of 100?

**Comment by turt2live** [comment]
+1 to making it configurable. There's plenty of rooms I'm in that have a dummy account holding PL100 and the rest of us have PL50 so we can be kicked out, and I'd rather not have to do some API voodoo every time I want PL50 to add/edit widgets
