### ISSUE TITLE
Tab-completion doesn't work with cyrillic nicknames.

### ISSUE THREAD

**Issue by Ai-rin** [vector-im/riot-web#4868]
Tested on riot.im/develop
Chromium Version 60.0.3112.101 (openSUSE Build) (64-bit)

**Comment by rkfg** [comment]
At least you can mention using the beginning of MXID, it completes successfully to the nickname. But it's absolutely necessary to be able to type and complete just the nickname.

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890 (i think - please confirm)
