### ISSUE TITLE
Language Dropdown shouldn't directly reload on new Guest Accounts which don't have a password!

### ISSUE THREAD

**Issue by MTRNord** [vector-im/riot-web#4870]
The language Picker in the settings reloads the page on choosing language. If no password is set the user will loose his name :( A popup or so is needed

Steps to reproduce:
1. Logout and go into the "GuestView"
2. Click the settings button -> Riot asks name -> Warnings of missing passwords appear at top
3. Choose language -> Riot reloads -> User lost Username forever

**Comment by MTRNord** [comment]
My bad that isn't a thing :I I just didn't pay enough attention to my screen

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/29671288-0971974a-88e1-11e7-8cda-88efeb394814.png)
