### ISSUE TITLE
quoting a message with a URL preview includes the URL preview text in the quote

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4874]
I think this is a regression?

### Steps to reproduce

- Find a message with a URL preview
- Click on the "..." menu, and select quote
![image](https://user-images.githubusercontent.com/1012976/29688209-ea0d4564-88ec-11e7-8d7d-09106bc3e933.png)
- see that the quote includes the URL preview
![image](https://user-images.githubusercontent.com/1012976/29691848-ec400174-88fa-11e7-87d1-90cd03dc1c51.png)

Describe how what happens differs from what you expected.

The quote should only include the message text, not the URL preview.

Log: not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Revolt (WebKit GTK+)
- **OS**: Debian
- **URL**: riot.im/staging (0.12.2)

**Comment by lampholder** [comment]
Yes, this is a regression :(

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
