### ISSUE TITLE
Custom widgets should be available even without a ScalarClient

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4882]
to create

**Comment by turt2live** [comment]
Some of the other clientside widgets would also be nice. Ie: youtube. They shouldn't need a backend to add this.

**Comment by t3chguy** [comment]
@turt2live the issue with that is I think it has a scalar middleware to load youtube to better fit the widget or something like that

**Comment by turt2live** [comment]
Youtube clips have a special embed URL. Maybe scalar adds some redirect stuff?

**Comment by t3chguy** [comment]
I think it adds the button in the bottom right for instance
