### ISSUE TITLE
[Feature Request] Custom Room Settings

### ISSUE THREAD

**Issue by rodneyrod** [vector-im/riot-web#4884]
There's currently no option for users to group rooms together in their own 'Room Settings' group e.g. Low Priority, Favourites etc.

I would like to request some way that users can create, edit and remove their own custom 'Room Settings' groups.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/1373

You can already create custom tags using the API and riot will honour them, just has no UI for doing it yet.
