### ISSUE TITLE
'Leave room' and 'save' too close together

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4889]
### Description

From a user: "I almost left the room instead of saving it".

### Steps to reproduce

- Open room settings
- Find out that the leave room and save button are the same color, and close together

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: Internal. Based on v0.12.2

**Comment by lampholder** [comment]
In terms of pixels they're quite far apart:
![image](https://user-images.githubusercontent.com/1922197/29812690-572eade4-8c9f-11e7-9d72-31be11f02a41.png)
So I'd be surprised if we were suffering from people _physically_ misclicking on exit when they meant to save.

However, they are both bold buttons in the same rough screen region, so I suspect people might not see the difference between the two buttons when trying to progress through the UX in a hurry.

**Comment by turt2live** [comment]
Making the leave button a different color could help, or the epic #5476

**Comment by turt2live** [comment]
Not anymore!
