### ISSUE TITLE
Room read state doesn't sync on one computer

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#4892]
On one computer, for some rooms, the read state is often not updated, i.e.:
* Scroll to the bottom or click the mark all read cross.
* Line above unread messages disappears.
* Room name in the left column still stays bold.
* ~Read state is not synced to other devices.~ This has changed somewhat with v0.12.2, see comment below.
* In some rooms like #riot or #offtopic, it works sometimes, in other rooms like #books, I think it works always, in other rooms like #matrix-news, it never works.

This is only the case on one computer (current FF, Arch Linux). On two laptops that use the same Riot Web installation (self-hosted), it works flawlessly (both current FF, one Arch Linux, one Windows).

**What I tried (didn't help):**
* Shift-Reload
* Clear cache (button in Riot, and browser cache)
* Log out and in again.
* Update to Riot Web 0.12.2 (saw it on 0.11.4, too).

**What I noticed in the console log:**
When it works, I see a line "Persisting sync data up to <blah>" in the log. When it doesn't work, no such line shows up although I have scrolled to the end of the timeline, so it seems that the corresponding function is never called in this case.

I'll send a rageshake once I have submitted the issue and mention the issue there.

This is probably an edge case as I've never heard of anybody else seeing this problem. I hope you can give me tips where I could look to be able to solve the problem.

I can help hunting down the issue by installing some dev version on my server (I'm the only one using it, anyway) as long as I can get a ready-made .tar.gz.

**Comment by zzottel** [comment]
New observations:
* When the last event in a room is a leave/join event, it seems to work, but not in other cases.
* Different from what I wrote above, read markers seem to be synced to other devices now, i.e. I'm not prompted to jump to unread messages that I actually read on this computer, like I was with v0.11.4. Only the room title stays bold on other devices and then is reset (and synced back to this device) when I open the room on another device, with no new messages indicated.

**Comment by turt2live** [comment]
I've had this happen in a few rooms due to a homeserver missing state:

1. Invite someone to a room
2. Invite a bot to a room
3. Chat with the person + bot at least once each
4. Kick the bot
5. Ensure the bot's homeserver does *not* see the kick event (root of the issue)
6. Interact with the bot where the bot responds
7. Your read marker will always be above the bot's messages.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/1190097/30069858-0afc73ae-921f-11e7-914e-a458df63de7d.png)

**Comment by zzottel** [comment]
My problem is fixed in Riot 0.12.3, everything works as it should again, thanks a lot!

Still keeping the bug open for @turt2live 's problem which seems to be a different one.

**Comment by lukebarnard1** [comment]
Closing this as @turt2live's issue is separate and a bit of an edge case (ensuring the other homeserver doesn't see a kick).
