### ISSUE TITLE
reCAPTCHA doesn't work on Riot/Desktop, so forces you to sign up on Riot/Web

### ISSUE THREAD

**Issue by ssolidus** [vector-im/riot-web#4893]
### Description

When trying to create an account, the captcha appears as `[Object object]`

### Steps to reproduce

- Open Riot desktop client
- Attempt to create an account
- Should produce captcha, instead comes up as `[Object object]` (see screenshot below)

### Log/Screenshots: 
Log not available

![image](https://user-images.githubusercontent.com/14216632/29737798-d5f7bfa2-8a57-11e7-9a76-4bfdfe9ef998.png)

### Version information
- **Platform**: Desktop
- **OS**: Windows 7 x64
- **Version**: 0.12.2

**Comment by t3chguy** [comment]
What it's trying to say is that robot detection is not available on desktop but obviously failing
I'll take a look

**Comment by t3chguy** [comment]
The captcha lib doesn't work when the protocol is file:// as it is in Electron

**Comment by t3chguy** [comment]
Broken error fixed here: https://github.com/matrix-org/matrix-react-sdk/pull/1340

**Comment by t3chguy** [comment]
I will leave this issue open to track the greater issue

**Comment by Ashaman-** [comment]
Additionally, attempts to sign up with captcha enabled on a forked version of riot-web which has a different default homeserver and identity server set are met with directions to register on the web client at riot.im. This should be a setting defined in config.json IMO.

**Comment by aaronraimist** [comment]
Wonder if reCAPTCHA v3 works better here 
https://webmasters.googleblog.com/2018/10/introducing-recaptcha-v3-new-way-to.html

**Comment by jryans** [comment]
It looks like captchas now work in Riot desktop, so I have [made a change](https://github.com/matrix-org/matrix-react-sdk/pull/2663) to allow them there. Hopefully that will continue to be true in production usage on all OSes.
