### ISSUE TITLE
Command line option for starting in/setting theme

### ISSUE THREAD

**Issue by gsantner** [vector-im/riot-web#4896]
### Description
Currently the only way to set the light/dark theme is by going into settings. it would be great to have an command line option, that does set the theme of the current running instance, or if nothing running of a new one. 
(Sidenote: I would like to wrap this then in a custom script, that makes riot startup in light mode outdoor and at day, otherwise in the dark theme mode.)

### Steps to reproduce
Currently the only way to update this is by going into settings

### Version information

- **Platform**: desktop
- **OS**: Arch x64
- **Version**: 0.9.10

**Comment by t3chguy** [comment]
this is non-trivial

The theme comes down over the wire, from your Synced account_data
the main electron process can't directly interact with the rendering process
++ how would a conflict be handled in such a case?

(Start flag says DARK, but your synced data says LIGHT)

**Comment by gsantner** [comment]
Okay, but the settings option too does nothing different than telling the new value to the sync network? Why is this synced at all, thats client specific, not account specific. This way I cannot have dark mode on desktop and light mode at laptop

**Comment by t3chguy** [comment]
Design choice I guess? this is from way before I even knew about the project

**Comment by gsantner** [comment]
Do you think thats still a good design choice? (I know its not done by you / up to you to decide)

**Comment by t3chguy** [comment]
if I had to pick between synced/not-synced I'd personally choose synced
there is a future project that will allow you to override synced settings with not-synced ones
but that's a while off yet

**Comment by lampholder** [comment]
As @t3chguy says, there are reasons why this is the case, so if someone were to tackle this they should make sure to validate their approach widely before doing so :)

**Comment by t3chguy** [comment]
Be that as it may, caching the last seen theme and using that for the spinning wheel of doom whilst syncing as you open the client would be sane, what do you think @lampholder

**Comment by lampholder** [comment]
That seems sane if it's a single user logging in/out of Riot on that machine (which is by far and away the most likely case).

Still, I'm not sure it adds all that much value :\

**Comment by gsantner** [comment]
Closing some old stuff nobody seems to care about
