### ISSUE TITLE
Desktop client: Paste files into chat window as a way to upload

### ISSUE THREAD

**Issue by Edszx** [vector-im/riot-web#4898]
### Description

It would be very useful to be able to go to the windows explorer, "CTRL + C" a text file, word document, jpg image, etc, and have them uploaded on the current chatroom by just pressing "CTRL + V" when the window is in focus, currently, we can only upload "clipboard images" that way, not even jpg or png files, just "image data" that is on the clipboard, like when you take a screenshot with the "PrntScrn" key, but if i copy an image file from windows explorer and try to paste it in the desktop client, nothing happens.

### Version information

- **Platform**: Desktop
- **OS**: Windows 7 x64
- **Version**: 0.12.2

**Comment by t3chguy** [comment]
I'm not sure how feasible this is,
re copying an image file, open the file then right click copy the image itself
or you could drag and drop it into riot

**Comment by Edszx** [comment]
Thank you for mentioning those alternatives, i'm already aware of them, but changing windows constantly, moving them and drag and dropping files really dulls the flow of work in the program, specially on lower resolutions, i'm just making the suggestion because instant pasting/uploading of files would really help with the efficiency of my team, because we are constantly uploading pictures and small files.

**Comment by t3chguy** [comment]
@Edszx do you know of any webapp that has this functionality out of interest?

**Comment by t3chguy** [comment]
As far as I can tell, the HTML spec doesn't allow for it
https://stackoverflow.com/a/8710277
and pasting a file can only lead to the filename being read (not even the full path)

**Comment by Edszx** [comment]
I don't know of any webapp with this functionality, sadly, if it's not supported then nothing we can do about it, thanks for your time!

**Comment by StefanBrand** [comment]
I know one: [Discourse](https://meta.discourse.org/). The forum software allows for image pasting. 

E.g. <kbd>Ctrl</kbd> + <kbd>c</kbd> a `jpg` in Windows Explorer, start a new post in Discourse, and then <kbd>Ctrl</kbd> + <kbd>v</kbd> -> Image is uploaded.

**Comment by t3chguy** [comment]
@StefanBrand I tried and it does not paste the image in.

**Comment by t3chguy** [comment]
If I open it in photos and then Copy and Paste it does work though, just like Riot and Github and more

**Comment by StefanBrand** [comment]
Can't be... I'm on Firefox 55.0.3.

**Comment by t3chguy** [comment]
I'm on Chrome 60

**Comment by StefanBrand** [comment]
It even works in Riot this way, though.

**Comment by t3chguy** [comment]
I just tried on 55.0.3 FF Freshly installed and also did not work, neither Discourse nor Riot

**Comment by StefanBrand** [comment]
What's your OS?

**Comment by t3chguy** [comment]
Windows 10 v1703

**Comment by StefanBrand** [comment]
![screenshot-2017-9-17 riot](https://user-images.githubusercontent.com/8948865/30524298-5fb8d12c-9bf1-11e7-9d09-1aef2fa0da4f.png)

That comes up after I have copy-pasted the file from Windows Explorer. 

My Windows version is 10.0.15063

**Comment by t3chguy** [comment]
You're either magic or Windows hates me

**Comment by makedir** [comment]
Why are Windows image clipboard contents always uploaded as PNG? Please give option to change this to JPEG with compression factor.

**Comment by makedir** [comment]
Why are Windows image clipboard contents always uploaded as PNG if you insert them via ctrl+v? Please give option to change this to JPEG with compression factor.

**Comment by aaronraimist** [comment]
I don't use Windows but probably because Windows takes screenshots as a PNG. You should probably use some other utility to convert them if you want a JPEG.

**Comment by makedir** [comment]
That doesnt make any sense and is the typical being ignorant solution to everything for devs. If you use clip tools in Windows to share stuff into client, it is just retarded to post them as 2-4MB sized pictures everytime instead of using proper JPEG or other compression.

**Comment by ara4n** [comment]
@aaronraimist yup, we fixed it with the move to slate.

@makedir: i would be pretty pissed off if i wanted to send someone a PNG and the app randomly reencoded it to be a JPG. For instance, any transparency you have (like on macOS screenshots) would get lost. Feel free to file a feature request to optionally JPEG everything before upload to save bandwidth, but i doubt it will get prioritised very high (especially if you call us retarded).

**Comment by makedir** [comment]
@ara4n THATS WHY AS A GOOD APP DEVELOPER YOU GIVE OPTIONS. OPTIONS. AND DONT FORCE ANYTHING. There just has to be a simple PNG/JPEG slider in the frame when you ctrl+c into the client...

**Comment by ara4n** [comment]
as i said, if you want an optional feature to recompress images at upload (whether that is by pasting them or uploading them or whatever) go file a request rather than trying to hijack a bug about the clipboard being broken.
