### ISSUE TITLE
Broken video thumbnail

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4899]
FF55 Fedora, all sorts of nasty: ![](https://riot.ovh/_matrix/media/v1/download/matrix.org/zlSCXZVmiYeUKfrDqrFOFYva)

**Comment by t3chguy** [comment]
`Video loading stopped. Video playback aborted due to a network error. Video can't be played because the file is corrupt. Video format or MIME type is not supported. No video with supported format and MIME type found. Video playback aborted due to an unknown error.`

**Comment by saad440** [comment]
Checked in Firefox with a new profile to make sure it wasn't an addon causing issues. Same issue.
Checked in Chrome, no issue like this.
So I suppose it's not a network issue as part of the error message suggests.

**Comment by saad440** [comment]
Ok, looks like a false alarm.
I went to the web inspector and found this

![ff55-riot-video-webinspector](https://user-images.githubusercontent.com/10145377/29749298-b13d3a58-8b41-11e7-8e7e-76d680424e77.png)

Opened the video link (the direct link to the file) in a new tab and it appeared like this, even though it was actually playing.
![ff55-video-directloading](https://user-images.githubusercontent.com/10145377/29749300-c4331060-8b41-11e7-9fe7-565453c72e5e.png)

So it's either my particular config or a bug in Firefox itself. I'll see what I can find out about it.

**Comment by saad440** [comment]
Sorry, false alarm.
I have tracked down the issue to the package mozilla-arc-theme that I had gotten installed from the Korora repo. Disabling it in the appearance section fixed it.
