### ISSUE TITLE
Automatically continue lists on shift+enter (when markdown is enabled)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4905]
### Description

When starting a list (unordered or ordered) the next bullet/number should automatically appear when hitting shift+enter. 

Example:
```
1. words here <shift+enter>
2. <cursor>
```

Hitting shift+enter after not entering text on the bullet point should clear it (ie: `2. ` would become a blank line in the above example).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
Most rich text editors would use Enter instead of Shift, Enter here. @turt2live could you explain why you'd prefer what you've suggested.

**Comment by turt2live** [comment]
Because Enter is Send.

**Comment by lampholder** [comment]
Modified title for clarity - then MD is _not_ enabled the composer already behaves like every other WYSIWYG editor.

We might want to consider how we handle multiline messages more widely - shift-enter continuing the markdown list formatting seems fairly inutitive to me, but I can also see it surprising some people.

**Comment by ara4n** [comment]
i agree with @lukebarnard1 that lists are special, and hitting enter should start a new bullet rather than send a message. i for one certainly use shift-enter within a list item quite often.  so i'm afraid i don't think this one is ever going to get fixed.
