### ISSUE TITLE
Use a toaster library for unobtrusive notices

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4908]
Something like https://github.com/tomchentw/react-toastr which allows for timed notices, static, and custom animations. Would be useful for things like incoming voip calls, invites, and generic success messages

**Comment by turt2live** [comment]
The alternative would be to use dialogs, but that can be clunky and intrusive in some cases.

**Comment by lampholder** [comment]
I would dearly love a better way of that app itself interacting with users. Right now we have the nag bar, which has a few problems (primarily being easy to miss and hard to distinguish one nag from a different nag).

I think there are a couple of less-ideal aspects of toast:
- they're short lived, so not a good solution for an invite (though in this regard more suited to something like a inbound call)
- they obscure whatever they pop infront of, for however long they stick around for (and if you try and click any `dismiss` UX you risk mistiming and the click passing through to whatever's behind)

They might still be the best solution - something to consider.

**Comment by turt2live** [comment]
The duration aspect can be resolved by not specifying a timeout, so it stays on screen until the user dismisses or responds to it. 

Maintaining the top right convention, the toaster should only cover the tabs for the right hand menu and possible the filter room members field, both are relatively infrequent to be using where a toaster would interfere. Besides, the toaster can be dismissed and the stuff under it can be interacted with again.

**Comment by t3chguy** [comment]
We have some toasts now

**Comment by turt2live** [comment]
Yea, and we have other issues to track where we want to use them (and a designer who can make better decisions than those of us who recommend throwing libraries at the problem). Closing as fixed enough.
