### ISSUE TITLE
Message appears unencrypted while in flight

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4912]
### Description

![image](https://user-images.githubusercontent.com/1190097/29755918-486f2b60-8b5c-11e7-8085-f3c8f052665f.png)

This is a bit jarring and has had me worried a couple times. This feels like a regression, but I can't be certain on that.

### Steps to reproduce

- Send a message with unknown devices in the room (or something that will cause significant delay in sending)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Very jarring and unnerving.

**Comment by t3chguy** [comment]
This appears to only happen sometimes, I've reproduced on the first message since a refresh pretty consistently though

**Comment by turt2live** [comment]
Note this also happens if the message gets caught by the unknown device prompt: https://github.com/vector-im/riot-web/issues/6735

**Comment by t3chguy** [comment]
@turt2live how do you feel about 
![image](https://user-images.githubusercontent.com/2403652/41318919-ed915ffa-6e91-11e8-9d9b-f98060cd219d.png)

**Comment by turt2live** [comment]
why not a lock icon?

**Comment by t3chguy** [comment]
Because at that point it is still encrypting. It could fail so would be misleading imo

**Comment by t3chguy** [comment]
Toml has suggested a faded *locked* padlock to match the faded text
