### ISSUE TITLE
Slashes get automatically converted in grafana url field

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4914]
### Description

Typing `//` in the url field ends up being `%2F%2F` automatically.

### Steps to reproduce

![grafana gif](https://user-images.githubusercontent.com/1190097/29758559-c3a1d11a-8b71-11e7-97b9-b78e263fabdd.gif)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
The workaround is to paste the URL in.

At the moment the widget adding interfaces, despite looking the same, all seem to have slightly different implementations/behaviours. Is this intentional? What could we do to ensure a more homogenous experience across widgets?

**Comment by turt2live** [comment]
Pasting does work, at the time of reporting this it didn't. Typing is still broken though :/

+1 to making it consistent. A couple people I support have complained that it is too annoying because they end up having to actually read the dialogue. For something as minor as a widget, it shouldn't require thinking to add, edit, or delete a widget.

**Comment by rxl881** [comment]
Thanks for the great bug report @turt2live. Yup, plan is definitely to make this much more simple / consistent / reusable ... for the record, this will come with the "dynamic", "manifest-backed" widget stuff that is being worked on at the moment. However, as that could be a little way off being deployed, I'll fix this here, now.

**Comment by rxl881** [comment]
Should be done, pending review on https://github.com/matrix-org/scalar/pull/253

**Comment by turt2live** [comment]
I can't see if https://github.com/matrix-org/scalar/pull/253 has been merged (repo not public is my guess). Has this been merged @rxl881 ? If so, it's still broken on /develop

**Comment by rxl881** [comment]
Thanks for prodding me on this on @turt2live -- Sorry, nope it didn't get merged in the end. The main reason being that all of the scalar-web widget component stuff needs splitting in to consistent and reusable components and fixing properly (across all widgets).

Assuming no other distractions, I'm going to make fixing widget creation / editing my top priority for today (Nov 29th ;) ). I'll aim to get an update on this issue a little later today.

**Comment by rxl881** [comment]
Quick update ... sorry, I've been distracted working on widget postMessage API stuff today. I will get to this asap. Hopefully this week.

**Comment by rxl881** [comment]
I've modified and sent https://github.com/matrix-org/scalar/pull/253 back for review. Fingers crossed we should be able to get this out to /develop tomorrow. Sorry for the delay.

**Comment by rxl881** [comment]
This should now be fixed and deployed on /develop.
