### ISSUE TITLE
hard to join #_gimpnet_#gtk+:matrix.org

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4924]
according to @sadiq:matrix.org, https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15039243772704418vnkkh:matrix.org

EDIT:
> one more thing: The Gtk channel from Gimpnet isn't an invite only channel. But it seems like only users with invitation can join (I was asked to report that here, I don't know if it is already fixed)

**Comment by t3chguy** [comment]
@pksadiq

**Comment by lukebarnard1** [comment]
@t3chguy, it's not clear what the issue is here. Please can you elaborate (I'd prefer additional  >quoting along with `matrix.to` links)

**Comment by t3chguy** [comment]
I'm also not sure I can reproduce it anymore, @pksadiq any chance for comment?

**Comment by pksadiq** [comment]
When a new user tries to join gtk+ channel on GIMPNet via RIOT, he/she gets kicked saying it is an invite only channel. Once the user gets invitation, he/she seems to be always permitted to join (So I can't know if the issue still exists).

This may be tested by simply clicking https://riot.im/app/#/room/#_gimpnet_#gtk+:matrix.org and trying to join.

**Comment by lukebarnard1** [comment]
Ah. This is not a Riot issue, it's an issue with the IRC bridge which thinks that gtk+ is invite only. Please take the issue there (http://github.com/matrix-org/matrix-appservice-irc (although we're not maintaining bridges at the moment).
