### ISSUE TITLE
Consider making pill mentions function as a visual style only

### ISSUE THREAD

**Issue by smichel17** [vector-im/riot-web#4930]
### Description

I love the way pill mentions look. I hate the way they function. I'd love if they behaved just like text. Specifically, I don't like:

### 1. Unintuitive behavior

**Steps to reproduce**

- Type someone's name and hit tab
    - Pill mention is formed
- Press backspace 4 times

**Result (after each backspace):**

1. **Expected**: Deletes the space following the mention
    - **Actual**: as expected
2. **E**: Deletes the colon following the mention
    - **A**: as expected
3. **E**: Deletes the last character in the person's name *edit: and pill styling disappears*
    - **A**: Nothing happens
4. **E**: Deletes the second to last character in the person's name
    - **A**: Deletes the entire name/pill

### 2. Inconsistent behavior

**Steps to reproduce**

- Type someone's name and hit tab
    - Pill mention is formed
- Press the left arrow twice to move the cursor to the end of the card
- Press backspace

**Expected result:** Consistent with backspace 3, above (either my preference or the current behavior)
**Actual result:** Deletes the entire name/pill

### 3. Broken home and end keys

**Steps to reproduce**

- Start typing someone's name and hit tab
   - Pill is formed
- Type "extra text"
- Press home key
- Press end key

**Expected result:** cursor jumps to end of the line, following "text"
**Actual result:** cursor jumps to the end of the mention

I tried to figure out the specific rules that follow home and end. It seems to be this:

- If the cursor is within a mention, it will always jump to the start/end of the mention.
    - Putting the cursor at the end of a mention (after the last character) counts as inside the mention. **Thus, the end key alone is not capable of freeing the cursor from a mention.**
- If the cursor is not within a mention, it will always jump to the start/end of the line.
    - Putting the cursor at the start of a mention does *not* count as inside the mention.
    *Except: if the message begins with a mention, putting the cursor at the start of the line counts as a mention.* **Thus, no combination of home and end keys is capable of freeing the cursor from the first mention.**

### Version information
- **Platform**: web
- **Browser**: Chromium Version 60.0.3112.101 (Developer Build) Fedora Project (64-bit)
- **OS**: Fedora
- **URL**: https://riot.im/develop/#/room/#snowdrift:matrix.org (or any room)

Related: #4640

**Comment by lukebarnard1** [comment]
We're not going to allow arbitrary editing of the text within a pill, it's an abuse vector we'd like to limit. It's tractable to consider that if the person has a second name in their display name, we can allow for that to be deleted.

**Comment by smichel17** [comment]
I'm sorry, I seem to have forgotten a crucial detail. Edited my comment (backspace 3).

Basically, any mention would display as a pill and only mentions display as pills. This is consistent with how git{hub|lab|ter}, polari, and (I think) discord work.

**Comment by lukebarnard1** [comment]
Wow, this is strange. It's as if there's some extra "hidden" character is causing this.

**Update:** I decided to test whether the user's avatar being set affected this behaviour because this has been the source of many bugs. My suspicion was correct - if the user hasn't set their avatar, the initial inserted in it's place causes draft-js to go a bit wobbly. The issue tracking that is here: #4772

**Comment by benrob0329** [comment]
I feel like mentions should just be the full username, and that username can be pill-ified.

**Comment by smichel17** [comment]
Advance apology for bumping, but can you please consider raising the priority of this issue? It's important enough to me that I have actually switched back to using irc on my desktop in order to use a different client[1], even though I like Riot better in pretty much every other respect.

It's especially annoying when dealing with an irc bridge, where people have irc and matrix names that share a common prefix. If I mention the wrong name, I can't just backspace a few times and correct it; I have to start from the beginning again (and, if I mentioned multiple people, it's hard to navigate through them because mentions break home and end functionality; I updated the original post to include this).

I suppose this would be OK if a mention behaved like a single character, and I can't put my cursor in the middle of it (like an emoji that's been copy-pasted into the text box). But it's this awkward mix between the two that is difficult to reason about and frustrating to work with. I just want my text box to act like text.

Reading over this, I think I may have come off more aggressively than intended. Text is a terrible medium, in some ways. Please read this less like criticism and more like a plea.

[1]: The client is polari; if you did nick autocompletion (specifically, multiple mentions at the start of a message) the way they do, I would be *ecstatic*.

**Comment by smichel17** [comment]
@lukebarnard1 I have disabled avatars, which helps a little, but mentions still behave as a weird amalgamation of one unit and individual characters.

The most obvious example I can give is: mention someone, place your cursor in the middle of their name, and press backspace. The entire mention is deleted. Why does the delete key treat a mention as a single unit, but the left and right arrow keys don't?

I don't particularly care *which* way you choose to treat mentions, I just want them consistent.

**Comment by lukebarnard1** [comment]
>The most obvious example I can give is: mention someone, place your cursor in the middle of their name, and press backspace. 

This feels like an OK UX and a little bit of an edge-case. 

I agree the cursor shouldn't have been within the bounds of the mention in the first place - this is the default behaviour of the rich input library we're using (draft-js).

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890
