### ISSUE TITLE
Emoji links not linkified

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4932]
Paste this as a message in Riot: https://en.wikipedia.org/wiki/🐻

The bear gets converted to emojione, ruining the link.

**Comment by lampholder** [comment]
:(

**Comment by ara4n** [comment]
fixed by matrix-org/matrix-react-sdk#1890

**Comment by BloodyIron** [comment]
The "tm" character also breaks URL hyperlinking, as per my closed #9318

**Comment by yannicka** [comment]
The emoji is now part of the link:

![image](https://user-images.githubusercontent.com/22885898/82730560-03a69b80-9d01-11ea-8883-3c7fca26bd21.png)
