### ISSUE TITLE
'Ctrl-A Backspace' sometimes doesn't work in new composer

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4935]
According to Cal in https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1504062793894871KAYFH:matrix.org, with complex formatting, it will sometimes erase without showing that it's erased

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/2257

**Comment by ara4n** [comment]
fixed by matrix-org/matrix-react-sdk#1890
