### ISSUE TITLE
'x' bottom on room preview no longer does anything

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#4938]
should take you back to the room directory

**Comment by t3chguy** [comment]
What `x`
![image](https://user-images.githubusercontent.com/2403652/29868758-26d04890-8d78-11e7-8f0b-b278a196360d.png)


ALSO WHAT THE HAPPENED ^^^

**Comment by turt2live** [comment]
cannot reproduce on Chrome 60, riot.im/develop

Steps used:
1. Create a room
2. Invite (and join) someone else to the room
3. Make it peekable and guest accessible
4. Leave the room
5. Navigate back to the room

I also tried forgetting the room.

**Comment by dbkr** [comment]
It appears for me after clicking on any room in the room directory that I'm not either in or is peekable: 
![screen shot 2017-08-30 at 17 19 17](https://user-images.githubusercontent.com/986903/29883194-623e6c98-8da7-11e7-8531-a890a98d13a0.png)

**Comment by turt2live** [comment]
Ah, I do get that when trying to go to a room by alias that I'm not in, particularly for cross-server rooms where I can't peek.

**Comment by t3chguy** [comment]
oh, I understood room preview = peeking, but in this case its the opposite.

**Comment by t3chguy** [comment]
So the button appears if the `onCancelClick` prop is passed, but it defaults to a no-op fn: https://github.com/matrix-org/matrix-react-sdk/blob/120a4f4f44480f7ded7b78ea0e993ca949abef35/src/components/views/rooms/RoomHeader.js#L59

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/05c232c8c34b87c19e8a613ffabb9c0565073e40/src/components/structures/RoomView.js#L1473 and https://github.com/matrix-org/matrix-react-sdk/blob/05c232c8c34b87c19e8a613ffabb9c0565073e40/src/components/structures/RoomView.js#L1517 are not passing the prop.

**Comment by t3chguy** [comment]
@dbkr 
> should take you back to the room directory

what if you got there by hitting a Pill, or its a oob invite?

**Comment by dbkr** [comment]
Turns out it's not meant to be there at all: it's only supposed to be there when editing room settings.
