### ISSUE TITLE
Typing notification takes a few seconds to display after switching room

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#4948]
### Description

After switching away from a room and back again while someone is typing, the typing notification bar takes a fair few seconds to appear. This makes it look like someone has stopped typing when actually they haven't.

### Steps to reproduce

- Have someone constantly typing in a room
- Switch to another room
- Switch back
- Observer the typing notification doesn't display at first

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
Possibly because the status bar animates from closed to open and a debounce is involved. We probably want to just display it open as soon as you switch if a user is typing already, or for any other reason why the status bar is openl.

**Comment by turt2live** [comment]
I think this is fixed (I haven't seen it since new typing notif behaviour)
