### ISSUE TITLE
Initiating a call in an encrypted room in which you are the only room member gives an unhelpful error message.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4949]
See conversation starting at https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15041919372464087cwsok:matrix.org

> so why does the message say: Error
> Conference calls are not supported in encrypted rooms
> 
> that means there is not exactly 2 users in that room

**Comment by lampholder** [comment]
It says `conference calls are not supported in encrypted rooms`, but you weren't actually trying to start a conference call.

**Comment by t3chguy** [comment]
My guess is its checking numMembers != 2 rather than >2 somewhere

**Comment by turt2live** [comment]
fwiw, this is the non-encrypted version:
![image](https://user-images.githubusercontent.com/1190097/30072612-25a1d6be-9228-11e7-98db-fcbdbeb3b24d.png)

**Comment by t3chguy** [comment]
Hmm looking at the code I cannot see why this is happening

**Comment by t3chguy** [comment]
I cannot reproduce, I have a feeling the reporter had bots in their room

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/30080408-bf84bfe0-9240-11e7-8398-9a3c984e486c.png)
