### ISSUE TITLE
withMatrixClient needs to go away

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4951]
We are now planning to remove withMatrixClient and just use `this.context.matrixClient` everywhere. This is partly because we want to support ES6 components moving fowards and rather not maintain two withMatrixClients and partly because the utility of being able to swap out the contexts for a different concept later depending on what the next React version does instead is not so great.

**Comment by lampholder** [comment]
Hey @lukebarnard1 I put some labels on your issue what do you think?

I don't really understand what you wrote so this is probably the most unhelpful form of 'triage'.

**Comment by lukebarnard1** [comment]
The labels are accurate :+1:

**Comment by turt2live** [comment]
We're so much closer to this now: just a few components appear to be using it.

**Comment by bwindels** [comment]
> We're so much closer to this now: just a few components appear to be using it.

just stumbled across this ticket in the source code. I guess we don't use `withMatrixClient` anymore as I don't recall seeing it ever :) But the second part of what Luke wrote, passing the client through the context, we're doing almost nowhere AFAIK, and rather get it through MatrixClientPeg. Or am I mixing things up?

**Comment by turt2live** [comment]
All of the groups stuff appears to be using context instead of a peg.

**Comment by bwindels** [comment]
right, is the idea then to use context in all react components and peg only in stores?

**Comment by turt2live** [comment]
I think so, although I'm ashamedly not caught up on the React way of doing things.
