### ISSUE TITLE
Aliases being added in the same 'Save' request cannot be canonical aliases

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4952]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=48861196)](https://www.bountysource.com/issues/48861196-aliases-being-added-in-the-same-save-request-cannot-be-canonical-aliases?utm_source=48861196&utm_medium=shield&utm_campaign=ISSUE_BADGE)

I couldn't find a similar issue on github, but this has been a long standing issue:

1. Open room settings
2. Type out a local alias
3. Set the canonical alias to that alias
4. Press save

The canonical alias is unchanged. Thanks lub on matrix for the reminder (https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1504211679174jddeO:imninja.net)

**Comment by t3chguy** [comment]
@turt2live I just tested this and could not reproduce, maybe it has been fixed since

**Comment by turt2live** [comment]
My network pane begs to differ.
![image](https://user-images.githubusercontent.com/1190097/35397273-4940c4ec-01ac-11e8-8b3b-4041889a0e13.png)

**Comment by turt2live** [comment]
Updated original post for the bounty :)

**Comment by turt2live** [comment]
This is not fixed

**Comment by turt2live** [comment]
This looks like it was actually fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2171 and my testing revealed a broken homeserver.
