### ISSUE TITLE
Lag/delay switching between 1:1 chats

### ISSUE THREAD

**Issue by kethinov** [vector-im/riot-web#4960]
There seems to be some kind of lag switching between some (not all) chats under some circumstances.

How I reproduce:
- Latest macOS, Electron app version 0.12.2, recent MacBook Pro.
- Bug did not seem present in 0.11.
- Under "People" switch to another person.
- If the chat you're switching to has a long chat history, there is a noticeable (like 1-2 second) delay between clicking the name and seeing the chat history.
- Does not happen with chats that do not have long histories.

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/4925
