### ISSUE TITLE
Theme changes have never had any effect. 

### ISSUE THREAD

**Issue by rocket-pig** [vector-im/riot-web#4964]
### Description

Any manner of changing from light to dark, saving, not saving, re-opening, ctrl-shift-reloading, clearing cache etc.....I can not has dark theme. 

### Steps to reproduce

-Im not sure if it's reproducable for anyone else, as reading thru the other bug reports it seems that nobody is having this problem. 

![screenshot from 2017-09-03 11-08-43](https://user-images.githubusercontent.com/24867505/30005479-509fd370-9098-11e7-8c46-4c5a241bd103.png)

### Version information

Chrome browser Version 60.0.3112.90 (Official Build) (64-bit) 
Ubuntu 16.10
Riot.im/app

**Comment by ara4n** [comment]
please can you submit a bug report from the settings page (after trying to change the theme) so we can see what error is causing this?

**Comment by rocket-pig** [comment]
I gave up, downloaded the desktop client, and the theme began as dark, thank goodness. 

Also just logged back into browser version and submitted report as requested, with same comment as title of this thread. Hope that helps! Thank you

**Comment by ara4n** [comment]
thanks!

-- 
Matthew Hodgson
Matrix.org

**Comment by turt2live** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/4700

**Comment by rocket-pig** [comment]
Except the other feller is able to change themes. I am (was, on web browser version) not whatsoever.

**Comment by pafcu** [comment]
@rocket-pig Is this still a problem?

**Comment by ara4n** [comment]
pretty sure this was fixed ages ago
