### ISSUE TITLE
Line breaks removed when using "Quote" function in message menu

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4966]
Line breaks is removed from quoted message text, when using "Quote" function in message menu, so if I try to quote message like:
```
line 1
line 2

line 4 after empty line
line 5
```
this will look in editor like:
```
| line 1 line 2  line 4 after empty line line 5
```

**Comment by lampholder** [comment]
I believe this is linked with https://github.com/vector-im/riot-web/issues/4874 inasmuch as they share a common cause - quoting pulling message text from the DOM rather than the message event data.

**Comment by aaronraimist** [comment]
This seems to be fixed
