### ISSUE TITLE
hovering over an emoji in the picker should not activate the autocomplete; surely you should have to click on it

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4974]
Even with "Automatically replace plain text Emoji" option disabled - sometimes text is autoreplaced with smileys instantly on typing.

For example, if I type `rooms :` text in message textarea - this text is auto replaced to `rooms 😁` on typing instantly after pressing `:` key.

Another example:
- `open long time :` » `open long time 😗`

**Comment by lampholder** [comment]
Hey @MurzNN - can you advise what browser/OS you're using and whether you've got any plugins/keyboard remappings etc. in place?

I'm not seeing this, but since pressing : opens the autocomplete popup, what sounds like might be happening is that the autocomplete popup is misinterpreting something as your making a selection.

What is your autocomplete delay set to in user settings?

**Comment by lampholder** [comment]
Minor p2 just 'cause I haven't heard of this affecting many people - if it's more common then it's more important :)

**Comment by lampholder** [comment]
Changed my mind - P1 until we know more about what's going on.

**Comment by MurzNN** [comment]
Firefox 55 web browser on Ubuntu Linux with https://riot.im/develop/ website.

**Comment by MurzNN** [comment]
Now I can't repoduce this after fresh reload of webpage, seems this is effect of some previous actions in DOM.

**Comment by MurzNN** [comment]
Yeah, reproduced: Open https://riot.im/develop/ , type "test :", select smiley from list via mouse click, after this - continue typing "test 😘 asada rooms :" and after you press last ":" - it will be instantly replaced by smiley "☺".

**Comment by t3chguy** [comment]
@MurzNN its because your mouse is still over the autocomplete thing most likely

**Comment by MurzNN** [comment]
Yes, mouse is still over smileys and they replaced instantly!

**Comment by vberger** [comment]
Yes, I have the same issue. If the pointer is where the autocomplete appears, whatever emoji is under it is automatically inserted whenever I type `:`

**Comment by lukebarnard1** [comment]
So _sometimes_ in _some_ browsers, a mouse move event is sent when the auto complete dialog appears, even if the mouse doesn't move...

**Comment by eternaleye** [comment]
@lukebarnard1 I disagree, TBH - not once have I wanted mousing over to _replace my input_, mostly because the input is the same size as the picker and so I don't really gain anything from it. I'd much prefer if `onMouseOver` instead showed a larger preview (sticker-sized?) so I could tell what was being selected.

**Comment by tradej** [comment]
I have this issue in Firefox 54.0.1 on Fedora 26. When the mouse is in the area where the list of emoji _will appear_ when typing (meaning the cursor is there first), the emoji that appears under the cursor is automatically entered when I continue typing.

I second the notion that `onMouseOver` is not a good action to replace the emoji, and would prefer having to click to replace them.

**Comment by lukebarnard1** [comment]
Okay, the consensus seems to be in favour of not inserting the emoji `onMouseOver` and finding another way to preview the emoji, and I quite like the suggestion from @eternaleye for a "sticker-sized" version of the emoji being previewed. Potentially the preview should only be shown after 1s or whatever.

**Comment by MurzNN** [comment]
I vote that emoji picker contains only emoji without text, and on hover - show sticker-sized hovered emoji with text implementation.
Here is React implementation of Slack Emoji picker: https://slack.engineering/rebuilding-slacks-emoji-picker-in-react-bfbd8ce6fbfe?gi=37f3b106bb90
![img](https://cdn-images-1.medium.com/max/1600/1*-9whH4kAysq6wVZaUQUc8Q.png)

**Comment by t3chguy** [comment]
Except it's not only an emoji picker but also autocomplete so if it doesn't have the short names you don't know what to type to filter further

**Comment by MurzNN** [comment]
With so much items in current unicode emoji list there are easier to select them via mouse (and filter via mouse by categories) instead of remember and typing text implementation. And classic text emoji like `;-)` and `:)` don't need replacement to image.

**Comment by lukebarnard1** [comment]
@MurzNN that feels like a separate issue. Let's keep discussion of improving the picker (UX) itself to https://github.com/vector-im/riot-web/issues/1107

**Comment by zzottel** [comment]
The worst problem is that if the mouse happens to be in region where picker list shows up, that emoji is instantly inserted (FF 55). So typing ":-)" while the mouse pointer is somewhere above the text field means some random emoji is inserted.

The same is true for commands: Type /me while the mouse pointer is somewhere above the text field, and some random command is inserted.

**Comment by anoadragon453** [comment]
Also getting this in FF 55.02. I like the idea of being to hover over the emojis and see them change, but perhaps only start listening for that after you've *moved* the mouse *after* the dialog has appeared, instead of instantly replacing once the dialog comes up.

**Comment by t3chguy** [comment]
@anoadragon453 that's the intention but https://github.com/vector-im/riot-web/issues/4974#issuecomment-330246244

**Comment by anoadragon453** [comment]
@t3chguy Ah, missed that sorry. Seems like you guys have some idea on how to improve the situation, so I'll just wait and keep my mouse to the side for now :P
