### ISSUE TITLE
Half of my 1:1's lost their 1:1 status

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4980]
### Description

Welcome back https://github.com/vector-im/riot-web/issues/3331 ?

This time about half of my DMs lost their status, instead of all of them. I can't pull logs atm, but I've reported the bug in Riot and will note to get synapse logs if needed.

~164 rooms lost their 1:1 status

### Steps to reproduce

- Open riot.im/develop after 3 days of not having the tab open

Describe how what happens differs from what you expected.

Log: sent (references this issue)    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Update on synapse logs: Nothing interesting is there, so I suspect it's a Riot issue.

**Comment by lampholder** [comment]
😭

**Comment by turt2live** [comment]
Good news: Not a riot-web issue.
Bad news: riot-android issue.

I'll gather more information and report it there.
