### ISSUE TITLE
Mangled names in highlights

### ISSUE THREAD

**Issue by lheckemann** [vector-im/riot-web#4984]
### Description

When I try to highlight a user with square brackets in their name, the resulting message appears mangled. E.g. when I highlighted `sphalerite[test]` on the IRC Bridges room, it appeared as `@freenode_sphalerite%5Btest%5D:matrix.org`:
![2017-09-05-203655_765x59_scrot](https://user-images.githubusercontent.com/341954/30080336-2bfc95c8-927b-11e7-89e3-282a1ae66068.png)
When Mikaela highlighted the same user, it appeared fine: 
![2017-09-05-204712_1049x185_scrot](https://user-images.githubusercontent.com/341954/30080406-68ef9b88-927b-11e7-835c-10fc38c1f463.png)

I noticed that this difference appears in the source of the messages as well: my highlight had `<a href="https://matrix.to/#/@freenode_sphalerite%5Btest%5D:matrix.org">` while Mikaela's had `<a href="https://matrix.to/#/@freenode_sphalerite[test]:matrix.org">`.

### Steps to reproduce

- Highlight an IRC-bridged user with a name containing square brackets (not tested with regular matrix users)

Expected: appears as `sphalerite[test]`

Actual: appears as `@freenode_sphalerite%5Btest%5D:matrix.org`

Log: Sent

### Version information

- **Platform**: Web app

For the web app:

- **Browser**: Firefox 55.0.2
- **OS**: NixOS (linux) 17.03
- **URL**: riot.im/app *and* riot.im/staging

Also tested on…

- **Browser**: Chromium 60.0.3112.78
- **OS**: NixOS (linux) 17.03
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
looks like a state mismatch, could you go into settings scroll to bottom and clear cache and reload
seems like your client doesn't have the displayname of that user and so its falling back to MXID

**Comment by lheckemann** [comment]
No, that didn't help.

Full source of an example message: 
```json
{
  "origin_server_ts": 1504641691881,
  "sender": "@sphalerite:matrix.org",
  "event_id": "$15046416911557180tqAdP:matrix.org",
  "unsigned": {
    "age": 1028,
    "transaction_id": "m1504641691682.0"
  },
  "content": {
    "body": "sphalerite[test]: ",
    "msgtype": "m.text",
    "formatted_body": "<a href=\"https://matrix.to/#/@freenode_sphalerite%5Btest%5D:matrix.org\">sphalerite[test]</a>:",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!tckjEObrtDIGmCBjwX:matrix.org"
}
```

**Comment by grahamperrin** [comment]
OK, I found the incident I was seeking. From <https://github.com/vector-im/riot-web/issues/4867#issuecomment-329870050> (2017-09-15) affecting `/develop/`: 

![2017-09-15 19 44 01 riot 2](https://user-images.githubusercontent.com/192271/30498432-9e53904c-9a4e-11e7-819d-6e435c979cf2.png)

Strangely, I have no recollection of the bug biting `/app`/ at any time in the months since then.

**Comment by Ralith** [comment]
Any hope of a fix in the forseeable future?

**Comment by jryans** [comment]
At the moment, this is part of a long backlog of paper cuts, each of which seems important on its own. I'll mark this "help-wanted" to hopefully encourage a PR to be submitted here.

**Comment by Ralith** [comment]
If this isn't considered a priority, maybe it shouldn't be labeled "major, p1"?

**Comment by jryans** [comment]
Nudging down to p2, as that seems to be closer to current priority in practice. It's still quite a bad issue when you hit it, so major seems appropriate.

**Comment by jryans** [comment]
(In general though, the issue priorities should be viewed as a very fuzzy relative ordering. We would like to get to the p1 issues before the p2 issues, etc. There's also lots of room to clean up older issues that may no longer apply, etc. Issue tracking is a best effort system that continually evolves over time.)

**Comment by Ralith** [comment]
This is still happening, e.g. with backticks.
