### ISSUE TITLE
@mention tab completion doesn't work for TheManiac™

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4992]
the lozenge is mysteriously missing when trying to tab-complete TheMan\<tab\>

**Comment by lampholder** [comment]
@ara4n - to confirm your experience is the same as mine:
- go to Matrix HQ
- type `TheMan` and press <kbd>tab</kbd>
- The full name is completed to `TheManiac™` but without an avatar or the lozenge background

**Comment by maxgrenderjones** [comment]
Confirmed

**Comment by lukebarnard1** [comment]
This is because in the composer, emoji (like :tm:) are entities, and entities can't be nested.

**Comment by ara4n** [comment]
fixed by matrix-org/matrix-react-sdk#1890

**Comment by maxgrenderjones** [comment]
:D
