### ISSUE TITLE
Riot Desktop 0.12.2 (macOS) Searching in This Room/All Rooms yields no results

### ISSUE THREAD

**Issue by MacLemon** [vector-im/riot-web#4998]
### Description
Riot Desktop 0.12.2 (macOS) Searching in This Room/All Rooms yields no results

### Steps to reproduce
- Enter any room
- Look for a string that's definitely been said in that room, or just say “testing foo” in that room.
- Now we know a string that should be found.
- Go to the search item by clicking on the loupe icon of the room
- in the search field enter “testing foo” (sand the quotes, as usually)
- klick either “This Room” or “All Rooms” to define the search scope
- wait for the results to be displayed

Describe how what happens differs from what you expected.
Nothing is ever found, or at least nothing is displayed. Even strings/words that *definitely* must be there, like “testing foo” are not found.

### Version information
For the desktop app:

- **OS**: macOS 10.12.6 (Sierra)
- **Version**: 0.12.2

- **OS**: iOS 10.3.3
- **Version**: 0.53 #master 86; Olm 2.2.2

- **Server**: synapse 0.22.1 matrix.org or other federated homeservers on the same version.

### Regression
This did indeed work with former versions of Riot Desktop and iOS and seems to be a regression in 0.12.x./0.5.3.
Related Bug for Riot/iOS [#1499](https://github.com/vector-im/riot-ios/issues/1499)

**Comment by t3chguy** [comment]
Could it possibly be https://github.com/vector-im/riot-web/issues/4950 or https://github.com/vector-im/riot-web/issues/2548

**Comment by lampholder** [comment]
I tried this with 0.12.3 on OSX 10.12.6. I sent the message:
`banana test`

into a room, and the searched for the string
`banana test`

I tried it a few times; the first time I got a 504 & the search result was returned; subsequent times I just got the search result.

It _was_ unreasonably slow, but it did work.

@MacLemon - can you confirm:
- was the room encrypted (#2548)?
- was the search string made up of uncommon words (#4950)?

Thanks!

**Comment by MacLemon** [comment]
> was the room encrypted (#2548)?
Yes, pretty much all the rooms I use are encrypted, which is one of the main reasons of using Matrix. (Encrypted group chats)

> was the search string made up of uncommon words (#4950)?
Yes, absolutely.

Conclusion: The bug affecting me is #2548. It would help if the user would be informed about this, or even remove the search items from the toolsbar since they don't work at all in E2E chats.
Obviously better, let the client search in the local copy of the chat history and make users happy. :-)

**Comment by lampholder** [comment]
100% agreed - this is under discussion here: https://github.com/vector-im/riot-web/issues/4982
