### ISSUE TITLE
Race in decrypting events causes UISI

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5001]
* we receive the megolm event and try to decrypt; this fails (asynchronously)
* we receive the olm event and decrypt the megolm keys. We add the key to the store, and also look for any recorded failures for that megolm session (currently none)
* we go back to processing the megolm event. We record the failure, but now it's too late.

One solution might be to serialise access to the list of failures.

**Comment by lampholder** [comment]
Again, happy to negotiate on the priority here - I've P1'ed but I don't know what % of encrypted traffic this is likely impacting.

**Comment by richvdh** [comment]
It seems to affect matthew quite heavily. Agreed it should be P1 but it's unlikely to get much progress while I'm on holiday...

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/544, I hope
