### ISSUE TITLE
Autocomplete lozenge breaks if you try to remove the trailing colon

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5002]
If you type:
 * Manu<tab>  (which autocompletes to `(Manu):` in a lozenge)
 * and then delete the trailing space and colon
 * and type `/`
 * and then start to type someone else's name

it all breaks.  see video at https://matrix.org/_matrix/media/v1/download/matrix.org/lsNiNwJlgEZMXsDhMFFTNWoC

**Comment by turt2live** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/4864

**Comment by t3chguy** [comment]
Closing as duplicate, it occurs only on members with the generated avatars
