### ISSUE TITLE
feature request: edit message

### ISSUE THREAD

**Issue by edmundlaugasson** [vector-im/riot-web#5004]
### Description

Would expect to edit the message like in [Slack](https://slack.com/), [Telegram](https://telegram.org/). This means that the edited message will be replaced with new one and previous one will be not shown.

### Steps to reproduce

- enter the message
- press arrow up and edit the message
- press enter to send edited message to replace the old one

A new message will be sent instead of editing the old one. Then I have to delete the previous message and all participants will see that I deleted a previous message. It does not save space and conversation will get longer and deleted messages as garbage will waste the space. Certainly in fast messaging the deleting is very uncomfortable.

Also "Edit message" choice would be expected under three dot menu of the message like in [Slack](https://slack.com/), [Telegram](https://telegram.org/). In that way there would be possible to edit also messages in history not only the last one.

### Version information

matrix-react-sdk version: 0.10.3
riot-web version: 0.12.3
olm version: 2.2.1

Using desktop version on 64-bit Linux Mint 18.2 MATE

**Comment by uhoreg** [comment]
dup of #1862.  This is a highly requested feature, but it turns out to be difficult to do due to the way Matrix works.  However, it is definitely planned to be implemented eventually.
