### ISSUE TITLE
Allow 'Ctrl-Enter' to be used to send a message

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5005]
in addition to 'Enter'.  As suggested by Poulad at https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15048789704490836xMIEa:matrix.org

**Comment by richvdh** [comment]
it does already

**Comment by pouladpld** [comment]
No. I meant giving user the option to change keys in this format:

- `Enter` : Make line breaks within message text
- `Ctrl + Enter`: Send message

**Comment by pouladpld** [comment]
@uhoreg could you modify the title?

**Comment by pouladpld** [comment]
Here is an example of 2 different options for it. Image from Telegram's web app UI:

![image](https://user-images.githubusercontent.com/14295804/30215608-80427670-947e-11e7-8b9f-62ebf3f7b4ad.png)

**Comment by pouladpld** [comment]
@lampholder now you closed #5006, please keep this one open

**Comment by theowen** [comment]
@richvdh I don't think this should be closed yet

**Comment by uhoreg** [comment]
@theowen #5006 is the issue to follow for allowing configuration of what `Enter` does

**Comment by jsveiga** [comment]
Isn't this what the "send_on_ctrl_enter" in Advanced Configuration does?
