### ISSUE TITLE
Riot 0.12.3 Windows setup detected as virus by Avans

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/riot-web#5009]
Don't have much info, just a friend sending me this screenshot:
![](https://image.prntscr.com/image/QcsH642UTw_KtMnPlU_ZNQ.png)

EDIT: Avans Free Antivirus on 64-bit Windows 10 for Education.

**Comment by TheLastProject** [comment]
More info:
![](https://image.prntscr.com/image/7oA_H13VQPGpE5oCQBZS4g.png)

**Comment by 4nd3r** [comment]
looks clean:
https://www.virustotal.com/#/url/53984d8b5a2edb15dc8049957a929f5d410ca675f94b6a828c430d229a46e89c/detection
https://www.virustotal.com/#/url/dfbacbc0ec5b1e517c95488e507fdc3b187c75b5c0c0ca30acbc47d30ae3252e/detection

so looks like false positive.

**Comment by MTRNord** [comment]
@4nd3r you scaned the link. Scanning the setup file after download gives https://www.virustotal.com/#/file/e08d0974a6a7e83d29ba029fe4b79ef2de4e1a74b2f08977e6d6a1e62b1d577c/detection

**Comment by MTRNord** [comment]
But scanning the actual application doesn't give the same result. So it is the installer which got the warning https://www.virustotal.com/#/file/c498773f8ef1525b5859fb50479c489458347a7b0e4bfb94ada735add0ca6fb9/detection

**Comment by lampholder** [comment]
Hmm. Odd that this should happen just as we start signing the installer :\

@TheLastProject - was your friend installing Riot for the first time?

**Comment by TheLastProject** [comment]
He had run an older version before, which he uninstalled because "it broke" before trying to install this new version. I do not know which version this was.

**Comment by ara4n** [comment]
this is almost certainly https://github.com/vector-im/riot-web/issues/5948
