### ISSUE TITLE
downloading a json.gz file gave me a gzip file but stripped the .gz extension

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5011]

**Comment by dbkr** [comment]
I think this is actually a bug somewhere in the depths of electron.

**Comment by dbkr** [comment]
Turns out this is https://github.com/electron/electron/issues/10121

**Comment by t3chguy** [comment]
The upstream bug was closed. Will double check if this is fixed

**Comment by t3chguy** [comment]
It seems like the electron app no longer handles downloads and they just get opened in the default browser

**Comment by t3chguy** [comment]
this looks to have been macos specific but since upstream bug is closed going to assume solved unless told otherwise.
