### ISSUE TITLE
If you've selected the files panel then create a new room, the message in the files panel is wrong.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5016]
To reproduce the issue:
- go to any room
- click the files panel
- create a new room
- look how it still says "You must join the room to see its files"

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/30422600-5d1692f8-9938-11e7-814a-a3a6d6e6865c.png)
I cannot reproduce but looking at the code I have a feeling its racy

**Comment by t3chguy** [comment]
/me would Gif but Windows gif screencap is dreadful

**Comment by turt2live** [comment]
This doesn't happen anymore.
