### ISSUE TITLE
Sometimes can't see last message when there is someone typing in the room

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5017]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15051523201994uwSIi:thebeckmeyers.xyz There's probably an open issue for this, please close as dupe if needed

**Comment by lampholder** [comment]
There is; it's here: https://github.com/vector-im/riot-web/issues/4829

There's a question on #4829 about whether this is just E2E rooms - I don't think it is, but if you can confirm that you've experienced it in non-E2E rooms for certain that would be useful :)
