### ISSUE TITLE
Hide message contents on lock screen for privacy

### ISSUE THREAD

**Issue by alallier** [vector-im/riot-web#5019]
### Description

It would be nice to hide the contents of a message when on the lock screen. You could still provide the native notification but not show who it is from or what the contents are. Using Mattermost for an example, this is how a notification looks on the lock screen of Windows.

![image](https://user-images.githubusercontent.com/13004518/30287269-6e91946c-96f2-11e7-91f2-1557066ea123.png)

### Version information

Any version

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10 (not sure how this affects Mac OS)

**Comment by t3chguy** [comment]
So this is just hiding message contents in notifications.

**Comment by t3chguy** [comment]
Duplicate https://github.com/vector-im/riot-web/issues/3814

**Comment by t3chguy** [comment]
I don't know how possible it is for a webapp to know your lock state. Maybe via some native electron code for the desktop app but this wouldn't be trivial at all. @alallier

**Comment by alallier** [comment]
This is aimed at the desktop app. Electron supports it.

https://github.com/vector-im/riot-web/issues/3814#issuecomment-328825181
