### ISSUE TITLE
E2E room with new message takes a while to move to top

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#5020]
Normally when you receive a message in a room its unread count goes up at the same time that it move to the top of the room list.

At least with one (largish) e2e room I see the unread count go up and the desktop notification several seconds before the room moves to the top of the list.

This is on chrome web at riot.im/develop (linux)

**Comment by dbkr** [comment]
I suspect this is another one due to rich's async stuff, in that the RoomList is updating when the event arrives, but the event is now not decrypted at this point, so it doesn't consider the room to have an unread message.
