### ISSUE TITLE
consider whitelisting <sub>, <sup>

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5021]

**Comment by lampholder** [comment]
Sounds<sub>good</sub>to<sup>me</sup>:smiley:

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/30374135-c632ae1a-987b-11e7-8a1c-68cec8aef404.png)

**Comment by turt2live** [comment]
@t3chguy this can be closed now? :p
