### ISSUE TITLE
Read reports randomly display different (and sometimes incorrect) formats

### ISSUE THREAD

**Issue by alallier** [vector-im/riot-web#5026]
### Description

Only the first read report is in the 12 hour format (when the 12 hour format is selected)

### Steps to reproduce

* Enable 12 hour format
* Receive a message in a room with more than one person, and have more than one person read your message (leaving a read report). Hover over each read report to see the time.

Notice only the first read report is in the 12 hour format and the rest are in the 24 hour format. See below GIF.

![matrixreadreport](https://user-images.githubusercontent.com/13004518/30375586-16b30b2a-9857-11e7-95bc-1665d9da2650.gif)

**Edit**: See below discussions and follow up GIFs in the comments. The read reports have more random and incosistent behavior

### Version information

- **Platform**: All

For the desktop app:

- **OS**: Windows 10 Version 1703 (Build 15063.540)
- **Version**: 0.12.3

Related to #4393

**Comment by t3chguy** [comment]
The desktop app is the same code as the webapp.

**Comment by alallier** [comment]
It's behaving very strangely, the message from above is fine now. But another channel shows timestamps in completely different syntax's and still the wrong hour format. Seems like there are some inconsistencies.

![matrixreadreport2](https://user-images.githubusercontent.com/13004518/30376030-c0344f64-9858-11e7-805a-375801f1946f.gif)

**Comment by t3chguy** [comment]
weirdly for me they're always in 24H mode :L

**Comment by alallier** [comment]
@t3chguy Even with the 12 hour format selected in options?

**Comment by t3chguy** [comment]
yeah, and then in a dev build I'm having a similar issue where randomly some are 12H and some 24H

**Comment by alallier** [comment]
Yep that's what I observe as well as some are in some type of format while others are in different formats. Like some say `Mon, Sep 4 17:08` and others just say `Mon, 9:44 PM`. Like my GIFs demonstrate.

**Comment by t3chguy** [comment]
I have narrowed it down to our DateUtils being a bit wonky
I'll debug some more

**Comment by t3chguy** [comment]
think I found the issue, the is12H parameter wasn't being passed all the way

**Comment by t3chguy** [comment]
(not desktop specific)

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1383

**Comment by turt2live** [comment]
@t3chguy this one too

**Comment by t3chguy** [comment]
dammit, wish Github would just be magic and close them for me!
(not like it does, if I wrote Fixes #5026 in the commit/PR once it hits master, sometimes...)
