### ISSUE TITLE
Unable to start a chat when using an e-mail address for the other participant - Riot bug, invalid request body

### ISSUE THREAD

**Issue by maxidor** [vector-im/riot-web#5028]
### Description
Unable to start a chat using an e-mail address

### Steps to reproduce
- Click on "Start Chat" icon on the bottom left
- Type in an e-mail for a user you wish to start a direct chat with
- Accept the "box" from Riot
- Press Enter or "Start chat"

At this point, I would expect to see a new room created and the user invited using its e-mail, either as a pending invite, or turned into a Matrix ID.  
Instead Riot shows a dialog "Failure to create room" with the message "Server may be unavailable, overloaded, or you hit a bug."

Log: not sent

### Troubleshooting info
When sending a POST request to `/_matrix/client/r0/createRoom`, the e-mail address is put under the `invite` attribute, instead of the `invite_3pid` which makes synapse deny the request with a status 400, as it is not a valid Matrix ID.

### Version information
- **Platform**: web (in-browser) AND desktop

For the web app:

- **Browser**: Firefox 55.0.2
- **OS**: Linux Mint 18.2
- **URL**: Private server, version 0.12.1, 0.12.2, 0.12.3

For the desktop app:

- **OS**: Linux Mint 18.2
- **Version**: 0.12.3

**Comment by dbkr** [comment]
Oops. Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1386
