### ISSUE TITLE
/join doesn't join anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5029]
### Description

It leaves you at the "Click to Join" prompt.

### Steps to reproduce

- Type `/join #some:room.com`

I'd expect to be joined to the room. This looks like a regression.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Easily reproduced (and it does just leave you at the 'Click to join' prompt indefinitely - it's not just slow).
