### ISSUE TITLE
Video conferencing config needs to be factored out to allow for self-hosted freeswitches

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#503]
VC in vector is currently hardcoded to the matrix-appservice-verto AS (and thence freeswitch) running on matrix.org.  We need to spec how to set a state event to track where the focus is for a given conference, and then expose config options so that folks can host their own verto bridges and freeswitches for self-hosted verto conferencing.  Related: https://matrix.org/jira/browse/SPEC-174 and https://matrix.org/jira/browse/BOTS-132.

**Comment by 4nd3r** [comment]
do I understand correctly that right now all video and voice calls are be going through 3rd-party server?

if yes, is it somehow possible to disable video/voice calls in vector/synapse?

**Comment by richvdh** [comment]
closing as per https://github.com/vector-im/riot-web/issues/1869#issuecomment-340302329
