### ISSUE TITLE
need timeline events when folks add/remove aliases

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5034]

**Comment by t3chguy** [comment]
Needs design.
One possible mockup:
![image](https://user-images.githubusercontent.com/2403652/30442280-e72c3d5e-9973-11e7-992c-9c9a108332f8.png)


Simply generating the string is not i18n-sane due to different pluralizations and sentence structure and the fact that you can add and remove any number of aliases in the same event.

**Comment by Angedestenebres** [comment]
Hey,

This is exactly the same thing if an user uses the /me command. The message is shown without any timeline, see screen below as example:

![screenshot_2018-05-17_13-57-27](https://user-images.githubusercontent.com/21110485/40176123-911bc196-59da-11e8-91f4-fd31240f79f6.png)

However, on mobile app, the timeline can be found by clicking on the message : 

![screenshot_20180517-113708](https://user-images.githubusercontent.com/21110485/40176324-4d83e318-59db-11e8-9dd9-5e7cef9ce910.png)

**Comment by ara4n** [comment]
i never saw that there was a proposal for this; sorry @t3chguy :( this looks fine to me, although i'm a bit confused about the i18n issues here, or why one wouldn't just have "Foo added #bar, removed #baz" and why we have the 'changed' state at all?

**Comment by ara4n** [comment]
closed by matrix-org/matrix-react-sdk#2167. I opted to back out the GELS collapsible support, as it seemed to introduce a lot of complexity, and I couldn't find anyone in the translation community who could justify why it would be hard to internationalise the plurals in "added X and removed Y as addresses for this room", given 'addresses' will always be plural, even in Polish?
