### ISSUE TITLE
Show who banned the user in RoomSettings

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5039]
Only to people who can unban though?

**Comment by MTRNord** [comment]
Maybe Show the reason too? (not sure If it already does it)

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/30481975-61b95560-99de-11e7-864c-1055ea35c97a.png)

It does show the reason, if there is one :)

**Comment by MTRNord** [comment]
@turt2live and I learned another thing about riot :) in that case ignore my above comment :)

**Comment by lampholder** [comment]
There's always another thing to learn about riot :D

**Comment by turt2live** [comment]
This is fixed now.
