### ISSUE TITLE
Disable grey tint suggestion for rooms?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5045]
There's quite a few issues reported that can be narrowed down to the grey tint being used. To alleviate some of the pressure around the UI being confusing/hard to read, does it make sense to just take out the grey tint for the time being? In a perfect world, the grey tint would just work with the rest of the app, but given the backlog and number of items requiring design I assume that making the UI work with grey tints is not high priority.

@lampholder - what do you think?

Edit: I should probably include mentions to those issues:
* https://github.com/vector-im/riot-web/issues/4637
* https://github.com/vector-im/riot-web/issues/3328
* Many messages in #riot over the last year (comes up every once and a while)

**Comment by lampholder** [comment]
I think this makes a lot of sense.

If I understand it correctly, I think we could drop the grey tint from the colour picker without changing any rooms already configured to use the grey tint. And grey-tint-fans can always add the tint to rooms manually with the... `/tint` command.
