### ISSUE TITLE
adding RSS is broken in /develop.

### ISSUE THREAD

**Issue by Ai-rin** [vector-im/riot-web#5047]
You always get "HTTP 500: Internal Server Error".
/app works fine.

Chromium 61.0.3163.79 (openSUSE Build) (64-bit)

**Comment by turt2live** [comment]
I can't reproduce this. It's possible it was broken at the time of reporting and fixed now - is it still happening?

**Comment by Ai-rin** [comment]
Yeah it started to work for me too. Probably got fixed in the latest builds.
