### ISSUE TITLE
Jitsi Widget should allow external Jitsi Servers

### ISSUE THREAD

**Issue by m1ndgames** [vector-im/riot-web#5048]
### Description

The Jitsi Widget in Riot provides a jitsi.riot.im url.
We dont want to use external services and prefer to host everything ourself.

The Widget should allow that an external jitsi room url can be entered manually.

### Steps to reproduce

- Enter a Room
- Create a Jitsi Widget
- It provides a hardcoded jitsi.riot.im URL.

### Version information

Riot Web 0.12.2 Release

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome, Firefox?
- **OS**: Desktop: Arch Linux, Server: Debian 9
- **URL**: private, but applies to any room.

**Comment by t3chguy** [comment]
> We dont want to use external services and prefer to host everything ourself.
The panel you see to add the Jitsi widget, Modular, is not possible to host yourself anyway.

Nothing to stop you using Custom Widget via Modular or via state events, but Jitsi Widget with custom jitsi urls is planned

**Comment by m1ndgames** [comment]
I guess you mean the integration server scalar.vector.im?

Why is this hosted by vector, and not part of the riot web package?

**Comment by t3chguy** [comment]
Because it controls services that are ran by vector, like their go-neb instance and their bridges. It is proprietary as in the future will provide premium (paid) services. None of the existing services will become paid, additional ones will be added.

**Comment by m1ndgames** [comment]
I understand, thanks for clarification.

**Comment by t3chguy** [comment]
> but Jitsi Widget with custom jitsi urls is planned

leave this issue open to track that

**Comment by JamesTurland** [comment]
Has there been any update on this? It would be a great addition to the platform as it'd compliment the decentralisation that the rest of the platform affords.

**Comment by MTRNord** [comment]
I know this is a upstream issue  but Dimension by @tur2live supports this (a alternativ to scalar. Selfhosted)

**Comment by wetradecrypto** [comment]
Any update on this?

**Comment by ara4n** [comment]
the guy working on it left the project, and we haven't found bandwidth to progress it since.

**Comment by Jimmy-SafeCash** [comment]
Just wondering if this feature has made it onto any future update path yet?

**Comment by lephisto** [comment]
Updates? Where to get rid of the public jit.si?

**Comment by t3chguy** [comment]
By default it actually uses jitsi.riot.im not the public jit.si.
