### ISSUE TITLE
one of the 'envelope' emojis in RTE is invisible in the editor

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5049]
If you just use the plain 'envelope' symbol (2709) it works fine, but there's also one combined with 'variant 16' (fe0f). In the composer it tries to fetch 2709-fe0f.svg for this, which doesn't exist. In the timeline it just uses 2709.svg.

<img width="319" alt="screen shot 2017-09-15 at 11 14 22" src="https://user-images.githubusercontent.com/986903/30477993-13257fe0-9a07-11e7-9c19-f65ebfb4a8a0.png">

If you select the first envelope here, it's invisible in the composer.

**Comment by lampholder** [comment]
I thought this was already filed somewhere, but I can't find it :\

**Comment by pafcu** [comment]
@dbkr https://github.com/matrix-org/matrix-react-sdk/pull/1458 fixes this, right? Can be closed?

**Comment by pafcu** [comment]
@dbkr @lampholder Could be closed?

**Comment by ara4n** [comment]
sounds like it!
