### ISSUE TITLE
declining an invite no longer removes it from LeftPanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5052]

**Comment by lampholder** [comment]
Potentially related https://github.com/vector-im/riot-web/issues/4624

This seems to be an ongoing but intermittent problem.

**Comment by mray** [comment]
Riot-web verion  0.13.0 on Ubuntu:

![peek 2017-11-19 21-27](https://user-images.githubusercontent.com/164785/32995217-9bed2f74-cd71-11e7-9156-ab36d1d29eca.gif)

**Comment by t3chguy** [comment]
@mray I think thats a different issue, in that the invite was revoked or similar, go to bottom of Settings and clear client cache

https://github.com/vector-im/riot-web/issues/3743

**Comment by mray** [comment]
Unfortnuately this workaround does not work here. Restarted riot *and* synapse, cleared Cache and Reloaded. Still persists.

**Comment by mray** [comment]
Still a problem in 0.13.1.

**Comment by ara4n** [comment]
it works these days.
