### ISSUE TITLE
ILAG: Canceling username prompt after joining a room leaves infinispinner

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5055]
### Description

This is a somewhat more complicated issue, but seems like it could be encountered easily.

### Steps to reproduce

- Navigate to riot.im/develop/#/room/#matrix:matrix.org
- Click the "Join room" button
- Cancel/exit the username dialog
- Infinispinner

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Has this been fixed already? I can't reproduce this.

What sort of infinispinner was it? Full page, or somewhere else?

**Comment by turt2live** [comment]
This seems fixed.
