### ISSUE TITLE
if a new search is prepared soon after a cancellation, then pulsing of the magnifying glass icon is premature

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#5056]
## Steps

From <https://github.com/vector-im/riot-web/issues/498#issuecomment-329877993>: 

> 1. whilst the magnifying glass pulses
> 2. click the nearby **X**

3. click the magnifying glass icon at the head of the page

## Expected

- a non-pulsing magnifying glass icon to the right of the search field

## Actual result

- pulsing.

**Comment by grahamperrin** [comment]
… and if the second search is begun too soon, then search results are for the _previously sought_ phrase. For example: 

![2017-09-15 20 59 43 riot 2](https://user-images.githubusercontent.com/192271/30501118-0a670246-9a59-11e7-8b81-80dd02e976c5.png)

**Comment by turt2live** [comment]
Cannot reproduce with new search UI
