### ISSUE TITLE
Close button does not work when room does not exist

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/riot-web#5058]
### Description

When joining a room which does not exist, the close button do not work.

### Steps to reproduce

- join an empty room
- click on the upper right cross
- it does nothing

### Version information

- **Platform**: web
- **Browser**: Firefox 50.0.2
- **OS**: Debian
- **URL**: private server, v0.12.3

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1381 probably
