### ISSUE TITLE
Click&dragging the scrollbar in the message pane causes significant jumping

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5059]
### Description

When using the "grab the scrollbar and drag up/down" method to navigate the timeline the pane jumps around due to the way the scrollbar interacts with the infinite scrolling.

I'm not sure how to deal with this, but presumably it's a minor case.

### Steps to reproduce

- Click and drag scrollbar up until you trigger infinite scrolling

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I haven't been able to reproduce this, I'll try dragging the scrollbar more in daily use and see what happens :)

**Comment by turt2live** [comment]
It probably comes down to me not using the scrollbar right. I don't let go of it, and when dragging it upwards eventually the paged content loads, causing the scrollbar to become smaller and smaller, eventually to the point where the cursor is above the bar, leading the OS to think that you want to scroll up "faster".

**Comment by turt2live** [comment]
This seems to have gotten better - closing
