### ISSUE TITLE
Why can't I quote outside photo using MD?

### ISSUE THREAD

**Issue by kmahyyg** [vector-im/riot-web#5060]
### Description

I'm trying to send a photo which stored in the network (not in my homeserver) using Markdown grammar , looks like this:

```![test photo](https://www.baidu.com/img/bd_logo1.png)```

### Steps to reproduce

- 1. send a message to other people using the markdown code above.

#### Describe how what happens differs from what you expected.

Instead of seeing a photo , I just saw a empty string but got a Chrome pop-up notification which contains the plain text of markdown code.

#### Log 

I can't find any related log in the console of Chrome Developer Tools.

### Version information

- **Platform**: WEB

For the web app:

- **Browser**: Chrome 61.0.3163.79
- **OS**: Windows
- **URL**:https://riot.im/app and the latest version of Riot Web APP which I set up in my private server.

Also , I tested in the situation both with default server and my self-hosted homeserver.
The problem existed in both servers.

**Comment by MTRNord** [comment]
inline images need to be a `mxc://` URL. Means only already uploaded images do work. The reason is that external services could/can leak the IP of users in the Chat. the `mxc://` URL is documented here: https://matrix.org/docs/spec/client_server/unstable.html#id54

**Comment by kmahyyg** [comment]
So Can I setup a server to store outside photo?

**Comment by uhoreg** [comment]
To fix this issue, Riot would need to:

1. detect the image link
2. download the linked image
3. upload it to the server
4. replace the link with the resulting mxc URL

**Comment by kmahyyg** [comment]
Thanks a lot.

**Comment by t3chguy** [comment]
Which for the record is often not possible for riot to do, due to CORS
Adding a mechanism for server side download to mxc would be required
