### ISSUE TITLE
Devtools: Clicking back after failing to send an event should be still have the data you tried to send

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5063]
### Description

When entering an event there's the possibility of spelling errors and such. It would be nice that if when you click 'Back' after an event failed to send (such as the case of invalid json), the form was still populated with what you tried to send.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
this is just a manifestation of me being lazy and using uncontrolled inputs :L
