### ISSUE TITLE
Devtools: Event sends when not entering anything

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5064]
### Description

Clicking 'send' without entering anything says the event sent successfully.

### Steps to reproduce

- Open `/devtools`
- Click "Send an event"
- Click "send" without entering anything
- See "Event sent!"

It should probably yell at me to at least specify an event type.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
/me wonders why js-sdk is happy with that

**Comment by t3chguy** [comment]
huh I guess the empty string is a valid event type...
