### ISSUE TITLE
Devtools: Would be nice to edit a state event

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5065]
### Description

From the `explore state` area, it would be nice to be able to edit the state event. Doesn't need to be anything pretty, just shove me into the `send custom state event` screen.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Grand idea, didn't think of it when designing :)
