### ISSUE TITLE
Devtools: Would be nice to search m.room.members and other long lists

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5066]
### Description

Ability to search this:
![image](https://user-images.githubusercontent.com/1190097/30525721-5ec1a140-9bc9-11e7-9c9e-dfa018bb4b18.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
*cough*<kbd>Ctrl</kbd> <kbd>F</kbd>*endcough*

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/30525748-f78fb13c-9bc9-11e7-9334-8a6afd43897a.png)
