### ISSUE TITLE
Devtools: Browse/edit account data

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5068]
### Description

This would be neat.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
js-sdk and its stores do not expose a way of fetching all account data, only by type :L

**Comment by t3chguy** [comment]
http://matrix-org.github.io/matrix-js-sdk/0.8.2/store_memory.js.html#line302

**Comment by t3chguy** [comment]
eh, `cli.store.accountData` is not too nasty
