### ISSUE TITLE
/<tab> or pause should show list of / commands

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5069]
atm you have to do /<letter><tab> for it to start autocompleting

**Comment by t3chguy** [comment]
I think it used to show them all on just `/`, so maybe a regression

**Comment by lampholder** [comment]
I don't quite understnad Matthew's original comment, but I'd vote for showing them all on just `/`.

I'm guessing we'd pause for the length of time specified by the autocomplete delay in user settings? Popping suggestions immediately might help mitigate https://github.com/vector-im/riot-web/issues/4630 but I think I'd rather people can control all forms of autocomplete with the same setting.

**Comment by turt2live** [comment]
The same behaviour as the emoji, people, etc autocomplete would be fine imo. It used to work nicely, but something changed in recent builds.
