### ISSUE TITLE
join room from preview as PWLU is broken

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5071]
I just loaded riot.im/develop as incognito user; clicked the Riot room icon; clicked 'join'; got infinite spinner.

**Comment by lukebarnard1** [comment]
I just tried and couldn't repro, so looks like we've got a flaky bug.

**Comment by dbkr** [comment]
I can't repro this either right now

**Comment by lukebarnard1** [comment]
Going through the ILAG flow seems fine to me but the spinner on the room header does appear for a long time.
