### ISSUE TITLE
Logout/Signout inadequately discoverable

### ISSUE THREAD

**Issue by sbts** [vector-im/riot-web#5073]
Hiding that under settings makes it hard to find for users that are running on insecure machines. Perhaps it should be located on the home page, or within the main UI instead. I'd vote the homepage personally

**Comment by lampholder** [comment]
I agree it is far too hard to find at the moment (though I'm not yet sold on the home page's being the place to find it).

**Comment by t3chguy** [comment]
plus homepage can vary between instances so would be an inconsistent place to put it

**Comment by croulibri** [comment]
Definitively agree, it is hard to find.
I would rather prefer logout button to on the top right corner of the window, like in most websites (such as github for instance).

Issue mentioned also at https://github.com/vector-im/riot-web/issues/2984#issuecomment-346377600

**Comment by danlamanna** [comment]
+1 - I had to spend 5 minutes and then search the internet to find this issue to learn how to sign out of the application.

**Comment by Thovthe** [comment]
Fixed with the redesign.  Should we close?
