### ISSUE TITLE
Chevrons on tags can block room count

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5079]
### Description

![image](https://user-images.githubusercontent.com/1190097/30567802-4f86c9dc-9c8f-11e7-85ce-f5a32da6d7ba.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I think this is more a case of 'long room tags can push room count into chevrons', but either way, it's ugly.

Not sure how we address it though without truncating tag names, which is _also_ not super helpful.

**Comment by turt2live** [comment]
A similar issue is tags that are too long: https://github.com/vector-im/riot-web/issues/3332

Although this one is more focused at the "sweet spot" of not wrapping.

**Comment by turt2live** [comment]
Room counts aren't a thing, and the chevrons moved
