### ISSUE TITLE
composer loses focus after typing a bad command

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5086]
e.g. /test and then no composer focus. i think we need to reintroduce the fix which autofocused after dialogs are closed

**Comment by turt2live** [comment]
Related:
* https://github.com/vector-im/riot-web/issues/5078
* https://github.com/vector-im/riot-web/issues/4068
* https://github.com/vector-im/riot-web/issues/3944
* https://github.com/vector-im/riot-web/issues/3508

**Comment by lukebarnard1** [comment]
>I think we need to reintroduce the fix which autofocused after dialogs are closed

This caused a fair few issues. I'd rather fix this case-by-case.

**Comment by t3chguy** [comment]
This seems to work fine for me, though I wouldn't be able to explain why
