### ISSUE TITLE
modular widgets non-obviously doesn't work on <0.12.x shows sorry you do not have permission.. which isn't right :L

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5099]

**Comment by lampholder** [comment]
Is this when you visit a room that's got a widget already attached? What happens?

**Comment by t3chguy** [comment]
Its when you're on <0.12.x and go into Scalar, it says "Sorry you do not have permission..." in the Widgets section, because a newer Scalar loads in an old Riot

**Comment by lampholder** [comment]
Ugh :\

I wonder how much we can do about that now, but it's certainly something to consider as Scalar continues to evolve :\

**Comment by t3chguy** [comment]
yeah unless Scalar can access the version of the Riot accessing it

**Comment by turt2live** [comment]
I'd guess that Scalar is interpreting no response from Riot as no permission (as Riot doesn't respond if it doesn't understand). Going forward, Riot could be made to respond with an error or expose some kind of version endpoint to determine the scalar API version. The only reason I'd recommend making the scalar api version and riot version different is to give the scalar api a chance to be standardized.

**Comment by turt2live** [comment]
Sorry Riot v0.12.x and lower, you have other problems.
