### ISSUE TITLE
Current password label is not translatable

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5105]
### Description

On the settings page there is a field called "Current password". The text is hard-coded into https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/views/settings/ChangePassword.js#L211.

### Steps to reproduce

- Switch to a language with 100% coverage (e.g. Deutsch).
- Notice that the field still says "Current password" in English.

### Version information

Current git develop branch.

**Comment by t3chguy** [comment]
good spot!

**Comment by t3chguy** [comment]
whats even weirder is the string has already been translated!!

**Comment by pafcu** [comment]
Not so weird. The policy is to add strings manually to the translations, right? So whoever added the string did exactly that, but just forgot to add the `_t()` call.

**Comment by t3chguy** [comment]
yeah but there's a script to catch stale translatrions

**Comment by pafcu** [comment]
There is. But it has loads of false positives, so it's probably not used much.
