### ISSUE TITLE
Multiline comments get mangled by RTE

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5106]
'pressing shift enter makes a new line, and every character i type after that creates a newline too', says nepugia (e.g. see https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15061050331544177CozaI:matrix.org), Firefox 55 64bit freebsd

**Comment by uhoreg** [comment]
FTR, I cannot reproduce in my Firefox 55 32bit Linux.  nepugia says that they do not have any Firefox extensions installed other than uMatrix, which is not blocking anything on the page.

**Comment by lampholder** [comment]
P2 minor just 'cause this doesn't seem to be affecting many people - lets leave this open here until we learn more.

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it either (on Riot Web 1.6.1, Firefox 76).

**Comment by t3chguy** [comment]
Composer has been replaced since this issue so am presuming fixed
