### ISSUE TITLE
cannot un-Admin yourself through RightPanel mod tools

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5107]

**Comment by lampholder** [comment]
Creating a brand new room (to verify this) I was shown as having power level: **Custom of 100** which looks odd to me.

And also this power level couldn't be changed, so yes it looks like something is awry here.

**Comment by lukebarnard1** [comment]
Apart from there not being any local echo and sometimes the change taking a long time, this looks fine.

I suggest we open a new issue if we care about putting a spinner on the dropdown to indicate waiting for the new power levels arriving in the /sync.
