### ISSUE TITLE
Allow specifying home server in URL

### ISSUE THREAD

**Issue by jooize** [vector-im/riot-web#5112]
## Scenario

Group wants to run home server for Matrix IDs with their domain, but rather trust the officially hosted Riot client. They want to redirect `chat.group.com` to https://riot.im/app/#/login and have `matrix.group.com` already entered into home server so nobody has to write it manually.

## Solution

https://riot.im/app/#/login?home_server=matrix.group.com

`chat.group.com` → `https://riot.im/app/#/login?home_server=matrix.group.com`

Would you agree to assume HTTPS and port 8448? Otherwise, how should it be done?

**Comment by uhoreg** [comment]
This should already be possible using the hs_url parameter (https://github.com/matrix-org/matrix-react-sdk/pull/716).  (e.g. https://riot.im/app/#/login?hs_url=..., where the parameter value is whatever you would put in the custom homeserver field)

**Comment by danger89** [comment]
Looks like this `hs_url` parameter isn't working at all.. Please, tell me what I'm doing wrong:

https://app.element.io/?default_hs_url=https://matrix.melroy.org#/login

**Comment by uhoreg** [comment]
@danger89 the parameter broke during the redesign a couple of years ago.  The issue to follow is https://github.com/vector-im/element-web/issues/5469
