### ISSUE TITLE
Widgets get unvoluntarily removed by room moderators and admins

### ISSUE THREAD

**Issue by almereyda** [vector-im/riot-web#5115]
### Description

Since the introduction of widgets into some of our rooms, other moderators and administrators of those repeatingly remove widgets without wanting to, as they believe the X will fold it, instead of removing it.

### Steps to reproduce

- add a widget to a room with other moderators *that don't know about widgets, yet*
- wait a while, until someone will try to fold it, and unexpectedly removes it

There could be a confirmation dialogue repeating the intent, offering an OK button and allowing for cancel.

### Version information

`riot-web v0.12.3`

This touches with:

- #4839 (#4834)
- #4844

**Comment by pafcu** [comment]
Perhaps change the X to a more universally understood icon, such as a trashcan?

**Comment by lampholder** [comment]
We do need to spend some time refining the UX, but either a trashcan icon or a confirmation 'are you sure you want to remove this widget from this room?' would help to mitigate this particular problem.

**Comment by almereyda** [comment]
To also resolve #4839, it may be also good to

* [ ] create an issue for an option for collapsing widgets upon channel display by default, and on a per-user basis.

**Comment by rxl881** [comment]
I have addressed the icon (trash can) and warning / confirmation dialog in:
Riot-web: https://github.com/vector-im/riot-web/pull/5397
Matrix-react-sdk: https://github.com/matrix-org/matrix-react-sdk/pull/1520

**Comment by uhoreg** [comment]
@rxl881 since the PRs are merged, can this be closed?

**Comment by rxl881** [comment]
@uhoreg - Yes. Thanks for spotting :)
