### ISSUE TITLE
Icons for buttons don't appear, but accessible at URL

### ISSUE THREAD

**Issue by jooize** [vector-im/riot-web#5118]
https://chat.nubits.com/#/room/#chat:nubits.com

![screen shot 2017-09-25 at 16 25 12](https://user-images.githubusercontent.com/719371/30813651-4b88713a-a20e-11e7-972c-417f0aa9e05b.png)

https://chat.nubits.com/img/icons-home.svg

**Comment by uhoreg** [comment]
@jooize It is probably a web server configuration issue, such as #3501

**Comment by MTRNord** [comment]
sounds like blocked iframes

**Comment by jooize** [comment]
Removed `add_header  X-Frame-Options DENY;` from my Nginx configuration, and now they show up.

Thanks!
