### ISSUE TITLE
creating a room from bottom left menu creates a direct chat

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#5122]
clicking on the 'create room' button obviously. Click on the button, configure the room (like name, avatar), invite a bunch of people, and here we go

**Comment by lampholder** [comment]
That's very odd - I can't reproduce it, but the automatic application of the _direct chat_ flag seems like something that can be racey/somehow non-deterministic :(

**Comment by lampholder** [comment]
Aaaaand it just happened to me (I think).

On /develop (Chrome, Windows) I created a room and invited one member - at some point in that journey it became a direct message.

**Comment by ara4n** [comment]
I've been having the opposite problem; i've been doing 'start chat' and having it turn up as a normal room.

**Comment by turt2live** [comment]
to be honest, I've not seen this in well over a year. If others have, please re-open.
