### ISSUE TITLE
'forward message' button should surely quote the message being fwded

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5124]
otherwise it looks as if the forwarder sent it in the first place

**Comment by t3chguy** [comment]
How would that work for images/files/other?

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4747

**Comment by t3chguy** [comment]
/me thinks of a field within `m.room.message` events giving details of the original event and sender

**Comment by t3chguy** [comment]
@turt2live completely forgot that was a thing - ty
