### ISSUE TITLE
failure to switch rooms (FF Quantum)

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5128]
Not sure if this is an issue with FF Quantum (FF57), or some strange bug that hasn't been encountered before.

I was switching rooms in Riot running under FF Quantum, and suddenly it stopped switching.  The URL fragment in the address bar changed, and the new room was selected, but the timeline did not change.  I couldn't even open the user preferences to submit a bug report. 😞   So here is a C+P of the JavaScript console, in case anyone can make any sense out of it.  AFAICT, somewhere around line 672 is the start of the problems.

https://matrix.org/_matrix/media/v1/download/matrix.org/IAraArUXmgwZYZKMNGKfdKDo

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox developer edition, 57.0b3
- **OS**: Debian
- **URL**: riot.im/app (0.12.4)

**Comment by lampholder** [comment]
P2 for now; lets see if other people experience the same problem. Troubling :\

**Comment by non-Jedi** [comment]
I've had something similar when opening integrations menu for a room where it couldn't be closed but url would change. Didn't file a bug since I'm using a non-supported browser. Browser is qtwebengine based, so it doesn't share code with firefox; if this is same issue, it's for more than just FF.

**Comment by turt2live** [comment]
@uhoreg @non-Jedi are either of you still seeing this?

**Comment by non-Jedi** [comment]
I have not seen this in the past few months.

**Comment by jryans** [comment]
I also haven't seen anything like this lately. Let's close for now, but feel free to reopen if it comes back.
