### ISSUE TITLE
Devtools: Per-room option to show unrecognized events

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5132]
### Description

A toggle per-room to show unrecognized (custom) events in the timeline would be nice. Useful for debugging IoT devices, new state events, etc. Ideally this would be per-room to avoid the browser problems in rooms with spammy custom events (IoT).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This is https://github.com/matrix-org/matrix-react-sdk/pull/295

**Comment by t3chguy** [comment]
(without per-room granularity)

**Comment by turt2live** [comment]
Probably also arbitrarily blocked on https://github.com/matrix-org/matrix-react-sdk/pull/1516

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/2993 adds a version of this idea. It's not currently per-room at the moment, but it could be adapted that way if desired in the future. Let's consider this fixed and adapt from there.
