### ISSUE TITLE
Devtools: Editing a state event and hitting 'back' brings you to the main page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5134]
### Description

It should probably bring you back to the event page

### Steps to reproduce

- Open /devtools
- Explore room state
- Select an event
- Click 'Edit'
- Click 'Back'

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
this is slightly trickier to fix, as by then the previous component is unmounted
grr
