### ISSUE TITLE
nick handling of '@freenode_Pangolin`:matrix.org' fails due to the backtick

### ISSUE THREAD

**Issue by sbts** [vector-im/riot-web#5135]
The result is the backtick commences an inline code block, meaning the simple form of the nick
```
Pangolin`:
```
becomes
[Pangolin`](https://matrix.to/#/@freenode\_Pangolin`\:matrix.org):

as displayed once the event is posted

This can be reproduced easily enough by clicking on, or tab completing a nick containing a single backtick

Specifically this is seen running Chrome on Linux
against riot.im/develop

**Comment by turt2live** [comment]
Similar, if not duplicate of, https://github.com/vector-im/riot-web/issues/4867

**Comment by sbts** [comment]
@turt2live Yep, looks like it's fundamentally a duplicate.
Although the original report was related to a trailing backslash, which was fixed.
As #4867 is still open, I'll close this one
