### ISSUE TITLE
'failed to set user avatar' error dialog leaks access token

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5139]

**Comment by t3chguy** [comment]
leaks to what, Piwik?

**Comment by ara4n** [comment]
it leaks it to the user, in the error dialog.

**Comment by t3chguy** [comment]
It literally passes through `err.message` :L
https://github.com/matrix-org/matrix-react-sdk/blob/6a53b7b149361d2d05ff6e435d46a9968aa6602d/src/components/structures/UserSettings.js#L424

**Comment by t3chguy** [comment]
what would be desired to show here, to still show a little bit of detail, should it just strip the Token?

**Comment by t3chguy** [comment]
> leaks to what, Piwik?
seems like a dumb Q but the Dialogs are what feed Piwik sooooo...
