### ISSUE TITLE
setting room name to To🅱️ic leads to Toic

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5144]

**Comment by lampholder** [comment]
Is this already fixed?

Actually it seems to work on /app as well as /develop, so maybe it's somehow a browser/platform thing?

It worked fine on Ubuntu/Chrome 60.0.3112.78

**Comment by t3chguy** [comment]
So it seems like it depends on where I copy the 🅱️ from, some get consumed some don't
throwing it down to browser intuition
