### ISSUE TITLE
Devtools should get a setting to enable and then a button

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5151]
or put into Room Settings, otherwise you cannot use it in rooms you have no permission to talk

**Comment by pafcu** [comment]
Seems the correct thing to do is to actually allow slash commands even in rooms where you do not have permission to talk? E.g. it still makes sense to also allow /join /part /nick etc.

**Comment by t3chguy** [comment]
Needs design then, seems that by design it completely removes the input box

**Comment by turt2live** [comment]
A button would be better. There's not much value to redesign the chat input for rooms which you cannot speak. For example, there's 2 other ways to leave the room, and you can join a room a few other ways, etc.

**Comment by turt2live** [comment]
another option is to just have `/devtools` take an optional room ID

**Comment by Half-Shot** [comment]
This got done.
