### ISSUE TITLE
Can't deop self on Riot web

### ISSUE THREAD

**Issue by thekyriarchy** [vector-im/riot-web#5153]
### Description

Using /deop on one's own username only seems to work on Riot Android, not Riot web. I haven't tried this on iOS, but this behavior has been consistent since I started using Riot many months ago. 

### Steps to reproduce

- Be admin of a room
- Try to /deop yourself
- See error

**Comment by turt2live** [comment]
I can't reproduce this. What was the error you saw?

**Comment by lampholder** [comment]
I didn't realise you could use `/deop` to achieve something that isn't possible in the UI (I don't think it's possible for an admin to deadmin themselves in the user details panel).

I also wasn't able to reproduce - `/deop` just set my power level to 0.

**Comment by thekyriarchy** [comment]
The error I was getting was permission denied unable to deop users at the same power level as me. Now I am having trouble reproducing even though this has happened over the past several months. Maybe it is related to #2360 and therefore only affects some rooms?

**Comment by lampholder** [comment]
Is #2360 the right issue? I can't see how it's related :\

**Comment by t3chguy** [comment]
If your access token had expired you would have had a completely different error @thekyriarchy

**Comment by thekyriarchy** [comment]
Oops, meant to link to https://github.com/matrix-org/synapse/issues/2360

updated my comment above

**Comment by thekyriarchy** [comment]
I still haven't been able to reproduce this, so I think I'll close this bug now. I can reopen if I encounter it again and can provide better details. Conceivably could've been encountering an error with messing up the capitalization on my username (#617), but I don't think so because that would give a different error and I rarely camel case my username
