### ISSUE TITLE
custom widgets should warn if they can't embed when you try to hit save, not when you try to view...

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5155]

**Comment by rxl881** [comment]
This should now be addressed. When you attempt to add a custom widget Scalar checks if content can be embedded and displays an error if not. I have added a checkbox (which can be unticked) to bypass this check. See attached screenshot.

<img width="1009" alt="screen shot 2017-12-05 at 22 16 38" src="https://user-images.githubusercontent.com/6763606/33633862-1ef71160-da0a-11e7-935c-682a36166e0c.png">

**Comment by turt2live** [comment]
Throwing the raw header back is probably going to cause even more questions. Translating it to something like "This content cannot be embedded because the website does not support displaying the content in Riot.im" is likely going to be better.
