### ISSUE TITLE
Difficulty filtering users in RHS

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5156]
### Description

It briefly shows your filter, then it goes back to showing everyone.

### Steps to reproduce

- Open a room
- Filter room members
- Wait a short while

Possibly may be related to updates in the RHS? 

Log: not sent   

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Trying to reproduced this, I experienced a wide range of amounts of time between typing my filter query and the filter resetting - everying from nearly 2 minutes down to almost instantaneous.

I tried eyeballing the console to see if the filter resetting coincided with anything happening there, but it didn't seem to.

For clarity, by 'filter resetting' I mean 'my filter term stayed in the filter box but the list of members stopped being filtered'.

**Comment by turt2live** [comment]
@lampholder I think this should be higher severity or higher priority. It's becoming increasingly frustrating to use Riot for mundane tasks because of this bug.

**Comment by lampholder** [comment]
Hmm, I can appreciate that :(

I can't even imagine it's that hard to fix - whatever's refreshing the component just needs to make sure the filter is still honoured.

**Comment by t3chguy** [comment]
Think I have this fixed, just testing now

**Comment by ara4n** [comment]
looks good!
