### ISSUE TITLE
maybe sessions makes more sense to people than devices

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5159]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15071030174113448SwKsp:matrix.org

**Comment by lampholder** [comment]
If I understand correctly, the source of the 'device' confusion is that, on one _physical_ device, you can sign in, sign out (disposing of your e2e encryption keys) and sign in again, resulting in two _device ids_. Is that right?

Session is an interesting alternative; it might well be closer to the concept we're trying to represent. My fear is that it might go too far in the opposite direction - people might intuitively expect a session to represent the literal common-parlance session of use of the app.

I think you're right that the _device_ term is problematic; I think we need to think carefully about what we might replace it with.

**Comment by t3chguy** [comment]
That is right, plus you have have multiple "devices" on one *physical* device in alternate clients.

I had not considered session being a single session of use, most webapps I can think of use the term sessions when managing other devices signed in so not sure on that front

**Comment by aaronraimist** [comment]
This seems to be more or less solved on develop https://github.com/matrix-org/matrix-react-sdk/pull/3980
