### ISSUE TITLE
cmd-m should be the minimize shortcut but instead it toggles markdown in the text box if it's focused

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5165]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15071520564891939pgear:matrix.org

Seems to apply to mac os riot desktop

**Comment by lampholder** [comment]
We fall into this trap quite a bit 😢 

I guess there are a few approaches we might consider:
    - getting a list of common convention keyboard shortcuts and committing to not reusing them
    - providing keyboard shortcut customisation (perhaps only for electron) to let people work around these problems themselves

**Comment by t3chguy** [comment]
CIDER doesn't use Cmd-M for markdown toggling (instead using `/plain`)
