### ISSUE TITLE
Change of display name notice contains redundancy

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5171]
When a user changes their display name the string `'%(senderName)s changed their display name from %(oldDisplayName)s to %(displayName)s.'` is displayed. However, `%(senderName)` is often already the new display name, and something like 'Bob changed their display name from Billy to Bob' is shown (i.e. Bob is mentioned twice).

The phrasing is a bit misleading as it was _Billy_ who changed their display name. When the message is displayed, no one yet knows who 'Bob' is, so you have to jump to the end of the message to figure out who it is that changed their display name. It would be more logical to say something like '%(oldDisplayName)s changed their name to %(displayName)s.'.

**Comment by pafcu** [comment]
Similarly also 'Bob set their displayname to Bob'

**Comment by t3chguy** [comment]
I think where it differs is when disambiguation is applied

**Comment by pafcu** [comment]
Perhaps the "redundant" form should only be displayed in these cases then?

**Comment by lampholder** [comment]
It _does_ look clunky, but it's also not immediately obvious what would be better (or, at least, better enough to commit to doing it).

**Comment by ara4n** [comment]
`%(oldDisplayName)s changed their name to %(displayName)s` would work for me.
