### ISSUE TITLE
setting powerlevel for 'send message' to Admin sometimes lets users send to a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5177]
i have an example of this happening in a new room which is created; has power level changed to Admin for message sending; then a random user joins and can send (and redact).

**Comment by richvdh** [comment]
In the example given, the power_level has `"events_default":0`, ie random users can send messages.

I can see that at some points the events_default has been set to 100, but not at that time - which might be user error or a client error.

**Comment by t3chguy** [comment]
Closing as not reproducible
