### ISSUE TITLE
Event tile for ending a video call shows "unknown failure"

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#5178]
<img width="398" alt="screen shot 2017-10-07 at 10 11 02" src="https://user-images.githubusercontent.com/6750344/31306043-f2839f72-ab47-11e7-9f68-70144bfc4076.png">

**Comment by lampholder** [comment]
Presumably this is just cosmetic? And hopefully easy to fix?

/me wonders how user hangup ever got classified as 'unknown failure'

**Comment by turt2live** [comment]
I believe this was https://github.com/vector-im/riot-android/issues/2623
