### ISSUE TITLE
was unable to copy-paste a ! command into RTE

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5182]
Tried to copy paste https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1507417355483jWnPy:t2l.io (`!alias #telegram_-1001063183002:t2bot.io`) from the timeline into the RTE on Chrome 61, but nothing happened. Presumably some weird HTML clipboard problem

**Comment by ara4n** [comment]
ah, i had MD mode disabled (i.e. pure RTE turned on), which may have had something to do with it....

**Comment by lampholder** [comment]
Yep - pastaing in `!alias #telegram_-1001063183002:` works fine - it's just if the clipboard contains an anchor tag (including the autolinkified t2bot.io) the RTE mode composer dumps it.

**Comment by ara4n** [comment]
fixed by matrix-org/matrix-react-sdk#1890
