### ISSUE TITLE
Opaque Username Password Limitations on Account Registration

### ISSUE THREAD

**Issue by robertandrewsmith** [vector-im/riot-web#5190]
### Description

Hi, I registered with Riot.im via the website and received a verification token by email to confirm registration, but I could NOT login. After I copy/paste the link provided in the verification email, then choose my Matrix ID (or by email address), then submit my login credentials, the webpage returns an invalid username/password message.

The email address, which in my case resembles UPPERlowercaselettersnumbers0123456789@somedomain.com, does receive email from no-reply@riot.im .  Yet, on the riot.im webchat, I entered my username, which prompted me to set a password and email address to associate, I get an invalid email address message.  

### Describe how what happens differs from what you expected.

**I should be allowed to register and use Riot.im with complex passwords and email addresses** 

⦁	If there are restrictions on the character length of an email address, kindly please remove them.
⦁	If there are restrictions on the character length of a password, kindly please remove them.
⦁	If there are restrictions on the characters that one can use for a password (or username), please identify this on the registration page.

### Version information

- **Browser**: Chrome, Firefox, & Edge (latest versions as of date of this issue)
- **OS**: Windows 10 Pro

**Comment by lampholder** [comment]
Hi @robertandrewsmith - are you happy to talk a bit more about your registration experience? You shouldn't be falling foul of any hidden password/username character/length/complexity rules - our restrictions are very limited (min password length of 6 characters).

We have a couple of separate registration flows:
    1. https://riot.im/app/#/register
    2. choosing a mxid via the dialogue that looks like this:
    ![image](https://user-images.githubusercontent.com/1922197/31452703-a0d0a040-aea7-11e7-945b-49b9f58c7073.png)

Which one were you using?

**Comment by robertandrewsmith** [comment]
Both. Initially, I registered on https://riot.im/app/#/register but after problems, posted the github issue, then chose your other registration flow to bring attention to the registration issue on github.
Both registration flows have failed for me.  Actually, the problem seems to be more with the login not passing my info.  Perhaps character restrictions are set on login

**Comment by lampholder** [comment]
Odd. I was able to follow the https://riot.im/app/#!/register flow by supplying UPPERlowercaselettersnumbers0123456789@adomainiown.co.uk, a username of the form 'testuser.2039840293' and a password - I received my email, clicked the link, completed the CAPTCHA and entered the app successfully.

> Actually, the problem seems to be more with the login not passing my info. Perhaps character restrictions are set on login

Can you clarify? Do you think the login interface is silently dropping some characters from the credentials you supply? Thanks for your help with this BTW :)

**Comment by nrbray** [comment]
Hi,
This could be related:
As nrbray:matrix.org tried the password reset link for my nrbray:matrix.org and checked mail several times over a couple of days but no luck receiving the email confirmation.

**Comment by nrbray** [comment]
Working: generating a new  address in the form: pqr.abc@456xyz.net
Not working: https://riot.im/app/#/forgot_password

**Comment by lampholder** [comment]
@nrbray can I confirm that your previous two comments are the same issue tracked in https://github.com/vector-im/riot-web/issues/5521 (and can therefore be considered resolved?)

**Comment by nrbray** [comment]
@lampholder yes, I have checked my use cases again and these are resolved (I think my error in the first place)

**Comment by wadelee1986** [comment]
I can't  registered account,
how  to resolve this problem ?

My phone: +86 15611084264
      email:  923881393@qq.com

Can you help register a account ?

**Comment by lampholder** [comment]
Uh, sorry I missed your comment from over a year ago @wadelee1986 - did you manage to create an account in the end? The UX issues affecting this issue have now been resolved (on /develop, landing on /app shortly) so I'm going to close this

**Comment by robertandrewsmith** [comment]
Sadly, you never solved out my initial issue and I therefore decided not to use riot.  I might consider trying again if you have since provided a help bubble with all of the acceptable characters for login. Have a nice weekend.
