### ISSUE TITLE
add a `?` under Analytics so users can see what is being collected

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5192]

**Comment by t3chguy** [comment]
First draft, @lampholder opinions:
![image](https://user-images.githubusercontent.com/2403652/32189127-b7cdaaa0-bda1-11e7-94bd-f79169b6e3ed.png)

**Comment by t3chguy** [comment]
imagining there'll be two more two more rows between language and HS URL, Instance (if a riot.im/* one) and RTE on/off)
My instance doesn't tag those, not sure why RTE on/off isn't firing

**Comment by turt2live** [comment]
Having the descriptions be a bit more human readable and a brief overview of the stuff being listed would probably help. Please pardon the markdown mockup, but here's a proposal:

----

## Analytics

The following information is sent to us to help make Riot.im better.
* The page you're using (`https://riot.im/app/#/settings` currently)
* The platform you're on (`Web`)
* The version of Riot.im (`v0.24.2`)
* Whether or not you're logged in
* Your language of choice (`en`)
* Your homeserver's URL (`https://matrix.org`)
* Your identity server's URL (`https://vector.im`)
* Whether or not you're using the Rich Text Editor

----

**Comment by pafcu** [comment]
It should perhaps be spelled out that "page you are using" may also contain the room and user names? I think this is something people might care about.

**Comment by t3chguy** [comment]
@pafcu it actually can't, its redacted

**Comment by pafcu** [comment]
In that case _that_ should be spelled out as it is non-obvious.

**Comment by lampholder** [comment]
I like this a lot.

I'd love for the **analytics** section of the settings page to read something like:

Privacy is important to us, so we don't collect *any* personal or identifiable data for our analytics. [Learn more about how we use analytics]().

For the popup itself, I think we should combine the data layout from @turt2live's suggestion with some wording that makes it clear that we don't track room ids, etc. Perhaps something like:

## Analytics

The following information is sent to us to help make Riot.im better:
* The platform you're on - `Web`
* The version of Riot.im - `v0.24.2`
* Whether or not you're logged in (we don't record your user name)
* Your language of choice `en`
* Your homeserver's URL `https://matrix.org`
* Your identity server's URL `https://vector.im`

We also record each page you use in the app (currently `https://riot.im/app/#/settings`). Where this page includes identifiable information, such as a room, user or group ID, that data is removed before being sent to the server.

**Comment by t3chguy** [comment]
@lampholder exactly what I needed, I'll have that implemented for review tonight/tomorrow :)

**Comment by pafcu** [comment]
Tiny adjustment:

- Your language of choice: `English`

**Comment by t3chguy** [comment]
@pafcu do we have an exhaustive lookup list? I don't think we do

**Comment by t3chguy** [comment]
oh of course we will, somewhere, whatever feeds the Language Picker

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/32373808-05235ba8-c093-11e7-91ad-53463b50bbf3.png)

Still not resolving the language, but draft 2, comments?

**Comment by t3chguy** [comment]
(it only shows the 2 other analytics options if they're actually being captured, which in the case of my instance they're not being for various reasons)

**Comment by pafcu** [comment]
How about combining platform (which is a "difficult" word anyway) with version and just say "Web (x,y,z)"?

I also suggest having explanations (microcopy) like "We don't record ..." below the actual item and in a smaller font (and perhaps in a lighter font to not draw full attention). This way you can also move the second column closer to the first which makes it easier to read.

How about adding a link to the actual privacy policy as well?

It could perhaps be clarified that this is all just related to Riot the app, and that the HS can collect other info. There is no support for it yet, but it would be _great_ if a HS could somehow link to its privacy policy.

Should it be Community instead of Group?

What about IP-addresses? I believe that EU law classes it as "identifiable information", so is that also not recorded?

**Comment by t3chguy** [comment]
I believe piwik strips the last byte or two out of the addresses

**Comment by pafcu** [comment]
How about browser version and such?

**Comment by turt2live** [comment]
It's still missing the introduction text between the header and the table.

**Comment by t3chguy** [comment]
Piwik actually collects IP (XXX.XXX.0.0), Browser, Operating System and Resolution, wording suggestions appreciated

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/32992067-1be56dba-cd3e-11e7-9323-e1c8249728df.png)
