### ISSUE TITLE
browsing directories on other servers is super-unintuitive

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5194]
If you're not on matrix.org, you have to type into the dropdown which doesn't look like you should be able to type things into.

Apart from the utter lack of discoverability, you have to type! Words! with your fingers! The brutality!

**Comment by turt2live** [comment]
Related:
* https://github.com/vector-im/riot-web/issues/3932
* https://github.com/vector-im/riot-web/issues/3770
* https://github.com/vector-im/riot-web/issues/3769

**Comment by richvdh** [comment]
actually apparently you don't have to type it -  you can add entries to the dropdown via the config.json for the riot-web instance as per https://github.com/vector-im/riot-web/blob/2b7ee756f8945c933050b6c3a451340241c9bab2/config.sample.json#L9.

But if you want to use one that's not on the list, it's deeply undiscoverable.

**Comment by ara4n** [comment]
also related: https://github.com/vector-im/riot-web/issues/2054

**Comment by pafcu** [comment]
It would perhaps be more clear if the placeholder text was something other than "matrix.org". Perhaps "Type a remote server name here".

**Comment by richvdh** [comment]
@pafcu: to be honest, I don't think most people get as far as seeing that placeholder text, since you have to focus the dropdown to see it.

**Comment by pafcu** [comment]
@richvdh Certainly, but it is an _easy_ step in the right direction.

**Comment by r3pek** [comment]
I would just remove it altogether. that combo box makes no sense at all. one would just type the domain and be done with it.

**Comment by Half-Shot** [comment]
Not sure how it was before, but now there is a blinking cursor in the combo box which seems like a good indicator to me that you can type in it. 

@lampholder doesn't seem like a p1 to me, but idk.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/12495

**Comment by turt2live** [comment]
@vector-im/design this is your honorary comment asking to have this looked at (as I hear, you've been nudged elsewhere)
