### ISSUE TITLE
Room should not be highlighted while working with group settings/pages

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5202]
### Description

It looks a bit weird for Riot to be saying you're looking at `#test:matrix.org` but really you're playing with some group settings.

This is similar to having the user settings screen open, although I seemingly can't find the bug for that.

### Steps to reproduce

- Open a room
- Edit/manage/etc a group

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
This is actually blocked on us doing a `NavigationStore` which stores the user's current point in the application. This would be a non-trivial jiggle of things.

**Comment by turt2live** [comment]
A NavigationStore would be the correct solution, although for the purposes of release it might be suitable to have some kind of CSS hack.

**Comment by lukebarnard1** [comment]
`NavigationStore` wasn't needed in the end - although it might be preferable over storing the navigation state across a mixture of different components and stores.
