### ISSUE TITLE
Featuring rooms/users is not discoverable

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5208]
### Description

The cog in the top right is the only place where the featured rooms/users. It took me a while to figure this out, as I was expecting to have a giant "Feature Someone" button considering I have permission to do so.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Interesting - as we work through the settings options for Groups we're trying to establish a 'settings paradigm' that we'll (eventually) use throughout all of Riot.

We are thinking that our settings paradigm will (for all configurable entities):
- click on a cog to enter 'settings mode'
- once in settings mode, changes are persisted on a per-setting basis, i.e.:
    - there is no page-wide 'save' button
    - clicking a checkbox/radiobutton persists changes immediately
    - editing a textbox/area flags that content as 'changed' and prompts for either a save or rollback action (we have some UX mocked up for this)
- click the X to leave settings mode again

However, this _doesn't_ necessarily support the experience you describe above - that is, if 'featuring a user' is deemed to be 'configuring the group' (that's certainly how we've thought of it to date).

What are your thoughts?

**Comment by turt2live** [comment]
For background: I work on a different application that has a different settings paradigm than Riot, so this issue might be some of that bleeding in.

The cog definitely feels the way to go. Riot doesn't have a concept of first-time setup though, which is more where this issue is coming from. This might be similar to https://github.com/vector-im/riot-web/issues/5207 in a way, as I'd imagine a warning of "You have no one featured! [Click here] to feature someone". 

One of the other problems is the cog size vs element size on the page is a different ratio from elsewhere in the app. With the content being overall larger, the cog appears even smaller, making it hard to find.

**Comment by lukebarnard1** [comment]
We've now removed the "featured" sections. We'll reconsider the "saving" paradigm that we want to use app-wide. 

I think clicking the cog, and not having a "save" button would fit the proposed paradigm. Discovery can be considered separately - we need to educate the user that to alter the group members, they could use the cog.

**Comment by lampholder** [comment]
P2 now that the featured stuff is pushed to the next phase.

**Comment by turt2live** [comment]
I'm not sure `cannot reproduce` is fair, given the feature was intentionally removed. If anything, this should be closed instead of being marked as invalid.

**Comment by lampholder** [comment]
Haha, no, sorry - `cannot-reproduce` is occasionally a side effect of `not-release-blocker` + fat hands 😁

**Comment by turt2live** [comment]
I'm going to go ahead and close this given featuring rooms/users hasn't been a thing for a long while.
