### ISSUE TITLE
Should be able to click a group avatar to edit it (like with rooms)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5211]
### Description

When in a room, a user can click the avatar to edit the avatar and other settings. This functionality should be introduced to groups too.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Consistency ftw :D 

Also - I never knew you could do that :P

**Comment by turt2live** [comment]
It's now possible to click the name or short_description, but the avatar remains unclickable

**Comment by lampholder** [comment]
@lukebarnard1 is fixing this as I watch :D
