### ISSUE TITLE
Should be able to use aliases to feature groups in rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5212]
### Description

![image](https://user-images.githubusercontent.com/1190097/31452347-e7fa8d6e-ae6b-11e7-8f1b-fc7a622a87d3.png)

Aren't room IDs supposed to be hidden?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yes, you should.

**Comment by turt2live** [comment]
So... when I reported this I thought I was associating a room with the group, not adding it to the summary. This is a non-issue, and my usability problem is covered elsewhere.
