### ISSUE TITLE
"Failed to add rooms to the summary of +group" - Why?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5213]
### Description

![image](https://user-images.githubusercontent.com/1190097/31452423-1a12daae-ae6c-11e7-862e-39e104c0bf56.png)

The room ID is offtopic. Why did it fail? (power level in room? in any case, please tell me why in the message ;)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I'm going to assume (perhaps recklessly) that this is only to do with _featuring_ rooms (rather than adding them generally) and push it back to the next phase.

**Comment by turt2live** [comment]
It was. I'm going to close this as it is no longer applicable.

**Comment by lampholder** [comment]
Well, we do still intend to feature rooms... I guess we'll discover this again then though if it is still a problem then.
