### ISSUE TITLE
Can't find myself when trying to feature myself

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5215]
### Description

![image](https://user-images.githubusercontent.com/1190097/31452505-57e33716-ae6c-11e7-8101-abec613a8597.png)

It tells me to search by name or ID, so entering `Tr` should autocomplete `TravisR` surely?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I guess it's just mirroring the invite behaviour. Of course, whilst you never want to invite yourself to a room, everybody's going to want to add themselves to groups' featured users lists :)

**Comment by lampholder** [comment]
Downgrading since we've pushed featuring people out to the next phase

**Comment by t3chguy** [comment]
++ this is trivial, literally just the adding of a `includeSelf: true`

**Comment by turt2live** [comment]
I'm going to go ahead and close this given featuring rooms/users hasn't been a thing for a long while.
