### ISSUE TITLE
Clicking on my own user in the featured users list shouldn't ask to start a chat

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5217]
### Description

![image](https://user-images.githubusercontent.com/1190097/31452674-d78ffaf8-ae6c-11e7-8f5c-897c5bda2ce0.png)

It's unexpected to show me a bunch of my 1:1s when I click on my own user.

### Steps to reproduce

- Feature yourself
- Click on yourself

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Wowee, that's crazy :)

**Comment by turt2live** [comment]
Closing this as featured users aren't a thing anymore.
