### ISSUE TITLE
404 on group should say "group not found"

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5218]
### Description

![image](https://user-images.githubusercontent.com/1190097/31453359-1fe1eb84-ae6f-11e7-872a-5efdf3049ed4.png)

This error doesn't really make sense. I know the group doesn't exist (yet), but most people would probably see this as an error. 500 errors should still be reported in this way, but 404 should have slightly different language.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Looks like this is fixed - it now says "Community +whatever:whereever.foo not found"
