### ISSUE TITLE
A (valid, functioning) call to /_matrix/client/r0/rooms/{roomId}/invite returns {}

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5219]
Could it return an eventid? @patroniser could then maintain a (admittedly distasteful) map of invited emails to event ids (supporting a chain of email->event id; event id->token; token->resolved mxid).

**Comment by turt2live** [comment]
This is a spec problem. Opened https://github.com/matrix-org/matrix-doc/issues/1887
