### ISSUE TITLE
No hover effect on group members (RHS)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5221]
### Description

The cursor changes, but it feels too different from how room members work. A similar effect (if not the same) would be nice.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Consistency ftw!

**Comment by turt2live** [comment]
Closing this in favour of #5349
