### ISSUE TITLE
Purple invite hard to see on dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5222]
### Description

![image](https://user-images.githubusercontent.com/1190097/31456598-80b25900-ae77-11e7-992c-177f09bb198d.png)

A slightly lighter color would be nice.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yeah, that doesn't stand out well at all.

**Comment by turt2live** [comment]
This was made red.
![image](https://user-images.githubusercontent.com/1190097/33243097-afeae1d0-d29c-11e7-9902-5dfbdd05c5d5.png)
