### ISSUE TITLE
No indication of successful group invite sent

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5223]
### Description

Something like the RHS saying "Invited members" or similar would be helpful. Currently the invite is sent and zero feedback is received.

### Steps to reproduce

- Send a group invite

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This is on @lukebarnard1's todo list :D

**Comment by turt2live** [comment]
I'm closing this as https://github.com/matrix-org/matrix-react-sdk/pull/1459 has landed. I'll move the RHS stuff into https://github.com/vector-im/riot-web/issues/5228
