### ISSUE TITLE
Cannot view group or respond to group invite over federation

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5225]
### Description

I sent an invite to `@turt2live:matrix.org` to join `+coolkids:t2l.io` and no amount of waiting allows me to accept the invite.

It loads the RHS members, but does not let me respond.  500 internal server error on getting the summary.

### Steps to reproduce

- Create a group on homeserver1
- Invite someone from homeserver2

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This also affects viewing groups over federation in general.

**Comment by vurpo** [comment]
I tested federation of a group between vurpo.fi and matrix.org, it seemed to work fine (sending an invite to a group, accepting the invite, viewing the group page, flair)

**Comment by turt2live** [comment]
This got fixed in some kind of commit between reporting and now. Weird.
