### ISSUE TITLE
Group invites should look and behave like room invites

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5226]
### Description

Group invite selected:
![image](https://user-images.githubusercontent.com/1190097/31457074-e8d9eba0-ae78-11e7-968e-5619fee7d65e.png)

Compared to a normal invite:
![image](https://user-images.githubusercontent.com/1190097/31457088-f3f2faa4-ae78-11e7-9fd7-e25cd4101baa.png)

I feel it should be the same.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
They look _totally_ different. Group invites should look more-or-less like room invites, for better or for worse.

 - [ ] Sub-list header should read "Group Invites", the group invites occupying their own list
 - [ ] The ( ! ) should be red and should have a tail in the header _and_ the tile itself
 - [ ] The text should read "Invite from ... "

**Comment by lukebarnard1** [comment]
Fixing "Invite from" is slightly trickier because:
 1. "Invite from" is generated in the js-sdk when calculating the room name
 1. We only get the matrix ID of the group inviter

**Comment by ara4n** [comment]
matrix-js-sdk@4382d69 fixes the remaining item here.  The fact it doesn't tell you who invites you is not a huge problem, and we don't even do that for rooms! (if they have an m.room.name)
