### ISSUE TITLE
Hide panel button has a significant clickable area on groups RHS

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5230]
### Description

![image](https://user-images.githubusercontent.com/1190097/31457492-2ae77c64-ae7a-11e7-99f6-481f3dcea55c.png)

The entire area highlighted in red is clickable. This should be much smaller.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Nice spot!

**Comment by turt2live** [comment]
Closing as a dupe of https://github.com/vector-im/riot-web/issues/5311 (as it is more generic)
