### ISSUE TITLE
Clicking on a group member on the RHS puts loading icon above panel header

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5231]
### Description

![image](https://user-images.githubusercontent.com/1190097/31457580-66cbdbd0-ae7a-11e7-8d9e-bb1044dc1ba3.png)

It should probably be the other way around

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
This has apparently gone away
