### ISSUE TITLE
When viewing a member of a group, the 'members' icon should be highlighted and the invite button should be shown

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5232]
### Description

![image](https://user-images.githubusercontent.com/1190097/31457639-936d1c9e-ae7a-11e7-9696-502a5add3999.png)

As pictured, the 'members' icon is not highlighted, and the invite button is just plain wrong.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
@lampholder this issue isn't triaged yet :)

**Comment by lampholder** [comment]
So it isn't! Dunno how it sneaked through :P
