### ISSUE TITLE
Publishing a group does not update your flair in related rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5236]
### Description

There's no clear way to force the flair to update either.

* [x] Invalidate local cache when updating flair
* [ ] Invalidate everyone else's cache when updating flair

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
There's a 30mins cache on the user's own Flair and we do plan on invalidating the cache when the user's group membership changes and publishing a group would be another reason to invalidate it.

**Comment by lampholder** [comment]
For the first phase we're going to invalidate the cache for the local user when they change their flair settings (so they'll see their own flair update in real time).

This won't impact other users who will still not see the change until the ~30 minute cache validity has expired.

Obviously this is NotGood and we want to have something better in future.

**Comment by turt2live** [comment]
The "update flair for everyone else" is a problem for https://github.com/vector-im/riot-web/issues/5235 - the local cache fix works though!
