### ISSUE TITLE
"Join an existing group" button does nothing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5237]
### Description

I can click the + until I get tired, but nothing happens.

### Steps to reproduce

- Open the groups dashboard
- Click the + for 'Join an existing group'

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yep. We need to decide on what's "good enough" for labs, but I feel that a button that does nothing is not really good enough - even a js `alert("Soz - not yet impled");` would be better :P

**Comment by turt2live** [comment]
For the release, it might be best to just not include it for now. Adds a nice changelog entry for a future release as well ("You can now join groups at will!").

**Comment by lukebarnard1** [comment]
The button has been removed
