### ISSUE TITLE
Free-to-join groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5242]
### Description

A nice feature to add would be to have groups that anyone can join on their own free will. For example, +woodworkers:makerspace.com should be open to the world/server to join and declare that they are a woodworker.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This is an intended feature :)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/6399

@lampholder or someone else - copy/pasting the p1 would be appreciated :)
