### ISSUE TITLE
Cannot change group aspects without first setting an avatar, short description, and long description

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5249]
### Description

The avatar should be optional, and not prevent me from entering a description, featuring things, etc.

```
rageshake.js:65 Failed to save group profile 
MatrixError {errcode: "M_UNKNOWN", name: "M_UNKNOWN", message: "'avatar_url' value is not a string", data: {…}, httpStatus: 400}
```

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Updated title: All 3 are required. These should be purely optional.

**Comment by lukebarnard1** [comment]
This is a bug in synapse. I'll look into it.

**Comment by lukebarnard1** [comment]
Synapse is expecting strings for all JSON body values. Riot passes `null` for unset parts of group summary state, when it ought to not pass the key,value at all.
