### ISSUE TITLE
Pill-ify groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5253]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50185338)](https://www.bountysource.com/issues/50185338-pill-ify-groups?utm_source=50185338&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### Description

+test:t2l.io should be a pill in chat.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
When I saw the :+1: I _knew_ it would be pill-enthusiast extraordinaire @lukebarnard1 :laughing:.

It is a good idea, though :smile:

**Comment by turt2live** [comment]
Original post updated to include bounty.

**Comment by t3chguy** [comment]
This is done by the above PR but as part of NV so the bounty should be moved to another issue as you see fit :)
