### ISSUE TITLE
A group's long_description should respect newlines

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5254]
### Description

The following should describe the issue:
![image](https://user-images.githubusercontent.com/1190097/31466762-9640293c-ae95-11e7-8f66-c542b0aa4969.png)
![image](https://user-images.githubusercontent.com/1190097/31466768-9c293e1a-ae95-11e7-9af1-575550885d8b.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Apparently this field supports HTML, which I didn't know. If there's some HTML in the box, use the default behaviour, however if there aren't any, just convert them to <br> silently.

**Comment by lampholder** [comment]
Certainly the current feature needs to be more intuitive, though I might prefer it be an explicit choice to interpret it as plaintext or HTML rather than inferring from the presence of HTML tags.

We might consider this being markdown, too.

**Comment by turt2live** [comment]
Closing this in favour of https://github.com/vector-im/riot-web/issues/5261 - it seems like more people want markdown, and I feel an RTE can provide that better. 

Feel free to re-open if there's disagreement :)
