### ISSUE TITLE
Cannot expand/collapse RHS when editing a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5257]
### Description

I often have the RHS collapsed because of my monitor layout. The RHS cannot be opened from the edit groups page, making it hard to invite then feature someone in one action.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This seemed to work fine for me?

**Comment by turt2live** [comment]
@lampholder 
![image](https://user-images.githubusercontent.com/1190097/31501769-67f3553e-af28-11e7-9a88-4043a064f256.png)

The right edge is the edge of my screen. I have to exit the group editing page, expand the RHS, then go back to editing.

**Comment by lukebarnard1** [comment]
The RHS is now disabled when editing group settings, so it's not useful to be able to expand it.
