### ISSUE TITLE
Add sheriff's badge to admin in a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5258]
### Description

When looking at a group's page, or the group members, the admin of the group should always have a gold sheriff badge. This would be to identify who is in control of the group, and if https://github.com/vector-im/riot-web/issues/5240 is implemented, the people who have the most power.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I _think_ this is the right way to go, but I'd want to think about it a little more - the sheriff's badge already has a meaning in rooms which I would be a little nervous conflating with groups (it might be fine, I just feel... aware that there's an opportunity for confusion here).

**Comment by turt2live** [comment]
Currently the way to find out if someone is an admin of the group is through tribal knowledge (you'd have to just know already). Some kind of indicator would help for when someone wants to have someone added, they know who to talk to.

**Comment by thekyriarchy** [comment]
Agreed on needing an indicator, also agreed other options other than sheriff's badge should be considered. Other sites use a crown. Others use a star. I don't think it matters all too much, since it can change later if needed

**Comment by lampholder** [comment]
Yeah, I haven't actively thought about this at all, but we do _need_ to know who the admins are, and we _can_ change it later, so let's go with sheriff's badges for now.
