### ISSUE TITLE
Adding rooms to the group should show the alias before showing the ID

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5263]
### Description

![image](https://user-images.githubusercontent.com/1190097/31467576-aa161e2e-ae97-11e7-92c3-497de9591059.png)

The alias for this room is not `!mPYrV...`

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
GAH leaking room ids. :nauseated_face:
