### ISSUE TITLE
Hitting Enter or clicking "Join" button in Room Directory should actually join

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5265]
* Go to room directory
* Select moznet or some other bridged network
* Type in #mrflibble or whatever
* Hit enter or the 'join' button
* Get dumped into a room preview for an anonymous room with a helpful "Do you want to join this room?" message.

This is an ILAG regression.

**Comment by turt2live** [comment]
Suspect this is related to https://github.com/vector-im/riot-web/issues/5029

**Comment by lukebarnard1** [comment]
As far as I can tell, we never actually joined when hitting enter or clicking "join".

**Comment by bwindels** [comment]
The end to end tests are (legitimately) failing, as they expect a "Join" button after clicking on a room in the room directory.
