### ISSUE TITLE
Add a bit of left-padding to the flair

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5268]
### Description

It feels a bit cramped currently. A few pixels would probably help.
![image](https://user-images.githubusercontent.com/1190097/31497769-41b1a282-af1d-11e7-9065-3ba0dbe62a7d.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Absolutely

**Comment by lukebarnard1** [comment]
This was a non-issue - I forgot to push some CSS :innocent:
