### ISSUE TITLE
Option to disallow redaction per-room

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5270]
Currently you're always allowed to redact your own messages. Shouldn't we have a setting which allows you to control this?

**Comment by richvdh** [comment]
I have a feeling that setting the power level required to send an `m.room.redaction` might achieve this. (Not to be confused with the `redact` power level, which controls the power level required to redact *other* peoples' messages.)

**Comment by uhoreg** [comment]
somewhat related to #4005

**Comment by richvdh** [comment]
also somewhat related to https://github.com/matrix-org/matrix-doc/issues/720

**Comment by t3chguy** [comment]
Yes setting powerlevel of `m.room.redaction` works - just tested

**Comment by lampholder** [comment]
So @richvdh is the ask to expose a powerlevel for m.room.redaction as a configurable option in settings?

**Comment by turt2live** [comment]
fwiw, there's some brief conversation about this on https://github.com/matrix-org/matrix-react-sdk/pull/1477

**Comment by richvdh** [comment]
> So @richvdh is the ask to expose a powerlevel for m.room.redaction as a configurable option in settings?

yes, in short.

**Comment by richvdh** [comment]
For context, the conversation @turt2live mentions seems mostly of the opinion that we shouldn't let people do this, and instead should always allow people to redact their own messages. This is a somewhat controversial topic.

**Comment by richvdh** [comment]
As per the discussions in https://github.com/matrix-org/matrix-doc/issues/1071, we have decided not to expose this in the client.
