### ISSUE TITLE
"Only server admin can create group on this server" seems to be missing an 's' or 'the'

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5272]
### Description

The intent is clear, but the message is a bit hard to read. Maybe "Only the server admins can create groups on this server" was intended?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Maybe: "Only a server admin can create groups on this server"?

But yeah, needs tweaking to scan properly.
