### ISSUE TITLE
No way to revoke a group invite

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5273]
### Description

In case you invite the wrong person, or they were mean to you after you started inviting them. Would be nice to revoke that invite.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This feels like this could be an expensive release blocker, so let's have a chat about whether we can tolerate its being bumped out of phase 1.

**Comment by turt2live** [comment]
I suspect it would be a fairly rare occurrence, so my vote would be to bump it. (the mitigation would be wait for them to accept then kick them)

**Comment by lampholder** [comment]
I think we decided that it would actually be pretty easy - once the invites appear in the member list properly, it's as simple as 'kicking' that user (with similar UX and slightly different language). Did that turn out to be true, @lukebarnard1?

**Comment by lukebarnard1** [comment]
>Did that turn out to be true, @lukebarnard1?

Haven't put this on my todo, but can do.

**Comment by lukebarnard1** [comment]
Having looked at this, we literally just need to change "remove from this community" to "revoke this invite" :smile:

**Comment by piegamesde** [comment]
> Having looked at this, we literally just need to change "remove from this community" to "revoke this invite" 😄

This is wrong, please reopen.

Removing someone from a room is only possible given the appropriate permissions, however anybody should be able to cancel their invitation of somebody. Notably, you currently can never cancel invites of accounts which are admin.

**Comment by t3chguy** [comment]
> however anybody should be able to cancel their invitation of somebody.

Matrix permissions don't allow to differentiate disinvite and kick permissions. You already linked the relevant issues.

> This is wrong, please reopen.

That'd be a spec issue not a client one.

**Comment by piegamesde** [comment]
Apologies, I only found that it is a spec issue later on
