### ISSUE TITLE
Suggestion: change Members icon in RHS

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5277]
its confusing its the same as the Start Chat icon from LHS. https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15079175231638710LQYyA:matrix.org

**Comment by lampholder** [comment]
Opinion: I don't think the right hand side circle-icons represent the 'tab' concept at all well, so it might be good to rework the tabs more generally (and do a new, different icon at the same time).

Another opinion: I think the 'people' icon actually maps more logically onto the 'members list' than the 'start chat' concept.

**Comment by turt2live** [comment]
Given the start chat button doesn't exist anymore, I'm going to arbitrarily decide this is fixed
