### ISSUE TITLE
Widgets seem to say forbidden if viewed from different riot version (develop/staging/stable)

### ISSUE THREAD

**Issue by MTRNord** [vector-im/riot-web#5284]
### Description

I added a etherpad in #riotweb-translations:matrix.org via Riot develop. It works for me and some other but not for others in the room. The link itself works.

### Steps to reproduce

- Create a Etherpad widget via riot.im/develop
- View it from staging or stable

Users see a permission denied error from scalar and not the widget.

Log: not sent

### Version information of widget creator

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Windows 10
- **URL**: riot.im/develop

### Version information of viewer
- **URL**: riot.im/develop / riot.im/app / riot.im/staging

**Comment by t3chguy** [comment]
Likely different scalar versions don't share scalar tokens, and /app and /develop use different scalar urls

**Comment by MTRNord** [comment]
@t3chguy yep thats somehow what I expected but there should be someway of atleast telling the user or even a fallback way or something

**Comment by inducer** [comment]
Another facet of this is that widgets hosted on `*.riot.im` (Jitsi, Etherpad) simply do not work on self-hosted riot instances. In Firefox 57, I just get a blank widget, and I had to hunt in the developer console to see that the underlying reason is 403 Forbidden error.

**Comment by t3chguy** [comment]
@inducer they should if that self-hosted riot doesn't have the integrations server disabled via config.json

**Comment by inducer** [comment]
@t3chguy Are you saying this *should* or *shouldn't* work for the self-hosted case?

For specificity: I am currently self-hosting riot-web 0.12.7rc3 and synapse 0.23, my config.json looks like this:

``
{
    "default_hs_url": "https://tiker.net",
    "default_is_url": "https://vector.im",
    "brand": "Riot",
    "disabled_integrations_ui_url": "https://scalar.vector.im/",
    "disabled_integrations_rest_url": "https://scalar.vector.im/api",
    "bug_report_endpoint_url": "https://vector.im/bugs",
    "enableLabs": true,
    "roomDirectory": {
        "servers": [
            "tiker.net",
            "matrix.org"
        ]
    }
}
```

If I click "Show Apps" in a room that's purely local to that instance, I get offered a number of apps, including (say) the etherpad at `scalar.vector.im`. If I click "Save" and "Close" in that popup, I get an empty widget at the top of the window, and if I pop open the developer console, I get a message that says

> Loading failed for the <script> with source “https://scalar.vector.im/api/widgets/etherpad.bundle.js”.

If I then dig further to the corresponding http request, I get a 403 error.

**Comment by turt2live** [comment]
@lampholder I feel this should be higher priority. People who use Riot in a power-user sense (/develop) are making rooms broken for non-power users, leading to all kinds of confusion and frustration.

**Comment by lampholder** [comment]
Agreed.

**Comment by MTRNord** [comment]
Happens with selfhosted Dimension Servers with the staging scalar too

**Comment by turt2live** [comment]
It's possible they are related, but I think they're distinct issues. Either way, pinging @rxl881 in the hopes it lands on his radar when he gets back :)

**Comment by turt2live** [comment]
I think we fixed this in the last 2 years.
