### ISSUE TITLE
Add Option to Disable BigEmoji

### ISSUE THREAD

**Issue by composition4** [vector-im/riot-web#5285]
### Description

Users cannot disable BigEmoji if they don't like them cluttering up their chat.

### Steps to reproduce

- Put on sunglasses
- Make emoji with no additional text
- Bask in the blaze of a huge emoji
- Search in options, fail to find disable option
- Remove sunglasses
- Cry yourself to sleep

### Expected Behavior

- Search in options for "Disable BigEmoji"
- Tick "Disable BigEmoji in Chat"
- Dance with joy and sleep soundly

![image](https://user-images.githubusercontent.com/15522744/31578251-3d1b0784-b0eb-11e7-806f-70d8e7d672f0.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (32-bit)
- **OS**: Ubuntu linux 4.10.0-36-generic #40~16.04.1-Ubuntu SMP Tue Sep 19 15:26:08 UTC 2017 i686 athlon i686 GNU/Linux
- **URL**: riot.im/app/#/room/#Cyberpunk:matrix.org

**Comment by ara4n** [comment]
fixed by @t3chguy - thanks!

**Comment by composition4** [comment]
Thanks for the fast response! I love you @t3chguy be mine forever! 🖤 

When can I expect rollout?

**Comment by ara4n** [comment]
it should be live on riot.im/develop already (if not, wait a few more minutes for the continuous integration build to update).  The next formal release will likely be in a few weeks - it won't be in 0.12.7.

**Comment by composition4** [comment]
😭
