### ISSUE TITLE
Filter messages from specific users

### ISSUE THREAD

**Issue by betz** [vector-im/riot-web#5287]
Apparently some integration bot users are annoying some people, while that are useful for others.
A way to keep everyong happy is to be able to mark some users to be filtered from your message stream. Not blocked, just filtered from view in riot. 
Sometime you might toggle between seeing the complete stream  and the filtered stream...

**Comment by turt2live** [comment]
This seems like it could be accomplished with the ignoring functionality, where ignoring someone filters them from your timeline, and unignore puts them back. You'd lose intermediate history, but that seems desirable in this case.

**Comment by betz** [comment]
wait, ignoring functionality?

**Comment by turt2live** [comment]
`/ignore <user id>` and `/unignore <user id>`. Also available by clicking their avatar and clicking `Ignore` on the right side.

**Comment by betz** [comment]
aha! perfect. didn't notice until now.
Thanks.
