### ISSUE TITLE
better parity with slack emoji

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5291]
people spend their lives sending me `:+1:` etc. rather than blindly using emoji-one codes we should make more of an effort to be usable by slack afficionados

**Comment by lampholder** [comment]
You mean you get the raw text `:+1:` (which github obvs helpfully renders as a thumbs-up).

Yeah; this shouldn't be too hard to do.

**Comment by lampholder** [comment]
I think we'd want to support multiple names for emojis, rather than replace `:thumbsup:` with `:+1:`.

**Comment by ara4n** [comment]
This is P1 because it's a horrid experience for people migrating from Slack, and it's trivial to do.

**Comment by lukebarnard1** [comment]
This seems ambiguous to me. Can someone spell this out? Do we:
 1. turn :xxxx: into an emoji when the second ":" is typed?
 1. turn :xxxx: into an emoji when the message is sent?
 1. improve our emoji meta data to include slack aliases?

**Comment by ara4n** [comment]
We're talking about option 3 in this one.

There could be a separate option to interpret the second colon as an autocomplete, but that's pretty evil (right up there with autoturning :) into :smile:) and should absolutely not be on by default - and should be a separate bug, if it isn't already.

**Comment by t3chguy** [comment]
EmojiOne already has a list of aliases which are what Slack uses to refer to their emoji by

**Comment by t3chguy** [comment]
So https://github.com/matrix-org/matrix-react-sdk/pull/2085 has landed which does this somewhat, some improvements are needed as noted in the PR summary

**Comment by turt2live** [comment]
ftr, emojione is being removed (https://github.com/vector-im/riot-web/issues/9281) but this issue still applies in that we need to have more aliases.

**Comment by t3chguy** [comment]
new emoji data helps with this:

![image](https://user-images.githubusercontent.com/2403652/64700634-265c9100-d49f-11e9-9345-8ee00315ed11.png)
![image](https://user-images.githubusercontent.com/2403652/64700641-29f01800-d49f-11e9-9c1c-3cdbbc62e7b1.png)

**Comment by t3chguy** [comment]
as per https://github.com/vector-im/riot-web/issues/5291#issuecomment-341782343 this is resolved, the above referenced PR improves the sorting such that +1 -1 are first results.

**Comment by t3chguy** [comment]
The remaining above issue is tracked as https://github.com/vector-im/riot-web/issues/7256
