### ISSUE TITLE
Use Gemini scrollbar for group pages

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5292]
### Description

Please. The OS scrollbar makes the app feel very split, and clashes really bad with the dark theme (at least on windows).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
Done in https://github.com/vector-im/riot-web/pull/5295 (as intended)
