### ISSUE TITLE
401 on trying to set password

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5294]
I've seen quite a few reports of people getting 401ed when trying to set a password. I think this is when people try to set a password and it works but Riot doesn't realise it has worked, at which point it's stuck because trying again uses the old password.

**Comment by dbkr** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/1554 almost certainly fixes this, as the resulting page refresh will have been racing with setting the password, so a good number of time the request to set the password will have got sent and then the page refresh will go through before the response comes back (or before the js gets around to writing the flag to localstorage).

**Comment by mvz** [comment]
I'm still seeing this.

**Comment by mvz** [comment]
Thanks @t3chguy, that indeed looks like my issue.

In the mean time, I managed to reset my password using the reset password function from inside the Fractal client.
