### ISSUE TITLE
Issues with Riot-bot

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5298]
1. The bot presents itself as Riotbot even though it is called Riot-bot
2. It tries to display an animated GIF even though animated GIFs don't work
3. Said animated gif is somewhat inappropriate (half-nude people are a big no-no in some places).  It also feels out of place given that the videos give a "professional feel", while a half-naked dancing man in star-spangled underwear gives the opposite impression

It would also be nice to have some localization for the bot and provide it in multiple languages.

**Comment by rxl881** [comment]
Thanks for submitting these, @pafcu. 

Hopefully issues 1 and 2 are now sorted (fix deployed).

I've split number 3 out in to a separate issue - https://github.com/vector-im/riot-web/issues/5312.

Localisation request (definitely something that we want) being tracked in -
 https://github.com/vector-im/riot-web/issues/5313
