### ISSUE TITLE
RTE is no longer in labs, need to update help

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5299]
https://about.riot.im/need-help/ states:

> **How do I turn on Rich Text?**

> Rich text gives you extra text editing tools and is still beta. It can be enabled via the main settings cog under the ‘labs’ section, by checking the “New Composer and Autocomplete” box.

This is no longer true.

**Comment by lampholder** [comment]
Thanks for reporting this - I've fixed up the FAQ.
