### ISSUE TITLE
Clicking right panel header (probably) shouldn't hide it

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#5311]
It's really quite frustrating if you try to hit one of the buttons, e.g. notifications, but miss and have the panel disappear completely. There is a dedicated button for hiding the panel, so I don't think the current behaviour is need/intuitive/helpful.

**Comment by turt2live** [comment]
also applies to groups (https://github.com/vector-im/riot-web/issues/5230)

**Comment by lampholder** [comment]
As per #5230 we should significantly reduce the size of the clickable area, probably to something like:

![image](https://user-images.githubusercontent.com/1922197/31709867-30ec6f40-b3eb-11e7-8d35-3b75f32ed464.png)

**Comment by t3chguy** [comment]
There is no longer a dedicated close button, closing is done via clicking the active tab header so closing as this behaviour is now intentional
