### ISSUE TITLE
Warn spectacularly if a room is E2E but not megolm

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5319]
as fun as it is accidentally using Olm (or worse) rooms and having no idea why everything breaks

**Comment by lampholder** [comment]
I don't know how this can come about, or what behaviour we see as a result, but it sounds very glitchy.

**Comment by uhoreg** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4005
