### ISSUE TITLE
uploaded images larger than 2MB(?) fail on getting image info in newer chrome

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5326]
Where by "newer", I mean "Erik's". Chrome throws an error when setting the src of the image to the data URL for Erik's glaring cat gif which is 1.78MB, but not his badger gif which is a couple of hundred KB. Presumably this is a limitation introduced recently.

We can probably load the thing as a blob URL or something to get around this easily.

**Comment by lukebarnard1** [comment]
Link to PR that limits size of data URI in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=69227
