### ISSUE TITLE
Typoing in MD resulted in an invisible message

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5332]
<img width="693" alt="screen shot 2017-10-18 at 19 13 42" src="https://user-images.githubusercontent.com/1294269/31732347-852ff336-b438-11e7-961d-9be1de9d4f40.png">

**Comment by t3chguy** [comment]
seems like the closing ``` is missing?

**Comment by t3chguy** [comment]
This is just commonmark: 
![image](https://user-images.githubusercontent.com/2403652/31733140-ab6e04e4-b432-11e7-8293-d78bba1f4cfc.png)

**Comment by turt2live** [comment]
It may be just commonmark, but it is unexpected behaviour.

**Comment by ara4n** [comment]
yup, it was a typo, but this still seems pretty weird. that said, GFM does it too - i guess it interprets the stuff after a ``` as a directive. so in the end, not really a bug.
