### ISSUE TITLE
pass loading stats through Analytics

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5333]

**Comment by lampholder** [comment]
What stats precisely?

**Comment by t3chguy** [comment]
how long it took to load the app then how long until its usable (finished syncing)

**Comment by lampholder** [comment]
Oh yeah, that'd be good.

**Comment by t3chguy** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming

**Comment by t3chguy** [comment]
Closing in favour of higher priority and more detailed duplicate https://github.com/vector-im/riot-web/issues/6322
