### ISSUE TITLE
Create random-number UUID for each user, decouple from MXID

### ISSUE THREAD

**Issue by heyakyra** [vector-im/riot-web#5336]
### Description

Had a long but good discussion about this here: https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15023053682225048OSKVp:matrix.org

Down the line, it would be great to change the spec to, in two phases, first assign a random-number UUID to every MXID, then begin to use that system rather than MXIDs for everything other than convenient links

### Takeaways (tl;dr): 

- MXIDs are planned to be deemphasized anyways
- Usernames can be changed easily
- This will allow matrix users to optionally have their identities evolve with themselves (marriage, or safety reasons, or other transitions) 
- Currently, Facebook, Twitter, LinkedIn all allow users to change their usernames
- Platforms which do not, like Reddit, encourage throwaways, or account abandonment
- This might make it easier to migrate accounts in down the line (https://github.com/matrix-org/matrix-doc/issues/883)

### Main concerns: 

- Being able to have a contact for ten years if you change MXID 
- Being able to use the same MXID forever

For the first, a contact wouldn't disappear if MXID was changed. It would be similar to a nick change, but with bigger consequences (links would need updating). It doesn't make sense to force people to stick with a MXID they might otherwise feel the need to abandon...in order to keep contacts with an old MXID. 

For the latter, users would be able to have one MXID for life, if they so choose, and they would! Just like facebook, twitter, and the like, if you don't change your username/url (MXID), you can be assured it will continue to work for the person you gave a business card to ten years ago. 

Edit: Looks like this is already being discussed at https://github.com/matrix-org/matrix-doc/issues/494

https://github.com/matrix-org/matrix-doc/issues/496
https://github.com/matrix-org/matrix-doc/issues/915

**Comment by turt2live** [comment]
Closing in favour of the spec side of this issue (see references)
