### ISSUE TITLE
Riot translations/Weblate: Merge failures

### ISSUE THREAD

**Issue by bamstam** [vector-im/riot-web#5345]
The Weblate platform which is used for Riot translations currently sends out a high number of warning emails about merge failures for different languages.

Could anyone look into these merge failures?

**Comment by MTRNord** [comment]
@dbkr I think you might be able to help

**Comment by pafcu** [comment]
I think this is no longer a problem right now? Could this be closed?

**Comment by bamstam** [comment]
yes, currently no problems/notifications
