### ISSUE TITLE
'delete' button in Room list in RightPanel needs to be themed and fixed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5347]
atm it's the wrong X and not themed so it's invisible on dark theme.

**Comment by lukebarnard1** [comment]
The plan is to make a `GroupRoomInfo` anyway, with a similar "Remove this room from the group" and a "Publish this room on the group page?"

**Comment by lukebarnard1** [comment]
@ara4n please could you elaborate as to which icon is the right X?

**Comment by ara4n** [comment]
cancel.svg or cancel-white.svg depending on the theme darkness.  cancel-small is for deleting aliases & things in UserSettings.
