### ISSUE TITLE
It's surprising that the user info you see in RightPanel for groups isn't normal MemberInfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5349]
We seem to have a totally different UI component to view member details when looking at a group member than a room member.  I expect to have the normal profile info (presence; existing chats with them) etc from MemberInfo

**Comment by turt2live** [comment]
Related:
* https://github.com/vector-im/riot-web/issues/5228
* https://github.com/vector-im/riot-web/issues/5221

**Comment by lukebarnard1** [comment]
Also related:
 - https://github.com/vector-im/riot-web/issues/5570

**Comment by t3chguy** [comment]
I guess the issue is that MemberInfo wants a RoomMember object, but for which room should that be given, worse yet, which avatar&displayname should the Group member info pane show? That of the user in the first added room in the group or?
