### ISSUE TITLE
Invites to groups leak the inviter's mxid rather than using displayname

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5357]

**Comment by lukebarnard1** [comment]
Actually, we _only_ get the mxid from the invite, so this would require changes server-side.

**Comment by ara4n** [comment]
(This is in the group preview accept/decline thing)

**Comment by ara4n** [comment]
Conclusion: the group API spectacularly fails to provide the `invite_state` stuff that the room API inviting flow does, so it'd be a whole of work to reimplement that for groups, which is very very very frustrating.  Instead, let's fudge in the client for now by querying /profile for the mxid to fill in the avatar & displayname.  See also https://docs.google.com/document/d/1ZnAuA_zti-K2-RnheXII1F1-oyVziT4tJffdw1-SHrE/edit# :|
