### ISSUE TITLE
Unbreakable topics don't wrap nicely with groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5359]
### Description

![image](https://user-images.githubusercontent.com/1190097/31781185-0c15a6ee-b4b5-11e7-9cbf-86294124a082.png)

See the metalshop room for an example.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This seems to be something that works properly in its on the room directory page.
