### ISSUE TITLE
Can't click camera on group avatar

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5361]
### Description

The content div for the Leave button appears to be blocking the element.

### Steps to reproduce

- Go to the edit group view
- Try to click the camera

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I tried deleting the content div for the leave button but I still couldn't click the camera icon :(

**Comment by lampholder** [comment]
Weirdly this didn't seem to be a problem on @lukebarnard1's machine I think? Still not working on mine, though.

**Comment by lukebarnard1** [comment]
So the top half of the icon works.... probably because it's actually overflowing outside of it's container. Yey. 
![2017-10-24-165028_427x86_scrot](https://user-images.githubusercontent.com/6750344/31953665-7440c404-b8db-11e7-8e4e-e5829691f7fd.png)
