### ISSUE TITLE
(feature request)  Live Support chat addon / minimal, preconfigured UI

### ISSUE THREAD

**Issue by naturallymitchell** [vector-im/riot-web#5363]
### Description

Intended audience is websites that want to give viewers an instant, live contact session.  For businesses using Matrix behind the scenes, this would make the most sense, since clients can have a way to enter it, or at least a room inside of it where they can invite to meet other users in the system.

### Examples:
* https://www.kandy.io/sites/default/files/inline/website-chat.jpg
* http://customericare.com/wp-content/uploads/2015/03/video-chat-support-for-website-admin.png

**Comment by MTRNord** [comment]
might be working with the new group/communities pretty neat (having a group with support agents and auto adding rooms to the group. rooms = users that use the live chat. (just throwing in a idea)

**Comment by lampholder** [comment]
Not something I expect the core team to have any bandwidth to process any time soon, but I think this would represent an excellent usecase for Matrix.

**Comment by MTRNord** [comment]
Might be something for the matrix-whishlist by @turt2live

**Comment by turt2live** [comment]
(added to wishlist as https://github.com/turt2live/matrix-wishlist/issues/98)

**Comment by n1trux** [comment]
I have been made aware of [maubot/supportportal](https://github.com/maubot/supportportal)*, which does exactly this with a client of your choice. There's still a need for a Riot configuration though :)

---

\* _The bot acts as the primary customer support user on Matrix who is invited by users. When the bot is invited, it'll join and announce the invite to a management room, where one of your customer support agents can claim the task by joining the room._

**Comment by tgr** [comment]
How does a bot help here? What would be needed is a web client (maybe a special mode of riot, more likely a separate client) that can be loaded on top of any website and presents a very minimal view to the user (probably only supports 1:1 chat, probably only displays comments).

**Comment by n1trux** [comment]
Of course you need a front end or minimal mode for Riot, but you also need a routing component on the server. Or do you just want to throw everyone into the same room or onto the same support account?

**Comment by t3chguy** [comment]
I actually made a prototoype of a single-room Riot, see https://github.com/matrix-org/matrix-react-sdk/pull/4398#issue-402646116

**Comment by kaktux** [comment]
[i think Rocket Chat has this solved quite nice](https://docs.rocket.chat/guides/administrator-guides/livechat):
Add Managers+Agents
set departments
set triggers (for the livechat widget)
customize appearence

So you can easily integrate a livechat into any website - and customers can login without needing an account into support rooms where agents can wait.

**Comment by kaktux** [comment]
In the matrix blog i just saw https://github.com/nomadic-labs/safesupport-chatbox
An embeddable chatbox built on Matrix.

Both those ideas are quite similar - so maybe they can build upon each other.
The main difference would probably the collection of data you would want in a support chat - but making this optional would fit both use cases.

Have a look.

**Comment by jryans** [comment]
While I agree this an interesting use case to explore, I don't think it makes sense to track here, as it would likely take the form of a separate project, so tracking in separate wishlists and such seems best.

As a another example, @arnav-t is working on this idea for their GSoC project this year: https://github.com/arnav-t/riot-embedded (work in progress).

**Comment by natrius** [comment]
@jryans Well, the separate and single-room riot may be, but the problem with the support-chat is not. In my opinion this issue should be opened again until the support-chat is solved.
