### ISSUE TITLE
Group directory

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5364]
### Description

For homeservers that want to publish this information more clearly (*cough* me). Something like the room directory, but for groups/communities. Should be opt-in for the group.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
:grin: 

Yeah, this is definitely something we need to do.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4429
