### ISSUE TITLE
Option for groups to hide the members list, but still support flair

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5365]
### Description

This is more intended for groups created for application services. It's not ideal that a group would list all 50,000 bridged users in a nice list to be spammed. Instead, the flair should be supported in rooms that opt-in, but the memberlist of the group should be hidden.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
https://github.com/vector-im/riot-web/issues/5389 would help with this

**Comment by turt2live** [comment]
There's API to support this when accepting a group invite, although to my knowledge it isn't possible to support this post-accept. It's supported by sending `{"m.visibility": {"type": "private"}}` alongside the acceptance, and calling the publicize endpoint.

**Comment by lukebarnard1** [comment]
The intention here is to do some for of pagination for the members.

**Comment by turt2live** [comment]
Pagination doesn't solve the privacy concern where someone may wish to have flair, but not be advertised on the group's page.

**Comment by lukebarnard1** [comment]
>in a nice list to be spammed

is the bit I had neglected to read.

We would indeed need an API for setting the visibility after the invite has been accepted.

**Comment by turt2live** [comment]
Closing this as the API supports the feature, however I don't have a use case for exposing it to the UI at all. If someone has feelings otherwise, please open a new issue or petition here and I'll re-open.

**Comment by vibl** [comment]
> Closing this as the API supports the feature

I couldn't find it. It has been requested many times (see https://github.com/matrix-org/matrix-spec/issues/367) but I found no trace of it being implemented.

Can you give a pointer?

**Comment by turt2live** [comment]
In 2018 this was about the Groups/Communities feature and not Spaces. A new issue should be opened for Spaces if desired.

**Comment by vibl** [comment]
Ok, thanks.
