### ISSUE TITLE
Shouldn't be able to add groups to rooms unless you have permission

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5367]
### Description

Users lacking appropriate power level are given the impression that they can add new groups to the room. However, they can't and get a generic error dialog when they try. Riot should prevent this from happening.

### Steps to reproduce

- Create a new room with 2 users: 1 admin, 1 not
- Have the not-admin try to add a group to the room

I would have expected that the list of groups be immutable.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
@turt2live could you clarify that this is relating a group to a room?

**Comment by turt2live** [comment]
@lukebarnard1 
![image](https://user-images.githubusercontent.com/1190097/31905531-bc007942-b7eb-11e7-8c05-7d0fcee7ba49.png)

This section. For example, this is matrix hq, and it is suggesting that I add a group (despite obviously not having permission).
