### ISSUE TITLE
Trying to set a power level requirement greater than your own PL confuses Riot

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5368]
In a room where you're admin, got to settings, enter a custom level of '101' into one of the 'PERMISSIONS' fields, (eg. "To change the topic, you must be a"). Click save. Error message appears. Open room settings again and note that the setting seems to have persisted anyway. Even better, inspect the power levels event in devtools and note that it's showing as 101 there too.

Clear cache & reload, the required power level goes back to what it was before you tried to change it in both places.

**Comment by lampholder** [comment]
Poor confused Riot :confused:

The settings UX honours the weird power level until the refresh, which adds to the confusion.

**Comment by t3chguy** [comment]
![5368](https://user-images.githubusercontent.com/2403652/64018149-8eb48580-cb23-11e9-9eed-66c4b860c583.gif)

This got fixed at some point, but https://github.com/vector-im/riot-web/issues/9679 is in its place :D
