### ISSUE TITLE
Clicking "I already have an account" from the registration page without entering anything gives you an error, requiring a second click.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5372]
### Description

The error should be suppressed and instead bring you to the login page.

### Steps to reproduce

- Go to the registration page
- Click "I already have an account"
- See error
- Click "I already have an account" again

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/app

**Comment by lampholder** [comment]
I couldn't reproduce this by:

- Navigating a fresh incognito browser to https://riot.im/{develop,app}/#!/register
- Immediately clicking 'I already have an account'

It just redirects me to `/#!/login` without showing an error message.

**Comment by turt2live** [comment]
I also can't reproduce this anymore.
