### ISSUE TITLE
CORS error leaks access_token if search results fail

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5373]

**Comment by lampholder** [comment]
@ara4n by leaks do you mean displays it in a user-visible error message?

**Comment by lampholder** [comment]
Related: #5374

**Comment by lampholder** [comment]
Is it possible to have a generic solution to this problem? Is it ever particularly useful to a regular user to pop up the offending URL in the UX?

**Comment by t3chguy** [comment]
This has been fixed by my above PR
