### ISSUE TITLE
Error dialog leaks access_token if UserSettings fail

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5374]
e.g. if you are offline

**Comment by lampholder** [comment]
UGLY:
![image](https://user-images.githubusercontent.com/1922197/31880703-487cbf92-b7d9-11e7-865d-c089e8adcc51.png)

**Comment by lampholder** [comment]
Related: #5373, #4541

**Comment by grahamperrin** [comment]
From `https://github.com/vector-im/riot-web/issues/6331`: 

> …  the application simply 'Can't load user settings' …

– and I'm almost certain that: 

- there was the word CORS in the dialogue
- there was no token in the dialogue.

**Comment by t3chguy** [comment]
This has been fixed by my above PR
