### ISSUE TITLE
No scrollbar on my groups page in Firefox

### ISSUE THREAD

**Issue by thekyriarchy** [vector-im/riot-web#5376]
If you shrink the window such that some (or all) groups don't fit in the space, no scrollbar appears so that you can access them. Chrome doesn't have this issue

firefox 57 ![firefox lacking scrollbars](https://i.imgur.com/kN7tkFH.png)

vs chrome 63

![chrome with scrollbars](https://i.imgur.com/x8L852u.png)

**Comment by lampholder** [comment]
@lukebarnard1 is that even the scrollbar we'd hope to see on the groups page on Chrome? It looks like a... browser native one rather than the styled chap.

**Comment by lukebarnard1** [comment]
The idea will be to part of MyGroups scrollable. If we have an idea of what part that would be (probably Your Communities, right?) then we can go and stick that in (and then the entire `MyGroups` element won't be larger than the thing containing it).

**Comment by lukebarnard1** [comment]
So we've since added a non-native scroll bar to the page, I shall see if this has been fixed.

**Comment by thekyriarchy** [comment]
not fixed for me using riot.im/develop

**Comment by lukebarnard1** [comment]
I've been able to repro locally. I'll see how far I can get with twiddling the CSS.

**Comment by lukebarnard1** [comment]
@thekyriarchy, now that's landed, would you mind seeing if the problem persists?

**Comment by thekyriarchy** [comment]
@lukebarnard1 oops sorry, didn't realize it hadn't landed before. just re-tested and it works!

**Comment by lukebarnard1** [comment]
Apparently this is still a problem on Quantum.

**Comment by ara4n** [comment]
And still doesn't work for Amandine on Chrome 62 on her MBA

**Comment by fredcy** [comment]
I'm not sure if it's the same issue, but when I view the page for a particular community such as `+tezoscommunity:matrix.org` the display is often truncated and does not offer a scroll bar.

<img width="1054" alt="screen shot 2018-03-01 at 10 37 00 am" src="https://user-images.githubusercontent.com/15950/36856803-887f4c9a-1d3c-11e8-849c-7b6c0c988bba.png">

**Comment by lampholder** [comment]
I actually think this should go into 0.15 but adding to 0.14 to drive that conversation.

**Comment by lukebarnard1** [comment]
@fredcy, did you experience this on macOS?

**Comment by lukebarnard1** [comment]
(Closing this is favour of https://github.com/vector-im/riot-web/issues/6294)

**Comment by fredcy** [comment]
@lukebarnard1 Yes, I saw that in Chrome on MacOS.
