### ISSUE TITLE
Group ID should be more obvious as a group ID when lacking flair

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5377]
### Description

![image](https://user-images.githubusercontent.com/1190097/31839339-e58c0ccc-b59d-11e7-8d7c-acd03a5fccd6.png)

This feels like it is part of the display name, albeit slightly out of alignment. The color difference isn't enough at a glance to notice a difference.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I'm not convinced that we want to render _anything_ here for groups without an avatar. It's visually pretty noisy :\
