### ISSUE TITLE
Remove avatar icon for rooms drifts away from avatar

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5381]
### Description

![image](https://user-images.githubusercontent.com/1190097/31847299-983a4338-b5d6-11e7-8c53-0e6f4ac7532e.png)

It should be in the top right of the avatar, not far left and invisible. 

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
So, _that's_ where that extra X came from :P

**Comment by lukebarnard1** [comment]
Fixed by 0e20b20f
