### ISSUE TITLE
"You're not in any communities" should respect dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5385]
### Description

![image](https://user-images.githubusercontent.com/1190097/31864696-272f8f32-b71f-11e7-97b4-752dacf0309a.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 55
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
oops :innocent:

**Comment by lukebarnard1** [comment]
Fixed by d9fa11d0
