### ISSUE TITLE
Riot-desktop v0.12.7 does not show "Groups" feature in Labs

### ISSUE THREAD

**Issue by maxidor** [vector-im/riot-web#5394]
In `riot-web` v0.12.7 release, you are able to turn on the "Groups" feature in Labs.
In the desktop version, same release, there is no Labs and therefore no "Groups" feature.

In both case, here is the version info from settings:
```
matrix-react-sdk version: 0.10.7
riot-web version: 0.12.7
olm version: 2.2.1
```

**Comment by t3chguy** [comment]
in riot.im/app (0.12.7) I get no access to Labs:
![image](https://user-images.githubusercontent.com/2403652/31898969-5f567af8-b812-11e7-89c6-d091b1337fd1.png)


So this is the intention for release code, such as /app and the desktop app.

Try clearing your cache, something is wrong in your instance of /app

**Comment by maxidor** [comment]
Then shouldn't the release force a cache clearing? The issue is still there, even if the intention was to hide it.

**Comment by t3chguy** [comment]
Is it even possible for a webapp to tell a browser to dump its cache ooi?

**Comment by maxidor** [comment]
One of the methods are how caching was set in the headers, file timestamps, etc. So there is a minimum that can be done on the webapp end.

**Comment by t3chguy** [comment]
thats not something riot-web can define, but rather the webserver?

**Comment by maxidor** [comment]
Files timestamps is defined by riot-web when you perform/deploy the release
