### ISSUE TITLE
widget title bar is clickable but doesn't look like it is

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5395]
There is no indication that the widget title bar is clickable to collapse the widget.  The mouse should change to a hand cursor when it's over the title bar to indicate that it's clickable, and maybe add a downward/right-facing triangle (like the one in the room tags headers in the left-hand-side bar) to indicate that it's collapsible.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox Quantum
- **OS**: Debian
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
it now changes to hand cursor.
