### ISSUE TITLE
Clicking on a room in the groups page takes you to /#/room/undefined

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5398]
### Steps to reproduce

- go to a /#/group/+matrix:matrix.org
- click on any room under the "Rooms" section on that page
- look at the address bar

Describe how what happens differs from what you expected.

I would expect to be taken to the room that I clicked on.

Log: not sent    

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 57.0b10
- **OS**: Debian
- **URL**: riot.im/develop (c7d18ff52ed1-react-e023aa9a10f4-js-b0b50f4ef91c)

**Comment by turt2live** [comment]
Possibly related to https://github.com/vector-im/riot-web/issues/5401
