### ISSUE TITLE
Clickable area around the display name should be reduced

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5400]
### Description

Currently the clickable area is fairly large, leading to the occasional accidental mention to land in the composer. The red box highlights the approximate area for which the user can click.
![image](https://user-images.githubusercontent.com/1190097/31907102-17a5f110-b7f0-11e7-89dc-235a239d753b.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by aidalgol** [comment]
I tried to fix this by moving `onClick={props.onClick}` in `matrix-react-sdk/src/components/views/messages/SenderProfile.js` from `<div className="mx_SenderProfile" …` to `<span className="mx_SenderProfile_name">`, but that had no effect.  (I'm completely new to React, so I'm still stumbling around.)

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2653
