### ISSUE TITLE
Room directory in groups are missing avatars

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5401]
### Description

Note: I don't have permission to set `m.room.related_groups`, which may be part of the cause for the bug?

![image](https://user-images.githubusercontent.com/1190097/31907434-0a2f730c-b7f1-11e7-8ffb-4248262d3333.png)

### Steps to reproduce

- Create a group
- Add #offtopic:matrix.org to the group via the groups interface (not m.room.related_groups)

Page refreshes, navigation, etc did not fix the issue. There's no obvious errors in the console or network pane either.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I seem to get a mixture - sometimes the avatar loads right away, sometimes it takes a refresh. Always seems to get there in the end though - both federated and unfederated.

**Comment by turt2live** [comment]
@lampholder I'm going to argue that this is a release blocker because it looks ugly and is very user-facing.
