### ISSUE TITLE
Add rooms to group UX in bottom right gets wrapped unpleasantly.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5406]
![image](https://user-images.githubusercontent.com/1922197/31934439-031cc084-b8a4-11e7-84b2-f8ac20051526.png)

Maybe something more like:
![image](https://user-images.githubusercontent.com/1922197/31934575-654a22a6-b8a4-11e7-8f5c-9dcbf4ac7c43.png)

**Comment by lukebarnard1** [comment]
fixed by a747a78e
