### ISSUE TITLE
Messages can (still) be sent in the wrong order after a connection outage

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5408]
It looks like there can be a race of sorts between messages which are stuck waiting for a server response (during server problems) and those which are explicitly being queued by riot-web due to riot realising that the server is unavailable. As a result, the final ordering of the messages ends up wrong.  Not sure if the out-of-order messages are those sent before or immediately after the outage.

Somewhat related to #639

**Comment by Nostradamos** [comment]
Happend to me yesterday when there was a huuuge lag. First time i noticed this behaviour.

**Comment by ara4n** [comment]
this is driving me mad. pretty much every time i send a message whilst on bad connectivity, i end up with the first one failed and the next one pending.  The pending one then gets sent, but the failed one is stuck failed until i manually resend it, meaning the ordering gets reversed and there's nothing whatsoever i can do  :(

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/issues/781
