### ISSUE TITLE
'** Unable to decrypt: Unknown encryption algorithm "undefined". **'

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5411]
I've seen this a few times recently - it's happening because the creator is sending an `m.room.encrypted` with empty `contents`. No idea why it's happening - could do with a rageshake from the sender.

**Comment by uhoreg** [comment]
somewhat related to https://github.com/vector-im/riot-web/issues/3744 (though in the case of a redacted message, the empty `contents` is to be expected)

**Comment by richvdh** [comment]
ohhhh *headdesk* they've been redacted. Thanks @uhoreg!
