### ISSUE TITLE
the text you get when 4+ people are typing is missing i18n

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5412]

**Comment by pafcu** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1525 ?

**Comment by pafcu** [comment]
@ara4n I think this should be fixed by matrix-org/matrix-react-sdk#1525. Could be closed?

**Comment by turt2live** [comment]
Can confirm this has been fixed (thanks #offtopic). Was too brief to get a screenshot.

**Comment by ara4n** [comment]
\o/ thanks!
