### ISSUE TITLE
Scrolling performance is lagging

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5419]
### Description

Trying to catch up on room history leads to the timeline jumping and generally feeling sluggish. The time between me scrolling down and the timeline actually scrolling is noticeable enough to be jarring.

Part of this performance issue may be related to the screen resolution at which I have Riot.im (1200x1920 / portrait). 

I'm not sure what information would be useful, so please let me know if there is anything I can supply to help fix this.  

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by jooize** [comment]
Is this the same issue I have with scrolling up in history where the content suddenly jumps around and I lose my position and have to figure out whether to scroll up or down? Makes it time-consuming and frustrating to read past messages.

Version: Riot 0.13.5
Platform: macOS

**Comment by turt2live** [comment]
@jooize that sounds a bit closer to https://github.com/vector-im/riot-web/issues/6265

**Comment by turt2live** [comment]
Overall this seems to be fixed - probably related to some other performance issues. If someone feels otherwise, please open a new issue or mention it here so this can be re-opened.
