### ISSUE TITLE
Pinned images aren't pretty

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5421]
### Description

![image](https://user-images.githubusercontent.com/1190097/31954509-07223ad4-b8a3-11e7-9c7e-1643ba784e82.png)

The download bar gets pushed to the left, when it should probably be aligned with the image.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
What about scaling the image to fit the window size/a smaller max height, too? Clicking the image will still provide a full size full screen view, and seeing the whole thing feels like it will be useful on more occasions than seeing part of the thing bigger.
