### ISSUE TITLE
Granular settings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5425]
This is just an issue to track the discussion in https://github.com/matrix-org/matrix-react-sdk/pull/1516 (as I keep forgetting that the discussion there is on a PR rather than an issue)

**Comment by turt2live** [comment]
Here's a bunch of links from that PR that provide some context or are directly related to granular settings:
* https://github.com/matrix-org/matrix-react-sdk/pull/1479
* https://github.com/vector-im/riot-web/issues/3589
* https://github.com/vector-im/riot-web/issues/5405
* https://github.com/vector-im/riot-web/issues/1624
* https://github.com/vector-im/riot-web/issues/5424
* https://github.com/matrix-org/matrix-react-sdk/pull/1516#issuecomment-338726634 (and following conversation)

**Comment by turt2live** [comment]
Related: Language settings (https://github.com/vector-im/riot-web/issues/4937)

**Comment by turt2live** [comment]
@ara4n Granularity of the settings has been completed.

**Comment by ara4n** [comment]
\o/ thank you!!!
