### ISSUE TITLE
Unable to use plural strings in tests

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5426]
> ah, you're right - plurals won't work in the tests as the mangling that's done in copy-res doesn't happen

https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1508882505770989OjriH:matrix.org

**Comment by lampholder** [comment]
@dbkr - I think you've been in this space recently?

**Comment by lukebarnard1** [comment]
Right. So basically we really need to make `./gen-i18n.js` part of the dev process

**Comment by pafcu** [comment]
Is the issue not more that it is looking for the translations in the wrong place / wrong format during testing? It does not seem that running that script would change it.

**Comment by dbkr** [comment]
Yeah, them problem is that in the tests we just use the raw translations source file which is invalid for plurals. We need to do the same mangling that happens in copy-res.

**Comment by pafcu** [comment]
This is still broken as discussed [here](https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15091253674102019UzYNN:matrix.org). Could this be re-opened to not forget it?
