### ISSUE TITLE
Ongoing conference call notification below a widget is completely hidden on smaller window sizes

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5428]
![image](https://user-images.githubusercontent.com/1922197/31988280-7c031922-b966-11e7-939c-85eb2b0ce9f9.png)
![image](https://user-images.githubusercontent.com/1922197/31988317-95e6d1c6-b966-11e7-86f9-81a702c2c5d6.png)
![image](https://user-images.githubusercontent.com/1922197/31988333-9eda1496-b966-11e7-9053-e1d6c6f36821.png)

Particular fun when you're trying to debug with developer console :P

**Comment by lukebarnard1** [comment]
Should the notif go above the widgets?

**Comment by ara4n** [comment]
replaced by widgets
