### ISSUE TITLE
UX not possible to show url preview again, after dismissed it

### ISSUE THREAD

**Issue by Nostradamos** [vector-im/riot-web#5431]
It's not possible to get the url preview back, once you clicked on the X (or cancel) button.
There should be a way to show the preview again, or just don't make it dismissable.
Or what's the point in making a url preview dismissable?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/31990223-63cec2ec-b96c-11e7-8e67-fc42719ea5e3.png)
