### ISSUE TITLE
Pills get stretched when pinned

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5438]
### Description

![image](https://user-images.githubusercontent.com/1190097/32016278-b7fc346c-b980-11e7-9eef-1a392da66b85.png)

The gap between the avatar and displayname is larger. I'm suspecting this is just some dirty CSS I wrote to make the message avatar line up nicely also scoping to the pill.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
fixed
