### ISSUE TITLE
https://riot.im/app redirects to http://riot.im/app/ (not https), which then redirects to https://riot.im/app/

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5441]
which causes a surprising failure when trying to embed in an https site since it tries to load a non-secure page.  See https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1508973538105wkNKi:dries.info

**Comment by lampholder** [comment]
Bleugh, that's awful. _Hopefully_ it's easy to put right?

**Comment by richvdh** [comment]
this sounds like an apache fail on our side, rather than a thing we can get help with

**Comment by lampholder** [comment]
I didn't know whether this was going to be apache or react routing, though you're right it probably is apache.

**Comment by pafcu** [comment]
@lampholder Any progress on this? It's classed as a major p1 bug, and it probably should not be too difficult to fix

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/41500334-4f40f98e-7187-11e8-9371-5ac5525cb811.png)
:(

**Comment by t3chguy** [comment]
This is still an issue on the new infra:
![image](https://user-images.githubusercontent.com/2403652/57585725-e9c65c00-74e3-11e9-90f9-6171c792fcb3.png)

**Comment by ara4n** [comment]
bleurgh. this is due to apache defaulting to `DirectorySlash On`. will try overriding with a mod_rewrite rule first.

**Comment by ara4n** [comment]
done; the required voodoo was:

```
        DirectorySlash off
        RewriteOptions AllowNoSlash
        RewriteCond %{REQUEST_URI} [^/]$
        RewriteCond %{LA-U:REQUEST_FILENAME} -d
        RewriteRule ^(.+)$ https://riot.im$1/ [L,R]
```

**Comment by ara4n** [comment]
actually, the correct non-voodoo way of doing it is:

```
ServerName https://riot.im
```
