### ISSUE TITLE
Use the bulk delete_devices API instead of hammering the server

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5442]
as per https://github.com/matrix-org/synapse/pull/1993

**Comment by lampholder** [comment]
@richvdh What's the priority of this?

**Comment by richvdh** [comment]
@erikjohnston any opinions?

**Comment by erikjohnston** [comment]
P-9000? Its not something that is making things materially worse, but it makes me sad, and occasionally the server a bit slow for a few minutes as someone deletes 100s of devices.

My main concern is ensuring people don't c+p the current solution when they next need to deal with UI auth, as its horrific and naughty

**Comment by ara4n** [comment]
it took out the whole synapse last night.  I suggest we shove checkboxes next to all the devices in UserSettings and a big delete button at the bottom, and probably remove the little delete buttons whilst we're at it.

**Comment by fmcd** [comment]
An option to delete all devices not seen in the last X hours/days would be useful. 99% of my device list was previous one-time browser sessions. The only continually active ones are the desktop client and android clients.

**Comment by t3chguy** [comment]
This is now done as far as I can see
