### ISSUE TITLE
Registration should automatically lowercase requested usernames

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5445]

**Comment by turt2live** [comment]
Related discussion (UX on doing this for groups): https://github.com/vector-im/riot-web/issues/5434

**Comment by lampholder** [comment]
@ara4n is this just to reduce the proliferation of mixed-case usernames by stopping our Riot instance from registering them?

**Comment by ara4n** [comment]
no, this is to stop the horrid error msg when you try to register a username of Foo
