### ISSUE TITLE
Cannot autocomplete in the middle of a message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5450]

**Comment by lukebarnard1** [comment]
You'll have to be more specific, I cannot reproduce with "testing :) *tab*"

**Comment by t3chguy** [comment]
`test :) test` then go back to `:)` and TAB, nothing happens
Same if you go into the middle of a message and type `:`, no popup

**Comment by lukebarnard1** [comment]
Oh, sounds like the autocompleting logic is using the entire message as a query to determine completions instead of the message up to the cursor.

**Comment by turt2live** [comment]
What @t3chguy said. Sorry

**Comment by jryans** [comment]
Completing user names in the middle of a message is also affected.

**Comment by jooize** [comment]
I frequently want to autocomplete a name with a colon right after. Say I autocomplete one, and want to address another one with the same message, so I tap Left twice, press Colon, Space, and partially write the next name. When I press Tab, the input field blinks red.

![Screenshot 2019-05-20 at 19 58 40](https://user-images.githubusercontent.com/719371/58042162-38a27000-7b3a-11e9-879b-64cf15ae1b8f.png)
![Screenshot 2019-05-20 at 19 59 04](https://user-images.githubusercontent.com/719371/58042163-38a27000-7b3a-11e9-9f11-b4f32c128a63.png)
![Screenshot 2019-05-20 at 20 03 19](https://user-images.githubusercontent.com/719371/58042235-6a1b3b80-7b3a-11e9-95f1-63327183d5d2.png)

**Comment by t3chguy** [comment]
Fixed
