### ISSUE TITLE
Join room banner has migrated to middle of screen

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5451]
### Description

![image](https://user-images.githubusercontent.com/1190097/32072261-3366e65a-ba4f-11e7-8531-2b509293a91f.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
Fixed by 3dcc397f
