### ISSUE TITLE
"No rooms in group" shown while waiting for rooms request to finish

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5457]
### Description

When viewing a group, the rooms list may take a bit longer to load. Instead of saying no rooms, a loading status may be better.

### Steps to reproduce

- Be on a slowish network
- Open a group with many rooms
- Note that the rooms placeholder is "No rooms in group".

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Very confusing

**Comment by lukebarnard1** [comment]
@dbkr discussed a similar problem last night. The conclusion was to add a `ready` flag to each of the APIs that are hit by the group store. If an API has never hit out (in the app's lifetime), the flag is `false`, otherwise `true`.
