### ISSUE TITLE
redaction dialog box lacks default focus on OK button :|

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5461]

**Comment by aidalgol** [comment]
Are there any dialogs where the default focus _is_ set correctly?

**Comment by turt2live** [comment]
The log out dialog is correctly focused. Not sure about any other examples.

**Comment by aidalgol** [comment]
{{ConfirmRedactDialog}} is not using {{QuestionDialog}}, but is instead using {{BaseDialog}}.  It looks like {{QuestionDialog}} correctly sets the default focus to the OK button.  Should I try fixing this by making {{ConfirmRedactDialog}} use {{QuestionDialog}}?

**Comment by ara4n** [comment]
that would be great - alternatively I think all dialogs are meant to have default focus (and remember it when stacked), and this might be what has actually broken. but using QuestionDialog is definitelt a valid solution too! thank you!

**Comment by aaronraimist** [comment]
It does now
