### ISSUE TITLE
Race when registering by email may result in "User ID already taken"

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5465]
There's some unusual race which I've seen once(?) where you get "User ID already taken" during normal email registration flow.  @carlbennetts just hit it when testing chat.status.im, although I can't reproduce at all.  I think we've seen it once before, and me/luke/kegan chased it a bit but never caught it.

**Comment by lampholder** [comment]
Potentially related: https://github.com/vector-im/riot-web/issues/4102

**Comment by lukebarnard1** [comment]
Despite similarities, I don't think #4102 is related. 

Last time I chased @ara4n's issue, I think it was some bizarre race between the identity server and the HS but I don't have any evidence to back that up.

The existing issue is vector-im/riot-web#3221

"User ID already taken" is the raw error message from synapse given by the registration API, "Username in use" doesn't seem to be part of either code base any more and "Username not available" is the error message in the `SetMxIdDialog`.

**Comment by ara4n** [comment]
closing as a dup of #3221 (which i couldn't find)
