### ISSUE TITLE
Ability to set custom avatar ("pet avatar") to override default locally

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#5475]
Similar to #3130, it'd be good to be able to override the room avatar on an individual level. Just chatted to a friend who doesn't yet (or chooses not to) set her room avatar, but when I wanted to replace the default letter-in-a-circle with a photo, she would no longer see my avatar on the otherwise unnamed room — but the photo I uploaded.

In fixing this (if desirable), at least the UI issue of #5123 will also be relevant, I bet.

Thanks!

**Comment by turt2live** [comment]
#3130 is the ongoing issue for this, although the title doesn't suggest it. The title of #3130 should be updated :/

**Comment by madduck** [comment]
Happy either way.
