### ISSUE TITLE
Status page for matrix.org homeserver 

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5477]
It'd  be nice to have a status page to show if matrix.org was struggling.

https://github.com/matrix-org/matrix.org/issues/23

**Comment by aaronraimist** [comment]
https://status.matrix.org ?

**Comment by jonas-schievink** [comment]
The status page is timing out. Is there a status page for the status page? It should really not be hosted on the same infra as the page it is supposed to report the status of.

**Comment by turt2live** [comment]
The status page is currently down following the security incident, and further down because of a temporary issue on matrix.org

**Comment by cmcaine** [comment]
matrix.org and status.matrix.org are down together again, fwiw.
