### ISSUE TITLE
Configure whether or not a room appears in a group's room list to non-members.

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#5480]
For this to be possible, we need to:
 - [x] Add a column to the synapse database (apparently this is already there and already is handled correctly by APIs - only members can see rooms that are marked `is_public: false`)
 - [x] Add a setter API for this column that takes `groupId`, `roomId` and `{publicity: "true/false"}` https://github.com/matrix-org/synapse/pull/2612
 - [x] Changing the "X" on the `GroupRoomTile` to a link under an "Admin Tools" header in a new `GroupRoomInfo`, in the same vein as `GroupMemberInfo` https://github.com/matrix-org/matrix-react-sdk/pull/1563
 - [x] Add a UI to Riot for manipulating whether the group-room association `is_public`. https://github.com/vector-im/riot-web/pull/5497

Based on https://docs.google.com/document/d/13OQ0gtdLsha4RKttxVZlGTKEncvjOToa2duv8bOdyvs/edit#heading=h.xsf65cn5ty5q

**Comment by turt2live** [comment]
Access to the document is restricted. Please may we have comment/view access?

**Comment by lampholder** [comment]
Access should be open now if I've googled my google properly.
