### ISSUE TITLE
Trying to open a conversation with yourself results in a misleading error message

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5482]
### Description

Trying to open a conversation with yourself results in the error message "Server may be unavailable, overloaded, or you hit a bug."

### Steps to reproduce

- Navigate to https://riot.im/develop/#/<your_mxid>?action=chat
- If prompted, choose "Start new chat"
- Notice you get an error

Either a more informative error should be give, or it should actually just open an empty chat with just you.

### Version information

Tested on riot-web version: 0.12.7

**Comment by uhoreg** [comment]
dup of  #4833
