### ISSUE TITLE
3pid invites are not collapsed

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5489]
![image](https://user-images.githubusercontent.com/1012976/32281194-805bff32-bef4-11e7-9d00-63b289b99e3a.png)

In the screenshot above, you can see that three invites by MXID have been collapsed, but the 3PID invites are not collapsed.  Also, the 3PID invites have different wording from the MXID invites.  (The screenshot is from around https://matrix.to/#/!eUGMvloIjhBoAwlyRh:matrix.org/$15095479812593647HdYSs:matrix.org in #linear-supporters:matrix.org.)

**Comment by lampholder** [comment]
Not collapsing is a biggy, esp. with Sync Bot's mass-inviting antics.

The 3pid invite wording might be intentionally different, inasmuch as there is a _very_ subtle semantic difference between inviting a user and sending an invite to a user's email address, but I think I'd agree that any difference we're hoping to convey isn't worth the aesthetic downsides.
