### ISSUE TITLE
Add a way to select to which email we want the email notifs to go

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#5496]
E.g. a drop down

**Comment by lampholder** [comment]
Is there ever a situation where somebody would want to be able to send notifications to multiple email addresses? Do we want to support that?

**Comment by turt2live** [comment]
Multiple email addresses would be nice, although imho that can be p5.

**Comment by uhoreg** [comment]
related (dup?): https://github.com/vector-im/riot-web/issues/3454

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2727
