### ISSUE TITLE
Total react crash on changing room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5514]
Looks like something very bad happened during unmounting the room perhaps?  Might be related to attempts to speed up room switching?

https://github.com/matrix-org/riot-web-rageshakes/issues/497

**Comment by lampholder** [comment]
I've tagged this 'release-blocker', though am I right in thinking this is likely already in front of users on /app?

**Comment by ara4n** [comment]
yes, it was released, although i've only seen it once.

**Comment by lampholder** [comment]
This shouldn't block 0.14. Anecodtally it doesn't sound like this is happening regularly, and when it did happen it happened on already-released code.

**Comment by turt2live** [comment]
Room switching has almost entirely been rewritten since this was reported. Please open a new issue if it still happens.
