### ISSUE TITLE
"Never send to unverified devices"

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5515]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by uhoreg** [comment]
This seems to be an accidentally-submitted issue.

**Comment by t3chguy** [comment]
Real issue being: https://github.com/vector-im/riot-web/issues/5516
