### ISSUE TITLE
Not working for me: https://riot.im/app/#/forgot_password

### ISSUE THREAD

**Issue by nrbray** [vector-im/riot-web#5521]
### https://riot.im/app/#/login

Unable to reset password for user nrbray:matrix.org

### Steps to reproduce

- https://riot.im/app/#/login
- Forgot your password? -> https://riot.im/app/#
- pqr.abc@12xy.com
- N5n0Z@aBDJwhIm3eetKV
- N5n0Z@aBDJwhIm3eetKV
- Send reset email
- Continue -> 
- An email has been sent to pqr.abc@12xy.com. Once you've followed the link it contains, click below.
- https://riot.im/app/# -> "I have verified by email address"

No email

Log: not sent?    

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: , , Firefox 56.0
- **OS**: , , Ubuntu,

**Comment by nrbray** [comment]
Related?  #4210

**Comment by nrbray** [comment]
- Still logged in on Android
- From settings, added a new email  abcdef@service.com
- Received an email with link to complete verification
- https://vector.im/_matrix/identity/api/v1/validate/email/submitToken?token=sixfigure&client_secret=longgobledeygook&sid=sixfigure
- Verification successful! Please return to your Matrix client to continue.

- new email in Forgotten password page:
- Error /n Failed to send email: This email address was not found

**Comment by turt2live** [comment]
@nrbray if you use that password for anything, reset it.

**Comment by nrbray** [comment]
@turt2live  thanks, the above is an example, not used for anything

**Comment by lampholder** [comment]
UGH. Could be our password reset emails are being spam filtered (@nrbray did you check your spam filter?); that doesn't explain the 'email address not found' failure mode, though :(

**Comment by nrbray** [comment]
Guaranteed, nothing on my side appeared at my address, I checked the logs
at the entry point. I hope that helps. N

**Comment by lampholder** [comment]
Did you mean to close this?

**Comment by nrbray** [comment]
Yes, sorry this seems to be a bad report from me now.  I checked everything again and it seemed to work now.  I am surprised that I had trouble before and it does seem as though I overlooked a block on high rate emails.
