### ISSUE TITLE
If you type an explicit room alias when adding a room to a group, tab-complete should not be replaced by autocomplete results

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5525]
i.e. typing #matrix-architecture:matrix.org should not be turned into #matrix-dev:matrix.org when you hit tab.

**Comment by ara4n** [comment]
The solution here should surely be that if you have a direct match between one of the aliases in your autocomplete results and the one you are typing in here, it should use the direct match when you hit tab.  So presumably the problem is to a) stop searching topics; b) make sure shorter matches get higher precedence in the results.

**Comment by lukebarnard1** [comment]
- [ ] Don't do substring matching in topics of rooms
 - [ ] Aliases that are matched and are shorter should get higher precedence in the list of rooms
