### ISSUE TITLE
Can we have a 'remove' button next to the rooms listed in a group settings

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#5529]

**Comment by turt2live** [comment]
imho this should be higher priority and/or just implemented as a quick win. Several people aren't discovering the remove button on the RHS and I suspect having it right on the list (where they primarily add rooms) would help a lot.

**Comment by stellarmagnet** [comment]
Yeah I cant find how to remove.Please help

**Comment by t3chguy** [comment]
Closing in favour of higher priority duplicate (with more info) #5743
