### ISSUE TITLE
Stop the intrusive Unknown Device Dialog modal in favour of using the StatusBar

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5534]
Split out from #4522.

* Rather than shoving a modal dialog in the face of anyone when they try to send a message in a room with unknown devices, instead we should buffer the message and show the StatusBar to let the user decide whether to "send anyway" or "manage devices".  For now, "manage devices" would display the UnknownDeviceDialog, but in future, could be the full dashboard proposed in #4522.

Lots of ideas from @lampholder on how this could look at https://docs.google.com/document/d/12r21OrXYEvzKclKCUWX2a-2ckU6Se0IJHoZaLicVxFc/edit# - my suggestion is to keep the Status Bar the same height & look and feel as the normal "server disconnected" warning at least at a first cut, for consistency with the rest of the app, and to avoid getting blocked on new design assets.

**Comment by dbkr** [comment]
This is done in https://github.com/matrix-org/matrix-react-sdk/pull/1600
