### ISSUE TITLE
Devtools 'event type' field not themed

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5557]
### Description

![image](https://user-images.githubusercontent.com/1190097/32617216-9dd87142-c531-11e7-844a-ddc48534264e.png)

It should be styled to match the theme.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Turns out it is kinda themed:
![image](https://user-images.githubusercontent.com/1190097/32617252-c0d4edba-c531-11e7-8f53-6191dc06d2d7.png)

**Comment by t3chguy** [comment]
Weeeird, I could have sworn they were themed :(

**Comment by t3chguy** [comment]
FIXXED
