### ISSUE TITLE
shared secret MAC calculation is different between /r0/register and /v1/register

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5565]
/v1/register uses `user0password0admin`. /r0/register just uses `user`. Why are these different?

**Comment by lampholder** [comment]
I'm not aware of this causing any problems - please shout if you disagree witht he prioritisiation 😄

**Comment by richvdh** [comment]
the danger is that someone might decide to start using /r0/register in its current form, which will then mean we can never fix it.

Still hard to disagree with your prioritisation though.

**Comment by richvdh** [comment]
TBH I think I meant to close this in favour of https://github.com/matrix-org/synapse/issues/2664.

**Comment by hawkowl** [comment]
v1 register is gone, so this can be closed
