### ISSUE TITLE
Topic sanitization for rooms in groups appears broken 

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5568]
### Description

Similar to, if not a code-wise duplicate of, https://github.com/vector-im/riot-web/issues/3461

![image](https://user-images.githubusercontent.com/1190097/32671267-f48e0452-c603-11e7-8f80-8bb4a162d540.png)

Note the `&amp;`.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
The difference is that the groups/room dict uses linkifyString, and then has to escape it
whereas the topic in the room header uses `linkifyElement` which doesn't need escaping and *works*

**Comment by t3chguy** [comment]
but then that leads to having to ref the div/whatever that holds the topic

**Comment by turt2live** [comment]
This got fixed
