### ISSUE TITLE
No 'Start Chat' for members of groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5570]
### Description

![image](https://user-images.githubusercontent.com/1190097/32671515-fb4b420e-c604-11e7-8e1f-93a15922c912.png)

:(

This is from +matrix:matrix.org

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by sleeksorrow** [comment]
I am affected by this one as well, as this would be the best workflow for my use case. I am not sure what milestone "Temporary Bug Bin" means. Is this still a valid feature request, tho?

Riot for Aandroid has this feature, I can pull up the member list of my community, tap a name and start a chat. So this is some quite prominent inconsistency.
