### ISSUE TITLE
Package-lock.json Causing Build Failure

### ISSUE THREAD

**Issue by BennZoid** [vector-im/riot-web#5580]
### Description

I'm currently trying to build the latest version of riot(0.13.0-RC.2) on Solus (linux).  The build fails to pull in the module 7zip-bin-linux as it previously would.  It would appear that the package-lock.json contains a mac version of the 7zip bin so npm install doesn't try to install the linux version until "npm install" is ran a second time or ran with the --no-shrinkwrap option (to ignore the lock file).  This leads to building  successfully ~~but then riot will not start which I believe is due to an auto-launch [issue](https://github.com/Teamwork/node-auto-launch/issues/67).~~ (Fixed)

### Steps to reproduce

- Using linux computer
- clone develop branch or download 0.13.0-RC.2 source tarball
- `npm install`
- `npm build`
- `node_modules/.bin/build -l --x64 --dir`
- fail upon downloading electron with `Error: Cannot find module '7zip-bin-linux'`

### Version information

For the desktop app:

- **OS**: Solus Linux
- **Version**: v0.13.0-RC.2

**Comment by silkeh** [comment]
This issue also applies to v0.13.0-rc.3. Ignoring/removing `package-lock.json` results in a working build.

**Comment by turt2live** [comment]
I can't reproduce this on modern versions of riot. If it is still an issue, please open a new bug
