### ISSUE TITLE
Room tint is not respected in many places

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5583]
### Description

E.g. links in messages, counts,chevrons and the "drop here boxes" in the left sidebar remain green even if I choose to tint a room red.

### Version information
Riot-web 557fd8f7341e-react-ddd230d79895-js-7a59579dcdec on FF 56.0

**Comment by ara4n** [comment]
this is only on FF56.  changing to a tinted room when on the dark theme goes horribly wrong:

<img width="2032" alt="screen shot 2017-11-13 at 21 52 37" src="https://user-images.githubusercontent.com/1294269/32751269-1f69c880-c8bd-11e7-9d73-984da33113d5.png">

**Comment by ara4n** [comment]
...and on latest develop.
