### ISSUE TITLE
what-is-riot page links to download page badly

### ISSUE THREAD

**Issue by emiljoha** [vector-im/riot-web#5584]
### Description
Link problems on https://about.riot.im/what-is-riot/#item6.  

1) The desktop app link results in a page not found error. Links to page https://about.riot.im/download/desktop while the download page is at https://about.riot.im/downloads/.

 2) The link to get the iOS and Android app leads to the general download page. https://about.riot.im/downloads/. If you are on mobile the resulting page will be relevant. However if on desktop the desktop download tab is displayed.

### Steps to reproduce

1) Start up firefox, go to https://about.riot.im/what-is-riot/#item6 and click on "desktop apps" link on the third bullet point. "We also have desktop apps for macOS, Windows & Linux." A "page not found" page is displayed.

2) Start up firefox on linux computer, go to the same link as problem 1 and press "here" in the second bulletpoint reading "Get Riot on iOS and Android here".  The download page opens with the linux "tab" open. Expected something more relevant to iOS and Android.

**Comment by emiljoha** [comment]
My suggestion is to remove the two different links to the download page with one "Download Riot" button or something similar.

**Comment by lampholder** [comment]
Ugh - thanks for spotting this.

My guess is that the tone of this little segment is intended to reinforce the idea of Riot's existing across all known human technologies. I'd be tempted to try and leave that sense intact by replacing the four bullets with:
- [Use Riot in your browser](https://riot.im/app); (Chrome/Firefox recommended)
- Get Riot for your mobile device - available on the [App Store](https://itunes.apple.com/us/app/vector.im/id1083446067) or [Google Play](https://play.google.com/store/apps/details?id=im.vector.alpha) now!
- [Download desktop apps](https://about.riot.im/downloads/) for Windows, macOS and Linux
- Even more options - why not [take a look at third party Matrix clients](https://matrix.org/docs/projects/try-matrix-now.html)?

**Comment by turt2live** [comment]
I'm assuming this is magically fixed by the new about.riot.im - @nadonomy another for your consideration.

**Comment by turt2live** [comment]
Magically fixed.
