### ISSUE TITLE
UserSettings only echos theme change in radiobutton after they take effect

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5585]
the local echo of the dialog should be instant. this is pre-granular settings

**Comment by turt2live** [comment]
Fixed in granular settings ;)

**Comment by lampholder** [comment]
P3ing with granular settings on the horizon

**Comment by turt2live** [comment]
This is fixed already. Granular settings has landed. The lag seen in the radio button is because the browser chews through resources trying to render the page.

**Comment by turt2live** [comment]
This is not fixed on /develop for some reason. Some of the lag can be associated to render lag, however most of it appears to be the local echo in granular settings not working.

**Comment by turt2live** [comment]
This got fixed somewhere in the 2 years
