### ISSUE TITLE
[status theme] Dark theme buttons in UserSettings have much brighter text

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5587]
### Description

Status theme:
![image](https://user-images.githubusercontent.com/1190097/32757931-33d0c904-c89f-11e7-9bb5-f99d76390665.png)

Before:
![image](https://user-images.githubusercontent.com/1190097/32757939-3d1dbd32-c89f-11e7-818e-b65917894f94.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
thanks - fixed in 142a9d75
