### ISSUE TITLE
CSS regression where Tinter decides to tint SVGs jet black

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5589]
repro steps are unclear; just got it on dark theme during business as usual

**Comment by ara4n** [comment]
I had this on my main riot.im/develop account but can't repro it.  It might be a race that means that if the CSS hasn't loaded by the time the tinter does the first SVGs, it doesn't know what the correct tint colour is.  But in practice it should then fall through to the defaults (Vector Green).  Going to close and reopen when i next see it.

**Comment by ara4n** [comment]
actually, will just stick as 'cannot reproduce' for now to make it easier to find this issue.

**Comment by lampholder** [comment]
We've not heard any new instances in ~1 year, so I'm going to close.
