### ISSUE TITLE
Now Chrome/FF/Safari all support WASM, we should probably use it for Olm

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5591]
I think this is just as easy as shoving a `-s WASM=1` into the emscripten runes when building olm for matrix-js-sdk? See https://github.com/kripken/emscripten/wiki/WebAssembly

**Comment by lampholder** [comment]
Does this pin us to more modern versions of browsers, or does it fall back to the non webassembly version if the browser doesn't include support?

**Comment by uhoreg** [comment]
see also #3753

**Comment by fuzzy76** [comment]
According to https://caniuse.com/#feat=wasm that would exclude ~26% of browsers (~18% if you filter by desktop users).

**Comment by uhoreg** [comment]
This may not be as easy as just setting `-s WASM=1`, as per https://github.com/matrix-org/olm/issues/12

**Comment by dbkr** [comment]
https://github.com/vector-im/riot-web/pull/7385 does this!

**Comment by dbkr** [comment]
The notable exception in that list is TorBrowser which explicitly disables WASM

**Comment by ara4n** [comment]
@dbkr can we close this then? :)

**Comment by turt2live** [comment]
I'm voting yes.
