### ISSUE TITLE
Dark theme no longer apply if the room has a specific color

### ISSUE THREAD

**Issue by floviolleau** [vector-im/riot-web#5592]
### Description

With dark theme selected in settings, dark theme is no longer applied if a room has a specific room color chosed.

### Steps to reproduce

- Choose a color on a room
- Save the setting of that room
- Move from another room and go back to that one using left menu

This happen:![image](https://user-images.githubusercontent.com/5442973/32784372-f2fe1ea8-c94e-11e7-894b-f63b0dc0241b.png)

### Version information

- **Platform**: web (in-browser) latest from develop (v0.12.7-337-g557fd8f7)

For the web app:

- **Browser**: Firefox 56.0.2 (64 bits)
- **OS**: Windows 7
- **URL**: private server

**Comment by ara4n** [comment]
dup #5583
