### ISSUE TITLE
MELS avatars have wrong vertical offset in Firefox

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5594]
Bizarrely and depressingly, toggling the `line-height` style attribute on & off on the initial fixes it :(

<img width="641" alt="screen shot 2017-11-14 at 16 16 41" src="https://user-images.githubusercontent.com/1294269/32790816-5297efee-c957-11e7-89f6-6d8749e42314.png">

**Comment by uhoreg** [comment]
dup of https://github.com/vector-im/riot-web/issues/4096 (it happened in pre-57 too)

**Comment by uhoreg** [comment]
Oh, wait, this is a different issue.  Sorry for the noise.

**Comment by lampholder** [comment]
Fixed! (As of ff 64 something, if we didn't fix this in Riot itself)

**Comment by lampholder** [comment]
But I'm bumping from P1 'cause I don't think it actually looks noticably broken.

**Comment by jryans** [comment]
I believe this is a styling bug in Firefox. I am working on a reduced test case.

**Comment by ara4n** [comment]
This is still broken in the redesign:

<img width="466" alt="screenshot 2019-02-10 at 22 43 28" src="https://user-images.githubusercontent.com/1294269/52540785-629f0600-2d85-11e9-9da8-2b912cab5883.png">

**Comment by jryans** [comment]
I believe this is partly a Firefox style caching / race condition bug, which I have [reported upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1535053). It is interesting, however, that we now also have reports of similar issues in Chrome as well (#9088).

I will continue investigating style tweaks in Riot to avoid these strange browser behaviours.
