### ISSUE TITLE
Permanent "You are not receiving desktop notifications"

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#5603]
Clicking the "X" or clicking "Enable them now" does nothing

**Comment by lukebarnard1** [comment]
I was able to dismiss it after refreshing

**Comment by MTRNord** [comment]
got the same error. rageshake sent if needed.

**Comment by turt2live** [comment]
A quick test of other people who are having this shows that they are somehow missing the localstorage item to enable desktop notifications. The easiest way to check is to call `localStorage.getItem("notifications_enabled")` which should return `"true"` or `"false"` if you've previously defined the setting.

Based on the few people I've tested, it only happens to people with fairly old riot sessions (many many months).

**Comment by uhoreg** [comment]
> Based on the few people I've tested, it only happens to people with fairly old riot sessions (many many months).

It happened to me on a relatively new session (since whenever Quantum was first released, which seems to be around late September).  Going to my user preferences, I saw that both "Enable desktop notifications" and "Enable audible notifications" were unchecked.  Checking "Enable desktop notifications" resulted in both of those options being checked.

**Comment by turt2live** [comment]
This should have been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1613 - are you still having the issue?

**Comment by uhoreg** [comment]
I just loaded /develop last night, so it seems like it still isn't fixed :(  (Of course, now that I've updated my settings, I probably won't be able to reproduce it any more.)

**Comment by JaniM** [comment]
This only happens to me on /develop.

**Comment by uhoreg** [comment]
After nuking my session and re-logging in on /develop, I see this again.  So now that I have it in a broken state again, let me know if there's anything I can do to debug.

**Comment by uhoreg** [comment]
BTW, `localStorage.getItem("notifications_enabled")` returns `null` in that session.

**Comment by t3chguy** [comment]
@uhoreg / @lukebarnard1 can you repro since matrix-org/matrix-react-sdk#1675 landed?

**Comment by lukebarnard1** [comment]
Importantly, if you click the "X", the local storage item to check is `"notifications_hidden"`. It should be "true" after clicking the "X".

**Comment by lukebarnard1** [comment]
No I cannot :smile:
