### ISSUE TITLE
Turning off url previews in user settings no longer works

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#5607]
I have disabled url previews in my user settings, after updating riot URL previews are now happening again. Twiddling on and off doesn't help.

This might be due to the new granular settings PR that landed just before I refreshed?

### Version information

- **Browser**: Chrome
- **OS**:  Ubuntu
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Yes, this is granular settings :(

URL previews are a somewhat special case and get treated a bit differently, so what ends up happening is the room-device (or -account?) level returns a value that does not reflect the overall default, despite the level not actually being set (which should therefore cause inheritance).

**Comment by turt2live** [comment]
@erikjohnston are you still having this? (barring the OPTIONS preflight problem)
