### ISSUE TITLE
Notification panel doesn't use the correct emojis

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5609]
### Description

![image](https://user-images.githubusercontent.com/1190097/32848335-6be1e8be-c9e9-11e7-9e30-bcc78201de6f.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Glitchy :(
