### ISSUE TITLE
uneven space between icons

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/riot-web#5612]
![screenshot from 2017-11-15 20-41-37](https://user-images.githubusercontent.com/7166727/32853938-9d712be0-ca45-11e7-9fa2-bc4fb16ad7df.png)

![ron-swanson-computer](https://user-images.githubusercontent.com/7166727/32854018-e70d23ee-ca45-11e7-84fe-d3777ed483d1.gif)

**Comment by t3chguy** [comment]
Well thanks... Now I can't unsee that uneven space :(

**Comment by turt2live** [comment]
This is likely because the communities icon didn't exist before, so there was a gap there. That menu is also split into two parts, so the settings icon is a different area. 

This doesn't excuse it, just explaining what is going on.

**Comment by lampholder** [comment]
Gah, yes. @turt2live's explanation is correct. We are (were?) not intending to have this many icons down in the bottom left - having added the groups icon we wanted to look at how people were actually using these buttons and consider combining some of them into a more streamlined setup.

Now I _also_ can't unsee the goddamned extra pixels though, so if somebody wants to fix this up whilst we're figuring out these icons' future please do 😁

**Comment by ara4n** [comment]
a) this is the best bug ever
b) it'll be fixed in the upcoming LeftPanel redesign

**Comment by turt2live** [comment]
Seems fixed by @lukebarnard1: https://github.com/vector-im/riot-web/pull/6130
