### ISSUE TITLE
Community IDs are linkified to matrix.to, but matrix.to does not support community IDs

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5614]
### Description

If you type in e.g. +foo:matrix.org it is turned into the link https://matrix.to/#/+foo:matrix.org. However, matrix.to does not support community IDs (https://github.com/matrix-org/matrix.to/issues/33).

### Steps to reproduce

- type in e.g. +foo:matrix.org in a message and send it
- open link in new tab

### Version information

Riot web 0.13.0 on FF 56

**Comment by ara4n** [comment]
fixed by @lub - thank you!! https://github.com/matrix-org/matrix.to/pull/35

**Comment by ara4n** [comment]
oh, we also need to make riot-web correctly intercept  https://matrix.to/#/+foo:matrix.org links in-app.
