### ISSUE TITLE
SenderProfile CSS colour has broken on develop

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5620]
Perhaps since the theming merge:

<img width="850" alt="screen shot 2017-11-16 at 14 43 42" src="https://user-images.githubusercontent.com/1294269/32897102-9f7b9942-cadc-11e7-9c42-77b84efd1797.png">

**Comment by turt2live** [comment]
It's more pronounced on the dark theme:
![image](https://user-images.githubusercontent.com/1190097/32897575-41283ea6-caa3-11e7-9070-ab12c0d123f7.png)

**Comment by ara4n** [comment]
also looks like idle-presence MemberInfos have also got too light

**Comment by turt2live** [comment]
Seemingly fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1615

**Comment by ara4n** [comment]
\o/ thanks @lukebarnard1
