### ISSUE TITLE
Linkifier is overzealous

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5621]
### Description

![image](https://user-images.githubusercontent.com/1190097/32901006-fcf5d546-caab-11e7-963b-8ea148a98d66.png)

It's a bit hard to see, but `txn.call` got linkified despite being part of `txn.call_after`.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by pafcu** [comment]
This is an issue with https://github.com/SoapBox/linkifyjs/. I'm not sure if it is a bug or a "feature". Perhaps an issue should be opened there?

**Comment by uhoreg** [comment]
related to/dup of #5323

**Comment by turt2live** [comment]
Duplicate of #5323 indeed
