### ISSUE TITLE
Group settings cog is not shown after accepting invite

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#5631]
* receive group invite
* accept invite
* wait for spinner
* see summary page, but no settings cog

**Comment by richvdh** [comment]
This is what I got after accepting an invite:

![image](https://user-images.githubusercontent.com/1389908/32940011-4ebfd8f4-cb79-11e7-9a39-9d6f116fe782.png)

I want to see the cog so I can publish it on my profile!

**Comment by lampholder** [comment]
Me neither - the cog is one of the first things to arrive :)
