### ISSUE TITLE
Browser language detection is broken

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5632]
### Description

Riot checks if a user has set a preferred language. If not, it takes the preferred language from the browser's settings. However, it seems that now there is a default setting for the user's language which is returned when checking, so the language detection code thinks that the user has explicitly chosen a language already and does not use the browser-provided one.

This is probably related to granular settings.

### Steps to reproduce

- Set browser to prefer e.g. "de" as language
- Open a private browsing tab to make sure you are not using any stored settings
- Go to https://riot.im/develop
- Observe that the page is in English

### Version information

Riot Web 4c8f77bb8069-react-02629d13d920-js-4438d716b97b with Firefox 56

**Comment by MTRNord** [comment]
I think the /develop is broken a bit in General because of granular settings. Propably TravisR does have a idea why (as He does granular settings)
