### ISSUE TITLE
Pasting text in to the textbox breaks the textbox

### ISSUE THREAD

**Issue by maciozo** [vector-im/riot-web#5636]
### Description
After pasting text in to the textbox, sometimes the cursor gets moved to the front, and backspace stops working. Sometimes the text gets duplicated. Sometimes the text disappears when its sent. After selecting all the text and "clearing" it with backspace or delete, it will still appear, but on top of the placeholder text when focus is lost.

### Steps to reproduce

Find some text, formatted or plain
Focus the textbox in Riot
Paste either with mouse or keyboard

Log: sent

https://www.youtube.com/watch?v=HOYoJrd0UnM
![firefox_2017-11-17_16-34-34](https://user-images.githubusercontent.com/15807067/32958112-6817a7fa-cbb5-11e7-9f08-7041ce20caff.png)

### Version information

- **Platform**: web v0.13.0 (Also happened in 0.12.x)

For the web app:

- **Browser**: Firefox Nightly 59.0a1 (2017-11-17) (64-bit) (Has happened throughout multiple majour versions)
- **OS**: Windows 8.1
- **URL**: riot-web version: 0.13.0

**Comment by lampholder** [comment]
I tried to reproduce this as accurately as I could - using notepad++, firefox nightly and windows 7, and copy/pasting using the mouse, I _wasn't_ able to get the same behaviour.

Anecdotally thought It's not the first time I've heard of this failure - do you have any other browser extensions/os usability elements in place that might have impacted this?

**Comment by maciozo** [comment]
Ah, I seem to have found the cause.

In about:config, having `dom.event.clipboardevents.enabled` set to `false`. Setting it to `true` (which is the default) results in the expected behaviour.

This is also the cause of issue #5635

**Comment by WorldCodeCentral** [comment]
Hello, I have the same issue as pictured in maciozo's screenshot. I am using Firefox 59 as well (beta 9). However `dom.event.clipboardevents.enabled` is set to `true`. I found out that disabling both of the addons Stylus and Vimium fixed the issue. `dom.event.clipboardevents.enabled` remained `true` though, so seems to be unrelated in my case. Please forward if there's a more general issue for this problem, as my case is independent of pasting something in the textbox.

**Comment by yannicka** [comment]
On Firefox 76 (Kubuntu 20.04), Riot Web 1.6.1, with `dom.event.clipboardevents.enabled` set to `true`, I cannot reproduce the issue (same with `false`).

Do you still have the problem?

**Comment by t3chguy** [comment]
The composer has been replaced since this issue so am presuming solved
