### ISSUE TITLE
'Download app for desktop' link at bottom about.riot.im should link to https://about.riot.im/downloads/ instead of https://riot.im/desktop.html

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5643]
and about.riot.im/downloads should link straight to the download files instead of linking to riot.im/desktop.html, as the current UX requires extra unnecessary steps from the /downloads page: you need to click on the "Download for x" button, and then you need to find your OS again (even though it was already selected in the /downloads page), and click on the actual file that you want to download.

**Comment by lampholder** [comment]
Yeah, agreed this is a little bit clunky.

**Comment by turt2live** [comment]
@nadonomy something to consider

**Comment by arjunkrishnababu96** [comment]
Desktop download page https://riot.im/download/desktop returns a 404. 

(I got that link by clicking the **Download for App Desktop** button on https://about.riot.im/downloads).

**Comment by turt2live** [comment]
@arjunkrishnababu96 this is due to a different problem, documented here: https://matrix.org/blog/2019/04/11/security-incident/

**Comment by shirishag75** [comment]
@turt2live I am guessing the same is the case for deb https://riot.im/packages/debian/ stretch main also having 404. None of the binary packages will be released till probably the e2e issues are resolved or at least some way for people to have some sanity. Could it mean a new release ?

**Comment by turt2live** [comment]
The 404 is affected by the same thing, however our release plan is unclear at this time.

**Comment by turt2live** [comment]
We fixed this in the rebrand
