### ISSUE TITLE
Communities aren't guest/new user accessible from links

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-web#5650]
### Description

Going to https://riot.im/app/#/group/+matrix:matrix.org without logging in gives a prompt for username which leads to two options:

1. press X and Riot will load forever.
2. enter username and be introduced to Riot as a new user without ever seeing https://riot.im/app/#/group/+matrix:matrix.org without entering the page again, and who does that?

### Steps to reproduce

- Open an incognito window
- Go to https://riot.im/app/#/group/+matrix:matrix.org

I expected to see +matrix:matrix.org, but instead I see Riot bot.

![screenshot from 2017-11-19 11-07-35](https://user-images.githubusercontent.com/831184/32989170-1f200018-cd1a-11e7-89b1-93dcd1c5d669.png)
![screenshot from 2017-11-19 11-07-55](https://user-images.githubusercontent.com/831184/32989174-278523dc-cd1a-11e7-91f4-f38192c5530e.png)
![screenshot from 2017-11-19 11-08-46](https://user-images.githubusercontent.com/831184/32989188-5cf14c30-cd1a-11e7-9adb-b57abfb210a5.png)

First there is selecting username, then eternal loading after clicking X to close it and after refreshing the page and setting username, I am asked for username again and thrown into some room that has nothing to do with +matrix:matrix.org.

Being able to link guests to community pages would be important for those communities which include multiple rooms (23) and cannot go telling people to join `#bridge_#channel:example.net` and saying change `CHANNEL` to `ANOTHERCHANNEL` 22 times and I have understood that Riot doesn't even support multiple instances within the same browser.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 58.0b4
- **OS**: Arch Linux
- **URL**: riot.im/app

Firefox 58.0b4, Arch Linux, https://riot.im/app

**Comment by lukebarnard1** [comment]
> Being able to link guests to community pages would be important for those communities which include multiple rooms

Absolutely, and the intention with guests is to allow them to access public groups and their public memberships and room associations. The server currently disallows guest access.

And of course this doesn't justify the flow being buggy.

 1. Sounds like we forgot to think about what happens when someone cancels the username dialog without having been in the app already (prior to navigating to it).
 1. Sounds like the intention to view the group _after_ sign-in happens at a point before the user is considered non-guest.

**Comment by ara4n** [comment]
the fact we can't use communities for onboarding is a huge problem, and i've reprioritised to reflect...

**Comment by ara4n** [comment]
@lukebarnard1 this should take priority over LeftLeftPanel stuff please.

**Comment by lukebarnard1** [comment]
Having just tried the repro steps, I get a different experience where I see +matrix as a registered user, but with a second "To get started, ..."  displayed. This supports 
> Sounds like the intention to view the group after sign-in happens at a point before the user is considered non-guest.

Instead of improving the current flow, let's just make synapse allow guest access of public group info.

**Comment by ara4n** [comment]
sgtm. is this on your radar?

**Comment by lukebarnard1** [comment]
https://github.com/matrix-org/synapse/pull/2715 is merged and will let guests see groups

**Comment by ara4n** [comment]
@erikjohnston please can we get this on matrix.org tomorrow? more clusters today with folks advertising groups the public can’t join...

**Comment by ara4n** [comment]
so apparently this didn't fix things :(

**Comment by t3chguy** [comment]
Seems fine to me also

**Comment by ara4n** [comment]
closing at @Mikaela's request

**Comment by vesterinen** [comment]
This is still not working for me when landing onto a community page. It shows me to page and once I try to click to register so I could comment and pushes me first to choose username and then to accept 'terms and conditions'. Then it lands me on the Riot.im landing page. Not to the community page I tried to get to.

**Comment by vesterinen** [comment]
> This is still not working for me when landing onto a community page. It shows me to page and once I try to click to register so I could comment and pushes me first to choose username and then to accept 'terms and conditions'. Then it lands me on the Riot.im landing page. Not to the community page I tried to get to.

exactly as I reported earlier here https://github.com/vector-im/riot-web/issues/6247#issuecomment-368264885

**Comment by turt2live** [comment]
@vesterinen I've opened https://github.com/vector-im/riot-web/issues/7529 to track one of the issues with the community page. Clicking "Register" on the left isn't going to be possible in the next release because the button has moved to where the composer would be (which is not shown on the community page). 

For reference, the page not loading at all is https://github.com/vector-im/riot-web/issues/7204

**Comment by vesterinen** [comment]
> @vesterinen I've opened #7529 to track one of the issues with the community page. Clicking "Register" on the left isn't going to be possible in the next release because the button has moved to where the composer would be (which is not shown on the community page).
> 
> For reference, the page not loading at all is #7204

got it! thanks for the quick reply
