### ISSUE TITLE
Aux panel causing misalignment between room header and right panel header

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#5656]
It has `margin-bottom: 5px;`, even when hidden:

<img width="341" alt="screen shot 2017-11-20 at 13 09 25" src="https://user-images.githubusercontent.com/6750344/33019912-2bd1fc32-cdf4-11e7-85b8-48a5d98bfde7.png">

**Comment by turt2live** [comment]
This is effectively a duplicate of https://github.com/vector-im/riot-web/issues/4981#issuecomment-344416422 (as it's not been fixed yet)

**Comment by ara4n** [comment]
The right fix for this is probably to remove the margin-bottom, but add a new 5px margin-bottom on topics so that if topics are 2 lines high, they push the header out a bit in order to look less cramped.

**Comment by turt2live** [comment]
Fixed somewhere in the redesign
