### ISSUE TITLE
Clicking on LeftPanel when in any settings page should exit settings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5658]
Rather than forcing the user to go hunt for the (X) button

**Comment by t3chguy** [comment]
This used to be the case, back when the faded sidebars where click-through-able
So is a regression :P

**Comment by lukebarnard1** [comment]
oh. 

The faded UI is disabled with CSS `pointer-events: none`. 

Instead, we could have a store that controls whether the left/right panels are disabled and then not do things when the UI is disabled.

**Comment by lampholder** [comment]
For clarity, the desired behaviour is for a click on the faded room list or llp ("outside of the modal") should close settings ("dismiss the modal").

So the first click outside of the settings pane will dismiss settings, but the click will not pass through to the underlying element.
