### ISSUE TITLE
Memory usage of Riot has increased quite a lot

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5660]
### Description

I have a fairly large account that sits in 820 rooms, so it's not all that surprising that Riot uses a good chunk of my RAM. Over the last couple weeks I've noticed the RAM usage getting steadily higher, despite not joining more than a few rooms. Approximately a month ago the RAM usage was hovering around 1.2GB, and now it's anywhere between 1.7 and 2GB. I'm working on getting a memory snapshot, however the footprint is so large that chrome needs some extra flags to get the dump.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Do we have any ideas why this might be?

Potentially related to https://github.com/vector-im/riot-web/issues/3307

**Comment by turt2live** [comment]
It helped a bit to clear out the rageshake logs, however that only fixed the issue for a short while. I was seeing ~2GB of strings being loaded due to rageshake :(

**Comment by grahamperrin** [comment]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15146526923278095CKgBf:matrix.org (2017-12-30): 

>> Is it reasonable for the web app to use more than 1 G memory?
>> …
>> https://matrix.org/_matrix/media/v1/download/matrix.org/buFeNpKqWJVDrAWLxuqxbBAc

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15146764903622711dLWLX:matrix.org @ara4n replied: 

>  yup, riot/web memory usage sucks atm and we need to improve it

Two frames from a (long) screen recording, made this morning (for a variety of purposes, not solely for Riot). The leap in use of virtual memory by Waterfox – from 4,811 M to 10.8 G, when <https://riot.im/app/#/room/#mozilla_#firefox:matrix.org> begins to load – is entertaining (not alarming): 

![2018-02-04 08 44 54 frame](https://user-images.githubusercontent.com/192271/35776019-77cce51a-098c-11e8-80a6-64fa8eeab5da.png)

![2018-02-04 08 44 58 frame](https://user-images.githubusercontent.com/192271/35776022-851726f4-098c-11e8-9670-bd6c008d8075.png)

`:-)` yeah, I could use fewer extensions, but the sixty-something that are currently enabled are a good fit for my workflows.

**Comment by hrj** [comment]
> Do we have any ideas why this might be?

I wouldn't like to share a heap snapshot publicly, but I could share some statistics:

I am running version 0.13.5.

The tab manager of chromium was showing 0.5 GB of memory usage for the vector.im tab.  

The heap snapshot was 261 MB. I assume the rest of the 0.5GB is used internally by Chromium.

 Attaching a screenshot of the highest memory consuming object.



![riot-heap](https://user-images.githubusercontent.com/345879/36073406-0399f82a-0f56-11e8-91ef-4e31627aeb49.png)

**Comment by turt2live** [comment]
I'm going to close this at risk of it being re-opened by someone on the team. Personally my memory usage has decreased and some other issues (#6212 and #3307 in particular).

**Comment by grahamperrin** [comment]
I haven't noticed a decrease …

![2018-03-13 07 55 43](https://user-images.githubusercontent.com/192271/37420102-e3581734-27ad-11e8-8324-2423905effd3.png)

**Comment by grahamperrin** [comment]
Thanks @turt2live 

With `/develop` it's fairly easy to have a colossal amount of virtual memory in use, for example from this: 

![2018-03-14 18 42 10](https://user-images.githubusercontent.com/192271/37490632-0f5f2012-2893-11e8-82d8-2ebda97d17e0.png)

– to this (more than 34 G): 

![2018-03-14 19 26 23](https://user-images.githubusercontent.com/192271/37490599-f6384244-2892-11e8-931a-f217846a81c3.png)

– but that might be platform- and/or browser-specific, 

- Mozilla bug [1441041 - memory not freed after ceasing to visit some types of content](https://bugzilla.mozilla.org/show_bug.cgi?id=1441041)

**Comment by turt2live** [comment]
@grahamperrin I highly recommend opening a new issue if you're seeing this as not improved. Keep in mind there's also #6212 and #3307 which have somewhat derailed into general performance problems.

**Comment by grahamperrin** [comment]
Yep, in a nutshell: 

- ignoring the red alert for connectivity, for `/develop` I see 686.04 MB in the screenshot
- that's significantly less than the 1,016.72 MB beneath the pointer in the shot of `/app` at https://github.com/vector-im/riot-web/issues/5660#issuecomment-373109541
