### ISSUE TITLE
Incorrect lang attribute in root <html> element

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5662]
### Description

The root `<html>` element always has `lang="en"` despite the user having chosen a different language. This results in spell-checkers thinking everything is in English, and screenreaders trying to use English pronunciation for all languages.

This seems to be hardcoded in `src/vector/index.html`

### Steps to reproduce

- Choose another language than English, e.g. Deutsch in the user settings
- View HTML source
- Observe that `lang="en"`

### Version information

Riot Web c28d9e5cde96-react-d4feca5dfb4d-js-c31ce641a163 on FF57

**Comment by ElSi-DVT** [comment]
This problem still exists in current versions of Element Web and is very annoying for users who work with a language other than English. @t3chguy are there any plans to improve this?

I think that shouldn't be too difficult to implement. The static `lang="en"` value would simply need to be replaced by a variable value from the currently selected language.

**Comment by t3chguy** [comment]
@ElSi-DVT its not even an open issue so is very unlikely to be tackled by anyone. I suggest opening an issue if it is a problem for you. We don't tend to fix already closed issues, and community contributors are unlikely to see them also.

**Comment by ElSi-DVT** [comment]
Hi @t3chguy thanks for your reply and the tip - I'll do it that way. :) #32603
