### ISSUE TITLE
Full text search seems almost completely unusable

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5666]
I can't remember the last time I got a valid search result out of the system; it seems to timeout quite quickly with a horrible error that leaks an access token to the UI.

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/4738, https://github.com/vector-im/riot-web/issues/5373, https://github.com/vector-im/riot-web/issues/5517

**Comment by grahamperrin** [comment]
For me: it's much improved in recent weeks. 

I vaguely recall reading an announcement, but I can't find anything relevant blogged (so maybe there was a hurrah in the Riot room, or something).

**Comment by ara4n** [comment]
yeah, i ended up fixing us by moving back from GIST to GIN indices.
