### ISSUE TITLE
Localization (eo) of day's headline uses unformatted "%(fullYear)s" in devel version

### ISSUE THREAD

**Issue by hdurer** [vector-im/riot-web#5667]
### Description
With locale set to Esperanto the dividers between days are formatted as e.g.:
`Ĵaŭ, %(fullYear)s Nov 16 09:11` (compare to English's `Thu, Nov 16 2017 09:11`).
This still works in the non-devel version: `Ĵaŭ, 2017 Nov 16 09:11`

### Steps to reproduce

- Set locale to Esperanto in setting
- Look at any room

### Version information

- **Platform**: web (in-browser) freshly re-loaded to ensure I don't get a stale app

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by pafcu** [comment]
This is fixed in  https://github.com/matrix-org/matrix-react-sdk/pull/1618

**Comment by hdurer** [comment]
Cool.  Thanks.
