### ISSUE TITLE
Permission error when saving room tinting

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5670]
### Description

Setting room tint (for yourself) should not require any special permissions. However, if you click _Save_ in room where you are not allowed to change settings you get the error "M_FORBIDDEN: You don't have permission to post that to the room. user_level (0) < send_level (50)".

Despite the error, the tint seems to be saved anyway.

### Steps to reproduce

- Go to room where you do not have admin rights
- Open settings, change tint
- Click save

### Version information

Riot web c28d9e5cde96-react-d4feca5dfb4d-js-c31ce641a163 on FF57

**Comment by turt2live** [comment]
I'm suspecting this is https://github.com/vector-im/riot-web/issues/5637

**Comment by pafcu** [comment]
You're probably right. Closing this one as a duplicate
