### ISSUE TITLE
Riot fails completely with cookies disabled in Firefox

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5671]
If you turn off cookies in Firefox, like so:

![screen shot 2017-11-22 at 16 08 20](https://user-images.githubusercontent.com/986903/33137336-9563fb4e-cf9f-11e7-82d7-985eeedddb8d.png)

...Riot fails to load and just displays a blank page, because Firefox throws an exception ("The operation is insecure") when accessing window.localStorage at the top of createMatrixClient.js.

**Comment by aaronraimist** [comment]
Related issue about Chrome #3164

**Comment by t3chguy** [comment]
this should be caught by Modernizr and shown a beautifully ugly red page but app load order screws that up.
