### ISSUE TITLE
Invite suggestions are unreliable

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5672]
### Description

When you invite a person to a room and start typing a Matrix ID you get suggestions. However, as you type, sometimes valid suggestions are removed.

### Steps to reproduce

- Create a room
- Press _Invite to this room_
- Write `@riot-bot:matrix` (note that it suggests `@riot-bot:matrix.org`)
- Write `@riot-bot:matrix.o` (note that it no longer suggests `@riot-bot:matrix.org`)

![image](https://user-images.githubusercontent.com/62835/33147387-d735084c-cfc7-11e7-8ca5-e95a137e4eb6.png)
![image](https://user-images.githubusercontent.com/62835/33147406-e9873682-cfc7-11e7-9a00-da53379c567e.png)
![image](https://user-images.githubusercontent.com/62835/33147431-ff30130a-cfc7-11e7-9e89-5b2a3e99d30f.png)
![image](https://user-images.githubusercontent.com/62835/33147442-0d9b98e2-cfc8-11e7-880a-4eff1c5eb145.png)

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by lampholder** [comment]
It's good to see this behaviour spelled out - I've experienced it (and felt it feeling clunky) but it's helpful to see it clearly articulated.

I wonder what we should do instead.

Potentially:
- All the while there's an exact partial match with a known mxid we should probably keep that as the highlighted option.
- If there is no matching known mxid then suggesting the partially completed mxid is _probably_ fine (though only accepting a 'complete' mxid might be better - why am I allowed to invite the obviously-invalid `@riot-bot:matrix`?)

'Completeness' risks being hard to define (is `@riot-bot:matrix.com` complete? If so what about `@riot-bot:matrix.co`?) I guess if we only converted inputs matching `@\w+:\w+\.(any|valid|tld)` into a suggestion we'd be okay?

**Comment by pafcu** [comment]
What is more confusing to me is why a _valid_ suggestion is removed in the first place? (i.e. `@riot-bot:matrix.org` is a perfectly valid suggestion after typing `@riot-bot:matrix.o`, yet it is suddenly no longer offered as an alternative). I can live with some clearly incorrect alternatives being shown, or even highlighted, but please don't remove the correct ones! :-)

Also, the avatar for the suggested "incomplete" mxid annoyingly changes color while you type.

**Comment by aaronraimist** [comment]
This seems to be fixed in the new invite dialog

**Comment by turt2live** [comment]
Yea, if it's still a problem please open a new issue.
