### ISSUE TITLE
Hide server selector doesn't apply to password reset page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5673]
### Description

![image](https://user-images.githubusercontent.com/1190097/33151090-afaed02a-cf93-11e7-9d64-bd02a3ef0cb9.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: chat.tenx.tech

**Comment by turt2live** [comment]
This is an issue specific to tenx and not riot. The option seems to work as intended.

**Comment by ara4n** [comment]
yeah, they forked it unfortunately.
