### ISSUE TITLE
RTE should insert a newline before code block

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5674]
### Description

Markdown requires that the code block triple-backticks start on a new line. However, the code button in the RTE does not add a newline, which may lead to "broken" markdown.

### Steps to reproduce

- Press the "Show Text Formatting Toolbar" button in the RTE 
- Write "foo" in RTE
- Press the '</>' button
- Write "bar"
- Press enter

I expect "bar" to be inside a code block. Instead I get an empty code block at the end (Markdown probably gets confused and thinks the last backticks actually start a codeblock rather than end it).

Actual result:
![image](https://user-images.githubusercontent.com/62835/33163209-9c5e54f6-d02d-11e7-8cd1-507c4cb15bf9.png)

Expected result:
![image](https://user-images.githubusercontent.com/62835/33163218-af850138-d02d-11e7-9547-a5de7e92e144.png)

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by lampholder** [comment]
If I'm understanding http://spec.commonmark.org/0.28/#fenced-code-blocks correctly, fenced code blocks _can_ interrupt paragraphs:

> A fenced code block may interrupt a paragraph, and does not require a blank line either before or after.

Indented code blocks explictly _cannot_ interrupt a paragraph.

However, also from the commonmark spec:

> Unclosed code blocks are closed by the end of the document (or the enclosing block quote or list item)

So your example _does_ highlight a bug in Riot's handling of the markdown - it should close the code block with the end of the document and render as per your expected result :smile:

**Comment by pafcu** [comment]
Ah, so that's different from e.g. GFM where fenced code blocks _can't_ interrupt a paragraph. The joys of Markdown ...```
This should be in a code block
```

**Comment by pafcu** [comment]
Actually the reference implementation at http://spec.commonmark.org/dingus/ also fails so either the reference implementation is wrong, the spec is wrong, or the interpretation of the spec is wrong.

![image](https://user-images.githubusercontent.com/62835/33187387-abf0935c-d091-11e7-8f4e-0b1b47b1905b.png)

**Comment by pafcu** [comment]
A newline should also be inserted when pressing the quote button (if not pressed at the beginning of a line)

**Comment by aaronraimist** [comment]
This seems to work properly in the new composer (you have to select the text that you want to be in the code block now to see the RTE rather than being a button to open a code block like it was previously)
