### ISSUE TITLE
clicking on emoji loses focus

### ISSUE THREAD

**Issue by betz** [vector-im/riot-web#5677]
Describe here the problem that you are experiencing, or the feature you are requesting.
When clicking on a emoji, the focus of the textfield is lost.
This means you have to click back on the textfield after clicking on a emoji.
Smaller issue, but breaks the flow.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5078

**Comment by betz** [comment]
sorry. i did search before submitting a new one, but with the word emoji.
