### ISSUE TITLE
Spurious power-level change when going from standard level to custom level (with same powerlevel)

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5678]
### Description

When changing power level from _Default (0)_ to _Custom (0)_ and then back to _Default_ again a unnecessary change of powerlevel event is shown. This is bad because this may show that someone considered changing someone's power level, but changed their mind.

### Steps to reproduce

- Create a new room
- Invite `@riot-bot:matrix.org`
- Click Riot-bot avatar
- Change powerlevel to _Custom_ (but don't the default value `0`)
- Change back to _Default (0)_
- Observe the event "XXX changed the power level of @riot-bot:matrix.org from Default (0) to Default (0).

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by aaronraimist** [comment]
This was fixed at some point
