### ISSUE TITLE
Ability to somehow share e2e history when migrating accounts

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5680]
Currently if you migrate between HSes you are spectacularly out of luck if you want to keep access to your e2e history. Hopefully being able to invite the new user into the rooms and then proactively share keys to them might help with this.

**Comment by ara4n** [comment]
Actually, i'm an idiot - if you export your megolm keys manually from the old account and import them to the new one, it should just work (modulo history visibility).

**Comment by strypey** [comment]
No, you're not ;) Exporting and importing keys works, but it's time-consuming and potentially confusing for less geeky users. I definitely see value in a simpler UI for verifying that a new account is controlled by the user of the old account, which automates the handover of keys to the new account for decrypting history. Could bits of the device cross-signing logic be used to do this?
