### ISSUE TITLE
When an encrypted room contains unknown devices, the buttons to verify/block are larger than the lines for the devices

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#5683]
Screenshot says it all:
![deepinbildschirmfoto_bereich auswahlen_20171124231048](https://user-images.githubusercontent.com/1236369/33224876-85486684-d16e-11e7-9788-4a658548d7ac.png)

**Comment by lampholder** [comment]
Interesting - I don't think I've noticed this myself (though I'll keep an eye out for it) - perhaps it's a problem that gets more pronounced the more devices there are in the dialogue?

**Comment by zzottel** [comment]
It seems it becomes wrong if there's more than one device per user. See the attached screenshot. All users above those shown in the screenshot looked the same as the first three in the screenshot (which doesn't look perfectly right, either, but at least it's the same for everybody). Then, where the user with the three devices is, it becomes completely wrong.

This is Firefox, btw, same on Windows and Linux, 57 and prior versions.
![2017-11-27 13_55_22-riot](https://user-images.githubusercontent.com/1236369/33267914-7dbba8ea-d37b-11e7-8372-c7843eae56b2.png)

**Comment by zzottel** [comment]
Fixed in 0.14.1 (or earlier).
