### ISSUE TITLE
Invisible scrollbar prevents selecting item near bottom of window in user settings

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5686]
### Description

In the user settings, it is not possible to click on items that are at the very bottom of the window, because they seem to be covered by a `<div class="thumb" style="transform: translateX(0%);"></div>` which seems to capture the clicks.

### Steps to reproduce

- Open user settings
- Scroll contents so that an item is very close to the bottom of the window
- Try clicking on item and observe that nothing happens

E.g. clicking on "Mirror local video feed" in the situation below does nothing:

![image](https://user-images.githubusercontent.com/62835/33232408-3054123e-d206-11e7-93e2-a1e7ff81f33e.png)

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57 and Chrome 62.0.3202.62

**Comment by lampholder** [comment]
I just tried this on 62.0.3202.94 on my mac and it seemed to work:

![click](https://user-images.githubusercontent.com/1922197/33486986-c57fe148-d6a3-11e7-83e4-3a702785b33f.gif)

**Comment by turt2live** [comment]
I can reproduce this on Windows 10 Chrome 62 (also applies to the right side, if you're on a narrow enough screen). Right clicking the unclickable area to get the element reveals it's the Gemini scrollbar container.

**Comment by turt2live** [comment]
Fixed
