### ISSUE TITLE
User settings does not have focus initially

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5688]
### Description

When opening user settings by clicking the cog icon in the left sidebar, the settings area does not initially have focus. Pressing the down arrow on the keyboard does not scroll the view, but instead changes the focused item in the left sidebar. Clicking somewhere in the settings gives it focus and makes it scrollable with the keyboard.

### Steps to reproduce

- Open settings by clicking the settings icon in the left sidebar
- Press keyboard down arrow
- Observe that "Filter Room Names" receives focus in the background, rather than the view scrolling

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by turt2live** [comment]
Fixed (now a dialog)
