### ISSUE TITLE
The autocomplete delay field in user settings is not themed

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5690]
### Description

The autocomplete delay field in user settings is not themed

![image](https://user-images.githubusercontent.com/62835/33234526-9086b126-d228-11e7-80a0-a998d64519d2.png)

It always has a white background.

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by turt2live** [comment]
Fixed
