### ISSUE TITLE
UI suggestion: Use "Show Text Formatting Toolbar" to toggle visibility, rather than having a separate close button

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5693]
### Description

IMHO it would be a lot more convenient to be able to open and close the text formatting toolbar using the same button, rather than revmoving the button that opened it, and having the button to close it in a completely different place. When exploring the UI it is also a hassle, because you can't easily just peek at what the toolbar does: if you open it, you now have to start looking for where the button to close it is, rather than just clicking the same spot again. This also seems rather inconsistent with how these kind of toolbars generally work.

![image showing toolbar closed](https://user-images.githubusercontent.com/62835/33238927-ce4a3f5e-d297-11e7-8cb4-c8cca54fec3f.png)

![image showing toolbar opened](https://user-images.githubusercontent.com/62835/33238923-bfb76a5c-d297-11e7-80d6-30da7c030a90.png)

A separate small issue is the toolbar _also_ includes a button to toggle Markdown on/off. It is confusing to have two buttons on screen that do exactly the same things, as a user will surely wonder if they are somehow different.

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by lampholder** [comment]
100% agreed on both counts.

**Comment by aaronraimist** [comment]
This formatting bar doesn't exist anymore
