### ISSUE TITLE
The Deactivate Account dialog is missing the "X" close button from the top right corner

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5694]
### Description

The Deactivate Account dialog is missing the "X" close button from the  top right corner that all other dialogs have. This is because [DeactiveAccountDialog](https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/views/dialogs/DeactivateAccountDialog.js) does not utilize `BaseDialog` which provides the close button by default.

![image](https://user-images.githubusercontent.com/62835/33239115-a43d290c-d29b-11e7-9e0f-297516492c96.png)

Example of dialog with close button:
![image](https://user-images.githubusercontent.com/62835/33239102-9062a236-d29b-11e7-87ad-515d5c8a86b0.png)

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/5689

**Comment by pafcu** [comment]
Would probably be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1631 which is currently still open

**Comment by pafcu** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1674
