### ISSUE TITLE
Red buttons in status theme have a blue border

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5695]
### Description

It looks like the border color of red buttons in the Status theme is not set correctly:

![image](https://user-images.githubusercontent.com/62835/33239854-6b4e0e4e-d2ab-11e7-986e-3243c684cef1.png)

Perhaps this is intended, but it looks somewhat strange and  in both the light and dark themes the border color of red buttons is red.

**Comment by jryans** [comment]
The Status theme is being removed.
