### ISSUE TITLE
Notifications should support granularity

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5701]
### Description

*Note: this is almost certainly a duplicate of something, although I can't find an appropriate issue at the moment*.

Similar to the new granular settings system, notifications should support a tiered system. There are some aspects of this already (noise levels), however further granularity would be for things like "in this room,  want notifications from bots". 

The scope of this is fairly broad: take all the notification settings and put them at granular levels. The levels would mirror those available in granular settings (per-device, per-room-per-device, per-room-per-account, per-account, per-account-per-room, per-room, defaults). The `config.json` probably doesn't need to be included for this system.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I think the current Notifications system makes this redundant as we prefer simplicity than infinite configurability. Also, Matrix doesn't support per-device push rules so most of this is impossible without that

**Comment by turt2live** [comment]
well, it did support per-device rules before we apparently decided it didn't.

**Comment by t3chguy** [comment]
per-device was never in the spec, was a mystical riot and Synapse concoction.

**Comment by turt2live** [comment]
right, but it was supposed to be in the spec then suddenly it wasn't on any plan and got burninated. Doesn't seem to matter though, I don't remember this issue from 2017 at all.
