### ISSUE TITLE
Groups and ILAG play badly when linking to a group page

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5705]
If you go to https://riot.im/app/#/group/+matrix:matrix.org in an anonymous tab, you get prompted by ILAG to pick a nick (why?), and then you find yourself in a conversation with Riotbot being asked to pick a nick again... and have totally lost the +matrix:matrix.org group by this point.  This is a terrible experience for a community who wish to say "just go to https://riot.im/app/#/group/+matrix:matrix.org to join the Matrix community!" to Joe Public.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5650

**Comment by ara4n** [comment]
thanks.
