### ISSUE TITLE
Quoting messages with underscores leads to extraneous backslashes

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5711]
![image](https://user-images.githubusercontent.com/1190097/33330572-675d2294-d41c-11e7-8777-5e31c9ec24f6.png)

**Comment by richvdh** [comment]
presumably this is related to https://github.com/vector-im/riot-web/issues/4809

**Comment by lampholder** [comment]
I think this is a straight dup of #4809

**Comment by turt2live** [comment]
I'm a bit skeptical it's a duplicate, but it's certainly related. Will wait for a fix on #4809 before re-opening though.
