### ISSUE TITLE
[Granular Settings] Lack of audio notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5713]
### Description

This is affecting at least me. The default notification structure should enable audio notifications, but I'm not hearing them on multiple devices.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I've awkwardly triaged this as a feature/bug - I think the current noisy notification UX is highly confusing (so confusing I have no idea what the intended behaviour is).

P3 'cause we're not committed to addressing this in the immediate term, but it _is_ important.

**Comment by turt2live** [comment]
This appears to be due to my lack of understanding on how the settings work together. There's no behaviour change before and after granular settings as far as I can tell.
