### ISSUE TITLE
[Regression] Clicking "Permalink" in the context menu opens a new tab

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5715]
### Description

Clicking permalink used to just permalink the message in the current view, now it opens a new tab.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
What did it used to do? Put the link in the message composer?

**Comment by turt2live** [comment]
> Clicking permalink used to just permalink the message in the current view

**Comment by turt2live** [comment]
It's now "Share Message" with a helpful popup.
