### ISSUE TITLE
Flair hide/display user settings tweaks.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5721]
I think there are some good tweaks we could make to the UX to make it a better experience for users on slower connections (or talking to slower homeservers).

- [ ] disable the checkbox whilst the state is loading
- [ ] disable the checkbox whilst a state-change request is being processed
- [ ] modify the UX to let users know the checkbox is in a 'persisting to the server' state
- [ ] make clicking the label text also change the checkbox state

Fiddling with a fiddle: https://jsfiddle.net/8kk3fhvd/ - I think changing the full label text is jarring and bad; perhaps changing the checkbox for a spinner would be better?

**Comment by lampholder** [comment]
The experience of the current impl seems better now than it did when I tried it first thing this morning. Maybe something's already been changed?

**Comment by turt2live** [comment]
There's also the approach I'm taking in tabbed settings: https://jsfiddle.net/turt2live/uzgfovsg/2/

**Comment by turt2live** [comment]
We did this
