### ISSUE TITLE
[Granular Settings] /tint doesn't work with granular settings when only specifying one color

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5726]
### Description

The tinting code was modified to require both colors, however previous versions made the secondary color optional. This optional parameter was made required as part of granular settings.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
According to that PR this is fixed
