### ISSUE TITLE
Presence status is completely wrong

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5727]
### Description

For some rooms I'm offline, some I'm away, and some can't decide while I'm typing. Something is very wrong with the logic.

*Note: I'll look into this as part of my 'fix riot' sprint*

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I'm guessing you mean on a homeserver that is configured with presence enabled?

**Comment by turt2live** [comment]
Yes, my own in this case. For reference, here's some of the behaviour I'm seeing:

* Randomly considered "offline" when switching rooms, never updating to "away" or even "online"
* Occasionally considered "away" even while actively using the app

It's possible this is the result of riot-web conflicting with another app/client (like another browser or even my android phone). The expected behaviour is:
* Show as "Offline" only when the user has specifically asked to be shown as offline (or when the app is closed)
* Show as "Away" when the user hasn't used the app in a while
* Show as "Online" when the user is currently using the app. Ie: typing, scrolling, moving around, etc.

**Comment by turt2live** [comment]
This is pretty bad.
![image](https://user-images.githubusercontent.com/1190097/33971030-9257ad16-e033-11e7-8027-c619f71e1ee3.png)

It's probably best to back out of the PR I wrote for prensece management. I'll open a PR sometime this week(end) to do just that.

**Comment by dbkr** [comment]
This should be fixed now https://github.com/vector-im/riot-web/pull/5881 and https://github.com/matrix-org/matrix-react-sdk/pull/1676 are merged
