### ISSUE TITLE
Notifications/unread messages should bubble up to LLP

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5729]
### Description

*LLS = Left Left Sidebar*

When I'm pinged in a room, show that on the community. Also show me that I have unread messages in that community.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by grahamperrin** [comment]
> … When I'm pinged …

Also I'd like the GUI to offer something useful when a keyword is mentioned; so that I can find the mention after the event. Should this be a separate issue?

**Comment by turt2live** [comment]
This got fixed in the redesign.
