### ISSUE TITLE
Can't distinguish the room list from the timeline on the dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5735]
### Description

All of the categories have turned to the same color as the background color. Previously it was hard to distinguish, but was possible because the categories where lighter grey. On the light theme, the sidebar is a different color from the timeline, making it clearly distinguishable. The dark theme could use a simple 1px right border or a slightly lighter overall background color to help distinguish it.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by JigmeDatse** [comment]
I find this design change is worst on the dark theme.  The light and status.im themes at least distinguish the room list, and timeline clearly.  That makes the lack of distinction between the room groups headings and list of rooms less of a "it's all the same thing".  Putting some distinction there would be very helpful for me.

**Comment by ara4n** [comment]
the re-design isn't finished. don't panic!

**Comment by JigmeDatse** [comment]
Nope, no panic.  Just putting it out there.

**Comment by turt2live** [comment]
Went with a border. Fixed via https://github.com/vector-im/riot-web/pull/6194
