### ISSUE TITLE
All Riot-Web dialogs have partially broken keyboard support

### ISSUE THREAD

**Issue by pvagner** [vector-im/riot-web#5736]
### Description

Riot displays OK / Cancel dialogs or dialogs with other context sensitive buttons on a lot of places. E.g. going to Settings and clicking the button Logout or opening room settings and clicking Leave button display one.
These dialogs are consuming some key presses e.g. the enter key in an unexpected way.

### Steps to reproduce

- Open an empty room or any other room you don't mind leaving
- On the room header bar click the Settings button
- In the Room settings window click the leave button
- Notice the dialog with Leave and Cancel buttons but don't yet click either of those buttons
- Use the tab or shift+tab keyboard shortcuts to navigate until the Cancel button receives the focus
- With Cancel button having the focus now press the enter key.

Pressing the enter key dismisses the dialog the same way as I would have clicked the Leave button however focusing on the Cancel button immediatelly before pressing the enter key I had an intention to click on the cancel button.

Log: not sent

### Version information

- **Platform**: tested on the web (in-browser) however I expect the desktop to work the same way

For the web app:

- **Browser**: Firefox 57 on Linux however I expect most of them to work like this
- **OS**: Arch Linux
- **URL**: Riot-Web 0.13.2

**Comment by lampholder** [comment]
YUCK.

**Comment by lampholder** [comment]
I think the intent is clear - <kbd>Enter</kbd> should "choose the default" on modals. Except that should not happen if the user has intentionally selected any of the other buttons on the modal with the keyboard.

How tractable is that?

**Comment by pvagner** [comment]
Several points so we can easier agree on what's good and what is not.

- Simple dialogs should only allow focussing buttons e.g. OK button and a Cancel button.
- Dialogs which collect some data e.g. login dialog which may display other interactive controls such as text entry fields and checkboxes should embed a form where we can use onSubmit handler to receive this feature for free.

However by removing enter key handling from the BaseDialog component another issue pops up which is even more critical. The dialog reappears when exited via the enter key press. If the dialog is exited via spacebar press or via mouse click it is not shown again.
