### ISSUE TITLE
Integrating Tools

### ISSUE THREAD

**Issue by psyapathy** [vector-im/riot-web#5740]
```
Integrating Tools

    It can be hard for a team to be effective without tools: pick up what you need from our ready-to-use list of bots integrating with the likes of Github and others.
```

Hi. Can I get somewhere the source code of the bots (integration tools) available in a riot.im/app to use on my Riot? Thank you

**Comment by uhoreg** [comment]
The issue tracker isn't the right place to ask questions like this.  You're more likely to get help for this sort of thing by asking in the #riot:matrix.org or #matrix:matrix.org rooms.

But anyways, the code for the bots is available at https://github.com/matrix-org/go-neb.  The IRC/Slack/Gitter integrations are separate, and are at https://github.com/matrix-org/matrix-appservice-irc, https://github.com/matrix-org/matrix-appservice-slack, and https://github.com/matrix-org/matrix-appservice-gitter respectively.  The integration manager does not have source code available, but you can use an alternative implementation that you can find at https://dimension.t2bot.io/.
