### ISSUE TITLE
How post images into chat by link?

### ISSUE THREAD

**Issue by psyapathy** [vector-im/riot-web#5741]
Hello!
How post images into chat by link?
http or mxc?

Show me format please..

Image on server. In path /images/1.png

Is it possible?

**Comment by t3chguy** [comment]
Riot only renders inline images if they are MXC urls. https://matrix.org/docs/spec/client_server/r0.3.0.html#id66

TLDR, upload an image into any room, look at the event of that image, it'll contain an mxc url and then you can use Markdown syntax to inline the image in using that MXC url.
