### ISSUE TITLE
Thumbnail image uploaded from riot-web are blank

### ISSUE THREAD

**Issue by 2Belette** [vector-im/riot-web#5745]
They are blank on riot-web, riot-desktop and android app when the image is uploaded from riot-web only.

Thumbnail appear correctly when the image is uploaded from android app or riot-destktop under the same matrix home server.

The result:
![2017-11-30-12 03 00](https://user-images.githubusercontent.com/2325706/33428590-add43560-d5c9-11e7-9f10-981323f48c52.png)

Same issue on riot-web 0.13.1 and 0.13.2

**Comment by ara4n** [comment]
which browser is this? please can you submit a bug report from it, referencing this bug?

**Comment by 2Belette** [comment]
I forgot the browser version, sorry:
iceweasel (firefox) 52.5.0 (64-bit) (ESR)

**Comment by 2Belette** [comment]
> please can you submit a bug report from it, referencing this bug?

@ara4n  where do you want me to submit a bug report?

**Comment by ara4n** [comment]
okay - please can you submit a bug report from UserSettings in the app? I'm wondering if IceWeasel has some of WebCrypto turned off for whatever IPR reason.

**Comment by 2Belette** [comment]
by the way and perhaps enough for you (let me know)
I realized 2 things:
-working on the latest 57.0.1 Firefox version
-working on my IceWeasel ESR version (52.5) only if the room/chat is unencrypted, it appears to be an issue on e2e only.

**Comment by turt2live** [comment]
When you see the issue, go to your user settings and scroll to the bottom. There should be a bright red "Report It" button. Click that and send logs - it helps the team troubleshoot the problem.

**Comment by 2Belette** [comment]
I just sent it and put in the comment this issue on github

**Comment by 2Belette** [comment]
@ara4n for your information, I just confirmed that the issue appears only when E2E is activated (which is the case on all my rooms or direct chat).
I created another room without E2E and thumbnail is displaying OK everywhere (from riot-web itself and on riot-desktop + android riot.im)

**Comment by 2Belette** [comment]
any other tests you'll willing me to do? (I guess you have been able to reproduce it as I saw p2 label on it?)
many thanks

**Comment by 2Belette** [comment]
I am still experimenting the same issue on riot-web version: 0.14.2 have you been able to figure out the issue or do you want me to help you test anything?

many thanks
