### ISSUE TITLE
creak says inviting new users via mxid breaks

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5747]
here's what happenning in a few bullet points:
	•	ask a friend to create an account and give me the matrix identifier
	•	click "Invite in this room" and enter "@my_friend_username:matrix.org"
	•	see that the user is invited in the user list
	•	hear the user complaining he didn't receive an invitation

workaround: invite using the email

**Comment by romainf-unity** [comment]
### Description

I can't invite my friends using their freshly newly created matrix IDs. It seems to work, but my friend never receive the invitation. But if I use the e-mail, it works.

### Steps to reproduce

- ask a friend to create an account and give me the matrix identifier
- click "Invite in this room" and enter "@my_friend_username:matrix.org"
- see that the user is invited in the user list
- hear the user saying he didn't receive an invitation

Workaround: invite using the email

(all done on matrix.org, verified the ID case twice)



### Version information



- **Platform**: desktop?
- **OS**: macOS
- **Version**: 0.13.1

**Comment by MightyCreak** [comment]
(re-post with the right GH account)



### Description

I can't invite my friends using their freshly newly created matrix IDs. It seems to work, but my friend never receive the invitation. But if I use the e-mail, it works.

### Steps to reproduce

- ask a friend to create an account and give me the matrix identifier
- click "Invite in this room" and enter "@my_friend_username:matrix.org"
- see that the user is invited in the user list
- hear the user saying he didn't receive an invitation

Workaround: invite using the email

(all done on matrix.org, verified the ID case twice)



### Version information



- **Platform**: desktop?
- **OS**: macOS
- **Version**: 0.13.1

**Comment by turt2live** [comment]
I'm unable to reproduce this, and without additional information there's not much to try and explore. This is a possible case sensitivity issue, though.
