### ISSUE TITLE
widgets steal focus when you switch to the room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5754]
if you have etherpad or googdocs or whatever in a room, it's pretty annoying that if you switch to the room and start typing it goes into the widget rather than composer. composer should steal back focus or something even if there's a widget present

**Comment by MTRNord** [comment]
I think this is a duplicate but I dont remember the other issue number

**Comment by t3chguy** [comment]
Related to #5130

**Comment by ara4n** [comment]
pretty much a dup of #5130 - thanks
