### ISSUE TITLE
Roomlist panel fonts look kinda goopy on the status theme

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5757]
![image](https://user-images.githubusercontent.com/1922197/33492337-a81e3fa8-d6b4-11e7-8141-8374feae0afd.png)

Particularly the section headings.

Fonts are clean and crisp on light theme:
![image](https://user-images.githubusercontent.com/1922197/33492391-d88ae6aa-d6b4-11e7-8d3b-7f09215210b3.png)

**Comment by turt2live** [comment]
I have this same problem on Windows 10 Chrome 62, although not as bad:
![image](https://user-images.githubusercontent.com/1190097/33492540-8991a60e-d67a-11e7-900f-5966bb0fde8b.png)

**Comment by lampholder** [comment]
I should have said I'm currently on Windows 10 Chrome 62 too 😄 

I suspect this might be something to do with `-webkit-font-smoothing: subpixel antialiased` and @ara4n having a retina display and me not 😛

**Comment by uhoreg** [comment]
see https://makandracards.com/makandra/2605-improve-web-font-rendering-in-windows-by-autohinting-fonts, which says:

> Linux and MacOS ignore hinting information in font files and replace it with auto-hinting, an algorithm that works better than embedded hinting most of the time. Windows does not employ auto-hinting, causing horrible rendering for most fonts.

(though the article is 6 years old)  The article also points at an auto-hinting tool, so it may be worth running the font through that and seeing if it looks better on Windows.

**Comment by jryans** [comment]
The Status theme is being removed.
