### ISSUE TITLE
"more rooms" indicator arrow on status theme is hard to read (and a bit out of place)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5758]
### Description

This is what it looks like isolated:
![image](https://user-images.githubusercontent.com/1190097/33492568-a240c540-d67a-11e7-9810-348a61f97172.png)

And here it is amoung rooms:
![image](https://user-images.githubusercontent.com/1190097/33492587-b123c652-d67a-11e7-8564-6a0560c1208c.png)

The grey background makes it hard to see and almost feels out of place.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by jryans** [comment]
The Status theme is being removed.
