### ISSUE TITLE
Clicking "Jump to read receipt" closes MemberInfo

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5760]
### Description

This is a bit surprising, and I feel it should probably stay open.

### Steps to reproduce

- Open a member's info
- Click "Jump to read receipt"
- Note that the member info closes

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Agreed - it would be more like the other buttons MemberInfo then (hence less surprising).

**Comment by t3chguy** [comment]
not the eziest, looked at it last night thinking it was a quickfix :(

**Comment by t3chguy** [comment]
This also happens with MemberInfo + clicking on permalink/timestamp

**Comment by t3chguy** [comment]
This happens because `<RoomView />` is keyed by roomId, so whenever Room ID changes, the state is wiped out

**Comment by aaronraimist** [comment]
Seems to be fixed

**Comment by turt2live** [comment]
indeed
