### ISSUE TITLE
Read receipts should appear on the last visible event instead of disappearing into the ether

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5761]
### Description

Here's a screenshot from #riot: 
![image](https://user-images.githubusercontent.com/1190097/33504672-96818a02-d6a5-11e7-8b82-8aa08a553156.png)

In this screenshot, Matthew sent a message and has not read anything (as far as I can tell). Doing a bit of investigation, I can see that Matthew's read receipt is at `$1512163962601724BjrBV:matrix.org` which happens to be this event:
```
synapse=# select event_id, room_id, type, content from events where event_id = '$1512163962601724BjrBV:matrix.org';
             event_id              |            room_id             |             type             |      content
-----------------------------------+--------------------------------+------------------------------+-------------------
 $1512163962601724BjrBV:matrix.org | !DgvjtOljKujDBrxyHk:matrix.org | org.matrix.room.preview_urls | {"disable":false}
(1 row)
```

That particular event happens to fit in between Matthew's message and my first message. Matthew's read receipt should probably still appear on his original message as Riot has no way of communicating to the user that there's a hidden event, and missing read receipts feels buggy.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
see also: #3511 and #948
