### ISSUE TITLE
Can't manage Travis Integration anymore

### ISSUE THREAD

**Issue by Croydon** [vector-im/riot-web#5764]
### Description

I have added Travis Integration to a room. Directly after adding it I was able to edit the settings.
Since I first left the Travis integration settings page I was never able to return to it.

### Steps to reproduce

I'm not sure yet if this is constantly reproduceable or a result of specific settings.
If it is it would be:
- Add Travis integration to a room
- Change settings
  - I don't remember exactly anymore what I have done, but it should be:
  - adding several repositories + entering a default repository
- Save and close this page
- Try to reopen the page
- Page doesn't load, internal error, Riot completely freezes till a restart (Desktop), reload (web)

Describe how what happens differs from what you expected.

Web console output after click on the Travis integration:

>04:23:49.127
Object { error: "Bridge returned HTTP 404 Not Found: Link not found" }
GitterScalarApi.js:27:16
04:23:49.131
Bridge returned HTTP 404 Not Found: Link not found
GitterScalarApi.js:29:20
04:23:49.139
Object { error: "Bridge returned HTTP 404 Not Found: Link not found" }
SlackScalarApi.js:27:16
04:23:49.141
Bridge returned HTTP 404 Not Found: Link not found
SlackScalarApi.js:29:20
04:23:49.151 membership_state of @_neb_travisci_=40_croydon=3amatrix.org:matrix.org in room !ARHzPSDZjqBqrKeAap:matrix.org requested.
rageshake.js:65:16
04:23:49.152 membership_state of @_neb_rssbot_=40_croydon=3amatrix.org:matrix.org in room !ARHzPSDZjqBqrKeAap:matrix.org requested.
rageshake.js:65:16
04:23:53.074
TypeError: t.data is undefined
[Learn More]
TravisCIComponent.js:297:30
04:23:53.126 Unhandled rejection _updateRenderedComponent@https://scalar.vector.im/scalar.bundle.js:69:25871
_performComponentUpdate@https://scalar.vector.im/scalar.bundle.js:69:25694
updateComponent@https://scalar.vector.im/scalar.bundle.js:69:24972
performUpdateIfNecessary@https://scalar.vector.im/scalar.bundle.js:69:24299
performUpdateIfNecessary@https://scalar.vector.im/scalar.bundle.js:7:1079
s@https://scalar.vector.im/scalar.bundle.js:6:10552
perform@https://scalar.vector.im/scalar.bundle.js:20:6154
perform@https://scalar.vector.im/scalar.bundle.js:20:6154
perform@https://scalar.vector.im/scalar.bundle.js:6:11701
S@https://scalar.vector.im/scalar.bundle.js:6:11878
closeAll@https://scalar.vector.im/scalar.bundle.js:20:6742
perform@https://scalar.vector.im/scalar.bundle.js:20:6234
batchedUpdates@https://scalar.vector.im/scalar.bundle.js:70:16069
u@https://scalar.vector.im/scalar.bundle.js:6:10834
r@https://scalar.vector.im/scalar.bundle.js:20:18581
enqueueSetState@https://scalar.vector.im/scalar.bundle.js:20:19718
r.prototype.setState@https://scalar.vector.im/scalar.bundle.js:35:6749
_getWebhookUrl/<@https://scalar.vector.im/scalar.bundle.js:64:27199
o@https://scalar.vector.im/scalar.bundle.js:1:10711
e.exports/i.prototype._settlePromiseFromHandler@https://scalar.vector.im/scalar.bundle.js:66:27180
e.exports/i.prototype._settlePromise@https://scalar.vector.im/scalar.bundle.js:66:27983
e.exports/i.prototype._settlePromise0@https://scalar.vector.im/scalar.bundle.js:66:28684
e.exports/i.prototype._settlePromises@https://scalar.vector.im/scalar.bundle.js:66:30014
e.exports/i.prototype._fulfill@https://scalar.vector.im/scalar.bundle.js:66:29055
e.exports/i.prototype._resolveCallback@https://scalar.vector.im/scalar.bundle.js:66:25916
e.exports/i.prototype._settlePromiseFromHandler@https://scalar.vector.im/scalar.bundle.js:66:27338
e.exports/i.prototype._settlePromise@https://scalar.vector.im/scalar.bundle.js:66:27983
e.exports/i.prototype._settlePromise0@https://scalar.vector.im/scalar.bundle.js:66:28684
e.exports/i.prototype._settlePromises@https://scalar.vector.im/scalar.bundle.js:66:30014
e.exports/i.prototype._fulfill@https://scalar.vector.im/scalar.bundle.js:66:29055
i/<@https://scalar.vector.im/scalar.bundle.js:34:13678
u@https://scalar.vector.im/scalar.bundle.js:67:27933
r@https://scalar.vector.im/scalar.bundle.js:67:27364

### Version information

- **Platform**: on web AND desktop

Version matrix-react-sdk: 0.11.2
Version riot-web: 0.13.2
Version olm: 2.2.1

**Comment by lukebarnard1** [comment]
I can't see a `t.data` in the current code, or previous versions of the file where the error happened. It does seem similar to https://github.com/vector-im/riot-web/issues/6043, which was fixed.

**Comment by lanker** [comment]
I can confirm being able to access Travis settings on /develop now (had the same issue as reported here previously).

**Comment by lukebarnard1** [comment]
Okay, then I'll close this. Thanks @lanker
