### ISSUE TITLE
Long homeserver domain names and internationalisation to longer languages (like French) break "Sign in with" box

### ISSUE THREAD

**Issue by justin-sleep** [vector-im/riot-web#5767]
### Description
Riot's login page has a "Sign in with" box, which lists the options to authenticate with.  The text overflows out of the box when the domain name is too long.

### Steps to reproduce

- Point Riot to a homeserver with a long domain name

![2017-12-01-19 51 54](https://user-images.githubusercontent.com/14955039/33517590-920a2892-d74c-11e7-8941-a9cb6d6bb713.png)

### Version information

Web, 0.13.2 

Present on latest versions of Chromium and Firefox.

**Comment by lampholder** [comment]
Quick fix: truncate with ellipsis.

Controversial longer fix: bring back the enhanced user name button that I mooted at some point in the past with the @ and the domain baked into the username field (I think people didn't like it):

`[@| User name |:matrix.org]`

`[@| User name |:lant.uk]`

**Comment by pafcu** [comment]
This is a common problem all around Riot and there are several related issues with the same symptoms (e.g. text does not fit into combobox). It seems like a generic solution is needed, so probably the ellipsis one is the best (although certainly it is possible to additionally special case this one)

**Comment by ara4n** [comment]
ellipsising ftw for now

**Comment by turt2live** [comment]
The whole dropdown can probably be removed when #7520 is implemented

**Comment by turt2live** [comment]
Conclusion: we're going to use an ellipsis and punt the remainder to the redesign (https://github.com/vector-im/riot-web/issues/7586)

**Comment by turt2live** [comment]
This was actually fixed long ago by https://github.com/vector-im/riot-web/pull/6244
