### ISSUE TITLE
VectorCustomServerDialog.js uses `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5772]
`src/components/views/login/VectorCustomServerDialog.js` uses dangerouslySetInnerHTML rather than the safer and more "standard" way of using `_t()` to insert React components. It is also inconsistent with how the almost identical `src/components/views/login/CustomServerDialog.js` (does it one paragraph at a time) which means that it is more difficult to re-use translation (although which one is "more correct" is up for debate")

**Comment by turt2live** [comment]
Not anymore!
