### ISSUE TITLE
Unable to decline invitation to a room via irc bridge.

### ISSUE THREAD

**Issue by marudor** [vector-im/riot-web#5774]
### Description

Unable to decline invitation to a room via irc bridge.

### Steps to reproduce

- Join a room that needs invite
- try to decline the invitation you get (nothing happends)
- try to accept the invitaton - you get forbidden, invitation stays

Describe how what happens differs from what you expected.

Declining should remove the invitation

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome 62.0.3202.94
- **OS**: macOS
- **URL**: riot.im/develop & riot.im/app

Also on riot-ios

**Comment by t3chguy** [comment]
This is a synapse bug, try clear client cache in settings

**Comment by marudor** [comment]
This worked. Thanks.
Maybe there should be a hint to clear the cache if it breaks?
