### ISSUE TITLE
we no longer have any spinner or feedback when you try to login

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5779]
in normal skin, type username<tab>password<tab><enter> and there is no UI feedback

**Comment by turt2live** [comment]
GitHub ate the angle brackets, but there's some keyboard navigation between the words there (`<tab>` mostly)

**Comment by lampholder** [comment]
I'm guessing you mean in the window between the credentials' being accepted and the app starting to load?

So, presumably more noticable on slow connections?

**Comment by turt2live** [comment]
the spinner between *submitting* your credentials and the app begining to load. It's noticable on all connections.

**Comment by lukebarnard1** [comment]
This was caused by https://github.com/matrix-org/matrix-react-sdk/commit/67cc02df3b3a938972fcf33969fa9bdb00b8e841#diff-05ab68aa5adaf79f75347e30e4e0b588
, which shows the `{ loader }` being removed. This would've been picked up by linting :innocent: 

(@ara4n adding some status.im-related stuff)
