### ISSUE TITLE
Where riot-web takes the update information?

### ISSUE THREAD

**Issue by psyapathy** [vector-im/riot-web#5785]
Hi friends!
Tell me please. Where riot-web takes the update information while trying to find updates in the settings? Can I specify the update path somewhere in the code? To update my modified client riot on my new  versions?

For example, I want that client did not take the updates from riots.im, but takes updates from localhost
Thank you advance

**Comment by t3chguy** [comment]
the web version looks for a /version file in the same directory as the webapp and shows an update if the version file has changed during the session

the desktop version has its update location in config.json, which is a build config rather than a user config.

**Comment by t3chguy** [comment]
This sort of question belongs more in `#riot:matrix.org` rather than here
