### ISSUE TITLE
No caret after emoji in RTE

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5787]
### Description

After selecting an emoji, and re-clicking the text entry field to give it focus, I don't see any caret to indicate that I can continue typing. The caret reapperas once I type something after the emoji.

![I should see a caret after the emoji](https://user-images.githubusercontent.com/62835/33657893-04fd3e4e-da7b-11e7-86e5-129eafcd5398.png)

![Caret after normal text](https://user-images.githubusercontent.com/62835/33658149-f9856612-da7b-11e7-8e66-0110df0f2da9.png)

### Steps to reproduce

- Type e.g. `:thumb` and select the first emoji
- Click message entry field again
- Notice lack of caret
- Type something, notice that the caret appears

I expect a caret to be visible also after emojies.

### Version information

- **Browser**: Firefox 57
- **OS**: Linux
- **URL**: riot.im/develop 9835e2e0b491-react-9eb334a1d404-js-020b29306839

**Comment by lampholder** [comment]
I can confirm that this happens in FF and not in Chrome

**Comment by gergelypolonkai** [comment]
It’s the same for me using the Electron app.

**Comment by t3chguy** [comment]
likewise

**Comment by tschopo** [comment]
Also it wold be nice if you can just continue typing after selecting the emoji and don't have to re-click the text field.

**Comment by ara4n** [comment]
fixed by matrix-org/matrix-react-sdk#1890
