### ISSUE TITLE
Suggestion: Make it more clear that the headings in the left sidebar are tags

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5789]
### Description

Currently it is not very clear that the headings in the left sidebar are actually tags, which leads to some confusion regarding how rooms work in Riot (e.g. thinking that things listed under People are actual people, rather than rooms including people, or thinking people and rooms are somehow fundamentally different in other ways). Perhaps adding a small tag/label icon next to the heading would make it more apparent that they are simply tags. Something like http://fontawesome.io/icon/tag/

**Comment by lampholder** [comment]
Something like this might be helpful, esp. as we figure out the exact mental models we hope/expect our users to manage as they wrangle groups/tags/filtering the UX with the LLS.

**Comment by turt2live** [comment]
Now that tags are a special feature in Riot, how comfortable are you with this being clear enough @lampholder ?

**Comment by lampholder** [comment]
I think the new design removes all of this ambiguity, so we can close this.
