### ISSUE TITLE
Adding rooms to a community should not suggest rooms I've queued for adding

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5792]
### Description

![image](https://user-images.githubusercontent.com/1190097/33678805-249d8da4-da7a-11e7-8575-ac8276e85862.png)
Hopefully a picture is worth a thousand words here.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I think this applies more generically to that component, don't suggest things that have already been chosen
