### ISSUE TITLE
Changes to community avatar do not update the LLS

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5793]
### Description

![image](https://user-images.githubusercontent.com/1190097/33678944-92b00b46-da7a-11e7-918d-bda6622d9ab3.png)

Note the distinct lack of the beaker on the left side.

### Steps to reproduce

- Create a new community
- Give the community an avatar
- Try to find your beaker in the left side

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
@lukebarnard1 is this a caching thing (i.e. will the beaker come through in ~30 minutes?).

I always lose patience and just refresh the UI :S

**Comment by lukebarnard1** [comment]
It is a caching thing - it uses the same cache as Flair. I'm planning on making the FlairStore a Real Store so that it can push updates to the view _and_ do caching.

**Comment by turt2live** [comment]
Fixed at some point down the line.

**Comment by lukebarnard1** [comment]
This was actually a dup of https://github.com/vector-im/riot-web/issues/6189 - fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1783
