### ISSUE TITLE
RTE buttons for bold, italic, etc. do not change text formatting when Markdown is disabled

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5802]
### Description

The RTE shows buttons for bold, italic, etc. even when Markdown is disabled. Clicking them does not actually seem to do anything.

### Steps to reproduce

- Click Markdown button in RTE to disable Markdown
- Click Show Text Formatting Toolbar
- Click e.g. bold
- Notice that your text is not modified in any way

![image](https://user-images.githubusercontent.com/62835/33803379-ddb0fc74-dd8e-11e7-801c-0d0d421b32a0.png)

### Version information

- **Platform**: web

- **Browser**: Firefox 57
- **OS**:  Linux
- **URL**: riot.im/develop

**Comment by uhoreg** [comment]
The buttons are supposed to change the text style (and the do so for me in the desktop version).  Did you type anything after clicking the buttons?

**Comment by pafcu** [comment]
Apparently I did not. :man_facepalming:
