### ISSUE TITLE
Firefox 57 crashes if avatar selection is canceled

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5806]
### Description

More a bug in Firefox, but documenting here anyway:

Clicking on the avatar selector in User or Room settings opens a file selection dialog. Clicking cancel causes Firefox to crash. Chrome works correctly.

### Steps to reproduce

- Open user settings
- Click user avatar to open file selector
- Click cancel
- Observe crash

### Version information

- **Platform**: web

- **Browser**: Firefox 57
- **OS**: openSUSE Tumbleweed
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Fwiw this doesn't happen with Firefox 59 (a different version of Firefox) on a mac (a different oS)

**Comment by vurpo** [comment]
Can't reproduce on Firefox 65, Fedora 29 with Gnome (Wayland)

**Comment by Cadair** [comment]
Can not reproduce on FF 65 on arch linux with plasma

**Comment by turt2live** [comment]
Going to consider it magically fixed, or a browser issue. If it continues, please open a new issue.
