### ISSUE TITLE
maybe hide the 'historical' group if it is empty

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5810]
as it isn't clear what it does.  Also add some help text

**Comment by turt2live** [comment]
As a bit of feedback on the historical section in general: I don't find it helpful. The only times I've used it are when I've accidentally clicked on it.

**Comment by MTRNord** [comment]
It also feels very slow if I want to use it. (which is why I don't use it so often)

**Comment by turt2live** [comment]
We do this
