### ISSUE TITLE
Offer to reduce image size on uploading

### ISSUE THREAD

**Issue by grafenhofer** [vector-im/riot-web#5813]
In the Android version a resolution reduction is suggested before uploading a picture. This feature would be very helpful to have in the web client too, especially since image sizes can be huge when coming from high resolution cameras.

**Comment by uhoreg** [comment]
somewhat related to https://github.com/vector-im/riot-web/issues/4426

**Comment by pafcu** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4144

**Comment by uhoreg** [comment]
Good catch, @pafcu .  Closing.
