### ISSUE TITLE
Quick-edit for a group on the LLP

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5818]
### Description

This doesn't necessarily mean having the option to edit the name/avatar, but there should be a button to go to the edit page from the LLP. Something like right-click or a floating ellipsis to get a context menu.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Whether or not this is a good idea depends on whether we intend for the items on the left to represent groups, or something else.

If we want to reinforce a different mental model, of the LLP items' being a filter (potentially comprising multiple groups and/or some per-user additions) then we need to be careful about conflating those LLP items with groups.

Of course today those LLP items _are_ groups - if that stays the same then a link to the group edit page makes perfect sense.

**Comment by turt2live** [comment]
Now that the groups have a context menu with an option to go to the community page, I feel this is done. Feel free to re-open if there's disagreement :)
