### ISSUE TITLE
Display name text field in settings does not immediately strip formatting 

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5825]
### Description

If you paste some text that happened to be a link in the Display name field in the User settings, the formatting is preserved. Once the field loses focus, the formatting is removed, so not a huge issue. But it does look strange.

### Steps to reproduce

- Copy text containing a link from a webpage
- Paste into display name field

![image](https://user-images.githubusercontent.com/62835/33903030-2be47620-df77-11e7-8b4c-7e2e7e99a8ba.png)

### Version information

- **Platform**: web

- **Browser**: Firefox 57
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by pafcu** [comment]
The underlying reason is of course that Riot uses `contentEditable` divs, rather than actual text inputs. Is there a reason for that?

**Comment by turt2live** [comment]
It's a regular input now
