### ISSUE TITLE
Display names are vulnerable to homoglyph attacks

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5826]
### Description

When two users have the same display name Riot disambiguates them by showing the full mxid. However, a user can have a display name that _looks_ identical to someone else, by substituting e.g. latin letters with similar cyrillic ones. Thus, a user is lead to believe that a message from "Mаrk" is actually from "Mark". The disambiguation algorithm should take homoglyphs into account.

### Steps to reproduce

- Set display name of a user to "Mаrk" (with a cyrillic а)
- Set display name of another user to "Mark" (with a normal a)
- Observe that messages from both users look identical

![image](https://user-images.githubusercontent.com/62835/33903890-17f7cb50-df7a-11e7-8b8a-138ea9c1e788.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This is perhaps (yet) another argument for their also being a numeric disambiguation component to mxids.

**Comment by pafcu** [comment]
Could we get a `security` label as well? I feel like impersonating users is a security problem.

**Comment by lampholder** [comment]
AH, no, I was misbraining.

The homoglyph attack in mxids is already sidestepped by only allowing a restricted set of characters.

We _don't_ place these restrictions on display names, hence the problem.

This isn't an easy problem to solve I think:
- restricting character set for display names is very restrictive, esp for people with non-latin alphabet names
- hashing display names to generate a disambiguation visual indicator (like a colour) increases the complexity of a homoglyph attack but doesn't eradicate it entirely
- homoglyph-aware string comparison sounds like it could improve the situation but will be very difficult to make water tight

**Comment by lampholder** [comment]
> Could we get a `security` label as well? I feel like impersonating users is a security problem.

Absolutely.

**Comment by pafcu** [comment]
> homoglyph-aware string comparison sounds like it could improve the situation but will be very difficult to make water tight

This is a fairly well known issue, and has been "solved" by standard character lists (http://www.unicode.org/reports/tr36/). There is even a module for it on npm (https://www.npmjs.com/package/unicode-confusables-data). I tried to fix it, but had to give up to just how aweful the state of the JS ecosystem is (basically webpack can't load that npm module).

**Comment by lampholder** [comment]
I was wondering whether there was a module for that, and had just found http://www.unicode.org/Public/security/revision-06/confusables.txt

So that looks like the right approach.

**Comment by ara4n** [comment]
dup of https://github.com/matrix-org/matrix-doc/issues/669

**Comment by ara4n** [comment]
the main discussions in the past on this have happened at https://github.com/matrix-org/matrix-doc/issues/669

**Comment by pafcu** [comment]
I think the issue is not what names we allow, but rather how those names are displayed and/or disambiguated. I'm not sure that should be up to the spec (although I suppose the spec could have some recommendations).

**Comment by ara4n** [comment]
Agreed, but eitherway you need an algorithm to decide which names are ambiguous.  I'm not convinced that the normal utf8 'confusables' stuff is adequate - e.g. does it cover zalgos for instance (Going and adding a combining diacritic which shoves a single pixel dot 400px off the top of one of my letters)?  Eitherway, the previous bugs have a lot of discussions on how one might do this.   Last time I thought it through, I think I concluded that our best bet might be to just do a SSM comparison to decide whether it needs more disambiguation or not - and it would be *very* nice if this disambiguation was performed by the server, rather than each and every client having to work it out itself, especially if it's a computationally complex thing.

**Comment by t3chguy** [comment]
Names now go through [unhomoglyph](https://www.npmjs.com/package/unhomoglyph) for comparisons, which fixes this.

**Comment by turt2live** [comment]
Closing as fixed, although continuing the discussion on https://github.com/matrix-org/matrix-doc/issues/669 would be nice.
