### ISSUE TITLE
Disambiguation algorithm should ignore whitespace

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5827]
### Description

Currently it is possible to impersonate someone by using the same display name as they, but adding e.g. a space or zero-width space to your display name. This causes the disambiguation algorithm to think that there is no need to show the full mxid, even though it is impossible for a human to tell the two names apart.

### Steps to reproduce

- Have a user change their display name "testuser"
- Have another user change their display name to "testuser "
- Observe that messages from both users look identical

### Version information

- **Platform**: web

- **Browser**: Firefox 57
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Should tackle at the same time as #5836.

**Comment by lukebarnard1** [comment]
It would be fun to homogenise display names before checking for ambiguity:
 - Remove white space
 - Reduce homoglyphs to their a-z equivalents

**Comment by lukebarnard1** [comment]
>Should tackle at the same time as #5836.

This feels like a 001 mistake comment.

**Comment by pafcu** [comment]
@lampholder Probably ment https://github.com/vector-im/riot-web/issues/5826 which is the issue about homoglyphs
