### ISSUE TITLE
clicking on LLP icons shouldn't steal focus from the MessageComposer

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5829]
it feels weird to click on the LLP icons (or background) and promptly lose focus from the room you are currently typing in

**Comment by pafcu** [comment]
Related: https://github.com/vector-im/riot-web/issues/5775

**Comment by ara4n** [comment]
this seems magically fixed - thanks @lukebarnard1 !

**Comment by lukebarnard1** [comment]
"Yey" 😅
