### ISSUE TITLE
Improve UX of RoomSettings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5836]
The sister-bug for https://github.com/vector-im/riot-web/issues/5476, which has ended up being mostly about UserSettings - although has some discussion of how UserSettings could be updated to match...

**Comment by turt2live** [comment]
ftr the tabbed settings stuff I'm (slowly) working on plans to address this by going through a similar review process. The reason for picking on UserSettings first is because it is the most complex and complained about.

**Comment by aaronraimist** [comment]
Probably fixed by redesign otherwise a more specific issue should be opened or added to https://github.com/vector-im/riot-web/issues/8207
