### ISSUE TITLE
Drag and drop LLP uses huge amounts of CPU while dragging

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5839]
### Description

The effect ends up being on par with trying to reorganize rooms where things appear to revert, be lagging behind the cursor, or just in general sluggish.

![image](https://user-images.githubusercontent.com/1190097/34002237-4dba8ef4-e0af-11e7-9126-4ae5bfe28d75.png)

The yellow blocks are me moving a group upwards, then a different one downwards.

For reference, I'm in 22 groups. For the full profile, please message me (`@travis:t2l.io`).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63 (**updated**)
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
@turt2live it would be good to get another profile from you having totally changed the underlying dnd impl

**Comment by turt2live** [comment]
@lukebarnard1 sent via PM. Looks pretty similar though.

**Comment by ara4n** [comment]
weird; it seems fine for me now.

**Comment by turt2live** [comment]
It feels smoother, but still uses a lot of system resources.

**Comment by turt2live** [comment]
What I thought was dragging using a lot of resources is actually just Riot being open. Closing this as the drag and drop no longer tries to eat the entire cpu.
