### ISSUE TITLE
Composer broken in Firefox Nightly (59.0a1)

### ISSUE THREAD

**Issue by alexjg** [vector-im/riot-web#5843]
### Description

Most of the UI for the composer is broken in Firefox Nightly (59.0a1)

### Steps to reproduce

- Open Riot in Firefox Nightly
- attempt to send a message by pressing enter, or open the RTE, or disable markdown

Messages are not sent, RTE not enabled, markdown not disabled etc.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox Nightly (59.0a1)
- **OS**: Arch Linux?
- **URL**: / riot.im/app /

**Comment by lampholder** [comment]
I only have my mac laptop to test on right now, but it's fine there (59.0a1 (2018-01-10) (64-bit)).

Is anybody else experiencing this as a problem?

**Comment by pafcu** [comment]
Catching / testing these kind of things would be pretty easy using [riot-selenium-tests](https://gitlab.com/saparvia/riot-selenium-tests) and [SauceLabs](https://saucelabs.com/). If someone on the team got a [free account](https://saucelabs.com/open-source-request-account) I'd even be happy to automate the whole thing.

**Comment by NoXPhasma** [comment]
Same happens for me, can't send any message and other parts of the UI are broken too. Desktop client works fine, though.

Browser: Firefox Nightly (59.0a1)
OS: Linux Mint 18.3

**Comment by musoke** [comment]
I'm also experiencing this. Both riot.im/app and riot.im/staging. riot.im/develop doesn't load at all

Browser: Firefox Nightly (59.0a1)
OS: Ubuntu 16.04

**Comment by lukebarnard1** [comment]
Tested this on 60.0a1 (2018-02-12) (64-bit) on Ubuntu 14. /develop (ec0dd6347013-react-03921bad79bc-js-7df2bfe7bcd1) seems fine!
