### ISSUE TITLE
Riot duplicates calls to Scalar

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5846]
### Description

Riot sends two /register requests very close together when opening Riot to a room. The first is the normal register for the manage integrations button check, however the second appears to be coming from the AppTile getting set up. Although it's not really a huge issue, it's causing uneeded duplicate data in the integration manager and homeserver (by requesting 2 sets of open ID tokens).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Updated title, it's also affecting `/account` and probably others:
```
Dec-17-2017 17:14:02.366 -07:00 verbose [Webserver] Incoming request: GET /api/v1/scalar/account?scalar_token=redacted
Dec-17-2017 17:14:02.465 -07:00 verbose [Webserver] Incoming request: GET /api/v1/scalar/account?scalar_token=redacted
```

**Comment by ara4n** [comment]
we shouldn't be calling /account for every room either, should we?
