### ISSUE TITLE
syntax highlight view source

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5853]
plz

**Comment by pafcu** [comment]
This should be extremely easy to add using https://www.npmjs.com/package/react-syntax-highlighter

**Comment by t3chguy** [comment]
@pafcu or you know, use highlight.js which is already used to highlight code blocks in Riot... :P

**Comment by pafcu** [comment]
Perhaps, but it seems nicer to go towards React instead.

**Comment by t3chguy** [comment]
that package is just a wrapper for hljs (highlight.js)

**Comment by pafcu** [comment]
So should be even better then?

**Comment by t3chguy** [comment]
its more that it'd be a waste of space adding it, for a non-key function like highlighting the view source which most users don't see
I already have this running with just highlight.js and no additional deps

**Comment by turt2live** [comment]
+1 to reducing dependencies.

**Comment by pafcu** [comment]
Well, who am I to argue, but it IMHO there is a smaller cognitive load when you use React components in a React app, rather than mixing together various things.

**Comment by t3chguy** [comment]
agreed, but only if the other usage of highlight.js would be to be refactored to also use the above, which is out of scope

**Comment by pafcu** [comment]
OTOH, doing things in part might make sense? Changing one place later, is easier than changing two places later.
