### ISSUE TITLE
Hovering over 12K in matrix hq should give you the actual number of users

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5858]
### Description

![image](https://user-images.githubusercontent.com/1190097/34182888-44c2c83c-e4d5-11e7-87ae-eb77fc43cf9b.png)
^ this icon. Hovering it should tell me 12,453 or whatever it is.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
agreed. i don't know how it's even become to be abbreviated; the intention and design was to spell out the full count.

**Comment by turt2live** [comment]
I can't find the issue now, but the full number was becoming hard to keep aligned and was causing a bit of confusion for people. I like the 12K, but I also (rarely) want to see the actual room member count.
