### ISSUE TITLE
Riot doesn't install to the Windows start menu

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5859]
### Description

I also can't search for "Riot" to get it started, and there's no desktop icon. If I exit riot from the task tray, there's no getting it back.

### Steps to reproduce

- Be on windows 10
- Download the Riot installer
- Install riot
- Exit Riot from the task tray (if it's open)
- Try to use the start menu to find riot

I would expect to be able to find Riot in the task tray.

Log: not sent (not applicable)    

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 0.13.3

**Comment by MTRNord** [comment]
It works on my PC. I lately had issues that their search didn't let you type more than one Letter if they have a Match. Maybe that's what Happening?

**Comment by MTRNord** [comment]
(their=Windows 10)

**Comment by turt2live** [comment]
I aslso couldn't find it anywhere in the folder structure, and even typing "R" gets me nothing.

**Comment by MTRNord** [comment]
Can you check If the install succeded by looking if the riot folder exists in `%CSIDL_LOCAL_APPDATA%` (appdata/Local)?

**Comment by turt2live** [comment]
It's there, it's how I re-opened it to get the version number :p

**Comment by MTRNord** [comment]
Hmm 🤔 well now I am out of ideas. I did think of a crashed installer. But as the app itself is present that shouldn't be the case

**Comment by turt2live** [comment]
This is no longer an issue.
