### ISSUE TITLE
Add warm&fuzzy text when waiting for a room create to go through

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5869]
### Description

This is a minor detail that can help improve the experience of waiting for your new room to be created. Some homeservers are slow, and that makes the wait time even longer.

The current situation is as follows:
* Click "+ Create Room"
* Fill out dialog and submit
* Be brought to a **Join room** screen with a spinner
* Wait for a while
* Be dumped into the room

My suggestion would be to improve that spinner screen (3rd bullet point):
* Have the title say "Create room" or "Creating room" instead of "Join room"
* Have some text above the spinner explaining what's going on, maybe with a bit of humour. Something like "Hang tight while we create your room".

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by MTRNord** [comment]
I would love to see a "tour" background when a new Room got created too. Which for example has arrows pointing on to the settings button, where too invite people etc. Which than gets removed on the first message. (After the spinner before the first message a "Room Tutorial")

**Comment by turt2live** [comment]
The tutorial aspect is similar to https://github.com/vector-im/riot-web/issues/1631
A more specific room tutorial might be a new issue (in order to keep issues somewhat limited in scope).

**Comment by MTRNord** [comment]
@turt2live I will move my suggestion over there

**Comment by lampholder** [comment]
Yeah, this feels like it could be a big UX win for a modest investment (hopefully).

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2225
