### ISSUE TITLE
Groups overlapping with the "Add" button in the LLS conflict with each other

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5879]
### Description

![ice_video_20171225-125238](https://user-images.githubusercontent.com/1190097/34342605-a412331c-e972-11e7-8dd4-2377dc6b5c60.gif)
(quality is the fault of the recorder)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
We need to sort out the too-many-llp-things problem; possibly some sort of scrolling (definitely some sort of option to limit which things appear there)

**Comment by turt2live** [comment]
There's a scrollbar now
