### ISSUE TITLE
Can't use up arrow to find previously entered commands in a room

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5880]
### Description

It would be nice if the RTE history stored this. The common case would be typos in commands or duplicating the execution.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Weechat does this; I think it's surprised me its not being there, too.
