### ISSUE TITLE
Actually replace freeswitch with jitsi in riot/web at last

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5883]
We seem to have forgotten this.

**Comment by BloodyIron** [comment]
So Freeswitch is going to be removed completely for Riot to use?

**Comment by BloodyIron** [comment]
I ask, as I was actually planning to look into how freeswitch can interface with riot, as some of the PBX's I work with use freeswitch.

**Comment by t3chguy** [comment]
@BloodyIron Yes

**Comment by lampholder** [comment]
@ara4n not forgotten, just not yet done 😢

**Comment by BloodyIron** [comment]
What is the driving force behind moving away from freeswitch? Is there a discussion you can link me to? I suspect this has already been talked about, so I am curious.
