### ISSUE TITLE
emoji completion does not work after newline with shit+enter

### ISSUE THREAD

**Issue by spacebug0** [vector-im/riot-web#5884]
### Description

After writing some text and then using shift+enter to get a newline, the emoji pop-up windows does not show when typing : on the newline.

### Steps to reproduce

- Write some text
- Make a new line using shift+enter
- Write :

Describe how what happens differs from what you expected.

Expected: That the window for emoji to pop-up.
Happened: No emoji window was shown.

Log: not sent?    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 57.0.1
- **OS**: Debian Stretch 64bit
- **URL**: riot.im/app

**Comment by lampholder** [comment]
Confirmed - also happens in FF nightly (59) on mac.

Doesn't happen in Chrome.

**Comment by ara4n** [comment]
itym shift ;) also, fixed by matrix-org/matrix-react-sdk#1890
