### ISSUE TITLE
option to keep username on same line as message

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5895]
like most IRC clients do it

**Comment by ara4n** [comment]
ironically i always envisioned this as part of the compact theme ;)

**Comment by lampholder** [comment]
Is that ironic? :P 

I'd like to see this - @ara4n would you be happy with this change being made to the compact theme?

**Comment by aaronraimist** [comment]
Fixed by irc layout

**Comment by Standard8** [comment]
@aaronraimist Please can you explain a bit more about what's closed this or at least give a reference?

The current release desktop client doesn't have anything relating to an irc layout as far as I can tell. So is that not released yet or am I looking in the wrong place?

**Comment by t3chguy** [comment]
It is implemented in Labs, you can try it on riot.im/develop > Settings > Labs > IRC Layout

You can even enable it on the desktop client by following the docs:
https://github.com/vector-im/riot-desktop#user-specified-configjson
https://github.com/vector-im/riot-web/blob/develop/docs/config.md
https://github.com/vector-im/riot-web/blob/develop/docs/labs.md
