### ISSUE TITLE
Dedupe group profile requests

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5899]
### Description

If there's a conversation between a few people in a room and one or more have flair, anyone who opens that room will send out a fairly large number of profile requests. I've seen as many as 15 simultaneous requests come through to the server, and that stacks up really badly when you're the server. Particularly if those requests end up going over federation.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
This sounds like the FlairStore is not deduping requests for group profiles. Actually this is exactly what https://github.com/matrix-org/matrix-react-sdk/pull/1666 fixes.

**Comment by lampholder** [comment]
So @lukebarnard1 is this fixed?

**Comment by lukebarnard1** [comment]
yarp
