### ISSUE TITLE
When viewing a community (`GroupView` mounted), 3x requests are done than are necessary

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#5901]
Specifically, the requests done 3 times (by `GroupStore`) are:
 - `/summary`
 - `/rooms`
 - `/users`
- `/invited_users`

(with the prefix `r0/groups/%2Bgroup%3Adomain.com/`)

**Comment by turt2live** [comment]
related: https://github.com/vector-im/riot-web/issues/5899

**Comment by lukebarnard1** [comment]
I'd argue for them being unrelated - #5899 would be the FlairStore doing something weird whilst calling `/profile`.
