### ISSUE TITLE
Ability to add new room/conversation categories and rename existing ones (left panel).

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#5904]
It would be nice if we could add new room/conversation categories on the left side, as well as edit the names of the existing ones. When dealing with larger-scale implementations, being able to have custom organisation of such things would be very valuable.

**Comment by turt2live** [comment]
Which left side are you referencing? The room list already supports tags, although there's no UI to add/edit them (that would be https://github.com/vector-im/riot-web/issues/1373 ). If you're talking about the group icons, then that would be https://github.com/vector-im/riot-web/issues/5730 (although currently possible by just creating groups for yourself).

**Comment by BloodyIron** [comment]
I'm not entirely sure what the appropriate term is in this case, so bear with me as I try to explain further.

By default, on the left side, there is "Favourites", "People", "Rooms", "Low Priority" and "Historical". I'm talking about editing those, and the ability to add new ones. These are the categories you can click on the triangle to collapse/expand display of them.

A use case example, make a category called "work", and one called "gaming", stuff like that. As it is now, I am not seeing a way to do this.

**Comment by turt2live** [comment]
That would be https://github.com/vector-im/riot-web/issues/1373

**Comment by BloodyIron** [comment]
Ahh whoops, I see that now!
