### ISSUE TITLE
Drag and drop LLP ordering fails if you try to drag onto the bottom element of the list

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5910]
If you have:

```
A
B
C
D
E
```

and you try to drag A onto E, you should get BCDEA.  Instead, you get BCDAE.

**Comment by ara4n** [comment]
Same happens if you try to drag to the top of the list - and in fact if you drag any element off the side of the list and then back in from the side again at a new position.

**Comment by lukebarnard1** [comment]
I *think* this will require the LLP itself to be a drop target that knows whether we're dropping before the first or after the last tag.

**Comment by lampholder** [comment]
From a separate but highly related bug; @ara4n's comments:
> Currently the bg of the LLP isn't a drop target at all, so if you try to drag nodes off the top or bottom of the list, they stubbornly refuse to move - rather than snapping to the beginning or end of the list as you might hope.
