### ISSUE TITLE
Drag and drop LLP should let you drop stuff off the top or bottom of list to move it to the start or end

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5911]
Currently the bg of the LLP isn't a drop target at all, so if you try to drag nodes off the top or bottom of the list, they stubbornly refuse to move - rather than snapping to the beginning or end of the list as you might hope.

**Comment by lampholder** [comment]
Basically a dup of #5910 - @lukebarnard1's suggestion on #5910 already proposes this, so I'm going to pasta the comment from this bug also onto #5910 and leave us with one place to track this thing.
