### ISSUE TITLE
trying to tag a room as favourite in RoomSettings gives a 'no permission' error

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5919]
if you are a non-privileged user in the room. feels like it's errantly trying to set some other data at the same time

**Comment by t3chguy** [comment]
`m.room.related_groups` is always trying to be stored, even if it wasn't modified

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/2752

**Comment by t3chguy** [comment]
Closing in favour
