### ISSUE TITLE
Ability to disable all identity server functionality via the config file

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5921]
By setting the default_is_url to an empty string/null or something.

**Comment by lampholder** [comment]
Interesting. What consequences would this have?

Threepid invites wouldn't work; what else?

**Comment by lampholder** [comment]
Also, just so I'm not guessing, what's the reason behind this?

**Comment by turt2live** [comment]
Someone wanted it for privacy concerns (I really should have linked the message). They were concerned that their users would accidentally use the identity server in a privacy-centric group. 

The other thing (that I know of) to disable would be adding/editing 3pids.

**Comment by jasmir** [comment]
Is there any movement here? I'd like to add that using the .well-known/matrix/client stuff for it would be _very_ convenient.
For example by `  "m.identity_server": {
    "base_url": ""
  }
`

**Comment by meskio** [comment]
As a work around I've notice that having an 'identity server' that just replies an application/json `{}` in https://<a domain>/_matrix/identity/api/v1 works to keep riot happy and don't use an identity server.

But will be really nice to get an official way to disable the identity server.

**Comment by aaronraimist** [comment]
Would also be nice to have this when the identity server you wanted to use is down :)

**Comment by lampholder** [comment]
https://github.com/vector-im/riot-web/issues/10094

**Comment by aaronraimist** [comment]
Doesn't https://github.com/matrix-org/matrix-react-sdk/pull/3088 fix 90% of this? All you need to do now is make it also work with a completely blank field instead of only working if you enter a URL that isn't an identity server.

Related: https://github.com/vector-im/riot-web/issues/10274

**Comment by lampholder** [comment]
Updated the issue title to distinguish it from https://github.com/vector-im/riot-web/issues/10425

**Comment by dbkr** [comment]
Annoyingly we overlooked this in [MSC2078](https://github.com/matrix-org/matrix-doc/pull/2078) and the id_server param is still require in all situations, so spec-wise we'd be unable to register with an email at all if no IS were specified, even if the HS sends its own emails.

@turt2live points out that (again, spec-wise) a solution to this could be to abuse `params` from UIA to have a flag for `requires_identity_server`: `true`/`false`. Default `true`.

**Comment by rubo77** [comment]
Why is this closed?

**Comment by t3chguy** [comment]
Because it got implemented by #3285?

**Comment by FiveKnive** [comment]
What is the correct way to disable it?
