### ISSUE TITLE
Collapsed RoomTiles don't show room name when uncollapsed

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#5928]
(And need to be remounted somehow before they do show the room name)

**Comment by lampholder** [comment]
I couldn't reproduce this (by naively collapsing/uncollapsing the LHS).

Any tips @lukebarnard1 ?

**Comment by lukebarnard1** [comment]
Hmm. Me neither.

I seem to remember that it happened when refreshing Riot in a small enough window to cause the RoomList to be collapsed. When expanding it, the rooms would appear without their names.

This might have been done with some TagPanel filtering applied.

**Comment by turt2live** [comment]
I think this is fixed through magic
