### ISSUE TITLE
https://about.riot.im/need-help/#account-management-section indicates that phone numbers can be used to reset passwords

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5932]
but that doesn't seem to be the case

**Comment by lampholder** [comment]
Indeed it doesn't - fixed (thanks).

**Comment by ara4n** [comment]
i wonder if we should support password reset for phone numbers. i had a user a few days ago who was very sad that they had lost access to their account because they signed up via phone number... and then forgot their password.

**Comment by turt2live** [comment]
I could have sworn an issue existed for that already, but couldn't find it. Requested here: https://github.com/vector-im/riot-web/issues/5947
