### ISSUE TITLE
preloading the LLP makes startup really really slow on my account

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5935]

**Comment by turt2live** [comment]
Similar conversation at https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$151516805013Wbkkt:t2l.io (riot-dev)

**Comment by lampholder** [comment]
We shouldn't block on pre-loading all the rooms associated with groups, if that's what we're doing.

**Comment by ara4n** [comment]
we're not blocking deliberately, but the amount of processing to load up all the room lists for the groups seems to be sufficiently vicious and possibly happening in a tight loop that it blocks the whole app for 5-6s for me (after login, which makes for a very bad feeling when you can see the UI, albeit with a blank LLP, but can't actually interact with the app).

**Comment by turt2live** [comment]
This is getting really bad.
![image](https://user-images.githubusercontent.com/1190097/34693923-8ddfc8dc-f482-11e7-865e-820bfa011665.png)

The LLP had the circles for the groups, but had not yet gotten around to the avatars.

**Comment by lukebarnard1** [comment]
/me and @dbkr had a theory that it could be the GroupStores pinging an update to the RoomList causing it render once for n-by-4 requests, where n is the number of groups.

**Comment by lukebarnard1** [comment]
@turt2live / @ara4n, has matrix-org/matrix-react-sdk#1704 helped at all? Has startup improved?

**Comment by turt2live** [comment]
It's improved, although I'm still getting major delays on startup. I suspect those are a different issue though.

**Comment by ara4n** [comment]
it's much better for me now, although I am also seeing the spinner freeze during launch, it's better than it was before.
