### ISSUE TITLE
Encrypted room does not allow group audio/video chat

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#5941]
### Description
Encrypted room does not allow group audio/video chat. If I knew that, I would never enabled encryption (I'm the room creator and administrator). And there is no way to disable encryption for now. Actually users does not care whether room encrypted or not. It is now very inconvenient for us: we see lock icon for own messages and exclamation mark for other people messages. To see the lock everywhere we need to verify each other user/device which is very inconvenient if there are tens or hundreds of users  in a room.

## Possible fixes
Please
- allow to disable encryption in a room for its creator, **or**
- enable group audio/video calls in encrypted room.
- **if** room is encrypted please disable or simplify verification process.

### Version information
- **Platform**: web (in-browser) or desktop
- **OS**:  Linux
- **Version**: 0.13.4

**Comment by ara4n** [comment]
please use the Jitsi widget for group voip/video chat, which should work fine in e2e rooms.

**Comment by ara4n** [comment]
(we are shortly removing the pre-jitsi conferencing entirely)
