### ISSUE TITLE
we should sign the installed Riot.exe on electron

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5948]
rather than just the installer

**Comment by aidalgol** [comment]
[VirusTotal scan details](https://www.virustotal.com/#/file/aa393f9951ca549e30797d86949e990794f880038f7faa409354505b01890d78/details)

**Comment by MTRNord** [comment]
I think this has a upstream issue at the electron-builder dep or some upstream dep of it has it.

**Comment by t3chguy** [comment]
This is already done for the Riot Nightly so will be inherited by Riot 1.6

![image](https://user-images.githubusercontent.com/2403652/79210498-d8e14180-7e3c-11ea-8740-47ab5472b2ee.png)
