### ISSUE TITLE
Ability to autojoin rooms when you join a community

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5951]
Right now we have the ability to autojoin rooms when you register an account on a given HS.

However, it could also be useful (for Slack/Discord style semantics) if you autojoined a set of rooms on joining a given group.  We'd need to be careful about being clear why these rooms have been joined though (perhaps we should reconsider grouping RoomList via group?) - and we need to be very careful about abuse (if accepting an invite to a +evil:matrix.org then autojoins you to 200k rooms).

(Split out from #3848)

**Comment by turt2live** [comment]
#3848 is related to the start chat button - is this correct? Eitherway, this seems like a duplicate of https://github.com/vector-im/riot-web/issues/5244

**Comment by ara4n** [comment]
so it is.

**Comment by ara4n** [comment]
fixed broken link
