### ISSUE TITLE
Getting notifactions for my name »jan« even though it’s unrelated text (like »Jan-Mar« for months)

### ISSUE THREAD

**Issue by jancborchardt** [vector-im/riot-web#5955]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Have a short username like `@jan:matrix.org`
- Be in some channels like `#wikimedia.design`
- Get notifications for month roundups Jan-Mar like these ;)
![screenshot from 2018-01-09 15-36-43](https://user-images.githubusercontent.com/925062/34726565-b7e1a2fe-f554-11e7-8e64-9e71c76daa07.png)

My settings (I have _no_ keywords set):
![screenshot from 2018-01-09 15-42-39](https://user-images.githubusercontent.com/925062/34726570-badf0ff0-f554-11e7-915c-9e4be580e5ed.png)

### Version information

- **URL**: riot.im/app
- And Android app too. It’s regardless of the client or version.

**Comment by turt2live** [comment]
"Messages containing my user name" is set to noisy, which is causing "jan" to be picked up. I'd recommend setting it to "off" in this case.

**Comment by jancborchardt** [comment]
@turt2live ah ok! So then "jancborchardt" (which I use as display name / through IRC) will then still be picked up as noisy? Thanks!

**Comment by turt2live** [comment]
Yup. If you have further issues with pings (like I often do), set both the display name and user name options to 'off' and set keywords to 'noisy', clicking on the word 'keywords' to set keywords to ping on.
