### ISSUE TITLE
Flair seems unreliable

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5956]
@t3chguy and others have complained that flair is missing on some users when it is very clearly published. Occasionally it seems to randomly not appear on events: https://t2l.io/_matrix/media/v1/download/riot.ovh/CSxFHNUYqIzNyIyinbNQdVqG

**Comment by t3chguy** [comment]
So it seems it might be a server issue https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1516201253133WnwvR:ldbco.de

**Comment by turt2live** [comment]
I believe this was fixed a while ago. Closing as I haven't seen any problems recently.

**Comment by lukebarnard1** [comment]
I've seen problems recently. Reopening. 

I actually caught the client in a state where I didn't have +matrix:matrix.org flair in #riot despite the network tab clearly showing the client had received my publicised groups that included "+matrix:matrix.org".

The client also has the group profile state for that group, so seemingly the `<Flair>` tag isn't being rendered next to my name for whatever reason.

**Comment by turt2live** [comment]
I'm pretty sure this got re-fixed again. @lukebarnard1 are you still seeing issues?

**Comment by lukebarnard1** [comment]
I've definitely heard reports of this and I've seen it first hand fairly recently. If I don't see or hear anything in the next week or so, I'll close this, otherwise I'll be a bit more specific about the bug I'm seeing.

**Comment by ara4n** [comment]
i haven't seen flakiness here, but i think people might have got used to flair being a bit hit & miss. that said, we don't have anything to go on here; let's open a bug when we see it next break properly.

**Comment by Hidden-R3d** [comment]
I've had the same issue. I was in a room, with community flair enabled for a community I was in. The flair worked perfectly fine there. I left both the room and the community. I made new ones. I enabled community flair for the community I was in in the new room, yet it's not showing up.
