### ISSUE TITLE
Unban button CSS is badly broken in RoomSettings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5962]
Since i switched buttons to be mixins.

**Comment by lampholder** [comment]
Broken inasmuch as it still has the bullet?

![screen shot 2018-01-11 at 13 37 29](https://user-images.githubusercontent.com/1922197/34828172-99d0d6b4-f6d4-11e7-812c-bb9469f155e3.png)

**Comment by turt2live** [comment]
I think this is fixed
