### ISSUE TITLE
Setting associated flair (i.e. related groups) for a room in RoomSettings doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5963]
Trying to set flair for #riot-android:matrix.org is silently dismissed.  Looking at the logs, it doesn't seem that it notices that the flair fields have been changed at all.

**Comment by t3chguy** [comment]
/me assumes regression caused by https://github.com/matrix-org/matrix-react-sdk/pull/1691 and investigates

**Comment by ara4n** [comment]
thanks.
