### ISSUE TITLE
Rich replies are not pretty to those without the feature enabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5965]
### Description

What I see:
![image](https://user-images.githubusercontent.com/1190097/34837665-be2d1246-f6b8-11e7-8580-8ddf76242bb7.png)

What they see:
![image](https://user-images.githubusercontent.com/1190097/34837670-c1e91362-f6b8-11e7-846a-9f2dc219a0db.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Would this not be fixed by https://github.com/vector-im/riot-web/issues/5967 ?

**Comment by turt2live** [comment]
... yup. Closing this in favour of #5967
