### ISSUE TITLE
Instead of "Quote" for the text in a rich reply, say something like "In reply to..."?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5967]
### Description

![image](https://user-images.githubusercontent.com/1190097/34837995-c12bc608-f6b9-11e7-96ae-32e6bf57095e.png)

Would also help with those who do not have the feature enabled.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Even it's tractable to go with the replies-rendered-in-series-rather-than-nested idea I proposed on one of these issues, I like the idea of the link the user clicks to expand messages further back in the chain to read something like the suggested `In reply to TravisR`

**Comment by lampholder** [comment]
Perhaps something like:

![screen shot 2018-01-16 at 11 23 36](https://user-images.githubusercontent.com/1922197/34986503-bce6f226-faaf-11e7-8607-89e5c201d03d.png)

**Comment by t3chguy** [comment]
I like that
I don't like the thought of having to write it, but I like how it looks :P

**Comment by t3chguy** [comment]
for interest of documentation, the design above has been chosen and implemented in a PR

**Comment by t3chguy** [comment]
Related https://docs.google.com/document/d/1KLdKtuZBbFoWDSfN4KM3p7LnIvFBQfSORICBo8zRHaE/edit

**Comment by t3chguy** [comment]
Fixed by merged PR
