### ISSUE TITLE
Clicking the "Quote" link does nothing if you don't have rich replies enabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5970]
### Description

It should probably just be a normal permalink. Currently it does nothing.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by non-Jedi** [comment]
Clicking on "Quote" acts just like a normal permalink for me with rich replies disabled. I think this is working?

**Comment by turt2live** [comment]
Oh it is, I'm just dumb and was clicking on a buggy link.
