### ISSUE TITLE
Only nest up to one or two rich replies

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5972]
### Description

Anything else is just diminishing returns for conversation context and usability. See also: https://github.com/vector-im/riot-web/issues/5968 https://github.com/vector-im/riot-web/issues/5969

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This was the intent, a max nesting of 3 iirc but weirdly harder than it should have been to implement, just failed to work :L

**Comment by turt2live** [comment]
another related issue: https://github.com/vector-im/riot-web/issues/5974
