### ISSUE TITLE
Recent changes have caused automatic focus on the file upload confirmation dialog to disappear

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5977]
### Description

This was last working yesterday, and now I have to click in anger to upload files.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
This is probably https://github.com/matrix-org/matrix-react-sdk/pull/1674
