### ISSUE TITLE
"Display your community flair in rooms configured to show it" option is not scrollable in Chrome

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5991]
It used to be, but it isn't any longer :(

**Comment by lukebarnard1** [comment]
I can scroll it (on Chrome 63), so you may have to be more specific, @lampholder.

**Comment by lampholder** [comment]
Oh yeah, sorry, bad bug--.

It is not scrollable:
- _on chrome 63.0.3239.132 (Official Build) (64-bit)
- _with the trackpad_
- _on my mac_
- _running high sierra 10.13.1 (17B48)_

**Comment by lukebarnard1** [comment]
So the only difference in my (working) setup is that I'm on macOS Sierra. This is odd.

**Comment by turt2live** [comment]
Fixed by making it a tab
