### ISSUE TITLE
Left sidebar headers sometimes get lost

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5996]
### Description

Sometimes the headers on the left sidebar don't appear where they should.  It seems to happen mainly after expanding/collapsing a header, and gets fixed by itself some time after (presumably when a new message arrives and the sidebar redraws).

### Steps to reproduce

- Scroll to top of left-hand sidebar
- expand the "People" section
- collapse the "People" section
- Scroll down and up quickly
- (may need to try it several times)
- see 
![image](https://user-images.githubusercontent.com/1012976/35048398-ecffaf14-fb6a-11e7-8d9a-3f99ee222abf.png)
- note: "Low Priority" should be above "#ansible", and "Rooms" should be at the top, just below "Favourites" and "People", which have disappeared.

I don't know if it makes a difference, but I have Tag Panel, Pinned Messages, and Replies enabled in Labs.

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 57
- **OS**: Debian
- **URL**: riot.im/develop a94208e230c2-react-792db430078b-js-f2d1222de7df

**Comment by uhoreg** [comment]
This just happened without expanding/collapsing any section.  Maybe it's some JS function getting rate-limited too much?

**Comment by lampholder** [comment]
Is this on /app or /develop? And for how long have you noticed this happening?

**Comment by turt2live** [comment]
I've managed to reproduce this within the last week or so on /develop. Chrome 63, Windows 10 if it helps.

**Comment by uhoreg** [comment]
It was on develop, on Firefox.  I just tried develop the other day to see what was new, and noticed it then.    It seems to be triggered by scrolling up and down very quickly in the sidebar.

**Comment by turt2live** [comment]
I'm suspecting this is not an issue with the revamped list
