### ISSUE TITLE
after clicking 'send anyway' after unknown devices are present in the room, the messagecomposer loses focus

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5998]

**Comment by lampholder** [comment]
Should we discuss a more robust way to handle returning focus to the composer after interacting with another UX element? We do seem to encounter this failure very frequently :\

**Comment by turt2live** [comment]
+1 to the composer having focus a majority of the time. I'd expect to always be able to type a message unless a dialog is open or something else needs my attention.

**Comment by anoadragon453** [comment]
This seems to no longer be the case.
