### ISSUE TITLE
Open settings page (at the profile section) when you click on your avatar in the text input box

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#600]
Probably easy to do and a nice shortcut. Please pushback if nightmarish.

**Comment by ara4n** [comment]
I'm slightly concerned that you might expect this to bring up the MemberInfo section on the right-hand panel for yourself (in the context of the room) when clicking on it - which is what happens with other avatars in the timeline (including your own).

Another related question is whether clicking on an avatar in general in the timeline should perform autocomplete on their name (as it does on matrix-console-ios), or open up the MemberInfo section (as it does currently).

The advantage of autocomplete is that it makes it easier to autocomplete crazy names like エイリアン which don't begin with an ASCII character.  The disadvantage is that you have go via the MemberList if you want to interact with the user in any other way - e.g. view more profile data; kick/ban then; etc...

what do you think?

**Comment by AmandineLP** [comment]
> concerned that you might expect this to bring up the MemberInfo section on the right-hand panel for yourself 

You already get the MemberInfo section when clicking on yourself in the member list and having an action here display something in the member list just feels weird...

> Another related question is whether clicking on an avatar in general in the timeline should perform autocomplete on their name, or open up the MemberInfo section

I like the autocomplete... Maybe not the most intuitive but as you say it's great for non ASCII names. Let's try this and see if people yell. I was about to say "we're going to have search in the member list anyway" but that won't be helpful with non-ASCII. 
Can we have double-click = autocomplete and single click = MemberInfo? <- not entirely convinced myself given I'm not sure double-click is standard on web, but want to hear your thoughts

**Comment by t3chguy** [comment]
This is now linked to the Custom User Status in Labs

**Comment by turt2live** [comment]
Further, the top menu is where we have access to the menu on this.
