### ISSUE TITLE
You can't scroll the roomlist with the trackpad if you try and scroll the headings not the list of rooms themselves

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6001]
Which is super annoying if you have some custom tags.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/2696

**Comment by t3chguy** [comment]
okay I guess scroll whell vs trackpad but still

**Comment by lampholder** [comment]
Issue search fail shame 😢  (thanks for deduping)
