### ISSUE TITLE
homogenise messages to community

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6005]
some error messages stil mention Group rather than community

**Comment by t3chguy** [comment]
Most of these cases occur when the Error is passed through from Synapse

**Comment by t3chguy** [comment]
PR above fixes an instance of this, but this may not be the only instance

**Comment by lampholder** [comment]
I've changed the title of https://github.com/vector-im/riot-web/issues/6003 to encompass this issue - closing this one as a dup.

**Comment by t3chguy** [comment]
@lampholder aaaaare you though ;)?
