### ISSUE TITLE
If you start 'reply'ing to a message, then switch to a different room and send a message, your new message is rendered as a reply (to a message in a different room)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6006]

**Comment by t3chguy** [comment]
This is intentional :(

> even if it were to span multiple rooms!

- https://github.com/vector-im/riot-web/issues/3571#issue-219484407
was my specification

**Comment by lampholder** [comment]
As discussed IRL - we'll remove this feature for now (because its current impl is a bit confusing, and we get a lot of utility from the replies stuff without worrying about cross-room replies for now)
