### ISSUE TITLE
Create room dialog accepts Enter but doesn't have the create button focused

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6009]
### Description

Pressing Enter to submit the form works, although the button doesn't appear to have focus (not highlighted).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
What would you expect here?

Is it not standard for forms to submit on enter but for the current form input to have the highlight style? (This is a genuine not rhetorical question).

**Comment by turt2live** [comment]
I'm pretty sure I just managed to confuse myself when reporting this. The behaviour is exactly how I'd expect.

/me closes in shame with a side of confusion
