### ISSUE TITLE
Read receipts disappear before new messages arrive

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6011]
### Description

Similar to https://github.com/vector-im/riot-web/issues/6010, people's read receipts can fall off screen before a message arrives. The person who sent the event (which I cannot see yet) does not have their read receipt move down, however everyone else may have their read receipt run away.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Half-Shot** [comment]
Seems like something we could solve with caching the RR until the event arrives, although that might be interesting to write in React without bodging it.

**Comment by turt2live** [comment]
I feel like this hasn't happened since 2018
