### ISSUE TITLE
URL preview thumbnails inexplicably wink out of existence

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6012]
One minute they're there; then they disappear to be replaced by broken icons.  Switching back and forth make them reappear again?

**Comment by ara4n** [comment]
`2018-01-19_FuAbmaXFNjdTbgvr Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`
i'm seeing alarming numbers of these ^
which i think coincide with the mysteriously disappearing url preview icons
that actual one being: https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/2018-01-19_FuAbmaXFNjdTbgvr?width=100&height=100

**Comment by turt2live** [comment]
Seemingly related: I've seen/received a number of complaints that media on matrix.org is unreliable for the last week or so. Stuff like images posted to rooms coming to the client as 404, despite everyone else seeing it fine. 

ERR_CONTENT_LENGTH_MISMATCH sounds eerily similar to https://github.com/vector-im/riot-web/issues/2585#issuecomment-355882717

**Comment by ara4n** [comment]
richvdh fixed this.
