### ISSUE TITLE
You can scroll the top of the header (title, description, save button, close button) on the room settings view off the top of the page

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6018]
Using the status theme on chrome 63.0.3239.132 on mac 10.13.1 (17B48) high sierra if you open room settings (it seems only to happen in rooms with a description set) and scroll scroll scroll to the bottom then you can very confusingly hide the save/X buttons.

**Comment by lampholder** [comment]
I also cannot reproduce this on Windows, only on my macbook air:
![off_the_top](https://user-images.githubusercontent.com/1922197/35618447-ec45b11e-0672-11e8-85ea-282706392191.gif)

**Comment by turt2live** [comment]
Not anymore!
