### ISSUE TITLE
Read receipt disappears when a hidden message is read

### ISSUE THREAD

**Issue by nvbln** [vector-im/riot-web#6020]
### Description

The read receipt disappears when a message is read that is not displayed. I encounter this when there is a name change (which I do not see as I have hidden them). The other party reads the name change message and that's where their read receipt is. Because that message is hidden from me I do not see any read receipt. I do see the read receipt again when a new message is sent and read. Might be related to #3511 and #4947. 

### Steps to reproduce

1. Hide name change updates.
2. Change your name (or have someone else change their name).
3. See read receipts disappearing when the name change is read.

I would expect the read receipts to appear on the last message before the hidden message. Then when a new message that is not visible appears the read receipts go to that message (when read of course). 

Log: no log.

No screenshots as you can't see what isn't there. ;) 

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian Linux
- **Version**: 0.13.4

**Comment by uhoreg** [comment]
Closing as a dup of https://github.com/vector-im/riot-web/issues/5761.  The message is hidden for a different reason, but it's basically the same thing.
