### ISSUE TITLE
Disambiguation can be unhelpful in the autocomplete suggestions

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6024]
### Description

![image](https://user-images.githubusercontent.com/1190097/35300639-4d6c0eb2-0046-11e8-987b-fa0782d0bd9e.png)

In the above, there are two MTRNords. They aren't duplicated, but one happens to be on matrix.org and the other on matrix.ffslfl.net. The ellipsis at the end of the suggestion pill happens to cut off the domain, leaving me unsure of who is who.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
That looks like a regressed autocomplete

**Comment by turt2live** [comment]
How so?

**Comment by t3chguy** [comment]
Oh wait users is a special autocomplete snowflake

**Comment by t3chguy** [comment]
Ignore meee

**Comment by lampholder** [comment]
I'd say it's imperative for the autocomplete to give you enough information to choose the right person, so truncation here isn't really viable.

Let's look at solutions which don't truncate.

**Comment by t3chguy** [comment]
It could be done like the command autocomplete where each entry is a line and shows all the info it needs, instead of this "stack as many as you can but truncate" dealio
