### ISSUE TITLE
Cannot use Enter key to accept room suggestion when adding rooms to a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6026]
### Description

![cannot-enter-group](https://user-images.githubusercontent.com/1190097/35303293-b20ea9bc-004e-11e8-8fa8-c1ebe49e7a64.gif)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Also I can't use the arrow keys to navigate downwards in the list. This also applies when trying to invite someone to the group.

**Comment by lampholder** [comment]
<kbd>Enter</kbd> should accept suggestions.

We need to be a bit careful that we make our users feel safe to press <kbd>Enter</kbd> - at the moment I hold back because I'm fairly certain Riot will invite the users/send the message/whatever sooner than I want it to.

**Comment by turt2live** [comment]
@lampholder this is also a regression btw

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5994 and now fixed
