### ISSUE TITLE
Rooms in group and LLP appear to be able to become desynchronized

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6027]
### Description

![image](https://user-images.githubusercontent.com/1190097/35303885-c85c18a6-0050-11e8-8869-82f5df803eb6.png)

All the rooms (except offtopic) also have the group in the related_communities. I'm not sure what happened, but I've described what I did.

### ~~Steps to reproduce~~ What I did

- Created a new group, giving it an avatar, name, topic, and description
- Invited my other self to it
- Accepted the invite
- In the database, gave my other self admin
- On my other self, added the four rooms in one request
- On my other self still, clicked the group in the LLP

Log: sent (referencing this)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
@lukebarnard1 is this just a symptom of the caching?

**Comment by lukebarnard1** [comment]
> is this just a symptom of the caching?

Yep. There's an outstanding issue to fix that. I think the consensus was to fetch rooms for a group *again* when clicking on its related tag in the LLP

**Comment by turt2live** [comment]
Closing in favour of #6192 (more concrete reproduction steps)
