### ISSUE TITLE
new RoomList drop & drag breaks cosmetics of placeholder drop targets

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6031]
These should not be dark green...
<img width="254" alt="screen shot 2018-01-24 at 09 06 27" src="https://user-images.githubusercontent.com/1294269/35320979-01297f62-00e6-11e8-9d00-0993f28a29f7.png">

**Comment by lukebarnard1** [comment]
I imagine this is also quite bad when you drag your first room into an empty "People" and are surprised to see the entire placeholder animate out the way... Although I haven't tested this, it probably will happen.

**Comment by lukebarnard1** [comment]
Just tested this - the placeholders don't move but they also don't do anything when you drag a room tile over them.

**Comment by lukebarnard1** [comment]
For now, we'll just change the background colour back to what it was before if there's a placeholder in the sublist

**Comment by turt2live** [comment]
@lukebarnard1 this is still a problem on the dark theme
![image](https://user-images.githubusercontent.com/1190097/36321088-d3e874a4-1305-11e8-92d4-cd34aa728ed1.png)
