### ISSUE TITLE
h1/h2 in timeline should be displayed as h3

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6032]
apparently the CSS for this has regressed

**Comment by ara4n** [comment]
(to stop people shouting, or rendering random h1 separators)

**Comment by turt2live** [comment]
For tracking: Regressed from https://github.com/vector-im/riot-web/pull/3719

**Comment by turt2live** [comment]
fwiw, this seemingly got fixed on /develop recently. There's some concerns about the behaviour at #6319

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/41073357-1c78246a-69c0-11e8-921f-8700638869c1.png)

This issue has been resolved.
