### ISSUE TITLE
Image previews are too small and should be a pop out.

### ISSUE THREAD

**Issue by Cerothen** [vector-im/riot-web#6041]
### Description

When sent a file that is an graphic the image is displayed inline as part of the conversation, when the Riot.im window (desktop or web) is narrow (half/third of the screen) the image itself is pretty small. When clicking on the image you get a preview with some info and a button that says "Download this file". The issue is when this overlay comes up the image is sometimes even smaller than it was in the conversation view. Downloading the file browsing to the download location and opening it in the default image software seems like a lot of extra steps to be able to see the image in a larger/fullscreen window.

For the web experience there should be a button above/below the "Download this file" button for images/gifs/streamable videos (mp4s,etc.) that shows that content in an embedded popup window (something like the answer provided here: https://stackoverflow.com/a/2909717 ).
`window.open('/pageaddress.html','winname','directories=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no,scrollbars=no,width=400,height=350');`

For the desktop experience either doing the same as above or allowing these files to be opened with their default program (eg by downloading first to the temp directory) and opening it automatically.

This would smooth the process of wanting to preview an image in a larger window in an elegant way.

### Steps to reproduce

- Share an image
- Try and preview that image in a larger window without needing to browse to the file.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome
- **OS**: Windows
- **URL**: Riot-Web
- **Version**: 0.13.4 

For the desktop app:

- **OS**: Windows
- **Version**: 0.13.4

**Comment by turt2live** [comment]
The previews being too small is https://github.com/vector-im/riot-web/issues/3638 

Some other enhancements suggested in this area are:
* https://github.com/vector-im/riot-web/issues/3323
* https://github.com/vector-im/riot-web/issues/3159
* https://github.com/vector-im/riot-web/issues/282

**Comment by lampholder** [comment]
Yeah, I'm going to close this as a dup. I swear we used to have a `duplicate` label kicking around here...

**Comment by t3chguy** [comment]
I remember that label too :(

**Comment by ara4n** [comment]
hm, i think i might have deleted it in a fit of confusion, on the basis that it was redundant. but i guess it isn’t.
