### ISSUE TITLE
Clicking "Travis CI" integration under "existing integrations" causes Riot to freeze

### ISSUE THREAD

**Issue by alexgleason** [vector-im/riot-web#6043]
1. Describe your issue:

My room looks like this.

![screenshot from 2018-01-25 16 23 36](https://user-images.githubusercontent.com/3639540/35413020-21abe1ec-01ec-11e8-98d1-53d7575b1eae.png)

Clicking "Travis CI" causes Riot to freeze. Clicking on other elements has no affect afterwards and I cannot regain control without refreshing the page.

I've just added an integration for Travis and did not customize the template. I typed in my repo's name, copied the code it generated into my travis.yml file, and haven't been able to open the window again since it closed. I'm a little uncertain of how it entered this state.

2. Can you reproduce the issue?

It always happens for this room upon refreshing. I did not try creating a new room and adding the integration again.

3. On which browser/OS does the issue appear?

Chromium 63.0.3239.84, Ubuntu 16.04.3

4. Which version of Riot does it affect?

0.13.3 (on matrix.org)

5. How would you tag this issue?

Bug

**Comment by t3chguy** [comment]
Getting the Javascript log for this would be handy

**Comment by alexgleason** [comment]
Shoot, sorry! I had it ready and totally meant to attach it.

Full log here: [riot.im-1516917158243.log](https://github.com/vector-im/riot-web/files/1665826/riot.im-1516917158243.log)

The major issue seems to be this, as it occurs right when I click the button:

```
Uncaught TypeError: Cannot read property 'user_id' of undefined
    at TravisCIComponent.js:297
    at Array.map (<anonymous>)
    at TravisCIComponent.js:292
    at Array.map (<anonymous>)
    at Object._getExistingHooks (TravisCIComponent.js:290)
    at Object.render (TravisCIComponent.js:386)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at d._renderValidatedComponent (ReactCompositeComponent.js:819)
    at d.performInitialMount (ReactCompositeComponent.js:359)
    at d.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at Object.updateChildren (ReactChildReconciler.js:119)
    at m._reconcilerUpdateChildren (ReactMultiChild.js:209)
    at m._updateChildren (ReactMultiChild.js:308)
    at m.updateChildren (ReactMultiChild.js:295)
    at m._updateDOMChildren (ReactDOMComponent.js:944)
```

**Comment by t3chguy** [comment]
Seems like a Scalar bug;
@rxl881 any ideas?

**Comment by turt2live** [comment]
Did the Travis CI bot actually join the room or is it sitting as "invited"?

Also, @alexgleason, I've sent you a private message from my alt account `[e] TravisR` - when you get a chance, please take a look.

**Comment by alexgleason** [comment]
@turt2live The bot joined the room. I haven't broken my build yet, so I'm not sure if the bot is working.

**Comment by turt2live** [comment]
Looks like it was created somehow without an owner. Rick would (hopefully) know best as to how that happened.

**Comment by alexgleason** [comment]
The bot's display name is `Travis CI [@alexgleason:matrix.org]`. I believe that suggests I am the owner?

It's a public room so feel free to view https://riot.im/app/#/room/#gardenhub:matrix.org

**Comment by alexgleason** [comment]
Quick update: the bot works.

I broke my build and the bot responded appropriately by posting a message in the room. I am still experiencing the issue described here, however.

**Comment by lukebarnard1** [comment]
Actually this is just a typo - there are two variables named `i`. One is an index, and the other is some Object.

**Comment by rxl881** [comment]
This should now be deployed for riot.im/develop. Assuming that there are no issues I will deploy for riot.im/app in the next day or so.
