### ISSUE TITLE
z-index of inbound voip call popup is all broken again

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6048]
this time, statusbar and the sticky headers occlude it

**Comment by turt2live** [comment]
also I noticed that it is impossible to right click it and disappears when you try and do so. Right clicking the buttons works though. (was trying to inspect it)

**Comment by turt2live** [comment]
I can't figure out what the right click behaviour is doing to cause it (changing the z-index has no effect). It also appears the call box is not incorrectly layered anymore - closing as "fixed at some point this year".
