### ISSUE TITLE
Replying to images doesn't show the image

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6052]
### Description

![image](https://user-images.githubusercontent.com/1190097/35486916-735d3e4e-0432-11e8-8d0a-8968759aa393.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Hum
I wonder why
I'll look into it when I get in
