### ISSUE TITLE
"Download file" link in an encrypted room doesn't have a cursor

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6058]
### Description

The cursor should be a hand. This is a problem specific to encrypted rooms.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I cannot reproduce on the desktop app on windows, but also can't screenshot because snipping tools hide the cursor

**Comment by t3chguy** [comment]
also on Chrome 63 on Windows 10 on riot.im/develop

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/35562128-595c62d0-05aa-11e8-9570-90f4aa4333e6.png)

Had to revert to less sane methods

**Comment by t3chguy** [comment]
its because browsers `getComputedStyle` doesn't realise its a cursor

**Comment by t3chguy** [comment]
adding it to the CSS of the Decrypt link makes the browser realise and hey presto it passes it through to the iframe
