### ISSUE TITLE
Riot stalls when receiving messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6060]
### Description

The few places I use riot.im/develop have become particularly bad to use as of today. I've taken a few profiles to hopefully help narrow down what is going on.

[riot-slow-jan29-2018.zip](https://github.com/vector-im/riot-web/files/1674755/riot-slow-jan29-2018.zip) (20mb compressed; 260mb uncompressed)

There's 3 profiles in the archive because chrome was getting mad at me. Here's their breakdown:
1. Chrome watching the page load activity, up until it considers the page loaded. After this profile finished, the entire tab stalled on rendering (not uncommon).
2. This is after I realized chrome stopped profiling and the tab was responsive again.
3. A minute or so after the second profile ended, riot was becoming slow and having long pauses. This is a profile of just switching rooms and idling in a few places to try and see if anything in that area is causing the problem.

The only change that I'm aware of was https://github.com/matrix-org/matrix-js-sdk/pull/594 landing. Riot was last "usable" (by a rough standard of not stalling every few seconds) Sunday, Jan 28, 2018.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
It's officially reached the point where I can only use Riot if I wish to type messages blind because it can't keep up with what I'm typing or clicking.

Here's a profile containing 1.7 minutes of frustration. In it, I check a couple rooms and try to send 2 messages in another room.

[lots-of-pauses.zip](https://github.com/vector-im/riot-web/files/1675437/lots-of-pauses.zip) (6mb compressed; 84mb uncompressed)

**Comment by turt2live** [comment]
It looks like it's churning pretty badly on trying to figure out if badges should be displayed or not. The flame graph shows a few places where it takes several seconds to `makeRoomTiles`, in which it seems to call `doesRoomHaveUnreadMessages` a lot. This is also falling into the granular settings quite often in calling `shouldHideEvent`. All of this is kicked off by receiving events from the js-sdk.

**Comment by turt2live** [comment]
For the most part this has gone away. Conveniently, my homeserver is also not trying to set itself on fire anymore. I have a feeling it's somewhat related.

**Comment by turt2live** [comment]
... and I've narrowed it down to receiving messages causing an app-wide stall. Easily reproduced on my account by sending 3 or more messages in another client. The faster the messages come in, the longer riot pauses. 

This correlates with the flame graph where it's trying to reorganize my massive room list.

**Comment by ara4n** [comment]
This is making riot/develop completely unusable for me.
We've always stalled to reorder the RoomList when receiving messages (this prompted a bunch of my RoomList perf work back in April last year which subsequently got backed out).
However, something has changed about the RoomList reordering in the last few days which means that it's now horrifically slow - pauses of >30s whilst trying to type.

**Comment by lukebarnard1** [comment]
My vote would be to close this following the recent perf work in https://github.com/matrix-org/matrix-react-sdk/pull/1801 and https://github.com/vector-im/riot-web/pull/6313

**Comment by turt2live** [comment]
Yea, I think the remaining performance issues are https://github.com/vector-im/riot-web/issues/6212 and https://github.com/vector-im/riot-web/issues/3307 now
