### ISSUE TITLE
Replying to a message with an emote doesn't look like an emote

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6061]
### Description

![image](https://user-images.githubusercontent.com/1190097/35527273-6d3b4c58-04e7-11e8-8c02-6728f51866b7.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
soooo this further pushes me to wanting to have the replying semantic entirely out of the text/html representation of the event
otherwise this is the only sane rendering of a reply which remote matches what is on the wire

**Comment by t3chguy** [comment]
@lampholder ideas on how best to render a reply in the form of an emote?

**Comment by lampholder** [comment]
Are we talking about the difference between

![image](https://user-images.githubusercontent.com/1922197/35621834-a7866ebe-067d-11e8-8cc3-7c457805e923.png)

and perhaps something like

![image](https://user-images.githubusercontent.com/1922197/35621872-c81db290-067d-11e8-85ce-f3d096d2d3b8.png)

?

**Comment by lampholder** [comment]
What about instead of:

![image](https://user-images.githubusercontent.com/1922197/35621937-18f8a6fc-067e-11e8-88ac-12e57a8f5f29.png)

just: 

![image](https://user-images.githubusercontent.com/1922197/35621984-305166ea-067e-11e8-8705-9ab701c27192.png)

?

Easy to draw in gimp; perhaps a lot fiddlier to realise in code?

**Comment by lampholder** [comment]
AS discussed IRL, the sender then isn't at the top of the message, which is problematic.

**Comment by lampholder** [comment]
I think this might actually be fine.

If the emote-reply is the first thing User X has said after other users have been speaking, it'll have their avatar there.

If the emote-reply is not the first thing User X has said after other users have been speaking, the reply won't have an avatar/display name near it. However, I don't think this looks materially weirder than a standard emote.

I reckon we try implementing it as per the mocked up screenshot above and see how we go.

**Comment by t3chguy** [comment]
It is no longer possible to reply with an emote as you cannot write a sane PR for it, but the app will render it well if someone sends an emote reply without a fallback.
