### ISSUE TITLE
One of my rooms is stuck under "Rooms" as a direct chat

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6062]
### Description

I've tried dragging, the context menu, and the room settings. It won't budge. Even after a page refresh. The problem is persistent across multiple riot-web tabs/browsers as well (riot-android displays it fine).

No known console errors. The room is composed of 8 users (including me).

![image](https://user-images.githubusercontent.com/1190097/35528934-a8f2488c-04ec-11e8-867c-3a8a931ed484.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Super broken :(

We'll be spending some time with the roomlist now - depending on the approach we take we might sidestep this entirely (with a fairly substantial rewrite of the roomlist structure under the hood) - if we don't we should definitely look into the specific failure mode here :\

**Comment by lukebarnard1** [comment]
@turt2live it would be interesting to know what the room's `m.tags` account data event contains.

**Comment by turt2live** [comment]
On riot web:
```
{
	"tags": {
		"im.vector.fake.recent": {}
	}
}
```

However it is listed in my `m.direct` account data:
![image](https://user-images.githubusercontent.com/1190097/35987948-6e9fb950-0cba-11e8-820f-3a852006946e.png)
(highlighting is CTRL+F)

**Comment by lukebarnard1** [comment]
As I feared, Riot has managed to put a fake tag in your room's tags. This should not be possible but the way the RoomList is implemented easily lends itself to this kind of issue.

The fix for this is quite simple - special case tagging of rooms with "im.vector.fake.*" to not actually tag rooms, which can be done once https://github.com/matrix-org/matrix-react-sdk/pull/1719 lands.

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/1719 has been merged, so as I understand it this is unblocked now? 😇

**Comment by lukebarnard1** [comment]
Ohhhhh I think this is the same bug as https://github.com/vector-im/riot-web/issues/6287 because the room in that issue was likewise tagged as im.vector.fake.recent.

The login in RoomListActions does not protect against this, and is quite a simple fix - never tag a room as a fake thing.

**Comment by turt2live** [comment]
Having analyzed by account data in more detail recently, it was indeed tagged weirdly and caused Riot confusion. Not sure what caused it, but also haven't ever seen it since. Manual correction made it unstuck.
