### ISSUE TITLE
Wrong avatar for toml in pill

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6063]
### Description

![image](https://user-images.githubusercontent.com/1190097/35536025-d07cb5de-0502-11e8-9b66-eb1753c6b93b.png)

The tooltip is to show that I don't mean the matrix.org toml (whose avatar is shown here). The matrix.org toml autocompleted first in #riot, but I selected the lant.uk one instead. It's worth noting that the "real" (lant.uk) toml has no avatar as far as my riot is concerned due to the media repo getting confused and throwing a 404.

Sending the message causes the right avatar to be loaded (or lack of avatar, in my case).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Minor rather than major because it's "just" in the composer - if we were rendering the wrong avatars in the timeline I think that would certainly be major.

**Comment by turt2live** [comment]
This has since been fixed through magic
