### ISSUE TITLE
[about.riot.im] Smooth scrolling interferes with OS scrolling

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6064]
See conversation starting at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1517260641413156vyfND:matrix.org (#riot)

**Comment by lampholder** [comment]
I get slightly different scrolling experience across windows, mac and ubuntu - mac is the most pronounced, in which a single tick of the mousewheel scrolls me maybe 10 lines - on windows/ubuntu it's more like 3 lines.

**Comment by turt2live** [comment]
yet another one for @nadonomy

**Comment by turt2live** [comment]
Presumed fixed in the rebrand
