### ISSUE TITLE
Inline permalinks get converted to quotes

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6065]
### Description

It's a bit awkward to see a permalink get converted to a quote in the middle of your message:

Message:
```
This is a test <a href=\"https://matrix.to/#/!vfFxDRtZSSdspfTSEr:matrix.org/$1517257908201oFmrE:riot.ovh\">permalink to another message</a> to show a bug in riot.
```

Result:
![image](https://user-images.githubusercontent.com/1190097/35542802-445fcbf0-051f-11e8-8f3a-75b33394961f.png)

Expected:
![image](https://user-images.githubusercontent.com/1190097/35542839-64ea8c52-051f-11e8-9537-990f9f001bb6.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Also fixed by a more explicit format (other issue somewhere)

**Comment by t3chguy** [comment]
Fixed by merged PR
