### ISSUE TITLE
clicking on RRs should surely open MemberInfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6066]

**Comment by lukebarnard1** [comment]
Currently they toggle the +n RRs sliding out from underneath if there are >5

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5784

**Comment by lukebarnard1** [comment]
Also this is a dup: https://github.com/vector-im/riot-web/issues/5784

**Comment by lukebarnard1** [comment]
o_o @t3chguy jinx!
