### ISSUE TITLE
opening a /develop tab with /app still open makes e2e fail

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#6069]
maybe before migrating to indexeddb, warn the user to close all other Riot tabs.  See https://matrix.to/#/!boLskYiwabbCQNNhlK:sw1v.org/$15173457771642556SVZGs:matrix.org

**Comment by turt2live** [comment]
related: https://github.com/vector-im/riot-web/issues/168

**Comment by richvdh** [comment]
well I guess that now that /app has been updated, this is no longer an issue?

**Comment by uhoreg** [comment]
Yup, it's probably too late for it to be worth doing anything here.
