### ISSUE TITLE
'Check for updates' button on chat.status.im 404s

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6071]
The call to version?cachebuster=12312312312312 404s, when it... shouldn't.

Works fine on /app and /develop.

**Comment by lampholder** [comment]
We should let status know when this is fixed :)

**Comment by t3chguy** [comment]
So this is just the `https://chat.status.im/version` file missing, I guess someone deployed them weirdly?

**Comment by lampholder** [comment]
Yeah, I think so.

**Comment by t3chguy** [comment]
Seems like the entire deployment is not available, if this is by intent then this ticket can probably be closed

**Comment by turt2live** [comment]
Closing in favour of internal tickets.
