### ISSUE TITLE
Reports that riot.im/develop is defaulting to the dark theme before light

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6075]
### Description

At least 3 people have noticed that riot.im/develop (or self-built versions of it) are defaulting to the dark theme instead of the light theme. It eventually loads correctly, however it should be defaulting to the light theme.

Given the following outputs, it should be the light theme:
```
theme @ device = undefined
theme @ account = light
theme @ config = light
```
```
theme @ device = undefined
theme @ account = light
theme @ config = undefined
```

The output from above is from some very nasty javascript to simulate what the settings handler should be doing:
```
var theme = JSON.parse(localStorage.getItem("mx_local_settings") || "{}")["theme"];
console.log("theme @ device = " + theme);
var theme = (mxMatrixClientPeg.get().getAccountData("im.vector.web.settings") || {getContent:function(){return{};}}).getContent()["theme"];
console.log("theme @ account = " + theme);
var theme = (mxReactSdkConfig || {})["default_theme"];
console.log("theme @ config = " + theme);
```

The default is hardcoded to light, so this requires some investigation or more logging (or both).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
> TravisR:  on another account that I haven't configured at all, I get
> ```
> theme @ device = undefined
> theme @ account = undefined
> theme @ config = light
> ```
> and the theme stays dark even after loading even though settings show its light

:(

**Comment by lampholder** [comment]
Loosely related: https://github.com/vector-im/riot-web/issues/4895

**Comment by MTRNord** [comment]
Wasnt the theme loaded at a later point since the Status.im Theme changes? Means it might be a Timing issue on load?

**Comment by turt2live** [comment]
It's possible it's just a timing issue, although it's supposed to fall back to the light theme regardless. The people seeing the dark theme don't have any reference to it.

**Comment by MTRNord** [comment]
A more verbose Version of my 2 questions: I am not sure If this is the case but maybe the themes get loaded before the granular settings get loaded

**Comment by lukebarnard1** [comment]
>It eventually loads correctly, however it should be defaulting to the light theme.

Investigating this, I reckon it might be to do with the fact that we show the client prior to a network `/sync` being done, so one way to repro is to:
 1. Change theme in UserSettings
 1. Immediately refresh
 1. See theme flick from default (light) to the previous and then finally to the correct theme when the incremental /sync finishes

**Comment by turt2live** [comment]
That doesn't explain https://github.com/vector-im/riot-web/issues/6075#issuecomment-362091221 though :(

**Comment by lukebarnard1** [comment]
So I'm able to reproduce a bug in firefox where I've selected the dark theme but the loading spinner is shown with the status theme. I think this is a bug where firefox doesn't honour the "disabled" attribute on the `<link rel="stylesheet"` and the status theme comes first so it takes precedence.

**Comment by ara4n** [comment]
ugh. firefox and chrome handle alt stylesheets completely differently; i thought i had got this working through - through a fragile combination of the disabled attribute versus programmatically enabling/disabling them using JS (or adding them to the DOM on demand)? this is particularly fiddly as the tint stuff needs to be able to edit the CSS after it loads to fix up any variables.

**Comment by lukebarnard1** [comment]
I saw this SO comment which seemed to hold true when I tested it out: https://stackoverflow.com/a/48798173

Alternatively, could we create `<link>` tags on the fly, whilst retaining ability to alter the CSS after loading? That way we could just keep one link tag that we create and modify if the theme changes?
