### ISSUE TITLE
Horizontal scrollbar on particularly sized messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6077]
### Description

Apologies for the weird message, the actual message that caused this is meant for a private conversation so some masking had to be done.

```
abc ad a testing hhhhhh: user testinga party be abcd. Abcd I abcd is lotsofwords yesyes 2 test abc pkliiiiiiiiii ab the kliimi testab iiiiiiiiiiiii. Aii `Oiwords:w.io` testab conta ma abc de testab 'OLONGwor:dsh''''. 

```

The extra newline at the end is required to get the scrollbar. Here's the result:
![image](https://user-images.githubusercontent.com/1190097/35661408-36509a92-06cf-11e8-800e-caa3aecc057e.png)

In my case, the entry field (`div.notranslate public-DraftEditor-content`) is exactly 685.91x57 pixels.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I can reproduce this reliably across all platforms.

To reproduce:
- focus the composer
- type "This is ugly" with each word on a separate line
- put your cursor at the end of the 'is'
- press and hold the spacebar
- voila: 
  ![image](https://user-images.githubusercontent.com/1922197/35673397-5d1c5b38-0739-11e8-9221-ee1bc60bc4ba.png)
