### ISSUE TITLE
Embed riot on a website

### ISSUE THREAD

**Issue by zaesarius** [vector-im/riot-web#6078]
Hi, 

Is it there an iframe or kind of widget for integrating a riot group on a website?

Thanks

**Comment by t3chguy** [comment]
This is not really what "Issues" are for, You can iframe riot if you host it yourself (the one hosted at riot.im does not expose headers which allow iframing)

**Comment by t3chguy** [comment]
Try https://matrix.to/#/#riot:matrix.org for further queries

**Comment by zaesarius** [comment]
Thank you Michael
