### ISSUE TITLE
Community settings cog icon is pushed off screen by long community name / ID

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6079]
So you can only click it by expanding the window

**Comment by lampholder** [comment]
Aaaand it looks like I'm a member of my new group `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` until this is fixed :P
