### ISSUE TITLE
Don't name empty 1:1 rooms 'Empty room'

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6083]
> Feature request: as well as retaining the icon for DMs the other person has left, retain the name

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15176150771364oQANG:berigora.net

**Comment by lampholder** [comment]
I feel like I've moaned about this in the past, though I can't find that moaning in a github comment at present :)

Calling the room 'Empty room' makes it _very_ difficult to find a chat with somebody who has since left your 1:1 room.

**Comment by turt2live** [comment]
As a note for someone who picks this change up: This may also require a spec change. The spec says that the room should be named "Empty room (was YourFriend)", however the js-sdk(?) just calls it "Empty room".

It might be worthwhile to change the spec to special case 1:1 chats to show "YourFriend" instead of "Empty room...".

**Comment by dbkr** [comment]
Good point that this is specced. I think what I'll do is make a spec bug to think about updating this in the future (just in case this turns out to be a terrible idea and confuse everyone...)
