### ISSUE TITLE
Rooms not being automatically flagged as 1:1's anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6088]
### Description

A few IRC users have invited me to rooms, however those rooms are under "Rooms". They should have automatically been considered 1:1 chats. This used to be the case, so I believe this is a regression.

I can also reproduce this with real matrix users using the 'start chat' button.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
Tried to repro this but for me, inviting a user to chat via 'start chat' puts the room in 'people' on both the receiving and sending side.

**Comment by t3chguy** [comment]
@dbkr though the issue mentions IRC. I'd suggest messaging yourself from IRC to see what happens

**Comment by dbkr** [comment]
Oh good point, this is probably the heuristic failing since the irc bridge isn't supplying the m.direct flag.

**Comment by ara4n** [comment]
https://docs.google.com/spreadsheets/d/1iWWorOY0_RWnNPsoijlBBejhQTDAqcVoJvTW4oiUAXY/edit#gid=0

**Comment by lukebarnard1** [comment]
>Oh good point, this is probably the heuristic failing since the irc bridge isn't supplying the m.direct flag.

This turned out to be true - the IRC bridge wasn't setting is_direct when creating the room.

**Comment by lukebarnard1** [comment]
Reopened because we haven't tested all of the code paths to getting a direct message.
