### ISSUE TITLE
Question: If a community has no rooms, no members, no admin, etc, is it removed after time?

### ISSUE THREAD

**Issue by lectrode** [vector-im/riot-web#6094]
I created a community with a test account, but didn't see any option to delete it. I "left" it, hoping I could re-create it with my actual account, but I get the message "Something went wrong whilst creating your community. Group already exists"

This community had no rooms, and currently has no members. Will it get deleted after some time, so the name can be reused? I tried looking for a FAQ or something but the only one I could find (https://about.riot.im/need-help/ ) didn't have anything about communities.

Community was created on default matrix.org servers.

**Comment by turt2live** [comment]
Communities are not deleted when they become empty. This is reported as https://github.com/vector-im/riot-web/issues/5354

Generally support queries are best asked in [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org) as this area is intended for bug reports and feature requests.

**Comment by lectrode** [comment]
Thank you. I'll close this since it is already open as a bug/request.
