### ISSUE TITLE
Please add a "mark all as read" button, or some meaningful equivalent.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6097]
clicking "Jump to first unread message" becomes completely useless if you've not kept up with it. I have rooms where my first unread message is months ago and there's no way for me to slowly scroll through months and months of talk so that the first unread message marker is in the appropriate place. 

Please add a "mark all as read" button, or some meaningful equivalent.

**Comment by lampholder** [comment]
From a rageshake

**Comment by t3chguy** [comment]
There is such a button @lampholder - its the `X` button on the banner, it used to say "Mark all as read" but then that was removed.

**Comment by turt2live** [comment]
Loosely related: https://github.com/vector-im/riot-web/issues/850

**Comment by ara4n** [comment]
as @t3chguy pointed out, it's the X.
