### ISSUE TITLE
Button to pop out widget

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6099]
### Description

As much fun as it is to edit a document in a room, in a multi-tasking world it would be nice to shove the document over to a new tab and continue talking with other teams/rooms.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Half-Shot** [comment]
+1 to this, it's very impractical to split the view with doc editing.

**Comment by turt2live** [comment]
done
