### ISSUE TITLE
Character error

### ISSUE THREAD

**Issue by wonderoftheworld1** [vector-im/riot-web#6101]
Chat Error
Characters are missing when I type other language (ex Chinese/Korean/Japaneses)
Ex) this is test --> (send) --> "this"
all the words after first word disappear(words disappear after space)
<must be fix soon as possible. very basic function not working.>

**Version information**

OS: Windows 10
Version: riotweb 0.13.4 / olm 2.2.1

**Comment by wonderoftheworld1** [comment]
Also, foreign language bots command do not work.
Ex) !guggy (non-english)
Output image is not related image at all.
I checked Guggy and other bots for non-english search and plenty of data exist

**Comment by lampholder** [comment]
Potentially related to https://github.com/vector-im/riot-web/issues/5495?

Could you provide more detail about the browser + version? And the OS text entry method you're using?
 Can you try the browser with all plugins disabled?

It'd be great to see an animated gif captured of the behaviour too - it's a little hard to visualise. Thanks for your help!

**Comment by turt2live** [comment]
@wonderoftheworld1 are you still seeing this on recent Riot versions (0.17 and higher)?

**Comment by turt2live** [comment]
Upon reflection, this looks very much like https://github.com/vector-im/riot-web/issues/5495 which means it gets bundled into an upstream issue with slate: https://github.com/vector-im/riot-web/issues/7665

Closing in favour of that.
