### ISSUE TITLE
Screen layout is ugly and broken when loading permalinks

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6105]
When clicking through search results to jump to the permalink, you get something that looks like this, with broken gemini as well as being way too high for the screen :(

<img width="2032" alt="screen shot 2018-02-07 at 14 17 17" src="https://user-images.githubusercontent.com/1294269/35921155-c5da1a66-0c11-11e8-85e5-cc29e30ec390.png">

**Comment by turt2live** [comment]
This is a duplicate of https://github.com/vector-im/riot-web/issues/4121 and https://github.com/vector-im/riot-web/issues/5544
