### ISSUE TITLE
Possibility to change the home URL of the Web Client

### ISSUE THREAD

**Issue by bn4t** [vector-im/riot-web#6108]
### Description
It would be nice being able to change the URL that is shown on `/#/home` using the config.

![grafik](https://user-images.githubusercontent.com/17193640/35963659-56e3086a-0cad-11e8-842d-68c358fad4fe.png)

### Version information

- **Platform**: web

- **URL**: https://riot.im/app/#/home and any riot-web installation

**Comment by t3chguy** [comment]
You can change the entire homepage by editing the `home.html` file in the root of where you host riot.
