### ISSUE TITLE
Riot fails in strange ways when indexeddb is full

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6120]
### Description

![image](https://user-images.githubusercontent.com/1190097/36070177-ce3001e6-0eb2-11e8-8a73-bbc33c6b3bbf.png)

This has lead to all kinds of fun problems:
* Syncs not being saved (https://github.com/vector-im/riot-web/issues/6118)
* Not being able to send bug reports/logs
* Encryption being reported as disabled in rooms (see screenshot below)
* Cannot send encrypted events (likely because Riot thinks encryption is disabled)

![image](https://user-images.githubusercontent.com/1190097/36070172-a516f2f6-0eb2-11e8-866e-59d753c72ce1.png)

Riot should probably fail a bit more gracefully. I didn't realize my storage was full until I went to start a report about encryption being disabled and happened to consider the case of indexeddb being full. The app runs fine otherwise - messages can be sent and received, features work, etc. The only problems are those described above.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
For those that may be running into this, clean up your primary drive. Chrome, for example, sets the maximum quota to ~6% of your available free space.

**Comment by lampholder** [comment]
As per #6125 (which I'm going to close as a dup) we need to warn loudly when this happens as a bare minimum. It would be nice also to tell people what they can do to address the problem (and ultimately even nicer make it so they don't encounter this problem by effectively managing the size of indexeddb.

**Comment by lukebarnard1** [comment]
Looking into this, there is a `QuotaExceededError` that will be passed to the `onabort` function attached to the indexeddb transaction (which we could potentially attach here:)

https://github.com/matrix-org/matrix-js-sdk/blob/678ff23bcbf385471632c56aec38746a6e87845b/src/store/indexeddb-local-backend.js#L65-L74

**Comment by turt2live** [comment]
Today's failure mode was silently failing to sync. Took nearly 3 hours before I realized that my client wasn't syncing.

**Comment by grahamperrin** [comment]
Thanks, 

> … We will need to move over to a different storage API: Storage. …

Is a future move _certain_?

**Comment by hrj** [comment]
E2E has suddenly stopped working for me since yesterday.
```
Unable to decrypt: The sender's device has not sent us the keys for this message. 
```

There was no change in browser versions or anything else on my system, but the free space on my disk did change drastically yesterday. So it is probably related to this issue.

To reclaim space, which tables of the Local storage / Indexed DB can we delete safely? I don't want to lose my device keys for sure. I assume log entries can be deleted without affecting functionality.

**Comment by ara4n** [comment]
can you rageshake so we can see whether the issue actually is indexeddb filling up?  the error you've quoted there could be related to other issues (e.g. failing to upload one-time keys to your server or something).

the safest bet is to export your E2E keys via settings, and then either relogin to entirely flush the storage, or you could experiment with manually deleting the `logs` and `matrix-js-sdk:riot-web-sync` tables from indexeddb. Not sure how gracefully the app would recover from the tables from disappearing under it, though, and the chances are relatively high that it will just panic and re-login.

**Comment by jryans** [comment]
https://github.com/vector-im/riot-web/issues/9220 tracks this problem as a meta-issue of several separate tasks. We have now implemented some of the ideas here and tracked the remaining ones in new issues, so I think we can close this.
