### ISSUE TITLE
People/rooms no longer ordered by recent activity

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6132]
### Description

I'm chatting with someone and the room on the left isn't moving to the top. The other chats above them are several days old, so I doubt this is a timezone/time parsing problem. Likely related to all the recent changes in the area.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
note: dragging a 1:1 conversation to anywhere in the list bubbled the conversations to the top

**Comment by turt2live** [comment]
Also affects the 'Rooms' category - updated title

**Comment by lukebarnard1** [comment]
So it looks like the RoomListStore is unaware of the general case for reordering sublists - it doesn't reorder for receiving an event that marks the room as unread.

**Comment by lukebarnard1** [comment]
Thinking about this, we ought to not try to duplicate the condition for reordering lists ordered by recent activity.

The ordering is based on finding the event closest to the end of the timeline that is:
 1. going to trigger/has triggered the "unread count" or
 2. sent by the current user.

By this logic, we only need to listen to `Room.timeline` events and only trigger a reordering of "recent" sublists if they fulfil these criteria.

**Comment by lukebarnard1** [comment]
In the end, we opted for generating every list to avoid a subtle early optimisation for causing bugs. An optimisation over regenerating everything could be to only regenerate lists that the room is in, but this is only really useful if the room is in many lists, which is only possible with custom tagging. Another optimisation would be to not bump the room to the top, but reorder it individually based on its updated TS, but this is still slightly subtle and unlikely to improve overall performance: there are other places where can do this.

(E.g. we could optimise the regeneration of all lists.)

**Comment by lukebarnard1** [comment]
@erikjohnston says this is still a problem for e2e rooms.

**Comment by lukebarnard1** [comment]
We decided to go for a different fix.
