### ISSUE TITLE
Tags lost ordering

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6135]
##### Yesterday (how I want my rooms ordered)
riot-web version: 1d2f5bafdac0-react-b4aa9f37f695-js-7df2bfe7bcd1
![image](https://user-images.githubusercontent.com/1190097/36158296-347e8bd8-1099-11e8-8dbb-af5a64cbf783.png)

##### Current /develop (random shuffling)
riot-web version: e67147213bd4-react-a0aa3df89381-js-7df2bfe7bcd1
![image](https://user-images.githubusercontent.com/1190097/36158244-17bf6c4c-1099-11e8-82bd-f14750142e7a.png)

All my tags were ordered how I wanted them, now they have all been shuffled strangely. Possibly related to #6132 

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by eternaleye** [comment]
I came here via the update notes saying this got fixed, but my channels are still in the reordered state they changed to. In addition, I can no longer reorder them with drag-and-drop.

**Comment by lukebarnard1** [comment]
I'll reopen this issue to track this incorrect behaviour (which I have reproduced).
