### ISSUE TITLE
broken layout with tagpanel disabled

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6136]
![screen shot 2018-02-13 at 16 53 18](https://user-images.githubusercontent.com/986903/36162474-74c0772a-10de-11e8-87f8-16000618485a.png)

**Comment by lukebarnard1** [comment]
This might be https://github.com/vector-im/riot-web/issues/6133

**Comment by ara4n** [comment]
it's even worse than this, hence the attempts at an emergency fix in #6138:

<img width="426" alt="screen shot 2018-02-13 at 21 45 03" src="https://user-images.githubusercontent.com/1294269/36176079-662e4590-1109-11e8-81e5-bc061a8484e1.png">

**Comment by ara4n** [comment]
https://github.com/vector-im/riot-web/pull/6134/ looks to have fixed it (based on testing locally)
