### ISSUE TITLE
Sometimes which theme you're on gets confused

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6141]
I just opened riot.im/develop firefox, it wasn't logged in, but was set to the dark theme. Logged in, went into settings, light theme was selected, even though it was still using the dark theme. Not sure how this happened.

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/6075

**Comment by ara4n** [comment]
i think @dbkr might have fixed this? i haven't seen it forever
