### ISSUE TITLE
Received push for invite but it didn't appear in RoomList

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6144]
A refresh fixed this.

The push resulted in:
 - Count on window title being `[1]`, favicon being red;
 - Audible bing;
 - Desktop notif.

This should have been caught by RoomListStore `MatrixActions.RoomMember.membership`, resulting in regeneration the room lists from MatrixClient state.

**Comment by lampholder** [comment]
@lukebarnard1 is this a regression from 0.13?

**Comment by lukebarnard1** [comment]
More info: I've had to refresh a couple of times to get the invites to appear - sometimes the push hadn't even arrived before I needed to refresh.

**Comment by lukebarnard1** [comment]
@lampholder I haven't determined whether this is even client-side yet; it could be the invite isn't being sent down the /sync stream. But given the changes to RoomList, I wouldn't be surprised.

**Comment by lukebarnard1** [comment]
In another instance, the invite didn't seem to have come down my /sync stream...
