### ISSUE TITLE
Use Referrer Policy to prevent referrers from being sent 

### ISSUE THREAD

**Issue by rugk** [vector-im/riot-web#6147]
I did not check whether you already use a similar mechanism, but it would be great if you can prevent the browser from sending the referrer when they click on a link (a user sent), so it does not leak to the site that the user came from Riot (including the whole URL).

The fix is easy, it's also just another [HTTP header or HTML meta tag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy). So even if you already prevent it in some other way, this is a really safe and small thing and works in all modern browsers, so you should really make use of that.

**Comment by rugk** [comment]
BTW you can also add `rel="noreferrer"` to links, but one referrer policy works for all links, so…

**Comment by lampholder** [comment]
Seems like a reasonable ask, and sounds easy to do.

P3 == a sensible feature that isn't on the team's roadmap right now, but we'd be happy to see it from a community contribution :)

**Comment by rugk** [comment]
If you look some centimeters/pixels above, I've already opened a PR… 😄
