### ISSUE TITLE
Sometimes when switching rooms the bottom portion of the timeline is cut off for a little while (develop)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6149]
### Description

![image](https://user-images.githubusercontent.com/1190097/36242791-21bda748-11db-11e8-8e7a-28d7cce0c0c8.png)

turns into

![image](https://user-images.githubusercontent.com/1190097/36242798-2e313170-11db-11e8-823c-9d198ca9bef9.png)

a few seconds after opening the room. This is most noticeable on messages, however by the time I notice the issue it's already fixed itself and my screenshot tool is unable to capture it.

Started happening within the last couple days. Doesn't always happen to rooms. Multiline messages are usually affected.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
@turt2live I saw this before but only ever on rooms were the "Jump to first unread..." was visible. Can you remember if this was the case?

**Comment by turt2live** [comment]
That feels accurate.

**Comment by turt2live** [comment]
Also when I jump to a room where someone is typing

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/4829

**Comment by WGH-** [comment]
This (or similar) bug has been annoying me for a long time. Sometimes its "scroll to the bottom" panel that obscures the last messages. And I'm on rather old version, 0.13.1, and also seen this on older versions as well.

**Comment by turt2live** [comment]
I finally caught it with a typing notification:
![image](https://user-images.githubusercontent.com/1190097/36985667-1c619ec0-2055-11e8-9096-aab5dfc46c6b.png)

**Comment by lukebarnard1** [comment]
@turt2live was there a "Jump to first unread ... " at the top of your view?

**Comment by turt2live** [comment]
nope

**Comment by turt2live** [comment]
Fixed by new typing notification behaviour
