### ISSUE TITLE
Many read receipts can easily cover the entire timeline

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6152]
![2018-02-15-110128_763x220_scrot](https://user-images.githubusercontent.com/6750344/36254110-b1503a40-1241-11e8-81b9-18568d0f5163.png)

We should consider better ways to indicate the full list of readers. (E.g. we could do as the mobile clients do and show a modal)

**Comment by turt2live** [comment]
Note that this is the other way around as of https://github.com/matrix-org/matrix-react-sdk/pull/2065

![image](https://user-images.githubusercontent.com/1190097/42972357-65a1d03c-8b6c-11e8-8404-6011fa75483f.png)

Hovering over the message makes it readable, although at risk of looking really broken:
![image](https://user-images.githubusercontent.com/1190097/42972378-731fdcea-8b6c-11e8-8adf-ef23b3862e93.png)

**Comment by Half-Shot** [comment]
https://matrix.half-shot.uk/_matrix/media/v1/download/half-shot.uk/3e7510e472deb185a7607e5c827b98b6 < me getting angry at it today.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7608 (due to https://github.com/vector-im/riot-web/issues/6152#issuecomment-406427348 )
