### ISSUE TITLE
Disable integrations

### ISSUE THREAD

**Issue by rugk** [vector-im/riot-web#6163]
As integrations are loaded from a third-party server and as a server admin, you might not that, please let us disable integrations.

(Just interpret when you set `integrations_ui_url` to `null` e.g.)
Similar to https://github.com/vector-im/riot-web/issues/5921

**Comment by turt2live** [comment]
Integrations can be disabled by setting the integrations_* settings to empty strings.

**Comment by lampholder** [comment]
Is this a feature that's already implemented, or do we need to do some work to make it more discoverable?

**Comment by rugk** [comment]
Aha, good. Maybe a config documentation is needed?

**Comment by turt2live** [comment]
The documentation is https://github.com/vector-im/riot-web/issues/1698 (which is wrongly closed imho)

However, there is some documentation in the readme under the config.json section:
![image](https://user-images.githubusercontent.com/1190097/36266586-08e029d6-122f-11e8-8e33-e3236f6ce135.png)

**Comment by lampholder** [comment]
Ah okay, that's not too bad :)

**Comment by rugk** [comment]
Ah, it's on https://github.com/vector-im/riot-web#configjson. Did not saw that,. ok.
