### ISSUE TITLE
Hello, Im interested in contributing to this project by translating the readme.md file to Spanish which is my native language, let me know if interested.

### ISSUE THREAD

**Issue by LuigiBaute** [vector-im/riot-web#6167]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by tulir** [comment]
I don't think translating the README is that relevant, as it's mostly for devs and advanced users rather than normal users. However, it seems that there's still a bit of stuff to translate in the app itself. If you want to help with that, check out https://github.com/vector-im/riot-web/blob/master/docs/translating.md

**Comment by LuigiBaute** [comment]
I'm sorry I can only make contributions when they are over a thousand words.

**Comment by lampholder** [comment]
Hi @LuigiBaute - I'd be interested in having a Spanish translation of the README, but I'd be afraid that it would get out of date and the core team would struggle to keep it current.

Are you interested in maintaining such a document, or only providing a one-off translation?

Either way, it might be useful to have (as long as it clearly stated 'TRANSLATED on THIS DATE; latest updates in English in README.md').

Are there github repo conventions for internationalisting READMEs?

Also - out of interest @LuigiBaute are you happy to share the reason for only translating 1000 words +?

**Comment by LuigiBaute** [comment]
I work under the rules of Utopian-io and therefore my contributions need to be of over a thousand words, and one time translation. so I can only offer you one translated doc as you said:  'TRANSLATED on THIS DATE; latest updates in English in README.md'... let me know if you're still interested.
