### ISSUE TITLE
Not all the hover effects are triggered in some areas of the LLP

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6170]
### Description

![image](https://user-images.githubusercontent.com/1190097/36271123-ee3e419c-123a-11e8-9678-eca64d64ce42.png)

Moving the mouse out a little bit causes the avatar to lose it's hover effect, however moving it in gives me the full hover effect (tooltip and context menu).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Hot damn, is github in github? I really want to fix their label UX.

**Comment by lukebarnard1** [comment]
@lampholder what is your obsession with this mistake label? It's somehow fulfilling it's own prophecy! Maybe you should rename it to something else??..

**Comment by turt2live** [comment]
fwiw, now that I've learned that you can remove groups from the LLP this is more irritating than before. I know that the context menu is there, but unless I move my mouse significantly inwards it doesn't give me a hover effect.

**Comment by t3chguy** [comment]
I cannot repro this nowadays

**Comment by turt2live** [comment]
We've lost the opacity feature which might be a bug of its own. For now I'll count that as intentional.
