### ISSUE TITLE
Dropping a group already on the LLP makes the LLP create a gap

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6172]
### Description

The reproduction steps are probably more interesting than what I have to say.

### Steps to reproduce

1. Go to the groups homepage
2. Drag a group over to the LLP
3. After dropping it, observe this behaviour:
    ![image](https://user-images.githubusercontent.com/1190097/36272818-d6248a76-123f-11e8-92a9-5a5c3a91458c.png)
4. In the room list, go to a different room (cause a re-render of the LLP)
5. Observe a gap
    ![image](https://user-images.githubusercontent.com/1190097/36272850-eac5d4b2-123f-11e8-88ab-24e48a53e959.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
@turt2live can you send some logs? The expected behaviour (although slightly strange) is for the existing one to move to the position of the dropped one.

**Comment by turt2live** [comment]
@lukebarnard1 I haz an err 4 u!

```
TagOrderActions.js:46 Uncaught TypeError: Cannot read property 'filter' of null
    at Object.TagOrderActions.moveTag (TagOrderActions.js:46)
    at Object._onDragEnd (LoggedInView.js:229)
    at exports.default (fire-hooks.js:71)
    at drag-drop-context.js:137
    at dispatch (createStore.js:186)
    at index.js:14
    at dispatch (applyMiddleware.js:45)
    at action-creators.js:316
    at index.js:11
    at Object.dropAnimationFinished (bindActionCreators.js:7)
    at Draggable._this.onMoveEnd (draggable.js:100)
    at moveable.js:89
```

**Comment by lukebarnard1** [comment]
Ah. TagOrderActions.moveTag assumes that you've removed some tags... This is thankfully an easy fix!

**Comment by turt2live** [comment]
(TIL you can remove groups now 🎉)
