### ISSUE TITLE
Screensharing no longer works in chrome 64

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6181]
Failed to get screen-sharing stream: NotAllowedError: Invalid state - despite having the plugin installed.

**Comment by lampholder** [comment]
I couldn't reproduce this - after https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes, access to the mic and the camera is blocked, but I could still screenshare.

**Comment by lampholder** [comment]
Ah; not the jitsi screen share - the shift-click-on-the-video-call-button screen share.

Yeah; this is broken but it's not a scalar thing.

**Comment by MurzNN** [comment]
Seems permission problem can be fixed using new getDisplayMedia() API in Chromium v70  https://groups.google.com/forum/#!msg/discuss-webrtc/Uf0SrR4uxzk/uO8sLrWuEAAJ

**Comment by edsoubsoub** [comment]
Hello,
I still have "Failed to get screen-sharing stream: NotAllowedError: Invalid state" on Chrome only.
Chrome Version 73.0.3683.103 (Build officiel) (64 bits)
I also enable on chrome://flags :
 - Experimental Extension APIs
 - Experimental Web Platform features
And https://cdn.rawgit.com/uysalere/js-demos/master/getdisplaymedia.html is working well ...

Hope someone can help me to fix the screensharing on Chrome.

**Comment by szimszon** [comment]
The problem is also there on Desktop version: 1.4.2 for Linux...

**Comment by polyrain** [comment]
Is there an update on this?

**Comment by mjattiot** [comment]
@polyrain I made a PR https://github.com/matrix-org/matrix-js-sdk/pull/1276/

**Comment by tuxflo** [comment]
While this seems to work in Chrome now, the same error message still appears in the riot deskop client. Any ideas how to deal with that?
