### ISSUE TITLE
Jitsi widgets no longer work in chrome 64

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6182]
Lots of big yellow error warnings, and meanwhile it looks like the permissions aren't available for jitsi to capture media from within its iframe

**Comment by rxl881** [comment]
Hopefully this is now fixed. There were various problems, but in short Chrome 64 introduced some new iframe permissions. I've added the necessary camera, microphone and media permissions back for the widget iframes in https://github.com/matrix-org/matrix-react-sdk/pull/1766.

In addition to this I also had to upgrade our jitsi-meet instance to the latest stable (as that also creates an iframe that needs the additional permissions).

Tested working on /develop.
