### ISSUE TITLE
Can easily end up in a state where your room list is non-interactable until you fix it

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6184]
### Description

The easiest ways I've found to reverse the effect are:
* Going to the group's settings page and clicking the X in the top right
* Refreshing riot

### Steps to reproduce

- Open a group's settings
- Click the "Communities" button at the bottom of the LLP
- Your room list is now not interactable, even if you manage to escape the groups area
  * To escape the groups area, go to a group's page and click on a room

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Oh yeah! That's awful :)

**Comment by lampholder** [comment]
Two approaches to address:
1. disable LLP when you're in settings
2. reenable roomlist when you're in settings **and ensure that all interactions with LLP and roomlist whilst in settings are safe**

Option 1. is quick (probably). I think @ara4n was keen we ultimately move in the direction of reenabling the roomlist when you're in settings (though annoyingly I can find a written conclusion on that - @ara4n can you remember what you decided?)

**Comment by lukebarnard1** [comment]
I think the decision was not to allow a single interaction on any faded UI - a click which exists User/Group/RoomSettings and returns the UI to its normal opacity
