### ISSUE TITLE
Changing the group's avatar does not update LLP

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6189]
### Description

It should at least update for the person who changed the avatar. I think there's a different bug already reported for pushing these kinds of updates to other people somewhere.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Caching caching caching :(

As you say - it should at least update for the person doing the updating; some sensible cache invalidating should be easy there?

**Comment by turt2live** [comment]
This seems like a similar issue to https://github.com/vector-im/riot-web/issues/5559 fwiw. I haven't tested otherwise though.
