### ISSUE TITLE
Room selection suggestion for 'Riot' gives HQ

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6191]
### Description

![image](https://user-images.githubusercontent.com/1190097/36322821-04639a0e-130c-11e8-9821-42cd0d88d2b7.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5348#issuecomment-342125777

(Linked to comment which explains behaviour)
