### ISSUE TITLE
Updating rooms on a group does not update the filter

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6192]
### Description

I created a group, added some rooms to it, filtered it using the LLP, and added more rooms to it. The room list did not update, even after navigating to a different group and back.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yeah, at the moment you have to refresh :(

**Comment by turt2live** [comment]
This got fixed it seems.

**Comment by brylie** [comment]
I have also experienced this issue and reported it in #11824 

I have tried refreshing as well as clearing cache then reloading.
