### ISSUE TITLE
Invites not appearing in room list

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6200]
### Description

Original bug: https://github.com/vector-im/riot-web/issues/6144

I'm still seeing this, however my steps may have affected the outcome slightly:
* Was filtering on a group in the LLP
* Received invite to a room
* Went back to 'global' in the LLP
* Invite not visible in room list

As with #6144, I also received the desktop notification, audible bing, favicon change, and title change.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
I can confirm this is an issue, I've just seen it myself.

**Comment by lukebarnard1** [comment]
Saw this again just now, I can confirm the invite didn't arrive in my /sync stream :/

**Comment by lukebarnard1** [comment]
So I think this is being caused by incorrect assumptions about when RoomMember.membership is fired. It's only fired for changes to a membership, which is not something that happens when we get a new room in the `invite` state in the /sync.

The solution is fairly simple - we use the correct event.

**Comment by lukebarnard1** [comment]
Further investigation reveals that we process and event room-specific events before even storing the room if it's new to the client. We have to use the "Room" event if we want to re-render things when new rooms are added to the store.
