### ISSUE TITLE
Clicking the X (was logo) in LLP causes a light grey box

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6220]
### Description

![image](https://user-images.githubusercontent.com/1190097/36502806-48b6fa2a-1708-11e8-9281-d50a69844a59.png)

This is a bit distracting, and the icon disappears to make it less helpful. I assume this is part of the accessibility stuff.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
So this was basically to indicate focus to the clear button, but it looks like its container is focusable.

**Comment by lukebarnard1** [comment]
Fixed by
