### ISSUE TITLE
X in LLP is not dark theme compatible

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6221]
### Description

![image](https://user-images.githubusercontent.com/1190097/36502858-6cf620b4-1708-11e8-87f8-5abe5c7658c9.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I think it's a tiny bit smaller, too?

**Comment by lampholder** [comment]
Sorry - smaller than its friend the X button that appears in the filter room names box when you type in a room name.

**Comment by lukebarnard1** [comment]
Actually, it's not smaller. It's lower :man_facepalming: : 

![2018-03-08-165152_363x291_scrot](https://user-images.githubusercontent.com/6750344/37163986-0ad290c6-22f1-11e8-9e2d-8e737149d2f7.png)

**Comment by lukebarnard1** [comment]
Bizarrely, having fixed the position; there's still an illusion where the "X" in the LLP *appears* smaller o_o

![2018-03-08-170100_391x170_scrot](https://user-images.githubusercontent.com/6750344/37164542-7ffc2154-22f2-11e8-8f3e-cbf5ab577c25.png)
