### ISSUE TITLE
":D*space-bar*" -> :grinning: but ":D*wait 200ms*" -> weird suggestions

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6232]
![2018-02-22-152111_872x306_scrot](https://user-images.githubusercontent.com/6750344/36546724-082b68d8-17e4-11e8-8cb1-cb87048059f3.png)

and this is true for others:
 - `0:)`: pressing space gives :innocent: but waiting gives japanese symbols (and :innocent:)
 - `:o`: pressing space gives :open_mouth: but waiting gives :o: :ox: etc..
 - `:p`: pressing space gives :stuck_out_tongue: but waiting gives :pig: :poop: etc.. 
 - `:L`: pressing space gives :confused: (should this be :laughing:?) waiting gives :o: :a: :b: etc.

**Comment by lampholder** [comment]
Don't we have essentially two distinct mappings?

We have:
- ascii emoticon -> emoji, and
- the emoji name (:name:) -> emoji

It certainly is odd that the obvious emoji doesn't appear in your search results (though in practice this doesn't often trip me up).

**Comment by lukebarnard1** [comment]
We do have two mappings but the ascii mapping should take precedence. I seem to remember that there was a functional restriction on this but I can't remember exactly what it is.

**Comment by yannicka** [comment]
Do you still have the issue?

**Comment by t3chguy** [comment]
cannot repro
