### ISSUE TITLE
Clicking mailto links closes riot

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6248]
### Description

It should open the link in a new tab or something else. Taking over riot isn't great when you accidentally click on an email address.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Can't reproduce on macOS, is this still an issue?

**Comment by turt2live** [comment]
I think we fixed this.
