### ISSUE TITLE
Implement cancelling 3pid invites

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#625]
Blocked on support from synapse (https://github.com/matrix-org/synapse/issues/1473)

**Comment by ara4n** [comment]
I have no idea why we've never done this; it should be trivial - surely we just delete the 3PID invite from the DAG. Does it even need synapse changes?

**Comment by ara4n** [comment]
yeah, i just deleted a stuck one via /devtools by setting the body of the 3pid invite state event to {} and it dutifully disappeared.  the only nastiness is that you end up with

<img width="428" alt="screenshot 2018-09-12 at 11 53 35" src="https://user-images.githubusercontent.com/1294269/45420638-8d741980-b682-11e8-9658-a640f3141612.png">

in the timeline, plus the empty state event obviously hangs around forever, but that's a problem of https://github.com/matrix-org/matrix-doc/issues/456

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/5490

**Comment by ara4n** [comment]
You could, but i'm not sure it's the end of the world, given the IS will try exchange the 3pid invite for a real invite, which will fail because the 3pid invite will have been deleted (aka replaced by `{}`)

**Comment by thomas4019** [comment]
Any update on this?

**Comment by gdvine** [comment]
This is an important security feature actually, as 3PID unaccepted invites hang around forever and are impossible to revoke currently. So if a user wishes to disinvite a user that never had a chance to accept, he/she can't.
