### ISSUE TITLE
Dropping an icon in the LLP while filtering causes the filter to be cleared

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6253]
### Description

1. Click a group to filter on it
2. Move any group in the LLP

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
So it does! That's annoying.

@lukebarnard1 if this is trivial to fix whilst we're in the area lets consider it for 0.14; I think if you're not expecting to touch that code again before 0.14 maybe lets leave it until (soon) after.

**Comment by lukebarnard1** [comment]
I reckon this is the same thing causing https://github.com/vector-im/riot-web/issues/6156 which is in-turn caused by https://github.com/atlassian/react-beautiful-dnd/issues/273 and fixed by https://github.com/atlassian/react-beautiful-dnd/pull/353, but this hasn't been released.

**Comment by turt2live** [comment]
Probably. Is the entire LLP background supposed to clear the filter, or just the X at the top? Currently it seems to still be the entire thing

**Comment by lukebarnard1** [comment]
The intention is that the background also clears the filter.
