### ISSUE TITLE
UserSettings -> Notifications spinner is in a weird place

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6254]
![2018-02-26-182101_914x444_scrot](https://user-images.githubusercontent.com/6750344/36687559-e8f2b71e-1b21-11e8-8c1a-a777be11bbcf.png)

Maybe let's put it next to the header "Notifications"? Also we should standardise this sort of thing.

**Comment by turt2live** [comment]
Fixed, afaict
