### ISSUE TITLE
Broken image on 'clear filter' button.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6258]
Reported by Rick:

When there's a notification and the 'remove filter' button is visible, the 'remove filter' image doesn't seem to load (it renders as a broken image).

**Comment by lukebarnard1** [comment]
This reeeally needs more detail. E.g. was it on `/develop`?

**Comment by lukebarnard1** [comment]
Apparently, it was but this was only a problem for the first time the image was viewed. 

I could only imagine that there was a failure in requesting the image for some reason or another, potentially related to it being the first request for this particular image since the client started.

**Comment by lampholder** [comment]
Yeah, I think let's close this - if other people report the same thing then we can ressurect.
