### ISSUE TITLE
If something goes wrong with setting your displayname, the error message replaces the input field.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6267]
![image](https://user-images.githubusercontent.com/1922197/36799256-a27fa1c8-1ca4-11e8-969e-85065c2bd9fb.png)

In the end, it did actually also successfully change my displayname.

**Comment by lukebarnard1** [comment]
@lampholder I wonder if it failed for a particular room...

**Comment by turt2live** [comment]
not anymore
