### ISSUE TITLE
Slack Integration still in channel

### ISSUE THREAD

**Issue by Sorunome** [vector-im/riot-web#6270]
hey, i went half-way through setting up a slack integration with the built-in widget thing, thus the matrix.org provided slack bridge. the `@slackbot:matrix.org` user already joined the channel and made itself admin, but then i changed my mind and stopped. Is there a way to remove the bot from said channel? Slack doesn't show up as a "current integration"
i can't kick it as it has admin and thus same power level as me

**Comment by zymptomLabs** [comment]
same problem here

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/6427
