### ISSUE TITLE
'This image cannot be displayed' warning is styled the same as normal message text.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6271]
![image](https://user-images.githubusercontent.com/1922197/36837401-3560328e-1d34-11e8-97c6-516b28d8f108.png)

**Comment by jevolk** [comment]
![screenshot from 2018-03-13 23-48-56](https://user-images.githubusercontent.com/4682706/37387393-6bdd2d5a-2719-11e8-8007-52aa8c5937b4.png)
