### ISSUE TITLE
There is no obvious way to view devices keys of once verified devices.

### ISSUE THREAD

**Issue by nagua** [vector-im/riot-web#6277]
### Description

If you use multiple devices in multiple locations for riot there is no way to "transfer" the verified devices to another device. It would be helpful if I could see the device key, that was verified in the device list of a person.

In this way I can verify the devices of a friend on my mobile phone. Once I login to a new devices I get my mobile phone and recheck all devices that I have verified there and also verify on my new client this way.

### Version information

- **Platform**: same on android (play store) and riot-web (current master)

**Comment by lampholder** [comment]
I think (at least configurable) shared/transitive/inherited verification and trust is the intended direction of E2E UX to meet exactly this usecase.

**Comment by nagua** [comment]
Hey, I can understand that this will be the long-term solution and I would prefer that solution.
But I think showing the verified keys of other devices would be an easy to implement short term fix for this issue.

**Comment by uhoreg** [comment]
dup of #2735

**Comment by gerroon** [comment]
+1 Please, this will be very helpful to have in the trusted clients.
