### ISSUE TITLE
When adding E2E(!) rooms to favourites, the room stays under "Rooms" and is also under "Favourites"

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6287]

**Comment by lampholder** [comment]
I couldn't reproduce this - did you do it by dragging or with the context menu?

**Comment by lukebarnard1** [comment]
Context menu.

**Comment by lukebarnard1** [comment]
This has nothing to do with the e2e-ness. I actually think this is another case of https://github.com/vector-im/riot-web/issues/6287
