### ISSUE TITLE
mac users are unable to scroll on group details pages at all

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6294]
on status theme; neither room list nor people list is scrollable

**Comment by lampholder** [comment]
I'm using Chrome on my Macbook Air btw, and it's all communities pages that are affected.

**Comment by lukebarnard1** [comment]
This is definitely platform-specific; it's only happening on Chrome on macOS.

**Comment by lukebarnard1** [comment]
One option would be to `forceGemini` on every GeminiScrollbar we use. This means we don't get native scrollbars ever, but does reduce maintenance required on this.

**Comment by lukebarnard1** [comment]
Decision on this is to `forceGemini` on all of our GeminiScrollbars. It's probably a good idea to also wrap it in our own component to have one place to give things to the API across the app.
