### ISSUE TITLE
"Only a server admin can create groups on this server" Communities doesn't work.

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/riot-web#6296]
### Description

Can't create a community, comes up with error:

"Something went wrong whilst creating your community
Only a server admin can create groups on this server"

### Steps to reproduce

- Try create a community on Riot.
- Click 'create'.

Describe how what happens differs from what you expected.

Community should be created, instead error message is produced.

Log: sent/not sent?    

![community](https://user-images.githubusercontent.com/29645145/37254277-c8443f92-2576-11e8-89dc-bd9750ec6c11.png)

### Version information

0.13.5

- **Platform**: web (in-browser) or desktop?

Desktop.

For the desktop app:

- **OS**: Debian Linux
- **Version**: 0.13.5

**Comment by t3chguy** [comment]
This is a Synapse configuration, you can either become Server Admin or you can modify your Synapse config to allow any local users to make Communities

**Comment by MurzNN** [comment]
Thanks for the link, will be good to document this option in some docs.
