### ISSUE TITLE
Transparent avatars on the LLP are green now (when selected)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6305]
### Description

They used to be white.
![image](https://user-images.githubusercontent.com/1190097/37317011-17ca677e-2628-11e8-8d8e-3d398488247e.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Monginoth** [comment]
Is this a 24bit or 32bit PNG?  (good) Or an 8bit PNG? (not good)

**Comment by turt2live** [comment]
32 bit. This is specifically caused by https://github.com/vector-im/riot-web/pull/6290

**Comment by lampholder** [comment]
Blue if you're on the status theme :P 

Is this necessarily a problem? Or were you just flagging it because it is a possibly unintentional change?

**Comment by turt2live** [comment]
I feel relatively strongly that this should be fixed for 0.14. Particularly considering the backgrounds are white when not selected, and then suddenly different. To demonstrate this problem, here's the difference of having nothing selected and all of them selected:

![image](https://user-images.githubusercontent.com/1190097/37357447-1710f0d8-26ae-11e8-9974-ef571d6b1937.png)

**Comment by ara4n** [comment]
@turt2live did this get fixed?

**Comment by turt2live** [comment]
Nope
![image](https://user-images.githubusercontent.com/1190097/52363554-2fb0e700-2a00-11e9-936f-757080d296e3.png)

**Comment by aaronraimist** [comment]
This seems to be fixed now
