### ISSUE TITLE
Tests for Prevention of [some] RoomList Regressions

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6315]
In order to have some degree of confidence in merging:
 - https://github.com/matrix-org/matrix-react-sdk/pull/1801
 - https://github.com/vector-im/riot-web/pull/6313

, the plan is to write a few tests to make sure RoomTiles and RoomSublists are updating correctly in response to app state changing. To be clear, the following tests **should pass prior to the changes mentioned**.

The following should be tested (manually/automatically):
  1. receiving a message in an unread room causes it to transition to the "read" state;
  2. receiving a room state event for a room should update the respective view of the RoomTile, namely:
     - avatar;
     - name;
     - member event (in case the room name is "Alice, Bob and 2345 others";
  3. receiving a message in a room which is not at the top of a manually sorted RoomSubList;
  4. having a notification count > 0 should be displayed when we receive an event and the count is > 0;
  5. the notification count should be zeroed when we look at the room.

#### Automated test considerations:
1\. and 2. could probably be done with a RoomTile instance and a mocked js-sdk (room/client). 3. would require RoomListStore only, with the assumption that the RLS state is accurately rendered.

**Comment by lampholder** [comment]
https://docs.google.com/spreadsheets/d/1_EeVYIP5q8XGrpDF1dMjJkL1DoL-bFEy7Vcp5m_ecJg/edit?usp=sharing

**Comment by turt2live** [comment]
@lampholder what's the status of this one?

**Comment by lampholder** [comment]
Hah, my manual qa results from a year ago can probably safely be closed :P Thanks.
