### ISSUE TITLE
Logging in as "Username" instead of "username" returns weird, misleading error

### ISSUE THREAD

**Issue by altergui** [vector-im/riot-web#6318]
### Steps to reproduce

- Browse to https://chat.disroot.org/ using Firefox 52.6.0 on 32 bit linux (same with Firefox on OSX and Safari on OSX)
- input your username with an uppercase letter (if you're "maryjane", input "Maryjane")
- input your password
- click Sign in

possible expected results:

- simply log in, ignoring the case mismatch
OR
- get a specific error saying "Username incorrect. Note it's case sensitive"
OR
- get the standard "Incorrect username and/or password"

actual result:

- get a "modal" dialog saying "For security, this session has been signed out. Please sign in again", very much misleading.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 52.6.0 on 32 bit Debian Linux, also Firefox on OSX and Safari on OSX
- **URL**:  https://chat.disroot.org/

**Comment by altergui** [comment]
Can't reproduce the behaviour in https://riot.im/app/, so it's most likely specific to the disroot.org deployment scheme. Sorry for the noise, hope it might still be useful for future reference.

**Comment by enannos** [comment]
Is there a possibility to make riot ignore the upper/lower case?

**Comment by t3chguy** [comment]
It's not about riot, riot just sends it to synapse where usernames are case sensitive

**Comment by enannos** [comment]
Thank you for the quick reply. 
Is there a way to "transform" the username(on the login page) toLowerCase before we send it to synapse?

**Comment by t3chguy** [comment]
But then what if someone's username is uppercase? These exist.

**Comment by turt2live** [comment]
Please use #riot:matrix.org for support questions, or open a new issue if you believe there's a bug in Riot. Using a year old issue for questions is not ideal.

**Comment by enannos** [comment]
@turt2live you are right. This issue drives me just crazy for the last month.
@t3chguy We are using the matrix LDAP connector(we used to work with mxisd until the development stopped) to authenticate the users against our AD and for the uid we user the "sAMAccountName" which, as far as I know, is always lowercase

**Comment by t3chguy** [comment]
Yes but riot doesn't know that and shouldn't know that, it should be up to that connector
