### ISSUE TITLE
After exiting [m] Matrix HQ I was neither in nor out of the room

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#6320]
### Description

See https://github.com/vector-im/riot-ios/issues/1805
and https://matrix.to/#/!tDRGDwZwQnlkowsjsm:matrix.org/$15203172863855822hIdtS:matrix.org

### Steps to reproduce

For me, it seems to be intermittently but very frequently after the following:
- Entering the room [m] Matrix HQ (I haven't had it with any other room)
- Exiting this room by clicking the gear and ckicking the exit button ("Ruimte verlaten") in my Dutch version)
- Optionally forgetting the room by clicking the three dots to the right of the room name and clicking "X Forget" ("X Vergeten")
- Waiting till more messages are posted in [m] Matrix HQ
- Now te red indicator will show on the tray icon
- If the room hasn't been forgotten, "History" ("Historische" - misnamed in Dutch) will show the number of unread messages, and so will [m] Matrix HQ under that heading.
- When trying to enter the room the process takes forever - for more details see https://github.com/vector-im/riot-ios/issues/1805

Emptying the cache solves the problem for a moment, but soon after it happens again.

Describe how what happens differs from what you expected.

I expect not to be alerted of new messages in rooms I am not in, and even more so if I have forgotten that room.

Log: sent/not sent?    

I don't know where to find a log file.

![image](https://user-images.githubusercontent.com/12461597/37442518-c2f2fde4-2841-11e8-8177-dbc73f65185d.png)

### Version information

- **Platform**: web (in-browser) or desktop?

Desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y 

Ubuntu Linux 16.04.
Aptitude states "riot-web 0.13.5".  Does that make sense?  I have no idea where to find version information in the app itself.

**Comment by turt2live** [comment]
This sounds very much like a state reset which is badly timed. Now that the room has been replaced and is due for a proper upgrade, I suspect this problem has gone away.
