### ISSUE TITLE
Terrible experience joining #fractal-gtk:matrix.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6321]
Reproduction steps:

 * Go to Room Directory (for matrix.org)
 * Search for fractal 
 * Click on the room for 'Gtk+ Matrix.org client' (not the other one)
 * Peek into the room correctly! :)
 * Hit 'join' on the status bar at the top of the page
 * Your peeking view says 'matthew joined'
 * ...but nothing happens, and the status bar doesn't go away.
 * you switch away and back again
 * ...and see hundreds of membership events in the timeline from ancient history.  If you scroll up high enough you actually see the current timeline events for the room :/

**Comment by ara4n** [comment]
There's one special aspect here potentially: i've been in this room before, and /part'ed it a while back. So this is me re-joining it for the first time in at least 6 months.

**Comment by lampholder** [comment]
Joining as toml:matrix.org on /app was a little slow but worked fine:

Joining as isobelle.mtp on /develop was no slower, and I successfully entered the room, but it did render a tonne of membership events that I didn't see on /app - the earliest was from Oct 2017 (each membership event or group of events was grouped under it's date heading).

**Comment by lampholder** [comment]
...but joining as a brand new user was fine.

**Comment by ara4n** [comment]
just to be clear, i had two major fails:
 * The join didn't work; the room never transitioned from peeking into joined
 * The tonne of membership events between Oct 2017 & present data pushing the current timeline pages into the past.

**Comment by lampholder** [comment]
I've played around with a few more brand new/old test accounts joining this room.

Conclusions:
- on /app I have seen the status bar not going away (sometimes, not always)
- on /app I have _not_ seen the list of memberevents appearing out of order
- on /develop I have seen the status bar not going away (sometimes, not always)
- on /develop I _haev_ seen the list of memberevent appearing out of order (sometimes, not always)

**Comment by ara4n** [comment]
I'm finding it impossible to join HQ too on develop - clicking on "join room" on the preview pane just spins; never joins.

**Comment by lampholder** [comment]
We have a fix for this (@dbkr has the details)

**Comment by dbkr** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/630
