### ISSUE TITLE
I seem to get the 'For security, this session has been signed out. Please sign in again.' message every time I sign out now.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6326]
I _think_ this is on /app and /develop, though I should verify.

To reproduce:
- got to user settings
- click log out
- be logged out
- be told you've been signed out 'for security'

**Comment by turt2live** [comment]
Possibly related: https://github.com/vector-im/riot-web/issues/5874

otherwise a duplicate of https://github.com/vector-im/riot-web/issues/6054 ?

**Comment by lampholder** [comment]
I think your links might be the wrong way around, but I think you're right (inasmuch as I think #6054 might be related and #5874 is the dup).

Also it looks like I triaged #5874, apparently in some sort of triaging trance whereby I then forgot all the details of that issue.

Thanks :P

**Comment by turt2live** [comment]
Oops. Yea, I picked #6054 because I failed to read this issue's title (autocompleted out as in).
