### ISSUE TITLE
RoomSubList header notification count doesn't update when reading a room

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6334]
Following https://github.com/matrix-org/matrix-react-sdk/pull/1801/files, where individual room tiles listen for when their room is read, we now don't force update the entire RoomList when switching rooms.

This means we don't update the sub list header immediately when switching to a room so it might be stale for a small amount of time.

Solution would be to split the header out and make it listen for `on_room_read` and update it's own count. Bonus points for making a flux store that pushes state to both the room tiles and the headers (which would be in the shape of a map between roomId and notif. count).

**Comment by turt2live** [comment]
Fixed
