### ISSUE TITLE
BaseDialog-based components assume <kbd>Enter</kbd> on any tab-indexed item = affirmative 

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6336]
FTR <kbd>space</kbd> works as expected.
Actual:
 - tab-select any item 
 - hit <kbd>enter</kbd> 
 - positive action assumed intended

Expected: 
 - (for creating a room if "Advanced" is selected, it should open); 
 - if "Cancel" is selected, the dialog should be closed;
 - "X" is tab-index-able. This might only be an issue for some cases.

**Comment by lampholder** [comment]
It took me a few times to parse this - if I understand correctly, you're saying the <kbd>Enter</kbd> performs the 'affirmative' action of the dialogue, regardless of which form component is selected.

**Comment by lukebarnard1** [comment]
Yep.

**Comment by turt2live** [comment]
This looks to have gotten fixed in https://github.com/matrix-org/matrix-react-sdk/pull/1652
