### ISSUE TITLE
public rooms only seem to appear in public list once added to communities.

### ISSUE THREAD

**Issue by zorilya** [vector-im/riot-web#6344]
### Description

A room set to be publicly visible only appears in the rooms directory once furthered added to a community

### Steps to reproduce

- create a new room
- set room to be publicly listed on the server's room directory
- search for room in directory and see it isn't there
- add the same room to a community
- search for it again in the directory and find it

###Describe how what happens differs from what you expected.

I expected that regardless of a room being part of a community, if it was listed it would be visible in the public directory on the server.

### Version information

- **Platform**: both web and desktop (chrome and windows)

For the web app:

- **Browser**: Iron (chromium)
- **OS**: Windows
- **URL**: / riot.im/app /

For the desktop app:

- **OS**: Windows
- **Version**: most recent as of 17th March 2018 (currently matrix.org is not letting me connect so I can't tell)

**Comment by uhoreg** [comment]
Did you set an alias for your room?
