### ISSUE TITLE
Feature Suggestion: Local User Aliases (Real Names)

### ISSUE THREAD

**Issue by svoop** [vector-im/riot-web#6352]
With the growing number of users, it's getting difficult at times to tell who's behind a display name.

How about adding the ability to add a local user alias (e.g. on the user profile sidebar) and if set, use that alias to identify the user in the chat window etc.

For example: Instead of having "ufired" (full: ufired:matrix.org) displayed, you could locally use the display alias "Donald".

**Comment by turt2live** [comment]
This sounds like #3130

**Comment by svoop** [comment]
Isn't #3130 more about room names than user names?

**Comment by turt2live** [comment]
It links through to https://github.com/matrix-org/matrix-doc/issues/690 which describes both users and rooms.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-doc/issues/690
