### ISSUE TITLE
RoomTile badge not updated when RR received

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6357]
This was caused by the recent optimisations to RoomTiles (https://github.com/matrix-org/matrix-react-sdk/pull/1801)

**Comment by lukebarnard1** [comment]
The immediate fix for this is to make RoomTiles listen for read receipts.

Long term, we want to expose a matrix-js-sdk event that fires when the notification count for a room changes instead of making assumptions about the kind of events that will cause the count to update (as I did with https://github.com/matrix-org/matrix-react-sdk/pull/1801).

**Comment by turt2live** [comment]
Potentially related: #6010

**Comment by lukebarnard1** [comment]
@turt2live doubtful - this particular bug was most certainly introduced following RoomList optimisations.

**Comment by turt2live** [comment]
:( okay.

**Comment by lukebarnard1** [comment]
>The immediate fix for this is to make RoomTiles listen for read receipts.

This causes flickering because RoomList also listens to read receipts. Removing this has been declared invasive so we'll do a different fix: getting room notif count when the room tile is given new props.
