### ISSUE TITLE
Pills with no space between them don't ping.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6358]
### Description

![image](https://user-images.githubusercontent.com/1190097/37677645-3e1dfae8-2c41-11e8-870d-929447325617.png)

:(

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Dup of https://github.com/vector-im/riot-web/issues/5121
