### ISSUE TITLE
the download button on image preview seem to be broken in encrypted rooms

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6359]
Clicking on it opens a new tab with data:image/png;base64,iVBORw0KGgoAAAANSU.... -type URLs

**Comment by ara4n** [comment]
...but doesn't show the image, or download it.  it works from the download prompt in the timeline; it only breaks if you press the button on the lightbox.

**Comment by lampholder** [comment]
I can reproduce this on my mac (Chrome 65) but not on my ubuntu machine (Chrome 60 somehow).

I'll update Chrome on my ubuntu machine and see if that narrows it down to a chrome version change.

**Comment by lampholder** [comment]
Having upgraded to Chrome 65 on my ubuntu machine I can confirm that this bug now manifests there, too.

**Comment by lampholder** [comment]
Okay, multiple things might have been happening here. I think the problem I was seeing was actually a different one (though related) - opening a blob: url in a new tab is caught by my adblocker under Chrome 65 (where it didn't seem to be in Chrome 60).

So under Chrome 65 my experience in E2E rooms is now:
- Clicking the _↓ download whatever.jpg (size)_ link opens a blob:https//usercontent.riot.im/udiyaifdsuiafy URL in a new tab (and is blocked by Adblock Plus)
- Clicking the image itself opens it in a lightbox; clicking the [download] link in the lightbox opens a data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcetc... URL which renders as a blank page.

In contrast, in non-E2E rooms, clicking on the _↓ download whatever.jpg (size)_ or the button in the lightbox both just open in a new tab the https://../matrix/_media link (so, actually, both UX elements marked 'download' do not actually download anything).

**Comment by ara4n** [comment]
we changed to blobs so have a whole different set of problems \\o/
