### ISSUE TITLE
Palemoon browser: Scrolling in a channel does not work

### ISSUE THREAD

**Issue by sideeffect42** [vector-im/riot-web#6361]
### Description

Scrolling in a channel does not work

### Steps to reproduce

- Join a channel with more than a screen-height of messages
- Try to read the last message by scrolling down

Describe how what happens differs from what you expected.

I would expect to have a scrollbar that I can use to scroll down.
Adding "overflow: auto" to "div#mx_RoomView_body" helps.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Palemoon (Firefox)
- **OS**: Gentoo
- **URL**: riot.im/app

**Comment by mission712** [comment]
Riot is really broken in Palemoon. I suggest against trying to use it.

**Comment by sideeffect42** [comment]
@mission712 That is correct, and the reason why I opened this issue.

I can understand that things like calls do not work because WebRTC is not in such a good shape with Palemoon (I guess, I don't compile it in anyway).

But simple things like scrolling should work in every browser.

**Comment by MTRNord** [comment]
@sideeffect42 i think scrollbars like riot uses need modern css Features. That's why overflow is disabled too.

**Comment by lampholder** [comment]
Does scrolling not work at all? Or is it just the most recent message that is unreachable?

**Comment by sideeffect42** [comment]
@lampholder It depends. E.g. on the "start page" scrolling works just fine. It also works in some channels, while in others it does not (no scrolling at all).
When I switch to a channel where scrolling is broken, I also cannot switch the channel anymore without reloading the page.

Don't know if it helps, but the console mentions `TypeError: this.scrollbar is null` and `TypeError: e is null` a few times.

**Comment by lampholder** [comment]
The scrollbar issue could be gemini scrollbar/palemoon not playing nicely together (though that isn't backed up by it working on some rooms and not others, and there don't appear to have been any related issues filed on https://github.com/noeldelgado/gemini-scrollbar/).

We're doing some work in the scrollbar area (https://github.com/vector-im/riot-web/issues/6294) which might improve things (though I'm not super hopeful that the causes of these issues overlap).

**Comment by sideeffect42** [comment]
Not sure if this issue originates from Gemini at all.

To me it looks like something in the "initialisation of a channel" is broken and as Riot does not allow system scrollbars scrolling is broken.

**Comment by sideeffect42** [comment]
Scrolling has been working for me again in PaleMoon.
I consider this issue resolved.
