### ISSUE TITLE
inaccessible remote encrypted media gives 'Error decrypting image' instead of 'Error downloading image'

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#6362]
"somebody" broke federation on matrix.org such that media requests returned a 521, which synapse turrned into a 502.

For encrypted content, Riot then displayed "/!\ Error decrypting image" (with 'Unable to decrypt attachment:  Error: Mismatched SHA-256 digest' in the console') rather than a download error.

**Comment by uhoreg** [comment]
dup of https://github.com/vector-im/riot-web/issues/3892
