### ISSUE TITLE
We don't cache bust /sync (and presumably other APIs)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6365]
If nothing happens on a homeserver for >30s, the /sync request will respond with a sync token = the token we sent a request with. Apparently, this gets cached in a way that means we'll never get a newer /sync because the browser hits cache when we do the next request (with the same token).

So we should probably bust the cache on the /sync API, and presumably others (but this is probably worse because the failure mode is quite bad). 

It's a bit of an edge case because the common case is that the homeserver has changes to give to clients.

cc. @erikjohnston, @rxl881 (who discovered this)

**Comment by richvdh** [comment]
After further discussion, the conclusion was that we should fix this using cache-control headers from the server, rather than using cachebusters on the client (which are a bit ming).
