### ISSUE TITLE
Room list tag state change on drag and drop is glitchy.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6369]
Dragging roomtiles from one section to another results in their having the wrong tag.

**Comment by lampholder** [comment]
My starting setup was:

INVITES
(#) Test Room
FAVOURITES
(#) Matrix HQ
PEOPLE
(#) Riot-bot

I dragged _Matrix HQ_ from FAVOURITES to PEOPLE, then I waited for a bit, then _Matrix HQ_ ended up in ROOMS.

Further dragging and dropping caused similar unpredictable behaviour.

**Comment by lukebarnard1** [comment]
- So dragging Rooms -> People was broken: https://github.com/matrix-org/matrix-react-sdk/pull/1811
 - Dragging from FAVOURITES to PEOPLE has *always* resulted in the thing being put into ROOMS

**Comment by lampholder** [comment]
I've found another problem in a similar space (which maybe should be a separate bug but I'm putting it here for now):

If you're roomlist looks like this:
![selection_017](https://user-images.githubusercontent.com/1922197/37768235-cc4bd3e2-2dc4-11e8-9438-4891b114101b.png)

And you drag **Riot** onto the "You're not in any rooms yet!' landing rectangle, it gets stuck on the ROOMS header like this:
![selection_018](https://user-images.githubusercontent.com/1922197/37768244-d4a94024-2dc4-11e8-9465-6918e02124d3.png)

It fails with this error:
![selection_019](https://user-images.githubusercontent.com/1922197/37768249-d77446dc-2dc4-11e8-97ff-c362facfb985.png)

**Comment by lampholder** [comment]
Also I noticed that you can't drag into historical, but it turns out you can't do that on /app, either.

**Comment by lukebarnard1** [comment]
FTR: Same bug

**Comment by lampholder** [comment]
The room list is a mess of UX paradigms - four headings that look the same (five if you count invites) and they all work a little bit differently.

**INVITES** - No dragging; disappear after accepting/rejecting
**FAVOURITES** - Drag within the list to set order manually. Drag outside of list to change DM/not DM, Favourite/Not Favourite and Low Priority/Not Low Priority state.
**PEOPLE** - rooms end up here based upon unclear (to the user) heuristics. No dragging within list. Drag outside of list to change DM/not DM, Favourite/Not Favourite and Low Priority/Not Low Priority state. Ordered by most recent activity.
**ROOMS** & **LOW PRIORITY** - No dragging within list. Drag outside of list to change DM/not DM, Favourite/Not Favourite and Low Priority/Not Low Priority state. Ordered by activity.
**HISTORICAL** - No dragging of any sort, in or out.

Add to that that some transitions don't work - this is clearly an area that needs some attention :smile:

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8614
