### ISSUE TITLE
Room tile context menu gets stale

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6370]
- Click a room ellipsis context menu
- Set the room to 'LOW PRIORITY' (assuming it isn't already)
- See it move to LOW PRIORITY
- Click the ellipsis menu again
- See the 'LOW PRIORITY' marker is not set

**Comment by lampholder** [comment]
We know this is because the roomlist does an optimistic update but the context menu is not linked with the same store (so is stale).

**Comment by turt2live** [comment]
Semi-related (by subject matter): #3918

**Comment by turt2live** [comment]
Fixed magically in the redesign
