### ISSUE TITLE
unsupported browser warning in 0.14 is just a blank page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6372]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/%2415216794491408yPotH:kek.community

**Comment by t3chguy** [comment]
http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= is in logs

**Comment by t3chguy** [comment]
or from develop: `Unhandled rejection Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `CompatibilityPage`.`

**Comment by dbkr** [comment]
@t3chguy how did you repro this? I seems to work for me.

**Comment by turt2live** [comment]
Cannot reproduce to date.
