### ISSUE TITLE
Missing shims for IE11 functionality

### ISSUE THREAD

**Issue by walle303** [vector-im/riot-web#6373]
In v0.13.5 and probably earlier, riot-web does not work in IE11 at all without adding a few shims

To work at all: https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Polyfill
Couldn't tell if this one is absolutely needed or not: https://github.com/axemclion/IndexedDBShim
For encryption: https://github.com/vibornoff/webcrypto-shim

Adding these shims makes riot-web functional in IE11 sans the login screen which for some reason keeps its username/password/sign in button disabled, but should be fixable otherwise.

I'm aware IE11 is technically unsupported by riot, but it still has fairly high usage and riot should at least maintain some kind of baseline functionality where possible.

After using these shivs and logging in using a workaround, riot-web is functional, although has poor performance, which is probably to be expected.

IE11 version in question: 11.0.9600.18860

**Comment by lampholder** [comment]
According to http://gs.statcounter.com/browser-version-market-share IE 11 has ~2.6% of the browser market share (and I'm willing to bet a lot of them are not super likely to be using Riot even if it _did_ support their browser) :D 

I can't see a very compelling case to add code to support so small a segment of the market (whilst giving them a degraded user experience at the same time).

**Comment by nschonni** [comment]
The Canadian Government ended up going with Rocket Chat because of the lack of IE11 support. Everything else here was better, but that was a dealbreaker.
IE11 probably has pretty low traffic on stats-counter, but still is heavily used in the enterprise space

**Comment by nschonni** [comment]
Although FF is my preferred browser, it is also only a 1.5% ahead of IE11

**Comment by turt2live** [comment]
Governments not being able to use Riot does seem like a huge problem. We technically don't support IE or Edge, but should definitely support IE11 if we can.

**Comment by t3chguy** [comment]
We have now made a statement we do not support IE: https://github.com/vector-im/riot-web#riot

should this issue be closed?

**Comment by jryans** [comment]
At this moment in time, we do not plan to support IE 11. It's always possible that something may change in the future that leads us to a different decision, but for the moment, it is not planned, so I think it's reasonable to close this.
