### ISSUE TITLE
Corrupt layout after switching to a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6377]
I've been getting this an awful lot in the last week or so; I assume there's been some change to our CSS which makes it easier for Chrome to screw up the layout (or perhaps there's some incremental re-rendering going on which means it all goes wrong)?  Eitherway, it's really really fugly for a few 100ms before it fixes itself after changing to a room.

<img width="2032" alt="screen shot 2018-03-23 at 21 36 49" src="https://user-images.githubusercontent.com/1294269/37855923-ac7666d8-2ee9-11e8-9e63-0789aaed3cf3.png">

**Comment by ara4n** [comment]
THIS IS SO ANNOYING

I get it almost each and every time on my local copy >:(

<img width="1004" alt="screen shot 2018-05-24 at 18 30 17" src="https://user-images.githubusercontent.com/1294269/40501729-9f807fa0-5f80-11e8-8b5b-1292b688bc44.png">

It vanishes if you move the mouse over the screen, and it vanishes if you trigger CDT's inspector.

**Comment by yannicka** [comment]
For my part, I do not have the impression of having this problem, is it still relevant?

**Comment by t3chguy** [comment]
Assuming fixed
