### ISSUE TITLE
[UX] Shortcut for jumping between recent rooms

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#6384]
### Description

Sometime you jump from room to room and you want to go back to the previous room, but you don't remember which one it was. Having a shortcut for that would be a nice touch.

It's not a far fetched idea, Slack has them (Alt+Left/Right), that's why I miss them in Riot as well ;)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: All
- **Version**: 0.13.5

**Comment by t3chguy** [comment]
OS: All is incorrect
in Windows you can use the Mouse back button as you can in-browser

**Comment by MightyCreak** [comment]
what if you don't have a mouse back button? then all is still correct, isn't it?

**Comment by MTRNord** [comment]
@MightyCreak your Browsers back Button should work too (and therefor Also the Key combination of Your Browser)

**Comment by MightyCreak** [comment]
I'm on the desktop app, not in the browser.

**Comment by t3chguy** [comment]
Actually I misunderstood this issue. I thought it was like https://github.com/vector-im/riot-web/issues/301 but for any room not notifications only. This is more actually about visited order.

**Comment by jaywink** [comment]
`alt-left/right` seems to do this now, on desktop nightly at least? Can't see any mention of it and can't remember it working before :thinking: 

But it's fantastic :tada:

**Comment by t3chguy** [comment]
So yeah, on browsers use your browser shortcut (typically Alt-left/right)
on Windows & Linux riot-desktop also Alt-left/right
![image](https://user-images.githubusercontent.com/2403652/81159346-c8763f80-8f80-11ea-971a-d31d003fcc17.png)


On Mac it is Cmd-`[`/`]`

**Comment by colans** [comment]
@t3chguy How does one get to the Keyboard Shortcuts screen?  I couldn't find anything in Settings.

On the Linux desktop app, Alt & left or right does nothing.  I tried this with both Alt keys. (riot-web version: 1.5.3).

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/81186626-ee183e80-8faa-11ea-9e01-36aba4c2226b.png)

but you're on a really old version of riot. Latest in packages.riot.im is 1.6.0 (1.5.15 was before that)

**Comment by colans** [comment]
Looks like I was using a Debian repo that wasn't up-to-date, probably the OS one.  Seems to all work now (and `riot-web` was replaced by `riot-desktop`).  Thanks!
