### ISSUE TITLE
hitting enter after Ctrl-K should switch to the first result

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6391]

**Comment by lukebarnard1** [comment]
But how could you join? You're already joined if the list appears in the list, so would this be for invites?

**Comment by t3chguy** [comment]
@lukebarnard1 I think the meaning is Ctrl-K, filter, then Enter without having to first down-arrow
So if there is only one result from the filtering, default to it on Enter to jump to its room view

**Comment by lukebarnard1** [comment]
In that case, I think we could default to the first one at all times - Enter serves no other purpose anyway.

**Comment by t3chguy** [comment]
I agree, and I could have sworn I had an issue open for that but cannot find it so might have just moaned about it in riot-dev

**Comment by t3chguy** [comment]
this isn't actually a regression
