### ISSUE TITLE
memberlist has got stuck on a filtered view for another room

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#6393]
I think I did something like:
* filter member list
* switch room

it is now showing the filtered member list for the original room, even when I try to clear the filter or change room.

Also my console is FULL OF RED

**Comment by richvdh** [comment]
I did a shake of rage

**Comment by lukebarnard1** [comment]
@richvdh it seems the Real error has vanished into a sea of "React has gone wibbly" errors. 

I can't reproduce on /develop, even switching between the same rooms as shown in the logs. Any chance you could try reproing?

**Comment by richvdh** [comment]
yeah can't repro now :/

**Comment by richvdh** [comment]
rageshake is https://github.com/matrix-org/riot-web-rageshakes/issues/749

**Comment by lukebarnard1** [comment]
Closing this as I think it was fixed recently, possibly https://github.com/matrix-org/matrix-react-sdk/pull/1809/
