### ISSUE TITLE
Tab freezes/crashes trying to autocomplete in hq

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6394]
> btw, `@-autocompletion` is uber laggy in current /develop (chromium 65.0.3325.181). The whole tab freezes for several minutes(!) each time I type a character after `@`.

https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1522093844183mGHKc:intelfx.name

I've also reproduced this to the point of chrome giving me the sad folder of OOM.

**Comment by lampholder** [comment]
Is this the same as https://github.com/vector-im/riot-web/issues/6371 ?

**Comment by turt2live** [comment]
sure is, except for chrome too. 

(heh, I even reported that one...)
