### ISSUE TITLE
Support for 'anyone can join' communities

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6399]
This feature is distinct from 'knocking' to request access to a community.

This feature supports:
- community admins configuring their communities to allow anybody to join
- users to join said communities

**Comment by lampholder** [comment]
Community admin screen:
![desktop 1](https://user-images.githubusercontent.com/1922197/37967463-5907f6a6-31c3-11e8-994c-72ec0d069d8b.png)

- I would love to hear suggestions for better wording than 'Anyone'
- Also opportunistically redesigning the ambiguous 'Leave' button to read 'Leave this group'

**Comment by lampholder** [comment]
User joining screen:
![desktop](https://user-images.githubusercontent.com/1922197/37967501-7bbc5052-31c3-11e8-83b0-e1e7f2e0f637.png)

- Yes, the 'Join this group' is an a slightly aesthetically unpleasing location, but it mirrors the location for 'leave this group' when you view the group settings.
- There is a case for the _join_ button also to live behind group settings, but I think it would be favouring consistency over engagement (and hence a mistake).

**Comment by lampholder** [comment]
Sorry @turt2live - should just have added this stuff to #5242. Thanks for doing the tidying :)

**Comment by turt2live** [comment]
No problem. Would rather the information be somewhere than nowhere anyways :p

I am a bit concerned about the placement of the join rules though. It's under the warning saying it'll take 30 minutes to appear. Surely this is a change that won't take 30 minutes to reach other people? (hopefully)

**Comment by lampholder** [comment]
Hmm, you're right, it won't. I'll talk to @lukebarnard1 tomorrow about whether (due to the current impl) it might _appear_ like the rules hadn't changed for ~30 minutes (I don't know whether we fetch the group details afresh upon opening the group - I expect we do).

Certainly though it won't take 30 minutes for your config change actually to affect people's ability to join.

**Comment by lampholder** [comment]
Possible tiny improvement on the settings warning:
![desktop 3](https://user-images.githubusercontent.com/1922197/38025194-673e8368-327f-11e8-8a74-8c301ec9cd01.png)

I experimented with some other options (see https://www.figma.com/file/BC3S8Rhacn6oThrtpzeTgbZT/Join-anyone-can-join-community) - anything that radically repositioned the caveat text just looked even clunkier IMHO

**Comment by lampholder** [comment]
An alternative to the join button that more closely mirrors room join UX:

![desktop 1](https://user-images.githubusercontent.com/1922197/38025273-a7ed91b0-327f-11e8-9a55-44e586bb29f9.png)

s/looking at/something less stupid/

**Comment by turt2live** [comment]
@lampholder what do you think about this?
![image](https://user-images.githubusercontent.com/1190097/38036923-0c916350-3265-11e8-9807-8014c569462c.png)

(doesn't actually work, I just shoved a button into the dom)

**Comment by lampholder** [comment]
I think aesthetically it's an improvement, but I see a few problems:
- we only put 'save' buttons there today
- on a narrower monitor the button will overlap the title/description
- I'm fine with 'this' being absent from 'Join Community', though I think I would want to keep in 'Leave this community' and I like the symmertry between the two

Fwiw I'm not wild about the aesthetics of what I've proposed, but (for better or worse) it uses the existing UX language so I reckon we'll go with it for now :\

**Comment by ara4n** [comment]
fwiw i assumed we'd so something like @turt2live's example, but probably with the button at the bottom of the group description text rather than lost in the top bar. I'm not sure the preview bar is going to make much sense, plus it's going to push the important content down the page for no good reason (and is fiddlier to do than just slapping a button in the page)

**Comment by lukebarnard1** [comment]
To summarise:
 - [ ] "Join this community" button https://github.com/matrix-org/matrix-react-sdk/pull/1815
 - [ ] Change wording of leave button (https://github.com/matrix-org/matrix-react-sdk/pull/1815) and update delay warning.
 - [ ] Radio button in group settings.

**Comment by turt2live** [comment]
An added benefit to this would be to automatically enable flair when joining public communities. Anything to reduce the road to flair feels like an improvement to me.

**Comment by ara4n** [comment]
this happened, and #6507 is @turt2live's last suggestion.
