### ISSUE TITLE
Riot web only displays half of my communities in Settings (to be able to configure flair). 

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6401]
Filed by @AmandineLP via a rageshake.

@AmandineLP can you show me this IRL?

**Comment by AmandineLP** [comment]
It got replaced by https://github.com/matrix-org/riot-web-rageshakes/issues/760
I can definitely show it IRL.

**Comment by lukebarnard1** [comment]
Looking at this IRL, it seems that each gemini scrollbar in riot on macOS is both native *and* gemini. 

This *may* have something to do with the fact that the box overflows comically.

**Comment by turt2live** [comment]
I'm assuming that the issue is resolved by the tab being introduced. @AmandineLP if you continue to have issues, please re-open.
