### ISSUE TITLE
The desktop client prevents screensaver after audio/video call on MATE Linux

### ISSUE THREAD

**Issue by gradinaruvasile** [vector-im/riot-web#6402]
### Description

The desktop client prevents screensaver after audio/video call on MATE Linux. After a video call is finished the screensaver is still inhibited. This lasts until i restart the desktop client.

### Steps to reproduce

- Start a video call
- End a video call
- Wait for the screensaver timeout

The screensaver should kick in but it doesnt until the client is restarted.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop? Desktop
- **OS**: Debian Linux Testing 64 bit, MATE desktop
- **Version**: 0.13.5

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/11264
