### ISSUE TITLE
Upgrade path to React 16

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6410]
This afternoon, I took a random detour to get Riot working with React 16, for the sake of investigating how difficult this would be. I succeeded, but obviously the diff is huge, so we might not want to do this "right now". 

I did not manage to get the react-sdk tests working, primarily because matrix-react-test-utils needs similar treatment (being made compatible with React 16).

Steps to upgrade riot-web, matrix-react-sdk and matrix-react-test-utils:
 + Update various npm dependencies to most recent versions:
   - draft-js-export-html
   - draft-js-export-markdown
   - react
   - react-dom
   - react-gemini-scrollbar
 + Apply react-codemod JSCodeshifts on `/src` and `/test`
   - React-PropTypes-to-prop-types
     - will fail on trailing commas at the end of prop types
     - and where there is more than one "React.PropTypes" on a single line
   - class
     - Might render the box it's running on totally useless for a few minutes...
 + `s/react-addons-test-utils/react-dom\/test-utils/`
 + Fix cases where the React context API has changed(?)

**Comment by lampholder** [comment]
OOI was there an inspiration for this detour other than generally keeping framework use up to date?

**Comment by lukebarnard1** [comment]
My inspiration was primarily the number of times I've stared blankly at the logs when there's a bug that cause React to go wibbly and useless, requiring a refresh. This has been fixed in 16.

**Comment by akihikodaki** [comment]
I managed Riot work on React 16:
https://github.com/akihikodaki/riot-web/tree/react-16

Pull requests of dependent changes are open.

**Comment by Half-Shot** [comment]
Assuming that since the move to Slate, the work required to do this has changed?

**Comment by t3chguy** [comment]
Current split of work:
- [ ] Stop using React.PropTypes
- [ ] Update react-gemini-scrollbar to do the same: https://github.com/matrix-org/react-gemini-scrollbar/pull/1
- [ ] Either use the polyfill for createClass or transition to using ES classes

**Comment by turt2live** [comment]
> react-gemini-scrollbar

We actually want to kill this with fire, if it makes it easier.

**Comment by t3chguy** [comment]
Is there any plan for this :D?

**Comment by turt2live** [comment]
There is the plan of "kill it with fire" but the implications haven't been thought out I don't think. I have opened https://github.com/vector-im/riot-web/issues/10474 to track it though.

**Comment by turt2live** [comment]
I've blocked this pending a release (see https://github.com/vector-im/riot-web/pull/10480#pullrequestreview-285053367)

After that release, we should be good to go. Huge thanks to @t3chguy for taking this on!

**Comment by t3chguy** [comment]
In that case I'd really appreciate not letting it rot. Not letting things like React.createClass would be swell.

**Comment by turt2live** [comment]
Yup, it should be only a week or so - if it starts to get longer than that I already have reminders set to start screaming about the problem.

**Comment by turt2live** [comment]
see https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1568219990249171GhfVS:matrix.org?via=matrix.org&via=openintents.modular.im&via=vector.modular.im

We've decided to merge it to avoid delaying it, however to mitigate risk we're not merging react 16 features until after release (just in case there's some weird internal change in react 16 that breaks things). Should prevent it from bitrotting too much, and help make it possible for us to move forward.
