### ISSUE TITLE
Special characters in pill names cause escaping

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6412]
On /app: ![](https://t2l.io/_matrix/media/v1/download/matrix.org/VshrEeBACEVatpurcLdmcuyd) 

On /develop:
![](https://t2l.io/_matrix/media/v1/download/t2l.io/7caea5a27ce1763c885afe55e8a2a08a)

**Comment by grahamperrin** [comment]
Thanks for opening this issue for me. 

Hmm. I was not previously aware of #4984 but the symptoms above do seem to be a duplicate. 

I'm almost certain that there was (or is) a more recent issue that was limited to `\develop\`. Q4 2017, if I recall correctly. 

I'm _vaguely_ reminded of part(s) of  issue 4809, _RTE inserts spurious backslashes into URLs (including room aliases, etc) in code blocks_ … I'll keep looking …

**Comment by turt2live** [comment]
This does look like a duplicate of https://github.com/vector-im/riot-web/issues/4984, so I think it's best to fork over to there.
