### ISSUE TITLE
Exec must be without quotes in riot-web.desktop

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#6421]
I'm using riot-web from https://riot.im/packages/debian
It's impossible to run it from menu, as ```Exec="/opt/Riot/riot-web"```
Must be without quotes: ```Exec=/opt/Riot/riot-web```

**Comment by t3chguy** [comment]
Iirc that file is generated by electron-builder so worth opening an issue there

**Comment by c-e-p-x-u-o** [comment]
The workaround is ```% cp /usr/share/applications/riot-web.desktop .local/share/applications/``` and remove quotes.

**Comment by 532910** [comment]
Should be fixed in 21.0.1
https://github.com/electron-userland/electron-builder/issues/2759#event-2433766694

**Comment by t3chguy** [comment]
This should just be a case of bumping the electron-builder dependency which will need to be done soon for the sandbox workaround once that is fixed upstream

**Comment by jryans** [comment]
I have confirmed this is indeed fixed by upgrading `electron-builder`.

**Comment by 532910** [comment]
fixed in riot-web-1.4.2 (may be earlier) debian package
thank you!
