### ISSUE TITLE
issue with editing of a single messages with more than 10 lines in riot-web on Linux

### ISSUE THREAD

**Issue by git-minix** [vector-im/riot-web#6425]
### Description

If longer messages (larger than the edit windows) are written with Riot-Web on Debian 9.4 and Mint Linux, the scrolling will not work correctly and sometimes the content of the previous message will be merged into the new message.

### Steps to reproduce
- go in a room and write a message like "this is a test - line #1" with 15 lines
- do not use CR after each line, use SHIFT CR or copy the message via Copy&Paste form a text file
- use the cursor keys to move from the top to the bottom in the edit window
- try to edit the message in different lines 

The editing of such messages does not work reliable. 
 
### Version information

Testet with Debian 9.4 and the riot-web package 0.13.5
Testted witt Linux Mint 18.3 Sylvia and the riot-web package 0.13.5

from: deb https://riot.im/packages/debian/ stretch main

- **Platform**: desktop
- **OS**: Debian 9.4 and  Linux Mint 18.3 Sylvia
- **Version**: 0.13.5

**Comment by lampholder** [comment]
I wasn't able to reproduce this on 0.13.5 running on my ubuntu machine, though I think under different circumstances the RTE can get into a very confused (but difficult to reliably reproduce) state.

**Comment by ara4n** [comment]
i've seen this a few times under OSX.

**Comment by ara4n** [comment]
fixed by #1890, hopefully.
