### ISSUE TITLE
integrations suggested by homeserver

### ISSUE THREAD

**Issue by ZerataX** [vector-im/riot-web#6430]
### Description

I think it would be very helpful to allow riot to get integrations suggested by the homeserver, like the type of bridges supported by the homeserver. currently always using the matrix.org integrations is kinda annoying when I would like to supply my own alternatives, e.g. my own matrix <-> irc bridge.

Of course you could always ship your own riot-web/mobile/desktop, but in most cases I would assume people would prefer to just use the default. even neater would be, to suggest an entire integration manager so you could point it to e.g. https://github.com/turt2live/matrix-dimension 

If nothing is suggested it should still default back to matrix.org integrations.

so something similar to https://github.com/vector-im/riot-web/issues/4081#issuecomment-305005166

**Comment by MTRNord** [comment]
I think the .well-known proposal by @maxidor is able to handle exactly this

**Comment by maxidor** [comment]
Indeed, such extensions in it was one of the long term enhancements I had in mind, both for the integration manager and for informing the client about bridges protocols (even tho that should be done at the protocol level I think)

**Comment by ZerataX** [comment]
I assume you're referring to https://github.com/kamax-io/matrix-java-sdk/issues/23 or more specifically this [proposal](https://docs.google.com/document/d/1vF-uWlUYmf1Xo161m871H1upJbwiIPeikWGWzaE_lrU/edit#heading=h.wbm0zzzcw8ii)

This looks very promising and would exactly fullfill my usecase.

**Comment by maxidor** [comment]
@ZerataX yes!

**Comment by ZerataX** [comment]
I guess I can close this then, since it should be mostly addressed with https://github.com/matrix-org/matrix-doc/issues/433

**Comment by turt2live** [comment]
I'd recommend keeping it open so it can actually be implemented.

**Comment by turt2live** [comment]
we ended up implementing this - see https://github.com/matrix-org/matrix-doc/pull/1957 for details on how it works.

**Comment by jittygitty** [comment]
What's the status of this, have maintainers addressed the issue? Is there already a way to change integrations manager server?
I was quite shocked to discover that current one is hard-coded to scalar.vector.im and it isn't even open-source. https://github.com/vector-im/element-meta/issues/260
