### ISSUE TITLE
how to force firefox to have riot-web username and password stored in its database. 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#6431]
I am on Debian testing (fully updated) - 

```
$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
~$ apt-show-versions -a riot-web
riot-web:amd64 0.13.5 install ok installed
riot-web:amd64 0.13.5 stretch riot.im
No unstable version
No experimental version
riot-web:amd64/stretch 0.13.5 uptodate
```

riot was installed via -

```
$ cat /etc/apt/sources.list | grep riot
	deb https://riot.im/packages/debian/ stretch main
```

```
~$ apt-show-versions -a firefox-esr
firefox-esr:amd64 52.7.3esr-1 install ok installed
firefox-esr:amd64 52.7.3esr-1 buster   cdn-fastly.deb.debian.org
firefox-esr:amd64 52.7.3esr-1 unstable cdn-fastly.deb.debian.org
No experimental version
firefox-esr:amd64/buster 52.7.3esr-1 uptodate
```

Now as per http://kb.mozillazine.org/Profile_folder_-_Firefox the username and password should be stored in sigons.sqlite followed with key3.db but I never get the riot username and password in firefox's database ever. 

How can I make sure that firefox keeps the username and password in its sqlite database ?

**Comment by aaronraimist** [comment]
Sorry I don't understand. Are you accessing Riot using Firefox at riot.im or are you using the desktop app (not using Firefox)? If you are using the desktop app you installed from debian then I don't see where Firefox comes into the situation or why it would ever store your password.

**Comment by shirishag75** [comment]
I am using riot-web, not using firefox browser.

**Comment by aaronraimist** [comment]
Please go ahead and close this issue after our discussion on #riot. I think we are on the same page.
