### ISSUE TITLE
avoid double negatives 

### ISSUE THREAD

**Issue by ZerataX** [vector-im/riot-web#6435]
## Description

With double negative I'm addressing radio boxes that have a negative description: 
- [ ] Disable X

which would in this state enable X

instead of either:
- [x] X 
- [x] Enable X

Currently these aren't just inconsistent, but generally more confusing and easy to misread, especially in german loc the negative particle is often at the end of the sentence.

### Steps to reproduce

- open the settings page

Currently the options on the settings page often like to use a negative formulation like:
`Disable inline URL previews by default`
Which leads to user confusion (at least for me and my friends) since most other options use a positive phrase like:
`Enable automatic language detection for syntax highlighting`

Ideally all radio boxes should enable a function never disable and have consistent phrasing.

![enable-disable](https://user-images.githubusercontent.com/5024958/38215091-ea70b198-36c6-11e8-9a7b-0ce27ba90bb4.png)

### Version information

This seems to be consistent across all platforms in english and german.

**Comment by turt2live** [comment]
related: #5476 

ftr: this should be easy(ish) to fix with granular settings. All it should be is a label change and an interpreter in the various levels.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2504
