### ISSUE TITLE
Stickerpicker doesn't load stickers during scrolling, only once scrolling stops

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6443]
This means you can't scroll through the list of stickers to find the one you're looking for, as whilst you scroll, the images don't update and you only see placeholders.  You have to actively release the mouse and stop scrolling to let the images load, which is quite unintuitive.  Instead, i'd suggest (ratelimitedly) lazyloading in images whilst you scroll - or at least let them load when you pause scrolling.

**Comment by Cadair** [comment]
I appear to be unable to reproduce this on Firefox (while clicking and dragging on the scroll bar)

**Comment by dali99** [comment]
Can't reproduce on firefox either, scrolling with the scrollwheel and scrolling with by dragging bar. It loads really slowly though (which is odd seeing as the images are cached and load with 0ms delay according to FF network analysis) so it sort of looks like it doesn't load.

**Comment by lampholder** [comment]
I can't currently verify this due to stickerpack UX being otherwise broken.

@ara4n @rxl881 - is this a blocker for sticker packs going live?

**Comment by rxl881** [comment]
It shouldn't be a blocker. Once the "persistent context menu" for the sticker picker has been implemented the initially visible stickers will be loaded (while the contextual menu is hidden) on initial riot load (ready for when it is made visible).

We may choose to rate limit pre-loading of all other (non-visible) sticker thumbnails, which will be trivial once we're at that stage, but it's certainly not a blocker on release, IMHO.

**Comment by rxl881** [comment]
This should now be fixed. Stickers are now lazy-loaded (rate-limited) in the background once the sticker picker has initially been added to the DOM (e.g. after first opening), regardless of whether stickers are visible or not.
