### ISSUE TITLE
Reports of trying to register but every username entered is invalid

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6456]
I assume this is the ILAG path somehow getting stuck after the user tries to specify an existing or invalid-character username.  I tried to reproduce it on the normal registration path and it was okay.

**Comment by ara4n** [comment]
My guess is that this is due to the horrid case sensitivity feedback, which is very cryptic in terms of complaining about the capital letter.

<img width="587" alt="screen shot 2018-04-05 at 21 29 08" src="https://user-images.githubusercontent.com/1294269/38390183-70e8df72-3918-11e8-8a15-570dd3d42dcb.png">

This is then a dup of https://github.com/vector-im/riot-web/issues/5833 but would be good to confirm.

**Comment by lukebarnard1** [comment]
Yep, confirmed this is a dup of #5833
