### ISSUE TITLE
Go to a certain date in room history

### ISSUE THREAD

**Issue by Cenness** [vector-im/riot-web#6460]
### Description

Would be nice to have option to scroll up to a certain date in history, i.e user click on date, calendar pops up, user chooses a date, room frame updates to that date or previous if chosen is not available.

### Steps to reproduce
N/A

### Version information
N/A

**Comment by MurzNN** [comment]
Related to this https://github.com/matrix-org/matrix-doc/issues/969 API feature request

**Comment by aaronraimist** [comment]
Duplicate of #1606 (upvote that)
