### ISSUE TITLE
Images sometimes larger than the width of the page

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#6462]
### Description

When receiving images, they are sometimes wider than the message section, causing weird scrolling

### Steps to reproduce

- Send e.g. a screenshot
- view in riot-web on small-ish resolution

I would expect images to have a max width that fits within the message section

Log: not sent

![image](https://user-images.githubusercontent.com/5447747/38423774-2b5844c4-39af-11e8-99f2-11220714862f.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox nighly
- **OS**: Fedora 27?
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Yes I can confirm this. The weird thing is when I scroll back to old images, sometimes they display normally and sometimes they display way to large which seems to cause huge performance issues.

Firefox on Mac

**Comment by lampholder** [comment]
I think this is a dup of https://github.com/vector-im/riot-web/issues/6492
