### ISSUE TITLE
Hovering over images in E2E room with long history causes 100% CPU usage of Firefox process

### ISSUE THREAD

**Issue by jtl999** [vector-im/riot-web#6467]
### Description

In a E2E room with a friend that has long history, hovering over thumbnails of images I send them freezes Firefox and causes 100% CPU of the `firefox` process

### Steps to reproduce

- Have room with long history (I tried a new E2E room with a dummy account with no history and was unable to reproduce)
-  Send images 
-  Hover over the image preview thumbnail
-  firefox process will have 100% CPU usage

I also tried the same with Riot Desktop on my OS X machine (10.11.6) and was unable to reproduce

![](https://i.imgur.com/GtUVeho.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 59.0.2
- **OS**: Void Linux
- **URL**: riot.im/app

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/2866 sadly.
