### ISSUE TITLE
[website] change instructions for adding .deb repository key

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#6470]
The apt-key man page recommends putting keyfiles directly in `/etc/apt/trusted.gpg.d` instead of using `apt-key add`, so the desktop install instructions should tell users to use something like `sudo wget -O /etc/apt/trusted.gpg.d/riot.asc https://riot.iom/packages/debian/repo-key.asc` instead of `curl -L https://riot.im/packages/debian/repo-key.asc | sudo apt-key add -`.  As pointed out by sergio in https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1523209724748581QaXXX:matrix.org

**Comment by richvdh** [comment]
[my apt-key manpage doesn't recommend that, and surely it's better to avoid running wget as root?]

**Comment by c-e-p-x-u-o** [comment]
Could you explain how does wget as root relates with problem?
Do not run wget as root! Run wget as user and then run mv as root!

**Comment by c-e-p-x-u-o** [comment]
Update to Stretch! And read the man!
https://manpages.debian.org/stretch/apt/apt-key.8.en.html

**Comment by lampholder** [comment]
Dunno what to do with this one :)
Our docs should strive to give clear, unambiguously good advice, but it's not clear to me whether we're falling short of that here.

**Comment by c-e-p-x-u-o** [comment]
What is unclear or ambiguously with
```
$ sudo wget -O /etc/apt/trusted.gpg.d/riot.asc https://riot.im/packages/debian/repo-key.asc
```
or
```
$ wget -O /tmp/riot.asc https://riot.im/packages/debian/repo-key.asc
$ sudo cp /tmp/riot.asc /etc/apt/trusted.gpg.d/riot.asc
```
?

**Comment by c-e-p-x-u-o** [comment]
```$ wget -O - https://riot.im/packages/debian/repo-key.asc | sudo tee /etc/apt/trusted.gpg.d/riot.asc```

**Comment by c-e-p-x-u-o** [comment]
```$ curl https://riot.im/packages/debian/repo-key.asc | sudo tee /etc/apt/trusted.gpg.d/riot.asc```

**Comment by c-e-p-x-u-o** [comment]
```$ curl https://riot.im/packages/debian/repo-key.asc | sudo tee /etc/apt/trusted.gpg.d/riot.asc```

**Comment by c-e-p-x-u-o** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895855
So the Debian Administrator's Handbook also says to use separate file and site will be fixed.

**Comment by uhoreg** [comment]
> why does it matter?

My understanding is that it makes management easier, in that if you want to later remove the key, it's just an `rm` statement, rather than trying to figure out the key ID and then issuing the proper `apt-key del` command..

Anyways, there is another suggestion for managing apt keys, documented at https://wiki.debian.org/DebianRepository/UseThirdParty, which makes apt only trust the riot.im key for signing the riot.im repository, rather for signing every repository on the system.  One issue with recommending that method, though, is that apt in Ubuntu trusty and Debian jessie don't seem to support the `signed-by` tag, so it will not work on those systems.  So if we want to go with those instructions, we would either need to provide different instructions depending on what distribution users are on, or drop support for Ubuntu trusty and Debian jessie.

**Comment by richvdh** [comment]
https://wiki.debian.org/DebianRepository/UseThirdParty says a lot of things, but I think that most of them seem to be recommendations for things to do *in addition* to installing the keys rather than alternatives?

**Comment by uhoreg** [comment]
Yes.  The most relevant part of that page with respect to the archive signing key is that it recommends putting the key into a location that *isn't* automatically picked up by apt-secure, and specifically annotating the `deb` line with the location to the key.

**Comment by uhoreg** [comment]
With the new signing keys, and repo location:

```
sudo wget -O /usr/share/keyrings/matrix-riot-im.gpg https://packages.riot.im/debian/repo-key.gpg
sudo sh -c "echo 'deb [signed-by=/usr/share/keyrings/matrix-riot-im.gpg] https://packages.riot.im/debian/ bionic main' > /etc/apt/sources.list.d/matrix-riot-im.list"
```

**Comment by 532910** [comment]
Users must never put anything in `/usr` except `/usr/local`.
`sudo wget -O /etc/apt/trusted.gpg.d ...`

**Comment by 532910** [comment]
I'd prefer to use armored file:
```
sudo wget -O /etc/apt/trusted.gpg.d/riot.asc https://packages.riot.im/debian/repo-key.asc
```

**Comment by uhoreg** [comment]
The instructions from https://github.com/vector-im/riot-web/issues/6470#issuecomment-483695491 are based on https://wiki.debian.org/DebianRepository/UseThirdParty which recommends *not* putting things in `/etc/apt/trusted.gpg.d`, as that causes apt to cause that key to be trusted to sign all repositories.

**Comment by 532910** [comment]
@uhoreg thank you for explanation!

Should be closed, right?
