### ISSUE TITLE
FB are no longer supporting Draft.js; perhaps we should switch to Slate.js or similar

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6477]
https://github.com/facebook/draft-js/issues/1312#issuecomment-360500901

->

http://slatejs.org/#/rich-text looks really nice

**Comment by lukebarnard1** [comment]
Slate does look very nice. I don't think it supports Entities like draftjs does, but looking at it, it'd be possible to write a plugin for those sorts of things (if someone hasn't already).

**Comment by ara4n** [comment]
fixes #4708 already for instance

**Comment by ara4n** [comment]
done.

**Comment by aliplutus** [comment]
what, why? draftjs still work very fine
