### ISSUE TITLE
Permissions are broken for embedded jitsi with no obvious way to fix

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6481]
![image](https://user-images.githubusercontent.com/1294269/38562394-5e8c81fe-3cd2-11e8-85a0-137586200190.png)

**Comment by bneiluj** [comment]
That's correct. 

Also, after enabling the in google settings the audio for the specific domain, the page has to be refreshed.

**Comment by rxl881** [comment]
I believe that this was due to an iframe permissions change that was introduced in Chrome 65. This should already be fixed on /develop and should be fixed on /app when a new riot release is performed (hopefully later today).

**Comment by rxl881** [comment]
FTR the original issue for this was https://github.com/vector-im/riot-web/issues/6182 and was fixed in https://github.com/matrix-org/matrix-react-sdk/pull/1766

**Comment by ara4n** [comment]
sorry for crankness on this; confirmed fixed on 0.14
