### ISSUE TITLE
Ability to explicitly re-mark messages as unread

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6482]
So you can use the 'jump to unread messages' to go back and find them earlier.  Useful if you accidentally scroll past a bunch of stuff but want to undo your 'reading' action.  In practice, I strongly suspect that bookmarking messages by starring them would be a more intuitive UX, especially as our 'Jump to first unread message' UX is very hard to use currently, but just as an email client has 'mark email as unread' which can sometimes be very useful, perhaps we should provide the same too.  In fact, perhaps we should use the email 'read' model to track which messages have been read and which haven't been...

**Comment by t3chguy** [comment]
> perhaps we should use the email 'read' model to track which messages have been read and which haven't been...

For both RM and RR?

**Comment by turt2live** [comment]
Related/possible dupes:
* https://github.com/vector-im/riot-web/issues/4586
* https://github.com/vector-im/riot-web/issues/4406
* https://github.com/vector-im/riot-web/issues/2452
* https://github.com/vector-im/riot-web/issues/6386
* https://github.com/vector-im/riot-web/issues/2938

**Comment by ara4n** [comment]
huh, yeah, dup https://github.com/vector-im/riot-web/issues/4406. hadn't seen that one before.
