### ISSUE TITLE
community sidebar

### ISSUE THREAD

**Issue by yogsototh** [vector-im/riot-web#6491]
### Description

The latest riot update added a left sidebar for communities.
For me it is empty I'd like to remove it. I couldn't. I had to tweak the CSS using developer tools.

So either there is a way to hide it and something should be done to discover how.
Or we can't remove that lost space and for me this is a bug that should be fixed.

### Steps to reproduce

Launch Riot

### Version information

- **Platform**: desktop
- **OS**: macOS
- **Version**: 0.14.0

**Comment by turt2live** [comment]
There should be a checkbox in your user settings:
![image](https://user-images.githubusercontent.com/1190097/38628310-4aba0a1a-3d6e-11e8-96d7-33231a7478d6.png)

**Comment by yogsototh** [comment]
Ah yes thanks! I really did't see it.

**Comment by lukebarnard1** [comment]
@yogsototh asking in #riot:matrix.org is perfectly acceptable.
