### ISSUE TITLE
Images in e2e rooms on /app expand to fill the whole width until you resize the screen, and then resize correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6492]
https://youtu.be/dzy4sQYH4gY shows the fail

**Comment by turt2live** [comment]
Seems like the opposite of https://github.com/vector-im/riot-web/issues/5861 annoyingly (which is still an issue)

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1865
