### ISSUE TITLE
using dark default_theme in config.json not working

### ISSUE THREAD

**Issue by skylord123** [vector-im/riot-web#6499]
### Description

I tried to set the default theme to dark for my riot instance but it keeps using the light theme. I thought this was related to #5623 but it looks like it is a new issue.

Here is my domain I am using to test this: https://chat.skylar.tech (so you can also verify my setup is correct).

### Steps to reproduce

- Set theme to `dark` in `config.json`
- Load your instance and you will see it is still using the default `light` theme.

You would expect it to start using the dark theme but that is not the case.

### Version information

I just got this setup this morning on a docker container. So it is running the latest as far as I am aware. The riot version just says "unknown".

**Comment by skylord123** [comment]
I tested this using incognito and clearing my cache to make sure my user settings wouldn't mess with it.

**Comment by skylord123** [comment]
Also, I would expect this to set the default for the user to the dark theme if they register via the site. But if they login then use the user's settin (this way if the user registers they don't go back to the light theme).

Would like to confirm this after the fix.

**Comment by skylord123** [comment]
This looks like it is working correctly now. @ara4n does it load correctly for you? If so I will close it.

**Comment by turt2live** [comment]
I think this was accidentally fixed alongside https://github.com/vector-im/riot-web/issues/6424 - @skylord123 are you still seeing issues on the latest release?

**Comment by skylord123** [comment]
Just tested by creating a new guest user in incognito on my home server and it applied the dark theme before the user registered and kept it after the registration.

So this is fixed. What a nice little accident ;)
