### ISSUE TITLE
E2e room content takes 10+ seconds to load after refresh

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6503]
Refreshing Riot Web in Chrome then going to an e2e room, the timeline is blank for 10+ seconds, without any sign whatsoever that stuff is happening. Then suddenly messages start to load. Unsure when it started (and this might be a duplicate) but really annoying and ugly.

Version:
![image](https://user-images.githubusercontent.com/8582858/38670166-f037a6ec-3e3f-11e8-8f19-c38346247561.png)

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/6379
