### ISSUE TITLE
Search to show all messages from a given user.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6508]
I thought we had a bug for this but i can't find it.

It'd be a no-brainer to provide a search result which shows all the messages said by a given user (e.g. yourself), searching across all rooms.  The current API should even support it; just needs to be exposed in the UI.

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/4752 ?

**Comment by lampholder** [comment]
Yeah, that looks like #4752 to me.
