### ISSUE TITLE
Doesn't quit by close window action.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-web#6511]
When I close riot window it doesn't quit really. Only Ctrl-Q quits riot or from menu.

I have no system tray, but I'v specially launched it for for the test: no systray icon is showed.
And no ability to disable it.

Possible it's a dup for #3133.

riot-web 0.14.0 https://riot.im/packages/debian sid/main amd64
and many versions before

**Comment by dkasak** [comment]
There should probably be a way of closing Riot Desktop from the GUI even if there is non systray.

**Comment by c-e-p-x-u-o** [comment]
There is way to close it: <Alt> (menu opens) File -> Quit.

**Comment by c-e-p-x-u-o** [comment]
I'm using Enlightenment. But systray icon is not shown in it's system tray.

**Comment by lampholder** [comment]
This is mostly a dup of https://github.com/vector-im/riot-web/issues/4628 - bumping the priority there to reflect the increased interest (and my increased awareness of the importance of the electron client since I filed that bug in July '17)
