### ISSUE TITLE
Adding a room by alias fails (if you're not already joined to that room)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6514]
And why is it asking me for a room id(?!)

<img width="775" alt="screen shot 2018-04-13 at 02 06 08" src="https://user-images.githubusercontent.com/1294269/38711724-59bd6f6e-3ebf-11e8-99b2-8a8960e47a60.png">

**Comment by lampholder** [comment]
We shouldn't ask for a room id - room id should be an accepted-but-not-prompted-for input.

**Comment by aaronraimist** [comment]
Duplicate of #5548
