### ISSUE TITLE
emoji to emotes parsing is weird

### ISSUE THREAD

**Issue by ZerataX** [vector-im/riot-web#6522]
### Description

Currently the way emojis are being replaced with the images for emojione is very unsatisfying.

It seems that only emojis created before Unicode 10 are being replaced using the 2.2 version of  emojione.
Furthermore vs15 is being ignored.

### Steps to reproduce
Sending an orange heart 🧡  will fall back to system default instead of the expected emojione image. 
Meaning any phone below android 8 or ios11 will not display anything
and will also look inconsistent compared to e.g. purple heart :purple_heart: 

If I send ❤︎ (U+2764 ❤  + U+FE0E VARIATION SELECTOR-15) it will be displayed as the emojione 2.2 version of the red heart  :heart: emoji instead of the Heavy Black Heart ❤︎ pictogram.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Arch Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
I think this is effectively solved by https://github.com/vector-im/riot-web/issues/9281 because emojione won't interfere for much longer.

**Comment by ZerataX** [comment]
vs15 is btw still being ignored fwiw
