### ISSUE TITLE
Can upload files with the settings open

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6524]
### Description

![image](https://user-images.githubusercontent.com/1190097/38773686-2a05d1ce-4010-11e8-959b-d7cfc4210fff.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Hmm, on ubuntu chrome dragging onto the app when viewing settings just opened the image in chrome.

From the screenshot it looks like you got the 'drop file here...' prompt. Are you saying that it's a bug that you got the prompt (I think it is) or a bug that you can't upload a file when the settings panel is open?

**Comment by turt2live** [comment]
@lampholder bug that I could upload a file (and it went to the room)

For reference, I had the Windows file open dialog open to change the room avatar and was seeing if I could cheat by dragging an image onto the file open dialog. Answer: cannot cheat.

**Comment by turt2live** [comment]
@lampholder was the above able to answer your question?

**Comment by lampholder** [comment]
Oh yeah!

The Windows file open dialog for the room avatar change is actually crucial as far as I can tell - for whatever magical reason you can't drop your file on the room when settings is open otherwise. Does that match your experience?

**Comment by turt2live** [comment]
Fixed by magic settings
