### ISSUE TITLE
Start a chat dialog misleading

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#6541]
If you click Start Chat in the start a chat dialog without a target selected it spews a message: `Try using one of the following valid address types: Matrix ID, Matrix Room ID, email address.`. Room ID is not actually supported in this dialog

**Comment by networkinterfacecontroller** [comment]
This also displays when inviting someone to a room if you hit tab with nothing typed

**Comment by turt2live** [comment]
This got fixed.
