### ISSUE TITLE
Emails of invited members are still showing up under the "Invited" area in a room even after that person has created an account and joined.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6549]
From a rageshake

**Comment by ara4n** [comment]
this should work - it's the whole concept of 3rd party invites.

however, if you invite twice or something perhaps one of them gets stuck?

**Comment by turt2live** [comment]
I swear I've seen this recently, but having tested about 16 times I can't reproduce it. If it comes up again, or someone has reproduction steps, please reopen.
