### ISSUE TITLE
Pills whose displaynames begin with / are interpreted as commands

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6551]
Despite you tab-mentioning a user whose displayname begins with / to wrap it in a pill, it still gets interpretted by the composer as a slash command.  This lends itself to abuse.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1890

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1890 indeed
