### ISSUE TITLE
Forgetting a room randomly changes your selected room

### ISSUE THREAD

**Issue by networkinterfacecontroller** [vector-im/riot-web#6555]
### Description

When forgetting a room from the historical section, one of your currently open chats (not from historical) is randomly selected as the active window

### Steps to reproduce

-  click menu next to room you have left that is in historical
- select forget
- watch madness ensue 

Expected behavior would be for whatever your current active room is to remain your active room

Log: no log sent   

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 0.14.1

**Comment by uhoreg** [comment]
Thanks for your report.  This has previously been reported as #2037, so I'm closing this issue.  Please feel free to follow and/or upvote the other issue.
