### ISSUE TITLE
segmentation fault on image download

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#6556]
Segmentation fault trying to download any image from the specific e2e-encrypted direct chat 

dmesg
```
riot-web: segfault at c9 ip 00000000037c9668 sp 00007ffe5aec92b0 error 4 in riot-web[400000+466d000]
```

riot-web  0.14.1https://riot.im/packages/debian sid/main amd64

**Comment by uhoreg** [comment]
Since riot is written in JavaScript, the segfault is probably due to electron, and given the age of this issue, and the progress made in electron, I doubt this is an issue any more, so I'm closing this.

**Comment by 532910** [comment]
Awesome!
