### ISSUE TITLE
Disable Communites Filter Panel doesn't seem to work any more

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6561]
Enabling the setting doesn't remove the communities filter panel.

It still doesn't take effect even after refreshing the page.

**Comment by lampholder** [comment]
Ugh, this is somehow intermittent.

**Comment by lukebarnard1** [comment]
I can't reproduce this. Note that you do have to close settings for the setting to take effect.

**Comment by CR0CKER** [comment]
Same here. The preferences setting shows no effect in a freshly installed Riot desktop app on MacOS.

**Comment by t3chguy** [comment]
Duplicate of fixed https://github.com/vector-im/riot-web/issues/8418
