### ISSUE TITLE
'Deactivate Account' is 'Delete Account' in french

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6567]
> by the way, in french it says delete my account not deactivate my account

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15241720662372825Mwiyk:matrix.org

**Comment by valetdepik** [comment]
Solved.

**Comment by turt2live** [comment]
in you I shall trust. It should be fixed in the next version (when they merge weblate into the project).
