### ISSUE TITLE
Update README.md to reflect status of the skinning abstraction 

### ISSUE THREAD

**Issue by SteveALee** [vector-im/riot-web#6570]
> WARNING: As of July 2016, the skinning abstraction is broken due to rapid development of matrix-react-sdk to meet the needs of Riot (codenamed Vector), the first app to be built on top of the SDK

Is there an update on this as of April 2018?

I ask as I am creating an [app with ultra simple UI](https://github.com/AlwaysInMind/aim-web-app) and so this would be useful.

thanks

**Comment by SteveALee** [comment]
I now see https://github.com/matrix-org/matrix-js-sdk might be better - given I want to start with simple webRTC only

**Comment by t3chguy** [comment]
There is actually an update, the layering has recently been fixed, there may still be bugs with it and its still on the develop branch

**Comment by SteveALee** [comment]
Ooh, great. I'll take a look. Thanks

**Comment by ara4n** [comment]
i've updated the doc (no idea why i forgot this at the time :|)
