### ISSUE TITLE
Rooms with 'All Messages' as the notifications level no longer get green badges

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6575]
### Description

There used to be a message count badge (in green) to the right of the room name when there's an unread message and 'All Messages' is set as the notifications level. This may only happen to newly joined rooms (possibly joined on another device).

### Steps to reproduce

- Join a room (the default is 'All Messages' for the notification level)
- With the room not selected, receive a message in it
- Note the lack of badge (desktop notification and bold room name still occur, however)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
I can't reproduce this. 

Are you seeing this with *every* room that is set to "All messages"? and can you confirm the type of message you're receiving in that room?

**Comment by WildYorkies** [comment]
You only get notifications in two situations any more:

1. When someone does an `@room` mention
2. When someone sends a message in a DM conversation

Name mentions just don't work at all anymore.

**Comment by turt2live** [comment]
Also cannot reproduce anymore. Was probably a transient failure.
