### ISSUE TITLE
Devices section doesn't fit narrow screen.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-web#6581]
Devices section doesn't fit 1200x1600. So it's hard to find the checkbox for delete device as the scrollbar is shown at the bottom.

There should be no horizontal bottom scrollbar. If devices section doesn't fit the scrollbar should be shown just under this section!

Moreover there are a lot of unused space on the right.

![qwe](https://user-images.githubusercontent.com/14617699/39124243-60f90cec-4703-11e8-9738-0fe5a36f74c2.png)

**Comment by uhoreg** [comment]
Thank you for your report.  This issue has already been filed as #6314, so I'm closing this issue.  Please feel free to follow and/or upvote the other issue.
