### ISSUE TITLE
Viewing group page often produces an infinite spinner

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6592]
I think I've rageshaked on this before, but occasionally when I try to view a group page by manually entering its URL, i get stuck on an infinite spinner.

Probably related to #6413.

**Comment by lampholder** [comment]
I have invites to communities I just can't get rid of because of this bug :(

**Comment by lukebarnard1** [comment]
I have found the probable cause for this bug!

It's probably the concurrency limiter getting wedged. Apparently, when requests fail, they get stuck and prevent further requests from going through.
