### ISSUE TITLE
New Submit Bug Report dialog UX is confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6595]
Relaying on behalf of @AmandineLP:

<img width="711" alt="screen shot 2018-04-24 at 18 54 57" src="https://user-images.githubusercontent.com/1294269/39204902-0e1d3892-47f1-11e8-80d8-78e44771622e.png">

 * The placeholder github issue isn't that obviously a placeholder, which is confusing & frustrating
 * It's unclear what the 'Click here to create a GH issue' prompt is up to.  Are we asking users to create a bug before they submit logs?
 * Is the GH issue link the one for the rageshake contents? Or one you've yet to create? Or one you should have already created?

To fix, I suggest we just fix the wording of the second paragraph: "Please report bugs by [creating issues]() in Github.  If you are submitting logs associated with a given bug, please provide its URL below."

**Comment by turt2live** [comment]
I believe we've fixed these concerns:
![image](https://user-images.githubusercontent.com/1190097/61269635-74ce0780-a75c-11e9-8031-b7ae9d453614.png)
