### ISSUE TITLE
Move PRs to matrix-react-sdk

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6598]
Now that the Great Relayering has happened, we need to close all PRs and ask contributors to PR against matrix-react-sdk if they want to.

**Comment by WildYorkies** [comment]
Should Issues be moved to that repo as well? @lukebarnard1

**Comment by ara4n** [comment]
if we could, yes. but github doesn't currently provide a way of doing that whilst preserving the original numbering scheme (which is hardcoded all over the shop in the code and the issues themselves). So irritatingly we're stuck with the issues being filed against riot-web despite the code they likely refer to being in matrix-react-sdk :(

**Comment by turt2live** [comment]
ftr, as of a few weeks ago:
![image](https://user-images.githubusercontent.com/1190097/52834671-31ce1200-30a0-11e9-9bfd-d4a091ac17cc.png)

**Comment by aaronraimist** [comment]
Are there any PRs left?

**Comment by ara4n** [comment]
i doubt it. the onus was left on the author to rebase.
