### ISSUE TITLE
Privacy notice

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6607]
We need:
- a privacy notice for matrix.org
- possibly a privacy notice for riot.im
- probably a privacy notice for scalar

My guess is that we would like this feature to look something like:
- homeservers can configurably serve a privacy notice
- riot can display that privacy notice to all users of the homeserver
- the homeserver can track which users have agreed to the privacy notice

We might tactically choose to implement some aspects of the above in the client in the short term, however.

**Comment by turt2live** [comment]
@lampholder I believe this is covered by one or more of your riot-meta issues, if not already complete.

**Comment by lampholder** [comment]
So it is! I think this can be closed :)
