### ISSUE TITLE
The sticker picker is slow to use

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6608]
We want the sticker picker to feel nice and polished when it goes live. Currently it is (not very, but noticeably) slow.

Sort of related:
- https://github.com/vector-im/riot-web/issues/6471 - the fade-in on the stickerpicker is pretty but a bit annoying when you want to get a sticker quicker
- https://github.com/vector-im/riot-web/issues/6443 - Stickerpicker doesn't load stickers during scrolling, only once scrolling stops

**Comment by ara4n** [comment]
Folks confirm this in the wild: https://jasonrobinson.me/content/1603903/riot-added-stickers-o-ui-for-choosing-them-lags/

Amandine also has very slow scrolling on hers.

I think the solution is:
 * Turn off the fade in animation
 * fix the lazyloading code so it lazyloads as you scroll - not when you stop scrolling

**Comment by ara4n** [comment]
cc @rxl881 for info

**Comment by rxl881** [comment]
I've seen a couple of reports of this and while I agree that the two items you list (@ara4n) will help, I think that a bigger problem might actually be all of the animated GIFs playing at the same time. Chrome appears to be particularly inefficient at reengineering GIFs and when the frame thread caps out on a single processor scrolling etc. blocks completely.

It seems like the simplest / best solution to this might just be to make thumbnail GIFs in the sticker picker only render on mouse hover.

**Comment by rxl881** [comment]
As mentioned in #6769 I believe that this should now be fixed as a result of a number of merged PRs that drastically improve the way in which sticker thumbnails are loaded and monitored for visibility.
