### ISSUE TITLE
don't show the login page if an exception occurs insetLoggedIn or similar

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6616]
We seem to show the login page if an exception propagates out of setLoggedIn which is a terrible failure mode because people think they've been logged out, so log in again and lose all their keys without the usual warning.

**Comment by turt2live** [comment]
suggestion: Re-use the browser incompatibility warning and make it say something along the lines of "It's broken, please report this to the devs" maybe with a submit logs button. Some text to reassure the user that their e2e keys and stuff aren't obliterated would be nice as well, even if it says something like "It *should* be fine".
