### ISSUE TITLE
Feature Request: Edit a message

### ISSUE THREAD

**Issue by sunjam** [vector-im/riot-web#6618]
### Searched and not sure where to post this request if it doesn't already exist on Riot or Matrix.org

I'd like to be able to **edit** any message I post.  This is a critical feature I'm used to on every other communication platform.  Will **edit** ever be feasible?

**Comment by ara4n** [comment]
yes, it will. we'll be working on it fairly shortly. dup https://github.com/vector-im/riot-web/issues/1862

**Comment by thearduinoguy** [comment]
Fairly shortly is now over a year ago and still no editable messages. Please allow the message to be edited up to 30 seconds after posting to allow for errors.

**Comment by t3chguy** [comment]
Editable messages are in the latest version.
