### ISSUE TITLE
Images shared by bot can't display on Web/Desktop clients

### ISSUE THREAD

**Issue by charlesparvin** [vector-im/riot-web#6629]
I'm developping a MagicTheGathering related chatbot that puts cards' images in chat when requested by users

I'm using the sendImageMessage from the client in matrix-js-sdk to send URLs such as http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442093&type=card (PNG image).

Example message source (I had tried putting the w/h/mimetype/filesize metadata in the info part but it didn't change anything)

```
{
  "origin_server_ts": 1524860945239,
  "sender": "@me:myserver.com",
  "event_id": "$redacted:server.com",
  "unsigned": {
    "age": 164,
    "transaction_id": "m1524860938257.209"
  },
  "content": {
    "url": "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442093&type=card",
    "info": null,
    "body": "Lurking Chupacabra",
    "msgtype": "m.image"
  },
  "type": "m.room.message",
  "room_id": "!redacted:server.com"
}
```
Mobile users see the images appear in their chat as intended. But desktop/web clients (tested with 2 different users on their own machines) see the following message instead (but a "view the source" still gives the above)

```
MagicBot sent an image
Image 'Ravenous Chupacabra' cannot be displayed.
```

The problem happens both on encrypted and non-encrypted chats. Uploading images as users works fine

**Comment by t3chguy** [comment]
the URL should be an `mxc` resource (on the federated media repository) otherwise clients could refuse to render it (as a privacy protection mechanism).
https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-media-r0-upload

This seems to raise a serious issue that the mobile clients show non mxc-urls

**Comment by charlesparvin** [comment]
Well that clears up some doubts I had when starting to send images (I had seen the MXC URLs in example but it wasn't specifically mentionned that they were mandatory and I hadn't connected the dots for the privacy part also)

I'll double check the non-mxc URLs part and open a ticket on the riot-androit repo with steps to reproduce
