### ISSUE TITLE
[Feature Request] Start Minimized/In System Tray Setting

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#6633]
I have Riot starting on multiple computers when they boot, and for some reason whether it starts full screen, or minimized, varies from one computer to the next.

I can't seem to find a setting for "start minimized", or something of the sort. So, any chance we can get a setting for this please?

**Comment by BloodyIron** [comment]
I'm already using --hidden on my laptop, and it's not honouring it. Not sure why. Laptop is Ubuntu 18.04 (was doing this on 17.10 too).

**Comment by BloodyIron** [comment]
Yeah I'm still seeing --hidden as being ignored on any computer I've ran Riot (desktop) on.

**Comment by t3chguy** [comment]
Should be fixed by above PR. After next release if still broken let me know.
