### ISSUE TITLE
Redacting a pin event breaks the message context menu in that room

### ISSUE THREAD

**Issue by tulir** [vector-im/riot-web#6635]
### Steps to reproduce
* Pin a message
* Redact the event that pinned the message
* Try to open a message context menu

Context menu does not open, console shows 
```
TypeError: t.getContent(...).pinned is undefined @ MessageContextMenu.js:82:15
```

The context menu can be restored by manually sending a valid `m.room.pinned_events` event, such as `{"pinned": []}`

### Version information
- **Platform**: web
- **Browser**: Firefox 60.0b16
- **OS**: Ubuntu 18.04
- **Version**: 5c722f31ffe77843315a77dafeeab2162a583894 / matrix-org/matrix-react-sdk@773437b049f5136812c84282b3335e9d89c3eaff

**Comment by lampholder** [comment]
I expect us to be looking at pinned messages impl in the near future - we'll bear this in mind then.
