### ISSUE TITLE
We should constrain the format of aliases in RoomSettings at enter-time

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#664]
Erik wrote a useful component called RoomAlias which provides a way of editing aliases whilst constraining the format of the string to look right.  We should use it, or something like it, in RoomSettings.

**Comment by t3chguy** [comment]
Same should apply to Related Groups I presume

**Comment by t3chguy** [comment]
I'm thinking an input more like 
![image](https://user-images.githubusercontent.com/2403652/35183446-3a516f08-fdde-11e7-92a8-09a91247f88b.png)
would be simpler to both implement and use

**Comment by t3chguy** [comment]
We have a new generation component for this now: 
![image](https://user-images.githubusercontent.com/2403652/71366037-b75fff80-2598-11ea-9ed0-642186c1906d.png)
It needs to be used for 
![image](https://user-images.githubusercontent.com/2403652/71366052-c3e45800-2598-11ea-8d53-18a638887d7f.png)
