### ISSUE TITLE
Power level descriptions have a tab between "you must be a" and the label

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6642]
### Description

This is annoying for copy/pasting.

### Steps to reproduce

- Open a room's settings where you don't have permission to edit the power levels
- Copy/paste the descriptions ("To send messages, you must be a whatever").

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Fixed in the redesign
