### ISSUE TITLE
member list no longer orders by power level

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6643]

**Comment by ara4n** [comment]
so yo no longer have a way to tell who has ops in rooms with large numbers of people.

**Comment by aidalgol** [comment]
You can still look at the list of "Privileged Users" under the room settings until this is fixed.

**Comment by t3chguy** [comment]
It does seem to be, ignoring matrix.org having no presence:
![image](https://user-images.githubusercontent.com/2403652/40267754-63e14dfa-5b5a-11e8-8d97-d1414f4e49a3.png)
