### ISSUE TITLE
"Jump to first unread message" keeps coming back in #matrix-dev and #matrix

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6655]
### Description

No matter what I do, if I navigate away from the room and come back after someone has posted something, the bar will be at the top. I've tried clicking the X with no avail - the bar disappears but happily returns if I go away and come back. If messages come by after I've cleared the bar and have yet to navigate away, the read marker is in the correct spot. Once I leave and come back, it's also back.

Clicking 'Jump to first unread message' brings me to the redacted images with large depth values. 

This issue also affects riot-android. I can see the requests going through and getting a 200 OK, so it really shouldn't be this buggy.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
So annoying :(

**Comment by ara4n** [comment]
@turt2live i assume this died with the rebirthing of HQ & dev?

**Comment by turt2live** [comment]
Yes, and I'm sure there's a bug somewhere in the read marker stuff, but when a room is that hilariously broken there's not much the server/client can do.
