### ISSUE TITLE
Add a confirm prompt when removing avatar in settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6656]
> I've accidentally deleted my avatar a couple times on riot-web by hitting the wrong x and there is no confirmation on this action.

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1525275807948OOSpS:eggy.cc

**Comment by t3chguy** [comment]
You can no longer remove avatars, closing in favour of https://github.com/vector-im/riot-web/issues/8456
