### ISSUE TITLE
Stickers overlap content

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6666]
### Description

![image](https://user-images.githubusercontent.com/1190097/39595208-0e0592f0-4ecc-11e8-8e70-2277fdd32626.png)

From #test

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
A fix for this is being committed right now :)

**Comment by ara4n** [comment]
fixed (completely blindly) by https://github.com/matrix-org/matrix-react-sdk/commit/afb9e1f5f4af7bb502f4813ee81e49dddc2a54d9
