### ISSUE TITLE
Replies show both fallback and rich representation

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6669]
### Description

![image](https://user-images.githubusercontent.com/1190097/39600707-da878d64-4edc-11e8-8565-32fb24b36133.png)

### Steps to reproduce

Not sure.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
They'll be on an older version of replies

**Comment by t3chguy** [comment]
(which I agree is a bad experience but its on `/develop` and also to fix a bug/limitation that was found)

**Comment by lampholder** [comment]
Right, so will this affect all of the old replies, but no new replies?

**Comment by lampholder** [comment]
What I'm thinking is if this is only when rendering the 'old' style replies events I'm not super worried.

**Comment by t3chguy** [comment]
@lampholder Exactly

**Comment by t3chguy** [comment]
when old means the version right before the `<!--end-mx-reply-->` change and any previous
