### ISSUE TITLE
False incoming calls while app starts

### ISSUE THREAD

**Issue by dva-re** [vector-im/riot-web#6673]
### Description

Every morning, when I turn on the Riot app on PC or Mac, incoming call sound starts while history loads. Also blinking notifications about incoming calls from all contacts I have ever talked with. 

### Steps to reproduce

- Close Riot App
- Start Riot App

![riot-app](https://user-images.githubusercontent.com/10573161/39618010-8db3b68a-4f8a-11e8-9380-7b3bc1a2a531.png)

### Version information

- **Platform**:  desktop
- **OS**: Windows, macOS
- **Version**: 0.14.2 

_This gives considerable inconvenience when the whole office starts the computers and the melody begins, it looks like a jingle bells from all the speakers._

**Comment by lampholder** [comment]
This is a dup of https://github.com/vector-im/riot-web/issues/6510 :cry:
