### ISSUE TITLE
Email verification prompt on vector.im throws 404 for the image

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6677]
Clicked 'Forgot My Password', went through the hoops, and landed on a page that looked like this:

![image](https://user-images.githubusercontent.com/1190097/39731118-c91cbdd0-5222-11e8-9afd-710bd87df318.png)

The image referenced is `https://riot.im/app/img/logos/riot-logo.svg`

**Comment by ara4n** [comment]
fixed in matrix-org/sydent@7c95c24 - thanks
