### ISSUE TITLE
"Error Failed to change power level" when trying to make new mods/admins

### ISSUE THREAD

**Issue by jywarren** [vector-im/riot-web#6680]
### Description

I'm an admin in https://riot.im/app/#/room/#publiclab:matrix.org and trying to make more mods/admins, but when i use the dropdown in the right-sidebar menu:

![image](https://user-images.githubusercontent.com/24359/39763289-b55211f0-52aa-11e8-9c31-29d82e44d262.png)

...I see this message:

![image](https://user-images.githubusercontent.com/24359/39763465-212d23c4-52ab-11e8-9063-5a58a202021b.png)

If I choose `Admin`, i first see this, and click `Continue`, but then see the error message after a few seconds.

![image](https://user-images.githubusercontent.com/24359/39763309-bfb6148e-52aa-11e8-9f63-2a1c1e1731bf.png)

### Steps to reproduce

- click on a user
- click the sidebar dropdown for `Level`
- choose `Moderator` or `Admin`
- see message

Describe how what happens differs from what you expected.

I had hoped to make new moderators. It's not clear to me why it's not working, though I could speculate that it relates to verification? But I can't seem to figure it out or find additional guidance. 

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: riot.im/app

```
Google Chrome	66.0.3359.139 (Official Build) (64-bit)
Revision	a020eddf0d85fe84d4a6787b304f50aafb670969-refs/branch-heads/3359@{#767}
OS	Mac OS X
JavaScript	V8 6.6.346.26
```

**Comment by jywarren** [comment]
I believe that's unrelated, as I also attempted to admin that user. Thanks,
though, Liz!

**Comment by jywarren** [comment]
I haven't seen this come up again but will report back if it does! Feel free to close if you like. Thanks!

**Comment by anoadragon453** [comment]
Closing as per author's request.

**Comment by erAck** [comment]
Fwiw, I have the same with Element Web 1.11.5
As Admin in a (version 6) room plumbed with a LiberaChat channel I can't change neither permission roles nor roles of mxids, only get `Error  Failed to change power level`.

**Comment by erAck** [comment]
Fixing m.room.power_levels from string to integer fixed this for me.
https://github.com/matrix-org/synapse/issues/12538#issuecomment-1110801076
