### ISSUE TITLE
Password reset ('forgot password') asks user to backup their e2e keys, which is impossible

### ISSUE THREAD

**Issue by 26000** [vector-im/riot-web#6681]
### Description

When a user tries to reset their password (click on 'Forgot your password?') using an email linked to that account, they are asked to export their E2E room keys. But they don't have access to their keys obviously as they are neither logged in nor have keys in local storage.

### Steps to reproduce

 1. Go to https://riot.im/app/ or any other Riot instance.
 2. Enter the login page and click 'Forgot your password?'
 3. Enter your email and password, click 'Send Reset Email'
 4. You get asked to export your keys, which you don't have access to

(on an instance with guest access disabled)

 5. Click 'EXPORT E2E ROOM KEYS'
 6. Enter your passphrase, click 'Export'
 7. See an 'Unknown error' (second image) and an error in console: `Error exporting e2e keys: TypeError: Cannot read property 'exportRoomKeys' of null`

(on an instance with guest access enabled)

 5. Click 'EXPORT E2E ROOM KEYS'
 6. Enter your passphrase, click 'Export'
 7. Get your guest account E2E keys downloaded, not those of your account. Which is very bad, it's misleading and the user thinks they downloaded their keys, not a temporary account ones.

![image](https://user-images.githubusercontent.com/23152347/39765708-0972c078-52d2-11e8-8235-2b0a55dce2ec.png)
![image](https://user-images.githubusercontent.com/23152347/39765910-7baf073c-52d2-11e8-8bb4-2f8f64b99a04.png)

What I expect is a window saying that 'if you don't have a backup of your E2E room keys, you will lose all your E2E history'.

Log: unable to, not logged in

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chromium
- **OS**: Arch Linux
- **URL**: riot.im/develop / riot.im/app / chat.kotobank.ch / any other

**Comment by ara4n** [comment]
this just resulted in Amandine deleting all her E2E keys >:(

**Comment by t3chguy** [comment]
@ara4n this or https://github.com/vector-im/riot-web/issues/2671 ?

**Comment by ara4n** [comment]
it was the combination of both. the client had been logged out (by browser deleting local storage); but on prompting to reset the password it lured you into a sense of security by letting you export keys (which are blank). Having exported, without noticing the keys are blank, you then reset the password and lose all your other keys everywhere else due to #2671.

**Comment by ara4n** [comment]
see #2780
