### ISSUE TITLE
Slash-command sends a typing notification

### ISSUE THREAD

**Issue by jevolk** [vector-im/riot-web#6685]
When leading the input with a `/` the server still receives a typing notification which it will broadcast, even though the user does not intend to send a message to the room.

**Comment by t3chguy** [comment]
what about, `/me`, some slashcommands DO send a message into the room

**Comment by jevolk** [comment]
It looks as if there are an overwhelming number of commands which don't compared to those which do so perhaps it's possible to special case a match on `/me` and the few others.

Consider though in the majority case: for example a `/join #foo` when the user is in room `#bar` ends up sending _two_ useless broadcasts to `#bar` when it will never receive a message.

**Comment by jevolk** [comment]
@lampholder I know you're trying to do your best to triage these issues using your company's guidelines so I'm just alerting you to the possibility that you have mislabeled this with the `feature` label.

This is, without a doubt, an _extremely_ low priority issue. But it still describes unwanted or unwarranted behavior of the program. That makes it a bug, not a feature.

**Comment by lampholder** [comment]
Perhaps you're right - I'm certainly happy to recategorise this one 😄
