### ISSUE TITLE
Error in setting up a dev environment

### ISSUE THREAD

**Issue by soumikau-egnaroinc** [vector-im/riot-web#6686]
### Description

I followed all the steps under Setting up a dev environment and everything was installed without any issues but on "npm run" inside riot-web it gives the following error.

**Failed at the riot-web@0.14.1 start script 'parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the riot-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls riot-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/soumika/.npm/_logs/2018-05-09T09_10_07_451Z-debug.log
soumika@so 70% 1/1 build modules/home/soumika/Documents/riot/riot-web/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                                                                                ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at doListening (net.js:1416:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)
Reskindex: completed**

### Steps to reproduce

- git clone git@github.com:vector-im/riot-web.git
- cd riot-web
- git checkout develop
- npm install
- rm -r node_modules/matrix-js-sdk; ln -s ../../matrix-js-sdk node_modules/
- rm -r node_modules/matrix-react-sdk; ln -s ../../matrix-react-sdk node_modules/
- npm start

Describe how what happens differs from what you expected.

Log: sent/not sent?    

![image](https://user-images.githubusercontent.com/21257268/39806365-6215711a-5397-11e8-9a26-f9f8c8d81069.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by t3chguy** [comment]
Pretty clear error right there:
`Error: listen EADDRINUSE 127.0.0.1:8080`
You already have something on port 8080, historically I remember Skype used to listen on port 8080 for some stupid reason which you can disable in Settings.

**Comment by soumikau-egnaroinc** [comment]
Thank you. That helped :)
