### ISSUE TITLE
Two scrollbars in Firefox

### ISSUE THREAD

**Issue by fladd** [vector-im/riot-web#6694]
### Description

In Firefox, there are two issues with scrolling:
1. Scrolling is "jumpy", probably related to dynamically loading content from the chat history
2. There are two scrollbars (superimposed on each other)

### Steps to reproduce

- Scroll the chat window

Describe how what happens differs from what you expected.

I expect these issues to not happen.

Log: not sent

![image](https://user-images.githubusercontent.com/2971539/39844450-6a44cbde-53f0-11e8-89ee-c76536aaa50f.png)

### Version information

- **Platform**: web (in-browser) or desktop?
web (develop)

For the web app:

- **Browser**: Firefox (59, 60)
- **OS**: Windows, macOS
- **URL**: riot.im/develop 
For the desktop app:

- **OS**: Windows, macOS
- **Version**: current

**Comment by fladd** [comment]
Thanks for the answer. I don't really understand why replacing a well proven standard element like a browser's native scrollbar with some less proven third-party alternative was necessary (not sure what is unaesthetic about a normal scrollbar), but I think it would be great if this could be deactivated by users who value function over form.

**Comment by aaronraimist** [comment]
This is also present in Safari

**Comment by turt2live** [comment]
I'm not seeing this in Firefox 62 (Windows 10) - is it still happening for people?

Also I don't have a Safari to test with, but maybe it magically got fixed in the last 14 days? (please say yes...)

**Comment by aaronraimist** [comment]
@turt2live No it hasn't gotten fixed in /develop for Firefox or Safari on macOS. I cannot reproduce in Firefox on Elementary OS (Ubuntu).

**Comment by turt2live** [comment]
I'm going to pin it as a Mac issue then and hope someone has the bandwidth to fix it

**Comment by turt2live** [comment]
ftr, this is likely going to be fixed in the upcoming redesign.

**Comment by aaronraimist** [comment]
@turt2live fixed by getting rid of Gemini or what?

**Comment by turt2live** [comment]
I think that's the current plan, although it's somewhat subject to change. Getting rid of gemini is a long-term goal of the project in the first place and is likely to be the route taken.

**Comment by klopsi** [comment]
Firefox renders this page with two scrollbars and pgup/pgdn doesn't work.
[img]https://0x0.st/sROe.png[/img]
Page works fine in chromium, epiphany-browser, qupzilla, konqueror, qutebrowser.
Is this related to this bug?  Can it be fixed?

**Comment by ara4n** [comment]
this is still the case currently in the redesign. it should be fixed by killing off gemini everywhere.

**Comment by fladd** [comment]
still happening in 1.0 😬

**Comment by t3chguy** [comment]
This should be completely gone now as we just use CSS.
