### ISSUE TITLE
Right click in riot-web desktop doesn't work

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#6697]
### Description

I can't open the context menu with right click. This includes:
- message timestamps
- images
- URLs within messages
- blank space

### Steps to reproduce

- start riot desktop
- right click an URL or image

At that point I'd expect a context menu opening, but it doesn't appear.

Log: sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.14.2 (branch: develop, last commit: 0e0067785174de35c9fe6947a62d0f5cbe063704 - [also seems to happen on stable](https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$152590449956kFIWU:kotobank.ch))

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/6763
