### ISSUE TITLE
Riot loads a blank page - SyntaxError: JSON.parse: expected double-quoted property name

### ISSUE THREAD

**Issue by killua-eu** [vector-im/riot-web#6699]
Hi,

I started getting a blank screen on riot homepage load. Source is there, the Firefox console returns
`SyntaxError: JSON.parse: expected double-quoted property name at line 18 column 1 of the JSON data`

![screenshot from 2018-05-10 15-50-24](https://user-images.githubusercontent.com/410734/39875768-d0ac268e-5471-11e8-9685-b99178d11876.png)

Chromium reports errors

![screenshot from 2018-05-10 16-20-00](https://user-images.githubusercontent.com/410734/39875769-d0e0effe-5471-11e8-9cfb-8fbb680a8d40.png)

but eventually shows.

![screenshot from 2018-05-10 16-51-14](https://user-images.githubusercontent.com/410734/39876025-825e46b4-5472-11e8-9361-e19ff1db24db.png)

On windows 10 all works in firefox (60) and in chrome.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 59.0.2, **OS**: Ubuntu 17.10
- **URL**: chat.industra.space problem spotted on 0.14.2 currently on 0.14.1 (problem present as well)

Clearing the cache doesnt help.

**Comment by t3chguy** [comment]
Loading `https://chat.industra.space/#/home` works for me
You'll have to find which network request returns invalid JSON and figure out why. Typically this can be the config.json but in your case since it loads fine for me, it looks fine.

**Comment by killua-eu** [comment]
Before I could find out anything, it started to work again. Oh well, thanks @t3chguy :)
