### ISSUE TITLE
grey sending state is not honoured for replies

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6705]

**Comment by ara4n** [comment]
this seems hard to reproduce.

**Comment by t3chguy** [comment]
Seems fine to me

![image](https://user-images.githubusercontent.com/2403652/39955329-0f09e570-55c5-11e8-8de3-0806b9aff401.png)

(both message and the replythread are greyed out)

**Comment by lampholder** [comment]
Seems fine to me, too. @ara4n were there any special conditions that might have effected your experience?

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it (on Element Desktop 1.7.1).
