### ISSUE TITLE
Regression: Collapsing and expanding widgets in a room doesn't load them

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6707]
### Description

This used to work as a quick way to 'refresh' a widget, however now it's stuck on the loading spinner.

### Steps to reproduce

- In a room with a widget, expand the widget (if it isn't already)
- Give the widget permission to load (if you haven't already)
- Wait for the widget to load
- Collapse the widget by clicking the title bar
- Expand the widget by clicking the title bar
- Infinite spinner of sadness

The widget appears to load in the background somewhere as console.log statements make it through, but the content never shows.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
From duplicate issue:
>Probably due to the most recent changes to sticker widget matrix-org/matrix-react-sdk#1888
