### ISSUE TITLE
Key press ordering is often wrong in RTE

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6712]
I thought i'd already filed this (and it's quite similar to https://github.com/vector-im/riot-web/issues/6464 and https://github.com/vector-im/riot-web/issues/4708), but there's a really annoying failure mode where if you start typing a message and hit ctrl-A to select it in order to replace it with something else, you can end up with an uneditable character wedged at the beginning of the composer.  If you keep ctrl-A-to-replacing then eventually you can get rid of it, but the race between moving the selection and typing the replacement is horrible and very similar to #4708.

Mainly filing the issue now to track whether switching to Slate fixes it (which superficially it does, so far, on the matthew/slate branch of react-sdk).

**Comment by lampholder** [comment]
Presumably this is fixed in the inbound Slate rewrite?

**Comment by turt2live** [comment]
@ara4n have you seen this in the last 6 months? I haven't, whereas previously it was infuriatingly common.

**Comment by ara4n** [comment]
yup, slate fixed it (and this was one of my main reasons for slate)
