### ISSUE TITLE
Typing/clicking spams the console with "No sticker picker widget available"

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6715]
### Description

Surely it should only complain once?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by rxl881** [comment]
I don't think that this log line is adding anything, and it is being printed every time the component is being re-rendered (when no sticker picker is present). So, I've removed it - 986fb3237d7016d4a90ec6c5164203f77997ec93
