### ISSUE TITLE
ILAG login can fail leaving you stuck on two spinners.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6734]
I just tried to test following an link to a non-peekable but public join_rules room in an incognito tab (riot.im/develop/#/room/#foo:matrix.org) ; ILAG failed badly after signing up my account in order to join the room, leaving me staring at two spinners - one in the background trying to join the room; another in an ugly grey foreground overlay that covered the whole screen).

**Comment by bwindels** [comment]
Was this filed before GDPR consent was put into place?

**Comment by ara4n** [comment]
Yes it was. But the bug still exists, except we get stuck on one spinner rather than two now...

**Comment by bwindels** [comment]
Went through it with Matthew and the remaining problematic behaviour is a dupe of #6679
