### ISSUE TITLE
Document how to turn off piwik and bug reports

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6738]

**Comment by turt2live** [comment]
I'd say it's worth documenting just because it comes up every once and a while. To be honest, it probably doesn't need anything more than "To disable, remove it from your config" added to the README.

**Comment by lukebarnard1** [comment]
Fair enough, especially if it's in the sample and the instructions we give are to copy that over to config.json.

**Comment by turt2live** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/7435
