### ISSUE TITLE
animated stickers should have the option not to loop?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6748]

**Comment by t3chguy** [comment]
because !()[https://riot.ovh/_matrix/media/v1/download/matrix.org/VAQdAzPxaJLNNSjVZxJEUULx] is jarring

**Comment by lampholder** [comment]
Do you mean the viewer should be able to stop them from looping? Or something else?

Or should they just honour the do not autoplay option as per https://github.com/vector-im/riot-web/issues/6534 ?

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/6534 (and assuming that's the issue being reported)
