### ISSUE TITLE
No timestamps on action messages (/me)

### ISSUE THREAD

**Issue by Angedestenebres** [vector-im/riot-web#6751]
Hey,

There is an issue if an user uses the /me command. The message is shown without any timestamps, see screen below as example:

![screenshot_2018-05-17_13-57-27](https://user-images.githubusercontent.com/21110485/40176123-911bc196-59da-11e8-91f4-fd31240f79f6.png)

However, on mobile app, the timestamps can be found by clicking on the message : 

![screenshot_20180517-113708](https://user-images.githubusercontent.com/21110485/40176324-4d83e318-59db-11e8-9dd9-5e7cef9ce910.png)

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/2284
