### ISSUE TITLE
Redacted stickers don't show up with stripy redaction thing

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#6757]
### Description

When redacting an m.sticker event, there's no visual indication afterward that a redacted event exists in the stream.

### Steps to reproduce

- Send m.sticker event into room.
- Redact sticker.

![sticker_redaction](https://user-images.githubusercontent.com/17915621/40194335-0c83702a-59d8-11e8-8a39-7f0b6586bbf6.png)

In above image, a sticker event was redacted immediately above the visible redacted event.

### Version information

- **Platform**: web

For the web app:

- **Browser**: qutebrowser v1.2.1 (qtwebengine)
- **OS**: Void Linux glibc 64bit
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
fixed by above PR
