### ISSUE TITLE
freeze invite from bad server

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#6759]
I am use Riot on official riot site in rambox. https://rambox.pro/
Ubuntu 16.04 on desktop.

1. I have account on matrix.org.
2. I create new matrix-server.
3. I have account on my new matrix-server.
4. I forget allow server-to-server port on firewall on my server (8448).
5. I was create new room on my server and send invite to my account on matrix.org.
6. I cannot accept or cancel this invite on matrix.org account. It said "Not a known room" for cancel or "No known server" for accept invite.
7. I setup server-to-server port in firewall properly. Now I can join and succerfully invite my accounts, but this old room from step 1-6 - not removed from my list in riot. I think, that it is must be remove, if error occur. 

![1](https://user-images.githubusercontent.com/1297163/40206726-b141753e-5a74-11e8-8e30-c28b0ba86903.png)
![2](https://user-images.githubusercontent.com/1297163/40206727-b17a2e2e-5a74-11e8-942d-deefa013680f.png)
![3](https://user-images.githubusercontent.com/1297163/40206728-b1b48f56-5a74-11e8-8866-7afce941cff6.png)

**Comment by t3chguy** [comment]
Reject the invite then clear cache in Settings. This is a Synapse bug

**Comment by progserega** [comment]
> Reject the invite then clear cache in Settings. This is a Synapse bug

Yes, this is help. Thank you!
