### ISSUE TITLE
Cannot add bot/bridge if maximum of widgets are present

### ISSUE THREAD

**Issue by Salamandar** [vector-im/riot-web#6771]
If the maximum of widgets (2) already are present, the "Add widgets" obviously prompts an error.

Unfortunately that's the only (visible) way to add another kind of integrations (bot/bridge).

**Comment by turt2live** [comment]
There's also a 3x3 grid icon in the top right of the room by the search button that opens the "Integrations Manager".

**Comment by Salamandar** [comment]
Oh didn't know that, thanks !
Still, having 2 buttons with almost the same usage is a bit confusing.

**Comment by lampholder** [comment]
The second button is gone now, so hopefully this is resolved :)
