### ISSUE TITLE
Custom widget: Etherpad yields "Cookie could not be found. Please allow cookies in your browser!"

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#6773]
Hey, I'm using `/develop` and tried to add a `pad.riseup.net` Etherpad instance as "custom widget" to Riot. Everything seems to be working fine including the UI even starting to load, but then the Pad just displays in large letters:

"Cookie could not be found. Please allow cookies in your browser!"

This happens in three different browsers, and I've turned off all cookie blocking etc., so I think this is probably a problem in Riot. Or is it Etherpad?

**Comment by lampholder** [comment]
Hmm, this works for me on chrome 65.0.3325.181 on Ubuntu. @madduck are you still seeing the problem now?

**Comment by turt2live** [comment]
I think we fixed this at some point in the last 2 years. If it is still an issue, visit #riot-web:matrix.org for assistance first.
