### ISSUE TITLE
Request: Option to change ringing/notification sound

### ISSUE THREAD

**Issue by gnorbsl** [vector-im/riot-web#6776]
The current ringing sound is incredibly intrusive in my opinion. 

I would welcome an option to change the sound or at least a way to change it manually, I wasnt able to figure out where it is stored.

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/5891

**Comment by lampholder** [comment]
I've added 'ringing' to #5891 - let's use #5891 to track (closing this one)
