### ISSUE TITLE
Stuck after login in Tor Browser: performance.mark is not a function

### ISSUE THREAD

**Issue by ollieparanoid** [vector-im/riot-web#6781]
### Description

I can't use the riot webapp anymore. After logging in, the spinning animation goes on forever, and the JS console says:
> `TypeError: performance.mark is not a function`

I guess the function was disabled in Tor Browser to make fingerprinting the user harder.

### Steps to reproduce
- Install Tor Browser on Linux
- Open Riot Webapp
- Login

### Version information

- **Platform**: web (in-browser)
- **Browser**: Tor Browser 7.5.4 (based on Mozilla Firefox 52.8.0) 
- **OS**: Arch Linux x86_64
- **URL**: https://chat.disroot.org/

### Output from JS console
```
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  olm.js
"Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome."  bundle.js:49:8449
set language to en-us  bundle.js:49:8449
"Vector starting at https://chat.disroot.org/#/login"  bundle.js:49:8449
TypeError: performance.mark is not a function[Learn More]  bundle.js:127:12030
	t.default<.startPageChangeTimer https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:127:12030
	bound  self-hosted:913:17
	t.default<.componentWillUpdate https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:127:11608
	C._performComponentUpdate https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:152:30868
	C.updateComponent https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:152:30246
	C.performUpdateIfNecessary https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:152:29573
	i<.performUpdateIfNecessary https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:17:13271
	s https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:14:9503
	i.perform https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:36:9535
	i.perform https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:36:9535
	.perform https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:14:10658
	x https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:14:10835
	bound  self-hosted:915:17
	i.closeAll https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:36:10123
	i.perform https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:36:9615
	d.batchedUpdates https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:153:21416
	l https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:14:9785
	r https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:50:3504
	u<.enqueueSetState https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:50:4647
	r.prototype.setState https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:74:10316
	t.default<.setStateForNewView https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:127:12911
	bound  self-hosted:915:17
	t.default<.onAction https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:127:13392
	bound  self-hosted:915:17
	a</e.prototype._invokeCallback https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:98:20483
	a</e.prototype.dispatch https://chat.disroot.org/bundles/600a15a9167cce7998f8/bundle.js:98:20298
	bound  self-hosted:955:17
```

**Comment by turt2live** [comment]
Looks like this problem would have been introduced in https://github.com/matrix-org/matrix-react-sdk/pull/1814

**Comment by jadasaq** [comment]
@t3chguy the error I am getting in https://github.com/vector-im/riot-web/issues/6809 is different. Please check the logs in the link.

my error starts like this:
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  olm.js
Failed to open log database: undefined  bundle.js:49:9096
Failed to initialise rageshake: Error: Failed to open log database: undefined  bundle.js:49:9096
InvalidStateError  bundle.js:49:9674

**Comment by t3chguy** [comment]
@jadasaq no it is not, `Unhandled rejection t.default<.startPageChangeTimer@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:127:16347` is from your log, `startPageChangeTimer` calls `performance` which is blocked in Tor

**Comment by jadasaq** [comment]
> t3chguy
is that the only issue? what about the remaining errors?
also, is there any other way to signup to riot?
`

**Comment by lampholder** [comment]
Ugh - @lukebarnard1 it looks like performance stuff is striking again :(

**Comment by lampholder** [comment]
We need to be 100% certain that our performance measurement stuff doesn't break the client _ever_.

**Comment by lukebarnard1** [comment]
>We need to be 100% certain that our performance measurement stuff doesn't break the client ever.

This would depend on spinning up Riot in a bunch of different browsers and doing a few tests at least before we release.

**Comment by t3chguy** [comment]
Fixed by above referenced PR.
