### ISSUE TITLE
@-mention doesn't autocomplete display names

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6782]
### Description

Trying to autocomplete someone by the name "James" doesn't work because their username is "jchaulk".

![image](https://user-images.githubusercontent.com/1190097/40393412-8f685aac-5ddc-11e8-942c-7e45bf9982f3.png)
![image](https://user-images.githubusercontent.com/1190097/40393422-96e2530a-5ddc-11e8-9b2f-ebc8e05734d0.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by BadPackets** [comment]
Definitely would be nice to have this feature.

**Comment by lampholder** [comment]
As far as I can tell @-mentions _do_ complete display names - is this something specific to the 'ja' != 'jc' case?

**Comment by t3chguy** [comment]
fwiw `@travisr` <kbd>TAB</kbd> does not work for me to autocomplete you @turt2live

**Comment by turt2live** [comment]
That's just mean of Riot then :(

It used to, so maybe one of the autocomplete fixes made it different?

**Comment by t3chguy** [comment]
autocomplete fixes (mine) haven't been released yet and I tested in /app :(

![turt2live](https://user-images.githubusercontent.com/2403652/41928111-096a38ca-796c-11e8-8a4f-029c5176f8f6.gif)

**Comment by xfalcox** [comment]
@t3chguy this change will use display names for autocomplete even when the matrix_id doesn't match?

Use case is:

- Matrix ID: `@x12345678:matrixhomeserver.com`
- Display Name: John Smith

So typing `@Joh` will autocomplete this user?

**Comment by t3chguy** [comment]
No, joh<TAB> would though

**Comment by bwindels** [comment]
Doesn't work for me either on Riot 0.16. I don't think it ever has. You need to remember the user ids of people if they diverge from their display name AFAIK.

**Comment by bwindels** [comment]
@dbkr right, but that still doesn't allow you to cycle through users, so it only works when the part you typed is the unambiguous start of a display name. When I try to complete t3chguy on riot-dev by typing "@ mi" (ignore the space) I can't get it to work for example.

**Comment by dbkr** [comment]
@bwindels typing `@mi` into riot-dev doesn't give t3chguy as an option though, because it only matches usernames and his username doesn't match that query. It gives some people whose usernames do though, and you can cycle through them with tab / down arrow / cursor?

**Comment by dbkr** [comment]
This shouldn't be *too* hard to fix: I suggest just stripping the `@` from the start of the query in `UserProvider.js` if the query starts with `@`. (since it's only used for trigger the autocompletion) and then stripping the `@` from the start of all the usernames we feed into the matcher to match. The kicker is that the matcher can only take keys from an object. I'm thinking the best thing would be to rewrite the matcher so you can just feed in search strings and matching objects, making it a lot simpler.

Leaving this for now as I was hoping it would be a quick fix.
