### ISSUE TITLE
Unable to view or send messages in any E2E rooms with single device

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#6786]
### Description

When I try to send messages in E2E rooms in qutebrowser, it immediately goes to "your message was not sent", and stays there no matter what until you press "cancel message". Additionally, I am unable to decrypt any old messages including ones I could see yesterday. This is the case using both /develop and /staging. /app allows me to "send anyways" but still can't decrypt messages I could decrypt yesterday. See screen shot taken from /develop below.

![message_not_sent](https://user-images.githubusercontent.com/17915621/40433195-6685845a-5e79-11e8-9f5a-8a91cae40827.png)

I have not attempted to log out this account and back in because I wanted to document the bug first. Will comment after attempting to do so. Will also send debug logs from riot-web /develop @adam:thebeckmeyers.xyz.

### Steps to reproduce

see above.

### Version information

- **Platform**: web

For the web app:

- **Browser**: qutebrowser v1.2.1 (qtwebengine)
- **OS**: Void Linux glibc 64bit
- **URL**: riot.im/develop, riot.im/staging

UPDATE: after going back to /develop after trying /app, everything seems to be working as expected with exception of being unable to decrypt old messages. In particular, in rooms with unknown devices, I now see the normal warning where I have three options "show devices", "send anyways", "cancel" rather than just the two of "send anyways" and "cancel" I had before. The "send anyways" button now works where it hadn't before. Maybe this was just a transient bug on /develop? Is /staging directly tracking /develop currently?

**Comment by turt2live** [comment]
@non-Jedi Is your indexeddb full by chance? Reference: https://github.com/vector-im/riot-web/issues/6120

**Comment by non-Jedi** [comment]
Very well could be. Drive was very full when I started the browser (but cleared out since then). Let me restart and see what happens. Will have to wait for a couple hours; in middle of very large download.

**Comment by lampholder** [comment]
So does it sound like this is just another instance of (the very annoying) #6120?

Also @non-Jedi we usually use /staging to host a release candidate for testing, so it doesn't 'track' /develop per se. /develop will sometimes have code changes we've decided we're not releasing yet, and it will usually have any the code changes that have been implemented since the release candidate was cut

**Comment by non-Jedi** [comment]
Ah. Yes. Sorry; forgot about this. Although I wasn't able to decrypt the old events I lost until I shared keys, I haven't had any recurring problems with the other stuff here, so I'm going to say this is probably just the aforementioned issue.
