### ISSUE TITLE
emojione ignores variation selectors

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6788]
which means that even if you type ™ as U+2122 U+FE0E to indicate that it should be rendered as a font glyph rather than by an emoji font, emojione still goes and hijacks it. This is true on both Slate & Draft

**Comment by turt2live** [comment]
We're taking out emojione: https://github.com/vector-im/riot-web/issues/9281

I suspect this might be a composer issue as well, possibly a variant of https://github.com/vector-im/riot-web/issues/7665
