### ISSUE TITLE
Can't type Russian symbol 'б' in Start chat dialog

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#6789]
In input field of `Start a chat` dialog I can't type Russian symbol `б` with error `You have entered an invalid address.`. Seems this is because Russian symbol 'б' is located at `,` button, so Riot interprets this key press as splitter, without lookup to current locale and received symbol. Can we fix this?

**Comment by MazeChaZer** [comment]
For anyone interested, the relevant source code for this is at https://github.com/matrix-org/matrix-react-sdk/blob/3a222e02f14234383067ab273cc1b447e35e9df5/src/components/views/dialogs/AddressPickerDialog.js#L138

**Comment by lampholder** [comment]
This is a dup of https://github.com/vector-im/riot-web/issues/4523

**Comment by lampholder** [comment]
I'm going to close this one in favour of continuing discussion on #4523
