### ISSUE TITLE
errors from invites are swallowed silently

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#6790]
if an attempt to invite a user to a room fails with a 403, riot swallows the error

**Comment by lampholder** [comment]
This is (probably) the general case of https://github.com/vector-im/riot-web/issues/4308 and https://github.com/vector-im/riot-web/issues/3968 and https://github.com/vector-im/riot-web/issues/1597 and is possibly the same as https://github.com/vector-im/riot-web/issues/3283?

**Comment by richvdh** [comment]
> This is (probably) the general case of #4308 and #3968 and #1597 and is possibly the same as #3283?

yes.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2317
