### ISSUE TITLE
tags in room list don't adjust at window resize

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#6795]
### Description

The tags in the room list stay at the same place when I resize the window. It is basically the same misbehavior as described in https://github.com/vector-im/riot-web/issues/3670

Other users also seem to have that issue:
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$152718102382nEpAB:t2l.io
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1527182155104JEOBL:cadair.com

### Steps to reproduce

- resize the riot window

I'd expect the room list to re-arrange it's tags, but they stay at the same place.

Log: sent

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 0.15.3 (develop@b97ae0246d7d566f3ac0a25bb712ecb9cb3c02a6)

**Comment by lampholder** [comment]
I've triaged this like #3670 was triaged; as far as I can see it's the exact same problem back again.

**Comment by lukebarnard1** [comment]
Bizarrely, the original fix (https://github.com/matrix-org/matrix-react-sdk/commit/1faecfd) [got reverted](https://github.com/matrix-org/matrix-react-sdk/commit/ebfafb363972e77ef02f0e518573bf68ebc0ed15#diff-fd399859805e65901b9904ef5fd19844R466) when @dbkr did the revert on #807.
