### ISSUE TITLE
Hide empty tags when room filter active

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#6801]
When I type something into the room filter box, it's very confusing to have all the tags displayed, even though none of the matching rooms are associated with them.

I suggest that Riot should hide tags that are empty when a room filter is active (just like it wouldn't display empty tags in the first place, as such a concept doesn't exist). That is to say: please compute the set of tags to display from the set of rooms that pass the filter.

**Comment by lampholder** [comment]
I would very much like this feature.
