### ISSUE TITLE
riot shouldn't try to load integrations from an integration manager unless the user has accepted that manager's privacy policies

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6802]

**Comment by ara4n** [comment]
We try to get an auth token from the integration manager regardless of whether the user has accepted that integration manager's policies (or even their HS's policies).

**Comment by ara4n** [comment]
This is particularly unfortunate if the HS & integration manager are run by different parties (e.g. someone using a custom HS but using the scalar integ manager, especially as scalar is the default integ manager in SdkConfig.js), as the privacy acceptance mechanism on their HS doesn't help them with scalar.

**Comment by turt2live** [comment]
Much like how synapse isn't required to force consent upon users, the API for this shouldn't assume the manager requires consent. 

Also, please ping me when the PR is open or shoot me a message during development. I'd like to make sure Dimension supports this :)

**Comment by 4nd3r** [comment]
not only this, but there should be an option to turn off any 3rd party connection.

imagine corporate network, where this kind of behaviour will raise alarms or network is airgapped, so no point even trying.

**Comment by t3chguy** [comment]
You can do that by self hosting riot which is just a bunch of static files @4nd3r
