### ISSUE TITLE
[Desktop Client] [Windows 7] Riot client doesn't start minimized

### ISSUE THREAD

**Issue by BadPackets** [vector-im/riot-web#6803]
Steps to reproduce:
Windows 7
Riot desktop client v0.15.4
![image](https://user-images.githubusercontent.com/32589462/40574946-d6cdd5aa-6090-11e8-8fc8-df9d160700c9.png)
Riot client doesn't start minimized and uses last window position instead (usually maximized)

Issue does not occur on Windows 10. Not sure if `--hidden` is being ignored or other Electron issue.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/6633

**Comment by BadPackets** [comment]
Sure, I tested both OS. Interesting to read in [#6633](https://github.com/vector-im/riot-web/issues/6633) that the issue was affected a nix user. I figured this was a Windows issue only.

Windows 7
"%LOCALAPPDATA%\riot\update.exe" --processStart "Riot.exe" --process-start-args "--hidden"
Does not start minimized

Windows 10
"%LOCALAPPDATA%\riot\update.exe" --processStart "Riot.exe" --process-start-args "--hidden"
Always starts minimized

**Comment by lampholder** [comment]
Can this issue and https://github.com/vector-im/riot-web/issues/6633 be summarised as:
 - we would like this to be an explicit, configurable option in Riot
 - electron doesn't reliably honour the --hidden parameter; whether or not it honours the param seems to be OS/version specific

**Comment by t3chguy** [comment]
@lampholder it's not only os/version specific, it also depends on what state you left the window on last run

**Comment by t3chguy** [comment]
There's a pr which should fix it

**Comment by t3chguy** [comment]
Should be fixed by above PR. After next release if still broken let me know.
