### ISSUE TITLE
Every update to desktop version of Riot changes the device key

### ISSUE THREAD

**Issue by spijet** [vector-im/riot-web#6808]
### Description

After updating Riot to new version I find that I'm unable to read any e2e-encrypted chats I'm member of, seeing this error instead of every message:
```
** Unable to decrypt: The sender's device has not sent us the keys for this message. **
```
Then, if I open my secondary Riot instance (iOS or browser-based), I see that, while having unchanged device ID, my Desktop instance has different device key (iOS/Web "see" the old device key on the "Verify" page, while Desktop shows the new key in its "Options" screen).

### Steps to reproduce

- Update `riot-desktop` package
- Launch it
- Check the device key in the app and compare it with the key seen in other Riot apps

Describe how what happens differs from what you expected.

Log: Sent!

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.15.4 (olm version: 2.2.1)
- **Arch Linux package versions**:
- - `riot-web`: 0.15.4-1
- - `riot-desktop`: 0.15.4-1

**Comment by ara4n** [comment]
this sounds possibly related to https://github.com/vector-im/riot-web/issues/6761 or https://github.com/vector-im/riot-web/issues/6714

**Comment by turt2live** [comment]
I wonder if it's somehow related to #6120 as well

**Comment by spijet** [comment]
My whole `~/.config/Riot/IndexedDB/` dir is 5.0 MBytes at the moment. Also, I think that if it was the cause, wouldn't device key change at arbitrary points in time, not exactly after upgrading Riot?

**Comment by turt2live** [comment]
Potentially. I only mentioned it because it fits into the category of "strange e2e behaviour". It's more than likely something to do with electron though.

**Comment by ArchangeGabriel** [comment]
Why would it have to do with electron? electron wasn’t updated in a while on Arch. However it could be related to NodeJS for instance, since Arch updated to 10.x recently.

I have not observed this issue yet, I will look carefully on next Riot update.

**Comment by turt2live** [comment]
*electron version of riot

**Comment by ArchangeGabriel** [comment]
There is no embedded electron in Riot on ArchLinux, system one is used. ;)

**Comment by ArchangeGabriel** [comment]
So actually this could be an electron version mismatch between Riot expectations and what is available.

**Comment by turt2live** [comment]
I'm just trying to say the desktop version of Riot, which is commonly known as the electron version :(

Either way, my suggestion clearly isn't the issue so I'll leave it to someone else to figure out (as done here: https://github.com/vector-im/riot-web/issues/6808#issuecomment-392408190 )

**Comment by spijet** [comment]
@ArchangeGabriel My employer hosts its own Matrix server with its own deployment of riot-web (which is not different from current upstream, AFAIK). I see no problems when using the web version, only the Electron-based desktop version from Arch.

The problem itself happens exactly after upgrading `riot-{web,desktop}` packages, not NodeJS or Electron. I'll try to isolate the case when the next Riot version is available (by isolating I mean I will only update `riot-web` and `riot-desktop` packages and nothing else, just to check).

**Comment by akontsevich** [comment]
Hope you'll find the solution to solve this. I was forced to remove old room and create new unencryped. No users in it since then. :)

**Comment by spijet** [comment]
Just did a partial upgrade of Riot, after upgrading everything else on my system:
```
[2018-07-05 10:06] [PACMAN] Running 'pacman --color auto -S community/riot-desktop community/riot-web'
[2018-07-05 10:07] [ALPM] running '00_snapper-pre.hook'...
[2018-07-05 10:07] [ALPM-SCRIPTLET] ==> root: 1282
[2018-07-05 10:07] [ALPM] transaction started
[2018-07-05 10:07] [ALPM] upgraded riot-web (0.15.5-1 -> 0.15.6-1)
[2018-07-05 10:07] [ALPM] upgraded riot-desktop (0.15.5-1 -> 0.15.6-1)
```
So far so good — nothing broke this time. I exported E2E room keys before upgrading, in case if anything goes wrong. @akontsevich, it could work for you in the future.

**Comment by akontsevich** [comment]
@spijet hope so. For now all my users gone from this platform.

**Comment by spijet** [comment]
Just upgraded Riot to 0.15.7-1 — no problems here. I think I'll close it for now. Will reopen in case if anything breaks again.
