### ISSUE TITLE
https://riot.im/app/ = blank page.

### ISSUE THREAD

**Issue by magicgoose** [vector-im/riot-web#6810]
### Description
If I try to load https://riot.im/app/, I get a (visually) blank page.
Probably related to the fact that https://riot.im/app/config.riot.im.json replies with 404. (this request is made from https://riot.im/app/)

It also used to show something ≈10 minutes ago.

### Steps to reproduce

- Visit https://riot.im/app/

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 60.0.1 (64-bit) EME-free
- **OS**: macOS
- **URL**: riot.im/app

To be precise, here's the example response to the failing request:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /app/config.riot.im.json was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at riot.im Port 80</address>
</body></html>
```

**Comment by t3chguy** [comment]
That failing request is fine, its for an optional instance config.

Paste the full log if you want help

**Comment by magicgoose** [comment]
Here is the output from the Web Console:

	Unhandled rejection value/this.flushPromise<@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:49:10594
	e.exports/e.prototype._execute@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:37:28101
	e.exports/i.prototype._resolveFromExecutor@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:38:23940
	i@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:38:16248
	value@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:49:10543
	flush@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:49:13482
	@https://riot.im/app/bundles/237db52ea1bc0282ffcf/bundle.js:75:28852
	bundle.js:49:9096
	Successfully compiled asm.js code (total compilation time 53ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))
	olm.js
	Failed to open log database: undefined
	bundle.js:49:9096
	Failed to initialise rageshake: Error: Failed to open log database: undefined
	bundle.js:49:9096
	set language to en-us
	bundle.js:49:9096
	Vector starting at https://riot.im/app/
	bundle.js:49:9096
	No previous session found.
	bundle.js:49:9096
	Doing guest login on https://matrix.org
	bundle.js:49:9096
	XML Parsing Error: syntax error
	Location: https://riot.im/app/version?cachebuster=1527508620711
	Line Number 1, Column 1:
	version:1:1
	Registered as guest: @857841:matrix.org
	bundle.js:49:9096
	setLoggedIn: mxid: @857841:matrix.org deviceId: guest_device guest: true hs: https://matrix.org
	bundle.js:49:9096
	Removing indexeddb instance: matrix-js-sdk:crypto
	bundle.js:49:9096
	unable to delete IndexedDBCryptoStore: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
	bundle.js:49:9096
	Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.
	Content Security Policy: The page’s settings blocked the loading of a resource at https://riot.im/app/bundles/237db52ea1bc0282ffcf/indexeddb-worker.js (“worker-src”).
	Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.
	Content Security Policy: The page’s settings observed the loading of a resource at https://riot.im/app/bundles/237db52ea1bc0282ffcf/indexeddb-worker.js (“worker-src”). A CSP report is being sent.

**Comment by magicgoose** [comment]
I don't know why but when I reloaded the page again, it finally shows something.
