### ISSUE TITLE
Google Calendar Widget and Google Docs Widget broken

### ISSUE THREAD

**Issue by chimere2** [vector-im/riot-web#6812]
### Description

When adding the GoogloDocs or GoogleCalendar widgets to a room, the message "404 not found" is displayed

### Steps to reproduce

- Add a Google Calendar or Google Docs Widget to a room
- message "404 not found" is displayed in widget
- if expanding the widget outside Riot, one can see that the following URL is called  : 
   https://scalar.vector.im/api/widgets/googleCalendar.html?src=...
- replacing "googleCalendar" by "googlecalendar" in the above URL makes it work again.
- same problem with Google Docs widget 
  calls https://scalar.vector.im/api/widgets/googleDocs.html?url=...
  intead of https://scalar.vector.im/api/widgets/googledocs.html?url=

Log: sent/not sent?    
no logs

### Version information

- **Platform**: web (in-browser) or desktop?
  Desktop

For the desktop app:

- **OS**: Tested on Linux, Windows, Android
- **Version**: 0.15.3 and 0.15.4

**Comment by turt2live** [comment]
Confirmed. Paging @rxl881

**Comment by poVoq** [comment]
On the Android version it also just gives a black screen. Might be related to recent Google drive API changes?

**Comment by chemikyn** [comment]
I reproduced this issue exactly as described on Riot.im on the Opera web browser 53.0 on Ubuntu 18.04.

**Comment by lukebarnard1** [comment]
A fix for this is incoming! It's actually an issue with Modular.
