### ISSUE TITLE
Riot-web app block suspend

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#6814]
Riot-web electron app block suspend mode in Mac OS immediately after start app (without starting using camera, mic, making any calls). Is there any way to fix this?

In Mac OS system monitor shows "yes" in column "Preventing sleep" of Riot app.

**Comment by lampholder** [comment]
I don't use electron on my mac - what is the user experience of this? Can you not sleep your mac once you've started riot.im electron?

**Comment by t3chguy** [comment]
It prevents automatic sleeping when the app dispatches info about a voip call, so related probably to the erratic ringing from past calls on launch

**Comment by MurzNN** [comment]
Seems sleep is blocked if after ending the call, sometimes rooms after call finished - stay with unread messages like:
- ... placed a voice call.
- ... answered the call.
- ... ended the call.

**Comment by MurzNN** [comment]
Here is screenshot with fake unread notifications in Mac OS after ending call: http://i.imgur.com/bThGmA3.png
