### ISSUE TITLE
Add 'Copy image to clipboard' function to Electron right click menu on image

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#6815]
At now Riot-web Electron provide ability only for Save image, but Chromium engine can also copy image to clipboard. This will be useful for easily re-paste them is neighboring room, without downloading to computer and uploading. 

So please add menu item "Copy to clipboard" on image right click menu.

**Comment by t3chguy** [comment]
Its there.
![image](https://user-images.githubusercontent.com/2403652/40663942-b8b6c5d6-6351-11e8-8bdd-3c5fa987a9e0.png)

**Comment by MurzNN** [comment]
Yes, sorry, the problem is reproduced in Rambox Electron app (I use it instead of Riot).

**Comment by t3chguy** [comment]
The context menu is something that the electron layer manages, not the webapp so open the issue there.
