### ISSUE TITLE
Decrypted images do not conform to m.image

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#6832]
### Description

There's a difference between the decrypted event content from an image sent in an encrypted room versus a non-encrypted room.

Non-encrypted:

```
{
  "origin_server_ts": 1527846842270,
  "sender": "@andrewm:amorgan.xyz",
  "event_id": "$15278468421020aTwQo:amorgan.xyz",
  "unsigned": {
    "age": 46,
    "transaction_id": "m1527846842244.1155"
  },
  "content": {
    "body": "carolyn-smaller.jpg",
    "info": {
      "mimetype": "image/jpeg",
      "thumbnail_info": {
        "mimetype": "image/jpeg",
        "h": 189,
        "w": 153,
        "size": 8593
      },
      "h": 189,
      "thumbnail_url": "mxc://amorgan.xyz/QbWuyVJksRZokwSgtfhUarPv",
      "w": 153,
      "size": 10967
    },
    "msgtype": "m.image",
    "url": "mxc://amorgan.xyz/RRHERkBHFpYSDvteOCDOQskn"
  },
  "type": "m.room.message",
  "room_id": "!jvaOtgjswhzJGxFLEK:amorgan.xyz"
}
```

Decrypted:

```
{
  "type": "m.room.message",
  "content": {
    "body": "carolyn-smaller.jpg",
    "info": {
      "size": 10967,
      "mimetype": "image/jpeg",
      "thumbnail_info": {
        "w": 153,
        "h": 189,
        "mimetype": "image/jpeg",
        "size": 8593
      },
      "w": 153,
      "h": 189,
      "thumbnail_file": {
        "v": "v2",
        "key": {
          "alg": "A256CTR",
          "ext": true,
          "k": "7Cab6Y9QWJm-e8dror6pUkWz2CIiisMO3xnTirA-E_4",
          "key_ops": [
            "encrypt",
            "decrypt"
          ],
          "kty": "oct"
        },
        "iv": "ApFZtBT8WFoAAAAAAAAAAA",
        "hashes": {
          "sha256": "jLFI9gorPnAxKFbAF1+P0XuIb0W5mn8dc9sB+15FIyU"
        },
        "url": "mxc://amorgan.xyz/mCMPZDBgvKCipPNUuurenByq",
        "mimetype": "image/jpeg"
      }
    },
    "msgtype": "m.image",
    "file": {
      "v": "v2",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "cHHk4WpvvxfX5ZFiCgEWGkLyYwsPDXb2FOTgQ1E5oKo",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "iv": "GQDWG8eVe8kAAAAAAAAAAA",
      "hashes": {
        "sha256": "qdXODimf3OPsjnkWBOQxZhhw4jjKSwKsXMY7y/HTrH8"
      },
      "url": "mxc://amorgan.xyz/YIZRftLvxgKumrhBrSWyZWHe",
      "mimetype": "image/jpeg"
    }
  }
}
```

Accessing the `url` for a non-encrypted image is `event.content.url`, whereas for a decrypted image is `event.content.file.url`, which shouldn't be the case.

The bug appears when you forward a decrypted image from an encrypted room to a non-encrypted room. Quick solution is to transform the event so that it conforms when sending from encrypted -> non-encrypted rooms. Speccing this all out would help avoid these issues as well.

**Comment by lampholder** [comment]
I don't know much about this, but it certainly feels like a decrypted image event should be functionally the same as an unencrypted image event, unless there's a good reason for this not to be the case.

So I think the event format discrepancy is nasty, but I'm triaging as P2 minor because this won't affect many users.

**Comment by turt2live** [comment]
Arguably it should be higher priority given it's technically non-compliant with the spec.

**Comment by uhoreg** [comment]
This is now part of the spec (https://matrix.org/docs/spec/client_server/r0.6.0#extensions-to-m-message-msgtypes).  Presumably the reason that it's different is that for encrypted files, the URL by itself is not useful.  Since what Riot does is spec-compliant, I'm closing this, and if there are any disagreements about whether it should be made consistent, then it should be opened as a bug in matrix-doc.
