### ISSUE TITLE
Backspace in draft makes view jump around

### ISSUE THREAD

**Issue by mordae** [vector-im/riot-web#6836]
### Steps to reproduce

- I input first paragraph of http://lipsum.com/ generated text into the draft field.
- I move cursor to the first line.
- I delete a single letter of the second word.
- View shows the ending of the draft instead of the cursor area.
- I input a single letter and the view jumps back.

### Version information

For the web app:

- **Browser**: Firefox 59
- **OS**: Fedora Linux
- **URL**: both http://riot.im/app/ and http://riot.im/develop/

**Comment by lampholder** [comment]
This is a dup of https://github.com/vector-im/riot-web/issues/6825

There's a reimpl of the composer (using slate.js instead of draft.js) in flight, so hopefully that will wrap up a lot of the issues like this.
