### ISSUE TITLE
Re-request keys does not work

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#6838]
### Description

I cannot make re-request work on riot-web. I have similar a issue as #6593. But I cannot provide steps to reproduce:

- riot-web A has all keys in an e2e room
- the user logs in on riot-web B
- riot-web A displays the incoming key request dialog. The user ignores the request
- the user re-requests the keys on riot-web B

-> Nothing happens on riot-web A. I expected to see the incoming key request dialog again.

Discussion at https://matrix.to/#/!HCXfdvrfksxuYnIFiJ:matrix.org/$15281228777104CHVyN:matrix.org

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox
- **OS**: macOS
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Interesting - I'm not aware of our having changed anything here recently.

**Comment by manuroe** [comment]
On mobile, we have implemented a state machine a bit different for the outgoing request: https://github.com/matrix-org/matrix-ios-sdk/blob/48142dcd96305d1e4a313b8b459cd1d1fa5962ea/MatrixSDK/Crypto/KeySharing/Data/MXOutgoingRoomKeyRequest.h#L19-L43

The main idea is to make a new request with a different id than the one we cancel.

**Comment by drue** [comment]
Broken for me too.  It wouldn't be so bad if Riot didn't blow away all the key material every time my computer runs out of disk space, which happens whenever I close my laptop for more than a couple hours because OSX dumps RAM to disk.

**Comment by dkasak** [comment]
I'm experiencing this too. It's particularly annoying because sometimes riot-desktop freezes and I have to kill it, which makes it lose all state (I have to log in again and there is no key material).

**Comment by neilalexander** [comment]
It seems that Riot, when clicking `Re-request keys`, is actually sending cancellations but not sending new key requests. I see this in the Seaglass log when rerequesting keys from Riot:
```
2018-09-10 13:59:59.790736+0100 Seaglass[62658:76429929] [MXIncomingRoomKeyRequestManager] processReceivedRoomKeyRequestCancellation: m.room_key_request cancellation for @neilalexander:matrix.org:BETLCMSZCJ (id m1536584093764.19)
2018-09-10 13:59:59.791034+0100 Seaglass[62658:76429929] [MXIncomingRoomKeyRequestManager] handleKeyRequest: Already cancelled this key request, ignoring
```

**Comment by uhoreg** [comment]
This should now be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/850 and https://github.com/matrix-org/matrix-js-sdk/pull/855
