### ISSUE TITLE
can't access the last items of the message context menu if the message is at the bottom of the timeline

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6839]
please can we fix this at last and reposition the menu or make it scrollable?

![image](https://user-images.githubusercontent.com/8582858/40976615-8c4b92ea-68c6-11e8-815b-2e26c0de7390.png)

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/3792
