### ISSUE TITLE
Hide deleted messages on desktop client

### ISSUE THREAD

**Issue by J316** [vector-im/riot-web#6840]
On the Linux desktop client I see an empty line every time I delete a message, this doesn't happen on Android. It is annoying because if I call a lot I get a lot of notifications for call start and call end, and even if I delete them I see empty lines and the history ends up being a mess.

**Comment by t3chguy** [comment]
Its an option.
![image](https://user-images.githubusercontent.com/2403652/40981174-3b70abe2-68d2-11e8-9765-bf29133df9c4.png)

**Comment by J316** [comment]
An option to hide call start and end without deleting the messages all the time would be useful
