### ISSUE TITLE
Deploy-specific riot config files don't override defaults

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6843]
When you start up a riot.im on example.im it checks for a config file `config.example.im.json`. However, if it finds this, it uses it as the only config file (rather than falling back on `config.json` for defaults).

For running multiple homeservers, it would be useful if config.json could provide the defaults and the deploy-specific file have just the deploy-specific overrides.

**Comment by turt2live** [comment]
copy/pasting from the PR for visibility (and because I missed this issue somehow):

fwiw, this is a thing I wrote: https://github.com/homeserver-today/react-sdk-config-server

The use case for #6843 is homeserver hosting, and react-sdk-config-server is specifically written for that use case :p

**Comment by t3chguy** [comment]
Clearly this issue isn't actually wanted to be solved.
