### ISSUE TITLE
email addresses should be sanity-checked in the invite box

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#6854]
syntactically invalid email addresses should not result in an invite.  e.g. see https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1528485460415135KiZGp:matrix.org

**Comment by turt2live** [comment]
for onlookers: the email address in question is `@user@matrix.org`

**Comment by lampholder** [comment]
Email address validation can be tricky, but yes - it's a crappy UX to let users type in @user@matrix.org and not feed back that it probably won't work.

**Comment by lampholder** [comment]
Perhaps we could use something like https://github.com/mailcheck/mailcheck too (though that wouldn't solve this specific problem). Email invites are probably worth sinking some time it to give the best UX we can - it's very easy for the inviter to mistype and get zero feedback ever that their invite isn't going to make it.

**Comment by ara4n** [comment]
we could also provide a service on synapse which does a callout to check that the target MTA accepts a RCPT TO for this address, although obviously this might be prone to abuse.

Better than nothing to do a simple regexp check on the email validity (or even use the fugly official RFC822 regexp)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2338
