### ISSUE TITLE
Quoting multiple messages ends up in wrong order

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#6855]
Expectation:
If I quote message A first, then, without sending my message in between, quote message B, they should be arranged "message A, message B" in my text to send.

Actual behaviour:
If I quote message A first, then, without sending my message in between, quote message B, they are arranged "message B, message A" in my text to send.

Seen in Riot Web 0.15.4.

**Comment by lampholder** [comment]
Huh, it never even occurred to me to try that!

You're right - clicking 'quote' should probably _append_ rather than prepend the quoted message text to whatever's already in the composer.

**Comment by ara4n** [comment]
i think this is fixed in the slate branch (matrix-org/matrix-react-sdk#1890) ftr.

**Comment by t3chguy** [comment]
It is
