### ISSUE TITLE
kickbans are not properly shown

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6856]
if you ban someone after they've left it says they've left again, rather than the kick/ban msg

**Comment by turt2live** [comment]
If this is about the event in #riot, it looks like what happened is the event was `leave -> leave+reason` . Was the intention to have it be `leave -> ban`?

**Comment by ara4n** [comment]
true; i think i fatfingered and kicked rather than banned. so this is probably a nonbug.
