### ISSUE TITLE
Decrypting PDFs ('regular files') looks like it's doing nothing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6859]
### Description

Clicking "Decrypt" on a PDF (or really any file a few MB in size) appears to do nothing, despite the decryption kicking off. Maybe a spinner or some sort of animation to tell the user that their click was heard and something is happening would help?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/2749
