### ISSUE TITLE
Using BEPO keyboard layout, inserting non-breakable space moves cursor at beginning of line

### ISSUE THREAD

**Issue by OlivierNicole** [vector-im/riot-web#6862]
### Description

Pressing Shift + space during typing moves the cursor at beginning of the line. This is a problem for those of us, like me, who use Shift+space to insert a non-breaking space. The “bépo” keyboard layout encourages this and it is very hard to lose the habit.

Moreover, I don't understand whether this cursor move is a bug or a feature.

**Edit:** It only happens when using Shift+space in the bépo layout (inserting a non-breakable space using the Compose key doesn't trigger this behaviour). The cursor must be at the end of the text being typed, otherwise it doesn't happen.

### Steps to reproduce

- In Riot-web, try pressing Shift+space while typing a message.

### Version information

- **Platform**: web, but also Riot-desktop 0.15.4
- **Browser**: Firefox 60.0.1
- **OS**: Arch Linux

**Comment by t3chguy** [comment]
for me shift+space just inserts a space
so might be something electron-on-linux related

**Comment by Half-Shot** [comment]
Checked Electron Linux and I get the same result as @t3chguy. Sounds environment specific to me.

**Comment by OlivierNicole** [comment]
Indeed, I just checked, this only happens with the Bépo keyboard layout. When inserting a non-breakable space using the Compose key this behaviour doesn't show.

**Comment by lampholder** [comment]
Hopefully this will be fixed incidentally when the new slate.js composer lands.

**Comment by OlivierNicole** [comment]
@lampholder Do you have any idea where the problem is from? Is it in Electron? So I know which people to let know about this.

**Comment by ArchangeGabriel** [comment]
I’m on Linux, using bépo as well, and I don’t have this issue.

**Comment by OlivierNicole** [comment]
@ArchangeGabriel Well, I'm confused. I have this issue on two different operating systems (namely Arch and Ubuntu).

**Comment by hidrarga** [comment]
I also have this issue on OpenSUSE 42.3

**Comment by hidrarga** [comment]
This bug seems to be fixed for me :) (Riot web v0.17, OpenSUSE 42.3)

**Comment by turt2live** [comment]
@OlivierNicole are you still seeing this on recent versions of Riot (0.17 or higher)?

**Comment by OlivierNicole** [comment]
Hi, sorry @ArchangeGabriel for not replying.
@turt2live This is fixed for me as well no 0.17!

**Comment by turt2live** [comment]
Awesome! Thank you. Closing as magically fixed then :)
