### ISSUE TITLE
Devtools close button display is broken

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6865]
![screen shot 2018-06-13 at 10 30 14](https://user-images.githubusercontent.com/986903/41342702-ca6b965e-6ef4-11e8-9a38-dd2e857a515d.png)

**Comment by t3chguy** [comment]
Cannot repro :(
![image](https://user-images.githubusercontent.com/2403652/41342922-400bd496-6ef5-11e8-9769-882158d7d89d.png)

**Comment by dbkr** [comment]
Actually it looks like this is only in my dev version, sometimes.

**Comment by t3chguy** [comment]
fun :(
