### ISSUE TITLE
load minified matomo js

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#6870]
rather than the full-fat one

**Comment by lampholder** [comment]
Are we really not already doing this?

**Comment by lampholder** [comment]
Also - how big is the matomo js? I really hope it's not large :\

**Comment by turt2live** [comment]
It looks like the file is already minified (and the matomo docs confirm this):
![image](https://user-images.githubusercontent.com/1190097/41543833-e7cf4a54-72d4-11e8-9861-9c4f7552f833.png)

**Comment by t3chguy** [comment]
- Weird I could have sworn we were loading http://piwik.riot.im/js/piwik.js which looks non minified to me

**Comment by turt2live** [comment]
That's the same URL I have. Maybe Chrome is helping?

**Comment by t3chguy** [comment]
Yup, its an annoying URL
its http://piwik.riot.im/js/piwik.js (full) vs http://piwik.riot.im/piwik.js (minified) [note the missing `/js`
so its actually fine

**Comment by turt2live** [comment]
re: the url being subtly different
![giphy 2](https://user-images.githubusercontent.com/1190097/41796052-30ee98e8-7622-11e8-9363-0868ba027be0.gif)
