### ISSUE TITLE
Add option to send by ctrl-enter

### ISSUE THREAD

**Issue by Eisfunke** [vector-im/riot-web#6871]
Normally, riot sends a message when pressing enter, newlines can be added by shift-enter.

It'd be great if Riot could get an option to add newlines by enter and send the message by ctrl-enter instead. This would help people using many newlines (like me) and people who often send messages accidentally when trying to add a newline (also like me).

I got this idea from the Telegram desktop client, which has an option like that.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5006.
