### ISSUE TITLE
Major Editor Weirdness

### ISSUE THREAD

**Issue by jcgruenhage** [vector-im/riot-web#6873]
sorry for the title, no idea how else to say it.

### Description

The editor on /develop is very broken. Letters appear out of order, but when hitting send, sometimes, even though the text in the box was wrong, the right things are sent.

### Steps to reproduce

I don't have exact steps here sadly, but it seems to happen multiple times per minute.

Describe how what happens differs from what you expected.

Log: sent

### Version information

https://github.com/vector-im/riot-web/commit/9dd37ac9e270

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 60.0.1
- **OS**: Fedora
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
Probably caused by https://github.com/matrix-org/matrix-react-sdk/pull/1961

**Comment by lampholder** [comment]
This is fixed (with the rollback)
