### ISSUE TITLE
Regression: Unban button has gone big again

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6876]
![image](https://user-images.githubusercontent.com/1190097/41423924-d902e6fc-6fb9-11e8-9cf1-1a6ca3bc85f2.png)

on develop

**Comment by t3chguy** [comment]
I'm not sure how this ever worked, the buttons in UserSettings for delete devices are not AccessibleButtons :(

**Comment by turt2live** [comment]
This looks slightly worse when there's multiple people:
![image](https://user-images.githubusercontent.com/1190097/42292990-dd5776f2-7f93-11e8-951e-de8e19380a37.png)

**Comment by turt2live** [comment]
Fixed
