### ISSUE TITLE
status.im theme pulls <something> from status.im on each client startup, discloses usage to a 3rd party

### ISSUE THREAD

**Issue by schwindp** [vector-im/riot-web#6885]
### Description

Using Riot on MacOS I see that using the status.im theme my client does pull content (CSS?) from status.im on each startup

### Steps to reproduce

- set client theme to 'status.im'
- have an application firewall
- close down and startup riot again
- see client trying to access status.im website on port 443

I'd rather not see the access on each startup as this discloses usage information to a 3rd party. Why not package the CSS with the client?

Log: not sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS
- **Version**: 0.15.4

**Comment by t3chguy** [comment]
As of https://github.com/vector-im/riot-web/pull/6317/files I cannot reproduce this, I see no references to `status.im` in the codebase other than https://github.com/vector-im/riot-web/blob/7f50fb302346fd338b1a3e70ce23bd2203eed8cb/src/vector/index.js#L267 (and one below) it which only trigger on mobile browsers.

**Comment by MTRNord** [comment]
@t3chguy afaik there is a font I think that gets loaded from status.im

**Comment by t3chguy** [comment]
Yup you're right, weird that Find in Path failed to find it

![image](https://user-images.githubusercontent.com/2403652/41499840-6629ae96-717f-11e8-974b-c7f790728ed1.png)

**Comment by t3chguy** [comment]
in this case I'm not sure if legally we can package the font without purchasing additional licenses for it.
https://sharptype.co/typefaces/post-grotesk/buy/

**Comment by jryans** [comment]
The Status theme is being removed.
