### ISSUE TITLE
Missing messages.

### ISSUE THREAD

**Issue by gupta2140** [vector-im/riot-web#6886]
I use Riot client for freenode (webapp on mozilla firefox, chrome and app on android) and every night I miss messages from any one user (randomly).
It may sound strange but I receive messages from all others, but miss all the messages from any 1 user (randomly changes every night).

Also it happens everyday only during night and late morning, i.e 10 p.m to 8 a.m (in India, UTC +5.30).
It seemed to be fixed almost a month ago, but again started to happen after some update.

Kindly look into the issue.

### Version information

- **Platform**: web (in-browser) and android app.

For the web app:

- **Browser**: Firefox Quantum(60.0.2)
- **OS**: Ubuntu
- **URL**: / riot.im/app /

For the android app:
- **OS**: Android 7.1.2

**Comment by t3chguy** [comment]
Riot is a matrix client and the IRC users get bridged via matrix-appservice-irc. Confirm if these missing messages are visible in other clients, if they also are not then close this issue and report this in the `#irc:matrix.org` room on Matrix or `#matrix-irc` on Freenode

**Comment by gupta2140** [comment]
Yes these messages are visible in other clients. Sometimes when I feel I'm missing some messages, I temporary login to other client (like webchat.freenode.net or kiwiirc) and those messages are visible there.

**Comment by t3chguy** [comment]
Yes but `webchat.freenode.net` and kiwiirc are IRC clients, which doesn't make this a Riot bug and is more likely to be a bridging issue, which is why I edited my original comment to add `Matrix` specifier

**Comment by gupta2140** [comment]
okay thanks. I should report this bug on #matrix-irc freenode channel right?

**Comment by t3chguy** [comment]
If those messages also don't show up in other Matrix clients yes

**Comment by gupta2140** [comment]
Thank you!
