### ISSUE TITLE
broken displayname yields no visible SenderProfile

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#6896]
looks like a broken emote

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/41509686-94ca6c10-724f-11e8-843d-d16b9829f99c.png)

**Comment by lampholder** [comment]
@t3chguy do you know how the displayname was broken?

**Comment by t3chguy** [comment]
he set it to a zero width non joiner char

**Comment by t3chguy** [comment]
I'd say this is potentially major, as someone could spoof someone else using this, if they changed their avatar to match the background colour
