### ISSUE TITLE
Message editor breaks when tabcompleting names

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#6899]
Steps to reproduce:
 * Start with a normal text entry area "Send a message (unencrypted)".
 * type "@to" and tab-complete to a name.
 * Display now shows " :" - the pill containing the name has dissappeared.
 * Press backspace twice, removing the ":" and " "
 * Text entry area is now entirely empty (no "send a mesage"), loses caret and is now un-clickable to add new text.
 * Clicking "M" button causes the box to recover by showing/unshowing the text formatted as markdown.
* At this point the caret is now available and text entry area can be deleted to get back to the "send a message prompt".

The issue is recoverable from, but is repeatable across channels and across tab-completed names, whether or not the tab completion is in the middle of the message or not (though the missing information in the middle of the message.

**Comment by jcgruenhage** [comment]
Also, while you can't see the pill, it is there. It appears upon sending.

**Comment by lampholder** [comment]
Anecdotally I feel like I'm seeing a lot of composer bugs suddenly :S

**Comment by lampholder** [comment]
This is only on /develop, not /app, so I'd hope we could track down the cause.
