### ISSUE TITLE
Click to mention has regressed

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6900]
Clicking on a SenderProfile (displayname above message) should insert a pill into the composer. This has regressed with an error message (when the composer is empty):
```js
Uncaught TypeError: Cannot read property 'getEntityAt' of undefined
    at Object.removeRange (DraftModifier.js:100)
    at removeTextWithStrategy (removeTextWithStrategy.js:39)
    at keyCommandPlainDelete (keyCommandPlainDelete.js:27)
    at onKeyCommand (editOnKeyDown.js:46)
    at editOnKeyDown (editOnKeyDown.js:141)
    at DraftEditor.react.js:146
...
```

If the composer has text in it, it appears to insert whitespace but when switching between rich mode and markdown mode, markdown pills might appear. Or the composer might be broken until a room switch happens.

**Comment by michaelkaye** [comment]
Ah, see also #6899

**Comment by lukebarnard1** [comment]
This is probably because `MATRIXTO_URL_PATTERN` was changed by https://github.com/matrix-org/matrix-react-sdk/pull/1975/files#diff-43ba768343dac45fa03389f245f80e39R172.

cc. @t3chguy

**Comment by lukebarnard1** [comment]
Having heard the entire office complain, and given I think I know a fix, I'll go and fix this.

**Comment by t3chguy** [comment]
ah so yeah this is probably my fault with the regex accidentally removing a capturing group when instead I intended to remove the `|` and replace it with a capturing character group
