### ISSUE TITLE
Can't pick a langauge from the registration view

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#6901]
I'd imagine we have translated the registration page but I can't find anywhere that let's me select a language which seems to be a bit of a fail.

**Comment by t3chguy** [comment]
Its there on the login view:
![image](https://user-images.githubusercontent.com/2403652/41531539-8d67b404-72eb-11e8-96db-9f9d1ba32f0c.png)

**Comment by lampholder** [comment]
Right, so there on login but not on register. Doesn't look like too complicated a fix?

**Comment by t3chguy** [comment]
also missing from Forgot Password view
