### ISSUE TITLE
auto-complete on room name is broken

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6903]
I haven't tried display names. But basical start typing a name #syn and press tab and what you typed disappears, only the selection in the autocomplete is visible. Then there is no way to add the selected pill to the text, other than by pressing Enter.... which send the message.... When is Slate landing?

**Comment by turt2live** [comment]
@lukebarnard1 this is another issue fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1986

(confirmed fixed by myself)

**Comment by t3chguy** [comment]
Thanks for confirming @turt2live
