### ISSUE TITLE
Room uses user's avatar when no avatar is set

### ISSUE THREAD

**Issue by pkoziol** [vector-im/riot-web#6904]
### Description

I changed my avatar the first time (previously I had default letter on some background).
Suddenly my existing, pubic room (`#public:koziolek.biz`) also changed is image. My new room (`#riot-room-avatar-issue:koziolek.biz`) and it also uses my avatar.

### Steps to reproduce

- Have account without avatar

#### Part 1 - existing, public room

- Create room (anyone can join, anyone can view history, no messages yet, no avatar)
- Change your (user's) avatar
- **Riot uses user avatar instead of still using letter and color**
- Room history says:
  > koziolek set a profile picture.
  > koziolek removed the room avatar.

#### Part 2 - new room

- Hava account with recently changes avatar (for the first time)
- Create new room
- **Riot uses user avatar from the start for instead of still using letter and color**
- Room history says:
  > koziolek joined the room.
  > koziolek made future room history visible to all room members.
  > koziolek changed the room name to nowyyy.
  > koziolek removed the room avatar.
  > koziolek changed the room avatar to
  > koziolek removed the room avatar.
  > koziolek made future room history visible to anyone.
  > koziolek changed the room name to riot-room-avatar-issue.

Log: sent

Screenshot:
![riot-room-avatar-issue](https://user-images.githubusercontent.com/3846677/41534933-aefd2580-7300-11e8-9e60-09fa0f5673f4.png)

As you can see, my other existing, private (only for invited) room was not affected.

### Version information

- **Platform**: riot-web version: 0.15.5
- **Browser**: Firefox 60.0.2
- **OS**: Windows 10
- **URL**: riot.im/app

**Comment by Half-Shot** [comment]
This is expected behavior in that rooms where you are the only member will show your avatar. Adding more users will make it revert to showing the room initials as a avatar. The room avatar is actually still not set, we just show it as the user's by default.

**Comment by pkoziol** [comment]
Hah, this is little surprising, but I guess most people would not be alone in rooms. Thanks!
