### ISSUE TITLE
Riot Desktop 0.15.5 on MacOS fully weddged due to backend URL being changed

### ISSUE THREAD

**Issue by ssbarnea** [vector-im/riot-web#6906]
Apparently Riot.im client on MacOS become impossible to use because when it starts it tries to connect to a backend that no longer exists and when trying to get into Settings, it does endup with an endless loop.

Apparently there is no information published regarding how to wipe all its settings/preferences and start from zero.

**Comment by lampholder** [comment]
I can't reproduce this with the electron client running on my mac, but it would be good to publish instructions on how to wipe an install completely and start from scratch.

**Comment by t3chguy** [comment]
delete `~/Library/Application Support/Riot` (pretty sure the Riot bit at the end is Riot, could be Riot.app or similar though)

**Comment by ssbarnea** [comment]
I can confirm that doing a ``rm -rf ~/Library/Application\ Support/Riot`` allowed me to reconfigure the Riot client. Still, we need a workaround.
