### ISSUE TITLE
Irrelevant command suggestions stay present when writing out a command

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6907]
### Description

![image](https://user-images.githubusercontent.com/1190097/41544989-60af7c94-72d7-11e8-98c5-557e2417a403.png)

If I'm typing `/me`, I'd love to see the syntax for `/me`, not the others. It's also a bit scary when you move your mouse over the other suggestions and have your command destroyed (it comes back if you go to `/me` again).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 67
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
so this sadly is what the FuzzyMatcher thinks matches `/me` :(

**Comment by turt2live** [comment]
How insane is it to suggest that if you type `/command` with some arguments that it does a strict match?

**Comment by t3chguy** [comment]
yeah that's what imma make it do now, if its a valid command

**Comment by t3chguy** [comment]
made it so that as soon as the input has a space it goes into strict matching

**Comment by lukebarnard1** [comment]
So I'm still experiencing this. It's slightly worse when typing `/me is talking about Some*tab*` -> `/me ` :upside_down_face:

**Comment by t3chguy** [comment]
I'll be home soon and look at it, I didn't consider tab would work again that's not fun

**Comment by t3chguy** [comment]
@lukebarnard1 the missing slash is the entire issue, I managed to lose a slash during the consolidation
