### ISSUE TITLE
CORS request rejected: https://matrix.org/_matrix/client/r0/publicRooms?

### ISSUE THREAD

**Issue by exarkun** [vector-im/riot-web#6913]
### Description

Attempting to look at the room directory eventually fails with a pop up error:

```
Failed to get public room list
CORS request rejected: https://matrix.org/_matrix/client/r0/publicRooms?
```

### Steps to reproduce

- Load the riot.im web interface.
- Click the bottom left "Room directory" button
- wait a handful of seconds

Describe how what happens differs from what you expected.

I expected to see a list of rooms and be able to pick one to join.

Log: sent    

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Ubuntu 17.10
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
CORS is hiding the underlying error. Try to reproduce with the network tab of your browsers developer tools to get us the actual error. Most likely it's a timeout due to matrix.org being slow.

**Comment by exarkun** [comment]
The error occurred repeatedly around the time I reported it.  However, no error is occurring at this time.

**Comment by t3chguy** [comment]
This will have just been matrix.org timing out then.

**Comment by t3chguy** [comment]
There are other public servers btw https://www.hello-matrix.net/public_servers.php

**Comment by devcline** [comment]
is it possible to make more friendly message , like Server Timeout ⏳

**Comment by t3chguy** [comment]
But it's not possible to know whether it timed out or the server is misconfigured/failing and not serving the appropriate CORS header.

**Comment by devcline** [comment]
well maybe "Server is unresponsive (CORS request rejected: .... )

**Comment by t3chguy** [comment]
But it could be not the fault of the server and instead of a firewall or proxy/reverse proxy misconfiguration
