### ISSUE TITLE
Room names are not displayed - Firefox

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-web#6919]
### Description

When resuming the Firefox browser, sometimes the room names are empty and the scrollbars are white. F5 fixes the issue

### Steps to reproduce

- Not sure this is the smallest way to get the issue
- open Riot on Firefox
- Put Firefox on background
- Lock the Mac
- try to view Riot

<img width="1495" alt="screen shot 2018-06-22 at 14 08 46" src="https://user-images.githubusercontent.com/3940906/41776032-809af39c-7626-11e8-83f0-73afc84ee32b.png">

### Version information

- **Platform**: web (in-browser)?
- **Browser**: Firefox 60.0.1 (and previous)
- **OS**:  macOS
- **URL**: riot.im/develop

**Comment by MTRNord** [comment]
You also seem to have wrong scrollbars 🤔

**Comment by turt2live** [comment]
My best bet is you're missing some CSS somewhere. Did an extension of some kind block it by chance?

**Comment by bmarty** [comment]
@MTRNord I called them "slides", my bad. Description updated

**Comment by MTRNord** [comment]
@bmarty oh you wrote that :) I missed that line on mobile thats why I made that comment in the first place

**Comment by tidux** [comment]
This seems to be a MacOS specific bug.  I can't reproduce it with Firefox on Linux or Windows.

**Comment by bmarty** [comment]
@tidux I have not seen this issue on any other website (yet?)

**Comment by lampholder** [comment]
I think this is related to the issue reported by @rxl881 and possibly @neilisfragile (with a placeholder https://github.com/vector-im/riot-web/issues/6696).

@rxl881 at least experienced the problem on his mac when plugging into an external monitor - @bmarty did you use an external monitor at all?

**Comment by lampholder** [comment]
`minor` because despite the carcrash aesthetic it does seem to be rare and is easy to overcome.

**Comment by rxl881** [comment]
In addition to plugging in external monitors, I have also seen this and similar issues when plugging in external mice (and possibly keyboards). This is especially true for the scrollbar bug shown in the above screenshot.

**Comment by bmarty** [comment]
@rxl881 , yes, I use an external monitor

**Comment by lampholder** [comment]
Rare inasmuch as I'm not seeing many complaints so I'm guessing the overall incidence is low. It looks easy to reproduce, but perhaps most riot users aren't docking/undocking their laptops on a regular basis.

> I have also seen this and similar issues when plugging in external mice (and possibly keyboards).
GNH computers are terrible. Why would/how could peripherals impact display in this way? 

Btw @rxl881 are you also on firefox?

**Comment by rxl881** [comment]
No (I'm on Chrome) @lampholder.

I believe that the peripherals muck up the lib that we use for scrollbars (Gemini or something, IIRC). @dbkr will probably know something about this?

**Comment by turt2live** [comment]
I believe we fixed this in the redesign when we saw it.
