### ISSUE TITLE
Groups autocomplete pops up in the middle of a sentence

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6929]
I tried typing `Person+crew` and at the `+c` I got a pop up. Surely that shouldn't happen. 

Haven't tested aliases or users, but they probably have the same issue.

**Comment by t3chguy** [comment]
Yup
![image](https://user-images.githubusercontent.com/2403652/41824521-68d8f134-7809-11e8-95b4-57b0cd123c81.png)

Should be trivial with a word boundary added to the regexp tho

**Comment by t3chguy** [comment]
(the capture group wasn't actually being used)
