### ISSUE TITLE
Wishlist: self-hosted jitsi server

### ISSUE THREAD

**Issue by megrf** [vector-im/riot-web#6930]
Please make possible integrating riot with a self-hosted jitsi server instead of official jitsi server (as today).

**Comment by Half-Shot** [comment]
This sounds like a riot-meta issue, given it's essentially something scalar needs to provide the option for.

**Comment by MTRNord** [comment]
Also one option might by to host your own matrix-dimension for now. But I am not sure how urgent you need it
