### ISSUE TITLE
Tab completing @username mentions

### ISSUE THREAD

**Issue by jcgruenhage** [vector-im/riot-web#6931]
People are used to mention people with @username from all the other services (telegram, discord, gitter, slack), so the tab completion should probably try to ignore a leading "@" during completion.

**Comment by t3chguy** [comment]
the difficulty there is then what if I want to explicitly autocomplete by someone's MXID?

**Comment by jcgruenhage** [comment]
Maybe try both and join the list of results?

**Comment by t3chguy** [comment]
That is what I presumed you were suggesting, but thats not
> explicitly by someone's MXID

That's by MXID/Displayname

**Comment by jcgruenhage** [comment]
Oh I see what you mean... Well what about selecting the mxid entry from that list then? That should work, right?

**Comment by t3chguy** [comment]
well I mean in the end they always get completed to a pill which has both MXID and Displayname (only the latter actually shown)
its just force of habit that I tend to autocomplete using people's MXIDs rather than their Displaynames

**Comment by jcgruenhage** [comment]
well you could also build in a thing where for explicitly doing mxid's is `\@localpar<tab>` if you really need that

**Comment by t3chguy** [comment]
to be fair, for consistency with other autocompletes, `@` should complete on both name and MXID, like room and community completers do

**Comment by turt2live** [comment]
This sounds like a duplicate of https://github.com/vector-im/riot-web/issues/6782 (which is still a question?)

**Comment by jcgruenhage** [comment]
@turt2live yes, it is a duplicate, I had not found that. Thanks!

**Comment by jcgruenhage** [comment]
(Forgot to close this yesterday)
