### ISSUE TITLE
clicking 'copy' in the 'share' window doesn't copy to clipboard

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6933]
it displays the 'Copied!' message but when pasting somewhere the clipboard is empty

**Comment by lukebarnard1** [comment]
@AmandineLP could you please provide your OS and browser, browser version? 

Also, where are you pasting the clipboard to?

**Comment by lampholder** [comment]
This isn't universal - copy+pasting works on Chrome on my mac/ubuntu machines.

**Comment by t3chguy** [comment]
works on my chrome/windows machine
the `Copied!` message only pops up if the browser claims the copy was successful which makes this even harder to debug as there won't be anything in a rageshake

**Comment by t3chguy** [comment]
If anyone has reproduced this recently please speak up.
