### ISSUE TITLE
Disabling desktop notifications gives a nagbar to enable desktop notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6937]
### Description

In Riot/Desktop (not tested in /Web) if you open your user settings and uncheck `[x] Enable desktop notifications`, you'll be presented with a nagbar to enable desktop notifications.

Would be nice if the bar respected my decision a little bit by not appearing :)

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 0.15.5

**Comment by t3chguy** [comment]
As far as I can tell it affects anyone who enabled notifications before https://github.com/matrix-org/matrix-react-sdk/commit/6f674f21f652699da0d0b9855fcfa061f713586f
