### ISSUE TITLE
Room settings stay open when leaving a room via settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6939]
### Description

After a leave completes Riot picks another room to look at. If you leave the room via the room settings, the room settings will remain open for the new room you're navigated to. The backdrop disappears though.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 67
- **OS**: Windows 10
- **URL**: riot.im/develop and /app

**Comment by lampholder** [comment]
Is this a regression or did I just never notice it before? I feel like it's a regression.

Actually, the settings that are open for the next room seem (on my chrome/ubuntu at least) to occupy an oddly shrunken section of the screen real estate:

![image](https://user-images.githubusercontent.com/1922197/41913862-64d822b2-7949-11e8-9b31-c7f703441bb7.png)

So yeah, feelsl ike a regression and is certainly v. glitchy.
