### ISSUE TITLE
My historical section is missing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6941]
### Description

![image](https://user-images.githubusercontent.com/1190097/41883925-3217f26c-78ae-11e8-95ea-1220f7df48e3.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 67
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I'm not sure what we want the behaviour to be exactly - I appreciate the clarity of empty headers being invisible, especially when I filter by community, but at the moment we allow users to change a room's dm/room favourite/low-priority status by dragging and that's only possible with a drag target.

**Comment by t3chguy** [comment]
@lampholder those won't vanish because the droptarget means the roomsublist is not empty, but the Historical roomsublist had no text/anything when it was empty, only a Spinner when you clicked on it which yielded either rooms or empty space

**Comment by t3chguy** [comment]
oh I see what you mean, they *can* vanish when querying by searchFilter, so its a different break than Historical

**Comment by turt2live** [comment]
In the screenshot there's no filtering whatsoever going on. The section used to be there, but it disappeared some time yesterday.

**Comment by t3chguy** [comment]
After discussion, this behaviour is going behind an opt-in flag as well as fixing Historical when it is enabled

**Comment by turt2live** [comment]
Is this actually a feature? I'm a bit concerned that the actual bug is lost in translation.

**Comment by t3chguy** [comment]
No sorry probably my bad explanation.
The roomsublist auto-hide behaviour will be opt-in,
Your bug is about the roomsublist-auto-hide behaviour, the PR above fixes the bug but the behaviour will still be opt-in

**Comment by turt2live** [comment]
There is no PR above.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/2016

**Comment by t3chguy** [comment]
Faaaaar above

![image](https://user-images.githubusercontent.com/2403652/41927827-3496b830-796b-11e8-84e5-ef829f0e8430.png)

**Comment by turt2live** [comment]
When was this introduced? It seemed like an unintended bug which is why I reported it. I don't actually mind the behaviour.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/1954

**Comment by t3chguy** [comment]
it is unintended
