### ISSUE TITLE
Our (opt-in, anonymous) analytics are missing the platform type (electron/web) off many (but not all) of the metrics.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6946]
This makes things confusing.

**Comment by lukebarnard1** [comment]
@lampholder do you happen to know which metrics are present? It might be useful for debugging this.

**Comment by lampholder** [comment]
All I know is what we saw the other day - that there were stats from what looked like Electron deploys which hadn't been tagged as Platform Electron

**Comment by t3chguy** [comment]
I had a quick look through and could not find any instances of this :(

**Comment by t3chguy** [comment]
This is fixed with my rewrite
