### ISSUE TITLE
Use `position: sticky` on RoomSubList headers

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6950]
Now that most browsers support `postion: sticky`, we should use it to position RoomSubList headers instead of using JS. We could also use this for sticky date headers in the timeline.

https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky

**Comment by lampholder** [comment]
![screen shot 2018-06-29 at 08 48 16](https://user-images.githubusercontent.com/1922197/42080033-3edefa22-7b79-11e8-98a3-6fd64654a54d.png)

Those supported browser version numbers all appear to be in the dim and distant past, so perhaps it is time to experiment with this.

**Comment by turt2live** [comment]
We have changed the layout completely
