### ISSUE TITLE
Member list seems to reorder itself (Possibly: sometimes higher power first, sometimes online first)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6953]
This is at least my experience on a federated homeserver with presence enabled, using riot.im/develop.

**Comment by lampholder** [comment]
I've flagged this 'cannot-reproduce' just to represent that we're not 100% confident in the nature of this bug yet - @lukebarnard1 to add more details as he continues to experience it. Other people please let us know if you're seeing the same thing.

**Comment by lampholder** [comment]
I updated the title to be a bit more generic, hopefully to catch the attention of anyone who is finding their member list updating/reordering suprisingly.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/49611686-84cc7000-f95f-11e8-85ba-d2215de9da78.png)

If I understand the issue correctly, toml should be at the top.

**Comment by turt2live** [comment]
for clarity:

> on a server where presence is disabled, it should be ordered by PL only. on a server *with* presence working, it should be ordered by presence and then PL

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2381 (for experimental)
