### ISSUE TITLE
scalar fails to display

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#6954]
JS console says: 'Refused to display 'https://scalar.vector.im/?...' in a frame because it set 'X-Frame-Options' to 'sameorigin'.  ping @rxl881 ?

**Comment by rxl881** [comment]
It sounds like this might be affecting riot desktop (electron) clients. 

![screen shot 2018-06-27 at 22 54 57](https://user-images.githubusercontent.com/6763606/42001845-29399a14-7a5d-11e8-81a9-465d690d74e6.png)

**Comment by Half-Shot** [comment]
I've also been affected by this while trying to debug @chevdor's issue. Works fine on Android and the browser version for me.

**Comment by chevdor** [comment]
@Half-Shot thanks for CCing me. I can also confirm it works on iOS.

**Comment by fabrixxm** [comment]
https://scalar.vector.im gives me 502 from cloudflare

the `x-frame-options: SAMEORIGIN` header is in cloudflare response headers

**Comment by lampholder** [comment]
Part of the scalar infrastructure had died :(

It looks like the X-Frame-Origins business was cloudflare trying to render its error page.

This has now been restarted and we're putting in place some more comprehensive monitoring.

@uhoreg @fabrixxm can you test that it's working for you again when you get a chance? Thanks!

**Comment by fabrixxm** [comment]
works for me 👍

**Comment by chevdor** [comment]
Awesome, it works again indeed.

**Comment by uhoreg** [comment]
Yup, works for mee to.  Thanks, Rick and Tom.
