### ISSUE TITLE
A way to view the key of a device

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6955]
Currently the only way I can see the key of a device once I've verified it is to unverify it and click the verify button

**Comment by lampholder** [comment]
Is this the same usecase as https://github.com/vector-im/riot-web/issues/6095 ?

**Comment by t3chguy** [comment]
@lampholder 6095 is seeing all of your own keys easily, this is about seeing a peer's keys after verifying it

**Comment by Mikaela** [comment]
Is this a duplicate of https://github.com/vector-im/riot-web/issues/6676 and https://github.com/vector-im/riot-web/issues/2735 ?
