### ISSUE TITLE
setting topic and room name barely works any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6956]
if i try to set one after the other they seem to collide and cancel each other out, despite the UI telling me  that i'm setting it correctly.  Presumably related to slow remote echo

**Comment by lukebarnard1** [comment]
Sounds similar to https://github.com/vector-im/riot-web/issues/6019

**Comment by lukebarnard1** [comment]
I'd be interested to see if this improves after https://github.com/matrix-org/matrix-react-sdk/pull/2028

**Comment by lampholder** [comment]
It looks like this has a good chance of being fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2028

**Comment by turt2live** [comment]
Fixed
