### ISSUE TITLE
Connectivity lost status bar has regressed

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6958]
From M4tthew: ![](https://t2l.io/_matrix/media/v1/thumbnail/matrix.org/MzYLVkxZyaskASEBGvGndFvd?width=800&height=600)

**Comment by lampholder** [comment]
We've made some changes here to better render the GDPR error - @lukebarnard1 do you think that might have caused this regression?

**Comment by lukebarnard1** [comment]
Yep. This was https://github.com/matrix-org/matrix-react-sdk/pull/2025

**Comment by turt2live** [comment]
Presuming fixed due to PR being merged.
