### ISSUE TITLE
flag messages sent from 'only encrypt for verified devices' clients

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6959]
so that other recipients can guess that the uisi is a feature rather than a bug and display the right ux

**Comment by Half-Shot** [comment]
Related: https://matrix.to/#/!HCXfdvrfksxuYnIFiJ:matrix.org/$1530259455257zkrNL:half-shot.uk

**Comment by uhoreg** [comment]
fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1135
