### ISSUE TITLE
New --hidden functionality breaks riot desktop

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#6961]
I'm on 0.15.6 for Riot desktop.

* Ubunut 18.04, XFCE4 + Compiz

Launch with --hidden, the program never finishes loading and the interface is a "hall of mirrors" kind of deal where it draws what was behind it.
Launch without --hidden, program launches fine.
Looks like a regression to me D:

**Comment by t3chguy** [comment]
`--hidden` for you prior to this launched the app visible though, right? ISTR you having an issue with that

**Comment by BloodyIron** [comment]
Previously the --hidden flag launched it visible, not minimized.

**Comment by t3chguy** [comment]
so at least its just more comically broken now :D

**Comment by BloodyIron** [comment]
Well, it does "more" than before, just totally in the wrong direction. lol

**Comment by BloodyIron** [comment]
This bug is still happening as of the currently available version.

**Comment by BloodyIron** [comment]
Still getting this.

**Comment by BloodyIron** [comment]
Still getting this on my laptop, where "--hidden" doesn't minimise it to start, and it's not drawing the window correctly unless I minimise and maximise it again.

**Comment by salim-b** [comment]
This is also an issue on Ubuntu 20.04 (GNOME 3.36.1) using the [Riot Snap package](https://snapcraft.io/riot-web), see https://github.com/vector-im/riot-web/issues/5214#issuecomment-625799960

**Comment by t3chguy** [comment]
Is this still the case with later versions of Electron?

**Comment by BloodyIron** [comment]
Looks to be resolved! If a similar issue comes back, I'll open a new ticket :) Thanks d00ds! \o/
