### ISSUE TITLE
Riot Templates mail

### ISSUE THREAD

**Issue by Unsourire** [vector-im/riot-web#6964]
Hello,
I'm trying to configure the Matrix server and the riot web based application to send notification from my domain name. But even if I change the configuration files the mail is still sending from riot.im mail address when I send an invitation for exemple.

I had the following line on the homeserver.yaml file 
-------------------------------------------
email:
   enable_notifs: true
   smtp_host: "localhost"
   smtp_port: 25
#   smtp_user: "exampleusername"
#   smtp_pass: "examplepassword"
   require_transport_security: true
   notif_from: "xxxxxr <noreply@domain.com>"
   app_name: Matrix
   template_dir: /home/clients/7b6/.synapse/res/templates
   notif_template_html: notif_mail.html
   notif_template_text: notif_mail.txt
   notif_for_new_users: True
   riot_base_url: "https://riot-m.domain.com/"
--------------------------------------------------

here is the config.json file : 
---------------------------------------------
{
    "default_hs_url": "https://matrix.domain.com",
    "default_is_url": "https://vector.im",
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": true,
	"brand": "Riot",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "bug_report_endpoint_url": "",
	    "features": {
        "feature_groups": "labs",
        "feature_pinning": "labs"
    },
    "default_federate": false,
    "welcomePageUrl": "home.html",
    "default_theme": "light"
}
------------------------------------------------

Do you have any idea why is not working for me?
Thank you

**Comment by t3chguy** [comment]
Invites are sent by the identity server, so you might want to host your own if you want to change how that looks. See https://github.com/kamax-io/mxisd

**Comment by Unsourire** [comment]
Hello,
Do you have a solution to install the identity server on virtualenv? Because i'm using a managed server so i can't install directly on the system. I was able to install matrix synapse.
Thank you

**Comment by t3chguy** [comment]
That is unrelated to this repository. Try open an issue on the identity server you want to use, e.g: https://github.com/matrix-org/sydent
