### ISSUE TITLE
Feature request: Specify is_url parameter in Riot URL to prepopulate the identity server field on login.

### ISSUE THREAD

**Issue by zougloub** [vector-im/riot-web#6965]
### Description

(I hope it's not a duplicate, I searched for open issues).
Every time I open my browser, i have to select a custom server and re-enter its info, and this flow could be improved, if either I could pass the parameters in the URL, or there was a way to remember the home server.

### Steps to reproduce

1. Open riot.im/app
2. Enter settings
3. Close browser
4. Reopen browser
5. goto 1

### Version information

- **Platform**: web
- **Browser**: Firefox, nightly
- **OS**: Linux
- **URL**: riot.im/app

**Comment by turt2live** [comment]
There's two undocumented methods for doing this:

For using custom URLs: Go to `https://riot.im/app/#/login?hs_url=https://your.server.here&is_url=https://your.identity.server`

For using local storage, set the `mx_hs_url` and `mx_is_url` keys.

**Comment by t3chguy** [comment]
@turt2live it's actually just hs_url via query, not is_url  iirc

**Comment by turt2live** [comment]
Both work and are optional.

**Comment by t3chguy** [comment]
yeah it didn't work for me:
![image](https://user-images.githubusercontent.com/2403652/42137485-01fefb00-7d65-11e8-9ec8-4870435ffccd.png)

**Comment by t3chguy** [comment]
or using the URL you posted earlier:
![image](https://user-images.githubusercontent.com/2403652/42137504-3845524a-7d65-11e8-99ef-75aa0dbd76ea.png)

**Comment by turt2live** [comment]
I didn't need 3 comments to prove me wrong, but thank you. Looks like my test was faulty last night - `is_url` does not work.

**Comment by zougloub** [comment]
Thanks for the info, `hs_url` is all that's needed for me, but I won't close the issue as others might appreciate `is_url`.

**Comment by lampholder** [comment]
I've updated the title to reflect the ask, and prioritised it fairly low (since it's rare for people to use alternative ISes at the moment).

**Comment by syhe** [comment]
@lampholder is it really that rare? Everyone using Matrix.org in an isolated (corporate, for example) environment is (hopefully) using their own identity server.

**Comment by julianfoad** [comment]
This seems to fixed: I just tested it. Can someone close it?

**Comment by ericmigi** [comment]
@turt2live did this undocumented feature ?hs_url get removed at some point? Can't seem to get it working now

**Comment by turt2live** [comment]
Yes, it was removed when we tried to simplify the login/registration/config setup for users. The current suggestion is to make use of a config.json to run your Riot instead.

**Comment by ericmigi** [comment]
is there a way to load that into a web based riot client? My use case is this: I've created a raspi config script that automatically sets up a HS with a unique subdomain. But it's slightly confusing to explain to users how to change the settings in riot.im/app and I don't want to have to maintain native apps with the config files for each HS. Any thoughts?

**Comment by turt2live** [comment]
Riot isn't much more complicated than hosting a static site, so if you're able to host Synapse from the script it could also configure nginx to serve the latest version of Riot using the same config templating tool on `/var/www/html/config.json`. 

The download script would be something like: `curl -s https://api.github.com/repos/vector-im/riot-web/releases/latest | grep "browser_download_url.*tar.gz\"" | cut -d : -f 2,3 | tr -d \" | wget -qi - && tar -zxf riot-*.tar.gz -C /var/www/html --strip-components=1`

**Comment by ericmigi** [comment]
@turt2live that worked perfectly, thanks!
