### ISSUE TITLE
bruno (@bwindels:matrix.org) has no profile in the matrix.org user directory

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6970]

**Comment by MTRNord** [comment]
We have a similiar problem. Old users (registered a mont ago or so) work. Fresh ones dont.

**Comment by lampholder** [comment]
Related to https://github.com/vector-im/riot-web/issues/6599?

**Comment by MTRNord** [comment]
@lampholder atleast my part is related. not sure about the one from Matthew

**Comment by ara4n** [comment]
i think synapse might be just not updating the profile directory any more? `@tom:lant.uk` has no profile in the dir for me too.

**Comment by ara4n** [comment]
actually, might not be synapse's fault - i just invited tom to another room and this time the profile showed up fine. wtf?

**Comment by ara4n** [comment]
This is *really* bad. matrix.org user dir can't even find nadonomy at all.

**Comment by lampholder** [comment]
Let's make #6599 the canonical issue for 'inviting is broken'.
