### ISSUE TITLE
broken default avatar on FF61b6 on macOS

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6973]
<img width="407" alt="screen shot 2018-07-05 at 00 56 46" src="https://user-images.githubusercontent.com/1294269/42295804-76e310ba-7fee-11e8-8b7b-b672754c2426.png">

**Comment by aaronraimist** [comment]
@ara4n does this still exist?

**Comment by jryans** [comment]
AFAIK, the avatars work on Firefox and also the UI in the screenshot above is gone.
