### ISSUE TITLE
E2E device lists can get out of sync over federation when users delete their devices.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6974]
Lots of reports internally last week about federated servers not correctly relaying when users delete devices from their accounts.  I think particularly @lukebarnard1 deleted all his e2e devices but this didn't propagate to anyone else in the rooms until they manually refreshed their member info.

**Comment by turt2live** [comment]
This sounds like https://github.com/vector-im/riot-web/issues/4527

**Comment by richvdh** [comment]
dup #4527
