### ISSUE TITLE
Feature:  Sub-community/group

### ISSUE THREAD

**Issue by go2null** [vector-im/riot-web#6980]
### Description

I would like to be able to define communities (groups) and then build up other communities/groups based on those smaller communities/groups.  The idea is to mimic an organization/team/role structure.

### Possible implementation

1. Allow adding Community to the "Invite new community members" dialog.
2. Either
  2.1 Add a *Community* section to the existing *Members* list, or
  2.2 Add a new *Community* list

**Comment by lampholder** [comment]
We want to support the idea of organisational structures' being representable by Matrix primitives - sub-communities might be the way to do this (but anyone planning on doing any work in this area should make a lot of noise about it, since there are a lot of preexisting opinions on the topic).

**Comment by go2null** [comment]
Sub-committees implies a parent-child relatiionship (1-many).
I'm thinking of a simpler, more flexible many-to-many relationship. (Main complexity is detecting recursive "dependencies".)

**Comment by aaronraimist** [comment]
Duplicate of #5259
