### ISSUE TITLE
The "Verify device" dialog mentions the "blacklist" button, but it isn't shown in the popup.

### ISSUE THREAD

**Issue by digitalatigid** [vector-im/riot-web#6981]
The "Verify device" dialog mentions the "blacklist" button, but it isn't shown in the popup. I can see this leading to confusion.

**Comment by lampholder** [comment]
You mean:

![image](https://user-images.githubusercontent.com/1922197/42809301-38245c3a-89ad-11e8-927b-e7f9003804bf.png)

doesn't look (something) like:
![image](https://user-images.githubusercontent.com/1922197/42809540-c524a8f6-89ad-11e8-8fab-c56eb07a3f22.png)

**Comment by digitalatigid** [comment]
yes, exactly that

**Comment by Half-Shot** [comment]
This kinda sucks, we should remove the text or add the button back because it's quite worrying if you do have a bad device and can't really act on it.

**Comment by aaronraimist** [comment]
It doesn't say this anymore.

(https://github.com/vector-im/riot-web/issues/11751 exists for adding blacklisting back in)
