### ISSUE TITLE
Cant copy longer chat logs

### ISSUE THREAD

**Issue by makedir** [vector-im/riot-web#6991]
If you want to copy longer chat logs, it is impossible for the Windows client. Scrolling up/down will clear entries above/below a specific value. There is no legit way to copy a longer chat which went over a couple of hours.

**Comment by t3chguy** [comment]
That's expected, if riot didn't limit the timeline rendered then the browser would slow to a crawl :(

**Comment by makedir** [comment]
1. it was working a couple of weeks ago
2. dont FORCE stuff, give OPTIONS to decide
3. give option to do a copy to clipbaord for a time index, for example copy all chat of yesterday

**Comment by t3chguy** [comment]
nothing has changed in how the timeline is rendered in the past months...
Exporting chat logs is better tracked: https://github.com/vector-im/riot-web/issues/2630

**Comment by makedir** [comment]
That ticket is from Nov 22, 2016, and wasnt implemented so far. The Riot client fronted should have a simple user-friendly basic chat export for admins, just copy chat from 1.1.2018 to 1.2.2018 in channel x to clipboard.

**Comment by t3chguy** [comment]
That's what that issue is tracking, so closing as duplicate.
