### ISSUE TITLE
Room unread state shows joins/parts even if they're hidden

### ISSUE THREAD

**Issue by maxlath** [vector-im/riot-web#7001]
### Description

when toggling the option, join/parts messages are successfully hidden (see #916), but channels keep being displayed in **bold** even when no new messages were posted, which I suspect is due to the channel status still accounting for join/parts messages despite the option being toggled

### Steps to reproduce

- Disable join/parts messages in user setting
- Look at channels being displayed in bold despite no new messages

### Version information

riot-web : 0.15.7
olm : 2.2.1

- **Platform**: web
- **Browser**: Firefox 61.0
- **OS**: Ubuntu 16.04.4
- **URL**: https://riot.im/app/#/room/#freenode_#inventaire:matrix.org

**Comment by ara4n** [comment]
another for #3363.

**Comment by ara4n** [comment]
also very similar to #4947

**Comment by t3chguy** [comment]
I'm pretty sure this has been fixed along the way

**Comment by turt2live** [comment]
It wasn't

**Comment by t3chguy** [comment]
This will be fixed as part of FTUE Notifications

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/4947
