### ISSUE TITLE
Copy permalink from share dialog includes formatting

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7003]
The result of pasting the link into gdocs:
![image](https://user-images.githubusercontent.com/1190097/42580717-60eb7514-84e8-11e8-974b-9ee6c25aab9d.png)

This is from clicking the copy button, not CTRL+C

**Comment by t3chguy** [comment]
aaaaah that explains the workaround code I found in react-sdk, how I wish that had a comment!

**Comment by t3chguy** [comment]
Weirdly if I apply the magic code to this it stops copying even though identical code (shared method) works for code blocks :'(
