### ISSUE TITLE
Share room dialog use hosted riot URL

### ISSUE THREAD

**Issue by skylord123** [vector-im/riot-web#7009]
### Description

I host my own instance of riot web so I can use the dark theme by default as well as customize some other things. I found that when I share a room it always uses `matrix.to` for the host. I would like the option to be able to generate URLs that point straight to my riot web instance instead of going to `matrix.to` and listing available matrix clients.

The reason I am requesting this is because some users are not tech savvy and will not be able to join a room as guest very easily. I would rather have it go straight to my riot-web host so it opens the chat right away. This is mainly because my wife likes to webcam with her mom (across the world) and her mom is not technologically inclined (she has troubles trying to get facebook video chat or skype to work). Making it so my wife can just give her mom the URL that plops her straight into the room would be highly beneficial for this.

Even if the link generated is a `riot.im` one that avoids the matrix page altogether would work as well (but I would prefer to be able to specify I want to use my own riot-web install host).

I think this could be accomplished by adding a checkbox to the share room dialog that says something like "Use riot for this link" that would use the current client's connected riot host.

**Comment by t3chguy** [comment]
it uses `matrix.to` for the host...?

**Comment by skylord123** [comment]
You are right, correcting.

**Comment by lampholder** [comment]
This is related (from a UX perspective at least) to https://github.com/vector-im/riot-web/issues/6909

**Comment by BloodyIron** [comment]
Yeah if I'm self-hosting riot, matrix, and the whole infra (non-federated, internal auth), how would I change the share URLs from matrix.to to mydomain.tld?

**Comment by t3chguy** [comment]
If you change it then you'll lose compatibility with people who send matrix.to links (they'll no longer be intercepted and opened directly and instead they'll go to the matrix.to Web page)

**Comment by t3chguy** [comment]
(e.g those made by the mobile apps)

**Comment by BloodyIron** [comment]
> If you change it then you'll lose compatibility with people who send matrix.to links (they'll no longer be intercepted and opened directly and instead they'll go to the matrix.to Web page)

How do I get it to go to _my_ infra though? Without relying on the "matrix.to" public domain.

I'm not beyond recompiling the mobile versions too ;P

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3500

See `permalinkPrefix` in https://github.com/vector-im/riot-web/blob/develop/docs/config.md for documentation

**Comment by BloodyIron** [comment]
Woot! :D

**Comment by skylord123** [comment]
Pretty stoked on this, thanks devs!
