### ISSUE TITLE
Permalinks to events your server doesn't know about don't work.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7012]
If you ask for /context on a given permalink, servers don't attempt to backfill if they don't happen to have that piece of the DAG.  This makes permalinks pretty useless (e.g. I just linked @lampholder to some stuff in #e2e-dev:matrix.org from before he joined the room, and despite it being visible and him currently being in the room, he still couldn't follow the link).

Somewhat related to https://github.com/vector-im/riot-web/issues/2925

**Comment by richvdh** [comment]
dup of #2834
