### ISSUE TITLE
Markdown parser renders [Anything]:[Anything] as ""

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-web#7013]
### Description

If you send this : " [Anything]:[Anything] " or this " [Anyt hing]:[Anything] " the message will be empty, and if you take a look at the source, you can see that the encrypted source contain text, but the decrypted source doesn't anything : 

```
{
  "room_id": "id:address",
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": ""
  }
}
```

The message can be viewed if by adding a backslash ( \ ) before it (backslash will not be visible)

### Steps to reproduce

Create a room, activate the encryption

Send in the chat : 
[Anything]:[Anything]
Or
[Anyt hing]:[Anything]

(Note that [Anything]:[Any thing] (with a space in the second [ ] works)

(You can replace "Anything" by anything you want)

Screenshot : https://i.imgur.com/mvWfJVN.png

### Version information

- **Platform**:

- **OS**: Debian, but the bug is also in Android and Windows
- **Version**: 0.15.7

(Self-hosted synapse server)

**Comment by turt2live** [comment]
This is unrelated to encryption, but it is weird. I suspect the markdown parser is doing something weird here.

**Comment by lampholder** [comment]
The markdown parser looks like a likely candidate.

For the record, this occurs in both the draft and slate versions of the composer.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/42869494-1cd8ae34-8a6d-11e8-92e3-a5a4e69f4197.png)

**Comment by t3chguy** [comment]
its desired commonmark behaviour, its called References

**Comment by turt2live** [comment]
I'm increasingly wondering whether the number of markdown issues related to commonmark doing the right-but-unexpected thing means Riot should use a limited subset of markdown. It's not like people are encouraged or expected to write multi-page documents with references and advanced formatting, so there's not much reason to keep supporting the more intrusive features.

**Comment by aaronraimist** [comment]
This doesn't seem to happen anymore?

**Comment by turt2live** [comment]
Indeed. It looks like we've fixed/changed our markdown processing (probably accidentally) to fix this.
