### ISSUE TITLE
Back out 'im.riot.account_deactivation_preferences' - we don't need it any more

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7024]
It's in here: https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/views/dialogs/DeactivateAccountDialog.js#L89

And it's no longer necessary (since the automatic processing was introduced in synapse a while ago).

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2259
