### ISSUE TITLE
Empty room list

### ISSUE THREAD

**Issue by KitsuneRal** [vector-im/riot-web#7025]
### Description

After opening Riot Web (either after a fresh login, or just opening riot.im/app, or riot.im/develop, with an existing access token) I see the properly populated home page and community bar but the room list looks as if I had no rooms added. In the browser console, I see "Unhandled rejection _generateRoomLists/<@https://riot.im/develop/bundles/af5598ba6c15dc485a54/bundle.js:88774:38" with what seems to be a stack trace afterwards (see the logs).

Log: will be sent right after posting

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 61.0.1
- **OS**: Windows 7
- **URL**: riot.im/develop or riot.im/app

**Comment by bwindels** [comment]
The offending line would be:
```
var tagNames = (0, _keys2.default)(room.tags);
```
being the babel translation of [RoomListStore:184](https://github.com/matrix-org/matrix-react-sdk/blob/87d0c4b45a5a25f3db8ea4cd898ed8e2400926aa/src/stores/RoomListStore.js#L184):
```
let tagNames = Object.keys(room.tags);
```
My only guess would be that `room.tags` is not an object... Maybe in invalid event was passed to `Room::addTags`?

**Comment by KitsuneRal** [comment]
Oh, then apparently I managed to break Riot by sending a malformed `m.tags` room event from Quaternion (fixed by cbb8c1bf4e33639d8a00341021542de99bd6bce2).

**Comment by KitsuneRal** [comment]
(which I don't think Riot can ever protect itself from, so closing this)

**Comment by bwindels** [comment]
Adding a guard nonetheless, no reason it should cause the room list to go empty.
