### ISSUE TITLE
Strikethrough behaviour in slate is wrong

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7026]
### Description

Previously I could write ``<del>athing</del>`` in the editor to make draft strikethrough some text. Now that no longer seems to work.

Incidentally the only way to do strikethrough in slate is to use the RTE, which generates the correct HTML but the incorrect markdown for the message:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "body": "Do these work better in slate",
    "formatted_body": "<p><del>Do these work better in slate</del></p>"
  }
}
```

I'd like to see the return of ``~~sometext~~`` but at least the old functionality would be good. And even better if we can make the ``body`` look remotely correct. Several bridges rely on ``body`` being correct in order to render the result in other apps.

### Version information

- **Platform**: web, develop

**Comment by t3chguy** [comment]
>  And even better if we can make the body look remotely correct. Several bridges rely on body being correct in order to render the result in other apps.

is unrelated and already how the old RTE functioned.

**Comment by t3chguy** [comment]
`<del>` in Riot is considered part of the MD so only works in MD mode

**Comment by t3chguy** [comment]
![h](https://user-images.githubusercontent.com/2403652/42766684-fbd66ace-8912-11e8-9858-a9f8a3854da6.gif)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/42767156-31a18a7a-8914-11e8-8e2c-8d48ac61808c.png)

**Comment by Half-Shot** [comment]
*hangs his head in shame*, but also the MD button sucks >:(
