### ISSUE TITLE
"Unencrypted" is underlined in red on slate

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7027]
![image](https://user-images.githubusercontent.com/1190097/42766456-c2e38eee-88d7-11e8-970c-18a9fab6b16f.png)

**Comment by t3chguy** [comment]
That's because its not in your browser's spell check list :(

**Comment by t3chguy** [comment]
I don't think its possible for us to ask the browser not to spellcheck the placeholder

**Comment by turt2live** [comment]
It didn't do this pre-slate, so it'd be nice to not have it be a thing post-slate.

**Comment by t3chguy** [comment]
its because in draft-js the concept of placeholder is implemented entirely differently
not sure if this is something we can fix or have to ask upstream to fix

**Comment by t3chguy** [comment]
(or just change the verbiage to one that browsers like)
