### ISSUE TITLE
Always-open syntax helper autocomplete thing flashes with slate

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7028]
![flickering_slate](https://user-images.githubusercontent.com/1190097/42771215-ada83dfc-88e3-11e8-8b94-2e59dd27c6b0.gif)

Bad quality can be blamed on the screen recorder. It's also a lot more flashy in person.

**Comment by t3chguy** [comment]
Yup I just reported it in #riot-dev and know why it happens, am looking into the sanest way to fix it

**Comment by t3chguy** [comment]
(it happens on any autocomplete + typing)
