### ISSUE TITLE
Can't copy/paste aliases from the timeline into the composer anymore for commands

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7032]
I often highlight aliases in the timeline so I can `/join` them more easily. The composer now pastes the alias as a markdown link, which the `/join` command obviously doesn't like.

**Comment by t3chguy** [comment]
/me would recommend `Control Shift V`
not sure what the desired outcome is here, as the composer is in a way *doing the right thing*
just is annoying

**Comment by t3chguy** [comment]
(I cannot repro it on plain links)

**Comment by turt2live** [comment]
![asjdh](https://user-images.githubusercontent.com/1190097/42823921-05143902-899c-11e8-896c-f32e689a7f8c.gif)
![image](https://user-images.githubusercontent.com/1190097/42823937-0cac1dc4-899c-11e8-8859-fdaec62e37f6.png)

**Comment by t3chguy** [comment]
right so we have different definitions of 
> plain link

**Comment by turt2live** [comment]
Not sure what I was smoking to think it was a plain link. Maybe copy/pasted from the timeline?

**Comment by t3chguy** [comment]
at which point it'll have been linkified :/

**Comment by t3chguy** [comment]
It was concluded this is a feature, it's how gmail, google docs etc function. If you wish to avoid it, <kbd>Control</kbd> <kbd>Shift</kbd> <kbd>V</kbd>

**Comment by turt2live** [comment]
That's a very silly feature to be completely honest. If this was a truly rich editor, I wouldn't mind it automatically linkifying for me - that's actually useful. Given this is a markdown entry, I'd rather it be representative of plain text and therefore require my manual effort to have this stuff happen.

**Comment by t3chguy** [comment]
It's not automatically linkifying for you though, it's representing what you pasted. Imagine I post `<a href="https://...">this</a>`
The old composer paste would have pasted "this" now it pastes exactly what you copied: a link

**Comment by turt2live** [comment]
That's completely backwards in my perspective: I would have copied the text "this", not a link. If I wanted the link, I would have asked for the link via a context menu :/

It's clear that I'm nto going to win this fight though - Can it at least be an option? I'd really like to just have the composer be as close as possible to "just send the text I want to send without being helpful".

**Comment by t3chguy** [comment]
That's not down to me, it was M's doing

**Comment by t3chguy** [comment]
/me is personally likes things being options so people can be happier with how they use riot

**Comment by lampholder** [comment]
Flagged as `bug` `question` because at the moment there isn't really a satisfactory combination of labels that represent this I think.

**Comment by turt2live** [comment]
My understanding is that rich pasting is being turned off (yay!), however as another data point: the "Copy Permalink" option on github results in slate trying to wrap the URL in a code block, followed by a ton of extra newlines.

**Comment by lampholder** [comment]
Which 'Copy permalink' thing is that?

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/42950106-85e41274-8b30-11e8-999d-91d2e0e51d97.png)
