### ISSUE TITLE
quoting when in RT mode breaks in slate

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7034]
the buttons are getting out of sync so i can't toggle out of quote mode in the editor. i think this used to work when i committed it, so it may be a regression

**Comment by t3chguy** [comment]
Okay so I've figured out a case where this happens
If you Context Menu > Quote
it results in

`<blockquote><p>THING YOU'RE QUOTING</p></blockquote>

**Comment by lampholder** [comment]
This is still a problem, but hasn't stopped us releasing (and I think doesn't count as a release blocker)

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by turt2live** [comment]
We don't have rich text mode.
