### ISSUE TITLE
How to send long messages without getting them chopped into a matrix url on the reciever's side

### ISSUE THREAD

**Issue by arshdkhn1** [vector-im/riot-web#7035]
When i send a long message via riot, it end up showing like in the attached image.. How do i avoid this? Is there someway to replace newlines into separate message?

![image](https://user-images.githubusercontent.com/16819670/42781915-0e30de28-8965-11e8-8ba0-902788d2178e.png)

**Comment by t3chguy** [comment]
Thats up to how the matrix-appservice-irc bridge is configured, not something Riot can do anything about...

**Comment by arshdkhn1** [comment]
@t3chguy what should i do to avoid this? I searched online and i couldnt find anything that can help me

**Comment by t3chguy** [comment]
You can't ever avoid it, different instances of IRC bridges may have different configurations and send "pastebinned" messages under different scenarios...

**Comment by arshdkhn1** [comment]
hmm, thanks @t3chguy . Closing the issue since it is not related to Riot.
