### ISSUE TITLE
slate loses focus whenever you alt-tab away from the browser

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7036]

**Comment by t3chguy** [comment]
Cannot reproduce in Chrome on Windows :(

![m1](https://user-images.githubusercontent.com/2403652/42812633-2ef15b78-89b6-11e8-8f69-8629b7eee47f.gif)

**Comment by turt2live** [comment]
I can reproduce this on Windows. Tabbed between chrome and greenshot.

**Comment by t3chguy** [comment]
Reproducible case:
Send message, tab out, tab in

Weirdly doesn't seem to happen when manually clearing the composer

**Comment by t3chguy** [comment]
Turns out `Plain.deserialize` did not give us a focussed thing and the focus was only there because the composer was already focusses, if you tabbed out and back in it realized it wasn't focussed and poof
