### ISSUE TITLE
Slate occasionally loses focus in a way left clicking doesn't refocus

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#7039]
Reported by @tulir:

> The composer occasionally loses focus in a way that left clicking doesn't refocus it (right clicking, switching rooms, etc.. fixes it)

Possibly Firefox specific

**Comment by tulir** [comment]
Possibly gone, I haven't got this yet on the final version.

**Comment by t3chguy** [comment]
Closing as in my MANY MANY hours of testing I did not hit this, hit me if it occurs again
