### ISSUE TITLE
Slate RT->MD converts Pills into MD Links

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#7040]
Reported by @tulir:

> Rich text -> markdown converts pills into markdown URLs. Technically not a problem, but probably not what users expect.

**Comment by lampholder** [comment]
This one feels pretty weird :\ How easy is it to 'fix' (whereby I guess I mean 'special case pills to survived MD transformation back and forth)

**Comment by t3chguy** [comment]
We'd need our of slate-md-serializer instead of relying on https://github.com/tommoor/slate-md-serializer aiui

**Comment by t3chguy** [comment]
We no longer have the RT/MD dance.
