### ISSUE TITLE
Slate placeholder still shown when we have a formatting block

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#7042]
![image](https://user-images.githubusercontent.com/2403652/42814819-5802f2c2-89bd-11e8-8122-de34a545a00a.png)

**Comment by lampholder** [comment]
I feel bad about this. How hard is it to get rid of?

I'd say it's important to fix, but not an absolute showstopper for release if for some reason it's particularly tricky to tackle.

**Comment by t3chguy** [comment]
workaround done
