### ISSUE TITLE
pasting from macOS terminal in MD mode in slate adds linefeeds everywhere

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7043]
it feels like each new line is getting wrapped in a para tag, which is a bit disasterous for sharing code

**Comment by ara4n** [comment]
I think there are two problems here:
 * Plain text content fell through to Slate which inserted it via Plain.deserialise (now fixed by @t3chguy above)
 * HTML content gets pasted with p-tags everywhere, whose CSS has big vertical margins in the composer, but not in the timeline itself, hence @turt2live's concern that the linefeeds seem to vanish.

**Comment by t3chguy** [comment]
This has been fixed by making MD mode rich pasting drop the formatting
