### ISSUE TITLE
Placeholder text color has changed, and it's distracting

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7045]
riot.im/develop on Chrome (Windows)

Before slate:
![image](https://user-images.githubusercontent.com/1190097/42825199-beeeedc0-899e-11e8-82be-cb2582f6d31b.png)

After slate:
![image](https://user-images.githubusercontent.com/1190097/42825226-cae1c04e-899e-11e8-8975-215675177b46.png)

The contrast between the cursor and the placeholder is quite distracting because the cursor is now the brightest object in the area, which is flashing in the corner of my eye. When the placeholder text was nearly as bright, it wasn't as bad because the flashing cursor would blend in nicely with the rest of the composer.

**Comment by lampholder** [comment]
Slack and Discord also seem to favour a high-contrast between cursor and placeholder (though dark on light rather than light on dark), and tbh I think I prefer the new version - the placeholder looks much more distinct from composed message text.

**Comment by turt2live** [comment]
I'm not sure about slack, but Discord doesn't have nearly as much darkening around the text field:
![image](https://user-images.githubusercontent.com/1190097/42886984-28b0c3e6-8a62-11e8-80fb-a2ba38108e1d.png)

**Comment by turt2live** [comment]
After 3 months, I forgot about this, so it probably isn't an issue.
