### ISSUE TITLE
Slate: cmd+m both toggles markdown and minimises the window

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7047]
It should definitely do just one of those things. It always used to do the former although I would really love if it did the latter and we found a non-clashing shortcut for markdown toggle.

**Comment by t3chguy** [comment]
this should be fixed in the next Slate PR, which adds a `preventDefault`

**Comment by t3chguy** [comment]
/me won't be able to test without a Mac so *SHOULD*

**Comment by lampholder** [comment]
/me confirms this is now fixed (inasmuch as the old behaviour is restored - we override the OS default and capture <kbd>cmd</kbd>+<kbd>m</kbd> for markdown mode toggle.
