### ISSUE TITLE
we should probably not show the /me autocomplete command in slate

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7051]
anyone who is techie enough to know what /me is doesn't need to be told it each and every time for the duration of them typing a /me command. at the least we could hide it after the first word has been typed

**Comment by t3chguy** [comment]
this and ddg need such a specialcase

**Comment by lampholder** [comment]
Related (obvs): https://github.com/vector-im/riot-web/issues/7008

**Comment by turt2live** [comment]
Also related: https://github.com/vector-im/riot-web/issues/6920
