### ISSUE TITLE
Undo and slate composer

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7052]
...don't seem to get on very well. The thing I've noticed most is that when pasting text in non-markdown mode, undo does not undo the paste. The same happens in markdown, although testing now, it's broken when pasting plain text but works when pasting rich text.

~~Also the state of when the 'undo' menu action is available seems incorrect. Sometimes cmd+z works even when the undo menu item is greyed out(!)~~

**Comment by t3chguy** [comment]
Slate manages its own history locally instead of relying on the browser so 

> Also the state of when the 'undo' menu action is available seems incorrect. Sometimes cmd+z works even when the undo menu item is greyed out(!)

is sadly expected

**Comment by t3chguy** [comment]
> ...don't seem to get on very well. The thing I've noticed most is that when pasting text in non-markdown mode, undo does not undo the paste. The same happens in markdown, although testing now, it's broken when pasting plain text but works when pasting rich text.

will probably have been my fault when fixing the extreme case of `<p>`s when pasting plaintext content

**Comment by t3chguy** [comment]
going to break 

> Also the state of when the 'undo' menu action is available seems incorrect. Sometimes cmd+z works even when the undo menu item is greyed out(!)

into its own issue

**Comment by dbkr** [comment]
Ah, I didn't even have the console open at the time, didn't think it would be a thing that threw exceptions.
