### ISSUE TITLE
Widgets behave a bit strangely if you close the add widget dialog before it completes adding the widget

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7057]
Indeed; a 8MB gif:

![widgets](https://user-images.githubusercontent.com/1922197/42882881-e099a64c-8a91-11e8-92f5-0e7d3969bdc3.gif)

**Comment by lampholder** [comment]
It can get very glitchy if you're impatient - not in the gif, but I managed to get two etherpads when I wanted one (by thinking the first hadn't stuck), then as I deleted both of them one of them came back again.

**Comment by dbkr** [comment]
There isn't really any local echo as such until wwe have https://github.com/matrix-org/matrix-react-sdk/pull/2035

**Comment by lampholder** [comment]
Ah okay; I thought local echo was a bit you'd already merged to /develop as part of the jitsi work.

**Comment by turt2live** [comment]
Closing this as there's not much we can do about someone pulling the plug on a dialog while it's loading. Similar to how we can't prevent data corruption when the power goes out.

We could in theory put in place a dialog that says 'are you sure?' which interacts heavily with the integration manager, but the lines of code to benefit here would be insane, particularly for something as insignificant as a widget (just be more patient and try again).
