### ISSUE TITLE
Tabbing through autocomplete doesn't work anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7059]
on /develop, chrome windows 10.

1. Start typing an alias with multiple results
2. Press tab twice, having your eye on the last option
3. Autocomplete disappears with the second option picked for you

I should be able to get to the 3rd and 4th suggestion.

**Comment by t3chguy** [comment]
Argh this is caused by the "hide if focus changes" :(

**Comment by t3chguy** [comment]
oh argh, Pills in the composer don't count as "text" so when it switches between pills the condition fails because "text ' ' === text ' '" :(

**Comment by t3chguy** [comment]
this got fixed
