### ISSUE TITLE
Clicking autocomplete suggestions doesn't work anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7060]
Also the hover effect is missing:
![image](https://user-images.githubusercontent.com/1190097/42891266-2b4e2670-8a6c-11e8-926a-9487577c70db.png)

**Comment by t3chguy** [comment]
the "hover" effect happened because hovering selected that entry

**Comment by t3chguy** [comment]
So the hack to make this work is identical to the hack already applied to make the formatting buttons work
