### ISSUE TITLE
Pasting text into composer is buggy with Firefox when dom.event.clipboardevents.enabled is disabled

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#7062]
### Description

Pasting into the editor if not at beginning of a message makes it look like the message was composed correctly, but upon sending, the pasted text is not sent.

### Steps to reproduce

- Disable `dom.event.clipboardevents.enabled` in `about:config`
- Click on editor
- Type \<space\> in editor
- Type \<ctrl-v\> (assuming some text in clipboard)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 61.0
- **OS**: Void linux
- **URL**: riot.im/develop

**Comment by non-Jedi** [comment]
This one is especially annoying when trying to quote text by pasting it after a ">".

**Comment by non-Jedi** [comment]
Actually, only certain copy-pasted text seems to trigger this bug? Didn't trigger on a GH URL...

Following is text originally used to trigger bug:

>If there are significant changes to the core ideas, it may be better to
start a new MSC (with links back to the old one), rather than having a
single, long, sprawling

**Comment by t3chguy** [comment]
were you in RT mode and is the content you pasted in Rich?

**Comment by t3chguy** [comment]
![a](https://user-images.githubusercontent.com/2403652/43006669-33a0684c-8c2e-11e8-9297-59742b93a677.gif)
cannot repro :(

**Comment by non-Jedi** [comment]
Not entirely sure what that means, so here's a gif:

![peek 2018-07-20 11-59](https://user-images.githubusercontent.com/17915621/43012677-cbdde900-8c14-11e8-9298-0934bb4a11e4.gif)

**Comment by lampholder** [comment]
Thanks for sending the gif!

The gif shows some odd behaviour - we certainly shouldn't see the placeholder text whilst there's text in the composer.

Perhaps I'm misinterpreting, but I can't see the gif representing the problem originally described. Do you try and send the message in the gif? (It's a bit hard to tell where it loops)

**Comment by non-Jedi** [comment]
Yep. When the blank message gets sent is when i press enter with pasted text.

**Comment by t3chguy** [comment]
I cannot repro :(
![n](https://user-images.githubusercontent.com/2403652/43141937-1c681354-8f4f-11e8-9e5f-6cf607194568.gif)

**Comment by lampholder** [comment]
I can't repro either :( @non-Jedi can you still reproduce this?

**Comment by non-Jedi** [comment]
I can still reproduce. It seems to be a firefox-specific issue though.

**Comment by non-Jedi** [comment]
Just to make sure, I disabled all firefox extensions/add-ins, and I can still consistently reproduce the issue.

**Comment by l0b0** [comment]
I can reproduce, but only when using middle mouse button to paste.

**Comment by turt2live** [comment]
Out of interest, has this issue gone away for people on riot.im/develop as of today?

**Comment by non-Jedi** [comment]
@turt2live nope. Still getting the same behavior on riot.im/devel with Firefox.

**Comment by turt2live** [comment]
I can't reproduce this on Windows. Are people with OSX able to reproduce this at all? It's very possible it's a Linux-only problem.

**Comment by aaronraimist** [comment]
@turt2live I can't reproduce on macOS (but I can't reproduce on Ubuntu either so maybe I'm doing something wrong).

**Comment by aaronraimist** [comment]
@l0b0 @non-Jedi What desktop environments are you using?

**Comment by l0b0** [comment]
I'm using up-to-date Arch Linux, LightDM and Awesome WM.

**Comment by non-Jedi** [comment]
Qtile. But problem exists if I run Firefox without any de or wm as well.

**Comment by non-Jedi** [comment]
let me double check that problem isn't isolated to single computer when I get a chance.

**Comment by mvgorcum** [comment]
I was able to reproduce this bug in firefox on windows 7 on riot.im/app.

**Comment by igh2** [comment]
This is limiting Riot's usefulness for anything other than stream-of-consciousness messaging.  These are my results with Firefox 63 on Fedora 29, pasting into a markdown-enabled editor field.

- Pasting a single line of plain text works as expected.
- Pasting a single line of text with in-line formatting (bold, italics, etc.) works as expected.
- Pasting text with line breaks results in the loss of all line breaks in the editor field.
- Pasting text that includes a blockquote indicated by a greater-than at the start of each line of the block results in a loss of the line breaks in the editor field, and the greater-thans are included literally in the mass of text.
- Pasting text that ends with a blockquote delimited by a pair of three-back-ticks results in nothing showing in the editor field except the last three-back-ticks.
- Pasting text that includes a blockquote delimited by a pair of three-back-ticks and has text following the blockquote results in nothing showing in the editor field except the text that followed the blockquote.

**Comment by sandys** [comment]
im facing the exact same issue. this is a huge usability issue. and is affecting our ability to use it.

**Comment by absorber** [comment]
I made a video about this. It seems to be indeed Firefox-specific and was present in the old Riot Web UI as well as the new re-design: https://youtu.be/4OeOR6dXAQk

Steps to reproduce:

0. Go to a random Wikipedia article (in my example I went to [here](https://en.wikipedia.org/wiki/Software_bug))
1. Select and copy text in that Wikipedia article.
2. Paste it into the text input field of Riot Web.
3. Select all of the text you have pasted into the text input field (I did Ctrl+a)
4. Press the Backspace or Delete key.

Expected behavior: Text gets deleted.
Observed behavior: Text does not get deleted, unless you switch to another channel and back.

Same happens with plaintext, however there I could reproduce the behavior by cutting and pasting a part of the text into the input itself.

I'm on Firefox 65.0 (64-bit) and Ubuntu 16.04 with i3 running without compositor.

**Comment by t3chguy** [comment]
@sandys Yes Riot is using Slate

**Comment by absorber** [comment]
@t3chguy I'm guessing it might be a Slate.js bug then. If I go to https://www.slatejs.org/#/rich-text and repeat my steps to reproduce, I get this error:
```
An error was thrown by one of the example's React components!

Q@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:152177
Se@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:157514
ea@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:178988
a/n.updateSelection@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:181441
value@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:183374
Yo@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:84561
Zo@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:81001
Vo@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:80500
Wo@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:80326
Go@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:79699
yo@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:78931
enqueueSetState@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:54467
k.prototype.setState@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:14:1268
a/n.onChange@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:42:22982
value@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:188233
onChange@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:187219
value@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:116247
value/<@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:116040
o@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:163992
E/<@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:164114
u@https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:167167


    in a
    in a
    in div
    in a
    in div
    in Styled(div)
    in div
    in a
    in a
    in div
    in a
    in a
    in a
    in a
```

Again, this does not happen if I do this in my Chromium instance.

**Comment by non-Jedi** [comment]
@lampholder Given that a significant number of people have found their way to this issue after reproducing, could this issue get assigned a priority tag of some sort?

**Comment by ara4n** [comment]
i guess the reason it's not prioritised is because we've been unable to repro it, so it's hard to tell how many people are affected. but circumstantially it seems to be biting people a bunch, so will P1 it.

**Comment by cyphar** [comment]
I can also reproduce this issue (and have been experiencing it for the better part of a year, but kept forgetting to file an issue about it). Given the comment in ianstormtaylor/slate#2612 it seems to be a Linux+Firefox specific issue. Here is a GIF of the issue (I'm on openSUSE Tumbleweed with Firefox 65.0.1).

![output](https://user-images.githubusercontent.com/2888411/54695987-1498d180-4b7f-11e9-9109-5e17b1d2927b.gif)

**Comment by dms-cat** [comment]
This issue is caused by disabling `dom.event.clipboardevents.enabled` in about:config, which is a useful configuration change to [enable pasting text (especially passwords) on sites which don't allow it](https://www.howtogeek.com/251807/how-to-enable-pasting-text-on-sites-that-block-it/). The workaround is to simply flip this value to the default, but Riot should support pasting when this feature is disabled to avoid breaking the user experience on other sites.

**Comment by aaronraimist** [comment]
@dms-cat Another option is to use https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/ which should let you choose to only block those events on certain sites rather than disabling a fairly important feature across all sites. (yes I am the maintainer of that add-on on Firefox, but I'm also part of the matrix community)

**Comment by non-Jedi** [comment]
Thanks for tracking down the root problem @dms-cat (this has now become my favorite example of correlation \neq causation. Linux users are more likely to use password managers, and people using password managers are more likely to have `dom.event.clipboardevents.enabled` disabled (I myself had entirely forgotten about changing this setting) rather than this bug being due to some special combination of Riot, firefox, and linux.

To the Riot devs, given the above, is this a won't-fix or not actually considered a bug or something?

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by absorber** [comment]
For me it appears not to be an issue anymore, and I have `dom.event.clipboardevents.enabled` set to false.

This is on FF 74.0 (64-bit) under Ubuntu 18.04.4
