### ISSUE TITLE
some emojii look weird in the edit box once picked:

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#7073]
### Description

There are odd things in the edit box for some emoji which are decomposed.

### Steps to reproduce
- type ":eye"
- press "tab"
- hit enter

Describe how what happens differs from what you expected.

The three images attached are shown one-two-three. Two looks wrong as the emoji has been decomposed.

![one-eye](https://user-images.githubusercontent.com/1917473/43092572-8e130f36-8ea5-11e8-999c-55a30e5f6bc7.png)
![two-eye](https://user-images.githubusercontent.com/1917473/43092570-8dec978e-8ea5-11e8-9654-1284b2c542d1.png)
![three-eye](https://user-images.githubusercontent.com/1917473/43092571-8e010476-8ea5-11e8-86a1-b66e1fd24456.png)

### Version information

- **Browser**: Firefox 61.0.1
- **OS**: linux
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This is a bug in the Slate.js-based composer, which mirrors a bug in the old Draft.js-based composer which (when you tried to send eye-in-speech-bubble) would not render the emoji at all in the composer (though it would still render in the timeline).

Not sure whether this is a release-blocker or not - it's certainly very glitchy, but isn't materially _functionally_ worse than the Draft.js-based composer.
