### ISSUE TITLE
Slate issue: markdown quoting doesn't work anymore

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#7078]
If I type '> xxx' it doesn't display xxx as a quote but literally displays '> xxx'

**Comment by lampholder** [comment]
We couldn't remember if this was something that had changed, but thought that it was at least internally consistent for composer to interpret '> xxx' as a quote in MD mode, but as the literal text in RT mode, so we won't change this (unless we decide that this shortcut for quoting is something we do want to add in support for in RT mode, too).

**Comment by lampholder** [comment]
Closing this for now - lets reopen if we change our position on the above
