### ISSUE TITLE
Cursor goes back to the beginning of the message when switching tabs

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7080]
On riot.im/develop Chrome Windows 10:
1. Type some words
2. Click on a different tab
3. Go back to Riot
4. Notice your cursor isn't where you left it

**Comment by t3chguy** [comment]
So this is even weirder, sometimes its not at the beginning, I had it pop into the middle, it seems to be restoring the wrong selection state :/

**Comment by turt2live** [comment]
There's suggestions this is related to #7036

**Comment by lampholder** [comment]
Okay, on Windows 10 I reproduced (in each case 1. typing word, 2. switching browser tab, 3. returning to riot tab):
- Firefox 63.0a1 (didn't note the date - didn't realise it might change independently of the version number ffs) 64bit - composer is unfocused
- Firefox 63.0a1 (2018-07-24) 64bit - composer is focused and cursor stays where you left it
- Chrome 67.9.3396.99 64bit - composer is focused and cursor reliably moves to start of composer
- Chrome 68.0.3440.75 64bit - composer is focused and cursor stays where you left it

**Comment by lampholder** [comment]
Also, fwiw, on my mac:
- Chrome 67.0.3396.99 64bit - composer is focused and cursor stays where you left it
- Firefox 63.0a1 (2018-06-28) (64-bit) - composer is focused and cursor seems to end up in different places depending on whether you've just sent a message, or whether you repositioned the cursor with the mouse before going to the other tab, or with the keyboard or on whether `Math.random() > 0.8` 😭😭😭💀💀💀
- ![anigif_enhanced-23629-1437576392-8](https://user-images.githubusercontent.com/1922197/43194115-8ef47f84-8ff9-11e8-81f8-34f76926cc9b.gif)

**Comment by lampholder** [comment]
I've definitely been able to reproduce various brokennesses in the latest firefox, so I think this is not browser version specific. @turt2live do you have any more suggestions on how we can reproduce this reliably?

**Comment by t3chguy** [comment]
Any chance this got fixed by various Slate updates?

**Comment by turt2live** [comment]
I can't reproduce it as easily as before, so assuming fixed. If it isn't fixed for someone, please comment here so this can be reopened.
