### ISSUE TITLE
Pasting bits of timeline into the RT composer results in unexpected formatting

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7081]
To reproduce:
- copy some plain text bits of timeline
- pasta into the composer

![image](https://user-images.githubusercontent.com/1922197/43154752-63d7c25c-8f6d-11e8-8c73-d722be051798.png)

![image](https://user-images.githubusercontent.com/1922197/43154756-65b240e8-8f6d-11e8-8c73-13c638e14e7c.png)

![image](https://user-images.githubusercontent.com/1922197/43154757-674d3264-8f6d-11e8-9b11-89b74ed94d85.png)

Since the riot-web timeline is actually a big stack of `<li>`s, Slate faithfully renders this as a numbered list.

There are a few possible fixes to this:

- Don't use `<li>`s in the timeline
- Inspect the pastaed HTML more elabourately to identify that we don't want the numbered list somehow (perhaps heuristics to identify it's timeline we're pasting)
- Disable RT paste entirely

**Comment by lampholder** [comment]
This is known and is not (currently) considered a release blocker.

**Comment by turt2live** [comment]
Note: This only applies to rich text mode

**Comment by t3chguy** [comment]
We no longer have rich text mode. Is this still an issue for you in the new composer?

**Comment by turt2live** [comment]
Unlikely.
