### ISSUE TITLE
Release scripts don't update package-lock.json version

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7083]
...so our release tags end up with a package.json with the right version and a package-lock.json with a mismatched version. I think this just makes npm disregard the package-lock.json file, making it entirely pointless.

It may be better to just remove the thing from version control until we figure out this and whatever other nuances it introduces.

**Comment by lampholder** [comment]
> It may be better to just remove the thing from version control until we figure out this and whatever other nuances it introduces.

Agreed - make it so.

**Comment by dbkr** [comment]
It is done

**Comment by jryans** [comment]
Through changes to our release scripts such as https://github.com/matrix-org/matrix-js-sdk/commit/073a025b831bed1ab6e8f57c6ba2dc029efc80be and https://github.com/matrix-org/matrix-js-sdk/commit/68c8fe0fa92d8ca998c89b03659c80dd0b7274d8, we now attempt to commit lock files generally.

At the moment, the React SDK still ignores the lock file, but I'll clean that up as part of the switch to Yarn in https://github.com/vector-im/riot-web/issues/7756.
