### ISSUE TITLE
Drag to re-order rooms & people appears to work but doesn't

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7086]
Dragging a room in the non-reorderable sections (ie. people and rooms) causes all the other rooms to jiggle about underneath, and when you release, it plops into place where you drop it. It then promptly reverts back to where it was before.

When the re-ordering isn't going to work, it shouldn't look like it's going to.

(Surprised I couldn't find an existing issue for this)

**Comment by lampholder** [comment]
Fixing this requires thought; anyone planning on do anything in this area would be advised to socialise their ideas noisily beforehadn to avoid wasting effort :)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8614
