### ISSUE TITLE
"Share message" on a redacted event sounds a bit strange

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7089]
Possibly special case it to be the old "Permalink" option?

**Comment by t3chguy** [comment]
it sounds strange on State Events too tbh

**Comment by lampholder** [comment]
Actually 'Share Permalink' works for everything I think?

If not, 'Share Message' for m.room.message and 'Share Permalink' for everything else?

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2690
