### ISSUE TITLE
Implement UX for Server Quotas

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7091]
Implement this: https://www.figma.com/file/G2WhEpAyGVbJ0ZQ9GgjcnbQL/HHS-Nagbar?node-id=0%3A1

- [x] Error on /login
- [x] Error on message send
- [x] Error on /sync
- [x] Banner for people who haven't been locked out

**Comment by manuroe** [comment]
this PR (https://github.com/matrix-org/matrix-react-sdk/pull/2114) is also related to this issue.

**Comment by turt2live** [comment]
Closing as I believe the designs have been implemented for a long while now. They might need addressing for the redesign, however that sounds like a new unit of work.
