### ISSUE TITLE
Jitsi widget position strangeness with wide window

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7092]
![screen shot 2018-07-26 at 13 53 39](https://user-images.githubusercontent.com/986903/43263492-55258c8e-90db-11e8-9d2e-2dcacb7f176e.png)
With the window wide enough that the middle panel gets its width clamped, the jitsi widget ends up the right width but in the wrong place horizontally as you resize the window horizontally.

**Comment by lampholder** [comment]
This was a release blocker just to mend all of the broken windows before the release. Since it didn't make the cut then, it's not a release blocker now.

**Comment by turt2live** [comment]
This got fixed:
![image](https://user-images.githubusercontent.com/1190097/78406820-b0e21a80-75c0-11ea-9a06-614b381c43e3.png)
