### ISSUE TITLE
setting room alias & canonical alias on a newly created room often doesn't stick

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7099]
i don't think you can set the canonical alias until the room alias has already been committed, but then the room alias itself also doesn't commit sometimes

**Comment by turt2live** [comment]
Related to, if not duplicate of https://github.com/vector-im/riot-web/issues/4952

**Comment by lampholder** [comment]
Yeah, looks like a dup to me. I'm going to bump the priority of #4952.
