### ISSUE TITLE
Clicking on user mentions popup doesn't insert the right mention

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7106]
Type the first few letters of someone's name, but ambiguous enough to have multiple matches (eg 'mic' in #riot), then press tab to insert a pill. The menu of users pops up, click on one a little way down the list, a mention is inserted for whichever one is highlighted rather than the one you clicked on.

**Comment by lampholder** [comment]
I've got different behaviour now.

- press <kbd>R</kbd> in a room with multiple users with display names starting 'R'
- press <kbd>⇥</kdb> to insert a pill and open the user autocomplete
- click on any other user and it inserts their pill
- you've got two pills when you probably only wanted the second one:

![r](https://user-images.githubusercontent.com/1922197/45309214-22f49980-b51b-11e8-8f89-6de142e6ae11.gif)

**Comment by yannicka** [comment]
I can't reproduce the issue. Has it been fixed?
![Peek 21-05-2020 17-27](https://user-images.githubusercontent.com/22885898/82575185-69234c80-9b88-11ea-9082-10206b020300.gif)

**Comment by t3chguy** [comment]
Indeed seems that way
