### ISSUE TITLE
Triple clicking doesn't select pills

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7107]
Type some text into the composter including a mention pill, triple click to select everything then press backspace to delete. The pill is not deleted.

**Comment by aaronraimist** [comment]
I can't reproduce this

**Comment by t3chguy** [comment]
Related to https://github.com/vector-im/riot-web/issues/7053

**Comment by turt2live** [comment]
Closing as a duplicate of https://github.com/vector-im/riot-web/issues/7053 (can reproduce)
