### ISSUE TITLE
Presence status - color

### ISSUE THREAD

**Issue by scuq** [vector-im/riot-web#7118]
### Description

Cosmetic feature request: 

Give the "online" presence status a clear color like green, it's really hard to tell who is online and who's not if the difference is light gray to lighter gray.

Maybe you can give us an updated howto or some options within the desktop client to customize the underlying css, have customized it x times, but of course it's gone after an update.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows, Ubuntu, iOS
- **Version**: riot-web version: 0.16.0

**Comment by arthurlogilab** [comment]
Interested in changes suggested by @scuq, maybe as an option ? For instance some of users (migrating from xmpp/jabber clients) would like to be able to hide offline members to see at a glance who's available.

**Comment by t3chguy** [comment]
I believe the plan is to use online dots like we do on the DM list:
![image](https://user-images.githubusercontent.com/2403652/82425724-d5198e00-9a7e-11ea-9039-41a93947b97f.png)

**Comment by iuliuh** [comment]
I believe this can be closed, am I right?

**Comment by turt2live** [comment]
It'll be even more present in a future release, so I'd consider it closed enough for now.
