### ISSUE TITLE
Hitting the ignore button shows the unignore one everywhere

### ISSUE THREAD

**Issue by atallahade** [vector-im/riot-web#7121]
### Description

Hitting the "ignore" button on a user make all other users have the "unignore" button instead of "ignore".

### Steps to reproduce

- Ignore a user
- Try to ignore another one

You expect to see a "ignore" button on the second user but you see the "unignore" button instead.
**Edit:** The issue doesn't appears if the user panel is closed then reopened.

*The bug can be seen on the right part of this video:*
![riot-bug-01](https://user-images.githubusercontent.com/2213999/43508789-2c3cf164-9571-11e8-9b85-f908b5e2b5fa.gif)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chromium 67.0.3396.87
- **OS**: Debian 9.4
- **URL**: matrix.xwiki.com

**Comment by lefherz** [comment]
Having the same, using riot with rambox.

I discovered a workaround though:

* click on a user
* ignore the user
* close the user tab by pressing X on the right
* ignore another user

The user tab doesn't seem to refetch the data about the users, when you click on another user.

**Comment by t3chguy** [comment]
This no longer happens

![7121](https://user-images.githubusercontent.com/2403652/58050335-f92e5080-7b46-11e9-92e7-2b59cf3f2f0f.gif)
