### ISSUE TITLE
Dead keys stopped working in the desktop version

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#7124]
### Description

Since 0.16.0, dead keys have stopped working *in the desktop version*. It still works fine from the browser. With dead keys I mean characters like `'`. Characters *using* those characters (like `é`) still work fine.

### Steps to reproduce

* Set your keyboard layout to US International with dead keys.
* Try to type a `'` by pressing it twice.

Normally there would now be a ' character, but there won't be. This goes the same for ^, `, ~, and any other dead keys I can't think of right now.

### Version information
- **Platform**: web (in-browser) or desktop?

Desktop

For the desktop app:

- **OS**: Gentoo Linux
- **Version**: 0.16.0

**Comment by dbkr** [comment]
I just tried to repro this on Desktop v0.17.0, Ubuntu 16.04 (although in a VM) with the 'UK, international with dead keys' keyboard layout. Typing the backtick twice does give me a backtick character. Is this still a problem in Riot 0.17?

**Comment by PureTryOut** [comment]
It definitely is. Try "US international with dead keys" layout instead. In my case it's mainly the `'` character, which on that layout is beneath the `"`.

**Comment by aaronraimist** [comment]
After doing some testing, this seems to be a Chrome only issue. Firefox works.

It also doesn't appear to be an upstream bug as dead keys work in Chrome on https://www.slatejs.org/#/rich-text.

**Comment by aaronraimist** [comment]
Sorry, there are like 5 duplicate bugs here with #7440 (@lampholder can you combine these into one and close some as duplicates please?) so I don't know the full details of each.

Anyway, "Dead keys stopped working in the desktop version" is different from "Dead keys stopped working in the desktop version **only**". You said "It still works fine from the browser." but not which browser, so I am just clarifying.

**Comment by turt2live** [comment]
I can't for the life of me get Gentoo up and running, so I've resorted to using Ubuntu 18.10. I think this is an upstream issue in Slate - I'm seeing random failures of being able to enter dead keys, which happens on both riot (firefox, chrome, or electron) and slate.

**Comment by turt2live** [comment]
Because this happens on riot and slate, and is consistent with "IMEs don't work", I'm closing this in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.

**Comment by PureTryOut** [comment]
> I can't for the life of me get Gentoo up and running

But it has a nice well-written installation handbook, it isn't that hard ;) Doesn't seem to be OS related though, so Ubuntu should do fine.

I do notice that I had step 2 to reproduce it wrong, as pressing `'` 2 times would give you `´`. Instead on a US international dead key layout, you would press `'` once and then a space to type it. The former `´` works still, but any key requiring the character to be typed first and then a space is broken (as you just get the space instead).

I'll subscribe to the other issue though.
