### ISSUE TITLE
Easier login with non-default homeserver

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#7126]
If I want (need) to use Riot to log in to an account on a non-default homeserver, this currently requires me to:

1. flick the radio buttons below the login form
2. make the changes required to the form fields that now became visible
3. wait until JS updates the drop-down above the login form
4. only then can I log in

This is a bit of a nuisance to do manually, and it just doesn't work with password managers, not even the smart ones.

I wonder if there are some UI improvements that would make it easier to log in in automated fashion. The `hsurl` query parameter used to get honoured, but that seems to be no longer the case, unfortunately.

Maybe an easy way would be to hide the drop-down if there's only one entry, to hide the extra fields for the homeserver in such a way thay they are just invisible but can still be manipulated through the DOM, and give preference to them over the drop-down if they differ?

**Comment by bwindels** [comment]
Thanks for the report. Something to keep in mind for the redesign?

**Comment by Half-Shot** [comment]
FYI,  A well known configuration option is nearly out of proposal land that would allow us to find homeservers reliably by a userIDs domain part.

**Comment by Half-Shot** [comment]
(so the option to specify homeserver will be more of a fallback)

**Comment by madduck** [comment]
Ideally, of course, a `SRV` lookup on the domain portion of the MXID would be part of that. But yes, in terms of usability, it'd be a lot better if I could just log in as `@madduck:madduck.net` without having to bother with homeservers at tall.

**Comment by t3chguy** [comment]
Matrix SRV records specify only the location of the federation api endpoints and JavaScript in browser is unable to make SRV queries without relying on some external service

**Comment by turt2live** [comment]
The proposal in question is https://github.com/matrix-org/matrix-doc/pull/1359 btw

**Comment by madduck** [comment]
Regarding SRV records, the lookup could be made by the server running the Riot Web instance, or is that a no-go?

**Comment by bwindels** [comment]
I think so, Riot just needs a static web server at the moment.

**Comment by ara4n** [comment]
going to make https://github.com/vector-im/riot-web/issues/7253 the canonical bug for this one

**Comment by madduck** [comment]
> going to make #7253 the canonical bug for this one

I don't quite see the relation. Are you suggesting that I log in with `@madduck:madduck.net` in the future, which results in a request to `https://madduck.net/.well-known/matrix-something` to find out which homeserver to use?

**Comment by ara4n** [comment]
yup.

**Comment by madduck** [comment]
Sounds good, thanks!
