### ISSUE TITLE
Invites should check more thoroughly if a user exists

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7137]
The current behaviour of Riot is to dumbly accept any mxid you give it and invite that user. This happens in both the invite and start chat dialog. Worse than that, it shows you an entry for them in the dropdown suggestion list so long as it's a valid MXID.

![image](https://user-images.githubusercontent.com/2072976/43634630-8caae80a-9704-11e8-8ebc-33afa45ae29f.png)

- We could validate these mxids by their /profile, though I believe it would not be sensible to use /profile as the only source of truth.
- We could add an "I'm feeling lucky" button to invite the user anyway if we definitely believe they exist. 
- We should at the very minimum say "This user could not be found, it's possible they are hidden or simply do not exist".

For user's on bridges, we should be doing proper lookups on the bridge. I believe we could fix this by doing a user lookup on the bridge if a /profile request comes in for them.

**Comment by turt2live** [comment]
I quite like having the existing behaviour where it autocompletes users that may not exist. It works well for bridges, and works well when trying to invite someone when your homeserver is super slow.

**Comment by turt2live** [comment]
We now have a dialog step warning people that users probably don't exist - if this feels insufficient, please reopen.
