### ISSUE TITLE
The :train: emoji is actually a tram.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7138]
This caused a lot of disruption when I said I was taking a 🚋 to the office.

**EDIT**: The proof is here https://emojipedia.org/tram-car/

### Steps to reproduce

- Type `:train:` into the composer.

An emoji of a tram (🚋) shows up next to the text `:train:`.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **URL**: riot.im/develop

**Comment by michaelkaye** [comment]
...

**Comment by lampholder** [comment]
I'm tempted to make a `P6` label just for this bug 😄 

More seriously, I don't know where we get our :word: -> emoji mapping, but Github (as the first example to hand) _also_ thinks that 🚋 is a `:train:`. As does Android.

**Comment by aaronraimist** [comment]
Pretty sure it comes from the `shortname`s in here: https://github.com/emojione/emojione/blob/v2.2.7/emoji.json
(https://github.com/matrix-org/matrix-react-sdk/pull/2085/files#diff-9c6d157ed970be15913b7569c44ad765)

```  
"tram": {
    "unicode": "1f68a",
    "unicode_alt": "",
    "code_decimal": "&#128650;",
    "name": "tram",
    "shortname": ":tram:",
    "category": "travel",
    "emoji_order": "1610",
    "aliases": [],
    "aliases_ascii": [],
    "keywords": [
      "transportation",
      "travel",
      "train"
    ]
  },
```
```
  "train": {
    "unicode": "1f68b",
    "unicode_alt": "",
    "code_decimal": "&#128651;",
    "name": "tram car",
    "shortname": ":train:",
    "category": "travel",
    "emoji_order": "1613",
    "aliases": [],
    "aliases_ascii": [],
    "keywords": [
      "transportation",
      "travel",
      "train"
    ]
  },
```

**Comment by kiliankoe** [comment]
And `:hamburger:` stills shows a cheeseburger 🙈

**Comment by Half-Shot** [comment]
I still think about this issue :thinking:

**Comment by turt2live** [comment]
We're taking out emojione (https://github.com/vector-im/riot-web/issues/9281), so this will shortly become a problem for your operating system vendor.

**Comment by Half-Shot** [comment]
>We're taking out emojione (#9281), so this will shortly become a problem for your operating system vendor.

Hold up, the problem was because the mapping of `:train:` became :tram:. Does remove emojiOne actually fix the mapping issue. Also 99% certain my OS won't be mapping.

**Comment by turt2live** [comment]
Removing emojione does help in that we get to more easily define our own mappings, so I think it would eventually. I'd prefer to keep this closed though until emojione is removed and in front of users though: an issue this small is not really worth the anxiety caused by looking at the issue list, and it is likely more suited as a 30 second PR.

**Comment by aaronraimist** [comment]
Just adding a note here that emojibase does seem to correctly call 🚆 a `:train:`

https://github.com/matrix-org/matrix-react-sdk/pull/2995
https://github.com/milesj/emojibase/blob/master/packages/generator/src/resources/shortcodes.ts#L925
