### ISSUE TITLE
Could not verify identity of the remote server

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-web#7140]
### Description

I start using Riot on Android for a while and after sometime the app starts giving me the error in the title (with details in the attachment). No other device or account has this issue. And it normally runs fine on my Android device  from the start but I do not know at what point it starts to decide the throw this error. When I get this error, none of other apps or devices has problem with the identity of the server

Does Riot on Android need to use any other process to access the internet?  I have firewall installed on this device therefor only necessary apps are allowed to use the internet. However like I said Riot works fine for couple days so it cant be an internet issue and disabling the firewall did not seem to solve the issue.

I can use any of the web services on that server that is using the same LE certs for 443 in Chromium or other apps, so it does not seem to be like a Cert issue to me. 

Also the fingerprint shown in the screenshot matches my server's finger print. 

### Steps to reproduce

- Install it on a home server

- Get a free dns pointing to you home ip 

- Get LE certs

- Install Matrix, point to use the LE certs

- Forward the ports 

- Add an account

- Install Riot on Android 

- Start testing it 

Here is some log from android, does not seem to be useful
```

08-03 10:06:06.494  3355 27646 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=im.vector.alpha cmp=im.vector.alpha/im.vector.activity.LoginActivity} from uid 1000 on display 0
08-03 10:06:06.622  3355  4094 I ActivityManager: Start proc 27652:im.vector.alpha/u0a77 for activity im.vector.alpha/im.vector.activity.LoginActivity
08-03 10:06:06.915 27652 27652 I XLua.Xposed: Loaded im.vector.alpha:10077
08-03 10:06:07.285  3355  4094 I ActivityManager: Start proc 27682:com.android.webview:sandboxed_process0/u0i4 for service im.vector.alpha/org.chromium.content.app.SandboxedProcessService0
08-03 10:06:07.312 27652 27702 W cr_CrashFileManager: /data/user/0/im.vector.alpha/cache/WebView/Crash Reports does not exist or is not a directory
08-03 10:06:07.486 27682 27682 I XLua.Xposed: Loaded im.vector.alpha:99004
08-03 10:06:07.523 27682 27682 I XLua.Xposed: Skipping isolated im.vector.alpha:99004
08-03 10:06:07.652  3355  4094 I ActivityManager: START u0 {cmp=im.vector.alpha/im.vector.activity.SplashActivity} from uid 10077 on display 0
08-03 10:06:08.164  3355  3375 I ActivityManager: Displayed im.vector.alpha/im.vector.activity.SplashActivity: +477ms (total +1s643ms)
08-03 10:06:08.201  3355 14180 I ActivityManager: START u0 {cmp=im.vector.alpha/im.vector.activity.VectorHomeActivity} from uid 10077 on display 0
08-03 10:06:08.945  3355  3375 I ActivityManager: Displayed im.vector.alpha/im.vector.activity.VectorHomeActivity: +694ms

```

### Version information

This is happening on Android Lineage OS 14.1, the server runs on Debian X64. I am uisng Riot Android 0.8.12 from Fdroid.

![ss](https://user-images.githubusercontent.com/8519469/43649977-356c10e6-9704-11e8-9af9-ca0b61561b4c.jpg)

**Comment by t3chguy** [comment]
Try github.com/vector-im/riot-android
This is the wrong repository

**Comment by gerroon** [comment]
Ok thanks. After thinking about this issue for a while, I put the fullchain.pem instead of chain.pem in the yaml file, and for now I am not facing the issue, in case someone else ends up hitting this issue.
