### ISSUE TITLE
Font scaling is not remembered

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-web#7144]
Hi

I assume that riot-web is also same for the desktop version so I am filing this under here.

I scale the fonts up using ctrl+ to make it comfortable for myself but next restart resets the font sizing. It would be nice if this is remembered properly.

### Steps to reproduce

- Use Ctrl + to scale up the font size

- Restart Riot

### Version information

Riot Desktop version: 0.16.0 on Linux Debian X64.

thanks

**Comment by lampholder** [comment]
I think this is a dup of https://github.com/vector-im/riot-web/issues/3160
