### ISSUE TITLE
slate doesn't work in safari 10.1.2 at all

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7146]
seemingly you get a massive sprawling composer

**Comment by ara4n** [comment]
even if safari 10 has low market share, it's one of the platforms we explicitly claim to support.

**Comment by bwindels** [comment]
It's not really clear but I interpreted "Chrome, Firefox and Safari." as the latest versions of those browsers? Anyway, we can bump it to `p1` if you think it's appropriate.

**Comment by aaronraimist** [comment]
Safari 11 is available on macOS 10.11 and higher. 

macOS 10.10.x no longer receives security updates so I don't know why it would be worth supporting.

![screen shot 2018-09-29 at 9 31 43 am](https://user-images.githubusercontent.com/5855073/46246971-90814080-c3ca-11e8-8fa7-2759a7fe0f2a.png)

**Comment by turt2live** [comment]
In a somewhat desperate attempt to cull composer-related issues: is this fixed by chance with 0.17+? (newer slate)

**Comment by aaronraimist** [comment]
Slate is gone

**Comment by t3chguy** [comment]
It's still an option in the settings iirc

**Comment by aaronraimist** [comment]
Well Riot only supports the last two major versions and the current version of Safari is Safari 13 so this can be closed for that reason
