### ISSUE TITLE
Errors on first sync are swallowed (especially MAU error)

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7148]
Any sync errors during the first sync are just logged to the console but the user continues to see a spinner with no feedback. We should show something to reflect the fact that things aren't going well (but we are still trying).

In the MAU case, if somehow the server allows you to log in but not sync due to a MAU limit, we'll hit this case and you get to stare at a spinner for a long, long time.

**Comment by lampholder** [comment]
This feels like it could be the cause of quite a few riot-spins-infinitely errors; would probably be a good one to fix.
