### ISSUE TITLE
native macos keyboard text replacement (substitution) are not working on riot client

### ISSUE THREAD

**Issue by ssbarnea** [vector-im/riot-web#7155]
On MacOS (System Settings > Keyboard > Text) you can define text sequences that are auto-expanding while you type. For example you can save previous keystrokes adding things like "zze -> my.long.email@example.com" and when you would type `zze` the system will replace it will your email address.

Somehow this feature works in most applications without having to do anything but it does not work on Riot.

One sign that Riot does not support these is that is missing the Substitutions submenu on Edit menu.

I even used the trick for enforcing the enablement of text replacement on apps that do not official support it, `defaults write -g WebAutomaticTextReplacementEnabled -bool true` (see last article) but apparently this adds the substitution menu to Riot but all menu items are disabled and the text replacement happens to be unchecked.

References:
* http://osxdaily.com/2010/07/23/set-up-text-substitution-in-mac-os-x/ 
* https://support.apple.com/kb/PH25699?locale=en_GB
* https://www.macworld.com/article/1160500/software-utilities/text-substitutions.html

**Comment by lampholder** [comment]
I'm guessing you're talking about the electron app - (automatic substitution doesn't seem to work for me in Chrome across the board, though this might be something one could enable by following the steps in the links you posted).

Anyway, I can confirm that the text replacement doesn't work in Riot Electron. As an additional data point, it _does_ work in the Slack installed app.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.
