### ISSUE TITLE
Role-based On-boarding (Simpler On-boarding)

### ISSUE THREAD

**Issue by tmikaeld** [vector-im/riot-web#7157]
I've been moving a few company users over to Riot and a few normal users as well, mostly from Wire and Signal.

They are completely confused and overwhelmed by all the myrriad of buttons, texts, new conventions like private/public rooms, favorites, pages, directories... while all they want to do is connect with their peers and start a discussion!

Tell me, as a new user, is it easy to get ANY grasp of where to start on this initial page? **[1]**

I think a better way to address on-boarding is a choice where we apply GOOD defaults and relevant on-boarding to the role they choose.... for example:

**What will you use Riot for?**

- Chatting with friends ***(Like Skype or WhatsApp)***
- Collaborate with my team ***(Like Slack)***
- Join discussion boards ***(Like IRC or Discord)***
- All of the above ***(Advanced Interface)*** <- current view

This will make it a ton easier to instantly make the interface familiar to everyone!

**[1]**
![image 2018-08-10 at 11 48 21 am](https://user-images.githubusercontent.com/907195/43951399-59309c38-9c93-11e8-8041-c63293be2df7.png)

**Comment by lampholder** [comment]
Thanks @tmikaeld - you're comments are certainly valid - some of what you've raised (in particular the 'role' or 'intended use' approach to onboarding) has gone into the redesign that is currently underway. There's a blog post about it (though I don't think the role-based stuff is explored there IIRC): https://medium.com/@RiotChat/a-sneak-peek-at-a-whole-new-riot-im-1114df653782
