### ISSUE TITLE
settings modal spontaneously disappears

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7158]
Video: https://matrix.sw1v.org/_matrix/media/v1/download/sw1v.org/HsWtKoctTohBrSctzYxMsbqt

**Comment by lampholder** [comment]
This is enraging.

**Comment by lampholder** [comment]
This is (I think) because we capture the mouseup on the bits of the screen to either side of the settings modal, so if you drag with the mouse and let go in the wrong place we dismiss the settings :(

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2183
