### ISSUE TITLE
Implement the UX for room version upgrades.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7164]
Implement the UX defined in https://github.com/vector-im/riot-web/issues/7005

Figma link: https://www.figma.com/file/bi7DL10OyXistJWUb6dO7H/Room-Versioning-(web)---Second-Draft?node-id=0%3A1

**Comment by lampholder** [comment]
Riot meta issue: https://github.com/vector-im/riot-meta/issues/212

**Comment by turt2live** [comment]
Where does the room account data get populated?

**Comment by lampholder** [comment]
This includes:
- [ ] all the UX above
- [ ] hide the old room version in the roomlist
- [ ] any necessary js sdk stuff to make it all work

This excludes:
- search
