### ISSUE TITLE
Cannot disinvite users unless you have ops, even if you invited them.

### ISSUE THREAD

**Issue by wayneoutthere** [vector-im/riot-web#7180]
### Description

any user to be able to disinvite someone they have invited to a room

### Steps to reproduce

- Invite a user (example, a typo in the user you were TRYING to invite)
-see the invitation sitting on the side awaiting acceptance
-click options to dis-invite or remove invitation
-no such option exists (for non admin)

Describe how what happens differs from what you expected.

I expected that if I am the author of the invite, that I could remove the invite, especially because if you do a typo, or accidentally invite the wrong person!

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**:  Firefox 61.0.1 (64-bit)
- **OS**: ubuntu 18.04
- **URL**:riot.im/app

**Comment by lampholder** [comment]
@ara4n I think this would require a spec change to fix - is that right?

I agree that it is unintuitive that an inviter can't rescind invites they have issued.

**Comment by ara4n** [comment]
Almost a dup of https://github.com/vector-im/riot-web/issues/2989 but not quite.

Yup, fixing this is a spec change; have filed it

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/1378
