### ISSUE TITLE
Hard to see 👓 on dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7183]

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/44351305-83069b80-a499-11e8-95f7-3e3cdaffc366.png)

**Comment by lampholder** [comment]
But then again, :milk_glass: :right_anger_bubble: :white_circle: 
(whether or not that illustrates anything probably depends on which os/browser/app you're using to view github).

Fundamentally, emoji are unbordered so visibility against same-colour backgrounds is low.

**Comment by turt2live** [comment]
Closing as an OS issue due to https://github.com/vector-im/riot-web/issues/9281
