### ISSUE TITLE
Empty room sublists showing again when filtering

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#7184]
It seems that current `/develop` suffers again from #6801. If I filter by a community, then most tags are hidden, but I am still shown "Favourites", "Rooms", "People", "Low Priority", and "Historical", despite them being empty.

Without a community filter, when searching for a room name, all tags are shown, even if empty.

**Comment by lampholder** [comment]
Isn't this fixed by the 'Show empty room list headings' setting?

**Comment by madduck** [comment]
Oh, indeed. I wasn't aware of this setting, and confused why it worked with communities, without that setting. Thanks for letting me know.
