### ISSUE TITLE
Can't access user settings when homeserver is inaccessible (and hence cannot log out)

### ISSUE THREAD

**Issue by BenediktSteindl** [vector-im/riot-web#7192]
### Description

Cannot log out from riot-desktop app due to domain change of the homeserver. This prevents me from accessing the setting so that I can sign out of riot and set the new login credentials.

**Comment by jaw-sh** [comment]
Appending that we moved our homeserver just now and even a complete reinstall on Windows 10, 64-bit doesn't remove sign-in information so a lot of users are stuck not able to reconnect.

**Comment by turt2live** [comment]
Fixed in the redesign - a dedicated link is now under your name in the top right.
