### ISSUE TITLE
No spinner when registering an account

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7193]
![image](https://user-images.githubusercontent.com/1190097/44302756-b952e800-a2ec-11e8-844f-42a0e498e540.png)

**Comment by turt2live** [comment]
This was against a test homeserver that was timing out the register request (due to my own stupidity). Simulating a slow connection in chrome seems to also do the job.

**Comment by yannicka** [comment]
Do you still have the problem?

**Comment by t3chguy** [comment]
Spinner is now there
