### ISSUE TITLE
list of Salon/chat isn't wide enough

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riot-web#7195]
Hello,

In Riot desktop, the list of salon/chat we have on the left is not wide enough and sometime, titles aren't fully displayed.
Is it possible to let the user decide of the width of this column? After all, the same for the list of members on the right would be nice too?

Thank you,

Thatoo

**Comment by lampholder** [comment]
This work is in flight as part of the early stages of the redesign! Not sure exactly when it's going to land yet, but here's a sneak peek:

![resize](https://user-images.githubusercontent.com/1922197/44342208-2d72c480-a482-11e8-8bd0-2f750cff9505.gif)

**Comment by t3chguy** [comment]
This is now a thing
