### ISSUE TITLE
Share room dialog produces permalinks with room IDs rather than room aliases, which will never work on servers which don't already know the room ID in question

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7197]

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/2925 (the list of issues related to 2925 is getting fairly long)

**Comment by lampholder** [comment]
Agreed - until #2925 is addressed, what could the share room dialog do that is right?

**Comment by ara4n** [comment]
dup #7071. what it should be doing is using aliases for now.
