### ISSUE TITLE
typing :-shortcut emoji can race in slate

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7198]
if i rapidly type :thu<tab>, i can end up with 📺hu rather than 👍 quite reliably.

**Comment by lampholder** [comment]
What keys are you pressing to achieve this?

<kbd>Shift ⇧</kbd>+<kbd>:</kbd> <kbd>t</kbd> <kbd>h</kbd> <kbd>u</kbd> <kbd>Tab ⇥</kbd> ?

**Comment by yannicka** [comment]
Do you still have this issue?

**Comment by t3chguy** [comment]
The autocomplete integration with the composer has been rewritten since then, assuming no until told otherwise
