### ISSUE TITLE
Our number emoji seem to be broken/partially decomposed/decomposable

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7200]
- Go to the composer
- Type :two:
- see that the emoji looks weird in autocomplete: ![image](https://user-images.githubusercontent.com/1922197/44352711-ffe74480-a49c-11e8-895f-c67f5da75fd7.png)

On mac/chrome you can see when you type characters immediately to the right of the :two: that the emoji doesn't take up the full character space. On ubuntu/chrome you can see a white square in the background of the character (more visible if you put a space immediately preceeding the :two).

**Comment by turt2live** [comment]
I'm making wild assumptions here and thinking this will be fixed by https://github.com/vector-im/riot-web/issues/9281
