### ISSUE TITLE
Cannot load federated groups you're not a member of in Riot

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7204]
Synapse returns a 500 on `/invited_members`, which looks like this on the group's server:

```
homeserver_1 - 2018-08-15 19:48:09,204 - synapse.access.https.8558 - 93 - INFO - 5.9.150.85 - 8558 - Received request: GET /_matrix/federation/v1/groups/%2Btelegram%3At2bot.io/invited_users?requester_user_id=%40travis%3At2l.io
homeserver_1 - 2018-08-15 19:48:09,205 - synapse.federation.transport.server - 130 - INFO - Request from t2l.io
homeserver_1 - 2018-08-15 19:48:09,213 - synapse.http.server - 82 - INFO - <XForwardedForRequest at 0x7ff73cd1f2d8 method='GET' uri='/_matrix/federation/v1/groups/%2Btelegram%3At2bot.io/invited_users?requester_user_id=%40travis%3At2l.io' clientproto='HTTP/1.0' site=8558> SynapseError: 403 - User not in group
homeserver_1 - 2018-08-15 19:48:09,213 - synapse.access.https.8558 - 139 - INFO - 5.9.150.85 - 8558 - {t2l.io} Processed request: 0.009sec (0.000sec, 0.004sec) (0.001sec/0.006sec/3) 51B 403 "GET /_matrix/federation/v1/groups/%2Btelegram%3At2bot.io/invited_users?requester_user_id=%40travis%3At2l.io HTTP/1.0" "Synapse
/0.33.2rc1" [0 dbevts]
```

Riot briefly shows the group page, then follows up with "Failed to load group" due to the 500. Riot probably shouldn't fail that badly if the invite list fails to load, and synapse might want to consider exposing the list.

**Comment by turt2live** [comment]
More and more people are being bitten by this and it prevents the use of groups. @lampholder is it possible to bump up the priority higher than 1? :p

**Comment by lampholder** [comment]
Gah :(

Thanks for agitating for progress, but right at this moment I don't think we can spare the bandwidth to look into it properly :( As we work on the redesign, onboarding onto groups/communities is I think going to be a very important flow, so we'll _have_ to address it then (but that is still some time away).

**Comment by turt2live** [comment]
Should be magically fixed with a synapse update (as per https://github.com/matrix-org/synapse/pull/3969 )
