### ISSUE TITLE
We can start to drop the "(IRC)" replacement hack now

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7214]
We replace "(IRC)" in several places in Riot. The irc bridge now supports groups, doesn't set the suffixes any longer and sets portal rooms to use the correct group for flairs by default.

- https://github.com/matrix-org/matrix-react-sdk/blob/3c8fc5a8afa4a7923b9858513188da2af962ce2e/src/components/views/rooms/MessageComposerInput.js#L364
- https://github.com/matrix-org/matrix-react-sdk/blob/3c8fc5a8afa4a7923b9858513188da2af962ce2e/src/autocomplete/UserProvider.js#L108
- https://github.com/matrix-org/matrix-react-sdk/blob/3c8fc5a8afa4a7923b9858513188da2af962ce2e/src/autocomplete/UserProvider.js#L112
- https://github.com/matrix-org/matrix-react-sdk/blob/487e3cb98822313b827fbee72008c230042d7ad3/src/components/views/messages/SenderProfile.js#L113

**Comment by aaronraimist** [comment]
Is this done now @Half-Shot?

**Comment by Half-Shot** [comment]
Yes!
