### ISSUE TITLE
Undesirable invites

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#7215]
Periodically somebody includes or invites me in some strange rooms without my approvement, agreement. How is this possible?! For example today it was Internal room ID: !DgvjtOljKujDBrxyHk:matrix.org

Could you add some option to Riot setting to not allow to include me to strange and unknown to me rooms without my agreement? Thanks!

**Comment by t3chguy** [comment]
> Could you add some option to Riot setting to not allow to include me to strange and unknown to me rooms without my agreement? Thanks!

That is what an invite is. If you were to completely hide invites as you're asking then it'd be impossible for you to ever join invite-only rooms.

**Comment by akontsevich** [comment]
I do not like to join any rooms without my agreement!!! It is very strange situation and looks like some spam or undesired attention attraction.

**Comment by t3chguy** [comment]
> I do not like to join any rooms without my agreement!!! It is very strange situation and looks like some spam or undesired attention attraction.

Then this has nothing to do with `invites`
You may have been affected by a state reset or you were automatically joined by the homeserver of your choice, which is responsible for your user account and can technically do anything with it. Riot has nothing to do with this.

**Comment by turt2live** [comment]
This sounds like a case of state resets :(

**Comment by akontsevich** [comment]
I logged in only to matrix.org. Is this Your policy?! This invites are VERY boring actually!!! Happen almost every day, want to have some mechanism to disable this intrusion. What if they start to invite/spam me/us to tens or hundreds rooms per day?! This is unacceptable situation! Where they take our logins by the way to invite?!

**Comment by t3chguy** [comment]
@akontsevich As has been alluded to above, you are hitting a Matrix protocol bug.

**Comment by akontsevich** [comment]
@t3chguy when it will be fixed? What ticket is it?

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/1953
