### ISSUE TITLE
going through GDPR stuff when starting a chat loses the start chat

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#7220]
Steps: I create an account, click start chat, find the contact I want to talk to, click start chat -> I get the GDPR popup, click on the button to go through the doc, agree to everything => I'm back to the app but my chat wasn't created => frustrating

**Comment by lampholder** [comment]
The simplest fix is https://github.com/vector-im/riot-web/issues/7168

The problem at the moment is that we don't have any way for Riot to know that the user _has_ consented (other than retrying the same API request over and over until it succeeds).

**Comment by lampholder** [comment]
This also affects direct links to chat with a user, e.g. https://riot.im/develop/#/user/@username:server.org?action=chat

**Comment by ara4n** [comment]
effectively dup of #7168
