### ISSUE TITLE
 mobile device has lots of device IDs

### ISSUE THREAD

**Issue by sl5net** [vector-im/riot-web#7224]
in my mobile device under settings are quite a lot of device IDs. 15 pieces. And when I wanted to send something in a room with encryption. I was asked to verify. Why does my smart phone have so many IDs? Is not one enough?

**Comment by lampholder** [comment]
Your smart phone only has one _active_ id, but each time you've installed/uninstalled the app (on the same or different phones) it'll have generated a new id.

If you're on Android, look in the Cryptography section of the user settings - you'll see a Device Name, and a Device ID. Take a note of the Device ID, then look through the list of Devices - all the 'Mobile' devices with _different_ device ids are probably stale (you can verify, in Android at least, by clicking gon the device id and seeing when it last logged in).

You can do all of the above in Riot Web or Riot iOS, too.

I can be tricky to keep a lid on the number of devices (and it's certainly fiddly to have to keep verifying them all the while) - we are actively working on improving this at the moment :)

**Comment by lampholder** [comment]
Closing this for now - if you think you have lots of additional devices due to a bug we can reopen and investigate.
