### ISSUE TITLE
Option to remove "Jump to first unread message."

### ISSUE THREAD

**Issue by Tectract** [vector-im/riot-web#7225]
People find the 'Jump to first unread message' banner annoying, as it seems redundant given it appears often and doesn't behave usefully.

[abusive screaming edited out of the bug report]

**Comment by Tectract** [comment]
Every notification should have an option to permanently disable it.

**Comment by ara4n** [comment]
Agreed that the "Jump to first unread message" popup is annoying, but you don't need to scream at us about it.

Duplicate of https://github.com/vector-im/riot-web/issues/4134.
