### ISSUE TITLE
Can't scroll all the way down on timeline when "Jump to first unread message" banner is shown

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7234]
![scrollbug](https://user-images.githubusercontent.com/274386/44730499-6560b400-aae1-11e8-8d98-770566c1c1c1.gif)

Once you scroll up, it fixes itself. Seems to happen on firefox only.
Looking at the DOM, the element with class `gm-scroll-view` seems to be pushed down by the banner.

p1 because I personally find it annoying as hell :)

**Comment by bwindels** [comment]
Happens with both LL on and off

**Comment by tulir** [comment]
Duplicate of/related to #1770
