### ISSUE TITLE
Bug with russian  letter "Б", "б"

### ISSUE THREAD

**Issue by cavabanga26** [vector-im/riot-web#7246]
Hello!
In the client on the form "Start chat" when entering a user name in which there is a Russian letter "Б", the client can not find the name and gives an error "The wrong address is entered.
Try using one of the following valid address types: Matrix ID, email. "
The problem arises only with the letter "Б"

**Comment by lampholder** [comment]
Sorry, this bug has been around for a while: https://github.com/vector-im/riot-web/issues/4523

**Comment by lampholder** [comment]
Closing this one as a dup
