### ISSUE TITLE
Can't expand the 'see more' list.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7249]
Amandine can't expand the 'See more' button in the room list anymore (for Rooms and Favourites, People work randomly)

I filtered the list to be able to access a room hidden under “see more” and clearing the filter had no effect :/

**Comment by turt2live** [comment]
@lampholder I think this got fixed by https://github.com/matrix-org/matrix-js-sdk/pull/708 (as referenced via the rageshake). Are you or @AmandineLP able to confirm?

**Comment by lampholder** [comment]
I don't think I've seen this in a while - @AmandineLP ?

**Comment by lampholder** [comment]
Also we're deleting this 'see more' list, so I'm declaring this bad boy closed
