### ISSUE TITLE
Address bar unhelpfully overwritten

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7250]
![screen shot 2018-08-31 at 11 47 41](https://user-images.githubusercontent.com/1922197/44908536-b526c180-ad13-11e8-899d-7d69dc59c69c.png)

Set a room's access settings as above (the room needs to not already have an alias). Click the link down to the addresses section and it overrides your address bar to https://riot.domain/#addresses, which is annoying

**Comment by turt2live** [comment]
Fixed
