### ISSUE TITLE
Membership list ordering is bonkers when presence is turned on

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7251]
(and the horrible multiple chevron bug is still there)

<img width="238" alt="screen shot 2018-08-31 at 16 25 47" src="https://user-images.githubusercontent.com/1294269/44921500-9d166880-ad3a-11e8-8752-8bad5522f0f3.png">

**Comment by ara4n** [comment]
see https://github.com/vector-im/riot-web/issues/1997 for the chevrons

**Comment by turt2live** [comment]
@ara4n I don't see the bug here - what is the intended behaviour? It looks like it is correctly ordering online over offline.

**Comment by turt2live** [comment]
This got fixed somewhere
