### ISSUE TITLE
.well-known support

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7253]
https://matrix.org/docs/spec/client_server/r0.4.0.html#server-discovery

**Comment by Tragen** [comment]
I would be very happy to see this soon. Currently we have our server running on
matrix.chat.domain.tld
and it would be great if we could use only
domain.tld

**Comment by aaronraimist** [comment]
@Tragen you don't need this to land to be able to do that. See https://github.com/matrix-org/synapse/tree/67dbe4c89944cf5957f806ad63f60880e2242b23#setting-up-federation

**Comment by Tragen** [comment]
I have done this all and it's still not good. You cannot login with domain.tld with Riot. I need to login with matrix.chat.domain.tld and also the Matrix ID shown is wrong.

**Comment by t3chguy** [comment]
You'd need to reset your database. The matrix id domain is the one you configure synapse with when you install it, that combined with an SRV record to get federation working can achieve it.

**Comment by Tragen** [comment]
I have done that. I did a complete reset for synapse to use domain.tld but still Riot can only login with matrix.chat.domain.tld and shows the login id also with the wrong domain.

**Comment by djmaze** [comment]
@t3chguy That does not work because the browsers cannot resolve SRV records. (See #2682)

**Comment by mvgorcum** [comment]
@djmaze the 'wrong matrix ID' is indeed solvable with an SRV record, because the server part (after the ':') is only relevant for server to server connections, and those can resolve SRV records.

Clients, however, would still need to select 'custom server' and fill in the whole address of the server (so chat.domain.tld) though they can login with @user:domain.tld.

**Comment by Tragen** [comment]
And that's where the .well-known comes into place. Now the client can resolve the correct domain also.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2227
