### ISSUE TITLE
Spinner doesn't appear in timeline anymore when reconnecting after error

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7261]
We no longer show a spinner when recovering after losing connectivity (e.g. after being slept).  Superficially this looks like the catchup has entirely failed, as the client lets you send messages, but there's no evidence that the client doesn't think it's caught up.  This might be the same as the previous "RR suddenly jump" bug? (if RR are the only things to have changed position after having caught up). In practice, though, it's still trying to reconnect. [Rageshake](https://github.com/matrix-org/riot-web-rageshakes/issues/955). It looks like this:

<img width="2032" alt="screen shot 2018-08-17 at 23 34 19" src="https://user-images.githubusercontent.com/1294269/44289895-7c4c0e80-a276-11e8-8e8b-3198745925b0.png">

**Comment by bwindels** [comment]
Split of from #7182

**Comment by bwindels** [comment]
PR: https://github.com/matrix-org/matrix-js-sdk/pull/702

**Comment by ara4n** [comment]
hm, can we not close this now if the fix merged?
