### ISSUE TITLE
[Feature Request] Add option to disable typing notification

### ISSUE THREAD

**Issue by rubo77** [vector-im/riot-web#7283]
### Description

I don't want to see the typing notification of other users, when they are typing. This is disturbing and stealing my time, because I cannot stop thinking about the oncoming message ;)

### Solution

Add an extra option in settings to suppress typing notifications from others.

### Workaround

Add this style with [Stylish](https://userstyles.org/styles/163918/riot-hide-typing-notifications) that injects those CSS:

```
.mx_RoomStatusBar_typingBar, .mx_RoomStatusBar_typingIndicatorAvatars > img:nth-child(1) {
    display:none;
}
```

**Comment by schwukas** [comment]
Correct me if I'm mistaken but shouldn't that be an issue for [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk). I couldn't find anything related to typing notifications in riot's code, only in matrix-react-sdk.
If so, I would gladly open an issue there and take care of it.

**Comment by aaronraimist** [comment]
Issues for any of the Riot components get filed on this repo (matrix-react-sdk doesn't even have issues enabled)

**Comment by rubo77** [comment]
@schwukas : you can create a PR in the matrix-react-sdk that would add this and link here, I would be glad, since the workaround only works, if you use Riot in a browser. The stand-alone riot-app cannot be invoced with such a style workaround

**Comment by schwukas** [comment]
I just did. I only was bit hesitant because this is my first contribution to the project. You can find the PR [here](https://github.com/matrix-org/matrix-react-sdk/pull/3494)
