### ISSUE TITLE
mojave shows both gemini & native scrollbars when you scroll...

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7291]

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/6694

**Comment by lampholder** [comment]
@ara4n how noticable did you find this? In my (albeit quick) testing it seemed similar to the ff problem - not immediately noticable (but detectable if you were looking for it).

We've got a problem with gemini across the board really - I'd like us to review our scrollbar homogenisation technology and application to see if we can't find something that gives us fewer headaches :\

**Comment by ara4n** [comment]
fixed somewhere along the way, probably by the css scrollbar stuff.
