### ISSUE TITLE
Missing e-mail on HS where e-mail is required gives confusing error messages

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7297]
![email required but still dialog](https://user-images.githubusercontent.com/274386/45225013-c2b3ec80-b2bb-11e8-99a1-90921e9f7cfc.png)
![no email error](https://user-images.githubusercontent.com/274386/45225015-c2b3ec80-b2bb-11e8-9029-0dee8481cfc3.png)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/2180
