### ISSUE TITLE
Make develop build and run using normal npm conventions

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7305]
Rather than messing with fetch-develop.deps.sh / mandating manual linked checkouts, or having to run three separate `npm run start` processes, it would be much more simpler if riot-web just let you `npm run build` or `npm run start` on develop to pull in the right versions of react-sdk and js-sdk as per package.json.  Users could then `npm link` if they want to customise a particular version of the dep, but would ever only need a single `npm run start` instance.

**Comment by ara4n** [comment]
in practice, i think this means:

* adding post-install scripts to js-sdk and react-sdk which make them build their /lib dirs after install (and checking it doesn't break CI or release processes), so that if npm pulls them in from github, they can still be used as real dependencies without having to manually `npm run build` them.
* making `npm run start` also somehow safely cascade into node_modules and recurse onto js-sdk and react-sdk too.

The end result would be that you could do:

```
git clone git+ssh://git@github.com/vector-im/riot-web
cd riot-web
npm i
npm run start # or npm run build
```

...and it would 'do the right thing' and work.

@martindale, does that match your expectations?

**Comment by martindale** [comment]
@ara4n yes, this is great!  Thanks for taking the time to write this up.  I think will help a lot — if I have time this week, I'm going to take a crack at shoring up the dependency tree and making this work.

**Comment by bwindels** [comment]
I'd love our build setup to be simpler as well, but I wonder how js-sdk and react-sdk would get built after making local changes if you've set it up with `npm link` to come from some other local directory. 

We might be able to configure webpack to monitor `node_modules/matrix-js|react-sdk` as well from riot-web, as described here: https://stackoverflow.com/questions/41522721/how-to-watch-certain-node-modules-changes-with-webpack-dev-server/44166532#44166532

**Comment by bwindels** [comment]
That approach seems less like npm conventions to me though (where every module is supposed to build itself), but taking this shortcut for local development only might be worth the convenience.

**Comment by ara4n** [comment]
I've started a google doc to try to gather and comment on options here: https://docs.google.com/document/d/138w2bb8BokVR6OJA7_5qIeDFkjp9GODzlrqhVC9sMEI/edit#

**Comment by ara4n** [comment]
!CsvCRIIUwihoBBiFpX:status.im

**Comment by turt2live** [comment]
This is mostly fixed by https://github.com/vector-im/riot-web/pull/7355 - we still have a couple oddities, although they seem unavoidable given the requirement to maintain a js-sdk and react-sdk separate to riot-web.
