### ISSUE TITLE
only empty rooms & warning in the room I had open on my screen

### ISSUE THREAD

**Issue by krrisis** [vector-im/riot-web#7311]
### Description

updating riot this morning resulted in this: 

![image](https://user-images.githubusercontent.com/6533925/45323653-afde2980-b500-11e8-9b06-7b54f66ea5af.png)

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by turt2live** [comment]
The conversation for this starts at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15366120921426704cXxIY:matrix.org in #riot

My best guess is that Riot is handling the lack of an `m.room.create` badly, causing the room upgrade warning to show up. Some servers (like Construct, currently) don't inform the client of the create event, and it appears the case the OP has experienced is some sort of cache problem where the event disappeared.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7331
