### ISSUE TITLE
Pin rooms where I've been binged at the top of the "Rooms" section

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#732]

**Comment by turt2live** [comment]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=30118866)](https://www.bountysource.com/issues/30118866-pin-rooms-where-i-ve-been-binged-at-the-top-of-the-rooms-section)

**Comment by dbkr** [comment]
My reservation about this is that it implies the room list would re-order when you switched to a room you'd been binged in (since the notification would clear). I think this would be quite annoying.

**Comment by turt2live** [comment]
When testing I found that once I clicked on the room I wasn't distracted by it jumping down 2 or 3 places. It's no worse than receiving messages in a popular room while reading a different room.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1936
