### ISSUE TITLE
LL bug: tried to join the home assistant room, and the bg member sync didn't happen.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7321]
I clicked on home-assistant from the main room directory on matrix.org

https://riot.im/develop/#/room/#gitter_home-assistant=2Fhome-assistant:matrix.org

It gave me an ugly blank RoomPreviewBar telling me to click 'join' again... but then on joining, it says there are 1.4K users, but only the LL ones are visible:

<img width="249" alt="screenshot 2018-09-12 at 12 50 54" src="https://user-images.githubusercontent.com/1294269/45423275-ba2c2f00-b68a-11e8-89ea-7eead2cb8a57.png">

**Comment by bwindels** [comment]
you still have the console logs by any chance?

**Comment by ara4n** [comment]
maybe - will try to rageshake (just resyncing atm)

**Comment by bwindels** [comment]
Able to repro this in an e2e test, it's caused by the room not being available yet trough `client.getRoom(roomId)` while peeking in `MemberList`, so it doesn't wait for anything and just renders. Thinking how to fix this ...
