### ISSUE TITLE
Joining a room UX is unnecessarily clunky.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7322]
When you try and join a room, you get this grey box:
![screenshot 2018-09-12 at 12 52 55](https://user-images.githubusercontent.com/1922197/45423287-ca440e80-b68a-11e8-94b6-cfd70e6b0d59.png)

If the room is previewable, you see the contents of the room behind the grey box.
If the room is not previewable, you see empty space behind the grey box.

We can improve this with a simple wording change; something like:

### For previewable rooms:
This is a live preview of #solutionsspam
[Click here](https://example.com) to join the discussion!

### For non-previewable rooms:
There is no preview available for #solutionsspam
[Click here](https://example.com) to join the room anyway.

**Comment by lampholder** [comment]
Maybe @nadonomy could take a swing at the wording. 

I think the important concept for the preview is that you can view the room (and evaluate whether it's the sort of place you want to visit) _without_ the members of that room seeing you (but as soon as you join your involvement _is_ visisble to room members.

**Comment by turt2live** [comment]
I like Coffee's suggestion because it matches the new design :)

**Comment by aaronraimist** [comment]
Coffee's suggested design was implemented in https://github.com/matrix-org/matrix-react-sdk/pull/2925
