### ISSUE TITLE
Rooms with missing m.room.create events now show up as 'known vulnerability' room version warnings :/

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7331]
This can happen when your HS's state for the room gets lost and it syncs empty state, but the resulting warning is scary & confusing.

**Comment by ushacow** [comment]
Hi! Could you tell how to get rid of such rooms? What should I delete from database?

**Comment by ushacow** [comment]
Thanks for your help! Do you mean the button in Settings -> Clear Cache and Reload in Riot-web? I've tried that one, but it didn't remove Empty rooms with 'known vulnerability' message in my client.

**Comment by turt2live** [comment]
This is particularly bad when joining a room for the first time: the power levels and create event both haven't made it to the client yet, so riot appears to assume it should show the warning to "room administrators only" of which I (in my case) am definitely not one. Should probably fail a bit safer towards not showing the warning.

**Comment by lampholder** [comment]
Does this strike every room which the joiner doesn't have perms to view history?

I'm going to abuse `critical` here to indicate how urgently I think this needs to be fixed, it is _super_ alarming :\

**Comment by turt2live** [comment]
I don't think it's related to history. I just joined another room (over federation) and got the problem right away.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/755
