### ISSUE TITLE
Add badge to GIFs

### ISSUE THREAD

**Issue by koyuawsmbrtn** [vector-im/riot-web#7344]
### Description

When "Autoplay GIFs" is disabled there should be a badge that indicates that this is a GIF file so people will hover over it when they want to (similar to Discord or Mastodon). Just guessing wildly by the file name isn't an option for the "average user".

### Version information

- **Platform**: Desktop
- **OS**: openSUSE Tumbleweed 2018.09.14
- **Version**: 0.16.2

**Comment by renanpvaz** [comment]
Hey, I could work on this. I'd be grateful if any other info or tips could be provided since I've never contributed to this repo.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/2235
