### ISSUE TITLE
Inserting emoji with compose key creates ghost character

### ISSUE THREAD

**Issue by tulir** [vector-im/riot-web#7347]
Inserting emoji with compose key (e.g. ™ with `compose+t+m` or ☺ with `compose+:+)`) creates the real character with emojione and a ghost character with the main font. The ghost character does not get sent, but it can be a bit confusing.

![riot-compose-key](https://user-images.githubusercontent.com/4224639/45590803-14a6e300-b94a-11e8-82e0-a0ab22940a31.gif)

- **Platform**: web
- **Browser**: Firefox 62.0
- **OS**: Ubuntu 18.04
- **Version**: Latest develop (e58ac74aa25baa936297d9084866d02b0a94b390 / matrix-org/matrix-react-sdk@77d5daf9e396dc0d54b25f22696f0a1f347550f0 / matrix-org/matrix-js-sdk@833002f846e9a0428f8d1e6cd10652372c9065a7)

**Comment by BobVul** [comment]
The same thing happens on both Firefox and Chrome with the [Windows 10 emoji keyboard](https://blogs.windows.com/windowsexperience/2018/02/05/windows-10-tip-get-started-emoji-keyboard-shortcut/).

**Comment by tulir** [comment]
New composer fixed all the IME bugs, including this one
