### ISSUE TITLE
Consider upgrading EmojiOne

### ISSUE THREAD

**Issue by evoL** [vector-im/riot-web#7354]
### Description

Currently Riot doesn't support new emoji added in Unicode 10 and above. That's because it depends on EmojiOne 2, which is [not supported anymore](https://github.com/emojione/emojione#emojione-version-2). Since EmojiOne [support even Unicode 11 in version 4](https://github.com/emojione/emojione/releases/tag/4.0.0) and new emojis are being more and more widespread, I believe it would be nice to upgrade.

Unfortunately, according to my short research, it's not as easy as just bumping the version in `package.lock`. EmojiOne 3 was a breaking change and it might be necessary to adapt the code and ensure everything still works. Apart from that, version 3 and above are released under a [different license](https://github.com/emojione/emojione#emojione-version-3). It would be worth checking if the new terms are OK.

In any case, I think this would be beneficial for the users of Riot, especially because there is a growing discrepancy between emoji support in OSs and what Riot supports. (I found one issue about that already: https://github.com/vector-im/riot-web/issues/6522)

### Version information

- **Platform**: web

For the web app:

- **Browser**: all
- **OS**: all
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
Unfortunately emojione 3 also has a different license, so we can't use in Riot I'm afraid. There are alternatives though.

**Comment by evoL** [comment]
Fair enough, I was kind of expecting this. I just had a quick look at their [free license page](https://www.emojione.com/licenses/free) and two points stand out there:

* > May not include icons in open source projects
* > May not use assets as primary component of your digital application

Now, I feel both points are kind of arguable in case of Riot (Is an entry `package.json` considered including? Are emoji a primary component of Riot?), but I agree it's better to stay on the safe side, since it's not Creative Commons anymore.

Speaking of alternatives, two of the big players release their emoji set under a fitting license, [Google](https://github.com/googlei18n/noto-emoji) (Apache 2.0) and [Twitter](https://github.com/twitter/twemoji) (CC-BY 4.0). Combined with a dataset like [iamcal/emoji-data](https://github.com/iamcal/emoji-data) (MIT-licensed), it would be possible to replicate what EmojiOne gives out of the box.

**Comment by sandys** [comment]
is there an update on this ? Google's Noto Emoji seems like the best option here - https://www.google.com/get/noto/help/emoji/

**Comment by Half-Shot** [comment]
I'm very sad that @Mathjis 's 🤮 didn't render properly in riot, could we look for alternatives as a matter of priority :(

**Comment by turt2live** [comment]
We're taking out emojione (https://github.com/vector-im/riot-web/issues/9281) for various reasons (see comments). Closing this because we don't have plans to upgrade emojione. In future, we may reconsider and use one of the lovely alternatives proposed here though!

**Comment by evoL** [comment]
Fair enough. I buy the maintenance cost argument. Thanks for the update :)

I'd just like to somewhat reiterate the point of https://github.com/vector-im/riot-web/issues/9281#issuecomment-476736502 — please at least keep a lookup table for shortcodes (`:smile:`) and emoticons (`:)`) to emojis.
It doesn't have to be EmojiOne's, but may be a different, preferably up-to-date one (like the one from https://github.com/iamcal/emoji-data). This is a very useful feature no matter whether you use custom emojis or not.

**Comment by turt2live** [comment]
I believe the plan is to do that - @evoL posting that link on #9281 would help make sure it doesn't get lost though :)
