### ISSUE TITLE
consider adding option to *not* replace Emoji

### ISSUE THREAD

**Issue by igalic** [vector-im/riot-web#7356]
### Description

Most operating systems these days contain a complete and pre-installed (colour!) Emoji font that is specific to the system, or the user's configuration.

### Steps to reproduce

- painstakingly install and configure a [beautiful and perfect Emoji font](https://github.com/C1710/blobmoji) and rejoice 😻 
- use *literally* any web or electron app, including riot.im/app and see that it gets auto-replaced with something you don't want 😿 

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Electron: 3.0.0-beta.5 / Chromium: 66.0.3359.181
- **OS**: Ubuntu
- **URL**: riot.im/app (i have not tried riot.im/develop yet)

**Comment by turt2live** [comment]
Good news! We're taking out emojione (the lib we use for this). Closing this to track it here: https://github.com/vector-im/riot-web/issues/9281
