### ISSUE TITLE
Riot freezes if an emoji is inserted into the editor

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/riot-web#7357]
When any emoji is inserted into the message editor, Riot freezes completely and I have to kill it. It doesn't matter if the emoji comes from the colon autocompletion feature or from the clipboard.

Log: Has been sent

Right before the freeze a warning appears on the development console twice:

```
rageshake.js:66 Warning: The range anchor was set to a Node that is not a Text node. This should not happen and can degrade performance. The node in question was:
```

Clearing the cache doesn't help.

### Version information

- **Platform**: Desktop
- **OS**: Windows 7
- **Version**: 0.16.4

**Comment by turt2live** [comment]
This sounds like a duplicate of #7216

**Comment by MazeChaZer** [comment]
Oh yeah, from the freeze on I'm getting a fast incline in RAM usage, from <200K to well over 1G and not stopping.

**Comment by MazeChaZer** [comment]
Seems to be the same as #7105, closing in favor of the other issue.
