### ISSUE TITLE
[Feature Request] Web/Android - Straight to Bottom

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#7359]
Can we get a function where we can click/tap to go "straight to the bottom" or latest chat line?

When I hit the "go to the latest unread message" that can set me back days+ in the scrolling logs, and well, I don't want to spend hours scrolling back to the bottom.

So a nice button that shows up when I'm scrolled up, would be super handy.

Please? :)

**Comment by aaronraimist** [comment]
Both Riot-web and Riot-android have had this feature for a while, doesn't this button do what you are requesting?
![Uploading Screen Shot 2018-09-18 at 9.11.54 PM.png…]()

**Comment by BloodyIron** [comment]
lol oops! Sorry for missing that! D: Yeah, it does do what I want, heh.
