### ISSUE TITLE
Minimise then maximise a jitsi widget - get an infinite spinner

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7363]
You can fix by navigating away from and back to the room.

**Comment by lampholder** [comment]
Only seems to affect the jitsi widget - other widgets (etherpad for example) come back fine.

**Comment by akontsevich** [comment]
Have same issue.

**Comment by turt2live** [comment]
It looks like we've fixed this since 2019 at least. If this is still a problem, please open a new issue.
