### ISSUE TITLE
Layout is messed up when switching to another monitor

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#7365]
### Description

I use the desktop app (on my MacBook Pro mid-2015) and I often switch to my 4K monitor when I get to the office.

If I already have the Riot desktop opened, when I switch to (or from) my 4K monitor, the layout is messed up and not really usable.

My workaround for now is to quit and reopen Riot.

Note: Slack (using Electron as well) doesn't have this problem.

### Steps to reproduce

- Open Riot desktop on your laptop
- Plug your monitor (maybe only a 4K one?)
- Move the window to this monitor
- Unplug your monitor

I'm expecting the layout to be resized to the new size and resolution and still be usable.

Log: not sent    

### Version information

- **Platform**: desktop
- **OS**: macOS
- **Version**: 0.16.4

**Comment by MightyCreak** [comment]
The repro steps don't work as is... there must be something else I'm doing that raises this bug. I'll try to figure it out, but basically the steps represent my day to day workflow.

**Comment by ara4n** [comment]
We won't be able to act on this without a screenshot so we can see what the failure is

**Comment by MightyCreak** [comment]
Yep, I'll give it as soon as I have it. Just know that I have this issue almost every day for as long as I can remember (it's not just a one timer).

**Comment by lampholder** [comment]
We have certainly seen weirdnesses on switching to external monitors (https://github.com/vector-im/riot-web/issues/6919 and https://github.com/vector-im/riot-web/issues/6696).

This has been relatively low priority due to its being anecdotally easy to fix and my not having heard any complaints about it outside of the office.

Doesn't seem limited to riot desktop or any particular browser.

**Comment by MightyCreak** [comment]
I got a screenshot for you:

![riot_layout_issues](https://user-images.githubusercontent.com/6382548/45888870-1e3aab80-bd8d-11e8-9e51-f67102f5e344.png)

Notes:
* I scrambled the personal data (I think it's pretty obvious to see what's scrambled and what's not 😄)
* In this case, I connected my 4K screen on my laptop; the laptop lid was always is closed during the procedure
* We don't see it on the screenshot, but the cursor is on the first room, under "Favoris".

Issues:
* The name of the rooms disappeared
* The scrollbars are always shown in the community panel
* The scrollbars are always shown in the right panel
* The "is writing" panel, above the text area at the bottom, is displayed although there's nothing in it

**Comment by Quiark** [comment]
I have the same result using Firefox

**Comment by turt2live** [comment]
I believe we fixed this in the redesign when we saw it.
