### ISSUE TITLE
Invalid alias format message is useless

### ISSUE THREAD

**Issue by ssbarnea** [vector-im/riot-web#7376]
When someone is trying to add a room alias, they will get a "Invalid alias format", one message that does not include any cloue regarding what would count as a valid alias format, neither a link to a web page that would document the "format".

**Comment by lampholder** [comment]
Slightly related to https://github.com/vector-im/riot-web/issues/7372 (in which I gripe about the term alias being used at all).

This UX:
![image](https://user-images.githubusercontent.com/1922197/45957141-3bc97880-c00c-11e8-8120-0e23be719a94.png)
should be modified such that you:
- don't need to type in the non-optional components of a room alias (the leading `#` and the trailing `:domain.tld`)
- get feedback when you try and type an illegal character (perhaps something like http://jsfiddle.net/5ocu2cqk/20/ , though I know people have strong feelings about UX that just refuses to accept your invalid keypresses (as opposed to acceptiong them and then highlighting that they are invalid)

**Comment by lampholder** [comment]
p1 'cause if we're tackling #7372 and really want to encourage people to set aliases, we'll be more successful if the UX for creating an alias is helpful rather than annoying.

**Comment by turt2live** [comment]
I think we fixed this with the new alias UX
