### ISSUE TITLE
"New messages" banner is out of alignment

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7379]
![image](https://user-images.githubusercontent.com/1190097/45965788-a2d43680-bfe6-11e8-899b-5e669bb2ad2b.png)

**Comment by lampholder** [comment]
Reproduced, on Chrome at least.

**Comment by turt2live** [comment]
This is going to be solved by https://github.com/vector-im/riot-web/issues/7592 which moves the thing to somewhere completely different.

**Comment by turt2live** [comment]
Fixed
