### ISSUE TITLE
"Unable to connect to homeserver" warning should probably appear sooner

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7380]
This appeared on my third failed sync:
![image](https://user-images.githubusercontent.com/1190097/45967782-3fe59e00-bfec-11e8-97fe-09a5d393b7ce.png)

That's over 180 seconds since I opened the app. After the first failed sync due to a timeout might be more reasonable?

**Comment by lampholder** [comment]
Yeah, I can't see a reason why this wouldn't be better sooner. 180 seconds is significantly longer than most people would be willing to wait for feedback :P

**Comment by turt2live** [comment]
This happened in https://github.com/matrix-org/matrix-react-sdk/pull/2182 but might still be too eager as per https://github.com/vector-im/riot-web/issues/7424
