### ISSUE TITLE
Adding an alias before selecting a room visibility setting all before pressing save tells you the room must have an address

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7396]
![image](https://user-images.githubusercontent.com/1190097/46106908-4106fe80-c197-11e8-816e-132dd0fa40d7.png)

1. Create a new room
2. Add an alias, but don't press save
3. Click "anyone who knows the room's link" for the visibility setting and don't press save
4. Observe a warning that you need to complete step 2 of this example

**Comment by lampholder** [comment]
bleurgh

**Comment by matthijskooijman** [comment]
I believe this is no longer relevant, since the UI has gotten a major rework (and will get more with https://riot.im/app/#/room/#dansstage-techies:matrix.org). Anyone care to close this?
