### ISSUE TITLE
Compound (ZWJ) emoji does not work

### ISSUE THREAD

**Issue by BobVul** [vector-im/riot-web#7398]
### Description

It's not possible to use [ZWJ emoji](https://unicode.org/emoji/charts/emoji-zwj-sequences.html) ([see also](https://emojipedia.org/emoji-zwj-sequences/)) at the moment. Much of the emoji inserted by the Windows 10 emoji keyboard (Win+`;` or Win+`.` on version 1803) uses ZWJ sequences.

These work in most other text entry fields in the same browser, e.g. this GitHub comment box.

### Steps to reproduce

- Copy one of the gendered shrugs into the input field: 🤷‍♂️ or 🤷‍♀️
- Type a space after to get the field to process the character

Alternatively:

- On Windows 10 v1803, press Win+`;` or Win+`.` to bring up the emoji keyboard
- Search for `shrug` and enter one.

The glyph is not a single male or female shrug as expected, but an ungendered shrug with a male or female symbol afterwards.

There is also an extra glyph appearing in the input field, #7347

![image](https://user-images.githubusercontent.com/1674237/46117663-d791f900-c245-11e8-8f36-e2deeb94c2a5.png)

Log: not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Tested Firefox 62, Chrome 69
- **OS**: Tested Windows
- **URL**: riot.im/app and also a private server running 0.16.3.

**Comment by tulir** [comment]
Emojione only has support for that starting from version 3 (which is unusable due to licensing), so this would most likely fixed by switching the emoji pack (#7354) and/or allowing native emoji (#7356)

**Comment by turt2live** [comment]
Closing because we're removing emojione (https://github.com/vector-im/riot-web/issues/9281) - we can revisit this if it becomes a problem post-removal.
