### ISSUE TITLE
Collapse joins/parts in a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#74]
Or perhaps just collapse them by default after a wihle?  Or just collapse lots of duplicates?

**Comment by azrdev** [comment]
related to #916

**Comment by fuzzy76** [comment]
There is some duplicate collapsing going on ATM, but it does not work very well for bridge IRC rooms, since every second message is the IRC bot inviting the joining people – which breaks the collapsing.

**Comment by ara4n** [comment]
this happened. i'll file a new bug to merge joins/invites.

**Comment by richvdh** [comment]
> this happened

**Comment by fuzzy76** [comment]
Is ```lborda and 4 others left, tau was invited, joined and left, was invited and joined, raijin and 1 other left, were invited and joined, hutch34 and 1 other were invited and joined expand``` supposed to be human readable?
