### ISSUE TITLE
E2E: Mechanism for encrypting the key with the passphrase (design and impl)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7404]

**Comment by dbkr** [comment]
I think the conclusion here is to just use PBKDF2 as with the exported key file. We can store the salt and number of iterations in the json along with the backup.

**Comment by dbkr** [comment]
https://github.com/matrix-org/matrix-doc/pull/1703 is relevant

**Comment by jryans** [comment]
I believe this is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/786.
