### ISSUE TITLE
Infinite spinner on startup when not logged in

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7405]
Probably due to lazy loading being enabled by default now. riot.im/develop

```
POST https://matrix.org/_matrix/client/r0/user/%401103697%3Amatrix.org/filter? 403 ()
rageshake.js:66 Unhandled rejection M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
```

**Comment by bwindels** [comment]
Should be fixed but feels premature to close this before it;s deployed and confirmed as fix probably :)

**Comment by turt2live** [comment]
It didn't infinispin when I opened riot.im/develop in an incognito window, which is how I found this bug in the first place
