### ISSUE TITLE
Redesign: timeline

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7406]
Implement Jouni's design

**Comment by BloodyIron** [comment]
How is this going to look for mobile?

**Comment by bwindels** [comment]
This is way to big of a story. Replacing it with [multiple smaller issues](https://github.com/vector-im/riot-web/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22Redesign%3A+timeline%3A+%22).
