### ISSUE TITLE
JS console is being spammed with Promise being deprecated

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7409]
`Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.`

This started happening with the webpack 4 changes

**Comment by lampholder** [comment]
The last thing the console needs is more spam.

What's the right way to fix this? Silence the warnings? Or heed them?

**Comment by turt2live** [comment]
I'd vote for fixing them. They seem to be coming from deep within the js-sdk, so this may be non-trivial to fix. I'm not sure suppressing them is a good idea given it's already at the deprecation stage and we risk forgetting about it and having it all break down on us.

**Comment by aaronraimist** [comment]
Doesn't look super difficult to fix

https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred

Example of a fix: https://github.com/matrix-org/matrix-react-sdk/pull/1292/files

**Comment by turt2live** [comment]
Hopefully they are all that simple...

**Comment by aaronraimist** [comment]
Actually I didn't turn them back on. I tried but it seems like when I did it turned the warnings back on for matrix-react-sdk and matrox-js-sdk too.

There are a few more I can do in matrix-react-sdk but I'm afraid there are a bunch that I'm not sure if I understand enough to be able to rewrite them.

**Comment by sparky-raccoon** [comment]
Not-so related to this topic, but do you know a way to turn off ALL console logs? I heard that logs are very important for you guys, but they might cause performance (possibly security) issues. Have you tried to hide them through a babelrc / webpack configuration? 

Thanks for the answer!

**Comment by turt2live** [comment]
@sparky-raccoon this is the kind of question that is better answered in #riot-web:matrix.org than on a github issue. To answer it though: performance is marginally impacted by the console logging as we don't spam it. Where there are security issues, please report them to us under https://matrix.org/security-disclosure-policy/

**Comment by t3chguy** [comment]
Bluebird is now gone :D
