### ISSUE TITLE
Make riotbot not noisy

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7413]
Either change synapse's default push rules to mute it, or have clients set a push rule for their bot before they invite it to mute it.  As per https://github.com/vector-im/riot-meta/issues/134

**Comment by ara4n** [comment]
yeah, sounds like a nice solution.

**Comment by turt2live** [comment]
Given it is a Riot feature, I assume having clients mute it is probably best. Would require changes to riot-android and riot-ios though.
