### ISSUE TITLE
Two spaces at the end of a line without other formatting sends raw <br/>

### ISSUE THREAD

**Issue by tulir** [vector-im/riot-web#7416]
Typing and sending (note spaces after foo)
```
foo  
bar
```
will result in
```
foo<br />
bar
```
being sent.

**Browser**: Firefox 62.0
**OS**: Ubuntu 18.04
**Version**:  4e4906605b2b matrix-org/matrix-react-sdk@5765d59132d1 matrix-org/matrix-js-sdk@9c9d8468a5de

**Comment by lampholder** [comment]
Huh, how odd.

To clarify, that `<br />` literally appears as part of the visible message rendered into the timeline.

**Comment by lampholder** [comment]
P2 because even though it's the worst thing when the composer doesn't faithfully represent what you've typed, typing
```
foo  
bar
```
is pretty rare and doesn't have real utility.

**Comment by turt2live** [comment]
Since this has been reported I've seen 2 people randomly fall victim to it. It's more common as a typo, probably.

**Comment by igh2** [comment]
> is pretty rare and doesn't have real utility.

and 

> Since this has been reported I've seen 2 people randomly fall victim to it. It's more common as a typo, probably.


...but that is how one creates line breaks in markdown - is it really that rare?

**Comment by tulir** [comment]
> that is how one creates line breaks

you can create a line break by creating a line break

**Comment by igh2** [comment]
I am actually seeing this now when using shift-enter to insert line breaks.  

The behavior of the editor appears to have changed a couple of times since last night.  Am I somehow getting automatic code updates?

**Comment by aaronraimist** [comment]
@igh2 if you are using riot.im/develop yes it's possible things may have changed.

If you are using riot.im/app then no, the code would be the same. It may be an intermittent failure or you may be doing it slightly differently causing a new failure.

**Comment by tulir** [comment]
Looks like this doesn't happen in the new composer :tada:
