### ISSUE TITLE
Can't download any files in E2E rooms in Safari

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7421]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Send .png file in a Riot room
- try to download it

Describe how what happens differs from what you expected.

Instead of downloading, a page like this appears.
![screen shot 2018-09-29 at 9 26 57 am](https://user-images.githubusercontent.com/5855073/46246918-d4c01100-c3c9-11e8-9d55-24fb0f3cec89.png)

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Safari Technology Preview Release 66 (Safari 12.1, WebKit 13607.1.7.2)
- **OS**: macOS 10.13.6
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
It looks like this occurs only in encrypted rooms.

**Comment by aaronraimist** [comment]
When I right click on the image and select open in new tab, I get a very similar `blob:https://riot.im/...` URL however not the same URL, and that URL works. I'm not sure why those URLs wouldn't be the same.

**Comment by aaronraimist** [comment]
Appears to be fixed in Safari 13 (or by some Riot change that I missed).
