### ISSUE TITLE
CONTRIBUTING.md points to Synapse, but we don't have towncrier

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7430]
Quote from https://github.com/matrix-org/matrix-react-sdk/pull/2186:
> Unrelated but I was somewhat confused as CONTRIBUTING.rst says matrix-react-sdk follows the same pattern as Synapse but there is no Towncrier in here as far as I can tell.

**Comment by lampholder** [comment]
Our docs should tell the truth.

Separately, should we be using towncrier?

**Comment by turt2live** [comment]
Ftr I had some thoughts over at https://github.com/matrix-org/matrix-react-sdk/issues/2186 - it might be beneficial to have the contributing document in one place for all of matrix-org/*, mentioning that individual repos may add onto it. Equally, that might be solving problems we don't have.

**Comment by ara4n** [comment]
please let’s not do towncrier; the current system isn’t broken.

-- 
Matthew Hodgson
Matrix.org

**Comment by aaronraimist** [comment]
> Ftr I had some thoughts over at [matrix-org/matrix-react-sdk#2186](https://github.com/matrix-org/matrix-react-sdk/pull/2186) - it might be beneficial to have the contributing document in one place for all of matrix-org/*, mentioning that individual repos may add onto it. Equally, that might be solving problems we don't have.

I think it makes sense to keep individual CONTRIBUTING files in each repo or at least one per GitHub organization. I like the idea that vector-im stuff is separated from matrix-org stuff (even though it is made by the same people).

**Comment by aaronraimist** [comment]
This got fixed by #7899
