### ISSUE TITLE
Thank you page for the TOS doesn't tell you what to do next

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7436]
The intent is that the user can simply close the tab (because it was opened in a new tab), but that isn't communicated at all

**Comment by lampholder** [comment]
So it doesn't :( 

Right now it looks like:
![image](https://user-images.githubusercontent.com/1922197/46349937-64282700-c64b-11e8-9ab6-fcdeb00d66a6.png)

The slight nuance is that (I think it's still the case that) the wording has to be appropriate cross platform, and on iOS/Android you don't have to close the browser tab.

@manuroe did you implement improved consent flow on mobile in the end? What does the user do to get back to the app on iOS/Android after providing consent?

**Comment by lampholder** [comment]
I think this would/could also be fixed by https://github.com/vector-im/riot-web/issues/7168.

**Comment by lampholder** [comment]
I think this was fixed by #7168 (it's true you can still trigger the orignal behaviour by configuring your homeserver to impose t's and c's acceptance after registration, but that's not affecting matrix.org users and it will be rare that non matrix.org users want to run that configuration).
