### ISSUE TITLE
riot upgrade 0.16.4 -> 0.16.5 can not restore session

### ISSUE THREAD

**Issue by user318** [vector-im/riot-web#7437]
Hi. After upgrading riot web from version 0.16.4 to 0.16.5, it shows an error that it cannot restore the session and suggest to clear the data, logout and login again. Reverted back to 0.16.4 and error disappeared.
![screenshot-2018-10-2 riot](https://user-images.githubusercontent.com/671062/46340251-320bca80-c635-11e8-9707-191c5d05fa09.png)

**Comment by lampholder** [comment]
Hi @user318 - did you send logs when you encountered the issue?

Would you be happy to try upgrading again and send logs if you didn't?

Thanks!

**Comment by user318** [comment]
Hi @lampholder 
I surely can try load new interface and collect some logs. But do not know where to look for them. Some JS logs in browser?

**Comment by user318** [comment]
And I'm not sure that will work. Here is what I have in browser's console during interface load:
[log-load.txt](https://github.com/vector-im/riot-web/files/2438317/log-load.txt)

And when I try to send logs I get an error: "Failed to send logs: No connected database". I used local URL, not github, but I think it does not plays any role. This is what I have in console:
[log-send.txt](https://github.com/vector-im/riot-web/files/2438327/log-send.txt)

**Comment by JeremyRand** [comment]
I can reproduce this issue on the https://riot.im/app/ instance using Firefox 52.9.0 in Private Browsing mode.  Started happening circa 1-2 days ago IIRC.  Haven't yet tried to send logs.

**Comment by JeremyRand** [comment]
I get the same error as @user318 (`Failed to send logs: No connected database`) when I try to send logs via the https://riot.im/app/ instance.

**Comment by user318** [comment]
No issues with 0.16.6 now. I have switched now 0.16.4 -> 0.16.6 withoud such error.

**Comment by JeremyRand** [comment]
Yep, fixed here as well.
