### ISSUE TITLE
Composer: doesn't play nicely with OS-level input enhancements

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7441]
Inspired by https://github.com/vector-im/riot-web/issues/7440, aggregating the various composer/keyboard issues into a meta issue (these issue I think are _not_ related to the "dead keys don't work" bug):
- https://github.com/vector-im/riot-web/issues/7419
- https://github.com/vector-im/riot-web/issues/7218
- https://github.com/vector-im/riot-web/issues/7155
- https://github.com/vector-im/riot-web/issues/6101 (maybe)

**Comment by aaronraimist** [comment]
#7527

**Comment by lampholder** [comment]
#7535

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/7488

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/7639

**Comment by turt2live** [comment]
I think these are all https://github.com/ianstormtaylor/slate/issues/2368

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.
