### ISSUE TITLE
E2E Key Backup: Recovery key is a pickle of the Olm PkEncryption object which is several time longer than it needs to be

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7446]
Spilt out from https://github.com/vector-im/riot-web/issues/3661

**Comment by dbkr** [comment]
https://github.com/matrix-org/olm-backup/pull/61 exposes the appropriate functionality in Olm, rest of this is in the various dbkr/e2e_backups branches

**Comment by jryans** [comment]
(I am assuming this is fixed because it was marked as In Test. @dbkr, please reopen if incorrect.)
