### ISSUE TITLE
Blank read receipts with lazy loading

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#7449]
Lost of the little avatar bubbles for read receipts are blank until the member list is fetched. This looks a bit weird when you have a line of read receipts and they're full of gaps.

It might be nice to have some visual place holder for those avatars, or possibly not event display any read receipts until the members are loaded (to stop the slightly weird experience of only seeing a subset of receipts at first)

**Comment by turt2live** [comment]
Related/potential duplicate of https://github.com/vector-im/riot-web/issues/7260 (from more recent comments).

**Comment by erikjohnston** [comment]
Oh, didn't find it because I was searching for receipts.
