### ISSUE TITLE
User still in member list after leaving (with LL enabled)

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#7450]
I have a room with a bunch of people, someone left the room but they still appear in the right hand panel.

**Comment by erikjohnston** [comment]
(It's also possible this is a synapse issue, though it seemed more likely to be riot web.)

**Comment by bwindels** [comment]
The only thing that I can think off is that an exception occured after loading the members before `this._listenForMembersChanges();` got called. Would be very helpful to get a rageshake if this happens again. Going to park it for now.

**Comment by bwindels** [comment]
I wonder if this could be related to not tracking all left members properly and when you load members from storage again (which don't get updated as users leave) there is no indication the user has left in the mean time and is added again to the members. The sync data should contain all members the have left though, which should end up in the room state by the time members are loaded from storage...

**Comment by ara4n** [comment]
given we no longer do LL on incremental syncs, any leaves should have come down /sync.  So if the leaves aren't applied to the membership store, that'd explain things?

**Comment by bwindels** [comment]
Not really, as LL members from the store are only applied if the member is not already in the room state, which should be the case for any leave since you fetched the LL store members... but maybe our bookkeeping isn't 100% foolproof, just a hunch I had, wanted to jot it down somewhere.

**Comment by bwindels** [comment]
No significant errors in rage shake

**Comment by bwindels** [comment]
Managed to reproduce, just refresh the page after somebody left with LL turned on.

**Comment by bwindels** [comment]
Fixed
