### ISSUE TITLE
Infinite spinner on registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7451]
I thought we'd killed it, but it still lives.

Signed up today for a new matrix.org account using https://riot.im/develop and landed on an infinite spinner after email verification.

The ping rectangle error warning didn't appear either.

Fixed on a refresh.

**Comment by lampholder** [comment]
Please track any further instances of this here

**Comment by turt2live** [comment]
@lampholder do we have any instances of this today? Rageshakes? Any further information we can use for debugging?

**Comment by lampholder** [comment]
Nope, and with no further instances tracked here this is not a useful issue, esp with all the changes to registration - let's close it.
