### ISSUE TITLE
If you don't provide an email address at registration, you still sometimes see a flash of the 'email sent' screen,

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7457]

**Comment by lampholder** [comment]
A minor issue really, but a (very) early glitch in the users' experience of Riot.

**Comment by turt2live** [comment]
@lampholder I'm not seeing this. Do you have more information to reproduce it?

**Comment by lampholder** [comment]
Nope; it was reported by @AmandineLP and it felt like something I'd seen. I suggest we just put it to the bottom of the pile for now.

**Comment by ara4n** [comment]
this is being tracked elseplace

**Comment by lampholder** [comment]
@ara4n where?
