### ISSUE TITLE
Selecting multiple messages worth of text highlights the sender's avatar unexpectedly

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7460]
![riot-avatar-highlight-select-lines](https://user-images.githubusercontent.com/1190097/46504976-d2581f80-c7ec-11e8-9ea8-671ad53c89c8.gif)

**Comment by lampholder** [comment]
It would be lovely if highlighting + copy+pasting the message text 'just worked'

**Comment by z3ntu** [comment]
Would be a lot better if `mx_MessageTimestamp` , `mx_Flair` and `mx_EventTile_avatar` had a `user-select: none;` CSS attribute (I'll try to open a PR).

Ideally (in my opinion), multiline messages would put the username in front of every line instead of being in a separate line at the top

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2929

**Comment by z3ntu** [comment]
Also an extension of this issue is #893 . Interestingly, the option of using user-select was already discussed there but there was something about it not working correctly in browsers, but in chromium 73.0.3683.103, electron 4.1.4 and firefox 66.0.3 it works fine.
