### ISSUE TITLE
Widgets, Stickers, and Integrations dialog remain blank in Firefox 62.0.3

### ISSUE THREAD

**Issue by JoKeyser** [vector-im/riot-web#7467]
### Description
The Manage Integrations dialog and custom widgets remain blank in Firefox 62.0.3 (64-bit), Mozilla Firefox for Arch Linux - 1.0.
In contrast, both work fine when using Chromium, version 69.0.3497.100 (Official Build) Arch Linux (64-bit).

### Steps to reproduce
In Firefox I used *Help > Restart Firefox with Add-Ons Disabled* and disabled Tracking Protection.

#### Manage Integrations dialog
After clicking the button 'Manage Integrations':

![manageintegrations](https://user-images.githubusercontent.com/8722846/46613455-92a67600-cb13-11e8-8b52-67ccba171fbf.png)

#### Custom widget
When joining a room with a simple custom widget (here: https://matrix.org/docs/spec/client_server/r0.4.0.html), it says `Sorry, this content is not embeddable in Matrix`, and the console log's error is `Content is not embeddable Forbidden - Invalid Scalar access token`:

![widgetproblem](https://user-images.githubusercontent.com/8722846/46613902-b61df080-cb14-11e8-89aa-b421c4ed83d5.png)

### Version information

- **Platform**: Web (in-browser) on matrix.org, fresh account.
- **Browser**: Firefox version 62.0.3 (64-bit), Mozilla Firefox for Arch Linux - 1.0.
- **OS**: Arch Linux.
- **URL**: riot.im/app

**Comment by JoKeyser** [comment]
I hope these issues are related, let me know if I should split them up.

**Comment by JoKeyser** [comment]
Hm, I will test with my other Arch laptop (and then edit the comment here).

I now also tested adding Stickers, and it shows the same blank as the Manage Integrations dialog, maybe that helps in narrowing it down:

![stickers_broken_too](https://user-images.githubusercontent.com/8722846/46627777-d8773480-cb3b-11e8-942f-0838ca9dbfaf.png)

**Comment by dreszczyk** [comment]
I've installed whole system today and I want to confirm, that the stickers window is blank. I'm using Chrome 71 dev.

**Comment by aaronraimist** [comment]
@bart:fam-ribbers.com is having this issue https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1540052025931NqfWr:fam-ribbers.com

(I can't reproduce)

**Comment by dannycolin** [comment]
@JoKeyser are you blocking third-party cookie? I had a similar problem and adding an exception for https://scalar.vector.im in the Firefox's cookie settings solved it.

**Comment by patrickschneider23** [comment]
[ `` ](url)

**Comment by JoKeyser** [comment]
@dannycolin omg thanks, I didn't realize that I rejected 3rd-party cookies. After adding the exception https://scalar.vector.im, widget dialog, custom widget, and stickers dialog work.
Sorry everyone, that was clearly my oversight.

I'll close here; of course project members should re-open if they think it's valuable to track the similar issues mentioned above.

**Comment by dreszczyk** [comment]
> @dannycolin omg thanks, I didn't realize that I rejected 3rd-party cookies. After adding the exception https://scalar.vector.im, widget dialog, custom widget, and stickers dialog work.
> Sorry everyone, that was clearly my oversight.
> 
> I'll close here; of course project members should re-open if they think it's valuable to track the similar issues mentioned above.

How do I enable third party cookies in Chrome?

**Comment by dannycolin** [comment]
@dreszczyk by downloading Firefox :P or maybe this link could help you https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en

**Comment by c-e-p-x-u-o** [comment]
same on chromium 70.0.3538.67-2 on debian sid
