### ISSUE TITLE
Extremely long link preview

### ISSUE THREAD

**Issue by nukeop** [vector-im/riot-web#7469]
### Description
Example link: https://play.google.com/store/apps/details?id=com.gombosdev.ampere
This will generate a preview that's around 2-3 screens long in a moderately sized window.

### Steps to reproduce

- Send the link above to any channel

**Describe how what happens differs from what you expected:**
The preview length should be capped at a reasonable length.

Log: N/A

Screenshot below
![screenshot](https://i.imgur.com/VZuMfSw.png)

### Version information
0.16.5

- **Platform**: web (in-browser) or desktop?
Web

- **Browser**: Firefox Nightly 64
- **OS**: Linux Mint
- **URL**: riot.im/app

**Comment by lampholder** [comment]
Dup of https://github.com/vector-im/riot-web/issues/2894 (though that bug says this should be fixed in Synapse, and it appears not to be)
