### ISSUE TITLE
Missing public GPG key for the latest release

### ISSUE THREAD

**Issue by lbeltrame** [vector-im/riot-web#7470]
### Description

GPG key A13D232B is not present in the keyservers I checked (MIT, GnuPG, SKS). It is important to have it available to verify the authenticity of the tarball.

### Version information

Version 0.16.6.

**Comment by bwindels** [comment]
Hi, thanks for reporting this. As I released Riot for the first time, we added a key for me, which is the one you are seeing. I tried publishing the master and subkeys again to pgp.mit.edu, but getting occasional proxy errors trying to query it back. Could you try if republishing worked for you?

**Comment by lbeltrame** [comment]
```
gpg --keyserver pgp.mit.edu --recv-keys A13D232B 
gpg: requesting key A13D232B from hkp server pgp.mit.edu
gpg: key 48E8F4A1: "riot.im (Package Signing key) <packages@riot.im>" 5 new signatures
gpg: key 48E8F4A1: "riot.im (Package Signing key) <packages@riot.im>" 1 new subkey
gpg: non è stata trovata alcuna chiave definitivamente affidabile
```

**Comment by bwindels** [comment]
Guess it worked then?

**Comment by lbeltrame** [comment]
Took a few tries, but yes.
