### ISSUE TITLE
Composer loses focus after typing emoji

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7472]
...if it's the first character you type in the composer.

I'm using the OS X emoji picker here: unsure if there's a way to repro it on other platforms. Focus composer, ctrl+cmd+space, pick an emoji, emoji goes into composer, press another letter, nothing happens. If you press space, you get a space and can carry on typing.

Having looked into this a little, the selection in the DOM is moving to the sticker button in the time between the composer's componentDidUpdate and a setTimeout(,0) in componentDidUpdate.

```
componentDidUpdate() {
        console.log("i dun updated");
        const s = window.getSelection();
        console.log("selection anchor: ", s.anchorNode); // <-- prints the last text node in composer
        setTimeout(function() {
            console.log("selection anchor: ", s.anchorNode); <-- prints sticker button
        }, 0);
    }
```

**Comment by dbkr** [comment]
Ah yes, I thought I filed this, but failed to find it again. Thanks!

**Comment by dbkr** [comment]
More interestingly, I can repro this on the slatejs.org examples *if* I edit the HTML to put `<div>hello</div>` right after the content-editable div.

**Comment by lampholder** [comment]
I really wish you could merge issues on github, but you can't, so I'm going to copy+pasta everything Dave's said here onto #7281

**Comment by lampholder** [comment]
Closing this in favour fo #7218
