### ISSUE TITLE
riot.im website references old Ubuntu version

### ISSUE THREAD

**Issue by kristbaum** [vector-im/riot-web#7474]
### Description

The riot.im [download page for the electron app](https://riot.im/desktop.html) lists "artful" as the default release (both in the text and the command), this should be replaced by "bionic". This should be the default until Ubuntu 20.04 LTS.

**Comment by lampholder** [comment]
I agree it should be up-to-date; I'm neutral as to wheter we update the commands on the site to keep pace with each release or only bump in line with Canonical's LTS releases.

**Comment by turt2live** [comment]
@nadonomy another fix, though this might be @lampholder territory.

**Comment by lampholder** [comment]
Ugh, it's out of date again, pesky page.

Out of date _and_ still purple (https://github.com/vector-im/riot-web/issues/8893)

@dbkr what can we do to make this suck less?

**Comment by aaronraimist** [comment]
This has been fixed
