### ISSUE TITLE
Attempting to reset password through forgot password has you to "export" E2E keys

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7475]
### Description

**Not** a security issue. Just a UI bug.

When you use the forget password interface, it allows you to "Export E2E room keys" which seemingly completes (would be a security issue) but it doesn't actually export anything sensitive. This could mislead someone into thinking they did backup their E2E keys though.

![screen shot 2018-10-10 at 6 51 00 pm](https://user-images.githubusercontent.com/5855073/46772402-78a89700-ccbd-11e8-97f8-928a7c9a502e.png)

### Steps to reproduce

- Attempt to reset password through forgot password mechanism
- Warning appears telling you to export E2E room keys

The warning should appear but button allowing you to export E2E keys should not appear (unless you are logged in and it *can* actually export the E2E keys

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 69.0.3497.100
- **OS**: macOS
- **URL**: riot.im/app 0.16.6

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/6681
