### ISSUE TITLE
Update electron single instance API

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7481]
Electron sez:

```
'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
```

**Comment by t3chguy** [comment]
I swear I did this somewhere, it's probs lost in a feature branch somewhere

**Comment by t3chguy** [comment]
It is already the case, just the api to do so is changing. When you try and launch a new riot it just opens the minimised one

**Comment by dbkr** [comment]
Yeah, it's not important, until Electron remove the API, at which point it will suddenly become important. :)

**Comment by Kattihatt** [comment]
I'm still having this issue and it prevents riot-web from starting on my system.

**Comment by t3chguy** [comment]
@Kattihatt that sounds unlikely, deprecation warnings are exactly that, warnings, they do not affect the operation of the software. More likely is something else is going wrong, describe your symptoms in more detail.

**Comment by adisubektie** [comment]
root@tux# riot-web
riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by riot-web)
/opt/Riot/riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Riot/riot-web)
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform

root@tux# ll libdbus-1.so.3
lrwxrwxrwx 1 root root 18 Des  7  2016 libdbus-1.so.3 -> libdbus-1.so.3.7.6

same issue.

**Comment by t3chguy** [comment]
This has since been fixed by https://github.com/vector-im/riot-web/commit/60d307603873b4a6e9630fafea986e3d1589d5f8
Any crashes you may have, open new issues for.
