### ISSUE TITLE
Firefox double emoji

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7482]
Inserting emoji with the OS X character picker on firefox causes double emoji to appear in the composer, one emojione and one native. There is only actually one in the composer state: if you hit send, you just get a single emoji, but it's failing to remove the native one from the content-editable div.

**Comment by turt2live** [comment]
@dbkr are you still seeing this? I think it might be either https://github.com/vector-im/riot-web/issues/7550 or https://github.com/vector-im/riot-web/issues/7488

**Comment by turt2live** [comment]
@aaronraimist is that specifically on OS X?

**Comment by aaronraimist** [comment]
@turt2live Yes, I don't really know how to get a macOS like emoji picker in Ubuntu.

**Comment by turt2live** [comment]
I'm going to add it to https://github.com/vector-im/riot-web/issues/7665 as somewhere in the chain describes the same behaviour in Slate. Closing in favour of that.
