### ISSUE TITLE
if you enter emoji via the OS picker and then try to copy-paste it to duplicate it, it overwrites rather than appends

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7488]
the same is then true of non-emoji too - e.g. if you say 🍤a🐼 into a fresh composer and try to copy-paste the a, it can replace everything else there. on Chrome 69

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.
