### ISSUE TITLE
No noise, badge, or highlight on encrypted pings

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7489]
I received a ping in an encrypted chat, and it didn't get a badge in the room list, noise, or even have the message highlighted :(

My push rules don't appear to be preventing it either.

**Comment by lampholder** [comment]
There are some caveats around notifs and e2e: my understanding of what _should_ have happened (informed by @dbkr):
- the message should be highlighted
- you should get the sound
- you won't get a badge
- you won't get a push notification

**Comment by ara4n** [comment]
presumably at the least we can calculate the badge clientside. oh, except currently they're entirely managed by the server?

**Comment by ara4n** [comment]
adding to FiP as "i turned on encryption and my notifications no longer work, but they work on riot/mobile so why don't they work on riot/web?" is a pretty big WTF moment.

**Comment by turt2live** [comment]
ftr, having tested this in some more detail the lack of noise does in fact appear to be a me problem and not a problem for Riot. The lack of badge and highlight is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/851

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/851

Follow up is https://github.com/vector-im/riot-web/issues/9069
