### ISSUE TITLE
User settings window borders should be easier to identify

### ISSUE THREAD

**Issue by airblag** [vector-im/riot-web#7492]
### Description

When opening the user settings, the only indication of the limits of the settings overlay window are the text and the small closing X on the top right.

One of my user thought he couldn't scroll down the settings window, because his mouse was too far on the right size (he is working with a huge monitor, so the white space on the sides of the settings are quite big).

All 3 themes (light, dark, status.im) have the same issue.

Changing the background color of the settings window to be different than the rest, giving the settings window the whole space (since you cannot interract with anything else when it's open), or maybe a small separator line like the one one splitting the room list from the rest could increase the user experience

### Version information

- **Version**: 0.16.5

**Comment by lampholder** [comment]
The redesign is going to take a swing at the settings UX, too, so we should address this then. (Redesign is in flight now)

**Comment by turt2live** [comment]
Fixed
