### ISSUE TITLE
When the homeserver responds to /publicRooms with not-200, we retry straight away

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7497]
which leads to sluggish UI and my server getting harassed. I would have probably expected the directory to give up on anything that isn't a timeout.

### Steps to reproduce

- Have a buggy homeserver that emits 500s when calling ``/publicRooms``
- Click room directory
- A error prompt will open, but will flicker. If you open the developer tools, it will show lots of network requests.

Describe how what happens differs from what you expected.

### Version information
- **Platform**: web desktop
 server, what version of riot-web?

- **Version**: 0.16.5

**Comment by Half-Shot** [comment]
This is caused by https://github.com/matrix-org/synapse/issues/4039 on the synapse side.

**Comment by Half-Shot** [comment]
Did more debugging today, will also do it if it's not even online.

**Comment by jryans** [comment]
This appears to also be fixed with https://github.com/matrix-org/matrix-react-sdk/pull/2834. I only see one request to `/publicRooms` now.
