### ISSUE TITLE
'known vulnerability' room version warnings. Post #7331

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#7510]
2018-10-16 17:23 UTC

1:1 chat, invited user to room, they saw the room vuln warning for about 30 seconds, then it disappeared. It sounds like a race condition but my understand was that #7331 should have eradicated these warnings.

Room ID !MbjyFdYziYNGQLVhgA:matrix.org
Room version 1

**Comment by neilisfragile** [comment]
though user using install from arch - they may have had a pre v17 release

**Comment by turt2live** [comment]
I really hope the warning doesn't show up in 0.17 erroneously :(

**Comment by neilisfragile** [comment]
They confirmed it was pre v17. So I wouldn't object to this issue being closed.
