### ISSUE TITLE
No members shown on the right in "communities", no way to add an admin in communities

### ISSUE THREAD

**Issue by adalvigi** [vector-im/riot-web#7511]
### Description

Under the "members" section of my community, I can't visualize any of the members. I also have no way to set users as admins, how should it be done?

### Steps to reproduce

Just go to the communities panel and try to click on "members"

### Version information

- **Platform**: desktop

- **OS**: Happens on both Windows and Ubuntu
- **Version**: 0.17.0

**Comment by adalvigi** [comment]
It does the same on the Web browser version, it's getting annoying

**Comment by adalvigi** [comment]
I think I may have understood where the error may be: on the left, where there are rooms and users you have chats with, it actually shows the ones which are in the community, but you have no "community settings" (like make admin) for them, I don't even see the admin status of a friend who created his community and added me. These things should instead be shown on the right, leaving the left side with the "global" rooms and chats for the user.

**Comment by turt2live** [comment]
Not being able to add other administrators is tracked here by the way: https://github.com/vector-im/riot-web/issues/5240

**Comment by BrotherWarrior** [comment]
I have the same problem. In web-version 16.4 all memers of community shown properly in members section, but in desktop version 17.0 all communities has no members, members section is empty. I can invite users to community, but members list is still empty (no invited users, no members)

**Comment by phil-flex** [comment]
![image](https://user-images.githubusercontent.com/34325924/47199698-6dccc100-d3a5-11e8-833d-f2d85d037585.png)
I have the same problem in version 0.17.1.

**Comment by turt2live** [comment]
This should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2223

The admin stuff is tracked over at https://github.com/vector-im/riot-web/issues/5240
