### ISSUE TITLE
Instability on Windows 7

### ISSUE THREAD

**Issue by colonelkrud** [vector-im/riot-web#7512]
### Description

Riot becomes unresponsive after normal use on windows 7. *Creating issue on behalf of user @cacMac*

### Steps to reproduce

- Launch Riot desktop
- connect to room
- tab out of riot
- receive image in room
- tab in to riot to view image
- windows task manager calls riot unresponsive
Possible issue with image event lazy loading and windows 7 sp1

Log: sent   

### Version information

- **Platform**: Desktop

- **OS**: Windows 7 SP1
- **Version**: 0.17.0

**Comment by turt2live** [comment]
Potentially maybe related: #7507

**Comment by wareya** [comment]
Same here, though it seems to basically happen randomly too.

**Comment by dbkr** [comment]
I've reproduced this crash (although just the instructions above didn't do it - I'm unsure what did in the end). This is presumably a regression in Electron 3. Trying to find out more...

**Comment by colonelkrud** [comment]
Unfortunately I am on a different platform entirely and can not help reproduce this issue. I submitted this bug on behalf of another user of my homeserver. He claims that the crash is most consistent when he hears a notification on riot and then tabs/switches focus back to the app. It does happen randomly but seems to happen more consistently when receiving image events. 

The user has an older os, Windows 7 sp1. It is possible that this is the same electron issue you mentioned but it behaves differently on the older version of Windows. 

I have however noticed a slight lag on my system when trying to reproduce the issue. I am running the same version of the desktop app but have Mac 10.10.5 running. It is difficult to explain and does not leave a noticeable log.. but it is like the app hesitates when switching focus to view a message.

**Comment by shkshk90** [comment]
Hello, 
I am facing this same exact issue.
I tried to debug using VS2017, but I can't get anything useful.
There seems to be a random Null pointer dereference happening somewhere, but I get no further info about the causes.
This issue does indeed happen more consistently when there's a new notification and I switch to Riot's window.
If there's anything I can submit, I am willing to help.

**Comment by dbkr** [comment]
I've finally managed to get the electron debug symbols and track this down: electron is NPEing when we try to dismiss a notification.

**Comment by dbkr** [comment]
Upstream bug: https://github.com/electron/electron/issues/15251

**Comment by linuxmail** [comment]
Hi,

my colleague had also massive problems with 0.17 and reverted to an older (0.16.5) version back. He tried now the 0.17.1 version and instead of just a crashing Riot, the whole Windows7 had a problem, because of a massive ram usage with more than 5GB from Riot.
Sounds like a memory leak.

**Comment by linuxmail** [comment]
Hi,

my colleague had also problems with 0.17.0 and tried 0.17.1. This version is not only crashing, he said, that Riot tooks over 5GB of memory, until he had to kill the process, before his Windows7 becomes completly unresponsible. We is only in a few small rooms .. on a private Matrix host.

**Comment by colonelkrud** [comment]
> Hi,
> 
> my colleague had also massive problems with 0.17 and reverted to an older (0.16.5) version back. He tried now the 0.17.1 version and instead of just a crashing Riot, the whole Windows7 had a problem, because of a massive ram usage with more than 5GB from Riot.
> Sounds like a memory leak.

You should open a new issue for 0.17.1 about the memory leak and post logs. It is likely a separate issue as this issue has been resolved. I mean it could be a result of this fix, I don’t know. Really should be a new issue though as this one is closed.
