### ISSUE TITLE
olm missing from package-lock.json

### ISSUE THREAD

**Issue by Ralith** [vector-im/riot-web#7522]
Has the lockfile not been updated in a while? This makes it very difficult to produce a NixOS package of riot.

**Comment by MTRNord** [comment]
I dont think optionalDependencies get locked. The olm dep is optional in the package.json:

```
"optionalDependencies": {
    "olm": "https://matrix.org/packages/npm/olm/olm-2.2.1.tgz"
},
```

**Comment by Ralith** [comment]
All the documentation I can find says they do. It also seems like package-lock.json has been obsoleted by npm-shrinkwrap.json, which suggests that the file has not been updated for a long time indeed. When I create a npm-shrinkwrap.json myself, it contains the "optional" dep and works fine.

**Comment by lampholder** [comment]
> FWIW, I'm pretty sure I've experienced the same problems that you're describing while updating the riot-electron-nix package. 😿

Do we need documentation/better documentation?

**Comment by eqyiel** [comment]
@lampholder I'm not sure, but it would be good to know what the consequences are of packaging `riot-web` without `olm` (since it's optional).  AFAICT it's a module used for E2E but that's the extent of my knowledge on the matter. 😅

**Comment by lampholder** [comment]
Hi @eqyiel - olm is indeed used for E2E encryption; tbh I'm not exactly sure what happens when you package Riot without it. I'm 100% certain that encryption won't work, and I'm maybe 80% certain the UX will do the RightThing too (i.e. not let you try and turn on encryption when it's not going to work because your client doesn't support it).

**Comment by Ralith** [comment]
It looks like this has been fixed, though npm is still making reproducible packaging an utter nightmare.
