### ISSUE TITLE
Ctrl+Left broken when pills present

### ISSUE THREAD

**Issue by aidalgol** [vector-im/riot-web#7527]
### Description
<kbd>Ctrl</kbd>+<kbd>Left</kbd> when there is a pill in the message composer does not move the cursor left a word at a time, but instead moves only one character at a time.

### Steps to reproduce
1. Insert a pill for a user in the current room (either by clicking the user's name, or via tab-completion).
2. Enter multiple words of text (e.g. <kbd>Testing this bug.</kbd>)
3. Type <kbd>Ctrl</kbd>+<kbd>Left</kbd> and observe the cursor movement.

### Version information
- **Platform**: desktop
- **OS**: Debian GNU/Linux 9.5
- **Version**: 0.17.0 (installed via Flatpak from Flathub)

**Comment by aidalgol** [comment]
I have not rolled back to a previous version to be 100% sure, but I think this is a regression in 0.17.0.

**Comment by aaronraimist** [comment]
Yes, seems to be related to upgrading Slate.

This feature works in v0.16.6 and is broken on /develop.

**Comment by lampholder** [comment]
On a mac, ctrl+left/right move to the start/end of line, and alt+left/right moves word by word. And both are broken in Riot.im composer when there's a pill in there (fine when there isn't).

**Comment by rkfg** [comment]
This seems to be fixed in 0.17.3 for me.

**Comment by aaronraimist** [comment]
Yes seems fixed for me as well. @lampholder ready to close?

**Comment by turt2live** [comment]
Fixed here too. Closing.
