### ISSUE TITLE
Add bulk verification

### ISSUE THREAD

**Issue by natrius** [vector-im/riot-web#7528]
### Description

When someone new joins an encrypted room it is needed to verify every single key from who he don't know and that can sometimes be exhausting. 

Add an option to bulk-verify keys, either check-boxes and "Verify all checked" or one button for the user "Accept all keys from this user" or something like that. I have more than one guy with something between 2 and 8 devices. 

Its clear that it somehow violates the security aspect and a proper warning before proceeding would be fine too. And it would still be faster.

### Version information

- **Platform**: desktop (probably web too?)

- **OS**: Windows, Ubuntu
- **Version**: 0.17.0

**Comment by aaronraimist** [comment]
You don't need to verify all devices. You only need to verify people's devices if you want extra security. 

Cross signing will greatly improve the verification experience if you do choose to verify https://github.com/matrix-org/matrix-doc/issues/1680

**Comment by lampholder** [comment]
Yeah, the bulk of this problem should go away with the E2E improvements in flight - the idea is that everyone in the room should already have cross-signed all their devices (because it should be easy and part of the default flow of the app as you register/sign in), so when you join you only need to verify once per user (if you want to verify at all, as per what @aaronraimist said). The UX should also be much less warning-triangle-tastic if you do choose not to verify every user in the room.

**Comment by lampholder** [comment]
I'm putting `wontfix` on this because if this is still a problem post redesign then the redesign has (at least in part) failed. We can revisit then.

**Comment by natrius** [comment]
Just to add something: When logging out and in i have to do all the verification again. Thats really annoying O.o
Just wanted to switch between 2 users to test some things and i will now end up installing a second client.

**Comment by t3chguy** [comment]
You can pass a profile arg to the desktop client to have multiple profiles

**Comment by natrius** [comment]
In case someone is searching i put together the following (for Windows ofc):

Create a riot.cmd file wherever you want where you add the following line.
`START "" "%LOCALAPPDATA%\riot\Riot.exe" --profile=profile1`
Now you can start your original riot.im application with your original account and the riot.cmd with the new profile for testing purposes for example.

**Comment by vilim** [comment]
Was there any actual resolution of this issue? We are a group of 15 people, many of us using 2+ clients, which makes verification of every two pairs extremely impractical

**Comment by t3chguy** [comment]
> many of us using 2+ clients, which makes verification of every two pairs extremely impractical

With cross-signing in versions 1.6+ this doesn't matter.
You verify each other person (once)
You verify each of your own devices (once)

**Comment by vilim** [comment]
Ok, sorry, I guess the issue is that not everyone has verified their own devices.
Some bulk verification option for a group (during e.g. a video call or an in-person meeting) would still be nice: if I am not mistaken, with 15 people it is 210 verifications in total that need to be done for a room to be completely verified.

**Comment by natrius** [comment]
Well, you are wrong @vilim its 15 verifications. No matter how many devices are used. Because you just verify the user and not the device anymore. But that means that everybody should have verificated all of his own devices, of course :)

**Comment by vilim** [comment]
Sorry, maybe I am on an older server instance, but in our case each person has to verify each other person (which is 15x14 verifications), I can find no option to broadcast verifiedness. E.g. each person who I haven't verified yet with the emoji reciting procedure has this in their profile:

![image](https://user-images.githubusercontent.com/3041236/86006420-35083a80-ba16-11ea-936d-de9810721df3.png), 

leading to a proliferation of the little red shields everywhere

**Comment by t3chguy** [comment]
Yes, you are definitely on an old Riot as I told you on another thread about Redactions.

That section looks entirely different as of 1.6.x

![image](https://user-images.githubusercontent.com/2403652/86006697-464d4900-ba0e-11ea-882e-4bc3ffd35549.png)
