### ISSUE TITLE
Adding 2 aliases results in 2 state event messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7531]
The first one has just one of the aliases, and the second has both

**Comment by lampholder** [comment]
Is this grim but not actually problem-causing?

**Comment by aaronraimist** [comment]
I don't think it causes any problems, it just looks bad.
![screen shot 2018-10-23 at 11 05 19 am](https://user-images.githubusercontent.com/5855073/47374444-90b3e980-d6b3-11e8-9a4b-51ee28ed6c1d.png)

**Comment by richvdh** [comment]
this seems to be a dup of https://github.com/vector-im/riot-web/issues/5035

**Comment by turt2live** [comment]
Yea, although at the time of filing #5035 there wasn't a UI bit to go with it. Will use #5035 to track though.
