### ISSUE TITLE
Spacebar not functional after emoticon

### ISSUE THREAD

**Issue by Noisefever** [vector-im/riot-web#7537]
### Description

If I type a emoticon like ":D", I can't enter space anymore. The emoticon selection pops up but I cant choose the first suggestion. Space does not do anything. I can just type enter or another character, but that will result in not translating the emoticon.

Even if I deactivate the emoticon translation, I can't type space after an emoticon. So I can't continue typing after an untranslated emoticon like for example ":D".

### Steps to reproduce

Windows Client! Just try to type: "hello :) I want to type this but I cant."

### Version information

- **Platform**: Windows 10
- **OS**: Windows
- **Version**: 0.17.1

**Comment by lampholder** [comment]
dup of: https://github.com/vector-im/riot-web/issues/7509
