### ISSUE TITLE
make /join accept room ids, for power users without url bars

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7543]

**Comment by t3chguy** [comment]
should it also accept a server_name if you want to join a room over federation then?

**Comment by turt2live** [comment]
related: https://github.com/vector-im/riot-web/issues/3248
also related: https://github.com/vector-im/riot-web/issues/2925

we could probably use the same approach from https://github.com/vector-im/riot-web/issues/2925 to make it work correctly. An MVP would be just to hope/assume the user is already in the room and they just want to go there.

**Comment by lampholder** [comment]
I would dearly love for this to be addressed in a way that also solved #3248 so that I can direct my electron client to visit matrix.to links :)

**Comment by turt2live** [comment]
(for #3248 I was thinking of a `/goto <url>` command. `/join` could probably also accept a matrix.to URL with all the server information introduced in the solution for #2925 and magically work)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2272
