### ISSUE TITLE
[Feature Request] Notifications popup in OS, "Accept/Reject" instead of just "View" (call)

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#7546]
I'm on Ubuntu with XFCE, the environment notification pops up when someone calls me, but just says "View", I think it'd be great if we could get "Accept/Reject" in the OS notification styling.

**Comment by aaronraimist** [comment]
Duplicate of #11705

Looks like you forgot you opened this :)

The newer issue has more details so I'll close this old one

**Comment by BloodyIron** [comment]
@aaronraimist LOL well I did post this over a year ago, bound to forget it XD

But yeah, I agree, close this one, keep other one open.
