### ISSUE TITLE
Devtools buttons are indented funny

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7548]
![image](https://user-images.githubusercontent.com/1190097/47412148-15404f80-d728-11e8-95ac-cb1eee3d5f7a.png)

Regression due to https://github.com/matrix-org/matrix-react-sdk/pull/2231

**Comment by jryans** [comment]
I am happy to attempt this if you haven't started on it yet.

**Comment by turt2live** [comment]
@jryans by all means, go for it :)

**Comment by t3chguy** [comment]
Out of interest, how is `/devtools` a First Impressions thing :o?

**Comment by turt2live** [comment]
The dialog buttons being on the right was, and that broke the dialog. Was more added to the board so I didn't forget.

**Comment by turt2live** [comment]
This happened: https://github.com/matrix-org/matrix-react-sdk/pull/2252
