### ISSUE TITLE
Avatars can get out of sync with the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#755]
Very bizarre bug on a sluggish network (in-flight wifi) - the bottom two lines were sent by me, not Fil, but have been treated as a continuation of his?!

<img width="1004" alt="screen shot 2016-01-24 at 15 25 08" src="https://cloud.githubusercontent.com/assets/1294269/12538710/c684cf46-c2ae-11e5-8b3f-7b01d4f87dbd.png">

**Comment by Kegsay** [comment]
Amandine reproduced this today. It seems to be purely UI-based. The event JSON seemed fine. The logged in user ID seemed fine. Refreshing the window made everything appear correctly. My guess is that continuation logic is broken.

**Comment by ara4n** [comment]
i think this probably got fixed by ribot
