### ISSUE TITLE
Emoji multiply when inserting multiple at a time

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7550]
Inserting more than one emoji into the composer at once (eg. paste a string with multiple emoji or quote a message with multiple emoji) causes extra copies of the emoji to be inserted.

Looks like it may be causing problems here: https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1540355358213387PVppP:matrix.org

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2247
