### ISSUE TITLE
Clarification request

### ISSUE THREAD

**Issue by MayhemBill** [vector-im/riot-web#7554]
I've been looking a team Collab alternative to NextCloud, and this seems to be something along what I need, however I'm a little confused.

Is this meant to be run on it's own, or do I need to run another service along side of it?

I'm asking because this is referred to as a client, but I can't seem to figure out what the server part is supposed to be; unless this is standalone.

**Comment by t3chguy** [comment]
Any matrix server e.g github.com/matrix-org/synapse

**Comment by MayhemBill** [comment]
And with Synapse, I can create my rooms and such on there? eg private rooms and such?

**Comment by t3chguy** [comment]
Yes. This is more a question for a chat room rather than an issue. Maybe research how Matrix works, what federation of rooms means and other such concepts. For further questions I'd suggest the Matrix Room `#matrix:matrix.org` or `#riot:matrix.org`

**Comment by MayhemBill** [comment]
So I do need to run other software beside this one

**Comment by t3chguy** [comment]
If you just want basic functionality, I.e no bridges or bots or LDAP integration then yes.
