### ISSUE TITLE
Regression in 0.17: tray icon is now tiny in KDE Plasma

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/riot-web#7555]
### Description
Upon upgrading to version 0.17, Riot's tray icon in KDE Plasma is tiny.

### Steps to reproduce
- Use KDE Plasma
- Upgrade to Riot 0.17
- Look at the tray icon. As of 0.17, it looks like this:
![tiny tray icon](https://user-images.githubusercontent.com/1097249/47474414-0a42f900-d7d4-11e8-95fe-1b9d81db8991.png)
As you can see, all other tray icons are fine. Riot's tray icon was fine too, until upgrading to Riot 0.17. No other updates were performed.

### Version information
- **Platform**: desktop
- **OS & VERSION**: Kubuntu 18.04 with KDE Plasma 5.12.7. Riot 0.17.

**Comment by lampholder** [comment]
AMAZING.

I guess this is an (undesirable) side-effect of having bumped the electron version :(

**Comment by mortlind** [comment]
Is there any news or workarounds for this issue? I have suffered from it for some months now. It does not make the application defunct, but it makes it very hard to see on the icon, whether there are notifications.

**Comment by omakuta** [comment]
Indeed, same here. It seems ignored.

**Comment by ashledombos** [comment]
Indeed same here. I hope this issue is not ignored.

**Comment by croulibri** [comment]
I am with KDE 5.14 on Debian testing and the tray icon is unfortunately still a blurb green square, that turns pink when a message arrives.
Riot is up to date with Riot Debian repository (https://riot.im/packages/debian/)

I think the resizing of the icon is not working :-(

**Comment by QUASARFREAK** [comment]
Same here running the latest KDE Neon 5.15

**Comment by fundatillus** [comment]
On KDE Neon 5.15.1, installing the suggested package `indicator-application` fixed the size problem... but is this the correct icon? 

![riot-icon](https://user-images.githubusercontent.com/33880759/53137404-adbcd400-3550-11e9-98cc-68f9344ae26e.png)

**Comment by fundatillus** [comment]
On a fresh Debian 9 install, I see the small icon when [installing from the repository](https://github.com/vector-im/riot-web#desktop-installation-for-debian-stretch), but [building from source](https://github.com/vector-im/riot-web#building-from-source) and [running as a desktop app](https://github.com/vector-im/riot-web#running-as-a-desktop-app) using `node v8.15.0` and `npm v6.4.1`, which uses `electron v4.0.5`, results in a properly sized and functioning icon.

**Comment by Pointedstick** [comment]
Yep, fixed for me too now.

**Comment by akontsevich** [comment]
@Pointedstick, please reopen the bug: issue still exists if libappindicator1 and libappindicator3 uninstalled or libayatana-appindicator1 or 3 used.

**Comment by mortlind** [comment]
I agree with @akontsevich

**Comment by aaronraimist** [comment]
@lampholder is that confirmed? Did you find an issue on Electron? Have they fixed it in a more recent version?

**Comment by yannicka** [comment]
I'm using KDE Plasma and I see this (Riot 1.6.0):

![image](https://user-images.githubusercontent.com/22885898/82261866-1e26f080-9960-11ea-8be8-8e93fcda5e10.png)

Is it fixed?

**Comment by t3chguy** [comment]
Assuming fixed unless someone complains otherwise
