### ISSUE TITLE
Redesign: polish room list

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7567]
- [x] use SVG icon instead of "+" character for add room button
- [x] fix chevron clipping
- [x] polish margins
- ~~show correct context menu icon on room tile hover~~
- [x] style context menu button
- [x] bring back "filter rooms" field
- [x] polish/align badge with design 
- [x] add border around badge same as background color
 - [x] if not done sooner, show room section header badge also when section is expanded (not collapsed).

Questions:
 - Where do the mute settings go? Design for context menu does not have them.

**Comment by bwindels** [comment]
@nadonomy just about knowing what to do with the mute settings.

**Comment by bwindels** [comment]
Nad will have a look at making the margins a bit denser by the end of next monday, I'll implement the ones in the current design for now.

**Comment by bwindels** [comment]
Put the remaining work for the context menu in https://github.com/vector-im/riot-web/issues/7666, so we can close this.

**Comment by bwindels** [comment]
Interesting, thanks for reporting (here is fine). @nadonomy I guess this might tie into our font choice?

**Comment by bwindels** [comment]
Hmm, maybe it's just a matter of lowering the font-weight.

**Comment by bwindels** [comment]
Yeah, changing the font-weight from 600 to 599 seems to only affect the non-latin typography in Nunito.
![fw-600](https://user-images.githubusercontent.com/274386/49573962-2c817800-f937-11e8-9c7e-21d7f8d9bcd0.png)
![fw-599](https://user-images.githubusercontent.com/274386/49573963-2c817800-f937-11e8-97b8-ec577b0c971f.png)

**Comment by nadonomy** [comment]
This is super interesting. Definitely some inconsistencies across different character sets in Nunito:

![languages](https://user-images.githubusercontent.com/4626865/49576002-027e8480-f93c-11e8-9940-2211e7fea05b.png)

Need to explore and ponder a bit more on how we can solve this better.
