### ISSUE TITLE
Redesign: composer: redesign RoomPreviewBar

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7576]
- [x] show preview at bottom
- [x] don't show room header when preview is not available
- [x] show preview in timeline area when preview is unavailable
- [x] implement new messages
- [x] merge auth buttons into preview bar
- [x] implement panel style used with previewing
- [x] implement dialog style when preview is unavailable
- [x] show avatar & link user of inviter
- [x] see if we can fix being kicked appearing as "Joining room"
-  ~~being desinvited is shown as being kicked~~
https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5caf6e4f300c1ba0552d0c10

**Comment by bwindels** [comment]
![image](https://user-images.githubusercontent.com/274386/55894909-a7d78c80-5baa-11e9-876d-42c19f835f8c.png)

WIP, but do we want to fill this whitespace with something? E.g. placeholder icon, ...?

**Comment by Half-Shot** [comment]
I can't see the proposed design, but does it fix the problem listed in #9427 where the room preview is missing lots of info and to a lesser extent #9428

**Comment by bwindels** [comment]
After talking with @nadonomy , it looks like we might want to split up the 8 different messages we display in the RoomPreviewBar into 2 components: one where the composer is as in the design, and one where the timeline goes (e.g. for messages that can only be displayed when there is no peeked timeline). Also merging in AuthButtons.

**Comment by bwindels** [comment]
![image](https://user-images.githubusercontent.com/274386/55966663-542b7880-5c68-11e9-99d6-5edcc85068a0.png)

**Comment by bwindels** [comment]
drafting informational messages here: https://docs.google.com/document/d/1GGqGEbltoO3VXHYdQzxQoB8Nf_ip746TiiTlc-y9l4Q/edit

**Comment by nadonomy** [comment]
@bwindels I updated your parent issue comment with the Zeplin link from our call. If things unravel in the course of development feel free to ping at any time.

**Comment by jryans** [comment]
Looks like this is considered fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2925.
