### ISSUE TITLE
Redesign: dark theme

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7578]

**Comment by bwindels** [comment]
https://paulmillr.com/posts/using-dark-mode-in-css/ detect macos dark theme and switch automatically?

**Comment by bwindels** [comment]
we'll have to resolve complains about text not being readable in dark theme currently ...

**Comment by grahamperrin** [comment]
https://twitter.com/grahamperrin/status/1089255738390839297 `/experimental/` _Dark_ (one of the four page styles) in Firefox in safe mode. 

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Sat 26 Jan 2019 20:17:46 GMT
FreeBSD 13.0-CURRENT r343308 GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 65.0,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

**Comment by unendingPattern** [comment]
Hi, I got bored.
I'd like to propose something like this as the idea for a dark theme.

https://gist.github.com/unendingPattern/e5630e84611087c05811a97aef09d765

![a52theme](https://user-images.githubusercontent.com/448386/51804471-50877880-2259-11e9-943e-3726f8431e74.png)

vs

![riottheme](https://user-images.githubusercontent.com/448386/51804468-4cf3f180-2259-11e9-8305-953e6cd811c9.png)

**Comment by grahamperrin** [comment]
Thanks. 

For users (like me) who associate darkness with (for want of a better expression) _restraint_, consider less use of colour e.g. no diversity of colours for usernames. I know, it's contentious, but it makes a considerable difference when I'm trying to focus more on content (what's written) than on metadata.

**Comment by ara4n** [comment]
@unendingPattern thanks for having a go at this. once we have themes up and running on the redesign, it should be possible for this to land as a custom theme.

Heads up that we do have an 'official' dark theme for the redesign - we just haven't implemented it yet as we've been focusing on implementing the redesign itself rather than the additional themes. 

<img width="1451" alt="screenshot 2019-01-27 at 19 14 16" src="https://user-images.githubusercontent.com/1294269/51805641-f510b700-2267-11e9-8973-14d65b0ba5c9.png">

**Comment by grahamperrin** [comment]
#8280 noted with thanks. 

Whilst we're without the official dark theme, I can get something like what I need (with Waterfox) with my little CSS from a few months ago plus [No Color](https://addons.mozilla.org/addon/no-color/) and [Invert Colors](https://addons.mozilla.org/addon/invert-colors/): 

![image](https://user-images.githubusercontent.com/192271/51816711-ca524d00-22bf-11e9-9cc6-ae60995c4b4c.png)

– too stark (excessive contrast) but it'll do for now. 

When the official dark theme becomes available I can use [Monochromer](https://addons.mozilla.org/addon/monochromer/) and so on. 

In the meantime if I need help with CSS I'll take it elsewhere, probably at https://www.reddit.com/r/css/

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2619 and https://github.com/vector-im/riot-web/pull/8540.

Please check out the dark theme on /develop and file issues for any feedback!
