### ISSUE TITLE
Redesign: composer: new emoji picker

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7589]

**Comment by bwindels** [comment]
Some uncertainty about complexity:
 - update emojione? Licensing fee ...
 - use library for picker?

**Comment by bwindels** [comment]
Needs design where stickers will go? As a tab in the dialog? Might inhibit us from using a preexisting emoji picker?

**Comment by Pneumaticat** [comment]
(If you're interested in a FOSS Emoji set, perhaps https://github.com/EmojiTwo/emojitwo would interest you; it seems fairly maintained and under CC BY-SA 4.0.)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9484
