### ISSUE TITLE
Redesign: keyboard shortcuts

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7593]
- [ ] add shortcuts
- [x] add shortcuts dialog

Looks reasonable if we don't allow the shortcuts to change.

**Comment by aaronraimist** [comment]
First opened this as a separate issue (#7747) but it probably fits here:

There isn't any good way to determine what they available keyboard shortcuts are. I think we should start adding them to [tooltips](https://ux.stackexchange.com/questions/84709/how-to-expose-the-keyboard-shortcuts-of-a-web-application-to-the-user) and maybe add a dedicated interface, something like iOS's keyboard shortcuts viewer.

![image](https://user-images.githubusercontent.com/5855073/48983901-5bd3f180-f0ba-11e8-870d-9298b8357362.png)

or like StackOverflow's help sheet:
![image](https://user-images.githubusercontent.com/5855073/48983906-67271d00-f0ba-11e8-988d-37de8497ba57.png)



Related: #7165 #3232

**Comment by t3chguy** [comment]
There are other issues representing adding various other keyboard shortcuts, I will be repurposing this one just for adding a means of discoverability in the app itself.

**Comment by ptman** [comment]
This probably makes https://github.com/vector-im/riot-web/blob/develop/docs/shortcuts.md redundant?
