### ISSUE TITLE
Japanese missing in language selection

### ISSUE THREAD

**Issue by kava2108** [vector-im/riot-web#7599]
A Japanese resource file (riot-web/src/i18n/strings/ja.json) exists. But there is no Japanese as 'Choose a language'. 

Please add the following line if it's ok.
/riot-web/scripts/copy-res.js
INCLUDE_LANGS
{'value': 'ja', 'label': '日本語'},

And when installed in windows Japanese version, Riot-Desktop is displayed in English. it will be better if it's displayed in Japanese from the beginning without language selection as Riot-Android do so.

**Comment by aaronraimist** [comment]
The translations for Japanese aren't done. If you could help with that, you would be greatly improving the experience for all Japanese users

You can learn more about how to translate here: https://github.com/vector-im/riot-web/blob/master/docs/translating.md

https://translate.riot.im/projects/riot-web/matrix-react-sdk/ja/

**Comment by kava2108** [comment]
I almost finished the translations for Japanese.

Could you please add Japanese as 'Choose a language'?

**Comment by aaronraimist** [comment]
Whoa awesome! We will get those Japanese translations added to the next release.

**Comment by aaronraimist** [comment]
Looks like this has shipped in the 0.17.6 release candidate and will be available in that version when it comes out!
