### ISSUE TITLE
Redesign: Epic

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7602]
#### First things to work on
1. [Redesign: move RightPanel below RoomHeader](https://github.com/vector-im/riot-web/issues/7556) 
1. [Redesign: make interaction target of horizontal resize handles bigger](https://github.com/vector-im/riot-web/issues/7558) 
1. [Redesign: research only showing native scrollbars on hover](https://github.com/vector-im/riot-web/issues/7560) 
1. [Redesign: improve room sub list resizing](https://github.com/vector-im/riot-web/issues/7557) 
1. [Redesign: add more-content-above-below indicators in scrollable areas](https://github.com/vector-im/riot-web/issues/7561)
1. [Redesign: polish room list](https://github.com/vector-im/riot-web/issues/7567)
1. [Redesign: generic restyling of dialogs](https://github.com/vector-im/riot-web/issues/7566) 
1. [Redesign: uniform styling of buttons and inputs](https://github.com/vector-im/riot-web/issues/7559) 
1. [Redesign: memberlist](https://github.com/vector-im/riot-web/issues/7587) 
1. [Redesign: member info panel](https://github.com/vector-im/riot-web/issues/7595) 

#### Things to work on in near future

 - [Redesign: timeline: jump to bottom](https://github.com/vector-im/riot-web/issues/7592) 
 - [Redesign: timeline: jump to last unread](https://github.com/vector-im/riot-web/issues/7591) 
 - [Redesign: timeline: unread messages marker](https://github.com/vector-im/riot-web/issues/7590) 
 - [Redesign: timeline: restyle pills](https://github.com/vector-im/riot-web/issues/7572)
 - [Redesign: timeline: message states](https://github.com/vector-im/riot-web/issues/7571) 
 - [Redesign: timeline: make date separator stick to bottom of room header](https://github.com/vector-im/riot-web/issues/7575) 
 - [Redesign: timeline: implement new file transfer UX](https://github.com/vector-im/riot-web/issues/7565) 
 - [Redesign: files panel](https://github.com/vector-im/riot-web/issues/7588) 
 - [Redesign: timeline: timestamp placement](https://github.com/vector-im/riot-web/issues/7564) 
 - [Redesign: timeline: move typing notifications inside timeline, after last message](https://github.com/vector-im/riot-web/issues/7563) 
 - [Redesign: update message style](https://github.com/vector-im/riot-web/issues/7573) 
 - [Redesign: search: move search from timeline to right panel](https://github.com/vector-im/riot-web/issues/7581) 
[Redesign: mentions panel](https://github.com/vector-im/riot-web/issues/7594) 

#### Stuff that makes sense to do towards the end
 - [Redesign: keyboard shortcuts](https://github.com/vector-im/riot-web/issues/7593) 
 - [Redesign: composer: new emoji picker](https://github.com/vector-im/riot-web/issues/7589) 
 - [Redesign: integrations: placeholder](https://github.com/vector-im/riot-web/issues/7584) 
 - [Redesign: dark theme](https://github.com/vector-im/riot-web/issues/7578)

**Comment by lampholder** [comment]
#### Timeline
[Redesign: timeline: read receipt placeholder](https://github.com/vector-im/riot-web/issues/7601) 
[Redesign: timeline: jump to bottom](https://github.com/vector-im/riot-web/issues/7592) 
[Redesign: timeline: jump to last unread](https://github.com/vector-im/riot-web/issues/7591) 
[Redesign: timeline: unread messages marker](https://github.com/vector-im/riot-web/issues/7590) 
[Redesign: timeline: restyle pills](https://github.com/vector-im/riot-web/issues/7572)
[Redesign: timeline: message states](https://github.com/vector-im/riot-web/issues/7571) 
[Redesign: timeline: make date separator stick to bottom of room header](https://github.com/vector-im/riot-web/issues/7575) 
[Redesign: timeline: implement new file transfer UX](https://github.com/vector-im/riot-web/issues/7565) 
[Redesign: timeline: timestamp placement](https://github.com/vector-im/riot-web/issues/7564) 
[Redesign: timeline: move typing notifications inside timeline, after last message](https://github.com/vector-im/riot-web/issues/7563) 
[Redesign: update message style](https://github.com/vector-im/riot-web/issues/7573) 

#### Room List
[Redesign: polish room list](https://github.com/vector-im/riot-web/issues/7567)
[Redesign: add \"Private rooms\" category](https://github.com/vector-im/riot-web/issues/7574) 
[Redesign: make interaction target of horizontal resize handles bigger](https://github.com/vector-im/riot-web/issues/7558) 
[Redesign: improve room sub list resizing](https://github.com/vector-im/riot-web/issues/7557) 
[Redesign: resizeable/collapsible sections:](https://github.com/vector-im/riot-web/issues/7162) 

#### Right Hand Side
[Redesign: member info panel](https://github.com/vector-im/riot-web/issues/7595) 
[Redesign: mentions panel](https://github.com/vector-im/riot-web/issues/7594) 
[Redesign: keyboard shortcuts](https://github.com/vector-im/riot-web/issues/7593) 
[Redesign: memberlist](https://github.com/vector-im/riot-web/issues/7587) 
[Redesign: files panel](https://github.com/vector-im/riot-web/issues/7588) 
[Redesign: move RightPanel below RoomHeader](https://github.com/vector-im/riot-web/issues/7556) 

#### Search
[Redesign: search: support search in all rooms](https://github.com/vector-im/riot-web/issues/7583) 
[Redesign: search: move search from timeline to right panel](https://github.com/vector-im/riot-web/issues/7581) 

#### Communities
[Redesign: groups/communities placeholder](https://github.com/vector-im/riot-web/issues/7597) 
[Redesign: style community bar](https://github.com/vector-im/riot-web/issues/7570) 

#### Composer
[Redesign: composer: new emoji picker](https://github.com/vector-im/riot-web/issues/7589) 
[Redesign: composer: restyle composer](https://github.com/vector-im/riot-web/issues/7585) 
[Redesign: composer: restyle autocomplete popup list](https://github.com/vector-im/riot-web/issues/7577) 
[Redesign: composer: redesign RoomPreviewBar](https://github.com/vector-im/riot-web/issues/7576) 

#### General
[Redesign: room header](https://github.com/vector-im/riot-web/issues/7160)
[Redesign: login screen](https://github.com/vector-im/riot-web/issues/7586) 
[Redesign: integrations: placeholder](https://github.com/vector-im/riot-web/issues/7584) 
[Redesign: calls: placeholder](https://github.com/vector-im/riot-web/issues/7580) 
[Redesign: widgets: placeholder](https://github.com/vector-im/riot-web/issues/7579) 
[Redesign: dark theme](https://github.com/vector-im/riot-web/issues/7578) 
[Redesign: implement new default avatar colors](https://github.com/vector-im/riot-web/issues/7569) 
[Redesign: keyboard focus rectangle visuals](https://github.com/vector-im/riot-web/issues/7568) 
[Redesign: generic restyling of dialogs](https://github.com/vector-im/riot-web/issues/7566) 
[Redesign: implement top-left menu (without communities)](https://github.com/vector-im/riot-web/issues/7562) 
[Redesign: research only showing native scrollbars on hover](https://github.com/vector-im/riot-web/issues/7560) 
[Redesign: uniform styling of buttons and inputs](https://github.com/vector-im/riot-web/issues/7559)

**Comment by bwindels** [comment]
#### Prioritized list

1. [Redesign: move RightPanel below RoomHeader](https://github.com/vector-im/riot-web/issues/7556) 
1. [Redesign: polish room list](https://github.com/vector-im/riot-web/issues/7567)
1. [Redesign: make interaction target of horizontal resize handles bigger](https://github.com/vector-im/riot-web/issues/7558) 
1. [Redesign: research only showing native scrollbars on hover](https://github.com/vector-im/riot-web/issues/7560) 
1. [Redesign: improve room sub list resizing](https://github.com/vector-im/riot-web/issues/7557) 
1. [Redesign: add more-content-above-below indicators in scrollable areas](https://github.com/vector-im/riot-web/issues/7561)

**Comment by bwindels** [comment]
Use
```
Array.from(document.querySelectorAll(".issues-listing li a.h4")).map(a => `[${a.innerText}](${a.href})`).join("\n");
```

**Comment by lampholder** [comment]
Replaced with https://github.com/vector-im/riot-web/projects/13?fullscreen=true
