### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by DaniellMesquita** [vector-im/riot-web#7612]

**Comment by anoadragon453** [comment]
https://riot.im/experimental · https://riot.im/app/#/room/#riot-design:matrix.org

Afaik this issue is requesting a material-design theme for Riot.

A redesign is currently in progress, please see the above links for the current demo and discussion.

**Comment by DaniellMesquita** [comment]
This is for months and I'm not seeing too much changes.
And to make it better, should use Material Design

**Comment by LordZane** [comment]
@DaniellMesquita what about material design would make it better? And if you open the first link, and compare it to the 2nd there is a huge difference. You can also see much more about the redesign on the riot.im medium blog

**Comment by lampholder** [comment]
Thanks for stopping by @DaniellMesquita 😁 

If you have specific, actionable feedback on the redesign it would be warmly received!
