### ISSUE TITLE
Sometimes people's read receipts disappear upon refresh

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7613]

**Comment by lampholder** [comment]
To clarify - does this mean that when you refresh your browser, sometimes other people's read receipts vanish from the UI? Is it everybody's, or a subset? If a subset, is it a predictable subset or a random one?

**Comment by turt2live** [comment]
I refreshed the browser and they vanished. I guess I forgot to close this though: there was a problem with my stored syncs, causing old read receipts to be used. I just couldn't see them in the viewport.
