### ISSUE TITLE
Electron/Desktop: It is possible to get stuck logged in due to captcha

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7617]
Related to #4893 but worse

[`@eevee:matrix.org` is experiencing this.](https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1540656658258748xxEDu:matrix.org?via=matrix.org&via=chat.weho.st&via=disroot.org&via=maunium.net)

>how can i log out of an account currently in this status? i messed up while making an alt on another server and can't log out of it to get back into one i didn't mess up on
>i'm on windows 10 atm. the problem is how i messed up the account can't be completed in captcha i dont think? i tried using the email and it didnt work/was giving an error to me

![image](https://user-images.githubusercontent.com/5855073/47608638-6a18ea00-d9f6-11e8-948a-5dc3ac127f8b.png)

Seemingly no way to log out from this screen. He has had to uninstall and reinstall the desktop app.

**Comment by aaronraimist** [comment]
Yes I believe uninstalling and reinstalling was successful.

**Comment by aaronraimist** [comment]
When you say the homesever vanishes entirely what do you mean? It was a user on matrix.org and everything was up at the time.

**Comment by jryans** [comment]
I think we can improve this by leaving the "Sign in instead" link on screen even during UI auth like captchas.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2661
