### ISSUE TITLE
[Feature Request] ASCII art support

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#7618]
Not exactly sure how this could be achieved, but is there any way we could get ASCII art support in Riot?

Examples: https://user.xmission.com/~emailbox/ascii_cats.htm

When you copy and paste that to riot chat, it looks like utter gibberish.

Please? :)

**Comment by muellermartin** [comment]
This is totally doable already by enabling Markdown formatting (the small `M` icon with the downarrow next to it right above the input field). Then you can use triple backticks ` ``` ` to start a code block and end it with another triple backticks. Inbetween you can input text which will keep its formatting and will be displayed with monospaced font.

For example two of the provided ASCII art pictures then look like this:
<img width="581" alt="riot-ascii-art-demo" src="https://user-images.githubusercontent.com/343302/47663176-52776800-db94-11e8-8b56-e22c21be89c8.png">

**Comment by BloodyIron** [comment]
@muellermartin thanks! Didn't realise! :D

**Comment by muellermartin** [comment]
Glad that I could help :) If you feel like this obsoletes you feature request, feel free to close this issue.

**Comment by MTRNord** [comment]
Well any hint how I can make sure markdown doesn't screw it up? Because even using the code blocks of markdown it sometimes breaks the spacing :/ I feel like it still optimizes the input in some cases. Not sure exactly

**Comment by BloodyIron** [comment]
@MTRNord I haven't tested for all ASCII art cases. What example do you see it getting skewed?

**Comment by MTRNord** [comment]
@BloodyIron I did try ASCII UML Charts (so meaning ASCII arrows between the different blocks.) And most of the top down arrows had different spacings across all the pipes going from top to bottom (for example if a top down arrow is a bit longer and you have multiple Pipe characters above each other stacked). I would expect all pipe characters to have the same spacing in front of them. They look fine in the preview while writing but break when being sent.

**Comment by MTRNord** [comment]
But I dont very often do ASCII Stuff. So might be I just did something basic wrong

**Comment by lampholder** [comment]
@MTRNord can you share any specific snippets that rendered oddly? How are you generating the UML diagrams?

**Comment by MTRNord** [comment]
@lampholder I did it manualy in the composer.

Something like this

```
Test 1 --> Test 2
  |
  |
 \ /
Test 3
```

The top down arrow (1 to 3 in the example) has weird spacing for me sometimes inside of Riot.

**Comment by MTRNord** [comment]
@lampholder thanks for the page hint. I guess I will make a new issue as soon as I have the problem again. For now I cant give more things to test.
