### ISSUE TITLE
Can edit settings of a room I had previous left

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7619]
I had left #discord:matrix.org, and Riot was showing me the usual "click here to rejoin screen". However it was also showing me the settings cog and let me edit the room. I assume this might be because I have PL100 in the room?

Either way, we probably shouldn't show the settings menu if the user isn't joined to the room.

**Comment by lampholder** [comment]
Were you able to persist changes to the room settings? I couldn't (I got the error below), but I _did_ see the edit settings cog, which is certainly a UI bug.

![image](https://user-images.githubusercontent.com/1922197/47854769-89d75600-ddda-11e8-9acf-38696182edef.png)

**Comment by Half-Shot** [comment]
@lampholder Nope, I couldn't (which is a relief, or the problem would be much much worse)

**Comment by turt2live** [comment]
Fixed - everything should be disabled now
