### ISSUE TITLE
Searching room for "aws"

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-web#7621]
### Description

Searching any room in Riot-web (tested on /develop) results in an HTTP 500 response to the search request with the following request / response.

![selection_004_1](https://user-images.githubusercontent.com/6763606/47643054-35c23c80-db62-11e8-84e2-dd8a4e8e7f31.png)
![selection_003](https://user-images.githubusercontent.com/6763606/47642796-808f8480-db61-11e8-80e3-b890e308efc5.png)
![selection_005](https://user-images.githubusercontent.com/6763606/47642817-8c7b4680-db61-11e8-855a-7d92162773c6.png)
![selection_002](https://user-images.githubusercontent.com/6763606/47643148-7752e780-db62-11e8-936b-1ccf2634049d.png)

### Steps to reproduce

- Select a room in Riot-web
- Click the search icon in the menu bar at the top of the room
- Type ("aws") in the search input box.
- Hit the search button / or pres enter.
- Delay and then presented with "Search failed" error dialog.

Describe how what happens differs from what you expected.

I have not tested this exhaustively, but this error may just be being thrown when there is at least one result to be returned from the room history.

Search results not returned.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome
- **OS**: Linux (Mint) / 
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
There was a synapse search bug which I think got fixed?

**Comment by turt2live** [comment]
I'm closing this as a synapse issue which is probably fixed.
