### ISSUE TITLE
Riot desktop doesn't launch on Ubuntu 14.04 anymore

### ISSUE THREAD

**Issue by wincak** [vector-im/riot-web#7623]
### Description

Desktop application doesn't start any more. It used to work before but stopped recently (a week/few weeks ago), probably with one of the updates.

### Steps to reproduce

1) Update Riot to latest version in repositories
2) Try to run it
3) See nothing

Expected: Riot starts
What happens: Nothing. Only following messages are shown if attempted to run from console:

```
riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by riot-web)
/opt/Riot/riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Riot/riot-web)
Gtk-Message: Failed to load module "unity-gtk-module"
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform
```

### Version information

Riot desktop (riot-web 0.17.0) from: https://riot.im/packages/debian/ jessie main
Ubuntu 14.04, kernel 4.4.0-138-generic.

**Comment by Achtland** [comment]
I have the same issue with kubuntu 14.04 trusty tahr on two thinkpads and a desktop. It ran fine with 0.16.4, but since 0.17.0 and now on 0.17.3 riot-web doesn't start. It only shows the outline of the window. 
I tried to delete the profile, but now it doesn't start at all. It tries to load but then suddenly and silently crashes. Reinstalling changed nothing.

**Comment by i47320673** [comment]
+1
17.6 not fix the issue
14.04.5 LTS, Trusty
-KDE

4.10.9-041009-generic

> /opt/Riot/riot-web
/opt/Riot/riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Riot/riot-web)
/opt/Riot/riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Riot/riot-web)
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
Starting auto update with base URL: https://riot.im/download/desktop/update/
Auto update not supported on this platform
==========Process started, no main window============

After disable AutoUpdate in config.json

> /opt/Riot/riot-web
/opt/Riot/riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Riot/riot-web)
/opt/Riot/riot-web: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Riot/riot-web)
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
No update_base_url is defined: auto update is disabled
==========Process started, no main window============

There are 3 child processes started

>ps -fe|grep riot
user1    8137  2623  0 15:38 pts/8    00:00:01 /opt/Riot/riot-web
user1    8139  8137  0 15:38 pts/8    00:00:00 /opt/Riot/riot-web --type=zygote --no-sandbox
user1    8167  8139  0 15:38 pts/8    00:00:00 /opt/Riot/riot-web --type=renderer --no-sandbox --service-pipe-token=6D072770ECBC396F19345E1E4AD14093 --lang=ru --app-path=/opt/Riot/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --
user1    8174  8137  0 15:38 pts/8    00:00:00 /opt/Riot/riot-web --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=306D7D647B06770942B22D69E6DFF87
=========

**Comment by aldenstpage** [comment]
I have the same issue with a fresh install on 0.17.8.

**Comment by i47320673** [comment]
Hi, 0.17.9 released.
Is issue resolved?

**Comment by i47320673** [comment]
Clear install 17.9 seems OK for me. Thanks.

**Comment by wincak** [comment]
Works for me now after upgrade to version 1.0.4, no additional fiddling needed. Thank you!
@aldenstpage @Achtland can you please try if you still have this issue?

**Comment by jryans** [comment]
Seems like this might be resolved. If it's still a problem, please let us know. A new issue might be appropriate given the time span involved here.
