### ISSUE TITLE
Reset room list on enter in room filter field

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-web#7625]
### Description

Hitting enter in the filter field for rooms opens the first found room, but doesn't reset the room list. When pressing *down* in the filter field to select the first room and press enter, thereafter, the room list gets reset. It would be handy, if this happens from a room filter, too.

### Steps to reproduce

1. click into the field on the left above all rooms which contains *Filter room names*
1. enter a texts that narrows the rooms to a few ones
1. hit enter
1. the room of the first match opens, but the room list stays narrowed down

### Version information

- **Platform**: Firefox nightly 65.0a1
- **OS**: Debian Linux
- **URL**: private server with riot-web: 0.17.1

**Comment by lampholder** [comment]
Hmm, I'm not sure what the right behaviour for this is - I quite _like_ that the list stays filtered (until I forget that it's filtered and wonder why I can't find a particular room).

I think the UX of this requires some thought, certainly, but I'm not sure that the change described is necessarily ideal in all cases.

**Comment by dannycolin** [comment]
> Hmm, I'm not sure what the right behaviour for this is - I quite _like_ that the list stays filtered (until I forget that it's filtered and wonder why I can't find a particular room).

I think the behavior where pressing enter reset the filter makes sense. It would work mostly like the urlbar of a browser when you search for something in it and the dropdown is closed after you hit enter.

And alternative could be to use `ctrl + k` as a toggle. It would go like this:

1. Press `ctrl + k`
2. Enter the filter input
3. Type something and it filters the room list
4. Press Enter to go to the selected room OR press `ctrl +k` to quit the filter mode and get back to the unflitered room list.
