### ISSUE TITLE
Inconsistent flair ordering

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7632]
![image](https://t2l.io/_matrix/media/v1/download/t2l.io/7a11ae39d89af564854b27f2fca963c7)

**Comment by lampholder** [comment]
Yuk. Seems like an easy fix?

**Comment by n-o-o-b** [comment]
Is it possible to choose the order of one's flairs?

**Comment by n-o-o-b** [comment]
Should it not be possible for the user to rearrange the flairs? It's possible to rearrange the communities in the sidebair, and in my opinion the flairs should either follow that order, or, even better, be rearrangeable separately, from the settings.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2389.
