### ISSUE TITLE
Emoji picker in windows 10 just doesn't work with Riot

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7639]
![image](https://user-images.githubusercontent.com/1190097/47814362-1c142700-dd13-11e8-8083-6e4f38288697.png)

* Selection is always at the start
* Placeholder still present
* Cannot navigate between the emoji or to the end of the message

**Comment by aaronraimist** [comment]
Is this an upstream bug in Slate? I assume related to https://github.com/ianstormtaylor/slate/issues/2368

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.
