### ISSUE TITLE
Canonical alias shows that it will be changed when the user doesn't have permission

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7643]
> there's also an UI bug where riot changes the canonical alias to show the alias you're adding when there's no canonical alias even though you can't actually change the canonical alias

**Comment by lampholder** [comment]
I've given this a higher priority because I think 'canonical aliases' are confusing enough a concept as it is, without muddying the waters with glitchy UX :)

**Comment by t3chguy** [comment]
This appears fixed

![7643](https://user-images.githubusercontent.com/2403652/59982627-4e112b00-960d-11e9-9b90-00538ca3110f.gif)
