### ISSUE TITLE
don't warn about a room being empty when starting a chat

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7644]
as if you've just started a chat with someone and they haven't joined, of course it's empty, and the message is just confusing

**Comment by ara4n** [comment]
<img width="980" alt="screenshot 2018-11-01 at 14 49 40" src="https://user-images.githubusercontent.com/1294269/47859159-97460d80-dde5-11e8-9580-92eaad689eda.png">

**Comment by turt2live** [comment]
it should probably just consider invites as "joined" for the purposes of the notice.

**Comment by lampholder** [comment]
> it should probably just consider invites as "joined" for the purposes of the notice.

Makes sense to me.

**Comment by t3chguy** [comment]
Cannot repro 
![image](https://user-images.githubusercontent.com/2403652/53453324-a8adc800-3a1b-11e9-83a2-3e6952bedc7c.png)

It already counts invited :/ https://github.com/matrix-org/matrix-react-sdk/blob/7d2c6fbd0b5494a6c7f053f4b32fd41f62c754a1/src/components/structures/RoomView.js#L809

**Comment by ara4n** [comment]
i reproed this as recently as yesterday, i think. it might be that you have to create the room via Start Chat + a bunch of invitees?

**Comment by t3chguy** [comment]
If bunch >= 2 then still no for me :(
![image](https://user-images.githubusercontent.com/2403652/53454185-47d3bf00-3a1e-11e9-9eb3-2b66a64912d5.png)

**Comment by t3chguy** [comment]
even if I message to trigger it to recheck
![image](https://user-images.githubusercontent.com/2403652/53454218-5ae68f00-3a1e-11e9-931b-af9941d13e79.png)

**Comment by turt2live** [comment]
I can easily reproduce this fwiw by inviting a single user to an otherwise empty room

**Comment by t3chguy** [comment]
> I can easily reproduce this fwiw by inviting a single user to an otherwise empty room

Works! Thanks

Shall debug

**Comment by t3chguy** [comment]
Hah, if you send a message into that room it disappears, so its just that invitation which trips it

**Comment by t3chguy** [comment]
this is a nasty race condition :(
