### ISSUE TITLE
Flair checkbox is confusing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7647]
It is hard to remember what state it is trying to communicate

**Comment by jryans** [comment]
@lampholder How about if we change this to only show the positive text ("Flair will appear if enabled in room settings") no matter the state of the checkbox? I think that's more inline with how settings and checkboxes usually behave.

**Comment by lampholder** [comment]
Yeah, I think only-positive text could work. How about:

- [ ] Show flair (where enabled in room settings)

**Comment by turt2live** [comment]
not anymore!
