### ISSUE TITLE
Entering URL without https will make application unresponsive

### ISSUE THREAD

**Issue by fwsGonzo** [vector-im/riot-web#7651]
And, occasionally it will freeze and have to be closed. Matrix-server URLs are usually HTTPS, so if there is any way to make the default protocol https that would help alot of beginners out. I only realized this due to chance, as its not something you ordinarily think about. This was on Ubuntu desktop.

**Comment by turt2live** [comment]
More information about this would be appreciated: was this on web or desktop? which browser? operating system? and where was the URL entered?

**Comment by fwsGonzo** [comment]
Updated to reflect this was Ubuntu desktop, and it was my little brother having this problem, so it was a remote debugging session.

**Comment by turt2live** [comment]
Where was the URL entered?

**Comment by fwsGonzo** [comment]
The problems start immediately after typing in an URL that responds with a 403 in the box that says "Home server URL".

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="...">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at ... Port 80</address>
</body></html>
```

**Comment by lampholder** [comment]
Right, so if you don't specify a protocol (http/https) riot just assembles the URL it's poking as a relative path (so if you're using https://riot.im/app and you put in the domain `example.com` then it will poll `https://riot.im/app/example.com/_matrix/client/r0/login` - in the case of https://riot.im it'll get a 404, but that'll obviously depend on the particular configuration of the server serving the riot web client.

> The problems start immediately after typing in an URL that responds with a 403 in the box that says "Home server URL".

Did you mean 301?

If you type a full URL that response with a 301 (or a 403) you get the 'Cannot connect to homeserver...' message.

So I guess we've got two issues:
1. Riot doesn't follow 301 redirects (but I don't know that we want it to)
1. Riot doesn't handle matrix server URLs without a protocol specified well

**Comment by lampholder** [comment]
I made two separate issues (I'll close this one):
- https://github.com/vector-im/riot-web/issues/7706 - missing protocol handled badly
- https://github.com/vector-im/riot-web/issues/7707 - not following redirects
