### ISSUE TITLE
We should just document the old symlink approach to setting up a riot dev environment for people with broken npm

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7654]
There is an argument to be made about fixing the environment. However with 4 known cases of people unable to `npm link`, we should just have a section for 'if you have a broken environment, try this:'

**Comment by lampholder** [comment]
Until we can come up with something better, removing barriers to progress as pragmatically as possible is a good idea.

**Comment by turt2live** [comment]
It's documented here: https://github.com/vector-im/riot-web/blob/5ef141913b976372d0a43f42e5415b017088391b/README.md#setting-up-a-dev-environment

It's mostly useful if your npm gives you something along the lines of "I don't feel like working today, so here's a permission error that means nothing and only when you try to `npm link`".

**Comment by t3chguy** [comment]
I don't think applies anymore given yarn isn't made of fail

**Comment by ara4n** [comment]
indeed.
