### ISSUE TITLE
We should actually turn on lazy loading for everyone

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7655]
Private instances will likely not be aware of the feature flag, turning off lazy loading

**Comment by lampholder** [comment]
I think this is safe for people who might be updating their clients but not their homeservers (i.e. I think if the homeserver doesn't support lazy loading, Riot still works fine) - is that right?

If so, I can't see why not.

**Comment by turt2live** [comment]
It's worth testing, but I believe riot won't try to lazy load unless the homeserver can be proven to have the feature.

**Comment by turt2live** [comment]
we did this
