### ISSUE TITLE
Riot is queuing messages, but not sending them

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7669]
### Description

Sending messages into a room causes the messages to be queued (as seen in logs) and enter the grey state but it doesn't ever send the HTTP request. Sync is working as expected and messages are appearing in the room.

If I wasn't clear enough, the request is never sent so there isn't an error reported to the client. It just stays pending forever.

- The app is in the foreground
- The system is not constrained on resources.
- Synapse is not receiving the requests
- Unsure what causes the requests to batch up, I'm hoping the logs are of use.
- This happens in all the rooms I'm in.

### Steps to reproduce

- Open a room
- Try to send a message
- See it enter the timeline and be greyed out, but never go black (sent).

Describe how what happens differs from what you expected.

Log: sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 0.17.0

**Comment by lampholder** [comment]
Flagged this as maximum scary until I know a bit more about it 📦 

@Half-Shot - were you disconnnected when you sent the messages? Is this happening reproducably?

**Comment by Half-Shot** [comment]
[This accurately describes what I think is happening](https://github.com/vector-im/riot-web/issues/2523#issuecomment-288772666) but I cannot for the life of me accurately produce this. It happens occasionally. *Seldomly* it totally drops out forever like the bug report above, but sometimes it just locks up Riot's sending queue for 1-2 minutes as it retries and eventually gets there.

On a related note, do we know why Riot locks up all the rooms if my messages fail to send for one of them?

**Comment by Half-Shot** [comment]
Not seen this in a while, let's close.
