### ISSUE TITLE
Can't delete quote blocks with delete key in rich text mode

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#7676]
But oddly, hitting return works:

![cantdelete](https://user-images.githubusercontent.com/4626865/48260213-84998d00-e412-11e8-82e4-be348d373ee5.gif)

**Comment by nadonomy** [comment]
Just updated with a gif illustrating keyboard keystrokes. Will update the title to clarify too.

**Comment by t3chguy** [comment]
I have a feeling this might be a regression as I'm 99% this used to work

**Comment by lampholder** [comment]
> I have a feeling this might be a regression as I'm 99% this used to work

Confirmed this is a regression - this worked pre-slate.

**Comment by t3chguy** [comment]
I meant a since-slate regression, as I think (not 100% sure) this worked in my original implementation

**Comment by t3chguy** [comment]
We no longer have this rich text mode in the new composer
