### ISSUE TITLE
Who can join this room? Everyone how is part of the community the room is in!

### ISSUE THREAD

**Issue by fladd** [vector-im/riot-web#7678]
### Description

There is no option to make a room accessible to community members.

### Steps to reproduce

n.a.

Describe how what happens differs from what you expected.

I expect the section "Who can join this room" to have an option "Everyone who is part of the community/communities this room is in".

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5857
