### ISSUE TITLE
How to use domain.com instead domain.com/riot

### ISSUE THREAD

**Issue by devcline** [vector-im/riot-web#7690]
with nginx config
thanks

**Comment by devcline** [comment]
```
location /riot { 
	alias /var/www/im.cxema.in; 
	}
```

i dont know why but not its ok; i dont know what i do to manage this , but before it was poiting to /riot

**Comment by turt2live** [comment]
You'd have to update your nginx config to use the correct domain name and relevant location directives. For support, please visit [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org) on Matrix as someone should be able to help you out there.
