### ISSUE TITLE
integrations_ui_url requires a '/' at the end

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#7694]
### Description

If you don't have a `/` at the end of your `integrations_ui_url`, then Scalar breaks with error "You don't have permission to add widgets to this room", which is utterly confusing and can lead people on wild goose chases.

This isn't exactly user friendly. Ideally we would just append a `/` to the end of the option if it doesn't already have one.

### Steps to reproduce

- Set `integrations_ui_url` to `https://scalar.vector.im` in your Riot config
- Watch Scalar not work

**Comment by makyo** [comment]
This doesn't appear to be the case any more, perhaps by dint of the `url` lib. My config has the following:

```
    "integrations_ui_url": "https://scalar.vector.im",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
```

and I was able to add a widget to a room.

**Comment by turt2live** [comment]
success!
