### ISSUE TITLE
Desktop-App: Zoom factor is not remembered and menu hint is wrong

### ISSUE THREAD

**Issue by rubo77** [vector-im/riot-web#7696]
On Ubuntu 18.04 with the desctop app riot-web 0.17.0 the zoom factor is only remembered until riot is completely exited.

On each first start the Zoom is reset to 100%

If you don't find the zoom, press ALT once and you get the menu on top which has **View->Zoom in and out** 

You can also zoom via shortcuts:

- CTRL SHIFT +  : zoom in
- CTRL - : zoom out

This is a bug, because the menu sais CTRL +, (maybe this bug only exists in **german QWERTZ** keyboardlayout)

A sentence in the settings 

    Use CTRL + and - key to zoom

would be great also!

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/7721

**Comment by aaronraimist** [comment]
I can't reproduce the zoom setting not being remembered but #8381 fixes the menu item being wrong (it fixes it badly but that's because electron sucks).

**Comment by aaronraimist** [comment]
@rubo77 can you test this again? Should be fixed in 1.0

**Comment by rubo77** [comment]
tested and works fine as expected on Ubuntu: CTRL+ zooms up and the setting stays over restarts of the program
