### ISSUE TITLE
GDPR Consent on registration UX snagging list

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7700]
Three things we need to fix before this goes live:
- [x] The Consent page should not display the yellow-bordered checkboxes - it needs to be abundantly clear that this page is informational (when part of the consent-on-registration flow) not interactive-but-broken
- [x] The words next to the checkbox should read 'I agree to the [Terms and Conditions](https://example.com)', not just '[Terms and Conditions](https://example.com)'
- [x] You should have to click some sort of 'affirmative/next' button after checking the checkbox - just checking the checkbox shouldn't advance the flow
- [x] Make ILAG still work (the new flow shouldn't block ILAG if the homeserver supports registration without providing an email address)

**Comment by lampholder** [comment]
Also, when I try to ILAG with consent-on-registration enabled, Riot panics and hits me with the "ILAG can't handle this, switching to regular registration flow" popup:

![screenshot 2018-11-14 at 12 14 18](https://user-images.githubusercontent.com/1922197/48481883-f0129e80-e806-11e8-92a1-9191e4694b85.png)

This was on a homeserver that empircally did allow emailless registrations (the above was implemented to skip ILAG (which doesn't gather an email address until later in the flow) for homeservers which don't allow registration without an email address.

**Comment by turt2live** [comment]
> The words next to the checkbox should read 'I agree to the Terms and Conditions', not just 'Terms and Conditions'

@lampholder this is a lot harder to maintain in a safe way for other languages. The policy name (and URL) come from the server, which would mean the Riot side would fall into the concatenation problem ("I agree to the %(terms and conditions)" is not going to work in all languages). The text immediately preceding the checkboxes should be fine (or it could be improved):
![image](https://user-images.githubusercontent.com/1190097/48522882-7941c980-e837-11e8-9281-5e254cbf0d96.png)

Alternatively, we can just make the whole line a hyperlink and lie on the server side by making the policy name "I agree to the terms and conditions", which would hyperlink the whole thing.

**Comment by turt2live** [comment]
> The Consent page should not display the yellow-bordered checkboxes - it needs to be abundantly clear that this page is informational (when part of the consent-on-registration flow) not interactive-but-broken

@lampholder can I get a mockup or text for "abundantly clear"?

**Comment by lampholder** [comment]
> @lampholder can I get a mockup or text for "abundantly clear"?

Ironically my request was ambiguous 😁 I actually just meant we need to lose the yellow boxes and the checkboxes (and the text next to the checkboxes). By just showing the user checked (and non-interactive) boxes I think it's confusing - like we're pretending to give them a choice, or that the form is broken. So I think it would be fine if the page just looked like this:

![image](https://user-images.githubusercontent.com/1922197/48543265-0ed16d80-e8b9-11e8-98cb-820781311cfd.png)

**Comment by lampholder** [comment]
> @lampholder this is a lot harder to maintain in a safe way for other languages. 

All right, understood. We should bear this in mind as we work on the redesign so that we have a pain-free way to handle i18n/subject-verb-object permutations generally.

I think this will actually be fine if in separating the clicking of the checkbox from the progression through registration by making the form look something like:

![image](https://user-images.githubusercontent.com/1922197/48545873-d03eb180-e8be-11e8-8b47-233e4d3ffb5b.png)

What do you think?

**Comment by turt2live** [comment]
Sounds good to both suggestions - I'll bump the whole issue back up to high priority again :)

**Comment by turt2live** [comment]
Closing as the Riot side is now merged. the matrix.org changes to the policy are being tracked elsewhere.
