### ISSUE TITLE
People are losing avatars after they clear cache and reload 

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7705]
Empirically they're also losing members from the member list, which is probably related. Clear cache and reload is being pressed because the room doesn't have a name for them :(

**Comment by bwindels** [comment]
Will get a fix out for this today. This is riot not handling a synapse LL bug well.

**Comment by bwindels** [comment]
The details: riot sets the room name to null if the room name is an empty string and there are no heroes in the summary. Synapse doesn't seem to send the heroes when you've previously set a room name and then cleared it, which makes the state event have an empty state key.

**Comment by turt2live** [comment]
The concern is that the room name should not be an empty string in the first place. Both instances I've witnessed this happen to someone else, they are in rooms that definitely have names.

**Comment by bwindels** [comment]
Synapse issue: https://github.com/matrix-org/synapse/issues/4194

**Comment by turt2live** [comment]
I think this was fixed
