### ISSUE TITLE
 Verify / blacklist device screen buttons aren't aligned

### ISSUE THREAD

**Issue by axelsimon** [vector-im/riot-web#7712]
### Description
Just saw this, look at how the device names align with the right-hand side buttons:

![riot_verify_blacklist_buttons_out_of_line_screenshot from 2018-11-16 09-24-43](https://user-images.githubusercontent.com/1172256/48615411-c2edf980-e988-11e8-8774-0787ef12906f.png)

The verify and blacklist buttons become staggered after a few lines, making it hard to be sure which device's verify or blacklist button you are clicking on.
When you reach device 8, the buttons on the right are actually device 7.

Hope this helps,
axel

### Version information
- **Platform**: desktop
- **OS**: Fedora 29
- **Version**: 0.17.5

### Possibly related issue:
#4387

**Comment by lampholder** [comment]
Oh god, that's horrendous :(

All of this UX is in the process of being overhauled, though if we can fix this sooner I think we should.

**Comment by aaronraimist** [comment]
I don't think this screen exists anymore
