### ISSUE TITLE
"Unknown error" when attempting to deactivate account

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7717]
### Description

When attempting to deactivate their accounts, some users receive an "Unknown error". Nothing appears in browser console.

User is on matrix.org HS.

https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$15425700261066390hBeex:matrix.org?via=matrix.org&via=disroot.org&via=chat.weho.st&via=bosmsg.de

### Steps to reproduce

- Press Deactivate your account button
- Input password
- Press Deactivate account button

Log: not sent

![image](https://user-images.githubusercontent.com/5855073/48678096-4d2e8d00-eb44-11e8-8305-83834123a7d1.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox Nightly
- **URL**: riot.im/app

**Comment by aaronraimist** [comment]
@richvdh is this good to close? Do you want to add something to UPGRADE.rst to tell other sever operators to remove that from their configurations?

**Comment by lampholder** [comment]
It does look good to close - the user who filed the github issue has now been able to successfully close their account.

Adding a note to UPGRADE.rst sounds like a good idea, too.

**Comment by jryans** [comment]
I believe this is considered done from the Riot side. (Synapse listed this in their upgrade notes.)

**Comment by rgpublic** [comment]
I still cannot deactivate my account on matrix.org and get the "unknown error". What should I do? File a new issue?

**Comment by jryans** [comment]
> I still cannot deactivate my account on matrix.org and get the "unknown error". What should I do? File a new issue?

Hmm, yes, please file a new issue. I suppose it must be something different since matrix.org HS should already have applied the suggested change described in this issue.

**Comment by Foxofgrey** [comment]
I'm getting the same error here. I used Firefox, Brave, and the iOS app all returning unknown error. But I got this message on iOS:
"Failed to remove threepid from ID server"

**Comment by artemist** [comment]
I tried to do this today, and it was failing for me too. The issue seems to be that the client is POSTing the data `{"auth":{"type":"m.login.password","user":"@artemist:matrix.org"},"erase":true}`, which results in a 400 response with the error `{"errcode":"M_UNKNOWN","error":"Missing parameter: password"}`. Copying the request as cURL then adding the password field into the "auth" dictionary in the data worked for me. I still got the response `{"id_server_unbind_result": "no-support"}`, but idk if that is important.

**Comment by jryans** [comment]
> I tried to do this today, and it was failing for me too. The issue seems to be that the client is POSTing the data `{"auth":{"type":"m.login.password","user":"@artemist:matrix.org"},"erase":true}`, which results in a 400 response with the error `{"errcode":"M_UNKNOWN","error":"Missing parameter: password"}`. Copying the request as cURL then adding the password field into the "auth" dictionary in the data worked for me. I still got the response `{"id_server_unbind_result": "no-support"}`, but idk if that is important.

This was caused by regression that is now [fixed](https://github.com/matrix-org/matrix-react-sdk/pull/3201) as part of Riot 1.2.4. In general, it's best to open a new issue when you experience a problem rather than commenting on a closed one so we can ensure it's triage quickly.
