### ISSUE TITLE
Direct chat does not show user avatar

### ISSUE THREAD

**Issue by lugino-emeritus** [vector-im/riot-web#7719]
### Description

Moving a room with two members to a direct chat "removes" the room avatar (= avatar of other member).

### Steps to reproduce

- (Create) a room with you (A) and one additional member (B) (B needs an user avatar)
    -> Now riot should show the avatar of B in the room -> correct
- Disable 'direct chat' option if enabled
- Enable 'direct chat' option
    -> Now there is no room avatar anymore :(
- Disabling the 'direct chat' option shows the avatar again.

### Version information

- Tested with firefox 63.0, Linux Mint and Windows 10
- Tested with riot 0.17.3, 0.17.5 and /experiental

**Comment by lampholder** [comment]
I can reproduce this reliably:
![screen recording 2018-11-23 at 13 31 35 2018-11-23 13_33_27](https://user-images.githubusercontent.com/1922197/48946050-63619200-ef24-11e8-81ed-36bf915fff9c.gif)

Refreshing the client doesn't seem to fix the problem.

**Comment by lampholder** [comment]
Interestingly:
- the problem isn't fixed by clear cache and refresh or by logging out/in again
- existing DMs which had the right avatar lost it when I untagged them as DMs (and never regained it)

**Comment by Bubu** [comment]
This problem is annoying when migrating accounts (invite new account, leave with old) as that basically gets every direct chat I have into this state where I either don't tag them as a direct chat or they'll have no room avatar

**Comment by lugino-emeritus** [comment]
Problem solved in version 1.0.*
