### ISSUE TITLE
Pin unread rooms only considers badges

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7723]
Rooms that are 'mentions only' do not cause unread badges, which means the room is not ordered correctly.

**Comment by aaronraimist** [comment]
Relevant conversation: https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$154177512316qJtnn:raim.ist?via=matrix.org&via=t2bot.io&via=riot.tenx.tech&via=meshspace.de

![screen shot 2018-11-20 at 11 10 10 am](https://user-images.githubusercontent.com/5855073/48790407-debd0c80-ecb4-11e8-9fcb-e1caadcec949.png)

Should it be a third option or should the behavior of the "pin unread rooms" option be changed?

**Comment by turt2live** [comment]
The conversation was actually https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$15427278634667ofZxl:maunium.net?via=matrix.org&via=disroot.org&via=chat.weho.st&via=bosmsg.de

It probably shouldn't have a third option, but the "pin unread rooms" should order unread-with-badges above unread.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2330
