### ISSUE TITLE
unpin react-sdk & js-sdk deps after release

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7728]
or only pin them on the release branch. eitherway, dev should dep on dev, not releases,  so `npm run start` works correctly without faffing with `npm run link`

**Comment by jryans** [comment]
We now do this as part of the release process (though it's a manual step at the moment).

**Comment by turt2live** [comment]
in practice we forget that step almost every time in recent versions.

**Comment by jryans** [comment]
Sounds like we should add it to the release script then.
