### ISSUE TITLE
E2E message keys disappeared from Riot Web and can't be requested

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#7734]
### Description

I am in an encrypted room that I have used successfully in the past with Riot Web and iOS. However, something has changed, and now the messages are only viewable on Riot iOS. On Riot Web, it acts as if the message keys are missing. When I click to request them, nothing seems to happen. (In the console, I can observe that it appears to get keys, but the messages remain hidden)

Curiously, if I try riot.im/develop, some of the older messages do appear. With riot.im/app, none of the older messages will appear.

### Steps to reproduce

- Create an encrypted room with several devices
- Something happens causing a device to lose keys
- Try to re-request message keys

I would expect the message keys to be requested successfully and the messages to re-appear. Currently, they seem to be broken with no path to recovery.

### Version information

- **Platform**: web
- **Browser**: Firefox 65
- **OS**: macOS 10.13.6
- **URL**: riot.im/app shows no older messages, riot.im/develop shows some but not all

**Comment by jryans** [comment]
I have sent debug logs from my end.

I do see messages like "room key request for unknown session ..." in the console, which perhaps is related to the problem.

**Comment by jryans** [comment]
I was able to manually export room keys from iOS and import them into Web successfully. The messages are now viewable in Web again, so that's great, but I wonder what even was wrong to start with.

Perhaps I corrupted some state by switching between /app and /develop in the same browser?

**Comment by lampholder** [comment]
Dave's taking a look into this now :)

If I understand it correctly, there should be measures in place to stop E2E state being corrupted by switching between Riot versions (by warning you if there's an incompatibility), though of course it's possible that there's a problem in _that_ code.

Anyway, I'm glad importing the keys has overcome the immediate hurdle - we'll try and find out what caused this in the first place.

**Comment by jryans** [comment]
I guess there's actually still an issue remaining: Riot Web can't seem to get *new* message keys automatically any more. So, the manual import works, but then new messages are still broken. So, I would need to keep repeating the process of manually exporting and importing keys to see new messages.

**Comment by jryans** [comment]
@dbkr guessed it was a version corruption issue between /app and /develop. And indeed, if I stay on /develop, everything works as intended even for new messages.

I filed #7735 to handle the root cause of version confusing across multiple app branches on the same domain, so I think this can be closed.
