### ISSUE TITLE
custom power levels should have the badge of their next lowest level

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7742]
eg pl 51 should be shown as 50 rather than blank

**Comment by t3chguy** [comment]
Comments say this is deliberate https://github.com/matrix-org/matrix-react-sdk/blob/77cee8e67ea4b3937746d6f863680d4821c45fef/src/components/views/rooms/MemberTile.js#L142

**Comment by turt2live** [comment]
There's no rationale recorded for that, and tbh I'm tempted to call that comment a bug personally

**Comment by ara4n** [comment]
i /think/ i may have written that, and i agree that it's a thinko. the rationale was "we should not confuse people by saying that 53 is a moderator, when in practice they're something a bit more than a moderator".  I think we should show their mod badge anyway, as the semantics of that badge is "user has at least that PL".  But in MemberInfo we should give the precise value rather than lying and saying "they're Op (i.e. 50)".

**Comment by t3chguy** [comment]
I'm fixing it regardless :P

![image](https://user-images.githubusercontent.com/2403652/53454864-879ba600-3a20-11e9-9393-d16d47065bdb.png)

**Comment by turt2live** [comment]
> i /think/ i may have written that

!blame Luke, according to git.

**Comment by ara4n** [comment]
ah. right. it might have been based on spurious advice from me eitherway. eitherway, let's fix it!

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2709
