### ISSUE TITLE
Some matrix.org users can't join #matrix:matrix.org - CORS request rejected

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7745]
`@tya99:matrix.org` and `@cj232:matrix.org` can't join #matrix:matrix.org

tya99:
> i'm having trouble joining the #marix:matrix.org channel the thing just spins around and never lets me get in

## Browser console: 
https://dpaste.de/hsrr

Highlights:
```
rageshake.js:99 [!QtykxKocfZaZOUrTwp:matrix.org] Peek poll failed: Error: CORS request rejected: https://matrix.org/_matrix/client/r0/events?room_id=%21QtykxKocfZaZOUrTwp%3Amatrix.org&timeout=30000&from=s753744768_623528594_1124893_201363733_93238299_519270_13565385_10267141_24511
    at c (file:///usr/lib/riot/webapp/bundles/7d178a862b1d188cf096/bundle.js:23:48825)
    at XMLHttpRequest.o.onreadystatechange (file:///usr/lib/riot/webapp/bundles/7d178a862b1d188cf096/bundle.js:23:48351)
```

```
rageshake.js:99 Error: CORS request rejected: https://matrix.org/_matrix/client/r0/sync?filter=3&timeout=30000&since=s753744760_623528584_1124890_201363731_93238297_519270_13565485_10267234_24511
    at c (index.js:259)
    at XMLHttpRequest.o.onreadystatechange (index.js:242)
```

```
rageshake.js:99 Number of consecutive failed sync requests: 1
rageshake.js:99 Starting keep-alive
rageshake.js:99 MatrixClient sync state => RECONNECTING
rageshake.js:99 MatrixClient sync state => SYNCING
```

https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1542975037111476BQxvp:matrix.org?via=matrix.org&via=disroot.org&via=chat.weho.st&via=bosmsg.de
https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1543003303205464UtACh:matrix.org?via=matrix.org&via=disroot.org&via=chat.weho.st&via=bosmsg.de

**Comment by tya99** [comment]
Thanks for opening the issue. I wasn't sure what I was looking for :)

**Comment by lampholder** [comment]
I just had a chat about this with @erikjohnston - it sounds like the CORS could be a red herring masking a plain old timeout (if the request times out between our haproxy and the synapse instance, the error response from haproxy to riot doesn't have CORS headers so registers with a CORS error).

Are the affected users _ever_ able to get into #matrix:matrix.org? Are they trying at a particularly busy time?

**Comment by tya99** [comment]
> Are the affected users ever able to get into #matrix:matrix.org? Are they trying at a particularly busy time?

I had tried at different times of the day, and on different days. I haven't had the error happen since. I'm not a heavy Matrix user though.

**Comment by aaronraimist** [comment]
I’m going to close this for now. If someone gets this again they can create a new issue or ping me to reopen this one.

**Comment by asim-vax** [comment]
@aaronraimist trying to reset a password caused a timeout, now i can't create a new account, or reset password on an old account
CORS request rejected: https://matrix.org/_matrix/client/r0/register/email/requestToken (for requesting a new account)

**Comment by aaronraimist** [comment]
@asim-vax actually maybe opening a new issue would be better
