### ISSUE TITLE
Cannot login anymore (stuck at spinner)

### ISSUE THREAD

**Issue by gabm** [vector-im/riot-web#7761]
### Description

It started some days ago. Riot.im stoppped working for me in my Qutebrowser. I logged out and wanted to log in again. On my login attempt i entered my credentials and then it got stuck at the spinner. 

So I decided to try Chromium for riot.im. That worked and I could continue using riot. Yesterday this stoppped working the same way. First the synchronisation didnt work anymore (couldnt send/receive any messages), then I logged out and now I'm stuck a the spinner after login.

I tried deleting cookies and cache but that doesnt seem to have any effect on both browsers... I can still use it on Android and probably any new browser...

### Steps to reproduce

Obviously I can't provide any logs, the app doesnt launch anymore...

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromeium 70, Qutebrowser 1.5.2
- **OS**: Arch Linux
- **URL**: iot.im/app

**Comment by lampholder** [comment]
Hi @gabm - sorry you're having these difficulties.

Can you confirm that your account is on the matrix.org homeserver?

**Comment by gabm** [comment]
yes I'm at matrix.org... @gabm:matrix.org

**Comment by gabm** [comment]
interestigly it started working again... idk what happened?!
