### ISSUE TITLE
Events that take a while to send lock up the queue for every room

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7762]
### Description

When talking in HQ or another room, for one reason or another the send operation takes a long amount of time to succeed. If I talk in another room, the messages will remain in a waiting grey state until the message in HQ is sent. The problem is the HQ messages can take upwards of 5 minutes to get sent (again, will look into that).

### Steps to reproduce

- Talk in a large or troublesome room, e.g. #matrix:matrix.org
- Watch the event get delayed
- Try to talk in another room, see delays

I don't remember this being the case before, though it might never have been quite this bad before. Either way it makes the client unusable.

Log: sent?
### Version information

- **Platform**: web
- **OS**: Ubuntu 18.10
- **Version**: 0.17.3

**Comment by lampholder** [comment]
Is anyone else seeing this? I haven't experienced it (but I'm not connecting directly to matrix.org).

**Comment by Half-Shot** [comment]
Not seen this in a while.
