### ISSUE TITLE
New users register to matrix.org until "custom server" radio is selected on https://myhomeserver/#/register

### ISSUE THREAD

**Issue by killua-eu** [vector-im/riot-web#7764]
### Description & Steps to reproduce

- Spin up a new homeserver
- Go to https://myhomeserver/#/register
- Register as a new user 
- As long as you don't change the radiobutton from  "default server" to "custom server", your registration will go to matrix.org instead of myhomeserver. :bug: 

Affects all versions down to the current. Here is the riot's config:

```
root@matrix:/opt/riot-web# cat config.json 
{
    "default_hs_url": "https://myhomeserver:443",
    "default_is_url": "https://vector.im",
    "disable_custom_urls": false,
    "disable_guests": false,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "Riot",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
    "features": {
        "feature_groups": "labs",
        "feature_pinning": "labs"
    },
    "default_federate": false,
    "welcomePageUrl": "home.html",
    "default_theme": "light",
    "roomDirectory": {
        "servers": [
            "myhomeserver"
        ]
    },
    "welcomeUserId": "@riot-bot:matrix.org",
        "enable_presence_by_hs_url": {
        "https://myhomeserver": false
    }
}

**Comment by lampholder** [comment]
Yeah, I haven't been able to reproduce this. Can you advise which version of riot you're using?

**Comment by lampholder** [comment]
One thing to check is to make sure that you're not using a cached config.json (the browser tends to cache this file pretty aggressively).

Also, riot will check _two_ config files when it starts up, first `config.domain.tld.json` (e.g. config.riot.im.json), then `config.json`. If it finds the former it won't bother checking the latter.

**Comment by killua-eu** [comment]
Sorry for the late reply, it must have been the cache, I cant reproduce myself after setting up a new browser profile. @aaronraimist thanks for pointing out the problem with the matrix bot. Is there a way to selfhost the bot? I tried (and failed) to find any info on it.

**Comment by jryans** [comment]
It sounds like this issue is now fixed. Thanks for letting us know!
