### ISSUE TITLE
Memberlist is missing everyone except a few heros

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7766]
### Steps to reproduce

- Turn on lazy load months ago
- Have a well-filled cache
- Click on a room (#whatsapp:maunium.net)
- 4 members load, out apparently 89

I'd expect members to eventually turn up

Log: sent

### Version information
- **OS**: Ubuntu
- **Version**: 0.17.3

**Comment by Half-Shot** [comment]
I've not seen this one in a while, can I close it?

**Comment by turt2live** [comment]
no one else has commented saying the issue exists, so sure.
