### ISSUE TITLE
Make it usable: check webrtc calls/jitsi/widgets UX isn't completely broken and fix if it is.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7781]
- [x] fix integration manager not working on /experimental

**Comment by bwindels** [comment]
Integration manager is broken because it uses /develop on scalar

**Comment by bwindels** [comment]
WebRTC call works, Jitsi & widgets work.

**Comment by dbkr** [comment]
* I have seen the jitsi call hang up when switching to certain rooms, indicating a problem with the persistent widget stuff.
* I think the jitsi screen share stuff in electron might also have bitrotted in some fashion
