### ISSUE TITLE
Sometimes legit invitees cannot write in a room

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#7790]
See here: https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1544110954587329cEkKR:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org&via=chat.weho.st

**Comment by turt2live** [comment]
There's no logs associated with this, and the linked conversation doesn't really help narrow down the issue. Closing as a duplicate of https://github.com/vector-im/riot-web/issues/7838 to track the larger issue here: https://github.com/vector-im/riot-web/issues/7843
