### ISSUE TITLE
[Feature request] Add a cute seal emoji

### ISSUE THREAD

**Issue by CsatiZoltan** [vector-im/riot-web#7791]
Related issue #2648 , though no solution is provided so far to define custom emojis.

**Comment by lampholder** [comment]
ᶘ ᵒᴥᵒᶅ

**Comment by lampholder** [comment]
(The right solution to this is absolutely to support custom emojis)

**Comment by CsatiZoltan** [comment]
> 
> 
> ᶘ ᵒᴥᵒᶅ

Can you elaborate how you typed it?

**Comment by turt2live** [comment]
Custom emoji would be https://github.com/vector-im/riot-web/issues/2648

For now, we're moving towards relying on the operating system's emoji (https://github.com/vector-im/riot-web/issues/9281) so a request to the Unicode consortium may be in order. Closing this as a duplicate of https://github.com/vector-im/riot-web/issues/2648 and https://github.com/vector-im/riot-web/issues/9281
