### ISSUE TITLE
Add a way to temporarily mute notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7796]
eg: `/mute 5m` or something

**Comment by lampholder** [comment]
HOW DOES THIS NOT HAVE MORE UPVOTES?

**Comment by aaronraimist** [comment]
This is pretty advanced but I'd also love a way to schedule it. For example I'm in a room that is extremely busy once a week at a specific time so I'd like to turn of push notifs during that time but during the rest of the week it is pretty quiet so I want notifications.

**Comment by aaronraimist** [comment]
Oh just realized this is a duplicate of #3569
