### ISSUE TITLE
Right-click on Room List should *not* open a custom context menu

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7798]
please O:-)

**Comment by turt2live** [comment]
worth noting that the current behaviour is the result of fixing a bug: https://github.com/matrix-org/matrix-react-sdk/pull/1978

**Comment by lampholder** [comment]
I'd say just don't reimplement this in the new UX?

One thing I like about Slack's UX is that channels in the channel are links - this means that the right click context menu gives you 'copy link' and 'open in new tab' for free.

**Comment by turt2live** [comment]
This is an accessibility feature, and something we've repeatedly said we're keeping as expected behaviour.
