### ISSUE TITLE
Sending a message into a room fails with CORS rejected while doing a /members query

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7800]
### Description

For one of my rooms, see attached logs.

### Steps to reproduce

- Open the bugged room.
- Try to send a message.

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: 0.17.6

**Comment by Half-Shot** [comment]
I've not seen this in a long time, can I close it?

**Comment by turt2live** [comment]
no one else has commented saying the issue exists, so sure.
