### ISSUE TITLE
CORS error failing to connect to HS using Brave

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7801]
https://twitter.com/gustavmarwin_/status/1071795509537529856?s=21

**Comment by lampholder** [comment]
P1 to investigate this and see how easy it is to fix. If it's straightforward then we should fix it, but we should think twice if it's going to require a lot of effort.

**Comment by jryans** [comment]
This appears to be upstream issue in Brave's blocking mechanism. Blocking third-party cookies also affects requests.

I have filed an [issue](https://github.com/brave/brave-browser/issues/2521) with Brave and [replied](https://twitter.com/jryans/status/1073169479650172928) to the user.

**Comment by aaronraimist** [comment]
The upstream Brave issue is fixed and a quick test shows Riot works for me in the latest version of Brave

**Comment by turt2live** [comment]
counting that as fixed, thanks @aaronraimist !
