### ISSUE TITLE
Gopher links don't display correctly

### ISSUE THREAD

**Issue by hook54321** [vector-im/riot-web#7802]
Gopher links don't display correctly and clicking them doesn't do anything

- **Platform**: Desktop

![image](https://user-images.githubusercontent.com/7744057/49737009-8f4e7880-fc83-11e8-9732-4d872f37386b.png)

**Comment by lampholder** [comment]
You're welcome to submit a PR to fix this (it's probably a trivial addition to the set of linkified protocols) but I'm afraid I don't think it's something we'll get to any time soon :P

**Comment by t3chguy** [comment]
Sadly not that simple 
This is a duplicate of https://github.com/vector-im/riot-web/issues/5094

**Comment by hook54321** [comment]
What about https://github.com/vector-im/riot-web/issues/4457 ?

**Comment by t3chguy** [comment]
That too, though that issue has slightly devolved into handling `file://` in the desktop app, which does get linkified correctly, so its just Related to that one
