### ISSUE TITLE
Pinning unread rooms is broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7803]
again

**Comment by turt2live** [comment]
I'm convinced this is particularly broken on /experimental since the Great Merge last week. My room list has just been ordered incorrectly and refuses to update at times. Independent of #7826, this should still work within some degree of usability.

**Comment by rubo77** [comment]
I think the logic is missing a point here: At the moment, there are only two options:

- Pin unread rooms to the top of the room list
- Pin rooms I'm mentioned in, to the top of the room list

But the first option leaves you with a long list of rooms that are set to "Mentions only" where you don't care to read everything. Rooms where there was acticvity last are listed below those (for you unimportant) rooms.

We need a third option:

- Pin unread, **not muted** rooms to the top of the room list

**Comment by turt2live** [comment]
Both options are disappearing soon in favour of prioritizing rooms people are more like to care about (ie: forcing the pin options on for everyone, with some other tweaks).

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2634
