### ISSUE TITLE
E2E: Account Settings: Account Section: Warning on other devices that a new recovery method has been set.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7806]
Part of https://github.com/vector-im/riot-meta/issues/228

At the moment you'll only be notified when you refresh or you start a new megolm session. (This might no be a sufficient UX).

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.26nq3b78b51w

**Comment by dbkr** [comment]
Resolved by https://github.com/matrix-org/matrix-react-sdk/pull/2360
