### ISSUE TITLE
E2E: Account Settings: Security and trust section: Introduce the concept of trusted users to the js-sdk/react-sdk

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7809]
Part of https://github.com/vector-im/riot-meta/issues/228

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.26nq3b78b51w

**Comment by uhoreg** [comment]
This seems to be done with the latest cross-signing work
