### ISSUE TITLE
E2E: Security Notifications: Room view decoration signalling to a user whether the room is 'trusted'

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7823]
Part of https://github.com/vector-im/riot-meta/issues/232

Room view decoration signalling to a user whether a room is 'trusted, assuming a room is trusted when you trust all of the users in it (not necessarily all of the devices)

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.2tsmbascrbtf

**Comment by lampholder** [comment]
We should make sure this task still makes sense when we have a shared understanding of 'trusted users'

**Comment by lampholder** [comment]
Okay, so my current understanding (which I realise my contradict prior understandings) is:
- I trust a user if I have verified their 'user key'
- their devices are trusted by me if they have signed them with the 'user key' I have verified
- a room is trusted if all the devices of all the users in the room are trusted

Interesting question:
- what if a room is set to only encrypt messages for trusted devices? Can it have the 'trust' tick then, because all of the traffic is guaranteed only to be shared amongst trusted devices?

**Comment by turt2live** [comment]
Done in redesign
