### ISSUE TITLE
Need to figure out the design for pinned rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7826]
*Note*: Where this issue references mobile clients, only riot-android was tested. I don't have an iOS device to play with, unfortunately.

## History

The ability to pin rooms that are unread/have mentions to the top of the room list is often requested, and now that it exists there's a bit of uncertainty on how exactly it should work. The original issues that reference the feature are:
* https://github.com/vector-im/riot-web/issues/1104
* https://github.com/vector-im/riot-meta/issues/96

There's also been some bugs during the journey to where we are today:
* https://github.com/vector-im/riot-web/issues/7645
* https://github.com/vector-im/riot-web/issues/7646
* https://github.com/vector-im/riot-web/issues/7723
* https://github.com/vector-im/riot-web/issues/7803

The feature is split into two parts: pinning rooms with unread mentions (pings) and pinning rooms with unread messages. These are independent options on both riot-android and riot-web, and should have the same effect.

For simplicity, this issue references rooms with the setting "mentions only" as "bold" rooms. This is a shared concept between the mobile clients and riot-web.

## How riot-web is supposed to do it

This is the subject for debate, however this is how it is designed to work currently (assuming there were no bugs outstanding). The theory is that it is based off the riot-android behaviour in that rooms on the homescreen are ordered pings > unread > bold > everything else, like so:
![image](https://user-images.githubusercontent.com/1190097/49758973-8ce92000-fc7d-11e8-88f4-d61324c5016f.png)
*I'm in far too many rooms to show that there are rooms which have read messages - just assume they exist for the sake of the argument*

This is what the equivalent behaviour looks like on riot-web:
![image](https://user-images.githubusercontent.com/1190097/49759010-b30ec000-fc7d-11e8-960e-a429605c4460.png)

## It is easy for a room to get lost in the room list when reading it

This is the complaint I see most often regarding pinned rooms. If people have other concerns with how it works from a design perspective, please comment below. Please bear in mind that if what you're experiencing does not match what is above, then you are almost certainly seeing a bug and not a feature.

When you click on a room to read it, the list reshuffles to make sure your unread rooms stay at the top. Although this isn't too much of a problem if you only have a few rooms with unread messages, it can be a significant problem when there's lots of rooms or high volumes of traffic.

For some people it is very easy to end up in a situation where they have 10+ unread rooms and a "show more" bar at the bottom of the section. When they click a room to read it, it quickly jumps to the bottom of the list which happens to be under the "show more" banner, hiding it. Previously there was a bug in the riot-web implementation which caused bold rooms to not sort correctly (making the order pings > unread > everything else), so it wasn't much of an issue given people with this many rooms appear to set rooms to "mentions only" (ie: bold when unread) anyways. 

Although the jump-to-the-end behaviour is the same on riot-android, the UX is a bit different. When opening a room from the start screen, your entire view is replaced by the room which can cause you to forget what the order of the rooms was previously. Upon going back to the start screen, your room list would have been re-ordered but you also wouldn't care too much about the room you just looked at anymore. With riot-web giving you a constant reminder that the room list exists, it may be desirable to reconsider how the room list orders itself.

**Comment by turt2live** [comment]
/me defers to @lampholder for the rest of the labels

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2634

**Comment by ara4n** [comment]
@erikjohnston this seems to be a contradiction?

> Personally, I really really prefer having the ability to only pin rooms with unread messages in, as I lurk in too many rooms for it to be viable to pin all unread rooms.

'Only pin rooms with unread notifications'?

**Comment by erikjohnston** [comment]
As in only pin rooms which have unread badges and don't pin rooms which are just bold (i.e. unread but muted rooms).
