### ISSUE TITLE
E2E: Cross signing (js-sdk)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7827]
Part of https://github.com/vector-im/riot-meta/issues/234

- [X] functions to save/load public signing keys on server
- [X] functions to create/refresh/save signing keys
- [ ] manage trust on own cross-signing keys received from server
- [ ] functions to send private signing key to another device
- [x] functions to sign/verify devices
- [x] functions to sign/verify other users' ssk's
- [ ] send/receive/store device signatures
- [ ] modify verification functions to verify ssk
- [x] functions to get user/device verification status
- [ ] unit tests on everything
- [ ] modify key backup so that it signs/verifies using ssk

**Comment by lampholder** [comment]
This is https://github.com/matrix-org/matrix-js-sdk/pull/832

**Comment by uhoreg** [comment]
I'm working on this by getting test cases working.  The test that I'm working on are:

- [ ] upload signature when a user is verified
- [ ] get ssk and usk from sync
- [ ] use trust chain to determine device verification
- [ ] trust signatures received from other devices
- [ ] dis-trust an unsigned device
- [ ] dis-trust a user when their ssk changes

**Comment by uhoreg** [comment]
Obsoleted by another issue
