### ISSUE TITLE
Clicking an avatar shows different information if clicked in chat or user list

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#7851]
Seen in #offtopic-gingerbread:half-shot.uk, Riot Web 0.17.8, FF 63.0.3:

Click on Coffee in user list:
![deepinbildschirmfoto_bereich auswahlen_20181213093909](https://user-images.githubusercontent.com/1236369/49926488-f0f92780-febb-11e8-8fb4-840d952c19e6.png)

Click on Coffee in chat:
![deepinbildschirmfoto_bereich auswahlen_20181213093821](https://user-images.githubusercontent.com/1236369/49926521-0706e800-febc-11e8-9790-99f8b2c5040e.png)

Note the differing power level and presence status.

One other room member sees the same, one doesn't.

**Comment by anoadragon453** [comment]
To add on to this, when I click a user's info from the timeline I get the following:

![image](https://user-images.githubusercontent.com/1342360/49936322-e9457d00-fed3-11e8-9d11-5fe6b2a145eb.png)

Whereas coming from the userlist gives:

![image](https://user-images.githubusercontent.com/1342360/49936342-f8c4c600-fed3-11e8-9f42-65b45f53a593.png)

**Comment by t3chguy** [comment]
Seemingly clicking in the timeline shows the user at that exact instance, like their historical data, so it makes sense it doesn't have presence data, but why the heck is this a thing?

**Comment by t3chguy** [comment]
This causes even more confusion if the user has since left as it gives you options like Kick and Mute which require the user to be in the room to function

**Comment by t3chguy** [comment]
This is fixed in UserInfo (cross-signing)
