### ISSUE TITLE
Formating error with backtick in chats (for codes)

### ISSUE THREAD

**Issue by Extarys** [vector-im/riot-web#7852]
### Steps to reproduce

- Type a text
- Put 3 backtick on the current line instead of a blank (new) line
- Type some code
- Put 3 more backtick

Some text
``` < at the end of the previous line
My code
```

Sorry I don't know how to disable formatting in github

Describe how what happens differs from what you expected.

The message is deformed 
![flameshot-2018-12-13-04-58-39](https://user-images.githubusercontent.com/11581433/49931065-08241f00-fe94-11e8-9cec-26030249cfb4.png)

It should be able to correct the formatting before displaying the text. This works well in discord.

### Version information

- **Platform**: desktop, probably web too

- **OS**: Linux Mint
- **Version**: 0.17.8

**Comment by t3chguy** [comment]
Could you verify the same happens here: https://spec.commonmark.org/dingus/

**Comment by Extarys** [comment]
Yes it does. I guess this is the engine riot uses to render text.

But look on Discord:
![image](https://user-images.githubusercontent.com/11581433/49931454-e2e3e080-fe94-11e8-8343-f0957758b7fa.png)

I think I'm not alone when I say that sometimes I type too fast. The current render is quite ugly and break the design and overall experience.

**Comment by t3chguy** [comment]
It's just down to what dialect of markdown discord uses, the one riot chose has the behaviour you describe

**Comment by Extarys** [comment]
And it's not optimal and should be fixed. It's why I opened an issue.

**Comment by t3chguy** [comment]
It can only be fixed upstream in the commonmark specification, or by switching dialect which has been rejected several times, so maybe best would be to make a ticket with them

**Comment by lampholder** [comment]
I'm adding `wontfix` to indicate that we won't special-case changing this behaviour. I totally agree it's ugly and we could do better by special-casing, but I from a maintenance perspective being able to say "we use commonmark and commonmark does _this_" is hugely preferable to "we use commonmark except where we don't".

I'm totally neutral about what markdown dialect we use, as long as we use it without patches/tweaks that are hard to maintain :)

**Comment by Extarys** [comment]
Thanks @lampholder I totally understand. I will try to conceive  commonmark then :)
