### ISSUE TITLE
Kick was shown as a leave

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7853]
We kicked someone who was having trouble joining from their HS (looked like a split). However, the kick shows up as "X left the room" despite the event being submitted by another user:
```
{
  "type": "m.room.member",
  "content": {
    "membership": "leave",
    "reason": "Apparently you aren't even joined"
  },
  "sender": "@Half-Shot:half-shot.uk",
  "state_key": "@benpa:bpulse.org",
  "membership": "leave",
  "event_id": "$1544700825245czgIl:half-shot.uk",
  "origin_server_ts": 1544700825258,
  "unsigned": {
    "replaces_state": "$154099363819RsEzk:bpulse.org",
    "prev_content": {
      "membership": "leave"
    },
    "prev_sender": "@benpa:bpulse.org",
    "age": 552
  },
  "room_id": "!ruaviCwHdJSWfKcBam:half-shot.uk"
}
```

**Comment by lampholder** [comment]
If you /kick a mxid that's neither a room member nor an invited room member, Riot renders this as that mxid's having left (I am certain I filed a bug for this in the past).

Is that what happened here?

**Comment by Half-Shot** [comment]
Oh right, that's probably it. The user was broken so I can believe the membership was also broken.

**Comment by t3chguy** [comment]
So I guess we need to decide how we'd like to show a NOTHING -> Leave (/kick of a user who wasn't even in the room)

**Comment by Half-Shot** [comment]
Feeling is that if the user has no previous state then it shouldn't be shown (as it isn't really a state change).

However, it's a bit more worrying when the client is missing previous state. I guess we could query for state about the member in the absence of state, and show a kick/leave message if appropriate.

I don't *think* calls to /state/m.room.member/@foobar:matrix.org is expensive?

**Comment by turt2live** [comment]
tbh I'm not sure why we even need to consider the prev content for a kick: a kick by definition is making a user `leave` who is not yourself.

**Comment by lampholder** [comment]
Isn't @Half-Shot saying we need to consider the prev content to know whether it's a kick (causing somebody who is not you to `leave`) or a noop?

**Comment by turt2live** [comment]
You don't though, because `state_key !== sender ? kick : leave`

**Comment by Half-Shot** [comment]
>tbh I'm not sure why we even need to consider the prev content for a kick: a kick by definition is making a user leave who is not yourself.

I think this is acceptable.

**Comment by t3chguy** [comment]
Because if they weren't really in the room then you aren't making them leave

**Comment by turt2live** [comment]
That sounds like a spec problem, not a UI/UX problem. Not to mention the case of someone going out of their way to kick someone that wasn't in the room is fairly rare.

**Comment by t3chguy** [comment]
> Not to mention the case of someone going out of their way to kick someone that wasn't in the room is fairly rare.

Yes but by mistake, such as a typo, I can imagine it happening

**Comment by turt2live** [comment]
I'm still convinced that we should fix that particular case in the spec, not in the UI.

https://github.com/matrix-org/matrix-doc/issues/1928
