### ISSUE TITLE
!giphy is not working

### ISSUE THREAD

**Issue by erikbye** [vector-im/riot-web#7854]
Web and desktop. 

!giphy is not doing anything.

It seems to not be working for any integrations. E.g. wikipedia.

There is no error message, the command just get submitted to the room as a regular message.

**Comment by XHotSniperX** [comment]
@erikbye how did it work? Having the same issue

**Comment by t3chguy** [comment]
Are you in an encrypted room?

**Comment by XHotSniperX** [comment]
yes

**Comment by t3chguy** [comment]
@XHotSniperX Well the bots don't support encrypted rooms as then you'd be leaking your entire room to the operator of the bot, in this case matrix.org

**Comment by XHotSniperX** [comment]
oh okay, thanks for the info
