### ISSUE TITLE
Redesign: new jump to unread button is hard to spot

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7855]
Matthew wrote: The unread message marker needs a placeholder badge of some kind - even if it's just a dot or exclamation mark of something.  Otherwise it just blends into the background.

**Comment by uhoreg** [comment]
The jump to unread button also needs a way to dismiss it

**Comment by bwindels** [comment]
add badge with white dot

**Comment by bwindels** [comment]
> The jump to unread button also needs a way to dismiss it

@uhoreg It will dismiss itself after 30s now, and given that it's visually a lot less intrusive, we thought we could do without a dismiss option. Still evaluating this though.
