### ISSUE TITLE
E2E: Copy / download recovery key should have primary styling

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7857]
The `[Copy to clipboard]` and `[Download]` buttons on the Recovery Key page are secondary-styled, so it's not obvious that you need to click them to continue. I think they should be primary-styled.

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/49947761-e81f4a80-fee9-11e8-9a6b-1c1ce7456330.png)

**Comment by lampholder** [comment]
Just looks like a bug that the [Copy to clipboard] and [Download] buttons are secondary- rather than primary-styled:

![image](https://user-images.githubusercontent.com/1922197/50165846-b3423780-02dd-11e9-9493-307ca81a46cf.png)

**Comment by lampholder** [comment]
@jryans - I spoke with Nad about this and he's going to have a look at ways we can fix the odd bouncing-between-modals UX. Regarding the first bullet (primary- vs secondary-styling) this just looks like a bug - could you fix?

**Comment by jryans** [comment]
Right, the button styling seems straightforward. I'll do that for now, and wait to hear from @nadonomy on the modal navigation issues.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2375.
