### ISSUE TITLE
Hard to read e2e key backup dialog on the dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7859]
![image](https://user-images.githubusercontent.com/1190097/49962513-ab942480-fed2-11e8-9754-018eb4a3b122.png)

(blue tint is my custom tint)

related: https://github.com/vector-im/riot-web/issues/2988

**Comment by jryans** [comment]
I am assuming this is currently low priority as the dark theme is rethought and E2E dialogs are soon to get detailed mockups. I would assume one or both of these projects will improve this.

**Comment by aaronraimist** [comment]
This got fixed in the new dark theme
