### ISSUE TITLE
E2E: Registration and Login: Cross-sign via Recovery Passphrase / Key

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#7865]
Part of vector-im/riot-meta#229.

Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.6ojk5yl2sbr7

**Comment by uhoreg** [comment]
This seems to be done already
