### ISSUE TITLE
Grey gradient shouldn't be present at the bottom of room sublist if you're at the bottom of that list.  However if you filter the list, that check fails and so you get an unwanted gradient.

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7867]
Bruno: yeah, see https://github.com/vector-im/riot-web/issues/7561#issuecomment-437855264

**Comment by babolivier** [comment]
I don't know if this is the right issue, but it doesn't look solved on my end. Here's what I get when I filter rooms for a specific community (the list of which doesn't fill up the height of the container entirely):

![image](https://user-images.githubusercontent.com/5547783/50095188-d224c900-020c-11e9-9cd4-e3be6dc2eeae.png)

I'm using the version currently deployed on `/experimental`, and flushed my cache to make sure I wasn't behind on something.

**Comment by bwindels** [comment]
Should be fixed now, please reopen if it still happens.
