### ISSUE TITLE
Can't use a password manager to register an account

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7868]
When picking a password, it goes into the 'confirm password' field rather than both password fields. Additionally, the form complains about a missing password.

**Comment by lampholder** [comment]
Which password manager are you using? 1password seems to do a good job (though the **Missing password** error notif doesn't clear even after blurring the password input fields). 

![image](https://user-images.githubusercontent.com/1922197/50280530-ad1a9b00-0444-11e9-8279-148998e4683b.png)

**Comment by lampholder** [comment]
Also one for the new login UX to manage - we should test it against lastpass and 1password (any other popular choices?) and try and make sure the experience is good.

**Comment by turt2live** [comment]
I use LastPass and Chrome's built in one.

**Comment by lampholder** [comment]
New login doesn't play nicely with 1password :(

**Comment by jryans** [comment]
At the moment, develop appears to support:

  | Save from Registration | Save from Login | Use on Login
--- | --- | --- | ---
**1Password** | ✅ | ✅ | ✅
**LastPass** | ✅ | ✅ | ✅ 
**Chrome** | ✅ | ✅ | ✅  

If there are other issues here, please file an new issue with detail about the specific situation.
