### ISSUE TITLE
With Kindle Fire, Riot incorrectly detects wrong platform, no option to log-in

### ISSUE THREAD

**Issue by andy5995** [vector-im/riot-web#7869]
### Description

Using the Amazon Silk browser, I was not given the option to log-in to the web version of Riot. Riot seems to detect an IOS or Android operating system (indicated in screenshot below).

### Steps to reproduce

Using Kindle Fire 10.1 (7th generation - 2017 release), in the Amazon Silk browser:

- I went to riot.im
- was redirected to https://about.riot.im/ 
- I clicked on the "Launch" option
- was redirected to the mobile version
- was given the option to install the app from 3 different app stores
- Nowhere could I find the option to log in through the Silk browser with my existing riot account

![screenshot_2018-12-14-22-27-08](https://user-images.githubusercontent.com/16764864/50039021-8f86a500-fff0-11e8-9c56-79588a43a353.png)

### Version information

- **Platform**: Kindle Fire 10.1 (7th generation - 2017 release)

For the web app:

- **Browser**: Silk (latest available version)
- **OS**: Amazon Fire OS
- **URL**: riot.im/app

## Temporary Solution

I was able to log in by using a chat-room link.

At the first page I mentioned (in the screenshot above), choosing the option "Desktop site" from the Silk menu solved the problem. I didn't think to look for it though.

By the way, riot seems to work fine with Silk on a Fire. I haven't used it much yet, but haven't noticed any problems after I'm able to log in.

**Comment by jryans** [comment]
At the moment, this is done because the Riot Web layout is not optimized for mobile devices, or at least not the small width of most phones. Tablets are more of a gray area I suppose... However, the mobile apps are still recommended for a better experience that handles notifications and other OS integration.

**Comment by turt2live** [comment]
Unfortunately the Kindle Fire is all sorts of unsupported for Element at the moment - closing as something we are unlikely to fix specifically, though we have some interest in potentially exploring options for mobile browsers in the future.
