### ISSUE TITLE
No offline status visible.

### ISSUE THREAD

**Issue by MilkmansWife8291** [vector-im/riot-web#7871]
Me and a friend are looking for an open source chat software, Riot seems very good, except that in our room we cannot see whether the other is offline or not in the members menu to the right. We are using the default server. How would we get this to work?
This problem is present for myself in both desktop and browser versions (Windows 7 Ultimate 64-bit, latest Firefox, latest Pale Moon) and himself in browser version, he has not tried the desktop app (Windows 10, latest Firefox).

**Comment by jryans** [comment]
The default server on matrix.org currently has user presence disabled. If you run your own homeserver, you could enable it there as one way to get this feature.

We hope to re-enable presence on matrix.org in the future. More info available in #2667.
