### ISSUE TITLE
Make icons consistent

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#7883]
> Icon spacing is all broken in the top right, and uses distinctly adhoc icons (e.g. travis's pin icon for pinned messages; rick's modular icon; luke's share icon)... all of which need to be homogenized

**Comment by nadonomy** [comment]
Closing for this sprint, although we'll continue to iterate on this in future.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2370.
