### ISSUE TITLE
Redesign: membership list ordering is wrong; high PLs are no longer at the top.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7886]
(instead it's ordering by broken presence)

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/6953

**Comment by bwindels** [comment]
@turt2live It's not broken on /develop though ... This is on /experimental.

**Comment by turt2live** [comment]
#6953 is the issue for broken on develop. I've also seen it broken constantly on develop. Unless this issue is referencing something else, it's not an experimental-exclusive issue.

**Comment by bwindels** [comment]
Ok, that does sounds like the same thing then.
