### ISSUE TITLE
Gradient alphas ugly on Safari

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7889]
Bruno: have a screenie?

**Comment by nadonomy** [comment]
<img width="277" alt="screenshot 2018-12-17 at 17 45 38" src="https://user-images.githubusercontent.com/4626865/50105085-a19c5980-0223-11e9-804b-3ae9be79fcd8.png">

**Comment by bwindels** [comment]
My suspicion is that safari isn't supporting the `linear-gradient(color1, color2)` or `transparent` syntax we're using well, and need to use something more explicit.

> That's what I saw on Windows 10 Firefox too. Well not that extrem Bad but it feels way to much and big.

Odd, I suspect this might be due to something else. Could you provide a screenshot as well @MTRNord?

**Comment by nadonomy** [comment]
This should be fixed with this PR:

https://github.com/matrix-org/matrix-react-sdk/pull/2373

@MTRNord if you're still experiencing this, please comment on this issue with a screenshot and we can dig deeper.
