### ISSUE TITLE
E2E: In-room reminder to set up backup if one exists

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7902]
If we start up and see an e2e key backup but can't use it because the creating device is not verified, show the prompt to set it up by verifying that devices.

**Comment by jryans** [comment]
After chatting with @nadonomy, we're thinking we'll use an in-room reminder for this case as well, but with different text from the initial set up reminder (since in this case you want to sync an additional device to an existing key backup by trusting it).

Precise wording to be defined.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2394.
