### ISSUE TITLE
'Remove' button on LLP can be confusing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7909]
People (including me) can end up thinking that they'll leave the group but it doesn't do that. We might need additional user education in the LLP area

**Comment by turt2live** [comment]
tulir says: just add a new button after the remove to leave?

**Comment by lampholder** [comment]
This _should_ be easy to fix, but trips over our not having a good name for that left-left panel.

Ideally we'd rephrase 'Remove' to 'Remove from Communities Panel' and add a 'Leave Community' button which actually quit the community (with a confirmation dialogue I'd expect).

Is 'Communities Panel' a good enough name? Communities Quick List? Speed Dial?

**Comment by lampholder** [comment]
I think 'Communities Panel' might be good enough.

**Comment by aaronraimist** [comment]
Isn't this called "Hide" now? I think that makes more sense.

**Comment by turt2live** [comment]
Yup, it sure is.
