### ISSUE TITLE
Use :smile: instead of :smiley: for :D auto-replacement

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#7910]
### Description

When auto-replacement of emojis is enabled, `:D` becomes :smiley: (`:smiley:`) while I think it is more appropriate to use :smile: (`:smile:`). In both Riot, Github and Slack, :smiley: looks more like a "oh, surprise" than a "it's funny".

I always had this feeling that it was the wrong smiley that was used, but thought that it was just the emoji library that was like that, but I discovered that Slack was also using `:smile:` for `:D`. Which is yet another argument.

And also, it's more logical since `:)` is replaced by `:slight_smile:`, with no `y` in the end.

### Steps to reproduce

- Write `:D` and <kbd>Space</kbd>

What happened: it is replaced by :smiley:
Expected: should probably be replaced by :smile: instead.

### Version information

- **Platform**: both web and desktop

For the web app:

- **Browser**: Firefox 64
- **OS**: Linux (Fedora)
- **URL**: riot.im/app

For the desktop app:

- **OS**: Linux (Fedora)
- **Version**: 0.17.6

**Comment by Matrixcoffee** [comment]
Weird. I've always associated `:D` with 😁

**Comment by MightyCreak** [comment]
`:grin: ` :grin: make me feel more like the auto-replacement for `^^`.

**Comment by MightyCreak** [comment]
Ok so, I've read the code a little and apparently the auto-replacement list is not done by Riot devs, but it's coming from the emojione third party module: https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L101 (line 101).

So it would need to push a change here...

**Comment by MightyCreak** [comment]
I've entered an issue in emojione: https://github.com/emojione/emojione/issues/635

We'll see how it goes...

**Comment by tulir** [comment]
FYI: Riot uses an outdated emojione and can't update as emojione 3+ has a bad license. Hopefully Riot will switch to Noto Color Emoji or Twemoji soon (#7354)

**Comment by lampholder** [comment]
> auto-replacement list is not done by Riot devs, but it's coming from the emojione third party module

I'm pretty certain that's the case

> FYI: Riot uses an outdated emojione and can't update as emojione 3+ has a bad license

This is sadly certainly the case.

Fwiw I don't think we should consider managing our own mapping of :textname: -> emoji - I'll be happiest if we adopt a standard emoji library and embrace its standard :textname: -> emoji mapping.

**Comment by MightyCreak** [comment]
> Fwiw I don't think we should consider managing our own mapping of :textname: -> emoji - I'll be happiest if we adopt a standard emoji library and embrace its standard :textname: -> emoji mapping.

I agree 100% for the :textname: -> emoji mapping, but I think it's arguable for smileys (`:)`, `;)`, `:D`, etc...) since the list is way shorter and, most importantly, not standardized as the emoji textnames are.

**Comment by aaronraimist** [comment]
:D is now 😁 which I think makes sense

**Comment by jryans** [comment]
Yes, I think we can consider this fixed by the switch to Emojibase for this data.
