### ISSUE TITLE
Experimental: Selected Right Side Panel does not persist over room swaps

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#7911]
I generally find the notifications right panel to be more useful than the room member list, so I would like to have it as my default panel. If I select it and then change room the selection is reset to the member list.

**Comment by tulir** [comment]
This doesn't seem to be related to the redesign

**Comment by lampholder** [comment]
I'd love to see this - I too would love to replace the memberlist with my notifs panel as default.

**Comment by yannicka** [comment]
For my part, the notification panel remains open when I change rooms. Has the issue been fixed?

**Comment by t3chguy** [comment]
Yup!
