### ISSUE TITLE
E2E: Simplify create key backup navigation maze

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#7912]
From @lampholder (extracted from #7857):

After clicking [Copy to clipboard] and navigating to the subsequent screen, I expected to click the primary button and to have completed key backup. I was surprised when I got dragged back to the Recovery Key page, and actually without thinking about it clicked [Copy to clipboard] and bounced back and forth a few times before realising I had to click the now-enabled [I've made a copy]. Could the success modal for copying to clipboard include a back button as well as finish button?

**Comment by jryans** [comment]
I believe the current status here from before the holidays was that @nadonomy was rethinking this flow, so we were waiting on him before proceeding. If we want to resolve this without detailed UX help, we could also proceed with something like @lampholder's suggestion above of going to a "done" screen after completing copy / download that also offers a way back if you also wanted to both copy *and* download.

**Comment by nadonomy** [comment]
@jryans I vaguely remember discussing this briefly before we broke for the holidays. I'd go with your original suggestion of the success modal having a secondary [Back] button and then we change the behaviour of [Done] to finish setup.

I'll update the wireframes shortly to reflect this.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2405 on experimental.
