### ISSUE TITLE
UX - cannot access room directory in riot-web/experimental

### ISSUE THREAD

**Issue by sandys** [vector-im/riot-web#7923]
hi guys,
I'm coming from Slack/Hipchat. It is really very difficult for me to figure out how to get the list of rooms on my server, so that i can browse and join. 
We are planning to use Riot/Modular for our company as a replacement for Slack and we have a lot of rooms that people can potentially join. So a browse behavior is very very important.

**Comment by jryans** [comment]
At the moment, the room directory isn't present in the redesign, but that's only temporary. It will reappear before this becomes the stable version.

**Comment by jryans** [comment]
(In case it's unclear, in stable / released Riot, you can reach the room directory via the "3 bullets" icon in the bottom left corner.)

**Comment by bwindels** [comment]
tracking this here: https://github.com/vector-im/riot-web/issues/7607
