### ISSUE TITLE
Redesign: incomplete memberlist

### ISSUE THREAD

**Issue by MayeulC** [vector-im/riot-web#7924]
### Description

When using riot.im/experimental, not everyone shows up in the memberlist for _**#riot-design:decentralizing.world**_. Only members who spoke since I joined seem to show up. Note that user "Baco" only made multiple status changes before my joining, yet (s)he appears in the memberlist.

Attached below are two screenshots of that room, from the old design, as well as the new one.

![old-memberlist](https://user-images.githubusercontent.com/3952726/50277803-b1938380-0445-11e9-8afb-35ed1e7a80e0.png) ![new-memberlist](https://user-images.githubusercontent.com/3952726/50277807-b5270a80-0445-11e9-841e-d4c504d398ef.png)

### Steps to reproduce

Unfortunately, I am unsure how to reproduce this. Maybe you need to join a room that is publicly-readable?
I tried to reproduce by joining **_#VideoLAN:matrix.org_** as an example, but could see every member.
I am writing this bug report nonetheless so that users affected by the same bug can figure out a way to reproduce this.

### Version information

- **Platform**: web
- **Browser**: Firefox 64.0
- **OS**: Arch Linux
- **URL**: riot.im/experimental, compared to riot.im/app

**Comment by lampholder** [comment]
There's a good chance that this is related to lazy loading generally rather than the redesign specifically, so I'm going to triage this as a wider bug for now.

**Comment by yannicka** [comment]
Is the problem still there?

**Comment by t3chguy** [comment]
Presumed fixed

**Comment by MayeulC** [comment]
Yeah, sorry about that. I haven't hit that issue for quite some time, and forgot I had filled it in the first place. Thanks for noticing :)
