### ISSUE TITLE
Experimental: Mashing text in to the room filter can freeze the whole app

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7926]
No logs 'cause it ded.

I've seen this now on two occasions; it's occurred when I've mistyped what I'm trying to filter a few times and then mashed a bunch of stuff in frustration (this detail may or may not be important)

**Comment by lampholder** [comment]
Another clue: the processor goes nuts, so some sort of infinite loop might be occurrign.

**Comment by jryans** [comment]
From the profile @lampholder shared, this is caused by an infinite loop in `_onMoveFocus` from `LeftPanel.js`. I'll keep digging.

**Comment by jryans** [comment]
Steps to reproduce:

1. Enter enough random characters in room filter so that no rooms match
2. Press the Enter key

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2380.
