### ISSUE TITLE
Use versioned URLs for images

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#7932]
We don't want to wait for caching to expire with quick changes.

**Comment by jryans** [comment]
This will help @nadonomy iterate quickly on experimental, for example.

**Comment by jryans** [comment]
The ideal case would be for the URL to contain the hash of the file, so that it only changes when the file changes. If that's too hard, then using the bundle ID similar to JS and CSS URLs is a good option as well.

**Comment by ara4n** [comment]
see also 
https://github.com/vector-im/riot-web/issues/233

**Comment by jryans** [comment]
I have an approach that extends the Webpack build process to add a content hash to image URLs to achieve this.

However, it does require changing all JSX usages of images from:

```js
<img src="img/warning.svg" />
```

to:

```js
import WarningSVG from "img/warning.svg";
// ... other code ...
<img src={WarningSVG} />
```

Does anyone have opinions about this transformation? Feel free to add reactions here if you have them.

For cases where we use images via CSS `url`s, no change is needed.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2460 and https://github.com/vector-im/riot-web/pull/8159.
