### ISSUE TITLE
Add a dismiss button to the upgrade nag bar

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#7936]
<img width="1439" alt="screenshot 2018-12-21 at 09 34 15" src="https://user-images.githubusercontent.com/4626865/50335718-1c0af900-0504-11e9-9e3b-0bdcf34ee620.png">

**Comment by lampholder** [comment]
_Should_ this just be dismissable?

Dismissable without a follow-up nag strategy sounds like a recipe for people running out-of-date clients - I'm not sure the UX + of making this dismissable is worth this tradeoff.

Obviously if we want to spend a little more time on this, we could implement a more sophisticated nag strategy UX, but I don't know if it's worth it at this time.

**Comment by aaronraimist** [comment]
<img width="238" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/83663862-d8d50680-a58e-11ea-83a6-7478856d691d.png">
Fixed since it is now a toast
