### ISSUE TITLE
Copied e-mail addresses are prefixed with `mailto:`

### ISSUE THREAD

**Issue by martinvonwittich** [vector-im/riot-web#7937]
### Description

When I copy an e-mail address (e.g. firstname.lastname@example.com) by rightclicking on it -> Copy Link Address, my clipboard contains `mailto:firstname.lastname@example.com` afterwards. The `mailto:` that prefixes this is superfluous and I have to manually remove it when I want to paste the address somewhere else, which is annoying.

### Steps to reproduce

- Send a message containing an e-mail address in a chat message, e.g. `firstname.lastname@example.com`
- Right click the address as it is displayed in Riot
- Click on "Copy Link Address"
- Paste it anywhere, and notice the `mailto:` prefix

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 0.17.6

**Comment by lampholder** [comment]
This looks like electron being an idiot.

It's right that they should be mailto: links, and this works fine in Chrome/Firefox. Dunno what we need to do for electron to handle them more sensibly.

**Comment by t3chguy** [comment]
So this is browsers special-casing mailto: links and replacing the `Copy link address button` with a `Copy e-mail address buton` and then stripping this.

**Comment by t3chguy** [comment]
This was fixed
