### ISSUE TITLE
Package webapp into asar file?

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7942]
We should think about packaging the webapp into an asar file in the electron app now that we no longer serve from a file:// URL.

**Comment by t3chguy** [comment]
We did this

**Comment by synnack** [comment]
Well, this causes problems for webapp deploy. The web server serves this directory for clients. Maybe create a seperate package for web servers ?

**Comment by t3chguy** [comment]
@synnack that's https://github.com/vector-im/element-web/issues/2777
