### ISSUE TITLE
matrix-react-sdk is using a 3 year old version of jest's expect library

### ISSUE THREAD

**Issue by trashhalo** [vector-im/riot-web#7947]
### Description

matrix-react-sdk is using a 3 year old version of an expect library. The documentation for this library has exited the internet. This makes it hard for contributors to update your tests.

I found this when I was looking to bring this test file out of xdescribe into a working state again https://github.com/matrix-org/matrix-react-sdk/blob/master/test/components/views/rooms/MessageComposerInput-test.js

### Steps to reproduce

- Look at the package json version of expect. ^1.16.0
- Look at the release list on https://www.npmjs.com/package/expect
- Realize that jests documentation doesn't go back that far https://jestjs.io/en/versions

Describe how what happens differs from what you expected.

I find it kind of strange to be using Jest's expect with karma to begin with. But assume you have a good reason for this mix I would have `expect(matrix).toHaveUpgradedItsLibraries()` in the last 3 years.

### Version information
develop branch

**Comment by trashhalo** [comment]
1. Would you be open to merging a pull request that updated expect to latest version (and dealt with any breaking changes)
2. I noticed the library is using jest expect but with karma. Do you have an interest in switching to the jest test runner too? Is this something you would be open to someone doing in a pull request outside the main contributors?
3. The package json is missing an engine section but the riot readme says there is a min version of node supported. Could I add the engine section in a pull request to better align how the node community communicates node version requirements?
4. The libraries are missing lock files. Is that intentional? Just wondering what that thinking is there

**Comment by jryans** [comment]
> * I noticed the library is using jest expect but with karma. Do you have an interest in switching to the jest test runner too? Is this something you would be open to someone doing in a pull request outside the main contributors?

This sounds like it could be a large change. I am not aware of an existing opinion for or against such a change. The core team is in a bit of a crunch period at the moment though, so I would be worried that the PR might sit open for a while. Probably best to discuss further in #riot-dev first.

> * The package json is missing an engine section but the riot readme says there is a min version of node supported. Could I add the engine section in a pull request to better align how the node community communicates node version requirements?

Sure, feel free to send a PR for this. 😄 

> * The libraries are missing lock files. Is that intentional? Just wondering what that thinking is there

While I believe it has been a clear convention to commit lock files in applications, the advice for libraries tends to differ depending on who you ask. Probably worth discussing more in #riot-dev.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2390.
