### ISSUE TITLE
Users with LLP disabled can't submit feedback on redesign

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7950]

**Comment by turt2live** [comment]
-1 to taking away that option. I run a Riot instance for an organization which explicitly disables it because it doesn't serve any practical purpose in the community interacting with that Riot.

**Comment by lampholder** [comment]
Could we just disable the option/not honour it in the /experimental deploy?

**Comment by turt2live** [comment]
We don't really need to fix this anymore. The help icon just does a rageshake (basically), and thus can be done by the settings.
