### ISSUE TITLE
Redesign: Support for room tags

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#7951]
Just gave `/experimental` a whirl, and the first thing I notice is that rooms aren't listed under tags anymore, as has been the case for the standard, as well as `/develop` release. Please support room tags, ideally not just read-only (i.e. display rooms in the list accordingly), but also give people a means to add/remove tags to rooms, and to manage existing tags (#1373).

**Comment by aaronraimist** [comment]
They are back in 1.0.0 under a labs flag. https://github.com/vector-im/riot-web/issues/8723 is the issue for enabling it by default and getting rid of the labs flag.
