### ISSUE TITLE
README says to link the react-sdk then install riot's deps

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7952]
This will lead to the react sdk being out of date. Problematic section: setting up a dev env

**Comment by t3chguy** [comment]
Nope, `yarn` is smarter than that and the instructions specify yarn :D

**Comment by t3chguy** [comment]
node_modules after a yarn install in riot-web:

![image](https://user-images.githubusercontent.com/2403652/57552378-9d541280-7363-11e9-8a4b-8bdb43d8f389.png)

**Comment by turt2live** [comment]
this was before yarn was a thing, but yup: fixed
