### ISSUE TITLE
Community sidebar needs "x" - but suggest a redesign

### ISSUE THREAD

**Issue by NukeManDan** [vector-im/riot-web#7953]
Just a suggestion - a way to clear the community filter is needed - but as a new user I also was confused by the community sidebar. maybe a way to easily express "all rooms and people" vs. "no community selected" 

It needs to be very clear that all communities do is filter your people and rooms.

**Comment by lampholder** [comment]
The old UX did have an (X) that would appear when a community was selected. We probably do need something along those lines again.

**Comment by rubo77** [comment]
In the desktop app, I cannot find a way to leave the community selection at all. Is there another way than reopening the app?

**Comment by turt2live** [comment]
Clicking the background of the sidebar should clear it.

**Comment by jryans** [comment]
Related: https://github.com/vector-im/riot-web/issues/9026

**Comment by remram44** [comment]
This is extremely non-obvious and should be easy to fix (add a label "click here to deselect" or something to the background if the functionality is still there!) It should probably be considered more of a priority, I had to restart the app and then look for this issue.

**Comment by tmladek** [comment]
>I had to restart the app and then look for this issue.

Absolutely concurred; at first I wasn't even sure if Riot maybe lost the possibility of showing me all non-community rooms and chats. Right now, this breaks basic UI rules.

**Comment by aaronraimist** [comment]
FTUE probably

This is also an accessibility issue, as far as I can tell there is no way to deselect a community using Voice Over.

**Comment by t3chguy** [comment]
The tiles act as toggles as of https://github.com/matrix-org/matrix-react-sdk/pull/3755
