### ISSUE TITLE
Fav / People /People sidebar scrolling for whole sidebar

### ISSUE THREAD

**Issue by NukeManDan** [vector-im/riot-web#7955]
the sidebar for each tab (Fav / People /People) independently scrolls - this should be a single scroll w/ auto collapsing/expanding tabs, as in the native app. 

As a side feature - I would suggest a more prominent display of these tags - they get lost in the list of rooms/people. Possibly giving them a highlighted background or stronger lettering.

**Comment by lampholder** [comment]
It was an intentional choice to move from the old behaviour to this current behaviour (now in place across web and the native app).

We do want to iterate on this, but I'll close this issue for now.
