### ISSUE TITLE
Lazy load read receipts.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7957]
I just did a heap snapshot for the first time in a while, and see 130MB retained by my 1,700 rooms.

Some of these rooms have multiple MB retained *each* by `_receiptCacheByEventId` (plus more for other RR related things).

It feels like the next no-brainer perf improvement really is to LL RRs. (cc @manuroe)

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/6867
