### ISSUE TITLE
Can't find badger emoji

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7964]
### Description

https://emojipedia.org/badger/ isn't found in riot when searching `:badger:`

### Steps to reproduce

- Open Riot
- Go to a chat and start to type `:badger`
- No emoji is found

### Describe how what happens differs from what you expected.

I would like to see badgers available in my riot client.

Log: not sent?    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.17.8

**Comment by t3chguy** [comment]
This is due to an outdated emojione. Closing in favour of #7348

**Comment by Half-Shot** [comment]
Yes, just found it.
