### ISSUE TITLE
Redesign: hovering over rooms under the "Rooms" tag resizes the timeline

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/riot-web#7965]
- **Browser**: Firefox version 64.0
- **OS**: Gentoo Linux

### Description

When hovering over a room in the room list under the tag "Rooms" it causes the whole timeline to expand to the left, which then resizes back to the original size once you stop hovering there.

### Steps to reproduce

- Make sure you have the timeline open
- Hover over any room under the "Rooms" tag
- Notice the timeline resizes

![output](https://user-images.githubusercontent.com/1565836/50524774-f23f6c80-0ad7-11e9-809c-d3ae11b9d2db.gif)

**Comment by lampholder** [comment]
I don't experience this on my ff 66.0a1 (2018-12-30) on mac fwiw

**Comment by jryans** [comment]
macOS tends to use overlay scrollbars, so I suspect we'll want to carefully check scrollbar behavior on each major desktop OS.

**Comment by PureTryOut** [comment]
This issue seems to have been fixed on https://riot.im/experimental. Can anyone with Linux confirm?

**Comment by AllienWorks** [comment]
I have the same issue on Firefox @ Manjaro Linux – [see preview](https://i.imgur.com/gp994Jm.mp4)

**Comment by tydog98** [comment]
Also have this issue with Firefox on Ubuntu

**Comment by AllienWorks** [comment]
I managed to fix this via manually resizing the sidebar in the end.

**Comment by bwindels** [comment]
Can indeed repro with a fresh login.
`mx_AutoHideScrollbar_overflow` and `mx_AutoHideScrollbar_underflow` toggle on the sublist on hover, but breakpoint in `AutoHideScrollbar::onOverflow/onUnderflow` does not trigger :thinking: ... must be some issue with ff devtools. For some reason ff seems to trigger overflow events on hover. Maybe we shouldn't rely on those at all, if possible?

**Comment by maciejhirsz** [comment]
Firefox 64 on Manjaro (Arch based), can also reproduce this.

**Comment by jaywink** [comment]
Can also see this behaviour with Firefox 65.0b12 (64-bit) on Ubuntu. Resizing fixes the issue as well.
