### ISSUE TITLE
Composer history doesn't persist between sessions anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7966]
1. Send a message
2. Use the arrow keys to see that the message is in the history
3. Refresh
4. Use the arrow keys and note that the message is missing from your history

**Comment by t3chguy** [comment]
Cannot repro on /app w/ Chrome

**Comment by lampholder** [comment]
Yeah, I can't repro this on ff on mac.

@turt2live - are you still seeing this? Any thoughts on how we can repro?

**Comment by turt2live** [comment]
I get this constantly on /develop and /experimental and the steps provided are 100% reproducible :(

**Comment by t3chguy** [comment]
Any chance your localStorage is knackered/full?

**Comment by turt2live** [comment]
Far from it, and I've logged out and back in several times. Unless the storage is so corrupted that it can't be deleted, I'm not sure how much I can help here.

**Comment by turt2live** [comment]
Nope, Chrome 71 and Windows 10.

**Comment by turt2live** [comment]
Fixed, magically.
