### ISSUE TITLE
Redesign, stickers: popup for stickers and background weirdness

### ISSUE THREAD

**Issue by AlexDaniel** [vector-im/riot-web#7971]
Firefox on linux, see the screenshot:

![screenshot](https://user-images.githubusercontent.com/5507503/50546253-46a83080-0c2d-11e9-9005-f606987d829a.png)

Opening another popup (e.g. by pressing ```…``` button on a message) brings up another popup that kinda conflicts with the stickers menu.

**Comment by lampholder** [comment]
Nice spot - this is indeed a regression introduced in the redesign.
