### ISSUE TITLE
Redesign, settings: mx_RoomHeader has no background but has a border

### ISSUE THREAD

**Issue by AlexDaniel** [vector-im/riot-web#7974]
Firefox on Linux

Normally, top of the settings page looks like this:

![screenshot](https://user-images.githubusercontent.com/5507503/50546360-545eb580-0c2f-11e9-8e4c-e04be6d662cf.png)

Notice the line that separates the “Settings” heading from the actual settings. If we scroll down, we will observe this bug:

![image](https://user-images.githubusercontent.com/5507503/50546414-7c4e1900-0c2f-11e9-8d3e-67b40cc8d1fc.png)

Notice how the line crosses the content.

This happens because the border is part of the `mx_RoomHeader` element, but `mx_RoomHeader` has no background. `mx_RoomHeader_wrapper` (which is inside `mx_RoomHeader`) has background, but it is a bit shorter vertically. So either move the border to the wrapper element, or give the upper element its own background.

**Comment by turt2live** [comment]
Fixed by replacing settings
