### ISSUE TITLE
"Cannot find homeserver" using riot-web

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/riot-web#7977]
Trying to join `#matrix:matrix.org` my home server (as far as I know that is a common problem for very large rooms), that's why I ask for help here.

### Description

Recently I noticed that I can not use https://riot.im/app/ with my homeserver accounts. The Web-App reports

> Cannot find homeserver

Using my homeserver with Riot-Destop/iOS/Android **works** just fine and even riot.im/app/ worked fine in the past.

### Steps to reproduce

1. I open https://riot.im/app/ -> log in
2. I provide my MXID `@user:yuhu.ddns.net` and password
3. I provide my homeserver under "Custom server": `https://yuhu.ddns.net:8448`

Riot-Web reports "Cannot find homeserver". The same is the case when I try, for example, https://matrix.bau-ha.us/#/home so it seems not to be related to a certain riot-web server.

Because using riot-web servers with my homeserver was no problem in the past I wonder if there was a recent change not accepting homeservers anymore that use port `8448` for client connection? I know it is reommended to use a Reverse Proxy but for some setups it is very useful to use port `8448` (in my case: running a homeserver really *at home* with only one public IP address via dynamic DNS and providing a data cloud service as well that already uses port `443`).

### Version information

- **Homeserver**: 

If not matrix.org: See "Steps to reproduce".

- **Version**: Synapse/0.33.9

- **Install method**: pip

- **Platform**: 

```
r4dh4l@vm-synapse:~$ uname -a
Linux vm-synapse 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
r4dh4l@vm-synapse:~$ cat /etc/debian_version 
9.6
```

The VM has 2GB RAM and one CPU.

I've already posted this in [Synapse issues tracker](https://github.com/matrix-org/synapse/issues/4320) and was redirected here.

**Comment by Half-Shot** [comment]
Hiya, I tested trying to log in (bogus credentials, but selecting your server) with your own instance of Riot (https://matrix.bau-ha.us/#/home) and it actually did fail to authenticate, which means it definitely found your homeserver. 

![image](https://user-images.githubusercontent.com/2072976/50572441-3628bf00-0dc1-11e9-88bb-92a5ee88ff41.png)

It's not possible this was just a networking issue?

**Comment by Half-Shot** [comment]
Okay, this time I tried the homeserver you gave in the report and it did the same as above:

![image](https://user-images.githubusercontent.com/2072976/50572464-99b2ec80-0dc1-11e9-8e95-427d8fa5c59e.png)

This could be an issue with your local connection / server? I seem to be able to connect fine :(

**Comment by uhoreg** [comment]
This is probably https://github.com/vector-im/riot-web/issues/7875

**Comment by lampholder** [comment]
Yep, pretty certain this is a dup of #7875.

We are actively looking for a solution to this - I'll close this issue so that there's one clear issue on which to track progress (but I'll make a note on 7875 that there's potentially some useful stuff on here)

**Comment by r4dh4l** [comment]
Thx all for your support!
