### ISSUE TITLE
Slack bridge not two way

### ISSUE THREAD

**Issue by cloudwheels** [vector-im/riot-web#7978]
### Description

Slack bridge not two way

### Steps to reproduce

Set up slack bridge to room. Messages (including simple text message) only go one way, from Matrix to Slack

Log: sent/not sent?  N/A  

### Version information

- **Platform**: web (in-browser) or desktop?
WEB
For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? CHROME

Google Chrome | 71.0.3578.94 (Official Build) beta (64-bit)
-- | --
Revision | 6da2ba233559398092dabd8dc7bc8e78cd758307-refs/branch-heads/3578@{#890}
Platform | 11151.59.0 (Official Build) beta-channel cyan
Firmware Version | Google_Cyan.7287.57.180
ARC | 5167872
JavaScript | V8 7.1.302.31

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
chromebook
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
 riot.im/app

**Comment by t3chguy** [comment]
Did you set up the outgoing webhook on the slack side?

**Comment by cloudwheels** [comment]
@t3chguy 
I've not located much in the way of documentation so if you have any pointers please?
I'm using the Event  bridge as this is recommended. Should I be using Webhook bridge instead?
Will try with Webhook but the Event option looks preferable.
Also, there's a small UI bug with my setup above that the webhook setup doesn't scroll properly.

**Comment by cloudwheels** [comment]
@t3chguy OK got it!
I had to just invite the bot to the channel - seems to work now, so will close this.
Docs seem to be lacking round here, not sure the instruction on the integration screen was clear enough first time round.
I won't add an issue for the above ui 'glitch' as the method is essentially deprecated and functionality not blocked (if you navigate by tabbing). I don't think anyone needs anymore work to do round here!
