### ISSUE TITLE
Inviting someone from the memberinfo results in an invite and an error

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7986]
The invite appears to go okay, but the error dialog is less than helpful:
![image](https://user-images.githubusercontent.com/1190097/50622598-9dcb3100-0ecb-11e9-9e2f-6cb61277b164.png)

**Comment by lampholder** [comment]
@turt2live can you provide any more details about what you did here? Do you mean inviting using the [Invite to this room+] button at the top of the memberlist panel?

**Comment by turt2live** [comment]
I clicked on someone's avatar then clicked "invite"

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/57573251-c4bae600-741c-11e9-9825-5595713ebf52.png)

My IDE found this one for me 👍

**Comment by jryans** [comment]
This is why we really need to be linting _all_ files... 😭
