### ISSUE TITLE
WebRTC ICE configuration?

### ISSUE THREAD

**Issue by zougloub** [vector-im/riot-web#7987]
### Description

In the browser (at least on Firefox) it's possible to configure default ICE STUN/TURN servers in the browser options so that video calls can work in all cases.
But I couldn't find a setting for the Android app and was wondering how it's handled in there... is there something (perhaps there's a setting for the web view, but I don't know, haven't looked)?
Also, a setting within Riot could be useful (or so I think).

### Version information

**Platforms** (which I used to check):
- Android app
  - Version: 0.8.21 (G-b161)
- Web app:
  - **OS**: Linux
  - **Version**: 0.17.8

**Comment by lampholder** [comment]
Riot's STUN/TURN servers are configured in the homeserver config - the client gets these details from the server on login. What are the firefox configuration options you mention?

**Comment by zougloub** [comment]
Thanks for the info. In my case since I control the home server it works. But I'm not sure free homeservers eg. matrix.org are providing TURN.
The Firefox option is `media.peerconnection.default_iceservers`.

**Comment by jryans** [comment]
The matrix.org HS does provide TURN for calls. The JS SDK also has a fallback STUN server in case the HS doesn't provide TURN.
