### ISSUE TITLE
Feedback about Riot's registration page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7988]
> Is there any good single page website for easily registering a matrix account? I guess Riot's registration page is fine but doesn't emphasize using a custom server as much as I'd like.

([source](https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$1546492358321IQGdC:raim.ist?via=matrix.org&via=half-shot.uk&via=disroot.org))

> The riot.im signup page doesnt fill a mobile device's viewport (and I'm using the experimental branch). Granted the page before tells you to download the app. But no one has time for that when I'm standing over their shoulder.

([source](https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15464931371468729iENUs:matrix.org?via=matrix.org&via=half-shot.uk&via=disroot.org))

**Comment by aaronraimist** [comment]
I've heard a lot of people say they send friends to Riot's registration page and tell them how to register using a custom server but they end up with a matrix.org account. Someone was asking a day or two ago for a guide with screenshots on how to register in Riot using a custom server, it probably shouldn't be that difficult.

**Comment by lampholder** [comment]
This has changed a lot since 3 Jan. Would be good to do some user testing though.
