### ISSUE TITLE
Room upgrades: both rooms appear in the room list

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7992]

**Comment by richvdh** [comment]
reloading riot fixes it, so I guess it's just a ui update issue

**Comment by jryans** [comment]
A [similar issue](https://github.com/vector-im/riot-ios/issues/2148) occurs for me on Riot iOS as well.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2433
