### ISSUE TITLE
Room upgrades: communities not updated

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7994]
tbh this is probably a server-side issue, but let's track it here for now

**Comment by lampholder** [comment]
Oh, you mean the community maintains a reference to the old room instance? I hadn't considered that :\

This is tricky, 'cause rooms and communities are not adminned by the same people. It might be preferable to advise community admins that they are linking to outdated rooms rather than do any magic autoreplace.

**Comment by turt2live** [comment]
> This is tricky, 'cause rooms and communities are not adminned by the same people. It might be preferable to advise community admins that they are linking to outdated rooms rather than do any magic autoreplace.

I'm struggling to think of a reason why the community would want to link to the old room outside of really edge case things.

**Comment by lampholder** [comment]
They almost certainly wouldn't - I'm just worried about the abuse case (which might be spurious - my understanding is sketchy) where somebody on a different homeserver writes a tombstone event telling the world that !old_good_room:homeserver.tld is now !new_evil_room:homeserver.tld and the good people of +good_rooms:homeserver.tld find that an evil room is part of their community...

**Comment by lampholder** [comment]
I discussed this with @turt2live - conclusion: whilst it is possible for a moderator to tombstone a good room to a bad new location, it is also possible for a moderator to do _anything_. A community admin adding a room to the community is an expression of trust in that rooms administrators - if the room turns evil (either via tombstone shenanigans or room admins booting out the goodies and inviting in the baddies) then its up to the community admin to spot this and remove the room from the community (just like a room admin polices the room members).

**Comment by lampholder** [comment]
So tl;dr yeah communities should _somehow_ update themselves. If this is as @richvdh says a server issue rather than a riot issue though perhaps we should track it there?

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/4897
