### ISSUE TITLE
Room upgrades: link to old room backpaginates for ages

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7997]
If you click on the 'Click here to see older messages' link, it takes you to the old room, which then back-paginates, apparently forever

**Comment by turt2live** [comment]
This is effectively the same as https://github.com/vector-im/riot-web/issues/5937 - there's no event tile rendered, so it just paginates forever.

Giving it a tile makes it happy again:
![image](https://user-images.githubusercontent.com/1190097/51000387-3116ee80-14ea-11e9-8c98-2b1c78c268fe.png)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2430

Using https://github.com/vector-im/riot-web/issues/5937 to track the underlying cause.
