### ISSUE TITLE
Room upgrades: should the new-room link take you to the top of the room?

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7998]
Currently the forward link restores the scroll state in the new room, or takes you to the end of the room. Would it make more sense to take you to the start of the room?

**Comment by lampholder** [comment]
Conceptually perhaps - it would 'feel right' that the end of one room joins on to the start of the next room.

Is this easy to do, or would we have to backpaginate our way through all of the messages in the new room?

**Comment by lampholder** [comment]
If this is easy to do (as I hope it is) then lets do it

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2432
