### ISSUE TITLE
E2E: Trigger cross-signing flow for logged in users

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8002]
We have wireframes and a separate issue (#7865) for cross-signing during the login flow, but existing users are already logged in to various devices, so they wouldn't see something like this that happens only during login.

We should work out how we want to trigger cross-signing for users who are already logged in. We could leverage the in-room reminder for key backup or take a different approach.

**Comment by uhoreg** [comment]
This seems to be done already
