### ISSUE TITLE
[Minor] Scrollbars on Windows are ugly

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8007]
They don't fit the theme at all
![image](https://user-images.githubusercontent.com/1190097/50661100-4a0a2780-0f5f-11e9-8e0b-dbf7b2fa7463.png)

**Comment by lampholder** [comment]
Is your issue with their colour, their form, or both?

**Comment by turt2live** [comment]
All of the above.

**Comment by AllienWorks** [comment]
Having similar issue on Firefox @ Manjaro Linux.

Moreover, for some reason, the Favorites section even glitches the whole layout on hover (sidebar gets narrower on hover on Favorites) – see [video preview](https://i.imgur.com/gp994Jm.mp4).

**Comment by turt2live** [comment]
@AllienWorks I think the issue you're seeing is different from this one. Please open a new issue using the "Redesign" template with the link to the video there.

**Comment by AllienWorks** [comment]
> @AllienWorks I think the issue you're seeing is different from this one. Please open a new issue using the "Redesign" template with the link to the video there.

Issue disappeared when I manually resized the sidebar width, so probably some leftover of my old settings from non-experimental Riot version. Not sure if another logged issue is needed then..?

**Comment by erikjohnston** [comment]
I have the same issue on linux on the room list. Everywhere else they use a different (and imo nicer) scrollbar style

**Comment by erikjohnston** [comment]
Some more insight:

1. It feels like the colours clash between the grey of the scrollbar and the light blue of the room list
2. This is often not a problem for other sites because the scrollbar is on the right side of the entire app and feels like part of the browser, rather than part of the app.


It also sounds like the idea is to move away from the current css fake scrollbar library and towards native scrollbars.

**Comment by bwindels** [comment]
with [native CSS scrollbars](https://drafts.csswg.org/css-scrollbars-1/) we can do better, like this:

![native-css-scrollbars](https://user-images.githubusercontent.com/274386/51484103-95f80180-1d92-11e9-9092-3767507a42c7.gif)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2470
