### ISSUE TITLE
Incorrect placement of room hover-over menu icon & unread messages counter

### ISSUE THREAD

**Issue by jerrykan** [vector-im/riot-web#8015]
The new version just push to /experimental appears to have a few issues with the list of rooms in the sidebar.

The menu dots that show up when hovering over a room are not right aligned:

![hover_menu](https://user-images.githubusercontent.com/377632/50668734-1be71f00-1015-11e9-8380-69ea073a0e7c.gif)

There is also (a related?) issues with the unread message counters as well:

![unread_marker](https://user-images.githubusercontent.com/377632/50668726-0f62c680-1015-11e9-9e5a-bf03180228f1.png)

**Riot Version:** 373c587ef8fb-react-46aa54393402-js-e8022e985e1f
**Browser:** Firefox 64.0
**OS:** Debian testing

**Comment by turt2live** [comment]
This is known, sorry :(  Working on a hotfix now.

Part 1 is here: https://github.com/matrix-org/matrix-react-sdk/pull/2402

**Comment by turt2live** [comment]
The primary issue here should be fixed, although there's some little other things we have our eye on. Thanks for catching it!

**Comment by jerrykan** [comment]
> This is known, sorry :( Working on a hotfix now.

No worries, it is "experimental" for a reason ;)
