### ISSUE TITLE
Redesign: Jump to unread button is hard to click

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8019]
The circular unread button in the redesign doesn't seem to be clickable across its entire visible surface... I seem to have to hover my cursor for a while to reveal the precise area that can be clicked, which doesn't feel great.

Ideally, the entire button would be clickable.

**Comment by jerrykan** [comment]
I've also noticed this problem.

### Version information
- **Platform**: web 
- **Browser**: Firefox v65.0
- **OS**: Linux (Debian testing)
- **URL**: riot.im/develop (674b8c3561ff-react-b19a1a018871-js-03a54353be98)
