### ISSUE TITLE
Nested quotes behave unexpectedly

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8020]
Quoting a message containing a quote places the caret after the first quote, and before the second one:

![quoting](https://user-images.githubusercontent.com/4626865/50699945-2b7c5d00-1041-11e9-8f3f-362a33e6fbd9.gif)

It's impossible to break out of the quote to write your message.

**Comment by nadonomy** [comment]
Removed the redesign label as this issue is also being exhibited on `/app`.

**Comment by nadonomy** [comment]
Adding the same labels as #7676 as it'd make sense to fix these issues at the same time.

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by yannicka** [comment]
I cannot reproduce the issue. I think the problem has been solved.

![Peek 21-05-2020 18-23](https://user-images.githubusercontent.com/22885898/82581014-35e4bb80-9b90-11ea-9df0-a93811a3dc4f.gif)

**Comment by nadonomy** [comment]
Looks that way! Closing.
