### ISSUE TITLE
Clearing a filter on the room list causes my tag sizing to change

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8023]
It might be a symptom of me being in a lot of rooms, but when I clear my filter my People and Favourites get smaller:

![room-filter-reset](https://user-images.githubusercontent.com/1190097/50704550-0245d780-1015-11e9-8660-105fea4ef8da.gif)

**Comment by jaywink** [comment]
Seeing this as well. Any filtering and then removing the filter resets any resize I've made to the room list sections which feels like a big usability issue as my favourites is usually expanded to maximum height and it collapses after filtering to show 1,5 rooms.

**Comment by Cadair** [comment]
This also seems to happen when filtering with communities as well.

**Comment by lampholder** [comment]
Right, I'm now _only_ seeing this on community filtering. Is anyone still seeing it on filter filtering?

**Comment by turt2live** [comment]
I can't reproduce this with plain searching

**Comment by jaywink** [comment]
Works ok for me too, for room filtering :+1: :heart:

**Comment by turt2live** [comment]
Goodbye letterboxes.
