### ISSUE TITLE
Display name changes trigger on blur

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8028]

**Comment by ara4n** [comment]
instead it should trigger on hitting a save button of some kind.

this is basically a matter or switching settings to be direct manipulation... except where that's going to be annoying, like this, and then provide a separate mini-save button.

**Comment by ara4n** [comment]
see https://github.com/vector-im/riot-web/issues/5476 and friends.

**Comment by turt2live** [comment]
Fixed
