### ISSUE TITLE
All-Emoji nicknames in pills become large if they are the only message content

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#8035]
### Description

All-Emoji nicknames in pills become large if they are the only message content:
![hard to swallow pill](https://user-images.githubusercontent.com/2803622/50744184-12320700-1221-11e9-85f3-7a3b29c29edb.PNG)

### Steps to reproduce

- have "big emoji" enabled in riot web
- post only a pill of a emoji only nick

normally pill looks like:
![normal pill](https://user-images.githubusercontent.com/2803622/50744190-2544d700-1221-11e9-8815-bebb866232c6.PNG)

Describe how what happens differs from what you expected.

Log: not sent    

### Version information

For the web app:

- **Browser**: Vivaldi 2.3.1401.7 (Official Build) (64-bit)
- **OS**: Windows 7 x64
- **URL**: riot.im/app

**Comment by lampholder** [comment]
Bleugh.

Should be an easy fix (he says, hopefully).
