### ISSUE TITLE
Ellipsis in room list is broken

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8037]

**Comment by turt2live** [comment]
Broken how? I fear this might have accidentally happened with the Great Merge last week.

**Comment by bwindels** [comment]
![image](https://user-images.githubusercontent.com/274386/50782482-0afe0e00-12a0-11e9-8617-59197f2262b4.png)

**Comment by turt2live** [comment]
ah, that might still be our fault. The RoomTile CSS changed a bit due to custom status being merged into experimental, and I think the flow layout of the tile got altered as part of that.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2410.

**Comment by bwindels** [comment]
thanks
