### ISSUE TITLE
Inconsistency in readme config and sample configs

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#8040]
The readme lists config option `integrations_widgets_urls` which is not present in the sample file `config.sample.json`. The sample config contains `integrations_jitsi_widget_url` which is not present in the readme config documentation.

Both are used in code, though it looks like neither is mandatory as a fallback is made to `integrations_rest_url`. The official Riot electron config has only `integrations_widgets_urls`.

Logging for cleanup or documentation enhancement, whichever is appropriate.

**Comment by lampholder** [comment]
Grim - we should fix this as soon as we get a chance (not sure when that will be)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8449
