### ISSUE TITLE
Clicking login/register from the homepage's banner doesn't stop the guest's MatrixClient

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8043]
as highlighted by the network request watcher:
![image](https://user-images.githubusercontent.com/1190097/50792883-b187e600-1283-11e9-8530-eca50bfbdc68.png)

(middle 3 are a .well-known discovery)

**Comment by lampholder** [comment]
You mean we end up with two active MatrixClients?

**Comment by turt2live** [comment]
No, just one at least during the login page. We are syncing from the login page though, which is wrong.

**Comment by turt2live** [comment]
This isn't an issue anymore, as it doesn't really apply to a problem.
