### ISSUE TITLE
E2E: Spam in console during key backup

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8047]
```
Could not find /(<device>(.*?)<\/device>|<device>|<device\s*\/>)/ in Backup has a <validity>valid</validity> signature from this device
rageshake.js:61 Could not find /(<verify>(.*?)<\/verify>|<verify>|<verify\s*\/>)/ in Backup has a <validity>valid</validity> signature from this device
```

**Comment by turt2live** [comment]
Those lines are repeated several times a second btw

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2412.

**Comment by turt2live** [comment]
During the key backup. Afterwards I visited the settings and saw similar behaviour, although not as frequently.

**Comment by jryans** [comment]
Hmm, okay, that's different from the behavior I have seen. Sounds like something is trigger lots of re-renders here.

**Comment by turt2live** [comment]
Might be the endless stream of events coming to my client. React might be trying to trigger rendering the settings somehow, causing it to be noisy

**Comment by jryans** [comment]
Alright, I'll add this to my queue of "too many re-renders" to come back to later.
