### ISSUE TITLE
"New Recovery Method" dialog should be dismissable

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8048]
![image](https://user-images.githubusercontent.com/1190097/50799578-d5562680-1299-11e9-84f8-113b1175e2b8.png)

As someone who started the backup knowingly, I don't care to go to settings or set up secure messaging. I just want to continue using my client.

**Comment by lampholder** [comment]
Was this on the same device you just set up recovery on, or a different one?

**Comment by turt2live** [comment]
A different one

**Comment by jryans** [comment]
For this specific issue, I'll enable the cancel button and have it re-check key backup status. That still leaves some related confusion that I filed as #8069.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2415 and https://github.com/matrix-org/matrix-js-sdk/pull/819.
