### ISSUE TITLE
Status doesn't disappear from the DM in the roomlist

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8051]
This morning Bruno changed his status (from "AFK" to "") - this was updated in the memberlist, but not the roomlist (until I moused over the DM entry in the roomlist).

**Comment by turt2live** [comment]
Were you hovering over the room list at the time?

**Comment by lampholder** [comment]
I couldn't tell you for certain, but I'd say probably not - I _think_ the AFK persisted for a little while of my generally using the app.

**Comment by turt2live** [comment]
Custom status isn't in the new room list
