### ISSUE TITLE
Custom Status UX snagging list (subjective)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8064]
Alright - reworking this issue to represent the smallest set of changes necessary to get this into a reasonable place.

- [ ] Status should be seen to change immediately upon clicking submit (i.e. not after switching rooms)
- [ ] The textbox border needs fixing on /experimental
     ![screenshot 2019-01-08 at 16 43 05](https://user-images.githubusercontent.com/1922197/50845334-7f01ea00-1364-11e9-8951-06db6a1fceaf.png)
- [ ] The 'X Clear Status' link should be red (i.e. active) when there's a status to clear, _not_ when there's text in the textbox.

### Stretch Goal
Now that we've had a little more time to think about this UX, we've come up with a slight reimagining:
- https://zpl.io/29oe4Rl
- Not captured in the zeplin - once you click on a button, the popup should stick around until you click off

Before fixing these issues in the current design, consider how much more effort it would be to implement the new design instead.

**Comment by lampholder** [comment]
- [ ] Padding is broken in /experimental
    ![screenshot 2019-01-08 at 16 43 05](https://user-images.githubusercontent.com/1922197/50845334-7f01ea00-1364-11e9-8951-06db6a1fceaf.png)

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/823 and https://github.com/matrix-org/matrix-react-sdk/pull/2442.

The new design from Zeplin has been implemented and all other snags resolved.

**Comment by lampholder** [comment]
I love the new impl, but I've realised that (since it takes a little while for the status to persist), we should really make an activity spinner appear adjacent to the button after you've told it to do something. Not critical that this is fixed now.

**Comment by lampholder** [comment]
/me files the above as a new issue
