### ISSUE TITLE
E2E: Key Backup snagging list

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8066]
- [x] 'Start a new backup' should probably indicate that it's a _process of regular backups_ that's being set up, not a one-off backup. (fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2416)
- [x] Escaping the 'Start a new backup' modal is peculiarly difficult - I only managed it by first pressing escape, _then_ clicking outside of the modal (fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2420)
- [x] Debounce the feedback text on the passphrase entry
- [x] Niggle: stop telling my passphrase doesn't match before I've obviously finished typing it in
- [ ] Niggle: could the 'go back and set it again' link be a backwards-directing button on the modal?
- [ ] Niggle: the 'backup version' is not something we'd expect everyday users to understand or care about - in the final impl could this be downplayed? 
- [x] "This device is uploading keys to this backup" (in user settings) sounds like it's in the process of doing it right now' so does "Your encryption keys are now being backed up to your Homeserver." (on the success dialogue after setting up backup) (fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2416)
- [x] It's too easy to to dismiss the key backup nag bar forever (and never again be reminded of something you really should do)
- [x] It looks like we set 'showRoomRecoveryReminder' to `false` if the user sets up backup (rather than to record a permanent dismissal of the reminder). (fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2420)
- [x] If you mash in a wrong key, the title of the modal is still 'Backup Restored'. And it gives you a total of the failures (rather than suggesting you check your password).
- [x] We should consider referring to the initial upload as an _initial_ upload to reinforce the idea that you'll keep backing up to this backup automatically (fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2416)

EDIT: Extracting "The Secure Message Recovery notif should say if you already have a backup in place (and that 'setup' means 'just verify the device that started the backup' in that case)" to a separate issue 'cause it unlocks our ability to turn this feature on by default for /develop and /experimental users

**Comment by jryans** [comment]
>  It looks like we set 'showRoomRecoveryReminder' to `false` if the user sets up backup (rather than to record a permanent dismissal of the reminder).

Do you have more detail about this one? In my testing, setting up the backup **does not** change `showRoomRecoveryReminder` to `false`. The intent of the current code is exactly as you describe: only opting out should cause this setting to change.

**Comment by lampholder** [comment]
Only niggles and the warning vs widgets issue remain, so I've pulled warning vs widgets out to a separate bug: https://github.com/vector-im/riot-web/issues/9078
