### ISSUE TITLE
"New Recovery Method" is confusing when devices are trusted but backup version has changed

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8069]
The "New Recovery Method" dialog can be confusing as currently written if your devices are all trusted but the backup version has changed (by stopping and restarting backup from device B without reloading device A).

It currently reads as:

![image](https://user-images.githubusercontent.com/1190097/50799578-d5562680-1299-11e9-84f8-113b1175e2b8.png)

The "Set up Secure Messages" button in this case wants to help you verify any unverified devices that might be blocking key backup. But in fact, that might not be the issue. You may just have seen an old key backup version, in which case an "Accept" button with dialog text specific to the situation would be all that's needed.

It may be hard to explain this case in a simple way in the dialog text.

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/8046

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2435.
