### ISSUE TITLE
We have a lot of listeners (at least that's what my console says)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8071]
```
(node) warning: possible EventEmitter memory leak detected. 501 listeners added. Use emitter.setMaxListeners() to increase limit.
consoleObj.(anonymous function) @ rageshake.js:61
events.js:146 console.trace
./node_modules/events/events.js.EventEmitter.addListener @ events.js:146
```

**Comment by lampholder** [comment]
Have you confirmed that this is only an /experimental thing?

**Comment by turt2live** [comment]
It started showing up in the last couple days on experimental. I would be surprised if develop or app had it

**Comment by bwindels** [comment]
I suspect this is due to multiple rooms being shown at once with the tiled ui? Let's see if this keeps happening with it reverted...

**Comment by turt2live** [comment]
Looks to be tiled UI related - closing.
