### ISSUE TITLE
Widgets interact badly with the tiled view

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8085]
![image](https://user-images.githubusercontent.com/1190097/50942308-687f8f80-1445-11e9-98ed-1b18ccb64568.png)

**Comment by lampholder** [comment]
I didn't see this - my widgets loaded correctly (though I wasn't able to type into the etherpad). I wasn't able to close opened widgets (or open closed ones) though.

**Comment by turt2live** [comment]
Sorry, the widget being blank is expected in this case (dev environment). I couldn't minimize it, and it pushed the buttons down too far.
