### ISSUE TITLE
Composer history doesn't work in the tiled view

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8086]

**Comment by bwindels** [comment]
For context, I [disabled it](https://github.com/matrix-org/matrix-react-sdk/commit/c8243357eac5509d6e920df0928450c939165d98) on purpose to avoid a bug, which is don't remember the specifics of.

**Comment by lampholder** [comment]
Labelling this unfairly as a `major` `bug` because we don't have labels for `fine-for-now-but-not-when-it-comes-out-of-labs` and `implementation-limitation`.

**Comment by lampholder** [comment]
Closing because tiled interface is not currently a thing
