### ISSUE TITLE
Fragment doesn't update in the tiled view

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8087]
None of my rooms are #riot-dev, yet the hash always says #riot-dev

**Comment by lampholder** [comment]
Whereabouts is this? Could you submit a screenshot?

**Comment by jryans** [comment]
I believe @turt2live means the room shown in the browser's URL bar does not match the room he is in.

**Comment by lampholder** [comment]
Closing because tiled view isn't a thing
