### ISSUE TITLE
Call preview appears while in room where call is happening

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8091]
This looks like to be `CallPreview` not being ported to `OpenRoomsStore`/`ActiveRoomObserver`.

**Comment by AmandineLP** [comment]
Heads up that the video call button didn't change into the hang up button too (it was working in the version I was using yesterday, so it might be linked to the same problem), so I can't hang up the call

**Comment by lampholder** [comment]
Both of these issues have been fixed by backing out tiled view.
