### ISSUE TITLE
Font rendering characters inconsistently on some OSes and looks like a ransom note

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8092]
Ubuntu Firefox:

![image](https://user-images.githubusercontent.com/1922197/50967083-023f4f00-14cf-11e9-864c-f100cbfbc27c.png)
![image](https://user-images.githubusercontent.com/1922197/50967085-053a3f80-14cf-11e9-9582-941efe112f37.png)

Isn't programming great and not at all annoying?

**Comment by nadonomy** [comment]
I suspect this is related to the rendering issues @turt2live is running into on Windows:

![](https://user-images.githubusercontent.com/1190097/50792138-37eef880-1281-11e9-97a7-9679e8cb5f8f.png)

He was able to narrow it down to specifically 12px text styles, along with some other stray .5px ones.

@lampholder from the same setup can you screengrab this link https://codepen.io/nadonomy/pen/YdjwjY?

For reference- here's how it should look on a sane setup (macOS, Safari):

<img width="287" alt="screenshot 2019-01-10 at 12 10 41" src="https://user-images.githubusercontent.com/4626865/50967773-079d9900-14d1-11e9-8197-867ba1a06151.png">

And how it looks on Windows:

![](https://matrix.org/_matrix/media/v1/download/t2l.io/054a53a92a2f2bb56a3afe71403f2afa)

**Comment by lampholder** [comment]
Here it is on ubuntu:

![image](https://user-images.githubusercontent.com/1922197/50967863-4f242500-14d1-11e9-9975-46befb7dbcec.png)

**Comment by nadonomy** [comment]
Cheers, super useful.

**Comment by nadonomy** [comment]
Now wondering if this might be related to the display being lower DPI, and whether we're just hitting yet more artefacts of Nunito being a display typeface.

**Comment by alicerunsonfedora** [comment]
It might be just Nunito itself. I occasionally run into this problem with the AliceOS documentation page.

**Comment by nadonomy** [comment]
Possibly related: https://teamtreehouse.com/community/issue-with-google-webfonts-rendering

**Comment by lampholder** [comment]
From a duplicate issue:

![image](https://user-images.githubusercontent.com/1922197/52131143-f8bf8780-2633-11e9-9dba-53863e0c7562.png)

**Comment by ara4n** [comment]
This is still biting people. ISTR that i dug into it at some point and discovered it was related to cleartype font hinting and whether Chrome was using GDI or its own font renderer? or something?

**Comment by ara4n** [comment]
@turt2live can you try disabling 'Accelerated 2D canvas' in chrome://flags?

**Comment by ara4n** [comment]
This looks suspiciously like https://stackoverflow.com/questions/27828423/google-font-letter-height-not-consistent.  @turt2live do you have a 'enable Direct Write' in flags? If so, can you try tha ttoo?

**Comment by ara4n** [comment]
This is also https://github.com/google/fonts/issues/632
