### ISSUE TITLE
1 notification that is always new when starting riot-web.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [vector-im/riot-web#8097]
I've read that event a bunch of times already, but it's still new whenever I start riot-web (doesn't happen on Riot Android on the same account).

**Comment by lampholder** [comment]
Are you able to submit logs to help us debug? (there's an option at the bottom of user settings)

**Comment by gerg5c42g542g2c54g52c** [comment]
I don't think so at this time. Unless I'm able to do this manually and there's not too much to redact.

**Comment by lampholder** [comment]
Closing because there's nowhere to start with this :(
