### ISSUE TITLE
Infinite loop of view_room dispatches when viewing a room you're not in

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8100]
Might be related: #8075 

1. Receive a message/permalink for a room you're not in
2. Click the permalink
3. Observe infinite spam in the console

This appears to be because the `OpenRoomsStore` has an outdated `RoomViewStore` for the active room, as it should be showing the target room, not the old room. This leads to it dispatching updates in a loop because none of the stores match the room ID attempting to be seen.

**Comment by turt2live** [comment]
Looks like it somehow causes a storm of `focus_composer` dispatches too?

**Comment by bwindels** [comment]
#8130 is a dupe

**Comment by turt2live** [comment]
For documentation purposes, the easiest way people have run into this is:

1. Upgrade a room
2. Click "The conversation continues here" *without* accepting the invite to the new room
3. Bad things happen

**Comment by lampholder** [comment]
This appears to have been fixed by backing out tiled view - closing.
