### ISSUE TITLE
Redesign: Settings header partially transparent

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8102]
The header in Settings doesn't seem to fully cover content as it scrolls by:

![settings-header](https://user-images.githubusercontent.com/279572/50998885-6f161180-14ee-11e9-82b2-ac8bdf38c205.gif)

- **Browser**: Firefox 66
- **OS**: macOS 10.14.2
- **URL**: riot.im/experimental

**Comment by turt2live** [comment]
Fixed
