### ISSUE TITLE
Changelogs are increasingly shown as forbidden

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8105]
<img width="399" alt="screenshot 2019-01-11 at 14 33 18" src="https://user-images.githubusercontent.com/1294269/51039866-1c039380-15ae-11e9-957f-b936e8b11575.png">

(also shamelessly using this bug to check on https://github.com/vector-im/riot-web/issues/2985)

**Comment by turt2live** [comment]
I suspect this is more people in the office trying to update :(

Maybe we could have a secret slash command for specifying a token?

**Comment by maxgrenderjones** [comment]
I _am_ on a widely used office IP, but I doubt it has crazily many Riot users (but I live in hope). I would however expect that the IP has a lot of general github traffic associated with it

**Comment by babolivier** [comment]
FTR, when this is happening, the browser's console usually tells you that GitHub forbid the request due to rate limiting on unauthenticated API calls (which have way lower threshold than the authenticated ones). I think serving the changelog ourselves would be a decent solution.

**Comment by ara4n** [comment]
fixed by matrix-org/matrix-react-sdk@ef78036a7
