### ISSUE TITLE
Redesign: "Show empty room list headings" feature

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8108]
Experimental currently has a setting for "Show empty room list headings" but there is no code that reads that value (removed in https://github.com/matrix-org/matrix-react-sdk/pull/2229).

Should we prune the setting (since it's odd to have setting that does nothing)? Is there a plan to restore the code that implements the setting?

(I already have local change that prunes the setting, so I can proceed with that if appropriate...)

**Comment by jryans** [comment]
The setting was [removed](https://github.com/matrix-org/matrix-react-sdk/commit/e08c70b82089299bbf736f92dafe6a8ec5daf773#diff-7343e79e45dd5943e6d8ef53ab1c231a) from experimental.

**Comment by lampholder** [comment]
👍
