### ISSUE TITLE
support Google auth for login  

### ISSUE THREAD

**Issue by sandys** [vector-im/riot-web#8113]
Please support Google Auth for login. This is both login using gmail account cloud.google.com/identity.

Google auth has support for 2FA and SAML and may be related to issues #2772 and #3544 .

From a compliance perspective, Google auth/login has all compliances built in and a lot of enterprises would need this, especially for chats that are sensitive from a regulatory perspective. 

Do note that we will need the option to make this login method mandatory - we would not want to give the option to login using any other mechanism (including password). Guest logins can still be passwordless (and should be exempt from this).

Value added features could be a check that only logins from a particular domain (e.g. @something.com ) be allowed in google auth.

**Comment by aaronraimist** [comment]
Related/duplicate: #4610

**Comment by lampholder** [comment]
Yeah, looks like a dup to me
