### ISSUE TITLE
Unable to send encrypted messages

### ISSUE THREAD

**Issue by deltabeard** [vector-im/riot-web#8115]
### Description

I have set up my own Synapse server. I am able to send and receive unencrypted messages. I am able to receive encrypted messages. I am however *unable* to send any encrypted messages from my server (deltabeard.com) to another server (matrix.org).

Riot.im simply shows "Your message was not sent." Attempting to resend does nothing.

### Steps to reproduce

- Start chat
- Enable encryption in the room
- Watch as you are unable to send any more messages.

Logs:
[console.log](https://github.com/vector-im/riot-web/files/2752517/console.log) Shows some errors regarding encryption.
[homeserver.log](https://github.com/vector-im/riot-web/files/2752518/homeserver.log)

deltabeard.com server, unable to send an encrypted message:
![2019-01-12-205242_1069x336_scrot](https://user-images.githubusercontent.com/3747104/51078620-15f5db80-16b0-11e9-9ae8-0db772349091.png)

Remote working server, not receiving any encrypted messages from deltabeard.com:
![knnrnihkamqltrgwqkrzrggw](https://user-images.githubusercontent.com/3747104/51078623-227a3400-16b0-11e9-85d1-6e80e85f961f.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 64.0.2 
- **OS**: Arch Linux
- **URL**: riot.im/app

### Server:
Synapse 0.34.1.1
Alpine Linux
Linux 2.6.32-042 (Standard for OpenVZ VPS)

**Comment by deltabeard** [comment]
Better screenshot showing how unencrypted messaged send and receive fine:

![2019-01-12-212940_1079x632_scrot](https://user-images.githubusercontent.com/3747104/51078681-383c2900-16b1-11e9-999b-d01482c5e361.png)

**Comment by moozer** [comment]
after upgrading to version 1.0.0 and 1.0.1 I get this exact problem also.

"your message was not sent" - that is pretty self-explanatory. It doesn't help me much in my debugging, though.

I'm seeing this using the ordinary matrix.org server. It worked before upgrading. 

I'm unable to find relevant log files to include here, or to give me ideas where to search. 

@deltabeard how to you make it save log files? and where?

**Comment by moozer** [comment]
I solved the problem by deleting old devices from the user - ones like old lost phone installations and so on. I deleted 17 of those dating to august 2018 from whenever I started using riot

My question about how to get logs, still stands though. I feel it will be handy at some point in the future :-)

**Comment by deltabeard** [comment]
Hi @moozer. The "console.log" file was what was in the "Console" tab in "Developer Tools" of Firefox, which can be opened by pressing F12. I simply copy and pasted the log into a text editor.

The homeserver.log I believe is a file in the "synapse" directory, which is the same directory the server configuration "homeserver.yaml" is in. I can't check it now because I deleted the server.

I'm hoping to deploy the latest version of synapse with a clean config, and see if I get this error.

**Comment by deltabeard** [comment]
I just fixed the issue. The /var/tmp/nginx directory was owned by nginx, but nginx was configured to run as user www. Fixing this issue allows me to send encrypted messages.
It's unclear whether this was bad default config on Alpine Linux or my own incompetence. Probably the latter.
