### ISSUE TITLE
PDFs no longer open reliably on Chrome

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8116]
Assume this is a regression caused by https://github.com/matrix-org/synapse/pull/4284 :/

**Comment by lampholder** [comment]
We thought we'd tested to verify that this wasn't the case, but obviously not.

Now as I understand it it's basically a trade off - if we want .pdfs to open on Chrome, we need to run the risk of firefox being vulnerable to running js code that's been uploaded to the media repo.

**Comment by lampholder** [comment]
We could look into mitigating this by setting the download content disposition on pdfs, perhaps from within Synapse, perhaps from Riot.

**Comment by jryans** [comment]
I guess another option would be to tailor the CSP based on browser UA, but I know that's pretty gross and frowned upon.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8605 (higher priority)
