### ISSUE TITLE
need to click twice on the member icon to display the member list

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#8128]
on experimental

**Comment by bwindels** [comment]
only happens when the memberlist is hidden

**Comment by bwindels** [comment]
cannot repro anymore, I suspect it was caused by the tiled UI.

**Comment by rkfg** [comment]
Still an issue in 1.0 for me. Updated today. When the user list is hidden I need to click the button twice for it to show up. This happens each time I switch to another room.
