### ISSUE TITLE
Custom status indicator border is not centered

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8134]
![image](https://user-images.githubusercontent.com/1190097/51200230-237cb280-18b6-11e9-9f13-5ea35dd41c74.png)

![image](https://user-images.githubusercontent.com/1190097/51200237-2aa3c080-18b6-11e9-9551-15e4a2647130.png)

Windows 10, Chrome 71.

**Comment by jryans** [comment]
Reproduced in Chrome on macOS as well.

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2446.
