### ISSUE TITLE
After rejoining a big room (#riot-ios:matrix.org), all kind of weird things happen

### ISSUE THREAD

**Issue by fridtjof** [vector-im/riot-web#8137]
### Description

As you can see in the first screenshot, out of the (currently) 932 users in that room (according to the badge in the repository's README), I can see 4. My client also thinks that I am actually the only person in that room (see the count above the avatar icon in the top right).

The client used is Riot (Web/Desktop) 0.17.8 on macOS 10.14.2.
My homeserver is das-labor.org, running synapse 0.34.1.1-py3. Federation in general works - the Synapse Admins room works fine, for example.

I have already cleared my cache multiple times, also due to issues with the room name being the standard "<user> and x others" without a logo. (https://github.com/vector-im/riot-ios/issues/1066)

In the second screenshot, it's turned into a one-to-one chat because someone joined after me. Also notice the read indicator for "A", who does not show up in the list to the right.

### Steps to reproduce

- Join #riot-ios:matrix.org

Expectation: Room shows up with the full member list, and a proper icon/title.

Log: sent    

![image](https://user-images.githubusercontent.com/2780577/51119817-1909dc80-1814-11e9-920a-1f84a82f10f5.png)

![image](https://user-images.githubusercontent.com/2780577/51121113-e57c8180-1816-11e9-834e-f51862ff6ac8.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS 10.14.2
- **Version**: 0.17.8

**Comment by ara4n** [comment]
thoughts from @aaronraimist:

<img width="1172" alt="Screenshot 2019-03-18 at 02 20 38" src="https://user-images.githubusercontent.com/1294269/54502820-75789d80-4924-11e9-9bb2-f986c7e58fb1.png">

**Comment by aaronraimist** [comment]
@ara4n people still seem to have trouble with `#riot-ios:matrix.org`. Do you think it can be upgraded soon?

**Comment by aaronraimist** [comment]
The room has finally been upgraded so hopefully this is better now.

**Comment by fridtjof** [comment]
Yup, everything works as it should now! :)

**Comment by aaronraimist** [comment]
@fridtjof Great! You can close this issue then.
