### ISSUE TITLE
E2E: Key backup: Backup is not signed by any of your devices (when it is)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8142]
Two parts to this:

1. The message isn't helpful. Any backup will _always_ have been signed by a device at some point. What we mean is that it hasn't been signed by a currently-logged in device, so there's no action you can take to establish trust in this backup other than by decrypting it with the key you've (hopefully) kept somewhere safe.

2. The message is appearing when it isn't true. Steps I took:
    1. Log in to an account (with an existing back up) on two machines (which have not verified each other)
    1. On machine A, delete the existing backup 
    1. On machine A, create a new backup
    1. Verify that machine A is saying true things about the state of the backup in settings (it is)
    1. Go to machine B
    1. Go to an encrypted room
    1. See the 'Secure Message Recovery' message with the (incorrect) message "If you log out or use anohter device, you'll lose your secure message history. To prevent this, set up Secure Message Recovery"
    1. Click 'Set up' - it initiates the secure message recovery setup wizard as if from scratch
    1. Back out of that and check what backup state is being reported in settings
    1. Discover that machine B is saying that "Backup is not signed by any of your devices" (but it is)

**Comment by lampholder** [comment]
I hate what I've done with this bug report, inasmuch as there's likely two or maybe three different issues rattling around in here. It probably makes sense to fix them all in one go, though.

**Comment by dbkr** [comment]
Have fixed the error message in above PR: I can't repro the misbehaviour though. If you're able to repro it again can you include console logs / rageshake from machine B after step 'x'?

**Comment by lampholder** [comment]
Ignore this until I claim to have seen it again :)

**Comment by lampholder** [comment]
I suspect most or all of this is resolved by the steps we took to make key backup information less stale generally.
