### ISSUE TITLE
E2E: Backup: the recovery dialog does not warn on wrong passphrase

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#8143]
or on wrong recovery key.

It displays this success dialog instead:
<img width="561" alt="screenshot 2019-01-16 at 14 44 31" src="https://user-images.githubusercontent.com/8418515/51253115-c65c2c00-199d-11e9-8722-5f4b93aad8aa.png">

This has been discussed at https://matrix.to/#/!uewiilduiDRfPomIha:matrix.org/$1547645507171128xJuGy:matrix.org?via=matrix.org&via=sandbox.modular.im&via=ponies.im

iOS mitigates this with https://github.com/matrix-org/matrix-ios-sdk/pull/619/files#diff-29268acd3adb54172cd5d3d1ba563b23R795.

**Comment by lampholder** [comment]
We should definitely fix this.

Fix probably means:

If none of the sessions could decrypt, say 'Backup Failed' and prompt the user to check their passphrase/key and try again.

If _some_ of the sessions failed (is this possible?) then we should show a different message - perhaps 'Backup Partially Restored' as the title, with an explanation of how to remedy the situation (if it is possible achieve a partial restore, _is_ it possible to do anything to fix?)

**Comment by lampholder** [comment]
Decrypting only _some_ of the keys is _technically_ possible, but only with buggy clients/manually messing with the API
