### ISSUE TITLE
Room list filtering feels broken when room list sections are collapsed

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8145]
If a room list section is collapsed, its state persists when filtering. Although this is technically correct— I find I often use 'filter' for 'search'. At least a couple of times a day I 'search' for a room and it's missing from the list; making me think either Riot or my brain is broken. Should we not arrange rooms into sections at all when looking at filter results?

**Comment by lampholder** [comment]
I wish I could add 100000 👍 to this - the number of times I've not found a room I'm searching for beacuse its section is collapsed 🤦‍♀️

**Comment by turt2live** [comment]
We fixed this :D
