### ISSUE TITLE
matrix.to permalinks don't work for self-hosted instance

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/riot-web#8149]
### Description

Since https://github.com/vector-im/riot-web/commit/9b8e127e23689243dc4f95980fafbe0cfbc9f1ca, share buttons link to matrix.to. However, for self-hosted instances that don't communicate with riot.im, this makes the shared links useless as users cannot connect with them. It may even be considered a security risk, because users may try to log in on one of the links shown at matrix.to, leaking their credentials for the private instance.

### Steps to reproduce

- Click share in a self-hosted Riot-web connected to a self-hosted Matrix
- Notice the link is formatted like https://matrix.to/#/!usfAvrMVqltHkpWfgW:example.com?via=example.com
- Send the matrix.to link to someone
- Notice that they can never join with any of the options because they link to Riot.im, which our server doesn't federate with

Describe how what happens differs from what you expected.

The link should, well, work. And the old link before this change would work on self-hosted instances.

Log: not sent

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox 64.0.2
- **OS**: macOS
- **URL**: Riot-web 0.17.8

**Comment by jryans** [comment]
Note that if you paste the matrix.to link in a Matrix room and the receiver clicks it in Riot, then their Riot **should** just navigate to the room, rather than displaying the client chooser UI.

**Comment by turt2live** [comment]
Also you can type `/goto https://matrix.to/...` and it'll work

**Comment by TheLastProject** [comment]
Sure, in those situations it works, but it doesn't in other situations, such as people sharing a link to a colleague over email, because matrix.to itself will point to the wrong location. Especially for non-technical users this behaviour is very confusing.
