### ISSUE TITLE
"There is a known vulnerability affecting this room" warning presented erroneously on room upgrade. 

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#8154]
In rooms that are not version 1 room admins are presented with a security warning. This happens even when the room version is valid, so rooms on version 2 erroneously have this warning.

This is misleading, but also takes up valuable screen real estate. 

<img width="745" alt="screenshot 2019-01-17 at 17 27 40" src="https://user-images.githubusercontent.com/451032/51336738-368daf00-1a7d-11e9-9c26-921217c0145f.png">

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/828 on experimental

**Comment by neilisfragile** [comment]
\o/
