### ISSUE TITLE
very long unbroken text in the composer breaks the layout

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8157]

**Comment by ara4n** [comment]
![image](https://user-images.githubusercontent.com/1294269/51356936-6c9a5580-1ab4-11e9-8db2-0f0b24d63b3a.png)

**Comment by yannicka** [comment]
![Peek 17-07-2020 15-58](https://user-images.githubusercontent.com/22885898/87794015-53f43280-c846-11ea-9ea4-182a235e95a5.gif)

I can't break the layout (on Element Desktop 1.7.1). Do you still have the issue?

**Comment by t3chguy** [comment]
We have a new composer since then
