### ISSUE TITLE
Low priorty room list does not shrink or scroll

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#8160]
- **Browser**: Firefox 64.0 
- **OS**: unbuntu

### Description

Scrolling or resizing left hand side room list stops working for "Low Priority" section, it takes up exactly the space for the rooms inside it, no more no less. 

### Steps to reproduce

My "Low Priority" room list is not compressed and i can't resize, reduce it's height or scroll it. This persists over force-refreshing the webpage.

Log: sent

**Comment by michaelkaye** [comment]
![screenshot from 2019-01-18 12-01-08](https://user-images.githubusercontent.com/1917473/51386073-190e2300-1b19-11e9-9086-01f575344b45.png)
(dragging or moving the thin line above "Low Priority" does not allow it to go down, only up (but up is limited by the sections above not allowing themselves to shrink - there's a few pixels of wiggle at most.

**Comment by michaelkaye** [comment]
Interestingly, as soon as i left a room that i was in, i gained a Historical section at the bottom (that hadn't been there before) and the room list managed to scroll and resize properly again.

If i had to debug, i'd say "if there's no historical rooms, then it doesn't work"

**Comment by lampholder** [comment]
Yeah, the bottom section (whatever it is) in the room list struggles a bit. We are considering our options on how to fix this :)
