### ISSUE TITLE
bings in an upgraded room are hard to find

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#8161]
### Description

I got a bing in a room that was upgraded after the bing.  The Riot favicon shows a (1) to indicate the bing, but since the room was upgraded, the room that I was binged in does not appear in the room list, so I couldn't figure out where the bing was coming from until I opened the notifications panel.

It's good that the old room is no longer visible in the room list in general, but maybe if the room has a bing in it, it should still show up.

### Steps to reproduce

- get binged
- get the room upgraded
- get confused

Describe how what happens differs from what you expected.

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 60.4.0esr
- **OS**: Debian
- **URL**: riot.im/experimental

**Comment by turt2live** [comment]
This might also require server-side magic to send the badge counts or something. We'd also need to communicate to the user that the bing is in the old room
