### ISSUE TITLE
Some broken images on experimental

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8164]
![2019-01-18 at 14 45](https://user-images.githubusercontent.com/279572/51412034-d3a92000-1b2f-11e9-8b6f-48ce8ea5c0c2.png)

After image URL changes in #7932, some paths seem not quite right.

**Comment by f0x52** [comment]
Same problem here
![image](https://user-images.githubusercontent.com/23422690/51413528-91073800-1b6f-11e9-9812-a7b504035a63.png)

**Comment by jryans** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/8165.

Thanks everyone for the reports! If you see any others, please file a new issue.
