### ISSUE TITLE
Past messages from multiple days prior appear among most recent messages

### ISSUE THREAD

**Issue by tiffanytkn** [vector-im/riot-web#8172]
- **Browser**: Firefox 64.0 64-bit
- **OS**: Xubuntu 18.04.1 LTS

### Description

As I scrolled up to read past messages in a room, the timeline of messages was disrupted by messages from previous days. More specifically, I was reading messages from Friday, and then messages from Tuesday were inserted in the chronology of messages. However, only a few messages or a single message at a time. Essentially, messages were displayed out of order and the out-of-order messages were from 3-4 days ago.

![screenshot_2019-01-19_00-07-42](https://user-images.githubusercontent.com/42646958/51423475-51981600-1b86-11e9-9a03-b8414d34b6a7.png)

![screenshot_2019-01-19_00-05-37](https://user-images.githubusercontent.com/42646958/51423478-54930680-1b86-11e9-8fff-163fb104c666.png)

I tried to reproduce this in other rooms and individual chats, but I wasn't able to. Even when I refreshed my page, the messages from Tuesday were shown inserted between the most recent messages, as shown below. Out of place message is highlighted.

![screenshot_2019-01-19_01-19-20](https://user-images.githubusercontent.com/42646958/51423614-92912a00-1b88-11e9-9092-e22e8902ee55.png)

### Steps to reproduce

- Scroll back through multiple days' worth of messages in room?

While scrolling back, I expected my messages to be displayed in order but instead, messages from previous days appeared inserted between my most recent messages. Possibly related to Issue #6780?

Debug log sent.

**Comment by lampholder** [comment]
If you clear cache and refresh do the messages come back in order?

**Comment by tiffanytkn** [comment]
> If you clear cache and refresh do the messages come back in order?

Yes, I cleared the cache on Riot Android, and the messages appeared in order on the web interface as well as on the Riot Android app.

**Comment by lampholder** [comment]
This sounds like a dup of https://github.com/vector-im/riot-web/issues/6780 - we could probably do a better job highlighting messages that have appeared out of order, but there's no way to guarantee against them. I'm going to close this issue

**Comment by jivanpal** [comment]
Doesn't #6780 concern the order in which the homeserver has received events (which unavoidably has the potential to happen out of order, as mentioned in that issue thread), whereas this issue concerns the client receiving them out of order? Why is this issue able to be resolved by clearing the cache, and why is clearing the cache necessary, rather than the client being able to sort out such messes without any user intervention? Or have I misunderstood one/both issue statement(s)?
