### ISSUE TITLE
when a new message arrives there is a lag between the notif badge appearing in the room list and the room name changing colour

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#8186]
about 1s

**Comment by bwindels** [comment]
it might be a debouncing in the roomliststore to not run the (potentially slow) sorting all of the time.

**Comment by lampholder** [comment]
Probably related to/the same as: https://github.com/vector-im/riot-web/issues/8184

**Comment by bwindels** [comment]
this should be fixed, please reopen if still an issue.
