### ISSUE TITLE
sign-up: selection of server type on two lines

### ISSUE THREAD

**Issue by sblondon** [vector-im/riot-web#8190]
In the electron app, the login form displays 2 choices of servers.

The choice between default server and custom server can be displayed in two lines if the translation is too long. It decreases the readability of the choices. It occurs on several languages: catalan, german, euskadi, french, galician, italian, latvian, hungarian, poland, greek, Български, српски.

![riot_server_selector](https://user-images.githubusercontent.com/1708780/51485135-a1045f00-1d9d-11e9-8cb7-f64e75e3d2bd.png)
Tested on desktop, Debian testing with 
```
Package: riot-web
Version: 0.17.8
```

**Comment by jryans** [comment]
Yes, I think we can call this fixed on experimental and coming soon. It's possible there are other i18n issue with the new layout, so please file those if they come up.
