### ISSUE TITLE
Right panel direct chat room avatars don't align with start chat button

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#8191]
![screenshot from 2019-01-21 17-03-56](https://user-images.githubusercontent.com/8428120/51488944-cc3b7e00-1d9e-11e9-8148-b7df827166cb.png)

I'm assuming the start chat image should align with the avatars above, and "start chat" should be on the same line

**Comment by yannicka** [comment]
The "+" button seems to have been moved to the top right.

![image](https://user-images.githubusercontent.com/22885898/82262968-36980a80-9962-11ea-9fd8-f91b8fbc47c2.png)

So I guess the problem is no longer relevant?

**Comment by t3chguy** [comment]
That is the left panel @yannicka 
but yes the list of direct chats has gone away in anticipation of Canonical DMs
