### ISSUE TITLE
Redesign: Single-line room topic does not line up with room name

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8193]
- **Browser**: Chrome 
- **OS**: Debian Linux

### Description

![image](https://user-images.githubusercontent.com/1342360/51491424-3a377380-1da6-11e9-9d2d-cb1865dee1fb.png)

### Steps to reproduce

- Make a room with a short topic
- Notice it does not vertically line up with the room name

Multi-line room topics look alright however.

![image](https://user-images.githubusercontent.com/1342360/51491488-64893100-1da6-11e9-8592-e02327d1315f.png)

**Comment by yannicka** [comment]
Do you still have the problem?

For my part, it looks like this (aligned):
![image](https://user-images.githubusercontent.com/22885898/82262754-cab5a200-9961-11ea-8f43-499ef01d0fca.png)

**Comment by t3chguy** [comment]
Looks to be center aligned whereas baseline aligned might be more correct

**Comment by anoadragon453** [comment]
Yeah, looks fine now.
