### ISSUE TITLE
Room list filter and member list filter have different text colors

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8194]
<img width="205" alt="2019-01-21 at 13 54" src="https://user-images.githubusercontent.com/279572/51496064-1bc08080-1d84-11e9-86a5-0b4a6d60202d.png">

<img width="243" alt="2019-01-21 at 13 54" src="https://user-images.githubusercontent.com/279572/51496077-24b15200-1d84-11e9-8c4f-1c5d9307f6bb.png">

Member list filter text color is harder to read, so maybe it should switch to be the same as room list filter text color?

**Comment by nadonomy** [comment]
Not sure what's happening here exactly (FF specific bug?), the text should match the icon and does so in Safari:

<img width="280" alt="screenshot 2019-01-21 at 20 04 22" src="https://user-images.githubusercontent.com/4626865/51496488-429ca800-1dc0-11e9-85cf-d4b1711457fd.png">

And yep; the filter members text should match filter room names (as per the first bullet in #8182).

**Comment by jryans** [comment]
> Not sure what's happening here exactly (FF specific bug?), the text should match the icon and does so in Safari:
> 
> <img alt="screenshot 2019-01-21 at 20 04 22" width="280" src="https://user-images.githubusercontent.com/4626865/51496488-429ca800-1dc0-11e9-85cf-d4b1711457fd.png">

Moved this Firefox specific bit to #8195.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/12630

**Comment by t3chguy** [comment]
This seems to be resolved
![image](https://user-images.githubusercontent.com/2403652/79056907-3f0a7080-7c53-11ea-8767-f75c71cfd746.png)
![image](https://user-images.githubusercontent.com/2403652/79056911-416cca80-7c53-11ea-8b55-ea7c020d4ab9.png)
![image](https://user-images.githubusercontent.com/2403652/79056914-4f225000-7c53-11ea-8ec1-5ae00fa23d44.png)
![image](https://user-images.githubusercontent.com/2403652/79056915-521d4080-7c53-11ea-8acd-aff99e4a21c5.png)
