### ISSUE TITLE
The LLP can be scrolled even when there's very few icons

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8197]
![scrolling-llp](https://user-images.githubusercontent.com/1190097/51499292-f2552400-1d86-11e9-95f4-9163561a28c4.gif)

**Comment by turt2live** [comment]
more obvious in the dark theme: https://github.com/vector-im/riot-web/issues/8592

**Comment by aaronraimist** [comment]
Is this still reproducable?

**Comment by t3chguy** [comment]
Re-open if you can reproduce
