### ISSUE TITLE
Double clicking a message with italics only selects one part of the line, not the whole line

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8210]
Firefox 64 on Fedora 29

![shear-select](https://user-images.githubusercontent.com/274386/51528383-71e9fe00-1e2e-11e9-89d1-3de12235e361.gif)

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it on Firefox 78 (on Ubuntu 20.04).

**Comment by t3chguy** [comment]
Nor I
