### ISSUE TITLE
m.notice messages are formatted differently

### ISSUE THREAD

**Issue by xoxys** [vector-im/riot-web#8212]
### Description
Some messages send from a CI-Bot sended with gomatrix are formatted differently in riot-web

![image](https://user-images.githubusercontent.com/3391958/51531003-8cc36f00-1e3c-11e9-8864-752a7550d51b.png)
```
"content": {
    "body": "Status: **success**<br/> Build: by success",
    "msgtype": "m.notice",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>Status: <strong>success</strong><br/> Build: by success</p>\n"
  },
```

![image](https://user-images.githubusercontent.com/3391958/51531028-9b118b00-1e3c-11e9-854b-5ac2b1cd9472.png)
```
"content": {
    "body": "Status: **success**<br/> Build: by xoxys",
    "msgtype": "m.notice",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>Status: <strong>success</strong><br/> Build: by xoxys</p>\n"
  },
```

I can't notice any difference between both messages, but one is displayed in red and the other in black/grey. Why happens this?

### Version information
- **OS**: macOS/Linux
- **Version**: 0.17.8

**Comment by turt2live** [comment]
The second one mentions your name and so riot pings you. The red highlight indicates this.

There's a setting for "notifications from bots" in your user settings - this controls the behaviour you're seeing here.

**Comment by xoxys** [comment]
And there is no indicator required? Something like @username? Only my username in a random Text?

**Comment by turt2live** [comment]
Yes, until the spec supports better forms of mentions, unfortunately.

**Comment by xoxys** [comment]
But this does not happen in riot-android :) i know, different project but i think riot Clients should nearly work the same. Anyway, thanks for you reply.

**Comment by turt2live** [comment]
They should absolutely be the same in this case. What does riot say your current setting is?

**Comment by xoxys** [comment]
Bot message notifications are "on" (not "loud")

**Comment by xoxys** [comment]
And "Messages containing my username is set to " loud" on android but this does not change the message color

**Comment by turt2live** [comment]
I think that's a riot-android bug then. It should be rendering it similar to riot-web.

**Comment by lampholder** [comment]
Filed with Android: https://github.com/vector-im/riot-android/issues/2958
