### ISSUE TITLE
Sometimes Riot will say a backup was created by an unknown device when it looks like the device should be known.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8213]
https://github.com/matrix-org/riot-web-rageshakes/issues/1174

![image](https://user-images.githubusercontent.com/1922197/51535266-df525a80-1e3f-11e9-895d-efc6beeef935.png)

**Comment by lampholder** [comment]
I'll try and get some solid repro steps for this, if I can't we can still look at the code/add some logging to see what's going on.

**Comment by lampholder** [comment]
Well, I'm seeing it again. And the (extra) problem with it is that when key backup is in this state, you also get the wrong SMR warning when you go to an encrypted room, which invites you to click 'set up' and create a totally new backup

**Comment by lampholder** [comment]
Right, this time I:
- set up backup on device with ID UNMBGNLXWU
- looked at key backup settings on a different device
- the settings told me 'Backup has a signature from **unknown** device with ID UNWBGNLXWU'
- console logs told me 'Ignoring signature from unknown key ed25519:UNWBGNLXWU'

**Comment by lampholder** [comment]
@ara4n has offered to take a look at this.

**Comment by lampholder** [comment]
> console logs told me 'Ignoring signature from unknown key ed25519:UNWBGNLXWU'

This is a red herring - you get this whenever your backup has been signed by a device you haven't verified.

**Comment by lampholder** [comment]
Okay, I now know some things. The appearance of this issue is dependent upon the information stored in your indexeddb `device_data` table.

When you log in from a fresh client, this table contains a json object with a reference to _just your new device_. Certain things will trigger its being poplated with a full list of your devices:
- look at the memberinfo for your own account
- try and send a message in an encrypted room (you'll get the 'unknown devices present' notif, it doesn't matter how you respond to this)

Empirically, just logging in on a new device _does not_ prompt your other devices to refresh their list of your devices stored in `device_data`.

The problem is, the key backup UX appears to be assuming that `device_data` has fresh device information, but it doesn't.

**Comment by lampholder** [comment]
Dave is 95% confident that adding a new device is supposed to trigger a poke to your existing devices prompting them to update their local `device_data` with your new device information.

As I said above, this isn't happening. If it were happening in the past, it could have been broken for ages without our noticing - prior to key backup, you only _needed_ a fresh list of your devices before sending an encrypted message, and however it's happening `device_data` _is_ being refreshed before that.

The upshot of this is if you create two devices, set up key backup on one and then try to use that backup on the second, your second device will say the backup is signed by an 'unknown' device.

You can force `device_data` to be refreshed by:
- trying to send a message in an encrypted room, or
- looking at your own memberinfo

The table of devices is populated by a call to /devices, so it contains fresh information.

**Comment by dbkr** [comment]
This ^ was almost certainly the cause of this bug
