### ISSUE TITLE
Riot 0.17.9 stuck on white screen

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#8217]
### Description

After updating to Riot 0.17.9 on ArchLinux, the window stay white upon opening.
In the console, only this is printed:
```
Attempting to migrate data between origins
Loading path: /usr/lib/riot/origin_migrator/source.html
```

Deleting the data folder does not change the white screen issue (but obviously remove the “migration” line).

### Steps to reproduce

- Launch Riot 0.17.9.

Log: n/a

Screenshot: just a plain white window.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.17.9

**Comment by dbkr** [comment]
How are you installing the desktop app on Arch? eg. building from the source or using one of the Arch packages?

**Comment by ArchangeGabriel** [comment]
Building the Arch package from the source (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/riot).

**Comment by dbkr** [comment]
Aaha - I think your package will now need to copy over the `origin_migrator` directory. It's probably trying to open this to migrate the data and failing.

**Comment by ArchangeGabriel** [comment]
Of course… :man_facepalming: That did it, thanks! :)

**Comment by geosword** [comment]
Same problem here with Ubuntu 18.3 , installing from the repo. I assumed "It's probably trying to open this to migrate the data and failing." meant it was a permissions problem, but after adjusting the permissions to allow my user to access it, I've also tried re-installing, nothing changes. What do I need to do to get this back up and running?

Thanks in advance.

**Comment by Esux** [comment]
> Same problem here with Ubuntu 18.3 , installing from the repo. I assumed "It's probably trying to open this to migrate the data and failing." meant it was a permissions problem, but after adjusting the permissions to allow my user to access it, I've also tried re-installing, nothing changes. What do I need to do to get this back up and running?
> 
> Thanks in advance.

I realize you probably don't need this information any more, but as this is the top google result when googling about the issue maybe someone else would find it useful. Download the source if you haven't already. Extract it somewhere. Open a terminal where the 'origin_migrator' folder is.

> sudo cp -r origin_migrator/ /usr/lib/riot/
