### ISSUE TITLE
Redesign: Integration server error hidden under right side bar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8218]
- **Browser**: Chrom
- **OS**: Debian Linux

### Description

![image](https://user-images.githubusercontent.com/1342360/51542816-074bb900-1e54-11e9-8fbf-be033946599d.png)

The integrations error is hidden under the right sidebar.

### Steps to reproduce

- Break your integrations server
- Look to see the helpful warning message
- Be unable to read it :(((

Here is what it should look like:

![image](https://user-images.githubusercontent.com/1342360/51542876-2d715900-1e54-11e9-9443-78a37d612bb7.png)

Also the message looks like it could use some padding, and some more width.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2482
