### ISSUE TITLE
Make registration fields respond to available registration flows from the HS

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8219]
We're making a change to make support for registration by phone number configurable on the HS.

Riot should detect the avialable registration flows and update its UX accordingly - i.e. if there are no registration flows for msisdn (phone number) it should not show the phone number field.

It should update live, so if the user choses another homeserver/switches to anohter homeserver using .well-known, the registraiton UX should update. Ideally we should find a way for this not to be visually too jarring.

This doesn't affect login, which should stay the same. It also doesn't stop users from associating their account with a phone number later on in user settings.

**Comment by turt2live** [comment]
> This doesn't affect login, which should stay the same. 

We should also be responsive to the login flows on login while we're at it, imo. Assuming we aren't already.

**Comment by jryans** [comment]
Fixed the registration flow in https://github.com/matrix-org/matrix-react-sdk/pull/2551.

For login, it sounds like we'll need something else, and so we should probably file a separate issue to track it.
