### ISSUE TITLE
Links opening in desktop app frame

### ISSUE THREAD

**Issue by yanlinaung30** [vector-im/riot-web#8226]
### Description
URL is opening in RIOT and cannot return to homepage.

### Steps to reproduce
- I clicked a url on pop up menu in Riot.
- It is opening in Riot and cannot return to home screen
- There is no button to click.

Describe how what happens differs from what you expected.

Log: sent/not sent?    

![image](https://user-images.githubusercontent.com/4996766/51581274-c3a98b80-1ef5-11e9-9660-86340c402024.png)

### Version information

- **Platform**: desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows
- **Version**: 10

**Comment by turt2live** [comment]
> I clicked a url on pop up menu in Riot.

Was this a link in a message or somewhere else?

**Comment by dbkr** [comment]
Thanks for the bug report.

Issues here are twofold:

 1. We have a couple of links like this in the app which should have a `target="_blank"` on them, but don't (they'll navigate away from riot in the browser too)
 2. v0.17.9 enables sandbox mode in electron, and this bug: https://github.com/electron/electron/issues/8841
