### ISSUE TITLE
After upgrading to 0.17.9 can't connect to any homeserver (proxy setting trouble) with new Electron setup

### ISSUE THREAD

**Issue by szimszon** [vector-im/riot-web#8229]
### Description

After the upgrade from 0.17.8 to 0.17.9 we are not able to connect to homeserver (I see a magenta banner with Unable to connect to Homeserver. Retrying...). If I do nothing just start the 0.17.8 everything is fine.

### Steps to reproduce

- Upgrade from 0.17.8 to 0.17.9

![kep](https://user-images.githubusercontent.com/745542/51594026-d7ec8900-1ef3-11e9-9caf-592d053d6559.png)

### Version information

For the desktop app:

- **OS**: Windows10 with corporate squid proxy
- **Version**: 0.17.9

**Comment by szimszon** [comment]
Okay I checked from another network without the proxy and everything is fine.
So it seems to me that the windows proxy settings and/or network proxy settings (http://wpad/wpad.dat) are not honored ;(

**Comment by t3chguy** [comment]
If you want to specify a proxy see https://github.com/vector-im/riot-web/issues/3320#issuecomment-318668688

**Comment by szimszon** [comment]
I know there are possibilities to do so ('--proxy-pac-url=' https://electronjs.org/docs/api/chrome-command-line-switches). All I say is it was working out of the box on ver. 0.17.8 and still works. To tinker with commandline parameters is not an option for us sorry.

**Comment by szimszon** [comment]
I checked in the meantime and I'm not able to connect to the server even if I specify (in the app-0.17.9/Riot.exe) --proxy-server or --proxy-pac-url... :(

**Comment by szimszon** [comment]
Could be related to #8232 ... and not proxy settings...

**Comment by szimszon** [comment]
Now I modified the public_baseurl to the url without the :8443 but now on login I got CORS errors...

**Comment by szimszon** [comment]
Now I have this:
![kep](https://user-images.githubusercontent.com/745542/51675767-f080a000-1fd4-11e9-8bf6-d110b70f2394.png)

**Comment by szimszon** [comment]
Also there is no use if I try: 
...\AppData\Local\riot\app-0.17.9\Riot.exe --proxy-pac-url=http://wpad/wpad.dat
or even
\AppData\Local\riot\app-0.17.9\Riot.exe --proxy-server=http://...

The same app (0.17.9) is running from Firefox as a charm. I needed to change the public_baseurl from ...hu:8443 to ...hu (without the :8443) but this is another story.

Desktop app 0.17.9 is still not working. ;(

**Comment by dbkr** [comment]
Just tried to reproduce this and I was able to set a proxy server in Windows 10 settings and Riot picked it up and used it. I've just noticed that the error is showing as tunnel connection failed, so it looks like Riot is trying to use the proxy server but failing. Does your proxy server require auth of some kind? Perhaps this is what has broken.

**Comment by szimszon** [comment]
Yes we need authentication for the proxy.
I think we have Negotiate as a means to authenticate to a squid proxy.
https://wiki.squid-cache.org/Features/NegotiateAuthentication

**Comment by floviolleau** [comment]
Hi,

The problem is not only related to electron I think.

I configured a different HS in the login page and for somewhat reason, some XHR calls still go to the default HS and are not using the HS I configured in the login page.

Any ideas?

Thanks

**Comment by jryans** [comment]
> I configured a different HS in the login page and for somewhat reason, some XHR calls still go to the default HS and are not using the HS I configured in the login page.

Is your issue related to proxies as well? If not, I would suggest filing a separate issue, as it sounds a bit different from the issue here.

**Comment by floviolleau** [comment]
I created #8300

**Comment by szimszon** [comment]
The problem is still present with 1.0 ;(

**Comment by szimszon** [comment]
Additionally I have seen when I put http:// instead of https:// (by mistake) I got Proxy Authentication Required error. Weird.

**Comment by szimszon** [comment]
With version 1.2.0 Riot-web started working with proxy using https://wiki.squid-cache.org/Features/NegotiateAuthentication...
