### ISSUE TITLE
Email registration - there's no 'resend' link if the invite email is lost.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8237]
Reported over twitter:
> Trying to sign up. Still waiting for invite email, I fear it was eaten by my SMTP; my spam detection needs a retry to accept email from unknown sources. I can't find a resend link, what do I do?

We should add a 'resend registration email' link to the registration flow.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9397 (more thumbs) - will xfer labels
