### ISSUE TITLE
responsive design collapse prevent room list filtering

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#8244]
A UX nit.

I often run Riot in half my total screen and the responsive design collapses to give a more compact view. As part of the compaction I lose the ability to filter the room list, which means the only way to find a room is to expand the window, filter, then resize. 

Not an urgent requirement, but I wonder if others have the same problem. 

Is it possible through design chicanery to preserve the room list filter?

**Comment by lampholder** [comment]
I'm not a fan of the compact list as it is today at all. It seems feasible to design something that supports filtering/better navigation on a more narrow window profile.

**Comment by turt2live** [comment]
The new room list is better - if it continues to be an concern, please open a new issue.
