### ISSUE TITLE
Custom Status: status ends up on a wrong room

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8245]
![image](https://user-images.githubusercontent.com/1922197/51682097-6fc6a180-1fde-11e9-86cf-60af7a6274f9.png)

Room List Perf Test Room is a room with two participants. It is not a DM for either participant. Both participants have set a custom status. The custom status shown in the screenshot is the status of the _other_ participant (i.e. not the current user).

**Comment by turt2live** [comment]
This is working as intended. The custom status shows up on rooms which *look* like direct chats because it is unaware of the tagging.

**Comment by MurzNN** [comment]
How users can set custom status string, is it available in UI (when Labs item is enabled)?

**Comment by lampholder** [comment]
I've just learned about the `m.is_direct` that is (optionally) provided as part of the matrix protocol to indicate DMs. I know it's not mandated client behaviour, but I think we could lean on it more heavily within Riot (thereby encouraging its adoption more generally, too) to provide a generally saner UX.

**Comment by turt2live** [comment]
The new room list doesn't support custom status.
