### ISSUE TITLE
Settings Redesign: Label on theme control looks strange

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8249]
Maybe we should remove the label from the theme control?

![image](https://user-images.githubusercontent.com/279572/51696727-bd85de80-1fcb-11e9-9a09-efecbab2e0a0.png)

**Comment by turt2live** [comment]
It looks fine over here :(

I think this is partly because there's no final design for dropdowns (on that same page there's 2 kinds of dropdowns) - have added to the list of things to check up on once this all lands.

**Comment by jryans** [comment]
> It looks fine over here :(

What does it look like for you? For me, Firefox and Chrome on macOS seem to both show issues like th screenshot above.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/51697891-266a5800-1fc6-11e9-8001-99e1bc67f4b8.png)

I guess there's just not enough styles being changed on selects?

**Comment by jryans** [comment]
I think the style of `select:disabled` is UA and OS specific, so we may want to force it to white for fields.

**Comment by turt2live** [comment]
Ah, good call. I've put it on the CSS touchups list - if someone beats me to it, that's great :)

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2502

More work to do, however. Tracked here: https://github.com/vector-im/riot-web/issues/8264
