### ISSUE TITLE
Redesign: Fields without placeholder don't match the design

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8250]
Here are some uses of the new `Field` component without a placeholder:

![image](https://user-images.githubusercontent.com/279572/51697255-01c5ae80-1fcd-11e9-8ced-725e7deb964e.png)

The design for input validation says:

<img width="398" alt="2019-01-24 at 11 42" src="https://user-images.githubusercontent.com/279572/51697322-2883e500-1fcd-11e9-898b-b0020ab6083b.png">

The label should still be inside the input, since it is unfocused with no value.

**Comment by turt2live** [comment]
Merged in https://github.com/matrix-org/matrix-react-sdk/pull/2503
