### ISSUE TITLE
after startup, riot shows only loading spinner

### ISSUE THREAD

**Issue by luto** [vector-im/riot-web#8252]
### Description

When opening matrix, there are a bunch of old messages visible in each chat. Below that, there is only a loading spinner, which doesn't go away. New messages after that aren't visible.

The console has roughly 15 messages similar to this one:

```
Error decrypting event (id=$1533757537570962MbvHS:matrix.org): TypeError: Cannot read property 'message' of undefined
```

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: no, see comment

![image](https://user-images.githubusercontent.com/2158203/51709517-dec7e880-2026-11e9-8661-37b60fb47b9a.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome Version 71.0.3578.98 (Official Build) Arch Linux (64-bit) 
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by luto** [comment]
I wanted to submit debug logs, but it just sits there saying "Collecting logs ..." for minutes :/

**Comment by tsowa** [comment]
I have got the same problem from about one month. On one Chromium browser there was such a spinner and no new messages. I pressed 'logout' and now even cannot login, there is  only the spinner visible.

- Platform: web, 0.17.9, self-hosted: chat.x51.pl
- Server: self-hosted synapse 0.34.1 (the same problem was with 0.33)
- Browser: Chromium 71.0.3578.98
- OS: FreeBSD 11 (client and server)
- there is no problem with Firefox 64.0.2 - riot works properly

Below are logs from chromium console:
rageshake.js:99 Overrode homeserver setting with https://matrix.x51.pl/ from login response
rageshake.js:99 setLoggedIn: mxid: @tomasz.sowa:matrix.x51.pl deviceId: LPWASLFPXS guest: false hs: https://matrix.x51.pl/
rageshake.js:99 Removing indexeddb instance: matrix-js-sdk:crypto
rageshake.js:99 Removed indexeddb instance: matrix-js-sdk:crypto
rageshake.js:99 IndexedDB worker is ready
indexeddb-local-backend.js:415 Removing indexeddb instance: matrix-js-sdk:riot-web-sync
indexeddb-local-backend.js:431 Removed indexeddb instance: matrix-js-sdk:riot-web-sync
rageshake.js:99 Deleted indexeddb data.
rageshake.js:99 Session persisted for @tomasz.sowa:matrix.x51.pl
rageshake.js:99 Lifecycle: Starting MatrixClient
rageshake.js:99 IndexedDBStore.startup: connecting to backend
rageshake.js:99 MatrixClientPeg: waiting for MatrixClient store to initialise
rageshake.js:99 newscreen home
rageshake.js:99 Presence: online
rageshake.js:99 IndexedDB worker is ready
indexeddb-local-backend.js:178 LocalIndexedDBStoreBackend.connect: connecting...
indexeddb-local-backend.js:202 LocalIndexedDBStoreBackend.connect: awaiting connection...
indexeddb-local-backend.js:183 LocalIndexedDBStoreBackend.connect: upgrading from 0
indexeddb-local-backend.js:204 LocalIndexedDBStoreBackend.connect: connected
indexeddb-local-backend.js:592 LocalIndexedDBStoreBackend: loading account data...
indexeddb-local-backend.js:612 LocalIndexedDBStoreBackend: loading sync data...
indexeddb-local-backend.js:599 LocalIndexedDBStoreBackend: loaded account data
indexeddb-local-backend.js:619 LocalIndexedDBStoreBackend: loaded sync data
indexeddb-local-backend.js:233 LocalIndexedDBStoreBackend: loaded initial data
rageshake.js:99 IndexedDBStore.startup: loading presence events
rageshake.js:99 IndexedDBStore.startup: processing presence events
rageshake.js:99 connecting to indexeddb matrix-js-sdk:crypto
rageshake.js:99 Upgrading IndexedDBCryptoStore from version 0 to 7
rageshake.js:99 connected to indexeddb matrix-js-sdk:crypto
rageshake.js:99 Unhandled rejection TypeError: Cannot read property 'name' of undefined    at e.<anonymous> (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:65648)    at E (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:152766)    at Generator._invoke (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:152554)    at Generator.e.(anonymous function) [as throw] (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:152945)    at Generator.c (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:140731)    at p._promiseRejected (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:97987)    at R._settlePromise (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:114888)    at R._settlePromise0 (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:115461)    at R._settlePromises (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:116702)    at https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:70263From previous event:    at R.U [as _captureStackTrace] (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:83751)    at R._then (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:109419)    at R.then (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:1:107767)    at Object.onPasswordLogin (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:98:291008)    at t.value (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:105:146567)    at Object.o (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:39:37923)    at s (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:39:36124)    at Object.executeDispatchesInOrder (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:39:36853)    at f (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:159654)    at p (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:159780)    at Array.forEach (<anonymous>)    at e.exports (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:53:237061)    at Object.processEventQueue (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:161184)    at https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:55:37519    at Object.handleTopLevel [as _handleTopLevel] (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:55:37541)    at p (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:55:58621)    at u.perform (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:31:65726)    at Object.batchedUpdates (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:53:252170)    at Object.batchedUpdates (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:23:44211)    at dispatchEvent (https://chat.x51.pl/bundles/c2932262ed6106cd4535/bundle.js:55:59402)
e.(anonymous function) @ rageshake.js:99
a @ bluebird.js:1564
H @ bluebird.js:1280
Y @ bluebird.js:1305

In server logs I found some warnings such as:

2019-01-25 16:27:13,921 - synapse.access.https.8448 - 233 - INFO - POST-400- - - 8448 - Received request: POST /_matrix/federation/v1/groups/%2Btestcommunity%3Ax51.pl/renew_attestation/%40tomek.ttmath%3Amatrix.\
org
2019-01-25 16:27:13,922 - synapse.federation.transport.server - 267 - WARNING - POST-400- authenticate_request failed: 401: Invalid signature for server matrix.org with key ed25519:auto: Unable to verify signat\
ure for matrix.org
2019-01-25 16:27:13,923 - synapse.http.server - 85 - INFO - POST-400- <XForwardedForRequest at 0x8104d9368 method=u'POST' uri=u'/_matrix/federation/v1/groups/%2Btestcommunity%3Ax51.pl/renew_attestation/%40tomek\
.ttmath%3Amatrix.org' clientproto=u'HTTP/1.1' site=8448> SynapseError: 401 - Invalid signature for server matrix.org with key ed25519:auto: Unable to verify signature for matrix.org

2019-01-25 16:27:30,684 - synapse.access.https.8448 - 233 - INFO - PUT-401- - - 8448 - Received request: PUT /_matrix/federation/v1/send/1548390315434/
2019-01-25 16:27:30,685 - synapse.metrics - 374 - INFO - - Collecting gc 0
2019-01-25 16:27:30,688 - synapse.federation.transport.server - 267 - WARNING - PUT-401- authenticate_request failed: 401: Invalid signature for server terracrypt.net with key ed25519:a_pRmF: Unable to verify s\
ignature for terracrypt.net
2019-01-25 16:27:30,688 - synapse.http.server - 85 - INFO - PUT-401- <XForwardedForRequest at 0x810435830 method=u'PUT' uri=u'/_matrix/federation/v1/send/1548390315434/' clientproto=u'HTTP/1.1' site=8448> Synap\
seError: 401 - Invalid signature for server terracrypt.net with key ed25519:a_pRmF: Unable to verify signature for terracrypt.net
2019-01-25 16:27:30,689 - synapse.access.https.8448 - 302 - INFO - PUT-401- - - 8448 - {None} Processed request: 0.005sec/0.001sec (0.003sec, 0.000sec) (0.001sec/0.001sec/1) 154B 401 "PUT /_matrix/federation/v1\
/send/1548390315434/ HTTP/1.1" "Synapse/0.34.1.1 (b=HEAD,t=v0.34.1.1,5c792ee)" [0 dbevts]

**Comment by luto** [comment]
The error fixed itself for me.
