### ISSUE TITLE
Detect Modular via config.json

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8253]
For the authentication redesign, we want to know if Riot's default HS is Modular or not. One way to do so would be to state that it is in `config.json` for Modular installs.

**Comment by jryans** [comment]
For a Modular-hosted Riot, we will

* Hide the 3 column server type selector on auth pages 
* Add a note linking to riot.im in case the user was expecting to connect to some other server
* Skip the Modular server name prompt

**Comment by ara4n** [comment]
I suggest this isn’t done in a modular specific manner, but more: `“forceHS”: true` or something?

**Comment by jryans** [comment]
> I suggest this isn’t done in a modular specific manner, but more: `“forceHS”: true` or something?

I went back and forth about that... Let's discuss more in https://github.com/matrix-org/matrix-hosted/issues/538.

**Comment by jryans** [comment]
> I suggest this isn’t done in a modular specific manner, but more: `“forceHS”: true` or something?

I went back and forth about this... I agree it's clearer and more future-proof to use settings specific to the desired behavior like you are suggesting. 

Originally, I was worried we'd need to pre-select the Modular server type button on Modular-hosted Riots, but since we've decided to entirely hide the server type selector, then yes, I think something like that will work. `"forceDefaultHS": true` seems to capture the intent.

**Comment by jryans** [comment]
Filed https://github.com/matrix-org/matrix-hosted/issues/538 to add the extra config setting to Modular-hosted Riots.

**Comment by jryans** [comment]
Ah, we already have `disable_custom_urls`, so I think we could continue using this.

**Comment by jryans** [comment]
Modular now sets `disable_custom_urls` (which also hides the 3 column selector), so that seems sufficient here.
