### ISSUE TITLE
Mark Microsoft Edge as a browser that is not supported

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#8259]
According to https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$154523902082863CXVSE:matrix.org?via=matrix.org&via=half-shot.uk&via=linuxgaming.life Edge is not supported, why doesn't it throw up the message saying your browser isn't supported? People keep having bad experiences with this.

**Comment by aaronraimist** [comment]
Looks like it used to work #3624

**Comment by aaronraimist** [comment]
Actually the [developer guide](https://github.com/matrix-org/matrix-react-sdk#developer-guide) says
> Edge should also work, but we're not testing it proactively.

so I don't know what the best course of action is

**Comment by turt2live** [comment]
It looks like Edge works just fine for me. What sort of issues are causing problems?

It's probably not throwing up warnings about being unsupported because it has the required APIs to do what Riot needs.

**Comment by aaronraimist** [comment]
Seems like it does work for me as well so I'll close this for now and if someone has an issue with edge in the future they can submit their logs
