### ISSUE TITLE
New line characters are deleted when pasting several lines of text into the chat box

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/riot-web#8274]
- **Browser**: Icecat 60.3.0esr 64bit
- **OS**: GuixSD GNU/Linux-libre

### Description
When I paste something like some lines from IRC into Riot I lose the formatting of all the lines. It gets squished together.
![2019-01-26-150717_728x64_scrot](https://user-images.githubusercontent.com/3146494/51792788-73a91e00-21ae-11e9-8252-27ef1c671ca6.png)
![2019-01-26-150724_475x138_scrot](https://user-images.githubusercontent.com/3146494/51792790-773ca500-21ae-11e9-9969-195c2260e010.png)

### Steps to reproduce
- find some multi-line text to copy
- copy it either as full lines with a triple click and drag or as a block select with ctrl-shift click and drag
- middle click to paste into riot or ctrl-v if you copied to secondary clipboard in previous step

### Describe how what happens differs from what you expected.
I expect it to continue looking like it does in my first screenshot. Instead I've got to go through the text slowly and hit shift-enter at all the spots where it was supposed to have a new line just to get the formatting back that was already there before.

**Comment by lampholder** [comment]
There's a lot of stuff that could be going wrong outside of riot here - if this text were copied from a terminal, etc. I haven't been able to reproduce it with any multiline text I've found.

**Comment by Soundtoxin** [comment]
After discussing the problem with some people, I changed this about:config setting to true and it fixed some pasting issues with riot, the multiline problem in particular.
dom.event.clipboardevents.enabled;true
It was false by default in Icecat.

**Comment by lampholder** [comment]
I've not heard of this affecting anyone else, and this setting is `true` by default in firefox

**Comment by Soundtoxin** [comment]
It's false by default in IceCat.
