### ISSUE TITLE
Redesign: Arial is leaking into Settings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8275]
Looks because we're trying to reference Nunito Semibold but haven't included it as a webfont?  Correct would be to specify Nunito but at the correct `font-weight` (600 for semibold).

e.g. word Composer:

<img width="303" alt="screenshot 2019-01-26 at 22 41 51" src="https://user-images.githubusercontent.com/1294269/51793652-9988ef80-21bb-11e9-8683-1554c613c4f7.png">

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2526
