### ISSUE TITLE
Redesign: Disable FF-based switching CSS themes

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8277]
Apparently FF users are still given the option to switch theme by selecting the alt CSS from the dharma theme.  We should just remove the broken themes I suspect and re-add them in as they are implemented to work.

https://twitter.com/grahamperrin/status/1089255738390839297

**Comment by ara4n** [comment]
see also #7578

**Comment by turt2live** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/8280
