### ISSUE TITLE
Consider only showing the first line of the commit in the changelog

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8285]
So that when people like me write a short story as a commit message people aren't bombarded with it.

![image](https://user-images.githubusercontent.com/1190097/51850465-0648da80-22df-11e9-9fb7-06b02011de2e.png)

**Comment by lampholder** [comment]
tbh I quite enjoy the short stories :P

**Comment by jryans** [comment]
I also enjoy the long messages... I just wish they displayed with line breaks and such as they were written.

**Comment by turt2live** [comment]
I see no harm in having people click to read more. Consider it your 1 line preview of the chapter :p

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2667
