### ISSUE TITLE
Searching without a valid hit makes the room list strange

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#8286]
- **Browser**: Current Firefox Nightly
- **OS**: Fedora Linux

### Description

When searching for something without getting a hit, the two special-cased panels, "people" and "rooms" still appear, and share 50% of the available space, which looks strange.

### Steps to reproduce

- search for a room that doesn't exist

Describe how what happens differs from what you expected.

None of the panels should appear, or the available actions, should be visible in a more friendly way
such as "create a new room" or "create a chat with someone"

Log: not sent?    
![image](https://user-images.githubusercontent.com/5447747/51853512-c3135980-2328-11e9-892a-7551f849dcd1.png)

**Comment by bwindels** [comment]
https://github.com/vector-im/riot-web/issues/7578#issuecomment-433355898
