### ISSUE TITLE
Everyone is reporting that Electron on says its on macOS

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#8298]
Affects Riot Desktop on both Windows and Linux. Someone must have filled a bug for this already, I've seen it reported like 15 times but I can't find any open bug.

**Comment by tya99** [comment]
I can confirm, if there's anything you'd like me to test I will do so.

**Comment by jryans** [comment]
This should be fixed by https://github.com/vector-im/riot-web/pull/8241, but so far it has only been merged into experimental.

**Comment by aaronraimist** [comment]
Seems fixed, at least on Fedora

For anyone else seeing this: Riot doesn't seem to rename your existing devices so you may want to manually rename them or log in and log out.
