### ISSUE TITLE
Quote in desktop notification displayed incorrectly

### ISSUE THREAD

**Issue by natrius** [vector-im/riot-web#8305]
### Description

Using the Riot Desktop App on Windows, getting the small preview windows in the corner of the monitor. When a quote was used in the message, special characters are shown like _s & gt ; _

### Steps to reproduce

- Minimize Riot
- get somebody to quote something

Log: not sent?

![screen_riot](https://user-images.githubusercontent.com/7243447/51911238-9e26f100-23d1-11e9-9356-295fc5b99c5b.png)

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 0.17.9

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/53295396-69e8f980-37f2-11e9-8d77-e1291db91eca.png)

Cannot repro

**Comment by turt2live** [comment]
Also can't reproduce on desktop or web
