### ISSUE TITLE
Video chat no full screen

### ISSUE THREAD

**Issue by riot-user** [vector-im/riot-web#8308]
Hi,
on different screens (Laptop, 4k-Monitor, HD-Monitor) full screen is not really full screen. The own window is to big in the left corner. The main window is only half of the screen.

**Comment by lampholder** [comment]
I don't think I've seen this - are you happy/able to submit a screenshot?

Also do you know if this is a jitsi video conference or the 1:1 video calling built into Riot?

**Comment by lampholder** [comment]
I haven't been able to reproduce this - if you are still having problems and are happy to provide more detail, please reopen :)

**Comment by riot-user** [comment]
![Riot Full Screen](https://user-images.githubusercontent.com/47153247/54385390-c2474480-4696-11e9-9995-92d4a6ba6a18.JPG)

Hi, sorry for the late reply. Enclosed the screenshot. The picture is only 40% of the possible space.
