### ISSUE TITLE
Room v3 permalinks don't always work

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8315]
Sample: 
https://matrix.to/#/!bxACizmWIbCVfYUUZD:jki.re/$39w4321vgLY9rzStEo3uvKXeHXq52qOqVV/ymH2lkZI?via=jki.re&via=t2l.io

Result:
![image](https://user-images.githubusercontent.com/1190097/51949157-b6563a80-23e8-11e9-8e07-e0ab8946d353.png)

My bet it on the slashes.

**Comment by lampholder** [comment]
Is this a riot thing or a synapse thing?

**Comment by turt2live** [comment]
Riot+Spec probably.
