### ISSUE TITLE
'view source' modals look weird

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8324]

**Comment by lampholder** [comment]
Please can we have a screenshot with any "X looks adjective" bugs?

Looks fine to me:

![image](https://user-images.githubusercontent.com/1922197/52074633-3a8ff580-2582-11e9-85e3-22aa89ad1ca6.png)

Do you mean weird inasmuch as they don't have a close X?

**Comment by turt2live** [comment]
I can only assume it was because the title is missing. Closing as fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2696
