### ISSUE TITLE
clicking on riot.im link from home page replaces Riot with the about.riot.im page

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#8331]
which is really bad on the desktop app.  As reported at https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$154888409275433mNISv:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org  Related to #8226

**Comment by jryans** [comment]
Presumably this link also needs `target="_blank" rel="noopener"` added.

**Comment by uhoreg** [comment]
yup, although it might be good for whatever displays the home page to add those attributes rather than relying on people who edit the home.html to remember to add them

**Comment by minakitty** [comment]
If it's what I read that as, I noticed something similar when trying to connect to my homeserver I just installed (I'm new to Matrix/Riot in general)  I got the following error message when inputting my custom server info:
`Can't connect to homeserver - please check your connectivity, ensure your homeserver's SSL certificate is trusted, and that a browser extension is not blocking requests.`
And 'homeserver's SSL certificate' is a hyperlink.  I clicked it thinking it would give me more information and instead it took me to the root index.html file of my web server.  The only way I could get out was to fully exit Riot from the task tray in Win10

**Comment by lampholder** [comment]
@uhoreg I don't know if we do any post-processing on the home.html - if we do then yes that would make sense

@minakitty that is related (inasmuch as we shouldn't be rendering that link without the `target="_blank" rel="noopener"` business

**Comment by jryans** [comment]
I believe home.html is loaded directly as an unmodified static page.

The one @minakitty mentioned has already been fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2496, we just haven't released an Electron build with that fix yet.

**Comment by jryans** [comment]
> We run home.html through internationalisation so I'd think there's some level of processing going on there

Ah, fair enough... We do a string replacement at load time for that.

I guess I am not thrilled about using more string replacement to adjust link `href`s (harder to get the replacement correct), but it could be done if we really want to solve this in one place for home.html.

**Comment by jryans** [comment]
The specific link reported here has been fixed in https://github.com/vector-im/riot-web/pull/8365.
