### ISSUE TITLE
If HS registration is disabled, errors trying to register are awful

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8334]
You get an error of "Unable to query for supported registration methods" rather than "this homeserver has registration disabled"

**Comment by lampholder** [comment]
We should check the new flow against standard modular configs (e.g. required email address), too

**Comment by lampholder** [comment]
The /app behaviour is also problematic.

- go to register
- choose 'custom server'
- start typing in the Home server URL (why is there a space there?????)
- if you type too slowly it polls `https://partofadomainna/register`, gets an error, and (on my macbook air) displays that error below the fold
- if you complete typing a HS URL for an HS with registration disabled, it gets back the `registration disabled` state in the json payload, and _doesn't_ tell the user
- user is left to enter their registration details with no hope of success
- registration fails, error displayed beneath the fold

**Comment by jryans** [comment]
This is a regression with the new flow on /develop? A screenshot would help, but I can try to recreate as well.

**Comment by jryans** [comment]
> This is a regression with the new flow on /develop? A screenshot would help, but I can try to recreate as well.

Yes, it's a regression. @lampholder supplied this from /app:

![image](https://user-images.githubusercontent.com/279572/52069482-6be9d080-2544-11e9-9e6c-b8664236c4d9.png)

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2548.
