### ISSUE TITLE
Composer layout broken after Start Chat

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8335]
<img width="1151" alt="screenshot 2019-01-31 at 10 55 32" src="https://user-images.githubusercontent.com/1294269/52046381-df8cdd00-2546-11e9-8ce6-5745f5c76941.png">

**Comment by ara4n** [comment]
this was a newly created DM to a federated user (on the initiator's side); it looks like we're missing the self-avatar entirely for this DM, which breaks the layout.

**Comment by bwindels** [comment]
I guess the missing self-avatar is missing state from the server, as it should always send your own user IIRC. I'll have a look to fix the layout issues though.
