### ISSUE TITLE
Requesting WebRTC media permissions from UserSettings leaves the camera permenantly turned on.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8340]
I just took an incognito tab in Chrome, logged into a local Riot (http://localhost:8080), and opened UserSettings and hit the 'request permissions' button on the VoIP tab. It turned on the camera, which stayed on despite exiting Settings.

**Comment by t3chguy** [comment]
Damn I thought I fixed this

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/structures/UserSettings.js#L295-L299 should prevent this :(

**Comment by jryans** [comment]
Is this issue with the new tabbed style or old style settings UI?

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2553
