### ISSUE TITLE
Home button missing

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-web#8341]
- **Browser**: Firefox 56
- **OS**: Debian

### Description

I can't find the button of the home screen. I use this frequently, when I leave a chat room and don't expect to get new messages. Otherwise I have to stay in a room, but when I switch back to the riot tab, the new messages in this room get marked as read, while I don't want  to read those messages.

It would also helpful to have a hotkey for this button, like ctrl-k is for the room filter.

**Comment by turt2live** [comment]
Fixed - it's now under your name in the top left if configured

**Comment by ndarilek** [comment]
I'm a blind screen reader user and can't find this. Is it keyboard-accessible?

I click the button labeled with my name and see options Settings and Log out. No Home button.

I'm trying to navigate back to the screen where I can join a room. Whenever I load Riot, I'm in my last room. I can't figure out how to join another.

THanks.

**Comment by jryans** [comment]
> I click the button labeled with my name and see options Settings and Log out. No Home button.
> 
> I'm trying to navigate back to the screen where I can join a room. Whenever I load Riot, I'm in my last room. I can't figure out how to join another.

At the moment, there will only be a Home button in the menu if a home page was configured by whoever is hosting Riot. On the default install at https://riot.im/app, no home page is set, so no Home button will appear in the menu.

Are you looking for the room directory? That can be reached via the "+" button next to the "Rooms" sub-header on the left side, but now that I've written that out, it doesn't sound very accessible. Perhaps we should add some kind of title or similar to the button so you can locate it via screen reader? (It already has a `role=button` and `tabindex=0` set.)

**Comment by jryans** [comment]
(If you have suggestions to improve the room directory button's accessibility or similar, I would suggest creating an new issue for that.)

**Comment by ndarilek** [comment]
OK, found the button. Happy to open new issues, but in this case I 
didn't even know what to *ask* for. :) Thanks, any reason a home 
location isn't configured on riot.im/app? I actually did click on the 
button with my name a few times, so I'd have found that if it was an 
option. I think it's a good thing to have. It feels a bit odd to me 
that, once I've joined a room, I can't relate to Riot in any way other 
than landing in that last room. Meanwhile, the home page makes 
discovering lots of things easier, and in the absence of easy 
accessibility to some features, that discovery is a useful thing.


Thanks again.

**Comment by jryans** [comment]
>Any reason a home location isn't configured on riot.im/app?

That content was moved to a separate "welcome" page that appears when you are logged out (though you can still view it when logged in via the URL https://riot.im/app/#/welcome.)

It's possible that choice should be reconsidered, so you could file an issue like "Bring back the home page to riot.im" or similar if that's something you'd like to see.

Independent of whether there is or is not a home page though, let's also try to make the always present "add room" button more accessible as well.

**Comment by jo-so** [comment]
A hint about this issue: Now, I'm using the communities button on the left bottom corner, when I want to leave all rooms.

BTW: This might also a good page to go after `/part`. Currently, after `/part` a random room gets opened.
