### ISSUE TITLE
Settings page content overlaps headline

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-web#8343]
- **Browser**: Firefox 56
- **OS**: Debian

### Description

When scrolling down on the global settings page, the page content goes beyond the line of the page head.

![grafik](https://user-images.githubusercontent.com/23032146/52055321-5f26a600-255f-11e9-8309-b0086bc06bbe.png)

**Comment by lampholder** [comment]
"tabbed settings" fix inbound (take a look in labs to enable the tabbed settings feature to follow the wip)
