### ISSUE TITLE
Settingspage: Distance of communities with border too small

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-web#8344]
- **Browser**: Firefox 56
- **OS**: Debian

### Description

In the global settings page, the distance to the border of the communities section is to small.

![grafik](https://user-images.githubusercontent.com/23032146/52055850-d9a3f580-2560-11e9-9def-4dcd52f2751f.png)

**Comment by lampholder** [comment]
AH, looks like an unintended side effect of fixing flair styling in the new 'tabbed settings' (there's a labs feature you can enable to follow that work in progress). Tabbed settings is an incremental effort to improve riot's settings UX, starting by dividing the existing settings into different 'tabbed' sections.

So I don't expect we'd fix this, 'cause tabbed settings are going to land very shortly and replace the existing settings ux.
