### ISSUE TITLE
Move non-feather icons out of feather-icons directory

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8348]
The `feather-icons` directory currently contains a mix of https://feathericons.com/ icons and ones from other places.

@ara4n [says](https://github.com/matrix-org/matrix-react-sdk/pull/2540#discussion_r252491900) let's keep it to https://feathericons.com/ only, so we'll need a bit of detective work to sort them out.

**Comment by bwindels** [comment]
As we've forked feather-icons with the stroke thickness changes Nad did, I wonder how useful this will be, but meh :)

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2706
