### ISSUE TITLE
Nunito font on Windows looks like a ransom note

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8350]
Apparently we didn't have a public issue to track this, so here it is. 

![image](https://user-images.githubusercontent.com/1190097/52076209-68a61300-254b-11e9-9810-538458c17bac.png)

**Comment by lampholder** [comment]
I'm going to close this as a dup of https://github.com/vector-im/riot-web/issues/8092 (though I'll lift this nice illustration for that issue)
