### ISSUE TITLE
Search room messages

### ISSUE THREAD

**Issue by girzel** [vector-im/riot-web#8353]
Apparently the riot web search functionality only searches room members, not room messages. For small rooms, at least (eg my wife and I have a room for family discussions), it would be very handy to be able to search message history.

**Comment by jryans** [comment]
Hmm, is this in an encrypted room? It does search room messages, but currently only for unencrypted rooms. See https://github.com/vector-im/riot-web/issues/2548 for planned work to enable search in encrypted rooms.

**Comment by girzel** [comment]
Thanks, that's the one to watch. I appreciate the quick response.
