### ISSUE TITLE
Login with Custom Server

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#8359]
### Description

This is a comment based on the change introduced in matrix-org/matrix-react-sdk#2547.

### Steps to reproduce

- Go to https://riot.im/develop/#/login
- Type a mxid with a non-matrix.org HS in the login box (blindly not reading the rest of the page :wink: )
- Type your password in
- It breaks.

The great thing that `.well-known` added was that the user had to follow one set of instructions irrespective of what default HS Riot was configured with (i.e. using riot.im or chat.openastronomy.org etc), they just typed their mxid and password in.

After this change if you are not using the default HS then you now have to click custom.

I would suggest that if you type a mxid into the username box with a domain part not matching the default that Riot is configured to it automatically swaps to the "Custom" option and does a .well-known lookup.

**Comment by jryans** [comment]
Thanks for filing! 😁 I agree that `.well-known` and the 3 column server type selector don't interact very well together.

I believe we can fix this by restoring the login flow to something simpler without the server type selector.

**Comment by jryans** [comment]
This should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2574.
