### ISSUE TITLE
 Viewing any room chat logs without joining them hangs my browser FF 43.0.3

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#836]
Illandan: viewing any room chat logs without joining them hangs my browser FF 43.0.3 (including small chat rooms https://matrix.org/beta/%23/room/%23WhatWouldMatrixDo%3F:matrix.org)

Amandine repro'd on FF 44.0.0. 

But couldn't repro when matrix.org was diminished. To be tested again

**Comment by aaronraimist** [comment]
Probably not reproducible anymore?

**Comment by turt2live** [comment]
Going to assume so. If it happens again, please open a new issue.
