### ISSUE TITLE
Reducing window size causes big ol' slug of a scrollbar

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8361]
<img width="699" alt="screenshot 2019-02-01 at 16 21 17" src="https://user-images.githubusercontent.com/4626865/52135350-8489e180-263d-11e9-9c01-39db216aa9ef.png">

Safari on /experimental.

**Comment by lampholder** [comment]
Same on Chrome:
![image](https://user-images.githubusercontent.com/1922197/52135513-e34f5b00-263d-11e9-8d96-4d7446a07a86.png)

**Comment by ara4n** [comment]
CSS Horizontal scrollbars are also broken in timeline for overscroll on macOS Chrome:

<img width="952" alt="screenshot 2019-02-05 at 01 30 53" src="https://user-images.githubusercontent.com/1294269/52248299-b1602200-28e5-11e9-9857-8c57fb04685e.png">

**Comment by ara4n** [comment]
fixed by 6083b8853
