### ISSUE TITLE
Space and caption after a link breaks the link

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/riot-web#8370]
- **Browser**: Icecat 60.3.0esr 64bit
- **OS**: GuixSD GNU/Linux-libre

### Description
If I paste a link and put a few words after it, the link breaks. Seem to be adding percentsignuFEFF to the end of stuff. If someone quotes the message, the link in the quoted section works.

### Steps to reproduce

- paste link
- make a space after the end of the url and type some stuff

It seems to be a recent issue.

**Comment by Soundtoxin** [comment]
This bug is hellish. It breaks link previews, but also a lot of times makes the link itself not work. People are lazy these days so it's the difference between my links being viewed or not. They're not gonna manually copy/paste or fix the URL. It seems to happen even if I just start a new line right after the link. I don't have ways to avoid it anymore besides posting ONLY the link and then saying anything related in a separate message, which I am not a fan of doing.

**Comment by lampholder** [comment]
Could you provide more information on how you're copying and pasting the link? Where from, which paste buffer, what UX path you're using (ctrl+c vs right click copy vs highlight and paste with middle click, etc.) Also what mode is the composer in (markdown or rich text)?

Thanks!

**Comment by Soundtoxin** [comment]
I believe it occurred with both ctrl-c/ctrl-v copy paste and highlight/middle click copy paste. I always leave markdown mode on. I think the cause is related to a default about:config setting in icecat. I recently solved several Riot issues all in one go by changing it, however I still recall things working fine at some point before so I'm not sure if it's a bug or not. The setting in question is `dom.event.clipboardevents.enabled`. It was false by default and setting it to true solved this issue as well as another one where my new line characters were being deleted so my paste got squished into one blob. Whether you close this is up to you. I'm not sure if you want this setting to be required or not. If this setting is the way it is in icecat but not firefox, it's likely due to privacy or security benefits to having it disabled, and I don't recall other sites giving me trouble pasting things.

**Comment by aaronraimist** [comment]
@Soundtoxin Can you confirm if this has been fixed in recent versions of Riot?

**Comment by Soundtoxin** [comment]
Not the most scientific test since I've changed hardware, operating systems, and browsers in this time (using normal firefox instead of icecat at the moment), but I've tried setting that about:config setting to the one that was an issue before, and the problem doesn't seem to occur. Should be safe to close this. I'd forgotten about it since I found that work-around before.
