### ISSUE TITLE
credit @octete for the auth page bg (CC-BY-SA)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8374]

**Comment by jryans** [comment]
What's the precise attribution required here? Where should it be placed?

**Comment by jryans** [comment]
I assume we should do something here before the release...?

**Comment by ara4n** [comment]
erm, yup. i should have asked @octete at lunch today how to handle this, but forgot.

We really should have a 3rd party licensing section in Settings in general, which lists all our attribution license obligations.  I don't think we need to scrawl on the image itself.

**Comment by octete** [comment]
Do you need anything from me? :)

**Comment by ara4n** [comment]
@octete only confirmation i guess that CC-BY-SA is okay as a license and whether you want to be credited by name or nickname :)

**Comment by jryans** [comment]
We could add this to Settings -> Help & About -> Legal next to the policies once we have the attribution content.

**Comment by lampholder** [comment]
> @octete only confirmation i guess that CC-BY-SA is okay as a license and whether you want to be attributed by name or nickname :)

@octete have you had any thoughts on this? I'd also like to credit you in the blog post (with thanks to you in the caption under one of the screenshots with the photo) - are you happy for that? How would you like to be credited there?

And thanks btw - the photo is beautiful :)

**Comment by octete** [comment]
Hi Tom,

Apologies for the delay. Name would be better, thanks! :-)
