### ISSUE TITLE
Encryption icons aren't clickable

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8375]
![image](https://user-images.githubusercontent.com/1190097/52160224-9041cc00-266e-11e9-8ab0-d3c4013c056b.png)

I feel these red icons should be clickable so I can solve the problem they are trying to convey. Likewise with the grey one down here:

![image](https://user-images.githubusercontent.com/1190097/52160226-a780b980-266e-11e9-96e5-c38ca3a0cde2.png)

**Comment by Cadair** [comment]
I ran into this earlier, clicking on the ones by the message could also show what device sent it?

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8441 because it has more labels

**Comment by bpcurse** [comment]
The referenced Issue #8441 has been closed as well but the icons still aren't clickable in v1.5.5 (Manjaro/Arch Linux Desktop). Only a tooltip is displayed.

![Bildschirmfoto_2019-12-10_21-34-55](https://user-images.githubusercontent.com/29312856/70567261-e25c5380-1b95-11ea-9671-216d1ddfaedd.png)
![Bildschirmfoto_2019-12-10_21-35-12](https://user-images.githubusercontent.com/29312856/70567270-e6887100-1b95-11ea-8482-02aa567a922f.png)

I'd recommend to reopen this issue.

**Comment by turt2live** [comment]
This sort of thing should be addressed in the cross-signing sprint. In general, please open a new issue for issues.
