### ISSUE TITLE
Unable to scale user interface in desktop app

### ISSUE THREAD

**Issue by rjek** [vector-im/riot-web#8378]
### Description

The usual Ctrl-+ and Ctrl-- shortcut keys do not scale the user interface when using the desktop version of Riot.  This works fine when using Firefox.

### Steps to reproduce

- Launch Riot desktop app
- Press Ctrl-+ (Actually Ctrl-Shift-=)

I expect the user interface to scale larger: nothing happens.  Same for Ctrl--

Log: Not sent   

### Version information

- Desktop

For the desktop app:

- Debian Linux (testing)
- **Version**: 0.17.9

**Comment by jryans** [comment]
#8416 clarifies that is a regression, so closing this in favor of #8416.
