### ISSUE TITLE
When sending email invitations, email user names containing hyphens don't work. For example: awd-s@example.com doesn't work whereas awds@example.com does.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8382]

**Comment by aaronraimist** [comment]
Original report is: https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1549213167323508fCzio:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org

It's not clear exactly what part doesn't work (receiving the email or accepting the invite) but I can't reproduce this. I can send invites to emails with hyphens and they seem to work just fine. I receive the email and can accept the invite.
![screen shot 2019-02-03 at 12 00 37 pm](https://user-images.githubusercontent.com/5855073/52180556-6ba03e00-27ad-11e9-83b1-95640747f106.png)

![screen shot 2019-02-03 at 12 14 41 pm](https://user-images.githubusercontent.com/5855073/52180550-54f9e700-27ad-11e9-9f3f-6c526f2ee8a0.png)

**Comment by aaronraimist** [comment]
> Sorry, I should have continued by saying that after sending the invitation to the hyphenated user, the recipient doesn't receive an email from the system containing the invitation.

**Comment by aaronraimist** [comment]
@ara4n user says:

> The problem isn't me or Riot. It appears that the receiving email server is rejecting messages from the Riot domain and responding with "Diagnostic-Code: SMTP; 554 5.7.1" which I understand implies that your IP is on a blacklist somewhere. It's not just Riot, a message from an email server in The Netherlands is similarly rejected whereas one from a server in Switzerland is accepted and passed to the recipient. Rather than waste more time, we'll just work around the problem by changing email servers. Thank you for your help.

**Comment by lampholder** [comment]
I couldn't reproduce this either - thanks for investigating.
