### ISSUE TITLE
Room directory topics get double html-escaped

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#8383]
### Description

In the room directory, the topics appear to get html-escaped twice, leading to ugly "&amp" text being visible.

![image](https://user-images.githubusercontent.com/5447747/52182647-708ddd80-27ff-11e9-9df2-fea9ea83fe3f.png)

### Steps to reproduce

 1. open room directory

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/3461
