### ISSUE TITLE
Loop in 'try the app' flow

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8384]
> I found a bug with Riot redesign.
> 
> 1. https://riot.im/develop/
> 2. Try the app first (guest login)
> 3. Create account
> 4. Sign in instead
> 5. Try the app first (guest login)
> 6. > You need to register to do this. Would you like to register now?

Source: https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1549233808403264ZXsKl:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org

**Comment by lampholder** [comment]
I just end up in a loop on matrix.org:

1. ![image](https://user-images.githubusercontent.com/1922197/54356600-ec2b4780-4653-11e9-87f7-ae01aab5d0d2.png)
2. ![image](https://user-images.githubusercontent.com/1922197/54356629-fa796380-4653-11e9-9379-fe603a622490.png)
3. Click 'Try the app first' -> Goto 1

**Comment by turt2live** [comment]
Considering we don't have a concept of guests, is the fix to just remove the option? This is technically ILAG.

**Comment by lampholder** [comment]
The fix is just to remove the option!

We'll revisit onboarding as part of Community-based onboarding, but for now lets just delete the 'Try the app first' link from the Sign In page.
