### ISSUE TITLE
we shouldn't warn users about needing to invite users an empty room if there are already invited users there

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8387]

**Comment by turt2live** [comment]
This is a regression: https://github.com/vector-im/riot-web/issues/6851

**Comment by ara4n** [comment]
this looks so crap :(

<img width="768" alt="Screenshot 2019-03-12 at 16 20 01" src="https://user-images.githubusercontent.com/1294269/54243828-e9303a00-4521-11e9-9a12-96afc0a268c4.png">

prioritising it and putting it on FIP

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/7644 (copied to FiP)
