### ISSUE TITLE
Update icons in riot-web repo

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8391]
Everything in:

- [x] res/vector-icons
- [x] electron_app/build
- [x] electron_app/img

**Comment by jryans** [comment]
The favicons exists in ~20 shapes and sizes for different devices:

https://github.com/vector-im/riot-web/tree/develop/res/vector-icons

Is there a "good" way to update them? Maybe a script or something?

**Comment by ara4n** [comment]
https://github.com/vector-im/riot-web/blob/master/scripts/make-icons.sh

**Comment by jryans** [comment]
It sounds like @nadonomy is working on this.
