### ISSUE TITLE
Added a room to community, "Unnamed Room" added

### ISSUE THREAD

**Issue by vranki** [vector-im/riot-web#8395]
### Description

I added a room to a community. The added room was named "Unnamed Room" and 
cannot be removed.

The community in question is  +community:hacklab.fi if you want to check for yourself.

### Steps to reproduce

(Not sure if the adding failure can be reproduced easily)

- Add a room to community (in this case a channel bridged from IRC)
- Observe it's name is "Unnamed Room"
- Delete the room from community
- "Failed to remove 'Unnamed Room' from +community:hacklab.fi"

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 65
- **OS**: Ubuntu
- **URL**: Both riot.im/develop and riot.im/app

**Comment by turt2live** [comment]
This might be an instance of https://github.com/vector-im/riot-web/issues/5866

**Comment by vranki** [comment]
Yep, looks like it. I think this cam be marked as duplicate. 

Should I file a separate bug for not being able to delete the Unnamed room from community?

**Comment by lampholder** [comment]
> Should I file a separate bug for not being able to delete the Unnamed room from community?

Yes please (if you haven't already)

**Comment by vranki** [comment]
Deletion issue filed as #8765
