### ISSUE TITLE
Fix poorly constructed nodes in SVG's

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8396]
Fix dots in any icons with '!' marks. 

E.g. Widgets:

<img width="460" alt="screenshot 2019-02-04 at 15 17 21" src="https://user-images.githubusercontent.com/4626865/52217297-0cffc080-2890-11e9-9715-ec011f974adc.png">

Help & About in Settings:

<img width="126" alt="screenshot 2019-02-04 at 15 17 30" src="https://user-images.githubusercontent.com/4626865/52217312-1426ce80-2890-11e9-96d3-49bd28780996.png">

**Comment by lampholder** [comment]
I think this is fixed
