### ISSUE TITLE
quitting a room doesn't remove it from my room list

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#8398]
More specifically, this was a 1:1: where the other party had left, and now the room is still in the People category while it should have gone to historical

**Comment by turt2live** [comment]
@AmandineLP were you hovering over the room list at the time? Wondering as there's a known-ish bug related to this and just want to verify if this is another manifestation of it.

**Comment by turt2live** [comment]
Presuming fixed, and if not then it is with the new room list.
