### ISSUE TITLE
Update security info page

### ISSUE THREAD

**Issue by Otto-AA** [vector-im/riot-web#8401]
### Description

The [Security info page](https://about.riot.im/security/) seems out of date. It would be useful for people like me, if this is kept up to date.

For example, the status of E2E-Encryption is as follows:
> As of May 2017 Riot’s end-to-end encryption is technically in beta, but this is due to some residual stability bugs and missing usability features. Once these are resolved we plan to get the full implementation security assessed and out of beta. End-to-end encryption will then be turned on by default for private conversations.

Hence, this information isn't of much help for viewers.

**Comment by turt2live** [comment]
Another @nadonomy thing that's probably @lampholder 's problem

**Comment by lampholder** [comment]
We are right now in the process for producing a new about.riot.im with all new (and accurate) content - we expect it to land this week (so I'm going to close this issue - a tiny bit prematurely perhaps)
