### ISSUE TITLE
Can't see encryption icons in MemberInfo when the panel is at the minimum size

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8402]
![image](https://user-images.githubusercontent.com/1190097/52235763-47faf780-2882-11e9-9f27-77588aa68eed.png)

**Comment by Cadair** [comment]
I don't think I can reproduce this.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9380 (more traction)
