### ISSUE TITLE
"disable_custom_urls" prevent account registration

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8405]
- **Browser**: Firefox
- **OS**: Debian Linux

### Description

Setting `disable_custom_urls` to `true` when self-hosting Riot causes the "Create Account" page to be blank except for a "Sign in instead" button.

### Steps to reproduce

- in `config.json` set `disable_custom_urls` to `true`.
- Try to register
- Presented with no options to register.

![image](https://user-images.githubusercontent.com/1342360/52244936-8969c200-28d7-11e9-963e-6abff8eb7ec7.png)

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2571
