### ISSUE TITLE
direct manipulation radiobuttons for changing room visibility are very very sluggish

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8406]
as they don't local-echo and so wait for the server to do something. also, m.room.join_rules changes don't seem to be showing up in the timeline?

**Comment by turt2live** [comment]
Join rules have never been shown in the timeline.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2593
