### ISSUE TITLE
Unnatural placement of "Invite to this room" and "Filter room members"

### ISSUE THREAD

**Issue by neilalexander** [vector-im/riot-web#8409]
- **Browser**: Safari 12.0.3
- **OS**: macOS 10.14.3

### Description

The placement of the "Filter room members" box at the bottom-right is inconsistent against the "Filter room names" being at the top-left -- it feels unnatural and looks unbalanced. It would make more sense for it to be at the top-right. The "Invite to this room" button can return to the bottom right instead, as it is in release versions of Riot currently.

**Comment by lampholder** [comment]
Thanks for the feedback - I can confirm that this is on our designer's radar to address :)
