### ISSUE TITLE
UX issue: Two clicks required to sign in after failing to sign in with full MXID due to CORS

### ISSUE THREAD

**Issue by dkasak** [vector-im/riot-web#8412]
- **Browser**: Firefox 65
- **OS**: Arch Linux

### Description

Somewhat related to #7845 (the reproduction steps are the same). After sign-in fails with the full MXID due to CORS issues (#7875) and changing the `Username` to just the localpart to work around this, the `Sign in` button requires two clicks to work instead of just one.

### Steps to reproduce

1. Visit https://riot.im/develop/
2. Click on Advanced/Other "Find other public ..."
3. Focus the `Homeserver URL` input box.
4. Delete matrix.org, type in my HS domain.
5. Focus `Username` input box and enter full MXID.
6. Focus `Password` input box and enter password.
7. Click on `Sign in`; this fails due to CORS errors (expected).
8. Focus Username input box again and edit it to contain only the local part of the MXID.
9. Without clicking anywhere else, click on `Sign in`.

# Expected behaviour

Riot signs in.

# Actual behaviour

Riot ignores the click. It only signs in after an additional click on `Sign in`.

**Comment by aaronraimist** [comment]
Hmm I cannot reproduce this anymore.

**Comment by jryans** [comment]
@dkasak Does it also seem fixed on /develop for you as well?

**Comment by dkasak** [comment]
Yes, I can't reproduce it anymore either.
