### ISSUE TITLE
would be amazing to scroll the room list without having to focus on it

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#8413]
I think this is a regression because I've only be bitten by it recently and the timeline works. I have another window in focus, put my mouse over the room list and try to scroll but it doesn't

**Comment by lampholder** [comment]
@AmandineLP can you reproduce this? I can scroll riot in the background on chrome and firefox (on mac os)

**Comment by lampholder** [comment]
Closing since I've not been able to reproduce
