### ISSUE TITLE
Encourage self-hosting and simplify using custom HS.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [vector-im/riot-web#8414]
Matrix aspires to have a well balanced ecosystem of smaller servers avoiding the common problem of federation. Hence this issue.

Right now to use a custom homeserver you have to do extra steps and now that these steps exist and are required, this creates a very bad UX for those not using matrix.org or modular.im.

I don't think the server option should be hidden, if anything it could be marked as 'optional', so that people don't fill it if they don't need it, but to not discourage decentralization.

Identity server is a bit problematic as it's still closed source. I think it should default to the same value as homeserver url, this would provide expected behavior in all use cases except when wanting to use vector.im with another HS, but that should require manual action anyway.

The secondary issue is promoting modular, but since Riot is developed by New Vector, I guess I don't care that much.

**Comment by jryans** [comment]
I think I agree with the sentiment you are expressing, but I am not sure what concrete change you'd like to see here. Please provide more specific, actionable info with a single problem per issue.

**Comment by t3chguy** [comment]
@gerg5c42g542g2c54g52c identity server is not closed source at all, sygnal and mxisd are two open source code bases implementing the Identity server APIs

**Comment by gerg5c42g542g2c54g52c** [comment]
It's even worse now - "Sign in to matrix.org   Change", the option to use another server is hidden and hard to find.

@jryans I'm not sure what more do you want. Should I design the whole login page? Then you'll tell me you don't like it and my work is wasted. I'm not a designer nor do I work for New Vector, I can't just do that.

The specific change I want to see is encouraging the use of other homeservers. This not being the case is the problem with the current design reported here. I think that's as specific as it gets. The other part of my initial post is merely an attempt to try to find a right solution and initiate a discussion on what it should be.

> I don't think the server option should be hidden, if anything it could be marked as 'optional', so that people don't fill it if they don't need it, but to not discourage decentralization.

What about this?

**Comment by jryans** [comment]
> It's even worse now - "Sign in to matrix.org Change", the option to use another server is hidden and hard to find.

This is not specific to matrix.org, it just uses the default HS for the Riot install. If you self-host Riot, you would likely set a different default HS, and that's what would appear there.

> The specific change I want to see is encouraging the use of other homeservers. This not being the case is the problem with the current design reported here. I think that's as specific as it gets. The other part of my initial post is merely an attempt to try to find a right solution and initiate a discussion on what it should be.

"encouraging the use of other homeservers" could take many forms. The current design attempts to simplify accessing the default HS for a Riot install. You can also make use of `.well-known` if you are HS supports it by logging in with a full MXID `@localpart:server.name`, and the login page will adjust the HS appropriately.

**Comment by gerg5c42g542g2c54g52c** [comment]
It's good that there's a default server option, but what's the default HS for Riot desktop? That can't be set and this is really bad UX. How am I supposed to explain everyone that they should go to https://riot.im (both riot.im/app and the apps default to matrix.org and don't make the change needed obvious) and use non matrix.org HS?

This is the usual UX I experience that goes something like this:
A: Hey, how about we keep in touch? I use this cool app.
A: Wait, no, go back, you have to disable this, untick that and don't forget to do this too, you have to do this one every time, remember.
B: Oh.. ahh, do you have Facebook?

Also, self hosting Riot isn't the safest thing to do (one has to secure that Riot, no, people don't just know how to do this) and it's useless for an average user.

**Comment by t3chguy** [comment]
> A: Wait, no, go back, you have to disable this, untick that and don't forget to do this too, you have to do this one every time, remember.

There is nothing you have to do *every time*
If your HS has `.well-known` set up then for Login it'll dynamically gather what HS you want to use, but obviously, for making an account it has no way of doing so unless you tell it.

> You can also make use of `.well-known` if your HS supports it by logging in with a full MXID `@localpart:server.name`, and the login page will adjust the HS appropriately.

**Comment by gerg5c42g542g2c54g52c** [comment]
> There is nothing you have to do _every time_

That was just an example, but to be honest Riot isn't an exception to this rule. Fe. constant nagging to enable analytics, but there's more.

You mean MSC1708? How does this solve the problem? The problem is: I open riot.im/app, I want to use otherhs.tld, but I'm discouraged to do so. Unless I misunderstand in which case please explain, .well-known is a completely different thing, it's an alternative to SRV.

**Comment by gerg5c42g542g2c54g52c** [comment]
@jryans @t3chguy Oh, I see, one can use the full MXID to as username, no need to click 'Change' next to the homeserver name.

There are a few problems with the login page in v1:
- it says 'Sign in to matrix.org' - this discourage use of other HS and therefore decentralization and self hosting
- the 'Username' field doesn't indicate to the user what should be entered there, there should be an example just like with logging using Email or Phone, fe. if one chooses to use email to login, an example is shown 'joe@example.com'. The same should be done in the case of Username, an example should be shown, fe. '@joe:example.com'.
