### ISSUE TITLE
Desktop app: Zoom is no longer working after 0.17.9 update

### ISSUE THREAD

**Issue by pravi** [vector-im/riot-web#8416]
### Description

Control ++ was able to zoom riot before update to 0.17.9, but after update, it does not work and I have to stick with very small fonts. There is no option to increase font size either.

### Steps to reproduce

After launching riot, try to zoom by pressing control ++

Nothing happens to text size.

Log: sent/not sent? 

No logs.

### Version information

- **Platform**: desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Debian unstable/sid
- **Version**: 0.17.9

**Comment by jnaulty** [comment]
I'm also experiencing this issue after updating to this version.

* **OS**: Ubuntu 18.04
* **Version**: 0.17.9

**Comment by rubo77** [comment]
Did you try Ctrl shift+ ?

**Comment by pravi** [comment]
@rubo77 that also does not work.

**Comment by aaronraimist** [comment]
Hopefully will be fixed by https://github.com/vector-im/riot-web/pull/8381

**Comment by aaronraimist** [comment]
Can you test this again? Should be fixed by 1.0.0

**Comment by rubo77** [comment]
I tested it and it works fine as expected on Ubuntu: CTRL+ zooms up and the setting stays over restarts of the program.

I guess, then it is fixed on Debian too.

**Comment by pravi** [comment]
Yes, fixed on debian as well. Thanks!
