### ISSUE TITLE
Visibilty of community filter panel (LLP) does not respond to changing the setting in settings.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8418]

**Comment by aaronraimist** [comment]
Hmm... it does but only after 2 refreshes

**Comment by turt2live** [comment]
2 refreshes, or resizing, or sacrificing a goat in my experience. I think you just have to get lucky enough for it to cause a re-render and persist a sync.

**Comment by 532910** [comment]
works for me with 1.4.2
thank you!
