### ISSUE TITLE
Encryption icon pushes composer out of alignment with the rest of the timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8426]
![image](https://user-images.githubusercontent.com/1190097/52374919-b9ba7900-2a1b-11e9-8cd0-c8264b0fcf8c.png)

This is very distracting, and I haven't been able to adapt in the week or so it has been around.

**Comment by lampholder** [comment]
Hmm, I hadn't actually noticed, but now that I have I can't _unnotice_ it.

**Comment by jryans** [comment]
I spend a while pixel tweaking the unencrypted layout to be aligned, and I think it's quite nice visually to have that alignment between composer input and timeline.

With these new encryption icons, it's less clear how to achieve it. Can we move the icon somewhere else...?

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by yannicka** [comment]
The new composer doesn't seem to have that problem:

![image](https://user-images.githubusercontent.com/22885898/82581340-be635c00-9b90-11ea-86c9-273f866f33de.png)
