### ISSUE TITLE
Update warning shown when resetting password now that key backup exists

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8430]
I assume this "has been improved" once key backup is enabled:

![image](https://user-images.githubusercontent.com/279572/52403149-f5a61a80-2abd-11e9-9fc6-3900cc1cfe00.png)

**Comment by lampholder** [comment]
Ooo, old UX is old! Fixit!

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9432 (more defined UX)
