### ISSUE TITLE
We can no longer click on warnings on E2E timeline msgs to view the E2E details about an event.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8441]
This is a pretty major regression - i can no longer see which device a user used to send me a msg!

Given we've taken away the green padlocks, there's not even an icon for me to click.

Can we reintroduce it as clickable from the red `(!)` warnings, and also add it to the context menu for the event tile?

Also, can we shift to using a Tooltip component rather than an HTML tooltip for the (!) warnings, so the tooltip is larger and appears more rapidly?

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2620
