### ISSUE TITLE
Filtering the LeftPanel by text should ignore any filtering by communities, imo.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8442]
I expect the filter search to search *all* my rooms, regardless of whether the LLP is filtering stuff by communities or tags.

I guess this is because I use filter search a bit like Spotlight or other services and expect it to search eeeeeeeeeverything.

@lampholder wdyt?

**Comment by bwindels** [comment]
would it clear your community filter if you picked a room not in your community then?

**Comment by ara4n** [comment]
i don’t think so? you’d just view the picked room, the leftpanel would still be filtered, the community filter would still be there but idle until you pick the leftpanel?

conversely, i wonder if clicking community whilst filtered should reset the filter...

**Comment by lampholder** [comment]
👍 

I think it might be even better if there were some visual indicator differentiating between rooms which are in/out of my current communities filter, but that's only an optimisation - it would work well without I think.

**Comment by ara4n** [comment]
i find this a major obstacle to using communities btw; it's really jarring that clicking on a community with a badge notif often doesn't work because there's already a text filter in place.  And conversely really jarring that searching for a room often doesn't work because we're already filtered on a community.

**Comment by bwindels** [comment]
> i don’t think so? you’d just view the picked room, the leftpanel would still be filtered, the community filter would still be there but idle until you pick the leftpanel?

Right, and when you clear your filter, you'd just be in a room that is currently not displayed in your left panel because of the community filter, which is fine I suppose.

**Comment by t3chguy** [comment]
This was explicitly not done in the new room list.
