### ISSUE TITLE
Minimized sidebar could be minimized further

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8443]
![image](https://user-images.githubusercontent.com/1342360/52414482-652b0280-2adc-11e9-848c-d41df378aae0.png)

Currently the minimized sidebar is about 1.5x-2.0x as wide as it needs to be, in order to support the unread notifications badge.

Instead, we could move the badge closer/onto the room icon (similar to where the `+` button is currently).

**Comment by aaronraimist** [comment]
Fixed
