### ISSUE TITLE
Community menu overlaps unread messages badge

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8445]
![image](https://user-images.githubusercontent.com/1342360/52416926-a0303480-2ae2-11e9-97a5-68a2b9be5830.png)

Chromium, Debian Linux

* Have unread notifications in a community
* Right-click/click menu icon
* See overlap

**Comment by lampholder** [comment]
I'm going to close this because we have 3293 open issues and I think this... isn't big enough to track :)
