### ISSUE TITLE
People unaware that a room was upgraded if they don't actively check it

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8447]
### Description

If a user is in a room but doesn't actively check it (room is on `mentions-only` perhaps) and it gets upgraded, there really isn't any mechanism for informing them that an upgrade occurred.

With my UX hat on, I'd probably put a regular (non-bing) notification on the room (unless room is set to bing?), that instead of a number, has the upgrade icon in it.

People are suffering from this in the wild though.

**Comment by lampholder** [comment]
Ah, becuase they have notifications set to alert on mentions, but nobody's mentioning them 'cause they're all chatting away in the upgraded version of the room that you're not in?

So yes, Riot should translate the tombstone event into an alert of some kind that appears on the roomlist.

It wouldn't be too awful if we just counted the tombstone as a binging notif and skipped the upgrade-icon-in-the-roomlist business to get a fix out quickly.

**Comment by anoadragon453** [comment]
> It wouldn't be too awful if we just counted the tombstone as a binging notif and skipped the upgrade-icon-in-the-roomlist business to get a fix out quickly.

I'm all for this idea.

**Comment by turt2live** [comment]
[MSC1930](https://github.com/matrix-org/matrix-doc/pull/1930) has been opened to drive this through for everyone else in the ecosystem.

If we decide that we want to do something more special for upgrades (dialog, setting off a screeching alarm, flashing the entire UI until you click a button, etc) then there's room to do so in the MSC.
