### ISSUE TITLE
Unable to login to ANY custom homeserver using riot (web or desktop)

### ISSUE THREAD

**Issue by chresan** [vector-im/riot-web#8451]
It is not possible any more to login to ANY custom homeserver using the desktop version of Riot (v0.17.9) or the riot client located at https://riot.im/app/

The client reports the message: "Invalid homeserver discovery response"
(I have configured .well-known/matrix/client according to the docs)

I've tried with other homeserver login names and they all have the same problem.

**Comment by chresan** [comment]
This is not an issue. (Script blocker on a new computer interfered). Sorry mistake on my end.

**Comment by r4dh4l** [comment]
Sometimes it is related to https://github.com/vector-im/riot-web/issues/7845 and then it helps to use just the local part of the Matrix ID as username, so `alice` for the MXID `@alice:example.com`.
