### ISSUE TITLE
Jump to bottom button is missing if uBlock Origin is on

### ISSUE THREAD

**Issue by evoL** [vector-im/riot-web#8453]
- **Browser**: Chrome 72.0.3626.81 
- **OS**: Debian Testing

### Description

The jump to bottom bottom is missing on https://riot.im/develop.
When there are new messages, only the number appears, but is not clickable. I see https://github.com/vector-im/riot-web/issues/7592 is closed; is it live?

### Steps to reproduce

not applicable

Log: not sent

**Comment by turt2live** [comment]
It should be on the right side of the timeline. Is it missing for you?

**Comment by evoL** [comment]
Yes, it's missing, but I think I know the cause.

I'm using uBlock Origin with cosmetic filters on and it turns out they remove the button. If I disable "cosmetic filtering", the button appears again.

As I think more people use adblockers, this might be useful to fix. Here's the CSS rule that uBlock Origin applied that made the button disappear on my side: https://0bin.net/paste/lHv6j90ksvOpN5rU#-LMIEJoaXKROEdZ70tAoOf+kDtKssa0BRafzEDzUNDx

**Comment by evoL** [comment]
Actually, now that I think about it, it's not Riot's issue, but the blocklist's. Closing this.
