### ISSUE TITLE
No way to remove avatars from user/room settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8456]
Previously we had a red X floating on the edge of the avatar in the settings. This caused confusion as to what this does as people thought it was a close button. We should consider not using an X and maybe use the literal word "remove" under the avatar.

**Comment by t3chguy** [comment]
Or a 🗑

**Comment by Thatoo** [comment]
Getting back a [new] system to delete avatar is important, at least in direct chat for the two "chatter" to be able to get back each other's profile picture as their direct chat room's picture.

**Comment by nadonomy** [comment]
Updated our (internal) Zeplin with a proposal: [https://zpl.io/a759PvY](https://zpl.io/a759PvY)

Essentially, changing the hover text contextually, and providing the option to remove with a context menu:

<img width="767" alt="Screenshot 2019-05-02 at 18 27 06" src="https://user-images.githubusercontent.com/4626865/57094770-3c945c80-6d09-11e9-8084-9a20c1adcc2d.png">

(Note that this comp is using our old palette as it's from a legacy source file)

**Comment by t3chguy** [comment]
context menu in modal is surprisingly finnicky, all clicks inside the context menu get ignored for some reason :((

**Comment by turt2live** [comment]
@t3chguy There's a whole comment somewhere saying "GAHHHH LAYERING!" or something along that lines - may have to take a peek at how that works. I think the example was the "Copied!" text for the share dialog.

**Comment by t3chguy** [comment]
I narrowed it down to the focus trap in BaseDialog, the copied in share dialog I did a long time back and it does no click handling so is unaffected.

Any chance you could explain why we need this focus trap thingy? I seem to be missing the point

**Comment by t3chguy** [comment]
Chrome's inspector being able to breakpoint all mouse click handlers is infinitely useful, also kinda scary that all my clicks get sent to my chrome extensions, should really investigate which extension was installing a global click handler.

**Comment by t3chguy** [comment]
So some combination of
+ magic from https://github.com/theKashey/react-focus-lock/issues/19
+ switch to https://github.com/theKashey/react-focus-lock

should help here

**Comment by turt2live** [comment]
> the copied in share dialog I did a long time back and it does no click handling so is unaffected.

Although it does no click handling, the layering of context menus (and thus tooltips) was changed recently. Suspected it to be something strange in the element having a high z-index but the click being under a transparent pane.

**Comment by t3chguy** [comment]
It isn't that, I tested with an anchor tag and left click didn't work but middle click opened a new tab. I am 100% certain this is focus trap capturing the click before react propagates it, I verified this by stepping through the code.

It's because focus trap checks to see if the click was inside the trapped dom element but context menus and modal are portals so live in their own DOM trees.

**Comment by t3chguy** [comment]
This should be easier after https://github.com/vector-im/riot-web/issues/10697

**Comment by florian2833z** [comment]
Any updates??

**Comment by t3chguy** [comment]
I am soon rewriting context menus for accessibility purposes, this might unblock this but it is not guaranteed

**Comment by florian2833z** [comment]
May I ask why this was even removed in the first place?

**Comment by turt2live** [comment]
The design was changed, and was likely just an oversight.

**Comment by t3chguy** [comment]
Rewriting context menus simplified this due to React Portals
