### ISSUE TITLE
Improve room directory content

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8462]
With the changes being made to home & welcome, we should improve the content of the room directory to aid discoverability.

**Comment by ara4n** [comment]
the content side of this is mitigated to some extent by https://github.com/matrix-org/synapse/pull/4647 (and deployed on matrix.org to remove some of the more insalubrious rooms from the published list)

**Comment by nadonomy** [comment]
@lampholder did you add `needs-design` to this issue erroneously or am I missing some context? This issue was meant to only address the content that populates the room dir.

**Comment by lampholder** [comment]
Yep, looks like I misapplied the label, sorry.

**Comment by jryans** [comment]
Is this done then, with the Synapse-side mitigations? Or is there more we plan to do here?

**Comment by nadonomy** [comment]
Yep, I believe done. Considering there's no riot work, and the synapse updates are deployed I'll close.
