### ISSUE TITLE
Clicking 'invite to chat' in the memberinfo panel doesn't work?

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8467]
TypeError: s is undefined[Learn More] Avatar.js:58:9
    defaultAvatarUrlForString Avatar.js:58
    _getState BaseAvatar.js:118
    _getState (index):974
    getInitialState bundle.js:88628
    Constructor factory.js:839
    React 4
    mountComponent bundle.js:339375
    React 2
    mountComponent bundle.js:339445
    React 14
    mountComponent bundle.js:339445
    React 6
    mountComponent bundle.js:339445
    React 4
    updateChildren bundle.js:345531
    React 2
    receiveComponent bundle.js:340937
    React 4
    receiveComponent bundle.js:339734
    React 4
    updateChildren bundle.js:345531
    React 2
    receiveComponent bundle.js:340937
    React 4
    receiveComponent bundle.js:339734
    React 11
    flushBatchedUpdates (index):974
    React 4
    enqueueUpdate bundle.js:347258
    enqueueSetState bundle.js:347452
    setState React
    onAction MatrixChat.js:700
    onAction (index):974
    _invokeCallback Dispatcher.js:200
    dispatch Dispatcher.js:176
    dispatch (index):1016

**Comment by lampholder** [comment]
Hmm, the invites did actually go through - looks like maybe the roomlist just didn't update. Refreshing made the DM appear.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2601
