### ISSUE TITLE
mx_Field requires you to click after the label if no placeholder is used in order to enter text

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8469]
`<Field id={"one"} type={"password"} label={"Enabled Password"}/>` for instance doesn't let you click the input to type something

**Comment by turt2live** [comment]
Actually this was a misinterpretation of a bug.

![image](https://user-images.githubusercontent.com/1190097/52492276-15a11100-2b86-11e9-8273-8cc4622f1527.png)

Pink box denotes where to click in order to actually enter a value

**Comment by turt2live** [comment]
Even worse, it selects the wrong input when you click it:
![label-click mp4](https://user-images.githubusercontent.com/1190097/53130696-383d0d80-3528-11e9-9269-63768e008cad.gif)

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2714
