### ISSUE TITLE
inline mx_Field selects have their arrow well outside of the input

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8471]
![image](https://user-images.githubusercontent.com/1190097/52492629-cc04f600-2b86-11e9-9f48-79a71c4e47eb.png)

**Comment by lampholder** [comment]
Hey @turt2live - is this affecting live UX anywhere, or otherwise affecting development?

**Comment by turt2live** [comment]
This is probably p5 maintenance. Not affecting anything live, just some very assuming code we have.

**Comment by lampholder** [comment]
This doesn't seem still to be a problem - @turt2live does the fact that these options in user settings look good mean that this is fixed?

![image](https://user-images.githubusercontent.com/1922197/56959355-13c36a00-6b45-11e9-925a-c259c303a7a4.png)

**Comment by turt2live** [comment]
As per https://github.com/vector-im/riot-web/issues/8471#issuecomment-472894305 we don't have anything that uses them in this way, just some code that assumes we won't.
