### ISSUE TITLE
Redesign: Opening direct room link while not logged in is now broken

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/riot-web#8476]
- **Browser**: Chrome 67
- **OS**: Windows

### Description

On the develop branch, attempting to join a room via a room link while not logged in no longer works. It says "Click Here to join the discussion", but "Click Here" no longer does anything. It used to prompt you to choose a new username, with the option to also login if you already have an account.

### Steps to reproduce

Make sure your browser is not logged in by clearing the cookies, then attempt to join a room via a direct room link. 

Example: https://riot.im/develop/#/room/#test:matrix.org

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2611
