### ISSUE TITLE
Logging in via new Welcome screen redirects back to welcome screen

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/riot-web#8477]
- **Browser**: Chrome 67
- **OS**: Windows

### Description

Logging in via the new Welcome page immediately brings me back to the welcome page again after the login attempt

### Steps to reproduce

- Go to https://riot.im/develop/#/welcome
- Click Sign In
- Enter username and password
- Click Sign In
- Riot now immediately goes back to https://riot.im/develop/#/welcome. The only way to get into the application is to put a direct room link in the address bar (example: https://riot.im/develop/#/room/#test:matrix.org)

**Comment by jryans** [comment]
Thanks for the report! This has been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2603.
