### ISSUE TITLE
Blank page after logging in to /staging

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8479]
![image](https://user-images.githubusercontent.com/1190097/52501738-49883080-2b9e-11e9-82cf-9b47fc7bc6a6.png)

**Comment by ara4n** [comment]
presumably this is just because we're not specifying a home.html equivalent any more?

**Comment by turt2live** [comment]
yup, I think the decision was that some room should be opened instead (I can't remember the heuristic for which one though).

**Comment by jryans** [comment]
We should decide what we want to do here. @lampholder, any thoughts?

**Comment by jryans** [comment]
We don't seem to have a last room stored after you log out, so maybe something like first room in the list or most active room would make sense here.

**Comment by dbkr** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2637
