### ISSUE TITLE
SAS verification failures

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8482]
Tracking issue for SAS failure things. See related issues/rageshakes.

**Comment by lampholder** [comment]
This only seems to be tracking one issue in the end - @turt2live are you happy to close this (and track any future bugs with SAS verification by adding the `feature:e2e-sas-verification` label)?

**Comment by turt2live** [comment]
> @turt2live are you happy to close this (and track any future bugs with SAS verification by adding the feature:e2e-sas-verification label)?

yes
