### ISSUE TITLE
reports of email validation being broken

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8490]
and the validation link taking you to a blank page?

**Comment by robertandrewblackburn** [comment]
yep, I'm having this issue now. Can't open an account...

**Comment by jryans** [comment]
Where did you begin registering? On /develop, /app, or somewhere else?

**Comment by robertandrewblackburn** [comment]
Through the desktop client (d/l'd from https://riot.im/desktop.html)

Though from what I understand that's just an electron app wrapping the web client?

**Comment by dbkr** [comment]
I've just got an issue where the registration doesn't continue properly on the browser you clicked the email link on, so let's stick these two in the same bucket...
