### ISSUE TITLE
Ctrl+K doesn't work

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#8495]
### Description

The [riot-web shortcut doc](https://github.com/vector-im/riot-web/blob/master/docs/shortcuts.md) shows <kbd>Ctrl</kbd>+<kbd>K</kbd> as jump to named room, but it doesn't work.

### Steps to reproduce

- Hit <kbd>Ctrl</kbd>+<kbd>K</kbd>
- Nothing happend

Log: not sent    

### Version information

- **Platform**: desktop
- **OS**: Fedora 29, Flatpak install
- **Version**: 0.17.9

**Comment by jryans** [comment]
This appears to work on riot.im/develop on macOS, so the issue may be specific to desktop.

**Comment by MightyCreak** [comment]
Maybe it's a feature from the new GUI refactor?

**Comment by t3chguy** [comment]
Control K as a shortcut to the room list filter was added quite some time ago, definitely way before the new GUI Refactor

**Comment by MightyCreak** [comment]
Oh, my bad. I was expecting a popup where I could enter some text and see the matching rooms. I've seen that the cursor is actually changing focus to the search field in the top-left corner.

I must say it's a bit subtle, but now I know what to expect ;)

Closing it since it's not a bug.
