### ISSUE TITLE
Jump to bottom button is missing when returning to an upgraded room with lots of history

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8503]
Switching from old watercooler to new watercooler using the 'The conversation continues here' button leaves you at the top of the timeline (expected) with no alternative but to manually scroll down (not expected). After scrolling down a little bit, the button shows up

**Comment by lampholder** [comment]
How much is a little bit? How likely is an average user to notice?

A lot of people are going to have this experience once rooms start getting upgraded, so if it's reasonably weird and disruptive this might still be worth keeping on fire.

**Comment by turt2live** [comment]
a single step of the scroll wheel is enough, but it is awkward that you're at the top of the timeline with no way down until you try and do something. I suspect this might also be a bug outside of upgrades if you were to permalink someone to ancient history or search results.
