### ISSUE TITLE
Can't login to a numeric .XYZ domain.

### ISSUE THREAD

**Issue by commagray** [vector-im/riot-web#8504]
Hi! Something strange happens.

I have a domain https://092918.xyz with Synapse 0.99 on them. According to https://092918.xyz/_matrix/client/versions and https://092918.xyz:8448/_matrix/client/versions it says it works. https://neo.lain.haus/fed-tester/ says everything is OK too. Firefox shows a valid cert for the domain.

But if I'm trying to login via Riot it says the next thing:
> Can't connect to homeserver - please check your connectivity, ensure your homeserver's SSL certificate is trusted, and that a browser extension is not blocking requests.

Although I can browse (empty) room list via Riot from other account on matrix.org domain. I can even login via curl:
```
[commagray@CANTERLOT-WIN ~]$ curl -XPOST -d '{"type":"m.login.password", "user":"commagray", "password":"password"}' "https://092918.xyz/_matrix/client/r0/login"
{
    "access_token": "longsecretstring",
    "device_id": "BKKLEERTXU",
    "home_server": "092918.xyz",
    "user_id": "@commagray:092918.xyz"
}
```

Is that a problem with my server or Riot?

**Comment by turt2live** [comment]
Which version of Riot is giving you the issue? A quick test on my part shows that your server seems to be interacting just fine with riot.im/develop

**Comment by commagray** [comment]
Oh, sorry. I forgot to mention that I use https://riot.im/develop on Firefox Nightly on Windows 10. And /app shows the same thing.

**Comment by turt2live** [comment]
From the javascript console, can you send `mxSendRageshake("https://github.com/vector-im/riot-web/issues/8504")` after attempting login please? This will send debug logs to us which might be of help.

For reference, here's what they send:
> Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users. They do not contain messages.

**Comment by commagray** [comment]
Oh, it seems to be Firefox issue.
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://092918.xyz/_matrix/client/r0/login. (Reason: CORS request did not succeed).[Learn More]

Tried in Chrome Canary and it works fine. Too much restrictions in my settings, I guess.
