### ISSUE TITLE
Implement improved palette

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8505]
With new brand colours & improved contrast/legibility for accessibility.

**Comment by jryans** [comment]
@nadonomy Is this one about applying the updated palette to the existing dharma (soon renamed to light) theme?

**Comment by nadonomy** [comment]
@jryans yeah, I hastily created this at the start of the week to ensure we don't forget it. If you have a more relevant issue now feel free to close.

**Comment by jryans** [comment]
- [x] Accent
- [x] Notice
- [x] Notice secondary
- [x] Avatars
- [x] Usernames
- [  ] Default theme values

**Comment by jryans** [comment]
We'll update the default them values to match the palette after release.

**Comment by jryans** [comment]
I'll keep this for a moment to do a quick scan over the default theme color values, then leave any remaining tweaking as separate work.

**Comment by jryans** [comment]
Made a few tweaks in matrix-org/matrix-react-sdk@b7cb16242bcb59ce16df0db8d640d77153992116.
