### ISSUE TITLE
Design & implement a better collapsed room list state

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8507]
Currently there's an awkward negative space to the right of room list icons. We should explore:

1/ Finding a place for the (+) icons that doesn't create a negative space gutter
2/ Exposing the first few characters of room names and/or room sections
3/ Retaining room filter

EDIT: Screenshot from dupe issue #8652:

https://user-images.githubusercontent.com/184066/52812297-31397980-30a8-11e9-9f19-6627778dd142.png

**Comment by ara4n** [comment]
c.f. https://fairground.moe/@ghost/101578589688650543

**Comment by lampholder** [comment]
Should also address https://github.com/vector-im/riot-web/issues/8244

**Comment by turt2live** [comment]
Reminder to address https://github.com/vector-im/riot-web/issues/9389

**Comment by turt2live** [comment]
The new room list is better at this.
