### ISSUE TITLE
Squished avatar with collapsed room list

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8517]
![image](https://user-images.githubusercontent.com/1342360/52557030-264fc200-2de6-11e9-8f7c-10c3dd882287.png)

- **Browser**: Chrome
- **OS**: Debian Linux

### Description

I believe this happens after the room list has been closed for some time. I don't have a clear set of steps for reproduction, but this is the second or third time I've seen this happen already.

Somehow the little dropdown arrow is no longer hidden and is thus squishing everything in the upper menu together.

**Comment by t3chguy** [comment]
I'm fairly certain this is fixed by https://github.com/matrix-org/matrix-react-sdk/commit/a3eb45e0b9c3a6261b861f7fb3a2178b75b1c511
