### ISSUE TITLE
Add configurable welcome background image and logo options to config.json

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8526]

**Comment by jryans** [comment]
Added to develop in #8528. You can use the following `config.json` options:

1. `branding`: Configures various branding and logo details, such as:
    1. `welcomeBackgroundUrl`: An image to use as a wallpaper outside the app
       during authentication flows
    1. `authHeaderLogoUrl`: An logo image that is shown in the header during
       authentication flows
