### ISSUE TITLE
Voice & Video settings icon is cut off

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8527]
- **Browser**: Chrome
- **OS**: Debian Linux

![image](https://user-images.githubusercontent.com/1342360/52575744-a726b200-2e16-11e9-9b08-f5d6f77d0344.png)

### Description

The voice & video icon is slightly cut off at the sides.

**Comment by anoadragon453** [comment]
This seems to be a problem with the Flags icon as well.

![image](https://user-images.githubusercontent.com/1342360/52575808-c7567100-2e16-11e9-94c2-935f4939448f.png)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8578
