### ISSUE TITLE
Autocomplete doesn't respond to select & delete events

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#853]
I started typing something, autocomplete appeared, I cut my text and autocomplete stayed visible. I had to start typing again to remove it

![image](https://cloud.githubusercontent.com/assets/8582858/12778139/701c01fa-ca61-11e5-9195-77aac207033d.png)

**Comment by aviraldg** [comment]
@ara4n fixed with new autocomplete

**Comment by t3chguy** [comment]
Fixed indeed
