### ISSUE TITLE
[Question] What exactly are Integrations?

### ISSUE THREAD

**Issue by nunoperalta** [vector-im/riot-web#8533]
I saw many issues here about "Integrations" and apparently everyone knows what they are about :)

But... I'm completely lost here.

What exactly are Integrations, those that we set up in "integrations_*_url" ?
What is the purpose of them?
What do I lose if I disable Integrations?

**Comment by lampholder** [comment]
Integration are bots, bridges and widgets that you can add to a room in matrix. They are managed by a separate piece of software, the 'integrations manager'. Today I know of two integrations managers - Scalar (the New Vector proprietary implementation that provides integrations for matrix.org) and [Dimension](https://github.com/turt2live/matrix-dimension) an open source implementation.

Bots are fairly self-explanatory, widgets are small web applications you can embed into the matrix client experience (such as a jitsi video conference, or a google doc, or etherpad). Bridges connect matrix to external platforms such as IRC or Slack or Gitter.

The integrations_*_url config is (I think) associated with connecting your client to an integrations manager.

If you're using https://riot.im/app connecting to matrix.org you'll be able to try out all of the integrations - click the four squares icon in the top right:
![screenshot 2019-02-19 at 12 17 09](https://user-images.githubusercontent.com/1922197/53014622-ea99a580-3440-11e9-832a-3e371600770d.png)

and you'll get a modal window to add and configure integrations:
![screenshot 2019-02-19 at 12 17 28](https://user-images.githubusercontent.com/1922197/53014641-f5ecd100-3440-11e9-9fd4-c94c338c0172.png)

**Comment by nunoperalta** [comment]
@lampholder Perfect explanation! Thank you very much.

**Comment by purjolini** [comment]
What is the specific setting to get rid of BOT SETTINGS "You need to be able to invite users to do that."? Can't invite any giphy,google,guggy etc bots.

**Comment by TwoTwenty** [comment]
> What is the specific setting to get rid of BOT SETTINGS "You need to be able to invite users to do that."? Can't invite any giphy,google,guggy etc bots.

I am in the same boat.
