### ISSUE TITLE
Maximise chances of positive first impressions (esp. for small screens) by choosing sensible sizes/default collapsedness for UX elements after switching to new Riot

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8534]
We've had some feedback that new Riot performs badly on small screens.

I'm on a 2014 macbook air, and my smallscreen experience has actually been pretty good, though I've achieved that by making some tweaks.

It strikes me that we could maximise the chances of a positive reception (esp. for users on small screens) by:

- collapsing LOW PRIORITY by default
- collapsing INVITES by default
- minimising the width of the room list (mine feels pretty good at ~230px)
- minimising or perhaps hiding the memberlist panel by default on smaller screens (the minimum width of ~250px feels okay, but its not being visible at all feels better)

**Comment by turt2live** [comment]
We removed letterboxes.
