### ISSUE TITLE
Consider implications of showing the old room when leaving the upgraded room

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8539]
Opening this as a UI issue to propagate to the other projects as needed.

There's some concern that leaving an upgraded room magically makes the old room appear in the room list, which could confuse people. Instead, maybe we should be leaving the chain of rooms?

**Comment by lampholder** [comment]
Ugh, yes, I hadn't considered that.

**Comment by anoadragon453** [comment]
Just confused by this today.

**Comment by lampholder** [comment]
I don't think we expect regular users to understand the mechanisms underpinning room upgrades. Therefore, it is highly unlikely that when a regular user chooses to leave a room that happens to be upgraded, they're _intending_ to leave the newer version and remain a member of the old version.

My opinion is that we should honour users' _intention_ and leave all versions of the room at once.

**Comment by lampholder** [comment]
This didn't seem to work when I tested just now on the test server/riot instance you provisioned for me @turt2live :\

**Comment by lampholder** [comment]
Inasmuch as, I `/part`ed the new room, and the old room popped back into the room list

**Comment by lampholder** [comment]
Stand down: I'm an idiot.
