### ISSUE TITLE
Clicking on a third party invite in the room members list has no effect

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#854]
When you mouse over such member, a chevron is displayed beside their display name, suggesting we can click on it. But nothing happen on click.

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/4667 means that the chevron is no longer there at least, but still no MemberInfo available for these.

**Comment by t3chguy** [comment]
It does now 
![image](https://user-images.githubusercontent.com/2403652/71366563-31dd4f00-259a-11ea-9dd8-58890f1be452.png)
