### ISSUE TITLE
breadcrumb refinements

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8548]
we should use Tooltip rather than HTML tooltips to show the room names, so you don't have to wait ages for the HTML tooltip to appear.  Also, we should allow the list to be horizontally scrolled (as the grey gradient on the RHS implies)

**Comment by AmandineLP** [comment]
Maybe we should also display the space for breadcrumbs only when the first room is here to populate it

**Comment by AmandineLP** [comment]
Also, for tracking: the room should move up when we view it rather than when we move away

**Comment by AmandineLP** [comment]
Potential idea for later: add a red/grey dot when new msg came in the room

**Comment by lampholder** [comment]
also (from https://github.com/vector-im/riot-web/issues/8549) breadcrumbs should persist over refreshes

**Comment by turt2live** [comment]
I've broken this out for easier tracking and bug squashing:
* https://github.com/vector-im/riot-web/issues/9303
* https://github.com/vector-im/riot-web/issues/8714
* https://github.com/vector-im/riot-web/issues/8659
* https://github.com/vector-im/riot-web/issues/8606
* https://github.com/vector-im/riot-web/issues/8549
