### ISSUE TITLE
e2e context menu should not appear on non-e2e msgs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8551]

**Comment by ara4n** [comment]
i.e. the bottom line of the context menu is spurious in a non-e2e room

<img width="319" alt="screenshot 2019-02-13 at 11 20 50" src="https://user-images.githubusercontent.com/1294269/52708202-82028280-2f81-11e9-87ab-cb469ac76b7e.png">

**Comment by lampholder** [comment]
yep

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2684
