### ISSUE TITLE
room filtering doesn't show rooms who are named based on their alias?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8553]
I'm in a room with an alias of `#_xmpp_muc.xmpp.org_xsf:matrix.org`.

But trying to filter for `xsf` in the RoomList silently fails; it looks like we're only searching m.room.name or something rather than the alias?  In practice we should surely be searching based on whatever label is shown on the RoomTile in the RoomList.

**Comment by aaronraimist** [comment]
Related/dup of #2557 which is a dup of #974
