### ISSUE TITLE
Integrations Manager Error broken

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8567]
- **Browser**: Firefox
- **OS**: Debian Linux

### Description

![image](https://user-images.githubusercontent.com/1342360/52715872-6d2fea00-2f95-11e9-85f7-db7a995cb966.png)

The error for integrations is behind the button.

### Steps to reproduce

- Set an incorrect integrations manager in Riot's config.json
- See the error is borked looking

**Comment by turt2live** [comment]
it was replaced with a dialog
