### ISSUE TITLE
After setting displayname in User Settings and hitting Save, the Save button ungreys itself

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8569]
Save button should stay grey after you hit save, as there are no more changes to be saved, but it does not...

**Comment by turt2live** [comment]
This is intentional design on my part fwiw. There's not really a reasonable way for the user to realize that the values have been successfully committed, so it re-enables the button as a visual cue.

**Comment by lampholder** [comment]
I'm with Matthew on this one - the message I receive from the save button going green again is that my changes weren't persisted.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2726
