### ISSUE TITLE
Changes to displaynames in UserSettings do not immediately update the TopLeftMenu label

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8570]

**Comment by turt2live** [comment]
Applies to any profile change:
![image](https://user-images.githubusercontent.com/1190097/53611752-dd8d5c80-3b8c-11e9-87db-1a0675c3d85f.png)

**Comment by sk-alexis** [comment]
description:
After display name change the name on the top corner is not refreshed, there is the need to logout and log back in for riot to give the right updated name

the feauture requested is for riot to refresh account panel on top left, after a display name, or even profile changes for that matter.
Steps to reproduce

    go to profile settings
    change a display name
    hit save
    and notice that although in room your name is updated on the top left corner on account panel, there is still the old name.

the expect behaviour would be to riot refresh profile so updated name is displayed.

**Comment by t3chguy** [comment]
Pretty sure Travis fixed this in the new room list

**Comment by sk-alexis** [comment]
If it was fixed congratulations @t3chguy, but I actually tested on /develop and it doesnt seam to be fixed a easy way to do it though would be to close settings once a new nickname has being saved, so if I wasnt clear just add the X (close click) to the end of the Save feature/button

**Comment by t3chguy** [comment]
> but I actually tested on /develop and it doesnt seam to be fixed

![fix](https://user-images.githubusercontent.com/2403652/86522184-10ff8b80-be52-11ea-878d-85fc007c34cf.gif)


I'm not sure what the close interaction has to do with anything?
