### ISSUE TITLE
Tom signed up for a fresh account and ended up with two riotbot convos

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8574]
One was a DM, one was a room.  The DM one said nothing; the room one intro'd.

https://github.com/matrix-org/riot-web-rageshakes/issues/1215

**Comment by lampholder** [comment]
This was because I:
- signed up for a new account with email
- opened the email link on another device
- both devices decided they'd like to talk to riotbot pls

The DM one saying nothing is down to riot-bot - he won't start two tutorials with the same user
