### ISSUE TITLE
filtering roomlist by a community hides your favourites section

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8582]
filtering roomlist by a community hides your favourites section (and any rooms that are in both community and your favourites are invisible)

**Comment by turt2live** [comment]
@lampholder please use descriptive titles :(

**Comment by lampholder** [comment]
Er, obviously "issues" was a mistake :\

**Comment by t3chguy** [comment]
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/2403652/64853586-968c2380-d613-11e9-80f6-f5b0a63ec004.png)

**Comment by t3chguy** [comment]
non issue
