### ISSUE TITLE
Switch to new communities icon in Communities header

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8585]
Communities header:

![image](https://user-images.githubusercontent.com/1342360/52728111-97da6c80-2fae-11e9-86f4-f58a29fb290d.png)

and communities right-click menu:

![image](https://user-images.githubusercontent.com/1342360/52728133-a3c62e80-2fae-11e9-9d82-310e71d886e3.png)

Should presumably be using the new communities icon:

![image](https://user-images.githubusercontent.com/1342360/52728163-b04a8700-2fae-11e9-801a-27f065947f05.png)

**Comment by lampholder** [comment]
Communities is ripe for a radical redesign, so I reckon we just tackle this when we get to it
