### ISSUE TITLE
Dark theme: Impossible to tell difference between sent/not sent messages

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8586]
- **Browser**: Chrome
- **OS**: Debian Linux

### Description

Really hard to tell the difference between a sent and not-sent message using the dark theme. Here the 'z's are not sent:

![image](https://user-images.githubusercontent.com/1342360/52728450-3961be00-2faf-11e9-971e-50bf7fa32803.png)

**Comment by turt2live** [comment]
I agree it's very hard to tell, but not impossible. My fancy monitor is able to distinguish the color difference :)

**Comment by aaronraimist** [comment]
@nadonomy do you have a color for the pending messages?

**Comment by nadonomy** [comment]
> @nadonomy do you have a color for the pending messages?

Yeah. We're using A1B2D1 for secondary text throughout the theme (room topics, timestamps etc) and this should just use that.

@jryans It might be best to factor out the magic colours used for quoted messages, join/leave events to use a common secondary text variable in the base theme too?

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2665
