### ISSUE TITLE
Room pills are hard to read in new dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8587]
See below:
![](https://i.imgur.com/2g9jHxJ.png)

**Comment by jryans** [comment]
This ones needs design, I think.

**Comment by aaronraimist** [comment]
They don't look like that to me. For me the background is to dark to its hard to see there is even a pill there.
Safari 12
![screen shot 2019-02-13 at 12 01 45 pm](https://user-images.githubusercontent.com/5855073/52732970-25a26180-2f87-11e9-9384-cb6556409ca4.png)

I like the original design for pills
![screen shot 2019-02-13 at 12 04 10 pm](https://user-images.githubusercontent.com/5855073/52733120-89c52580-2f87-11e9-80e0-e06ebb79d0b7.png)

**Comment by jryans** [comment]
For now, we'll make them the room / group pills the same as user pills. It's possible we may need to tweak the color in general, though.

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2659
