### ISSUE TITLE
Should we call the Default theme the Light theme?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8590]
ref: https://matrix.to/#/!XIydWLOEJvcDBKwWKE:matrix.org/$15500785483986fGirD:cadair.com?via=matrix.org&via=disroot.org&via=matrixim.cc

**Comment by jryans** [comment]
Internally it is called "light" everywhere, so it's just the string in settings at the moment.

**Comment by lampholder** [comment]
I like that 'light' is more descriptive than 'default', so I'd say go for it

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2662
