### ISSUE TITLE
Missing spacing in Settings > Room Addresses

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8591]
![image](https://user-images.githubusercontent.com/1342360/52731139-edb21300-2fb4-11e9-8832-ee62cf7d2d83.png)

- **Browser**: Firefox
- **OS**: Debian Linux

### Description

Should probably be some spacing there like the rest of the Save buttons have.

**Comment by turt2live** [comment]
This is known to me, but apparently not reported. The whole component needs replacing

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2679
