### ISSUE TITLE
Community list in LLP has an unneeded scroll bar

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#8592]
![image](https://user-images.githubusercontent.com/1391051/52731652-24d4f400-2fb6-11e9-919b-e998c53b6618.png)

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/8197

**Comment by Cadair** [comment]
darn it, I searched for so many different things :woman_facepalming:
