### ISSUE TITLE
Rageshake dialog needs to be redesigned for the redesign

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8595]
* The issue URL is not a placeholder in the screenshot, it is a real URL
* Field alignment

![image](https://user-images.githubusercontent.com/1190097/52732992-d5270600-2f7e-11e9-8409-bb2ea6b18088.png)

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2859
