### ISSUE TITLE
Home screen text is unreadable on dark theme

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8603]
- **Browser**: Chrome
- **OS**: Debian Linux

### Description

![image](https://user-images.githubusercontent.com/1342360/52738958-be58d180-2fc7-11e9-87cf-1ac626dc3265.png)

![image](https://user-images.githubusercontent.com/1342360/52738991-da5c7300-2fc7-11e9-92e5-78f666383399.png)

- Matrix logo needs to be white
- Can't read Need Help? text
- White background for the buttons is a bit jarring

**Comment by jryans** [comment]
@anoadragon453 Is this about the home page (`#/home`) or welcome page (`#/welcome`)?

The home page is now blank for default Riot, so I am unsure if this issue still applies.

**Comment by anoadragon453** [comment]
Home page. This is on my local instance. Don't believe I changed anything in `config.json` from the default related to the home screen.

**Comment by anoadragon453** [comment]
Indeed, due to old files.

**Comment by jryans** [comment]
Looks like @anoadragon453 had the older setting `welcomePageUrl` set to `home.html`, which was putting this content there. Since this shouldn't be an issue with default Riot config, I think it makes sense to close.
