### ISSUE TITLE
Synapse's new CSP breaks viewing transferred PDFs in Chrome

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8605]
https://github.com/matrix-org/synapse/pull/4284 added "sandbox" to the media repo's CSP. This was to stop certain attachment classes being able to get at the DOM when being viewed in a tab launched from riot.

However, empirically it means that PDFs are no longer visible in Chrome - you get a big grey page, and have to know to hit 'File Save' to save the actual attachment.  Instead, we should either improve the CSP so it doesn't affect PDFs (which weren't the target we were protecting from), or special-case PDFs in Riot so they are downloaded immediately as attachments.

**Comment by ara4n** [comment]
(p1 because high profile users are getting bitten by this)

**Comment by dbkr** [comment]
I think the conclusion here is that we should just force them to download

**Comment by olmari** [comment]
This needs fixing, somehow... Persons behind (irc, or other oldschool) bridges or otherwise linked to file directly just practically fails to get pdf file. This can't be purpose of synapse/matrix to block these like this.
