### ISSUE TITLE
Clicking Unknown Devices warning has a 'Send anyway' button

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8608]
- **Browser**: Chrome
- **OS**: Debian Linux

### Description

If you click the Big Red Lock in an encrypted room, it presents you with the following screen:

![image](https://user-images.githubusercontent.com/1342360/52745311-9c1a8000-2fd6-11e9-9cf4-18be53c1de57.png)

It seems like we might need a new dialog for this.

**Comment by arxcode** [comment]
The "Send anyway" thing is one thing, but more importantly it actually doesn't list any "unknown devices" that could be verified... I had the same thing and don't really know what to do about it.

**Comment by eMPee584** [comment]
Even when you verify the last/only device that shows up there, the dialogue does not seem to take that into account and go away. `Send anyway` is somewhat pointless after having verified all devices in room...

**Comment by lampholder** [comment]
We've gotten rid of the ability to open this dialog by clicking the padlock, so, problem solved :P
