### ISSUE TITLE
make dark names more readable when using dark theme

### ISSUE THREAD

**Issue by swedneck** [vector-im/riot-web#8611]
- **Browser**: Firefox 65
- **OS**: Fedora 29

### Description

Names with a dark color are very hard to read, either names should not use dark colors when using the dark theme (may be confusing as names would swich color) or there should be a drop shadow or something around the text.

**Comment by anoadragon453** [comment]
Additionally, names that are pure white are hard to distinguish from message text.

**Comment by lampholder** [comment]
I think we've changed the name colours since this was filed
