### ISSUE TITLE
disable_custom_urls config option affects both login and registration in different ways

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#8612]
I am trying to do some minimal config / customisation of Riot 1.0 for one of my deployments, and I want the following two things to be true:

1. Allow login for all servers, i.e. I want well-known to work for users who already have matrix.org accounts.
2. Have a simple registration screen for my custom HS only.

I can achieve 2 by setting `disable_custom_urls` to `true` which leads to a nice simple registration screen:

![image](https://user-images.githubusercontent.com/1391051/52753695-9ed59f00-2fef-11e9-9781-b14e16a91138.png)

However, this breaks number one, as I now can't have users login with other HSes, so having `disable_custom_urls` to `false` leads to the following registration screen:

![image](https://user-images.githubusercontent.com/1391051/52753570-18b95880-2fef-11e9-83ab-dc2c82e51ebd.png)

Would it be possible to have a separate setting for disabling server selection on the registration screen? Or for bonus points allowing simple customisation of all three server options? (I might quite like having "openastronomy.org", "matrix.org", "custom" options rather than the defaults for instance).

**Comment by lampholder** [comment]
This is a dup of https://github.com/vector-im/riot-web/issues/8824
