### ISSUE TITLE
Logging in to a new Riot prompts to set up key backup, not to restore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8613]
There's zero messaging saying I have a backup on my other device. It's all saying I should create one

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/53024603-3c4d2a80-3457-11e9-8f15-f5f55603ee57.png)

**Comment by lampholder** [comment]
It does now appear to be doing the 'right thing', though the UX is not as reassuring as it should be. I'm going to resolve this issue - we can pick up UX refinements when Nad and I go through the E2E UX together

**Comment by turt2live** [comment]
Err... This was opened as a result of the messaging in your screenshot. If it's tracked elsewhere, sure, bit if not I'd reopen.
