### ISSUE TITLE
Settings icons are clipped

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8617]
I think some of the background CSS might have broken.

<img width="27" alt="screenshot 2019-02-14 at 10 16 22" src="https://user-images.githubusercontent.com/4626865/52780482-22b87700-3042-11e9-9afb-8202537c4d46.png">

Inconsistent icon weights captured here: #8619

**Comment by ara4n** [comment]
closing as dup of https://github.com/vector-im/riot-web/issues/8578 which explains why this is happening( i think)
