### ISSUE TITLE
Remove welcome menu item from top left menu

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8618]
We've decided it's too confusing to have this, since it leads you out of the app.

**Comment by spantaleev** [comment]
I've just pressed the Welcome button, thinking it would open the Home page.
Looks like it logged me out without asking for confirmation or anything.

It also makes me wonder.. where is the homepage in that case?

**Comment by jryans** [comment]
The home page is now blank by default, but can be customized if you self-host Riot. There is a separate menu item for Home that is only shown if it exists.
