### ISSUE TITLE
Settings icons use inconsistent weights

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8619]
We'll be fixing this with an upcoming UI refresh.

**Comment by turt2live** [comment]
tbh this is a little distracting at the moment, should it be 1px like everything else?

![image](https://user-images.githubusercontent.com/1190097/53260774-8e789080-368f-11e9-8bcc-04357271e740.png)

**Comment by turt2live** [comment]
I'm considering this a blocker for the room list implementation:
![image](https://user-images.githubusercontent.com/1190097/83991863-6efc8a00-a90b-11ea-881c-87696c72426a.png)

**Comment by turt2live** [comment]
Fixed elsewhere at the moment.
