### ISSUE TITLE
Make welcome.html snippable for modular

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8622]
Please can we wrap the bits of `welcome.html` that don't work for homeservers with guest access turned off in:
```
<!-- BEGIN remove these lines for servers without guest access -->
... lines to remove
<!-- END remove these lines for servers without guest access -->
```

We can indent the markers to fit with the flow of the HTML, but the indentation must be identical on both `BEGIN` and `END` so as not to break the ansible snipping.

It might be good for the comment to make some reference to ansible (so we don't blunder them out of the file at some point in the future).

**Comment by jryans** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/8634
