### ISSUE TITLE
Message entry box is too tall on Firefox

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8624]
![image](https://user-images.githubusercontent.com/1342360/52788273-50a8b600-3058-11e9-950d-cf873fc3c22c.png)

- **Browser**: Firefox 60.5.0esr
- **OS**: Debian Linux

### Description

The text field (with placeholder or actual text) looks too high on Firefox.

For reference, here is how it looks on Chrome:

![image](https://user-images.githubusercontent.com/1342360/52788178-10493800-3058-11e9-8b61-6497b13ca594.png)

**Comment by lampholder** [comment]
I don't think this is significant enough of an issue to track :)
