### ISSUE TITLE
Cannot override ServerTypes and default URL

### ISSUE THREAD

**Issue by abeluck** [vector-im/riot-web#8628]
**Problem:** The [ServerTypeSelector](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/auth/ServerTypeSelector.js) module is too tightly coupled to the [Registration](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/auth/Registration.js#L134) component. 

The template string `yourMatrixAccountText = _t('Create your %(serverName)s account', {` in [`RegistrationForm`](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/auth/RegistrationForm.js#L301) always has `serverName` set to matrix.org, even when you change default HS url in config.json.

Screenshot: 
![screenshot from 2019-02-14 14-55-45](https://user-images.githubusercontent.com/1761767/52791233-5f936680-3060-11e9-9711-6d9728369c9e.png)

**Use case:** In a custom matrix-react-sdk skin, I want to be able to override the default Free/Premium/Advanced server types. The simplest case is changing the default Free hs/is urls to be my own homeserver url. One expects that the UI should also reflect these skin changes.

**Root Cause**: 
[This block of code in Registration.js](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/auth/Registration.js#L132-L144) always has `hsUrl` defined as the static string from [`ServerTypeSelector`](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/auth/ServerTypeSelector.js#L35). And even if I provide a component that replaces `ServerTypeSelector`, I cannot override the constant `TYPES`.

Replacing the `Registration` component as well is not really an option as it is over 500 LOC and provides lots of functionality that would be common to many skins.

**Comment by jryans** [comment]
I agree these components are too tightly coupled at the moment. See also https://github.com/vector-im/riot-web/issues/8297.

Having said that, if you do configure a default HS in config.json, Riot should pre-select the advanced / other column and show the correct server name:

![image](https://user-images.githubusercontent.com/279572/52797557-029ead00-306e-11e9-969b-b514d6e6443a.png)

Do you see something else?

**Comment by abeluck** [comment]
@jryans You are correct. That is the default behavior, and it is working as expected.

However, what I am trying to do is provide my own `src/components/views/auth/MyOwnServerTypeSelector.js` that replaces the default one. I want my HS to be treated like matrix.org in the current selector, and I'm removing the modular.im button (as it makes no sense in my context).

In my fork of riot-web, I've created this custom component, and it is working fine! However the "Create your matrix.org account" text still shows even though it connects to my own HS.

**Comment by turt2live** [comment]
This should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2941 now that the `hsName` is pushed into `ServerTypeSelector.TYPES.FREE.serverConfig` - assuming you can override that, it should be fine. A quick test of changing the `hsName` there to something other than matrix.org at least renders it as such, so in theory changing it in-code should also work.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3001 - it won't make it into 1.2.0, but should be in the next regularly scheduled release.

**Comment by abeluck** [comment]
Just got around to checking this out, it is  _not fixed_ yet.

The problem is that [matrix-react-sdk/src/components/structures/auth/Registration.js](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/auth/Registration.js#L29) is importing the function `getTypeFromServerConfig` from the existing ServerTypeSelector.js.

In my project I've provided a different component that replaces `ServerTypeSelector`, and it is used.

However because this function is cherry-picked out of the default `ServerTypeSelector` file, I have no way to make changes to `TYPES.FREE`  without patching `matrix-react-sdk/src/components/views/auth/ServerTypeSelector.js`

@turt2live  said:
> This should be fixed by matrix-org/matrix-react-sdk#2941 now that the hsName is pushed into ServerTypeSelector.TYPES.FREE.serverConfig - _assuming you can override that_, it should be fine. 

That's exactly the problem, you can't override it.

**Comment by turt2live** [comment]
You should be able to override it with:
```
import {makeType} from "matrix-react-sdk/lib/utils/TypeUtils";
import {ValidatedServerConfig} from "matrix-react-sdk/lib/utils/AutoDiscoveryUtils";
import {TYPES} from "matrix-react-sdk/lib/components/views/auth/ServerTypeSelector";

TYPES.FREE.serverConfig = makeType(ValidatedServerConfig, {
    hsUrl: "https://example.org",
    hsName: "example.org",
    hsNameIsDifferent: false,
    isUrl: "https://vector.im",
});
```

at least, this is what worked for me in testing and just now.

**Comment by abeluck** [comment]
@turt2live  many thanks! 

Sorry for the noise. I don't use js that often, so it didn't occur to me I could just monkey patch the TYPES object that way.

Thanks again!
