### ISSUE TITLE
Logging in on a new device can replay stale Incoming Verification Requests which then get stuck.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8629]
1.  I logged into my main account fresh on Firefox
2. I got an Incoming  Verification Request from Rick.  He was confused, as he doesn't remember even sending it, so it must have been as while ago. I don't remember ever receiving it before.
3. I hit 'verify'; it showed the whole "waiting for your partner" thing
4. rick got no alert on his side.
5. i tried to close the spinner; it failed to close the dialog.
6. i was therefore unable to use the app and had to hit refresh.

<img width="929" alt="screenshot 2019-02-14 at 14 30 16" src="https://user-images.githubusercontent.com/1294269/52793319-62448a80-3065-11e9-9f91-4ba7bf08b80d.png">

**Comment by Insoleet** [comment]
We encoutered the same problem on a private E2E multi-users room.

**Comment by ara4n** [comment]
see also #8807

**Comment by turt2live** [comment]
I think the X not working is https://github.com/matrix-org/matrix-js-sdk/pull/961/files#diff-0a3445e771f0c35ffee76e9d08b65e12R175
