### ISSUE TITLE
hit the video call button in a room which already has a widget; minimise then maximise the widget; jitsi no longer loads

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8631]

**Comment by lampholder** [comment]
https://matrix.lant.uk/_matrix/media/v1/download/lant.uk/iAzZKlgCpWCQJiqLmUtrKZyl

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/7363 (fixed)
