### ISSUE TITLE
Markdown indicator on dark theme is invisible when in RTE mode

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8637]
See below:
![](https://i.imgur.com/DUEEPcv.png)

**Comment by aaronraimist** [comment]
Similar to  
https://github.com/vector-im/riot-web/issues/8554#issuecomment-463204172 
![screen shot 2019-02-14 at 10 33 49 am](https://user-images.githubusercontent.com/5855073/52801704-17664b00-3044-11e9-8d97-8eed6b7ef00e.png)

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2659
