### ISSUE TITLE
Copy icon in share dialog has artifacts on edges

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8639]
- **Browser**: Chrome
- **OS**: Debian Linux

### Description

![image](https://user-images.githubusercontent.com/1342360/52803043-18659f80-3079-11e9-9a34-77ddca787f17.png)

The copy icon looks odd with strange artefacts at the side. Also happens on the light theme, but more obvious on the dark theme.

**Comment by lampholder** [comment]
Only perceptible on dark theme

**Comment by anoadragon453** [comment]
This doesn't seem to be an issue anymore.
