### ISSUE TITLE
UX on setting room alias can be misleading

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#8640]
When adding a room alias in a room that doesn't have any and hitting enter, the alias appears as the canonical alias (main address), which made me think the alias was set, but Riot doesn't actually send the request until you hit "Save", resulting in me thinking I had set the alias and continuing with the rest of my things while I hadn't.

Tested on /staging ~10min ago.

**Comment by turt2live** [comment]
for context: the entire UI here is somewhat placeholder.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2679
