### ISSUE TITLE
User ID already taken.

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [vector-im/riot-web#8651]
i removed my email on riot to reuse it (like fresh) but i can't user my same username so any help ?

**Comment by aaronraimist** [comment]
If you deactivated your account you can't reuse that username. You could contact your home server operator to get it reactivated.

**Comment by EsmailELBoBDev2** [comment]
my home server is matrix.org, what i do ?

**Comment by jryans** [comment]
For matrix.org HS, please email support@matrix.org for help with this.
