### ISSUE TITLE
Consider always showing the current room in the breadcrumbs

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8659]

**Comment by Valodim** [comment]
I second this. With the current behavior, clicking between rooms actually takes a while to figure out how icons even behave, it feels "one behind" in a way.

**Comment by lampholder** [comment]
I think this is already in the list of breadcrumb improvements, but will leave this here for now.

**Comment by ara4n** [comment]
https://github.com/vector-im/riot-web/issues/8548#issuecomment-463143830 is the dup comment
