### ISSUE TITLE
Unable to type umlauts in chat

### ISSUE THREAD

**Issue by kiliankoe** [vector-im/riot-web#8660]
### Description

I'm on a US keyboard layout (running macOS) and I usually type German umlauts via option+U for the diaeresis ¨ followed by the respective letter. This unfortunately does not seem to be working in the redesigned Riot interface released today (congrats on that btw!) in Safari. It does work in current Firefox.

### Steps to reproduce

- Open any chat in Riot
- Attempt to type umlaut by typing diaeresis and letter separately

I can see the diaeresis appearing, but the cursor seems somewhat buggy. On typing the letter however the diaeresis disappears and I'm left with just the letter.

### Version information

- **Platform**: web (in-browser)

- **Browser**: Safari 12.1, 12.2 (technology preview)
- **OS**: macOS
- **URL**: riot.im/app

**Comment by turt2live** [comment]
Duplicate of one of the issues on https://github.com/vector-im/riot-web/issues/7665

**Comment by kiliankoe** [comment]
ah perfect, thanks 👍
