### ISSUE TITLE
Registration spinner doesn't fit in the box

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8661]
![image](https://user-images.githubusercontent.com/1190097/52818969-5953b900-3065-11e9-84a7-2b1610d67747.png)

**Comment by jryans** [comment]
Hmm... is that Edge only?

**Comment by turt2live** [comment]
That was chrome

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2712
