### ISSUE TITLE
Should be able to dismiss read marker indicator

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8666]
I can't find the issue for this

**Comment by aaronraimist** [comment]
#8512 was the issue but I'll close that and thumbs up this cc @jryans

**Comment by ejpcmac** [comment]
Maybe the UX could be unified with #8541 for this issue. We should be able to dismiss messages per room, or community. Looking for the new behaviour to achieve this (in fact missing), I have tried:

1. to right click on the unread inticator in the message views
2. to click / right click on the room options in the side bar to see if the option was instead there

Maybe this can help.

**Comment by Throne3d** [comment]
From #riot-web:matrix.org:
> **Throne3d**, 02:35
> Discord uses alt+clicks to let you manually mark some point read/unread, so you can move your unread marker to save your place if you're reading history
> (it's not very well advertised as a feature)
> I find that very useful – maybe it'd be a good thing to add wrt this?

(If you alt+click the last message in a channel, it marks the whole channel as read – in fact, it marks everything up to, and including, the message you click, as read, and everything after it as unread.)

**Comment by tulir** [comment]
Could just jumping back down dismiss the read marker?


[Message](https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$155052855861064JSQUK:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org) from @fladd:matrix.org:

> if i jump down again that clearly is a sign that I read where the marker is, and don't care to read the rest. this should clear the marker and move it to the current position all the way down in my opinion

**Comment by ejpcmac** [comment]
> Could just jumping to read marker and back down dismiss it?

@tulir This is not a good thing IMO. You can be interested in what’s currently going on in the channel while reading the logs. When doing this, you may want to go back and forth from your “last read” message to the current conversation.

**Comment by fladd** [comment]
Maybe at least make it an option or so?
I am literally never interested in anything else than the last position. Once I have been there any marker should be entirely deleted. Right now, if I understand it correctly, the marker is just moved down half a screen or so.
For me the current behaviour just leads to a situation where I (a) constantly have a read marker somewhere in the room at a position I don't care about (might be weeks ago), and (b) cannot jump to the actual point where I **last** left the room. Hence, I currently just scroll up an manually search for where I last left the room, since this still gets me quicker there than starting from this random position in my room history where Riot has left the read marker at some point in the (distant) past.

**Comment by Mikaela** [comment]
I am missing the ability to mark room as read by pressing ESC which is supported by Discord and at least Telegram jumps to main screen with that.

**Comment by fladd** [comment]
I see that in the newest version on /develop, the read marker is automatically cleared if you don't jump to it within 30 seconds after switching to the room. Nice! This should work for most people (although people need to know this, so they don't go away to get a coffee to prepare for reading through all this history, only to figure out after they got their coffee that the marker is gone :-) ).

**Comment by aperezdc** [comment]
Well, I am not a fan of the read marker being dismissed automatically after 30 seconds, but I guess it's better than nothing :upside_down_face:

**Comment by yangm97** [comment]
Me neither. The fact riot allowed me to manage this manually kind of made it special.

**Comment by fladd** [comment]
The problem with managing it manually is, that if you don't do that every single time you switch to a room, the read marker becomes entirely useless (as described above) :-)

**Comment by yangm97** [comment]
And the problem with dismissing automatically is that you could lose the last location accidentally, making the feature useless :-)

Maybe a toggle would do well

**Comment by fladd** [comment]
Well it could also just work like in every IRC client. Upon switching to
the room you are automatically taken to the read read marker and the read
marker is then automatically deleted. You can then decide to read through
everything you missed or to just jump down to the current point in time and
ignore everything. This solves both issues, doesn't it?

**Comment by yangm97** [comment]
That's how telegram does it too. Which means that I (and other people) end up replying some of the old messages with something like "#readfromhere" just so we can read/reply to other stuff without losing that point in time accidentally, for instance, when you open it on mobile but don't actually have time to read the entire thing or the fact that  it's currently impossible to reply to messages once you jump to the last unread bit on riot mobile. 

Personally I don't like it either, but it's a little more standard behavior at least.

**Comment by cuibonobo** [comment]
I think it is fine that the marker disappears after 30 seconds, but I would like a way to dismiss it manually. I will often jump quickly between rooms to see the latest things that have been happening and 30 seconds seems too long to wait for the marker to go away.

**Comment by yangm97** [comment]
I would also love to be able to disable the behaviour of the marker vanishing on its own.

**Comment by altsalt** [comment]
Alternatively, it would be nice to have actually follow along as the text scrolls. Right now the assumed read speed is painfully slow. Often I just want to page down glancing for keywords.

**Comment by MurzNN** [comment]
@needs-design - maybe like this?
![image](https://user-images.githubusercontent.com/336662/61115684-a8c6d580-a49b-11e9-83cc-88e24dd4b628.png)

**Comment by MurzNN** [comment]
Other way from RocketChat is pinned line on top of message list:
![image](https://user-images.githubusercontent.com/336662/62446813-6b88f700-b76c-11e9-9fe5-8806840a6cd0.png)

**Comment by MurzNN** [comment]
This feature is already re-implemented successfully in RiotX-Android, so why Riot-Web still can't give back it? At first - with ugly design, but functional, second step - good design...

**Comment by kortschak** [comment]
Any chance of any movement on this? Throwing away tens of minutes each time I use riot to keep up with rooms' streams is a killer for usability here.

**Comment by mstriemer** [comment]
I put a simple patch up at matrix-org/matrix-react-sdk#4159, if that's something that's wanted I can spend a little more time on it to get it ready.

**Comment by escapewindow** [comment]
If we could map the `esc` key as well, that would be perfect.

**Comment by mstriemer** [comment]
Looks like mark as read on escape is #12537. I agree that would be a nice feature, but I don't think these would depend on each other.
