### ISSUE TITLE
When the welcome.html 404's, we show the user a broken welcome page

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8676]
See below:
![](https://i.imgur.com/c0Dyjfc.png)

**Comment by pedro-nonfree** [comment]
I'm a victim of this bug; let me know what can I do in my side

**Comment by jryans** [comment]
I think we'll need more detail, such as any stacks in the console and network request details. I have configured my local Riot so that both config.json requests 404 and the welcome page loads just fine.

**Comment by pedro-nonfree** [comment]
@jryans 

I'm using [this tool](https://github.com/grigruss/Riot-web-server-update/pull/2#issuecomment-464087959) to upgrade the static files

in fact is not related to my particular yaml file configuration: now is deleted and I'm just using the defaults

- static riot files: riot.guifi.net
- matrix homeserver: matrix.guifi.net

**Comment by jryans** [comment]
When I look at riot.guifi.net, the `config.json` isn't the issue. Instead, `welcome.html` (which is a new file in 1.0 and later) 404s, which is the file that embeds the welcome content.

Perhaps the update process you're using isn't adding new files or something? (I have verified that the release published on GH contains `welcome.html`.) This doesn't seem to be an issue with Riot itself, but please reopen if I am misunderstanding.

**Comment by pedro-nonfree** [comment]
Aha, so that's the think, you added a new welcome.html

so I had a /welcome endpoint that after renaming it to welcome_custom it works [1]

looks like that if now I want to change the welcome page I have to setup everything by myself. Correct? (Previously I was adding html code to a template)

[1]

```
    # static front page to anounce how works the service (inside riot)
    location /welcome_custom {
        alias /var/www/html/riot.guifi.net;
        index /matrix.html;
```

**Comment by jryans** [comment]
> looks like that if now I want to change the welcome page I have to setup everything by myself. Correct? (Previously I was adding html code to a template)

The new welcome.html is a page you can customize. You also point it at a different file via `{ embeddedPages: { welcomeUrl }}` in `config.json`.
