### ISSUE TITLE
Make the system menu dark themed when using the dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8680]
This might be hard, because Windows.

**Comment by yangm97** [comment]
<img width="380" alt="screen shot 2019-02-15 at 01 08 54" src="https://user-images.githubusercontent.com/4412002/52832502-e75c8d80-30bf-11e9-97cb-c52432d78b8b.png">

There are some possible solutions on macOS:

1. Use the native dark theme API
Works only on Mojave and later.

2. Use the native bar tint API
Seems to work as far as Yosemite (afaik), is used by Sublime Text, Telegram, etc. Can be tinted with any color.

3. Ignore the title bar completely and add system buttons on top
Idk if there's an API for that, but it looks like most electron apps pick this one so it shouldn't be hard.

**Comment by starcraft66** [comment]
This would be really, really, really appreciated!

**Comment by starcraft66** [comment]
Upon further inspection, a quick and dirty way of getting this working on macOS 10.14+ is setting the `NSRequiresAquaSystemAppearance` to `false` in the application's `Info.plist` file as per https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app.

However, electron also apparently has built-in APIs to manage the title bar colour: https://github.com/electron/electron/issues/13387

**Comment by Timsuper** [comment]
would be nice

**Comment by dbkr** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/11140
