### ISSUE TITLE
You can type Riot off the screen

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8681]
![](https://t2l.io/_matrix/media/v1/thumbnail/hacklab.fi/SCAPIIXipvwSTkPIsWnvMhWt?width=800&height=600)

**Comment by vurpo** [comment]
Normally I guess it would break the line at word boundaries, but it seems the field never breaks inside a word, so one really long word extends the width of the field and types the right sidebar off the screen. (The right sidebar was open when I took this screenshot)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/77474309-c8761200-6e0e-11ea-93d2-46ee851b81c4.png)

new composer happily breaks words up
