### ISSUE TITLE
Firefox's check spelling not working correctly

### ISSUE THREAD

**Issue by jerrykan** [vector-im/riot-web#8682]
### Description
Firefox's in-built check spelling feature does not work correctly when writing a new message.

### Steps to reproduce
- Type an incorrectly spelt word in the "Send a message" field
- Observe that no red curly line appears below the word

A work-around seems to be if you change to another tab, then change back again, the incorrectly spelt word is correctly highlighted.

### Version information
- **Platform**: web 
- **Browser**: Firefox v65.0
- **OS**: Linux (Debian testing)
- **URL**: riot.im/develop (674b8c3561ff-react-b19a1a018871-js-03a54353be98)

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by jerrykan** [comment]
As of Riot version v1.5.13 and using Firefox v72.0.2 (64-bit) (Linux) this seems to be working now.
