### ISSUE TITLE
Favicon on /develop is wrong

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8683]

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/52834081-2decc080-309d-11e9-9217-50f32afaf355.png)

Left: actual
Right: expected

**Comment by jryans** [comment]
I believe this is just a caching issue. If you compare:

https://riot.im/develop/vector-icons/favicon.ico
https://riot.im/develop/vector-icons/favicon.ico?123

...you get a different image. I think we'll probably just wait it out?
