### ISSUE TITLE
Community pages wont load on address change

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#8684]
I replaced one of the welcome html buttons on https://openastronomy.riot.im and when you click on it the URL in the address bar changes, but the page doesn't load

**Comment by Cadair** [comment]
This seems to be in general anything that changes the address to `/groups/` doesn't get reflected in the app unless you refresh.

**Comment by t3chguy** [comment]
Cannot reproduce :((
![8684](https://user-images.githubusercontent.com/2403652/75595572-da20ff80-5a84-11ea-8a3e-79484b72bf6f.gif)

**Comment by Cadair** [comment]
OK, maybe it isn't any interaction with the address bar, but it definitely happens on some button clicks in the app:

![riot-bug](https://user-images.githubusercontent.com/1391051/75666535-e0260480-5c6d-11ea-8f4a-f4bc750ff320.gif)
