### ISSUE TITLE
Room switching takes longer and longer if you leave the app open

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8685]
My only (unproven) theory is that the breadcrumbs are storing the last 12 hours of rooms, leading to long term slowdowns. Have not confirmed if disabling the feature helps

**Comment by bwindels** [comment]
the breadcrumbs are trimmed to [20 rooms](https://github.com/matrix-org/matrix-react-sdk/blob/321dd49db4fbe360fc2ff109ac117305c955b061/src/components/views/rooms/RoomBreadcrumbs.js#L25) though.

**Comment by turt2live** [comment]
I don't think this is a breadcrumbs issue, and I haven't seen it recently. Closing as cannot reproduce.
