### ISSUE TITLE
vertical scrollbar for community filter panel

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#8690]
There must no scrollbar (when content fit viewport)
![image](https://user-images.githubusercontent.com/14617699/52845438-2d454000-3118-11e9-871b-6832f60c5ab4.png)

**Comment by lampholder** [comment]
Hi - thanks for the report, but please do include which browser/version and OS/version you're using, too - it's particularly useful when diagnosing css issues (and useful most of all when diagnosing scrollbar issues - scrollbars are a pain). Thanks!

**Comment by 532910** [comment]
This issue is for any browser and desktop client.

**Comment by MaxMatti** [comment]
> please do include which browser/version and OS/version you're using

This also occurs with Firefox 65.0.1 (64-Bit) on Archlinux.

While this is the only panel in the new design where I noticed this issue, it occured on a few occasions in the old design. However iirc those could be fixed by reloading the page, which is not the case here.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3143

**Comment by 532910** [comment]
Thank you!
