### ISSUE TITLE
After setting a custom HS in sign-in, going to create account reverts it to matrix.org

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8695]

**Comment by abeluck** [comment]
I've seen this too, but I can't reproduce it consistently.

It also happens with the IS url. 

Basically the steps are

1. Enter custom HS/IS url
2. Defocus the input box

**Result:** sometimes the content of the input reverts to the default matrix.org

But like I said, it doesn't happen consistently for me.

**Comment by lampholder** [comment]
/me wonders if this is the default homeserver + .well-known support fighting.

**Comment by bwindels** [comment]
for me, it was localhost, so no well-known

**Comment by jryans** [comment]
@bwindels I can no longer reproduce this on https://riot.im/develop (still happens on /app for now). Do you agree? (There are several reports of this, so verifying it's fixed would be great.)

**Comment by bwindels** [comment]
@jryans yep, can't repro anymore on /develop :+1:

**Comment by jryans** [comment]
Thanks for testing! Let's consider this fixed then.
