### ISSUE TITLE
Add statement of supported browsers

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8701]
The README or some page linked from it should list our supported browsers.

**Comment by jryans** [comment]
Ah, I guess we sort of have something in the [React SDK developer guide](https://github.com/matrix-org/matrix-react-sdk#developer-guide). We should lift it up to Riot Web, and also perhaps be more explicit with versions, such as "last 2 stable releases", "latest stable version only", or similar.

**Comment by jryans** [comment]
There is also [`CompatibilityPage`](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/CompatibilityPage.js), which should match whatever statement we make in our docs.

**Comment by turt2live** [comment]
Official ruling is:
> Firefox Chrome Safari, latest versions.

Edge is supported if it works, but not actively maintained.
