### ISSUE TITLE
Room padlock is green immediately after enabling e2e on a room

### ISSUE THREAD

**Issue by neutralinsomniac** [vector-im/riot-web#8708]
Start a chat with someone, enable e2e encryption, and the room padlock turns green even if you haven't verified any of the user's devices. The padlock will not turn red unless you load the user's list of devices by clicking their name in the user list, and then clicking on a different room and back again.

**Comment by lampholder** [comment]
Hmm, I wasn't able to reproduce this, but I wonder if there's an edge case where a user (whose devices you _have_ verified) adds a device in between their being invited and you clicking on their device list?

**Comment by neutralinsomniac** [comment]
This was done on a closed-network homeserver. I invite a user to a chat, they accept, then I enable e2e, and instantly the padlock goes green (even though I've verified *none* of their devices, and they certainly haven't added new devices in the meantime). I've reproduced it 4 times with different people. That said, I'm having a hard time reproducing it again this morning. I'm wondering if the closed-network speed is causing a race that isn't normally seen over the internet.

**Comment by anoadragon453** [comment]
Just ran into this myself on open federation between amorgan.xyz and matrix.org.

Have sent logs.

**Comment by anoadragon453** [comment]
Also interestingly Riot has now marked it as a public room (not a DM).

**Comment by neutralinsomniac** [comment]
Just triggered this again this morning. Switched long-running chat with lots of devices (all unverified) over to e2e, and room padlock turned green until I navigated away/back to it

**Comment by uhoreg** [comment]
The room decoration logic is now different with cross-signing, so this issue is probably no longer relevant.
