### ISSUE TITLE
Unable to send/upload files on desktop (since 1.0)

### ISSUE THREAD

**Issue by pe7ro** [vector-im/riot-web#8709]
### Description

The file upload (send) fails:
"Upload Failed
The file 'image.png' failed to upload."

Does not work for both images, images from clipboard, files. 

### Steps to reproduce

* start app
* open chat (e2ee or not does not matter)
* drag-and-drop or "upload file" a file.
* error message is shown

![untitled](https://user-images.githubusercontent.com/44572319/52871174-575f2800-3141-11e9-9798-2001b1bc13f8.png)

Log: not sent 

### Version information

- **Platform**:  desktop (debian)

matrix-react-sdk version: <local>
riot-web version: 1.0.0 and 1.0.1
olm version: 3.0.0

**Comment by turt2live** [comment]
Are you using matrix.org as your homeserver?

**Comment by pe7ro** [comment]
yes

**Comment by turt2live** [comment]
matrix.org is currently having some troubles with media uploads - try again in a little bit. If the issue persists, please come visit us in [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org).
