### ISSUE TITLE
Key backup interacts horribly with password managers

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8713]
It can't find the password, the username ends up in the filter room members list, and it's all awful

**Comment by lampholder** [comment]
Different password managers have different headaches. Chrome's is https://github.com/vector-im/riot-web/issues/8789

**Comment by lampholder** [comment]
We should be able to recommend that people use password managers

**Comment by lampholder** [comment]
I think this is a dup of https://github.com/vector-im/riot-web/issues/7861 ?
