### ISSUE TITLE
Pending messages are hard to distinguish in dark theme

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#8727]
When sending a message in the dark theme, if the network is unreliable, it's very difficult to tell if the message has sent or not. In the old UI, there was a significant difference in the text color (a medium gray), but in the new UI the difference is much more subtle. Unless the message contains a pill, it's almost impossible to tell by appearance.

**Comment by eternaleye** [comment]
The color of quotes, and of join/part events, is much closer to what I remember the old UI using (and quite easy to tell apart)

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/8586
