### ISSUE TITLE
Horizontal scrollbar in fenced code blocks not visible on the dark theme

### ISSUE THREAD

**Issue by dkasak** [vector-im/riot-web#8734]
![scrollbar not visible](https://i.imgur.com/dWTtOAo.png)

It's there since I'm able to click on it and scroll, but I suppose it's the same colour as the background.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4256

**Comment by dkasak** [comment]
Is this really a duplicate? I found that issue but it seemed different: the screenshots there do show the scrollbar, it's just partially hidden by the text. Also, I seem to remember that prior to the redesign the scrollbars on `<pre>` blocks were visible for me.

**Comment by turt2live** [comment]
It's a further regression, but the issue appears to be the same afaict
