### ISSUE TITLE
FR: Put a lock in the room icons for encryption

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-web#8742]
Hi

It will be really useful to have a lock icon in the icons of encrypted room's. It is hard to tell which room is encrypted which is not, well until one enters the room.

thanks

**Comment by aaronraimist** [comment]
Duplicate of #11226

**Comment by turt2live** [comment]
Not sure that's true, 11226 seems to be about the general decoration and not the room list.

**Comment by foldleft** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/11935
