### ISSUE TITLE
FR: Circle for direct chat, square for rooms.

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-web#8743]
Hi

One issue that i find confusing is to distinguish between a room and a direct chat, this is naturally a real issue when one has many favorites. So it is not really possible to tell if it is a direct chat or not unless rooms are clearly named, which does not happen always.

So my recommendation is to make the room icons as square shaped and the direct one to one chats as a circle which can stay as is as of now.

thanks

**Comment by targodan** [comment]
Isn't that solved already?

In Riot 1.0.1 the icons of direct chats have a small person-icon-thingy in the bottom right whereas the rooms don't.

Also changing the shape of the icon probably isn't a good idea. Take for example the icon of the Riot channel. It has a dark background, so in dark mode you only see the `R` but cannot make out the shape of the icon.

**Comment by gerroon** [comment]
Well I am on Android, Fdroid version, maybe that one does not have that feature not sure, I am not seeing any kind of person or head in the icons myself.

**Comment by targodan** [comment]
This is the riot-web project. This has nothing to do with the android version of riot.
Take a look at the [riot-android repository](https://github.com/vector-im/riot-android).
