### ISSUE TITLE
Clicking the top-right user icon when looking at a user profile should close sidebar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8745]
It's confusing that this icon can both close the sidebar or go back to the user list. I know that clicking each of the other icons will close the sidebar if I'm on that menu

**Comment by lampholder** [comment]
I think I agree - it blurs the mental model of what those top right buttons do.

**Comment by benparsons** [comment]
I agree with this - I keep hitting this issue and was about to open a new bug.

Context:

* right panel is closed
* click a user icon -> right panel opens
* click the "Members" tab icon -> you're back to the members list
* click the "Members" tab icon -> right panel closes

This is mitigated slightly by the fact that if you double-click the icon the right panel closes, bu it's still inconsistent.

**Comment by aaronraimist** [comment]
Fixed
