### ISSUE TITLE
Images get enlarged even when you click aside of them

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riot-web#8747]
### Description

When an image gets displayed in a chat, it still gets enlarged when I click into empty space 5 cm to the right of the image. Please restrict the enlarge/zoom action to the real frame of the image.

- **Platform**: Flatpak

For the desktop app:

- **OS**: Fedora Silverblue 29
- **Version**: 1.0.1

**Comment by lampholder** [comment]
You should be seeing the whole message tile be highlighted (grey on light theme) - it's clicking the message tile (rather than clicking the image within it) that causes the image to be displayed in the lightbox.

**Comment by fbruetting** [comment]
I don’t see any highlighting in the dark theme. But it’s not that good as this sometimes happens when I have another active window and just want to click inside the Riot window for activating it. Could you maybe restrict that area to the image itself and the text instead of the frame around everything?

**Comment by jryans** [comment]
> I don’t see any highlighting in the dark theme.

The highlighting has been improved on /develop, but it hasn't reached release yet, so you'd should see it with the next release (since you appear to be using the desktop build).

**Comment by lampholder** [comment]
I reckon this is very likely fixed - the higlighting looks good on light/dark to me
