### ISSUE TITLE
This is not an issue, it's positive feedback for your latest release.

### ISSUE THREAD

**Issue by davepuchyr** [vector-im/riot-web#8752]
I couldn't figure out how to give positive feedback on your latest release, but I want you to know that at least one user likes the improvements.  Nice work!

**Comment by lampholder** [comment]
Thanks for this, it made my day; I've had it printed on a mug :P

![image](https://user-images.githubusercontent.com/1922197/53010535-16635e00-3436-11e9-80d3-419161d07a65.png)

**Comment by BurnyBoi** [comment]
Seems like this unhandled exception has now been caught. Good work guys!

**Comment by lampholder** [comment]
And with the arrival of the mug, I guess we can consider this issue closed:

![image](https://user-images.githubusercontent.com/1922197/53407842-078c2680-39b5-11e9-88aa-cb115c14a6e8.png)

Thanks all :grin:
