### ISSUE TITLE
unable to open browser-console box in riot-web 1.0.1 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#8753]
I have firefox as my default browser. In firefox it is CTRL+SHIFT+J to see the browser-console according to https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts. I am able to do the same in firefox 60.0.4 but seems to be impossible in the newer riot-web. 

```
Package: riot-web
Version: 1.0.1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.19.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.7-4
ii  libnss3           2:3.42-1
ii  libxss1           1:1.2.3-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information

```

**Comment by jryans** [comment]
This seems to work on Riot desktop for macOS, so it may be Linux specific.

**Comment by jryans** [comment]
@shirishag75 The Riot Web desktop app is not based on Firefox and won't use the same shortcuts.

In testing on Ubuntu, Ctrl+Shift+I should open the DevTools in Riot Web desktop. Does it work for you?

**Comment by shirishag75** [comment]
> @shirishag75 The Riot Web desktop app is not based on Firefox and won't use the same shortcuts.
> 
> In testing on Ubuntu, Ctrl+Shift+I should open the DevTools in Riot Web desktop. Does it work for you?

ok that works :)
