### ISSUE TITLE
Update to 1.0 sets URL preview to off.

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#8754]
This happens with update to 1.0 and they doesn't appear with 1.0.1.

I have `Enable inline URL previews by default=ON` in settings.

**Comment by BurnyBoi** [comment]
That setting will apply to rooms that you join going forward, but there's still the setting in each room. Are you sure you have previews enabled for the particular room you're testing in? Check the room settings page.

**Comment by 532910** [comment]
Oh, yes, you are absolutely right!

**Comment by 532910** [comment]
I have `Enable inline URL previews by default=ON` in the global settings. But after updating to 1.0 I have `URL Previews=OFF` for per room contols.

**Comment by jryans** [comment]
Hmm... has a room admin set the room to default enable URL previews? If not, I believe you'd have to manually enable it for yourself. It may help to screenshot the relevant room settings dialog.

**Comment by 532910** [comment]
> has a room admin set the room to default enable URL previews?
Why does it matter?

There was no "Enable URL Previews" per room controls. Moreover, android client 0.8.22 (G-b162) ignores them and shows previews according to global settings.

**Comment by jryans** [comment]
There are several settings added together for URL previews, so I think it helps to understand what you are seeing. I can't help if I don't understand the issue...

Here's are a few of the possible states:

<img width="490" alt="2019-02-20 at 12 26" src="https://user-images.githubusercontent.com/279572/53091782-cd310e00-350a-11e9-916f-6d7f272201ab.png">

<img width="492" alt="2019-02-20 at 12 27" src="https://user-images.githubusercontent.com/279572/53091798-db7f2a00-350a-11e9-90a4-56ba591ac7b1.png">

**Comment by 532910** [comment]
I don't ask for help, it's a bug report.

**Comment by jryans** [comment]
Surely you'd prefer the bug to be fixed, though...? (I am trying to understand the situation so that it can be fixed.) If you don't want to discuss it further, let's close the issue.

**Comment by 532910** [comment]
Sorry.

The situation is:

Before 1.0 there were no per room URL Previews controls. (Rright?) And my global URL preview toggle was on.

Now, after upgrading to 1.0, most of my rooms have per-room URL Previews switched off.

**Comment by t3chguy** [comment]
> Before 1.0 there were no per room URL Previews controls. (Rright?) And my global URL preview toggle was on.

Nope, riot-web has had per-room URL Preview Controls for quite some time. Way prior to 1.0.

![image](https://user-images.githubusercontent.com/2403652/53285250-6dc73e00-3756-11e9-9c82-e45902770ec8.png)

**Comment by 532910** [comment]
OK. So before upgrading to 1.0 per-room controls were on for me. And upgrade resets most of them.

**Comment by jryans** [comment]
@turt2live Could this be related to removing negation in settings? Just trying to think of any recent changes in this area...

**Comment by turt2live** [comment]
No, the URL preview settings were inverted long ago (as shown by t3chguy's screenshot). I suspect what's actually going on is confusion about what each setting does and who it impacts, which is tracked here: https://github.com/vector-im/riot-web/issues/6736

**Comment by lampholder** [comment]
This issue doesn't feel useful to me, and I've not heard anybody else complain about a change in behaviour so I'm going to close it.

**Comment by 532910** [comment]
The issue usefulness to you personally and abcense of other complains are not the reasons to close this issue.
