### ISSUE TITLE
Discoverability of Client Settings

### ISSUE THREAD

**Issue by Thovthe** [vector-im/riot-web#8755]
In the redesign the settings are inadequately discoverable and room settings get confused for client settings.  I wouldn't click on my _username_ to try to change things about my _client_.

**Possible options:**
- left-left-panel like the old design
- separate button next to username
- take the room buttons on the right of the top panel put them in the right panel, use the original spot for client buttons
- take the room buttons on the right of the top panel put them closer to the room name, cordon off a section for client buttons

**Comment by lampholder** [comment]
We're continuing to look at this interface, and your suggestions have been noted. I'm going to close this issue for nwo.
