### ISSUE TITLE
How to use the old design?

### ISSUE THREAD

**Issue by April93** [vector-im/riot-web#8756]
I went ahead and updated and the UI got severely worse. Everything is much more cluttered, seems the colors got messed up? Everything in general is a lot worse. How do I change it back?

**Comment by jryans** [comment]
Unfortunately, it would be too much of a maintenance burden to maintain both the old and new designs together, so the old design is no longer available. I would recommend filing issues on any specific details that you dislike about the new design to see if they can be improved for everyone.
