### ISSUE TITLE
On Mac OSX electron, Cmd+DELETE behaving as left arrow instead of DELETE 

### ISSUE THREAD

**Issue by leijurv** [vector-im/riot-web#8757]
On the Mac OSX, typing Cmd+DELETE in the message box, with the entire message selected, moves the cursor to the beginning of the box instead of deleting the message. I have verified in all other entry boxes I can find that it should instead delete the entire message (other electron apps like discord, chrome top bar, chrome text boxes like this one, telegram). I do this when I type Cmd+A then DELETE without letting go of Cmd in between.
Cmd+DELETE seems to erase everything to the left of the cursor, and I suppose that when the entire message is selected, it does so from the left edge of what's selected. Again, this is different behavior from every other electron app so I'm not sure why it's happening.

Riot 1.0.1 Mac OSX 10.13.6

**Comment by t3chguy** [comment]
Apparently this was fixed, so maybe worth mentioning upstream that you're still having the issue: https://github.com/ianstormtaylor/slate/pull/1888

**Comment by leijurv** [comment]
I'm not sure that's the same issue, because on Mac CTRL+DELETE is different from CMD+DELETE. 

CTRL deletes one word, CMD deletes the entire line/text box.

**Comment by lampholder** [comment]
Yeah, I'm not sure that's the same issue.

cmd+backspace works on the slate.js example page, too, so I'm not sure this is an upstream issue (at least, not one that's still open).

**Comment by aaronraimist** [comment]
Is this still happening on Riot 1.5.7? I can't reproduce it.

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by leijurv** [comment]
I am no longer able to reproduce this in Riot.

I have updated my Mac OSX and Riot many times since reporting this, so I'm not entirely sure what fixed it.
