### ISSUE TITLE
We should have a default_server_name config.json property that defaults homeserver url and identity server url via .well-known

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8763]
My matrix homeserver runs at https://matrix.lant.uk. The server name is lant.uk.

config.json:
```
{
    "default_server_name": "lant.uk"
}
```

Then, when you go to https://riot.lant.uk (don't, it doesn't exist), you'll see the nice and simple UX:
![screenshot 2019-02-18 at 15 32 24](https://user-images.githubusercontent.com/1922197/52961313-8f10de80-3392-11e9-8026-259ae800783f.png)
![screenshot 2019-02-18 at 15 32 53](https://user-images.githubusercontent.com/1922197/52961314-8f10de80-3392-11e9-8e63-d316fe127860.png)
![screenshot 2019-02-18 at 15 33 05](https://user-images.githubusercontent.com/1922197/52961315-8f10de80-3392-11e9-9528-475f0a8362eb.png)

i.e. no server picker three-way option box, everything looked up via https://lant.uk/.well-known/matrix/client

**Comment by lampholder** [comment]
We should also ignore `default_hs_url` and `default_is_url` if `default_server_name` has been set

**Comment by lampholder** [comment]
And, because I wasn't explicit in the above, we should reject `default_server_name` if it's prefixed with `http://` or `https://`. It's a server name (which we'll use to construct a .well-known request), _not_ a URL.

**Comment by lampholder** [comment]
It's been suggested that 'Create your lant.uk account' might itself be confusing - if lant.uk were a large organisation it's likely they would already _have_ something they think of as a lant.uk account. 

It's also been raised that whilst lant.uk is the most sensible domain part for their mxids, they might prefer to be represented in the UX by their full company name, or similar.

Two possible independent mitigations for this:
- Change the 'Create your ________ account' wording to read 'Create your _______ matrix account' (making it more obviously distinct from whatever other accounts/infrastructure exist on lant.uk)
- Perhaps also support a server's "Display Name" via a .well-known option
   ```
    {
        "m.homeserver": {
            "base_url": "https://matrix.lant.uk",
            "display_name": "Lant ltd."
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    }
````

**Comment by lampholder** [comment]
Also just another bit of context to dump on this - for .well-known to work properly in almost all useful cases, you need to be able to serve it with appropriate CORS headers

**Comment by turt2live** [comment]
Was this feature accidentally removed in 1.0?

**Comment by jryans** [comment]
> Was this feature accidentally removed in 1.0?

Thanks for the reminder, as it looks like something similar was added in https://github.com/matrix-org/matrix-react-sdk/pull/2327. I think a combination of spots of unused properties plus the mockups I saw caused me to misunderstand and remove some portions of the previous work here. Sorry about that!

Anyway, I'll get to work reassembling the pieces.

**Comment by turt2live** [comment]
Also just a reminder that the display name is something I fought hard on last time due to phishing concerns.

**Comment by jryans** [comment]
> Also just a reminder that the display name is something I fought hard on last time due to phishing concerns.

I am fairly sure the display name bit will be deferred anyhow, so we can revisit the discussion before proceeding down that road.

**Comment by jryans** [comment]
I have deferred the more controversial display name idea to https://github.com/vector-im/riot-web/issues/8826.

**Comment by jryans** [comment]
> no server picker three-way option box

I am not entirely convinced that simply defining `default_server_name` should be a trigger to hide the 3 column selector. Doesn't seem like it would be a bit mysterious?

At the moment, I'm thinking we should leave the 3 column selector alone here and handle it separately. For example, in https://github.com/vector-im/riot-web/issues/8824, we might add a mode which disables custom HS for registration only, and that would also hide the 3 column selector as well.

@lampholder, any thoughts?

**Comment by jryans** [comment]
> @lampholder, any thoughts?

I discussed this with @lampholder, and we agreed to handle this part and more with separate config settings. I updated https://github.com/vector-im/riot-web/issues/8824 for this.

**Comment by jryans** [comment]
The main bit of this has been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2669 and https://github.com/vector-im/riot-web/pull/8832.

Additional parts have been deferred to https://github.com/vector-im/riot-web/issues/8824 and https://github.com/vector-im/riot-web/issues/8826.
