### ISSUE TITLE
Unable to delete a "Unnamed Room" from community

### ISSUE THREAD

**Issue by vranki** [vector-im/riot-web#8765]
### Description

I added a room to a community. The added room was named "Unnamed Room" and
cannot be removed.

The community in question is +community:hacklab.fi if you want to check for yourself.

### Steps to reproduce

(Not sure if the adding failure can be reproduced easily)

* Add a room to community (in this case a channel bridged from IRC)
* Observe it's name is "Unnamed Room"
* Delete the room from community
* "Failed to remove 'Unnamed Room' from +community:hacklab.fi"

Log: not sent

### Version information

* **Platform**: web

For the web app:

* **Browser**: Firefox 65
* **OS**: Ubuntu
* **URL**: Both riot.im/develop and riot.im/app

**Comment by kiliankoe** [comment]
Can I ask how you deleted the room from the community? I can't find a way to do that from within Riot.

**Comment by vranki** [comment]
It's well hidden (usability issue IMO):

* Go to https://riot.im/develop/
* Hover mouse over community on left, click on (...)
* Choose view community
* Click # in top right corner
* Click on room to remove
* Click remove from community

**Comment by kiliankoe** [comment]
Ah, thank you! I must've tried right-clicking and hovering over anything I could find, but I never thought to left click the room there 🤦‍♂️

**Comment by lampholder** [comment]
Sorry for the bad UI here - that's entirely of my doing :( 

i can't see the _Unnamed Room_ still associated with +community:hacklab.fi - did you manage to delete it in the end?

**Comment by vranki** [comment]
Looks like it's gone. I didn't manage to remove it. Maybe someone else did. 

I'll close the issue, reopen it if this happens again.
