### ISSUE TITLE
'Passwords don't match' doesn't disappear even when they match

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8769]
### Description

When creating an account, you may end up typing a password and a confirmation password. All is well you think, but oh noes!! You messed up and they don't match! Riot helpfully warns you of this before you click Register by showing a little "Passwords don't match" error at the top.

With lowered self-esteem, you go back to re-enter both passwords. Clicking off though, you see that "Passwords don't match" is still at the top! Is this right? Are you that tired that you *still* can't type your password twice?! You try again, and again. You resort to copy/pasting, but the error still persists!!!

And then, with a hint of faith, you click Register and find out your passwords were the same, you just messed up once.

The error should disappear once your passwords match, possibly even without clicking/tabbing off the field.

### Steps to reproduce

- Click Create Account
- Type in your details with a mismatching password and confirmation password
- Fix the passwords
- See that "Passwords don't match error *never leeeeaves*

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by jryans** [comment]
I agree that's quite annoying. 😭

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2672

**Comment by anoadragon453** [comment]
\o/
