### ISSUE TITLE
Rooms drop to the wrong place in the Roomlist after being read

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8774]
I'm assuming that @turt2live's https://github.com/matrix-org/matrix-react-sdk/pull/2634 will change this, but in the current implementation......

`<Fredrik>` random feedback (because I don't know where else to put it) a lot of people have complained that in the new UI the channels are sorted seemingly randomly. Like you have your unread activity ones on top as usual, but after that's been read, it goes to some weird place in the list, like it's not sorted by name and it's not sorted by activity

`<Erik>` That sounds like they have the option set to order the room such that unread rooms come first, which I didn't think was the default? The option is under Settings > Preferences > Room List

`<Fredrik>` well that's what they want, unread rooms first, then ordered by recent activity

so on the top you might have 2 or 3 rooms with unread activity, you go to check one and then it drops down to just below those with unread activity

like now it drops down and is buried by 10 channels that no one has touched in the last 6 months

but it's also not in alphabetical order, so really hard to find that channel again

it's the non-pinned rooms sorting that is different from old version

`<Erik>` Huh, and to be clear those rooms aren't bold?

`<Fredrik>` nope

![8dcb3f63-128b-4bf8-ad4d-083da20ec31f](https://user-images.githubusercontent.com/1294269/53010862-36e3e600-343f-11e9-9113-b4803734e4b2.png)

`<Fredrik>` like here, "Parity/Matrix VIP Support" is after the wasm and workshop ones, that haven't had activity in months

but the bold/pinned are at the top as they should be

but then if i read the governance one for instance, it'll drop down to where it isn't even visible in the list anymore

**Comment by turt2live** [comment]
Indeed fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2634

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2634
