### ISSUE TITLE
Settings action on room context menu

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8781]
### Description

![image](https://user-images.githubusercontent.com/1342360/53019003-afe93a80-344b-11e9-869b-d14c8045bb5f.png)

When changing a lot of settings on different rooms, it's a bit tedious to first have to click the room, then click the settings cog. It'd be nice to have a 'Settings' option directly in the context menu. Could possibly also take the person into the room when they click it.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2692
