### ISSUE TITLE
Cannot rejoin a room kicked from

### ISSUE THREAD

**Issue by grinapo** [vector-im/riot-web#8782]
### Description

When kicked from a room there's a choice of "Rejoin" or "Forget" room. 
It is not possible to rejoin since:
> "Failed to join room: No known servers"

It is not even possible to normally join by selecting the room from the room list since it offers the same possibilities.

I was able to join the room by manually issuing `/join <room id>`.

### Steps to reproduce

- use your own server, not matrix.org
- join #test:matrix.org
- ask a bot to kick you
- try to rejoin
May be related to what servers are on? What rooms you're joined? Etc...

### Version information

- **Platform**: web/chromium

For the web app:

- **Browser**: chromium Version 72.0.3626.7 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)
- **OS**: see above
- **URL**: private server, matrix-react-sdk version: <local> riot-web version: 1.0.1 olm version: 3.0.0

**Comment by lampholder** [comment]
Sorry it's been a while to follow up on this one - do you have any logs you can share?

**Comment by grinapo** [comment]
It seem to be fixed! Yay!
