### ISSUE TITLE
Username colour issue / color changing with app theme

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-web#8787]
My username color is changing depending on the theme.

There is an issue with the hash method for colors and the css. The color index is based on the hash % 8 , which is someting 0..7 but the style is defined as mx_SenderProfile_color[1..8]
Therefore color 0 is the default color for text (based on theme) and color 8 is never used.

In order to avoid changing existing colors (in version already released) , the mobile implementation will use username8 color for mx_SenderProfile_color0

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2664 right?

**Comment by jryans** [comment]
Yes, should be, thanks!
