### ISSUE TITLE
Getting rid of the bar on the left side of linux application

### ISSUE THREAD

**Issue by Mati20187** [vector-im/riot-web#8788]
- **OS**: Arch Linux

### Description

Yesterday I installed Riot.im client on my system. Everything is fine besides the bar on the left side of the program. It's pretty much useless and it uses a pretty big portion of the program's window. It also has a scrollbar, which does nothing. Is it possible to somehow hide this bar? I've been searching for such option in settings but found nothing.

### Steps to reproduce

- none

Describe how what happens differs from what you expected.

I'd love to have an option to disable this bar. 
![riot](https://user-images.githubusercontent.com/31066931/53023874-efb51f80-3455-11e9-82f7-4a0f771bedf8.png)

Log: not sent

**Comment by 4nd3r** [comment]
that's community bar. you can disable it in settings. 

tho, another question is why it's enabled by default and imho it should be shown only if you create/join your first community.

**Comment by BurnyBoi** [comment]
The only thing about 4nd3r's suggestion would be that it would also hide the button for the communities page, which would make it harder to reach the function to create a new community. 

I think a good counter-proposal would be to put an "add community" button at the top of the community filter panel so it makes it more clear what the panel is for. It could just be a big round button with a "+" similar to what Discord does with guilds. Not sure if there's already a request for this.

**Comment by Mati20187** [comment]
> that's community bar. you can disable it in settings.
> 
> tho, another question is why it's enabled by default and imho it should be shown only if you create/join your first community.

Can you tell me where excalty is the option to disable this bar? I'm scrolling through the settings for 4th time and I can't find it

**Comment by BurnyBoi** [comment]
It's under User Settings -> Preferences -> Advanced -> "Enable Community Filter Panel". Switch it off.

**Comment by Mati20187** [comment]
> It's under User Settings -> Preferences -> Advanced -> "Enable Community Filter Panel". Switch it off.

Thanks! I switched it off but forgot to restart the program
