### ISSUE TITLE
Feature Request: Option to disable media embeds

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/riot-web#8790]
### Description

When I use Riot at work, I don't want to see images or videos pop up on my screen. Someone could potentially post something NSFW. 

It would be helpful if, similar to Discord, there was a user setting to not embed videos and pictures uploaded directly to Matrix. When enabled, if someone uploads an embeddable file, it should show a placeholder with a link to view/download it, similar to what happens when someone uploads a non-embeddable file like a .txt file. I tried setting URL previews to off in a room, but understandably this doesn't affect media uploaded directly to Matrix.

As a workaround, I'm currently using uMatrix to block all images on the page. This also hides room/user avatars though, so it's not ideal.

**Comment by aaronraimist** [comment]
Sounds like #4286/#2466

**Comment by BurnyBoi** [comment]
#2466 makes it sound like they should still always display by default, but then allow you to hide them per-image afterwards. 

#4286 sounds more like it, but I think this should apply to videos too, since Riot currently displays the first frame of the video behind the play button.

**Comment by BurnyBoi** [comment]
#2466 makes it sound like the images should still display by default, but then allow you to hide them per-image after the fact. I think it should work the opposite, where you can choose to hide them by default, then have a button to show them if you want to see. 

#2466 sounds more like it, but this should apply to videos too, since Riot displays the first frame of the video behind the play button.

**Comment by BurnyBoi** [comment]
I added my comment about videos to #4286, and will continue the discussion there as needed. Thanks for linking those other issues.
