### ISSUE TITLE
Too many "Unable to decrypt" error after logging in a web client

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-web#8795]
I logged in a Riot web client (Safari (Version 12.0.2 (14606.3.4)) and accepted (without verifying) all the keys sharing requests observed in Riot on another web client (Google Chrome Version 71.0.3578.98).

I observed a lot of "Unable to decrypt" errors in my encrypted rooms, mainly for the 10 last messages.
- Scrolling in the room history seems working correctly (I received on my other browser the keys request, and accepted them, then the old messages are decrypted)
- About the UISI, I re-requested the keys, but I never received the demand on Chrome, and the decryption error is not fixed.

<img width="762" alt="screenshot 2019-02-19 at 19 48 48" src="https://user-images.githubusercontent.com/8969772/53039750-22740d80-3480-11e9-97f9-a3f6f66865d0.png">

**Comment by giomfo** [comment]
@uhoreg: FYI this is another case where we observed a lot a "Unable to decrypt" error (Web Safari <-> Web Chrome), which impacts DINSIC too

**Comment by manuroe** [comment]
> * About the UISI, I re-requested the keys, but I never received the demand on Chrome, and the decryption error is not fixed.

This is a known issue: https://github.com/vector-im/riot-web/issues/6838.

**Comment by manuroe** [comment]
> I observed a lot of "Unable to decrypt" errors in my encrypted rooms, mainly for the 10 last messages.

My 2cts, it looks like riot-web does not make keyshare requests for events received in the initial `/sync`.

If this is the intended behaviour of the riot-web code, this is great because it avoids to send hundreds of key share requests when logging in on a new device. This is a feature I wanted to propose because I just noticed all the noise for that on riot mobile apps.

Of course, the app should then request keys on display.

**Comment by uhoreg** [comment]
> My 2cts, it looks like riot-web does not make keyshare requests for events received in the initial /sync.

It looks like it does make keyshare requests for those events, and it's sending them, but I'm not seeing them show up on the other side for some reason.
