### ISSUE TITLE
Receiving a keyshare request cancels your ongoing verification of another device

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8798]
Caused by https://github.com/vector-im/riot-web/issues/5828 in my case, in bout of bad timing.

1. Log in to Device A
2. Receive a keyshare request from Device B
3. Start verification with Device B
4. Receive a keyshare request from Device C
5. Device B says the verification was cancelled

Then it all falls apart:
6. Verify Device C with Device A
7. Receive a keyshare request from Device A on Device B
8. On Device B, verify Device A
9. Your verification between A and B resumes
10. You're left totally confused, wondering what you just verified and if all the devices are working

**Comment by turt2live** [comment]
@lampholder what sort of UX should we do here? Put the keyshare on hold until verification completes or something more involved like https://github.com/vector-im/riot-web/issues/9554 ?

**Comment by lampholder** [comment]
Can the second request fail with a notice "this user cannot be verified at this time, please try again shortly"?

It's not something that we'd expect to happen very often, and, if people are using verification synchrously as is intended, such a failure should be resolved by the verifiee explaining to the verifier that they need to hold on a sec whilst they finish the first verification.

The important thing is that your legitimate verification attempts can't be frustrated by random requests from other users.

**Comment by turt2live** [comment]
Not all keyshare requests are manually sent. As mentioned in the issue, the case for this one was an automatic part of Riot.

Not sure if that changes your answer.

**Comment by lampholder** [comment]
Oh _keyshare_. Reading all the words dramatically changes my answer, sorry.

A keyshare request should never interrupt a verification.

Worst case, the keyshare request (manual or automated) can be retried manually after.
