### ISSUE TITLE
Room tiles missing from list

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8801]
![image](https://user-images.githubusercontent.com/1190097/53053486-b8973c00-345e-11e9-815f-cfe79324e276.png)

I refreshed and saw this. The scrollbar hints at there being more tiles, but doesn't render them.

**Comment by turt2live** [comment]
and 10 minutes later for no obvious reason, #matrix-dev shows up:
![image](https://user-images.githubusercontent.com/1190097/53053966-255f0600-3460-11e9-9e7f-195c847cbaf6.png)

**Comment by lampholder** [comment]
Is this still happening anyone? I haven't noticed it.

**Comment by turt2live** [comment]
nope, this was fixed by one of the "room list algo is being dumb" fixes
