### ISSUE TITLE
Weird autocomplete on room member filter

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8806]
![image](https://user-images.githubusercontent.com/1190097/53057440-b0de9400-346c-11e9-9f6c-cf37e970dcb6.png)

**Comment by t3chguy** [comment]
I'd argue this filter and the top left filter should have autocomplete disabled

**Comment by turt2live** [comment]
I actually suspect this is an artifact of https://github.com/vector-im/riot-web/issues/8789 or https://github.com/vector-im/riot-web/issues/8713 or any of the other password manager bugs where it sticks the username in random inputs.

**Comment by lampholder** [comment]
Yeah, looks like it. Let's tackle https://github.com/vector-im/riot-web/issues/7861 and hopefully it'll resolve the fringey bits like this.

**Comment by turt2live** [comment]
It'll resolve it landing a username in there, but people already bitten won't be fixed. We might want to consider sticking whatever flags we can on fields to not have them autocomplete.
