### ISSUE TITLE
Room tiles are blank after shrinking the window to be small enough for LeftPanel collapse and then expanding it manually 

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8810]
This bit me on stage at FOSDEM:

https://youtu.be/DZBvy4abB1o?t=1153

<img width="1183" alt="screenshot 2019-02-20 at 02 39 06" src="https://user-images.githubusercontent.com/1294269/53062507-f0cb6880-34b8-11e9-9023-ee9ba8ffd0a6.png">

and it's biting others too:

![screenshot from 2019-02-19 21-31-38](https://user-images.githubusercontent.com/1294269/53062522-fb85fd80-34b8-11e9-87b1-452562831296.png)

see https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1550629966212125XrJaf:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org

It looks curiously similar to #6919 and #6594 but is more reproduceable

**Comment by xloem** [comment]
After reading your summary of this bug, I found what triggers it on my system.  If the window is too small to display the labels _at launch_, it will never display them throughout its lifetime.  If the window is large enough to display them at launch, it will keep on displaying them when resized large.

**Comment by lampholder** [comment]
@ara4n Can you still reproduce this?

@xloem Does your approach still reproduce this for you?

**Comment by xloem** [comment]
@lampholder, this is still happening for me with both riot 1.0.3 desktop and https://riot.im/app on windows 10, but not with riot 1.0.3 on red hat linux.  I'm guessing I wasn't using linux before.

**Comment by turt2live** [comment]
I remember us fixing this since March. If it's still happening to people, please open a new issue.
