### ISSUE TITLE
Address privacy concerns over connections to Google servers

### ISSUE THREAD

**Issue by shiftee** [vector-im/riot-web#8817]
### Description

I came across [this](https://old.reddit.com/r/privacytoolsIO/comments/arg79n/lets_talk_about_the_new_riot_update/?st=jscyuvgb&sh=373f913d) thread on reddit.com/r/privacytoolsIO

There are privacy concerns due to the following connections to Google servers:
1. fonts.gstatic.com
2. www.google.com
3. ajax.googleapis.com

Can you please give a response to this?

I'm sure that any connection to Google servers is done with good reason but it's also important that Riot is squeaky clean from a privacy perspective.

Keep up the good work

**Comment by jryans** [comment]
What version of Riot are you testing?

Can you describe what steps you went through when you saw these loads? Login, registration, already logged in, etc.?

In recent versions of Riot, all fonts should be served from Riot itself, so there shouldn't be any direct loads from `fonts.gstatic.com` in Riot.

I can't see any direct usages of `ajax.googleapis.com` in Riot today.

Some homeservers (like matrix.org) may use Google's reCAPTACHA, so this would trigger a load from `google.com`, but this only happens during account creation. (It does create an `iframe` which may load more resources from other domains, including but not limited to all 3 listed here.) We're well aware it would be better to use something else for captchas, but so far haven't found a great alternative (see https://github.com/vector-im/riot-web/issues/3606).

As a summary, we'd of course like to avoid any loads from Google. As far as I know, the only case today should be the possible load of reCAPTACHA (this is only loaded if your homeserver requires it during account creation).

**Comment by shiftee** [comment]
I didn't perform the test myself so I can't say.

I created this issue primarily to bring attention to bad publicity Riot is getting in that privacy-focused reddit thread.

I will point the author of the thread to this issue and perhaps they will supply more info

**Comment by antonizoon** [comment]
Is it possible to consider the use of alternative captcha systems equal in design to Google Recaptcha, such as Coinhive? It would allow such JavaScript to be self hosted, uses proof of work to make spam expensive, and causes attackers to earn the website some money. If coinhive is blocked by adblock systems (sometimes people get even more angry about mining than ads), then users could get to use google recaptcha as a fallback. :^)

https://coinhive.com/documentation/captcha

**Comment by antonizoon** [comment]
When it comes to the Google fonts usage in riot.im, this may originate unintended from a JavaScript library that unnecessarily imports fonts from Google Fonts that could be self hosted or just rely on local fonts instead. Please audit your dependencies to see which library is the culprit.

**Comment by jryans** [comment]
> When it comes to the Google fonts usage in riot.im, this may originate unintended from a JavaScript library or CSS that unnecessarily imports fonts from Google Fonts that could be self hosted as a theme or just rely on local fonts instead. Please audit your dependencies to see which library is the culprit.

The fonts on riot.im are self-hosted.

**Comment by jryans** [comment]
> Is it possible to consider the use of alternative captcha systems equal in design to Google Recaptcha, such as Coinhive? It would allow such JavaScript to be self hosted, uses proof of work to make spam expensive, and causes attackers to earn the website some money. If coinhive is blocked by adblock systems (sometimes people get even more angry about mining than ads), then users could get to use google recaptcha as a fallback. :^)
> 
> https://coinhive.com/documentation/captcha

Let's use the existing #3606 for captcha alternatives.

**Comment by jryans** [comment]
From the evidence presented so far, these requests seem to be related to Google's reCAPTCHA. The issue author doesn't have more detail about the requests, which I think we'll need to investigate further, so let's close this.

If someone is observing such third-party requests in some context other than captchas during registration, please file an issue and we'll investigate further.

**Comment by antonizoon** [comment]
Through basic code auditing, I can tenatively confirm independently that riot.im web does not directly use any google libraries, other than recaptcha served from the homeserver and used at homeserver discretion (meaning that you could self host your own homeserver that uses your own captcha solution as stated in [this issue]())

https://github.com/vector-im/riot-web/search?q=google&unscoped_q=google

I have also did a basic audit of the served browser code from riot-web and there is no sign of any direct use of Google fonts or Javascript dependencies there (other than Google Recaptcha at sign in only) as reported by uMatrix or decentraleyes.

The author's screenshot is actually of a scan notification on riot-android, which is more likely to have unintended use of Google Fonts using some backend Android library, as it was made by Google it is very plausible that they rely on that too. Please audit that too.

https://github.com/vector-im/riot-android/search?q=fonts.google&unscoped_q=fonts.google
