### ISSUE TITLE
Use the homeserver in the Matrix ID if server discovery failed

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#8818]
I often use https://riot.im/develop (to avoid the troubles of having to build the `develop` branch myself), and sometimes I try to connect to a homeserver, using a full MXID like `@alice:matrix.example.com`, that has no `/.well-known/matrix/client` file. This causes server discovery to fail and Riot to try and authenticate the user against `matrix.org` (the default server in Riot's configuration) instead of `matrix.example.com`. It might be just me, but it feels really counterintuitive to me.

**Comment by turt2live** [comment]
As per https://github.com/vector-im/riot-web/issues/9290, the decision here is to just fail the user's ability to log in. It should not default to matrix.org - that is a bug.
