### ISSUE TITLE
ugly system tray icon [solved]

### ISSUE THREAD

**Issue by DoctorSubtilis** [vector-im/riot-web#8819]
- Linux (Kubuntu 18.04)

### Description

The system tray icon seems very strange and ugly  

### Steps to reproduce

- launch riot-web  
- icon appears in system tray
- but she is not the correct riot icon, she seems in wrong size

![riot icon bug](https://user-images.githubusercontent.com/20089138/53086470-78d75f80-3505-11e9-8893-49bde547dc8f.jpg)
 [the riot icon is the blue one]

Log: not sent

**Comment by drathir** [comment]
Interesting what i can confirm that Arch have nice (i guess valid) one:  ![image](https://user-images.githubusercontent.com/4871862/53092124-35d0b880-3514-11e9-88e6-642cfbb2a236.png)

**Comment by DoctorSubtilis** [comment]
It's the same I have in KDE menu: but not system tray :(

**Comment by zink-chimaera** [comment]
> It's the same I have in KDE menu: but not in system tray :(

Same here. Could reproduce on Neon 16.04.

**Comment by Ksenar** [comment]
kde neon
solved the problem with the installation libappindicator3
`sudo apt install libappindicator3-1`
and launch riot through XDG_CURRENT_DESKTOP=Unity
`XDG_CURRENT_DESKTOP=Unity /opt/Riot/riot-web --hidden`

**Comment by DoctorSubtilis** [comment]
Thank you very much: solved!

**Comment by jryans** [comment]
Does this mean `riot-web` should depend on `libappindicator3`? (My knowledge of Linux desktop environments is limited...)

**Comment by DoctorSubtilis** [comment]
I had already installed `libappindicator3`; if you don't, you can try to install it.

**Comment by jryans** [comment]
Okay, will close for now I guess... If there's something Riot itself can do to improve this, please let us know.

**Comment by zink-chimaera** [comment]
So is this an error within KDE? If not you should fix the behaviour depending on  XDG_CURRENT_DESKTOP imo. I'm currently hot-fixing the .desktop file locally but I wouldn't expect that from every user. ¯\_(ツ)_/¯

Here's my /usr/share/applications/riot-web.desktop:
`
[Desktop Entry]
Name=Riot
Comment=A feature-rich client for Matrix.org
Exec=XDG_CURRENT_DESKTOP=Unity "/opt/Riot/riot-web" %U
Terminal=false
Type=Application
Icon=riot-web
StartupWMClass=riot
Categories=Network;InstantMessaging;Chat;

`

**Comment by jryans** [comment]
If we should edit the `.desktop` file for everyone, we could do that, but it's not clear to me whether that's actually correct or not.

**Comment by akontsevich** [comment]
Think #7553 and #7624 could be closed for now: works fine if libappindicator3 (libappindicator-gtk3) not installed. Unlike #6767 and #8819 (icon look) should be reopened and fixed: stopped to work even if I run with `Exec=XDG_CURRENT_DESKTOP=Unity riot %U`. For now icon looks like blank black square in KDE which is weird. I think local electron version used to build riot should be manually patched like Skype done previous year, where icon looks good for now with whatever appindicator is used or not, Unity desktop set or not. Otherwise we can wait too long it will be fixed in Electron. Makes sense?
