### ISSUE TITLE
Mobile Guide suggests not changing the IS URL even though a custom default IS is defined

### ISSUE THREAD

**Issue by thegcat** [vector-im/riot-web#8825]
### Description

The `/mobile_guide` page shows the following note:

```
Note: You shouldn't need to modify the identity server field, which by default is set to https://vector.im.
```

This is erroneous and has caused a few users trying to register on our server to fail registration. We offer our own Identity Server.

Furthermore our Riot Web installation has, amongst others, the following configuration bits:

```json
    "default_hs_url": "https://matrix.kif.rocks",
    "default_is_url": "https://matrix.kif.rocks",
    "disable_custom_urls": true,
```

This all works well for Riot itself. The mobile guide should also reflect those settings, in this case it should not even hint at other identity servers being usable as `disable_custom_urls` is `true`.

### Steps to reproduce

Install Riot Web with the config above.

### Version information

- **Platform**: web
- **Browser**: Safari, though the users were mostly using Chrome
- **URL**: https://riot.kif.rocks/mobile_guide/ currently version 1.0.1

**Comment by jryans** [comment]
Thanks for the report! This seems like a good enhancement to add.

**Comment by jacotec** [comment]
I just was about to file this bug as well when Github showed me this :-)

That's annoying, I need to tweak the index.html in mobile_guide as well after each update of Riot-Web.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3001 - it won't make it into 1.2.0, but should be in the next regularly scheduled release.
