### ISSUE TITLE
Support HS display names defined in .well-known client metadata

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8826]
It's been suggested that 'Create your lant.uk account' might itself be confusing - if lant.uk were a large organisation it's likely they would already _have_ something they think of as a lant.uk account. 

It's also been raised that whilst lant.uk is the most sensible domain part for their mxids, they might prefer to be represented in the UX by their full company name, or similar.

Two possible independent mitigations for this:
- Change the 'Create your ________ account' wording to read 'Create your _______ matrix account' (making it more obviously distinct from whatever other accounts/infrastructure exist on lant.uk) (handled in https://github.com/vector-im/riot-web/issues/8763)
- Support a server's "Display Name" via a .well-known option
```
    {
        "m.homeserver": {
            "base_url": "https://matrix.lant.uk",
            "display_name": "Lant ltd."
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    }
```

_Originally posted by @lampholder in https://github.com/vector-im/riot-web/issues/8763#issuecomment-464823909_

As @turt2live points out, this does introduce some risk of phishing attacks where an evil server masquerades as an organization you trust via the display name in order to hijack your account.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3001 - it won't make it into 1.2.0, but should be in the next regularly scheduled release.
