### ISSUE TITLE
Clicking X/Ok on 'Failed to get public room list' will drop me back on the room list, causing a loop

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#8827]

**Comment by lampholder** [comment]
Do you have repro steps for triggering 'Failed to get public room list'?

**Comment by Half-Shot** [comment]
I did this on the kde public instance, lemme try there again.

**Comment by Half-Shot** [comment]
Going to close this until I can repro

**Comment by jryans** [comment]
We also changed the dialog 7 days ago in https://github.com/matrix-org/matrix-react-sdk/pull/2834 so that the failure is now inline, so that probably fixes this as well.
