### ISSUE TITLE
Can we hide the algo used when turning on encryption

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#8829]
at least on /app as 'Amandine turned on end-to-end encryption (algorithm m.megolm.v1.aes-sha2)' is ugly as hell

**Comment by lampholder** [comment]
Yeah, this is certainly in @nadonomy's crosshairs for dejargoning the app

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2939)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/897)

**Comment by jryans** [comment]
While chatting more with @ara4n, he would like to have some kind of handling of unknown algorithms at the same time as the propose hiding here. I think he came up with a decent approach:

* When the algorithm is the one we expect (`m.megolm.v1.aes-sha2`), hide the algorithm as in this existing PR: %(senderName)s turned on end-to-end encryption.
* For anything else, show the algorithm as unrecognised: %(senderName)s turned on end-to-end encryption (unrecognised algorithm %(algorithm)s).
