### ISSUE TITLE
room creation events should be collapsed into a MELS-style summary

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8830]
rather than taking up 6 lines, one per matrix event

**Comment by AmandineLP** [comment]
A lot of them shouldn't even appear IMO

**Comment by lampholder** [comment]
This too is part of the dejargoning drive.

**Comment by t3chguy** [comment]
Current plan, get a mockup of a MELS style thing which amalgamates all the room config events until the first message, that way someone can spin up a room, tweak some settings, and use it without a massive backlog.
