### ISSUE TITLE
Allowed characters error on registration is unhelpful

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8839]
![image](https://user-images.githubusercontent.com/1190097/53122756-a677d500-3514-11e9-814b-2958cbf8bf71.png)

(ignore the blue highlight - that's Chrome trying to be helpful)

This leaves me asking the question "what needs these characters?"

Steps to reproduce:
1. Press register without entering anything

**Comment by jryans** [comment]
Thanks for the report. This is related to the "quick wins" on validation that removed the "shaking" on field error. Now it's not clear which field has the validation error, so maybe the best fix it update the text for now. (Eventually, we hope to have validation tooltips pointing at the field.)

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2673
