### ISSUE TITLE
Having a default_hs_url shouldn't leave you at the server picker

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8840]
![image](https://user-images.githubusercontent.com/1190097/53122817-d7f0a080-3514-11e9-8a2d-5f583225adc2.png)

I would expect to be left at a place where I can enter a username for the server, not verify the URLs.

Config:
```
{
  "default_hs_url": "https://dev.t2host.io"
}
```

URL visited: /register

**Comment by jryans** [comment]
Ah yeah, I agree. Same for the case of `default_server_name` as well.

**Comment by jryans** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2675
