### ISSUE TITLE
Add a confirmation prompt before actually enabling encryption

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8843]

**Comment by TUSF** [comment]
The prompt should also make obvious that, not only will the change be permanent, but what "Encryption" actually means for a room.

**Comment by uhoreg** [comment]
Warning could be something along the lines of: "Encryption may prevent integrations such as bots and bridges from working correctly in this room.  Once encryption is enabled, it cannot be disabled."

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2728
