### ISSUE TITLE
Search always returns no results

### ISSUE THREAD

**Issue by remeisigma** [vector-im/riot-web#8844]
### Description

Searching for past messages in encrypted rooms always returns "no results"

### Steps to reproduce

-In an encrypted room, click magnifying glass in top right
-Enter a search term you expect to have results

Describe how what happens differs from what you expected.

-Search returns "No results"
-Expected behavior: Search returns results matching search term

Log: Not sent; issues submitting logs    

<img width="1076" alt="screen shot 2019-02-20 at 7 18 24 pm" src="https://user-images.githubusercontent.com/18301092/53136391-734d3a00-3544-11e9-8a2d-9fdf3e00428e.png">
<img width="1071" alt="screen shot 2019-02-20 at 7 18 33 pm" src="https://user-images.githubusercontent.com/18301092/53136390-734d3a00-3544-11e9-977a-d8d59f137e27.png">
<img width="1076" alt="screen shot 2019-02-20 at 7 18 40 pm" src="https://user-images.githubusercontent.com/18301092/53136388-734d3a00-3544-11e9-9a2e-121d5a86b8a9.png">

(Deleted messages at the bottom of the room are unrelated to the bug; bug existed before I redacted their contents)

### Version information

- **Platform**: Desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: macOS
- **Version**: 1.0.1

**Comment by turt2live** [comment]
This would be fixed by https://github.com/vector-im/riot-web/issues/2548
