### ISSUE TITLE
Room categories can be much larger than they should be

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8859]
![image](https://user-images.githubusercontent.com/1342360/53183578-7eab6e80-35f3-11e9-9b0e-9b8bed9a2d97.png)

### Description

Room categories can get into a state where one of them (always favorites for me) can become a much larger scrollable area than it should be.

### Steps to reproduce

Happened initially by filtering by a community then unfiltering. Now Riot remembers this broken configuration and loads it every time I refresh :')

Describe how what happens differs from what you expected.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: self-host of  riot.im/develop

**Comment by turt2live** [comment]
@anoadragon453 if you refreshed in the last 15ish minutes, you're running into https://github.com/vector-im/riot-web/issues/8857

**Comment by anoadragon453** [comment]
Yeap, sure did.

**Comment by anoadragon453** [comment]
Feel free to close as dup.

**Comment by turt2live** [comment]
(if it happens after https://github.com/matrix-org/matrix-react-sdk/pull/2674 lands, please reopen)

**Comment by anoadragon453** [comment]
Refreshed and still have this issue this morning. May be due to Riot saving the broken layout?

Can clear cache and reload but also might not want to break the test case.

**Comment by turt2live** [comment]
There was another bug. Are you still seeing this after https://github.com/matrix-org/matrix-react-sdk/pull/2681 ?

**Comment by anoadragon453** [comment]
Not anymore no, I think that PR has done it. I'll let you know if it pops up again though :)
