### ISSUE TITLE
Redacted messages (and potentially other types) visual design

### ISSUE THREAD

**Issue by matrixes** [vector-im/riot-web#8873]
- **Browser**: Chrome, Safari, Firefox? which version?
Any

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Any

### Description

This is a re-iteration of https://github.com/vector-im/riot-web/issues/8559#issuecomment-463832773 in #8559 and an inclusion of #3657

Make the redacted highlight into something _visually similar_ to join/leave messages.

![52822131-28997100-30b1-11e9-88e3-0f9201d838a2](https://user-images.githubusercontent.com/46491408/53232086-a26dc380-368a-11e9-82fa-0b38543c9d50.png)

There are a few ways you can make it "unique" if that's what you're going for. Custom icon and text color for one.

I'm actually not really sure why the redacted highlight has taken such a prominent place in the chat (I'm new to Synapse/Matrix/Riot, so I don't have the background yet), as it is.
The way it's presented right now (the striped graphic), redactions are among the single most important events in the chat.

This may be my personal view, but I definitely want them to be lowlights, not highlights. I want to be aware of them, but only in my peripheral view. If I'm interested in redacted messages, I'll go look for them, but I don't want to become aware of every single time it happens. It's impossible to ignore them at this point.
Also, having this as a text phrase instead of a striped "thing", makes it easily searchable, if that's a concern.

I (as many others, I'm sure) have used both Slack and Discord and they have way less intrusive (none at all, really) indicators/highlights that a message has been removed.
They do have something for _modified/edited_ messages, but that is another topic.
For redaction/removal, Riot is the first I've come across that makes such a "big deal", in lack of a better phrase/word for it, out of redacted messages, and I'm not geling with them, and it looks like others have had the same thought as well.

**Comment by t3chguy** [comment]
https://www.figma.com/file/24AolJtg1WOTvhm0EA35S1/Deleted-messages

**Comment by matrixes** [comment]
@t3chguy This Figma service, I'm just getting a login wall when I click the link, so I can't review it. Or that's on purpose?

**Comment by t3chguy** [comment]
The above-linked PR doesn't collapse sequential redactions, will handle that as a separate task as it ended up more involved than simply using ELS due to the alternate semantics, ELS being generic to not be just a single sender
