### ISSUE TITLE
Tag Notification is a multiple of the actual amount of notifications

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8874]
![image](https://user-images.githubusercontent.com/1342360/53234547-a9df9d80-3687-11e9-9809-c47916c1ca7b.png)

![image](https://user-images.githubusercontent.com/1342360/53234587-c2e84e80-3687-11e9-9319-6bb60cf54b4d.png)

### Description

For some reason the notifications of a group is a multiple of the notifications of the rooms that it contains. Every time I receive a notification in this room the amount of rooms goes up n where n = n + 2 each time it happens.

This seems to only be happening to my favourites, which is currently afflicted by #8859, so no idea if this is related or not.

Log: sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: Independent build of riot.im/develop

**Comment by turt2live** [comment]
There was another bug. Are you still seeing this after https://github.com/matrix-org/matrix-react-sdk/pull/2681 ?

**Comment by anoadragon453** [comment]
Seems to have been fixed, thanks!
