### ISSUE TITLE
Source maps seem to be invalid, breakpoints don't work

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8880]
We suspect this has been broken since the introduction of image cache busting, but that's unverified. 

@ara4n found one fix by changing `devtool` to `eval-source-map`, but this bloats production files and crashes builds on some machines, so we need another way.

**Comment by jryans** [comment]
The current status here is more nuanced than I thought:

* For me:
  * Firefox Nighty: Original source mapped, but bps never hit
  * Chrome Canary: Original source mapped, bps seem to hit correctly
* For Travis:
  * Original source mapped, but sometimes off by ±2 lines
* For Matthew:
  * Original source mapped, but sometimes off by ±4 lines, both Firefox and Chrome

**Comment by jryans** [comment]
Updated above status. Firefox Nightly seems okay for me now. I had a bad configuration setting locally.

**Comment by jryans** [comment]
Does anyone have a specific example of "source maps are bad here"? It's possible only certain areas of the code base have issues, so focusing on a specific issue report and trying to fix it should help.

**Comment by turt2live** [comment]
The Notifier is particularly bad to try and debug in. Off by a couple lines, breakpoints move around on refresh, etc. All in chrome.

**Comment by turt2live** [comment]
This is threatening cross-signing, so taking it up now.

**Comment by turt2live** [comment]
for documentation purposes: The proposed plan is to rip out the dual babel setup and replace it all with one webpack. Babel will still exist for npm publishing purposes.
