### ISSUE TITLE
Media links don't seem to respect .well-known settings

### ISSUE THREAD

**Issue by targodan** [vector-im/riot-web#8881]
### Description

I have a matrix setup for my domain `targodan.de` with both server and client well-known pointing to `matrix.targodan.de`. When I send an image via riot though, the download link shows up as `https://targodan.de/_matrix/media/v1/download/targodan.de/...`.

I would expect this to be `https://matrix.targodan.de/_matrix/media/v1/download/targodan.de/...`, as defined in my well-known. Whether this should be read from the client or server well-known though I cannot judge.

My client well-known:
```
{"m.homeserver":{"base_url":"https://matrix.targodan.de"},{"m.identity_server":"https://vector.im"}}
```

My server well-known:
```
{"m.server":"matrix.targodan.de:443"}
```

I first noticed this on the desktop riot, but it's also the case for my self-hosted riot installation.

I have not yet tested it with resources other than images.

### Steps to reproduce

- Setup a HS on a subdomain
- Setup client and server well-knowns on the domain
- Login via Riot and send any image
- Take a look at the download link in riot

Log: not sent

### Version information

- **Platform**: web (in-browser) *and* desktop?

For the web app:

- **Browser**: Chrome
- **OS**: Arch Linux
- **Version**: 1.0.1

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.0.1

**Comment by lampholder** [comment]
I have (on lant.uk) essentially the same .well-known config, and I'm getting the right media repo links.

Are the images appearing correctly in Riot, or is every image resource broken?

**Comment by targodan** [comment]
I just checked again and now even uses the correct links. 🤔 

I think I observed this in a transition state, where I already had the well-known but port 8448 was still open (hence the images still worked but I was concerned about what would happen when I closed port 8448). Since then I closed the port, having forgotten about my concerns.

I guess the lack of a well-known was still buffered or riot tries 8448 before checking the well-known.

I'm closing this, since everything is working now, even with port 8448 closed. Sorry for making a fuss.

**Comment by t3chguy** [comment]
Did you log out and back in? As I understand it, it is queried at log in time only

**Comment by targodan** [comment]
I just tried stopping to proxy on `targodan.de` and my riot now claims it cannot connect to the HS. It even shows this in the login screen:

```
Can't connect to homeserver - please check your connectivity, ensure your homeserver's SSL certificate is trusted, and that a browser extension is not blocking requests.
```

**Comment by targodan** [comment]
Does riot not support the client well-known at all?

Here is my client well known: https://targodan.de/.well-known/matrix/client
And I tell riot my homeserver is "https://targodan.de"

**Comment by aaronraimist** [comment]
If you tell Riot your homeserver URL is https://targodan.de then it will use that as the homeserver URL and won't perform a .well-known lookup. It only uses `/.well-known/matrix/client` when you enter a username (for example @bob:targodan.de) in the username field.

**Comment by targodan** [comment]
So sorry, I completely forgot about this issue. It's been resolved by now.

I had to logout and login again after changing the well-known. That made riot login to my server using the url in the well-known (matrix.targodan.de) and thus also access media via that same link.
