### ISSUE TITLE
Unknown device warnings better visible in dark theme

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#8882]
The warning sign for unsafe messages in E2E rooms - the circle with the exclamation mark - doesn't jump out, as warnings ought to do, in the black theme.

**Comment by lampholder** [comment]
Do you mean this one? 
![image](https://user-images.githubusercontent.com/1922197/53730448-df4a6f00-3e6f-11e9-9495-18a7bb56c414.png)

Or this one?
![image](https://user-images.githubusercontent.com/1922197/53730468-f38e6c00-3e6f-11e9-80b6-9e6ab8946d59.png)


Thanks!

**Comment by Biep** [comment]
The first one - the circle with the exclamation mark.  In the dark theme a bright colour should be used.

**Comment by aaronraimist** [comment]
<img width="36" alt="Screen Shot 2020-01-21 at 12 31 53 AM" src="https://user-images.githubusercontent.com/5855073/72780818-6ec25300-3be5-11ea-9599-900eca5e6c14.png">
I think this is fixed now
