### ISSUE TITLE
Save button for room addresses does not work and shows no error

### ISSUE THREAD

**Issue by matthijskooijman** [vector-im/riot-web#8887]
### Description
I just created a new room, set a title, set the room to be joinable by guests and then tried to add a room address. Adding it seems to work at first:

![image](https://user-images.githubusercontent.com/194491/53254007-cf3dcd00-36c2-11e9-85c2-14d462e6d1b8.png)

But then I click "save" and nothing happens. Closing the settings and reopening them shows the address was not added. Checking the developer tools shows that there are some errors happening. In particular, I see a 403 on a PUT request to https://matrix.org/_matrix/client/r0/directory/room/%23test-alias-asdfasdf%3Amatrix.org, with a response body of:

    {errcode: "M_UNKNOWN", error: "Not allowed to create alias"}

I'm not sure why this happens, since the permissions seem to be ok:

![image](https://user-images.githubusercontent.com/194491/53254298-6440c600-36c3-11e9-9097-76a25a2d334e.png)

Changing the access policy back to "Only invited" does not fix this either. I just tried creating a brand new room, which seems to have the same problem (create room -> add alias -> broken). Removing the dashes from the address also doesn't help. Using Riot on Android also shows "Not allowed to create alias".

If anyone wants to investigate the error itself, the room is https://riot.im/app/#/room/!GWbmKIbihEfXbNGheu:matrix.org, but I think the more import problem here is that no proper error message is shown in the webclient, instead just nothing happens.

I tried this on both Chromium 64 and Firefox 52 on Linux Debian stable.

### Version information
https://riot.im/app
matrix-react-sdk version:
riot-web version: 1.0.1
olm version: 3.0.0

**Comment by turt2live** [comment]
The save button's existence is solved by https://github.com/matrix-org/matrix-react-sdk/pull/2679, however it looks like you're running into some other issue. We had a minor configuration mishap on matrix.org - everything should be working now, are you able to confirm?

**Comment by matthijskooijman** [comment]
Yup, seems to work again now, so I just tried at a bad time.

Still, this means that currently the webapp is hiding server errors, leaving the user without any clue what's happening. Does the PR you linked also fix that? If not, this issue should be left open to track that issue?

On a related note, I noticed that the current code actually repeats the PUT request for a new alias if you click the save button twice (even when the first one is successful), resulting in a 409 Conflict result on the second attempt. However, looking at your PR, I suspect that that is implicitly solved by the way aliases are added now.

**Comment by turt2live** [comment]
Errors are shown with the PR as well - I tested this between verifying the issue on matrix.org and saying this :)

Going to close this as I think all the concerns are addressed - if something does come up, please open up a new issue and we can track it there.

**Comment by matthijskooijman** [comment]
Thanks!
