### ISSUE TITLE
Guest access to rooms not working?

### ISSUE THREAD

**Issue by matthijskooijman** [vector-im/riot-web#8888]
### Description

I created a new room, added a room alias and set access to allow guests, opened the room link in a private tab, but Riot insists that I register for an account rather than allowing to join the room as a guest.

When I open [the room link]() in a private browsing tab, I get a page that asks me to join the room. When I click, a popup opens saying registration is required:

![image](https://user-images.githubusercontent.com/194491/53261596-b9d19e80-36d4-11e9-81f4-bc777d60e93c.png)

AFAICS, the security settings for the room are correct:

![image](https://user-images.githubusercontent.com/194491/53261646-d4a41300-36d4-11e9-8739-922228e5fbb1.png)

Loading this page with devtools open shows there are some 403 errors underneath:

![image](https://user-images.githubusercontent.com/194491/53261770-25b40700-36d5-11e9-9d46-ec461d4cf462.png)

I also tried making the room history visible to anyone, which shows a preview of the room, but still insists on registering when I click to join. It also fixes some 403s, but not others:

![image](https://user-images.githubusercontent.com/194491/53261967-b1c62e80-36d5-11e9-9518-a1a76abf18c3.png)

I suspect this is more of a server problem than a riot-web problem, but I couldn't find the proper place to file bug reports against the matrix.org instance, so I went ahead and filed it here. @turt2live you mentioned something about reconfiguring the server recently, so you might be interested in this report too.

**Comment by turt2live** [comment]
Riot actually disabled the guest view of things while the UX is reworked a bit. Here's some issues which track the various moving parts for this:

* https://github.com/vector-im/riot-web/issues/8384
* https://github.com/vector-im/riot-web/issues/8522
* https://github.com/vector-im/riot-web/issues/8808

**Comment by matthijskooijman** [comment]
Ok, thanks for pointing that out. Seems that for now, ILAG is disabled (#8222) until the authentication UI is reworked.

Can you tell me what ILAG stands for? I've looked around, but could not find it anywhere. It seems to be some kind of extensible flow specification for authentication and registration, I think?

However, does this "ILAG" thing (when it is eventually re-enabled) actually allow real guest access? Or does it just allow registering password-less accounts, littering the server with unused, inaccessible accounts? #4724 actually suggests the latter? I guess this is also the subject of #8522?

**Comment by turt2live** [comment]
Improved Landing As a Guest

It's not true guest access, but does make it so you can trial the app before committing to signing up. Stuff like being able to see rooms, maybe participate in them briefly, and otherwise poke around a bit. Pre-redesign had this in the sense that if you tried to do anything sufficiently complicated the app would say "Hold on! You'll need to register to try that part out" and give you a box to stick a username in. It then created your account for you and warned you that you'll need to set up a password otherwise the account will be lost forever, but didn't require you to set a password.

**Comment by RomeSilvanus** [comment]
Is there any timeline as to when guest access will be available again?

It would be a really useful feature for me.

**Comment by rmoz** [comment]
Maybe strip the option from the settings till ILAG works? It's annoying that users are able to select option that is on available. It took me a fair amount of time before I figured out that I wasn't doing anything wrong.

**Comment by t3chguy** [comment]
> Maybe strip the option from the settings till ILAG works? It's annoying that users are able to select option that is not available. It took me a fair amount of time before I figured out that I wasn't doing anything wrong.

riot is just one Matrix client, other clients can support Guests so if the room moderation flag isn't there then you can't tell if the room is guest-accessible
