### ISSUE TITLE
https://riot.im/desktop.html is not part of the redesigned riot app or the redesigned about.riot.im, and is a big purple dog's breakfast

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8893]
To reproduce this issue:

- Go to https://riot.im/desktop.html
- Experience the vivid purple
- Sob

**Comment by lampholder** [comment]
@dbkr how are these pages actually populated? Can we bump them to about.riot.im proper?

**Comment by turt2live** [comment]
@lampholder they are in the about.riot.im repo - see related issues.

**Comment by turt2live** [comment]
fixed/purged in the rebrand
