### ISSUE TITLE
Issue with npm install

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8902]
User `@lowee:matrix.org` had an issue while executing `npm install` after cloning the Riot web directory.

node: v10.15.1 LTS
OS: Linux

Log: https://gist.github.com/anoadragon453/a73c8282083eff9bcccc2dd8f94782ab

Link: https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1550925692265521lEmGk:matrix.org

**Comment by jryans** [comment]
The logs here don't provide much insight... It seems like it tried to run the `prepublish` script `'npm run clean && npm run build:compile`, but this failed with error code 134 (unclear what that means). I think I will try to interactively debug with them in #riot-dev.

**Comment by turt2live** [comment]
134 is the generic error for "it broke". Usually when there's nothing obvious in the logs it means that the machine ran out of memory - webpack can be quite expensive and use several gb of memory suddenly, leading to things breaking.
