### ISSUE TITLE
Center icons when room list is collapsed

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#8906]
When the left panel is collapsed there is a lot of extra room on the right side. It would be nice to shrink the width of the collapsed left panel and center the room icons.

![screen shot 2019-02-23 at 11 37 47 am](https://user-images.githubusercontent.com/5855073/53289755-c7803600-375f-11e9-950a-d599677b4cfa.png)

**Comment by lampholder** [comment]
I think @nadonomy is currently looking into the ux around this. Those left-aligned icons make me very unhappy :P

**Comment by aaronraimist** [comment]
This got fixed recently
