### ISSUE TITLE
Electron installer uses old logo

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8913]
![image](https://user-images.githubusercontent.com/1190097/53296378-4199d480-37cb-11e9-8e96-80136a8e69c8.png)

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/blob/master/electron_app/build/install-spinner.gif needs redesign

**Comment by nadonomy** [comment]
@turt2live is your screenshot from https://riot.im/desktop.html? Or somewhere else?

**Comment by t3chguy** [comment]
@nadonomy the screenshot is from running the installer, riot.im/desktop.html just happens to be the window he had behind the installer

**Comment by turt2live** [comment]
what @t3chguy said

screenshotting circles is hard :(

**Comment by nadonomy** [comment]
A simple fix for this is in https://github.com/vector-im/riot-web/pull/8984 however I'll leave this issue open and repurpose it to represent making the install spinner look nice and animated.

**Comment by nadonomy** [comment]
Scratch that— closing this for posterity and will make a new issue.
