### ISSUE TITLE
Can't change username?

### ISSUE THREAD

**Issue by markur** [vector-im/riot-web#8927]
### Description

i made a mistake when I signed up. I meant my username to be "markur" and instead it has 2 "r"s. "marrkur" how can I correct that? Can't do it from the front end.

Mark

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:
Safari 11.5.2

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?

Mac OS High Sierra 10.13.6

- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

Mac OS High Sierra 10.13.6
Riot Version 1.0.1

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y 
mark@macwiseguy.com

**Comment by t3chguy** [comment]
Your username is immutable and unique, and how you're referred to by everything in the system, so changing username is fundamentally the same as making a new account, so that is the way to do it

**Comment by markur** [comment]
Can I use the same email I registered with? I don't want to use an alternate address just because of this.

**Comment by markur** [comment]
Looks like I can't use the same email address. So what option do I have? can't somebody on the backend delete that account? I'm sure this will happen again. While not a bug, technically, very inconvenient and I'm likely to use this as I'm trying to use less email addresses than more.

**Comment by lampholder** [comment]
In User Settings (in the top left menu) you can delete your account, or you can disassociate your email address from your wrong-named account and use it for a new account. Either option will allow you to use your email address for a new account.

**Comment by aaronraimist** [comment]
Closing this as the support has been provided.

**Comment by jxu** [comment]
Is there functionality to export and import all data to simulate a username change? #19367

I want to move my identity to a self-hosted matrix server.

**Comment by doshmeister** [comment]
Having a problem with username changing.

Chose the username "jayming" and registered account, but after email confirmation it said username is taken. Since I have used my email to register, i cannot make a new account without using a throw-away email, which I don't want to do.

I'm sure if I could learn how to "unregister" an email or delete an account without being logged in this would be resolved.

**Comment by t3chguy** [comment]
@jxu https://ems.element.io/tools/matrix-migration

**Comment by acerspyro** [comment]
I personally feel like referring to users internally by their usernames is bad practice, a UUID should be used instead.

Usernames should only be used for display and sign on purposes.

Additionally, having fixed usernames could cause some pain to people who changed their name legally and had their old name in their username.
