### ISSUE TITLE
Space missing in the Dutch translation

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#8931]
Charleswas uitgenodigd en is toegetreden, Dirque en één anderewas uitgenodigd.

**Comment by jryans** [comment]
Riot translations are handled through https://translate.riot.im/, so this sounds like it should be submitted there. See https://github.com/vector-im/riot-web/blob/develop/docs/translating.md for a guide.

**Comment by Biep** [comment]
OK, that's too much trouble.
I'll just let it drop.

 ---- On di, 26 feb 2019 17:29:23 +0100 J. Ryan Stinnett <notifications@github.com> wrote ----
