### ISSUE TITLE
Encrypt megolm keys securely in indexeddb

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8938]
Currently we encrypt megolm keys with a hardcoded key of DEFAULT_KEY, as per https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/OlmDevice.js#L77

Instead we should do something like https://crypto.stackexchange.com/a/52488 to generate a secure keypair, and store it in Indexed DB with the .extractable property set to false.

**Comment by bwindels** [comment]
wrt the linked ticket, as the `CryptoKey` would also be stored in the network home directory (within indexeddb), wouldn't that still allow the admin to run Riot off that directory and decrypt the messages?

**Comment by uhoreg** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7271
