### ISSUE TITLE
Cannot find newly created user

### ISSUE THREAD

**Issue by markuskramerIgitt** [vector-im/riot-web#8939]
### Description
Using the webapp, I created  my first two Riot/Matrix users:
- @test20190225a:matrix.org and 
- @test20190225b:matrix.org

I cannot find or write from one to the other.

What do I miss?

### Steps to reproduce
Browse to https://riot.im/app
 
### Version information

Google Chrome is up to date
Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by markuskramerIgitt** [comment]
I do find other usernames starting with test2018, but none starting with test2019

Either the creation of the users partially failed or the lookup partially fails.

**Comment by t3chguy** [comment]
The autocomplete only shows users you share rooms with for privacy reasons. You can send invites to any full MXID, e.g @test......:matrix.org

**Comment by lampholder** [comment]
Also the user directory on matrix.org is currently wedged, so even if you are in public room/share rooms the user search functionality is not going to work for newly created users (this is being addressed).

**Comment by lampholder** [comment]
This is this: https://github.com/matrix-org/synapse/issues/4581

**Comment by markuskramerIgitt** [comment]
Thank you - I can send invite using the full ID @test20190225a:matrix.org
