### ISSUE TITLE
Electron should support pulling custom config.json from preferences if available

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8949]
You can't edit the config.json in-place in Riot on Electron on some platforms (e.g. macOS) as it breaks the package signature.

Instead, we should support looking at ~/.riot/config.json or equivalent to let users override the default config.json (e.g. to provide a custom installation script which grabs Riot and then applies the custom config.json to set up the correct default HS etc).

**Comment by t3chguy** [comment]
Related/would solve https://github.com/vector-im/riot-web/issues/4394#issue-237851822

**Comment by ara4n** [comment]
actually this is p1 to support folks who want custom desktop apps. @t3chguy do you think you'll have a chance to look at it? otherwise we'll put it on the team proj board.

**Comment by t3chguy** [comment]
I will have this in a PR tomorrow

**Comment by ara4n** [comment]
thanks! :)
