### ISSUE TITLE
Ctrl+ - does not work

### ISSUE THREAD

**Issue by mariachr** [vector-im/riot-web#8953]
### Description
Control + - does not work and I have to stick with very big fonts. There is no option to decrease font size either.

### Steps to reproduce
After launching riot, try to zoom out by pressing control + "-"

Nothing happens to text size.

Log: No logs.

### Version information
* **Platform**: desktop

For the desktop app:

* **OS**: Windows 10
* **Version**: 1.0.1

**Comment by lampholder** [comment]
This is (essentially) https://github.com/vector-im/riot-web/issues/3160
