### ISSUE TITLE
Breadcrumbs UI can get into a broken state

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8954]
![image](https://user-images.githubusercontent.com/1342360/53428615-01ad3a00-39e3-11e9-8e95-f7b394c41947.png)

### Description
Breadcrumbs UI can get a bit broken with rooms and the little fade thing getting offset a bit to the left. No reproducibility steps other than have been using Riot all day and it just happened.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: Independent build of riot.im/develop

**Comment by turt2live** [comment]
just to clarify: there was no dragging/resizing of things in the minutes leading up to it breaking?

**Comment by anoadragon453** [comment]
I don't *believe* so, no.
