### ISSUE TITLE
Better accessibility to buttons for rooms/people and associated actions

### ISSUE THREAD

**Issue by ndarilek** [vector-im/riot-web#8955]
### Description

As a screen reader user, the buttons on the main chat screen are a bit confusing and unintuitive:
 * Some buttons seem to expand and collapse the areas of the screen displaying favorites, people, rooms, etc. [aria-expanded](https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions) would help with this.
 * Similarly, there appear to be _+_ buttons that, when clicked, expand to reveal other actions. These at least could benefit from an `aria-label="Actions"` indicator, because as of now they are unlabelled buttons. They may also benefit from `aria-expanded`, and as a bonus, moving keyboard focus to the first relevant focussable element would be useful.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

1. Launch your favorite/least favorite screen reader.
2. Visit https://riot.im/app.
3. Close your eyes and tab through the interface. Try to figure out from just the spoken words what the interface is meant to do, and forget any knowledge you have about how it actually works. :)

### Version information

- **Platform**: web (in-browser) or desktop? Web

For the web app:

- **Browser**: Chrome 72.4
- **OS**: Chrome OS 72.4
- **URL**: riot.im/app

**Comment by lampholder** [comment]
These sound like very easy changes to make, so I'd advocate our just making them?

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/302 for the master a11y bug
