### ISSUE TITLE
Why doesn't 'da<tab>' autocomplete Dave in #riot-dev?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8957]

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/53438519-4b832980-39bd-11e9-9d96-1c462fe0bb6e.png)

I would expect Dave, not this Ben person.

**Comment by lampholder** [comment]
What order is that list in? My list comes out like this (and Dave is at the top):
![image](https://user-images.githubusercontent.com/1922197/53496590-41832880-3a9a-11e9-9caa-8e3cdf3ee637.png)

**Comment by turt2live** [comment]
Left to right, top to bottom. That Ben fellow is the first suggestion.

**Comment by Soundtoxin** [comment]
I think it's going by the handles rather than display names and "das" from "dasistmeinaccount" comes before "dav" in "dave" because s comes before v in the alphabet.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4784 which gives higher scores to displayname results
