### ISSUE TITLE
Sticker packs return 403 when used in Firefox

### ISSUE THREAD

**Issue by ongun-kanat** [vector-im/riot-web#8963]
### Description

When I want to use stickers in Firefox the server the loading symbol turns indefinitely. The developer toolbox shows that the AJAX request to https://scalar.vector.im/api/widgets/assets?widget_type=m.stickerpicker&widget_id=17476f18-c3df-4ccf-b4f5-9995c8932f2a&filter_unpurchased=true has returned 403 forbidden. All of my browsers/riot instances are verified.

### Steps to reproduce

- Login to Riot using Chromium (the first client also where I made my registration)
- Click on the stickers button.
- Stickers show up

- Login to Riot.im https://riot.im/app using Firefox
- Open a chat room
- Try to send a sticker 
- The stickers refuse to load ( Opening the Network tab of developer tool show a HTTP 403 response is returned from the stickers page.)

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox 65
- **OS**: Arch Linux
- **URL**:  riot.im/app

**Comment by lampholder** [comment]
Only P2 since this does not appear to be a common occurence, but obviously is pretty impactful if it does occur.

**Comment by lampholder** [comment]
@ongun-kanat I've just caught up with the scalar team - they've advised that you can probably fix by deleting all cookies with 'scalar' in the name. Give that a shot and let me know how you get on!

**Comment by ongun-kanat** [comment]
@lampholder Did it the JSON returned OK but now the javascript page https://scalar.vector.im/api/widgets/id/17476f18-c3df-4ccf-b4f5-9995c8932f2a/stickers-03386755b8f994101a68.bundle.js returns 403. I tried removing cookies and clearing HTML5 local storage none worked.

**Comment by lampholder** [comment]
Thanks for trying - @jaywink do you have any thoughts?

**Comment by jaywink** [comment]
Hi @ongun-kanat . Sorry for the late response to this. Some fixes were made in Riot 1.0.4 which was released a few days ago, that should ensure a more stable authentication flow with Scalar in the issue that Scalar tokens become invalid.

Could you confirm this issue still exists for you? Thanks.

**Comment by ongun-kanat** [comment]
@jaywink Yeah, it seems to be solved right now. I was on vacation sorry for the late feedback.
