### ISSUE TITLE
inviting a user that's already in the room fails with misleading error message

### ISSUE THREAD

**Issue by dali99** [vector-im/riot-web#8965]
![2019-02-27-012418_489x155_scrot](https://user-images.githubusercontent.com/990767/53456367-75c0ff80-3a2e-11e9-88f8-89ab8d71a357.png)

**Comment by turt2live** [comment]
How was the invite initiated? Via the right side, the button on the right side, through a command, or some other means?

**Comment by dali99** [comment]
This happens when you use /invite, and the big button on the right side.

Don't know how I'd use the right side to invite someone who's already in the room.

**Comment by turt2live** [comment]
There's ways of doing it, but just wanted to make sure the right code path was being used which it indeed is. Fixing the error in the MultiInviter stuff should magically fix this (for whoever happens to be troubleshooting it).

**Comment by turt2live** [comment]
Labels transferred from earlier dup

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2734
