### ISSUE TITLE
allow matrix.to permalinks to be reconfigured in config.json

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8968]
e.g. to allow the KDE riot to permalink straight through to webchat.kde.org if they want.  Alternatively, we could extend .well-known to advertise a default webclient location, which matrix.to could peek to provide route users to a branded riot or whatever as long as they support going to a room by appending the room alias (or id) & event to the URL

**Comment by aaronraimist** [comment]
Related/dup: https://github.com/vector-im/riot-web/issues/8149

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8149 because I think that's the primary concern here.
