### ISSUE TITLE
Replies prepend replied-to message to reply text in timeline

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8969]
![image](https://user-images.githubusercontent.com/274386/53501396-5cf72f00-3aac-11e9-93a1-5270923d17fc.png)

**Comment by bwindels** [comment]
reply was "test" from Amandine, but Hubert's message got prepended to it on the same line.

**Comment by t3chguy** [comment]
Could you show what the event looks like? Is this a sending or rendering issue...?

**Comment by bwindels** [comment]
Looking into it... m.relates_to seems to be missing from the reply, sent with Riot Android...

**Comment by bwindels** [comment]
```
{
  "content": {
    "body": "> <@Amandine:matrix.org> Do we have more updates on the crypto issues or was uhoreg too lost in cross signing yesterday?\n\nI got a bit distracted by cross-signing stuff yesterday, but I'm still working on the crypto issues.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/<redacted room id>/<redacted event id>\">In reply to</a> <a href=\"https://matrix.to/#/@Amandine:matrix.org\">@Amandine:matrix.org</a><br>Do we have more updates on the crypto issues or was <a href=\"https://matrix.to/#/@uhoreg:matrix.org\">uhoreg</a> too lost in cross signing yesterday?</blockquote></mx-reply>I got a bit distracted by cross-signing stuff yesterday, but I'm still working on the crypto issues.",
    "msgtype": "m.text"
  },
  "room_id": "<redacted room id>",
  "type": "m.room.message"
}
```

**Comment by bwindels** [comment]
riot web should probably not include the mx-reply to this, but as m.relates_to should be there normally, demoting this to p2.

**Comment by bwindels** [comment]
fwiw, these changes to `ReplyThread.js` got merged this monday, but don't seem related AFAICT:

https://github.com/matrix-org/matrix-react-sdk/pull/2671/files#diff-b9d18900308f768e1b0937cb16dcdb28L88

**Comment by tuxayo** [comment]
Here is an instance of the issue, if that can help
https://matrix.to/#/!UCnwUWwIKhcpaPTHtR:sw1v.org/$15517103872018981RPVip:matrix.org?via=sw1v.org&via=matrix.org&via=chat.weho.st

riot-web: 1.0.1
Riot android: probably the latest from Play store

**Comment by uhoreg** [comment]
fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5006
