### ISSUE TITLE
Weird messed up timeline when joining a room for the first time

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#897]
I joined the room by clicking on it from the directory. No messages were exchanged before, only statuses. Xena is admin and on Matrix.org. Refreshing fixes it

![image](https://cloud.githubusercontent.com/assets/8582858/12930369/203e3790-cf78-11e5-82c8-a733e122f950.png)

**Comment by AmandineLP** [comment]
it happened again...

![image](https://cloud.githubusercontent.com/assets/8582858/12949562/dc27d03e-d008-11e5-87f1-afc56115ccb8.png)

**Comment by ara4n** [comment]
@erikjohnston this looks worryingly like the HS coughing up ancient events?

**Comment by erikjohnston** [comment]
I think the last one might be a federation thing (where we hadn't gotten the join before), and a different bug from the first.

**Comment by erikjohnston** [comment]
So, I can't see anything obvious that would explain this behaviour server side. I think at this point I kinda need the `/sync` and `/messages` responses, which I appreciate might be hard to get.

Is there any possibility that vector has incorrectly ordered the responses to multiple `/message` requests? Alternatively, synapse will send down those events in the state section?

**Comment by ara4n** [comment]
@dbkr: is there any chance this is related to the multiple concurrent 
/sync bug you hit?

**Comment by richvdh** [comment]
I suspect this is something to do with changes in `history_visibility`; in particular, events that have `shared` history_visibility which become visible when you join. But still, it's hard to see why old events would be stuck at the end of the timeline. It would be very useful to have the `/events` / `/sync` / `/messages` requests from this time.

**Comment by richvdh** [comment]
Amandine saw it again:
https://matrix.org/_matrix/media/v1/download/matrix.org/mKQPzAFjFfMQDOrPiujKfRYU

**Comment by richvdh** [comment]
This bug, in its original guise (messed up timeline on room join), doesn't seem to have been seen for a while. (As opposed to #1456, which is some sort of screwup which happens when synapse decides to backfill an existing room over federation, and is definitely still happening). Is it possible it's gone away?

**Comment by ara4n** [comment]
yeah, unless @AmandineLP has seen it again (given she seems to be the main progenitor), i think this has been fixed somehow somewhere. Perhaps @erikjohnston might even known where.

**Comment by AmandineLP** [comment]
I haven't seen it recently

**Comment by ara4n** [comment]
KILL IT WITH FIRE
