### ISSUE TITLE
[solved] Couldn't start capturing media! Is your microphone set up and does this app have permission?

### ISSUE THREAD

**Issue by DoctorSubtilis** [vector-im/riot-web#8979]
### Description
Riot desktop in Kubuntu cannot do audio or video calls: I get this error message Couldn't start capturing media! Is your microphone set up and does this app have permission?

### Steps to reproduce

- start Riot-web desktop in Kubuntu 18.04
- try to do a audio or video call
- you get that error message

Describe how what happens differs from what you expected.

Log: sent    

### Version information

Riot version  
versione matrix-react-sdk: <local>  
versione riot-web: 1.0.1  
versione olm: 3.0.0  

- **Platform**: desktop

For the desktop app:

- **OS**: Kubuntu
- **Version**: 18.04

**Comment by turt2live** [comment]
@DoctorSubtilis unfortunately I'm not able to reproduce this. Do you have the mute icon next to the URL as shown here?
![image](https://user-images.githubusercontent.com/1190097/53525791-d3d9fb00-3a9f-11e9-8be3-53e56eda280f.png)


Also double check that it isn't blocked when clicking ion the (i) icon:
![image](https://user-images.githubusercontent.com/1190097/53525847-f0763300-3a9f-11e9-873d-3eb0accc0cc4.png)

**Comment by DoctorSubtilis** [comment]
Thank you Travis, but the browser app is working, the problem is **the desktop** one (**Platform**: desktop). In Firefox indeed I don't get any error message.

**Comment by DoctorSubtilis** [comment]
I tried, on the same PC, to use Riot as another user, and it worked there. So I then copied the settings folder of the user where it worked on the home of the one that did not work and so I **solved** it.

**Comment by turt2live** [comment]
Oops, I somehow missed the desktop part of this - sorry. It's good to hear you've solved it, but a bit worrying that this isn't the first time I've seen someone lose media permissions in the desktop app. I've reported https://github.com/vector-im/riot-web/issues/8993 so we can track what's going on there.
