### ISSUE TITLE
Change default branch to develop for Riot Web repos

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8992]
After talking with @lampholder about process on GitHub, we felt it would simplify things if we change the "default branch" on Riot Web repos from master to develop. This should improve several things:

* New contributors will check out repos on the correct branch by default
* Issues should auto-close correctly when merged to develop
* PRs will target the correct branch by default

The master branch still exists for those who want the stable version, but arguably most of those people want a released artifact instead anyway.

(As an aside, Riot iOS and Android teams already have default branch set to develop.) Any opinions on this?

**Comment by turt2live** [comment]
My general thoughts are that it sounds like a good thing to do but we really shouldn't do it quietly.

People have build scripts for Riot and I don't think we should break those intentionally, even if they are custom, non-standard, monstrosities that people put together.

**Comment by jryans** [comment]
> My general thoughts are that it sounds like a good thing to do but we really shouldn't do it quietly.
> 
> People have build scripts for Riot and I don't think we should break those intentionally, even if they are custom, non-standard, monstrosities that people put together.

Right, that's a good point. What's a good way to broadcast the intent to change to such people? Announcing it in #riot-dev?

**Comment by turt2live** [comment]
Yea, probably an at-room notification and general noise for a day or so before doing it.

**Comment by jryans** [comment]
We'll also need to review our build, release, etc. scripts to ensure they all checkout a specific branch instead of relying on the default.

**Comment by uhoreg** [comment]
Back in the days before GitHub, people used to do development on the master branch.  Since git is a development tool, it's always seemed weird to me to have development done on a not-default branch.  I don't know why things changed when GitHub showed up, but +1 to going back to having development on the default branch, like we had in the good old days.

Now get off my lawn!
\</curmudgeon>

**Comment by jryans** [comment]
I reviewed our own build, release, etc. scripts, and we appear to correctly choose a branch explicitly in all of them.

The next step is to communicate our intent to the community.

**Comment by jryans** [comment]
I have posted in #riot-dev:matrix.org with our intent to change.

**Comment by jryans** [comment]
The default branch settings have been changed.
