### ISSUE TITLE
Identify animated GIFs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#90]
Either by a GIF badge, or. (heaven forbid) inline the animated GIF, perhaps having preprocessed it to remove any looping, so that it only plays on load and onclick?

**Comment by dbkr** [comment]
This probably requires something serverside to do properly: either the preprocessing you mention or just detecting and flagging the fact that it's animated. Worth opening a bug upstream?

**Comment by uhoreg** [comment]
Was this referring to an older design?  It looks like it can be closed in favour of #2416

**Comment by ara4n** [comment]
yeah.
