### ISSUE TITLE
Email association image broke again

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9006]
Probably because we changed everything around.

![image](https://user-images.githubusercontent.com/1190097/53612261-de26f280-3b8e-11e9-9adf-d7d018b733e4.png)

References https://riot.im/app/themes/riot/img/logos/riot-logo.svg

This is on https://vector.im/_matrix/identity/api/v1/validate/email/submitToken?...

**Comment by jryans** [comment]
Looks like [this line](https://github.com/matrix-org/sydent/blob/bb0c48468ca879c72929a50be93368ddfd3e933f/res/verify_response_page_template_vector_im#L43) in sydent would need to be updated.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/4779 and/or https://github.com/matrix-org/sydent/pull/120 (+ riot.im changes)
