### ISSUE TITLE
Avatars broken in email notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9009]
![image](https://user-images.githubusercontent.com/1190097/53613498-5db6c080-3b93-11e9-8f8f-cb9b4751e7ba.png)

First one is a default avatar (https://vector.im/beta/img/f4c371.png) when it shouldn't be - the room has an avatar.

The second one should be my avatar, but isn't (instead it's https://vector.im/beta/img/76cfa6.png).

Both cases show that by changing the swatches we also broke the images. 

Related: https://github.com/vector-im/riot-web/issues/9006

**Comment by jryans** [comment]
For this, there seem to be [several templates](https://github.com/matrix-org/synapse/search?q=vector.im%2Fbeta%2Fimg&unscoped_q=vector.im%2Fbeta%2Fimg) in Synapse that would need to be updated.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/4779 and/or https://github.com/matrix-org/sydent/pull/120 (+ riot.im changes)
