### ISSUE TITLE
Breadcrumbs should have right-click menus

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9012]
Would be cool if you could right-click a breadcrumb and get the same context menu (notifications, leave, settings) that you do if you right-click a room in the room list. Sometimes rooms get buried in the list but it's right there in the breadcrumbs.

**Comment by lampholder** [comment]
If right click menus have a future then yes, we should support them here.

Let's have a conversation about whether we're removing them before we add any more, though :P

**Comment by turt2live** [comment]
@lampholder does the right click menu have a future?

**Comment by lampholder** [comment]
I'm going to say: no. Riot Web should not override right click. 

No need to do anything about the room list now particularly; let's just not let it spread. 

Things we might consider (but are certainly not part of the breadcrumbs work):
- having rooms in the room list/breadcrumbs have an href to their room that you can discover through (standard) web right click
- supporting useful context right click consistently throughout the electron build

**Comment by ara4n** [comment]
> I'm going to say: no. Riot Web should not override right click.

+10000

**Comment by turt2live** [comment]
Closing as won't fix then, as there's no work to do here. A seperate issue for fixing room tiles and such sounds like a good thing given the scope.
