### ISSUE TITLE
Improve breadcrumbs

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9015]
Meta issue with links to all the issues so we can move it out of labs:
- https://github.com/vector-im/riot-web/issues/8954
- https://github.com/vector-im/riot-web/issues/8890
- https://github.com/vector-im/riot-web/issues/8797
- https://github.com/vector-im/riot-web/issues/8714
- https://github.com/vector-im/riot-web/issues/8705
- https://github.com/vector-im/riot-web/issues/8685
- https://github.com/vector-im/riot-web/issues/8662
- https://github.com/vector-im/riot-web/issues/8659
- https://github.com/vector-im/riot-web/issues/8606
- https://github.com/vector-im/riot-web/issues/8564
- https://github.com/vector-im/riot-web/issues/8548

**Comment by NotAFile** [comment]
Is making breadcrumbs persist across restarts part of the plan?

**Comment by turt2live** [comment]
yup: it's about 2 levels deep in that list. https://github.com/vector-im/riot-web/issues/8548#issuecomment-465112440

**Comment by turt2live** [comment]
Closing this as the issues are being tracked elsewhere for out of labs requirements.
