### ISSUE TITLE
room doesn't stick to bottom shortly after opening it

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9018]

**Comment by turt2live** [comment]
is this https://github.com/vector-im/riot-web/issues/8792 ?

**Comment by bwindels** [comment]
I suspect it is not, as it only happens when sticking to the bottom, and it has a slight delay when the timeline loads.
Initial investigations seem to point to saveScrollState failing to see we're at the bottom...

**Comment by bwindels** [comment]
ok, this does seems to be the flair coming in in the end. It doesn't just make the timeline grow, but also triggers scroll for some reason (scrollTop differencing by 1px). the scroll event is fired before the resizeobserver, unsticking to the bottom because isAtBottom fails.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2746
