### ISSUE TITLE
blank settings page

### ISSUE THREAD

**Issue by Funkstorm** [vector-im/riot-web#9022]
### Description

The Settings page is blank (white window) on my machine. This affects both, web client and desktop client using Windows.

### Steps to reproduce

Just open the Settings tab.

Describe how what happens differs from what you expected.

Log: not sent (can't access the settings page for sending the log)

![riot](https://user-images.githubusercontent.com/8846375/53677946-5fc66f80-3cb8-11e9-956d-2c86fd3e1f7b.jpg)

![riot web](https://user-images.githubusercontent.com/8846375/53678010-4671f300-3cb9-11e9-98cb-262d2a402e1d.jpg)

### Version information

- **Platform**: web (in-browser) or desktop? web and desktop

For the web app:

- **Browser**: Chrome 72.0.3626.119 64-bit
- **OS**: Windows 10 v1709 build 16299.431
- **URL**: https://riot.im/app/#/home

For the desktop app:

- **OS**: Windows 10 v1709 build 16299.431
- **Version**: 1.0.1

**Comment by rdrr** [comment]
It's the same for me

- OS: Arch Linux v4.20.13.arch1-1
- Version: 1.0.1-1

**Comment by turt2live** [comment]
In the Javascript console (CTRL+SHIFT+I in chrome) please type `mxSendRageshake("https://github.com/vector-im/riot-web/issues/9022")` and press enter. This will send debug logs to us for investigation.

For reference:
> Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users. They do not contain messages.

**Comment by esbendalsgaard** [comment]
It is the same for me on the Windows client 

- OS: Windows10 version 1809

- Version 1.0.1

**Comment by esbendalsgaard** [comment]
It is working now :-)

**Comment by Funkstorm** [comment]
> It is working now :-)

Not for me.

**Comment by Funkstorm** [comment]
Same happens on my Raspberry Pi 3

![image 02-03-2019 1](https://user-images.githubusercontent.com/8846375/53684475-1f91dc00-3d0e-11e9-8346-3d1f3a361377.jpg)

**Comment by esbendalsgaard** [comment]
> It is working now :-)
> 
> Not for me.

Sad to hear. I can confirm that it is working on the desktop app (Windows10) and the webapp (Firefox) for me. To get the desktop client to work, it was not sufficient to close and restart the app, but I had to quit the app so it was not working in the background. After that it worked - maybe a coincidence?
![image](https://user-images.githubusercontent.com/48148278/53687687-e2dada80-3d37-11e9-83a2-46abb204fbcd.png)

**Comment by rdrr** [comment]
So, I created a room and that seems to have fixed it for me.

**Comment by turt2live** [comment]
Creating a room is indeed the workaround, sorry for not posting that earlier.

Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2738
