### ISSUE TITLE
Riot can enter an infinite tight loop if demoting yourself to a custom level

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9039]
![image](https://user-images.githubusercontent.com/1342360/53748320-09feec80-3e9d-11e9-8de0-51b7a3376690.png)

### Description
Trying to set your own power level to `-1` in a room can cause Riot to enter a tight loop and freeze your browser process.

Logs: sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome/Firefox
- **OS**: Debian Linux & MacOS
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Can haz rageshake please?

**Comment by anoadragon453** [comment]
@turt2live sent

**Comment by turt2live** [comment]
hmmm.. your rageshake doesn't have anything of interest in there. Not even a reference to the screenshot.

**Comment by anoadragon453** [comment]
How far back do rageshakes go? Would it not record it? I have to crash the tab to get Riot back, and then did a rageshake afterwards.

**Comment by turt2live** [comment]
It went back 4 sessions in your case, which probably should have caught it. I wouldn't doubt that it being spammed is causing the problem.

I've managed to reproduce it though in an easier environment to debug.

**Comment by anoadragon453** [comment]
Cool, alright.

**Comment by turt2live** [comment]
I demoted this but then it started to bother me that I couldn't fix it, so I fixed it: https://github.com/matrix-org/matrix-react-sdk/pull/2743

The reproduction case was even more limited by requiring the user to use <kbd>Enter</kbd> to submit the value which invoked the infinite loop.

**Comment by anoadragon453** [comment]
Pretty sure I hit tab to get out of the field, but probably has the same effect.
