### ISSUE TITLE
Layout on sending state event in devtools is incorrectly indented

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9044]
![image](https://user-images.githubusercontent.com/1342360/53798507-47608a00-3f30-11e9-8d86-c8957cfd556c.png)

### Steps

- Go to a room
- Type `/devtools` into the message box
- Select `Send Custom Event`
- Click the red `Event` button
- See brokenness

### Description

State key field in /devtools is oddly indented.

Describe how what happens differs from what you expected.

Log: not sent    

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: Independent build of riot.im/develop

**Comment by t3chguy** [comment]
the two fields are actually meant to be on the same line but somehow the width is too great and this happens :'(

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2985
