### ISSUE TITLE
Country selector dropdown needs a redesign touch up

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9048]
![](https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/lvyBBFjjxDcZCxIlIvGplvns?width=800&height=600)

Perhaps we should improve at least:

* Replace green border
* Option font color
* Option font weight

**Comment by turt2live** [comment]
Also getting that fancy joined input on the settings would be awesome. Currently it crudely places them next to each other:
![image](https://user-images.githubusercontent.com/1190097/53825017-8c85bb80-3f32-11e9-8cb5-8ea2a500c097.png)

**Comment by jryans** [comment]
> Also getting that fancy joined input on the settings would be awesome.

Agreed! Filed #9049 for this part.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2765
