### ISSUE TITLE
Changing Link Shortening Service

### ISSUE THREAD

**Issue by martindale** [vector-im/riot-web#9057]
When changing line 21 of `src/matrix-to.js` in `matrix-react-sdk` to a self-hosted instance, pillboxes in Riot break.  This value should be easily configured, perhaps from `config.json`.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/8968

**Comment by t3chguy** [comment]
Even if configurable via config.json it'd still break pills, because the pills are based on your selected matrix-to instance.
