### ISSUE TITLE
Modular link is annoying

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9059]
Ugh. I want to be supportive but sticking the modular link (https://github.com/matrix-org/matrix-react-sdk/pull/2748/) in such a visible spot seems like it is going to annoy more people than it gets to signup. At the very least it should only show up for users on matrix.org or maybe a small list of public home servers (although I totally understand why you wouldn't want to maintain such a list). I really don't want that showing up when I already have my own domain.

![screen shot 2019-03-05 at 8 46 02 pm](https://user-images.githubusercontent.com/5855073/53852484-cfbe4980-3f87-11e9-928c-d6b056bc29e9.png)

Keywords: Upgrade to your own domain

**Comment by jryans** [comment]
Thanks, I think we meant to do this from the start, but that check was forgotten in the first pass. Anyway, it has now been merged in https://github.com/matrix-org/matrix-react-sdk/pull/2754.

Thanks for bringing it up! 😁
