### ISSUE TITLE
Power level background is non-transparent on disable power level fields

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9064]
![image](https://user-images.githubusercontent.com/1342360/53887910-26c12e80-401b-11e9-9825-4d8a36990683.png)

### Description

Background should be transparent, not white.

### Reproductions

- Go to room where you can't change your power level

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by yannicka** [comment]
Is it still relevant? The display seems to have evolved and no longer seems to be a problem:

![image](https://user-images.githubusercontent.com/22885898/82259498-fdf53280-995b-11ea-8d80-440b8352e39a.png)

**Comment by t3chguy** [comment]
indeed, thanks
