### ISSUE TITLE
add to Linux/Debian repository documentation the package requirement: apt-transport-https

### ISSUE THREAD

**Issue by talbym** [vector-im/riot-web#9072]
As the Linux/Debian repository only supports https, following the instructions given [here](https://riot.im/desktop.html) does not work under Debian 9 without first adding to the Debian 9 installation the following package:
apt-transport-https
This package requirement should be added to the documentation on the above mentioned page.

**Comment by uhoreg** [comment]
fixed in the latest instructions.  Thanks for reporting.
