### ISSUE TITLE
Stop shipping Riot Desktop builds for 32-bit Linux

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9074]
We have recently upgraded to Electron 4, which no longer supports 32-bit Linux.

Riot 0.17.9 and later versions are built with Electron 4.x, and when you run them on Ubuntu 16.04 32-bit, it fails:

![](https://matrix.org/_matrix/media/v1/download/matrix.org/REhDKBOxpHEyjjoPBoKdGeSE)

A similar error is described in https://github.com/electron/electron/issues/16407. Since Electron is no longer supporting this platform and these builds already don't work, we should stop shipping them going forward.

**Comment by lampholder** [comment]
What else needs doing for this?

**Comment by jryans** [comment]
I think that might be it...? https://riot.im/desktop.html doesn't mention architecture specifically. It would be nice if we had some way to alert any 32-bit users that they won't receive updates any more, but I don't think we have such a thing.

**Comment by artenax** [comment]
Electron unofficially supported Linux 32 bit until version 18.3.15 (Chromium 100.0.4896.160 March 29, 2022). The latest element-desktop build 1.10.15 of June 14, 2022 for Linux 32 bit can be downloaded here https://github.com/artenax/element-desktop/releases

**Comment by t3chguy** [comment]
@artenax that version has multiple published security vulnerabilities, it is not suggested for use
