### ISSUE TITLE
m.emote messages shouldn't have large emoji

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9079]
![image](https://user-images.githubusercontent.com/1342360/53955086-ef608980-40cf-11e9-9338-367af1f9485c.png)

### Description

Empty m.emote messages shouldn't have large emoji, as it looks weird with the small text.

Log: not sent

**Comment by lampholder** [comment]
Yeah, probably. I think emotes + emoji is a bit of a weird combo generally, but big emoji here does look strange.
