### ISSUE TITLE
Default field values in RegistrationForm seem suspicious

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9083]
`RegistrationForm` has various `default*` props for each field, which are passed via a `defaultValue` prop on each field.

Auth form validation forces `Field` to become a controlled React component, so it's unclear whether `defaultValue` actually does anything after that change.

**Comment by t3chguy** [comment]
YUP, this causes the registration form to be emptied on an error:

![image](https://user-images.githubusercontent.com/2403652/62796061-19c7d000-bad0-11e9-90b1-4d282bb5e9bd.png)

I'm surprised there is no specific error about the above, its SUPER ANNOYING
