### ISSUE TITLE
Replies don't show that the original message was redacted

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9085]

**Comment by lampholder** [comment]
If you refresh/navigate away from the room and return the reply looks good:
![image](https://user-images.githubusercontent.com/1922197/54429830-830e0780-4719-11e9-968c-85cc7138dfa7.png)

**Comment by turt2live** [comment]
Sorry, this is definitely a case of me being bad and not screenshotting. The bug is in your screenshot: the reply is empty with no indication of redaction.
