### ISSUE TITLE
The text selection is broken when there's a pill

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#9087]
### Description

When there's a pill in the message you're writing (and only when there's a pill), there is a bug when selecting the text and using the left arrow: the selection shifts.

Here's a gif explaining the problem (because apparently github doesn't accept videos):
![simplescreenrecorder-2019-03-08_08 19 35](https://user-images.githubusercontent.com/6382548/54031220-212f2a00-417c-11e9-8e20-380885f8e478.gif)

### Steps to reproduce

- Mention someone and write more text
- Select a word
- Use the left arrow

The whole selection shifts, I would expect the selection to disappear and the caret to move one character to the left of where it is.

Log: not sent    

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Firefox 65.0.1
- **OS**: Fedora 29
- **URL**: riot.im/app

For the desktop app:

- **OS**: Fedora 29
- **Version**: 1.0.1

**Comment by lampholder** [comment]
Fantastic - I've seen this reported before but never with good repro steps. Thanks :)

**Comment by aaronraimist** [comment]
@MightyCreak does this still happen for you in the current version of Riot (1.5.12)?

**Comment by MightyCreak** [comment]
Seems fixed! I can't reproduce it.

**Comment by aaronraimist** [comment]
Great!
