### ISSUE TITLE
Green outline around Disinvite button

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9096]
![image](https://user-images.githubusercontent.com/1342360/54075992-d9082880-429d-11e9-8c52-9353f3e39707.png)

### Description

The disinvite button (when you're removing the invite of a user to a room) the "disinvite" button has a green outline around it even though it's a red/danger button.

### Steps to reproduce

- Invite a user to a room
- Remove their invite
- See the red Disinvite button has a green outline

Describe how what happens differs from what you expected.

Log: not sent    

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: private riot.im/develop

**Comment by t3chguy** [comment]
Cannot reproduce:
![image](https://user-images.githubusercontent.com/2403652/64688140-a4ab3a00-d483-11e9-9f31-eff9cd2ae772.png)

**Comment by t3chguy** [comment]
Closing presumably fixed incidentally

**Comment by anoadragon453** [comment]
Yes :slightly_smiling_face: Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3269
