### ISSUE TITLE
Scalar: Etherpad widget broken on all platforms "Sorry, this content is not embeddable in Matrix"

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9098]
Starting in the last day or two I've seen people report that the Etherpad widget is broken on Android and iOS and I can reproduce on web.

![Screen Shot 2019-03-10 at 8 22 32 AM](https://user-images.githubusercontent.com/5855073/54085687-a0ecfe00-430e-11e9-9fca-115438e42c99.png)

```
[Error] Failed to load resource: the server responded with a status of 502 () (embeddable, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (etherpad-03386755b8f994101a68.bundle.js.map, line 0)
[Error] Content is not embeddable – "The string did not match the expected pattern."
	(anonymous function) (etherpad-03386755b8f994101a68.bundle.js:69:8649)
	i (etherpad-03386755b8f994101a68.bundle.js:67:72784)
	_settlePromiseFromHandler (etherpad-03386755b8f994101a68.bundle.js:67:46189)
	_settlePromise (etherpad-03386755b8f994101a68.bundle.js:67:47010)
	_settlePromise0 (etherpad-03386755b8f994101a68.bundle.js:67:47698)
	_settlePromises (etherpad-03386755b8f994101a68.bundle.js:67:48915)
	_drainQueue (etherpad-03386755b8f994101a68.bundle.js:67:2806)
	_drainQueues (etherpad-03386755b8f994101a68.bundle.js:67:2863)
	drainQueues (etherpad-03386755b8f994101a68.bundle.js:67:997)
	promiseReactionJob
```

**Comment by lampholder** [comment]
@jaywink this still works for me - any ideas?

**Comment by jaywink** [comment]
It looks tbh either a temporary problem with Scalar or Etherpad itself. I can't really tell where the 502 is from in the stack. Could dig deeper but first would like to ask @aaronraimist can you still get a failure? If so, can you let me know the timestamp when you re-tried and I will take a new look at logs?

For me tried web, desktop and mobile, not live and develop, and things seem to work fine atm.

**Comment by aaronraimist** [comment]
Hmm. No I cannot reproduce it today. I'll reopen if I get it again or hear any more reports. It seems like it was broken for about a 24 hour period before I opened this issue though so it may be worth looking in to those logs.

**Comment by florianjacob** [comment]
I have this exact & reproducable behaviour when I use etherpad names that are too long: `ABCDEFGHIJKLMNOPQRS` as pad name, i.e. 20 chars long works just fine, but `ABCDEFGHIJKLMNOPQRST`, i.e. 21 chars long, results in a 502 bad gateway and the not embeddable banana. Could that be what was actually causing this? Related: https://github.com/vector-im/riot-web/issues/6039

**Comment by Biep** [comment]
A friend of mine has a slightly different issue:
She has an issue with Etherpad - only on the Mac. Elsewhere (tablet, iPhone) she can open the integration just fine, but on the Mac she gets `this content is not embeddable in Matrix.` both in Safari and in the installed Element Desktop.

**Comment by k0gen** [comment]
> A friend of mine has a slightly different issue:
> She has an issue with Etherpad - only on the Mac. Elsewhere (iPad, iPhone) she can open the integration just fine, but on the Mac she gets `this content is not embeddable in Matrix.` both in Safari and in the installed Element Desktop.
> On the iPad it crashes sometimes, but otherwise works well.

Yes I can confirm that this is still the problem on Safari or Brave and in latest (1.7.16) Element.app on macOS Big Sur 11.1
Element.app:
<img width="359" alt="Element-app 2021-01-4 o 22 22 38" src="https://user-images.githubusercontent.com/3606313/103581541-82d99000-4edc-11eb-9623-953c6ef2d5c6.png">
Safari.app:
<img width="361" alt="Safari-2021-01-4 o 22 15 13" src="https://user-images.githubusercontent.com/3606313/103581553-89680780-4edc-11eb-8bb5-4cea5c8226f6.png">
Brave.app:
<img width="370" alt="Brave-2021-01-4 o 22 39 17" src="https://user-images.githubusercontent.com/3606313/103582390-0942a180-4ede-11eb-90dd-310defc0c0a4.png">

As much as I don't trust Google Chrome.app for my daily browsing I decided to do a last test and turns out it is the only one that works:
<img width="356" alt="chrome-2021-01-4 o 22 44 44" src="https://user-images.githubusercontent.com/3606313/103582695-aa315c80-4ede-11eb-82e7-81b9b0ff77b6.png">

**Comment by jaywink** [comment]
The issue with Safari is tracked in https://github.com/vector-im/element-web/issues/15405

**Comment by k0gen** [comment]
> The issue with Safari is tracked in #15405

Yes, thank you for the information. I have decided to write a comment in this issue because it felt more general. Should I open a new issue separately for Element Desktop app (macOS) and Brave Browser?

**Comment by jryans** [comment]
Please default to opening new issues, and we can de-duplicate as needed. Generally speaking, closed issue are not watched for new comments and complicate tracking.
