### ISSUE TITLE
E2E: SAS Verification - Can't dismiss incoming verification request

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9103]
![image](https://user-images.githubusercontent.com/1922197/54114426-b3d50080-43ea-11e9-9622-57b70ae15a92.png)

This request might have been kicking around on my machine for a while before I noticed.

**Comment by ara4n** [comment]
it's not just that you can't dismiss it, but if the originator has got bored and gone away by now we shouldn't be showing it at all as it is entirely useless...
