### ISSUE TITLE
Share Message in right-click message gives broken link

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9110]
Right-click on a message and (don't click, but) right-click "Share Message" and copy. You'll get a link that looks like:

https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/!QtykxKocfZaZOUrTwp:matrix.org

The format of the link should be `https://matrix.to/#/<room ID>/<event ID>` but it is instead `https://matrix.to/#/<room ID>/<room ID>`.

Seems like a fairly high priority bug.

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: independent build of riot.im/develop

**Comment by jryans** [comment]
https://riot.im/develop appears to produce the correct URL with room and event as expected. Are there any other steps? What do you see if you try https://riot.im/develop?

**Comment by anoadragon453** [comment]
Yep, same bug in riot.im/develop

**Comment by jryans** [comment]
Perhaps the particular message you are trying to share is relevant? Could you describe a room and message I can find through other means that exhibits this issue?

**Comment by anoadragon453** [comment]
Any message is Matrix HQ is doing it for me.

**Comment by anoadragon453** [comment]
Ah I think I see the issue. I'm not clicking `Share Message`, I'm right-clicking it in the menu and copying it. It's fine in the actual modal view that pops up but not in the message right-click menu.

**Comment by jryans** [comment]
Aha, yes, I agree, the link on the "Share Message" item itself is broken.
