### ISSUE TITLE
Option to autojoin upgraded rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9113]
I'm already tired of clicking the join button

**Comment by lampholder** [comment]
We avoided this at the time for fear of abuse. IIUC anyone who can write a tombstone event could cause  you to join a new room of their own design - is that right?

**Comment by turt2live** [comment]
Yea, that's also a good point. Not anyone can, but a malicious room admin could decide to upgrade their room forever.

Maybe some sort of cooldown / rate limit on the autojoins? Possibly only autojoining rooms in my recents list?

**Comment by turt2live** [comment]
I think my concerns are largely handled by https://github.com/vector-im/riot-web/issues/8447 and not the solution described here.
