### ISSUE TITLE
Third party invites not transferred on upgrade

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9115]
It's extremely questionable how this is handled - should a new invite be issued? Is the IS involved? Do we need to spec it?

**Comment by turt2live** [comment]
@lampholder do you have thoughts on this one? I'm not entirely sure if we should bother transferring these invites given we don't transfer other invites/membership. Does it seem unreasonable to expect someone to re-send an invite post-upgrade?

**Comment by lampholder** [comment]
IIUC we don't transfer membership, and we don't transfer regular invites, so I think it would be very confusing and inconsistent (not to mention complicated) if we _did_ transfer 3pid invites.

The UX shouldn't even be too bad for users who eventually do claim their outstanding 3pid invites. Tombtone events are state events, so if:
1. you're invited to a room
1. that room is upgraded
1. you accept your invite

You should still see that tombstone event and be able to follow the trail to where you want to be.

**Comment by turt2live** [comment]
I'm going to close this as wontfix then, leaving one of the other issues for tracking invites to sort the general problem out.

**Comment by lampholder** [comment]
For clarity - @turt2live I'm of a mind to close this - what do you think?
