### ISSUE TITLE
Messages "sticking" to the bottom of IRC chat

### ISSUE THREAD

**Issue by n-o-o-b** [vector-im/riot-web#9118]
### Description

I have this really weird bug where a couple of messages I've sent stay at the bottom of the chat and always drop below the latest message, even though they're not the latest sent. It happens in PM and chatrooms.

### Steps to reproduce

- have a matrix.org account
- start chatting over the irc bridge
- wait for some of your messages to experience 2x gravitational pull and drop to the bottom all the time and really annoy you

![InkedInkedircbug1_LI](https://user-images.githubusercontent.com/19697175/54137441-92d5d500-4415-11e9-8b20-5f34ecf95b7b.jpg)
![Inkedircbug2_LI](https://user-images.githubusercontent.com/19697175/54137444-94070200-4415-11e9-86ee-3a21e4a2349f.jpg)

### Version information

- **Platform**: Windows 10 desktop (web is not loading for me on windows)
- **OS**: Windows, Win10 64-bit
- **Version**: 1.0.3

**Comment by lampholder** [comment]
Very odd - would you be happy to submit logs? (user settings -> help and about -> submit debug logs)

**Comment by Half-Shot** [comment]
This looks like https://github.com/vector-im/riot-web/issues/10032, closing this to track over there.
