### ISSUE TITLE
Can't join room ids from the room directory anymore

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9120]
I used to be able to type room ids into the search bar and hit enter, but that seems to no longer be the case.

**Comment by lampholder** [comment]
Does't work on my old version of Riot Web:
![image](https://user-images.githubusercontent.com/1922197/54439474-c32cb480-4730-11e9-8dbc-7bcd4e63f262.png)
(valid local roomid, pressing enter does nothing)

Any idea when this last did work?

**Comment by turt2live** [comment]
Fwiw the /join command was updated for power users to be able to do this.

**Comment by Half-Shot** [comment]
Ah okay.

**Comment by vmario89** [comment]
additionally i have the problem that i cannot see the room directory from entry view perspective:
![grafik](https://user-images.githubusercontent.com/5631071/54467902-74126e00-4788-11e9-86ea-b8143d267d54.png)

![grafik](https://user-images.githubusercontent.com/5631071/54467895-6a890600-4788-11e9-962e-d39774801796.png)

**Comment by Half-Shot** [comment]
@vmario89 This probably needs it's own issue :)

**Comment by vmario89** [comment]
yes i answered first, then i recognized closed state. i already did. thanks for reply :-)
