### ISSUE TITLE
Open source Riot bot

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9122]
Where is the code for the Riot Bot? @killua-eu would like to be able to self host/customize welcomeUserId
https://github.com/vector-im/riot-web/issues/7764#issuecomment-471636890

**Comment by turt2live** [comment]
@rxl881 not sure what the plans are for this, so when you get a moment please leave a comment :)

**Comment by lampholder** [comment]
Just in case it's not obvious - you can point welcomeUserId at _any_ bot, not just Riot bot.

**Comment by killua-eu** [comment]
@lampholder , quite right, but all of the other bots are useless as welcome bots helping new users find their way around. Unless you modify the welcome page itself (something most people won't want to do), you will always get the chat with the matrix-bot button (see #9263) and confuse users.

**Comment by lampholder** [comment]
The welcome page link shouldn't be hardcoded to Riot Bot (though the intention behind the welcome page and the home page is that they be trivial for people running their own riot instances to replace) - I've made an issue for that https://github.com/vector-im/riot-web/issues/9379
