### ISSUE TITLE
Windows 10 - Start automatically after login, keeps getting unset

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#9123]
Just installed Riot desktop on my Windows 10 1809 system. When I try to set it to start after login (via the in-app preference setting), I switch to another setting area, then back to preferences, and it goes back to "unset", as in, not set to start after login.

Relaunching the app, and trying to set it, does not fix it.

matrix-react-sdk version: <local>
riot-web version: 1.0.3
olm version: 3.0.0

**Comment by BloodyIron** [comment]
Just submitted logs to this issue.

**Comment by t3chguy** [comment]
Any chance you could run the app in a command line and try again to see the logs there, they won't be included in the rageshake submitted logs

**Comment by BloodyIron** [comment]
Starting it in a command prompt did not change any behaviour, and nothing was outputted to the command prompt. I don't think I've ever seen a Windows app output errors to the command prompt when the program was ran that way.

So, issue still persists.

**Comment by BloodyIron** [comment]
Okay this is now happening on my Ubuntu Linux desktop too, where the setting goes unset.

I think this is a bug from a recent update, a regression, because my Ubuntu Linux version of Riot was perfectly reliable for this facet!

**Comment by BloodyIron** [comment]
Running the program at the CLI, and trying to set the "Start automatically after system login" setting, does not echo anything to the console. (Ubuntu Linux)

**Comment by BloodyIron** [comment]
Woot!
