### ISSUE TITLE
Redesign for long topics

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9125]
Should be able to expand the topic or something to get at links which are hidden at the end

**Comment by turt2live** [comment]
https://app.zeplin.io/project/5b6798f88c7cda5122505339/screen/5b67a925c314c57502a72bc4 references the the long topic, but I can't find a design which fixes the problem.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/1836
