### ISSUE TITLE
the historical section has gone missing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9129]
it's deliberate to not show it by default in the LeftPanel, and only show it if toggled in TopLeftMenu, but this hasn't been implemented so it appears to be gone and gone forever

**Comment by turt2live** [comment]
nb it does show up if you leave a room in your current session, but promptly flies away when you refresh.

**Comment by lampholder** [comment]
Related https://github.com/vector-im/riot-web/issues/7850

**Comment by ara4n** [comment]
i saw another person report that it's appearing and disappearing erratically, which is pretty unpleasant.

**Comment by benqrn** [comment]
The historical section in riot-web seems permanently gone for me (does not randomly appear/disappear).

**Comment by dawidpotocki** [comment]
That's amazing, it's finally gone. There is no need to fix it my friends. Would love too see more ~~bugs~~ features like this.

**Comment by benqrn** [comment]
It shows in riot-web again but only displays recent rooms.

Is the long term goal for historical rooms to properly allow viewing/searching/rejoining them, or disable access to them entirely?

It was nice to be able to reference rooms I've left (similar to 'archiving' a conversation in Google Hangouts), they perhaps were made for a single purpose and would never receive further updates, so I could leave them to organize my room list better, but still view the content later.

**Comment by t3chguy** [comment]
> it's deliberate to not show it by default in the LeftPanel, and only show it if toggled in TopLeftMenu

**Comment by benqrn** [comment]
> > it's deliberate to not show it by default in the LeftPanel, and only show it if toggled in TopLeftMenu

I do not see the option in TopLeftMenu, one my my riot-web clients does not show the historical section.

The other issue I was pointing out above was that only recent rooms are displayed in the historical section, instead of all of them.

**Comment by turt2live** [comment]
The historical section is now intentionally missing.
