### ISSUE TITLE
Visual highlight for autocomplete missing

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9134]
There is a pretty important bug in the latest 1.0.x releases: we don't see which smiley is currently selected any more. So we just need to hit tab until we get the right one.

_Originally posted by @MightyCreak in https://github.com/vector-im/riot-web/issues/1107#issuecomment-471983297_

**Comment by MightyCreak** [comment]
Wow, that was fast! Thank you! :heart_eyes:

**Comment by jryans** [comment]
Thanks for bringing it to our attention. 😁
