### ISSUE TITLE
Feature request: Channel Groups/Categories

### ISSUE THREAD

**Issue by MrFunken** [vector-im/riot-web#9135]
### Description

Feature request: Allow the client to group different channels together.
Basically, like the favorite function, but with the possibility to create multiple of them and name them however you want.

### Reason

I'm active in multiple organizations/projects. Sometimes it happens that they have similar channel names. That makes it sometimes really confusing to find the right channel.

### Version information
- **Platform**:

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.0.1

**Comment by t3chguy** [comment]
Riot already supports custom tags like Favourites just has no UI to create them. https://github.com/vector-im/riot-web/issues/1373#issuecomment-469608956
