### ISSUE TITLE
Invite emails claim we support Safari

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9138]
To ship 1.0, we shelved efforts to continue to officially support Safari. Until that changes, we should adjust the copy in the email to not advertise Safari support.

**Comment by aaronraimist** [comment]
If true then https://github.com/matrix-org/matrix-react-sdk#developer-guide also needs to be updated and lots of issues can be closed.

#124 #2762 #1024 #1671 #3112 #7421 #6388 #7420 #7146 to name a few

I would strongly urge you to not drop Safari support though. I've been using Safari for several months and only a small percentage of things are broken, for the most part it works.

**Comment by nadonomy** [comment]
If I could add more than one thumbs up to your comment I would. 😃

Not fixing Safari specific bugs was something we optimised to get 1.0 over the finish line, out of pragmatism. From dogfooding, I also agree there's only a small number of issues that would need to be fixed for us to confidently advertise support for Safari.

@lampholder or @ara4n might be able to speak to a more official stance moving forward.

**Comment by lampholder** [comment]
AFAIK we're not planning to remove Safari from our committed platforms.

Right now our supported browsers list looks like: latest Chrome, Firefox and Safari + we'll try and fix bugs on Edge (but we don't actively test it).

I don't think we need to Safari from the email though - having some outstanding bugs != unsupported. It seems to work generally fairly well in Safari - @nadonomy are there specific issues you think are problematic enough for us to say Safari is not supported until they're addressed?

**Comment by lampholder** [comment]
Agreed with @nadonomy to close this - we still support Safari, and any showstopper bugs anyone's encountering there should be addressed and resolved :)
