### ISSUE TITLE
Support HEIC images

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#9143]
Currently, HEIC images show as download links only.  As HEIC is a replacement of JPEG, they should be shown the same way

**Comment by aaronraimist** [comment]
Looks like no browser support this right now :(

https://caniuse.com/#feat=heif

**Comment by turt2live** [comment]
Realistically we can't support this specifically anyways - it's a browser feature that would need to be supported.

**Comment by ajkessel** [comment]
Just found this [workaround](https://github.com/ser/maubot-hateheif/), maybe useful to people watching this issue.
