### ISSUE TITLE
Reset room name

### ISSUE THREAD

**Issue by kiliankoe** [vector-im/riot-web#9147]
If a third account is added to a direct chat, the room logically changes its name to reflect that and lists the other two participants. If one of these is removed however, the room name cannot be changed back to only the other participant's name. And since #3130 isn't a thing, I can't overwrite the room name with the other participant's name either, as that wouldn't make sense for them.

Ideally I would expect the room name to automatically change its default back to the single other participant on the second member change.

**Comment by lampholder** [comment]
Have you tried deleting the name entirely? I think that does the Right Thing in Riot web (though the rooms become named 'unnamed room' on Riot Android at least I think)

**Comment by kiliankoe** [comment]
Yes, I've tried that. I definitely should've added that to the above description. Unfortunately this leaves the room name set with both other participants (one no longer being in the room). I've only tried Riot Web for this so far.

**Comment by lampholder** [comment]
Hey - I just tried to reproduce this by:
1. inviting a user to a dm (so we're both admins in the room) (room name == just the other participant's name)
1. inviting a third user to the dm (this user was not an admin) (room name == the name of both of the other two participants)
1. kicking that third user (room name returns to just the name of the original other participant)

In other words, I couldn't reproduce this problem. Would you be able to provide precise repro steps to help us track this down? Thanks!

**Comment by kiliankoe** [comment]
Interesting, I was sure of this being the case when I opened the issue, but I can't reproduce this either anymore. Sorry for wasting your time!
