### ISSUE TITLE
clicking search result doesn't do anything if already on a link with event id

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9153]
go to https://riot.im/develop/#/room/#riot-web-internal:matrix.org/$1551981818124915QJxVu:matrix.org search for something and click a result. It doesn't go back to the timeline

**Comment by bwindels** [comment]
this seems to be a problem in general with not going to and event link if already on one. might be a dupe.

**Comment by ara4n** [comment]
this is https://github.com/vector-im/riot-web/issues/2903
