### ISSUE TITLE
Email invites are awkward

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9158]
1. User receives email invite
2. User clicks link, sees "Guest" in the top left and an accept button with a warning about how the email isn't associated with their account.
3. User clicks "Accept" and receives a dialog saying they need to register
4. User goes to registration form and fills in their information
5. After submitting it, they have to confirm their email
6. They click the link in their email, and see "User ID already taken"
7. They return to the other Riot tab and see that they are staring at the invite from the original user
8. They click accept and actually talk to the other party

Step 5 seems unnecessary as it causes the user to be confused in step 6. Not to mention the user ends up with 3 or 4 tabs just to register for an account with Riot :(

Ideally, Step 7 would also be magically automated. Step 2 is also not great UX.

**Comment by 1xPdd** [comment]
I also found this quite confusing. 2, 3 + 4 could be combined/streamlined. 2 + 5 seem contradictory; I previously signed up on matrix.org w/ no email--and have done the same on my home instance. Is email confirmation as part of registration even necessary?

**Comment by turt2live** [comment]
I'm upgrading this to https://github.com/vector-im/riot-web/issues/9816 because the other half is fixed by https://github.com/vector-im/riot-web/issues/9586
