### ISSUE TITLE
Riot bot needs updating for the new design, including logos

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9162]
*Author's note: I swear we had an issue for this, but it is eluding me*

**Comment by aaronraimist** [comment]
This is very confusing to people since it shows them buttons that don't exist or are in different places

**Comment by jryans** [comment]
We've decided to disable Riot bot, at least for now.

**Comment by jryans** [comment]
Tracking disable work in https://github.com/vector-im/riot-web/issues/12893
