### ISSUE TITLE
CI build doesn't work / Switch to BuildKite now

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9164]
Seems to only apply to the riot-web repo for some reason. Random unit tests often fail for no obvious reason, and sometimes the build crashes entirely at `yarn install`.

https://travis-ci.org/vector-im/riot-web/jobs/505974036 is an example of this.

**Comment by turt2live** [comment]
Upgrading this to "the CI is literally useless" now that react-sdk builds are failing:

> An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.2.tgz: Request failed \"502 Bad Gateway\"".

**Comment by turt2live** [comment]
Annoyingly I can't reproduce this locally, so it might be a Travis CI + yarn/npm issue and not our fault. Getting 503 errors in CI logs now.

**Comment by turt2live** [comment]
Travis CI is failing us, so we're jumping to BuildKite by just migrating what we have. https://github.com/vector-im/riot-web/issues/9019 will later make the pipelines better.

**Comment by turt2live** [comment]
Somewhere between me opening this issue and now, NPM realized that their stuff is broken: https://status.npmjs.org/incidents/3p30y0pkblsp

This causes BuildKite builds to also fail for the same reasons as Travis CI, however I also think that switching to BuildKite now is a good plan all around. Going to move ahead on BuildKite and hope npm fixes their stuff before UK morning so the PRs can safely go up for review with green checkmarks.

**Comment by turt2live** [comment]
npm has fixed the issue, now there's just a couple things to fix:

* Status checks aren't landing on riot-web due to lack of permissions
* The builds are a bit massive and are blowing out the resource limit on the workers

**Comment by jryans** [comment]
> An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.2.tgz: Request failed "502 Bad Gateway"".

For future reference, I believe the "Yarn registry" is just a CNAME to npm's registry, so if we see errors with `registry.yarnpkg.com`, we should something similar when using npm as well.

**Comment by turt2live** [comment]
I've fixed vector-im not allowing BuildKite to manipulate status checks, so riot-web should now receive them.

I've also tested the build a couple times today to see if I could reproduce the "running out of memory" problem - it appears as though the problem has gone away, however I'm still going to recommend we get larger instances sooner rather than later.

**Comment by turt2live** [comment]
Landed 🎉 

Future work to be dealt with in https://github.com/vector-im/riot-web/issues/9019
