### ISSUE TITLE
Dropdown menu for room list inoperable.

### ISSUE THREAD

**Issue by golanv** [vector-im/riot-web#9166]
### Description

When attempting to join a new room, only rooms on Matrix are displayed.  The drop down menu to select rooms from other servers/bridges does not work in this version of Riot.  When clicking the drop down menu, the menu fails to respond (almost like the real menu was replaced with a picture of the drop down menu).

### Steps to reproduce

- Click the "+" to join a new room.
- Click the drop down menu on the Room Directory window.
- Watch the drop down menu fail to do anything.

The click event displays the following in the browser console:

> Uncaught TypeError: Cannot read property 'servers' of undefined
    at t.value (bundle.js:113)
    at t.value (bundle.js:113)
    at l._renderValidatedComponentWithoutOwnerOrContext (bundle.js:63)
    at l._renderValidatedComponent (bundle.js:63)
    at l._updateRenderedComponent (bundle.js:63)
    at l._performComponentUpdate (bundle.js:63)
    at l.updateComponent (bundle.js:63)
    at l.performUpdateIfNecessary (bundle.js:63)
    at Object.performUpdateIfNecessary (bundle.js:23)
    at b (bundle.js:23)
    at f.perform (bundle.js:30)
    at v.perform (bundle.js:30)
    at v.perform (bundle.js:23)
    at Object.E [as flushBatchedUpdates] (bundle.js:23)
    at u.closeAll (bundle.js:30)
    at u.perform (bundle.js:30)

Log: not sent 

### Version information

- **Platform**: Desktop 1.0.3

For the desktop app:

- **OS**: Fedora Linux 29 64-bit
- **Version**: KDE Plasma version 5.14.4, KDE Frameworks version 5.55.0, QT Version 5.11.3

**Comment by jryans** [comment]
Hmm, are you able to check the same steps on https://riot.im/develop? For me, the issue doesn't seem to occur there, but I'd like you to try to verify (in case I misunderstood the steps).

**Comment by golanv** [comment]
> Hmm, are you able to check the same steps on https://riot.im/develop? For me, the issue doesn't seem to occur there, but I'd like you to try to verify (in case I misunderstood the steps).

I can't seem to replicate the behavior on https://riot.im/develop.  However, I also can't replicate the behavior on https://riot.im/app.  It only seems to be a problem on my desktops.  Additionally, I am getting the package builds from this Copr repo: https://copr.fedorainfracloud.org/coprs/taw/Riot.  I'm not sure if that is relevant or not however.

**Comment by lampholder** [comment]
There's a section in `config.json`:
```
    "roomDirectory": {
        "servers": [
            "matrix.org"
        ]
    },
```
This dictates which homeservers appear in the dropdown in the room directory. My guess is the Copr repo builds are building with a slightly mangled config.json which isn't including any homeservers in that list.

So there are two things here:
- maybe they should fix their build
- we should probably default to searching the user's own homeserver if nothing is provided in that section of the config

**Comment by golanv** [comment]
You are correct.  It seems the config.json is missing from the desktop package.

**Comment by taw00** [comment]
In process of fixing this.
Hmm. I wonder if I need to mark this as a config file for the RPM... cuz... for every update, it will replace it. It really should exist... in `/etc/riot/` or some such. Or in `~/.config/Riot/`

**Comment by jryans** [comment]
> In process of fixing this.
> Hmm. I wonder if I need to mark this as a config file for the RPM... cuz... for every update, it will replace it. It really should exist... in `/etc/riot/` or some such. Or in `~/.config/Riot/`

The config file built with Riot is meant to serve as the default values, so it's meant to be replaced on update in case those defaults change.

Recent versions actually do now support a [local user config override](https://github.com/vector-im/riot-web/pull/8983) as well. (I thought this had documentation as well, but I can't seem to find it now...)

**Comment by jryans** [comment]
> Recent versions actually do now support a [local user config override](https://github.com/vector-im/riot-web/pull/8983) as well. (I thought this had documentation as well, but I can't seem to find it now...)

Okay, documentation is [now merged](https://github.com/vector-im/riot-web#desktop-app-configuration).

**Comment by taw00** [comment]
RPM builds should be fixed in T-minus 15 minutes or so. Already pushed and tested in the test repo. So... Go eat a sandwich, then come back and `sudo dnf ugprade -y riot`

Have a lovely weekend.

**Comment by jryans** [comment]
It sounds Copr have fixed their build to include the config file.

I have spun out the second part about Riot improving behaviour when unconfigured to https://github.com/vector-im/riot-web/issues/9208, so I think we can close this.
