### ISSUE TITLE
Failed to add the following rooms to community

### ISSUE THREAD

**Issue by vranki** [vector-im/riot-web#9174]
### Description

Trying to add a room to community fails.

### Steps to reproduce

- Go to community you're admin of
- Add a room (in this case it's a ircnet channel)

"Failed to add the following rooms to +community:hacklab.fi:

!NfdeQaiYpiHwPfWihI:irc.snt.utwente.nl"

I did this before, triggering #8395 but looks like it's fixed.
Possibly related to #5866

The room in question has also alias on matrix.org, and I'm on the room from matrix.org homeserver.

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**:Firefox
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This could be tricky to diagnose from the information available - without any logs, it's hard to know what's going wrong (empirically it is possible to add rooms to communities in some cases - I was able to add one to one of my communities just now).

**Comment by vranki** [comment]
I just sent logs for this. I hope they are helpful. Let me know if you need anything else.

**Comment by rterwedo** [comment]
@lampholder We do not get an error, but from a UX pov, the room is not added inside the community you are in, which is strange (its added under the user but then you have to go manually add in a community)

**Comment by dev-zero** [comment]
I just experienced the same issue with a newly created community. Here's what I did:

1. select the community
2. click "+" next to `ROOMS`, add a room, the room gets created, but does not get added to the community
3. go to "View Community", name the previously created room
4. get the error

Now whenever I try to display the community, there's the loading icon for the list of rooms.

**Comment by vranki** [comment]
Communities are being remade completely so I'm afraid this bug won't be fixed in current implementation. Just hurry up with the room based communities :-)

**Comment by roberestarkk** [comment]
I am having this exact same error, except I'm also experiencing an issue where the whole community seems to basically be broken. Rooms can't be added, existing list of rooms (should be empty?) load-spins forever, users get an error saying unable to join but they show up in the list...

Steps to reproduce: Create community, add room successfully, leave room so it goes away, go to try to remove it from the community but see no option for that, assume it'll disappear on it's own.
Try to add a new room to the community.

Are you saying I should just give up on the concept of a community until it's rewritten?
If I leave the community empty and then wait a while and try to recreate it, can I re-use the name?

**Comment by t3chguy** [comment]
Communities on my server are fine, most reports I've heard of issues are from matrix.org users.

**Comment by roberestarkk** [comment]
Oh I see where the demarkation is.
I am a matrix.org user yes, I'll see if I can find where to complain. Thanks!

**Comment by vranki** [comment]
Communities will be remade as rooms. No point in fixing this anymore. Closing.

**Comment by jasonkolodziej** [comment]
Is there a status update on this issue?

Thank you!

**Comment by vranki** [comment]
I don't think this will be touched as communities will be rewritten as rooms. Check synapse high level roadmap.

The advice is: Don't use communities yet, unless you are absolutely sure.

**Comment by dev-zero** [comment]
for anyone else looking for the roadmap and the respective issue/PR:

* https://github.com/orgs/matrix-org/projects/9
* https://github.com/matrix-org/matrix-doc/pull/1772
