### ISSUE TITLE
Deploy an index.html in the /develop/bundles/<hash> dir for bisecting

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#9179]
It'd be nice if `/develop/bundles/<hash>` had an index.html that allowed loading that specific build, so that when an update causes an error, it's possible to bisect exactly which deploy it showed up in

**Comment by eternaleye** [comment]
An alternative would be to deploy an `index-<hash>.html`, though that would not be as discoverable (`/develop/bundles` has a directory listing, `/develop/` loads the app).

**Comment by dbkr** [comment]
The bundles are just the resources - they're not the complete app. The builds from jenkins would be the way to bisect (https://matrix.org/jenkins/job/VectorWebDevelop/).
