### ISSUE TITLE
Notifications on Riot Android app

### ISSUE THREAD

**Issue by 3arn0wl** [vector-im/riot-web#9180]
### Description

Notifications in the Riot Android app are spasmodic. This includes all messages - i.e. ones which incorporate the users' name, as well as those which don't.

### Steps to reproduce

There does not seem to be any reasons why notifications sometimes work, and other times don't. 

Describe how what happens differs from what you expected.
Sometimes notifications are given : at other times they are not. 

Log: sent/not sent? Sorry - they are on other people's devices.

### Version information

The latest version of the Android app, and previous versions too.

- **Platform**: Android

**Comment by t3chguy** [comment]
Try https://github.com/vector-im/riot-android

**Comment by 3arn0wl** [comment]
Opps! Sorry for my mistake!
