### ISSUE TITLE
Configuration of security/privacy impossible in Riot

### ISSUE THREAD

**Issue by vmario89** [vector-im/riot-web#9186]
Hi, in Riot 1.0.1 and using synapse 0.99.2+xenial1 the auto-created room from Synapse is not configurable from Riot. If you click on the button on the right side no panel is changed. I am exspecting to see encryption settings when clicking on the button.

excerpt from homeserver.yaml:
auto_join_rooms:
   - "#hallo:matrix.fablabchemnitz.de"
autocreate_auto_join_rooms: true

![grafik](https://user-images.githubusercontent.com/5631071/54467807-cd2dd200-4787-11e9-8815-8688ba7f9d4d.png)

![grafik](https://user-images.githubusercontent.com/5631071/54467813-d323b300-4787-11e9-8b3a-e324337c72ec.png)

regards, Mario

**Comment by jryans** [comment]
Thanks for the report! Do you see the same issue on https://riot.im/develop?

**Comment by vmario89** [comment]
hi. i removed all the cache from Windows App in roaming-Directory. i think it was cache-related problem. works now
