### ISSUE TITLE
room directory not loading

### ISSUE THREAD

**Issue by vmario89** [vector-im/riot-web#9187]
Hey,

in Riot 1.0.1 i cannot see room directory.  It does not load - everything else is working fine so far. Can you tell me where to find logs from Riot? I only got apache2 web server logs but they do not provide info about internal application problems. i checked the folder but was not able to find sth.

![grafik](https://user-images.githubusercontent.com/5631071/54467922-9c01d180-4788-11e9-924d-bfce5156d859.png)
![grafik](https://user-images.githubusercontent.com/5631071/54467923-a02def00-4788-11e9-9615-4f1744cc57ef.png)

**Comment by jryans** [comment]
You should be able to open DevTools in Riot with Ctrl-Shift-I. Do you see any logs in the Console tab?

Do you see the same issue on https://riot.im/develop?

**Comment by vmario89** [comment]
hi, i updated to v1.0.4-rc.1, still not working.

https://riot.im/develop is working fine. so i guess the mistake is on my side. may it have to to with reverse proxy / web server settings? i am using plesk instance with nginx in front and apache2 in background.

regards, Mario

**Comment by vmario89** [comment]
i dont know why but it works now. i am closing the issue.
