### ISSUE TITLE
Color Scheme not readable.

### ISSUE THREAD

**Issue by dkotrada** [vector-im/riot-web#9189]
### Description

I use an old Laptop. My screen is not Rettina Mac OS. Color of dark and light themes of Riot are really bad in contrast.

### Steps to reproduce

Use 

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by jryans** [comment]
Are there specific portions of the UI that are particularly an issue?

**Comment by lampholder** [comment]
@dkotrada could I ask that you add your thoughts to https://github.com/vector-im/riot-web/issues/7946 ?

Thanks!

**Comment by dkotrada** [comment]
whit new update it is not an issue anymore
