### ISSUE TITLE
when firing up an old matrix client, all your interactive verification requests arrive again

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9197]
i just had all the interactive verif reqs reappear on syncing a client for the first time in a few months. what's more, i couldn't reliably cancel them (either due to the X button not working, or the app being so overloaded it didn't respond to clicks

**Comment by turt2live** [comment]
I suspect this is the same cause as https://github.com/vector-im/riot-web/issues/8629

**Comment by turt2live** [comment]
I think the X not working is https://github.com/matrix-org/matrix-js-sdk/pull/961/files#diff-0a3445e771f0c35ffee76e9d08b65e12R175

**Comment by turt2live** [comment]
Trivial reproduction steps:
1. Close Bob's client
2. Have Alice start a verification
3. Have Alice cancel that verification
4. Start Bob's client

Bob then receives an unexpected verification request, and a silenced error about an unhandled `m.key.verification.cancel` event.
