### ISSUE TITLE
Remove Edge from browser support statements

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9201]
At the current time, we do not intend to do additional work specifically to support Edge.

If it works for most use cases, that's great, but we do not intend to fix issues that affect only Edge.

I believe the React SDK is [the only place](https://github.com/matrix-org/matrix-react-sdk/blame/554da0fec3182cfde2c9110d4ec41396db059bc2/README.md#L28) that needs updating.

**Comment by aaronraimist** [comment]
Should #9175 be closed as well or is that issue going to stay open to think about supporting it in the future?

**Comment by lampholder** [comment]
I'll update #9175 with our current position - I reckon we leave it open as you say to represent our thinking about supporting it in the future :)
