### ISSUE TITLE
Using /upgraderoom with same version number still attempts an upgrade

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/riot-web#9203]
### Description

Was in a room on version 3, and someone was able to trigger another room "upgrade" to the same version.

### Steps to reproduce

- Create a room
- Upgrade it to version 3 using "/upgraderoom 3"
- In the upgraded room, enter "/upgraderoom 3" again
- The room will be locked down, another will open, and it will still be on version 3

Expected result is that Riot should not allow upgrading from 1 version to the same version, as it's basically pointless. It should throw an error message and prevent the command from doing anything.

### Version information

- **Platform**: web (in-browser) or desktop? Tested on Riot /develop branch. Version number is 9735c332fffb-react-bb111dc6c5f9-js-f8985dbb39c6

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Chromium 67
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows 10

**Comment by turt2live** [comment]
Much like https://github.com/vector-im/riot-web/issues/9204, this is technically legal although there's no reason why you would want to do this, aside from maybe recovering from a room being destroyed by some event.
