### ISSUE TITLE
Question: /upgraderoom allows downgrading...should it?

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/riot-web#9204]
### Description

Was in a room on version 3, and was able to downgrade the room to version 1

### Steps to reproduce

- Create a room
- Upgrade it to version 3 using "/upgraderoom 3"
- In the upgraded room, enter "/upgraderoom 1"
- The room will be locked down, another will open, and it will be on version 1

Is this intended behavior?

### Version information

- **Platform**: web (in-browser) or desktop? Tested on Riot /develop branch. Version number is 9735c332fffb-react-bb111dc6c5f9-js-f8985dbb39c6

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Chromium 67
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows 10

**Comment by turt2live** [comment]
Upgrades are not a linear structure and thus have no concept of A before B. Although there's very few reasons you would want to go from version 3 to 1, there's also no reason for us to prevent it given it is a legal thing to do.

Room versions are complicated, and can be read in more detail here: https://matrix.org/docs/spec/#room-versions
