### ISSUE TITLE
Messages in the room are often quickly scrolled out of view when a typing notification appears

### ISSUE THREAD

**Issue by jimmycuadra** [vector-im/riot-web#9205]
### Description

Sometimes when a typing notification appears in a room, the previously sent messages that are visible in the viewport quickly start scrolling up off the top of the screen, as if someone was sending a bunch of empty messages very fast. It doesn't happen every time, but has been happening frequently for me, maybe 3-4 times an hour in a room with ongoing discussion.

### Steps to reproduce

- Chat with people in a room.
- Wait for it to happen.

Log: Not sent thus far, but I could send one if it's needed to diagnose.

### Version information

- **Platform**: Desktop (macOS)

**Comment by chrissphinx** [comment]
Here is a short video showing this bug: https://gfycat.com/fantasticadmiredarctichare

**Comment by ara4n** [comment]
i haven't seen this particular failure mode before, but we've almost finished entirely rewriting the timeline scrolling logic, which will fix this and a few billion other similar issues.

**Comment by ara4n** [comment]
(https://github.com/matrix-org/matrix-react-sdk/commit/71f6b08b265697a716b0cef3a5b1d9d974e84325 is where the rewrite is happening ftr)

**Comment by jimmycuadra** [comment]
It's almost certainly gotten much worse since the last Riot update, so maybe a diff between that release and the previous one can help narrow down the cause.. It's happening often enough that it's bordering on unusable on my most active room. All my friends are getting super frustrated with it >_<

**Comment by strixaluco** [comment]
Me and my contacts are now experiencing this too, but it never occurred before — started to happen today. We are on Riot Desktop 1.0.4 (GNU/Linux and Windows)

**Comment by bwindels** [comment]
Released 1.0.5 as a hotfix, disabling the jump prevention when typing notifs disappear. They will soon come back as we're reworking scrolling and jump prevention as part of https://github.com/vector-im/riot-web/issues/8565 though, hopefully in the next release.

**Comment by bwindels** [comment]
1.0.5 is now live on /app

**Comment by bwindels** [comment]
Closing, please reopen should this still occur on 1.0.5.
