### ISSUE TITLE
Room list sorted a grey room above a red room

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9216]
rageshake included.

**Comment by progserega** [comment]
![1](https://user-images.githubusercontent.com/1297163/59193774-2a3ff500-8bca-11e9-938b-e43db9a64068.png)
When I select "sort by activity" in options - room with latest messages - sort to end of list...
I send messages (from other account) to othe room - and it is drop down to end list. I think that room with newer messages must go to top of list, becouse when "list window" not show all rooms - rooms with latest activity not showing:
![2](https://user-images.githubusercontent.com/1297163/59193969-c7029280-8bca-11e9-8e08-8ccb1d0fc9ae.png)

Web-riot at https://riot.im/develop: a00bceaff737-react-2e556b7df43c-js-7080458f7eaa

**Comment by turt2live** [comment]
Hopefully we've rid the world of this problem with the new room list. If we haven't, my 4 months of work will be extremely sad.
