### ISSUE TITLE
Buildkite builds sometimes exit for no reason

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9218]
Exited with status -1 (agent lost).

This is usually a timeout / resource limit problem.

**Comment by turt2live** [comment]
I think this is largely fixed by some related fixes done to the buildkite agent configuration. We don't appear to need to do anything special to take on those changes.

**Comment by MilsonCodes** [comment]
What agent settings did you change to fix this issue? Or what specific resources did you find were limited? @turt2live
