### ISSUE TITLE
.well-known not honored/read on initial loading of "sign in" page

### ISSUE THREAD

**Issue by olmari** [vector-im/riot-web#9224]
### Description

When we configure our riot-web in our webserver to use "default_server_name": "hacklab.fi" and then go to our riot webpage and click "sign in", riot says "Sign in to your Matrix account on matrix.org", when it should say "..on hacklab.fi", refreshing page corrects it.

ADD/EDIT: To clarify: testing shows this is not only cosmetic, apparently .well-known isn't read at all, as trying to login with only username without server-part in name says that wrong username, but when refreshed page it works.

### Steps to reproduce

- Prerequisite: have working .well-known on hacklab.fi server for matrix http://hacklab.fi/.well-known/matrix/client
- Configure "default_server_name": "hacklab.fi" on config.json
- Go to https://riot.hacklab.fi and click "sign in"
- Observe page wrongfully saying "Sign in to your Matrix account on matrix.org"
- Refresh the page
- Observe page rightfully saying "Sign in to your Matrix account on hacklab.fi"

Log: not sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 73.0.3683.75 and Firefox 65.0.1 tested
- **OS**: Windows 10, Ubuntu 18.10 tested
- **URL**: https://riot.hacklab.fi version 1.0.4

**Comment by turt2live** [comment]
This is effectively blocked on https://github.com/vector-im/riot-web/issues/9290 so we can figure out what the actual relationship is supposed to be.

**Comment by turt2live** [comment]
Transferring fire status to https://github.com/vector-im/riot-web/issues/9290 and tracking progress there, as that's where the fix lies.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3001 - it won't make it into 1.2.0, but should be in the next regularly scheduled release.
