### ISSUE TITLE
Searching for "M_UNKNOWN apache" went horribly wrong in HQ

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9226]
![image](https://user-images.githubusercontent.com/1190097/54726113-3a01ed00-4b37-11e9-84ed-5639aeeb2f14.png)

**Comment by jryans** [comment]
Is it reproducible? I get the following:

![2019-03-21 at 10 33](https://user-images.githubusercontent.com/279572/54746739-d6be9c00-4bc4-11e9-8ad4-d8cd0fbd35a3.png)

**Comment by turt2live** [comment]
Yup, every time I search I get the same single result from someone in June 2018

**Comment by jryans** [comment]
Hmm, I wonder if it's a federation issue...?

**Comment by turt2live** [comment]
Unlikely as the messages should all be indexed the same. I wonder if it's giving you permission issues or something, or if my search index is completely hosed

**Comment by jryans** [comment]
I am seeing logical results for other queries in that room, like "apache" by itself gives ~43 results.

**Comment by turt2live** [comment]
Closing because this a server side problem which only appears to affect my homeserver.
