### ISSUE TITLE
Failure in the composer causes react to break (Fails to display #riot-android)

### ISSUE THREAD

**Issue by RAOF** [vector-im/riot-web#9227]
### Description

Riot fails to display #riot-android:matrix.org. It appears in the room list, but selecting it doesn't change the main display to show the contents of the room. The room appears selected in the room list, and the room breadcrumbs up the top change as if Riot was displaying the room - switching to another room puts the riot-android badge in the leftmost spot, etc. The riot-android app happily displays this room.

### Steps to reproduce

- Select #riot-android:matrix.org from the room list, click the breadcrumb badge, etc 

The UI surrounding the main view changes as if the room was displayed, but the content (room title, members list, messages) does not change from the previously displayed room.

Log: sent    

![image](https://user-images.githubusercontent.com/804339/54727034-c2c96900-4bc9-11e9-8aa1-ec257ecd3118.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox nightly 68
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
No idea what happened here, but the composer exploded

**Comment by lampholder** [comment]
If somebody has half an hour to see if they can resolve this by looking at the logs, please do - otherwise we'll wait until we have more instances reported before digging deeply into it

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by RAOF** [comment]
No. I've just rejoined #riot-android, and it seems fine.
