### ISSUE TITLE
Timeline is missing events

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#9229]
A bunch of events that should have arrived in a gappy sync earlier have gone missing, and now the timeline is out of order. Console shows 
```
rageshake.js:61 Caught /sync error Error: live timeline 0 is no longer live - it has a neighbouring timeline
```

etc.

**Comment by ara4n** [comment]
this is a dup of https://github.com/vector-im/riot-web/issues/8593 ftr

**Comment by jryans** [comment]
Right, I'll close this and move that one into the fire then.
