### ISSUE TITLE
"Never send encrypted messages to unverified devices in this room from this device" seems to be ignored if enabled 

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/riot-web#9235]
### Description

If I enable the security option "Never send encrypted messages to unverified devices in this room from this device" for an encrypted room I can choose "send anyway" in the "unknown devices" warning and the message will be send.

### Steps to reproduce

1. Enable encryption for a room.
2. Enable "Never send encrypted messages to unverified devices in this room from this device" for this room.
3. Send a message. There should be a "unknown devices" warning. Choose "send anyway".

> Describe how what happens differs from what you expected.

The message should _not_ be send. There should be an info message instead saying something like: 

> "You have activated "Never send encrypted messages to unverified devices in this room from this device" in the security settings of this room and have not verified any recipients devices. Verify at least one recipient device to allow Riot to deliver your message to verified devices."

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: GNU/Linux Debian
- **Version**: 1.0.4

Edit: I have to correct my issue description a little bit although the given issue description is not wrong: Messages sent via "send anyway" are shown as "Unable to decrypt: The sender's device has not sent us the keys for this message.".
After I verified the fingerprint of the recipients device the message was readable for the recipient. So the bug seems unfortunately not to be a security problem but anyway very irritating (a message in such a room shouldn't be delivered at all).

**Comment by turt2live** [comment]
This ultimately only affects the per-room option. The global option works fine. Refreshing the page after setting the flag does do the right thing, however the current session was not affected.

Introduced in https://github.com/matrix-org/matrix-react-sdk/pull/2523 and fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2817

**Comment by r4dh4l** [comment]
I have to correct my issue description a little bit although the given issue description is not wrong: Messages sent via "send anyway" are shown as "Unable to decrypt: The sender's device has not sent us the keys for this message.".
After I verified the fingerprint of the recipients device the message was readable for the recipient. So the bug seems unfortunately *not* to be a security problem but anyway very irritating (a message in such a room shouldn't be delivered at all).
