### ISSUE TITLE
riot.im website l10n

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#9237]
Please make https://riot.im website localized:

1. it should use Accept-Language HTTP header. (Like debian.org does, for example.)
2. and take translation from translate.riom.im

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4458

**Comment by 532910** [comment]
sorry

**Comment by turt2live** [comment]
no worries, we'd rather have duplicates than silence. I just have to sound a bit cold in my message to make github do the right thing is all :)
