### ISSUE TITLE
[Feature Request] Busy/DND/Do Not Disturb capabilities

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#9239]
Any chance we can get Busy/DND/Do Not Disturb functionality baked into Riot? And then maybe have that hook into external systems that could toggle/trigger it?

Per conv/chat room doesn't work for every scenario, a global setting would be nice.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/1672

See also https://github.com/vector-im/riot-web/issues/3569, https://github.com/vector-im/riot-web/issues/7758

**Comment by BloodyIron** [comment]
oops, sorry
