### ISSUE TITLE
Welcome user id does not work

### ISSUE THREAD

**Issue by vmario89** [vector-im/riot-web#9246]
Hi,
in Riot 1.0.5 and 1.0.4 it seems that welcomeUserId does not work. I think it does not work since i activated privacy policy/consent/terms. If i create a fresh user on my server the new user will not be greeted by the bot i added to config.

>     "welcomeUserId": "@riot-bot:matrix.org",

Any ideas?

regards, Mario

**Comment by vmario89** [comment]
you can try it out yourself by creating an mxid on riot.fablabchemnitz.de

**Comment by turt2live** [comment]
The request to create the room is failing because the user hasn't accepted the terms of service yet. It looks like your homeserver is using the legacy flow for this. In the config, make sure `require_at_registration` is `true` under `user_consent`.

**Comment by vmario89** [comment]
hi.  did. but it makes no difference. when creating a new user the user wont get a hello from riot-bot

**Comment by turt2live** [comment]
does the user get a checkbox to accept the terms and conditions when registering? If they receive the dialog to review terms and conditions, synapse is not configured correctly.

**Comment by vmario89** [comment]
Hi,
yes the user gets checkbox displayed before joining the rooms indeed:
![grafik](https://user-images.githubusercontent.com/5631071/54886679-03a3d500-4e8b-11e9-9425-fec4f2304089.png)

**Comment by turt2live** [comment]
looks like it works for me now. The `welcomeUserId` is only used for new accounts, not new logins. Does the same happen for you too?

**Comment by turt2live** [comment]
@vmario89 I'm assuming the issue is fixed - please visit us in #riot:matrix.org on Matrix if you need further support.
