### ISSUE TITLE
Tooltip on the buttons "start a chat" and "join a room"

### ISSUE THREAD

**Issue by albangegout** [vector-im/riot-web#9249]
Users couldn't find how to start a new chat or to join a room.

**Comment by lampholder** [comment]
Some tooltips are a good place to start.

We can probably do a reasonable and _very_ quick job with `title` text in the `<div>`:

![image](https://user-images.githubusercontent.com/1922197/54837104-7f502700-4cbd-11e9-98e8-6cb72be6f6f5.png)
(imagine the mouse pointer)

What text do we want in there?

How about:

- PEOPLE (+) - Start a new private conversation with somebody
- ROOMS (+) - Find an existing chat room, or create a new one

@nadonomy - what do you think?

**Comment by turt2live** [comment]
(popovers are not difficult to do and we should avoid `title` tags imo)
