### ISSUE TITLE
Devtools: Explore room account data

### ISSUE THREAD

**Issue by dnaf** [vector-im/riot-web#9267]
The devtools currently have an "Explore account data" dialogue, but no dialogue to interact with per-room account data.

**Comment by dnaf** [comment]
Aaaaaaaaaaand I see now that this dialogue has a button to switch to room data that I hadn't noticed. Whoops 😅

**Comment by jryans** [comment]
Feel free to submit some UX tweaks to improve the DevTools dialogs if you'd like. 😄
