### ISSUE TITLE
Clearing a room list filter visually emptied my people section

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9273]
![image](https://user-images.githubusercontent.com/1190097/54943151-549ce300-4ef6-11e9-9c18-5fff4f440656.png)

I was searching for a particular chat, got no results, then clicked the X to clear the filter. Was presented with this.

**Comment by lampholder** [comment]
@turt2live have you seen this recently? I haven't seen anything like this in quite a while

**Comment by turt2live** [comment]
I haven't seen this but iirc Matthew has

**Comment by turt2live** [comment]
This is a duplicate of some other bug we fixed. The lazy-loaded tiles were misbehaving.
