### ISSUE TITLE
Room directory shows [m] matrix entry which gives same results as HS

### ISSUE THREAD

**Issue by eMPee584** [vector-im/riot-web#9286]
The room directory search on our server (riot v1.0.5 at the moment) shows an entry **[m] Matrix** which I thought should search matrix.org, but it only shows the same search results as a HS search. Adding matrix.org to config.js
```
    "roomDirectory": {
        "servers": [
            "matrix.tii.tu-dresden.de",
            "matrix.org"
        ]
    }
```
will show an additional matrix.org list entry that works normally.
This on firefox and chromium (linux).

c.f. https://matrix.tii.tu-dresden.de/ => Explore rooms: Room Directory

**Comment by turt2live** [comment]
This is caused by https://github.com/vector-im/riot-web/issues/6260
