### ISSUE TITLE
Room directory suggests old versions of rooms

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9288]
## STR

1. Search the matrix.org room directory for "gsoc":

![image](https://user-images.githubusercontent.com/279572/55023840-91033880-4ff5-11e9-91dd-cd2fec19d017.png)

2. The "[Unnamed room](https://riot.im/develop/#/room/!WZbLERcNJxrvkxPfyV:matrix.org)" is the right room, but an old version

## Expected

I expected to see the [latest version](https://riot.im/develop/#/room/!ahcBstQiPShMcpZxLK:jki.re) of the room instead.

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/9284

**Comment by turt2live** [comment]
This is a synapse issue: https://github.com/matrix-org/synapse/issues/4948
