### ISSUE TITLE
roomlist is slow on re-sorting after you've viewed a room and moved away

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9296]
the room should drop down immediately rather than hang around for ~300ms before dropping down, otherwise it feels a bit weirdly flakey

**Comment by Bendodroid** [comment]
Most of the time it's not 300 ms, more like 5 s for me. And sometimes the sorting fails completely. The "Synapse Admins" room is especially stubborn for no apparent reason. I have "Sort by name" and "Show rooms with unread messages first" enabled but that room in particular always stays somewhere far down while others are at the top as they are supposed to be. And the best thing is that it is not really reproducible how to reliably break it. Reloading Riot helps most of the time, but not always (In the browser reloading the tab or completely restarting the electron app).

**Comment by Bendodroid** [comment]
After updating riot-desktop to 1.6.0 (on Arch Linux) the sorting is no longer slow. The weird behaviour with the "Synapse Admin" Room persists, though. In the browser it's as before.

**Comment by turt2live** [comment]
the rate limit makes it appear slow when it's not, and artificially makes it slow when it shouldn't be. The update should have had no effect, just probably a perceived effect.

**Comment by turt2live** [comment]
We've fixed this with the new room list.

**Comment by Bendodroid** [comment]
Can confirm this is no longer an issue, room list is now working as it should be in Element Desktop. Good job :+1:
