### ISSUE TITLE
Recent chrome + macOS makes the touchbar flash every time you press a key in the composer

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9299]
Chrome Version 73.0.3683.86, macOS 10.14.3. It is horrrrrrrrrific

**Comment by turt2live** [comment]
My instinct says this might be part of https://github.com/vector-im/riot-web/issues/7665 but only barely.

**Comment by lampholder** [comment]
Probably another one to be solved by the [Simple, stable composer](https://github.com/vector-im/riot-web/issues/7697)

**Comment by Ai-rin** [comment]
In my case (linux with fcitx as input method framework) it causes quick momentary layout changes every time i press a key. This, and its slowness are driving me crazy.

**Comment by aaronraimist** [comment]
I can't reproduce this in the new composer

**Comment by aaronraimist** [comment]
(deleted my comment about not being able to reproduce, I actually can reproduce it. It doesn't happen on every key press but it does happen randomly.)

**Comment by ara4n** [comment]
i just turned on my touchbar for the first time in about 8 months and was dismayed to discover this is still happening, despite CIDER :( it's literally every keypress.

@bwindels are you surprised that something changes the entire function of the inputbox every time you press a key?

**Comment by jryans** [comment]
This flickering seems to happen when the composer modifies selection state.
