### ISSUE TITLE
How to delete the "deleted message" event ?

### ISSUE THREAD

**Issue by Verboli** [vector-im/riot-web#9301]
Hi, I would like to know how can I delete the "deleted message" event : 
![bug](https://user-images.githubusercontent.com/48999695/55098718-a2644780-50be-11e9-9ae5-fe6429f1e725.png)
I have a room that has to stay clean (images list), and I don't want to see some trash in the room.

Is it possible to delete this event for everyone, without having to tell everyone to activate the "hide deleted messages" option ?

**Comment by jryans** [comment]
No, it's not possible to delete events for others. It's important to understand that in Matrix, similar to email, you can't force a client to hide or delete anything.

**Comment by turt2live** [comment]
If you're confident enough in playing with the guts of room, there is an opportunity to turn that setting on for everyone only in that room.

**Comment by jryans** [comment]
For other support questions like this, I would recommend asking in the #riot:matrix.org room.
