### ISSUE TITLE
Joining OFTC IRC chat issue

### ISSUE THREAD

**Issue by shiftee** [vector-im/riot-web#9307]
### Description

Be forewarned I don't entirely know what i'm doing.

Yesterday I tried to join an IRC chat using the following address:
`#_oftc_#osm-ie:matrix.org`

It seems to have succeeded as I can see a post from this morning.

There is however an invite which I cannot clear (see image).
Clicking accept causes a loading indicator to appear which never ends.

How do I get rid of this invite?

Thanks

![Screenshot from 2019-03-28 10-19-39](https://user-images.githubusercontent.com/1383407/55149740-a33ebd00-5142-11e9-8157-84077cbf0e0a.png)
### Steps to reproduce

- Join the room #_oftc_#osm-ie:matrix.org
- The invite doesn't go away after clicking accept

### Version information

- **Platform**: web (in-browser) or desktop?
I joined the room using the web client: https://riot.im/app
The notification is present on my F-Droid Riot app also.

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? 65.0.1 (64-bit)
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Ubuntu 16.04
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? https://riot.im/app

**Comment by shiftee** [comment]
The invite persisted over the weekend.
I rejected it and it went away.
I am still a member of the room.

**Comment by jryans** [comment]
Thanks for the report! I am not sure what the root cause is here... Maybe try asking in [#irc:matrix.org](https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org?via=matrix.org&via=feneas.org&via=chat.weho.st) where the IRC bridge experts may have ideas.

**Comment by Half-Shot** [comment]
This seems like a synapse / riot issue if the invite is lingering. If it's no longer an issue, can this be closed.

**Comment by shiftee** [comment]
I haven't joined another room since, but I think it's likely you would have come across it if it was still an issue.
I'm happy to close

**Comment by jryans** [comment]
Let's close for now then, and we can adjust in the future if there are other reports. Thanks for the feedback!
