### ISSUE TITLE
Link preview does not work

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#9310]
### Description

Link previews for newest messages do not work: sites, youtube, etc. Works for history messages months ago. Clean cache and restart button does not help.

### Version information

- **Platform**: both: web (in-browser) and desktop

For the web app:

- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/develop & riot.im/app & desktop

For the desktop app:

- **OS**: SUSE Linux
- **Version**: 1.0.5

**Comment by akontsevich** [comment]
Ha, works again now  - server side thing?

**Comment by jryans** [comment]
Yes, I believe there were some temporary failures with the link preview API on matrix.org.
