### ISSUE TITLE
Version 3 room reporting vulnerability

### ISSUE THREAD

**Issue by E-werd** [vector-im/riot-web#9311]
### Description

Version 3 room is reporting:

There is a known vulnerability affecting this room.
This room version is vulnerable to malicious modification of room state.
Click here to upgrade to the latest room version and ensure room integrity is protected.
Only room administrators will see this warning

Internal room ID: !RBQNbVLNepzbeBbkpz:phuks.co
Screenshot of room setting: https://i.imgur.com/DPjHQbq.jpg

### Steps to reproduce

- Unsure.  It seems to happen after the server goes offline, likely from a crash.

Describe how what happens differs from what you expected.

Log: sent

### Version information

- **Platform**: desktop
- **OS**: Windows 10 1809
- **Version**: 1.0.5

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/9225 - I'll move your rageshake over there.
