### ISSUE TITLE
Ability to use standard scrollwheel to scroll breadcrumbs

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9314]
The ability to scroll breadcrumbs is a huge win, though not as productive if I have to click and drag the scrollbar, which is kind of a slow process.

It would be nice if the standard vertical scroll could scroll horizontal if hovering over the breadcrumbs in order to scroll through them.

**Comment by turt2live** [comment]
fwiw, it works great if you have a mouse which supports horizontal scrolling...

**Comment by anoadragon453** [comment]
Lemme just order one :P
