### ISSUE TITLE
"User ID taken" error clears registration form

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9320]
![user-id-taken mp4](https://user-images.githubusercontent.com/1190097/55202719-305b3380-518e-11e9-82c9-d0e71986eb7d.gif)

**Comment by t3chguy** [comment]
I knew there was an issue for this somewhere, fixed this recently :D

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3299
