### ISSUE TITLE
hitting search button should autofocus search input field

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9322]

**Comment by t3chguy** [comment]
This works for me

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/57735824-d52dc380-769d-11e9-9f41-43b164b2caf1.png)

Could it be a platform specific thing?

**Comment by yannicka** [comment]
Do you still have the problem? I can't reproduce it either (on Riot Desktop 1.6.0).
