### ISSUE TITLE
The desktop app has no 'save as' function for files

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9324]
On riot/web you can save files directly to disk by right-click and save-as on the link.  On desktop, you don't have this right click, so the only thing you can do is to 'open' the file (which for an image, opens it in a web browser, which is a bit surprising).

![garden](https://user-images.githubusercontent.com/1294269/55244001-386fad80-5238-11e9-9750-21a2ba177c82.jpg)

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/7104

**Comment by ara4n** [comment]
Related: https://github.com/vector-im/riot-web/issues/5162

**Comment by mortlind** [comment]
I am on 1.3.6 in the desktop app, and I do not have a "save as" in the context menu. I only have the link to the element and a "Copy link address"-item.
