### ISSUE TITLE
No responsive design?

### ISSUE THREAD

**Issue by akuckartz** [vector-im/riot-web#9329]
I am using riot-web from Chrome on an Android Smartphone. The page looks like displayed on a large screen.

**Comment by aaronraimist** [comment]
Riot web isn't designed for mobile phones. Riot shouldn't let you open it, it is supposed to provide you with a link to the android app. You probably have your user agent set as a desktop browser.

**Comment by akuckartz** [comment]
That sounds like "This bug is a feature."

I would like to use Riot web on mobile phones and don't like to depend on OS-specific "Apps".

**Comment by tulir** [comment]
It is a feature. Native apps provide a far better experience than a web app and it's much less work to only support larger screens.

**Comment by akuckartz** [comment]
> it's much less work to only support larger screens

That is the (only) reason which I think might have some validity. But responsive design now has a history of about nine years and I don't see why it is can't be used efficiently in developing riot web. It seems to have been a goal in the past: #82

**Comment by tulir** [comment]
> It seems to have been a goal in the past: #82

I'm pretty sure that was just responding to narrower desktop browser windows (e.g. using half a screen). Riot web has never targeted mobile browsers because the native apps have always been there and done it better. At this point, it would be a ton of work to make everything mobile optimized and there are much more important things to do too.

**Comment by aaronraimist** [comment]
I think it is quite likely that another web client will come along that targets mobile web browsers but Riot probably isn’t that client. They already employee people to write great native apps so I don’t think they are going to put much focus on Riot web working on mobile.

The beauty of matrix is you can use any client you want. Eventually if many people want it, someone will write a good mobile web client.

**Comment by jryans** [comment]
We would need to very consciously choose to support mobile web and invest in making it work for there to be any chance of it working well as each new feature lands over time. At the moment, we're focusing on the Riot apps for mobile, so I'll close this issue.

If you'd like to open a new issue that explains your use case for mobile web stated as a suggestion, we could use that to track interest going forward.

**Comment by akuckartz** [comment]
This issue was intended as such a suggestion. *Thanks for discussing it here*, but I will not create yet another issue for the same purpose. I consider this as closed with resolution "won't fix". That might play a role in evaluations of the Matrix ecosystem or not.

**Comment by jryans** [comment]
To be clear, with my community member hat on, I would also like to see mobile web clients exist. Riot itself just isn't in a position to offer that today.
