### ISSUE TITLE
Strikethrough is broken in markdown mode

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/riot-web#9330]
### Description
The strikethrough markdown feature is not working. The text is sent literally.

### Steps to reproduce

- type a word surrounded by two tildes, ~~test~~

### Describe how what happens differs from what you expected.
I expect it to put a strike through the word. I recently did it successfully from the Android app, but both my friend and I can't get it to work in the web version. I'm using develop. I do not know what he's using, but there is a high chance it's just stable.
![2019-03-31-084258_433x152_scrot](https://user-images.githubusercontent.com/3146494/55289865-882ab200-53bb-11e9-9323-0bbf49146f72.png)
### Version information

- **Platform**: web (in-browser)

- **Browser**: GNU IceCat 60.6.1esr, the version numbers match up with firefox and the main difference is removed things, about:config tweaks, and some default addons
- **OS**: GuixSD GNU/Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Riot Web uses commonmark which doesn't support tilde strike through. Use the del html tag format instead.
