### ISSUE TITLE
/devtools create a state event dialog has broken alignment

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9332]
![image](https://user-images.githubusercontent.com/2072976/55297617-df626e00-541f-11e9-8aa7-6c29509d7d8a.png)

State Key should be gently poked to the left

**Comment by t3chguy** [comment]
this only happens on narrow views, where its wide enough it fits fine:
![image](https://user-images.githubusercontent.com/2403652/57735644-35703580-769d-11e9-9d74-78d383c5d016.png)

**Comment by jryans** [comment]
Sprinkling some flex CSS should solve it...
