### ISSUE TITLE
Timeline not scrolling to bottom on new messages.

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-web#9334]
### Description

Since Friday (2019-03-29), scrolling has been broken on my Linux desktop machine. New messages, inbound from other users or created by me, do not cause the timeline to scroll to the bottom and are therefore invisible.

### Steps to reproduce

- Send a message in a room. Timeline does not move (or in some cases appears to move backwards)
- Scroll to bottom manually to see the posted message.

### Version information

For the web app:

- **Browser**: Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
- **OS**: Linux (Mint)
- **URL**: https://riot.im/develop

![scroll issue](https://user-images.githubusercontent.com/6763606/55316460-5d496800-5466-11e9-8ca8-0620a2e16c31.gif)

**Comment by bwindels** [comment]
Should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2865, are you still seeing this on /develop @rxl881 ?

**Comment by lampholder** [comment]
Rick confirms he hasn't seen this again

**Comment by SanderVanKeer** [comment]
I'm having the exact same issue now in the following version:

Element version: 1.7.14
olm version: 3.2.1

Any ideas?
