### ISSUE TITLE
Rooms keep going missing in my room list

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9336]
### Description

One of my rooms (seen in the logs) has been hidden in my list, without me doing any actions. I still
get notifs from the room and can get to the room via hyperlinks.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.0.5

**Comment by Half-Shot** [comment]
More interestingly once they are gone, they stay gone across restarts.

**Comment by turt2live** [comment]
What's the room ID we should be looking for? Please add a comment to the rageshake of it's private.

**Comment by Half-Shot** [comment]
Added room_ids to the rageshake

**Comment by turt2live** [comment]
The first one appears only in the context of enabling encryption, but never again. The other does not show up. I wonder if Riot just doesn't recognize the rooms anymore - does clear cache and reload fix it?

**Comment by Half-Shot** [comment]
I've cleared the cache and reloaded, and rageshaked above.

**Comment by Half-Shot** [comment]
A fresh session of riot.im/develop in the browser has the rooms listed, so this seems to be a problem limited to my desktop session.

**Comment by Half-Shot** [comment]
I logged in and out of the desktop client and imported my keys from the key backup, however my room list is *still* missing these rooms :/

**Comment by turt2live** [comment]
The logs aren't showing the room going missing at all. Does this happen when filtering? Scrolling through the list?

**Comment by Half-Shot** [comment]
Both with the filtered and non-filtered views, it's not in the list even if I scroll top to bottom.

**Comment by Half-Shot** [comment]
Happened again. I have a brand new session of riot.im/develop and 1.1.0:

Missing room is "!OluOzqbTJgecdDIuKn:half-shot.uk" (Matrix Discord Bridge)

1.1.0:

![image](https://user-images.githubusercontent.com/2072976/57637525-8c91df80-75a3-11e9-8920-10f1453bb869.png)
![image](https://user-images.githubusercontent.com/2072976/57637556-9c112880-75a3-11e9-8e7d-26a1c0cd622c.png)

develop:

![image](https://user-images.githubusercontent.com/2072976/57637574-aaf7db00-75a3-11e9-9cb6-dc9251117965.png)

**Comment by Half-Shot** [comment]
`!bnLgpuUKYinJhwsUeO:matrix.org` has gone too

**Comment by gnorbsl** [comment]
I clicked on the community icon in the desktop app and all but one room are hidden now in the room list, I can be @pinged which shows me the room but not in the list. I can only see rooms that are free to join for guests.

This is a privately hosted riot server.

**Comment by jryans** [comment]
@gnorbsl This sounds like just how filtering by a community works today. To unfilter, you click an empty space on the community bar on the far left. Anyway, it is known that is confusing, and is a separate issue from this, such as https://github.com/vector-im/riot-web/issues/9026.

**Comment by turt2live** [comment]
@Half-Shot have you seen this recently? It seems like this issue is one of the warning bells for https://github.com/vector-im/riot-web/issues/11303, though the logs here are less informative (due to lack of logging at the time).

**Comment by Half-Shot** [comment]
I've not noticed this recently. Shall we close this?

**Comment by turt2live** [comment]
Yea, I'll close this side for now.
