### ISSUE TITLE
Power Levels are all 0 in user page

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9340]
### Description

Power levels in all rooms show as 0 for every user, even though their icon is marked correctly in the user list.

![image](https://user-images.githubusercontent.com/1342360/55340564-df548380-549c-11e9-919d-ec5a3a7b456a.png)

![image](https://user-images.githubusercontent.com/1342360/55340586-e8ddeb80-549c-11e9-913f-2f5748ec7e25.png)

### Steps to reproduce

- Go into a room with admin/mod
- Notice they have a badge next to their icon
- Click their account and see their PL is reported as 0

Log: sent

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: build of riot.im/develop

**Comment by jryans** [comment]
@anoadragon453 Any chance you can recall when you last saw this working correctly?

**Comment by anoadragon453** [comment]
@jryans Not really, other than the fact that I know it was working at the time of https://github.com/vector-im/riot-web/issues/9039

@babolivier @benparsons seemed to experience the same bug. Do you guys have any idea when it might've started?

**Comment by turt2live** [comment]
I think this is the long standing bug where when you click on someone's avatar it opens MemberInfo differently for some reason. Previously it would show "Restricted", but that dropdown is now clamped.
