### ISSUE TITLE
Scroll-to-bottom is broken in rooms with things in the headers (AuxPanel)

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9342]
### Description

Riot can still get into a state where its `scrollTop` value becomes non-int.

![image](https://user-images.githubusercontent.com/1342360/55344203-b33d0080-54a4-11e9-819f-5b67c086ac36.png)

This creates problems such as entering a room not scrolling to the correct position, and scrolling to the bottom of a room does not remove the scroll-to-bottom button. A fix was attempted in https://github.com/matrix-org/matrix-react-sdk/pull/2846 but does not seem to have completely solved the issue.

### Steps to reproduce

- Happens at some random point. Refresh fixes the issue
- The issue also just seems to be fixed at random points as well, possibly due to functionality introduced in the above mentioned PR

Log: sent

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: build of riot.im/develop

**Comment by anoadragon453** [comment]
Actually this seems to only happen in rooms with the simple counters Labs feature.

**Comment by anoadragon453** [comment]
This also seems to happen with rooms with widgets.

**Comment by bwindels** [comment]
You got the values posted in the screenshot above while being entirely scrolled down in a room?

**Comment by anoadragon453** [comment]
@bwindels That is correct.

**Comment by bwindels** [comment]
Should be fixed on /develop now
