### ISSUE TITLE
Ugly 'download failed' dialog if you cancel a 'save as' operation on electron

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9350]
If you right-click on an attachment and choose 'save as', but then hit cancel rather than selecting a download location, electron coughs up an ugly 'download failed' warning, rather than ignoring your cancellation

**Comment by turt2live** [comment]
fwiw, the reason for the ugly dialog is that we don't have access to our fancy dialogs at this level and have to rely on the OS to do something sensible. At least in the case of Windows, it's a plain MessageBox.
