### ISSUE TITLE
Sticker picker sends a sticker multiple times after switching rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9354]
1. Add stickers
2. Be in 2+ rooms
3. Open sticker picker
4. Switch rooms
5. Switch back
6. Send sticker
7. See multiple

Happens with Scalar and Dimension - appears to be a Riot issue. The picker is sending one sticker over postMessage, and Riot is sending several out. Probably something to do with remounting?

**Comment by jryans** [comment]
This seems like a bad bug to live with for 2 weeks... It may discourage using stickers once people hit it. Should we do a hotfix for this?

**Comment by turt2live** [comment]
I'm not really sure to be honest. The broken behaviour landed on develop 2 weeks ago, and landed on staging 2 weeks ago. With only one complaint about it happening, I'm more interested in statistics for how stickers are currently used: it comes across as a feature which is not used and therefore has minimal impact.

**Comment by dali99** [comment]
Id think most sticker users are self hosted considering how "uninteresting" the stickers on riot.im are.

They might not have bothered to update for a couple of weeks like I did before this bit me, (caught 10 minutes after upgrading dimension and riot)

**Comment by jryans** [comment]
Okay, if current usage is low, then perhaps it's okay at the moment.
