### ISSUE TITLE
[Critical] Bitdefender thinks Riot.im is malware

### ISSUE THREAD

**Issue by vc7ee** [vector-im/riot-web#9358]
### Description
**Platform**: Windows 10 with Bitdefender. If someone is able to look in to it, I can give licenses associated with my account.

### Steps to reproduce
1. Install Riot.im
2. in 15hrs Bitdefender will scan
3. Ohno Riot.im is poof!
4. Restore Riot.im from Bitdefender
5. Riot.im is still poof!
6. Unistall the Riot.im without icon
7. Try to install from just downloaded .exe (64x)
8. Think of install locations (I found no documentation of install locations) to manually remove, find Appdata/Local/Riot and delete it
9. Try to install
[10. Fail again, log.](https://paste.ubuntu.com/p/9KtxVT6ZFS/)
![image](https://user-images.githubusercontent.com/38327267/55398776-e6c96a80-5538-11e9-88af-b0542e697c2c.png)
(ignore the Ubuntu terminal window, using AnyDesk I can't do a screenshot on my computer without entering the command in the terminal)

Now the computer is unable to riot. (except web)

**Comment by turt2live** [comment]
@RasmusKallas I'm not able to reproduce this. Here's what I tried:

1. Create a fresh Windows 10 Pro machine
2. Install Bitdefender and run a few quick scans
3. Install Chrome to download Riot from riot.im/desktop.html
4. Open the installer and log in to Riot
5. Run a quick scan in Bitdefender with the app in the foreground
6. Run a quick scan in Bitdefender with the app in the background (tasktray)
7. Completely close Riot
8. Run a quick scan in Bitdefender
9. Run a complete scan in Bitdefender
10. Update Windows (including restart)
11. Run another complete scan in Bitdefender

At no point did Bitdefender alert me to the problem, and it didn't delete anything (manually checked). The app still operates normally.

The setup log indicates permission errors writing to the install directories. Given your mention of AnyDesk, this sounds a bit like a customized environment (possibly corporate/remote support) - is the target machine under a group policy or something that prevents writing to the appdata folder? Is a custom blacklist being used for Bitdefender? Is the user able to create a text file (and applicable directories) in `%USERPROFILE%\AppData\Local\riot-web\test.txt` ?

**Comment by RasmusKallas** [comment]
I would note that I have since contacted Bitdefender.
This is a granny customized environment. Fresh windows 10 + anydesk + chrome + bitdefender + libreoffice, as fast as possible. I'll get back to you on the permissions.

**Comment by vc7ee** [comment]
Fixed.
