### ISSUE TITLE
Riot Web attempts to work too aggressively on mobile

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9360]
Related PR: https://github.com/vector-im/riot-web/pull/9363

- [x] Investigate what's going on
- [x] Add cookie expiry time 
- [x] Adjust expiry time to 4hrs
- [x] Cookie expiry set in `onBackToRiotClick()` doesn't solve the problem for users with the cookie already set. Clear with next release?
- [x] Make CSS more mobile friendly, so text doesn't render tiny (and update branding along the way)

Notes from internal chat, tested on iPad:

https://matrix.to/#/!tAMgPDeOawUJMkFXVZ:matrix.org/$1553800151544179fppPV:matrix.org?via=matrix.org&via=jki.re&via=dbkr.me

**Comment by turt2live** [comment]
more info: Sometimes it works, sometimes it doesn't. Tom got no mobile guide, but then at some point in the rageshake process got it suddenly. Seems like 2/5 devices skipped the guide

**Comment by turt2live** [comment]
So both cases of this happening in our standup are actually a feature: https://github.com/vector-im/riot-web/pull/7415 (https://github.com/vector-im/riot-web/issues/7378)

I'll at least open a PR to expire the cookie after 24 hours or so (the page is a bit complicated, so a short TTL is easier than 'make it work for a session'), however the rest I'm leaving to @nadonomy and @lampholder to figure out.

**Comment by nadonomy** [comment]
I took a look at the PR. I think setting an expiry time on the cookie seems reasonable. A few thoughts on how we can improve fixing this further:

1. The cookie expiry is set in `onBackToRiotClick()`, which I assume won't solve the problem for users who already have the cookie set, so we should figure out something for them.
2. Is an expiry time of 2 or 4hrs more appropriate? It's enough to not be constantly popping up interrupting a session but for multiple sessions users should really be using a mobile app.
3. Whenever I hit the bug, because the install guide was shown after loading the client, the install guide was tiny. I assume somewhere along the app stack meta viewport CSS is erroneously cascading. This is a must fix to consider the issue solved.

@lampholder let me know your thoughts.

**Comment by lampholder** [comment]
I remember now our deciding not to show the install instructions on deep links. On reflection I think this is a bit weird, but I think will get some attention when we condsider link-based onboarding in more detail.

In the meantime, if we fix https://github.com/vector-im/riot-web/issues/8384 and make the mobile install instructions dismissable as per @turt2live/@nadonomy's discussion above, I think we'll be back in a reasonable place.

**Comment by nadonomy** [comment]
Updated parent comment with a checklist of outstanding stuff before we consider the issue resolved. Feel free to edit/amend/add to it.

**Comment by turt2live** [comment]
@nadonomy I'm not able to reproduce the tiny effect. The guide is a bit on the small side, but it sounds like you're running into a worse problem than that.

Here's what I see:
![image](https://user-images.githubusercontent.com/1190097/55521282-617bae00-563d-11e9-9018-aa785f231aad.png)
