### ISSUE TITLE
Vague error when trying to create a room alias that already exists

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9367]
### Description

![image](https://user-images.githubusercontent.com/1342360/55442180-6ee55980-55a5-11e9-969e-11e67e786d2c.png)

A generic error is shown when trying to add an alias to a room that already has the alias, rather than an error message that explicitly states that.

The response received from Synapse is a `409` - Conflict.

### Steps to reproduce

- Create an alias in a room that alias already exists.

**Comment by anoadragon453** [comment]
Possibly related: https://github.com/matrix-org/matrix-react-sdk/pull/835

**Comment by Biep** [comment]
This occurs if the alias is in use anywhere - not necessarily for the same room.
The message might link to the room that has the alias - maybe it is what people want, only they didn't know the room already existed, and therefore created another one.

**Comment by turt2live** [comment]
We replaced this with a tooltip saying it is taken
