### ISSUE TITLE
Firefox's "view image" causes logout

### ISSUE THREAD

**Issue by tleydxdy** [vector-im/riot-web#9369]
### Description

Web client's will get logged out when using "view image" in the right click menu to enlarge image in a e2ee room

### Steps to reproduce

- click a image in e2ee room to open it
- right click and select "view image"
- go back, and greeted with a guest screen trying to access that room
- refresh will bring you to the login page

Log: none    

In a non-e2ee room this is fine, the difference I could spot is that when viewing image the url starts with http in non-e2ee room, and blob in e2ee room (not super sure, but definitely not http). 

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 66.0.2
- **OS**: Arch
- **URL**: riot.im/app

**Comment by tleydxdy** [comment]
after a bit of testing, it's umatrix plugin that causes the problem, but I've enabled all the boxes in umatrix. even disabling umatrix for the site causes the same problem.

**Comment by tleydxdy** [comment]
okay, it seems like it's umatrix blocking blob:https://riot.im from accessing localstorage. I'm not sure if this is something riot could fix now, I've reported it to umatrix https://github.com/uBlockOrigin/uMatrix-issues/issues/126

**Comment by jryans** [comment]
Thanks for the report! That doesn't sound like something that Riot could anticipate, so I think I'll go ahead and close this since you found a solution.
