### ISSUE TITLE
Welcome page link to riot bot should be pulled from config.json rather than hard coded

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9379]
We should consider the button in the bottom left pulling from `config.json` rather than being hardcoded (but this is not entirely straightforward - the button says 'Chat with Riot Bot' but we only put the mxid in config.json).

![image](https://user-images.githubusercontent.com/1922197/55543556-29b64a00-56c1-11e9-84a5-80ab58b89c27.png)

**Comment by jryans** [comment]
This is quite similar to https://github.com/vector-im/riot-web/issues/9263, though the other issue is about disabling the button.

**Comment by lampholder** [comment]
Oh yeah, this is basically a dup of #9263; closing
