### ISSUE TITLE
Loses track of "first unread message"

### ISSUE THREAD

**Issue by abderrahim** [vector-im/riot-web#9382]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

Not sure if this reproduces every time, but I noticed it happens when I

- open a room with 200+ messages,
- scroll up a couple messages,
- a new message arrives

Describe how what happens differs from what you expected.

Riot used to keep track of unread messages until I see them (or close the notification).

Log: not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox (60.6.1 ESR)
- **OS**: Debian
- **URL**: riot.im/app

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/12338
