### ISSUE TITLE
Make integrations_ui_url configureable for electron

### ISSUE THREAD

**Issue by enko** [vector-im/riot-web#9386]
It would be nice if the electron app could make `integrations_ui_url` configureable. At the moment it is hardcoded to scalar.modular.im and I cant set it to my self hosted instance.

A settings entry where I could specify a custom integration server. Alternativly I coudl think of that synapse advertises a integrations server so I dont have to configure all my clients (See https://github.com/vector-im/riot-ios/issues/2356).

**Comment by t3chguy** [comment]
You can provide an override config file as specified here: https://github.com/vector-im/riot-web#desktop-app-configuration

**Comment by enko** [comment]
@t3chguy While this works under Linux like a charm, I can't seem to get it running under windows. This is my `config.json`:

```
C:\Users\tim_1wij8gh>cat %APPDATA%\Riot\config.json
{
    "integrations_ui_url": "https://dimension.schumacher.im/riot",
    "integrations_rest_url": "https://dimension.schumacher.im/api/v1/scalar",
    "integrations_widgets_urls": ["https://dimension.schumacher.im/widgets"],
    "integrations_jitsi_widget_url": "https://dimension.schumacher.im/widgets/jitsi"
}
```
The strangest thing is, that the stickers are using the other integrations, but the Button on the top of a channels, still calls the integrations on modular.im.

**Comment by targodan** [comment]
It does not work on Arch Linux for me. See #9476

**Comment by enko** [comment]
@targodan I edited `/etc/riot/config.json` to make it work. I did not try `$XDG_CONFIG_HOME\$NAME\config.json`

**Comment by t3chguy** [comment]
So the issue is, it works for only the configuration options for the electron side of the app due to an oversight on my part

**Comment by jryans** [comment]
We'll use https://github.com/vector-im/riot-web/issues/9476 to track the problem here.
