### ISSUE TITLE
Room notifications look different when room list is collapsed

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9389]
### Description

The room notifications look different when the room list is collapsed vs. non-collapsed.

Collapsed room list:

![image](https://user-images.githubusercontent.com/1342360/55642531-a5e78500-57c8-11e9-8ceb-2dd39e52290b.png)

Non-collapsed room list:

![image](https://user-images.githubusercontent.com/1342360/55642556-b435a100-57c8-11e9-91d9-56f0e9987a94.png)

### Steps to reproduce

- Have some unread rooms
- Collapse the room list

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: build of riot.im/develop

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8507 rather than tracking this on its own.
