### ISSUE TITLE
recent room avatars above the room list very slowly scroll by mouse wheel

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#9394]
![1](https://user-images.githubusercontent.com/1297163/55661268-3916ce00-584e-11e9-8d26-a07979c33947.png)

Scroll by mouse is now work in last develop version of riot-web. But it is very slowly.

### Version information

For the web app:

- Firefox 66.0.2 (64bit)
- Ubuntu 16.04
- https://riot.im/develop

version riot-web: ab136c42a7fe-react-2ca281f6b7b7-js-0a82c8400696
version olm: 3.0.0

**Comment by turt2live** [comment]
Is it possible to get a gif or video of what slowly means?

**Comment by progserega** [comment]
https://yadi.sk/i/vuG6LuOXLlslFA

**Comment by progserega** [comment]
In room list scrolling by mouse is nice. It is slow only in new area "recent rooms".

**Comment by turt2live** [comment]
oh wow, that is painful.

**Comment by jryans** [comment]
https://github.com/vector-im/riot-web/issues/9400 might be a similar issue.

**Comment by turt2live** [comment]
@progserega can you try this again on the latest develop?

**Comment by progserega** [comment]
Try on https://riot.im/develop - now scroll faster x1.5, I think. But still slow.

**Comment by progserega** [comment]
At last develop breadcrumb not scrolling by mouse wheel.

**Comment by anoadragon453** [comment]
Can confirm this is still a problem for me, but only in Firefox: https://streamable.com/nfezn

Chrome is fine: https://streamable.com/hx44d
