### ISSUE TITLE
smiles not copy&paste in edit line

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#9396]
![4](https://user-images.githubusercontent.com/1297163/55661825-c27bcf80-5851-11e9-8490-31c37bd6ef33.png)

Steps to reproduce:

1. type :-) in edit window
2. type space for :-) convert to smile
3. delete space
4. press shift+left for select smile
5. press ctrl+c for copy smile
6. press ctrl+v for paste more such smiles - no reactions: smiles not paste (it is bug)
7. press space (for type space)
8. press ctrl+v - at now smile success paste

OS: Ubuntu 16.04
Firefox 66.0.2 64bit
Web-Riot: https://riot.im/develop
version riot-web: ab136c42a7fe-react-2ca281f6b7b7-js-0a82c8400696
version olm: 3.0.0

**Comment by jryans** [comment]
I would guess https://github.com/vector-im/riot-web/issues/7697 may resolve this.

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by yannicka** [comment]
I cannot duplicate the issue. Do you still have it?

I can copy&pase smiles with the mouse and the keyboard, like any character.

![Peek 21-05-2020 18-53](https://user-images.githubusercontent.com/22885898/82584158-63cbff00-9b94-11ea-91c8-4aa601d780c9.gif)

**Comment by turt2live** [comment]
We fixed this.
