### ISSUE TITLE
Breadcrumbs scroll horribly with a touchpad :(

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9400]
Related to https://github.com/vector-im/riot-web/issues/9314

You try and scroll horizontally but it only reacts to the accidental vertical component of your scroll action.

**Comment by bwindels** [comment]
wonder if this is the tooltip preventing scroll events.

**Comment by jryans** [comment]
Possibly related to https://github.com/vector-im/riot-web/issues/9394.

**Comment by turt2live** [comment]
I can't actually test this because my laptop is sub par, however I believe this would be caused by the scroll event being additive.

**Comment by turt2live** [comment]
@lampholder can you try this again on the latest develop?

**Comment by jryans** [comment]
For me, it still seems quite difficult to scroll horizontally. I guess there aren't any `wheel` properties that say "from touchpad"...? Ideally we wouldn't attempt to consider the vertical component at all from a touchpad.

**Comment by lampholder** [comment]
Yeah, I'm afraid it still feels very glitchy to me :(

**Comment by turt2live** [comment]
Can I get a video of what "glitchy" is? Without a trackpad myself it's impossible to reproduce this, so I'm hoping that a video showing the behaviour can be reverse engineered enough to solve the problem.

**Comment by bwindels** [comment]
For me, on Fedora 29, FF 66:
![breadcrumbs-scroll](https://user-images.githubusercontent.com/274386/55942286-9d150a00-5c33-11e9-92df-431eb6c4138a.gif)

First scrolling horizontally on the touchpad, which feels fast and fluid (but didn't expect to use it like this, I intuitively used vertical touchpad scrolling). then vertical touchpad scrolling, which is slower, and then scroll wheel on my mouse, which is a lot slower still.

Ideally they would all scroll at the same rate.

**Comment by bwindels** [comment]
As you don't have the hardware, I'm also happy to have a look @turt2live

**Comment by jryans** [comment]
I believe the main issue I have noticed is that with a touchpad, you could hover over the breadcrumbs and move from the center of the touchpad to the top-right corner, in an attempt to scroll right. However, since there is both motion right and up, the vertical handling counteracts the horizontal, and it just kind of shakes around:

![breadcrumb-touchpad](https://user-images.githubusercontent.com/279572/55944377-65f92580-5c40-11e9-8b59-cdf36345861a.gif)

**Comment by jryans** [comment]
It seems like it's hard to distinguish mouse wheel vs. touchpad scrolling generally... 

Maybe it would be sufficient to say if the `wheel` event contains any horizontal delta, it's probably from a touchpad-like device, so ignore the vertical component and only use the horizontal. Would that be reasonable?

**Comment by bwindels** [comment]
While testing with my touchpad, I see both deltaX and deltaY with a non-zero value, depending of how I scroll.

deltaX/Y values from the touchpad do always seem to be fractional, whereas from the mouse wheel always seem to be integers.

**Comment by jryans** [comment]
For Firefox on macOS with my MBP touchpad, the delta values are integers only.

**Comment by turt2live** [comment]
Recent changes were supposed to consider anything over a delta of 10 as horizontal only movement, but it sounds like that's too high. Maybe zero is the right answer for a threshold. 

I'll put together a quick script for people to run to see if it fixes the issue later today.

**Comment by turt2live** [comment]
turns out the script is simple:

@jryans @bwindels can you give this a try in the js console? Will need to reload after setting to pick up the changes.
```
mxSettingsStore.setValue("breadcrumb_scroll_tolerances", null, "device", {xyThreshold: 0, yReduction: 1.0});
```

**Comment by jryans** [comment]
> turns out the script is simple:
> 
> @jryans @bwindels can you give this a try in the js console? Will need to reload after setting to pick up the changes.
> 
> ```
> mxSettingsStore.setValue("breadcrumb_scroll_tolerances", null, "device", {xyThreshold: 0, yReduction: 1.0});
> ```

For me, this is almost enough. One extra bug fix is also needed: the `xyThreshold` allows any negative value to go through, so moving from center to bottom-left isn't correct yet. If I also change the code to 

```js
if (Math.abs(e.deltaX) >= xyThreshold) return;
```

then yes, the scrolling is great for me.

**Comment by bwindels** [comment]
Can't test atm without /develop
