### ISSUE TITLE
Settings layout seems broken on /develop

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9401]
Fedora 29, Chromium Version 73.0.3683.86 (Developer Build) Fedora Project (64-bit)

![image](https://user-images.githubusercontent.com/274386/55717671-5d5ae200-59e9-11e9-8a94-0d5286791f0d.png)

**Comment by jryans** [comment]
Chrome Canary (75) seems differently strange here:

![2019-04-08 at 11 35](https://user-images.githubusercontent.com/279572/55717969-774cf280-59f2-11e9-8178-0aa21366f8f2.png)

**Comment by bwindels** [comment]
related to https://github.com/matrix-org/matrix-react-sdk/pull/2868

**Comment by jryans** [comment]
It seems to affect Firefox as well.

**Comment by bwindels** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2885
