### ISSUE TITLE
Dialog boxes are overflowing

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9402]
![image](https://user-images.githubusercontent.com/1342360/55722823-42936800-59ff-11e9-812b-c74713ec9ed1.png)

![image](https://user-images.githubusercontent.com/1342360/55722841-4aeba300-59ff-11e9-8a06-54c59c1d3fa0.png)

![image](https://user-images.githubusercontent.com/1342360/55723019-bb92bf80-59ff-11e9-8af3-a259a3f1348a.png)

### Description

Dialog boxes seem to have been broken.

~~Additionally my settings got into this state, but a refresh fixed it so...?:~~ Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/2885

![image](https://user-images.githubusercontent.com/1342360/55722853-5343de00-59ff-11e9-9d95-f9ad8d285f6f.png)

Log: sent

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: build of riot.im/develop

**Comment by jryans** [comment]
A specific fix for Settings was just made in https://github.com/matrix-org/matrix-react-sdk/pull/2885, so the refresh probably pulled that in.

**Comment by jryans** [comment]
Since `.mx_Dialog` sets `max-width: 704px`, things get a bit strange when `mx_Dialog_fixedWidth` inside it sets `width: 60vw`, which may trigger scrollbars at some widths.

**Comment by anoadragon453** [comment]
Seems to be fixed in https://github.com/matrix-org/matrix-react-sdk/commit/c245eae3905c5cb9ae0d1ba9ae57c035d3068efc
