### ISSUE TITLE
Small Danish language issue: "Filter" to "Filtrér"

### ISSUE THREAD

**Issue by KristofferDannefer** [vector-im/riot-web#9407]
### Description

In the Danish version of Riot, the search field on the right under the members section says "filter", where it is supposed to say "filtrér".

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

Browser: Chrome
OS: Windows 10
URL: https://riot.im/app/#/room.org

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
Thanks for pointing it out. Our translations are actually a community effort, so if you have a spare few moments feel free to go ahead and fix it: https://github.com/vector-im/riot-web/blob/develop/docs/translating.md
