### ISSUE TITLE
Run Riot on OpenSuse

### ISSUE THREAD

**Issue by MarkSmz** [vector-im/riot-web#9414]
### Description

I'm trying to install Riot on my PC (OpenSuse Leap 15). Because there is no official Version for this distribution, I tried to install it with Flatpak, which doesn't worked (here is an link to my problem with it [https://github.com/flatpak/flatpak/issues/2802](url)). 
So I tried to build it my self, I've never done this before, so i have no experience with it. I followed the steps give here [https://github.com/vector-im/riot-web#running-as-a-desktop-app](url). I'm not sure what to do at point 7., but if I got that right, I don't have to do anything about it. Right? I followed the next steps, and ended up with point 2 (from Running as Desktop app). I have to Install and run electron, but but when entering `yarn electron` I got this error:
`mark@Marks-PC:~/riot-web> yarn electron
yarn run v1.15.2
$ yarn install:electron && electron .
$ install-app-deps
  • please use as subcommand: electron-builder install-app-deps
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/home/mark/riot-web/electron_app
/bin/sh: electron: Kommando nicht gefunden.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Can someone tell me whats wrong?
### Version information

- **Platform**:  Desktop

For the desktop app:

- **OS**: OpenSuse Leap 15
- **Version**: 1.0.7

**Comment by t3chguy** [comment]
Install electron
E.g "npm i -g electron"

**Comment by MarkSmz** [comment]
> Install electron
> E.g "npm i -g electron"

I have installed electron with yarn (`yarn add electron` and `yarn electron-builder install-app-deps`)
Or is that wrong?

Is it right, that I cant install Riot on OpenSuse, only run it with Yarn?
And if so is it possible to build an rpm of it, because I can build an deb by using this command: `node_modules/.bin/build -l --x64`

**Comment by jryans** [comment]
I think discussing this interactively in the #riot-web:matrix.org room would be more useful. This isn't a good place for support questions.

**Comment by MarkSmz** [comment]
Sorry I'm only writing again now. Unfortunately I don't have time for it at the moment, but thanks for help and the offer. When I have time again I will come back and give it a try. I'll probably just install Riot over Flatpak now.
