### ISSUE TITLE
Security concern regarding sharing files

### ISSUE THREAD

**Issue by JasonGitly** [vector-im/riot-web#9417]
### Description

**Background info:** I'm using Riot to share sensitive files. When the recipient of a file clicks on the download link on their desktop version of Riot, the direct download link automatically opens up in the default web browser installed on the computer.

**Problem:** The download link can be stored in the history of the web browser. Even if the recipient logs out of their Riot account, anyone or any program/extension with access to the history of their default web browser can download all the [sensitive] files without any authentication.

**Suggestion:** At the very least Riot can use "Open in a web browser" instead of "Download" as the text of the download link or notify the user that if they proceed the link would be opened in their default web browser (of course, a much more convenient solution would be to download the shared files without having to open their links in a web browser).

### Steps to reproduce

- Share a zip file with yourself
- Click on the download link of that file on the desktop version of Riot

**Unexpected behavior:** The file will not be downloaded from Riot. Instead the direct download link will be sent to the default web browser installed on the computer.

### Version information

- **Platform**: Desktop
- **OS**: Windows 10 64bit
- **Version**: 1.0.6

**Comment by turt2live** [comment]
This is actually a server-side concern (see https://github.com/matrix-org/synapse/issues/2150), although definitely a problem. There are some proposals in the works to fix this which reference that issue.

We already try and set all the necessary flags for browsers to try and download the file, however browsers employ additional restrictions which mean that this doesn't always work. There is some opportunity for us to work around the problem, however I'm not entirely sure what the benefit would be in this case besides increased memory usage of the app.
