### ISSUE TITLE
[Support | Issue] Riot-web cannot connect to Matrix Synapse on localhost (Windows WSL Ubuntu 18.04)

### ISSUE THREAD

**Issue by menturion** [vector-im/riot-web#9420]
### Description & Steps to reproduce ###

I am trying to set up a dev environment on a locall Windows 10 machine using the Ubuntu18.04 WSL.

The latest version of Matrix Synapse seems to run fine. Entering URL "http://localhost:8008" prompts the following message (s. attached screenshot) after being forwarded to "http://localhost:8008/_matrix/static/" ...

![2019-04-10_121555](https://user-images.githubusercontent.com/41576848/55871589-4227d800-5b8b-11e9-8617-2c407a040da9.jpg)

Then I downloaded the latest prebuilt version of Riot-web ("riot-v1.0.7.tar.gz", https://github.com/vector-im/riot-web/releases/download/v1.0.7/riot-v1.0.7.tar.gz) and unpacked it within the "htdocs" root folder of a XAMPP installation.

I changed server entries within the Riot "config.json" file to "localhost", leaving the identy server entry blank. 

### Result ###

A white blank page is shown in the browser and the following errors are displayed in the console of FF resp. Chrome when visiting the Riot-web URL.

#### Firefox ####

![2019-04-10_122832](https://user-images.githubusercontent.com/41576848/55872675-dbf08480-5b8d-11e9-8baf-dbcdc57c6699.jpg)

```
Starting watcher for RoomList.orderByImportance@<null room> rageshake.js:107
Starting watcher for feature_custom_tags@<null room> rageshake.js:107
wasm streaming compile failed: TypeError: Response has unsupported MIME type rageshake.js:107
falling back to ArrayBuffer instantiation rageshake.js:107
Initialised rageshake. rageshake.js:107
To fix line numbers in Chrome: Meatball menu → Settings → Blackboxing → Add /rageshake\.js$ rageshake.js:107
Using WebAssembly Olm rageshake.js:107
set language to de rageshake.js:107
Using Web platform rageshake.js:107
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Weitere Informationen] getconfig.js:61:24
    u getconfig.js:61
    onreadystatechange index.js:294
    onreadystatechange index.js:281
```

#### Chrome ####

![2019-04-10_124020](https://user-images.githubusercontent.com/41576848/55872706-ee6abe00-5b8d-11e9-8d4f-80b878cb60a5.jpg)

```
Starting watcher for RoomList.orderByImportance@<null room>
rageshake.js:107 Starting watcher for feature_custom_tags@<null room>
rageshake.js:107 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
e.(anonymous function) @ rageshake.js:107
rageshake.js:107 falling back to ArrayBuffer instantiation
e.(anonymous function) @ rageshake.js:107
rageshake.js:107 Initialised rageshake.
rageshake.js:107 To fix line numbers in Chrome: Meatball menu → Settings → Blackboxing → Add /rageshake\.js$
rageshake.js:107 Using WebAssembly Olm
rageshake.js:107 set language to de
rageshake.js:107 Using Web platform
(index):1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.callback (getconfig.js:61)
    at index.js:294
    at XMLHttpRequest.o.onreadystatechange (index.js:244)
```

Altering any settings of e.g. the server entries within the Riot "config.json" file seems to have no effect.

### Question ###

Have I done anything wrong or is this a bug?

**Comment by Half-Shot** [comment]
Can you include your config.json?

**Comment by menturion** [comment]
I started with the default config, replacing only this ...
```
    "default_hs_url": "https://matrix.org",
    "default_is_url": "https://vector.im",
```
with this ...
```
    "default_hs_url": "http://localhost",
    "default_is_url": "",
```
and ended up with the following config ...
```
{
    "default_hs_url": "http://localhost",
    "default_is_url": "",
    "disable_custom_urls": false,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": true,
    "brand": "Riot",
    "integrations_ui_url": "",
    "integrations_rest_url": "",
    "integrations_jitsi_widget_url": "",
    "bug_report_endpoint_url": "",
    "features": {
        "feature_groups": "labs",
        "feature_pinning": "labs"
    },
    "default_federate": true,
    "default_theme": "light",
    "roomDirectory": {
        "servers": [
            "localhost"
        ]
    },
    "welcomeUserId": "@riot-bot:localhost",
    "enable_presence_by_hs_url": {
        "http://localhost": false
    }
}
```

... with many permutations in between. None of the many configurations led to a successful connection.

**Comment by t3chguy** [comment]
You're missing the port though: `http://localhost:8008` (or 8448 with https)

**Comment by menturion** [comment]
I just changed the config by adding the port like this ...

`"default_hs_url": "http://localhost:8008",`

... with ths same result (s. attached screenshot).

![2019-04-10_170613](https://user-images.githubusercontent.com/41576848/55890518-1caec480-5bb3-11e9-8a8d-5e2c8d65fd8c.jpg)

Do I also have to add the port number ("8008") to other settings in the configuration?

**Comment by turt2live** [comment]
That error can also mean that something else is going wrong - in the network tab, look for the red failed request and see what it is.

**Comment by menturion** [comment]
Just checked it.
The waterfall diagram looks ok to me. Any idea?

![2019-04-10_192332](https://user-images.githubusercontent.com/41576848/55900039-9308f200-5bc6-11e9-8c4b-dcdded47be19.jpg)

**Comment by turt2live** [comment]
What's the response for the config.localhost.json call?

**Comment by menturion** [comment]
In the second last line, HTTP/1.1 200 ok.

**Comment by menturion** [comment]
I moved the code into the root of a fresh new XAMPP installation and it worked now. 
Have to check what might have caused this issue.

Issue can be closed. Many thanks for your replies and ideas!

**Comment by turt2live** [comment]
The response body will be the interesting part. If Riot gets a 200 OK, it will think it is a valid config. Chances are the webserver is sending an HTML error page with something like access denied (file permission problem) or not found (but missing the 404 status code). If riot gets an error code, it'll try a request to just `/config.json` which is probably what you want.

**Comment by jryans** [comment]
Closing by request of the issue creator.

**Comment by menturion** [comment]
@turt2live 
It was an old rewrite rule that intercepted the requests.
Disabling this rule for the Riot-web subfolder solved this issue.
