### ISSUE TITLE
Room join preview is extremely bland for joining via the room directory.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9427]
![image](https://user-images.githubusercontent.com/2072976/55919974-e93e5b00-5bef-11e9-8f6b-fdc23d83a862.png)

It literally shows a room name and nothing else, meanwhile `/publicRooms` gives us [all this information](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-publicrooms).

It would surely be easy to pass this info into the join room code, and make everything prettier. At minimum show the room alias, since it would be a nice reassurance to know I am going to the right place.

(This won't affect joins via alias directly, because we lack the API to do a /publicRooms/#myalias:foobar which is very sad)

**Comment by turt2live** [comment]
The designs for https://github.com/vector-im/riot-web/issues/7576 appear to cover this, I think.
