### ISSUE TITLE
"Click here to join discussion" is a hyperlink and not a button in the join room dialog

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9428]
It's a small thing, but it just looks a bit meh against our shiny buttons elsewhere. I'd consider this more important than the other occurrences of hyperlinked text only because I join rooms frequently :)

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/7576

**Comment by Half-Shot** [comment]
This got done.
