### ISSUE TITLE
password change shouldn't warn you to export keys if you have online backup running

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9432]

**Comment by turt2live** [comment]
might want to also encourage you to set up key backup if you haven't already first

**Comment by matthijskooijman** [comment]
AFAIU, the warning would only be unneeded if *all* your devices have online backup running, right? If any device is not running this and has some keys that are not present on other devices that *do* have backup running (or is this impossible?), logging them out could destroy those keys?

**Comment by jryans** [comment]
> AFAIU, the warning would only be unneeded if _all_ your devices have online backup running, right? If any device is not running this and has some keys that are not present on other devices that _do_ have backup running (or is this impossible?), logging them out could destroy those keys?

Yes, that's correct, some keys can be lost if they are only known to devices that don't participate in key backup, so there's so nuance involved in updating the message here.

**Comment by lampholder** [comment]
@dbkr is it possible to compare the device list with the encrypted backup to establish whether there are devices that would risk losing their keys if you did a password reset?

**Comment by aaronraimist** [comment]
Related #9037

**Comment by uhoreg** [comment]
I think this can be closed in favour of https://github.com/vector-im/riot-web/issues/9037
