### ISSUE TITLE
Images are completely broken

### ISSUE THREAD

**Issue by adalvigi** [vector-im/riot-web#9440]
From after the maintaining that logged users off, me and other users can't upload or view any image file. Already present images can't be seen, and upload of new ones hangs infinitely. 

There are also some issues with key backups, but they're off topic. I couldn't recover any key despite the key backup being enabled.

**Comment by exuvo** [comment]
From https://twitter.com/matrixdotorg 18h hours ago

> The new http://matrix.org  homeserver is online as of about an hour ago (other than the media repository, which is still recovering). Other services will return tomorrow.

**Comment by jryans** [comment]
Images now appear to be working on the matrix.org HS.
