### ISSUE TITLE
E2E key backup: Unable to load key backup status

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9442]
![image](https://user-images.githubusercontent.com/1922197/56037568-818b2b80-5d27-11e9-8596-44cab76f0d63.png)

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/56040329-11cc6f00-5d2e-11e9-829f-1c1913915d9f.png)

No problem accessing the same key backup from Riot Android

**Comment by jryans** [comment]
@lampholder Do you happen to be on /app or /develop? Ben saw this on /develop, but then it worked on /app. (You can open a separate tab to check without losing /develop since it's not deployed at the moment.)

**Comment by lampholder** [comment]
Hmm, I've been on /develop, and I'm currently on a random build - /me tries /app

**Comment by jryans** [comment]
I suspect the factoring out in https://github.com/matrix-org/matrix-react-sdk/commit/0f1ebf8095b52b23f694c43721159c65592ad15f from https://github.com/matrix-org/matrix-react-sdk/pull/2899 introduced this ~3 days ago.
