### ISSUE TITLE
Update on desktop version fails in Ubuntu

### ISSUE THREAD

**Issue by arjunkrishnababu96** [vector-im/riot-web#9447]
### Description

Unable to update the app via `sudo apt update`. I've been using Riot for over a month without issues, and have been running the system update command almost daily -- this issue showed up only today.

### Steps to reproduce

From a machine running Ubuntu 18.04 LTS,

1. Open terminal
2. Run `sudo apt update`

Describe how what happens differs from what you expected.

The following error message shows up about Riot. (FWIW, other programs on my computer update without any issues, so it's only Riot that is problematic).

> Err:10 https://riot.im/packages/debian bionic Release                                                                                                
  404  Not Found [IP: 104.25.36.105 443]

> E: The repository 'https://riot.im/packages/debian bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

(Output not relevant to Riot has been omitted).

Log: not sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 18.04 LTS

**Comment by turt2live** [comment]
This is because of https://matrix.org/blog/2019/04/11/security-incident/ - please watch https://twitter.com/matrixdotorg for updates on the situation.
