### ISSUE TITLE
MatrixClient is not stopped when the token no longer works

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9451]
This results in us hitting `/versions`, `/pushrules`, and `/sync` with no success because the token doesn't work. `/pushrules` is called on a loop to try and get them, which invokes calls on `/versions`. `/sync` just happens.

We should stop the MatrixClient when we know there's no hope in syncing.

**Comment by turt2live** [comment]
This also affects people's ability to log in. They'll get "Unable to connect to homeserver" because the /pushrules is 429ing. We do not back off when we receive a 429, but we should.

**Comment by shirishag75** [comment]
I saw the same thing.  I guess the only sane thing remaining is to just read matrix's twitter handle and when things are a bit more saner try again. Although I won't be till downloads and **esp**. package repos. are not back.

**Comment by turt2live** [comment]
As a bit more information: The client has to be offline when the token is deactivated. If the client is online, it stops making requests.

So to reproduce:
1. Log in
2. Delete your access token from the synapse database
3. Close riot
4. Restart synapse
5. Open riot
