### ISSUE TITLE
Gitter Bridge not working - Integration Errors

### ISSUE THREAD

**Issue by shreyasbapat** [vector-im/riot-web#9452]
### Description
We have a matrix channel bridged to a gitter room. But after the downtime, our integration is no longer working. 

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

I can't open the integrations page .

![Screenshot from 2019-04-13 16-08-03](https://user-images.githubusercontent.com/24257914/56078495-63e0c380-5e06-11e9-96b7-4d2b2e828664.png)

### Version information

- **Platform**: web (in-browser) or desktop?
Web
For the web app:

- **Browser**: Google Chrome 73.0.3683.103 
- **OS**:  Ubuntu 19.04
- **URL**: https://riot.im/app/#/room/#einsteinpy:matrix.org

**Comment by turt2live** [comment]
See https://twitter.com/RiotChat/status/1117110823023984640

**Comment by shirishag75** [comment]
Same here 
![riot-some-integration-error-still](https://user-images.githubusercontent.com/727626/56184886-4c265c80-600b-11e9-8849-7a019aa08947.png)

**Comment by shreyasbapat** [comment]
Still, the integration hasn't started to work :/
