### ISSUE TITLE
Unable to download the desktop version / Autoupdate doesn't work

### ISSUE THREAD

**Issue by Raj2032** [vector-im/riot-web#9453]
![image](https://user-images.githubusercontent.com/29293830/56080138-7bd53900-5e40-11e9-8936-3a6fb39b2b92.png)

On hte riot website, I click on this icon and it shows me this.

![image](https://user-images.githubusercontent.com/29293830/56080143-90193600-5e40-11e9-8d8a-909482f18807.png)

Any idea how do I get the desktop version?

**Comment by turt2live** [comment]
This is due to https://twitter.com/RiotChat/status/1117110823023984640 - we are working on getting the downloads page back up and running, although there's a lot of work to be done.

**Comment by shirishag75** [comment]
I am guessing both downloads and repository issues will be resolved once the packages are rebuilt and signed with new keys. There probably will also need to add instructions as to how remove old keys from Debian/Ubuntu keychain/keyring and put new ones in. Once the work and the documentation is completed and published, could this be marked as done perhaps.

**Comment by Raj2032** [comment]
@shirishag75 Is it also available for Windows?

**Comment by shirishag75** [comment]
I *think* so but cannot be sure as most links don't work and anyways I'm a linux user so not really interested in that platform. Although I would expect them to have it also for MS-Windows.

**Comment by Raj2032** [comment]
I use Windows and Linux but most of my friends use Windows so I need a
Windows compatibility version for them.

**Comment by turt2live** [comment]
Windows desktop builds are supported by Riot. The download page is just offline at the moment.

**Comment by Raj2032** [comment]
Oh ok that is good to know.

**Comment by shirishag75** [comment]
I am guessing either a new build or the same build but a different gpg key is in works. Looking forward to see the new build or/and new set of keys :)

**Comment by redtux** [comment]
Hi! Thank you for your good work. Could you please provide a brief explanation on what has happened directly at https://riot.im/download/desktop and at https://riot.im/packages/debian etc. with a link to https://matrix.org/blog/2019/04/11/security-incident/ (and maybe also to this issue) instead of leaving us users in the dark with an http status 404 error? This would be great! :+1:

**Comment by Raj2032** [comment]
No worries

**Comment by shirishag75** [comment]
> Hi! Thank you for your good work. Could you please provide a brief explanation on what has happened directly at https://riot.im/download/desktop and at https://riot.im/packages/debian etc. with a link to https://matrix.org/blog/2019/04/11/security-incident/ (and maybe also to this issue) instead of leaving us users in the dark with an http status 404 error? This would be great! +1

While I'm just a user like you, allow me to share some of the things I am guessing they will be doing. 

First see https://github.com/vector-im/riot-web/issues/9441#issuecomment-483186170 . That comment in itself tells a lot. In essence, what happened was that a [greyhat](https://en.wikipedia.org/wiki/Grey_hat ) was able to compromise lot of riot infrastructure. One of the things which was compromised were the GPG

**Comment by turt2live** [comment]
https://riot.im/download/desktop/ has new downloads available for 1.0.8 (freshly signed packages). Making the update button / autoupdate stuff work is coming up next.

**Comment by Raj2032** [comment]
THanks for the link :)

**Comment by BloodyIron** [comment]
Still getting GPG key issues with the PPA, I'm not really finding the steps people are need to take that were previously using the PPA before the breach. Seems like a bit of a shortcoming to know which steps to follow that are trusted.

Please advise.

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/6470#issuecomment-483695491 might give some hints, although tbh I'm not sure about this universe.

**Comment by shirishag75** [comment]
> Still getting GPG key issues with the PPA, I'm not really finding the steps people are need to take that were previously using the PPA before the breach. Seems like a bit of a shortcoming to know which steps to follow that are trusted.
> 
> Please advise.

@BloodyIron what issues are you getting at using instructions at https://riot.im/download/desktop/ ?

Debian / Ubuntu repo:
This is a fresh package repository with a fresh public key: if you have the existing riot.im/packages repository, you should move to the new repository and add the new key

   

>  Add the repository ("bionic" is codename for 18.04, use the appropriate codename depending on your distribution):
>     sudo sh -c "echo 'deb https://packages.riot.im/debian/ bionic main' > /etc/apt/sources.list.d/matrix-riot-im.list"
>     Add the public key:
>     curl -L https://packages.riot.im/debian/repo-key.asc | sudo apt-key add -
>     Update and install Riot:
>     sudo apt-get update && sudo apt-get -y install riot-web
>

**Comment by aaronraimist** [comment]
This should be fixed now right?

**Comment by turt2live** [comment]
seems like it
