### ISSUE TITLE
CORS error when adding sticker packs to self-hosted Riot

### ISSUE THREAD

**Issue by lnicola** [vector-im/riot-web#9454]
### Description

Adding a sticker pack to a self-hosted Riot throws a CORS error for https://scalar.vector.im/api/register?v=1.1.

### Steps to reproduce

- install self-hosted Synapse and Riot
- log in
- try to add a sticker pack

Log: not sent

![image](https://user-images.githubusercontent.com/308347/56081224-96dd8400-5e13-11e9-9d41-5f8c4a5b4c64.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Arch Linux
- **URL**: self-hosted Riot 1.0.7-1

**Comment by turt2live** [comment]
See https://twitter.com/RiotChat/status/1117110823023984640
