### ISSUE TITLE
 "Registration disabled on this homeserver"

### ISSUE THREAD

**Issue by bradleyreid** [vector-im/riot-web#9455]
### Description

Cannot register with riot, I get a red error message: "Registration disabled on this homeserver"

### Steps to reproduce

I try to register for Riot.IM by launching the web browser or via android app
For web browser:
-Launch riot.im web version
-Select "create account"
-"Registration has been disabled on this homeserver" is displayed

For android app:
-Launch app
--Select "create account"
-"Registration has been disabled" is displayed

I would expect to be able to register, I have tried this while signed on to multiple wireless networks with the same response. Sorry if this is not the best channel for this, but unfortunately I cannot learn much more as almost all of the "help" for riot is in riot chats that I cannot access! 

Log: not sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 66.0.3
- **OS**: Manjaro 18.0.4, Android 7.0
- **URL**: riot.im/app

**Comment by turt2live** [comment]
This is because of https://twitter.com/matrixdotorg/status/1117118688233250817 - it should be enabled again as soon as it possibly can be.

Note: it also only affects matrix.org - using your own homeserver should not be affected.

**Comment by turt2live** [comment]
matrix.org has now turned on registrations again. If you continue to have problems, come by #riot:matrix.org on Matrix.
