### ISSUE TITLE
Shift-Delete doesn't copy to clipboard

### ISSUE THREAD

**Issue by lnicola** [vector-im/riot-web#9461]
### Description

Shift-Delete should traditionally cut the text, putting it into the clipboard, same as Ctrl-X / Cmd-X. Ctrl-X works fine.

### Steps to reproduce

- type some text, copy it to clipboard, delete it
- type something else, select it, cut with Shift-Del
- paste

Log: not sent

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Arch Linux
- **URL**: self-hosted, `0.99.2-3`

**Comment by jryans** [comment]
@lnicola Where are you typing? In the message composer?

**Comment by lnicola** [comment]
@jryans In this pane:

![image](https://user-images.githubusercontent.com/308347/56131381-ecd73680-5f8f-11e9-966f-57a17a901ced.png)

**Comment by jryans** [comment]
Thanks! My guess is that this is another variant of https://github.com/vector-im/riot-web/issues/7665 and will be fixed by https://github.com/vector-im/riot-web/issues/7697.

**Comment by lnicola** [comment]
I'm confused. That sounds like a workaround, not a fix. Can't the existing editor handle Shift-Del just like it handles Ctrl-X?

**Comment by t3chguy** [comment]
@lnicola could you try it here: https://www.slatejs.org/#/rich-text

If it doesn't work there then it is an issue upstream in the composer we use (slatejs) and not something we can work around without implementing something like #7697

**Comment by lnicola** [comment]
Yeah, I just tried it, and it doesn't work. It's an upstream bug.

**Comment by lnicola** [comment]
Filed https://github.com/ianstormtaylor/slate/issues/2694.

**Comment by lampholder** [comment]
related: https://github.com/vector-im/riot-web/issues/6531

**Comment by lnicola** [comment]
Fixed in the new composer (`1.5.0`?).
