### ISSUE TITLE
not able to retirve the account.

### ISSUE THREAD

**Issue by aj07** [vector-im/riot-web#9463]
Suddenly, I was logout from the riot browser and unfortunately I didn't remember the password but I have key. 

When, I tried to relogin the system by doing forgot password link. It giving error"email address not found"  
![Screenshot from 2019-04-14 17-12-05](https://user-images.githubusercontent.com/9623159/56090730-880cd500-5ed8-11e9-8531-345e8e3d25ce.png)
![Uploading Screenshot from 2019-04-14 17-12-18.png…]()

**Comment by lampholder** [comment]
Hi, sorry about this - would you be happy to email me the email address and matrix id you were using to connect and I'll take a look? My email is tom@matrix.org

**Comment by lampholder** [comment]
l

**Comment by aj07** [comment]
Done @lampholder

**Comment by michaelnew** [comment]
What was the resolution here? A friend (who is not terribly tech-savvy) is having the same issue and I'm not sure what to tell her.

**Comment by jryans** [comment]
> What was the resolution here? A friend (who is not terribly tech-savvy) is having the same issue and I'm not sure what to tell her.

Assuming your friend uses the matrix.org HS, I would encourage them to mail support@matrix.org about this.
