### ISSUE TITLE
Debian Repository no longer available

### ISSUE THREAD

**Issue by benhartwich** [vector-im/riot-web#9465]
Hi,

the debian repository is no longer available. Will it be available again? I can´t find any infos.

"The repository 'https://riot.im/packages/debian stretch Release' does no longer have a Release file."

Thanks and regards,

**Comment by seth100** [comment]
yes and the desktop page is 404: https://riot.im/download/desktop

**Comment by benhartwich** [comment]
Why was this closed? Is there any comment regarding this?

**Comment by turt2live** [comment]
Github ate my comment, sorry :(

Duplicate of https://github.com/vector-im/riot-web/issues/9453
