### ISSUE TITLE
Invite ordering is broken

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9468]
Rather than invites being listed in chronological order, they seem to be a weird mix of either new invite being prepended to the list, or appended to the list.

**Comment by turt2live** [comment]
A rageshake might be interesting for this to see if it's the room sorting algorithm getting in the way

**Comment by lampholder** [comment]
Perhaps related: https://github.com/vector-im/riot-web/issues/9588

**Comment by turt2live** [comment]
fixed in the new room list
