### ISSUE TITLE
How do I prevent others from seeing that I have read the message?

### ISSUE THREAD

**Issue by Raj2032** [vector-im/riot-web#9470]
Any idea on any version (for Android, iOS, Windows etc) how to disable for others to see that you have read the message?

**Comment by turt2live** [comment]
It's not currently possible. See https://github.com/vector-im/riot-web/issues/2527

**Comment by Raj2032** [comment]
Is it going to be implemented though?

**Comment by turt2live** [comment]
yes, but requires some non-trivial changes in order to accomplish it.

**Comment by Raj2032** [comment]
Oh ok that is good to know. Additionally I wanted to know I hope it is not like if the user disables this feature, then the user can't view others if their message(s) have been read or not?

**Comment by turt2live** [comment]
We'd probably split the two options apart
