### ISSUE TITLE
Unable to load Riot.im/app because of an CSP error

### ISSUE THREAD

**Issue by dannycolin** [vector-im/riot-web#9471]
### Description

Got stuck in an infinite load loop when I try to open the riot web app.

Error message from the developer console : 

```
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.
Content Security Policy: The page’s settings blocked the loading of a resource at https://riot.im/app/bundles/ffb4fa6e8a9bd1bedd9a/indexeddb-worker.js (“worker-src”).
XML Parsing Error: syntax error
Location: https://riot.im/app/version?cachebuster=1555286370964
Line Number 1, Column 1:
```
### Steps to reproduce

- go to `https://riot.im/app` URL

Describe how what happens differs from what you expected : 

The app should load :).

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser)
For the web app:

- **Browser**: Firefox 68
- **OS**: Debian 9
- **URL**: riot.im/app

**Comment by turt2live** [comment]
This sounds a lot like an extension or browser setting interfering - we don't have that strict of a CSP on the app, and it loads fine for me in Chrome/Firefox.

**Comment by jryans** [comment]
@dannycolin What add-ons do you have installed in Firefox?

**Comment by dannycolin** [comment]
@jryans I use UMatrix, Ublock, Privacy Badger and HTTPS Everywhere but I've also tried in *safe mode* and I have the same issue.

**Comment by jryans** [comment]
@dannycolin Can you try with fresh Firefox profile perhaps? You can create one in about:profiles, for example.

Something is injecting a CSP onto the page since it's not part of the app itself at the moment. It's either an add-on, proxy, or something like that.

**Comment by dannycolin** [comment]
@jryans I've tested a fresh profile and also a fresh profile were I've reproduce the exact settings in about:preferences I have in my regular profile. In both cases, riot.im/app loaded successfully.

I'm guessing something in about:config must be interfering with Riot but I have no clue what could cause that. I'll have to investigate more. If you have any idea, let me know.

**Comment by jryans** [comment]
I am not sure off-hand, but you could try bisecting your user prefs in the `prefs.js` file your profile to find out:

1. Quit Firefox
2. Edit `prefs.js` to only contain the first half
3. Start Firefox, see if issue happens
4. Continue subdividing by half until you the find the pref responsible

Closing since it's not a Riot issue.

**Comment by dannycolin** [comment]
@jryans thanks for the tip! It solved my issue :).

**Comment by jryans** [comment]
@dannycolin Aha, great to hear! What was the problem pref in the end?

**Comment by dannycolin** [comment]
@jryans hard to say because Firefox updated more than one value in prefs.js. It resetted some addons configs. I suspect UMatrix was responsible for the problem because now it detects a matrix.org request when I load riot.im/app.
