### ISSUE TITLE
Restore PPA for desktop client

### ISSUE THREAD

**Issue by dejIO** [vector-im/riot-web#9474]
Posting here for visibility, please kindly point me to the right direction.

Right now, if someone wants to download the Riot desktop client, [they get a 404.](http://web.archive.org/web/20190415070541/https://riot.im/download/desktop)

This makes adoption of new users unnecessarily difficult (some people still like desktop clients).

That is all.

**Comment by jryans** [comment]
Thanks for the report! I believe https://github.com/vector-im/riot-web/issues/9453 covers this problem with a wider scope (all desktop platforms), so let's use that issue to track.
