### ISSUE TITLE
Reactions: Add emoji picker as a message action

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9483]
<img width="1101" alt="Screenshot 2019-05-17 at 13 56 14" src="https://user-images.githubusercontent.com/4626865/57930674-8145f900-78ae-11e9-8cf9-9418669ed56d.png">

Currently we're thinking we'll use https://github.com/missive/emoji-mart.

To open the emoji picker:

- Clicking (🙂+) reveals the emoji picker
- Clicking 'View all' reveals the emoji picker

**Comment by turt2live** [comment]
Would be great if it was added in such a way where https://github.com/matrix-org/matrix-doc/pull/1959 could be supported in future.

Note from the proposal:
> Although this proposal does not include an emoji picker definition, the API it proposes can easily and transparently be extended to such a widget.

**Comment by jryans** [comment]
> Would be great if it was added in such a way where [matrix-org/matrix-doc#1959](https://github.com/matrix-org/matrix-doc/pull/1959) could be supported in future.

As fas as I can see, we should be able to the extend the picker component with custom data sets to achieve this. It may take some amount of customising / forking to do so, but I think that's acceptable.

**Comment by PopeRigby** [comment]
It would probably be a good idea to have the emoji picker in the right-click menu as well.
