### ISSUE TITLE
API support for aggregations

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9485]
We'll need API support for aggregations (to support message editing and reactions). This will likely be broken down into sub-tasks in React and JS SDKs once the shape of the API is known in more detail.

For the moment, https://github.com/matrix-org/matrix-doc/pull/1849 gives some idea of the direction here.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2392)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/111)
