### ISSUE TITLE
Reactions: Increment existing reaction type on click

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9486]
When you click one of the existing reaction types displayed below a message, increment that type and highlight it.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/116)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2397)
