### ISSUE TITLE
Message Editing: Editing in the timeline

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9487]
This includes the UX to enter edit mode, show the editing composer (https://github.com/vector-im/riot-web/issues/9481).

Sending the edit is tracked separately (https://github.com/vector-im/riot-web/issues/9575), so this could local edit only at first.

- [x] switch to editor upon clicking edit in action bar
- [x] render pills
- [x] add auto-completion for pills
 - [x] enter to save, shift enter to newline
 - [x] only allow editing events of type=m.room.message and msgtype=m.text
 - [x] \(edited) annotation
 - [x] implement design, dark theme
 - [x] add avatars to pills
- [x] make pillifying, link previewing update on edit
 - [x] test locally with eriks flag enabled server support locally and see that we don't display the fallback content when the server already aggregated/replaced the event while back-paginating.
 - [x] parse html to markdown (easy)
 - [x] re-apply markdown (easy-ish, can copy-paste code from `MessageComposerInput::handleReturn` probably) Pills should be markdown links and then ran through the markdown parser.
 - [x] tab completion

**Comment by bwindels** [comment]
Tracking undo support for new composer in https://github.com/vector-im/riot-web/issues/9831 as this issue has been in progress forever already.
