### ISSUE TITLE
Message Editing: Annotate edited messages in timeline

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9489]
Edited messages will be annotated in the timeline to show that they have been edited.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2400)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/120)

**Comment by bwindels** [comment]
might need to look into m.relations for events that the server already aggregated/replaced while paginating back to detect this, as well as checking for makeReplaced having been called.
