### ISSUE TITLE
Message Editing: View edit history

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9490]
For an edited message, we should add an edit history dialog (probably accessed by the ["edited" annotation](https://github.com/vector-im/riot-web/issues/9489)) which shows all edits of the message.
 - [x] implement basic dialog
 - [x] fetch and show history 
 - [x] date separators
 - [x] make pillifying work
 - [x] handle emotes correctly
 - [x] do pagination (on scroll)
 - [x] order messages descending
 - [x] style both `m.text` and `org.matrix.custom.html` the same
 - [x] try not to duplicate styles between event tile and history item too much
 - [x] make it work in e2e rooms
 - [x] minor style tweaks to align fully with design

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/121)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2401)

**Comment by bwindels** [comment]
We'll be using `/_matrix/client/r0/rooms/{roomID}/relations/{eventID}/m.replace/m.room.message` to paginate through edits.

**Comment by bwindels** [comment]
actually, messages in the dialog look pretty well aligned with both existing timeline and design of the dialog. Checking the last checkbox for minor design tweaks.
