### ISSUE TITLE
Message Editing: Display edits as diffs

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9493]
We'd like to display [edit history](https://github.com/vector-im/riot-web/issues/9490) as a diff to make it obvious what was added / removed / changed.

However, we should only do this if we can be absolutely certain that we know the immediate predecessor of an edit without gaps, etc.

 - [x] diff text messages
 - [x] diff html messages

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/123)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2403)

**Comment by bwindels** [comment]
Consider using https://github.com/google/diff-match-patch , as riotx does
