### ISSUE TITLE
Etherpad error messages unreadable with black theme

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#9504]
Messages (such as '500 Internal Server Error An internal server error occurred.') are basically black on black.

Sorry, no pic - the etherpads are back, so the error doesn't occur anymore.

**Comment by turt2live** [comment]
I'm not sure how much value there is in fixing this - typically people only see the "Forbidden" version of this, and it's just an iframe. The widget should really be sending a proper error page or the browser should be rendering it more appropriately.

**Comment by turt2live** [comment]
This is a Scalar issue.
