### ISSUE TITLE
Password reset email doesn't mention password reset

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#9508]
When you reset your password, you get an email saying "You have asked us to register this email address with riot.im" rather than "you have already registered this email address with riot.im and now you have requested a password reset".

**Comment by richvdh** [comment]
seems to be a duplicate of https://github.com/vector-im/riot-web/issues/2761 ftr. I'll leave this open though so that the riot team can re-triage appropriately

**Comment by turt2live** [comment]
ah yes, I thought there was a duplicate but couldn't find it. It's already at the highest priority we can give it though, and it doesn't qualify for fire status imo :(
