### ISSUE TITLE
URLs on riot.im - Error 404 Not Found

### ISSUE THREAD

**Issue by ukcb** [vector-im/riot-web#9511]
I miss a few pages on https://riot.im/

* https://riot.im/privacy
* https://riot.im/tac
* https://riot.im/copyright

**Comment by turt2live** [comment]
This is due to https://twitter.com/matrixdotorg/status/1116304867683905537 and the rest of that thread. It looks like the team has already been asked for it to be restored, however I'll ask again.

**Comment by preemeijer** [comment]
Hello,

Also the following url is not working: https://translate.riot.im found on the following page https://github.com/vector-im/riot-web/blob/master/docs/translating.md

And when you go to the following page https://translate.riot.im/accounts/profile/ (redirects to https://matrix.orgaccounts/profile/) there is a warning of a potential security risk using Firefox.

Cheers, Paul

**Comment by jryans** [comment]
Moved the translate.riot.im portion to https://github.com/vector-im/riot-web/issues/9585.

The privacy, etc. URLs in the original issue are now working.
