### ISSUE TITLE
Send extra parameter in send message

### ISSUE THREAD

**Issue by hassanAwanAlvi** [vector-im/riot-web#9521]
Hi, I am using RIOT web. I want to send an extra parameter ("is_allowed" : true) into the message body. 
Please tell me in which class should I change it. I am a beginner and I can't find it. Thanks.

**Comment by jryans** [comment]
Issues aren't the best place for this type of question. I would suggest joining #riot-web:matrix.org to ask about this, and we may redirect you as needed.
