### ISSUE TITLE
Mismatched branches on a riot-web PR don't cause build failure

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9522]
In a case of a riot-web PR which is backed up by react-sdk changes, we should fail to build the riot-web PR if the branches don't match. Instead, we get green checkmarks across the board even though the changes needed cannot be found.

**Comment by jryans** [comment]
How would CI detect the case of "riot-web PR which is backed up by react-sdk changes" when the matching branches don't exist?

**Comment by turt2live** [comment]
When there's code changes dependent on the react-sdk. I'm amazed it already passes when the classes I'm using simply aren't there

**Comment by jryans** [comment]
Ah, I see, yes that should certainly fail...

**Comment by turt2live** [comment]
I think we fixed this
