### ISSUE TITLE
Room Directory and Chat with Riot Biot from welcome broken when HS disables guest access

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9546]
If the default HS for your Riot install has guest access disabled (`allow_guest_access: False`), then both the "Chat with Riot Bot" and "Room Directory" actions will fail quite badly:

* Chat with Riot Bot silently does nothing 
* Room Directory opens a model an infinite spinner:

![image](https://user-images.githubusercontent.com/279572/56591321-70240800-65e0-11e9-9a47-11ed6d54e9c9.png)

**Comment by turt2live** [comment]
We should just hide these options when we can't register a guest imo

Or provide a config option to hide the whole section.
