### ISSUE TITLE
trying to transfer E2E files to servers with small transfer sizes breaks with inscrutable errrors

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9552]

**Comment by lampholder** [comment]
I guess you reproduce this by being on a home server with small file size limits and trying to decrypt an encrypted file.

**Comment by turt2live** [comment]
have posted a $25 bounty if anyone is interested in solving this. Improving the error message to not be so confusing would be amazing.

See https://www.bountysource.com/issues/73246138-trying-to-transfer-e2e-files-to-servers-with-small-transfer-sizes-breaks-with-inscrutable-errrors for bounty details.

**Comment by uhoreg** [comment]
This sounds like a dup of https://github.com/vector-im/riot-web/issues/3892.  Travis, are you able to transfer your bounty to that issue (or should we just close that issue and keep this one)?

**Comment by turt2live** [comment]
I'll contact support and see what they can do.
