### ISSUE TITLE
Windows 10, Riot desktop application doesn't log in.

### ISSUE THREAD

**Issue by createchange** [vector-im/riot-web#9553]
### Description

I was recently having issues with certs. I set up a matrix-synapse homeserver as one of the first real projects when I was teaching myself IT. There is a lot I would change, but I was able to get things operational again.

When trying to figure out the cert stuff, I was getting 502 errors, I attempted connecting through various devices during that time, including: browser, iOS app, Windows desktop app. Once I was able to get the certs sorted out, connectivity was regained through the browser and iOS application, but not the desktop app.

If I enter incorrect credentials, I get rejected for bad auth attempts. But if I enter correct credentials, the window turns white with a loading circle and a logout button, but never progresses past that. It would seem that I have authenticated fine (I could cross-reference the matrix-synapse logs if it would help), but I just cannot drop back into a session.

I have uninstalled and reinstalled Riot, as well as rebooted. This does not resolve the issue. I checked for remnant files after uninstalling, but didn't see anything.

### Steps to reproduce

- Log in with correct credentials
- Sit in white loading screen
- Log out
- Rinse
- Repeat

Without logging in, there does not seem to be a way to access the settings menu.

### Version information

- **Platform**: web (in-browser) or desktop? Desktop

- **OS**: Windows
- **Version**: 1.0.8

**Comment by createchange** [comment]
I enabled developer tools in the app, and saw this error after having successfully authenticated:

> Failed to load https://example.com/_matrix/client/versions: Redirect from 'https://example.com/_matrix/client/versions' to 'https://example.com/_matrix/client/versions' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'vector://vector' is therefore not allowed access.

More information: I have the homeserver set up behind an Nginx proxy - they reside on different VMs. I am happy to provide configs if that will help (they are a mess). I am expecting to get redirected to the Matrix team, but I will mention again that I am able to use the Web and both iOS and Android clients to access this homeserver without issue.

On the reverse proxy and homeserver, I have added the following "add_header" directive:

```
# Reverse proxy nginx config
location / {
                  proxy_set_header X-Real-IP  $remote_addr;
                  proxy_set_header X-Forwarded-For $remote_addr;
                  proxy_set_header Host $host;
                  proxy_pass https://192.168.1.42;
                  add_header 'Access-Control-Allow-Origin' '*';
 }
```

```
# Homeserver nginx config
location /_matrix {
        proxy_pass http://localhost:8008;
        add_header 'Access-Control-Allow-Origin' '*';
    }
```

which results in the opposite error:

> Access to XMLHttpRequest at 'https://example.com/_matrix/client/r0/joined_groups' from origin 'https://riot.im' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

And immediately knocks the server offline.

I am not sure what the issue is, and I've reached the limit of what I can run down and still enjoy my night, so help would be appreciated.

Thanks!
Jonathan

**Comment by turt2live** [comment]
Usually CORS hides the underlying error, and the `add_header` isn't strictly required. From the network pane of the developer tools, what is the status code for the failed request? It might just be an innocent timeout caught in the fray.

**Comment by createchange** [comment]
Thanks for the response. Quick point that I need to add on - I tested on my work laptop, and it connects just fine. 

It would appear that the issue is just relegated to this specific install. However, as mentioned earlier, rebooting/reinstalling has unfortunately not been successful.

Here is a screenshot of the responses:
![responses](https://user-images.githubusercontent.com/29058450/56709460-aa73cf00-66de-11e9-8d83-99c80b5c84ee.PNG)

**Comment by createchange** [comment]
I would like to have a functional chat client and not have to resort to the web browser. Curious if I can get some more help on this? Has it been determined that is, in fact, not a bug? It would appear to me that this has not been determined, especially since all other Desktop application using users are having no issues - it's only with this uninstall.

Where are files placed when the desktop client is installed? I would like to at least have that info so I can remove everything and do a completely fresh install.

**Comment by jryans** [comment]
> I would like to have a functional chat client and not have to resort to the web browser. Curious if I can get some more help on this? Has it been determined that is, in fact, not a bug? It would appear to me that this has not been determined, especially since all other Desktop application using users are having no issues - it's only with this uninstall.

So far, I don't think we know what the issue is here. GitHub issues aren't the best format for support questions, so you may have better luck asking for help in #riot:matrix.org.

> Where are files placed when the desktop client is installed? I would like to at least have that info so I can remove everything and do a completely fresh install.

On Windows:

* App files are installed in `C:\Users\<User>\AppData\Local\riot-web`
* User data is kept in `C:\Users\<User>\AppData\Roaming\Riot`

Note: Deleting your user data directory would cause you to lose E2E message keys, unless you had already enabled the Key Backup feature.

**Comment by createchange** [comment]
@jryans 

Starting by letting you know that blowing away all installation files on Windows did the trick - thank you for that information. :)

I guess we have a different understanding of what would constitute support vs. a bug, or where they overlap. I would consider not being able to log into the app to be a bug that support is an aside on to figure out the underlying issue, but I'm probably missing some nuance as I'm admittedly not a developer.

Thank you again for your help, and for your work. I appreciate the freedom that your products provide. Keep up the good work!

**Comment by jryans** [comment]
> I guess we have a different understanding of what would constitute support vs. a bug, or where they overlap. I would consider not being able to log into the app to be a bug that support is an aside on to figure out the underlying issue, but I'm probably missing some nuance as I'm admittedly not a developer.

Admittedly, it's a bit fuzzy and can depend on the precise nature of what you are seeing. Please free to communicate your feedback in whatever medium (issue, chat, etc.), but just be aware we may recommend moving to a different forum for certain types of reports. 😁 

For issues that appear to only affect one person where the root cause is unknown, asking via chat tends to be a faster path towards a solution, since we may need to debug the issue interactively.

Anyway, I am glad to see the issue is fixed
