### ISSUE TITLE
Manually deleted IndexedDB/log database not created from scratch on next load

### ISSUE THREAD

**Issue by andreygursky** [vector-im/riot-web#9560]
### Description

Using browser developer tools it is possible to delete IndexedDB/log database manually. Then there is a persistent error during loading riot-web:
```
rageshake.js:107 Failed to open log database: AbortError
e.(anonymous function) @ rageshake.js:107
t.onerror @ rageshake.js:203
error (async)
(anonymous) @ rageshake.js:201
n._execute @ bluebird.js:985
R._resolveFromExecutor @ bluebird.js:3268
R @ bluebird.js:2864
value @ rageshake.js:193
init @ rageshake.js:543
(anonymous) @ rageshakesetup.js:32
(anonymous) @ rageshakesetup.js:53
o @ bootstrap:63
(anonymous) @ index.js:29
(anonymous) @ index.js:431
o @ bootstrap:63
(anonymous) @ server.js:3
o @ bootstrap:63
(anonymous) @ bootstrap:196
(anonymous) @ bootstrap:196
```
and immediately after that:
```
rageshake.js:107 Failed to initialise rageshake: Error: Failed to open log database: AbortError
e.(anonymous function) @ rageshake.js:107
(anonymous) @ rageshakesetup.js:45
c @ bluebird.js:5276
R._settlePromiseFromHandler @ bluebird.js:3297
R._settlePromise @ bluebird.js:3354
R._settlePromise0 @ bluebird.js:3399
R._settlePromises @ bluebird.js:3475
(anonymous) @ bluebird.js:175
Promise.then (async)
a @ bluebird.js:4504
s.hasDevTools.l.settlePromises @ bluebird.js:174
R._reject @ bluebird.js:3442
R._rejectCallback @ bluebird.js:3259
(anonymous) @ bluebird.js:3271
t.onerror @ rageshake.js:204
error (async)
(anonymous) @ rageshake.js:201
n._execute @ bluebird.js:985
R._resolveFromExecutor @ bluebird.js:3268
R @ bluebird.js:2864
value @ rageshake.js:193
init @ rageshake.js:543
(anonymous) @ rageshakesetup.js:32
(anonymous) @ rageshakesetup.js:53
o @ bootstrap:63
(anonymous) @ index.js:29
(anonymous) @ index.js:431
o @ bootstrap:63
(anonymous) @ server.js:3
o @ bootstrap:63
(anonymous) @ bootstrap:196
(anonymous) @ bootstrap:196
```

### Steps to reproduce

- navigate developer tools --> application --> storage --> IndexedDB
- delete log database
- reload riot.im/app (again and again)

Expected: log database is created from scratch if it could not be found.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chromium 73.0.3683.75-1
- **OS**: Debian testing
- **URL**: riot.im/develop and riot.im/app

**Comment by jryans** [comment]
After testing here, the log database _is_ re-created after these steps. I believe (since you're also on #7769) this is just another version of hitting the storage space limits. Since Chrome thinks you're out of space, it's refusing to allow the database to be created.

Let's consider this a variant of #7769.

**Comment by andreygursky** [comment]
Thanks for trying out.

Regarding the message "Error: Failed to open log database: AbortError". Since something like "failed to create" is missing, it could mean there is some open() function that implicitly creates a database if no existing is found. So if open() fails it means actually not only opening but also re-creating has failed. Maybe the error message can then be improved to reflect this?

> Since Chrome thinks you're out of space, it's refusing to allow the database to be created.

That's strange, since matrix-js-sdk:crypto and matrix-js-sdk:riot-web-sync are re-created.
