### ISSUE TITLE
riot.im Server problems? (is this the right place to ask for this?)

### ISSUE THREAD

**Issue by GITchristoph** [vector-im/riot-web#9565]
### Description

I am new to riot.im and while connected to my riot account via the webpage I would like to:

1. Invite other members to a room (e.g. user@example.com)
2. Add an email address to my username
3. Add a phone number to my username 

None of the items above work.

Error messages are:

1. user@example.com: Unknown server error
2. **Unable to add email address**  - Server returned 520 error (Status 520)
3. **Error** - Service Unavailable (Status 503)

Could it be that there are server issues at the moment?

Is there another way to find this out instead of opening an issue here in github?
I hope it's ok that I post this here.

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Safari
- **OS**: macOS
- **URL**: riot.im/app /

**Comment by t3chguy** [comment]
Those sound like issues with the vector.im identity server, inviting `user@example.com` is an e-mail invitation, perhaphs you mean the matrix user id `@user:example.com`

**Comment by GITchristoph** [comment]
Thanks for your answer

I am not sure what the Matrix user ID is but it makes sense I guess. 

I have a username at the moment which is not my email address. I would like to add my email address to this username and that gives me the error message as exclaimed in point 2 above. 
Adding a phone number to that username gives the error message as per point 3.

I hope that makes sense

**Comment by dbkr** [comment]
I can't reproduce these errors. Is there any chance you would have entered a custom identity server when registering / logging in? Can you try this again and send a bug report from settings if it still doesn't work? There will have been a brief period of downtime for sydent this morning, it's possible that you managed to try all three things within that window.

**Comment by GITchristoph** [comment]
Hi

It must have been a server issue that is solved now.
All 3 items work now.

The outage for me was from approx. 23pm last night until lunch time today (CET).

**Is there a website that informs about server outages or maintenance times?**

Looking forward to get into this more now.

Thanks a lot!

**Comment by jryans** [comment]
> Is there a website that informs about server outages or maintenance times?

There is normally https://status.matrix.org/, though that itself still needs to be rebuilt at the moment.

**Comment by GITchristoph** [comment]
Cool!

Understood and thanks ;-)
