### ISSUE TITLE
When you deactivate your account you get left on a partially responsive settings screen atop the login background

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9566]
![image](https://user-images.githubusercontent.com/1922197/56799205-5d901580-6810-11e9-911e-08ac11b5d82d.png)

Only _Voice and Video_ and _Labs_ work.

**Comment by anoadragon453** [comment]
![image](https://user-images.githubusercontent.com/1342360/61067486-8c755b00-a3ff-11e9-8299-c935f30d2505.png)

Still seeing this today. Not the best last-impression.

**Comment by turt2live** [comment]
I'm arbitrarily bumping the priority and counting it as a FiP despite not being FiP.
