### ISSUE TITLE
Reactions: Send reaction event when user reacts

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9572]
Reaction events are sent in response to 2 UI actions:

* Choosing a new emoji type from the picker
* Clicking on an existing type displayed below a message to increment an existing type

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/114)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2395)
