### ISSUE TITLE
Reactions: Undo a reaction

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9574]
Undo a reaction by clicking an emoji type below the message you previously voted for.

To send an undo to the HS, redact the previous reaction event.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/117)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2398)
