### ISSUE TITLE
Reactions: Add primary reactions as message actions

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9576]
In the message action bar, alongside a button that opens the emoji picker to choose any emoji, we should also offer easy access to the primary emoji types:

* 👍 / 👎 
* 🙂 / 😔

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2393)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/112)

**Comment by NotAFile** [comment]
How were the primary emoji types decided? Of course, you can bikeshed endlessly over this, but I think 👍🙂 and their opposites are nearly identical in meaning. I assume the plan is to just make the featured ones the most "frecent" in the future?

**Comment by jryans** [comment]
> How were the primary emoji types decided? Of course, you can bikeshed endlessly over this, but I think 👍🙂 and their opposites are nearly identical in meaning. I assume the plan is to just make the featured ones the most "frecent" in the future?

These primary types are meant to have additional meaning in that they will also serve as signals in a future reputation system. I would encourage you to join #matrix-reputation:matrix.org if you're interested in more details here.

The primary emoji themselves would not change over time. Other emoji would be accessed separately through a larger emoji picker.
