### ISSUE TITLE
I am not able to register a new password using two-stage process on OFTC 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#9579]
While it took me lot of time to figure out that I needed to reset my password. I tried doing that . While I got the reset password it comes in sort of like this - 

```
/msg NickServ SENDPASS shirish
numeric:alphanumeric token <yournewpassword>
```

Now I tried various combinations such as - 
```

/msg NickServ SENDPASS shirish
numeric:alphanumeric token <yournewpassword> 
```

It siad unrecognized command . 

I tried then - 

```
msg NickServ SENDPASS shirish
numeric:alphanumeric token <yournewpassword> 
```

got the same error . 

Then tried 

```
msg NickServ SENDPASS shirish
numeric:alphanumeric token yournewpassword
```

to which Nickserv says - 

```
NickServ
14:10
Unknown command msg, /msg NickServ HELP for help.
```

Tried doing that and it says - 

```
Command error
Unrecognised command: /msg NickServ help
```

I am not using the real tokens and the passwords to protect my privacy . But the format in which the messages were received in my email box was the same as described above. The password I made was also alphanumric+special symbol password. 

So seems we riot is unable to figure out the commands for IRC or something. Have no clue. I also tried using devtools from Settings > Advanced > Open Devtools but was none the wiser. 

Could somebody explain or share more.

**Comment by t3chguy** [comment]
`/msg` is an IRC command which does not exist in Riot, to do the equivelant, simply say `SENDPASH shrish` inside the chat you have with NickServ

**Comment by shirishag75** [comment]
are you sure it is **SENDPASH** , at my end it was sendpass shirish which did the first part of the two pass-process. 

The first part is where I get an email with a token, the second is where I have to put the token along with my

**Comment by t3chguy** [comment]
that was merely a typo, what I'm saying is you replace `/msg NickServ <X>` with sending a messgae in the room with NickServ of `<X>`

**Comment by shirishag75** [comment]
> that was merely a typo, what I'm saying is you replace `/msg NickServ <X>` with sending a message in the room with NickServ of `<X>`

could you put a real hypothetical example so I know exactly what steps to follow.

**Comment by t3chguy** [comment]
> Command error
Unrecognised command: /msg NickServ help

Shows you already have a room with NickServ, in this room send the message `SENDPASS shrish`

**Comment by shirishag75** [comment]
> > Command error
> > Unrecognised command: /msg NickServ help
> 
> Shows you already have a room with NickServ, in this room send the message `SENDPASS shrish`

My dear friend, I already did that. I also received a token from Nickserv to the email registerd to the nick I have. 

Where I am having issue is at the last stage which is where I try to put the msg to nickserv with the token and a new password so that nickserv recognizes who I am using the one-time token generated by the system and a new password used by me. This is where I am stuck, in the second and final phase , not in the first phase.

**Comment by t3chguy** [comment]
The e-mail probably gives you an instruction to paste `/msg NickServ ...` into your IRC client right? Just paste the bit after `/msg NickServ`

I am not familiar with OFTC, if you want to get help from NickServ just send the message `help` in the room you have with NickServ.

**Comment by shirishag75** [comment]
> The e-mail probably gives you an instruction to paste `/msg NickServ ...` into your IRC client right? Just paste the bit after `/msg NickServ`
> 

That fixed it, somehow it needs to be made more intuitive :(
