### ISSUE TITLE
Phone numbers are not authorized to register on this server

### ISSUE THREAD

**Issue by tgr** [vector-im/riot-web#9580]
After setting up a new modular.im server and trying to register on it, I get a "Phone numbers are not authorized to register on this server" error. If they are not authorized why show a phone number field in the registration form?

(Riot-web, Chrome 73 / Ubuntu 18.04, `XXX.riot.im/#/register` page, a brand new modular.im server. Couldn't actually register due to an unrelated bug so not sure about the exact Riot version.)

**Comment by lampholder** [comment]
I've raised this with the modular team. Riot web does the right thing (i.e. hides the phone number field) when the homeserver says that it doesn't support phone number registration.

**Comment by rxl881** [comment]
@tgr - Thanks for pointing this out. We've implemented a fix for this (hiding the phone number field) which should be rolled out to all modular hosts tomorrow morning UK time.

**Comment by lampholder** [comment]
This should now be rolled out to all modular hosts :)
