### ISSUE TITLE
Registration failure

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9581]
I just tried a typical registration flow on riot.im/app - signing up as matthewtest17.  I copied the verification link from my mail client into the browser, did the captcha, clicked the T&Cs, and then got logged in as a Guest rather than matthewtest17.  This triggered two weird errors: "To do this action, you must register" (despite me having registered), and then a warning that I was logged in a guest whilst trying to do behaviour as a registered user.  I then explicitly chose login from the TopLeftMenu to re-login as matthewtest17.  :-/

**Comment by lampholder** [comment]
Coudl be related to https://github.com/vector-im/riot-web/issues/9480

**Comment by turt2live** [comment]
fwiw the code that tries to make this less of a disaster hasn't landed on /app yet - see also https://github.com/vector-im/riot-web/issues/6875

**Comment by ara4n** [comment]
I just this happen again, on signing up another new test account on riot.im/app (now on 1.1).

This feels like registration is just completely broken right now, and has been for several weeks?!
