### ISSUE TITLE
Cannot accept new terms - HMAC incorrect

### ISSUE THREAD

**Issue by flaphoschi** [vector-im/riot-web#9584]
### Description

Since friday we have new terms and policies, the channel *System Alerts* requires me to accept them and click on a link.

### Steps to reproduce
1.) Open you client and open the link from the channel (I tried it with Fractal on Linux, Riot for iOS and Riot Website with Firefox and Epiphany)
2.) Website says only "HMAC incorrect"

When I remove the parameter "u" and argument which is my username, I can see the new terms. But how to accept it? Is the parameter "h" and it's long random looking argument enough?

Thanks

**Comment by ara4n** [comment]
which server is this?

**Comment by flaphoschi** [comment]
My homeserver is matrix.org
The URL:
https://matrix.org/_matrix/consent?h=RANDOM_CHARACTERS&u=MY_USERNAME

**Comment by ara4n** [comment]
i'm confused, as we haven't changed the terms & conditions on the Matrix.org server in months...

**Comment by flaphoschi** [comment]
That’s it. I mixed up the messages in the channel from the past :sleepy:

My bad. I‘m sorry.

**Comment by ara4n** [comment]
np :)
