### ISSUE TITLE
translate.riot.im is not available

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9585]
The following url is not working: https://translate.riot.im found on the following page https://github.com/vector-im/riot-web/blob/master/docs/translating.md

And when you go to the following page https://translate.riot.im/accounts/profile/ (redirects to https://matrix.orgaccounts/profile/) there is a warning of a potential security risk using Firefox.

_Originally posted by @preemeijer in https://github.com/vector-im/riot-web/issues/9511#issuecomment-485127214_

**Comment by dbkr** [comment]
It's back and hopefully working

**Comment by preemeijer** [comment]
@dbkr works as expected.
Thanks! Cheers, Paul
