### ISSUE TITLE
Password reset sends the account regisration email copy

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9587]
> Hello there!
> 
> You have asked us to register this email address with riot.im - the open source, distributed and secure shared workspace for the web that's built on Matrix.
> 
> If it was really you who made this request, you can click on the following link to complete the verification of your email address:
> ...

It should say something about resetting your password.

**Comment by ara4n** [comment]
dup of https://github.com/vector-im/riot-web/issues/2761
