### ISSUE TITLE
Email Registration. the verifcation Email takes hours before the server sends it

### ISSUE THREAD

**Issue by dikruege** [vector-im/riot-web#9589]
### Description

During setup an account its not possible to register with an email right away.
Even Create and account and register an Email later is almost impossible.
I takes up to 5-6 hours till the System sends out an Confirmation mail.

### Steps to reproduce
- Open Opetions
- instert vaild mail
-Press 'Add MAIL' Button
Wait till Winter is comeing

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:
Version von matrix-react-sdk: <local>
Version von riot-web: 1.0.7
Version von olm: 3.0.0
and
RIOT Andriod App from Google play store

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows 10
- **Version**: 1.x.y

**Comment by ara4n** [comment]
ugh, sorry - this was due to an overloaded identity server; is now fixed.

**Comment by dikruege** [comment]
seams not solved...

**Comment by ara4n** [comment]
hm, it should be fine now. reopening for someone to try to repro.

**Comment by lampholder** [comment]
It _does_ seem fine to me (I just got a registration email instantaneously, both on setting up a fresh account and on linking an additional email address with an existing account) - I wonder if there's something peculiar to your email server? Are you able to share the domain?

If you'd rather not share your email address publicly you can message me on matrix @tom:lant.uk or via email tom@matrix.org.
