### ISSUE TITLE
Homeserver name is converted to lower case

### ISSUE THREAD

**Issue by LexPendragon** [vector-im/riot-web#9590]
### Description

I could not get Riot.IM to sign in with the Linux desktop app, [the web page](https://riot.im/app/#/room/#riot:matrix.org), nor the android app.

### Steps to reproduce

- Open the application and click Change to update the homeserver:

![image](https://user-images.githubusercontent.com/30753787/56923691-30a26380-6a99-11e9-83c1-2911bef04cfa.png)

- Click next to return to the username screen.  You can see the account name now shows as lowercase, which breaks Federation

![image](https://user-images.githubusercontent.com/30753787/56923701-38620800-6a99-11e9-98f5-376655d68c0b.png)

- After clicking sign in, it will attempt to sign in before giving an error:
Can't connect to homeserver - please check your connectivity, ensure your homeserver's SSL certificate is trusted, and that a browser extension is not blocking requests.

![image](https://user-images.githubusercontent.com/30753787/56923995-e40b5800-6a99-11e9-9e4a-50dc7a2c7f74.png)

If it retained the case sensitivity, the connection should go through.

Log: Not sent, I can't get in to see a log    

### Version information

- This was on the Android App from Google Play, the web page, and a self compiled app on OpenSUSE Tumbleweed

For the web app:

- **Browser**: Firefox 66.0.3 (64-bit)
- **OS**:  Linux, OpenSUSE Tumbleweed
- **URL**: https://riot.im/app/#/login

For the desktop app:

- **OS**:  Linux, OpenSUSE Tumbleweed

- **Version**: riot-v1.0.8-86-g77dff119.tar.gz was used, can't reach user settings panel.

**Comment by LexPendragon** [comment]
I recreated my homeserver using lowercase, and Riot connected fine.

**Comment by turt2live** [comment]
This is a feature of JavaScript that we can't reasonably fix. The URL parser built into browsers squashes the case down to lowercase, and we use the parser to validate the URL.
