### ISSUE TITLE
Message action bar has no border on dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9591]
![image](https://user-images.githubusercontent.com/1190097/56928669-ca1b4680-6a94-11e9-82cb-e0dd70abbc9f.png)

it's hard to know where the button starts.

**Comment by jryans** [comment]
Ah right, I noticed this before merging, but then I forgot to wait for an updated colour decision. Blocked on colour help from @nadonomy.

**Comment by jryans** [comment]
We have a design, so I'll update the colours now.

**Comment by jryans** [comment]
I have also [added](https://github.com/matrix-org/matrix-react-sdk/commit/33bb9e2af65e805180aa17dd6000a3f4fe238c85) this to the release branch.
