### ISSUE TITLE
Move read avatars to author line

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#9595]
Currently, the list of tiny avatars to the right is flush with the first line of the message, and then truncated to avoid overlapping with it.  The line above that, which shows the author name and flair, tends to have a large empty space - so it makes sense to move the read avatars there, and truncate only when that line approaches the name/flair.

**Comment by jryans** [comment]
Note that https://github.com/vector-im/riot-web/issues/4377 proposes they should be at the bottom of the message, so we many need to reconcile these two suggestions.

**Comment by aaronraimist** [comment]
The decision has been made to line then up with the bottom of the message in https://github.com/matrix-org/matrix-react-sdk/pull/3892
