### ISSUE TITLE
Low quality of image thumbnails in encrypted rooms

### ISSUE THREAD

**Issue by Player701** [vector-im/riot-web#9599]
### Description

When end-to-end encryption is enabled, image thumbnails seem to have lower quality than those posted in unencrypted rooms.

### Steps to reproduce

- Post [this test image](https://mega.nz/#!btcA0ArA!hRpNaCm8V8eYqGRhSqTjDGYNqNBklEfYdBcTY7MJ97k) in an unencrypted room. Thumbnail looks like [this](https://imgur.com/a/LtstPV2).
- Post the same test image in an encrypted room. Thumbnail looks like [this](https://imgur.com/a77RDwR). The quality is noticeably lower than in the previous case.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 66.0.3 (64-bit)
- **OS**: Windows 10
- **URL**: riot.im/app

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/2769
