### ISSUE TITLE
Room Upgrade nits

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9603]
- [x] The top and the bottom got cut off my admin warning:
     ![Screenshot 2019-05-01 at 12 39 10](https://user-images.githubusercontent.com/1922197/57016030-d2e45780-6c0f-11e9-976e-36cb169efd1e.png)
- [x] "creating a room it it's place" (it it typo):
    ![Screenshot 2019-05-01 at 12 43 57](https://user-images.githubusercontent.com/1922197/57016031-d37cee00-6c0f-11e9-8a60-fe64aef22618.png)
- [x] Why do we have two confirmation UXes, ^ this and v this ?:
    ![Screenshot 2019-05-01 at 12 44 13](https://user-images.githubusercontent.com/1922197/57016032-d37cee00-6c0f-11e9-84d9-ea34d49bf72b.png)

**Comment by turt2live** [comment]
> Why do we have two confirmation UXes

The second one is supposed to scare you to not run it - it's only shown for slash commands.
