### ISSUE TITLE
Trade mark symbol ™ (Unicode character U+2122 TRADE MARK SIGN) is replaced by a picture with emoji substitution disabled

### ISSUE THREAD

**Issue by ethus3h** [vector-im/riot-web#9612]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.
The trade mark symbol ™ (Unicode character U+2122 TRADE MARK SIGN) is replaced by a picture with emoji substitution disabled.

Here is a picture showing my settings: 
![Screenshot_2019 05 01_20 38 26](https://user-images.githubusercontent.com/10457522/57051808-625e2a80-6c51-11e9-8596-042fb6317af9.png)

### Steps to reproduce

- Disable emoji substitution in settings (Settings → Preferences → Automatically replace plain text Emoji)
- Type or paste ™ (Unicode character U+2122 TRADE MARK SIGN)

Describe how what happens differs from what you expected.

I expect a trademark sign to display as text, but it is displayed as a picture. I have the typefaces I want installed on my computer and configured the way I want them; I never want a Web site to try to override it (not least because the picture substituted is blurry, hard to read, and doesn't match with the surrounding text), but even with substitution theoretically disabled in the app settings (and Web pages prevented from overriding my typeface settings in the browser preferences), it still insists on replacing it.

Log: sent/not sent?  Not sent  

![Screenshot_2019 05 01_21 06 01](https://user-images.githubusercontent.com/10457522/57052417-f8478480-6c54-11e9-84d4-611dd1ac24bc.png)

### Version information

- **Platform**: web (in-browser) or desktop? Web

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Firefox 60.5.1 ESR
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Gentoo GNU/Linux
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? riot.im/app

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
We do this for quite a few unicode symbols, such as other emoji. The fix is https://github.com/vector-im/riot-web/issues/9281
