### ISSUE TITLE
Can't remove "direct chat" attribute from group chat

### ISSUE THREAD

**Issue by t-aus-m** [vector-im/riot-web#9614]
### Description

A user I was chatting with created a room by adding more users to our direct chat. Since then I can't get the chat to be a group chat by removing the "direct chat" option on desktop.

### Steps to reproduce

- Create direct chat
- Invite more people
- Try to change the option for "direct chat" to be off

After doing that, the particular chat will not move to the room section, but will stay in the people section. Also when I open the context-menu again, the "direct chat" option is marked as active again.

Log: sent  

### Version information

- **Platform**: Desktop
- **OS**: Ubuntu 19.04
- **Version**: 1.0.8

**Comment by lampholder** [comment]
Interesting - is this on matrix.org?

I can't reproduce this, but I have experienced similar behaviour in the past, usually exacerbated by the homeserver being slow to respond under load.

Can you try toggling off Direct Chat and then leaving it for a while to see if the request does go through?

Obviously that shouldn't be necessary, but I don't think we have local echo implemented properly on the room list component yet.

**Comment by t-aus-m** [comment]
Not on matrix.org but on a room with users of three different homeservers.

> Can you try toggling off Direct Chat and then leaving it for a while to see if the request does go through?

I have tried that before, it did not work.

In the meantime I managed to solve the issue by leaving the room and being invited back into the room. Works as a fix for me, but might not work for other users.

**Comment by turt2live** [comment]
In the new room list it's impossible to change the DMness of a room.
