### ISSUE TITLE
(x) on widgets is ambiguous, possibly broken

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9622]
I keep on clicking it expecting it to dismiss widgets with cookie warnings, but it does nothing. After minimising a widget it again does nothing.

The hover tooltip labels the icon as 'Revoke widget access' but it's not clear if that's for me, or for everyone.

We should clarify the intention of the button, and consider changing the interaction to [...] to reveal a context menu where we can use words to label the action(s) rather than abstract icons.

**Comment by turt2live** [comment]
We replaced it with a menu which has words.
