### ISSUE TITLE
Aggregations: Avoid clipping context menu

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9624]
With the current [...] context menu implementation the menu is often clipped off screen.

Instead of rendering it to the right of the action bar, we should position it beneath it, and aligned to the right. If the context menu would be clipped at the bottom (e.g. on the last message in the timeline) we should render it above, again aligned to the right.

When we do this, we don't need to worry re-creating the arrow part of the tooltip background— stylistically we can follow the profile top left context menu.

**Comment by uhoreg** [comment]
See also https://github.com/vector-im/riot-web/issues/3429, which mentions other things that overflow (some of which are now fixed)
