### ISSUE TITLE
A new room only appears in breadcrumbs the second time you enter it

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#9625]
Create a new room, send a bunch of messages, switch to another room: the room you just created is not in the breadcrumbs while it should be. It should probably appear the moment you enter it, like when you switch to an existing one

**Comment by turt2live** [comment]
is this on /app or /develop? It appears to work okay on develop ._.

![image](https://user-images.githubusercontent.com/1190097/57151416-28467300-6d8e-11e9-8247-6eeb53e4ce63.png)

**Comment by lampholder** [comment]
I can't reproduce this either on /develop, so I'm going to close this
