### ISSUE TITLE
onRoomTimeline in breadcrumbs is unsafe

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9630]
https://github.com/matrix-org/matrix-react-sdk/blob/4450740d7de0030f1b0214fdd892b250e1db3c9a/src/components/views/rooms/RoomBreadcrumbs.js#L119-L123

The above doesn't check if the room is null until the `_calculateRoomBadges` call, which can apparently cause the app to stop functioning. Not entirely sure how this happened though given this is a case of "this should never happen" as we get the `room` from the js-sdk's emitter.

**Comment by jryans** [comment]
It's not currently true that all `EventTimelineSet`s have `room`s. It is quite unfortunate that something  where the `room` is optional emits `Room.timeline`, but let's worry about that separately...

I believe this is how it happens:

1. `_createClient` [creates](https://github.com/matrix-org/matrix-react-sdk/blob/67d22ab33162bbcc051edf9a5c06603775750710/src/MatrixClientPeg.js#L197) an `EventTimelineSet` with `room: null` for tracking notifications
2. The `SyncApi` [re-emits the `Room.timeline[Reset]`](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/sync.js#L107-L110) events from this special notification timeline set onto the client

Therefore, it seems that every handler bound to the client for `Room.timeline` or `Room.timelineReset` must test for `room` if it expects one to exist.

**Comment by jryans** [comment]
Also [merged](https://github.com/matrix-org/matrix-react-sdk/commit/19cd02e4e2b566db0f2f339b40ad5a528558ea8b) to release branch.
