### ISSUE TITLE
E2E: Cross Signing: Remaining items (backend)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9631]
- [x] Tidy Synapse code (early-to-mid next week)
  - [x] clean up `upload_signing_keys_for_user` and convert to use 3-key system
  - [x] convert sytests to use 3-key system
  - [x] convert unit tests to use 3-key system
  - [x] clean up `upload_signatures_for_device_keys`
  - [x] make sure federation works with 3-key system
  - [x] when user-signing key is changed, only user should be notified (should be done, but not tested yet)
  - [x] add lots of comments
  - [x] split into 2 PRs
  - [x] update spec
- [x] Make sure that cross-signing key changes are handled correctly
- [x] Switch to 3-key system
- [x] Making the clients stay in sync with each other e.g. if one device signs a key, then other devices will trust it
- [x] Sharing cross-signing keys when you add a new device
- [x] Update SAS functions to verify the cross-signing key
- [x] Write a quick demo
- [x] Update key backup to be signed/verified by cross-signing key
- [x] Migrate device verifications to master key verifications
  - [x] Synapse
  - [x] js-sdk
  - [x] MSC

**Comment by lampholder** [comment]
Related links:
- https://github.com/matrix-org/synapse/issues/4110
- https://github.com/vector-im/riot-web/issues/7827
- https://github.com/matrix-org/matrix-js-sdk/pull/832

**Comment by Thatoo** [comment]
Is cross-signing on android/Riot and android/RiotX at the same stage that on Riot-web (Riot desktop)?
I guess iOS user are wondering the same too, so same question for them.

**Comment by ara4n** [comment]
no, we're doing the initial implementation on riot/web (aka riot/desktop) and testing it there. if it works well in practice, then the mobile clients will port over the code. we won't bother porting it to riot/android, only riotx.

**Comment by Thatoo** [comment]
It looks like we are very close to get this feature working and available on Riot, doesn't it?

**Comment by uhoreg** [comment]
The synapse bits are all merged now.  We will track the JS SDK part via its own PR, and the UI parts have their own issues, so I'm going to close this issue.
