### ISSUE TITLE
Token Authentification

### ISSUE THREAD

**Issue by ekasuweantara** [vector-im/riot-web#9634]
Hi, can I just log into riot with access_token without a password?
I want to implement SSO at Riot. When the first application is logged in, here I call the login API to get chat details to be displayed in the first application. Here I have got access_token, device_id, home_server, user_id
If the user wants to open the riot website, I want to automatically log in without having to enter a username and password again. I use a riot website with version v1.1.0-rc.1

**Comment by jryans** [comment]
This isn't a great place for support questions. I'd recommend asking in #riot-web:matrix.org.
