### ISSUE TITLE
Fix link to Riot Android on mobile guide

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9635]
Currently links to the old Riot Android im.vector.alpha https://riot.im/app/mobile_guide

**Comment by turt2live** [comment]
Fuuuuuuuuu--

**Comment by ara4n** [comment]
i have manually tweaked the live deployment on riot.im/app/mobile_guide for this, and also fixed riot-web/develop in 03b2766c

**Comment by turt2live** [comment]
Have also cherry picked it (https://github.com/vector-im/riot-web/commit/ee0b7e9c82ea522a1dbbc7cb09bc058575502115) so it lands in the next release
