### ISSUE TITLE
Scroll to bottom icon is broken on FF

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9637]
<img width="152" alt="Screenshot 2019-05-05 at 01 17 44" src="https://user-images.githubusercontent.com/1294269/57186253-a52f3500-6ed3-11e9-8353-8c3ed0b0bccf.png">

**Comment by bwindels** [comment]
wfm on FF ... possible the SVG image just failed to load?

**Comment by lampholder** [comment]
I use FF exclusively and I've never seen this - @ara4n can you reproduce this easily?

**Comment by ara4n** [comment]
i think it must have been a cached 404 or failed image load somehow. it's ok now.
