### ISSUE TITLE
We've lost the ability to quote messages on develop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9639]
![image](https://user-images.githubusercontent.com/1190097/57269132-80f26600-7043-11e9-902e-aa969091d631.png)

**Comment by jryans** [comment]
Hmm, can you identify a specific message that should support quoting but no longer does?

At the moment, I currently see the quote option in the menu for most messages, so a specific regression example would help.

**Comment by bwindels** [comment]
![quote](https://user-images.githubusercontent.com/274386/57290108-44a72000-70ac-11e9-8597-4e5f3c3012ad.gif)

Seems to always be missing for me the first time you open the context menu for a given event. The second and subsequent times you open it, the quote option is there.

**Comment by jryans** [comment]
Thanks for the hint! I'll work on this as a release blocker then.

**Comment by bwindels** [comment]
also happening with reactions labs feature disabled, so likely a release blocker

**Comment by jryans** [comment]
Landed to [develop](https://github.com/matrix-org/matrix-react-sdk/commit/0316deb6c58fbcaddfe2b0f9a3a3db963fbe2112) and [release](https://github.com/matrix-org/matrix-react-sdk/commit/406c9d5d214c3c59bd31ba4d47a5311c95fb9416)
