### ISSUE TITLE
Can't sort favorites anymore

### ISSUE THREAD

**Issue by z3ntu** [vector-im/riot-web#9640]
### Description

It was possible to drag-and-drop the favorites before to change the order they appear in in the sidebar. Now this is not possible anymore.

Log: not sent (I don't think they are relevant)    

### Version information

Version 1.0.8

- **Platform**: both web and desktop

For the web app:

- **Browser**: Chrome
- **OS**: Arch Linux
- **URL**:  riot.im/app

**Comment by aaronraimist** [comment]
Yes that feature was removed. https://github.com/vector-im/riot-web/issues/8614 is the issue about bringing them back so feel free to add a 👍 there.
