### ISSUE TITLE
Composer no longer inserts emoji correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9645]
I end up with both emoji-one and plain emoji when i use the macOS emoji picked (ctrl-cmd-space) to insert a 👍on FF in Slate in MD mode:

<img width="300" alt="Screenshot 2019-05-07 at 15 38 39" src="https://user-images.githubusercontent.com/1294269/57308492-5a353d80-70de-11e9-96a0-34dbf1afcabc.png">

**Comment by jryans** [comment]
(Verified this is not a regession from /app at least, same behavior there.)

**Comment by lampholder** [comment]
I think this is a dup of https://github.com/vector-im/riot-web/issues/7347
