### ISSUE TITLE
Startup performance has degraded (again)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9646]
![image](https://user-images.githubusercontent.com/1190097/57313626-39a0bf80-70ad-11e9-8265-7fdac0c3b89b.png)

and "Aw Snap!" pages indicate that my account is hitting the limits of computing power again. The unresponsive notice appears to be down to enabling encryption whereas the Aw Snap is unknown (likely out of memory).

**Comment by bwindels** [comment]
Do you see this repeatedly whereas before you didn't? Or this happened once or twice recently?

**Comment by turt2live** [comment]
It's happened every time I refresh develop in the last 2ish weeks, whereas before it would be slow to load but never unresponsive/crash.

**Comment by turt2live** [comment]
After a few hours of profiling this, I can't reproduce the behaviour I was (and am) seeing. The profiles show that Riot is just doing stuff it normally would, and the size of my account is making it harder. I'm not seeing the effects of having the debugger open either - in fact, things seem to be smoother when profiling.

Closing until I have concrete evidence of this being a problem, and not just some perceived issue.
