### ISSUE TITLE
Unable to easily click reply or [...] buttons

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#9650]
![riot-bug](https://user-images.githubusercontent.com/1917473/57379829-911f5800-719f-11e9-976b-71d857b73017.png)

### Description

New location of reply and [...] menu is very hard to select. The overlapping with the previous section means that when you mouse into the red area, (which is very easy when attempting to move the mouse to these buttons) you end up moving the message selection to the previous message instead.

That then needs us to move back to the message we wanted to select then try, slower, to get to the button again.

This is incredibly frustrating compared to the previous UI, especially if using a trackpad (in my case) or i imagine for users with pointer control issues - you have to hit a 5mm target and are not allowed to overshoot.

A fix would be not to deselect this message if you enter the red area near the buttons, or put the buttons inside the message itself so that overshoots don't tend to select another message

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox
- **OS**: Debian
- **URL**: riot.im/app

**Comment by jryans** [comment]
@nadonomy, should we try to extend an invisible area around the action bar to make it easier to hit? I believe you're also considering tweaks to the action bar position in general, so it seemed good to have this on your radar.

**Comment by nadonomy** [comment]
I think this is also down to our UI being slightly too small in general too, I find I'm often zoomed in at 110-120%, but definitely out of the scope of this issue. 😉

@jryans Making the hit targets for the buttons bigger, if we have a simple way to do that, sounds good to me. Possibly in conjunction with increasing the button size all round?

The changes I'm going to look at are mostly colour related, along with possibly (ab)using css gradients or box shadows to stop buttons from directly bleeding into text.

**Comment by jryans** [comment]
I believe I can address this with an invisible safe area around the action bar.

**Comment by jryans** [comment]
This has also been merged to the Riot 1.3.0 release branch.
