### ISSUE TITLE
Reactions: Mix of color, non-color emojis and boxes in reaction bar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9651]
![image](https://user-images.githubusercontent.com/1342360/57395165-40e2ce80-717c-11e9-87a5-2af4f5e11cc7.png)

![image](https://user-images.githubusercontent.com/1342360/58090790-fd4a8480-7bbf-11e9-91b4-6356dfc58476.png)

### Description

I'm getting an interesting mix of color and non-color emojis in my reactions bar, which kind of make it look like I've already selected 'Like' when I haven't.

### Version information

- **Platform**: web
- **Browser**: Chromium
- **OS**: Debian Linux
- **URL**: independent build of riot.im/develop

**Comment by jryans** [comment]
Ah, the fun world of native emoji... 😭

**Comment by anoadragon453** [comment]
If there's a way to detect whether at least one emoji won't be rendered properly in the current browser, it may be worth reverting to simpler emotes.

**Comment by ara4n** [comment]
let’s just shove svg in there; of all the things to be consistent, these are pretty important

**Comment by jryans** [comment]
Which SVG would we use...? Whatever we pick, they won't match the platform's native emoji, which seems like it would be visually surprising.

**Comment by Sorunome** [comment]
On electron using archlinux soru just gets boxes for emojis. it seems to be working in webbrowser fine, though

![Screenshot_2019-05-21_12-59-28](https://user-images.githubusercontent.com/2433620/58090736-40105a80-7bc8-11e9-87a6-a84eed8a98d6.png)

**Comment by anoadragon453** [comment]
This seems to have now gotten even worse:

![image](https://user-images.githubusercontent.com/1342360/58090741-e310a680-7bbf-11e9-99b8-88ddfefa69a1.png)

Chromium web, Debian Linux, latest develop

**Comment by jryans** [comment]
_Should_ be fixed as of ~30 mins ago with the new emoji font...

**Comment by Sorunome** [comment]
> _Should_ be fixed as of ~30 mins ago with the new emoji font...

This is from a clean develop build ~10 mins ago

**Comment by f0x52** [comment]
Works in Firefox 67.0 on latest /develop, where previously it was broken
![image](https://user-images.githubusercontent.com/23422690/58091043-ecead780-7bc8-11e9-9d0f-511bbd06a0c8.png)

**Comment by jryans** [comment]
Ah sorry, I was reacting specifically to @anoadragon453's version. I would expect it at least fixed in modern browsers. There may indeed still be an issue with Electron.

**Comment by anoadragon453** [comment]
Correction, getting the following on latest develop:

![image](https://user-images.githubusercontent.com/1342360/58091097-a6917a80-7bc0-11e9-87df-fb210002840b.png)

**Comment by jryans** [comment]
> Correction, getting the following on latest develop:

What version of Chromium?

**Comment by bwindels** [comment]
> Correction, getting the following on latest develop:
> 
> ![image](https://user-images.githubusercontent.com/1342360/58091097-a6917a80-7bc0-11e9-87df-fb210002840b.png)

Crap, I see the same on Chrome 73 on Fedora 30.

**Comment by bwindels** [comment]
changing the font-family to `Nunito, 'Noto Color Emoji', 'Twemoji Mozilla', Arial, Helvetica, Sans-Serif` renders emojis with the native font for me, so chromium does colored emojis, it just doesn't seem to like the Twemoji woff2 file ...

**Comment by bwindels** [comment]
Oddly enough [this says](https://www.chromestatus.com/feature/5897235770376192) that COLR support should have been shipped in version 71.

**Comment by bwindels** [comment]
Might be a problem on macOS as well, see linked issue.

**Comment by jryans** [comment]
As a counterpoint, Chromium 73 on Ubuntu 18.04 from Ubuntu's package repo appears to display the emoji correctly.
