### ISSUE TITLE
Docker hub does not contain any image

### ISSUE THREAD

**Issue by nim65s** [vector-im/riot-web#9653]
Hi,

Even if in #9606, @turt2live said:
> We now have a Docker image autobuilding for releases and master

and if in the main readme we can find:

> The easiest way to use it is to use the prebuilt image:
> `docker run -p 80:80 vectorim/riot-web`

https://hub.docker.com/r/vectorim/riot-web/tags is empty, so I think autobuilding is failing, and that nobody ever pushed a working image.

**Comment by turt2live** [comment]
The builds appear to be failing due to npm packages not being found. It also looks like npm is still recovering from some degradation of service, which might be related.

**Comment by turt2live** [comment]
update on this: it's not npm's fault, it's docker hub's. Their constrained systems can't download our dependencies fast enough, so the build/network times out. Fix is to probably build our images in Buildkite and publish manually, which is much harder.

For the 1.1.0 release, I'll manually build and publish `:latest` and `version-1.1.0`.

**Comment by turt2live** [comment]
I've pushed builds manually for now - please open an issue if they don't work or can't be found.
