### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by alittlebitofit** [vector-im/riot-web#9655]
Currently there is no way I can select multiple messages or multiple chats/rooms neither on web client nor on android app.

It would be better to have a feature that lets you select multiple messages, multiple rooms/chats. 

Deletion would get easier with this new feature.

Hope I am thorough.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5885, https://github.com/vector-im/riot-web/issues/3689, https://github.com/vector-im/riot-web/issues/2158

**Comment by alittlebitofit** [comment]
@turt2live Thanks for the reference. :)
