### ISSUE TITLE
Display picture

### ISSUE THREAD

**Issue by alittlebitofit** [vector-im/riot-web#9657]
Suppose you are in room A, B and C.
So the users in room A would see your display/profile picture or avatar of a cat.
Users in room B would see your profile picture of a dog.
And in room C, picture of a rabbit.

What I am saying is, you get to choose the profile picture others would see according to the room you are in.

I was even thinking of a different profile picture for a particular user.

But I hope I am thorough.

And by the way, just in case to avoid the confusion, I wasn't talking about the room avatar but your own avatar.

Thanks for reading. :)

**Comment by turt2live** [comment]
This is a great idea, although is a duplicate: https://github.com/vector-im/vector-web/issues/2458

**Comment by alittlebitofit** [comment]
@turt2live Again thanks for the reference. :)
