### ISSUE TITLE
GIFs now autoplay even if you've disabled the setting to do so

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9658]
regression.

**Comment by turt2live** [comment]
I'm not able to reproduce this - was it a sticker by chance? (making it a duplicate of https://github.com/vector-im/riot-web/issues/6534)

**Comment by uhoreg** [comment]
I'm seeing this too, ever since I upgraded to 1.1.0.  It happens with non-stickers.

**Comment by jryans** [comment]
I am seeing this also, will investigate...

**Comment by turt2live** [comment]
My testing was flawed I guess, as I can reproduce it now too. Possibly tested against an outdated version of Riot?

**Comment by jryans** [comment]
The regression was caused by https://github.com/matrix-org/matrix-react-sdk/pull/2439.
