### ISSUE TITLE
Use native Promises

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9660]
All of our supported browsers (as well as Node.js) have supported native Promises for a while. We should remove userland Promise libs (like `bluebird`) and convert to native instead.

**Comment by t3chguy** [comment]
benchmarks still tend to show bluebird as performing better than native promises: https://gist.github.com/joseluisq/a87adfd46d86d82ba787919a062f6e36

**Comment by jryans** [comment]
> benchmarks still tend to show bluebird as performing better than native promises: https://gist.github.com/joseluisq/a87adfd46d86d82ba787919a062f6e36

The recent comments there seem to say native is fastest...?

**Comment by t3chguy** [comment]
I somehow completely missed that, also stated in the bluebird README:

> Promises in Node.js 10 are significantly faster than before. Bluebird still includes a lot of features like cancellation, iteration methods and warnings that native promises don't. If you are using Bluebird for performance rather than for those - please consider giving native promises a shot and running the benchmarks yourself.

**Comment by turt2live** [comment]
fwiw we do use the cancellation features of bluebird in the js-sdk

**Comment by ara4n** [comment]
yup, cancellation features are used for cancelling file uploads iirc

**Comment by jryans** [comment]
Hmm, I don't think I am seeing obvious calls to `cancel` on promises so far... Could someone link to an example of where it's being used?

**Comment by t3chguy** [comment]
Cancellations are the least of what we use.

Things like Deferreds, mapSeries etc are simple to transition
Things like `.value()` (a sync way of getting the fulfilled value) and `isFulfilled()` which the code claims we use for performance (to save it being thrown onto the next event loop when it is already done) are much harder. This is a gargantuan task.

**Comment by t3chguy** [comment]
react-sdk changes have landed, js-sdk and riot-web due.

**Comment by t3chguy** [comment]
Fixxxxxed :D
