### ISSUE TITLE
Non-alphanumeric characters corrupted in IRC channels

### ISSUE THREAD

**Issue by tgr** [vector-im/riot-web#9662]
![riot-irc-pipe-char](https://user-images.githubusercontent.com/145412/57478080-e8c8cc80-724e-11e9-814d-2b2ac5c4c884.png)

Note the `=7c` in the nicknames for what should be a `|` (pipe). 

Seen in https://riot.im/app/#/room/#mediawiki:matrix.org which is bridged to `#mediawiki` on Freenode.

**Comment by lampholder** [comment]
@Half-Shot - looks bridgey?

**Comment by Half-Shot** [comment]
Yep, this is bridgey. There is an issue for it on the IRC bridge already. Can close this one.

**Comment by jryans** [comment]
Seems like the bridge issue might be https://github.com/matrix-org/matrix-appservice-irc/issues/749 or similar.
