### ISSUE TITLE
Linux install Error 

### ISSUE THREAD

**Issue by wisdomlight** [vector-im/riot-web#9663]
I am using PureOS - latest
with gnome 3.30.2

I follwoed the instructions from the riot page on linux installation

here's there error i get:
Err:9 https://packages.riot.im/debian green Release                                 
  404  Not Found [IP: 2606:4700:20::6819:2369 443]

and another one

sudo apt install riot-web
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package riot-web

any suggestions?

**Comment by Neonate14** [comment]
I'm using Linux Mint 19.1 and I can't install using apt either. I had to download the .deb file directly and install that.

**Comment by wisdomlight** [comment]
Where do you download the .deb file from?

Sherab

Just like an experience in a dream
Everything I now enjoy
Will become a mere recollection
For what has past will not be seen again

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Neonate14** [comment]
> Where do you download the .deb file from?

https://packages.riot.im/debian/pool/main/r/riot-web/

**Comment by jryans** [comment]
The package repo doesn't know about distro versions like `green`, so I think you'll need to use the deb file directly, or choose the nearest Debian version name instead.
