### ISSUE TITLE
Non deterministic room ordering

### ISSUE THREAD

**Issue by robmv** [vector-im/riot-web#9666]
### Description

Room order change randomly when switching rooms, even when all rooms don't have unread messages. Disabling the `Order rooms in the room list by most important first instead of most recent` preference doesn't change the behaviour

### Steps to reproduce

- Join 4 or more rooms.
- Mark all mesages as read.
- Select a room, wait for its content, select it again, the room changes position only after selected a second time
- Switch rooms randomly, some time the list order changes, sometimes it doesn't (still no new unread messages)

I expect rooms to stay on the same position if no new unread messages have arrived, this help with memory retention and faster location by collation order. I always expect rooms starting with a Z to be at the end on the group list (for my language collation)

IMHO, if the user doesn't have the `most important` preference enabled, all rooms must  be ordered by language collation rules. Maybe move rooms with unread messages to the top, but this subgroup of unread rooms must be collated too.

What is the definition of room importance? does it take into account other things than just unread counts?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 66.0.4
- **OS**: Linux
- **URL**: riot.im/app 1.1.0

**Comment by turt2live** [comment]
The new room list is sorted alphabetically by default, and has options to make it less predictable but hopefully understandable.
