### ISSUE TITLE
How to configure email settings in Riot web

### ISSUE THREAD

**Issue by AyoubGhaddab** [vector-im/riot-web#9668]
Hi,
I am new in matrix server and chat applications.
I am hosting a matrix server and a riot application on a server and i'am still getting riot branded emails, how can I configure to send mail via my homeserver smtp server,

Thank you.

**Comment by jryans** [comment]
Email sending functions are handled by the HS / IS, not the clients, so let's start with your [Synapse](https://github.com/matrix-org/synapse/issues/5172) issue for this.
