### ISSUE TITLE
Reactions: Local echo undo of reaction via redaction

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9675]
We currently don't local echo for redactions (of any kind). This means that undoing a reaction (which uses redactions) feels quite slow. We should support local echo of redactions at least for reactions specifically, but perhaps also for any kind of redaction as well (if that's easy to do).

**Comment by lampholder** [comment]
Similar rationale to https://github.com/vector-im/riot-web/issues/9739, this is being bumped from phase:1 to phase:2
- it's not mvp for reactions

**Comment by lampholder** [comment]
We've decided this _is_ MVP for reactions :D

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/937 and https://github.com/matrix-org/matrix-react-sdk/pull/3058.
