### ISSUE TITLE
develop: version cache not working

### ISSUE THREAD

**Issue by palmtown** [vector-im/riot-web#9678]
Hello,

I am developing Riot and I have 2 issues:

1. When I make changes to files they are not automatically being rebuilt.  
2. When I make changes to files, the Riot client web app does not reload automatically.  

Note that I am using **npm start** to start the development server.  Also, I notice in debugging tools that version/?cachebuster is showing as 404.

Can anyone provide any guidance to what might be wrong?

**Comment by t3chguy** [comment]
> version/?cachebuster is showing as 404.

This is expected, this file is only available in releases

> When I make changes to files, the Riot client web app does not reload automatically.

This is also expected, just how riot development is, you refresh if you want changes

> When I make changes to files they are not automatically being rebuilt.

This is the only bit that is wrong, it works for me and always has in my nearly two years of riot development, you might need to share more information about your environment, anything that could make filesystem watches not work?

**Comment by palmtown** [comment]
Hello t3chguy,

Thank you for your update.  I can't think of what would make filesystem watches not work.  How can I test/debug this feature?  Any help would be appreciated.

**Comment by palmtown** [comment]
I was able to resolve the problem.  I fixed it by deleting the repo and recreating it.
