### ISSUE TITLE
Reactions: Filter to only one reaction per user per key

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9693]
Planning to include your own events in the bundling and aggregated requests

**Comment by jryans** [comment]
Synapse already [enforces this limit](https://github.com/matrix-org/synapse/blob/b051cefc7561139e6dac23a0562cef78eb505646/synapse/handlers/message.py#L607-L619) when users try to send to their HS. Maybe that's enough?

**Comment by lampholder** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/1922197/60524122-e8473200-9ce3-11e9-9e9f-4c873125d549.png">
LGTM

**Comment by lampholder** [comment]
(there are actually two _different_ thumbsups there 🤦‍♂ but this is a demonstration of it working properly)
