### ISSUE TITLE
Long displaynames should be cut off

### ISSUE THREAD

**Issue by f0x52** [vector-im/riot-web#9699]
Super long displaynames should be cut off (with ellipsis) in various places, such as that user's messages, their join/leave events, typing notifications and in the sidebar when selected.

as seen here with someone in Matrix HQ
![image](https://user-images.githubusercontent.com/23422690/57647088-63cd1280-75c2-11e9-897b-8f1986925c4e.png)

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5739
