### ISSUE TITLE
[Question] Running on Dat Protocol

### ISSUE THREAD

**Issue by DaniellMesquita** [vector-im/riot-web#9706]
Is it possible to run on Dat Protocol with its decentralized database, while yet communicating with Matrix servers?

**Comment by turt2live** [comment]
If it works with Matrix, yes. Riot is not a multi-protocol client and only supports Matrix. Matrix on the other hand, can bridge to other networks where needed to provide you with access to other places.

Questions are best asked in [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org) as they normally get lost in the issue list.
