### ISSUE TITLE
[Feature] Status

### ISSUE THREAD

**Issue by DaniellMesquita** [vector-im/riot-web#9707]
- [ ] Online
- [ ] Offline
- [ ] Away
- [ ] Busy

**Comment by turt2live** [comment]
Presence is already supported. Custom away messages are set aside for https://github.com/vector-im/riot-web/issues/478

**Comment by DaniellMesquita** [comment]
Isn't easy to set presence:
![image](https://user-images.githubusercontent.com/6765277/57660340-88be8700-75bc-11e9-9a0d-6c2927a5e02c.png)

**Comment by turt2live** [comment]
https://github.com/vector-im/riot-web/issues/478 and related issues cover that

**Comment by DaniellMesquita** [comment]
Also planned to show status on a private conversation?

**Comment by turt2live** [comment]
yes
