### ISSUE TITLE
Message order is broken 

### ISSUE THREAD

**Issue by procopsamuraev** [vector-im/riot-web#9708]
### Description
Old message will be stick as last one.   See on screenshot. New messages will be behind old one.
### Steps to reproduce
Didnt find how to reproduce. Happens occasionally with different users.
But noticed that stacked messages doesn't have next header:
  ```
"type": "m.room.message",
  "sender": "@redacted",
  "content": {
    "msgtype": "m.text",
    "body": "sss"
  },
```
so stacked messages will only contain this (if see source on the client)

```
{
  "event_id": "$1557818289109xijSn:im.example.com",
  "user_id": "@nurlena.jonid:im.example.com",
  "room_id": "!GfVDDBCThRXtnwlMtq:im.example.com",
  "type": "m.room.message",
  "origin_server_ts": 1557818289216,
  "content": {
    "msgtype": "m.text",
    "body": "i just bought it today"
  }
}
```

Log: sent/not sent
![riot-message](https://user-images.githubusercontent.com/48545058/57680555-78f87e80-7660-11e9-8f38-0067b28aa1ce.png)

### Version information

**Platform**: Desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.1.0

**Comment by jryans** [comment]
Thanks for the report, and I agree this is quite unfortunate. 😭 I believe this is the same issue as https://github.com/vector-im/riot-web/issues/9443, so I'll close this as a duplicate, but please reopen if it appears to be distinct.
