### ISSUE TITLE
Read markers are being sent for events that haven't been sent yet

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9711]
Just noticed this in the network tab:

![image](https://user-images.githubusercontent.com/2072976/57696011-ad137580-7647-11e9-8702-833626d2c144.png)

![image](https://user-images.githubusercontent.com/2072976/57696006-a7b62b00-7647-11e9-933c-02c85fb23730.png)

It's not causing an issue, but seems like a race is happening somewhere.

**Comment by Half-Shot** [comment]
Tried to reproduce this again, but was unable to. Maybe it got fixed.

**Comment by jryans** [comment]
Okay, let's close for now until we see it again. Thanks for the update!
