### ISSUE TITLE
Aggregations: Show message action bar tooltips on hover

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9716]
Add an in-app tooltip on hover to show:

- Emoji group "Agree or Disagree"
- Emoji group "Like or Dislike"
- "Add Reaction"
- "Reply"
- "Edit"
- "More"

**Comment by nadonomy** [comment]
Possibly useful: https://codyhouse.co/blog/post/css-rounded-triangles-with-clip-path

**Comment by t3chguy** [comment]
outdated
