### ISSUE TITLE
a typo in i18n/zh_Hant

### ISSUE THREAD

**Issue by kingwap99** [vector-im/riot-web#9718]
perl -i -pe's/訪克/訪客/g' i18n/zh_Hant.34badf6.json
Please run the code above the fix that typo, thanks .

and below three, I think it's a better translation in Taiwan. 

perl -i -pe's/（選擇性）/(可省略)/g' i18n/zh_Hant.34badf6.json
perl -i -pe's/收藏夾/我的最愛/g' i18n/zh_Hant.34badf6.json
perl -i -pe's/夥伴/好友/g' i18n/zh_Hant.34badf6.json

**Comment by turt2live** [comment]
Although the weblate instance is down right now (https://github.com/vector-im/riot-web/issues/9585), these are contributed through that interface. See https://github.com/vector-im/riot-web/blob/develop/docs/translating.md for more details.
