### ISSUE TITLE
Username validation doesn't tell you that you need *lowercase* letters

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9720]
![image](https://user-images.githubusercontent.com/1190097/57724618-72f6a380-7648-11e9-9ce6-c556ad00c206.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/79055278-b2a48180-7c43-11ea-859a-63999d91a52e.png)

this seems to now be a thing
