### ISSUE TITLE
Show who reacted to what in tooltip on hover

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9722]
(Internal) Zeplin link: https://zpl.io/a3e7okQ

<img width="906" alt="Screenshot 2019-05-14 at 21 06 33" src="https://user-images.githubusercontent.com/4626865/57728588-2f258d80-768c-11e9-99cd-0dab0e57e67e.png">

- Sorted in ascending time order of reaction
- Clip at 6 names and show "& N more"

Tooltip colours:
- Background: Inherit from left-left-panel per theme
- 'Name': White in light, message body (#EDF3FF) in dark
- 'Reacted with': 70% opacity of the above

**Comment by turt2live** [comment]
> How many names to clip at, and if we do, whether we display '& x more'

ftr I like github's approach of showing 10 and the "& more":
![image](https://user-images.githubusercontent.com/1190097/57731030-0040f480-7657-11e9-837c-b6fbfe46391a.png)

**Comment by Half-Shot** [comment]
Note that it would be cool to find out the full list of people for each reaction, but probably something for the future. I guess this could be part of the context menu, or a button in the event source to provide a long list of names.

**Comment by jryans** [comment]
> the full list of people for each reaction

I believe https://github.com/vector-im/riot-web/issues/9723 covers that via modal, unless you have something else in mind.

**Comment by Half-Shot** [comment]
Oh yes, that's perfect. Ignore me :)
