### ISSUE TITLE
Add support for reading markdown tables

### ISSUE THREAD

**Issue by tmdoit** [vector-im/riot-web#9735]
Format markdown table like in Mattermost clients: https://docs.mattermost.com/help/messaging/formatting-text.html#tables

**Comment by t3chguy** [comment]
riot-web does support tables just fine, the markdown flavour of choice does not support entering them though, feel free to open an issue with commonmark re tables though, or upvote https://github.com/vector-im/riot-web/issues/5940 if you want to switch to GFM which supports them.

**Comment by dessalines** [comment]
This standard markdown table syntax doesn't seem to work in element:

```
a | table
--- | ---
a | row
```

**Comment by hex-m** [comment]
You can send a table by using the CommonMark HTML feature.
```
/html <table>
  <thead>
    <tr>
      <th>Column 1</th>
      <th>Column 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Lorem</td>
      <td>Ipsum</td>
    </tr>
    <tr>
      <td>et</td>
      <td>dolor</td>
    </tr>
  </tbody>
</table>
```

**Comment by pflegende** [comment]
a workaround to use easy markdown-constructed tables in matrix-element

# md2html for use table2matrix
based on https://github.com/element-hq/element-web/issues/9735#issuecomment-1048557103

use this as bookmarklet (more inside a short [instruction](https://codeberg.org/pflegende/2konsolidate/src/branch/master/md2htm.md)):
https://codeberg.org/pflegende/2konsolidate/src/branch/master/md2htmx.js

CU
😊👋
