### ISSUE TITLE
Message editing composer - if you autocomplete at the end of a line, then press down to choose the autocomplete item, you also move the cursor to the line below.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9738]
![Screen Recording 2019-05-16 at 11 27 21 2019-05-16 11_43_18](https://user-images.githubusercontent.com/1922197/57848138-1de59980-77d0-11e9-9fdd-4a61b4f4a641.gif)

Sorry for the agonisingly slow gif.

**Comment by bwindels** [comment]
Matthew hit this while entering a newline in the middle of a line.

**Comment by bwindels** [comment]
The other bug is a bit more specific, so closing this as a dupe of https://github.com/vector-im/riot-web/issues/9741
