### ISSUE TITLE
Add focus border to edit composer

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9739]
If you hit tab whilst a selection is active on the new composer, keyboard focus heads off somewhere else (where) but there is no visual cue this has happened at all?  Same if no selection is active, but at least the cursor disappears.

**Comment by bwindels** [comment]
hmm, I have seen this, but now can't repro anymore ...

**Comment by bwindels** [comment]
As for the confused state, can't repro anymore as mentioned, but perhaps the editor should have a focus border of some sort @nadonomy ?

**Comment by bwindels** [comment]
![image](https://user-images.githubusercontent.com/274386/58476104-5a55b580-813f-11e9-8462-871368857baf.png)

Nad: this is what 50% opacity looks like, any more and it's visually distracting

**Comment by lampholder** [comment]
I'm bumping this from phase:1 to phase:2 because:
- phase 1 was essentially MVP, and this isn't MVP
- we've completed phase 1, and this wasn't in it 😄 

We do need to have a separate chat (for this and reactions) agreeing exactly what phase 2 comprised and its anticipated delivery date
