### ISSUE TITLE
E: The repository 'https://packages.riot.im/debian helium Release' does not have a Release file

### ISSUE THREAD

**Issue by ecofintech** [vector-im/riot-web#9742]
Trying to install riot desktop I get this error:

E: The repository 'https://packages.riot.im/debian helium Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Thanks

**Comment by t3chguy** [comment]
that's not ui/ux at all, nor is it a bug, I can't find reference to "debian helium" anywhere.

Except https://www.bunsenlabs.org/
Which calls itself helium but is actually based on Debian 9 "stretch"
So the repository should be

`https://packages.riot.im/debian stretch Release`

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/57850997-5c328700-77d7-11e9-90c6-1d6759c18c01.png)
