### ISSUE TITLE
Interacting with buttons on messages breaks keyboard input

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9744]
Composer focus is lost, so when sending reactions etc you need to click on the composer again to type.

**Comment by bwindels** [comment]
So, while editing, you click a reactions button (which are now hidden for the same message since this got filed) and then want to continue typing?

Probably missing something, but if you click outside of the editor, or any text field, wouldn't you expect the text field to lose focus?

**Comment by nadonomy** [comment]
> while editing

Not while editing, just in general use. I.e. Type/send a message -> Send a reaction -> Keyboard no longer inputs until you click on the composer.

**Comment by jryans** [comment]
Slack and Discord appear to do what @nadonomy is suggesting here. The composer is allowed to unfocus when you take action elsewhere on the page (clicking, reacting, etc.), but when you press a character (assuming it doesn't trigger an action elsewhere), the composer is focused and the character is added.

**Comment by bwindels** [comment]
Right, I see. Not sure the feature:* labels are appropriate though, as this was already the case before we started working on edits and reactions?

**Comment by jryans** [comment]
Well, I suppose it's bound to come up more after reactions and edits, since it's more likely that people will have moved their focus away from the composer (by clicking those buttons). We should probably chat in reactions-dev about whether to treat it as part of the project.

**Comment by lampholder** [comment]
Bumping to phase:3 to keep phase:2 as tightly scoped as possible
