### ISSUE TITLE
Read Receipts, Read Markers, Notifications don't behave well with reactions and edits

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9745]
@jryans has [analysed](https://docs.google.com/document/d/196pPSDKbuwjpjQymAsKUFyCjTlnS6hFy-gYjV77cSK8/edit) in depth, and here are the key changes to make right away:

* [x] [When sending read receipts, consider these relations as displayed when received and advance our read receipt past them so that any possible notifications are marked as read](https://github.com/matrix-org/matrix-react-sdk/pull/3059)
* [x] [When displaying read receipts, they should be “rewound” back to the last visible event if set to a hidden event ID](https://github.com/matrix-org/matrix-react-sdk/pull/3056)

Future work:

* [Message Editing: Change default push rules to not send notifications for edits](https://github.com/vector-im/riot-web/issues/9881)
* [Aggregations: Tweak read marker advancing behavior](https://github.com/vector-im/riot-web/issues/9889)

**Comment by turt2live** [comment]
Shouldn't these be using custom event types that don't trigger notifications in the first place?

**Comment by bwindels** [comment]
> Shouldn't these be using custom event types that don't trigger notifications in the first place?

I *thought* this was also a problem for `m.reaction` events, not 100% sure though. Also, not sure what an edit would look like if it's not a `m.room.message`...

**Comment by turt2live** [comment]
oh right, edits are part of the problem. Nevermind that then.

**Comment by uhoreg** [comment]
see also https://github.com/vector-im/riot-web/issues/3511 (which was a similar issue, but for redactions)

**Comment by jryans** [comment]
I have attempted to [analyse](https://docs.google.com/document/d/196pPSDKbuwjpjQymAsKUFyCjTlnS6hFy-gYjV77cSK8/edit) the various issues at play here. I'll update the original comment here to cover the most critical changes we need to make and open additional issues for follow up work.

**Comment by Valodim** [comment]
I was surprised about the small amount of activity on this issue: Reactions are beginning to pop up here and there from folks who enable the feature in labs, and this causes inexplicably incorrect unread markers for everyone else (although thankfully at least they don't trigger actual system notifications on riot-android).

Unreliable unread markers have a potential to be *extremely* disruptive to the overall user experience. Please don't underestimate this as a source of frustration for users of (even slightly) outdated riot versions.

**Comment by ara4n** [comment]
if you follow the link in the previous comment you’ll see the activity switched over to a googledoc. this issue is the main pending issue right now with reactions, and as such is being actively worked on, and at top prio

**Comment by Valodim** [comment]
Great to hear, that clears up my worries! Thanks for your work, really looking forward to this feature :+1:

**Comment by lampholder** [comment]
Popping a phase:1 label on this to represent that its resolution blocks the delivery of the MVP

**Comment by jryans** [comment]
The critical bugs in this area which led to stuck notifications, etc. _should_ now be fixed on develop (https://github.com/matrix-org/matrix-react-sdk/pull/3056, https://github.com/matrix-org/matrix-react-sdk/pull/3059). 

If you are still seeing issues related to this, please open a new issue so we can investigate separately.
