### ISSUE TITLE
Message editing: Keyboard shortcuts

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9751]
- [Up] should edit the last message sent
- Should preserve the current interaction used to cycle through messages; first [Up] moves the caret, second up moves to the next message
- Replaces the current interaction of paginating through sent message history in main composer by default, we're currently not confident whether we'll allow users to enable the previous functionality in Settings, to be resolved by polling #riot-dev

**Comment by bwindels** [comment]
Oops, I tracked this in https://github.com/vector-im/riot-web/issues/9832, which is closed now as this is implemented.
