### ISSUE TITLE
Reactions: Update quick reactions

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9753]
<img width="751" alt="Screenshot 2019-05-17 at 13 56 04" src="https://user-images.githubusercontent.com/4626865/57930722-9d499a80-78ae-11e9-831b-7f6d871fb486.png">

- [x] [Add new interactive tooltip style](https://github.com/matrix-org/matrix-react-sdk/pull/3131)
- [x] [Update quick reactions, abandoning previous Like/Dislike & Agree/Disagree toggle mechanic](https://github.com/matrix-org/matrix-react-sdk/pull/3138)
- [x] [Hovering over a reaction increases its scale](https://github.com/matrix-org/matrix-react-sdk/pull/3138)
- [x] [Hovering a reaction shows its label and short code at the bottom of the tooltip](https://github.com/matrix-org/matrix-react-sdk/pull/3138)
- [x] [Reactions already sent should have a reduced alpha, where clicking it again will redact](https://github.com/matrix-org/matrix-react-sdk/pull/3138)
- [x] [Ensure that the tooltip doesn't dismiss too aggressively when mousing between the action bar and tooltip](https://github.com/matrix-org/matrix-react-sdk/pull/3137) (https://atomiks.github.io/tippyjs/ is worth benchmarking, and possibly using, along with Facebook's Like -> Hover -> Reaction interaction)

Before dev, we should discuss if we want to execute on https://github.com/vector-im/riot-web/issues/9483 first, in case this tooltip is redundant after dogfooding the emoji picker with prominent quick reactions. We should try just revealing the emoji picker on hover.

Once emoji picker exists (https://github.com/vector-im/riot-web/issues/9483):

- Clicking (🙂+) reveals the emoji picker
- Clicking 'View all' reveals the emoji picker

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/146)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2459)

**Comment by jryans** [comment]
Should the tooltip appear when hovering or clicking (🙂+)? I am guessing on hover based on the Tippy.js and Facebook interaction styles you are referencing.

**Comment by nadonomy** [comment]
> * Should the tooltip appear when hovering or clicking (🙂+)? I am guessing on hover based on the Tippy.js and Facebook interaction styles you are referencing.

Yes please. Hover for easier discoverability.

> What should the tooltip look like in dark theme? (I see it does appear on the unified palette, but seems to have the same color as the timeline...)

Will check in detail soon and get back to you!
