### ISSUE TITLE
Failed reaction events show 'message not sent' error

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9755]
I was spamming thumbs on a message and then it popped up, I guess it shouldn't do that

**Comment by jryans** [comment]
We haven't really defined how error handling should work for reactions, so maybe we can use this as chance to do so.

**Comment by jryans** [comment]
@nadonomy / @lampholder, should reactions show error messages in the same ways as messages do, or should something else happen?

**Comment by nadonomy** [comment]
> @nadonomy / @lampholder, should reactions show error messages in the same ways as messages do, or should something else happen?

Great question. Will message you on Riot to ensure we have a shared understanding of what happens with messages today to figure it out from there.

**Comment by jryans** [comment]
Let's consider this a duplicate of https://github.com/vector-im/riot-web/issues/9692, where we plan to do something about reaction errors generally.
