### ISSUE TITLE
New roomdirectory layout mangles emojis in implicit room names somehow

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#976]
<img width="315" alt="screen shot 2016-02-21 at 10 36 22" src="https://cloud.githubusercontent.com/assets/1294269/13202139/175afda8-d887-11e5-9e0c-356574e2bddd.png">

**Comment by ara4n** [comment]
related to #990 perhaps

**Comment by ara4n** [comment]
...and the letter in the RoomAvatar gets entirely confused.

**Comment by t3chguy** [comment]
This is fixed as far as I can test
