### ISSUE TITLE
Provisioning IRC bridge via Scalar fails due to failure to fetch channels ops

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#9762]
### Description

Scalar fails to fetch the channel ops from the IRC channels due to a timeout. This makes provisioning a new bridge impossible.

![Selection_160](https://user-images.githubusercontent.com/1174866/57981906-948bcc80-7a46-11e9-9498-bfdb996504d4.png)

### Steps to reproduce

Try to provision a new bridge for a FreeNode channel with an opped user.

After typing channel name, spinner indicates Scalar tries to fetch channel ops. It fails after a while with error in screenshot.

```
curl 'https://scalar.vector.im/api/bridges/irc/_matrix/provision/querylink?rid=*************&scalar_token=***************&v=1.1' 
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0' 
    -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' --compressed 
    -H 'content-type: application/json' -H 'DNT: 1' -H 'Connection: keep-alive' 
    -H 'Referer: https://scalar.vector.im/?scalar_token=******************&room_id=!vRAZWcUKzsmhTbtjgK%3Afeneas.org&room_name=Federated%20web%20social%20news&theme=dark' 
    -H 'Cookie: <redacted>' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' 
    -H 'TE: Trailers' 
    --data '{"remote_room_channel":"#feneas-social","remote_room_server":"chat.freenode.net"}'
```

Fails with:

```
HTTP/2.0 504 Gateway Timeout
date: Sun, 19 May 2019 12:03:39 GMT
content-type: text/html; charset=UTF-8
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: cf_use_ob=0; path=/; expires=Sun, 19-May-19 12:04:09 GMT
expires: Thu, 01 Jan 1970 00:00:01 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma: no-cache
server: cloudflare
cf-ray: 4d95ec52dc245b13-HEL
X-Firefox-Spdy: h2
```

**Comment by Half-Shot** [comment]
Looks like `2019-05-20 08:00:05 WARN:Provisioner Could not case map #anothermxtest - BridgedClient has no IRC client`

**Comment by Half-Shot** [comment]
So this bug was caused by the bridge's bot irc client being disconnected, despite being connected and the result was that these operations were not completing. I don't know why the disconnection wasn't detected though.

**Comment by abbec** [comment]
I also get this exact issue, what do you mean with the above comment? Is there anything I can do to try and resolve?

**Comment by abbec** [comment]
This is the response I get:


Error 504 Ray ID: 4de1edbe6db78671 • 2019-05-28 17:26:35 UTC
Gateway time-out
You
Browser
Working
Stockholm
Cloudflare
Working
scalar.vector.im
Host
Error
What happened?

The web server reported a gateway time-out error.
What can I do?

Please try again in a few minutes.

Cloudflare Ray ID: 4de1edbe6db78671 • Your IP: 94.255.216.200 • Performance & security by Cloudflare

**Comment by jaywink** [comment]
This has been resolved for now, thanks everyone involved.

**Comment by tgr** [comment]
The error I get now is "Failed to get operators." with the response body being `{"message":"Bridge returned HTTP 500 Internal Server Error: Failed to get operators for channel #wmhack (err_needreggednick)"}` I guess the bot's IRC client is operational but not logged in?

**Comment by jaywink** [comment]
Hi @tgr 

You're essentially seeing this: https://github.com/matrix-org/matrix-appservice-irc/issues/447 .. currently a channel cannot be in +r mode when registering the bridge. The workaround is to remove +r, provision the bridge and then add +r back to the channel.

This does mean Matrix users need to register their nick with freenode, but that is a good thing to do anyway.
