### ISSUE TITLE
Message Editing: Handle error codes when sending

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9772]
After chatting with @nadonomy about reactions / edits errors in general, we came up with:

* Use same e2e (!) icon to decorate messages with an error
  * Clicking on it reveals a context menu with any of:
    * Resend reactions
    * Resend edit
    * Encryption information
* Users will see the message status bar explaining the error (network, rate limited, unverified, etc.)
* Irrespective of what colours e2e uses (as its subject to change), unsent edit/reactions should always decorate red

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/196)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2511)

**Comment by bwindels** [comment]
Dupe of https://github.com/vector-im/riot-web/issues/9692
