### ISSUE TITLE
"Couldn't load page" for home.html template

### ISSUE THREAD

**Issue by the-moog** [vector-im/riot-web#9776]
### Description

On a self hosted server users get "Couldn't Load Page" on login.

### Steps to reproduce

- Install riot-web
- Login

Describe how what happens differs from what you expected.

The user should not get an error as this creates confusion.

If the home.html is missing then an internal template should be used, alternately a basic home.html should be provided in the distribution with instruction on how to customise.

Log: sent/not sent?    Not necessary

### Version information

- web

For the web app:

- Firefox
- Win10
- private server Riot 1.0.1

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by jryans** [comment]
Can you include the `config.json` for your Riot install?

**Comment by the-moog** [comment]
contents of config.json:
Nothing that different from stock.
I note that the line  "welcomePageUrl": "home.html", was removed from sample since first install. Though home.html seems to be a default anyway (in that that's what Apache says is 404)

[config.json.txt](https://github.com/vector-im/riot-web/files/3201715/config.json.txt)

**Comment by jryans** [comment]
So have you removed the line `"welcomePageUrl": "home.html"` from your own config? Maybe Riot is caching it? I would not expect Riot to show this error to the user unless the config has `welcomePageUrl` set to some page that 404s.

**Comment by the-moog** [comment]
welcomePageUrl is not set in my config but is being requested by the browser (and hence Riot).  Where could it be cached?  Restarting the webserver does not change this.
I will try adding welcomePageUrl but setting it to an empty string.
I tried to find it in the source tree but it's unreadable. Is there a repos of non minified Riot code?

**Comment by jryans** [comment]
I would suggest checking the config.json loaded by the browser in their network tools to see what config it actually receives.

Here's a [pointer](https://github.com/matrix-org/matrix-react-sdk/blob/19edc5c5a4dd3f807dae2d15e0476ef105ca9344/src/utils/pages.js#L17) to code that reads this config.

**Comment by the-moog** [comment]
Ok, so the browser has cached an ancient options.json.
Setting disable cache in the browser debugger solves the issue.

So the bug is that the options.json file should be sent by Riot as nocache.

**Comment by jryans** [comment]
Cache settings like that are handled by headers on your web server. I don't believe any changes are needed in Riot itself for this issue.

**Comment by ara4n** [comment]
@jryans - perhaps we should include a cachebuster when loading config.json though to prevent this sort of thing? after all, we got bit on it after the rebuilt on riot.im itself...

**Comment by the-moog** [comment]
I disagree.  Forcing the cache behaviour for config.json is not portable between webservers.   e.g. In apache it requires specific configuration or .htaccess file but that same config won't work on nginx.  Riot would therefore have to ship with special configuration instructions for every supported webserver.  

Surely the better solution would be to change the getconfig.js to apply a request header with no-cache, no-store set for the request object.  This also handles per-site .json files and is server portable.

**Comment by jryans** [comment]
Okay, I have filed https://github.com/vector-im/riot-web/issues/9784 to consider cache busting `config.json`.
