### ISSUE TITLE
Google Docs Viewer widget freezes Riot

### ISSUE THREAD

**Issue by wonx** [vector-im/riot-web#9778]
### Description

The Google Docs Viewer widget freezes the whole Riot desktop app. 

I am new to this app, so I have not used it extensively, but another user in a chat-room added the google docs viewer widged, and when I expanded it and allowed it, the whole Riot app froze. I couldn't click anywhere. Restarting the app did not work. I had to delete all configuration files and log in again. 

### Steps to reproduce

- Add a google docs document using the Google Docs Viewer widget
- Expand the widget
- Allow permissions for said widget.

The document should load in the widged. Instead, a dark-grey background with a Loading... text appears, and it never loads. Riot then uses 100% of the CPU.

### Version information

- **Platform**: Desktop app in Ubuntu 18.04.
Versió de matrix-react-sdk: <local>
Versió de riot-web: 1.1.2
Versió d'olm: 3.1.0

**Comment by jryans** [comment]
@jaywink, is something wrong with the Docs widget?

**Comment by bmoroz82** [comment]
Similar/same issue observed on Windows x64 desktop app as well various browsers (Firefox, Chrome).

Platform: Desktop Windows 10
Version: 1.1.2

**Comment by jaywink** [comment]
Reproduced as well, Ubuntu 18.10, Riot web desktop 1.1.2 and also web. Thanks for reporting, needs investigating further.

**Comment by bmoroz82** [comment]
Status update?

**Comment by jaywink** [comment]
@bmoroz82 Unfortunately nothing to update this on yet.

@jryans any ideas on how to debug this from Riot client side? Posted some console logs I could rip out: https://github.com/matrix-org/riot-web-rageshakes/issues/1575

The last bits of interest are:

```
Widget reported content loaded for googledocs_@jaywink:federator.dev_1558605231524 rageshake.js:107
Attempt to set a forbidden header was denied: Connection 1938954755-client_js_prod_kix_core.js:248:10
```

**Comment by jryans** [comment]
After a bit of investigation, it appears there is some kind of bad behaviour occurring inside the Google Docs code itself.

So far, I have noticed that Google Docs is trying to send some kind of error that is triggered on `mousemove` events, so once you start moving your mouse inside the widget, it very rapidly builds up errors and prevents other content from doing work.

Riot Desktop is not required, as it's easy to reproduce this in Firefox and Chrome with Riot Web.

I'll keep looking at this tomorrow, but so far I am guessing it will be hard for Riot to make a change to fix this.

**Comment by jryans** [comment]
Here are some experiments I've done to try to work out a possible fix:

Trial | Result
-----|-------
Google Docs widget in Riot | Freezes when mouse enters the widget
`iframe` to doc with Riot's `allow` and `sandbox` (no widget wrapper) | Working
`iframe` to doc with only `allowfullscreen` | Working

So, it seems like something about the Scalar widget wrapper triggers the Google Docs code to enter a runaway code path on `mousemove`.

**Comment by jryans** [comment]
At the moment, I can't really tell _what_ about the Scalar widget wrapper is causing this to happen. We may need to disable Google Docs widgets until this can be fixed. 😞

**Comment by bmoroz82** [comment]
Currently working in Opera browser for me (wasn't before) on at least one machine. However, seeing 'Blocked script ... because the document's frame is sandboxed and the 'allow-scripts' permission is not set.' and 'Refused to display ... in a frame because it set 'X-Frame-Options' to 'deny'.' in developer console.

**Comment by jryans** [comment]
> However, seeing 'Blocked script ... because the document's frame is sandboxed and the 'allow-scripts' permission is not set.'

Hmm, that's a bit surprising, since we do have `allow-scripts` set on the frame in Riot... Perhaps this message is from some hidden internal iframe. In any case, the main document is definitely able to run scripts.

**Comment by bmoroz82** [comment]
Still getting reports from other team members that the desktop app freezes and their web browsers will open the document but the "document isn't loaded completely" (Mac OS Chrome). So it appears to be just me...

**Comment by jryans** [comment]
It's been quite easy for me to reproduce in multiple browsers, so it's not just you. Unfortunately for now we intend to disable the Google Docs widget, as it's impacting Riot generally. Hopefully we can bring it back in future if a fix can be spotted.

I'll leave this open for now until the change is deployed.

**Comment by jaywink** [comment]
Change has been deployed, Google Docs widget has been removed from Scalar.

Note that existing widget instances are not affected. Since room widgets are stored in room state, there is nothing we can do to force remove the widgets and it would probably be wrong to do anyway. 

I'll open an issue in the Scalar repository to track the future comeback once there is bandwidth to follow up on the freezing issue.
