### ISSUE TITLE
Broken emoji in reaction tooltip

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9782]
On develop:

<img width="357" alt="Screenshot 2019-05-21 at 12 34 51" src="https://user-images.githubusercontent.com/4626865/58092885-1d307700-7bc5-11e9-97cf-5f9d0c1f665e.png">

**Comment by bwindels** [comment]
Chrome on macOS? Looks like what's being discussed in https://github.com/vector-im/riot-web/issues/9651

**Comment by bwindels** [comment]
wait, emojis seem to render ok, but where the ascii shortcode should go, it's rendering a broken emoji?

**Comment by bwindels** [comment]
ReactionsRowButtonTooltip falls back to the emoji when a shortcode was not found, so it might be failing to render the emoji because there is an explicit color set on the element.

**Comment by bwindels** [comment]
Also emojibase doesn't seem to have a short code for 👍️

**Comment by jryans** [comment]
> ReactionsRowButtonTooltip falls back to the emoji when a shortcode was not found, so it might be failing to render the emoji because there is an explicit color set on the element.

@nadonomy, assuming the emoji was actually appearing, is this a good fallback when we don't have a shortcode, or would you prefer we just don't say "reacted with X" at all?

**Comment by nadonomy** [comment]
> > ReactionsRowButtonTooltip falls back to the emoji when a shortcode was not found, so it might be failing to render the emoji because there is an explicit color set on the element.
> 
> @nadonomy, assuming the emoji was actually appearing, is this a good fallback when we don't have a shortcode, or would you prefer we just don't say "reacted with X" at all?

The latter sounds good to me. The user can infer everything else contextually.

**Comment by bwindels** [comment]
ftr, EmojiBase actually does have a shortcode for :+1:, so we're probably doing something wrong ...
```
{
    "annotation": "thumbs up",
    "group": 1,
    "hexcode": "1F44D",
    "order": 272,
    "shortcodes": [
      "thumbsup",
      "+1",
      "yes"
    ],
    "tags": [
      "+1",
      "hand",
      "thumb",
      "up"
    ],
    "unicode": "👍️",
    "skins": [ ... ]
  },
```

**Comment by ara4n** [comment]
the shortcode is 'thumbsup' (the current code only considers the first thumbsup).
the reason the emoji isn't showing is something else.

**Comment by ara4n** [comment]
nad: which version of Chrome & macOS is this?

**Comment by nadonomy** [comment]
> nad: which version of Chrome & macOS is this?

Chrome Version 74.0.3729.157 (Official Build) (64-bit)
macOS 10.14 (18A391)

**Comment by jryans** [comment]
Filed separate issue about [missing shortcodes](https://github.com/vector-im/riot-web/issues/9785) and [hiding reacted with](https://github.com/vector-im/riot-web/issues/9786).

Let's keep this issue focused on the missing emoji glyphs.

**Comment by bwindels** [comment]
Can @nadonomy or @jryans perhaps also test emoji support with the riot dark skin on macOS? Wondering if the dark background in the tooltip broke rendering somehow...

**Comment by nadonomy** [comment]
> Can @nadonomy or @jryans perhaps also test emoji support with the riot dark skin on macOS? Wondering if the dark background in the tooltip broke rendering somehow...

Sure! Seems to behave the same as the light theme:

<img width="463" alt="Screenshot 2019-05-21 at 14 58 56" src="https://user-images.githubusercontent.com/4626865/58102318-0267fd80-7bd9-11e9-943b-d343a1c562cc.png">

**Comment by jryans** [comment]
I think we can treat this as fixed for now...? Only emoji in tooltips were affected, and we no longer show them there after https://github.com/matrix-org/matrix-react-sdk/pull/3003.
