### ISSUE TITLE
Missing shortcodes for thumbs up / down reactions

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9785]
EmojiBase actually does have a shortcode for :+1:, so we're probably doing something wrong ...
```
{
    "annotation": "thumbs up",
    "group": 1,
    "hexcode": "1F44D",
    "order": 272,
    "shortcodes": [
      "thumbsup",
      "+1",
      "yes"
    ],
    "tags": [
      "+1",
      "hand",
      "thumb",
      "up"
    ],
    "unicode": "👍️",
    "skins": [ ... ]
  },
```

_Originally posted by @bwindels in https://github.com/vector-im/riot-web/issues/9782#issuecomment-494367406_

**Comment by jryans** [comment]
The issue seems to be that Riot is currently using U+1F44D for thumbs up, which appears to be correct for a thumbs up without a skin tone. When searching Emojibase for the unicode value, their `unicode` value for this emoji seems to include an additional character, maybe some kind of null skin tone...?

**Comment by bwindels** [comment]
I guess a solution would be to look into the skins property as well then ...

**Comment by jryans** [comment]
Okay, the extra part in Emojibase is U+FE0F, the [variation selector](https://unicode-table.com/en/FE0F/). So, just need to improve our searching to account for cases like this.

**Comment by anoadragon453** [comment]
Is this fix simple? It's still quite weird to see shortcodes for only some reactions:

![image](https://user-images.githubusercontent.com/1342360/60338410-cd9c5280-999d-11e9-865e-7321520dd115.png)

![image](https://user-images.githubusercontent.com/1342360/60338412-cffeac80-999d-11e9-9446-25a00dd4cb8b.png)
