### ISSUE TITLE
Reactions/edits not applied live when using the labs "show hidden events" option

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9791]
switching rooms and back fixes the counts

**Comment by jryans** [comment]
@turt2live Have you seen this with both reactions and edits, or just reactions only?

I have seen a [related thing](https://github.com/vector-im/riot-web/issues/9954) with reactions which happens with and without hidden events. Is this issue a duplicate of that, or is it really something that only happens with hidden events?

**Comment by turt2live** [comment]
I'm inclined to call this a duplicate of https://github.com/vector-im/riot-web/issues/9954 until I can prove otherwise
