### ISSUE TITLE
Don't allow moderators to edit anyones messages

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9793]
We've discussed making it possible for moderators to edit anyones message in future. Although the plan would be to expose mod edits in both the  _(edited)_ label  and the 'View Edits' modal, there's something that fundamentally rubs me the wrong way about the platform letting some users put other words into other users mouths.

The established precedent for this is traditional forum software. However, we should consider taking inspiration from more modern discussion platforms like Reddit where moderators can mute/redact comments, but not edit them.

It's important that the matrix spec/protocol is able to support mods being able to edit messages, however we can choose not to expose this in Riot.

If we decide for this, we should also consider filing an issue or expanding https://github.com/vector-im/riot-web/issues/9792 to include notifications for being moderated. 

After figuring out how to move forward, we should track the conclusions in riot-meta to then feed work into all platforms.

**Comment by bwindels** [comment]
> Presently, it's possible for moderators to edit anyones message.

This should not be possible at the moment. Where are you seeing this?

**Comment by nadonomy** [comment]
> > Presently, it's possible for moderators to edit anyones message.
> 
> This should not be possible at the moment. Where are you seeing this?

Ah thanks. Edited the parent issue comment to better reflect the current functionality. Will leave this issue open for discussion when we visit this in future.

**Comment by anoadragon453** [comment]
I would like to keep the functionality for bot-related reasons, but am fine with the functionality not being exposed in Riot.

**Comment by bwindels** [comment]
> I would like to keep the functionality for bot-related reasons, but am fine with the functionality not being exposed in Riot.

AFAIK, eventually we want the power levels to determine who can edit a message. See https://github.com/matrix-org/matrix-doc/pull/1849#discussion_r291955122 and other comments there.

**Comment by babolivier** [comment]
I kinda feel like it's not something we want to keep in Matrix in the long term to allow people to edit other people's messages without their content. It feels really close to impersonation to me. The main argument I'd see would be moderation when a message is breaking a room's rules, and redaction is more than enough for that.
I'd be fine with a bot editing messages on my behalf only if I give it access to my account, otherwise it sounds incredibly intrusive to me.

**Comment by anoadragon453** [comment]
> It's important that the matrix spec/protocol is able to support mods being able to edit messages

I can think of many examples of bots that would be handy. A bot that translates people's messages from one language to another. A bot that removes tracking data from URLs that are posted to a channel. A bot that removes annoying emoji from people's messages.

In addition having multiple accounts with the ability to edit the same content can be wildly useful for all sorts of things inside and outside of chat.

If an admin/mod controls the room, they should be able to manipulate content in it.

Of course we need to be clear about how the message arrived in that state. We need to a) allow people to view message history, and b) be clear without requiring anything more than a glance as to who edited the message last.

**Comment by ara4n** [comment]
From my perspective, we want to support this in the protocol, so long as the edit history is maintained (assuming the edits are not redacted) and the fact that the msg was edited by a given user is made abundantly clear in the UI.  The reasons are:
 * The use case of bridging platforms such as messageboards where it's common for mods to edits msgs (e.g. to add spoiler tags, or to split off offtopic content)
 * Mods can redact messages anyway, which is almost more unpleasant than editing them (especially as it by definition doesn't leave the history behind)
 * Having a mod able to go in and edit out sensitive content (e.g. delete an access_token from someone's message, or add a spoiler tag, or even fix a markup problem) doesn't seem unreasonable.

**Comment by babolivier** [comment]
*NV hat still off*

> From my perspective, we want to support this in the protocol, so long as the edit history is maintained (assuming the edits are not redacted) and the fact that the msg was edited by a given user is made abundantly clear in the UI. The reasons are:
> 
>     * The use case of bridging platforms such as message boards where it's common for mods to edits msgs (e.g. to add spoiler tags, or to split off offtopic content)
> 
>     * Mods can redact messages anyway, which is almost more unpleasant than editing them (especially as it by definition doesn't leave the history behind)
> 
>     * Having a mod able to go in and edit out sensitive content (e.g. delete an access_token from someone's message, or add a spoiler tag, or even fix a markup problem) doesn't seem unreasonable.

Right, I see your point, and I agree that it has some benefits. Though I just can help but think of the potential for abuse and how it has a non-zero probability to cause some mess at some point.

To me, the UI/UX for something like that is hard to get to a point where the information of which part of the message has been written by whom is as clear and obvious to everyone as the fact that the message has been edited (more than just providing edits history, because I don't believe edits histories are read by the majority of users), and _every_ client must get it right here, and the whole thing sounds super complicated and not so realistic to me.

I kinda fear that this might make people afraid to interact in somewhat crowded rooms because it may mean that some mod they don't know can impersonate them to part of the members in the room (because it would make me so). Matrix is particularly attractive to privacy (h)activists and people who want full control over their data and this sounds like a step in the opposite direction to me.

> Mods can redact messages anyway, which is almost more unpleasant than editing them

tbh I'm way more comfortable with someone deleting a message than sticking a statement I have never said or thought under my name.

**Comment by ara4n** [comment]
I see the concern, but surely sticking "Edited by Matthew" at the end of the message (similar to how we have just "Edited" today) is going to stick out like a sore thumb?

**Comment by turt2live** [comment]
(it sticks out pretty obviously on github, which is good)

**Comment by ara4n** [comment]
the fact that github lets mods edit msgs is another example of why you need matrix as a protocol to support the concept, otherwise the impedance mismatch of bridging such threads into matrix is going to be an arbitrary and avoidable pain in the ass.

**Comment by Half-Shot** [comment]
A benefit I think nobody has brought up yet is that you can see toxic moderators in action if malicious edits have the editors name visible. It might actually be useful in red flagging folks that could tie into reputation work later.

**Comment by equinox** [comment]
@babolivier has summarised most of my concerns regarding this, and I think that explicitly giving consent for someone to edit your messages is the best compromise.

If a moderator takes issue with a message you've sent, they already have the options of redacting it or replying to it (which gives people the context of the message), so in essence there's no missing contextual problems to confuse people as to what the moderator is replying to. Which would have maybe been a pro for the ability to allow moderators to edit messages if replies weren't a thing.

**Comment by babolivier** [comment]
*NV hat still off*

> (it sticks out pretty obviously on github, which is good)

I'd say GH's UX is good enough for tech people (or at least people used to VCSs and going through histories), which I assume is github's target, but not necessarily Matrix's. My dad's never going to go through an edit history, and would probably even miss the "edited by" annotation as it's currently implemented in Riot.
Plus I'm not convinced by "others do it so it's good". I already find it intrusive in GitHub (even though I think it applies better to GH's use case than Matrix's (as Matrix is currently mainly used for, that is)).

> A benefit I think nobody has brought up yet is that you can see toxic moderators in action

I'm more in favour of "don't let people cause damage to others" than "let them cause damage and blame them after if someone spots it".

Anyway, I've turned the feature off in Riot and probably won't turn it back while this is still an issue. It really makes the whole edit feature an anti-feature imho.

**Comment by turt2live** [comment]
Ultimately we decided that moderators can't edit other people's messages, though the spec does support it. Closing this as "fixed" given the issue title.

**Comment by chagai95** [comment]
@turt2live is there a ticket which I can upvoted if I'd like to see admins able to edit messages in the future on Element?

**Comment by anoadragon453** [comment]
And if the spec supports it, wouldn't the right thing be for Element web to warn users if it happened?

**Comment by turt2live** [comment]
This is largely a spec issue given the MSC recommends this behaviour and is anticipated to stick around for a while.

Please leave a comment on there: https://github.com/matrix-org/matrix-doc/pull/2676

Locking due to age.
