### ISSUE TITLE
Autocomplete should order based on who was last speaking

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#98]

**Comment by jfrederickson** [comment]
IMO, the userlist should also sort based on last speaker. In my experience, this ordering tends to be more useful than presence-ordering, as lots of things can cause presence ordering, and as a result the userlist shifts around a lot.

But that's just, you know, my opinion, man.

**Comment by uhoreg** [comment]
This should probably have been closed along with #1741, even though it seems to have regressed as per #2685

**Comment by ara4n** [comment]
yeah, this has been ordered by last-speaker for a while, although sometimes breaks as per #2685
