### ISSUE TITLE
Emojis are shifted up slightly

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9800]
### Description

Emojis are now working as of https://github.com/matrix-org/matrix-react-sdk/pull/3008, however it seems to be shifted up a little bit (possibly only on one mode of emoji).

![image](https://user-images.githubusercontent.com/1342360/58167461-e8372980-7c83-11e9-90f2-83dbc04f1df4.png)

![image](https://user-images.githubusercontent.com/1342360/58167480-eec5a100-7c83-11e9-950e-aa3795fc158d.png)

![image](https://user-images.githubusercontent.com/1342360/58167443-dfdeee80-7c83-11e9-9cde-3985d1700357.png)

### Version information

- **Platform**: web
- **Browser**: Chrome  73.0.3683.75
- **OS**: Debian 9.8
- **URL**: riot.im/develop

**Comment by Sorunome** [comment]
Also on archlinux w/ electron

**Comment by jryans** [comment]
Hmm, maybe only an issue with SBIX style? Can you check which emoji font you're loading in the browser's network tab?

**Comment by anoadragon453** [comment]
@jryans TwemojiMozilla-sbix.8082b10.woff2

**Comment by jryans** [comment]
Should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3011. You'll need to have a local emoji font like "Noto Color Emoji" installed.

**Comment by bwindels** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3011 addresses this for now
