### ISSUE TITLE
skin emojis aren't rendered at all with Twemoji in Chrome on Linux

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9801]
Firefox:
![image](https://user-images.githubusercontent.com/274386/58168673-5547c080-7c7e-11e9-9773-42e53a3499fd.png)
Chrome:
![image](https://user-images.githubusercontent.com/274386/58168689-5ed12880-7c7e-11e9-9452-b28030435a75.png)

**Comment by jryans** [comment]
Should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3011. You'll need to have a local emoji font like "Noto Color Emoji" installed.

**Comment by bwindels** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3011 addresses this for now
