### ISSUE TITLE
Breadcrumbs can't be scrolled anymore

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9804]
I don't seem to be able to scroll breadcrumbs anymore using a normal mouse scroll wheel.

- **Platform**: web
- **Browser**: Firefox Nightly 69.0a1 (2019-05-22), Chromium
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Can you still scroll in the timeline? What about settings?

**Comment by anoadragon453** [comment]
Message timeline and settings are fine.

**Comment by turt2live** [comment]
oh, weird. I couldn't reproduce this on a build from ~10 hours ago, but now it's broken. Will take a look.
