### ISSUE TITLE
Wrong Error Message with /me

### ISSUE THREAD

**Issue by kazukyakayashi** [vector-im/riot-web#9805]
Hello

When I do a `/me` in response to a message, Riot displays a wrong error message: **For the moment it is not possible to answer with an emoji**

![Riot](http://pix.toile-libre.org/upload/original/1558539338.jpg)

**Comment by t3chguy** [comment]
This sounds like a mistranslation, it should say "with an emote"

**Comment by jryans** [comment]
Yes, looks like a bad translation. See [the guide](https://github.com/vector-im/riot-web/blob/develop/docs/translating.md) if you'd like to help. I believe [this](https://translate.riot.im/translate/riot-web/matrix-react-sdk/fr/?checksum=977adb0ff31a07b1) is the bad string here.
