### ISSUE TITLE
Scroll-to-bottom icon is missing on FF

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9806]
![image](https://user-images.githubusercontent.com/1342360/58187140-23e6e900-7cae-11e9-9752-5006a221a41d.png)

![image](https://user-images.githubusercontent.com/1342360/58187254-55f84b00-7cae-11e9-9ce2-539474f7a1b0.png)

### Description

The scroll-to-bottom icon seems to be missing. Happens even after a refresh on both light and dark theme.

Possibly related: https://github.com/vector-im/riot-web/issues/9637

Log: sent

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly 69.0a1 (2019-05-22)
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Hmm, puzzling... On Firefox Nightly for macOS, I see the expected appearance:

<img width="90" alt="2019-05-24 at 10 20" src="https://user-images.githubusercontent.com/279572/58317431-a639ef00-7e0d-11e9-8305-b1459237ebb7.png">

**Comment by jryans** [comment]
@anoadragon453, is this still happening for you?

**Comment by anoadragon453** [comment]
Yep, still getting this on latest /develop.

![image](https://user-images.githubusercontent.com/1342360/58319322-98866880-7e11-11e9-8242-f3043126f142.png)

Seems to be related to my ad blocker (uBlock Origin, a very common one).

**Comment by anoadragon453** [comment]
It's due to the following rule: `##div[title="Scroll to bottom of page"]`

In Fanboy's Annoyance List, which is not on by default but I do have enabled.

Adding a `.` to the end of the message prevents it from being hidden ¯\\\_(ツ)\_/¯

**Comment by anoadragon453** [comment]
Or a zero width space: `​`

**Comment by jryans** [comment]
Hmm... I am tempted to say since it's related to a block list, and beyond that a non-default one, that we don't need to make a change in Riot here. If we see more reports of confusion because of this, we can reconsider.
