### ISSUE TITLE
bold emoji sent with markdown disabled get cut off on top due to small line-height

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#9808]

**Comment by jryans** [comment]
Please add browser and OS version details.

**Comment by bwindels** [comment]
it's the markdown-body style setting the line-height to inherit which takes it from .mx_EventTile_line to be 22px ... too many !important declaration.

**Comment by uhoreg** [comment]
Looks like the issue happens due to bold emoji, which causes the `markdown-body` class to be added, which has `line-height: inherit !important`, causing the line height to be too small.
![image](https://user-images.githubusercontent.com/1012976/58189673-f0de2e80-7c88-11e9-999e-3dbbcc1f606e.png)

(Firefox ESR 60.something on Linux)
