### ISSUE TITLE
Email invites don't work

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9816]
1. Be in a room
2. Send an email invite to someone to join the room
3. They can't claim it

This affects /app as of writing.

The user clicks the link and is presented with a dialog-looking thing to create an account. They click this and are brought to the normal registration page. If the user happens to be logged in to an account already, they are just directed to the room rather than being told to verify their email address.

Not sure when this broke exactly, but it's not good.

Checkboxes for bugs identified here:
 * [x] "This invite wasn't sent to you" after signing up with invited email address
 * [x] No invite if signing up with different email
 * [x] not signed in, sign in with account that has invited email (invite sent before email bound): no invite -- this is https://github.com/matrix-org/sydent/issues/162 (https://github.com/matrix-org/matrix-react-sdk/pull/3083 works around)
 * [x] not signed in, sign in with account that doesn't have invited email: no invite - fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3083
 * [x] <del>if the HS has guest access disabled when you click on the email invite link, it just redirects to the welcome screen when it fails to register a guest user.</del> Split out to https://github.com/vector-im/riot-web/issues/10026

**Comment by turt2live** [comment]
This broke in 1.1.0 as part of https://github.com/matrix-org/matrix-react-sdk/pull/2925

The old version had this:
![image](https://user-images.githubusercontent.com/1190097/58229714-acd24480-7cef-11e9-80e2-de1cfdde1265.png)

I'm taking it off my list, but leaving it as a fire for someone to fix. Given the age of the bug, I'm inclined to throw this into the "needs-design" bucket but have it fixed for the release after this week's (~2 weeks from now).

**Comment by dbkr** [comment]
I've just gone through and tested all the different possible scenarios here. Here are the results. Bugs identified marked with [!!]:

not signed in, signup w/o email
 * get 'this invite wasn't sent to you' dialog
 * click 'try to join anyway'
 * joined

not signed in, signup with invited email
 * get 'this invite wasn't sent to you dialog' [!!]
 * (invite gets lost in link-clicking client)
 * click 'try to join anyway'
 * joined

not signed in, signup with different email
 * no invite at all on either client [!!]

not signed in, sign in with account that has invited email (invite sent before email bound)
 * no invite [!!]

not signed in, sign in with account that doesn't have invited email
 * no invite [!!]

signed in with account that has invited email
 * (invite would get turned into a regular invite by being looked up)

signed in with account that doesn't have invited email
 * get 'this invite wasn't sent to you' dialog [!!]
 * click 'try to join anyway'
 * joined

**Comment by the-moog** [comment]
Still there in 1.2.1 (RiotSDK 1.2.1) even though RiotSDK 1.1.1 'fixes' email registration.

**Comment by jryans** [comment]
It's definitely known this is still an issue. It's being worked on.

**Comment by the-moog** [comment]
I got all exicited when I saw the 'fixed' comment in 1.1.1
Happy to help with any testing....

**Comment by dbkr** [comment]
Yep, email registration and email invites are different things.

**Comment by dbkr** [comment]
Another bug: if the HS has guest access disabled when you click on the email invite link, it just redirects to the welcome screen when it fails to register a guest user.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3074 and https://github.com/matrix-org/matrix-react-sdk/pull/3083.
