### ISSUE TITLE
Pasting links in the composer triggers emoji input

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9818]
<img width="1000" alt="Screenshot 2019-05-23 at 10 14 29" src="https://user-images.githubusercontent.com/4626865/58240794-9950c900-7d43-11e9-9399-3de52d745fb5.png">

Pasting https://zpl.io/amde1xD via Keyboard (CMD+V).

macOS 10.14
Chrome 74.0.3729.169 (Official Build) (64-bit)
Latest on /develop

**Comment by bwindels** [comment]
Happens (only with the mentioned link) in both the main composer and edit composer.

**Comment by jryans** [comment]
The trigger is the text "xD" in the link, which matches those emoji.

<img width="360" alt="2019-05-23 at 14 49" src="https://user-images.githubusercontent.com/279572/58258046-eb0c4a00-7d69-11e9-9a52-8a91a9f910e4.png">

**Comment by bwindels** [comment]
Also looking at this one as part of https://github.com/vector-im/riot-web/issues/9985
