### ISSUE TITLE
Collapsing the right sidebar scrolls to the bottom in a room

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9822]
### Description

Just spent a long time today scrolling up in the room looking for an old image that was sent. Thought I might be able to find it quicker if I opened the right sidebar to look at the file viewer. Unfortunately, when you do so it resets the scroll in the room as if you've clicked to another room and then back again.

My naive guess is that it's recreating the message list widget or something, but I'm not actually sure how the UI of Riot works here. I assume it's not necessary and we only need to resize it like we do when we collapse the left room list.

Example video: https://streamable.com/bdrbb

### Version information

- **Platform**: web
- **Browser**: Firefox v69
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Yes, I have also noticed that toggling the notifications panel causing the timeline to remount as well, so seemingly anything in the right panel triggers this.

Seems good to investigate and fix for both app efficiency and better UX.

**Comment by hramrach** [comment]
Seems the behavior has changed. Showing the side pane does not scroll to the bottom anymore but to some random point in the channel (maybe the message that was shown when you opened the channel).
