### ISSUE TITLE
Aggregations: Change to send_relation API

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9825]

**Comment by turt2live** [comment]
(we can also use this API to determine server-side support, although if all goes according to plan then `0.5.0` appearing in `/versions` would also work)

**Comment by ara4n** [comment]
As per discussions elsewhere, there really should be zero reason to use /send_relation if you're already using /send.  It's just a helper method for folks who prefer a more structured API, which helps highlight to the developer that the server is doing more than just sending a message (in that it may also make adjustments to aggregation metadata, if needed in future) - just as /kick and /ban etc are helper methods which have equivalent 'raw' /send variations too.

**Comment by lampholder** [comment]
We're not going to do this, and if there's a discrepancy between mobile and web using different APIs this is fine :)
