### ISSUE TITLE
Windows 10 doesn't have any flag emoji

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9830]
![image](https://user-images.githubusercontent.com/1190097/58291305-2f9fe180-7d7a-11e9-8dba-c77ae0611bde.png)

Windows 10, Chrome 74, /develop

**Comment by bwindels** [comment]
This is our COLR support detection failing and falling back to Segoe, right?

**Comment by turt2live** [comment]
Chrome on Windows 10 claims COLR support, but yes I think these are Segoe flags.

**Comment by bwindels** [comment]
Does the Twemoji font load?

**Comment by turt2live** [comment]
I remember answering questions in a room somewhere, but the conclusion today is that the flags are back! 

There was something weird going on with fonts.
