### ISSUE TITLE
"Homeserver URL does not appear to be a valid Matrix homeserver" error is unclear on which homeserver is invalid

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9835]
![image](https://user-images.githubusercontent.com/274386/58319004-789e7700-7e08-11e9-8ad2-fd64c99ff3f4.png)

leaves the user with no option apart from clearing their storage in the devtools. Would be helpful to have a logout option to start a new session.

Might also be helpful to mention the actual homeserver url ...

**Comment by bwindels** [comment]
(ftr I hit this on a local synapse that wasn't running)

**Comment by bwindels** [comment]
This is also shown if riot is configured with a default hsurl that is invalid (not running in this case), but I'm guessing this is somewhat on purpose.

**Comment by turt2live** [comment]
It's not complaining about your account's homeserver, it's complaining about the configuration. I thought it had words to say that, but apparently not. I wonder if that's what is causing so much confusion around this error...

The app doesn't know if you are logged in at this point, so a logout button would not be possible (or help). I think we just need to clarify the error message to complain about config being invalid.

**Comment by turt2live** [comment]
(I'm hijacking this issue to clarify that error - if I've missed the point, feel free to take it back)

**Comment by bwindels** [comment]
Indeed, nothing to do with the session. Would be good to clarify this and perhaps also mention the configured (invalid) server in the error message.

**Comment by bwindels** [comment]
@rxl881 encountered the same screen on /develop as well, with a couple refresh fixing it :thinking: 
![image](https://user-images.githubusercontent.com/274386/58483745-5a11e600-8150-11e9-95bd-c4f4037713c5.png)

Rick: Multiple refreshes followed, which resulted in a blank page and then after a while the same message. Eventually I refreshed and it worked (no login or other action required)

**Comment by jryans** [comment]
@lampholder and I have both seen this on develop, including an extra line about `Invalid /versions response`. I think it would help debugging to add a lot more logging including server URL, etc. in the discovery code.

**Comment by anoadragon453** [comment]
Myself and other users of my self-hosted Riot (which is pulled from BuildKite develop every hour) are also seeing this error message from time to time, across a variety of browsers.

Here is the `config.json`:

```
{
    "default_hs_url": "https://amorgan.xyz",
    "default_is_url": "https://vector.im",
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": true,
    "brand": "Riot",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
    "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
    "features": {
        "feature_groups": "labs",
        "feature_pinning": "labs",
        "feature_tabbed_settings": "labs",
        "feature_state_counters": "labs",
        "feature_room_breadcrumbs": "labs",
        "feature_custom_tags": "labs",
     	"feature_state_counters": "labs",
	"feature_tag_panel": "enable",
 	"feature_presence_management": "labs",
        "feature_reactions": "labs",
        "feature_message_editing": "labs"
    },
    "default_federate": true,
    "default_theme": "light",
    "roomDirectory": {
        "servers": [
            "matrix.org"
        ]
    },
    "welcomeUserId": "@riot-bot:matrix.org",
    "piwik": {
        "url": "https://piwik.riot.im/",
        "whitelistedHSUrls": ["https://matrix.org"],
        "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
        "siteId": 1
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false
    }
}
```

**Comment by non-Jedi** [comment]
When refreshing, I sometimes get the error mentioned here, sometimes it works, and sometimes I get an error about an "invalid identity server response" on riot.im/develop. My identity server is https://vector.im and homeserver is https://matrix.thebeckmeyers.xyz.

**Comment by turt2live** [comment]
> I think it would help debugging to add a lot more logging including server URL, etc. in the discovery code.

We know what the issue is, just need to improve the messaging. The bug of it showing up in the first place still needs a @lampholder to give me a plan.

**Comment by non-Jedi** [comment]
I just saw this error again this morning on riot.im/develop

**Comment by jryans** [comment]
Sorry to hear that. 😭 I think it's likely best to open a new issue and include your config.json so we can analyse your specific case in detail.

**Comment by non-Jedi** [comment]
I'm using the hosted Riot on riot.im/develop. I thought the config.json was setup server-side for Riot? If it's client-side config, I can dump it to open an issue if you let me know how.

**Comment by jryans** [comment]
Ah right, sorry, I was reading a bit too fast... So no need to worry about the config.json since we have that already, but still I think a fresh issue and console logs would be best, so that we can track your case separately.

**Comment by non-Jedi** [comment]
I'll see if I can trigger again when I get a minute later.
