### ISSUE TITLE
Breadcrumb scrolling is horribly slow

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9838]
### Description

This is me scrolling with my desktop mouse, scrolling nearly as fast as I can: https://streamable.com/nfezn

It's too slow to be comfortably usable.

Funnily enough this is not a problem at all in Chrome: https://streamable.com/hx44d

- **Browser**: Firefox v69
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/9394
