### ISSUE TITLE
Unknown prop `buttonRole` on `<span>` tag

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9841]
```
Warning: Unknown prop `buttonRole` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by AccessibleButton)
    in AccessibleButton (created by BaseAvatar)
    in BaseAvatar (created by MemberAvatar)
    in MemberAvatar (created by EventTile)
    in div (created by EventTile)
    in div (created by EventTile)
    in EventTile (created by withMatrixClient<EventTile>)
    in withMatrixClient<EventTile> (created by MessagePanel)
    in li (created by MessagePanel)
    in ol (created by ScrollPanel)
    in div (created by ScrollPanel)
    in div (created by AutoHideScrollbar)
    in div (created by AutoHideScrollbar)
    in AutoHideScrollbar (created by ScrollPanel)
    in ScrollPanel (created by MessagePanel)
    in MessagePanel (created by TimelinePanel)
    in TimelinePanel (created by RoomView)
    in div (created by RoomView)
    in div (created by RoomView)
    in MainSplit (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in MatrixChat
```

Added by https://github.com/matrix-org/matrix-react-sdk/pull/3019. @turt2live, maybe something was meant to convert `buttonRole` to the value of `role` on the button?

**Comment by turt2live** [comment]
Short version: everything is awful

Long version: all of this needs to be redone anyways, so will take a look then.

**Comment by jryans** [comment]
Should I delete the `buttonRole` lines (which I assume aren't having an effect currently) to avoid the warning for now, if it's going to be a while before we return to this?

**Comment by turt2live** [comment]
it'll be at least 1 release cycle before I poke it (~2 weeks). I'd sooner recommend rolling back https://github.com/matrix-org/matrix-react-sdk/pull/3019 as a whole. I can cherry pick the parts I need when I get back to it.

Worth noting this affects the RC too.

**Comment by jryans** [comment]
Ah okay, we can use this as a reminder to roll that back then (not sure I'll get to it today).

**Comment by jryans** [comment]
Marking release blocker so we remember to also revert in the release branch.

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3036 is the release branch PR.
