### ISSUE TITLE
Safari: Triple clicking a message with reactions will select reactions as well

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9847]
For example triple clicking this message:
![Screen Shot 2019-05-26 at 7 28 21 PM](https://user-images.githubusercontent.com/5855073/58389078-6ed56900-7fec-11e9-8d08-d6cf7e809144.png)

selects all of this
```
Hmm no idea. Never had that fail before. Do the other admin APIs work? Are you on the latest version of Synapse?
👍
👎
🙂
😔
```

Triple clicking this message with a reaction:
![Screen Shot 2019-05-26 at 7 29 40 PM](https://user-images.githubusercontent.com/5855073/58389093-9debda80-7fec-11e9-8b73-a5aaaf00373b.png)

selects this:
```
upgraded to synapse 0.99 and and ran the purge command and it worked like a charm, thanks!
👍 1
👍
👎
🙂
😔
K
J
```

**Comment by turt2live** [comment]
This is a subset of https://github.com/vector-im/riot-web/issues/893
