### ISSUE TITLE
African union flag emoji

### ISSUE THREAD

**Issue by ritzvik** [vector-im/riot-web#9849]
**Is your suggestion related to a problem? Please describe.**
There is no African union flag emoji which pops up on typing `:flag_`

**Describe the solution you'd like**
The flag can be found on the wikipedia page https://en.wikipedia.org/wiki/African_Union

**Comment by jryans** [comment]
Are other flags appearing for you?

**Comment by ritzvik** [comment]
> Are other flags appearing for you?

Yups! I thought as EU flag is present it would be good to have the african flag also 😄

**Comment by jryans** [comment]
Aha, okay! 😁 We don't manage the specific emoji character by character, so I think it would be best to file requests for additional characters with these repos:

* [Emojibase](https://github.com/milesj/emojibase): mapping of Emoji characters to autocomplete text
* [twemoji-colr](https://github.com/mozilla/twemoji-colr): Emoji font used in Riot
