### ISSUE TITLE
Sending image from clipboard can queue it twice

### ISSUE THREAD

**Issue by f0x52** [vector-im/riot-web#9852]
After pasting an image from the clipboard, there's a few seconds of delay, with no feedback that anything is happening. If you paste again during this time, your image will be queued twice, with the second modal appearing after you've sent/cancelled the first one. 

- **Browser**: Firefox 68.0b4 dev branch
- **OS**: Debian Unstable
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
the delay here is whilst the client is asking the server for its media limits
