### ISSUE TITLE
"No Known Servers" fix?

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9861]
### Description

When joining a room with ID `!xxxxxxxxxxx:bla.com` I sometimes get the "No known servers" error. The fix for this is to ask bla.com for entry to the room, so I add `?via=bla.com` to the URL. Joining the room then works.

Surely if we're joining a room then `bla.com` should inherently be added to the `via` array if I'm joining a room with ID ending in `bla.com`?

**Comment by turt2live** [comment]
This is a synapse bug - we expect the homeserver to try the domain in the room ID because we're a client. Clients shouldn't be parsing room IDs, and the spec recommends (somewhere) that homeservers try that domain.

**Comment by anoadragon453** [comment]
Thanks for the context :+1:
