### ISSUE TITLE
Riot-web session ate itself!

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-web#9862]
### Description

I was happily using Riot on my laptop (not actively typing or anything, but reading rooms). I switched back from a Jitsi tab to riot-web and noticed that some of the messages in the e2e room that I was viewing were undecryptable (which was unusual). I tried switching between rooms and was shown the following error message. There was plenty of free disk space, so that wasn't the pproblem.

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Chrome - Version 74.0.3729.157 (Official Build) (64-bit)
- **OS**: macOS
- **URL**: riot.im/develop

<img width="1680" alt="Screenshot 2019-05-28 at 10 56 00" src="https://user-images.githubusercontent.com/6763606/58472413-1ada9980-813e-11e9-949a-ac3839a174b3.png">
<img width="691" alt="Screenshot 2019-05-28 at 11 39 03" src="https://user-images.githubusercontent.com/6763606/58472414-1ada9980-813e-11e9-9e44-f5cc643de488.png">

**Comment by jryans** [comment]
From the debug logs, it seems that local storage was marked as having crypto initialised, but the IndexedDB store wasn't accessible. There are no errors in the log related to this, so it's unclear why that would have happened.

**Comment by jryans** [comment]
Since Rick was able to get going again (thanks to key backup) and the log doesn't pinpoint anything here, let's close this for now. If we hear more reports of issues like this, we should investigate further.
