### ISSUE TITLE
editing with arrow-up doesn't take last message in room into account

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9864]
probably 1-off error in findEditableEvent fn

**Comment by bwindels** [comment]
can't reproduce anymore now ... should have attached a GIF when I had it happening to see if any of the messages had anything special about them.

**Comment by lampholder** [comment]
We can leave this open incase anyone else sees it

**Comment by anoadragon453** [comment]
I get this regularly, but it might be a slightly different problem, in that it'll only occur for about 2s after I send a message. After a little bit, Riot figures out that the message I just sent is the one I want to edit.

And yes this occurs a bit after the message has been indicated as sent.

**Comment by bwindels** [comment]
Hmm, interesting. Might not be re-rerending if the order of events is wrong. Let's see if this is still a problem once https://github.com/vector-im/riot-web/issues/9860 is implemented.

**Comment by turt2live** [comment]
That sounds like the same problem I run into. The send request succeeds, but sync hasn't picked up on it yet.

**Comment by bwindels** [comment]
my guess is that this happens when an event has been sent but the remote echo hasn't been received yet. In this case, it's not in the timeline collection yet, still in the pending event list, which wasn't taken into account so far to edit.
