### ISSUE TITLE
Spellcheck stops working on web after a second

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9865]
### Description

When clicking on a room, if I immediately start typing spell check is working, but as soon as the room fully loads my words stop being spell checked.

### Steps to reproduce

- Enter a room
- Type "asdasda..."
- Notice the red bar growing under the text for a little bit and then it disappears altogether

Log: sent

### Version information

- **Platform**: web
- **Browser**: Firefox v69.0a1 (2019-05-27) 
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by jryans** [comment]
I believe this is due to the current Slate composer cycling `contenteditable` on and off. It should be fixed when we integrate our new composer for main message writing (https://github.com/vector-im/riot-web/issues/9866).

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by anoadragon453** [comment]
Nope :)
