### ISSUE TITLE
Clicking "Decrypt" on a file turns the filesize numbers into emoji

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9867]
### Description

![image](https://user-images.githubusercontent.com/1342360/58480997-68adcc80-8153-11e9-922c-cef6f9fc53b2.png)

Definitely a weird one. Numbers show up as emoji in the timeline in the "Download" notice into emoji numbers. Seems to only happen in encrypted rooms.

### Steps to reproduce

- Upload a file to an encrypted room
- Click "decrypt" on the link under the file
- Numbers turn into emoji

### Version information

- **Platform**: web
- **Browser**: Chrome v73.0.3683.103, Firefox v69.0a1, v67.0 
- **OS**: Debian, Ubuntu, Windows
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
fwiw the right longterm fix to this is to switch to sandboxes for the download link, as per https://github.com/vector-im/riot-web/issues/6173. See also https://github.com/vector-im/riot-web/issues/6418
