### ISSUE TITLE
Cleanup and write tests for new composer

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9868]
While trying to get the new editor (used for editing messages) up and running as quickly as possible, block element support has sort of been crammed into the editor model, and translating document positions to caret positions could be better defined, as well as general cleanup.
 - ~~support block/line parts as container for inline parts~~ this is probably not essential
 - [x] unit tests for model and parts
 - [x] formalize how a document position translates to a caret position.
 - [x] cleanup render code

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3247
