### ISSUE TITLE
Registering with an email causes Riot to ask for T&C twice

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9874]
### Description

I'm asked to agree to the Terms and Conditions twice if registering with an email.

### Steps to reproduce

- Register on matrix.org with an email
- Asked to agree to T&C before sending the email
- After clicking the link in the email and coming into Riot I'm asked to agree again
- Clicking the link says I've already agreed and that I'm being dumb

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian Stretch
- **URL**: riot.im/app, riot.im/develop

**Comment by turt2live** [comment]
@anoadragon453 can you do a quick test on /app and /staging to see if the behaviour is just a /develop problem?

**Comment by anoadragon453** [comment]
Oh, sorry, this was on `/app`.

**Comment by turt2live** [comment]
well, that's fun. Can you do the inverse to see if we fixed it? There's been some work regarding email+t&c registration recently.

**Comment by anoadragon453** [comment]
Yes, happens on `/develop` as well.

**Comment by lampholder** [comment]
I wasn't able to repro, and just now stood with @anoadragon453 and observed this not happening on his machine.
For the record, he used a disposable email address, and opened the email confirmation link in the same browser instance (but a different tab).

**Comment by anoadragon453** [comment]
Was also not able to reproduce now on `/develop`, so closing.
