### ISSUE TITLE
Have to press Enter twice to send a message that ends with unwanted autocomplete

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9876]
For example, 'hello world :)' requires two Enter presses, despite me not wanting to use the emoji-emoji (just the smiley as two characters). I do not have autoreplace plaintext emoji with real emoji enabled.

**Comment by turt2live** [comment]
also applies if your message ends with a colon at all.

**Comment by turt2live** [comment]
... and if you say `#anything` at the end...

**Comment by ara4n** [comment]
is this a regression?

**Comment by turt2live** [comment]
On develop, yes

**Comment by ara4n** [comment]
right, it's biting me now too. annoying.

**Comment by bwindels** [comment]
This must be https://github.com/matrix-org/matrix-react-sdk/pull/2968, which was a fix for https://github.com/vector-im/riot-web/issues/4721

Maybe the solution is to only capture Enter while autocompleting when you've actually auto-completed (e.g. the text you typed has been replaced with an emoji, selectionOffset > 0)?

**Comment by turt2live** [comment]
That solution sounds like the right thing to me, although I think it'd make sense to also capture Enter when your selection changes from 0 -> 1 -> 0 again

**Comment by lampholder** [comment]
Slack handles this in quite a nice way.

- Ending your message with an emoticon:
    Slack doesn't update the composer, but your emoticon will have been replaced with the corresponding emoji when it enters the timeline
    (Otherwise, Slack replaces emoticons with emoji on space (not other non-word characters, though - comma, semicolon etc. do not trigger a substitution)

- Ending your message with a colon:
    Slack doesn't initiate emoji-autocomplete until you've type `:xx` - i.e. colon and two characters. This stops emoticons triggering unwanted autocomplete suggestions, and means ending a message with colon is fine (since a colon by itself doesn't trigger autocomplete)
