### ISSUE TITLE
Links preview does not work reliably

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#9880]
### Description

Links preview does not work reliably on mobile, web and desktop versions. Related to #9310.

### Version information

- **Platform**: both: web (in-browser) and desktop and mobile

For the web app:
- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/develop & riot.im/app & desktop

For the desktop app:
- **OS**: SUSE Linux
- **Version**: 1.1.2

**Comment by jryans** [comment]
Can you describe in more detail? Does it fail all the time for certain links? What's an example link that fails for you?

URL preview is currently done on the server. See https://github.com/vector-im/riot-web/issues/2953 for some past discussion about considering moving to the client. There are various setting to control URL preview per account and per room if you are worried about leaking URLs to the HS.

**Comment by akontsevich** [comment]
Today all the time completely fails, previous days partially - shown some link, some - not. Happen with any link: youtube, news, blogs, whatever, etc.

**Comment by lampholder** [comment]
I'm afraid we're going to need some more information to help debug this:
 - is your account on matrix.org? 
 - is URL preview enabled in your User Settings (Preferences: Timeline)?
 - is encryption enabled in the rooms?
 - is URL preview enabled for participants in the Room Settings (General)? (this setting doesn not appear if the room is encrypted)
 - is URL preview enabled for _you_ in the Room Settings (General)?
 - how long are you waiting for the URL previews to render?
 - please do provide specific examples of actual URLs
 - please do provide specific examples of times of failure - it could be that the server is just overloaded at the times you're trying to preview, causing the requests to time out

**Comment by lampholder** [comment]
@akontsevich I hope you don't mind I edited the original issue for clarity - we can use this issue to track URL previews not working reliably and #2953 can continue to be used to track (perhaps optionally) making URL previews work client side.

**Comment by lampholder** [comment]
Also URL previews aren't yet implemented on iOS, so if you were trying to use them there that will explain the failure.

**Comment by akontsevich** [comment]
>     * is your account on matrix.org?
Yes!

>     * is URL preview enabled in your User Settings (Preferences: Timeline)?
Sure, it worked before, stopped few days ago, nothing changed in settings.

>     * is encryption enabled in the rooms?
No.

>     * is URL preview enabled for participants in the Room Settings (General)? (this setting doesn not appear if the room is encrypted)
Yes! However bug appears regardless of this setting.

>     * is URL preview enabled for _you_ in the Room Settings (General)?
Yes.

>     * how long are you waiting for the URL previews to render?
Hours, previously worked almost immediately.

>     * please do provide specific examples of actual URLs
Any youtube video, another example: http://drevo.tantrido.ru/?p=1624

>     * please do provide specific examples of times of failure - it could be that the server is just overloaded at the times you're trying to preview, causing the requests to time out
Does not work for 3-5 days already.

>Also URL previews aren't yet implemented on iOS, so if you were trying to use them there that will explain the failure.

No, I mean Android devices: preview stopped to work on them as well.

**Comment by turt2live** [comment]
This looks to be limited to matrix.org users only. Some URLs do work, however the one you've mentioned indeed does not work.

**Comment by turt2live** [comment]
From some investigation: it's because the image from the preview cannot be downloaded. Have opened https://github.com/matrix-org/synapse/issues/5298 to track fixing it.

**Comment by akontsevich** [comment]
![изображение](https://user-images.githubusercontent.com/3843657/58655210-47e7a180-8322-11e9-98ab-90c3a20df660.png)
This is preview from Skype, for example. However it is not the only problem: as I mentioned nothing from youtube works, many other sites like this: https://hdrezka-me.me/22654-teni-ischezayut-v-polden-95051943.html, livejournal, etc  - nothing works actually.

**Comment by akontsevich** [comment]
Inserting new youtube link shows preview, however all previous links or on next days links are not previewed. So could be both synapse and client bugs.

**Comment by akontsevich** [comment]
Issue appeared again. Please fix!

**Comment by turt2live** [comment]
It's a Synapse bug, as you're aware. Please don't comment on closed issues :/
