### ISSUE TITLE
Always warn when signing out of riot

### ISSUE THREAD

**Issue by LordKorea** [vector-im/riot-web#9885]
**Is your suggestion related to a problem? Please describe.**
When I sign out of riot on the riot-desktop electron app on linux my device ID (and my UI language) is reset. I've been told on the riot-web:matrix.org channel that this is expected behavior. This is counter-intuitive as I expect the "Sign out" to not cause any troubles after signing back in.

**Describe the solution you'd like**
A warning (like the one when no keys are backed up when signing out) should be shown every time the user tries to sign out and warn the user of the consequences.

**Describe alternatives you've considered**
I've not come up with any alternatives.

**Additional context**
N/A

**Comment by aaronraimist** [comment]
A warning is now shown if you click sign out and don't have key backup
