### ISSUE TITLE
Aggregations: Tweak read marker advancing behavior

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9889]
As discussed in the [detailed analysis](https://docs.google.com/document/d/196pPSDKbuwjpjQymAsKUFyCjTlnS6hFy-gYjV77cSK8/edit), read markers plus hidden events leads to a "ping pong" issue where we advance past our own hidden event in one code path and then back up to the last visible one in another.

We should improve such code paths to avoid this confusion and remove these unnecessary server calls to change read marker for no purpose.

**Comment by bwindels** [comment]
As read receipts move past hidden events now, there should be no more ping-pong effect. I couldn't see any while testing in any case. Additionally, I've made read markers update past hidden events in https://github.com/matrix-org/matrix-react-sdk/pull/3226 to keep things symmetrical with read receipts.
