### ISSUE TITLE
Emotes / Emoji are no longer existent (Square character) or low-fi black and white after update to latest version.

### ISSUE THREAD

**Issue by unknown-user-9246102101** [vector-im/riot-web#9891]
### Description

It used to be that every emoji was present and accounted for. What happened? Why am I missing most emoji, or they look like I'm a phone user for the few someone has bothered to support?

### Steps to reproduce

Type a ":" then notice crappy support for emojis and broken characters. Notice that you used to have good support with colorful images.

![broken-emotes](https://user-images.githubusercontent.com/35440139/58578797-3f527680-820f-11e9-9922-8e52571709e0.jpg)

I expected support for colorful and existent emojis but I do not have pictures of it.

What gives?

### Version information

- **Platform**: Desktop (win 7)
- **OS**: Windows
- **Version**: 
    matrix-react-sdk version: `<local>`
    riot-web version: 1.2.0
    olm version: 3.1.0

**Comment by hooger** [comment]
I also experience the same behaviour on Debian stable, latest, also right after upgrading from 1.1.2 -> 1.2.0. The upgrade caused other issue as well, so I consider downgrading until fix.

**Comment by jryans** [comment]
Emoji current requires support for COLR fonts. If that doesn't exist, it will fall back to native emojis that might be installed. For Windows, that's Segoe UI Emoji. For Linux, that's Noto Color Emoji.

In the above screenshot, you are seeing what happens with no COLR support and no native emoji font either.

Can you open the Console (Ctrl-Shift-I), filter on "COLR", and see what messages are there?

**Comment by hooger** [comment]
It says
```
Checking for COLR support
Waiting for COLR SVG to load
Drawing canvas to detect COLR support
Canvas check reveald COLR is supported? false
```
so I guess, something is not installed. However
```
apt search noto |grep -i font
```
returns a list of results, all marked as installed. Can you help me fix the issue?

Results are: ("telepítve" means installed)
```
fonts-cabin/stable,stable,now 1.5-2 all [telepítve, automatikus]
  humanist sans serif font
fonts-noto/stable,stable,now 20161116-1 all [telepítve, automatikus]
  metapackage to pull in all Noto fonts
fonts-noto-cjk/stable,stable,now 1:1.004+repack2-2 all [telepítve, automatikus]
  "No Tofu" font families with large Unicode coverage (CJK)
fonts-noto-hinted/stable,stable,now 20161116-1 all [telepítve, automatikus]
  "No Tofu" font families with large Unicode coverage (hinted)
fonts-noto-mono/stable,stable,now 20161116-1 all [telepítve, automatikus]
  "No Tofu" monospaced font family with large Unicode coverage
fonts-noto-unhinted/stable,stable,now 20161116-1 all [telepítve, automatikus]
  "No Tofu" font families with large Unicode coverage (unhinted)
texlive-fonts-extra/stable,stable,now 2016.20170123-5 all [telepítve]
  TeX Live: Additional fonts
```

Thank you in advance!

**Comment by jryans** [comment]
On Debian, I guess you might want [fonts-noto-color-emoji](https://tracker.debian.org/pkg/fonts-noto-color-emoji), but it doesn't appear to be available in stable. Perhaps the full fonts-noto package includes it? I am not sure.

According to [this thread](https://www.reddit.com/r/debian/comments/83lyf2/color_emoji_on_debian_9/), it's possible you may also need updated libraries like fontconfig, cairo, etc.

**Comment by hooger** [comment]
I see the thread and I will try something when I have some more time, however the issue reamins: before the upgrade the emojis worked, now they don't. Is it possible that you changed to a newer version of the emojis? If yes, is it really necessarry to make strong requirements? I had no issues before, so I guess the current versions are just fine.

**Comment by jryans** [comment]
We removed the previous Emoji font (Emojione) because of licensing restrictions that prevented us from upgrading to new versions and getting new images.

The new font we have included solves that licensing and character issues, but it also uses a newer font technology that currently requires up to date browsers, font libraries, etc.

**Comment by hooger** [comment]
Oh, that totally makes sense! Thank you for the clarification!

**Comment by jryans** [comment]
There are some more details about the emoji change in the [Riot 1.2 blog post](https://medium.com/@RiotChat/riot-web-1-2-farewell-emojione-hello-twemoji-33b3befcf21a).

**Comment by crispygoth** [comment]
Losing emoji support on Debian Stable (please note this is the *currently maintained stable release*, not an "older release" as your blog post suggests) is somewhat disappointing. I'd rather have some slightly out-of-date emojis than the current extremely basic fallback. Is there no way to support both?

**Comment by ara4n** [comment]
We'll fix this by shipping a fallback font.

**Comment by jryans** [comment]
Filed the SBIX fallback idea as https://github.com/vector-im/riot-web/issues/9900.

**Comment by ara4n** [comment]
should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3050

**Comment by nukeop** [comment]
This is happening again on Element version: v1.7.28

**Comment by SimonBrandner** [comment]
> This is happening again on Element version: v1.7.28

@nukeop, please open a new issue with as much detail as possible
