### ISSUE TITLE
Private conversation: Specific message gets pushed to the bottom of the conversation despite being older

### ISSUE THREAD

**Issue by tobbi** [vector-im/riot-web#9894]
### Description
One specific message in a private conversation with someone does not follow the timestamp ordering guidelines but gets pushed down each time I continue the conversation.

### Steps to reproduce
- Start a private conversation with someone. Other steps than that, I don't really know.

Log: sent/not sent?    

![Screenshot at Mai 29 20-25-32](https://user-images.githubusercontent.com/583169/58582181-777aa900-8251-11e9-876e-c6b9e1cac1bd.png)

### Version information

- **Platform**: web (in-browser) or desktop? Web App (through Rambox)

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Rambox (Chromium)
Version: 0.6.7
Plattform: darwin (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?

Mac OS X 10.13.6

- **URL**: riot.im/app

**Comment by tobbi** [comment]
Interestingly enough, when I click the timestamp of the message, it moves from the bottom to the conversation to the top of the conversation.

**Comment by turt2live** [comment]
Does refreshing the page help at all?

**Comment by tobbi** [comment]
You're right: Refreshing the page fixed the issue for me.

**Comment by turt2live** [comment]
Sounds like a resurgence of https://github.com/vector-im/riot-web/issues/9443 then - will leave this open to see if anyone else runs into it, but it is supposed to be fixed in 1.2.0 (which you're running according to your logs).

**Comment by turt2live** [comment]
@tobbi have you (or anyone else) seen this recently? It seems like it hasn't happened in a while, and might have been just a weird edge case we have fixed since then.

**Comment by tobbi** [comment]
So far, I haven't seen any more instances of this happening, though I have to admit I haven't PMed people excessively. I would assume that this issue can be closed.

**Comment by ploth** [comment]
I just reported two bug reports via rage shake in riotx regarding this one.

**Comment by t3chguy** [comment]
This issue tracker is about riot-web, perhaps you want https://github.com/vector-im/riotX-android/
