### ISSUE TITLE
Riot on Safari may attempt to render Variation Selector-16 (white boxes) between emoji

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9895]
https://emojipedia.org/variation-selector-16/

![Screen Shot 2019-05-29 at 2 21 10 PM](https://user-images.githubusercontent.com/5855073/58585790-3a95be80-821f-11e9-8b6d-df805353b0c6.png)

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Safari 12
- **OS**: macOS 10.14.5
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
How do you trigger this?

**Comment by jryans** [comment]
I have observed this in Safari for any emoji that have skin tone variants, even when an actual tone is not being used.

For example the `:thumbup:` emoji does not include an actual skin tone modifier, but it does include a second character which is this variation selector. In Safari only, this second part displays as a box.

**Comment by aaronraimist** [comment]
Yeah I guess it would happen with any of these https://unicode.org/emoji/charts/emoji-variants.html#270f emoji which have multiple styles

![Screen Shot 2019-06-05 at 2 01 56 PM](https://user-images.githubusercontent.com/5855073/58982631-86ee7a80-879a-11e9-9dc3-096a1657c78b.png)
![Screen Shot 2019-06-05 at 1 56 03 PM](https://user-images.githubusercontent.com/5855073/58982268-a933c880-8799-11e9-9177-656519430988.png)

**Comment by aaronraimist** [comment]
This old PR looks related https://github.com/matrix-org/matrix-react-sdk/pull/1458/files

**Comment by aaronraimist** [comment]
![Screen Shot 2019-11-08 at 9 24 52 AM](https://user-images.githubusercontent.com/5855073/68487919-9f5f3700-0209-11ea-817c-3c65413a634b.png)

Still an issue 😢

**Comment by t3chguy** [comment]
re-opening until the font created by that patch lands on develop
