### ISSUE TITLE
'help' link in Help & About section of user settings 404s

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#9896]
it should probably be changed to https://about.riot.im/help instead of https://about.riot.im/need-help.  We should probably also 302 /need-help to /help.

**Comment by turt2live** [comment]
I vote we fix it with a 302 and pretend we never got it wrong

**Comment by uhoreg** [comment]
The 302 has been added.  I'll let someone else decide if we should change the code, or if we should just close this.

**Comment by lampholder** [comment]
/me is happy just to close this :)
