### ISSUE TITLE
Ship SBIX emoji fallback font

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9900]
We're seeing some configurations (https://github.com/vector-im/riot-web/issues/9891 and elsewhere in chat) that don't support COLR fonts, leading to a bad emoji experience, especially if you also don't have a native font either.

We should be able to remedy this by also shipping a SBIX variant of our emoji font, since that format has wider support.

**Comment by lampholder** [comment]
Are we actually moving forward with this? Is the first step for Matthew to fork the mozilla script to make it also generate SBIX? Is that something somebody other than Matthew could do?

**Comment by ara4n** [comment]
i've already forked the script to fix https://github.com/mozilla/twemoji-colr/issues/50. i would be working on it right now if i hadn't been hijacked. someone else could go and add the thing to the script to blat out a PNG and change the TTX to point to the the PNG in a SBIX, probably cribbing off https://github.com/RoelN/ChromaCheck/blob/master/src/chromacheck-sbix.ttx as an example of what SBIX TTX looks like.

**Comment by ara4n** [comment]
and yes, we should absolutely move fwd on it.

**Comment by jryans** [comment]
Is your patch in https://github.com/mozilla/twemoji-colr/issues/50 literally the only change so far? (Should we fork the font into our org and continue from there?)

**Comment by ara4n** [comment]
yup and yup.

**Comment by ara4n** [comment]
should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3050

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3050 has merged to develop.
