### ISSUE TITLE
Unable to backup keys: "Error.  Unable to load! ..."

### ISSUE THREAD

**Issue by DiagonalArg** [vector-im/riot-web#9903]
Settings >> Security & Privacy >> "Start Using Key Backup" or "Export E2E Room Keys"

In either case, I immediately get a screen that says: "Error.  Unable to load! Check your network connectivity and try again."  

I'm posting, so obviously my network is fine ...

Desktop, Ubuntu 16.04
Riot v. 1.2.0

Since I need the issue URL to get the logs, I'll edit this once I have them....

Hm.  I go to Settings >> Help & About >> Submit Debug Logs, then I put in [this github url](https://github.com/vector-im/riot-web/issues/9903) and click "Send Logs".  It says, "Preparing to send logs" and I get the spinner, but it just keeps going and going ...

Yup, it's not terminating.  I have to X out.

**Comment by turt2live** [comment]
I'm going to tentatively close this as a duplicate of https://github.com/vector-im/riot-web/issues/9901 - when that issue is fixed, and you still see problems, please open a new issue.
