### ISSUE TITLE
Unable to backup keys: Frozen at "That matches!"

### ISSUE THREAD

**Issue by DiagonalArg** [vector-im/riot-web#9904]
Settings >> Security & Privacy >> "Start Using Key Backup"

I get a screen that asks for a password.  I submit that and end up at the confirm screen.  I put in my password again and it says, "That matches!"  So I hit the "Next" button and ...  it refuses to budge.

Desktop, Ubuntu 18.04
Riot v. 1.2.0

Since I need the issue URL to get the logs, I'll edit this once I have them....

Hm. I go to Settings >> Help & About >> Submit Debug Logs, then I put in this github url and click "Send Logs". It says, "Failed to send logs.  HTTP 500" (in red)

My network is fine, though.

**Comment by LordKorea** [comment]
Sounds very much like a duplicate of https://github.com/vector-im/riot-web/issues/9901

**Comment by turt2live** [comment]
I'm going to tentatively close this as a duplicate of https://github.com/vector-im/riot-web/issues/9901 - when that issue is fixed, and you still see problems, please open a new issue.
