### ISSUE TITLE
Unable to upload logs / rageshake is down

### ISSUE THREAD

**Issue by DiagonalArg** [vector-im/riot-web#9906]
See these two (compound) bugs:

https://github.com/vector-im/riot-web/issues/9903
https://github.com/vector-im/riot-web/issues/9904

Desktop, Ubuntu 16.04 and 18.04
Riot v. 1.2.0

In 16.04 I just get a spinner that never ends.
In 18.04 I get an "HTTP 500"

In either case, my network is fine.

**Comment by turt2live** [comment]
The server which handles logs is currently experiencing problems - am working on it.

**Comment by DiagonalArg** [comment]
Could this be the reason I couldn't backup keys or either 16.04 or 18.04?

**Comment by turt2live** [comment]
Unlikely. Your problem with keys is likely to be https://github.com/vector-im/riot-web/issues/9901

Logs would confirm it, but for obvious reasons that's a bit difficult right now.

**Comment by turt2live** [comment]
Should be back up now.
