### ISSUE TITLE
hs_url param is broken

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#9908]
users used to be able to set the default homeserver URL by setting a parameter ( matrix-org/matrix-react-sdk#716 ), but it looks like it was broken in the redesign

**Comment by turt2live** [comment]
this is somewhat intentionally broken in develop due to the recent login/auth changes btw.

**Comment by lampholder** [comment]
I hadn't considered this - the intention is for people to provide links to https://riot.im/app (or other riot instances) and specify the default homeserver via GET params.

In theory this sounds like a good thing to keep supporting - do we have any idea how well used it is?

@turt2live is it possible to:
- if the riot instance allows connecting to other HSes, check whether the provided HS is valid as we do when checking the config
- if the riot instance is locked down to a single HS, probably just ignore the GET param HS?

**Comment by turt2live** [comment]
@lamlholder the exact same parameters are heavily intertwined with email validation already, and are ignored by the validator for this reason

**Comment by lucysan** [comment]
Any update on this? We don't want to host yet another copy of Riot, but without the ability to redirect to homeserver login we're forced to.

**Comment by turt2live** [comment]
It's no easier to do than it was in May. Hosting your own Riot is going to be much better.

**Comment by TheTimeWalker** [comment]
Just found out that this is broken which is a bit annoying since I often times get issues with people onboarding to my home server since they immediately try to login to matrix.org instead. The solution "hosting your own Riot" doesn't make much sense to me because riot-web's Readme already mentions that hosting your own instance with the same domain as your home server brings in some security risks.

**Comment by uhoreg** [comment]
@TheTimeWalker It's only an issue to host Riot on the same hostname as your homeserver, not demain.  So if your Riot is on riot.example.com, and your homeserver is on synapse.example.com, then you're fine.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/5469 which has more upvotes
