### ISSUE TITLE
Put it on the toolbar do not work since update to 1.2

### ISSUE THREAD

**Issue by ralfi** [vector-im/riot-web#9912]
Hi riotsis,

since update to 1.2 i can not set riot-web to the toolbar but the app self stay open (ps -lea).

**Comment by lampholder** [comment]
Hey @ralfi - can you provide some more information? What platform are you running on, etc?

**Comment by ralfi** [comment]
Sorry, Debian 9 / cinnamon and i mean the taskbar of course. As i see in riot matrix group other users have similar appearences since upgrade. Up to yesterday and v 1.1 everything was fine.

**Comment by ralfi** [comment]
Works again since 1.2.1
