### ISSUE TITLE
Uploads/Downloads broken in upcoming browsers

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9913]
### Description

Whenever a friend uploads a file, Riot will correct state the name and the correct filesize (1.84MB, 3.26MB, etc), but when anyone downloads any of them the contents of the file are just the following text:

```
function stream() { [native code] }
```

I don't believe it's a server problem as he's on my homeserver and neither I nor anyone else on it has the same issue, and it's not even limited to his account as one of his other computers does not exhibit the same behavior on the same account.

However, for him on one computer it's 100% reproducible.

Log: sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Microsoft Edge Canary: Version 76.0.174.0 (Official build) canary (64-bit) (the chromium fork), Chrome Canary Version 76.0.3809.0 (Official Build) canary (64-bit)
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I can reproduce this on Microsoft Edge Canary on macOS.

We can probably wait until Edge's Chromium-based fork is a little further along before worrying, though

**Comment by anoadragon453** [comment]
Heads up that this is also happening on Chrome Canary itself, meaning it'll probably affect Chrome users at some point as well.

Chrome Canary `Version 76.0.3809.0 (Official Build) canary (64-bit)`.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9922

**Comment by krixano** [comment]
@turt2live This is not an issue exclusive to Edge. The same problem happens on Chrome Canary... Hence @anoadragon453 comment.

**Comment by turt2live** [comment]
Why does everything have to be so awful :(

Have opened https://github.com/vector-im/riot-web/issues/9924 to track it, and will try and take a look.

**Comment by lnicola** [comment]
Also happens in Firefox Nightly.

**Comment by lnicola** [comment]
https://groups.google.com/forum/#!topic/mozilla.dev.platform/26MI90sjjSY
