### ISSUE TITLE
Taskbar Icon missing

### ISSUE THREAD

**Issue by vsatmydynipnet** [vector-im/riot-web#9915]
There is a not nice bug in 1.2.0. I start 2 clients on Linix/XFCE with --profile. I had a Riot symbol in the taskbar for every instance. Now with 1.2.0 only the first one has the symbol, which is kinda bad because no quit or hide for 2nd++ instances possible

**Comment by lampholder** [comment]
Is this a duplicate of https://github.com/vector-im/riot-web/issues/9897 ?

**Comment by vsatmydynipnet** [comment]
duplicate of #9897 https://github.com/vector-im/riot-web/issues/9897
