### ISSUE TITLE
Chrome Canary is unable to submit a bug report

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9917]
### Description

Chrome Canary has an infinite spinner on submitting a bug report due to the following error (likely the top one):

![image](https://user-images.githubusercontent.com/1342360/58703047-5a53f080-839f-11e9-9ebe-369d1d9f7f98.png)

### Steps to reproduce

- Run Chrome Canary
- Try to submit a bug report
- Wait [forever](https://www.youtube.com/watch?v=RLkc1huIBCo)

Describe how what happens differs from what you expected.

Log: lol

### Version information

- **Platform**: web
- **Browser**: Chrome Canary Version 76.0.3809.0 (Official Build) canary (64-bit)
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Good to have a heads up on... whatever Microsoft are doing, but P3 'cause Edge is not supported and Canary's not finished :)

**Comment by turt2live** [comment]
It looks like your network changed... Is it possible to get a more stable error log from your console? Also preferably on /develop or /app to eliminate web server weirdness

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/9922

**Comment by jryans** [comment]
@anoadragon453 Can you retest this again in your copy of Chrome Canary? It worked for me via https://riot.im/develop, but I'd like to verify on your side as well.
