### ISSUE TITLE
Can't join room. Stuck at the spinner

### ISSUE THREAD

**Issue by bbigras** [vector-im/riot-web#9920]
### Description

I tried to create a new room with a name on https://riot.im/app and I'm stuck at the "joining room" spinner. Even if I refresh.

### Steps to reproduce

- create new room with a name

Stuck at "joining room".

Log: not sent

![image](https://user-images.githubusercontent.com/24027/58711694-faece500-838c-11e9-9df0-5d1000e5393d.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 74.0.3729.157
- **OS**: NixOS
- **URL**: riot.im/app

**Comment by bbigras** [comment]
I was low on disk space.. Just like last time I tried to report a bug. Maybe the UI could detect that or something.

**Comment by ildar** [comment]
that's indeed the unfortunate bug. While having ~20MB of free space a user can hardly guess it's the low space problem. Could that be fixed?

**Comment by HammyHavoc** [comment]
Seeing this issue when attempting to join #synapse:matrix.org to discuss a different issue.

**Comment by HammyHavoc** [comment]
Hm. Closed Element on Windows and reopened it, now works fine.
