### ISSUE TITLE
Support "New Microsoft Edge" (Chromium base)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9922]
Affects all 3 channels: beta, dev, canary

See referenced issues for a list of problems. Although Riot doesn't support Edge (or New Edge), this issue serves as a thing to track different problems which might be easily solved.

**Comment by jryans** [comment]
The issues referenced above are now working correctly in Chromium-based Edge Canary 77 (tested on macOS).

@turt2live Do you want to keep this open as a general bin for other Edge issues?

**Comment by turt2live** [comment]
The bin didn't grow as much as I anticipated, so closing
