### ISSUE TITLE
Chrome 76 (upcoming release) doesn't work with Riot

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9924]
* [x] https://github.com/vector-im/riot-web/issues/9913 - Uploads/Downloads broken in upcoming browsers
* [x] https://github.com/vector-im/riot-web/issues/9917 - Cannot send bug reports

I'm labelling this as p1 major because our user base uses Chrome and the next Chrome release is going to suck for them.

**Comment by lampholder** [comment]
This will become stable Chrome on July 30

**Comment by turt2live** [comment]
and because of that release day, we'll review this sometime between now and then rather than immediately. We're hoping that Chrome considers the issues bugs and fixes them so we don't have to.

**Comment by bwindels** [comment]
Both linked bugs are closed, does that mean this can be closed as well?

**Comment by jryans** [comment]
Well, it's a bit confusing, as I believe both bugs were closed "in favour of" this meta-bug even before the problems had been investigated, which was a bit surprising... Anyway, their closed state is less useful than usual.

In any case, I'll retest in Canary and see what happens.

**Comment by jryans** [comment]
All listed problems appear to be working correctly with Chrome Canary 77, so it appears everything is fixed here.
