### ISSUE TITLE
Cannot accept entry of confirmation of key backup passphrase

### ISSUE THREAD

**Issue by kortschak** [vector-im/riot-web#9933]
### Description

Choosing key backup passphrase will not progress past the second second dialogue.

### Steps to reproduce

- Choose to set up a key back up from the warning in a room "Start using Key Backup".
- Enter passphrase in first dialogue.
- Click non-dimmed "Next" button.
- Re-enter passphrase.
- Click non-dimmed "Next" button.

No progress from this click.

I would expect that a non-dimmed button would result in an action.

Log: not sent

![Screenshot from 2019-06-02 08-59-47](https://user-images.githubusercontent.com/275221/58754719-cf493680-8515-11e9-8168-1c72bfc53bb0.png)

![Screenshot from 2019-06-02 09-00-24](https://user-images.githubusercontent.com/275221/58754721-d6704480-8515-11e9-9ec6-2c871d066ed8.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu?
- **Version**: 1.2.0

**Comment by turt2live** [comment]
1.2.1 fixes this specific bug - please try upgrading.

**Comment by kortschak** [comment]
I love time travellers! Thanks.
