### ISSUE TITLE
Consider not showing edit messages when "Show hidden events in timeline" is on

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9937]
![image](https://user-images.githubusercontent.com/1342360/58789960-41d61700-85e7-11e9-97bd-92de112cb0c8.png)

### Description

It's nice to have the "Show hidden events in timeline" options on, but it can be annoying when edits are displayed separately from the edited message, especially when it comes right after the original message (now displayed as edited), which it often does.

Even with this on we are unable to see the previous message, so doubling the message shows nothing new, and I believe adding a special case to hide the duplicated event would be a nice quality of life improvement.

### Steps to reproduce

- Turn "Show hidden events in timeline" on in Labs
- Send a message
- Edit a message
- Now there's two very similar messages in the timeline

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by anoadragon453** [comment]
Or alternatively display them in a collapsed fashion as we do reactions:

![image](https://user-images.githubusercontent.com/1342360/58790512-6d0d3600-85e8-11e9-997e-767d01163d5e.png)

**Comment by jryans** [comment]
I think showing them as a collapsed source view is more useful for debugging.
