### ISSUE TITLE
Twemoji doesn't work

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/riot-web#9941]
As I understood it, a few days ago emojione was replaced with twemoji, which is great :+1: 
Problem is, since that change emojis didn't display for me at all. I had to install a system font (noto-fonts-emoji). That works, I now see the noto emojis, but this is not how it was intended to work, right?

### Version information

- **Platform**: Desktop
- **OS**: Arch Linux
- **riot-web**: 1.2.1
- **electron**: 4.1.4

**Comment by turt2live** [comment]
This sounds like it would be fixed by https://github.com/vector-im/riot-web/issues/9900 - due for the next release.
