### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nerdoc** [vector-im/riot-web#9949]
Small translation issue:

![Screenshot_20190604_152804](https://user-images.githubusercontent.com/2955584/58882783-58f73080-86dd-11e9-9659-729c50d119d4.png)

"Diese Passphrase sieht start genug aus" should be "Diese Passphrase sieht stark genug aus".

**Comment by nerdoc** [comment]
and if you're on it: "Für maximale Sicherheit sollte diese anders als dein Konto-Passwort lauten" is much better German as the current version above. Without ",", "diese", "lauten" instead of "sein".

**Comment by jryans** [comment]
Thanks for filing! Translations are handled through a [separate process](https://github.com/vector-im/riot-web/blob/develop/docs/translating.md). Feel free to contribute there if you'd like to help! 😁

**Comment by nerdoc** [comment]
eh - no, sorry. too busy ATM to make an account. S/O with an account there can fix this, it's a no-brainer.
