### ISSUE TITLE
CMD+I triggers top left context menu

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9958]
Italic fires correctly, but also triggers the context menu. Markdown disabled. Latest Chrome on /develop.

**Comment by turt2live** [comment]
ftr: this was by design because the key combination was supposed to be unused, and therefore could be used to toggle this menu. Sounds like we need to pick a different combination.

**Comment by turt2live** [comment]
So far <kbd>CMD</kbd>+<kbd>`</kbd> is winning as an alternative
