### ISSUE TITLE
Switching between profiles by clicking avatars in the timeline can show the wrong avatar for the user in MemberInfo

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9959]
1. Have a slow homeserver
2. Click the first member in the timeline to open MemberInfo
3. *Without closing MemberInfo*, click the second member to open their MemberInfo
4. Observe that the name, devices, etc all change but the avatar is for the first user.

**Comment by t3chguy** [comment]
Fixed, blanks itself instantly
