### ISSUE TITLE
Unable de connect with invitation link on matrix.org

### ISSUE THREAD

**Issue by magicvince** [vector-im/riot-web#9964]
When I send mail invitation for non-members, they can't join the discussion or the room without create an account.

I follow the bot tutorial but the UI isn't the same (I try with web version on firefox 60.7 and with the last debian riot desktop application).

**Comment by lampholder** [comment]
> When I send mail invitation for non-members, they can't join the discussion or the room without create an account.

This behaviour has changed a bit throughout Riot's history. Originally we supported guest accounts, then moved to provide 'simple, lightweight onboarding' (so people could start chatting just by picking a name). We're currently considering how to tackle this - being tracked here: https://github.com/vector-im/riot-web/issues/9264

> I follow the bot tutorial but the UI isn't the same (I try with web version on firefox 60.7 and with the last debian riot desktop application).

Riot Bot needs (still) needs updating - this should be happening soon, as is tracked here: https://github.com/vector-im/riot-web/issues/9162

**Comment by lampholder** [comment]
Closing since this is a dup of those other two issues)
