### ISSUE TITLE
Rely on r0.5.0 in /versions instead of unstable_features for lazy-loading detection

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9966]
so Synapse can remove it: https://github.com/matrix-org/synapse/blob/00cf679bf22737b6b9028ba0dada47e029fc0925/synapse/rest/client/versions.py#L44

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2671)
