### ISSUE TITLE
Account disabled after x time ?

### ISSUE THREAD

**Issue by jodumont** [vector-im/riot-web#9969]
:crying_cat_face: _I would like to say **I'm sorry** to open an issue her for this but I trully don't know where to open it._

### if someone know where I could get the need I help it would be very appreciate if you simply mention it below

So probably over 18 months ago I created an account via https://riot.im which I probably didn't link to an email but save my password into my vaults (keepass and lastpass) as usual.

I tried to sign in again, 18 months later and apparently my password is not the right one.
I'm obviously unable to reset the password because if I link my account with an email I simply don't remember it.

**Comment by turt2live** [comment]
If your account was on matrix.org, email support@matrix.org and the team might be able to help out. If your account was on a different homeserver, you'll have to contact that administrator.
