### ISSUE TITLE
How to join an existing community ?

### ISSUE THREAD

**Issue by PhieF** [vector-im/riot-web#9971]
Hi

When I'm given a community link, like
+criquette:lostpod.me
I've no ways to join it or I don't know any

I could type the following address:
https://riot.im/app/#/group/+criquette:lostpod.me

but how to actually join the community, then ? It seems I can only see it

Thanks

**Comment by t3chguy** [comment]
That community appears to be invite-only, so you can only join it if the admin of it invites you. This is a setting of the community, e.g:
![image](https://user-images.githubusercontent.com/2403652/58994659-35211100-87e9-11e9-84fe-b5298814e76a.png)

**Comment by PhieF** [comment]
Yes, that's right for the second point (thank you)

but what about the first ? There seems to be no way to add a community knowing it's address, except by writing this kind of url ?

**Comment by t3chguy** [comment]
That probably falls under https://github.com/vector-im/riot-web/issues/4428

**Comment by PhieF** [comment]
It looks like it, indeed
just a kind of shortcut to this kind of links https://riot.im/app/#/group/+criquette:lostpod.me
