### ISSUE TITLE
Cookie policy should be hosted on about.riot.im somewhere, not matrix.org

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9972]
The cookie policy for riot.im/whatever is currently hosted here: https://matrix.org/docs/guides/riot_im_cookie_policy

We should host the file (generated from https://github.com/vector-im/policies/blob/master/docs/riot-im/cookie_policy.md) somewhere on about.riot.im instead.

**Comment by lampholder** [comment]
@benparsons is happy for it to stay hosted on matrix.org for now, so downgrading this to a p2

**Comment by jryans** [comment]
The matrix.org copy seems to have vanished, see https://github.com/vector-im/riot-web/issues/10202.

**Comment by turt2live** [comment]
I believe this is mentioned now. If not, it's a bug in the website and not something for us to fix here.
