### ISSUE TITLE
The room selector when creating a community doesn't work

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#9973]
When you want to add several rooms at once in a community, the selector is broken after you've added the first one.
For ex. I want to add all 3 SURF rooms to my SURF community, I type surf in the search field, select room 1, room 1 is added, then type surf again, only rooms 2 and 3 are displayed, I select room 2 and room 1 is added again etc.
In the screenshot below, if I type enter or select the last room left in the drop down, room 1(Scoping) is added again.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8582858/59039133-2465af00-886c-11e9-92d6-7958a0a0c55e.png">

**Comment by t3chguy** [comment]
Can reproduce, seems to still be indexing based on the unfiltered list
