### ISSUE TITLE
Add modifier key to get old up arrow behavior

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9977]
It would be nice to be able to press shift + up arrow to repeat a message again, in addition to just pressing the up arrow allowing you to edit your previous message

**Comment by turt2live** [comment]
I also very much want this, particularly in private chats between me and a bot. I often want to re-run the same command, not edit it.

**Comment by lampholder** [comment]
We should be careful to pick the right modifer for this - ideally one that doesn't already do anything useful regarding navigating around within a text area or editing text.

On my relatively default mac:
- Shift + up selects text line by line
- control + up makes windows fly all around
- option + up does nothing special (cursor still moves with the arrow keys)
- command + up == home (takes us to the very top left of the textbox)

On my relatively default windows machine:
- shift + up selects text line by line
- ctrl + up does nothing (cursor does not move)
- windows + up makes the app fullscreen (who knew?)
- alt + up does nothing (cursor does not move)

On my lubuntu virtualised on my mac:
- control + up does nothing special (cursor still moves with the arrow keys)
- option + up does nothing (cursor doesn't move)
- command + up does nothing (cursor doesn't move)

So does alt/option look like a good bet?

Matthew suggested "Meta", but I confess I don't know for certain what "Meta" actually represents/maps to across various modern OSes :P

**Comment by jryans** [comment]
> Matthew suggested "Meta", but I confess I don't know for certain what "Meta" actually represents/maps to across various modern OSes :P

In web browsers at least, Meta means Command key on macOS, Windows key on Windows.

**Comment by lampholder** [comment]
Aaan of course alt+up moves you between rooms in Riot (I was testing in github's textarea)

**Comment by lampholder** [comment]
We've been bitten by trampling on existing OS/browser/accessibility shortcuts in the past, so this would be good to avoid (esp. for such a power-user feature)

**Comment by t3chguy** [comment]
> shift + up selects text line by line

how about shift + up but only if the composer is empty?
