### ISSUE TITLE
Emojis are slightly too big

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9981]
### Description

Emojis are slightly too big and encroaching on their boundaries.

Chrome:

![image](https://user-images.githubusercontent.com/1342360/59096784-99d88a80-8913-11e9-8ae8-bab2d58e3423.png)

![image](https://user-images.githubusercontent.com/1342360/59096795-a0670200-8913-11e9-8c48-084e47049c35.png)

Firefox:

![image](https://user-images.githubusercontent.com/1342360/59096853-defcbc80-8913-11e9-9536-7f681057842d.png)

![image](https://user-images.githubusercontent.com/1342360/59096858-e6bc6100-8913-11e9-8565-9016a4808e92.png)

Log: not sent

### Version information

- **Platform**: web
- **Browser**: Chrome v73.0.3683.75, Firefox v69.0a1 
- **OS**: Debian stretch/stable
- **URL**: riot.im/develop

**Comment by brainscar** [comment]
I'm having the same issue with the electron client.

**Comment by Angedestenebres** [comment]
I have the same issue after updating my client to the v1.2.2 on Linux Mint :

![Capture d’écran_2019-06-19_19-37-50](https://user-images.githubusercontent.com/21110485/59787464-c56f5380-92c9-11e9-8c4b-a595d60984bd.png)

No matter if it's the first message or the second one from the user.
It happens with all emojis.

**Comment by ara4n** [comment]
This is https://github.com/vector-im/riot-web/issues/9939.  I had a stab at fixing this, but the SBIX rendering on Linux seems to be broken and ignore the normal vertical offset metadata.

**Comment by ara4n** [comment]
closing as a dup, as even though this one has more examples, the other one actually explains the problem.
