### ISSUE TITLE
If "enable_room_list_search" is disabled in Synapse, do not show the room list search form when clicking on the "Add room" icon

### ISSUE THREAD

**Issue by menturion** [vector-im/riot-web#9989]
If "enable_room_list_search" is disabled in Synapse, do not show the room list search form when clicking on the "Add room" icon.

-- Currently, the room search form is shown although "returning an empty list for all queries". 
-- Instead, display directly the "create new room" form, if "enable_room_list_search" is disabled.

**Comment by turt2live** [comment]
We don't show the directory on the + button anymore
