### ISSUE TITLE
Backup banner shows up despite already configured backup

### ISSUE THREAD

**Issue by Valodim** [vector-im/riot-web#9990]
what it says in the title, only happened once on riot-web/electron v1.2.1.

perhaps related: the user info at the top left showed mxid and placeholder avatar, rather than display name and avatar.

debug log coming up

**Comment by jryans** [comment]
I believe this is similar to an issue @babolivier observed recently as well. Our suspicion was that the key backup info hadn't loaded by the time the room was opened, leading the key backup room banner appearing incorrectly.

**Comment by jryans** [comment]
Indeed, looking at the logs, it appears that asking the HS about key backup fails at first (see "Error checking for active key backup"), but then later on it works.

**Comment by jryans** [comment]
Active work in https://github.com/vector-im/riot-web/issues/13404 should address this as well.
