### ISSUE TITLE
Reply button missing on e2ee messages retrieved from other devices

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#9991]
### Description

In an e2ee room, if there are u2d messages that are subsequently retrieved from other devices, hovering over those messages only gives the "..." hamburger menu thing but not the reply button.

I am unable to provide screenshots as the bug seems to have rectified itself since I started filing this issue. Maybe switching tabs away or maybe just time?

### Steps to reproduce

- Create an e2ee room and trigger u2d on one device somehow.
- Force Riot to retrieve the events from other devices.
- Hover over retrieved messages.

### Version information

- **Platform**: web

For the web app:

- **Browser**: qutebrowser v1.6.2 (QtWebEngine (Chromium 65.0.3325.230))
- **OS**: Void Linux
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Thanks for filing this issue! I have spotted a way to reproduce it and should have it fixed shortly.
