### ISSUE TITLE
KDE: No tray icon when minimized

### ISSUE THREAD

**Issue by heini** [vector-im/riot-web#9994]
### Description

After enabling "Close button minimizes only" (freely translated from German UI), when I hit the close button, no icon appears in the systray, but the app keeps running (verified with `ps -ef`).

### Steps to reproduce

- Enable "Close button minimizes only"
- Hit close button

### Version information

- **Platform**: Desktop
- **OS**: Debian Linux, with KDE
- **Version**: 1.2.1

**Comment by erciccione** [comment]
This is probably related to #9897

**Comment by heini** [comment]
OK, let's track it there, then...
